### ISSUE TITLE
SQLAlchemy asyncpg dialect doesn't support mutlihost connection string

### ISSUE THREAD

**Issue by iliadmitriev** [sqlalchemy/sqlalchemy#10004]
### Describe the use case

You should be able to setup DSN connection string for multiple databases.
Like:
```python
url_str = "postgresql+asyncpg://user:password@/dbname?host=host1:5432&host=host2:5432"
engine = create_async_engine(url=url_str)
```

host1:5432 - is main db connection
host2:5432 - fallback connection

### Databases / Backends / Drivers targeted

`postgresql`
`asyncpg` dialect

### Example Use

```python
import asyncio
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

async def async_main() -> None:
    engine = create_async_engine(
        "postgresql+asyncpg://user:password@/dbname?host=host1:5432&host=host2:5432"
    )

    async with engine.begin() as conn:
        res = await conn.execute(
            text("select 1")
        )

    await engine.dispose()

asyncio.run(async_main())
```

### Additional context

This works for `postgrsql+psycopg2`

Section: `Specifying multiple fallback hosts`
https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#specifying-multiple-fallback-hosts

Found old issues in asyncpg Driver
https://github.com/MagicStack/asyncpg/issues/840

**Comment by iliadmitriev** [comment]
> thanks. are you able to provide a PR with test support?

yes, sure

**Comment by iliadmitriev** [comment]
here we go https://github.com/sqlalchemy/sqlalchemy/pull/10005

**Comment by sqla-tester** [comment]
**Ilia Dmitriev** has proposed a fix for this issue in the **main** branch:

**Feature asyncpg dialect doesn't support mutlihost connection string** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4755

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Feature asyncpg dialect doesn't support mutlihost connection string** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4755
