### ISSUE TITLE
Return Type for Dialect.create_connect_args is incorrect

### ISSUE THREAD

**Issue by cancan101** [sqlalchemy/sqlalchemy#10038]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

The type signature for `create_connect_args` reports that it returns `ConnectArgsType` (`Tuple[Tuple[str], MutableMapping[str, Any]]`); however, the example docs indicate that tuple in the first element of the return tuple may be empty:
https://github.com/sqlalchemy/sqlalchemy/blob/6d5cdd1f59415ea8f08efe0f40126b8c384d1125/lib/sqlalchemy/engine/interfaces.py#L1231-L1236
and likewise the default implementation:
https://github.com/sqlalchemy/sqlalchemy/blob/6d5cdd1f59415ea8f08efe0f40126b8c384d1125/lib/sqlalchemy/engine/default.py#L617-L621
In addition, both cases use lists rather than tuples

### To Reproduce

```python
from sqlalchemy.engine.default import DefaultDialect
from typing import Tuple, Dict, Any


class MyDialect(DefaultDialect):
    def create_connect_args(self, url) -> Tuple[Tuple[str], Dict[str, Any]]:
        opts = url.translate_connect_args()
        opts.update(url.query)
        return ((), opts)
```

### Error

```
test.py:9: error: Incompatible return value type (got "tuple[tuple[], Any]", expected "tuple[tuple[str], dict[str, Any]]")  [return-value]
``` 

### Versions

- OS: MacOS
- Python: 3.10.2
- SQLAlchemy: 2.0.17
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.4.1

**Comment by CaselIT** [comment]
Hi,

thanks for reporting. the appropriate type is probably `Tuple[Sequence[str], MutableMapping[str, Any]]`

**Comment by cancan101** [comment]
Yes, that seems correct. Any idea why mypy isn't catching this issue? The current implementation in `DefaultDialect` should be causing an error.

**Comment by CaselIT** [comment]
many internal modules of sqlalchemy that aren't in the user facing interface are untyped or marked as mypy ignore, at least partially

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**fix ConnectArgsType tuple to be variable length** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4762

**Comment by zzzeek** [comment]
> Hi,
> 
> thanks for reporting. the appropriate type is probably `Tuple[Sequence[str], MutableMapping[str, Any]]`

The appropriate type is:

    ``Tuple[Tuple[str, ...], MutableMapping[str, Any]]``

**Comment by CaselIT** [comment]
we have a list in the first arg in multiple places.

Also mike you didn't see https://github.com/sqlalchemy/sqlalchemy/pull/10039

**Comment by zzzeek** [comment]
my patch is abandoned
