### ISSUE TITLE
Patch 1.4.x with improved mapper derivation

### ISSUE THREAD

**Issue by alexjironkin** [sqlalchemy/sqlalchemy#10043]
### Describe the use case

In the process of upgrading `flask_sqlalchemy` we discovered an issue where mapper is not derived inside the session for legacy query API (I am not sure if this is also the case for new style API because codebase is too large to check). In particular we use UNION operator and subsequent query fails to find appropriate mapper for this.

A complete test is described here: https://github.com/pallets-eco/flask-sqlalchemy/issues/1231

Briefly, it appears that `bind_arguments` do not contain a `mapper` and bind resolution using `clause` does work. Upgrading to sqlalchemy 2.0.17 this is resolved. Unfortunately other libraries we have have a hard pin of `sqlalchemy<2` E.g. `sqlalchemy-bigquery` and these guys don't have an ETA for v2 upgrade (https://github.com/googleapis/python-bigquery-sqlalchemy/issues/510)

In particular I traced the fix to be in 2.0.15 (2.0.14 fails the test I have reported in https://github.com/pallets-eco/flask-sqlalchemy/issues/1231). Looking at the comparison between the two tags (https://github.com/sqlalchemy/sqlalchemy/compare/rel_2_0_14...rel_2_0_15) most likely fix was done by @zzzeek to deal with https://github.com/sqlalchemy/sqlalchemy/issues/9805 issue.

Can we port this fix to 1.4.x?

### Databases / Backends / Drivers targeted

I have tested with postgres and sqlite, however I think all backends will be affected.

### Example Use

Unfortunately I was not able to create pure sqlalchemy example, see https://github.com/pallets-eco/flask-sqlalchemy/issues/1231 for usecase

**Comment by zzzeek** [comment]
hi -

this patch doesn't qualify for a backport as it firstly non trivial, changes the behavior of the ORM, and involves a deterministic behavior that arises when one constructs a query of a particular form; if users had this issue within their 1.4 code, it would have been reported within the three years that 1.4 has been generally available.    for applications that are adding new SQLAlchemy code, they should be upgrading to the 2.0 series **first** before doing major new development; 2.0 has been out for six months now.

**Comment by zzzeek** [comment]
additionally there are workarounds for this issue, just emit a `session.flush()` before the query in question is executed

**Comment by zzzeek** [comment]
note I'm only looking at the issue at #9805 which involves flush.    if you have other issues here then I would need a proper [MCVE](http://stackoverflow.com/help/mcve) posted as a standalone script on SQLAlchemy's issue tracker.

**Comment by alexjironkin** [comment]
I don't think this is the issue with flush, just positive side effect of the fix. Let me try to put together minimal example to reproduce the problem next week.

**Comment by zzzeek** [comment]
OK let's do a new issue for that once we have a complete test so I can see what the issue is.
