### ISSUE TITLE
Mapped dataclass integration with `Annotated` is silently skipped at runtime.  should likely raise

### ISSUE THREAD

**Issue by studioph** [sqlalchemy/sqlalchemy#10046]
### Describe the bug

**Expected behavior:**
According to the documentation in, the following example of mapping column declarations using `Annotated` should work at runtime with mapped dataclasses, even if type-checking tools do not analyze it correctly:
```python
from typing import Annotated

from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import registry

intpk = Annotated[int, mapped_column(init=False, primary_key=True)]

reg = registry()


@reg.mapped_as_dataclass
class User:
    __tablename__ = "user_account"
    id: Mapped[intpk]


u1 = User()
```

**Actual behavior:**
```
TypeError: __init__() missing 1 required positional argument: 'id'
```

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#integration-with-annotated

### SQLAlchemy Version in Use

2.0.17

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
from typing import Annotated

from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import registry

intpk = Annotated[int, mapped_column(init=False, primary_key=True)]

reg = registry()


@reg.mapped_as_dataclass
class User:
    __tablename__ = "user_account"
    id: Mapped[intpk]


u1 = User()
```

### Error
```
Traceback (most recent call last):
  File "/home/paul/dev/scratch/sa_test.py", line 316, in <module>
    u1 = User()
TypeError: __init__() missing 1 required positional argument: 'id'
```

### Additional context

Looking through past issues, this seems very similar to #8578. My best guess is that a similar thing is happening here where the dataclass arguments aren't getting passed through as expected.

The example code that immediately follows in the docs does work as expected, but this relies on adding
```
= mapped_column(init=False)
```
to each column, rather than being able to specify it once with the `Annotated` declaration.

**Comment by zzzeek** [comment]
I propose this should raise an error since dataclass arguments inside of Annotated are not supported by pep-681.  what do you think?

**Comment by zzzeek** [comment]
cc @CaselIT

**Comment by CaselIT** [comment]
Id mypy - pylance do not pick it up I think that yes, we should at least warn and possibly raise

**Comment by studioph** [comment]
Just so I'm understanding correctly, the above example was never intended to work even at runtime due to lack of PEP-681 support. Should there be a documentation update to remove/clarify language that seems to imply this should work? If so I can submit a PR for that.

**Comment by zzzeek** [comment]
the exception raise is more important since people are guaranteed to see it.   we could use a PR for that + docs though the exception raise requires looking in the source of orm/properties.py a bit

note that I would *like* to support passing these DC arguments through, that would be straightforward.  it's just it will never work with typing tools and pep-681 authors are very strict about trying to enforce a "single way things should work".

**Comment by zzzeek** [comment]
the docs should include an example of how to work around, that is, mapped_column() with just the DC arguments as you have in your workaround above.

**Comment by zzzeek** [comment]
also the thing we're raising for here is, "any of the DC arguments not at their default".   So we might need some extra logic to do that for all arguments correctly that should likely be part of orm/interfaces/_AttributeOptions

**Comment by studioph** [comment]
Actually, the docs do already have an example using `mapped_column(init=False)` (where I got that from), I think it's just the wording of the first example that should be changed for now (since it currently says `will work perfectly fine at runtime`).

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**accommodate all mapped_column() parameters in Annotated transfer** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4888
