### ISSUE TITLE
Mapper is not passed to get_bind

### ISSUE THREAD

**Issue by alexjironkin** [sqlalchemy/sqlalchemy#10058]
### Describe the bug

This defect is specific for 1.4.x branch and <=2.0.14 and links to CustomSession usage e.g. in Flask-SQLAlchemy (https://github.com/pallets-eco/flask-sqlalchemy/issues/1231). SQLAlchemy 2.0.15+ work as expected 

This seem to be liked in the way SQLALchemy internally works out the mapper based on statement to execute see https://github.com/sqlalchemy/sqlalchemy/issues/10043

Flask-SQLAlchemy relies on mapper to resolve correct bind internally to use.

### SQLAlchemy Version in Use

1.4.48

### DBAPI (i.e. the database driver)

all

### Database Vendor and Major Version

n/a

### Python Version

3.9

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import create_engine, select, union, func
from sqlalchemy.orm import sessionmaker, Session as sa_orm_Session
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, Integer, String

from unittest.mock import patch

def test_get_bind_args():
    engine = create_engine("sqlite:///")
    Session = sessionmaker(engine)
    Base = declarative_base()

    class UserType1(Base):
        __tablename__ = "user_type_1"
        id = Column(Integer, primary_key=True)
        user_type = Column(Integer, nullable=False)
        name = Column(String, nullable=False)

    class UserType2(Base):
        __tablename__ = "user_type_2"
        id = Column(Integer, primary_key=True)
        user_type = Column(Integer, nullable=False)
        name = Column(String, nullable=False)

    with Session() as session:
        Base.metadata.create_all(engine)

        session.add(UserType1(id=1, user_type=1, name="alice"))
        session.add(UserType1(id=2, user_type=1, name="bob"))
        session.add(UserType2(id=2, user_type=2, name="charlie"))
        session.commit()

        query_1 = select(
            func.count(UserType1.name).label("count"),
            UserType2.user_type.label("user_type"),
        ).group_by(UserType2.user_type)

        assert session.execute(query_1).all()

        query_2 = select(
            func.count(UserType2.name).label("count"),
            UserType2.user_type.label("user_type"),
        ).group_by(UserType2.user_type)

        assert session.execute(query_2).all()

        with patch.object(
            sa_orm_Session, "get_bind", wraps=session.get_bind
        ) as patched:
            union_query = union(query_1, query_2)

            assert len(session.query(union_query.subquery()).all()) == 2

            patched.assert_called_once()

            assert "mapper" in patched.call_args.kwargs
```

### Error

```
AssertionError: assert 'mapper' in {'clause': <sqlalchemy.sql.selectable.Select object at 0x7f2ccfc59760>}`
```

**Comment by zzzeek** [comment]
hi - 

it's very unusual to pass a union directly to Query like that, and it's not clear this would have worked in 1.3 at all.

Therefore use new-style queries, the bind can be passed directly:

```py
 union_query = union(query_1, query_2)
 result = session.execute(select(union_query), bind_arguments={"bind": desired_mapper})
```


I will add a test case for this under 2.0

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add tests for #10058** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4765

**Comment by alexjironkin** [comment]
I kept the test the same syntax for 1.4 and 2.0 for clarity, but this happens with older style querying `query_1.union(query_2)` as well. What can we do to get this fixed in 1.4? Otherwise I'm not really sure about the point of the whole exercise, given we know it was fixed in 2.0.15 already (thank you btw :)). 

I do wish we could upgrade to 2.0 even though it's 6 month old and I realise it's a stretch to have support for older version, but the reality is that many other dependencies pin to <2.0 as the case with Google's BigQuery extension and our hands are tied.

**Comment by zzzeek** [comment]
> I kept the test the same syntax for 1.4 and 2.0 for clarity, but this happens with older style querying `query_1.union(query_2)` as well. 

dont use the older style of querying for new code

> What can we do to get this fixed in 1.4? 

this is not a regression or something that affects current in-production code so it's not eligible for 1.4

> Otherwise I'm not really sure about the point of the whole exercise, given we know it was fixed in 2.0.15 already (thank you btw :)).

I wanted to know the use case so that I can add test support for it, so that it doesnt break again, so thanks for that

> I do wish we could upgrade to 2.0 even though it's 6 month old and I realise it's a stretch to have support for older version, but the reality is that many other dependencies pin to <2.0 as the case with Google's BigQuery extension and our hands are tied.

you have a workaround, so use that

**Comment by zzzeek** [comment]
for legacy Query under 1.4 or 2.0, apply this workaround

```py
        union_query = union(query_1, query_2)
        from sqlalchemy import inspect

        subq = union_query.subquery()


        q = session.query(subq)
        q._propagate_attrs = q._propagate_attrs.union({"plugin_subject": inspect(UserType1), "compile_state_plugin": "orm"})

        q.all()
```

**Comment by alexjironkin** [comment]
Many thanks for the workaround, tested in various scenarios and it seems to work.
