### ISSUE TITLE
Local connection pools do not work with multiprocessing

### ISSUE THREAD

**Issue by mliu-aqtc** [sqlalchemy/sqlalchemy#10077]
### Describe the bug

According to this documentation, it should be possible to pass an engine to a multiprocessing pool, as long as the connections are properly disposed. However, the documentation assumes that the engine is a global variable and can be pickled. I am attempting to pass an engine that is a local variable to a process pool, and it is resulting in a pickling error, which looks like it may be because of some unpickleable local functions in the engine.

The error looks like: "Can't pickle local object 'create_engine.<locals>.connect'"

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/pooling.html#using-connection-pools-with-multiprocessing-or-os-fork

### SQLAlchemy Version in Use

1.4.46

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

cockroachdb 22.2.5

### Python Version

3.10

### Operating system

linux

### To Reproduce

```python
import concurrent.futures
import multiprocessing as mp
import sqlalchemy

def foo(engine):
    return "success"

def main():
    engine = sqlalchemy.create_engine("<URL>")

    engine.dispose(close=True)
    with concurrent.futures.ProcessPoolExecutor(mp_context=mp.get_context("spawn")) as executor:
        future = executor.submit(foo, engine)

    for future in concurrent.futures.as_completed([future]):
        print(future.result())

if __name__ == "__main__":
    main()
```

### Error

```
cls = <class 'multiprocessing.reduction.ForkingPickler'>, obj = <concurrent.futures.process._CallItem object at 0x7fd3db43bf10>, protocol = None

    @classmethod
    def dumps(cls, obj, protocol=None):
        buf = io.BytesIO()
>       cls(buf, protocol).dump(obj)
E       AttributeError: Can't pickle local object 'create_engine.<locals>.connect'
```

**Comment by CaselIT** [comment]
Hi,

I don't think this is worth fixing.
Either make the engine a module level variable, or acquire a new engine in the pool method.

Since even when passing the same engine you will need to dispose all connections, creating a new engine is basically equivalent.

**Comment by zzzeek** [comment]
technically the first connect of an engine runs a few queries to set up the dialect but this is generally negligible.      The bigger reason pickling (without a special pickling function to omit things) would be not really viable is the SQL query cache, which is huge and you definitely don't want to send that through a serialized pipe.

**Comment by mliu-aqtc** [comment]
> Either make the engine a module level variable, or create a new engine in the pool method.

The latter is my current workaround. However, I the initial engine creation comes with several configurations, eg setting `pool_pre_ping=True`, which I would need to copy over to create the new engine. For my use case, I am not able to provide the same configuration when recreating the engine. Is there a way to recreate the engine with the same configuration using only the existing engine?

**Comment by zzzeek** [comment]
there's ways to do that, though I dont know of any way to carry over event handling functions, if any have been added to that engine (like end-user before_cursor_execute(), etc).   so it depends on if you are doing this for a library that takes in *any* engine from anywhere and promises to keep it identical, that would be very difficult.

so i would need some constraints on what you actually need.

**Comment by zzzeek** [comment]
and if this were for a fully generic library, then I'd have the library be passed a function that creates an engine, not an actual engine.

**Comment by zzzeek** [comment]
(or one that *returns* an engine that's already global)

**Comment by mliu-aqtc** [comment]
>and if this were for a fully generic library, then I'd have the library be passed a function that creates an engine, not an actual engine.

This is an option as well. Would take a bit of refactoring, but I think it makes the most sense. Thanks!

**Comment by zzzeek** [comment]
this is what that looks like

```py
import concurrent.futures
import multiprocessing as mp
import sqlalchemy

engine = sqlalchemy.create_engine("sqlite://")

def get_my_engine():
    return engine

def foo(get_engine):
    engine = get_engine()
    engine.dispose(close=False)
    return "success"

def main():

    with concurrent.futures.ProcessPoolExecutor(mp_context=mp.get_context("spawn")) as executor:
        future = executor.submit(foo, get_my_engine)

    for future in concurrent.futures.as_completed([future]):
        print(future.result())

if __name__ == "__main__":
    main()
```

**Comment by zzzeek** [comment]
with the above approach, by skipping the pickling, we retain the full SQL cache and all the type handlers cached by the dialect across the process boundary, without having to actually serialize and send all of that complex data over the pipe.
