### ISSUE TITLE
Use of session without ORM results in `'NoneType' object has no attribute 'mapper'` AttributeError

### ISSUE THREAD

**Issue by stephenfin** [sqlalchemy/sqlalchemy#10098]
### Describe the bug

I don't have the terminology to describe this bug, so hopefully the reproducer below explains what the issue is. For context, the reproducer is a simplified version of code from [OpenStack Placement](https://github.com/openstack/placement/blob/master/placement/objects/resource_provider.py#L494-L523). I _suspect_ that the issue is from [this code](https://github.com/sqlalchemy/sqlalchemy/blob/f5eba15eb7697107c30d0b8110440c7f1d7a8d03/lib/sqlalchemy/orm/query.py#L589-L596) but I don't currently understand what that code is really doing so what do I know :sweat_smile: 

### SQLAlchemy Version in Use

2.0.18

### DBAPI (i.e. the database driver)

pysqlite

### Database Vendor and Major Version

SQLite 3.40.1

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
import sqlalchemy as sa
from sqlalchemy import orm

BASE = orm.declarative_base()


class Message(BASE):
    __tablename__ = 'messages'

    id = sa.Column(sa.Integer, primary_key=True)
    parent_message_id = sa.Column(sa.Integer)
    message = sa.Column(sa.String)


def main():
    # create database
    engine = sa.create_engine('sqlite://')
    BASE.metadata.create_all(engine)

    # create test messages
    Session = orm.sessionmaker(bind=engine)
    session = Session()
    for x in range(10):
        message = Message(message='Hello, world')
        session.add(message)
        session.commit()

    # for each message, if the parent_message_id column is unset, set it to the
    # value of id column (i.e. the parent is itself)

    subq_1 = session.query(Message.__table__.c.id)
    subq_1 = subq_1.filter(Message.__table__.c.parent_message_id.is_(None))
    subq_1 = subq_1.subquery(name="subq_1")

    subq_2 = sa.select(subq_1.c.id).select_from(subq_1).scalar_subquery()

    upd = Message.__table__.update().where(Message.__table__.c.id.in_(subq_2))
    upd = upd.values(parent_message_id=Message.__table__.c.id)

    res = session.execute(upd)

    print(res.rowcount)


if __name__ == '__main__':
    main()
```

### Error

```
Traceback (most recent call last):
  File "/tmp/sqlalchemy-bug/test.py", line 46, in <module>
    main()
  File "/tmp/sqlalchemy-bug/test.py", line 40, in main
    res = session.execute(upd)
          ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/sqlalchemy-bug/.venv/lib64/python3.11/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/sqlalchemy-bug/.venv/lib64/python3.11/site-packages/sqlalchemy/orm/session.py", line 2120, in _execute_internal
    ) = compile_state_cls.orm_pre_session_exec(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/sqlalchemy-bug/.venv/lib64/python3.11/site-packages/sqlalchemy/orm/bulk_persistence.py", line 659, in orm_pre_session_exec
    bind_arguments["mapper"] = plugin_subject.mapper
                               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mapper'
```

**Comment by zzzeek** [comment]
this is another #9805 regression

**Comment by zzzeek** [comment]
you know how it is when a user is like, "this has to work!" and you are like "sure, but im not really sure what will happen if i make it work like that..."  well here we are :)

**Comment by zzzeek** [comment]
it's a little odd the codepaths are working out that way here

**Comment by stephenfin** [comment]
For anyone who stumbles upon this before the regression is resolved, I can work around this by migrating from the legacy [`Session.query()`](https://docs.sqlalchemy.org/en/20/orm/queryguide/query.html) to [`select()`](https://docs.sqlalchemy.org/en/20/core/selectable.html#sqlalchemy.sql.expression.select). As far as I can tell, this is functionally equivalent and the preferred way to do things in 2.x.

Using `Session.query()`:

```python
subq_1 = session.query(Message.__table__.c.id)
subq_1 = subq_1.filter(Message.__table__.c.parent_message_id.is_(None))
subq_1 = subq_1.subquery(name="subq_1")

subq_2 = sa.select(subq_1.c.id).select_from(subq_1).scalar_subquery()
```
Using `Session.query()` (simplified to remove the redundant subquery):

```python
subq = session.query(Message.__table__.c.id)
subq = subq.filter(Message.__table__.c.parent_message_id.is_(None))
subq = subq.scalar_subquery()
```

Using `select()`:

```python
subq = sa.select(Message.__table__.c.id)
subq = subq.filter(Message.__table__.c.parent_message_id.is_(None))
subq = subq.scalar_subquery()
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**test for None plugin_subject** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4773
