### ISSUE TITLE
PostgreSQL CITEXT case-insensitive comparison not working in psycopg dialect due to ::VARCHAR cast

### ISSUE THREAD

**Issue by jtbeach** [sqlalchemy/sqlalchemy#10096]
### Describe the bug

I've used CITEXT quite a lot for fields where I want to do case-insensitive comparison. I noticed that this landed recently in SQLAlchemy so thought I would try out.

Whilst the DDL was rendered correctly for the table, etc. when I try to do a case-insensitive query, the query is *case sensitive* because of the `::VARCHAR` cast added to the bind param.

For the example below, the rendered query was:

```
SELECT test.id, test.email
FROM test
WHERE test.email = %(email_1)s::VARCHAR
2023-07-12 17:49:36,083 INFO sqlalchemy.engine.Engine [generated in 0.00014s] {'email_1': 'Testuser@example.com'}
2023-07-12 17:49:36,085 INFO sqlalchemy.engine.Engine ROLLBACK
```

Unfortunately the `::VARCHAR` added to the email_1 bind parameter makes the comparison case-sensitive, which default the purpose of using CITEXT in Sqlalchemy in the first place. I wonder whether this is a particular issue with the psycopg dialect or it affects all psycopg dialects.

If I switch to using the `psycopg2` dialect, it works as expected and the query rendered is:

```
SELECT test.id, test.email
FROM test
WHERE test.email = %(email_1)s
```

See https://www.postgresql.org/docs/current/citext.html -- From the text "If you'd like to match case-sensitively, you can cast the operator's arguments to text." -- so the cast to VARCHAR is causing a **case-sensitive** comparison.

### SQLAlchemy Version in Use

2.0.18

### DBAPI (i.e. the database driver)

psycopg

### Database Vendor and Major Version

PostgreSQL 15

### Python Version

3.10

### Operating system

OSX

### To Reproduce

```python
from uuid import UUID

from sqlalchemy.dialects.postgresql import CITEXT
from sqlalchemy import create_engine, text, select
from sqlalchemy.orm import (
    DeclarativeBase,
    MappedAsDataclass,
    Mapped,
    mapped_column,
    Session,
)


class Base(MappedAsDataclass, DeclarativeBase):
    pass


class Test(Base, kw_only=True):
    __tablename__ = "test"

    id: Mapped[UUID] = mapped_column(
        init=False,
        default=None,
        server_default=text("gen_random_uuid()"),
        primary_key=True,
    )
    email: Mapped[str] = mapped_column(CITEXT)


engine = create_engine("postgresql+psycopg://postgres@localhost/test")
with engine.begin() as conn:
    conn.execute(text("CREATE EXTENSION IF NOT EXISTS citext"));
    Base.metadata.create_all(conn)


with Session(engine, expire_on_commit=False) as write_sess, write_sess.begin():
    x = Test(email="testuser@example.com")  # Lowercase
    write_sess.add(x)

with Session(engine, expire_on_commit=False) as read_sess:
    stmt = select(Test).filter_by(email="Testuser@example.com")  # Uppercase
    res = read_sess.scalars(stmt).one()
```

### Error

```
Traceback (most recent call last):
  File "/Users/joelbeach/git/blaze/backend/python/apps/cie/test.py", line 42, in <module>
    res = read_sess.scalars(stmt).one()
  File "/Users/joelbeach/Library/Caches/pypoetry/virtualenvs/cie-yfnr8umH-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1822, in one
    return self._only_one_row(
  File "/Users/joelbeach/Library/Caches/pypoetry/virtualenvs/cie-yfnr8umH-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 760, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required
```

**Comment by zzzeek** [comment]
this is very strange because we have exactly this test in the suite, yet ours passes and this one does not.  still looking

**Comment by zzzeek** [comment]
because are test was not written properly

**Comment by zzzeek** [comment]
yes sorry, this type was recently added and is entirely not working.  will be in 2.0.19

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure CITEXT is not cast as VARCHAR** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4771
