### ISSUE TITLE
object not in collection warning not emitted for pending backref members

### ISSUE THREAD

**Issue by Goryaa** [sqlalchemy/sqlalchemy#10090]
### Describe the bug

A bi-directional relationship will not be kept in sync if the many side is unloaded, and the one side sets a value. However, if the many side is loaded, then they stay in sync. I am not sure which is intended, but it seems odd that the loading strategy can have this effect. Exists in 2.0.18, and on 1.4 this inconsistency only occurs with `cascade_backref=False`.

### SQLAlchemy Version in Use

1.4.42, 2.0.18

### DBAPI (i.e. the database driver)

sqlite3

### Database Vendor and Major Version

SQLite

### Python Version

3.9

### Operating system

Windows

### To Reproduce

```python
from sqlalchemy import ForeignKey, create_engine, Integer, Column, select
from sqlalchemy.orm import Session, relationship, declarative_base, selectinload, lazyload

Base = declarative_base()


class Parent(Base):
    __tablename__ = "parent"

    id = Column(Integer, primary_key=True)

    children = relationship('Child', cascade_backrefs=False, back_populates="parent")


class Child(Base):
    __tablename__ = "child"

    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey("parent.id"), index=True)

    parent = relationship('Parent', back_populates="children")


engine = create_engine("sqlite://", echo=False)
Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)


with Session(engine) as session:
    session.add(Parent())
    session.commit()


with Session(engine) as session:
    p = session.scalar(select(Parent).options(lazyload(Parent.children)))

    c = Child()
    c.parent = p

    print('When Unloaded:', c in p.children)  # False

with Session(engine) as session:
    p = session.scalar(select(Parent).options(selectinload(Parent.children)))

    c = Child()
    c.parent = p

    print('When Loaded:', c in p.children)  # True
```

### Error

*

**Comment by zzzeek** [comment]
unclear, this seems to be intentionally abusing the API a bit.  both examples are not "useful".  take the second example:

```py
with Session(engine) as session:
    p = session.scalar(select(Parent).options(selectinload(Parent.children)))

    c = Child()
    c.parent = p

    print("When Loaded:", c in p.children)  # True

    session.flush()
    session.expire_all()

    print("but then we flushed and reloaded...", c in p.children)

```

output includes a warning, and your object is then *not* in the collection:

```py
$ python test3.py 
When Unloaded: False
When Loaded: True
/mnt/photon_home/classic/dev/sqlalchemy/test3.py:58: SAWarning: Object of type <Child> not in session, add operation along 'Parent.children' will not proceed
  session.flush()
but then we flushed and reloaded... False

```

so this seems like more of a "warn" situation

**Comment by zzzeek** [comment]
specifically it's lost within the flush and there's no warning

```
    print("When Unloaded:", c in p.children)  # False
```

vs

```
    with session.no_autoflush:
        print("When Unloaded:", c in p.children)  # True
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**cascade fixes revealed by the removal of cascade_backrefs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4770

**Comment by zzzeek** [comment]
OK so with the change coming, let's assume test case as:

```py
with Session(engine) as session:
    p = session.scalar(select(Parent).options(lazyload(Parent.children)))

    print("CASE ONE.  LAZYLOAD")
    c = Child()
    c.parent = p

    print("When Unloaded:", c in p.children)  # True

with Session(engine) as session:
    p = session.scalar(select(Parent).options(selectinload(Parent.children)))

    print("CASE TWO.  SELECTINLOAD")
    c = Child()
    c.parent = p

    print("When Loaded:", c in p.children)  # True

    print("FLUSHING FOR CASE TWO, AS WOULD ALWAYS BE THE CASE WHEN MUTATING")
    session.flush()

```

you will get an equivalent warning in both cases:

```
CASE ONE.  LAZYLOAD
/mnt/photon_home/classic/dev/sqlalchemy/test3.py:49: SAWarning: Object of type <Child> not in session, add operation along 'Parent.children' will not proceed (This warning originated from the Session 'autoflush' process, which was invoked automatically in response to a user-initiated operation.)
  print("When Unloaded:", c in p.children)  # True
When Unloaded: False
CASE TWO.  SELECTINLOAD
When Loaded: True
FLUSHING FOR CASE TWO, AS WOULD ALWAYS BE THE CASE WHEN MUTATING
/mnt/photon_home/classic/dev/sqlalchemy/test3.py:61: SAWarning: Object of type <Child> not in session, add operation along 'Parent.children' will not proceed
  session.flush()

```

this warning will hopefully encourage that `session.add(c)` be added to resolve the warning.

**Comment by CodeMouse92** [comment]
This seems to have some odd side effects, as we've started getting the warnings mentioned by @zzzeek in that last comment. However, we carefully stepped through and confirmed that we only have the one session in each of the failing tests, and we are explicitly adding each item being created. Yet, when adding **existing** (and confirmed existing) object to new or existing objects in one-to-many relationships, we get these warnings _unreliably_, with various ephemeral test and coverage failures. Rerunning the exact same tests on the exact same system produces varying warnings. We've had to pin to 2.0.18 as a result.

Be advised, I'm working on proprietary code, and I'm up against a pressing deadline. However, this change needs to be inspected more closely, as it is having unexpected effects on otherwise functional code.

**Comment by zzzeek** [comment]
> Probably better to create a new issue for this

not without an [MCVE](http://stackoverflow.com/help/mcve).  I dont think there is any bug here.

**Comment by zzzeek** [comment]
hi @CodeMouse92 -

the actual warning itself is not emitted without effect; this warning occurs when the unit of work traverses a collection and locates an object that is absent from the session, and the object is then actively skipped.   previously, the object wasn't detected at all in some cases, so while it was still skipped, there would be no warning.

The demonstration program below, which I would encourage you to try out, illustrates the bug fix:

```py
from __future__ import annotations

from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

class Base(DeclarativeBase):
    pass


class A(Base):
    __tablename__ = 'a'

    id: Mapped[int] = mapped_column(primary_key=True)
    data: Mapped[str]
    bs: Mapped[list[B]] = relationship(back_populates='a')

class B(Base):
    __tablename__ = 'b'

    id: Mapped[int] = mapped_column(primary_key=True)
    data: Mapped[str]
    b_id: Mapped[int] = mapped_column(ForeignKey("a.id"))
    a: Mapped[A] = relationship(back_populates='bs')


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

with Session(e) as sess:
    b1 = B(data='b1')
    a1 = A(data='a1')
    sess.add(a1)

    # when this flush is present, the warning goes away in 2.0.18, but b1 is
    # still **not** flushed.  in 2.0.19 the warning is correctly emitted whether or not this 
    # flush is present
    sess.flush()

    b1.a = a1
    sess.commit()

```

It should not be surprising that by adding deeper detection for a subtle case of an object being skipped from a flush operation, some existing programs that most likely work perfectly fine would suddenly see this warning, and in order to mitigate would need adjustment to actively add the object(s) reported in the warning to the `Session`, or to ensure they aren't associated with other objects that are being flushed, or to delay the progression of the flush using [no_autoflush](https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.no_autoflush) as typically it's a bit of an antipattern to have connected object structures at flush time where part of the structure is flushed and part of it is still transient.    

i've done another pass over the code and I can say that the warning is definitive - there is no codepath where the object(s) for which the warning is emitted are either (a) not actually part of a target collection or (b) are still flushed anyway, within that flush.    The object is definitely present in the (unloaded) collection as a pending object and it is definitely not flushed, which is what this warning intends to show.    If there is a bug in the underlying collection logic, like the "pending collection" structure, that is possible however this is all code that's been working the same way for over a decade.   It is much more likely that your program simply has some objects that don't need to be flushed at this point for the program to work correctly, and the warning is just letting you know that they're present and being skipped (as they were before).

**Comment by CodeMouse92** [comment]
I understand the fix. That is not the problem here. In my situation, the theoretical `b1` already exists in the database, having been committed by a now-closed session altogether. It is being added to `a1`, which has been added. Yet, when running the test code that adds the already existing `b1` object to the new (or modified, already existing) `a1`, I get these warnings:

```
tests/crud/profile/test_profile.py::test_create_profile
  /home/.../manage_db/operations.py:37: SAWarning: Object of type <Profile> not in session, add operation along 'PracticeArea.profiles' will not proceed
    session.commit()

tests/crud/profile/test_profile.py::test_create_profile
  /home.../manage_db/operations.py:37: SAWarning: Object of type <Profile> not in session, add operation along 'PracticeLevel.profiles' will not proceed
    session.commit()

tests/crud/profile/test_profile.py::test_update_profile
  /home/.../manage_db/operations.py:81: SAWarning: Object of type <Profile> not in session, add operation along 'PracticeLevel.profiles' will not proceed
    session.commit()

tests/crud/profile/test_profile.py::test_update_profile
  /home/.../manage_db/operations.py:81: SAWarning: Object of type <Profile> not in session, add operation along 'PracticeArea.profiles' will not proceed
    session.commit()
```

```
# fake_populated_session creates a database pre-populated with data,
# and creates a new, unique session which is passed to the operations seen below.
# We've confirmed this carefully by stepping through the entire stack with pdb
# and checking id(session). Similarly, `generate_profile` ONLY selects from existing
# prepopulated practice_area and practice_level items. This too has been verified
# via pdb and manual examination of database.
def test_create_profile(fake_populated_session: Session) -> None:
    new_profile = generate_profile(fake_populated_session)
    new_profile_create = schema.ProfileCreate(
        # ...
        practice_area_pk=new_profile.practice_area_pk,
        practice_level_pk=new_profile.practice_level_pk,
    )

    # this raises the warnings
    result = crud.create_profile(
        new_profile_create, session=fake_populated_session
    )
    # ...

####

def create_profile(
    profile: schema.profile.ProfileCreate, *, session: Session
) -> models.profile.Profile:
    # this function handles unrelated logic, but ultimately returns result of `session.get(model, pk)`
    practice_area: models.PracticeArea = queries.get_by_pk(
        session=session,
        pk=profile.practice_area_pk,
        model=models.practice_area.PracticeArea,
        # ...
    )
   
    # ...same...
    practice_level: models.PracticeLevel = queries.get_by_pk(
        session=session,
        pk=profile.practice_level_pk,
        model=models.practice_level.PracticeLevel,
        # ...
    )

    model = models.profile.Profile(
        # ...
        practice_area=practice_area,
        practice_level=practice_level,
    )
    return operations.create_record(
        record=model, session=session,
    )

####

def create_record(
    *,
    record: TModel,
    session: Session,
    # ...
) -> TModel:
    session.add(record)
    session.commit()
    session.refresh(record)

    # ...
    return record
```

Be advised, autoflush being true or false and/or manually flushing makes no difference whatsoever; I just checked.

**Comment by zzzeek** [comment]
> I understand the fix. That is not the problem here. In my situation, the theoretical `b1` already exists in the database, having been committed by a now-closed session altogether. It is being added to `a1`, which has been added. Yet, when running the test code that adds the already existing `b1` object to the new (or modified, already existing) `a1`, I get these warnings:

by associating these objects together, one persistent and one transient or detached, assuming there is a back-populates between these two objects, the ORM is not sure that you in fact *dont* want to persist the "a1" object in the event that a flush occurs.   As in my example above, "a1" will not be persisted if you see this  warning (it might be persisted later, or through some other means, but that's out of scope for the warning).


> This is the best I can do to show you the code. I recognize this is not quite an MVCE, but as I said, I'm up against a bear of a deadline.

sure, pin to 2.0.18 for now.

> As you can clearly see, the situation described is absolutely not present, so the warning is not valid. What's further...

I can't really go off of a code fragment without a runnable context, there could be all kinds of things going on, but if you change this warning to an exception, then use pdb to inspect the condition, you will see that the object in question is not part of the Session and does not get flushed; you can also do `where` inside of pdb and see where this flush is happening.  it might be an autoflush that is not expected.  if you do see an INSERT or UPDATE somehow occur for the object in the same flush for which this warning is emitted, that's what should be not possible and is what a short self contained test would illustrate.   

> 
> > It is more likely that your program simply has some objects that don't need to be flushed at this point for the program to work correctly, and the warning is just letting you know that they're present and being skipped (as they were before).
> 
> This is not the case, as tests will variably _fail_ as a result of the dropped commits, and/or coverage will drop off, indicating that the actual _behavior_ of the code is different in 2.019 vs. 2.0.18.

OK so that is totally not expected, so I need a self-contained, succinct demonstration of that.    If the issue is as egregious as is being claimed, it will be reported soon enough by someone else as well.

**Comment by CodeMouse92** [comment]
If I am able to scrounge up the time to get an MVCE put together at some point, I will. I do expect this will get reported by someone else before long, though, as the use pattern here is pretty typical: a many-to-one relationship. Incidentally, it also occurs wherein both objects already exist on the database, but the relationship is being created; that's the `update_profile` test.

The only other thing I can wonder is, does SQLAlchemy now expect the _persistent_ object to be added again too with `session.add()`? Up to now, it's been enough to acquire the object from the session, modify it, and then `commit()` and `refresh()` on the same session.

**Comment by zzzeek** [comment]
> 
> The only other thing I can wonder is, does SQLAlchemy now expect the _persistent_ object to be added again too with `session.add()`? 

not if it's persistent, no, it's already in the session if persistent.  if you mean detached, and you have added this object to a one-to-many collection, then maybe, sure.  why else add it to a collection if you dont want that change to take place.

> 
> Luckily, I already checked for exactly that, and all the objects showed as being part of the session. That's the point my coworker and I were about ready to check into the funny farm.

OK I need to see **exactly** how you are checking that.  the warning is emitted directly after this test:

```py
    not uowcommit.session._contains_state(child)
```

can you please report the result of:

```py

obj = <my object that I know is in the session>
state = inspect(obj)
session._contains_state(child)
```

the `_contains_state` method is this:

    def _contains_state(self, state: InstanceState[Any]) -> bool:
        return state in self._new or self.identity_map.contains_state(state)


this method is literally the same one that is called when you ask `obj in session`.

so there is absolutely no way if you are looking at the correct object and the correct session that this warning could be emitted if that test is true.

A complete MCVE for the code you've shared is below.    obviously it produces no warnings or surprises, so see if you can modify this to show the condition you are seeing.

```py
from __future__ import annotations

from typing import Any

from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session


class Base(DeclarativeBase):
    pass


class PracticeArea(Base):
    __tablename__ = "practice_area"
    id: Mapped[int] = mapped_column(primary_key=True)
    profiles: Mapped[list[Profile]] = relationship(
        back_populates="practice_area"
    )


class PracticeLevel(Base):
    __tablename__ = "practice_level"
    id: Mapped[int] = mapped_column(primary_key=True)

    profiles: Mapped[list[Profile]] = relationship(
        back_populates="practice_level"
    )


class Profile(Base):
    __tablename__ = "profile"

    id: Mapped[int] = mapped_column(primary_key=True)
    practice_area_pk: Mapped[int] = mapped_column(
        ForeignKey("practice_area.id")
    )
    practice_level_pk: Mapped[int] = mapped_column(
        ForeignKey("practice_level.id")
    )

    practice_area: Mapped[PracticeArea] = relationship(
        back_populates="profiles"
    )
    practice_level: Mapped[PracticeLevel] = relationship(
        back_populates="profiles"
    )


class ProfileCreate:
    def __init__(self, practice_area_pk, practice_level_pk):
        self.practice_area_pk = practice_area_pk
        self.practice_level_pk = practice_level_pk


def get_by_pk(*, session: Session, pk: Any, model: type[Base]) -> Any:
    obj = session.get(model, pk)
    assert obj is not None
    return obj


def test_create_profile(fake_populated_session: Session) -> None:
    new_profile = Profile(
        practice_area=PracticeArea(), practice_level=PracticeLevel()
    )
    fake_populated_session.add(new_profile)
    fake_populated_session.flush()

    new_profile_create = ProfileCreate(
        # ...
        practice_area_pk=new_profile.practice_area_pk,
        practice_level_pk=new_profile.practice_level_pk,
    )

    result = create_profile(new_profile_create, session=fake_populated_session)
    # ...
    print(f"result: {result}")


def create_profile(profile: ProfileCreate, *, session: Session) -> Profile:
    practice_area: PracticeArea = get_by_pk(
        session=session,
        pk=profile.practice_area_pk,
        model=PracticeArea,
        # ...
    )

    practice_level: PracticeLevel = get_by_pk(
        session=session,
        pk=profile.practice_level_pk,
        model=PracticeLevel,
        # ...
    )

    model = Profile(
        # ...
        practice_area=practice_area,
        practice_level=practice_level,
    )
    return create_record(
        record=model,
        session=session,
    )


####


def create_record(
    *,
    record: Base,
    session: Session,
    # ...
) -> Any:
    session.add(record)
    session.commit()
    session.refresh(record)

    # ...
    return record


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

with Session(e) as sess:
    test_create_profile(sess)

```

**Comment by CodeMouse92** [comment]
I've dropped to `pdb` as follows:

```
def create_profile(
    profile: schema.profile.ProfileCreate, *, session: Session
) -> models.profile.Profile:
    practice_area: models.PracticeArea = queries.get_by_pk(
        session=session,
        pk=profile.practice_area_pk,
        model=models.practice_area.PracticeArea,
        run_hooks=False,
        as_reference=True,
    )

    practice_level: models.PracticeLevel = queries.get_by_pk(
        session=session,
        pk=profile.practice_level_pk,
        model=models.practice_level.PracticeLevel,
        run_hooks=False,
        as_reference=True,
    )

    model = models.profile.Profile(
        name=profile.name,
        pronouns=profile.pronouns,
        personal_quote=profile.personal_quote,
        about_summary=profile.about_summary,
        flair=profile.flair,
        highlights=profile.highlights,
        practice_area=practice_area,
        practice_level=practice_level,
    )
    import pdb; pdb.set_trace()
    return operations.create_record(
        record=model, session=session, index_on=model
    )
```

From there, I've run `interact` and did the following:

```
>>> session
<sqlalchemy.orm.session.Session object at 0x7f0629d68790>
>>> from sqlalchemy import inspect
>>> practice_area
<PracticeArea 1>
>>> state = inspect(practice_area)
>>> session._contains_state(state)
True
>>> practice_level
<PracticeLevel 7>
>>> state = inspect(practice_level)
>>> session._contains_state(state)
True
>>> practice_area in session
True
>>> practice_level in session
True
```

Just in case something else is going on, I also dropped into `pdb` this way instead:

```python
def create_record(
    *,
    record: TModel,
    session: Session,
    # ...
) -> TModel:
    session.add(record)
    import pdb; pdb.set_trace()
    session.commit()
    session.refresh(record)

    # ...
    return record
``

```
>>> session
<sqlalchemy.orm.session.Session object at 0x7faf01c3cc70>
>>> from sqlalchemy import inspect
>>> state = inspect(record.practice_area)
>>> session._contains_state(state)
True
>>> record.practice_area
<PracticeArea 1>
>>> state = inspect(record.practice_level)
>>> session._contains_state(state)
True
>>> record.practice_level
<PracticeLevel 7>
>>> state = inspect(record)
>>> session._contains_state(state)
True
>>> record in session
True
>>> record
<Profile None (Rachel Burns)>
```

In both cases, after dropping out of interact via `Ctrl+D`, and then continuing with `c`, I got:

```
tests/crud/profile/test_profile.py::test_create_profile
  /home/.../manage_db/operations.py:38: SAWarning: Object of type <Profile> not in session, add operation along 'PracticeArea.profiles' will not proceed
    session.commit()

tests/crud/profile/test_profile.py::test_create_profile
  /home/.../manage_db/operations.py:38: SAWarning: Object of type <Profile> not in session, add operation along 'PracticeLevel.profiles' will not proceed
    session.commit()

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by zzzeek** [comment]
in fact I can modify my program above and do something that I would expect to cause problems surrounding your "fake_populated_session" fixture that produces this result; populate the "fake" `Profile` but don't flush it.  this would explain why perhaps you see "your object is in the session" but that's not the object the warning is talking about, in this case it would be talking about that "fake" `Profile` object.   The warnings are produced in this case, they only emit as of 2.0.19, and they are correct:

```py
from __future__ import annotations

from typing import Any

from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session


class Base(DeclarativeBase):
    pass


class PracticeArea(Base):
    __tablename__ = "practice_area"
    id: Mapped[int] = mapped_column(primary_key=True)
    profiles: Mapped[list[Profile]] = relationship(
        back_populates="practice_area"
    )


class PracticeLevel(Base):
    __tablename__ = "practice_level"
    id: Mapped[int] = mapped_column(primary_key=True)

    profiles: Mapped[list[Profile]] = relationship(
        back_populates="practice_level"
    )


class Profile(Base):
    __tablename__ = "profile"

    id: Mapped[int] = mapped_column(primary_key=True)
    practice_area_pk: Mapped[int] = mapped_column(
        ForeignKey("practice_area.id")
    )
    practice_level_pk: Mapped[int] = mapped_column(
        ForeignKey("practice_level.id")
    )

    practice_area: Mapped[PracticeArea] = relationship(
        back_populates="profiles"
    )
    practice_level: Mapped[PracticeLevel] = relationship(
        back_populates="profiles"
    )


class ProfileCreate:
    def __init__(self, practice_area_pk, practice_level_pk):
        self.practice_area_pk = practice_area_pk
        self.practice_level_pk = practice_level_pk


def get_by_pk(*, session: Session, pk: Any, model: type[Base]) -> Any:
    obj = session.get(model, pk)
    assert obj is not None
    return obj


def test_create_profile(fake_populated_session: Session) -> None:
    pa = PracticeArea()
    pl = PracticeLevel()
    fake_populated_session.add_all([pa, pl])
    fake_populated_session.flush()

    # make a Profile but intentionally keep it not really
    # part of the `Session` but part of pa.profiles / pl.profiles
    new_profile = Profile(
        practice_area_pk=pa.id, practice_level_pk=pl.id,
        practice_area=pa, practice_level=pl
    )

    new_profile_create = ProfileCreate(
        # ...
        practice_area_pk=new_profile.practice_area_pk,
        practice_level_pk=new_profile.practice_level_pk,
    )

    result = create_profile(new_profile_create, session=fake_populated_session)
    # ...
    print(f"result: {result}")


def create_profile(profile: ProfileCreate, *, session: Session) -> Profile:
    practice_area: PracticeArea = get_by_pk(
        session=session,
        pk=profile.practice_area_pk,
        model=PracticeArea,
        # ...
    )

    practice_level: PracticeLevel = get_by_pk(
        session=session,
        pk=profile.practice_level_pk,
        model=PracticeLevel,
        # ...
    )

    # now make the profile we want to persist.  but this is not the one
    # being warned about.  it's the other one.
    model = Profile(
        # ...
        practice_area=practice_area,
        practice_level=practice_level,
    )
    return create_record(
        record=model,
        session=session,
    )


####


def create_record(
    *,
    record: Base,
    session: Session,
    # ...
) -> Any:
    session.add(record)
    session.commit()
    session.refresh(record)

    # ...
    return record


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

with Session(e) as sess:
    test_create_profile(sess)

```

output (which is correct here):

```
2023-07-27 14:59:11,243 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-07-27 14:59:11,243 INFO sqlalchemy.engine.Engine INSERT INTO practice_area DEFAULT VALUES
2023-07-27 14:59:11,243 INFO sqlalchemy.engine.Engine [generated in 0.00012s] ()
2023-07-27 14:59:11,244 INFO sqlalchemy.engine.Engine INSERT INTO practice_level DEFAULT VALUES
2023-07-27 14:59:11,244 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ()
/home/classic/dev/sqlalchemy/test3.py:128: SAWarning: Object of type <Profile> not in session, add operation along 'PracticeLevel.profiles' will not proceed
  session.commit()
/home/classic/dev/sqlalchemy/test3.py:128: SAWarning: Object of type <Profile> not in session, add operation along 'PracticeArea.profiles' will not proceed
  session.commit()
2023-07-27 14:59:11,246 INFO sqlalchemy.engine.Engine INSERT INTO profile (practice_area_pk, practice_level_pk) VALUES (?, ?)
2023-07-27 14:59:11,246 INFO sqlalchemy.engine.Engine [generated in 0.00012s] (1, 1)
2023-07-27 14:59:11,247 INFO sqlalchemy.engine.Engine COMMIT
2023-07-27 14:59:11,247 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-07-27 14:59:11,249 INFO sqlalchemy.engine.Engine SELECT profile.id, profile.practice_area_pk, profile.practice_level_pk 
FROM profile 
WHERE profile.id = ?
2023-07-27 14:59:11,249 INFO sqlalchemy.engine.Engine [generated in 0.00011s] (1,)
result: <__main__.Profile object at 0x7f60fe0c08d0>
2023-07-27 14:59:11,249 INFO sqlalchemy.engine.Engine ROLLBACK
```

to "fix" this, don't associate the `PracticeArea` / `PracticeLevel` objects with that `Profile` that isn't wanted in the flush.

**Comment by zzzeek** [comment]
> ```
> >>> session
> <sqlalchemy.orm.session.Session object at 0x7f0629d68790>
> >>> from sqlalchemy import inspect
> >>> practice_area
> <PracticeArea 1>
> >>> state = inspect(practice_area)
> >>> session._contains_state(state)
> True

```

take a look inside of `practice_area.profiles`.  that's what the warning is telling you to look inside of.  you would see two `Profile` objects based on what this appears as, one is not in the `Session`.

**Comment by CodeMouse92** [comment]
```
>>> record.practice_area.profiles
[<Profile None (Christopher Dominguez)>, <Profile None (Christopher Dominguez)>]
>>> record
<Profile None (Christopher Dominguez)>
```

_VERY NICE_ sir.
