### ISSUE TITLE
Reuse of bindparams with literal_execute in positional dialects overwrites past values

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10142]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10141

<div type='discussions-op-text'>

<sup>Originally posted by **tmrlvi** July 25, 2023</sup>
When using `bindparam` in `literal_execute`, I get wrong output if I reuse the same bindparam twice.
I suspect it is a bug.
For example,

```
from sqlalchemy import select, create_engine, bindparam

conn = create_engine(f"sqlite://").connect()

a = bindparam("a", value="abc", literal_execute=True)
b = bindparam("b", value="def", literal_execute=True)
c = bindparam("c", value="ghi", literal_execute=True)
print(conn.execute(select(a,b,a,c)).fetchone())
```

**Expected:** ('abc', 'def', 'abc', 'ghi')
**Actual:** ('def', 'def', 'def', 'ghi')

Note that `print(conn.execute(select(a,b,c)).fetchone())` and `print(conn.execute(select(a,a,b,c)).fetchone())` works as expected. The problem is repeating `a` after `b` or `c`. I was able to track it down to `SQLCompiler._process_parameters_for_postcompile` where in `replacement_expressions` the value are overwritten incorrectly, but the root cause is somewhere else.</div>

**Comment by tmrlvi** [comment]
Found the culprit. In the for loop that fills the literals, you take the right value from parameters only if you havn't seen this parameter, but regardless, always update the `replacement_expressions`. So, value retains the value of the previous parameter, but then updates the current parameter.
```
            if parameter in self.literal_execute_params:
                if escaped_name not in replacement_expressions:
                    value = parameters.pop(name)

                replacement_expressions[
                    escaped_name
                ] = self.render_literal_bindparam(
                    parameter,
                    render_literal_value=value,
                )
```

All in all, it looks like a mistake in indentation.

**Comment by tmrlvi** [comment]
What is the correct behavior in case of repeatitions? Taking the first or last?

**Comment by tmrlvi** [comment]
And should we issue a warning when they are different?

**Comment by zzzeek** [comment]
these are named parameters so the same parameter being repeated would use the same value associated with that name.   That is, the test you show would work as expected.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**dont mis-render value from previous loop iteration** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4932
