### ISSUE TITLE
Windows wheels cp27 for release 1.4.49 missing

### ISSUE THREAD

**Issue by schlamar** [sqlalchemy/sqlalchemy#10159]
### Describe the bug

There are no Python 2.7 (cp27) wheels for latest 1.4.49 release on PyPI. I checked a few other 1.4.x releases including 1.4.48 and all of them has cp27 wheels for Windows uploaded.

### SQLAlchemy Version in Use

1.4.49

### Python Version

2.7

### Operating system

Windows

**Comment by zzzeek** [comment]
hi -

yes we are well aware of this change.   We can no longer provide Python 2.7 wheels due to https://github.com/actions/runner-images/issues/7401 .    There is no further action we can take here unfortunately.

**Comment by CaselIT** [comment]
As mike said the effort to continue supporting windows and osx wheels for 2.7 was deemed not worth it.
You should still be able to install the pure python version though
