### ISSUE TITLE
ORM context blows away independent ctes

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10167]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10166

<div type='discussions-op-text'>

<sup>Originally posted by **kkjot88** July 31, 2023</sup>
I am using version 2.0.17, postgres 15.3. Consider:

```python
from sqlalchemy import select, insert
from sqlalchemy.orm import as_declarative, Mapped, mapped_column


@as_declarative()
class TestTable:
    __tablename__ = "t"
    id: Mapped[int] = mapped_column(autoincrement=True, primary_key=True)
    c1: Mapped[str]
    c2: Mapped[str]


with session_maker() as session:
    cte_select = select(TestTable.c1, TestTable.c2).limit(1).cte("select")
    cte_insert = (
        insert(TestTable).from_select(["c1", "c2"], cte_select).cte("insert")
    )

    select_stmt = select(cte_select).add_cte(cte_insert)
    results = session.execute(select_stmt).all()

    session.commit()
```
what i get:
```sql
WITH select_values_cte AS 
(SELECT t.c1 AS c1, t.c2 AS c2 
FROM t
 LIMIT :param_1)
 SELECT select_values_cte.c1, select_values_cte.c2 
FROM select_values_cte
```
what i would expect:
```sql
WITH select_values_cte AS 
(SELECT t.c1 AS c1, t.c2 AS c2 
FROM t
 LIMIT :param_1), 
insert_values_cte AS 
(INSERT INTO t (c1, c2) SELECT select_values_cte.c1 AS c1, select_values_cte.c2 AS c2 
FROM select_values_cte)
 SELECT select_values_cte.c1, select_values_cte.c2 
FROM select_values_cte
```
from docs:

This method will associate the given :class:`_sql.CTE` constructs with
the parent statement such that they will each be unconditionally
rendered in the WITH clause of the final statement, even if not
referenced elsewhere within the statement or any sub-selects.

Am i doing something wrong? Seems to me this should work fine.</div>

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**pass along independent CTE attributes in ORM context** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4779
