### ISSUE TITLE
[2.0.19] FromClause.name does not exist

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#10160]
With 2.0.19 we seem to be getting:
```
 aiohttp_admin/backends/sqlalchemy.py:204:39: error: "FromClause" has no
attribute "name"  [attr-defined]
                    props = {"reference": relationship.entity.persist_sele...
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...
```
https://github.com/aio-libs/aiohttp-admin/actions/runs/5701121875/job/15451536717?pr=752

2.0.18 appears to be untyped for this element, so it was always `Any` in the past.

Code: https://github.com/aio-libs/aiohttp-admin/blob/c252be2eeddf8618803461800da61ba3b8dd9dd7/aiohttp_admin/backends/sqlalchemy.py#L195-L204

### Versions

- Python: 3.10
- SQLAlchemy: 2.0.19
- Type checker: mypy 1.4.1

**Comment by zzzeek** [comment]
not sure of a change that changed this (if you want to bisect) but FromClause doesnt really have a "name" in any case, like what's the "name" of a JOIN ?     What's the use case here?

**Comment by zzzeek** [comment]
test case:

```py
from sqlalchemy.sql.selectable import FromClause

x: FromClause
y = x.name


```

2.0.18:

```
HEAD is now at e3b9d4c19e - 2.0.18
[classic@zotac sqlalchemy:HEAD]$ mypy test3.py 
test3.py:4: error: "FromClause" has no attribute "name"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)

```

2.0.19 , no change:

```
HEAD is now at 9e89d2cbbf - 2.0.19
[classic@zotac sqlalchemy:HEAD]$ mypy test3.py 
test3.py:4: error: "FromClause" has no attribute "name"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)

```

**Comment by Dreamsorcerer** [comment]
Perhaps I'm using the wrong attributes to get what I need (it does work at runtime, but there may be multiple ways to do it).
If I remember correctly, it is getting the name of the table in the relationship (`relationship.entity.persist_selectable.name`).

Looking closer with `reveal_type()`, it actually the entire `relationship` which is `Any` in 2.0.18. So, the change must have been adding typing to `Mapper.relationships()`.

**Comment by zzzeek** [comment]
yah that code is not safe. Here's a runtime error for that

```py
from __future__ import annotations

from sqlalchemy import ForeignKey
from sqlalchemy import inspect
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column


class Base(DeclarativeBase):
    pass


class A(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(primary_key=True)


class B(Base):
    __tablename__ = "b"
    id: Mapped[int] = mapped_column(primary_key=True)
    a_id: Mapped[int] = mapped_column(ForeignKey("a.id"))

j1 = A.__table__.join(B.__table__)
class C(Base):
    __table__ = j1

    id = j1.c.a_id
    id2 = j1.c.b_id

inspect(C).persist_selectable.name
```

output:
```
Traceback (most recent call last):
  File "/mnt/photon_home/classic/dev/sqlalchemy/test3.py", line 32, in <module>
    inspect(C).persist_selectable.name
AttributeError: 'Join' object has no attribute 'name'

```

**Comment by zzzeek** [comment]
closing as this is the correct behavior

**Comment by Dreamsorcerer** [comment]
Well, that's not the relationships. Maybe it's not safe, but I'm not sure under what condition it would fail:
```
for _, r in inspect(C).relationships:
    print(r.persist_selectable.name)
```
There are no relationships here, so my actual code still passes.

**Comment by zzzeek** [comment]
`relationship` does not have a `persist_selectable` attribute, your other code indicated `relationship.entity.persist_selectable`, thats the mapper

```py
j1 = A.__table__.join(B.__table__)
class C(Base):
    __table__ = j1

    id = j1.c.a_id
    id2 = j1.c.b_id

class D(Base):
    __tablename__ = 'd'

    id: Mapped[int] = mapped_column(primary_key=True)

    a_id: Mapped[int] = mapped_column(ForeignKey("a.id"))

    c = relationship(C)

for _, r in inspect(D).relationships.items():
    print(r.entity.persist_selectable.name)
```

```
Traceback (most recent call last):
  File "/mnt/photon_home/classic/dev/sqlalchemy/test3.py", line 42, in <module>
    print(r.entity.persist_selectable.name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Join' object has no attribute 'name'

```

**Comment by Dreamsorcerer** [comment]
Thanks, makes sense. I've just added a `if not isinstance(relationship.entity.persist_selectable, sa.Table` check to skip those relationships (there was already a similar check to reject ORM models that are not Tables elsewhere).
