### ISSUE TITLE
ignore sequence / identity order it in other dbs, only use it on oracle

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10207]
plan is for 1.4 to just make pg ignore order and to rename in in v2, deprecating order

### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10203

<div type='discussions-op-text'>

<sup>Originally posted by **AbdealiLoKo** August  8, 2023</sup>
I believe this is a bug - but reporting it here just in case I am wrong ... as I am using `Identity()` for the first time.

I am trying to use `Identity()` for postgres and oracle in my code.
I generally support: MySQL, sqlite, mssql, oracle, and postgres in my application

Reproducible example:
```py
from sqlalchemy import Table, Identity, Column, BigInteger, MetaData
from sqlalchemy.schema import CreateTable
from sqlalchemy.dialects import sqlite, mysql, oracle, mssql, postgresql
meta = MetaData()
table = Table(
    'mytable',
    meta,
    Column('mycol', BigInteger(), Identity(order=True), primary_key=True),
    sqlite_autoincrement=True
)
print('sqlite', CreateTable(table).compile(dialect=sqlite.dialect()))
print('mysql', CreateTable(table).compile(dialect=mysql.dialect()))
print('oracle', CreateTable(table).compile(dialect=oracle.dialect()))
print('mssql', CreateTable(table).compile(dialect=mssql.dialect()))
print('postgresql', CreateTable(table).compile(dialect=postgresql.dialect()))
```

This gives me the output:
```sql
sqlite
CREATE TABLE mytable (
        mycol BIGINT NOT NULL PRIMARY KEY AUTOINCREMENT
)

mysql
CREATE TABLE mytable (
        mycol BIGINT NOT NULL AUTO_INCREMENT,
        PRIMARY KEY (mycol)
)

oracle
CREATE TABLE mytable (
        mycol NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (ORDER),
        PRIMARY KEY (mycol)
)

mssql
CREATE TABLE mytable (
        mycol BIGINT NOT NULL IDENTITY,
        PRIMARY KEY (mycol)
)

postgresql
CREATE TABLE mytable (
        mycol BIGINT GENERATED BY DEFAULT AS IDENTITY (ORDER),
        PRIMARY KEY (mycol)
)
```

When I run the last one i postgres, it gives the following error:
```
SQL Error [42601]: ERROR: syntax error at or near "ORDER"
  Position: 80
```

I couldn't find any documentation that says `ORDER` is a valid concept in postgres. So, I feel like sqlalchemy is generating it wrongly.
`ORDER` is only valid for oracle (For RAC support)

I am using:
 - python: 3.7.16
 - sqlalchemy: 1.4.47</div>

**Comment by CaselIT** [comment]
on_null is also oracle only, but it's currently correctly ignored by other dialects

**Comment by zzzeek** [comment]
why dont we do that for now, just dont render ORDER on other dialects

**Comment by zzzeek** [comment]
also why 1.4 ?

**Comment by CaselIT** [comment]
It's a bug that is also on 1.4. the fix there would just be to ignore the order

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fix rendering of order in sequences and identity columns.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4799

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**Fix rendering of order in sequences and identity columns.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4800

**Comment by CaselIT** [comment]
The cherry pick for 1.4 is partial. The change on v2 break alembic so I'll have to check it better

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**Fix rendering of order in sequences and identity columns.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4827

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fix rendering of order in sequences and identity columns.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4828

**Comment by CaselIT** [comment]
additional changes will be done in #10247
