### ISSUE TITLE
CTE Compiles in Incorrect Order for Postgres Insert From Select

### ISSUE THREAD

**Issue by 110holmberg** [sqlalchemy/sqlalchemy#10201]
### Describe the bug

The issue described [here](https://github.com/sqlalchemy/sqlalchemy/issues/4275) for the Oracle engine and fixed [here](https://github.com/sqlalchemy/sqlalchemy/commit/3619edcb8aa3ceef2a44925b85315fc0e90c5982) for the Oracle engine and MySQL engine also exists for the Postgres engine. I have used the same code example from this previous issue to reproduce the error.

When attempting to execute an SQL statement with a common table expression insert using a Postgres engine, the insert statements render with a syntax error. The `insert into` statement should be at the beginning of the query, but instead is in the middle.

### SQLAlchemy Version in Use

1.4.46

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

Redshift 1.0.5

### Python Version

3.9

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import create_engine, Table, Column, Integer, select, MetaData, String

engine = create_engine('postgresql://username:password@host:port/database')

metadata = MetaData()

foo = Table('foo', metadata, Column('name', String(1)), schema='test_schema')
baz = Table(
    'baz',
    metadata,
    Column('id', Integer, primary_key=True, autoincrement=False),
    Column('name', String(50)),
    schema='test_schema'
)


metadata.create_all(engine)

cte_1 = select([foo.c.name]).cte('first_cte')
cte_2 = select([cte_1.c.name]).select_from(cte_1).cte('second_cte')
ins = baz.insert().from_select([baz.c.name], cte_2)

print(ins.compile(engine))

with engine.begin() as conn:
    conn.execute(ins)
```

### Error

```
Traceback (most recent call last):
  File "sqlalchemy_mvc.py", line 26, in <module>
    conn.execute(ins)
  File "/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Python/3.9/lib/python/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Python/3.9/lib/python/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Python/3.9/lib/python/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Python/3.9/lib/python/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "INSERT"
LINE 7:  INSERT INTO test_schema.baz (name) SELECT second_cte.nam...
         ^

[SQL: WITH first_cte AS 
(SELECT test_schem.foo.name AS name 
FROM test_schema.foo), 
second_cte AS 
(SELECT first_cte.name AS name 
FROM first_cte)
 INSERT INTO test_schema.baz (name) SELECT second_cte.name 
FROM second_cte]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

### Additional context

I was able to resolve the issue after forking the package with [this](https://github.com/110holmberg/sqlalchemy/commit/865a4b60da8a40b6cd339855998edc9b6e90ce79) one line change that takes advantage of the original fix that was implemented for Oracle and MySQL in [this](https://github.com/sqlalchemy/sqlalchemy/commit/3619edcb8aa3ceef2a44925b85315fc0e90c5982) PR.

**Comment by CaselIT** [comment]
Hi,

I think the issue is of redshift, so you should be opening an issue to their dialect.

The postgresql syntax looks ok https://www.postgresql.org/docs/current/sql-insert.html
