### ISSUE TITLE
remove select().c  / .columns, completely.   no trace

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10236]
I thought we already removed this in 2.0 but we didn't.   Erase it completely for 2.1 please

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**remove _implicit_subquery and all derived functions** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5570
