### ISSUE TITLE
Type `text` and `exec_driver_sql` using LiteralString instead of str

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10255]
Python 3.11 added support for [LiteralString](https://docs.python.org/3/library/typing.html#typing.LiteralString), meaning that type checkers will error if someone tries to do
```py
conn.exec_driver_sql(f'select * form foo where foo.id = {my_id}')
```

That's also in typing extensions.
The idea would be to type all the places that take an input sql with this.

For reference psycopg3 uses it in its typing

**Comment by gordthompson** [comment]
Maybe I'm missing something, but this code

```python
# sqla_issues_10255.py
#
# https://github.com/sqlalchemy/sqlalchemy/issues/10255
from typing import LiteralString


def my_exec_driver_sql(stmt: LiteralString) -> str:
    return f"done: {stmt}"


sp_name = "my_sp"
result = my_exec_driver_sql(f"EXEC {sp_name}")
print(result)
```

does not raise any type checking warnings

```
> python -VV
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
> mypy -V
mypy 1.5.1 (compiled: yes)
> mypy .\sqla_issues_10255.py
Success: no issues found in 1 source file
```

**Comment by CaselIT** [comment]
That's disappointing.. Maybe mypy does not support it?

Does pyright report an error?

**Comment by gordthompson** [comment]
> Does pyright report an error?

Not for me.

```
> pyright --version
pyright 1.1.323
> pyright .\sqla_issues_10255.py
0 errors, 0 warnings, 0 informations
```

**Comment by CaselIT** [comment]
Then I don't understand what's up. Your example is exactly the same as the one from the stdlib example
```py
def run_query(sql: LiteralString) -> None:
    ...

def caller(arbitrary_string: str, literal_string: LiteralString) -> None:
    run_query("SELECT * FROM students")  # OK
    run_query(literal_string)  # OK
    run_query("SELECT * FROM " + literal_string)  # OK
    run_query(arbitrary_string)  # type checker error
    run_query(  # type checker error
        f"SELECT * FROM students WHERE name = {arbitrary_string}"
    )
```

**Comment by gordthompson** [comment]
No warnings in VSCode, either. Weird.

**Comment by zzzeek** [comment]
did you check if mypy is supporting pep-675 yet ?  these peps precede support by typing tools

**Comment by CaselIT** [comment]
> did you check if mypy is supporting pep-675 yet ? these peps precede support by typing tools

seems not https://github.com/python/mypy/issues/12554

pyright does seem to support it though https://github.com/microsoft/pyright/issues/3023. Maybe it needs strict mode though?

**Comment by gordthompson** [comment]
In VSCode I have "Python > Analysis: Type Checking Mode" set to "strict". Pylance is v2023.8.30

**Comment by CaselIT** [comment]
that's very strange then. does the example from the python docs also raises no error?

**Comment by CaselIT** [comment]
ok, that's the correct behaviour. we are in this case `run_query("SELECT * FROM " + literal_string)  # OK`, since `sp_name` is a literal that's a subtype of literal string.

if you update your example as follows it should error correctly
```py
from typing import LiteralString


def my_exec_driver_sql(stmt: LiteralString) -> str:
    return f"done: {stmt}"

def go(sp_name: str)->None:
    result = my_exec_driver_sql(f"EXEC {sp_name}")
    print(result)

go('my_sp')

deg go(sp_name result = my_exec_driver_sql(f"EXEC {sp_name}")
print(result)

**Comment by gordthompson** [comment]
Okay, thanks. I suppose that if I really want to I can use

```python
  result = my_exec_driver_sql(f"EXEC {sp_name}")  # type: ignore
```

to avoid the warning. However, if this change is primarily intended to thwart Little Bobby Tables (SQL injection) then it may also end up annoying a lot of people who are legitimately using dynamic SQL.

**Comment by gordthompson** [comment]
BTW, it also warns for "Python > Analysis: Type Checking Mode" set to "basic".

**Comment by CaselIT** [comment]
> However, if this change is primarily intended to thwart Little Bobby Tables (SQL injection) then it may also end up annoying a lot of people who are legitimately using dynamic SQL.

Yes, this is the main drawback. I've opened the issue to see if something like this makes sense.
Overall the idea for this is to have the safe option by default, but still allow a str if needed by the user 

An option could be to add an alias of `text` that's typed as str so if one really wants a dynamic generated string it can use it (or even a kw arg that allows str instead of literal string on text, even if it's not great since it would be otherwise ignored). Same for exec_driver_sql.

**Comment by zzzeek** [comment]
just FYI I dont think we could actually use this in SQLAlchemy for things like exec_driver_sql, we have [interpolation](https://github.com/sqlalchemy/sqlalchemy/blob/09d247d57ffb6329739deae89019c9e7ad3b9e7f/lib/sqlalchemy/dialects/mssql/base.py#L2914) in our own code and it's not really avoidable for building up dynamically generated textual queries.

**Comment by CaselIT** [comment]
psycopg has a specific construct for dynamic queries, if we want to use that as inspiration: https://www.psycopg.org/psycopg3/docs/advanced/typing.html#checking-literal-strings-in-queries

**Comment by zzzeek** [comment]
we have that, it's `text()`

**Comment by CaselIT** [comment]
sure, buy it's typed as str, so you can pass interpolated strings to it.

**Comment by zzzeek** [comment]
text() only allows for bound parameters.  I think supporting a clone of psycopg3's SQL().format() feature would be a lot of burden to place on the userbase and us.   not the least of which is that it provides the illusion of "Security", does psycopg3's SQL().format() prevent the strings within format() from being used for SQL injection (if not, someone will absolutely raise a CVE that it should)  ?  if so, then what is the solution for someone that genuinely needs to format arbitrary strings in a SQL string ?

**Comment by CaselIT** [comment]
I was not proposing to use the same system as psycopg, but maybe be could have a str subclass that could be used. Something like
`text(i_know_about_sql_injections(...))`

**Comment by zzzeek** [comment]
this is already why we don't allow `connection.execute("select * from table")` - that was the point of only allowing `text()`, and why we have `exec_driver_sql()` - these are the functions where people are supposed to make sure they aren't using untrusted input.   

if we add typing that limits `text()` to only non-interpolated strings, people will complain about it from both ends; from one end, that just to compose a string programatically, they need *two* levels of objects, and from the other end, that it doesnt actually protect anything at runtime since it's currently not possible to detect an f string at runtime.

to actually do this kind of thing "for real", you need to have a concept of "tainted strings" where strings that come from untrusted sources are runtime tagged in such a way that they can be guarded against in all cases.   this is out of scope for generic Python.

**Comment by zzzeek** [comment]
we definitely would not want:

    `text(trusted_input("xyz" + "qpr"))`

we would want


    `trusted_text("xyz" + "qpr")

this doesn't help the `exec_driver_sql()` part though

**Comment by zzzeek** [comment]
so we'd have 

`text()`

`trusted_text()`

`exec_driver_sql()`

`exec_trusted_driver_sql()`

i mean if someone is driving untrusted input into one of them they're going to drive it into the other one also

**Comment by zzzeek** [comment]
yeah I am not really buying https://peps.python.org/pep-0675/#appendix-b-limitations .

they assume everyone uses a type checker.    I've never seen a CVE that uses a type checker, they do a runtime thing.   If we start claiming that text() will not accept an interpolated string, CVEs will be published that show that they do.

**Comment by CaselIT** [comment]
makes sense to me. i think pep 675 at the moment would just complicate things, so let's close this

**Comment by zzzeek** [comment]
thanks, we can keep an eye on this and see where public preference goes, just seems a little soon right now given all the adjustment everyone is making for 2.0
