### ISSUE TITLE
Allow using Enum with length=None

### ISSUE THREAD

**Issue by eltoder** [sqlalchemy/sqlalchemy#10269]
### Describe the use case

When using string-based enum types, i.e. `Enum(python_enum,  native_enum=False)`, the default behavior is to use `String(N)` with N set to the length of the longest enum member name. This can break if new enum members are added in the future with longer names. If the default behavior cannot be changed, the issue can be solved by explicitly passing `length=None`, which removes the string length limit. This almost works, except that it breaks the check here: https://github.com/sqlalchemy/sqlalchemy/blob/09d247d57ffb6329739deae89019c9e7ad3b9e7f/lib/sqlalchemy/sql/sqltypes.py#L1454
This can be further worked-around by passing an undocumented argument `_disable_warnings=True`. It would be nice if the latter was not required. This requires only a one-line change
```python
if not _disable_warnings and length_arg is not None and length_arg < length:
```

### Databases / Backends / Drivers targeted

Any database.

### Example Use

**Example:**
```python
import enum
import sqlalchemy as sa

class MyEnum(enum.Enum):
    A = 1

md = sa.MetaData()
table = sa.Table("test", md, sa.Column("enum", sa.Enum(MyEnum, native_enum=False, length=None)))
print(sa.schema.CreateTable(table))
```
**Expected output:**
```
CREATE TABLE test (
        enum VARCHAR
)
```
**Current output:**
```
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
**Work-around:**
```python
table = sa.Table(
    "test",
    md,
    sa.Column("enum", sa.Enum(MyEnum, native_enum=False, length=None, _disable_warnings=True))
)
```

**Comment by CaselIT** [comment]
Hi,

`length=None` is not currently supported or tested. @zzzeek do you think it would make sense?

**Comment by zzzeek** [comment]
yes we can support length=None.   Fortunately we already use NO_ARG as the default for this, so the area is clear for `None` as a distinct value.

**Comment by sqla-tester** [comment]
**Eugene Toder** has proposed a fix for this issue in the **main** branch:

**Allow using Enum with length=None** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4830
