### ISSUE TITLE
Custom column type fails type-check

### ISSUE THREAD

**Issue by mmzeynalli** [sqlalchemy/sqlalchemy#10284]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

As I have many non-nullable fields, I created the following code snippet:

```
class NotNullColumn(Column):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs, nullable=False)

    @property
    def _constructor(self):
        return Column
```

However, whenever I use it, mypy complains, although I have no problem with other fields.

### To Reproduce

For example, if I use `NotNullColumn`:

```python
class RefreshToken(Base):
    __tablename__ = "auth_refreshtoken"

    uuid = Column(UUID, primary_key=True, index=True)
    user_id: int = Column(ForeignKey("auth_user.id", ondelete="CASCADE"))
    refresh_token = NotNullColumn(String)
    expires_at = NotNullColumn(DateTime)
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, onupdate=func.now())
```

And whenever I assign value to these fields or create a new RefreshToken, I get mypy error. THERE IS NO LOGIC ERROR, THE CODE WORKS JUST FINE.

### Error

```
src\auth\models.py:17: error: Incompatible types in assignment (expression has type "NotNullColumn", variable has type "bytes")  [assignment]
src\auth\models.py:32: error: Incompatible types in assignment (expression has type "NotNullColumn", variable has type "datetime")  [assignment]
src\auth\service.py:85: error: Unexpected keyword argument "refresh_token" for "RefreshToken"  [call-arg]
src\auth\service.py:85: error: Unexpected keyword argument "expires_at" for "RefreshToken"  [call-arg]
``` 

### Versions

- OS: Windwos 10
- Python: 3.10
- SQLAlchemy: 2.0.20
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): sqlalchemy[mypy]

**Comment by CaselIT** [comment]
Hi,

I'm assuming you are using the mypy plugin. It's deprecated so it's unlikely it will be changed to accommodate column subtypes. To have an overall better typing experience take a look at the v2 syntax https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#orm-declarative-models
