### ISSUE TITLE
Add `get_one` to `Session`, `AsyncSession`, scoped, etc

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10292]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10291

<div type='discussions-op-text'>

<sup>Originally posted by **samtoffler** August 29, 2023</sup>
I'm new to SQLAlchemy, so apologies if I've missed this somewhere in my research.

A common pattern I've seen is the following:

```
foo = db.session.get(Foo, foo_id)

if foo is None:
  raise Exception("Foo not found")
```

It would be nice if there was something like `Session.get_one()`, similar to [`Result.one()`](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.one), that raises a `NoResultFound` exception in the event that no instance is found. I could use `Session.query().one()`, but would like to keep the performance benefits of `get` as described in the [docs](https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.get).</div>

The logic would be a simple get + check for none and raise if so.
Add to all sessions (scoped, async, etc)

**Comment by CarlosEduR** [comment]
@CaselIT is there anyone already working on it? If not, I'd like to do so.

**Comment by CaselIT** [comment]
I don't think so, feel free to work on it

**Comment by sqla-tester** [comment]
**Carlos Sousa** has proposed a fix for this issue in the **main** branch:

**Add get_one to Session, AsyncSession, scoped, etc** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4872

**Comment by sqla-tester** [comment]
**Carlos Sousa** has proposed a fix for this issue in the **main** branch:

**Add get_one to Session, AsyncSession, scoped, etc** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4872
