### ISSUE TITLE
do not import greenlet if concurrency functions are not used

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10296]
from #10197, I would prefer we don't import greenlet at all if asyncio is not used.

Right now we expose these four functions in sqlalchemy.util:

```py
from .concurrency import await_fallback as await_fallback
from .concurrency import await_only as await_only
from .concurrency import greenlet_spawn as greenlet_spawn
from .concurrency import is_exit_exception as is_exit_exception
```

one way to do this would be to use a `__getattr__()` within `sqlalchemy.util.__init__` instead.

Or we could make the functions in concurrency.py / _concurrency_py3k use a late import against "greenlet" itself, that raises `NotImplementedError` if "greenlet" isn't present.

this probably would work pretty well.

**Comment by zzzeek** [comment]
late import against "greenlet" starts getting  messy because we have `_AsyncioGreenlet` subclassing `greenlet`.  There's ways to manipulate all this but it becomes overkill.

**Comment by zzzeek** [comment]
this is only worth it if there is some super simple ten-line shim that can achieve this goal.  if we have to put getattr tricks all over the place, then it's not worth it.

**Comment by zzzeek** [comment]
I have something working.  this is the only way to test it:

```py
>>> import sqlalchemy
>>> import sys
>>> sys.modules['greenlet']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'greenlet'

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**dont import greenlet at all until _concurrency_pk3k is used** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4841

**Comment by CaselIT** [comment]
this works
```py
import importlib
import sys
print(importlib.util.find_spec('greenlet'))
assert importlib.util.find_spec('greenlet') is not None
assert 'greenlet' not in sys.modules
```

**Comment by CaselIT** [comment]
but does not really solve the issue

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**dont import greenlet at all until actually used** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4861

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**don't import greenlet at all until it's needed** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4861
