### ISSUE TITLE
`select_from` is not consistently typed.

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10337]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

`select_from` is not consistently typed.

### To Reproduce

```python
import sqlalchemy as sa
import sqlalchemy.orm as orm


class B(orm.DeclarativeBase):
    pass


class M(B):
    __tablename__ = "foo"
    id: orm.Mapped[int] = orm.mapped_column(primary_key=True)
    name: orm.Mapped[str]


print(sa.exists(1).select_from(M))
print(sa.select(1).select_from(M).exists())
```

### Error

```
(error: Argument 1 to "select_from" of "Exists" has incompatible type "Type[M]"; expected "FromClause"  [arg-type])
``` 

### Versions

- OS: any
- Python: any
- SQLAlchemy: 2.0.20
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.3.0

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fix Existing.select_from type definition** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4866
