### ISSUE TITLE
Use the native UUID type on mariadb

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10339]
Version 2.0 of sqlalchemy added support for Uuid but has no specific support for it on mariadb, so `char(32)` is used there.

Since 10.7 there is a specific type for UUID in mariadb https://mariadb.com/kb/en/uuid-data-type/

**Comment by zzzeek** [comment]
to clarify, this is the agnostic `Uuid` datatype.  `UUID` works fine on MariaDB, see #10028

**Comment by CaselIT** [comment]
Yes, also probably export the type from the mysql dialect too.

**Comment by whysage** [comment]
Hi, please review
https://github.com/sqlalchemy/sqlalchemy/pull/10849

**Comment by whysage** [comment]
Hi, any comments on pull request?

**Comment by sqla-tester** [comment]
**Volodymyr Kochetkov** has proposed a fix for this issue in the **main** branch:

**implement native uuid for mariadb >= 10.7** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5120

**Comment by zzzeek** [comment]
i've moved the dialect handling down to the "supports_native_uuid" attribute which is where this should be set up.   the mechanics of when the MariaDBUUID type get used or not gets a little crazy internally but overall it looks like all the drivers accept UUID objects directly, just they dont coerce on the other end so will have to confirm that's the case here.
