### ISSUE TITLE
Errors from use of hashlib.md5 for truncated names on FIPS-enabled systems

### ISSUE THREAD

**Issue by hozn** [sqlalchemy/sqlalchemy#10342]
### Describe the bug

On systems (RHEL) where FIPS is enabled, the md5 is disabled in openssl and calls to `hashlib.md5()` in python will fail with an error like:
```
# SNIP
|   File "/opt/app-root/lib64/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 7507, in _truncate_and_render_maxlen_name
|     name = name[0 : max_ - 8] + "_" + util.md5_hex(name)[-4:]
|                                       ^^^^^^^^^^^^^^^^^^
|   File "/opt/app-root/lib64/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 90, in md5_hex
|     m = hashlib.md5()
|         ^^^^^^^^^^^^^
| ValueError: [digital envelope routines] unsupported
|
| Application startup failed. Exiting.
| Server stopped!
```

As mentioned in the [docs](https://docs.python.org/3/library/hashlib.html), for newer versions of python (3.9+) there is a `usedforsecurity` flag that can be set to `False` to avoid this error.

### SQLAlchemy Version in Use

2.0.15

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

Postgresql 15

### Python Version

3.11

### Operating system

Linux, OSX

### To Reproduce

```python
# Create table with a constraint name or column name that exceeds a maximum length.

class MyModel(DeclarativeBase):
    __tablename__ = "mytable"

    id: Mapped[int] = mapped_column(primary_key=True)
    very_very_very_very_very_very_very_very_very_very_long_name: Mapped[str]
#   0123456789012345678901234567890123456789012345678901234567890123456789
#   1         2         3         4         5         6         7
```

### Error

```
# SNIP
|   File "/opt/app-root/lib64/python3.11/site-packages/sqlalchemy/sql/compiler.py", line 7507, in _truncate_and_render_maxlen_name
|     name = name[0 : max_ - 8] + "_" + util.md5_hex(name)[-4:]
|                                       ^^^^^^^^^^^^^^^^^^
|   File "/opt/app-root/lib64/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 90, in md5_hex
|     m = hashlib.md5()
|         ^^^^^^^^^^^^^
| ValueError: [digital envelope routines] unsupported
|
| Application startup failed. Exiting.
| Server stopped!
```

**Comment by zzzeek** [comment]
OK, will add a compat function, thanks

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**qualify hashlib.md5() with usedforsecurity=False** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4884

**Comment by zzzeek** [comment]
so that patch has the change which passes, however I cannot confirm for a FIPS python build.  if you have that available, feel free to test the above patch.

I'm your coworker; is there an RH BZ I can track?

**Comment by CaselIT** [comment]
the lib says:
> Constructors for hash algorithms that are always present in this module are sha1(), sha224(), sha256(), sha384(), sha512(), sha3_224(), sha3_256(), sha3_384(), sha3_512(), shake_128(), shake_256(), blake2b(), and blake2s(). md5() is normally available as well, though it may be missing or blocked if you are using a rare “FIPS compliant” build of Python. These correspond to algorithms_guaranteed.

maybe an option is to switch to use sha256 or similar?

**Comment by hozn** [comment]
> so that patch has the change which passes, however I cannot confirm for a FIPS python build. if you have that available, feel free to test the above patch.

I need to figure out how to get the patched version into our build environment, but I am happy to confirm the fix once I do that.  (To confirm, this is not already available as a pip-installable branch of repo, correct?)

**Comment by zzzeek** [comment]
you can get a tar.gz of the whole dist from that gerrit link https://gerrit.sqlalchemy.org/changes/sqlalchemy%2Fsqlalchemy~4884/revisions/1/archive?format=tgz

**Comment by CaselIT** [comment]
> the use of sha1() is not for security purposes, why add the additional overhead ?

it's actually faster on my machine
```py
import hashlib
import pathlib
import timeit

data = dict(
    tiny=b"Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    small=b"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    large=pathlib.Path("README.rst").read_bytes(),
)
print({k: len(v) for k, v in data.items()})
print(hashlib.algorithms_available)

for alg in ["md5", "sha1", "sha256", "blake2b", "blake2s", "sha3_256"]:
    for k, v in data.items():
        print(
            alg, k, timeit.timeit(lambda: hashlib.new(alg, v), number=100_000)
        )
```
md5 tiny 0.04080080008134246
md5 small 0.08052820013836026
md5 large 0.6139742997474968
sha1 tiny 0.04092900035902858
sha1 small 0.055188000202178955
sha1 large 0.27000509994104505
sha256 tiny 0.04145619971677661
sha256 small 0.05663490016013384
sha256 large 0.2862066999077797
blake2b tiny 0.03135589975863695
blake2b small 0.06260390020906925
blake2b large 0.6898574000224471
blake2s tiny 0.028144500218331814
blake2s small 0.09150159964337945
blake2s large 1.0769564001820982
sha3_256 tiny 0.04526299983263016
sha3_256 small 0.10754700005054474
sha3_256 large 0.9548165001906455
```

**Comment by CaselIT** [comment]
we could probably even use `sha256`/`sha224`

**Comment by zzzeek** [comment]
we are actually using md5 tiny.

**Comment by zzzeek** [comment]
i guess md5 to me implies "this is not for security, at all", whereas the sha algos start looking like we are doing something for security.

**Comment by CaselIT** [comment]
Yes, I'm just suggesting alternatives if they start removing algos from python.

Hopefully setting that flag works

**Comment by hozn** [comment]
> you can get a tar.gz of the whole dist from that gerrit link https://gerrit.sqlalchemy.org/changes/sqlalchemy%2Fsqlalchemy~4884/revisions/1/archive?format=tgz

Thank you! I'll work with the SRE team to replace our SA pkg and re-run this test.

**Comment by zzzeek** [comment]
OK thanks, don't go through too much trouble, this is a pretty simple change, just thought if it was easy to test locally

**Comment by hozn** [comment]
Sorry, yes, our initial attempts to install via tgz into this container env failed (maybe a poetry bug, didn't dive in too deep), so we'll just test out the release once it is generally available.  Thank you again for such amazingly fast support on this!

**Comment by zzzeek** [comment]
it's checked into main now so if you want to install from github you can try that.  otherwise it will go out in 2.0.21
