### ISSUE TITLE
Drop support for python 3.7

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10357]
It's eol so it makes sense removing it.

Things to note that are 3.8+
- [Assignment expressions](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions)
- [Positional-only parameters](https://docs.python.org/3/whatsnew/3.8.html#positional-only-parameters)
- [A few improvement on the typing module](https://docs.python.org/3/whatsnew/3.8.html#typing)

**Comment by zzzeek** [comment]
yes definitely

i guess 2.1 dev should start soon, mainly it means we aren't really releasing 1.4 anymore b.c. i dont want to deal with three branches

**Comment by CaselIT** [comment]
I guess we can do a final 1.4 release then do a 2.0 branch

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**2.1 setup / initial dependency/min version change** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4943
