### ISSUE TITLE
Pyright - InstrumentedAttribute is not hashable

### ISSUE THREAD

**Issue by rmorshea** [sqlalchemy/sqlalchemy#10353]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

As the title indicates, Pyright complains that `InstrumentedAttribute` is not hashable. This comes up when you include it in a dictionary (e.g. `{MyTable.some_column: some_value}`) for updating rows.

### To Reproduce

```python
from sqlalchemy import MetaData, update
from sqlalchemy.orm import DeclarativeBase, Mapped


class Base(DeclarativeBase):
    pass


class X(Base):
    i: Mapped[int]


update(X).values({X.i: 1})  # error: error: Dictionary key must be hashable
```

### Error

```
example.py:14:19 - error: Dictionary key must be hashable
    Type "InstrumentedAttribute[int]" is not hashable (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
``` 

### Versions

- OS: MacOS
- Python: 3.10
- SQLAlchemy: 2.0.20
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): pyright v1.1.327

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. We may need to add a `__hash__` method in type checking.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fix typing to ensure that InstrumentedAttribute is hashable** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4867
