### ISSUE TITLE
Run CI pipeline against Mariadb 11.0

### ISSUE THREAD

**Issue by ihtiuh** [sqlalchemy/sqlalchemy#10373]
### Describe the use case

To find out compatibility between SQLAlchemy and Mariadb version 11.0, we would like to request CI pipeline run for MariaDB 11.0

### Databases / Backends / Drivers targeted

MariaDB 11.0.3

### Example Use

N/A

**Comment by CaselIT** [comment]
Hi,

Current mysql/mariadb test uses the following command in jenkins
> python -m pytest --rootdir /home/jenkins/workspace/sqlalchemy_2x_gerrit/5e6c224d/sqlalchemy/sqlalchemy --log-info=sqlalchemy.testing -n2 --max-worker-restart=5 --dburi 'mysql+mysqldb://scott:tiger@mariadb108/test?charset=utf8mb4' --dburi 'mysql+pymysql://scott:tiger@mariadb109/test?charset=utf8mb4' --dburi 'mysql+pymysql://scott:tiger@mysql57/test?charset=utf8mb4' --dburi 'mysql+mysqldb://scott:tiger@mysql56/test?charset=utf8mb4' --dburi 'mysql+mysqldb://scott:tiger@mysql80/test?charset=utf8mb4' --dburi 'mysql+pymysql://scott:tiger@mysql80/test?charset=utf8mb4' --dbdriver mysqldb --dbdriver pymysql --dbdriver asyncmy --dbdriver aiomysql -m 'not memory_intensive and not mypy' --junitxml=junit-py311-cext-mysql.xml

so it does not appear to be tested.
(from https://jenkins.sqlalchemy.org/job/sqlalchemy_2x_gerrit/cext=cext,db=mysql,pyv=py311/3980/consoleFull but the link will likely expire soon)

@zzzeek since PG16 and Oracle 23 are also out maybe it makes sense updating a bit the dbs run by the jenkins

**Comment by zzzeek** [comment]
I am doing pg16 and mdb 11.1 now.  the oracle thing requires downloading whatever their latest dev thing is and re-experimenting all over again with setup scripts since they tend to change things dramatically each time

**Comment by CaselIT** [comment]
if you like there is a docker image of 23 available: https://hub.docker.com/r/gvenzl/oracle-free

**Comment by zzzeek** [comment]
as you know I like to build our docker images so that I can stay in control....

**Comment by CaselIT** [comment]
(btw I don't think it's urgent to have the oracle 23 since I doubt they broke anything that was supported on previous versions)

**Comment by zzzeek** [comment]
current mariadb 11 version is 11.1.2.     CI currently has 11.1.2, 10.9 for mariadb running.   log attached

[sqla_mariadb_jenkins_run_20230920.txt](https://github.com/sqlalchemy/sqlalchemy/files/12674548/sqla_mariadb_jenkins_run_20230920.txt)

**Comment by ihtiuh** [comment]
Thanks for the quick resolution :heart:
