### ISSUE TITLE
`AsyncSession.close_all()` always raise a AttributeError

### ISSUE THREAD

**Issue by ProgramRipper** [sqlalchemy/sqlalchemy#10421]
### Describe the bug

`AsyncSession.close_all()` is a `classmethod`, but the `AsyncSession` class does not have the `.sync_session` class attribute, so it always raise an `AttributeError`.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#sqlalchemy.ext.asyncio.AsyncSession.close_all

### SQLAlchemy Version in Use

2.0.21

### DBAPI (i.e. the database driver)

_irrelevant_

### Database Vendor and Major Version

_irrelevant_

### Python Version

_irrelevant_

### Operating system

_irrelevant_

### To Reproduce

```python
await AsyncSession.close_all()
# or...
await AsyncSession().close_all()
```

### Error

```
>>> await AsyncSession.close_all()
Traceback (most recent call last):
  File "/nix/store/26wf73xxskg8ar6fiz0yk64w3j6hhk5a-python3-3.9.18/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/nix/store/26wf73xxskg8ar6fiz0yk64w3j6hhk5a-python3-3.9.18/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/home/nixos/plugin-orm/.venv/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 1013, in close_all
    await greenlet_spawn(self.sync_session.close_all)
AttributeError: type object 'AsyncSession' has no attribute 'sync_session'
``` 

### Additional context

Considering [`Session.close_all()`](https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.close_all) has been deprecated since SQLAlchemy 1.3, maybe `AsyncSession.close_all()` should be marked as deprecated, and fix it for backard compatibility like this:

```diff
diff --git a/lib/sqlalchemy/ext/asyncio/session.py b/lib/sqlalchemy/ext/asyncio/session.py
index dcbf26c6c..dc8d2f317 100644
--- a/lib/sqlalchemy/ext/asyncio/session.py
+++ b/lib/sqlalchemy/ext/asyncio/session.py
@@ -1059,7 +1059,7 @@ class AsyncSession(ReversibleProxy[Session]):
     @classmethod
     async def close_all(self) -> None:
         """Close all :class:`_asyncio.AsyncSession` sessions."""
-        await greenlet_spawn(self.sync_session.close_all)
+        await greenlet_spawn(close_all_sessions)
```

**Comment by zzzeek** [comment]
feel free to provide a PR with a short test in test/ext/asyncio/test_session_py3k.py

**Comment by sqla-tester** [comment]
**Bryan不可思议** has proposed a fix for this issue in the **main** branch:

**fix AsyncSession.close_all()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4878
