### ISSUE TITLE
SQL Server [WITH TIES]

### ISSUE THREAD

**Issue by leonokubo** [sqlalchemy/sqlalchemy#10458]
### Describe the bug

[with ties] with subquery, is removing "order_by"

```
    def query(self, table: Table, engine, session):
        column = getattr(table.columns, self.watermark_config.column)
        subquery = table.select()\
            .where(self.condition(column))\
            .fetch(with_ties=True, count=self.top)\
            **.order_by(self.order_by(column))**

        query = subquery.cte("results")\
            .select()\
            .fetch(with_ties=True, count=80, percent=True)\
            **.order_by(self.watermark_config.column)**

        pd.read_sql(sql=query, con=engine, dtype_backend="pyarrow")
```

Error:
{ProgrammingError}(pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The TOP N WITH TIES clause is not allowed **without a corresponding ORDER BY** clause. (1062) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)')

### SQLAlchemy Version in Use

2.0.21

### DBAPI (i.e. the database driver)

ODBC Driver 17 for SQL Server

### Database Vendor and Major Version

SQL Server

### Python Version

3.11

### Operating system

Windows

### To Reproduce

```python
table = Table(
            reader.table_name,
            MetaData(),
            schema=reader.database,
            include_columns=[colum for colum in source_mapping.keys()],
            autoload_with=engine
        )

subquery = table.select()\
            .where(self.condition(column))\
            .fetch(with_ties=True, count=self.top)\
            .order_by(self.order_by(column))

query = subquery.cte("results")\
            .select()\
            .fetch(with_ties=True, count=80, percent=True)\
            .order_by(self.watermark_config.column)
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
```

**Comment by zzzeek** [comment]
hi - 

I dont have "reader" or "source_mapping" here, so I'll just make something up

**Comment by zzzeek** [comment]
The issue here is that SQL Server does not allow ORDER BY in a subquery, so there is a hardcoded rule to prevent the ORDER BY from appearing:

```py
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.dialects import mssql
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import query

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)


a_table = A.__table__


subquery = (
    a_table.select()
    .where(a_table.c.data == "x")
    .fetch(with_ties=True, count=10)
    .order_by(a_table.c.id)
)

cc = subquery.cte("results")
query = (
    cc.select().fetch(with_ties=True, count=80, percent=True).order_by(cc.c.id)
)

print(query)

print("------------------------")
print(query.compile(dialect=mssql.dialect()))

```

the SQL Server query is:

```
WITH results AS 
(SELECT TOP __[POSTCOMPILE_param_2] WITH TIES a.id AS id, a.data AS data 
FROM a 
WHERE a.data = :data_1)
 SELECT TOP __[POSTCOMPILE_param_1] PERCENT WITH TIES results.id, results.data 
FROM results ORDER BY results.id

```

if we comment out the rule:

```diff
diff --git a/lib/sqlalchemy/dialects/mssql/base.py b/lib/sqlalchemy/dialects/mssql/base.py
index f23d05fcf5..1e4cc98681 100644
--- a/lib/sqlalchemy/dialects/mssql/base.py
+++ b/lib/sqlalchemy/dialects/mssql/base.py
@@ -2388,6 +2388,7 @@ class MSSQLCompiler(compiler.SQLCompiler):
     def order_by_clause(self, select, **kw):
         # MSSQL only allows ORDER BY in subqueries if there is a LIMIT
         if (
+            False and
             self.is_subquery()
             and not select._limit
             and (
```


then we get


```
WITH results AS 
(SELECT TOP __[POSTCOMPILE_param_2] WITH TIES a.id AS id, a.data AS data 
FROM a 
WHERE a.data = :data_1 ORDER BY a.id)
 SELECT TOP __[POSTCOMPILE_param_1] PERCENT WITH TIES results.id, results.data 
FROM results ORDER BY results.id

```

unclear if SQL Server supports the syntax being requested

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**comment out SQL Server order_by filter** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4899

**Comment by leonokubo** [comment]
> O problema aqui é que o SQL Server não permite ORDER BY em uma subconsulta, portanto, há uma regra codificada para impedir que ORDER BY apareça:
> 
> ```python
> from sqlalchemy import Column
> from sqlalchemy import Integer
> from sqlalchemy import String
> from sqlalchemy.dialects import mssql
> from sqlalchemy.orm import declarative_base
> from sqlalchemy.orm import query
> 
> Base = declarative_base()
> 
> 
> class A(Base):
>     __tablename__ = "a"
> 
>     id = Column(Integer, primary_key=True)
>     data = Column(String)
> 
> 
> a_table = A.__table__
> 
> 
> subquery = (
>     a_table.select()
>     .where(a_table.c.data == "x")
>     .fetch(with_ties=True, count=10)
>     .order_by(a_table.c.id)
> )
> 
> cc = subquery.cte("results")
> query = (
>     cc.select().fetch(with_ties=True, count=80, percent=True).order_by(cc.c.id)
> )
> 
> print(query)
> 
> print("------------------------")
> print(query.compile(dialect=mssql.dialect()))
> ```
> 
> a consulta do SQL Server é:
> 
> ```
> WITH results AS 
> (SELECT TOP __[POSTCOMPILE_param_2] WITH TIES a.id AS id, a.data AS data 
> FROM a 
> WHERE a.data = :data_1)
>  SELECT TOP __[POSTCOMPILE_param_1] PERCENT WITH TIES results.id, results.data 
> FROM results ORDER BY results.id
> ```
> 
> se comentarmos a regra:
> 
> ```diff
> diff --git a/lib/sqlalchemy/dialects/mssql/base.py b/lib/sqlalchemy/dialects/mssql/base.py
> index f23d05fcf5..1e4cc98681 100644
> --- a/lib/sqlalchemy/dialects/mssql/base.py
> +++ b/lib/sqlalchemy/dialects/mssql/base.py
> @@ -2388,6 +2388,7 @@ class MSSQLCompiler(compiler.SQLCompiler):
>      def order_by_clause(self, select, **kw):
>          # MSSQL only allows ORDER BY in subqueries if there is a LIMIT
>          if (
> +            False and
>              self.is_subquery()
>              and not select._limit
>              and (
> ```
> 
> então obtemos
> 
> ```
> WITH results AS 
> (SELECT TOP __[POSTCOMPILE_param_2] WITH TIES a.id AS id, a.data AS data 
> FROM a 
> WHERE a.data = :data_1 ORDER BY a.id)
>  SELECT TOP __[POSTCOMPILE_param_1] PERCENT WITH TIES results.id, results.data 
> FROM results ORDER BY results.id
> ```
> 
> não está claro se o SQL Server suporta a sintaxe solicitada

perfect, that's what I hope happens

**Comment by zzzeek** [comment]
OK here's the error

sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.


since the statement has TOP in it, we should be allowing the ORDER BY.

**Comment by leonokubo** [comment]
@zzzeek, 
if you put the limit in the subquery, the query removes the "with_ties"


PUT LIMIT:
WITH results AS 
(SELECT TOP __[POSTCOMPILE_param_2] bar.id AS id, bar.name AS name 
FROM bar 
WHERE bar.name = :name_1 ORDER BY bar.id)
 SELECT TOP __[POSTCOMPILE_param_1] PERCENT WITH TIES results.id, results.name 
FROM results ORDER BY results.id

WHITOUT LIMIT:

WITH results AS 
(SELECT TOP __[POSTCOMPILE_param_2] **WITH TIES** bar.id AS id, bar.name AS name 
FROM bar 
WHERE bar.name = :name_1)
 SELECT TOP __[POSTCOMPILE_param_1] PERCENT WITH TIES results.id, results.name 
FROM results ORDER BY results.id

**Comment by CaselIT** [comment]
That's expected, you can't specify voth fetch and limit, one wikl override the other

**Comment by leonokubo** [comment]
@CaselIT 
it's ok, but with you dont put LIMIT, the query remove "order_by"

**Comment by CaselIT** [comment]
Yes, that's a not implemented feature that it will be fixed

**Comment by zzzeek** [comment]
I'm fixing fetch(count=X, with_ties/percent).  What's this about LIMIT ?

**Comment by CaselIT** [comment]
IIRC limit and fetch work the same on mssql and both render top.

**Comment by leonokubo** [comment]
In my opinion, there are two problems,
- When I put a limit, it shouldn't remove the "with ties". 
- When not sending the limit, it does not remove the "order_by"

**Comment by CaselIT** [comment]
Fetch and limit are synonymous. Yes use fetch to set a limit

**Comment by zzzeek** [comment]
fetch and limit are not synonymous for SQLAlchemy, we use entirely different methods and syntaxes

**Comment by zzzeek** [comment]
all the code I see here is using .fetch(), so I am assuming we are talking about fetch clauses only

**Comment by CaselIT** [comment]
> fetch and limit are not synonymous for SQLAlchemy, we use entirely different methods and syntaxes

If i want to write `top 5` on mssql i can use `limit(5)` or `fetch(5)`. In that sense they are synonymous
