### ISSUE TITLE
Mixins unable to resolve 

### ISSUE THREAD

**Issue by Jmkernes** [sqlalchemy/sqlalchemy#10465]
### Describe the bug

When defining a mutually dependent relationship, mixins do not resolve after foreign key relationship checks, leading to missing foreign key errors. I sent an example of the simplest relationship, but the same holds true for a composite foreign key constraint as well.

By removing the IDMixin in the code example and directly specifying the primary key ids, this error disappears.

As a side note , alembic is unable to parse the foreign key relationships here as well.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/relationship_persistence.html#post-update

### SQLAlchemy Version in Use

2.0.16

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.10

### Operating system

OSX

### To Reproduce

```python
import uuid
import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column, DeclarativeBase

class Base(DeclarativeBase):
    pass

class IDMixin:
    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, server_default=sa.text("gen_random_uuid()"))

class Post(IDMixin, Base):
    __tablename__ = "posts"
    __table_args__ = (sa.UniqueConstraint("id", "user_id"),)

    name: Mapped[str]
    user_id: Mapped[uuid.UUID] = mapped_column(sa.ForeignKey("users.id"))

class User(IDMixin, Base):
    __tablename__ = "users"

    favorite_post_id = sa.Column(sa.Uuid, sa.ForeignKey("posts.id"))
    favorite_post: Mapped[Post] = relationship(
        Post,
        primaryjoin=favorite_post_id == Post.id,
        foreign_keys=favorite_post_id,
        post_update=True,
    )
    posts: Mapped[list[Post]] = relationship(
        Post, primaryjoin=id == Post.user_id, foreign_keys=Post.user_id
    )
```

### Error

```
sqlalchemy.exc.ArgumentError: Could not locate any simple equality expressions involving locally mapped foreign key columns for primary join condition 'posts.user_id = :user_id_1' on relationship User.posts.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or are annotated in the join condition with the foreign() annotation. To allow comparison operators other than '==', the relationship can be marked as viewonly=True.
```

**Comment by zzzeek** [comment]
you are using the Python built-in function [id](https://docs.python.org/3/library/functions.html#id) in your mapping, where I think you mean to refer to the column `User.id`.  Since `User.id` isn't set up until the classes are fully defined, use a lambda:

```
class User(IDMixin, Base):
    __tablename__ = "users"

    favorite_post_id = sa.Column(sa.Uuid, sa.ForeignKey("posts.id"))
    favorite_post: Mapped[Post] = relationship(
        Post,
        primaryjoin=favorite_post_id == Post.id,
        foreign_keys=favorite_post_id,
        post_update=True,
    )
    posts: Mapped[list[Post]] = relationship(
        Post, primaryjoin=lambda: User.id == Post.user_id, foreign_keys=Post.user_id
    )

```

docs at https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#late-evaluation-of-relationship-arguments
