### ISSUE TITLE
SQLAlchemy specifies the wrong version dependency for cx_Oracle.

### ISSUE THREAD

**Issue by vectro** [sqlalchemy/sqlalchemy#10470]
### Describe the bug

In 07678e0 we started using cx_Oracle identifies like `DB_TYPE_NVARCHAR`; however these were not added to `cx_Oracle` until version 8, and `setup.cfg` was never updated to reflect this new dependency.

As a result pip or poetry will allow SQLAlchemy 2.0.22 with cx_Oracle 7.3.0 which results in this error message:
```
AttributeError: module 'cx_Oracle' has no attribute 'DB_TYPE_NVARCHAR'
```

### SQLAlchemy Version in Use

2.0.22

### DBAPI (i.e. the database driver)

cx_Oracle

### Database Vendor and Major Version

N/A

### Python Version

3.9.6

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import create_engine
create_engine('oracle+cx_oracle://scott:tiger@host:1521/?service_name=hr')
```

### Error

(top of stack trace and venv directory redacted)
```
  File "<string>", line 2, in create_engine
  File ".venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File ".venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 614, in create_engine
    dialect = dialect_cls(**dialect_args)
  File "<string>", line 2, in __init__
  File ".venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File ".venv/lib/python3.9/site-packages/sqlalchemy/dialects/oracle/cx_oracle.py", line 1065, in __init__
    dbapi_module.DB_TYPE_NVARCHAR,  # used for CLOB, NCLOB
AttributeError: module 'cx_Oracle' has no attribute 'DB_TYPE_NVARCHAR'
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**amend cx_Oracle version checks, setup.cfg to oracle 8** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4922

**Comment by zzzeek** [comment]
thanks for reporting
