### ISSUE TITLE
regression due to #7744

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10479]
broke in 428262a2d5374613f4a4cf925bbd9e94e0e

```py
from sqlalchemy import column
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects import postgresql

expr = column("q", JSONB)["foo"].astext +  " " + column("q", JSONB)["bar"].astext

print(expr.compile(dialect=postgresql.dialect()))
```
expected:

    (q ->> %(q_1)s) || %(param_1)s || (q ->> %(q_2)s)

got:

    q ->> %(q_1)s || %(param_1)s || q ->> %(q_2)s

now what's really stupid is if you make it just a two-element expression, then it works:

```
expr = column("q", JSONB)["foo"].astext +  " "

```

produces

    (q ->> %(q_1)s) || %(param_1)s

which is because the "long expression chain" thing that's broken here is not coming into play

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement eager_grouping for expression clauselists** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4924
