### ISSUE TITLE
SQLAlchemy tries to give cx_Oracle more rows than it can handle.

### ISSUE THREAD

**Issue by vectro** [sqlalchemy/sqlalchemy#10482]
When trying to insert more than 2GB of data at a time using `cursor.executemany`, cx_Oracle fails with the error message `DPI-1015: array size of [number of items] is too large`. This behavior is documented [in the cx_Oracle documentation](https://cx-oracle.readthedocs.io/en/latest/api_manual/cursor.html#Cursor.executemany).

### SQLAlchemy Version in Use

2.0.22

### DBAPI (i.e. the database driver)

cx_Oracle

### Database Vendor and Major Version

Oracle  19c

### Python Version

3.9.6

### Operating system

Linux

### To Reproduce

```python
data_list = list(data_structure_over_2_gb)
conn.execute(table.insert(), data_list)
```

### Error

```
  File "[redacted]/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "[redacted]/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "[redacted]/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "[redacted]/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "[redacted]/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "[redacted]/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "[redacted]/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1938, in _exec_single_context
    self.dialect.do_executemany(
  File "[redacted]/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/oracle/cx_oracle.py", line 1431, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) DPI-1015: array size of [redacted] is too large
[SQL: INSERT INTO [redacted]([redacted]) VALUES ([redacted])]
[parameters: [[redacted]  ... displaying 10 of [redacted] total bound parameter sets ...  [redacted]]]
``` 

### Additional context

There is [a request](https://github.com/oracle/python-cx_Oracle/issues/200) to fix this in the cx_Oracle driver although it doesn't seem to have gotten much attention.

**Comment by vectro** [comment]
To be explicit, I think sqlalchemy should batch rows in this situation and give cx_Oracle less than 2GB at a time.

**Comment by vectro** [comment]
Also the [documentation for python-oracledb](https://python-oracledb.readthedocs.io/en/latest/api_manual/cursor.html#Cursor.executemany) mentions that it has the same issue / same 2 GB limit.

**Comment by zzzeek** [comment]
SQLAlchemy has no reasonable way to measure the "data size" of rows here, that's way outside our wheelhouse here and would also add a lot of upfront effort to the mechanics of bulk insert.   this is an unusual use case with an easy workaround when it occurs for the caller, since they know their data size, so this should be handled outside of SQLAlchemy.

**Comment by zzzeek** [comment]
to be clear, the issue here is not "cx_oracle has a max of 500K rows for executemany()", IIRC it's the total *data size* of all the rows added up.   which means for things like strings, to get the "Data size" we'd need to know the encoding and somehow figure out the encoded size (which means we do the encoding), etc., this is out of scope for us.

**Comment by vectro** [comment]
While I agree that figuring out the number of rows to batch is difficult, I think SQLAlchemy could do more here than throw up its hands:

1. One option would be to default to some reasonable batch size (say, 250,000 rows or less) that would cover most use cases.
2. Another would be to start with some batch size (could be all the rows) and then halve the batch size every time we see the DPI-1015 error.

That said, I respect the decision not to address this issue in SQLAlchemy.

**Comment by zzzeek** [comment]
> While I agree that figuring out the number of rows to batch is difficult, I think SQLAlchemy could do more here than throw up its hands:
> 
>     1. One option would be to default to some reasonable batch size (say, 250,000 rows or less) that would cover most use cases.

I could have an executemany with just 1000 rows and BLOBs of 100M each and it would fail the same way, so I dont see number of rows as anything we can go on


> 
>     2. Another would be to start with some batch size (could be all the rows) and then halve the batch size every time we see the DPI-1015 error.

that would be very surprising behavior of questionable efficiency, though there are ways to build extensions on your end that do this, if you think it's interesting (we have a hook right here: https://docs.sqlalchemy.org/en/20/core/events.html#sqlalchemy.events.DialectEvents.do_executemany )

it looks like cx_oracle / oracledb has the issue left opened so they still seem in favor of fixing on their end, where they have a lot more options to deal with this efficiently.

**Comment by zzzeek** [comment]
cc @CaselIT

**Comment by CaselIT** [comment]
I agree with what mike said.

At most what we could do is have an oracle execution option called `oracle_batch_row_number: int` or something similar to make the batching internal to sqlalchemy, but figuring out the number would still be the user responsibility.

regarding option 1 or 2, they are probably more appropriate for the driver to implement.

**Comment by CaselIT** [comment]
overall the solution here is 
```py
data_list = list(data_structure_over_2_gb)
while True:
  batch = data_list[:number_of_rows_in_bach]
  data_list[:number_of_rows_in_bach] = []
  conn.execute(table.insert(), batch )
  if not data_list:
    break
```

is I'm also -1 on adding something like `oracle_batch_row_number`
