### ISSUE TITLE
Typehints for declared_attr not working

### ISSUE THREAD

**Issue by ashish16052** [sqlalchemy/sqlalchemy#10485]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

I am trying to add types to declared_attr, but pylance (or even pyright) is failing to catch them (just shows Any).

<img width="291" alt="image" src="https://github.com/sqlalchemy/sqlalchemy/assets/86217607/7f3b5c64-98c1-40be-b122-f016e390beb3">

Expected version: Str  here.

Help me if I am conceptually wrong here.

### To Reproduce

```python
create a class with declared_attr, add a return type to it.

from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import as_declarative


@as_declarative()
class ClassA:
    @declared_attr
    def version(cls) -> str:
        return "Version"


print(ClassA.version)
```

### Versions

- OS: Ubuntu-22.04
- Python: 3.8
- SQLAlchemy: 1.4
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): pyright 1.1.331

**Comment by zzzeek** [comment]
hi -

the declared attr here is incorrect; when used for mapped elements, it needs to return `Mapped` as documented at https://docs.sqlalchemy.org/en/20/orm/declarative_mixins.html#composing-mapped-hierarchies-with-mixins .

additionally, the thing being returned can't be a plain string, it has to be a column / relationship element of some kind:


```py

from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import as_declarative, Mapped, mapped_column


@as_declarative()
class ClassA:
    @declared_attr
    def version(cls) -> Mapped[str]:
        return mapped_column(Integer)


reveal_type(ClassA.version)

```

pylance sees this correctly

![image](https://github.com/sqlalchemy/sqlalchemy/assets/128223/3d18640f-6a91-4fd8-8cae-8047d1cdccae)

**Comment by ashish16052** [comment]
Tried this, the issue persisted
<img width="421" alt="image" src="https://github.com/sqlalchemy/sqlalchemy/assets/86217607/ac1172e8-5528-4dad-b3fc-11f71fd00059">

```
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import Mapped, as_declarative, mapped_column


@as_declarative()
class ClassA:
    @declared_attr
    def version(cls) -> Mapped[str]:
        return mapped_column(Integer)

reveal_type(ClassA.version)
```

**Comment by zzzeek** [comment]
make sure you are on the latest vscode, pylance recently had a bug in this regard
