### ISSUE TITLE
remove False from ping() for mysqlclient; need to keep it for pymysql but at the same time watch out for removal

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10492]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10489

see thread at https://github.com/PyMySQL/mysqlclient/discussions/651#discussioncomment-7308971

we need to remove the False call for mysqlclient immediately, and probably apply introspection to the pymysql version to make sure we are either sending False or we are checking that it no longer accepts an argument.   

we should backport and release for 1.4.x also

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**revise argument to mysqlclient/pymysql ping** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4926
