### ISSUE TITLE
Make ORM private api more explicitly so

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10497]
Related to the discussion in https://github.com/sqlalchemy/sqlalchemy/discussions/10474

Rename function to have underscore in them / rename private modules to have an udnerstore.
This in an attempt to discourage usage of private ORM api by 3-rd party library.

If such api is required then a clear feature request should be done to see if it can be accommodated using alternative public api or if the creation of such public api can be done

**Comment by zzzeek** [comment]
attributes.py is not "private" in total, im not sure we can underscore whole modules at this point as there are public functions in attributes.py that people may be importing

**Comment by zzzeek** [comment]
the only way to do this issue "legit" is to rename everything in `sqlalchemy.orm` to `_attributes.py`, `_registry.py`, `_decl_api.py` etc.    which then implies renaming .py files throughout the whole library.   IMO this is not worth the effort.

What I'll do here is rename what was brought up in #10474 (which I think will break sqlalchemy-utils again) and maybe some other things.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**apply underscores to ORM class and def names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5571

**Comment by zzzeek** [comment]
this should cover it

**Comment by CaselIT** [comment]
change looks ok for me.
