### ISSUE TITLE
first_init event has zero testing and is broken likely for years

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10500]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10499

no idea why there's no test coverage for this, does not work in 1.4 either

**Comment by CaselIT** [comment]
Considering that it's been broken for more than 2 years without any report until now, would it make sense to remove it?

**Comment by zzzeek** [comment]
it would !  I have no idea what this event would be useful for

**Comment by zzzeek** [comment]
yah the issue is that all the `InstanceEvents` have the same calling form, receiving the "target" object first.  this one has a different calling form.  the generic "wrap" for the events that sends an object instead of a state to the user-defined listener fails on this one since it's a different argument signature.

**Comment by zzzeek** [comment]
let's just take it out in 2.1

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**remove first_init** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5565
