### ISSUE TITLE
support NULL passed through literal_processor

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10535]
right now a None value that's passed through the compiler for literal_processor() is passed in, and none of the handlers expect None and just return None, where the compiler then renders nothing.  

Changes should be as follows:

1. the compiler, when it sees the value is None, returns the string NULL or otherwise uses a render_null() method of some kind; it does **not** send the data to the literal_processor() for the type, **unless** should_evaluate_none on the type is set
2. all the types that have literal_processor() and do not have "should_evaluate_none" can assume the value passed is non None
3. tests for JSON/JSONB doing "evaluate none" style tests should be added; the base test_literal_round_trip() suite should do a NULL round trip for all datatypes

this could be a 2.0 thing or a 2.1 thing

**Comment by zzzeek** [comment]
since I'm tryring to do #9737 let's just do it

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**accommodate NULL at the compiler level for literal_render** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4937
