### ISSUE TITLE
Allow `binds` arg to be a callable?

### ISSUE THREAD

**Issue by nilsso** [sqlalchemy/sqlalchemy#10543]
### Describe the use case

In using the Litestar framework I've ran into a problem with having a session config with multiple engines, boiling down to the `binds` argument to `Session`. It wants to essentially pickle the session config, with the problem being [engine objects aren't pickleable](https://github.com/sqlalchemy/sqlalchemy/discussions/7308).

I'd like to propose passing a callable that returns the expected binds dictionary.

I've tried out the following modifications to `sqlalchemy/orm/session.py` and it's seemed to work so far, but I might just be too naïve.

```py
_SessionBindKey = Union[Type[Any], "Mapper[Any]", "TableClause", str]
_SessionBind = Union["Engine", "Connection"]
_SessionBinds = Dict[_SessionBindKey, _SessionBind]  # NEW
_SessionBindsArg = Union[_SessionBinds, Callable[[], _SessionBinds]]  # NEW

...

class Session(_SessionClassMethods, EventTarget):
    ...
    def __init__(..., binds: Optional[_SessionBindArg] = None):
        ...
        if binds is not None:
            if hasattr(binds, "__call__"):  # NEW
                binds = binds()
            for key, bind in binds.items():
                self._add_bind(key, bind)
```

### Databases / Backends / Drivers targeted

Any?

### Example Use

```py
def make_binds():
    engine_a = Engine(...)
    engine_b = Engine(...)
    return {
        TableA: engine_a,
        TableB: engine_b,
    }

sessionmaker(binds=make_binds)
```

**Comment by zzzeek** [comment]
> ### Describe the use case
> 
> In using the Litestar framework I've ran into a problem with having a session config with multiple engines, boiling down to the `binds` argument to `Session`. It wants to essentially pickle the session config, 

that's not a valid usecase.  there is no reason to pickle a `Session` object, as the session represents an ongoing database transaction.  

There are certainly patterns involving caching of objects and such that use pickling, such as the [dogpile caching](https://docs.sqlalchemy.org/en/20/orm/examples.html#module-examples.dogpile_caching) example, but these are hooks that pickle individual objects and restore them to new `Session` objects as needed.

> I'd like to propose passing a callable that returns the expected binds dictionary.

you can make a `Session` that uses a callable for binds [following this example for custom vertical partitioning](https://docs.sqlalchemy.org/en/20/orm/persistence_techniques.html#custom-vertical-partitioning).

**Comment by nilsso** [comment]
Thanks for the reply and for the example using callable. I'll close this as it's probably more a usage issue than anything to do with SQA.
