### ISSUE TITLE
sqlalchemy memory leak？

### ISSUE THREAD

**Issue by dobet** [sqlalchemy/sqlalchemy#10566]
### Describe the bug

I use sqlalchemy 1.3.20, my memory keeps increasing. Is there a memory leak bug in this version?

I use memroy_profiler and heap to record memory, the sqlalchemy object memory keeps increasing.

### SQLAlchemy Version in Use

1.3.20

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

mysql5.7

### Python Version

3.6.8

### Operating system

linux

### To Reproduce

```python
no
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
``` 

no error

**Comment by CaselIT** [comment]
Hi,

Don't know, likely not.

Since you haven't provided any examples or snippet or even a description of what you are doing that's the only answer that can be given.

Feel free to reopen of you can provide an example instead of "no"
