### ISSUE TITLE
many-to-many associaton table containing hyphen

### ISSUE THREAD

**Issue by jaruji** [sqlalchemy/sqlalchemy#10563]
### Describe the bug

Hello,

I encountered an issue when attempting to model a many-to-many relationship in Sql alchemy ORM between two tables. I assume this issue is caused by a hyphen in the name of the association table - I do have a identical example set up for a different relationship, in which the association table has '_' instead of '-', and everything works smoothly. The issue is that I can't currently afford to rename this specific association table, as it would break multiple things. I wonder if there is something obvious I'm missing? And if there is not, is there a way to bypass this issue? Help would be much appreciated! 

The code provided is a small snippet, with all the other relationships stripped.

### SQLAlchemy Version in Use

2.0.22

### DBAPI (i.e. the database driver)

pyodbc

### Database Vendor and Major Version

Azure SQL Database (SQL Server)

### Python Version

3.9.6

### Operating system

Windows

### To Reproduce

```python
class WineTag(Base):
    __tablename__ = "WineTag"

    id = Column(Integer, primary_key=True, index=True)
    value = Column(String(255), nullable=False)

class CompanyWineWineTag(Base):
    __tablename__ = "CompanyWine-WineTag"

    id = Column(Integer, primary_key=True, index=True)
    companyWineId = Column(
        Integer, ForeignKey("Company-Wine.id", ondelete="CASCADE"), nullable=False
    )
    wineTagId = Column(
        Integer, ForeignKey("WineTag.id", ondelete="CASCADE"), nullable=False
    )

class CompanyWine(Base):
    __tablename__ = "Company-Wine"

    id = Column(Integer, primary_key=True)
    createdAt = Column(DATETIME2, nullable=False, server_default=text("(getdate())"))
    companyId = Column(ForeignKey("Company.id", ondelete="SET NULL"))
    supplier = Column(Unicode(100))
    producer = Column(Unicode(100))
    url = Column(Unicode(255))
    volume = Column(Float(53))
    packaging = Column(Unicode(100))

    tags = relationship(
        "WineTag",
        secondary="CompanyWine-WineTag",
    )
```

### Error

```
unsupported operand type(s) for -: 'Table' and 'Table'
```

**Comment by zzzeek** [comment]
as [documented](https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#using-a-late-evaluated-form-for-the-secondary-argument-of-many-to-many) using a string here is an evaluated Python expression, so since you have an unusual table name, please use a lambda:

```
    tags = relationship(
        "WineTag",
        secondary=lambda: CompanyWineWineTag.__table__
    )

```

**Comment by zzzeek** [comment]
I've rearranged the docs in 527fac5457153154d9e4c to emphasize the lambda form here as generally better and added caveats to the current "eval()" form of "secondary".   We should look into "secondary" not being an eval since I'm not sure why it's like that.

**Comment by jaruji** [comment]
Exactly what I was looking for, not sure how I overlooked this in the docs. Thank you for your help!
