### ISSUE TITLE
figure out why "secondary" uses eval() and if not a good reason, change it

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10564]
I dont really know why secondary uses eval.  it should be string name of table, possibly schema qualified, looked up in metadata.  i can't think of a valid Python expression one would need there instead where they would not use lambda.

See #10563.

**Comment by msavinash** [comment]
It's to support [late evaluation of relationship arguments](https://github.com/sqlalchemy/sqlalchemy/blob/main/doc/build/orm/basic_relationships.rst#late-evaluation-of-relationship-arguments). Basically if the value of "secondary" is known only at runtime, after evaluation of some condition. I guess it is to support more flexibility of database operations. The documentation heavily states that this is a potential vulnerability though.

**Comment by zzzeek** [comment]
> It's to support [late evaluation of relationship arguments](https://github.com/sqlalchemy/sqlalchemy/blob/main/doc/build/orm/basic_relationships.rst#late-evaluation-of-relationship-arguments). Basically if the value of "secondary" is known only at runtime, after evaluation of some condition. I guess it is to support more flexibility of database operations. The documentation heavily states that this is a potential vulnerability though.

I didn't say it shouldn't be accepted as a string, just that the string itself does not need to be python-evaluated

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**lookup "secondary" directly, dont use eval()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5566
