### ISSUE TITLE
bind substitution fails for selectinload / lazyload + with_expression

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10570]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10569

all the way in to how selectinload applies bind substitution

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import query_expression
from sqlalchemy.orm import relationship
from sqlalchemy.orm import selectinload
from sqlalchemy.orm import Session
from sqlalchemy.orm import with_expression
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    boolean = query_expression()
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs=[B(data="a"), B(data="b"), B(data="c")]))
s.commit()

def go(x):
    with Session(e) as sess:
        return sess.execute(
            select(A).options(
                selectinload(A.bs).options(
                    with_expression(B.boolean, x)
                )
            )
        ).scalars().all()

for a in go(B.data < 'c'):
    for b in a.bs:
        print(f"data: {b.data}  boolean: {b.boolean}")

# works, the expression changes from < to ==
for a in go(B.data == 'b'):
    for b in a.bs:
        print(f"data: {b.data}  boolean: {b.boolean}")

# but bind substitution gets stuck
for a in go(B.data == 'c'):
    for b in a.bs:
        print(f"data: {b.data}  boolean: {b.boolean}")

```

same issue for lazyload.  subqueryload seems to not have the problem.

**Comment by CaselIT** [comment]
> same issue for lazyload. subqueryload seems to not have the problem.

joined too seems to work

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**something something something** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4941

**Comment by zzzeek** [comment]
OK this is not a bug in caching directly, it's not the bound parameter thing etc.   it has to do with the loader options being extracted from the cached ORM context.    the second version of the parameter is just gone.  I feel like I've seen this before, as....it's not really solvable without building some dramatic new mechanism into the ORM.   but maybe there is something that's supposed to be doing this.

**Comment by zzzeek** [comment]
OK.  we do all this stuff for with_loader_criteria(), but not with_expression().  so there's precedent for all of this that has to be applied here
