### ISSUE TITLE
DeclarativeBase and TypeVar breakage

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#10593]
### Describe the typing issue

Not sure if this is something with SQLAlchemy or Mypy, although pretty minor. If I try to use a model class with aiohttp 3.9's AppKey, it results in a type error. Other classes work fine though.

### To Reproduce

Minimal reproducer without aiohttp:
```python
from typing import Generic, TypeVar
from sqlalchemy.orm import DeclarativeBase

class Base(DeclarativeBase):
    ...

class Foo(Base):
    ...

T = TypeVar("T")

class AppKey(Generic[T]):
    ...

class Application:
    def __setitem__(self, key: AppKey[T], value: T) -> None:
        ...


a = Application()
k = AppKey[type[Foo]]()

a[k] = Foo
```

### Error

```
error: Cannot infer type argument 1 of "__setitem__" of "Application"  [misc]
```

The error is pretty confusing, which is reported under https://github.com/python/mypy/issues/12012
But, basically means the assignment is not the correct type (i.e. It doesn't recognise it as `type[Foo]`).

### Versions

- SQLAlchemy: 2.0.21
- Type checker: mypy 1.6.1

### Additional context

Remove `DeclarativeBase` from the example and it type checks correctly.

**Comment by CaselIT** [comment]
Hi,

The issue seems to be of mypy. The following has the same error
```py
from typing import Generic, TypeVar

class Meta(type):
    ...

class Base(metaclass=Meta):
    ...

class Foo(Base):
    ...

T = TypeVar("T")

class AppKey(Generic[T]):
    ...

class Application:
    def __setitem__(self, key: AppKey[T], value: T) -> None:
        ...


a = Application()
k = AppKey[type[Foo]]()

a[k] = Foo
```

You can use `DeclarativeBaseNoMeta` if you don't need the features of the normal base. https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.DeclarativeBaseNoMeta

**Comment by Dreamsorcerer** [comment]
> You can use `DeclarativeBaseNoMeta` if you don't need the features of the normal base. https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.DeclarativeBaseNoMeta

Thanks, seems to work at runtime, but I get this additional error from mypy:
`error: "object" has no attribute "relationships"`
With:
```
            mapper = sa.inspect(model)
            assert mapper is not None
            for name, relationship in mapper.relationships.items():
```
When model is defined as `type[DeclarativeBase] | type[DeclarativeBaseNoMeta]` (doesn't seem to be a base class to allow both?). So, seems that `sa.inspect()` ends up returning `object` when given a union of either base types.

**Comment by CaselIT** [comment]
this seems again an issue with mypy

**Comment by CaselIT** [comment]
without sqlalchemy
```py
from typing import Protocol, TypeVar


class X:
    i: int


class Y:
    i: str


_T = TypeVar("_T")


class P(Protocol[_T]):
    i: _T


def go(i: P[_T]) -> _T:
    return i.i


def fn(a: X, b: Y) -> None:
    reveal_type(go(a))
    reveal_type(go(b))


def fnu(a: X | Y) -> None:
    reveal_type(go(a))
```

in general mypy has a lot of issue with unions.
pyright works correctly there

**Comment by Dreamsorcerer** [comment]
Well, reading a little into the differences of mypy/pyright, this could easily be improved for mypy by having a common base class. i.e. The common base class of DeclarativeBase/DeclarativeBaseNoMeta is presumably object currently, and so that's what mypy infers:
https://microsoft.github.io/pyright/#/mypy-comparison?id=unions-vs-joins
