### ISSUE TITLE
Engine with illegal windows filename causes infinite loop and missing error messages

### ISSUE THREAD

**Issue by stekow** [sqlalchemy/sqlalchemy#10602]
### Describe the bug

There are some illegal file names on Windows, like 'CON', 'PRN', 'AUX', 'NUL', 'COM1', etc. If you create an engine with one of them:

`engine = create_engine('sqlite:///CON') `

There is no error message. The expected behaviour should be this exception:

`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file`

After that you can try to use the engine for something like this:

```
Base = declarative_base()
Base.metadata.drop_all(engine)
```

The result is that SQLAlchemy ends in an infinite loop. It's possible that other operations with this "broken" engine will throw different errors or react in other strange ways. I only tested this case.

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

pysqlite

### Database Vendor and Major Version

SQLite

### Python Version

3.11

### Operating system

Windows

### To Reproduce

```python
import unittest

from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base


Base = declarative_base()
class TestSQLAlchemy(unittest.TestCase):
    def test_drop(self):
        engine = create_engine('sqlite:///CON')
        self.assertIsNone(Base.metadata.drop_all(engine))

if __name__ == '__main__':
    unittest.main()
```

### Error

Infinite loop. No error messages.

**Comment by CaselIT** [comment]
Hi,

I'm more on the won't fix camp here.
What's the use case for this?

Also this seems to be caused built-in sqlite3 library.
If you try this you get the same issue
```
import sqlite3
sqlite3.connect('sqlite:///CON')
```

**Comment by CaselIT** [comment]
Feel free to report it to the python issue tracker

**Comment by stekow** [comment]
> Feel free to report it to the python issue tracker

Okay. 

https://github.com/python/cpython/issues/111851

**Comment by stekow** [comment]
> I'm more on the won't fix camp here. What's the use case for this?

I encountered this problem when creating connection strings from user input.
