### ISSUE TITLE
Mypy error when passing a Python list to `any_`

### ISSUE THREAD

**Issue by Apakottur** [sqlalchemy/sqlalchemy#10626]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

Mypy reports that the `any_` function does not accept objects of type `list[str]`, even though it does.

### To Reproduce
I am trying to generate the following Postgresql query with SQLAlchemy:

```sql
SELECT user_account.first_name FROM user_account WHERE user_account.first_name ILIKE ANY (ARRAY['bob','alice'])
```

I have the following Python code:
```python
from sqlalchemy import select, any_
q = select(UserAccount.first_name).where(UserAccount.first_name.ilike(any_(["bob", "alice"])))
```

The code runs the correct query on the DB and works well, but I get the type error:
```txt
error: Argument 1 to "any_" has incompatible type "list[str]"; expected "ColumnElement[Never] | _HasClauseElement | SQLCoreOperations[Never] | ExpressionElementRole[Never] | Callable[[], ColumnElement[Never]] | LambdaElement"  [arg-type]
```

### Versions

- OS: Ubuntu 22.04
- Python: 3.11
- SQLAlchemy: 2.0.23
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.7.0

**Comment by CaselIT** [comment]
Hi,

that's the expected behaviour, since the query you wrote will lead to sql that's not executable by most pg drivers. The outlier here is psycopg2.

use `array()` instead
```py
from sqlalchemy import select, any_
from sqlalchemy.dialects import postgresql
q = select(UserAccount.first_name).where(UserAccount.first_name.ilike(any_(postgresql.array(["bob", "alice"]))))
```

(I'm assuming postgresql here)
```

**Comment by zzzeek** [comment]
that's not the documented API for any_() and I have no idea how that is working.  what driver is that?

**Comment by CaselIT** [comment]
> that's not the documented API for any_() and I have no idea how that is working. what driver is that?

this is psycopg2 that sees a %s and will happily place anything there

**Comment by Apakottur** [comment]
Ah cool, did not know I needed to use `postgresql.array` explicitely. The query @CaselIT suggested works great.

I am using asyncpg.

**Comment by CaselIT** [comment]
> I am using asyncpg.

strange that is works with asyncpg. I guess it's able to infer list -> array.
