### ISSUE TITLE
Use PEP-646 instead of tuple workaround

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10635]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/10633

<div type='discussions-op-text'>

<sup>Originally posted by **uriyyo** November 14, 2023</sup>
Latest `mypy` version `1.7.0` supports `PEP 646`. It will be great if `sqlachemy` will use it instead of the current tuple workaround.|

Example:
```py
from typing_extensions import reveal_type

from sqlalchemy import create_engine, select, null, Integer, Float, Text

engine = create_engine('sqlite:///:memory:', echo=True)

stmt = select(
    null().cast(Integer),
    null().cast(Float),
    null().cast(Text),
)

reveal_type(stmt)

with engine.connect() as conn:
    res = conn.execute(stmt)
    reveal_type(res)

    for a, b, c in res:
        reveal_type(a)
        reveal_type(b)
        reveal_type(c)
```
```py
temp.py:13: note: Revealed type is "sqlalchemy.sql.selectable.Select[Tuple[builtins.int, builtins.float, builtins.str]]"
temp.py:17: note: Revealed type is "sqlalchemy.engine.cursor.CursorResult[builtins.int, builtins.float, builtins.str]"
temp.py:20: note: Revealed type is "builtins.int"
temp.py:21: note: Revealed type is "builtins.float"
temp.py:22: note: Revealed type is "builtins.str
```

It will require to make breaking changes to `Row`, `Result`, .etc. But it will eliminate `.t`, `.tuple`, `.tuple()`, .etc workarounds.</div>

**Comment by zzzeek** [comment]
I worked a lot with pep-646 here and did not find a way for it to be helpful here.   I see theres a PR but I'm still skeptical it can be made effective as there is no "Map" operator.  See https://github.com/python/typing/discussions/1001 . 

can someone comment on the above discussion why that doesn't apply here?

**Comment by zzzeek** [comment]
also see https://github.com/sqlalchemy/sqlalchemy/pull/10276.  are we continuing with what's there?

**Comment by CaselIT** [comment]
seems that there are two different but similar implementations:
- https://github.com/sqlalchemy/sqlalchemy/pull/10634
- https://github.com/mehdigmira/sqlalchemy/pull/2 (that started from https://github.com/sqlalchemy/sqlalchemy/pull/10276)

**Comment by sqla-tester** [comment]
**Yurii Karabas** has proposed a fix for this issue in the **main** branch:

**Add PEP 646 integration** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4986

**Comment by sqla-tester** [comment]
**Yurii Karabas** has proposed a fix for this issue in the **main** branch:

**Add PEP 646 integration** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4986
