### ISSUE TITLE
SQLAlchemy 1.4.50 marked as Python2.7-compatible but is not

### ISSUE THREAD

**Issue by rsanden-deca** [sqlalchemy/sqlalchemy#10652]
### Describe the bug

Python 2.7 `pip2 install SQLAlchemy` now fails with `SyntaxError: invalid syntax`  when compiling `sqlalchemy/ext/mypy/plugin.py` and other type-annotated files. This breaks builds for (frozen, often intranet-only) legacy applications.

This is being caused by SQLAlchemy 1.4.50 being marked as `>=2.7` [on PyPI](https://pypi.org/project/SQLAlchemy/1.4.50/).

Please mark **1.4.50** as non-compatible with Python 2.7, so that pip2 will continue to pick up **1.4.49** and install successfully.

### SQLAlchemy Version in Use

1.4.50

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

2.7

### Operating system

Debian Stretch

### To Reproduce

```python
pip2 install SQLAlchemy
```

### Error

```
    byte-compiling /usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/mypy/plugin.py to plugin.pyc
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/mypy/plugin.py", line 46
        self, fullname: str
                      ^
    SyntaxError: invalid syntax
```

**Comment by CaselIT** [comment]
Hi,

There were no change between 49 and 50 to the mypy plugin: https://github.com/sqlalchemy/sqlalchemy/compare/rel_1_4_49...rel_1_4_50

Also said plugin is not imported by default by anything in sqlalchemy, so don't import it in the code

**Comment by CaselIT** [comment]
Also the code for that plugin has always been annotated. Here is 1.4.0 code
https://github.com/sqlalchemy/sqlalchemy/blob/e769ba4b00859ac8c95610ed149da4d940eac9d0/lib/sqlalchemy/ext/mypy/decl_class.py#L76

**Comment by rsanden-deca** [comment]
That's odd, then. I just tested this again:
```
root@some-debian-stretch-container:~# pip2 install SQLAlchemy==1.4.49
Collecting SQLAlchemy==1.4.49
  Downloading https://files.pythonhosted.org/packages/4a/e0/79a08e64a6440c632f3d657fe76a2eb8cf29571cfa3318c44aa669193682/SQLAlchemy-1.4.49-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.6MB)
    100% |################################| 1.6MB 1.2MB/s 
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python2.7/dist-packages (from SQLAlchemy==1.4.49)
...
...
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2; python_version < "3"->importlib-metadata; python_version < "3.8"->SQLAlchemy==1.4.49)
Installing collected packages: SQLAlchemy
Successfully installed SQLAlchemy-1.4.49
```

root@some-debian-stretch-container:~# pip2 install SQLAlchemy==1.4.50
Collecting SQLAlchemy==1.4.50
  Downloading https://files.pythonhosted.org/packages/5a/0a/dabe332c40afebb0a979d3e66b34570fce2f8611bae19b186f0c69f54643/SQLAlchemy-1.4.50.tar.gz (8.5MB)
    100% |################################| 8.5MB 229kB/s 
  Ignoring greenlet: markers 'python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))))' don't match your environment
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python2.7/dist-packages (from SQLAlchemy==1.4.50)
Requirement already satisfied: configparser>=3.5; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from importlib-metadata; python_version < "3.8"->SQLAlchemy==1.4.50)
...
...
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2; python_version < "3"->importlib-metadata; python_version < "3.8"->SQLAlchemy==1.4.50)
Building wheels for collected packages: SQLAlchemy
  Running setup.py bdist_wheel for SQLAlchemy ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-TPKMBj/SQLAlchemy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpJL6sv5pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/sqlalchemy
  ...
  ...
      byte-compiling /usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/mypy/plugin.py to plugin.pyc
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/mypy/plugin.py", line 46
        self, fullname: str
                      ^
    SyntaxError: invalid syntax
    ```
    
    For some reason, `pip2 install SQLAlchemy==1.4.50` performs a wheel build (which fails) whereas 1.4.49 does not.
    
    I figured that this was a matter of 1.4.50 not being python2-compatible, but maybe not.

**Comment by CaselIT** [comment]
I also can't reproduce on 2.7:
```
podman run -ti python:2.7 bash
root@722d9bf77d52:/# pip install -U pip
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pip
  Downloading pip-20.3.4-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 4.6 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-20.3.4
root@722d9bf77d52:/# pip install sqlalchemy
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting sqlalchemy
  Downloading SQLAlchemy-1.4.50.tar.gz (8.5 MB)
     |████████████████████████████████| 8.5 MB 4.3 MB/s
Requirement already satisfied: importlib-metadata in /usr/local/lib/python2.7/site-packages (from sqlalchemy) (1.6.0)
Requirement already satisfied: contextlib2; python_version < "3" in /usr/local/lib/python2.7/site-packages (from importlib-metadata->sqlalchemy) (0.6.0.post1)
Requirement already satisfied: pathlib2; python_version < "3" in /usr/local/lib/python2.7/site-packages (from importlib-metadata->sqlalchemy) (2.3.5)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python2.7/site-packages (from importlib-metadata->sqlalchemy) (1.2.0)
Requirement already satisfied: configparser>=3.5; python_version < "3" in /usr/local/lib/python2.7/site-packages (from importlib-metadata->sqlalchemy) (4.0.2)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from pathlib2; python_version < "3"->importlib-metadata->sqlalchemy) (1.14.0)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/lib/python2.7/site-packages (from pathlib2; python_version < "3"->importlib-metadata->sqlalchemy) (1.10.0)
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.4.50-cp27-cp27mu-linux_x86_64.whl size=1613694 sha256=1cf2ebd7d8c48a62601aa8fa2ee1a461c1ef216badea31e9b2ad15ca54964d93
  Stored in directory: /root/.cache/pip/wheels/03/cc/9a/a75e2fce03b54389d23deb4a1aa5f8592c0c86a3d245021ad6
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-1.4.50
```

**Comment by rsanden-deca** [comment]
Okay, thanks for checking! Cheers.

**Comment by CaselIT** [comment]
> byte-compiling /usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/mypy/plugin.py to plugin.pyc

I think you have a setting that tries to byte compile every file enabled.
Likely this flag of pip
> --compile                   Compile Python source files to bytecode
