### ISSUE TITLE
Postgres VARCHAR fields mapped to enums serialize to strings in relationships

### ISSUE THREAD

**Issue by joel-olazagasti** [sqlalchemy/sqlalchemy#10653]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

When defined a mapped column as VARCHAR on the DB side, and a StrEnum on the mapped side, records pulled from a relationship serialize that column into `str` literals, and not the enum member. Records from the table properly serialize to the enum member when queried directly.

### To Reproduce

```python
class User(Base):
    __tablename__ = "users"
    id: Mapped[UUID] = mapped_column(primary_key=True, default_factory=uuid4)
    cake_preference: Mapped[List["Cake"]] = relationship(
        "Cake",
        init=False,
    )


class Cake(base):
    __tablename__ = "cakes"
    id: Mapped[UUID] = mapped_column(primary_key=True, default_factory=uuid4)
    favorite_type: Mapped["CakeType"] = mapped_column(
        "cake_type",
        VARCHAR,
        nullable=False,
        default=CakeType.vanilla,
    )
    user_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE")
    )

user = session.get_one(User,$UUID)
for cake in user.cake_preference:
    assert isinstance(cake.favorite_type, str)
```

### Error

```
# Copy the complete text of any errors received by the type checker(s).
``` 
The above assertion is true, when it should not be.

### Versions

- OS:Mac & Linux
- Python: 3.11.2
- SQLAlchemy: 2.0.21
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc):

**Comment by CaselIT** [comment]
Hi,

This is the expected behaviour. The type you pass to `mapped_column` has precedence over whatever is provided as type annotation.
To get enums back use the `Enum` type with `native_enum=False`
