### ISSUE TITLE
Add local column in dependency rule error message

### ISSUE THREAD

**Issue by jvllmr** [sqlalchemy/sqlalchemy#10668]
### Describe the use case

I am currently migrating a rather large codebase to SQLAlchemy 2.0 and encountered the `Dependency rule tried to blank-out primary key...` error. I already know how to fix it in the codebase, but it took me like 20 minutes to fix it because the specified object has more than one affected relationship. I finally realised it when I printed out the local column before-hand.

I think it could be very handy if the error message contains the name of the local column.
My proposal would be: `Dependency rule on column '<local column>' tried to blank-out primary key column '<remote column>' on instance '<instance>'`

### Databases / Backends / Drivers targeted

*

### Example Use

The snippet from the codebase where the info about the local column would have helped (of course there are a lot more columns and methods involved in the real thing. I would have found my mistake immediately otherwise 😺 ):

```python

class Cable(DeclarativeBase):
    pnr: sa_orm.Mapped[int] = Column(Integer(), primary_key=True)
    id: sa_orm.Mapped[int] = Column(Integer(), primary_key=True)
    # error causing relationships come after

class Device(DeclarativeBase):
    pnr: sa_orm.Mapped[int] = Column(Integer(), primary_key=True)
    id: sa_orm.Mapped[int] = Column(Integer(), primary_key=True)
    # error causing relationships come after

class CadCableSide(DeclarativeBase):
    __tablename__ = "cad_cable_side"
   
    __table_args__ = (  # {{{
        ForeignKeyConstraint(["pnr"], ["project.pnr"], ondelete="CASCADE"),
        ForeignKeyConstraint(
            ["pnr", "device_id"],
            ["device.pnr", "device.id"],
            name="cad_cable_side_device_fk",
            ondelete="SET NULL",
        ),
        ForeignKeyConstraint(
            ["pnr", "cable_id"],
            ["cable.pnr", "cable.id"],
            name="cad_cable_side_cable_fk",
            ondelete="CASCADE",
        ),
    )

    pnr: sa_orm.Mapped[int] = Column(Integer(), primary_key=True)
    cable_id = Column(Integer, nullable=False)
    device_id = Column(Integer(), nullable=True)

    # error causing relationships come after

```

Deleting a cable or a device both result in the error because of the `pnr` column in both foreign keys. In my example I was trying to patch the CadCableSide->Cable relationship although I should have migrated CadCableSide->Device relationship instead. But the error message only said `Dependency rule tried to blank-out primary key column 'cad_cable_side.pnr' on instance '<CadCableSide ...>'`

**Comment by zzzeek** [comment]
sure, as long as it uses the already-existing stringfication facilities as we dont want it incurring any new operations when it stringifies. thanks!

**Comment by sqla-tester** [comment]
**Jan Vollmer** has proposed a fix for this issue in the **main** branch:

**Fixes: #10668 add local column to dependency rule error message** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4977

**Comment by sqla-tester** [comment]
**Jan Vollmer** has proposed a fix for this issue in the **main** branch:

**add local column to dependency rule error message** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4977

**Comment by sqla-tester** [comment]
**Jan Vollmer** has proposed a fix for this issue in the **rel_2_0** branch:

**add local column to dependency rule error message** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4955
