### ISSUE TITLE
use quote_plus to encode for string url

### ISSUE THREAD

**Issue by jachien** [sqlalchemy/sqlalchemy#10662]
### Describe the bug

sqlalchemy.engine.url.URL's [render_as_string](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/engine/url.py#L629) function [url encodes](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/engine/url.py#L910C39-L910C43) some but not all characters for passwords.

I expect the output of `render_as_string` to url encode all necessary characters for a db url.

### SQLAlchemy Version in Use

1.4.41

### DBAPI (i.e. the database driver)

n/a

### Database Vendor and Major Version

n/a

### Python Version

3.8

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import create_engine
import urllib

password = urllib.parse.quote_plus("notareal[password]")
db_url = f"postgresql+pg8000://scott:{password}@localhost:5432/mydatabase"
print(db_url)
# postgresql+pg8000://scott:notareal%5Bpassword%5D@localhost:5432/mydatabase

engine = create_engine(db_url)
print(engine.url.render_as_string(hide_password=False))
# postgresql+pg8000://scott:notareal[password]@localhost:5432/mydatabase
# The password is no longer url encoded.
```

### Error

I am using AWS xray which monkey patches `Session`. The [monkey patched code](https://github.com/aws/aws-xray-sdk-python/blob/master/aws_xray_sdk/ext/sqlalchemy_core/patch.py#L17C27-L17C28) uses `urllib.parse.urlparse` on the string returned by URL's `render_as_string`. 

One of my passwords included a square bracket. Because square brackets are not url encoded by `render_as_string`, this leads to `urlparse` interpreting the db url as an invalid IPv6 url. This breaks xray functionality and logs an error:

```
[ERROR] Error parsing sql metadata.
Traceback (most recent call last):
  File "/var/task/aws_xray_sdk/ext/sqlalchemy_core/patch.py", line 22, in _sql_meta
    url = urlparse(str(engine_instance.engine.url))
  File "/var/lang/lib/python3.8/urllib/parse.py", line 384, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/var/lang/lib/python3.8/urllib/parse.py", line 486, in urlsplit
    raise ValueError("Invalid IPv6 URL")
```

### Additional context

Is there any reason why sqlalchemy is only [url encoding specific characters](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/engine/url.py#L909-L910) instead of using `urllib.parse.quoteplus`?

**Comment by zzzeek** [comment]
likely historical compatibility with the function.  however I can only target this at 2.1 which wont be in production for many months.   I would advise reporting this to AWS xray where they should use SQLAlchemy's URL parsing and/or write their own stringify for now.

**Comment by jachien** [comment]
Thanks for the suggestion, I opened https://github.com/aws/aws-xray-sdk-python/issues/416 with the xray repo.

**Comment by zzzeek** [comment]
this will not work

```
>>> from sqlalchemy import URL
>>> from sqlalchemy import make_url
>>> u1 = make_url("dbtype://user:pass+word+%2B+other%3Awords@host/dbname")
>>> u1.password
'pass+word+++other:words'
>>> u1 = make_url("dbtype://user:pass word+%2B+other%3Awords@host/dbname")
>>> u1.password
'pass word+++other:words'

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Replace custom URL-encoding method with quote** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5007

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**Replace custom URL-encoding method with quote** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5008
