### ISSUE TITLE
SQLAlchemy does not respect ancestor loggers' handlers

### ISSUE THREAD

**Issue by ssvine** [sqlalchemy/sqlalchemy#10689]
### Describe the bug

SQLAlchemy installs default logging handler when there are existing ancestor loggers' handlers. This causes the main program with its own logging setup to have unexpected logging activity.

In general, you should not need to attach a handler to more than one logger - if you just attach it to the appropriate logger which is highest in the logger hierarchy, then it will see all events logged by all descendant loggers, provided that their propagate setting is left set to True. A common scenario is to attach handlers only to the root logger, and to let propagation take care of the rest.

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

any

### Database Vendor and Major Version

any

### Python Version

any

### Operating system

any

### To Reproduce

```python
import logging
from sqlalchemy import create_engine, text

logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
formatter = logging.Formatter('MY HANDLER: %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

e = create_engine("sqlite://", echo=True, echo_pool="debug")
with e.connect() as conn:
    print(conn.scalar(text("select 'hi'")))
```

### Error

```
2023-11-23 20:44:25,954 DEBUG sqlalchemy.pool.impl.SingletonThreadPool Created new connection <sqlite3.Connection object at 0x0000023679348F40>
MY HANDLER: Created new connection <sqlite3.Connection object at 0x0000023679348F40>
2023-11-23 20:44:25,954 DEBUG sqlalchemy.pool.impl.SingletonThreadPool Connection <sqlite3.Connection object at 0x0000023679348F40> checked out from pool
MY HANDLER: Connection <sqlite3.Connection object at 0x0000023679348F40> checked out from pool
2023-11-23 20:44:25,954 INFO sqlalchemy.engine.Engine BEGIN (implicit)
MY HANDLER: BEGIN (implicit)
2023-11-23 20:44:25,954 INFO sqlalchemy.engine.Engine select 'hi'
MY HANDLER: select 'hi'
2023-11-23 20:44:25,954 INFO sqlalchemy.engine.Engine [generated in 0.00070s] ()
MY HANDLER: [generated in 0.00070s] ()
hi
2023-11-23 20:44:25,954 INFO sqlalchemy.engine.Engine ROLLBACK
MY HANDLER: ROLLBACK
2023-11-23 20:44:25,954 DEBUG sqlalchemy.pool.impl.SingletonThreadPool Connection <sqlite3.Connection object at 0x0000023679348F40> being returned to pool
MY HANDLER: Connection <sqlite3.Connection object at 0x0000023679348F40> being returned to pool
2023-11-23 20:44:25,954 DEBUG sqlalchemy.pool.impl.SingletonThreadPool Connection <sqlite3.Connection object at 0x0000023679348F40> reset, transaction already reset
MY HANDLER: Connection <sqlite3.Connection object at 0x0000023679348F40> reset, transaction already reset
``` 

### Additional context

The output of the reproduce step should be:

```
MY HANDLER: Created new connection <sqlite3.Connection object at 0x000001DDA8CB8D60>
MY HANDLER: Connection <sqlite3.Connection object at 0x000001DDA8CB8D60> checked out from pool
MY HANDLER: BEGIN (implicit)
MY HANDLER: select 'hi'
MY HANDLER: [generated in 0.00040s] ()
hi
MY HANDLER: ROLLBACK
MY HANDLER: Connection <sqlite3.Connection object at 0x000001DDA8CB8D60> being returned to pool
MY HANDLER: Connection <sqlite3.Connection object at 0x000001DDA8CB8D60> reset, transaction already reset
```

The bug is here: https://github.com/sqlalchemy/sqlalchemy/blob/44771ab0c32730d1ecefac21af13f113b1b19726/lib/sqlalchemy/log.py#L140C68-L140C68

Should use `self.logger.hasHandlers()` instead of `self.logger.handlers`.

**Comment by CaselIT** [comment]
Hi,

This is expected since you are using `echo=True`. See also https://github.com/sqlalchemy/sqlalchemy/discussions/10302#discussioncomment-6888150

**Comment by ssvine** [comment]
From the discussion: The idea is that echo is used when debugging or when an application is not using logging.

So, this statement, expressed in the code would look like:

```
if debug or not app.uses_logging():
    print(echo)
```

But in the repro case my app is *using* logging :-)

SQLAlchemy tests self.logger.handler to check whether app uses logging. But the right way to check is self.logger.hasHandlers()

Fixing to self.logger.hashHandlers() do not break any expected behaviour, it keeps the behaviour...

**Comment by CaselIT** [comment]
Many libraries and applications add a null handler by default, thus breaking the `hasHandler` feature.

In general sence you are using logging directly don't pass echo to the engine/pool.

**Comment by ssvine** [comment]
I think libraries uses sibling loggers that are not ancestors of the sqlalchemy logger, so no interference here

**Comment by ssvine** [comment]
Usual way to add root logger for a library: getLogger(__name__) or something like getLogger('my_fancy_lib')

**Comment by CaselIT** [comment]
In my experience it's not uncommon for libraries to add a null handler to the root logger.

It's not clear to me why not using echo is not an option, in favour of controlling loggers the usual way

**Comment by ssvine** [comment]
> In general sence you are using logging directly don't pass echo to the engine/pool.
This sounds like unnecessary restriction

**Comment by CaselIT** [comment]
I disagree.
There is an easy workaround if you keep wanting to use echo: add a null handler to the relevant sqlalchemy logger

**Comment by ssvine** [comment]
Yes, it helps

> In my experience it's not uncommon for libraries to add a null handler to the root logger.

That's a deal. Libraries use they own loggers.

```
import logging
logger = logging.getLogger('my_library')
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
formatter = logging.Formatter('MY HANDLER: %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

sql_logger = logging.getLogger('sqlalchemy')
sql_logger.hasHandlers()
```

I emulate third party library that sets up its own logger 'my_library' with its own handler.

At the same time `sql_logger.hasHandlers() == False`

There is no interference between libraries. So I do not understand why you worry about breaking `hasHandlers`

**Comment by CaselIT** [comment]
> That's a deal. Libraries use they own loggers.

As mentioned, that's not always true. I'm not saying they are right in doing so.

**Comment by ssvine** [comment]
Ok, I will setup null handler. Thanks for the discussion
