### ISSUE TITLE
Under the Windows system, when the pymssql version is higher than 2.2.7, the sqlalchemy query will be blocked and unresponsive, but there is no such problem under the Linux system. I'm not sure if this is a problem with pymssql or sqlalchemy.

### ISSUE THREAD

**Issue by zhaoziming** [sqlalchemy/sqlalchemy#10691]
### Describe the bug

Under the Windows system, when the pymssql version is higher than 2.2.7, the sqlalchemy query will be blocked and unresponsive, but there is no such problem under the Linux system. I'm not sure if this is a problem with pymssql or sqlalchemy.

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

mssql+pymssql

### Database Vendor and Major Version

SQLSERVER 13.0.2186.6

### Python Version

3.10 and 3.11

### Operating system

Windows

### To Reproduce

```python
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy import text

DB_URL = 'mssql+pymssql://user:passwd@10.32.66.182:1433/DataBase?charset=utf8'
engine = create_engine(DB_URL, echo=False)
connection = engine.connect()
result = connection.execute(text("select 1 as aaa")).fetchall()
print(result)
```

### Error

Connect blocks without reporting an error

**Comment by zzzeek** [comment]
hi -

you'd want to [use pymssql directly to debug the issue](https://pymssql.readthedocs.io/en/latest/) as this is something with your driver / database configuration, then report it to pymssql.

**Comment by zhaoziming** [comment]
Yes, you are right, this is a problem with pymssql, I was careless, sorry.

**Comment by zhaoziming** [comment]
@zzzeek Yes, you are right, this is a problem with pymssql, I was careless, sorry.
