### ISSUE TITLE
Rowcount isn't returned for INSERTs without RETURNING when using psycopg3

### ISSUE THREAD

**Issue by juusom** [sqlalchemy/sqlalchemy#10696]
### Describe the bug

The `CursorResult.rowcount` property returns `-1` instead of the actual cursor's rowcount value when using psycopg3 when performing an INSERT without a RETURNING clause. With psycopg2, it works as expected.

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

psycopg

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
import uuid

from sqlalchemy import UUID, Column, MetaData, Table, create_engine, insert

metadata = MetaData()

engine = create_engine('postgresql+psycopg://')

t1 = Table(
    "data",
    metadata,
    Column("id", UUID, primary_key=True),
)

with engine.begin() as conn:
    metadata.create_all(conn)
    stmt = insert(t1).values({'id': uuid.uuid4()})
    result = conn.execute(stmt)
    assert result.rowcount == 1
```

### Error

N/A

### Additional context

I dug into it a bit and it seems that with psycopg2, the `rowcount` property of a cursor remains unchanged after the cursor is closed, but with psycopg3, it turns to `-1` at that point. The memoized property `CursorResult.rowcount` isn't accessed before the cursor is closed [here](https://github.com/sqlalchemy/sqlalchemy/blob/44771ab0c32730d1ecefac21af13f113b1b19726/lib/sqlalchemy/engine/default.py#L1933), so the rowcount information is lost by the time the execute call returns.

I can't say if the psycopg behavior change is intentional or not, but it would seem to me that it would be prudent to grab the value before the cursor is closed in any case.

**Comment by zzzeek** [comment]
hi -

"rowcount" is only supported for UPDATE and DELETE statements.    for other kinds of statements, it varies per driver but we dont support these use cases; see the notes at https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.CursorResult.rowcount
