### ISSUE TITLE
add reflection for pg DOMAIN types similarly to ENUM reflection

### ISSUE THREAD

**Issue by ovangle** [sqlalchemy/sqlalchemy#10693]
### Describe the use case

Motivated by an issue which I initially filed as https://github.com/sqlalchemy/alembic/issues/1357, I did a little more digging into what was actually causing the issue today. It turns out that the column type information for `DOMAIN` columns is being replaced with a column of the domain's underlying type during reflection (see [`lib/sqlalchemy/dialects/postgresql/base.py:3760-3773`](https://github.com/sqlalchemy/sqlalchemy/blob/44771ab0c32730d1ecefac21af13f113b1b19726/lib/sqlalchemy/dialects/postgresql/base.py#L3760-L3774)). Note that the `coltype` isn't being set in that block, instead it replaces the `attype` and loops until it finds a suitable type to use instead of the domain.

Since it seems that the erasure is intentional (probably to work around deeper issues with wrapped types), I'm hesitant to pursue my investigation without seeking further guidance from someone more familiar with sqlalchemy internals.

### SQLAlchemy Version in Use

2.1.0b1

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 15.4

### Python Version

3.11

### Operating system

Ubuntu

### To Reproduce

```python
def test_domain_type_reflection(self, metadata, connection):
        positive_int = DOMAIN("positive_int", Integer(), check='value > 0', not_null=True)
        Table(
            "table",
            metadata,
            Column("value", positive_int)
        )

        metadata.create_all(connection)
        m2 = MetaData()
        t2 = Table("table", m2, autoload_with=connection)

        eq_(t2.c.value.type.name, 'positive_int')
        eq_(t2.c.value.check, 'value > 0')
```

### Error

```
./test/dialect/postgresql/test_types.py::NamedTypeTest::test_domain_type_reflection Failed: [undefined]AttributeError: 'INTEGER' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovangle/dev/sqlalchemy/.venv/lib/python3.11/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovangle/dev/sqlalchemy/test/dialect/postgresql/test_types.py", line 1109, in test_domain_type_reflection
    eq_(t2.c.value.type.name, 'positive_int')
        ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'INTEGER' object has no attribute 'name'
```

**Comment by zzzeek** [comment]
hi -

there's no way to reflect a DOMAIN type because these are custom declared in your own code and we do not have any publicly documented mechanism as yet to associate user-defined types with reflection targets.

I think this is an Alembic issue only for now and the PostgreSQL dialect on the Alembic side needs to be smart enough to ignore DOMAIN types when doing type comparison.   

On the SQLAlchemy side there can be a new Ideas discussion "how to support custom reflection" or something like that but this is not the ultimate problem you're having on the alembic side, you just want your false positives gone.

**Comment by CaselIT** [comment]
Apparently at some point a DomanType was added: https://github.com/sqlalchemy/sqlalchemy/blob/44771ab0c32730d1ecefac21af13f113b1b19726/lib/sqlalchemy/dialects/postgresql/named_types.py#L385

**Comment by zzzeek** [comment]
yes it was a big to-do that took months.  cc @singingwolfboy

**Comment by CaselIT** [comment]
maybe 2.1 could add reflection for them? Assuming it round trips ok?

**Comment by zzzeek** [comment]
reflection requires that the dialect have some kind of lookup table that links to the Python type objects.   so this implies someone's custom DOMAIN datatype would make use of some new, public API that associates a dialect with a type, which could be like:

```
    # something engine-local
    # note I dont like this API, but something that associates them like this
    engine.associate_datatype(MyDomain, "MY_DOMAIN")
```

or

```
   # this would be global.   This is probably what everyone would want to use 
   # though I hate globals....
   @reflects_as("MY_DOMAIN", "postgresql")
   class MyDomain(DOMAIN):
        ...
```

or anything else like the above.

Here's the point of that.   If we build that system, it has to apply **for any type, user defined or otherwise** and be a general system of affecting the reflected type registries of all dialects.

There's nothing technically difficult about this.  It's just an API that we have to *get right the first time*, which is why I've not been in any hurry to design this.

**Comment by zzzeek** [comment]
please disregard my comments regarding reflection

**Comment by ovangle** [comment]
@zzzeek
Reflecting the  `DOMAIN` back into the `DOMAIN` is pretty simple, the issue is that in order to behave correctly, the `DOMAIN` has to be reflected as its data type in order to process binds and results, correct?

What is required is that the `DOMAIN` essentially be a dynamic `TypeDecorator[T]` with `data_type: TypeEngine[T]`?

Would it be possible, at least initially, to add restrictions to what types could be used as the `data_type` of a DOMAIN, to insist that the underlying type is always recoverable via reflection? This essentially limits choices of data type to the simple types declared in `PGDialect.ischema_names`? Personally I don't mind if all my domain values are `str`s and `int`s, I'm just trying to push some validation into the db...

I understand that this is probably an egregious suggestion for a number of reasons, but would something like the following be in the ballpark of the right direction to be taking.

```python
_T = TypeVar('_T', bound=Any)

def is_reflectable(dialect, data_type: TypeEngine[Any]):
    """
    Determines whether the type is safe to be used as the basis of a DOMAIN. 
    """
    return data_type.__class__ in dialect.ischema_names.values()
    
class DOMAIN(NamedType, type_api.TypeDecorator[_T], sqltypes.SchemaType):
   impl = sqltypes.NULLTYPE
   
   def __init__(self, name: str, data_type: TypeEngineArgument[_T], data_type_args: Optional[tuple], data_type_kwargs: Optional[dict], **kwargs):
          self.name = name
          self.data_type = data_type

   def load_dialect_impl(self, dialect):
       if not is_reflectable(dialect, self.data_type):
            raise NotSupportedError('The underlying data type of a DOMAIN must be reflectable`)
       return self.data_type
````

**Comment by ovangle** [comment]
The above comment was written before I actually tried to roundtrip values to the database, but from all the tests I've written today, everything _seems_ to behave fine without any changes to the type itself.

**Comment by CaselIT** [comment]
Are you planning on opening a PR with the change in the linked commit?

**Comment by ovangle** [comment]
Depends on discussion here, really. I'd like the alembic issue fixed, and that should be fixed by the commit above (after adding a couple more fixes I've made to address failing tests). But unless I end up making a PR about it, it's just "a commit".

**Comment by ovangle** [comment]
I meant that I didn't have any plans to, I just wanted to share the commit with myself. But sure, I'll open one.

**Comment by CaselIT** [comment]
As you prefer

**Comment by sqla-tester** [comment]
**Thomas Stephenson** has proposed a fix for this issue in the **main** branch:

**Add pg DOMAIN type reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5030

**Comment by sqla-tester** [comment]
**Thomas Stephenson** has proposed a fix for this issue in the **rel_2_0** branch:

**Add pg DOMAIN type reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5239
