### ISSUE TITLE
Remove old signature for in session events

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10721]
The session events after_bulk_update and after_bulk_delete have legacy signatures that date back to the 0.9 release.

This will remove them

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Remove legacy signatures from session events** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4994
