### ISSUE TITLE
Support INET4 and INET6 in MariaDB

### ISSUE THREAD

**Issue by kkirsche** [sqlalchemy/sqlalchemy#10720]
### Describe the use case

This feature would add support for the MariaDB IPv4 and IPv6 addresses in SQLAlchemy. This would provide greater compatibility across dialects as now both Postgres and MariaDB would have native IP address types.

### Databases / Backends / Drivers targeted

* MariaDB versions >=[11.3.0](https://mariadb.com/kb/en/mariadb-11-3-0-release-notes/)
* Driver: `mysqlclient`

### Example Use

Equivalent to https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#sqlalchemy.dialects.postgresql.INET

### Additional context

* `INET4`: https://mariadb.com/kb/en/inet4/
* `INET6`: https://mariadb.com/kb/en/inet6/

**Comment by kkirsche** [comment]
Edited to include links to MariaDB documentation on the two data types.

**Comment by zzzeek** [comment]
sure, I'm assuming you want to do a PR

**Comment by CaselIT** [comment]
is this only on mariadb or mysql has equivalents?

**Comment by kkirsche** [comment]
> sure, I'm assuming you want to do a PR

Yep, I'll just be a bit slower in making the contribution and addressing feedback as my wife is pregnant and I'm balancing additional responsibilities.

**Comment by kkirsche** [comment]
> is this only on mariadb or mysql has equivalents?

From an initial search it was MariaDB only. I'll continue to look for MySQL though as ideally I'd love for this to be a generic type across backends if at all possible (it very well may not be though). As I recall, MySQL and MariaDB share the same dialect today, which would complicate things somewhat if they diverge too much.

**Comment by CaselIT** [comment]
> As I recall, MySQL and MariaDB share the same dialect today, which would complicate things somewhat if they diverge too much.

Almost, they are somewhat separated, but some work should be done to properly support them.
It may be that this is an occasion to work on it.

> Yep, I'll just be a bit slower in making the contribution and addressing feedback as my wife is pregnant and I'm balancing additional responsibilities.

Sure, no problem, take your time

**Comment by sqla-tester** [comment]
**Adam Žurek** has proposed a fix for this issue in the **main** branch:

**Added INET4 and INET6 types for MariaDB** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5598
