### ISSUE TITLE
`DeclarativeBase` doesn't forward keyword arguments in `__init_subclass__`

### ISSUE THREAD

**Issue by michaeloliverx** [sqlalchemy/sqlalchemy#10732]
### Describe the bug

`DeclarativeBase.__init_subclass__` doesn't forward unknown keyword arguments meaning `Base` **MUST** come last when using a Mixin that uses `__init_subclass__` with keyword arguments.

The docs don't reflect this:

> There’s no fixed convention for the order of mixins and base classes. Normal Python method resolution rules apply, and the above example would work just as well with:
> 
> ```python
> class MyModel(Base, HasLogRecord, CommonMixin):
>     name: Mapped[str] = mapped_column()
> ```

This should be a simple fix for `DeclarativeBase` but opens a wider discussion to do this for other or all classes that use `__init_subclass__` e.g. `MappedAsDataclass`?

Happy to open a PR for this, draft without tests here https://github.com/sqlalchemy/sqlalchemy/pull/10733.
If accepted where should a test for this live?

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/declarative_mixins.html#composing-mapped-hierarchies-with-mixins

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 15

### Python Version

3.11

### Operating system

OSX

### To Reproduce

```python
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class Mixin:
    def __init_subclass__(cls, arg1: str, **kwargs: object) -> None:
        super().__init_subclass__(**kwargs)


# Works because `Base` is last
class TableOne(Mixin, Base, arg1=""):
    __tablename__ = "table_one"
    pk: Mapped[int] = mapped_column(primary_key=True)


# Doesn't work because `Base` is first and doesn't forward **kwargs
class TableTwo(Base, Mixin, arg1=""):
    __tablename__ = "table_two"
    pk: Mapped[int] = mapped_column(primary_key=True)

```

### Error

```
Traceback (most recent call last):
  File "example.py", line 18, in <module>
    class TableTwo(Base, Mixin, arg1=""):
TypeError: __init_subclass__() got an unexpected keyword argument 'arg1'
```

**Comment by zzzeek** [comment]
what's concerning here is we already had this bug and it was fixed for DeclarativeMeta in 664cefb27 #5357.  Why didnt our test support also expand to include this?

can you please in your PR include additional tests that follow after https://github.com/sqlalchemy/sqlalchemy/blob/d8cab0694e6dc9f7b7fd02a4b5a8ae6bbb2e896e/test/orm/declarative/test_basic.py#L900 , thanks

**Comment by CaselIT** [comment]
> This should be a simple fix for `DeclarativeBase` but opens a wider discussion to do this for other or all classes that use `__init_subclass__` e.g. `MappedAsDataclass`?

For sure `DeclarativeBaseNoMeta` should behave in the same manner. Probably also `MappedAsDataclass`

**Comment by sqla-tester** [comment]
**Michael Oliver** has proposed a fix for this issue in the **main** branch:

**Forward `**kwargs` in `__init_subclass__` to super** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4998
