### ISSUE TITLE
tox w/o greenlet install is broken for main as well as 2.0

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10747]
no test coverage for this, adding

see also #6136

**Comment by zzzeek** [comment]
specifically in 2.0 it breaks if you include an asyncio dbdriver, using:

    tox  -e py312-cext-sqlite-nogreenlet

**Comment by CaselIT** [comment]
> specifically in 2.0 it breaks if you include an asyncio dbdriver, using:

I think it's fine to have it break if it's missing and the test is leveraging an async driver.

Btw the fact that the test raise an error without greenlet was fixed here https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5023

It's just the tox case that's missing

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure test suite runs w/o greenlet** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5010

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**ensure test suite runs w/o greenlet** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5011

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**restore ValueError when greenlet not installed** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5012

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**restore ValueError when greenlet not installed** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5013
