### ISSUE TITLE
`aliased` does not have the desired effect when `extend_existing=True` is used.  This problem can cause serious bugs when writing complex sql statements.

### ISSUE THREAD

**Issue by amisadmin** [sqlalchemy/sqlalchemy#10767]
### Describe the bug

`aliased` does not have the desired effect when `extend_existing=True` is used.  This problem can cause serious bugs when writing complex sql statements.
```py
def test_sqlalchemy_aliased():
    from sqlalchemy import Column, select, Integer, String
    from sqlalchemy.orm import declarative_base, aliased

    Base = declarative_base()

    class User(Base):
        __tablename__ = "user"
        id = Column(Integer, primary_key=True)

    class User2(Base):
        __tablename__ = "user"
        __table_args__ = {"extend_existing": True}
        id = Column(Integer, primary_key=True)
        name = Column(String)


    print(select(aliased(User, name="NewUser").id))
    # SELECT "user".id FROM "user"
    # Why not?
    # SELECT "NewUser".id FROM "user" AS "NewUser"
    print(select(aliased(User2, name="NewUser2").id))
    # SELECT "NewUser2".id FROM "user" AS "NewUser2"
```

This is the simplest example,

- I tried more complex sql queries,  and none of the User models worked with aliased.

- If there are more extended models, none of the previous models will take effect, and only the last one can be aliased.

- In practice, there may be so many extended models that it is difficult to determine which model class the program will load last.

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

psycopg2, pyodbc, pysqlite, mysqlclient, asyncpg

### Database Vendor and Major Version

SQLite, PostgreSQL 12, MySQL 8

### Python Version

3.11

### Operating system

Windows

### To Reproduce

```python
def test_sqlalchemy_aliased():
    from sqlalchemy import Column, select, Integer, String
    from sqlalchemy.orm import declarative_base, aliased

    Base = declarative_base()

    class User(Base):
        __tablename__ = "user"
        id = Column(Integer, primary_key=True)

    class User2(Base):
        __tablename__ = "user"
        __table_args__ = {"extend_existing": True}
        id = Column(Integer, primary_key=True)
        name = Column(String)


    print(select(aliased(User, name="NewUser").id))
    # SELECT "user".id FROM "user"
    # Why not?
    # SELECT "NewUser".id FROM "user" AS "NewUser"
    print(select(aliased(User2, name="NewUser2").id))
    # SELECT "NewUser2".id FROM "user" AS "NewUser2"
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
```

**Comment by amisadmin** [comment]
This mistake is very subtle.

Since User, User2,User3, etc. are distributed in different files, I can't determine which one can use 'aliased'

The program executes without throwing exceptions, but the resulting sql statement does not execute as expected.

**Comment by zzzeek** [comment]
this is not an appropriate use of extend_existing:

```py
    class User(Base):
        __tablename__ = "user"
        id = Column(Integer, primary_key=True)

    class User2(Base):
        __tablename__ = "user"
        __table_args__ = {"extend_existing": True}
        id = Column(Integer, primary_key=True)
        name = Column(String)
```

that is creating an ORM mapping of the "user" table to User, which works fine, but in the next step, you are retroactively altering the underlying `Table` construct for which `User` is mapped, without any attempt to notify the ORM mapping of `User` that things have changed.   Retroactive modification of ORM mappings to replace same-named columns with new ones ("id" in this case) is not supported.

extend_existing is only intended to be used at the Core level when reflecting tables and augmenting those reflected tables with new columns (or vice versa).   Nothing ORM should be happening to Table objects that are still being edited.
