### ISSUE TITLE
get_check_constraints() fails to parse constraints marked NO INHERIT

### ISSUE THREAD

**Issue by ellisvalentiner** [sqlalchemy/sqlalchemy#10777]
### Describe the bug

`get_check_constraints()` fails to parse constraints marked `NO INHERIT`.

If the constraint returned by `pg_get_constraintdef()` is marked `NO INHERIT`, `get_check_constraints` in `dialects/postgresql/base.py` prints a warning and fails to parse the constraint.

The regex in get_check_constraints does not handle `NO INHERIT`: `re.match(r"^CHECK *\((.+)\)( NOT VALID)?$", src)`

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 15

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
import sqlalchemy
from sqlalchemy import MetaData, Table, text

engine = sqlalchemy.create_engine("postgresql://postgres@localhost/postgres", echo=False)
with engine.connect() as conn:
    conn.execute(text("""CREATE TABLE IF NOT EXISTS tbl
(
  id int NOT NULL DEFAULT 0,
  a  INT,
  CHECK
    (
    a IS NOT NULL
    ) NO INHERIT
);"""))
tbl = Table('tbl', MetaData(), autoload_with=engine)
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
/app/repro.py:15: SAWarning: Could not parse CHECK constraint text: 'CHECK (a IS NOT NULL) NO INHERIT'
  tbl = Table('tbl', MetaData(), autoload_with=engine)
```

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting and for the PR

**Comment by sqla-tester** [comment]
**Ellis Valentiner** has proposed a fix for this issue in the **main** branch:

**Support reflecting no inherit check constraint in pg.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5083

**Comment by sqla-tester** [comment]
**Ellis Valentiner** has proposed a fix for this issue in the **rel_2_0** branch:

**Support reflecting no inherit check constraint in pg.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5106
