### ISSUE TITLE
Unable to update MutableList string member at specific index

### ISSUE THREAD

**Issue by glouvigny** [sqlalchemy/sqlalchemy#10784]
### Describe the bug

When upgrading to SQLAlchemy 2.0 from 1.4.50, I face an issue where strings members of a `sqlalchemy.ext.mutable.MutableList` cannot be updated.

This is likely due to strings being recognized as instances of Iterable and not scalar types:

https://github.com/sqlalchemy/sqlalchemy/blob/b12b7b120559d07a6f24fb2d6d29c7049084b4a5/lib/sqlalchemy/ext/mutable.py#L911-L912

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 15

### Python Version

3.11.2

### Operating system

OSX

### To Reproduce

```python
import sqlalchemy
import sqlalchemy.orm
from sqlalchemy.ext.mutable import Mutable, MutableList


Base = sqlalchemy.orm.declarative_base()


class Entity(Base):
    __tablename__ = 'entity'

    id = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True)
    names = sqlalchemy.Column(MutableList.as_mutable(sqlalchemy.JSON), default=MutableList)
    ages = sqlalchemy.Column(MutableList.as_mutable(sqlalchemy.JSON), default=MutableList)


instance = Entity()

assert instance.ages is None

instance.ages = [12, 23]
assert instance.ages == [12, 23]

instance.ages[0] = 34
assert instance.ages == [34, 23]


assert instance.names is None

instance.names = ["alice", "bob"]
assert instance.names == ["alice", "bob"]

instance.names[0] = "charlie"
assert instance.names == ["charlie", "bob"]
```

### Error

```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    assert instance.names == ["charlie", "bob"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use a standard function to check for iterable collections** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5042

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**use a standard function to check for iterable collections** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5043

**Comment by zzzeek** [comment]
thanks for reporting
