### ISSUE TITLE
`RuntimeError: Set changed size during iteration` raised in clsregistry _MultipleClassMarker.add_item

### ISSUE THREAD

**Issue by yilei** [sqlalchemy/sqlalchemy#10782]
### Describe the bug

We have several tests that use flask and sqlalchemy, they create & destroy the database multiple times for each test case in a single test invocation. They use automap_base to generate mapped classes.

We saw the tests can fail with a `RuntimeError: Set changed size during iteration` raised here:
https://github.com/sqlalchemy/sqlalchemy/blob/6e089c3dbf7e7348da84dfc62cc1c6100a257fd4/lib/sqlalchemy/orm/clsregistry.py#L245

Upon investigation, when running the list comprehension `[ref() for ref in self.contents]`, the `self.contents` set itself could be modified during a GC cycle when `_remove_item` is called.

I believe this is a similar issue as https://github.com/sqlalchemy/sqlalchemy/issues/3208 linked in a comment from `add_item`, and the fix is to protect this by making a copy:

```python
        # protect against class registration race condition against
        # asynchronous garbage collection calling _remove_item,
        # [ticket:3208]
        modules = {
            cls.__module__
            for cls in [ref() for ref in self.contents.copy()]
            if cls is not None
        }
```

### SQLAlchemy Version in Use

1.4.35

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

MySQL 5.6

### Python Version

3.11

### Operating system

Linux

### To Reproduce

Unfortunately, the tests we have are fairly large, and I have only been successfully reproduce it in the tests, not a stripped down version.

I hope this is understandable since the bug is triggered by a Python GC cycle, and I also hope the fix should be clear.

### Error

```
  File "sqlalchemy/ext/automap.py", line 891, in prepare
    mapped_cls = type(
                 ^^^^^
  File "sqlalchemy/orm/decl_api.py", line 72, in __init__
    _as_declarative(reg, cls, dict_)
  File "sqlalchemy/orm/decl_base.py", line 126, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sqlalchemy/orm/decl_base.py", line 177, in setup_mapping
    return cfg_cls(registry, cls_, dict_, table, mapper_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sqlalchemy/orm/decl_base.py", line 314, in __init__
    clsregistry.add_class(
  File "sqlalchemy/orm/clsregistry.py", line 69, in add_class
    module.add_class(classname, cls)
  File "sqlalchemy/orm/clsregistry.py", line 231, in add_class
    existing.add_item(cls)
  File "sqlalchemy/orm/clsregistry.py", line 171, in <listcomp>
  for cls in [ref() for ref in self.contents]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Set changed size during iteration
```

### Additional context

I'm also reading the code in sqlalchemy 2.0, it has a new `bookkeeping` mechanism in automap prepare while the 1.x versions don't:

https://github.com/sqlalchemy/sqlalchemy/blob/6e089c3dbf7e7348da84dfc62cc1c6100a257fd4/lib/sqlalchemy/ext/automap.py#L1243-L1245

This _might_ also make this bug no longer reproducible, since in our tests they are using a shared `AutomapBase` for different test cases, and the new bookkeeping appears to make it no longer re-creating the classes when we call prepare with new instances of the databases.

**Comment by CaselIT** [comment]
Hi,

The fix to use copy should be fine to have also on v2, even if not strictly necessary.
Care to send a PR?

**Comment by sqla-tester** [comment]
**Yilei Yang** has proposed a fix for this issue in the **main** branch:

**Use a copy of `self.contents` in this list comprehension.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5031

**Comment by sqla-tester** [comment]
**Yilei Yang** has proposed a fix for this issue in the **main** branch:

**Use a copy of `self.contents` in this list comprehension.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5031

**Comment by sqla-tester** [comment]
**Yilei Yang** has proposed a fix for this issue in the **rel_2_0** branch:

**Use a copy of `self.contents` in this list comprehension.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5034

**Comment by sqla-tester** [comment]
**Yilei Yang** has proposed a fix for this issue in the **rel_1_4** branch:

**Use a copy of `self.contents` in this list comprehension.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5035
