### ISSUE TITLE
Incorect filled in return type for select with func elements

### ISSUE THREAD

**Issue by enadeau** [sqlalchemy/sqlalchemy#10801]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

A select construct with a min function gets a `Never` when annotated with the correct types.

I have a statement that use a min function on a datetime mapped column. When not annotated mypy complains about the variable needed a type annotation.

When the correct type annotation is added mypy complains that the type is not compatible with the assignment and says the datetime component of the statement is of type `Never`

### To Reproduce

```python
from datetime import datetime

import sqlalchemy as sa


class Base(sa.orm.DeclarativeBase):
    pass


class Foo(Base):
    __tablename__ = "foo"

    id: sa.orm.Mapped[int] = sa.orm.mapped_column(primary_key=True)
    group_id: sa.orm.Mapped[int]
    created_at: sa.orm.Mapped[datetime]


stmt = (
    sa.select(
        Foo.group_id,
        sa.func.min(Foo.created_at),
    )
    .group_by(Foo.group_id)
)
reveal_type(stmt)

stmt_annotated: sa.Select[tuple[int, datetime]] = (
    sa.select(
        Foo.group_id,
        sa.func.min(Foo.created_at),
    )
    .group_by(Foo.group_id)
)
reveal_type(stmt_annotated)
```

### Error

```
$ mypy foo.py 
foo.py:19: error: Need type annotation for "stmt"  [var-annotated]
foo.py:25: note: Revealed type is "sqlalchemy.sql.selectable.Select[tuple[builtins.int, Any]]"
foo.py:28: error: Incompatible types in assignment (expression has type "Select[tuple[int, Never]]", variable has type "Select[tuple[int, datetime]]")  [assignment]
foo.py:34: note: Revealed type is "sqlalchemy.sql.selectable.Select[tuple[builtins.int, datetime.datetime]]"
Found 2 errors in 1 file (checked 1 source file)
``` 

### Versions

- OS: Ubuntu 23.10
- Python: 3.12.0
- SQLAlchemy: 2.0.24
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.8.0

### Additional context

This bug was not present in 2.0.23 as the functions module was not yet typed

**Comment by CaselIT** [comment]
Hi,

This seems more a bug in mypy than anything else. Pyright works correctly here.
The typing in question is this one https://github.com/sqlalchemy/sqlalchemy/blob/b44018d46b0b306bae04e0b0ea2e11ca78ef64e9/lib/sqlalchemy/sql/functions.py#L1112-L1139

there is even a note trying to make it liked by mypy, but I guess it's failing do be liked by mypy.


Not sure if there is a way of making it work.

**Comment by xmatthias** [comment]
Encountering the same with the latest update.
is there a corresponding bug in the mypy repo for this, if we assume this is a bug in mypy? 

> Not sure if there is a way of making it work.

If it's not working with half of the popular type checkers (assuming mypy and pyright to be the 2 most popular ones) - then i think this should be postponed until the mypy bug is fixed, or until an alternative solution is found.

In it's current form (it's not working if using mypy) - it's confusing more than anything ... so while type hinting aims to help python development, it currently only makes us (users) apply some odd workarounds (currently probably the only option is to add  `# type: ignore` all over the place).

**Comment by zzzeek** [comment]
there are two things going on here:

1. pyright, at least over here, does not seem to like "sa.orm" thing.   I dont see how that can be fixed on our end.   Doing this, pyright is now fine:

```py
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy import func
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

class Base(DeclarativeBase):
    pass


class Foo(Base):
    __tablename__ = "foo"

    id: Mapped[int] = mapped_column(primary_key=True)
    group_id: Mapped[int]
    created_at: Mapped[datetime]

stmt = (
    sa.select(
        Foo.group_id,
        func.min(Foo.created_at),
    )
    .group_by(Foo.group_id)
)

reveal_type(stmt)


```


2. mypy has trouble with unions where some elements are non generic.    The immediate issue here resolves if I remove this non-generic element from the `_ColumnExpressionArgument` union:

```diff
diff --git a/lib/sqlalchemy/sql/_typing.py b/lib/sqlalchemy/sql/_typing.py
index 944b29176..14a5a0ce6 100644
--- a/lib/sqlalchemy/sql/_typing.py
+++ b/lib/sqlalchemy/sql/_typing.py
@@ -172,7 +172,7 @@ _T9 = TypeVar("_T9", bound=Any)
 
 _ColumnExpressionArgument = Union[
     "ColumnElement[_T]",
-    _HasClauseElement,
+    #_HasClauseElement,
     "SQLCoreOperations[_T]",
     roles.ExpressionElementRole[_T],
     Callable[[], "ColumnElement[_T]"],

```

then mypy passes with both the original case as well as my altered version.

```
test3.py:25: note: Revealed type is "sqlalchemy.sql.selectable.Select[tuple[builtins.int, datetime.datetime]]"
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add a generic argument to _HasClauseElement** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5050

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**add a generic argument to _HasClauseElement** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5051

**Comment by enadeau** [comment]
Thanks for the fix and quick reply. Looking forward to getting that in the next release
