### ISSUE TITLE
uselist not inferred correctly for relationship when a non-string type annotation is used in Mapped

### ISSUE THREAD

**Issue by DavideCanton** [sqlalchemy/sqlalchemy#10815]
### Describe the bug

It seems that the [one-to-one](https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#one-to-one) example for a relationship does not infer correctly the `uselist` value if the mapped argument is not a string annotation.

The difference is in the value inferred for uselist in the `Parent.child` relationship, that is correctly inferred to `False` in the example, while it is inferred to `True` if the type annotation for `child` is changed to `Mapped[Child]`.

In the docs of the uselist parameter (https://docs.sqlalchemy.org/en/20/orm/relationship_api.html#sqlalchemy.orm.relationship.params.uselist) it is stated that uselist may be derived from whether the mapped argument is a collection or not, but in this case `Mapped[Child]` is not a collection, so I would expect uselist set to `False`.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/relationship_api.html#sqlalchemy.orm.relationship.params.uselist

### SQLAlchemy Version in Use

2.0.24

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 13

### Python Version

3.10

### Operating system

Windows

### To Reproduce

```python
from sqlalchemy import ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship, DeclarativeBase


class Base(DeclarativeBase):
    pass


class Child(Base):
    __tablename__ = "child"

    id: Mapped[int] = mapped_column(primary_key=True)
    parent_id: Mapped[int] = mapped_column(ForeignKey("parent.id"))
    parent: Mapped["Parent"] = relationship(back_populates="child")


class Parent(Base):
    __tablename__ = "parent"

    id: Mapped[int] = mapped_column(primary_key=True)
    # this relationship has uselist=True
    child: Mapped[Child] = relationship(back_populates="parent")
    # this relationship has uselist=False
    # child: Mapped["Child"] = relationship(back_populates="parent")
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
```

**Comment by DavideCanton** [comment]
Just to add some further information, adding `from __future__ import annotations` makes it work correctly with `Mapped[Child]`.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**TODO / WIP: fix lh relationship annotation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5059

**Comment by zzzeek** [comment]
thanks for reporting

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**force uselist=False for all collection class not present** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5060
