### ISSUE TITLE
No overload variant of "coalesce" of "_FunctionGenerator" matches argument types

### ISSUE THREAD

**Issue by erdnaxeli** [sqlalchemy/sqlalchemy#10818]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

Using `func.coalesce` produce typing errors.

### To Reproduce

```python
from typing import Optional

from sqlalchemy import String, create_engine, func, select
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "user_account"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(30))
    fullname: Mapped[Optional[str]]


engine = create_engine("sqlite://", echo=True)
Base.metadata.create_all(engine)

with Session(engine) as session:
    result = session.execute(select(func.coalesce(User.name, "default name")))
```

### Error

```
t.py:23: error: No overload variant of "coalesce" of "_FunctionGenerator" matches argument types "InstrumentedAttribute[str]", "str"  [call-overload]
t.py:23: note: Possible overload variants:
t.py:23: note:     def [_T] coalesce(self, col: ColumnElement[_T], *args: ColumnElement[Any] | _HasClauseElement | SQLCoreOperations[Any] | ExpressionElementRole[Any] | Callable[[], ColumnElement[Any]] | LambdaElement, **kwargs: Any) -> coalesce[_T]
t.py:23: note:     def [_T] coalesce(self, col: ColumnElement[_T] | _HasClauseElement | SQLCoreOperations[_T] | ExpressionElementRole[_T] | Callable[[], ColumnElement[_T]] | LambdaElement, *args: ColumnElement[Any] | _HasClauseElement | SQLCoreOperations[Any] | ExpressionElementRole[Any] | Callable[[], ColumnElement[Any]] | LambdaElement, **kwargs: Any) -> coalesce[_T]
Found 1 error in 1 file (checked 1 source file)
``` 

### Versions

- OS: linux 6.5.12
- Python: 3.12.1
- SQLAlchemy: 2.0.24
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.8.0

### Additional context

I can use `func.coalesce(User.name, text("'default name'"))`, but this returns a new error:
```
t.py:23: error: Need type annotation for "result"  [var-annotated]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**allow literals for function arguments** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5062

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**allow literals for function arguments** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5063

**Comment by zzzeek** [comment]
this is a general class of regression based on that we added typing to sqlalchemy.sql.functions in 2.0.24
