### ISSUE TITLE
Add support for "server-side" cursors in oracledb

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#10820]
All oracle cursors are "server-side" but sqlalchemy never uses them as such, so some async functionalities are currently disabled, like `stream` that relies on server-side cursors.

It should be possible to enable them in sqlalchemy

_Originally posted by @CaselIT in https://github.com/sqlalchemy/sqlalchemy/issues/10679#issuecomment-1868281521_

**Comment by CaselIT** [comment]
let's try to target 2.0

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Added support for server-side cursor in oracledb.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5441

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Added support for server-side cursor in oracledb.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5442

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Added support for server-side cursor in oracledb async dialect.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5441
