### ISSUE TITLE
CASE expressions involving NULL values have incorrect types

### ISSUE THREAD

**Issue by evansd** [sqlalchemy/sqlalchemy#10843]
### Describe the bug

CASE expressions take as their type the type of their final WHEN clause:
https://github.com/sqlalchemy/sqlalchemy/blob/4871a2f72f5f0e514fe81a8caa17a14f9fc51300/lib/sqlalchemy/sql/elements.py#L3426-L3429

But where a CASE expression includes explicit NULL values, this behaviour is not always correct.

Below is a draft PR fixing the issue which I could submit if this issue is accepted:
https://github.com/sqlalchemy/sqlalchemy/pull/10847

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.11.7

### Operating system

Linux

### To Reproduce

```python
import datetime

import sqlalchemy


current_date = sqlalchemy.func.date()
date_literal_1 = sqlalchemy.literal(datetime.date(2000, 1, 1))
date_literal_2 = sqlalchemy.literal(datetime.date(2100, 1, 1))

# CASE expression involving an explicit NULL value
case_1 = sqlalchemy.case(
    (current_date < date_literal_1, None),
    (current_date > date_literal_2, date_literal_2),
    else_=current_date,
)

# Same expression with order of WHEN clauses reversed
case_2 = sqlalchemy.case(
    (current_date > date_literal_2, date_literal_2),
    (current_date < date_literal_1, None),
    else_=current_date,
)

# We use SQLite to demonstrate the bug as its lack of a native date type makes the
# incorrect type assignment more obvious, though the bug itself has nothing to do with
# SQLite
engine = sqlalchemy.create_engine("sqlite:///")
with engine.connect() as conn:
    result_1 = conn.execute(sqlalchemy.select(case_1)).fetchone()[0]
    result_2 = conn.execute(sqlalchemy.select(case_2)).fetchone()[0]

assert result_1 == result_2, f"{result_1!r} != {result_2!r}"
```

### Error

```
Traceback (most recent call last):
  File "sqla_repro.py", line 32, in <module>
    assert result_1 == result_2, f"{result_1!r} != {result_2!r}"
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: datetime.date(2024, 1, 8) != '2024-01-08'
```

**Comment by zzzeek** [comment]
that's fine, I would have thought case() had a `type_` parameter also but apparently not.    if you can write a changelog message that is in the area of "enhanced case() to derive the ultimate type by scanning the given expressions for the first non-NULL expression, rather than hardcoding to the last WHEN case", that would be helpful.

**Comment by sqla-tester** [comment]
**David Evans** has proposed a fix for this issue in the **main** branch:

**Fix type of CASE expressions which include NULLs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5084

**Comment by sqla-tester** [comment]
**David Evans** has proposed a fix for this issue in the **rel_2_0** branch:

**Fix type of CASE expressions which include NULLs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5066
