### ISSUE TITLE
URL parsing changed between 2.0.23 and 2.0.24

### ISSUE THREAD

**Issue by RichieCahill** [sqlalchemy/sqlalchemy#10852]
### Describe the bug

When upgrading from 2.0.23 to 2.0.24+ the behavior of create_engine changed.
The method no longer accepts URL encoded passwords and spread to URL encode them a second time

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/engines.html#escaping-special-characters-such-as-signs-in-passwords

### SQLAlchemy Version in Use

2.0.24+

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.9-3.11

### Operating system

linux RHEL 8

### To Reproduce

```python
Run this code on sqlalchemy 2.0.23 and 2.0.24 

import configparser
import urllib

from sqlalchemy import URL


def main() -> None:
    """Main"""
    drivername = "postgresql+psycopg2"
    username = "inigo"
    password = "secret@%$#^&*()"
    host = "server.example.com"
    port = 5432
    database = "name"

    engine_url = URL.create(
        drivername=drivername,
        username=username,
        password=password,
        host=host,
        port=port,
        database=database,
    )

    quoted_engine_url = URL.create(
        drivername=drivername,
        username=username,
        password=urllib.parse.quote(password),
        host=host,
        port=port,
        database=database,
    )

    singal_string_engine_url = quoted_engine_url.render_as_string(hide_password=False)

    double_string_engine_url = singal_string_engine_url.replace("%", "%%")

    config_file = configparser.ConfigParser()
    config_file.add_section("alembic")
    config_file.set("alembic", "sqlalchemy.url", double_string_engine_url)
    config_url = config_file.get("alembic", "sqlalchemy.url")

    print(f"engine_url                  = {engine_url.render_as_string(hide_password=False)}")
    print(f"quoted_engine_url           = {quoted_engine_url.render_as_string(hide_password=False)}")
    print(f"singal_string_engine_url    = {singal_string_engine_url}")
    print(f"double_string_engine_url    = {double_string_engine_url}")
    print(f"config_url                  = {config_url}")


if __name__ == "__main__":
    main()
```

### Error

sqlalchemy 2.0.23
![image](https://github.com/sqlalchemy/sqlalchemy/assets/64815956/125e76d6-7bb4-4fee-8f80-ef94da95fe19)

 sqlalchemy 2.0.24
![image](https://github.com/sqlalchemy/sqlalchemy/assets/64815956/efc05710-da12-4cd7-b8b1-f1ec47fc7fc0)

### Additional context

we believe this will affect all BD and python versions

we believe this change created this bug
<https://docs.sqlalchemy.org/en/20/changelog/changelog_20.html#change-2.0.24-engine>

More info
<https://github.com/sqlalchemy/sqlalchemy/issues/10662>
<https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4996>
<https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5007>
<https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5008>

**Comment by zzzeek** [comment]
hey there -

parsing has not been changed at all.

The program below demonstrates the three URLs that are being tested here - the "engine URL", then the "quoted url" rendered in SQLAlchemy 2.0.23, and the "quoted url" rendered in SQLAlchemy 2.0.24.   The parsing is identical on both platforms as well as any 1.4 version:

```py
from sqlalchemy.engine import url
import urllib


u1 = url.make_url("postgresql+psycopg2://inigo:secret%40%$#^&*()@server.example.com:5432/name")
u2 = url.make_url("postgresql+psycopg2://inigo:secret%40%25%24%23%5E%26%2A%28%29@server.example.com:5432/name")
u3 = url.make_url("postgresql+psycopg2://inigo:secret%2540%2525%2524%2523%255E%2526%252A%2528%2529@server.example.com:5432/name")

assert u1 == url.URL.create(
    drivername = "postgresql+psycopg2",
    username = "inigo",
    password = "secret@%$#^&*()",
    host = "server.example.com",
    port = 5432,
    database = "name",
)

assert u2 == url.URL.create(
    drivername = "postgresql+psycopg2",
    username = "inigo",
    password = "secret@%$#^&*()",
    host = "server.example.com",
    port = 5432,
    database = "name",
)

assert u3 == url.URL.create(
    drivername = "postgresql+psycopg2",
    username = "inigo",
    password = urllib.parse.quote("secret@%$#^&*()"),
    host = "server.example.com",
    port = 5432,
    database = "name",
)
```


what **has** changed is render_as_string.   this code that you have:

```py
    quoted_engine_url = URL.create(
        drivername=drivername,
        username=username,
        password=urllib.parse.quote(password),
        host=host,
        port=port,
        database=database,
    )

```

that's incorrect.  you would not want to URL quote the password when constructing the URL object.  That *changes* the password to something else.  The bug that was fixed in #10662 fixes the url **string generation** to be correct.

Here's a simple test with both versions of your URL.  In 2.0.24, round trip passes.  prior to 2.0.24, this fails on the second URL.  it should be clear this was a bug to be fixed.

```py
from sqlalchemy.engine import url
import urllib


u1 = url.URL.create(
    drivername = "postgresql+psycopg2",
    username = "inigo",
    password = "secret@%$#^&*()",
    host = "server.example.com",
    port = 5432,
    database = "name",
)

u2 = url.URL.create(
    drivername = "postgresql+psycopg2",
    username = "inigo",
    password = urllib.parse.quote("secret@%$#^&*()"),
    host = "server.example.com",
    port = 5432,
    database = "name",
)


assert url.make_url(u1.render_as_string(hide_password=False)) == u1
assert url.make_url(u2.render_as_string(hide_password=False)) == u2
```

**Comment by zzzeek** [comment]
added a note in d9ed5cb521d5e7a2b6264

**Comment by RichieCahill** [comment]
Thank you for the help and the explanation.
