### ISSUE TITLE
[MySQL] Nullability of generated columns is not inspected correctly

### ISSUE THREAD

**Issue by GeorchW** [sqlalchemy/sqlalchemy#10850]
### Describe the bug

The inspector does not pick up the nullability of generated columns for MySQL.

### SQLAlchemy Version in Use

2.0.22

### DBAPI (i.e. the database driver)

MySQL

### Database Vendor and Major Version

MySQL 8

### Python Version

Python 3.11

### Operating system

Linux

### To Reproduce

```python
import os
from sqlalchemy import sql, create_engine, inspect

# Create a table with a generated column in MySQL

engine = create_engine(os.environ["DB_URL"])
conn = engine.connect()


ddl = """CREATE TABLE IF NOT EXISTS mytable (
    my_generated_column int GENERATED ALWAYS AS (1234) VIRTUAL NOT NULL
);"""
conn.execute(sql.text(ddl))

# Try inspecting the generated column
inspector = inspect(conn)
cols = inspector.get_columns("mytable")
cols = [col for col in cols if col["name"] == "my_generated_column"]
assert cols[0]["nullable"] == False
```

### Error

```
Traceback (most recent call last):
  File "reproduction.py", line 19, in <module>
    assert cols[0]["nullable"] == False
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by zzzeek** [comment]
thanks for reporting, feel free to provide a PR if you have resources

**Comment by sqla-tester** [comment]
**Georg Wicke-Arndt** has proposed a fix for this issue in the **main** branch:

**Parse NOT NULL for MySQL generated columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5102

**Comment by sqla-tester** [comment]
**Georg Wicke-Arndt** has proposed a fix for this issue in the **rel_2_0** branch:

**Parse NOT NULL for MySQL generated columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5121

**Comment by sqla-tester** [comment]
**Georg Wicke-Arndt** has proposed a fix for this issue in the **main** branch:

**Parse NOT NULL for MySQL generated columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5102

**Comment by sqla-tester** [comment]
**Georg Wicke-Arndt** has proposed a fix for this issue in the **rel_2_0** branch:

**Parse NOT NULL for MySQL generated columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5121
