### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by arron1227** [sqlalchemy/sqlalchemy#10872]
### Describe the bug

I want to use as asynccontextmanager for rollback.
I got 'AttributeError: __enter__' error when I execute with 'with db_session_scope() as session:' code.

### SQLAlchemy Version in Use

2.0.25

### DBAPI (i.e. the database driver)

aiomysql

### Database Vendor and Major Version

mysql 5

### Python Version

3.10

### Operating system

OSX

### To Reproduce

```python
engine = create_async_engine(url)
async_session = async_sessionmaker(engine, expire_on_commit=False)

@asynccontextmanager
async def db_session_scope():
    async with async_session() as session:
        try:
            yield session
            await session.commit()
        except:
            await session.rollback()
        finally:
            await session.close()
```

### Error

```
  File ----, line --, in ----
    with db_session_scope() as session:
AttributeError: __enter__
```

**Comment by CaselIT** [comment]
Hi,

The provided example is not what os causing that exception. You are trying to use `with` instead of `async with`

**Comment by arron1227** [comment]
Oh, It's my mistake.
Thank you so much!
