### ISSUE TITLE
replace ORM loader depth warning with notes in cache disabled message

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#10896]

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**remove loader depth warning, replace with logging message** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5128

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**remove loader depth warning, replace with logging message** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5129
