### ISSUE TITLE
Incompatible return value type

### ISSUE THREAD

**Issue by decaz** [sqlalchemy/sqlalchemy#10906]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

Return type of `ResultInternal._allrows` is `List`:
https://github.com/sqlalchemy/sqlalchemy/blob/b455b1fc03e25fc6a53cac74f3cee515c3efbf8a/lib/sqlalchemy/engine/result.py#L546

But return type of `ScalarResult.all` (and other methods) which use method specified above is more abstract - `Sequence`:
https://github.com/sqlalchemy/sqlalchemy/blob/b455b1fc03e25fc6a53cac74f3cee515c3efbf8a/lib/sqlalchemy/engine/result.py#L1775-L1783

### To Reproduce

```python
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import DeclarativeBase as Base


class User(Base):
    __tablename__ = 'user'


async def get_users(session: AsyncSession) -> list[User]:
    query = select(User)
    result = await session.execute(query)
    users = result.scalars().all()
    return users
```

### Error

```
example.py:14: error: Incompatible return value type (got "Sequence[User]", expected "list[User]")  [return-value]
Found 1 error in 1 file (checked 1 source file)
``` 

### Versions

- Python: 3.12.1
- SQLAlchemy: 2.0.25
- Type checker: mypy 1.8.0

**Comment by CaselIT** [comment]
Hi,

That's expected. If you need to return a list use `list(...)`

**Comment by decaz** [comment]
But from docstring: `Return all scalar values in a list.` and it's actual return type is exactly `list`, not a some kind of sequence..

**Comment by decaz** [comment]
@CaselIT from the [docs](https://docs.python.org/3/library/typing.html#typing.List):
```
Note that to annotate arguments, it is preferred to use an abstract collection type 
such as Sequence or Iterable rather than to use list or typing.List.
```
I mean abstract types are more suitable for annotation of arguments, not returned values.

**Comment by CaselIT** [comment]
The reasoning was already mentioned in another similar issue / discussion.

There is no use case where the return type if all needs to be modified, so sequence is appreciate since it give the ability of changing the type in the future.

**Comment by zzzeek** [comment]
ie lets update the docs to not say "list", say "sequence"

**Comment by CaselIT** [comment]
Sure, but list is kinda a generic name, but let's be specific to avoid ambiguity.
