### ISSUE TITLE
Type bool seems missing in scalar_subquery() return results

### ISSUE THREAD

**Issue by AlexanderPodorov** [sqlalchemy/sqlalchemy#10937]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

See example code.

### To Reproduce

```python
from sqlalchemy import SQLColumnExpression, select
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column()
    type: Mapped[str] = mapped_column()

    @hybrid_property
    def test(self) -> bool:
        return self.account_id == self.id

    @test.inplace.expression
    @classmethod
    def _test_expression(cls) -> SQLColumnExpression[bool]:
        return select(cls.account_id == cls.id).scalar_subquery()  # shows error, see below.


# Expression of type "ScalarSelect[int]" cannot be assigned to return type "SQLColumnExpression[bool]"
#   "ScalarSelect[int]" is incompatible with "SQLColumnExpression[bool]"
#     Type parameter "_T_co@SQLColumnExpression" is covariant, but "int" is not a subtype of "bool"
#       "int" is incompatible with "bool"


# type of "s" is "ScalarSelect[int]"
s = select(User.account_id == User.id).scalar_subquery()

# however if I add "bool" into "_NOT_ENTITY" TypeVar localed in "sqlalchemy.sql._typing.py"
# it returns correct type "ScalarSelect[bool]"

# type of "s" is "ScalarSelect[bool]" after this change
s = select(User.account_id == User.id).scalar_subquery()
```

### Versions

- OS:
- Python: 3.12.1
- SQLAlchemy: 2.0.25
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): pyright 1.1.336

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting.
I'm not sure if this is wanted or not, since not all databases can return a bool from a query like that (some of them represents conditions as ints)

cc @zzzeek

**Comment by AlexanderPodorov** [comment]
Hi,
Having it as a `bool` is nice, since we can use it as a `bool` in all related contexts.
I guess for those databases where `bool` is not supported, one can use `int` and `SQLColumnExpression[int]`.

**Comment by CaselIT** [comment]
that's likely, let's wait for mike opinion to see if he has some different suggestion here

**Comment by zzzeek** [comment]
definitely a very strange bug, with this patch, needs a test please

```diff
diff --git a/lib/sqlalchemy/sql/_typing.py b/lib/sqlalchemy/sql/_typing.py
index 570db02aa..6d54f415f 100644
--- a/lib/sqlalchemy/sql/_typing.py
+++ b/lib/sqlalchemy/sql/_typing.py
@@ -108,6 +108,7 @@ _NOT_ENTITY = TypeVar(
     "_NOT_ENTITY",
     int,
     str,
+    bool,
     "datetime",
     "date",
     "time",

```

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**A scalar subquery that returns bool is now correctly typed** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5237

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**A scalar subquery that returns bool is now correctly typed** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5238
