### ISSUE TITLE
Nested 1.x -style transaction is broken in version >=1.4.14

### ISSUE THREAD

**Issue by k-ronning** [sqlalchemy/sqlalchemy#10951]
### Describe the bug

When an exception is raised in a nested "with Connection.begin()" block, the outer/actual transaction is rolled back but the Connection state is such that the following Connection.begin() raises the error "sqlalchemy.exc.InvalidRequestError: the current transaction on this connection is inactive.  Please issue a rollback first."

### SQLAlchemy Version in Use

1.4.51

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

SQLite, PostgreSQL 15

### Python Version

3.9

### Operating system

Linux

### To Reproduce

```python
import sqlalchemy

def test():
    try:
        with dbconn.begin():
            with dbconn.begin():
                pass
            # Exception raised in the outer transaction is not problematic
            raise ValueError()
    except ValueError:
        print("Exception 1")
        
    try:
        with dbconn.begin():
            with dbconn.begin():
                raise ValueError()
    except ValueError:
        print("Exception 2")
        
    with dbconn.begin(): # this will throw sqlalchemy.exc.InvalidRequestError
        pass             # in SQLAlchemy >= 1.4.14
    
    print("Passed!")

my_engine = sqlalchemy.create_engine("sqlite://")
with my_engine.connect() as dbconn:
    test()
```

### Error

```
Traceback (most recent call last):
  File "/home/kronning/Documents/sqlalchemy_bugreport_2024-02-01/test3.py", line 27, in <module>
    test()
  File "/home/kronning/Documents/sqlalchemy_bugreport_2024-02-01/test3.py", line 20, in test
    with dbconn.begin(): # this will throw sqlalchemy.exc.InvalidRequestError
  File "/home/kronning/extsrc/sqlalchemy-rel_1_4_14/lib/sqlalchemy/engine/base.py", line 765, in begin
    return MarkerTransaction(self)
  File "/home/kronning/extsrc/sqlalchemy-rel_1_4_14/lib/sqlalchemy/engine/base.py", line 2356, in __init__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: the current transaction on this connection is inactive.  Please issue a rollback first.
``` 

### Additional context

Output of the example code in version <=1.4.13, which is expected:
```
Exception 1
Exception 2
Passed!
```

Output in version >= 1.4.14, which is wrong:
```
Exception 1
Exception 2

Traceback (most recent call last):
  File "/home/kronning/Documents/sqlalchemy_bugreport_2024-02-01/test3.py", line 27, in <module>
    test()
  File "/home/kronning/Documents/sqlalchemy_bugreport_2024-02-01/test3.py", line 20, in test
    with dbconn.begin(): # this will throw sqlalchemy.exc.InvalidRequestError
  File "/home/kronning/extsrc/sqlalchemy-rel_1_4_14/lib/sqlalchemy/engine/base.py", line 765, in begin
    return MarkerTransaction(self)
  File "/home/kronning/extsrc/sqlalchemy-rel_1_4_14/lib/sqlalchemy/engine/base.py", line 2356, in __init__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: the current transaction on this connection is inactive.  Please issue a rollback first.
```

**Comment by CaselIT** [comment]
Hi,

using a `begin` inside another `begin` is deprecated and should be raising a deprecation warning.
Use `begin_nested` instead

**Comment by k-ronning** [comment]
I understand nesting `begin` is deprecated and raises a warning, but shouldn't it still work in 1.4.x?

**Comment by k-ronning** [comment]
The commit that introduced this bug is `c5587fda7986df5851491a069830ddd4a63e01ba`.

**Comment by zzzeek** [comment]
the support for very very legacy "nesting" of transactions like that was probably never tested for context managers, as the change you refer to is about context managers, not "begin" itself.

While this may or may not be a regression, the "nesting of transactions" feature was, well until now I would have said nobody used it ever it's so legacy that it's not really worth it to revise this pretty large PR from two years ago, we are mostly done doing releases for 1.4 which is close to EOL at this point.

**Comment by k-ronning** [comment]
Thank you for the clarification! :+1:
