### ISSUE TITLE
Add type annotation to the Unicode class.

### ISSUE THREAD

**Issue by jenstroeger** [sqlalchemy/sqlalchemy#10969]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

As per discussion & comment https://github.com/sqlalchemy/sqlalchemy/discussions/10950#discussioncomment-8368380 the type annotations for `Unicode` are missing.

### To Reproduce

```python
import sqlalchemy as sa

class Base(sa.orm.DeclarativeBase):
    pass

class Table(Base):
    name: sa.orm.Mapped[str] = sa.orm.mapped_column(sa.Unicode(), primary_key=True)
```

### Error

```
unicode.py:9:53: error: Call to untyped function "Unicode" in typed context  [no-untyped-call]
        name: sa.orm.Mapped[str] = sa.orm.mapped_column(sa.Unicode(), primary_key=True)
                                                        ^~~~~~~~~~~~
``` 

### Versions

- OS: macOS Ventura 13.6.4, Darwin Kernel Version 22.6.0
- Python: Python 3.10.13 
- SQLAlchemy: 2.0.25
- Type checker: mypy 1.8.0 (compiled: yes)

**Comment by jenstroeger** [comment]
@CaselIT @zzzeek I think we can close this PR as well, it’s been addressed by commit https://github.com/sqlalchemy/sqlalchemy/commit/13c5d631177a4e30b76cef132a69ad8ad0d513ed?

**Comment by CaselIT** [comment]
Yes, thanks for reporting it!
