### ISSUE TITLE
public methods have heading underscore.

### ISSUE THREAD

**Issue by cbscsm** [sqlalchemy/sqlalchemy#11015]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

pyright checks whether a protected member is accessed by checking whether the name has a heading underscore. Some linters also check it the same way. But SQLAlchemy has some public methods with heading underscore like [Row._tuple](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Row._tuple). When I use `Row._tuple` method, pyright report errors `reportPrivateUsage` error.

### To Reproduce

```python
Run pyright with following code.

import typing

from sqlalchemy import Row


def row2tuple[T: tuple[typing.Any, ...]](row: Row[T]) -> T:
    return row._tuple()
```

### Error

```
error: "_tuple" is protected and used outside of the class in which it is declared (reportPrivateUsage)
``` 

### Versions

- OS: macOS Sonoma 14.2.1
- Python: 3.12
- SQLAlchemy: 2.0.25
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): pyright 1.1.349

### Additional context

I can ignore `reportPrivateUsage` to suppress this issue, but I want to avoid accessing real protected members.
For now, also to developers, it's hard to know which is false-protected(public but with heading underscore) and true-protected(suppose to be used internally).

PEP8 suggests trailing underscore for avoiding name collision. Instead of heading underscore. So I suggest `tuple_` method name instead of `_tuple`.

> single_trailing_underscore_: used by convention to avoid conflicts with Python keyword, e.g. :
> ```
> tkinter.Toplevel(master, class_='ClassName')
> ```

reference: https://peps.python.org/pep-0008/#descriptive-naming-styles

**Comment by CaselIT** [comment]
Hi

`Row` is following the named tuple convention, that has documented underscored method as a public methods. See _fields and _asdict.

That _tuple method will also be deprecated since it will be unnecessary in 2.1.

I'm not sure if there is a way to tell pyright that some methods are public even if underscored

**Comment by cbscsm** [comment]
I agree that it's not an issue in SQLAlchemy, since collections.namedtuple has same issue. I think pyright hard-coded about collections.namedtuple. Should I close this issue?

**Comment by CaselIT** [comment]
hopefully 2.1 will be better, since Row becomes a tuple for the type checker: https://docs.sqlalchemy.org/en/21/changelog/migration_21.html#row-now-represents-individual-column-types-directly-without-tuple


still it will still be a while before 2.1 is released
