### ISSUE TITLE
Printing the SQL Alchemy's Engine object only censures / redacts passwords up until the first `@` sign.

### ISSUE THREAD

**Issue by TabLand** [sqlalchemy/sqlalchemy#11027]
### Describe the bug

Printing the SQL Alchemy's Engine object only censures / redacts passwords up until the first `@` sign.
The issue is not reproducible when using the constructor.
If I use the `%40` escape sequence, everything is censured / redacted correctly.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

Censuring of passwords does not seem to be currently documented. A search for `***` returns only the following page:
https://docs.sqlalchemy.org/en/20/_modules/examples/space_invaders/space_invaders.html

### SQLAlchemy Version in Use

2.0.27

### DBAPI (i.e. the database driver)

mssql+pyodbc

### Database Vendor and Major Version

N/A

### Python Version

3.11.6

### Operating system

Windows

### To Reproduce

```python
import sqlalchemy
from sqlalchemy.engine import URL

print("sqlalchemy.create_engine(): Partial password prints to terminal")
engine = sqlalchemy.create_engine("mssql+pyodbc://sa:Ch@ngeM&!@localhost:1433/my_database?driver=SQL+Server+Native+Client+10.0")
print(f"{engine}\n")

print("URL.create(): No password prints to terminal")
url = URL.create("mssql+pyodbc",username="sa",password="Ch@ngeM&!", host="localhost:1433", database="my_database")
print(f"{url}\n")

print("sqlalchemy.create_engine(): No password prints to terminal")
engine = sqlalchemy.create_engine("mssql+pyodbc://sa:Ch%40ngeM&!@localhost:1433/my_database?driver=SQL+Server+Native+Client+10.0")
print(f"{engine}\n")
```

### Error

Output of reproduction steps below:

```
sqlalchemy.create_engine(): Partial password prints to terminal
Engine(mssql+pyodbc://sa:***@ngeM&!@localhost:1433/my_database?driver=SQL+Server+Native+Client+10.0)

URL.create(): No password prints to terminal
mssql+pyodbc://sa:***@[localhost:1433]/my_database

sqlalchemy.create_engine(): No password prints to terminal
Engine(mssql+pyodbc://sa:***@localhost:1433/my_database?driver=SQL+Server+Native+Client+10.0)
```

**Comment by CaselIT** [comment]
Hi,

You need to escape special characters in user and passwords when providing the url as string

**Comment by TabLand** [comment]
Related discussion: https://github.com/sqlalchemy/sqlalchemy/discussions/8547

**Comment by CaselIT** [comment]
There's also a changelog entry for this change: https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#str-engine-url-will-obfuscate-the-password-by-default
