### ISSUE TITLE
Include dialect for YugabyteDB in documentation

### ISSUE THREAD

**Issue by Sfurti-yb** [sqlalchemy/sqlalchemy#11026]
### Describe the use case

YugabyteDB is a cloud native distributed database compatible with Postgresql. 
We have developed a YugabyteDB dialect for SQLAlchemy for adding enhancements specific to YugabyteDB. 
Please let us know what are the steps to get it added in the documentation.

### Databases / Backends / Drivers targeted

Database: YugabyteDB (YSQL)
Drivers: `psycopg2` and `psycopg2-yugabytedb`

### Example Use

To connect to a local YugabyteDB cluster using `psycopg2` and `sqlalchemy_yugabytedb` plugin:
```
from sqlalchemy import create_engine
engine = create_engine('yugabytedb://yugabyte@localhost:5433/yugabyte')
```

**Comment by CaselIT** [comment]
Hi,

If I understand correctly you just want to add it to the table here https://github.com/sqlalchemy/sqlalchemy/blob/main/doc/build/dialects/index.rst

if so feel free to open a PR adding it

**Comment by CaselIT** [comment]
done in #11047
