### ISSUE TITLE
`python_implementation` marker used in `build-system.requires` is non-standard and unsupported by alternative installers

### ISSUE THREAD

**Issue by layday** [sqlalchemy/sqlalchemy#11034]
### Describe the bug

SQLAlchemy declares a conditional build dependency on Cython using the `python_implementation` environment marker. This is a non-standard, undocumented marker, which the [packaging](https://github.com/pypa/packaging/issues/72) library used by pip has inherited from setuptools, but which alternative installers might not support. [uv](https://github.com/astral-sh/uv) does not support this marker. Please consider using `platform_python_implementation` or `implementation_name` instead.  For a list of standard markers, see https://packaging.python.org/en/latest/specifications/dependency-specifiers/#environment-markers.

### SQLAlchemy Version in Use

2.1.0b1.dev0

### DBAPI (i.e. the database driver)

n/a

### Database Vendor and Major Version

n/a

### Python Version

any

### Operating system

any

### To Reproduce

Attempt installing SQLAlchemy from source with [uv](https://github.com/astral-sh/uv).

### Error

Installer-dependent.

**Comment by CaselIT** [comment]
Thanks for reporting
