### ISSUE TITLE
passing logging_name to create_engine causes messages to be duplicated

### ISSUE THREAD

**Issue by valery-iwanofu** [sqlalchemy/sqlalchemy#11054]
### Describe the bug

passing logging_name to create_engine causes messages to be duplicated

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine.params.logging_name

### SQLAlchemy Version in Use

2.0.27

### DBAPI (i.e. the database driver)

sqlite

### Database Vendor and Major Version

sqlite

### Python Version

3.12.1

### Operating system

windows

### To Reproduce

```python
from sqlalchemy import create_engine, text

def test_engine(logging_name: str | None):
    engine = create_engine('sqlite://', echo=True, logging_name=logging_name)
    with engine.begin() as conn:
        conn.execute(text('SELECT 1'))
    engine.dispose()

print('Excepted output without duplicates:')
test_engine(None)

print()
print('Actual output with duplicates:')
test_engine('custom_logging_name')
```

### Error

No errors

### Additional context

Excepted output without duplicates:
```
2024-02-24 15:49:15,498 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-02-24 15:49:15,518 INFO sqlalchemy.engine.Engine SELECT 1
2024-02-24 15:49:15,519 INFO sqlalchemy.engine.Engine [generated in 0.00078s] ()
2024-02-24 15:49:15,519 INFO sqlalchemy.engine.Engine COMMIT
```

Actual output with duplicates:
```
2024-02-24 15:49:15,522 INFO sqlalchemy.engine.Engine.custom_logging_name BEGIN (implicit)
2024-02-24 15:49:15,522 INFO sqlalchemy.engine.Engine.custom_logging_name BEGIN (implicit)
2024-02-24 15:49:15,523 INFO sqlalchemy.engine.Engine.custom_logging_name SELECT 1
2024-02-24 15:49:15,523 INFO sqlalchemy.engine.Engine.custom_logging_name SELECT 1
2024-02-24 15:49:15,523 INFO sqlalchemy.engine.Engine.custom_logging_name [generated in 0.00062s] ()
2024-02-24 15:49:15,523 INFO sqlalchemy.engine.Engine.custom_logging_name [generated in 0.00062s] ()
2024-02-24 15:49:15,524 INFO sqlalchemy.engine.Engine.custom_logging_name COMMIT
2024-02-24 15:49:15,524 INFO sqlalchemy.engine.Engine.custom_logging_name COMMIT
```

**Comment by CaselIT** [comment]
Hi,

The issue here is that you are creating the engine with echo=True twice, and that adds an handler every time.

While unfortunate `logging_name` has no influence on this. Just try commenting `test_engine(None)` in your example.

@zzzeek maybe echo should not do that? Or maybe the handler it adds could be tagged in some way so that it's not re-added if already present?

**Comment by zzzeek** [comment]
> @zzzeek maybe echo should not do that? Or maybe the handler it adds could be tagged in some way so that it's not re-added if already present?

this one is surprising to me actually.   you can make two engines with echo=True and there is no double logging.  you can make two engines w/ echo=True and both have a logging name, and there is also no double logging.   only this combination, and then you do get double logging.   

this...seems like a bug?  I dont quite understand what is making this effect yet.

**Comment by zzzeek** [comment]
oh I see what it's doing.

OK this is yeah, how can you fix that.     I guess we'd have to go up the chain of handlers, we can do that

**Comment by zzzeek** [comment]
OK we can fix it in all cases, but this would be too far for 2.0.x, like this:

```
    def _logger_has_handlers(self):
        tokens = self.logger.name.split(".")
        while tokens:
            lg = logging.getLogger(".".join(tokens))
            if lg.handlers:
                return True
            tokens.pop(-1)

        return False

```

i dont like that for 2.0.x because i cant be sure there isn't some user interaction where they have one handler for "sqlalchemy.engine" and another for the root logger and they want both to stay in place.

this can be in 2.0

```diff
diff --git a/lib/sqlalchemy/log.py b/lib/sqlalchemy/log.py
index e6922b81a..44838369c 100644
--- a/lib/sqlalchemy/log.py
+++ b/lib/sqlalchemy/log.py
@@ -134,17 +134,30 @@ class InstanceLogger:
 
     _echo: _EchoFlagType
 
-    __slots__ = ("echo", "logger")
+    __slots__ = ("echo", "logger", "extra_token")
 
-    def __init__(self, echo: _EchoFlagType, name: str):
+    def __init__(self, echo: _EchoFlagType, name: str, extra_token: Optional[str] = None):
         self.echo = echo
         self.logger = logging.getLogger(name)
+        self.extra_token = extra_token
 
         # if echo flag is enabled and no handlers,
         # add a handler to the list
-        if self._echo_map[echo] <= logging.INFO and not self.logger.handlers:
+        if (
+            self._echo_map[echo] <= logging.INFO
+            and not self._logger_has_handlers()
+        ):
             _add_default_handler(self.logger)
 
+    def _logger_has_handlers(self):
+        if self.logger.handlers:
+            return True
+        elif self.extra_token and self.logger.parent.handlers:
+            return True
+        else:
+            return False
+
+
     #
     # Boilerplate convenience methods
     #
@@ -250,7 +263,7 @@ def instance_logger(
         # if a specified echo flag, return an EchoLogger,
         # which checks the flag, overrides normal log
         # levels by calling logger._log()
-        logger = InstanceLogger(echoflag, name)
+        logger = InstanceLogger(echoflag, name, extra_token=instance.logging_name)
 
     instance.logger = logger  # type: ignore

```

**Comment by zzzeek** [comment]
this wont fix the reverse case though.

**Comment by zzzeek** [comment]
yah with the fix, this case still fails:

```py
from sqlalchemy import create_engine, text

e1 = create_engine('sqlite://', echo=True, logging_name="myname")
with e1.begin() as conn:
    conn.execute(text('SELECT 1'))

e2 = create_engine('sqlite://', echo=True)
with e2.begin() as conn:
    conn.execute(text('SELECT 2'))

with e1.begin() as conn:
    conn.execute(text('SELECT 3'))

```

there's no way to fix this as long as the logging names overlap on sqlalchemy.engine.Engine

**Comment by zzzeek** [comment]
this can't be made to be automatic, has to be a dcoumented caveat
