### ISSUE TITLE
Incompatible types in assignment

### ISSUE THREAD

**Issue by 9en9i** [sqlalchemy/sqlalchemy#11069]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

When using assignment in the model relation field, the static type analyzer outputs an error. We could fix this error, but then the code becomes incorrect in runtime. If you replace `books: Mapped[list["BookModel"]]` with `books: Mapped[Sequence["BookModel"]]`, the error appears:
`sqlalchemy.exc.ArgumentError: Collection annotation type <class 'collections.abc.Sequence'> cannot be instantiated; please provide an explicit 'collection_class' parameter (e.g. list, set, etc.) to the relationship() function to accompany this annotation`
Explicitly specifying `uselist=True` doesn't help in this case either. The sqlalchemy error still appears.

### To Reproduce

```python
from sqlalchemy import ForeignKey, select
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
    relationship,
    Session,
)


class BaseModel(DeclarativeBase):
    pass


class AuthorModel(BaseModel):
    __tablename__ = "author"
    id: Mapped[int] = mapped_column(primary_key=True)
    books: Mapped[list["BookModel"]] = relationship(
        secondary="associate_author_book",
        back_populates="authors",
        cascade="all, delete",
    )


class AssociateAutorBookModel(BaseModel):
    __tablename__ = "associate_author_book"
    author_id: Mapped[int] = mapped_column(ForeignKey("author.id"), primary_key=True)
    book_id: Mapped[int] = mapped_column(ForeignKey("book.id"), primary_key=True)


class BookModel(BaseModel):
    __tablename__ = "book"
    id: Mapped[int] = mapped_column(primary_key=True)
    authors: Mapped[list[AuthorModel]] = relationship(
        secondary="associate_author_book",
        back_populates="books",
    )


def update_author(session: Session, author: AuthorModel, new_books: list[int]) -> None:
    author.books = session.scalars(
        select(BookModel).where(BookModel.id.in_(new_books)),
    ).all()
```

### Error

error: Incompatible types in assignment (expression has type "Sequence[BookModel]", variable has type
"SQLCoreOperations[list[BookModel]] | list[BookModel]")  [assignment]

### Versions

- OS: macos 14
- Python: 3.12.1
- SQLAlchemy: 2.0.27
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.8.0

**Comment by CaselIT** [comment]
Hi,

That seems a normal type error, like assigning a set to a frozenzet.
have you tried?
```py
author.books = list(session.scalars(
        select(BookModel).where(BookModel.id.in_(new_books)),
    ).all())
```

**Comment by CaselIT** [comment]
Also you can tell relationship what collection to use by setting https://docs.sqlalchemy.org/en/20/orm/relationship_api.html#sqlalchemy.orm.relationship.params.collection_class

**Comment by 9en9i** [comment]
But .all() returns list, so why call list from list again? (execute additional code)

**Comment by 9en9i** [comment]
Can I use 
`list(session.scalars(select(BookModel).where(BookModel.id.in_(new_books))))`
instead of 
`list(session.scalars(select(BookModel).where(BookModel.id.in_(new_books))).all())`?
 I checked, at a glance it comes back the same.

**Comment by CaselIT** [comment]
yes, but using `all()` is likely baster since it avoids using the iterator
