### ISSUE TITLE
regression due to #11055

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11200]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11199

<div type='discussions-op-text'>

<sup>Originally posted by **agronholm** March 26, 2024</sup>
Mypy gives an error for the following snippet:
```python
from sqlalchemy import MetaData
from sqlalchemy.ext.asyncio import create_async_engine


async def main() -> None:
    engine = create_async_engine("sqlite:///testdb")
    metadata = MetaData()
    async with engine.begin() as connection:
        await connection.run_sync(metadata.reflect)
```
The error:
```
sqltest.py:9: error: Argument 1 to "run_sync" of "AsyncConnection" has incompatible type "Callable[[Union[Engine, Connection], Optional[str], bool, Union[Sequence[str], Callable[[str, MetaData], bool], None], bool, bool, bool, KwArg(Any)], None]"; expected "Callable[[Connection, Optional[str], bool, Union[Sequence[str], Callable[[str, MetaData], bool], None], bool, bool, bool, KwArg(Any)], None]"  [arg-type]
sqltest.py:9: note: This is likely because "reflect of MetaData" has named arguments: "bind". Consider marking them positional-only
Found 1 error in 1 file (checked 1 source file)
```
This does not happen in v2.0.28, and the likely change that caused this was #11055.

Am I doing something wrong, or is this a mypy bug, or a problem with the annotations?</div>

**Comment by zzzeek** [comment]
@francipvb any chance you can take a look at this and suggest corrections?

cc @CaselIT @agronholm

**Comment by CaselIT** [comment]
mypy is saying:
> This is likely because "reflect of MetaData" has named arguments: "bind". Consider marking them positional-only

If I apply this change
```diff
diff --git a/lib/sqlalchemy/sql/schema.py b/lib/sqlalchemy/sql/schema.py
index 8436aac43..780576e32 100644
--- a/lib/sqlalchemy/sql/schema.py
+++ b/lib/sqlalchemy/sql/schema.py
@@ -5691,6 +5691,7 @@ class MetaData(HasSchemaAttr):
     def reflect(
         self,
         bind: Union[Engine, Connection],
+        /,
         schema: Optional[str] = None,
         views: bool = False,
         only: Union[
```

then everything passes.

But we can't do that on 2.0 since 3.7 does not support them (IIRC)

**Comment by CaselIT** [comment]
This is also liked by mypy:
```diff
diff --git a/lib/sqlalchemy/sql/schema.py b/lib/sqlalchemy/sql/schema.py
index 8436aac43..04774d190 100644
--- a/lib/sqlalchemy/sql/schema.py
+++ b/lib/sqlalchemy/sql/schema.py
@@ -5690,7 +5690,7 @@ class MetaData(HasSchemaAttr):
     @util.preload_module("sqlalchemy.engine.reflection")
     def reflect(
         self,
-        bind: Union[Engine, Connection],
+        __bind: Union[Engine, Connection],
         schema: Optional[str] = None,
         views: bool = False,
         only: Union[
@@ -5786,7 +5786,7 @@ class MetaData(HasSchemaAttr):

         """

-        with inspection.inspect(bind)._inspection_context() as insp:
+        with inspection.inspect(__bind)._inspection_context() as insp:
             reflect_opts: Any = {
                 "autoload_with": insp,
                 "extend_existing": extend_existing,
@@ -5844,7 +5844,7 @@ class MetaData(HasSchemaAttr):
                     missing_str = ", ".join(missing)
                     raise exc.InvalidRequestError(
                         f"Could not reflect: requested table(s) not available "
-                        f"in {bind.engine!r}{s}: ({missing_str})"
+                        f"in {__bind.engine!r}{s}: ({missing_str})"
                     )
                 load = [
                     name
```

Overall this seems more like a bug of mypy.
pylance and pyright report no errors

**Comment by zzzeek** [comment]
we can't change that name because people may send it by name.

can we change the paramspec and/or add alternate paramspecs that work with metadata.reflect as is ?

**Comment by CaselIT** [comment]
I'm not sure. Maybe we can use some overloads?

Would it make sense to report this to mypy.

**Comment by francipvb** [comment]
Hello,

I'm looking into this. It seems that mypy is more strict with this usecase.

**Comment by zzzeek** [comment]
can we get the PR for this?

**Comment by sqla-tester** [comment]
**Francisco Del Roio** has proposed a fix for this issue in the **main** branch:

**Fix typing issue in `MetaData.reflect()` in AsyncIO context** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5242

**Comment by sqla-tester** [comment]
**Francisco Del Roio** has proposed a fix for this issue in the **rel_2_0** branch:

**Fix typing issue in `MetaData.reflect()` in AsyncIO context** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5263
