### ISSUE TITLE
message formatter is not reset when logging_token execution option is changed

### ISSUE THREAD

**Issue by nettnikl** [sqlalchemy/sqlalchemy#11210]
### Describe the bug

The logging token is not in the second statement.

### SQLAlchemy Version in Use

2.0.23

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

Postgres 15

### Python Version

3.10

### Operating system

Windows WSL

### To Reproduce

```python
sqlalchemy_logger = logging.getLogger("sqlalchemy.engine")
sqlalchemy_logger.setLevel("DEBUG")

engine = create_engine(config.POSTGRES_DATABASE_CONNECTION_STRING, pool_recycle=3600, connect_args=connect_args)
    
conn = engine.connect().execution_options(logging_token='healthcheck_1')
print(conn.execute(select(text('1'))))
    
conn = sessionmaker(bind=engine)().connection().execution_options(logging_token='healthcheck_2')
print(conn.execute(select(text('1'))))
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
```

**Comment by zzzeek** [comment]
the connection already emitted messages by the time you are calling the logging_token execution option.  the message formatter is memoized and is not reset.

**Comment by nettnikl** [comment]
Ah, that (explanation) makes sense. Appreciate the quick response and that you explained! Any help or info needed from my side?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use a full ConnectionCharacteristic for logging_token** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5216

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**use a full ConnectionCharacteristic for logging_token** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5217

**Comment by zzzeek** [comment]
nope, this would theoretically be a one liner but I dont want the perf overhead of `@property` so I've rerouted this into a more formalized system for processing execution options
