### ISSUE TITLE
Exists.select() annotated as returning Select[Any] instead of Select[bool]

### ISSUE THREAD

**Issue by wbolster** [sqlalchemy/sqlalchemy#11231]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

tl;dr: `Exists.select()` claims to return `Any`, while in reality its' a query returning a boolean:

``` python
class Exists(UnaryExpression[bool]):
    def select(self) -> Select[Any]:
```

this causes type checkers to complain about `Any` for no good reason.

some background to clarify. a query of the form

``` sql
SELECT EXISTS (
    SELECT 1
    FROM ...
    WHERE ...
)
```

… returns a scalar boolean value indicating the existence of data matching a condition.

there are multiple ways to build these in sqlalchemy, e.g. fully nested, which results in a lot of indentation and wasted space when formatted over multiple lines:

``` python
sa.select(sa.exists(sa.select(...).where(...)))
```

or via `Select.exists()` which returns `Exists`, with similar indentation ugliness:

``` python
sa.select(sa.select(...).where(...).exists())
```

alternatively, via `Select.exists()` and `Exists.select()` chaining, which looks very clean:

``` python
statement = (
    sqlalchemy.select(...)
    .where(...)
    .exists()
    .select()
)
```

all of these result in the same query, b/c:

- `Select.exists()` is a convenience helper to turn `SELECT ...` into `EXISTS (SELECT ...)`
- `Exists.select()` is a convenience helper to turn `EXISTS (...)` into `SELECT EXISTS (...)`

### To Reproduce

``` python
def f() -> bool:
    statement = (
        sqlalchemy.select(1)
        .select_from(Thing)
        .where(Thing.col == "foo")
        .exists()
        .select()
    )
    return session.scalars(statement).one()
```

### Error

Returning Any from function declared to return "bool"  [no-any-return] (python-mypy)

### Versions

- OS: linux
- Python: 3.11
- SQLAlchemy: 2.0.29
- Type checker: mypy 1.9.0

**Comment by wbolster** [comment]
unless i'm misunderstanding something, the fix could be as simple as:

``` diff
-    def select(self) -> Select[Any]:
+    def select(self) -> Select[bool]:
```

**Comment by CaselIT** [comment]
Hi,

That change makes sense. Can you open a PR to fix?

I wonder what something like oracle or mssql return here (since at least one of them cannot return bool) but from the python side it should be ok to use bool here

**Comment by sqla-tester** [comment]
**wouter bolsterlee** has proposed a fix for this issue in the **main** branch:

**typing: annotate Exists.select() to return Select[bool]** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5244

**Comment by sqla-tester** [comment]
**wouter bolsterlee** has proposed a fix for this issue in the **rel_2_0** branch:

**typing: annotate Exists.select() to return Select[bool]** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5245
