### ISSUE TITLE
MSSQL Select with `limit` and `distinct` throws error

### ISSUE THREAD

**Issue by hari01584** [sqlalchemy/sqlalchemy#11252]
### Describe the bug

MSSQL selectable returns invalid query when using both limit (ie for TOP N) and distinct, sample code:

### SQLAlchemy Version in Use

2

### DBAPI (i.e. the database driver)

pyodbc

### Database Vendor and Major Version

MSSQL

### Python Version

3.12

### Operating system

Linux

### To Reproduce

```python
select(distinct(SearchResultLog.query)).limit(10)
```

### Error

```
2024-04-10 01:59:09 sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near the keyword 'DISTINCT'. (156) (SQLExecDirectW)")
2024-04-10 01:59:09 [SQL: SELECT TOP 10 DISTINCT searchresultlog.query 
``` 

### Additional context

Instead, the correct query in this case would be: `SELECT DISTINCT TOP 10 searchresultlog.query`

**Comment by zzzeek** [comment]
we can accept PRs for this to expedite...

**Comment by zzzeek** [comment]
SQL server does not support a column-level form of distinct, you want to use [distinct()](https://docs.sqlalchemy.org/en/20/core/selectable.html#sqlalchemy.sql.expression.Select.distinct):

```py
from __future__ import annotations

from sqlalchemy import annotations
from sqlalchemy import distinct
from sqlalchemy import select
from sqlalchemy.dialects import mssql
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column

class Base(DeclarativeBase):
    pass


class A(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(primary_key=True)
    data: Mapped[str]


# wrong
stmt = select(distinct(A.data)).limit(10)
print(stmt.compile(dialect=mssql.dialect()))

# correct
stmt = select(A.data).distinct().limit(10)
print(stmt.compile(dialect=mssql.dialect()))
```

**Comment by CaselIT** [comment]
That distinct function is there to be used in aggregate expressions.

Even pg does not support such a query (distinct on has q different syntax)
