### ISSUE TITLE
add "lib" lookup and/or skip to test_pickle_rows_other_procses

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11268]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11266

this test assumes "lib" is in the PYTHONPATH which is wrong:

https://github.com/sqlalchemy/sqlalchemy/blob/483edf651f6c3db6729f8d75265241b67ccd6b80/test/sql/test_resultset.py#L521-L539

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fix missing pythonpath in test that use subprocess** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5251

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Fix missing pythonpath in test that use subprocess** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5252
