### ISSUE TITLE
ERROR: No matching distribution found for greenlet!=0.4.17;

### ISSUE THREAD

**Issue by ma9ni** [sqlalchemy/sqlalchemy#11281]
### Describe the bug

ERROR: Could not find a version that satisfies the requirement greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))) (from SQLAlchemy->-r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))) (from SQLAlchemy->-r requirements.txt (line 3))
logout
Execution failed with exit code 1

### SQLAlchemy Version in Use

SQLAlchemy 2.0.29

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.9

### Operating system

Linux

### To Reproduce

```python
pip install -r requirement.txt
```

### Error

```
ERROR: Could not find a version that satisfies the requirement greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))) (from SQLAlchemy->-r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))) (from SQLAlchemy->-r requirements.txt (line 3))
logout
Execution failed with exit code 1
```

**Comment by CaselIT** [comment]
Hi,

This seems an issue with your local install.
Also it's from a different library, so there is nothing sqlalchemy can do here.

If you are not using async you can install sqlalchemy without dependecies and it will work also without greenlet
