### ISSUE TITLE
NoForeignKeysError inconsistent error?

### ISSUE THREAD

**Issue by ElHaban3ro** [sqlalchemy/sqlalchemy#11304]
### Describe the bug

I have been getting a BUG for a couple of days now that makes NO sense whatsoever.

I am creating the services of my application divided in different files. The error comes when I try to create a many to many relationship, but although it seems to be ALL right, I can't get a consistent result. The error itself is as follows:

```
sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship SubUser.instances - there are no foreign keys linking these tables via secondary table 'instance_subuser'.
```

The relevant code here:
instances.py
```py
class Instance(Base):
"""Model for subusers.
"""
    tablename = 'instances'
    id = Column(Integer, primary_key = True)
    subusers = relationship('SubUser', secondary = InstanceSubuserRelationShipTable, back_populates='instances')
    name = Column(String, unique = True)
    # Irrelevant parameters here...
```

---
subusers.py
```py
class SubUser(Base):
"""Model for subusers.
"""
    tablename = 'subusers',
    id = Column(Integer, primary_key = True)
    instances = relationship('Instance', secondary = InstanceSubuserRelationShipTable, back_populates='subusers')
    # Irrelevant parameters here...
```

---
instance_subuser.py
```py
instances_subusers = Table(
    'instance_subuser',
    Base.metadata,
    Column('instance_id', Integer, ForeignKey('instances.id')),
    Column('subuser_id', Integer, ForeignKey('subusers.id')),
)
```

### SQLAlchemy Version in Use

2.0.29

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL v16.2

### Python Version

Python 3.11

### Operating system

Linux

### To Reproduce

```python
instances.py

class Instance(Base):
"""Model for subusers.
"""
    tablename = 'instances'
    id = Column(Integer, primary_key = True)
    subusers = relationship('SubUser', secondary = InstanceSubuserRelationShipTable, back_populates='instances')
    name = Column(String, unique = True)
    # Irrelevant parameters here...


---
subusers.py
```py
class SubUser(Base):
"""Model for subusers.
"""
    tablename = 'subusers',
    id = Column(Integer, primary_key = True)
    instances = relationship('Instance', secondary = InstanceSubuserRelationShipTable, back_populates='subusers')
    # Irrelevant parameters here...
```

---
instance_subuser.py
```py
instances_subusers = Table(
    'instance_subuser',
    Base.metadata,
    Column('instance_id', Integer, ForeignKey('instances.id')),
    Column('subuser_id', Integer, ForeignKey('subusers.id')),
)
```
```


### Error

```
2024-04-22 17:37:51.038 | ERROR    | src.backend.services.main_services:create_tables:85 - An error has happened when creating the tables: Foreign key associated with column 'instance_subuser.subuser_id' could not find table 'subusers' with which to generate a foreign key to target column 'id'
2024-04-22 17:37:51.038 | INFO     | src.backend.api.api:__init__:24 - The API has been instantiated and configured on port 3456. Debug Mode: True
2024-04-22 17:37:51.084 | ERROR    | src.backend.admin.create_admin_profile:start_form:20 - An error has been caught in function 'start_form', process 'MainProcess' (14261), thread 'Thread-1 (_start_api)' (125600580765376):
Traceback (most recent call last):

  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/relationships.py", line 2413, in _determine_joins
    self.primaryjoin = join_condition(
    │                  └ <function join_condition at 0x723bb3b0ede0>
    └ <sqlalchemy.orm.relationships.JoinCondition object at 0x723bb150af50>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/sql/util.py", line 123, in join_condition
    return Join._join_condition(
           │    └ <classmethod(<function Join._join_condition at 0x723bb390d800>)>
           └ <class 'sqlalchemy.sql.selectable.Join'>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/sql/selectable.py", line 1355, in _join_condition
    raise exc.NoForeignKeysError(
          │   └ <class 'sqlalchemy.exc.NoForeignKeysError'>
          └ <module 'sqlalchemy.exc' from '/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between '('subusers',)' and 'instance_subuser'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x723bb5358900>
    └ <Thread(Thread-1 (_start_api), started 125600580765376)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x723bb53585e0>
    └ <Thread(Thread-1 (_start_api), started 125600580765376)>
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (_start_api), started 125600580765376)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (_start_api), started 125600580765376)>
    │    └ <bound method Routines._start_api of <src.backend.routines.Routines object at 0x723bb27e4d90>>
    └ <Thread(Thread-1 (_start_api), started 125600580765376)>

  File "/home/fer/work/eva-cloud/src/backend/routines.py", line 42, in _start_api
    FirstAdmin(services = self.services).start_form()
    │                     │    └ <src.backend.services.main_services.Services object at 0x723bb43c1b90>
    │                     └ <src.backend.routines.Routines object at 0x723bb27e4d90>
    └ <class 'src.backend.admin.create_admin_profile.FirstAdmin'>

> File "/home/fer/work/eva-cloud/src/backend/admin/create_admin_profile.py", line 20, in start_form
    admins = self.services.get_admins()
             │    │        └ <function UsersService.get_admins at 0x723bb3198f40>
             │    └ <src.backend.services.main_services.Services object at 0x723bb43c1b90>
             └ <src.backend.admin.create_admin_profile.FirstAdmin object at 0x723bb150b710>

  File "/home/fer/work/eva-cloud/src/backend/services/users_services.py", line 240, in get_admins
    admins = self.session.query(User).filter(User.role == 'admin').all()
             │    │       │     │            │    └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x723bb33b0680>
             │    │       │     │            └ <class 'src.backend.models.users.User'>
             │    │       │     └ <class 'src.backend.models.users.User'>
             │    │       └ <function Session.query at 0x723bb34bb560>
             │    └ <sqlalchemy.orm.session.Session object at 0x723bb23d7010>
             └ <src.backend.services.main_services.Services object at 0x723bb43c1b90>

  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2896, in query
    return self._query_cls(entities, self, **kwargs)
           │    │          │         │       └ {}
           │    │          │         └ <sqlalchemy.orm.session.Session object at 0x723bb23d7010>
           │    │          └ (<class 'src.backend.models.users.User'>,)
           │    └ <class 'sqlalchemy.orm.query.Query'>
           └ <sqlalchemy.orm.session.Session object at 0x723bb23d7010>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 275, in __init__
    self._set_entities(entities)
    │    │             └ (<class 'src.backend.models.users.User'>,)
    │    └ <function Query._set_entities at 0x723bb35e1580>
    └ <sqlalchemy.orm.query.Query object at 0x723bb156c750>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 287, in _set_entities
    self._raw_columns = [
    └ <sqlalchemy.orm.query.Query object at 0x723bb156c750>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 288, in <listcomp>
    coercions.expect(
    │         └ <function expect at 0x723bb3c93ba0>
    └ <module 'sqlalchemy.sql.coercions' from '/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/sql/coercions...
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/sql/coercions.py", line 389, in expect
    insp._post_inspect
    │    └ <sqlalchemy.util.langhelpers.HasMemoized.memoized_attribute object at 0x723bb35d8350>
    └ <Mapper at 0x723bb5347c90; User>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
    │   │        │    │                    │    │    └ <Mapper at 0x723bb5347c90; User>
    │   │        │    │                    │    └ <function Mapper._post_inspect at 0x723bb35dd8a0>
    │   │        │    │                    └ <sqlalchemy.util.langhelpers.HasMemoized.memoized_attribute object at 0x723bb35d8350>
    │   │        │    └ '_post_inspect'
    │   │        └ <sqlalchemy.util.langhelpers.HasMemoized.memoized_attribute object at 0x723bb35d8350>
    │   └ <attribute '__dict__' of 'Mapper' objects>
    └ <Mapper at 0x723bb5347c90; User>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py", line 2711, in _post_inspect
    self._check_configure()
    │    └ <function Mapper._check_configure at 0x723bb35dcae0>
    └ <Mapper at 0x723bb5347c90; User>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py", line 2388, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    │                      │    └ <sqlalchemy.orm.decl_api.registry object at 0x723bb46ccd90>
    │                      └ <Mapper at 0x723bb5347c90; User>
    └ <function _configure_registries at 0x723bb35e07c0>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py", line 4203, in _configure_registries
    _do_configure_registries(registries, cascade)
    │                        │           └ True
    │                        └ set()
    └ <function _do_configure_registries at 0x723bb35e0900>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py", line 4244, in _do_configure_registries
    mapper._post_configure_properties()
    │      └ <function Mapper._post_configure_properties at 0x723bb35dc9a0>
    └ <Mapper at 0x723bb33b6ad0; SubUser>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py", line 2405, in _post_configure_properties
    prop.init()
    │    └ <function MapperProperty.init at 0x723bb369d620>
    └ <_RelationshipDeclared at 0x723bb33b0a50; instances>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/interfaces.py", line 584, in init
    self.do_init()
    │    └ <function RelationshipProperty.do_init at 0x723bb3597240>
    └ <_RelationshipDeclared at 0x723bb33b0a50; instances>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/relationships.py", line 1644, in do_init
    self._setup_join_conditions()
    │    └ <function RelationshipProperty._setup_join_conditions at 0x723bb35974c0>
    └ <_RelationshipDeclared at 0x723bb33b0a50; instances>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/relationships.py", line 1884, in _setup_join_conditions
    self._join_condition = jc = JoinCondition(
    │                           └ <class 'sqlalchemy.orm.relationships.JoinCondition'>
    └ <_RelationshipDeclared at 0x723bb33b0a50; instances>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/relationships.py", line 2310, in __init__
    self._determine_joins()
    │    └ <function JoinCondition._determine_joins at 0x723bb35cc540>
    └ <sqlalchemy.orm.relationships.JoinCondition object at 0x723bb150af50>
  File "/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/orm/relationships.py", line 2433, in _determine_joins
    raise sa_exc.NoForeignKeysError(
          │      └ <class 'sqlalchemy.exc.NoForeignKeysError'>
          └ <module 'sqlalchemy.exc' from '/home/fer/work/eva-cloud/.venv/lib/python3.11/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.NoForeignKeysError: Could not determine join condition between parent/child tables on relationship SubUser.instances - there are no foreign keys linking these tables via secondary table 'instance_subuser'.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify 'primaryjoin' and 'secondaryjoin' expressions.
``` 

### Additional context

_No response_

**Comment by zzzeek** [comment]
Am traveling this week.  Will have time to look early next week if no one else is available to triage this

**Comment by zzzeek** [comment]
the correct parameter for setting the tablename on a decalrative base is `__tablename__`, not `tablename`.  Fixing that, your program fails because you have an errant comma in your table definition:

```
sqlalchemy.exc.NoForeignKeysError: Can't find any foreign key relationships between '('subusers',)' and 'instance_subuser'.
                                                                                      ^^^^^^^^^^^ note tuple here


class SubUser(Base):
    tablename = 'subusers',
                         ^^^ errant comma here

    id = Column(Integer, primary_key = True)
    instances = relationship('Instance', secondary = InstanceSubuserRelationShipTable, back_populates='subusers')
    # Irrelevant parameters here...

```

**Comment by ElHaban3ro** [comment]
Ironically it wasn't that (because later I fixed it and it kept throwing error), it was ',' after the '__tablename__'. Biggest nonsense in the universe, I know.

**Comment by CaselIT** [comment]
just fyi, black and compatible formatters will format a one-tuple with parents, so your case would have become `__tablename__ = ('subusers',)`, making it more visible when there are errant comma
