### ISSUE TITLE
Generated syntax error when using funcs in server_default in MySQL

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#11317]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11315

<div type='discussions-op-text'>

<sup>Originally posted by **martinm07** April 24, 2024</sup>
Using MySQL version `8.0.29` and SQLAlchemy version `2.0.29` on Windows 10, the following code produces the further following error:
```python
from sqlalchemy import create_engine, Table, Column, MetaData, Integer, Date, func

engine = create_engine("mysql://root:password@localhost/dbname", echo=True)

metadata_obj = MetaData()
user_table = Table(
    "users",
    metadata_obj,
    Column("id", Integer, primary_key=True),
    Column("date_created", Date, server_default=func.current_date())
)

metadata_obj.create_all(engine)
```
```
sqlalchemy.exc.ProgrammingError: (MySQLdb.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds 
to your MySQL server version for the right syntax to use near 'CURRENT_TIME, \n\tPRIMARY KEY (id)\n)' at line 3")
[SQL:
CREATE TABLE users (
        id INTEGER NOT NULL AUTO_INCREMENT,
        date_created DATE DEFAULT CURRENT_TIME,
        PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
```
SQLAlchemy produces incorrect MySQL code, which should be what I put in `text()` below:
```python
from sqlalchemy import create_engine, text

engine = create_engine("mysql://root:WeMustKnowWeWillKnow@localhost/testing", echo=True)

with engine.connect() as conn:
    conn.execute(
        text("""
CREATE TABLE users (
        id INTEGER NOT NULL AUTO_INCREMENT,
        date_created DATE DEFAULT (CURRENT_TIME),
        PRIMARY KEY (id)
)
""")
    )
    conn.commit()
```
Namely, brackets around `CURRENT_TIME`.
Is this a bug, or some known limitation?</div>

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fixed a bug that caused a syntax error when a function was specified to server_default when creating a column in MySQL.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5515

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Fixed a bug that caused a syntax error when a function was specified to server_default when creating a column in MySQL.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5516

**Comment by CaselIT** [comment]
Uff gerrit picked the wrong author

**Comment by CaselIT** [comment]
fixed
