### ISSUE TITLE
ColumnCollection.get(col, default) types as Optional even with default

### ISSUE THREAD

**Issue by mark-thm** [sqlalchemy/sqlalchemy#11328]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

ColumnCollection.get(column, default) returns an Optional even when a default is specified, but the return is non-None when default is specified. 

### To Reproduce

```python
table: sa.Table = ...

col: sa.ColumnElement = table.c.get(“foo”, sa.literal(“bar”)) # disallowed, result is possibly None
```

### Error

No error — the typings result in .get returning an Optional

### Versions

- OS: MacOS Sonoma 14.x, Ubuntu 22.04
- Python: 3.11
- SQLAlchemy: 2.0.29
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.10

### Additional context

https://github.com/sqlalchemy/sqlalchemy/blob/046ebffed77aff2f5e039763af4a3eb8a122c9c8/lib/sqlalchemy/sql/base.py#L1644 should likely have an overload for when default is present.

**Comment by sqla-tester** [comment]
**Mark Elliot** has proposed a fix for this issue in the **main** branch:

**Add overload for ColumnCollection.get(col, default)** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5286

**Comment by sqla-tester** [comment]
**Mark Elliot** has proposed a fix for this issue in the **rel_2_0** branch:

**Add overload for ColumnCollection.get(col, default)** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5289
