### ISSUE TITLE
func.count argument typing issue

### ISSUE THREAD

**Issue by tspng** [sqlalchemy/sqlalchemy#11336]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

Typing error when passing `1` as an argument to `func.count()` as shown in the [docs](https://docs.sqlalchemy.org/en/20/core/functions.html#sqlalchemy.sql.functions.count).

### To Reproduce

```python
from sqlalchemy.sql.functions import func

print(func.count(1))
```

### Error

```
error: Argument 1 to "count" has incompatible type "int"; expected "ColumnElement[Any] | _HasClauseElement[Any] | SQLCoreOperations[Any] | ExpressionElementRole[Any] | Callable[[], ColumnElement[Any]] | LambdaElement | None"  [arg-type]
``` 

### Versions

- OS: macOS v14.4.1
- Python 3.12.2
- SQLAlchemy: 2.0.29
- Type checker: mypy==1.10.0

### Additional context

- The mypy typing error only shows on versions sqlalchemy > 2.0.23
- `functions` is a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810), but it has been checked. So I assume the typing should already work. Please delete the issue if I'm wrong.

**Comment by CaselIT** [comment]
Hi,

It's already reported here https://github.com/sqlalchemy/sqlalchemy/discussions/11316
