### ISSUE TITLE
Bundle labels are wrong for new style select only (query works ?!)

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11347]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11345

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy.orm import Bundle
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Session
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    x = Column(Integer)
    y = Column(Integer)
    z = Column(Integer)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(x=1, y=2, z=3))
s.commit()

new_row = s.execute(
    select(A.x, A.y, Bundle("mybundle", A.x, A.z))
).one()

old_row = s.query(A.x, A.y, Bundle("mybundle", A.x, A.z)).one()


assert old_row[2]._mapping == {"x": 1, "z": 3}  # works

# fails
assert new_row[2]._mapping == {"x": 1, "z": 3}, f"nope: {new_row[2]._mapping}"

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**disable col deduping inside of Bundle** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5276

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**disable col deduping inside of Bundle** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5277

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**revise approach for bundle deduping** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5280

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**revise approach for bundle deduping** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5301

**Comment by Neah-Ko** [comment]
Hello @zzzeek ,

I'm bringing more activity to this matter as I may have found another bug.
I've updated my sqlalchemy version to latest today and worked on the feature described in the discussion.

The feature worked nicely with my initial version of the function, only handling `x-to-one` (nested entities) relationships.
I went on to tackle `x-to-many` (nested lists) relationships
My statement building currently looks like this: 


```python
       rels = table.relationships()
        nested, fields = partition(fields, lambda x: x in rels)
        stmt = select(
            DictBundle(
                table,  
                *[getattr(table, f) for f in fields],
                *[
                    DictBundle(
                        nes,
                        *[
                            getattr(get_declarative_class(rels[nes].target), f) 
                            for f in [
                                x.name for x in rels[nes].target.columns
                            ]
                        ]
                    )
                    for nes in nested
                ],
            )
        )
        joins = []
        for rel, nes in zip(rels, nested):
            # Handle x-to-many (nested lists) relationships
            if rel.secondary is not None:
                stmt = stmt.join_from(self.table, rel.secondary)
            stmt = stmt.join_from(self.table, rel.target)
     stmt = stmt.where(...)
```

## Example

On a similar example as in the discussion, where `myresource` has now `tags` attached:

```python
class Tag(Base):
    name = Column(String, primary_key=True)

class MyResource(Base):
  id = ...
  ...
  tags:    Mapped[Set["Tag"]]  = relationship(secondary=asso_res_tag, uselist=True, lazy="joined")

asso_res_tag = Table(
    "ASSO_RES_TAG",
    Base.metadata,
    Column("id_myresource",   ForeignKey("MYRESOURCE.id"),       primary_key=True),
    Column("name_tag",          ForeignKey("TAG.name"),                    primary_key=True),
)
```

and trying out with some test case:
```bash
curl -d '{ "name": "test", "contact": {"username": "test"},  "tags": [{"name":"bip"}, {"name":"bap"}, {"name":"bop"}],}' http://127.0.0.1:8000/myresources/
```

and querying my object
```bash
curl  http://127.0.0.1:8000/myresources/1?name,contact,tags
```

query result before serialization:
```python
{'name': 'test', 'contact': {'username': 'test', 'email': None, 'firstName': None, 'lastName': None}, 'tags': {'name': 'bap'}}
```

and after serialization I completely loose the `tags` fields because marshmallow is expecting a list for it.
So my best guess is that somewhere in the pipeline, `uselist` isn't consumed.
I've tried adding an `id` to the tags table and changing the relationship/associative table accordingly hoping to help statement inferences and it didn't.

Let me know if you have a clue.

Best regards,

**Comment by zzzeek** [comment]
im not sure what you're doing there.  uselist only has to do with loading ORM objects, and a Bundle does not load ORM objects.    the join_from calls are fine but uselist has no interaction with those.

**Comment by Neah-Ko** [comment]
Good evening,
I'm sorry about bringing `uselist` into this it was a bad wording inspiration on my part. I have little idea on how most of the core works, and frankly the source code is quite impressive.


For my issue, 
I meant that it is only fetching a single result when querying a table object relationship column that is supposed to be a list.
It is returning only the top indexed as a single item which is then shaved at serialization step.


The snippets I've provided were describing my attempt at querying a table object with the possibility to restrict on a list of `fields` (or defaults to a regular `select(table)`)
  - Some of those fields may be `relationship` fields 
     -> So query and join those tables as well 

The goal is to implement a an abstract REST GET function i.e.: `/resource?field`
If you want to run the code you may find it here: https://github.com/bag-cnag/biodm/tree/dev
It is still work in progress, but I've documented how to install and setup


The source that I've provided are somewhat simplified examples of me tinkering with this [function](https://github.com/bag-cnag/biodm/blob/2655df980fa4f4f40be12449a7eb81e97e3c5b35/src/biodm/components/services/dbservice.py#L437)


I'm testing with the following command to create a dataset:
``` bash
curl -d '{"id": 1, "version": 1, "name": "ds_test", "contact": {"username": "test"}, "owner_group": {"name": "g"}, "tags": [{"name":"bip"}, {"name":"bap"}, {"name":"bop"}], }' http://127.0.0.1:8000/datasets/
``` 

and query it that way:
``` 
curl http://127.0.0.1:8000/datasets/1_1?fields=name,contact,tags
``` 

which yields the following sql code when I print the statement before executing it.

```
SELECT "DATASET".name, "USER".id, "USER".username, "USER".email, "USER"."firstName", "USER"."lastName", "TAG".id AS id_1, "TAG".name AS name_1 
FROM "DATASET" JOIN "USER" ON "USER".username = "DATASET".username_user_contact JOIN "ASSO_DATASET_TAG" ON "DATASET".id = "ASSO_DATASET_TAG".id_dataset AND "DATASET".version = "ASSO_DATASET_TAG".version_dataset JOIN "TAG" ON "TAG".id = "ASSO_DATASET_TAG".id_tag 
WHERE "DATASET".id = :id_2 AND "DATASET".version = :version_1
```

which when I run directly in my postgres DB plugging in my values for id and version `(1, 1)` gets me:

```
   name   | id | username | email | firstName | lastName | id_1 | name_1 
----------+----+----------+-------+-----------+----------+------+--------
 ds_test |    | test     |       |           |          |    1 | bip
 ds_test |    | test     |       |           |          |    2 | bap
 ds_test |    | test     |       |           |          |    3 | bop
```

So in principle the core gets back all my tags but doesn't make a list out of it when building my `Dataset` item
c.f. result  before serialization in my comment above.

Best,

**Comment by zzzeek** [comment]
I dont see any code here that I can run so I still dont really know what it is you're doing.  is this still involving Bundle?  Bundle only returns columns.  you will get every row back individually.   sub-bundles aren't going to be merged into lists or anything like that.

**Comment by zzzeek** [comment]
this is sort of not the place to keep discussing this.  if you can take [this program](https://github.com/sqlalchemy/sqlalchemy/issues/11347#issue-2275804209) and alter it to show an example of this "one row when there should be three" thing, start a new discussion
