### ISSUE TITLE
_JoinedListener can sneak into a metadata collection if Enum adapts itself, which can happen now, prohibiting serialization

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11365]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11360
```py
import pickle
import sqlalchemy as sa
from sqlalchemy.orm.decl_api import declarative_base

# Get base and metadata
base = declarative_base()
sa_metadata = base.metadata

class _Foo(base):
    __abstract__ = True
    __tablename__ = "foo"

    id_ = sa.Column(sa.Integer(), primary_key=True)
    column1 = sa.Column(sa.Enum("red", "green", name="column1"))

class Foo(_Foo):
    pass

pickle.dumps(sa_metadata)
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**setup JoinedDispatch to support pickling** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5302

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**setup JoinedDispatch to support pickling** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5303
