### ISSUE TITLE
Add `insert_default` param to `Column`

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#11374]
I think we might want to consider adding the `insert_default` param to `Column` directly and making that the official name.  not sure why I didn't start doing that in 2.0

_Originally posted by @zzzeek in https://github.com/sqlalchemy/sqlalchemy/discussions/11372#discussioncomment-9373965_

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add ``insert_default`` to ``Column``.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5299

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Add ``insert_default`` to ``Column``.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5300
