### ISSUE TITLE
TypeAlias cannot be found in type_annotation_map

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/sqlalchemy#11370]
### Describe the bug

I have a `TypeAlias` that I'm trying to put in `type_annotation_map` but SQLAlchemy can't seem to find it.

(my naive understanding was that `Json` in the example would be looked up directly by hash in the annotation map)

### SQLAlchemy Version in Use

2.0.30

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 12

### Python Version

3.10

### Operating system

macOS

### To Reproduce

```python
from typing import Annotated, Dict, List, Optional, TypeAlias, Union

from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

JsonPrimitive: TypeAlias = Union[str, int, float, bool, None]
JsonObject: TypeAlias = Dict[str, "Json"]
JsonArray: TypeAlias = List["Json"]
Json: TypeAlias = Union[JsonObject, JsonArray, JsonPrimitive]


class Base(DeclarativeBase):
    type_annotation_map = {
        Json: JSONB(none_as_null=True),
    }


class Model(Base):
    __tablename__ = "model"

    id: Mapped[int] = mapped_column(primary_key=True)
    data: Mapped[Optional[Json]]
```

### Error

```
Traceback (most recent call last):
  File "/scratch_184.py", line 25, in <module>
    class Model(Base):
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 836, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 244, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 325, in setup_mapping
    return _ClassScanMapperConfig(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 571, in __init__
    self._extract_mappable_attributes()
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1541, in _extract_mappable_attributes
    value.declarative_scan(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/properties.py", line 709, in declarative_scan
    self._init_column_for_annotation(
  File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/properties.py", line 880, in _init_column_for_annotation
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not locate SQLAlchemy Core type for Python type typing.Union[str, int, bool, float, typing.Dict[str, ForwardRef('Json')], typing.List[ForwardRef('Json')]] inside the 'data' attribute Mapped annotation
``` 

### Additional context

There's still an error even if the TypeAlias is not self-referential:

```python
JsonPrimitive: TypeAlias = Union[str, int, float, bool, None]
JsonObject: TypeAlias = Dict[str, object]
JsonArray: TypeAlias = List[object]
Json: TypeAlias = Union[JsonObject, JsonArray, JsonPrimitive]
```

but weirdly it works if `JsonPrimitive` doesn't have `None`:

```python
JsonPrimitive: TypeAlias = Union[str, int, float, bool]
JsonObject: TypeAlias = Dict[str, object]
JsonArray: TypeAlias = List[object]
Json: TypeAlias = Union[JsonArray, str, int, float]
```

(both of these types aren't very useful, so I would specify the JSONB explicitly in `mapped_column`, but I thought it's worth mentioning what I'd tried).

**Comment by zzzeek** [comment]
we probably cant use Unions as keys, kind of an edge case

**Comment by zzzeek** [comment]
do we have a patch for this?    near term label is for stuff we have a fix set up for.   this one is in that intricate place w/ the type guessing etc

**Comment by CaselIT** [comment]
I'm not sure it can be fixed, since changing the current logic would change the current behaviour.

The main issue here is that we have an union that includes None in the column type, since this is a json column and there are two null supported: json-null and sql-null. This conflicts with the logic used to detect if a column is nullable, meaning that in the type map we look for the union-without-none.

Overall this case is undecidable, so I would flag it as won't fix, maybe adding that special case to the error message / linked error link.

**Comment by sqla-tester** [comment]
**Frazer McLean** has proposed a fix for this issue in the **main** branch:

**Permit optional types in type annotation map** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5513

**Comment by zzzeek** [comment]
this can't be cleanly fixed until we fix the architecture that's broken in #11944

**Comment by sqla-tester** [comment]
**Frazer McLean** has proposed a fix for this issue in the **main** branch:

**General improvement on annotated declarative** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5513

**Comment by sqla-tester** [comment]
**Frazer McLean** has proposed a fix for this issue in the **main** branch:

**Permit optional types in type annotation map** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5513

**Comment by sqla-tester** [comment]
**Frazer McLean** has proposed a fix for this issue in the **rel_2_0** branch:

**Permit optional types in type annotation map** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5600
