### ISSUE TITLE
Assign column to None to change to server_default for make_transient

### ISSUE THREAD

**Issue by riwu** [sqlalchemy/sqlalchemy#11405]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

I want to assign a non-nullable column to `None` so that the value can be reset to the `server_default`.

However, this throws a mypy error since the column typing is not optional.

### To Reproduce

```python
from datetime import datetime
from sqlalchemy import func

Class Table(Base):
    inserted_on: Mapped[datetime] = mapped_column(server_default=func.now())

obj = session.scalar(select(Table))
make_transient(obj)
obj.inserted_on = None
session.add(obj)
```

### Error

```
error: Incompatible types in assignment (expression has type "None", variable has type "SQLCoreOperations[datetime] | datetime") [assignment]
``` 

### Versions

- OS: Windows
- Python: 3.11.8
- SQLAlchemy: 2.0.29
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.10.0

**Comment by CaselIT** [comment]
Hi,

I think this is currently working as expected.
Also assigning to `None` will not set a non-nullable column to default, it will raise a non-null violation. For example on postgresql this will lead to `null value in column "..." of relation ".." violates not-null constraint`

You can use DEFAULT for this, using `literal_column()` (at least on postgresql):
```py
obj.inserted_on = literal_column("DEFAULT")
```

@zzzeek is there a more integrated way in sqlalchemy to do this?

**Comment by riwu** [comment]
@CaselIT have you tried my code above? Assigning to `None` does work if the column has `server_default` set and we executed `make_transient` on the object.

Your suggestion works too but assigning to `None` seems a lot more succcient.

**Comment by CaselIT** [comment]
It's not an issue of working or not. The issue here is only regarding the type checker.
You have specified that a column cannot be nullable `Mapped[datetime]`. Allowing `None` to be set would defeat the intent, don't you think?

**Comment by riwu** [comment]
Agree, though maybe we could have a custom function instead of hardcoding a `"DEFAULT"` string.  
Maybe something similar to the `false` etc functions that already exists?
```
from sqlalchemy import default 
literal_column(default())
```

**Comment by CaselIT** [comment]
that may be an idea, but you would not need literal_column then, just 
```
obj.inserted_on = default()
```

@zzzeek what do you think? I'm not sure if this concept is general enough that's supported by multiple dbs

**Comment by CaselIT** [comment]
From a very quick check it seems that `insert xx values (default)` works on postgresql, oracle, mysql (assuming mariadb too) and sqlserver. Seems not implemented in sqlite (at least from the docs)

So it may be worth doing?

**Comment by zzzeek** [comment]
if you want to assign None on the python side just make sure the type is optional:

```py
class Table(Base):
    inserted_on: Mapped[Optional[datetime]] = mapped_column(nullable=True, server_default=func.now())
```

this is documented [here](https://docs.sqlalchemy.org/en/20/orm/declarative_tables.html#mapped-column-derives-the-datatype-and-nullability-from-the-mapped-annotation):

> It is also perfectly valid to have a [mapped_column()](https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.mapped_column) whose nullability is different from what would be implied by the annotation. For example, an ORM mapped attribute may be annotated as allowing None within Python code that works with the object as it is first being created and populated, however the value will ultimately be written to a database column that is NOT NULL. The [mapped_column.nullable](https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.mapped_column.params.nullable) parameter, when present, will always take precedence:

**Comment by zzzeek** [comment]
if you want a special "None" datetime, you could do this:


```py
if TYPE_CHECKING:
     NONE_DATETIME: datetime
else:
    NONE_DATETIME = None
```
