### ISSUE TITLE
fix in issue 10365 also fixed an ORM select() issue  that likely has no test coverage

### ISSUE THREAD

**Issue by jdimmerman** [sqlalchemy/sqlalchemy#11412]
### Describe the bug

A query including a polymorphic child but not selecting from polymorphic column set excludes the polymorphic filter. This impacts with `select()` and `with_entities()`.

### SQLAlchemy Version in Use

2.0.30

### DBAPI (i.e. the database driver)

psycopg2, though I replicated without specifying a driver in pyfiddle

### Database Vendor and Major Version

PostgreSQL, though appears agnostic to vendor

### Python Version

3.12.2

### Operating system

Mac, Linux

### To Reproduce

```python
Consider the configuration:


from sqlalchemy import select
from sqlalchemy import ForeignKey, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
     pass

class User(Base):
     __tablename__ = "user_account"

     id: Mapped[int] = mapped_column(primary_key=True)
     address_id: Mapped[int] = mapped_column(ForeignKey("address.id"))
     model_type: Mapped[str] = mapped_column(String(50))
     __mapper_args__ = {"polymorphic_identity": "base", "polymorphic_on": "model_type"}


class Admin(User):
     __mapper_args__ = {"polymorphic_identity": "admin"}

class Address(Base):
     __tablename__ = "address"
     id: Mapped[int] = mapped_column(primary_key=True)
```

```
print(select(Address.id, Admin.id).select_from(Admin).join(Address))
```
Results in the following. as expect. Note the `WHERE` clause.
```
SELECT address.id, user_account.id AS id_1 
FROM user_account JOIN address ON address.id = user_account.address_id 
WHERE user_account.model_type IN ('admin')
```

```
print(select(Address.id).select_from(Admin).join(Address))
```
Results in the following. Note the absence of the `WHERE` clause.
```
SELECT address.id
FROM user_account JOIN address ON address.id = user_account.address_id 
```
```


### Error

Note the missing WHERE clause in the reproduction

### Additional context

_No response_

**Comment by jdimmerman** [comment]
Odd! I reproduced locally and then again in a python fiddle with my minimalist example: [https://python-fiddle.com/saved?checkpoint=1716561570 (](https://python-fiddle.com/saved/Mf8Y0oUm37DfVyOINqjQ)

I'm still able to reproduce with your example

![image](https://github.com/sqlalchemy/sqlalchemy/assets/12055704/9f338067-e3e2-4051-9c42-edaba619327f)

**Comment by zzzeek** [comment]
has your SQLAlchemy installation been modified?   can you verify you're on 2.0.30?  it looks like older 2.0.x versions do have this bug, so likely an upgrade needed

**Comment by jdimmerman** [comment]
Confirming my local version now. Indeed the python fiddle is using 2.0.20

**Comment by jdimmerman** [comment]
I'm still seeing the issue locally on 2.0.30 but my local configuration is much more complex, which may or may not be a contributing factor. I'll try and match your reproduction and go from there. Thanks for the quick feedback.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Add test for issue 11412** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5305

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**Add test for issue 11412** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5306

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**Add test for issue 11412** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5307

**Comment by jdimmerman** [comment]
Ah so I can still replicate the issue with the legacy ORM syntax, but agreed the query syntax fix is good on 2.0.30.

Issue exists in:
```
print(session(Admin).join(Address).with_entities(Address.id))
```

**Comment by jdimmerman** [comment]
Full reproduction on 2.0.30

```
from sqlalchemy import select
from sqlalchemy import ForeignKey, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, Query


class Base(DeclarativeBase):
     pass

class User(Base):
     __tablename__ = "user_account"

     id: Mapped[int] = mapped_column(primary_key=True)
     address_id: Mapped[int] = mapped_column(ForeignKey("address.id"))
     model_type: Mapped[str] = mapped_column(String(50))
     __mapper_args__ = {"polymorphic_identity": "base", "polymorphic_on": "model_type"}


class Admin(User):
     __mapper_args__ = {"polymorphic_identity": "admin"}

class Address(Base):
     __tablename__ = "address"
     id: Mapped[int] = mapped_column(primary_key=True)

# this includes the WHERE clause
print(select(Address.id).select_from(Admin).join(Address))

# this is missing the WHERE clause
print(Query(Admin).join(Address).with_entities(Address.id))
```

**Comment by zzzeek** [comment]
Query converts to a select() internally but only at the end.  it's all legacy stuff that we dont really want to mess with if we dont have to.

**Comment by jdimmerman** [comment]
Understood!
