### ISSUE TITLE
`FunctionFilter.filter` should be generative, not mutate in-place 

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#11426]
I think there is also a bug in `FunctionFilter.filter`: should be generative but isn't https://github.com/sqlalchemy/sqlalchemy/blob/deb285550a26f37c4bc3a0289df370691e25843c/lib/sqlalchemy/sql/elements.py#L4403-L4424

_Originally posted by @CaselIT in https://github.com/sqlalchemy/sqlalchemy/issues/11423#issuecomment-2135965910_

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Make `FunctionFilter.filter` generative** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5326
