### ISSUE TITLE
Legacy class names are not fully imported by sqlalchemy.orm.collections.*

### ISSUE THREAD

**Issue by kajinamit** [sqlalchemy/sqlalchemy#11435]
### Describe the bug

Classes in `sqlalchemy.orm.collections` module were renamed in SQLAlchemy 2.0, but some of the legacy names are not imported by `sqlalchemy.orm.collections.*` while the others are.
It's ideal that the behavior is consistent for all legacy class names.

### SQLAlchemy Version in Use

2.0.30

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.11.7

### Operating system

Fedora 38

### To Reproduce

```
>>> from sqlalchemy.orm.collections import *
>>> attribute_mapped_collection
>>> MappedCollection
```

MappedCollection and attribute_mapped_collection are both legacy names but only attribute_mapped_collection is not loaded.

### Error

```
>>> from sqlalchemy.orm.collections import *
>>> attribute_mapped_collection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'attribute_mapped_collection' is not defined
>>> MappedCollection
<class 'sqlalchemy.orm.mapped_collection.KeyFuncDict'> 
```

**Comment by zzzeek** [comment]
obviously no test is needed, dont worry about the label.  just the imports and a changelog file in doc/build/changelog/unreleased_20/ as mentioned.  thanks!

**Comment by sqla-tester** [comment]
**Takashi Kajinami** has proposed a fix for this issue in the **main** branch:

**Import all legacy classes by sqlalchemy.orm.collections.*** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5418

**Comment by sqla-tester** [comment]
**Takashi Kajinami** has proposed a fix for this issue in the **rel_2_0** branch:

**Import all legacy classes by sqlalchemy.orm.collections.*** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5428

**Comment by zzzeek** [comment]
im just going to commit these without any specific test added
