### ISSUE TITLE
InstanceState modified and expired are not documented

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#11431]
As the title says

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Document InstanceState modified and expired.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5331

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Document InstanceState modified and expired.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5332
