### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlalchemy.sql.cache_key'

### ISSUE THREAD

**Issue by brunolnetto** [sqlalchemy/sqlalchemy#11465]
### Describe the bug

I use sqlalchemy for routinary data science activities, like web scrapping and data analysis. During one of my activities, sqlalchemy started reporting following error `ModuleNotFoundError: No module named 'sqlalchemy.sql.cache_key'`. My SQLAlchemy version is 2.0.30. I installed it inside an environment createdby command run `virtualenv .venv && source .venv/inn/activate && pip install sqlalchemy` 

### SQLAlchemy Version in Use

2.0.30

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL

### Python Version

3.8.10

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import create_engine, pool
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

POSTGRES_HOST='localhost'
POSTGRES_PORT=5432
POSTGRES_USER='postgres'
POSTGRES_PASSWORD='postgres'
POSTGRES_DBNAME='mydb'

uri=f'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DBNAME}'

engine = create_engine(
    uri,
    poolclass=pool.QueuePool,   # Use connection pooling
    pool_size=20,               # Adjust pool size based on your workload
    max_overflow=10,            # Adjust maximum overflow connections
    pool_recycle=3600           # Periodically recycle connections (optional)
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base.metadata.create_all(engine)
```
```


### Error

```
Traceback (most recent call last):
  File "tests/test_db.py", line 1, in <module>
    from sqlalchemy import create_engine, pool
  File "/home/brunolnetto/github/RF_CNPJ/.venv/lib/python3.8/site-packages/sqlalchemy/__init__.py", line 13, in <module>
    from .engine import AdaptedConnection as AdaptedConnection
  File "/home/brunolnetto/github/RF_CNPJ/.venv/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 18, in <module>
    from . import events as events
  File "/home/brunolnetto/github/RF_CNPJ/.venv/lib/python3.8/site-packages/sqlalchemy/engine/events.py", line 19, in <module>
    from .base import Connection
  File "/home/brunolnetto/github/RF_CNPJ/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 30, in <module>
    from .interfaces import BindTyping
  File "/home/brunolnetto/github/RF_CNPJ/.venv/lib/python3.8/site-packages/sqlalchemy/engine/interfaces.py", line 38, in <module>
    from ..sql.compiler import Compiled as Compiled
  File "/home/brunolnetto/github/RF_CNPJ/.venv/lib/python3.8/site-packages/sqlalchemy/sql/__init__.py", line 13, in <module>
    from .base import Executable as Executable
  File "/home/brunolnetto/github/RF_CNPJ/.venv/lib/python3.8/site-packages/sqlalchemy/sql/base.py", line 47, in <module>
    from .cache_key import HasCacheKey  # noqa
ModuleNotFoundError: No module named 'sqlalchemy.sql.cache_key'
``` 

### Additional context

_No response_

**Comment by CaselIT** [comment]
Hi,

Please try re-installing sqlalchemy. You seem to have corrupted your venv

**Comment by brunolnetto** [comment]
@CaselIT Great! Thanks for helping me out. Since you are here, is there any elegant way to handle DDL operations like database and roles creation only with SQLAlchemy? Please, provide me some references

**Comment by CaselIT** [comment]
Sqlalchemy does not have constructs that handle creation of db and reles, but you can easily execute the SQL strings for them.

For postgresql there may be some further support in the external extension called sqlalchemy-utils

**Comment by CaselIT** [comment]
Oh you may also look at https://docs.sqlalchemy.org/en/20/core/ddl.html#sqlalchemy.schema.DDL

**Comment by brunolnetto** [comment]
Anything that mimics the parametrized SQL will be of great help.

```
CREATE DATABASE "$POSTGRES_NAME"
        WITH
        OWNER = "$POSTGRES_USER"
        ENCODING = 'UTF8'
        CONNECTION LIMIT = -1;
    
    CREATE DATABASE "$POSTGRES_NAME"_Test
        WITH
        OWNER = "$POSTGRES_USER"
        ENCODING = 'UTF8'
        CONNECTION LIMIT = -1;

    CREATE USER "$POSTGRES_USER" WITH PASSWORD "$POSTGRES_PASSWORD";
    GRANT pg_read_all_data, pg_write_all_data ON DATABASE "$POSTGRES_NAME"_Test TO "$POSTGRES_USER";
```

**Comment by CaselIT** [comment]
I'm not sure if ddl supports parameterization.

But sqlalchemy-utils does have a method to add a database

**Comment by brunolnetto** [comment]
This was of great help. I guess, much of my troubles are to despair often when not achieving some goal.

**Comment by brunolnetto** [comment]
@CaselIT Would you mind taking a look at issue [1]? It basically says I am able to use sqlalchemy_utils on a local application, or with a dockerized database, but not when both are dockerized. I use the service name, yes, as host.


https://github.com/kvesteri/sqlalchemy-utils/issues/743
