### ISSUE TITLE
Raise an exception when a viewonly relationship is written to

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#1147]
**Migrated issue, originally created by Anonymous**

(original reporter: ged) It would be nice if this safeguard was implemented... And by the way, shouldn't the examples at:
http://www.sqlalchemy.org/docs/05/mappers.html#advdatamapping_relation_customjoin
http://www.sqlalchemy.org/docs/05/mappers.html#advdatamapping_relation_customjoin_multiplejoin
be set as viewonly?

**Comment by zzzeek** [comment]
I have no intention to work on this but others are welcome to if they want this implemented.
