### ISSUE TITLE
dataclasses integration with kw_only wrongly type errors on inherited Base with mixin

### ISSUE THREAD

**Issue by Avishayy** [sqlalchemy/sqlalchemy#11485]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

When a mapped class uses a Base class with the MappedAsDataclass mixin with `kw_only=True`, it should be OK for columns with default values to be after columns without one and it does work just fine in runtime, but pyright still yells
```
Fields without default values cannot appear after fields with default values Pyright (reportGeneralTypeIssues)
```
adding `kw_only=True` (redundant) to the mapped class fixes the typing issue.

### To Reproduce

```python
from typing import Optional
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column


class Base(MappedAsDataclass, DeclarativeBase, kw_only=True):
    id: Mapped[int] = mapped_column(
        init=False, primary_key=True
    )

class User(Base):
    email: Mapped[str]
    favorite_band: Mapped[Optional[str]] = mapped_column(default=None)

    # Pyright: Fields without default values cannot appear after fields with default values Pyright (reportGeneralTypeIssues)
    # Works in runtime
    password: Mapped[str]


class UserWorking(Base, kw_only=True):
    email: Mapped[str]
    favorite_band: Mapped[Optional[str]] = mapped_column(default=None)

    # OK
    password: Mapped[str]
```

### Error

```
Fields without default values cannot appear after fields with default values Pyright (reportGeneralTypeIssues)
``` 

### Versions

- OS: MacOS 14.3.1 (23D60)
- Python: 3.12
- SQLAlchemy: 2.0.30
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): pyright 1.1.367

### Additional context

It should be noted that I tested regular dataclasses
```python
@dataclass(kw_only=True)
class A:
    b: Optional[str] = None
    c: int

@dataclass
class B(A):
    d: str 
```
and this works without and typing issue on `d`

This might be a typing issue of pyright, but I'm not proficient enough in typings to figure out whose fault it is, and I felt here is a good start.

For now, I'll use kw_only=True on my classes that have such behavior.

**Comment by zzzeek** [comment]
this is a bug either in both mypy and pyright, or, we aren't supposed to allow what you have to work at runtime.   I would report this to mypy first.

Working with [pep-681](https://peps.python.org/pep-0681/), here's your failing test illustrated without using SQLAlchemy:

```py
from typing import Optional, Any
import typing_extensions


def field(default: Any=None, init: bool=True, repr: bool=True) -> Any:
    pass

@typing_extensions.dataclass_transform(
    field_specifiers=(
        field,
    )
)
class ModelMeta(type):
    pass

class ModelBase(metaclass=ModelMeta):
    def __init_subclass__(cls, kw_only: bool=False) -> None:
        pass

class Base(ModelBase, kw_only=True):
    pass

class Vehicle(Base):
    b: Optional[str] = field(default=None)
    c: int

```

mypy:

```
test5.py:25: error: Attributes without a default cannot follow attributes with one  [misc]
Found 1 error in 1 file (checked 1 source file)

```

to resolve, put  kw_only on`Vehicle` directly.  This also solves the top issue if kw_only is placed on `User` directly:

```py
from typing import Optional, Any
import typing_extensions


def field(default: Any=None, init: bool=True, repr: bool=True) -> Any:
    pass

@typing_extensions.dataclass_transform(
    field_specifiers=(
        field,
    )
)
class ModelMeta(type):
    pass

class ModelBase(metaclass=ModelMeta):
    def __init_subclass__(cls, kw_only: bool=False) -> None:
        pass

class Base(ModelBase):
    pass

class Vehicle(Base, kw_only=True):
    b: Optional[str] = field(default=None)
    c: int


```

mypy:

```
Success: no issues found in 1 source file
```

SQLAlchemy has no ability to modify this typing behavior as we can only use what the typing tools give us, so I'd report this upstream to them.

**Comment by Avishayy** [comment]
Thank you @zzzeek, I appreciate the detailed response. I'll report this upstream.
