### ISSUE TITLE
Support two-phase commit in oracledb

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#11480]
The oracledb 2.3 adds support for two-phase commit in thin mode, so it makes sense to enable it in the ci

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add support for two-phase commit in oracledb.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5334

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Add support for two-phase commit in oracledb.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5416
