### ISSUE TITLE
MyPy doesnt not report errors in attribute assignment (strict, 2.0)

### ISSUE THREAD

**Issue by funkindy** [sqlalchemy/sqlalchemy#11517]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

I dont get any mypy errors on ORM instances initializing/assignment with wrong types. 

### To Reproduce

```python
import uuid

from sqlalchemy import Integer, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Test(DeclarativeBase):
    __tablename__ = 'test'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name = mapped_column(String)


test = Test(id=uuid.uuid4(), name=1)  # wrong types here
test.name = [1, 2, 3]  # and here
```

### Error

No error:
```
(.venv) ➜  mypy sa.local.py --strict
Success: no issues found in 1 source file
```

### Versions

- OS: MacOS
- Python: 3.12
- SQLAlchemy: 2.0.21
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.10.0

### Additional context

I expect mypy here to indicate that the assignments have wrong types. Maybe i am missing something?

Thank you!

**Comment by CaselIT** [comment]
Hi,

There is no annotation in `name` so any is inferred. Use `name: Mapped[str]`

**Comment by funkindy** [comment]
@CaselIT thanks, my bad i forgot it. This fixes attribute value assignment, but have no effect on instantiation:

```python
import uuid

from sqlalchemy import Integer, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Test(DeclarativeBase):
    __tablename__ = 'test'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String)


test = Test(id=uuid.uuid4(), name=1)
```

Mypy still shows `Success: no issues found in 1 source file`

Maybe this is just not supported?

**Comment by CaselIT** [comment]
I mentioned it above:

> Also note that the init is not automatically generated, but you can use MappedAsDataclass to generate dataclasses automatically

by automatically generated I mean that a generic `__init__(self, **kwargs:Any)`` is used. If you want the init to be generated look at the dataclasses integration https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#orm-declarative-native-dataclasses

**Comment by zzzeek** [comment]
i dont see action to take here, reopen if im missing something
