### ISSUE TITLE
Microsoft SQL Server miscompilation for ROWS PRECEDING/FOLLOWING

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11514]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11513

<div type='discussions-op-text'>

<sup>Originally posted by **suhas-dc** June 19, 2024</sup>
On Microsoft SQL Server running a query with an OVER clause containing a row range fails. For example,

```
query = sa.select(sa.func.avg(col_one).over(order_by=[col_two], rows=(-5,1)))
connection.execute(query)
```

fails with `ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '@P1'. (102) (SQLExecDirectW)")`.

The sqlalchemy query object is compiled into some thing similar to
```
SELECT avg(anon_1.[col_one]) OVER (ORDER BY anon_1.[col_two] ASC ROWS BETWEEN 
? PRECEDING AND ? FOLLOWING)
FROM dbo.table AS anon_1'''
```

And, pyodbc does not seem to support bind parameters for PRECEDING and FOLLOWING since running the above query as textual SQL will also fail with the same error. Compiling the query with `literal_binds` `True` substitutes the bind parameters giving a query pyodbc will run.

EDIT: I faced this issues on sqlalchemy 1.4 but it seems to me that the issue may also exist on sqlalchemy 2.0 after looking through the `visit_over` definition.
</div>

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use literal execute for SQL Server frame parameters** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5348

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**use literal execute for SQL Server frame parameters** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5349

**Comment by suhas-dc** [comment]
Will the fix for this issue be backported to sqlalchemy 1.4?

**Comment by zzzeek** [comment]
we normally wouldn't backport this as we are hardly doing 1.4 releases anymore in any case, but this might be a pretty straight backport

**Comment by CaselIT** [comment]
I don't think this is a good target for backport to 1.4 since you can easily use the workaround you mentioned at https://github.com/sqlalchemy/sqlalchemy/discussions/11513#discussioncomment-9818924

**Comment by zzzeek** [comment]
> I don't think this is a good target for backport to 1.4 since you can easily use the workaround you mentioned at [#11513 (reply in thread)](https://github.com/sqlalchemy/sqlalchemy/discussions/11513#discussioncomment-9818924)

that workaround is only for compilation, it's not going to work with a regular statement execution

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**use literal execute for SQL Server frame parameters** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5359
