### ISSUE TITLE
Can not load SqlAlchemy Metadata pickle file if contains enum from abstract model

### ISSUE THREAD

**Issue by notatallshaw-gts** [sqlalchemy/sqlalchemy#11530]
### Describe the bug

This is a follow up to https://github.com/sqlalchemy/sqlalchemy/discussions/11360 and https://github.com/sqlalchemy/sqlalchemy/issues/11365

While in 2.0.31 you can successfully dump the pickle file, I find that you can not load it in a fresh Python process. I think my steps to reproduce are obvious enough and clear enough that this should be a bug report, not a discussion, but sorry if I missed something and I'm just doing it wrong.

### SQLAlchemy Version in Use

2.0.31

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.11.2

### Operating system

Linux

### To Reproduce

Steps to reproduce:

1. Run this script:

```python
import pickle
import sqlalchemy as sa
from sqlalchemy.orm.decl_api import declarative_base

base = declarative_base()
sa_metadata = base.metadata

class _Foo(base):
    __abstract__ = True
    __tablename__ = "foo"
    id_ = sa.Column(sa.Integer(), primary_key=True)
    column1 = sa.Column(sa.Enum("red", "green", name="column1"))

class Foo(_Foo):
    pass

with open("test.pkl", "wb") as f:
    pickle.dump(sa_metadata, f)
```

2. In a separate process run:

```python
import pickle

with open("test.pkl", "rb") as f:
    pickle.load(f)
```

### Error

```
Traceback (most recent call last):
  File "test_pickle_load.py", line 4, in <module>
    pickle.load(f)
AttributeError: Can't get attribute 'JoinedDDLEventsDispatch' on <module 'sqlalchemy.event.base' from '.../python3.11/site-packages/sqlalchemy/event/base.py'>
```

**Comment by zzzeek** [comment]
you can work around like this:

```py
import pickle
from sqlalchemy import Enum
Enum("a", "b", "c").copy()

with open("test.pkl", "rb") as f:
    pickle.load(f)
```

**Comment by notatallshaw-gts** [comment]
> ```python
> from sqlalchemy import Enum
> Enum("a", "b", "c").copy()
> ```

Confirmed, works for me, thanks for the quick response.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**create JoinedDispatcher subclasses up front** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5383

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**create JoinedDispatcher subclasses up front** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5384
