### ISSUE TITLE
Support INTERSECT DISTINCT, EXCEPT DISTINCT, and UNION DISTINCT

### ISSUE THREAD

**Issue by gallodustin** [sqlalchemy/sqlalchemy#11545]
### Describe the use case

Some dialects such as MySQL and BigQuery use the syntax of INTERSECT DISTINCT rather than just INTERSECT, like many other dialects use. Although this can be patched in the compiler class of that particular dialect, it would be nice if the main SA repo included this syntax since it applies to multiple different DBs.

### Databases / Backends / Drivers targeted

MySQL, BigQuery, likely others too.

### Example Use

```sql
SELECT employee_id FROM dataset.employees
INTERSECT DISTINCT
SELECT manager_id FROM dataset.managers;
```

### Additional context

Example impact in the bigquery-sqlalchemy repo: https://github.com/googleapis/python-bigquery-sqlalchemy/issues/388

**Comment by CaselIT** [comment]
Hi,

This is already customizable by 3rd party dialects very easily, so I think there is nothing else to do here.

A 3rd party dialed in almost all cases defines a custom subclass of the SQLCompiler and is free to override the dict https://github.com/sqlalchemy/sqlalchemy/blob/fc2cb4496d35c0b8bb7d59aa74b553f07210eded/lib/sqlalchemy/sql/compiler.py#L339-L346 that is set assigned to the compiler class here https://github.com/sqlalchemy/sqlalchemy/blob/fc2cb4496d35c0b8bb7d59aa74b553f07210eded/lib/sqlalchemy/sql/compiler.py#L1092

**Comment by zzzeek** [comment]
but how does someone tell the API to do "INTERSECT DISTINCT"?  We have explicit methods for these, like select().intersect().   This would imply new methods like intersect_distinct() (but only if this is SQL standard)

**Comment by zzzeek** [comment]
it looks like this is the only syntax for BigQuery, so in that case, they just render this syntax instead, so no API change there.  

for MySQL, DISTINCT is the default anyway: https://dev.mysql.com/doc/refman/8.4/en/intersect.html  "As with [UNION](https://dev.mysql.com/doc/refman/8.4/en/union.html) and [EXCEPT](https://dev.mysql.com/doc/refman/8.4/en/except.html), if neither DISTINCT nor ALL is specified, the default is DISTINCT."

because what else would there be if you didnt indicate ALL.

so there's no distinguishing API here, this is just how bigquery compiler should be rendering which I think it already does so that's that.

**Comment by CaselIT** [comment]
that's my understanding as well. No dialect does something different when using `intersect` vs `intersect distinct`. They either support only one of them or they support both and are synonyms

**Comment by gallodustin** [comment]
> so there's no distinguishing API here, this is just how bigquery compiler should be rendering which I think it already does so that's that.

FYI, the BQ compiler is not doing this yet, see the issue on their repo I linked in the original post.

> but how does someone tell the API to do "INTERSECT DISTINCT"? We have explicit methods for these, like select().intersect(). This would imply new methods like intersect_distinct() (but only if this is SQL standard)

New methods such as this are exactly what I'm requesting, yes. But if BQ is truly the only example (maybe there are more, but I haven't found any), I can agree with expecting them to handle it in their own compiler instead.

**Comment by zzzeek** [comment]
what does INTERSECT DISTINCT do that is different from "INTERSECT" and "INTERSECT ALL" ?

**Comment by gallodustin** [comment]
By my understanding, INTERSECT DISTINCT in BQ is equivalent to INTERSECT in other DBs ([Postgres](https://www.postgresql.org/docs/current/queries-union.html#QUERIES-UNION) for example is explicit that INTERSECT will remove duplicates), while INTERSECT ALL is not currently supported in BQ.

The only issue is getting SA to generate a query that includes the INTERSECT DISTINCT syntax. Which, as @CaselIT suggested, can alternatively be handled in the BQ compiler.

**Comment by zzzeek** [comment]
as long as INTERSECT and INTERSECT DISTINCT mean the same thing there is no need to add public methods to SQLAlchemy (where we are talking about `select().intersect_distinct()`, `select().union_distinct()` etc.

**Comment by CaselIT** [comment]
> The only issue is getting SA to generate a query that includes the INTERSECT DISTINCT syntax. Which, as @CaselIT suggested, can alternatively be handled in the BQ compiler.

that's the kind of changes that are expected to be handled by a dialect.
