### ISSUE TITLE
Support tcp keepalive for postgresql

### ISSUE THREAD

**Issue by NiuBlibing** [sqlalchemy/sqlalchemy#11551]
### Describe the use case

When postgresql is behind a loadbalancer or nat, it need a tcp keepalive to keep the connection.

### Databases / Backends / Drivers targeted

postgresql

### Example Use

set tcpkeepalive when init.

**Comment by CaselIT** [comment]
Hi

This is a driver feature, so you would have to look at how to do that in the driver you are using and configure it correctly.
If it's a parameter to pass in the connect call you can pass it here https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine.params.connect_args
