### ISSUE TITLE
TypeError when calling .one() on an AppenderQuery from instance not in session

### ISSUE THREAD

**Issue by clj** [sqlalchemy/sqlalchemy#11562]
### Describe the bug

The behaviour of calling `.one()` on an AppenderQuery differs on whether the instance is in the session or not when using SQLAlchemy 1.4 and 2.0, but not 1.3. When the instance is not in the session, I expect a result or a `NoResultFound` exception as I get in 1.3, but in 1.4 and 2.0 I instead get a `TypeError: 'OrderedIdentitySet' object is not an iterator`.

### SQLAlchemy Version in Use

1.4.52, 2.0.31

### DBAPI (i.e. the database driver)

pysqlite, pymysql

### Database Vendor and Major Version

SQLite, MySQL 8

### Python Version

3.8.18

### Operating system

OSX

### To Reproduce

```python
from sqlalchemy import *
from sqlalchemy.orm import *
try:
    from sqlalchemy.orm import declarative_base
except ImportError:
    from sqlalchemy.ext.declarative import declarative_base

Session = sessionmaker()
engine = create_engine("sqlite:///:memory:")
Base = declarative_base()


class User(Base):
    __tablename__ = "user"

    id = Column(Integer, primary_key=True)


class Address(Base):
    __tablename__ = "address"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("user.id"), nullable=False)

    user = relationship(User, backref=backref("addresses", lazy="dynamic"))


connection = engine.connect()
with connection.begin():
    Base.metadata.create_all(connection)
session = Session(bind=connection)
user = User()
#session.add(user)
user.addresses.one()
```

### Error

```
Traceback (most recent call last):
  File "minimal.py", line 34, in <module>
    user.addresses.one()
  File ".../lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2778, in one
    return self._iter().one()  # type: ignore
  File ".../lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1810, in one
    return self._only_one_row(
  File ".../lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 749, in _only_one_row
    row: Optional[_InterimRowType[Any]] = onerow(hard_close=True)
  File ".../lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1673, in _fetchone_impl
    return self._real_result._fetchone_impl(hard_close=hard_close)
  File ".../lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 2259, in _fetchone_impl
    row = next(self.iterator, _NO_ROW)
TypeError: 'OrderedIdentitySet' object is not an iterator
``` 

### Additional context

I'm seeing this error as part of an in-progress migration from 1.4 to 2.0, where the existing application tests occasionally  
calls `.one()` on `AppenderQuery` to perform assertions on instances that are known to be present.

The actual code path that triggers this looks something like this:
```
# Test code
user = User()
session.add(user)
session.flush()
# Application code
session.rollback()  # an application exception causes a rollback
# Test code
user.addresses.one()   # expecting a NoResultFound error
```
In the application code, if no exception is thrown, a `session.commit()` is executed instead of a  `session.rollback()`, and the behaviour is again as expected: `NoResultFound` (or if there actually is a result, then the result is returned).

Behaviour for the various SQLAlchemy versions I have been using:
```
        in session     not in session
SA13:  NoResultFound    NoResultFound
SA14:  NoResultFound    TypeError
SA20:  NoResultFound    TypeError
```

Thanks for a fantastic library.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**call iter() on detached/transient dynamic session** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5391

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**call iter() on detached/transient dynamic session** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5392

**Comment by zzzeek** [comment]
thanks for reporting

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**call iter() on detached/transient dynamic session** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5393
