### ISSUE TITLE
func.lag() on datetime returns str when using SQLite

### ISSUE THREAD

**Issue by mrh1997** [sqlalchemy/sqlalchemy#11578]
### Describe the bug

When creating a `select` with a lag function on a `datetime` it returns a the resulting column as `str`.
This behaviour is only reproducable on SQLite and only when using the lag function and when the column is of type datetime.
When using i.e.  `postgres` or the `max` function everything works as expected (aka the result is of type datetime)

### SQLAlchemy Version in Use

2.0.25

### DBAPI (i.e. the database driver)

SQLite

### Database Vendor and Major Version

2.6.0

### Python Version

3.11

### Operating system

Windows 11 (64bit)

### To Reproduce

```python
from sqlalchemy import create_engine, select, func, Table, Column, MetaData, DateTime, Integer, insert
from datetime import datetime

metadata = MetaData()
TestTable = Table('TestTable', metadata,
              Column('primary', Integer(), primary_key=True),
              Column('column', DateTime(), nullable=False),
              Column('over', Integer()),
              )
engine = create_engine("sqlite:///:memory:")
metadata.create_all(engine)

with engine.connect() as sess:
    sess.execute(insert(TestTable).values(primary=1, column=datetime.now(), over=1))
    sess.execute(insert(TestTable).values(primary=2, column=datetime.now(), over=1))

    lagfunc = func.lag(TestTable.c.column).over(partition_by=TestTable.c.over)
    result = sess.execute(select(lagfunc)).all()
    print(result)   # <- here a string is returned !!!
```

### Error

No stacktrace. But in the output you can see that a string instead of datetime object is outputted

**Comment by zzzeek** [comment]
hi -

[functions have datatypes which you must specify explicitly in most cases](https://docs.sqlalchemy.org/en/20/tutorial/data_select.html#functions-have-return-types) (link is from the SQLAlchemy tutorial, I would recommend reading the whole thing)

that is

```
    lagfunc = func.lag(TestTable.c.column, type_=DateTime).over(partition_by=TestTable.c.over)
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure intro to "functions have types" is not misleading** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5397

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**ensure intro to "functions have types" is not misleading** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5398

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**ensure intro to "functions have types" is not misleading** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5399

**Comment by zzzeek** [comment]
adding some clarification to that section to prevent it from being misleading
