### ISSUE TITLE
allow "name" with flat=True

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11575]
use case allows for this:

```py
    def test_aliased_joined_entities(self, named, flat):
        Company = self.classes.Company
        Engineer = self.classes.Engineer

        e1 = aliased(Engineer, flat=flat, name="myengineer")
```

aliases would be named `<prefix>_<tablename>`

**Comment by zzzeek** [comment]
this is taken from discussion at #5262

**Comment by sqla-tester** [comment]
**Eric Atkin** has proposed a fix for this issue in the **main** branch:

**Allow flat for join with name** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5411

**Comment by sqla-tester** [comment]
**Eric Atkin** has proposed a fix for this issue in the **rel_2_0** branch:

**Allow flat for join with name** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5403
