### ISSUE TITLE
AssociationProxy.any does not exist (but AssociationProxyInstance.any does)

### ISSUE THREAD

**Issue by tamird** [sqlalchemy/sqlalchemy#11614]
### Describe the use case

There's no analogue of [RelationshipProperty.any](https://github.com/sqlalchemy/sqlalchemy/blob/e44e805506fa71318e23a2bfad733fbbf5a9ee59/lib/sqlalchemy/orm/relationships.py#L908) on [AssociationProxy](https://github.com/sqlalchemy/sqlalchemy/blob/e44e805506fa71318e23a2bfad733fbbf5a9ee59/lib/sqlalchemy/ext/associationproxy.py#L342)  - though there [AssociationProxyInstance.any](https://github.com/sqlalchemy/sqlalchemy/blob/e44e805506fa71318e23a2bfad733fbbf5a9ee59/lib/sqlalchemy/ext/associationproxy.py#L1059).

### Databases / Backends / Drivers targeted

N/A

### Example Use

Clarifying: this comes up when I try to define a `column_property` using the relationship proxy.

```python
class MyModel:
  foo: Mapped[list[Foo]] = relationship()
  bar: AssociationProxy[list[Bar]] = association_proxy("foo", "bar")
  
  has_bars: Mapped[bool] = column_property(bar.any())
```

**Comment by zzzeek** [comment]
hi - 

this is not possible.   in this context, "bar" is an AssociationProxy object that has no link to any class, and no expression can be produced.

**Comment by zzzeek** [comment]
Here's a demonstration of the architecture

```py
class MyRelationship:
    def any(self):
        return "any!"

class MyDescriptor:
    def __init__(self, attr):
        self.attr = attr

    def __get__(self, instance, cls):
        if instance is not None:
            return getattr(instance, self.attr)
        elif cls is not None:
            return getattr(cls, self.attr)
        else:
            raise Exception("no instance or class is present")

    def any(self):
        # what do we call here?
        raise Exception("How to call any() here?")

class MyClass:

    foo = MyRelationship()

    bar = MyDescriptor("foo")


assert MyClass().bar.any() == "any!"
assert MyClass.bar.any() == "any!"



class MyOtherClass:
    foo = MyRelationship()

    bar = MyDescriptor("foo")

    # requested use case
    bat = bar.any()
```

you can see there's nothing to be called by an any() method.    I would add this column_property() after the fact (We dont currently support lambda configuration for column_property() either, there should be an issue for that somewhere but there's no easy solution to that one for other reasons)

**Comment by CaselIT** [comment]
> We dont currently support lambda configuration for column_property() either, there should be an issue for that somewhere but there's no easy solution to that one for other reasons

it's #6120
