### ISSUE TITLE
Implicit type conversion for asyncpg

### ISSUE THREAD

**Issue by riwu** [sqlalchemy/sqlalchemy#11636]
### Describe the use case

With the `psycopg` driver, I can insert `'1 min'` to an `Interval` column and it will implicitly convert it to a `timedelta` object accordingly. 

However, with the `asyncpg` driver, it throws this error:
```sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $9: '1 min' ('str' object has no attribute 'days')```

Can SQLAlchemy perform the implicit conversion so that any code will be compatible with both `psycopg` and `asyncpg` drivers?

### Databases / Backends / Drivers targeted

Postgresql, asyncpg

### Example Use

```
class Table(Base):
    __tablename__ = 'table'
    interval: Mapped[timedelta]

session.add(Table(interval='1 min'))
```

**Comment by CaselIT** [comment]
Hi

Is that psycopg2 or the newer version 3?
Usually sqlalchemy will not do type conversion, it will at most automatically render a cast (not sure if it's happening here).

Can you provide the output logs with echo=True?

**Comment by riwu** [comment]
Sorry some corrections:  
SQLAlchemy is not doing a type conversion/cast.  
Postgresql accepts "1 min" as a value for an Interval column.

So the problem is: asyncpg is not accepting str as an Interval value even though postgresql supports it.

Should I raise the issue with asyncpg, or should SQLAlchemy perform an implicit type conversion so that it works with asyncpg?

**Comment by CaselIT** [comment]
The statement run in the db will be `INSERT INTO t (data) VALUES ($1::INTERVAL) RETURNING t.id`.
You may need to use `type_coerce('1 min', sa.Text)` to avoid rendering the cast there and let postgresql figure it out.

In any case I think it's just how asyncpg behaves
