### ISSUE TITLE
Expand Default Value Constraint Support

### ISSUE THREAD

**Issue by fruitymedley** [sqlalchemy/sqlalchemy#11644]
### Describe the use case

SQL allows the creation of default value constraints during column creation via the syntax[^1]
```SQL
CREATE TABLE Person (
    ID int NOT NULL,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int,
    City varchar(255) DEFAULT 'Sandnes'
); 
```
which is currently well supported within SQLalchemy.

Several flavors of SQL also allow for the adding of a default value constraint outside of column creation via the syntax[^1]
```SQL
ALTER TABLE Person
ALTER City SET DEFAULT 'Sandnes'; 
```
which is not currently supported within SQLalchemy.

SQL Server in particular also supports the ability to name default constraints via the syntax[^1]
```SQL
ALTER TABLE Person
ADD CONSTRAINT df_City
DEFAULT 'Sandnes' FOR City; 
```
which is not currently supported within SQLalchemy.

I propose to add support for both creating default value constraints separate from creating a column (for dialects which support it) as well as allowing for naming default value constraints (in SQL Server).

[^1]: [w3schools](https://www.w3schools.com/sql/sql_default.asp)

### Creation of Default Value Constraints

- MySQL
- SQL Server
- MS Access
- Oracle:

### Naming of Default Value Constraints

- SQL Server

### Base Case (existing)

The following SQL statement
```SQL
CREATE TABLE Person (
    --    other columns
    City varchar(255) DEFAULT 'Sandnes'
); 
```
has the corresponding SQLalchemy definition
```python3
Table(
    "Person",
    ...
    Column("City", String(255), default_value="Sandnes"),
)
```

SQLalchemy also supports ad-hoc creation of primary key constraints through the syntax
```python3
PrimaryKeyConstraint("id", name="PK_Table"),
```

SQLalchemy further supports naming conventions for constraints through the syntax[^1]
```python3
convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata_obj = MetaData(naming_convention=convention)
```

I therefore propose the creation of an class `DefaultValueConstraint` of the form
```python3
class DefaultValueConstraint:
    __init__(self, column, server_default, name=None): # Name is optional and only used in SQL Server
        ...
```
with usage
```python3
Table(
    "Person"
    ...
    Column("City", String(255)),
    DefaultValueConstraint("City", "'Sandnes'", "df_Person_City"),
)
```

I further propose extending functionality of `MetaData.naming_convention` to include support of default value constraint names, such that
```python3
convention = {
    ...
    "df": "df_%(table_name)s_%(column_0_name)s"
}

metadata_obj = MetaData(naming_convention=convention)
```
would automatically name default value constraints either specified through `server_default` or `DefaultValueConstraint`.
```python3
Table(
    "Person"
    ...
    Column("City", String(255)),
    DefaultValueConstraint("City", "'Sandnes'"), # -> yields "df_Person_City"
)
```

[^1]: [SQLalchemy docs](https://docs.sqlalchemy.org/en/20/core/constraints.html#configuring-constraint-naming-conventions)

### Additional context

N/A

**Comment by CaselIT** [comment]
Hi,

The alter syntax is implemented in alembic.
`DefaultValueConstraint` is something that could be added, but I'm not sure how useful it would be.

**Comment by zzzeek** [comment]
there's no immediate need for a DefaultValueConstraint in SQLAlchemy since SQLAlchemy does not support ALTER.  for ALTER compilation directives, please see [alembic](https://alembic.sqlalchemy.org/)
