### ISSUE TITLE
Improve bitwise operator support

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#11663]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11621

<div type='discussions-op-text'>

<sup>Originally posted by **nmoreaud** July 19, 2024</sup>
Hello

Do you know if bit operators are working fine with Oracle?
I have encountered an error: `ORA-00920: invalid relational operator\nHelp: https://docs.oracle.com/error-help/db/ora-00920/"`
In the logs, I see that the operator has been replaced in the query by `&`, which is not supported by my database (`bitand` is the right syntax).

```python
# SQLAlchemy==2.0.28
# CREATE TABLE ... (
# "UNIX_RIGHTS" NUMBER(3,0) DEFAULT 1, 
# )
# unixrights= Column(SmallInteger, default=1)
unixrights= mapped_column('unixrights', SmallInteger, nullable=True, default=1)
filter = or_(User.unixrights.bitwise_and(1) != 0, User.unixrights.bitwise_and(2) != 0)
```</div>

**Comment by CaselIT** [comment]
We could probably add a test to the suite

**Comment by zzzeek** [comment]
it should be a suite test for bitwise on all backends, surprised we dont have that

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fixed compilation of bitwise operators on oracle and sqlite.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5419

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Fixed compilation of bitwise operators on oracle and sqlite.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5420
