### ISSUE TITLE
Async oracledb execute unexpected behaviour

### ISSUE THREAD

**Issue by Rollmops** [sqlalchemy/sqlalchemy#11669]
### Describe the bug

I am trying to use the `oracledb` library with the `AsyncConnection` and it seems, the `execute` statement is fetching the entire table. At least it takes a very long time until the `execute` statement is finished.
The sync implementation works as expected.

### SQLAlchemy Version in Use

2.0.31

### DBAPI (i.e. the database driver)

oracledb (2.3.0)

### Database Vendor and Major Version

Oracle 19.3.0.9

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
import asyncio

import oracledb

oracledb.init_oracle_client()

from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy import text


user = ""
password = ""
host = ""
port = ""
sid = ""

async def async_main():
    connect_string = f"oracle+oracledb://{user}:{password}@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST={host})(PORT={port}))(CONNECT_DATA=(SID={sid})))"
    engine = create_async_engine(connect_string)

    async with engine.begin() as conn:
        result = await conn.execute(text("SELECT * FROM TABLE_WITH_MANY_ROWS"))

    print(result.first())


if __name__ in {"__main__", "__mp_main__"}:
    asyncio.run(async_main())
```

### Error

There is no error message, only a vastly different runtime compared to the sync implementation.

**Comment by CaselIT** [comment]
Hi,

That's expected, since the normal result cannot fetch additional rows with async.
Use https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#sqlalchemy.ext.asyncio.AsyncConnection.stream to have an async result that's able to fetch rows as needed

**Comment by Rollmops** [comment]
Ok, thanks, I tried this. But unfortunately streams are not yet supported by `oracledb`.

**Comment by CaselIT** [comment]
oh right, forgot about it. It's tracked by https://github.com/sqlalchemy/sqlalchemy/issues/10820

In the meantime I think you can use yield_per https://docs.sqlalchemy.org/en/20/orm/queryguide/api.html#orm-queryguide-yield-per. But I'm not 100% sure it support async out of the box
