### ISSUE TITLE
Reflection caching is not handling quoted_name instances correctly

### ISSUE THREAD

**Issue by Masterchen09** [sqlalchemy/sqlalchemy#11687]
### Describe the bug

I have already prepared a pull request for it, but the pull request template says I should create an issue first...and here we are...

I have noticed this issue when playing around with some toy examples in context of the SAP HANA dialect (https://github.com/SAP/sqlalchemy-hana), but technically it affects all dialects which require name normalization (i.e. also the built-in Oracle dialect).

When names (schema, tables, ...) are returned by the reflection methods of a dialect which requires name normalization the names are typically normalized in a way that for example uppercase names in the database are represented in lowercase in SQLAlchemy. When using these names again in a query the names have to be denormalized again. To distinguish between normalized lowercase names (i.e. names which appear in uppercase in the database) and non-normalized lowercase names (i.e. names which appear in lowercase in the database) during denormalization the quoted_name class resp. an instance of the class is used for the non-normalized names. This class inherits from str and is acting the same as a str except, that it has a quote property and that the upper and lower method are working differently based on the value of this property.

https://github.com/sqlalchemy/sqlalchemy/blob/bae75fe92f9636bafb75461ff0bc556432831e30/lib/sqlalchemy/sql/elements.py#L5190-L5284

This quoted_name class is problematic in context of reflection caching: The reflection caching mechanism is using a dictionary for storing the return values of the different reflection methods - for the key of this dictionary among other thing the input parameters are used (e.g., the get_table_names method is using the schema name, which could either be a str or a quoted_name instance e.g. returned by the get_schema_names method).

https://github.com/sqlalchemy/sqlalchemy/blob/bae75fe92f9636bafb75461ff0bc556432831e30/lib/sqlalchemy/engine/reflection.py#L78-L99

As the quoted_name class is not overriding the \_\_hash\_\_ and \_\_equals\_\_ methods of the str class the following instances are treated the same when caching, although they might not represent the same name:

```python
"name" == quoted_name("name", quoted=True) == quoted_name("name", quoted=False)
```

As these names are currently treated the same, you could get a cached result for the wrong object from the reflection methods.

To solve this issue you would typically implement the \_\_hash\_\_ and \_\_equals\_\_ methods...however this would break the existing logic regarding the denormalization: The denormalize_name methods of the dialects are typically using the transformed lowercase and/or uppercase value of a name and compare it to the provided name (str or quoted_name) to decide whether a name has to be denormalized or not:

https://github.com/sqlalchemy/sqlalchemy/blob/bae75fe92f9636bafb75461ff0bc556432831e30/lib/sqlalchemy/engine/default.py#L1038-L1053

Or in the SAP HANA dialect: https://github.com/SAP/sqlalchemy-hana/blob/38fdc7667870db8052083dd457575ea4e796cdfb/sqlalchemy_hana/dialect.py#L684-L692

My proposed fix is to handle quoted_name instances within the reflection cache decorator differently than str instances - this would not solve issue in cases where the default cache decorator of Python (https://docs.python.org/3/library/functools.html#functools.cache) is used together with quoted_name instances, but it would solve cases where the quoted_name instances typically are used: Within the reflection methods of SQLAlchemy and where reflection caching is used...

For the details of the proposed fix, please see the PR which I will create after creating this issue.

The impact of this issue is rather limited: Real problems can only occur in case in a database two objects with the same name with different casing are existing and which are requested after each other (e.g., using get_table_names for two schemas with the same name). I found this issue only because I tried to understand how the normalization and denormalization are working and I created some toy examples...usually you wound not have the same object twice with the same name, but different casing...

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

n/a

### SQLAlchemy Version in Use

2.0.31

### DBAPI (i.e. the database driver)

hdbcli

### Database Vendor and Major Version

SAP HANA Cloud

### Python Version

3.10

### Operating system

Windows

### To Reproduce

```python
def test_reflection_cache(self, connection):
    # dummy method which mimics a reflection method of the
    # dialect (e.g., get_schema_names)
    @cache
    def get_cached_name(self, connection, name, **kw):
        return name

    dialect = connection.dialect
    info_cache = {}

    # first test a string
    n1 = get_cached_name(
        dialect, connection, "name", info_cache=info_cache
    )

    assert isinstance(n1, str) and not isinstance(n1, quoted_name)
    assert n1 == "name"
    assert not hasattr(n1, "quote")

    # a single value should be cached
    assert len(info_cache) == 1
    assert any(True for n in info_cache.values() if n == "name" and not hasattr(n, "quote"))
    assert not any(True for n in info_cache.values() if n == "name" and hasattr(n, "quote") and getattr(n, "quote"))

    # test a quoted_name instance, which is inherited from string
    n2 = get_cached_name(
        dialect,
        connection,
        quoted_name("name", quote=True),
        info_cache=info_cache,
    )

    assert isinstance(n2, str) and isinstance(n2, quoted_name)
    assert n2 == "name"
    assert hasattr(n2, "quote")
    assert getattr(n2, "quote") == True

    # two values should be cached
    assert len(info_cache) == 2
    assert any(True for n in info_cache.values() if n == "name" and not hasattr(n, "quote"))
    assert any(True for n in info_cache.values() if n == "name" and hasattr(n, "quote") and getattr(n, "quote"))

    # test the string again
    n3 = get_cached_name(
        dialect, connection, "name", info_cache=info_cache
    )

    assert isinstance(n3, str) and not isinstance(n3, quoted_name)
    assert n3 == "name"
    assert not hasattr(n3, "quote")

    # still only two values should be cached
    assert len(info_cache) == 2
    assert any(True for n in info_cache.values() if n == "name" and not hasattr(n, "quote"))
    assert any(True for n in info_cache.values() if n == "name" and hasattr(n, "quote") and getattr(n, "quote"))

    # clear the cache
    info_cache = {}

    # test the quoted_name instance first
    n4 = get_cached_name(
        dialect,
        connection,
        quoted_name("name", quote=True),
        info_cache=info_cache,
    )

    assert isinstance(n4, str) and isinstance(n4, quoted_name)
    assert n4 == "name"
    assert hasattr(n4, "quote")
    assert getattr(n4, "quote") == True

    # a single value should be cached
    assert len(info_cache) == 1
    assert not any(True for n in info_cache.values() if n == "name" and not hasattr(n, "quote"))
    assert any(True for n in info_cache.values() if n == "name" and hasattr(n, "quote") and getattr(n, "quote"))

    # test the string
    n5 = get_cached_name(
        dialect, connection, "name", info_cache=info_cache
    )

    assert isinstance(n5, str) and not isinstance(n5, quoted_name)
    assert n5 == "name"
    assert not hasattr(n5, "quote")

    # two values should be cached
    assert len(info_cache) == 2
    assert any(True for n in info_cache.values() if n == "name" and not hasattr(n, "quote"))
    assert any(True for n in info_cache.values() if n == "name" and hasattr(n, "quote") and getattr(n, "quote"))

    # test the quoted_name instance again
    n6 = get_cached_name(
        dialect,
        connection,
        quoted_name("name", quote=True),
        info_cache=info_cache,
    )

    assert isinstance(n6, str) and isinstance(n6, quoted_name)
    assert n6 == "name"
    assert hasattr(n6, "quote")
    assert getattr(n6, "quote") == True

    # still only two values should be cached
    assert len(info_cache) == 2
    assert any(True for n in info_cache.values() if n == "name" and not hasattr(n, "quote"))
    assert any(True for n in info_cache.values() if n == "name" and hasattr(n, "quote") and getattr(n, "quote"))
```

### Error

n/a

**Comment by sqla-tester** [comment]
**Masterchen09** has proposed a fix for this issue in the **main** branch:

**handle quoted_name instances separately in engine.reflection.cache** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5443
