### ISSUE TITLE
Support postgres:// URL 

### ISSUE THREAD

**Issue by ryantm** [sqlalchemy/sqlalchemy#11705]
### Describe the use case

* According to
https://www.prisma.io/dataguide/postgresql/short-guides/connection-uris?query=&page=1
a postgres URL can have a schema of "postgres" or "postgresql".
* Users who have a URL starting with "postgres://" cannot use sqlalchemy without
URL pre-processing, because they will see this error:

```
  File "/home/runner/UserAuth/.pythonlibs/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
```
* Since postgres unambiguously means we want to use postgresql, we can
add a quick dialect alias to solve this UX problem

### Databases / Backends / Drivers targeted

postgresql

### Example Use

With SQLALCHEMY_DATABASE_URI = "postgres://example.com" sqlachemy should be able to connect read and write from the database.

**Comment by zzzeek** [comment]
hi please see #6083

**Comment by zzzeek** [comment]
noting such URLs are legacy as well as because they dont include a driver and the default driver psycopg2 is quite legacy, so you want

`postgresql+psycopg://...`


there is no portability from 3rd party systems with their own URL formats

**Comment by ryantm** [comment]
Thanks for the pointer and link to the issue!
