### ISSUE TITLE
with_statement_hint() has lost its generative capability

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11703]
regression somewhere in 2.0

```py
from sqlalchemy import select


s1 = select(1)
s2 = s1.with_statement_hint("foo")

assert s1 is not s2
```

**Comment by zzzeek** [comment]
broke in 3b4d62f4f72e8dfad7f38db192a6a

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**restore generative to with_statement_hint** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5461
