### ISSUE TITLE
Oracle with_hint and with_statement_hint bugs

### ISSUE THREAD

**Issue by mkmoisen** [sqlalchemy/sqlalchemy#11702]
### Describe the bug

The with_hint function takes a selectable as well as the hint.

```
with_hint(selectable: '_FromClauseArgument', text: 'str', dialect_name: 'str' = '*')
```

In Oracle, the `selectable` is not relevant, because all hints must be placed after the SELECT keyword:

```
SELECT /*+ USE_NL(second) */
```

If I pass in `None` for the selectable, SQLAlchemy will not compile the hint correctly with the Oracle style.

```
from sqlalchemy import table, column, select
from sqlalchemy.dialects import oracle

first = table('first', column('a'))
second = table('second', column('a'))

sel = select(first, second).select_from(first.join(second, first.c.a == second.c.a))

print(
    sel.with_hint(
        None, 'USE_NL(second)'
    ).compile(
        dialect=oracle.dialect()
    )
)
```
This outputs the following which is wrong for Oracle:

```
SELECT first.a, second.a AS a_1
FROM first JOIN second ON first.a = second.a USE_NL(second)
```

The solution to this is to just put any random selectable instead of `None`:

```
print(sel.with_hint(first, 'USE_NL(second)').compile(dialect=oracle.dialect()))
# or 
print(sel.with_hint(second, 'USE_NL(second)').compile(dialect=oracle.dialect()))
# or 
print(sel.with_hint(table('totally_irrelevant'), 'USE_NL(second)').compile(dialect=oracle.dialect()))
```

which outputs the correct:

```
SELECT /*+ USE_NL(second) */ first.a, second.a AS a_1
FROM first JOIN second ON first.a = second.a
```

However, I believe this is a bug because the `selectable` is meaningless for Oracle. I think it is confusing to have to put in a random selectable here. It would be better to allow `None`.

### SQLAlchemy Version in Use

2.0.32

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

Oracle

### Python Version

3.12.4

### Operating system

Linux and Windows

### To Reproduce

```python
from sqlalchemy import table, column, select
from sqlalchemy.dialects import oracle

first = table('first', column('a'))
second = table('second', column('a'))

sel = select(first, second).select_from(first.join(second, first.c.a == second.c.a))

print(
    sel.with_hint(
        None, 'USE_NL(second)'
    ).compile(
        dialect=oracle.dialect()
    )
)
```

### Error

```
SELECT first.a, second.a AS a_1
FROM first JOIN second ON first.a = second.a USE_NL(second)
```

**Comment by mkmoisen** [comment]
In addition, the `with_statement_hint` does not work with Oracle:

```
print(
    sel.with_statement_hint(
        'USE_NL(second)'
    ).compile(
        dialect=oracle.dialect()
    )
)
```

This outputs:

```
SELECT first.a, second.a AS a_1
FROM first JOIN second ON first.a = second.a USE_NL(second)
```

Moreover, the `with_statement_hint` actually modifies `sel` instead of returning a new sel.

We can see that if I just print out sel:

```
print(sel.compile(dialect=oracle.dialect()))
```

This outputs with the hint:

```
SELECT first.a, second.a AS a_1
FROM first JOIN second ON first.a = second.a USE_NL(second)
```

Shouldn't this return a new select instead of modifying the original select?

**Comment by zzzeek** [comment]
that's a table hint, you have a tablename there.  to format the tablename you [use the %(name)s token](https://docs.sqlalchemy.org/en/20/core/selectable.html#sqlalchemy.sql.expression.Select.with_hint):

```py
from sqlalchemy import table, column, select
from sqlalchemy.dialects import oracle

first = table('first', column('a'))
second = table('second', column('a'))

sel = select(first, second).select_from(first.join(second, first.c.a == second.c.a))

print(
    sel.with_hint(
        second, 'USE_NL(%(name)s)'
    ).compile(
        dialect=oracle.dialect()
    )
)
```

we dont yet have any "statement hint" concept for Oracle, just table hints right now

**Comment by zzzeek** [comment]
the with_statement_hint generative is a bug, need to see where that came from

**Comment by zzzeek** [comment]
with_statement_hint regression in #11703

**Comment by mkmoisen** [comment]
@zzzeek 

What about multi table hints?

For example:

/*+ LEADING(first second) USE_NL(second) */

In this case it seems to me that passing `None` in and typing both out manually would be better, compared to passing one in.

But passing `None` in results in SQLAlchemy ignoring the Oralce style hint:

```
SELECT first.a, second.a AS a_1
FROM first JOIN second ON first.a = second.a USE_NL(second)
```

See how the `USE_NL(second)` is put at the end of the statement, instead of after `SELECT` ?

**Comment by mkmoisen** [comment]
@zzzeek 

In addition there are many hints in Oracle that take no table name at all.

/*+ ORDERED */

/*+ CACHE */

/*+ RESULT_CACHE */

/*+ FIRST_ROWS */

/*+ ALL_ROWS */

etc.

**Comment by zzzeek** [comment]
Sure, we should add with_statement_hint() for all of these examples.  make a separate issue

**Comment by zzzeek** [comment]
requested that we have individual issues per specific thing.  with_statement_hint generative is #11703 .  new issue forthcoming to add with_statement_hint support to the oracle dialect

**Comment by zzzeek** [comment]
updated, we recommend prefix_with() for this use case right now including for MySQL
