### ISSUE TITLE
Permanently corrupted hybrid_property column labeling as a result of selecting column returned by hybrid_property.expression

### ISSUE THREAD

**Issue by tomas-sk** [sqlalchemy/sqlalchemy#11728]
### Describe the bug

The issue causes a select of `hybrid_property` to return its value under wrong label. The ORM model becomes "corrupted" by construction of a different specific select, selecting the column returned by `hybrid_property.expression`. The select causes memoization of `_proxy_key`, which is then incorrectly used as label of the column in the corrupted select.

`select(Model.id)` will return the `id` hybrid_property under `_id` key which is the name of the column returned by `hybrid_property.expression` of the `id` hybrid_property.

We have found this issue during migration of a large codebase from SQLAlchemy `1.3` to `1.4`, we will be thankful for a `1.4` fix.

### SQLAlchemy Version in Use

1.4.52, 2.0.32

### DBAPI (i.e. the database driver)

Any, psycopg2

### Database Vendor and Major Version

Any, PostgreSQL 15

### Python Version

3.11, Any

### Operating system

Windows, Any

### To Reproduce

```python
from sqlalchemy import Column, select
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Model(Base):
    __tablename__ = 'model'

    _id = Column(UUID(as_uuid=True), primary_key=True, nullable=False)

    @hybrid_property
    def id(self):
        return self._id

    @id.expression
    def id(cls):
        return cls._id


assert select(Model.id).subquery().c[0].key == 'id' and Model.id.expression._proxy_key == 'id'

assert select(Model._id).subquery().c[0].key == '_id'
# Creating above select causes the first select to fail when repeated.
# Selecting the underscored hybrid.expression's "target" Column causes
# memoization of `_proxy_key` in `Model._id.__clause_element__().__dict__`
# As a consequence column `id` is returned under name `_id` in the result rows
# instead of the expected `id`.
# Presence of the memoized `_proxy_key` in __dict__ causes it to be cloned
# in `sqlalchemy_sql_annotation_annotated._with_annotations`
# and it takes precedence when accessed via the Proxy class of hybrid property
# during select construction.

# The broken memoized state can be reverted by deleting memoized `_proxy_key` using following line
# del Model._id.__clause_element__().__dict__['_proxy_key']

assert (
    select(Model.id).subquery().c[0].key == 'id'
), "Resulting `id` column would be returned incorrectly under `_id` attribute/key."
assert Model.id.expression._proxy_key == 'id'
```

### Error

```
# No exceptions
```

**Comment by zzzeek** [comment]
hi - 

thanks for reporting.

this issue occurs deep in an extremely central set of methods that have wide reaching effects throughout the Core and ORM; these methods were carefully rewritten in the 1.4 series to suit the new column architectures and it took many months. 

it's not clear the extent to which the required changes would be backwards compatible as this was not really the primary intended use of a hybrid property (but certainly, this should work consistently.  it's not clear to me if there was ever a guarantee that the name of a hybrid expression in a result set would be named the same as the attribute but that seems to be current behavior).   so for the moment this is targeted at 2.1 and hopefully can be targeted at 2.0.  1.4 not the current release series so we aren't backporting new code issues (that is, issues that only show up when someone writes new code that never worked in 1.4).

I think in your case you should be using [synonym](https://docs.sqlalchemy.org/en/20/orm/mapped_attributes.html#sqlalchemy.orm.synonym) if want an attribute that's a total mirror of a column.


partial fix but not full looks like

```diff
diff --git a/lib/sqlalchemy/sql/selectable.py b/lib/sqlalchemy/sql/selectable.py
index 632e2e792..555c2b9a9 100644
--- a/lib/sqlalchemy/sql/selectable.py
+++ b/lib/sqlalchemy/sql/selectable.py
@@ -4626,12 +4626,12 @@ class SelectState(util.MemoizedSlots, CompileState):
                 assert is_column_element(c)
 
             if not dedupe:
-                name = c._proxy_key
+                name = col_name if col_name else c._proxy_key
                 if name is None:
                     name = "_no_label"
                 return name
 
-            name = c._tq_key_label if table_qualified else c._proxy_key
+            name = c._tq_key_label if table_qualified else col_name if col_name else c._proxy_key
 
             if name is None:
                 name = "_no_label"

```

this fixes the result set portion of it, tests seem to pass with this so will have to find some time to see how this didn't get tested already plus fix the `.c` case.

**Comment by zzzeek** [comment]
OK this is better, this is a memoization in the annotated that should fix this 

```diff
diff --git a/lib/sqlalchemy/sql/elements.py b/lib/sqlalchemy/sql/elements.py
index 64b686fc0..2b6835a6a 100644
--- a/lib/sqlalchemy/sql/elements.py
+++ b/lib/sqlalchemy/sql/elements.py
@@ -5347,7 +5347,14 @@ class AnnotatedColumnElement(Annotated):
 
     def _with_annotations(self, values):
         clone = super()._with_annotations(values)
-        clone.__dict__.pop("comparator", None)
+        for attr in (
+            "comparator",
+            "_proxy_key",
+            "_tq_key_label",
+            "_tq_label",
+            "_non_anon_label",
+        ):
+            clone.__dict__.pop(attr, None)
         return clone
 
     @util.memoized_property

```

**Comment by zzzeek** [comment]
this is safer to backport to 1.4 however we have no 1.4 release planned right now, we just had one and these are only every few months usually

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**de-memoize _proxy_key when new annotations are added** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5466

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**de-memoize _proxy_key when new annotations are added** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5467

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**de-memoize _proxy_key when new annotations are added** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5468

**Comment by zzzeek** [comment]
you really dug into exactly where it was happening which is definitely not common for an attribute mechanics issue, this is an area where things are extremely intricate and confusing.

the bug is of the nature of a missing de-memoization which is always a very safe kind of fix as opposed to a codepath that wasn't considered which is what I thought it was at first.     so I'll keep this ported to 1.4 but we want to be close to being done with 1.4 releases
