### ISSUE TITLE
Handle ORM compatible querying for non-session connections

### ISSUE THREAD

**Issue by chamini2** [sqlalchemy/sqlalchemy#11729]
### Describe the use case

We normally use Sessions for queries to our database, but we have a use case where we want to get every ms we can out of an operation. So I am trying to make the read only operations we do for auth of our users to not run in a transaction at all.

This works by using `AsyncConnection`, but I have to write a SQL query that is not compatible with the Session interface at all, and cannot load into a model object but have to build it manually.

Is there a way to make ORM models compatible queries without starting a transaction at all?

### Databases / Backends / Drivers targeted

postgres

### Example Use

```
conn = await rollback_session.connection()
model = await conn.get(UserModel, user_id)
```

### Additional context

There may be a way to avoid transactions already that I have missed. Maybe making a superclass of `AsyncSession`?

**Comment by CaselIT** [comment]
Hi,

This is already possible: https://docs.sqlalchemy.org/en/20/orm/session_transaction.html#setting-isolation-for-a-sessionmaker-engine-wide
