### ISSUE TITLE
Support empty connection string for postgresql+psycopg

### ISSUE THREAD

**Issue by stinovlas** [sqlalchemy/sqlalchemy#11758]
### Describe the use case

It's possible to specify empty connection string for `psycopg2` driver, which results in `pglib` reading connection details from env variables such as `PGHOST` and `PGUSER`. This is documented here:
https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#empty-dsn-connections-environment-variable-connections

However, the same is not possible for `psycopg` driver. The `psycopg >= 3` does support this and I think it could be supported in SQLAlchemy as well.

### Databases / Backends / Drivers targeted

Database: PostgreSQL
Driver: Psycopg (aka `psycopg3`)

### Example Use

```python
engine = create_engine("postgresql+psycopg://")
```

### Additional context

I could probably provide a PR, if requested.

**Comment by stinovlas** [comment]
Similar `psycopg2` changes have been discussed here: https://github.com/sqlalchemy/sqlalchemy/issues/4562

**Comment by CaselIT** [comment]
Hi,

The same logic used for psycopg2 is used for psycopg3, so it should work. Does it currently raises an error?

**Comment by zzzeek** [comment]
this is supported, no issue can be reproduced

```py
$ PGHOST=localhost PGUSER=scott PGPASSWORD=tiger PGDATABASE=test python
Python 3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red Hat 14.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlalchemy import create_engine
>>> engine = create_engine("postgresql+psycopg://")

# illustrate the arguments passed
>>> engine.dialect.create_connect_args(engine.url)
([''], {'context': <psycopg.adapt.AdaptersMap object at 0x7f59b805b5f0>})

# make an actual connection
>>> c = engine.connect()

# works fine
>>> c.exec_driver_sql("SELECT 1").all()
[(1,)]

```

**Comment by zzzeek** [comment]
no bug was reported here, so closing

**Comment by stinovlas** [comment]
I'm really sorry for wasting your time, I obviously did something wrong while testing this. I'll be more thorough next time.

**Comment by zzzeek** [comment]
there's no problem at all, we like to get issues closed in case the reporter disappears which happens often, then we have issues left open for months/ years
