### ISSUE TITLE
and_ only acceptiong Literal[True] instead of bool

### ISSUE THREAD

**Issue by enadeau** [sqlalchemy/sqlalchemy#11767]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

The and_ function accept a `Literal[True]` but not an arbitrary `bool`.

It seems to work to actually work and can sometime be useful to use the bool as a flag to turn on/off a condition

### To Reproduce

```python
import sqlalchemy as sa

from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "user_account"

    id: Mapped[int] = mapped_column(primary_key=True)
    group_id: Mapped[int]
    fullname: Mapped[str | None]


def user_filter(only_null_name: bool):
    return sa.and_(only_null_name, User.fullname.is_(None))
```

### Error

```
foo.py:21: error: Argument 1 to "and_" has incompatible type "bool"; expected "Literal[True] | ColumnElement[bool] | _HasClauseElement[bool] | SQLCoreOperations[bool] | ExpressionElementRole[bool] | TypedColumnsClauseRole[bool] | Callable[[], ColumnElement[bool]] | LambdaElement"  [arg-type]
``` 

### Versions

- OS: Ubuntu
- Python: 3.12.0
- SQLAlchemy: 2.0.32
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): 1.11.1

### Additional context

A simillar issue exists with the `or_` function

**Comment by zzzeek** [comment]
Hi -

SQLAlhcemy's `and_()` does not accept Python booleans, it accepts column expressions.

the correct typing for your code should use https://docs.sqlalchemy.org/en/20/core/sqlelement.html#sqlalchemy.sql.expression.SQLColumnExpression so that it would:

```py

from sqlalchemy import SQLColumnExpression

def user_filter(only_null_name: SQLColumnExpression[bool]) -> SQLColumnExpression[bool]:
    return sa.and_(only_null_name, User.fullname.is_(None))

```
