### ISSUE TITLE
Typing lost when using selectable.with_only_columns(x, maintain_column_froms=...)

### ISSUE THREAD

**Issue by rslinckx** [sqlalchemy/sqlalchemy#11782]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

As seen here: https://github.com/sqlalchemy/sqlalchemy/blob/663e6f1d60c99fa93da479b4f6f3b3c5e49cc2a8/lib/sqlalchemy/sql/selectable.py#L5917

there are several overload that are generated to keep typing information in presence of 1 to X parameters to with_only_columns. However the overloads do not contain the maintain_column_froms: bool argument, making the type checker (pyright in this case) choose the generic overload which results in a Select[Any] type, losing whatever argument type was given to with_only_columns.

I think the fix is that maintain_column_froms (and possibly other kwargs) should be added to the overloads so that they are picked up by the type-checker

### To Reproduce

```python
from sqlalchemy import select, sql

# Correct
s: Select[tuple[int]] = select(sql.literal(1))
# Also correct
s2: Select[tuple[bool]] = s.with_only_columns(sql.literal(True))
# Should be Select[tuple[bool]] like above
s3: Select[Any] = s.with_only_columns(sql.literal(True), maintain_column_froms=True)
```

### Versions

- OS: osx
- Python: 3.12
- SQLAlchemy: 2.0.32
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): pyright 1.1.372

**Comment by zzzeek** [comment]
if you can provide a fix that would expedite, thanks!

**Comment by rslinckx** [comment]
I suspect the fix should be made in this file: https://github.com/sqlalchemy/sqlalchemy/blob/main/tools/generate_tuple_map_overloads.py but it appears to differ from the 2.0.x releases, probably due to the Unpack thing coming up in master.

In the 2.0 branch: https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0/tools/generate_tuple_map_overloads.py it correctly shows the various __entX parameters however the tool apparently has no knowledge of the original overloaded function (apart from the name), and so can't include the extra kwargs automatically.

I must admit I'm not comfortable in modifying this code-generating code without any prior knowledge of the whole system, presumably either some ast parsing or regex capturing or augmenting the magic-comment string would be able to insert what's missing but 🤷🏿

**Comment by CaselIT** [comment]
the issue was actually that `sqlalchemy.sql.selectable` was not even run by the script. I've now make it fail if it missed an expected generation.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**fix select.with_only_columns type hints** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5452

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**fix select.with_only_columns type hints** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5453
