### ISSUE TITLE
schematype.metadata is not re-assigned on tometadata

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11802]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11798

```py
from sqlalchemy import Column
from sqlalchemy import Enum
from sqlalchemy import MetaData
from sqlalchemy import Table

metadata1 = MetaData()

my_table = Table(
    "my_table",
    metadata1,
    Column("x", Enum("a", "b", "c", metadata=metadata1)),
)

metadata2 = MetaData()
tt2 = my_table.to_metadata(metadata2)

assert my_table.c.x.type.metadata is metadata1
assert tt2.c.x.type.metadata is metadata2
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**pass to_metadata argument to Enum.copy()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5473

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**pass to_metadata argument to Enum.copy()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5474
