### ISSUE TITLE
Problem mixing lateral and nested CTE for Postgresql

### ISSUE THREAD

**Issue by odelmarcelle** [sqlalchemy/sqlalchemy#11815]
### Describe the bug

When using a nested recursive CTE within a lateral from clause, the content of the CTE does not follow the behavior of simpler lateral clauses and instead inlines the parent query.

### SQLAlchemy Version in Use

2.0.31

### DBAPI (i.e. the database driver)

psycopg

### Database Vendor and Major Version

Postgresql

### Python Version

3.12

### Operating system

Windows

### To Reproduce

```python
from sqlalchemy import Integer, String, Values, select, column
from sqlalchemy.dialects.postgresql import dialect
cases = Values(column("case", String), name="labels").data(
    [("a", ), ("b", )]
)
v = Values(column("n", Integer), column("case", String), name="some_table").data(
    [(1, "a"), (2, "b")]
)
cte = (
    select(
        v.c.n + 1
    ).where(v.c.case == cases.c.case).cte(name="cte_0", nesting=True)
)
lat = select(cte, cases.c.case.label("lateral_case")).lateral()
stmt = select(cases, lat).select_from(cases)

print(stmt.compile(dialect=dialect(), compile_kwargs={"literal_binds": True}))
```

### Error

this prints
```
SELECT labels."case", anon_2.anon_1, anon_2.lateral_case 
FROM (VALUES ('a'), ('b')) AS labels ("case"), LATERAL (WITH cte_0 AS 
(SELECT some_table.n + 1 AS anon_1 
FROM (VALUES (1, 'a'), (2, 'b')) AS some_table (n, "case"), (VALUES ('a'), ('b')) AS labels ("case") 
WHERE some_table."case" = labels."case")
 SELECT cte_0.anon_1 AS anon_1, labels."case" AS lateral_case 
FROM cte_0) AS anon_2
```
as you can see, the **labels** VALUES clause is duplicated. It appears both at the top level and within the recursive CTE. However, the final select of the lateral clause correctly references the top level **labels** VALUES.

The expected output is as follows, with the duplicated VALUES clause removed:
```
SELECT labels."case", anon_2.anon_1, anon_2.lateral_case 
FROM (VALUES ('a'), ('b')) AS labels ("case"), LATERAL (WITH cte_0 AS 
(SELECT some_table.n + 1 AS anon_1 
FROM (VALUES (1, 'a'), (2, 'b')) AS some_table (n, "case")
WHERE some_table."case" = labels."case")
 SELECT cte_0.anon_1 AS anon_1, labels."case" AS lateral_case 
FROM cte_0) AS anon_2
```

### Additional context

This also affects recursive CTEs, which is initially how I discovered the problem. I have been unable to find documentation related to this issue. I believe that the CTE should behave as the rest of the lateral statement whenever they are nested.

**Comment by CaselIT** [comment]
Hi,

You may need to manually specify that you want to correlate, using `correlate` / `correlate_except`.
This usage seem very specialized, so I'm not sure it warrants a change into the auto-correlation logic.

@zzzeek what do you think?

**Comment by zzzeek** [comment]
hi -

First off this should not be posted as an issue.   I have tried [very hard to get people to please read these instructions](https://github.com/sqlalchemy/sqlalchemy/issues/new?assignees=&labels=requires+triage&projects=&template=bug_report.yaml) and im not sure what else to do other than writing a bot to just close issues.

Secondly, as @CaselIT mentions, this is an exotic statement and by adding a simple correlate() call the SQL you request is rendered exactly.    There's no way we'd get auto-correlation to figure this out since it's not aware of LATERAL.

any further issues **please open a discussion**, thank you

**Comment by odelmarcelle** [comment]
Thank you for the fast reply. Adding correlate() solved the issue as you said.

My apologies, it wasn't my intention to fill an issue for nothing. I've been reviewing the documentation of both CTEs and lateral clauses before posting this issue to check whether this case was addressed.

I really didn't expect the call to correlate() to be necessary, as I thought the correlation would be taken care of thanks to lateral(). While I agree that my use case is exotic, this is something I developed using SQL and attempted to translate into SQLAlchemy code. As I started from SQL, I naively expected LATERAL to behave similarly in SQLAlchemy.

Would you accept a contribution to the documentation to highlight such limit in the lateral construct?

**Comment by CaselIT** [comment]
sure, mentioning that manual correlation may be needed when using lateral may be useful.
the docs is defined here https://github.com/sqlalchemy/sqlalchemy/blob/a102b8880cee50ac54ee6c25265420d670f91c21/lib/sqlalchemy/sql/selectable.py#L303
