### ISSUE TITLE
`get_check_constraints` result changed in SQLAlchemy 2.0.33

### ISSUE THREAD

**Issue by harupy** [sqlalchemy/sqlalchemy#11832]
### Describe the bug

In mlflow/mlflow, we use `inspector.get_check_constraints` when validating database table schemas. We found the result has changed in the latest release (2.0.33).

```python
import mlflow

mlflow.set_tracking_uri("sqlite:///mlruns.db")

with mlflow.start_run():
    pass

import sqlalchemy

engine = sqlalchemy.create_engine("sqlite:///mlruns.db")

inspector = sqlalchemy.inspect(engine)

print(inspector.get_check_constraints("experiments"))
# 2.0.33:
# [{'sqltext': "lifecycle_stage IN ('active', 'deleted')), \n\tUNIQUE (name", 'name': 'experiments_lifecycle_stage'}]
# 2.0.32:
# [{'sqltext': "lifecycle_stage IN ('active', 'deleted')", 'name': 'experiments_lifecycle_stage'}]

# experiments table has a check constraint for `lifecycle_stage` and a unique constraint `name`. The 2.0.32 result looks correct while the 2.0.33 doesn't.
```

### SQLAlchemy Version in Use

2.0.33

### DBAPI (i.e. the database driver)

sqlite

### Database Vendor and Major Version

sqlite

### Python Version

3.8

### Operating system

Linux

### To Reproduce

```python
See the code above
```

### Error

```
N/A
``` 

### Additional context

https://github.com/sqlalchemy/sqlalchemy/pull/11678 seems related

**Comment by zzzeek** [comment]
hi -

I can't fix unless you can give me a CREATE TABLE that reproduces this

**Comment by harupy** [comment]
@zzzeek Thanks for the comment. Sure, let me create a minimum reproducer.

**Comment by harupy** [comment]
I probed the value of `table_data`:

```sql
CREATE TABLE experiments (
        experiment_id INTEGER NOT NULL, 
        name VARCHAR(256) NOT NULL, 
        artifact_location VARCHAR(256), 
        lifecycle_stage VARCHAR(32), creation_time BIGINT, last_update_time BIGINT, 
        CONSTRAINT experiment_pk PRIMARY KEY (experiment_id), 
        CONSTRAINT experiments_lifecycle_stage CHECK (lifecycle_stage IN ('active', 'deleted')), 
        UNIQUE (name)
)
```

**Comment by harupy** [comment]
The regex in https://github.com/sqlalchemy/sqlalchemy/pull/11701 doesn't seem to assume that `UNIQUE (name)` appears after constraints:

```
        # This can either be (1) the beginning of the next constraint,
        # or (2) the end of the table definition.
```

**Comment by harupy** [comment]
This line doesn't seem to cover all possible constraint keywords:

https://github.com/sqlalchemy/sqlalchemy/blob/b2d629f18695ecb08cddeb99d7c2573e1f3d04b2/lib/sqlalchemy/dialects/sqlite/base.py#L2677

**Comment by zzzeek** [comment]
cool if you have a PR to put up that fixes the regex I can add more tests (or if you want to)

**Comment by harupy** [comment]
@zzzeek I filed #11834.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Fix regular expression for `SQLiteDialect.get_check_constraints`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5458

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**Fix regular expression for `SQLiteDialect.get_check_constraints`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5490
