### ISSUE TITLE
Version 2.0.33 incorrectly considers Mapped[Annotated[list, int]] as list[list] regression

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11831]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11830

<div type='discussions-op-text'>

<sup>Originally posted by **Klikini** September  3, 2024</sup>
Hi, my application has code that looks like this:

```python
# common file

from typing import Annotated

from sqlalchemy import Integer
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import MappedAsDataclass, DeclarativeBase

IntArray = Annotated[list, int]

class Base(MappedAsDataclass, DeclarativeBase):
    type_annotation_map = {
        IntArray: ARRAY(Integer),
    }
```

```python
# implementation file

from sqlalchemy.orm import mapped_column, Mapped

from .common import Base, IntArray

class MyModel(Base):
    my_column: Mapped[IntArray] = mapped_column(default_factory=list)
```

This worked fine with version 2.0.32, but fails with the following error after upgrading to version 2.0.33: `sqlalchemy.exc.ArgumentError: Could not locate SQLAlchemy Core type for Python type list[list] inside the 'my_column' attribute Mapped annotation`

Is this a bug in the new release, or was I doing something wrong that didn't cause problems until now?</div>

**Comment by zzzeek** [comment]
also you should apply a type to that list, which also works:

```
Annotated[list[int], int]
```

the use of `list` by itself is incomplete

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use proper functions to get typing origin, args** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5488

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**use proper functions to get typing origin, args** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5489
