### ISSUE TITLE
raise an error if joinedload() is used with anything that is not a SELECT

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11853]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11852

joinedload() likes to silently pass if not applicable but for an insert()/update()/delete() returning it should just raise, since this is never appropriate

**Comment by CaselIT** [comment]
maybe warning in v2, error in v2.1 is better?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**raise for joinedload, subqueryload used with DML** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5499

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**raise for joinedload, subqueryload used with DML** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5500

**Comment by zzzeek** [comment]
not sure yet.
