### ISSUE TITLE
mariadbconnector doesn't pass along query parameters in the url as arguments to connect method as mysqldb does 

### ISSUE THREAD

**Issue by tapetersen** [sqlalchemy/sqlalchemy#11870]
While trying to ensure our codebase works with both connectors the first issue was that appending, in our case, `?unix_socket=/path/to/socket` wasn't having any effect while using mariadbconnector while mysqldb passes it as args to the connect method.

Both drivers are very similar and supports the same argument in almost all cases so I assume it would work fine just doing the same call in both drivers (or if that is not a desired usage deprecate passing it as url_params and document that it's prefered to pass it as explicit options to create_engine).

We can work around it either way but it feels like an unnecesary inconsistency.

I havn't checked the behavior of other dialects in this regard but the difference between these to is simply the call to `opts.update(url.query)` at 
https://github.com/sqlalchemy/sqlalchemy/blob/29c2c15902094965f9dca66efae33305f09c3878/lib/sqlalchemy/dialects/mysql/mysqldb.py#L208

which has no corresponding call in mariadbconnector.
Just adding it here https://github.com/sqlalchemy/sqlalchemy/blob/29c2c15902094965f9dca66efae33305f09c3878/lib/sqlalchemy/dialects/mysql/mariadbconnector.py#L169

works reasonably in my preliminary testing.

_Originally posted by @tapetersen in https://github.com/sqlalchemy/sqlalchemy/discussions/11868_

**Comment by tapetersen** [comment]
Small reproduction below

```
from sqlalchemy.dialects.mysql import mariadbconnector
from sqlalchemy import make_url

dialect = mariadbconnector.dialect()
args, opts = dialect.create_connect_args(make_url("mysql+mariadbconnector:///?unix_socket=foo.sock"))
assert opts["unix_socket"] == "foo.sock"
```

result:
```
Traceback (most recent call last):
  File "/home/tobias/Projects/sqlalchemy/dialectest.py", line 6, in <module>
    assert opts["unix_socket"] == "foo.sock"
KeyError: 'unix_socket'
```

**Comment by sqla-tester** [comment]
**Tobias Petersen** has proposed a fix for this issue in the **main** branch:

**Merge url query args to opts in mariadbconnector like mysqldb** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5505

**Comment by sqla-tester** [comment]
**Tobias Petersen** has proposed a fix for this issue in the **rel_2_0** branch:

**Merge url query args to opts in mariadbconnector like mysqldb** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5506
