### ISSUE TITLE
the ORM does not expire server_onupdate columns during a bulk UPDATE (new style)

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#11917]
This was discussed in #11911

The `server_onupdate` columns do not get expired by the orm following an update, requiring populate-existing to fetch the new values. This impact mainly computed columns.

Reproducer:
```py
from sqlalchemy import orm
import sqlalchemy as sa

class Base(orm.DeclarativeBase):
    pass

class T(Base):
    __tablename__ = "t"
    id: orm.Mapped[int] = orm.mapped_column(primary_key=True)
    value: orm.Mapped[int]
    cc: orm.Mapped[int] = orm.mapped_column(sa.Computed("value + 42"))

e = sa.create_engine("sqlite:///", echo=True)
Base.metadata.create_all(e)
with orm.Session(e) as s:
    s.add(T(value=10))
    s.flush()
    s.commit()
with orm.Session(e) as s:
    assert (v := s.get_one(T, 1)).cc == 52

    s.execute(sa.update(T).values(id=1, value=2))

    assert (v := s.get_one(T, 1)).cc != 44  # should be 44
with orm.Session(e) as s:
    assert (v := s.get_one(T, 1)).cc == 52

    r = s.execute(sa.update(T).values(value=2).returning(T))
    assert (v := r.scalar_one()).cc != 44  # should be 44
    assert (v := s.get_one(T, 1)).cc != 44  # should be 44
with orm.Session(e) as s:
    r = s.execute(sa.insert(T).values(value=9).returning(T))
    assert (v := r.scalar_one()).cc == 51

    r = s.execute(sa.update(T).values(value=2).filter_by(id=2).returning(T))
    assert (v := r.scalar_one()).cc != 44  # should be 44
    r = s.execute(sa.select(T).filter_by(id=2))
    assert (v := r.scalar_one()).cc != 44  # should be 44
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**honor prefetch_cols and postfetch_cols in ORM update w/ WHERE criteria** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5526

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**honor prefetch_cols and postfetch_cols in ORM update w/ WHERE criteria** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5527

**Comment by zzzeek** [comment]
@CaselIT  in #12125 this introduces a sudden new lazy fetch taht would be better if we could add RETURNING for this case, was this a user-reported issue?   looking at a revert for this for now

**Comment by CaselIT** [comment]
it was discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11911.

I think this change made sense so at least for 2.1 I think it makes sense to keep

**Comment by zzzeek** [comment]
oh i want to keep it for sure but the RETURNING thing should be there for it so we arent' incurring a lazy load
