### ISSUE TITLE
MappedAdDataclass error when providing a __table__

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#11973]
This example raises 
> AssertionError: Mapped[] received without a mapping declaration

```py
import sqlalchemy as sa
from sqlalchemy.orm import Mapped, MappedAsDataclass, DeclarativeBase

t = sa.Table(
    "x",
    sa.MetaData(),
    sa.Column("id", sa.Integer, primary_key=True),
    sa.Column("name", sa.Text),
)

class Base(MappedAsDataclass, DeclarativeBase):
    pass

class X(Base):
    __table__ = t
    id: Mapped[int]
    name: Mapped[int]
```

**Comment by zzzeek** [comment]
i dont think this is new information we've told people to use `TYPE_CHECKING` for this use case in the past havent we?   I dont see how the ORM could do this one because it wants to map columns that are given as annotations

I guess we would have to turn off the whole ORM annotated declarative feature if `__table__` is given.     We might have an issue for this already not sure, this has definitely come up though

**Comment by CaselIT** [comment]
You are probably right regarding type_checking. I don't remember at the moment.

I don't know if the issue is only when using dataclasses. I haven't tried without.

In any case a better error may be nice to have

**Comment by CaselIT** [comment]
> I don't know if the issue is only when using dataclasses. I haven't tried without.

the issue is only when using dataclass.

I'll just raise a better error

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improve error in dataclasses with table** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5541

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Improve error in dataclasses with table** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5542

**Comment by stanevicius1** [comment]
@CaselIT revert or fix it [issue](https://github.com/corridor/sqlalchemy-history/issues/146)

**Comment by CaselIT** [comment]
Reverting is unlikely to fix, since before it was hitting an assert.

If you can provide an example that worked in 2.0.35 and does not in 2.0.36 without using external libraries please open a new issue

**Comment by stanevicius1** [comment]
@CaselIT  solution makes another problem and issue already created: https://github.com/corridor/sqlalchemy-history/issues/146

**Comment by CaselIT** [comment]
Whatever sqlalchemy-history is doing it's not supported.
I would suggest that a maintainer of that library should open a discussion to understand what they require sqlalchemy to do for their library so that a way that uses the public api is found. If that's not available the sqlalchemy team can evaluate adding a new api to cater that use case

**Comment by benedikt-bartscher** [comment]
@stanevicius1 i posted one possible mitigation here: https://github.com/corridor/sqlalchemy-history/issues/146#issuecomment-2518890066
