### ISSUE TITLE
get _Binary to generic LargeBinary

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#11978]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11977

```py
>>> from sqlalchemy import types
>>> types.VARBINARY().as_generic()
LargeBinary()

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**_Binary as generic to LargeBinary** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5531

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**_Binary as generic to LargeBinary** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5532
