### ISSUE TITLE
foreign key reflection in mysql 8 can be very slow in large databases

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#11975]
Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11967

Db information:

```sql
select count(1)
from information_schema.columns
```
3091788
```sql
select count(1)
from (select distinct table_schema, table_name from information_schema.columns) as x
```
58316

```slq
select count(1)
from information_Schema.REFERENTIAL_CONSTRAINTS 
```
1033

see https://github.com/sqlalchemy/sqlalchemy/discussions/11967#discussioncomment-10893458 and https://github.com/sqlalchemy/sqlalchemy/discussions/11967#discussioncomment-10894233

The issue is the query run by: https://github.com/sqlalchemy/sqlalchemy/blob/74a8e2ced922183d6ad072eced904cb989113fa2/lib/sqlalchemy/dialects/mysql/base.py#L3042-L3127

that looks like this:
```sql
select table_schema, table_name, column_name
from information_schema.columns
where (table_schema, table_name, lower(column_name)) in (
  (%(table_data_1_1)s, %(table_data_1_2)s, %(table_data_1_3)s),
  (%(table_data_2_1)s, %(table_data_2_2)s, %(table_data_2_3)s)
);
```

The solution here is probably to simplify the query condition

**Comment by gordthompson** [comment]
The `lower(column_name)` is not sargable so at best we'd be doing an index scan on 3 million entries. Is it really necessary? This test suggests that perhaps it isn't if the `in( … )` clause really is case-insensitive.

```sql
select version()
```

```
version()|
---------+
8.0.34   |
```

```sql
create table t1 (`Id` int)
```

```sql
select table_schema, table_name, column_name
from information_schema.columns
where (table_schema, table_name, column_name) in (
  ('test', 't1', 'Id')
)
```

```
TABLE_SCHEMA|TABLE_NAME|COLUMN_NAME|
------------+----------+-----------+
test        |t1        |Id         |
```

```sql
select table_schema, table_name, column_name
from information_schema.columns
where (table_schema, table_name, column_name) in (
  ('test', 't1', 'id')
)
```

```
TABLE_SCHEMA|TABLE_NAME|COLUMN_NAME|
------------+----------+-----------+
test        |t1        |Id         |
```

```sql
select table_schema, table_name, column_name
from information_schema.columns
where (table_schema, table_name, column_name) in (
  ('test', 't1', 'ID')
)
```

```
TABLE_SCHEMA|TABLE_NAME|COLUMN_NAME|
------------+----------+-----------+
test        |t1        |Id         |
```

**Comment by CaselIT** [comment]
Interesting find gord. It's likely that the column_name type is case insensitive, so any comparison does not consider case.

Do you se the same behaviour if you use `=` ?

**Comment by gordthompson** [comment]
Oh, wait. The [MySQL bug report](https://bugs.mysql.com/bug.php?id=96365) says

> First establish that the database is on a case-insensitive filesystem with lower_case_table_names=2

My test above was on a Linux server with lower_case_table_names=0, so it may not be applicable.

The dialect tweak checks for that. This is more of an edge case than I first thought.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Optimize MySQL foreign key reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5546

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Optimize MySQL foreign key reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5547
