### ISSUE TITLE
missing type cast for jsonb in values for postgres?

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#11994]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/11990

<div type='discussions-op-text'>

<sup>Originally posted by **JabberWocky-22** October 12, 2024</sup>
I'm using `values` to update multi rows in single execution in postgres.
The sql failed due to type match on jsonb column, since it doesn't have a type cast and take text as fallback.
Currently I can add type cast in update statement, but it will nice to add it in rendering just like uuid column.

To Reproduce:
```python
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

table = sa.Table(
    "test",
    sa.MetaData(),
    sa.Column("id", sa.Integer),
    sa.Column("uuid", sa.Uuid, unique=True),
    sa.Column("extra", JSONB),
)
engine = sa.create_engine("postgresql://xxx:xxx@localhost:1234/db")
with engine.begin() as conn:
    table.create(conn, checkfirst=True)
    conn.execute(
        table.insert().values(
            [
                {"id": 1, "uuid": "d24587a1-06d9-41df-b1c3-3f423b97a755"},
                {"id": 2, "uuid": "4b07e1c8-d60c-4ea8-9d01-d7cd01362224"},
            ]
        )
    )
    value = sa.values(
        sa.Column("id", sa.Integer),
        sa.Column("uuid", sa.Uuid),
        sa.Column("extra", JSONB),
        name="update_data"
    ).data(
        [
            (
                1,
                "8b6ec1ec-b979-4d0b-b2ce-9acc6e4c2943",
                {"foo": 1},
            ),
            (
                2,
                "a2123bcb-7ea3-420a-8284-1db4b2759d79",
                {"bar": 2},
            ),
        ]
    )
    conn.execute(
        table.update()
        .values(uuid=value.c.uuid, extra=value.c.extra)
        .where(table.c.id == value.c.id)
    )

```

traceback:
```bash
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "extra" is of type jsonb but expression is of type text
LINE 1: UPDATE test SET uuid=update_data.uuid, extra=update_data.ext...
                                                     ^
HINT:  You will need to rewrite or cast the expression.

[SQL: UPDATE test SET uuid=update_data.uuid, extra=update_data.extra FROM (VALUES (%(param_1)s, %(param_2)s::UUID, %(param_3)s), (%(param_4)s, %(param_5)s::UUID, %(param_6)s)) AS update_data (id, uuid, extra) WHERE test.id = update_data.id]
[parameters: {'param_1': 1, 'param_2': '8b6ec1ec-b979-4d0b-b2ce-9acc6e4c2943', 'param_3': '{"foo": 1}', 'param_4': 2, 'param_5': 'a2123bcb-7ea3-420a-8284-1db4b2759d79', 'param_6': '{"bar": 2}'}]
```

Versions:
SQLAlchemy:  2.0.35
psycopg2-binary:  2.9.3
db: PostgreSQL 15.2

Have a nice day</div>

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Render bind cast in json and jsonb in PG** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5548

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Render bind cast in json and jsonb in PG** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5549

**Comment by ljmc-github** [comment]
Hi @CaselIT,

This change breaks one of my flows, maybe you can help resolve in nice way.

I have several reflected tables with a JSON or JSONB columns, they were set up so that they use SQL NULL for None rather than JSON null and so I've added an event for catching reflection of columns whose type is `sqlalchemy.JSON` (which includes JSONB columns) and switch the column info type to `JSON(none_as_null=True)`.

```python
from sqlalchemy import JSON, event

@event.listens_for(metadata, "column_reflect")
def _reflect_jsonb_with_none_as_null_true(inspector, table, column_info):
    if isinstance(column_info["type"], JSON):
        column_info["type"] = JSON(none_as_null=True)
```

With this change, and explicit casts, my comparisons are broken for JSONB columns with `(psycopg2.errors.UndefinedFunction) operator does not exist: jsonb = json`, which make sense as the parameter is casted to `::JSON` when previously it relied on postgress sorting it out from TEXT.

Any way to keep a generic event catcher ?

I wouldn't mind doing the following, but JSONB being a subclass of JSON, I might not be the only one using `isinstance` against `JSON` for both.

```python
@event.listens_for(metadata, "column_reflect")
def _reflect_jsonb_with_none_as_null_true(inspector, table, column_info):
    if isinstance(column_info["type"], JSONB):
        column_info["type"] = JSONB(none_as_null=True)
    elif isinstance(column_info["type"], JSON):
        column_info["type"] = JSON(none_as_null=True)
```

**Comment by CaselIT** [comment]
Not sure if we can update this change to make both use cases work.
The main issue is that posgresql is unnecessarily picky about types. 

@zzzeek do you have some ideas here?

**Comment by zzzeek** [comment]
if a column is reflected as JSONB then they have to maintain that JSONB datatype, of course, so their second solution that differentiates between JSON/JSONB is the correct one.  I dont see how this would be controversial.    they likely can just set the `none_as_null` attribute in place or re-build the type using `__class__` if they want to avoid referencing JSONB explicitly

**Comment by ljmc-github** [comment]
@CaselIT @zzzeek thank you both for quick answers, I know I was abusing JSON datatype tree there, I wasn't aware I could set the `none_as_null` directly, just tried it and it works perfectly, keeping things generic and simple.

```python
from sqlalchemy import JSON, event

@event.listens_for(metadata, "column_reflect")
def _reflect_jsonb_with_none_as_null_true(inspector, table, column_info):
    if isinstance(column_info["type"], JSON):
        column_info["type"].none_as_null=True
```
