### ISSUE TITLE
ORM enabled update sync-session fetch relies on hardcoded order of PK columns for user-specified RETURNING result

### ISSUE THREAD

**Issue by ManiMozaffar** [sqlalchemy/sqlalchemy#11997]
### Describe the bug

When using SQLAlchemy's AsyncSession to perform updates with complex WHERE clauses involving subqueries and window functions, the session does not correctly maintain the state of affected Event objects. In the provided example, an update using a LEAD window function successfully modifies records in the database, but the AsyncSession fails to recognize these changes, leading to inconsistencies between the ORM state and the actual database state. This issue likely stems from the session not properly expiring or refreshing objects after executing intricate update statements, causing the ORM to become out of sync with the core database state.

### SQLAlchemy Version in Use

2.0.28 (tried on different version, doesnt' fix it)

### DBAPI (i.e. the database driver)

aiosqlite

### Database Vendor and Major Version

SQLite

### Python Version

3.12

### Operating system

MacOSX

### To Reproduce

```python
from contextlib import asynccontextmanager
from dataclasses import asdict
from datetime import datetime, timedelta, timezone
from uuid import uuid4

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column


class BaseSQL(MappedAsDataclass, DeclarativeBase): ...


class Event(BaseSQL):
    __tablename__ = "Events"
    event: Mapped[str] = mapped_column(sa.String())
    created_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True))
    id: Mapped[str] = mapped_column(primary_key=True, default_factory=lambda: str(uuid4()))
    author_id: Mapped[str] = mapped_column(primary_key=True, default_factory=lambda: str(uuid4()))


@asynccontextmanager
async def init_sqlachemy_db():
    engine = create_async_engine("sqlite+aiosqlite:///:memory:", echo=False)
    db = async_sessionmaker(engine, expire_on_commit=False, autobegin=False)
    async with engine.begin() as conn:
        await conn.run_sync(BaseSQL.metadata.create_all)
    yield db


async def populate_some_data(session: AsyncSession):
    now = datetime.now(timezone.utc)
    author_id = str(uuid4())
    objs = [
        Event(author_id=author_id, event="1", created_at=now - timedelta(days=4)),
        Event(author_id=author_id, event="2", created_at=now - timedelta(days=3)),
    ]

    inserted_objs = (
        await session.execute(sa.insert(Event).returning(Event), [asdict(obj) for obj in objs])
    ).all()
    return inserted_objs


def get_complicated_where():
    event_lead = sa.select(
        Event.id,
        sa.func.lead(Event.event)
        .over(
            partition_by=Event.author_id,
            order_by=Event.created_at,
        )
        .label("next_event"),
    ).subquery()
    event_query = (
        sa.select(event_lead.c.id).select_from(event_lead).where(event_lead.c.next_event == "2")
    )
    return event_query


async def test_complicated_update_map_incorrectly_in_sqlalchemy():
    async with init_sqlachemy_db() as db:
        async with db.begin() as session:
            inserted_objs = await populate_some_data(session)
            event_query = get_complicated_where()
            query = (
                sa.update(Event).where(Event.id.in_(event_query)).values(event="2").returning(Event)
            )
            result = await session.scalar(query)
            print(result)
            assert result is not None and result.event == "2"


if __name__ == "__main__":
    import asyncio

    asyncio.run(test_complicated_update_map_incorrectly_in_sqlalchemy())
```

### Error

Assertion error, event was supposed to be "2"

### Additional context

Some weird facts:

- removing variable name inserted_objs would fix the issue :D I guess because garbage collected? No idea tbh. Isn't it supposed to be still attached and referenced in sesson in identity map?
- Changing the "WEHRE" statement to "event == 1" would fix the issue (as a workaround ofc)
- Adding populate_existing to query DOES NOT fix the issue, nor it should matter. because this is workaround, not a solution to bug. Session fails to understand the latest state is returned by update query, not in select statement.
- Expunging object from session before running the query DOES solve the problem, but as a workaround ofoucrse. The point of this bug is having your objects in ORM, disrespecting populate_existing and execution order it still fail.

**Comment by CaselIT** [comment]
Hi,

I disagree on the fact that populate existing shouldn't matter here, but the fact that in either case the state is not updated looks like a bug

**Comment by CaselIT** [comment]
Also I don't think this in an async session issue, but of the normal session.

@zzzeek it seems likely that the but is in the code used to evaluate the where in the session.

@ManiMozaffar can you try setting fetch as synchronization strategy to see if it fixes the issue? https://docs.sqlalchemy.org/en/20/orm/queryguide/dml.html#selecting-a-synchronization-strategy

**Comment by zzzeek** [comment]
workaround like this for now (note sort_order):

```py
class Event(BaseSQL):
    __tablename__ = "Events"
    event: Mapped[str] = mapped_column(sa.String())
    created_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True))
    id: Mapped[str] = mapped_column(
        primary_key=True, default_factory=lambda: str(uuid4()), sort_order=-2
    )
    author_id: Mapped[str] = mapped_column(
        primary_key=True, default_factory=lambda: str(uuid4()), sort_order=-1
    )

```

**Comment by ManiMozaffar** [comment]
> Also I don't think this in an async session issue, but of the normal session.
> 
> @zzzeek it seems likely that the but is in the code used to evaluate the where in the session.
> 
> @ManiMozaffar can you try setting fetch as synchronization strategy to see if it fixes the issue? https://docs.sqlalchemy.org/en/20/orm/queryguide/dml.html#selecting-a-synchronization-strategy

Setting it to either fetch or False doesn't solve the issue.

**Comment by ManiMozaffar** [comment]
> workaround like this for now (note sort_order):
> 
> ```python
> class Event(BaseSQL):
>     __tablename__ = "Events"
>     event: Mapped[str] = mapped_column(sa.String())
>     created_at: Mapped[datetime] = mapped_column(sa.DateTime(timezone=True))
>     id: Mapped[str] = mapped_column(
>         primary_key=True, default_factory=lambda: str(uuid4()), sort_order=-2
>     )
>     author_id: Mapped[str] = mapped_column(
>         primary_key=True, default_factory=lambda: str(uuid4()), sort_order=-1
>     )
> ```

I'm wondering why changing the "WHERE" statement fixing the issue?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**WIP: needs tests** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5535

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**match ORM mapped cols to PK in interpret_returning_rows** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5536
