### ISSUE TITLE
TypeDecorator pickling error in 2.0, works fine in 1.4.54

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#12002]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/12001

<div type='discussions-op-text'>

<sup>Originally posted by **rad-pat** October 15, 2024</sup>
When trying to upgrade to 2.0.35 from 1.4.54, we cannot because we get a pickling error in 2.0.35. 

I'm sure pickling queries is not the best way to transport between app layers, however it is currently being done in our app until I can update it. 

We have a couple of custom types to control behaviour across dialects where certain types are not yet supported. It's possible that some of them are not needed any longer. However, here is a very quick example of the pickling error in case it is something easy to address.

```python
import pickle
import sqlalchemy as sa

class MyType(sa.TypeDecorator):
    impl = sa.NVARCHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name in {'postgresql'}:
            return dialect.type_descriptor(sa.UnicodeText)
        else:
            return self.impl

m = sa.MetaData()
t = sa.Table('test', m, sa.Column('id', MyType))

delete_query = sa.delete(t).where(t.c.id == '1')

p = pickle.dumps(delete_query)

#    p = pickle.dumps(delete_query)
#        ^^^^^^^^^^^^^^^^^^^^^^^^^^
#_pickle.PicklingError: Can't pickle <class 'sqlalchemy.sql.type_api.TDComparator'>: attribute lookup TDComparator on sqlalchemy.sql.type_api failed
```</div>

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add tests for pickling types inside an expression, some reduce methods** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5539

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**add tests for pickling types inside an expression, some reduce methods** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5540
