### ISSUE TITLE
Unable to use IN operator in 2.0.36 to select a list of columns

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#12019]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/12018

<div type='discussions-op-text'>

<sup>Originally posted by **Apakottur** October 21, 2024</sup>
The following code:
```python
result = await session.execute(
            select(Actor.id).where(
                Actor.id.in_([Actor.id]),
            )
````

Is valid in sqlalchemy==2.0.35 and generates the following correct SQL:
```sql
SELECT actor.id  FROM actor WHERE actor.id IN (actor.id)
```

However, in sqlalchemy==2.0.36 the same expression gives:
```text
sqlalchemy.exc.ArgumentError: IN expression list, SELECT construct, or bound parameter object expected, got [<sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7b8fec7bb240>].
```

It this a bug or using IN like this is no longer allowed?

[full gist](https://gist.github.com/Apakottur/3ae21382dcd22539a86464820269b613)</div>

**Comment by CaselIT** [comment]
while the sql in the example does not make much sense, since it's always true, one could use something like `select(Thing.id).where(Thing.in.in_([Thing.parent_id, Thing.another_id]))`

**Comment by zzzeek** [comment]
it's not actually always true if "thing.id" were null....

I'm still trying to wrap my head around the SQL use case here though.   Why would someone realistically put a fixed column in an IN list like that?   very strange.

**Comment by zzzeek** [comment]
oh wow I know what the change is!  it was the mypy update.     There was this code change that I found to be a little scary but no tests failed.   well ok

**Comment by CaselIT** [comment]
> oh wow I know what the change is! it was the mypy update. There was this code change that I found to be a little scary but no tests failed. well ok

yes, that's the change, I forgot to report this here. I had commented in the discussion with that commit: https://github.com/sqlalchemy/sqlalchemy/discussions/12018#discussioncomment-11004785

> I'm still trying to wrap my head around the SQL use case here though. Why would someone realistically put a fixed column in an IN list like that? very strange.

I agree it's quite strange, but you can have valid use cases. see for example the op comment here https://github.com/sqlalchemy/sqlalchemy/discussions/12018#discussioncomment-11004846

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**refine in_() check to use proper duck-typing for __clause_element__** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5562

**Comment by zzzeek** [comment]
we had tests for this SQL form already just not with an ORM element

**Comment by CaselIT** [comment]
makes sense that the table column would pass since it's a column element
