### ISSUE TITLE
Python 3.8 is eol, remove support from 2.1

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#12029]
as title says.

Things we could use:
- dict union -> does not really have too much impact since sqlalchemy mostly uses immutable dict
- use lowercase collections -> IIRC I had issues there, so it's likely safer to just wait until 3.10+. Also would make backporting to 2.0 harder

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Removed support for Python 3.8 since it's EOL.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5553

**Comment by jvanasco** [comment]
Why are so many py39 lines stripped for a py38 deprecation?

**Comment by CaselIT** [comment]
That check indicates python3.9 or greater, that's always true after removing 3.8 support

**Comment by jvanasco** [comment]
Thanks for indulging me with the explanation! The sections I saw didn't seem like there was a logic gate going on, but setting the new default behavior makes perfect sense.
