### ISSUE TITLE
Improve detection of max_identfier_length in oracledb driver

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#12032]
After the discussion #11879 oracledb added a new attribute to get the max identifier length https://github.com/sqlalchemy/sqlalchemy/discussions/11879#discussioncomment-11061829.

Use that instead of doing a query if present

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improve Oracle identifier length detection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5551

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Improve Oracle identifier length detection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5552

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improve oracle max id length again** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5590

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Improve oracle max id length again** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5591
