### ISSUE TITLE
Autocompletion issue with decalarative_base() objects

### ISSUE THREAD

**Issue by Gabbar-v7** [sqlalchemy/sqlalchemy#12106]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

from sqlalchemy import DateTime, Integer, String, func, create_engine
from sqlalchemy.orm import Mapped, declarative_base, mapped_column

## Return type set to Any in func definition
UserBase = declarative_base()    

engine = create_engine("sqlite:///database.db", echo=True)

## Here auto completion doesn't work nor code highlight
UserBase.metadata.create_all(engine) 

### To Reproduce

```python
from sqlalchemy import DateTime, Integer, String, func, create_engine
from sqlalchemy.orm import Mapped, declarative_base, mapped_column


UserBase = declarative_base()    

engine = create_engine("sqlite:///database.db", echo=True)

UserBase.metadata.create_all(engine)
```

### Error

```
# Copy the complete text of any errors received by the type checker(s).
``` 

No error text received

### Versions

- OS: Debian 12
- Python: 3.11
- SQLAlchemy: latest using pip install sqlalchemy
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): vocode python, pylance

### Additional context

Minor issue i tired it and only needs update in the return type in the declarative_base() fun.

**Comment by zzzeek** [comment]
hi - 

unfortunately Python pep484 typing has no support for dynamically generated classes returned by functions to have proper typing information, so the legacy `declarative_base()` function necessarily returns `Any`.   Please use the modern [DeclarativeBase](https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.DeclarativeBase) base class.

**Comment by Gabbar-v7** [comment]
But i tried changing the return type form Any to DeclarativeMeta i worked. Is there anything i am missing here like maybe the function returns different types for particular conditions.

**Comment by zzzeek** [comment]
but that's not what is actually returned.   that might work for a few attributes but it's not complete, the returned object doesnt know that it's a base for mapped classes and all of that part doesnt work.    so `Any` is more appropriate

please use the non-legacy APIs
