### ISSUE TITLE
Support oracle table function

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#12100]
Discussed in #12087

The issues is https://github.com/sqlalchemy/sqlalchemy/blob/fa76fbda4aa2887d001e1e15f9bfe9dfb24fadc8/lib/sqlalchemy/dialects/oracle/base.py#L866-L867 that seems to double up table if the function is already table

proposed solution is to add custom compile for table function

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Support table function in oracle** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5592

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_2_0** branch:

**Support table function in oracle** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5593
