### ISSUE TITLE
TypeVar bound by declarative base type "`has no attribute "__mapper__"`"

### ISSUE THREAD

**Issue by vergenzt** [sqlalchemy/sqlalchemy#12111]
### Describe the typing issue

The SQLAlchemy `mypy` plugin [tells `mypy` about the `__mapper__` attribute on subclasses of declarative bases](https://github.com/sqlalchemy/sqlalchemy/blob/1b40521f5fb1628dfc6beec73fddda6855f6c77f/lib/sqlalchemy/ext/mypy/apply.py#L299-L301).

Unfortunately this information does not get conveyed to `mypy` when using a generic `TypeVar` which is `bound` by the declarative base. `mypy` just complains that the base class `has no attribute "__mapper__"`.

For now I'm working around this by just adding a `# type: ignore` comment when I access `__mapper__` on the generic argument. But am filing this issue to explain the `# type: ignore` comment itself. 🙂

### To Reproduce

```python
# file: test.py
from typing import Any, Iterable, Tuple, Type, TypeVar

from sqlalchemy import Column, Text
from sqlalchemy.orm import as_declarative
from sqlalchemy.orm.mapper import Mapper


@as_declarative()
class Base:
    __abstract__ = True


MY_METADATA_KEY = object()
"Key used for setting my special metadata on columns"


class MyModel(Base):
    __tablename__ = "my_model"
    id = Column(Text, primary_key=True)
    col1 = Column(Text, info={MY_METADATA_KEY: "foo"})


MyModel.__mapper__  # type checks ✅


M = TypeVar("M", bound=Base)


def column_metadata(model_type: Type[M]) -> Iterable[Tuple[str, Any]]:
    mapper: Mapper = model_type.__mapper__  # does NOT type check ❌
    for column in mapper.columns.values():
        if MY_METADATA_KEY in column.info:
            yield (column.name, column.info[MY_METADATA_KEY])


print(dict(column_metadata(MyModel)))
```

### Error

```
test.py: note: In function "column_metadata":
test.py:31:22: error: "type[M]" has no attribute "__mapper__"  [attr-defined]
        mapper: Mapper = model_type.__mapper__  # does NOT type check ❌
                         ^~~~~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 1 source file)
```

Note that running the file directly succeeds:
```console
$ python test.py
{'col1': 'foo'}
```

### Versions

- OS: MacOS Sonoma 14.6.1 (23G93)
- Python: 3.10.14
- SQLAlchemy: 1.4.52
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.8.0

**Comment by vergenzt** [comment]
Gonna go ahead and close this since I did not test it on sqlalchemy `2.*`. Just filed for future reference.

**Comment by CaselIT** [comment]
I would suggest upgrading to v2 if you use type checkers in any capacity
