### ISSUE TITLE
`greenlet` is not installed on CPython 3.13

### ISSUE THREAD

**Issue by vytas7** [sqlalchemy/sqlalchemy#12145]
### Describe the bug

The `greenlet` dependency is unexpectedly not installed on the CPython 3.13 `x86_64` platform, contradicting the [documentation](https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#asyncio-platform-installation-notes-including-apple-m1).

The `greenlet` binary wheel is [available for CPython 3.13](https://pypi.org/project/greenlet/#files).
(FWIW, the `greenlet` wheels for 3.13 were made available prior to the release of SQLAlchemy 2.0.36.)

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#asyncio-platform-installation-notes-including-apple-m1

### SQLAlchemy Version in Use

2.0.36

### DBAPI (i.e. the database driver)

Any

### Database Vendor and Major Version

Any

### Python Version

CPython 3.13.0

### Operating system

Linux

### To Reproduce

```python
# Install SQLAlchemy on CPython 3.13.
import greenlet

# Or, a oneliner in Docker:
# docker run --rm -it python:3.13 /bin/bash -c "python -m venv /tmp/venv; /tmp/venv/bin/pip install SQLAlchemy; /tmp/venv/bin/python -c 'import greenlet'"
```

### Error

```
ModuleNotFoundError: No module named 'greenlet'
```

### Additional context

`python:3.12` works as expected.

**Comment by zzzeek** [comment]
you should standardize on installing as `pip install sqlalchemy[asyncio]` since that will be required in 2.1

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**enable py3.13 for greenlet** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5574

**Comment by CaselIT** [comment]
manually closing since this will not got in main
