### ISSUE TITLE
Invalid OID Handling in SQLAlchemy with asyncpg and autoload_with Causes DataError

### ISSUE THREAD

**Issue by gtolarc** [sqlalchemy/sqlalchemy#12147]
### Describe the bug

I encountered an issue when using SQLAlchemy with asyncpg and the autoload_with option while trying to load table metadata. The problem occurs because PostgreSQL's oid type is treated as a signed 32-bit integer (int32) by asyncpg, which leads to a DataError when the OID value exceeds the maximum range of int32 (2,147,483,647).

### Steps to Reproduce
1. Create a PostgreSQL table with an OID that exceeds the int32 range. For example, an OID like 3195477613.
2. Use SQLAlchemy to define the table with autoload_with to load metadata:

```python
from sqlalchemy import Table, MetaData

metadata = MetaData()
table = Table("master_product_view", metadata, autoload_with=conn)
```

3. Execute the code.

### Observed Behavior
The following exception is raised during metadata loading:

```python
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: 3195477613 (value out of int32 range)
```

### Expected Behavior
The autoload_with option should correctly handle OID values, even if they exceed the int32 range.

### SQLAlchemy Version in Use

1.4.54

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.13

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import Table, MetaData

metadata = MetaData()
table = Table("master_product_view", metadata, autoload_with=conn)
```

### Error

The following exception is raised during metadata loading:

```python
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: 3195477613 (value out of int32 range)
```

**Comment by CaselIT** [comment]
Hi,

That's an error that comes from asyncpg, sqlalchemy is just reporting it.
I don't believe there is anything that sqlalchemy can do here, so I would suggest opening an issue in the asyncpg repository (The error should include also the sql statement that caused it, so you could use that when reporting that issue)

**Comment by zzzeek** [comment]
there's no stack trace here nor indication of the specific query, is this a query we should be using a cast() with ?  how can you tell this is not something we can control?

**Comment by CaselIT** [comment]
there is no information given and there is no casting to int in sqlalchemy reflection, so I'm guessing that's some issue with asyncpg. If not we can reopen the issue
