### ISSUE TITLE
fix CLOB->NVARCHAR output handler

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#12150]
> Hi Mike,
> 
> While looking into this issue (https://github.com/oracle/python-oracledb/issues/424) I discovered that SQLAlchemy is using an output type handler for CLOB to return NVARCHAR data. This is wrong! CLOB should use VARCHAR and NCLOB should use NVARCHAR. If you use CLOB with NVARCHAR you will end up performing two conversions instead of one. If one of those conversions fails you may get invalid data.
> 
> So this code in lib/sqlalchemy/dialects/oracle/cx_oracle.py:
> 
>>             elif dialect.auto_convert_lobs and default_type in (
>>                 cx_Oracle.CLOB,
>>                 cx_Oracle.NCLOB,
>>             ):
>>                 return cursor.var(
>>                     cx_Oracle.DB_TYPE_NVARCHAR,
>>                     _CX_ORACLE_MAGIC_LOB_SIZE,
>>                     cursor.arraysize,
>>                     **dialect._cursor_var_unicode_kwargs,
>>                 )
> should be:
> 
>>             elif dialect.auto_convert_lobs and default_type in (
>>                 cx_Oracle.CLOB,
>>                 cx_Oracle.NCLOB,
>>             ):
>>                  typ = cx_Oracle.DB_TYPE_VARCHAR if default_type is cx_Oracle.CLOB else cx_Oracle.DB_TYPE_NVARCHAR
>>                  return cursor.var(
>>                     typ,
>>                     _CX_ORACLE_MAGIC_LOB_SIZE,
>>                     cursor.arraysize,
>>                     **dialect._cursor_var_unicode_kwargs,
>>                 )

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use VARCHAR for CLOB outputtypehandler** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5575

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**use VARCHAR for CLOB outputtypehandler** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5576
