### ISSUE TITLE
`SmallInteger` is compiled to `SERIAL` instead of `SMALLSERIAL` on table creation when `asyncpg` driver is used.

### ISSUE THREAD

**Issue by FeeeeK** [sqlalchemy/sqlalchemy#12170]
### Describe the bug

If you are trying to create a table with a primary column of `SmallInteger` and the asyncpg driver is used, it will be compiled to `SERIAL` rather than `SMALLSERIAL`.
This is because this type is not implemented as a column spec and `AsyncpgInteger` is used instead, and a check for `SmallInteger` in the code below will return `False`, this should be fixed in #12171.
https://github.com/sqlalchemy/sqlalchemy/blob/860ca0b9d21874d9827f7f37cd0c330436baefb4/lib/sqlalchemy/dialects/postgresql/base.py#L2202-L2207

### SQLAlchemy Version in Use

2.0.36

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

PostgreSQL 16

### Python Version

3.12.7

### Operating system

Windows

### To Reproduce

```python
from sqlalchemy import SmallInteger, create_engine
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.orm import Mapped, declarative_base, mapped_column
from sqlalchemy.schema import CreateTable

ASYNCPG_SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost/postgres"
PSYCOPG_SQLALCHEMY_DATABASE_URL = "postgresql+psycopg2://postgres:postgres@localhost/postgres"
asyncpg_engine = create_async_engine(ASYNCPG_SQLALCHEMY_DATABASE_URL)
psycopg_engine = create_engine(PSYCOPG_SQLALCHEMY_DATABASE_URL)

Base = declarative_base()


class TestTable(Base):
    __tablename__ = "test_table"

    id: Mapped[int] = mapped_column(SmallInteger(), primary_key=True, autoincrement=True)


def main():
    print(CreateTable(TestTable.__table__).compile(psycopg_engine))
    print(CreateTable(TestTable.__table__).compile(asyncpg_engine))


if __name__ == "__main__":
    main()
```

### Error

```
CREATE TABLE test_table (
        id SMALLSERIAL NOT NULL,
        PRIMARY KEY (id)
)

CREATE TABLE test_table (
        id SERIAL NOT NULL,
        PRIMARY KEY (id)
)
```

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting

**Comment by sqla-tester** [comment]
**FeeeeK** has proposed a fix for this issue in the **rel_2_0** branch:

**Add missing `SmallInteger` column spec for `asyncpg`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5614

**Comment by sqla-tester** [comment]
**FeeeeK** has proposed a fix for this issue in the **main** branch:

**Add missing `SmallInteger` column spec for `asyncpg`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5613
