### ISSUE TITLE
Patch adding support for multiple result sets in ResultProxy

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#1635]
**Migrated issue, originally created by Anonymous**

This patch adds support for multiple result sets in the ResultProxy. It basically just adds a "nextset" method and replaces all the calls to close in the fetch* methods with a call to nextset, which closes the proxy if there are no more results available or no nextset method.

----------------------------------------
Attachments: [base-sa06.diff](../wiki/imported_issue_attachments/1635/base-sa06.diff) | [base-sa05.diff](../wiki/imported_issue_attachments/1635/base-sa05.diff)

**Comment by zzzeek** [comment]
this is really a doable thing but it's almost never that someone actually needs to access multiple result sets, most DBAPIs don't support it, and when someone does need it, they just do the raw cursor thing.    So I would welcome someone who wanted to work on this but I don't think there's really enough need for this to be worth it.
