### ISSUE TITLE
support in_() with orm.evaluator

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#1653]
**Migrated issue, originally created by Anonymous**

Working with up-to-date trunk, I can create queries with in_() criteria that work when .select() called on them but fail when .delete() is called. The error is:

sqlalchemy.exc.InvalidRequestError: Could not evaluate current criteria in Python.  Specify 'fetch' or False for the synchronize_session parameter.

See attached script.

----------------------------------------
Attachments: [sqla06bug.py](../wiki/imported_issue_attachments/1653/sqla06bug.py)

**Comment by radzak** [comment]
Encountered this a few times, it would be really great to see it implemented. :)

**Comment by zzzeek** [comment]
it's a pretty self-contained change, maybe you can work on it

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Propose using RETURNING for bulk updates, deletes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2048
