### ISSUE TITLE
func.now() should translate to calling SYSDATE for Oracle

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#1758]
**Migrated issue, originally created by Anonymous**

    Care should be taken that the return type is correct (date vs. datetime)

**Comment by CaselIT** [comment]
does anyone still uses oracle 8? It's eol since 2006.
Maybe we could close this?

**Comment by zzzeek** [comment]
cc @kbower

**Comment by zzzeek** [comment]
I don't think anything from Oracle ever "ends", really....

**Comment by kbower** [comment]
Yep, still forced to support it... sigh.  (Not by choice, mind you, but several of our clients use Oracle 8i and cannot upgrade because the legacy software on top of it is using oracle forms that needs that version.)

Still, if you want to close this ticket, I've already patched our application to "do the right thing" on oracle 8.   So you could close this from my perspective, but I just thought you might want sqlalchemy library to handle it...

**Comment by CaselIT** [comment]
> Oracle 8i and cannot upgrade because the legacy software on top of it is using oracle forms that needs that version

that must be horrible :\

I asked just because this was an issue from 10 years ago, for a db version that has been eol for more.
I'll leave the decision to @zzzeek

**Comment by kbower** [comment]
> I asked just because this was an issue from 10 years ago, for a db version that has been eol for more.
> I'll leave the decision to @zzzeek

I hear ya!

**Comment by zzzeek** [comment]
i mean you've worked around it right?   I guess you're still using the non-ansi mode joins thing also then.

is this just one customer you have ?

**Comment by kbower** [comment]
> i mean you've worked around it right? 

yes.  if you don't want to bother supporting this in sqlalchemy, it wouldn't hurt us...

> I guess you're still using the non-ansi mode joins thing also then.

oh, yes.  In fact, we found there was a certain version of Oracle 11 with a bug that forces us to use non-ansi mode (even though not Oracle 8)!

> is this just one customer you have ?

no, several (all running the same old version of the legacy software)

**Comment by zzzeek** [comment]
like #1760 this is an old oracle 8 issue for which there are workarounds.
