### ISSUE TITLE
reflect postgresql "inherits" relationships, add to table dependencies, cascade constraints downwards?

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#1803]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

**Comment by zzzeek** [comment]
given table defs as:

```
create table base (
  id serial primary key,
  date_created timestamp default current_timestamp
);

create table users (
  username text,
  password text
) inherits ("base");

create table books(
  name text,
  authors text
) inherits ("base");
```

reflect will actually get all three tables and have all the columns present for each.  it just won't have the primary key constraint for the "id" column in the subtables (and likely not the indexes, etc. either).  so the feature would need to cascade these constraints downwards during reflection.

**Comment by zzzeek** [comment]
So for the sub-tables to have the constraints and indexes present but not have them be part of a CREATE TABLE, there would need to be a flag on constraint that this constraint was "cascaded" from a super-table, and it is only a "virtual" constraint of some kind.  This implies deep changes to DDL sequences and constraint logic.

**Comment by zzzeek** [comment]
I think the "inherits" concept here should remain local to Postgresql.    I think PostgreSQL should copy out the PrimaryKeyConstraint to the sub-tables if they do not have a PK constraint of their own, and the object should have a dialect-specific flag that it is "inherited'.  This will need a change in Inspector->_reflect_pk to copy over this flag.   PG then uses this flag at DDL rendering time to know that there isn't actually a primary key constraint on this table.

**Comment by zzzeek** [comment]
it's also uncertain how this should work given that PARTITION BY is now a more common approach with PostgreSQL, and also I don't see mention here of how the columns themselves should be represented in the Table objects.   Ideally there is a round trip from DDL-> reflection so that would indicate that "users" and "books" above do not have an "id" or "date_created" column.   But then their .c collection *does* have to have it.  nothing like this is supported right now and this might be a very awkward change to the Table architecture.

**Comment by zzzeek** [comment]
I think "users" and "books" Table objects would have these columns but then each column needs its own "postgresql_inherits" attribute stated on it.   Then if I make a Table object with some columns, then add "inherits" or partitioning, does it pull in the columns from that other Table?  

I think we would in fact need to have Table subclasses in the Postgresql dialect to accommodate this fully.

**Comment by zzzeek** [comment]
this has never been asked for
