### ISSUE TITLE
create_all() should check for other schema constructs (i.e. indexes, others ?)

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#1993]
**Migrated issue, originally created by Anonymous**

Demo code:

    from sqlalchemy import *
    from sqlalchemy.ext.declarative import declarative_base
    eng=create_engine('sqlite:///:memory:')
    Base = declarative_base(bind=eng)
    class User(Base):
      __tablename__ = 'users'
      id = Column(Integer, primary_key=True)
      name = Column(String)
    Base.metadata.create_all()
    ix=Index('user_by_name', User.name)
    Base.metadata.create_all()
    print eng.execute('select * from sqlite_master').fetchall()
    ix.create()
    print eng.execute('select * from sqlite_master').fetchall()

Output:

    [u'users', u'users', 2, u'CREATE TABLE users (\n\tid INTEGER NOT NULL, \n\tname VARCHAR, \n\tPRIMARY KEY (id)\n)')]((u'table',)
    [u'users', u'users', 2, u'CREATE TABLE users (\n\tid INTEGER NOT NULL, \n\tname VARCHAR, \n\tPRIMARY KEY (id)\n)'), (u'index', u'user_by_name', u'users', 3, u'CREATE INDEX user_by_name ON users (name)')]((u'table',)

**Comment by zzzeek** [comment]
also related to #527

**Comment by zzzeek** [comment]
create_all() is [documented](https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.MetaData.create_all) as creating all tables.  the `Index` is only a supplementary object to a `Table` and is not included in what `create_all()` does.   real world use cases use alembic for this kind of case.
