### ISSUE TITLE
get_sequence_names

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2056]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

one for the sprints

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Added reflection method :meth:`.Inspector.get_sequence_names`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1881
