### ISSUE TITLE
document isolation_level fully

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2487]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

seems to be missing from the create_engine() docs, also should likely have its own section in "working with engines and connections", and definitely needs to list out the four values we have.

**Comment by zzzeek** [comment]
we have an ORM section in https://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#session-transaction-isolation and we just need a paragraph added to https://docs.sqlalchemy.org/en/latest/core/connections.html#using-transactions at this point.

**Comment by zzzeek** [comment]
this forgot to get closed, we have an in-depth section on isolation at https://docs.sqlalchemy.org/en/14/core/connections.html#setting-transaction-isolation-levels-including-dbapi-autocommit
