### ISSUE TITLE
annotate all core/ORM generative methods with some standard notation referring to a "generative" glossary entry; specify return value

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2646]
**Migrated issue, originally created by foo foo ([@zimbabwe](https://github.com/zimbabwe))**

http://docs.sqlalchemy.org/ru/latest/core/expression_api.html#sqlalchemy.sql.expression.Insert

The documentation for the values() call isn't clear about what it returns. Apparently it returns a new Insert object, with the provided values arguments associated with it. Connection.excecute() should then be called on this returned value. The passed-in values are not attached, or "fixed" to the insert object itself, but to a new one that values() instantiates and returns.

The documentation isn't clear on this and the examples don't show it being used in this way. 

Simply listing the method's return type would be sufficient but adding an additional explanation, or showing this usage in the examples, would be helpful as well.

**Comment by zzzeek** [comment]
hey there, 2021 here.   We will be approaching this as we provide for full pep-484 support, no need for this to be its own thing.
