### ISSUE TITLE
document bindparam() vs. literal()

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2688]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

I'm seeing a lot of SO answers come out doing this:

    select([some_value).<someop> <something else>](bindparam('some_name',))

when they should be using `literal()`.   Let's beef up the docs for bindparam() and literal() to be fully cross-referenced and explain the difference.   Let's also make this clear in `BindParam`, that it really has these *two* public constructor functions.

**Comment by zzzeek** [comment]
this is an old issue and I don't really know what it's even referring towards.   bindparam() and literal() act pretty differently so they can use whichever they want.
