### ISSUE TITLE
stacklevel for SAWarning about Unicode types

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2707]
**Migrated issue, originally created by Domen Kožar ([@iElectric](https://github.com/iElectric))**

When passing strings to a Unicode type, sqlalchemy complains:
lib/python2.7/site-packages/SQLAlchemy-0.8.0-py2.7-linux-x86_64.egg/sqlalchemy/engine/default.py:455: SAWarning: Unicode type received non-unicode bind param value.

Those warnings are hard to debug. Changing stacklevel to 17 reports the stack correctly, but I'm not sure if stacklevel is dynamic.

**Comment by zzzeek** [comment]
this issue is practically obsolete as python 3 makes a much harder distinction between bytes and text.    Ideally this would just be an exception and users having trouble tracking it down should be turning warnings into exceptions.
