### ISSUE TITLE
clarify what should happen with query(A).select_from(A).join(B.a)

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2722]
**Migrated issue, originally created by Anonymous**

(original reporter: rbu) We had quite a hard time figuring out the JOIN order as generated by a query(A).join(B) statement. All examples in the documentation have A as left and B as right side. Apparently though, when giving an explicit criterion as query(A).join(B.a), B will be the left side even when adding a select_from.

Details:

    # surprising
    >>> print DBSession.query(User.id).outerjoin(Track.user)
    SELECT user.id AS user_id 
    FROM track LEFT OUTER JOIN user ON user.id = track.user_id
    
    # bug?
    >>> print DBSession.query(User.id).select_from(User).outerjoin(Track.user)
    SELECT user.iduser AS user_id 
    FROM track LEFT OUTER JOIN user ON user.id = track.user_id
    
    # expected
    >>> print DBSession.query(User.id).outerjoin(User.tracks)
    SELECT user.iduser AS user_id 
    FROM user LEFT OUTER JOIN track ON user.id = track.user_id

This magic ordering based on the explicit criterion given should be covered in the documentation, but we did not find such note.

**Comment by zzzeek** [comment]
2021, we have an error for a related case:

    stmt = select(A).join_from(A, B.a)

    explicit from clause mapped class A->a does not match left side of relationship attribute B.a


but the above case still acts the same and does not warn:

     stmt = select(A).select_from(A).join(A, B.a)

    SELECT a.id, a.data 
    FROM b JOIN a ON a.id = b.a_id

The select_from(A) and .join(B.a) are essentially contradictory, and the join(B.a) supersedes the select_from().

this also ignores select_from():

    stmt = select(A).join(B.a).select_from(A)

that said, overall, the statement is equivalent to this:

   stmt = select(A).select_from(A).select_from(B.__table__.join(A.__table__))

this is SQLAlchemy's behavior throughout its releases; the FROM list builds itself up where a JOIN that involves two FROM objects will supersede that of the individual FROM objects.

**Comment by zzzeek** [comment]
trying to see how we could warn on this, because we can see the above pattern when we calc the from list, how do we know what to warn on for this:

    stmt = select(A).select_from(B).select_from(A).select_from(B.__table__.join(A.__table__))

so say the rule is, "warn when an item in the select_from() list is being replaced by a join() object, where that object is on the right side of the join".   that would be seen as noise in the above.

seems like we just need to document that select_from() does not actually imply the ordering of the FROM list if more specific JOINs are added to the construct.

**Comment by zzzeek** [comment]
the new documentation format plus that we can just talk about select() alone now makes it simple to document this.
