### ISSUE TITLE
have math operators + and - do something reasonable for dates and timedeltas (or raise)

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2769]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

We can get support for "date2 - date1" pretty easily for most backends at this point, now that we have full control of operators.   The most straightforward way might be just to create a SQL construct called "DateSubtract" or something like that, returning an Interval as the return type.

**Comment by zzzeek** [comment]
im not sure why i reopened this, if and when there are plans for this to actually be done, we would revisit.  however as there is almost never any call for this feature and it would also be enormously complicated it's unlikely it would be worth it.
