### ISSUE TITLE
Support for IF EXISTS/IF NOT EXISTS DDL constructs

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2843]
**Migrated issue, originally created by Rémy Roy ([@remyroy](https://github.com/remyroy))**

IF EXISTS and IF NOT EXISTS are already part of many DBMSs DDL vocabulary. They have many use cases which are highly useful in some situations.

For instance, creating a table if it does not already exists or dropping a column if it exists.

It would be nice to have those directives with standard SQLAlchemy DDL methods. I guess they could be implemented using the native support for DBMSs that support them or with some introspection for those that do not.

**Comment by mark-stopka** [comment]
Any update on this?

**Comment by RamonWill** [comment]
Hi Mike,

As discussed, i'm happy to work on this. So from what i can gather from looking at this issue and the surrounding duplicates is that IF EXISTS and IF NOT EXISTS needs to be implemented for CreateIndex/DropIndex/CreateTable/DropTable/AddConstraint/DropConstraint.

Do you have an idea of how you would like this to be implemented? 

My naive approach would be to maybe utilise the method `create_all()`'s `checkfirst`  parameter in some way. Once the program reaches a creation method i.e. `visit_create_table` then i can somehow use checkfirst to create the exists clause. I can also maybe add this approach to the Index and Constraint parameters. To be honest i do need to look into it more and create a working example but just curious as to your ideas if any.

Thank you,
Ramon

**Comment by zzzeek** [comment]
hi @RamonWill  -

at the moment I didn't have any way to integrate this into the actual create/drop sequence that's emitted from ddl.py.   That would be difficult to achieve and is also unnecessary as we do our own "checkfirst".

I think what we cover here is to make the option available to the create/drop constructs themselves, and then implement it in compiler.py.    the parameter would not be used by "checkfirst":
```

from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import Table
from sqlalchemy.schema import CreateTable
from sqlalchemy.schema import DropTable

m = MetaData()
t = Table('t', m, Column('q', Integer))


print(CreateTable(t, if_not_exists=True))

print(DropTable(t, if_exists=True))
```

a patch for the beginning of the above looks like:

```diff
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index 925441539..a640e0d5a 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -3755,7 +3755,10 @@ class DDLCompiler(Compiled):
         text = "\nCREATE "
         if table._prefixes:
             text += " ".join(table._prefixes) + " "
-        text += "TABLE " + preparer.format_table(table) + " "
+        text += "TABLE "
+        if create.if_not_exists:
+            text += "IF NOT EXISTS "
+        text += preparer.format_table(table) + " "
 
         create_table_suffix = self.create_table_suffix(table)
         if create_table_suffix:
@@ -3855,7 +3858,12 @@ class DDLCompiler(Compiled):
         )
 
     def visit_drop_table(self, drop, **kw):
-        return "\nDROP TABLE " + self.preparer.format_table(drop.element)
+        if drop.if_exists:
+            text = "\nDROP TABLE IF EXISTS "
+        else:
+            text = "\nDROP TABLE "
+
+        return text + self.preparer.format_table(drop.element)
 
     def visit_drop_view(self, drop, **kw):
         return "\nDROP VIEW " + self.preparer.format_table(drop.element)
diff --git a/lib/sqlalchemy/sql/ddl.py b/lib/sqlalchemy/sql/ddl.py
index 67c11f6c7..133ad54cf 100644
--- a/lib/sqlalchemy/sql/ddl.py
+++ b/lib/sqlalchemy/sql/ddl.py
@@ -368,6 +368,17 @@ class _CreateDropBase(DDLElement):
         """
         return False
 
+class _CreateBase(_CreateDropBase):
+    def __init__(self, element, if_not_exists=False, **kw):
+        self.if_not_exists = if_not_exists
+        super(_CreateBase, self).__init__(element, **kw)
+
+
+class _DropBase(_CreateDropBase):
+    def __init__(self, element, if_exists=False, **kw):
+        self.if_exists = if_exists
+        super(_DropBase, self).__init__(element, **kw)
+
 
 class CreateSchema(_CreateDropBase):
     """Represent a CREATE SCHEMA statement.
@@ -402,13 +413,14 @@ class DropSchema(_CreateDropBase):
         super(DropSchema, self).__init__(name, **kw)
 
 
-class CreateTable(_CreateDropBase):
+class CreateTable(_CreateBase):
     """Represent a CREATE TABLE statement."""
 
     __visit_name__ = "create_table"
 
     def __init__(
-        self, element, bind=None, include_foreign_key_constraints=None
+        self, element, bind=None, include_foreign_key_constraints=None,
+        if_not_exists=False
     ):
         """Create a :class:`.CreateTable` construct.
 
@@ -424,7 +436,7 @@ class CreateTable(_CreateDropBase):
          .. versionadded:: 1.0.0
 
         """
-        super(CreateTable, self).__init__(element, bind=bind)
+        super(CreateTable, self).__init__(element, bind=bind, if_not_exists=if_not_exists)
         self.columns = [CreateColumn(column) for column in element.columns]
         self.include_foreign_key_constraints = include_foreign_key_constraints
 
@@ -549,7 +561,7 @@ class CreateColumn(_DDLCompiles):
         self.element = element
 
 
-class DropTable(_CreateDropBase):
+class DropTable(_DropBase):
     """Represent a DROP TABLE statement."""
 
     __visit_name__ = "drop_table"

```

now it might get more complicated when individual dialects have different syntaxes here and the compiler may need to add new methods like "render_if_exists()" or something like that.   the work here is getting a baseline of what the six major databases support and then getting it implemented for all the constructs we have right now.

thanks!

**Comment by RamonWill** [comment]
Hey @zzzeek ,
Thanks for the above guidance. I have looked further into implementing as per above I may have to use render_if_exists as CREATE TABLE/INDEX IF EXISTS is different for SQL Server. 
A proposal i had in mind was to add an attribute to [Dialects Compiler Classes](https://github.com/sqlalchemy/sqlalchemy/blob/d5c89a541f5233baf6b6a7498746820caa7b407f/lib/sqlalchemy/engine/default.py#L49) (and the dialects that inherit from it) called supports_exists_table, supports_exists_index, supports_exists_constraint.

using Create table in your example, i would then do something like the following:
```diff
         text = "\nCREATE "
         if table._prefixes:
             text += " ".join(table._prefixes) + " "
-        text += "TABLE " + preparer.format_table(table) + " "
         text += "TABLE "
+        if create.if_not_exists and self.dialect.supports_exists_table: #<<<<<< 
+            text = self._render_table_if_not_exists(text, table)
         text += preparer.format_table(table) + " "
```

In terms of support for EXISTS/ IF NOT EXISTS here is what i found
**PostgreSQL**:
  Table: Yes version >=9.1. [CREATE TABLE IF NOT EXISTS...] AND [DROP TABLE IF EXISTS...]
  Index: Yes version >= 9.5. [CREATE INDEX IF NOT EXISTS...] AND [DROP INDEX IF EXISTS...]
  Constraint: [DROP Constraint IF EXISTS...]
**MySQL**:
  Table: Yes. [CREATE IF NOT EXISTS...] AND [DROP IF EXISTS...]
  Index: No.
  Constraint: No.
**Mariadb**:
  Table: Yes. [CREATE TABLE IF NOT EXISTS...] AND [DROP TABLE IF EXISTS...]
  Index: Yes. [CREATE INDEX IF NOT EXISTS...] AND [DROP INDEX IF EXISTS...]
  Constraint: Yes. [DROP Constraint IF EXISTS...], ADD [CONSTRAINT [symbol]] FOREIGN KEY  [IF NOT EXISTS]
**SQLite**:
  Table: Yes.
  Index: Yes.
  Constraint: No.
**Microsoft SQL Server**:
  Table: Yes BUT it is different that the others for IF NOT EXISTS. [DROP TABLE IF EXISTS...]
  Index: Yes BUT it is different that the others for IF NOT EXISTS.  AND [DROP INDEX IF EXISTS...]
  Constraint: [DROP Constraint IF EXISTS...]
**Oracle**:
  Table: Yes. [CREATE TABLE [IF NOT EXISTS]...] AND [DROP TABLE [IF EXISTS]...]
  Index: Yes. [CREATE INDEX [IF NOT EXISTS]...] AND [DROP INDEX [IF EXISTS] ... ON table]
  Constraint: No.

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **master** branch:

**Support IF EXISTS/IF NOT EXISTS for DDL constructs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2321
