### ISSUE TITLE
document table.constraints

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2902]
**Migrated issue, originally created by Anonymous**

I was trying to temporarily disable foreign keys for replication, but for the life of me couldn't find how to get the set of ForeignKeyConstraint objects from either Inspector, MetaData, or Table, for the longest time. There's nothing on it from google.

Perhaps it should be exposed in the docs. Are there any reason it is private?

**Comment by jvanasco** [comment]
All three have docstrings now:

* https://docs.sqlalchemy.org/en/14/core/metadata.html?#sqlalchemy.schema.Table.constraints
* https://docs.sqlalchemy.org/en/14/core/metadata.html?#sqlalchemy.schema.Table.indexes
* https://docs.sqlalchemy.org/en/14/core/metadata.html?#sqlalchemy.schema.Table.foreign_keys

Safe to close, @zzzeek ?

**Comment by CaselIT** [comment]
Fine for me
