### ISSUE TITLE
loader strategies at lazy load time + potential assoc proxy tie-in

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#2982]
**Migrated issue, originally created by Ezra Epstein ([@eepstein](https://github.com/eepstein))**

I've encountered a use case where being able to override the default fetch strategy of the underlying relationships would come in handy.

In this case the underlying relationships are both lazy - a one-to-many (backref) to an intermediate join table, followed by a to-one to the target table for the association.  There are good reasons for each to be lazy "joins" (separate select statement required).

However, when the association_proxy is accessed I would like to indicate that the second relationship should be fetched eagerly using an (inner) join.   Without that the association_proxy ends up giving rise to the N+1 select problem.

I do have some work-arounds that make use of the org Query APIs.  Would be very nice, however, to be able to do this directly via a mapped attribute.

Thanks for considering it.  (Or clarifying what I may be doing wrong if this is already a feature!)

**Comment by zzzeek** [comment]
at this point, for the general problem of setting loader options on instances, we have #3037 .    if and when #3037 happens we can look into adding some kind of method on the association proxy to do this, which would be trivial.
