### ISSUE TITLE
extensibility for ORM evaluator

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3162]
**Migrated issue, originally created by eevee ([@eevee](https://github.com/eevee))**

Current problem I'm having is that it doesn't know how to evaluate `op("&")`, but from the looks of it, it also won't understand hybrid properties (which would seem to exist for exactly this purpose!) or custom operators or custom `ClauseElement` subclasses.  There doesn't seem to be any way to extend it at all, and it's barely been updated since it was written.

**Comment by zzzeek** [comment]
I know eight years later you're probably super excited to know I just implemented something for this, so you can pull out your old python 2 code from mercurial and ...well port it to python 3 first , and then use this great new feature!  so we dont have to see this issue staring at the bottom of the list anymore :)

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement python_impl to custom_op for basic ORM evaluator extensibility** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3481
