### ISSUE TITLE
query heuristic inspection system

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3225]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

given issues like #3223 and the openstack issues with model_query(), here's a sketch of an idea:

```
@event.listens_for(EventedQuery, "before_compile", retval=True)
def append_order_by(new_query):
    
    if inspect(new_query).selects_against(MyClass).has_any():
        for insp in inspect(new_query).selects_against(MyClass).all_aliases():
            new_query = new_query.order_by(insp.entity.whatever)
    return new_query

```

with this extension we'd need to identify specific use cases (since we see them all the time anyway) and add them to the docs of this extension as covered use cases.  So the docs here need lots of recipes and they need to be tested.

**Comment by zzzeek** [comment]
this issue is completely superseded by the approach we've now made in #4472 along with 6930dfc032c3f9f474e71a (unticketed? ) which provides a comprehensive hook to intercept 2.0-style ORM select() constructs as well as to be able to add filtering criteria (which is what everyone needs) generically.
