### ISSUE TITLE
effectively no documentation for get_children / the visitors module

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3295]
**Migrated issue, originally created by kenko ([@kenko](https://github.com/kenko))**

... even though traversing parts of a query is necessary for getting horizontal sharding right (and is even exhibited in one of the examples).

**Comment by zzzeek** [comment]
visitors is documented at the API level, which is as good as lots of what's in Python std lib: https://docs.sqlalchemy.org/en/13/core/visitors.html?highlight=visitors#module-sqlalchemy.sql.visitors
