### ISSUE TITLE
Return a namedtuple for inserted_primary_key

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3314]
**Migrated issue, originally created by v ([@vr2262](https://github.com/vr2262))**

Hello,

It's a bit annoying that the inserted_primary_key is a list instead of something with some useful metadata. If it were a namedtuple instead, a user could access the keys by name in addition to the existing method (by index).

The documentation for namedtuple even recommends usage like this:

*Named tuples are especially useful for assigning field names to result tuples returned by the csv or sqlite3 modules*

(from [https://docs.python.org/3/library/collections.html#collections.namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple))

For what it's worth, psycopg2 allows for namedtuple cursors:
[http://initd.org/psycopg/docs/extras.html#namedtuple-cursor](http://initd.org/psycopg/docs/extras.html#namedtuple-cursor)

**Comment by zzzeek** [comment]
we have everything in place for this now as the inserted_primary_key structure is generated in the compiler where the work is cached.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Return Row for CursorResult.inserted_primary_key** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2735
