### ISSUE TITLE
Naming conventions example should use columns_0_name

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3345]
**Migrated issue, originally created by Thomas Tanner ([@ttanner](https://github.com/ttanner))**

The example
http://docs.sqlalchemy.org/en/latest/core/constraints.html#configuring-constraint-naming-conventions

```
convention = {
  "ix": 'ix_%(column_0_label)s',
  "uq": "uq_%(table_name)s_%(column_0_name)s",
  "ck": "ck_%(table_name)s_%(constraint_name)s",
  "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
  "pk": "pk_%(table_name)s"
}

```
should be changed to   "ck": "ck_%(table_name)s_%(column_0_name)s",
Otherwise unnamed constraints (for example, Boolean) raise

sqlalchemy.exc.InvalidRequestError: Naming convention including %(constraint_name)s token requires that constraint is explicitly named.

**Comment by jvanasco** [comment]
This should be solved by https://github.com/sqlalchemy/sqlalchemy/issues/4784, which adds a new `type_ck` naming convention for type-bound classes (Boolean, Enum).

**Comment by zzzeek** [comment]
yeah this is a duplicate of that one at this point
