### ISSUE TITLE
relationship comparisons to objects with None don't render IS NULL

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3373]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

e.g.:

    session.query(Address).filter(Address.user == User(id=None))

will produce:

    SELECT address.id AS address_id, address.user_id AS address_user_id,
    address.email_address AS address_email_address
    FROM address WHERE ? = address.user_id
    (None,)

This have to be fixed for all the relationship filter conditions, including filter() with both == and !=, with_parent(), etc.

see also #3371, which adds a warning for these.

**Comment by zzzeek** [comment]
no plans to do this until someone cares
