### ISSUE TITLE
add CreateDatabase() / DropDatabase() DDL object

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3382]
**Migrated issue, originally created by Unknown Name ([@984958198](https://github.com/984958198))**

Only in this way to create:

from sqlalchemy import create_engine
from sqlalchemy.engine.url import make_url

url = mysql://root:root@localhost:3306/wiki20?charset=utf8
engine = create_engine(url, echo=True)
database=make_url(url).translate_connect_args().get('database')
if database:
        engine.connect().execute("create database if not exists %s"%database)

**Comment by zzzeek** [comment]
there's really no reason for this construct as it is all DB specific in any case , and creating it would imply the whole range of DDL.py checking if the DB exists or not and all that and it would be a big job to actually get it right in terms of integrating with the creation / dropping of tables, sequences, etc.    if someone is motivated to put the effort into this, we can reopen
