### ISSUE TITLE
support new Oracle 12c OFFSET / TOP N

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3543]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

Let's support at least a subset of https://oracle-base.com/articles/12c/row-limiting-clause-for-top-n-queries-12cr1 to fulfill LIMIT/OFFSET.

This is a big enough deal that I'd like to at some point get an Oracle 12c CI environment going.

There should be a manual flag to select either style, and if set to None it will auto-select based on detected Oracle version.

**Comment by CaselIT** [comment]
@zzzeek I think this was done in 1.4 as part of fetch/offset
