### ISSUE TITLE
make session / core (?) docs more clear about SAVEPOINT / ROLLBACK TO SAVEPOINT / RELEASE mapping to begin/rollback/commit

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3550]
**Migrated issue, originally created by Jean-Sébastien Suzanne ([@jssuzanne](https://github.com/jssuzanne))**

See http://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#using-savepoint.

A save point can be released, it is not a commit or rollback. Or in the documentation, the ``begin_nested`` must be committed or rollbacked.

**Comment by zzzeek** [comment]
the behavior of begin_nested()/ rollback()/ commit() and their relationship to the RELEASE and ROLLBACK TO SAVEPOIINT instructions is documented at https://docs.sqlalchemy.org/en/14/orm/session_transaction.html#using-savepoint for the ORM.    For Core the docs are still fairly vague about it, documented at https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.Connection.begin_nested .   will add a little bit to NestedTransaction now.
