### ISSUE TITLE
figure out how to support all of PG's bizarro SETOF, RECORD, etc. types w/ emphasis on JSON fucntions

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3566]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

that is, all the functions in http://www.postgresql.org/docs/9.4/static/functions-json.html need to be possible without building subclasses of functions.

**Comment by connorlanewhite** [comment]
@zzzeek 
Hey Mike - given the relative age of this issue (and its status as being both pre-migration as well as milestone 1.5) - I wanted to check in on it.

Is the recommended approach still as prescribed earlier (basically variants on the answer from 4 years ago), or has some progress been made on these items.

Thank you!
Lane

**Comment by zzzeek** [comment]
> @zzzeek
> Hey Mike - given the relative age of this issue (and its status as being both pre-migration as well as milestone 1.5) - I wanted to check in on it.
> 
> Is the recommended approach still as prescribed earlier (basically variants on the answer from 4 years ago), or has some progress been made on these items.
> 
> Thank you!
> Lane

unfortunately no progress as of yet, in master /1.4 there are major changes to the archtecture of FROM clauses coming which will likely impact these recipes.    A lot of these PG functions are under the umbrella of what they refer to as "object relational" functions which are outside the normal bounds of what SQL is expected to do.      An approach for these recipes can be contributed by someone but overall I want to make sure this approach covers as much of PG's "object relational" model as possible, which means, it has to be planned in as broad a way as possible.   I welcome contributors who have long term motivation to stay with the feature through it's completion and suppor phase and are OK with having many weeks/ months of back and forth which is what this one would take.

**Comment by connorlanewhite** [comment]
Totally makes sense - thanks so much for the update

**Comment by CaselIT** [comment]
Another pg only feature (I think)

A specific construct for postgres row valued expressions. Example
```sql
select *
from some_table
where some_table is not null
```
This query will return all the rows where all columns are not null.

Current workaround is to use a `sa.column` or a `sa.literal_column` to represent the table in the where, since `sa.table` does not work with the comparison. 

Postgresql documentation: https://www.postgresql.org/docs/12/functions-comparison.html after the tip note.

Also, to render `not (some_table is null)`, `self_group` needs to be used, since `not(a is b)` is transformed to `a is not b` by sqlalchemy.
In this case it's not the same since `not (some_table is null)` returns all the rowswhere at least a column is not null, while `some_table is not null` returns all the rows where all columns are not null.

Consolidating from #5256

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement support for functions as FROM with columns clause support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2484

**Comment by zzzeek** [comment]
hey folks!

making some progress here.   First off, both SQLite and Oracle also have table valued functions.   that's what these are called, more or less.    Oracle's syntax is predictably awkward but good news, the API I have working for Postgresql works just the same way for Oracle which is a good initial test for how the API looks.

Here's one that shows off a bunch of features:

```python

        a = table("a", column("id"), column("refs"))
        b = table("b", column("id"), column("ref"))

        unnested = (
            func.unnest(a.c.refs)
            .named_table_valued("unnested", with_ordinality="ordinality")
            .alias("unnested")
        )

        stmt = (
            select(
                a.c.id, a.c.refs, unnested.c.unnested, unnested.c.ordinality
            )
            .outerjoin(unnested, true())
            .outerjoin(
                b,
                unnested.c.unnested == b.c.ref,
            )
        )
       print(stmt)
```

that one prints:

```sql
            SELECT a.id, a.refs, unnested.unnested, unnested.ordinality 
            FROM a 
            LEFT OUTER JOIN unnest(a.refs) 
            WITH ORDINALITY AS unnested(unnested, ordinality) ON true 
            LEFT OUTER JOIN b ON unnested.unnested = b.ref

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement support for functions as FROM with columns clause support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2497

**Comment by zzzeek** [comment]
Hi all -

I'd like to thank everyone waiting up to six years for us to get this done.   Please review the new docs at https://docs.sqlalchemy.org/en/14/tutorial/data.html#tutorial-functions-table-valued (general tutorial) and 
https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#postgresql-table-valued-overview (PostgreSQL-specific use cases) to see all that's new, and hopefully everything in the above cases is covered.   These syntaxes also work on SQLite for a few of its functions as well as with user-defined table valued functions created on SQL Server, and Oracle .

**Comment by ruicore** [comment]
Thanks a lot, this is very helpful 😊
