### ISSUE TITLE
Use column expressions with session.bulk_update_mappings, session.bulk_insert_mappings

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3568]
**Migrated issue, originally created by Fabio Sussetto ([@fabiosussetto](https://github.com/fabiosussetto))**

```
mappings = [
   {'id': 1, 'balance': User.balance + 10},
   {'id': 2, 'balance': User.balance + 20}
]
db.session.bulk_update_mappings(User, mappings)
```

On 1.0.9 this fails with the following error:
```
can't adapt type 'BinaryExpression' [SQL: 'UPDATE "user" SET balance=%(balance)s WHERE "user".id = %(user_id)s'] [parameters: ({'user_id': 1, 'balance': <sqlalchemy.sql.elements.BinaryExpression object at 0x10d153be0>}
```

Is this supported?

Thanks!

**Comment by zzzeek** [comment]
I continue to hope that the "bulk_" features can actually be removed at some point in favor of direct use of insert()/update() as I think these features were misguided (unless someone can make the case why they are very useful), so for now no plans to add new features.
