### ISSUE TITLE
add public accessor for the pool._timeout value

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3689]
**Migrated issue, originally created by Thomas Briles**

(edited by mike) in the form of a read-only Python descriptor with documentation.

**Comment by sqla-tester** [comment]
**Irina Delamare** has proposed a fix for this issue in the **master** branch:

**add public accessor for the pool._timeout value** https://gerrit.sqlalchemy.org/1057

**Comment by sqla-tester** [comment]
**irina** has proposed a fix for this issue in the **master** branch:

**Fixes #3689** https://gerrit.sqlalchemy.org/1099

**Comment by sqla-tester** [comment]
**Irina Delamare** has proposed a fix for this issue in the **master** branch:

**Provide public accessor for Pool.timeout().** https://gerrit.sqlalchemy.org/1099
