### ISSUE TITLE
Document that `load_only()` implies `undefer()`

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3757]
**Migrated issue, originally created by Adrian ([@thiefmaster](https://github.com/thiefmaster))**

I just noticed that my column property which is defined with `deferred=True` is automatically undeferred if I list the column in the `load_only()` option. While this makes sense (I wouldn't specify it if I didn't want it to be loaded) I just noticed it by coincidence - the name "load *only*" sounds like it just restricts what's loaded but doesn't enable additional loading.

An extra sentence in the `load_only` docs could clarify this...

**Comment by CaselIT** [comment]
does anyone still uses oracle 8? It's eol since 2006.
Maybe we could close this?

**Comment by RamonWill** [comment]
Hey Guys,
I can create a PR for this. I replicated this locally and checked the docs just to double check if it was still outstanding.

Regards,
Ramon

**Comment by CaselIT** [comment]
I don't think anyone is working on this at the moment, so feel free to work on it 👍
