### ISSUE TITLE
Accessing the history of a synonym attribute   (either raise or resolve for attribute)

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3777]
**Migrated issue, originally created by Konsta Vesterinen ([@kvesteri](https://github.com/kvesteri))**

Consider the following code:
```
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base, synonym_for

Base = declarative_base()


class User(Base):
    __tablename__ = 'user'
    _name = sa.Column(sa.String, primary_key=True)
    
    @synonym_for('_name')
    @property
    def name(self):
        return self._name

u = User()
sa.inspect(u).attrs['name'].history
```

Currently this raises the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sqlalchemy/orm/state.py", line 684, in history
    PASSIVE_NO_INITIALIZE)
  File "/sqlalchemy/orm/state.py", line 309, in get_history
    return self.manager[key].impl.get_history(self, self.dict, passive)
AttributeError: '_ProxyImpl' object has no attribute 'get_history'
```

I think it would make more sense if this either

1. Would not raise an AttributeError but rather show the history of the property that the synonym property is pointing at (in this case the history of ``_name``)
2. Raise an error with more descriptive error message

This is just a minor issue for me and its easy to find a workaround for this.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement SynonymProperty.get_history()** https://gerrit.sqlalchemy.org/1055
