### ISSUE TITLE
consider rollup of __clause_element__() onto ClauseElement

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3816]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

tried to do this for #3802 late in 1.1 but it's too critical if someone is doing a while loop, and here's at least one example:  https://github.com/albertov/py-mailing/blob/a81d71f35b3c04de75cca48eb82b0b85bbaaf915/mailing/models/util.py#L45.  there's no reason that person would have done that besides copying our code.   additionally, if we put `__clause_element__()` onto ClauseElement, there's a lot of internal checks that should also be optimized.   

other more far-out tricks would be:

1. return a copy of the object that raises some assertion on `__clause_element__()`.  though this is expensive

2. deprecate `__clause_element__()` and replace with some totally other method.   But we'd need almost-forever backwards compat for calling upon `__clause_element__` also in this case.  It sort of suggests all the places where we do `hasattr(obj, '__clause_element__')` should become some other kind of single call that perhaps we can put into cutils.   Detecting `__clause_element__` itself would then raise some kind of deprecation warning.

**Comment by zzzeek** [comment]
the plan in 2.0 is:

we don't actually need `ClauseElement`, what we are looking for is `ColumnElement`.   There will be two accessors "has_column_element" and "column_element".    The refactor here is going along well with this idea and I hope to greatly simplify the large number of argument checking functions.

**Comment by zzzeek** [comment]
This is happening now via the work seen in #4617 .   We are going to entirely change the system by which objects get inspected in Core so we can push out `__clause_element__()` as part of this process.   `__clause_element__()`may or may not be able to emit a deprecation warning here, depending on how things go.

**Comment by zzzeek** [comment]
New plan, is that `__clause_element__()` is just fine, and in fact we can expand how it is used so that we get a clause element from ORM mapped aliases and classes too.   This will be part of the coercion system moving through review at https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1244/.

closing this issue as 'wontfix'
