### ISSUE TITLE
include single table inh discriminator for query.update() / query.delete()?

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3903]
**Migrated issue, originally created by Ollie Rutherfurd ([@orutherfurd](https://github.com/orutherfurd))**

ie session.query(Subclass).update(...) updates all rows in the table vs just Subclass rows.

Script attached that demonstrates the issue.  There are two rows, only one should be updated, but both are updated.

----------------------------------------
Attachments: [test_update.py](../wiki/imported_issue_attachments/3903/test_update.py)

**Comment by ericman93** [comment]
any update?

**Comment by zzzeek** [comment]
dupe of #5018 which has some more detail and a unit test.   both issues were independently milestoned to 1.4, oddly enough.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Support extra / single inh criteria with ORM update/delete** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2201
