### ISSUE TITLE
synchronize_session='fetch' should, you know, 'fetch' the actual data

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#3992]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

synchronize_session='fetch' currently runs the SELECT and then expires the objects.   If we're running a SELECT, we should be fetching the actual keys that changed and populating, not expiring.    perhaps we'd call this "eager_fetch" in case we're worried about side effects, but I think just switching "fetch" is fine, the term "fetch" implies something's being fetched.

**Comment by zzzeek** [comment]
I can't see myself working on this for now.  a lot of work and folks aren't really asking for it.
