### ISSUE TITLE
Docs: responsive sphinx theme

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#4008]
**Migrated issue, originally created by mixmastamyk ([@mixmastamyk](https://github.com/mixmastamyk))**

Hi,

Been trying to read the docs on a mobile device and it is quite difficult because the sidebar takes up most of the viewport.  Happens on a narrow desktop window also, when trying to work on code and have docs open at the same time.

A few lines of responsive css could move or hide the sidebar for narrow viewports.  Alternatively there are responsive Sphinx themes, like Alabaster.

Thanks for the hard work,

----------------------------------------
Attachments: [Screenshot_20170613-222752.png](../wiki/imported_issue_attachments/4008/Screenshot_20170613-222752.png)

**Comment by zzzeek** [comment]
certainly, having some real CSS pros come in and fix all of my homegrown stuff would be awesome, as long as they could maintain some of the usability stuff like the side menubar staying fixed on the left side (for desktop at least, on mobile the menubar should probably go away) and highlighting the current section.    It looks like Sphinx does the same thing: http://www.sphinx-doc.org/en/master/usage/quickstart.html but it's jumping around for me on firefox/linux whereas mine is rock solid.    I really need desktop to be as perfect as possible.      So if someone can help here, great, but I don't have plans to try this alone at the moent.
