### ISSUE TITLE
implement SQLite INSERT ON CONFLICT variant of insert()

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#4010]
**Migrated issue, originally created by Michael Bayer ([@zzzeek](https://github.com/zzzeek))**

SQLIte-specific variant implemented similarly to Postgresql's ON CONFLICT, MySQL ON DUPLICATE KEY

original issue #960

**Comment by zzzeek** [comment]
annoyingly, SQLite has the same "INSERT..ON CONFLICT" *and* "INSERT OR REPLACE" confusion that MySQL has - as we are standard on doing the "ON CONFLICT" version , clarify that's what we should be doing here.

**Comment by zzzeek** [comment]
it looks like SQlite only got ON CONFLICT a year ago, good thing we waited here !  :)   http://sqlite.1065341.n5.nabble.com/UPSERT-available-in-pre-release-td101550.html

**Comment by mfreeborn** [comment]
Just registering my interest here for this to be formally supported in the public API. It would appear that SQLite has chosen the same syntax as Postgres, and SQLAlchemy already supports upsert in the [Postgres dialect](https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#insert-on-conflict-upsert).

My very sketchy work around tries to hand-build the correct SQL and looks something like this:

```python
# Result is a Table object
stmt = Item.insert().values([{"id": 1, "value": "Pending"}, {"id": 2, "value": "Positive"}])

# compile the statement so that we can get all the bound parameters
# the raw SQL should looking something like: INSERT INTO items (id, value) VALUES ((?, ?), (?, ?))
compiled_statement = stmt.compile(dialect=sqlite.dialect())

# binds is a mapping of {parameter_name -> BindParameter} e.g. {"id_1": BindParameter("id_1", value=1, type_=Integer)} 
binds = compiled_statement.binds

# we want the str SQL statement to edit
original_statement = compiled_statement.string

# and we will hand build our custom UPSERT statement
upsert_stmt = "ON CONFLICT (id) DO UPDATE SET value=excluded.value"

# before putting it all together
stmt = original_statement + " " + upsert_stmt

# however, we need to rebind all the parameters, so first we must replace all those "?"s with proper parameter names
for param_name in binds.keys():
    stmt = stmt.replace("?", f":{param_name}", 1)

# and then convert our str back into a SQLAlchemy TextClause and re-bind the parameters
stmt = text(stmt).bindparams(*binds.values())

# and finally execute it
with engine.connect() as conn:
    conn.execute(stmt)
```

I'm sure we can all agree that is a very unpleasant hack, what with all the string manipulation involved. That said, it works, and in reality I've refactored the process into several discrete steps so the code is re-usable.

I'd be interested to know if anyone has managed anything a bit slicker in the absence of it being supported by the SQLAlchemy library.

**Comment by RamonWill** [comment]
Hi @mfreeborn ,
I've listed this issue on my TODO, upon inspection i believe that the implementation of the Upsert would be similar to that of PostgreSQL as you alluded to above. I might be able to come up with implementing this use case.

@zzzeek : to resolve this issue i am thinking that i could create a method in the SQLite dml [Insert class](https://github.com/sqlalchemy/sqlalchemy/blob/55843040b1b4e1493e27051f5125fa322a43dc31/lib/sqlalchemy/sql/dml.py#L771)?

 i.e. Creating a method called `sql.dml.Insert.on_conflict_do_update(...)` similar to ([Insert.on_conflict_do_update ](https://github.com/sqlalchemy/sqlalchemy/blob/55843040b1b4e1493e27051f5125fa322a43dc31/lib/sqlalchemy/dialects/postgresql/dml.py#L50)for the PostGreSQL dialect).

**Comment by zzzeek** [comment]
> 
> @zzzeek : to resolve this issue i am thinking that i could create a method in the SQLite dml [Insert class](https://github.com/sqlalchemy/sqlalchemy/blob/55843040b1b4e1493e27051f5125fa322a43dc31/lib/sqlalchemy/sql/dml.py#L771)?
> 
> i.e. Creating a method called `sql.dml.Insert.on_conflict_do_update(...)` similar to ([Insert.on_conflict_do_update ](https://github.com/sqlalchemy/sqlalchemy/blob/55843040b1b4e1493e27051f5125fa322a43dc31/lib/sqlalchemy/dialects/postgresql/dml.py#L50)for the PostGreSQL dialect).

yes for the moment the various ON CONFLICT varieties are being addressed as individual INSERT constructs that are per-dialect.

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **master** branch:

**Implement upsert for SQLite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2230

**Comment by ericman93** [comment]
> yes for the moment the various ON CONFLICT varieties are being addressed as individual INSERT constructs that are per-dialect.

any ETA for this feature? I saw most of the dialect already implement `on_conflict_do_nothing`

**Comment by CaselIT** [comment]
No, and it's not currently being worked on.

Since it's also missing an issue I'll open one

**Comment by zzzeek** [comment]
> No, and it's not currently being worked on.
> 
> Since it's also missing an issue I'll open one

im rereading comments, and not following.   

what are we adding?

**Comment by CaselIT** [comment]
A single implementation of the various insert/on_conflit/etc to avoid having to use the different insets from the dialects.

IIRC we talked about trying to unify sqlite and pg that are similar in funcionality

**Comment by CaselIT** [comment]
created https://github.com/sqlalchemy/sqlalchemy/issues/8321 as a 2.x issue

**Comment by zzzeek** [comment]
> A single implementation of the various insert/on_conflit/etc to avoid having to use the different insets from the dialects.
> 
> IIRC we talked about trying to unify sqlite and pg that are similar in funcionality

oh that, that's not for anytime soon we have lots of other things to work on before that
