### ISSUE TITLE
add "PARTITION BY" and "STATS SAMPLE PAGES" to mysql reflected options

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#4038]
**Migrated issue, originally created by chebee7i ([@chebee7i](https://github.com/chebee7i))**

Some keyword kwargs like 'mysql_partition_by' and 'mysql_stats_sample_pages' are not reflected and stored in kwargs.

```
import sqlalchemy as sa
m = sa.MetaData()

t = sa.Table('ti', m,
    sa.Column('id', sa.Integer),
    sa.Column('amount', sa.DECIMAL(7, 2)),
    sa.Column('tr_date', sa.Date),
    mysql_engine='InnoDB',
    mysql_partition_by='HASH( MONTH(tr_date) )',
    mysql_partitions='6'
)

engine = ...
t.create(engine)
m2 = sa.Metadata(bind=engine, reflect=True)
assert 'mysql_partition_by' in m2.tables['ti'].kwargs  # AssertionError
```

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **master** branch:

**Add support for Partitioning and Sample pages on mysql reflected options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2185

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **main** branch:

**Add support for Partitioning and Sample pages on mysql reflected options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4033
