### ISSUE TITLE
sqlalchemy.engine.reflection.Inspector.get_columns : documentation error for SQLAlchemy 1.2.0b1

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#4051]
**Migrated issue, originally created by Rudolf Cardinal ([@RudolfCardinal](https://github.com/RudolfCardinal))**

In SQLAlchemy 1.2.0b1, it's possible for `sqlalchemy.engine.reflection.Inspector.get_columns` to return the following dict as one of its results: 

    {
        'type': VARCHAR(length=255),
        'nullable': False,
        'default': None,
        'name': 'device_id',
        'comment': 'Source tablet device ID'
    }

The docs at http://docs.sqlalchemy.org/en/latest/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_columns seem to be out of date for this in that (a) `attrs` is documented as part of the returned dictionary, but is absent in this real example; (b) `comment` is new and undocumented.

**Comment by CaselIT** [comment]
I think it should be fixed in #5064

**Comment by zzzeek** [comment]
you can add "Fixes: #4051" to that PR's commit message

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Support inspection of computed column** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1679

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Support inspection of computed column** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1679

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Support inspection of computed column** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1796
