### ISSUE TITLE
Allowing schema name to be specified for table construction

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#4127]
**Migrated issue, originally created by Philip Martin ([@pmart123](https://github.com/pmart123))**

I want to propose a change to the table expression class so it can accept a schema name in its constructor. I believe this is useful when building queries that are referencing table objects with different schema names. My proposed enhancement would follow the same convention used in the Table class by allowing for:

```python
from sqlalchemy import column, table, MetaData, Table, Column, CHAR

# this currently generates a TypeError due to invalid keyword argument
t = table('bar', column('x'), schema='foo')

# same API as Table class
t = Table('bar', MetaData(), Column('x', CHAR(2), primary_key=True), schema='foo)
```

**Comment by zzzeek** [comment]
this was added in #5309.
