### ISSUE TITLE
Adding column comment to the column __repr__

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#4138]
**Migrated issue, originally created by Jorge Sierra**

under schema.py
class Column(SchemaItem, ColumnClause):
function def __repr__(self):

add     

 if self.comment:
     kwarg.append('comment')

to the keywords for creating a __repr__ of a Column

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Add ``comment`` attribute to :class:`.Column` ``__repr__`` method.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1872

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add ``comment`` attribute to :class:`.Column` ``__repr__`` method.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1873
