### ISSUE TITLE
PostgreSQL domain with array reflected to sqltypes.NULLTYPE

### ISSUE THREAD

**Issue by jsynowiec** [sqlalchemy/sqlalchemy#4377]
I have two pgsql domains: `isoweekday` that is based on INT and `isoweekdays` that is an array of the former. Both domains add some checks like no duplicate values, no empty list, only values from <1, 7> range.

```sql
CREATE DOMAIN isoweekday AS INT
CHECK(...);

CREATE DOMAIN isoweekdays AS isoweekday[]
CHECK(...);
```

I've created custom types, like so:

```py
class ISOWeekDayDomain(types.UserDefinedType, types.Integer):
    def get_col_spec(self, **kwargs):
        return 'isoweekday'


class ISOWeekDaysDomain(types.UserDefinedType, ARRAY):
    def __init__(self, **kwargs):
        if 'item_type' not in kwargs:
            kwargs['item_type'] = ISOWeekDayDomain

        super(ISOWeekDaysDomain, self).__init__(**kwargs)

    def get_col_spec(self, **kwargs):
        return 'isoweekdays'
```

and then used them to define a column:

```py
Column(
    ISOWeekDaysDomain, nullable=False, server_default=text('ARRAY[1,2,3,4,5,6,7]')
)
```

Creating migrations using Alembic went well, and it created the following statement:

```py
    op.add_column(
        u'config',
        sa.Column(
            'dow',
            ISOWeekDaysDomain(),
            server_default=sa.text(u'ARRAY[1, 2, 3, 4, 5, 6, 7]'),
            nullable=False,
        ),
    )
```

After applying migrations on the database, I'm getting the following warning:
```
sqlalchemy/dialects/postgresql/base.py:2683: SAWarning: Did not recognize type 'isoweekday[]' of column 'dow'
```

Running alembic yields a new database migration that alters the previously added column with `sqltypes.NULLTYPE`.

```py
op.alter_column(u'tent_crawling_config', 'dow',
           existing_type=sa.NullType(),
           nullable=False,
           existing_server_default=sa.text(u'ARRAY[1, 2, 3, 4, 5, 6, 7]'))
```

The `domains` dictionary passed to `_get_column_info` contains both created domains and during execution it enters the [dialects/postgresql/base.py#L2677](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/base.py#L2677) block.

What am I missing? How to register my custom types that map domains so the reflection API recognises them?

I'm using `SQLAlchemy==1.2.14` and PostgreSQL `v11`

**Comment by jsynowiec** [comment]
The problem seems to be that there is some special treatment for arrays

```py
        # strip '[]' from integer[], etc.
        attype = attype.replace('[]', '')

        is_array = format_type.endswith('[]')
```

but it's not applied after domain handling in the while loop, so if the domain `attype` ends with `[]` the `coltype` will be `None`.

**Comment by jsynowiec** [comment]
Thanks! I was already exploring this yesterday. As I've mentioned in the https://github.com/sqlalchemy/sqlalchemy/pull/4380#issuecomment-442331469, after adding my types to the `ischema_names` it now seems to work. At least there are no warnings and Alembic is not generating wrong migrations.

**Comment by zzzeek** [comment]
> Managing domains is another topic. One have to write the SQL manually and execute it against the database. I've started experimenting with `_CreateDropBase`, `compiles` decorator and visitors but I'm just exploring some ideas. @zzzeek can you give me some pointers where to look? I would eventually like to have Alembic generating migrations for PSQL domains.

so if you really want to get into it, it would be nice if Alembic had first class support for PG domains.   as Im sure you know, just to get through the day you can emit `op.execute("ALTER ...")` in any way you'd like to create and alter domains, however to get real operations for them as well as autogenerate support, for starters you can go through the series of steps at first at https://alembic.sqlalchemy.org/en/latest/api/operations.html#operation-plugins and then for autogenerate at https://alembic.sqlalchemy.org/en/latest/api/autogenerate.html#autogen-custom-ops .   If you can get all those things working, that paves the way for them to be included in Alembic fully.
