### ISSUE TITLE
add detail to schemas section, including the logic of "schema agnostic"

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4387]
from https://github.com/sqlalchemy/alembic/issues/519, we are looking at this section:  https://docs.sqlalchemy.org/en/latest/core/metadata.html#specifying-the-schema-name

some of the verbiage that needs to be adapted:

> SQLAlchemy's convention is that table metadata is agnostic of the default schema in the database if the schema_name is not given. To work correctly, table reflection must assume the same convention, meaning, when it reflects database tables, if those tables are in the default schema, the "schema" parameter is not filled in. Without this assumption, all kinds of use cases become un-symmetrical.

as well as detail on how reflection works with schemas, maybe this should be a new section, need to draw from https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#remote-schema-table-introspection-and-postgresql-search-path as well without being too postgresql specific.

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Fixes: #4387** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3104

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Fixes: #4387** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3258

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **main** branch:

**Add new sections regarding schemas and reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3104

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **rel_1_4** branch:

**Add new sections regarding schemas and reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3318
