### ISSUE TITLE
Silent errors when executing multiple SQL statements

### ISSUE THREAD

**Issue by ch41rmn** [sqlalchemy/sqlalchemy#4389]
When using the `.execute(query)` method, where the query is a string representing multiple statements, sometimes the execution silently fails half-way through, leading to some rather bizarre debugging scenarios.

Minimum reproducible example:
```
$ python
Python 3.7.1 (default, Oct 23 2018, 14:07:42) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy as sa
>>> engine = sa.create_engine('mssql://{user}:{pass}@{server}/{db}?driver=ODBC+Driver+17+for+SQL+Server')
>>> with engine.begin() as conn:
...     conn.execute("""
...     select 1 as foo into #foo;
... 
...     insert into #foo (foo) values
...         (2), (3);
... 
...     update #foo
...     set
...         bar = 5;
...     -- expect failure here! the 'bar' column does not exist
... 
...     insert into #foo (foo) values
...         (4), (5);
...     """)
...     
...     results_proxy = conn.execute('select * from #foo')
...     print(results_proxy.fetchall())
... 
<sqlalchemy.engine.result.ResultProxy object at 0x10ab89b38>
[(1,), (2,), (3,)]
```

As per example above, the multi-statement execute should have failed at the third statement (update), because the column doesn't exist, and raised `pyodbc.ProgrammingError`. Instead, the execution silently terminates, and the results reflect this.

Have tested this against Microsoft SQL Server 2016, yet to test against other RDBMS.

Systems used:
- OSX 10.13.6 + Conda 4.5.11
- Python 3.7.1
- ODBC driver: `msodbcsql17/17.2.0.1` via Homebrew
- Microsoft SQL Server 2016
```
$ pip list
Package    Version   
---------- ----------
certifi    2018.10.15
pip        18.1      
pyodbc     4.0.24    
setuptools 40.6.2    
SQLAlchemy 1.2.14    
wheel      0.32.3
```

**Comment by zzzeek** [comment]
Hi there -

SQLAlchemy does not suppress driver exceptions.  When you see this kind of behavior, the first thing to do is try it with the raw driver.  No exception is generated:

```python

import pyodbc

conn = pyodbc.connect("DRIVER={ODBC Driver 13 for SQL Server};Server=mssql2017,1433;Database=test;UID=scott;PWD=tiger^5HHH")

cursor = conn.cursor()
cursor.execute(
    """
    select 1 as foo into #foo;

    insert into #foo (foo) values
        (2), (3);

    update #foo
    set
        bar = 5;
    -- expect failure here! the 'bar' column does not exist

    insert into #foo (foo) values
        (4), (5);
    """
)
cursor.close()

cursor = conn.cursor()
cursor.execute('select * from #foo')
print(cursor.fetchall())
```

also, it's not a common practice to send multiple statements with semicolons as it is known to behave differently across drivers, as we see is the case here.

**Comment by zzzeek** [comment]
output from the above script is the same:

    [(1, ), (2, ), (3, )]

**Comment by dsedivec** [comment]
For posterity, and because I hit this problem _again_ today, note that the error seems "silent" because SQL Server is returning multiple result sets, and you have to go through each of them (with [DBAPI's `cursor.nextset()`](https://peps.python.org/pep-0249/#id29)) until you get to the one that raises an error.  Only at that point will you get an exception raised by PyODBC.

[SQLAlchemy does not support multiple result sets](https://docs.sqlalchemy.org/en/20/core/connections.html#multiple-result-sets), so there is no way to see these sort of errors when you execute multiple statements like this through SQLAlchemy.  If you have to use multiple SQL statements within a single `execute` on MSSQL, use "raw" DBAPI connections and cursors.

**Comment by CaselIT** [comment]
nothing has changed, this use case keeps not being supported, so you will need to use the cursor to get the single results and the errors.
Note that even when using the dbapi directly you have to call nextset until you get the error, so it's not really something surprising that sqlalchemy will not raise an error in that case
