### ISSUE TITLE
Cannot iterate over sets from class level hybrid properties since 1.1.0

### ISSUE THREAD

**Issue by tonyfinn** [sqlalchemy/sqlalchemy#4391]
Since upgrading to 1.1.0, I have some code that returns a set from a hybrid property that fails when the property is read at class level and the set is then iterated over. Here's a sample case to reproduce the problem:

```python
from sqlalchemy.ext.hybrid import hybrid_property


class RegularProperty:
    def __init__(self, set_value):
        self.set_value = set_value

    @property
    def set_property(self):
        return self.set_value


class UsesHybridProperty:
    default_set_value = {1, 2, 3}
    def __init__(self, set_value):
        self.set_value = set_value

    @hybrid_property
    def set_property(self):
        if isinstance(self, type):
            return self.default_set_value
        else:
            return self.set_value


regular_instance = RegularProperty({1, 2, 3})
hybrid_instance = UsesHybridProperty({1, 2, 3})

print(list(regular_instance.set_property))
print(list(hybrid_instance.set_property))
print(list(UsesHybridProperty.set_property))
```

Expected output (returned in 1.0.19):

```
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
```

Actual output (1.3.0b1, but affects all versions from 1.1.0+)

```
[1, 2, 3]
[1, 2, 3]
Traceback (most recent call last):
  File "hybrid_issue_poc.py", line 31, in <module>
    print(list(UsesHybridProperty.set_property))
  File "/home/e/.local/share/virtualenvs/api-v1ub1sIx/lib/python3.7/site-packages/sqlalchemy/sql/operators.py", line 411, in __getitem__
    return self.operate(getitem, index)
  File "/home/e/.local/share/virtualenvs/api-v1ub1sIx/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 181, in operate
    return op(self.comparator, *other, **kwargs)
  File "/home/e/.local/share/virtualenvs/api-v1ub1sIx/lib/python3.7/site-packages/sqlalchemy/sql/operators.py", line 411, in __getitem__
    return self.operate(getitem, index)
  File "/home/e/.local/share/virtualenvs/api-v1ub1sIx/lib/python3.7/site-packages/sqlalchemy/ext/hybrid.py", line 1146, in operate
    return op(self.expression, *other, **kwargs)
TypeError: 'set' object does not support indexing
```

As far as I can tell, this is because the exposed descriptor implements `__getitem__` and not `__iter__` while `__set__` implements `__iter__` but not `__getitem__`, so python attempts to simulate iteration with `__getitem__` and `__len__`, but when the hybrid property descriptor passes the getitem call through to the proxied set it fails.

**Comment by zzzeek** [comment]
OK so this would have happened as a result of #3653 documented at https://docs.sqlalchemy.org/en/latest/changelog/migration_11.html#hybrid-properties-and-methods-now-propagate-the-docstring-as-well-as-info.

But what I don't understand is the use case.   The purpose of `@hybrid_property` invoked at the class level is to return a SQL expression.  If you only need to return a Python set, then you should use a regular descriptor like a `@classproperty` which you can use in sqlalchemy.util.classproperty as well as in answers like [this](https://stackoverflow.com/a/5192374/34549)

**Comment by zzzeek** [comment]
the old `@hybrid_property` was pretty much what `@classproperty` still is.  But yeah hybrids are strictly for SQL expressions at the class level, thanks for following up.
