### ISSUE TITLE
deprecation warnings to implement for 1.3, plus new deprecations

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4393]
There's a lot of things that are documented as deprecated but don't emit a warning, and other things that are vaguely called "legacy" and we need to get over that,  as I want to start moving towards getting rid of these things in future major versions, these need to be fully deprecated with warnings emitted on use, tests to confirm they all emit a warning:

* engine.convert_unicode, String.convert_unicode, String.uniciode_errors - these flags are oriented around Python 2 legacy behavior where DBAPIs would crash if they were to be sent a Python u'' string, as well as where Python u'' were desired from result sets.   The behaviors surrounding "force" and "encoding_errors" have to do with people who were using legacy MySQL databases that are storing strings with invalid or inconsistent encodings; these users should use a custom workaround String datatype if they still need to deal with essentially corrupted databases.   All DBAPIs now accommodate Python u'' directly, and in the case where the u'' is to have non-ascii data, the Unicode datatype is used.   Additionally, the entire universe of "convert_unicode" is meaningless in Python 3 where there are no non-Unicode string objects.

* SessionExtension._adapt_listener(), MapperExtension._adapt_listener(), ConnectionProxy, etc.  these should have been emitting a warning from day one, this will also handle Session.extension parameters etc. emit a warning
  
* pool.manage thing.  deprecate this in 1.3, warn, nobody is using it (lib/sqlalchemy/pool/dbapi_proxy.py).

* sqlalchemy.databases package - this was how you imported dialects a decade ago, nobody knows it's there.  should emit a deprecation warning

* engine threadlocal strategy, this is a holdover from 0.1, also there's some issues here that should be "wontfix" related to it

* sqlalchemy.ext.serializer - deprecate, have it warn.   this module is never used and also doesn't work completely as the structures it creates are too complicated for Python pickling of various implementations to handle.

* sqlalchemy.event.legacy - this is a system by which we can change the signatures for event listener functions while allowing the old one to still work, and a few event APIs had some changes since the system was first released.  It has an elaborate system of documenting itself in sphinx but it seems like it doesn't emit warnings?   make sure this emits warnings when deprecated arguments are used + tests

* session._enable_transaction_accounting, how can this not be emitting a warning?  this
  flag is there to suit exactly one specific person back in 2007. if that code is still 
  even running it's probably stuck on Python 2.4.   

* legacy_is_orphan - the documentation doesn't even show it as deprecated, it's from 0.8,
  should have been whacked long ago and can even be taken out in a 1.x series like 1.4

* something a little more controversial.  connection pool weakref returning connection to pool, e.g. when ConnetionFairy is gc'ed.   this use case is quite ancient, and took many years of bugs, tests, and complexity to get right - it really should be gone.  ideally, eventually, if a ConnectionFairy is weakrefed, it should likely emit a warning forever, but it should *not* return the connection to the pool or try to close it or anything, it should let the whole thing go, because a correctly written application shouldn't be losing connections in any case.  This logic was part of the culture of Python before there were context managers or even decorators,where the pattern of "open a thing, use it, close it" had no idiomatic pattern.  now it does and everyone should be using them.    So the change is, when ConnectionFairy is weakref'ed, do the same thing it does for now, but emit a warning, say hey you let this connection get dropped, tell them this will be deprecated.

* see if the same is possible with ResultProxy?  e.g. they have a result with results pending and they drop it.  that is also no good.  should warn and shouldn't clean up after them eventually.

* engine.table_names(), engine.has_table() -> these should be deprecated for a long 
  time in favor of the inspector.  Please also move has_table to inspector which doesn't
  have it, then add corresponding methods has_temp_table(), has_temp_view(), has_view().
  that will be great.
  
* do a grep for things marked as "deprecated" or superseded and add real deprecation
  warnings, such as collection.linker, query.with_lockmode (so old! put warning 
  in LockmodeArg.parse_legacy_query)
  
* joinedload_all(), etc_all(), these are already documented as deprecated in 0.9, these
  need to warn
  
* defer->addtl_attrs, that's weird

* ORMJoin->join_to_left, I think we can just remove this in 1.3, I dont think it was
  ever used
  
* attributes->init_collection w/ instancestate, this doesnt even need to be anything,
  inspect() returns the object, doesn't matter, just take that doc out
  
* all the dialect stuff: sybase, zxjdbc, adodbapi - these should warn when they are 
  invoked.  firebird, ehhhh, not sure.  that's still a working dialect just not one 
I want to deal with.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue:

**Add deprecation warnings to all deprecated APIs** https://gerrit.sqlalchemy.org/1048

**Comment by zzzeek** [comment]
work begins at https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1048

**Comment by zzzeek** [comment]
ComparableProperty should be fully deprecated as it is replaced by hybrid
