### ISSUE TITLE
it does not support djangorestframework

### ISSUE THREAD

**Issue by thumb0422** [sqlalchemy/sqlalchemy#4407]
-models.py

    class ProductInfo(Base):
           __tablename__ = 'product_info'
           id = Column(Integer, primary_key=True)

-views.py

     class ProductInfoViewSet(viewsets.ModelViewSet):
           queryset = session.query(ProductInfo)
           serializer_class = ProductInfoSerializer

when it run,  error:  AttributeError: 'Query' object has no attribute 'model'
Does sqlalchemy  support DRF?

**Comment by zzzeek** [comment]
looks like you need https://github.com/dealertrack/djangorest-alchemy.     there's no django support in sqlalchemy directly.  thanks!
