### ISSUE TITLE
GenericTypeCompiler not present in API documentation

### ISSUE THREAD

**Issue by tswast** [sqlalchemy/sqlalchemy#4411]
When I search https://docs.sqlalchemy.org/en/latest/genindex.html for GenericTypeCompiler, I don't find anything.

It is referenced from https://docs.sqlalchemy.org/en/latest/core/internals.html#sqlalchemy.engine.default.DefaultDialect.type_compiler but I'd have to dig into the source code to find out additional details about this class.

Is it valid to override GenericTypeCompiler in dialect implementations such as in https://github.com/mxmzdlv/pybigquery/pull/32 ?

**Comment by zzzeek** [comment]
sure, GenericTypeCompiler is fine and likely necessary for custom dialects.    I don't know that every single bit that custom dialects use is in the published docs.  this would need to be in https://github.com/sqlalchemy/sqlalchemy/blob/master/doc/build/core/internals.rst
