### ISSUE TITLE
psycopg2 wheel package will be renamed to psycopg2-binary

### ISSUE THREAD

**Issue by kataev** [sqlalchemy/sqlalchemy#4419]
> psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

We will making something with it?

Maybe recommend install `sqlalchemy[postgresql_psycopg2binary]` instead `sqlalchemy[postgresql]`?

**Comment by zzzeek** [comment]
that's alraedy been added in 5469dd1b8f1 for #4306

**Comment by zzzeek** [comment]
which...it seems like what you referred to at the top.   so, still not sure what the question is :)

**Comment by kataev** [comment]
Yep, this is it.
I apologize for disturbing.
