### ISSUE TITLE
should non-primary mapper loader options inspect the primary mapper for attributes not locally present?

### ISSUE THREAD

**Issue by ariloulaleelay** [sqlalchemy/sqlalchemy#4421]
Load options ignored for non_primary mapper:

```python
#!/usr/bin/env python

import sqlalchemy

from sqlalchemy import Column, ForeignKey, Integer, create_engine, orm
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Parent(Base):
    __tablename__ = 'parents'
    id = Column(Integer, primary_key=True)


class Child(Base):
    __tablename__ = 'children'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey(Parent.id), nullable=False, index=True)
    parent = orm.relationship(Parent, backref='children')


aliased_child = sqlalchemy.select([Child]).alias()
mapped_child = orm.mapper(Child, aliased_child, non_primary=True)

engine = create_engine('sqlite://', echo=True)
Base.metadata.create_all(engine)
DBSession = orm.sessionmaker(bind=engine)
session = DBSession()

parent = Parent(id=0)
child = Child(id=1, parent_id=0)
session.add_all([parent, child])
session.commit()

# this works
session.expunge_all()
child = session.query(Child).options(orm.noload('*')).first()
child.parent  # no parent (ok)

# this is not
session.expunge_all()
child = session.query(mapped_child).options(orm.noload('*')).first()
child.parent  # parent lazily loaded (not ok)
```

**Comment by zzzeek** [comment]
ah, this is not what I thought.

**Comment by zzzeek** [comment]
so, your non-primary mapper doesn't have "parent".   If you add that, it works:

```
mapped_child = orm.mapper(
    Child, aliased_child, non_primary=True,
    properties={
        'parent': orm.relationship(Parent)
    })

```


I don't see, at the moment, how it would be possible for the loader options to examine both the non-primary and the primary mapper at the same time.  for example if you said "joinedload('parent')", that raises an attribute error right now.  should it be looking at the primary mapper to figure these things out?   that's not possible without there being a relationship on the NP such that things like the join condition and all that can be worked out.

but there is the area of attributes that are on the object once loaded, which have loader behaviors that are essentially from the primary mapper, such as lazyload of parent.   even eager loaders that run on "secondary" could in theory work here, e.g. first query is against the NP mapper, then a "selectin" load runs against the primary mapper?   is that what someone would want?

**Comment by ariloulaleelay** [comment]
I use NP mapper to make row-limited relationship as described here:
https://docs.sqlalchemy.org/en/latest/orm/join_conditions.html#row-limited-relationships-with-window-functions

It looks like this
```python

class Answer(Base):
   ...
   question_id = Column(Integer, ForeignKey(Question.id))
   # there are some other relationships to authors, tags, comments etc.

class Question(Base):
   ...

partition = select([
    Answer,
    func.row_number().over(
        order_by=Answer.rating.desc(),
        partition_by=Answer.question_id
    ).label('index')
]).alias()

non_primary_mapper_for_answer = mapper(Answer, partition, non_primary=True)

Question.top_rated_answer = relationship(
    non_primary_mapper_for_answer,
    primaryjoin=and_(
        non_pirmary_mapper_for_answer.c.question_id == Question.id,
        non_pirmary_mapper_for_answer.c.index == 1
    )
)

```
So when i do ```session.query(Question).options(noload('*'), selectinload('top_rated_answer'))```
i get top_rated_answer and it's relationship attributes (eg. author) lazily loads when accessed. I found no way to set load strategy for them.

**Comment by zzzeek** [comment]
OK, first off the query there should be (using the documentation mappings):

```
for a1 in s.query(A).options(noload('*'), selectinload(A.partitioned_bs).noload('*')):
    for b in a1.partitioned_bs:
        assert 'some_data' not in b.__dict__

```

and it does not work, and this is *another* bug that is not what's originally shown here nor is it being fixed by the patch in #3348.

non primary mappers are definitely going away.  I will create a system by which a normal AliasedClass can be used instead.

**Comment by zzzeek** [comment]
OK sorry, in your case "author" is a relationship, noload('*') is only for relationships, I'm working on three things at once here let me try to get only correct statements on this ticket.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement relationship to AliasedClass; deprecate non primary mappers** https://gerrit.sqlalchemy.org/1059
