### ISSUE TITLE
allow relationship to AliasedClass and get rid of non primary mappers

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4423]
will replace #3348 #4422 #4421

taking the example from https://docs.sqlalchemy.org/en/latest/orm/join_conditions.html?highlight=partitioned#row-limited-relationships-with-window-functions , it would be mapped as:

```
class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    cs = relationship("C")


class C(Base):
    __tablename__ = 'c'
    id = Column(Integer, primary_key=True)
    b_id = Column(ForeignKey('b.id'))

partition = select([
    B,
    func.row_number().over(
        order_by=B.id, partition_by=B.a_id
    ).label('index')
]).alias()

partitioned_b = aliased(B, alias=partition)

A.partitioned_bs = relationship(
    partitioned_b,
    primaryjoin=and_(partitioned_b.a_id == A.id, partition.c.index < 10)
)

```

the non primary mapper has no queryable alias making it very difficult to query from, and additionally acts in this detached way vs. it's original mapped class that nobody needs (e.g. doesn't inherit properties).  AliasedClass already does the thing that people need from np mappers, which is, load the class from a different selectable.  all that is missing is for relationship to be able to point to it.  make that happen and non primary mappers can finally be removed.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement relationship to AliasedClass** https://gerrit.sqlalchemy.org/1059

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement relationship to AliasedClass; deprecate non primary mappers** https://gerrit.sqlalchemy.org/1059
