### ISSUE TITLE
StatementError.__str()__ does not obey contract of its superclass SQLAlchemyError.__str()__

### ISSUE THREAD

**Issue by piotr-dobrogost** [sqlalchemy/sqlalchemy#4430]
Looking at class `SQLAlchemyError` it seems that the idea is to return `unicode` string from `__str()__` method.
For example `__unicode()__` method [looks](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_0b1/lib/sqlalchemy/exc.py#L57-L58) like this:

```python
    def __unicode__(self):
        return self.__str__()
```
However `StatementError` class which inherits `__unicode()__` method from `SQLAlchemyError` class implements its own `__str()__` which returns `str` string not `unicode` string. This results in returning `str` string from `StatementError.__unicode()__` which is not right. Looking at implementation of `__str()__` in `StatementError` class it seems there is nothing which would prevent using `unicode` format string instead of `str` one when constructing return value thus resolving the issue.

All of the above is concerned with Python 2.

**Comment by piotr-dobrogost** [comment]
Well, I meant replacing
`return ' '.join(…`
with
`return u' '.join(…`
on line [328](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_0b1/lib/sqlalchemy/exc.py#L328) in `exc.py` so there would be no explicit use of type name.

We got exceptions from our own logging code which did not support objects returning something different than `unicode` object from `__unicode()__` method.

**Comment by Mekk** [comment]
My general testcase is sth like:
```
try:
    engine = sqlalchemy.create_engine("oracle://nobody:nopass@127.0.0.1")
    engine.connect()
except Exception as err:
    print(repr(str(err)))
    print(repr(unicode(err)))
```

On „english” settings it runs fine. But if you run it under
```
NLS_LANG=polish_poland.al32utf8
```
the result is
```
'(cx_Oracle.DatabaseError) ORA-12541: TNS:brak nas\xb3uchu\n'
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb3 in position 49: ordinal not in range(128)
```

(polish message for "TNS: no listener" is "TNS: brak nasłuchu", with "ł" letter present)

SImilar problem for various other errors.

**Comment by Mekk** [comment]
Small fix: example above was run under
```
NLS_LANG="polish_poland.EE8ISO8859P2"
```
(also interesting). under utf-8 result is a bit different
```
'(cx_Oracle.DatabaseError) ORA-12541: TNS:brak nas\xc5\x82uchu\n'
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 49: ordinal not in range(128)
```

**Comment by Mekk** [comment]
Of course problem is not Polish-specific. For example NLS_LANG=RUSSIAN_CIS.CL8MSWIN1251 gives
```
'(cx_Oracle.DatabaseError) ORA-12541: TNS:\xed\xe5\xf2 \xef\xf0\xee\xf1\xeb\xf3\xf8\xe8\xe2\xe0\xf2\xe5\xeb\xff\n'
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 41: ordinal not in range(128)
```

In general: Oracle error messages are encoded in NLS_LANG-derived encoding and frequently contain national characters. So to convert them to unicode, one must use connection encoding info to properly decode from (IIRC cx_Oracle provides one as conn.encoding)

**Comment by Mekk** [comment]
I am not sure which way of fixing this would align best with sqlalchemy (and be most consistent with othere databases). I can imagine:
- normalizing error message to unicode always on exception creation (on the border of the driver), and later implementing str via decoding to locale encoding (which need not be the same as database one, btw)
- simply saving encoding info into exception object (err.encoding) and implementing unicode via decoding str according to this attribute
- giving an option to provide separate str and unicode exception descriptions on exception creation (and using them in such a case)

**Comment by piotr-dobrogost** [comment]
> * giving an option to provide separate str and unicode exception descriptions on exception creation (and using them in such a case to implement **str** and **unicode**)

Example of this approach could be seen in the answer to [How can I raise an Exception that includes a Unicode string?](https://stackoverflow.com/q/29096702/95735) question at Stackoverflow where exception object can be constructed either with `unicode` or `str` message.

**Comment by piotr-dobrogost** [comment]
I'm sorry for confusion; original analysis was incorrect. I missed the fact that one of the arguments to `join()` is [set](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_0b1/lib/sqlalchemy/exc.py#L319) like this:
`        details = [self._message()]`
and as `_message()` returns `unicode` this makes later `join()` where it's used to also return `unicode`.
