### ISSUE TITLE
None column name produced for SQLite functional index on inspect

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4431]
which affects alembic see https://github.com/sqlalchemy/alembic/issues/523

```
from sqlalchemy import create_engine

e = create_engine("sqlite://")

e.execute("""
CREATE TABLE suppliers (
    id VARCHAR(20) NOT NULL,
    name VARCHAR, PRIMARY KEY (id)
)
""")

e.execute("""
CREATE INDEX supplier_name_idx ON suppliers (
replace(replace(replace(lower(name), '.', ''), ' ', ''), ',', ''));
""")

from sqlalchemy import inspect
print(inspect(e).get_indexes("suppliers"))

```

we get a warning when we do full reflection, but not just on the get_indexes call, and I think the index should raise a warning and be skipped like it is in Postgresql functional indexes, right now it produces a broken result:

```
$ python test.py 
[{'name': 'supplier_name_idx', 'column_names': [None], 'unique': 0}]

```

PG skips it with a warning:

```
/home/classic/dev/sqlalchemy/lib/sqlalchemy/dialects/postgresql/base.py:3271: SAWarning: Skipped unsupported reflection of expression-based index supplier_name_idx
  "expression-based index %s" % idx_name
[]

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Skip expression-based index reflection for SQLite** https://gerrit.sqlalchemy.org/1085

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_2** branch:

**Skip expression-based index reflection for SQLite** https://gerrit.sqlalchemy.org/1086
