### ISSUE TITLE
loader option error messages

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4433]
see if we can get every mistake here to make a clear error:

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs=[B()]))
s.commit()

```

case one:

```
(Pdb) !s.query(A, B).options(load_only(A.id, B.data))
*** sqlalchemy.exc.ArgumentError: Wildcard loader can only be used with exactly one entity.  Use Load(ent) to specify specific entities.

```

they don't see the wildcard.   Can we catch that and re-state, or can we detect this within load_only() and not defer() ?

```
(Pdb) !s.query(A).options(load_only('id', 'bs'))
<sqlalchemy.orm.query.Query object at 0x7f9c411a95f8>

```

doesn't raise.  why not?   it's wrong.   only if we call .all():

```
(Pdb) !s.query(A).options(load_only('id', 'bs')).all()
*** Exception: can't locate strategy for <class 'sqlalchemy.orm.relationships.RelationshipProperty'> (('deferred', False), ('instrument', True))

```

there's the error.  two levels of bad, first off, it should be, "undefer() only applies to column based attributes, does not apply to relationship attribute "bs"".    Secondly, like before, it should be stated in terms of load_only().

```
(Pdb) !s.query(A).options(load_only(A.id, B.data))
*** sqlalchemy.exc.ArgumentError: Can't find property 'data' on any entity specified in this Query.  Note the full path from root (Mapper|A|a) to target entity must be specified.

```

I just stated "data" is from "B", that's where it's from!   you need to say, "Attribute B.data is in terms of class "B", but this query has no entity "B"".  Also, "note full path from root mapper() must be speciied", please state the class, not the mapper

```
(Pdb) !s.query(A, B).options(load_only(A.id, B.data))
*** sqlalchemy.exc.ArgumentError: Wildcard loader can only be used with exactly one entity.  Use Load(ent) to specify specific entities.

```

same double issue again - the first level of error message should be, "can't use wildcard loader against multiple entities A, B; please use Load(A).undefer(), Load(B).undefer" - and then, wrong again, the error has to be in terms of load only (so thats two test cases)

```
(Pdb) !s.query(A).options(load_only(A.bs), subqueryload(A.bs).load_only("data"))
<sqlalchemy.orm.query.Query object at 0x7feef10a54e0>

```

this query "works" because the subqueryload wipes out the load_only(A.bs) - but this should raise immediately, like above 

amazingly, it doesnt' even work from Load(), just ignores it:

`(Pdb) !s.query(A).options(Load(A).load_only(A.bs), subqueryload(A.bs).load_only("data"))
`

all the mapper options need to be doing a check up front for the right kind of attribute, at least when they get sent to query.options().

problem exists in the other direction too:

```
(Pdb) !s.query(A).options(joinedload(A.data))
<sqlalchemy.orm.query.Query object at 0x7feef09b8828>
(Pdb) !s.query(A).options(joinedload(A.data)).all()
*** Exception: can't locate strategy for <class 'sqlalchemy.orm.properties.ColumnProperty'> (('lazy', 'joined'),)
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Improve error messages in the area of loader options** https://gerrit.sqlalchemy.org/1082
