### ISSUE TITLE
data become None when inserted

### ISSUE THREAD

**Issue by zhiyiZeng** [sqlalchemy/sqlalchemy#4439]
I'm using Sqlalchemy to insert some data. However, when inserted, the data would be converted into None automatically. But, when using Pymysql to insert data, it works fine. I have no clue at all. Need some help.

```python
def conntect_database():

    engine = create_engine('mysql+pymysql://XX:XX@localhost:3306/test?charset=utf8', pool_size=200)
    meta = MetaData(bind=engine, reflect=True)
    session_factory = orm.sessionmaker(bind=engine, autocommit=True)
    s = orm.scoped_session(session_factory)

    class Test:
        def __init__(self, test=None,):
            test = test

    tables = {
        'test': Test,
    }
    orm.Mapper(Test, meta.tables['test'])

    return s, engine, tables

new = tables['test'](test='test')
s.add(new)
s.flush()

```
I'm using Pycharm to debug. The result is as following:
![image](https://user-images.githubusercontent.com/20840761/51070846-ec728b00-1682-11e9-81ef-20d78d4cadc7.png)
![image](https://user-images.githubusercontent.com/20840761/51070922-3d36b380-1684-11e9-8a42-1669ba1385bf.png)

Here is Pymysql code.
```python

connection = pymysql.connect(host='localhost',
                             user='XX',
                             password='XX',
                             db='test',
                             charset='utf8',
                             cursorclass=pymysql.cursors.DictCursor)
with connection.cursor() as cursor:
    # Create a new record
    sql = "INSERT INTO `test` (`test`) VALUES (%s)"
    k = cursor.execute(sql, ('test',))

connection.commit()
print('yes')

```
Here is the result.
![image](https://user-images.githubusercontent.com/20840761/51070916-26905c80-1684-11e9-92ae-a8f461e0711e.png)

The environment is Python3.5, Windows10. Any help would be appreciated. The Version of Sqlalchemy is 1.1.15 and 1.2.15, both no luck.

**Comment by zzzeek** [comment]
> I'm using Sqlalchemy to insert some data. However, when inserted, the data would be converted into None automatically. But, when using Pymysql to insert data, it works fine. I have no clue at all. Need some help.
> 
> ```python
> def conntect_database():
> 
>     engine = create_engine('mysql+pymysql://XX:XX@localhost:3306/test?charset=utf8', pool_size=200)
>     meta = MetaData(bind=engine, reflect=True)
>     session_factory = orm.sessionmaker(bind=engine, autocommit=True)
>     s = orm.scoped_session(session_factory)
> 
>     class Test:
>         def __init__(self, test=None,):
>             test = test

this needs to be "self.test = test", can you try that?  otherwise you are not assigning to the instance, it's just doing nothing.

let me know if that works.

> 
>     tables = {
>         'test': Test,
>     }
>     orm.Mapper(Test, meta.tables['test'])
> 
>     return s, engine, tables
> 
> new = tables['test'](test='test')
> s.add(new)
> s.flush()
> ```
> 
> I'm using Pycharm to debug. The result is as following:
> ![image](https://user-images.githubusercontent.com/20840761/51070846-ec728b00-1682-11e9-81ef-20d78d4cadc7.png)
> ![image](https://user-images.githubusercontent.com/20840761/51070922-3d36b380-1684-11e9-8a42-1669ba1385bf.png)
> 
> Here is Pymysql code.
> 
> ```python
> connection = pymysql.connect(host='localhost',
>                              user='XX',
>                              password='XX',
>                              db='test',
>                              charset='utf8',
>                              cursorclass=pymysql.cursors.DictCursor)
> with connection.cursor() as cursor:
>     # Create a new record
>     sql = "INSERT INTO `test` (`test`) VALUES (%s)"
>     k = cursor.execute(sql, ('test',))
> 
> connection.commit()
> print('yes')
> ```
> 
> Here is the result.
> ![image](https://user-images.githubusercontent.com/20840761/51070916-26905c80-1684-11e9-92ae-a8f461e0711e.png)
> 
> The environment is Python3.5, Windows10. Any help would be appreciated. The Version of Sqlalchemy is 1.1.15 and 1.2.15, both no luck.

**Comment by zzzeek** [comment]
hope this helped your problem.

**Comment by zhiyiZeng** [comment]
still no luck. Thanks anyway.

**Comment by zhiyiZeng** [comment]
still no luck. Thanks anyway.

**Comment by zzzeek** [comment]
try following through the tutorial at https://docs.sqlalchemy.org/en/latest/orm/tutorial.html which illustrates a mapping pretty much the same as this one, this is very basic.

**Comment by zzzeek** [comment]
> Thanks, but I cannot open it because of Internet regulations. Are there any other tutorials I can use?

oh that's terrible.  it's part of this code.   can you read it here on github?   https://github.com/sqlalchemy/sqlalchemy/blob/master/doc/build/orm/tutorial.rst

**Comment by zhiyiZeng** [comment]
Yes!! That's what I need! I appreciate that very much.

**Comment by zzzeek** [comment]
if you download sqlalchemy.tar.gz at https://pypi.python.org/pypi/SQLAlchemy, the full HTML documentation is in the tar.gz file under doc/.

**Comment by zhiyiZeng** [comment]
It's really helpful, thank you again! :-)

**Comment by zzzeek** [comment]
can I ask what your country of origin is which imposes these regulations, as I need to know if a large chunk of my userbase can't read my documentation

**Comment by zhiyiZeng** [comment]
I'm currently in  C .....h.....i......n......a.
