### ISSUE TITLE
Creating a Unicode where-clause with N-prefix

### ISSUE THREAD

**Issue by villebro** [sqlalchemy/sqlalchemy#4442]
I'm not sure if this is a SqlAlchemy issue or something with the dialect/connector, but is there some way to force the query compiler to prefix a Unicode string with N for e.g. MSSQL? If a column has been defined as `UnicodeText` (also tried `NVARCHAR`, same result), one would expect a where clause on that column to be prefixed with an N for MSSQL. However, this doesn't automatically seem to happen, and I haven't been able to find any documentation on how to achieve this. Below is an example to illustrate the problem:

```python3
import sqlalchemy as sa
from sqlalchemy.sql import column, table

mssql_engine = sa.create_engine("mssql+pyodbc://XXX")

col = column('unicode_col', type_=sa.types.UnicodeText())
unicode_where_str = '🐍'

select = sa.select([col])
select = select.where(col == unicode_where_str)
select = select.select_from(table('tbl'))
print(select.compile(mssql_engine, compile_kwargs={'literal_binds': True}))
```

This yields
```sql
SELECT unicode_col 
FROM tbl 
WHERE unicode_col = '🐍'
```
while one would expect the unicode type to put an N-prefix on the where clause, like so:
```sql
SELECT unicode_col 
FROM tbl 
WHERE unicode_col = N'🐍'
```
Is there some way to either automatically get the N-prefix, or manually inject it, e.g. by using `TypeDecorator`?

**Comment by zzzeek** [comment]
you could use TypeDecorator.bind_expression (https://docs.sqlalchemy.org/en/latest/core/custom_types.html?highlight=bind_expression#sqlalchemy.types.TypeDecorator.bind_expression), however the database driver, e.g. pyodbc or pymssql, does this for you when the statement is executed.  What is your actual use case?

**Comment by zzzeek** [comment]
more appropriately it would be literal_processor()

**Comment by zzzeek** [comment]
well Im unable to show that the "N" makes any difference on Oracle *OR* SQL server.  can you please illustrate the problem you're having with SQL Server itself as well as what Python driver / database version you are using ?

**Comment by villebro** [comment]
I verified this on both MSSQL 2008R2 and 2017. Below I create a table on the 2017 instance (database has `SQL_Latin1_General_CP1_CI_AS` collation) with an `NVARCHAR` and `VARCHAR` column, insert the snake from the previous example (`U+1F40D`) both with and without N-prefixing into both columns:

<img width="448" alt="screenshot 2019-01-14 at 21 06 45" src="https://user-images.githubusercontent.com/33317356/51135516-e62b0d00-1842-11e9-81b1-4199bfd47182.png">

The select produces the following:

<img width="257" alt="screenshot 2019-01-14 at 21 06 52" src="https://user-images.githubusercontent.com/33317356/51135680-46ba4a00-1843-11e9-9a1c-900ad6c4de6b.png">

As can be seen, only the N-prefixed snake that was inserted into the `NVARCHAR` column turns up in its original shape. Interestingly running a select without N-prefixing is able to find the mutated snake, NOT the N-prefixed snake:

<img width="295" alt="screenshot 2019-01-14 at 21 41 40" src="https://user-images.githubusercontent.com/33317356/51136513-55a1fc00-1845-11e9-9cad-3caeff13715a.png">

<img width="259" alt="screenshot 2019-01-14 at 21 41 47" src="https://user-images.githubusercontent.com/33317356/51136530-5cc90a00-1845-11e9-8286-2946b473134a.png">

Running the same with N-prefixing turns up the correct snake. I ran the same via SSMS on 2008R2 and also on Superset (Python 3.6.4 with SQLAlchemy==1.2.16, pymssql==2.1.4) with similar results:

<img width="1110" alt="screenshot 2019-01-14 at 21 32 06" src="https://user-images.githubusercontent.com/33317356/51136000-19ba6700-1844-11e9-891a-59854d872d1a.png">

The underlying query from Superset rendered by SQLAlchemy:
<img width="894" alt="screenshot 2019-01-14 at 21 32 23" src="https://user-images.githubusercontent.com/33317356/51136013-1e7f1b00-1844-11e9-9735-74ff9b3b967e.png">

I read somewhere that MSSQL 2019 is the first version of MSSQL to introduce native UTF8 support (🤣🤣🤣), so the N-prefix might be optional nowadays, but on older versions it seems to be necessary.

**Comment by zzzeek** [comment]
OK my SQL Server here is the linux one, this is the version string:  Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64) \n\tSep 14 2018 13:53:44 \n\tCopyright (C) 2017 Microsoft Corporation\n\tDeveloper Edition (64-bit) on Linux (CentOS Linux 7 (Core))

The database looks like I created it as: "CREATE DATABASE test;" e.g. i didn't specify any collation.   

For these string statements you are making, are you running those in with python and the driver as well?  or is this cut-and-paste into a GUI ?   i wonder if that affects things ?

**Comment by zzzeek** [comment]
I can't get it to fail, here's more or less the same test, py3k/py2k and pymssql/pyodbc, passes 

```
#! coding: utf-8

import pymssql

conn = pymssql.connect(
    user="scott", password="tiger^5HHH", host="mssql2017:1433", database="test"
)


cursor = conn.cursor()

cursor.execute(
    """
CREATE TABLE t (
    id INT,
    x NVARCHAR(255) NULL,
    y VARCHAR(255) NULL
)
"""
)

cursor.execute("DELETE FROM t")
cursor.execute("INSERT INTO t (id, x, y) VALUES (1, N'réveillé', N'réveillé')")
cursor.execute("INSERT INTO t (id, x, y) VALUES (2, 'réveillé', 'réveillé')")

# note in Python 2, these are bytestrings.  pymssql doesn't accept
# u"" on py2k.
for stmt in [
    "SELECT t.* FROM t WHERE t.x = 'réveillé'",
    "SELECT t.* FROM t WHERE t.x = N'réveillé'",
    "SELECT t.* FROM t WHERE t.y = 'réveillé'",
    "SELECT t.* FROM t WHERE t.y = N'réveillé'",
]:
    cursor.execute(stmt)
    rows = cursor.fetchall()
    assert rows == [
        (1, u"réveillé", u"réveillé"),
        (2, u"réveillé", u"réveillé"),
    ], rows

```

in any case the N certainly isn't making things worse so I'll likely just push it through.

**Comment by zzzeek** [comment]
hey let's try your unicode character and not the ones I have which might overlap with latin1 or something

**Comment by zzzeek** [comment]
ding

**Comment by zzzeek** [comment]
hooray.  OK that was it.   needed weirder characters.  lets see what oracle says.

**Comment by zzzeek** [comment]
yeah oracle doesn't need it.

**Comment by zzzeek** [comment]
and adding this to the tests makes me have to deal with mysql utfmb4 all over again...

**Comment by zzzeek** [comment]
this is looking kind of 1.3 ish now.   are you worked around for 1.2.x ?

**Comment by villebro** [comment]
Yeah sorry I should have stressed the part about using adequately weird characters, I wasted a good bit of time using accented ascii-compliant letters, too 😃

**Comment by villebro** [comment]
I agree about this being 1.3 material. I'm thinking we can live without this until 1.3 comes out (eager ones can go with the RC).

**Comment by villebro** [comment]
Thanks @zzzeek for fixing this and loved the snaked-up French in the test cases :laughing:
