### ISSUE TITLE
Making PostgreSQL ignore length in TEXT columns

### ISSUE THREAD

**Issue by dsuch** [sqlalchemy/sqlalchemy#4443]
Hello,

I am using SQLAlchemy 1.2.8 but I can see that the same applies to the latest git version (as of 14/01/2019).

My use-case is that I would like for the definition below to work as, essentially, a column without any practical length limit under MySQL, PostgreSQL and SQLite:

data = Column(Text(2 * 10 ** 9)) # 2 GB

That is, it should create an underlying column in a manner that will not have practical boundaries, hence 2 GB.

As it stands today, the definition will work under SQLite and MySQL only. In the latter database LONGTEXT datatype will be used.

However, in PostgreSQL an error will be raised because TEXT datatype does not have any inherent limitations so the database rejects constructs such as TEXT(2000000000).

Class sqlalchemy.dialects.postgresql.base.PGTypeCompiler inherits method ```_render_string_type``` from its base class and this method adds the length limitation to TEXT columns under PostgreSQL indiscriminately, even if we know that columns of this type reject it.

I believe that ```_render_string_type``` could be overridden in PGTypeCompiler or otherwise made to understand that in PostgreSQL TEXT columns cannot have length specified.

If the method read as below, if such a method was added to PGTypeCompiler, then the definition above would work on all of these databases - it simply adds an 'if' statement to ignore length with TEXT columns that by definition cannot have any length.

```python
def _render_string_type(self, type_, name):

    text = name
    if type_.length and name != 'TEXT':
        text += "(%d)" % type_.length
    if type_.collation:
        text += ' COLLATE "%s"' % type_.collation
    return text
```

Regards.

**Comment by zzzeek** [comment]
Hi there -

the rendering of DDL for any SQLAlchemy type is controllable using the compilation extension:  

https://docs.sqlalchemy.org/en/latest/core/custom_types.html#overriding-type-compilation

demo:
```python

from sqlalchemy import Text
from sqlalchemy import Table, MetaData, Column
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.dialects import mysql, sqlite, postgresql
from sqlalchemy.schema import CreateTable


@compiles(Text, "sqlite")
def sqlite_text(type_, compiler, **kw):
    return "VARCHAR"


@compiles(Text, "mysql")
def mysql_text(type_, compiler, **kw):
    return "LONGTEXT(%d)" % type_.length


@compiles(Text, "postgresql")
def postgresql_text(type_, compiler, **kw):
    return "TEXT"


table = Table("tab", MetaData(), Column("data", Text(2 * 10 ** 9)))

for dialect in mysql.dialect(), postgresql.dialect(), sqlite.dialect():
    print(CreateTable(table).compile(dialect=dialect))

```

output:
```sql
CREATE TABLE tab (
	data LONGTEXT(2000000000)
)



CREATE TABLE tab (
	data TEXT
)



CREATE TABLE tab (
	data VARCHAR
)


```

**Comment by zzzeek** [comment]
additionally, another canonical way to create the type you want is to use [with_variant](https://docs.sqlalchemy.org/en/latest/core/type_api.html?highlight=with_variant#sqlalchemy.types.TypeEngine.with_variant) to define the different DB-level types.  This is usually the most appropriate way so that database-specific typing directives can be grouped with the type they apply towads, rather than sending in a bucket of options and expecting each backend to pick and choose which ones apply (which is the situation we hope to avoid by not adding tweaks to the different dialects that involve things meant for other database backends.  the approach does not scale)

```
from sqlalchemy import Text
from sqlalchemy import Table, MetaData, Column
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.dialects import mysql, sqlite, postgresql
from sqlalchemy.schema import CreateTable

text_type = Text().with_variant(mysql.LONGTEXT(), "mysql")

table = Table("tab", MetaData(), Column("data", text_type))

for dialect in mysql.dialect(), postgresql.dialect(), sqlite.dialect():
    print(CreateTable(table).compile(dialect=dialect))

```
LONGTEXT does not appear to take a length parameter.  

output:

```
CREATE TABLE tab (
	data LONGTEXT
)



CREATE TABLE tab (
	data TEXT
)



CREATE TABLE tab (
	data TEXT
)

```

**Comment by dsuch** [comment]
Hi @zzzeek,

thanks for the hints - all of this looks very interesting!

At this point, from my perspective, I think the ticket can be closed, thank you again.
