### ISSUE TITLE
add section to engines.rst how to urlencode special chars in passwords

### ISSUE THREAD

**Issue by ronlut** [sqlalchemy/sqlalchemy#4452]
Hi.

Our password (generated by MySQL) contains a percent (`%`) symbol.

The `_rfc_1738_unquote` function, called by `_parse_rfc1738_args` in the process of creating an engine, replaces the percent symbol (and the character following it) with another symbol, making the password impossible to encode into `latin-1` by the pymysql driver later on.

In our example, `%8` turns into some unicode character I guess: 
![image](https://user-images.githubusercontent.com/3050627/51322784-148d3000-1a6f-11e9-9ecd-b025421d4a8d.png)

Is that a bug or is that by design?
If that's not a bug, what can I do to deal with it? Except changing the password.

Thanks

**Comment by zzzeek** [comment]
hi there -

you need to use urlencoding for special characters in the URL (because it's a URL), so a password like "my%password" should be passed as "my%25password".

please let me know that resolves your issue.

looks like we need some documentation for this since I can't find it.

**Comment by ronlut** [comment]
I changed the password as it wasn't important enough for me to not change it, but happy to hear there is a better solution :)

**Comment by zzzeek** [comment]
quote_plus is better
