### ISSUE TITLE
sa autocommit with greenlet lead to poor concurrency performance

### ISSUE THREAD

**Issue by stupidstan** [sqlalchemy/sqlalchemy#4453]
in openstack quota update, if two greenlet execute the same update sql concurrently:
update table set value=value+1 where id=1

greenlet1:
begin()
update sql(switch out, some time consuming like fibnacci or orm work)
commit(after 10s switched back)

greenlet2：
begin()
update sql(hanged on sqlserver for 10s)
commit()

i setted the psycopg.connection, connection.connection.connection(autocommit=true), its worked.
could sa support real autocommit ?

**Comment by zzzeek** [comment]
SQLAlchemy supports autocommit and I've referenced the documentation for how to do this.
