### ISSUE TITLE
new mysqlclient 1.4.0 is out, need to update performance tests

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4455]
since they moved to a purely native string encoder a lot of aaa_profiling blows up and needs to be regenerated.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Regenerate callcounts for mysqlclient 1.4.0** https://gerrit.sqlalchemy.org/1105

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_2** branch:

**Regenerate callcounts for mysqlclient 1.4.0** https://gerrit.sqlalchemy.org/1106
