### ISSUE TITLE
SHOW CREATE TABLE for mysql - parser issue(s)

### ISSUE THREAD

**Issue by kuba--** [sqlalchemy/sqlalchemy#4456]
I tried to get mysql table definition using reflection, by following script:
```python
import pandas as pd
import sqlalchemy

engine = sqlalchemy.create_engine('mysql+pymysql://root@127.0.0.1:3306/db')
with engine.connect() as conn:
    repo_df = pd.read_sql_table("tablename", con=conn)
```

The problem which I came across is related to the _mysql reflection parser_ used by sqlalchemy.
For instance to extract table name it uses following regex: 
```
^CREATE (?:\w+ +)?TABLE +`(?P<name>(?:``|[^`])+)` +\($
```
Here: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/reflection.py#L54
https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/reflection.py#L338
Which basically requires a new line after '('. In other words following response:
```
CREATE TABLE `tablename` (`columnname` TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```
is incorrect for sqlalchemy. You have to format it as:
```
CREATE TABLE `tablename ` (
`columnname ` TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

Than I came across another issue - column names has to be indent by **two spaces**.
See https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/reflection.py#L45
```python
 if line.startswith("  " + self.preparer.initial_quote):
                self._parse_column(line, state)
```
to parse a column name the new line has to start with **two spaces** and '`'.

Ultimately, I managed by formatting my queries as:
```sql
CREATE TABLE `table_name` (
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `phone_numbers` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

but if you check specification: https://dev.mysql.com/doc/refman/8.0/en/create-table.html
there is nothing about indentation for 2 spaces.

**Comment by zzzeek** [comment]
hi there -

consider that the code you refer towards has never shown any such problem, regardless of the specification, and it should be apparent that I need more information.   Specifically, what OS platform / MySQL version / build do you have that is outputting the "SHOW CREATE TABLE" in this format ?    We have CI that runs against six versions of Mariadb/MySQL including 8.0 which calls this code for hundreds of tables each run.    Additionally, can you please illustrate the stack trace you are getting?  thanks.

OTOH, if this is just "theoretically" wrong, or you are using the reflection code for some kind of CREATE TABLE string that's generated programmatically in some non-standard way, please include that when you post an issue, that is a very significant detail.

**Comment by kuba--** [comment]
@zzzeek - we have own implementation of Mariadb/MySQL, which for query:
```sql
SHOW CREATE TABLE `refs`
```
returned:
```sql
CREATE TABLE `refs` (`name` TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

This couldn't be parsed by sqlalchemy and we got:
```
INFO:sqlalchemy.engine.base.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.base.Engine:{}
DEBUG:sqlalchemy.engine.base.Engine:Col ('Variable_name', 'Value')
DEBUG:sqlalchemy.engine.base.Engine:Row ('sql_mode', '')
INFO:sqlalchemy.engine.base.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.base.Engine:{}
DEBUG:sqlalchemy.engine.base.Engine:Col ('Variable_name', 'Value')
INFO:sqlalchemy.engine.base.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.base.Engine:{}
DEBUG:sqlalchemy.engine.base.Engine:Col ('DATABASE()',)
DEBUG:sqlalchemy.engine.base.Engine:Row ('gitbase',)
INFO:sqlalchemy.engine.base.Engine:show collation where `Charset` = 'utf8mb4' and `Collation` = 'utf8mb4_bin'
INFO:sqlalchemy.engine.base.Engine:{}
DEBUG:sqlalchemy.engine.base.Engine:Col ('Collation', 'Charset', 'Id', 'Default', 'Compiled', 'Sortlen')
INFO:sqlalchemy.engine.base.Engine:SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
INFO:sqlalchemy.engine.base.Engine:{}
INFO:sqlalchemy.engine.base.Engine:SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
INFO:sqlalchemy.engine.base.Engine:{}
INFO:sqlalchemy.engine.base.Engine:SHOW FULL TABLES FROM `gitbase`
INFO:sqlalchemy.engine.base.Engine:{}
DEBUG:sqlalchemy.engine.base.Engine:Col ('Table', 'Table_type')
DEBUG:sqlalchemy.engine.base.Engine:Row ('refs', 'BASE TABLE')
INFO:sqlalchemy.engine.base.Engine:SHOW FULL TABLES FROM `gitbase`
INFO:sqlalchemy.engine.base.Engine:{}
DEBUG:sqlalchemy.engine.base.Engine:Col ('Table', 'Table_type')
DEBUG:sqlalchemy.engine.base.Engine:Row ('refs', 'BASE TABLE')
INFO:sqlalchemy.engine.base.Engine:SHOW CREATE TABLE `refs`
INFO:sqlalchemy.engine.base.Engine:{}
DEBUG:sqlalchemy.engine.base.Engine:Col ('Table', 'Create Table')
DEBUG:sqlalchemy.engine.base.Engine:Row ('refs', 'CREATE TABLE `refs` (`name` TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 240, in read_sql_table
    meta.reflect(only=[table_name], views=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4160, in reflect
    Table(name, self, **reflect_opts)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 470, in __new__
    metadata._remove_table(name, schema)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 465, in __new__
    table._init(name, metadata, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 548, in _init
    metadata, autoload_with, include_columns, _extend_on=_extend_on
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 570, in _autoload
    _extend_on=_extend_on,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1590, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 415, in reflecttable
    table, include_columns, exclude_columns, **opts
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 643, in reflecttable
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: refs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    repo_df = pd.read_sql_table("refs", con=conn)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 242, in read_sql_table
    raise ValueError("Table %s not found" % table_name)
ValueError: Table refs not found
```

The problem appeared in the reflection parser, so if I return:
```sql
CREATE TABLE `refs` (
  `name` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```
Everything looks fine.
But the new line and **two spaces** before column name are important for the parser. It will skip parsing columns if you don't have these **2 spaces** - see: 
https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/reflection.py#L45

**Comment by zzzeek** [comment]
thanks for that detail, it's essential that I know how something is going wrong in reality.   The "here's the broken line of code" doesn't tell us much because that line of code has run trillions of times around the world for 13 years and never had this problem :)

**Comment by zzzeek** [comment]
we also don't recognize that name "TEXT" because we expect those names to be lower case.

**Comment by zzzeek** [comment]
so I can give you a stub with a few tests, but AFAICT this would require a rewrite of MySQLTableDefinitionParser because it is using the split on newline and the two spaces in order to parse out the columns, and without being able to rely upon that it seems like we'd need to build a complete grammar.   Do you have a patch in mind?   otherwise I am not going to have the resources to work on this seeing that this is not standard MySQL.

**Comment by zzzeek** [comment]
the two spaces are entirely significant in the parsing scheme here:

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/reflection.py#L45

**Comment by kuba--** [comment]
This is what I posted, and this is what I think is weird. Why every column definition has to start as a new line with 2 spaces. 
Is it documented anywhere?

**Comment by zzzeek** [comment]
> This is what I posted, and this is what I think is weird. Why every column definition has to start as a new line with 2 spaces.
> Is it documented anywhere?

not at all.   let me try to sum up - the code that is there works with every publicly released version of MySQL and MariaDB for the past 13 years.   However, as you've noted, it is not per spec, and on your custom built MySQL variant, it doesn't work.  It should be changed.   However I don't have a change that will work handy right now.    The parsing scheme relies upon those spaces to know that it is looking at a column in the SHOW CREATE TABLE statement.   It can't be fixed trivially, it needs to be thrown out and rewritten to support your use case.  which should happen.  it's just I can't prioritize that work for myself right now.

**Comment by kuba--** [comment]
I believe if we "eat spare whitespaces" we'll be still backward compatible. On the other hand I believe we need  _solid_ mysql parser, because for new mysql implementations or if mysql change a little bit, we'll come back to this issue.

**Comment by zzzeek** [comment]
this is totally true, if they change anything, we're in a brittle state. of course it would be nice if their information_schema provided all the information we need and we wouldn't have to parse anything (perhaps very recent versions of it have improved).
