### ISSUE TITLE
postgres covering index is not supported

### ISSUE THREAD

**Issue by omris94** [sqlalchemy/sqlalchemy#4458]
pg11 supports covering index (INCLUDE columns), it will be great to have support of this kind of index.

i looked at the code (not for a long time but..) and i have one insight that may help,
in dialects/postgresql/base.py - get_indexes - we may want to query the column indnkeyatts of pg_index which tells us the number of key columns. With the combination of indnkeyatts with indkey (which gives us an array of key columns and non-key columns [key columns are alway first]) we can differ between key and non-key columns.

covering index pg11: https://www.depesz.com/2018/04/26/waiting-for-postgresql-11-indexes-with-include-columns-and-their-support-in-b-tree/
pg_index: https://www.postgresql.org/docs/11/catalog-pg-index.html

**Comment by zzzeek** [comment]
hi there -

OK I get the idea there's an "INCLUDE" keyword, and it seems like you are looking at some internals for reflection at the moment.   

Can we make this into a better feature request:

1. link to exactly what INCLUDE syntax looks like

2. proposal for SQLAlchemy to render these (right?  reflection is just one part of it)

3. take a look at other kinds of PG index extensions at https://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#postgresql-specific-index-options to see the general idea of how these look

4. reflection of the additional parameters in 3 can be part of the feature request.

5. if you want to just PR the "inspector" part of it, then you can work with get_indexes() to provide additional keys inside of "dialect_options" in the records returned by [inspector.get_indexes()](https://docs.sqlalchemy.org/en/latest/core/reflection.html?highlight=get_indexes#sqlalchemy.engine.reflection.Inspector.get_indexes) but that won't give you DDL.

**Comment by omris94** [comment]
hey, sorry for the late response..

1. postgres 11 create index syntax (including INCLUDE option): [https://www.postgresql.org/docs/11/sql-createindex.html](url)

2 + 3. i used "compiles" and "Index.argument_for" in order to make SQLAlchemy render it. It will be great to have "postgres_include" as an option in a future SQLAlchemy release

4 + 5. i needed the "inspector" part for my migration tests, so i patched get_indexes in my env. In my solution (which is not perfect), get_indexes ignores the non_key columns. i can create a PR with my solution, but we may want to improve it if we'll have "postgres_include" option during the creation.

**Comment by zzzeek** [comment]
The idea is we should assume we're adding the whole front-to-back feature.   There's a lot of other "postgresql_xyz" features that should serve as a template for this.

**Comment by kataev** [comment]
SQL Server also support include clause: https://use-the-index-luke.com/blog/2019-04/include-columns-in-btree-indexes#compatibility

**Comment by zzzeek** [comment]
> SQL Server also support include clause: https://use-the-index-luke.com/blog/2019-04/include-columns-in-btree-indexes#compatibility
> Maybe port (copy-past man_shrugging) code from mssql dialect?

oh you mean *we* have "INCLUDE" syntax for SQL Server right now, I just looked sure, this is not a hard change except for the potential reflection part because that involves figuring out how to get it back from the PG catalog tables.

**Comment by gordthompson** [comment]
To get more familiar with this topic I did a quick test with mssql. I had an existing table named [team] …

``` sql
CREATE TABLE [dbo].[team](
	[prov] [varchar](2) NOT NULL,
	[city] [varchar](20) NOT NULL,
	[team_name] [varchar](20) NULL,
 CONSTRAINT [PK_team] PRIMARY KEY CLUSTERED 
(
	[prov] ASC,
	[city] ASC
)
```

… and I added two indexes with

``` sql
CREATE INDEX IX_team_all ON team (prov, city, team_name);
CREATE INDEX IX_team_covering ON team (prov, city) INCLUDE (team_name);
```

When I run `get_indexes` I see the following

``` python
result = engine.dialect.get_indexes(engine.connect(), "team")
pprint(result)
"""console output:
[{'column_names': ['prov', 'city', 'team_name'],
  'name': 'IX_team_covering',
  'unique': False},
 {'column_names': ['prov', 'city', 'team_name'],
  'name': 'IX_team_all',
  'unique': False}]
"""
```

Based on the discussion so far, does this mean that the output is potentially misleading because there is no way to distinguish between the two?

**Comment by zzzeek** [comment]
@gordthompson that result it's giving you is definitely the wrong answer, yes.   the "team_name" column should not be listed out under "column names" like that.

if "INCLUDE" is part of the SQL standard then I would be fine adding a new member to the indexes collection "include_columns".

**Comment by gordthompson** [comment]
@zzzeek - My understanding is that CREATE INDEX is not part of the SQL Standard. [This page](https://www.w3resource.com/sql/creating-index/sql-creating-index.php) says so explicitly, and I found no mention of it in a draft copy of "ISO/IEC 9075-2 Foundation (SQL/Foundation)" I got from [here](http://www.wiscorp.com/sql20nn.zip) via [Wikipedia](https://en.wikipedia.org/wiki/SQL).

**Comment by zzzeek** [comment]
that had to be something I knew at one point.

OK so if "INCLUDE" seems to be a concept that has a few vendors doing the same thing we can still try to allow it at the top level.

**Comment by gordthompson** [comment]
Okay, so as I understand it from looking at the comments to this issue and the code in the current SQLA master, the mssql dialect knows how to render a covering index …

https://github.com/sqlalchemy/sqlalchemy/blob/1613c9fb2555eec8f922595304080286f72e6dc4/lib/sqlalchemy/dialects/mssql/base.py#L606-L614

… but mistakenly returns the INCLUDEd column(s) when reflecting the index (ref: comments above). This could be fixed quite easily by incorporating the `sys.index_columns.is_included_column` flag in the `get_indexes` logic for mssql.

The postgresql dialect, on the other hand, does not yet know how to render a covering index natively, but it does already know that it should exclude INCLUDEd columns on reflection:

https://github.com/sqlalchemy/sqlalchemy/blob/1613c9fb2555eec8f922595304080286f72e6dc4/lib/sqlalchemy/dialects/postgresql/base.py#L3627-L3632

So would a satisfactory resolution to this issue be:

1. to add the ability for the postgres dialect to render a covering index similar to how mssql does it, and
2. to tweak the mssql dialect's `get_indexes()` to omit the INCLUDEd columns similar to how postgresql does it?

**Comment by zzzeek** [comment]
yes and also 3. postgresql dialect no longer ignores these columns, includes them in the index dictionry

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Improve handling of covering indexes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2204
