### ISSUE TITLE
Bug found when doing a join

### ISSUE THREAD

**Issue by chidioguejiofor** [sqlalchemy/sqlalchemy#4459]
I am currently using `flask_sqlalchemy` in which I am using `sqlalchemy` to connect to a `postgres` database and I found that whenever I try to to do a join using the following command:
`rows = Session.query(TableOne).join(TableTwo).join(TableThree).filter(TableOne.name == "john-dough")all()`

An error is thrown in my terminal. 

On examination, I found that SQLAlchemy adds a  `'\n'` to the query returned. Here is a sample:

```

SELECT TableOne.id, ...{columns}  \nFROM TableOne JOIN TableTwo ON TableOne.id = TableTwo.table_one_id 
JOIN TableThree ON TableTwo.id = TableThree.table_one_id \nWHERE TableOne.name ="john-dough"

```
When I copied the SQL query generated and removed the **\n** the code works as expected.

I am sorry I am unable to show the exact tables in my database. This is because I found this on a confidential project and thus cannot share critical information here

**Comment by zzzeek** [comment]
hi there -

newlines have no significance in SQL.   Without rudimentary top level information, such as, what database is this and what version?  what is the database driver, what version , what Python version, what is the error message seen, as well as a stack trace, there is nothing that can be done here.    Similarly,  re: the exact tables, there is no need to show these tables.  Simply create an [MCVE](http://stackoverflow.com/help/mcve) using demonstration tables to produce a script that reproduces the error.

thanks and good luck!

**Comment by chidioguejiofor** [comment]
@zzzeek thanks for the feedback. This was one of the first issues I have ever raised in my career and would definitely apply your feedback in the future. Currently, I might not be able to re-create the bug because of some constraints that I currently have. 

Thanks for the feedback once again.
