### ISSUE TITLE
before_compile() hook for query.update query.delete

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4461]
which we can call before_compile_update() and before_compile_delete() to differentiate

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add QueryEvents before_compile_update / before_compile_delete** https://gerrit.sqlalchemy.org/1109

**Comment by decaz** [comment]
@zzzeek I've found link to this issue here - https://github.com/sqlalchemy/sqlalchemy/wiki/FilteredQuery. It would be great if you update recipe in accordance with these changes (2nd caveat). Thanks!

**Comment by zzzeek** [comment]
the filteredquery recipe is already deprecated and probably won't work as well in 1.4.   I'm working on a new system for what "Filtered query" tries to do that will work in all cases but it is 1.4 only.

**Comment by Adityashaw** [comment]
> the filteredquery recipe is already deprecated and probably won't work as well in 1.4. I'm working on a new system for what "Filtered query" tries to do that will work in all cases but it is 1.4 only.

The wiki link for "Filtered Query" says, ` For 1.4, an all new system of augmenting queries that is more capable is introduced, which works fully in all cases.`
I would love to upgrade to 1.4 from 1.3. Can we have the documentation link so that we can implement the "same" thing in 1.4 that "Filtered Query" does in 1.3?

Thanks!

**Comment by zzzeek** [comment]
> > the filteredquery recipe is already deprecated and probably won't work as well in 1.4. I'm working on a new system for what "Filtered query" tries to do that will work in all cases but it is 1.4 only.
> 
> The wiki link for "Filtered Query" says, ` For 1.4, an all new system of augmenting queries that is more capable is introduced, which works fully in all cases.`
> I would love to upgrade to 1.4 from 1.3. Can we have the documentation/wiki link so that we can implement the "same" thing in 1.4 that "Filtered Query" does in 1.3?
> 
> Thanks!

updated, that link is https://docs.sqlalchemy.org/en/14/orm/session_events.html#do-orm-execute-global-criteria .   let me know if it goes OK because there's some intricate stuff in there to make that work.

**Comment by zzzeek** [comment]
the wiki examples are rewritten at https://docs.sqlalchemy.org/en/14/orm/examples.html#examples-session-orm-events
