### ISSUE TITLE
Syntax used for PostgreSQL check constraints will be deprecated in PostgreSQL 12

### ISSUE THREAD

**Issue by volcan01010** [sqlalchemy/sqlalchemy#4463]
### Summary

Reflection of check constraints against PostgreSQL databases queries the `pg_constraint.consrc` column.  This has been deprecated in PostgreSQL 12, so constraint reflection will fail against that version.

### Details

Check constraint reflection takes place in the following code function:

https://github.com/sqlalchemy/sqlalchemy/blob/bd735eba637cbf2c157046f72dc795a8b2b803e7/lib/sqlalchemy/dialects/postgresql/base.py#L3376

However, this query will fail in PostgreSQL 12, when the `consrc` column of the table is deprecated:

https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=96b00c433cd615144a34ff1a79d691d8b297120d

### Potential fix

The recommended way to fix this is to use the `pg_get_constraintdef` function instead.  The PostGIS project hit this issue and their solution may be helpful: https://trac.osgeo.org/postgis/ticket/4231

### Is this a bug?

I think this counts as a bug. I encountered the issue when models generated by sqlacodegen had different constraints to those displayed in PGAdmin4's SQL view.  However, I can't provide a script to demonstrate this because I don't know how the results from `pg_get_constraintdef` and `pg_constraint.consrc` came to be different in the first place!

This will be a bug when run with PostgreSQL 12.  A potential way to test it is to add check constraints to a PostgreSQL 12 table and then try to reflect them.

### SQLAlchemy version

Issue noticed against version 1.2.12 (but applies to [latest commit at time of writing](https://github.com/sqlalchemy/sqlalchemy/commit/bd735eba637cbf2c157046f72dc795a8b2b803e7))

**Comment by volcan01010** [comment]
Suggested replacement SQL query:

```sql
            SELECT
                cons.conname as name,
                right(left(pg_get_constraintdef(cons.oid), -1), -7) as src
            FROM
                pg_catalog.pg_constraint cons
            WHERE
                cons.conrelid = :table_oid AND
                cons.contype = 'c'
```

**Comment by volcan01010** [comment]
It looks like it goes right back to version 8.0:

https://www.postgresql.org/docs/8.0/functions-info.html

**Comment by zzzeek** [comment]
we are already stripping from the text returned so ill just do more of a proper regex on the python side.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use pg_get_constraintdef for CHECK constraint reflection** https://gerrit.sqlalchemy.org/1113

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_2** branch:

**Use pg_get_constraintdef for CHECK constraint reflection** https://gerrit.sqlalchemy.org/1114

**Comment by volcan01010** [comment]
That was quick!

I wondered if the existing test should be updated so that the present code will fail. I only found this issue because of the mismatch between the constraints reported by PGAdmin and the values in the `consrc` column.  I have posted a suggestion below that inserts bad data into the consrc column.  I don't know the best way to handle the fact that this insertion will fail in PG 12 because the column will no longer exist.

```python
    @testing.provide_metadata
    def test_reflect_check_constraint(self):
        meta = self.metadata

        cc_table = Table(
            "pgsql_cc",
            meta,
            Column("a", Integer()),
            CheckConstraint("a > 1 AND a < 5", name="cc1"),
            CheckConstraint("a = 1 OR (a > 2 AND a < 5)", name="cc2"),
        )

        cc_table.create()

        # Insert bad data into pg_constraint.consrc column, which should not be used
        # and which will be deprecated in PG 12
        CONSRC_SQL = """"
                UPDATE pg_catalog.pg_constraint
                SET consrc = 'consrc column is deprecated'
                WHERE contype = 'c'
        """
        try:
            with testing.db.connect() as conn:
                conn.execute(CONSRC_SQL)
        except SomeKindOfPsycopg2ErrorMaybeProgrammingError:
            # consrc column doesn't exist in PG > 12
            pass   

        reflected = Table("pgsql_cc", MetaData(testing.db), autoload=True)

        check_constraints = dict(
            (uc.name, uc.sqltext.text)
            for uc in reflected.constraints
            if isinstance(uc, CheckConstraint)
        )

        eq_(
            check_constraints,
            {
                u"cc1": u"(a > 1) AND (a < 5)",
                u"cc2": u"(a = 1) OR ((a > 2) AND (a < 5))",
            },
        )
```

**Comment by zzzeek** [comment]
I'm not sure you can update pg_catalog tables directly?    what are we looking for in that test?

**Comment by volcan01010** [comment]
I don't know if you can update those tables or not either. The aim was to show that the constraint definition was coming from wherever `pg_get_constraintdef` looks, and not from the `consrc` column.

Thanks for fixing this.

**Comment by zzzeek** [comment]
ah OK.   Well we have CI where we just run these databases for real so I'll add pg 12 when it's released.
