### ISSUE TITLE
No public access to query._execution_options

### ISSUE THREAD

**Issue by daniel--** [sqlalchemy/sqlalchemy#4464]
[This recipe](https://github.com/sqlalchemy/sqlalchemy/wiki/FilteredQuery) uses the private variable `query._execution_options`. There should be a getter for this variable to avoid private variable access.

Fix incoming.

**Comment by zzzeek** [comment]
heya.

we could use this for Connection and Engine also if you've thought of a good name for the accessor (get_execution_options() ?   im not a huge fan of getters, prefer `@property`)

**Comment by daniel--** [comment]
Sure, I can add one for Connection and Engine also, I went with `get_execution_options()` but I agree on preferring `@property` the problem is `execution_options` is already a function on Query

**Comment by zzzeek** [comment]
we got the issue number wrong, this was fixed with https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1112/, needs to be updated
