### ISSUE TITLE
names generated by func are not quoted for case sensitive names, special characters

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#4467]
Through the use of `func` sql statements can be executed. Something like
```py
table = sa.Table(...)
fn = getattr(sa.func, '1; drop table other_table; select max')
sa.select([fn(table.c.id)])
fn = getattr(sa.func, '(select count(*) from other_table), max')
sa.select([fn(table.c.id)])
```
executes the valid statements
```
SELECT 1; drop table other_table; select max(table.id) AS "1; drop table other_table; select max_1" 
FROM table
SELECT (select count(*) from other_table), max(table.id) AS "(select count(*) from other_table), max_1" 
FROM table
```

These are just two examples, but it seems that the name of function is taken as is, without executing any sort of validation.

Maybe `func` should validate that the name of the function is a valid database identifier?

I was thinking about letting an consumer of an api I'm writing on specify a function name and wanted to check if I needed to validate it against a list of allowed functions.

**Comment by CaselIT** [comment]
As always thanks for your quick reply

>database identifiers can actually have a wide variety of characters in them, they just need to be quoted.

I agree that is it not easy, since every database may have its own rules.

> it is not appropriate to use untrusted user input as a python attribute name any more than it would be to use untrusted user input as the name of a SQL table

Yes, I agree, I would probably ended up with a function name whitelist in any case, it just was surprising to find that I could execute sql statements that way.

Regarding "arbitrary", I'm not a native English speaker, so I may have misused it. I'll edit the original issue to avoid it.

**Comment by CaselIT** [comment]
I've tried this out on postgres (10.5) and this may break existing code. 
The query 
```py
 sa.select([sa.func.MAX(sa.column('id'))], from_obj=sa.table('table'))
```
now executes
```sql
SELECT "MAX"(id) AS "MAX_1" FROM table
```
that returns the error `function MAX(integer) does not exist`

**Comment by zzzeek** [comment]
Right, so we'd hope people are using all lower case, but also there some databases I refer to as "name normalize" databases, which are Oracle, Firebird, DB2, which represent everything as UPPERCASE, so while someone can be saying "func.max()" without issue, their source code might have a lot of calls to func.MAX() because that's how their database documents it.

**Comment by zzzeek** [comment]
doing case sensitive quoting on function names still might be appropriate, but as it breaks compatibility we can more safely omit casing from the quoting question for now:

```
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index b703c59f23..1a2bcc339f 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -1073,13 +1073,32 @@ class SQLCompiler(Compiled):
         else:
             name = FUNCTIONS.get(func.__class__, None)
             if name:
+                name = (
+                    self.preparer.quote(name)
+                    if self.preparer._requires_quotes_omit_casing(name)
+                    else name
+                )
                 if func._has_args:
                     name += "%(expr)s"
             else:
-                name = func.name + "%(expr)s"
-            return ".".join(list(func.packagenames) + [name]) % {
-                "expr": self.function_argspec(func, **kwargs)
-            }
+                name = func.name
+                name = (
+                    self.preparer.quote(name)
+                    if self.preparer._requires_quotes_omit_casing(name)
+                    else name
+                )
+                name = name + "%(expr)s"
+            return ".".join(
+                [
+                    (
+                        self.preparer.quote(tok)
+                        if self.preparer._requires_quotes_omit_casing(tok)
+                        else tok
+                    )
+                    for tok in func.packagenames
+                ]
+                + [name]
+            ) % {"expr": self.function_argspec(func, **kwargs)}
 
     def visit_next_value_func(self, next_value, **kw):
         return self.visit_sequence(next_value.sequence)
@@ -3439,6 +3458,16 @@ class IdentifierPreparer(object):
             or (lc_value != value)
         )
 
+    def _requires_quotes_omit_casing(self, value):
+        """Return True if the given identifier requires quoting, but
+        not taking case convention into account."""
+        lc_value = value.lower()
+        return (
+            lc_value in self.reserved_words
+            or value[0] in self.illegal_initial_characters
+            or not self.legal_characters.match(util.text_type(value))
+        )
+
     def quote_schema(self, schema, force=None):
         """Conditionally quote a schema name.
 

```

that should be fully compatible because anyone using special characters in a function name right now is getting invalid SQL.

**Comment by CaselIT** [comment]
>doing case sensitive quoting on function names still might be appropriate, but as it breaks compatibility we can more safely omit casing from the quoting question for now

I agree. It's probably best to save that change for a major release. As an alternative it could be enabled with an option, like a kwargs on `func` (but I'm not sure if it's possible) or on when creating the engine/parser.

I've tried the latest patch and it does seem to fix the issue, keeping compatibility with upper case functions.

Thanks for your effort, and for this great library 👍

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove all remaining text() coercions and ensure identifiers are safe** https://gerrit.sqlalchemy.org/1126
