### ISSUE TITLE
Using load_only on joinedload for polymorphic relation loads more columns

### ISSUE THREAD

**Issue by mattisborgen** [sqlalchemy/sqlalchemy#4468]
This is using sqlalchemy==1.2.16

Following snippet produces SQL that loads more attributes (other_attribute) than was asked for:

```
from sqlalchemy import Column, ForeignKey, Integer, Unicode, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Query, relationship, joinedload
from sqlalchemy.pool import NullPool

engine = create_engine(
    'mysql://**',
    poolclass=NullPool
)

connection = engine.connect()
connection.begin()

Base = declarative_base()


class Context(Base):
    __tablename__ = 'context'
    id = Column(Integer, primary_key=True)
    context_type = Column(Unicode(256), nullable=False)

    parent = relationship('Context')

    parent_id = Column(
        Integer, ForeignKey(
            'context.id'
        ), nullable=True
    )
    __mapper_args__ = {'polymorphic_on': context_type}


class Task(Context):
    __tablename__ = 'task'
    __mapper_args__ = {'polymorphic_identity': 'child1'}
    id = Column(
        Integer,
        ForeignKey('context.id'),
        primary_key=True
    )


class Project(Context):
    __tablename__ = 'project'

    id = Column(
        Integer,
        ForeignKey('context.id'),
        primary_key=True
    )

    full_name = Column(Unicode(256))

    other_attribute = Column(Unicode(256))


Base.metadata.create_all(connection)

query = Query(Task).options(
    joinedload(Task.parent.of_type(Project)).load_only('full_name')
)

print(query)
```

The following query is produced:

`
SELECT task.id AS task_id, context.id AS context_id, context.context_type AS context_context_type, context.parent_id AS context_parent_id, anon_1.context_id AS anon_1_context_id, anon_1.context_context_type AS anon_1_context_context_type, anon_1.project_id AS anon_1_project_id, anon_1.project_full_name AS anon_1_project_full_name, anon_1.project_other_attribute AS anon_1_project_other_attribute
FROM context JOIN task ON context.id = task.id LEFT OUTER JOIN (SELECT context.id AS context_id, context.context_type AS context_context_type, context.parent_id AS context_parent_id, project.id AS project_id, project.full_name AS project_full_name, project.other_attribute AS project_other_attribute
FROM context LEFT OUTER JOIN project ON context.id = project.id) AS anon_1 ON context.id = anon_1.context_parent_id
`

Where as sqlalchemy==1.1.4 gave, which omits other_attribute in the outer select:

`
SELECT task.id AS task_id, context.id AS context_id, context.context_type AS context_context_type, context.parent_id AS context_parent_id, anon_1.context_id AS anon_1_context_id, anon_1.context_context_type AS anon_1_context_context_type, anon_1.project_id AS anon_1_project_id, anon_1.project_full_name AS anon_1_project_full_name
FROM context JOIN task ON context.id = task.id LEFT OUTER JOIN (SELECT context.id AS context_id, context.context_type AS context_context_type, context.parent_id AS context_parent_id, project.id AS project_id, project.full_name AS project_full_name, project.other_attribute AS project_other_attribute
FROM context LEFT OUTER JOIN project ON context.id = project.id) AS anon_1 ON context.id = anon_1.context_parent_id
`

I've been trying with more explicit alias and with_polymorphic approaches, but it gives same result.

**Comment by zzzeek** [comment]
looks the same description as #3287 but have not run the demo or checked the query yet.

**Comment by zzzeek** [comment]
#4373 fixes this for a Load option as well, not sure if that impacts the fact that this is an of_type(), but please try 1.3.0b2 as well.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure of_type subclass taken into account with wildcards** https://gerrit.sqlalchemy.org/1117

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_2** branch:

**Ensure of_type subclass taken into account with wildcards** https://gerrit.sqlalchemy.org/1118
