### ISSUE TITLE
allow additional criteria to be and-ed onto a relationship-based join, works for all join / loader options

### ISSUE THREAD

**Issue by dima-starosud** [sqlalchemy/sqlalchemy#4472]
This usability improvement request is related mostly to `Load` options, in particular to filtering relationships. In short it would be great to have a way to extend `ON` clause condition. 

Here is motivation.

Imagine there are two models (e.g. X and Y), which in general may be connected in different ways (1toM, NxM, custom join condition, etc.). While querying X we want to filter Y, but in the way that doesn't affect X model.
Possible SQL solution is to add appropriate condition to `ON` clause of `JOIN`, but for this one has to turn `RelationshipProperty` into `ClauseElement`, and it's hard in general case, because it's not always just condition.

Here is workaround I came up with, sorry if it's too long:

```
from sqlalchemy import Column, ForeignKey, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, aliased, configure_mappers, contains_eager, relationship
from sqlalchemy.pool import NullPool
from sqlalchemy.sql.expression import Join, and_

engine = create_engine('postgresql://***', poolclass=NullPool)
connection = engine.connect()
connection.begin_nested()
session = Session(connection)

Base = declarative_base()


class X(Base):
    __tablename__ = 'x'
    id = Column(Integer, primary_key=True)
    ys = relationship('Y', secondary='xy')

    def __repr__(self):
        return "X(ys={})".format(self.ys)


class Y(Base):
    __tablename__ = 'y'
    id = Column(Integer, primary_key=True)
    value = Column(String)

    def __repr__(self):
        return "Y(value={})".format(self.value)


class XY(Base):
    __tablename__ = 'xy'
    x_id = Column(Integer, ForeignKey(X.id), primary_key=True)
    y_id = Column(Integer, ForeignKey(Y.id), primary_key=True)


configure_mappers()
Base.metadata.create_all(connection)

x = aliased(X, name='my_x')
y = aliased(Y, name='my_y')

session.add(X(ys=[Y(value='hello world')]))
session.flush()
session.expire_all()

q0 = session.query(x)
q1 = q0.outerjoin(y, x.ys)
q2 = q1.options(contains_eager(x.ys, alias=y))

assert len(q0._from_obj) + 1 == len(q2._from_obj)
j = q2._from_obj[-1]
assert isinstance(j, Join)
original_j_onclause = j.onclause

print(q2.all())  # [X(ys=[Y(value=hello world)])]

j.onclause = and_(original_j_onclause, y.value == 'hello')
print(q2.all())  # [X(ys=[])]

j.onclause = and_(original_j_onclause, y.value == 'hello world')
print(q2.all())  # [X(ys=[Y(value=hello world)])]
```

Is it possible to do this without touching/mutating protected attributes?

**Comment by zzzeek** [comment]
The ON clause of join() is open ended, you can simply do this:

```
a1 = (
    s.query(A)
    .join(B, A.bs.expression & (B.id > 4))
    .options(contains_eager(A.bs))
    .one()
)

```
you'd have to clarify what " and it's hard in general case, because it's not always just condition." means.   

as far as neater syntaxes, I'd be more interested in one that works with joinedload(), so that one can affect the ON clause generated by joinedload().     As far as the issue here, I would not support an API that changes the ON clause after the fact, as it would be too confusing to use and document.  People have enough confusion over join() itself.

A slicker syntax that would be nice if it could work *all* the eager loader options:

    sess.query(A).options(joinedload(A.bs.on(B.id > 4))

or something like that.   No resources to work on that right now though, would have to be a someday thing.

**Comment by dima-starosud** [comment]
In the setting I showed relationship is many to many, so:
`session.query(x).outerjoin(y, x.ys)` produces
```
SELECT my_x.id AS my_x_id 
FROM x AS my_x LEFT OUTER JOIN (xy AS xy_1 JOIN y AS my_y ON my_y.id = xy_1.y_id) ON my_x.id = xy_1.x_id
```
whereas `session.query(x).outerjoin(y, x.ys.expression)` gives
```
SELECT my_x.id AS my_x_id 
FROM x AS my_x LEFT OUTER JOIN y AS my_y ON my_x.id = xy_1.x_id AND y.id = xy_1.y_id
```
which leads to `(psycopg2.ProgrammingError) missing FROM-clause entry for table "xy_1"`.

**Comment by zzzeek** [comment]
oh the stupid many to many.  sure.  well i have no time to work on this anytime soon as it involves a throughout architectural change, and also dealing with join() vs. eager options.

the feature is:

    Class.relationship.and_(<criteria>)

so you can say:

   query(A).join(A.bs.and_(<criteria>))
   query(A).options(joinedload(A.bs.and_(<criteria>))
   query(A).options(lazyload(A.bs.and_(<criteria>))

The and_() unit is applied to the condition using the same internal mechanics as that of of_type(), so will have impact everywhere of_type() impacts.   The feature would need to also work with of_type being present.

**Comment by zzzeek** [comment]
at the moment I'd like to make this dependent on #4469 since that is a lingering architectural flaw in the pathing system

**Comment by dima-starosud** [comment]
It's not only many to many:
```
class X(Base):
    __tablename__ = 'x'
    id = Column(Integer, primary_key=True)
    ys = relationship('Y')

    def __repr__(self):
        return "X(ys={})".format(self.ys)


class Y(Base):
    __tablename__ = 'y'
    id = Column(Integer, primary_key=True)
    x_id = Column(Integer, ForeignKey(X.id))
    value = Column(String)

    def __repr__(self):
        return "Y(value={})".format(self.value)


x = aliased(X, name='my_x')
y = aliased(Y, name='my_y')

q = session.query(x).outerjoin(y, x.ys.expression & y.value == 'hello')
print(q)
# SELECT my_x.id AS my_x_id
# FROM x AS my_x LEFT OUTER JOIN y AS my_y ON (my_x.id = y.x_id AND my_y.value) = %(param_1)s

print(q.all())
# psycopg2.ProgrammingError: invalid reference to FROM-clause entry for table "y"
```

**Comment by dima-starosud** [comment]
> You can access the .primaryjoin, .secondaryjoin fields of the relationship

Oh, thank you, I will try.

> you need to use parenthesis

Doesn't help:

```
from sqlalchemy import Column, ForeignKey, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, aliased, configure_mappers, relationship
from sqlalchemy.pool import NullPool

engine = create_engine('postgresql://***', poolclass=NullPool)
connection = engine.connect()
connection.begin_nested()
session = Session(connection)

Base = declarative_base()


class X(Base):
    __tablename__ = 'x'
    id = Column(Integer, primary_key=True)
    ys = relationship('Y')

    def __repr__(self):
        return "X(ys={})".format(self.ys)


class Y(Base):
    __tablename__ = 'y'
    id = Column(Integer, primary_key=True)
    x_id = Column(Integer, ForeignKey(X.id))
    value = Column(String)

    def __repr__(self):
        return "Y(value={})".format(self.value)


configure_mappers()
Base.metadata.create_all(connection)

x = aliased(X, name='my_x')
y = aliased(Y, name='my_y')

q = session.query(x).outerjoin(y, x.ys.expression & (y.value == 'hello'))
print(q)
# SELECT my_x.id AS my_x_id
# FROM x AS my_x LEFT OUTER JOIN y AS my_y ON my_x.id = y.x_id AND my_y.value = %(value_1)s

print(q.all())
# sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) invalid reference to FROM-clause entry for table "y"
# LINE 2: ... x AS my_x LEFT OUTER JOIN y AS my_y ON my_x.id = y.x_id AND...
#                                                              ^
# HINT:  Perhaps you meant to reference the table alias "my_y".
```

As I said the problem is that `x.ys.expression` doesn't know about other side `y = aliased(Y, name='my_y')`

**Comment by zzzeek** [comment]
it's because of the aliased and you probably dont want to deal with using clause adaptation which would be necessary here.   so just modify _froms.

**Comment by zzzeek** [comment]
I have work happening right now on a very similar option here: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2062

that issue should probably try to accommodate this one as well.

**Comment by zzzeek** [comment]
ok above I proposed:

```
query(A).join(A.bs.and_(<criteria>))
query(A).options(joinedload(A.bs.and_(<criteria>))
query(A).options(lazyload(A.bs.and_(<criteria>))

```

this would be easier as:

```
query(A).options(joinedload(A.bs).and_(<criteria>))
query(A).options(lazyload(A.bs).and_(<criteria>))

```

meaning it doesn't apply to query.join().   the "A.bs" is already kind of an "expression element" already as it has a `__clause_element__()` method so it might be a little messy to have it there.

**Comment by zzzeek** [comment]
you had mentioned this is mostly for Load in any case.

**Comment by zzzeek** [comment]
nevermind it's going to be a PITA either way

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add new loader criteria option** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2062

**Comment by dima-starosud** [comment]
Thanks a lot @zzzeek, will apply this once upgraded to latest version.

**Comment by dima-starosud** [comment]
Thanks a lot @zzzeek! This is exactly what I needed.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement relationship AND criteria; global loader criteria** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2129

**Comment by coreybrett** [comment]
Would this issue be related to https://stackoverflow.com/questions/63839679/can-i-specify-the-join-conditions-of-a-relationship-when-writing-a-query-instead ?

**Comment by zzzeek** [comment]
seems like it, I suggest giving it a try

**Comment by zzzeek** [comment]
incredibly, it looks like I did this whole issue without ever getting and_() to work for any of the other options.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement PropComparator.and_() for remaining options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2334
