### ISSUE TITLE
Index(postgresql_using='TYPE') wraps index type in extra quotes if it's uppercase

### ISSUE THREAD

**Issue by oscdc** [sqlalchemy/sqlalchemy#4473]
For the PostgreSQL dialect, `Index()` takes a `postgresql_using=` parameter to specify the index type. However, the generated SQL is wrong if the parameter value is uppercase:
```
from sqlalchemy import create_engine
from sqlalchemy.ext import declarative
from sqlalchemy.schema import CreateTable, CreateIndex
from sqlalchemy.sql import schema, sqltypes

Base = declarative.declarative_base()

class MyTable(Base):
    __tablename__ = 'my_table'
    some_column = schema.Column(sqltypes.String(), primary_key=True)
    __table_args__ = (
        schema.Index('my_index', some_column, postgresql_using='BTREE'),
    )

engine = create_engine('postgresql://')
print(CreateTable(MyTable.__table__).compile(engine))
for index in MyTable.__table__.indexes:
    print(CreateIndex(index).compile(engine))
```

This produces the SQL:
`CREATE INDEX my_index ON my_table USING "BTREE" (some_column)`
which is invalid because `"BTREE"` is quoted.

However, if we change it to lowercase: `postgresql_using='btree'`, then it produces valid SQL.

Is the `postgresql_using` argument supposed to be case-sensitive like that?

**Comment by oscdc** [comment]
Thanks for the explanation.

Would it be acceptable to add `btree`, `hash`, `gist`, `gin`, etc., to the set of `RESERVED_WORDS` for the postgresql dialect, since they do sort of act like keywords?

**Comment by zzzeek** [comment]
> Thanks for the explanation.
> 
> Would it be acceptable to add `btree`, `hash`, `gist`, `gin`, etc., to the set of `RESERVED_WORDS` for the postgresql dialect, since they do sort of act like keywords?

well they aren't listed at https://www.postgresql.org/docs/9.6/sql-keywords-appendix.html so we wouldn't note them as such.

**Comment by sanjana96** [comment]
I would like to work on this. I have a branch ready with quoting removed and a test added, would [this ](https://github.com/sqlalchemy/sqlalchemy/compare/master...sanjana96:QuotingIndex)do? I am a first time contributor, please do let me know if anything different is expected.

**Comment by zzzeek** [comment]
@sanjana96 the keyword still needs to be run through a normalization function.   I'm working on this general problem in #4481 right now where I will add some additional functions that are used for literal keywords like these and I will probably pull this in with that, as well as #4467.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove all remaining text() coercions** https://gerrit.sqlalchemy.org/1126
