### ISSUE TITLE
any non-constant as expresion as default in SQLite requires parenthesis

### ISSUE THREAD

**Issue by pax0r** [sqlalchemy/sqlalchemy#4474]
Acording to https://www.sqlite.org/lang_createtable.html expression as default for columns requires brackets in SQLite.

SQLAlchemy renders this without them which causes SYNTAX ERROR.

**Comment by zzzeek** [comment]
had to do a lot more to make this work

**Comment by sqla-tester** [comment]
**Bartlomiej Biernacki** has proposed a fix for this issue in the **master** branch:

**Render parenthesis around sqlite expression defaults** https://gerrit.sqlalchemy.org/1123

**Comment by sqla-tester** [comment]
**Bartlomiej Biernacki** has proposed a fix for this issue in the **rel_1_2** branch:

**Render parenthesis around sqlite expression defaults** https://gerrit.sqlalchemy.org/1121
