### ISSUE TITLE
How to ignore the creation of a specific table

### ISSUE THREAD

**Issue by Sphinxs** [sqlalchemy/sqlalchemy#4478]
I have an OAuth 2.0 application that has a database, user data and token data are stored in this database. I have also another application that has its own database and need to connect to OAuth 2.0 database, to check if the user' token is valid or not, and its own database.

I connect to multiple databases on the second application this way:

```python
# db.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

# app.py
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://' + \
        app.config['DATABASE_USER'] + ':' + \
        app.config['DATABASE_PASSWORD'] + '@' + \
        app.config['DATABASE_HOST'] + '/' + \
        app.config['DATABASE']
    
app.config['SQLALCHEMY_BINDS'] = {
         'oauth': 'mysql://' +
                app.config['DATABASE_USER_OAUTH'] + ':' +
                app.config['DATABASE_PASSWORD_OAUTH'] + '@' +
                app.config['DATABASE_HOST_OAUTH'] + '/' +
                app.config['DATABASE_OAUTH']
    }
```

To check if the user' token is valid or not, on the second application I need to duplicate the user and token models (ORM) generated on the OAuth 2.0 application. The problem is that I just need the duplicated models to create a decorator, but when I generate the second application' database, the models (user and token) are tracked by SQLAlchemy and its structure is created on the second application' database. When I send a token to the second application, the OAuth 2.0 database it's used get token information, this causes a weirdo behavior in my application.

I have set the models to use the OAuth 2.0 connection:
 
```python
# oauth.py
class User(db.Model):
    __bind_key__ = 'oauth'

    __tablename__ = 'oauth2_user'
    
    # ...

class Token(db.Model, OAuth2TokenMixin):
    __bind_key__ = 'oauth'
    
    __tablename__ = 'oauth2_token'

    # ...
```

But it doesn't work. I have also read the table configuration [documentation](https://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/table_config.html?highlight=__table_args__#table-configuration), but I did not found nothing that can help me.

MySQL engine, `Flask-SQLAlchemy==2.3.2, mysqlclient==1.3.14, SQLAlchemy==1.2.15`.

**Obs**: I don't want to create the user and token table on the second application' database, but I want to have the user and token models available and at the same time use the user and token tables present on OAuth 2.0 database

**Comment by zzzeek** [comment]
So this is all flask and I don't know anything about flask.  at http://flask-sqlalchemy.pocoo.org/2.3/binds/ it looks like you need to send a special keyword to db.create_all().  That's not part of SQLAlchemy however.

please consult with the Flask community for further help on this issue thanks!

**Comment by zzzeek** [comment]
just FYI the non-flask way to do this is to simply use two different declarative bases, then call Base.metadata.create_all() on each one individually as needed, see https://docs.sqlalchemy.org/en/latest/orm/persistence_techniques.html#simple-vertical-partitioning

**Comment by Sphinxs** [comment]
@zzzeek , thanks, I have fixed the problem by creating a connection with SQLAlchemy, a session and a `MetaData` object. I get the table structure with the `MetaData` and use it. The issue now it's the methods attributed to the models, I can't get the methods via `MetaData` so...

**Comment by zzzeek** [comment]
> I get the table structure with the MetaData and use it. 

what does that mean exactly?   I'm not sure what pulling Table objects from a MetaData to affect CREATE TABLE DDL has to do with methods on your models.

**Comment by Sphinxs** [comment]
My model on OAuth 2.0 server application looks like:

```python
class User(db.Model):
    __tablename__ = 'oauth2_user'
    
    def check_token(self, token):
        # Check if token is it valid
```

When I get the model via `MetaData` in another application, the SQLAlchemy object is returned and I use it to as argument to the Authlib module, but because I can't get the method `check_token` that Authlib expect, I receive an error.

**Comment by zzzeek** [comment]
why can't you invoke the User class directly?  from myapp import User

**Comment by zzzeek** [comment]
did you try talking on the flask list about any of this?  this is application organization stuff and basic python

**Comment by zzzeek** [comment]
OK, I really think you need to deal with the flask community, this has nothing to do with your original question, sorry.
