### ISSUE TITLE
security issues as reported by 'bandit'

### ISSUE THREAD

**Issue by saobao913** [sqlalchemy/sqlalchemy#4480]
SQLAlchemy-1.2.16

FWIW ...

[main]	INFO	profile include tests: None
[main]	INFO	profile exclude tests: None
[main]	INFO	cli include tests: None
[main]	INFO	cli exclude tests: None
[main]	INFO	running on Python 3.6.7
195 [0.. 50.. 100.. 150.. ]
Run started:2019-01-31 07:28:53.483109

Test results:
>> Issue: [B608:hardcoded_sql_expressions] Possible SQL injection vector through string-based query construction.
   Severity: Medium   Confidence: Medium
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/dialects/mssql/base.py:2164
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b608_hardcoded_sql_expressions.html
2163	                    where session_id = @@SPID
2164	                  """
2165	                    % view
2166	                )

--------------------------------------------------
>> Issue: [B307:blacklist] Use of possibly insecure function - consider using safer ast.literal_eval.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/ext/declarative/clsregistry.py:293
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval
292	        try:
293	            x = eval(self.arg, globals(), self._dict)
294	

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/orm/instrumentation.py:585
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html
584	    env = locals().copy()
585	    exec(func_text, env)
586	    __init__ = env["__init__"]

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/util/compat.py:283
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html
282	    # the code line where the issue occurred
283	    exec(
284	        "def reraise(tp, value, tb=None, cause=None):\n"
285	        "    if cause is not None:\n"

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/util/compat.py:305
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html
304	        if lcl is None:
305	            exec("exec func_text in globals_")
306	        else:

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/util/compat.py:307
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html
306	        else:
307	            exec("exec func_text in globals_, lcl")
308	

--------------------------------------------------
>> Issue: [B303:blacklist] Use of insecure MD2, MD4, MD5, or SHA1 hash function.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/util/langhelpers.py:30
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5
29	        x = x.encode("utf-8")
30	    m = hashlib.md5()
31	    m.update(x)

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/util/langhelpers.py:151
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html
150	def _exec_code_in_env(code, env, fn_name):
151	    exec(code, env)
152	    return env[fn_name]

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/util/langhelpers.py:192
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html
191	    env = {"cls": callable_, "symbol": symbol}
192	    exec(code, env)
193	    decorated = env[location_name]

--------------------------------------------------
>> Issue: [B307:blacklist] Use of possibly insecure function - consider using safer ast.literal_eval.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/util/langhelpers.py:1000
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval
999	
1000	        decorated = eval(code, locals())
1001	        decorated.__defaults__ = getattr(fn, "im_func", fn).__defaults__

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/lib/sqlalchemy/util/langhelpers.py:1460
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html
1459	    env = locals().copy()
1460	    exec(code, env)
1461	    return env["set"]

--------------------------------------------------
>> Issue: [B102:exec_used] Use of exec detected.
   Severity: Medium   Confidence: High
   Location: SQLAlchemy-1.2.16/sqla_nose.py:32
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html
31	    to_bootstrap = "nose"
32	    exec(code, globals(), locals())
33	

--------------------------------------------------

Code scanned:
	Total lines of code: 97395
	Total lines skipped (#nosec): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0.0
		Low: 210.0
		Medium: 30.0
		High: 0.0
	Total issues (by confidence):
		Undefined: 0.0
		Low: 18.0
		Medium: 7.0
		High: 215.0
Files skipped (1):
	SQLAlchemy-1.2.16/doc/build/corrections.py (syntax error while parsing AST from file)

**Comment by zzzeek** [comment]
hi there -

every few years someone runs this tool on our code and sends us the raw results, but unfortunately without making the effort to evaluate (no pun intended) what vulnerabilities bandit is trying to inform the user of in each case and applying it to the use case in question, it illustrates nothing useful.

Suffice to say these are not security issues, if you'd like to report a security issue please refer to the specific use case and describe in detail how it allows an attacker to harm a system.  use of "exec", "eval", or the "md5" functions themselves are not security issues.  If they were, their existence should be reported to the Python maintainers directly.
