### ISSUE TITLE
MySQL Upsert on_duplicate_key_update

### ISSUE THREAD

**Issue by bcochofel** [sqlalchemy/sqlalchemy#4483]
Hi,

I'm trying to upsert a table that has a column named "id" (primary key) and a column named "name" (unique key).

The var "value" is a dict, and the following code gives me:

TypeError: on_duplicate_key_update() takes exactly 1 argument (2 given)

```
try:                                                          
    stmt = insert(dbmeta.tables['Assets']).values(values)     
    ustmt = stmt.on_duplicate_key_update(values)              
    dbconn.execute(ustmt)                                     
    trans.commit()                                            
except exc.SQLAlchemyError as e:                              
    print("[ ERROR ] - Rolling back transation (%s)" % e, file=sys.stderr)                
    trans.rollback()                                          
    return False                                              
return True                                                   
```

What am I doing wrong?

Thanks,
Bruno

**Comment by zzzeek** [comment]
here are the 1.2 docs:

https://docs.sqlalchemy.org/en/rel_1_2/dialects/mysql.html?highlight=on_duplicate_key_update#sqlalchemy.dialects.mysql.dml.Insert.on_duplicate_key_update

the single dictionary form is new in 1.3

**Comment by bcochofel** [comment]
> here are the 1.2 docs:
> 
> https://docs.sqlalchemy.org/en/rel_1_2/dialects/mysql.html?highlight=on_duplicate_key_update#sqlalchemy.dialects.mysql.dml.Insert.on_duplicate_key_update
> 
> the single dictionary form is new in 1.3

Hi, thanks for the quick answer.

Should I describe every column that I want to update? The think is, my dict varies according to the parameters that are passed, so not all the columns go to the dict.
How can I handle this dynamically?

**Comment by zzzeek** [comment]
are you looking for Python star syntax?

    ustmt = stmt.on_duplicate_key_update(**values)

**Comment by bcochofel** [comment]
> are you looking for Python star syntax?
> 
> ```
> ustmt = stmt.on_duplicate_key_update(**values) 
> ```

Hi zzzeek, not quite sure what you mean?

**Comment by zzzeek** [comment]
I'm trying to answer your question "how can I handle this dynamically?"   the usage you have attempted at the top of this question needs only the modification of using **kwargs syntax.   can you please just try this and let me know it solves your problem, thanks.

**Comment by bcochofel** [comment]
Hi, ok, now I understood, thanks.

Closing this topic.

Bruno
