### ISSUE TITLE
The base common file to execute SQL

### ISSUE THREAD

**Issue by liuweiming1997** [sqlalchemy/sqlalchemy#4487]
I am so sorry to ask this question, I can not find the common interface for sqlalchemy to execute SQL. I am a newbee, can someone known can tell me? thanks in advance.

**Comment by zzzeek** [comment]
hi please see:

https://docs.sqlalchemy.org/en/latest/core/connections.html#basic-usage

**Comment by liuweiming1997** [comment]
> hi please see:
> 
> https://docs.sqlalchemy.org/en/latest/core/connections.html#basic-usage

thanks for your reply, but i can not connect to this website, I will try more effort for it

**Comment by zzzeek** [comment]
are you in guangzhou province china?   we've had connectivity issues from there.   Please download the .tar.gz distribution from https://files.pythonhosted.org/packages/c6/52/73d1c92944cd294a5b165097038418abb6a235f5956d43d06f97254f73bf/SQLAlchemy-1.2.17.tar.gz, unzip the file and the HTML documentation is present in doc/ .

**Comment by liuweiming1997** [comment]
yeah, but I proxy to US is not work for me,  thanks a lot

**Comment by liuweiming1997** [comment]
I have see it, emmmm, what I say it how the SQL statements like `INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'lower_case_table_names'` do in using `sessionmaker(bind=engine)`, I found it maybe in `sqlalchemy/orm/query.py`? I do not mean how can i directly execute SQL statements.

**Comment by liuweiming1997** [comment]
I maybe found it in `sqlalchemy/engine/base.py` function `execute`
