### ISSUE TITLE
Sqlalchemy + Sqlite filtering by datetime range is allowed, but returns nonsensical results.

### ISSUE THREAD

**Issue by fake-name** [sqlalchemy/sqlalchemy#4490]
I have a table that uses a sqlite backend, with a few `datetime` typed columns.

```

class BillEntry(db.Model):
	id               = db.Column(db.Integer, primary_key=True)
	bill_name        = db.Column(db.Text, index=True)
	paid_date        = db.Column(db.DateTime, default=datetime.datetime.utcnow)
	amount           = db.Column(db.Float)
	note             = db.Column(db.Text)
	is_money         = db.Column(db.Boolean)


```

I was trying to query the table with date-ranges:

```
			haves = BillEntry.query                       \
				.filter(BillEntry.bill_name == pow_name)  \
				.filter(BillEntry.paid_date > window_min) \
				.filter(BillEntry.paid_date < window_max) \
				.all()
```

This executes perfectly fine, but returns invalid and nonsensical results.  From what I can tell, this is because sqlite doesn't have a datetime type, and therefore the resulting query uses string less-then/greater-then operations.

Now, once I figured out that was what was going on, it's a easy fix, but damn if it wasn't confusing. I would have assumed that a range-based query would result in an exception if the db-backend can't actually *do* the range-based query. 

I can't see any context where the behaviour, as it is now, is actually what anyone would want. It seems to me that the ideal result here is for the query to throw an exception.

**Comment by zzzeek** [comment]
SQLite doesn't have a dedicated datetime type but SQLAlchemy does, which renders a string format simlar to ISO format, including for comparison operations.   For simple greater than / less than / equals comparisons, these strings work fine (assuming no timezone differentiators, which isn't different from any other database).    Here is a demonstration:

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
import datetime

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(DateTime)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add_all([
    A(data=datetime.datetime(2018, 5, 10, 12, 15, 48)),
    A(data=datetime.datetime(2018, 6, 10, 12, 15, 48)),
    A(data=datetime.datetime(2018, 7, 10, 12, 15, 48)),
    A(data=datetime.datetime(2018, 8, 10, 12, 15, 48)),
])
s.commit()

print(
    s.query(A.data).filter(A.data > datetime.datetime(2018, 7, 1, 0, 0, 0)).all()
)
```

output, as you can see the incoming comaprison dates are converted to the same string format and simple comparisons work correctly:

```
2019-02-09 12:04:32,469 INFO sqlalchemy.engine.base.Engine INSERT INTO a (data) VALUES (?)
2019-02-09 12:04:32,469 INFO sqlalchemy.engine.base.Engine ('2018-05-10 12:15:48.000000',)
2019-02-09 12:04:32,469 INFO sqlalchemy.engine.base.Engine INSERT INTO a (data) VALUES (?)
2019-02-09 12:04:32,469 INFO sqlalchemy.engine.base.Engine ('2018-06-10 12:15:48.000000',)
2019-02-09 12:04:32,469 INFO sqlalchemy.engine.base.Engine INSERT INTO a (data) VALUES (?)
2019-02-09 12:04:32,469 INFO sqlalchemy.engine.base.Engine ('2018-07-10 12:15:48.000000',)
2019-02-09 12:04:32,470 INFO sqlalchemy.engine.base.Engine INSERT INTO a (data) VALUES (?)
2019-02-09 12:04:32,470 INFO sqlalchemy.engine.base.Engine ('2018-08-10 12:15:48.000000',)
2019-02-09 12:04:32,470 INFO sqlalchemy.engine.base.Engine COMMIT
2019-02-09 12:04:32,471 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-02-09 12:04:32,471 INFO sqlalchemy.engine.base.Engine SELECT a.data AS a_data 
FROM a 
WHERE a.data > ?
2019-02-09 12:04:32,471 INFO sqlalchemy.engine.base.Engine ('2018-07-01 00:00:00.000000',)
[(datetime.datetime(2018, 7, 10, 12, 15, 48),), (datetime.datetime(2018, 8, 10, 12, 15, 48),)]

```

Where the date stuff does *not* work for SQLite is working with date arithemetic like adding deltas to dates and stuff like that.   For that, you need to use [sqlite's date functions directly](https://www.sqlite.org/lang_datefunc.html).

So if you can please provide an [MCVE](http://stackoverflow.com/help/mcve) that I can run directly here with no dependencies that illustrates your failure, we can more specifically see what's going wrong.  thanks!

**Comment by fake-name** [comment]
Ok, I wrote a minimal example that uses the exact same query.... and it works. It looks like the issue was PEBKAC on my part.

Sorry about the bother.
