### ISSUE TITLE
mysql issue 88718 workaround not tested for windows/osx casing on py2k

### ISSUE THREAD

**Issue by HarshadKavathiya** [sqlalchemy/sqlalchemy#4492]
When we use sqlalchemy in python 2.7, while DB migrates if by default sqlalchemy try to lower "referred_table" but in python 2.7, its get table name as Unicode instead of str. So its raised exception as "TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'".

For more details refer this: https://github.com/sqlalchemy/alembic/issues/533

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add complete coverage and fix lower() for MySQL 88718 workaround** https://gerrit.sqlalchemy.org/1129

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_2** branch:

**Add complete coverage and fix lower() for MySQL 88718 workaround** https://gerrit.sqlalchemy.org/1130

**Comment by zzzeek** [comment]
fixes https://github.com/sqlalchemy/alembic/issues/533
