### ISSUE TITLE
ORM: Flag to force fetch of trigger-computed PK on insert

### ISSUE THREAD

**Issue by braincore** [sqlalchemy/sqlalchemy#4494]
DB: Postgresql

I'm inserting an object with a PK specified into a table. However, there is a table trigger that will rewrite the PK before the final insertion.

If no PK is specified, the trigger populates one. This is handled correctly and I can see that SA is correctly asking for a `RETURNING PK` and then populates the object's PK. However, if I specify a PK, SA omits the return clause for the PK.

I've tried the following:
* Add `FetchedValue()` as an argument to the PK `Column()`.
* Set `eager_defaults` to `True` in `__mapper_args__`. (Did not expect this to work)

This is related to #2598. But unlike in that issue, the initial PK value from the client is important for the creation of the final PK and cannot be easily substituted by a pure server-side computation.

**Comment by zzzeek** [comment]
unfortunately that's not what FetchedValue does right now, because you are providing a value, that indicates that FetchedValue is not in play.  There is no built in feature that supports what you are doing right now so some other means would need to be devised to accommodate what you are looking for.

**Comment by braincore** [comment]
Thanks for the quick reply and for the great library!

How do you imagine the interface (not implementation) for a feature like this? Just in case I decide to make a PR.

I hacked around a bit, and as expected, I see the code that omits the PK from `compiler.returning` and `compiler.postfetch`. For kicks, I tried working around that code, but it fails which I think is because the postfetch assignment of the PK dirties it: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/loading.py#L958

**Comment by zzzeek** [comment]
I haven't thought about how this would be done directly, the INSERT / RETURNING / PK mechanics are extremely intricate due to the already vast number of behavioral combinations, and it's usually not very simple to add a new thing like this.     Take a look at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/crud.py to see where that all happens.

However, I'm working through a few recipes to do this simply.  I have one which works great but makes SELECTs kind of hard.   Trying one more idea now.

**Comment by zzzeek** [comment]
OK here's the recipe that *should* work, and to make it work only needs a small adjustment in the ORM, not in Core, I'm pretty sure, so this is likely feasible as how this should be done:
```

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import FetchedValue
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

from sqlalchemy import literal_column

Base = declarative_base()

class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, server_default=FetchedValue(), primary_key=True)
    data = Column(String)

e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)

Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

a1 = A(data='foo', id=literal_column('1'))
a2 = A(data='foo', id=literal_column('2'))
s.add_all([a1, a2])
s.flush()

# this doesn't work because the ORM doesn't see the PK col as "None",
# would be likely not hard to fix
assert a1.id == 1
assert a2.id == 2

```

next comment, I'll provide a recipe that works right now but is uglier.

**Comment by zzzeek** [comment]
Here's an event based approach that works right now, using a hidden column:

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import FetchedValue
from sqlalchemy import event
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from sqlalchemy.sql import Insert
from sqlalchemy.orm import deferred

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, server_default=FetchedValue(), primary_key=True)
    data = Column(String)

    # a column we'll never load but we want to set on insert
    id_ins = deferred(Column(Integer, system=True))

e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)

@event.listens_for(e, "before_execute")
def before_execute(conn, clauseelement, multiparams, params):
    if isinstance(clauseelement, Insert) and 'id_ins' in clauseelement.table.c:
        if multiparams:
            if isinstance(multiparams[0], dict):
                mp = list(multiparams)
            elif isinstance(multiparams[0], list):
                mp = multiparams[0]

            for param in mp:
                param['id'] = param.pop('id_ins', None) + 5
        else:
            params['id'] = params.pop('id_ins', None) + 5

Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

a1 = A(data='foo', id_ins=1)
a2 = A(data='foo', id_ins=2)
s.add_all([a1, a2])
s.flush()

assert a1.id == 6
assert a2.id == 7

s.query(A).all()

```

**Comment by braincore** [comment]
Thanks so much!

My first adaptation of your events-based workaround isn't working. The PK is not being populated.

The assignment of `param['id'] = param.pop('id_ins', None) + 5` (multiparams branch) is removing the `RETURNING PK` clause. Upon removing the assignment, the clause re-appears.

Possible confounding issues:
* `id_ins` is specified in a `Mixin` so I'm using `@declared_attr`.
* I'm using multiple engines as part of a `ShardedSession` so I create an event handler for each engine.

Note: I haven't tried your example verbatim yet, simply an adapted version. I'll try it later today.

**Comment by braincore** [comment]
Also, happy to test out whatever ORM patch is needed for your first solution.

**Comment by braincore** [comment]
Are you sure the param modification can happen in a `before_execute` event? Perhaps it's only possible without disturbing the returning clause in [`before_cursor_execute`](https://docs.sqlalchemy.org/en/latest/core/events.html#sqlalchemy.events.ConnectionEvents.before_cursor_execute)?

**Comment by zzzeek** [comment]
in #3133 we already have a patch to fix for ORM.  Can you upgrade to 1.3 final for your behavior?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Allow SQL expression for ORM primary keys** https://gerrit.sqlalchemy.org/1131

**Comment by zzzeek** [comment]
if you can try the gerrit patch linked above that would be the feature.

**Comment by braincore** [comment]
Patch works! It's a little bit cumbersome having to specify a SQL expression (my primary key is in fact a postgresql composite type), but I trust that's a necessary evil. I'll be using this immediately and look forward to it landing in master & the next release. Thank you!

**Comment by zzzeek** [comment]
use any kind of event, most expediently, @validates, to set the SQL expression when a numeric ID is passed (also you can just use literal() which renders as a bind parameter).   Using the SQL expression indicates that the actual value must be evaluated by the server, so it's a somewhat reasonable hint that the extra round trip is needed.    

```
from sqlalchemy.orm import validates
class MyClass(Base):
   @validates("id")
   def _id_as_expr(self, key, value):
       return literal(value)


```

**Comment by braincore** [comment]
I was doing the literal transformation in my `shard_chooser` callback, but using `validates()` looks less fragile--great. SA has an enormous number of capabilities :).

By the way, why do you suggest that there's an extra round trip? Are you referring to DBs without support for returning?

**Comment by braincore** [comment]
@zzzeek I've been experimenting with migrating to 1.4 and it appears this issue is now a regression. Given the extensive changes in v1.4, I'm wondering if your recommended solution has changed, or if this issue requires another patch. As discussed before, I've been using `literal()` to replace the partially-specified PK by the client with the finalized PK generated by the server.

**Comment by CaselIT** [comment]
it's also probably best to start a new issue if you can post a mcve so we can better track this
