### ISSUE TITLE
Bug on delete oll and insert new.

### ISSUE THREAD

**Issue by heckad** [sqlalchemy/sqlalchemy#4497]
I have this code.
```
def save_all_allowed_fields():
    AllowedFieldsModel.query.delete()
    db.session.commit()

    db.session.add_all(set(
        AllowedFieldsModel(field_name=n)
        for n in request.json.get('fields')
    ))

    db.session.commit()

    return '', 204
```
and get error 
```
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "allowed_fields_pkey"
DETAIL:  Key (field_name)=(profileType) already exists.
```
Way it is heppens if I deleted all rows?
version of alchemy 1.2.15, python 3.7

**Comment by zzzeek** [comment]
hi there -

the above code contains no context that could be used to illustrate what is actually happening.   Based on visual inspection only, the issue would indicate that you have duplicate keys inside of your `request.json.get('fields')` list.    Or perhaps `AllowedFieldsModel.query.delete()` is invoking on a different transaction.   It's impossible to say without a complete [MCVE](http://stackoverflow.com/help/mcve), please provide one thanks!

**Comment by heckad** [comment]
I am use set, because duplicate keys cann't be. Sessions provides by flask_sql alchemy. As far as I know it does not creates a new session.

**Comment by zzzeek** [comment]
there's a set, OK.   

So the only other possibility is that AllowedFieldsModel.query.delete() is running on a different transaction / Session.    This would be a flask issue and you'd need to work with the flask community to figure it out.  If you cannot produce a reproducing test case, you would need to continue debugging this by using echo=True and watching the SQL being emitted to further understand what may be going on.

other than that there's nothing I can offer here.

**Comment by zzzeek** [comment]
feel free to continue discussion and especially if you have SQL output to show or a working test case, closing this for now.

**Comment by gocreating** [comment]
Same problem.

I just try to delete filterd rows

```
for b in a.bs:
    session.delete(b)
session.commit()
```

and the duplicate key error happened:

```
sqlalchemy.exc.IntegrityError: (pyodbc.IntegrityError) ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'xxxxxxxxx'. Cannot insert duplicate key in object 'xxxx.yyy'. The duplicate key value is (<NULL>, xxxxxxx). (2627) (SQLExecDirectW)")
```
