### ISSUE TITLE
Error Message Formatting : Missing Bind Parameter

### ISSUE THREAD

**Issue by natec425** [sqlalchemy/sqlalchemy#4500]
Hey hey,

I'm just looking for comments/interest on changing the error formatting for `StatementError`. I'm interested in making small changes at the two lines below:
- Change `%r` to `%s` so that multi-line SQL statements appear formatted in a way that would be more quickly recognized by its author.

https://github.com/sqlalchemy/sqlalchemy/blob/4d7ac4be6c2f548b2e54d015003028bd9d10c805/lib/sqlalchemy/exc.py#L349

- Join on `"\n"` instead of `" "` in hopes of improved readability

https://github.com/sqlalchemy/sqlalchemy/blob/4d7ac4be6c2f548b2e54d015003028bd9d10c805/lib/sqlalchemy/exc.py#L356

For example, this makes the difference between the two error messages:

```
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id' [SQL: 'select * from reviews where id = %(id)s'] (Background on this error at: http://sqlalche.me/e/cd3x)

(sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id' [SQL: 'select * from reviews where id = %(id)s'] (Background on this error at: http://sqlalche.me/e/cd3x)
```

becomes

```
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id'
[SQL: (select * from reviews where id = %(id)s)]
(Background on this error at: http://sqlalche.me/e/cd3x)

(sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id'
[SQL: (select * from reviews where id = %(id)s)]
(Background on this error at: http://sqlalche.me/e/cd3x)
```

If this sounds alright. I'd be happy to make a PR :smile: 

Thanks for your time.

**Comment by zzzeek** [comment]
looks nicer but I worry the use case of grepping logs might be impacted.  though the error message itself is still staying on one line so maybe it wont be so bad.  we're right at the edge of me wanting to release 1.3.0 final so, that's where it would have to be.      I'd be happy to evaluate a PR to see what it ends up looking like.

**Comment by sqla-tester** [comment]
**Nate Clark** has proposed a fix for this issue in the **master** branch:

**Issue #4500 : Change StatementError formatting (newlines and %s)** https://gerrit.sqlalchemy.org/1136
