### ISSUE TITLE
Engine password stored/sent incorrectly

### ISSUE THREAD

**Issue by hodossy** [sqlalchemy/sqlalchemy#4503]
I am on Windows and Python 3.6 with SQLAlchemy 1.2.17.

My password that I used (I changed it already) is not sent to the server as specified, therefore the login fails.

 ``` python
import sqlalchemy as sa
    
my_password = r'~%Fa9C!.0%j~b;st*0_j729;;%5!.b_W'
engine = sa.create_engine(
    f'postgresql://user:{my_password}@myhost.com:5432',
    use_batch_mode=True,
    connect_args= {'application_name': 'my app'}
)
assert my_password == engine.url.password, 'Passwords do not match'
```

The above password is transformed to `~�9C!.0%j~b;st*0_j729;;%5!.b_W`

**Comment by zzzeek** [comment]
passwords with special characters must be URL encoded

please see https://docs.sqlalchemy.org/en/latest/core/engines.html?highlight=url%20encode#database-urls

**Comment by zzzeek** [comment]
follow the above instructions and let us know that solves your problem

**Comment by hodossy** [comment]
Yes, it does! Sorry I have overlooked that part of the docs :(
