### ISSUE TITLE
no documentation for extract

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4504]
there are no usage examples here and nobody has any idea how to use extract:

https://docs.sqlalchemy.org/en/latest/core/sqlelement.html?highlight=extract#sqlalchemy.sql.expression.extract

the constructor on Extract claims there are full usage docs but I think this is an auto-generated message and it is wrong.

**Comment by zzzeek** [comment]
this is still the case, extract has zero docs

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Fixes: #4504** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3111
