### ISSUE TITLE
Oracle type NCHAR is not supported by OracleDialect.get_columns

### ISSUE THREAD

**Issue by altvod** [sqlalchemy/sqlalchemy#4506]
If you try to inspect an Oracle table with `NCHAR` columns, they are returned as `NullType()`
The following code demonstrates it:
```
import sqlalchemy as sa
e = make_engine()  # create your Oracle engine somehow
table = sa.Table(
    'my_table', sa.MetaData(),
    sa.Column(name='my_char', type_=sa.CHAR()),
    sa.Column(name='my_nchar', type_=sa.NCHAR()),
)
table.drop(e, checkfirst=True)
table.create(e)
for col in sa.inspect(e).get_columns('my_table'):
    print(col['name'], repr(col['type']))
```

It will print:
```
my_char CHAR(length=1)
my_nchar NullType()
```

**Comment by zzzeek** [comment]
OK this just needs to be added to ischema_names and some other places, and by the time I work out all the spots for someones PR, the patch is here so I'll just push that up

**Comment by zzzeek** [comment]
you can do this for now:

```
from sqlalchemy.types import NCHAR
from sqlalchemy.dialects.oracle import base
base.ischema_names['NCHAR'] = NCHAR
```

the reflected datatype will just be missing the length at the moment.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add NCHAR to Oracle dialect** https://gerrit.sqlalchemy.org/1138

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_2** branch:

**Add NCHAR to Oracle dialect** https://gerrit.sqlalchemy.org/1139
