### ISSUE TITLE
feature suggestion: configurable delimiter for use_labels/apply_labels

### ISSUE THREAD

**Issue by brianmaissy** [sqlalchemy/sqlalchemy#4508]
I have a use case in which I execute selects on joins with use_labels=True, and then pass the RowProxy objects to a function for automatic processing.

In addition to preventing collisions of column names, use_labels also allows me to automatically separate the fields from different tables from each other.

The only minor problem is that if my table names have underscores in them, I can't deterministically determine the table name from the labelled column name without either aliasing the tables to a name without an underscore, or passing metadata about the possible table names to the postprocessing function.

If the underscore delimiter between the table name and column name that sqlalchemy uses to generate the labels was configurable, I would be able to choose a delimiter that I know does not appear in any of my table names, such as double underscore.

Is there another workaround that I haven't considered?

Does this sound like something which would be useful for other use cases? If not, I don't want to promote feature bloat. If so, and it sounds implementable, I'd be happy to take a crack at it.

**Comment by zzzeek** [comment]
hi there -

The feature seems to be very targeted at a small part of what may be a larger usage issue.   How is it that your row processing functions are aware of the concept of table names and column names embedded as keys in a result row but it does not know anything about those names?  is it producing some kind of nested structure?   Why can't this nested structure be generated more closely from the metadata that generated the result row (e.g. row[table.c.column]) ?

**Comment by brianmaissy** [comment]
Wow, very impressive intuition. Yes, I am building a nested structure, and yes, if my postprocessing function was aware of the query which generated the results, it would be able to intelligently build the structure.

I was hoping to simplify the implementation, and make it agnostic of the source of the data, by having it intuit the structure of the data to a certain extent just based on the labels of the result columns.

In the complex case (higher levels of nesting) I have an explicit way of describing the structure I want, but in the simple case of one root object joined with one or more "first degree nested" objects I thought it would be cute to be able to guess correctly automatically.

But now that I describe it in those terms, if I really wanted it to be data source agnostic, then it doesn't make sense to require a specific input format, because that makes it by definition non-agnostic.

So i think that answers my question: it is not a generic use case.

**Comment by brianmaissy** [comment]
The larger issue at play, which may actually be relevant to sqlalchemy but is way out of my place to suggest, is a way to get nested objects from an sqlalchemy core query, a sort of unidirectional ORM. I don't know how often you get that request, but it's the underlying issue here.

**Comment by zzzeek** [comment]
oh you used the "G" word (guess), good avoidance of temptation ! :)
