### ISSUE TITLE
prevent Alias class and subclasses from direct construction

### ISSUE THREAD

**Issue by f0rk** [sqlalchemy/sqlalchemy#4509]
```
from sqlalchemy import create_engine, Column, Integer, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy.sql.expression import Alias

engine = create_engine("sqlite://")
session = scoped_session(sessionmaker(autocommit=False, autoflush=False, bind=engine))

class Base(object):
    pass

Base = declarative_base(cls=Base)

class Member(Base):

    __tablename__ = "members"

    id = Column(Integer, primary_key=True)
    name = Column(Text)

Base.metadata.create_all(engine)

members = session.query(Member)
members_cte = members.cte()
members_alias = Alias(members_cte, "some_name")
final = session.query(*[c for c in members_alias.c])
print(str(final))
```

Which outputs:
```
SELECT some_name.id AS some_name_id, some_name.name AS some_name_name
FROM (SELECT members.id AS id, members.name AS name
FROM members) AS some_name
```

I expect:

```
WITH anon_1 AS 
(SELECT members.id AS id, members.name AS name 
FROM members)
 SELECT some_name.id AS some_name_id, some_name.name AS some_name_name 
FROM anon_1 AS some_name
```

It appears that the `__init__` method of `Alias` is the cause, which does:
```
while isinstance(baseselectable, Alias):
    baseselectable = baseselectable.element
```

Because `CTE` inherits from `Alias`, this code walks down into the underlying element of the `CTE`. Perhaps the correct solution here is to use the following instead:
```
while type(baseselectable) is Alias:
    baseselectable = baseselectable.element
```

**Comment by zzzeek** [comment]
haven't looked closely but I think that is the correct behavior, alias() of a selectable means subquery.  if you want your CTE to have a name, you give it a name directly: https://docs.sqlalchemy.org/en/latest/core/selectable.html?highlight=cte#sqlalchemy.sql.expression.Select.cte.params.name

i think there may have been some other issue that touched upon this I'd have to search for it.

**Comment by zzzeek** [comment]
#4204, #4319 deal with this kind of thing a bit

**Comment by f0rk** [comment]
I would argue then that the documentation is wrong, which describes `Alias` as such: "Represents an alias, as typically applied to any table or sub-select within a SQL statement using the AS keyword"

**Comment by f0rk** [comment]
Oh, maybe I misunderstood what you were saying. I don't want to give my CTE a name. The original issue is that I am trying to alias a CTE multiple times and they all render as subqueries a la:
```
from sqlalchemy import create_engine, Column, Integer, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy.sql.expression import Alias

engine = create_engine("sqlite://")
session = scoped_session(sessionmaker(autocommit=False, autoflush=False, bind=engine))

class Base(object):
    pass

Base = declarative_base(cls=Base)

class Member(Base):

    __tablename__ = "members"

    id = Column(Integer, primary_key=True)
    name = Column(Text)

Base.metadata.create_all(engine)

members = session.query(Member)
members_cte = members.cte()
members_1 = Alias(members_cte, "some_1")
members_2 = Alias(members_cte, "some_2")
final = session.query(members_1.c.name, members_2.c.name).join(members_2, members_1.c.id == members_2.c.id)
print(str(final))
```

Output:
```
SELECT some_1.name AS some_1_name, some_2.name AS some_2_name
FROM (SELECT members.id AS id, members.name AS name
FROM members) AS some_1 JOIN (SELECT members.id AS id, members.name AS name
FROM members) AS some_2 ON some_1.id = some_2.id
```

**Comment by zzzeek** [comment]
OK now I have looked closely.  Here is your problem.   `Alias()` is not intended to be called directly:

https://docs.sqlalchemy.org/en/latest/core/selectable.html?highlight=alias#sqlalchemy.sql.expression.Alias

> This object is constructed from the alias() module level function as well as the FromClause.alias() method available on all FromClause subclasses.

if you call `your_cte.alias()` or `alias(your_cte)`, it does the appropriate transformations as recorded by the CTE.

**Comment by f0rk** [comment]
I agree, however, it is also not really accurate to say that your_cte.alias() creates this Alias object, because it creates a new CTE. I'm having another issue where your_cte.alias() combined with a replacement traversal loses the name of the CTE and generates alias AS alias which I'm still trying to work through.

Although, if Alias shouldn't be used directly, probably should document that, too.

**Comment by zzzeek** [comment]
CTE is an Alias subclass so it is an Alias.    let's work with test cases.

I've never seen anyone use `Alias` directly and I'm not sure how you found it without reading the documentation.   It does state "this object is construct from the alias() module level function" which is the same for everything else in Core, e.g. select() -> Select, cte() -> CTE(), etc.    The only way to improve this would be to convert the Alias.__init__ method into the public factory for Alias (a later improvement which is why people don't hit this for Select) which I am attempting to do now.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Prevent __init__ from being called for Alias, subclasses** https://gerrit.sqlalchemy.org/1142

**Comment by zzzeek** [comment]
also replacement traversal is very hard.  it's a public use case but it is really 99.999% for the benefit of the ORM internals.
