### ISSUE TITLE
Missing test case for as_interface

### ISSUE THREAD

**Issue by tonikarppi** [sqlalchemy/sqlalchemy#4511]
Hi.

I'd like to submit a PR to add a test case which is missing for: https://github.com/sqlalchemy/sqlalchemy/blob/7a4c40ff6b9d278529735c792c3ddfda60bd4a85/lib/sqlalchemy/util/langhelpers.py#L791-L792

Currently the line is not covered by branch coverage when running `coverage run --branch -m pytest test/base/test_utils.py`. This is the relevant output from the annotation functionality in the coverage.py tool:
```
>     if not cls and not methods:
!         raise TypeError("a class or collection of method names are required")
```

**Comment by sqla-tester** [comment]
**Toni Karppi** has proposed a fix for this issue in the **master** branch:

**Add test to as_interface when no cls or methods** https://gerrit.sqlalchemy.org/1143

**Comment by zzzeek** [comment]
thanks!
