### ISSUE TITLE
sqlalchemy orm validates decorator.

### ISSUE THREAD

**Issue by lohxx** [sqlalchemy/sqlalchemy#4518]
Is it possible to use the validates decorator in a classical mapping?

https://docs.sqlalchemy.org/en/latest/orm/mapped_attributes.html

**Comment by zzzeek** [comment]
yes, use it in your class normally:

```
class MyClass(object):
   @validates('foo')
   def validate(self, key, value):
        return value

mapper(MyClass, my_table)

```

**Comment by lohxx** [comment]
Okay, thanks!
