### ISSUE TITLE
proposal: don't call pre-ping for brand new connection

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4524]
not sure if this is worth the complexity, however it is slightly (very slightly) wasteful to do a pre-ping when we just made a new connection.   review to follow.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't call pre_ping for fresh connection** https://gerrit.sqlalchemy.org/1156
