### ISSUE TITLE
Documentation: multiprocessing connections

### ISSUE THREAD

**Issue by jmarshall9120** [sqlalchemy/sqlalchemy#4526]
can you clarify the below:

```
from sqlalchemy import event
from sqlalchemy import exc
import os

eng = create_engine("...")

@event.listens_for(engine, "connect")
def connect(dbapi_connection, connection_record):
    connection_record.info['pid'] = os.getpid()

@event.listens_for(engine, "checkout")
def checkout(dbapi_connection, connection_record, connection_proxy):
    pid = os.getpid()
    if connection_record.info['pid'] != pid:
        connection_record.connection = connection_proxy.connection = None
        raise exc.DisconnectionError(
                "Connection record belongs to pid %s, "
                "attempting to check out in pid %s" %
                (connection_record.info['pid'], pid)
        )
```

found [here](https://docs.sqlalchemy.org/en/latest/core/pooling.html)

what is `engine` supposed to be in 
  `@event.listens_for(engine, "connect")`

is it supposed to be:
  1. the `eng` object?
  2. sqlalchemy.engine?
  3. sqlalchemy.Engine?
  4. something else?

**Comment by zzzeek** [comment]
> can you clarify the below:
> 
> ```
> from sqlalchemy import event
> from sqlalchemy import exc
> import os
> 
> eng = create_engine("...")
> 
> @event.listens_for(engine, "connect")
> def connect(dbapi_connection, connection_record):
>     connection_record.info['pid'] = os.getpid()
> 
> @event.listens_for(engine, "checkout")
> def checkout(dbapi_connection, connection_record, connection_proxy):
>     pid = os.getpid()
>     if connection_record.info['pid'] != pid:
>         connection_record.connection = connection_proxy.connection = None
>         raise exc.DisconnectionError(
>                 "Connection record belongs to pid %s, "
>                 "attempting to check out in pid %s" %
>                 (connection_record.info['pid'], pid)
>         )
> ```
> 
> found [here](https://docs.sqlalchemy.org/en/latest/core/pooling.html)
> 
> what is `engine` supposed to be in
> `@event.listens_for(engine, "connect")`
> 
> is it supposed to be:
> 
>     1. the `eng` object?

yes

> 
>     3. sqlalchemy.Engine?

it could be this also, see https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=checkout#sqlalchemy.events.PoolEvents
