### ISSUE TITLE
1.3.0 Tables not loading / TypeError

### ISSUE THREAD

**Issue by alex067** [sqlalchemy/sqlalchemy#4530]
With the latest 1.3.0 release last night, we have been having issues loading tables using pymssql. The error we receive is:

```
File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/mssql/base.py", line 2533, in get_columns
    coltype = coltype(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'scale'
```

After going through the sqlalchemy source code, it looks like the float datatypes for mssql use something called "scale." We noticed that our tables containing float datatypes (our db uses ms sql server), produce the TypeError mentioned above. We are able to load tables without float datatypes just fine. 

Once we rolledback sqlalchemy to 1.2.9, our tables containing floats have loaded just fine. 

Just a heads up with anyone else having the same issue.

**Comment by zzzeek** [comment]
already fixed in #4525
