### ISSUE TITLE
we've been testing the wrong version of mysql-connector-python

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4531]
I've been getting mysql-connector from : https://pypi.org/project/mysql-connector/

this is no longer the driver!  the official pypi is now:  https://pypi.org/project/mysql-connector-python/  

where the version is now 8.0.15.    Test suite seems to be passing close to normal for this one.   let's put it in a gerrit and see if everything passes.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Re-enable mysql-connector-python** https://gerrit.sqlalchemy.org/1161

**Comment by zzzeek** [comment]
I unfortunately don't have time to work on this, mysql-connector-python is still not passing all tests and as we already have two drivers that work great this is not the best use of my time.

**Comment by zzzeek** [comment]
can be reopened if someone wants to work on this
