### ISSUE TITLE
filter boolean column of ORACLE error.

### ISSUE THREAD

**Issue by whdxwym** [sqlalchemy/sqlalchemy#4533]
I use cx_oracle in my oracle connection. my model has a column with boolean value. After add a record, it stores 1 as the value. I filter records with this column using conditon `mymodel.mycolumn.is_(True)` will produce error, I have to write `mymodel.mycolumn == 1`. I do not know if this issue is caused by cx-oracle or by sqlalchemy.

**Comment by zzzeek** [comment]
use `column == True`.  The `is_()` operator is not database agnostic for boolean values because not every backend has a "true" constant.

**Comment by whdxwym** [comment]
you're right. thank you. I use `is_()` from google search results, it seems not the answer.

**Comment by zzzeek** [comment]
the whole == / is_ thing could be refined some day to "just work" but for now that's the way it is.
