### ISSUE TITLE
AssociationProxy does not accept cascade_scalar_deletes as a keyword argument.

### ISSUE THREAD

**Issue by Drvanon** [sqlalchemy/sqlalchemy#4534]
When I try to add `cascade_scalar_delete` to the arguments of association_proxy I get the following error:
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    class A(Base):
  File "main.py", line 12, in A
    b_assoc = relationship("Association", back_populates="a", cascade_scalar_deletes=True)
TypeError: relationship() got an unexpected keyword argument 'cascade_scalar_deletes'
```
While in the [documentation](https://docs.sqlalchemy.org/en/latest/orm/extensions/associationproxy.html#sqlalchemy.ext.associationproxy.AssociationProxy) I see that it should be an argument.

Code to reproduce error:
```python
from sqlalchemy import Table, Column, Integer, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.associationproxy import association_proxy, AssociationProxy

Base = declarative_base()

class A(Base):
    __tablename__ = 'a'
    id = Column(Integer, primary_key=True)

    b_assoc = relationship("Association", back_populates="a", cascade_scalar_deletes=True)
    bs = association_proxy("b_assoc", "b")

class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)

    a_assoc = relationship("Association", back_populates="b")

class Association(Base):
    __tablename__ = 'ab'
    a_id = Column(Integer, ForeignKey('a.id'), primary_key=True)
    b_id = Column(Integer, ForeignKey('b.id'), primary_key=True)

    a = relationship("A", back_populates='b_assoc')
    b = relationship("B", back_populates='a_assoc')

if __name__=="__main__":
    a = A()
    b = B()
    asso = Association()
    asso.a = a
    asso.b = b
    print(a.bs)
    a.bs.remove(b)
    print(a.bs)
```

**Comment by zzzeek** [comment]
hi there -

the argument you refer towards is on the association_proxy object, not relationship():
```

class A(Base):
    __tablename__ = 'a'
    id = Column(Integer, primary_key=True)

    b_assoc = relationship("Association", back_populates="a")
    bs = association_proxy("b_assoc", "b", cascade_scalar_deletes=True)

```

**Comment by zzzeek** [comment]
however, "bs" in this case is a collection so the `cascade_scalar_deletes` argument does not have any effect here.

Here is an example of cascade_scalar_deletes:

https://docs.sqlalchemy.org/en/latest/changelog/migration_13.html#association-proxy-has-new-cascade-scalar-deletes-flag

**Comment by zzzeek** [comment]
I've added this to the documenation for the parameter itself.

**Comment by Drvanon** [comment]
Hi, 
Thanks for the super quick response! How would you recommend implementing this in the list scenario? I would be really interested in that case.

**Comment by zzzeek** [comment]
the behavior of removing the intermediary object is already the default for lists.

you might want to add `cascade="all, delete-orphan" to your relationship though, perhaps this is what you're looking for ?  https://docs.sqlalchemy.org/en/latest/orm/cascades.html?highlight=cascades#delete-orphan

**Comment by Drvanon** [comment]
That does the trick. Thanks a lot! I had not come up with the thought that the fix would be at the `relationship`. I assumed it to be at the a `association_proxy`.

**Comment by zzzeek** [comment]
the association proxy is entirely an add-on that rides on top of the usual mapping/relationship system.  it doesn't do anything with persistence or object relational mapping, it only moves Python attributes and collections around.

**Comment by Drvanon** [comment]
Thanks again! This was my first issue, it has been a pleasure.
