### ISSUE TITLE
documentation for pyodbc is incorrect for python 3

### ISSUE THREAD

**Issue by htp84** [sqlalchemy/sqlalchemy#4542]
In the [documentation](https://docs.sqlalchemy.org/en/latest/dialects/mssql.html#module-sqlalchemy.dialects.mssql.pyodbc) for pyodbc, at **Pass through exact Pyodbc string**, *urllib.quote_plus()* is used. This only works for python 2. For python 3, *urllib.**parse**.quote_plus()* should be used.

**Comment by zzzeek** [comment]
PRs welcome

**Comment by zzzeek** [comment]
(just change to the Python 3 version unconditionally)

**Comment by cksajil** [comment]
Which file do I have to change in order to add this information to the documentation?

**Comment by zzzeek** [comment]
https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mssql/pyodbc.py#L53

**Comment by ericdeansanchez** [comment]
I went ahead and made the change and submitted a PR. Tried to do it earlier this weekend, but ```conda``` damaged itself (somehow) on an install...

**Comment by sqla-tester** [comment]
**ericdeansanchez** has proposed a fix for this issue in the **master** branch:

**Changed urllib.quote_plus to urllib.parse.quote_plus (Python 3 versio…** https://gerrit.sqlalchemy.org/1170

**Comment by cksajil** [comment]
@zzzeek Thank you.
