### ISSUE TITLE
_emit_insert_statements does groupby() on unsorted lists

### ISSUE THREAD

**Issue by qris** [sqlalchemy/sqlalchemy#4547]
https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/persistence.py has:

    for (
        (connection, pkeys, hasvalue, has_all_pks, has_all_defaults),
        records,
    ) in groupby(
        insert,
        lambda rec: (
            rec[4],  # connection
            set(rec[2]),  # parameter keys
            bool(rec[5]),  # whether we have "value" parameters
            rec[6],
            rec[7],
        ),
    ):

I don't think that `records` is sorted by all of the key returned by the `lambda` function. The [groupby function](https://docs.python.org/2/library/itertools.html#itertools.groupby) "generates a break or new group every time the value of the key function changes (which is why it is usually necessary to have sorted the data using the same key function)."

This doesn't cause any major problems, but can result in fewer INSERTs being executed in a single batch than would otherwise be possible.

**Comment by zzzeek** [comment]
the INSERT statements need to be inserted in a specific ordering based on when they were added to the session as well as to satisfy inter-row dependencies.  They are sorted that way first.  Whether or not some of the INSERT statements have different organizations of parameters is secondary.

that is, try sorting the records, then run the test suite.  it should fail unless I've totally forgotten how this works.

**Comment by zzzeek** [comment]
yeah the ordering there is the order in which records were add()'ed.  it does not seem to impact inter-row-sorting for self-referential relationships or inheritance.

if performance is a concern that's what batch mode is for, give it a list of identically structured rows and you get just one big insert.

**Comment by zzzeek** [comment]
OK no plans to change this right now feel free to continue discussion
