### ISSUE TITLE
Allow modifying rendered query before execution

### ISSUE THREAD

**Issue by sveniu** [sqlalchemy/sqlalchemy#4548]
Feature request: Allow modifying the rendered query, right before it is executed.

Use case: I would like to add trace details as a comment, embedded as a prefix before the query itself. The trace details would contain things like a trace ID (propagated from an X-Trace-ID HTTP header, for example), the true client IP, application ID, API endpoint that spawned this query, etc.

Example, before:
```
SELECT 1;
```

After:
```
/*
{
  "trace_id":"1234",
  "client_ip":"1.2.3.4"
}
*/
SELECT 1;
```

Log analysis, or something like the Postgres pg_stat_statements view, can then extract these details to gain a much greater insight into the database workload on a per-query basis.

I'd be interested in hearing what are some ways to approach this, to give it a go myself.

**Comment by zzzeek** [comment]
are you looking for the [before_execute](https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=before_execute#sqlalchemy.events.ConnectionEvents.before_execute) or [before_cursor_execute](https://docs.sqlalchemy.org/en/latest/core/events.html?highlight=before_execute#sqlalchemy.events.ConnectionEvents.before_cursor_execute) hooks ?

**Comment by zzzeek** [comment]
there is also [@compiles](https://docs.sqlalchemy.org/en/latest/core/compiler.html#changing-the-default-compilation-of-existing-constructs) which some people like to use for this case though the execute hooks are more what I had in mind for this kind of use case

**Comment by sveniu** [comment]
The before_cursor_execute hook indeed looks useful here. I'll try out a prototype using that. When looking at it, I had some trouble to figure out from the docs what the hook function can actually return, but it seems to be `return statement, parameters`.

Next, I was thinking that the original "context" (not ExecutionContext) is lost, and that the hook would be unable to obtain useful information. For example, how would it get the client IP, which was known to the caller, but lost when calling sqlalchemy?

In my case, lots of useful info is available in the runtime environment (wsgi), so the IP and other HTTP-related data is readily available. Another, even less graceful, solution would be to overload `parameters` with something like `{"metadata:somekey":"value"}` pairs, to be read by the hook and propagated to the SQL comment, and ignored by the underlying psycopg2, for example.

**Comment by zzzeek** [comment]
> The before_cursor_execute hook indeed looks useful here. I'll try out a prototype using that. When looking at it, I had some trouble to figure out from the docs what the hook function can actually return, but it seems to be `return statement, parameters`.
> 
> Next, I was thinking that the original "context" (not ExecutionContext) is lost, and that the hook would be unable to obtain useful information. For example, how would it get the client IP, which was known to the caller, but lost when calling sqlalchemy?

well, you either have to put that information somewhere that you can reach it down the stack, or if you were looking for a more hacky way, you could use python stack frame inspection to reach *up* the stack.  Clearly you're looking to add that information to your statement and / or your execution so you would need to pass that along.    if you want your event hook to see it, your two options are the statement itself or the execution context.   As far as *publicly* available places to do that right now, you can use execution_options, e.g., `conn.execution_options(my_opts={"trace_id": "1234"}).execute(stmt)`, and you can also use the .info dictionary on connection and other objects, an example of this case used to augment statements with comments from the ORM is at https://github.com/sqlalchemy/sqlalchemy/wiki/SessionModifiedSQL.     I think these two dictionaries come out to be about the same thing for a case like this so you might as well use .info which is the more "public" hook for arbitrary collections.




> 
> In my case, lots of useful info is available in the runtime environment (wsgi), so the IP and other HTTP-related data is readily available. Another, even less graceful, solution would be to overload `parameters` with something like `{"metadata:somekey":"value"}` pairs, to be read by the hook and propagated to the SQL comment, and ignored by the underlying psycopg2, for example.

**Comment by sveniu** [comment]
Nice, `.info` looks suitable, and the example on the wiki is spot on. In my case, I'll gradually add the context manager to the code base, and then it would also be prudent to use after_cursor_execute to remove .info params again, to avoid them leaking over to the next use of the connection/session, when it's reused where the context manager is not yet in place.

Thanks for pointing me in the right direction!

**Comment by zzzeek** [comment]
well then great!  we're done
