### ISSUE TITLE
with_for_update of kwarg invalid SQL on JTI subclass

### ISSUE THREAD

**Issue by raylu-bench** [sqlalchemy/sqlalchemy#4550]
When using joined table inheritance, querying for a child model automatically joins to the parent model. When passing the child model to `with_for_update`'s `of` kwarg like `with_for_update(of=Engineer)`, this results in invalid SQL like
```sql
FOR UPDATE OF engineer JOIN employee ON engineer.id = employee.id
```

mildly related: #4100

**Comment by sqla-tester** [comment]
**raylu** has proposed a fix for this issue in the **master** branch:

**Fix PostgreSQL for_update on JTI subclasses** https://gerrit.sqlalchemy.org/1171

**Comment by sqla-tester** [comment]
**raylu** has proposed a fix for this issue in the **master** branch:

**Expand joins when calculating PostgreSQL "WITH FOR UPDATE OF"** https://gerrit.sqlalchemy.org/1171
