### ISSUE TITLE
Foreign Key Constraint In Different Database Support

### ISSUE THREAD

**Issue by datadidit** [sqlalchemy/sqlalchemy#4553]
Hi,

I have two classes:

```python
class PlayerPro(MESA_BASE):
    ''' player_pro model '''
    __tablename__ = "player_pro"

    # Primary Keys
    ebis_id = Column(MEDIUMINT(9), primary_key=True)
    bam_id = Column(MEDIUMINT(9), index=True)
    phil_id = Column(MEDIUMINT(9), index=True)


class EvalProHit(PHIL_DATA_BASE):
    ''' Eval Pro Hit model '''
    __tablename__ = "eval_pro_hit"

    def list_id_default(self):  # pylint: disable=no-self-use
        return uuid.uuid4().hex

    # Keys
    eval_id = Column(VARCHAR(255), primary_key=True, default=list_id_default)
    phil_id = Column(MEDIUMINT(9), nullable=False)

    ForeignKeyConstraint([phil_id],
                         [PlayerPro.phil_id],
                         onupdate="CASCADE")
```

There in two different databases. When I go to create the tables the create statement is incorrect:

```sql
INFO:sqlalchemy.engine.base.Engine:
CREATE TABLE eval_pro_hit (
	eval_id VARCHAR(255) NOT NULL,
	phil_id MEDIUMINT(9) NOT NULL,

	FOREIGN KEY(phil_id) REFERENCES player_pro (phil_id) ON UPDATE CASCADE
)
```

Should be mesa.player_pro instead of player_pro. This is occuring from PHIL_DATA_BASE.metadata.create_all() . How can I accomplish this with models?

Also I tried to put in their mesa.player_pro.phil_Id instead of the actual column and I get this error:

```
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'eval_pro_hit.phil_id' could not find table 'mesa.player_pro' with which to generate a foreign key to target column 'phil_id'
```

Is there a way to reference a table from another DeclaritiveBase?

**Comment by datadidit** [comment]
For anyone else that runs into a similar issue. This https://stackoverflow.com/questions/43584453/how-to-handle-cross-schema-foreign-key-in-sqlalchemy was helpful. 

I needed to add
```
__table_args__ = {'schema': 'mesa'}
```

To `player_pro` model. Then it worked. Why isn't the schema derived from the `declaritive_base` associated with the model?

**Comment by zzzeek** [comment]
hi there -

it looks like you already asked this on the mailing list at https://groups.google.com/forum/#!topic/sqlalchemy/W-b9jMmzqRQ.   There is no need to post your question on two of SQLAlchemy's forums, I read both every day.  lets continue on the ML where I have asked for clarification to your question.
