### ISSUE TITLE
What to do when we have existing loggers for our application

### ISSUE THREAD

**Issue by jaskirat1208** [sqlalchemy/sqlalchemy#4558]
By default, logs are printed on stdout. But in some organisations, we have our own logger objects. In such cases, it may be useful to log everything with the same logger object. For that purpose, we have to set the variable engine.logger to our logger. But it is not good to set a variable manually. So, I think now two possibilities exist. Either add a setter function for logger and/or maybe you could set the value of logger in the engine constructor itself.

**Comment by zzzeek** [comment]
hi there -

SQLAlchemy uses [standard python logging](https://docs.python.org/3/library/logging.html) for which you can direct output in any way you'd like as well as supply your own loggers, filters for existing loggers, or anything else.    There are many examples on the web of how to create [custom loggers](https://dzone.com/articles/python-custom-logging-handler-example) wtihin this system.   For SQLAlchemy, you set up your custom logger on the `sqlalchemy.engine` namespace, see https://docs.sqlalchemy.org/en/latest/core/engines.html#configuring-logging .      No changes to SQLAlchemy are needed here.

**Comment by jaskirat1208** [comment]
Hi, could you please give me a link to using existing loggers ? The only
way out I found was override engine.logger So I wrote a setter function for
it.
Rgds
Jaskirat Singh

**Comment by zzzeek** [comment]
it depends on if your existing logger interacts with Python logging or not, is it a custom Handler object or is it just an entirely custom object that writes to a file ?

**Comment by zzzeek** [comment]
Links from my earlier comment as well as some additional ones:

custom logger example: https://dzone.com/articles/python-custom-logging-handler-example
Python logging: https://docs.python.org/3/library/logging.html
logging tutorial: https://docs.python.org/3/howto/logging.html#logging-basic-tutorial
a huge number of recipes: https://docs.python.org/3/howto/logging-cookbook.html#logging-cookbook

**Comment by jaskirat1208** [comment]
It is based on python logging.

**Comment by zzzeek** [comment]
OK assuming it's a handler

    import logging
    logging.getLogger("sqlalchemy.engine").addHandler(<your handler>)

**Comment by jaskirat1208** [comment]
Yeah, got it. Thanks man :)
Cheers
