### ISSUE TITLE
The object count increase after session.commit

### ISSUE THREAD

**Issue by Chenjunchao** [sqlalchemy/sqlalchemy#4560]
I am using sqlalchemy 1.1.9 on windows 7 64bit machine. The problem is that when I issue a "session.commit", the object count in gc increased 90. And it seems the newly created object cannot be released with "session.close" and "engine.dispose". Please help me, thanks in advance. Here is a simple demo to reproduce this issue:

```
from sqlalchemy import Column, String, create_engine, Integer
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
import gc
import os

Base = declarative_base()


class User(Base):
    __tablename__ = 'abc'

    id = Column(String(20), primary_key=True)
    name = Column(String(20))


db_file = 'd:/test.db'
if os.path.exists(db_file):
    os.remove(db_file)

engine = create_engine('sqlite:///d:/test.db')
DBSession = sessionmaker(bind=engine, autoflush=False, autocommit=False)
Base.metadata.create_all(engine)

print('Record initial object count: {}'.format(len(gc.get_objects())))

s = DBSession()

for i in range(1):
    u = User(id=str(i), name='User' + str(i))
    s.add(u)

print('Before session.commit,  object count: {}'.format(len(gc.get_objects())))
s.commit()

print('Before session.close,  object count: {}'.format(len(gc.get_objects())))
s.close()

print('Before engine.dispose,  object count: {}'.format(len(gc.get_objects())))

engine.dispose()
print('After engine.dispose,  object count: {}'.format(len(gc.get_objects())))
```

**Comment by zzzeek** [comment]
hi there -

Python's garbage collector does not immediately remove all objects from memory if they are involved in cycles, to ensure that all unreachable cycles are collected you need to call gc.collect() (this occurs automatically but we can invoke it ourselves to make sure it happens right now).  Also, the SQLite driver has known behaviors that can temporarily accumulate a small amount of internal state between queries that is memory managed, and SQLAlchemy also caches some things too, so small growths in memory are normal.   The only thing you need to be concerned about is if they keep growing unbounded over time, and the only way to see that is to run the code for many more iterations.   Below is your script using a loop and gc.collect(), with any version of SQLAlchemy no leak is illustrated.  if you remove the gc.collect(), the object count is a little more jagged but again there is no unbounded growth.

```
from sqlalchemy import Column, String, create_engine, Integer
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
import gc
import os

Base = declarative_base()


class User(Base):
    __tablename__ = 'abc'

    id = Column(String(20), primary_key=True)
    name = Column(String(20))



engine = create_engine('sqlite:///file.db')
DBSession = sessionmaker(bind=engine, autoflush=False, autocommit=False)
Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)

import time

while True:
    engine.execute("delete from abc")
    print('Record initial object count: {}'.format(len(gc.get_objects())))

    s = DBSession()

    for i in range(1):
        u = User(id=str(i), name='User' + str(i))
        s.add(u)

    print('Before session.commit,  object count: {}'.format(len(gc.get_objects())))
    s.commit()

    print('Before session.close,  object count: {}'.format(len(gc.get_objects())))
    s.close()

    print('Before engine.dispose,  object count: {}'.format(len(gc.get_objects())))

    engine.dispose()
    gc.collect()
    print('After engine.dispose,  object count: {}'.format(len(gc.get_objects())))
    time.sleep(1)
```

output:

```
ecord initial object count: 23703
Before session.commit,  object count: 23821
Before session.close,  object count: 23904
Before engine.dispose,  object count: 23903
After engine.dispose,  object count: 23777
Record initial object count: 23777
Before session.commit,  object count: 23815
Before session.close,  object count: 23818
Before engine.dispose,  object count: 23817
After engine.dispose,  object count: 23777
Record initial object count: 23777
Before session.commit,  object count: 23815
Before session.close,  object count: 23818
Before engine.dispose,  object count: 23817
After engine.dispose,  object count: 23777
Record initial object count: 23777
Before session.commit,  object count: 23815
Before session.close,  object count: 23818
Before engine.dispose,  object count: 23817
After engine.dispose,  object count: 23777
Record initial object count: 23777
Before session.commit,  object count: 23815
Before session.close,  object count: 23818
Before engine.dispose,  object count: 23817
After engine.dispose,  object count: 23777

```

**Comment by Chenjunchao** [comment]
Hi,
Thanks for your quick reply. Actually, my case is a litter bit different from yours. In my app, I have to create engine and session many times, and each time I do so, there is a few objects increase. And the memory keep increasing. I also tried gc.collect(), but there is still some "leak". I modified my demo as below:

from sqlalchemy import Column, String, create_engine, Integer
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
import gc
import os
import time

Base = declarative_base()


class User(Base):
    __tablename__ = 'abc'

    id = Column(String(20), primary_key=True)
    name = Column(String(20))


for j in range(4):
    db_file = 'd:/test' + str(j) + '.db'
    if os.path.exists(db_file):
        os.remove(db_file)

    engine = create_engine('sqlite:///' + db_file)
    DBSession = sessionmaker(bind=engine, autoflush=False, autocommit=False)
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)

    print('Record initial object count: {}'.format(len(gc.get_objects())))

    s = DBSession()

    for i in range(1):
        u = User(id=str(i), name='User' + str(i))
        s.add(u)

    print('Before session.commit,  object count: {}'.format(len(gc.get_objects())))
    s.commit()

    print('Before session.close,  object count: {}'.format(len(gc.get_objects())))
    s.close()

    print('Before engine.dispose,  object count: {}'.format(len(gc.get_objects())))
    engine.dispose()
    gc.collect()
    print('After engine.dispose,  object count: {}'.format(len(gc.get_objects())))
    time.sleep(1)


Actually, for each iteration, there are about 50 objects increasing. However, in my app, I have hundreds of tables and thousands of ORM objects to be saved. The memory usage increased rapidly. I'd like to know if there is a way to clean session/engine that no longer used. Thanks!

**Comment by Chenjunchao** [comment]
By the way, here is my out put:
Record initial object count: 25548
Before session.commit,  object count: 25665
Before session.close,  object count: 25756
Before engine.dispose,  object count: 25755
After engine.dispose,  object count: 25534
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Record initial object count: 25650
Before session.commit,  object count: 25762
Before session.close,  object count: 25804
Before engine.dispose,  object count: 25803
After engine.dispose,  object count: 25582
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Record initial object count: 25698
Before session.commit,  object count: 25810
Before session.close,  object count: 25852
Before engine.dispose,  object count: 25851
After engine.dispose,  object count: 25630
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Record initial object count: 25746
Before session.commit,  object count: 25858
Before session.close,  object count: 25900
Before engine.dispose,  object count: 25899
After engine.dispose,  object count: 25678
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by zzzeek** [comment]
what happens after 400 iterations?    what database backend and what DBAPI are you using ?

**Comment by zzzeek** [comment]
so the growth you see is because of the use of many new Engine objects in conjunction with the same Mapper objects over and over again.  Each Mapper has an LRUCache that is used to cache compiled SQL constructs against specific dialects in which they've been compiled.   Because you are making new Engines on every run, you are making new Dialect objects, and these caches are basically getting filled up until they hit their limit and start replacing old items.      This is extremely inefficient from a performance standpoint, and as you've noticed, it also uses a huge amount of memory.

However, it is not leaking.  Change your loop to "400" and bring the time.sleep() down to .1 and you will see that memory does not grow unbounded; when each mapper's cache reaches about 150 elements it prunes itself of old elements.

This patch (against master) illustrates the cache size:

```
diff --git a/lib/sqlalchemy/util/_collections.py b/lib/sqlalchemy/util/_collections.py
index 75e1727df6..d95216a069 100644
--- a/lib/sqlalchemy/util/_collections.py
+++ b/lib/sqlalchemy/util/_collections.py
@@ -884,6 +884,10 @@ class LRUCache(dict):
         self._mutex = threading.Lock()
 
     def _inc_counter(self):
+        print(
+            "Compiled cache id %s size is %s capacity is %s"
+            % (id(self), len(self), self.capacity)
+        )
        self._counter += 1
         return self._counter
 

```

if we log the iterations, here's the start:

```
ITERATION: #0
Record initial object count: 25742
Before session.commit,  object count: 25943
Compiled cache id 140095367805864 size is 0 capacity is 100
Before session.close,  object count: 25998
Before engine.dispose,  object count: 25997
After engine.dispose,  object count: 25657
ITERATION: #1
Record initial object count: 25787
Before session.commit,  object count: 25899
Compiled cache id 140095367805864 size is 1 capacity is 100
Before session.close,  object count: 25933
Before engine.dispose,  object count: 25932
After engine.dispose,  object count: 25698
ITERATION: #2
Record initial object count: 25828
Before session.commit,  object count: 25940
Compiled cache id 140095367805864 size is 2 capacity is 100
Before session.close,  object count: 25974
Before engine.dispose,  object count: 25973
After engine.dispose,  object count: 25746

```

here's the middle, memory is growing a lot!
```

ITERATION: #122
Record initial object count: 31588
Before session.commit,  object count: 31700
Compiled cache id 140095367805864 size is 122 capacity is 100
Before session.close,  object count: 31734
Before engine.dispose,  object count: 31733
After engine.dispose,  object count: 31506
ITERATION: #123
Record initial object count: 31636
Before session.commit,  object count: 31748
Compiled cache id 140095367805864 size is 123 capacity is 100
Before session.close,  object count: 31782
Before engine.dispose,  object count: 31781
After engine.dispose,  object count: 31554

```

however, right at 150 records in the cache, memory suddenly drops:

```
ITERATION: #149
Record initial object count: 32884
Before session.commit,  object count: 32996
Compiled cache id 140095367805864 size is 149 capacity is 100
Before session.close,  object count: 33030
Before engine.dispose,  object count: 33029
After engine.dispose,  object count: 32802
ITERATION: #150
Record initial object count: 32932
Before session.commit,  object count: 33044
Compiled cache id 140095367805864 size is 150 capacity is 100
Before session.close,  object count: 32976
Before engine.dispose,  object count: 32975
After engine.dispose,  object count: 30402
```

the cache is now full.   The size of each cache will move between 100 and 150 items and memory will jiggle up and down but not grow:

```
ITERATION: #200
Record initial object count: 32884
Before session.commit,  object count: 32996
Compiled cache id 140095367805864 size is 149 capacity is 100
Before session.close,  object count: 33030
Before engine.dispose,  object count: 33029
After engine.dispose,  object count: 32802
ITERATION: #201
Record initial object count: 32932
Before session.commit,  object count: 33044
Compiled cache id 140095367805864 size is 150 capacity is 100
Before session.close,  object count: 32976
Before engine.dispose,  object count: 32975
After engine.dispose,  object count: 30402

```


the reason we know this works is that we have tests for exactly this case, where someone is creating lots of engines against the same set of mappings: https://github.com/sqlalchemy/sqlalchemy/blob/master/test/aaa_profiling/test_memusage.py#L374   This test was very important to add since when I implemented the compiled cache, I knew that the "many engines" pattern would be the one vector that defeats the cache.

The simplest solution of course is to not create limitless engine objects.  It looks like you might be trying to do some kind of multi-tenancy with SQLite, in which case I'd suggest perhaps using ATTACH DATABASE / DETACH DATABASE with an engine per thread perhaps.

the cache itself can be made smaller by passing "_compiled_cache_size" to `__mapper_args__`, but this is private because the role of this cache may change across releases, and there are also other caches involved with dialects too which also can come into play here so we don't guarantee a consistent story for these attributes.

still another approach is to try to share the same dialect class across engines, likely by making a single SQLite engine, then each time you make a new engine, assign `my_new_engine.dialect = my_existing_engine.dialect`, though this is kind of hacky and doesn't cover everywhere the dialect is used.

**Comment by zzzeek** [comment]
so yeah hundreds of tables means you have hundreds of these caches.   so you have the worst case possible situation given the many engines/one mapping architecture + hundreds of mappings.

**Comment by zzzeek** [comment]
here's a significantly simpler and more performant version of your program using ATTACH DATABASE, and of course memory doesn't move at all:

```
from sqlalchemy import Column, String, create_engine, Integer, MetaData
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
import gc
import os
import time

Base = declarative_base(metadata=MetaData(schema="current"))


class User(Base):
    __tablename__ = 'abc'

    id = Column(String(20), primary_key=True)
    name = Column(String(20))


import contextlib

@contextlib.contextmanager
def using_db(engine, filename):
    with engine.connect() as connection:
        connection.execute("ATTACH DATABASE '%s' AS current" % filename)
        try:
            yield connection
        finally:
            connection.execute("DETACH DATABASE current")

engine = create_engine('sqlite://')

for j in range(400):
    db_file = str(j) + '.db'
    if os.path.exists(db_file):
        os.remove(db_file)

    with using_db(engine, db_file) as conn:
        DBSession = sessionmaker(bind=conn, autoflush=False, autocommit=False)
        Base.metadata.drop_all(conn)
        Base.metadata.create_all(conn)

        print("ITERATION: #%d" % j)
        print('Record initial object count: {}'.format(len(gc.get_objects())))

        s = DBSession()

        for i in range(1):
            u = User(id=str(i), name='User' + str(i))
            s.add(u)

        print('Before session.commit,  object count: {}'.format(len(gc.get_objects())))
        s.commit()

        print('Before session.close,  object count: {}'.format(len(gc.get_objects())))
        s.close()

        print('Before engine.dispose,  object count: {}'.format(len(gc.get_objects())))
        gc.collect()
        print('After engine.dispose,  object count: {}'.format(len(gc.get_objects())))
        time.sleep(.1)
```

**Comment by Chenjunchao** [comment]
Hi ,
Thanks for your suggestion. I will try ATTACH DATABASE / DETACH DATABASE and let you know the result!

**Comment by Chenjunchao** [comment]
It works for me. Thanks!
