### ISSUE TITLE
Column with dynamic type depending on dialect

### ISSUE THREAD

**Issue by mketiku** [sqlalchemy/sqlalchemy#4564]
Is it possible to create a model such that its columns are set dynamically with a specific type depending on the vendor or sql dialect being used?
That is if my model is running using a oracle sqlalchemy should create a column of type of `NUMBER` otherwise on a sqlserver engine a column of type of `BIGINT` should be created. I understand there are generic types such as `Integer` or `String` already but I am not sure how to make my own generic type. I would appreciate it if anyone could let me know if this is possible or point me in a more appropriate direction.

**Comment by mketiku** [comment]
I found the following https://docs.sqlalchemy.org/en/latest/core/custom_types.html#overriding-type-compilation detailing how to override the compilation of a type. This allows me to change the compilation for a specified engine like so
 ```python
@compiles(BIGINT, "oracle")
def compile_big_int_oracle(type_, compiler, **kw):
    return "NUMBER"
```  
Is it possible to take that a step further to compile a type depending on what table it is for?

**Comment by zzzeek** [comment]
> Is it possible to create a model such that its columns are set dynamically with a specific type depending on the vendor or sql dialect being used?
> That is if my model is running using a oracle sqlalchemy should create a column of type of `NUMBER` otherwise on a sqlserver engine a column of type of `BIGINT` should be created. I understand there are generic types such as `Integer` or `String` already but I am not sure how to make my own generic type. I would appreciate it if anyone could let me know if this is possible or point me in a more appropriate direction.

yes use with_variant for this:

https://docs.sqlalchemy.org/en/latest/core/type_api.html?highlight=variant#sqlalchemy.types.TypeEngine.with_variant

Using `@compiles` is only going to get you DDL but it will mis-assign the type handling to the object which in the Oracle dialect is immensely critical, so you want to do:

   Column("my_column", BIGINT.with_variant(oracle.NUMBER, "oracle"))

**Comment by mketiku** [comment]
Thank you for your help!, using the `with_variant()` method worked for me.

**Comment by zzzeek** [comment]
ok great
