### ISSUE TITLE
GenericFunction register is case-sensitive

### ISSUE THREAD

**Issue by adrien-berchet** [sqlalchemy/sqlalchemy#4569]
The `GenericFunction` instances are registered in `sqlalchemy.sql.functions._register`, which is a `collections.defaultdict(dict)`. The `sqlalchemy.sql.functions.func()` function uses the `get()` method to retrieved registered functions, which means that the search is case-sensitive.

This case-sensitivity can have some drawbacks, e.g.:

```python
from sqlalchemy import func
from sqlalchemy.sql.functions import GenericFunction
from sqlalchemy.types import Text, Integer

class CaseSensitiveFunc(GenericFunction):
    type = Text

class CaseInsensitiveFunc(GenericFunction):
    type = Integer

print(func.CaseSensitiveFunc().type, func.CaseInsensitiveFunc().type)  # Out: (Text(), Integer())
print(func.CaSeSeNsItIveFuNc().type, func.CaSeInSeNsItIveFuNc().type)  # Out: (NullType(), NullType())
```
In this example, the `GenericFunction(s)` are not retrieved by the `sqlalchemy.sql.functions.func()` function when their letter case is not exactly the same as in their definitions. So in this case, they are just sent to the DBMS as they are and the DBMS silently interpret them without considering the letter case, which can lead to some weird bugs (see here for example: https://github.com/geoalchemy/geoalchemy2/issues/215).

Some simple changes in `sqlalchemy.sql.functions` could add the possibility to register a `GenericFunction` without being case-sensitive. In this case we would have the following:

```python
from sqlalchemy import func
from sqlalchemy.sql.functions import GenericFunction
from sqlalchemy.types import Text, Integer

class CaseSensitiveFunc(GenericFunction):
    type = Text
    case_sensitive = True

class CaseInsensitiveFunc(GenericFunction):
    type = Integer
    case_sensitive = False

print(func.CaseSensitiveFunc().type, func.CaseInsensitiveFunc().type)  # Out: (Text(), Integer())
print(func.CaSeSeNsItIveFuNc().type, func.CaSeInSeNsItIveFuNc().type)  # Out: (NullType(), Integer())
```

Here the case-insensitive function is retrieved by `sqlalchemy.sql.functions.func()`.

**Comment by zzzeek** [comment]
please review #4467 where the case sensitivity of generic functions is also discussed.  Changes ilke these are often very dangerous to merge in point releases as they can break backwards compatibility.   For example here what if someone has defined two GenericFunctions that differ only in case, what happens?  should that now raise an error?

**Comment by zzzeek** [comment]
My apologies, I missed the "case_sensitive=True" flag above.

**Comment by zzzeek** [comment]
however, my thinking is that this should be an across-the-board change.  I would prefer to target at 1.4 and make these names case insensitive across the board.    The PR is very well written but is too much complexity for something I think will not see enough use and it is possibly more likely that everyone would appreciate a more consistent case sensitivity story.

**Comment by adrien-berchet** [comment]
Thanks for these comments!

> For example here what if someone has defined two GenericFunctions that differ only in case, what happens? should that now raise an error?

If they are both defined with `case_sensitive = True`, which is the default behavior, they will coexist. But if they are defined with `case_sensitive = False`, the last one will overwrite the first one silently. I was thinking about raising a warning or an exception in this case but I realized that this behavior (the last one overriding the first one) already exists in the master branch if we define 2 functions with the same identifier, so I did not add warnings/exceptions in this case to be consistent with the current behavior (but we could add some).

> however, my thinking is that this should be an across-the-board change. I would prefer to target at 1.4 and make these names case insensitive across the board. The PR is very well written but is too much complexity for something I think will not see enough use and it is possibly more likely that everyone would appreciate a more consistent case sensitivity story.

I agree that the more consistent the better.
But the current implementation is quite bug-prone and these bugs are quite hard to understand (e.g. when the query returns something but not with the expected type, the crash can occur much later after the actual bug (it actually happened to someone in my team, he spent a full day to find that a 't' should have been a 'T' :smile: , that's why I am here)). So I still think that something should be done about it.
But maybe we could use another temporary strategy? E.g. allowing a `force_case_sensitivity` attribute to the `GenericFunction` that would raise an exception when one call a function that is not registered and that another one is registered with the same lowercase name which has the `force_case_sensitivity` attribute set to `True`. But I am not fond of it.

**Comment by zzzeek** [comment]
There's another way, which is to change it to work case insensitively, but detect when someone has created two generic functions that name-conflict on different cases, then emit a warning, then support both of those in a deprecated "case sensitive" mode.    This is a little more intricate to implement and also we always add test for deprecated behaviors in the corresponding "test_deprecations.py" test suite, in this case test/sql/test_deprecations.py.

So this reduces the scope of backwards compatibility.  There is still the chance of backwards incompatibility in that if an application is calling one of their functions using the wrong casing, and is getting an object back that "works" because their GenericFunction in fact doesn't work (like datatypes or something), that would suddenly be exposed.  That is, it's exactly the bug you found but in reverse.  But this is such an unlikely situation it's not worth worrying about.

**Comment by zzzeek** [comment]
I have a few ideas on the implementation too, as I like to minimize "deprecated" codepaths as much as possible, but lets get the basic behavioral contract and tests happening first and I can refine it after that.

**Comment by adrien-berchet** [comment]
Indeed, this way would be better but I was afraid of introducing backward incompatibilities in the libraries depending on sqlalchemy. But if you think it is ok let's go for it!
Should I close #4570 then?

**Comment by zzzeek** [comment]
you can force-push to it a new revision if you'd like, i have no cycles to write new code in the near term...

**Comment by adrien-berchet** [comment]
Ok, I will try to take some time for this in the next few days.

**Comment by adrien-berchet** [comment]
I pushed a new commit in #4570 that should work as you described.
I did not move any test to `test/sql/test_deprecations.py` for now, I will clean this up later if we agree on the functional part.
Also, I had to rework the test `test/sql/test_functions.py::CompileTest::test_uppercase` because a `GenericFunction` with an identifier `now` is already registered when executing this test. But as I don't know the actual purpose of this test, it might be an unwanted change.

**Comment by sqla-tester** [comment]
**Adrien Berchet** has proposed a fix for this issue in the **master** branch:

**Add case insensitivity feature to GenericFunction.** https://gerrit.sqlalchemy.org/1178

**Comment by sqla-tester** [comment]
**Adrien Berchet** has proposed a fix for this issue in the **master** branch:

**Add case insensitivity feature to GenericFunction.** https://gerrit.sqlalchemy.org/1178

**Comment by sqla-tester** [comment]
**Adrien Berchet** has proposed a fix for this issue in the **rel_1_3** branch:

**Add case insensitivity feature to GenericFunction.** https://gerrit.sqlalchemy.org/1241
