### ISSUE TITLE
pool logging documentation is wrong

### ISSUE THREAD

**Issue by jaskirat1208** [sqlalchemy/sqlalchemy#4571]
As mentioned in SQLAlchemy docs,
'sqlalchemy.pool' - controls connection pool logging. set to logging.INFO or lower to log connection pool checkouts/checkins.
However, the checkouts and checkins to pool were not shown when I set echoflag to True as logger levels were logging.DEBUG for checkout/checkins and to adher to the documentation statement, it should be set to logging.INFO.

**Comment by zzzeek** [comment]
we need to establish that pool can use `echo="debug"` and engine can have `echo_pool="debug"` in the documentation for those flags, as well as that the INFO line is wrong, DEBUG is how you get checkins/checkouts.   doc fix should also be backported to 1.2, 1.1 as these docs are still on the site

**Comment by jaskirat1208** [comment]
Hi, 
In https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/pool/base.py#L108, the echo parameter is only logging that the connection has been invalidated, or that reconnection attempts have exhausted. Am I missing something ? or Should I add this in the documentation ? Same with the second one.
Third one:  ``sqlalchemy.pool`` - controls connection pool logging.  set to ``logging.DEBUG`` or lower to log connection pool checkouts/checkins.
Should I go for the PR ?

**Comment by zzzeek** [comment]
all "echo" flags accept the values: False, True, "debug" and are handled by the log.py module using the lookup table here:  https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/log.py#L82

therefore echo_pool='debug' means DEBUG logging will be turned on for the pool.   See the documentation for engine.echo right above it.

**Comment by jaskirat1208** [comment]
Please check PR #4583

**Comment by sqla-tester** [comment]
**jaskiratsingh** has proposed a fix for this issue in the **master** branch:

**Improve documentation for connection pool logging** https://gerrit.sqlalchemy.org/1183
