### ISSUE TITLE
DDL leaves transaction open

### ISSUE THREAD

**Issue by jmarshall9120** [sqlalchemy/sqlalchemy#4572]
This may be a case of me not finding the correct documentation, but is it intended behavior that DDL statements should leave transactions open? 

```
>>> sql = ("IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spTEST') "
           "BEGIN "
	   "    DROP PROCEDURE [dbo].[spTEST] "
           "END")

#This causes a hanging lock on my db
#  the lock that gets reported by the db is 
#  that it's waiting for programming instructions 
#  (ie the application is holding the lock).
>>> conn = _db_LOCAL.ActiveDbEngine.connect()
>>> r = conn.execute(sql )
>>> r.close()

#This doesn't
>> conn.close()
>>> conn = _db_LOCAL.ActiveDbEngine.connect()
>>> tran = conn.begin()
>>> conn2 = tran.connection
>>> r = conn2.execute(sql )
>>> tran.commit()
```

DB:  MSSQL 2014
PYTHON: 3.7
SQLALCHEMY: 1.3.1
PYODBC: 4.0.26

**Comment by zzzeek** [comment]
this is normal because the "autocommit" feature of the Engine is based on regular expressions and doesn't work for custom SQL without additional steps.   See https://docs.sqlalchemy.org/en/latest/core/connections.html#understanding-autocommit for how to handle this situation.

**Comment by jmarshall9120** [comment]
Thanks @zzzeek.  I actually saw that but wasn't completely sure what it meant.  Just thinking ahead, could we put a line in the documentation, something like "Auto-commit is only enabled by default for certian DML statements (INSERT, UPDATE, DELETE).  Regarding DDL statements and other database function a transaction must be declared."

Just a thought.
