### ISSUE TITLE
Association proxy is not working anymore when the remote attr on the target class is a property

### ISSUE THREAD

**Issue by SuryaSankar** [sqlalchemy/sqlalchemy#4574]
It used to be possible to define an association_proxy to a `property` defined on the target class

```python
class UploadedImage(db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True)
    file_name = db.Column(db.String(1000))

    @property
    def url(self):
        return url_for('main_bp.uploaded_file',
                       file_name=self.file_name,
                       _external=True)

class TemplateSheet(db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True)
    thumbnail_image_id = db.Column(db.Integer, db.ForeignKey(
        'uploaded_image.id'))
    thumbnail_image = db.relationship("UploadedImage")
    thumbnail_image_url = association_proxy("thumbnail_image", "url")

```

This used to work in SQLAlchemy 1.1.11.
After upgrading to 1.3.1, the above association proxy field no longer works and throws an exception as follows

```
In [20]: print(TemplateSheet.thumbnail_image_url)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/user/webapp/devenv.py in <module>()
----> 1 print(TemplateSheet.thumbnail_image_url)


/home/user/Envs/dev/local/lib/python2.7/site-packages/sqlalchemy/ext/associationproxy.pyc in __get__(self, obj, class_)
    189         if class_ is None:
    190             return self
--> 191         inst = self._as_instance(class_, obj)
    192         if inst:
    193             return inst.get(obj)

/home/user/Envs/dev/local/lib/python2.7/site-packages/sqlalchemy/ext/associationproxy.pyc in _as_instance(self, class_, obj)
    247             owner = self._calc_owner(class_)
    248             if owner is not None:
--> 249                 inst = AssociationProxyInstance.for_proxy(self, owner, obj)
    250                 setattr(class_, self.key + "_inst", inst)
    251             else:

/home/user/Envs/dev/local/lib/python2.7/site-packages/sqlalchemy/ext/associationproxy.pyc in for_proxy(cls, parent, owning_class, parent_instance)
    373         else:
    374             return cls._construct_for_assoc(
--> 375                 target_assoc, parent, owning_class, target_class, value_attr
    376             )
    377 

/home/user/Envs/dev/local/lib/python2.7/site-packages/sqlalchemy/ext/associationproxy.pyc in _construct_for_assoc(cls, target_assoc, parent, owning_class, target_class, value_attr)
    386 
    387         attr = getattr(target_class, value_attr)
--> 388         if attr._is_internal_proxy and not hasattr(attr, "impl"):
    389             return AmbiguousAssociationProxyInstance(
    390                 parent, owning_class, target_class, value_attr
```

Can this be fixed ?

**Comment by zzzeek** [comment]
hi there -

I don't understand what your code is meant to achieve as you are attempting to access a Python instance-only descriptor, e.g. `@property`, at the class level, which is a meaningless operation.  Perhaps you intended to use `@hybrid_property` ?

**Comment by zzzeek** [comment]
here is the patch for the specific condition:

```
diff --git a/lib/sqlalchemy/ext/associationproxy.py b/lib/sqlalchemy/ext/associationproxy.py
index ea3b8fadeb..ff387d8b59 100644
--- a/lib/sqlalchemy/ext/associationproxy.py
+++ b/lib/sqlalchemy/ext/associationproxy.py
@@ -385,7 +385,9 @@ class AssociationProxyInstance(object):
             )
 
         attr = getattr(target_class, value_attr)
-        if attr._is_internal_proxy and not hasattr(attr, "impl"):
+        if not hasattr(attr, "_is_internal_proxy") or (
+            attr._is_internal_proxy and not hasattr(attr, "impl")
+        ):
             return AmbiguousAssociationProxyInstance(
                 parent, owning_class, target_class, value_attr
             )

```

and then per https://docs.sqlalchemy.org/en/latest/changelog/migration_13.html#associationproxy-stores-class-specific-state-on-a-per-class-basis you will get the more meaningful exception, but nonetheless still an exception:

`AttributeError: Association proxy TemplateSheet.thumbnail_image refers to an attribute 'url' that is not directly mapped on class <class '__main__.UploadedImage'>; therefore this operation cannot proceed since we don't know what type of object is referred towards
`

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Refine ambiguous access for unknown attribute types** https://gerrit.sqlalchemy.org/1176

**Comment by zzzeek** [comment]
for basic `get()` for the purposes of `repr()` it will return the `AmbiguousAssociationProxyInstance` object, while maintaining an exception condition for any attempts at SQL expression behavior.

**Comment by SuryaSankar** [comment]
Thank you for the fix. But as you have mentioned, it is still anyways throwing a different exception now.

The property is accessed at the class level as a part of a serializing code. The code inspects the attributes defined on the class and generates functions to serialize them appropriately. 

I have a method which is defined like this on the Model class which is used as the declarative base

```
from flask_sqlalchemy import Model

class ModelBooster(Model, QueryableMixin, DictizableMixin):
    @classmethod
    def all_keys(cls):
        keys = []
        for c in cls.parents():
            keys += c.__dict__.keys()
        keys += cls.__dict__.keys()
        return keys

    @classmethod
    def association_proxy_keys(cls, include_parent_classes=True):
        result = []
        keys = cls.all_keys() if include_parent_classes else cls.__dict__.keys()
        for k in keys:
            try:
                if isinstance(getattr(cls, k), AssociationProxyInstance) and not k.startswith("_AssociationProxy_"):
                    result.append(k)
            except:
                continue
        return result
```

The above method would basically give all the association proxy keys as a list.  After the changes in 1.3.x it is no longer able to list the association_proxies which were mapped to properties on the target class. 

In the client code which uses models declared using the above class, I had used association proxies to access properties on target class - because it was convenient. I guess I could have just written properties on the accessing class as well to link to the target class's property. But since association_proxy worked fine, I had just used it as a getter property. ( The other features of `hybrid_property` were not required for that use case )

So, should it be assumed that it would no longer be possible to access an association proxy attribute mapped to a `property` on a target class - at the class level for inspection purposes?

**Comment by zzzeek** [comment]
> Thank you for the fix. But as you have mentioned, it is still anyways throwing a different exception now.
> 
> The property is accessed at the class level as a part of a serializing code. The code inspects the attributes defined on the class and generates functions to serialize them appropriately.
> 
> I have a method which is defined like this on the Model class which is used as the declarative base
> 
> ```python
> from flask_sqlalchemy import Model
> 
> class ModelBooster(Model, QueryableMixin, DictizableMixin):
>     @classmethod
>     def all_keys(cls):
>         keys = []
>         for c in cls.parents():
>             keys += c.__dict__.keys()
>         keys += cls.__dict__.keys()
>         return keys
> 
>     @classmethod
>     def association_proxy_keys(cls, include_parent_classes=True):
>         result = []
>         keys = cls.all_keys() if include_parent_classes else cls.__dict__.keys()
>         for k in keys:
>             try:
>                 if isinstance(getattr(cls, k), AssociationProxyInstance) and not k.startswith("_AssociationProxy_"):
>                     result.append(k)
>             except:
>                 continue
>         return result
> ```
> 
> The above method would basically give all the association proxy keys as a list. After the changes in 1.3.x it is no longer able to list the association_proxies which were mapped to properties on the target class.

please try the latest patch which has just merged, get() access at the class level has been restored and your example code seems to be doing nothing more than that.

**Comment by SuryaSankar** [comment]
@zzzeek Thanks a lot. It works fine with this patch. When will this be pushed to the official Pypi releases ?
