### ISSUE TITLE
Cleaner solution required when using dialect options in an ORM model.

### ISSUE THREAD

**Issue by lphuberdeau** [sqlalchemy/sqlalchemy#4575]
I've searched for a better solution as much as I could, but this does not seem elegant at all.

The objective is to configure the floating point precision in MySQL to get sub-second resolution on timestamps. However, when running unit tests, we use SQLite instead of MySQL. Not having this resolution in unit tests is not an issue. We can adjust the few affected tests to compensate if there is anything.

When setting the mysql_fps option on the column, I was expecting that the flag would be ignored for other dialects. Instead, there was an exception:

`sqlalchemy.exc.ArgumentError: Argument 'mysql_fps' is not accepted by dialect 'mysql' on behalf of <class 'sqlalchemy.sql.schema.Column'>`

How are these dialect-specific options intended to be used?

I came up with a work-around, but readability is heavily sacrificed.

```
class Event(Base):

    __tablename__ = "events"

    # ...

    try:
        event_date = Column(DateTime, nullable=False, mysql_fps=6)
    except ArgumentError:
        event_date = Column(DateTime, nullable=False)

```

**Comment by zzzeek** [comment]
Hi -

A few things.  

First off there is no "mysql_fps" option on Column objects, nor is there any option called "fps" in all of SQLAlchemy.   it sounds like  you are looking for the ["fsp" option on TIMESTAMP](https://docs.sqlalchemy.org/en/latest/dialects/mysql.html?highlight=fsp#sqlalchemy.dialects.mysql.TIMESTAMP.params.fsp).

Secondly, to distinguish dialect specific type options, 
use [with_variant](https://docs.sqlalchemy.org/en/latest/core/type_api.html?highlight=with_variant#sqlalchemy.types.TypeEngine.with_variant) for this.

```


class Event(Base):

    __tablename__ = "events"

    # ...

    event_date = Column(DateTime().with_variant(mysql.TIMESTAMP(fps=6), "mysql"))

```
hope this helps!

**Comment by lphuberdeau** [comment]
Apologies. A typo did slip in there somehow. I re-validated and an equivalent error occurs so the question/issue remains valid.

The fsp option is also available on datetime.

My understanding was that the mysql_fsp option is added via [argument_for](https://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.base.DialectKWArgs.argument_for) since 1.3. It does seem to be somehow taken into account as the error message changes versus using fsp= or any other bad argument name.

with_variant() seems to be exactly what I was looking for. I'm quite surprised I did not come across it.

Thanks for the quick response.
