### ISSUE TITLE
Erroneous "No driver name specified; this is expected by PyODBC" warning.

### ISSUE THREAD

**Issue by jmarshall9120** [sqlalchemy/sqlalchemy#4576]
I'm getting the following warning a lot:

> ...\lib\site-packages\sqlalchemy\connectors\pyodbc.py:79: SAWarning: No driver name specified; this is expected by PyODBC when using DSN-less connections
>   "No driver name specified; "

It happens when I use this connection url:

`url = mssql+pyodbc://*****:*****@(localdb)\ProjectsV13/ETL?DRIVER=%7BODBC+DRIVER+17+FOR+SQL+SERVER%7D&initialCatalog=ETL&trusted_Connection=no&connectTimeout=30&encrypt=no&trustServerCertificate=no&applicationIntent=ReadWrite&multiSubnetFailover=no`

so, in the above i'm passing the connection attribute "DRIVER" and alchemy is asking me to pass "driver"
looking at the code in that sqlalchemy module on lines 76-82 we get:

```
driver = keys.pop("driver", self.pyodbc_driver_name)
                if driver is None:
                    util.warn(
                        "No driver name specified; "
                        "this is expected by PyODBC when using "
                        "DSN-less connections"
                )
                else:
                    connectors.append("DRIVER={%s}" % driver)
```

So according to that if we pass the connection attribute 'DRIVER' as 'driver' we should get a connection and no warning.  That url would like this:

`mssql+pyodbc://*****:*****@(localdb)\ProjectsV13/ETL?driver=ODBC+DRIVER+17+FOR+SQL+SERVER&initialCatalog=ETL&trusted_Connection=no&connectTimeout=30&encrypt=no&trustServerCertificate=no&applicationIntent=ReadWrite&multiSubnetFailover=no`

Note in the above i also had to drop the `%7B` ('{') and `%7D` ('}') from the driver name.

It seems to me that the warning should be silenced if we are passing 'DRIVER' explicitly.  Adding:

```and not 'DRIVER' in keys```

to the code would avoid this warning being unnecessarily triggered.

after suggested changes
```
driver = keys.pop("driver", self.pyodbc_driver_name)
                if driver is None and not 'DRIVER' in keys":
                    util.warn(
                        "No driver name specified; "
                        "this is expected by PyODBC when using "
                        "DSN-less connections"
                    )
```

**Comment by zzzeek** [comment]
I was going to say to remove the entire block but unfortunately it is applying the brackets.   it would be backwards incompatible to remove it, and it would also be backwards incompatible to treat other case-convention keywords in the same way because that is also backwards incompatible. 

I would suggest why you can't simply use lowercase "driver"?   For example, your patch does not accept the contingency that someone is using "Driver" (seems likely) or "dRIVer" (seems unlikely however, so does DRIVER when we document how to send the URL).

**Comment by zzzeek** [comment]
oh, then we just remove the warning entirely.

**Comment by jmarshall9120** [comment]
I would argue that "Driver" and "dRIVer" are in violation of the MSSQL server odbc standard and the sqlalchemy documentation.  I mean what if they wanted to pass "MySUPErGreatDriver" and we patched in `key.lstrip('MySUPErGreatDriver').lower()` it could work too.  

The other thing is why hand hold the brackets?  It kinda creates a gottcha where if you already know how to handle a MSSQL connection you'll pass 'driver' with brackets anyway and get an error.

**Comment by zzzeek** [comment]
the routine is already translating lots of these parameters, for example the parameter "odbc_autotranslate" becomes "AutoTranslate", if UID/PWD are missing it appends "Trusted_Connection=yes", and additionally, an ODBC connection string separates the key/values with semicolons, so we are "handholding" all these things for the purpose of building an abstracted API around pyodbc. 

If you want to pass a raw ODBC connection string you would pass it all as "odbc_connect", and then whatever you gave it goes straight through.  I would argue if you want to use MSSQL connection strings from their docs, that's what this is for.  https://docs.sqlalchemy.org/en/latest/dialects/mssql.html?highlight=odbc_connect#pass-through-exact-pyodbc-string

**Comment by zzzeek** [comment]
I was consdiering if I should add case-insensitive support but these are really two different APIs and mixing them perhaps makes it even worse.

**Comment by jmarshall9120** [comment]
I guess it's up to you, if you wan't alchemy to be a complete abstraction of the underlying API or not.  Feel free to close as "won't fix" if you're satisfied, i'll start working with "odbc_connect" and see how that goes.  Thanks for the input.

**Comment by zzzeek** [comment]
OK, I was going to just make the whole thing case-insensitive and check for the brackets already present, but no other dialect does this, when you aren't using odbc_connect, you're talking to the dialect, not pyodbc.   The option is already there to send raw ODBC strings through with odbc_connect so i think it would just be overdoing it to add a third way of working, that is a "hybrid SQLAlchemy interpretation with guessing".
