### ISSUE TITLE
Error when running make gettext under `doc/build`

### ISSUE THREAD

**Issue by bukun** [sqlalchemy/sqlalchemy#4578]
I want to translate the docs of SQLAlchemy into Chinese using ``sphinx-intl``. However, when I run

    make gettext

or 

    sphinx-build -b gettext . _build/locale

I got the following error.

```
Exception occurred:
  File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/zzzeeksphinx/mako.py", line 37, in init
    builder.theme.get_theme_dirs()
AttributeError: 'MessageCatalogBuilder' object has no attribute 'theme'
```

I found ``mako.py`` , and I am not familar with it. I hope someone will fix it.

**Comment by zzzeek** [comment]
hi can you please retry again using the latest zzzeeksphinx, thanks.

**Comment by bukun** [comment]
Thanks zzzeek.

The error has gone away when using the last zzzeeksphinx. However, then running with the following steps:

    sphinx-build -b gettext . _build/locale
    sphinx-intl update -p _build/locale  -l zh
    sphinx-intl build
    make -e SPHINXOPTS="-D language='zh'" html

Still, there is a error of the last step:

> loading translations [zh]... done
> loading pickled environment... not yet created
>  
> Exception occurred:
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2301, in resolve
>     raise ImportError(str(exc))
> ImportError: module 'zzzeeksphinx.theme' has no attribute 'get_path'
> The full traceback has been saved in /tmp/sphinx-err-h08khly_.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
>

**Comment by zzzeek** [comment]
hi -

where do I get "sphinx-intl" from is that new ?

**Comment by zzzeek** [comment]
found it https://pypi.org/project/sphinx-intl/

**Comment by zzzeek** [comment]
OK the steps you outline above worked for me, maybe make sure you have the latest version of all packages ?    I get HTML output that even has some chinese characters in it.

**Comment by bukun** [comment]
``sphinx-intl`` could be installed via ``pip``.

Using the updated ``sphinx``, all run fine. Thank you. However, 

```

    The name of the builder is: htmlThe name of the builder is: html
    Exception occurred:
      File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/zzzeeksphinx/viewsource.py", line 95, in _view_source_node
        raise ImportError("Error trying to import %s: %s" % (modname, ie))
    ImportError: Error trying to import examples.postgis.discriminator_on_association: No module named 'discriminator_on_association'
    The full traceback has been saved in /tmp/sphinx-err-h1cofi3q.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
    Makefile:44: recipe for target 'html' failed
```

I copy some files under ``examples/generic_associations`` into ``examples/postgis`` to solve the error above.

The tanslation result for Chinese could find at  http://www.osgeo.cn/sqlalchemy/ .

Some of the words in tempalte cound not be tranlated via po files.

**Comment by zzzeek** [comment]
are you building the docs from inside the doc/build directory inside the full source tree?  it locates "examples/postgis" using relative directory imports.   also I'm using python 3.7 maybe that helps.

**Comment by bukun** [comment]
```
➜  examples git:(master) pwd
/home/bk/github/sqlalchemy/examples
➜  examples git:(master) ls postgis
__init__.py  postgis.py
➜  examples git:(master) ls generic_associations
discriminator_on_association.py  generic_fk.py  __init__.py  table_per_association.py  table_per_related.py

```

I did build inside the ``doc/build``, but I cound find the files used under ``postgis``.  As above.

**Comment by zzzeek** [comment]
I notice at: http://www.osgeo.cn/sqlalchemy/orm/examples.html   that the "generic associations" examples are now listed a second time under Postgis, which is incorrect, this might be related to your copying of the files.

send the stack trace that's in for example the file /tmp/sphinx-err-h1cofi3q.log above.

**Comment by bukun** [comment]
I thought it is very stange. To test again, I removed the ``examples`` directory I copied into  ``doc/build`` . 

When I build the following command, the build successfully finished.

    make -e SPHINXOPTS="-D language='en'" html

But, when change ``en`` to ``zh``：

    make -e SPHINXOPTS="-D language='zh'" html

Got the following error:

> The name of the builder is: htmlThe name of the builder is: html
> Exception occurred:
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/zzzeeksphinx/viewsource.py", line 95, in _view_source_node
>     raise ImportError("Error trying to import %s: %s" % (modname, ie))
> ImportError: Error trying to import examples.postgis.discriminator_on_association: No module named 'discriminator_on_association'
> The full traceback has been saved in /tmp/sphinx-err-jezhndcs.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> Makefile:44: recipe for target 'html' failed
> make: *** [html] Error 2

Here the log file:

> # Sphinx version: 2.0.0
> # Python version: 3.5.3 (CPython)
> # Docutils version: 0.14 
> # Jinja2 version: 2.10
> # Last messages:
> #   reading sources... [ 61%] orm/deprecated
> #   
> #   reading sources... [ 62%] orm/events
> #   
> #   reading sources... [ 63%] orm/examples
> #   
> #   The name of the builder is: html
> #   
> #   The name of the builder is: html
> #   
> # Loaded extensions:
> #   sphinxcontrib.devhelp (1.0.1) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinxcontrib/devhelp/__init__.py
> #   sphinx.ext.mathjax (2.0.0) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/ext/mathjax.py
> #   alabaster (0.7.12) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/alabaster/__init__.py
> #   sphinx.ext.autodoc (2.0.0) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py
> #   changelog (unknown version) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/changelog/__init__.py
> #   sphinxcontrib.applehelp (1.0.1) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinxcontrib/applehelp/__init__.py
> #   sphinxcontrib.htmlhelp (1.0.1) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinxcontrib/htmlhelp/__init__.py
> #   zzzeeksphinx (unknown version) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/zzzeeksphinx/__init__.py
> #   sphinxcontrib.serializinghtml (1.1.1) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinxcontrib/serializinghtml/__init__.py
> #   sphinxcontrib.qthelp (1.0.2) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinxcontrib/qthelp/__init__.py
> #   zzzeeksphinx.theme (unknown version) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/zzzeeksphinx/theme.py
> #   sphinx_paramlinks (unknown version) from /home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx_paramlinks/__init__.py
> Traceback (most recent call last):
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/statemachine.py", line 307, in next_line
>     self.line = self.input_lines[self.line_offset]
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/statemachine.py", line 1152, in __getitem__
>     return self.data[i]
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/statemachine.py", line 230, in run
>     self.next_line()
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/statemachine.py", line 310, in next_line
>     raise EOFError
> EOFError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/zzzeeksphinx/viewsource.py", line 93, in _view_source_node
>     tok, [pathname] if pathname else None)
>   File "/usr/lib/python3.5/imp.py", line 296, in find_module
>     raise ImportError(_ERR_MSG.format(name), name=name)
> ImportError: No module named 'discriminator_on_association'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/cmd/build.py", line 284, in build_main
>     app.build(args.force_all, filenames)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/application.py", line 338, in build
>     self.builder.build_update()
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 326, in build_update
>     len(to_build))
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 339, in build
>     updated_docnames = set(self.read())
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 445, in read
>     self._read_serial(docnames)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 467, in _read_serial
>     self.read_doc(docname)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
>     doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/io.py", line 323, in read_doc
>     pub.publish()
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/core.py", line 218, in publish
>     self.apply_transforms()
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/core.py", line 199, in apply_transforms
>     self.document.transformer.apply_transforms()
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
>     super().apply_transforms()
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
>     transform.apply(**kwargs)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/transforms/i18n.py", line 128, in apply
>     node.line, self.config, settings)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/transforms/i18n.py", line 61, in publish_msgstr
>     settings=settings,
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/readers/__init__.py", line 72, in read
>     self.parse()
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
>     self.parser.parse(self.input, document)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/sphinx/parsers.py", line 94, in parse
>     self.statemachine.run(inputlines, document, inliner=self.inliner)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 171, in run
>     input_source=document['source'])
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/statemachine.py", line 245, in run
>     result = state.eof(context)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2696, in eof
>     self.blank(None, context, None)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2688, in blank
>     context, self.state_machine.abs_line_number() - 1)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 418, in paragraph
>     textnodes, messages = self.inline_text(text, lineno)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 427, in inline_text
>     return self.inliner.parse(text, lineno, self.memo, self.parent)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 645, in parse
>     lineno)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 787, in interpreted_or_phrase_ref
>     lineno)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 871, in interpreted
>     nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/zzzeeksphinx/viewsource.py", line 29, in view_source
>     node = _view_source_node(env, text, None)
>   File "/home/bk/vpy_sqlalchemy_x/lib/python3.5/site-packages/zzzeeksphinx/viewsource.py", line 95, in _view_source_node
>     raise ImportError("Error trying to import %s: %s" % (modname, ie))
> ImportError: Error trying to import examples.postgis.discriminator_on_association: No module named 'discriminator_on_association'

**Comment by zzzeek** [comment]
I don't really know the answer, SQLAlchemy's documentation is very large and necessarily adds a lot of missing functionality to sphinx.  perhaps using a newer Python as 3.5 is kind of old.   it seems you're able to generate the documentation overall however.

**Comment by bukun** [comment]
Got the same error using Python 3.7.3 .

Yes,  I could copy the missing files to solve the error.
