### ISSUE TITLE
Log when overflow connections get removed

### ISSUE THREAD

**Issue by Vobo** [sqlalchemy/sqlalchemy#4581]
That would be useful if we could track how often we go to overflow.
Something like
```
--- a/lib/sqlalchemy/pool/impl.py
+++ b/lib/sqlalchemy/pool/impl.py
@@ -151,7 +151,6 @@ class QueuePool(Pool):
                 return False

     def _dec_overflow(self):
-        self.logger.debug("Overflow connection discarded")
         if self._max_overflow == -1:
             self._overflow -= 1
             return True
```

**Comment by zzzeek** [comment]
hi there -

I think it's a good idea that this kind of thing could be in the logging but why would you not want to log when the overflow *increments*?    Also I think it might be more succinct to have the overflow count just wtihin the existing connection checkout/checkin log line.

**Comment by zzzeek** [comment]
like this

```#diff
diff --git a/lib/sqlalchemy/pool/base.py b/lib/sqlalchemy/pool/base.py
index ea73f08d44..34d86bc1c3 100644
--- a/lib/sqlalchemy/pool/base.py
+++ b/lib/sqlalchemy/pool/base.py
@@ -462,6 +462,12 @@ class _ConnectionRecord(object):
         """
         return {}
 
+    def checkout_detail_log(self, connection):
+        return ""
+
+    def checkin_detail_log(self, connection):
+        return ""
+
     @util.memoized_property
     def record_info(self):
         """An "info' dictionary associated with the connection record
@@ -496,7 +502,8 @@ class _ConnectionRecord(object):
         _refs.add(rec)
         if echo:
             pool.logger.debug(
-                "Connection %r checked out from pool", dbapi_connection
+                "Connection %r checked out from pool%s", dbapi_connection,
+                pool.checkout_detail_log(dbapi_connection)
             )
         return fairy
 
@@ -660,7 +667,8 @@ def _finalize_fairy(
     if connection is not None:
         if connection_record and echo:
             pool.logger.debug(
-                "Connection %r being returned to pool", connection
+                "Connection %r being returned to pool%s", connection,
+                pool.checkin_detail_log(connection)
             )
 
         try:
diff --git a/lib/sqlalchemy/pool/impl.py b/lib/sqlalchemy/pool/impl.py
index ada3196612..ee64c4aa37 100644
--- a/lib/sqlalchemy/pool/impl.py
+++ b/lib/sqlalchemy/pool/impl.py
@@ -185,6 +185,16 @@ class QueuePool(Pool):
         self._overflow = 0 - self.size()
         self.logger.info("Pool disposed. %s", self.status())
 
+    def checkout_detail_log(self, connection):
+        return " (current overflow %s)" % (
+            self._overflow,
+        )
+
+    def checkin_detail_log(self, connection):
+        return " (current overflow %s)" % (
+            self._overflow,
+        )
+
     def status(self):
         return (
             "Pool size: %d  Connections in pool: %d "

```

**Comment by Vobo** [comment]
@zzzeek I just thought In terms of log processing (like ELK) it's more convenient to have events that represent deltas rather that the current aggregated state. But in fact that's fine as well. 
I was thinking about `_dec_overflow` because it's only called when we remove an overflow connection. `_inc_overflow` also gets called during filling. But now I realize it's not that important

**Comment by someboredkiddo** [comment]
just echoing on @Vobo's comment, we're interested in using these logs to tune the size of our connection pool to make sure it's large enough that we're not frequently opening overflow connections and paying a performance penalty with the time it takes to connect/disconnect for those queries.

ex. once this message is being logged and we set an alert for seeing a large number of `Overflow connection discarded` logs, we'd know we need to do some tuning. that said, we can just deduce this is an issue if we see a large number of `Connection %r checked out from pool` messages so your code tweak would help us out.

We would like to have this message to always be logged so have a slight preference for the log call to be done at an info level, but understand logging all connection openings/closing has the potential to get chatty. Worse case, if we leave this at debug we can just set the class logging for QueuePool to output at debug.

**Comment by zzzeek** [comment]
keep in mind you have many options to get this general info in your logs, including that you can have an event handler of your own for checkin and checkout and then log the value of "overflow" yourself.     The thing is, the point of overflow is for occasional bursts of activity so I worry that two individual log lines for every one of them will not be received well, whereas we can add the numeric value right to the log right now without upsetting anyone.

**Comment by Vobo** [comment]
@zzzeek I see your point. I was thinking we could add  only a single log line to `_dec_overflow` or `_inc_overflow`. We don't need to add it to both as it doesn't make much sense (if there has been an increment It definitely will be a decrement and vice versa) . I thought as overflow is occasional it's probably not gonna spam anyone

**Comment by zzzeek** [comment]
it's way easier if I just add the numerical output to the existing log line for now, can you guys handle that?

**Comment by zzzeek** [comment]
b.c. then i can just do this and have it in without any risk

**Comment by zzzeek** [comment]
> just echoing on @Vobo's comment, we're interested in using these logs to tune the size of our connection pool to make sure it's large enough that we're not frequently opening overflow connections and paying a performance penalty with the time it takes to connect/disconnect for those queries.
> 
> ex. once this message is being logged and we set an alert for seeing a large number of `Overflow connection discarded` logs, we'd know we need to do some tuning. that said, we can just deduce this is an issue if we see a large number of `Connection %r checked out from pool` messages so your code tweak would help us out.
> 
> We would like to have this message to always be logged so have a slight preference for the log call to be done at an info level, but understand logging all connection openings/closing has the potential to get chatty. Worse case, if we leave this at debug we can just set the class logging for QueuePool to output at debug.

just to note, for the performance issue of the QueuePool not having enough pooled connections and being able to detect this by counting log lines, just looking for  "Created new connection" and "Closing connection" in the log under DEBUG logging shows how often it has to do this, the other reason it may be doing this is due to connections going past their maximum age, but that still adds to the overhead of creating new connections.

To create custom logging using events looks like this:

```
from sqlalchemy import create_engine
from sqlalchemy import event

def log_overflow(e):
    overflow = [e.pool.overflow()]

    @event.listens_for(e, "checkin")
    @event.listens_for(e, "checkout")
    def pool_evt(
        dbapi_connection, connection_record, connection_proxy=None
    ):
        new_overflow = e.pool.overflow()
        if new_overflow != overflow[0]:
            e.pool.logger.info(
                "pool overflow %s to %s",
                (
                    "incremented"
                    if new_overflow > overflow[0]
                    else "decremented"
                ),
                new_overflow
            )
            overflow[0] = new_overflow

e = create_engine("mysql://", echo_pool="debug")
log_overflow(e)

l = [e.connect() for i in range(10)]

for c in l:
    c.close()


```

For now, Im not looking to do anything on this as I think overflow moves too quickly for it to be useful as a log line of its own, the existing logging can be used and events can be used for more real-time measurement and reporting.   I will support adding the numerical "overflow" and other metrics to the existing INFO log lines but I would need either a PR or some positive feedback that this would be useful, reopen if this is the case.
