### ISSUE TITLE
SADeprecationWarning: Use persist_selectable

### ISSUE THREAD

**Issue by Lepiloff** [sqlalchemy/sqlalchemy#4586]
I'm using SQLAlchemy in flask app. Then I run unittest, I get error at console before test results. 

```
    ./home/y700/Env/bee_ml/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py:2399: SADeprecationWarning: The create_engine.convert_unicode parameter and corresponding dialect-level parameters are deprecated, and will be removed in a future release.  Modern DBAPIs support Python Unicode natively and this parameter is unnecessary.
      default.DefaultDialect.__init__(self, **kwargs)
    /home/y700/Env/bee_ml/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:157: SADeprecationWarning: Use .persist_selectable
      info = getattr(mapper.mapped_table, 'info', {})
    .
    ----------------------------------------------------------------------
    Ran 2 tests in 0.062s
    
    OK
```

Could anybody help me to understand why this is happening and fix it?

**Comment by zzzeek** [comment]
hi there -

these are issues in flask-sqlalchemy and should be reported at https://github.com/pallets/flask-sqlalchemy/issues.

the warnings are harmless deprecation warnings and can safely be ignored by end users of flask-sqlalchemy.

**Comment by zzzeek** [comment]
well the second warning is.  the first warning, you should ensure you are not passing the convert_unicode parameter to your create_engine() call.

**Comment by Lepiloff** [comment]
@zzzeek Ok, thanks for you answer.
