### ISSUE TITLE
enhancement: more descriptive error for a particular loadonly usage

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#4589]
The error message on this tripped me up for a bit until I realized what happened. It would be nice if SqlAlchemy could raise something a bit more descriptive of the situation...

A project recently migrated some of it's schema, and a handful of columns were made readable via the legacy interface using standard Python `@property` decorator.

I missed migrating some of the `load_only` elements, and the error raised by SqlAlchemy is:

   AttributeError: 'property' object has no attribute 'property'

While the error makes perfect sense once you know what caused it, debugging it from scratch was a pain as you can't do much with a standard property object in pdb.  It took a long time to figure out the error was from providing a bad column name to loadonly. 

It would be great to catch this issue and state something like 'The column you are attempted to load is a @property object and not an actual column`. 

i don't think doing so would create issues elsewhere, but wanted to propose this enhancement for feedback before attempting a PR.

the attached code illustrates this.  

```
Traceback (most recent call last):
  File "/bugreport/test_orm_changed.py", line 73, in <module>
    print s.query(Foo).options(joinedload('bar').load_only('biz')).first()
  File "/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 1358, in options
    return self._options(False, *args)
  File "<string>", line 2, in _options
  File "/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 201, in generate
    fn(self, *args[1:], **kw)
  File "/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 1375, in _options
    opt.process_query(self)
  File "/lib/python2.7/site-packages/sqlalchemy/orm/strategy_options.py", line 146, in process_query
    self._process(query, True)
  File "/lib/python2.7/site-packages/sqlalchemy/orm/strategy_options.py", line 468, in _process
    query._current_path, query._attributes, raiseerr)
  File "/lib/python2.7/site-packages/sqlalchemy/orm/strategy_options.py", line 639, in _bind_loader
    loader.path, token, None, raiseerr):
  File "/lib/python2.7/site-packages/sqlalchemy/orm/strategy_options.py", line 200, in _generate_path
    attr = attr.property
AttributeError: 'property' object has no attribute 'property'
```

[test_orm_changed.txt](https://github.com/sqlalchemy/sqlalchemy/files/3040778/test_orm_changed.txt)

**Comment by zzzeek** [comment]
that should be fixed esp since I did a huge pass making the strategy messages better so feel free to send a PR.

**Comment by jvanasco** [comment]
Great I'll work on this tomorrow.

Is there a particular test suite for the messages?

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Fixes: 4589 - "enhancement: more descriptive error for a particular l…** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1908

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**More descriptive error for non-mapped string prop name** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1908

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **rel_1_3** branch:

**More descriptive error for non-mapped string prop name** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2182
