### ISSUE TITLE
Can't compile with literal_bind=True a literal None 

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#4591]
Trying to compile
```
sa.literal(None).compile(compile_kwargs={'literal_binds': True})
```
will result in the error
```
CompileError: Bind parameter '%(<some id> param)s' without a renderable value not allowed here.
```
Avoiding the `literal` will instead work:
```
(sa.column('a')==None).compile(compile_kwargs={'literal_binds': True})
```

**Comment by zzzeek** [comment]
there is no "literal binds" representation for NULL.      what is your actual issue ?

**Comment by CaselIT** [comment]
My issue is that I generate an query using a function that transforms literal object using `literal`. 
The query is executed without issues by the db (postgress with psycopg2), but I wanted to log the actual query executed and got this error.
Is there another way to represent a `NULL` as an sqlalchemy object?

It just seems strange that `sa.column('a')==None` compiles while `sa.column('a')==sa.literal(None)` doesn't.

**Comment by zzzeek** [comment]
> My issue is that I generate an query using a function that transforms literal object using `literal`.
> The query is executed without issues by the db (postgress with psycopg2), but I wanted to log the actual query executed and got this error.
> Is there another way to represent a `NULL` as an sqlalchemy object?

yeah, use sqlalchemy.null()

```
>>> print(sa.null().compile())
NULL

```

> 
> It just seems strange that `sa.column('a')==None` compiles while `sa.column('a')==sa.literal(None)` doesn't.

**Comment by CaselIT** [comment]
I did not know it existed.
Still it is strange that literal would not do the same.

Thanks for you reply

**Comment by zzzeek** [comment]
> 
> It just seems strange that `sa.column('a')==None` compiles while `sa.column('a')==sa.literal(None)` doesn't.

when you give it None SQLAlchemy has to interpret the None as something so it chooses "null()":

```
>>> expr = sa.column('a')==None
>>> expr.right
<sqlalchemy.sql.elements.Null object at 0x7fdf4bb1ca58>
>>> print(expr.right)
NULL

```

when you give it "literal()", that means you're looking to use a value.   There is no "None" value in SQL outside of special interpretations like JSON encoded None or a binary zero-termination, there's "NULL" which is not a "value", it's the absense of a value.

**Comment by CaselIT** [comment]
Thanks for the explanation. It makes sense
