### ISSUE TITLE
create_engine fast_executemany flag does not set DBAPI cursor property

### ISSUE THREAD

**Issue by tomanizer** [sqlalchemy/sqlalchemy#4592]
In ```create_engine``` I use the ```fast_executemany```- flag to turn on pyodbc's support for the fast insert feature.

```eng  = create_engine("mssql+pyodbc://myserver/mydb?driver=ODBC+Driver+13+for+SQL+Server", fast_executemany=True)```

But it does not seem to set it on the DBAPI cursor.
If I check the properties of the cursor, fast_executemany is still False.

cursor = eng.raw_connection().cursor()
cursor.fast_executemany 
```False```

I am using:
pyodbc - 4.0.26
sqlalchemy - 1.3.2
odbc driver - ODBC Driver 13 for SQL Server

**Comment by zzzeek** [comment]
fastexecutemany is set by the dialect on only those cursors that are used for "executemany".   it does not apply to raw cursors, you'd need to set that manually.

**Comment by zzzeek** [comment]
specifically what you request is actually impossible because you're calling cursor from the raw DBAPI connection.  SQLAlchemy has no way to affect that even if it wanted, except if it wrapped the whole connection which defeats the purpose of raw_connection.

**Comment by tomanizer** [comment]
Thanks Mike. How can I check if it was set?
I am asking because I do not seem to find any effect on my inserts.

**Comment by zzzeek** [comment]
you can use an after_cursor_execute event like this:  https://github.com/sqlalchemy/sqlalchemy/blob/master/test/dialect/mssql/test_engine.py#L383

the flag requires that a Microsoft ODBC driver is used.

**Comment by zzzeek** [comment]
I can confirm that flag offers an unbeliveable speedup.     Below is a self-contained script that you can try to confirm your driver is honoring the flag:

```
import random
import time

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Float
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    x = Column(Float)
    y = Column(Float)
    z = Column(Float)


def run_test(use_flag, data):
    e = create_engine(
        "mssql+pyodbc://scott:tiger^5HHH@mssql2017:1433/test?driver=ODBC+Driver+13+for+SQL+Server",
        fast_executemany=use_flag,
    )

    Base.metadata.drop_all(e)
    Base.metadata.create_all(e)

    now = time.time()
    s = Session(e)
    s.bulk_insert_mappings(A, data)
    s.commit()

    assert s.query(func.count(A.id)).scalar() == 10000
    total = time.time() - now
    return total

data = [
    {"id": i, "x": random.random(), "y": random.random(), "z": random.random()}
    for i in range(10000)
]

print("data ready")
print("without flag: %s" % run_test(False, data))
print("with flag: %s" % run_test(True, data))

```

I added the assertion at the end to make sure it was actually working, here are the timings:

```
data ready
without flag: 29.909787893295288
with flag: 0.6893811225891113

```

yes that is a 4200% speedup

**Comment by zzzeek** [comment]
I'm assuming we're good here thanks!
