### ISSUE TITLE
StrSQLCompiler can't render element of OnDuplicateClause when upserting data

### ISSUE THREAD

**Issue by troutrun** [sqlalchemy/sqlalchemy#4595]
Hi.

I am trying to upsert sales data (salesId (Primary Key), itemId and description) to a table and I am running into some problems, specifically 
(1) an attribute error: `AttributeError: 'StrSQLCompiler' object has no attribute 'visit_on_duplicate_key_update'` and 
(2) an unsupported compilation error: `sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.StrSQLCompiler object at 0x110e4eda0> can't render element of type <class 'sqlalchemy.dialects.mysql.dml.OnDuplicateClause'>` error. 

Both the errors above trigger when I try to print the on_duplicate_key_stmt variable. I am wondering if I did something wrong here. Thanks

```python
import copy
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import insert

_metadata = sa.MetaData()

Sales = sa.Table(
    'sales',
    _metadata,
    sa.Column('salesId', sa.String(32), primary_key=True),
    sa.Column('itemId', sa.String(32)),
    sa.Column('description', sa.String(32)),
)

sales_data = {'salesId': '1', 'itemId': '1', 'description': 'TESTING'}
sales_data_no_id = copy.deepcopy(sales_data)
sales_id = sales_data_no_id.pop('salesId')

insert_stmt = insert(Sales).values(sales_data)
on_duplicate_key_stmt = insert_stmt.on_duplicate_key_update(**sales_data_no_id)

print(on_duplicate_key_stmt)
```

**Comment by zzzeek** [comment]
you need to pass the correct dialect to the compilation:

```
from sqlalchemy.dialects import mysql
print(on_dup_stmt).compile(dialect=mysql.dialect())
```

see https://docs.sqlalchemy.org/en/latest/faq/sqlexpressions.html#how-do-i-render-sql-expressions-as-strings-possibly-with-bound-parameters-inlined

**Comment by troutrun** [comment]
Ah... that's how it is. Thanks

**Comment by zzzeek** [comment]
oh you mean the two exceptions were chained at once, right, you got just one exception at the end.    im going to add an error doc link to the error here.
