### ISSUE TITLE
[Question] params on sql builder on postgres dialect

### ISSUE THREAD

**Issue by jordic** [sqlalchemy/sqlalchemy#4598]
I had started digging inside the dialects, just to provide an asyncpg dialect suitable to be used for asyncio implementations. The main stopper I found, is on the way params are "rendered" by the builder. Actually found they use to be something like `:param_1` and asyncpg expects to have raw postgres params.. like `$1, $2`. Can anyone point me on the place, "params" are rendered/built?

**Comment by zzzeek** [comment]
right here:

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/compiler.py#L1570

where you'll want to see here:

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/compiler.py#L155

now beyond all that, what we are really doing here is revisiting this PR from the previous tracker: https://github.com/zzzeek/sqlalchemy/pull/433

since this issue is probably going to keep coming up it's good that we can get a link to this issue here.

**Comment by jordic** [comment]
O_O
Another one, using the same asyncpgsa approach [encode/databases](https://github.com/encode/databases/blob/master/databases/backends/postgres.py#L177)
After reading the old issue, I'm not sure, how this has end up. 
Should I provide the PR (with the diff mentioned on your latest comment), or is already merged?

I also had started digging inside all the mechanics around ResultProxy and the way results are "hydrated" to model instances... (Do you think that a asyncpg dialect should contain this data layer: something that can transform RowResults (from asyncpg) to ResultProxy, including the metadata... and providing async methods for the io related apis (cursor, .... )

I have started playing with an async version of orm/Query and had hitted the wall after executing the query and transforming the results to instances... (I can transform simple instances, with an ugly hack, but it's hard for me to understand all the logic behind, mappers, loaders and paths... and I can't "rehydrate" relationships... What I found with the debugger is that the first failing part is on the ResultProxy.. Do you have any docs around the architecture of this part? Somehting I should consider?

**Comment by zzzeek** [comment]
> O_O
> Another one, using the same asyncpgsa approach [encode/databases](https://github.com/encode/databases/blob/master/databases/backends/postgres.py#L177)
> After reading the old issue, I'm not sure, how this has end up.
> Should I provide the PR (with the diff mentioned on your latest comment), or is already merged?

nothing's been done on that, my last diff is probably a good start to supporting non-standard paramstyles but ultimately it probably has to be something more "legit", e.g. a Paramstyle class that includes everything about the paramstyle.  The compiler shouldn't be guessing anymore.    There would then be five Paramstyle classes already set up where those BINDTEMPLATES and they would also include if they are positional or named as well as if they are numeric.   A new dialect can then publish a new Paramstyle object.

> 
> I also had started digging inside all the mechanics around ResultProxy and the way results are "hydrated" to model instances... 

that happens in orm/loading.py


> (Do you think that a asyncpg dialect should contain this data layer: something that can transform RowResults (from asyncpg) to ResultProxy, including the metadata... and providing async methods for the io related apis (cursor, .... )

sure if you are doing async you should have a full ResultProxy and it should also support options for buffered behavior, which is non-blocking and is usually what most DBAPIs do, and additionally it should support not-fully-buffered non-blocking behavior too, that is, some kind of fetchone_async() method.  Huge job but this is what GVR wants everyone to do, so, he's the dictator :)   (I AM BEING SNARKY)


> 
> I have started playing with an async version of orm/Query and had hitted the wall after executing the query and transforming the results to instances... (I can transform simple instances, with an ugly hack, but it's hard for me to understand all the logic behind, mappers, loaders and paths... and I can't "rehydrate" relationships... 

all the stuff in loading.py works against a fully buffered set of rows, there should be no need for async to leak into that with the exception of some of the special loader strategies which you'd ignore for starters.


> What I found with the debugger is that the first failing part is on the ResultProxy.. Do you have any docs around the architecture of this part? Somehting I should consider?

what architecture specifically ?   it wraps around the cursor in https://www.python.org/dev/peps/pep-0249/, that is, it reads cursor.description, sets up a huge data structure from it, then it proxies the fetchXYZ() methods straight to that cursor.

**Comment by jordic** [comment]
> nothing's been done on that, my last diff is probably a good start to supporting non-standard paramstyles but ultimately it probably has to be something more "legit", e.g. a Paramstyle class that includes everything about the paramstyle. The compiler shouldn't be guessing anymore. There would then be five Paramstyle classes already set up where those BINDTEMPLATES and they would also include if they are positional or named as well as if they are numeric. A new dialect can then publish a new Paramstyle object.

Ohh. This seems like a big refactor for something so stable like this. Anyway I will try to consider doing it if I want to use the cool guy of (asyncpg)
 
> sure if you are doing async you should have a full ResultProxy and it should also support options for buffered behavior, which is non-blocking and is usually what most DBAPIs do, and additionally it should support not-fully-buffered non-blocking behavior too, that is, some kind of fetchone_async() method. Huge job but this is what GVR wants everyone to do, so, he's the dictator :) (I AM BEING SNARKY)

Haha, the `async` and `await` keywords are... It's so wired, if you think on lazy props on instances... something like `await obj.realted_items`. 

By the way I'm just considering something that can fetch full joined relations and can explicit save instances (or update them)... nothing so fancy, just an small layer on top of your awesome project.  A poor session could be an explicit transaction, with awaited executions (I know it will be slower than the sync version... but we can parallelize job (other external services) and gather them on the end. And I know we loose a lot on the road (Dependency solver, session merges, the entity map, polymorphic relations.... ), but that seems the price to go async... (I still have doubts about it, and that's the reason I want to keep the model as much compatible with synchronous sqlalchemy, if I hit so many walls I will go with flask or pyramid, that I know will do the job well). Sometimes,I need to try some new things to bypass burnout.. hehe
 

> > What I found with the debugger is that the first failing part is on the ResultProxy.. Do you have any docs around the architecture of this part? Somehting I should consider?
> 
> what architecture specifically ? it wraps around the cursor in https://www.python.org/dev/peps/pep-0249/, that is, it reads cursor.description, sets up a huge data structure from it, then it proxies the fetchXYZ() methods straight to that cursor.

Nothing wrong with yours :) (as expected)... The problem is that I had started with an outside asyncpg layer comming from other implementations, just to prove the concept. (It's hard to trust github repos... ) And the problem is that they are reimplementing a poor results proxy without anything else. Will try to do a second iteration with the aiopg, that on the first eye, seems like is implementing asyncio on top of dbapi ... (And sure is far away more compatible with sqlalchemy).

Anyway so many thanks for your answers and for the work in this project!

**Comment by zzzeek** [comment]
> > nothing's been done on that, my last diff is probably a good start to supporting non-standard paramstyles but ultimately it probably has to be something more "legit", e.g. a Paramstyle class that includes everything about the paramstyle. The compiler shouldn't be guessing anymore. There would then be five Paramstyle classes already set up where those BINDTEMPLATES and they would also include if they are positional or named as well as if they are numeric. A new dialect can then publish a new Paramstyle object.
> 
> Ohh. This seems like a big refactor for something so stable like this. Anyway I will try to consider doing it if I want to use the cool guy of (asyncpg)

It wouldn't be too much of a big deal, the change would be localized to compiler.py and default.py, I can try mocking it up though time is short for the time being..


> 
> > sure if you are doing async you should have a full ResultProxy and it should also support options for buffered behavior, which is non-blocking and is usually what most DBAPIs do, and additionally it should support not-fully-buffered non-blocking behavior too, that is, some kind of fetchone_async() method. Huge job but this is what GVR wants everyone to do, so, he's the dictator :) (I AM BEING SNARKY)
> 
> Haha, the `async` and `await` keywords are... It's so wired, if you think on lazy props on instances... something like `await obj.realted_items`.

OK the "lazy loader" thing is the one part of everything that presents the biggest challenge to async, and IMO the initial approach to that problem should be, "it doesn't lazy load".   There's all of Core that would need to do async first before we even get to the ORM.

> 
> By the way I'm just considering something that can fetch full joined relations and can explicit save instances (or update them)... nothing so fancy, just an small layer on top of your awesome project. A poor session could be an explicit transaction, with awaited executions (I know it will be slower than the sync version... but we can parallelize job (other external services) and gather them on the end. 

any reason you don't just want to use a thread pool and be done with it?   I bet you get no difference in performance

> > what architecture specifically ? it wraps around the cursor in https://www.python.org/dev/peps/pep-0249/, that is, it reads cursor.description, sets up a huge data structure from it, then it proxies the fetchXYZ() methods straight to that cursor.
> 
> Nothing wrong with yours :) (as expected)... The problem is that I had started with an outside asyncpg layer comming from other implementations, just to prove the concept. (It's hard to trust github repos... ) And the problem is that they are reimplementing a poor results proxy without anything else. 

yup saw that

> Will try to do a second iteration with the aiopg, that on the first eye, seems like is implementing asyncio on top of dbapi ... (And sure is far away more compatible with sqlalchemy).
> 
> Anyway so many thanks for your answers and for the work in this project!

my pleasure

**Comment by zzzeek** [comment]
assuming we are good here thanks!
