### ISSUE TITLE
Drop Python 2.7 support and remove compat shims 

### ISSUE THREAD

**Issue by auvipy** [sqlalchemy/sqlalchemy#4600]
Is there any plan or timeline regarding this? I would love to help with the process.

**Comment by zzzeek** [comment]
SQLAlchemy 2 is planned to have quite a dramatic set of changes which require I find a good stretch of time to work out some of the new patterns and validate that they'd even work.   There is a gist that I am maintaining that has current thinking on these plans but I am hesitant to publicize it because nothing is decided.

**Comment by auvipy** [comment]
OK cool. If you want me to start a work in progress PR I will start one right away to give python 2.7 a farewell blow.

**Comment by auvipy** [comment]
if you don't mind you could share that with me on twitter dm @auvipy or email: auvipy@gmail.com

**Comment by zzzeek** [comment]
hey.   OK this is not "a PR " :)   this is like a whole branch where a crapton of SQLAlchemy things are going to go away first within a series of many large gerrits, then get the tests to pass again which will be a huge job, *then* start worrying about py2k removal, that part is easy.

to give a flavor, all of connectionless execution is going away, all of autocommit is going away, all of "reset on return" going away, bound metadata is going away, and hopefully Query is going away

**Comment by zzzeek** [comment]
I've gone through and updated the document with my latest thinking.       I'm OK with it starting to leak now but it's going to be an enormous effort and I worry about it becoming a perl 6 kind of thing.   Here it is: https://gist.github.com/zzzeek/dd590d0a3485b7f19cab0322c48ece36

**Comment by auvipy** [comment]
took the time to read this fully. looks really promising! I will revisit this again and analyze the codes which I might be able to contribute! the unsupported dialects seems an easier one to start?

**Comment by zzzeek** [comment]
the whole list of everything that was deprecated in 1.3 should be easy in fact since I moved all the tests for all the deprecated things into special test_deprecated.py modules.   They'd all become empty in 2.0.     I think 2.0 probably needs to be developed inside a branch, it's too soon to be "master".

**Comment by auvipy** [comment]
ok. I believe so. we are going to follow 5-dev branch for next major celery release works. will look into them

**Comment by auvipy** [comment]
check the SQL module and found many deprecated features. if you open a 2-dev branch I can open PR on that one.

**Comment by zzzeek** [comment]
do you have interest in doing type annotations also?     id like mypy to be part of the test suite

**Comment by auvipy** [comment]
yes sure. what's your preferred way? stub? in master or in 2.0-dev? if 2.0 is 3 only we don't need stub

**Comment by zzzeek** [comment]
We're shooting for pyrhon 3.5 and above, this is real annotations all the way.

Note that dropbox has created stubs already which is likely very useful here: https://github.com/dropbox/sqlalchemy-stubs

**Comment by zzzeek** [comment]
This would likely be best if PRs that target individual subsections are submitted separately, e.g. sqlalchemy.engine, sqlalchemy.pool, sqlalchemy.event, sqlalchemy.orm, etc.  it will be a huge process

**Comment by auvipy** [comment]
ok great. please create a 2.0-dev branch. will come with small segmented PR

**Comment by zzzeek** [comment]
the branch is up, rel_2_0

**Comment by zzzeek** [comment]
also a lot of API changes are occurring which could work against the static typing effort, in that a lot of things are being removed.   the job here might be easier if we wait until the 2.0 API is somewhat in place particularly within the engine package.    Safer areas to start with are events, util, sql packages, probably a lot of ORM

**Comment by auvipy** [comment]
step 1: remove python 2 codes, step2: remove deprecated codes, step 3: type annotations will come with small incremental pr's

**Comment by zzzeek** [comment]
Yeah I am already doing the deprecations thing, a lot of these are going to be big like the threadlocal one that just merged.    There's a lot of small simple ones too so if you work on any just let  me know.

**Comment by auvipy** [comment]
OK then I am going to do the oters, like py2 removal, type annotation etc

**Comment by auvipy** [comment]
I am digging the SQL module first.

**Comment by sqla-tester** [comment]
**Federico Caselli** referenced this issue:

**First round of removal of python 2** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3247

**Comment by sqla-tester** [comment]
**Federico Caselli** referenced this issue:

**Remove object in class definition** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3325

**Comment by sqla-tester** [comment]
**Federico Caselli** referenced this issue:

**Replace raise_ with raise from** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3414

**Comment by zzzeek** [comment]
I think at this point there are hardly any remnants of python 2 left in the main codebase, so marking this as resolved.    there are of course a whole new class of compat shims which are the various 3.7/3.8/etc shims, especially for typing, so we aren't ever going to get out of those woods, but certainly nothing like the 2/3 thing.
