### ISSUE TITLE
postgresql's pg_service.conf file is not loaded any more in 1.3.2

### ISSUE THREAD

**Issue by douardda** [sqlalchemy/sqlalchemy#4601]
Seems a regression in SQLAlchemy 1.3.2. With SQLAlchemy up to 1.3.1 I can use a pg service file to declare db endpoints as described in https://www.postgresql.org/docs/11/libpq-pgservice.html

With the following snipet of code:

```python
# tst.py
from sqlalchemy import create_engine, inspector
engine = create_engine("postgresql:///?service=swh-log")
inspector = inspect(engine)
print(inspector.get_table_names())
```

I have:
```bash
(swh) $ pip install 'SQLAlchemy<1.3.2'
Requirement already satisfied: SQLAlchemy<1.3.2 in /home/ddouard/.virtualenvs/swh/lib/python3.5/site-packages (1.3.1)
(swh) $ python tst.py
['log', 'dbversion']
(swh) $ strace -e open python tst.py 2>&1  | grep service
open("/home/ddouard/.pg_service.conf", O_RDONLY) = 3
(swh) $
```

But with 1.3.2:

```bash
(swh) $ pip install 'SQLAlchemy==1.3.2'
Collecting SQLAlchemy==1.3.2
Installing collected packages: SQLAlchemy
  Found existing installation: SQLAlchemy 1.3.1
    Uninstalling SQLAlchemy-1.3.1:
      Successfully uninstalled SQLAlchemy-1.3.1
Successfully installed SQLAlchemy-1.3.2
(swh) $ python tst.py 
[]
(swh) $ strace -e open python tst.py 2>&1  | grep service
(swh) $
```

So in this later case, we see that:
1. the .pg_service.conf is not even loaded,
2. the failed connection to the db is not reported (with <1.3.2 I get a traceback if I try to use a invalid connection url `postgresql:///?service=nowhere`)

**Comment by douardda** [comment]
might be a side effect of #4562

**Comment by douardda** [comment]
So this revision is the culprit here, but as a side effect of the fact URL.translate_connect_args() makes quite radical assumptions on what options a connection URL may use...

**Comment by douardda** [comment]
So a simple fix might be to always execute `opts.update(url.query)` in `sqlalchemy/engine/url.py` (class URL) like:

```python
    def create_connect_args(self, url):
        opts = url.translate_connect_args(username="user")
        opts.update(url.query)
        if opts:
            if "port" in opts:
                opts["port"] = int(opts["port"])
            # send individual dbname, user, password, host, port
            # parameters to psycopg2.connect()
            return ([], opts)
        else:
            # send a blank string for "dsn" to psycopg2.connect()
            return ([''], opts)
```

**Comment by zzzeek** [comment]
So if we add that line, note that we are still sending a blank string to psycopg2 "host" parameter now, whereas we weren't doing that before.  Does your service file still work if we connect in this way?   that is, it used to be:

   psycopg2.connect(service="swh-log")

and at the moment unless we adjust further, it will be:

   psycopg2.connect('', service="swh-log")

that OK?   otherwise we can try to remove the blank hostname in cases like this

**Comment by zzzeek** [comment]
seems to be fine with or without the blank "" string

**Comment by douardda** [comment]
Yes it seems to be ok with this empty string as host. 
Not sure if this quick fix can have other side effects however...

**Comment by zzzeek** [comment]
OK it seems like if you send *any* parameters to psycopg2, even connect_timeout, then you dont need "dsn".   this is an odd design but im going to ask on #4562 about this also.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Propagate query-arg-only URL to psycopg2; don't send blank host** https://gerrit.sqlalchemy.org/1185

**Comment by douardda** [comment]
@zzzeek thanks a lot!
