### ISSUE TITLE
How to cite SQLalchemy?

### ISSUE THREAD

**Issue by smk508** [sqlalchemy/sqlalchemy#4604]
I can't find any white paper or any location on the sqlalchemy website that mentions citations. Is there a recommended way to cite this library or a bibtex that I could put into a paper to cite sqlalchemy?

**Comment by zzzeek** [comment]
no, but if you know how a project goes about having those things I am open to contributions.

**Comment by smk508** [comment]
A lot of open source libraries publish a white paper (on arXiv, a journal, or just on a website) and then that paper can be cited in order to cite the library.

For example, Pandas, Numpy, etc. all have whitepapers associated with them: https://www.scipy.org/citing.html 

Sometimes, these papers are just posted on arXiv ( this is the official whitepaper for PyTorch: https://openreview.net/forum?id=BJJsrmfCZ), and other times they are just posted to a website (https://www.tensorflow.org/about/bib). 

I imagine if you write up a paper, you would have no problem getting it into any journal, given how impactful sqlalchemy has been. If you don't want to do that, the Journal of Open Source Software has a really fast process for publishing libraries where you just write up a paragraph describing the project and that's it (https://joss.theoj.org/). Lastly, you could probably just declare a 'preferred bibtex format' and post that somewhere on the website for people to use whenever they want to cite sqlalchemy. 

Something like:
@misc{bayer, title={The Python SQL Toolkit and Object Relational Mapper}, url={https://www.sqlalchemy.org/}, author={Bayer, Michael}
}

I would be willing to help out with this if this hasn't already been done.

**Comment by zzzeek** [comment]
can you take a look at http://aosabook.org/en/sqlalchemy.html and see if this is getting close to what we'd term "a paper" ?    There's also a wikipedia page but it seems to be dinged for mostly copying our promotional material from the front page.

**Comment by smk508** [comment]
Yeah, this looks good. I made a bibtex entry based on this book for the chapter you linked. How does this look?

@inbook{brown_2012, place={Mountain View}, title={The architecture of open source applications}, booktitle={The architecture of open source applications volume II: structure, scale, and a few more fearless hacks.}, publisher={lulu.com}, author={Bayer, Michael}, editor={Brown, Amy and Wilson, Greg}, year={2012}}

**Comment by zzzeek** [comment]
looks fine to me, I would not be opposed to having a little "citing" section in SQLAlchemy's website here: https://www.sqlalchemy.org/library.html  if you can suggest a little bit of content for that.

pandas/numpy has a lot of this stuff because they're consumed by the scientific community.   SQLAlchemy is more for the plumbers working in CERN rather than the physicists :)

**Comment by smk508** [comment]
How does this look? I also updated the bibtex slightly:

Please cite SQLalchemy if you use it in your research. You can cite the following [article]
(http://aosabook.org/en/sqlalchemy.html):

Michael Bayer. Sqlalchemy. In Amy Brown and Greg Wilson, editors,The architecture of open source applications volume II: structure, scale, and a few more fearless hacks. aosabook.org, 2012.

Bibtex entry:

@incollection{sqlalchemy, place={Mountain View}, title={SQLalchemy}, booktitle={The architecture of open source applications volume II: structure, scale, and a few more fearless hacks.}, publisher={aosabook.org}, author={Bayer, Michael}, editor={Brown, Amy and Wilson, Greg}, year={2012}
}

**Comment by zzzeek** [comment]
can books be cited also?  because there's [this](https://www.amazon.com/Essential-SQLAlchemy-Mapping-Python-Databases/dp/149191646X) too

**Comment by smk508** [comment]
Are these guys also authors of the library? Assuming that you are the primary author/maintainer, this looks like it would be a secondary source. In other words, this book is a guide for how to use SQLalchemy and would have cited SQLalchemy (via the above Bibtex) in its references.

**Comment by zzzeek** [comment]
Right the book is the secondary source.  the AOSA chapter you see is the only thing I've been able to write in print.

**Comment by zzzeek** [comment]
please review https://www.sqlalchemy.org/library.html#citations , I'm assuming we can use correct casing conventions and stuff like that.  thanks!

**Comment by smk508** [comment]
Part of the chapter title is missing in the bibtex and the curly brackets aren't closed:
The architecture of open source applications volume II: structure_, scale, and a few more fearless hacks._

Otherwise, this looks good.

**Comment by zzzeek** [comment]
the `<pre>` section there is side scrolling, it sounds like you are referring to the overflow, scroll right to see the whole thing.   can i line break the text inside the brackets for this syntax?

**Comment by smk508** [comment]
Ok sorry, I didn't see the side scrolling. Yeah I think this should be fine, since people are going to highlight and copy/paste, so the full thing will get picked up.
