### ISSUE TITLE
Cannot create Postgres table with uppercase/capital letters in identifier

### ISSUE THREAD

**Issue by dbrakman** [sqlalchemy/sqlalchemy#4605]
The following python code completes without error, but tests in the psql console reveal that only a "tmp2" table was created:

```python
import sqlalchemy
from sqlalchemy import create_engine, Table, Column, Integer, String, MetaData

engine = create_engine('postgresql://{user}:{password}@{host}/{dbname}'.format(
    user='myuser', password='password', host='localhost', dbname='mydatabase'))

metadata = MetaData()
tmp1_table = Table('TMP1', metadata,
  Column('id', Integer, primary_key=True),
  Column('foo', String)
)
tmp2_table = Table('tmp2', metadata,
  Column('id', Integer, primary_key=True),
  Column('foo', String)
)
tmp3_table = Table('"TMP3"', metadata,
  Column('id', Integer, primary_key=True),
  Column('foo', String)
)
metadata.create_all(engine)
```

```sql
mydatabase=> select * from tmp1;
ERROR:  relation "tmp1" does not exist
LINE 1: select * from tmp1;
                      ^

mydatabase=> select * from tmp2;
 id | name
----+------
  1 | foo
  2 | bar

mydatabase=> select * from "TMP3";
ERROR:  relation "TMP3" does not exist
LINE 1: select * from "TMP3";
                      ^
```

I would expect
- Table 'tmp1' created according to Postgres' default conversion to lowercase identifiers, and
- Table 'TMP3' created
or
- An exception raised stating that the tables were not created.

**Comment by zzzeek** [comment]
Hi there, and thanks for the complete test case!

When you use a mixed case identifier SQLAlchemy's default is to create a case sensitive identifier, this is documented [here](https://docs.sqlalchemy.org/en/latest/core/metadata.html?highlight=table%20name#sqlalchemy.schema.Table.params.name)

if you turn on echo=True you can see this occurring:

```

CREATE TABLE "TMP1" (
	id SERIAL NOT NULL, 
	foo VARCHAR, 
	PRIMARY KEY (id)
)


2019-04-09 19:45:43,809 INFO sqlalchemy.engine.base.Engine {}
2019-04-09 19:45:43,838 INFO sqlalchemy.engine.base.Engine COMMIT
2019-04-09 19:45:43,843 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE tmp2 (
	id SERIAL NOT NULL, 
	foo VARCHAR, 
	PRIMARY KEY (id)
)


2019-04-09 19:45:43,843 INFO sqlalchemy.engine.base.Engine {}
2019-04-09 19:45:43,862 INFO sqlalchemy.engine.base.Engine COMMIT
2019-04-09 19:45:43,866 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE """TMP3""" (
	id SERIAL NOT NULL, 
	foo VARCHAR, 
	PRIMARY KEY (id)
)


```

you can have exact control over quoting regardless of casing conventions using [quoted_name](https://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.elements.quoted_name).

this area is a bit not well-documented enough and could use its own section but everything you describe is as expected.

**Comment by dbrakman** [comment]
Thanks, @zzzeek. To confirm, tables were created successfully, but not with the names I expected: `TMP1` and `"TMP3"`, verifiable by `select * from "TMP1";` and `select * from """TMP3""";`.

I couldn't figure out how to get output from `echo=True`, but a script to achieve the intended effect of `tmp1` and `TMP3` might be:
```
import sqlalchemy
from sqlalchemy import create_engine, Table, Column, Integer, String, MetaData
from sqlalchemy.sql import quoted_name
import logging

logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)

engine = create_engine('postgresql://{user}:{password}@{host}/{dbname}'.format(
    user='myuser', password='password', host='localhost', dbname='mydatabase'))

metadata = MetaData()
tmp1_table = Table(quoted_name('TMP1', False), metadata,
  Column('id', Integer, primary_key=True),
  Column('foo', String)
)
tmp2_table = Table('tmp2', metadata,
  Column('id', Integer, primary_key=True),
  Column('foo', String)
)
tmp3_table = Table('TMP3', metadata,
  Column('id', Integer, primary_key=True),
  Column('foo', String)
)
metadata.create_all(engine)
```

**Comment by zzzeek** [comment]
yes but more simply just use lower case names.   Some databases like Oracle express case-insensitive identifiers as UPPERCASE, and SQLAlchemy does "normalization" between these different casing convention when creating tables and also looking them up in schema catalogs, so that is why on the user-facing side the rules are more rigid than if you were communicating with PostgreSQL directly.
