### ISSUE TITLE
filter_by() creates an empty condition that breaks subsequent select_from()

### ISSUE THREAD

**Issue by kolypto** [sqlalchemy/sqlalchemy#4606]
Brief: `filter_by()`, called without arguments, breaks `select_from()`

Test case (Pure Python):

```python
import unittest

from sqlalchemy import Column, Integer
from sqlalchemy.orm import Query
from sqlalchemy.ext.declarative import declarative_base

# Define some models
Base = declarative_base()


class User(Base):
    __tablename__ = 'u'
    id = Column(Integer, primary_key=True)


class EmptyFilterByTestCase(unittest.TestCase):
    def test_select_from_after_filter_by(self):
        # Query User, with an empty filter_by()
        input_filter = dict()
        q = Query([User]).filter_by(**input_filter)

        # Inspection: there is a query condition
        assert q.whereclause is not None

        # Inspection: but it is empty
        assert len(q.whereclause.clauses) == 0

        # Now try to use select_from()
        # Logically, it should work fine: there's no real condition present
        # Practically, it gives an error, because there is an empty condition object
        q.select_from(User)


unittest.main()
```

**Comment by zzzeek** [comment]
I would think that breaks a lot of things :)    this use pattern has not been considered.

**Comment by zzzeek** [comment]
thank you for the complete test case.

**Comment by kolypto** [comment]
:D You're absolutely right. This is some poor programming: a `filter_by()` that's called unconditionally, even when there's no input. 

But because of you being a perfectionist, I'm certain you won't let your `Query` be broken down that easy!

**Comment by zzzeek** [comment]
hmmmm also you are just getting the "criterion has already been added" error, which is technically not necessary here but not necessarily incorrect ?   if your dictionary were non-empty then your code would be wrong.    This seems like it's doing the right thing, because you *did* call filter_by().

**Comment by zzzeek** [comment]
that is, it is better to catch a programming mistake structurally, rather than based on data.   by raising even if the data is empty, the error is highlighted structurally.

**Comment by kolypto** [comment]
I agree, `filter_by()` has been called. However, calling `filter()` with no arguments does not break anything. Perhaps, the behavior should be consistent?
 
I'll leave it to your discretion, if you decide the issue is not worth fixing.

**Comment by zzzeek** [comment]
oh OK now that's interesting (again it is news to me you can call query.filter() without an argument, that seems odd).   

I think query.filter() accepting `*args` may have been a newer design decision and here we simply need to remove the and_() implicit in filter_by(), as filter() will do that.

which will lead to what you requested in the first place :)

**Comment by zzzeek** [comment]
but it does mean that your ._whereclause is None.

**Comment by kolypto** [comment]
Sure, thank you! :)

**Comment by kolypto** [comment]
Yes, gotta fix the two `assert`ions in the unit test

**Comment by zzzeek** [comment]
This might be the kind of change that really breaks things for people however so I'm not 100% sure this is safe as a point release.   I'll run it against openstack to see how it fares.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't use and_() inside of Query.filter_by** https://gerrit.sqlalchemy.org/1187
