### ISSUE TITLE
Invalid link in Readme.rst

### ISSUE THREAD

**Issue by ww3pl** [sqlalchemy/sqlalchemy#4612]
Hi folks,

The issue is simple - link to the installation section in SQLAlchemy docs, provided in the Readme for this repo, is invalid.

I can't seem to find any working link which is version independent, though. Any ideas on that?
Correct link: https://docs.sqlalchemy.org/en/13/intro.html#installation
Current (invalid) link: https://www.sqlalchemy.org/docs/intro.html#installation

Same goes for the 'latest docs' reference, although here we indeed can find a version independent URL: 
Correct link: https://docs.sqlalchemy.org
Current link: https://www.sqlalchemy.org/docs/

I'll update the issue with a PR shortly.

**Comment by zzzeek** [comment]
hi there -

I am currently updating the redirects for both sites.   the link is correct

**Comment by ww3pl** [comment]
@zzzeek 
Thanks for the info. I guess we can then discard both the issue and the PR.

**Comment by zzzeek** [comment]
it's helpful that you pointed this out however since I forgot links of that form need to keep working.  should be up again.

**Comment by ww3pl** [comment]
Since the issue is resolved, I'm closing both the issue and the PR. 

Have a good day!
