### ISSUE TITLE
SSL params for pg8000

### ISSUE THREAD

**Issue by JyothiGandi** [sqlalchemy/sqlalchemy#4614]
I'm trying to add SSL to encrypt a connection to Amazon Aurora DB like below. But it was throwing an error. Am I missing something?

**pg8000 (version 1.12.5) supports SSL**

File "...venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
return self.dbapi.connect(*cargs, **cparams)
TypeError: connect() got an unexpected keyword argument 'ssl_ca'

Config:
```
Flask==0.12.4
SQLAlchemy==1.3.3
Flask-SQLAlchemy==2.3.2
pg8000==1.12.5
...
```

Code
```
SQLALCHEMY_DATABASE_URI = "postgresql+pg8000://my-user-name:my-user-password@qwertyuiop.us-east-1.rds.amazonaws.com:5432/my-db-name?ssl_ca=etc/rds-combined-ca-bundle.pem"

def create_app(load_admin=True):
    ...
    app = Flask(__name__,
                template_folder=settings.STATIC_ASSETS_PATH,
                static_folder=settings.STATIC_ASSETS_PATH,
                static_path='/static')

    # configure our database
    app.config['SQLALCHEMY_DATABASE_URI'] = settings.SQLALCHEMY_DATABASE_URI
    app.config.update(settings.all_settings())

    provision_app(app)
    db.init_app(app)
    ....
    return app
```

Link:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.SSL.html

**Comment by zzzeek** [comment]
Hi there -

from what I can see, pg8000 does not accept an argument called "ssl_ca", it has only a single argument "ssl" which refers to a dictionary: 

https://github.com/tlocke/pg8000#pg8000connectuser-hostlocalhost-unix_socknone-port5432-databasenone-passwordnone-sslnone-timeoutnone-application_namenone-tcp_keepalivetrue

There is no "ssl_ca" in the pg8000 source base:

https://github.com/tlocke/pg8000/search?q=ssl_ca&unscoped_q=ssl_ca

Additionally, another part of the confusion here is captured in #4146 , where pg8000 is not trying to emulate the psycopg2 API.   psycopg2 accepts all libpq SSL arguments directly and per http://initd.org/psycopg/docs/module.html#psycopg2.connect these are listed out at https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS .  This would be the driver where you can pass individual SSL arguments in the query string.   I had hoped that #4146 would lead to an improvement in pg8000 but this does not seem to have happened yet.

To send the "ssl" dictionary to pg8000, use the connect_args dictionary:

`e = create_engine("postgresql+pg8000://scott:tiger@host/dbname", connect_args={"ssl": {"sslrootcert": "/path/to/cert"})
`
Based on the above PostgreSQL document, the parameter might be called "sslrootcert", but I'm not sure about the Amazon API you are using.   I do not see any mention of a parameter called "ssl_ca" in the document you linked.

**Comment by JyothiGandi** [comment]
used the "connect_args" like this, it worked for me 👍 

```
class SQLAlchemyExt(SQLAlchemy):
    def apply_pool_defaults(self, app, options):
        cert_path = settings.AMAZON_RDS_SSL_CA_BUNDLE_PATH
        info = make_url(settings.SQLALCHEMY_DATABASE_URI)
        options['connect_args'] = {
            'ssl': dict(ca_certs=cert_path)
        }
        ...
        return super(SQLAlchemyExt, self).apply_driver_hacks(app, info, options)

```
