### ISSUE TITLE
Clear memory from session?

### ISSUE THREAD

**Issue by AleixDev** [sqlalchemy/sqlalchemy#4616]
When I run this code, memory starts increasing for every query and it never gets cleared.
I'm trying to `flush`, `expunge_all` and `close` the session to try to fix this without success... Is there any way to clear this memory? Am I missing something or is this a memory leak?

```
from __future__ import print_function

import time

from sqlalchemy import create_engine
from sqlalchemy import Column, SmallInteger, String
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Test(Base):
    __tablename__ = u'test'

    id = Column('id', SmallInteger, primary_key=True)
    text = Column('text', String(255), nullable=False)


engine = create_engine('sqlite:////tmp/test.sqlite')

Base.metadata.create_all(engine)

SessionMaker = sessionmaker(bind=engine)
session = SessionMaker()


def repopulate_db():
    q = session.query(Test)
    q.delete()

    for i in xrange(0, 50000):
        example_text = str(i * i * i)
        session.add(Test(id=i, text=example_text))

    session.commit()


def test_mem_leak():
    for i in xrange(0, 50000):
        session.query(Test.id, Test.text).filter(Test.id == i).all()

    print('flush...')
    session.flush()
    session.expunge_all()
    session.close()
    print('sleep...')
    time.sleep(3) # (just to see that the memory is not cleared until the script ends)
    print('end')


if __name__ == "__main__":
    # repopulate_db()
    test_mem_leak()
```

I'm running `htop` or this to monitor memory usage:
```
while((1)); do pid=`pgrep -f test_mem_leak.py`; if [[ $pid' ' != ' ' ]]; then ps -o rss= $pid; fi; sleep 1; done
```

Tested with: Python (2.7 and 3.4) and SQLAlchemy (1.3.3 and 1.0.0).

**Comment by zzzeek** [comment]
hi there -

does the memory continue to grow unbounded if you run "test_mem_leak()" in a loop?  that would be a "leak".  The Python interpreter otherwise is not that good at freeing up memory that was legitimately used for a large operation.   take a  look at the answers at https://stackoverflow.com/questions/11800544/why-does-my-python-process-use-up-so-much-memory , including try calling gc.collect() explicitly, to see if any of that helps.

**Comment by zzzeek** [comment]
that is, time.sleep(3) is not going to cut it, put a gc.collect() there at least.

**Comment by AleixDev** [comment]
You're right `gc.collect()` is what I was looking for, thank you for your time :)

**Comment by shihai1991** [comment]
> You're right `gc.collect()` is what I was looking for, thank you for your time :)

Hi, all. Did it works? I run your script and use `gc.collect()` , but I don't see the RSS freed.
