### ISSUE TITLE
consider removal of select.c / .join() for 1.4 as transitional to 2.0

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4617]
looking at the work being done in https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1192/ and how the basic idea here would mostly be a good refactoring in the 1.x series, where the new "clause discovery functions" (these things need a name, been writing hundreds of them for years and they are their own entity now) have been heavily reworked to hopefully be clearer to emit better messaging.   Overall, users should be guided to the more explicit cases, which means things like, don't say `select().order_by(some_select)`, say `select().order_by(some_select.scalar_subquery())`, things like this can emit deprecation warnings in 1.4 where in 2.0 they raise.    

The big thing is seeing if the newer class structure with Alias / Subquery/ ReturnsRows in the above gerrit can travel into the 1.x series; I'd likely restore "Selectable" in between ReturnsRows and FromClause to ease the change.   The one thing that can't really work the same way is that a SELECT from a SELECT without any alias name is really not a thing.   Both Postgresql and MySQL don't do it, SQLite of course does, but overall, the dramatic thing here would be telling users that hey, you don't need select().c for anything, if you've been using it, you should not be.   As well as select.join().   2.0 *will* have select.join() but it's going to do something different.

I guess in 1.4 if we did this, accessing select.c, select.join(), others would raise an exception that they should be calling .subquery() / alias() first.     if it can get through openstack's test suite it's likely potentially OK for a 1.x release.     this will be a big softening of the blow for people moving to 2.0.   bigger picture 1.4 should really be getting developed in parallel with 2.0 so that it can in every way serve as a launching platform.

**Comment by zzzeek** [comment]
the above gerrit should be ported out to remove the type annotations (they were helpful in designing the system), perhaps we can use comment annotations to help with the issue of "please don't accept or return Union[] of things", and the new clause introspection tools need to be completed.   They are good to go for 1.4, there will be a lot of regressions and user issues on them as they are dramatically different and also disallow more things than before, but it will be good to get them out to the userbase sooner rather than later.   

We may need to consider requirement of calling "subquery()" and "scalar_subquery()" rather than implicitly converting, which is the big new behavioral change here.   Let's get it cleaned up, see how it looks and then in particular see how it impacts existing projects like Openstack (probably not a lot since they use all ORM).

 .c and .join() will raise with a very informative error message.  This will be one of the larger migration points for 1.4.    There's no valid use case for using the "select.c" collection or the "select.join" method, when a user calls these they are usually making a mistake so this part should hopefully be OK.

**Comment by zzzeek** [comment]
https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1244/ is the first part of this which rewrites the clause coercion system, since we need a lot better definition here for the from clause change coming up.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**SelectBase no longer a FromClause** https://gerrit.sqlalchemy.org/1312
