### ISSUE TITLE
negation of asboolean

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4618]
this seems wrong

```
>>> from sqlalchemy import column, Boolean
>>> c = column('q', Boolean)
>>> 
>>> print(~c)
NOT q
>>> print(~~c)
NOT q
>>> print(~(~c))
NOT q

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement .compare() for all ColumnElements** https://gerrit.sqlalchemy.org/1195

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_2_0** branch:

**negate True/False separately from other elements** https://gerrit.sqlalchemy.org/1196

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**negate True/False separately from other elements** https://gerrit.sqlalchemy.org/1197
