### ISSUE TITLE
support psycopg2 ver 2.8 connection info

### ISSUE THREAD

**Issue by mozartilize** [sqlalchemy/sqlalchemy#4620]
Hi,

psycopg2 ver 2.8 adds connection info object ([release notes](initd.org/psycopg/articles/2019/04/04/psycopg-28-released/)) and I've just discovered that sqlalchemy connection (`_ConnectionFairy` instance) returns `info` to an empty dict and that causes error when using django_postgrespool2 (issue [here](https://github.com/lcd1232/django-postgrespool2/issues/11))

**Comment by zzzeek** [comment]
hi there -

you can use connection.connection.info for now

**Comment by mozartilize** [comment]
So is there any way can I set _ConnectionFairy.info to psycopg connection info object?

**Comment by zzzeek** [comment]
unfortunately psycopg2 has chosen an attribute name that SQLAlchemy is already using on its connection wrapper.  

the info object on psycopg2 could use some polish, like a meaningful repr:

(Pdb) print(dbapi_connection.info)
<psycopg2.extensions.ConnectionInfo object at 0x7f654a7f24f8>

anyway here's a recipe to copy its data into our own info dictionary, or you could do other things here, for now you can assign it to the connection record:

```
from sqlalchemy import create_engine
from sqlalchemy import event


e = create_engine("postgresql+psycopg2://scott:tiger@localhost/test")

@event.listens_for(e, "connect")
def connect(dbapi_connection, connection_record):
    connection_record.info = dbapi_connection.info


c = e.connect()
print(c.info)

```

if django_postgresqlpool2 is knowingly using SQLAlchemy's connection pool it should try to move through the "connection fairy" before it looks at info

also note if you are using the pool.manage() thing, that's deprecated.

**Comment by mozartilize** [comment]
thanks for your help!
btw as you mentioned about pool.manage is deprecated, I search through documents and did not find any infomation about it. does it relate to engine threadlocal decprecation, maybe?

**Comment by zzzeek** [comment]
oh, it's not even generated in the documentation anymore, so pool.manage is not there at all now.     if you are using pool.manage() you should see a warning coming out, here it is: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/pool/dbapi_proxy.py#L25

**Comment by mozartilize** [comment]
thanks! I'll follow up the docs.
