### ISSUE TITLE
Support for non-existing columns (blue-green deployments)

### ISSUE THREAD

**Issue by leonidumanskiy** [sqlalchemy/sqlalchemy#4622]
**Consider the following scenario:**
We are going from version `1.0` of our application to version `2.0` (with schema changes) and we would like to run blue-green deployments, meaning we want to run version `1.0` and `2.0` at the same time, slowly migrating users. 
Let's say version `2.0` requires a column being renamed (`user.login` -> `user.user_name`).

**Outside of SQLAlchemy, my steps would like like this:**
- Create and deploy temporary version `1.1` of my application, that supports forward-compatibility with `2.0` schemas: logic checks if column `user.user_name` exists, use it, otherwise fall back to `user.login`. Migrate users to app version `1.1`
- Once all users are migrated, shut down version `1.0` and run database migrations, renaming column.
- Deploy version `2.0`, that does not have column existence check.

Another popular approach is to deploy version `2.0` that is backward-compatible with old schemas.

Is there any way to introduce optional columns to `SQLAlchemy` schemas? If not, what is a recommended way to achieve this? 

My first thought is to have multiple versions of schemas, choosing one based on the existence of a new column, however it does not look like a good solution.

**Comment by zzzeek** [comment]
is your application going to run against both schemas in the same process simultaneously ?   if not, just use conditionals when you set up your Table objects.   there are also options depending on if you are using Core or ORM, such as, you can mark columns as 'deferred" an they won't be selected.

**Comment by zzzeek** [comment]
OK what you are doing here is called expand/ contract so you dont need to have "optional" columns, what you do is this:

1. create migrations that add new columns and tables only, all must be nullable
2. run the migrations
3. modify application to use the new columns, but at the same time, it must read and write to the old columns as well.  strategies to do this include:
   a. using triggers to copy data on write between old and new, I like this idea but others seem horrified by it
   b. application level modifications, that is, use SQLAlchemy events or similar to copy things back to the "old" column, ensure queries include both columns and use events to copy from the "old" object attribute to the "new" on read, things like that (there are many options here which should be applied on a case by case basis. often, the case is that the new version uses some totally different set of tables for something, so it's a matter of some extra step copy_structure_to_new_tables, kind of thing)
   c. applications use only the old columns until some kind of global flag is switched, which could happen say when a background process has migrated all the data over (this requires though that none of the applications write to the old columns while the data is being migrated)

the idea with #3 is that the applications know they are running against what is essentially multiple versions of the schema at once (unless you are using the trigger approach).   The reality is that usually most/all of the techniques need to be combined.

so then:

4. all applications are on the new code, now upgrade them all again to no longer refer to the old columns / tables

5. then run "contract" migrations, where the old columns / tables are dropped. 

This works out in practice based on a "leapfrogging" pattern, where the app might have:

version A - new database, new code
version B - expansion migrations are run for version C, database gains columns for version C, code starts reading/copying from version C columns / tables
version C - all applications now communicate with version C, contract migration are run against old version B tables / columns, expansion migrations are run for version D, code starts reading/copying from version D columns / tables
version D - all applications now communicate with version D, contract migration are run against old version C tables / columns, expansion migrations are run for version E, code starts reading/copying from version E columns / tables


that's pretty much the only way this kind of thing goes.   The part where it is either not a big deal, or it is, is how you do step 3, which very much depends on how the application works and what kinds of schema changes are happening.

**Comment by zzzeek** [comment]
hoping this helps!
