### ISSUE TITLE
Warning installing SqlAlchemy: sqla_nose.py

### ISSUE THREAD

**Issue by MarcoSulla** [sqlalchemy/sqlalchemy#4625]
I get this warning while installing sqlalchemy==1.3.3 on python 3.4.2 and Debian 8.11 with `pip3`:

> warning: no files found matching 'sqla_nose.py'

I think it's some unit tests.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove sqla_nose.py from MANIFEST.in** https://gerrit.sqlalchemy.org/1200
