### ISSUE TITLE
backport "threadlocal removal" from 2.0 to 1.4

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4632]
see https://github.com/sqlalchemy/sqlalchemy/commit/b682bb6f6eb2e1a1a4e7483e693d69aa1dbb171e, this should be in 1.4 also

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove threadlocal engine strategy, engine strategies pool threadlocal** https://gerrit.sqlalchemy.org/1356
