### ISSUE TITLE
deprecate metadata.bind, function.bind, e.g. all occurrences of ".bind"

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4634]
start emitting warnings on this

the job is here is documenting it, supporting it

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Deprecate bound metadata** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2302
