### ISSUE TITLE
remove all deprecated extension classes

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4638]
e.g. MapperExtension, SessionExtension, PoolListener, ConnectionProxy, these have been long deprecated .   remove sqlalchemy/interfaces.py entirely.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove deprecated extension and similar classes** https://gerrit.sqlalchemy.org/1500
