### ISSUE TITLE
deprecate all XYZ_all() options

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4642]
e.g. joinedload_all(), subqueryload_all(), etc.   surprised these aren't already deprecaterd?    these all have to warn in 1.4 and removed in 2.0

**Comment by CaselIT** [comment]
I can work on it.

Should we use the normal warning or the removed in 2 one?

**Comment by zzzeek** [comment]
i think these should be for the 1.x series.  there's a bunch of ORM Query things I hope to deprecate through 1.x assuming we have a 1.5 etc.

**Comment by CaselIT** [comment]
Ok

**Comment by CaselIT** [comment]
They do seem to be all deprecated from version 0.9 and do raise a warning.

I've checked `joinedload_all`, `subqueryload_all`, `lazyload_all`, `selectinload_all` and `baked_lazyload_all`
A there other?

Maybe they could be removed for version 1.4?

**Comment by zzzeek** [comment]
they all emit an 0.9 warning?   then....yes we can remove them !  this becomes part of #4643.

**Comment by zzzeek** [comment]
i bet it fails some openstack or something.  those were really widely used functions :)

**Comment by CaselIT** [comment]
Should be easy to check

**Comment by CaselIT** [comment]
`baked_lazyload_all` is deprecated as of 1.2 (along with the normal version). So I guess we will keep it for now

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Remove the deprecated loader options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1761

**Comment by CaselIT** [comment]
> 
> 
> i bet it fails some openstack or something. those were really widely used functions :)

nope, seems the warnings where scary enough 🙂
