### ISSUE TITLE
remove anything deprecated as version 1.1 or prior

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4643]
including:

weak_identity_map
Compiled.compile
ClauseElement.__or__ / __and__
"force" param on quote  (this one might be tricky based on what alembic / openstack are doing not sure)
text.autocommit

basically do a run like this:

    find lib -name "*.py" -exec grep -H -B5 deprecated {} \;

if we have a `@deprecation` decorator on it, and the version is 1.1 or prior, it goes.   If it's the only thing in the source file, the source file goes.   things in test_deprecations go that correspond to it and it can be in one gerrit.

**Comment by yurafff** [comment]
I want to help with this issue. Do you need more help?

**Comment by zzzeek** [comment]
Hi there -

Your help would be welcome.   Can you start with pull requests of relatively limited scope?  such as, each PR focuses on removing deprecations from an individual module, such as the deprecated arguments in session.py.

**Comment by yurafff** [comment]
no problem. today I will start to do it

**Comment by zzzeek** [comment]
hi  -

I just noticed that some of this is in this PR already: https://github.com/sqlalchemy/sqlalchemy/pull/4610  so there's some overlap with @auvipy 's efforts, basically most of this needs to be in the master branch rather than the 2.0.

**Comment by auvipy** [comment]
@yurafff I am already handling this, how much do you cover already?

**Comment by auvipy** [comment]
After getting his confirmation we can assign an issue to anyone specific

**Comment by auvipy** [comment]
should I start work on this?

**Comment by zzzeek** [comment]
hi -

are you still interested in this?   I have a gerrit to remove the extension classes but if you want to do small PRs here each one doing a few files each , that would be great.   if I dont hear from you I'll pick these up in a few days.

**Comment by auvipy** [comment]
yes, I am still interested in this. I am going to come with some small PR to help you.

**Comment by auvipy** [comment]
I started working on it expect some PR on sun day

**Comment by auvipy** [comment]
I found some more deprecations and coming with another PR

**Comment by CaselIT** [comment]
There are still parts to remove, as far back as 0.7, like the `Compiled.compile`
https://github.com/sqlalchemy/sqlalchemy/blob/0a4f7f38ce2b878a4e59da74373938b64bbb6e92/lib/sqlalchemy/sql/compiler.py#L425-L431

**Comment by CaselIT** [comment]
@zzzeek are you still working on this or can I try giving this a go looking for what is missing?

**Comment by zzzeek** [comment]
feel free to work on this, yes.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Remove code deprecated before version 1.1** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1833
