### ISSUE TITLE
create sqlalchemy.future package

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4648]
I think the best way to develop the major API changes for SQLAlchemy 2.0 is to develop them for 1.4 in terms of a "future" package first.     This will contain API compatible versions of the constructs that will be in 2.0, however they will build upon the existing 1.x structures as much as possible:

```
from sqlalchemy.future import core
from sqlalchemy.future import orm

```

things to have in core are:

* the new select() construct that is the "baked' structure we are working out in #4639 
* hopefully, similar insert() / update() / delete() constructs for the above
* a create_engine that returns the simplified API Engine object e.g. only has begin(), no connectionless execution or autocommit
* the new result object
* an adapt_engine that gives you a simplified API Engine on top of a 1.x engine
* maybe a MetaData that has no bind?

Things to have in ORM are:

* an ORM select() facade over Query, which provides the "select" like methods and support for the new result style, this select() will be invoked by the baked select() for ORM use
* the new declarative base features, new mapper() call
* modified Session.  should only accept the new engine/ connection

The Core / ORM packages will also export the full list of all API features that will still be there, like all the Core SQL and schema constructs, event / inspect hooks, all non-deprecated ORM functions, etc.   E.g. these two namespaces should work fully as they will in 2.0.

The future package needs to at least be compilable in Python 2, which means no type annotations.   For the baked query, which might need to use annotations in order to generate proxy methods, my idea is to use the @_generative() decorator to provide a form of annotations for now.

Once futures is in and the tests are set up, this will form the basis for these features in the 2.0 branch.  that is, a lot of the 2.0 work is going to happen first in 1.4.      What will be the big job in 2.0 is adapting all the internals to use all new APIs, in particular the caching APIs used in the ORM will be changing, stuff like that.

**Comment by zzzeek** [comment]
sqlalchemy.future.core.__init__  # core namespace, all types, inspect, pool, non statement elements
sqlalchemy.future.core.connection  # Engine / Connection
sqlalchemy.future.core.result  # result object w/ all / first() / one() / execution options etc.
sqlalchemy.future.core.builder  # cached query builder
sqlalchemy.future.core.selectable # contains Select() construct
sqlalchemy.future.core.dml  # insert / update / delete
sqlalchemy.future.orm.__init__ # ORM namespace
sqlalchemy.future.orm.selectable  # Select() construct
sqlalchemy.future.orm.declarative # new declarative facade, should be minimal
sqlalchemy.future.orm.session  # new Session facade, should be minimal

tests/future/core/test_*.py
tests/future/orm/test_*.py 

for the commit, have the files set up and everything that is *not* being rewritten available for import, that's it.   then the work for the select builder has a place to be merged in towards.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Create initial future package, RemovedIn20Warning** https://gerrit.sqlalchemy.org/1685
