### ISSUE TITLE
support DROP CHECK / DROP CONSTRAINT for CHECK for MySQL/MariaDB

### ISSUE THREAD

**Issue by hahahannes** [sqlalchemy/sqlalchemy#4650]
With version 8.0.16 mysql fully supports constraints. But I noticed that `drop_constraint` of alembic is not working because it produces `ALTER TABLE DROP CONSTRAINT` and not `ALTER TABLE DROP CHECK` which mysql uses

**Comment by hahahannes** [comment]
I think I can do it

**Comment by zzzeek** [comment]
if you can adjust _is_mariadb to return False if server_version_info isn't present that would allow the patch to work.

**Comment by sqla-tester** [comment]
**Hannes Hansen** has proposed a fix for this issue in the **master** branch:

**MYSQL: added support for drop check/constraint** https://gerrit.sqlalchemy.org/1258

**Comment by sqla-tester** [comment]
**Hannes Hansen** has proposed a fix for this issue in the **rel_1_3** branch:

**MYSQL: added support for drop check/constraint** https://gerrit.sqlalchemy.org/1284
