### ISSUE TITLE
The GenericFunction class is registered as a SQL function

### ISSUE THREAD

**Issue by adrien-berchet** [sqlalchemy/sqlalchemy#4653]
As discussed in #4570, the `GenericFunction` class is registered in `sqlalchemy.sql.functions._registry` which seems unintended.

**Comment by zzzeek** [comment]
OK!

**Comment by sqla-tester** [comment]
**Adrien Berchet** has proposed a fix for this issue in the **master** branch:

**Do not register the GenericFunction in sql.functions._registry** https://gerrit.sqlalchemy.org/1248

**Comment by sqla-tester** [comment]
**Adrien Berchet** has proposed a fix for this issue in the **master** branch:

**Do not register the GenericFunction in sql.functions._registry** https://gerrit.sqlalchemy.org/1248

**Comment by sqla-tester** [comment]
**Adrien Berchet** has proposed a fix for this issue in the **rel_1_3** branch:

**Do not register the GenericFunction in sql.functions._registry** https://gerrit.sqlalchemy.org/1254
