### ISSUE TITLE
pylint complains about table.insert() ("No value for argument 'dml' in method call [E1120]") / remove util.dependencies

### ISSUE THREAD

**Issue by solarjoe** [sqlalchemy/sqlalchemy#4656]
see also [here](https://stackoverflow.com/questions/54030879/no-value-for-argument-dml-in-method-call)

When using `sometable.insert()` pylint complains

`"No value for argument 'dml' in method call [E1120]"`

The first parameter for `insert` set by a decorator, so there is no need to pass it 
explicitly.

https://github.com/sqlalchemy/sqlalchemy/blob/64865304051b2af1ee4f90c6bf5e93378d4f302c/lib/sqlalchemy/sql/selectable.py#L1902

**Comment by zzzeek** [comment]
there is unfortunately no way to fix this fully on the SQLAlchemy side at this time, since we use parameter injecting decorators at runtime in order to solve the occasional import cycle.   The best we could do is a "# noqa" however I'd want to limit it to the given E codes, can you try this patch and if so, we will want to get a PR that adds this code to *all* occurrences of `@util.dependencies`:

```diff
diff --git a/lib/sqlalchemy/sql/selectable.py b/lib/sqlalchemy/sql/selectable.py
index a44e94da76..6f82bd3c81 100644
--- a/lib/sqlalchemy/sql/selectable.py
+++ b/lib/sqlalchemy/sql/selectable.py
@@ -1899,7 +1899,7 @@ class TableClause(Immutable, FromClause):
             col._cache_key(**kw) for col in self._columns
         )
 
-    @util.dependencies("sqlalchemy.sql.dml")
+    @util.dependencies("sqlalchemy.sql.dml")  # noqa: E1120
     def insert(self, dml, values=None, inline=False, **kwargs):
         """Generate an :func:`.insert` construct against this
         :class:`.TableClause`.

```

**Comment by zzzeek** [comment]
or maybe on the next line, I'm not sure, flake8 does not report this for me

**Comment by zzzeek** [comment]
also this might be totally wrong, the E1120 might need to be on *your* end, which means, it needs just to be in your setup.cfg.

**Comment by solarjoe** [comment]
Yes, I looked into it and see what you mean. The code you send above does not change anything.
But when I add one of these lines 

```
# noqa pylint: disable=E1120
# noqa pylint: disable=no-value-for-parameter
```
either at top of the file where I am using `insert()` the message is gone.

Setting `dml=None`also doesn't work, that would have been too easy ;) ?

**Comment by zzzeek** [comment]
so yes, at the moment, there's no way for this to be fixed on the SQLAlchemy side.  Ideally we'd have fewer import cycles, or we'd use a different system of handling import cycles which I'm actually evaluating anyway.  but for this one I think it has to be "wontfix", unless it gets fixed someday.

**Comment by solarjoe** [comment]
Second argument to decorator class?

```
@util.dependencies("sqlalchemy.sql.dml", something=None)
def insert(self, dml=something, values=None, inline=False, ...
```

?

**Comment by zzzeek** [comment]
well then I have to make all the arguments keyword arguments.  

again I think figuring out something besides `@util.dependencies` long term is the most likely approach.

**Comment by zzzeek** [comment]
i think the approach should be:

1. remote util.dependencies
2. replace with manual module setting inside of __init__.py files in the `__go()` call at the bottom, which I think we used to do but not sure if that ran into problems.   

let's see if we can try this for 1.4

**Comment by CaselIT** [comment]
> 
> 
> i think the approach should be:
> 
>     1. remote util.dependencies
> 
>     2. replace with manual module setting inside of **init**.py files in the `__go()` call at the bottom, which I think we used to do but not sure if that ran into problems.
> 
> 
> let's see if we can try this for 1.4

Maybe I'm missing something, but why can't we just use an import inside the function?

```py
def insert(self, dml, values=None, inline=False, **kwargs):
        """Generate an :func:`.insert` construct against this
        :class:`.TableClause`.
        E.g.::
            table.insert().values(name='foo')
        See :func:`.insert` for argument and usage information.
        """
        from sqlalchemy.sql import dml
        return dml.Insert(self, values=values, inline=inline, **kwargs)
```

**Comment by zzzeek** [comment]
using imports inside of the functions presents thread safety issues (actually reported, years ago) as __import__ is not threadsafe.

**Comment by CaselIT** [comment]
This is only valid if the module was never imported before.
Otherwise the import statement becomes a noop

**Comment by CaselIT** [comment]
What I mean is that `sql.__init__.py` could import `dml` to ensure the it is imported at least once

**Comment by zzzeek** [comment]
that's what #4689 proposes.   but then there's no need to "import dml" inside of a function, the #4689 approach says that it shoudl cross-populate modules as well, which is already the case if you look at the bottom of the various `__init__.py` modules.

**Comment by CaselIT** [comment]
For 4689 there is no need to do it. I've a patch for it that I'll add to gerrit later

**Comment by CaselIT** [comment]
I'm looking at what `dependencies` does and it should work as is if we remove its `__call__` logic and instead use the import inside the function.
The module is resolved by the normal `dependencies` logic, so the import in the function is actually a noop, and there is no thread safety problem

**Comment by zzzeek** [comment]
sure, I think overall, I really want all the functions and methods to do nothing with importing or dependencies at all.  i just want the modules to be there.   if i see an "import x" in a module, how do I know it's already present in sys.modules?  only if we pulled it from sys.modules explicitly do we know for sure.     if we use the "util.dependencies" thing, sure that can work too but I just dont like that thing very much it's too weird.  but maybe as a quick fix for this, sure.

**Comment by CaselIT** [comment]
If we go for the import in the function and the decorator to ensure that the module is importer so we avoid treading problems, maybe a simpler version of dependencies would be more appropriate.
If we just use it to add modules at the path, it can just be a function decorator that adds the modules to a global set, so that they can be imported by the package init.

**Comment by zzzeek** [comment]
sounds good to me

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Reorganized imports in the orm package to avoid cyclic references** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1773

**Comment by CaselIT** [comment]
The patch set 4 of https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1773 solves this issues, but it gets a significantly higher function call count that makes the test fail, caused most likely by the lazy import in the functions.

I'm not sure if there is a way to avoid it in a nice way. I've made some experiments, but I don't think `y()` or `z()` are great solutions (but they should solve the call count problem).
```
In [1]: def x():
   ...:     from sqlalchemy import orm
   ...:     return orm

In [2]: %timeit x()
701 ns ± 17.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [3]: import sys
   ...: def y():
   ...:     try:
   ...:         orm = sys.modules['sqlalchemy.orm']
   ...:     except Exception:
   ...:         from sqlalchemy import orm
   ...:     return orm

In [4]: %timeit y()
174 ns ± 5.66 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [8]: import sys
   ...: def z():
   ...:     orm = sys.modules['sqlalchemy.orm']
   ...:     return orm
   ...:

In [9]: %timeit z()
148 ns ± 3.1 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
I guess we could just use the `z()` form, since the module will be in the cache.
What do you think @zzzeek ?

**Comment by zzzeek** [comment]
yes, I had suggested earlier that we just look sys.modules for this.   however I think we can probably do even better by providing for a registry that has these symbols ready to go:

```

@util.preload_module("sqlalchemy.orm.strategy_options")
def _emit_lazyload(self, session, state, primary_key_identity, passive):
    strategy_options = util.preload.orm_strategy_options
```

**Comment by CaselIT** [comment]
Yes, we could use this solution.

**Comment by CaselIT** [comment]
New patch set is up. It's much better, since now we require that all modules are registered and resolved.
Let's see if the function count problem is solved

**Comment by CaselIT** [comment]
> Let's see if the function count problem is solved

we now fail because we are too good and the function count is below the expect.

@zzzeek could you update the profiles? I'm on windows so it writes different profiles for it
