### ISSUE TITLE
Support filtered indexes in MSSQL

### ISSUE THREAD

**Issue by mollardthomas** [sqlalchemy/sqlalchemy#4657]
Hello!

I would like to use filtered indexes in MSSQL but I noticed there is no support at the moment.

This is similar to postgresql partial indexes and they could be handled the same way :
```
Index("my_index", table.c.x, mssql_where=table.c.x > 10)
```
would render
```
CREATE INDEX my_index ON table (x) WHERE x > 10
```

I have put together the changes to implement this new feature and will submit a pull request after submitting this issue.

Thanks!

**Comment by zzzeek** [comment]
yes this is a great idea if SQL Server supports this thanks!

**Comment by sqla-tester** [comment]
**mollardthomas** has proposed a fix for this issue in the **master** branch:

**Add support for filtered indexes for mssql dialect** https://gerrit.sqlalchemy.org/1247

**Comment by sqla-tester** [comment]
**mollardthomas** has proposed a fix for this issue in the **rel_1_3** branch:

**Add support for filtered indexes for mssql dialect** https://gerrit.sqlalchemy.org/1255
