### ISSUE TITLE
When using psycopg2 with use_batch_mode=True, false delete warnings are issued

### ISSUE THREAD

**Issue by lauramroa** [sqlalchemy/sqlalchemy#4661]
I'm using psycopg2 with use_batch_mode=True. I have a parent child relationship with two children. If I delete the parent, SQL Alchemy gives me the following warning:

    SAWarning: DELETE statement on table 'child' expected to delete 2 row(s); 1 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.

This does not happen if I don't use batch mode.

Drilling down, the warning is issued in [sqlalchemy/orm/persistence.py](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/persistence.py) around line 1300 (on current master). The problem is that the delete query on line 1329 reports an incorrect row count. Even though the query deletes two rows, the rowcount is 1.

The following is a script that reproduces this error. It reproduces both the false warning _and_ the problem whereby rowcount is incorrect:  

    from sqlalchemy import Column, Integer, ForeignKey, create_engine, String
    from sqlalchemy.ext.declarative import declarative_base
    from sqlalchemy.orm import scoped_session, sessionmaker, relationship

    Base = declarative_base()

    class Parent(Base):
        __tablename__ = "parent"

        pk = Column(Integer, primary_key=True)

        children = relationship(
            "Child", back_populates="parent", cascade="all, delete-orphan"
        )

    class Child(Base):
        __tablename__ = "child"

        pk = Column(Integer, primary_key=True)
        parent_pk = Column(Integer, ForeignKey("parent.pk"), nullable=False)

        parent = relationship("Parent", back_populates="children")

    # Setup the engine + session + tables
    engine = create_engine("postgresql:///transiter_test_db_2", use_batch_mode=True)
    session_factory = sessionmaker(bind=engine, autoflush=False)
    Session = scoped_session(session_factory)
    session = Session()
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)

    def insert_parent_and_two_children():
        # Put one parent with two children
        parent = Parent()
        child_1 = Child()
        child_2 = Child()
        parent.children = [child_1, child_2]
        session.merge(parent)
        session.commit()
        print("Number of children: ", len(session.query(Child).all()))

    def delete_parent_using_orm():
        for parent in session.query(Parent):
            session.delete(parent)
        session.commit()
        print("Number of children: ", len(session.query(Child).all()))

    def delete_children_using_native_query():
        sql = "DELETE FROM child WHERE pk =:pk"
        # Note, following the script then 3 and 4 are the PKs created
        result = session.execute(sql, [{"pk": 3}, {"pk": 4}])
        session.commit()
        print("Number of children deleted: ", result.rowcount)
        print("Number of children: ", len(session.query(Child).all()))

    insert_parent_and_two_children()
    delete_parent_using_orm() # note the warning

    print('----')

    insert_parent_and_two_children()
    delete_children_using_native_query() # note the mismatching numbers

**Comment by lauramroa** [comment]
Just to make it clear: in all cases the correct number of rows are deleted. This is merely an issue with the reported rowcount.

**Comment by zzzeek** [comment]
the rowcount should not be consulted if the dialect reports supports_sane_multi_rowcount=False which is the case for use_batch_mode=True so this a bit of a mystery.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't warn on multi delete rowcount if supports_sane_multi is False** https://gerrit.sqlalchemy.org/1249

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Don't warn on multi delete rowcount if supports_sane_multi is False** https://gerrit.sqlalchemy.org/1250

**Comment by zzzeek** [comment]
we were just warning in the ORM.  old bug

**Comment by jamespfennell** [comment]
Accidentally filed this under my girlfriend's Github account. Awesome! Thanks for the fix.

**Comment by zzzeek** [comment]
the fix for this is wrong, tests fail for a DB that doesnt have sane multi row count.  additionally, the dialect should be supporting -1 for rowcount if this is not supported.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Correct fix and tests for #4661** https://gerrit.sqlalchemy.org/1262

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Correct fix and tests for #4661** https://gerrit.sqlalchemy.org/1263
