### ISSUE TITLE
The first connection against a postgres engine differs in state from all subsequent connections

### ISSUE THREAD

**Issue by MatthewWilkes** [sqlalchemy/sqlalchemy#4663]
Hi there,

When working on https://github.com/niteoweb/pyramid_deferred_sqla/issues/2 we discovered a potential minor bug in the `PGDialect` setup code. We're using the psycopg2 feature `set_session(readonly=True)` to ensure that certain transactions do not cause database writes. This is being done on the underlying connection objects as the readonly feature is not exposed through sqlalchemy as the isolation level is.

This is working well in the general case, however the very first connection that is set-up has already had statements run against it, specifically `show standard_conforming_strings` in
https://github.com/sqlalchemy/sqlalchemy/blob/fd2ecb5f87c1c0132263b5a35067c4bb76160fb2/lib/sqlalchemy/dialects/postgresql/base.py#L2432

The `DefaultDialect` has a similar pattern for feature detection, specifically `select version()` in https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L288-L290 and other commands in that function. These are explicitly rolled back in https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L315 but there is no explicit roll back in the PGDialect initialisation.

For users who are trying to set an isolation level, this isn't a problem as psycopg2's `connection.set_isolation_level(...)` is allowed in this state. However, `connection.set_session(...)` is not, raising an error as the transaction is already in progress.

I suggest we add an explicit rollback to the end of the `PGDialect` feature detection to match the one in `DefaultDialect` as it will allow the assumption that newly created connections to a postgres database have not yet had an implicit transaction begun.

I'm very much aware that sqlalchemy is not intended to support direct manipulation of the underlying connection options, however it appears that an attempt was made to keep the set-up code from affecting user transactions in some places and therefore the fact this dialect does affect the first user transaction appears to be an oversight.

I've attached a simple script that demonstrates this, which will require customisation to the connection string depending on your local environment.

[minrep_py.txt](https://github.com/sqlalchemy/sqlalchemy/files/3148676/minrep_py.txt)

**Comment by MatthewWilkes** [comment]
@zzzeek I just spent some time working on a more generic test, before realising you'd already put a better one than the one I wrote in a later comment. Oops. This PR has been updated with your suggested changes.

**Comment by sqla-tester** [comment]
**Matthew Wilkes** has proposed a fix for this issue in the **master** branch:

**Move initialize do_rollback() outside of the dialect** https://gerrit.sqlalchemy.org/1259

**Comment by sqla-tester** [comment]
**Matthew Wilkes** has proposed a fix for this issue in the **rel_1_3** branch:

**Move initialize do_rollback() outside of the dialect** https://gerrit.sqlalchemy.org/1260
