### ISSUE TITLE
Improve error message when value of create_engine's echo is not expected

### ISSUE THREAD

**Issue by rsyring** [sqlalchemy/sqlalchemy#4665]
In https://github.com/pallets/flask-sqlalchemy/issues/724, we received a traceback that ended with: 

```
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/sqlalchemy/log.py", line 96, in __init__
    if self._echo_map[echo] <= logging.INFO and not self.logger.handlers:
KeyError: '1'
```

I thought it might be helpful to make sure the echo value is in `_echo_map` before it's used and give a more helpful error message.

**Comment by zzzeek** [comment]
hi randy - 

can you provide a simple reproduction case here please as well as version information?    here are my attempts:

```

>>> from sqlalchemy import create_engine
>>> e = create_engine("sqlite://", echo=1)
>>> e.connect()
2019-05-06 14:34:56,880 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-05-06 14:34:56,880 INFO sqlalchemy.engine.base.Engine ()
2019-05-06 14:34:56,881 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-05-06 14:34:56,881 INFO sqlalchemy.engine.base.Engine ()
<sqlalchemy.engine.base.Connection object at 0x7f87a32cae80>
>>> e.echo = 1

```

**Comment by rsyring** [comment]
Interesting!  Maybe it's FSA's problem.  We can dig in further and produce a test case if we still think it's your problem (or close the issue if we don't).  Sorry for the bother.  :)

**Comment by rsyring** [comment]
We were not able to reproduce with a simple test case.  Thanks for the quick response and sorry for not doing my homework before opening the issue.  If our OP does produce a simplified test case and it looks like an SA problem, I'll be back.

**Comment by zzzeek** [comment]
OK, it does *look* like our case, since how did they get a "1" in there.  maybe an older version ?   I haven't looked at the code and I'm assuming somewhere I'm calling bool() on the integer value.
