### ISSUE TITLE
Considering using @dataclass for classes

### ISSUE THREAD

**Issue by auvipy** [sqlalchemy/sqlalchemy#4666]
or @dataclass 3.6+ feature

**Comment by zzzeek** [comment]
oh wow, see I had assumed you wanted ORM mappings to start using this, since someone had brought that up at some point.      So.... this is for the Python 3 only version ?

**Comment by zzzeek** [comment]
are you seeing the timestamps coming up wrong on this issue and others?   or is it my computer's clock or something

**Comment by auvipy** [comment]
attrs supports both python 2.7 and 3.4 as per docs https://github.com/python-attrs/attrs, if you want I can help to impement this on 1.4 versions as well.this is used by many popular python projects

**Comment by zzzeek** [comment]
what are we implementing?   also this is a third party dependency?   strong -1 on that unless there is an extremely good reason

**Comment by zzzeek** [comment]
I thought we were talking about dataclasses.  Looking at attrs,  I would be very concerned about complexity being introduced as SQLAlchemy does **a lot** of tinkering with class mechanics in order to squeeze out speed improvements.

**Comment by auvipy** [comment]
for the dataclass it is python 3.6 only

**Comment by auvipy** [comment]
https://realpython.com/python-data-classes/

using dataclass would be nice. it was initially implemented as a 3rd party package to work with py3.6 and later impemented into the core.

**Comment by auvipy** [comment]
OK sure. allow me some time to come with more detail. in short, this will be for internal classes only and no public user-facing classes need to be changed.

**Comment by zzzeek** [comment]
Ok -

Yes the `@dataclass` thing is nice and I fully plan to make use of all Python 3.6+ features in SQLAlchemy 2, as you can see on line 70 of https://gist.github.com/zzzeek/1f7bd3cc19e7ebea8f364e5b40577067 I'm using pep-526 with typing.NamedTuple and we'll have lots of that.

as far as a deliverable here I'd rather wait for specific changes to be proposed as we work on the Python 3 only codebase....is that OK ?

**Comment by zzzeek** [comment]
python 3.6 or python 3.7, it will be in the coming year so whichever.

**Comment by auvipy** [comment]
yes of course.

**Comment by auvipy** [comment]
> Ok -
> 
> Yes the `@dataclass` thing is nice and I fully plan to make use of all Python 3.6+ features in SQLAlchemy 2, as you can see on line 70 of https://gist.github.com/zzzeek/1f7bd3cc19e7ebea8f364e5b40577067 I'm using pep-526 with typing.NamedTuple and we'll have lots of that.
> 
> as far as a deliverable here I'd rather wait for specific changes to be proposed as we work on the Python 3 only codebase....is that OK?

perfectly makes sense.

**Comment by zzzeek** [comment]
closing this, as we want to have more specific things.

**Comment by kapilt** [comment]
I think the notional value here is something in sqla ext that allows for the transformation of a data class to a SQLAlchemy ORM derived class. The nearest thing I've seen here is something https://github.com/karlicoss/cachew.git which is is a bit limited in translations abilities.

**Comment by zzzeek** [comment]
related dataclass discussion at #5027
