### ISSUE TITLE
Support for Apache Phoenix

### ISSUE THREAD

**Issue by archenroot** [sqlalchemy/sqlalchemy#4668]
Hell, I have backend storage on Apache Phoenix:
https://phoenix.apache.org/language/index.html

How hard it could be to exten sqlalchemy for support this?
Main difference I see is it uses UPSERT instead of INSERT/UPDATE, otherwise it is very close to any other sql engine.

Any hints welcomed!

**Comment by zzzeek** [comment]
Well start with the new dialects README at: https://github.com/sqlalchemy/sqlalchemy/blob/master/README.dialects.rst

the UPSERT thing may be a bit of a blocker though.  How do you foresee SQLAlchemy being used with this database if it has no distinct INSERT or UPDATE commands ?   are you looking for read-only access, or just that users would need to use Core only or updating using a phoenix-specific construct ?

**Comment by zzzeek** [comment]
Core is this:  https://docs.sqlalchemy.org/en/13/core/tutorial.html

ORM is this:  https://docs.sqlalchemy.org/en/13/orm/tutorial.html

the ORM has much more elaborate expectations of how inserts and updates work.

**Comment by zzzeek** [comment]
hope this helps feel free to reopen for more questions thanks!
