### ISSUE TITLE
Intercept the query before execution

### ISSUE THREAD

**Issue by lohxx** [sqlalchemy/sqlalchemy#4669]
Is there a way to change all queries emitted to the database? I'm trying to do this using the before_compile event, but i would like to know if is there another way to do this.

**Comment by zzzeek** [comment]
before_cursor_execute is the most direct

https://docs.sqlalchemy.org/en/13/core/events.html?highlight=before_cursor_execute#sqlalchemy.events.ConnectionEvents.before_cursor_execute

**Comment by lohxx** [comment]
I have to had the informations about the table that is being queried, i don't know if the before_cursor_execute is gonna help me, the before_compile event gives me more info because of query object.

**Comment by zzzeek** [comment]
there are many ways to communicate messages between the two event hooks.   one very straightforward way unfortunately [isn't working](https://github.com/sqlalchemy/sqlalchemy/issues/4670) so another is to use the .info dictionary on the Connection (same example, different dictionary):
```

from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy import event
from sqlalchemy.orm import Query

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add_all([A(data='a'), A(data='b')])
s.commit()

@event.listens_for(Query, "before_compile")
def _before_compile(query):
    query.session.connection().info['my_option'] = True

@event.listens_for(e, "before_cursor_execute", retval=True)
def _before_cursor_execute(conn, cursor, statement, parameters, context, executemany):
    if conn.info.pop('my_option', False):
        statement = "-- my option found\n" + statement
    return statement, parameters

s.query(A).all()
```

this is taken from the wiki example at https://github.com/sqlalchemy/sqlalchemy/wiki/SessionModifiedSQL

**Comment by zzzeek** [comment]
hope this helps feel free to reopen for more questions thanks!
