### ISSUE TITLE
cant set execution options in before_compile event

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4670]
this is lame, because we don't use the modified query to make the new connection

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy import event
from sqlalchemy.orm import Query

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add_all([A(data='a'), A(data='b')])
s.commit()

@event.listens_for(Query, "before_compile", retval=True)
def _before_compile(query):
    return query.execution_options(my_option=True)

@event.listens_for(e, "before_cursor_execute", retval=True)
def _before_cursor_execute(conn, cursor, statement, parameters, context, executemany):
    if context.execution_options.get("my_option", False):
        statement = "-- my option found\n" + statement
    return statement, parameters

# no comment, no option
s.query(A).all()
```

**Comment by amacfie** [comment]
Appears to be fixed on master

**Comment by zzzeek** [comment]
that makes sense because the execution mechanics have been completely rewritten.  however this issue would need a test added to verify.

**Comment by RamonWill** [comment]
Hey @zzzeek, 
I'm happy to create the test for this but just not sure what parameters I can use for execution_options on a Query Class on an sqlite database. From the docs i can see that shares parameters with the connection class but just not sure which ones i can use for a test.

```diff
@event.listens_for(Query, "before_compile", retval=True)
def _before_compile(query):
    x =  query.execution_options(my_option=True)
+   x.get_execution_options() # this will return immutable dict {my_option:True}
    return x

@event.listens_for(e, "before_cursor_execute", retval=True)
def _before_cursor_execute(conn, cursor, statement, parameters, context, executemany):
    if context.execution_options.get("my_option", False):
        statement = "-- my option found\n" + statement
    return statement, parameters

# no comment, no option
+s.query(A).get_execution_options() # this will return an empty immutable dictionary
s.query(A).all()
```
From debugging the code i can see that execution options in _before_compile are used but they aren't bound to the global query, so when i perform get_execution_options() i get a blank immutable dictionary.

Any guidance would be appreciated

Thanks,
Ramon

**Comment by zzzeek** [comment]
hi @RamonWill -

in this case, the execution option only needs to take effect when the SQL statement is executed, which is what we intercept within the before_cursor_execute event.   it won't be copied out to the outermost Query as you've observed.

so how we test these things is by collecting what we see inside of before_cursor_execute and asserting that.  I usually use the mock library to gather data like this, although a plain Python list/dict can work too, likely better in this case:

```

from sqlalchemy import column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy.orm import Query
from sqlalchemy.orm import Session

e = create_engine("sqlite://", echo=True)


@event.listens_for(Query, "before_compile", retval=True)
def _before_compile(query):
    return query.execution_options(my_option=True)


opts = {}

@event.listens_for(e, "before_cursor_execute")
def _before_cursor_execute(
    conn, cursor, statement, parameters, context, executemany
):
    opts.update(context.execution_options)

s = Session(e)
s.query(column('1')).all()

assert opts["my_option"] == True

```

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **master** branch:

**Test execution_options on Query object before compilation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2081
