### ISSUE TITLE
Can no longer use delattr to remove auto incrementing primary key prior to sending data to Sql Server

### ISSUE THREAD

**Issue by sarahdorich** [sqlalchemy/sqlalchemy#4673]
I've been using `delattr(table, "Id")` where `table` is a sqlalchemy.ext.declarative.api.DeclarativeMeta and  "Id" is an auto incrementing primary key (meaning Sql Server will automatically fill this column in when I insert data). This deletes the primary key column of the table prior to sending data to the database (to avoid Sql Server errors). But as of 1.3.x, this is not allowed. I get an error 
"cant un-map individual mapped attributes on a mapped class".

Is there an alternative way to achieve what I need to or do I just need to use sqlalchemy 1.2.x going forward?

**Comment by zzzeek** [comment]
Hi there -

it's not clear how you are getting to where you are.   Why does your "table" class have an "Id" attribute in the first place, if you don't want it to have one?  How are you creating this declarative class ?

Additionally, SQL Server identity columns are fully supported, there is no error that is raised simply by mapping to an IDENTITY column.   SQL Server doesn't like if you provide a value for the column without first setting IDENTITY INSERT to "off", however, in this case, you simply don't provide an integer value for the column.  Even if you *did* do so, SQLAlchemy detects this and does the IDENTITY INSERT step though this is not recommended.

The real question is what exactly are the "SQL Server errors" you refer towards and can you please provide stack traces and complete error messages, as well as how you are creating the "table" declarative mapped class, and what the CREATE TABLE for the table in question (just the autoincrementing key part as well as any sequence objects required) looks like.

**Comment by sarahdorich** [comment]
Hi @zzzeek,

Thanks for the quick reply on this. Hopefully this detail answers your questions. Let me know if you need anything else.

Below is how I create the declarative class. The reason I include an Id column is because I want an Id column in the table. I just don't want to load data to it manually (as Sql Server will do that b/c it's an auto increment column - I know I can set IDENTITY INSERT to off but this is a lot of overhead IMO). The SQL Server errors I'm referring to is just if I try to insert data into this column without turning IDENTITY INSERT to "off" which obviously would occur. 

```
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import MetaData, Column, Integer, VARCHAR, DateTime, Boolean, DECIMAL, DATE, BIGINT, FLOAT, NUMERIC
from sqlalchemy import inspect

SCHEMA = 'myschema'
Base = declarative_base(metadata=MetaData(schema=SCHEMA))

class StagingGeographicalDistributionByCountry(Base):
    __tablename__ = 'StagingGeographicalDistributionByCountry'

    Id = Column(BIGINT, primary_key=True, autoincrement=True)
    SiteId = Column(Integer)
    StartDateMst = Column(DATE)
    EndDateMst = Column(DATE)
    CountryId = Column(BIGINT)
    CountryName = Column(VARCHAR)
    AvgVisitTimeSeconds = Column(FLOAT)
    BounceRatio = Column(FLOAT)
    IpCount = Column(Integer)
    Pageviews = Column(Integer)
    VisitorCount = Column(Integer)
```

Then in a main method, I use the `Base.metadata.create_all(engine)` to create this table.

Then I have a separate class that handles all interactions with the database. This class contains a method that takes in a pandas DataFrame (without an Id column but with all the other columns in the staging tables created with the declarative mapped class), a table name (that must map to a declarative mapped class such as `StagingGeographicalDistributionByCountry` (above). This method then creates a sqlalchemy engine, session, DeclarativeMeta table based on the table name supplied and uses the method `session.bulk_insert_mappings` to insert data from the pandas DataFrame into the table in Sql Server. 

Prior to sqlalchemy version 1.3.x, I was able to use `delattr` to remove the Id column prior to loading the rest of the data in this way. I couldn't find an alternative way to still create the table with a primary, auto incrementing key but load data without that column having data (maybe there is a better/different way?)

**Comment by zzzeek** [comment]
I still dont know why you need to remove the "StagingGeographicalDistributionByCountry.id" attribute.    SQLAlchemy will emit an INSERT that does not include this column if you do not provide a value for it.

Here is a demonstration.
```

from sqlalchemy import BIGINT
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(BIGINT, primary_key=True, autoincrement=True)
    data = Column(String)


e = create_engine("mssql+pyodbc://scott:tiger^5HHH@mssql2017:1433/test?driver=ODBC+Driver+13+for+SQL+Server", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.bulk_insert_mappings(
    A, [{"data": "some data %d" % i} for i in range(100)]
)


s.commit()

```

here's the INSERT at the end:

```
CREATE TABLE a (
	id BIGINT NOT NULL IDENTITY(1,1), 
	data VARCHAR(max) NULL, 
	PRIMARY KEY (id)
)


2019-05-10 17:14:11,008 INFO sqlalchemy.engine.base.Engine ()
2019-05-10 17:14:11,013 INFO sqlalchemy.engine.base.Engine COMMIT
2019-05-10 17:14:11,020 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-05-10 17:14:11,023 INFO sqlalchemy.engine.base.Engine INSERT INTO a (data) VALUES (?)
2019-05-10 17:14:11,023 INFO sqlalchemy.engine.base.Engine (('some data 0',), ('some data 1',), ('some data 2',), ('some data 3',), ('some data 4',), ('some data 5',), ('some data 6',), ('some data 7',)  ... displaying 10 of 100 total bound parameter sets ...  ('some data 98',), ('some data 99',))
2019-05-10 17:14:11,336 INFO sqlalchemy.engine.base.Engine COMMIT

```

**Comment by zzzeek** [comment]
hi there -

is that helping?   if you have what you need I'd like to close this.

**Comment by sarahdorich** [comment]
Hi @zzzeek, 
Yes, this helps. I was definitely over-complicating this for myself. 
Thanks for helping with my issue.

**Comment by zzzeek** [comment]
ok great!
