### ISSUE TITLE
message 20047 not recognized as disconnect in pymssql dialect

### ISSUE THREAD

**Issue by JonSchuff** [sqlalchemy/sqlalchemy#4680]
### Issue
Due to a recent change in freeTDS (>= 1.1.5), message 20047 `DBPROCESS is dead or not enabled` is now raised at a severity high enough to trigger an OperationalError to be raised by pymssql, which then cascades up to the is_disconnect function. Before the freeTDS change, the err msg was raised with an EXINFO severity level, causing pymssql to consume the message and retry on a fresh connection, which is why we haven't been faced with this issue before.
### Proposed Solution
Add message 20047 to the disconnect msg tuple in the pymssql dialect's is_disconnect function.

**Comment by sqla-tester** [comment]
**Jon Schuff** has proposed a fix for this issue in the **master** branch:

**Issue 4680 - recognize message 20047 as disconnect event in MSDialect_pymssql** https://gerrit.sqlalchemy.org/1268

**Comment by sqla-tester** [comment]
**Jon Schuff** has proposed a fix for this issue in the **rel_1_3** branch:

**Recognize message 20047 as disconnect event in MSDialect_pymssql** https://gerrit.sqlalchemy.org/1269
