### ISSUE TITLE
Add Support for MSSQL geography and geometry spatial data types

### ISSUE THREAD

**Issue by gmonkman** [sqlalchemy/sqlalchemy#4683]
MSSQL added geography and geometry data types to support spatial data in MSSQL 2008. Is it possible to add SQLAlchemy support for these data types?

**Comment by zzzeek** [comment]
right now geometry types are part of [Geoalchemy2](https://geoalchemy-2.readthedocs.io/en/latest/) where they have great maintainers who know all about how those types should work.   it would be more appropriate to propose this over there.

**Comment by zzzeek** [comment]
however, geoalchemy is working iwth the postgis *extension*.   So we might want to have basic reflection / creation support for these types here.  But having them do in-python geoaclhemy style operations would be out of scope (but also we'd need to see if geoalchemy can support that part of it).

**Comment by zzzeek** [comment]
@elemoine do you have thoughts on placement for SQL Server geometry types ?  Should I do something basic directly in SQLAlchemy and is this in scope at all for geoalchemy?

**Comment by elemoine** [comment]
GeoAlchemy currently works with both PostgreSQL/PostGIS and SQLite/SpatiaLite, with a specific focus on PostGIS. There is currently no plan to support MSSQL, but this could possibly be evaluated again.

**Comment by zzzeek** [comment]
@gmonkman can you clarify what functionaltiy you are looking for

**Comment by gmonkman** [comment]
Good morning, basic CRUD for geography and geometry data types, probably by instantiating type instances with an syntax similiar to SQL Server.

Here is an insert example from:
[https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/spatial-types-geography?view=sql-server-2017](https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/spatial-types-geography?view=sql-server-2017)
```

INSERT INTO SpatialTable (GeogCol1)  
VALUES (geography::STGeomFromText('LINESTRING(-122.360 47.656, -122.343 47.656 )', 4326)); 
```


And the supported spatial data types are listed here: [https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-sql-server?view=sql-server-2017](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-data-sql-server?view=sql-server-2017)

Sorry can't give a more precise design definition - deadline on something else!

thanks
Graham

**Comment by gmonkman** [comment]
To add, SQL Server makes use of the Open Geospatial Consortium (OGC) Well-Known Text (WKT) representation of a geometry instance to providhuman readable features, e.g. the LINESTRING in my last comment.

**Comment by zzzeek** [comment]
So the syntaxes there are not directly supported by SQLAlchemy Core without implementing extensions (this is not hard, but it's intended to be "extension" code outside of Core itself) and look very much like the syntaxes that GeoAlchemy does implement.   I'm not sure about the "GeogCol2 AS GeogCol1.STAsText()" syntax, I've not seen a "column that's a function of another column" syntax before.  

I'm not sure what the development resources are but this is the type of thing we wanted to be in GeoAlchemy2.

**Comment by zzzeek** [comment]
reiterating #5078, adding support for geo types can be in SQLAlchemy or Geoalchemy and IMO it should be probably easier in Geoalchemy since the framework for the standard geo types is already there.    I really would like to see some contributors, perhaps those that would want to work on SQLAlchemy, also take some role in giving attention to Geoalchemy2.  If geoalchemy2 thinks it would gain prominence by being under the github sqlalchemy organization I would consider that.

**Comment by ChanduArepalli** [comment]
Is there any chance or references to integrate GeoAlchemy with MSSQL?

**Comment by zzzeek** [comment]
wouldnt know here, you would need to talk to the [geoalchemy](https://geoalchemy-2.readthedocs.io/en/latest/) maintainers.
