### ISSUE TITLE
pysqlcipher3: wrong error excepted

### ISSUE THREAD

**Issue by dordin** [sqlalchemy/sqlalchemy#4684]
https://github.com/sqlalchemy/sqlalchemy/blob/6f270fb0e344016ce526e0a1ecb3e3de9ffd1e3b/lib/sqlalchemy/dialects/sqlite/pysqlcipher.py#L96

An `ImportError` is excepted, but a `ModuleNotFoundError` is raised.

**Comment by zzzeek** [comment]
hi there -

ModuleNotFoundError is a subclass of ImportError so the exception is caught.  Can you please provide more specifics as to the actual problem you are having?

**Comment by dordin** [comment]
Sorry, my mistake.

I was misled by a problem in pysqlcipher3.
