### ISSUE TITLE
Association proxy proxying hybrid property doesn't work anymore (>= 1.3)

### ISSUE THREAD

**Issue by nphilipp** [sqlalchemy/sqlalchemy#4690]
In my application, I use an association proxy on a hybrid property in the target collection, see https://gist.github.com/nphilipp/a1b490b762c1616baf48bf1e5930c637 for a test case. This worked as expected in SQLAlchemy versions < 1.3 (I checked with 1.2.19, 1.1.18, 1.0.19, 0.9.10). With 1.3.3 or the current tips of the rel_1_3 (`18bbd3396`) and master (`f07e050c9`) branches, I get a traceback like this one:

```
Traceback (most recent call last):
  File "testcase.py", line 86, in <module>
    lang=iso_code
  File "/home/nils/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 1796, in filter_by
    for key, value in kwargs.items()
  File "/home/nils/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 1796, in <listcomp>
    for key, value in kwargs.items()
  File "/home/nils/src/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 769, in __eq__
    self._ambiguous()
  File "/home/nils/src/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 758, in _ambiguous
    self.target_class,
AttributeError: Association proxy Keyword._lang refers to an attribute 'iso_code' that is not directly mapped on class <class '__main__.Language'>; therefore this operation cannot proceed since we don't know what type of object is referred towards
```

Bisecting found this commit as the first one where it didn't work anymore:

```
90574aabef36fd59841b7df7d8ac30e2030e9854 is the first bad commit
commit 90574aabef36fd59841b7df7d8ac30e2030e9854
Author: Mike Bayer <mike_mp@zzzcomputing.com>
Date:   Tue Oct 23 19:38:46 2018 -0400

    Create object- and column-oriented versions of AssociationProxyInstance
    
    The :class:`.AssociationProxy` now has standard column comparison operations
    such as :meth:`.ColumnOperators.like` and
    :meth:`.ColumnOperators.startswith` available when the target attribute is a
    plain column - the EXISTS expression that joins to the target table is
    rendered as usual, but the column expression is then use within the WHERE
    criteria of the EXISTS.  Note that this alters the behavior of the
    ``.contains()`` method on the association proxy to make use of
    :meth:`.ColumnOperators.contains` when used on a column-based attribute.
    
    Fixes: #4351
    Change-Id: I310941f4e8f778c200f8144a26a89e5364cd4dfb
```

**Comment by zzzeek** [comment]
im not sure how there aren't tests for proxying of hybrids at the expression level.    There are so many assocaition proxy tests....

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add QueryableAttribute._impl_uses_objects accessor for AssociationProxy** https://gerrit.sqlalchemy.org/1274

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Add QueryableAttribute._impl_uses_objects accessor for AssociationProxy** https://gerrit.sqlalchemy.org/1275

**Comment by nphilipp** [comment]
This was quick, thanks! I'll test this as soon I can.

**Comment by zzzeek** [comment]
ORM issues like these are *extremely* zinging for me.   if you wanted some new MySQL thing, that would be different :)

**Comment by nphilipp** [comment]
Hah! Anyway, just tested it with my application and the change fixes the issue in both master and rel_1_3 branches.
