### ISSUE TITLE
attribute events not fired for inherited classes

### ISSUE THREAD

**Issue by youtux** [sqlalchemy/sqlalchemy#4691]
I'm trying to update the [traduki](https://github.com/paylogic/traduki) library to not use `AttributeExtension`, since it has been deprecated in sqlalchemy v1.3.

I am trying to use the `event.listen` interface, but it seems that it doesn't work for inherited classes.

At [this commit](https://github.com/paylogic/traduki/commit/0f9e7d33635f8b13b899e56f8ace1c08ff39048a) you can see the very simple attempt, and also the test item that now fails.
Is this a sqlalchemy bug or is there a better way to do it?

Thank you

**Comment by youtux** [comment]
Oh and [this](https://github.com/paylogic/traduki/commit/0f9e7d33635f8b13b899e56f8ace1c08ff39048a) is the failure on CI.

**Comment by zzzeek** [comment]
hi there -

for events to propagate to subclasses you need to add the flag [propagate=True](https://docs.sqlalchemy.org/en/13/orm/events.html?highlight=propagate#sqlalchemy.orm.events.AttributeEvents.params.propagate)  .... hopefully this helps

**Comment by zzzeek** [comment]
I've improved the docstrings so that this implementation detail is easier to notice

**Comment by youtux** [comment]
Thanks for the answer! Unfortunately, this doesn't quite solve the issue.
The issue now is that my hook can receive `symbol('NO_VALUE')`, which was never the case before. This seems to be caused by the fact that `Dog.name.dispatch._active_history` is False, while it should be true.
Note that `Animal.name.dispatch._active_history` is True, so maybe `active_history=True` is not propageted correctly?
For reference, [this](https://github.com/paylogic/traduki/compare/master...b73c20b96e39822632357beeff17384d9e6d07e8) is the code with the suggested change, and [this](https://travis-ci.org/paylogic/traduki/builds/536144720) is the failed build for reference.

**Comment by zzzeek** [comment]
Hi -

Can you please provide an [MCVE](http://stackoverflow.com/help/mcve) so that I can further analyze what you are seeing?   thanks

**Comment by youtux** [comment]
I came up with this, I hope it will help:

```python
from sqlalchemy import Column, Integer, String, ForeignKey, create_engine, event
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

Base = declarative_base()


class Translation(Base):
    __tablename__ = 'translations'

    id = Column(Integer, primary_key=True, autoincrement=True)

    en = Column(String(255))
    nl = Column(String(255))
    fr = Column(String(255))


class BasePool(Base):
    __tablename__ = 'Pool'
    __mapper_args__ = {
        'polymorphic_on': 'type',
        'with_polymorphic': '*'
    }

    id = Column(Integer, primary_key=True, autoincrement=True)
    type = Column(String(255), nullable=False, index=True)

    name_id = Column(Integer, ForeignKey(Translation.id), nullable=True)
    name = relationship(Translation)


@event.listens_for(BasePool.name, 'set', retval=True, active_history=True, propagate=True)
def attr_set_hook(state, value, oldvalue, initiator):
    # I expect oldvalue here to be either a Translation or a None, but instead I get NEVER_SET
    assert isinstance(oldvalue, Translation) or oldvalue is None  # This breaks!
    # potential modification to oldvalue...
    if oldvalue is None:
        if isinstance(value, dict):
            return Translation(**value)
        return value
    else:
        # Modify inplace oldvalue
        oldvalue.en = value['en'] if isinstance(value, dict) else value.en
        oldvalue.fr = value['fr'] if isinstance(value, dict) else value.fr
        oldvalue.nl = value['nl'] if isinstance(value, dict) else value.nl
        return oldvalue


class SimplePool(BasePool):
    """Simple concrete class, needed just to show the behaviour"""
    __mapper_args__ = {'polymorphic_identity': 'simple'}


engine = create_engine('sqlite:///:memory:')
Base.metadata.create_all(engine)

session = sessionmaker(bind=engine)()

b = BasePool()
b.name = {'en': 'A simple pool', 'nl': 'A simple pool in Dutch'}  # This works

p = SimplePool()
p.name = {'en': 'A simple pool', 'nl': 'A simple pool in Dutch'}  # This triggers attr_set_hook, which breaks
```

**Comment by zzzeek** [comment]
I notice that the previous version of the code set "extension" upon the relationship, and as this extension contained the active_history flag, active_history would be applied to each instance of the relationship.      You can set active_history=True directly on the relationship which should solve this issue.   I will open a separate issue for the event-level active_history flag not working, and also why do we even have this flag.

**Comment by youtux** [comment]
I see, indeed if I now define the relationship with `active_history=True` keyword argument, it works as expected.

**Comment by zzzeek** [comment]
keep in mind I don't think it's safe for you to rely on "None" here, in #4696 I might be changing this.  None is not the same answer as you get with a column-oriented attribute and this makes no sense.  The correct answer IMO for the "old" value in your case above should be "NEVER_SET".     For future proofing you should likely be checking for NO_VALUE/NEVER_SET.

**Comment by youtux** [comment]
So if I understand correctly, once I upgrade to sqlalchemy 1.3.4 I should be able to have this working by just defining `active_history=True` on the `event.listen` rather than on the `relationship` itself, am I right?

**Comment by zzzeek** [comment]
that is correct.

however in 1.4 I might have this returning a value other than None if nothing was set.  the system right now seems very random.

**Comment by Bhargavishnu** [comment]
In my case i had used `propogate=True` changing it to `propagate` worked.
