### ISSUE TITLE
Column must be constructed with a non-blank name or assign a non-blank .name before adding to a Table

### ISSUE THREAD

**Issue by John-Male** [sqlalchemy/sqlalchemy#4692]
I am getting this error raised when I have table with two DateTime columns present 

I am running the code on Windows 10 Pro with Python 3.7.3, and SQLAlchemy 1.3.3

Here is the code that is being used 

**alchemy_base.py**
`import os
from sqlalchemy import create_engine, MetaData
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import scoped_session, sessionmaker
from api.core.config import SQLALCHEMY_DATABASE_URI

mlb_engine = create_engine(SQLALCHEMY_DATABASE_URI)
db_session = scoped_session(
    sessionmaker(autocommit=False, autoflush=False, bind=mlb_engine)
)

MLB_Session = sessionmaker(bind=mlb_engine,autocommit=False, autoflush=False)

meta = MetaData()
Base = declarative_base()`

**team_game_stats.py** code includes the SQL to create the table in the database

`from datetime import datetime
from sqlalchemy import Column, String, Integer, Date, Boolean, DateTime, Float
from api.database.db.alchemy_base import Base

class Team_Game_Stats(Base):
    \_\_tablename\_\_ = 'team_game_stats'
    StatID = Column(Integer, primary_key=True)
    TeamID = Column(Integer)
    SeasonType = Column(Integer)
    Season = Column(Integer)
    Name = Column(String(50))
    Team = Column(String(10))
    GlobalTeamID = Column(Integer)
    GameID = Column(Integer)
    OpponentID = Column(Integer)
    Opponent = Column(String(10))
    Day	= Column(Date)
    DateTime = Column(DateTime)
    HomeOrAway = Column(String(4))
    IsGameOver= Column(Boolean)
    GlobalGameID = Column(Integer)
    GlobalOpponentID = Column(Integer)
    Updated = Column(DateTime)
    Games = Column(Integer)
    FantasyPoints = Column(Float)
    AtBats = Column(Float)
    Runs = Column(Float)
    Hits = Column(Float)
    Singles = Column(Float)
    Doubles = Column(Float)
    Triples = Column(Float)
    HomeRuns = Column(Float)
    RunsBattedIn = Column(Float)
    BattingAverage = Column(Float)
    Outs = Column(Float)
    Strikeouts = Column(Float)
    Walks = Column(Float)
    HitByPitch = Column(Float)
    Sacrifices = Column(Float)
    SacrificeFlies = Column(Float)
    GroundIntoDoublePlay = Column(Float)
    StolenBases = Column(Float)
    CaughtStealing = Column(Float)
    PitchesSeen = Column(Float)
    OnBasePercentage = Column(Float)
    SluggingPercentage = Column(Float)
    OnBasePlusSlugging = Column(Float)
    Errors = Column(Float)
    Wins = Column(Float)
    Losses = Column(Float)
    Saves = Column(Float)
    InningsPitchedDecimal = Column(Float)
    TotalOutsPitched = Column(Float)
    InningsPitchedFull = Column(Float)
    InningsPitchedOuts = Column(Float)
    EarnedRunAverage = Column(Float)
    PitchingHits = Column(Float)
    PitchingRuns = Column(Float)
    PitchingEarnedRuns = Column(Float)
    PitchingWalks = Column(Float)
    PitchingStrikeouts = Column(Float)
    PitchingHomeRuns = Column(Float)
    PitchesThrown = Column(Float)
    PitchesThrownStrikes = Column(Float)
    WalksHitsPerInningsPitched = Column(Float)
    PitchingBattingAverageAgainst = Column(Float)
    GrandSlams = Column(Float)
    FantasyPointsFanDuel = Column(Float)
    FantasyPointsDraftKings = Column(Float)
    FantasyPointsYahoo = Column(Float)
    PlateAppearances = Column(Float)
    TotalBases = Column(Float)
    FlyOuts = Column(Float)
    GroundOuts = Column(Float)
    LineOuts = Column(Float)
    PopOuts = Column(Float)
    IntentionalWalks = Column(Float)
    ReachedOnError = Column(Float)
    BallsInPlay = Column(Float)
    BattingAverageOnBallsInPlay = Column(Float)
    WeightedOnBasePercentage = Column(Float)
    PitchingSingles = Column(Float)
    PitchingDoubles = Column(Float)
    PitchingTriples = Column(Float)
    PitchingGrandSlams = Column(Float)
    PitchingHitByPitch = Column(Float)
    PitchingSacrifices = Column(Float)
    PitchingSacrificeFlies = Column(Float)
    PitchingGroundIntoDoublePlay = Column(Float)
    PitchingCompleteGames = Column(Float)
    PitchingShutOuts = Column(Float)
    PitchingNoHitters = Column(Float)
    PitchingPerfectGames = Column(Float)
    PitchingPlateAppearances = Column(Float)
    PitchingTotalBases = Column(Float)
    PitchingFlyOuts = Column(Float)
    PitchingGroundOuts = Column(Float)
    PitchingLineOuts = Column(Float)
    PitchingPopOuts = Column(Float)
    PitchingIntentionalWalks = Column(Float)
    PitchingReachedOnError = Column(Float)
    PitchingCatchersInterference = Column(Float)
    PitchingBallsInPlay = Column(Float)
    PitchingOnBasePercentage = Column(Float)
    PitchingSluggingPercentage = Column(Float)
    PitchingOnBasePlusSlugging = Column(Float)
    PitchingStrikeoutsPerNineInnings = Column(Float)
    PitchingWalksPerNineInnings = Column(Float)
    PitchingBattingAverageOnBallsInPlay = Column(Float)
    PitchingWeightedOnBasePercentage = Column(Float)
    DoublePlays = Column(Float)
    PitchingDoublePlays = Column(Float)
    BattingOrderConfirmed = Column(Boolean)
    IsolatedPower = Column(Float)
    FieldingIndependentPitching = Column(Float)
    PitchingQualityStarts = Column(Float)
    PitchingInningStarted = Column(Integer)
    LeftOnBase = Column(Float)
    PitchingHolds = Column(Float)
    PitchingBlownSaves = Column(Float)
    SubstituteBattingOrder = Column(Integer)
    SubstituteBattingOrderSequence = Column(Integer)
    FantasyPointsFantasyDraft = Column(Float)

    def __init__(self,StatID):
        self.StatID = StatID

'''
  CREATE TABLE `team_game_stats` (
    `StatID` int(11) NOT NULL,
    `TeamID` int(11) DEFAULT NULL,
    `SeasonType` int(11) DEFAULT NULL,
    `Season` int(11) DEFAULT NULL,
    `Name` varchar(50) DEFAULT NULL,
    `Team` varchar(10) DEFAULT NULL,
    `GlobalTeamID`int(11) DEFAULT NULL,
    `GameID`int(11) DEFAULT NULL,
    `OpponentID`int(11) DEFAULT NULL,
    `Opponent` varchar(10) DEFAULT NULL,
    `Day` date DEFAULT NULL,
    `DateTime` datetime DEFAULT NULL,
    `HomeOrAway` varchar(4) DEFAULT NULL,
    `IsGameOver` boolean DEFAULT NULL,
    `GlobalGameID` int(11) DEFAULT NULL,
    `GlobalOpponentID` int(11) DEFAULT NULL,
    `Updated` datetime DEFAULT NULL,
    `Games`int(11) DEFAULT NULL,
    `FantasyPoints` decimal(10,3) DEFAULT NULL,
    `AtBats` decimal(10,3) DEFAULT NULL,
    `Runs` decimal(10,3) DEFAULT NULL,
    `Hits` decimal(10,3) DEFAULT NULL,
    `Singles` decimal(10,3) DEFAULT NULL,
    `Doubles` decimal(10,3) DEFAULT NULL,
    `Triples` decimal(10,3) DEFAULT NULL,
    `HomeRuns` decimal(10,3) DEFAULT NULL,
    `RunsBattedIn` decimal(10,3) DEFAULT NULL,
    `BattingAverage` decimal(10,3) DEFAULT NULL,
    `Outs` decimal(10,3) DEFAULT NULL,
    `Strikeouts` decimal(10,3) DEFAULT NULL,
    `Walks` decimal(10,3) DEFAULT NULL,
    `HitByPitch` decimal(10,3) DEFAULT NULL,
    `Sacrifices` decimal(10,3) DEFAULT NULL,
    `SacrificeFlies` decimal(10,3) DEFAULT NULL,
    `GroundIntoDoublePlay` decimal(10,3) DEFAULT NULL,
    `StolenBases` decimal(10,3) DEFAULT NULL,
    `CaughtStealing` decimal(10,3) DEFAULT NULL,
    `PitchesSeen` decimal(10,3) DEFAULT NULL,
    `OnBasePercentage` decimal(10,3) DEFAULT NULL,
    `SluggingPercentage` decimal(10,3) DEFAULT NULL,
    `OnBasePlusSlugging` decimal(10,3) DEFAULT NULL,
    `Errors` decimal(10,3) DEFAULT NULL,
    `Wins` decimal(10,3) DEFAULT NULL,
    `Losses` decimal(10,3) DEFAULT NULL,
    `Saves` decimal(10,3) DEFAULT NULL,
    `InningsPitchedDecimal` decimal(10,3) DEFAULT NULL,
    `TotalOutsPitched` decimal(10,3) DEFAULT NULL,
    `InningsPitchedFull` decimal(10,3) DEFAULT NULL,
    `InningsPitchedOuts` decimal(10,3) DEFAULT NULL,
    `EarnedRunAverage` decimal(10,3) DEFAULT NULL,
    `PitchingHits` decimal(10,3) DEFAULT NULL,
    `PitchingRuns` decimal(10,3) DEFAULT NULL,
    `PitchingEarnedRuns` decimal(10,3) DEFAULT NULL,
    `PitchingWalks` decimal(10,3) DEFAULT NULL,
    `PitchingStrikeouts` decimal(10,3) DEFAULT NULL,
    `PitchingHomeRuns` decimal(10,3) DEFAULT NULL,
    `PitchesThrown` decimal(10,3) DEFAULT NULL,
    `PitchesThrownStrikes` decimal(10,3) DEFAULT NULL,
    `WalksHitsPerInningsPitched` decimal(10,3) DEFAULT NULL,
    `PitchingBattingAverageAgainst` decimal(10,3) DEFAULT NULL,
    `GrandSlams` decimal(10,3) DEFAULT NULL,
    `FantasyPointsFanDuel` decimal(10,3) DEFAULT NULL,
    `FantasyPointsDraftKings` decimal(10,3) DEFAULT NULL,
    `FantasyPointsYahoo` decimal(10,3) DEFAULT NULL,
    `PlateAppearances` decimal(10,3) DEFAULT NULL,
    `TotalBases` decimal(10,3) DEFAULT NULL,
    `FlyOuts` decimal(10,3) DEFAULT NULL,
    `GroundOuts` decimal(10,3) DEFAULT NULL,
    `LineOuts` decimal(10,3) DEFAULT NULL,
    `PopOuts` decimal(10,3) DEFAULT NULL,
    `IntentionalWalks` decimal(10,3) DEFAULT NULL,
    `ReachedOnError` decimal(10,3) DEFAULT NULL,
    `BallsInPlay` decimal(10,3) DEFAULT NULL,
    `BattingAverageOnBallsInPlay` decimal(10,3) DEFAULT NULL,
    `WeightedOnBasePercentage` decimal(10,3) DEFAULT NULL,
    `PitchingSingles` decimal(10,3) DEFAULT NULL,
    `PitchingDoubles` decimal(10,3) DEFAULT NULL,
    `PitchingTriples` decimal(10,3) DEFAULT NULL,
    `PitchingGrandSlams` decimal(10,3) DEFAULT NULL,
    `PitchingHitByPitch` decimal(10,3) DEFAULT NULL,
    `PitchingSacrifices` decimal(10,3) DEFAULT NULL,
    `PitchingSacrificeFlies` decimal(10,3) DEFAULT NULL,
    `PitchingGroundIntoDoublePlay` decimal(10,3) DEFAULT NULL,
    `PitchingCompleteGames` decimal(10,3) DEFAULT NULL,
    `PitchingShutOuts` decimal(10,3) DEFAULT NULL,
    `PitchingNoHitters` decimal(10,3) DEFAULT NULL,
    `PitchingPerfectGames` decimal(10,3) DEFAULT NULL,
    `PitchingPlateAppearances` decimal(10,3) DEFAULT NULL,
    `PitchingTotalBases` decimal(10,3) DEFAULT NULL,
    `PitchingFlyOuts` decimal(10,3) DEFAULT NULL,
    `PitchingGroundOuts` decimal(10,3) DEFAULT NULL,
    `PitchingLineOuts` decimal(10,3) DEFAULT NULL,
    `PitchingPopOuts` decimal(10,3) DEFAULT NULL,
    `PitchingIntentionalWalks` decimal(10,3) DEFAULT NULL,
    `PitchingReachedOnError` decimal(10,3) DEFAULT NULL,
    `PitchingCatchersInterference` decimal(10,3) DEFAULT NULL,
    `PitchingBallsInPlay` decimal(10,3) DEFAULT NULL,
    `PitchingOnBasePercentage` decimal(10,3) DEFAULT NULL,
    `PitchingSluggingPercentage` decimal(10,3) DEFAULT NULL,
    `PitchingOnBasePlusSlugging` decimal(10,3) DEFAULT NULL,
    `PitchingStrikeoutsPerNineInnings` decimal(10,3) DEFAULT NULL,
    `PitchingWalksPerNineInnings` decimal(10,3) DEFAULT NULL,
    `PitchingBattingAverageOnBallsInPlay` decimal(10,3) DEFAULT NULL,
    `PitchingWeightedOnBasePercentage` decimal(10,3) DEFAULT NULL,
    `DoublePlays` decimal(10,3) DEFAULT NULL,
    `PitchingDoublePlays` decimal(10,3) DEFAULT NULL,
    `BattingOrderConfirmed` boolean DEFAULT NULL,
    `IsolatedPower` decimal(10,3) DEFAULT NULL,
    `FieldingIndependentPitching` decimal(10,3) DEFAULT NULL,
    `PitchingQualityStarts` decimal(10,3) DEFAULT NULL,
    `PitchingInningStarted`int(11) DEFAULT NULL,
    `LeftOnBase` decimal(10,3) DEFAULT NULL,
    `PitchingHolds` decimal(10,3) DEFAULT NULL,
    `PitchingBlownSaves` decimal(10,3) DEFAULT NULL,
    `SubstituteBattingOrder`int(11) DEFAULT NULL,
    `SubstituteBattingOrderSequence`int(11) DEFAULT NULL,
    `FantasyPointsFantasyDraft` decimal(10,3) DEFAULT NULL,
    PRIMARY KEY (`StatID`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
'''`
This code is used and raises the following error 

File "c:\saberdataapi\cron_jobs\get_team_game_stats.py", line 6, in <module>
    from api.database.models.team_game_stats import Team_Game_Stats as G_STATS
  File "C:\saberdataapi\api\database\models\team_game_stats.py", line 5, in <module>
    class Team_Game_Stats(Base):
  File "C:\saberdataapi\api\database\models\team_game_stats.py", line 23, in Team_Game_Stats
    Updated = Column(DateTime)
  File "C:\saberdataapi\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 1377, in __init__
    self._init_items(*args)
  File "C:\saberdataapi\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 107, in _init_items
    item._set_parent_with_dispatch(self)
  File "C:\saberdataapi\venv\lib\site-packages\sqlalchemy\sql\base.py", line 456, in _set_parent_with_dispatch
    self._set_parent(parent)
  File "C:\saberdataapi\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 1449, in _set_parent
    "Column must be constructed with a non-blank name or "
sqlalchemy.exc.ArgumentError: Column must be constructed with a non-blank name or assign a non-blank .name before adding to a Table.

I have tried renaming the Updated column and the same error is raised. I am wondering if there is a simple solution to get around this error other than creating a separate table to hold the Updated column. 

Any help is appreciated

John

**Comment by zzzeek** [comment]
you are redefining the Python variable name DateTime to be a Column object when it is intended to be a type object:

```
from sqlalchemy import Column
from sqlalchemy import DateTime  # <---- "DateTime" == SQLAlchemy type object
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    DateTime = Column(DateTime)   # <---- "DateTime" reassigned to Column object
    Updated= Column(DateTime)

```

you probably want to do it this way:

```
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = sa.Column(sa.Integer, primary_key=True)
    DateTime = Column(sa.DateTime)
    Updated= sa.Column(sa.DateTime)

```

**Comment by John-Male** [comment]
Thank you for your reply. I purchased a copy of Essential SQLAlchemy and it shows another way that would remove the problem which is to code the DateTime Column as 

`class User( Base):
    __tablename__ = 'users' 
   user_id = Column( Integer(), primary_key = True)
   username = Column( String( 15), nullable = False, unique = True) 
   email_address = Column( String( 255), nullable = False) 
   phone = Column( String( 20), nullable = False)  
   password = Column( String( 25), nullable = False) 
   created_on = Column( DateTime(), default = datetime.now) 
   updated_on = Column( DateTime(), default = datetime.now, onupdate = datetime.now)

**From Myers, Jason; Copeland, Rick. Essential SQLAlchemy: Mapping Python to Databases (Kindle Locations 2587-2608). O'Reilly Media. Kindle Edition. **
`
