### ISSUE TITLE
mssql/pyodbc w/freetds reflection fails when a column has a float dtype 

### ISSUE THREAD

**Issue by aberger91** [sqlalchemy/sqlalchemy#4693]
Hello

I know it's not recommended to use this configuration, but I was able to reflect mssql database tables using pyodbc bindings and freetds driver ONLY after modifying /dialects/mssql/base.py. 

Problem: 
In the "MSDialect.get_columns" method, scale and precision for floats are passed to coltype (FLOAT). This creates seemingly random errors during reflection, depending on if the reflected tables contain float datatypes in the schema: "coltype received unknown keyword argument: 'scale'".

The scale and precision are correctly skipped for MSREAL (the other approximate numeric datatype). I think it should be doing "if coltype is not MSREAL and coltype is not FLOAT", or something equivalent. 

Let me know if this is expected behavior and/or warrants a PR, and/or if I am just troubled and should move on. 

Thanks,
Andrew

**Comment by zzzeek** [comment]
hi there -

this looks like #4525 are you using the most recent SQLAlchemy available ?

**Comment by aberger91** [comment]
I'm using 1.3 (SQLAlchemy-1.3.0b2-py3.6-linux-x86_64.egg)

**Comment by zzzeek** [comment]
use the 1.3 that's on pypi, the ".z" in "x.y.z" for a release means it's only bug fixes.  always go for the latest

**Comment by aberger91** [comment]
Will do! Glad to hear it's not an issue anymore and thanks for the quick response
