### ISSUE TITLE
attribute events "old value" is fully inconsistent across active history / scalar non

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4696]
as documented in the fix for #4695, the current rules for the "old value" for attribute SET event on a transient object:

```
    # with active_history=False if old value is not present, for scalar we
    # return NO VALUE, for object we return NEVER SET
    # with active_history=True if old value is not present, for scalar we
    # return NEVER SET, for object we return None
    # so it is basically fully inconsistent across both directions.

```

This is crazy and needs to be fixed.    The fix has to be at the very least, "what is the difference between NO VALUE and NEVER SET" ?

guesses: 

*  "NO VALUE" means we don't know the answer.  "NEVER SET" means we *do* know the answer, that this value was never set.  so for a transient object it should always be NEVER SET, right?

* since active_history only applies to object loads, it should have no effect on this at all if there is nothing to load. so there should not be NO VALUE for transient objects period, right?

* but attributes don't know if we are transient or not?  do we need to start looking at the instancestate.key?   I vaguely recall there's another issue where we also might want to be looking at the instancestate's persistence state within the attribute system.

**Comment by zzzeek** [comment]
the related issue is #4640

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Unify NO_VALUE and NEVER_SET** https://gerrit.sqlalchemy.org/1281
