### ISSUE TITLE
Repeated insertions into sqlite database via sqlalchemy causing memory leak?

### ISSUE THREAD

**Issue by Santosh-Gupta** [sqlalchemy/sqlalchemy#4707]
When inserting a huge pandas dataframe of my data into sqlite via sqlalchemy and pandas `to_sql` with a specified chucksize, I would get memory errors. In google colab my enviroment would crash. 

At first I thought it was an issue with `to_sql` but I tried a workaround where instead of using chunksize I used `for i in range(100): df.iloc[i * 100000:(i+1):100000].to_sql(...)` and that still resulted in an error. 

It seems under certain conditions, that there is a memory leak with repeated insertions to sqlite via sqlalchemy.

I had a hard time trying to replicate the memory leak that occurred when converting my data, through a minimal example. But this gets pretty close. With my data, it would result in a memory crash no matter what I did. But when I tried to create a self-contained minimal example, I have to play around with parameters to cause the leak. 

The following code, when run in Google colab CPU mode, has a leak, although it's not severe enough to cause it to crash. 

```
import string
import numpy as np
import pandas as pd
from random import randint
import random

def make_random_str_array(size=10, num_rows=100, chars=string.ascii_uppercase + string.digits):
    return (np.random.choice(list(chars), num_rows*size)
            .view('|U{}'.format(size)))

def alt(size, num_rows):
    data = make_random_str_array(size, num_rows=2*num_rows).reshape(-1, 2)
    dfAll = pd.DataFrame(data)
    return dfAll

dfAll = alt(randint(1000, 2000), 10000)

for i in range(330):
    print('step ', i)
    data = alt(randint(1000, 2000), 10000)
    df = pd.DataFrame(data)
    dfAll = pd.concat([ df,  dfAll ])

import sqlalchemy

from sqlalchemy import create_engine
engine = sqlalchemy.create_engine('sqlite:///testtt.db')

for i in range(500):
    print('step', i)
    dfAll.iloc[(i%330)*10000:((i%330)+1)*10000].to_sql('test_table22', engine, index = False, if_exists= 'append')
```

This was run on Google Colab CPU enviroment. 

The database itself isn't causing the memory leak, because I can restart my enviroment, and the previously inserted data is still there, and connecting to that database doesn't cause an increase in memory. The issue seems to be under certain conditions, repeated insertions via looping `to_sql` or one `to_sql` with chucksize specified.

**Comment by zzzeek** [comment]
To be honest, this seems likely to be either in the SQLite driver or in pandas. SQLAlchemy is just in the middle, and I assume to_sql() doesn't use the ORM which is where memory use issues would usually occur. Have you tried emailing the pandas list to see if other people have had similar problems with to_sql() ? Have you tried running your crashing example in a regular Python command line ? (I don't know what google collab is).



On Sun, Jun 2, 2019, at 8:17 PM, Santosh Gupta wrote:
> When inserting a huge pandas dataframe of my data into sqlite via sqlalchemy and pandas `to_sql` with a specified chucksize, I would get memory errors. In google colab my enviroment would crash.

> At first I thought it was an issue with `to_sql` but I tried a workaround where instead of using chunksize I used `for i in range(100): df.iloc[i * 100000:(i+1):100000].to_sql(...)` and that still resulted in an error.

> It seems under certain conditions, that there is a memory leak with repeated insertions to sqlite via sqlalchemy.

> I had a hard time trying to replicate the memory leak that occurred when converting my data, through a minimal example. But this gets pretty close. With my data, it would result in a memory crash no matter what I did. But when I tried to create a self-contained minimal example, I have to play around with parameters to cause the leak.

> The following code, when run in Google colab CPU mode, has a leak, although it's not severe enough to cause it to crash.

> `import string
import numpy as np
import pandas as pd
from random import randint
import random

def make_random_str_array(size=10, num_rows=100, chars=string.ascii_uppercase + string.digits):
    return (np.random.choice(list(chars), num_rows*size)
            .view('|U{}'.format(size)))

def alt(size, num_rows):
    data = make_random_str_array(size, num_rows=2*num_rows).reshape(-1, 2)
    dfAll = pd.DataFrame(data)
    return dfAll

dfAll = alt(randint(1000, 2000), 10000)

for i in range(330):
    print('step ', i)
    data = alt(randint(1000, 2000), 10000)
    df = pd.DataFrame(data)
    dfAll = pd.concat([ df,  dfAll ])

import sqlalchemy

from sqlalchemy import create_engine
engine = sqlalchemy.create_engine('sqlite:///testtt.db')

for i in range(500):
    print('step', i)
    dfAll.iloc[(i%330)*10000:((i%330)+1)*10000].to_sql('test_table22', engine, index = False, if_exists= 'append')
`

**Comment by Santosh-Gupta** [comment]
I haven't tried emailing the Pandas list yet, I'll mention this. 

Google colab is a jupyter notebooks run over google's server for free. 
https://colab.research.google.com/

**Comment by Santosh-Gupta** [comment]
Turns out it's a Python issue

https://stackoverflow.com/questions/56418825/repeated-insertions-into-sqlite-database-via-sqlalchemy-causing-memory-leak/56511487?noredirect=1#comment99616175_56511487

**Comment by zzzeek** [comment]
yeah, that was what this appeared like.   pandas just creates buffers as large as what you are giving it and that's just Python not giving memory back, so it's not a "leak" in the standard sense.  glad someone amazingly took all the time to run your whole thing on the target platform and everything, you got lucky.

**Comment by Santosh-Gupta** [comment]
Thanks. With Colab, it would only take a few minutes to import, then select run -> runall. I highly encourage to check it out, it's very useful

https://colab.research.google.com/notebooks/welcome.ipynb#recent=true

**Comment by KirkHadley** [comment]
Just in case someone ends up here using a different db, I can confirm that this error also occurs with, at least, a MySQL DB using a SQLAlchemy connector. The fix (at least in our case) was to wrap the inner `to_sql` call in a function and then to call that function from inside the for loop. IIRC, this forces python to actually relinquish the memory.

**Comment by Santosh-Gupta** [comment]
> yeah, that was what this appeared like. pandas just creates buffers as large as what you are giving it and that's just Python not giving memory back, so it's not a "leak" in the standard sense. glad someone amazingly took all the time to run your whole thing on the target platform and everything, you got lucky.

Thanks. With colab everything is already set up, so all you have to do is hit run -> all. Highly encourage people to use it when discussing bugs to eliminate time spent on recreating the exact enviroment. 

> Just in case someone ends up here using a different db, I can confirm that this error also occurs with, at least, a MySQL DB using a SQLAlchemy connector. The fix (at least in our case) was to wrap the inner `to_sql` call in a function and then to call that function from inside the for loop. IIRC, this forces python to actually relinquish the memory.

Also pretty hacky, but then running that function in a process pretty much eliminates any chance for a leak.
