### ISSUE TITLE
Does SQLAlchemy allow for multiple order_by parameters when declaring a relationship?

### ISSUE THREAD

**Issue by tnelsonw** [sqlalchemy/sqlalchemy#4708]
When declaring a relationships, we want to order by multiple parameters. This seems to be possible on a query, but not on a relationship according to the documentation. For instance, is it possible to do something like this?
```
ports = relationship('scan.Port', back_populates='scan', order_by=(
        'scan.Port.param1',
        'scan.Port.param2',
        'scan.Port.param3'
    ))
```
This way we can order by more than one parameter if some rows have matching values for the first parameter, or second parameter, etc.

**Comment by zzzeek** [comment]
two ways:

```
ports = relationship('scan.Port', back_populates='scan', order_by=[
        scan.Port.param1,
        scan.Port.param2,
        scan.Port.param3
    ])

```
tuple or list is OK.   Then by string, specify the whole Python expression:

```
ports = relationship('scan.Port', back_populates='scan', 
  order_by="[scan.Port.param1, scan.Port.param2, scan.Port.param3]")

```

There's an FAQ entry about the same idea as applied to the more common "primaryjoin" case, same idea here though:

https://docs.sqlalchemy.org/en/13/faq/ormconfiguration.html#i-m-using-declarative-and-setting-primaryjoin-secondaryjoin-using-an-and-or-or-and-i-am-getting-an-error-message-about-foreign-keys

**Comment by zzzeek** [comment]
or you can use a lambda too if that helps:

```
ports = relationship('scan.Port', back_populates='scan', 
  order_by=lambda: [scan.Port.param1, scan.Port.param2, scan.Port.param3])

```

**Comment by tnelsonw** [comment]
Thanks
