### ISSUE TITLE
Add support for sqlite's INSERT ... ON CONFLICT ...

### ISSUE THREAD

**Issue by DrPyser** [sqlalchemy/sqlalchemy#4709]
https://sqlite.org/lang_UPSERT.html

SQLite recent versions ( since 3.24.0 (2018-06-04) ) supports upserts statements through the same syntax as postgresql, `INSERT ... ON CONFLICT ... DO ... `.

That would be a great addition to the sqlite dialect support.

Thanks for the great work!

**Comment by zzzeek** [comment]
yup, see #4010

**Comment by zzzeek** [comment]
closing this as this is a dupe of #4010

**Comment by DrPyser** [comment]
Oh, sorry, thought that was only for the "insert or replace" functionality.

**Comment by zzzeek** [comment]
geez, they have both, let me sort it out

**Comment by zzzeek** [comment]
when taht issue was created apparently SQLite didnt have ON CONFLICT yet.  but that is all anybody wants AFAIK.
