### ISSUE TITLE
evaluate RowProxy for ORM results ? (rename, genericize, etc)

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4710]
part of the 2.0 plan is that Core and ORM results will look much more the same, e.g. Core will get all(), first(), one() via an intermediary invocation object.  

let's see what it looks like for ORM to return the RowProxy instead of lightweight_named_tuple():

1. we need a new "parent" for RowProxy, so SimpleRowProxyParent(<list of names>) will do what ResultProxy does if you have a simple list of names.  I considered changing "parent" to be "key_fallback" or something but this object has a bunch of features including has_key, keys, etc.

2. the "processors" aspect of RowProxy would not be used for ORM because our "processors" are full-row processors, not per-key, and they have to be done up front (though I keep wondering if I'm not seeing something here on this).

3. items() / keys() / iterkeys() / iteritems() -> at the very least the "iter*" methods should not be there in a py3k context and we might want to fully py3k this (turn keys / items into iterators), and perhaps if py2k for now (in 1.4) we do the list version.  this should be py3k-ed a long time ago.  let's py3k / py2k-ize these for 1.4.

4. performance -> i have no idea which will be faster, the RowProxy obviously relies on C code for all the speed and in pure python it would not perform as well as the lightweightnamed tuple.  In C code, hopefully rowproxy is faster.  

5. welp, maybe Core uses lightweightproxy for all() / first() / one() if it really is better, if we go through this and see that's the case, consider flipping the whole issue around

6. Still not known is how existing ResultProxy.fetchall() / fetchmany() style methods will fit into the core version of things, perhaps the invocation object will have a "proxy()" method or something if someone really wants that...all() really should return a plain list.   the only functionality we need is fetchmany().   so maybe invocation object has chunks() ?    

the immediate tasks are:

1. make rowproxy work in the ORM for the lightweight keyed tuple, see what breaks

2. test the performance

**Comment by zzzeek** [comment]
if we make the invocation interface:

.all()
.first()
.one()
.chunks(<chunksize>)   -> returns an iterator of lists - does this also replace yield_per()? ooo!

maybe that really can be the full replacement for the public-facing aspect of ResultProxy.  but that's the 2.0 / 1.4future part of this.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use RowProxy for ORM keyed tuple** https://gerrit.sqlalchemy.org/1300

**Comment by zzzeek** [comment]
So the above gerrit is spawning into many different areas and I'll have to split it up.   deprecating the "column key fallback" thing is turning out to be a huge knot.   anyway, for here we have to decide between mapping / tuple, as RowProxy is a mapping. I think the mapping should be a separate accessor like row._mapping.   "row" acts like a tuple, e.g. `__contains__()` is looking at the values.  Note that I've modified RowProxy so that the processors are called just once up front.

in the above review, I have RowProxy.__contains__ acting like a mapping for Core and like a tuple for ORM, because it uses a different "metadata" object in each case that redefines the behavior.

problem is things like the Core Tutorial have shown the name / column access with getitem for years, we'd have to move that to be "row._mapping['name']", that might strike people as strange.     so for 1.4, I think we have _mapping available, but Core RowProxy is still a mapping, ORM RowProxy is a tuple, then in 2.0 we migrate RowProxy to being fully tuple all the time + _mapping.
