### ISSUE TITLE
LEFT INNER JOIN forced instead of LEFT JOIN when using Query API

### ISSUE THREAD

**Issue by Sturgelose** [sqlalchemy/sqlalchemy#4711]
**What am I doing**
With the following:

```
Base = automap_base()
engine = create_engine(f'mysql+pymysql://{USERNAME}:{PASSWORD}@{HOST}/{DB}')

Base.prepare(engine, reflect=True)
chain_id = 'DEMO'
user = Base.classes.User
acls = Base.classes.ACL
chain = Base.classes.Chain

// Simple context manager to create a session take from the docs
with session_scope() as session:
    session \
        .query(user.id, user.name, user.surname, user.email) \
        .join(chain, chain.ownerId == user.id) \
        .join(acls, acls.userId == user.id)\
        .filter(or_(chain.id == chain_id, acls.chainId == chain_id))\
        .all()
```
The objective is to do two independent joins and get the rows that either have a chain via the ACLs or via the Chain OwnerId. I'm aware I should be able to do two queries and merge them, but it's quite simplier if the DB does already this for me, plus I'm just replicating a query I did in an ORM in another language/framework and I'd like to keep the same logic to avoid problems.

**What do I get**
this produces the following query for mysql+pymsql:

```
SELECT 
`User`.id AS `User_id`, 
`User`.name AS `User_name`, 
`User`.surname AS `User_surname`, 
`User`.email AS `User_email` 
FROM `User` 
    INNER JOIN `Chain` ON `Chain`.`ownerId` = `User`.id 
    INNER JOIN `ACL` ON `ACL`.`userId` = `User`.id 
WHERE `Chain`.id = %(id_1)s OR `ACL`.`chainId` = %(chainId_1)s
// {'id_1': 'DEMO', 'chainId_1': 'DEMO'}
```

**What do I expect**
Note that the JOINS are INNER JOIN, and I'd need them to be simple LEFT JOINs. Neither INNER neither OUTER (or FULL, which is not supported in Mysql).
I've been taking my time to go through all the documentation but SQLAlchemy is still using the Inner keyword without being able to configure it.

I'm loading the models from the mapping of the schema of the database, which I hope is not affecting... If needed (later on) I could share the schema.

Any suggestion or pointer on how to make these JOINs as simple JOINs and not inner?

Thanks a lot!

**Comment by zzzeek** [comment]
hiya -

whats the difference between LEFT JOIN and LEFT OUTER JOIN ?

https://www.w3schools.com/sql/sql_join_left.asp

> Note: In some databases LEFT JOIN is called LEFT OUTER JOIN.

**Comment by zzzeek** [comment]
eg. I think you want to use outerjoin().

**Comment by Sturgelose** [comment]
Hi, well, I had already tried with outerjoin, but seems that for some reason the resulting query wasn't the proper one, and now running it again, it returned the expected one.

I had thought that in MySQL, the LEFT JOIN and LEFT OUTER JOIN wasn't equivalent, but seems it has been some human error from my side during the last 3 hours....

So, sorry for opening an issue when everything was fine! i guess until you don't open the issue, you don't discover your fault! :/ Hope I didn't make you loos much time!

**Comment by zzzeek** [comment]
there is no problem at all, feel free to ask questions anytime :)
