### ISSUE TITLE
pool_size not recognized when passed in database URL

### ISSUE THREAD

**Issue by archenroot** [sqlalchemy/sqlalchemy#4714]
I work with Optuna library where you have only option if I am not mistaken to pass db URL but no parameters.

https://optuna.readthedocs.io/en/latest/reference/study.html

Is it possible to make sqlalchemy to recognize all parameters from db url?

**Comment by archenroot** [comment]
Example of URL:
`params_db_file = 'postgresql://hyperparamdb:hyperparamdb@localhost/hyperparamdb?pool_size=200&pool_timeout=8000'`

**Comment by zzzeek** [comment]
hi there -

"pool_size" and "pool_timeout" are not part of the URL string, they are passed as keyword arguments to create_engine.  See https://docs.sqlalchemy.org/en/13/core/pooling.html#connection-pool-configuration.   The URL string only contains parameters that are consumed by the driver, i.e. the psycopg2 DBAPI in this case.

If you are using a library that doen't support these additional parameters then I would advise filing a bug with them.

**Comment by archenroot** [comment]
@zzzeek - thanks for confirmation. I opened ticket in optuna lib tracker.
