### ISSUE TITLE
Unable to update column to NULL within ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by nimcho** [sqlalchemy/sqlalchemy#4715]
The bug can be demonstrated on the following example:

```python
from sqlalchemy import Table, MetaData, Integer
from sqlalchemy.dialects import mysql

metadata = MetaData()

table = Table('table', metadata,
   Column('id', Integer, primary_key=True),
   Column('int_or_null', Integer, nullable=True),
)

def dump_sql(query):
    return str(query.compile(dialect=mysql.dialect()))

query = mysql.insert(table) \
    .on_duplicate_key_update(int_or_null=None)

print(dump_sql(query))
```

which generates an invalid SQL that subsequently fails to execute:

```sql
INSERT INTO `table` (id, int_or_null) 
VALUES (%s, %s) 
ON DUPLICATE KEY UPDATE 
```

The missing `int_or_null = %s` or `int_or_null = NULL` part is apparently being cut in the `visit_on_duplicate_key_update(...)` function:

https://github.com/sqlalchemy/sqlalchemy/blob/e2521b595ae8b5b4ca8147c5ee13e2fc0f597e63/lib/sqlalchemy/dialects/mysql/base.py#L1241-L1242

**Comment by sqla-tester** [comment]
**Lukas Banic** has proposed a fix for this issue in the **master** branch:

**Fix for: unable to set column to NULL within ON DUPLICATE KEY UPDATE** https://gerrit.sqlalchemy.org/1306

**Comment by sqla-tester** [comment]
**Lukas Banic** has proposed a fix for this issue in the **master** branch:

**Accommodate value of None for ON DUPLICATE KEY UPDATE** https://gerrit.sqlalchemy.org/1306

**Comment by sqla-tester** [comment]
**Lukas Banic** has proposed a fix for this issue in the **rel_1_3** branch:

**Accommodate value of None for ON DUPLICATE KEY UPDATE** https://gerrit.sqlalchemy.org/1307
