### ISSUE TITLE
Reflection of indexes in PostgreSQL doesn't include DESC / NULLS ordering.

### ISSUE THREAD

**Issue by eli-collins** [sqlalchemy/sqlalchemy#4717]
As of sqlalchemy 1.3.4, it looks like the Postgres dialect doesn't reflect the ASC/DESC or NULLS FIRST/LAST state of an index.   E.g.  `Index(col_a, col_b.desc())` is reflected back as `Index(col_a, col_b)`.

After diving into it a little, it looks like the query `PGDialect.get_indexes()` needs to pull the "ix.indoption" column as part of the query.  Per some references such as [this stackoverflow thread](https://stackoverflow.com/questions/18121103/how-to-get-the-index-column-orderasc-desc-nulls-first-from-postgresql),  ix.indoption appears to be a int2vector, where each integer is a mask corresponding to the columns/expressions in the index, where bit 0 indicates "DESC" and bit 1 indicates "NULLS FIRST".  

This seems poorly documented in postgres, and I hate to suggest hardcoding something so obscure; but short of rewriting the entire get_indexes() method to call and parse the output of `pg_get_indexdef()`, there doesn't seem to be much other way to get this information.

(I'm also not entirely clear how to pass this information back via get_indexes() to the reflection code. If this change seems reasonable, and someone can give me a pointer on that part, I'm willing to give a shot at making a patch for this).

**Comment by zzzeek** [comment]
you are correct that get_indexes() probably needs to be rewritten, however if we are going to rewrite it let me point out that it might be a good idea to pursue *all* unsupported PG index features including [covering indexes](https://github.com/sqlalchemy/sqlalchemy/issues/4458), [expression and partial indexes](https://github.com/sqlalchemy/sqlalchemy/blob/master/test/dialect/postgresql/test_reflection.py#L852), all of which aren't supported right now.

**Comment by zzzeek** [comment]
it seems reasonable though that we would be reading the ix.indoption flag in this case though, which is a simpler than reading expression / partial indexes.  We can actually apply desc() / nullsfirst() to the column object directly.  In the case of expression / partial indexes, we'd have to parse SQL, which we aren't going to do, we'd return these expressions as text().   

So in this case I say read ix.indoption and add an additional field to the inspector.get_indexes() dictionary within the "dialect_options" entry.   for full reflection of Index we would need to add new dialect level hooks into reflection.py so that the Postgresql dialect can intercept these options and return modified Column objects for idx_cols, that is [here](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/reflection.py#L903)

**Comment by eli-collins** [comment]
Thanks!  I'll try and work up a PR sometime this week for ix.indoption.

---

Re: expression indexes... I'd actually just explored what it would take to support expression indexes, since needed that feature myself.  I ended up writing a very hacked method that parses pg_get_indexdef()'s output... but it's parser is way too fragile to be suitable for general use.  

The only other approach I could find was to render pg_get_expr(ix.indexprs) -- but ix.indexprs contains ALL the expressions lumped into a nodetree, and pg_get_expr() doesn't offer a way to render only one element of the nodetree.  Which meant I was back to parsing sql output, ala pg_get_indexdef().  If postgres ever adds an "offset/index" argument to pg_get_expr(), I might be able to give reflecting ix.indexprs and ix.indpred support a shot.

**Comment by eli-collins** [comment]
I've got an initial draft of this working (still needs unittests).  However, outside of the PGDialect.get_indexes() changes, the rest of it looks pretty generic.  The dialect_options keyword that I'm passing through has a format like:

    postgresql_column_sorting={
         "col_a": dict(desc=True), 
         "col_b": dict(nullsfirst=True),
    } 

Looking at the code I've got, I think if it were made into a toplevel "column_sorting" keyword in the get_indexes() dictionary, the code to process it could be integrated cleanly into `Inspector._reflect_indexes()` with minimal changes, rather than having to introduce some new reflection hooks and indirection.  The code just calls `col.asc()`, `col.desc()`, etc; and seems very database-agnostic, allowing it to be reused if other dialects's inspectors need the same feature.

Let me know if that sounds better, or if you'd like to stay with the "postgresql_column_sorting" approach!

**Comment by sqla-tester** [comment]
**Eli Collins** has proposed a fix for this issue in the **master** branch:

**PostgreSQL now reflects per-column sort order on indexes.** https://gerrit.sqlalchemy.org/1310

**Comment by sqla-tester** [comment]
**Eli Collins** has proposed a fix for this issue in the **rel_1_3** branch:

**PostgreSQL now reflects per-column sort order on indexes.** https://gerrit.sqlalchemy.org/1318

**Comment by zzzeek** [comment]
I changed the datastructure to be just a tuple of keywords.    people are pushing me for a release of other things as usual so trying to get this included.

**Comment by eli-collins** [comment]
Sounds great!  Having it as a dict was probably over-engineering on my part - I wasn't sure if there'd be a need for future sorting-related keywords with a non-boolean value.  But I can't actually think of anything (at least as far as postgresq's index spec goes).
