### ISSUE TITLE
deprecate query.instances()

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4719]
there's no reason for this method to exist, it is a use case I made up back in 0.1 that has never been a thing.    in particular it's making it quite difficult to get around the "name lookup" problem I'm dealing with for #4718, however the whole thing was from before we had Query and definitely has no place in 2.0.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use RowProxy for ORM keyed tuple** https://gerrit.sqlalchemy.org/1300

**Comment by zzzeek** [comment]
clarification, query.instances() with no context given.  the with-context use case is still needed for horizontal sharding.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Deprecate textual column matching in Row** https://gerrit.sqlalchemy.org/1486
