### ISSUE TITLE
Wiki Update: Use functools.wraps on UniqueObject recipe

### ISSUE THREAD

**Issue by rdeaton** [sqlalchemy/sqlalchemy#4720]
On the wiki:
https://github.com/sqlalchemy/sqlalchemy/wiki/UniqueObject#implicit-constructor-and-scoped-session

To be friendly for usage, this example would be better if it included `from functools import wraps` and
```python
@wraps(cls)
def decorate(f):
```

**Comment by zzzeek** [comment]
the wiki is now open for all users to edit.  please update accordingly and close, thanks!

**Comment by rdeaton** [comment]
Thanks! Done.
