### ISSUE TITLE
Microsoft Sql Server "\Instance/Dababase"

### ISSUE THREAD

**Issue by dedalus2000** [sqlalchemy/sqlalchemy#4726]
For the first time I have to use sqlalchemy with Microsoft Sql Server.
I don't know this sql server very well: the administrator create an "instance" and, inside it, the database.

No sqlalchemy example exist for this configuration (I couldn't find any), but after many attemps I have found the correct uri:
r"mssql+pymssql://user:name@host\instancename/dbname"

The implicit port is 1433, but tunneling it I found some rounting problem (or sqlalchemy problem?) and I had to explicity it in the uri:
r"mssql+pymssql://user:name@host:1433\instancename/dbname"

This last one is not accepted by sqlalchemy.create_engine
It seems that "port" must ends with "/", url.make_url(uri) truncate the string just after the port.

**Comment by zzzeek** [comment]
hi there -

I believe "\instancename" modifies the hostname, not the port, so the URL would be:

r"mssql+pymssql://user:name@host\instancename:1433/dbname"

http://pymssql.org/en/stable/pymssql_examples.html#connecting-using-windows-authentication

if pymssql doesn't accept the windows host / port together then we'd need to find some other way to get pymssql to connect.   You'd likely have better results using pyodbc.

**Comment by dedalus2000** [comment]
It doesn't work.: the make_url function return the entire uri, but I the engine.DefaultDialect.connect receive ad dict with arguments {'host': 'host\instancename:1433', 'password': u'xx', 'user': 'yyy', 'database':'zzz'}

It seems to me that the port is considered as part of the host name.

```
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 411, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "src/pymssql.pyx", line 645, in pymssql.connect
sqlalchemy.exc.InterfaceError: (pymssql.InterfaceError) Connection to the database failed for an unknown reason. (Background on this error at: http://sqlalche.me/e/rvf5)
```

I'm going to switch to pyodbc, though I can continue with pymssql due a different routing settings (via iptables; I don't use the ssh-tunnel anymore, but a vpn with an entire ip class routing).

So, for me, this is not a problem anymore, but I can do tests if they can help you to improve sqlalchemy with mssql.

**Comment by zzzeek** [comment]
the only thing I'd need to know is if pymssql can connect at all in the way you were looking for.

is the connection accepted if you do this?

```
import pymssql
pymssql.connect(host="host:1433\instancename", database=.., user=..., password=...)
```

to support that we'd need to add additional query arguments to the URL and then document that a special way of connecting is required.

**Comment by zzzeek** [comment]
this will work, can you try this?  `"mssql+pymssql://user:name@/dbname?host=host:1433\instancename"`

```
>>> u = url.make_url("mssql+pymssql://user:name@/dbname?host=host:1433\instancename")
>>> from sqlalchemy.dialects.mssql import pymssql
>>> d = pymssql.dialect()
>>> d.create_connect_args(u)
[[], {'database': 'dbname', 'user': 'user', 'password': 'name', 'host': 'host:1433\\instancename'}]


```

**Comment by dedalus2000** [comment]
No, it doesn't

hosturi = r"""mssql+pymssql://{name}:{password}@
/{dbname}?host={host}:1433\{instance}""".format(
    name = config['mssql']["name"],
    password = config['mssql']["password"],
    host = config['mssql']["host"],
    instance = config['mssql']["instance"],
    dbname = config['mssql']["dbname"]
)

u = url.make_url(hosturi)
d = pymssql.dialect()
print d.create_connect_args(u)
#=> [[], {'host': 'hostip:1433\\instancename', 'password': u'password',
'user': 'user', 'database': 'dbname'}]

engine = create_engine(hosturi)
engine.execute('select 1')

The error is generated by the "execute":

sqlalchemy.exc.OperationalError: (pymssql.OperationalError) (18456, "Login
failed for user 'user'.DB-Lib error message 20018, severity 14:\nGeneral
SQL Server error: Check messages from the SQL Server\nDB-Lib error message
20002, severity 9:\nAdaptive Server connection failed
(hostip:1433\\instancename)\n") (Background on this error at:
http://sqlalche.me/e/e3q8)
e

Il giorno lun 17 giu 2019 alle ore 18:00 mike bayer <
notifications@github.com> ha scritto:

**Comment by zzzeek** [comment]
that means it connected just the login failed.

**Comment by dedalus2000** [comment]
it makes sense, but if I change the template string it works fine:
from
hosturi = r"""mssql+pymssql://{name}:{password}@
/{dbname}?host={host}:1433\{instance}""".format(
to the current one:
hosturi = r"""mssql+pymssql://{name}:{password}@
{host}\{instance}/{dbname}""".format(

So username and password is the same, I have no chances to pass the wrong
credentials

I tested again: your new uri without port works fine
hosturi = r"""mssql+pymssql://{name}:{password}@
/{dbname}?host={host}\{instance}""".format(

The port seems right, it is the standard one, and something is is
responding to telnet

If I set an unexistend port the error is what I'm expecting from that port
hosturi = r"""mssql+pymssql://{name}:{password}@
/{dbname}?host={host}:9999\{instance}""".format(

 (pymssql.OperationalError) (20009, 'DB-Lib error message 20009, severity
9:\nUnable to connect: Adaptive Server is u
navailable or does not exist (host:9999\\instance)\nNet-Lib error during
Connection refused (111)\n') (Background on this error at: htt
p://sqlalche.me/e/e3q8)

Other connection errors appears if I set a unexisted host or instance.

So If I explicity set the standard port it doesn't work (only with an
"instance"?), but it seems to me it uses and interpretes it.


Il giorno ven 21 giu 2019 alle ore 23:07 mike bayer <
notifications@github.com> ha scritto:

**Comment by zzzeek** [comment]
please get it to work with pymssql directly, if that can't do it, then there's nothing to support here:

http://www.pymssql.org/en/stable/

**Comment by zzzeek** [comment]
this is likely an issue on the pymssql side and special windows calling conventions are better suited towards use with the ODBC drivers as the reporter has done here.

**Comment by SkoZombie** [comment]
I was able to connect to a named MSSQL instance with the following connection string:
'mssql+pymssql://user:password@ip\\instance/db'

Versions:
SQLAlchemy==1.3.16
pymssql==2.1.4

**Comment by sumedh10** [comment]
@SkoZombie Did you have any success when including the port number along with a named instance? 

@zzzeek Not sure I understand the resolution here. I am facing the same problem where specifying both an instance and port leads to an error.

 

```python
import pymssql

# This works:
conn = pymssql.connect(
    host=host\instance,
    user=domain\username,
    password=password,
    database=database, 
    port = 1433
)
```

However, this doesn't work

```python
# This doesn't work 
conn = pymssql.connect(
    host=host:1433\instance,
    user=domain\username,
    password=password,
    database=database,
)
```

Error: 
```text
OperationalError: (pymssql.OperationalError) (20009, b'DB-Lib error message 20009, severity 9:
\nUnable to connect: Adaptive Server is unavailable or does not exist (database)
\nNet-Lib error during Connection refused (61)\nDB-Lib error message 20009, severity 9:
\nUnable to connect: Adaptive Server is unavailable or does not exist (database)
\nNet-Lib error during Connection refused (61)\n')
```

As for SQLAlchemy: 

```python
# This fails
create_engine(f'mssql+pymssql://{domain\username}:{password}@{host}\{instance}:1433/{database}') 
```
Error: 
```text
OperationalError: (pymssql.OperationalError) (20009, b'DB-Lib error message 20009, severity 9:
\nUnable to connect: Adaptive Server is unavailable or does not exist (database\instance)\n')
```

```python
# This fails
create_engine(f'mssql+pymssql://{domain\username}:{password}@/{database}?host={host}:1433\{instance}') 
```
Error: 
```text
OperationalError: (pymssql.OperationalError) (20009, b'DB-Lib error message 20009, severity 9:
\nUnable to connect: Adaptive Server is unavailable or does not exist (database)
\nNet-Lib error during Connection refused (61)\nDB-Lib error message 20009, severity 9:
\nUnable to connect: Adaptive Server is unavailable or does not exist (database)
\nNet-Lib error during Connection refused (61)\n')
```

**Comment by zzzeek** [comment]
> 
> Now that `pymssql` is no longer abandoned, hoping that this will get some attention since the installation process for `pymssql` is way simpler compared to `pyodbc`.

it's not?   OK, so perhaps they can allow "host=host:1433\instance" to work or otherwise someone can send SQLAlchemy a PR once it's known how pymssql supports this.  

pymssql is not in our current CI as it was unreliable and had different behavior when manually built vs. run against one of their binaries and i was unable to get any support for that.

**Comment by sumedh10** [comment]
After a quick look at the [source code](https://github.com/pymssql/pymssql/blob/master/src/_mssql.pyx#L664), I believe `pymmsql` simply ignores the port if instance is specified. 

I was under the assumption that for non-default ports, both instance and port would be required for a connection, which it turns out, is wrong. I can simply provide the host and instance, and the connection is established.

**Comment by deeTEEcee** [comment]
I was speaking to a coworker about this and he said that it's possible that you can only specify an instance name OR port, not both at the same time.

**Comment by carlosmontoyamoya** [comment]
Hi everyone,

As @SkoZombie mentioned on May 27, 2020, this is the correct way to establish a connection in SQL Server when using an instance name. We encountered this issue last week and resolved it using the following approaches.

**Connection with an Instance Name:**
The following code demonstrates how to configure a connection to SQL Server when an instance name is required. Update the parameters (username, password, host, instance, port, database) with your actual connection details:

```
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError
import logging

# Configuración del logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def test_connection():
    try:
        # Connection parameters
        # change the following parameters with your parameters.
        username = "username"
        password = "password"
        host = "10.123.123.12"
        instance = "INSTANCE_NAME"
        port = "1433"
        database = "DBNAME"

        # Build the connection string with the instance included in the host
        connection_string = (
            f"mssql+pymssql://{username}:{password}@{host}\\{instance}/{database}"
        )

        # SQLAlchemy engine creation
        engine = create_engine(connection_string, echo=True)

        # Test connection.
        with engine.connect() as connection:
            # Query execution with SQLAlchemy 2.x
            result = connection.execute(text("SELECT @@version"))
            for row in result:
                print(f"Result: {row[0]}")

        logger.info("Successful connection to database.")

    except SQLAlchemyError as e:
        logger.error(f"Error connecting to database: {e}")
    except Exception as e:
        logger.error(f"Unexpected error: {e}")

if __name__ == "__main__":
    test_connection()

```

**Connection Without an Instance Name:**
If your SQL Server configuration does not require an instance name, you can use the following code. Update the config dictionary with your connection details:

```
from sqlalchemy import create_engine, text

def test_connection():
    # Connection parameters
    # change the following parameters with your parameters.
    config = {
        "username": "username",
        "password": "password",
        "host": "10.123.123.12",
        "port": "1433",
        "dbname": "DBNAME"
    }

    # Connection URI
    connection_uri = f"mssql+pymssql://{config['username']}:{config['password']}@{config['host']}:{config['port']}/{config['dbname']}"

    try:
        # SQLAlchemy engine creation
        engine = create_engine(connection_uri, echo=True)

        # Test connection.
        with engine.connect() as connection:
            # Query execution with SQLAlchemy 2.x
            result = connection.execute(text("SELECT @@version"))
            for row in result:
                print(f"Result: {row[0]}")

        print("Successful connection to database.")

    except Exception as e:
        print(f"Error connecting to database: {e}")

if __name__ == "__main__":
    test_connection()
```
These examples should help you establish a connection to SQL Server using SQLAlchemy, whether or not your setup requires an instance name. Make sure to replace the placeholder values with your actual database credentials.

If you encounter any issues, feel free to ask for help.
