### ISSUE TITLE
it will random sort the order of mapped class' __dict__

### ISSUE THREAD

**Issue by NewUserHa** [sqlalchemy/sqlalchemy#4728]
I have a data class:
```
class machine:
  def __init__(...):
    ...

  @property
   ...
```

sqlalchemy:(already know id will autoincreament by blowcode.)
```
engine = sqlalchemy.create_engine("sqlite:///asyncippool.db")
metadata = sqlalchemy.MetaData(bind=engine)
table = sqlalchemy.Table('machine', metadata, sqlalchemy.Column('id', sqlalchemy.Integer, primary_key=True),
                         *(sqlalchemy.Column(_, sqlalchemy.Text()) for _ in machine().admin_sql))
metadata.create_all()
sqlalchemy.orm.mapper(machine, table)
session = sqlalchemy.orm.Session(engine)
hosts = [_.__dict__ for _ in session.query(machine).all()]
(_.pop('_sa_instance_state') for _ in hosts)
```

as you know, in python(maybe >3.6), dict is ordered by its insert ordered.
```
session.add(machine(..=..))
session.commit()
```
will break the order but my script need use that features. so I have to make a new object for inserting and avoding `'_sa_instance_state'` for now

could you consider fix it?

other questions:
  sqlalchemy cant return raw content of rows since I'm using classic mapping, so it doesn't have `._asdict()` method. the solution may be `.execute('select * from ...')` but I doubt it is named tuple.
  the '_sa_instance_state' is too annoying to let you use `.__dict__` way.
  sqlalchemy may lack the backup features that the standard library has

thanks!

**Comment by zzzeek** [comment]
> I have a data class:
> 
> ```
> class machine:
>   def __init__(...):
>     ...
> 
>   @property
>    ...
> ```
> 
> sqlalchemy:(already know id will autoincreament by blowcode.)
> 
> ```
> engine = sqlalchemy.create_engine("sqlite:///asyncippool.db")
> metadata = sqlalchemy.MetaData(bind=engine)
> table = sqlalchemy.Table('machine', metadata, sqlalchemy.Column('id', sqlalchemy.Integer, primary_key=True),
>                          *(sqlalchemy.Column(_, sqlalchemy.Text()) for _ in machine().admin_sql))
> metadata.create_all()
> sqlalchemy.orm.mapper(machine, table)
> session = sqlalchemy.orm.Session(engine)
> hosts = [_.__dict__ for _ in session.query(machine).all()]
> (_.pop('_sa_instance_state') for _ in hosts)
> ```
> 
> as you know, in python(maybe >3.6), dict is ordered by its insert ordered.
> 
> ```
> session.add(machine(..=..))
> session.commit()
> ```
> 
> will break the order but my script need use that features. so I have to make a new object for inserting and avoding `'_sa_instance_state'` for now
> 
> could you consider fix it?

Hi there -

You should not use `__dict__` with the SQLAlchemy ORM, and relying upon the insert ordering of the object itself is not supported.    Loading of objects indicates the object was newly constructed from the database, and the `__dict__` will actually be populated in the order in which the columns are SELECTed.  

If you need the attributes to be in a certain order, you can iterate them like table columns:
```

class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    x = Column(String)
    y = Column(String)
    z = Column(String)


a1 = A()
a1.y = 'y'
a1.x = 'x'
a1.z = 'z'

from sqlalchemy import inspect
for attr in inspect(a1).mapper.column_attrs:
    print(getattr(a1, attr.key))
```

or sorted by key, or something like that.   I don't know why you would need "insert ordering", but if you can tell me what you *actually* need to do such that attribute insert ordering is important, that would help.   If you need the attributes in the *same* order each time, then insert ordering is a bad idea, you should use the ordering of the table columns or something else that is declared explicitly in your application.

> other questions:
> sqlalchemy cant return raw content of rows since I'm using classic mapping, 

it can if you select from the table, `session.execute(table.select()).fetchall()`, or if you use the columns in your query, `session.query(machine.x, machine.y, machine..)`, that's the "raw" content of the row

> so it doesn't have `._asdict()` method. the solution may be `.execute('select * from ...')` but I doubt it is named tuple.
> the '_sa_instance_state' is too annoying to let you use `.__dict__` way.

an _asdict() method on your objects is very simple:

```

from sqlalchemy import inspect

class HasAsDict:
    def _asdict(self):
        return {
            key: getattr(self, key)
            for key in inspect(self).mapper.column_attrs.keys()
        }

```

dictionary will be identically ordered every time

**Comment by NewUserHa** [comment]
I'm using the ordering behavior of the dict with jinja2 template to save time for showing the content on page.

---<br />
>the __dict__ will actually be populated in the order in which the columns are SELECTed.

  `session.query(machine).first()` the `id` column/key isn't the first in the dict.

---<br />
the classic mapping will not make the mapped `machine` class able to `machine.query..` and `.as_dict()`.(if I remember correctly). is it right? because the document says:
>fully interchangeable. Both systems ultimately create the same configuration

---<br />
>session.query(machine.x, machine.y, machine..)

>from sqlalchemy import inspect
for attr in inspect(a1).mapper.column_attrs:
    print(getattr(a1, attr.key))

I'm new to sqlalchemy. shouldn't ORM make life easier? I feel raw sql with `row_factory` way is much simpler and straighter than it.

---<br />

can consider 1st an enhancement?
is the 2nd a bug?
can consider 3rd a document enhancement?

**Comment by zzzeek** [comment]
> ---
> 
> I'm using the ordering behavior of the dict with jinja2 template to save time for showing the content on page.

that doesn't tell me anything. do you need *deterministic* order only?  I've showed you how to get that.

> 
> ---
> 
> > the **dict** will actually be populated in the order in which the columns are SELECTed.
> 
> `session.query(machine).first()` the `id` column/key isn't the first in the returned obj's `.__dict__`.

OK, whatever is going on, I can't guarantee the order of `__dict__` being populated anyway.


> 
> ---
> 
> the classic mapping will not make the mapped `machine` class able to `machine.query..` and `.as_dict()`.(if I remember correctly). is it right? because the document says:
> 
> > fully interchangeable. Both systems ultimately create the same configuration

I assume that's referring to classical mapper() and declarative base, and it is true these create the same configuration, however with declarative the order of the columns added to Table might not affected if you are using mixins.   

> 
> ---
> 
> > session.query(machine.x, machine.y, machine..)
> 
> > from sqlalchemy import inspect
> > for attr in inspect(a1).mapper.column_attrs:
> > print(getattr(a1, attr.key))
> 
> I'm new to sqlalchemy. shouldn't ORM make life easier? 

the SQLAlchemy ORM makes life *very* easy in my opinion and in the opinion of many others.    There are a lot of ORMs available and if the subject area is new to you I would encourage you to try many of them, as they have different focuses.   I would be surprised if any of them make promises about the ordering of `__dict__`, however.

> I feel raw sql with `row_factory` way is much simpler and straighter than it.

You should always use the tools that work best for you and which you feel most comfortable with.   There was obviously some reason you felt you wanted to try other things so perhaps the tool you were using also had some shortcomings, this is the nature of using software libraries.


> 
> ---
> 
> can consider 1st an enhancement?

Unfortunately preserving `__dict__` order would be a very complicating requirement to meet and there is no demand for this feature, additionally there are other ways to solve your problem.

> is the 2nd a bug?
> can consider 3rd a document enhancement?

I'm not able to follow what #2 and #3 are, I'm sorry I need to you be more clear in what you are requesting.

**Comment by NewUserHa** [comment]
thanks.
indeed:
>There was obviously some reason you felt you wanted to try other things so perhaps the tool you were using also had some shortcomings

deterministic? I guess yes. `
```
        {%-for __ in _.values()-%}
        <td>{{__}}</td>
        {%-endfor-%}
        <td>
```

#2 was the "the dict will actually be populated in the order in which the columns are SELECTed.", but the dict isn't the order in which the columns are selected.

#3 is "classical mapper() and declarative base". `classical mapped class` lack some methods than `declarative base class`

**Comment by zzzeek** [comment]
> thanks.
> indeed:
> 
> > There was obviously some reason you felt you wanted to try other things so perhaps the tool you were using also had some shortcomings
> 
> deterministic? I guess yes. `
> 
> ```
>         {%-for __ in _.values()-%}
>         <td>{{__}}</td>
>         {%-endfor-%}
>         <td>
> ```

see `HasAsDict` solution in my first comment


> 
> #2 was the "the dict will actually be populated in the order in which the columns are SELECTed.", but the dict isn't the order in which the columns are selected.

not possible, sorry

> 
> #3 is "classical mapper() and declarative base". `classical mapped class` lack some methods than `declarative base class`

the mapper() call is to be replaced with a new function that works on top of Declarative in 2.0.   You can use this function now:

```
from sqlalchemy.ext.declarative import base
def declarative_mapper():
    _decl_class_registry = {}

    def quote_unquote_mapper(cls, table, properties={}):
        cls.__table__ = table
        cls._decl_class_registry = _decl_class_registry
        for key, value in properties.items():
            setattr(cls, key, value)
        base._as_declarative(cls, cls.__name__, cls.__dict__)

    return quote_unquote_mapper

# mapper here is the mapper() function
mapper = declarative_mapper()
```

**Comment by NewUserHa** [comment]
thanks.
there's a situation that I have a data structure(data class) and need to use SQL database.
if don't use sqlalchemy, I have to maintain to keep both the data class and the SQL statements the same.
if use sqlalchemy, I still have to create a class for mapping. 
  In classical mapping, there could be only one definition for the data structure except sqlalchemy will add a '_sa_instance_state' making I have to use some workaround method mentioned above.
  In declarative mapping, I have to create two definitions for the data structure:
```
class a:
  id = Column(...)
  ...
  def __init__(self, id=.., ...):
  self.id = ..
```
thus can not only edit one place to work for all.

I searched for days.
I think this is a pretty common situation. Is there any solution with sqlalchemy?
if there is, then it should be documented.
thank you for your patient!

**Comment by zzzeek** [comment]
if i understand correctly you are referring to the __init__() constructor method having to be defined to match the attributes.     Declarative already includes this __init__() constructor when you use declarative.   https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/basic_use.html#class-constructor  so there's no need to repeat yourself

**Comment by NewUserHa** [comment]
strange, I remembered once declarative base's __init__() didn't work.

ok, then 
every instance created from a class inherits from declarative_base() will be added a '_sa_instance_state' and some other things.
I know the `_sa_instance_state` thing is for tracking, and modify that instance's attribute then commit() can change records in the database directly. how can I be sure whether the one stored in my data structure if save to modify without affecting the database records since they are referencing?(and dont impact on performance) and it will throw errors if I del the '_sa_instance_state' for safe.
I didn't find docs about this.

for that order issue: the instance's ordered only except use `session.add()` against it. maybe it's not hard to fix?

**Comment by zzzeek** [comment]
OK now it sounds like you want to delete _sa_instance_state from dict.  I would say don't do that, and there is no need to do that.     If you absolutely have to iterate `__dict__`, just omit any keys that start with an underscore.

now I have to also point out that there *is* a whole plugin system that we added a long time ago, which nobody uses, that can completely redefine how all of this works, that is, if you wanted to put _sa_instance_state somewhere else, like in a weakkeydictionary, that is possible.   that system is at https://docs.sqlalchemy.org/en/13/orm/extensions/instrumentation.html and there is also an example of it.    But I think this is a very risky and complicated way of doing things.  

your original use case, that you are trying to print the keys from your object in a flask template, is very simple and there is no need to get into all of this in order to do that.    Again, please use or adapt my HasADict recipe given above.

**Comment by NewUserHa** [comment]
ok got it.

the last thing is how do users know when `_sa_instance_state` work to avoid commit() directly to the database.
there's no documentation for that.
do I think too much?

**Comment by zzzeek** [comment]
_sa_instance_state is accessible via

from sqlalchemy import inspect
state = inspect(my_object)

The InstanceState object is documented at:

https://docs.sqlalchemy.org/en/13/orm/internals.html#sqlalchemy.orm.state.InstanceState

elements of .attrs:

https://docs.sqlalchemy.org/en/13/orm/internals.html#sqlalchemy.orm.state.AttributeState

**Comment by NewUserHa** [comment]
I have read links you commented.
I want to be sure that sqlalchemy will commit() the modified object's attributes as long as it's in sqlalchemy's track system(eg. it's from queried or added to a session), even without using `session.query(..).filter(..).update({'..':'..'})`? because I didn't read about it in related documents.

**Comment by zzzeek** [comment]
that's how the session works, whatever you change gets flushed within the transaction

did you run through https://docs.sqlalchemy.org/en/13/orm/tutorial.html#adding-and-updating-objects ?

**Comment by NewUserHa** [comment]
ok got it!

excuse me, not totally. I find sqlalchemy should make life easier for dealing with common logic

the whole tutorial is really some long to a non-native speaker like me, I feel, and maybe to a person who already has some knowledge
thus I opened this issue ask if there could be a FAQ or Quickstart for this kind simple and fuzzy questions.

Thanks for your reply and patient!

**Comment by zzzeek** [comment]
I can appreciate that the docs are unfortunately not translated to other languages however I welcome efforts to do so, there have been a few folks who have volunteered to work on this however I've not gotten any complete contribution which I can add to the site.   If you google around there are a few translations of the docs around depending on what your native language is.

Beyond that I think most things discussed here are already documented, for the general topic of "serialization" there is no simple answer, everyone's use case is different, see https://stackoverflow.com/questions/5022066/how-to-serialize-sqlalchemy-result-to-json for how varied it can be.  There are also third party libraries to help with this task but this subject area is out of scope for what SQLAlchemy can / should provide directly since there is not a straightforward feature here.

**Comment by NewUserHa** [comment]
I found
```
class i:
   ...
memory=..
for i in toadd:
    a=i(...)
   memory[..] = a
   session.add(a)
   session.commit()
   session.refresh(a)
```
will only make all items in memory from a without anyvalues except the last item.

would you like to check if this is an issue?
