### ISSUE TITLE
all_orm_descriptors is including __mapper__

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4729]
the check is looking for `InspectionAttr` and not verifying that it's a descriptor

```
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import inspect

Base = declarative_base()


class HasAsDict:
    def _asdict(self):
        return {
            key: getattr(self, key)
            for key in inspect(self).mapper.all_orm_descriptors.keys()
        }


class A(HasAsDict, Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    x = Column(String)
    y = Column(String)
    z = Column(String)


a1 = A()
a1.y = "y"
a1.x = "x"
a1.z = "z"

print(a1._asdict())

```

`{'__mapper__': <Mapper at 0x7fd7a6abb9e8; A>, 'id': None, 'y': 'y', 'z': 'z', 'x': 'x'}
`

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Consult is_attrbute flag to determine descriptor; enable for assoc proxy** https://gerrit.sqlalchemy.org/1314

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Consult is_attrbute flag to determine descriptor; enable for assoc proxy** https://gerrit.sqlalchemy.org/1315
