### ISSUE TITLE
literal_column against quoted_name does not respsect quoting flag

### ISSUE THREAD

**Issue by villebro** [sqlalchemy/sqlalchemy#4730]
When constructing a sorted query with a limit on Oracle, the outer query should conditionally quote the alias from the inner query. This doesn't seem to happen if the expression is equal to the label. Example below:
```python
import sqlalchemy as sa
from sqlalchemy.dialects import oracle
from sqlalchemy.sql import literal_column, quoted_name, select, table


col = literal_column('SUM(ABC)').label(quoted_name('SUM(ABC)', True))
tbl = table('my_table')
query = select([col]).select_from(tbl).order_by(col).limit(100)

sql = str(query.compile(dialect=oracle.dialect(), compile_kwargs={'literal_binds': True}))
print(sql)
```
This yields
```sql
SELECT SUM(ABC) 
FROM (SELECT SUM(ABC) AS "SUM(ABC)" 
FROM my_table ORDER BY SUM(ABC)) 
WHERE ROWNUM <= 100
```
However, when the label isn't equal to the expression, the outer query is correctly quoted:
```python
col = literal_column('SUM(ABC)').label(quoted_name('SUM(ABC)_', True))
```
yields
```sql
SELECT "SUM(ABC)_" 
FROM (SELECT SUM(ABC) AS "SUM(ABC)_" 
FROM my_table ORDER BY SUM(ABC)) 
WHERE ROWNUM <= 100
```
Tested on version 1.3.4.

**Comment by zzzeek** [comment]
hi there -

that's certainly some subtle edge case you've found.    there is apparently a string comparison that is not taking the "quotiness" into account.

**Comment by zzzeek** [comment]
agnostic case, quoting on the order by vs. selected label reverse so it is broken in both cases
```

import sqlalchemy as sa
from sqlalchemy.sql import literal_column, quoted_name, select, table

col = literal_column('SUM(ABC)').label(quoted_name('SUM(ABC)', True))
tbl = table('my_table')

query = select([col]).select_from(tbl).alias().select().order_by(col)
print(query)


col = literal_column('SUM(ABC)').label(quoted_name('SUM(ABC)_', True))
tbl = table('my_table')

query = select([col]).select_from(tbl).alias().select().order_by(col)
print(query)

```

```
# wrong
SELECT anon_1.SUM(ABC) 
FROM (SELECT SUM(ABC) AS "SUM(ABC)" 
FROM my_table) AS anon_1 ORDER BY "SUM(ABC)"

# also wrong
SELECT anon_1."SUM(ABC)_" 
FROM (SELECT SUM(ABC) AS "SUM(ABC)_" 
FROM my_table) AS anon_1 ORDER BY SUM(ABC)

the label and order by should both be the label and both quoted

```

**Comment by zzzeek** [comment]
OK here's the bug:
```

from sqlalchemy import *
from sqlalchemy.sql.elements import quoted_name

col = literal_column(quoted_name("some_column", quote=True))

print(col)
```

**Comment by zzzeek** [comment]
does not quote the output because it assumes "literal".   the labeled column here is a literal_column so gets exported as that inside of Label._make_proxy().

**Comment by zzzeek** [comment]
still a second bug with the order_by label targeting

**Comment by zzzeek** [comment]
the patch for issue 1 is

```
@@ -850,7 +852,7 @@ class SQLCompiler(Compiled):
                 name, orig_name, (column, name, column.key), column.type
             )
 
-        if is_literal:
+        if is_literal and getattr(name, "quote", None) is None:
             name = self.escape_literal_column(name)
         else:
             name = self.preparer.quote(name)

```

this needs to be broken into two tickets once I identfiy the other issue

reporter: clearly your workaround for now is to not use a label name that requires quoting, there is no need for that

**Comment by villebro** [comment]
Thanks for picking this up so quickly. This query was generated programmatically, and is in fact the default behavior in the application in question, i.e. the label defaults to the expression if left undefined. There are simple workarounds that I can do to avoid this, but obviously the preferred solution is to make everything work out of the box. If I can be of any assistance please let me know.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Turn off the is_literal flag when proxying literal_column() to Label** https://gerrit.sqlalchemy.org/1316

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Turn off the is_literal flag when proxying literal_column() to Label** https://gerrit.sqlalchemy.org/1317

**Comment by zzzeek** [comment]
at the moment I consider everything to be stemming from one behavior regarding how literal_column() propagates on the outside of a subquery as a label, should resolve this.

**Comment by villebro** [comment]
I read through the test cases, looks very comprehensive and should solve all our problems 👍 Any ETA for next 1.3 release?

**Comment by zzzeek** [comment]
releases are around every three to four weeks or when the changelog queue is full. 1.3.5 is released
