### ISSUE TITLE
Give more details in LookupError message

### ISSUE THREAD

**Issue by lambdanis** [sqlalchemy/sqlalchemy#4733]
`LookupError` raised in `Enum` methods has the following message:
```'LookupError: "%s" is not among the defined enum values' % elem```

For easier debugging I think it would be helpful to include the enum name and possible values in the error message.

I'm happy to implement it if it sounds plausible.

**Comment by zzzeek** [comment]
note that enums don't need to have names unless they are Postgresql specific, however adding the name to the message if one is available should be fine.   

As far as possible values, this is also a good idea, but for it to be robust it would need to be implemented so as not to create an error message that is too long - assume some people have enums with 500 names in them and/or names that are hundreds of characters long.         There is a class that is used for this task within the realm of bound parameter sets at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/util.py#L463, this is more complicated than what's needed here, a new helper function _repr_tuple_names() can be added to util/langhelpers.py that will list out the string entries of a given tuple using ellipses for more than four values, as well as use ellipses for very long names:

```
'foo', 'bar','bat',  ... 'hoho'
'foo', 'bar', 'someverylongnametha...', .., 'hoho'

```

**Comment by RamonWill** [comment]
Hey @zzzeek ,

I'll be happy to help on this. I believe I have a resolution and will put a PR through sometime this week. 

I will also need to amend the messages in the [existing tests](https://github.com/sqlalchemy/sqlalchemy/blob/master/test/sql/test_types.py#L1442) to accommodate this change as well as create some additional tests.

Kind Regards,
Ramon

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **master** branch:

**resolution for issue 4733** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2123

**Comment by sqla-tester** [comment]
**RamonWill** has proposed a fix for this issue in the **rel_1_3** branch:

**error message for Lookup** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2155
