### ISSUE TITLE
Global filter for all ORM properties

### ISSUE THREAD

**Issue by mrquokka** [sqlalchemy/sqlalchemy#4735]
According this 
https://stackoverflow.com/questions/39852366/apply-a-global-filter-to-all-tables-for-every-query-in-sqlalchemy
Can i write someplace code

```
import sqlalchemy
from base import UUID, Base


class RootClass_(Base):
  __tablename__ = "rootclass_"
  mRID = sqlalchemy.Column(UUID, server_default=sqlalchemy.text(
      "uuid_generate_v4()"), primary_key=True)
  polymorphic_type = sqlalchemy.Column(sqlalchemy.types.String)
  name = sqlalchemy.Column(sqlalchemy.types.String)
  __mapper_args__ = {
      'polymorphic_identity': __tablename__,
      'polymorphic_on': polymorphic_type
  }


class CommonLanguage(RootClass_):
  __tablename__ = "commonlanguage"
  mRID = sqlalchemy.Column(
      UUID, sqlalchemy.ForeignKey(RootClass_.mRID),
      primary_key=True)
  __mapper_args__ = {
      "polymorphic_identity": __tablename__,
      "inherit_condition": mRID == RootClass_.mRID
  }


class CommonBase(RootClass_):
  __tablename__ = "commonbase"
  mRID = sqlalchemy.Column(
      UUID, sqlalchemy.ForeignKey(RootClass_.mRID),
      primary_key=True)
  __mapper_args__ = {
      "polymorphic_identity": __tablename__,
      "inherit_condition": mRID == RootClass_.mRID
  }


class CommonDescription(RootClass_):
  __tablename__ = "commondescription"
  mRID = sqlalchemy.Column(
      UUID, sqlalchemy.ForeignKey(RootClass_.mRID),
      primary_key=True)
  __mapper_args__ = {
      "polymorphic_identity": __tablename__,
      "inherit_condition": mRID == RootClass_.mRID
  }


CommonDescription.describedobject_mRID = sqlalchemy.Column(
    UUID, sqlalchemy. ForeignKey("commonbase.mRID"), nullable=False)
CommonDescription.DescribedObject = sqlalchemy.orm.relationship(
    CommonBase,
    foreign_keys=CommonDescription.describedobject_mRID,
    uselist=False,
    backref=sqlalchemy.orm.backref("Descriptions", uselist=True)
)
CommonDescription.language_mRID = sqlalchemy.Column(
    UUID, sqlalchemy. ForeignKey("commonlanguage.mRID"), nullable=False)
CommonDescription.Language = sqlalchemy.orm.relationship(
    CommonLanguage,
    foreign_keys=CommonDescription.language_mRID,
    uselist=False,
    backref=sqlalchemy.orm.backref("Descriptions", uselist=True)
)

global_language = CommonLanguage(name='test_lang')


#@some_orm_decorator
def my_super_property(current_instance, query):
  cls = current_instance.__class__
  if isinstance(current_instance, CommonDescription):
    return query.filter(cls.Language == global_language)
  else:
    return query


```

**Comment by zzzeek** [comment]
hi there -

I don't think I really understand what's being asked.     code looks fine to me feel free to use it.   note the "global filter" recipe now uses an event hook, see https://github.com/sqlalchemy/sqlalchemy/wiki/FilteredQuery .

I would assume you tried some code and something didn't work.   Please share a fully runnable example as well as the error and stack trace you are receiving, thanks.

**Comment by mrquokka** [comment]
> hi there -
> 
> I don't think I really understand what's being asked. code looks fine to me feel free to use it. note the "global filter" recipe now uses an event hook, see https://github.com/sqlalchemy/sqlalchemy/wiki/FilteredQuery .
> 
> I would assume you tried some code and something didn't work. Please share a fully runnable example as well as the error and stack trace you are receiving, thanks.

May be it will help, but how to reject load without error?
On examples, how to return None instead of raise TypeError(
            "private object %s was loaded, did you use "
            "joined eager loading?" % obj)

**Comment by mrquokka** [comment]
> hi there -
> 
> I don't think I really understand what's being asked. code looks fine to me feel free to use it. note the "global filter" recipe now uses an event hook, see https://github.com/sqlalchemy/sqlalchemy/wiki/FilteredQuery .
> 
> I would assume you tried some code and something didn't work. Please share a fully runnable example as well as the error and stack trace you are receiving, thanks.

Thanks, that is awesome

**Comment by zzzeek** [comment]
awesome means you're hopefully all set for now but feel free to reopen!
