### ISSUE TITLE
add FROM linter as an extension / option of some kind

### ISSUE THREAD

**Issue by youtux** [sqlalchemy/sqlalchemy#4737]
Hello, given the following base:

```
class Bar(Base):
    __tablename__ = 'bars'
    id = Column(Integer, primary_key=True)

class Foo(Base):
    __tablename__ = 'foos'

    id = Column(Integer, primary_key=True)

    bar_id = Column(Integer, ForeignKey(Bar.id))
    bar = relationship(Foo, backref='bar')
```

I wonder why sqlalchemy allows this kind of ORM queries to be executed:
```
session.query(Foo).filter(Bar.id == 42)
```
that results in the execution of this SQL:
```
SELECT foos.id AS foos_id, foos.bar_id AS foos_bar_id
FROM foos, bars
WHERE bars.id = ?
```

This is way more often a mistake than what the developer originally intended. I am asking this question because it is quite easy to add a filter condition to a model that was not originally joined, effectively voiding the filter condition:
```
session.query(Foo).join(Foo.bar).filter(Bar.id==42)  # Good query
session.query(Foo).filter(Bar.id==42)  # Oops, I forgot to join Foo.bar.
```
In the above example, the second query will fetch all the `Foo`s from the database. This is both a very slow operation and it also return unwanted records. Maybe it should raise instead?

EDIT: Fixed the last example

**Comment by youtux** [comment]
Of course it is possible to avoid the mistake in the first place by writing it the query like this:
```
session.query(Foo).filter(Foo.bar.has(Bar.id==42)).all()
```

**Comment by zzzeek** [comment]
there's a linter that can check for this condition, which I've just pulled out of my gists and added to the wiki:

https://github.com/sqlalchemy/sqlalchemy/wiki/FromLinter

as you might notice, it is fairly performance intensive so I'm not comfortable adding this in and turning it on by default.  at most it would be some kind of option or extension of some kind.  anyway, just drop that code in anywhere and you'll get a warning for any SELECT that doesn't join its FROMs.

**Comment by youtux** [comment]
Oh nice! I think it would be nice to have it as a configuration option for sqlalchemy. I think it would be useful to turn it for test-suite runs, and turn it off in production.

**Comment by youtux** [comment]
Also, in the example you linked I think you should always return `compiler.visit_select(element, **kw)`, but there is a `return` statement that returns None at the beginning of the function.
It makes queries like `select([42])` fail, since there is no `from` statement.

**Comment by zzzeek** [comment]
if you'd like to spend some time turning this into sqlalchemy.ext.linter , or something like that, which includes the tests in a test suite test/ext/test_linter, we can include it in a future release.    This would be a first step towards it becoming just a keyword flag or something, or maybe someone just does this:

    from sqlalchemy.ext.linter import lint_froms
    lint_froms()

The same recipe can also be applied using an engine event too, if for example it wants to attach to before_execute(), the SQL construct is there as well so it could be per engine.

**Comment by zzzeek** [comment]
> Also, in the example you linked I think you should always return `compiler.visit_select(element, **kw)`, but there is a `return` statement that returns None at the beginning of the function.
> It makes queries like `select([42])` fail, since there is no `from` statement.

I've made this change.

**Comment by youtux** [comment]
I'll look into that!

**Comment by youtux** [comment]
So I am finally trying to get this functionality in a `sqlalchemy.ext.linter` module, but I am having some troubles with testing. Specifically, I would like to know if there is a specific (possibly small) test module that I should take as example, since I am not used to the unittest-style (I never used anything else besides pytest).

**Comment by zzzeek** [comment]
we have our own fixtures in any case but they use things like setup methods, most of the teardown is automatic, did you try looking at something super simple like https://github.com/sqlalchemy/sqlalchemy/blob/master/test/ext/test_indexable.py#L21?  that is literally just, class + test method, nothing unittest/pytest is really involved

**Comment by zzzeek** [comment]
for class level setup hooks a test like https://github.com/sqlalchemy/sqlalchemy/blob/master/test/ext/test_hybrid.py#L538 has more than what you'd need for this...

pytest.org is down?

**Comment by youtux** [comment]
that's exactly what I was looking at then :). I am now trying using the `fixtures.TablesTest` base class, it should be enough for now.

And yes, pytest.org seems to be down.

**Comment by youtux** [comment]
I just pushed a very rough (but working) version of it. You can find it [here](https://github.com/youtux/sqlalchemy/tree/cartesian-product-linter).
I will probably continue in the next days, but some early feedback would be appreciated!

**Comment by zzzeek** [comment]
looks off to a great start!  

is there a reason it's not working as a compile hook?     as a compile hook you only need to test turning the queries into strings, you wouldn't need to execute them on a database in the tests.

**Comment by youtux** [comment]
The thing is that I couldn’t find a good way to “uninstall” the function without uninstalling all the other sql compilers, so there will be no way for the user to temporarily disable it, or otherwise enable it on a temporary basis. It is possible to do so with engine events instead.

**Comment by zzzeek** [comment]
OK that's a good point, what I would do for now is to maybe test it only against specific "Select" objects.   Overall, I think the linter part should be available as a function that can be plugged in using either approach, as well as I can just say, "lint(my_select)", it then probably raises a custom exception if the statement doesnt lint.

that is, make it a function that can be used in many ways, like in test suites, etc.

**Comment by youtux** [comment]
It is already like that, the only thing is that it warns instead of raising, but that can be fixed either in the userland by configuring the interpreter to raise for specific warning or in the library by having another argument in the signature to describe the behavior to be used in case of “problems”.

**Comment by sqla-tester** [comment]
**Alessio Bogon** has proposed a fix for this issue in the **master** branch:

**Query linter extension** https://gerrit.sqlalchemy.org/1461

**Comment by sqla-tester** [comment]
**Alessio Bogon** has proposed a fix for this issue in the **master** branch:

**Query linter option** https://gerrit.sqlalchemy.org/1664

**Comment by sqla-tester** [comment]
**Alessio Bogon** has proposed a fix for this issue in the **master** branch:

**Query linter option** https://gerrit.sqlalchemy.org/1664

**Comment by pellejacobs** [comment]
> It is already like that, the only thing is that it warns instead of raising, but that can be fixed either in the userland by configuring the interpreter to raise for specific warning or in the library by having another argument in the signature to describe the behavior to be used in case of “problems”.

@youtux The default behaviour that's been merged seems to be the warning, which has been great! Would you have any suggestions on how we could easily expand on that to raise an error instead?

**Comment by CaselIT** [comment]
python allows control of how warnings are handled: https://docs.python.org/3/library/warnings.html

You can turn a warning to an error fairly easily by adding a warning filter, something like the following should do it `"error:SELECT statement has a cartesian product:sqlalchemy.exc.SAWarning"`
