### ISSUE TITLE
create_engine work not as expected

### ISSUE THREAD

**Issue by SimonCrios** [sqlalchemy/sqlalchemy#4738]
# The URL function to analyze url seems not work as expected.

The URL I used: **postgresql://MolDB:MolDB123@127.0.0.2:5432/MolDB**
Error Log:
>Traceback (most recent call last):
  File "/home/crios/soft/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/crios/soft/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "MolDB/__main__.py", line 56, in <module>
    ENGINE = create_engine(uri(SETTING))  # type: Engine
  File "/home/crios/soft/conda/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/crios/soft/conda/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/home/crios/soft/conda/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/crios/soft/conda/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 288, in _parse_rfc1738_args
    return URL(name, **components)
  File "/home/crios/soft/conda/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 71, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: ':5432'

And then I went to engine/url.py and print all attribute of url.__init__.

Finally I got this:
input:
>self.drivername = drivername
 print(drivername)
        self.username = username
        print(username)
        print(username)
        self.password_original = password
        print(password)
        self.host = host
        print(host)
        if port is not None:
            print(port)
            self.port = int(port)
        else:
            self.port = None
        self.database = database
        print(database)
        self.query = query or {}
        print(query)

output:
>postgresql
MolDB
:MolDB123@
127.0.0.2
:5432

And I use this code bug fixed:
>    def __init__(
        self,
        drivername,
        username=None,
        password=None,
        host=None,
        port=None,
        database=None,
        query=None,
    ):
        self.drivername = drivername
        print(drivername)
        self.username = username
        print(username)
        self.password_original = password[1:-1]
        print(password)
        self.host = host
        print(host)
        if port is not None:
            print(port)
            self.port = int(port[1:])
        else:
            self.port = None
        self.database = database
        print(database)
        self.query = query or {}
        print(query)

**Comment by zzzeek** [comment]
hi there -

I can't reproduce your issue.  Are you using a very old version of SQLAlchemy, and/or have you modified parts of it ahead of time?   the URL as given is very standard and the port is parsed correctly:

```
Python 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlalchemy.engine import url
>>> u = url.make_url("postgresql://MolDB:MolDB123@127.0.0.2:5432/MolDB")
>>> u.port
5432
>>> int(u.port)
5432
>>> u.host
'127.0.0.2'
```

**Comment by SimonCrios** [comment]
I'm confused as well. I just reinstall SQLAlchemy and try it again.
>$ pip install sqlalchemy
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting sqlalchemy
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/62/3c/9dda60fd99dbdcbc6312c799a3ec9a261f95bc12f2874a35818f04db2dd9/SQLAlchemy-1.3.5.tar.gz (5.9MB)
     |████████████████████████████████| 5.9MB 3.1MB/s 
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Stored in directory: /home/crios/.cache/pip/wheels/25/68/79/fd446a3b1de37fda063ddbdd97329e0193bed0aae66b28a32f
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-1.3.5

Bug still ocurred. Maybe the version of my channel should be blamed?

**Comment by zzzeek** [comment]
what is:

`uri(SETTING)`

is that returning a plain string or some custom variant ?

**Comment by SimonCrios** [comment]
ummm.
The uri function is to generate uri and I print it's result. In this condition, the result is postgresql://MolDB:MolDB123@127.0.0.2:5432/MolDB

And I've tried your codes. It works as expected.

**Comment by SimonCrios** [comment]
The uri function is like below:
![image](https://user-images.githubusercontent.com/33002742/60067873-ec50de00-973e-11e9-9cc7-e36c9478743d.png)

**Comment by SimonCrios** [comment]
def uri(setting: dict) -> str:
    '''Create URI for SQLAlchemy Engine'''
    setting = setting['db']
    for i in ('type', 'driver', 'user',
              'passwd', 'host', 'port', 'db'):
        if i not in setting.keys():
            setting[i] = ''
    for i in setting.keys():
        setting[i] = str(setting[i]).lstrip().rstrip()
    if setting['driver'] != '':
        setting['driver'] = '+' + setting['driver']
    if setting['passwd'] != '':
        setting['passwd'] = ':' + uri_trans(setting['passwd'])
    if setting['host'] != '':
        setting['host'] = '@' + setting['host']
    if setting['port'] != '':
        setting['port'] = ':' + setting['port']
    uri = ('{type}{driver}://{user}{passwd}{host}{port}/{db}'
           ).format(**setting)
    return uri

**Comment by SimonCrios** [comment]
from urllib.parse import quote_plus as uri_trans
