### ISSUE TITLE
Docs: session.rollback() and session.close()

### ISSUE THREAD

**Issue by millerdev** [sqlalchemy/sqlalchemy#4740]
The [session documentation](https://docs.sqlalchemy.org/en/13/orm/session_basics.html#when-do-i-construct-a-session-when-do-i-commit-it-and-when-do-i-close-it) has this code snippet:
```py
@contextmanager
def session_scope():
    """Provide a transactional scope around a series of operations."""
    session = Session()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()
```
Could that be shortened to this while retaining the same functional behavior?
```py
@contextmanager
def session_scope():
    """Provide a transactional scope around a series of operations."""
    session = Session()
    try:
        yield session
        session.commit()
    finally:
        session.close()
```
In other words, can the `session.rollback()` on exception be omitted if it will finally be followed by `session.close()`, which is [documented to "[end] any transaction in progress"](https://docs.sqlalchemy.org/en/13/orm/session_api.html#sqlalchemy.orm.session.Session.close)? Does "[end] any transaction in progress" mean the same thing as _rollback any transaction in progress_?

**Comment by zzzeek** [comment]
So every connection ultimately has a "rollback" invoked on it when it gets back to the connection pool, assuming default behaviors for the pool (leading us to the first reason Session.rollback() may be required, in case someone has [changed those defaults](https://docs.sqlalchemy.org/en/13/core/pooling.html?highlight=reset_on_return#sqlalchemy.pool.Pool.params.reset_on_return )), however Session.rollback() has a lot of other things that happen that people may (or may not) be using, most importantly [event hooks](https://docs.sqlalchemy.org/en/13/orm/events.html?highlight=session%20rollback#sqlalchemy.orm.events.SessionEvents.after_soft_rollback) that are listening for a "rollback()" at the Session level, as well as all of the [object-level bookkeeping](https://docs.sqlalchemy.org/en/13/orm/session_events.html#deleted-to-persistent) which occurs and also may be important to an application.

in the example you cite, applications might want to do more within the "except" hook such as logging or similar, and they might want to not actually do the .close(), so it's important that this pretty important logical step be illustrated, even though in some cases, e.g. an application is using the default rollback-on-return strategy, and is not relying on any event hooks, and is guaranteed to fully discard all objects after the .close(), it isn't technically necessary.

**Comment by millerdev** [comment]
Cool, thanks for the detailed explanation.
