### ISSUE TITLE
MySQL TIMESTAMP nullable logic not correctly implemented for TypeDecorator

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4743]
eg. using a type like:

```
class TimezoneAwareTimestamp(types.TypeDecorator):
    """Ensure tz-aware timestamp are returned."""

    impl = TIMESTAMP

    def process_result_value(self, value, dialect):
        if not value:
            return None
        return value.replace(tzinfo=pytz.UTC)


```

it likely doesn't work for variant either, need to be going off of "impl" and need to add tests.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Unwrap TIMESTAMP when doing an isinstance()** https://gerrit.sqlalchemy.org/1329

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Unwrap TIMESTAMP when doing an isinstance()** https://gerrit.sqlalchemy.org/1330
