### ISSUE TITLE
Pythonic way of temporarily pausing event listeners

### ISSUE THREAD

**Issue by Peter92** [sqlalchemy/sqlalchemy#4746]
For the record, I'm not expecting this to get implemented, but it's potentially worth thinking about as a QOL feature. I've done something similar for signals in my Qt window wrapper and it's proved quite useful. If you're not interested at all just close this, just thought it wouldn't hurt suggesting.

I was looking at how to pause an event so that I could edit the "updated" timestamp without the update event firing.  The syntax I ended up with was this:

    event.remove(Model, 'before_update', model_update)
    try:
        #run code
    finally:
        event.listen(Model, 'before_update', model_update)

I was thinking a context manager could be useful in cases like this, where it'll basically run the above code but behind the scenes:

    with event.pause(Model, 'before_update', model_update):
        #run code

The issue of this would arise when attempting to pause multiple events. To get around that, an optional group could be provided (though from what I gathered from a quick look, it's probably not possible):

    @event.listens_for(Model, 'before_update', group='model_event')
    def on_update(*args): ....

    event.listens(Model2, 'before_insert', on_insert, group='model_event')

    with event.pause('model_event'):
        #run code

Did a quick test and it worked fine when adding this to `sqlalchemy/event/api.py`:

    @contextmanager
    def pause(target, identifier, fn):
        remove(target, identifier, fn)
        try:
            yield
        finally:
            listen(target, identifier, fn)

**Comment by zzzeek** [comment]
hiya -

I would not use remove() since it is an expensive operation and is also not very threadsafe.   I would instead build a decorator on your end that simply doesn't fire the event when a parameter is set.     demo below

```
from sqlalchemy import create_engine
from sqlalchemy import event
import contextlib


class pausable:
    def __init__(self, groupname):
        self.groupname = groupname
        self.paused = False

    @contextlib.contextmanager
    def pause(self):
        self.paused = True
        yield
        self.paused = False

    def __call__(self, fn):
        def run_fn(*arg, **kw):
            if not self.paused:
                return fn(*arg, **kw)

        return run_fn


p = pausable("mygroup")

e = create_engine("sqlite://", echo=True)


@event.listens_for(e, "before_cursor_execute")
@p
def event1(conn, cursor, statement, parameters, context, executemany):
    print("event1 executing statement!  %s" % statement)


@event.listens_for(e, "before_cursor_execute")
@p
def event2(conn, cursor, statement, parameters, context, executemany):
    print("event2 executing statement!  %s" % statement)


@event.listens_for(e, "before_cursor_execute")
def event3(conn, cursor, statement, parameters, context, executemany):
    print("event3 executing statement!  %s" % statement)


with e.connect() as conn:
    conn.execute("select 'we see this'")
    conn.execute("select 'we see this'")
    with p.pause():
        conn.execute("select 'we dont see this'")
    conn.execute("select 'we see this'")

```

the only issue is that the decorator won't work for events that specify "retval=True" where the return value is required.  In that case, the recipe would need some enhancements so that it can either know how to "return" the value it needs to, or it passes a flag into the event handler itself and the event handler knows not to run itself, just to return what's needed.

**Comment by Peter92** [comment]
Ah ok, thanks for the reply, I'm still relatively new to SA so I wasn't sure if there'd be cases where it'd break things. That way of using a decorator is actually really interesting though, I'd never considered them like that before.

Using `remove` isn't much of an issue for my particular case, as it's only ever run once with the metadata `after_create` event (to initially populate the database from a json file). If I need something to fire off a lot more however, I'll definitely use your suggestion, thanks :)

**Comment by zzzeek** [comment]
> Ah ok, thanks for the reply, I'm still relatively new to SA so I wasn't sure if there'd be cases where it'd break things. That way of using a decorator is actually really interesting though, I'd never considered them like that before.

basically every problem in Python you have to ask, "can a decorator do this?" :)
