### ISSUE TITLE
compoundselect assigns _proxy but does not clear proxy_set cache

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4747]
demo

```
diff --git a/test/sql/test_selectable.py b/test/sql/test_selectable.py
index bfa96d766..cef853148 100644
--- a/test/sql/test_selectable.py
+++ b/test/sql/test_selectable.py
@@ -433,6 +433,18 @@ class SelectableTest(
         assert u1.corresponding_column(table1.c.colx) is u1.c.col2
         assert u1.corresponding_column(table1.c.col3) is u1.c.col1
 
+    def test_proxy_set_pollution(self):
+        s1 = select([table1.c.col1, table1.c.col2])
+        s2 = select([table1.c.col2, table1.c.col1])
+
+        for c in s1.c:
+            c.proxy_set
+        for c in s2.c:
+            c.proxy_set
+
+        u1 = union(s1, s2)
+        assert u1.corresponding_column(table1.c.col2) is u1.c.col2
+
     def test_singular_union(self):
         u = union(
             select([table1.c.col1, table1.c.col2, table1.c.col3]),

```

just needs to adjust how that "_proxy" assignment takes place.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Clear proxy_set cache when creating an annotated column** https://gerrit.sqlalchemy.org/1337

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Clear proxy_set cache when creating an annotated column** https://gerrit.sqlalchemy.org/1338

**Comment by zzzeek** [comment]
still happening on the 1312 branch, need to reset proxy_set of columns inside of _proxies also and need the test case here to reproduce

**Comment by zzzeek** [comment]
while this can be fixed, it's a major problem because by putting the annotated column into proxy_set, we pull in its very expensive ``__eq__()`` and ``__hash__()`` methods and blow up all the performance tests.    So I can't find a way to generalize being able to use a Column's proxy_set along with annotations unless we change how proxy_set works.    I've tried adding an uncached version but that puts us back into the performance situation.   Basically any column that has an "annotated" inside of its proxy set is now expensive, so I think we may need to make this datastructure different so that the annotations or annotated version of the column can be held separate.

in particular, we maybe should prevent annotated columns in the proxy_set at all because comparisons are more expensive:

diff --git a/lib/sqlalchemy/sql/elements.py b/lib/sqlalchemy/sql/elements.py
index aa7b7f6888..50baf734d1 100644
--- a/lib/sqlalchemy/sql/elements.py
+++ b/lib/sqlalchemy/sql/elements.py
@@ -4384,10 +4384,12 @@ def _corresponding_column_or_error(fromclause, column, require_embedded=False):
 
 class AnnotatedColumnElement(Annotated):
     def __init__(self, element, values):
+        element.proxy_set  # make sure Annotated does *not* go into the
+                           # proxy set, because it's expensive! :)
+                           # this might be where we add some annotations or
+                           # something.
         Annotated.__init__(self, element, values)
         ColumnElement.comparator._reset(self)
-        if self._proxies:
-            ColumnElement.proxy_set._reset(self)
         for attr in ("name", "key", "table"):
             if self.__dict__.get(attr, False) is None:
                 self.__dict__.pop(attr)


```
    def test_proxy_set_iteration_includes_annotated_two(self):
        from sqlalchemy.schema import Column

        c1 = Column("foo", Integer)

        stmt = select([c1]).alias()
        proxy = stmt.c.foo
        c1.proxy_set

        proxy._proxies = [c1._annotate({"weight": 10})]

        d = {}
        for col in proxy.proxy_set:
            d.update(col._annotations)
        eq_(d, {"weight": 10})

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Rework proxy_cache fix to restore performance** https://gerrit.sqlalchemy.org/1340

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Rework proxy_cache fix to restore performance** https://gerrit.sqlalchemy.org/1341
