### ISSUE TITLE
Support executemany() via supports_multivalues_insert for Pandas to_sql

### ISSUE THREAD

**Issue by cjbj** [sqlalchemy/sqlalchemy#4750]
@zzzeek does the Oracle dialect need to expose `supports_multivalues_insert` so Pandas `to_sql` can use `executemany()`? https://github.com/pandas-dev/pandas/pull/19664/files

**Comment by zzzeek** [comment]
cx_Oracle like all DBAPis supports executemany() without any special capabilities or directives.  

supports_multivalues_insert is a flag that is specific to being able to create an INSERT statement that has multiple entries in the VALUES clause and is not related to the DBAPI pep249 executemany() method.

**Comment by cjbj** [comment]
:)
