### ISSUE TITLE
optionengine fails for reflection due to missing "engine" attribute

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4754]
Engine seems to assign "self.engine = self" which is an unpleasant circular reference in any case, that should likely be a descriptor.  it should also be part of `Connectable`.

```
from sqlalchemy import create_engine, MetaData

e = create_engine("sqlite://")
e = e.execution_options(isolation_level="SERIALIZABLE")

m = MetaData()
m.reflect(e)
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure .engine is part of Connectable interface, implement as descriptor** https://gerrit.sqlalchemy.org/1345

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Ensure .engine is part of Connectable interface, implement as descriptor** https://gerrit.sqlalchemy.org/1346
