### ISSUE TITLE
use inspector for all reflection functions, deprecate all old engine "callable" mechanisms, remove dialect.reflecttable etc

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4755]
metadata.reflect and Table autoload should be using inspector directly, and autoload_with should accept an inspector.   The dialect.reflecttable hook should be removed and engine.transaction(), engine.run_callable(), should be deprecated as we have context managers now..  engine.has_table(), engine.table_names(),  should all be deprecated, and internally they should use the inspector.   The inspector then needs to not be using engine.table_names() and such either, there's some crazy circular connectivity going on in there.     a little surprising there's still this much legacy happening in there.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Modernize internal reflection** https://gerrit.sqlalchemy.org/1389
