### ISSUE TITLE
Postgres: cannot create multidimensional arrays using columns as elements

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#4756]
I'm trying to create the following query with sqlalchemy without success:
```sql
SELECT ARRAY[ARRAY[foobar.foo, foobar.bar]] FROM foobar
```

I've tried:

```py
from sqlalchemy.dialects.postgresql import array 
table = sa.table('foobar', sa.column('foo'), sa.column('bar'))

q = sa.select([array([array([table.c.foo, table.c.bar])])])
```
but it raises `ValueError: Do not nest ARRAY types; ARRAY(basetype) handles multi-dimensional arrays of basetype`.
I've also tried this form
```py
q = sa.select([array([[table.c.foo, table.c.bar]])])
```
but it raises `ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'ColumnClause'` when executing since it tries to run ` SELECT ARRAY[%(param_1)s] AS anon_1` using `[table.c.foo, table.c.bar]` as parameter

Is there a way to create this query? I think the first snippet I tried should work, but I'm probably missing something.

Multidimensional array can be created using ` sa.select([array([[1, 2]])])` and mono dimensional array using columns also work with `sa.select([array([table.c.foo, table.c.bar])])`

**Comment by CaselIT** [comment]
It seems that explicitly setting the type of the outer `array` works
```
q = sa.select([array([array([table.c.foo, table.c.bar])], type_=<any type here>)])
```

It this the expected behavior?

**Comment by zzzeek** [comment]
specifying "any type" does not work because the object has the wrong type and it does not behave like an array:

```
>>> data = array([array([foobar.c.foo])], type_=NullType)
>>> data[1][2]
_unsupported_impl
    "Operator '%s' is not supported on " "this expression" % op.__name__
NotImplementedError: Operator 'getitem' is not supported on this expression

```
the request is to support multidimensional array literals which would likely need to be added.  patch in 5 minutes

**Comment by CaselIT** [comment]
what I meant by "works" is that the emitted sql is correct, and the result from the db is as expected.

I agree with you that this should not be the way to generate multidimensional arrays

PS: As always thanks for you quick replay and the effort on this library

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Support multidimensional array literals in Postgresql** https://gerrit.sqlalchemy.org/1347

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Support multidimensional array literals in Postgresql** https://gerrit.sqlalchemy.org/1348

**Comment by zzzeek** [comment]
this is getting merged and release is likely soon if you want to try this out

**Comment by CaselIT** [comment]
Thanks for the super fast resolution!
I'll try it once released
