### ISSUE TITLE
rename apply_labels() and with_labels() to use_labels(), core/ ORM

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4757]
this is a big inconsistency that should be fixed.   Select.use_labels flag right now should become underscored which was the only backwards compat concern.

**Comment by gordthompson** [comment]
@zzzeek - On looking at the code a bit closer, it appears that `.use_labels` is implemented in both `sql/selectable.py` and `orm/query.py` as a status interrogator (i.e., "Is the 'labels' option enabled?"), while `.apply_labels` and `.with_labels` (respectively) are used to set the `self._label_style` flag. Might we want to standardize the "setter" to either `.apply_labels` or `.with_labels` and leave `.use_labels` as the "getter"?

**Comment by zzzeek** [comment]
hey @gordthompson - 

I haven't done a deep think on this one.   Right now in 1.4 there are *three* labeling styles, and that is something new.   the new style is LABEL_STYLE_DISAMBIGUATE_ONLY and it's likely good as the "only" label style we might actually need going forward.    the internals should not really be checking ".use_labels" at this point because it does no accommodate for the three styles that exist now.

So i had in mind some new API that accommodates for these styles:

   stmt = stmt.use_labels(LABEL_STYLE_DISAMBIGUATE_ONLY)

or something, maybe flags  use_labels(disambiguate=True, include_tablename=True), not really sure.

the main point is it should be identical for both Query and select() because they are really two versions of the same thing now.

**Comment by gordthompson** [comment]
@zzzeek - Perhaps one flag might be sufficient:

(`.use_labels()` omitted) → `LABEL_STYLE_NONE`

`.use_labels()` or `.use_labels(False)` or `.use_labels(disambiguate_only=False)` → `LABEL_STYLE_TABLENAME_PLUS_COL`

`.use_labels(True)` or `.use_labels(disambiguate_only=True)` → `LABEL_STYLE_DISAMBIGUATE_ONLY`

**Comment by zzzeek** [comment]
it looks like right now Select.use_labels and Query.use_labels are boolean flags indicating the classic style of labeling.   we can perhaps go for a strict approach right now, have those "use_labels" accessors emit a 2.0 deprecation warning, and then add a simple methods set_label_style() and get_label_style() and just use the symbols.     if we were to make the default style "disambiguate only", people would basically never need to worry about this entire thing at all for new code because it always does the right thing.

**Comment by gordthompson** [comment]
@zzzeek - Okay, thanks. I'll give that a shot.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Replace with_labels() and apply_labels() in ORM/Core** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2463

**Comment by gordthompson** [comment]
Okay, so apparently trying to use

``` python
.set_label_style(util.symbol("LABEL_STYLE_TABLENAME_PLUS_COL"))
```
in place of

https://github.com/sqlalchemy/sqlalchemy/blob/97cb27777aff9797c16271022f104f39c38f2418/lib/sqlalchemy/orm/strategies.py#L904

is a no-no:

> sqlalchemy.exc.InvalidRequestError: Can't invoke Python callable symbol() inside of lambda expression argument

**Comment by zzzeek** [comment]
one would use the symbol object that is already defined:

```
from sqlalchemy import LABEL_STYLE_TABLENAME_PLUS_COL
stmt.set_label_style(LABEL_STYLE_TABLENAME_PLUS_COL)

```

we're going on the assumption at the moment that if we set "LABEL_STYLE_DISAMBIGUATE_ONLY" as the default labeling style, which itself will probably need some adjustments to existing tests etc. , people are generally never going to be using this whole feature explicitly as it won't be necessary.

**Comment by gordthompson** [comment]
The next challenge is to handle statements like

https://github.com/sqlalchemy/sqlalchemy/blob/97cb27777aff9797c16271022f104f39c38f2418/test/orm/test_eager_relations.py#L1084

which currently throws the error

```
Traceback (most recent call last):
  File "C:\Users\Gord\git\sqla-gerrit\test\orm\test_eager_relations.py", line 1085, in test_distinct
    u2.select(use_labels=True),
  File "<string>", line 2, in select
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\util\deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\sql\selectable.py", line 511, in select
    return Select._create_select_from_fromclause(self, [self], **kwargs)
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\sql\selectable.py", line 4136, in _create_select_from_fromclause
    return Select.create_legacy_select(entities, *arg, **kw)
  File "<string>", line 2, in create_legacy_select
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\util\deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\sql\selectable.py", line 4411, in create_legacy_select
    GenerativeSelect.__init__(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_labels'
```

**Comment by zzzeek** [comment]
if a test is calling select(use_labels=True) that will do a 2.0 deprecation warning once we open up the warnings filer.    If I have said previously to remove "use_labels=True" altogether, we can't do that for 1.4 because it's public API.   so I would say restore use_labels keyword argument in the create_legacy_select() method and GenerativeSelect.__init__().

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Replace with_labels() and apply_labels() in ORM/Core** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2463
