### ISSUE TITLE
Postgres' array subscripting operator binds too tightly for FunctionFilter to work

### ISSUE THREAD

**Issue by sm-Fifteen** [sqlalchemy/sqlalchemy#4760]
In an attempt to compensate for PostgreSQL's lack of a non-windowing `FIRST`/`FIRST_VALUE` aggregate, I have been resorting to doing an ordered array aggregation and then selecting the first element in the few occasions where needed. This has recently been leading to problems when used alongside FunctionFilter operations, since the syntax Postgres uses for array subscripting apparently takes priority over the `FILTER` keyword.

```sql
-- Invalid
SELECT ARRAY_AGG(num) FILTER (WHERE num % 2 = 0)[1]
FROM generate_series(1, 100) as t(num)
```

```sql
-- Valid (notice the extra parentheses)
SELECT ( ARRAY_AGG(num) FILTER (WHERE num % 2 = 0) )[1]
FROM generate_series(1, 100) as t(num)
```

This came at somewhat of a surprise (I would assume this to be a Postgres bug, since array subscripting is the only operator that does this, even though it isn't really an operator), both to me and SQLAlchemy  since attempting to reproduce that query leads to the same result:

```py
from sqlalchemy import column, select, func
from sqlalchemy.dialects.postgresql import array_agg

# test_db = ...

num = column('generate_series')
query = select([
    array_agg(num).filter(num % 2 == 0)[1]
]).select_from(func.generate_series(1, 100))

res = test_db.execute(query).fetchall()
print(res)
```

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "["
LINE 1: ...ate_series) FILTER (WHERE generate_series % 2 = 0)[1] AS ano...
                                                             ^
[SQL: SELECT array_agg(generate_series) FILTER (WHERE generate_series %% %(generate_series_1)s = %(param_1)s)[%(param_2)s] AS anon_1
FROM generate_series(%(generate_series_2)s, %(generate_series_3)s)]
[parameters: {'generate_series_1': 2, 'param_1': 0, 'param_2': 1, 'generate_series_2': 1, 'generate_series_3': 100}]
(Background on this error at: http://sqlalche.me/e/f405)
```

Unlike in plain SQL, however, there does not appear to be any way to write this query in order to make it valid under SQLAlchemy, and even if there was, there isn't really any reason for the Python code above to compile into incorrect SQL.

**Comment by zzzeek** [comment]
this workaround is available:

```
from sqlalchemy import func
from sqlalchemy.sql.elements import Grouping
from sqlalchemy import column
from sqlalchemy.dialects import postgresql

num = column('q')
print(
    (
        Grouping(func.array_agg(num).filter(num % 2 == 0))[1]
    ).compile(dialect=postgresql.dialect())
)
```

**Comment by zzzeek** [comment]
"filter" does not seem to be an "operator" per se in Postgresql but for now I will have it use the same precedence as the "concat" operator, basically in the middle.   unless you have better information

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**self_group() for FunctionFilter** https://gerrit.sqlalchemy.org/1353

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**self_group() for FunctionFilter** https://gerrit.sqlalchemy.org/1354

**Comment by sm-Fifteen** [comment]
> "filter" does not seem to be an "operator" per se in Postgresql but for now I will have it use the same precedence as the "concat" operator, basically in the middle. unless you have better information

Yeah, none of these components are actually operators, they're all syntax elements that are reacting strangely when put together. With that said, handling 'FILTER' like a binary operator for the sake of grouping is probably the best solution when it comes to this sort of interaction.
