### ISSUE TITLE
Error in session event documentation

### ISSUE THREAD

**Issue by flyingdutchman** [sqlalchemy/sqlalchemy#4765]
I found an inconsistency in the documentation about the session state changes: 

![image](https://user-images.githubusercontent.com/26379223/61280918-066b6280-a7b9-11e9-9111-2bf0e5eb1f95.png)
https://docs.sqlalchemy.org/en/13/orm/session_events.html#deleted-to-persistent

The code is not the correct one

**Comment by zzzeek** [comment]
it's a bug.

**Comment by zzzeek** [comment]
resolved by #4770
