### ISSUE TITLE
synonym_for without docstring break Sphinx autodoc builds (infinite recursion)

### ISSUE THREAD

**Issue by tlandschoff-scale** [sqlalchemy/sqlalchemy#4767]
Hi *,

the following code illustrates the fundamental problem: Accessing the `__name__` property of a synonym causes recursion:

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import *

Base = declarative_base()


# Parent must exist before child ;-)

class Parent(Base):
    __tablename__ = "parent"
    id = Column(Integer, primary_key=True)
    _contents = relation("Child", backref="_parent")


class Child(Base):
    __tablename__ = "child"

    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey("parent.id"))

    @property
    def parent(self):
        """Parent object"""
        return self._parent

    @synonym_for("_parent")
    @parent.setter
    def parent(self, value):
        self._parent = parent
```

With this, the following attribute access recurses:

```
>>> from depth import Child
>>> Child.parent.__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/sqlalchemy/orm/attributes.py", line 306, in __getattr__
    return getattr(self.comparator, attribute)
  File ".../site-packages/sqlalchemy/orm/attributes.py", line 306, in __getattr__
    return getattr(self.comparator, attribute)
...
  File ".../site-packages/sqlalchemy/util/langhelpers.py", line 853, in __getattr__
    return self._fallback_getattr(key)
  File ".../site-packages/sqlalchemy/util/langhelpers.py", line 831, in _fallback_getattr
    raise AttributeError(key)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

For this reason our sphinx documentation does not build anymore (as properties from mixin classes did not supply a docstring). Took a while to find the cause...

No idea what's going on inside SQLAlchemy here though.

**Comment by tlandschoff-scale** [comment]
Here is a full example configured with tox (against python 2.7 and 3.5):

[gh4767.zip](https://github.com/sqlalchemy/sqlalchemy/files/3397616/gh4767.zip)

Output for me:

```
$ unzip gh4767.zip
$ cd gh4767
$ python -m tox
...
updating environment: 2 added, 0 changed, 0 removed
reading sources... [ 50%] depth

Recursion error:
maximum recursion depth exceeded

This can happen with very large or deeply nested source files.  You can carefully increase the default Python recursion limit of 1000 in conf.py with e.g.:
    import sys; sys.setrecursionlimit(1500)
```

**Comment by zzzeek** [comment]
no workaround other than call configure_mappers() or apply a name, fix will be in next release

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Intercept uncompiled comparator attrbute error for attr access** https://gerrit.sqlalchemy.org/1358

**Comment by tlandschoff-scale** [comment]
> no workaround other than call configure_mappers() or apply a name, fix will be in next release

Actually I found another one: Add the missing docstring :-)

Thanks for the hint about configure_mappers(), wondered about that functionality as well.

Greetings, Torsten

**Comment by zzzeek** [comment]
OK now that I've gotten to look at this,the special thing you are doing is making a synonym to an attribute that does not exist yet, until the configure_mappers() sets up the backref.  that's why this case is special.  if you use two relationships with back_populates instead you should not get this problem.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Intercept unresolveable comparator attrbute error for attr access** https://gerrit.sqlalchemy.org/1359
