### ISSUE TITLE
Inspector.get_indexes() does not return indexes on postgres partitioned tables

### ISSUE THREAD

**Issue by otherdoug** [sqlalchemy/sqlalchemy#4771]
**Inspector.get_indexes()** does not return indexes for partitioned tables in postgres when indexes are present. Partitioned tables can have indexes on the parent table, which postgres propagates to the entire hierarchy transparently. See postgres docs [5.10.2.2](https://www.postgresql.org/docs/11/ddl-partitioning.html#DDL-PARTITIONING-DECLARATIVE). Right now, **get_indexes()** on a partitioned table appears to always return an empty list.

It appears that the query below is the culprit:
https://github.com/sqlalchemy/sqlalchemy/blob/5cf8e14d58c89fdb94c60bf5e94d8b13d296da25/lib/sqlalchemy/dialects/postgresql/base.py#L3236-L3264

Per postgres documentation, partitioned tables use 'p' as their `relkind` value, separately from other table types: https://www.postgresql.org/docs/11/catalog-pg-class.html. However, 'p' isn't included in the `WHERE` clause of the query.

As a quick test, executing the same query with `t.relkind IN ('r', 'v', 'f', 'm', 'p')` substituted in the `WHERE` clause appears to generate sensible results for my tables.

**Example SQL and Python:**
Create a partitioned table with indexes:
```SQL
CREATE TABLE tmp123 (col1 INTEGER, col2 INTEGER, col3 INTEGER) PARTITION BY HASH (col1);
CREATE INDEX ix_tmp123_col1 ON tmp123 (col1);
CREATE INDEX ix_tmp123_col2 ON tmp123 (col2);
CREATE INDEX ix_tmp123_col3 ON tmp123 (col3);
```

Satisfy ourselves that the indexes are really there:
```
# \d+ tmp123
                                  Table "public.tmp123"
 Column |  Type   | Collation | Nullable | Default | Storage | Stats target | Description 
--------+---------+-----------+----------+---------+---------+--------------+-------------
 col1   | integer |           |          |         | plain   |              | 
 col2   | integer |           |          |         | plain   |              | 
 col3   | integer |           |          |         | plain   |              | 
Partition key: HASH (col1)
Indexes:
    "ix_tmp123_col1" btree (col1)
    "ix_tmp123_col2" btree (col2)
    "ix_tmp123_col3" btree (col3)
Number of partitions: 0
```

And then try to inspect them:
```python
>>> import sqlalchemy as sa
>>> eng = sa.create_engine("postgresql://yourstring")
>>> ins = sa.engine.reflection.Inspector(eng)
>>> indexes = ins.get_indexes('tmp123')
>>> indexes
[]
```

**Comment by zzzeek** [comment]
hi -

can you provide a pull request with tests?

**Comment by zzzeek** [comment]
partitoined reflection was added in #4237

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Include 'p' for get_indexes() query** https://gerrit.sqlalchemy.org/1366

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Include 'p' for get_indexes() query** https://gerrit.sqlalchemy.org/1367

**Comment by zzzeek** [comment]
now I know why this wasn't implemented, because indexes for partitioned tables are apparently only available in PG 11.    important detail.

**Comment by otherdoug** [comment]
Hey sorry, little new at this. Looks like you have better tests than I would've written :)

And sorry didn't realize indexed partitions were new only as of PG11, but that definitely explains it.

**Comment by zzzeek** [comment]
crazy easy one liner of a fix, no worries!
