### ISSUE TITLE
regression, need proper error message for unaliased self-referential relationship

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4773]
in 1.2 we get the correct error:
`
sqlalchemy.exc.InvalidRequestError: Can't construct a join from Mapper|A|a to Mapper|A|a, they are the same entity`

now we're getting:
```

File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/query.py", line 2458, in _join_left_to_right
    assert left is not right or create_aliases
AssertionError
```

```

from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    parent_id = Column(ForeignKey("a.id"))
    as_ = relationship("A", remote_side="A.id")

s = Session()

s.query(A).join(A.as_)
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Fix regression for self-ref join to self error message** https://gerrit.sqlalchemy.org/1363

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix regression for self-ref join to self error message** https://gerrit.sqlalchemy.org/1364
