### ISSUE TITLE
selectinload doesn't need to JOIN for m2o either

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4775]
in #4340 we took out the JOIN when we are doing one-to-many where the foriegn key can be used as the primary key of the parent.    this optimization is even easier to do for a many-to-one, however, and a JOIN shouldn't be needed there either.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Optimize out JOIN for selectinload with many to one** https://gerrit.sqlalchemy.org/1368

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Optimize out JOIN for selectinload with many to one** https://gerrit.sqlalchemy.org/1369
