### ISSUE TITLE
Support multiple parents on orm

### ISSUE THREAD

**Issue by mrquokka** [sqlalchemy/sqlalchemy#4781]
If i will try to create class with two parent, error raised

`sqlalchemy.exc.InvalidRequestError: Class <class '__main__.TestCls'> has multiple mapped bases: [<class '__main__.RootClass_'>, <class '__main__.RootClass2_'>]`

Can i make a trick to support it?

Example is

```
import sqlalchemy.types
from base import Base, UUID, engine


class RootClass_(Base):
  __tablename__ = "rootclass_"
  mRID = sqlalchemy.Column(UUID, server_default=sqlalchemy.text(
      "uuid_generate_v4()"), primary_key=True)
  polymorphic_type = sqlalchemy.Column(sqlalchemy.types.String)
  __mapper_args__ = {
      'polymorphic_identity': __tablename__,
      'polymorphic_on': polymorphic_type
  }


class TestCls(RootClass_):
  __tablename__ = 'testcls'
  mRID = sqlalchemy.Column(
      UUID,
      sqlalchemy.ForeignKey(RootClass_.mRID),
      primary_key=True)
  __mapper_args__ = {
      "polymorphic_identity": __tablename__,
      "inherit_condition": mRID == RootClass_.mRID
  }


class TestCls2(RootClass_):
  __tablename__ = 'testcls2'
  mRID = sqlalchemy.Column(
      UUID,
      sqlalchemy.ForeignKey(RootClass_.mRID),
      primary_key=True)
  __mapper_args__ = {
      "polymorphic_identity": __tablename__,
      "inherit_condition": mRID == RootClass_.mRID
  }


class TestCls3(TestCls, TestCls2):
  __tablename__ = 'testcls3'
  mRID = sqlalchemy.Column(
      UUID,
      sqlalchemy.ForeignKey(TestCls.mRID),
      sqlalchemy.ForeignKey(TestCls2.mRID),
      primary_key=True)
  __mapper_args__ = {
      "polymorphic_identity": __tablename__,
      "inherit_condition": mRID == TestCls.mRID and mRID == TestCls2.mRID
  }


Base.metadata.create_all(engine)
```

**Comment by zzzeek** [comment]
TestCls3 can't map to both the "testcls3", "testcls2", and "testcls" tables at the same time, what this is trying to do is database multiple inheritance, which is explictly not supported by SQLAlchemy as it is vastly too complicated.  Instead, model the multiple parents using [relationship()](https://docs.sqlalchemy.org/en/13/orm/relationship_api.html?highlight=relationship#sqlalchemy.orm.relationship).

Additionally, if you just want to share common mappings between descendant classes, you can use [mixins](https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/mixins.html?highlight=mixins) for that.

**Comment by mrquokka** [comment]
> TestCls3 can't map to both the "testcls3", "testcls2", and "testcls" tables at the same time, what this is trying to do is database multiple inheritance, which is explictly not supported by SQLAlchemy as it is vastly too complicated. Instead, model the multiple parents using [relationship()](https://docs.sqlalchemy.org/en/13/orm/relationship_api.html?highlight=relationship#sqlalchemy.orm.relationship).
> 
> Additionally, if you just want to share common mappings between descendant classes, you can use [mixins](https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/mixins.html?highlight=mixins) for that.

That's bad, thanks for answer
