### ISSUE TITLE
add support for MSSQL try_cast function

### ISSUE THREAD

**Issue by sansagara** [sqlalchemy/sqlalchemy#4782]
I have this weird use case, when joining two tables on columns with different data types, where i want to make use of the MSSQL ` try_cast()` function. Right now, it's almost impossible to do, since using the builtin `cast` function is not enough, and using `func.try_cast` will result on a syntax error, as it expects the AS keyword.

My workaround has been to use: 
`.join(JoinedTable, Table.ColeccionID == func.try_cast(text('[JoinedTable].[Coleccion] AS float')))`

Using ´text()´ has been the only way to make this work, but having the table and column name as a string is not elegant.

**Comment by zzzeek** [comment]
for any custom SQL you can use [@compiles](https://docs.sqlalchemy.org/en/13/core/compiler.html) to create that object:

```
from sqlalchemy import column
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import table
from sqlalchemy.dialects import mssql
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql.elements import Cast


class TryCast(Cast):
    pass


@compiles(TryCast, "mssql")
def _try_cast(element, compiler, **kw):
    return "TRY CAST (%s AS %s)" % (
        compiler.process(element.clause, **kw),
        compiler.process(element.typeclause, **kw),
    )

t = table("t", column("a"), column("b"))
stmt = select([TryCast(t.c.a, Integer)])
print(stmt.compile(dialect=mssql.dialect()))

```

**Comment by zzzeek** [comment]
I can accept PRs to add a "sqlalchemy.dialects.mssql.try_cast" function to the dialect officially.

**Comment by sansagara** [comment]
Great! I can work on such a feature....

**Comment by zzzeek** [comment]
still needs to be committed...

**Comment by sqla-tester** [comment]
**Leonel Atencio** has proposed a fix for this issue in the **master** branch:

**Add support for try_cast  function on sqlalchemy.dialects.mssql** https://gerrit.sqlalchemy.org/1401

**Comment by sqla-tester** [comment]
**Leonel Atencio** has proposed a fix for this issue in the **rel_1_3** branch:

**Add support for try_cast  function on sqlalchemy.dialects.mssql** https://gerrit.sqlalchemy.org/1412
