### ISSUE TITLE
ARRAY and MEMBER are new MySQL RESERVED_WORDS

### ISSUE THREAD

**Issue by nikitych** [sqlalchemy/sqlalchemy#4783]
MySQL 8.0.17 added `ARRAY` and `MEMBER` to the Reserved keywords list.
https://dev.mysql.com/doc/refman/8.0/en/keywords.html

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add ARRAY and MEMBER to MySQL reserved words** https://gerrit.sqlalchemy.org/1378

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Add ARRAY and MEMBER to MySQL reserved words** https://gerrit.sqlalchemy.org/1379
