### ISSUE TITLE
allow user to override max_chars in raw sql query

### ISSUE THREAD

**Issue by msouth** [sqlalchemy/sqlalchemy#4791]
(Note: I am a python novice so I apologize if I'm asking too obvious a question)

I have an application that is using the ORM for all user-facing functionality, but I need to do raw queries for debugging/testing etc.  I made a quick flask route that accepts a query and executes it using conn.execute() as explained in the docs.

I need to be able to see the result of a `show create table foo` query against a mysql database, but it ends up truncating most of the table definition due to the setting of `max_chars` in `sql/util.py`

Is there some way I can increase the max_chars value, or (ideally) ask for my results not to be truncated at all?  I am thinking maybe on `connect()` or `execute()` you would do `execute(no_truncate=1)` or `connect(max_result_chars=1000000)`.

**Comment by zzzeek** [comment]
to get CREATE TABLE as a string use the recipe at:

https://docs.sqlalchemy.org/en/13/faq/metadata_schema.html#how-can-i-get-the-create-table-drop-table-output-as-a-string

**Comment by zzzeek** [comment]
oh, "SHOW CREATE TABLE".   you shouldn't use logging to see it, just fetch the result and print it:

    result = connection.execute("SHOW CREATE TABLE foo")
    print(result.fetchone()[0])

people usually use reflection or inspection to get this data, see https://docs.sqlalchemy.org/en/13/core/reflection.html and https://docs.sqlalchemy.org/en/13/core/reflection.html#fine-grained-reflection-with-inspector

**Comment by msouth** [comment]
OK--for posterity, if someone else needs what I needed here, it would be `print(result.fetchone()[1])`--the thing at zero would be 'foo', the name of the table.

To clarify a bit, my code was like this:

            
            rs = con.execute(query)
            for row in rs:
                return_string = return_string + str(row)

So, I realize now I was getting a "repr" of the data and not accessing the actual data.

Thank you for your help.

**Comment by zzzeek** [comment]
ah that is interesting, the whole row's "repr" does the truncation, not just the logging, i forgot about that
