### ISSUE TITLE
cx_Oracle dialect does not offer options to handle corrupt data

### ISSUE THREAD

**Issue by zoltan-fedor** [sqlalchemy/sqlalchemy#4799]
This issue has been described in details at https://github.com/oracle/python-cx_Oracle/issues/343
In summary, there are cases when Oracle contains "corrupt data", meaning data which cannot be encoded with UTF8 properly. This should be rare, but when it happens, then the current behavior of SQLAlchemy+cx_Oracle to error out. See error below.

Code:
```
sql = f"SELECT {_fields} FROM {self.schema}.{self.name} {_where}"
for r in self.edw.engine.execute(sql):
```
Error thrown when hitting corrupted chars:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 8: invalid continuation byte
```

It would be preferable if SQLAlchemy would allow different handlings of this string encoding issue, just like it is standard in Python (eg "replace", "xmlcharrefreplace", etc. see https://docs.python.org/3/library/codecs.html#error-handlers).

Luckily cx_Oracle allows for this, see https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#querying-corrupt-data

BUT to take advantage of these options, SQLAlchemy's cx_Oracle dialect would need to be enhanced, by allowing a new setting for the selection of the strategy to handle these encoding errors.

I am going to make a PR for it, if that's okey.

How the new functionality would work:
1. There would be a new `create_engine()` parameter in https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/dialects/oracle/cx_oracle.py named `text_encoding_errors`
2. This parameter's default value would be None for backwards compatibility
3. The parameter's value would be supplied to the `encodingErrors` parameter of cx_Oracle's `cursor.var()`, see https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#querying-corrupt-data
4. The possible values of this parameter would be of the standard Python text encoding error handlers, see https://docs.python.org/3/library/codecs.html#error-handlers

**Comment by zzzeek** [comment]
comments are on the PR.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implment encoding_errors for cx_oracle** https://gerrit.sqlalchemy.org/1411

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Implment encoding_errors for cx_oracle** https://gerrit.sqlalchemy.org/1532

**Comment by zzzeek** [comment]
hey there @zoltan-fedor  over at #4932 and also with some of my experimentation I'm getting the impression cx_Oracle already does errors="ignore" somewhat implicitly, as the reporter there also has bad utf-8 and has no problem in SQLAlchemy 1.2, where we only use cx_Oracle's decoders.    If you have access to your database I wonder if the whole need for this flag only arose as of SQLAlchemy 1.3 with Python 2 where we are using SQLAlchemy's decoders?

**Comment by zoltan-fedor** [comment]
"I wonder if the whole need for this flag only arose as of SQLAlchemy 1.3 with Python 2" >> actually in the project where this issue emerged I was using Python 3.7 with SQLAlchemy 1.3.6
