### ISSUE TITLE
Different behavior of `_generate_dispatch` between Python 2 and 3

### ISSUE THREAD

**Issue by killets** [sqlalchemy/sqlalchemy#4800]
Version 1.3.6 & 1.2.17

`ClauseElement.__visit_name__` is set as:
https://github.com/sqlalchemy/sqlalchemy/blob/fa8a5e823430c23c44b1ba3cd7512cb7f22e93b2/lib/sqlalchemy/sql/elements.py#L170
In same file we imported `unicode_literals` from future, this makes `__visit_name__` as `unicode` in python2, `str` in python3.

https://github.com/sqlalchemy/sqlalchemy/blob/fa8a5e823430c23c44b1ba3cd7512cb7f22e93b2/lib/sqlalchemy/sql/elements.py#L13

This will result bellow `_generate_dispatch` hit different follow, python2 enters `else` block, while python 3 enters `if` block.

https://github.com/sqlalchemy/sqlalchemy/blob/6f270fb0e344016ce526e0a1ecb3e3de9ffd1e3b/lib/sqlalchemy/sql/visitors.py#L79

Python2
```python
>>> visit_name
u'clause'
>>> type(visit_name)
<type 'unicode'>
>>> isinstance(visit_name, str)
False
```
Python3
```python
>>> visit_name
'clause'
>>> type(visit_name)
<class 'str'>
>>> isinstance(visit_name, str)
True
```

-------------------
In python 3, entering that `if` block, will give me 
```
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.dialects.oracle.base.OracleDDLCompiler object at 0x7f6c899640b8> can't render element of type <class 'sqlalchemy.sql.elements.ClauseElement'> (Background on this error at: http://sqlalche.me/e/l7de)
```
If I force the code enters the `else` block by changing `if  isinstance(visit_name, str)` to `if False:` , it will work without errors.

**Comment by zzzeek** [comment]
hi there -

it looks like an optimization opportunity is being missed but i don't know how you are getting an unsupported compilation error to be emitted. please illustrate a complete MCVE of what is actually not working, thanks.

**Comment by zzzeek** [comment]
The `ClauseElement` class is an abstract class and offers no compilation in either python 2 or 3:
```

from sqlalchemy.sql.elements import ClauseElement

ce = ClauseElement()

print(ce)
```

in both Python 2 and 3, it produces the same error:

`sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.StrSQLCompiler object at 0x7fbf52b24f90> can't render element of type <class 'sqlalchemy.sql.elements.ClauseElement'>`

which is correct because there's no compilation for that object.  So I don't know what it is you are doing.

that said, the optimization should be checking for text_type so I guess I'll push that through.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use compat.text_type to check for visit name string** https://gerrit.sqlalchemy.org/1409

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Use compat.text_type to check for visit name string** https://gerrit.sqlalchemy.org/1410
