### ISSUE TITLE
mysqlclient / pymysql removal of SET NAMES seems to break MySQL 8.0

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4804]
see https://github.com/PyMySQL/mysqlclient-python/issues/383.  We probably have to call SET NAMES ourselves.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Emit SET NAMES for all MySQL connections w charset** https://gerrit.sqlalchemy.org/1407

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Emit SET NAMES for all MySQL connections w charset** https://gerrit.sqlalchemy.org/1408
