### ISSUE TITLE
Inconsistent state when dialect initialization fails on the first connection attempt

### ISSUE THREAD

**Issue by vmagamedov** [sqlalchemy/sqlalchemy#4807]
We're using `PGDialect_psycopg2` and `pgbouncer`. In some cases, pgbouncer allows you to connect, but then connection may fail. The problem in that SQLAlchemy tries to initialize dialect only once, during this first connect, and if this initialization fails, SQLAlchemy doesn't trying to retry.

Our example. By default `PGDialect_psycopg2._has_native_jsonb == False`, and only during connection initialization this property becomes equal to `True`. When initialization fails on the first connect, SQLAlchemy then tries to decode already decoded by psycopg2 `JSONB` column values on subsequent connections.

Where strange things happen:

https://github.com/sqlalchemy/sqlalchemy/blob/d1948bc69bd0d26fbff77d7525ef899a2a9a580d/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L715-L726

https://github.com/sqlalchemy/sqlalchemy/blob/d1948bc69bd0d26fbff77d7525ef899a2a9a580d/lib/sqlalchemy/engine/create.py#L524-L532

Maybe it is safer to `listen` for every new connection and store somewhere the mark that dialect was already successfully initialized?

## How to reproduce

Here is how to easily reproduce this error (tried master and 1.3.7 versions):
```python
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:postgres@db:5432/test')

try:
    print(engine.execute('select 1;').fetchall())
except ZeroDivisionError as e:
    print(e)

print(engine.execute('select 1;').fetchall())
print('_has_native_jsonb', engine.dialect._has_native_jsonb)
```
Then just place `1/0` into `PGDialect_psycopg2.initialize()` method. Here is what this example prints:
```
division by zero
[(1,)]
_has_native_jsonb False
```
With our database we get this error on subsequent connections:
```python
Traceback (most recent call last):
  File "sandbox.py", line 54, in <module>
    print(engine.execute(product.select().where(product.c.id == 709765476)).fetchall())
  File "/Users/vm/ws/app/env/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 170, in __repr__
    return repr(sql_util._repr_row(self))
  File "/Users/vm/ws/app/env/lib/python3.7/site-packages/sqlalchemy/sql/util.py", line 458, in __repr__
    ", ".join(trunc(value) for value in self.row),
  File "/Users/vm/ws/app/env/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 2278, in process
    return json_deserializer(value)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```
When you remove `1/0` this error disappears.

**Comment by zzzeek** [comment]
I get it, that's a good solid bug.   I like my first_connect event so strategy will be that the pool will re run it if it fails.  Can you clarify what the error case pgbouncer is encountering ?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add new "exec_once_unless_exception" system; apply to dialect.initialize** https://gerrit.sqlalchemy.org/1417

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Add new "exec_once_unless_exception" system; apply to dialect.initialize** https://gerrit.sqlalchemy.org/1418

**Comment by zzzeek** [comment]
I haven't run your specific test but I have unit tests into the generic dialect.   If you could also use the linked patch and confirm your case is fixed that would be very helpful, thanks!
