### ISSUE TITLE
sql server: need to create new parameter type for "TOP N" query

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4808]
we hardcode the integer in "SELECT TOP 5 ..." in SQL Server.  This needs to be a new kind of bound parameter that is filled in by the execution context in a manner similar to that of expanding IN.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Render SQL Server LIMIT conditions after compile** https://gerrit.sqlalchemy.org/1421

**Comment by zzzeek** [comment]
kind of a crazy thing here is that this TOP N thing only comes in if the LIMIT is an integer directly.  that is, baked queries are unaffected because we use a bindparam() for limit() right now, and it uses ROW_NUMBER.   Technically we don't need "TOP N" at all but it is likely more performant for simple limits.  the new caching will of course need to work here for simple ints.
