### ISSUE TITLE
Make the joining operator of multiple filter criterions configurable

### ISSUE THREAD

**Issue by iSplasher** [sqlalchemy/sqlalchemy#4811]
Hello,
It would be really great if this operator was configurable.
https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/query.py#L1776

I have a query that emitted two different SQL queries depending on when I applied a filter criterion.

**Comment by zzzeek** [comment]
hi there -

I'm not following what effect you are looking for.  Can you please provide an example?

**Comment by iSplasher** [comment]
**I tried again while writing this, and it worked as expected. Turns out I was too tired last time. Sorry for the waste of time. Closing.**

**Here's the original reply:**

I'm sorry, I should've provided an example first. Sorry for the low quality post.

I have this long chain of query where I apply filter criterions and joins imperatively:
```
q = session.query(C).join(G).filter(A).join(H).filter(B)
```
This produced SQL that looks like this:
```
SELECT (...)
FROM (...)
WHERE (A) AND (B)
```
So, because I'd want an `OR` operation between the filters instead of `AND`,
I thought of saving up the filters to instead apply them all at the end:
```
q = session.query(C).join(G).join(H)
q.filter(or_(*saved_filters))
```
Thinking it would produce a query akin to the one above where `AND` is replaced with `OR`, it produced this instead:
```
SELECT (...)
FROM (...)
WHERE (A) or (
SELECT (...)
FROM (...)
WHERE (...)
)
```

**Comment by zzzeek** [comment]
hmmm OK, if `saved_filters` were just filter criteria, you wouldn't get a SELECT embedded like that, so I guess more was going on than that.   There have been occasional calls for some kind of "filter_or()" method to allow chaining of OR, but it would be of limited use since usually there are AND operators involved which mean the ORs necessarily need parenthesization.
