### ISSUE TITLE
PickleType not reflecting (SQLAlchemy 1.3.7)

### ISSUE THREAD

**Issue by kwatsen** [sqlalchemy/sqlalchemy#4812]
`PickleType` works fine when using the `MetaData` object used to create the table, but creating a new `Metadata` object and reflecting the table schema doesn't.

Note that everything works if the column type is `JSON` instead.

Here's a simple test program:
```
import sqlalchemy as sa

engine = sa.create_engine("sqlite:///test.db")
metadata = sa.MetaData(bind=engine)

test_table = sa.Table('test_table', metadata,
        sa.Column('row_id', sa.Integer, primary_key=True),
        sa.Column('my_obj', sa.PickleType)
        )
test_table.create()

# this works
with engine.connect() as conn:
    conn.execute(
        test_table.insert().values(
            my_obj = {'a': 1, 'b': '111', 'c': None}
            )
        )

# this fails
metadata2 = sa.MetaData(bind=engine)
metadata2.reflect()
test_table2 = sa.Table('test_table', metadata2, autoload=True)
with engine.connect() as conn:
    conn.execute(
        test_table2.insert().values(
            my_obj = {'a': 2, 'b': '222', 'c': None}
            )
        )

```

Here's the full stack trace:
```
$ rm test.db; python test_sqla_pickletype.py 
Traceback (most recent call last):
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 719, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 912, in process
    return DBAPIBinary(value)
TypeError: memoryview: a bytes-like object is required, not 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_sqla_pickletype.py", line 27, in <module>
    my_obj = {'a': 2, 'b': '222', 'c': None}
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 719, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 912, in process
    return DBAPIBinary(value)
sqlalchemy.exc.StatementError: (builtins.TypeError) memoryview: a bytes-like object is required, not 'dict'
[SQL: INSERT INTO test_table (my_obj) VALUES (?)]
```

Is this a bug or am I doing something wrong?

**Comment by zzzeek** [comment]
I might as well answer this fully, so I am writing this answer in the form of new documentation, however I don't have time to finish it right now.    You can read the patch that will be linked on this issue momentarily.   short answer is  PickleType is a Python type, not a database type, and if you need to combine the use of explicit Table metadata with reflected Table metadata and have the in-Python datatypes behave the same way, you need to override the types as discussed at https://docs.sqlalchemy.org/en/13/core/reflection.html#overriding-reflected-columns.  There are also more fine-grained approaches to this using events.    Generally it's better if, if you are making use of Python-only datatypes, you just rely on the explicit Table metadata that uses these datatypes rather than having other parts of the application rely on reflection.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Document how to work with reflection and custom datatypes** https://gerrit.sqlalchemy.org/1424

**Comment by kwatsen** [comment]
Thanks for the quick response and the documentation-add!

My application is modularized and it is the case that the first-time run does heavy analysis of some input data in order to dynamically calculate what tables and columns to create. For subsequent runs, the goal is to skip the analysis and jump to the runtime logic, relying on reflection to provide the necessary column types.  I understand the current implementation solely relies the metadata provided by the underlying DB, and hence is lossy by nature.  Presumably the fix would be for SA to store a special table/data of its own allowing for lossless reflection.  Would this be possible?

As for the suggested fix, I modified the code from:
```
test_table2 = sa.Table('test_table', metadata2, autoload=True)
```
to:
```
test_table2 = sa.Table('test_table', metadata2, sa.Column('my_obj', sa.PickleType), autoload=True)
```
and received this error:
```
$ rm test.db; python test_sqla_pickletype.py 
Traceback (most recent call last):
  File "test_sqla_pickletype.py", line 23, in <module>
    test_table2 = sa.Table('test_table', metadata2, sa.Column('my_obj', sa.PickleType), autoload=True)
  File "<string>", line 2, in __new__
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
    return fn(*args, **kwargs)
  File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 478, in __new__
    "existing Table object." % key
sqlalchemy.exc.InvalidRequestError: Table 'test_table' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```
Changing the line to:
```
test_table2 = sa.Table('test_table', metadata2, sa.Column('my_obj', sa.PickleType), autoload=True, extend_existing=True)
```
works!  

Perhaps add `extend_existing=True` to the example in  [Overriding Reflected Columns](https://docs.sqlalchemy.org/en/13/core/reflection.html#overriding-reflected-columns) Separately, it seems that [Limitations of Reflection](https://docs.sqlalchemy.org/en/13/core/reflection.html#limitations-of-reflection) could be updated as well.

One remaining question, assuming a table has many columns, is it okay the [Overriding Reflected Columns](https://docs.sqlalchemy.org/en/13/core/reflection.html#overriding-reflected-columns) to be on a subset of them (i.e., just the ones that had lossy reflection)?

Thanks!

**Comment by zzzeek** [comment]
> Thanks for the quick response and the documentation-add!
> 
> My application is modularized and it is the case that the first-time run does heavy analysis of some input data in order to dynamically calculate what tables and columns to create. For subsequent runs, the goal is to skip the analysis and jump to the runtime logic, relying on reflection to provide the necessary column types. I understand the current implementation solely relies the metadata provided by the underlying DB, and hence is lossy by nature. Presumably the fix would be for SA to store a special table/data of its own allowing for lossless reflection. Would this be possible?

That would never be a built-in feature but it can be written as an extension which uses events in order to receive both the emission of DDL as well as the reflected column event.  that is, there are event hooks which allow these things to be intercepted.  the extension would read and write to its own metadata tables to store these events.    it would be complicated to generalize, as if someone goes into the database and runs schema migrations, or creates tables by hand, etc. that all complicates the workflow.    

as mentioned earlier, there's not a strong need for this because if folks have explicit table metadata already, which is the normal case of use, they don't need to use reflection.



> 
> As for the suggested fix, I modified the code from:
> 
> ```
> test_table2 = sa.Table('test_table', metadata2, autoload=True)
> ```
> 
> to:
> 
> ```
> test_table2 = sa.Table('test_table', metadata2, sa.Column('my_obj', sa.PickleType), autoload=True)
> ```
> 
> and received this error:
> 
> ```
> $ rm test.db; python test_sqla_pickletype.py 
> Traceback (most recent call last):
>   File "test_sqla_pickletype.py", line 23, in <module>
>     test_table2 = sa.Table('test_table', metadata2, sa.Column('my_obj', sa.PickleType), autoload=True)
>   File "<string>", line 2, in __new__
>   File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
>     return fn(*args, **kwargs)
>   File "/Users/kent/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 478, in __new__
>     "existing Table object." % key
> sqlalchemy.exc.InvalidRequestError: Table 'test_table' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
> ```
> 
> Changing the line to:
> 
> ```
> test_table2 = sa.Table('test_table', metadata2, sa.Column('my_obj', sa.PickleType), autoload=True, extend_existing=True)
> ```
> 
> works!
> 
> Perhaps add `extend_existing=True` to the example in [Overriding Reflected Columns](https://docs.sqlalchemy.org/en/13/core/reflection.html#overriding-reflected-columns) Separately, it seems that [Limitations of Reflection](https://docs.sqlalchemy.org/en/13/core/reflection.html#limitations-of-reflection) could be updated as well.

OK that might be a documentation bug at this point, I'm not sure why the flag isn't there right now so I'm curious to see if perhaps long ago that flag wasn't needed, or something (yes, this is all my code and my documentation but there's no way I can track it all in my memory after 15 years).


> 
> One remaining question, assuming a table has many columns, is it okay the [Overriding Reflected Columns](https://docs.sqlalchemy.org/en/13/core/reflection.html#overriding-reflected-columns) to be on a subset of them (i.e., just the ones that had lossy reflection)?

OK yes, that's how it's supposed to work, if you had specified every column, there would not be any need to use "autoload", is there a way the example could be enhanced to make this clear?   if I added a comment like "# other columns can be omitted and will be refleted normally" ?   

> 
> Thanks again!
> Kent

**Comment by kwatsen** [comment]
> OK yes, that's how it's supposed to work, if you had specified every column, there would not be any need to use "autoload", 

Good point.

> is there a way the example could be enhanced to make this clear? if I added a comment like "# other columns can be omitted and will be reflected normally" ?

Actually, I may have written too soon before, as it appears that [Overriding Reflected Columns](https://docs.sqlalchemy.org/en/13/core/reflection.html#overriding-reflected-columns) has the statement "Individual columns can be overridden", and this is in the beginning of the first sentence no less!  ;)

Last question: would it be possible for one to pickle the sa.Table handles (with the full column types, etc.) and then on a subsequent run, fetch and reconstitute them?  I'm guessing that it probably wouldn't work, because the metadata/engine handles wouldn't be the same as before, right?

PS: feel free to close this issue, or I will on your next reply.

**Comment by zzzeek** [comment]
> 
> Last question: would it be possible for one to pickle the sa.Table handles (with the full column types, etc.) and then on a subsequent run, fetch and reconstitute them? I'm guessing that it probably wouldn't work, because the metadata/engine handles wouldn't be the same as before, right?

Table metadata is pickleable.   People do use this pattern, but the funny thing is that if you have a file that is a huge binary pickle of Table metadata, if possible, it's better to just have a file that is the original Python code with the Table objects inside of it.     But if you have existing DB schemas and such, yes people have pickled Metadata files and that is a common thing.    I wouldn't try using them across new SQLAlchemy releases , however, e.g. they aren't good as long term canonical storage.     


> 
> PS: feel free to close this issue, or I will on your next reply.

my documentation patch will auto-close this issue once I push it to master.
