### ISSUE TITLE
[sqlite] ATTACH DATABASE is not working since v1.3.7

### ISSUE THREAD

**Issue by xmnlab** [sqlalchemy/sqlalchemy#4814]
hey everyone!

Until sqlalchemy 1.3.6 connection to `sqlite://` + attach database approach was working[1][2] on ibis project.

but It seems using v1.3.7 it is not working any more .. but I am wondering how it is different from this test: https://github.com/sqlalchemy/sqlalchemy/blob/master/test/ext/test_horizontal_shard.py#L445

any thoughts about how to fix this issue?

[1] https://github.com/ibis-project/ibis/blob/9df27958f305a901728b540200bd8fa2820d4625/ibis/sql/sqlite/client.py#L325

[2] https://github.com/ibis-project/ibis/blob/9df27958f305a901728b540200bd8fa2820d4625/ibis/sql/sqlite/client.py#L367

ref: https://github.com/ibis-project/ibis/issues/1930

**Comment by zzzeek** [comment]
your application is likely relying on a bug that was fixed in #4793 .    When you ATTACH DATABASE, and then use table reflection, tables in the attached database must be referred towards by their schema name, that is, the name under which you attached the database.

**Comment by zzzeek** [comment]
the changelog for #4793 will be on the site momentarily, an RST typo prevented it from being displayed.

**Comment by xmnlab** [comment]
thanks @zzzeek for the feedback!

**Comment by zzzeek** [comment]
looks like you have this worked out.

**Comment by xmnlab** [comment]
thank you so much @zzzeek !
