### ISSUE TITLE
add create_engine flag which will cause .params to not be displayed in error messages or log messages

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4815]
see discussion at #4806.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add hide_parameters flag to create_engine** https://gerrit.sqlalchemy.org/1425

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Add hide_parameters flag to create_engine** https://gerrit.sqlalchemy.org/1426
