### ISSUE TITLE
Mysql, Raw sql execute, return me the value ,but type is different.

### ISSUE THREAD

**Issue by IamRoadRunner** [sqlalchemy/sqlalchemy#4821]
the type in table is JSON, but when I execute raw sql ,
it return me the value like unicode,
What should I do  to format it ?
Is there a function ? 
the database is mysql.

**Comment by zzzeek** [comment]
hi there -

if you invoke raw SQL then there is no typing information associated with your columns beyond what the mysql driver gives you.  

to use text with SQLAlchemy types use the [text()](https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=text#sqlalchemy.sql.expression.text) construct:

```
from sqlalchemy import text
result = conn.execute(text("SELECT json_data FROM table").columns(json_data=JSON))
```

**Comment by IamRoadRunner** [comment]
3q
