### ISSUE TITLE
array.contained_by text element assert error

### ISSUE THREAD

**Issue by chinasiten** [sqlalchemy/sqlalchemy#4822]
when i call `array([#some element]).contained_by([''])` will assert error
but
`array([#some element]).contained_by([]) ` works well.
the reason of it is `assert isinstance(obj, int)` in array.py at line 118
but i can't figure out the meaning of that code.
who can explain that for me?thanks.

**Comment by zzzeek** [comment]
I can't either so it's a bug.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove erroneous assertion from array._bind_param** https://gerrit.sqlalchemy.org/1432

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Remove erroneous assertion from array._bind_param** https://gerrit.sqlalchemy.org/1433
