### ISSUE TITLE
raiseload for columns

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4826]
like #3512 , it's almost strange we didn't implement this for columns also.

Is it possible we can use the existing raiseload() construct and have it call upon set_generic_strategy() rather than set_relationship_strategy() ?     it should just work for any attribute.

**Comment by zzzeek** [comment]
see https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/679/ where this has been partially worked on, based on older architectures

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement raiseload for deferred columns** https://gerrit.sqlalchemy.org/1516

**Comment by CaselIT** [comment]
Can you open a new issue?
