### ISSUE TITLE
function name being quoted leading to psycopg2 UndefinedFunction error

### ISSUE THREAD

**Issue by metheoryt** [sqlalchemy/sqlalchemy#4828]
Hi! I use `getattr(sqlalchemy.func, 'foo.bar')` function generator to call custom stored procedure. But since 1.3.0 sqlalchemy wraps such procedure in double quotes, so db cannot find it.
I've tested the case with different sqlalchemy and psycopg2 versions, and figured that this behaviour does not depends on psycopg and was added to sqlalchemy somewhere between 1.2.19 (yet working) and 1.3.0 (already not working).

function being quoted only when containing a dot in its name and obtained dynamically through `getattr` 

`func.foo` - ok
`func.foo.bar` - ok
`getattr(func, 'foo')` - ok
`getattr(func, 'foo.bar')` - quoted

python 3.6
sqlalchemy 1.3.0
psycopg2-binary 2.8.3
postgres 11 (docker)

**Comment by zzzeek** [comment]
hi there -

calling `getattr(func, "foo.bar")` is not the correct usage.  you should be calling `func.foo.bar`, that's what that is for.    if you need this to be based on a string, split the string on the dot and call getattr() for each token individually.

**Comment by metheoryt** [comment]
oh snap, thanks for clarification!
