### ISSUE TITLE
sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table <table_name> expected to update n+1 rows; n were matched

### ISSUE THREAD

**Issue by revolutionisme** [sqlalchemy/sqlalchemy#4831]
Hi,

I am getting a StaleDataError with `SQLAlchemy==1.3.6` whenever sqlalchemy is trying to use `session.bulk_update_mappings()` and its always 1 less than the number of rows to be updated. I am running the code as part of an aws lambda function.

This happens intermittently without any definite pattern. Following is the stack trace:

```
UPDATE statement on table 'data_table' expected to update 33 row(s); 32 were matched.: StaleDataError
Traceback (most recent call last):
File "/var/task/saving/rds/serverless.py", line 185, in handler
output = event_processor(event)
File "/var/task/saving/rds/serverless.py", line 178, in event_processor
save_to_database(data)
File "/var/task/saving/rds/serverless.py", line 133, in save_to_database
session.bulk_update_mappings(Data, update_data)
File "/var/task/sqlalchemy/orm/session.py", line 2849, in bulk_update_mappings
mapper, mappings, True, False, False, False, False
File "/var/task/sqlalchemy/orm/session.py", line 2888, in _bulk_save_mappings
transaction.rollback(_capture_exception=True)
File "/var/task/sqlalchemy/util/langhelpers.py", line 68, in __exit__
compat.reraise(exc_type, exc_value, exc_tb)
File "/var/task/sqlalchemy/util/compat.py", line 153, in reraise
raise value
File "/var/task/sqlalchemy/orm/session.py", line 2873, in _bulk_save_mappings
update_changed_only,
File "/var/task/sqlalchemy/orm/persistence.py", line 180, in _bulk_update
bookkeeping=False,
File "/var/task/sqlalchemy/orm/persistence.py", line 1029, in _emit_update_statements
% (table.description, len(records), rows)
sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'data_table' expected to update 33 row(s); 32 were matched.
```

I have tried multiple things, following is a snippet of the current code base:

```
def connect_db():
    def connect():
        return mysql.connector.connect(host=hostname, user=username, password=password, database=database, port=port)

    db = create_engine(f'mysql+mysqlconnector://', creator=connect, isolation_level='REPEATABLE_READ', echo=False)
    return db


# establish connection once per container
engine = connect_db()
Data.__table__.create(bind=engine, checkfirst=True)
Session = sessionmaker(bind=engine)

def save_to_database(data):
    session = Session()
    try:
        ids = [result[0] for result in session.query(Data.id).with_for_update(nowait=True).all()]
        ...
        #saving logic
        ...
        session.bulk_insert_mappings(Data, insert_data)
        session.flush()

        session.bulk_update_mappings(Data, update_data)
        session.flush()

        session.commit()

    except:
        session.rollback()
        raise
    finally:
        session.close()

def handler(event, context):
    output = save_to_database(event)
    return {'records': output}
```

I even added `.with_for_update(nowait=True)` based on the recommendation from "https://stackoverflow.com/questions/30763961/update-statement-on-table-xxx-expected-to-update-1-rows-0-were-matched-with"

Also I have already checked #3476 as it talked about similar issue but the problem is I am not deleting any ids from the table yet, its just insert or update. I am segregating insert and update after querying for all ids and then depending on that deciding whether the ids should be updated or inserted. 

Any help or pointers in this regard would be really appreciated.

**Comment by zzzeek** [comment]
can you turn on SQL logging?  it will illustrate the UPDATE statement as well as how many parameter sets are being passed.   

this condition can occur if a concurrent process has either deleted one of your rows, or perhaps changed its primary key.  the bulk update logic should be resilient against things like you have the same primary key twice in your data records but I don't recall offhand what it does in that case.

you might want to try explicitly loading all those objects first using Query(), then updating the Python objects, then doing regular flush()/ commit().   It's not as performant but if the error goes away completely when doing that, that would be a clue.

**Comment by revolutionisme** [comment]
@zzzeek I did turn on the logging, the update statement looks fine: 

`UPDATE data_table SET item1=%(item1)s, item2=%(item2)s, item3=%(item3)s, item4=%(item4)s, item5=%(item5)s, item6=%(item6)s, item7=%(item7)s, item8=%(item8)s, item9=%(item9)s, item10=%(item10)s, item11=%(item11)s, item12=%(item12)s, item13=%(item13)s, item14=%(item14)s, item15=%(item15)s, categories=%(item16)s, item17=%(item17)s, item18=%(item18)s, item19=%(item19)s, item20=%(item20)s, item21=%(item21)s, item22=%(item22)s, item23=%(item23)s WHERE data_table.id = %(id)s`

based on what you said 

> this condition can occur if a concurrent process has either deleted one of your rows or perhaps changed its primary key

the only situation I can imagine is that another lambda is spawned at the same time and that also consists of an update statement, and somehow or somewhere internally a `REPLACE` is being used and that's the only place the old row is deleted and a new row is inserted. 

Because otherwise, I can't seem to understand why this would happen as I actually have no other place where anything is deleted, the only three operations are Select, Insert and Update. 

> you might want to try explicitly loading all those objects first using Query(), then updating the Python objects, then doing regular flush()/ commit(). It's not as performant but if the error goes away completely when doing that, that would be a clue.

I am already doing the first, getting the ids first using Query, then based on that I am separating entries to be inserted and updated, and then using the bulk_insert and bulk_update mappings.

**Comment by zzzeek** [comment]
if you're already loading the entries using Query I would recommend just using the normal ORM flush() process, and not the bulk_update, if for no other reason than to see if that eliminates the problem or not because it would definitely not include the same PK twice in a single batch and possibly mis-represent the expected update count.      

otherwise it does look much like a row is being deleted from another process concurrently.  SQLAlchemy does not emit REPLACE.

**Comment by zzzeek** [comment]
oh.    Just noticed you're using "mysqlconnector".  Please try mysqlclient or pymysql.   the mysqlconnector DBAPI is extremely buggy, that might be the problem right there.

**Comment by revolutionisme** [comment]
> if you're already loading the entries using Query I would recommend just using the normal ORM flush() process, and not the bulk_update,

This i haven't done yet, fearing performance issues, but will definitely try if other things dont work

> if for no other reason than to see if that eliminates the problem or not because it would definitely not include the same PK twice in a single batch and possibly mis-represent the expected update count.

I am deduplicating the entries before passing it through the bulk_insert and bulk_update, both the list has unique entries. 

> oh. Just noticed you're using "mysqlconnector". Please try mysqlclient or pymysql. the mysqlconnector DBAPI is extremely buggy, that might be the problem right there.

This could be it, I would definitely try doing this with pymysql, would share the results. 

Thanks once again

**Comment by revolutionisme** [comment]
Update: Used pymysql, the performance is worse that mysqlconnector (around 3x slow) but its been 1.5 days and still no StaleDataError. 
I will close this issue in another couple of days of monitoring. 
Also, mysqlclient (which apparently is the fastest of the 3) needs some building of dependency and it depends on some system-level libraries that's why couldn't make it work with lambdas. But will try to build those dependencies on Amazon Linux image.

**Comment by zzzeek** [comment]
that's the latest mysqlconnector huh?   wow they are a problem

I'd +1 to get mysqlclient to work it's much faster than pymysql

**Comment by zzzeek** [comment]
well, one more possibility, if your stale data error is a race of some kind perhaps the slower performance of pymysql is the factor changing the behavior, but more likely mysqlconnector has a bug in it.  i've never seen a driver with so many bugs.

**Comment by revolutionisme** [comment]
@zzzeek Another update, not a good one though - received StaleDataError this morning after almost 3 days and only this one spike where lambda retried 4 times :

![image](https://user-images.githubusercontent.com/738958/64415941-86fe5f00-d096-11e9-8cc1-444d6ee08b41.png)

`sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'data_table' expected to update 43 row(s); 7 were matched.`

The only thing different this time is the matched elements, it's not 1 less than the expected items to be updated rather quite a bit 36 items were not matched. 

I would finally just try "On duplicate key update" individually, at least I believe either insert would happen and if insert doesn't happen, I would update it. 

https://docs.sqlalchemy.org/en/13/dialects/mysql.html#insert-on-duplicate-key-update-upsert

Would report back after trying this as well.

**Comment by zzzeek** [comment]
just to confirm, do you want your UPDATE statements to just go through and not actually affect rows that don't match?  you can use a core UPDATE and ignore the rowcount if so.  the bulk update should probably have an option for this too.

**Comment by revolutionisme** [comment]
I want to update if they actually match, technically they should match because I am querying for all the ids in the table and then segregating the data into two lists one which exists in the list of ids - this is used for update, one which doesn't exist in the list of retrieved ids - used for inserts. 

Nevertheless, I utilized "on duplicate key update" on individual rows and it is working for 4-5 days without a single error, the performance is similar to that of pymysql batch process. 

I am still not sure whether its a bug from sqlalchemy, the connectors or on our side (i am fairly sure on our side because theres no delete process yet, so there shouldn't be a stale data error unless there's a race condition somewhere). So you can choose to close this bug/question or if someone is interested s/he can check this out.

**Comment by zzzeek** [comment]
if it were me, I'd be going more in-depth and building out a handle_error() handler that would catch this message and then run a SELECT and such to show exactly what data is in the table when the statement ran, and dump it out to the logs.

**Comment by revolutionisme** [comment]
Thanks for the suggestion, will try and do that when I have some time off for experimentation.

**Comment by zzzeek** [comment]
closing this for now.
