### ISSUE TITLE
SQL Server 2017 (version 14) missing from mssql/base.py

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#4833]
It would go here:

https://github.com/sqlalchemy/sqlalchemy/blob/f499671ccc30cd42d6e3beb6ddec60e104bff9c5/lib/sqlalchemy/dialects/mssql/base.py#L697

**Comment by zzzeek** [comment]
hmm this is just the symbol, and nothing is accessing most of those.  is there some code that needs to look at that symbol in your access dialect?

**Comment by gordthompson** [comment]
No, I was just scanning through the mssql dialect code looking for ideas to steal and I noticed that SQL Server 2017 wasn't in there.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**add SQL Server 2017 to mssql/base.py - Fixes #4833** https://gerrit.sqlalchemy.org/1453
