### ISSUE TITLE
Substring not getting converted for MySQL and SQLite

### ISSUE THREAD

**Issue by Nikita2k** [sqlalchemy/sqlalchemy#4835]
Similar to https://github.com/sqlalchemy/sqlalchemy/issues/2676.
My dev setup runs on SQLite, while prod runs on Mysql. I'd like to use substr in a WHERE clause, but there is no way to do it cross platform.

Ideally I need something like `split` function, which can be done in Mysql like:
```
func.substring_index(
                        column, ":",  POS
                    ),
```
I ended up having a dialect on a session. Is there a function I'm missing?

**Comment by zzzeek** [comment]
if you want to build yourself a cross-platform substring function take a look at the examples at https://docs.sqlalchemy.org/en/13/core/compiler.html#utc-timestamp-function.

**Comment by zzzeek** [comment]
assuming this is answered.
