### ISSUE TITLE
don't read polymorphic discrim in joined eager (or elsewhere) if no PK; raise for no discriminator value if PK

### ISSUE THREAD

**Issue by mrquokka** [sqlalchemy/sqlalchemy#4836]
How can i make a handler when orm read rows, and raise exception when polymorphic_type is undefined?

**Comment by zzzeek** [comment]
it seems like a bug that no exception is raised right now

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Raise if required polymorphic_discriminator isn't present** https://gerrit.sqlalchemy.org/1448

**Comment by zzzeek** [comment]
code would need to emit a warning only in 1.3.x.    not sure if there are existing use cases for the "if not None" check

**Comment by zzzeek** [comment]
got it: 931decd84576e4ec61af31742

this has to do with joined eager loading as we have to gracefully handle a row that is all null for a related item.   the test run should flag if we still run on that assumption in this way.

**Comment by zzzeek** [comment]
it should be that, if we don't have a primary key for the record, we aren't going to look at the other columns.

**Comment by zzzeek** [comment]
wow, it has a test and it raises.  so silly, if there's no PK it should not be doing that.

Let me make this for 1.4, and here's what you can do now:

```
@event.listens_for(A, "load", propagate=True)
def init_a(object_, mapper):
    if not object_.type:
        raise Exception("no type")

```

full example:

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    type = Column(String)

    __mapper_args__ = {"polymorphic_identity": "a", "polymorphic_on": type}


class ASub(A):
    __mapper_args__ = {"polymorphic_identity": "asub"}


@event.listens_for(A, "load", propagate=True)
def init_a(object_, mapper):
    if not object_.type:
        raise Exception("no type")


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(ASub(), ASub())
s.commit()

s.query(A).all()

s.query(A).update(dict(type=None))
s.commit()
s.close()

s.query(A).all()

```

**Comment by mrquokka** [comment]
> it should be that, if we don't have a primary key for the record, we aren't going to look at the other columns.

Thanks. But i need this handler for somethink like that

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    type = Column(String)

    __mapper_args__ = {"polymorphic_identity": "a", "polymorphic_on": type}


def load_subclass():
    class ASub(A):
        __mapper_args__ = {"polymorphic_identity": "asub"}


@event.listens_for(A, "load", propagate=True)
def init_a(object_, mapper):
    if not object_.type:
        load_subclass()


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(ASub(), ASub())
s.commit()

s.query(A).all()

s.query(A).update(dict(type=None))
s.commit()
s.close()

s.query(A).all()
```

**Comment by zzzeek** [comment]
that looks like you've described a completely different problem, that you dont want to import all your models before querying the database.     the mappers can't be used correctly until all the subclasses you need to worry about are set up.    I would not advice configuring new mappers on the fly like that.
