### ISSUE TITLE
gracefully handle pyformat params that have parenthesis in them

### ISSUE THREAD

**Issue by yyscamper** [sqlalchemy/sqlalchemy#4837]
## Environment
- Database: postgresql + psycopg2
- SQLAlchemy: 1.3.3 and 1.3.6

## Description

A table in my database has a special column named `size(kb)`, if I try to query data using this column, the SQL execution fails with following trace. 
However, if I try to label this column with the exactly same name, and then use it in the query instead, the SQL execution will succeed.

```
Traceback (most recent call last):
  File "/Users/yuany/tmp/special_chars.py", line 14, in <module>
    engine.execute(select(['*']).where(table.c[colname] > 1))
  File "/Users/yuany/envs/dbe/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2144, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/yuany/envs/dbe/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/Users/yuany/envs/dbe/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/yuany/envs/dbe/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/Users/yuany/envs/dbe/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/yuany/envs/dbe/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1460, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/Users/yuany/envs/dbe/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/Users/yuany/envs/dbe/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "/Users/yuany/envs/dbe/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
KeyError: 'size(kb'
```

## Reproduce:

Execute the following code you can  reproduce it directly.

```python
#!/usr/bin/env python

from sqlalchemy import Column, Integer, MetaData, Table, create_engine, select

colname = 'size(kb)'

table = Table('test', MetaData(), Column(colname, Integer()), schema='public')
engine = create_engine("postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/postgres")
table.create(bind=engine, checkfirst=True)

# fail for following code
engine.execute(select(['*']).where(table.c[colname] > 1))

# but will succeed if labeled it:
# engine.execute(select(['*']).where(table.c[colname].label(colname) > 1))
```

## Finding

The compiled SQLAlchemy SQL before labeling is:

```sql
SELECT *
FROM public.test
WHERE public.test."size(kb)" > :size(kb)_1
```

After labeling, the SQL becomes: 

```sql
SELECT *
FROM public.test
WHERE public.test."size(kb)" > :param_1
```

The psycopg2 document tells some special characters are not supported:

ref: http://initd.org/psycopg/docs/usage.html#passing-parameters-to-sql-queries

```
Using characters %, (, ) in the argument names is not supported.
```

So this should be the reason for SQL failure. But why the labelled column will succeed, I find a slightly difference in `_bind_param` between `ColumnClause` (`Column` inherits from it) and `ColumnElement`(`Label` inherits from it):

> [ColumnElement](https://github.com/sqlalchemy/sqlalchemy/blob/b83c41c44bad0b166ad9a2355d10641b0310e2fe/lib/sqlalchemy/sql/elements.py#L754): 

```python
    def _bind_param(self, operator, obj, type_=None):
        return BindParameter(
            None,
            obj,
            _compared_to_operator=operator,
            type_=type_,
            _compared_to_type=self.type,
            unique=True,
        )
```

> [ColumnClause](https://github.com/sqlalchemy/sqlalchemy/blob/b83c41c44bad0b166ad9a2355d10641b0310e2fe/lib/sqlalchemy/sql/elements.py#L4290):

```python
    def _bind_param(self, operator, obj, type_=None):
        return BindParameter(
            self.key,
            obj,
            _compared_to_operator=operator,
            _compared_to_type=self.type,
            type_=type_,
            unique=True,
        )
```

The difference is the first parameter for BindParameter, it causes the difference of argument name in compiled SQL.

## Expect

Using the column with special characters directly in SQL querying will succeed.

**Comment by zzzeek** [comment]
hi there -

that's not the correct compiled SQL, because you need to use the psycopg2 dialect to generate it.    Here is the actual query that psycopg2 can't read:

```

SELECT * 
FROM a 
WHERE a."size(kb)" > %(size(kb)_1)s
```

Immediate workaround, which will also make your code easier to use in any case, is to give the column a key:

     table = Table('test', MetaData(), Column(colname, Integer(), key="foo"), schema='public')
    engine.execute(select(['*']).where(table.c.foo > 1))

that way it will use "foo_1" as the parameter name and you also won't have to do that awkward getitem to get the column.

**Comment by zzzeek** [comment]
gracefully here may mean to emit an error or warning that suggests to use "key", or other anonymizing routine at least for anonymous bound parameters.   if a user uses such a key directly for bindparam() that still has to raise.

**Comment by zzzeek** [comment]
also this is kind of a psycopg2 bug - python string interpolation can handle it:

```
(Pdb) parameters
{'key(foo)_1': 1}
(Pdb) statement
'SELECT * \nFROM a \nWHERE a."key(foo)" > %(key(foo)_1)s'
(Pdb) statement % parameters
'SELECT * \nFROM a \nWHERE a."key(foo)" > 1'
(Pdb) cursor.execute(statement, parameters)
*** KeyError: 'key(foo'
(Pdb) 

```

**Comment by zzzeek** [comment]
https://github.com/psycopg/psycopg2/issues/167  "Issue solved by declaring in the docs that %, (, ) are not supported."  

http://initd.org/psycopg/docs/usage.html#query-parameters

I think this should be a rule in the base compiler in any case when paramstyle is pyformat, but also things like spaces in colon format, etc., probably should accommodate more generally.   this would likely mean most of Oracles parameter quoting wouldnt be needed.

**Comment by zzzeek** [comment]
we will look into this technique:

```
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index e395caeaa..cc0d314f2 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -139,6 +139,7 @@ RESERVED_WORDS = set(
 )
 
 LEGAL_CHARACTERS = re.compile(r"^[A-Z0-9_$]+$", re.I)
+ILLEGAL_CHARACTERS = re.compile(r"[^A-Z0-9_$]", re.I)
 LEGAL_CHARACTERS_PLUS_SPACE = re.compile(r"^[A-Z0-9_ $]+$", re.I)
 ILLEGAL_INITIAL_CHARACTERS = {str(x) for x in range(0, 10)}.union(["$"])
 
@@ -1549,6 +1550,13 @@ class SQLCompiler(Compiled):
         if isinstance(bind_name, elements._truncated_label):
             bind_name = self._truncated_identifier("bindparam", bind_name)
 
+            # work around characters derived from column names etc. that
+            # are usually quoted, but within the bound parameter they
+            # are not
+            bind_name = ILLEGAL_CHARACTERS.sub(
+                lambda m: str(ord(m.group(0))), bind_name
+            )
+
         # add to bind_names for translation
         self.bind_names[bindparam] = bind_name
 

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Strip special chars in anonymized bind names** https://gerrit.sqlalchemy.org/1450

**Comment by yyscamper** [comment]
> hi there -
> 
> that's not the correct compiled SQL, because you need to use the psycopg2 dialect to generate it. Here is the actual query that psycopg2 can't read:
> 
> ```
> 
> SELECT * 
> FROM a 
> WHERE a."size(kb)" > %(size(kb)_1)s
> ```
> 
> Immediate workaround, which will also make your code easier to use in any case, is to give the column a key:
> 
> ```
>  table = Table('test', MetaData(), Column(colname, Integer(), key="foo"), schema='public')
> engine.execute(select(['*']).where(table.c.foo > 1))
> ```
> 
> that way it will use "foo_1" as the parameter name and you also won't have to do that awkward getitem to get the column.

Adding a key for column is not an easy job in our project, because users directly touch the table original name, and the original name is widely used in a lot configuration. So adding a key means I  need to manually maintain a mapping between original name and key for each table.

**Comment by yyscamper** [comment]
> we will look into this technique:
> 
> ```
> diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
> index e395caeaa..cc0d314f2 100644
> --- a/lib/sqlalchemy/sql/compiler.py
> +++ b/lib/sqlalchemy/sql/compiler.py
> @@ -139,6 +139,7 @@ RESERVED_WORDS = set(
>  )
>  
>  LEGAL_CHARACTERS = re.compile(r"^[A-Z0-9_$]+$", re.I)
> +ILLEGAL_CHARACTERS = re.compile(r"[^A-Z0-9_$]", re.I)
>  LEGAL_CHARACTERS_PLUS_SPACE = re.compile(r"^[A-Z0-9_ $]+$", re.I)
>  ILLEGAL_INITIAL_CHARACTERS = {str(x) for x in range(0, 10)}.union(["$"])
>  
> @@ -1549,6 +1550,13 @@ class SQLCompiler(Compiled):
>          if isinstance(bind_name, elements._truncated_label):
>              bind_name = self._truncated_identifier("bindparam", bind_name)
>  
> +            # work around characters derived from column names etc. that
> +            # are usually quoted, but within the bound parameter they
> +            # are not
> +            bind_name = ILLEGAL_CHARACTERS.sub(
> +                lambda m: str(ord(m.group(0))), bind_name
> +            )
> +
>          # add to bind_names for translation
>          self.bind_names[bindparam] = bind_name
>  
> ```

I prefer this solution. This is transparent to sqlalchemy user, and no side effect for user's existing code.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Strip special chars in anonymized bind names** https://gerrit.sqlalchemy.org/1451
