### ISSUE TITLE
[documentation] Code sample fix

### ISSUE THREAD

**Issue by martinkirch** [sqlalchemy/sqlalchemy#4838]
It seems the documentation on [Using Connection Pools with Multiprocessing](https://docs.sqlalchemy.org/en/13/core/pooling.html#using-connection-pools-with-multiprocessing) contains an error in the code sample about instrumenting `Pool` (which works great, thanks !).

My experience suggests that `engine = create_engine("...")` triggered the `connect` event, so the listener was set up too late, resulting in a `KeyError` on `pid` on `checkout`.

I suggest to change this sample to :

```python
from sqlalchemy import event
from sqlalchemy import exc
from sqlalchemy.pool import Pool
import os

@event.listens_for(Pool, "connect")
def connect(dbapi_connection, connection_record):
    connection_record.info['pid'] = os.getpid()

engine = create_engine("...")

@event.listens_for(engine, "checkout")
def checkout(dbapi_connection, connection_record, connection_proxy):
    pid = os.getpid()
    if connection_record.info['pid'] != pid:
        connection_record.connection = connection_proxy.connection = None
        raise exc.DisconnectionError(
                "Connection record belongs to pid %s, "
                "attempting to check out in pid %s" %
                (connection_record.info['pid'], pid)
        )
```

**Comment by zzzeek** [comment]
hi there -

create_engine() does not do a connect().    can you illustrate how you were getting that result?

**Comment by martinkirch** [comment]
Ah, OK. I do the engine instanciation in a function that calls `engine_from_config`, then declarative_base.prepare(engine)` so I guess the connection starts because of the latter.
My bad !

**Comment by zzzeek** [comment]
oh yeah the prepare() uses the database for sure.
