### ISSUE TITLE
Does sqlalchemy support Apache Derby 

### ISSUE THREAD

**Issue by pingsutw** [sqlalchemy/sqlalchemy#4839]
I working on a project use Apache Derby as my database.
Dose sqlalchemy support Apache Derby or JDBC, so I could write data to Derby

**Comment by zzzeek** [comment]
Hi there-

I'm not aware of a SQLAlchemy driver for this database right now, it seems like it speaks DB2's language, so *perhaps* [ibm-db-sa](https://pypi.org/project/ibm-db-sa/) can interact with it, however it's likely that Derby has different syntaxes.

it looks like there are DBAPI drivers for Derby at least such as https://pypi.org/project/pydrda/ ; it is feasable that a Derby dialect could be built using a DBAPI such as this one however someone would have to pick that up as a project.

**Comment by pingsutw** [comment]
Thanks @zzzeek for the reply, I tried ibm-db-sa, but not work for me.
I want to use SQLAlchemy in my project, so hope SQLAlchemy support Derby soon.

**Comment by zzzeek** [comment]
OK sorry I can't help right now :(
