### ISSUE TITLE
Does it support AWS `rdsData.execute_statement` of 'boto3'?

### ISSUE THREAD

**Issue by iammaze** [sqlalchemy/sqlalchemy#4840]
Hi,
I'm using SQLAlchemy for couple of years. Recently I've completed a project using Flask and SQLAlchemy. But my client says **"don't connect to DB directly instead use AWS Secret Manager"**. So, I need to use the boto3 library to use `rdsData.execute_statement` function to execute Queries.

So, does SQL Alchemy support it? Or is there any event like `on_execute_query` so that I can use that? Or where should I modify to the source to execute SQL via `rdsData.execute_statement`?

Thanks in advance.

**Comment by zzzeek** [comment]
hi there -

I am not a regular AWS user so you need to provide context.     What kind of database connection is in use and what driver?    Where is the background that boto3 is required to establish a database connection ?

**Comment by iammaze** [comment]
@zzzeek
Actually we have a AWS RDS Serverless Aurora MySQL database. But the problem is, all the ports are blocked so, no one can connect to the MySQL using the direct approach. But we can use the AWS SDK to connect to the MySQL using AWS Secret Manager like this:

```
rdsData = boto3.client('rds-data')
result = rdsData.execute_statement(
  resourceArn="my-resource-arn",
  secretArn="my-secret-arn",
  database="database_name",
  sql="select * from users;"
)

print(result)
```
So, every queries has to be executed like this. Now, how can I modify SQLAlchemy to execute queries like this?

Is there any event / callback which can be used? Any library which can be used? Or even how to modify the source to do it? Which would be the best approach?

**Comment by iammaze** [comment]
@zzzeek
Sorry, I got my answer. Basically AWS SDK is not a proper DB object or we can not use the columns from the returned values. So, I guess I have to remove SQLAlchemy and use raw programming.

Thanks.
