### ISSUE TITLE
[question] prevent connection cursor being reused

### ISSUE THREAD

**Issue by mozartilize** [sqlalchemy/sqlalchemy#4841]
Hi, currently my web application executes queries to database via

```python
with engine.connect() as conn:
    result = conn.execute(...)
    rows = result.fetchall()
```

but sometimes with many requests to the server and `InterfaceError: cursor already closed` occurs so I think that sqlalchemy is reusing connection cursor here, isn't it?

If it's true, so is there anyway to prevent or handle this situation?

Thanks!

**Comment by zzzeek** [comment]
This error only occurs if there is a bug in the DBAPI driver or for some drivers if they are being used in a thread-unsafe manner.

Please provide complete details on database / driver in use, type of application container / framework / servers, threads/greenlets/etc, steps to reproduce, how reproducible, complete stack trace, etc.

**Comment by zzzeek** [comment]
also the answer is no, SQLAlchemy is not "reusing" a cursor.  it's valid to use a cursor repeatedly for multiple statements as long as one statement is handled at a time, however SQLAlchemy only invokes one statement per cursor, optionally fetches the rows if the cursor is a row-returning cursor, then closes it.   the error you see is usually when it is attempting to fetch rows on the cursor, and the cursor is in a state where there are no rows to fetch.   This indicates that cursor.description is not None but that fetchall() would raise this error which means the DBAPI cursor is in a broken state that can't be anticipated.

this is usually a bug seen with the MySQL drivers, guessing that's what you're using, but will wait for your response.

**Comment by mozartilize** [comment]
Hi, I'm using postgres and psycopg2 driver, I init sqlalchemy engine when django app ready, run on daphne server, actually I have a wrapper

```python
def run_query(query):
     with engine.connect() as conn:
        return conn.execute(...)
```

and then call `run_query(...).fetchall()` in other functions. Still I cant reproduce this issue on my own but obviously somewhere was closing the dbapi connection that leads to cursor closed too

**Comment by zzzeek** [comment]
OK, my previous answer was a little heavy on some MySQL assumptions, it is less likely that psycopg2 is malfunctioning or having a concurrency related issue, however there's no way I'm aware of to get this particular failure mode without interacting with the cursor directly, such as through an event hook or something.

stack trace would say a lot here.  if you don't have a stack trace then is the issue not reproducible ?

**Comment by mozartilize** [comment]
Hi, this is traceback i got from server which relates to sqlalchemy

```
Internal Server Error: /foo/bar
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1211, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1161, in _fetchall_impl
    return self.cursor.fetchall()
psycopg2.InterfaceError: cursor already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  [...]
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1216, in fetchall
    e, None, None, self.cursor, self.context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1211, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/result.py", line 1161, in _fetchall_impl
    return self.cursor.fetchall()
sqlalchemy.exc.InterfaceError: (psycopg2.InterfaceError) cursor already closed
(Background on this error at: http://sqlalche.me/e/rvf5)
```

**Comment by zzzeek** [comment]
OK what was the SQL query emitted for which it was trying to fetch these rows?

**Comment by zzzeek** [comment]
you can turn on SQL echoing with echo=True or logging.getLogger("sqlalchemy.engine").setLevel(logging.INFO) + logging setup

**Comment by mozartilize** [comment]
sorry but do you think sql query could cause the issue?

**Comment by zzzeek** [comment]
without further information it would be a primary suspect at the moment, sure

**Comment by zzzeek** [comment]
also what's this?
```

Traceback (most recent call last):
  [...]
```

I really need to see the whole thing to know what kind of operation this was, thanks

**Comment by mozartilize** [comment]
Hi, the thing that emitted is django code and my sql runner above. I think it not a problem.

Btw I've been thinking about deployment when it restarts the service and all database connections are gone. But if it can cause the issue, I'm quite sure it will raise `InterfaceError: Connection already closed` instead of cursor. But 2 days after the re-deployment the issue seems like not appear anymore.

I'll close it and investigate more. Thanks for your help.

**Comment by zzzeek** [comment]
restarting the database etc. will cause an error but not "connection already closed" upon fetchall(), unless in the very unlikely case that the database was stopped exactly after the SQL statement was emitted and right before it went to fetch results.    so if you are starting and stopping your database while the program is running hundreds of concurrent queries at full speed, then sure.   that wouldn't be so mysterious though.

**Comment by mozartilize** [comment]
Once database completely restart then I test my program. I'm using docker services so my app is isolated to database.
