### ISSUE TITLE
Can I represent multiple database schemas in one SQLAlchemy Metadata object?

### ISSUE THREAD

**Issue by pmantica1** [sqlalchemy/sqlalchemy#4844]
I am wondering because SQL Server allows querying across databases.

**Comment by zzzeek** [comment]
yes see the [schema](https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=schema#specifying-the-schema-name) argument

**Comment by pmantica1** [comment]
If I have multiple databases, how do you prevent there from being table name conflicts?

**Comment by pmantica1** [comment]
The keys in the metadata.tables field are the table names. Does this mean that some tables won't appear in the Metadata object if they have conflicting names with other tables?

**Comment by zzzeek** [comment]
Hi -

I would encourage you to try it out.     I think you'll find that basic issues like not overwriting table names and such has been considered :)

**Comment by zzzeek** [comment]
closing as this has been answered.
