### ISSUE TITLE
emit 2.0 deprecation warning when any implicit autocommit is used

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4846]
consider if we can leave "autocommit" as an execution option which unconditionally autocommits; but anytime we use the regex or check _should_autocommit and it returns True, emit the warning

**Comment by gordthompson** [comment]
re: doctest issue:

`test_core` already has a `@testing.emits_warning`

https://github.com/sqlalchemy/sqlalchemy/blob/fe772672b4fc00df0b66aca92e2092779a844a2d/test/base/test_tutorials.py#L92

When that is in place, `test_core` has 58 failures, most of them "RemovedIn20Warning" fails. If I comment out that line then there are *no* "RemovedIn20Warning" failures but there are 3 "statement has a cartesian" failures. The `emits_warning` decorator/function *looks* like it could take more than one string/regep, but a list or tuple of strings to match do not appear to be acceptable.

**Comment by zzzeek** [comment]
I would remove the argument altogether from testing.emits_warning() which will have it match all warnings for now.

**Comment by gordthompson** [comment]
@zzzeek - Done. Thanks!
