### ISSUE TITLE
Helpful error message for spelling mistake

### ISSUE THREAD

**Issue by jtrakk** [sqlalchemy/sqlalchemy#4847]
It seems to be a [common problem](https://stackoverflow.com/questions/29269695/python-sqlalchemy-attributeerror-neither-column-object-nor-comparator-obje/46538084#46538084) that people invoke `column()` instead of `Column()` and get a difficult error message. It would be helpful to have a suggestion in the error about what's wrong.

```py
In [4]: sa.Table('tbl', sa.MetaData(), sa.column(sa.Integer))                                                                                   
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py in __getattr__(self, key)
    716         try:
--> 717             return getattr(self.comparator, key)
    718         except AttributeError:

AttributeError: 'Comparator' object has no attribute '_set_parent_with_dispatch'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-4-a2782c1b9801> in <module>
----> 1 sa.Table('tbl', sa.MetaData(), sa.column(sa.Integer))

<string> in __new__(cls, *args, **kw)

~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py in warned(fn, *args, **kwargs)
    126                     )
    127 
--> 128             return fn(*args, **kwargs)
    129 
    130         doc = fn.__doc__ is not None and fn.__doc__ or ""

~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/schema.py in __new__(cls, *args, **kw)
    494             except:
    495                 with util.safe_reraise():
--> 496                     metadata._remove_table(name, schema)
    497 
    498     @property

~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py in __exit__(self, type_, value, traceback)
     66             self._exc_info = None  # remove potential circular references
     67             if not self.warn_only:
---> 68                 compat.reraise(exc_type, exc_value, exc_tb)
     69         else:
     70             if not compat.py3k and self._exc_info and self._exc_info[1]:

~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/util/compat.py in reraise(tp, value, tb, cause)
    151         if value.__traceback__ is not tb:
    152             raise value.with_traceback(tb)
--> 153         raise value
    154 
    155     def u(s):

~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/schema.py in __new__(cls, *args, **kw)
    489             metadata._add_table(name, schema, table)
    490             try:
--> 491                 table._init(name, metadata, *args, **kw)
    492                 table.dispatch.after_parent_attach(table, metadata)
    493                 return table

~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/schema.py in _init(self, name, metadata, *args, **kwargs)
    588         # initialize all the column, etc. objects.  done after reflection to
    589         # allow user-overrides
--> 590         self._init_items(*args)
    591 
    592     def _autoload(

~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/schema.py in _init_items(self, *args)
    105         for item in args:
    106             if item is not None:
--> 107                 item._set_parent_with_dispatch(self)
    108 
    109     def get_children(self, **kwargs):

~/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py in __getattr__(self, key)
    719             raise AttributeError(
    720                 "Neither %r object nor %r object has an attribute %r"
--> 721                 % (type(self).__name__, type(self.comparator).__name__, key)
    722             )
    723 

AttributeError: Neither 'ColumnClause' object nor 'Comparator' object has an attribute '_set_parent_with_dispatch'


```

**Comment by zzzeek** [comment]
how is this a common problem?

**Comment by zzzeek** [comment]
I'm not claiming that it's not just that I'd like to know how they are using "column" and not "Column" and also where you see that this is a common problem, I've never seen this mistake before.  Python is not type-checked and until we long term get pep -484 annotations in there will be no generalized solution for "object X was passed to a function that expected Y", there are millions of ways this can happen.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Catch set_parent_w_dispatch missing** https://gerrit.sqlalchemy.org/1455

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Catch set_parent_w_dispatch missing** https://gerrit.sqlalchemy.org/1456

**Comment by zzzeek** [comment]
the fix will alert for any non SchemaItem passed

**Comment by jtrakk** [comment]
Oops, I messed up the link in my original post, intended to show that it was a common problem.

**Comment by zzzeek** [comment]
nevermind it's appropriate to put an exception in this one anyway, i will note however that beginner users are still often tripped up by Python 3's nested exception display.  this will display the actual exception at the bottom of the trace.

**Comment by jtrakk** [comment]
I think the idea of `raise from` is to indicate a situation like this. [This change](https://gerrit.sqlalchemy.org/plugins/gitiles/sqlalchemy/sqlalchemy/+/7afcb39a962d383e5ba04179c1b13131fb08a787%5E%21/#F1) sets the `__context__`, while `raise from` sets `__cause__`, which I think is what we'd want here.

**Comment by zzzeek** [comment]
we don't have that in Python 2.    however, I'm suppoed to be using compat.raise_from_cause, moment

**Comment by zzzeek** [comment]
right, it's exactly the same jsut changes the language....woopee

**Comment by zzzeek** [comment]
there's really quite a lot of exceptions that need this done actually.   separate issue

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use compat.raise_from_cause() for re-raise of schema item error** https://gerrit.sqlalchemy.org/1457

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Use compat.raise_from_cause() for re-raise of schema item error** https://gerrit.sqlalchemy.org/1458
