### ISSUE TITLE
use suppress / "raise from None" on most exceptions

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4849]
e.g. all of these:

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/elements.py#L726

see #4847

**Comment by zzzeek** [comment]
this can be done pretty quickly by using this assertion:

```
def _assert_proper_exception_context(exception):
    """assert that any exception we're catching does not have a __context__
    without a __cause__.

    Python 3 will report nested as exceptions as "during the handling of
    error X, error Y occurred". That's not what we want to do.  we want
    these exceptions in a cause chain.

    """
    if util.py3k and exception.__context__ is not exception.__cause__:
        assert False, (
            "Exception %r was correctly raised but did not set contextual "
            "exception %r as its cause" % (exception, exception.__context__)
        )

```

I think I want to backport to 1.3 also.

**Comment by zzzeek** [comment]
`__suppress_context__` is way better for most of these where the original catch is just part of the normal control flow of the function and need not be exposed.  this also makes it behave the same as python 2.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure all nested exception throws have a cause** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1754

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Ensure all nested exception throws have a cause** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1755
