### ISSUE TITLE
util.callable is no longer necessary

### ISSUE THREAD

**Issue by sloria** [sqlalchemy/sqlalchemy#4850]
`util.callable` is a compatibility helper to support Python 3.2. Since Python 3.2 is no longer supported, it is no longer necessary.

https://github.com/sqlalchemy/sqlalchemy/blob/17b7b3027f0e994cf47bf5fa3e536d3971076dcd/lib/sqlalchemy/util/compat.py#L161-L166

**Comment by sqla-tester** [comment]
**Steven Loria** has proposed a fix for this issue in the **master** branch:

**Remove unnecessary util.callable usage** https://gerrit.sqlalchemy.org/1459
