### ISSUE TITLE
max_identifier_length should be 128 not 30 for Oracle if server_version_info >= (12,2)

### ISSUE THREAD

**Issue by amandeep-sharma** [sqlalchemy/sqlalchemy#4857]
Oracle database has increased maximum identifier length from 30 bytes to 128 bytes.

Change is straight forward, instead of setting **max_identifier_length = 30**;
add below statement in the initialize method
**self.max_identifier_length = 128 if self.server_version_info >= (12,2) else 30**
in the file /dialects/oracle/base.py

**Comment by cs2018ncsa** [comment]
i don't see any downside to allowing SQLAlchemy to take advantage of (relatively) newly available functionality in Oracle. The suggested fix checks for appropriate versions so I fail to see how this might break anything.

**Comment by zzzeek** [comment]
Suppose they have database migrations that create a constraint using a naming convention.  This naming convention generated a too-long name.   They ran the migrations on their Oracle database with SQLAlchemy 1.3 so it generated a name that was truncated to 30 characters and the constraint was created.

Now they upgraded their SQLAlchemy and they need to run a migration which will DROP this constraint.  The constraint has the identical name, however the newer SQLAlchemy no longer truncates the name and the migration fails since there is no such constraint.

Oracle does not have transactional DDL and this migration was right in the middle when everything failed, so now their database is in an undefined state and their production application is down.

Here is a demonstration:

```
from sqlalchemy import Column
from sqlalchemy import Index
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import Table
from sqlalchemy.dialects import oracle
from sqlalchemy.schema import CreateIndex
from sqlalchemy.schema import DropIndex


m = MetaData(naming_convention={"ix": "ix_%(column_0N_name)s"})

t = Table(
    "t",
    m,
    Column("some_column_name_1", Integer),
    Column("some_column_name_2", Integer),
    Column("some_column_name_3", Integer),
    Column("some_column_name_4", Integer),
    Column("some_column_name_5", Integer),
    Column("some_column_name_6", Integer),
)

ix = Index(
    None,
    t.c.some_column_name_1,
    t.c.some_column_name_2,
    t.c.some_column_name_3,
    t.c.some_column_name_4,
    t.c.some_column_name_5,
    t.c.some_column_name_6,
)

oracle_dialect = oracle.dialect()
print(CreateIndex(ix).compile(dialect=oracle_dialect))

# later

oracle_dialect = oracle.dialect()
oracle_dialect.max_identifier_length = 128
print(DropIndex(ix).compile(dialect=oracle_dialect))

```

name before the change:

`CREATE INDEX ix_some_column_name_1s_ddab ON t (some_column_name_1, some_column_name_2, some_column_name_3, some_column_name_4, some_column_name_5, some_column_name_6)
`

name after the change:

`DROP INDEX ix_some_column_name_1some_column_name_2some_column_name_3some_column_name_4some_column_name_5some_column_name_6
`

**Comment by zzzeek** [comment]
see also https://github.com/sqlalchemy/alembic/issues/351 which is related to the overall status that we haven't really figured out the naming convention + truncation thing yet.

**Comment by cs2018ncsa** [comment]
thanks for taking the time to write up an example. its clear to me now this isn't as simple as it first appears to be.

**Comment by zzzeek** [comment]
so yes, the naming constraints thing which I was trying to make easier with "naming conventions" has only shown to be and endless source of thorny problems.

in this case, the way to make this possible would be:

1. we make the "max_identifier_length" attribute configurable for all dialects.   that way any database that makes a change like this, someone can accommodate it within their application if they really need to.

2. we add version detection into the oracle dialect within 1.3.x, and if max_identifier_length is at 30, we emit a warning that this will be changing in 1.4, that they should likely set it to 128 and test their application and database migrations.

3. in 1.4 we actually set the max_identifier_length.

We at least should do step 1 above.   also note you can set the max_idenififier_length after the fact right now as I did above, "engine = create_engine(...);  engine.dialect.max_identifier_length = 128", so this can be worked around for now.

**Comment by zzzeek** [comment]
https://stackoverflow.com/questions/756558/what-is-the-maximum-length-of-a-table-name-in-oracle#comment93525107_756569

"It's actually based on the version in the compatible parameter. If you have a 12.2 DB with compatible set to 11.2.0, is still limits you to 30 chars."

**Comment by zzzeek** [comment]
here's the background on that: 

https://docs.oracle.com/en/database/oracle/oracle-database/12.2/upgrd/what-is-oracle-database-compatibility.html#GUID-7FCE8614-8163-4393-AE66-2ADD1F73934F

so i will also check that here.

changes like this are never simple.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add max_identifier_length parameter; warn for Oracle** https://gerrit.sqlalchemy.org/1487

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Add max_identifier_length parameter; warn for Oracle** https://gerrit.sqlalchemy.org/1488

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Change Oracle max_identifier_length to 128** https://gerrit.sqlalchemy.org/1489

**Comment by zzzeek** [comment]
more changesets to go

**Comment by zzzeek** [comment]
we forgot to put `__backend__` on the test and it fails on SQL server

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Fix max_identifier_length for SQL server** https://gerrit.sqlalchemy.org/1504

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix max_identifier_length for SQL server** https://gerrit.sqlalchemy.org/1505

**Comment by zzzeek** [comment]
this 100% failed; the parsing doesn't work and 1.3 is pushing out the 128 identifier length in any case.  release today ASAP
