### ISSUE TITLE
Row-Level Locking support for mysql 8. with_for_update(skip_locked)¶

### ISSUE THREAD

**Issue by sergey-gladkow** [sqlalchemy/sqlalchemy#4860]
Tried to use the [row-level locking](https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_row_lock), that is already [supported for PostgreSQL](https://docs.sqlalchemy.org/en/13/core/selectable.html#sqlalchemy.sql.expression.GenerativeSelect.with_for_update.params.skip_locked) and Oracle  specifically the function  **skip_locked**, but not supported for MySQL. Are there plans to implement this feature for MySQL?

**Comment by zzzeek** [comment]
hi there -

we rely on these reports to learn about these new use cases.  can you link me to MySQL's syntax?  do you have any interest in contributing to a PR ?  this is likely a one liner

**Comment by sergey-gladkow** [comment]
for example, there are two references with a description of the work.
this is an example by mysql:
`SELECT * FROM mydb.product WHERE p_cost = 30 FOR UPDATE SKIP LOCKED;`
https://www.percona.com/blog/2018/06/29/mysql8-hot-rows-with-nowait-skip-locked/
https://mysqlserverteam.com/mysql-8-0-1-using-skip-locked-and-nowait-to-handle-hot-rows/

**Comment by zzzeek** [comment]
this is a lot more than skip locked, mysql 8 is supporting FOR (UPDATE | SHARE) and OF, that's a lot of syntax:

https://dev.mysql.com/doc/refman/8.0/en/select.html

**Comment by zzzeek** [comment]
we have support for at least most of this, but im not sure what "LOCK IN SHARE MODE" vs. "FOR SHARE" means

**Comment by zzzeek** [comment]
ah OK:

> SELECT ... FOR SHARE is a replacement for SELECT ... LOCK IN SHARE MODE, but LOCK IN SHARE MODE remains available for backward compatibility. The statements are equivalent.

OK so if OF is not in use, then we should continue to render LOCK IN SHARE MODE for backwards compatibility

**Comment by sergey-gladkow** [comment]
> this is a lot more than skip locked, mysql 8 is supporting FOR (UPDATE | SHARE) and OF, that's a lot of syntax:
> 
> https://dev.mysql.com/doc/refman/8.0/en/select.html

so you think it's harder than you thought it would be at first?

**Comment by zzzeek** [comment]
no, this is not hard, just needs to cover all the bases and has tests.    here are examples:

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/oracle/base.py#L1007

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/base.py#L1681

MySQL's would kind of be a mix of those plus it would render "LOCK IN SHARE MODE" instead of "FOR SHARE" if there is no OF clause.

**Comment by zzzeek** [comment]
there seems to be some interesting difference in how OF is implemented for Postgresql vs. Oracle there which seems to be arbitrary.  PG's version accepts column objects, it seems.  same end result though, so maybe that code should be made more cross-consistent.

**Comment by saledan** [comment]
Hi,
any news about this feature?

**Comment by zzzeek** [comment]
someone named @saledan made a comment on it and...that's about it for news!   added some tags in case people want to work on this.

**Comment by sqla-tester** [comment]
**RobotScribe** has proposed a fix for this issue in the **master** branch:

**Add with_for_update mysql new functionalities** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1928

**Comment by sqla-tester** [comment]
**RobotScribe** has proposed a fix for this issue in the **rel_1_3** branch:

**Add with_for_update mysql new functionalities** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1936

**Comment by elipoultorak** [comment]
> OK so if OF is not in use, then we should continue to render LOCK IN SHARE MODE for backwards compatibility

It looks like the choice to use  "LOCK IN SHARE MODE" instead of "FOR SHARE" stops you from using NOWAIT and SKIP LOCKED.
Here is the official syntax for mysql:
```
[FOR {UPDATE | SHARE}
        [OF tbl_name [, tbl_name] ...]
        [NOWAIT | SKIP LOCKED]
      | LOCK IN SHARE MODE]
```
source: https://dev.mysql.com/doc/refman/8.0/en/select.html
So the only way to use SKIP LOCKED is with FOR SHARE. Any way this could be updated?

**Comment by CaselIT** [comment]
If something is not working correctly with the current implementation, please open a new issue
