### ISSUE TITLE
Find IDs from a list that don't exist in a table

### ISSUE THREAD

**Issue by radzak** [sqlalchemy/sqlalchemy#4864]
I'd like to check which IDs does not exist in a table. I found a post on [dba.stackexchange](https://dba.stackexchange.com/questions/141129/find-ids-from-a-list-that-dont-exist-in-a-table) that contains numerous solutions, however, I could only replicate one of them in SQLAlchemy (the one not using [`VALUES`](https://www.postgresql.org/docs/9.5/static/sql-values.html)):

```python
import uuid
from sqlalchemy import literal, func

ids = [
    uuid.UUID('0116f60b-1112-4358-8eb7-251ea2131f37'),
    uuid.UUID('ca1ec5c9-f90d-4325-9d7b-09da9badd8f5'),
    uuid.UUID('88420dc2-c2d5-45d8-8d9a-8e95eca86232')
]

q1 = db_session.query(func.unnest(ids))
q2 = db_session.query(Transaction.id)

invalid_ids = [str(uid) for uid, in q1.except_all(q2)]
```

However the query issued is:
```python
>>> print(q1.except_all(q2))
SELECT anon_1.unnest_1 AS anon_1_unnest_1 
FROM (SELECT unnest(%(unnest_2)s) AS unnest_1 EXCEPT ALL SELECT transactions.id AS transactions_id 
FROM transactions) AS anon_1
```

I'd like to have:
```python
SELECT unnest(%(unnest_2)s) AS unnest_1 EXCEPT ALL SELECT transactions.id AS transactions_id
FROM transactions
```

I have some questions:
1. How could I get rid of the outer select above?
2. What's the difference between `SELECT * FROM unnest(...) EXCEPT ALL ...` and `SELECT unnest(...) EXCEPT ALL ...`?
3. I saw your answer from late 2013 https://stackoverflow.com/a/18900176/4796844 about [`VALUES`](https://www.postgresql.org/docs/9.5/static/sql-values.html). Has it been integrated into SQLAlchemy or would I still need a recipe?
4. In my use case, can you see any benefits in using `VALUES` over `unnest()`?
5. In [this answer on SO](https://stackoverflow.com/a/19364694/4796844), I saw the following:
```
SELECT ip 
FROM   login_log l 
WHERE  NOT EXISTS (
   SELECT  -- SELECT list mostly irrelevant; can just be empty in Postgres
   FROM   ip_location
   WHERE  ip = l.ip
   );
```
I implemented it in the following fashion:
```python
>>> query = db_session.query('*').select_from(
...     func.unnest(ids).alias('uid')
... ).filter(
...     ~exists().where(Transaction.id == literal_column('uid'))
... )
>>> print(query)
SELECT * 
FROM unnest(%(unnest_1)s) AS uid 
WHERE NOT (EXISTS (SELECT * 
FROM transactions 
WHERE transactions.id = uid))
```
I also tried `db_session.query(func.unnest(ids).label('uid')).filter(~exists().where(Transaction.id == literal_column('uid'))).all()` but I think aliasing in `SELECT ... WHERE NOT` (without FROM) construct is not supported as I was getting `column "uid" does not exist` error.

I would be grateful for the support :) I really like SQLAlchemy, keep up the good work!

**Comment by zzzeek** [comment]
hi there -

there's a lot going on here, the recipe for values is at https://github.com/sqlalchemy/sqlalchemy/wiki/PGValues.   Here is the first SO answer using that recipe, which also needs one extra thing I will append to the wiki momentarily:

```
from sqlalchemy import Column
from sqlalchemy import column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import select
from sqlalchemy import Table
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql.expression import FromClause


class values(FromClause):
    named_with_column = True

    def __init__(self, columns, *args, **kw):
        self._column_args = columns
        self.list = args
        self.alias_name = self.name = kw.pop("alias_name", None)

    def _populate_column_collection(self):
        for c in self._column_args:
            c._make_proxy(self)

    @property
    def _from_objects(self):
        return [self]


@compiles(values)
def compile_values(element, compiler, asfrom=False, **kw):
    columns = element.columns
    v = "VALUES %s" % ", ".join(
        "(%s)"
        % ", ".join(
            compiler.render_literal_value(elem, column.type)
            for elem, column in zip(tup, columns)
        )
        for tup in element.list
    )
    if asfrom:
        if element.alias_name:
            v = "(%s) AS %s (%s)" % (
                v,
                element.alias_name,
                (", ".join(c.name for c in element.columns)),
            )
        else:
            v = "(%s)" % v
    return v


images = Table("images", MetaData(), Column("id", Integer))

e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
with e.connect() as conn:
    images.drop(conn, checkfirst=True)
    images.create(conn)

    conn.execute(images.insert(), [{"id": i} for i in (1, 2, 3, 4, 6, 8)])

    t = values([column("id", Integer)], (4,), (5,), (6,), alias_name='t')

    stmt = (
        select([t.c.id])
        .select_from(t.outerjoin(images, t.c.id == images.c.id))
        .where(images.c.id == None)
    )

    print(conn.execute(stmt).fetchall())

```

**Comment by zzzeek** [comment]
for SELECTing FROM a function, which is another thing that is mostly idiosyncratic to PostgreSQL, there is a list of recipes at #3566, such as the one at https://github.com/sqlalchemy/sqlalchemy/issues/3566#issuecomment-441931333 which talks about PG's "unnest" function.

**Comment by zzzeek** [comment]
SQL-wise I dont think it matters much.  I like "values" because it is clearer, I don't really use functions like "unnest" because they are too idiosyncratic.

for "values" we need to take stock of what databases support this construct right now so that the feature can be targeted at all of them equally.

**Comment by zzzeek** [comment]
values is also SQL standard per https://www.postgresql.org/docs/9.5/sql-values.html so , we should probably just implement this built in.   even though  only PG supports it, if it's SQL standard it can be in the base.   volunteers welcome I can walk through it.

**Comment by zzzeek** [comment]
I've added for #4868 for eventual inclusion of this recipe.     closing this for now.
