### ISSUE TITLE
Reflect Table without specifying the database

### ISSUE THREAD

**Issue by eavelardev** [sqlalchemy/sqlalchemy#4865]
I create my engine with:

```python
engine = create_engine('mysql+pymysql://root:mysqlpass@localhost', pool_recycle=3600)
conn = engine.connect()
```
How I can reflect specific table from a specific database? I tried this:

```python
meta = MetaData()
messages = Table('my_database.my_table', meta, autoload=True, autoload_with=engine)
```
but doesn't work because `SHOW CREATE TABLE my_database.my_table` doesn't work outside of a database. The next code works for example:

```python
result = conn.execute('select * from my_database.my_table')
for row in result:
    print(row)  
```
Any suggestions? I don't want to create another engine specifying the database.

**Comment by zzzeek** [comment]
this is not supported right now, the URL has to have a /dbname at the end of it.

**Comment by eavelardev** [comment]
Thank you @zzzeek  the schema argument was my solution.

**Comment by zzzeek** [comment]
ok great
