### ISSUE TITLE
select.column / select.with_only_columns / query.with_entities / query.add_columns ...

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4871]
add new methods and set up deprecations

select.column
query.add_entities
query.add_column
query.add_columns 

    --->    .add_columns

select.with_only_columns
query.with_entities

   --->  .with_columns

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**Unify Query and select() , move all processing to compile phase** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1599

**Comment by zzzeek** [comment]
there's nothing that needs to change here, Query is legacy and when we document setting up column collections with cross-references between legacy Query and select, we can refer to the two methods which are select.add_columns() and select.with_only_columns().
