### ISSUE TITLE
depreacte textual coercion in query

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4873]
e.g.

    q = sess.query("1")

that shoudn't be accepted.   1.4 will disallow this.

**Comment by zzzeek** [comment]
this continues from #4481 as we basically missed this one.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Deprecate plain string passed to session.query()** https://gerrit.sqlalchemy.org/1483
