### ISSUE TITLE
set up utf-8 directives for mysql-pyodbc

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#4876]
(Further to #4869, specifically [this comment](https://github.com/sqlalchemy/sqlalchemy/issues/4869#issuecomment-536322193).) 

I have been able to tweak the mysql+pyodbc dialect and requirements to eliminate most of the failures in the test suite (currently "Tests failed: 11, passed: 126, ignored: 133") but I have one more hurdle. It involves the Unicode encoding used by MySQL Connector/ODBC.

As explained in the pyodbc wiki [Unicode article](https://github.com/mkleehammer/pyodbc/wiki/Unicode#mysql-and-postgresql), MySQL ODBC tends to use UTF-8 exclusively while the default for pyodbc is UTF-16. The fix is to explicitly set the encoding after the Connection object is created, e.g.,

```python
# Python 3.x
cnxn = pyodbc.connect(connection_string)
cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
cnxn.setencoding(encoding='utf-8')
```

I have verified that with my current test setup the code ...

```python
import pyodbc

cnxn = pyodbc.connect("DSN=mysql_sqla")

# cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
# cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
# cnxn.setencoding(encoding='utf-8')

crsr = cnxn.cursor()

crsr.execute("CREATE TEMPORARY TABLE foo (txt varchar(255))")

txt = "Alors vous imaginez ma 🐍 surprise, au lever du jour, quand une drôle de petite 🐍 voix m’a réveillé."
crsr.execute("INSERT INTO foo (txt) VALUES (?)", txt)

result = crsr.execute("SELECT txt FROM foo").fetchval()
print(result)
```

... fails with ...

```
pyodbc.Error: ('HY000', "[HY000] [MySQL][ODBC 8.0(w) Driver][mysqld-5.7.27-0ubuntu0.18.04.1]Incorrect string value: '\\xF0\\x9F\\x90\\x8D s...' for column 'txt' at row 1 (1366) (SQLExecDirectW)")
```

... but if I uncomment the setdecoding/setencoding lines then the code works fine.

So, I'm looking for the hook in the mysql+pyodbc dialect where I can specify those additional post-connect directives.

Any pointers greatly appreciated.

**Comment by zzzeek** [comment]
hi Gord -

for this use case you make use of the [on_connect](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L315) default dialect method.

examples:

mysql-python: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/mysqldb.py#L120

psycopg2: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L776

SQL Server: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mssql/base.py#L2373

etc

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**add on_connect to MySQLDialect_pyodbc** https://gerrit.sqlalchemy.org/1531
