### ISSUE TITLE
deprecate case_sensitive engine flag

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4878]
Years ago, the lookup of columns in a RowProxy was case insensitive.    As this eventually led to problems, it was changed to be case sensitive, but a new flag case_sensitive=False was added to create_engine() to assist with backwards compatibility.   There are no known cases of anyone using this flag and it's time to remove it.  The internal implementation is fairly complicated as well.

**Comment by auvipy** [comment]
I would like to tackle this one as well if you allow

**Comment by zzzeek** [comment]
yaeh give it a shot

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use RowProxy for ORM keyed tuple** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1300
