### ISSUE TITLE
quoting is missing from the db name for SQL server switch db

### ISSUE THREAD

**Issue by pmantica1** [sqlalchemy/sqlalchemy#4883]
Doesn't this code snippet in `sqlachemy/dialects/mssql/base.py` allow for SQL injection?
```
def _switch_db(dbname, connection, fn, *arg, **kw):
    if dbname:
        current_db = connection.scalar("select db_name()")
        connection.execute("use %s" % dbname)
    try:
        return fn(*arg, **kw)
    finally:
        if dbname:
            connection.execute("use %s" % current_db)
```

**Comment by zzzeek** [comment]
only if you pass untrusted web input into a database reflection method like inspector.get_table_names() which I don't consider to be a valid use case

**Comment by zzzeek** [comment]
that said, this is an identifier name and it's not clear if it might need quoting for case sensitivity in any case, tt comes out of a token split, lets see if I can find that use case.

**Comment by zzzeek** [comment]
the documented use of this parameter is that the brackets may be explicit in the string passed in so that the owner/schema can be delineated.   have to work around that too.  https://docs.sqlalchemy.org/en/13/dialects/mssql.html#multipart-schema-names

**Comment by zzzeek** [comment]
so yeah I can't actually simulate untrusted input being able to break out of the quoting due to the split of "owner.schema" that occurs.   however, the final tokens should still be prepared as normal identifiers.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Apply quoting to SQL Server _switch_db** https://gerrit.sqlalchemy.org/1492

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Apply quoting to SQL Server _switch_db** https://gerrit.sqlalchemy.org/1493
