### ISSUE TITLE
remove join rewriting for older sqlite versions

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4895]
Running a centos 7.0 docker container, Python is at version 2.7.5 and the sqlite3 version is:

Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.7.17'

this is newer than the [3.7.16](https://www.sqlite.org/changes.html) required for direct support of right-nested joins so it seems likely that this rather complex pile of code is not being used anywhere, as SQLAlchemy only supports Python 2.7 and above.  centos6 has only python 2.6 (not supported) and no Python 3.

**Comment by zzzeek** [comment]
if we just flat out set minimum sqlite version at 3.7.16 we can remove a bunch of booleans, however if we don't do that, then when we detect less than 3.7.16, lets emit a warning that complex right nested joins are not supported.

**Comment by zzzeek** [comment]
it's useful to look at some historical issues for this, it seems it was in fact around 2013, 2014 that people were using this feature, #2969, #2790 #2858, #2967

**Comment by zzzeek** [comment]
#3057

**Comment by zzzeek** [comment]
stack trace in #3057 shows python 2.7 in use

**Comment by zzzeek** [comment]
#3130 - I also wonder if these issues are all things that don't actually need to rewrite right-nested joins

**Comment by zzzeek** [comment]
ahha, before #3634, we were doing the rewrite unconditionally, was not checking for sqlite version!  After that change, there were **no** further issues reported.   so this is an unused codepath.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Drop right-nested join rewrtigin** https://gerrit.sqlalchemy.org/1503

**Comment by zzzeek** [comment]
there's additionally a warning for pysqlite older than 2.1.3. The oldest pysqlite that exists on pypi is 2.5.5 which is from 2009, so will remove this warning also.

**Comment by zzzeek** [comment]
also..... pysqlite2 is only on Python 2, so we should not try to import it on python 3.

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**Backport pysqlite dialect modernizations** https://gerrit.sqlalchemy.org/1506
