### ISSUE TITLE
Pytest - psycopg DatatypeMismatch

### ISSUE THREAD

**Issue by oskaraliasfunky** [sqlalchemy/sqlalchemy#4901]
Hey, after updating SQLAlchemy from version 1.2.19 to 1.3.01b and running pytest on app, i have some problems with data insertion to table where i use CastingArray for JSON encoded field. 
The following error pops up: 
`sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "days" is of type json[] but expression is of type text[]
E       LINE 1: ...id, '2019-10-06'::date, '2019-10-13'::date, 14.0, ARRAY['{"d...
E                                                                    ^
E       HINT:  You will need to rewrite or cast the expression.`

Here is a code which i use 
```python
class JSONEncodedField(TypeDecorator):
    impl = JSON

    def process_bind_param(self, value: Field, dialect: Any) -> Dict:
        d: Dict[str, Any] = asdict(value)
        d["date"] = d["date"].isoformat()
        d["x_done"] = [str(x_pk) for x_pk in d["x_done"]]
        d["x_planned"] = [str(x_pk) for x_pk in d["x_planned"]]
        return d

    def process_result_value(self, value: Dict, dialect: Any) -> Field:
        return Field(
            date=date.fromisoformat(value["date"]),
            score=value["score"],
            current_streak=value["current_streak"],
            x_done=[
                UserXPk(uuid.UUID(x_pk)) for x_pk in value["x_done"]
            ],
            x_planned=[
                UserXPk(uuid.UUID(x_pk)) for x_pk in value["x_planned"]
            ],
        )

    def coerce_compared_value(self, op: Any, value: Any) -> Any:
        return self.impl.coerce_compared_value(op, value)
```
Can't find nothing related in Changelog, debugged code to find out if there are any types changes after update, but everything is same as before.

**Comment by zzzeek** [comment]
hi there -

there's no reason to run 1.3.0b1, that's an old beta release.    Can you please run 1.3.9 and provide a complete test case.    You likely will want to work from the one I've just made for you below, which runs without issue (that is, make the script below show your error):

```
from datetime import date
from typing import Any
from typing import Dict
import uuid

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import JSON
from sqlalchemy import TypeDecorator
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

class JSONEncodedField(TypeDecorator):
    impl = JSON

    def process_bind_param(self, value: Any, dialect: Any) -> Dict:
        d: Dict[str, Any] = dict(value)
        d["date"] = d["date"].isoformat()
        d["x_done"] = [str(x_pk) for x_pk in d["x_done"]]
        d["x_planned"] = [str(x_pk) for x_pk in d["x_planned"]]
        return d

    def process_result_value(self, value: Dict, dialect: Any) -> Any:
        return dict(
            date=date.fromisoformat(value["date"]),
            score=value["score"],
            current_streak=value["current_streak"],
            x_done=[uuid.UUID(x_pk) for x_pk in value["x_done"]],
            x_planned=[uuid.UUID(x_pk) for x_pk in value["x_planned"]],
        )

    def coerce_compared_value(self, op: Any, value: Any) -> Any:
        return self.impl.coerce_compared_value(op, value)


Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(JSONEncodedField)


e = create_engine("postgresql://scott:tiger@localhost/test", echo='debug')
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add(
    A(
        data={
            "date": date.today(),
            "score": 10,
            "current_streak": 15,
            "x_done": [uuid.uuid4(), uuid.uuid4()],
            "x_planned": [uuid.uuid4(), uuid.uuid4()],
        }
    )
)
s.commit()

a1 = s.query(A.data).first()

```

**Comment by oskaraliasfunky** [comment]
I already updated it to 1.3.9, by version 1.3.0b1 I meant that, between ver. 1.2.19 and 1.3.0b1 problem occured, This can help in locating the problem. I Find it hard to show you a test case based on my code, I can't capture it because of the extensive application architecture. Thought u can help me basing on operations which my code performs. I can provide u example input to function process_bind_param which is {'date': '2019-10-07', 'score': 84.73828517325926, 'current_streak': 6, 'x_done': [], 'x_planned': ['55d2cb51-3c36-4c78-bf9b-c5f489b8ee80', 'e47c3802-43a9-4e91-8a70-e1c34ff2a9b3', '1c84709e-d01d-4927-88d1-5ce93411a6c2']} and this is my Table representation in db `TABLE_NAME = Table(
    "table_name",
    METADATA,
    Column("pk", UUID(as_uuid=True), primary_key=True),
    Column(
        "user_pk", UUID(as_uuid=True), ForeignKey("users.pk"), nullable=False, index=True
    ),
    Column("start_date", Date, nullable=False),
    Column("end_date", Date, nullable=False),
    Column("y", Float, nullable=False),
    Column("days", CastingArray(JSONEncodedField)),
)`
Plus this is migration for that `op.create_table(
        "progress_intervals",
        sa.Column("pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_pk", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column(
            "days",
            CastingArray(postgresql.JSON(astext_type=sa.Text())),  # Changed
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_pk"], ["users.pk"]),
        sa.PrimaryKeyConstraint("pk"),
    )`

**Comment by zzzeek** [comment]
at least show the full stack trace and the complete SQL query and the parameters which should be printed out in the error message. I can probably work from that, and the test I gave you is not doing everything we could be doing with that datatype, like using it in a WHERE clause, etc..   the code you have looks fine so there should be nothing changing with it from 1.2 to 1.3.

**Comment by oskaraliasfunky** [comment]
Sure, here is full stack trace, edited post above to display whole migration ```
self = <sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 object at 0x7feaf96c7910>, cursor = <cursor object at 0x7feaf43bbe50; closed: -1>
statement = 'INSERT INTO table_name (pk, user_pk, start_date, end_date, goal, days) VALUES (%(pk)s, %(user_pk)s, %(start_date)s, %(end_date)s, %(y)s, %(days)s)'
parameters = {'days': ['{"date": "2019-10-07", "score": 99.38732397554081, "current_streak": 4, "x_done": [], "x_planned": ...date': datetime.date(2019, 10, 14), 'y': 85.10230083793961, 'pk': UUID('be825921-d7fe-49bd-8929-77111729edeb'), ...}
context = <sqlalchemy.dialects.postgresql.psycopg2.PGExecutionContext_psycopg2 object at 0x7feafa8c9490>

    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "days" is of type json[] but expression is of type text[]
E       LINE 1: ...07'::date, '2019-10-14'::date, 85.10230083793961, ARRAY['{"d...
E                                                                    ^
E       HINT:  You will need to rewrite or cast the expression.
E       
E       [SQL: INSERT INTO table_name (pk, user_pk, start_date, end_date, y, days) VALUES (%(pk)s, %(user_pk)s, %(start_date)s, %(end_date)s, %(y)s, %(days)s)]
E       [parameters: {'pk': UUID('be825921-d7fe-49bd-8929-77111729edeb'), 'user_pk': UUID('c80d2d6f-9019-4244-a15f-41dbadb2337e'), 'start_date': datetime.date(2019, 10, 7), 'end_date': datetime.date(2019, 10, 14), 'y': 85.10230083793961, 'days': ['{"date": "2019-10-07", "score": 99.38732397554081, "current_streak": 4, "x_done": [], "x_planned": ["6382506f-17ba-473e-a2b1-c82c45a6908b",  ... (1325 characters truncated) ... one": [], "x_planned": ["854ca865-2d0a-47d9-a9b2-e1f23949b652", "75c1ac64-6223-4983-86df-5ce5f1601558", "c25207c5-79d0-4a90-bd50-2c4b0db3993f"]}']}]
E       (Background on this error at: http://sqlalche.me/e/f405)

/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py:580: ProgrammingError```

**Comment by zzzeek** [comment]
what is CastingArray?  that looks like it's involved.  are you trying to store an ARRAY of JSON ?

**Comment by oskaraliasfunky** [comment]
Oh sorry for didn't mention it, this class is in same file as JSONEncodedField and it's a cast.

```python
class CastingArray(ARRAY):
    def bind_expression(self, bindvalue: Any) -> Any:
        return cast(bindvalue, self)
```

**Comment by zzzeek** [comment]
OK, so, just as a note for the future, this is a simple issue but if you can be able to give **all** of these details, that helps, including, 1. this is an INSERT statement 2. the full datatype is ARRAY of JSON, which is a very tricky datatype  3. here's the SQL that was emitted.  with that information given, even though it seems difficult to create a reproduction case, that's enough information so that I can make one very simply, here it is:

```
from datetime import date
from typing import Any
from typing import Dict
import uuid

from sqlalchemy import ARRAY
from sqlalchemy import cast
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import JSON
from sqlalchemy import TypeDecorator
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

class CastingArray(ARRAY):
    def bind_expression(self, bindvalue: Any) -> Any:
        return cast(bindvalue, self)

class JSONEncodedField(TypeDecorator):
    impl = JSON

    def process_bind_param(self, value: Any, dialect: Any) -> Dict:
        d: Dict[str, Any] = dict(value)
        d["date"] = d["date"].isoformat()
        d["x_done"] = [str(x_pk) for x_pk in d["x_done"]]
        d["x_planned"] = [str(x_pk) for x_pk in d["x_planned"]]
        return d

    def process_result_value(self, value: Dict, dialect: Any) -> Any:
        return dict(
            date=date.fromisoformat(value["date"]),
            score=value["score"],
            current_streak=value["current_streak"],
            x_done=[uuid.UUID(x_pk) for x_pk in value["x_done"]],
            x_planned=[uuid.UUID(x_pk) for x_pk in value["x_planned"]],
        )

    def coerce_compared_value(self, op: Any, value: Any) -> Any:
        return self.impl.coerce_compared_value(op, value)


Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(CastingArray(JSONEncodedField))


e = create_engine("postgresql://scott:tiger@localhost/test", echo='debug')
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add(
    A(
        data=[{
            "date": date.today(),
            "score": 10,
            "current_streak": 15,
            "x_done": [uuid.uuid4(), uuid.uuid4()],
            "x_planned": [uuid.uuid4(), uuid.uuid4()],
        }]
    )
)
s.commit()

a1 = s.query(A.data).first()

```
now what's going wrong between 1.2 and 1.3?   with echo=True / 'debug' turned on, we can see this immediately (you can do this in your application too), 1.2 is doing the CAST and 1.3 is not:

```
# 1.2
INSERT INTO a (data) VALUES (CAST(%(data)s AS JSON[])) RETURNING a.id

# 1.3
INSERT INTO a (data) VALUES (%(data)s) RETURNING a.id

```

now why is it doing *that* ?  at the moment I have no idea, so let me look in the migration notes to see if there was anything about INSERT and bind_expression.

OK so I see something has changed as we see here: https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#typeengine-methods-bind-expression-column-expression-work-with-variant-type-specific-types  and I'm going to guess that beacuse your CastingArray is using a straight subclass and not a TypeDecorator, that's why it isn't working.   you need to use TypeDecorator in order to augment the bind/column processing behavior of a type.  


```
class CastingArray(TypeDecorator):
    impl = ARRAY

    def bind_expression(self, bindvalue: Any) -> Any:
        return cast(bindvalue, self)

```

and now running again the CAST works in both cases.

**Comment by oskaraliasfunky** [comment]
Oh mate, I'm very grateful to you, as you say it works now. I will try to learn a lesson from this situation and, among other things, I will better present the problems. ;) Best regards for u and for your kitty from avatar.
