### ISSUE TITLE
pool_pre_ping not detecting dead connection for Firebird database

### ISSUE THREAD

**Issue by lukens** [sqlalchemy/sqlalchemy#4903]
The `is_disconnect()` method for Firebird dialects check for the following in the error message:

`"Unable to complete network request to host"`
`"Invalid connection state"`
`"Invalid cursor state"`
`"connection shutdown"`

However, the actual error I get is: `"Error writing data to the connection"`

**Comment by zzzeek** [comment]
yup, we have to add these now and again, intereting you're using the firebird dialect because im constantly wanting to get rid of it, but it would need to be taken over as a third party dialect by someone who wants to maintain it.

**Comment by zzzeek** [comment]
you're using the firebird dialect successfully with SQLAlchemy 1.3 ?

**Comment by sqla-tester** [comment]
**lukens** has proposed a fix for this issue in the **master** branch:

**added additional error message to is_disconnect() for Firebird dialects** https://gerrit.sqlalchemy.org/1512

**Comment by sqla-tester** [comment]
**lukens** has proposed a fix for this issue in the **rel_1_3** branch:

**added additional error message to is_disconnect() for Firebird dialects** https://gerrit.sqlalchemy.org/1513

**Comment by lukens** [comment]
> you're using the firebird dialect successfully with SQLAlchemy 1.3 ?

I'm using it via PugSQL, and only for a single query, and it's working for me.

I'm new to Firebird in my new job, and there do (understandably) seem to be limited tools and drivers that support it well (if at all).
