### ISSUE TITLE
isolation_level "phantom" behaviour

### ISSUE THREAD

**Issue by hyperknot** [sqlalchemy/sqlalchemy#4905]
I'm using SQLAlchemy Core with PostgreSQL 9.6 using psycopg2, all latest version.

My problem is that set_isolation_level works in a really strange way. In theory, when I call it, nothing should happen, as set_isolation_level(0) is the default value both confirmed by SQLAlchemy and 'show all' command.

Yet, I cannot run `CREATE INDEX CONCURRENTLY` in the default state, it terminates in a:
```
CREATE INDEX CONCURRENTLY cannot run inside a transaction block
```

However once I manually call `conn.connection.connection.set_isolation_level(0)`, it starts working, even though _nothing_ changed, I get the very same default values both in `get_isolation_level()` and `show all`. Still, there is a definite change from this command as `CREATE INDEX CONCURRENTLY` now works.

The example code better illustrates what is happening.

```
with pg_engine.connect() as conn:
    print(conn.get_isolation_level())
    res = conn.execute('show all').fetchall()
    for r in res:
        if 'isolation' in r[0]:
            print(r)

    conn.execute("CREATE INDEX CONCURRENTLY ON tbl (col1)")
     # ^^^^^ this breaks with 
     # sqlalchemy.exc.InternalError: (psycopg2.errors.ActiveSqlTransaction) CREATE INDEX CONCURRENTLY cannot run inside a transaction block

    conn.connection.connection.set_isolation_level(0)

    print(conn.get_isolation_level())
    res = conn.execute('show all').fetchall()
    for r in res:
        if 'isolation' in r[0]:
            print(r)

    conn.execute("CREATE INDEX CONCURRENTLY ON tbl (col1)")
    # this runs fine (if the first one is commented out)
```

The normal output of the script (confirming nothing changed, in theory):
```
READ COMMITTED
('default_transaction_isolation', 'read committed', 'Sets the transaction isolation level of each new transaction.')
('transaction_isolation', 'read committed', "Sets the current transaction's isolation level.")
READ COMMITTED
('default_transaction_isolation', 'read committed', 'Sets the transaction isolation level of each new transaction.')
('transaction_isolation', 'read committed', "Sets the current transaction's isolation level.")
```

**Comment by hyperknot** [comment]
> You may want to add an `echo=True` kwarg to your `create_engine` call as it may let you see what statements are actually being sent to the server.

I'm testing it with that and it shows absolutely nothing at all for the isolation level change, nor for the lines before and after.

**Comment by zzzeek** [comment]
this script runs for me without error:

```
from sqlalchemy import create_engine

pg_engine = create_engine("postgresql://scott:tiger@localhost/test", echo=True)

with pg_engine.connect() as conn:
    conn.execute("drop table if exists tbl")
    conn.execute("create table tbl (col1 integer)")

with pg_engine.connect().execution_options(
    isolation_level="AUTOCOMMIT"
) as conn:

    print(conn.get_isolation_level())
    res = conn.execute("show all").fetchall()
    for r in res:
        if "isolation" in r[0]:
            print(r)

    conn.execute("CREATE INDEX CONCURRENTLY ON tbl (col1)")

```

note that there is no "autocommit" isolation level in Postgresql, this is a psycopg2-specific construct so you won't see it using get_isolation_level() or "show all" (not familiar with what that is, but the database itself knows nothing about autocommit).

**Comment by hyperknot** [comment]
I'm on 1.3.10.

[PostgreSQL's Transaction Isolation](https://www.postgresql.org/docs/12/transaction-iso.html) offers the same 4 modes as in SQLAlchemy [docs](https://docs.sqlalchemy.org/en/13/dialects/postgresql.html?highlight=set_isolation_level#transaction-isolation-level), except for autocommit. When I set to one of the 4 modes, like `execution_options(isolation_level="READ UNCOMMITTED")`, `show all` also changes (actually `show transaction_isolation` is what we need here).

So this leaves autocommit to be the object of my confusion. It is, especially because 

`execution_options(autocommit=True)` and `execution_options(isolation_level="AUTOCOMMIT")` seem to be totally different. 

So just to confirm, the following two are doing the same?
```
conn.connection.connection.set_isolation_level(0)
conn = conn.execution_options(isolation_level="AUTOCOMMIT")
```

While autocommit=True is actually "force commit command in SQLAlchemy, even if regex didn't match?"
```
conn = conn.execution_options(autocommit=True)
```

It'd be great to have "AUTOCOMMIT" do some kind of feedback, right now the only possible hint about this state is: `conn.connection.connection.autocommit == True`

I think if setting the isolation level is supported in psycopg2 specific way, then get_isolation_level() should also support this value, in a psycopg2 specific way. I don't know the internals of psycopg2 but possibly `conn.connection.connection.autocommit == True` can be used for this?

**Comment by zzzeek** [comment]
> I'm on 1.3.10.
> 
> [PostgreSQL's Transaction Isolation](https://www.postgresql.org/docs/12/transaction-iso.html) offers the same 4 modes as in SQLAlchemy [docs](https://docs.sqlalchemy.org/en/13/dialects/postgresql.html?highlight=set_isolation_level#transaction-isolation-level), except for autocommit. When I set to one of the 4 modes, like `execution_options(isolation_level="READ UNCOMMITTED")`, `show all` also changes (actually `show transaction_isolation` is what we need here).
> 
> So this leaves autocommit to be the object of my confusion. It is, especially because
> 
> `execution_options(autocommit=True)` and `execution_options(isolation_level="AUTOCOMMIT")` seem to be totally different.

absolutely, those are two different things, although they do the same "thing" just at different levels, which is, they deal with the DBAPI connection as far as whether or not  BEGIN and COMMIT are sent to the database.   The autocommit=True option is going to be removed in SQLAlchemy 2.0.


> 
> So just to confirm, the following two are doing the same?
> 
> ```
> conn.connection.connection.set_isolation_level(0)
> conn = conn.execution_options(isolation_level="AUTOCOMMIT")

they do the same set_isolation_level() call on the DBAPI connection but the latter will additionally revert that isolation level on the connection when it is checked back into the connection pool, which is pretty important.


> ```
> 
> While autocommit=True is actually "force commit command in SQLAlchemy, even if regex didn't match?"

yes that's what that does.  

> 
> ```
> conn = conn.execution_options(autocommit=True)
> ```
> 
> It'd be great to have "AUTOCOMMIT" do some kind of feedback, right now the only possible hint about this state is: `conn.connection.connection.autocommit == True`

AUTOCOMMIT is different from the other isolation levels in that the other ones may be set on a postgresql database session when you first connect.  this will never be the case for AUTOCOMMIT, which is not actually an "isolation level".   it is something that can be set while coexisting with the other isolation levels, that is, you can be in AUTOCOMMIT and REPETABLE READ at the same time, because AUTOCOMMIT just means the driver didn't emit BEGIN.   I can see how reading it is useful for debugging as you did here but otherwise reading it is not really the same thing.  I'd have to add a whole new accessor that would be for just this purpose as well as a new state variable since this setting is not tracked.

> 
> I think if setting the isolation level is supported in psycopg2 specific way, then get_isolation_level() should also support this value, in a psycopg2 specific way.

get_isolation_level() asks the database, not the driver, for the isolation level.   The database doesn't know this information.    An application might want to know what the real isolation level is, if they want to emit the BEGIN statement.   There would need to be a new accessor that retrieves driver level isolation.   PRs welcome with tests and documentation.


> I don't know the internals of psycopg2 but possibly `conn.connection.connection.autocommit == True` can be used for this?

well I would tell you to read the .isolation_level attribute:

http://initd.org/psycopg/docs/connection.html?highlight=isolation_level#connection.isolation_level

however they have made the same change as I did apparently:

> This value is now entirely separate from the autocommit property: in previous version, if autocommit was set to True this property would have returned ISOLATION_LEVEL_AUTOCOMMIT; it will now return the server isolation level.

aaannnnddddd...it looks like they have walked back the whole concept of autocommit being an isolation level:

>  set_isolation_level(level)
>    This is a legacy method mixing isolation_level and autocommit. Using the respective properties is a better option. 

I likely was following their lead when this was made to work like this.     So this looks like another refactor and upgrade path that would have to happen someday to have a brand new "set / get DBAPI level autocommit" feature on the Connection, but at the moment the fact that we have our own "autocommit" which needs to go away is likely a reason to not keep messing with it.

**Comment by zzzeek** [comment]
as far as the issue here, your original statement doesn't make sense to me, even given the idea that get_isolation_level() / set_isolation_levelI() will show autocommit

> "as set_isolation_level(0) is the default value both confirmed by SQLAlchemy and 'show all' command."

the script above shows me the words "READ COMMITTED", not "0", the output is:

```
READ COMMITTED
('default_transaction_isolation', 'read committed', 'Sets the transaction isolation level of each new transaction.')
('transaction_isolation', 'read committed', "Sets the current transaction's isolation level.")

```

in psycogp2, READ COMMITTED is isolation level 1:

```
>>> import psycopg2.extensions as ext
>>> ext.ISOLATION_LEVEL_AUTOCOMMIT
0
>>> ext.ISOLATION_LEVEL_READ_COMMITTED
1

```

**Comment by hyperknot** [comment]
I think I understand the points now.

1. I need to use `autocommit=True` now (for non-regex detected text queries), but this will change in SQLAlchemy 2.0
2. The right way to make queries like "CREATE INDEX CONCURRENTLY" work is to use `isolation_level="AUTOCOMMIT"`, as it will take care of resetting the connection.
3. `set_isolation_level(0)` didn't cause any issues for me only because these special queries were only used in purpose built scripts running in cron jobs, where the script terminates so there is no "next" connection.
4. isolation_level="AUTOCOMMIT" will also change in the future, as it was just a bad, legacy decision on psycopg2 side.

The original issue didn't make sense to you, because I thought that the default must be 0, as setting it to 0 didn't change the get_isolation_level() constant. I didn't check what was 0 in the source code.

On my side everything is clear now, and thank you for the detailed explanation. Hopefully this will be found by Google over other places, which still recommend `set_isolation_level(0)` usually.

**Comment by zzzeek** [comment]
so yes, getting rid of "autocommit=True" is part of trying to pare down all the possibilities with the Core API, which has too much emphasis on saving a few lines of typing at the expense of confusing everyone.    In 2.0, it will be only like this:

```
with engine.begin() as conn:
    conn.execute("stmt")

# or for conditional commit, something like this

with engine.connect() as conn:
    conn.execute("Stmt")
    conn.rollback()
    conn.execute("Stmt")
    conn.commit()

```

that is, there's no `engine.execute(stmt)`, no `stmt.execute()`, all those alternate patterns that brought about the need for "autocommit" all go away and things will be much easier to understand.

**Comment by hyperknot** [comment]
Oh, that looks like a very nice improvement!

**Comment by sumau** [comment]
In 2.0 will you still have execution_options as the executable level, or is just 'autocommit' that will be removed e.g. :

`with engine.connect() as conn:
    conn.execute("Stmt")
    conn.rollback()
    conn.execute("Stmt").execution_options(stream_results=True)
    conn.commit()`

**Comment by zzzeek** [comment]
execution_options() will be there, certainly, it has many uses and is open-ended for any user defined purpose.

in your example above, conn.execute() returns a result set so you wouldn't call execution options from that.

**Comment by sumau** [comment]
Thanks! And corrected my mistake for clarification :-)

**Comment by zzzeek** [comment]
this is all stuff on the path to greater clarity.   closing this issue for now.
