### ISSUE TITLE
Inconsistent behaviour when creating buffered ResultProxy with isolation_level=AUTOCOMMIT

### ISSUE THREAD

**Issue by sumau** [sqlalchemy/sqlalchemy#4909]
The following raises 'sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't use a named cursor outside of transactions' 👍 

`from sqlalchemy import create_engine`
`my_engine = create_engine('postgresql://postgres:***@localhost:5432/dev')`
`conn = my_engine.connect()`
`buff_auto_conn = conn.execution_options(stream_results=True,isolation_level='AUTOCOMMIT')`
`#buff_conn = buff_auto_conn.execution_options(isolation_level='READ COMMITTED')`
`#del buff_conn`
`s = buff_auto_conn.execute('select 1;')`

However if you uncomment the lines and re-run the error isn't raised

**Comment by zzzeek** [comment]
Hi there -

Nothing here is unexpected so which part to you consider to be the bug?

1. that you can't use stream results and autocommit isolation at the same time? this is a limitation of the Postgresql API that named cursors have to be inside a transaction, no bug in SQLAlchemy

2. that changing the isolation to READ COMMITTED makes the error go away?   the isolation_level exectution option is [documented](https://docs.sqlalchemy.org/en/13/core/connections.html?highlight=execution_options#sqlalchemy.engine.Connection.execution_options.params.isolation_level) as taking effect for the lifespan of the originating Connection object, so this is documented, can make the wording more clear if that's the issue.

**Comment by sumau** [comment]
Thanks for the quick response! So just to be clear in my head:

1.  'originating' and 'underlying' mean the same thing and refer to the connection being copied (buff_auto_con in example above)
2.  Setting the isolation_level changes the isolation level of both the "underlying" and "copied" connections (buff_auto_con and buff_con)
3. Deleting the "copied" connection does not reset the isolation level of the "underlying" connection to its original isolation_level

NOTE There is a new withhold parameter introduced in 2.4.3 that would allow for using named cursors outside of a transaction but not sure if it's high priority:
http://initd.org/psycopg/docs/cursor.html#cursor.withhold

**Comment by zzzeek** [comment]
those points would be correct.  there is only one DBAPI connection in play in your example, so to that extent, the semantics of execution_options() in that a new Connection wrapper is returned is misleading.

**Comment by zzzeek** [comment]
the docs are not very good here i will grant.   all of these docs come out badly the first time around.

**Comment by sumau** [comment]
How about changing it to:

Available on: Connection. Set the transaction isolation level _of the underlying DBAPI [connection](https://docs.sqlalchemy.org/en/13/core/connections.html?highlight=execution_options#sqlalchemy.engine.Connection.connection)_ for the lifespan of the Connection object ~~(not the underlying DBAPI connection, for which the level is reset to its original setting upon termination of this Connection object).~~
This setting is ~~not~~ removed ~~until~~ only when the underlying DBAPI connection is returned to the connection pool, i.e. the Connection.close() method is called. Deleting the Connection object will **not** reset the setting of the underlying DBAPI connection.
Valid values include those string values accepted by the create_engine.isolation_level parameter passed to create_engine(). These levels are semi-database specific; see individual dialect documentation for valid levels.
~~Note that this option necessarily affects the underlying DBAPI connection for the lifespan of the originating Connection, and is not per-execution. This setting is not removed until the underlying DBAPI connection is returned to the connection pool, i.e. the Connection.close() method is called.~~

**Comment by zzzeek** [comment]
that's better, I want to more explicitly address that the second "Connection" object is not special here also.
