### ISSUE TITLE
CompileError when updating object

### ISSUE THREAD

**Issue by jonathanunderwood** [sqlalchemy/sqlalchemy#4911]
```python
class TeamMembership(Base):
    user_id = Column(Integer, ForeignKey("user.id"), primary_key=True)
    team_id = Column(Integer, ForeignKey("team.id"), primary_key=True)
    role = Column(String(20))

    user = relationship("User", back_populates="user_teams")
    team = relationship("Team", back_populates="team_members")


class User(Base):
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, unique=True)
    first_name = Column(String)
    last_name = Column(String)
    department = Column(String)
    email = Column(String, unique=True)
    last_login = Column(DateTime, default=None)
    active = Column(Boolean, default=True)

    user_teams = relationship(
        "TeamMembership", back_populates="user", cascade="all, delete-orphan"
    )
    teams = association_proxy(
        "user_teams", "team", creator=lambda team: TeamMembership(team=team)
    )


class Team(Base):
    id = Column(Integer, primary_key=True, index=True)
    team_id = Column(String, unique=True)
    name = Column(String, unique=True)
    description = Column(String)

    team_members = relationship(
        "TeamMembership", back_populates="team", cascade="all, delete-orphan"
    )
    members = association_proxy(
        "team_members", "user", creator=lambda user: TeamMembership(user=user)
    )

session=Session()

u = User(user_id="pll750", first_name="Jim", last_name="Junk", email="junk@junk.com")
session.add(u)
session.commit()

u = session.query(User).filter(User.user_id == "pll750").first()
u.active = False
session.commit()

[...]

CompileError: bindparam() name 'user_id' is reserved for automatic usage in the VALUES or SET clause of this insert/update statement.   Please use a name other than column name when using bindparam() with insert() or update() (for example, 'b_user_id').

```

Maybe related to #1755, though that has been closed, presumably fixed.

**Comment by jonathanunderwood** [comment]
This is with: 

```python
sqlalchemy.__version__
'1.3.10'
```

**Comment by jonathanunderwood** [comment]
Also, this is with psycopg2/postgresql.

**Comment by jonathanunderwood** [comment]
Also, this is with this definition of Base:

```python
from sqlalchemy.ext.declarative import declarative_base, declared_attr
from sqlalchemy import inspect

class CustomBase:
    # Generate __tablename__ automatically
    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower()

    def as_dict(self):
        """Return a dict representation of the ORM model

        """
        d = {c.key: getattr(self, c.key) for c in inspect(self).mapper.column_attrs}
        return d


Base = declarative_base(cls=CustomBase)
```

**Comment by jonathanunderwood** [comment]
Changing the tablename attribute in `CustomBase` to this:

```python
    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower() + "_t"
```

and changing the `ForeignKey` table references in `TeamMembership` fixes the problem. So, this is some variant of #1755, but which only seems active when ForeignKey is being used - looks like the fix to #1755 isn't complete.

**Comment by zzzeek** [comment]
the bug is in Core and is unrelated to the foreign key.   You can work around it for now by removing index=True from your primary key column.  Primary key columns are always indexed so there is no need to apply an explicit Index to this column.  However, if you do want to do this anyway, you can work around the issue a second way by not using the "index=True" flag and instead using "Index("user_id_idx", User.id)".

the use of index=True is causing a cached label on the Column to be generated too early which the ORM then uses to create a bound parameter of a name which conflicts with that given.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use deferred none name for index=True, unique=True** https://gerrit.sqlalchemy.org/1517

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Use deferred none name for index=True, unique=True** https://gerrit.sqlalchemy.org/1518

**Comment by zzzeek** [comment]
this unfortunately cannot be fixed for 1.3 because Alembic relies too heavily on the current logic.    Just remove the index=True for now, you don't need it on primary key columns.

**Comment by jonathanunderwood** [comment]
Ok, will do. Thanks for the quick response.

**Comment by jonathanunderwood** [comment]
Have confirmed, removing `index=True` stops the problem from occuring. I wonder if there's a "dirty fix" for 1.3 that simply ignored the `index` keyword if the `primary_key` keyword is set to `True`.

Thanks again for your help with this, it was a head scratcher.

**Comment by zzzeek** [comment]
Haven't had any margaritas yet today and I may have thought of a different way to resolve this in 1.3 / 1.4 for now, ill see if i can get to it in a few.

**Comment by zzzeek** [comment]
took a different path and it's in for 1.3 also

**Comment by jonathanunderwood** [comment]
Awesome. Margaritas are the secret sauce of SQLAlchemy? :)
