### ISSUE TITLE
Missing NCHAR type mapping for colspec in cx_oracle dialect

### ISSUE THREAD

**Issue by agilevic** [sqlalchemy/sqlalchemy#4913]
In order for the so-called blank-padded comparison semantics to work with parameter binding we had to monkey-patch SQLAlchemy as follows. 

```
from sqlalchemy.dialects.oracle import cx_oracle
from sqlalchemy.sql import sqltypes

class _OracleNChar(sqltypes.NCHAR):
    def get_dbapi_type(self, dbapi):
        return dbapi.FIXED_NCHAR

cx_oracle._OracleNChar = _OracleNChar
cx_oracle.dialect.colspecs[sqltypes.NCHAR] = _OracleNChar
```

We believe you may be missing a mapping for the Oracle's NCHAR type, which cx_Oracle DBAPI defines as FIXED_NCHAR. Corresponding mapping for the CHAR (cx_Oracle.FIXED_CHAR) does exist in SQLAlchemy (sqltypes._OracleChar).

This was first reported on the discussion at
https://groups.google.com/forum/#!topic/sqlalchemy/c8JAt-w03qU

See also: https://github.com/oracle/python-cx_Oracle/issues/365

**Comment by zzzeek** [comment]
luckily we already have a test against CHAR which proves the need for cx_Oracle.FIXED_CHAR and it works for this one as well

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use cx_Oracle.FIXED_NCHAR for sqltypes.NCHAR** https://gerrit.sqlalchemy.org/1521

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Use cx_Oracle.FIXED_NCHAR for sqltypes.NCHAR** https://gerrit.sqlalchemy.org/1522
