### ISSUE TITLE
Passing None to query(...).get(__) results in TypeError

### ISSUE THREAD

**Issue by lizraeli** [sqlalchemy/sqlalchemy#4915]
Passing `None` to `query.get()`, i.e.:
```python
self.db.session.query(...).get(None)
```
results in a TypeError in [query.py#L955](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/query.py#L955):
```python
if len(primary_key_identity) != len(mapper.primary_key):
```
Prior to this check, the `primary_key_identity` is reassigned based on the return value of passing it to `to_list`:
 ```python
        if not is_dict:
            primary_key_identity = util.to_list(primary_key_identity)
```
However, `to_list` returns the default value of `None` if `None` is passed as the argument. In [_collections.py#L802](https://github.com/sqlalchemy/sqlalchemy/blob/885f15a306efc4c907ca82fa13871992ee556466/lib/sqlalchemy/util/_collections.py#L802)
```python
def to_list(x, default=None):
    if x is None:
        return default
    ...
```
I believe it may be worth either explictly checking if `primary_key_identity ` is `None`, or passing an empty list as the `default` value when calling `util.to_list`

**Comment by zzzeek** [comment]
What behavior would you expect if None is passed to get()?   I think it should raise InvalidRequestError in any case because a NULL primary key is not supported.

**Comment by lizraeli** [comment]
@zzzeek I think InvalidRequestError would be appropriate. Should I make a PR adding a `None` check and raising this exception?

**Comment by sqla-tester** [comment]
**lizraeli** has proposed a fix for this issue in the **master** branch:

**Raise InvalidRequestError when `get` is called with None** https://gerrit.sqlalchemy.org/1536

**Comment by zzzeek** [comment]
change in plans, since you can do query.get((None, None)) and it does *not* raise an error right now, is that all get(None) get((None, )) get((None, None)) will handle the "None" s as values in a consistent fashion and emit a warning that we may turn to an error in a future major release.

**Comment by sqla-tester** [comment]
**lizraeli** has proposed a fix for this issue in the **rel_1_3** branch:

**Correctly interpret None passed to query.get(); warn for empty PK values** https://gerrit.sqlalchemy.org/1552
