### ISSUE TITLE
Space and enter causing issue

### ISSUE THREAD

**Issue by pratik217** [sqlalchemy/sqlalchemy#4924]
User entered space and enter which results in query error

**Comment by gordthompson** [comment]
Please provide more details about what you are trying to accomplish, preferably including a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by pratik217** [comment]
Application using Angular5, flask as backend, sqlalachemy as Orm and MySQL. As db.

If a user enters "abc(space)(enter)def" in Html text area. It get saved in MySQL through orm. But it is unable to fetch from MySQL. 
Maybe not supporting issue?


Note. This is my initial analysis, maybe any limitations

**Comment by gordthompson** [comment]
You say that you get a "query error". Please post the complete stack trace.

**Comment by zzzeek** [comment]
hi please reopen if you can provide a proper [mcve](http://stackoverflow.com/help/mcve) , we unfortunately do not have the resources to debug an HTML web application in this forum.
