### ISSUE TITLE
use truediv for /, floordiv for // regarding numeric results

### ISSUE THREAD

**Issue by bgedik** [sqlalchemy/sqlalchemy#4926]
I have the following example:

from sqlalchemy import Column, Integer, MetaData, Table, select

```
metadata = MetaData()
test = Table("test", metadata, Column("id", Integer))
query = select(columns=[(test.c.id / 2).label("half_id")])
print("the type of the 'half_id' column is", query.c.half_id.type)

query = select(columns=[(test.c.id / 2.0).label("half_id")])
print("the type of the 'half_id' column is", query.c.half_id.type)
```

This prints `INTEGER` and `FLOAT`. The latter is correct, but the former is incorrect. 

Dividing 1 by 2 via / gives me 0.5 in MariaDB and Oracle and 0 in Postgres and MSSQL.

I was expecting column type derivation to follow the Python 3 rules in this case: / is a floating point division.

**Comment by zzzeek** [comment]
Numeric is the generic decimal-point base type so that is what will be returned if there is no explicit Float type present.

which leads us to what is the actual problem you are having ?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Integer Integer division should produce Numeric** https://gerrit.sqlalchemy.org/1529

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Integer Integer division should produce Numeric** https://gerrit.sqlalchemy.org/1530

**Comment by bgedik** [comment]
I assume you answered the question yourself: It does not come up as Numeric, but as Integer.

**Comment by zzzeek** [comment]
That is not what I'm asking.   I am asking how does this issue impact what it is you are trying to accomplish, that is, what is your use case.  this informs how I will approach fixing this and testing it.      I'm looking for that you have driver specfic issues here that is causing you to get the wrong result, like Oracle or SQL server.    these details would better inform me if this should be a Float or Numeric, since they have different result set behaviors.  thanks for assisting.

**Comment by bgedik** [comment]
My use case is to understand the type of a column expression. I have an API that takes an SQLAlchemy query as input and I need to introspect the column types in the query and to do some validation.

In this particular case, someone is passing me an SQLAlchemy query that has a column like `(some_int_attribute / some_int_attribute).label("foo")`. I look at this `foo` column and see that its type is 'Integer' and I look at my internal metadata (application specific logic here) and see that "foo" needs to be 'Integer' and declare that everything is OK. This becomes a problem, because "foo" is actually a floating point in the query (for some DBs at least), not Integer. SqlAlchemy incorrectly reports it as Integer. 

Btw, if you return Numeric it will be correct for some databases, yet incorrect for some others. If you return Integer, the list will swap, but the problem will continue.

In my case, I care about ~6 different databases, so Integer and Numeric will both cause trouble, but Numeric works for MySQL and Oracle, which is higher priority for me. 

I think the correct thing is to implement / for integer types so that it is consistent across databases. I don't know SqlAlchemy internals to comment how doable that is.

**Comment by zzzeek** [comment]
I just did a scan of the major supported databases.  it's hard to say it's "correct" either way because as you mention, each backend has their own decision here and in fact it's split about 50/50.

```
sqlite> select 1 / 2;
0
sqlite> select 1 / 2.0;
0.5

psql (11.5)
Type "help" for help.

test=> select 1 / 2;
 ?column? 
----------
        0
(1 row)

test=> select 1 / 2.0;
        ?column?        
------------------------
 0.50000000000000000000
(1 row)
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.3.17-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [test]> select 1/ 2;
+--------+
| 1/ 2   |
+--------+
| 0.5000 |
+--------+
1 row in set (0.000 sec)

MariaDB [test]> select 1/ 2.0;
+--------+
| 1/ 2.0 |
+--------+
| 0.5000 |
+--------+
1 row in set (0.000 sec)


SQL*Plus: Release 11.2.0.2.0 Production on Fri Oct 18 14:49:07 2019

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

Enter user-name: scott
Enter password: 

Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> SELECT 1 / 2 FROM DUAL;

       1/2
----------
	.5


root@17011b7785df /]# /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -d master 
1> SELECT 1 / 2;
2> go
           
-----------
          0

(1 rows affected)
1> SELECT 1 / 2.0;
2> go
          
----------
   .500000

(1 rows affected)

```
so we have:

SQLite, Postgresql, SQL Server do floordiv, MySQL and Oracle do div.   

SQLAlchemy aims for the "/" operator to match what the database does, not what Python does.   So it's not clear that delivering Numeric or Float is what should be done here.

There can't be a dialect hook here at the level you are working with, because your test case does not use any dialect.

We could theoretically add a new meta type called "DivNumeric" or something like that which responds to dialect-level logic, however it's not clear how this would behave in expressions without knowing the real type.

at the moment, while Ive proposed patches to change this behavior right now, it's not clear if this is the best course to take as Numeric implies certain kinds of result-processing behaviors, that is, coercion to Decimal, that are not appropriate if the returned value is actually expected to be integer.

the better way would be to support both real division and floor division and implement it fully for all backends.  that's a more major change that would not be in a 1.3 release, but this may be the best way to solve it.

you can for now resolve your immediate issue by using an Integer subclass as described at https://docs.sqlalchemy.org/en/13/core/custom_types.html#redefining-and-creating-new-operators

example:

```
from sqlalchemy import (
    Column,
    Integer,
    MetaData,
    Table,
    select,
    Float,
    type_coerce,
)


class DivInteger(Integer):
    class comparator_factory(Integer.Comparator):
        def __truediv__(self, other):
            return type_coerce(self.expr, Float) / other


metadata = MetaData()
test = Table("test", metadata, Column("id", DivInteger()))
query = select(columns=[(test.c.id / 2).label("half_id")])
print("the type of the 'half_id' column is", query.c.half_id.type)

query = select(columns=[(test.c.id / 2.0).label("half_id")])
print("the type of the 'half_id' column is", query.c.half_id.type)

```

At the moment I think the best approach here may be either pointing to the above recipe or adding a flag on Integer to switch the behavior, and what this would require is that for DBs that do floor division, that the integer value renders as a CAST to float at SQL render time.   This is looking more and more like a recipe right now.

**Comment by zzzeek** [comment]
in fact this gives you that:
```

class DivInteger(Integer):
    class comparator_factory(Integer.Comparator):
        def __truediv__(self, other):
            return cast(self.expr, Float) / other

test = Table("test", metadata, Column("id", DivInteger()))
query = select(columns=[(test.c.id / 2).label("half_id")])

print(query)

```

returns:

```
SELECT CAST(test.id AS FLOAT) / :param_1 AS half_id 
FROM test

```


which means you'll get truediv on every database

**Comment by zzzeek** [comment]
propose adding this to the documenation for now

**Comment by bgedik** [comment]
Thanks. This is not blocking me in any way. I already had a workaround implemented, albeit a different one, as I do not control how the database columns are created and metadata is reflected. 

I've reported it because it seems strange that / would behave differently at the SQLAlchemy expression level.

About: "the better way would be to support both real division and floor division and implement it fully for all backends. that's a more major change that would not be in a 1.3 release, but this may be the best way to solve it."

Does this mean / would always be real division and // would be integer division (as in Python 3), or are you considering functions for it?

**Comment by zzzeek** [comment]
Python 2.7 and 3.x both have individual operator.truediv and operator.floordiv functions so if under Python 2 one uses "from __future__ import division" I think that works

**Comment by zzzeek** [comment]
that is, I need to add `__floordiv__` support to the library.   since you have workaroudns I will target this all to 1.4 which makes it easier.

**Comment by zzzeek** [comment]
this is a nice to have but is not as high priority for 1.4.

**Comment by sm-Fifteen** [comment]
I'm running into that issue on Oracle, except the result is even more puzzling: the query executes properly but fails to cast its results properly at fetching, with an error similar to oracle/python-cx_Oracle#34.

```py
def test_oracle_fetch(oracle_engine):
	query = select([
		literal_column("1", INTEGER) / literal_column("2", INTEGER)
	]).select_from(table("DUAL"))

	with oracle_engine.connect() as conn_oracle:
		res = conn_oracle.execute(query)

	rows = res.fetchall()
	return rows
```

```
  File "test_file.py", line 358, in test_oracle_fetch
    rows = res.fetchall()
  File ".pyenv\lib\site-packages\sqlalchemy\engine\result.py", line 1288, in fetchall
    self.connection._handle_dbapi_exception(
  File ".pyenv\lib\site-packages\sqlalchemy\engine\base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File ".pyenv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File ".pyenv\lib\site-packages\sqlalchemy\engine\result.py", line 1284, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File ".pyenv\lib\site-packages\sqlalchemy\engine\result.py", line 1230, in _fetchall_impl
    return self.cursor.fetchall()
ValueError: invalid literal for int() with base 10: '.5'
```

I need to wrap the expression with `type_coerce(..., NUMERIC)` for the result to be fetched properly. It seems like the interface between cx_Oracle and SQLAlchemy uses the reported ClauseExpression types to cast the results returned by the database. Oracle always performs true div, but SQLAlchemy incorrectly assumes that `INTEGER / INTEGER = INTEGER`, and cx_Oracle seemingly expects that to hold true when fetching the results.

This is on Oracle 19c, with cx_Oracle 8.0.1 and SQLAlchemy 1.3.19.

**Comment by zzzeek** [comment]
> ```python
> query = select([
> 		literal_column("1", INTEGER) / literal_column("2", INTEGER)
> 	]).select_from(table("DUAL"))
> 
> 	with oracle_engine.connect() as conn_oracle:
> 		res = conn_oracle.execute(query)
> 
> 	rows = res.fetchall()
> 	return rows
> ```

this is a driver / dialect issue, the rest of this issue refers just to what the expression system thinks it will get.  as far as fetching, that looks like cx_Oracle having a problem and this would be a separate issue.

**Comment by zzzeek** [comment]
OK, it is a result of us setting up the result here as "integer" and then setting an incomptible outputtypehandler.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**consider truediv as truediv; support floordiv operator** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3355

**Comment by zzzeek** [comment]
2.0 will resolve the issue completely including that it will render CAST / FLOOR on individual dialects as appropriate so that both / and // act as closely to Python as possible.
