### ISSUE TITLE
quoted_name gives misleading repr

### ISSUE THREAD

**Issue by jackywang615** [sqlalchemy/sqlalchemy#4931]
I select data from oracle.
If column name only chinese, sqlalchemy return garbled.

![Snipaste_2019-10-21_14-52-20](https://user-images.githubusercontent.com/9586655/67182873-af59d700-f412-11e9-91db-224c15045c3f.png)
![Snipaste_2019-10-21_14-55-42](https://user-images.githubusercontent.com/9586655/67182953-e03a0c00-f412-11e9-822f-b4b4d765a5cb.png)

**Comment by zzzeek** [comment]
hi there -

have you set NLS_LANG correctly?      since you're running a straight string SQL statement, this is a basic cx_Oracle issue.       Need to know what NLS_LANG is set to.

**Comment by jackywang615** [comment]
@zzzeek 
NLS_LANG is correctly.
`os.environ['NLS_LANG'] = 'SIMPLIFIED CHINESE_CHINA.UTF8'`

under the "=====================" is output from cx_Oracle

**Comment by zzzeek** [comment]
there's not much I can do here as this is a basic round trip, can you please try the cx_Oracle DBAPI directly and report it over at https://github.com/oracle/python-cx_Oracle/issues```


import cx_Oracle

connection = cx_Oracle.connect(...)   # see https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#establishing-database-connections

cursor = connection.cursor()
cursor.execute("SELECT <your statement>")
cursor.description
```

**Comment by zzzeek** [comment]
unless you are talking about the difference between result.keys() and saved_cursor.description ?    I can't really see your screenshot.   I would need a test case and at least give me those chinese characters to work with.   also python 2 vs. python 3 info is needed

**Comment by jackywang615** [comment]
@zzzeek this is my code and result.

from sqlalchemy import create_engine, event
import cx_Oracle
import os

os.environ['NLS_LANG'] = 'SIMPLIFIED CHINESE_CHINA.UTF8'

sqlString = "select  姓名, 姓名 as 姓名id from 病人信息"


"""
use sqlalchemy
"""
engine = create_engine("oracle+cx_oracle://*********************")
conn = engine.connect()
cursor = conn.execute(sqlString)
print("sqlalchemy: {0}".format(cursor.keys()))

print("========================== split ==================================")


"""
use cx_oracle
"""
conn = cx_Oracle.connect("***************")
cursor = conn.cursor()
cursor.execute(sqlString)
print("cx_oracle: {0}".format([i[0] for i in cursor.description]))

![Snipaste_2019-10-23_21-31-31](https://user-images.githubusercontent.com/9586655/67397958-8edd7880-f5dc-11e9-94ba-b899637f00de.png)

**Comment by zzzeek** [comment]
name_normalize converts from oracle's UPPERCASE as case-insensitive to SQLAlchemy's lower case as case-insensitive and it does not expect characters for which "upper" / "lower" make no sense to be part of this.  for some reason name normalize is running on this.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use default repr() for quoted_name under python 3** https://gerrit.sqlalchemy.org/1537
