### ISSUE TITLE
unique bindparam for text

### ISSUE THREAD

**Issue by p-frolov** [sqlalchemy/sqlalchemy#4933]
Hello,
I have an issue with sa.text with parameters and sa.union_all function.

```python
query = sa.text('select id from runs where id=:run_id').columns(id=sa.Integer)

queries = []

queries.append(query.bindparams(run_id=433))
queries.append(query.bindparams(run_id=432))

conn.execute(queries[0]).fetchall()
# OK: [(433,)]

conn.execute(queries[1]).fetchall()
# OK: [(432,)]

q_union = sa.union_all(*queries)

conn.execute(q_union).fetchall()
# NOK: [(432,), (432,)]
#      the same ids, it seems last parameter applied to all queries
# EXPECTED: [(433,), (432,)]

# BUT:
print(q_union.compile(compile_kwargs={"literal_binds": True}))
# OK: select id from runs where id=433 UNION ALL select id from runs where id=432
#     different ids as set in bindparams
```

db details:
```python
runs = sa.Table(
    'runs', metadata,

    Column('id', sa.Integer, primary_key=True),
    # ...
)
CONNECTION_STRING = 'postgresql://user:pass@localhost/db'
```

bindparams example I found in documentation: https://docs.sqlalchemy.org/en/13/core/tutorial.html#specifying-bound-parameter-behaviors

I use:
sqlalchemy==1.3.5
psycopg2==2.7.5
python==3.6.8
postgres:11.1

PS: In production my queries much complex than in example. I use sa.select(run.c.id).where(...) and so on, but I have part of query with sa.text with parameters and have unexpected behavior above.
Example of real parts:
```python
sa.select(
    ..., sa.text(':key as key').bindparams(key=key)
).where(
    ... & sa.text("(runs.partial_ready->>:key)::bool = true").bindparams(key=key)
)
```

**Comment by zzzeek** [comment]
in SQLAlchemy master, that is the 1.4 series, there's an undocumented enhancement, undocumented because I wasn't sure I wanted to release this to people because nobody uses these kinds of features, that supports unique bound paremters in text().   unique parameters are what Core uses for things like literal() so that you never have any conflicting names.     So in master you can do this:

```
import sqlalchemy as sa

query = sa.text('select id from runs where id=:run_id').columns(id=sa.Integer)

queries = []

queries.append(query.bindparams(sa.bindparam("run_id", value=433, unique=True)))
queries.append(query.bindparams(sa.bindparam("run_id", value=432, unique=True)))


e = sa.create_engine("sqlite://", echo=True)
e.execute("create table runs(id integer)")

with e.connect() as conn:

    q_union = sa.union_all(*queries)

    conn.execute(q_union).fetchall()
```

I added this in 1.4 because it was needed for something internally, however I can see if I can locate the change and backport it to the current 1.3.x series because I think it was very short.

**Comment by zzzeek** [comment]
this was bundled as part of #4808 in 36e8fe48b2332ecc44b506d1f86c

**Comment by zzzeek** [comment]
it says "limited support", not sure what limited means so i might have to look at it.  this patch allows the test to work:

```
diff --git a/lib/sqlalchemy/sql/elements.py b/lib/sqlalchemy/sql/elements.py
index 22834dd19..2e3b64dde 100644
--- a/lib/sqlalchemy/sql/elements.py
+++ b/lib/sqlalchemy/sql/elements.py
@@ -1568,14 +1568,20 @@ class TextClause(Executable, ClauseElement):
 
         for bind in binds:
             try:
-                existing = new_params[bind.key]
+                #  existing = new_params[bind.key]
+                # the regex used for text() currently will not match
+                # a unique/anonymous key in any case, so use the _orig_key
+                # so that a text() construct can support unique parameters
+                existing = new_params[bind._orig_key]
+
             except KeyError:
                 raise exc.ArgumentError(
                     "This text() construct doesn't define a "
                     "bound parameter named %r" % bind.key
                 )
             else:
-                new_params[existing.key] = bind
+                #new_params[existing.key] = bind
+                new_params[existing._orig_key] = bind
 
         for key, value in names_to_values.items():
             try:

```

**Comment by p-frolov** [comment]
@zzzeek thank you for your answers,

unfortunately I can use only releases from standard repository in production.

for now I used workaround:
```python
    q_union = ' union all '.join(
        f'({q.compile(compile_kwargs={"literal_binds": True})})' for q
        in queries
    )
```
I know it's ugly and using of `compile_kwargs={"literal_binds": True}` is unsafe, but I hope `unique bindparam` will be added to nearest 1.3.xx version soon.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Document unique bound parameters for text()** https://gerrit.sqlalchemy.org/1540

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Support unique bound parameters for text()** https://gerrit.sqlalchemy.org/1541
