### ISSUE TITLE
UNSUPPORTED_PROTOCOL with python:3.7.4-slim-buster docker image

### ISSUE THREAD

**Issue by daveisfera** [sqlalchemy/sqlalchemy#4937]
We updated our docker image from `python:3.7-4-slim-stretch` to `python:3.7.4-slim-buster` and this error started happening when connecting to a MariaDB and MySQL database:
`2003, "Can't connect to MySQL server on 'mysqlnumetric.ceoxewvigov8.us-east-2.rds.amazonaws.com' ([SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1076))`

Is this an issue with the the buster OS or something that SQLAlchemy isn't doing correctly when running on buster?

**Comment by daveisfera** [comment]
Forgot to mention that we're using 1.3.8 and starting tests with 1.3.10

**Comment by zzzeek** [comment]
this is not a sqlalchemy issue this has to o with whatever driver you are using.

**Comment by zzzeek** [comment]
sounds like you are using mysqlclient native driver and SSL needs to be installed in your container

**Comment by daveisfera** [comment]
Opened an issue with `PyMySQL`
