### ISSUE TITLE
tox test failures under Windows

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#4946]
More of an FYI than a problem *per se*, but running the entry-level test ...

```
tox -e py38-sqlite
```

... under Linux (Xubuntu 18.04) completes successfully ...

```
========================================== 9799 passed, 1045 skipped in 646.72s (0:10:46) ==========================================
_____________________________________________________________ summary ______________________________________________________________
  py38-sqlite: commands succeeded
  congratulations :)
```

... but doing the same under Windows 8.1 produces several failures:

[py38-sqlite.txt](https://github.com/sqlalchemy/sqlalchemy/files/3769992/py38-sqlite.txt)

I've seen similar failures under Windows with Python 3.7.4 and 3.7.5rc1, so it's looking more like a Windows thing than a Python version thing.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Disallow memory tests from running on Windows** https://gerrit.sqlalchemy.org/1544

**Comment by zzzeek** [comment]
this is straightforward to fix, run the test suite with --nomemory, which is a SQLAlchemy flag that will deselect those tests.

**Comment by zzzeek** [comment]
also if you want to try out that patch, that also deselects those tests if you want to confirm

**Comment by gordthompson** [comment]
Patch set 1 helped, bringing the number of failures down from 22 to 13. Of those remaining, 9 are related to

> sqlite3.OperationalError: no such function: JSON_EXTRACT

Details here:

[py38_1544_PS1.txt](https://github.com/sqlalchemy/sqlalchemy/files/3772396/py38_1544_PS1.txt)

**Comment by zzzeek** [comment]
that would be because the pysqlite built into your windows python does not have the json extension installed, which is very strange because it is present in the linux version.   can you confirm the version of sqlite built into your python interpreter is 3.9 or greater 

```
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.26.0'

```

**Comment by gordthompson** [comment]
```
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.28.0'
```

It seems that different platform builds of Python can include slightly different pieces, e.g., as discussed [here](https://github.com/microsoft/azure-pipelines-image-generation/issues/1083).

**Comment by gordthompson** [comment]
I'm happy to leave this closed, but please re-open if you'd like to pursue this further.

**Comment by zzzeek** [comment]
nope lets get the sqlite going

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Perform an active check for sqlite json extension** https://gerrit.sqlalchemy.org/1546

**Comment by zzzeek** [comment]
there's the next one to try

**Comment by gordthompson** [comment]
Okay, that eliminated the "no such function: JSON_EXTRACT" failures, so now we're down to 5:

[py38_1546_PS1.txt](https://github.com/sqlalchemy/sqlalchemy/files/3773281/py38_1546_PS1.txt)

**Comment by zzzeek** [comment]
can you try this, wild guess, otherwise I have to load windows and pdb

```
diff --git a/lib/sqlalchemy/testing/requirements.py b/lib/sqlalchemy/testing/requirements.py
index c45156d6b..60e29421c 100644
--- a/lib/sqlalchemy/testing/requirements.py
+++ b/lib/sqlalchemy/testing/requirements.py
@@ -1017,7 +1017,7 @@ class SuiteRequirements(Requirements):
         gc.collect() is called, as well as clean out unreferenced subclasses.
 
         """
-        return self.cpython
+        return self.cpython and not self._running_on_windows()
 
     @property
     def no_coverage(self):


```

**Comment by gordthompson** [comment]
Hit the limit of 25 errors:

> TypeError: 'bool' object is not callable

[patch1_out.txt](https://github.com/sqlalchemy/sqlalchemy/files/3773973/patch1_out.txt)

**Comment by zzzeek** [comment]
once more

```
diff --git a/lib/sqlalchemy/testing/requirements.py b/lib/sqlalchemy/testing/requirements.py
index c45156d6b..82f691f8a 100644
--- a/lib/sqlalchemy/testing/requirements.py
+++ b/lib/sqlalchemy/testing/requirements.py
@@ -1017,7 +1017,8 @@ class SuiteRequirements(Requirements):
         gc.collect() is called, as well as clean out unreferenced subclasses.
 
         """
-        return self.cpython
+
+        return self.cpython + self.no_windows
 
     @property
     def no_coverage(self):

```

**Comment by gordthompson** [comment]
Sorry, but I get the same 5 failures as in py38_1546_PS1.txt.

[patch2_out.txt](https://github.com/sqlalchemy/sqlalchemy/files/3774145/patch2_out.txt)

**Comment by zzzeek** [comment]
yup, was just trying something

**Comment by CaselIT** [comment]
I can help on this. Is there already a partial patch in gerrit @zzzeek ?

**Comment by zzzeek** [comment]
there are a few gerrits linked in comments above and I think they've been merged.  for futher issues we would need a new PR.

**Comment by gordthompson** [comment]
Yes, Gerrit 1546 has been merged into GitHub master. I could create a PR that incorporates the patch from the later comment [here](https://github.com/sqlalchemy/sqlalchemy/issues/4946#issuecomment-546535362) even though it did not eliminate the 5 failures that existed before the patch was applied. Would that be appropriate? If not, I suppose I could make an arbitrary inconsequential change to something in master and then submit a PR based on that.

**Comment by CaselIT** [comment]
Indeed 1546 got merged in master

I've tried master with sqlite and I get 3 errors, that are permission errors in the same class

**Comment by CaselIT** [comment]
There seems to be other errors in the queue pool tests that happen in some executions.

I've listed them in the pr

**Comment by zzzeek** [comment]
yes the queue pool stuff has some race condition tests that uses threads etc and they are still too sensitive to timing.

**Comment by CaselIT** [comment]
maybe it's best just to accept a failure on windows (if pytest allows that) or skip them directly on windows.

**Comment by zzzeek** [comment]
I'll take a look at them to see what assumptions are being made but usually I just add a skip_windows kind of rule

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fix test failures under Windows** https://gerrit.sqlalchemy.org/1637

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix test failures under Windows** https://gerrit.sqlalchemy.org/1638
