### ISSUE TITLE
Add mention of `polymorphic_identity` meaning to inheritance docs

### ISSUE THREAD

**Issue by Quelklef** [sqlalchemy/sqlalchemy#4951]
The [documentation on inheritance](https://docs.sqlalchemy.org/en/13/orm/inheritance.html#relationships-with-single-table-inheritance) doesn't seem to explain exactly what the `polymorphic_identity` key on `__mapper_args__` is. It would be useful to state something like:

> `polymorphic_identity` is a value that populates the column designated by `polymorphic_on`. This value is how SqlAlchemy tells the type of a row that belongs to a polymorphic table. All rows of a subclass have the same value for this column.
> In this instance, `polymorhpic_on` designates the `type` column, which is of strings. So our `polymorhpic_identity` values are all strings; `'employee'`, `'manager'`, and `'engineer'`, respectively. If, however, the polymorphic discriminator were a row containing integers, then each `polymorphic_identity` would have to be an integer.

For a beginner like me, this omission took quite a bit of headscratching until I guessed what was going in.

**Comment by zzzeek** [comment]
pull requests welcome...

**Comment by Quelklef** [comment]
Yes, sir! https://github.com/sqlalchemy/sqlalchemy/pull/4952
