### ISSUE TITLE
Moving a dataframe to Oracle with cx_oracle 

### ISSUE THREAD

**Issue by rm17tink** [sqlalchemy/sqlalchemy#4953]
I am getting an error when I try and move a dataframe to oracle: 
`do_executemany
    cursor.executemany(statement, parameters)  TypeError: expecting number`

**Comment by zzzeek** [comment]
hi there -

you'd want to look at the SQL being emitted using echo=True with create_engine and also at the stack trace which would indicate what function is receiving the wrong kind of value.      these things can be shared here if you'd like help interpreting them.

**Comment by zzzeek** [comment]
no response

**Comment by hallison** [comment]
I have the same problem. :(

**Comment by zzzeek** [comment]
No problem!  Provide a working test case, stack trace, and turn on echo='debug' on your create_engine() and provide the SQL log output, hit reopen and we can get you on your way.

**Comment by hallison** [comment]
@zzzeek in the test cases the error not trigger. Only in production environment.

**Comment by hallison** [comment]
Stack:

File \\\"/app/sync/local/processors.py\\\", line 286, in process\
  oracle_session.commit()\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py\\\", line 1027, in commit\
  self.transaction.commit()\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py\\\", line 494, in commit\
  self._prepare_impl()\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py\\\", line 473, in _prepare_impl\
  self.session.flush()\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py\\\", line 2459, in flush\
  self._flush(objects)\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py\\\", line 2597, in _flush\
  transaction.rollback(_capture_exception=True)\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py\\\", line 68, in __exit__\
  compat.reraise(exc_type, exc_value, exc_tb)\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py\\\", line 154, in reraise\
  raise value\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py\\\", line 2557, in _flush\
  flush_context.execute()\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py\\\", line 422, in execute\
  rec.execute(self)\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py\\\", line 589, in execute\
  uow,\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py\\\", line 245, in save_obj\
  insert,\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py\\\", line 1084, in _emit_insert_statements\
  c = cached_connections[connection].execute(statement, multiparams)\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\\\", line 988, in execute\
  return meth(self, multiparams, params)\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py\\\", line 287, in _execute_on_connection\
  return connection._execute_clauseelement(self, multiparams, params)\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\\\", line 1107, in _execute_clauseelement\
  distilled_params,\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\\\", line 1248, in _execute_context\
  e, statement, parameters, cursor, context\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\\\", line 1468, in _handle_dbapi_exception\
  util.reraise(*exc_info)\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py\\\", line 154, in reraise\
  raise value\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\\\", line 1224, in _execute_context\
  cursor, statement, parameters, context\
File \\\"/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/oracle/cx_oracle.py\\\", line 1080, in do_executemany\
  cursor.executemany(statement, parameters)\
TypeError: expecting number\
