### ISSUE TITLE
How would I check the base object of a query?

### ISSUE THREAD

**Issue by nikhilro** [sqlalchemy/sqlalchemy#4956]
Hey, if there a function that takes in a `query` and it wants to do some assertions before modifying and/or executing the query, how would one do that? 

Specifically, I'm interested in ensuring the base entity of the query is `MyModel`; I would currently check it like this: `assert query._entity_zero().class_ is MyModel`. Wondering if there is a better sqlalchemy way to do this that does that involve fiddling around with private fields. 

Thanks,
Nikhil

**Comment by zzzeek** [comment]
to inspect the query entities look at query.column_descriptions: https://docs.sqlalchemy.org/en/13/orm/query.html?highlight=column_descriptions#sqlalchemy.orm.query.Query.column_descriptions

**Comment by nikhilro** [comment]
thanks for the quick reply. that's useful. I think i'm more interested in checking the `FROM` part of the SQL query which would be generated rather than columns which are returned if that makes sense

**Comment by zzzeek** [comment]
it's in there, here's a demo

```
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)

s = Session()


for q in [
    s.query(A),
    s.query(A.id)
]:
    assert q.column_descriptions[0]['entity'] is A

```

**Comment by nikhilro** [comment]
thanks, that'll do!
