### ISSUE TITLE
Supporting Yellowbrick with PostgreSQL dialect

### ISSUE THREAD

**Issue by sergioov** [sqlalchemy/sqlalchemy#4957]
Hi, 
There is a new data warehouse appliance called Yellobrick which can interact with python using the PostgreSQL dialect and engine. 
I don't have much experience contributing to code, but I would like to add my 2 cents. This will also help me with my developments since I need the engine function to work with pandas DataFrame.to_sql function. 

The error I got is this (very summarized): 

  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2666, in _get_server_version_info
    "Could not determine version from string '%s'" % v
AssertionError: Could not determine version from string 'Yellowbrick Database version 3.0.4-14193'

A quick fix I did was this: 
change from line 2654 the next function: 
    
```
def _get_server_version_info(self, connection):
        v = connection.execute("select version()").scalar()
        m = re.match(
            r".*(?:PostgreSQL|EnterpriseDB) "
            r"(\d+)\.?(\d+)?(?:\.(\d+))?(?:\.\d+)?(?:devel|beta)?",
            v,
        )
        if not m:
             if "Yellowbrick" in v:
                 return (9, 4)
        if not m:
            raise AssertionError(
                "Could not determine version from string '%s'" % v
            )
        return tuple([int(x) for x in m.group(1, 2, 3) if x is not None])
```
According to this page: 
    https://yellowbrick.com/docs/3.0/connectivity/downloading_drivers.html
Yellowbrick should be compatible with version 9.4 of postgres drivers. 

I hope this helps someone and could be included somehow in the next release.

**Comment by zzzeek** [comment]
it would be better for there to be a third party yellowbrick dialect.  i am sure it has many differences from postgresql including how information about existing schema objects, tables, and columns are loaded.    see https://github.com/sqlalchemy-redshift/sqlalchemy-redshift for an example of another "just like PostgreSQL" database that nonetheless has its own dialect.

**Comment by sergioov** [comment]
I agree with you, but currently, the official documentation on yellow brick point you to the JDBC and ODBC drivers for PostgreSQL.
So maybe the dialect would be just a copy of the PostgreSQL one?

**Comment by zzzeek** [comment]
sqlalchemy's postgresql driver and psycopg2 have nothing to do with JDBC or ODBC drivers, but anyway, yes, there should be a yellowbrick dialect that would subclass existing postgresql dialect constructs in a manner similar to that of the sqlalchemy-redshift dialect.

**Comment by zzzeek** [comment]
closing this as it pertains to a potential third-party dialect.
