### ISSUE TITLE
chunk iterator support for results

### ISSUE THREAD

**Issue by sumau** [sqlalchemy/sqlalchemy#4959]
It would be helpful to be able to 'automatically' iterate through fetchmany, similar to pd.read_sql(chunksize) or as suggested here:
http://code.activestate.com/recipes/137270-use-generators-for-fetching-large-db-record-sets/

So for example instead of writing the following in [this](https://docs.sqlalchemy.org/en/13/_modules/examples/performance/large_resultsets.html) example:
```python
    with engine.connect() as conn:
        result = conn.execution_options(stream_results=True).execute(
            Customer.__table__.select().limit(n)
        )
        while True:
            chunk = result.fetchmany(10000)
            if not chunk:
                break
            for row in chunk:
                row["id"], row["name"], row["description"]
```
you could write something like:
```python
    with engine.connect() as conn:
        result = conn.execution_options(stream_results=True, arraysize=10000).execute(
            Customer.__table__.select().limit(n)
        )
   for chunk in result:
          for row in chunk:
                row["id"], row["name"], row["description"]
```
I'm using arraysize to be in accordance with pep249 dbapi cursor.arraysize but perhaps chunksize might be better

**Comment by zzzeek** [comment]
hi there -

unfortunately that would entirely change how the resultproxy works both from an internal as well as an external point of view.   at most, I would consider adding a chunks() call to result however I'm not ready to do that right now as I am seeking to unify the API of ResultProxy and Query.   For that work I will attempt to consider this use case as well.

**Comment by zzzeek** [comment]
the activestate recipe is wrong.  with the vast majority of DBAPIs, it doesn't matter if you call fetchall() or fetchmany(), the rows are already fetched into memory fully after execute() is called.   so I think this feature is kind of misleading since fetchmany() is already misleading.    The option that should be considered here is stream_results: https://docs.sqlalchemy.org/en/13/core/connections.html?highlight=stream_results#sqlalchemy.engine.Connection.execution_options.params.stream_results   only works with three DBAPis right now - without it, there are no memory savings to fetchmany().

**Comment by sumau** [comment]
Makes sense - I'll add a generator where relevant in my code base as a workaround for now :-)

**Comment by zzzeek** [comment]
thanks!  sorry, I do want to do this, but ive been spending months just thinking about the result set and how to unify Core / ORM the best way.

**Comment by zzzeek** [comment]
there's thorny questions like, the user requests to do chunks, and we try to make it so that the DBAPI is also chunking using stream_results automatically.  but then what do we do for the DBAPIs that don't support streaming.

**Comment by sumau** [comment]
Would it help if I tried to find out how pandas copes with both chuncking
and streaming/buffering in read_sql? I ran some tests using memory_profiler
and I know it's working !

**Comment by sqla-tester** [comment]
it depends on driver and they also might be reading in pages using limit/offset. if they are doing that, it's still not efficient overall as offset is very wasteful at high numbers of rows.

**Comment by sumau** [comment]
Hey so did some digging around. Pandas is using fetchmany on the ResultProxy / BufferedRowResultProxy to do the chunking:

https://github.com/pandas-dev/pandas/blob/0f15046df0c30b76e163518d4914442d8f8efef5/pandas/io/sql.py#L759

I have also attached a script I wrote to test the memory usage and number of records fetched based on whether buffered, or chunking larger or smaller than max_buffered_size.

**Comment by zzzeek** [comment]
yes if you use postgresql with stream_results it will only fetch small batches at a time.  this is not the case for say SQLite though.

**Comment by sumau** [comment]
So yes you wouldn't use stream_results with SQLite but the chunking could still work, it would just happen after you load everything into memory. There are operations I want to apply to a "chunk" of rows at a time (e.g. writing to a csv) regardless whether the cursor is streamed or not.

**Comment by zzzeek** [comment]
absolutely, but we are going in a circle a bit.  above you mentioned that you saw better results with memory_profiler.   That part of it wont work.  but of course, fetchmany() works in all cases as a programming pattern so improving upon that is valid.

**Comment by sumau** [comment]
Sorry my bad, misunderstanding :-)

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Propose Result as immediate replacement for ResultProxy** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1911

**Comment by zzzeek** [comment]
This is coming in today.    the method is called .partitions() and you can pass it a chunk size, which will then work in conjunction with server side cursors if they are enabled in order to fetch that many rows from the cursor each time.

**Comment by sumau** [comment]
Thanks! I also noticed you have started updating the result object documentation for 1.4: https://docs.sqlalchemy.org/en/14/changelog/migration_14.html?highlight=partitions#new-result-object
I think it's great you renamed ResultProxy to CursorResult - it's much closer to DBAPI!

**Comment by zzzeek** [comment]
ack taht's the wrong result object....moment

**Comment by zzzeek** [comment]
OK doc update is pushed, should be much more informative

**Comment by sumau** [comment]
Very clear :-)
