### ISSUE TITLE
SQLAlchemy 1.3.10 issue with python3

### ISSUE THREAD

**Issue by smuzaffar** [sqlalchemy/sqlalchemy#4964]
While testing SQLAlchemy 1.3.10 with python 3.6.4 we are getting error [a]. Patching it with patch https://github.com/cms-sw/cmsdist/pull/5334/commits/e7322933f3fd4240d094a638d6382564c6c40295 allowed us to run our tests.

[a]
```
  File "sqlalchemy/1.3.10/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 285, in _exec_once_impl
    self(*args, **kw)
  File "sqlalchemy/1.3.10/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "sqlalchemy/1.3.10/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 1485, in go
    return once_fn(*arg, **kw)
  File "sqlalchemy/1.3.10/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 199, in first_connect
    dialect.initialize(c)
  File "sqlalchemy/1.3.10/lib/python3.6/site-packages/sqlalchemy/dialects/oracle/base.py", line 1247, in initialize
    super(OracleDialect, self).initialize(connection)
  File "sqlalchemy/1.3.10/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 319, in initialize
    max_ident_length = self._check_max_identifier_length(connection)
  File "sqlalchemy/1.3.10/lib/python3.6/site-packages/sqlalchemy/dialects/oracle/base.py", line 1300, in _check_max_identifier_length
    if self._get_effective_compat_server_version_info(connection) &gt;= (
  File "sqlalchemy/1.3.10/lib/python3.6/site-packages/sqlalchemy/dialects/oracle/base.py", line 1262, in _get_effective_compat_server_version_info
    if self.server_version_info < (12, 2):
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
```

**Comment by zzzeek** [comment]
hi there -

how is it that your server version info is None when you have an active connection?

**Comment by zzzeek** [comment]
Hi there -

Unfortunately I'm not able to act upon this without the information I requested.  Please reopen when you are available to discuss the rationale.   Once that happens, you can resubmit your PR.

**Comment by smuzaffar** [comment]
sorry I was away and could not reply.
We have oracle+frontier dialect implementation ( https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/master/py2-sqlalchemy-1.3.4-add-frontier-dialect.patch ) . Where getting server version is not implemented. This results in server_version_info set to None ( https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L290 ). I think correct fix would be to set server_version_info = () at engine/default.py#L290

**Comment by zzzeek** [comment]
hi -

thanks for getting back to me.  Why can't your custom dialect implement server version ?

**Comment by smuzaffar** [comment]
It can but I d not know how. The person who have developed this has gone. I am just a librarian to maintain the software stack :-)
If I am not wrong, oracle+frontier implementation does not talk to DB directly. https://github.com/fermitools/frontier is used to communicate. 

I guess either sqlalchemy should fail if the server_version is not implemented or it should set server_version_info to something which does not fail for python3.

**Comment by zzzeek** [comment]
is this system talking to a real oracle database?  the get_server_version_info method would look like (googled from https://www.techonthenet.com/oracle/questions/version.php ):

```
    def _get_server_version_info(self, connection):
        raw_version = connection.scalar("SELECT banner FROM v$version WHERE banner LIKE 'Oracle%';"
        return tuple(int(x) for x in raw_version.split("."))

```

this method would be added to the code you illustrated above on the OracleDialect_frontier class right where get_default_schema_name is.

OTOH if this database is not really Oracle-like, you should likely override the whole initialize() method of the dialect, or return a fake server version like (9, 0).   but if this database is very different from oracle then it won't work long term to continue subclassing the base Oracle dialect and you should rework the dialect to subclass DefaultDialect.

I will gladly help you to get that method to work correctly if it doesn't work on the first try.

**Comment by smuzaffar** [comment]
thanks for the information. I will see what I can do.
