### ISSUE TITLE
why isnt Oracle.INTERVAL a subclass of Interval?

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4971]
tests fail.   marking them as fails on oracle for now.

**Comment by zzzeek** [comment]
that is, tests in test/sql/test_types, which also don't have `__backend__`, adding that now.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Repair Oracle Interval** https://gerrit.sqlalchemy.org/1577
