### ISSUE TITLE
SQL Server expression-based offset not interpreted correctly

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4973]
```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)

# simple limit / offset, works
stmt = select([A.data]).limit(5).offset(10).order_by(A.id)

# expression limit / offset, works
stmt = select([A.data]).limit(literal_column("5")).offset(literal_column("10")).order_by(A.id)

# simple limit / expression offset, the check is wrong
stmt = select([A.data]).limit(5).offset(literal_column("10")).order_by(A.id)


from sqlalchemy.dialects import mssql
print(stmt.compile(dialect=mssql.dialect()))
```

error:

sqlalchemy.exc.CompileError: This SELECT structure does not use a simple integer value for offset

**Comment by zzzeek** [comment]
as a related issue, the testing fixtures are also not working correctly which did not catch for this failure correctly

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Interpret empty LIMIT, expression LIMIT correctly** https://gerrit.sqlalchemy.org/1567

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Interpret empty LIMIT, expression LIMIT correctly** https://gerrit.sqlalchemy.org/1568
