### ISSUE TITLE
could not assemble any primary key columns for mapped table

### ISSUE THREAD

**Issue by danerlt** [sqlalchemy/sqlalchemy#4975]
my model:
```
class Test(db.Model):
    __tablename__ = "Test"  
    STN = db.Column(db.String(3), nullable=False, info='')
    BEG_DATE = db.Column(db.Date, nullable=False, info='')
    END_DATE = db.Column(db.Date, nullable=False, info='')
    PRICE = db.Column(db.String(3), nullable=False, info='')
    REMARK = db.Column(db.String(255), nullable=True, info='')
```
when I run my flask app, its tips `could not assemble any primary key columns for mapped table`,Mysql database can create a database without a primary key, Why do I have to set the primary key?I don't want to set the primary key, how can I solve it?

**Comment by zzzeek** [comment]
hi there -

please see https://docs.sqlalchemy.org/en/13/faq/ormconfiguration.html#how-do-i-map-a-table-that-has-no-primary-key

if your table has no columns that qualify as a [candidate key](https://en.wikipedia.org/wiki/Candidate_key) then it cannot be used by the ORM, you would need to use [core only](https://docs.sqlalchemy.org/en/13/core/tutorial.html), however, there's really no such thing in relational databases as a table that doesn't have a candidate key of some kind, because otherwise it means you can have multiple rows that are complete duplicates of each other, how would that be useful ?

**Comment by s2t2** [comment]
I ran into this issue as well. I'm using psycopg to query a table managed by sqlalchemy. The table doesn't have a PK. Why should a table that exists need a PK in order to fetch rows from it?

**Comment by zzzeek** [comment]
> I ran into this issue as well. I'm using psycopg to query a table managed by sqlalchemy. The table doesn't have a PK. Why should a table that exists need a PK in order to fetch rows from it?

it doesn't.   If you emit a SELECT statement that wishes to receive rows back, no problem:

```
>>> from sqlalchemy import create_engine
>>> e = create_engine("sqlite://", echo=True)
>>> from sqlalchemy import MetaData, Table, Column, Integer
>>> t = Table("no_pk", MetaData(), Column("some_int", Integer))
>>> t.create(e)
2020-08-29 11:18:26,604 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2020-08-29 11:18:26,605 INFO sqlalchemy.engine.Engine 
CREATE TABLE no_pk (
	some_int INTEGER
)


2020-08-29 11:18:26,605 INFO sqlalchemy.engine.Engine [no key 0.00037s] ()
2020-08-29 11:18:26,607 INFO sqlalchemy.engine.Engine COMMIT
>>> with e.connect() as conn:
...     conn.execute(t.insert(), {"some_int": 1})
...     result = conn.execute(t.select())
...     print(result.fetchall())
... 
2020-08-29 11:18:59,469 INFO sqlalchemy.engine.Engine INSERT INTO no_pk (some_int) VALUES (?)
2020-08-29 11:18:59,470 INFO sqlalchemy.engine.Engine [generated in 0.00065s] (1,)
2020-08-29 11:18:59,470 INFO sqlalchemy.engine.Engine COMMIT
<sqlalchemy.engine.cursor.LegacyCursorResult object at 0x7fbfa39853d0>
2020-08-29 11:18:59,472 INFO sqlalchemy.engine.Engine SELECT no_pk.some_int 
FROM no_pk
2020-08-29 11:18:59,472 INFO sqlalchemy.engine.Engine [generated in 0.00038s] ()
[(1,)]

```

where there is an issue however is if you wish to use the [ORM Session](https://docs.sqlalchemy.org/en/13/orm/session.html) with [mapped classes](https://docs.sqlalchemy.org/en/13/orm/mapping_styles.html).   SQLAlchemy's ORM uses a pattern called [identity_map](https://docs.sqlalchemy.org/en/13/glossary.html#term-identity-map) which means that when the ORM loads ORM-mapped classes based on database rows, it assembles these into a map that is unique per identity.   An ORM mapped class therefore needs some means of determining the identity of a row which is normally the primary key, but it can be anything you want.

This is also what is up in my comment above at https://github.com/sqlalchemy/sqlalchemy/issues/4975#issuecomment-552918739 and the FAQ entry linked at https://docs.sqlalchemy.org/en/13/faq/ormconfiguration.html#how-do-i-map-a-table-that-has-no-primary-key .




> 
> Is there a way to revise the table settings to allow it to not have a PK? Otherwise I'll go back and add a PK, but will have to re-download the data...

as above, please read https://docs.sqlalchemy.org/en/13/faq/ormconfiguration.html#how-do-i-map-a-table-that-has-no-primary-key

**Comment by s2t2** [comment]
Thanks for the detailed explanation!
