### ISSUE TITLE
execute() seems to not close the DB connection properly

### ISSUE THREAD

**Issue by edwardkw** [sqlalchemy/sqlalchemy#4979]
Specifically, when executing Count queries on views:
```
q = 'SELECT count(*) AS count_1 FROM view_xyz123'

eng = sa.Engine('psql_settings`) # connect to a Postgresql db 

result = eng.execute(sa.text(q))
```

Despite `close_with_result` always being set to `True` in `execute()`, I am seeing open connections stack up in PSQL when running this repeatedly.

**Comment by zzzeek** [comment]
hi there -

the result called by engine.execute(), which includes the cursor, as well as the connection which refers to that cursor, is absolutely not closed if it returns results, until those results are fully fetched.   if the DBAPI cursor has a non-None cursor.description , nothing is closed until you fetch.

Additionally, engine.execute() and close_with_result are all going to be deprecated and removed by SQLAlchemy 2.0.     Strongly advise not using connectionless execution, the canonical pattern is:

```
with engine.connect as conn:
    result = conn.execute(text("query"))
```

with the above pattern, there is no ambiguity or need to know about strange flags like close_with_result.

**Comment by edwardkw** [comment]
@zzzeek Sorry, to clarify - after that `execute()` call, we immediately call `result.fetchall()`

**Comment by zzzeek** [comment]
the connections won't necessarily "close" from a PG point of view because there is a connection pool in use.  By default you'd see five connections open when the application is idle.

**Comment by edwardkw** [comment]
Does the `connect()` paradigm imply that the connection will be closed after the `with` block ends?

**Comment by edwardkw** [comment]
I encountered the same issue when using `connect()`;

```
            with self.engine.connect() as conn:
                res = conn.execute(sa.text(q))
                if res_type is not None:
                    return res.fetchall()
```

**Comment by zzzeek** [comment]
turn off pooling as documented at https://docs.sqlalchemy.org/en/13/core/pooling.html#switching-pool-implementations

**Comment by edwardkw** [comment]
@zzzeek Just wanted to thank you very much for your help, especially as this wasn't necessarily a proper bug.

**Comment by zzzeek** [comment]
no worries, it is now common that people post usage questions on github so I've learned to get used to it :)  (some become bugs in any case)
