### ISSUE TITLE
MSSQL's DateTimeOffset is a timezoned DateTime, not an interval

### ISSUE THREAD

**Issue by teozkr** [sqlalchemy/sqlalchemy#4980]
According to MSDN: https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?view=sql-server-ver15

Current stub: https://github.com/sqlalchemy/sqlalchemy/blob/be2cd2791ea65fb76b193a34752361f1e76d68b2/lib/sqlalchemy/dialects/mssql/base.py#L1022-L1027

**Comment by zzzeek** [comment]
hiya -

so.... we should remove the comment then ?

**Comment by zzzeek** [comment]
or beyond that bring it in to be a DateTime.    equivalent to PG's TIMESTAMP WITH TIMEZONE?

**Comment by teozkr** [comment]
Ideally, the latter.

**Comment by zzzeek** [comment]
I can do this for 1.4 is this somehow blocking you right now

**Comment by teozkr** [comment]
Currently I'm working around it by only storing times in UTC, but that feels pretty brittle. That said, I wouldn't be comfortable releasing it as a patch to 1.3 since changing `DATETIMEOFFSET` would break it for any current users.

**Comment by zzzeek** [comment]
so pyodbc is giving me:

    ODBC SQL type -155 is not yet supported.  

which suggests this type can't even be round-tripped for now.   so that would be a bigger blocker.

**Comment by zzzeek** [comment]
Also, the usual practice is to store timestamps in UTC, which I've always advocated for and I don't find it to be brittle at all, however, PG's TIMESTAMP WITH TIMEZONE is clearly very popular.       But I'm not sure SQL Servers datatype is going to be as full-featured as that of PG's; PG's datatype has all kinds of bumpers to make sure date arithmetic works, etc.   I still don't like it very much but you should at least confirm that SQL Server's datatype is indeed as slick and fail-proof as PGs; that the pyodbc driver doesn't seem to even know about this type is not a good sign.

**Comment by zzzeek** [comment]
here is there issue: https://github.com/mkleehammer/pyodbc/issues/134

**Comment by teozkr** [comment]
> Also, the usual practice is to store timestamps in UTC, which I've always advocated for and I don't find it to be brittle at all

Sorry, I should have been clearer. The brittleness comes from that, as far as I can tell, the `mssql.DateTime` type just truncates the `tzinfo` when writing (without converting to UTC, or even validating it), and returns a naive (zoneless) `datetime` when reading it back. It would be fine to convert to UTC when writing, and then always attach the UTC `tzinfo` back when reading.

**Comment by zzzeek** [comment]
so i can only fix this partially.   I'm not really a fan of plugging in an odbc output type handler in SQLAlchemy b.c. pyodbc should just fix this.

**Comment by teozkr** [comment]
I'm using pymssql, but that just seems to return the bytestring. Not a great outcome there either. I suppose the best path forward is to just use a validating `DecoratorType`.

**Comment by zzzeek** [comment]
> > Also, the usual practice is to store timestamps in UTC, which I've always advocated for and I don't find it to be brittle at all
> 
> Sorry, I should have been clearer. The brittleness comes from that, as far as I can tell, the `mssql.DateTime` type just truncates the `tzinfo` when writing (without converting to UTC, or even validating it), and returns a naive (zoneless) `datetime` when reading it back. It would be fine to convert to UTC when writing, and then always attach the UTC `tzinfo` back when reading.

that's easy to do with the current datetime types using a TypeDecorator, some examples of other kinds of operations are at https://docs.sqlalchemy.org/en/13/core/custom_types.html#typedecorator-recipes.   let me see if i can add one quick for timezones.

**Comment by zzzeek** [comment]
> I'm using pymssql, but that just seems to return the bytestring. Not a great outcome there either. I suppose the best path forward is to just use a validating `DecoratorType`.

so about that you might want to see https://github.com/pymssql/pymssql/issues/668  :(

**Comment by teozkr** [comment]
> so about that you might want to see pymssql/pymssql#668 :(

Ouch, thanks for the pointer. Not looking forward to dealing with the whole ODBC mess.

**Comment by zzzeek** [comment]
I will put this recipe on the site, give it a quick look over and make sure I didn't screw it up, seems to work:

```
import datetime

import pytz

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import DateTime
from sqlalchemy import Integer
from sqlalchemy import TypeDecorator
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session


class TZDateTime(TypeDecorator):
    impl = DateTime

    def process_bind_param(self, value, dialect):
        if value is not None:
            value = value.astimezone(pytz.utc)
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            value = pytz.utc.localize(value)
        return value


Base = declarative_base()


class StoreADate(Base):
    __tablename__ = "storeadate"

    id = Column(Integer, primary_key=True)
    data = Column(TZDateTime())


e = create_engine("mysql://scott:tiger@localhost/test", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

naive_date = datetime.datetime.strptime(
    "2013-10-21 08:44:08", "%Y-%m-%d %H:%M:%S"
)
localtz = pytz.timezone("America/Los_Angeles")
date_aware_la = localtz.localize(naive_date)


s.add(StoreADate(data=date_aware_la))
s.commit()


round_trip = s.query(StoreADate.data).first()[0]

assert round_trip == date_aware_la

```

**Comment by teozkr** [comment]
Looks good, but two nitpicks:

1. pytz isn't needed for UTC, [`datetime.timezone.utc`](https://docs.python.org/3/library/datetime.html#datetime.timezone.utc) should be enough (as of Python 3.2)
2. I'd rather fail loudly on naive objects rather than silently treat them as local time, especially given that you already opted into time zone awareness by using this type

**Comment by zzzeek** [comment]
yeah just noticed, new recipe:

```
import datetime

class TZDateTime(TypeDecorator):
    impl = DateTime

    def process_bind_param(self, value, dialect):
        if value is not None:
            if not value.tzinfo:
                raise TypeError("tzinfo is required")
            value = value.astimezone(datetime.timezone.utc).replace(
                tzinfo=None
            )
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            value = value.replace(tzinfo=datetime.timezone.utc)
        return value

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Base mssql.DATETIMEOFFSET on DateTime** https://gerrit.sqlalchemy.org/1579

**Comment by teozkr** [comment]
Seems to work great, thanks!
