### ISSUE TITLE
Can SQLAlchemy convert SQL Text to a SQLAlchemy Expression?

### ISSUE THREAD

**Issue by pmantica1** [sqlalchemy/sqlalchemy#4981]
I am asking because I want to figure out if I can use SQLAlchemy to parse view definitions to find the "primary keys" of views. (Many times the columns of a view can be mapped one-to-one with the columns of their underlying table. So one could theoretically use the view definition to find which columns of a view match the underlying table's primary key columns)

**Comment by zzzeek** [comment]
there's no SQL parsing in SQLAlchemy.    To the degree that some databases make us parse DDL for CREATE TABLE to figure out a table definition, that's all we do.   any kind of SQL expression however we don't do any parsing.  that's an entire subject area of its own for which you can look at something like https://github.com/andialbrecht/sqlparse/ .

**Comment by gordthompson** [comment]
@pmantica1 - I see from your comment in the other thread that you are aware of this:

https://github.com/pglass/sqlitis

**Comment by pmantica1** [comment]
I am sorry I thought that didn't SQLAlchemy didn't support this function, but I wanted to confirm. I should have phrased this question differently. Thank you for responding. I am sorry for the troubles.

**Comment by zzzeek** [comment]
no trouble at all I answer lots of questions on github now.
