### ISSUE TITLE
Use OAuth2 to connect to BigQuery

### ISSUE THREAD

**Issue by YannBrrd** [sqlalchemy/sqlalchemy#4982]
Hi,

Is it somehow possible to use user identity through oauth2 to connect to bigquery (user account, not technical or anything)? 

Thanks.

**Comment by zzzeek** [comment]
hi there -

we don't maintain the bigquery driver here and I know nothing about it.  I'm assuming this is "pybigquery" that's listed on the site, they are over here: https://github.com/mxmzdlv/pybigquery/

**Comment by YannBrrd** [comment]
OK, going there : )

**Comment by YannBrrd** [comment]
https://github.com/mxmzdlv/pybigquery/issues/42
