### ISSUE TITLE
Improving DATETIMEOFFSET support for mssql+pyodbc

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#4983]
At the moment (as of 1acc675), mssql+pyodbc will throw an error if SQL Server returns a `datetimeoffset` value (e.g., when using ODBC Driver 17 for SQL Server):

```python
dto_str = '2019-11-14 11:23:45 -07:00'
sql = sa.text(f"SELECT CAST('{dto_str}' AS datetimeoffset)")
result = engine.execute(sql).fetchone()[0]
```

> pyodbc.ProgrammingError: ('ODBC SQL type -155 is not yet supported.  column-index=0  type=-155', 'HY106')

I have written the code to add an `on_connect` method to lib/sqlalchemy/dialects/mssql/pyodbc.py and verified that it avoids the above error, instead returning a timezone-aware `datetime` object:

```python
print(type(result))
# <class 'datetime.datetime'>
print(repr(result))
# datetime.datetime(2019, 11, 14, 11, 23, 45, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)))
print(result)
# 2019-11-14 11:23:45-07:00
```

I just need a little help with 

1. Integrating the code to convert a timezone-aware `datetime` into the string format required for INSERT and UPDATE, defined [here](https://github.com/mkleehammer/pyodbc/wiki/Tips-and-Tricks-by-Database-Platform#datetimeoffset-columns-eg-odbc-sql-type--155-is-not-yet-supported). (Do I need to create a `bind_processor` for that, perhaps in [here](https://github.com/sqlalchemy/sqlalchemy/blob/1acc675e3f46786afe87dbe384f5970136e2e507/lib/sqlalchemy/dialects/mssql/base.py#L1022)?)

2. Adding some tests. I notice that test/dialect/postgresql/test_types.py has some timezone tests [here](https://github.com/sqlalchemy/sqlalchemy/blob/1acc675e3f46786afe87dbe384f5970136e2e507/test/dialect/postgresql/test_types.py#L794), but I wonder if it might be preferable to move those tests into the suite.

**Comment by gordthompson** [comment]
Related pyodbc issue:

https://github.com/mkleehammer/pyodbc/issues/134

**Comment by zzzeek** [comment]
the string format thing happens in the bind_processor() method, yes.

I'm wondering why pyodbc has this bug such that they actually went and added a whole wiki recipe to work around it?   why can't pyodbc fix the bug on their end?    There's been no call for the DATETIMEOFFSET type to actually work so I'm not sure if it's worth adding a bunch of intricate code here when we could just be fixing pyodbc.

**Comment by gordthompson** [comment]
ODBC type -155 (SQL_SS_TIMESTAMPOFFSET) is a SQL_Server-specific extension. As described [here](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-date-time/data-type-support-for-odbc-date-and-time-improvements?view=sql-server-ver15), it is defined in SQLNCLI.h (for SQL Server Native Client), not in sql.h or sqlext.h (for core ODBC).

So this is not a bug in pyodbc, it is an unimplemented database-specific feature. As such, the code to handle it belongs in a database-specific dialect like mssql+pyodbc, rather than in pyodbc itself.

**Comment by gordthompson** [comment]
Okay, so I added a `bind_processor` to the DATETIMEOFFSET class

```
Index: lib/sqlalchemy/dialects/mssql/base.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/sqlalchemy/dialects/mssql/base.py	(revision 1acc675e3f46786afe87dbe384f5970136e2e507)
+++ lib/sqlalchemy/dialects/mssql/base.py	(date 1573819735240)
@@ -1026,6 +1026,12 @@
         super(DATETIMEOFFSET, self).__init__(**kw)
         self.precision = precision
 
+    def bind_processor(self, dialect):
+        """Convert to string format required by T-SQL."""
+        dto_string = self.strftime("%Y-%m-%d %H:%M:%S %z")
+        # offset needs a colon, e.g., -0700 -> -07:00
+        return dto_string[:23] + ":" + dto_string[23:]
+
 
 class _UnicodeLiteral(object):
     def literal_processor(self, dialect):
```

but it does not seem to have any effect. When I try ...

```python
dto = datetime.datetime(2019, 11, 14, 11, 23, 45, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)))
df = pd.DataFrame([(dto,)], columns=['dto'])
from sqlalchemy.dialects.mssql import DATETIMEOFFSET
dtype_dict = {'dto': DATETIMEOFFSET}
df.to_sql('#tmp', engine, index=False, if_exists='replace', dtype=dtype_dict)
#
print("Table contents:")
print(engine.execute("SELECT * FROM #tmp").fetchall())
```

... I still get the parameter value being passed as a `datetime` object, which causes the offset to be dropped (effectively converting it to UTC):

```
2019-11-15 07:30:43,169 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE [#tmp] (
	dto DATETIMEOFFSET NULL
)


2019-11-15 07:30:43,169 INFO sqlalchemy.engine.base.Engine ()
2019-11-15 07:30:43,171 INFO sqlalchemy.engine.base.Engine COMMIT
2019-11-15 07:30:43,173 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-11-15 07:30:43,173 INFO sqlalchemy.engine.base.Engine INSERT INTO [#tmp] (dto) VALUES (?)
2019-11-15 07:30:43,174 INFO sqlalchemy.engine.base.Engine (datetime.datetime(2019, 11, 14, 11, 23, 45, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200))),)
2019-11-15 07:30:43,176 INFO sqlalchemy.engine.base.Engine COMMIT
2019-11-15 07:30:43,176 INFO sqlalchemy.engine.base.Engine SELECT * FROM #tmp
2019-11-15 07:30:43,176 INFO sqlalchemy.engine.base.Engine ()

Table contents:
[(datetime.datetime(2019, 11, 14, 11, 23, 45, tzinfo=datetime.timezone.utc),)]
```

Is there another place in the code where I need to enable the bind_processor?

**Comment by zzzeek** [comment]
Hi Gord -

I would suggest testing with SQLAlchemy constructs directly rather than adding the additional layer of indirection of Pandas.

Addititionally, the form of bind_processor() is that a callable function should be returned.   See https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mssql/base.py#L925 for an example.

ideally the bind processor we're doing here would be better off in the mssql/pyodbc.py file, but that requires an additional step for that to work.  let's get the simple version working first :)

**Comment by gordthompson** [comment]
Okay, thanks. I should have looked around for other examples. I've updated my `bind_processor` to

```
Index: lib/sqlalchemy/dialects/mssql/base.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/sqlalchemy/dialects/mssql/base.py	(revision 1acc675e3f46786afe87dbe384f5970136e2e507)
+++ lib/sqlalchemy/dialects/mssql/base.py	(date 1573840451691)
@@ -1026,6 +1026,15 @@
         super(DATETIMEOFFSET, self).__init__(**kw)
         self.precision = precision
 
+    def bind_processor(self, dialect):
+        def process(value):
+            """Convert to string format required by T-SQL."""
+            dto_string = value.strftime("%Y-%m-%d %H:%M:%S %z")
+            # offset needs a colon, e.g., -0700 -> -07:00
+            return dto_string[:23] + ":" + dto_string[23:]
+
+        return process
+
 
 class _UnicodeLiteral(object):
     def literal_processor(self, dialect):
```

but tracing through the code shows that it's not being called. Instead, the `bind_processor` for the `_DateTimeBase` class [here](https://github.com/sqlalchemy/sqlalchemy/blob/1acc675e3f46786afe87dbe384f5970136e2e507/lib/sqlalchemy/dialects/mssql/base.py#L996
) is still getting invoked:

**Comment by zzzeek** [comment]
ah OK well that helps explain the issue , moment

**Comment by zzzeek** [comment]
so for that bind_procsesor to take effect you need this:

```
diff --git a/lib/sqlalchemy/dialects/mssql/base.py b/lib/sqlalchemy/dialects/mssql/base.py
index ded90c348..1c88872b4 100644
--- a/lib/sqlalchemy/dialects/mssql/base.py
+++ b/lib/sqlalchemy/dialects/mssql/base.py
@@ -1026,6 +1026,14 @@ class DATETIMEOFFSET(_DateTimeBase, sqltypes.DateTime):
         super(DATETIMEOFFSET, self).__init__(**kw)
         self.precision = precision
 
+    def bind_processor(self, dialect):
+        def process(value):
+            """Convert to string format required by T-SQL."""
+            dto_string = value.strftime("%Y-%m-%d %H:%M:%S %z")
+            # offset needs a colon, e.g., -0700 -> -07:00
+            return dto_string[:23] + ":" + dto_string[23:]
+
+        return process
 
 class _UnicodeLiteral(object):
     def literal_processor(self, dialect):
@@ -2276,6 +2284,7 @@ class MSDialect(default.DefaultDialect):
         sqltypes.Time: TIME,
         sqltypes.Unicode: _MSUnicode,
         sqltypes.UnicodeText: _MSUnicodeText,
+        DATETIMEOFFSET: DATETIMEOFFSET
     }
 
     engine_config_types = default.DefaultDialect.engine_config_types.union(

```

however, it works for me without the bind procsesor as well, are you saying the tzinfo is silently ignored in that case?

**Comment by zzzeek** [comment]
also as far as the tests, we'd be looking in test/dialect/mssql/test_types.py ->TypeRoundTripTest, which are old tests that are an absolute mess and that fixture needs to be rewritten.   You can add an individual test for the DATETIMEOFFSET outside of all the other tests there using `@testing.provide_metadata`.

**Comment by gordthompson** [comment]
Yup, adding that `colspec` entry did the trick. Thanks.

For a test I just added a DATETIMEOFFSET column to the table in test_date_roundtrip.

I ran `tox -e py36-mssql` on Linux and got "9866 passed, 1138 skipped in 881.61s (0:14:41)". (No failures.)

So what do we need to do to move the bind_processor into mssql/pyodbc.py?

**Comment by zzzeek** [comment]
so go into pyodbc.py, and make a new type called _ODBCDateTimeOffset(DATETIMEOFFSET), e.g. subclass of the type we are using, and put the bind_processor() there.  then, move the "colspec" entry over to the pyodbc dialect:    "DATETIMEOFFSET: _ODBCDateTimeOffset", so that when a type that has DATETIMEOFFSET in it's mro is used, it will pull up _ODBCDateTimeOffset.

**Comment by gordthompson** [comment]
Done. All tests pass on Linux. Thanks again for your help.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add DATETIMEOFFSET support for mssql+pyodbc** https://gerrit.sqlalchemy.org/1584

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Add DATETIMEOFFSET support for mssql+pyodbc** https://gerrit.sqlalchemy.org/1596

**Comment by zzzeek** [comment]
someone had done a little bit of this work back in 2016 but abandoned it: https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/128/

**Comment by MarcoOttinaUC** [comment]
I will paste the error text here _just because_ any search engine I've used (Google, Ecosia) does not make this page to appear within the results; I lost hours before finding it and I wish no other developers will waste more than a single minute.
Hope it helps.

pyodbc.ProgrammingError: ('ODBC SQL type -155 is not yet supported. column-index=0 type=-155', 'HY106')

**Comment by CaselIT** [comment]
strange since that error message is in the issue first post. not sure if there is anything that could be done on out end to make these page indexable by search engines
