### ISSUE TITLE
Fetchall doesn't retrieve all rows

### ISSUE THREAD

**Issue by aliya1303** [sqlalchemy/sqlalchemy#4985]
Good evening!
We have a problem while executing following code:

import sqlalchemy as db
import pandas as pd
import cx_Oracle 

engine = db.create_engine("oracle+cx_oracle://{user}:{pw}@{host}:{port}/{db}"
                        .format(user = "usr",
                        pw = "pwd",
                        host = "host",
                        port = "port",
                        db = "db"), encoding='utf8', echo=True)

metadata = db.MetaData()
connection = engine.connect()

connection.execute("ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF'")

data = "select * from big_view"
df = pd.read_sql(data, connection)

print(df.shape)

connection.close()

Instead of geting 2 mil rows i get only about 200k rows.

**Comment by zzzeek** [comment]
hi.

so, there's nothing in SQLAlchemy that has anything to do with whether you get 200K or 2M rows.   The only thing that in theory even affects that is the uniquifying that happens in the ORM, but you're not using any of those features here.

So you problem is with one (or maybe more) of:

a. pandas
b. your query
c. your view
d. the cx_Oracle driver

Right now I'm going to lean on a. and c. as your most likely culprits.

To look more closely, here are your steps:

1. run this:
    print(connection.scalar("select count(*) from big_view"))
 
confirm it retuns the number 2,000,000.

2. run this:
    results = connection.execute("select * from big_view").fetchall()
    print(len(results))

confirm that's 2M.

Also I'd consider looking around pandas docuemntation / mailing lists to see if there is some 200K  limit or deduplication going on.   Does your view return duplicate rows that are perhaps being deduplicated?

**Comment by aliya1303** [comment]
hi again,

I tried 
       1. run this:
       print(connection.scalar("select count(*) from big_view"))
and 
      2. run this:
      results = connection.execute("select * from big_view").fetchall()
      print(len(results))
but it still 200k rows in the results. 

So even if we don't use pandas something cut our data. BTW there is no duplicated rows in my big_view, also there is not any key-like row, i mean every column has some gaps .

I have one little question. Do we need to have a key-like column? Does it affect on reading query?

**Comment by aliya1303** [comment]
Well, i tried to execute `"select rownum as id_row, t.* from cxfocus_data t"` but it doesn't help. There is still 200k rows in result, instead of 2m...

**Comment by zzzeek** [comment]
did the "select count" show you 2M ?

**Comment by aliya1303** [comment]
no, it shows 188 880 (about 200k rows)

**Comment by cjbj** [comment]
Sounds like you actually only have 188880 rows in the view.

**Comment by aliya1303** [comment]
select * from big_view in pl/sql developer returns 2m rows...

**Comment by aliya1303** [comment]
Thank you for answering me,

I tried to use only cx_Oracle, but it does not help. The following code also returns 200k rows instead of 2m:

import cx_Oracle 

dsn_tns = cx_Oracle.makedsn('host', 'port', service_name='service_name') 
conn = cx_Oracle.connect(user='user', password='pwd', dsn=dsn_tns) 

cur = conn.cursor()
cur.arraysize = 10000
cur.execute("ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF'")
cur.execute("select count(*) from cxfocus_data")
df = []
for row in cur:
    df.append(row)

print(df)

conn.close()
What shoul i do to get all data?
Select from view in Sql developer returns about 2 m rows.

**Comment by aliya1303** [comment]
ok, i tried to receive data from another table (330000 rows x 54 columns), and get only 168000 rows.
Is there any restrictions as memory restrictions?

**Comment by zzzeek** [comment]
hi -

it's important to understand that "select count(*) from view" from the client perspective is an extremely simple query that uses no significant memory resources or anything else like that.  this is directly what your Oracle database reports as the number of rows available to SELECT from those views.      It is the most authoritative answer as to how many rows the thing you are SELECTing from has and it is more accurate than whatever the "sql developer" tool is.

it's still unclear exactly what you are doing, however, if you have a split between tables and views which are against those tables, if the difference in rows is between the view vs. the table, then this would correspond to how the view is constructed.

it is also a common occurrence that you are simply connecting to a different database when you are using your Python scripts vs. when you use this "sql developer" tool, which perhaps is configured differently.   have you confirmed that you are definitely looking at the same database with both of these tools?

**Comment by anthony-tuininga** [comment]
And make sure you are connecting as the same user. Depending on the construction of the view, you may be having rows limited for particular users.

**Comment by aliya1303** [comment]
Hi again,

```
import sqlalchemy as db
import pandas as pd
**import os
os.environ["NLS_LANG"] = "Russian.AL32UTF8"**
import cx_Oracle 

engine = db.create_engine("oracle+cx_oracle://{user}:{pw}@{host}:{port}/{db}"
                        .format(user = "user",
                        pw = "pwd",
                        host = "host",
                        port = "port",
                        db = "db"), encoding='utf8', echo=True)

metadata = db.MetaData()
connection = engine.connect()
cxfocus_data = " select * from cxfocus_data t2"

df = pd.read_sql(cxfocus_data, connection)
df.to_csv('tmp.csv')
print(df.shape)

connection.close()

``` 

os.environ["NLS_LANG"] = "Russian.AL32UTF8" solved our problem. Now we get from db all expected rows .

Thank you very much for answering my questions :))

**Comment by cjbj** [comment]
That is unexpected.

**Comment by zzzeek** [comment]
i'll leave it to the oracle devs here how the encoding can possibly create 1.8M new rows
