### ISSUE TITLE
Confusing behavior when Table() isn't given positional arguments

### ISSUE THREAD

**Issue by nchammas** [sqlalchemy/sqlalchemy#4988]
I prefer to use keyword arguments over positional arguments whenever possible, because they are clearer to the reader and don't leave you guessing over whether you've passed things in in the wrong order.

So like a good boy I wrote the following bit of code:

```python
some_table = sqlalchemy.Table(
    name='le_table_name',
    metadata=sqlalchemy.MetaData(bind=session.get_bind()),
    schema='la_schema',
)

<a few moments later>

if not some_table.bind:
    raise ValueError("Table metadata must include connection binding.")
```

The lookup on `some_table.bind` yielded the following error:

```
Traceback (most recent call last):
  ...
  File ".../venv/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 755, in bind
    return self.metadata and self.metadata.bind or None
AttributeError: 'Table' object has no attribute 'metadata'
```

I could _not_ understand what was going on, since I had clearly provided a value to `metadata` when creating `some_table`! After going on some wild goose chases, I calmed down and realized that my snippet of code was exercising [this path](https://github.com/sqlalchemy/sqlalchemy/blob/ed2c5f9ad1f92010e447797576ab4eef3beee21f/lib/sqlalchemy/sql/schema.py#L445-L447). Somehow, that led to the above error.

The fix was simple--convert `name` and `metadata` into positional arguments:

```python
some_table = sqlalchemy.Table(
    'le_table_name',
    sqlalchemy.MetaData(bind=session.get_bind()),
    schema='la_schema',
)
```

I'm happy I got things working, but this seems like a strange restriction to live with. I assume it's because of the [column list specification](https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=table#sqlalchemy.schema.Table.params.*args) in `Table()`'s signature.

Can we improve the error that gets thrown when the user makes the same mistake I did? And is there some backwards-compatible way to allow `name` and `metadata` to be passed in as keyword arguments?

For the record:
* Python 3.5.8
* SQLAlchemy 1.3.10
* sqlalchemy-redshift 0.7.5

**Comment by zzzeek** [comment]
SQLAlchemy 2.0 will be Python 3 only, and eventually when Python 3.8 is the oldest python we support, and then we can use [positional only arguments](https://www.python.org/dev/peps/pep-0570/).   

as for currently, I don't really know what approach would be taken besides some isinstance() checks, I can accept a PR that provides tests in test/sql/test_metadata.py.

**Comment by nchammas** [comment]
Do you remember the reason for [this snippet of code](https://github.com/sqlalchemy/sqlalchemy/blob/ed2c5f9ad1f92010e447797576ab4eef3beee21f/lib/sqlalchemy/sql/schema.py#L445-L447)? I'm not clear on how it helps, and simply removing it would yield a much clearer error message in the example I provided above. I'm guessing some of the tests in [test_metadata.py](https://github.com/sqlalchemy/sqlalchemy/blob/master/test/sql/test_metadata.py) with `pickle` in their name depend on it. I'll take a look and see if I can make a minimally-invasive change to improve things.

**Comment by nchammas** [comment]
I'm afraid I'm a bit out of my depth here. I've figured out that in order to get rid of the [pickle workaround inside `Table`](https://github.com/sqlalchemy/sqlalchemy/blob/ed2c5f9ad1f92010e447797576ab4eef3beee21f/lib/sqlalchemy/sql/schema.py#L445-L447) we need to implement [`__getnewargs_ex__()`](https://docs.python.org/3/library/pickle.html#object.__getnewargs_ex__), but I wasn't able to get something working.

Part of it is because I don't know how to reliably get all keyword arguments passed to `Table` from within `__getnewargs_ex__()`. I see that the object passed to `__getnewargs_ex__()` has a `kwargs` attribute, but it's of type `_DialectArgView`, which doesn't directly convert to a dict. This is a problem because:

> The method must return a pair `(args, kwargs)` where _args_ is a tuple of positional arguments and _kwargs_ a dictionary of named arguments for constructing the object.

I'm going to close this for now and hope that my post here is enough to reach others who make the same, simple mistake I did.
