### ISSUE TITLE
Duplicated delete query has been emitted over secondary relationship

### ISSUE THREAD

**Issue by Sheile** [sqlalchemy/sqlalchemy#4991]
### Environment
SQLAlchemy: 1.3.5 or 1.3.11
PostgreSQL: 9.6
Python: 3.7.4

### Problem
When delete parent model which has a relationship to children via secondary table, and a relationship to secondary table directly, duplicated delete queries on same instance have been emitted and report SAWarning.

IMO, Unexpectedly `db.session.deleted` keep deleted instance after delete record in secondary table automatically.

Following logs are outputted when delete parent record. (Some comments are my opinion)
```
# Delete automatically by secondary relationship
# https://docs.sqlalchemy.org/en/13/orm/cascades.html#delete
2019-11-19 14:30:03,653 INFO sqlalchemy.engine.base.Engine DELETE FROM user_assignments WHERE user_assignments.user_id = %(user_id)s AND user_assignments.account_id = %(account_id)s
2019-11-19 14:30:03,654 INFO sqlalchemy.engine.base.Engine ({'user_id': 8, 'account_id': 6}, {'user_id': 8, 'account_id': 51})

# Delete automatically by explicitly cascade
# Unexpectedly db.session.deleted keep deleted instance?
2019-11-19 14:30:03,655 INFO sqlalchemy.engine.base.Engine DELETE FROM user_assignments WHERE user_assignments.user_id = %(user_id)s AND user_assignments.account_id = %(account_id)s
2019-11-19 14:30:03,656 INFO sqlalchemy.engine.base.Engine ({'user_id': 8, 'account_id': 6}, {'user_id': 8, 'account_id': 51}, {'user_id': 8, 'account_id': 987})

# Report SAWarning due to part of user_assignments are already deleted.
/home/centos/.pyenv/versions/3.7.4/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py:1367: SAWarning: DELETE statement on table 'user_assignments' expected to delete 3 row(s); 1 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
```

### Reproduce
We have two models `Account` and `User`.
These models have many-to-many relation via `UserAssignment` model which has data for email confirmation status.

```
class Account(db.Model):
  users = db.relationship('User', secondary='user_assignments', back_populates='accounts', lazy='dynamic',
                           secondaryjoin='''and_(User.id == UserAssignment.account_id,
                                                 UserAssignment.confirmed_at.isnot(None))''')

  assignments = db.relationship('UserAssignment', cascade='all, delete-orphan', lazy='dynamic')
```

```
select * from user_assignments where user_id = 8;
 user_id | account_id |         confirmed_at          
---------+------------+-------------------------------
       8 |          6 | 2017-05-19 16:21:38.938036+00 
       8 |        987 |                               
       8 |         51 | 2019-09-27 05:38:53.467833+00 
```

```
user = User.query.get(8)
db.session.delete(user)
db.session.deleted
# IdentitySet([<User 8>, <UserAssignment 8, 6>, <UserAssignment 8, 987>, <UserAssignment 8, 51>])

db.session.flush()
```

**Comment by zzzeek** [comment]
hi there -

can you please supply the models as well as an [MCVE](http://stackoverflow.com/help/mcve).   Your secondaryjoin as written does not make sense because it seems to be matching "user_assignment.account_id == user.id", so when I tried to guess what this table might look like, it has a, "account_account_id" that links to "account.id" ?  it's not clear.  thanks in advance.

**Comment by Sheile** [comment]
Thank you for quick reply and I'm sorry for confusion due to my mistake while reducing our code to example.
I've attached MCVE example, please check it.

[example.zip](https://github.com/sqlalchemy/sqlalchemy/files/3867313/example.zip)

#### 1. import `sql.sql` to `sqlalchemy_test` database on postgres.
```
$ psql postgresql://user:password@127.0.0.1/sqlalchemy_test < sql.sql
```

#### 2. execute `example.py`
```
$ python example.py
...
2019-11-20 13:27:29,303 INFO sqlalchemy.engine.base.Engine DELETE FROM user_assignments WHERE user_assignments.user_id = %(user_id)s AND user_assignments.account_id = %(account_id)s
2019-11-20 13:27:29,303 INFO sqlalchemy.engine.base.Engine ({'user_id': 8, 'account_id': 6}, {'user_id': 8, 'account_id': 51})
2019-11-20 13:27:29,304 INFO sqlalchemy.engine.base.Engine DELETE FROM user_assignments WHERE user_assignments.user_id = %(user_id)s AND user_assignments.account_id = %(account_id)s
2019-11-20 13:27:29,305 INFO sqlalchemy.engine.base.Engine ({'user_id': 8, 'account_id': 6}, {'user_id': 8, 'account_id': 51}, {'user_id': 8, 'account_id': 987})
/home/centos/.pyenv/versions/3.7.4/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py:1367: SAWarning: DELETE statement on table 'user_assignments' expected to delete 3 row(s); 1 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
  % (table.description, expected, rows_matched)
...
```

**Comment by zzzeek** [comment]
your mapping has a well known mistake documented at https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html#association-object:

> Warning

> The association object pattern does not coordinate changes with a separate relationship that maps the association table as “secondary”.

The User.assignments relationship and the User.accounts relationship are both separately doing the DELETE.   One of them has to be set up as viewonly=True and the cascade flag removed:

    # Include accounts that haven't confirmed yet
    assignments = relationship(
        "UserAssignment",
        #cascade="all, delete-orphan",
        lazy="dynamic",
        viewonly=True
    )

There is a bit of a bug I just noticed in that if you set viewonly=True and cascade, the cascade rule takes effect, which is wrong, I will address that in a separate issue.

**Comment by Sheile** [comment]
Thank you for appropriate advice and the document!

I've set `viewonly=True` on `accounts` relationship with secondary.
Unnecessary delete query isn't executed successfully.
Please close this issue if you want.

note: When add `viewonly=True` on `assignments` and remove `cascade`, will fail when delete `User` due to remain reference from unconfirmed assignment.
