### ISSUE TITLE
cascade set on relationship ignores viewonly=True

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4993]
sort of amazing but there it is, the B rows get deleted:

```

from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs=[B()]))
s.commit()
```

new logic should warn if these are both set, then the DELETE should not take place

**Comment by zzzeek** [comment]
OK, for 1.3.x we only warn, in 1.4, delete does not take place, because this could be a big one

**Comment by zzzeek** [comment]
ref #4991

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Warn for settings that don't work with viewonly=True** https://gerrit.sqlalchemy.org/1582

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Warn for settings that don't work with viewonly=True** https://gerrit.sqlalchemy.org/1583
