### ISSUE TITLE
don't delete / do any persistence.py if viewonly=True even if cascade is set

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4994]
see demonstration case in #4993 which will emit a warning.  this issue is to take the delete out in 1.4 only

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Raise for persistence casades set with viewonly=True** https://gerrit.sqlalchemy.org/1588
