### ISSUE TITLE
add memory usage to examples.performance.Profiler

### ISSUE THREAD

**Issue by sumau** [sqlalchemy/sqlalchemy#4999]
I have added memory usage to my clone of examples.performance.Profiler. I was wondering if it would be helpful to other people as well? Would be happy to create a pull request.

[__init__.txt](https://github.com/sqlalchemy/sqlalchemy/files/3882307/__init__.txt)

**Comment by zzzeek** [comment]
hi -

did you notice anything interesting about the memory use in those particular tests ? I ask because they're not really doing things that are unusual in their memory use.   that is, there's places to look at memory consumption but it's usually when someone has lots of ORM models, lots of engines, or one is looking for a memory leak.

**Comment by zzzeek** [comment]
Feel free to reopen and show the code you've worked up.

**Comment by sumau** [comment]
Sorry for delay! Memory usage was as expected for both sqlite and postgres - results attached if you're interested :-) I did have to commit some sessions in short_selects.py for the script to complete - is it worth me raising a pull request just to modify short_selects.py?

[memory.txt](https://github.com/sqlalchemy/sqlalchemy/files/3904708/memory.txt)

**Comment by zzzeek** [comment]
I guess your code is in the ".txt" file you attached originally.    I'm not really enthused about a third party dependency and like the "runsnake" dependency (which unfortunately is abandonware and doesn't even work anymore) that would have to be invoked only if someone uses that option.

the run attached does not seem to be actually running all those suites?   those runs are all from the bulk_inserts script.    also if those memory results are in megabytes, they don't look that interesting?   30M vs. 50M for a more automated approach is not something that would steer a decision either way.

**Comment by sumau** [comment]
oops correct results attached, which are not interesting either, so happy to conclude things here :-)
[memory.txt](https://github.com/sqlalchemy/sqlalchemy/files/3906260/memory.txt)

**Comment by zzzeek** [comment]
OK :)   Sorry, I don't know that this  example suite is that popular in any case , if we had a memory suite that shows how things change that would be more interesting, mostly in the area of result set behavior which we've discussed before (e.g. buffered vs non).
