### ISSUE TITLE
Association proxy for composites has stopped working from version 1.3

### ISSUE THREAD

**Issue by abhaykadam** [sqlalchemy/sqlalchemy#5000]
I am getting below error in my application:

```bash
api_1             |   File "/app/src/hoist/api/application/AppService.py", line 509, in create_app_field_config
api_1             |     field.references = settings.references or ()
api_1             |   File "/cache/local/lib/python2.7/site-packages/sqlalchemy/ext/associationproxy.py", line 202, in __set__
api_1             |     return self._as_instance(class_, obj).set(obj, values)
api_1             |   File "/cache/local/lib/python2.7/site-packages/sqlalchemy/ext/associationproxy.py", line 249, in _as_instance
api_1             |     inst = AssociationProxyInstance.for_proxy(self, owner, obj)
api_1             |   File "/cache/local/lib/python2.7/site-packages/sqlalchemy/ext/associationproxy.py", line 381, in for_proxy
api_1             |     target_assoc, parent, owning_class, target_class, value_attr
api_1             |   File "/cache/local/lib/python2.7/site-packages/sqlalchemy/ext/associationproxy.py", line 398, in _construct_for_assoc
api_1             |     is_object = attr._impl_uses_objects
api_1             |   File "/cache/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 393, in __getattr__
api_1             |     attribute,
api_1             | AttributeError: Neither 'property' object nor 'Comparator' object associated with ApplicationFieldReference.ref has an 
attribute '_impl_uses_objects'
```

The classes that i have loosely looks like:
```python
class ApplicationFieldReference(Base):
    __tablename__ = "app_field_ref"

    field_id = Column(Integer, ForeignKey("app_field.field_id"), primary_key=True)
    ref_type = Column(EnumType(30, ReferenceType), primary_key=True)
    ref_id = Column(Integer, primary_key=True, autoincrement=False)
    ref = composite(Reference, ref_type, ref_id)


class ApplicationField(Base, BaseApplicationField):
    __tablename__ = "app_field"

    field_id = Column(Integer, primary_key=True)
    app_id = Column(Integer, ForeignKey("app.app_id"), nullable=False)
    app = relation("Application")
    type = Column(Unicode(120), nullable=False)

    config = relation(ApplicationFieldConfig,
                      primaryjoin=and_(field_id == ApplicationFieldConfig.field_id,
                                       ApplicationFieldConfig.revision_to == None),
                      uselist=False,
                      viewonly=True)

    _references_relation = relation("ApplicationFieldReference", cascade='all, delete-orphan',
                                    primaryjoin=field_id == ApplicationFieldReference.field_id)
    references = association_proxy('_references_relation', 'ref',
                                   creator=lambda ref: ApplicationFieldReference(ref=ref))
```

Things are working fine with sqlalchemy till version 1.2.19; but, 1.3 onward, it started throwing the above error.

I checked a little bit, and the commit 90574aabef36fd59841b7df7d8ac30e2030e9854, is where it starts failing.

**Comment by zzzeek** [comment]
hi there -

can you please provide all the details you have.   your stack trace indicates you are setting a value on an object, can you provide a sample of those objects and the set operation which reproduces the bug?    Otherwise I have to try to guess how to reproduce this and is this is a likely ORM regression I'd like to get a fix in ASAP.

**Comment by abhaykadam** [comment]
@zzzeek , thanks for looking into the issue!

My code snippet which triggers the issue is:

```python
def create_app_field_config(field, config_data):
    config = ApplicationFieldConfig(field,
                                    label=config_data.label)

    field.config = config
    field.references = settings.references or ()
```

The `field` parameter contains:
```python
<ApplicationField app_id:38706 field_id:206465 type:text>
```

I get the exception when it tries to execute:
```python
 field.references = settings.references or ()
```

The `settings` variable contains:
```python
TextFieldSettings({'_fmt': None, 'size': TextSize.small})
```

And, `settings.references` evaluates to `None`:

The `references`, which, as mentioned above in the issue description, is a member of `ApplicationFieldReference` class, and is a composite column.

Definition of `Reference`:
```python
class Reference(namedtuple("_Reference", ("type", "id")), Jsonifiable):
   # some other methods, like __repr__(), __str__(), from_string(), from_json(), etc.

    def __composite_values__(self):
        return self
```

Please let me know if you need more info onto this.

**Comment by zzzeek** [comment]
thanks.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Generalize DescriptorProps.uses_objects** https://gerrit.sqlalchemy.org/1589

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Generalize DescriptorProps.uses_objects** https://gerrit.sqlalchemy.org/1590

**Comment by zzzeek** [comment]
there's a patch that you can download from https://gerrit.sqlalchemy.org/changes/1590/revisions/6bef95307862286f1d53b887c20d03344284d948/patch?zip , or otherwise use one of the methods in the top right of https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1590/ .  if you can confirm this resolves your issue and there are no further issues that would add more confidence to this, although I'm pretty sure I got the immediate issue you are having.

**Comment by abhaykadam** [comment]
Hi @zzzeek, the issue is resolved now. All my project's testcases, which were failing because of this, are passing. Thank you for quickly fixing it.
