### ISSUE TITLE
MetaData becomes unpickleable when you pass an InstrumentedAttribute into the ForeignKey(column=) argument

### ISSUE THREAD

**Issue by matthewgdv** [sqlalchemy/sqlalchemy#5001]
As mentioned in the title:

```
class Parent(Base):
    __tablename__ = "parent"
    id = Column(Integer, primary_key=True)


class Child(Base):
    __tablename__ = "child"
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey(Parent.id))

    parent = relationship(Parent, backref=backref("children", uselist=True, cascade="all"))

pickle.dumps(Base.metadata)  # error
```

but this works:

```
class Parent(Base):
    __tablename__ = "parent"
    id = Column(Integer, primary_key=True)


class Child(Base):
    __tablename__ = "child"
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey("parent.id"))

    parent = relationship(Parent, backref=backref("children", uselist=True, cascade="all"))

pickle.dumps(Base.metadata)  # works fine
```

It looks like this happens because the ForeignKey object keeps a reference to the InstrumentedAttribute as its ForeignKey._colspec instance attribute, which then causes the MetaData to have a reference into the entire ORM layer. Obviously this is bad because it means the pickler will try to pickle all of the model classes which were dynamically created at runtime and therefore cannot be pickled.

I've fixed it for myself in the interim by subclassing ForeignKey like so:

```
class ForeignKey(sqlalchemy.ForeignKey):
    def __init__(self, column: Any, *args: Any, **kwargs: Any) -> None:
        super().__init__(column=f"{column.comparator.table.name}.{column.comparator.key}" if isinstance(column, InstrumentedAttribute) else column, *args, **kwargs)
```

But this isn't really an ideal solution. I'm not familiar enough with the sqlalchemy internals to know what the cleanest and least wasteful way to fix this would be. 

Also, I have the sneaking suspicion that other sqlalchemy constructs similar to ForeignKey (like maybe Index, CheckConstraint, etc.) might have the exact same issue if they're implemented the same way. I haven't tested this though.

Any chance this could be looked at as a bugfix? Cheers!

**Comment by zzzeek** [comment]
please use:

    ForeignKey(Parent.id.expression)

for now.   it is not a given that ForeignKey can just do a conversion internally, would have to find time to look at it.

**Comment by matthewgdv** [comment]
Thanks for the quick response @zzzeek! That is definitely cleaner than what I was doing and avoids having string literals in my code (which I dislike a lot, since it means refactor/rename and linters don't work properly). This is an extremely low-priority bug, but at the very least there's now an issue against it, so the next unlucky soul who happens to run into this trap has something to google.

I'm not exaggerating when I say I spent like 5 hours chasing through the 5-million layers deep recursive stack trace of the pickler to figure out what exactly was causing the error.

Thanks again :)

**Comment by matthewgdv** [comment]
Actually @zzzeek, I just tested your solution (using `InstrumentedAttribute.expression`) and it still doesn't work.

Looking at the contents of the `AnnotatedColumn` object, it looks like it has a reference to the ORM layer through the `AnnotatedColumn._annotations` instance attribute (which contains a dictionary with the keys 'parententity' and 'parentmapper', which reference mappers, which then reference the actual class model class).

Currently, using a string there seems to be the only way I can find to keep the MetaData pickleable.

**Comment by zzzeek** [comment]
OK workaround for the moment call "expression._deannotate()", i need to think about this in terms of other kinds of schema objects also.   if i make an across-the-board setup to deannotate everything that goes into schema, like if you made a UniqueConstraint or things like that, that's a more fundamental change and would be better as a 1.4 thing.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Try to remove ORM elements at the schema level.** https://gerrit.sqlalchemy.org/1591

**Comment by zzzeek** [comment]
I can fix this for trivial examples like yours but for things like CheckConstraint with expressions, there needs to be some more fundamental approach.

what is the error you are getting with your pickle?

**Comment by zzzeek** [comment]
I can fix it for 1.4.  For 1.3, I have to add a lot more code which increases risk.   targeting at 1.4 for now.

**Comment by zzzeek** [comment]
finally I'd also be curious what your "pickle metadata" use case is, it's not a common case especially with a declarative ORM model.

**Comment by matthewgdv** [comment]
The error that pickle throws is:
```
PicklingError: Can't pickle <function __init__ at 0x0F1FB190>: it's not the same object as __main__.__init__
```

When trying the same thing with dill you get a slightly more useful error (and a pretty useless stack trace as long as a novel):
```
PicklingError: Can't pickle Base: it's not found as sqlalchemy.ext.declarative.api.Base
```

My main use-case for pickling MetaData is to avoid long reflection times when working with my company's pre-existing databases. It can take upwards of a minute to reflect complex database schemas will hundreds of tables, which is reduced down to a fraction of a second if I cache the MetaData and unpickle it.

It doesn't sound like that much time, but if every application I write has to wait for over a minute to start up that puts some pretty heavy limitations on what I can do with sqlalchemy.

Just to clarify though, the actual reflected tables themselves do play nice. The issue only really affects me when I create a table declaratively with sqlalchemy in an existing database and then try to pickle the MetaData containing both my new table and all the other existing ones. Unfortunately, this is something I do occasionally have to do.

There are of course workarounds like using string literals for columns rather than sqlalchemy objects, or throwing away the old MetaData and reflecting everything from scratch after adding a table declaratively, which is why I think this is pretty low-priority. Still, it would be nice to have it resolved :)

Hope that makes sense.

**Comment by zzzeek** [comment]
> ```
> 
> My main use-case for pickling `MetaData` is to avoid long reflection times when working with my company's pre-existing databases. It can take upwards of a minute to reflect complex database schemas with hundreds of tables, which is reduced down to a fraction of a second if I cache the `MetaData` and unpickle it when needed.

this is the use case for pickled metadata, absolutely.  Which then leads to, how is it that you also have an explicitly declared table model in your application that is making use of Column / ForeignKey() etc. ?     if your table schema is already declared in your model then why do you also need to use reflection for that same set of tables?

This leads me to guess that part of your model is reflected and part is in the model?   Or this model is used to create a pickle that is being used in some other application ?  (why can't that app import your model?)     this is why the use case is odd and this issue has never been reported.


> 
> It doesn't sound like that much time, but if every application I write has to wait for 1-2 minutes to start up that puts some pretty heavy limitations on what I can do with `sqlalchemy`.

if we were to have some contributors to help with #4379 it would likely be in the 5-10 seconds department, would that be too slow also ?

> 
> Just to clarify though, the actual reflected tables themselves do play nice. The issue only really affects me when I create a table declaratively with sqlalchemy in an existing database and then try to pickle the `MetaData` containing both my new table and all the other existing ones. Unfortunately, this is something I do occasionally have to do.

I think the most portable approach for now if these are declarative models is to use:

    ForeignKey(Parent.__table__.c.id)

nobody will fault the code for doing it that way.    the change I'm making is leveraging some new architectures in 1.4 and there's not a clean backport for 1.3 so it would be preferable if you could work around as above for now.

> 
> There are of course workarounds like using string literals for columns rather than `sqlalchemy` objects, or throwing away the old `MetaData` and reflecting everything from scratch after adding a table declaratively, which is why I think this is pretty low-priority. Still, it would be nice to have it resolved :)
> 
> Hope that makes sense.
> 
> I'll use the `._deannotate()` method or my `ForeignKey` subclass for now. Thanks for the quick and thorough response @zzzeek!

yeah that or the ``__table__`` approach above is more future proof.

**Comment by matthewgdv** [comment]
Awesome, thanks! I'll use the table column approach for sure.

And yeah, you're totally right. Having mostly reflected models, but then also some declarative ones ocasionally interspersed is an unusual use-case. I suppose that's the thing about massive open-source projects like this; with a large enough userbase you're bound to run into remote edge-cases eventually.

I didn't know there was an open issue to improve the speed of the schema reflection. That's really cool! I hope that goes somewhere because it would be a great optimization. I'll look at it a bit and maybe if it looks like something that's within my capabilies I'll look into some ways of implementing the mssql dialect `.get_multi_xxxxxxxx()` methods, since that's the only dialect I'm really familiar with.

Thanks again!
