### ISSUE TITLE
Download link is dead from docs site

### ISSUE THREAD

**Issue by teozkr** [sqlalchemy/sqlalchemy#5003]
The download links in the header of https://docs.sqlalchemy.org/en/13/ are domain-relative, so they point to https://docs.sqlalchemy.org/download.html#current (which doesn't exist), rather than https://www.sqlalchemy.org/download.html#current (which does).

**Comment by zzzeek** [comment]
oh weird, OK yeah thats recently new navigation that was added , thanks

**Comment by zzzeek** [comment]
the build is going through now they are up for https://docs.sqlalchemy.org/en/14/ so far thanks for the pointer!
