### ISSUE TITLE
schema translate map poorly interacts with cache

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5004]
the schema translate feature takes place within the compiler and this is plainly wrong.  the schema assignment should be taking place *after* the SQL is generated so that we only need one cache key.   This is along the lines of #5002 however I think even the existing cache key mechanism used with baked etc. needs to pull the schema translate **out** of the compiler entirely for 1.4 and add it to the translations which occur from the ExecutionContext, along with the expanding parameter sets of logic.    schema translate is intended to service many hundreds / thousands of schemas so having this occur pre-cache has to change.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Convert schema_translate to a post compile** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1812
