### ISSUE TITLE
Problems reflecting "dbo" schema dynamically (ORM) in MS SQL Server (mssql)

### ISSUE THREAD

**Issue by felipe0216** [sqlalchemy/sqlalchemy#5007]
Hello,

I am having problems reflecting my tables from the MS SQL Server database that have the schema "dbo". I have tried using the following code.

##### Engine works , I have tested it using CORE
>engine = db.create_engine("mssql+pyodbc:///?odbc_connect=%s" % params) 

##### I have tried binding it to engine as well
>meta = MetaData(schema="dbo")    

 ##### I have tried without this line as well 
>meta.reflect(bind=engine, schema="dbo")   

>Base = automap_base(metadata=meta)
>Base.prepare(engine, reflect=True)

##### That seemed to work fine, I get no errors, however, if I try to retrieve the name of the tables I can't see them:
Base.classes.keys()
> []

I have seen that the problem could be that the table doesn't have a primary key, however that is not the problem, because I have multiple tables under the schema "dbo" and they have primary keys.

If anyone knows a solution please let me know, I will be eternally grateful.

**Comment by zzzeek** [comment]
hi there-

there is no need to post the same question in both the mailing list and on github, as I have answered you on github, closing this.

**Comment by zzzeek** [comment]
correction, answered you on the mailing list.

**Comment by felipe0216** [comment]
I apologise, first time I use either of them, so I didn't know they were connected
