### ISSUE TITLE
SELECT drops two rows from result when using clickhouse.

### ISSUE THREAD

**Issue by sanyassh** [sqlalchemy/sqlalchemy#5012]
When doing `SELECT * FROM test_table;` inside clickhouse-client I get N rows as expected, but only N-2 when doing `engine.execute('SELECT * FROM test_table;')` from python code that uses sqlalchemy.

Steps to reproduce:

1. clickhouse-server is running on localhost.
2. The following commands are executed in clickhouse-client:

```
CREATE TABLE test_table (id INTEGER, created Date) ENGINE = MergeTree(created, (id), 8192);
INSERT INTO test_table (id, created) VALUES (1, 11345678);
INSERT INTO test_table (id, created) VALUES (2, 12345678);
INSERT INTO test_table (id, created) VALUES (3, 13345678);
INSERT INTO test_table (id, created) VALUES (4, 14345678);
SELECT * FROM test_table;
```

Results:

```
SELECT *
FROM test_table

┌─id─┬────created─┐
│  4 │ 2106-02-07 │
└────┴────────────┘
┌─id─┬────created─┐
│  3 │ 2084-08-20 │
└────┴────────────┘
┌─id─┬────created─┐
│  2 │ 2038-03-15 │
└────┴────────────┘
┌─id─┬────created─┐
│  1 │ 1991-10-08 │
└────┴────────────┘

4 rows in set. Elapsed: 0.004 sec. 

```

Okay, 4 rows as expected.

3. The following python script is executed:

```
from sqlalchemy import create_engine


connection_string = 'clickhouse://default:@localhost/default'
engine = create_engine(connection_string)
result = list(engine.execute('SELECT * FROM test_table;'))
print(len(result))
print(result)
```

Results:

```
2
[('4', '2106-02-07'), ('2', '2038-03-15')]
```

Definitely not as expected. So, what is going on here? 

sqlalchemy version: 1.3.11
clickhouse version (both server and client): 19.17.4.11

**Comment by zzzeek** [comment]
hi there -

i have no idea what clickhouse is and cannot offer help with this driver.  please contact the maintainers of this third party driver with your issue.  thanks!
