### ISSUE TITLE
SQLite's JSON field doesn't support numbers as the vale

### ISSUE THREAD

**Issue by gcbirzan** [sqlalchemy/sqlalchemy#5014]
Technically, this isn't an SQLAlchemy issue, but an SQLite. It seems that numbers (except Infinity and NaN) are returned as numbers (either ints or floats, even overriding the provided type, but that's to be expected), everything else is returned as a string, reqeuring JSON deserialization.

The problem can be seen here: https://gist.github.com/gcbirzan/adf321d82d57a6e638d0517fbcb7fe1a

The documentation is misleading, for two reasons:

Firstly, in the documentation (https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#sqlalchemy.dialects.sqlite.JSON) there is some mention of JSON_QUOTE being used to always return strings. This is not true, as can be seen from the queries being ran.

Secondly, there is no mention of this problem, except in the changelog (https://docs.sqlalchemy.org/en/13/changelog/migration_13.html#change-3850): 

> This will create a SQLite datatype with “numeric” affinity, which normally should not be an issue except in the case of a JSON value that consists of single integer value

Understanding the problem, now I can see what it means: that numbers are returned as such and break SQLAlchemy.

So, I'm not sure whether this should be fixed in SQLAlchemy or not (I'd say yes), but it should at the very least be properly documented.

**Comment by zzzeek** [comment]
hi -

thanks for the background.  this is only a simple bug fix, will be in 1.3.12.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Gracefully degrade for SQLite JSON receiving direct numeric value** https://gerrit.sqlalchemy.org/1597

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Gracefully degrade for SQLite JSON receiving direct numeric value** https://gerrit.sqlalchemy.org/1598
