### ISSUE TITLE
DeferredReflection initialize properties timing

### ISSUE THREAD

**Issue by lswest** [sqlalchemy/sqlalchemy#5019]
Hi!

**SQLAlchemy Version:** 1.3.11

At work we've been using SQLAlchemy for an API to access two postreSQL (with psycopg2) databases with roughly 30 tables. Originally it was written with `__table_args__` set to `'autoload': True`, but this was causing issues when we tried to import the files (i.e. generating Sphinx docs or re-using code across projects) without an active database connection, as the database engine was created when the class was read and not when it was instantiated.

Since then we've implemented DeferredReflection to load table metadata during our setup phase, which has solved the import issue. We've continued to see a performance issue we originally had as well - the first API call is always slower than subsequent ones - thanks to `_post_configure_properties` being run for all ORM classes once the first one is instantiated. Is this normal? Or is there a method one can manually run to initiate the process while making more semantic sense than instantiating a random ORM object?

I'd also appreciate any suggestions on how to debug sqlalchemy query performance (if that's possible) besides using `time.perf_counter()`.

**Things we've done:**

1. Defined 2 abstract DeferredReflection classes (one per database)
2. Inherit the two above classes for our relevant ORM classes.
3. In the ORM classes we've defined all the columns by hand that are primary keys, as we occasionally have to access old Oracle DB systems (via PostgreSQL Foreign Data Wrapper) and it didn't work without the columns being defined beforehand. The rest of the metadata should be loaded automatically.
4. During setup we run the `.prepare()` method for both abstract classes.
5. We have verified that the metadata and table names are recognized properly (from `DeferredReflection.__subclasses__()`
6. We use a mixture of both raw SQL and the SQLAlchemy query methods.

Thanks in advance for any input you might have.

**Comment by zzzeek** [comment]
> 
> Since then we've implemented DeferredReflection to load table metadata during our setup phase, which has solved the import issue. We've continued to see a performance issue we originally had as well - the first API call is always slower than subsequent ones - thanks to `_post_configure_properties` being run for all ORM classes once the first one is instantiated. Is this normal? 

this is normal, as the mappers once constructed need to resolve linkages between each other, that is, relationships.    Since relationships might have backref directives pointing to other classes, and additionally there may be user-defined event runners that also assume mappers all being set up, the full set of all mapper() objects in memory are configured in one step.


> Or is there a method one can manually run to initiate the process while making more semantic sense than instantiating a random ORM object?

absolutely, call configure_mappers():  https://docs.sqlalchemy.org/en/13/orm/mapping_api.html?highlight=configure_mappers#sqlalchemy.orm.configure_mappers

> 
> I'd also appreciate any suggestions on how to debug sqlalchemy query performance (if that's possible) besides using `time.perf_counter()`.

There's an in-depth section on using Python profiling to profile how much time is spent with queries, as the performance issues can be in one or more of several different areas: https://docs.sqlalchemy.org/en/13/faq/performance.html#how-can-i-profile-a-sqlalchemy-powered-application


> 
> **Things we've done:**
> 
>     1. Defined 2 abstract DeferredReflection classes (one per database)
> 
>     2. Inherit the two above classes for our relevant ORM classes.
> 
>     3. In the ORM classes we've defined all the columns by hand that are primary keys, as we occasionally have to access old Oracle DB systems (via PostgreSQL Foreign Data Wrapper) and it didn't work without the columns being defined beforehand. The rest of the metadata should be loaded automatically.
> 
>     4. During setup we run the `.prepare()` method for both abstract classes.
> 
>     5. We have verified that the metadata and table names are recognized properly (from `DeferredReflection.__subclasses__()`
> 
>     6. We use a mixture of both raw SQL and the SQLAlchemy query methods.
> 
> 
> Thanks in advance for any input you might have.

**Comment by lswest** [comment]
@zzzeek thank you so much for the really prompt reply. `configure_mappers()` is exactly what I was after, so I'll close this issue!

The explanation as to why it's necessary was also extremely helpful (and, in hindsight, pretty logical).

The FAQ on performance is going to be very useful in the future too.

Thanks again!
