### ISSUE TITLE
Retrieve dates in python's datetime format

### ISSUE THREAD

**Issue by felipe0216** [sqlalchemy/sqlalchemy#5025]
Hello,

I am trying to what would be the equivalent of this:
```
sql = "SELECT DISTINCT date_column FROM mytable"
dates_series = pd.read_sql(sql,cnxn)
dates_series = dates_series.dt.strftime('%Y-%m-%d')
```
I have found that pandas read_sql is compatible with SQLAlchemy, I have seen that the format is the following:
```
dates_series = session.query(mytable.date_column).distinct()
df = pd.read_sql(dates_series,con = session.bind)
```
however, if I try to run this it says. "Not an executable object:" and if I add "dates_series.statement" instead of just "date_series" it doesn't drop me an error, but it retrieves and empty series. Does anybody know why?????

**Comment by gordthompson** [comment]
Does your first code snippet throw an error or not produce the results you expect?

**Comment by felipe0216** [comment]
My first code does produce the output that I want, but I want to translate it to SQLAlchemy, this code uses a simple DBAPI connection.

**Comment by gordthompson** [comment]
Here is an example of pandas `read_sql_query` using a query encapsulated in a SQLAlchemy `text` object:

```python
import pandas as pd
import sqlalchemy as sa

# ...

query = sa.text("SELECT date_col FROM issue5025 WHERE id = 1")
df = pd.read_sql_query(query, engine)
date_value = df.iloc[0, 0]
print(repr(date_value))  # datetime.date(2001, 1, 1)
```

Does that help?

**Comment by felipe0216** [comment]
Hello @gordthompson ,

Yes, it does, thank you very much!
