### ISSUE TITLE
How to select multiple (12+) columns efficiently?

### ISSUE THREAD

**Issue by felipe0216** [sqlalchemy/sqlalchemy#5026]
Hello,

This is just a usability question. I am trying to create an statement that picks up several columns (12 in total and add a condition where a column containing dates show only the dates IN a certain range. 

I have the statement created for raw SQL, it looks like this:

```
datelist_tuple = tuple(array of dates)

varlist = ["AR1","AR55","AR10","AR11","AR69","AR107","AR113","AR120","AR3","AR66","AR61","AR109"]

sql = "SELECT "+str.join(",",varlist)+" FROM [BGT].dbo.BoE where AR1 in "+str(datelist_tuple)

```

I am trying to think of its equivalent in SQLAlchemy CORE or ORM, the solution would nomally be this:

```
select([BoE2.c.AR1, BoE2.c.AR55, BoE2.c.AR10, BoE2.c.AR11, BoE2.c.AR69, BoE2.c.AR107, BoE2.c.AR113, BoE2.c.AR120, BoE2.c.AR3, BoE2.c.AR66, BoE2.c.AR61, BoE2.c.AR109]).where(BoE2.c.AR1.in_(datelist_tuple))

```
But in my opinion it looks way more inefficient to write in SQLAlchemy, but I don't think it should. For sure, there are ways to optmize this, but I can't think how.

**Comment by gordthompson** [comment]
If you already have the column names in a list then you don't need to slavishly type out each one as `tablename.c.columnname`. Instead, you can just join them together and wrap them in a `text` object, and then pass that into your `select`. For example,

```python
import sqlalchemy as sa

# ...

issue5026 = sa.Table('issue5026', sa.MetaData(), autoload=True, autoload_with=engine)

column_names_list = ['col0', 'col1', 'col2']
column_names_text = sa.text(','.join(column_names_list))

query =  sa.select([column_names_text])\
    .select_from(issue5026)\
    .where(issue5026.c.col0==123)
result = engine.execute(query).fetchone()
print(result)
```

**Comment by felipe0216** [comment]
Thanks @gordthompson, that is exactly what I was looking for!
