### ISSUE TITLE
select() treats distinct keyword differently than distinct()

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5028]
this is related to 55f66e430d18b8daa51121cb, it's still wrong in master /1.3:

```

from sqlalchemy import *
from sqlalchemy.dialects import postgresql

t = table('t', column('q'))


for stmt in [
    lambda: select([t]).distinct('q'),  # good
    lambda: select([t]).distinct(text('q')),  # good
    lambda: select([t], distinct=text('q')),  # good
    lambda: select([t], distinct='q')  # boom
]:
    stmt = stmt()
    print(stmt.compile(dialect=postgresql.dialect()))


```

we're going to deprecate those keywords but for the moment it needs to work correctly.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use label reference coercion for select() distinct keyword argument** https://gerrit.sqlalchemy.org/1605

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Use label reference coercion for select() distinct keyword argument** https://gerrit.sqlalchemy.org/1606
