### ISSUE TITLE
Developer docs link to sqlalchemy-cubrid yielding a 404

### ISSUE THREAD

**Issue by metaperl** [sqlalchemy/sqlalchemy#5029]
The [experimental/incomplete](https://sqlalchemy-html.readthedocs.io/en/stable/dialects/index.html#experimental-incomplete) section of the Dialect docs mentions/links to sqlalchemy-cubrid but visiting [the link](https://bitbucket.org/zzzeek/sqlalchemy-cubrid) yields a 404 error.

**Comment by metaperl** [comment]
Looks like it should point here - https://github.com/zzzeek/sqlalchemy_cubrid

**Comment by zzzeek** [comment]
I'd rather blow away that link altogether (note it is pointingto my own bitbucket account) as I have no plans to do anything with cubrid

**Comment by zzzeek** [comment]
oh hey.

What on earth is https://sqlalchemy-html.readthedocs.io/   ?

Those are not my docs!!!

**Comment by zzzeek** [comment]
how did you find these docs?

https://github.com/readthedocs/readthedocs.org/issues/6456

**Comment by zzzeek** [comment]
alrighty that was not our docs, the user took the site down.
