### ISSUE TITLE
How to monitor the connection pool of Sqlalchemy?

### ISSUE THREAD

**Issue by xing-zhang2** [sqlalchemy/sqlalchemy#5032]
Now there is a situation where I want to get the status of the current connection pool and the number of connections in real time.

Is there any good way? 

Thank you.

**Comment by zzzeek** [comment]
Sure, why don't you take a look at [sqlalchemy-collectd](https://pypi.org/project/sqlalchemy-collectd/) for a comprehensive solution.

for a quick in-process solution you can look at engine.pool.status() which unfortunately appears to lack a docstring at the moment.

**Comment by zzzeek** [comment]
https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/pool/impl.py#L188

**Comment by xing-zhang2** [comment]
Thank you. It solved my problem
