### ISSUE TITLE
add type hint py3.8

### ISSUE THREAD

**Issue by mosi-kha** [sqlalchemy/sqlalchemy#5036]
hi
please add [type hint ](https://www.python.org/dev/peps/pep-0589/) for sqlalchemy's functions.
thanks

**Comment by zzzeek** [comment]
hi there -

I don't know what this issue is asking for.  pep589 refers to a specific datastructure, not "type hints for functions".  pep 484 type hints is discussed in #4609.   Support for "dataclasses" which was enabled in pep 589 is discussed in #4666.   Please provide specifics.

**Comment by mosi-kha** [comment]
sorry for faulty issue
when use `session`, suggests some function like `query` or `filter` ... to use.

**Comment by zzzeek** [comment]
please use the third party extension mentioned in #4609.
