### ISSUE TITLE
query.first() does not raise MultipleResultsFound with sqlite backend

### ISSUE THREAD

**Issue by Dantali0n** [sqlalchemy/sqlalchemy#5037]
Python                    : 3.7.5. 
SQLAlchemy         : 1.3.11      
SQLAlchemy-Utils: 0.36.0

When I call `query.first()` I get one object returned but when I call `query.all()` I get a list with with two objects. 
When I [read the documentation ](https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.one) the `query.first()` call should have raised the MultipleResultsFound but it didn't.

I have used a query with `filter_by` were I match entries based on the value for a choicetype in the database. I am using sqlite as backend.

**Comment by gordthompson** [comment]
You seem to be confusing `.first()` with `.one()`. `.one()` should throw an exception in your case, but `.first()` should not.

**Comment by Dantali0n** [comment]
> You seem to be confusing `.first()` with `.one()`. `.one()` should throw an exception in your case, but `.first()` should not.

Oops my mistake, I feel beyond dumb. Well problem solved haha

**Comment by zzzeek** [comment]
thanks @gordthompson  !
