### ISSUE TITLE
Could not parse CHECK constraint text

### ISSUE THREAD

**Issue by pipriles** [sqlalchemy/sqlalchemy#5039]
Hello,

I have the following CHECK constraint on one of my tables:
```sql
CONSTRAINT ownership_fk CHECK(foreign_property('OWNERSHIP', ownership_id))
```

And I am getting the following warning using sqlalchemy 1.3.8:
```
c:\program files\python37\lib\site-packages\sqlalchemy\dialects\postgresql\base.py:3450: 
SAWarning: Could not parse CHECK constraint text: "CHECK (foreign_property('OWNERSHIP'::text, (ownership_id)::text))"
```

What should I do to fix or suppress this warning?

Thanks

**Comment by gordthompson** [comment]
The constraint name `ownership_fk` suggests that it should be a FOREIGN KEY constraint rather than a CHECK constraint. In what context are you encountering the error? Are you supplying the DDL text yourself, or is it being generated for you? If the latter, please show us where it is coming from.

**Comment by zzzeek** [comment]
Warnings may be suppressed using the [python warnings filter](https://docs.python.org/3/library/warnings.html).      this is definitely a CHECK constraint since that's the DDL text being received.

@gordthompson , the regex that is failing to parse is at: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/base.py#L3491 and the exact string in this case that fails to match is `"CHECK (foreign_property('OWNERSHIP'::text, (ownership_id)::text))"`.

**Comment by pipriles** [comment]
@gordthompson Yes it is a check constraint, sorry that the name it gave it is a little confusing...

@zzzeek Shouldn't the regex match the CHECK constraint?

**Comment by zzzeek** [comment]
> 
> @zzzeek Shouldn't the regex match the CHECK constraint?

yes, however at the moment, it does not, and your Q was how to disable warnings.  It's not a very critical warning.

**Comment by gordthompson** [comment]
@pipriles - I did some testing and if `foreign_property` is a user-defined function that returns a boolean value you could also work avoid the warning by changing your CHECK constraint from

```sql
CONSTRAINT ... CHECK(foreign_property('OWNERSHIP', ownership_id))
```

to

```sql
CONSTRAINT ... CHECK(foreign_property('OWNERSHIP', ownership_id) = true)
```

I've also started working on a patch for this issue. Stay tuned ....

**Comment by pipriles** [comment]
@gordthompson Thank you,

It seems it creates an extra parenthesis when there is some kind of operation:
So maybe changing this line:

```python
m = re.match(r"^CHECK *\(\((.+)\)\)( NOT VALID)?$", src)
if not m:
    util.warn("Could not parse CHECK constraint text: %r" % src)
    sqltext = ""
else:
    sqltext = m.group(1)
    entry = {"name": name, "sqltext": sqltext}
```

To this 

```python
m = re.match(r"^CHECK *\((.+)\)( NOT VALID)?$", src)
if not m:
    util.warn("Could not parse CHECK constraint text: %r" % src)
    sqltext = ""
else:
    sqltext = re.sub(r'^\((.+)\)$', r'\1', m.group(1))
    entry = {"name": name, "sqltext": sqltext}
```

May fix the issue?

**Comment by gordthompson** [comment]
@pipriles - Your fix seems to work fine. Thanks!

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Improve regex parsing of CHECK constraints.** https://gerrit.sqlalchemy.org/1623

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Improve regex parsing of CHECK constraints for PostgreSQL.** https://gerrit.sqlalchemy.org/1672
