### ISSUE TITLE
mssql pyodbc DATETIMEOFFSET - fractional seconds not persisted

### ISSUE THREAD

**Issue by mattinbits** [sqlalchemy/sqlalchemy#5045]
A recent change to DATETIMEOFFSET for mssql+pyodbc appears to have caused fractions of seconds not to be persisted:

https://github.com/sqlalchemy/sqlalchemy/issues/4983
https://github.com/sqlalchemy/sqlalchemy/blob/d6d61ffe4ce207428b24b38431b75af5f5df1cf4/lib/sqlalchemy/dialects/mssql/pyodbc.py#L238

It looks like the call the strftime is disregarding any fractional part.

**Comment by gordthompson** [comment]
Yup. Thanks for catching this.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix DATETIMEOFFSET formatting to preserve fractional seconds.** https://gerrit.sqlalchemy.org/1622

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix DATETIMEOFFSET formatting to preserve fractional seconds.** https://gerrit.sqlalchemy.org/1643
