### ISSUE TITLE
Oracle reflection raises warning for ROWID type columns

### ISSUE THREAD

**Issue by kbower** [sqlalchemy/sqlalchemy#5047]
Was ROWID intentionally left out of `ischema_names`?

```diff
diff --git a/lib/sqlalchemy/dialects/oracle/base.py b/lib/sqlalchemy/dialects/oracle/base.py
index fe3d586a4..54714ab43 100644
--- a/lib/sqlalchemy/dialects/oracle/base.py
+++ b/lib/sqlalchemy/dialects/oracle/base.py
@@ -623,40 +623,41 @@ colspecs = {
 ischema_names = {
     "VARCHAR2": VARCHAR,
     "NVARCHAR2": NVARCHAR,
     "CHAR": CHAR,
     "NCHAR": NCHAR,
     "DATE": DATE,
     "NUMBER": NUMBER,
     "BLOB": BLOB,
     "BFILE": BFILE,
     "CLOB": CLOB,
     "NCLOB": NCLOB,
     "TIMESTAMP": TIMESTAMP,
     "TIMESTAMP WITH TIME ZONE": TIMESTAMP,
     "INTERVAL DAY TO SECOND": INTERVAL,
     "RAW": RAW,
     "FLOAT": FLOAT,
     "DOUBLE PRECISION": DOUBLE_PRECISION,
     "LONG": LONG,
     "BINARY_DOUBLE": BINARY_DOUBLE,
     "BINARY_FLOAT": BINARY_FLOAT,
+    "ROWID": ROWID,
 }


 class OracleTypeCompiler(compiler.GenericTypeCompiler):
     # Note:
     # Oracle DATE == DATETIME
     # Oracle does not allow milliseconds in DATE
     # Oracle does not support TIME columns

     def visit_datetime(self, type_, **kw):
```

**Comment by zzzeek** [comment]
hi Kent -

you need to slow down for me.   How does a table have a ROWID in the actual columns that come back in reflection ?  it's a pseudocolumn.      Note that if there are SQLAlchemy features that make this happen, yes, I need to be reminded what they are :).

**Comment by kbower** [comment]
ROWID is a valid column type in oracle:

```
Session altered.


database: XE

SQL> create table myrowid(a rowid);

Table created.

SQL> desc myrowid
 Name                                Null?    Type
 ----------------------------------- -------- ------------------------
 A                                            ROWID

SQL>
```

If you are asking _why you'd want to use one_, well that is more philosophical, but shouldn't SQLAlchemy support it?

**Comment by zzzeek** [comment]
> If you are asking _why you'd want to use one_, well that is more philosophical, but shouldn't SQLAlchemy support it?

heh ok sloooow down, didn't say anything about not supporting it, it's not in that list because it's not a thing anyone working on this had seen before.     this is what we call a "use case".   no biggie

**Comment by kbower** [comment]
> heh ok sloooow down, didn't say anything about not supporting it,

No, no, no... I didn't mean for that to sound accusatory ... I wasn't sure whether you were asking whether we should support that.  Definitely an edge case.  

Thank you sir!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**reflect Oracle ROWID** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4380

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**reflect Oracle ROWID** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4381

**Comment by kbower** [comment]
thanks, @zzzeek
