### ISSUE TITLE
compact extra spacing in code base

### ISSUE THREAD

**Issue by sahasrara62** [sqlalchemy/sqlalchemy#5049]
extra spacing in code base can be reduce.

there is space between various functions, classes, object, documentation or in some case space is required.

it is not mentioned why if space is created clearly for differentiating the object then no documentation or comments is present to define this.

so suggesting to improve this part and make code much cleaner and well structured.

**Comment by zzzeek** [comment]
hi there -

SQLAlchemy has a strict style guide that is implemented in the codebase automatically, and is also checked automatically.

All code formatting throughout SQLAlchemy conforms to [pep8](https://www.python.org/dev/peps/pep-0008/), is automatically formatted by [black](https://black.readthedocs.io/en/stable/), and the all commits are tested in continuous intregration using [flake8](http://flake8.pycqa.org/en/latest/).

So when you refer to "space between various functions" it's not clear what you are referring towards.   the above rules prevent SQLAlchemy from having any excessive whitespace.  The only whitespace variance that is even possible is a single line between individual lines of Python code inside of a function, such as:

```
def foo():
    do_thing_one()
    do_thing_two()

```
vs. 

```
def foo():
    do_thing_one()

    do_thing_two()

```

literally all other whitespace, including the space between classes and functions, is dictated directly by pep8 / black / flake8; see https://www.python.org/dev/peps/pep-0008/#blank-lines for the general guidelines.

Feel free to illustrate specifics, thanks!
