### ISSUE TITLE
[BUG] WeakSequence circular reference

### ISSUE THREAD

**Issue by carsonip** [sqlalchemy/sqlalchemy#5050]
WeakSequence is creating unnecessary circular reference and requiring gc module to clean it up.

Python: CPython 2.7.15

Code to reproduce issue:
```
import gc
gc.disable()
from sqlalchemy.util import WeakSequence

gc.collect()
gc.set_debug(gc.DEBUG_SAVEALL)


class X(object):
    pass


w = WeakSequence([X])
del w

gc.collect()
print(gc.garbage)
```

Expected result:
```
[]
```

Actual result:
```
[<sqlalchemy.util._collections.WeakSequence object at 0x7f7221b30bd0>, [<weakref at 0x7f721f853208; to 'type' at 0x5602f6ab5410 (X)>], <bound method WeakSequence._remove of <sqlalchemy.util._collections.WeakSequence object at 0x7f7221b30bd0>>, <weakref at 0x7f721f853208; to 'type' at 0x5602f6ab5410 (X)>, {'_storage': [<weakref at 0x7f721f853208; to 'type' at 0x5602f6ab5410 (X)>]}]
```

Visualization using objgraph:
![0](https://user-images.githubusercontent.com/9133397/71394476-b1c3f180-264c-11ea-9765-065ecfbfe58c.png)

Circular reference is not good for CPython's refcount garbage collector. Since the class is called "WeakSequence", it is expected that refcount can clean up the garbage instead of the gc module.

A fix is coming up. I suppose fixing this would be good for performance and memory.

**Comment by zzzeek** [comment]
you found this on code inspection?  The WeakSequence is only used in one little spot in the code and only involves teardown of mappers that use inheritance, not a standard situation nor one that is expected to be performant.    It is a bug though, thanks for the PR.

**Comment by carsonip** [comment]
Hi Mike,

My application is taking up more memory than expected and that's why I'm looking into my application's gc output and find that SQLAlchemy is creating lots of garbage (circular-referenced objects) (10+ MB of garbage for one simple PK query) that cannot be cleared out with CPython's refcount and must rely on the gc module. I have identified and fixed a few places that creates circular referenced objects, mostly related to recursive calls of nested functions with closures, and this WeakSequence bug is the most obvious and easy one.

I am going to create another issue and PR for the other changes tomorrow because it involves lots of changes, and I would need your input on them regarding coding style / test methodology. These changes should make SQLAlchemy more friendly to CPython's refcount gc without hurting other interpreters / performance, but it may hurt code readability a bit. Please let me know if you do not want these kind of changes.

**Comment by zzzeek** [comment]
Hi Carson -

let's examine each change individually and determine their relevance.    Circular refs are IMO not always a bad thing and for those cases where objects are not expected to be torn down regularly like Table and mapper objects, they often provide a more performant navigation path than would be present if we put weakref.ref()s in between.  So a particular reference cycle needs to be addressed in terms of if the cycle is present in a structure that requires frequent, performant teardown, or if it is a permanent structure that benefits more from simpler navigational paths.

**Comment by zzzeek** [comment]
that said, invoking a query that is *not* also invoking configure_mappers() should not be producing any unreachable cycles.   Make sure you are calling configure_mappers() before calling this query.    Query cache improvements coming in 1.4 / 2.0 will also take pressure off of these issues as compiled objects will be cached more often.

**Comment by sqla-tester** [comment]
**Carson Ip** has proposed a fix for this issue in the **master** branch:

**Fix WeakSequence circular reference** https://gerrit.sqlalchemy.org/1626

**Comment by sqla-tester** [comment]
**Carson Ip** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix WeakSequence circular reference** https://gerrit.sqlalchemy.org/1629

**Comment by zzzeek** [comment]
if we do find query-time cycles that are created I would want to prospose a new suite of tests within or alongside test/aaa_profiling/test_memusage.py, which runs some code and then asserts that no reference cycles, or an expected number of unreachable cycles, were created.

**Comment by zzzeek** [comment]
please review the tests proposed in https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1630 which hopefully should allow these cycles to be found and zeroing them out maintained.    So far, simple query scenarios do not seem to create cycles unless query.join() with certain kinds of arguments are used (which it shouldnt).

**Comment by zzzeek** [comment]
move on over to #5056 where a test suite is added and we can try to get some of these, mapperoptions not surprisingly seem to be a big issue but im not sure if those cycles can be eliminated without a lot more complexity.

**Comment by zzzeek** [comment]
update, all the cycles I've found I've managed to reduce to zero.  this is for query() using simple filter(), join() as well as query options.    you probably can find more cycles but the bunch that I've removed in the above gerrit should make a significant improvement in your test code.

**Comment by carsonip** [comment]
Thanks for taking this seriously. This is moving real fast. Here's my personal playground and this eliminated most of the ref cycles I found in my application: https://github.com/carsonip/sqlalchemy/commits/optimization-clone
Most of the changes don't require weakref.
I am starting a new playground with a MCVE to verify that the changes resolves ref cycle. I'll let you know the progress.

**Comment by carsonip** [comment]
Let me lay out what I have found so far, in categories:
1. Instances with PopulateDict attributes with instance methods as creator
    - `_class_resolver`
    - `ColumnAdapter`
    - `SQLCompiler` (fixed in master but not in rel_1_3)
![image](https://user-images.githubusercontent.com/9133397/71539575-42663e80-2979-11ea-80d2-b28cbed01a61.png)

2. Recursive calls of nested functions with closures (usually keeps a large number of garbage objects around)
   - clone methods under cloned_traverse, replacement_traverse etc
![image](https://user-images.githubusercontent.com/9133397/71539587-66c21b00-2979-11ea-97b7-ff3bbc7fca50.png)

3. Instances with instance attributes pointing at self
   - what you pointed out in #5056 , including EntityRegistry, AliasedInsp
![image](https://user-images.githubusercontent.com/9133397/71539618-e51ebd00-2979-11ea-9262-d5abf90628e0.png)

**Comment by carsonip** [comment]
Now that you are working full speed in gerrit, I'm not sure how I could help. Maybe I'll rebase my fixes on top of your patches and create a PR.

**Comment by zzzeek** [comment]
now..........is the issue you're having, that having lots of unreachable cycles is creating a larger memory footprint or the CPU time spent for cPython's GC to clean them up?      IIUC the gc collect runs at a particular interval so if the reference cycles are produced at a higher rate that will use more memory?    I am now getting into cycles that are necessary for performance, and removing them has a much bigger negative impact on call coiunts.

**Comment by zzzeek** [comment]
things seem to be a lot worse in 1.3 than in master for some reason which is strange

**Comment by carsonip** [comment]
My busy application is exhibiting some kind of high water mark memory pattern, i.e. it is consuming more memory than it is actually using, e.g. tracemalloc / pympler showing dicts are using 300MB and strs are using 50MB but the application is consuming 1GB from OS's point of view.

My hypothesis:
The application runs query A, B, C sequentially and it keeps the garbage around. At this moment CPython already allocated memory to keep the garbage of A, B, C, instead of do A, clean up, do B, clean up...

**Comment by zzzeek** [comment]
that/s kind of strange, have you set the GC settings very differnetly or something?   note that interpreters like pypy do *alll* garbage collection asychronously so the cycles are usually brought up more as a CPU issue rather than a memory one.

**Comment by carsonip** [comment]
I am using the defaults. The memory issue (and OOMs) may not be caused by SQLAlchemy because I also see ref cycle issues in another library I use, but I was thinking that avoiding ref cycle in CPython can't be a bad thing if it does not affect performance, and that's why I'm looking into this issue now. May not be as big as a problem as we may think, but I think it is a nice-to-have.

**Comment by zzzeek** [comment]
there's a 1.3 backport in https://gerrit.sqlalchemy.org/#/c/sqlalchemy/sqlalchemy/+/1631 which includes a backport of 1.4's newer "anon map" structure that no longer introduces a cycle.    you should confirm that the number of uncollected cycles is significantly lower in your test suite and assuming that's the case, see if it has an impact on OS level memory.  otherwise I'm inclined to go with what I have here and not much else.

**Comment by zzzeek** [comment]
yes, avoiding cycles if feasible isn't a bad thing, and particularly with objects that are produced and thrown away at high rates, in SQLAlchemy the statement / query / compiled objects, it's good to reduce them to near zero.    but turning 300MB into 1G of resident memory, probably not :) .

**Comment by zzzeek** [comment]
mostly whats good here is that I added a test suite for checking for ref cycles in these structures so if i add a new one someday I'll be aware of it, this is how the other performance tests work as well.

**Comment by carsonip** [comment]
I have checked yesterday that the anon_map class does help in reducing number of unreachable objects.

But the most significant fix (at least in my test suite) is about the recursive nested clone methods like this: https://github.com/carsonip/sqlalchemy/commit/95251599e4f94ca2ca2ecf117aaae6a5cd2ff50e and other commits here: https://github.com/carsonip/sqlalchemy/commits/optimization-clone

I don't see this kind of ref cycle in CycleTest yet, and I guess it is related to inheritance classes. 

These will reduce the number of garbage objects from ~9000 -> 1000 in my test suite. The fix is mostly about un-nesting the nested functions and pass in closure variables as kw args. I would like to see if we would like these changes to be merged. The cost of this is slightly uglier code and verbose kw args.

**Comment by carsonip** [comment]
MVCE:
```python
"""Joined-table (table-per-subclass) inheritance example."""
import gc
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import inspect
from sqlalchemy import Integer
from sqlalchemy import or_
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
from sqlalchemy.orm import with_polymorphic


Base = declarative_base()


class Company(Base):
    __tablename__ = "company"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))

    employees = relationship(
        "Person", back_populates="company", cascade="all, delete-orphan"
    )

    def __repr__(self):
        return "Company %s" % self.name


class Person(Base):
    __tablename__ = "person"
    id = Column(Integer, primary_key=True)
    company_id = Column(ForeignKey("company.id"))
    name = Column(String(50))
    type = Column(String(50))

    company = relationship("Company", back_populates="employees")

    __mapper_args__ = {
        "polymorphic_identity": "person",
        "polymorphic_on": type,
    }

    def __repr__(self):
        return "Ordinary person %s" % self.name


class Engineer(Person):
    __tablename__ = "engineer"
    id = Column(ForeignKey("person.id"), primary_key=True)
    status = Column(String(30))
    engineer_name = Column(String(30))
    primary_language = Column(String(30))

    __mapper_args__ = {"polymorphic_identity": "engineer"}

    def __repr__(self):
        return (
            "Engineer %s, status %s, engineer_name %s, "
            "primary_language %s"
            % (
                self.name,
                self.status,
                self.engineer_name,
                self.primary_language,
            )
        )


class Manager(Person):
    __tablename__ = "manager"
    id = Column(ForeignKey("person.id"), primary_key=True)
    status = Column(String(30))
    manager_name = Column(String(30))

    __mapper_args__ = {"polymorphic_identity": "manager"}

    def __repr__(self):
        return "Manager %s, status %s, manager_name %s" % (
            self.name,
            self.status,
            self.manager_name,
        )


engine = create_engine("sqlite://")
Base.metadata.create_all(engine)

session = Session(engine)

c = Company(
    name="company1",
    employees=[
        Manager(
            name="pointy haired boss", status="AAB", manager_name="manager1"
        ),
        Engineer(
            name="dilbert",
            status="BBA",
            engineer_name="engineer1",
            primary_language="java",
        ),
        Person(name="joesmith"),
        Engineer(
            name="wally",
            status="CGG",
            engineer_name="engineer2",
            primary_language="python",
        ),
        Manager(name="jsmith", status="ABA", manager_name="manager2"),
    ],
)
session.add(c)

session.commit()

gc.collect()
gc.set_debug(gc.DEBUG_SAVEALL)

c = session.query(Company).get(1)
gc.collect()
print(gc.garbage)
for e in c.employees:
    str(e)
gc.collect()
print('gc.garbage len = %s' % len(gc.garbage))
print(gc.garbage)

# from pympler.asizeof import asizeof
# import objgraph
#
# objgraph.show_backrefs(gc.garbage, 10, filename='objgraph-out/joined.png')
#
# print('size of garbage = %s' % asizeof(gc.garbage))
```

**Comment by zzzeek** [comment]
so....._transform_for_nested_select is a weird legacy workaround thing that only should be taking place if you are on an ancient version of SQLite.   in 1.4 it's just gone totally since I looked around and dtermined that not even older CentOSes that run current Python 2.7 have this SQLite version.  are you seeing _transform_select_for_nested_joins being used in a real world application?

**Comment by carsonip** [comment]
I don't recall anything related to `_transform_select_for_nested_joins`. I am using MySQL, and polymorphic classes.

**Comment by carsonip** [comment]
With my MCVE, here's a table of gc garbage counts `len(gc.garbage)` in my branch https://github.com/carsonip/sqlalchemy/tree/optimization-clone that corresponds to each commit:

92b4d4edd601b1c06c046d42dd3a2b579d2ac8f5 170
95251599e4f94ca2ca2ecf117aaae6a5cd2ff50e 78

**Comment by zzzeek** [comment]
OK so I just observed an issue with MySQL over in jenkins, my great tests here for counting cycles which all return zero, when they acutlaly hit MySQL and get a reuslt back, a simple test is producing 328 unreachable cycles.   so this might be the MySQL driver, are you on mysqlclient or pymysql ?

**Comment by carsonip** [comment]
mysqlclient

**Comment by zzzeek** [comment]
it might be producing a lot of cycles on its own

**Comment by carsonip** [comment]
But my MCVE is sqlite and the nested SQLAlchemy `clone` methods are creating ref cycles around __closure__ variable. Let me make an MCVE.

**Comment by zzzeek** [comment]
yes Im going to just do "del clone" for those, should fix it right up

**Comment by carsonip** [comment]
MCVE:
```
import gc
gc.disable()

def f(obj):
    s = set()
    def inner(e):
        if e not in s:
            s.add(e)
            inner(e)
    return inner(obj)

gc.collect()
gc.set_debug(gc.DEBUG_SAVEALL)
f(object())
gc.collect()
print(gc.garbage)
```

**Comment by carsonip** [comment]
When I do `del clone`, I get `SyntaxError: can not delete variable 'inner' referenced in nested scope`, do you get the error?

**Comment by carsonip** [comment]
This error only happens on Python2.

According to https://stackoverflow.com/questions/12338713/python-nested-scopes-with-dynamic-features

> This limitation was removed in Python 3.2; you are now responsible for not deleting nested variables yourself; you'll get a runtime error (NameError) instead:

**Comment by zzzeek** [comment]
yeah it works fine in python 3.       

i really dont know if this is a normal thing that one is not even supposed to use nested closures because that creates a cycle.   if you can confirm these are the actual source of your real memory issues that would help.   this has never been reported before and also note im hoping for a lot of these operations to be cached in the next few years.

**Comment by zzzeek** [comment]
it's too bad, confirm the "del clone" cleans out the cycles :(

**Comment by zzzeek** [comment]
with debug_saveall turned on there are more "unreachable" things but it might be best to break these out into smaller tests

**Comment by carsonip** [comment]
> with debug_saveall turned on there are more "unreachable" things but it might be best to break these out into smaller tests

I think the key is to do `gc.disable()` to make sure nothing get automatically cleaned up by gc before the manual gc. Otherwise, the manual gc may miss some objects. With debug_saveall it achieves the same purpose because objects that are auto gc'ed are saved into gc.garbage.

**Comment by zzzeek** [comment]
this seems to resolve the issue for both visits for a basic gc.collect(), im not using DEBUG_SAVEALL since it is not working smoothly with my test suite, if you can confirm:
```

diff --git a/lib/sqlalchemy/sql/visitors.py b/lib/sqlalchemy/sql/visitors.py
index 7b2ac285a..e672e87cd 100644
--- a/lib/sqlalchemy/sql/visitors.py
+++ b/lib/sqlalchemy/sql/visitors.py
@@ -405,20 +405,21 @@ def cloned_traverse(obj, opts, visitors):
     cloned = {}
     stop_on = set(opts.get("stop_on", []))
 
-    def clone(elem):
+    def clone(elem, **kw):
         if elem in stop_on:
             return elem
         else:
             if id(elem) not in cloned:
                 cloned[id(elem)] = newelem = elem._clone()
-                newelem._copy_internals(clone=clone)
+                newelem._copy_internals(**kw)
                 meth = visitors.get(newelem.__visit_name__, None)
                 if meth:
                     meth(newelem)
             return cloned[id(elem)]
 
     if obj is not None:
-        obj = clone(obj)
+        obj = clone(obj, clone=clone)
+
     return obj
 
 
@@ -463,9 +464,10 @@ def replacement_traverse(obj, opts, replace):
             else:
                 if elem not in cloned:
                     cloned[elem] = newelem = elem._clone()
-                    newelem._copy_internals(clone=clone, **kw)
+                    newelem._copy_internals(**kw)
                 return cloned[elem]
 
     if obj is not None:
-        obj = clone(obj, **opts)
+        obj = clone(obj, clone=clone, **opts)
+
     return obj

```

**Comment by zzzeek** [comment]
ugh, ok that doesnt actually work yet...

**Comment by carsonip** [comment]
Trying to achieve the same thing as `del clone`:
```
def f(obj):
    s = set()
    def inner(e, self=None):
        if e not in s:
            s.add(e)
            self(e, self=self)
    w = inner(obj, self=inner)
    return w
```

**Comment by zzzeek** [comment]
here it is, this works, it needs the other few clone-related changes you made in selectable.py

```
--- a/lib/sqlalchemy/sql/visitors.py
+++ b/lib/sqlalchemy/sql/visitors.py
@@ -405,20 +405,20 @@ def cloned_traverse(obj, opts, visitors):
     cloned = {}
     stop_on = set(opts.get("stop_on", []))
 
-    def clone(elem):
+    def clone(elem, _clone=None, **kw):
         if elem in stop_on:
             return elem
         else:
             if id(elem) not in cloned:
                 cloned[id(elem)] = newelem = elem._clone()
-                newelem._copy_internals(clone=clone)
+                newelem._copy_internals(_clone=_clone, clone=_clone, **kw)
                 meth = visitors.get(newelem.__visit_name__, None)
                 if meth:
                     meth(newelem)
             return cloned[id(elem)]
 
     if obj is not None:
-        obj = clone(obj)
+        obj = clone(obj, _clone=clone)
     return obj
 
 
@@ -449,7 +449,7 @@ def replacement_traverse(obj, opts, replace):
     cloned = {}
     stop_on = {id(x) for x in opts.get("stop_on", [])}
 
-    def clone(elem, **kw):
+    def clone(elem, _clone=None, **kw):
         if (
             id(elem) in stop_on
             or "no_replacement_traverse" in elem._annotations
@@ -463,9 +463,10 @@ def replacement_traverse(obj, opts, replace):
             else:
                 if elem not in cloned:
                     cloned[elem] = newelem = elem._clone()
-                    newelem._copy_internals(clone=clone, **kw)
+                    newelem._copy_internals(clone=_clone, _clone=_clone, **kw)
                 return cloned[elem]
 
     if obj is not None:
-        obj = clone(obj, **opts)
+        assert "clone" not in opts
+        obj = clone(obj, _clone=clone, **opts)
     return obj

```

**Comment by zzzeek** [comment]
DEBUG_SAVEALL is doing this thing where one test fails and then I can't get it to clean out the rest of the garbage before subsequent tests.   but it is also 3 AM here.  the way I'm doing it just with gc.collect() seems good enough for the most immediate cycles

**Comment by carsonip** [comment]
> here it is, this works, it needs the other few clone-related changes you made in selectable.py
> 
> ...

Looks good, but I guess some comments are needed to avoid confusing readers.

> DEBUG_SAVEALL is doing this thing where one test fails and then I can't get it to clean out the rest of the garbage before subsequent tests. but it is also 3 AM here. the way I'm doing it just with gc.collect() seems good enough for the most immediate cycles

Yeah let's call it a day for now. I think we have made good progress. I'll keep playing around.

**Comment by zzzeek** [comment]
with the branch for 1.3, your MCVE with the mappings goes from 354 for the rel_1_3 branch down to 20.     it's done :)

```
python test3.py 
[]
gc.garbage len = 20

```

**Comment by zzzeek** [comment]
if I revert just the cloned_traversal part of it, the number for your specific test goes up to 112.

**Comment by zzzeek** [comment]
Oook, 1.3 is good, but in 1.4 / master, something is still going wrong as master produces garbage len of 577 and 290 with the patch.

**Comment by carsonip** [comment]
I'm looking at the remaining 20 for 1.3, it requires just moving the `class ColumnsNotAvailable(Exception)` out of the function to either under the Mapper class or move it to global. This would bring us to 0.

**Comment by carsonip** [comment]
Let's say when we do:
```
session.query(Company).options(joinedload(Company.employees)).all()
```

There are still ref cycles in QueryContext, _ORMJoin, Load. Since some of these ref cycles are related to cached attributes (aka util.memoized_property), I'm not sure if you want these fixed because of the extra function calls.

The QueryContext one is doable but not elegant, and I am not sure if this will break things:
```
diff --git a/lib/sqlalchemy/orm/query.py b/lib/sqlalchemy/orm/query.py
index af8e1f116..c296e98ad 100644
--- a/lib/sqlalchemy/orm/query.py
+++ b/lib/sqlalchemy/orm/query.py
@@ -3910,7 +3910,7 @@ class Query(object):
 
         for rec in context.create_eager_joins:
             strategy = rec[0]
-            strategy(*rec[1:])
+            strategy(context, *rec[2:])
 
         if context.from_clause:
             # "load from explicit FROMs" mode,
diff --git a/lib/sqlalchemy/orm/strategies.py b/lib/sqlalchemy/orm/strategies.py
index 691be6a67..23792dd5d 100644
--- a/lib/sqlalchemy/orm/strategies.py
+++ b/lib/sqlalchemy/orm/strategies.py
@@ -1705,7 +1705,7 @@ class JoinedLoader(AbstractRelationshipLoader):
         context.create_eager_joins.append(
             (
                 self._create_eager_join,
-                context,
+                None,
                 entity,
                 path,
                 adapter,

```

**Comment by carsonip** [comment]
@zzzeek It appears that Inada Naoki bump into the issue of ref cycle due to recursive nested functions too. PyMySQL/mysqlclient-python@b3e775a
Apparently we could simply do `clone = None` to avoid the `_clone=_clone` mess and support Python 2 at the same time.

**Comment by carsonip** [comment]
Also do you think the fix in mysqlclient has anything to do with jenkins failing?

**Comment by zzzeek** [comment]
> @zzzeek It appears that Inada Naoki bump into the issue of ref cycle due to recursive nested functions too. [PyMySQL/mysqlclient-python@b3e775a](https://github.com/PyMySQL/mysqlclient-python/commit/b3e775a)
> Apparently we could simply do `clone = None` to avoid the `_clone=_clone` mess and support Python 2 at the same time.

I think I've fixed the reference cycles for the clone() thing in the current patch in review.   I pass in the "clone" func from the outside rather than referring to it directly inside.   py2 then allows me to "del clone" also but it's unnecessary as there are no cycles created in the first place.

**Comment by zzzeek** [comment]
> Also do you think the fix in mysqlclient has anything to do with jenkins failing?

yes definitely, some of the CI runs that got as far as running the tests against MySQL would pass on all backends except for MySQL so this is definitely a driver thing on the MySQL side.   Currently the CI is not getting that far because some of the weakref stuff I've added in most recent version is failing a tew other tests I have to fix.
