### ISSUE TITLE
Test on Postgres fail because prepared transactions are disabled by default

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5057]
While working on #5055 I encountered some error on postgres the type
```
psycopg2.errors.ObjectNotInPrerequisiteState: prepared transactions are disabled
HINT:  Set max_prepared_transactions to a nonzero value.
```
It seems that the default on postgres is to set it to 0. https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-MAX-PREPARED-TRANSACTIONS

I'll open a pr to add a requirement for it, as suggested by https://github.com/sqlalchemy/sqlalchemy/pull/5055#issuecomment-569296543

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Improve two phase transaction requirement detection for PG** https://gerrit.sqlalchemy.org/1632

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Improve two phase transaction requirement detection for PG** https://gerrit.sqlalchemy.org/1633
