### ISSUE TITLE
Potential bugs / typos found in code review

### ISSUE THREAD

**Issue by carsonip** [sqlalchemy/sqlalchemy#5060]
Keeping a list of weird things as I go through the code. I do not have enough understanding of the codebase yet, that's why I cannot tell for sure whether it is really a bug or how to fix it.

Unreachable code in mysql base:
https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/base.py#L2972

Unused parameter:
https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/dml.py#L630

Since I am still actively reading the code now, there may be more.

**Comment by zzzeek** [comment]
> Keeping a list of weird things as I go through the code. I do not have enough understanding of the codebase yet, that's why I cannot tell for sure whether it is really a bug or how to fix it.
> 
> Unreachable code in mysql base:
> https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/mysql/base.py#L2972

that is really weird that all of our flake8 stuff is not finding that

> 
> Unused parameter:
> https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/dml.py#L630
> 

right, that's code that isn't used anywhere but it's wrong yes.   not sure if that method should just be notimplemented for now.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**De-implement non-working / testing copy_internals from dml** https://gerrit.sqlalchemy.org/1634
