### ISSUE TITLE
Query inside column ORM object

### ISSUE THREAD

**Issue by hugoespinelli** [sqlalchemy/sqlalchemy#5066]
Versions:
Python: 3.7
SqlAlchemy: 1.3.12

Hi guys,
I have a table with a primary key that doesnt have auto increment. So in my ORM object, i need to do a query to obtain the last one primary key added. I tried to put this way:

class PPERSON(Base):
    __tablename__ = "PPERSON"
    __schema__ = GG_SCHEMA

    code = Column('CODE', Integer, primary_key=True)
    ...

    mysql_charset = 'utf8mb4'

    def __init__(self, rawPerson):
        metaTable = db.Table("PPERSON", metadata, autoload=True, autoload_with=connection.engine)
        self.code = db.select([db.func.max(metaTable.columns.CODE+ 1)])
       ...
 
But doesnt work as expected, give this error:

  File "C:\Users\hugoe\.virtualenvs\wordpress-dp-cUpxJYJt\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\hugoe\.virtualenvs\wordpress-dp-cUpxJYJt\lib\site-packages\sqlalchemy\engine\base.py", line 1318, in _cursor_execute
    self.dialect.do_execute(cursor, statement, parameters, context)
  File "C:\Users\hugoe\.virtualenvs\wordpress-dp-cUpxJYJt\lib\site-packages\sqlalchemy\engine\default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
  File "src\pymssql.pyx", line 468, in pymssql.Cursor.execute
sqlalchemy.exc.OperationalError: (pymssql.OperationalError) (1088, b'Cannot find the object "PPERSON" because it does not exist or you do not have permissions.DB-Lib error message 20018,
 severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')
[SQL: SET IDENTITY_INSERT [PPERSON] ON]
(Background on this error at: http://sqlalche.me/e/e3q8)

When i insert without ORM, works pefectly.

    metadata = db.MetaData()
    metaTable = db.Table('PPERSON', metadata, autoload=True, autoload_with=connection.engine)
    max_select = db.select([db.func.max(metaTable.columns.CODE+ 1)])
    ins = metaTable.insert().values(CODE=max_select)
    connection.execute(ins)

Any ideas?

**Comment by zzzeek** [comment]
your table is probably named "pperson" case insensitive.  please use all lower case names in SQLAlchemy, e.g.  Table('pperson', ...)   __tablename__ = 'pperson'.    If that's not it, turn on echo=True in create_engine() and view the SQL being emitted.

**Comment by hugoespinelli** [comment]
Nope, didn't work. This code shouldn't worked either if problem was case names.
`
metadata = db.MetaData()
metaTable = db.Table('PPERSON', metadata, autoload=True, autoload_with=connection.engine)
max_select = db.select([db.func.max(metaTable.columns.CODE+ 1)])
ins = metaTable.insert().values(CODE=max_select)
connection.execute(ins)
`

**Comment by zzzeek** [comment]
turn on echo=True in create_engine() and look at the SQL being rendered to try to determine the cause of the issue.   compare the one that works to the one that doesnt and find what's different.

**Comment by zzzeek** [comment]
please reopen if you have more information to share.
