### ISSUE TITLE
Executing Raw SQL String Beginning with a SELECT INTO does not return rows

### ISSUE THREAD

**Issue by yamen321** [sqlalchemy/sqlalchemy#5067]
I'm running into this issue trying execute raw sql from a sqlalchemy engine connected to my Microsoft SQL Server.

I've gone ahead and created a dummy table and inserted some dummy data via Microsoft SQL Server Management Studio so that I can demonstrate the problem I'm running into:

CREATE TABLE dummyTable (
	[Name] NVARCHAR(100),
	[Age] INT
)

INSERT INTO dummyTable ([Name], [Age])
VALUES ('John', 20), ('Jane', 22)

Now through Python, I've just opened up a transaction-less connection from my connected SQLAlchemy Engine like so:
`connection = engine.connect()`

I then try to execute the following:
`connection.execute(
"""
SELECT *
INTO #testTable
FROM dummyTable
SELECT * FROM #testTable
""")`

The above returns a result proxy object that returns no rows (resultProxyObject.returns_rows outputs 'False')

Executing the same raw SQL above in Microsoft SQL Server Management Studio properly returns
the two dummy rows from my dummy table...I can't seem to figure out why sqlalchemy won't return any rows. This seems to only happen whenever my query starts with a 'SELECT INTO' as even this fails to return any rows:

`connection.execute(
"""
SELECT *
INTO #testTable
FROM dummyTable
SELECT 1
""")`

I'd appreciate any insight! Please let me know if you have any questions!

**Comment by gordthompson** [comment]
```
SELECT * INTO #testTable FROM dummyTable SELECT * FROM #testTable
```

is not a single SQL statement. It is an *anonymous code block* consisting of two SELECT statements. The first (SELECT INTO) returns a row count, and the second (SELECT) returns a result set.

It is always a good idea to start any anonymous code block (or stored procedure) with `SET NOCOUNT ON;` to suppress the row counts so they don't "get in the way" of the result sets. You should be executing

```
SET NOCOUNT ON;
SELECT * INTO #testTable FROM dummyTable;
SELECT * FROM #testTable;
```

**Comment by yamen321** [comment]
That did the trick!
I didn't realize that row counts would interfere with my result sets. Thank you very much for your help @gordthompson
