### ISSUE TITLE
QueryContext ref cycle on eager joins

### ISSUE THREAD

**Issue by carsonip** [sqlalchemy/sqlalchemy#5071]
SQLAlchemy version: 1.3

`QueryContext` attribute `create_eager_joins` stores the arguments to strategy's `_create_eager_join`. But the arguments include QueryContext itself.

objgraph:
![image](https://user-images.githubusercontent.com/9133397/71660227-51882a80-2d85-11ea-973b-030f2da1920e.png)

A PR is coming up.

**Comment by sqla-tester** [comment]
**Carson Ip** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix QueryContext ref cycle on joinedload** https://gerrit.sqlalchemy.org/1652

**Comment by zzzeek** [comment]
does this apply to master as well ?

**Comment by zzzeek** [comment]
there's a big change to all of this coming in master but it isn't merged yet.

**Comment by sqla-tester** [comment]
**Carson Ip** has proposed a fix for this issue in the **master** branch:

**Fix QueryContext ref cycle on joinedload** https://gerrit.sqlalchemy.org/1653
