### ISSUE TITLE
Add Spatial Data Types

### ISSUE THREAD

**Issue by jbarker2160** [sqlalchemy/sqlalchemy#5078]
Please add support for spatial data types as well as spatial indices for all RDBMS.  Not having those data types limits utility.  Especially for mobile apps.

**Comment by zzzeek** [comment]
spatial datatypes are handled by the [geoalchemy2](https://geoalchemy-2.readthedocs.io/en/latest/) project.    The SQLAlchemy project itself would rather not duplicate this effort as spatial data types have many special complications and challenges to be met, however we will continue to support architectural needs of Geoalchemy2 as they are required.
