### ISSUE TITLE
quoted name is not applied to function name even when specified

### ISSUE THREAD

**Issue by andreychemarev** [sqlalchemy/sqlalchemy#5079]
There is one error when moving from 1.2.8 to 1.3.12 version.

I defined custom GenericFunction like this:

```python
class CustomFunction(GenericFunction): 
      type = Boolean 
      package = 'pack' 
      name = '"CustomFunction"' 
      identifier = 'CustomFunction'
```

When I used it with 1.2.8 version all was right, but when I use it
with 1.3.12 I get this error:
```postgresql
function "CustomFunction"(bigint) does not exist
```

I look at generated sql code and see following:

```postgresql
 SELECT ...,  """CustomFunction"""("columnName")  \nFROM ...
```

SQLAlchemy quotes already quoted name. I tried to find the reasons of this behaviour
and it seems it's in the `compiler.py` module. In particular, in the methods `requires_quotes` and `quote_identifier` of `IdentifierPreparer` class. They don't check if the name already has quotes.

In situation when name is without quotes, but in camel case, it converts name to lower case.

P.S. I use that GenericFunction definition when I need to construct dynamic query which
should contain calling of stored procedure in `select` section. For example:

```python
...
query = select([ 
    Table.c.column, 
    func.pack.CustomFunction(Table.c.column) ])

# code with conditions for adding relevant where clauses, like
# if condition:
#    query = query.where(...) 
...
``` 

Best regards.

**Comment by zzzeek** [comment]
hi there 

you are hitting some combination of #4467 and possibly #4569.

Please specify the database in use and exactly why this function name cannot be referred towards in a case-insensitive fashion, that is, without quotes, as in #4467 we were unable to identify a use case for this.  A function name that contains special characters will still be quoted.     assuming the quotes are necessary, use "sqlalchemy.sql.quoted_name" rather than hardcoding the quotes.

**Comment by andreychemarev** [comment]
The database in use is PostgreSQL (9.2). I have database with about hundred stored procedures named in camel case style. Some part of these doing some calculations such as distance between two points by coordinates, checking if point belongs some circle area, etc. (I know it's similar on PostGIS possibilities, but I don't have oppotunity to use PostGIS on database server). So, I need to extract some information from database with some estimated values and for this I use these stored procedures. 

It seems that using of `sqlalchemy.sql.quoted_name` is my solution. I haven't see it before, thanks!

**Comment by andreychemarev** [comment]
The database in use is PostgreSQL (9.2). I have database with about hundred stored procedures named in camel case style. Some part of these doing some calculations such as distance between two points by coordinates, checking if point belongs some circle area, etc. (I know it's similar on PostGIS possibilities, but I don't have oppotunity to use PostGIS on database server). So, I need to extract some information from database with some estimated values and for this I use these stored procedures.

It seems that using of sqlalchemy.sql.quoted_name is my solution. But it works only with hardcoding the quotes:

```python
class CustomFunction(GenericFunction):
    type = Boolean
    package = 'pack'
    name = quoted_name('"CustomFunction"', False)
    identifier = 'CustomFunction'
```

In case when `name = quoted_name('CustomFunction', False)` I get name without quotes and the same error.

So it should be?

**Comment by zzzeek** [comment]
to get the quotes you need `quoted_name("CustomFunction", True)` however it is not taking these into account so that is a bug.  

So to be clear you've named these functions all case sensitively with quoting ?

**Comment by zzzeek** [comment]
```diff
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index da527bbb1..e851ad9e7 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -1121,6 +1121,7 @@ class SQLCompiler(Compiled):
                 name = (
                     self.preparer.quote(name)
                     if self.preparer._requires_quotes_illegal_chars(name)
+                    or isinstance(name, elements.quoted_name)
                     else name
                 )
                 name = name + "%(expr)s"
@@ -1129,6 +1130,7 @@ class SQLCompiler(Compiled):
                     (
                         self.preparer.quote(tok)
                         if self.preparer._requires_quotes_illegal_chars(tok)
+                        or isinstance(name, elements.quoted_name)
                         else tok
                     )
                     for tok in func.packagenames

```

**Comment by zzzeek** [comment]
this has never been supported before, so not a regression, it's a new use case

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Support GenericFunction.name passed as a quoted_name** https://gerrit.sqlalchemy.org/1655

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Support GenericFunction.name passed as a quoted_name** https://gerrit.sqlalchemy.org/1656

**Comment by andreychemarev** [comment]
> So to be clear you've named these functions all case sensitively with quoting ?

Yes, all of them have case sensitively names (but names don't contain quotes). In PostgreSQL if you want to call stored procedure and its name contains upper-case symbols you should quote its name. For example, I have `CustomFunction` and call it through `select "CustomFunction"()`. That's why I used `name` property in `GenericFunction` with hardcoding quotes. Perhaps it should be considered as a feature of PostgreSQL syntax.
