### ISSUE TITLE
Bulk upsert - duplicates ORM mssql

### ISSUE THREAD

**Issue by felipe0216** [sqlalchemy/sqlalchemy#5080]
Hello,

I am currently reflecting a MSSQL table and doing a bulk insert to it, my problem is that I need to check/avoid duplicates and I don't know how to do it in SQLAlchemy syntax.

To give you some context, The SQL table is time series for a mortgage lender that contains 57 parameters including things such as "Loan ID", "Observation date","Month on Book", "Origination date", "Interest rate", etc. The clue to identify duplicates is in the "Month on book" since this can only have one row for each month after the "Origination Date" per "Loan ID". Each Loan ID would have different "Origination dates" and "Observation date", but the "Month on Book" encoding would be the same for every Loan ID.

For example:

Current date: March 2018

Origination Date: 30 Jan 2018

Observation Date: 30 March 2018

Month on Book: 2 (February would be "1" and Jan would be "0")

Since the table in MS SQL is already populated I want to insert new rows, but only having one record of month on book (the encoded version of "Observation Date") per LoanID (just in case someone runs the insert code twice, it doesn't duplicate all the data)

This is how I am currently doing the whole insert process up to the duplicate exception (see "sqlalchemy_orm_bulk_insert" or "sqlalchemy_core_insert". Also, I know that the class I created to standardise the connection-insertion process with SQl Alchemy could be a bit crap, so if someone has any suggestions, they would be more than welcomed.

```
class SQLAlchemy_cashflow():
    def __init__(self,database, user, password, sql_schema, driver, server):
        self.sql_schema = sql_schema
        self.driver = driver
        self.server = server
        self.database = database
        self.user = user
        self.password = password

        params = urllib.parse.quote_plus('Driver={'+str(self.driver)+'};'\
                                    "SERVER="+str(self.server)+";"\
                                    "Database="+str(self.database)+";"
                                    "UID="+str(self.user)+";"\
                                    "PWD="+str(self.password)+";"\
                                    "Trusted_Connection=yes"
                                    )
        engine = sa.create_engine("mssql+pyodbc:///?odbc_connect=%s" % params)
        self.engine = engine

        conn = engine.connect()
        metadata = MetaData(schema=sql_schema)
        Base = declarative_base(metadata= metadata)
        Base.metadata.reflect(engine)
        Session = sessionmaker(bind=engine)
        session = Session()

        self.metadata = metadata
        self.Base = Base
        self.session = session


    def reflection(self, sql_table):
        self.sql_table = sql_table
        class MyClass(self.Base):
            __table__ = self.Base.metadata.tables[self.sql_table]
        table_reflected = Table(sql_table, self.metadata, autoload=True, autoload_with = self.engine)
        return MyClass, table_reflected
    

    def sqlalchemy_orm_bulk_insert(self,class_object, df):
        connection("dbo")
        t0 = time.time()
        session.bulk_insert_mappings(class_object,
                                    df.to_dict(orient="record"))
        session.commit()
        print("SQLAlchemy ORM bulk_insert_mappings(): Total time for " + str(len(df)) +
            " records " + str(time.time() - t0) + " secs")


    def sqlalchemy_core(self, class_object, df):
        connection("dbo")
        t0 = time.time()
        engine.execute(class_object.__table__.insert(),
                    df.to_dict(orient="record"))
        print("SQLAlchemy Core: Total time for " + str(len(df)) + " records " +
            str(time.time() - t0) + " secs")


```

**Comment by zzzeek** [comment]
I can't write out a complete example right now but the general idea is:

1. sort the records you are merging in, on the keys that comprise the "duplication" you are checking for.

2. run through your sorted records in batches, like 1000 at a time.

3. for each batch, retrieve from the database all the records that already exist in that batch, using SELECT...WHERE rec IN (...)  .

4. organize the records in 3 into a dictionary, keyed on the fields you are deduping on.

5. iterate through your insert set again.   for each record, look in the dictionary from step 4 to see if the record already exists.   run those matches into an UPDATE list rather than an INSERT list.

6. invoke statements for that batch

7. move to next batch

**Comment by felipe0216** [comment]
Hello!

Thanks for your reply. It was really helpful. Just one thing, on the third point "SELECT...WHERE rec IN (...)" since the "IN (...)" the (...) would be columns in a pandas dataframe, so the sql query won't recognise it, how can you mitigate this?

**Comment by zzzeek** [comment]
> Hello!
> 
> Thanks for your reply. It was really helpful. Just one thing, on the third point "SELECT...WHERE rec IN (...)" since the "IN (...)" the (...) would be columns in a pandas dataframe, 

you need to expand the data yourself into simple tuples

> so the sql query won't recognise it, so when you say "run through your sorted records in batches, like 1000 at a time.", you mean bringing the first 1000 records from the database with a query, 

IIUC you have a set of records that are outside of the database, that is, in memory or a file or something, with which you mean to INSERT/UPDATE them into the database.  this is the set of records for which I would chunk in groups, assuming it's a large set of data (otherwise why use bulk methods).

> then make those records a pandas dataframe and compare it with the data I want to insert (also a pandas df) and then repeat?

when dealing with SQLAlchemy you need to convert "dataframes" into regular Python values, above I see the use of "dataframe.to_dict()", using that, then extracting the values which apply to the key being checked for "upsert".

**Comment by felipe0216** [comment]
Yes, I have records that I have extracted from a spreadsheet and I have converted them into a dataframe, it is indeed a large dataset (100k rows), but sometimes it is very small (300 rows). Yes, I mean to Insert/Update these records to the database.

Yes, I understand that I need to convert these values into records, in the same way it is done for the "bulk_insert_mapping()". My main question is regarding the SQL query needed for it in ORM since it is done using mssql which doesn't accept some of the methods such on "on_conflict_do_update" or others that I think could be useful.

A more tangible example would be: I have a spreadsheet (transformed to dataframe) that contains several Loans, each Loan has its LoanID, this identifier is repeated for each record in the time series(let's say 20 dates for each loan), one of the first things I want to do is is _select from the database all the LoanID that are in this dataframe, then check that the time series values in the database (dates entries in each loan) exist or not in the dataframe, once I have done that, the idea is to insert those that don't exist and update the ones that do_.

**Comment by zzzeek** [comment]
there's a slight ambiguity in how you are describing the problem: "then check that the time series values in the database exist or not in the **dataframe**"   this sounds backwards?

to be clear, the "dataframe" is the **source** of the data, and the "database" is the **destination** of the data, correct?    

can you extract from your dataframe a list of tuples, of the form [(LoanId, timevalue), (LoanId, timevalue), ...] ?  that is, you must extract the **key** on which you are attempting to deduplicate upon.

**Comment by felipe0216** [comment]
Oh I see what you mean, I said it like that because I am comparing the database to the dataframe and not the dataframe to the database.

Yes, dataframe is the source and database the destination.

Yes, just need to slice the two columns from the df and use the new_df.to_dict("orient") to leave it in that format. So I want to check the duplicates on the "timevalue" that would be my key, but first I need to make sure that I am matching it with the right LoanID in the database, does that make sense?

**Comment by jvanasco** [comment]
I've done similar bulk actions/migrations a few times, and basically use a variation of Michael's approach - but I stay away from the bulk operations api and just use multiple processes.

First:

I write a script to iterate over all the "source" in batches of n (1000?) using the 'windowed range query' technique (https://github.com/sqlalchemy/sqlalchemy/wiki/WindowedRangeQuery)

I analyze each item to determine if it is an insert, update, or advanced migration... then do the sql for that item.

Then:

I adapt the script to use Redis as a coordinator to determine the start value for the windowed query's offset.  This allows me to spin up multiple processes of the same migration script.  I forget who first suggested this technique, it may have been Simon King.

I usually get an initial 6 processes going before I start testing to see if additional processes increase or decrease efficiency.

This multi-process approach has made many (ver large) bulk operations process in under an hour instead of overnight.

**Comment by felipe0216** [comment]
Hello @jvanasco,

Thanks for your answer, it did help me a bit to understand how to do it. One thing, I just don't get where you are doing the comparison between your data that you want to insert and the data that is already in the database, from what I see, what the code is doing is to check for duplicates in the database, but the idea would be to check for duplicates before the data is inserted to the database using the session, and if it is duplicated, update those records

**Comment by jvanasco** [comment]
@felipe0216 this example might be more clear. it's a stripped down version of one of my template scripts

in this situation, to migrate `MIGRATED_TABLE` which is in PostgreSql, I create a new table `migration_yyyymmdd_id_logger` and stash the ids of items that need to be migrated into it.  

then I just keep querying that table - using multiple processes.  

Redis is used to coordinate the offset.
The logging table in postgres is used for both selecting data, and querying to determine how fast the migration is going.  i'll quickly toss together a script to query the migrated/not-migrated data every 60s, and manually add/remove workers based on that.

adapting this to your situation, i'd query the pandas source in the True loop, then probably do a sqlalchemy select to determine if i need an insert or update in `migrate_record`.

there are many ways to tackle this sort of stuff. i've just found this one to be the fastest for our use cases when it comes to developing and running.


```python
"""
THIS EDIT REQUIRES REDIS
redis is used to coordinate multiple workers.

IF THIS BREAKS, REDIS/POSTGRES must be reset

This is used to migrate the ____ table 



How to run:

    1. Ensure we have the correct table:

        BEGIN;
        CREATE TABLE migration_yyyymmdd_id_logger (id INT PRIMARY KEY, is_migrated BOOLEAN DEFAULT NULL);
        INSERT INTO migration_yyyymmdd_id_logger (SELECT id, NULL FROM {MIGRATED_TABLE} WHERE {{params identifying the need to migrate}});
        COMMIT;

    2. Get the max id of the table; this is used as a safety check. edit it into the script below
        todo: this should be an env var

    3. run this file:

        python {{filename}}.py

    4. audit:
        select count(*)  as counted, is_migrated from migration_yyyymmdd_id_logger group by is_migrated;

    5. finalize
        VACUUM FULL {MIGRATED_TABLE};
        \d {MIGRATED_TABLE}

"""
# ##############################################################################


# container object just sets up our db connection
api = IntegratedApi(setup_logging=True, expire_on_commit=False)
request = api.bootstrapped.request
dbSession = api.bootstrapped.request.dbSession.writer


# ##############################################################################


class Migration_YyyyMmDd_Id_Logger(
    ci_model.DeclaredTable, ci_model.UtilityObject
):
    """
    This table is used to log migration status
    """

    __tablename__ = "migration_yyyymmdd_id_logger"
    id = sqlalchemy.Column(
        sqlalchemy.Integer,
        sqlalchemy.ForeignKey("{MIGRATED_TABLE}.id"),
        nullable=False,
        primary_key=True,
    )
    is_migrated = sqlalchemy.Column(
        sqlalchemy.Boolean, nullable=True, primary_key=False, default=None
    )

    migrated_table = sqlalchemy.orm.relationship(
        "{MIGRATED_TABLE_CLASS}", uselist=False
    )


# ##############################################################################


def redis_connection(host="localhost", port=6379, db=0):
    redCon = redis.StrictRedis(host=host, port=port, db=db)
    return redCon


redCon = redis_connection(host="localhost", port=6379, db=0)

# todo: make this an env var
_max_id = 93634  # dev value of `select max(id) from migrated_table;`
result = dbSession.execute(
    sqlalchemy.text("select max(id) from {MIGRATED_TABLE};")
).first()
max_id = result[0]
if not max_id or (max_id < _max_id):
    raise ValueError("not max")

batchsize = 500


# ##############################################################################


def migrate_record(dbMig):
    """our core db migration function"""
    dbMigratedTable = dbMig.migrated_table
    if not dbMigratedTable:
        raise ValueError("Missing dbMigratedTable")

    #
    # perform migration here
    #
    
    # commit changes
    dbSession.flush()

    # log it
    dbMig.is_migrated = True
    dbSession.flush(
        objects=[dbMig,]
    )


while True:
    # each iteration of this block
    
    # if the value doesn't exist on first run, this gets set to 0.
    # thread 1 - doesn't exist: offset set to 500; fixed to 0
    # thread 2 - value is 500; offset set to 1000; fixed to 500
    offset_incremented = redCon.incrby("migration-{{filename}}-offset", batchsize)
    offset = offset_incremented - batchsize
    if offset > max_id:
        print("offset > max_id ; graceful exit")
        break
    query = (
        dbSession.query(Migration_YyyyMmDd_Id_Logger)
        .filter(
            Migration_YyyyMmDd_Id_Logger.is_migrated.op("IS")(None),
            Migration_YyyyMmDd_Id_Logger.id >= offset,
            Migration_YyyyMmDd_Id_Logger.id < (offset + batchsize),
        )
        .options(
            sqlalchemy.orm.joinedload("{MIGRATED_TABLE}")
        )
        .order_by(Migration_YyyyMmDd_Id_Logger.id.asc(),)
    )

    dbMigrations = query.all()
    print("OFFSET - %s - Loaded %s migrations" % (offset, len(dbMigrations)))

    for dbMig in dbMigrations:
        migrate_record(dbMig)

    # commit this batch
    dbSession.commit()
    print("OFFSET - %s complete")

# ##############################################################################

api.finish()
```

**Comment by felipe0216** [comment]
Hello @jvanasco,

Thank you so much for taking the time to write this example, it was really helpful! much appreciated.
