### ISSUE TITLE
 SQL Alchemy dynamic class - declarative_base losing attributes

### ISSUE THREAD

**Issue by MrDominikku** [sqlalchemy/sqlalchemy#5081]
Hi,

Based on below posts
- [dynamic-schema](http://sparrigan.github.io/sql/sqla/2016/01/03/dynamic-tables.html)
- [Dynamic Class Creation in SQLAlchemy](https://stackoverflow.com/questions/2768607/dynamic-class-creation-in-sqlalchemy#)

I wanted to make similar thing in my [project](https://github.com/MrDominikku/MYOPM). I use `declarative_base()` class for core ORM models stored in `db_models.py`, additionally depends on user settings I want to create and store dynamic classes in `BASE._dec_class_registry` (`db_manage.py`>`LotteryDatabase`>`self._initial_database`>`self.create_class_model`) those dynamic classes vary depends on params combinations from `games_config.py`.
Problem starts when the first `self.create_class_model` method is called it's correctly adding class to `BASE._dec_class_registry`, but when calling next one `BASE` "losing" first class and adding new one and so on. When `BASE.metadata.create_all()` is called all tables are created in schema, but I can't access this dynamic classes using `LotteryDatabase`>`self.set_model_by_table_name`.

I tried doing it with raw test example:

models.py

```
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Integer, Column
 
BASE = declarative_base()
 
 
class NewClass(BASE):
 
    __tablename__ = 'test'
 
    id = Column('id', Integer, primary_key=True)
```

test.py

```
from models import *
from sqlalchemy import create_engine
 
DB_ENGINE = 'sqlite:///my_db.db'
 
 
def main():
 
    engine = create_engine(DB_ENGINE)
 
    BASE.metadata.create_all(engine)
 
    input_params = {'__tablename__': 'test1',
                    'id': Column('id', Integer, primary_key=True)}
 
    _ = type('InputClass', (BASE,), input_params)
 
    model_params = {'__tablename__': 'test2',
                    'id': Column('id', Integer, primary_key=True)}
 
    _ = type('ModelClass', (BASE,), model_params)
 
    predict_params = {'__tablename__': 'test3',
                      'id': Column('id', Integer, primary_key=True)}
 
    _ = type('PredictClass', (BASE,), predict_params)
 
    BASE.metadata.create_all(engine)
```

In this example all classes where created and added to `BASE`, so problem is with my code and I am missing something. Your fresh look would be very helpful!
Application is fully operational and including `requirements.txt` file for packages.

For better inside what I am talking about, step by step example using debug mode. (look image below)

I have rewrote code so all class attributes are stored in dictionary and then used in creating models.

![declarative_base](https://user-images.githubusercontent.com/32632165/71840322-6504ff80-30bd-11ea-8970-e6c1a3b32fb4.jpg)

**Comment by zzzeek** [comment]
hi - 

your sample code puts the classes in _decl_class_registry fine, below is your code with the classes being retrieved:
```

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Integer, Column

BASE = declarative_base()


class NewClass(BASE):

    __tablename__ = 'test'

    id = Column('id', Integer, primary_key=True)


input_params = {'__tablename__': 'test1',
                'id': Column('id', Integer, primary_key=True)}

_ = type('InputClass', (BASE,), input_params)

model_params = {'__tablename__': 'test2',
                'id': Column('id', Integer, primary_key=True)}

_ = type('ModelClass', (BASE,), model_params)

predict_params = {'__tablename__': 'test3',
                  'id': Column('id', Integer, primary_key=True)}

_ = type('PredictClass', (BASE,), predict_params)


input_class = BASE._decl_class_registry["InputClass"]
model_class = BASE._decl_class_registry["ModelClass"]
predict_class = BASE._decl_class_registry["PredictClass"]

from sqlalchemy.orm import Session
print(Session().query(predict_class))
```

I don't have the resources to go looking at your full application but the basic idea works, if you need help with your app see if you can find folks on the IRC channel to take a look for you, or otherwise try to reverse your code back to the sample above to see what's different.

**Comment by zzzeek** [comment]
reopen if you have further questions thanks!

**Comment by MrDominikku** [comment]
Thanks, my solution for that is to create global `DYNAMIC_CLASS` and store all `_ = type(class_name, (BASE,), params)` and call it on run. `BASE._dec_class_registry` don't losing attributes then🙂
