### ISSUE TITLE
'only' used twice in engine.base

### ISSUE THREAD

**Issue by NotKhalifornia** [sqlalchemy/sqlalchemy#5091]
I will fix when I get home, the init documentation of the connection class has a little typo:

`        The constructor here is not public and is only called only by an
        :class:`.Engine`. See :meth:`.Engine.connect` and
        :meth:`.Engine.contextual_connect` methods.`

should be

`        The constructor here is not public and is only called by an
        :class:`.Engine`. See :meth:`.Engine.connect` and
        :meth:`.Engine.contextual_connect` methods.`

**Comment by zzzeek** [comment]
this is a typo, no issue is required feel free to send a PR.
