### ISSUE TITLE
spurious SQL UPDATE being emitted when Geography has not changed

### ISSUE THREAD

**Issue by matthew-emw** [sqlalchemy/sqlalchemy#5093]
@zzzeek fresh from our recent brief but efficient collaboration on https://github.com/sqlalchemy/alembic/pull/636 i thought i'd file this issue here but with this disclaimer: I'm conscious that the root cause of this issue might lie within geoalchemy2. apologies in advance if this turns out to be the case.

observed behaviour:
i'm using sqlalchemy 1.3.11 with a PostgreSQL/PostGIS backend
i have a table with a Geography column that represents a GIS point
i retrieve row from that table
i update the GIS point _with the same lat/lon values as before_
i observe an unexpected SQL update is issued to the database

exposition in code:
```
from datetime import datetime
from decimal import Decimal

import geoalchemy2
from geoalchemy2 import Geography
from shapely.geometry import Point
from sqlalchemy.event import listens_for
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import (
    class_mapper,
    sessionmaker)
from sqlalchemy.orm.session import Session
from sqlalchemy import (
    create_engine,
    inspect,
    Column,
    Integer,
    String, Numeric, DateTime)


engine = create_engine('<database-connection-string>', echo=True)
session = sessionmaker(bind=engine, autoflush=False)()
Base = declarative_base()


class Place(Base):
    __tablename__ = "place"
    id = Column('ID', Integer, primary_key=True)
    name = Column('NAME', String(50))
    latitude = Column('LATITUDE', Numeric(10, 8), nullable=False)
    longitude = Column('LONGITUDE', Numeric(11, 8), nullable=False)
    geo_point = Column('GEO_POINT', Geography(geometry_type='POINT', srid=4326), nullable=False)
    modified = Column('MODIFIED', DateTime(), nullable=False)


@listens_for(Place, "before_update")
def before_update(mapper, connection, target):
    session = Session.object_session(target)

    if session.is_modified(target, include_collections=False):
        print('target is modified')
        target.modified = datetime.utcnow()
        inspection_object = inspect(target)
        attrs = class_mapper(target.__class__).column_attrs
        for attr in attrs:
            hist = getattr(inspection_object.attrs, attr.key).history
            print("attribute {} has changes: {}".format(attr.key, hist.has_changes()))

            if len(hist.added):
                print("added: {}".format(hist.added[0]))

            if len(hist.deleted):
                print("deleted: {}".format(hist.deleted[0]))
    else:
        print('target is NOT modified')


with engine.begin() as connection:
    metadata = Base.metadata
    metadata.create_all(connection)

session.execute('TRUNCATE TABLE place')

print("\n\nAdding a place")
place = Place()
place.latitude = Decimal('{0:2.8f}'.format(52.238049))
place.longitude = Decimal('{0:3.8f}'.format(6.0916571111111))
place.geo_point = geoalchemy2.shape.from_shape(Point(place.longitude, place.latitude), srid=4326)
place.name = 'placename'
place.modified = datetime.utcnow()
session.add(place)
session.commit()
session.close()

print("\n\nBeginning new session")
session = sessionmaker(bind=engine, autoflush=False)()

print("\n\nFinding a place")
place = session.query(Place).filter(Place.name == 'placename').one()

print("\n\nUpdating a place")
place.latitude = Decimal('{0:2.8f}'.format(52.238049))
place.longitude = Decimal('{0:3.8f}'.format(6.0916571111111))
place.geo_point = geoalchemy2.shape.from_shape(Point(place.longitude, place.latitude), srid=4326)
place.name = 'placename'
session.add(place)
session.flush()
```

and the [partial] output from this:
```
2020-01-13 12:41:46,622 INFO sqlalchemy.engine.base.Engine TRUNCATE TABLE place
2020-01-13 12:41:46,622 INFO sqlalchemy.engine.base.Engine {}


Adding a place
2020-01-13 12:41:46,649 INFO sqlalchemy.engine.base.Engine INSERT INTO place ("NAME", "LATITUDE", "LONGITUDE", "GEO_POINT", "MODIFIED") VALUES (%(NAME)s, %(LATITUDE)s, %(LONGITUDE)s, ST_GeomFromWKB(%(ST_GeomFromWKB_1)s, %(ST_GeomFromWKB_2)s), %(MODIFIED)s) RETURNING place."ID"
2020-01-13 12:41:46,649 INFO sqlalchemy.engine.base.Engine {'NAME': 'placename', 'LATITUDE': Decimal('52.23804900'), 'LONGITUDE': Decimal('6.09165711'), 'ST_GeomFromWKB_1': <memory at 0x7fc7d06eb7c8>, 'ST_GeomFromWKB_2': 4326, 'MODIFIED': datetime.datetime(2020, 1, 13, 11, 41, 46, 648390)}
2020-01-13 12:41:46,651 INFO sqlalchemy.engine.base.Engine COMMIT


Beginning new session


Finding a place
2020-01-13 12:41:46,659 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-01-13 12:41:46,661 INFO sqlalchemy.engine.base.Engine SELECT place."ID" AS "place_ID", place."NAME" AS "place_NAME", place."LATITUDE" AS "place_LATITUDE", place."LONGITUDE" AS "place_LONGITUDE", ST_AsBinary(place."GEO_POINT") AS "place_GEO_POINT", place."MODIFIED" AS "place_MODIFIED" 
FROM place 
WHERE place."NAME" = %(NAME_1)s
2020-01-13 12:41:46,661 INFO sqlalchemy.engine.base.Engine {'NAME_1': 'placename'}


Updating a place
target is modified
attribute id has changes: False
attribute name has changes: False
attribute latitude has changes: False
attribute longitude has changes: False
attribute geo_point has changes: True
added: 01010000006095875cdb5d184039ecbe63781e4a40
deleted: 01010000006095875cdb5d184039ecbe63781e4a40
attribute modified has changes: True
added: 2020-01-13 11:41:46.666385
deleted: 2020-01-13 11:41:46.648390
2020-01-13 12:41:46,667 INFO sqlalchemy.engine.base.Engine UPDATE place SET "GEO_POINT"=ST_GeomFromWKB(%(ST_GeomFromWKB_1)s, %(ST_GeomFromWKB_2)s), "MODIFIED"=%(MODIFIED)s WHERE place."ID" = %(place_ID)s
2020-01-13 12:41:46,668 INFO sqlalchemy.engine.base.Engine {'ST_GeomFromWKB_1': <memory at 0x7fc7d06eb888>, 'ST_GeomFromWKB_2': 4326, 'MODIFIED': datetime.datetime(2020, 1, 13, 11, 41, 46, 666385), 'place_ID': 16}

Process finished with exit code 0

```

I draw attention to the section
```
attribute geo_point has changes: True
added: 01010000006095875cdb5d184039ecbe63781e4a40
deleted: 01010000006095875cdb5d184039ecbe63781e4a40
```

I've done my best to understand the issue by stepping through the code. The key stage seems to be the call to ```from_scalar_attribute``` within class History in sqlalchemy.orm.attributes on line 1655. I confess to losing full grasp of the flow once the step-through goes inside ```attribute.is_equal(current, original)```. I would expect this to return True, but it doesn't.

If this is a legitimate issue, I'd be happy to assist with producing a fix, if it's within my abilities. I'd also be grateful for any suggested workarounds.

**Comment by zzzeek** [comment]
heya -

OK so the UPDATE shows just the geometry column being updated, which would mean when SQLAlchemy asks this datavalue if the original value loaded from the database, and the new value you just assigned, are equal, it returns False.    since the issue doesn't occur with any ot the other datatypes we know this is something specific to the geoalchemy datatype.

specifically when you note that `attribute.is_equal(current, original)` should return True, but doesn't, that seems like that's basically where the bug is.  that line of code is calling upon a callable that is set on line 537 of attributes.py in current master, it is either the function "operator.eq" from Python stdlib, or it is a "compare_function" passed in by the ColumnProperty, which SQLAlchemy will get from the datatype itself, e.g. the Geography datatype.   which looking at [their source](https://github.com/geoalchemy/geoalchemy2/blob/master/geoalchemy2/types.py) it does not seem like they override it, so it is simply "x == y".

This can be figured out pretty quickly using pdb.set_trace(), if you know how.   Basically the Geography loaded from the database does not match the one you are setting.   This could be because the "shape" object has some issue with its "__eq__()" method (it seems to come from some library called "shapely") or possibly more likely is that the value being loaded from the database is not the same as what you put in; this often happens when the database is storing the particular data with lower precision than what is being passed in.

in your test script, if you do this:

```
place = session.query(Place).filter(Place.name == 'placename').one()
assert place.geo_point == geoalchemy2.shape.from_shape(Point(place.longitude, place.latitude), srid=4326)

```
that should come out as False and that might tell you something.

**Comment by matthew-emw** [comment]
i've added this block for elucidation:
```
print("\n\nFinding a place")
place = session.query(Place).filter(Place.name == 'placename').one()
old_geo_point = place.geo_point
forthcoming_new_geo_point = geoalchemy2.shape.from_shape(Point(Decimal('{0:3.8f}'.format(6.0916571111111)), Decimal('{0:2.8f}'.format(52.238049))), srid=4326)
assert old_geo_point.desc == forthcoming_new_geo_point.desc
assert old_geo_point == forthcoming_new_geo_point
```
the first assert passes, the second fails.

this 'desc' field is the actual WKB - in this case "01010000006095875cdb5d184039ecbe63781e4a40" - this hits the database as:
```
UPDATE place SET "GEO_POINT"=ST_GeomFromWKB('\x01010000006095875cdb5d184039ecbe63781e4a40'::bytea, 4326), "MODIFIED"='2020-01-13T16:52:12.968881'::timestamp WHERE place."ID" = 28;
```
in other words, equivalence of the 'desc' field should be sufficient for equivalence of the Geography objects.

(it was seeing this 'desc' field in my IDE and original output as being the same that led me to erroneously think my objects were equivalent - they obviously differ in some less relevant attribute(s))

so, to my mind, the next step is to look to introduce the compare_function override to the Geography object over at the geoalchemy2 project - does that make sense, or am i barking up the wrong tree?

**Comment by zzzeek** [comment]
geoalchemy2 objects should compare as expected so this would be on their end.     The most ideal way would be if the fundamental objects being compared would simply implement a working ``__eq__()`` and ``__ne__()`` method.     so this would not be at the typing level, just in terms of the "shape" objects you get back and nothing else.

if that's not appropriate then the next hook would be in geoalchemy2 to add the "compare_values" method to the Geography database type, the ORM would pick that up.

**Comment by matthew-emw** [comment]
many thanks for your guidance. implementing a ```__eq__()``` as you describe makes the behaviour conform to my expectations. i'm going to head on over to geoalchemy2, reference this discussion and see what can be done. thanks again.

**Comment by zzzeek** [comment]
hey there.

um, I can't follow that change quickly as I'd rather see it in diff format, but again, this is not a known issue in the unit of work, it does not emit unnecessary UPDATE statements in this scenario if nothing on an attriibute has changed.   attributes that log no change are not included and there's no UPDATE statement.     so you would have to illustrate an MCVE that shows the bug in SQLAlchemy alone and it would be preferable if it were with a test datatype that isn't dependent on geoalchemy2.

**Comment by zzzeek** [comment]
is it perhaps that this Geoalchemy object happens to also subclass ClauseElement, and that is the unusual case here?    I'm not sure why such an object would also be itself persisted, so again this seems like something a little off in Geoalchemy.   You would not be persisting a ClauseElement object as a non SQL expression.    an object is either a literal value, or a ClauseElement.  It can't be both.

**Comment by matthew-emw** [comment]
thanks again for your input. and apologies for jumping the gun a bit earlier.

i'll go away, learn more about ClauseElement, and aim to produce a better-focused demonstration of my issue.

**Comment by zzzeek** [comment]
so yeah, this is not how any of this was intended to work:

```
Pdb) thing
<WKBElement at 0x7f79c10d3b10; 01010000006095875cdb5d184039ecbe63781e4a40>
(Pdb) thing == thing
<sqlalchemy.sql.elements.BinaryExpression object at 0x7f79c0aa09d0>
(Pdb) bool(thing == thing)
True
(Pdb) place.geo_point
<WKBElement at 0x7f79c0abca10; 01010000006095875cdb5d184039ecbe63781e4a40>
(Pdb) place.geo_point == place.geo_point
<sqlalchemy.sql.elements.BinaryExpression object at 0x7f79c0aa0a10>

```

it's one thing to assign a SQL expression to the element but the fact that the database-loaded value is a ClauseElement, this is concerning because this suggests a pretty deep design issue in geoalchemy2...noting that this may be based on things I gave them many years ago.  going to look now

**Comment by zzzeek** [comment]
this is over on the geoalchemy side.   I dont think SQLAlchemy should add additional hooks to guess if an object that intends to be both SQL and a value at the same time is one or the other, IMO these two kinds of objects are separate.
