### ISSUE TITLE
integrate `pyproject.toml`; deprecate `setup.cfg`

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#5100]
SqlAlchemy has adopted `black` code formatting, which is enforced by the `pre-commit` hook in the configuration file `.pre-commit-config.yaml` https://github.com/sqlalchemy/sqlalchemy/blob/master/.pre-commit-config.yaml

The usage of `black` requires it to be invoked with `-l 79` which is declared in .pre-commit-config.yaml (https://github.com/sqlalchemy/sqlalchemy/blob/master/.pre-commit-config.yaml#L8)

The `black` project specifically recommends configuration data be stored in `pyproject.toml` (https://black.readthedocs.io/en/stable/version_control_integration.html), which is the only configuration file consulted (https://black.readthedocs.io/en/stable/pyproject_toml.html and various rejected tickets on black's github)

Adopting a `pyproject.toml` file is something we should do to:

* more correctly store the `black` settings
* alert developers to know `black` is being used
* move towards new standards

Ideally we can do this in two phases:

* add pyproject.toml for `black`
* migrate `setup.cfg` items to `pyproject.toml`  

However there are two concerns (if not more):

1. It is unknown how various components that currently use `setup.cfg` will react to a `pyproject.toml` file being present. Mike recalls at least one might be.  The first phase could break the current build and test systems.

2. migrating from `setup.cfg` might also break things.

See Also:
* This ticket is a continuation of discussion from https://github.com/sqlalchemy/dogpile.cache/pull/169
* PEP 518 (https://www.python.org/dev/peps/pep-0518/) advocates `pyproject.toml` over `setup.cfg` for build configuration
* `setuptools` is considering a deprecation of "setup.cfg", however the period would be "forever"  (see https://github.com/pypa/setuptools/issues/1688)

**Comment by CaselIT** [comment]
Regarding 1. in my local branch have a pyproject.toml to correctly use black and I have not experienced issues with flake8 or pytest.

**Comment by zzzeek** [comment]
let's add pyproject.toml, and whatever tools we use that support it, move the settings there.  which seem to be, "black".   so as far as "Deprecate setup.cfg", sure, but for now that means nothing since most of what we have still needs to be in there.   

Basically PR == one pyproject.toml file with a single "-l 79" setting inside of it, remove from .pre-commit-config.yaml :)    let's also upgrade to the most recent black.

**Comment by CaselIT** [comment]
Opened in https://github.com/sqlalchemy/sqlalchemy/pull/5103

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add pyproject** https://gerrit.sqlalchemy.org/1690

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Add pyproject** https://gerrit.sqlalchemy.org/1691

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add pyproject** https://gerrit.sqlalchemy.org/1690

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Add pyproject** https://gerrit.sqlalchemy.org/1691
