### ISSUE TITLE
filter by date for an datetime field does not work with SQLite, but works with PostgreSQL

### ISSUE THREAD

**Issue by arqeco** [sqlalchemy/sqlalchemy#5104]
SQLAlchemy: filter by date for an datetime field(does not work with SQLite, with PostgreSQL it works fine)

https://gist.github.com/danielthiel/8374607

**Comment by zzzeek** [comment]
hi there -

per the gist, use the DATE() function to convert from a full timestamp to date only: https://www.sqlite.org/lang_datefunc.html

SQLAlchemy does not have backend agnostic date operators.

**Comment by arqeco** [comment]
Hello zzzeek,

In my case what I need is DATETIME instead of DATE.

Anyway, the interesting thing here is that to get the next record the use of func.DATETIME is not needed but to get the previous record it is required. Why? This code below works.

```python
def get_next_note(current_record):
    next = session.query(Note).order_by(Note.creation_datetime.asc()).  \
        filter(Note.creation_datetime > current_record.creation_datetime).  \
        first()
    return next

def get_previous_note(current_record):
    previous = session.query(Note).order_by(Note.creation_datetime.desc()).  \
        filter(func.DATETIME(Note.creation_datetime) < func.DATETIME(current_record.creation_datetime)).  \
        first()
    return previous

```

**Comment by zzzeek** [comment]
It's hard for me to follow things from out of context code fragments but please note that in SQLite these dates are stored as  strings.    Turn on echo=True which will illustrate the SQL being emitted so that you can examine the values being compared.

**Comment by arqeco** [comment]
Ok.
Thank you zzzeek
