### ISSUE TITLE
Descending indexes for Firebird

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5106]
Another issue with the (soon to be external) Firebird dialect: 

According to [the Firebird docs for CREATE INDEX](https://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-ddl-idx.html)

> Index Direction
> 
> All indexes in Firebird are uni-directional.

The (single) ASCending/DESCending attribute appears at the beginning of the CREATE INDEX statement, not with the column name.

Currently

https://github.com/sqlalchemy/sqlalchemy/blob/d8ac1e9e6bfc931d2f14f9846d6924106f56b7e6/lib/sqlalchemy/testing/suite/test_reflection.py#L295

renders

```sql
CREATE INDEX noncol_idx_nopk ON noncol_idx_test_nopk (q DESC)
```

which causes Firebird to throw an error

> Error while preparing SQL statement:\n- SQLCODE: -104\n- Dynamic SQL Error\n- SQL error code = -104\n- Token unknown - line 1, column 57\n- DESC

What Firebird wants to see is

```sql
CREATE DESC INDEX noncol_idx_nopk ON noncol_idx_test_nopk (q)
```

Any ideas on how best to handle this?

**Comment by zzzeek** [comment]
to clarify, supporting FB's "DESC" keyword is a separate task from excluding the "noncol_idx" tests from the Firebird dialect.   The latter is probably the more important one.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add test requirement: indexes_with_ascdesc** https://gerrit.sqlalchemy.org/1675

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Add test requirement: indexes_with_ascdesc** https://gerrit.sqlalchemy.org/1683

**Comment by pauldex** [comment]
Firebird can create multi-column indices, but they are either ascending or descending, which is what is meant by the term 'uni-directional'.  Other database servers, such as SQL Server, allow creating multi-column indices with some columns ascending and others descending.  That is to support conditions to speed execution of queries which do things like 'name in ascending order and date in descending order'.  None of the tests using **Index("noncol_idx_nopk", noncol_idx_test_nopk.c.q.desc())** from **sqlalchemy/lib/sqlalchemy/testing/suite/test_reflection.py** test for (col1 asc, col2 desc).  If we can configure the tests to allow changing the order of the ASC/DESC to the expected place in Firebird (similar to CREATE TEMPORARY... vs CREATE GLOBAL TEMPORARY,..), all of the current tests would probably pass.  We'd need to add tests for the multi-columns indices in which some columns sort in one direction and others sort in the other direction.

**Comment by pauldex** [comment]
Obviously these new tests would be skipped by Firebird, since that kind of index is not natively supported.

**Comment by zzzeek** [comment]
we have to decide if we want to reopen this or open a new issue, or just punt for now, on supporting Firebird's special "asc/desc" behavior.   Actually since it's becoming an external dialect, the issue would be open on that side :).

**Comment by gordthompson** [comment]
> Actually since it's becoming an external dialect, the issue would be open on that side :).

Already done:

https://github.com/pauldex/sqlalchemy-firebird/issues/6
