### ISSUE TITLE
Feature request:  support `Column`s as mapping keys to `bulk_insert_mappings` et al

### ISSUE THREAD

**Issue by wadetregaskis-linkedin** [sqlalchemy/sqlalchemy#5111]
It'd be convenient to not have to write `.name` at the end of all the column names, when mostly using the SQLAlchemy ORM but sometimes dropping down to `bulk_insert_mappings` for performance, and not wanting to hard-code the column name literals at every `bulk_insert_mappings` call.

It'd also make it easier to use dataclasses and SQLAlchemy model objects, since mypy doesn't understand that a nominally 'int' column _happens_ to actually be some magic proxy which does indeed have a 'name' attribute.

**Comment by zzzeek** [comment]
hi there -

unfortunately I don't understand this request.  can you please supply an example.

also dataclasses are not supported with SQLAlchemy, for mypy support please use the [extension](https://github.com/dropbox/sqlalchemy-stubs).

**Comment by wadetregaskis-linkedin** [comment]
For example, the following will make mypy unhappy:

```
from dataclasses import dataclass
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String

Base = declarative_base()

@dataclass(order=False)
class User(Base):
    __tablename__ = 'users'
    id: int = Column(Integer, primary_key=True)
    name: str = Column(String)

…

some_session.bulk_insert_mappings(User, ({User.id.name: 5, User.name.name: 'John'},))  # Mypy complains about the `.name`.
```

At a glance it seems like that'd be the case using `sqlalchemy-stubs` even without dataclasses in the picture, since either way 'id' is typed as `int` and 'name' as `str`, neither of which have a `name` attribute.

It also reads rather weirdly to see `User.name.name`, which actually comes up fairly often in my use since `name` is indeed a pretty common column name.

Thus why I'd prefer to be able to do:

```
some_session.bulk_insert_mappings(User, ({User.id: 5, User.name: 'John'},))
```

Since SQLAlchemy would be pulling the column name from the given `Column`s, I wouldn't have to worry about confusing mypy (at least as long as `bulk_insert_mappings` doesn't have detailed type annotations to say it expects _exclusively_ `str` or `Column`, as opposed to `int` that mypy erroneously thinks `User.id` is).  Plus it just reads better.

None of this is ideal, but until Python type hinting, and mypy specifically, gain the ability to annotate a type as _both_ e.g. `str` and `Column` simultaneously, this seems to be the best workaround.

**Comment by zzzeek** [comment]
> For example, the following will make mypy unhappy:
> 
> ```
> from dataclasses import dataclass
> from sqlalchemy.ext.declarative import declarative_base
> from sqlalchemy import Column, Integer, String
> 
> Base = declarative_base()
> 
> @dataclass(order=False)
> class User(Base):
>     __tablename__ = 'users'
>     id: int = Column(Integer, primary_key=True)
>     name: str = Column(String)
> 
> …


The `@dataclass` thing is not supported with mappings right now and there are no plans for this to be a thing anytime soon.   As mentioned in my previous message, Dropbox publishes a SQLAlchemy extension for mypy, please use that.

> 
> some_session.bulk_insert_mappings(User, ({User.id.name: 5, User.name.name: 'John'},))  # Mypy complains about the `.name`.

use strings, not "User.id.name":

    bulk_insert_mappings(User, {"id": 5, "name": "John"})

> At a glance it seems like that'd be the case using `sqlalchemy-stubs` even without dataclasses in the picture, since either way 'id' is typed as `int` and 'name' as `str`, neither of which have a `name` attribute.
> 
> It also reads rather weirdly to see `User.name.name`, which actually comes up fairly often in my use since `name` is indeed a pretty common column name.
> 
> Thus why I'd prefer to be able to do:
> 
> ```
> some_session.bulk_insert_mappings(User, ({User.id: 5, User.name: 'John'},))

write a helper function for yourself:

def bulk_insert(session, cls, attrs):
    session.bulk_insert_mappings(cls, {attr.name: value for name, value in attrs.items()})

for SQLAlchemy itself, even having mypy annotations in the source is a couple of years away.   When I finally get through SQLAlchemy 1.4 and then 2.0 which will by Python 3 only and have vastly reduced the number of patterns in SQLAlchemy, then I will begin thinking of the best way for type annotations to be first class members of the SQLAlchemy library, starting by looking at what dropbox did and then seeing how it can be modernized for what the API will look like then.  Then whatever patterns seem like they should fall from that will be considered.

so for now, this is a small cosmetic issue you can work around yourself, having SQLAlchemy be fully pep-484 integrated is something that will need to be considered wholeistically, not just one little function at a time.   sorry.



> ```
> 
> Since SQLAlchemy would be pulling the column name from the given `Column`s, I wouldn't have to worry about confusing mypy (at least as long as `bulk_insert_mappings` doesn't have detailed type annotations to say it expects _exclusively_ `str` or `Column`, as opposed to `int` that mypy erroneously thinks `User.id` is). Plus it just reads better.
> 
> None of this is ideal, but until Python type hinting, and mypy specifically, gain the ability to annotate a type as _both_ e.g. `str` and `Column` simultaneously, this seems to be the best workaround.

**Comment by zzzeek** [comment]
sorry I can't attend to this however the purpose of bulk_insert_mappings() is performance; it's not feasible to be isinstance() checking every key in the dictionaries right now so it's best that you apply this conversion externally.
