### ISSUE TITLE
add py3.8, py3.9 token to setup.py

### ISSUE THREAD

**Issue by cclauss** [sqlalchemy/sqlalchemy#5113]
https://github.com/sqlalchemy/sqlalchemy/blob/master/setup.py#L161-L164

**Comment by gordthompson** [comment]
FWIW, I'm using 3.8 and it's working fine for me.

**Comment by zzzeek** [comment]
The original question seemed a bit snarky to me.  of course we support python 3.8, it's a simple oversight in the setup.py.

that said I wonder if there is some more future proof way of supporting all python 3.x that is 3.4 or higher without us having to remember to edit this each time.

**Comment by zzzeek** [comment]
doesn't seem like it: https://pypi.org/pypi?%3Aaction=list_classifiers

**Comment by cclauss** [comment]
I did not meant to be snarky...  Some project have had trouble with 3.8.

3.4 is EOL https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by zzzeek** [comment]
> I did not meant to be snarky... Some project have had trouble with 3.8.

sure we likely had some 3.8 regression or something but we are a highly active project with monthly releases so we are always targeting whatever python is in beta, currently 3.9.


> 
> 3.4 is EOL https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add py3.8, py3.9 token to setup.py** https://gerrit.sqlalchemy.org/1688

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Add py3.8, py3.9 token to setup.py** https://gerrit.sqlalchemy.org/1689
