### ISSUE TITLE
MutableList not sortable reverse or with custom key function

### ISSUE THREAD

**Issue by tinxx** [sqlalchemy/sqlalchemy#5114]
Usually Python `list`s support reversing sort direction and passing custom key functions. This function is missing when using `MutableList` wrapper.

Usage example:
```
a = [{'a': 2}, {'a': 1}, {'a': 3}]
a.sort()
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# TypeError: '<' not supported between instances of 'dict' and 'dict'
a.sort(key=lambda x: x.get('a'))
a
# [{'a': 1}, {'a': 2}, {'a': 3}]
a.sort(key=lambda x: x.get('a'), reverse=True)
a
# [{'a': 3}, {'a': 2}, {'a': 1}]
```

Edit: The problem can be solved like this:

```
-    def sort(self):
-        list.sort(self)
+    def sort(self, reverse=False, key=None):
+        list.sort(self, reverse=reverse, key=key)
         self.changed()
```

I wanted to send a pull request but don't have the time now to figure out how add a test.

**Comment by zzzeek** [comment]
the reverse() function is there for basic reversal

**Comment by zzzeek** [comment]
guess that's not the same thing.  haven't seen the "reverse" keyword arg before.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add keywords to MutableList.sort()** https://gerrit.sqlalchemy.org/1680

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Add keywords to MutableList.sort()** https://gerrit.sqlalchemy.org/1681

**Comment by tinxx** [comment]
Hi @zzzeek, thanks for the quick response! Cheers!
