### ISSUE TITLE
error compiling functions.concat for OracleDialect with multiple arguments

### ISSUE THREAD

**Issue by popokatapepel** [sqlalchemy/sqlalchemy#5118]
considering the following table definition

```
meta = MetaData()

tgd = Table('T_GROUP_DAT', meta,
            Column('C_ID'),
            Column('CLASS_CODE'))

```

I create a select-statement using the `sqlalchemy.sql.functions.concat` with 3 statements

```
tgd_q1 = select([functions.concat(tgd.c.C_ID, '-', tgd.c.CLASS_CODE)])
```

using

```
tgd_q1.compile(dialect=OracleDialect(), compile_kwargs={"literal_binds": True}))
```

the query 

```
SELECT concat("T_GROUP_DAT"."C_ID", "T_GROUP_DAT"."CLASS_CODE") AS concat_1
FROM "T_GROUP_DAT"
```

is generated. However, when I run this, the exception `ORA-00909: invalid number of arguments` is thrown. This is because CONCAT (https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions026.htm) only allows 2 Arguments.

**Comment by zzzeek** [comment]
hi there -

two-argument CONCAT form on Oracle is unfortunately one of many SQL limitations you'd find on Oracle.   Your options are to either use concat multiple times, e.g. concat(arg1, concat(arg2, arg3)), or use the concatenation operator.   You can get a working three-way concat like this, assuming C_ID is of String or similar datatype:

    tgd_q1 = select([tgd.c.C_ID + '-' + tgd.c.CLASS_CODE])

that will make use of Oracle's string concatenation operator which is the `||` symbol.

**Comment by popokatapepel** [comment]
ah ok I was acutally look for a way to generate the `||` symbol after compilation. 
thanks alot
