### ISSUE TITLE
Querying single-inh subclass while selecting entities from union CompoundSelect incorrectly (?) applies filter

### ISSUE THREAD

**Issue by HeyBillFinn** [sqlalchemy/sqlalchemy#5122]
When constructing a union query that includes a subclass that is polymorphically mapped, querying the subclass applies a filter by type in the outer select statement, causing other members of the union query to be omitted from the result.

This behavior goes back to at least 1.0.0, so it may be as intended, and it may not be worth fixing.

Reproduction steps:

``` python
from sqlalchemy import (
    Column,
    Integer,
    MetaData,
    String,
    create_engine,
    null,
    union_all,
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Query, Session

Base = declarative_base()


class Foo(Base):
    __tablename__ = "foos"
    __mapper_args__ = {"polymorphic_on": "type"}

    id = Column(Integer, primary_key=True)
    type = Column(String, nullable=False)


class SubFooA(Foo):
    __mapper_args__ = {"polymorphic_identity": "SUBA"}


class SubFooB(Foo):
    __mapper_args__ = {"polymorphic_identity": "SUBB"}


class Bar(Base):
    __tablename__ = "bars"

    id = Column(Integer, primary_key=True)
    baz = Column(Integer, nullable=False)


engine = create_engine("sqlite://")
metadata = MetaData()
with engine.begin() as connection:
    metadata = Base.metadata
    metadata.create_all(connection)

session = Session(bind=engine)

new_bar = Bar(baz=5)
session.add(new_bar)
session.commit()

# Union based on queries
query = session.query(Bar).union(session.query(SubFooA))
assert len(query.all()) == 1

# Union based on `CompoundSelect` using base class
bar_query = Query([Bar, null().label("foos_id"), null().label("foos_type")])
foo_query = Query(
    [null().label("bars_id"), null().label("bars_baz"), Foo]
).filter(Foo.type == "SUBA")
full_union = union_all(bar_query, foo_query)
query = session.query(Bar, Foo).select_entity_from(full_union)
assert len(query.all()) == 1, str(query)

# Union based on `CompoundSelect` parent query using base class
bar_query = Query([Bar, null().label("foos_id"), null().label("foos_type")])
subfoo_query = Query(
    [null().label("bars_id"), null().label("bars_baz"), SubFooA]
)
full_union = union_all(bar_query, subfoo_query)
query = session.query(Bar, Foo).select_entity_from(full_union)
assert len(query.all()) == 1, str(query)

# Union based on `CompoundSelect` using subclass
bar_query = Query([Bar, null().label("foos_id"), null().label("foos_type")])
subfoo_query = Query(
    [null().label("bars_id"), null().label("bars_baz"), SubFooA]
)
full_union = union_all(bar_query, subfoo_query)
query = session.query(Bar, SubFooA).select_entity_from(full_union)
# XXX: Assertion fails due to `WHERE anon_1.foos_type IN (?)` clause in outermost query
assert len(query.all()) == 1, str(query)
```

**Comment by zzzeek** [comment]
hi -

I'm not able to take this all in right now, however note that query.count() creates a subquery of its own and confuses things quite a bit.  is this symptom local to the use of query.count()?

**Comment by HeyBillFinn** [comment]
> I'm not able to take this all in right now, however note that query.count() creates a subquery of its own and confuses things quite a bit. is this symptom local to the use of query.count()?

No, it's not local to `.count()`. I've updated the sample to use `len(query.all())`, and the test fails in the same manner.

**Comment by zzzeek** [comment]
that single-inh logic thing is very difficult to get right.   it has been changed many times to accommodate more of these weird scenarios.

um but I'm not sure what this means:

    query = session.query(Bar, SubFooA).select_entity_from(full_union)

that's not really a thing.  select_entity_from() is sort of intended to work with just a single entity, were you hoping it selects them both from that ?    there's not really a capability to do that right now even without all the unions and such.

**Comment by zzzeek** [comment]
I guess it is supposed to do that, e.g. match all the "corresponding" entities.    But looking at what you're doing above that's extremely ambitious and perhaps there's a more direct way of doing what you need.

**Comment by zzzeek** [comment]
well, if we just turn off that single crit then it works, so, that's fairly amazing

    query = session.query(Bar, SubFooA).select_entity_from(full_union)._set_enable_single_crit(False)


that setting happens naturally when you do something like "from_self()".  I'm not really sure what cue we could rely upon here to know that the "single crit" has been set on the inside already,however.

**Comment by zzzeek** [comment]
well I can make a change that will allow this to "work", at the price of making other kinds of queries require more manual intervention (meaning, they'd start raising an error until corrected), but im having a hard time coming up with a use case that is less strange than the one you have here, so as of yet I'm not really sure what to do on this.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Propose Query.select_from_etc() must do its own single inh filtering** https://gerrit.sqlalchemy.org/1694

**Comment by zzzeek** [comment]
that's the patch but I'm not really sure about it.

**Comment by HeyBillFinn** [comment]
Yeah, I'm also not sure if covering this case is worth the added complexity. FWIW, our business case is selecting entities from different tables but performing the ordering & limiting in the database. So, for example, we might have a 1:many for `Manager` to `Engineer`s and also a 1:many for `Manager` to `Pet`s. Both `Engineer`s and `Pet`s have a birth date, but the classes are not related at all. We may want to identify the 40 youngest engineers & pet dogs that `Manager` Dilbert is responsible for. So, for us, that means that we perform a similar `union_all` query as the example by constructing queries for the `engineers` and `pets` tables, filtering by manger to Dilbert. Then, we label each table's column that stores the birth date to the same alias, so we can order & limit by it across all records in the outer union `order by` clause.

**Comment by zzzeek** [comment]
I've thought of a reason why my proposed behavior, to raise if someone does select_entity_from(<Some statement>) and that statement doesn't filter correctly, is correct.   because for joined inheritance and probably concrete also, the same thing can happen.   adding a test for that now.

**Comment by zzzeek** [comment]
OK this is a good change, but it's a surprise, so I had to write a big migration notes section for it.  thanks for the heads up on this.
