### ISSUE TITLE
NullPool causes TypeError: unique_connection() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by ramprax** [sqlalchemy/sqlalchemy#5124]
TypeError: unique_connection() missing 1 required positional argument: 'self'

This error occurs on calling engine.raw_connection(), if the engine was created with pool=NullPool. Trace attached.
[null_pool_trace.txt](https://github.com/sqlalchemy/sqlalchemy/files/4127144/null_pool_trace.txt)

Please see attached script to reproduce the issue - nullpool_bug_script.txt.
[nullpool_bug_script.txt](https://github.com/sqlalchemy/sqlalchemy/files/4127087/nullpool_bug_script.txt)

Environment details:
1. SQLAlchemy==1.3.13 on Python 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0] on linux
2. SQLAlchemy==1.3.6 on Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by CaselIT** [comment]
I think you have to pass an instance of the poll. From the [documentation](https://docs.sqlalchemy.org/en/13/core/engines.html#sqlalchemy.create_engine.params.pool)
>  an already-constructed instance of Pool,

**Comment by ramprax** [comment]
Oops! My bad!

**Comment by zzzeek** [comment]
I think you wanted to use pool_class=NullPool
