### ISSUE TITLE
deprecate connection branching

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5131]
towards a more explicit usage model in 2.0, the behavior of "branched" connections is very prevalent in the connection / dialect internals and will get in the way of newer patterns.   as things like "close_with_result" etc. are going away, this feature should be removed.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Deprecate connection branching** https://gerrit.sqlalchemy.org/1703
