### ISSUE TITLE
Error in saving None for DATETIMEOFFSET from SQL Server in ORM.

### ISSUE THREAD

**Issue by ayip723** [sqlalchemy/sqlalchemy#5132]
When I save a `None` for SQL Server's `DATETIMEOFFSET` via ORM, I've got an error like this.
```
Traceback (most recent call last):
  File "/pyenv/versions/seismic-sync/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1173, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/pyenv/versions/seismic-sync/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 808, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "/pyenv/versions/seismic-sync/lib/python3.8/site-packages/sqlalchemy/dialects/mssql/pyodbc.py", line 238, in process
    dto_string = value.strftime("%Y-%m-%d %H:%M:%S.%f %z")
AttributeError: 'str' object has no attribute 'strftime'
```

**Comment by zzzeek** [comment]
continuing from this feature in #4983  #5045, type handlers need to accommodate the None value

**Comment by zzzeek** [comment]
@gordthompson can you add this one in?  let me know or I'll do it if you don't have time.   propose for master and I can backport for 1.3 if you'd like

**Comment by gordthompson** [comment]
I'll have a look.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix handling of None as parameter for a datetimeoffset column** https://gerrit.sqlalchemy.org/1706

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix handling of None as parameter for a datetimeoffset column** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1718
