### ISSUE TITLE
mssql - query statement error

### ISSUE THREAD

**Issue by umbrella2n2** [sqlalchemy/sqlalchemy#5136]
"mssql" adds extra brackets and a dot (.) to field names, which causes error in querying.
Need to change brackets to empty spaces and dots to underscores.

...\Python38\Lib\site-packages\sqlalchemy\dialects\mssql
base.py

class MSIdentifierPreparer(compiler.IdentifierPreparer):
    reserved_words = RESERVED_WORDS
    def __init__(self, dialect):
        super(MSIdentifierPreparer, self).__init__(
            dialect,
            #initial_quote="[",
            #final_quote="]",
            initial_quote="",
            final_quote="",
            quote_case_sensitive_collations=False,
        )
    def _escape_identifier(self, value):
        return value

…\Python38\Lib\site-packages\sqlalchemy\sql
elements.py

def _gen_label(self, name, dedupe_on_key=True):
        t = self.table
        if self.is_literal:
            return None
        elif t is not None and t.named_with_column:
            if getattr(t, "schema", None):
                label = t.schema.replace(".", "_") + "_" + t.name + "_" + name
            else:
                #label = t.name + "_" + name
                label = t.name.replace(".", "_") + "_" + name

**Comment by zzzeek** [comment]
hi there -

The [guidelines](https://docs.sqlalchemy.org/en/13/dialects/mssql.html#multipart-schema-names) here will show you what to do if you have long multipart schema names.   If you have dots in your actual names, you need to add special brackets to indicate where quoting should or should not occur.
