### ISSUE TITLE
Support for compare safely NULL value on Mysql & MariaDB

### ISSUE THREAD

**Issue by johaven** [sqlalchemy/sqlalchemy#5137]
Hi,

**is distinct from** is not working for MySQL and MariaDB.

MySQL & MariaDB use operator **<=>** to compare safely NULL values (https://mariadb.com/kb/en/null-safe-equal/)

https://modern-sql.com/feature/is-distinct-from

In my use case, i can't get results what i want (without double comparison like this ```db.or_(File.uid == from_file.uid, db.and_(File.uid.is_(None), from_file.uid.is_(None)))```
```python
q = q.join(File, db.and_(Share.parent_id.isnot(None),
                                    File.uid.isnot_distinct_from(from_file.uid),
                                    File.sid == from_file.sid,
                                    File.path.like(from_file.path + '%')))
```
```python
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DISTINCT FROM files_3.uid AND files.sid = files_3.sid AND files.path LIKE concat' at line 14")
```

Would it be possible to implement the operator '**<=>**' as a function '**is distinct from**' ?

**Comment by zzzeek** [comment]
hi there -

I have to apologize, as I spent quite a bit of time on a response here three days ago, I definitely typed it all out, and here we see it is....not here.    So I will have to paraphrase quickly.

Need a motivated volunteer to submit a PR that will implement the following implementations from https://modern-sql.com/feature/is-distinct-from:

MySQL  / MariaDB:   <=> operator
Oracle: DECODE(A, B, 0, 1) = 0
MS SQL Server: EXISTS (SELECT c INTERSECT SELECT c2)  assuming SQL server doesn't need the VALUES part and works like this, it's not clear from the article

we also need round trip "backend" tests for this in sqlalchemy/testing/suite/test_select.py.

**Comment by zzzeek** [comment]
the backend tests need to assert that both "is_distinct_from()" and "isnot_distinct_from()" correctly filter existing rows.     I can perhaps merge just the test for now and support it for PG / SQLite.

**Comment by gordthompson** [comment]
I'll take a crack at this.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Broaden is[not]_distinct_from support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1835

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Broaden is[not]_distinct_from support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1843

**Comment by johaven** [comment]
Thank you !!! :)
