### ISSUE TITLE
support upsert in sqlite dialect

### ISSUE THREAD

**Issue by honglei** [sqlalchemy/sqlalchemy#5140]
UPSERT syntax was added to SQLite with version 3.24.0 (2018-06-04).
[https://www.sqlite.org/draft/lang_UPSERT.html](https://www.sqlite.org/draft/lang_UPSERT.html)

[SQLite - UPSERT *not* INSERT or [REPLACE]](https://stackoverflow.com/questions/418898/sqlite-upsert-not-insert-or-replace)

**Comment by zzzeek** [comment]
hi there -

this is already tracked in #4010.    this can be in any current release if contributors are available to produce pull requests with complete tests.
