### ISSUE TITLE
support customizable __module__ or namespace in automap

### ISSUE THREAD

**Issue by matthewgdv** [sqlalchemy/sqlalchemy#5145]
I've just encountered this issue and after a few hours spent investigating I'm think I know what's going on.

But first, some context:

Let's say in my database I've got the following two tables:

1) base.customer
2) report.customer

I need to automap them both and, **crucially, I want both classes to just be called 'customer'**.

I don't want to have to convert them to a python identifier using custom logic passed to the `AutomapBase.prepare(classname_for_table=)` argument. For example, the seemingly obvious solution would be to replace the dot with an underscore and name them `base_customer`, and `report_customer` respectively, to make them valid python identifiers. But this is inelegant, and there will always be ambiguity.

What if I have a schema called `customer_view` with a table called `customer`, and another schema called `customer` with a table called `view_customer`? Both classes then get mapped as `customer_view_customer`. Maybe not the best example, but it should showcase the issue.

You can spend forever coming up with ways to try to avoid this (maybe use 2 underscores instead of 1), and you still won't guarantee it works in every situation (some database schemas use double underscores in their object names as well to represent m2m relationships).

And it will just make everything more needlessly complicated. If you do this you now have to change the `AutomapBase.prepare(name_for_scalar_relationship=, name_for_collection_relationship=)` arguments so that you can still reference relationships nicely: for example: `customer1.email_address_collection` rather than `customer.base_email_address_collection`, and `some_email.customer` rather than `some_email.base_customer`.

The more elegant and idiomatic way to handle this seems to me to separate out the namespaces of schemas, to then allow duplication of names across different namespaces. As the Zen of Python states: "Namespaces are one honking great idea -- let's do more of those!"

So what I've done is I've created a new `AutomapBase` for every schema in my database in a loop, and called `AutomapBase.prepare(schema=)` individually for each, passing the specific schema to each one. I've also used the `AutomapBase.prepare(classname_for_table=)` argument to ensure that the schema name is not included in the name of the newly mapped class.

Now I can assign my `base_automap.classes` as `base`, my `report_automap.classes` as `report`, and then simply reference my classes as `base.customer` and `report.customer`, and it's so clean!

The part that gets me is that this ALMOST works. In fact, it works like a dream so long as there are no tables across the whole database that have duplicate names.

However, as soon as there are duplicates, the root `_ModuleMarker` (the one referenced as `_sa_module_registry` within each base's `_decl_class_registry`), through the `_ModuleMarker` of whichever module your `AutomapBase` was declared in (I think it's `sqlalchemy.ext.automap` unless you use a custom base), now has a `_MultipleClassMarker` against that table name in its `_ModuleMarker.contents` attribute, which will kill the old weakref as soon as a duplicate table name comes along.

And without this weakref being alive, several downstream parts of the automapping machinery (such as the `_relationships_for_fks()` method) just fail gracelessly, because they rely on this weakref being alive to work.

While googling around for this before posting this issue I've found this StackOverflow question (https://stackoverflow.com/questions/57118047/typeerror-issubclass-arg-2-must-be-a-class-or-tuple-of-classes) which I believe stems from the same cause. While I can't be 100% certain, the poster of this question probably had a schema change be made to his/her database that caused there to be multiple tables with the same name across different schemas, so their automapping broke.

This error is basically the same one I've been getting. The weakref-invoking property `_DeferredMapperConfig.cls` returns `None` from its dead weakref, which then causes an `issubclass()` check to receive `None` as its second argument, rather than a type. Many other methods called downstream of `AutomapBase.prepare()` also fail in similar ways due to the unexpected presence of `None`, rather than a base.

And the part that's kind of hilarious is that just as the poster in that StackOverflow issue mentioned, sometimes it just randomly works! This does actually make sense, since Python makes no guarantees about when it garbage-collects unreferenced objects. So if you get lucky your reference might still be alive by the time the flow of execution gets to that point. Will it work? Won't it? Who knows! :)

I'm wondering if we can get a patch in to the way `_MultipleClassMarker` works, so that it can keep track of multiple database objects with identical name stems (the part of the object name after the schema) simultaneously in a schema-aware manner?

If that's too much effort then at minimum a small change keeping the weakrefs cached in this situation rather than killing them off should be a decent compromise, since it will mean the automapper can still finish doing its job, and the only additional memory costs incurred will be for tables with duplicate names, which should hopefully not be too many.

In the long-term I think it would be preferable to add in better multi-schema support to `AutomapBase.prepare()` just in general, but that's a much bigger job. It's kind of silly that in order to namespace my automapped classes the same way we namespace our objects everywhere else in both Python and SQL, we need to use duplicate `AutomapBase` objects as a hacky workaround.

Sorry for this wall of text, this really got away from me a bit.

I'd be crazy grateful if this could be considered.

Thanks for your time.

**Comment by zzzeek** [comment]
hi there -

I'm not too big on "wall of text" reports like this one ( :) ) however if I just look at the top level use case, you just want to set `__module__` on your class.  There's no hook for that so the below test case illustrates how to do this all right now and also proposes two new API features for automap, which would be dependent that you can confirm the below recipe does everything you need.
```

from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import util
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.ext.declarative import DeclarativeMeta
from sqlalchemy.orm import Session

e = create_engine("sqlite://", echo=True)
with e.connect() as conn:
    conn.execute("create table base_customer (id integer primary key)")
    conn.execute("create table report_customer (id integer primary key)")

# optional step 1.  use a custom metaclass to set the desired
# __module__ on the class, so that declarative does not see any
# conflict.   This isn't technically necessary for the program to
# succeed but will eliminate that warning.
#
# Right now, declarative is hardcoded to look at cls.__module__ for this
# step right up front.  The two ways this could be customizable without
# a custom metaclass would be:
#
# 1. have declarative support some special attribute like
# cls.__declare_class_namespace__ that would supersede the use of
# __module__ if present.
#
# 2. add an option to automap such that it will add your choice of
# __module__ to the class dictionary, which seems to work.  I'd lean
# towards this, since it can also be integrated with step 2 below.
# I'd just use modulename_for_table().  while it might be nice if
# classname_for_table could return a tuple, I'd rather not have it be
# implicit that this is actually the __module__ and not some other kind
# of registry attribute.
#
class NameSetupMeta(DeclarativeMeta):
    def __init__(cls, classname, bases, dict_):
        if "__table__" in dict_:
            tablename = cls.__table__.name
            pseudo_schema, name = tablename.split("_")
            cls.__module__ = pseudo_schema

        DeclarativeMeta.__init__(cls, classname, bases, dict_)


Base = automap_base(metaclass=NameSetupMeta)

# optional step 2.   add the classes to Base.classes yourself.
# also something automap could support pretty easily, if there is a custom
# "__module__" set up by the above step 1 hook, then use this scheme for
# Base.classes also.
@event.listens_for(Base, "class_instrument", propagate=True)
def cls_instrment(klass):
    tablename = klass.__table__.name
    pseudo_schema, name = tablename.split("_")

    if pseudo_schema not in Base.classes:
        Base.classes[pseudo_schema] = util.Properties({})
    Base.classes[pseudo_schema][name] = klass


def my_classname(base, tablename, table):
    pseudo_schema, name = tablename.split("_")
    return name


# reflect the tables
Base.prepare(e, reflect=True, classname_for_table=my_classname)


s = Session()
q = s.query(Base.classes.report.customer, Base.classes.base.customer)
print(q)

```

**Comment by matthewgdv** [comment]
Thanks @zzzeek!

I've had a play around with your solution and it looks really promising, but there are still some errors that are happening when doing it this way.

First off, I've just modified the metaclass initializer, the listener, and the classname callback for use with actual database schemas (you couldn't show that off with sqlite since it doesn't support schemas). All together, I've run it like this:

```
from sqlalchemy import create_engine
from sqlalchemy import MetaData
from sqlalchemy import event
from sqlalchemy import util
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.ext.declarative import DeclarativeMeta

import config

engine = create_engine(config.connection_string)
meta = MetaData(bind=engine)

meta.reflect(schema="base")
meta.reflect(schema="report")


class NameSetupMeta(DeclarativeMeta):
    def __init__(cls, classname, bases, dict_):
        if "__table__" in dict_:
            schema = cls.__table__.schema
            cls.__module__ = schema if schema is not None else cls.__module__

        DeclarativeMeta.__init__(cls, classname, bases, dict_)

# I wanted to use an empty string here if the schema is None, but then the 
# class name starts with a dot, which looked strange (e.g. .company). If you 
# leave it as None you get errors later on when sqlalchemy calls string methods on it.
# Maybe changes to the module name parsing could be made to handle None?


Base = automap_base(bind=engine, metadata=meta, metaclass=NameSetupMeta)


@event.listens_for(Base, "class_instrument", propagate=True)
def cls_instrument(cls):
    table = cls.__table__
    name, schema = table.name, table.schema

    if schema is None and Base.metadata.bind is not None:
        schema = Base.metadata.bind.dialect.default_schema_name

    if schema is not None:
        if schema not in Base.classes:
            Base.classes[schema] = util.Properties({})
        Base.classes[schema][name] = cls
    else:
        # can probably just omit this else block, since this should happen elsewhere anyway
        Base.classes[name] = cls


# I've just modified this to support named default schemas ('dbo' in sql server,
# 'public' in postgres, etc.)

# The listener here does its job in addition to the already existing machinery,
# which means you'll still get all the classes placed into Base.classes as normal,
# in addition to the extra namespacing. This isn't necessarily a problem,
# unless it's undesirable for some reason I'm unaware of. Just thought I'd flag it.


def my_classname(base, tablename, table):
    return tablename


Base.prepare(classname_for_table=my_classname)
```

The fun bit is that depending on how Python happens to be feeling at any particular moment, the last statement (the `Base.prepare()` call) will result in one of 3 outcomes:
1) It succeeds (rarely)
2) This error: (often)
[error1.txt](https://github.com/sqlalchemy/sqlalchemy/files/4185915/error1.txt)
3) This error: (very rarely)
[error2.txt](https://github.com/sqlalchemy/sqlalchemy/files/4185916/error2.txt)

So there's still something fishy happening with the dereferencing.

Crucially, this **only happens** when I reflect 2 or more schemas which have objects with name collisions.

If I replace:
```python
meta.reflect(schema="base")
meta.reflect(schema="report")
```
with
```python
meta.reflect(schema="base")
meta.reflect(schema="log")
```
then everything works 100% of the time. This is because in my database, the `base` and `log` schemas have no overlapping object names, whereas the `base` and `report` schemas do. I've tested this with some other schemas as well and can confirm this is the determining factor.

If this could be solved then this would be a pretty perfect fix! I particularly love the idea of a new `modulename_for_table()` hook, so that a user wouldn't have to subclass `DeclarativeMeta` just for this.

**Comment by zzzeek** [comment]
so these classes can only be GC'ed if there are no strong references to them anywhere.   the trace shows that this dereferencing is happening before the class is mapped, so it happens before cls_instrument happens.

the proposal I have to allow automap to place classes into a namespaced registry immediately should fix this.  however, you can also fix this as follows:

```

do_not_go_away = set()


class NameSetupMeta(DeclarativeMeta):
    def __init__(cls, classname, bases, dict_):
        if "__table__" in dict_:
            schema = cls.__table__.schema
            cls.__module__ = schema if schema is not None else cls.__module__
        do_not_go_away.add(cls)
        DeclarativeMeta.__init__(cls, classname, bases, dict_)

```

the GC of the classes should be able to be seen with the following patch:

```
diff --git a/lib/sqlalchemy/ext/declarative/base.py b/lib/sqlalchemy/ext/declarative/base.py
index d76e4ab70..16829e5d1 100644
--- a/lib/sqlalchemy/ext/declarative/base.py
+++ b/lib/sqlalchemy/ext/declarative/base.py
@@ -711,11 +711,13 @@ class _DeferredMapperConfig(_MapperConfig):
 
     @cls.setter
     def cls(self, class_):
+        self.class_name = class_
         self._cls = weakref.ref(class_, self._remove_config_cls)
         self._configs[self._cls] = self
 
     @classmethod
     def _remove_config_cls(cls, ref):
+        print("CLASS %s WAS DEREFERENCED!!!! " % self.class_name)
         cls._configs.pop(ref, None)
 
     @classmethod

```

we're going to assume the second error is a variant of the first for now.

**Comment by matthewgdv** [comment]
Awesome, I can confirm this works. 👍 

Thanks so much for your extremely quick and throrough response on this!

Just a few final thoughts if some of this stuff does become new API components for automap.

1) If you go the route of a `AutomapBase.prepare(modulename_for_table=)` argument:
Should the callback passed to this argument return an empty string or `None`, the downstream stringparsing logic should handle it without crashing and strip away the leading dot from the fully qualified class name, leaving just the `classname_for_table` portion.

2) The use-case of preparing schema-namespaced database objects is in my opinion common enough to warrant some helper method or boolean argument switch for casual users. I'm happy to use the event listener solution you've supplied, but this requires a pretty intimate understanding of `sqlalchemy` that many users likely won't have.

Again though, thanks a ton, both for this and your work on `sqlalchemy` in general. It's such an amazing project!

**Comment by zzzeek** [comment]
in point number two are you advocating for a general Declarative feature that allows for some attribute other than `__module__` to be used as the namespace, independently of whether automap were used ?

**Comment by matthewgdv** [comment]
Hey again @zzzeek!

I have actually wondered a few times why specifying a database schema declaratively has to be done by passing the schema through as:

```python
class SomeModel(Base)
    __table_args__ = dict(schema="some_schema")
```
rather than:
```python
class SomeModel(Base)
    __schema__ = "some_schema"
```
But I always figured it was due to some principle of separation-of-concerns between the core and the ORM that I'm not quite well enough versed in `sqlalchemy` to understand, or some other reason I haven't thought of.

I wasn't really even thinking about that with my earlier suggestion though, since I don't know how feasable that is. It would be also be a bigger change affecting more moving parts of the ORM. I think I would love something like this though, if you do actually think it's a genuinely a good idea.

That said, I was thinking about smaller-scale changes. Something more along the lines of, for example, a default `False` boolean argument like: `AutomapBase.prepare(partition_by_module=)`, being introduced alongside `modulename_for_table`, which basically does the same thing the `class_instrument` listener above does.

**Comment by zzzeek** [comment]
well `__schema__` is kind of a generic word that may very well be in use by other systems but overall there are many optional arguments that `Table` accepts and for declarative they are all in one place, `__table_args__`.

you can of course make your own base class that applies `__schema__` to `__table_args__` automatically

```
class Foo(Base):
    @declared_attr
    def __table_args__(cls):
       # apply conditionals etc as appropriate
       return {"schema":cls.__schema__}

Base = declarative_base(cls=Foo)

```

> That said, I was thinking about smaller-scale changes. Something more along the lines of, for example, a default False boolean argument like: AutomapBase.prepare(partition_by_module=), being introduced alongside modulename_for_table, which basically does the same thing the class_instrument listener above does.

I was going to make modulename_for_table do both things.

**Comment by matthewgdv** [comment]
Yeah, what you said regarding `__schema__` makes sense.  I can't really think of any other proxies for `__module__` that would fit, so probably best to stick with it!

And yeah, keeping it as a single argument that triggers the namespacing behaviour sounds good! Less clutter in the call signature, and I can't really see a use-case where you'd want to provide `modulename_for_table`, but would still want a flat namespace returned. I love it. :)

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add hooks/docs for automap w/ multiple schemas** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4384
