### ISSUE TITLE
Table comments not reflected with Oracle database

### ISSUE THREAD

**Issue by dhirschfeld** [sqlalchemy/sqlalchemy#5146]
`sqlalchemy` is failing to reflect table comments from an Oracle database:
```python
In [52]: insp = Inspector.from_engine(engine)

In [53]: insp.get_table_comment('BIDDAYOFFER', 'INFOSERVER')
2020-02-11 14:32:54,051 INFO sqlalchemy.engine.base.Engine 
            SELECT comments
            FROM user_tab_comments
            WHERE table_name = :table_name
        
2020-02-11 14:32:54,052 INFO sqlalchemy.engine.base.Engine {'table_name': 'BIDDAYOFFER'}
Out[53]: {'text': None}
```

Digging about a bit and the comment is actually in the `ALL_TAB_COMMENTS` table:

![image](https://user-images.githubusercontent.com/881019/74211435-aa7ba480-4cdb-11ea-8a24-e608a868347c.png)

From [the Oracle docs](https://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_2095.htm#REFRN20278) 

> *`ALL_TAB_COMMENTS` displays comments on the tables and views **accessible** to the current user*

...whereas:

> *`USER_TAB_COMMENTS ` displays comments on the tables and views **owned** by the current user*

It seems unnecessarily restrictive to only reflect comments on tables ***owned*** by the current user?

**Comment by zzzeek** [comment]
thanks for the PR!  I added some short guidance.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Reflect comments from any table accessible by the current user** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1776

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Reflect comments from any table accessible by the current user** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1776

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Reflect comments from any table accessible by the current user** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1777

**Comment by zzzeek** [comment]
this is not working correctly.  we changed the query to use all_tab_comments but we aren't qualifying the table name with the owner.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Include schema in all_tab_comments query** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1791

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Include schema in all_tab_comments query** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1792

**Comment by dhirschfeld** [comment]
> *this is not working correctly. we changed the query to use all_tab_comments but we aren't qualifying the table name with the owner.*

Right, that would makes sense. Thanks for catching/fixing that @zzzeek!

**Comment by zzzeek** [comment]
well the alembic builds are failing on it because they reflect the same table name from multiple schemas simultaneously.

**Comment by CaselIT** [comment]
I guess a job that tests alembic in the sqlachemy jenkins could be useful?

**Comment by zzzeek** [comment]
yeah we need that pretty badly.    it doesn't have to be a matrix job though; alembic's test suite does all the backends in one go.   we can make it just for py37 and that's it.   we would need a script that does the thing where it looks at the GERRIT variables to get the correct SQLAlchemy version into a local virtual environment.  the openstack.sh script is a much more complicated example of this.
