### ISSUE TITLE
schema_translate_map does not work for Postgresql native enum within the CREATE TABLE

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5158]
While CREATE TYPE takes advantage of schema_translate_map, the use of the enum in the table does not:

```
from sqlalchemy import create_engine
from sqlalchemy import *

metadata = MetaData()

t = Table(
    "table1",
    metadata,
    Column("id", Integer(), nullable=False),
    Column("type1", Enum("One", "Two", name="enum1", schema="X"), nullable=True),
    PrimaryKeyConstraint("id"),
    schema="X"
)


e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)

with e.connect() as conn:
    trans = conn.begin()
    conn = conn.execution_options(schema_translate_map={"X": "test_schema"})
    t.create(conn)


    trans.rollback()

```

output, enum is created correctly but not referenced in the table correctly:

```
CREATE TYPE test_schema.enum1 AS ENUM ('One', 'Two')
2020-02-17 15:02:27,535 INFO sqlalchemy.engine.base.Engine {}
2020-02-17 15:02:27,536 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE test_schema.table1 (
	id SERIAL NOT NULL, 
	type1 "X".enum1, 
	PRIMARY KEY (id)
)

```

**Comment by zzzeek** [comment]
same issue if the translate source is "None".

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Pass DDLCompiler IdentifierPreparer to visit_ENUM** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1726

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Pass DDLCompiler IdentifierPreparer to visit_ENUM** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1727
