### ISSUE TITLE
query.update() / query.delete() need to generate ORM DML; work in ORM steps to session.execute()

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5160]
dependent on #5159

**Comment by zzzeek** [comment]
by ORM steps we mean the sychronize_session stuff.  this is likely dependent on the new execution model not really sure how to order these things

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Convert bulk update/delete to new execution model** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2027
