### ISSUE TITLE
pymysql error 1193 Unknown system variable tx_isolation

### ISSUE THREAD

**Issue by ifuchs** [sqlalchemy/sqlalchemy#5161]
I just upgraded MySQL to the current version 8 (from a very old version) and now I find that I am getting an error on engine.connect of the form (pymysql.err.internalError) (1193, Unknown system variable' tx_isolation). I am running sqlalchemy v 13.13 and pymysql v 0.9.3.

**Comment by zzzeek** [comment]
hi there -

something about your MySQL server is not sending out a version detection string that is expected.  Can you go to your MySQL console and send the results of:

"SELECT VERSION()"

example:

```
Server version: 8.0.16 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> SELECT VERSION();
+-----------+
| VERSION() |
+-----------+
| 8.0.16    |
+-----------+
1 row in set (0.006 sec)

```

**Comment by zzzeek** [comment]
also please indicate if you are using any kind of high level proxy servers like ProxySQL or MaxScale.

**Comment by ifuchs** [comment]
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.19    |
+-----------+
1 row in set (0.00 sec)

I am not running any proxy servers.

**Comment by ifuchs** [comment]
Not sure how or why, but it is now working.

**Comment by zzzeek** [comment]
yes I have a feeling you were running an old SQLAlchemy somehwere.   do you have a stack trace from the error scenario?

**Comment by zzzeek** [comment]
no issue here

**Comment by Skyler1017** [comment]
same issue here...
I am using mysql 5.6.28

**Comment by Skyler1017** [comment]
upgrade sqlalchemy and the  problem is solved!
1.1.0 -> 1.3.18

hope this helps.
