### ISSUE TITLE
subqueryload - unnecessary order by on loading 

### ISSUE THREAD

**Issue by omris94** [sqlalchemy/sqlalchemy#5162]
I have noticed that when i use subqueryload in order to load a relationship of a table, the emitted eager-load query is ordered by the parent query's primary key (or the parent query's order, which was the same in my case).  I commented out the order by in strategies.py:1142 and noticed the performance difference.
Do you think that we really need that order by?
 
tnx :-)

**Comment by zzzeek** [comment]
yes we need the order by because it allows SQLAlchemy to consume the rows straight into a dictionary using itertools.group_by() rather than having to hash for every row.  primary keys are indexed so ORDER BY is very fast..... .

unless

you are using MySQL.   

Are you using MySQL?   if so, use selectinload().   it will also ORDER BY but there's no subquery and usually not even a JOIN and I'm pretty sure your performance issues will vanish.

If you're not using MySQL, you should use selectinload() anyway.  subqueryload() would never have been written if I came up with selectinload() first.

**Comment by zzzeek** [comment]
I am curious if the ORDER BY is what acatually causes the issue with MySQL query plans here.    if you can share the details requested that would be handy.

**Comment by zzzeek** [comment]
I remain curious here as to the specific query plans but I don't have the resources to dig into this further without help.

**Comment by omris94** [comment]
First of all, thank you for the concern and sorry for my late response (I had an exam to study for..)

We are using postgresql and the data is a multi-sites aggregated data set, therefore we use composite PKs (`id, site_id`) and multi-column foreign keys (`site_id, other_table_id`).

Our case looks similar to this one (will help you understand the next paragraph):
`session.query(Table).filter(filters_on_table).options(subqueryload(Table.one_to_many_relation_to_other_table)).order_by(Table.id, Table.site_id)`

After reading your comment, we checked and you were right about the ״order by״ index use. I ran a few `EXPLAIN ANALYZE`s and saw that the query emitted by the `subqueryload` is not using an index. I checked and saw that my subquery is ordered by the FK `SELECT ... FROM other_table ... ORDER BY table_id, site_id` while indexing “other_table” by `site_id, table_id` which makes it impossible to use (in this case). I took a quick look at my other tables and saw that it might happen in a few other ones as well :-)

About the `SELECTINLOAD`, I have checked and it wasn’t quicker then the subqueryload (at least from the SQL perspective, for 20K-150K rows).

Thanks a lot for your help!

**Comment by zzzeek** [comment]
OK so, the ORDER BY that is used by both of these systems is used so that the in-python collation can be fast.   but if it's killing a Postgresql query plan that's a bigger problem, can you please share example tables + query ?

**Comment by zzzeek** [comment]
selectinload is often ordering by the foreign key columns on the related table, so thosea re not even primary key cols.  foreign key cols should be indexed also, however as both of these loads are often combining these columns with the ORDER BY that's already set on the relationship, it is certainly a whole subject area as to when different optimizers may or may not decide to use indexes.   the python-side change to the groupby collation is relatively minor, it can increase callcounts in that it now might call list.extend() many times vs. creating a single list in place, but that's likely not as expensive as a table scan on the server side.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove ORDER BY pk from subqueryload, selectinload** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1826

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Remove ORDER BY pk from subqueryload, selectinload** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1827
