### ISSUE TITLE
implement autocommit isolation level for pysqlite

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5164]
sqlite: connection.isolation_level=None    https://docs.python.org/2/library/sqlite3.html#sqlite3.Connection.isolation_level

cx_oracle: connection.autocommit=False https://cx-oracle.readthedocs.io/en/latest/user_guide/txn_management.html#autocommitting

the tests are already in place, need to add set_isolation_level methods similar to https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/connectors/pyodbc.py#L153 then add to enabled reqs at https://github.com/sqlalchemy/sqlalchemy/blob/master/test/requirements.py#L341

**Comment by gordthompson** [comment]
The expected values for SQLite

https://github.com/sqlalchemy/sqlalchemy/blob/1e126829d594aa9f525c41942b2729bae9378fcd/lib/sqlalchemy/dialects/sqlite/base.py#L1535

don't seem to match up with the values mentioned in the [sqlite3 docs](https://docs.python.org/2/library/sqlite3.html#sqlite3.Connection.isolation_level). Also, the current method for setting the isolation level uses

https://github.com/sqlalchemy/sqlalchemy/blob/1e126829d594aa9f525c41942b2729bae9378fcd/lib/sqlalchemy/dialects/sqlite/base.py#L1547

instead of setting `connection.isolation_level`. Is it just a case of the current SQLite dialect code needing to be updated to the new way of doing things?

**Comment by gordthompson** [comment]
Starting with SQLite, my first try was

```patch
Index: lib/sqlalchemy/dialects/sqlite/base.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/sqlalchemy/dialects/sqlite/base.py	(revision 1e126829d594aa9f525c41942b2729bae9378fcd)
+++ lib/sqlalchemy/dialects/sqlite/base.py	(date 1582326387146)
@@ -1532,7 +1532,7 @@
                 14,
             )
 
-    _isolation_lookup = {"READ UNCOMMITTED": 1, "SERIALIZABLE": 0}
+    _isolation_lookup = {"AUTOCOMMIT": None, "READ UNCOMMITTED": 1, "SERIALIZABLE": 0}
 
     def set_isolation_level(self, connection, level):
         try:
@@ -1543,9 +1543,12 @@
                 "Valid isolation levels for %s are %s"
                 % (level, self.name, ", ".join(self._isolation_lookup))
             )
-        cursor = connection.cursor()
-        cursor.execute("PRAGMA read_uncommitted = %d" % isolation_level)
-        cursor.close()
+        if isolation_level is None:
+            connection.isolation_level = None
+        else:
+            cursor = connection.cursor()
+            cursor.execute("PRAGMA read_uncommitted = %d" % isolation_level)
+            cursor.close()
 
     def get_isolation_level(self, connection):
         cursor = connection.cursor()
```

`test_autocommit_off` passed, but `test_autocommit_on` failed with

```
Traceback (most recent call last):
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\testing\suite\test_dialect.py", line 117, in test_autocommit_on
    self._test_conn_autocommits(c2, True)
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\testing\suite\test_dialect.py", line 109, in _test_conn_autocommits
    1 if autocommit else None,
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\testing\assertions.py", line 195, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: None != 1
assert None == 1
  -None
  +1
```

Since it looked like the `connection.isolation_level = None` didn't "take", and knowing that `connection` was a SQLAlchemy wrapper around the actual `sqlite3` connection object, I also tried

```python
            connection.connection.isolation_level = None
```

to try and apply the change to the underlying DBAPI connection object. Unfortunately, that failed for a different reason:

```
Traceback (most recent call last):
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\base.py", line 1264, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\default.py", line 573, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: some_table

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\testing\suite\test_dialect.py", line 119, in test_autocommit_on
    self._test_conn_autocommits(conn, False)
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\testing\suite\test_dialect.py", line 103, in _test_conn_autocommits
    self.tables.some_table.insert(), {"id": 1, "data": "some data"}
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\base.py", line 986, in execute
    return meth(self, multiparams, params)
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\sql\elements.py", line 281, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\base.py", line 1108, in _execute_clauseelement
    distilled_params,
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\base.py", line 1268, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\base.py", line 1494, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\util\compat.py", line 412, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\util\compat.py", line 155, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\base.py", line 1264, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\Gord\git\sqla-gerrit\test\..\lib\sqlalchemy\engine\default.py", line 573, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: some_table
[SQL: INSERT INTO some_table (id, data) VALUES (?, ?)]
[parameters: (1, 'some data')]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

I'm wondering if this might be a quirk of SQLite connections.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add AUTOCOMMIT support for cx_Oracle and SQLite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1734

**Comment by gordthompson** [comment]
So yeah, it's something weird with SQLite. This test fails for SQLite but not for Oracle (or anybody else, AFAIK):

https://github.com/sqlalchemy/sqlalchemy/blob/f559f378c47811b5528ad1769cb86925e85fd1e5/lib/sqlalchemy/testing/suite/test_dialect.py#L114-L119

The `conn.invalidate()` makes the "some_table" table go away.

**Comment by zzzeek** [comment]
yeah, this is all part of pysqlite's broken DDL / transaction support.   There's a note at https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#transactional-ddl regarding this.  for this table to show up in the connection, some manual steps are currently needed for pysqlite to do the right thing.  the recipe at https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#serializable-isolation-savepoints-transactional-ddl shows how this works for users.  For SQLite, we may have to emit "COMMIT" or something when we change this isolation level, not sure yet.

**Comment by zzzeek** [comment]
also the python bug tracker reports linked from that second document are a good read.

https://bugs.python.org/issue9924

https://bugs.python.org/issue10740

**Comment by gordthompson** [comment]
Aha. I was curious if the issue might be related to using an in-memory SQLite database so I tried

```
py.test --dburi=sqlite:///C:/Users/Gord/git/sqla-gerrit/sqla_test.sqlite -k AutocommitTest
```

and both tests passed.

**Comment by zzzeek** [comment]
well that's weird, that would imply that...perhaps it's not on the same connection / engine ?  that would be a simpler problem

**Comment by gordthompson** [comment]
Could it be related to the pooling behaviour described here

https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#threading-pooling-behavior

specifically, 

> When a :memory: SQLite database is specified, the dialect by default will use SingletonThreadPool. This pool maintains a single connection per thread ...

so the test thinks it is working with two separate connections but really they are one and the same?

**Comment by zzzeek** [comment]
the test calls connection.invalidate() which for the SQLite memory database, removes the  whole ":memory:" connection so that's why that's happening.

the reason the test calls invalidate() is beacuse it would really want to be calling .close(), but then we have no defined way to get that same connection back from the connection pool to try it again.

the test needs to be adjusted to somehow use .close() rather than invalidate, at least for the SQLite memory connection, or otherwise change how it is working.  what it wants to test is that the "autocommit" isolation level is reset.

**Comment by zzzeek** [comment]
im working out some way to get the same connection on a second checkout, will bea little hacky.

**Comment by zzzeek** [comment]
this is pretty ugly, but there's no API right now to checkout a specific DBAPI connection back from the pool:

```
diff --git a/lib/sqlalchemy/testing/suite/test_dialect.py b/lib/sqlalchemy/testing/suite/test_dialect.py
index 1b3307042..03f6d80b3 100644
--- a/lib/sqlalchemy/testing/suite/test_dialect.py
+++ b/lib/sqlalchemy/testing/suite/test_dialect.py
@@ -115,13 +115,24 @@ class AutocommitTest(fixtures.TablesTest):
         conn = config.db.connect()
         c2 = conn.execution_options(isolation_level="AUTOCOMMIT")
         self._test_conn_autocommits(c2, True)
-        conn.invalidate()
-        self._test_conn_autocommits(conn, False)
 
-    def test_autocommit_off(self):
-        conn = config.db.connect()
+        rec = conn.connection._connection_record
+        conn.close()
+
+        # test that the autocommit state resets
+        from sqlalchemy.pool.base import _ConnectionFairy
+        raw_conn = _ConnectionFairy._checkout(
+            config.db.pool, rec.checkout(config.db.pool)
+        )
+
+        conn = config.db._connection_cls(config.db, raw_conn)
         self._test_conn_autocommits(conn, False)
 
+        conn.close()
+
+    def test_autocommit_off(self, connection):
+        self._test_conn_autocommits(connection, False)
+
 
 class EscapingTest(fixtures.TestBase):
     @provide_metadata

```

**Comment by zzzeek** [comment]
we at least need to do "test_conn_autocommits(connection, True)" even on SQLite memory, if we aren't testing that it resets correctly which is kind of a separate thing.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add AUTOCOMMIT support for cx_Oracle and SQLite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1734

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add AUTOCOMMIT support for cx_Oracle and SQLite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1734

**Comment by gordthompson** [comment]
Depends on: #5168

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Implement autocommit isolation level for pysqlite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1814
