### ISSUE TITLE
Unexpected behaviour with numpy integers

### ISSUE THREAD

**Issue by stdkoehler** [sqlalchemy/sqlalchemy#5167]
Hi all,

using numpy integers with sqlalchemy leads to unexpected behaviour. If I insert a numpy integer (e.g. numpy.int32 to a table with Integer columns strange binary data is inserted.
Also filtering for Integer doesn't work (I provide a minimal example here: https://stackoverflow.com/questions/60053710/sqlalchemy-and-filtering-with-numpy-datatypes)

Casting the numpy.int32 to standard python int for the insert/query does work.

This happens with a sqlite3 database. I didn't try it on any other type. 

There is a similar issue https://github.com/sqlalchemy/sqlalchemy/issues/3586 which was rejected, mentioning that numpy.integers are not standard python integers. Given the large spread of numpy, I really think it would be great to address this. At minimum with a warning.
Of course I can cast, but if I forget, I will produce a mean bug.

Also, all seems fine with numpy.float... making the integers compatible shouldn't can't be much of an effort I would naively assume... it could be checked for type and if numpy.integer cast to python integer on sqlalchemy side...

Thanks!

**Comment by stdkoehler** [comment]
I got a little deeper in the answer and will be using the type decorator mentioned in https://github.com/sqlalchemy/sqlalchemy/issues/3586. I also understand the performance standpoint.
Nevertheless, the behaviour is not very transparent if you are just migrating to sqlalchemy. Especially, since everything just works well with the other libraries I've been using up to now (sqlite3, pyodbc, pandas). While I understand the answer given previously I really wonder if there wasn't a way to make numpy compatible. It's not that numpy was a very exotic library.

**Comment by CaselIT** [comment]
You should also be able to use the solution in this answer https://stackoverflow.com/questions/38753737/inserting-numpy-integer-types-into-sqlite-with-python3 to handle it in the sqlite3 side, since sqlachemy uses sqlite3 by default.
```py
sqlite3.register_adapter(np.int64, int)
# or np.int32 in your case
```

**Comment by zzzeek** [comment]
IMO sqlite3 and/or numpy should address this directly.      if for example numpy integers work fine with other database drivers.

**Comment by zzzeek** [comment]
especially that it just worked in python 2.   anyway, closing this.
