### ISSUE TITLE
get_check_constraints() fails to parse constraints with newlines

### ISSUE THREAD

**Issue by elimach** [sqlalchemy/sqlalchemy#5170]
`get_check_constraints()` fails to parse constraints with newlines.

If the constraint returned by `pg_get_constraintdef()` contains newlines, `get_check_constraints` in `dialects/postgresql/base.py` prints a warning and fails to parse the constraint.

The regex in `get_check_constraints` does not handle newlines: `re.match(r"^CHECK *\((.+)\)( NOT VALID)?$", src)` 

I think that can be solved by either using `flags=re.DOTALL` or by removing the newlines before parsing `src = src.replace('\n','')`.

Full test-case:

```bash
# Start postgres (any postgres >= 9)
docker run -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 postgres
```

```bash
# Log into postgres
psql -h localhost -U postgres postgres
```

```bash
# Create table with a check-constraint
CREATE TABLE tbl (
   id int NOT NULL DEFAULT 0
  ,CHECK
  (
    CASE
      WHEN id < 0 THEN false
      WHEN id >= 0 THEN true
    END
  )
);
```

```python
# execute test-script
# required libraries: pip install sqlalchemy psycopg2-binary

import sqlalchemy
from sqlalchemy import MetaData
from sqlalchemy.ext.declarative import declarative_base

engine = sqlalchemy.create_engine("postgresql://postgres@localhost/postgres", echo=False)
meta = MetaData(bind=engine)
meta.reflect()
```

```bash
# Result
dialects/postgresql/base.py:3489: SAWarning: Could not parse CHECK constraint text: 'CHECK (\nCASE\n    WHEN (id < 0) THEN false\n    WHEN (id >= 0) THEN true\n    ELSE NULL::boolean\nEND)'
  util.warn("Could not parse CHECK constraint text: %r" % src)
```

Link to discussion on pgsql-bugs:
- [pretty_bool in pg_get_constraintdef has no effect since pg >= 9](https://www.postgresql.org/message-id/flat/490036036.13996.1582635382921%40office.mailbox.org)

Greetings
elim

**Comment by zzzeek** [comment]
hi there -

are you able to provide this in the form of a pull request, that also adds a test case to https://github.com/sqlalchemy/sqlalchemy/blob/master/test/dialect/postgresql/test_reflection.py#L1542 ?  basically add a CheckConstraint with text that requires the fix.    otherwise will see if a contributor has time to get to this.

**Comment by EricBorczuk** [comment]
@zzzeek I took a stab at a fix! https://github.com/sqlalchemy/sqlalchemy/pull/5172

**Comment by zzzeek** [comment]
it looks great!

**Comment by elimach** [comment]
Hi Eric. That looks great. Thank you for fixing it.

**Comment by zzzeek** [comment]
is there a reason you are ironing out the newlines / carriage returns into spaces?    If I were doing that, I'd use a regex so that any expanse of space becomes a single whitespace, however, this will get in the way if the whitespace is present inside of a literal string expression.   so im going to have it give you back the constraint text exactly as it is, if possible.

**Comment by sqla-tester** [comment]
**Eric Borczuk** has proposed a fix for this issue in the **master** branch:

**While parsing for check constraints, ignore newline characters in the check condition** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1749

**Comment by sqla-tester** [comment]
**Eric Borczuk** has proposed a fix for this issue in the **rel_1_3** branch:

**While parsing for check constraints, ignore newline characters in the check condition** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1756

**Comment by zzzeek** [comment]
thanks all for the great work and reviews!

**Comment by EricBorczuk** [comment]
Just read your comment above - your changes make perfect sense, sorry I missed the case where newlines were literally placed in quotes!

Happy to help out, hopefully I can do more in the near future!
