### ISSUE TITLE
string argument without an encoding 

### ISSUE THREAD

**Issue by AAgile** [sqlalchemy/sqlalchemy#5175]
https://github.com/sqlalchemy/sqlalchemy/blob/132006ba8a714199d4f761b0e66fc2e516e46ba3/lib/sqlalchemy/sql/sqltypes.py#L929
The line referenced above is missing the 2nd argument, e.g. 
`value = bytes(value,'utf-8')`

This will cause crashes when trying to select NULL values from an INT table column, e.g.
`TableObj.query.filter(TableObj.column_one.is_(None).all()`

I came across this while building a flask app using sqlalchemy 1.3.11 with python3 & sqlite

**Comment by zzzeek** [comment]
hi there -

the line of code you refer towards is for the use of the Binary datatype, not int.  While there is no reproducing test case attached here, it looks like you are filing the identical bug as #5073 (which also did not include a test case).     When properly used, there is no "encoding" because the value being returned is of type bytes, not string.

Assuming everything is the same in this issue, if a SQLite column is storing integers, you should be using the Integer datatype.  if the column is storing mixed data, then you need to make your own type that will run isinstance() on each value to check what it is.

Here is a complete [MCVE](http://stackoverflow.com/help/mcve) illustrating no bug if the correct type is used:

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import INT
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(INT)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add_all([A(data=1), A(data=None)])
s.commit()


print(s.query(A).filter(A.data.is_(None)).all())

```

output:

```
CREATE TABLE a (
	id INTEGER NOT NULL, 
	data INTEGER, 
	PRIMARY KEY (id)
)


2020-02-27 23:17:47,428 INFO sqlalchemy.engine.base.Engine ()
2020-02-27 23:17:47,428 INFO sqlalchemy.engine.base.Engine COMMIT
2020-02-27 23:17:47,429 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-02-27 23:17:47,430 INFO sqlalchemy.engine.base.Engine INSERT INTO a (data) VALUES (?)
2020-02-27 23:17:47,430 INFO sqlalchemy.engine.base.Engine (1,)
2020-02-27 23:17:47,430 INFO sqlalchemy.engine.base.Engine INSERT INTO a (data) VALUES (?)
2020-02-27 23:17:47,430 INFO sqlalchemy.engine.base.Engine (None,)
2020-02-27 23:17:47,431 INFO sqlalchemy.engine.base.Engine COMMIT
2020-02-27 23:17:47,431 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-02-27 23:17:47,431 INFO sqlalchemy.engine.base.Engine SELECT a.id AS a_id, a.data AS a_data 
FROM a 
WHERE a.data IS NULL
2020-02-27 23:17:47,432 INFO sqlalchemy.engine.base.Engine ()
[<__main__.A object at 0x7f78f6e80b50>]

```

**Comment by AAgile** [comment]
That's super helpful, thank you for the quick reply. Looking at your example, it does work as expected where my code didn't but I'm not sure why. One possible difference is that in my project I created the object structure by reflecting the table, but it's just a hunch. I'll try to extract a relevant code piece and report back after the weekend.

**Comment by zzzeek** [comment]
So seeing that three people have had this problem in a few weeks, I can potentially be swayed to put a much nicer error message when this occurs.  but the basic issue is that SQLite doesn't have strong typing at the table level.  You can put any kind of data into any row and the type of that data is whatever was placed there.  Apparently sqlite and/or the Python pysqlite adapter has some way of distinguishing between a "string" and a "binary" bit of data.  that is, you can put 'foo' in one row, and b'foo' in another, and they will be stored *differently*.

so all the issues here come from this basic sqlite "feature" that depending on what application / platform was putting data into the database before, impacts how it can be read later on.

**Comment by AAgile** [comment]
Hi Everyone, 
I did some more work on this, and indeed it appears that there is a problem with the data entries in the sqlite db being of different data types, in spite of the column being defined as INT and all rows showing as "NULL" when viewed in sqlitebrowser. Below is a code sample:

        # -*- coding: utf-8 -*-
        """
        Example code for sqlalchemy issue:
        https://github.com/sqlalchemy/sqlalchemy/issues/5175
        """
        from os               import path
        from flask            import Flask
        from flask_sqlalchemy import SQLAlchemy
        # -----------------------------------------------------------------------------
        # source data
        # -----------------------------------------------------------------------------
        class config_obj():
            BASEDIR      = path.abspath(path.dirname(__file__))
            SQLITE_FILE  = path.join(BASEDIR,'bug.db')
            SQLITE_URI   = 'sqlite:///' + SQLITE_FILE
            SQLALCHEMY_DATABASE_URI        = SQLITE_URI
            SQLALCHEMY_TRACK_MODIFICATIONS = False

        # load db
        db  = SQLAlchemy()                      # create db object
        app = Flask(__name__)                   # create app object
        app.config.from_object(config_obj)      # load config file
        db.init_app(app)                        # ini db with app
        db.reflect(app = app)                   # load table metadata

        # -----------------------------------------------------------------------------
        # object definition
        # -----------------------------------------------------------------------------
        class SpaceObj(db.Model):
            # load object model from db schema table definition
            __table__ = db.metadata.tables['object']   

        # try to select with companyID NULL triggers error
        with app.app_context():    
            objects = SpaceObj.query.filter(SpaceObj.obj_reentry.is_(None),
                                        SpaceObj.company_id.is_( None),
                                        SpaceObj.obj_type.isnot('DEBRIS')).all()

Running this, should give you the type error output:

        # -*- coding: utf-8 -*-
        """
        Created on Sun Mar  1 10:12:46 2020

        @author: void
        """

        runfile('T:/tmp/bug.py', wdir='T:/tmp/bug.py')
        Traceback (most recent call last):

          File "T:/tmp/bug.py", line 54, in <module>
            SpaceObj.obj_type.isnot('DEBRIS')).all()

          File "H:\Apps\Anaconda3\envs\REngine\lib\site-packages\sqlalchemy\orm\query.py", line 3233, in all
            return list(self)

          File "H:\Apps\Anaconda3\envs\REngine\lib\site-packages\sqlalchemy\orm\loading.py", line 101, in instances
            util.raise_from_cause(err)

          File "H:\Apps\Anaconda3\envs\REngine\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
            reraise(type(exception), exception, tb=exc_tb, cause=cause)

          File "H:\Apps\Anaconda3\envs\REngine\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
            raise value

          File "H:\Apps\Anaconda3\envs\REngine\lib\site-packages\sqlalchemy\orm\loading.py", line 81, in instances
            rows = [proc(row) for row in fetch]

          File "H:\Apps\Anaconda3\envs\REngine\lib\site-packages\sqlalchemy\orm\loading.py", line 81, in <listcomp>
            rows = [proc(row) for row in fetch]

          File "H:\Apps\Anaconda3\envs\REngine\lib\site-packages\sqlalchemy\orm\loading.py", line 574, in _instance
            populators,

          File "H:\Apps\Anaconda3\envs\REngine\lib\site-packages\sqlalchemy\orm\loading.py", line 695, in _populate_full
            dict_[key] = getter(row)

          File "H:\Apps\Anaconda3\envs\REngine\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 944, in process
            value = bytes(value)

        TypeError: string argument without an encoding

To reproduce this, you will need the sqlite db file. The original is a development clone of a MySQL production db with 100k+ entries, but I trimmed it down to a smaller version to reproduce the error. Github wouldn't let me attach a .db file, so I changed the extension to .db.txt; you'll have to change it back to run the example.

[bug.db.txt](https://github.com/sqlalchemy/sqlalchemy/files/4272241/bug.db.txt)

So if this problem is caused by poorly managed entries in the db (which are outside of my control), how can I make my code more robust to handle that? Thanks again for all the help.

**Comment by AAgile** [comment]
One more update: I found a workaround using raw sql and then reconstruct the object list after:

    # -*- coding: utf-8 -*-
    """
    Example code for sqlalchemy issue:
    https://github.com/sqlalchemy/sqlalchemy/issues/5175
    """

    from os               import path
    from flask            import Flask
    from flask_sqlalchemy import SQLAlchemy

    # -----------------------------------------------------------------------------
    # source data
    # -----------------------------------------------------------------------------
    class config_obj():
        BASEDIR      = path.abspath(path.dirname(__file__))
        SQLITE_FILE  = path.join(BASEDIR,'bug.db')
        SQLITE_URI   = 'sqlite:///' + SQLITE_FILE
        SQLALCHEMY_DATABASE_URI        = SQLITE_URI
        SQLALCHEMY_TRACK_MODIFICATIONS = False

    # load db
    db  = SQLAlchemy()                      # create db object
    app = Flask(__name__)                   # create app object
    app.config.from_object(config_obj)      # load config file
    db.init_app(app)                        # ini db with app
    db.reflect(app = app)                   # load table metadata

    # -----------------------------------------------------------------------------
    # object definition
    # -----------------------------------------------------------------------------
    class SpaceObj(db.Model):
        # load object model from db schema table definition
        __table__ = db.metadata.tables['object']   
        
        # load object attributes from passed dict
        def load(self,data):
            #loop over dict > assign as attribute
            for key, value in data.items():
                self.key = value

    # -----------------------------------------------------------------------------
    # select entries (tolerates type error)
    # -----------------------------------------------------------------------------
    with app.app_context():    

        # get desired rows using raw sql    
        query   = """SELECT * FROM object WHERE 
                        company_id IS NULL AND
                        obj_type IS NOT 'DEBRIS' AND
                        obj_reentry IS NULL"""
        result  = db.session.execute(query)
        rdicts  = [{column: value for column, value in row.items()} for row in result]    
        
        # construct list of objects 
        objects = []
        for row in rdicts:
            obj = SpaceObj()
            obj.load(row)
            objects.append(obj)

This works, but it would admittedly be nicer if sqlalchemy were able to generate the desired result directly.

**Comment by zzzeek** [comment]
Just make yourself a datatype that expects everything you might get:
```

class MixedBinary(TypeDecorator):
    impl = String

    def process_result_value(self, value, dialect):
        if isinstance(value, str):
            value = bytes(value, 'utf-8')
        elif value is not None:
            value = bytes(value)

        return value
```

this is in the docs here: https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#dealing-with-mixed-string-binary-columns-in-python-3

that works around the trace you are getting.  now what this has to do with ints, im not sure you need to make sure you're using the datatypes you want for columns.    see https://docs.sqlalchemy.org/en/13/core/custom_types.html#custom-and-decorated-types-reflection for a discussion on how to work in these custom datatypes when you are using reflection.

**Comment by AAgile** [comment]
Good suggestion, thanks.

I did some more experimenting and found the cause at last: the "comment" column in the db table is defined as type BLOB (binary) but has string entries in a couple of rows. I have no idea how these made it into the production db (MySQL) from which the sqlite was cloned, but at least now I know what to look for. 

So in the end, sqlalchemy was not to blame. To be honest though, it would have been helpful if the error message was a little more descriptive; especially if it included the offending table column - that would have saved me a lot of time. 

Thanks for the help :).
