### ISSUE TITLE
remove util.compat.nested and rewrite nested context managers per py2.7/ py3 style

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5177]
I think this manager is used in test/engine/test_execute.py in one place and that's it.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Remove obsolete util.compat.nested** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1757
