### ISSUE TITLE
Execute does not accept positional parameters that are not dicts

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5178]
After #4848 `execute('select ?', 1)` will be coerced to `execute(text('select ?'), 1)`, but the second case raises an error since it expects that all positional elements are dicts.

The actual sql texts is not important for this issue, since the error happens before the sql is actually executed.

Full example:

```py
import sqlalchemy as sa
e = sa.create_engine('sqlite://')
e.execute('select ?', 42).scalar() # return 42
e.execute('select ?', (42, )).scalar() # return 42
e.execute(sa.text('select ?'), 42).scalar() # raises
e.execute(sa.text('select ?'), (42, )).scalar() # raises
```
In both cases the error is similar to this
```
----> 1 e.execute(sa.text('select ?'), 42)

..\lib\sqlalchemy\engine\base.py in execute(self, statement, *multiparams, **params)
   2287         """
   2288         connection = self.connect(close_with_result=True)
-> 2289         return connection.execute(statement, *multiparams, **params)
   2290
   2291     def exec_driver_sql(self, statement, *multiparams, **params):

..\lib\sqlalchemy\engine\base.py in execute(self, object_, *multiparams, **params)
    990             raise exc.ObjectNotExecutableError(object_)
    991         else:
--> 992             return meth(self, multiparams, params)
    993
    994     def _execute_function(self, func, multiparams, params):

..\lib\sqlalchemy\sql\elements.py in _execute_on_connection(self, connection, multiparams, params)
    279     def _execute_on_connection(self, connection, multiparams, params):
    280         if self.supports_execution:
--> 281             return connection._execute_clauseelement(self, multiparams, params)
    282         else:
    283             raise exc.ObjectNotExecutableError(self)

..\lib\sqlalchemy\engine\base.py in _execute_clauseelement(self, elem, multiparams, params)
   1069             # ensure we don't retain a link to the view object for keys()
   1070             # which links to the values, which we don't want to cache
-> 1071             keys = list(distilled_params[0].keys())
   1072         else:
   1073             keys = []

AttributeError: 'list' object has no attribute 'keys'
```

**Comment by zzzeek** [comment]
that's part of the change for 2.0.  execute() accepts statement object and an optional dict, and that's it.  there's no more positional parameters at the level of .execute(), as text() only uses named parameters.    direct positional param usage is only in exec_driver_sql().

**Comment by CaselIT** [comment]
So should we raise a more meaningful exception in this case?
Adding a check to avoid the error, does lead to the correct result though.

**Comment by zzzeek** [comment]
this should not be raising an exception until 2.0, for the moment we just need to emit a RemovedIn20 warning.

**Comment by zzzeek** [comment]
in 2.0 we really want positional only arguments but these are not ready until Python 3.7.   We will probably have to enforce this manually using `*args, **kw` unless 2.0 can target 3.7 and above.  the idea at https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#execute-method-more-strict-execution-options-are-available-on-orm-session is probably not going to be smooth enough as far as documentation.

**Comment by CaselIT** [comment]
Ok I'll change this.

Note that I found out this error because of this test in oslo.db
https://github.com/openstack/oslo.db/blob/bf5b45ebba24b4c8737c3197f2cd65f84fd2448c/oslo_db/tests/sqlalchemy/test_utils.py#L938

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Coerce string in execute to :func:`.text` and introduce `exec_driver_sql`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1753

**Comment by CaselIT** [comment]
> So should we raise a more meaningful exception in this case?
> Adding a check to avoid the error, does lead to the correct result though.

I was mistaken, avoiding the error on the keys actually leads to an execute error from the db. So maybe we should just raise a meaningful error?

**Comment by zzzeek** [comment]
> > So should we raise a more meaningful exception in this case?
> > Adding a check to avoid the error, does lead to the correct result though.
> 
> I was mistaken, avoiding the error on the keys actually leads to an execute error from the db. So maybe we should just raise a meaningful error?

can you provide a more specific example of what we're talking about?  what API usage, and then what error  ?

**Comment by CaselIT** [comment]
Here is an example of a piece of code I'm referring to, from the oslo.db tests:
```
        # NOTE(zzzeek): SQLAlchemy 1.2 Boolean type will disallow non 1/0
        # value here, 1.1 also coerces to "1/0" so use raw SQL to test the
        # constraint
        with self.engine.connect() as conn:
            conn.execute(
                "INSERT INTO abc (deleted) VALUES (?)",
                (10, )
            )
```
Link to the code https://github.com/openstack/oslo.db/blob/bf5b45ebba24b4c8737c3197f2cd65f84fd2448c/oslo_db/tests/sqlalchemy/test_utils.py#L938

Currently in ths change set https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1753, that changes execute to coerce a string to text, this code fails.
The original exception is the attribute error that I've reported in the issue op above.
As suggested, I've made that code path warn that a dict is required, but we still get an error, this time on the db/driver side:

```
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1327, in _execute_context
    cursor, statement, parameters, context
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/oslo_db/sqlalchemy/test_base.py", line 226, in ins_wrap
    return f(self)
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/oslo_db/tests/sqlalchemy/test_utils.py", line 940, in test_change_deleted_column_type_sqlite_drops_check_constraint
    (10, )
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 997, in execute
    return meth(self, multiparams, params)
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 281, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1128, in _execute_clauseelement
    distilled_params,
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1331, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1552, in _handle_dbapi_exception
    util.raise_from_cause(newraise, exc_info)
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 412, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 155, in reraise
    raise value.with_traceback(tb)
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1327, in _execute_context
    cursor, statement, parameters, context
  File "/home/jenkins/workspace/openstack_gerrit/openstack_project/oslo.db/oslo.db/.tox/py37/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
oslo_db.exception.DBError: (sqlite3.ProgrammingError) Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.
[SQL: INSERT INTO abc (deleted) VALUES (?)]
(Background on this error at: http://sqlalche.me/e/f405)
```
The link of the failing test: https://jenkins.sqlalchemy.org/job/openstack_gerrit/openstack_project=oslo.db/3102/testReport/oslo_db.tests.sqlalchemy.test_utils/TestMigrationUtils/test_change_deleted_column_type_sqlite_drops_check_constraint/

On hindside maybe I should have just commented on #4848. I can move this to that issue if you prefer

**Comment by zzzeek** [comment]
OK, let's back up.

in 1.4, the only thing we are doing is adding a deprecation warning.     the actual coercion to text() would only occur in 2.0.  Within 1.4, this would be wtihin a "future" version of Connection that outside apps would get by using things in sqlalchemy.future.

for the moment, just emitting the removedin20 deprecation warning, and adding the exec_driver_sql method, are all that are needed.   a second step would be to get a "future" version of Connection to use the new behavior but that can be something separate.   I'm still working out how the "Future" connecvtion will work, it will likely be the same Connection with some flags set on it.

**Comment by CaselIT** [comment]
I'm not sure why I convinced myself that the coercion was a 1.4 thing...
Well ok, I'll revert that change from https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1753, and that should take care of the error.
As a bonus, sqlalchemy will already use the `exec_driver_sql` everywhere it needs to :)

Regarding the warning with non dict positional arguments, should this be always emitted, or only in case of non string usage?

**Comment by zzzeek** [comment]
It might be hard to come up with a decent deprecation warning for the arguments right now since mutliple things are changing at once.     what I forgot to mention is that we still have an "executemany" style of calling which is invoked by passing a sequence of dictionaries, rather than a dictionary.    this is yet another "implicit" thing that will look ugly with pep-484 annotations but I wasn't ready to go so far as to change that also.

**Comment by CaselIT** [comment]
I'm checking the params after the `_distill_params` so it does support the list of dict use.
But I agree that it may be hard to come up with as warning, since it may not be needed, since using anything other than dict will cause an error when the args are acutally used unless a string is used as parameter, so we may just add it to the string warning.

**Comment by zzzeek** [comment]
I'd not go too far with this right now.    im still building out the concept of the "future" package so this will look more natural as it gets there.   the deprecation warning for text() and adding exec_driver_sql is fine though.

**Comment by zzzeek** [comment]
I think we can close here?  reopen if I'm wrong.

**Comment by CaselIT** [comment]
Yes, it should have probably be in the other issue to begin with. Sorry for the mix-up
