### ISSUE TITLE
Using column_property inside another column_property

### ISSUE THREAD

**Issue by Peter92** [sqlalchemy/sqlalchemy#5179]
Hi, I keep bumping into cool features you've done, and I've come across a case that feels like it _should_ theoretically work.

```python
class File(Base):
    name = Column(String(64))
    extension = Column(String(8))
    filename = column_property(name + '.' + extension)
    path = column_property('C:/' + filename)  # This errors
```

I did a quick test and found that I was able to easily implement this behaviour, should I do a pull request or is there a reason you wouldn't want to do this?

**Comment by zzzeek** [comment]
I think this does work.   you need to send that "C" as literal() so that Python can use SQLAlchemy's operator overrides:

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.declarative import declared_attr

Base = declarative_base()

class File(Base):
    __tablename__ = 'file'

    id = Column(Integer, primary_key=True)
    name = Column(String(64))
    extension = Column(String(8))
    filename = column_property(name + '.' + extension)
    path = column_property(literal('C:/') + filename)  # This errors


print(
    Session().query(File.path)
)
```

the column_property() itself does not implement the Python operators (like `__add__()` in this case) and that's not changing, so the left side of the expression here has to pull in the operators.  the right hand side is then seen to have a `__clause_element__()` attribute and then you're in.

**Comment by zzzeek** [comment]
more generally you'd do this:

`    path = column_property('C:/' + filename.expression)  
`

**Comment by zzzeek** [comment]
doc bugs:

https://docs.sqlalchemy.org/en/13/orm/mapping_columns.html#sqlalchemy.orm.column_property

1. column_property() docstring does not note that it returns a ColumnProperty object

2. column_property does it have a "Seealso" linking to https://docs.sqlalchemy.org/en/13/orm/mapped_sql_expr.html#using-column-property

3. the docstring for ColumnProperty itself is sort of taken over by ColumnProperty.Comparator which would be better to not be listing ":members:" https://docs.sqlalchemy.org/en/13/orm/internals.html#sqlalchemy.orm.properties.ColumnProperty, but Sphinx might not allow this

4. .expression could be mentioned in https://docs.sqlalchemy.org/en/13/orm/mapped_sql_expr.html#using-column-property

**Comment by CaselIT** [comment]
Maybe an example like this one would also be nice in the documentation?

**Comment by zzzeek** [comment]
yes, so much will be needed in the docs beyond this, I just realized there are still many classical mappings and also older-style select() objects that don't use "where()".
