### ISSUE TITLE
don't load dialect provision.py modules unless tests are running

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5180]
just noticed that the entire SQLAlchemy library, all of testing and orm, is imported when we load dialects because provision.py relies upon testing, which then relies upon ORM in one spot.

we should try to make it so that testing isn't even imported unless needed.  this will require revising how we call in "provision.py" in each dialect.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't import provision.py unconditionally** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1759

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Don't import provision.py unconditionally** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1760

**Comment by zzzeek** [comment]
i think this broke the DB reaper

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix tests failing for SQLite file databases; repair provisioning** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1747

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix tests failing for SQLite file databases; repair provisioning** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1793
