### ISSUE TITLE
[PG] Cannot select from cte with delete returning

### ISSUE THREAD

**Issue by ggtools** [sqlalchemy/sqlalchemy#5181]
## Version

Python: 3.7.6 on Mac OS
SQL Alchemy: 1.3.13

## Description

I'm trying to get information about the rows actually affected by a delete statement with Postgres. In SQL this could be something like:

```sql
WITH a AS
(
    DELETE FROM my_table
    WHERE my_table.id = 5
    RETURNING date_trunc('day' my_table.ts) as foo
)
SELECT count(*), * FROM a
GROUP BY foo;
``` 

## Reproduction

I created reproduction script from [test_pg_example_one}(https://github.com/sqlalchemy/sqlalchemy/blob/4c81d99bab0e884473abfcb573772aa5d94264c7/test/sql/test_cte.py#L1032) which is quite similar to my need:

```python
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine import default
from sqlalchemy.sql import and_, column, table

dialect = postgresql.dialect()
# dialect = default.StrCompileDialect()


def test_pg_example_one():
    products = table("products", column("id"), column("date"))

    moved_rows = (
        products.delete()
        .where(
            and_(products.c.date >= "dateone", products.c.date < "datetwo")
        )
        .returning(*products.c)
        .cte("moved_rows")
    )

    stmt = moved_rows.select()
    c = stmt.compile(dialect=dialect)
    print(c)


if __name__ == "__main__":
    test_pg_example_one()
```

When launched I go the following stacktrace:

```
python ref_cte.py
Traceback (most recent call last):
  File "ref_cte.py", line 28, in <module>
    test_pg_example_one()
  File "ref_cte.py", line 23, in test_pg_example_one
    c = stmt.compile(dialect=dialect)
  File "<string>", line 1, in <lambda>
  File "/Users/xtof/Documents/Dev/Python/bug-sa/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 468, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/Users/xtof/Documents/Dev/Python/bug-sa/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 474, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/Users/xtof/Documents/Dev/Python/bug-sa/venv/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 593, in __init__
    ) and statement._returning:
AttributeError: 'Select' object has no attribute '_returning'
```

The error occurs either with postgres or the default dialect. Interestingly enough, if you change the CTE to make an insert instead of a delete:
```python
    moved_rows = (
        products.insert()
        .returning(*products.c)
        .cte("moved_rows")
    )
```
The script output is what expected:
```sql
WITH moved_rows AS
(INSERT INTO products (id, date) VALUES (%(id)s, %(date)s) RETURNING products.id, products.date)
 SELECT moved_rows.id, moved_rows.date
FROM moved_rows
```

I also tried to write the full example as a subquery without more success albeit with a different error.

**Comment by zzzeek** [comment]
workaround:

    stmt = moved_rows.select().alias().select()

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Restore crud flags if visiting_cte is set** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1762

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Restore crud flags if visiting_cte is set** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1763

**Comment by zzzeek** [comment]
> 
> I also tried to write the full example as a subquery without more success albeit with a different error.


we want this to work all the way so was that error on compilation or execution?  what was it?   does the workaround work fully?

**Comment by ggtools** [comment]
On the full query the error was the exact same one: `AttributeError: 'Select' object has no attribute '_returning'` during compilation. 

The workaround fixes the issue on the full query. I'll try it on the real application tomorrow and keep you posted. I could also validate the fix against a pre-version if there's one available.

**Comment by zzzeek** [comment]
OK, it wil be pushed tonight and also the patch is https://gerrit.sqlalchemy.org/changes/sqlalchemy%2Fsqlalchemy~1763/revisions/1/patch?zip

**Comment by ggtools** [comment]
Tested on the real application and the head of rel_1_3. Thanks a lot.
