### ISSUE TITLE
cursor / connection not cleaned up if result proxy or after cursor execute fails

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5182]
on CI we are getting SQLite DB is locked due to test_dupe_col_obj which is doing connectionless execution, and due to some GC timing changes that seem to be a result of #4849, it's revealing the cursor and connection are not getting actively closed after the failure. the handle_dbapi_exception in Connection._execute_context() needs to be moved down to include the whole block.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Run handle_error for any exceptions raised in execute_context()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1765

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Run handle_error for any exceptions raised in execute_context()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1766
