### ISSUE TITLE
No Obvious way to select specific columns

### ISSUE THREAD

**Issue by PulellaP** [sqlalchemy/sqlalchemy#5187]
I cannot find a function that allows me to decide which columns I want the database to return a value form. The only way people seam to be doing it is by selecting all columns and then displaying only the ones they want. what if you're trying to save network usage because it is a saturated network. Do I really need my program to receive ALL columns if I only need one?
If I have a table called users that has the following columns ID, name, address, email

This is the target SQL statement that I want:

SELECT name FROM users;

**Comment by zzzeek** [comment]
hi there -

please see "Selecting Specific Columns" in the Core tutorial at: https://docs.sqlalchemy.org/en/13/core/tutorial.html#selecting-specific-columns

or for ORM use: "Querying": https://docs.sqlalchemy.org/en/13/core/tutorial.html#selecting-specific-columns

hope this helps!

**Comment by PulellaP** [comment]
Works thank you!!
