### ISSUE TITLE
Deprecate unmaintained dialects and dbapi

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5189]
There are currently some dialects and DBAPI modules that are not fully supported by SQLAlchemy. This is mainly because they are no longer maintained or the SQLAlchemy devs do not have the time to support them because of their low popularity.

A warning should be raised in this case.

Dialects that fall in this category:
- Firebird - It has a supported external dialect, so we should just point to [sqlalchemy-firebird](https://github.com/pauldex/sqlalchemy-firebird) maintained by @pauldex
- Sybase

DBAPI modules (non exhaustive list):
- pygresql
- oursql
- pypostgresql
- adodbapi

**Comment by CaselIT** [comment]
I'm not sure how this would work in the tests that import the dialect/dbapi.
Could a custom warning class be appropriate in this case? So that we can just ignore it in the tests?

**Comment by zzzeek** [comment]
the warning filters we set up in warnings.py can also have a filter that does a match on the string content of the warning.  I'd just add one of those.

**Comment by CaselIT** [comment]
Here's a table of dialects.

|  DB  | dialect | dialect downloads | deprecate | notes |
|------|---------|-------------------|-----------|--------|
|firebird|fdb| 5k/month| **yes**| External dialect present|
|firebird|kinterbasdb| not on pypi | **yes**| No longer maintained. Last update in 2009? |
|mssql|adodbapi| 10k/month|**yes**| From module docs: `The adodbapi dialect is not implemented in SQLAlchemy versions 0.6 and above at this time.`|
|mssql|mxODBC| 100/month|**yes**| Python 2 only. Last update in 2016.|
|mssql|pymssql| 930k/month|no| Discontinued, but still very popular.|
|mssql|pyodbc| 2.5m/month|no| |
|mysql/mariadb|cymysql| 13k/month|no| Not tested as part of SQLAlchemy's continuous integration |
|mysql/mariadb|myconnpy| 1.4m/month|no| Not tested as part of SQLAlchemy's continuous integration |
|mysql/mariadb|mysqldb| 2.4m/month|no| |
|mysql/mariadb|oursql| 650/month|**yes**| The OurSQL MySQL dialect is legacy and is no longer supported upstream |
|mysql/mariadb|pymysql| 4.6m/month|no| |
|mysql/mariadb|pyodbc| 2.5m/month|no| Not tested as part of SQLAlchemy's continuous integration |
|oracle|cx_oracle| 880k/month|no| |
|postgresql|pg8000| 800k/month|no| Not tested as part of SQLAlchemy's continuous integration |
|postgresql|psycopg2| 7.5m/month|no| |
|postgresql|psycopg2cffi| 21k/month|no| |
|postgresql|pygresql| 156k/month|no| Not tested as part of SQLAlchemy's continuous integration |
|postgresql|pypostgresql| 6.5k/month|**yes**| Seems no longer maintained. Last updated in 2016. |
|sqlite|pysqlcipher | 560/month|**yes**| (same as pysqlcipher3) |
|sqlite|pysqlcipher3 | 1.6k/month|**yes**| (same as pysqlcipher) |
|sqlite|sqlite3 | - |no|  |
|sybase|mxODBC |100/month|**yes**| Deprecate internal sybase dialect. From module docs:`This dialect is a stub only and is likely non functional at this time.` Python 2 only. Last update in 2016. |
|sybase|pyodbc |2.5m/month|**yes**| Deprecate internal sybase dialect. |
|sybase|pysybase |?|**yes**| Deprecate internal sybase dialect. Last release 2008 |

@zzzeek @gordthompson if you agree I can start adding deprecation warnings in the listed ones.

These should be `Removed in 2` warning, correct?

**Comment by zzzeek** [comment]
I agree with this table, there's a bit of history behind some of them but we'll just try to go forward and see what we can do.

I'm not sure these shouldnt just have straight deprecations in 1.4, as opposed to a "2.0" style deprecation.    as discussed, it very well might not make any difference since I'm really not anticipating a 1.5 right now BUT anything can happen.

**Comment by CaselIT** [comment]
Hi @Cito, we are currently deprecating many unsupported dialects / dbapi.

The `pygresql` dbapi is not currently tested by the continuous integration in sqlalchemy, but it's quite popular and mantained, contrary to many other candidates for deprecation.

It would probably be best if you could provide it as an external dialect for sqlalchemy, so that better support for it could be provided.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Deprecate unsupported dialects and dbapi** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1899

**Comment by Cito** [comment]
@CaselIT We can move the PyGreSQL dialect to a separate repository in the [PyGreSQL organisation](https://github.com/PyGreSQL). Is there any documentation for how to provide and test an external dialect, or an example I can copy from?

**Comment by CaselIT** [comment]
I think it that would be great.  

For documentation you can look at https://docs.sqlalchemy.org/en/13/core/connections.html#registering-new-dialects
@zzzeek is there also a more detailed guide in the documentation?

We have a gitter channel if you have additional questions https://gitter.im/sqlalchemy/devel

Regarding examples, off the top of my head, there are
https://github.com/sqlalchemy/sqlalchemy-access and
https://github.com/pauldex/sqlalchemy-firebird.
There is a list of external dialects here https://docs.sqlalchemy.org/en/13/dialects/index.html

Note that the deprecation will be part of the 1.4 release that is still a few months away.

**Comment by Cito** [comment]
@CaselIT thank you for the links. It is on my to-do list now.

**Comment by zzzeek** [comment]
the main README for new dialects is at https://github.com/sqlalchemy/sqlalchemy/blob/master/README.dialects.rst

@gordthompson has kept this document up to date and some of the current 3rd party dialects that are the most recently developed are:

https://github.com/sqlalchemy/sqlalchemy-access
https://github.com/pauldex/sqlalchemy-firebird

in this case there's already the pygresql.py code to work with and you would continue subclassing the Postgresql base that's in SQLAlchemy.  A dialect that does this for example is https://github.com/sqlalchemy-redshift/sqlalchemy-redshift .

**Comment by zzzeek** [comment]
pysqlcipher offers additional SQLite features that AFAIK are not offered by sqlite3, the ability to use encrypted database files.    if this is still the case I think we should probably keep it around.

**Comment by CaselIT** [comment]
From a quick browse of the sqlite3 api in python that seems to still be the case.
`pysqlcipher` is not particularly popular though, ~2k installs month from pypi, but I think we can hold off for now, and maybe revisit this in the future.

Another solution could be to deprecate it and check if we get any complaint :)

**Comment by zzzeek** [comment]
you won't get a complaint because it is not widely used, but if someone really wants an encrypted SQLite database with SQLAlchemy that's their only way to do it. I've worked for multiple financial places and there is definitely this wave of "everything has to be encrypted!" floating through quite often, such as if they want to send SQLite databases over FTP or something.
