### ISSUE TITLE
Docs: "driver" vs. "dialect"

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5190]
### General issue

https://docs.sqlalchemy.org/en/13/dialects/#external-dialects

refers to items as "driver for ...", but a dialect is not a driver; it is much more than that. I suggest reformatting that section to remove the repetitive "driver for ..." phraseology, and sort them by database name.

### Specific issue

The entry for "ibm_db_sa" links to

http://code.google.com/p/ibm-db/wiki/README

which redirects to 

https://github.com/ibmdb/python-ibmdb

and that appears to be just a DBAPI module, not a dialect. I suggest we remove it.

**Comment by zzzeek** [comment]
oh for IBM we do need to link to the SQLAlchemy dialect, whereever it is now, lets find it:

https://pypi.org/project/ibm-db-sa/

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Clean up list of external dialects** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1774
