### ISSUE TITLE
Deprecate old aliases relation and eagerload

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5192]
From the last dev meeting, we should deprecate them, and remove them in v2

- relation -> relationship
- eagerload -> joinedload

@zzzeek do you remember if there are other?

**Comment by zzzeek** [comment]
not offhand we'll just go as we find them

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Deprecate :func:`.eagerload` and :func:`.relation`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1778
