### ISSUE TITLE
emit 2.0 deprecation warning for connectionless execution, implicit execution, when engine.execute is used

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5193]
broken off from #4846 as the autocommit thing is more complicated

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Rework select(), CompoundSelect() in terms of CompileState** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1772
