### ISSUE TITLE
Can I modify the engine configuration of db mannually?

### ISSUE THREAD

**Issue by YonguoS** [sqlalchemy/sqlalchemy#5197]
I don't understand how the connection is created by the engine。I'm sure that db info such as host, port, user, password is necessary for creating a database connecton, and the info is from the engine obj。I now may need to modify the host info of the engine and make a new connction of it. I tried modify the 'engine.url.host' but not worked.

```
db_str = "mysql://root:root@10.185.67.110:3306/online_data3?charset=utf8"

engine = create_engine(db_str)

engine.url.host = '10.185.67.125'

# the connection is still connected to 10.185.67.110
conn = engine.connect()

```

**Comment by zzzeek** [comment]
hi there -

the engine uses a connection pool so it is not recommended that you would modify any elements of the URL.  Additionally, the engine is linked to a Dialect that upon first connection, checks things like the server version of the database, various options and settings that may be present, etc.   For subsequent connections, this step will not occur, so if you change the host to point to a different database, that information will not be accurate.

if you need to connect to different hosts, create different engines.   An individual engine can be released of all of its current database connections by calling the engine.dispose() method:  https://docs.sqlalchemy.org/en/13/core/connections.html?highlight=dispose#engine-disposal

**Comment by YonguoS** [comment]
thanks for you reply and I will consider your advice carefully.

My project's database source is a cluster and cannot bint to a VIP. If the Matser/Slave changes, the engine and connections created before will not be correct anymore and the program cannot sense. I want to create a daemon thread for every engine to get the accurate host, and when the change occurs, call the engine.dispose() method and update the engine's host to the new host, which can be smooth for the program. As what i said yesterday, modifing the engine.url.host didn't work. 
```
db_str = "mysql://root:root@10.185.67.110:3306/online_data3?charset=utf8"
engine = create_engine(db_str)

engine.pool._creator.func_closure[1].cell_contents['host'] = '10.185.67.11'
engine.dispose()

# connected to 10.185.67.11
conn = engine.connect()
```
The way above seems to work. But the codes are just too complicated for to fully understand. Is the way above correct or is there a better solution?

 Looking forward to your reply.

**Comment by zzzeek** [comment]
hi there -

it looks like you are trying to hack together a client-side failover mechanism inside of the connection pool.     this is not a feature that's included in SQLAlchemy and is usually a feature of the DBAPI driver, but does not seem to be something the Python MySQL drivers provide for.

in order to access the "creator", there is no need to patch into it, you can provide this directly via the [creator](https://docs.sqlalchemy.org/en/13/core/engines.html?highlight=creator#sqlalchemy.create_engine.params.creator) argument to create engine.  

however there's an easier way to do this which is just to use the pool from an adjacent engine:

```
e1 = create_engine("url1")

e2 = create_engine("url2")

e1.dispose()
e1.pool = e2.pool

```

**Comment by YonguoS** [comment]
I'm grateful to you for your advice! Replacing engine's pool works well in my _pratice!
