### ISSUE TITLE
Can one provide a default value for a query_expression?

### ISSUE THREAD

**Issue by sonthonaxrk** [sqlalchemy/sqlalchemy#5198]
https://docs.sqlalchemy.org/en/13/orm/loading_columns.html#sqlalchemy.orm.query_expression

Really useful feature. However, it defaults to none. it would be very useful if I could provide a default.

(I'm currently trying to provide a default by wrapping it in a hybrid_property but that's not working).

The use case for a default if a with_expression() is not provided is something like a permissions check. Rather than returning None, it would be good if I could override it and return False, or an arbitrary string.

**Comment by rollokb** [comment]
Looking at the source for query expression I found it trivial to add a default expression.

I was able to just add this to the model.

```
    has_access = ColumnProperty(sql.false())
    has_access.strategy_key = (("query_expression", True),)

```

How would the maintainers feel about a PR allowing a expression to be passed though the arguments? Is that something we'd want to support?

**Comment by CaselIT** [comment]
Not related to the issue, but it seems that the see also link `mapper_query_expression` is missing

**Comment by zzzeek** [comment]
we can accept PRs but they must include tests.  in this case, it must also ensure that the attribute is populated correctly as though the "with_expression()" option were present.

**Comment by zzzeek** [comment]
a workaroudn for now is that you can add a `@property` of your own, and if the vlaue of this attribute is "None", that's the default, so then return your chosen default value for that case.

**Comment by CaselIT** [comment]
> 
> 
> Not related to the issue, but it seems that the see also link `mapper_query_expression` is missing in the docs

This patch should fix the error in the docs https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1786

**Comment by zzzeek** [comment]
milestone is set out for priority only.

**Comment by raptorsun** [comment]
Hello guys, This feature would be very useful for me. I just submitted a pull request :)

**Comment by sqla-tester** [comment]
**Haoyu Sun** has proposed a fix for this issue in the **master** branch:

**Add default expression to query_expression()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2015

**Comment by sqla-tester** [comment]
**Haoyu Sun** has proposed a fix for this issue in the **rel_1_3** branch:

**Add default expression to query_expression()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2017
