### ISSUE TITLE
deprecate strings in loading strategy option

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5202]
Connected to #4705, this deprecates the use of strings in the loader strategy options, like `joinedload`, `selctinload`, `subqueryload` etc

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Deprecate strings indicating attribute names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2303
