### ISSUE TITLE
Documentation error: orm / extensions / associationproxy

### ISSUE THREAD

**Issue by SeattleChris** [sqlalchemy/sqlalchemy#5204]
There is an error in the reference to `UserKeyword.string_key` in the documentation at [orm/extensions/associationproxy](https://docs.sqlalchemy.org/en/13/orm/extensions/associationproxy.html) page in the "Proxying to Dictionary Based Collections" section. 

I believe this should be changed to `UserKeyword.special_key` to be consistent with what it is trying to reference in the example code.

**Comment by zzzeek** [comment]
indeed
