### ISSUE TITLE
PostgreSQL index reflection erroneously includes columns that are part of the INCLUDE clause

### ISSUE THREAD

**Issue by decaz** [sqlalchemy/sqlalchemy#5205]
Since PostgreSQL 11 the `INCLUDE` postfix was implemented for covering indexes. Currently it's not implemented within SQLAlchemy and I use `Index.argument_for('postgresql', 'include', None)` with special hook `@compiles(CreateIndex, 'postgresql')` to modify creation of such indexes. It works but when I use alembic it's auto generation algorithm sees the difference between metadata and real structure, in particular - indexed columns. Therefore it tries to create new index with all keys and included columns.

Refs: #4458

**Comment by zzzeek** [comment]
hi there -

the bug in #4458 includes that reflection would also be implemented.  as it stands I'm not following the case here, you've extended SQLAlchemy to add this special syntax, why aren't you also [extending alembic](https://alembic.sqlalchemy.org/en/latest/api/runtime.html?highlight=include_object#alembic.runtime.environment.EnvironmentContext.configure.params.include_object) to not create inappropriate diffs for this object, until such time that #4458 can be implemented?

**Comment by zzzeek** [comment]
that is, APIs provide all the quick fixes you should need.   for commits to sqlalchemy / alembic master, they should be full feature adds, not quick hacks.

**Comment by decaz** [comment]
@zzzeek this is not hack, because `indkey` contains keys which are **included** but SQLAlchemy doesn't support included indexes. So I think they should be excluded from resulting list.

From here: https://www.postgresql.org/docs/current/catalog-pg-index.html:

> indkey ... This is an array of indnatts values that indicate which table columns this index indexes. For example a value of 1 3 would mean that the first and the third table columns make up the index entries. Key columns come before non-key (included) columns. A zero in this array indicates that the corresponding index attribute is an expression over the table columns, rather than a simple column reference.

**Comment by zzzeek** [comment]
IIUC, when such an index is created in the PG database, then you try to reflect it, you get nothing back at all, as though this index does not exist.  is this accurate?

**Comment by decaz** [comment]
No, I'm getting back index with all columns including that are marked with `INCLUDE` keyword. That is the problem.

**Comment by zzzeek** [comment]
oh ok, when you said "Therefore it tries to create new index with all keys and included columns.", that sounded like it is just doing "add_index", as though it thinks there was no index there.   Is it also doing "drop_index" on the old one?  the issue description here is not very descriptive.    A better title would be, "Postgresql index reflection erroneously includes columns that are part of the INCLUDE clause" is that accurate ?

**Comment by decaz** [comment]
Yes, it also makes `drop_index`. And your title is more accurate, applied it, thanks.

**Comment by sqla-tester** [comment]
**mike bayer** has proposed a fix for this issue in the **master** branch:

**Fix covering index reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1800

**Comment by sqla-tester** [comment]
**mike bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Don't include PG INCLUDE columns as regular index columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1801
