### ISSUE TITLE
Combining pyproject.toml and setup.py has unintented consequences

### ISSUE THREAD

**Issue by rvanlaar** [sqlalchemy/sqlalchemy#5209]
SQLAlchemy has installation problems when installed with poetry and pip since 1.3.14.
The errors show up in the 'get_requires_for_build_wheel' phase.

That's because pyproject.toml and setup.py have problems coexisting.
See this comment: https://github.com/pypa/pip/issues/6163#issuecomment-456738585

Other issues mentioning this: https://github.com/python-poetry/poetry/issues/2197

**Comment by CaselIT** [comment]
I'm not sure if this may be connected with https://github.com/sqlalchemy/sqlalchemy/issues/5207

**Comment by CaselIT** [comment]
Also note that https://github.com/pypa/pip/issues/6163#issuecomment-456738585 does not apply to sqlalchemy, since setup.py does not import sqlalchemy.

Btw you can try to add `--no-use-pep517` to the pip install command

**Comment by zzzeek** [comment]
please continue discussion on #5207
