### ISSUE TITLE
Relationship to inherited subclass of polymorphic object lazy load sibling subclass.

### ISSUE THREAD

**Issue by christophebiocca** [sqlalchemy/sqlalchemy#5210]
Minimal repro: https://github.com/EncircleInc/sqlalchemy-invalid-type-viewonly-relation/blob/master/example.py

The core bits are:
```lang=python
parent = relationship(Parent)
child2 = relationship(Child2, viewonly=True)
```

to declare a relationship to a polymorphic class, and another relationship to a specific subclass. `viewonly` to avoid the two fighting over who owns the FK.

```lang=python
assert obj.child2 is None
assert obj.parent is not None
```

This is the expected behavior, we're pointing at some other subclass of `Parent`, so there's no `Child2` to point to.

```lang=python
assert obj.parent is not None
assert obj.child2 is None, f"{obj.child2} is a {type(obj.child2)}" # Explodes
```

This fails and shows that obj.child2 is actually an instance of `Child1`, which is surprising.

The example uses sqlite, but it was originally found on postgresql, so it's not backend specific.
The issue occurs on both 1.3.7 and 1.3.15.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Test instance for matching class hierarchy on get_from_identity** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1809

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Test instance for matching class hierarchy on get_from_identity** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1810

**Comment by zzzeek** [comment]
that will be merged in a few hours thanks
