### ISSUE TITLE
oracle VARCHAR2(2048 Byte) maybe not support

### ISSUE THREAD

**Issue by pedia** [sqlalchemy/sqlalchemy#5213]
A field in Oracle table declared as:
>  DESCRIPTION	VARCHAR2(2048 BYTE)

Access db code like:
```python
from sqlalchemy.dialects.oracle import VARCHAR2

description = Column(VARCHAR2(2048), nullable=True)
```

caught exception as:

> sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00906:  missing left parenthesis [SQL: SELECT count(:count_2) AS count_1 FROM t_event_log WHERE lower(CAST(t_event_log.description AS VARCHAR2)) LIKE lower(:param_1)] [parameters: {'count_2': '*', 'param_1': '%100003%'}] (Background on this error at: http://sqlalche.me/e/4xp6)

The SQL should be 
```sql
CAST(t_event_log.description AS VARCHAR2(2048))
```

'(2048)' is missing in SQL which cause error.

How to fix this?

**Comment by gordthompson** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) illustrating how that SQL statement is being generated. FWIW, this code shows that the `Column` object itself does have the length defined:

```python
description = sa.Column(sa.dialects.oracle.VARCHAR2(2048), nullable=True)
print(description.type)  # VARCHAR2(2048 CHAR)
```

**Comment by zzzeek** [comment]
it looks like they are using the cast() call.

send the varchar w/ the length to cast:

```
>>> from sqlalchemy import column, cast, VARCHAR
>>> from sqlalchemy.dialects import oracle
>>> print(cast(column('q'), VARCHAR(2048)).compile(dialect=oracle.dialect()))
CAST(q AS VARCHAR(2048 CHAR))
```

**Comment by zzzeek** [comment]
reopen if you have a reproducing example.

**Comment by pedia** [comment]
After some digging, I found this bug should in flask-admin.

```python
count_filter_stmt.append(cast(column, Unicode).ilike(stmt))
```

should be

```python
count_filter_stmt.append(cast(column, column.type).ilike(stmt))
```

Thanks all
