### ISSUE TITLE
TypeError: 'Column' object is not callable

### ISSUE THREAD

**Issue by pavelkim** [sqlalchemy/sqlalchemy#5216]
Hello,

I've got the following code:
```python
class Question(ORMBase):

    __tablename__ = 'question'

    id = Column(Integer, primary_key=True)
    text = Column(String)
    language_id = Column(Integer, ForeignKey('language.id'))
    gender = Column(Boolean)
    order = Column(Integer)
    date_inserted = Column(TIMESTAMP, server_default=text('CURRENT_TIMESTAMP'))
```

Getting an error:
```python
Traceback (most recent call last):
  File "server.py", line 27, in <module>
    class Question(ORMBase):
  File "server.py", line 36, in Question
    date_inserted = Column(TIMESTAMP, server_default=text('CURRENT_TIMESTAMP'))
TypeError: 'Column' object is not callable
```

But once I put `date_inserted` right after the `id` field, everything works fine. 
Any idea what is happening? 

Environment:
```
os x 10.13.6
python 3.6.10
sqlite3 3.31.1
CherryPy==18.5.0
CherryPy-SQLAlchemy==0.5.3
SQLAlchemy==1.3.15
```

UPD: 
`text('CURRENT_TIMESTAMP')` -> `sqlalchemy.text('CURRENT_TIMESTAMP')`
a workaround from here: https://github.com/rflynn/sqlacodegen/issues/3#issuecomment-261237063

**Comment by zzzeek** [comment]
looks like you found the problem, a simple naming conflict.   import "text" as a different name like "from sqlalhcemy import text" or "import sqlalchemy as sa", something like that.

**Comment by CaselIT** [comment]
The problem was the text column defined above `text = Column(String)`

**Comment by pavelkim** [comment]
> The problem was the text column defined above `text = Column(String)`

yep, that was it, thanks!
