### ISSUE TITLE
Issue with JSON type field not updating in certain circumstances

### ISSUE THREAD

**Issue by LokiWijnen** [sqlalchemy/sqlalchemy#5218]
Issue with JSON type field not updating in certain circumstances but fails silently (does not raise an exception)

I must say that I'm not 100% sure if this is an issue with SQLAlchemy or with sqlite or a combination of both.

This is my post on Stackoverflow:
[https://stackoverflow.com/questions/60893464/nested-json-array-not-updating-in-db](https://stackoverflow.com/questions/60893464/nested-json-array-not-updating-in-db)

The issue I'm experiencing is only with multidepth json arrays which once inserted cannot be updated. Example content:

```
data = {
    "title":'some title',
    "status": "some status",
    "logs": [
        [mytimestamp, "First message"],
        [mytimestamp, "Second message"],
        [mytimestamp, "Third message"]
    ]
}
```

Top level data manipulation, such as to `title` and `status` or adding an extra field at the same depth, is fine. However appending messages into `logs` fails silently (no exception is raised in python) when the field is of type JSON. It works absolutely fine if I use a field of type VARCHAR.

Just to clarify, if I have something simple like `data = {"foo": "bar", "baz": "bing"}` then there are no issues at all.

**Comment by CaselIT** [comment]
I think that this is the expected behaviour. From the documentation https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.JSON

> __Detecting Changes in JSON columns when using the ORM__
>
> The JSON type, when used with the SQLAlchemy ORM, does not detect in-place mutations to the structure. In order to detect these, the sqlalchemy.ext.mutable extension must be used. This extension will allow “in-place” changes to the datastructure to produce events which will be detected by the unit of work. See the example at HSTORE for a simple example involving a dictionary.

**Comment by LokiWijnen** [comment]
Thanks for the info, I wasn't aware of that even being a thing. I'll look into sqlalchemy.ext.mutable.

**Comment by CaselIT** [comment]
I think that the problem is that it would be very expensive to track changes to the json, since you would have to compare its value with the previous one, and it can be quite expensive.

I think that you can cheat by doing: 
- edit `data`
- `data = data.copy()`

By re-assigning a copy sqlalchemy would update it, since the object reference has changed

**Comment by LokiWijnen** [comment]
Thanks @CaselIT, I'll try that now.

Another option that appears to work is to always update a top-level item. For example, update `last_updated` every time a new log entry is added, this seems to cause the full record to be updated.

```
data = {
    "title":'some title',
    "status": "some status",
    "last_updated": int(floor(time.time() * 1000)),
    "logs": [
        [mytimestamp, "First message"],
        [mytimestamp, "Second message"],
        [mytimestamp, "Third message"]
    ]
}
```

**Comment by PiotrCzapla** [comment]
I had quite some troubles with the json field that was randomly not updated, using sqlalchemy 1.4.  It seems that simply json.copy() won't make the object marked as modified in every case. See #6865 for more info
