### ISSUE TITLE
casting polymorphic types

### ISSUE THREAD

**Issue by ericman93** [sqlalchemy/sqlalchemy#5225]
Using the Employee/Engineer/Manager example, I want to cast Employee to Engineer.

Changing `on` field only changes in the Employee table, but it won't add it to the Engineer table.   Changing `__class__` didn't work as well

I keep having 
```
identity 'type'; the object may not refresh and/or load correctly (this warning may be suppressed after 10 occurrences)
  (state_str(state), dict_[polymorphic_key]),
```
but the employee instance doesn't exist in the DB yet, I'm trying to change its type before even adding it to the session

**Comment by zzzeek** [comment]
hi there -

The general issue of changing the type of a polymorphic class is #648 and that is a long-ago "wontfix".      However, in this case you are saying you haven't placed the object into the session yet.   If you change the .__class__ of the object, you also need to change the mapper to which it refers towards by placing a new _sa_instance_state upon it, using semi-private API:

```
a1 = A()

a1.__class__ = B

inspect(B).class_manager.setup_instance(a1)

```

overall it is vastly preferable that you do not seek to change the class of an object, especially if its not saved.   Instead, defer the creation of the object until you know the type that it will be, or copy its state into a new object.

**Comment by ericman93** [comment]
while it really changed the mapper, it is trying to insert again related objects although the related object already exists in DB

**Comment by zzzeek** [comment]
please provide a succinct, self contained example with no external dependencies and minimal code and we will try to make it do the thing you want.

**Comment by ericman93** [comment]
it seems that the issue is in my side, sorry :)

**Comment by zzzeek** [comment]
ok great
