### ISSUE TITLE
warning on relationship(viewonly=True, backref(lazy="dynamic"))

### ISSUE THREAD

**Issue by leorochael** [sqlalchemy/sqlalchemy#5229]
On the commit 4376c2e, Adding a backref into a `viewonly` relationship was deprecated to avoid the issue where a backref one2many collection is modified, but the respective many2one relationship cannot be assigned.

However, if the `backref` is `lazy="dynamic"`, there is no risk of the collection in the one2many side of the relationship being modified in this case, so forgive me if I misunderstood the deprecation, but I think it is unwarranted in this specific case.

Conversely, if the `backref` is `lazy="select"` but both sides of the relationship are `viewonly`, then there should also be no harm, hence no warning, but you might consider this a separate issue.

Here is a simple example file showing the warning that I think is unwarranted (`.txt` added so it can be attached to a github issue):
[test_backref.py.txt](https://github.com/sqlalchemy/sqlalchemy/files/4429905/test_backref.py.txt)

**Comment by zzzeek** [comment]
hi there-

dynamic collections are mutable, so a misleading alteration of "c1.parent" can proceed here:

```
    p2 = Parent()

    p2.children_query.append(c1)

    # viewonly relationship was mutated in Python
    assert c1.parent is p2

```

it's true that in this case the backref allows the relationship to work more naturally, but this requires mutating it, so I would remove the viewonly=True in this case since you'd like the value to be modified in Python.

**Comment by leorochael** [comment]
Oh... that's what the `AppenderQuery` is for...

So, if instead of an AppenderQuery the relationship attribute returned a normal, non-mutable query, we could get rid of the warning as well, right? Couldn't a `viewonly` on the declaration side imply `viewonly` on the `backref()` side?

And in the case where both sides are explicitly marked `viewonly` does it make sense to still have a warning? I find it convenient to add `viewonly` relationships on both ends of a relationship that goes thru a secondary table.

I.e. incrementing the example I attached:

```python
class GrandChild(Base):

    __tablename__ = 'grandchild'

    id = sa.Column(sa.Integer, primary_key=True)
    parent_id = sa.Column(sa.ForeignKey(Child.id))
    parent = orm.relationship(
        Child,
        backref=orm.backref("child_children_query", lazy="dynamic"),
        foreign_keys=[parent_id],
    )

    grandparent = orm.relationship(
        Parent,
        viewonly=True,
        uselist=False,
        secondary=Child.__tablename__,
        foreign_keys=[parent_id, Child.parent_id]
        backref=orm.backref("grandchildren_query", lazy="dynamic", viewonly=True),
    )
```

Here the `grandparent / grandchildren_query` relationships are not supposed to be mutated on either end, so we could avoid a warning here, right?

**Comment by zzzeek** [comment]
> Oh... that's what the `AppenderQuery` is for...
> 
> So, if instead of an AppenderQuery the relationship attribute returned a normal, non-mutable query, we could get rid of the warning as well, right? Couldn't a `viewonly` on the declaration side imply `viewonly` on the `backref()` side?
> 
> And in the case where both sides are explicitly marked `viewonly` does it make sense to still have a warning? I find it convenient to add `viewonly` relationships on both ends of a relationship that goes thru a secondary table.

this is the identical issue that is happening in #5149.   "backref" and "back_populates" exist just for the matter of aligning the persistence of two relationships together.  if they are both viewonly, then there is no reason for the persistence to have anything associated with it.  as in #5149 there is simply the "convenience" of the "backref()" function but we don't have a solution for that right now, it can't be backref and folks should prefer to use relationship() explicitly especially for viewonly.


> 
> I.e. incrementing the example I attached:
> 
> ```python
> class GrandChild(Base):
> 
>     __tablename__ = 'grandchild'
> 
>     id = sa.Column(sa.Integer, primary_key=True)
>     parent_id = sa.Column(sa.ForeignKey(Child.id))
>     parent = orm.relationship(
>         Child,
>         backref=orm.backref("child_children_query", lazy="dynamic"),
>         foreign_keys=[parent_id],
>     )
> 
>     grandparent = orm.relationship(
>         Parent,
>         viewonly=True,
>         uselist=False,
>         secondary=Child.__tablename__,
>         foreign_keys=[parent_id, Child.parent_id]
>         backref=orm.backref("grandchildren_query", lazy="dynamic", viewonly=True),
>     )
> ```
> 
> Here the `grandparent / grandchildren_query` relationships are not supposed to be mutated on either end, so we could avoid a warning here, right?

**Comment by leorochael** [comment]
I think it's a pretty big convenience:

 - Not having to specify the primary keys on the `backref`,
 - SQLalchemy automatically figuring out which join keys are foreign from the point of view of the `backref`
 - Not having to deal with circular imports, since usually the place defining the `backref` usually has access to all fields from the local model as well as the related model properly defined and imported without having to resort to strings or lambdas.

It's a lot of code duplication and potential of making a mistake when changing things around if this convenience is not available.

But if that's the final decision, then that's that.

You may close this question if you don't want to make it a feature request.

**Comment by zzzeek** [comment]
I do want there to be a solution for this.  the viewonly decision was made here because leaving it open-ended led to [confusion](#5149).   

this is two reports that "backref()" was convenient.  So since the usage of the "backref()" function implies the use of the "backref" keyword argument, we can add viewonly_backref.    Issue coming up.

**Comment by zzzeek** [comment]
I've proposed new API to allow this use case and the back_populates one to be allowed explicitly in #5237.
