### ISSUE TITLE
ComputedReflectionFixtureTest causes errors for dialects without schemas

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5230]
Current fixture assumes schema support. Discovered during testing re:

https://github.com/pauldex/sqlalchemy-firebird/issues/4

**Comment by CaselIT** [comment]
thanks for checking this @gordthompson

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Apply fix to ComputedReflectionFixtureTest** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1841

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Apply fix to ComputedReflectionFixtureTest** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1842
