### ISSUE TITLE
Example of Full Text Search in Postgres with SQLAlchemy

### ISSUE THREAD

**Issue by Frick-David** [sqlalchemy/sqlalchemy#5231]
Can I get an example of how to do full text search with Postgres with the SQLAlchemy ORM? The documentation [here](https://docs.sqlalchemy.org/en/13/dialects/postgresql.html) does not show an example with the ORM. Simple example code I have:

```
class Person(db.Model):
    __tablename__ = 'person'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
```
The sources I was originally looking at on SO:
[source 1](https://stackoverflow.com/questions/42388956/create-a-full-text-search-index-with-sqlalchemy-on-postgresql)
[source 2](https://stackoverflow.com/questions/13837111/tsvector-in-sqlalchemy#13878979)
show tsvector. A couple comments on them as well as the internet said better support for tsvectors had been implemented in SQLAlchemy.
I am looking to do FTS on some article-type stuff using the ORM versus raw SQL or the QL.

Hope all is well,
David

**Comment by CaselIT** [comment]
I think you can port quite easily the example from the documentation to the orm.
I think you should be able to use `match` on the `name` column. So I think this should work

```py
res = session.query(Person).filter(Person.name.match('foo')).all()
```

**Comment by Frick-David** [comment]
Oh wow. Seems simple enough. Does match take a regex? I will need to play around with it to get fuzzy results. Searching for name Bob with two users Bob and Bobby is one such example. Does this work for sqlite as well as postgres (tested on postgres and it works)? Is this implementing a Full text search ts vector behind the scenes?

Thanks a lot for this!

-------- Original Message --------

**Comment by CaselIT** [comment]
I'm not sure regarding the regexp. 

> Does this work for sqlite

 It should from the documentation https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=match#sqlalchemy.schema.Column.match

**Comment by zzzeek** [comment]
I would strongly recommend you turn on echo=True on your create_engine() and watch the SQL being emitted.  SQLAlchemy is not really doing anything but rendering a "tsvector" or whatever magic keywords the database requires inside of a SQL string.    On SQLite it looks like it renders the keyword "MATCH".   SQLite FTS seems to require a SQLite [extension](https://www.sqlite.org/fts5.html) to be installed in the database and I'm sure it works differently than PG's full text feature.

**Comment by CaselIT** [comment]
I think this can be closed

**Comment by jeanmonet** [comment]
For anyone still looking for an example, see here https://stackoverflow.com/a/73999486/11750716.
