### ISSUE TITLE
Migrating to python3.7.3: TypeError: Object of type dict_values is not JSON serializable

### ISSUE THREAD

**Issue by alex4747-pub** [sqlalchemy/sqlalchemy#5234]
I am converting existing implementation from python-2.7.16 to python-3.7..3. I am using sqlalchemy 1.13.3 - got following exception. Tried sqlalchemy 1.13.5. did not work either.

Traceback (most recent call last):
  File "/home/ar/Envs/a3_pyvcluster/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1173, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/ar/Envs/a3_pyvcluster/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 834, in _init_compiled
    for key in compiled_params
  File "/home/ar/Envs/a3_pyvcluster/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 834, in <genexpr>
    for key in compiled_params
  File "/home/ar/Envs/a3_pyvcluster/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 2391, in process
    serialized = json_serializer(value)
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict_values is not JSON serializable

**Comment by CaselIT** [comment]
You probably forgot a `list(my_dict.values()` somethere.

In python3 dict.values() is not a list

**Comment by alex4747-pub** [comment]
Sorry it is 3 layers deep inside sqlalchemy - i have no control on any possible dictionary at this level. Sqlalchemy-wise is it pretty mundane: columns and relationships. The only suspect is postgres.JSONB column.

**Comment by zzzeek** [comment]
Hi there -

This issue cannot be attended towards without a proper [MCVE](http://stackoverflow.com/help/mcve).     SQLAlchemy passes your data values straight through to Python's json encoder / decoder, or more commonly to the psycopg2 json functions, so there is no known issue within SQLAlchemy which can cause this to occur.

**Comment by CaselIT** [comment]
> Sorry it is 3 layers deep inside sqlalchemy - i have no control on any possible dictionary at this level. Sqlalchemy-wise is it pretty mundane: columns and relationships. The only suspect is postgres.JSONB column.

That would be my suspect also. Check the data that you are trying to serialize as json. The error comes from the json serialization function, so there is nothing sqlalchemy can do.

If you need to customize the function used by sqlalchemy to serialize/deserialize jsons you can check the documentation: https://docs.sqlalchemy.org/en/13/core/engines.html#sqlalchemy.create_engine.params.json_deserializer

For example of mcve for sqlalchemy you can check there https://github.com/sqlalchemy/sqlalchemy/issues?q=is%3Aissue+label%3A%22great+mcve%22+

**Comment by alex4747-pub** [comment]
Do happen to have MCVE with postgres backend? It seems that the field in question is a dictionary that hast to be encoded as JSON field, but I am not sure yet.

**Comment by CaselIT** [comment]
changing ` create_engine('sqlite:///:memory:', echo=True)` to ` create_engine('postgresql://scott:tiger@host/db', echo=True)` should work

**Comment by zzzeek** [comment]
you can use pdb.set_trace() in your live application to understand more specifically what's going on, or even just print statements to see what the data in question looks like.

**Comment by alex4747-pub** [comment]
I did exactly that  and I noticed that I was using non-problematic data in my test. The problematic case has a couple of cases like     'route_distances': dict_values([]) . Now I am trying to figure out how this could happen and how to reproduce it. Is it possible to get this using dictionary constructor?

**Comment by CaselIT** [comment]
I think you can get dict_values only by calling `.values()` on a dict. Definitely not by calling `dict`

**Comment by alex4747-pub** [comment]
I suppose you can close it, is data generation that was screwed up.
