### ISSUE TITLE
disallow eval() from main argument on relationship() ; improve docs for other args

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5238]

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use dot-separated name resolution for relationship target** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1850

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Use dot-separated name resolution for relationship target** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1851
