### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by azuretek** [sqlalchemy/sqlalchemy#5239]
I'm trying to use this library to connect to the ProxySQL admin interface and while it's similar to MySQL it's lacking many global variables that this library expects to exist.

In this case I'm getting an error when connecting.

```
  File "/Users/abirenhart/.asdf/installs/python/3.6.10/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 199, in first_connect
    dialect.initialize(c)
  File "/Users/abirenhart/.asdf/installs/python/3.6.10/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 2450, in initialize
    default.DefaultDialect.initialize(self, connection)
  File "/Users/abirenhart/.asdf/installs/python/3.6.10/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 321, in initialize
    connection.connection
  File "/Users/abirenhart/.asdf/installs/python/3.6.10/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 2262, in get_isolation_level
    val = cursor.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```

I've narrowed the problem down to this line: https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_15/lib/sqlalchemy/dialects/mysql/base.py#L2262

I think if we change it to something like this it solves the problem.

```
    def get_isolation_level(self, connection):
        cursor = connection.cursor()
        if self._is_mysql and self.server_version_info >= (5, 7, 20):
            cursor.execute("SELECT @@transaction_isolation")
        else:
            cursor.execute("SELECT @@tx_isolation")
        try:
            val = cursor.fetchone()[0]
        except:
            raise NotImplementedError()
        cursor.close()
        if util.py3k and isinstance(val, bytes):
            val = val.decode()
        return val.upper().replace("-", " ")
```

**Comment by zzzeek** [comment]
ugh, how are we supposed to get the isolation level with proxysql?   it doesnt make sense that this is not knowable ?

**Comment by zzzeek** [comment]
proxy SQL in my understanding is using the actual MySQL database for its configuration data and it should be passing these things through?

**Comment by azuretek** [comment]
ProxySQL doesn't store its own configuration in MySQL. It uses SQLlite but with a MySQL interface.

The docs don't seem to indicate a way to tell the "isolation level" the way we do for MySQL.
https://www.sqlite.org/isolation.html

**Comment by zzzeek** [comment]
any other variables it's not reporitng on ?

**Comment by zzzeek** [comment]
also if you can confirm the query proceeds but returns no row, this patch will be applied:

```
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index 26d751faa..54a13b550 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -2297,7 +2297,14 @@ class MySQLDialect(default.DefaultDialect):
             cursor.execute("SELECT @@transaction_isolation")
         else:
             cursor.execute("SELECT @@tx_isolation")
-        val = cursor.fetchone()[0]
+        row = cursor.fetchone()
+        if row is None:
+            util.warn(
+                "Could not retrieve transaction isolation level for MySQL "
+                "connection."
+            )
+            raise NotImplementedError()
+        val = row[0]
         cursor.close()
         if util.py3k and isinstance(val, bytes):
             val = val.decode()

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Gracefully skip isolation level if no row returned** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1852

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Gracefully skip isolation level if no row returned** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1853

**Comment by azuretek** [comment]
> also if you can confirm the query proceeds but returns no row, this patch will be applied:
> 
> ```
> diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
> index 26d751faa..54a13b550 100644
> --- a/lib/sqlalchemy/dialects/mysql/base.py
> +++ b/lib/sqlalchemy/dialects/mysql/base.py
> @@ -2297,7 +2297,14 @@ class MySQLDialect(default.DefaultDialect):
>              cursor.execute("SELECT @@transaction_isolation")
>          else:
>              cursor.execute("SELECT @@tx_isolation")
> -        val = cursor.fetchone()[0]
> +        row = cursor.fetchone()
> +        if row is None:
> +            util.warn(
> +                "Could not retrieve transaction isolation level for MySQL "
> +                "connection."
> +            )
> +            raise NotImplementedError()
> +        val = row[0]
>          cursor.close()
>          if util.py3k and isinstance(val, bytes):
>              val = val.decode()
> ```

That is exactly the behavior, and your fix does appear to resolve the problem. Thanks!

**Comment by azuretek** [comment]
> any other variables it's not reporitng on ?

ProxySQL basically only has its own global variables, normal MySQL ones like `sql_mode` aren't available either. Everything seems to work with this fix though.

https://github.com/sysown/proxysql/wiki/Global-variables
