### ISSUE TITLE
clarify point number 2 in http://sqlalche.me/e/bhk3 that if seession.commit() is to be called, this will expire that data.

### ISSUE THREAD

**Issue by CharlesB2** [sqlalchemy/sqlalchemy#5243]
As probably other first-time users messing around with SQLAlchemy, I had the `DetachedInstanceError` after wanting to access attributes of a queried object after a session commit and session close.

The help page for this http://sqlalche.me/e/bhk3 isn't helpful in this case, since proposed solutions are 1. don't close session, or 2. load relations upfront with relationship-loading techniques. 

I think it should mention that the error also happens with expired attributes of an object, and the associated solution of setting argument `expire_on_commit=False` in Session init.

**Comment by zzzeek** [comment]
hi there -

the expiration of attributes on an instance is normal and you will not get DetachedInstanceError in that case if you follow the guidelines in the document you mention.   As long as the object is associated with the session, it is by definition not detached.

**Comment by zzzeek** [comment]
I guess you're saying you need more specificity on the "load everything up front" pattern.

**Comment by jvanasco** [comment]
I'll take this.

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**added docstring about expire_on_commit for #5243** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2211

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **rel_1_3** branch:

**added docstring about expire_on_commit for #5243** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2328
