### ISSUE TITLE
Rename reflecttable to reflect_table in inspector

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5244]
The inspector has a method called `reflecttable` that does not use snake case convention like all its other methods.

I think we should deprecate the old method (with a remove in 2 warning or also a more long term one)
and create `reflect_table`

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**The :meth:`.Inspector.reflecttable` was renamed to :meth:`.Inspector.reflect_table`.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1865
