### ISSUE TITLE
anticipate cx_oracle 8 changes in symbol behavior

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5246]
the differences described at https://github.com/oracle/python-cx_Oracle/issues/415 can be worked around locally, gerrit reviews are already in place which I will target to this issue.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Evaluate fixes for cx_Oracle 8 API changes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1862

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Evaluate fixes for cx_Oracle 8 API changes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1861
