### ISSUE TITLE
How to create a new table from select statement

### ISSUE THREAD

**Issue by elfring** [sqlalchemy/sqlalchemy#5251]
I am trying the software “SQLAlchemy 1.3.15-179.2” out also on my Linux system.
 
Code example:
```python
   q = session.query(pair.action, pair.check, pair.source_file,
                     func.count("*").label("C")
                    ).group_by(pair.action, pair.check, pair.source_file)
   command = "create table t2 as " + str(q.statement)
   sys.stderr.write("command:\n" + command + "\n")
```

I get the following test output then.
```
command:
create table t2 as SELECT pairs.action, pairs."check", pairs.source_file, count(:count_1) AS "C" 
FROM pairs GROUP BY pairs.action, pairs."check", pairs.source_file
```

:thinking: Now I wonder about the specification “`:count_1`”.
:crystal_ball: Should [the preservation of special information](https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.statement "Description for the attribute “statement”") like [an explicit asterisk](https://docs.sqlalchemy.org/en/13/core/functions.html#sqlalchemy.sql.functions.count "Description for the function “count”") be reconsidered?

**Comment by CaselIT** [comment]
You can use `literal_bind` to log sqlstrings with inline literals.
See this answer on stackoverflow https://stackoverflow.com/a/23835766

**Comment by elfring** [comment]
* Thanks for [your link to the topic “SQLAlchemy: print the actual query”](https://stackoverflow.com/questions/5631078/sqlalchemy-print-the-actual-query/23835766#23835766 "Clarification").

* But I wanted to adjust the shown Python code example (and related software) after I stumbled also on the following error message.
  “…
  ```
  sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'count_1'
  [SQL: create table t2 as SELECT pairs.action, pairs."check", pairs.source_file, count(?) AS "C" 
  FROM pairs GROUP BY pairs.action, pairs."check", pairs.source_file]
  [parameters: [{}]]
  (Background on this error at: http://sqlalche.me/e/cd3x)
  ```
  …”

* Will such information trigger any further improvements also for the software documentation?

**Comment by CaselIT** [comment]
Sorry I just thought you wanted to log the sql. The suggestion to use `q.statement.compile(compile_kwargs={'literal_binds': True})` works, but to achieve what you are trying to do it's probably best to do as described in this answer https://stackoverflow.com/questions/30575111/how-to-create-a-new-table-from-select-statement-in-sqlalchemy

Probably that answer could be adapted to a wiki page, similar to the [Views wiki page](https://github.com/sqlalchemy/sqlalchemy/wiki/Views)

**Comment by elfring** [comment]
Did the topic “How to create a new table from select statement in SQLAlchemy?” evolve any further in the meantime?

**Comment by CaselIT** [comment]
No, I don't believe it did.
If I'm not mistaken, there is no support for this type of table generation directly in sqlalchemy. This type of table generation is very similar to a view, and I think that if we did support one, we would also support the other.
Pinging @zzzeek just to confirm.

**Comment by elfring** [comment]
:bulb: I suggest to take another look at [corresponding software development discussions](https://groups.google.com/d/msg/sqlalchemy/5-6O-Pwzh4A/7VbE9bb3CQAJ "Creating database tables from queries based on ORM API?").

**Comment by CaselIT** [comment]
I'm not really sure what the point of your question is.
From the link provided, you have already asked the same exact question and mike already replied to you.
I'm not sure what else are you asking.

**Comment by elfring** [comment]
It seems that I stumbled on consequences from software evolution.
I became curious on related improvements then.

**Comment by CaselIT** [comment]
Then you should have started by linking the previous question, asking if any update on this was made.
Otherwise we are both wasting time.

I'm closing this. If you have other questions related to this feel free to reopen it

**Comment by elfring** [comment]
I imagine further possibilities to improve mentioned software areas another bit.
It seems that I can not reopen this issue myself.

**Comment by CaselIT** [comment]
It's really unclear what are you proposing. Could you please clarify what you refer in this?

> imagine further possibilities to improve mentioned software areas another bit

**Comment by elfring** [comment]
* How you you think about to make descriptions clearer for the usage of an explicit asterisk (for example)?
* Would you like to add any links to the documentation of the attribute “statement”?

**Comment by CaselIT** [comment]
> How you you think about to make descriptions clearer for the usage of an explicit asterisk (for example)?

Mike has already answered to this profusely in your first question.  

> Would you like to add any links to the documentation of the attribute “statement”?

As was already linked in you previous question, this is already in the documentation https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.statement

**Comment by elfring** [comment]
We got a different understanding for the usage of “[literal columns](https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.expression.literal_column "Description for the function “literal_column”")” during the application of the software library over time.

**Comment by CaselIT** [comment]
I don't think so, sorry. If I have understand it correctly, you aim to render the `*` in the string representation of `statement`. `literal_column` does this and from the documentation

>  literal_column() can be that, or any other arbitrary column-oriented expression.

`literal_column` clearly fits the usage with `*` since it is a column-oriented expression.
