### ISSUE TITLE
Update documentation for testing with pytest

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5254]
It looks like we need to further tweak the documentation for testing. According to ...

https://github.com/sqlalchemy/sqlalchemy/blob/master/README.unittests.rst

... we can run a test against a specific file using

```
py.test --dburi=postgresql+psycopg2://scott:tiger@localhost/test  test/sql/test_query.py
```

However, when I try to do that – on both Windows and Linux – I get:

```
(venv) gord@xubuntu64-nbk1:~/git/sqlalchemy$ py.test --dburi=mssql+pyodbc://sa:_whatever_@192.168.0.179:49242/sqla_test?driver=ODBC+Driver+17+for+SQL+Server /home/gord/git/sqlalchemy/lib/sqlalchemy/testing/suite/test_types.py
ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --dburi=mssql+pyodbc://sa:_whatever_@192.168.0.179:49242/sqla_test?driver=ODBC+Driver+17+for+SQL+Server
  inifile: /home/gord/git/sqlalchemy/setup.cfg
  rootdir: /home/gord/git/sqlalchemy
```

**Comment by CaselIT** [comment]
I routinely run only a specific file or folder, so that should not be the problem.
My guess it that is does not like the `=` or the url string needs to be quoted

**Comment by gordthompson** [comment]
@CaselIT - Thanks for the feedback. More mucking about suggests the following:

1. Yes, sometimes the dburi value needs to be quoted, at least under PowerShell. A URI containing `mssql+pyodbc://@(local)\SQLEXPRESS/sqla_test` needs to be quoted, while a URI containing `mssql+pyodbc://@.\SQLEXPRESS/sqla_test` does not.
2. In some cases, `--db mssql` (as per "README.unittests.rst") will throw an error, while `--db=mssql` will succeed.
3. Regardless of (1) and (2) above, specifying a file in "test/..." tends to work okay, while specifying a file in "lib/sqlalchemy/testing/suite/..." appears to be doomed to failure (and that was my original problem).

**Comment by CaselIT** [comment]
You need to use `test/dialect/test_suite.py` to test the suite, since the sqlalchemy plugin for pytest rewrites the location of tests or something similar with the effect that the entry point for the suite test is the `test_suite.py` file
Don't know regarding the `=` vs the ` ` which one it the correct ones. I usually use the space

**Comment by zzzeek** [comment]
this is correct, the thing is set up to only run tests out of the test/ directory.   right now to run specific tests from the suite I use the -k option, like `py.test test/dialect/test_suite.py -k ComponentReflectionTest`, or use pytest colon notation `py.test test/dialect/test_suite.py::ComponentReflectionTest`

**Comment by gordthompson** [comment]
Thank for the feedback. I had been using the -k option, and suppose I still could use `-k " Thing1Test or Thing2Test ..."` for suite tests to expand the coverage within a given suite file.
