### ISSUE TITLE
Postgresql condition on row expression

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5256]
Does sqlalchemy has a specific construct for postgres row valued expressions? Example
```sql
select *
from some_table
where some_table is not null
```
This query will return all the rows where all columns are not null.

Currently I'm using `sa.column` / `sa.literal_column` to represent the table in the where, since `sa.table` does not work with the comparison. 

Postgresql documentation: https://www.postgresql.org/docs/12/functions-comparison.html after the tip note.

Also, to render `not (some_table is null)` it there another other than using `self_group`? I've noticed that `not(a is b)` is transformed to `a is not b`.
In this case it's not the same since `not (some_table is null)` returns all the rowswhere at least a column is not null, while `some_table is not null` returns all the rows where all columns are not null.

**Comment by zzzeek** [comment]
> Does sqlalchemy has a specific construct for postgres row valued expressions? Example
> 
> ```sql
> select *
> from some_table
> where some_table is not null
> ```
> 
> This query will return all the rows where all columns are not null.

no, we don't have that.    just today on the list you might have noticed im dealing with a Geoaclhemy thing where they are trying to run a function against a whole table as a "record", and the solution i gave there would be the same way you'd do this, that is, a PGRow() or something kind of ColumnElement that renders "table" but has a datatype that lines up with whatever PG needs here, if it's like ARRAY or what I don't know.  but it's a column expression.

> 
> Currently I'm using `sa.column` / `sa.literal_column` to represent the table in the where, since `sa.table` does not work with the comparison.

see https://groups.google.com/d/msg/sqlalchemy/owT52zKYNVw/xUMImCaiAAAJ for the recipe I came up for this.   it would need a datatype and some other things for full comparison etc. to work

> 
> Postgresql documentation: https://www.postgresql.org/docs/12/functions-comparison.html after the tip note.

just FYI there's a ton of PG stuff that we don't have built in right now that are along this line, see #3566 .

if you want to work on this stuff it's definitely leveling up but 1.4 should be getting very good at this stuff by now :)


> 
> Also, to render `not (some_table is null)` it there another other than using `self_group`? I've noticed that `not(a is b)` is transformed to `a is not b`.
> In this case it's not the same since `not (some_table is null)` returns all the rowswhere at least a column is not null, while `some_table is not null` returns all the rows where all columns are not null.

uhhhhhhhh that indicates a three-condition behavior for "IS" ?   that is not good.   making sure everything is going through the column mechanics first is how to start, then the "negation" behavior for a column expression can be customized.

then again why would anyone ever need this goofy feature?   just like all the other PG things that you'll note I labeled "bizarro", that's how I find the issue in the search.

**Comment by CaselIT** [comment]
Note that at the moment I'm perfectly happy to use column or literal column in this case. The `is` behaviour can be customised with self_group, so I can create the desired query.

I'm not sure if this construct it worth creating. Btw here the table name here behaves like a `row()`.

I'll drop a line in the linked issue and close this, since it was just to ask if a better implementation existed.

**Comment by zzzeek** [comment]
I want to ultiamtely do everything here and in #3566.  this comes up all the time.  it's just if it is done quickly without consdiering PG's syntactical concepts in total, we can paint ourselves into a corner.  so id like to come up with a full concept that meets PG's conception of "records".

**Comment by CaselIT** [comment]
Added a comment in #3566. This can be closed, so we can track all the missing pg behaviors from a single place
