### ISSUE TITLE
subquery contains JSON columns will cause unexpected  query result with joins

### ISSUE THREAD

**Issue by IterableTrucks** [sqlalchemy/sqlalchemy#5257]
```python
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker,relationship,contains_eager
from sqlalchemy.ext.declarative import declarative_base

engine=sa.create_engine("postgresql:///postgres")
Session=sessionmaker(bind=engine)
Base=declarative_base()

class ChildSchool(Base):
    __tablename__="child_school_associations"
    child_id=sa.Column(sa.Integer,sa.ForeignKey("child.id"),primary_key=True)
    school_id=sa.Column(sa.Integer,sa.ForeignKey("schools.id"),primary_key=True)

class Child(Base):
    __tablename__="child"
    id=sa.Column(sa.Integer,primary_key=True)
    name=sa.Column(sa.String)
    schools=relationship("School",secondary=ChildSchool.__table__,backref="children")

class School(Base):
    __tablename__="schools"
    id=sa.Column(sa.Integer,primary_key=True)
    name=sa.Column(sa.String)

session=Session()
sub=session.query(sa.func.json_object_agg(Child.name,Child.id).label('names'),sa.func.max(Child.id).label('id')).subquery(with_labels=True)

childs=session.query(sub).join(Child,sub.c.id==Child.id).join(Child.schools).add_entity(Child).options(contains_eager(Child.schools)).all()
print(len(childs))
```
As there's only one row returned in the subquery , the length of childs should be 1.But the script prints 2. And if 

> sa.func.json_object_agg(Child.name,Child.id).label('names') 

is removed and the subquery is replaced by 
```python
sub=session.query(sa.func.max(Child.id).label('id')).subquery(with_labels=True)
```
Then the script print 1 normally. 
This anomaly can also be reproduced on mysql using json_objectagg function instead.

data in these three tables are 
```sql
postgres=# select id ,name from child;
 id |     name      
----+---------------
  1 | Ben Lindley
  2 | Kate Green
  5 | Billy Green
  3 | Cathy McMaine
(4 rows)
postgres=# select id,name from schools;
 id |             name              
----+-------------------------------
  1 | new_york_municipal_elementary
  2 | los_angeles_riverside_middle
(2 rows)
postgres=# select child_id,school_id from child_school_associations;
 child_id | school_id 
----------+-----------
        1 |         1
        1 |         2
        2 |         1
        2 |         2
        3 |         1
        3 |         2
        5 |         1
        5 |         2
(8 rows)

```

**Comment by CaselIT** [comment]
The example you provided produces these queries:
with `json_object_agg`
```sql
SELECT
  anon_1.names AS anon_1_names,
  anon_1.id AS anon_1_id,
  schools.id AS schools_id,
  schools.name AS schools_name,
  child.id AS child_id,
  child.name AS child_name
FROM (SELECT
  json_object_agg(child.name, child.id) AS names,
  MAX(child.id) AS id
FROM child) AS anon_1
JOIN child
  ON anon_1.id = child.id
JOIN child_school_associations AS child_school_associations_1
  ON child.id = child_school_associations_1.child_id
JOIN schools
  ON schools.id = child_school_associations_1.school_id
```
without 
```sql
SELECT
  anon_1.id AS anon_1_id,
  schools.id AS schools_id,
  schools.name AS schools_name,
  child.id AS child_id,
  child.name AS child_name
FROM (SELECT
  MAX(child.id) AS id
FROM child) AS anon_1
JOIN child
  ON anon_1.id = child.id
JOIN child_school_associations AS child_school_associations_1
  ON child.id = child_school_associations_1.child_id
JOIN schools
  ON schools.id = child_school_associations_1.school_id
```

Both of there queries are returning two rows, since the `child_school_associations ` has 2 rows with the `child_school_associations `.

I guess that the session does not compares the dict in the case of `json_object_agg`, so it does not makes the rows unique.
Note that the correct behavior should be the one that returns two rows, and I think that the automatic unique of the rows is going away in the future. Maybe @zzzeek  has more insight on this

Since you are using postgres, you can used `DISTINCT ON` the child id, by adding ` .distinct(Child.id)` to the query. I don't know if this query can work on mysql since, on pg at least, distinct with a json column gives an error

**Comment by zzzeek** [comment]
once you add that entity Child, the ORM query starts uniquing the rows against primary key identity as they come in.  this is strictly to support SQLAlchemy's "joined eager loading" feature which you probably aren't even using here, and this whole behavior is going away in 2.0: https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#uniquifying-orm-rows

**Comment by IterableTrucks** [comment]
> The example you provided produces these queries:
> with `json_object_agg`
> 
> ```sql
> SELECT
>   anon_1.names AS anon_1_names,
>   anon_1.id AS anon_1_id,
>   schools.id AS schools_id,
>   schools.name AS schools_name,
>   child.id AS child_id,
>   child.name AS child_name
> FROM (SELECT
>   json_object_agg(child.name, child.id) AS names,
>   MAX(child.id) AS id
> FROM child) AS anon_1
> JOIN child
>   ON anon_1.id = child.id
> JOIN child_school_associations AS child_school_associations_1
>   ON child.id = child_school_associations_1.child_id
> JOIN schools
>   ON schools.id = child_school_associations_1.school_id
> ```
> 
> without
> 
> ```sql
> SELECT
>   anon_1.id AS anon_1_id,
>   schools.id AS schools_id,
>   schools.name AS schools_name,
>   child.id AS child_id,
>   child.name AS child_name
> FROM (SELECT
>   MAX(child.id) AS id
> FROM child) AS anon_1
> JOIN child
>   ON anon_1.id = child.id
> JOIN child_school_associations AS child_school_associations_1
>   ON child.id = child_school_associations_1.child_id
> JOIN schools
>   ON schools.id = child_school_associations_1.school_id
> ```
> 
> Both of there queries are returning two rows, since the `child_school_associations ` has 2 rows with the `child_id == 5`.
> 
> I guess that the session does not compare the dict in the case of `json_object_agg`, so it does not makes the rows unique.
> Note that the correct behavior should be the one that returns two rows, and I think that the automatic unique of the rows is going away in the future. Maybe @zzzeek has more insight on this
> 
> Since you are using postgres, you can use `DISTINCT ON` the child id, by adding ` .distinct(Child.id)` to the query. I don't know if this query can work on mysql since, on pg at least, distinct with a json column gives an error

**Comment by IterableTrucks** [comment]
> The example you provided produces these queries:
> with `json_object_agg`
> 
> ```sql
> SELECT
>   anon_1.names AS anon_1_names,
>   anon_1.id AS anon_1_id,
>   schools.id AS schools_id,
>   schools.name AS schools_name,
>   child.id AS child_id,
>   child.name AS child_name
> FROM (SELECT
>   json_object_agg(child.name, child.id) AS names,
>   MAX(child.id) AS id
> FROM child) AS anon_1
> JOIN child
>   ON anon_1.id = child.id
> JOIN child_school_associations AS child_school_associations_1
>   ON child.id = child_school_associations_1.child_id
> JOIN schools
>   ON schools.id = child_school_associations_1.school_id
> ```
> 
> without
> 
> ```sql
> SELECT
>   anon_1.id AS anon_1_id,
>   schools.id AS schools_id,
>   schools.name AS schools_name,
>   child.id AS child_id,
>   child.name AS child_name
> FROM (SELECT
>   MAX(child.id) AS id
> FROM child) AS anon_1
> JOIN child
>   ON anon_1.id = child.id
> JOIN child_school_associations AS child_school_associations_1
>   ON child.id = child_school_associations_1.child_id
> JOIN schools
>   ON schools.id = child_school_associations_1.school_id
> ```
> 
> Both of there queries are returning two rows, since the `child_school_associations ` has 2 rows with the `child_id == 5`.
> 
> I guess that the session does not compare the dict in the case of `json_object_agg`, so it does not makes the rows unique.
> Note that the correct behavior should be the one that returns two rows, and I think that the automatic unique of the rows is going away in the future. Maybe @zzzeek has more insight on this
> 
> Since you are using postgres, you can use `DISTINCT ON` the child id, by adding ` .distinct(Child.id)` to the query. I don't know if this query can work on mysql since, on pg at least, distinct with a json column gives an error

```python
childs=session.query(sub).join(Child,sub.c.id==Child.id).distinct(Child.id).join(Child.schools).add_entity(Child).options(contains_eager(Child.schools)).all()
```
Adding an additional distinct on child.id will dismiss one school in the query result where the sql emitted is 
```sql
SELECT DISTINCT ON (child.id) anon_1.names AS anon_1_names, anon_1.id AS anon_1_id, schools.id AS schools_id, schools.name AS schools_name, child.id AS child_id, child.name AS child_name 
FROM (SELECT json_object_agg(child.name, child.id) AS names, max(child.id) AS id 
FROM child) AS anon_1 JOIN child ON anon_1.id = child.id JOIN child_school_associations AS child_school_associations_1 ON child.id = child_school_associations_1.child_id JOIN schools ON schools.id = child_school_associations_1.school_id
```

**Comment by CaselIT** [comment]
Yes, it seems you are right.

Out of curiosity, what is the use case that you are using this query for?

**Comment by zzzeek** [comment]
so... you *Iike* the deduping, or you *dont* like it?   it's easy to dedupe a result that is not deduped if that's what you want. Otherwise, this is the same issue as #4395, which is in the queue.

**Comment by IterableTrucks** [comment]
I'm  confused why the number of collections returned is different after I add "json_objectagg" function in subquery. It is expected that the length of collections should be same as the scenario where there's only "max" function in the subquery.

**Comment by zzzeek** [comment]
if you turn on echo='debug' that woudl show you all the result rows returned for each SQL, do you need help understanding what the database is doing?

**Comment by IterableTrucks** [comment]
this is the output of debug logs when using json_object_agg:

> 2020-04-26 13:58:05,185 INFO sqlalchemy.engine.base.Engine select version()
2020-04-26 13:58:05,185 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:58:05,185 DEBUG sqlalchemy.engine.base.Engine Col ('version',)
2020-04-26 13:58:05,185 DEBUG sqlalchemy.engine.base.Engine Row ('PostgreSQL 11.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit',)
2020-04-26 13:58:05,186 INFO sqlalchemy.engine.base.Engine select current_schema()
2020-04-26 13:58:05,186 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:58:05,186 DEBUG sqlalchemy.engine.base.Engine Col ('current_schema',)
2020-04-26 13:58:05,186 DEBUG sqlalchemy.engine.base.Engine Row ('public',)
2020-04-26 13:58:05,187 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-04-26 13:58:05,187 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:58:05,187 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-04-26 13:58:05,187 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:58:05,188 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2020-04-26 13:58:05,188 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:58:05,188 DEBUG sqlalchemy.engine.base.Engine Col ('standard_conforming_strings',)
2020-04-26 13:58:05,188 DEBUG sqlalchemy.engine.base.Engine Row ('on',)
2020-04-26 13:58:05,188 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-04-26 13:58:05,189 INFO sqlalchemy.engine.base.Engine SELECT anon_1.names AS anon_1_names, anon_1.id AS anon_1_id, schools.id AS schools_id, schools.name AS schools_name, child.id AS child_id, child.name AS child_name 
FROM (SELECT json_object_agg(child.name, child.id) AS names, max(child.id) AS id 
FROM child) AS anon_1 JOIN child ON anon_1.id = child.id JOIN child_school_associations AS child_school_associations_1 ON child.id = child_school_associations_1.child_id JOIN schools ON schools.id = child_school_associations_1.school_id
2020-04-26 13:58:05,189 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:58:05,190 DEBUG sqlalchemy.engine.base.Engine Col ('anon_1_names', 'anon_1_id', 'schools_id', 'schools_name', 'child_id', 'child_name')
2020-04-26 13:58:05,191 DEBUG sqlalchemy.engine.base.Engine Row ({'Ben Lindley': 1, 'Kate Green': 2, 'Billy Green': 5, 'Cathy McMaine': 3}, 5, 1, 'new_york_municipal_elementary', 5, 'Billy Green')
2020-04-26 13:58:05,191 DEBUG sqlalchemy.engine.base.Engine Row ({'Ben Lindley': 1, 'Kate Green': 2, 'Billy Green': 5, 'Cathy McMaine': 3}, 5, 2, 'los_angeles_riverside_middle', 5, 'Billy Green')
2

And the output when I removed json_object_add and left max function only:

> 2020-04-26 13:59:24,850 INFO sqlalchemy.engine.base.Engine select version()
2020-04-26 13:59:24,850 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:59:24,851 DEBUG sqlalchemy.engine.base.Engine Col ('version',)
2020-04-26 13:59:24,851 DEBUG sqlalchemy.engine.base.Engine Row ('PostgreSQL 11.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit',)
2020-04-26 13:59:24,851 INFO sqlalchemy.engine.base.Engine select current_schema()
2020-04-26 13:59:24,851 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:59:24,851 DEBUG sqlalchemy.engine.base.Engine Col ('current_schema',)
2020-04-26 13:59:24,851 DEBUG sqlalchemy.engine.base.Engine Row ('public',)
2020-04-26 13:59:24,852 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-04-26 13:59:24,852 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:59:24,852 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-04-26 13:59:24,852 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:59:24,852 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2020-04-26 13:59:24,852 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:59:24,852 DEBUG sqlalchemy.engine.base.Engine Col ('standard_conforming_strings',)
2020-04-26 13:59:24,853 DEBUG sqlalchemy.engine.base.Engine Row ('on',)
2020-04-26 13:59:24,853 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-04-26 13:59:24,854 INFO sqlalchemy.engine.base.Engine SELECT anon_1.id AS anon_1_id, schools.id AS schools_id, schools.name AS schools_name, child.id AS child_id, child.name AS child_name 
FROM (SELECT max(child.id) AS id 
FROM child) AS anon_1 JOIN child ON anon_1.id = child.id JOIN child_school_associations AS child_school_associations_1 ON child.id = child_school_associations_1.child_id JOIN schools ON schools.id = child_school_associations_1.school_id
2020-04-26 13:59:24,854 INFO sqlalchemy.engine.base.Engine {}
2020-04-26 13:59:24,855 DEBUG sqlalchemy.engine.base.Engine Col ('anon_1_id', 'schools_id', 'schools_name', 'child_id', 'child_name')
2020-04-26 13:59:24,855 DEBUG sqlalchemy.engine.base.Engine Row (5, 1, 'new_york_municipal_elementary', 5, 'Billy Green')
2020-04-26 13:59:24,855 DEBUG sqlalchemy.engine.base.Engine Row (5, 2, 'los_angeles_riverside_middle', 5, 'Billy Green')
1

**Comment by zzzeek** [comment]
OK here is your SQL without the extra column, where I've added padding to show where the column should go:

```
SELECT                               anon_1.id AS anon_1_id, schools.id AS schools_id, schools.name AS schools_name, child.id AS child_id, child.name AS child_name
FROM 
	(SELECT                                                 max(child.id) AS id FROM child) AS anon_1 
JOIN child ON anon_1.id = child.id 
JOIN child_school_associations AS child_school_associations_1 ON child.id = child_school_associations_1.child_id JOIN schools ON schools.id = child_school_associations_1.school_id

```

here it is with it, the SQL is identical except for the addition of the column you are specifying:

```
SELECT anon_1.names AS anon_1_names, anon_1.id AS anon_1_id, schools.id AS schools_id, schools.name AS schools_name, child.id AS child_id, child.name AS child_name
FROM 
	(SELECT json_object_agg(child.name, child.id) AS names, max(child.id) AS id FROM child) AS anon_1 
JOIN child ON anon_1.id = child.id 
JOIN child_school_associations AS child_school_associations_1 ON child.id = child_school_associations_1.child_id JOIN schools ON schools.id = child_school_associations_1.school_id

```

I see nothing unexpected about these queries, they appear to be exactly the SQL you are asking for.  the "Row" you see coming back is what your PosgreSQL database is giving you for each query.    Where is SQLAlchemy doing something incorrectly here?

**Comment by zzzeek** [comment]
Also as stated before, the ORM returns only one row with the second subuqery because the ORM will currently apply uniquing to all rows that contain a full entity such as a Child object.    With the first subquery, the rows are:

`[({'Ben Lindley': 1, 'Kate Green': 2, 'Billy Green': 5, 'Cathy McMaine': 3}, 5, <__main__.Child object at 0x7f77db1e2390>), ({'Ben Lindley': 1, 'Kate Green': 2, 'Billy Green': 5, 'Cathy McMaine': 3}, 5, <__main__.Child object at 0x7f77db1e2390>)]

`with the second, the JSON column is removed and the single row that you get back is:

`[(5, <__main__.Child object at 0x7febd1c34fd0>)]
`
if the uniquing were not applied, you'd get:

`[(5, <__main__.Child object at 0x7febd1c34fd0>), (5, <__main__.Child object at 0x7febd1c34fd0>)]
`

the uniquing by default goes away in SQLAlchemy 2.0 and in 1.4 you will be able to bypass it as part of  #4395 .

**Comment by zzzeek** [comment]
runnable MCVE for reference

```
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker, relationship, contains_eager
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class ChildSchool(Base):
    __tablename__ = "child_school_associations"
    child_id = sa.Column(
        sa.Integer, sa.ForeignKey("child.id"), primary_key=True
    )
    school_id = sa.Column(
        sa.Integer, sa.ForeignKey("schools.id"), primary_key=True
    )


class Child(Base):
    __tablename__ = "child"
    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.String)
    schools = relationship(
        "School", secondary=ChildSchool.__table__, backref="children"
    )


class School(Base):
    __tablename__ = "schools"
    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.String)


engine = sa.create_engine(
    "postgresql://scott:tiger@localhost/test", echo="debug"
)
Session = sessionmaker(bind=engine)
Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)
with engine.begin() as conn:
    conn.execute(
        Child.__table__.insert(),
        [
            {"id": 1, "name": "Ben Lindley"},
            {"id": 2, "name": "Kate Green"},
            {"id": 5, "name": "Billy Green"},
            {"id": 3, "name": "Cathy McMaine"},
        ],
    )
    conn.execute(
        School.__table__.insert(),
        [
            {"id": 1, "name": "new_york_municipal_elementary"},
            {"id": 2, "name": "los_angeles_riverside_middle"},
        ],
    )

    conn.execute(
        ChildSchool.__table__.insert(),
        [
            {"child_id": cid, "school_id": sid}
            for cid, sid in [
                (1, 1),
                (1, 2),
                (2, 1),
                (2, 2),
                (3, 1),
                (3, 2),
                (5, 1),
                (5, 2),
            ]
        ],
    )

session = Session()
sub = session.query(
    sa.func.json_object_agg(Child.name, Child.id).label("names"),
    sa.func.max(Child.id).label("id"),
).subquery(with_labels=True)

# sub=session.query(sa.func.max(Child.id).label('id')).subquery(with_labels=True)

childs = (
    session.query(sub)
    .join(Child, sub.c.id == Child.id)
    .join(Child.schools)
    .add_entity(Child)
    .options(contains_eager(Child.schools))
    .all()
)
print(childs)
#print(len(childs))

```

**Comment by IterableTrucks** [comment]
@zzzeek thx for the explanation of uniqueness. I will pay carefulness until v1.4 is released

**Comment by IterableTrucks** [comment]
@zzzeek By the way, will the deduping feature be applied when using json_object_agg in the subquery? I hope the result can be one entity with two rows which is the case of using max only.

**Comment by zzzeek** [comment]
if you have two rows and one of the elements in each row is different, by definition these two rows are not idententical so a deduping will preserve the two rows.  

within these two rows, if you have an ORM entity in each one, if each row represents the same object identity, (the primary key), then they will be the same Python object, if that's what you mean.    this is the "identity map" introduced in the first paragraph at https://docs.sqlalchemy.org/en/13/orm/session_basics.html#what-does-the-session-do .
