### ISSUE TITLE
[suggestion] about sqlalchemy doc

### ISSUE THREAD

**Issue by MonkandMonkey** [sqlalchemy/sqlalchemy#5261]
I'm learning through reading your well-designed and friendly docs. 
May I raise 2 suggestions here?

* The web page is a bit wide, which makes it harder to read and to focus on for long time.
* Could you plz support copy interactive python code directly without leading dots (...) and (>>>)?
<img width="672" alt="Screen Shot 2020-04-17 at 9 52 44 AM" src="https://user-images.githubusercontent.com/16662997/79523660-4a193280-8091-11ea-9f6d-216ace854326.png">

Thanks for the great work!

**Comment by zzzeek** [comment]
hi there -

web page width:   please feel free to propose changes to https://github.com/sqlalchemyorg/sqlalchemyorg/blob/master/_scss/site.scss, if you provide a PR I can try things out.

copy interactive thing:   I have no idea how to do that, I'm not a web designer.    if you can provide a minimalistic CSS based system to allow that to be possible we can add a filter or somesuch, that would have to be implemented in zzzeeksphinx somewhere similar to here: https://github.com/sqlalchemyorg/zzzeeksphinx/blob/master/zzzeeksphinx/sqlformatter.py  but if you can provide the HTML/CSS technique to make that possible that's what I'd need.

thanks!

**Comment by zzzeek** [comment]
I don't quite get the "width" part, the web page just grows to fit the browser window.    I took this practice from MySQL's docs at https://dev.mysql.com/doc/refman/8.0/en/server-components.html .   so my curiousity is,   1. does MySQL's doc page also seem "too wide"?  and 2. if not, what am I missing in SQLAlchemy's layout that makes it different from MySQL, given that both sites expand the width of the docs to fit the browser window ?

**Comment by zzzeek** [comment]
slightly bigger border on MySQL's site?  that's all I can see.

**Comment by MonkandMonkey** [comment]
Here is an example to illustrate its width (comparing with Flask doc)
<img width="1662" alt="sqlalchemy" src="https://user-images.githubusercontent.com/16662997/79626738-fb3ccd00-8164-11ea-8982-cf783f1f0a2a.png">
<img width="1680" alt="flask" src="https://user-images.githubusercontent.com/16662997/79626743-00018100-8165-11ea-9dad-319155f4a7bd.png">

**Comment by zzzeek** [comment]
a fixed width is very different from a flexible width and I changed to flexible width long ago to suit more screens and browsers.  again I am basing this off of a very high profile site that has a lot more traffic than flask so again please tell me what's wrong with https://dev.mysql.com/doc/refman/8.0/en/server-components.html and what SQLAlchemy is doing differently, thanks

**Comment by zzzeek** [comment]
moving issues to sqlalchemyorg, please continue discussion on either of these issues, thanks!    

https://github.com/sqlalchemyorg/sqlalchemyorg/issues/6

https://github.com/sqlalchemyorg/sqlalchemyorg/issues/7
