### ISSUE TITLE
SQLAlchemy raises error when inserting Postgres array of enum column

### ISSUE THREAD

**Issue by HamishLacmane** [sqlalchemy/sqlalchemy#5265]
I opened the following with Expected Behaviour, Actual behaviour, Stacktrace, MVCE, versions and all info on stackoverflow but haven't got a response. I did see a developer of this did edit my post to make it more suitable and jsut want to bring this potential bug to your attention :)
https://stackoverflow.com/questions/61224799/sqlalchemy-raises-error-when-inserting-postgres-array-of-enum-column

Python version: 3.8.2

**Comment by CaselIT** [comment]
There seem to be two bugs here:
- The first one is the missing cast in an array of native enums
- The second one is the wrong constraint generation when using `native_enums=False` inside an array

**Comment by zzzeek** [comment]
can we create two distinct issues with descriptions and succinct MCVEs here, thanks.

**Comment by HamishLacmane** [comment]
would you like me to do it or are one of you happy to do so?

**Comment by CaselIT** [comment]
Please feel free. Probably we can use this to track the problem with native enum and a new one for the other case?

**Comment by HamishLacmane** [comment]
Use this one to track the one with the inserting issue please

native_enum inside array issue is:
https://github.com/sqlalchemy/sqlalchemy/issues/5266

hope this helps

**Comment by CaselIT** [comment]
I was not aware of it, but the documentation already contains the solution:
https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#using-enum-with-array

Ideally it should be handled automatically, but that solution works as expected

**Comment by CaselIT** [comment]
@zzzeek should we maybe make the array aware of this and change its implementation if it's internal type is an enum (and also in case of json/jsonb that also has a workaround?)

**Comment by zzzeek** [comment]
for the INSERT issue, use of ARRAY with ENUM is documented here and requires use of a custom type:

https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#using-enum-with-array

so same as #5266 there are special steps documented for this unusual use case right now.

**Comment by CaselIT** [comment]
> 
> 
> @zzzeek should we maybe make the array aware of this and change its implementation if it's internal type is an enum (and also in case of json/jsonb that also has a workaround?)

With this I mean something like this added to the PG array class

```py
    def __new__(
        cls, item_type, as_tuple=False, dimensions=None, zero_indexes=False
    ):
        item_type = type_api.to_instance(item_type)
        if isinstance(item_type, sqltypes.JSON):
            type_ = CastingArray
        elif isinstance(item_type, sqltypes.Enum) and item_type.native_enum:
            type_ = ArrayOfEnum
        else:
            type_ = ARRAY
        instance = super().__new__(type_)
        type_.__init__(instance, item_type, as_tuple, dimensions, zero_indexes)
        return instance
```

**Comment by zzzeek** [comment]
right now the PG ARRAY class is not used at the time that you'd want it to.   Here's a patch that hits both use cases.   we can have one gerrit that closes both issues.

```diff

diff --git a/lib/sqlalchemy/dialects/postgresql/array.py b/lib/sqlalchemy/dialects/postgresql/array.py
index a3537ba60..8bf0688df 100644
--- a/lib/sqlalchemy/dialects/postgresql/array.py
+++ b/lib/sqlalchemy/dialects/postgresql/array.py
@@ -7,10 +7,12 @@
 
 from .base import colspecs
 from .base import ischema_names
+from .base import ENUM
 from ... import types as sqltypes
 from ...sql import expression
 from ...sql import operators
-
+from ... import util
+import re
 
 try:
     from uuid import UUID as _python_UUID  # noqa
@@ -318,6 +320,22 @@ class ARRAY(sqltypes.ARRAY):
                 for x in arr
             )
 
+    @util.memoized_property
+    def _against_native_enum(self):
+        if (
+            isinstance(self.item_type, sqltypes.Enum)
+            and self.item_type.native_enum
+        ) or isinstance(self.item_type, ENUM):
+            return True
+        else:
+            return False
+
+    def bind_expression(self, bindvalue):
+        if self._against_native_enum:
+            return expression.cast(bindvalue, self)
+        else:
+            return bindvalue
+
     def bind_processor(self, dialect):
         item_proc = self.item_type.dialect_impl(dialect).bind_processor(
             dialect
@@ -349,6 +367,18 @@ class ARRAY(sqltypes.ARRAY):
                     tuple if self.as_tuple else list,
                 )
 
+        if self._against_native_enum:
+            super_rp = process
+
+            def handle_raw_string(value):
+                inner = re.match(r"^{(.*)}$", value).group(1)
+                return inner.split(",") if inner else []
+
+            def process(value):
+                if value is None:
+                    return None
+                return super_rp(handle_raw_string(value))
+
         return process
 
 
diff --git a/lib/sqlalchemy/dialects/postgresql/base.py b/lib/sqlalchemy/dialects/postgresql/base.py
index d388b460c..30e4ccd1f 100644
--- a/lib/sqlalchemy/dialects/postgresql/base.py
+++ b/lib/sqlalchemy/dialects/postgresql/base.py
@@ -1920,6 +1920,22 @@ class PGDDLCompiler(compiler.DDLCompiler):
             colspec += " NOT NULL"
         return colspec
 
+    def visit_check_constraint(self, constraint):
+        if constraint._type_bound:
+            typ = list(constraint.columns)[0].type
+            if (
+                isinstance(typ, sqltypes.ARRAY)
+                and isinstance(typ.item_type, sqltypes.Enum)
+                and not typ.item_type.native_enum
+            ):
+                raise exc.CompileError(
+                    "PostgreSQL dialect cannot produce the CHECK constraint "
+                    "for ARRAY of non-native ENUM; please specify "
+                    "create_constraint=False on this Enum datatype."
+                )
+
+        return super(PGDDLCompiler, self).visit_check_constraint(constraint)
+
     def visit_drop_table_comment(self, drop):
         return "COMMENT ON TABLE %s IS NULL" % self.preparer.format_table(
             drop.element
diff --git a/lib/sqlalchemy/dialects/postgresql/psycopg2.py b/lib/sqlalchemy/dialects/postgresql/psycopg2.py
index e17749933..a27cd4969 100644
--- a/lib/sqlalchemy/dialects/postgresql/psycopg2.py
+++ b/lib/sqlalchemy/dialects/postgresql/psycopg2.py
@@ -466,6 +466,7 @@ from .base import PGDialect
 from .base import PGExecutionContext
 from .base import PGIdentifierPreparer
 from .base import UUID
+from . import array
 from .hstore import HSTORE
 from .json import JSON
 from .json import JSONB
@@ -665,6 +666,7 @@ class PGDialect_psycopg2(PGDialect):
     colspecs = util.update_copy(
         PGDialect.colspecs,
         {
+            sqltypes.ARRAY: array.ARRAY,
             sqltypes.Numeric: _PGNumeric,
             ENUM: _PGEnum,  # needs force_unicode
             sqltypes.Enum: _PGEnum,  # needs force_unicode

```

**Comment by zzzeek** [comment]
for the docs, we update the doc section at  https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#using-enum-with-array to mention in 1.3.17 this isnt' needed anymore but for prior versions here's the workaround

**Comment by zzzeek** [comment]
doesn't need the ARRAY colspecs part apparently, though it is unsual that array.py adds itself to colspecs, this should just be straight in the postgresql/base.py module

**Comment by CaselIT** [comment]
was setup like this by https://github.com/sqlalchemy/sqlalchemy/commit/1b463058e3282c73d0fb361f78e96ecaa23ce9f4

**Comment by CaselIT** [comment]
Also why this or `or isinstance(self.item_type, ENUM):`?

It's already covered by the previous check

**Comment by CaselIT** [comment]
> doesn't need the ARRAY colspecs part apparently, though it is unsual that array.py adds itself to colspecs, this should just be straight in the postgresql/base.py module

json.py seems to do the same.

**Comment by zzzeek** [comment]
They can specify postgresql.ENUM directly , does that include native_enum = True?

basically the test should have all four combinations of the sqltypes / postgresql versions of ARRAY and ENUM and ensure that full create + INSERT + SELECT + fetch results work.

**Comment by zzzeek** [comment]
> > doesn't need the ARRAY colspecs part apparently, though it is unsual that array.py adds itself to colspecs, this should just be straight in the postgresql/base.py module
> 
> json.py seems to do the same.

this has to be circular import stuff and maybe only breaks in python 2 kind of thing

**Comment by CaselIT** [comment]
> They can specify postgresql.ENUM directly , does that include native_enum = True?

Yes, since it's an Enum subclass, and I don't see anything that omits it

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Support `ARRAY` of `Enum`, `JSON` or `JSONB`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1902

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Support `ARRAY` of `Enum`, `JSON` or `JSONB`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1905
