### ISSUE TITLE
custom port selection broken for mysql using both mysql and mysql+pymysql

### ISSUE THREAD

**Issue by daliagachc** [sqlalchemy/sqlalchemy#5267]
hi, 
custom port selection is not used when using the following code: 
``` python
sqlEngine       = create_engine('mysql://user:pass@host:3333/database')

dbConnection    = sqlEngine.connect()
```
or 

``` python
sqlEngine       = create_engine('mysql+pysql://user:pass@host:3333/database')

dbConnection    = sqlEngine.connect()
```

basically it tries to connect to port 3336. How can i force the usage of a common port?

**Comment by zzzeek** [comment]
no known issue w/ port selection in SQLAlchemy MySQL diaelcts, we use custom ports in Openstack w MySQL drivers regularly.    Also, MySQL's default port is 3306, not 3336, if that is in fact the port you are observing then you want to see if you have some kind of proxy server in place or perhaps you have a .my.cnf file in your home directory that is affecting things.  Also please specify how you are determining what port it is trying to use, thanks.

**Comment by daliagachc** [comment]
Hi!
Yes, you are wright:  MySQL's default port is 3306, not 3336. I made a typo but only here (not in my code).
below it is what I've found. To summarize, I think that the MySQLdb will always use the 3306 regardless of the port you pass to it. mysql+mypysql seems to work as expected. 

``` python
Python 3.6.10 | packaged by conda-forge | (default, Mar  5 2020, 09:56:10) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.13.0
Python 3.6.10 | packaged by conda-forge | (default, Mar  5 2020, 09:56:10) 
[GCC Clang 9.0.1 ] on darwin
from sqlalchemy import create_engine
import sqlalchemy
import pandas as pd
import pymysql
import MySQLdb
sqlalchemy.__version__
Out[3]: '1.3.13'
pymysql.__version__
Out[4]: '0.9.3'
MySQLdb.__version__
Out[5]: '1.4.6'
engines = ['mysql','mysql+pymysql']
# mysql uses MySQLdb
# mysql+pymysql use pymysql
ports = ['3306','3333']
# port 3306 is the correct one
# port 3333 is not correct there is no sql server listening to 3333
for eng in engines:
    for port in ports:
        string = f'{eng}://root:password@localhost:{port}/mysql'
        print(string)
        engine = create_engine(string)
        try:
            res = pd.read_sql_table('user',engine,schema='mysql')['Host']
            print('SUCCES!')
            print(res)
        except Exception as e:
            print('Error')
            print(e)
        finally:
            print('___________________________________')
mysql://root:password@localhost:3306/mysql
SUCCES!
0    localhost
1    127.0.0.1
2          ::1
3            %
Name: Host, dtype: object
___________________________________
mysql://root:password@localhost:3333/mysql
SUCCES!
0    localhost
1    127.0.0.1
2          ::1
3            %
Name: Host, dtype: object
___________________________________
mysql+pymysql://root:password@localhost:3306/mysql
SUCCES!
0    localhost
1    127.0.0.1
2          ::1
3            %
Name: Host, dtype: object
___________________________________
mysql+pymysql://root:password@localhost:3333/mysql
Error
(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
(Background on this error at: http://sqlalche.me/e/e3q8)
___________________________________
```

**Comment by zzzeek** [comment]
OK this is all driver stuff, but when you use "localhost" with MySQL native client libraries, you aren't actually using *any* port, you are using a [unix socket](https://dev.mysql.com/doc/refman/8.0/en/connecting.html):

> Client programs determine what type of connection to make as follows:

  >  If the host is not specified or is localhost, a connection to the local host occurs:

  >      On Unix, MySQL programs treat the host name localhost specially, in a way that is likely different from what you expect compared to other network-based programs: the client connects using a Unix socket file. The --socket option or the MYSQL_UNIX_PORT environment variable may be used to specify the socket name. 


so use the actual IP number of your machine to see it use a TCP/IP connection and therefore the port.

**Comment by zzzeek** [comment]
in fact even the loopback address is sufficient, demonstration:

```
>>> e = create_engine("mysql://scott:tiger@localhost:1234/test")
>>> e.connect()
<sqlalchemy.engine.base.Connection object at 0x7f5d7e470c50>
>>> e = create_engine("mysql://scott:tiger@127.0.0.1:1234/test")
>>> e.connect()
Traceback (most recent call last):
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on '127.0.0.1' (115)")

```

**Comment by daliagachc** [comment]
true! thanks. i guess that this also goes for dns addresses?

**Comment by zzzeek** [comment]
the word "localhost" is the only magic keyword.

**Comment by CaselIT** [comment]
I think this can be closed

**Comment by arfaoui47** [comment]
You can't connect using 127.0.01 because that's using TCP connection implicitly.
