### ISSUE TITLE
add "limiting" feature to warn_deprecated()

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5268]
As mentioned in #5253

**Comment by gordthompson** [comment]
@zzzeek  - Would it make sense to convert

https://github.com/sqlalchemy/sqlalchemy/blob/c61e0265a07e4310e7767fb6f9e0b84d8c89eb71/lib/sqlalchemy/util/langhelpers.py#L1414

to a public class so we don't have to duplicate it in deprecations.py?

**Comment by zzzeek** [comment]
ohhh, we can use it in deprecations.py, this is all within the "util" package, just use it directly no problem!

**Comment by zzzeek** [comment]
obviosuly public/private scope in Python is all do whatever you'd like, this is fine

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add warn_deprecated_limited feature** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1916

**Comment by gordthompson** [comment]
Okay, I stole code from `warn_limited` and created a `warn_deprecated_limited` method, the only thing is that it doesn't limit. I went looking for code that tests `warn_limit` but I couldn't find any. :(

**Comment by zzzeek** [comment]
Here's a test:

```
from sqlalchemy.util.langhelpers import _hash_limit_string


messages = set()

printouts = set()

for i in range(100):
    message = _hash_limit_string("this is a unique message: %d", 10, (i,))
    printouts.add(str(message))
    messages.add(message)

assert len(messages) == 10
assert len(printouts) == 100

```

the test that's there won't prevent that final warning from raising, because we have set the warnings filter to "error" meaning it raises everytime.

The specific thing we're trying to block here is this collection that Python's warnings filter uses when the filter says "once", which is the default.

Run this program and then watch the memory usage in another window:


```
import warnings


i = 1
while True:
    warnings.warn("this is a warning, that your memory is growing unbounded!!  %d" % i)
    i += 1


```

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Add warn_deprecated_limited feature** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1942
