### ISSUE TITLE
index.create should take checkfirst argument as table.create does.

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#527]
**Migrated issue, originally created by Anonymous**

Creating indexes is often done in a comparable way to creating tables.  We
use table.create(checkfirst=True) often and it would be helpful/symetrical to 
have that on indexes also.

**Comment by zzzeek** [comment]
this is crazy.  there is a checkfirst argument to:  Table.create, Sequence.create, postgresql.ENUM.create.     let's just get the basic flag in there and not worry about anything in ddl.py

**Comment by zzzeek** [comment]
well to be fair, Sequence and ENUM both have systems of integrating checkfirst into the ddl sequence, Sequence has SchemaGenerator._can_create_sequence and ENUM has _check_for_name_in_memos.  But what is special about Sequence / ENUM is that they can be used multiple times, they are independent of tables that use them.   So again, we can add index.checkfirst but not worry about the kinds of things Sequence/ENUM are doing.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement checkfirst for Index.create(), Index.drop()** https://gerrit.sqlalchemy.org/1398
