### ISSUE TITLE
From subqueryload to selectinload

### ISSUE THREAD

**Issue by ilannn** [sqlalchemy/sqlalchemy#5270]
Hello there!

I'm looking for any reason why switching from the `subqueryload` strategy to `selectinlaod` ensures that relations are loaded correctly and predictably.

Any direction to look into will be much appreciated!

**Comment by CaselIT** [comment]
Not sure I understand the question.Both of these loading method should provide the same result, if they don't then I guess there is a bug somewhere.

What changes is the sql queries that are generated to load the objects

**Comment by uinvent** [comment]
Hi 
I hope this will lead you to the right direction.

Below link explains the sensitivity of sub-query.
[https://docs.sqlalchemy.org/en/13/faq/ormconfiguration.html#faq-subqueryload-limit-sort
](url)

Where as,
Select IN loading is similar in operation to subquery eager loading, however the SELECT statement which is emitted has a much simpler structure than that of subquery eager loading. Additionally, select IN loading applies itself to subsets of the load result at a time, so unlike joined and subquery eager loading, is compatible with batching of results using Query.yield_per(), provided the database driver supports simultaneous cursors.

Reference
https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html#select-in-loading

**Comment by CaselIT** [comment]
It's surely my fault, but I still don't understand what the question is, sorry.

**Comment by uinvent** [comment]
As per my understanding; @ilannn claims that subquery load strategy give unreliable query results as compared to selectinload. But he is not sure why!
The links I have shared supports his claim and provides an exact example.

**Comment by zzzeek** [comment]
there can be bugs in subqueryload also and there might even be a few very obscure known issues lurking.   but..without an example we wouldn't know what to look for.

if we want an easy answer to this whole issue whatever it is, selectinload is pretty much way better than subqueryload, and as long as the database in question is capable of emitting the selectinload queries, it's likely the better choice.

**Comment by ilannn** [comment]
Hey everyone! and thank you for the effort to consult on my question.
It's really a pleasure to the receive such a quick response from the community :)

I'll try to explain the issue in more details:
We have a model holding a few relationships. This model is paginated and filtered.
The problem seems to be with one of his relationships. It's a one-to-many relationship, and for an unknown reason, this relation returns us an empty list of results.
I'll note that after calling `object_session(self).expire_all()` on this model, the relationship is then loaded correctly.

Also, this scenario doesn't always happen, and when it does it happens to a different instance of the model.

Unfortunately, due to the information disclosure agreement, I can't publish the models.
But, in case you guys are out of ideas, I'll try to formulate a mock model structure

**Comment by zzzeek** [comment]
is that with your subqueryload or selectinload?   as mentioned above somewhere subuqeryload is a little bit sensitive to pagination type stuff

**Comment by jvanasco** [comment]
> It's a one-to-many relationship, and for an unknown reason, this relation may return an empty list of results for some model instances.

I've experienced similar issues in the past with subqueryload. Each of my problems were all tied to this:  

> This model is paginated and filtered 

Make sure your `order_by` has a deterministic sort order.  It is easy to start paginating and miss a row, ESPECIALLY when filters are involved.  there is a FAQ on this here:

https://docs.sqlalchemy.org/en/13/faq/ormconfiguration.html?highlight=order_by#why-is-order-by-required-with-limit-especially-with-subqueryload

**Comment by ilannn** [comment]
Hey all!

**I believe I got the answer I needed!**
It was indeed all about the non-deterministic results caused by `subqueryload` without a specified order.
Switching to `selectinload` fixed it by removing the order factor and matching results by their PK.

Thank you all for the help! It's much appreciated!

And @uinvent & @jvanasco for sending the relevant reading material 🙏
