### ISSUE TITLE
SQL Server 2010 Reflecting MetaData Issue

### ISSUE THREAD

**Issue by Paulos1993** [sqlalchemy/sqlalchemy#5271]
Hello,

When using the table function or MetaData function, CONCAT is used in the underlying sql and this is not support for pre 2012 ver of SQL server.

**Comment by CaselIT** [comment]
This is connected to the new functionality to reflect computed columns added in 1.3.16

https://github.com/sqlalchemy/sqlalchemy/blob/ec810befe3cd80e366909912ae421e46fa58fd50/lib/sqlalchemy/dialects/mssql/base.py#L2694-L2697

What do you use as an alternative to concat in mssql pre 2012?

**Comment by gordthompson** [comment]
> What do you use as an alternative to concat in mssql pre 2012?

Probably just the `+` operator.

**Comment by gordthompson** [comment]
@Paulos1993 - What do you get when you `select @@version`?

**Comment by CaselIT** [comment]
Ok, I'll probably add this to the patch https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1894

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fix regression when reflecting tables in MSSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1894

**Comment by zzzeek** [comment]
Do we have confirmation from MSSQL documentation that CONCAT is not on < 2012 and the text concatenation operator is?

**Comment by zzzeek** [comment]
at least the latter part.

**Comment by gordthompson** [comment]
It's not official Microsoft documentation, but there's this:

https://stackoverflow.com/q/10550307/2144390

**Comment by CaselIT** [comment]
The `+` on the columns renders as `||` not as `+`

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix regression when reflecting tables in MSSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1912
