### ISSUE TITLE
AttributeError preventing update to 1.3.16

### ISSUE THREAD

**Issue by jbgordon85** [sqlalchemy/sqlalchemy#5274]
I have v1.3.15, and am attempting to upgrade to 1.3.16 using pip.  I'm running SQLAlchemy in a virtual environment that has Python 3.5.1.  And I've been using it for years, and upgrading regularly without issue until now.  (The Python in my system's /usr/bin/python is 2.7.5, in case that matters.)  RHEL 7.8.

When I attempt the update, installing the new version fails because of an "AttributeError", apparently related to my Python distribution.  See output below.

To initiate the update, I enter:
`[me@xxxxxxxx ~]$ /srv/virtualenv/funcgendump_test/bin/pip install --upgrade SQLAlchemy`

And it returns:
> Collecting SQLAlchemy
>   Using cached SQLAlchemy-1.3.16.tar.gz (6.1 MB)
>     ERROR: Command errored out with exit status 1:
>      command: /srv/virtualenv/funcgendump_test/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n3dmqtzo/SQLAlchemy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n3dmqtzo/SQLAlchemy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-n3dmqtzo/SQLAlchemy/pip-egg-info
>          cwd: /tmp/pip-install-n3dmqtzo/SQLAlchemy/
>     Complete output (30 lines):
>     Traceback (most recent call last):
>       File "/srv/virtualenv/funcgendump_test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2458, in resolve
>         return functools.reduce(getattr, self.attrs, module)
>     AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-n3dmqtzo/SQLAlchemy/setup.py", line 220, in <module>
>         run_setup(True)
>       File "/tmp/pip-install-n3dmqtzo/SQLAlchemy/setup.py", line 199, in run_setup
>         **kwargs
>       File "/srv/virtualenv/funcgendump_test/lib/python3.5/site-packages/setuptools/__init__.py", line 143, in setup
>         _install_setup_requires(attrs)
>       File "/srv/virtualenv/funcgendump_test/lib/python3.5/site-packages/setuptools/__init__.py", line 132, in _install_setup_requires
>         (k, v) for k, v in attrs.items()
>       File "/srv/virtualenv/funcgendump_test/lib/python3.5/site-packages/setuptools/dist.py", line 426, in __init__
>         k: v for k, v in attrs.items()
>       File "/opt/rh/rh-python35/root/usr/lib64/python3.5/distutils/dist.py", line 281, in __init__
>         self.finalize_options()
>       File "/srv/virtualenv/funcgendump_test/lib/python3.5/site-packages/setuptools/dist.py", line 716, in finalize_options
>         for ep in sorted(eps, key=by_order):
>       File "/srv/virtualenv/funcgendump_test/lib/python3.5/site-packages/setuptools/dist.py", line 715, in <lambda>
>         eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))
>       File "/srv/virtualenv/funcgendump_test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2450, in load
>         return self.resolve()
>       File "/srv/virtualenv/funcgendump_test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2460, in resolve
>         raise ImportError(str(exc))
>     ImportError: type object 'Distribution' has no attribute '_finalize_feature_opts'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 

Pip isn't having trouble updating any other packages of mine, so I assume that my problem here isn't pip's fault.

Let me know if there's any other info I can provide, and thanks for any help you can give!

**Comment by CaselIT** [comment]
Could you also share you pip and setuptools versions?

**Comment by CaselIT** [comment]
I cannot reproduce it with python 3.5 on windows or on linux (docker).

You should probably try to reinstall pip with `pip install -I pip` to ignore the installed packages required by pip

**Comment by jbgordon85** [comment]
pip: 20.0.2
setuptools: 46.1.3

When I run "pip show setuptools", SQLAlchemy is not listed among setuptools' "Required-by" packages.  Should it?

**Comment by jbgordon85** [comment]
I'm sorry, I'm dumb, it IS there with the "Required-by" packages.  "zope.sqlalchemy".

**Comment by jbgordon85** [comment]
> I cannot reproduce it with python 3.5 on windows or on linux (docker).
> 
> You should probably try to reinstall pip with `pip install -I pip` to ignore the installed packages required by pip

Just tried.  No improvement. :-/

**Comment by CaselIT** [comment]
> pip: 20.0.2
setuptools: 46.1.3

Tried with the same versions and they work fine.

Maybe this works:
You can maybe try to create another environment also with python3.5 to check if it installs from there.
If it does, you can create a wheel in this new env using `pip wheel -w dist --no-deps sqlachemy`
This generates a file in the dist folder. You should then be able to install that wheel in you other env using `pip install path-to-wheel`

**Comment by jbgordon85** [comment]
Thanks, this worked!  I don't understand why suddenly I had to do it this way, though.  Do you have any ideas what might happen that would cause this?

**Comment by CaselIT** [comment]
I'm not really sure. It seems that your virtual env got corrupted someway.
Something similar has happened to me, but on windows.

If you can, you can maybe try to replace the env with a newly created one, since I suspect that similar problems may happen also on other libraries.

**Comment by jbgordon85** [comment]
Thanks, this makes sense.  In fact I'm pretty sure I know what event earlier this year could have corrupted my environment(s).  Looks like I've got some rebuilding to do!
