### ISSUE TITLE
Mechanism for external dialect to supersede internal dialect if possible

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5278]
To assist in transitioning from Firebird's internal dialect to the external [sqlalchemy-firebird](https://github.com/pauldex/sqlalchemy-firebird) dialect (and eventually removing the former).

Implement a way for `firebird://` URIs to use the external dialect if it has been installed, otherwise fall back to the internal dialect.

**Comment by zzzeek** [comment]
are we targeting 1.3.x or 1.4 ?

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Enable loading of external Firebird dialect, if available** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1919

**Comment by gordthompson** [comment]
AFAIK the external dialect itself is still okay with 1.3.

**Comment by gordthompson** [comment]
Further to my [note](https://github.com/pauldex/sqlalchemy-firebird/issues/23) to @pauldex, I branched my copy of [sqlalchemy-firebird](https://github.com/pauldex/sqlalchemy-firebird) and did a global search-and-replace for `firebird2` → `firebird`. Then I branched my copy of Gerrit_1919 and renamed the 

`lib/sqlalchemy/dialects/firebird`

folder to 

`lib/sqlalchemy/dialects/_no_more_firebird`

When I ran the suite tests I got 3 failures out of 194 and all three were Firebird-specific tests on the sqlalchemy-firebird side. They were easy to fix.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Enable loading of external Firebird dialect, if available** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1921
