### ISSUE TITLE
WinError 10061

### ISSUE THREAD

**Issue by ZorudaRinku** [sqlalchemy/sqlalchemy#5282]
Hello amazing people. I've been struggling with sqlalchemy for a few weeks now trying to get this error fixed but I just can't do it so I've come to the masters for help. Here is the error I am getting.

> Command raised an exception: OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10061] No connection could be made because the target machine actively refused it)")
(Background on this error at: http://sqlalche.me/e/e3q8)

If you think I'm trying to connect to 127.0.0.1 you'd be **DEAD** wrong.

main.py
`engine = sqlalchemy.create_engine(f'mysql+pymysql://{creds.user}:{creds.dbpassword}@{creds.host}/{creds.database}')`
`logging.info('Running remote instance of MariaDB.')`
`Session = sessionmaker(bind=engine)`

creds.py
`host = "162.251.81.23"`
`port = "3306"`
`user = "NotMyUsername"`
`dbpassword = "NotMyDBPassword"`
`database = "tagetDB"`

I do not have a server set up on my local machine but I used to and the issue was there when the local server was up. This error does not occur on any other projects. I have another project almost exactly the same that has no issue connecting to the remote DB. I also have datagrip from jetbrains that is also able to connect to the remote server. This issue also arises for our other developer as well. Yes port is open. Yes all my information is correct. I hope I've given you all enough information but if not just let me know! 👋

**Comment by ZorudaRinku** [comment]
Soooooooooooo.... Now its working. After 2-3 weeks of not working, I submit 1 ticket and it instantly starts working. I'll leave this issue up for you guys if you want to investigate or have more questions for me if you guys want to close it. 🤦‍♂️

**Comment by CaselIT** [comment]
Hi, It seems that the problem may be in the pymysql side.
SQLAlchemy does not handle the connection directly, but uses the specified dbapi.

Are you able to connect using pymysql directly, without SQLAlchemy?

**Comment by ZorudaRinku** [comment]
Interestingly enough, yes I can connect and execute to the database.

**Comment by CaselIT** [comment]
I'm not really sure there is anything actionable here without a reproducible case.
SQLAlchemy passes the connection information to the underlying dbapi, so connection problems should be investigated in the the dbapi library.

I'm closing this for now, if you can isolate a reproducible case please feel free to reopen
