### ISSUE TITLE
get legacy / future select() to do multiple calling styles

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5284]
I'm a little concerned about how pervasive it will be to make people change all their selects():

    select([a, b, c])
 
    select(a, b, c)

This is a small almost cosmetic thing that is going to be a big block for people who want to migrate to 2.0.  So I think we need to make this flexible and not warn for now:

1. we will use a `__new__()` constructor to make a decision about the first argument

2. both selects (current and future) need to do a quick isinstance(), or `hasattr __iter__`, or soemthing like that, on the first argument, and if it's a sequence, go into "sequence" mode.   Otherwise, we're in positional column arg mode.

3. if columns are sent positionally, then both old select() and new select() should construct in the new way, that is, no keyword arguments, whereclasue, etc. are accepted, the constructor only takes column expresions for the columns clause.

4. if columns are sent as a list in the first argument, for future select(), any remaining arguments should raise an error.  for classic select, they should be interpreted as they always have been.   this includes the super old style where the "whereclause" would have been passed positionally.

5. the only warning should be if one is explicitly using future select and they are sending the array of cols.    all the other forms shouldn't generate a warning.

**Comment by CaselIT** [comment]
I'm actually not sure about points 2 and 3.
I don't think `future.select` should accept the columns as an array, otherwise we either keep it like that or it will need to change again for v2.

I instead agree on old select that can act as a mix of the two, if it detects  a list behaves the old way, if it detects positional columns it acts as a new select

**Comment by zzzeek** [comment]
I think that's OK, the new select() has a killer new feature people are going to want which is that select().join() will actually do what ORM query does.   But, if they are using that new API they should write the select() in the new way.

**Comment by zzzeek** [comment]
also we dont have to use `__new__` we already have a bunch of Select._construct() methods we just add to that.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Propose a single select() construct** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2058
