### ISSUE TITLE
Potential SQLite Foreign Key documentation improvement

### ISSUE THREAD

**Issue by ColdHeat** [sqlalchemy/sqlalchemy#5289]
**Describe you question**
I needed to enforce SQLite foreign keys so I copied the event code referenced in the [documentation](https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#foreign-key-support). However it failed tests (which use in-memory SQLite) because it was placed after `db.create_all()` which cost me some time to debug. I'm not sure if this would be considered a flub on my part or if there's a possible documentation improvement. 

**Have a nice day!**

**Comment by CaselIT** [comment]
Just to be clear, the suggestion is to note that this code should be placed before all other interactions with the db?

If you want to suggest a pr, this is where that documentation is written

https://github.com/sqlalchemy/sqlalchemy/blob/d57767e08b35e4cd18ef57192a1842cc1b4939d4/lib/sqlalchemy/dialects/sqlite/base.py#L249-L297

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Fixes: #5289** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3069
