### ISSUE TITLE
Sybase use START AT clause for offset()

### ISSUE THREAD

**Issue by snowman2** [sqlalchemy/sqlalchemy#5294]
**Is your feature request related to a problem? Please describe.**

Related to: https://github.com/sqlalchemy/sqlalchemy/issues/2278

When attempting to use `offset` with the sybase API I get the error:

```
raise NotImplementedError("Sybase ASE does not support OFFSET")
```

**Describe the solution you'd like**

https://sqlalchemy.narkive.com/lK0j7vV6/sybase-ase-15-7-sqlalchemy-limit-offset-issue

This should be possible with `START AT`

**Describe alternatives you've considered**
Just RAW SQL instead of ORM query method.

**Comment by snowman2** [comment]
Never mind. Seems to not be working. That is unfortunate. Will close unless I find something else.

**Comment by CaselIT** [comment]
the sybase dialect is not really maintained, and it is not tested in the ci, and has been deprecated from version 1.4 onward.

If you where to propose a patch, I think it could be taken into consideration, @zzzeek.

**Comment by snowman2** [comment]
> the sybase dialect is not really maintained, it is not tested in the ci, and has been deprecated from version 1.4 onward.

That's scary :scream: . Will need to keep that in mind.

**Comment by snowman2** [comment]
Ref: #5189 

cc: @kirkhansen @rileymcdowell

**Comment by CaselIT** [comment]
It's not likely to be removed for a number of years yet, at least until version 2.
The reason is that it's not tested as part of the ci, and we currently don't have the resource to keep it up to date.

Ideally, if someone is interested, an external dialect could be created.
Here https://github.com/sqlalchemy/sqlalchemy/issues/5189#issuecomment-615940070 and https://github.com/sqlalchemy/sqlalchemy/issues/5189#issuecomment-616139638 are some link in case you would be interested

**Comment by snowman2** [comment]
cc: @JWCook @justingruca

**Comment by CaselIT** [comment]
I think that in case an external dialect is created we could go the same route of firebird, https://github.com/sqlalchemy/sqlalchemy/issues/5278, detecting it and preferring it to the internal implementation

**Comment by gordthompson** [comment]
@snowman2 - I've been helping get the external Firebird dialect – [sqlalchemy-firebird](https://github.com/pauldex/sqlalchemy-firebird) – off the ground (so to speak), so if you wanted to do something similar for Sybase I could lend a hand. Curious: Which DBAPI are you using? I notice that the most recent release of [python-sybase](https://pypi.org/project/python-sybase/) was twelve (12) years ago.

**Comment by snowman2** [comment]
We are currently using [pyodbc](https://github.com/mkleehammer/pyodbc). Will try to get more info later.

**Comment by snowman2** [comment]
Here is a code snippet to connect to the database with `sybase+odbc`:

```python
import pyodbc
from sqlalchemy import create_engine

connect_args = {"autoconnect": True}
creator = pyodbc.connect(
    database=database,
    user=username,
    password=password,
    driver="FreeTDS",
    host=host,
    port=port),
    **connect_args,
)
engine = create_engine(
    "sybase+pyodbc://",
    creator=creator,
    connect_args=connect_args,
)

**Comment by gordthompson** [comment]
Thanks for the update. If pyodbc and FreeTDS ODBC are working reasonably well for you then that could be the basis for an external Sybase dialect.

**Comment by CaselIT** [comment]
maybe we could reopen and rename the issue to make it more visible and to see if someone else is also interested in the external dialect?

**Comment by gordthompson** [comment]
Re-opening this issue because the internal Sybase dialect **will** be deprecated in 1.4 and removed in 2.0. If SQLAlchemy support is important to Sybase users then it's time for them to step up and implement an external dialect.

**Comment by sqla-tester** [comment]
**snowman2** has proposed a fix for this issue in the **master** branch:

**SYBASE: Added offset support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1955

**Comment by sqla-tester** [comment]
**snowman2** has proposed a fix for this issue in the **rel_1_3** branch:

**SYBASE: Added offset support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1956
