### ISSUE TITLE
Support SQLite computed columns

### ISSUE THREAD

**Issue by skoczian** [sqlalchemy/sqlalchemy#5297]
[sqlalchemy_mail_20200501.txt](https://github.com/sqlalchemy/sqlalchemy/files/4565503/sqlalchemy_mail_20200501.txt)
From version 3.31.0 (2020-01-22) SQLite supports generated columns; documentation: https://sqlite.org/gencol.html 
So SQLAlchemy should support that, as with other dialects, I think. At the moment trying to use a SQLite database with computed columns raises a CompileError. I'm attaching a stack trace, because it's pretty long.
On the other hand I just saw that the sqlite3 module in Python 3.8.2 uses SQLite version 3.28.0. So I'm early with my request. But shouldn't SQLAlchemy change the exception to a DBAPIError for the time being?

**Comment by zzzeek** [comment]
I dont know that we support the compilation for SQLite's computed columns, or if there is a generic DDL we have for this that would work on SQLite.

**Comment by CaselIT** [comment]
I've just checked and it seems that python installed with conda ships already with sqlite 3.31.1.

Both version 3.7.7 and 3.8.2 report that version

**Comment by CaselIT** [comment]
For refrection there is no documentation.
We need to use table_xinfo, and documentation on it is on the commit message....
https://www.sqlite.org/src/info/069351b85f9a706f60d3e98fbc8aaf40c374356b967c0464aede30ead3d9d18b
It returns an additional column "hidden"
0 normal column
1 hidden
2 virtual
3 stored
What a hacked together solution... And the column name is still hidden...

Also it seems the only way of reflecting the formulae is to use `select sql from slqmaster`

**Comment by CaselIT** [comment]
pragma is also bugged. The type of a column `computed_col INTEGER GENERATED ALWAYS AS (normal + 42)` is returned as `INTEGER GENERATED ALWAYS`.

Seems really an hacked together solution...

**Comment by zzzeek** [comment]
We can begin by spuporting rudimentary DDL and data round trip support.  refleciton can be later.

**Comment by zzzeek** [comment]
we have to make sure this version of SQLite is on my CI containers too.

**Comment by CaselIT** [comment]
Uploading patch now.
Should enable full support for them

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**SQLite 3.31 added support for computed column.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1933

**Comment by CaselIT** [comment]
> we have to make sure this version of SQLite is on my CI containers too.

They currently seem to be 3.26 both py27 and py37.
I've checked and I have 3.30.0 on py27, 3.31.1 on py37 and py38.

I don't know if 3.31 will ever be on py27, but we should be able to have it on py37.

Also shouldn't we start testing with py38?

**Comment by CaselIT** [comment]
I've just checked the latest python containers and python version 27,37,38 all have version 3.27.2.

Probably will need to compile it?

**Comment by CaselIT** [comment]
On debian, it seems to be sufficient to compile sqlite 3.31+ then run python with `LD_LIBRARY_PATH=/usr/local/lib/ python` (where `/usr/local/lib/` is the path where sqlite3 was installed) without needing to recompile python

**Comment by zzzeek** [comment]
jenkins master is doing python 38, for the gerrit job I should just be able to switch it

**Comment by CaselIT** [comment]
you have to verify which version pf sqlite it has. I think it depends on the os, not on the python version.

**Comment by zzzeek** [comment]
it's a container so centos8
```

jenkins@59a0899ccb04 jenkins]$ /opt/python3.8/bin/python3
Python 3.8.0 (default, Nov 30 2019, 04:46:03) 
[GCC 8.2.1 20180905 (Red Hat 8.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.26.0'
>>> 
[jenkins@59a0899ccb04 jenkins]$ cat /etc/centos-release
CentOS Linux release 8.0.1905 (Core) 

```

**Comment by CaselIT** [comment]
you can download and install the latest version from the sqlite site. then you gave to specify the library path when running python and it gets picked up automatically.

at least on Debian, but I guess that centos is similar

**Comment by zzzeek** [comment]
OK that is not the newest, hold on

**Comment by zzzeek** [comment]
blah, centos8.1 image is the latest and still has sqlite 3.26 for sqlite-devel.  the python 3.8 on there I build manually, centos8 is only at python 3.6 for their packaging.

**Comment by zzzeek** [comment]
e.g. I might have to either switch jenkins container to be fedora, or we have to build sqlite manually which I probably don't want to get into

**Comment by CaselIT** [comment]
I'm quite a noob on linux building stuff, but I managed with the classic `./configure && make && make install` so it should not be too hard

**Comment by zzzeek** [comment]
Well, "ish", to build Python requires a lot of dependencies are installed and there are also flags and stuff I have to use, so it's "easy" but took a lot of experimentation.

with SQLite, I have a vague memory that there is something crazy going on with how he does it, but i think it might be that he delivers it as a single giant C source file with everything generated into it to make it easier to build, something like that.

**Comment by zzzeek** [comment]
yup, an "amalgamation".  sqlite does nothing in the traditional way.   https://www.sqlite.org/amalgamation.html

**Comment by CaselIT** [comment]
the file that you download in a release seem to be already amargamated.

**Comment by zzzeek** [comment]
alrighty
```

[root@e6520f563ff0 sqlite-autoconf-3310100]# /opt/sqlite-3310100/bin/sqlite3 
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> 

```

the build scripts for the Pythons inside of jenkins need to be updated to use a locally built sqlite-devel and evertyhing has to be run all over again, i can do this but not today

**Comment by CaselIT** [comment]
on Debian python does not need to be rebuilt. you just need to specify the ld path. maybe its the same on centos? I don't know if ld_library is Debian specific

**Comment by CaselIT** [comment]
From a quick search is should work also on centos. Try setting `LD_LIBRARY_PATH` to the place where sqlite3 has installed the .so files, then start python. On debian it used the new sqlite version

**Comment by zzzeek** [comment]
I have to rebuild the images anyway to have the new sqlite installed on them.    I can do this on the containers for the moment but that can get blown away.

**Comment by zzzeek** [comment]
also the tests have to pass on older sqlite too in any case so might as well start that way

**Comment by CaselIT** [comment]
I guess we can run multiple pytest with multiple `LD_LIBRARY_PATH` to have python pick up different sqlite versions

> I have to rebuild the images anyway to have the new sqlite installed on them. I can do this on the containers for the moment but that can get blown away.

let me know if I can help

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**SQLite 3.31 added support for computed column.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1977
