### ISSUE TITLE
index with non-column-associated element and the index itself is deferred as far as being associated with the table

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5298]
```
from sqlalchemy import Column
from sqlalchemy import desc
from sqlalchemy import Index
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import Table
from sqlalchemy.schema import CreateIndex

metadata = MetaData()

t1 = Table(
    "a",
    metadata,
    Column('id', Integer)
)

c2 = Column('x', Integer)

# if we do it here, no problem
# t1.append_column(c2)

idx = Index('foo', c2, desc("foo"))

t1.append_column(c2)
print(CreateIndex(idx))

```

**Comment by zzzeek** [comment]
references #5292

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Handle non-string, non column expression in index for deferred attach** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1934

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Handle non-string, non column expression in index for deferred attach** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1935
