### ISSUE TITLE
different model columns during dev and test. BIT of mssql to Boolean of sqlite

### ISSUE THREAD

**Issue by copdips** [sqlalchemy/sqlalchemy#5299]
Hello, I often use a in memory sqlite during the unittest, it's embedded in python.
Now for a project, I should connect to Microsoft mssql, and one of the column is in `BIT`: `from sqlalchemy.dialects.mssql import BIT`. `BIT` is not a sqlite column, so during the unittest, my sqlite wont be setup correctly.

I would like to know if sqlalchemy can dynamically change the column of type `BIT` to `Boolean` when it finds the backend sql is a sqlite.

**Comment by CaselIT** [comment]
In this particular case you can just use the generic type `Boolean`, since it gets compiled to bit in mssql.

Otherwise you can probably do this by customizing how you compile BIT in sqlite: https://docs.sqlalchemy.org/en/13/core/compiler.html#type-compilation-extension
Example:
```py
import sqlalchemy as sa
from sqlalchemy.dialects import mssql, sqlite
from sqlalchemy.ext.compiler import compiles

m = sa.MetaData()

t = sa.Table("foo", m, sa.Column("my_col", mssql.BIT()))

ct = sa.schema.CreateTable(t)

@compiles(mssql.BIT, "sqlite")
def compile(element, compiler, **kw):
    return "INTEGER"

print(ct.compile(dialect=mssql.dialect()))
print(ct.compile(dialect=sqlite.dialect()))
```

**Comment by copdips** [comment]
that's so great, thank you very much for this rapid response.
