### ISSUE TITLE
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint 

### ISSUE THREAD

**Issue by nataly-obr** [sqlalchemy/sqlalchemy#5300]
**Describe the bug**
session.commit() method produces IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint.

**Expected behavior**
session.committed without error

**To Reproduce**

```py
import sqlalchemy as db
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

class Currency(Base):
    __tablename__ = 'currency'

    currency_code = db.Column('currency_code', db.String(3), primary_key=True)
    currency_name = db.Column('currency_name', db.String(140))

engine = create_engine('postgresql:...')
Session = sessionmaker(bind=engine)
session = Session()
currency_list = [Currency(currency_code = 'USD'), Currency(currency_code = 'EUR')]
currency_list = list(map(lambda x: session.merge(x), currency_list))
session.bulk_save_objects(currency_list, update_changed_only=False)
session.commit() 
```

**Error**

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "currency_pkey"
DETAIL:  Key (currency_code)=(EUR) already exists.
```

**Versions.**
 - OS: Ubuntu 18.04
 - Python: 3.6
 - SQLAlchemy: 1.3.16
 - Database: postgresql
 - DBAPI: psycopg2

**Additional context**
1. If I modify this code by adding session.commit() after session.merge(), everything works fine:
``` python
...
currency_list = list(map(lambda x: session.merge(x), currency_list))
session.commit() 
session.bulk_save_objects(currency_list, update_changed_only=False)
session.commit() 
```
2. The table 'currency' is empty.
3. Also no problem with adding this currency_code via psycopg2.connect(...) ...

**Comment by CaselIT** [comment]
I believe you do not have to add the object to the session when using `bulk_save_objects`.
In you first case you are saving them using `bulk_save_objects` when committing the objects added to the session.

You can enable `echo` on the engine to see the sql that sqlalchemy is emitting to the database

**Comment by nataly-obr** [comment]
@CaselIT 
Thanks a lot!
