### ISSUE TITLE
mysql session return the same result

### ISSUE THREAD

**Issue by lolongcovas** [sqlalchemy/sqlalchemy#5306]
**mysql session return the same result**

**Example**

This is the example case:

```
from sqlalchemy.orm import sessionmaker 
from sqlalchemy import create_engine

engine = create_engine("mysql://user:pass@host:3306/db_name", pool_recycle=60) 
session = sessionmaker(bind=engine)()

for _ in range(100):
    print(session.execute("select count(*) from tableX").fetchall())
    # all the time prints the same number of rows
    sleep(10)
```
there is another process which inserts data into table `tableX` every second. So, what I was expecting is the code of above prints an incremental number of rows.

**Comment by CaselIT** [comment]
It would help if you also shared the code that adds data. That code looks ok. Are you sure you are committing the changes there?
A complete example (with threads but it's the same with processes)

```py
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
import threading
import time

m = sa.MetaData()
t = sa.Table("table_1", m, sa.Column("id", sa.Integer, primary_key=True))
engine = sa.create_engine("sqlite:///test.db", echo=True)

m.create_all(engine)


def run_theread():
    for i in range(10):
        with engine.begin() as c:
            c.execute(t.insert(), {"id": i})
        time.sleep(2)


tr = threading.Thread(target=run_theread)
tr.start()

session = sessionmaker(engine)()

for i in range(25):
    print(i, session.execute("select count(*) from table_1").fetchall())
    time.sleep(1)

tr.join()
```

**Comment by zzzeek** [comment]
the Session runs in a transaction as soon as you use it.  so you need to call .rollback() in order to see new results.   see https://en.wikipedia.org/wiki/Isolation_(database_systems)

**Comment by CaselIT** [comment]
indeed the example above does not work on mysql but does on sqlite. They have a different isolation level by default?

**Comment by zzzeek** [comment]
all the databases have idiosyncratic behavior regarding what isolation levels are available, what the default isolation level is, what the specific behaviors of those isolation levels are.  In the case of SQLite the driver itself is also getting in the way by not actually beginning a transaction, otherwise you'd get serializable isolation and your program would actually throw an error due to the file being locked.

**Comment by CaselIT** [comment]
> 
> 
> indeed the example above does not work on mysql but does on sqlite. They have a different isolation level by default?

Yes, mysql has repeatable read by default. I'm not familiar with it. Postgres that by default has read committed, behaves like sqlite

**Comment by zzzeek** [comment]
examples of database implementing the isolation levels idiosyncratically, here's a good blog post describing non-standard isolation behaviors of MySQL innodb: https://blog.pythian.com/understanding-mysql-isolation-levels-repeatable-read/

**Comment by lolongcovas** [comment]
@CaselIT ur code works since the sql is sqlite. Indeed, i

**Comment by lolongcovas** [comment]
@CaselIT the inserting data code is actually command line that insert sqlite command to mysql:

```
INSERT INTO web_product_twins VALUES(1,'34141664','2020-04-26 14:29:17');
...
INSERT INTO web_product_twins VALUES(3,'34471559','2020-04-26 14:29:17');
...

tons of line of like this but with different values

```

so, these sqlite instructions are store in a sqlite_dump.txt file:
```
cat sqlite_dump.txt | mysql -u user -p pwd database_name
```

**Comment by CaselIT** [comment]
If you add `session.rollback()` after the print all should word.
As an alternative you can also change the isolation level to read committed.

**Comment by lolongcovas** [comment]
Yes, it is has to do with isolation level. Never heard about it before. 
```
engine = create_engine("mysql://user:pass@host:3306/db_name",
                       pool_recycle=60, isolation_level="READ COMMITTED")

```
worked!

thanks for the help, really appreciate it!
