### ISSUE TITLE
sqlalchemy.sql.expression.table  & schema

### ISSUE THREAD

**Issue by DylanModesitt** [sqlalchemy/sqlalchemy#5309]
[`table(...)`](https://docs.sqlalchemy.org/en/13/core/selectable.html#sqlalchemy.sql.expression.table) in the expression language does not accept a schema (presumably, [`intentionally`](https://docs.sqlalchemy.org/en/13/core/selectable.html#sqlalchemy.sql.expression.table)). When wanting to use it for schemas other than the default on some dialects (Oracle, for example), the resulting quoted identifier will not work. 

```python
sqlalchemy.select(["*"]).select_from(sqlalchemy.table("someschema.SOMETABLE"))
```

produces (with the oracle dialect)

```sql
SELECT * 
FROM "someschema.SOMETABLE" 
```

which is invalid. However, it happens that because `table` is produced from [`TableClause`](https://github.com/zzzeek/sqlalchemy/blob/9f6b67a37e820b9a5be54301d08f20161bd20ee8/lib/sqlalchemy/sql/selectable.py#L1878), setting `.schema` on the resulting `table` allows a correct query. 

```python
the_table = sqlalchemy.table("SOMETABLE")
the_table.schema = "someschema"
sqlalchemy.select(["*"]).select_from(the_table)
```

gives

```sql
SELECT * 
FROM "someschema"."SOMETABLE" 
```

**Possible Solution**

Is it possible for `TableClause` to take a keyword-only `schema` parameter? Or would this cause breaking changes when used with `sqlalchemy.Table` when a table is bound to a schema by metadata?

If that is not possible, is it acceptable for `table` do slightly more work than the `public_factory` and accept this keyword-only argument itself - since that appears to be the intended entry-point for `TableClause` when not using `.Table`. 

Or are either of these changes too fragile? I would be happy to work on a PR for this if any solution is acceptable. I think this is a fairly niche feature that is already implicitly supported by the expression-language "compiler" with `.schema` - but it would be nice to have on construction. 

**Alternatively**

One can do as I do now by setting `.schema` after creating the `TableClause` with `table`.

**Comment by zzzeek** [comment]
> 
> Is it possible for `TableClause` to take a keyword-only `schema` parameter? Or would this cause breaking changes when used with `sqlalchemy.Table` when a table is bound to a schema by metadata?

this should be possible, there might be a lot of cases to get working but then again maybe not.   it's just one extra attribute, and because it's being added, there's no issue of backwards incompatibility.   I don't see why it would interfere with the Table subclass, which would continue to accommodate "schema" and "name" in its own way.


> 
> If that is not possible, is it acceptable for `table` do slightly more work than the `public_factory` and accept this keyword-only argument itself - since that appears to be the intended entry-point for `TableClause` when not using `.Table`.

looking at TableClause that is likely the reason it doesnt have any options, because we are with Python 2 compatibility for the next year at least, we would have to add **kw to the class, so likely there should be "schema = kw.pop('schema', None)" and then "if kw: raise ArgumentError".


> 
> Or are either of these changes too fragile? I would be happy to work on a PR for this if any solution is acceptable. I think this is a fairly niche feature that is already implicitly supported by the expression-language "compiler" with `.schema` - but it would be nice to have on construction.

sure !

> 
> **Alternatively**
> 
> One can do as I do now by setting `.schema` after creating the `TableClause` with `table`.

a very effective workaround that is probably happening in the test suite too.

**Comment by sqla-tester** [comment]
**Dylan Modesitt** has proposed a fix for this issue in the **master** branch:

**Add 'schema' parameter to table** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1944

**Comment by sqla-tester** [comment]
**Dylan Modesitt** has proposed a fix for this issue in the **master** branch:

**Add 'schema' parameter to table** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1944

**Comment by sqla-tester** [comment]
**Dylan Modesitt** has proposed a fix for this issue in the **rel_1_3** branch:

**Add 'schema' parameter to table** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1976
