### ISSUE TITLE
[postgresql] Handle partition and partitionned table

### ISSUE THREAD

**Issue by RemiDesgrange** [sqlalchemy/sqlalchemy#5313]
**Is your feature request related to a problem? Please describe.**
It is currently cumbersome to deals with partition in SQLAlchemy (at least with postgresql).

**Describe the solution you'd like**
Id' like to be able to use `Table` and class base declaration (ORM) to deal with partitions. It's already possible to describe partionned table, but not partition on itself :+1: 

```python
engine = create_engine("postgresql://postgres:postgres@localhost:5432/postgres")
metadata = MetaData(bind=engine)
Base = declarative_base(metadata=metadata)

class UserType(Enum):
    HR = "HR"
    TECH = "TECH"

    def __str__(self) -> str:
        return str(self.value)


def create_partition(target, connection, **kw) -> None:
    """ creating partition by hand"""
    connection.execute(
        """CREATE TABLE IF NOT EXISTS "hr" PARTITION OF "user" FOR VALUES IN ('HR')"""
    )
    connection.execute(
        """CREATE TABLE IF NOT EXISTS "tech" PARTITION OF "user" FOR VALUES IN ('TECH')"""
    )


class User(Base):
    __tablename__ = "user"
    __table_args__ = (
        UniqueConstraint("id", "user_type"),
        {
            "postgresql_partition_by": "LIST (user_type)",
            "listeners": [("after_create", create_partition)],
        },
    )
    id = Column(UUID(as_uuid=True), default=uuid4, primary_key=True)
    user_type = Column(SQLEnum(UserType), nullable=True, primary_key=True)
    firstname = Column(String(255), nullable=False)

    def __repr__(self) -> str:
        return f"{self.id=}, {self.user_type=}, {self.firstname=}"
```

**Describe alternatives you've considered**
I tried creating table with `keep_existing` and stuff like `autoload` did not work great :-/

I tried to search on the web, I posted on [SO](https://stackoverflow.com/questions/61545680/postgresql-partition-and-sqlalchemy) and I didn't found a clean way of declarating. Note that my example is dumb and could be implemented by other (better) techniques,

**Comment by zzzeek** [comment]
hi there -

I'm not yet understanding the problem.    are you only referring to how to emit the DDL for CREATE PARTITION ?  your SO answer seems to imply that you want to create new subclasses for new partitions, but im not sure why that would be needed.

for creating new partitions I would use the DDL() consturct: https://docs.sqlalchemy.org/en/13/core/ddl.html?highlight=ddl#custom-ddl   these can be associated with a table or metadata and they will fire off when you emit a create.

I seem to recall there were some other recipes for PG partitions but I'm not finding them right now.     but need to know what use pattern you are looking for as it is not clear.

**Comment by zzzeek** [comment]
here it is, this is doing an older style where it creates the triggers also, I'm not sure if PG's feature still requires triggers in order to write to the tables, but this recipe also sets up a "single table" inheritance mapping against the partitions:

https://github.com/sqlalchemy/sqlalchemy/wiki/PostgreSQLInheritance

the example could be better.   It could automatically add DDL for each new partition when you create a class, if you set that DDL up within a method like declare last:  https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/api.html?highlight=__declare_last__#declare-last .

**Comment by zzzeek** [comment]
I'm actually confusing INHERITS and PARTITION BY.  let me read the docs for a second

**Comment by zzzeek** [comment]
OK INHERITS is the old way that is more flexible and PARTITION BY seems to be a shortcut of some kind.   anyway, it would be nice to add a new example for this, but general idea, make a DDL() object inside of `__declare_last__`

```
class MyClass(Base):
   # ...
   user_type = Column(...)

  __mapper_args__ = {"polymorphic_on": user_type}
  __table_args__ = ({"postgresql_partition_by": "expr"})
class MySubClass(MyClass):

   # ...

   __mapper_args__ = {"polymorphic_identity": "HR"}

   @classmethod
   def declare_last(cls):
       ddl = DDL("CREATE TABLE IF NOT EXISTS ....")
       event.listen(cls.__table__, "after_create", ddl)
```

**Comment by RemiDesgrange** [comment]
Ok Thanks for giving a quick answer. I was unaware of `declare_last` method. 

I don't have a specific use case right now, I'm just wondering and thinking "Is that stuff you implement 6 months ago would have been great with partition, or not ?" So I start toying with partition and SQLAlchemy and found it hard to get it right. I think your example is pretty clear. I'll try tomorrow on some other examples.

**Comment by zzzeek** [comment]
great.  We should have real examples for an ORM-enabled PARTITIONS recipe in the examples/ folder at some point, but that's outside of the scope of this issue for the moment so closing this.

**Comment by vvanglro** [comment]
@zzzeek 
hi~  
I tried using declare Last, but it didn't seem to fire
```python
from sqlalchemy import DDL, create_engine, MetaData, Column, DateTime, func, BigInteger, String
from datetime import datetime
from sqlalchemy import event
from sqlalchemy.ext.declarative import declarative_base

engine = create_engine("postgresql://postgres:postgres@localhost:55432/partition_test")
metadata = MetaData(bind=engine)
Base = declarative_base(metadata=metadata)


class Data(Base):
    __tablename__ = "test_table"

    __table_args__ = (
        {
            "postgresql_partition_by": "RANGE (id)",
        },
    )
    created_on = Column(
        DateTime, default=datetime.now, server_default=func.now()
    )
    id = Column(BigInteger, primary_key=True, autoincrement=True)

    name = Column(String(), index=True)

    @classmethod
    def __declare_last__(cls):
        ddl = DDL("CREATE TABLE IF NOT EXISTS test_table_2 PARTITION OF test_table FOR VALUES FROM (0) TO (10)")
        event.listen(cls.__table__, "after_create", ddl)


Base.metadata.create_all()
```

**Comment by zzzeek** [comment]
> @zzzeek hi~ I tried using declare Last, but it didn't seem to fire SQLAlchemy 1.3.24
> 
> ```python
> from sqlalchemy import DDL, create_engine, MetaData, Column, DateTime, func, BigInteger, String
> from datetime import datetime
> from sqlalchemy import event
> from sqlalchemy.ext.declarative import declarative_base
> 
> engine = create_engine("postgresql://postgres:postgres@localhost:55432/partition_test")
> metadata = MetaData(bind=engine)
> Base = declarative_base(metadata=metadata)
> 
> 
> class Data(Base):
>     __tablename__ = "test_table"
> 
>     __table_args__ = (
>         {
>             "postgresql_partition_by": "RANGE (id)",
>         },
>     )
>     created_on = Column(
>         DateTime, default=datetime.now, server_default=func.now()
>     )
>     id = Column(BigInteger, primary_key=True, autoincrement=True)
> 
>     name = Column(String(), index=True)
> 
>     @classmethod
>     def __declare_last__(cls):
>         ddl = DDL("CREATE TABLE IF NOT EXISTS test_table_2 PARTITION OF test_table FOR VALUES FROM (0) TO (10)")
>         event.listen(cls.__table__, "after_create", ddl)
> 
> 
> Base.metadata.create_all()
> ```

make sure you configure_mappers() so that hook is read:

```
configure_mappers()
Base.metadata.create_all()
```

**Comment by AmitArie** [comment]
Hi, there is a way to create the partitioned model dynamically? at run time?

**Comment by CaselIT** [comment]
you can execute DDL strings like the one shown in the example to create the table

Not sure if there is something more sophisticated in an external library like sqlalchemy-utils or similar

**Comment by pinkfrog9** [comment]
> ```python
> class Data(Base):
>     __tablename__ = "test_table"
> 
>     __table_args__ = (
>         {
>             "postgresql_partition_by": "RANGE (id)",
>         },
>     )
> ```

Hi @zzzeek , in this way, how to create an index specifically on a specific partitioned table?

If I add an index in the table_args above, then that index is created over all the partitioned table.
