### ISSUE TITLE
fetching cx_Oracle CLOBs unnecessarily slow / could be optimized with a switch

### ISSUE THREAD

**Issue by ztane** [sqlalchemy/sqlalchemy#5314]
According to the [cx_Oracle bug tracker](https://github.com/oracle/python-cx_Oracle/issues/63#issuecomment-322532071), it is possible to force fetching CLOBs with `cx_Oracle` as if they were long strings, by just using the following output type handler:

```
    def output_type_handler(cursor, name, defaultType, size, precision, scale):
        if defaultType == cx_Oracle.CLOB:
            return cursor.var(cx_Oracle.LONG_STRING, arraysize = cursor.arraysize)
```

SQLAlchemy currently has two options: either do not fetch CLOBs eagerly at all, or fetch the CLOBs using a very inefficient .read(). Maybe it would be worthwhile to add this as an option. This matters a lot when the database has lots of small CLOBs and the rows need to be fetched in bulk.

**Comment by ztane** [comment]
So, I made a change and tested the following query

```
SELECT * FROM (SELECT clob FROM table WHERE clob IS NOT NULL) WHERE ROWNUM <= 10000
 ```

The clob columns are *really small on average*. With the following change:

```
                    if dialect.auto_convert_lobs == 'inline':
                        return cursor.var(
                            cx_Oracle.LONG_STRING,
                            arraysize=cursor.arraysize
                        )
                    return cursor.var(
                        default_type,
                        size,
                        cursor.arraysize,
                        outconverter=lambda value: value.read(),
                        **dialect._cursor_var_unicode_kwargs
                    )
```

and the `'inline'` option, running over a slow VPN, I got 10000 rows in ~1.5 seconds. If I used `auto_convert_lobs=False`, it took 7-8 **seconds**, i.e. **much slower** and I just got CLOBs in the result set. And with `auto_convert_lobs=True`, well, I don't have enough patience, but I guess it will take ~5 minutes as it seems to scale linearly and 1000 rows took 32 seconds...

**Comment by ztane** [comment]
Now, there seem to be many branches, and I do not know how to write the similar code path for the blobs - frankly, I am unable to test this code any more than this because I do not even have a *write* access to *any* Oracle database...

**Comment by CaselIT** [comment]
Hi,
You should use the master branch as a starting point.

If you are able to provide a pr for this it would be great.
Regarding the test, once a pr is open we can test against the ci that tests also against oracle. I think you could use the current tests of clob on oracle as a baseline to add one for inline.
https://github.com/sqlalchemy/sqlalchemy/blob/bd303b10e2bf69169f07447c7272fc71ac931f10/test/dialect/oracle/test_types.py#L897-L1034

**Comment by zzzeek** [comment]
this is good, you went into the outputttype handlers which is where it all happens for cx_Oracle, and as they are constantly changing how things work here, it's not surprising that this is now possible.    suggest that this just be the new implementation for auto_convert_lobs = True

**Comment by zzzeek** [comment]
any limitation on the cx_Oracle side for this?    do we need to be concerned about very large values or anything ?

**Comment by CaselIT** [comment]
> suggest that this just be the new implementation for auto_convert_lobs = True

if there are no limitation I guess it would make sense, maybe new accepted values for `auto_convert_lobs` could be `read` for the legacy version and `inline` for this new version

**Comment by ztane** [comment]
As I said I cannot do much, because I just have one DB that I have access to, and only read access, and even then it has only small CLOB columns, and no BLOBs etc.

**Comment by zzzeek** [comment]
well we'd ask @anthony-tuininga

**Comment by zzzeek** [comment]
he already answered:

https://github.com/oracle/python-cx_Oracle/issues/63#issuecomment-323452444

> There is no technical limit. But the code is optimised for smaller CLOBs so may not perform as well with larger CLOBs. Note as well that you require a contiguous block of memory so this could become a problem with larger CLOBs.

we are doing value.read(), which is the same thing.

**Comment by zzzeek** [comment]
I really think we should use this mode going forward. this wasn't a thing in the old days and this whole business with data.read() has always been a huge burden.

**Comment by anthony-tuininga** [comment]
As noted, the performance difference fetching CLOBs (and BLOBs) as strings (bytes) is significant. I would indeed use that as the default. Those requiring the processing of large CLOB/BLOB should fetch the CLOB/BLOB directly and do whatever they need to do with it. It sounds like you have that option available already, so changing the default to fetch CLOB/BLOB as strings/bytes without doing a .read() makes sense to me.

**Comment by zzzeek** [comment]
@anthony-tuininga  how long has cx_oracle supported that?   that is how long have I been using read() for no reason :)

**Comment by zzzeek** [comment]
should we be applying similar to BLOB objects?

**Comment by anthony-tuininga** [comment]
Absolutely. Something like this can be used for both CLOB and BLOB together:

```python
def OutputTypeHandler(cursor, name, defaultType, size, precision, scale):
    if defaultType == cx_Oracle.CLOB:
        return cursor.var(cx_Oracle.LONG_STRING, arraysize = cursor.arraysize)
    if defaultType == cx_Oracle.BLOB:
        return cursor.var(cx_Oracle.LONG_BINARY, arraysize = cursor.arraysize)
```

**Comment by zzzeek** [comment]
ok first problem, it is converting empty strings to NULL, and then it is not even caling the outconverter in that case to give me a chance to fix it.     I can't change that behavior for 1.3 and even in 1.4 it would be a hard change.

**Comment by zzzeek** [comment]
OK it  looks like we are already not supporting blank VARCHAR but we do blank CLOB for the moment due to our implementation, so this is kind of an implemenation detail leaking out sort of badly.  it would be more consistent to not support blank strings in either case.

**Comment by anthony-tuininga** [comment]
Ah yes, the Oracle penchant for converting empty strings to null (and I can't change that). And yes, the outconverter is not called if the value is None (which has always been the case).

**Comment by zzzeek** [comment]
I can make this look like a bug fix: 

"    As part of this change, the behavior of a CLOB that was given a blank
    string on INSERT now returns None on SELECT, which is now consistent with
    that of VARCHAR on Oracle.
"

**Comment by zzzeek** [comment]
I do have the ability to jump in and change these  values however the bigger problem is that we can't distinguish bertween NULL and blank.  Id rather return NULL columns as NULL than blank strings as blank strings.

**Comment by anthony-tuininga** [comment]
Empty CLOB/BLOB are fairly uncommon, thankfully. I'm not sure what you mean by your last comment, but I assume that is internal to your project. :-)

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use cx_oracle.LONG_STRING /LONG_BINARY for CLOB/BLOB** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1947

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Use cx_oracle.LONG_STRING /LONG_BINARY for CLOB/BLOB** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1948

**Comment by zzzeek** [comment]
it means if I put two rows in my database, in one row the column is NULL, in the other row the column is a blank string.  then I SELECT them back.  They are both NULL.  I cannot correct for this loss of information such that both come back as what they were inserted as.

**Comment by anthony-tuininga** [comment]
Ah, that makes sense. That's an Oracle "feature". Some people think its wonderful and others...not so much!
