### ISSUE TITLE
remove check unicode returns for Python 3

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5315]
It is very unlikely that any Python DBAPI returns "bytes" for VARCHAR under Python 3, even in the extended world of external dialects.   let's add a new flag to dialects "unicode_returns", and in the spirit of simpler typing lets give it constants RETURNS_UNICODE, RETURNS_UNKNOWN, RETURNS_CONDITIONAL, RETURNS_BYTES.    in python 3 it defaults to RETURNS_UNICODE and python 2 it detauls to RETURNS_UNKNOWN.   third party dialects can set it to RETURNS_BYTES or RETURNS_CONDITIONAL if for some reason they actually have that behavior.   RETURNS_UNKNOWN is deprecated and will be removed in 2.0.    The "check_unicode_returns" check only proceeds for RETURNS_UNKNOWN.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Disable "check unicode returns" under Python 3** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1946
