### ISSUE TITLE
determine what should happen in sorted_tables when there is a cycle.  raise?  if not, why not?

### ISSUE THREAD

**Issue by brmzkw** [sqlalchemy/sqlalchemy#5316]
**Describe the bug**

The order of `base.metadata.sorted_table` is invalid when there are two cyclic dependencies, even for unrelated tables. The order is correct when the foreign key has `use_alter=True`.

**To Reproduce**
```py

from sqlalchemy import (
    Column,
    ForeignKey,
    Integer,
    String,
)

from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


#
# Two tables with cyclic dependencies.
#
class ModelA(Base):

    __tablename__ = 'models_a'

    id = Column(String, primary_key=True)
    model_b_id = Column(String, ForeignKey('models_b.id'))


class ModelB(Base):

    __tablename__ = 'models_b'

    id = Column(String, primary_key=True)
    taxi_id = Column(String, ForeignKey('models_a.id'))


#
# Now some unrelated tables to store users, roles and users roles.
#

class RoleUser(Base):

    __tablename__ = 'roles_users'
    user_id = Column(Integer, ForeignKey('users.id'), primary_key=True)
    role_id = Column(Integer, ForeignKey('roles.id'), primary_key=True)


class Role(Base):

    __tablename__ = 'roles'

    id = Column(Integer, primary_key=True)


class User(Base):

    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)


for table in Base.metadata.sorted_tables:
    print(table.name)


"""
Output of the print above:

    models_a
    models_b
    roles
    roles_users
    users

"roles_users" references "roles" and "users", but sorted_tables put it between
the two tables which is unexpected.

Now, if we set use_alter=True in ModelA.model_b_id, such as:

    model_b_id = Column(String, ForeignKey('models_b.id', use_alter=True))

Output becomes:

    models_a
    roles
    users
    models_b
    roles_users

Which is expected: roles_users is created **after** roles and users..
"""
```

**Versions.**
 - SQLAlchemy: 1.3.16

**Comment by zzzeek** [comment]
hi there -

the [documentation](https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=sorted_tables#sqlalchemy.schema.MetaData.sorted_tables) seems to make this clear in the pink warning box:

> Warning

> The sorted_tables accessor cannot by itself accommodate automatic resolution of dependency cycles between tables, which are usually caused by mutually dependent foreign key constraints. To resolve these cycles, either the ForeignKeyConstraint.use_alter parameter may be applied to those constraints, or use the sort_tables_and_constraints() function which will break out foreign key constraints involved in cycles separately.

is that not describing the case you are having or is there some issue with that wording, let me know.

**Comment by brmzkw** [comment]
Indeed, the problem in my snippet is the order is wrong for completely unrelated tables.

**Comment by zzzeek** [comment]
it does look like the function is *trying* to only omit the FKs involved in the cycle and it's not clear why that's not working.

**Comment by brmzkw** [comment]
I'm using `reversed(sorted_tables)` to delete all data between unittests. In my case, I don't mind if the order is wrong. But I guess it would be better if an exception with an explicit message was raised.

**Comment by zzzeek** [comment]
OK just checking that an error is OK.   however it also looks like it was in fact trying to do what you expected there and is doing it incorrectly so ill see if it can do that too.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Warn when sorted_tables is not actually sorting** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1949

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Warn when sorted_tables is not actually sorting** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1950

**Comment by zzzeek** [comment]
that patch just linked above will warn and also sort the remaining tables correctly.

**Comment by brmzkw** [comment]
Amazing, thanks!

**Comment by zzzeek** [comment]
those two gerrits will close this when merged.
