### ISSUE TITLE
Load external sybase dialect if available

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5318]
Extending #5278 for the external sybase dialect.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Load external firebird or sybase dialect if available** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1951

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Load external firebird or sybase dialect if available** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1952
