### ISSUE TITLE
pyodbc connector forcing "supports_sane_rowcount_returning" to False

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5321]
https://github.com/sqlalchemy/sqlalchemy/blob/5311a8531c621760ced0b3d0a5454e8c22871d66/lib/sqlalchemy/connectors/pyodbc.py#L17

was added almost 3 years ago, presumably in response to a deficiency in pyodbc at the time. That deficiency has apparently been resolved; I can change the value to `True` and the backend tests pass for `mssql+pyodbc`. Moreover, `True` allows a `sybase+pyodbc` (external) test to pass which otherwise will always fail with an "unexpected success" exception.

My question is whether this should remain a pyodbc override given that when pyodbc was (presumably) broken the value would always be `False`, but now the appropriate value might be `True` or `False` depending on the behaviour of a given ODBC driver.

**Comment by zzzeek** [comment]
can you link me to when it was set that way.    we can probably flip it on and if it breaks for people we'd find out soon enough, but it would be nice to understand what the issue was.

**Comment by gordthompson** [comment]
You mean this?

https://github.com/sqlalchemy/sqlalchemy/commit/b9b1e374bfbcece8259a4df5372ca68d45aaaf01

**Comment by zzzeek** [comment]
OK, this likely has to do with platforms and drivers.   With the linux drivers I have, it still fails, this is pyodbc 4.0.30 using /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2 .

The test script at the top of #4062 still fails for me if I turn on this flag and the test in the suite that fails is:


```
test/sql/test_rowcount.py::FoundRowsTest_mssql+pyodbc_14_0_3076_1::test_update_rowcount_return_defaults FAILED                                              [100%]

============================================================================ FAILURES =============================================================================
___________________________________________ FoundRowsTest_mssql+pyodbc_14_0_3076_1.test_update_rowcount_return_defaults ___________________________________________
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test/sql/test_rowcount.py", line 96, in test_update_rowcount_return_defaults
    assert r.rowcount == 3
AssertionError: assert -1 == 3
  +-1
  -3
===================================================================== short test summary info =====================================================================
FAILED test/sql/test_rowcount.py::FoundRowsTest_mssql+pyodbc_14_0_3076_1::test_update_rowcount_return_defaults - assert -1 == 3

```

we can certainly turn the flag on but we would have to have it conditional based on a compatibility matrix.   additionally there is an issue #5005 which is fairly straightforward that would make it much safer to turn this flag on, as it seems to be not fully understood under which circumstances pyodbc returns -1 for this flag and some users have reported it occurring in other scenarios as well.

**Comment by gordthompson** [comment]
> OK, this likely has to do with platforms and drivers.

Confirmed. That one little change didn't cause any test failures under Windows but it gave me 19 failures under Linux, in both cases with pyodbc 4.0.30 and ODBC Driver 17 for SQL Server (libmsodbcsql-17.5.so.2.1 and MSODBCSQL17.DLL).

Shall I start a change on Gerrit so we can dig into this?

**Comment by gordthompson** [comment]
On second thought, no need to open the can of worms. I can just override the connector setting in `SybaseDialect_pyodbc` and take the rest of the day off. ;)

**Comment by zzzeek** [comment]
yeha I woudl do that.  I'd rather have #5005 first.

**Comment by zzzeek** [comment]
oh also, duh, we should set the "False" setting in mssql/pyodbc and set it to True in connectors.    not critical though

**Comment by gordthompson** [comment]
Okay, that sounds good.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Move supports_sane_rowcount_returning = False to dialect level** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1960

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Move supports_sane_rowcount_returning = False to dialect level** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1980

**Comment by zzzeek** [comment]
working on #9414, it looks like this works for pyodbc now and it has to do with changes in SQLAlchemy, not the driver
