### ISSUE TITLE
reset_on_return is not reliable

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5326]
the .close() method on Transaction does not reset the "Reset agent".  this method is called by ORM Session when the session is closed and there is no rollback / commit:
```

from sqlalchemy import create_engine


pg_url = "postgresql://scott:tiger@localhost/test"

engine = create_engine(pg_url, echo=True, echo_pool='debug')

conn = engine.connect()


t1 = conn.begin()

t2 = conn.begin_nested()
t2.close()
t1.close()

newtrans = conn.begin()
conn.close()


```

immediate patch that hits it:

```
diff --git a/lib/sqlalchemy/engine/base.py b/lib/sqlalchemy/engine/base.py
index 296926abc..5075dea36 100644
--- a/lib/sqlalchemy/engine/base.py
+++ b/lib/sqlalchemy/engine/base.py
@@ -1730,6 +1730,9 @@ class Transaction(object):
         an enclosing transaction.
 
         """
+        if self.connection.connection._reset_agent is self:
+            self.connection.connection._reset_agent = None
+
         if not self._parent.is_active:
             return
         if self._parent is self:

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Assert reset agent always set correctly and is active** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1964

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Assert reset agent always set correctly and is active** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1965

**Comment by kbower** [comment]
watching

[google groups post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sqlalchemy/Lit5HWFiC0U/y6nE-uksBAAJ)

**Comment by zzzeek** [comment]
I'm going to do another pass in 1.4 and see if this whole reset agent thing can go away sooner rather than later as it is fairly silly what it does.

**Comment by kbower** [comment]
> I'm going to do another pass in 1.4 and see if this whole reset agent thing can go away sooner rather than later as it is fairly silly what it does.

Was reset agent added to ensure that the 'rollback' and 'commit' events are dispatched, right?

**Comment by zzzeek** [comment]
I found the real reason which was #2907.    mysql + drivers were in some situation where there was an XID, the application was falling into not cleaning up the transaction, and then the pool was actually failing to roll back the connection because of the XID state.   I tried yesterday to reproduce that again but MySQL / MAriaDB are much newer now and it's possible that all works much better, and this may also lead me to re-enable tests for 2pc with MySQL, previously there were too many issues.  however, an XID is still this annoying, long lasting thing even on Postgresql so I can see how it's relevant that the reset-on-return accommodate for this somehow.   

compounding the issue is that the test suite uses a lot of SQLite memory connections, which necessarily uses a "singleton" thread pool and some of the fixtures currently will establish more than one Connection object around the DBAPI connection, which is not ideal but still should be supported by that pool, so that's why the "reset on return" logic has lots of "skip if not none" type logic going on, which made it easier for a mistake like this one to slip in.

today I want to see if for 1.4 I can make the code easier to follow and modernize some assumptions a bit.

**Comment by zzzeek** [comment]
the immediate issue is worked around, however my test case above still misses some nuance that's in kent's test such that his test still emits the warning, so try again

```
from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy import event
from sqlalchemy import __version__

print("\n## sqlalchemy %s\n" % __version__)


def do_some_info_reset(connection):
    print("## ## do_some_info_reset on %x ## ##" % id(connection))
    # access connection:
    connection.info


pg_url = "postgresql://scott:tiger@localhost/test"

engine = create_engine(pg_url, echo=True)
event.listen(engine, "rollback", do_some_info_reset)

conn = engine.connect()

maker = sessionmaker(autoflush=True, autocommit=False)
DBSession = scoped_session(maker)
DBSession.configure(bind=conn)

metadata = MetaData(engine)
# map a system postgres table for demo purposes:
table = Table(
    "pg_language", metadata, Column("lanname", Unicode(255), primary_key=True)
)


class Something(object):
    pass


mapper(Something, table)

# mimic application layers with some try blocks:
try:
    try:
        DBSession.begin_nested()
        DBSession.query(Something).all()
        DBSession.close()
        DBSession.query(Something).all()
    finally:
        # should direct conn.close() do rollback as 0.9.1 an earlier?
        conn.close()
finally:
    pass
    DBSession.close()

```

**Comment by zzzeek** [comment]
here's the new test case
```

from sqlalchemy import create_engine


pg_url = "postgresql://scott:tiger@localhost/test"

engine = create_engine(pg_url, echo=True)


conn = engine.connect()

t0 = conn.begin()

t1 = conn.begin_nested()
t0.close()

t2 = conn.begin()

conn.close()


```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Actively unset reset agent in discard transaction** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1967

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Actively unset reset agent in discard transaction** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1968

**Comment by zzzeek** [comment]
OK that's merged and I'm not rushing out a release this time.  let me know that this eliminates all warnings and the rollback defeinitely happens in your setup.

**Comment by kbower** [comment]
It sure looks to be working and the rollback happens.  I'll poke at it a little more, but looks great so far.  Thanks a million!

**Comment by zzzeek** [comment]
the review I have going through in #5327 is WAY better.  but that's only for master / 1.4.
