### ISSUE TITLE
the transaction nesting model is broken

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5327]
we'd like to get rid of the transaction nesting model as we see in #4644.  however, the nesting is still there for now and going back to many versions, it doesn't actually make sense.   the Transaction object does not point to the previous Transaction object, and the management of the "reset agent" which we unfortunately still need for some two-phase types of situations is all over the place.

basic demo of nesting not even making sense:
```

from sqlalchemy import create_engine


pg_url = "postgresql://scott:tiger@localhost/test"

engine = create_engine(pg_url, echo=True, echo_pool='debug')

conn = engine.connect()


t1 = conn.begin()

t2 = conn.begin()

t3 = conn.begin()

assert t3._parent is t1  # shouldn't this be t2?
assert t2._parent is t1

t3.rollback()


assert not t3.is_active
assert not t1.is_active

assert not t2.is_active   # fails - t2 was just forgotten

```

see if we can revise the nesting model and localize how reset agent gets set up, then again it may not be worth it as 2.0 has a simpler model.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Update transaction / connection handling** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1969
