### ISSUE TITLE
Postgres row wise comparison

### ISSUE THREAD

**Issue by jeannei** [sqlalchemy/sqlalchemy#5331]
Does sqlalchemy support postgres row wise comparison? It looks like the only way I can do this is by constructing a raw sql query.

**Example **
```
SELECT *
FROM table
WHERE (col_1, col_2) > (val_1, val_2) 
```

Note `(col_1, col_2) > (val_1, val_2)` is shorthand for `ROW(col_1, col_2) > ROW(val_1, val_2)`

**Useful links**
- [Postgres row wise comparison](https://www.postgresql.org/docs/8.2/functions-comparisons.html#ROW-WISE-COMPARISON) on the website

-Thanks

**Comment by CaselIT** [comment]
Does [`tuple_`](https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=tuple#sqlalchemy.sql.expression.tuple_) work?

**Comment by jeannei** [comment]
@CaselIT that does indeed work i.e.
```
tuple_(col_1, col_2) > (val_1, val_2)
```

**Comment by CaselIT** [comment]
@zzzeek not sure if maybe some documentation could be added in the pg dialect page regarding this?

I'm not sure if creating an alias of `tuple_` as a `ROW` for pg makes sense. Also `ROW` is not pg only, it is in the sql spec. Not sure regarding the short hand notation with open parenthesis

**Comment by zzzeek** [comment]
not sure about ROW yet but we do need a doc section at https://docs.sqlalchemy.org/en/14/dialects/postgresql.html to start talking about these syntaxes (the table valued syntaxes separately).    so a new section "table values, row and tuple objects" that starts to talk about these things and maybe links to some of the workarounds that are still pending for other PG row-oriented cases, like passing a table into a function someone wanted the other day, `func.myfunc(literal_column("some_table"))`, things like that.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add documentation regarding row constructo in PostgreSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2004
