### ISSUE TITLE
Typo in documentation for cx_oracle

### ISSUE THREAD

**Issue by thorstenkampe** [sqlalchemy/sqlalchemy#5333]
Probably via copy and paste there is a type [here](https://docs.sqlalchemy.org/en/13/dialects/oracle.html#unicode)

| In all cases however, the driver requires an explcit encoding configuration.

explcit -> explicit

I've opened https://github.com/oracle/python-cx_Oracle/issues/439 for the cx_oracle source.

**Comment by zzzeek** [comment]
I don't see where that was cut and pasted from cx_Oracle, cx_oracle.py is part of SQLAlchemy's source code.   Pretty sure I wrote that likely a few days ago in 3ab5e3781b

**Comment by thorstenkampe** [comment]
You're absolutely correct. I already close the ticket with the `cx_oracle` team.

**Comment by RamonWill** [comment]
Hey Guys,

I can take on this one, I did a quick search and found the same typo in multiple files
Kind regards,
Ramon
