### ISSUE TITLE
Memory overflow when loading data into a SQL Server Database when looping

### ISSUE THREAD

**Issue by bmader12** [sqlalchemy/sqlalchemy#5334]
I have written a python script that reads files one-by-one out of a blob storage account, reformat them into a data frame and then writes them to a SQL Server DB using SQL Alchemy for daily log files.

Each file is 300K - 900K records and each day can have up to 75 files. The problem comes in that the VM I am running the code on runs out of memory at right around file 50. Using tracemalloc I have found that the file 
`"C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py:585"`
grows in memory with every loop while nothing else does. gc.collect is called at the end of every loop.

General pseudo code structure is:

```
For blob.name in blob:
     read in files
     log_df = clean files into df
     engine = create_engine('mssql+pyodbc://creds/DB?driver=ODBC Driver 17 for SQL Server', fast_executemany=True)
     log_df.to_sql(table_name,engine,schema='dbo',if_exists='append', chunksize =1000, method=None, index=False)    
     engine.dispose()
     del engine
     del log_df
     gc.collect()
```

I have tried with the engine only being declared once before the loop, as well as using 
```
conn = engine.connect()
df.to_sql(conn, etc)
conn.close()
conn.invaldiate()
```

None of those impacted the memory buildup.

Thank you for your help.

**Comment by zzzeek** [comment]
hi there -

this issue is not related to the "Engine" and is instead related to the "log_df.to_sql" function which I would assume is from Pandas.   the function is likely passing a too-large set of rows to be executed at once and this causes too much memory to be used at once.   functions like engine.dispose() only remove TCP connections, which do not store data related to SQL statements themselves.

you would need to use a chunking strategy as detailed at https://stackoverflow.com/questions/24007762/python-pandas-using-to-sql-to-write-large-data-frames-in-chunks.

**Comment by bmader12** [comment]
Hi,

Thank you for the quick response.

Just to clarify, it does successfully execute and write to the DB ~50 times, it is not an issue with the amount of memory required to write. 

Something is not getting cleared in memory after each loop and eventually the system runs out of memory.

Do you have any suggestions of approaches to release all memory? Or clear the data related to the SQL statements? (is it possible it is not clearing the echo statement after each write or something along those lines?)

Thank you for the help!

**Comment by zzzeek** [comment]
> Hi,
> 
> Thank you for the quick response.
> 
> Just to clarify, it does successfully execute and write to the DB ~50 times, it is not an issue with the amount of memory required to write.

if you are passing datasets that are of variable size, the larger ones may fail while the smaller ones do not.


> 
> Something is not getting cleared in memory after each loop and eventually the system runs out of memory.
> 
> Do you have any suggestions of approaches to release all memory? Or clear the data related to the SQL statements? (is it possible it is not clearing the echo statement after each write or something along those lines?)

there is no data accumulated by SQLAlchemy for this operation.  You'll have to report an issue with the PyODBC driver as that's where such an issue would be.  However, they will point you back to Pandas as well as PyODBC does not accumulate data either.    There's no data accumulation anywhere for the operation you are doing outside of the call to execute() itself, which suggests a too-large set of data is being passed.

**Comment by CaselIT** [comment]
As asked in the template, having the sqlalchemy, python and os versions would help. Also having the exception log would help.

The line you mentioned points to a black line in the current sqlalchemy version
https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_17/lib/sqlalchemy/engine/default.py#L585

As mike asked, are the dataset all of the same size?
Could you provide a script to generate mock data that has the same problem with growing memory in the for loop?

**Comment by zzzeek** [comment]
feel free to reopen if there's more detail.

**Comment by solleer** [comment]
I am also encountering this issue. When I remove the to_sql call the program no longer accumulates memory but when I leave the line it progressively increases memory usage.

**Comment by CaselIT** [comment]
without a reproducible example there is not much we are able to do.

**Comment by solleer** [comment]
It has something to do with `fast_executemany=True` when creating the engine, when I have it set to false it does not accumulate memory but when it is true it does.

ex code
```
for file_name in file_names:
    df = pd.read_csv(file_name)
    conn = create_engine(conn_str, fast_executemany=True)
    df.to_sql(table_name, con=conn.connect(), chunksize=10000)
    conn.dispose()
```
It accumulates memory whether `create_engine` is called during the loop or before

**Comment by zzzeek** [comment]
ah good catch.   welp I have no idea what that flag does, people wanted it, it's documented here: https://github.com/mkleehammer/pyodbc/wiki/Features-beyond-the-DB-API#fast_executemany .

I would definitely take this up with the pyodbc folks.

**Comment by zzzeek** [comment]
I'll jsut add a dragon for that....even though people are strating to complain about the dragons

**Comment by zzzeek** [comment]
pyodbc should not be putting the whole set of data into memory at once, it should be chunking

**Comment by CaselIT** [comment]
I think there's a indentation typo in `driver in order to use this flag:`. It gets formatted badly https://docs.sqlalchemy.org/en/13/dialects/mssql.html?highlight=fast_executemany#fast-executemany-mode

**Comment by CaselIT** [comment]
Maybe the issue should be moved to the ms pyodbc driver?

@bmader12 did you also use `fast_executemany=True`?

**Comment by zzzeek** [comment]
blah

**Comment by zzzeek** [comment]
I pinged them at https://github.com/mkleehammer/pyodbc/issues/547#issuecomment-668625338 and there are many fast_executemany issues with similar themes just sitting opened for multiple years.   so doesn't look like much is happening there.

**Comment by gordthompson** [comment]
@solleer - Your [example code](https://github.com/sqlalchemy/sqlalchemy/issues/5334#issuecomment-668612897) is already using the `chunksize` option of [to_sql](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html). Are you saying that it is not effective in limiting the amount of memory that your app is consuming?

**Comment by solleer** [comment]
@gordthompson correct
If you create any engine with `fast_executemany=True` and run `to_sql` then it increases the memory used minimum from then on while the script runs. I also ran it where I just generated the same large dataframe each time and the memory consumption went up after every call to `to_sql`

**Comment by gordthompson** [comment]
@solleer - Okay, so memory usage increases with each `to_sql` call, but does `chunksize` reduce the memory requirement for a single `to_sql` call when `fast_executemany` is enabled? In other words, if you have a very large DataFrame with a bazillion rows does `to_sql` trigger a MemoryError without `chunksize` but is able to complete when `chunksize` is used?

**Comment by solleer** [comment]
No matter the chunk size, the memory accumulation occurs. I've tried having no chunk size too and the memory accumulation occurs every time. Currently the difference between having `fast_executemany=True` and it being false is that when it is true each successive call to to_sql has an increased memory usage as a starting point when if it is false then the emory usage drops down to previous levels after each call instead of increasing.

**Comment by gordthompson** [comment]
@solleer - I am unable to reproduce your issue using vanilla pyodbc, so it's fairly safe to say that there is no memory leak in pyodbc itself:

``` python
cnxn = pyodbc.connect(connection_string, autocommit=True)
process = psutil.Process()

def printmem(msg):
    mb = process.memory_info().vms / 1048576
    print(f"{msg}: {mb:0.1f} MiB")

printmem("startup")
crsr = cnxn.cursor()
data = crsr.execute("SELECT * FROM MillionRows").fetchall()
crsr.close()
printmem("data loaded")

ins = "INSERT INTO #tmp (ID, TextField, LongIntegerField, DoubleField, varchar_column) VALUES (?,?,?,?,?)"
for iteration in range(5):
    crsr = cnxn.cursor()
    crsr.execute("DROP TABLE IF EXISTS #tmp")
    crsr.execute("CREATE TABLE #tmp (ID int primary key, TextField nvarchar(50), LongIntegerField int, DoubleField float, varchar_column varchar(100))")
    crsr.fast_executemany = True
    crsr.executemany(ins, data)
    crsr.close()
    printmem(f"iteration {iteration}")
"""console output:
startup: 6.9 MiB
data loaded: 190.1 MiB
iteration 0: 251.7 MiB
iteration 1: 251.6 MiB
iteration 2: 251.6 MiB
iteration 3: 251.7 MiB
iteration 4: 251.6 MiB
iteration 5: 251.6 MiB
iteration 6: 251.6 MiB
iteration 7: 251.6 MiB
iteration 8: 251.6 MiB
iteration 9: 251.6 MiB
"""
```

Next thing I'll try is to do a similar test with just SQLAlchemy. Stay tuned ....

**Comment by gordthompson** [comment]
@solleer  - Nope, no memory bloat with just SQLAlchemy:

``` python
import psutil
import sqlalchemy as sa

engine = sa.create_engine("mssql+pyodbc://mssqlLocal64", isolation_level="AUTOCOMMIT", fast_executemany=True)
process = psutil.Process()

def printmem(msg):
    mb = process.memory_info().vms / 1048576
    print(f"{msg}: {mb:0.1f} MiB")

printmem("startup")
with engine.connect() as conn:
    data = conn.execute("SELECT * FROM MillionRows").fetchall()
printmem("data loaded")

ins = "INSERT INTO #tmp (ID, TextField, LongIntegerField, DoubleField, varchar_column) VALUES (?,?,?,?,?)"
for iteration in range(10):
    with engine.connect() as conn:
        conn.execute("DROP TABLE IF EXISTS #tmp")
        conn.execute("CREATE TABLE #tmp (ID int primary key, TextField nvarchar(50), LongIntegerField int, DoubleField float, varchar_column varchar(100))")
        conn.execute(ins, data)
    printmem(f"iteration {iteration}")
"""console output:
startup: 15.9 MiB
data loaded: 387.8 MiB
iteration 0: 450.3 MiB
iteration 1: 450.5 MiB
iteration 2: 450.7 MiB
iteration 3: 450.7 MiB
iteration 4: 450.7 MiB
iteration 5: 450.7 MiB
iteration 6: 450.7 MiB
iteration 7: 450.7 MiB
iteration 8: 450.7 MiB
iteration 9: 450.7 MiB
"""
```

You may want to open a pandas issue.

**Comment by gordthompson** [comment]
@solleer - Okay, so throwing `to_sql` into the mix does cause memory consumption to increase for each iteration and, at least for my test DataFrame, slows down the process significantly.

``` python
import pandas as pd
import psutil
import sqlalchemy as sa

engine = sa.create_engine("mssql+pyodbc://mssqlLocal64", isolation_level="AUTOCOMMIT", fast_executemany=True)
process = psutil.Process()

def printmem(msg):
    mb = process.memory_info().vms / 1048576
    print(f"{msg}: {mb:0.1f} MiB")

printmem("startup")
df = pd.read_sql_query("SELECT * FROM MillionRows", engine)
printmem("data loaded")

for iteration in range(5):
    df.to_sql("pd_test", engine, index=False, if_exists="replace")
    printmem(f"iteration {iteration}")
"""console output:
startup: 139.4 MiB
data loaded: 445.0 MiB
iteration 0: 637.0 MiB
iteration 1: 762.3 MiB
iteration 2: 887.1 MiB
iteration 3: 1011.8 MiB
iteration 4: 1136.5 MiB
"""
```

I suspect that it is not a `to_sql` bug *per se*, but rather an unfortunate interaction between `to_sql` and `fast_executemany` under certain circumstances. There are conditions that can negate (at least some of) the benefits of `fast_executemany`, for example as discussed [here](https://github.com/mkleehammer/pyodbc/issues/500) and [here](https://github.com/mkleehammer/pyodbc/issues/741). If using `to_sql` directly is not satisfactory then consider a workaround like dumping the DataFrame to a CSV file and then using [BULK INSERT](https://docs.microsoft.com/en-us/sql/t-sql/statements/bulk-insert-transact-sql?view=sql-server-ver15) to upload it.

**Comment by CaselIT** [comment]
We should probably raise this issue in pandas.
@gordthompson Have you already done so?

**Comment by gordthompson** [comment]
> 
> 
> We should probably raise this issue in pandas.
> @gordthompson Have you already done so?

Not yet; I'd want to at least give them a manageable MCVE to work with. There's also the question of whether pandas is giving pyodbc something that is "wrong" vs. something that pyodbc "doesn't particularly like for some reason".

**Comment by gordthompson** [comment]
@solleer - Okay, so `to_sql` defaults to `varchar(max)` columns for strings and that appears to be the cause of the memory bloat (see pyodbc issue above). You can limit the width of your varchar columns with `dtype={"your_text_column": sa.String(255)}` or similar.
