### ISSUE TITLE
Querying ORM objects on query_expression

### ISSUE THREAD

**Issue by iSplasher** [sqlalchemy/sqlalchemy#5337]
**Describe your question**

Hello I have a question regarding `query_expression` #3058
It seems to me that this is not supported:
```python
class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)
    child_for_user = query_expression()
    children = relationship("Child", back_populates="parent", lazy="dynamic")

class Child(Base):
    __tablename__ = 'child'
   id = Column(Integer, primary_key=True)
   parent_id = Column(Integer, ForeignKey('parent.id'), nullable=False)
   user_id = Column(Integer)
   some_specific_user_data = Column(Integer)

# class User(Base)...

if __name__ == '__main__':
   sess.query(Parent).option(with_expression(Parent.child_for_user, sess.query(Child).filter(Child.user_id == 1).as_scalar())).first()

```
Results in a rightfully: `sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) subquery must return only one column`

Of course this could be solved by using `hybrid_property`, but then you'll have an additional SQL query for each `Parent`, which in the case of thousands of parent objects will be very expensive.

My question is, since `query_expression` doesn't seem to support this feature, what other ways are there to achieve this?

**Have a nice day!**

**Comment by zzzeek** [comment]
this would be awkward but you could make Parent.child_for_user into a viewonly relationship, then use contains_eager to get what you want.

demo:
```

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import contains_eager
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")
    b_for_a = relationship("B", viewonly=True, uselist=False)


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

a1 = A()
b1 = B()
a1.bs = [b1]
s.add(a1)
s.commit()


a1 = (
    s.query(A)
    .join(A.bs)
    .filter(B.id == 1)
    .options(contains_eager(A.b_for_a))
    .first()
)

assert a1.b_for_a is b1


```

**Comment by iSplasher** [comment]
Thank you very much for helping.
I just want to make sure, in the case that `B.id == 1` does not exists, the query would return `None`, right?
Is there a way to return the `A` object irrespectively of `B.id == 1` existence, like in the case of how `with_expression` would still return the object just with the attribute set to `None`?

Maybe this is just a case of bad design on my part? I'm not very experienced with designing SQL tables, maybe a different design that could allow this kind query exists?

**Comment by zzzeek** [comment]
> Thank you very much for helping.
> I just want to make sure, in the case that `B.id == 1` does not exists in the collection, the query would return `None`, right?

correct


> Is there a way to return the `A` object irrespectively of `B.id == 1` existence, like in the case of how `with_expression` would still return the object just with the attribute set to `None`?

yes, use query.outerjoin() instead of query.join()

> 
> Maybe this is just a case of bad design on my part? I'm not very experienced with designing SQL tables, maybe a different design that could allow this kind query exists?

I don't see much going on here with SQL that is unusual, it's just you want to have a single object returned that munges together two pieces of information at the same time rather than getting two separate objects that is a little awkward more from a Python point of view.

that is, you can just do this:

    row = query(A, B).outerjoin(A.bs).filter(B.whatever == 'anything').first()

then youd' get a tuple either (some_a, some_b) or (some_a, None).

**Comment by iSplasher** [comment]
Okay thank you,
One last question then, there is no way currently to have it be prepopulated on an attribute on an `A` object?

**Comment by zzzeek** [comment]
the example I gave pre-populates it using contains_eager().

**Comment by iSplasher** [comment]
Right, thank you
