### ISSUE TITLE
Documentation points to unreleased feature as having been released

### ISSUE THREAD

**Issue by boyntoni** [sqlalchemy/sqlalchemy#5338]
**Describe the bug**

The [documentation states](https://docs.sqlalchemy.org/en/13/core/selectable.html#sqlalchemy.sql.expression.table) that `schema` has been added to the `table` expression as of release `1.3.17`, however this is [not the case](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_17/lib/sqlalchemy/sql/selectable.py#L1937). The `master` branch [does](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/selectable.py#L1928) have it implemented, along with the incorrect version.

**Expected behavior**
Documentation accurately reflects feature set of a release.

**To Reproduce**
N/A

**Additional context**
N/A

**Have a nice day!**

**Comment by zzzeek** [comment]
thank you
