### ISSUE TITLE
TIME parameter from filter is changed to DATETIME in the query

### ISSUE THREAD

**Issue by Vaelek** [sqlalchemy/sqlalchemy#5339]
I cannot for the life of me get SA to filter a TIME column without treating it as a DATETIME.

I have the class defined as

    class v_MyView(Base):
      __table__ = Table('MyView', Base.metadata,
        Column('id', Integer, primary_key=True),
        Column('EntryDateTime', DateTime),
        Column('EntryDate', Date),
        Column('EntryTime', Time),
        ...

If I do this

    results = db.query(v_MyView).first()
    print(results.EntryTime)

I get `datetime.time(15, 30, 22, 560000)` as expected

However if I do this

    results = db.query(v_MyView).filter(v_MyView.EntryTime >= datetime.time(5,0)).first()
    print(results.EntryTime)

I get an error

    [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The data types time and datetime2 
    are incompatible in the greater than or equal to operator. (402) (SQLExecDirectW)

And looking at the generated query, I see

    WHERE [v_MyView].[EntryTime] >= ?]
    [parameters: (datetime.datetime(1900, 1, 1, 5, 0),)]

Examining the filter it appears to be generated correctly

    right: BindParameter('%(140718484304128 EntryTime)s', datetime.time(5, 0), type_=Time())

**Comment by zzzeek** [comment]
the TIME datatype for SQL server has a hardcoded behavior to convert to a datetime with "1900", and this is based on whatever the drivers were doing when this was last worked on.  it may be that the pyodbc driver doesn't support "time" directly but someone would need to spend some time looking into this.

short term solution is to use cast:   

    from sqlalchemy import cast
    query.filter(my_column >= cast(datetime.time(5, 0), TIME))  

etc

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Stop converting mssql datetime.time parameters to datetime.datetime** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1992

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Stop converting mssql datetime.time parameters to datetime.datetime** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2002
