### ISSUE TITLE
performance issue in master

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5340]
it seems very likely something went wrong in the result/cursor refactor.

here is 1.3 with C extensions:

```
[classic@photon3 sqlalchemy]$ python -m examples.performance large_resultsets --test test_core_fetchall --profile
Running setup once...
Tests to run: test_core_fetchall
test_core_fetchall : Load Core result rows using fetchall. (500000 iterations); total fn calls 420

```

here is 1.4:

```
[classic@photon3 sqlalchemy]$ python -m examples.performance large_resultsets --test test_core_fetchall --profile
Running setup once...
Tests to run: test_core_fetchall
test_core_fetchall : Load Core result rows using fetchall. (500000 iterations); total fn calls 9000484

```

something is clearly going extremely wrong on a per-row basis and hopefully it's trivial to fix.

**Comment by zzzeek** [comment]
and the profiling tests dont' show it at all!  wtf

1.3's test resulset, here's 1000 rows

test.aaa_profiling.test_resultset.ResultSetTest.test_string 3.7_sqlite_pysqlite_dbapiunicode_cextensions 479

1.4:

test.aaa_profiling.test_resultset.ResultSetTest.test_string 3.7_sqlite_pysqlite_dbapiunicode_cextensions 481

this generates a tuple from the result, so it is fully fetching

?!!?

**Comment by zzzeek** [comment]
OK this might be the deprecation warnings doing this, will have to scale these back, the performance example isn't using mappings(), that cuts it in half so far

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Performance fixes for new result set** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1986

**Comment by zzzeek** [comment]
Finding a lot of things and have mostly solved the problem, but we are still slower in orm2010.py for some reason even if I turn off uniquing, which is very weird.

**Comment by zzzeek** [comment]
OK lots of fixes, however there is a fundamental, very slight slowdown in the mechanics of Row, which bisect shows is directly due to cc718cccc where we reorganized row.  the previous approach of proxying to the original row simply has a little less overhead than our current approach of copying into a tuple, however what seems odd is that the profiling seems to claim it occurs at the tuple-access point, not at the row creation point.   not sure if this is an artifact of the profiling, or perhaps it has to do with Python allocating more memory to make a copy of the tuple.   We can look into maintaining some "proxy to tuple" beahvior in resultproxy.c, particularly if we don't have any processors which is going to be much more often the case, however trying to do this quickly was running into problems.    the current symptom is consuming 50000 rows and producing ORM objects from them is taking .75 seconds rather than about .65, so a tenth of a second per 50K rows in a heavy ORM context.   the simplicity of Row now is still likely worth it and we should just look into refining it to not copy the tuple if it doesn't need to, but this is not urgent.

**Comment by CaselIT** [comment]
Just checked before and after on windows, without cexts:

before: `test_core_fetchall : Load Core result rows using fetchall. (500000 iterations); total fn calls 13000490` `13000490 function calls (13000477 primitive calls) in 8.752 seconds`
after: `test_core_fetchall : Load Core result rows using fetchall. (500000 iterations); total fn calls 5500486` `5500486 function calls (5500473 primitive calls) in 4.092 seconds`
👍

**Comment by CaselIT** [comment]
Looking at `row.py` there are some easy win that let us remove 250k function calls

`test_core_fetchall : Load Core result rows using fetchall. (500000 iterations); total fn calls 2500486`
`2500486 function calls (2500473 primitive calls) in 3.430 seconds`

```diff
diff --git a/lib/sqlalchemy/engine/row.py b/lib/sqlalchemy/engine/row.py
index d279776ce..2d4045da4 100644
--- a/lib/sqlalchemy/engine/row.py
+++ b/lib/sqlalchemy/engine/row.py
@@ -103,7 +103,7 @@ except ImportError:
         def __getitem__(self, key):
             return self._data[key]
 
-        def _subscript_impl(self, key, ismapping):
+        def _subscript_impl(self, key, ismapping=False):
             try:
                 rec = self._keymap[key]
             except KeyError as ke:
@@ -132,8 +132,7 @@ except ImportError:
 
             return self._data[mdindex]
 
-        def _get_by_key_impl(self, key):
-            return self._subscript_impl(key, False)
+        _get_by_key_impl = _subscript_impl
 
         def _get_by_key_impl_mapping(self, key):
             # the C code has two different methods so that we can distinguish
@@ -322,6 +321,13 @@ class Row(BaseRow, collections_abc.Sequence):
         raise NotImplementedError()
 
 
+def _add_getitem(cls):
+    if not _baserow_usecext:
+        cls.__getitem__ = cls._get_by_key_impl
+    return cls
+
+
+@_add_getitem
 class LegacyRow(Row):
     """A subclass of :class:`.Row` that delivers 1.x SQLAlchemy behaviors
     for Core.
@@ -347,11 +353,6 @@ class LegacyRow(Row):
     def __contains__(self, key):
         return self._parent._contains(key, self)
 
-    if not _baserow_usecext:
-
-        def __getitem__(self, key):
-            return self._get_by_key_impl(key)
-
     @util.deprecated(
         "1.4",
         "The :meth:`.LegacyRow.has_key` method is deprecated and will be "
@@ -482,6 +483,7 @@ class ROMappingView(
         return list(other) != list(self)
 
 
+@_add_getitem
 class RowMapping(BaseRow, collections_abc.Mapping):
     """A ``Mapping`` that maps column names and objects to :class:`.Row` values.
 
@@ -510,9 +512,6 @@ class RowMapping(BaseRow, collections_abc.Mapping):
 
     if not _baserow_usecext:
 
-        def __getitem__(self, key):
-            return self._get_by_key_impl(key)
-
         def _values_impl(self):
             return list(self._data)
 ```

**Comment by CaselIT** [comment]
ok, this is really strange
```
In [1]: %timeit tuple(i for i in range(10000))
578 µs ± 23.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
In [2]: %timeit tuple([i for i in range(10000)])
409 µs ± 14.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by sqla-tester** [comment]
**Federico Caselli** referenced this issue:

**Avoid proxy functions in row functions** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1991

**Comment by zzzeek** [comment]
feel free to play with it this is the area where Python gets really temperamental :)     note there's nothing we have to worry about for the BaseRow Python implementation since that's not used when we use the C extensions.   not sure if that patch is on BaseRow pure python impl.

**Comment by CaselIT** [comment]
yes they affect the python version of BaseRow, so not greatly important, especially now that we build weels, but still workwhile since it's basically for free.
In the gerrit I've added a few other minor changes
