### ISSUE TITLE
Query strings are not escaped in engine URLs

### ISSUE THREAD

**Issue by miguelgrinberg** [sqlalchemy/sqlalchemy#5341]
**Describe the bug**

The `URL` class correctly processes escaped characters in the query string when parsing an input URL, but does not apply the escaping when returning this URL back.

Example:

```
>>> from sqlalchemy.engine.url import make_url
>>> url = make_url('sqlite:///db.sqlite?foo%3dbar=+baz')
>>> url.query
{'foo=bar': ' baz'}
>>> str(url)
'sqlite:///db.sqlite?foo=bar= baz
```
**Expected behavior**

The expected result for the last expression in the example above is:

```
>>> str(url)
'sqlite:///db.sqlite?foo%3Dbar=+baz
```

**To Reproduce**

See example above.

**Error**

N/A

**Versions.**
 - OS: all
 - Python: all
 - SQLAlchemy: 1.3.17
 - Database: all
 - DBAPI: all

**Additional context**

Related issue in Flask-Migrate: https://github.com/miguelgrinberg/Flask-Migrate/issues/328.

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Miguel Grinberg** has proposed a fix for this issue in the **master** branch:

**Fix query string escaping in engine URLs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1989

**Comment by sqla-tester** [comment]
**Miguel Grinberg** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix query string escaping in engine URLs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1990
