### ISSUE TITLE
SQL-expression is not wrapped by brackets when 'type_coerce()' is used

### ISSUE THREAD

**Issue by theosotr** [sqlalchemy/sqlalchemy#5344]
**Describe the bug**

It seems to me that `sqlalchemy` does not wrap an SQL expression with brackets when the function `type_coerce()` is used.

I have the following query

```python
mulExpr = type_coerce((Model.a * Model.b), types.Float).label('mulExpr')
divExpr = (Model.c / mulExpr).label('divExpr')
session.query(divExpr, mulExpr).select_from(Model)
```

The code generates the following SQL query when I ran it on `sqlite`.

```sql
SELECT Model.c / Model.a * Model.b AS "divExpr", Model.a * Model.b AS "mulExpr"
FROM listing
```

However, I would expect the following query instead where the sub-expression `Model.a * Model.b` is wrapped by brackets.

```sql
SELECT Model.c / (Model.a * Model.b) AS "divExpr", Model.a * Model.b AS "mulExpr"
FROM listing
```

Note that this issue only occurs when the function `type_coerce()` is applied to the sub-expression.

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,
You can use [self_group](https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.expression.ColumnElement.self_group) to ensure parenthesis are used.

**Comment by zzzeek** [comment]
self_group is likely what's broken here.

For the moment work around as:

```
from sqlalchemy.sql.elements import Grouping
expr = Grouping(type_coerce(...))
```

**Comment by zzzeek** [comment]
here's a test case that shows where this should be consistent:

```
from sqlalchemy import column, type_coerce, Integer, cast


a = column("a") / (column("b") * column("c"))
b = column("a") / cast(column("b") * column("c"), Integer)
c = column("a") / type_coerce(column("b") * column("c"), Integer)


print(a)
print(b)
print(c)
```

proposed fix, needs to defer to the inner expression for correct grouped behavior:

```
diff --git a/lib/sqlalchemy/sql/elements.py b/lib/sqlalchemy/sql/elements.py
index 43115f117..059b054d4 100644
--- a/lib/sqlalchemy/sql/elements.py
+++ b/lib/sqlalchemy/sql/elements.py
@@ -2893,6 +2893,12 @@ class TypeCoerce(WrapsColumnExpression, ColumnElement):
     def wrapped_column_expression(self):
         return self.clause
 
+    def self_group(self, against=None):
+        grouped = self.clause.self_group(against=against)
+        if grouped is not self.clause:
+            return TypeCoerce(grouped, self.type)
+        else:
+            return self
 
 class Extract(ColumnElement):
     """Represent a SQL EXTRACT clause, ``extract(field FROM expr)``."""

```

**Comment by CaselIT** [comment]
I'll look into this, since the documentation could also be improved for type_coerce, since it's not super clear why one should use it

**Comment by CaselIT** [comment]
The documentation is not correct regarding the anon_1 label:
```py
stmt = select([
                type_coerce(log_table.date_string, StringDateTime())
            ])
```
now renders 
```sql
SELECT date_string AS date_string FROM log
```
not `anon_1` as stated in the docs

**Comment by CaselIT** [comment]
Interestingly 
```py
stmt = select([
                type_coerce(log_table.date_string, StringDateTime())
                type_coerce(log_table.date_string, Time())
            ])
```
renders
```sql
SELECT date_string AS date_string, date_string AS date_string FROM log
``
but the processing happens correctly

**Comment by zzzeek** [comment]
yeah those anon_1 / label things change quite often, if you don't set an explicit label it's not defined what the format of an anonymous label will be so this is not critical

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Correctly apply self_group in type_coerce element.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1998

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Correctly apply self_group in type_coerce element.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1999
