### ISSUE TITLE
Generated query with bind params has nvarchar even though the database doesn't support it?

### ISSUE THREAD

**Issue by varmanishant** [sqlalchemy/sqlalchemy#5345]
**Describe the bug**

In Python 3, the following query with bind params `('number', 1)` generates a raw query (checked with SQL Server Profiler) that has `nvarchar` in it even thought our column is not `nvarchar` and our DB uses `Latin1_General_CI_AS` collation:

#### Query Before
```py
select_parametrized = """
SELECT * FROM products
JOIN sales ON products.idn = sales.pid
AND sales.type = ?
WHERE products.idn in (?);
```

#### Query After
```sql
declare @p1 int
set @p1=NULL
exec sp_prepexec @p1 output,N'@P1 nvarchar(12),@P2 int',N'
SELECT * FROM products
INNER JOIN sales ON products.idn = sales.pid 
    AND sales.type = @P1
WHERE products.idn in (@P2);
',N'number',1
select @p1
```

**Expected behavior**

Since my column is defined as `VARCHAR`, and the DB collation is `Latin1_General_CI_AS`, it should have generated `VARCHAR` instead?

**To Reproduce**

```py
import sqlalchemy
import sqlalchemy.orm

create_tables = """
CREATE TABLE products(
    idn NUMERIC(9) PRIMARY KEY
);
CREATE TABLE sales(
    idn NUMERIC(9) PRIMARY KEY,
    pid VARCHAR(50) NOT NULL,
    type VARCHAR(10) NOT NULL
);
"""

check_tables_exist = """   
SELECT * FROM products;
SELECT * FROM sales;
"""

insert_values = """
INSERT INTO products (idn) values (1);
INSERT INTO sales (idn, pid, type) values (1, 1, 'number');
INSERT INTO sales (idn, pid, type) values (2, 'Colgate', 'word');
"""

select_adhoc = """
SELECT * FROM products
JOIN sales ON products.idn = sales.pid
AND sales.type = 'number'
WHERE products.idn in (1);
"""

select_parametrized = """
SELECT * FROM products
JOIN sales ON products.idn = sales.pid
AND sales.type = ?
WHERE products.idn in (?);
"""

delete_tables = """
DROP TABLE products;
DROP TABLE sales;
"""

engine = sqlalchemy.create_engine('mssql+pyodbc://user:password@dsn')
connection = engine.connect()
cursor = engine.raw_connection().cursor()

Session = sqlalchemy.orm.sessionmaker(bind=connection)
session = Session()

session.execute(create_tables)

try:
    session.execute(check_tables_exist)
    session.execute(insert_values)
    session.commit()
    print(cursor.execute(select_adhoc).fetchall())
    print(cursor.execute(select_parametrized, ('number', 1)).fetchall())
finally:
    session.execute(delete_tables)
    session.commit()
```

**Error**

```
Traceback (most recent call last):
  File "reproduce.py", line 59, in <module>
    print(cursor.execute(select_parametrized, ('number', 1)).fetchall())
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error converting data type varchar to numeric. (8114) (SQLFetch)
```

**Versions.**
 - OS: Linux
 - Python: Python 3.8
 - SQLAlchemy: Latest
 - Database: MSSQL Server
 - DBAPI: MSODBC 17 with UnixODBC

**Additional context**

Python 2 does this correctly. Python 3 also works fine if I use `b'number'`, but is there a better way to make it work? It is hard to do this conversion **everywhere** and seems like a wrong thing to do. I tried `convert_unicode=False`, but that didn't help.

We are trying to migrate our app to Python 3, so would like to minimize the changes involved. At some later point we might re-design the schema to avoid getting into such issues, but it will really help if we can get a good work-around for now.

Thanks for your help!

**Comment by CaselIT** [comment]
You are using a raw cursor, so I think that the problem is of the dbapi you are using.

Have you tried using `session.execute` to run the selects?

**Comment by varmanishant** [comment]
Thanks for checking, @CaseIIT. Normally we use the ORM layer, since we were getting the issue, I `stepped` inside to see the exact query generated internally.

`session.execute` also seems to produce the same result (hope it is the correct way):

```py
select_parametrized = """
SELECT * FROM products
JOIN sales ON products.idn = sales.pid
AND sales.type = :type
WHERE products.idn in (:idns);
"""
```

```py
session.execute(select_parametrized, {'type:' 'number', 'idns': 1}).fetchall()
```

**Comment by gordthompson** [comment]
What you are seeing is pyodbc operating as designed. Since strings are always Unicode in Python_3, pyodbc calls the "wide" versions of the ODBC functions whenever possible. 

> even though the database doesn't support it?

All SQL Server databases support Unicode. You're talking about a particular column that is defined as `varchar` instead of `nvarchar`. In that case pyodbc leaves it up to the ODBC driver and the SQL Server instance to sort it out, mapping Unicode characters to the specific code page (SBCS) where possible and rendering un-mappable characters as '?'

```python
cnxn = engine.raw_connection()  # mssql+pyodbc://...
crsr = cnxn.cursor()
crsr.execute("DROP TABLE IF EXISTS thing")
crsr.execute("CREATE TABLE thing (id int PRIMARY KEY, item varchar(50))")
item = "beer"
crsr.execute("INSERT INTO thing (id, item) VALUES (?, ?)", 1, item)
item = "café"
crsr.execute("INSERT INTO thing (id, item) VALUES (?, ?)", 2, item)
item = "водка"
crsr.execute("INSERT INTO thing (id, item) VALUES (?, ?)", 3, item)
print(crsr.execute("SELECT * FROM thing").fetchall())
# [(1, 'beer'), (2, 'café'), (3, '?????')]
```

**Comment by varmanishant** [comment]
Thanks @gordthompson , so should I send the `string` object as `bytes` i.e (`string.encode('latin1')` because my database is `Latin 1`) to avoid PyODBC's default behavior? If so, is there a hook that could do this for all the `string` bind param's so that I can avoid modifying the code everywhere?! We could just remove it when we start using `nvarchar`. Even if I can specify something at the SQLAlchemy column definition, that would work as well (we actually create it via SQLAlchemy and not raw `create` like the above example).

**Comment by gordthompson** [comment]
pyodbc has [setinputsizes](https://github.com/mkleehammer/pyodbc/wiki/Cursor#setinputsizeslist_of_value_tuples) to fine-tune the parameter types, e.g.,

```python
cnxn = engine.raw_connection()
crsr = cnxn.cursor()
sql = "SELECT id FROM MillionRows WHERE varchar_column = ?"
value = "record123456"

result = crsr.execute(sql, value).fetchval()
```

... produces an `nvarchar` parameter value, whereas ...

```python
# ...

crsr.setinputsizes([(pyodbc.SQL_VARCHAR, 255)])
result = crsr.execute(sql, value).fetchval()
```

... produces a `varchar` parameter value. 

I see that support for `setinputsizes` has been included in the `oracle+cx_oracle` dialect, so it is *possible*; it just hasn't made it into the `mssql+pyodbc` dialect yet. In the meantime, encoding your strings first might be the most expedient approach.

**Comment by zzzeek** [comment]
you can use CAST(value, VARCHAR) too, that should work and that's probably what we usually do in this kind of situation.

**Comment by varmanishant** [comment]
Thank you @gordthompson and @zzzeek . I think I will probably consider moving to `NVARCHAR`; or else use `CAST(value, VARCHAR)' since it is more easier to read.

**Comment by varmanishant** [comment]
As mentioned above, this will not cause an issue in most of the normal scenarios - so closing it!

**Comment by D00mSlayer** [comment]
Hello! Its 2023 and I have this issue as well.
Stack:
Python - 3.10
PyODBC - 4.0.35
SQLAlchemy - 1.3.17
MS_ODBC Driver - v17

95% of my columns are VARCHAR and the parameters are cast as NVARCHAR when the cursor is executed.
How do i fix this because it used to work fine in Python 2.7.
