### ISSUE TITLE
Update profiles to python 3.8

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5347]
The ci now uses python 3.8 but the profiles are still for python 3.7.

**Comment by CaselIT** [comment]
github seems to have problem at the moment.
Added a patch here https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1997

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add python 3.8 profiles** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1997
