### ISSUE TITLE
row object needs GC in the C implementation

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5348]
Today I learned about the GC library calls in the C api.   we will need to add these to resultproxy.c now that we have ORM objects coming out in rows, because if the row itself is referred to by an object you can get a cycle quite easily.  the program below blows up memory immediately:

```

from sqlalchemy.engine import result

tup = result.result_tuple(['a', 'b', 'c'])


while True:

    obj = {"foo": {}}
    obj['foo']['bar'] = obj

    row = tup([1, 2, obj])

    obj['foo']['row'] = row

    del row



```

**Comment by craigds** [comment]
Is this issue specific to SQLalchemy 1.4.x  by any chance?

We see a noticeable increase in memory usage on our server when using sqlalchemy 1.4.x (stabilises at ~1GB RES), compared to much lower memory usage when using sqlalchemy 1.3.x (stabilises at ~260 MB RES)

**Comment by zzzeek** [comment]
I believe this issue was fixed and I forgot to tag it, but I'd have to try the above test case to be sure.

SQLAlchemy 1.4 will use more memory due to [compiled SQL caching](https://docs.sqlalchemy.org/en/14/core/connections.html#sql-compilation-caching); try turning that cache size down or off to see if memory decreases closer to what you had in 1.3.    Otherwise the greater memory use is expected depending on the nature of the application.

also try testing without the C extensions.  you can install without them as documented in https://docs.sqlalchemy.org/en/14/intro.html#installing-the-c-extensions or just delete the .so files from the python environment.  if memory use changes significantly for the better based on no C extensions alone, then that's something very urgent to report to us :) .

**Comment by zzzeek** [comment]
OK, unfortunately this didnt get tagged and the above test case still causes a problem, so we will get that fixed.

that said, I think it's relatively unlikely this is your issue, because first of all the above issue is a pure leak, your memory use wouldn't be stabilizing.   secondly the pattern above creates a cycle from an ORM object to the Row object itself which is very unlikely pattern in a real world application.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use Py_TPFLAGS_HAVE_GC for Row** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2891
