### ISSUE TITLE
add table hints to StrSqlCompiler

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5353]
there's no reason we can't render a generic "with_hint" for StrSQL to avoid the confusion noted in 

https://github.com/sqlalchemy/sqlalchemy/issues/4667#issuecomment-634672973

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Render table hints in generic SQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2008

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Render table hints in generic SQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2009
