### ISSUE TITLE
Flexible **kwarg Definition for DeclarativeMeta base definition

### ISSUE THREAD

**Issue by ewengillies** [sqlalchemy/sqlalchemy#5357]
**Is your feature request related to a problem? Please describe.**

I am using the declarative API and trying to pass arguments to `__init_subclass__` in my "base" ORM that is generated from `declarative_base()`.  

I think code makes this clearest.  Lets first define the base that can do special things to its subclasses without redefining the `metaclass` via the `__init_subclass__` hook (introduced in [PEP 487](https://www.python.org/dev/peps/pep-0487/), exists in python 3.6 and up):
```python
from sqlalchemy.ext.declarative import declarative_base

_Base = declarative_base()
class ORMBase(_Base):
    """
    Define common methods for all tables
    """
    __abstract__ = True

    def __init_subclass__(cls, do_special_thing=False, **kwargs):
        super().__init_subclass__(**kwargs)
        if do_special_thing:
            print("i am a very special subclass")
        else:
            print("I am a normal subclass")
```

If the subclass doesn't touch `do_special_thing`, then all is fine:
```python
>>> class NormalClass(ORMBase):
>>>    pass
I am a normal subclass
```
If I touch the `do_special_thing`, then it gets passed to [`DeclarativeMeta.__init__`](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/ext/declarative/api.py#L71) and fails. I can only assume this is because the `kwargs` that get passed to `__init_subclass__` are the same that get passed to `<metaclass>.__init__`.
```python
>>> class SpeicalClass(ORMBase, do_special_thing=True):
>>>    pass
i am a very special subclass
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-d185419c27b1> in <module>
     15             print("I am a normal subclass")
     16 
---> 17 class SpecialClass(ORMBase, do_special_thing=True):
     18     __abstract__ = True

TypeError: __init__() got an unexpected keyword argument 'do_special_thing'
```

**Describe the solution you'd like**

Solutions I can imagine:
Naively, just adding a `**kwargs` to the [`DeclarativeMeta.__init__`](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/ext/declarative/api.py#L71) solves this.

**Describe alternatives you've considered**

Other solutions I've considered:
  1) Maybe there is a dunder attribute I can use, like `__table_args__`, that is somehow already passed to the `__init_subclass__` hook?  I'm not aware of any, but then again, I'm new to `sqlalchemy` metaclassing, so apologies if I missed something!
  2) I can just pass args to `__init_subclass__` via class attributes, like:
```python
class SpeicalClass(ORMBase):
    do_special_thing=True
```
then anticipate this in the `ORMBase` class.  This will require ugly `try, except` or equivalently `hasattr` checks in `__init_subclass__` for each argument tho, which I'd like to avoid.
 
  3) A mixin class that uses `__int_subclass__`, like this:
```python
from sqlalchemy.ext.declarative import declarative_base

_Base = declarative_base()
class ORMBase: # NOTE now its not a declarative meta
    """
    Define common methods for all tables
    """

    def __init_subclass__(cls, do_special_thing=False, **kwargs):
        super().__init_subclass__(**kwargs)
        if do_special_thing:
            print("i am a very special subclass")
        else:
            print("I am a normal subclass")

class SpecialClass(_Base, ORMBase, do_special_thing=True):
    pass
```
still breaks for the same reason.
 
  4) Define my own metaclass, but that is what I was trying to avoid with `__init_subclass__` to begin with!  Even so, this works:
```python
from sqlalchemy.ext.declarative.api import DeclarativeMeta
from sqlalchemy.ext.declarative import declarative_base

class DeclarativeMetaInitSubclassable(DeclarativeMeta):
    def __init__(cls, classname, bases, dict_, **kwargs):
        super().__init__(classname, bases, dict_)

_Base = declarative_base(metaclass=DeclarativeMetaInitSubclassable)

        
class ORMBase(_Base):
    """
    Define common methods for all tables
    """
    __abstract__ = True

    def __init_subclass__(cls, do_special_thing=False, **kwargs):
        super().__init_subclass__(**kwargs)
        if do_special_thing:
            print("i am a very special subclass")
        else:
            print("I am a normal subclass")

class SpecialClass(ORMBase, do_special_thing=True):
    __abstract__ = True
```

**Additional context**
For clarity, this is not a problem when using regular python.  This works fine:
```python
class ORMBase:
    """
    Define common methods for all tables
    """
    __abstract__ = True

    def __init_subclass__(cls, do_special_thing=False, **kwargs):
        super().__init_subclass__(**kwargs)
        if do_special_thing:
            print("i am a very special subclass")
        else:
            print("I am a normal subclass")

class SpecialClass(ORMBase, do_special_thing=True):
    __abstract__ = True
```
I can only assume its from the [type.__init__](https://github.com/python/cpython/blob/v3.8.0/Objects/typeobject.c#L2245) written here.  Admittedly, this confuses me a little, since there seems to be a check there that `type.__init__` doesn't take `kwargs`.  

**Final comments**
I'm happy to take on writing a PR if the developers think my solution (or any other) are a good idea.

**Have a nice day! Thank you so much for `sqlalchemy`!**

**Comment by zzzeek** [comment]
OK, well, I've never heard of ``__init_subclass__`` before.   I can see why it has taken ten years for inclusion, because on the one hand, you have that it seems to be mostly an implicit way of doing something you can already do, and the pep even has the word "implicit" in the first line of code in the proposal at https://www.python.org/dev/peps/pep-0487/#proposal .   On the other, this hook looks like it is extremely simple and minimal in what it actually does and for the most part, doesn't get in the way of things.    Except that, IIUC they have redefined the [classic metaclass __init__() specification](https://python-3-patterns-idioms-test.readthedocs.io/en/latest/Metaprogramming.html#example-self-registration-of-subclasses) that we've all used for literally decades to now support ``**kw``.   It's a little weird that even today there's not a single example of a metaclass I can find within Python's main documentation and googling it comes up with a bunch of outdated tutorials.

anyway, usually when I see "Python 3 has this new feature I'm trying to use" I kind of panic, but in this case it looks like we just add ``**kw`` to our built in metaclass and we're done.   doesn't seem much harder than that, feel free to submit a PR.

**Comment by ewengillies** [comment]
thanks for the speedy feed back @zzzeek !  Will do.  

> It's a little weird that even today there's not a single example of a metaclass I can find within Python's main documentation and googling it comes up with a bunch of outdated tutorials.

100% agreed.

**Comment by sqla-tester** [comment]
**EwenGillies** has proposed a fix for this issue in the **master** branch:

**Add **kw support to DeclarativeMeta.__init__** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2019

**Comment by sqla-tester** [comment]
**EwenGillies** has proposed a fix for this issue in the **rel_1_3** branch:

**Add **kw support to DeclarativeMeta.__init__** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2073
