### ISSUE TITLE
Closing a connection throws an SAWarning: Reset agent is not active

### ISSUE THREAD

**Issue by altusgerona** [sqlalchemy/sqlalchemy#5361]
**Describe the bug**
Closing a connection throws `SAWarning: Reset agent is not active`

**Expected behavior**
To not throw a warning.

**To Reproduce**
```py
# Code snippet from https://github.com/pytest-dev/pytest-flask/issues/70#issuecomment-361005780
# This is a pytest fixture that handles setUp and rollback of test database
conn = _db.engine.connect()
txn = conn.begin()

options = dict(bind=conn, binds={})
sess = _db.create_scoped_session(options=options)

# establish  a SAVEPOINT just before beginning the test
# (http://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#using-savepoint)
sess.begin_nested()

@event.listens_for(sess(), 'after_transaction_end')
def restart_savepoint(sess2, trans):
    # Detecting whether this is indeed the nested transaction of the test
    if trans.nested and not trans._parent.nested:
        # The test should have normally called session.commit(),
        # but to be safe we explicitly expire the session
        sess2.expire_all()
        sess.begin_nested()

_db.session = sess
yield sess

# Cleanup
sess.remove()
# This instruction rolls back any commit that were executed in the tests.
txn.rollback()
conn.close()
```

**Error**
```
/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py:884: SAWarning: Reset agent is not active.  This should not occur unless there was already a connectivity error in progress.
```
The above occurs after running `pytest` regardless of test outcome.

**Versions.**
 - OS: Arch Linux
 - Python: 3.8
 - SQLAlchemy: 1.3.17
 - Database: Postgres 12
 - DBAPI: psycopg2

**Additional context**
It doesn't seem to cause any issue aside from throwing a warning. I'm glad to have any assistance especially if I seem to be misusing SQLAlchemy. I also thought that #5326 might have something to do with this but after reading the specifics it apparently just throws the same warning.

**Comment by zzzeek** [comment]
this is #5326, which was reopened and then resolved again.   the warning is harmless.  see the note at https://docs.sqlalchemy.org/en/13/changelog/changelog_13.html#change-83bc52ea196dc68a23a1ac36a39f3229 which details the second fix which will be in the next release.

your test case is not complete and I was not able to adjust it to reproduce the warning in 1.3.17, so please confirm github master resolves.  thanks!

**Comment by altusgerona** [comment]
Thank you for the quick update. Yes this warning doesn't happen on master anymore although it did throw a whole slew of other warnings which I guess just comes from the breaking changes that 1.4 will bring? Anyway, thank you very much!

**Comment by zzzeek** [comment]
oh right, that's 1.4 .    Sorry i meant test the 1.3 branch, it's here:  https://github.com/sqlalchemy/sqlalchemy/tree/rel_1_3 .     the fix in 1.3 is relatively small.

**Comment by altusgerona** [comment]
So I tried 1.3.18 and yes the warning now goes away but the other warnings that were not present in .17 still showed up. Maybe this is because I'm using flask-sqlalchemy? 
Also this error,
`AttributeError: 'Namespace' object has no attribute 'write_idents'`

**Comment by zzzeek** [comment]
perhaps you have some other installation issue, or maybe did not install the "master" version of SQLAlchemy completely.   1.3.18 is only a minor set of changes since 1.3.17 and no new warnings are added, please share the exact warnings and all stack traces. the word "write_idents" is part of SQLAlchemy's test fixtures only and is not something you'd be making any use of unless you are testing a third party dialect (nor do I know what Namespace is).

**Comment by altusgerona** [comment]
Probably. But so far the warnings don't show up. I think it's safe to close this for now. Thank you for your help!
