### ISSUE TITLE
sql server schema tokenizing hardcoded to two, loses dots completely

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5366]
in https://docs.sqlalchemy.org/en/13/dialects/mssql.html#multipart-schema-names we describe how to use brackets to set up separate schema sections for SQL server.  however it's hardcoded to lose any additional dots if the brackets aren't used and this is just wrong:

```
from sqlalchemy.dialects.mssql import base


print(
    base._schema_elements("foo.bar.bat.hoho")
)

```

```
python test3.py 
('foo', 'barbathoho')

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Support multiple dotted sections in mssql schema names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2020

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Support multiple dotted sections in mssql schema names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2021
