### ISSUE TITLE
default create_constraint to False for Enum and Boolean types

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5367]
There is an endless stream of issues related to these CHECK constraints that are not worth fixing, and the vast majority of users would rather not deal with them.   the feature will remain in place but if someone wants to turn the constraint on, it's their responsibility to make sure it is named and that they alter their migration techniques as appropriate.

**Comment by CaselIT** [comment]
this would only be for non native boolean/enum, correct?

**Comment by zzzeek** [comment]
yes the CHECK constraint only applies to the "non-native" version of these datatypes.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Default create_constraint to False** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2023
