### ISSUE TITLE
deprecate query.from_self()

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5368]
for all the tests in FromSelfTest, include new tests that make use of aliased(), which should also ensure that we are testing "aliased of aliased" as was just introduced in 4ecd352a9.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Attempt to package "from_self()" within AliasedClass** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2120

**Comment by zzzeek** [comment]
currently am attempting to get aliased() to also do the adaption based on a flag and see if this can be a full replacement for from_self().

**Comment by zzzeek** [comment]
It's proving to have just as much complexity because the query still has to run around and find all these aliased() constructs.  the whole thing then impacts the ORMSelectCompileState._exported_columns_iterator  which is where all of this stuff needs to be known, which then adds more complexity all over again.  this is the basic reason why Query.statement has to fall back to a full compile, because this method would need to do a lot more in order to do the right thing for a statement.  i can get it to do "from self" things but then with_polymorphic comes in and then it gets way too complicated to be worth it.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Complete deprecation of from_self()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2244
