### ISSUE TITLE
How to handle encrypted columns using AES_DECRYPT/AES_ENCRYPT MySQL functions in database models

### ISSUE THREAD

**Issue by ambersariya** [sqlalchemy/sqlalchemy#5370]
Hi, I'm a relatively new to python & sqlalchemy and I wanted to find out how to handle `aes_decrypt()/aes_encrypt()` mysql functions. The DB engine uses AES-256-CBC type encryption.

I am able to get results using do the above mentioned mysql functions as part of raw SQL query yields correct results but being able to do this with Models would help me greatly.

```python
# raw query
query = text(
        """
        SELECT
        CONVERT(AES_DECRYPT(u.email, '<encryption_key>', u.iv) USING 'utf8') as 'email
        FROM users u
        """
)
```

So far I've found this from the [wiki](https://github.com/sqlalchemy/sqlalchemy/wiki/SymmetricEncryption
) but unable to see how this would replicate the above functionality which gives the desired results:

1) because of the stored initial vector value in column.
2) This might be happening on the language level after fetching of records which wouldn't allow for filtering using the where clause

For example looking at the below model, `User.email` property is encrypted and the initial vector used to encrypt this value is stored as a column `(User.iv)` as well. In this case how to handle automatic decoding/encoding of such data?

```python
class User(Base):
    __tablename__ = 'users'

    id = Column(INTEGER(10), primary_key=True)
    email = Column(LargeBinary, nullable=False)
    iv = Column(BINARY(48))
    # ... Fields omitted for simplicity ...
```

Appreciate the help in advance.

Thanks

**Useful links**
- [MySQL 5.6.x documentation aes_decrypt()](https://dev.mysql.com/doc/refman/5.6/en/encryption-functions.html#function_aes-decrypt)

**Comment by zzzeek** [comment]
the wiki example refers to application-side encryption.  for server-side functions you normally use the bind_expression() and column_expression() methods, which are documented here: https://docs.sqlalchemy.org/en/13/core/custom_types.html#applying-sql-level-bind-result-processing.  that would work out of the gate if you weren't also using a persisted init_vector which appears to be optional.   

for the init_vector part you probably need to use a combination of column_property() and some combination either of composites or assigned SQL expressions, I will work up an example later, no time right now.  links below:

SQL functions: https://docs.sqlalchemy.org/en/13/core/tutorial.html#coretutorial-functions

https://docs.sqlalchemy.org/en/13/orm/mapped_sql_expr.html#mapper-column-property-sql-expressions

https://docs.sqlalchemy.org/en/13/orm/composites.html

https://docs.sqlalchemy.org/en/13/orm/persistence_techniques.html#embedding-sql-insert-update-expressions-into-a-flush

**Comment by zzzeek** [comment]
So this is published at https://github.com/sqlalchemy/sqlalchemy/wiki/SymmetricEncryptionServerSide .    It's using os.urandom() to generate the init_vector, you can also use MySQL RANDOM_BYTES() but you would have to execute the function beforehand to get the bytes locally, doesn't seem worth it as os.urandom() is cryptographically secure as well.

here is that recipe as written at the moment:
```

import os

from sqlalchemy import cast
from sqlalchemy import CHAR
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import LargeBinary
from sqlalchemy.dialects.mysql import CHAR
from sqlalchemy.dialects.mysql import TINYBLOB
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import column_property
from sqlalchemy.orm import Session

Base = declarative_base()

my_key = "some key"


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    enc_data = Column(LargeBinary)
    init_vector = Column(TINYBLOB)

    data = column_property(
        cast(
            func.aes_decrypt(
                enc_data, func.unhex(func.sha2(my_key, 512)), init_vector
            ),
            CHAR(charset="utf8"),
        )
    )


@event.listens_for(A.data, "set")
def set_a_data(target, value, oldvalue, initiator):
    if target.init_vector is None:
        target.init_vector = os.urandom(16)

    target.enc_data = func.aes_encrypt(
        value, func.unhex(func.sha2(my_key, 512)), target.init_vector
    )


e = create_engine("mysql://scott:tiger@mysql57/test", echo="debug")
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

a1 = A()

a1.data = "my data"

s.add(a1)
s.commit()

print(s.query(A.data).filter(A.data == "my data").all())

```

you can see that SELECT..WHERE is decrypting each time:

```
SELECT CAST(aes_decrypt(a.enc_data, unhex(sha2(%s, %s)), a.init_vector) AS CHAR CHARACTER SET utf8) AS anon_1 
FROM a 
WHERE CAST(aes_decrypt(a.enc_data, unhex(sha2(%s, %s)), a.init_vector) AS CHAR CHARACTER SET utf8) = %s
2020-06-02 12:28:34,041 INFO sqlalchemy.engine.base.Engine ('some key', 512, 'some key', 512, 'my data')

```

**Comment by zzzeek** [comment]
If you don't need persisted init_vector, here's the TypeDecorator version, which is much simpler:

```python

import os

from sqlalchemy import cast
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import LargeBinary
from sqlalchemy.dialects.mysql import CHAR
from sqlalchemy.dialects.mysql import TINYBLOB
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import column_property
from sqlalchemy.orm import Session
from sqlalchemy.types import TypeDecorator
from sqlalchemy import type_coerce

Base = declarative_base()

my_key = "some key"


class EncType(TypeDecorator):
    impl = LargeBinary

    def bind_expression(self, bindvalue):
        return func.aes_encrypt(
            type_coerce(bindvalue, CHAR()), func.unhex(func.sha2(my_key, 512)),
        )

    def column_expression(self, col):
        return cast(
            func.aes_decrypt(col, func.unhex(func.sha2(my_key, 512)),),
            CHAR(charset="utf8"),
        )


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(EncType)


e = create_engine("mysql://scott:tiger@mariadb104/test", echo="debug")
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

a1 = A()

a1.data = "my data"

s.add(a1)
s.commit()

print(s.query(A.data).filter(A.data == "my data").all())
```

**Comment by ambersariya** [comment]
@zzzeek thank you for telling me about both ways. I really appreciate the prompt response. I'll give it a try shortly

**Comment by ambersariya** [comment]
Worked perfectly for me after minor tweaks. Thank you very much @zzzeek
