### ISSUE TITLE
SQLAlchemy does not respect the percendence of operations when `op` method is used

### ISSUE THREAD

**Issue by StefanosChaliasos** [sqlalchemy/sqlalchemy#5376]
**Describe the bug**
SQLAlchemy (on the latest master version) does not place correct parenthesis when using the `op` method.

**Expected behavior**
```python
f = ((Author.id + 2).op('/')(4)).label('f')
session.query(f)
```

I expect the following query:

```sql
SELECT (author.id + ?) / ? AS f
FROM author
```

Instead SQLAlchemy generate the following query:

```sql
SELECT author.id + ? / ? AS f
FROM author
```

**Versions.**
SQLAlchemy latest master version([commit](https://github.com/sqlalchemy/sqlalchemy/commit/3b2c6692bd5df6fe4a37192dfdaed408e3be5e54))

**Have a nice day!**

**Comment by theosotr** [comment]
Actually, the method `op()`, gets a keyword argument, namely, `precedence` which indicates the precedence of the custom operator.

According to the documentation

> A lower number will cause the expression to be parenthesized when applied against another operator with higher precedence. The default value of 0 is lower than all operators except for the comma (,) and AS operators. A value of 100 will be higher or equal to all operators, and -100 will be lower than or equal to all operators.

So, wouldn't be safer if the default value was 100?

**Comment by zzzeek** [comment]
the "precedence" feature of op() is well documented at https://docs.sqlalchemy.org/en/13/core/sqlelement.html#sqlalchemy.sql.operators.Operators.op so closing this.
