### ISSUE TITLE
proposal: I am not sure if we want sqlalchemy.future as a public import space

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5379]
As I've gone through and implemented the biggest parts of the 2.0 architecture in 1.4, it turns out there is almost nothing in sqlalchemy.future.     I would propose that some kind of "future.engine" package remain present as a place for basiclally the new engine API to go, but that "future" style operation only need be calling create_engine() with a "future=True" flag.   the rest of the API seems to be functional without any "future" need, and at most perhaps the ORM Session would enable/disable "future" mode with a similar future=True flag sent to sessionmaker().

The reason it would be nice to not have users import from "sqlalchemy.future" would be that we don't have to worry about copying the entire import space into these packages, and it would continue to give us room to adjust the import namespaces between now, 1.4 and 2.0 without an abrupt change.    addtionally, I think it's going to be really confusing to have two different select() functions that are 99% the same except for subtle behavioral differences.

The major change that has led to this is that the select() construct has a "plugin" model now whereby it can call into orm-specific functions once it has the so-called "orm plugin".   I originally wasn't sure if this model was going to actually end up being used but it's turned out to be the best way to have "select()" with a few ORM-specific behaviors.    the end result here is that the "select()" and "future_select()" are nearly the same, future_select() just adds some new methods, and the new constructor which we want to unify in #5284 .   the only method that changes is join() / outerjoin(), which is a method that has always done something useless (creates a subquery and joins to it) and at the moment in 1.4 the base form of join() just raises an error.   so this would be one "backwards incomptible" bump for a function that nobody should be using anyway.

the "Removed in 2.0" warnings are now turned on/off by a single environment-style variable in https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/util/__init__.py#L152 which we just need to hook into os.environ().

for the engine, the newer API is in sqlalchemy.future.engine, and it is essentially the rollback() and commit() and new execute() methods, which are one-liners, and the Engine which sets up as no-ops all the old methods.   then there's a bunch of nicer docstrings.  So it is nice to have a place for the new Connection / Engine in terms of documentation but there's nothing really to "import" except for create_engine(), which sohuld just be the existing create_engine() with future=True.

the ORM Session has a big behavioral change which is that session.execute() will do ORM things if you pass it select/update/delete objects with ORM elements in them.   this is probably fine for everyone, but in case it's not we can also do a future=True mode for Session / sessionmaker().

in ORM there is otherwise no new API in the plan.  The one element was how do to query(User).from_statement(statement), but thanks to the ORM plugin model I think I'm going to put it right on select(),  select(User).from_statement(statement).

**Comment by zzzeek** [comment]
there's also the new declarative base, but I was planning to make this API shift in 1.4 in any case that declarative_base() can from from sqlalchemy.orm.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add future=True to create_engine/Session; unify select()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2058
