### ISSUE TITLE
Query crashes with syntax error on SQLite

### ISSUE THREAD

**Issue by theosotr** [sqlalchemy/sqlalchemy#5395]
The list of reserved words in sqlite does not contain the word "exists" as needed. So the following toy query

```python
session.query(Model.column.label('exists')).first()
```
crashes with

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "exists": syntax error
```

as  the keyword is not wrapped by quotes. See here https://github.com/sqlalchemy/sqlalchemy/blob/e1d4e59116bbf1a12bb6b3f57d33ddfc757d4567/lib/sqlalchemy/sql/compiler.py#L4288.

The list of reserved words must be updated. That is

```
diff --git a/lib/sqlalchemy/dialects/sqlite/base.py b/lib/sqlalchemy/dialects/sqlite/base.py
index 15d125ce0..a203e786e 100644
--- a/lib/sqlalchemy/dialects/sqlite/base.py
+++ b/lib/sqlalchemy/dialects/sqlite/base.py
@@ -1334,6 +1334,7 @@ class SQLiteIdentifierPreparer(compiler.IdentifierPreparer):
             "escape",
             "except",
             "exclusive",
+            "exists",
             "explain",
             "false",
             "fail",
```
**Have a nice day!**

**Comment by CaselIT** [comment]
If you could open a pr it would be great

**Comment by sqla-tester** [comment]
**Thodoris Sotiropoulos** has proposed a fix for this issue in the **master** branch:

**Fixes: #5395 Add 'exists' to SQLite's reserved keywords** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2036

**Comment by sqla-tester** [comment]
**Thodoris Sotiropoulos** has proposed a fix for this issue in the **master** branch:

**Add 'exists' to SQLite's reserved keywords** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2036

**Comment by sqla-tester** [comment]
**Thodoris Sotiropoulos** has proposed a fix for this issue in the **rel_1_3** branch:

**Add 'exists' to SQLite's reserved keywords** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2037
