### ISSUE TITLE
mysql ssl parameters are not documented.  options supported?

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5397]
We can connect to pymysql with ssl params as follows:
```

from sqlalchemy import create_engine

e = create_engine(
    "mysql+pymysql://scott:tiger@localhost/test?"
    "ssl_ca=/path/to/ca&ssl_capath=/path/to/cas&ssl_cipher=tls1&ssl_key=/path_to_key"
)

print(e.dialect.create_connect_args(e.url))

```
this assembles the ssl arguments in a dictionary as required by mysqlclient / pymysql / others(?) :

`[[], {'host': 'localhost', 'db': 'test', 'user': 'scott', 'passwd': 'tiger', 'ssl': {'ca': '/path/to/ca', 'key': '/path_to_key', 'capath': '/path/to/cas', 'cipher': 'tls1'}, 'client_flag': 2}]
`

however there is no mention of "ssl" in the docs at https://docs.sqlalchemy.org/en/13/dialects/mysql.html.

additonally, it's not clear if an additional parameter "check_hostname" needs to be supported.

**Comment by sqla-tester** [comment]
**Jerry Zhao** has proposed a fix for this issue in the **master** branch:

**add ssl_check_hostname option in mysqldb** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2774
