### ISSUE TITLE
Relationship cascade_iterator() fails when lazy=raise

### ISSUE THREAD

**Issue by kolypto** [sqlalchemy/sqlalchemy#5398]
**Describe the bug**

I've been using `raiseload()` in unit-tests to find performance issues (N+1) and found out that
`raiseload()` actually prevents Session.delete() from using cascade_iterator().

1. use `raiseload('*')` (to discover performance issues)
2. use `Session.delete()` on an instance that has related objects

It was supposedly fixed in 1.3.12 in #4997 , but I'm still experiencing it :) 

Unit-test below.

**Expected behavior**
Delete succeeds.

**Error**
> sqlalchemy.exc.InvalidRequestError: 'User.articles' is not available due to lazy='raise'

**To Reproduce**

Load a user with relationships, set `raiseload('*')`, and `Session.delete()` it:

* user = ssn.query(..).options(raiseload('*')).first()
* ssn.delete(user)

Here's what can be seen in the stack trace:

* ssn.delete(user)
* Session.delete()
* Session._delete_impl(state, instance, head=True)
* state.manager.mapper.cascade_iterator("delete", state)
* prop.cascade_iterator(...)
* tuples = self._value_as_iterable(state, dict_, self.key, passive=passive)
* x = impl.get(state, dict_, passive=passive)
* value = callable_(state, passive)
* return strategy._load_for_state(state, passive)

and there it goes: sets off the `raiseload()` thing:

> sqlalchemy.exc.InvalidRequestError: 'User.articles' is not available due to lazy='raise'

# Unit-test

```py
import unittest

from sqlalchemy import Column, Integer, create_engine, event, ForeignKey
from sqlalchemy.engine import Engine
from sqlalchemy.orm import Query, Session, sessionmaker, relationship, raiseload
from sqlalchemy.ext.declarative import declarative_base

# Define some models
Base = declarative_base()

class User(Base):
    __tablename__ = 'u'
    id = Column(Integer, primary_key=True)

    # This is the relationship that's going to fail when 
    # both Session.delete() and raiseload() are used
    articles = relationship(
        lambda: Article,
        collection_class=set,
        back_populates='author',
        # cascade='all, delete-orphan',  # not necessary; fails anyway
    )

class Article(Base):
    __tablename__ = 'a'
    id = Column(Integer, primary_key=True)
    author_id = Column(Integer, ForeignKey(User.id))
    author = relationship(User, back_populates='articles')


class ExceptionsInSignalHandler(unittest.TestCase):

    def test_raiseload_delete(self):
        """ Test how Session.delete() handles raiseload() """
        ssn = self.sessionmaker()

        # fixture: create a user and an article
        ssn.add(
            User(
                articles={
                    Article()
                }
            )
        )
        ssn.commit()

        # Load a user with raiseload()
        user: User = ssn.query(User).options(
            # Provide as a loader option
            raiseload('*')
        ).first()

        # Delete this user
        ssn.delete(user)  # expected to succeed
        ssn.flush()


    # Boring boilerplate stuff

    def setUp(self):
        # Init a working DB engine, sessionmaker
        self.engine: Engine = create_engine('sqlite:///test.sqlite')
        self.sessionmaker = sessionmaker()
        self.sessionmaker.configure(bind=self.engine)

        # Recreate the database
        Base.metadata.drop_all(self.engine)
        Base.metadata.create_all(self.engine)

    def tearDown(self):
        self.sessionmaker.close_all()
        self.engine.dispose()


unittest.main()

```

**Versions.**
 - OS: Linux
 - Python: 3.7
 - SQLAlchemy: 1.3.17
 - Database: N/A, but Postgres and SQLite

**Comment by zzzeek** [comment]
heya -

thanks for the clear test.

this error can be avoided if you tell the unit of work to not alter the "article" rows as follows:

```
class User(Base):
    __tablename__ = 'u'
    id = Column(Integer, primary_key=True)

    # This is the relationship that's going to fail when
    # both Session.delete() and raiseload() are used
    articles = relationship(
        lambda: Article,
        collection_class=set,
        back_populates='author',
        passive_deletes='never'
        # cascade='all, delete-orphan',  # not necessary; fails anyway
    )

```

the test then passes, but that's because SQLite does not enforce foreign keys by default.    So assuming we do pragma foreign keys:

```
        from sqlalchemy import event

        @event.listens_for(Engine, "connect")
        def set_sqlite_pragma(dbapi_connection, connection_record):
            cursor = dbapi_connection.cursor()
            cursor.execute("PRAGMA foreign_keys=ON")
            cursor.close()

```

now the test fails with:

```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: DELETE FROM u WHERE u.id = ?]
[parameters: (1,)]

```

so finally, use ON DELETE cascade so that these are taken care of in the way you see fit:

```
class Article(Base):
    __tablename__ = 'a'
    id = Column(Integer, primary_key=True)
    author_id = Column(Integer, ForeignKey(User.id, ondelete="SET NULL"))
    author = relationship(User, back_populates='articles')

```

then you let the database amend the Author rows and the ORM does not have to load these in to see what they are.

**Comment by zzzeek** [comment]
as far as the debate over if SQLAlchemy should assume foreign keys are set up to cascade and should assume "passive='never'" as the default, I'm -1 on that as there was a long thread on this at #5349.

**Comment by kolypto** [comment]
@zzzeek thanks for the recipe :) 
I've actually found another workaround. `ssn.refresh(user)` removes all raiseloads.... :D

**Comment by zzzeek** [comment]
does it?  OK I can never keep track of what makes options go away and what doesn't.  things are a little ad-hoc in that area still.
