### ISSUE TITLE
use psycopg2 "values" mode by default; separate out from "batch"

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5401]
psycopg2's executemany is very slow so we should test having "values" mode by default throughout CI, i.e. https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#psycopg2-executemany-mode .   this will also integrate with #5263 so that the ORM with psycopg2 will by *insanely* fast for inserts compared to how it is now.

**Comment by zzzeek** [comment]
So the "batch" mode that's implied by "values" at the moment is only for UPDATE statements and per psycopg2 documentation it removes "cursor.rowcount".  I think "values" for UPDATE is less compelling as a default so I will break out "values" and "batch" into two separate binary bits, and the default will be a new token "values_only".   "values" will become "values_plus_batch".

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Default psycopg2 executemany mode to "values_only"** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2051
