### ISSUE TITLE
how to set autoincrement to 1000

### ISSUE THREAD

**Issue by shivgana** [sqlalchemy/sqlalchemy#5402]

**Comment by zzzeek** [comment]
please share the type of database in use, thanks

**Comment by shivgana** [comment]
In sqlite3, table has created. I want to set auto increment value to 1000

**Comment by zzzeek** [comment]
Here are SQLite's documentation on this:  https://www.sqlite.org/autoinc.html

"The usual algorithm is to give the newly created row a ROWID that is one larger than the largest ROWID in the table prior to the insert. If the table is initially empty, then a ROWID of 1 is used. "

so you would have to INSERT a row with a primary key of "1000" first.  then the subsequent rows will have numbers higher than 1000 generated.
