### ISSUE TITLE
switch to setuptools setup.cfg format

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5404]
given that we want to upgrade our setuptools concept and *maybe* have a conditional requirement as stated in #5400 we should see if we can upgrade to setup.cfg format as docuemnted at https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files.

This new format will allow the code in setup.py that parses `__version__` and the README.rst file to be set up declaratively.  

We still would be looking to maintain our C-extension fallback building approach and w would still have the extra run_setup() indirection going on in setup.py.   

I haven't tried it yet but I am *assuming* we can send programmatic options to setuptools.setup(), which currently include cmdclass, distclass.  find_packages it looks like they have a declarative version of that for setup.cfg.

I also want to attempt to understand what's going on with our custom Distribution class and see if we still need to be doing this in that way.

**Comment by CaselIT** [comment]
We should also look into how `setup.cfg` interacts with `pyproject.toml` and pep 517.
I guess they should play nice together, since `setup.cfg` seems a setuptools thing, but it's worth making sure.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Move most setup options to setup.cfg** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2042
