### ISSUE TITLE
Strange behaviour when performing join with aliased table

### ISSUE THREAD

**Issue by StefanosChaliasos** [sqlalchemy/sqlalchemy#5406]
**Describe the bug**

Hi

I have three models

```python
class Author(Base):
    __tablename__ = 'author'

    id = Column(Integer, primary_key=True)


class Book(Base):
    __tablename__ = 'book'

    id = Column(Integer, primary_key=True)
    author_id = Column(ForeignKey('author.id', ondelete='CASCADE'))

    author = relationship('Author')


class Review(Base):
    __tablename__ = 'review'

    id = Column(Integer, primary_key=True)
    book_id = Column(ForeignKey('book.id', ondelete='CASCADE'))

    book = relationship('book')

```

and I write the following query (simplified for opening the issue)
where I perform three joins with aliased tables.

```python
bookAl = aliased(Book)
session.query(Author.id).select_from(Review).join(
  bookAl.author).join(bookAl, Review.book)
```

when I execute this query, I get a strange error

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) ambiguous column name: book_1.id
[SQL: SELECT author.id AS author_id
FROM review JOIN book AS book_1 ON book_1.id = review.book_id, book AS book_1 JOIN author ON author.id = book_1.author_id]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

the generated query is

```sql
SELECT author.id AS author_id
FROM review JOIN book AS book_1 ON book_1.id = review.book_id, book AS book_1 JOIN author ON author.id = book_1.author_id
```

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

the error refers to the fact that the "book_1" alias is being rendered twice in the FROM clause.    you want to re-order how the query is written such that it is clearer how you would like the SQL joins to be rendered.  when you say query(Auhor).select_from(Review), the join() method now considers "Review" to be the "left side" of the join, and if the clause you give it does not line up, it just adds a new FROM entry.   Hence your join() which originates from aliased(Book) have no "left side" to anchor onto and it comes out independently.  

let's think in terms of SQL.   three tables and it looks like you want a FROM clause that is "FROM review JOIN book AS book_1 ON (onclause) JOIN author ON (onclause)".   The order is "review", "book_1", "author".     specifically the query we imagine is:

```
SELECT author.id AS author_id 
FROM review 
JOIN book AS book_1 ON book_1.id = review.book_id 
JOIN author ON author.id = book_1.author_id

```

we use Query in the same way as we read the SQL we want:

```
q = s.query(Author.id)   # SELECT author.id AS author_id 
q = q.select_from(Review)  # FROM review 
q = q.join(bookAl, Review.book)  # JOIN book AS book_1 ON book_1.id = review.book_id 
q = q.join(bookAl.author)  # JOIN author ON author.id = book_1.author_id

```

your model and test case are clear so I in fact used the above query to generate the SQL.

**Comment by StefanosChaliasos** [comment]
Thanks for your reply, but I think this seems a bug to me, because when having inner joins like in our example, the order of joins does not matter at all
so, 

```sql
SELECT author.id AS author_id 
FROM review 
JOIN book AS book_1 ON book_1.id = review.book_id 
JOIN author ON author.id = book_1.author_id
```

is equivalent with 

```sql
SELECT author.id AS author_id 
FROM review 
JOIN author ON author.id = book_1.author_id
JOIN book AS book_1 ON book_1.id = review.book_id
```

I tested on sqlite and I got the same results. Correct me if I am wrong but the same applies for MySQL and Postgres as well.

Also, I think calling joins in specific order is not specified in SQLalchemy's documentation.

**Comment by zzzeek** [comment]
> Thanks for your reply, but I think this seems a bug to me, because when having inner joins like in our example, the order of joins does not matter at all
> so,
> 
> ```sql
> SELECT author.id AS author_id 
> FROM review 
> JOIN book AS book_1 ON book_1.id = review.book_id 
> JOIN author ON author.id = book_1.author_id
> ```
> 
> is equivalent with
> 
> ```sql
> SELECT author.id AS author_id 
> FROM review 
> JOIN author ON author.id = book_1.author_id
> JOIN book AS book_1 ON book_1.id = review.book_id
> ```
> 
> I tested on sqlite and I got the same results. Correct me if I am wrong but the same applies for MySQL and Postgres as well.

The second SQL statement is invalid SQL and will not work on PostgreSQL or MySQL.  SQLite's SQL engine is not very formalized.     You could probably generate that statement by placing two join() objects in that order but you wouldn't want to because it's invalid SQL.


> 
> Also, I think calling joins in specific order is not specified in SQLalchemy's documentation.

Feel free to provide a PR, I don't quite see how this can be made clearer from the docs at https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.join.

**Comment by zzzeek** [comment]
Nevermind, I will apply a note right now.

**Comment by StefanosChaliasos** [comment]
Thanks; yes you're right the latter query does not work on MySQL, Postgres. But if I wrote the query without alias, the order indeed does not matter.

Anyway, I surprised by the error, because I got an irrelevant error message and the resulting SQL query  was completely unexpected.

**Comment by zzzeek** [comment]
> Thanks; yes you're right the latter query does not work on MySQL, Postgres. But if I wrote the query without alias, the order indeed does not matter.
> 
> Anyway, I surprised by the error, because I got an irrelevant error message and the resulting SQL query was completely unexpected.

from SQLAlchemy's perspective it was expressing your stated intent as directly as possible.   note is coming.
