### ISSUE TITLE
Delete error when using master and slave(read only)

### ISSUE THREAD

**Issue by lz1998** [sqlalchemy/sqlalchemy#5407]
**Describe the bug**

When I use master(write) and slave(read only), I cant delete data.

**Expected behavior**

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example. 
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22)

```py
session = RoutingSession()
class RoutingSession(Session):
    def get_bind(self, mapper=None, clause=None):
        if self._flushing:
            print("write")
            return write_engine
        else:
            print("read")
            return read_engine

session.query(...).delete()
session.commit()
```

**Error**

```
# Copy error here. Please include the full stack trace.
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, 'proxy is read only')
```

**Versions.**
 - OS: macos
 - Python: 3.7
 - SQLAlchemy: 1.3.17
 - Database: mysql

**Additional context**

Why `session.query(...).delete()` is read?
**Have a nice day!**

**Comment by CaselIT** [comment]
Is the problem that the read engine is returned?

**Comment by zzzeek** [comment]
hi there -

the query.delete() operation is not within the flush process, so the routing session would need additional logic to determine that the query being invoked is in fact a delete operation.  

you can identify issues like these by using [pdb](https://docs.python.org/3/library/pdb.html):

```
class RoutingSession(Session):
    def get_bind(self, mapper=None, clause=None):
    	import pdb
    	pdb.set_trace()
        if self._flushing:
            print("write")
            return write_engine
        else:
            print("read")
            return read_engine

```

running it we see:

```
> /home/classic/dev/sqlalchemy/test3.py(21)get_bind()
-> if self._flushing:
(Pdb) self._flushing
False
(Pdb) clause
<sqlalchemy.sql.dml.Delete object at 0x7f490e5e3160>
(Pdb) 

```

easy enough we can check for that kind of clause to fix:

```
from sqlalchemy.sql import Update, Delete

class RoutingSession(Session):
    def get_bind(self, mapper=None, clause=None):
        if self._flushing or isinstance(clause, (Update, Delete)):
            print("write")
            return write_engine
        else:
            print("read")
            return read_engine

```

**Comment by CaselIT** [comment]
Sorry for the hijack this a bit Mike.
Does `if self._flushing or isinstance(clause, (Update, Delete)):` covers all cases where a session is modifying data?

**Comment by zzzeek** [comment]
oh no worries I hijacked you! :)    the approach above covers the cases that originate from Query and from Session() itself.   it won't cover if someone passed an insert() construct directly into session.execute(), though.    that example is sort of a recipe so it is not intended to be foolproof.

**Comment by zzzeek** [comment]
we have to make the choice between:  a. there's a fully supported feature for "reader" and "writer" engine and a whole heuristic system to make it work in every possible case,  b. there is no such system and no guidance given at all how to build one  and c. guidance on how you can build one of these noting this is a DIY project.

**Comment by zzzeek** [comment]
maybe we can have a new dragon with a little toolbox that says "DIY" and have a special box for that.

**Comment by CaselIT** [comment]
Regarding a. I don't think its possible in all cases without a lot of effort, especially for textual sql like `session.execute('insert ...')`

> maybe we can have a new dragon with a little toolbox that says "DIY" and have a special box for that.

Yes, probably we could add a dragon here https://docs.sqlalchemy.org/en/13/orm/persistence_techniques.html?highlight=self%20_flushing#custom-vertical-partitioning mentioning this, but we could probably update the example to include these two cases.

**Comment by zzzeek** [comment]
absolutely, SQLAlchemy is all about not having to build "case a" for everything.  it has a strong DIY spirit that we probably have to be more explicit about these days.

**Comment by zzzeek** [comment]
well i was thinking of getting our dragon artist to make a new dragon actually.   not everything should be "danger!" it just should manage expectations.

**Comment by CaselIT** [comment]
maybe for in this one we could have the human poke the sleeping dragon

**Comment by lz1998** [comment]
> Is the problem that the read engine is returned?

Yes, so it failed.

**Comment by zzzeek** [comment]
added to the docs
