### ISSUE TITLE
How to set Oracle database param while aleady set the sid in dsn?

### ISSUE THREAD

**Issue by liuzhenji** [sqlalchemy/sqlalchemy#5412]
**Describe your question**

oracle://user:password@host:port/sid
but sid is not the database, so

when i try to query something by the model class ,
there will always be exception : table or view does not exist

**Example (if applicable)**

engine = create_engine('oracle://oracle:123@192.168.0.6:1521/sidname', encoding='utf-8', echo=True)

class ListMain(Base):
    __tablename__ = 'tablename'

    testMainId = Column('main_id', String(50), primary_key=True)

session = DBSession()
testMain = session.query(ListMain).filter(ListMain.testMainId=='116040055948_2002_20161014_C723-G8').one()

**Have a nice day!**

**Comment by gordthompson** [comment]
When connecting to my Oracle XE instance I need to use

oracle+cx_oracle://scott:tiger@192.168.0.199:1521/?service_name=xepdb1&encoding=UTF-8&nencoding=UTF-8

Perhaps you need to do something similar with `service_name`?

**Comment by liuzhenji** [comment]
yeah,maybe. Cause i used to use mysql  which is much more elegant. I 'm newer to Oracle , I'll consult DBA about service_name and try it .

**Comment by zzzeek** [comment]
Here's cx_oracle connect:

https://cx-oracle.readthedocs.io/en/latest/api_manual/module.html#cx_Oracle.connect

can you show me what arguments you'd like to be passed ?

**Comment by zzzeek** [comment]
better docs:

https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#connection-strings

**Comment by liuzhenji** [comment]
I created session through sqlalchemy api, here it is:

engine = create_engine('oracle://oracle:123@192.168.0.6:1521/sidname', encoding='utf-8', echo=True)

**Comment by liuzhenji** [comment]
I will try this:

**Comment by zzzeek** [comment]
I don't either, which is why I think you need to ask the cx_Oracle people and figure out waht you want in terms of cx_Oracle.connect() first.

**Comment by liuzhenji** [comment]
> I don't either, which is why I think you need to ask the cx_Oracle people and figure out waht you want in terms of cx_Oracle.connect() first.

yes, i was thinking about that. But , there may will be a param to pass to the dbapi driver(cx_Oracle in this case) , which may the key to this problem. So i ask here first....

**Comment by liuzhenji** [comment]
I solved this problem by change to another oracle account which default pattern(Oracle pattern) is target pattern.....

**Comment by zzzeek** [comment]
right I am not familiar enough with cx_Oracle to know what parameters to pass for this case, but glad you solved your issue.

**Comment by liuzhenji** [comment]
> right I am not familiar enough with cx_Oracle to know what parameters to pass for this case, but glad you solved your issue.

Thanks for your concern~~
