### ISSUE TITLE
Rename Table.tometadata to to_metadata

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5413]
As discussed in the dev meeting we should deprecate `Table.tometadata` and replace it with `Table.to_metadata`

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Rename Table.tometadata to to_metadata** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2060

**Comment by gordthompson** [comment]
@zzzeek - If this passes muster shall we do something similar for `isnot` and `notin_`?

**Comment by zzzeek** [comment]
I think we can try that here sure I left comments on the gerrit
