### ISSUE TITLE
Can test_computed_col_default_not_set stop relying on autoincrement being set?

### ISSUE THREAD

**Issue by rafiss** [sqlalchemy/sqlalchemy#5414]
**Describe your question**

The test `test_computed_col_default_not_set` in `ComputedReflectionTest` performs the following check:

```
        cols = insp.get_columns("computed_column_table")
        for col in cols:
            if col["name"] == "with_default":
                is_true("42" in col["default"])
            elif not col["autoincrement"]:
                is_(col["default"], None)
```

This only works if the dialect being tested properly supports autoincrement.

The documentation of `ComponentReflectionTest::test_autoincrement_col` says the following:

```
        A backend is better off not returning "autoincrement" at all,
        instead of potentially returning "False" for an auto-incrementing
        primary key column.
```

I am wondering if would be ok to change the `elif not col["autoincrement"]` check to something like `elif col["name"] != "id"` instead.

**Additional context**

I am asking this question because I'm working on the [sqlalchemy-cockroachdb](https://github.com/cockroachdb/sqlalchemy-cockroachdb) dialect. CockroachDB does not support `autoincrement` by default because when using the `SERIAL` type, the default value is created using `unique_rowid()`, which generates a random integer (instead of using a sequence with `nextval()`).

I'm happy to make the code change in the test if this idea seems acceptable.

**Comment by zzzeek** [comment]
I think that test is pointing to the wrong table.  @CaselIT it's looking for the column named "with_default" so it should at least be looking at "computed_default_table" which has that column.

as for the "default" part, I think this test wants to check that only the column with "server_default" has a "default", but then, if the backend also has "autoincrement" that might also set "default".  So it would also work if we change it to "elif not col.get("autoincrement", False):".     Does cockroachdb put a "default" in the reflected column info but not set "autoincrement" ?      if this SERIAL column generates a new value without the user doing anything, that would qualify as "autoincrement", Postgresql doesn't have true "autoincrement" either but it sets this flag for a SERIAL column.

**Comment by CaselIT** [comment]
Hi,
There seem to a conflicting documentation between 
https://docs.sqlalchemy.org/en/13/core/reflection.html?highlight=get_columns#sqlalchemy.engine.reflection.Inspector.get_columns
and the documentation on [`ComponentReflectionTest::test_autoincrement_col`](https://github.com/sqlalchemy/sqlalchemy/blob/56e817bb0ef4eaca189b42b930a6e99ee4ed0671/lib/sqlalchemy/testing/suite/test_reflection.py#L1111-L1113)
I was working under the assumption that autoincrement was always returned. We should probably fix it (not sure with one is wrong)

As @zzzeek suggested `col.get("autoincrement", False)` would work. Also the inspected table should be `computed_default_table` instead of `computed_column_table` since we are testing that computed is returned not as a default value, but that a default value is still returned if present in other columns.

**Comment by zzzeek** [comment]
which means the "autoincrement" check we are doing there is probably not a good idea and we should do what the poster says and look for "id" which we know might have a default :)

**Comment by CaselIT** [comment]
We could also just test explicitly that the computed column does not have a default, since that is the actual test we are doing

**Comment by zzzeek** [comment]
im all for fixing it :)

@rafiss, you probably should include "autoincrement": "auto" in the columns dictionary at the least.   for a SERIAL col that will generate new values automatically, have it returned as true.

**Comment by rafiss** [comment]
> Does cockroachdb put a "default" in the reflected column info but not set "autoincrement" ?

Yes, the reflected column would have a default of `unique_rowid()`.

> If this SERIAL column generates a new value without the user doing anything, that would qualify as "autoincrement", Postgresql doesn't have true "autoincrement" either but it sets this flag for a SERIAL column

I didn't realize -- in that case, I will make the CockroachDB dialect set `autoincrement`.

Perhaps related: I see that tests marked as requiring `autoincrement_insert` do in fact expect the database to increment values 1-by-1. E.g. `test_autoincrement_on_insert`, `test_native_lastrowid_autoinc`, and `test_autoincrement_on_insert_implicit_returning` all assert that the ID goes up by 1.

> you probably should include "autoincrement": "auto" in the columns dictionary at the least. for a SERIAL col that will generate new values automatically, have it returned as true.

Sounds good to me.


I can also go ahead and modify the test as discussed above. So if I understand correctly, these would be the changes:
* make the test look at `computed_default_table`.
* don't use a for loop and look at autoincrement; instead just check each column by name.

Is that correct?

**Comment by zzzeek** [comment]
sounds good thanks for that!

**Comment by sqla-tester** [comment]
**Rafi Shamim** has proposed a fix for this issue in the **master** branch:

**Improvements to test_computed_col_default_not_set** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2057
