### ISSUE TITLE
SAWarning: index key 'sqlnotapplicable' was not located in columns for table

### ISSUE THREAD

**Issue by pon-sander** [sqlalchemy/sqlalchemy#5415]
**Describe the bug**
I keep getting the warning below. and can't find a sollution to this warning.
/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/reflection.py:740: SAWarning: index key 'sqlnotapplicable' was not located in columns for table '##########'
  flavor, c, table_name

**Expected behavior**
Cant find any doccumentation on this warning

**To Reproduce**

```py
df.to_sql(name='table', schema='schema', con=engine,
              if_exists=replace, dtype=dashdb_typemap, index=False)
```

**Error**

```
I keep getting the warning below. and can't find a sollution to this warning.
/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/reflection.py:740: SAWarning: index key 'sqlnotapplicable' was not located in columns for table '##########'
  flavor, c, table_name
```

**Versions.**
 - OS: Linux 
 - Python: 3.5
 - SQLAlchemy: 1.0.13
 - Database: DB2 11.5
 - DBAPI: Jaydbapi - ibm_db_sa

**Comment by zzzeek** [comment]
this warning refers to an unexpected scenario when an table index is reflected , where the table has reported a column of a particular name that is present in an index but there is no column in the table that matches this name.

this is not a situation that is expected to occur, and is likely a bug in the ibm_db_sa driver so I would report it to them.

**Comment by zzzeek** [comment]
there's also a new DB2 driver in the works here: https://github.com/IBM/sqlalchemy-ibmi not sure if this helps

**Comment by pon-sander** [comment]
oke there is no index on the table, I will raise a issue with the ibm_db_sa team.

**Comment by shawnzhu** [comment]
@pon-sander I got the same problem when using Db2 in cloud v11.5. and found these two PRs to ibm_db_sa:

* https://github.com/ibmdb/python-ibmdbsa/pull/60
* https://github.com/ibmdb/python-ibmdbsa/pull/62
