### ISSUE TITLE
Improve has_table function in mysql dialect

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5418]
https://github.com/sqlalchemy/sqlalchemy/blob/660a340bff8fcefd2826032e75210c0924a2335e/lib/sqlalchemy/dialects/mysql/base.py#L2484-L2489

This is in fact not an issue on Windows:

``` python
connection_uri = "mysql+pymysql://root:toot@localhost:3307/mydb?charset=utf8mb4"
engine = sa.create_engine(connection_uri)

# ...

print(platform.system())  # Windows
table_name = "γιορτή"
with engine.connect() as conn:
    sql = sa.text("SHOW TABLES LIKE :table_name")
    params = {"table_name": table_name}
    result = conn.execute(sql, params).fetchall()
    print(result)  # [('γιορτή',)]

**Comment by gordthompson** [comment]
Confirmed that the above code also works with a table named `测试`.

Further research indicates that this part of the code has not been updated [since 2007](https://github.com/sqlalchemy/sqlalchemy/commit/23d01887491c646e321f6bb1e8427b3dd82581c1). I imagine that multi-byte character support, especially for metadata, could have been a *real* mess back then.

One thing that's not 100% clear: Was the platform dependency strictly related to the *client* platform, or did the *server* platform also(?) come into play?

**Comment by zzzeek** [comment]
that's the most ancient code that I have no recollection of.   it does not seem to have any opinion on linux either, which is likely because....i used a mac back then ! :)    

it's possible we could just change that whole thing for "show tables like" and just be done with it if we can get someone to test on a mac.

**Comment by zzzeek** [comment]
I don't actually know about the client/server but I have a feeling that's a server issue because mysql links table names to filenames.

**Comment by jvanasco** [comment]
i have mac! it's on my todo.

**Comment by zzzeek** [comment]
current status is the above comment is in question has been removed, as of #9058 we have learned our lesson and are using DESCRIBE only, after we missed the hint in #6151 mentioned above.     the DESCRIBE logic outside of the 1.4 series was in place for 15 years so I'm pretty confident there are no macOSx issues that are affecting anyone.
