### ISSUE TITLE
need to use _execute_20(... opts) in persistence.py 

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5420]
in persistence.py we execute SQL using "cached_connections" which comes from this:

```
def _cached_connection_dict(base_mapper):
    # dictionary of connection->connection_with_cache_options.
    return util.PopulateDict(
        lambda conn: conn.execution_options(
            compiled_cache=base_mapper._compiled_cache
        )
    )

```

that won't work with a 2.0 engine because execution_options modifies the base connection in place.   the cached_connection_dict needs to go and we needto instead use _execute_20() and pass the options with the correct cache at that point.  will be easier to read also.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**use execute_20 to preserve compiled cache** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2279
