### ISSUE TITLE
use oracle GENERATED to detect PK indexes

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5421]
the oracle dialect considers any index that has all the primary key columns to be the generated primary key index.   this causes real indexes to be skipped. There's a GENERATED column that we should also include here: https://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_1069.htm#i1578369   .   we should look at both the existing "primary key" columns as well as that "GENERATED" is present so that user-created indexes against the primary key columns are returned.

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Date
from sqlalchemy import DateTime
from sqlalchemy import Index
from sqlalchemy import inspect
from sqlalchemy import Numeric
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base

BASE = declarative_base()
target_metadata = BASE.metadata


class EditEOB(BASE):
    """This is the Edit EOB cross reference table."""

    __tablename__ = "edit_eob"
    __table_args__ = (
        Index(
            "eob_edit_idx",
            "eob_rid",
            "edit_rid",
            "relationship_type",
            "effective_date",
            unique=True,
        ),
    )
    edit_rid = Column(Numeric(15, 0), primary_key=True)
    eob_rid = Column(Numeric(15, 0), primary_key=True)
    effective_date = Column(Date, primary_key=True)
    relationship_type = Column(String(3), primary_key=True)

e = create_engine("oracle://scott:tiger@oracle1120", echo="debug")

BASE.metadata.create_all(e)

insp = inspect(e)
print(insp.get_indexes("edit_eob"))

```

**Comment by zzzeek** [comment]
ref https://github.com/sqlalchemy/alembic/issues/706

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Check GENERATED column when omitting Oracle PK indexes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2054

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Check GENERATED column when omitting Oracle PK indexes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2055
