### ISSUE TITLE
Check if a value in table exists sqlalchemy + mssql in Python

### ISSUE THREAD

**Issue by edo101** [sqlalchemy/sqlalchemy#5424]
I want to look for a csv file in a table in mssql server. If the csv file name exists in the table I want it to return true or false so that I can use that information for if then statement. I tried doing the following but I get errors. I am using Pyhton 3.7 with sql achemy and pandas.

```
import sqlalchemy as db
from sqlalchemy import Table, Column, Integer, String, MetaData, ForeignKey, update, exists

def dbhandler():
    params = urllib.parse.quote_plus(db_string)
    engine = db.create_engine("mssql+pyodbc:///?odbc_connect={}".format(params))

    connection = engine.connect()
    metadata = db.MetaData()
    odfs_tester_history_files = db.Table('odfs_tester_history_files', metadata, autoload=True, autoload_with=engine)
    odfs_tester_history = db.Table('odfs_tester_history', metadata, autoload=True, autoload_with=engine)
    tables_dict = {'odfs_tester_history_files': {'engine': engine, 'connection': connection, 'table': odfs_tester_history_files}, 'odfs_tester_history': {'engine': engine, 'connection': connection, 'table': odfs_tester_history}}
    #return {'engine': engine, 'connection': connection, 'table': odfs_tester_history_files}
    return tables_dict

db_instance = dbhandler()
odfs_tabletest_dict = db_instance['odfs_tester_history_files']

sql = exists(db.select([odfs_tabletest_dict['table']]).where(odfs_tabletest_dict['table'].c.CSV_FILENAME == '06_16_2020_FMGN519.csv'))
df = pd.read_sql(sql, odfs_tabletest_dict['connection'])
```

This gives me the error: 
**Error: raise exc.ObjectNotExecutableError(self) sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: <sqlalchemy.sql.selectable.Exists object at 0x000000096F8782C8>**

**Comment by zzzeek** [comment]
hi, please don't keep opening new issues for one problem, let's continue with your questions about exists() over at #5423.

**Comment by edo101** [comment]
@zzzeek  I made this cause it is a different issue and it wasn't addressed in that issue you linked by anyone with answers

**Comment by CaselIT** [comment]
You will have to place it inside another select (with `[ ]`).

**Comment by zzzeek** [comment]
@edo101 these are issues that would be better addressed on the mailing list or in the IRC channel where you would have a wider audience available to help you.   We do answer questions on github as it is unavoidable but more long form help conversations are at least better kept in one issue.
