### ISSUE TITLE
SQLAlchemy ignores server_onupdate clause on update

### ISSUE THREAD

**Issue by Sebi2020** [sqlalchemy/sqlalchemy#5427]
**Describe the bug**
Different than described in the official documentation SQLAlchemy ORM does not take care of the **server_onupdate** statement and produces an error if you try to commit a Model-Object to the database

**Expected behavior**
I expected SQLAlchemy to append  something like `DEFAULT ... ON UPDATE` to the updatedAt column DDL.

**To Reproduce**
1. Create a model with a updatedAt DateTime Column and the server_onupdate keyword set to  `func.now()` and a second Column with an arbitary type.
2. Try to insert one row ( this will fail if you haven't specified a value for the updatedAt column or haven't set the server_default keyword).

If you have set a value on insertion or a server_default:
3. Try to update the second column and commit your changes to the db (without updating the updatedAt column). The `server_onupdate` clause has no effect. The old value is still present.

**Versions.**
 - OS: Linux
 - Python: 3.6, 3.8
 - SQLAlchemy: 1.3.16
 - Database: MySQL
 - DBAPI: Mysqldb

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

"ON UPDATE CURRENT_TIMESTAMP" is a MySQL-specific phrase that most MySQL versions, that is, those prior to 8.0, uses automatically when you make use of the "TIMESTAMP" data type.  there is no "ON UPDATE" clause in SQL, and MySQL's is in fact hardcoded to "CURRENT_TIMESTAMP" only.  

example:
```

MariaDB [test]> create table mytable (somecol timestamp);
Query OK, 0 rows affected (0.067 sec)

MariaDB [test]> show create table mytable;
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                                                                              |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| mytable | CREATE TABLE `mytable` (
  `somecol` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.003 sec)

```


mysql 8 now defaults the "explicit_defaults_for_timestamp" flag to True, but per #4652 we don't have explciit support for this yet.      for now, use this workaround:

    column('x', TIMESTAMP,  server_default=DefaultClause(text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)))

will add to the docs now

**Comment by zzzeek** [comment]
the updated documentation will be up on the site within an hour.  thanks for reporting!

**Comment by Sebi2020** [comment]
@zzzeek I don't use the `TIMESTAMP` datatype. I use DateTime.

**Comment by zzzeek** [comment]
> @zzzeek I don't use the `TIMESTAMP` datatype. I use DateTime.

same instructions apply.
