### ISSUE TITLE
proposal: Standardize `isnot` & `notin_` operator names for SqlAlchemy2.0 (1.4?)

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#5429]
A handful of sql operators, as implemented in Python, are not consistent in SQLAlchemy.

The majority of items use a schema of `snake_case_with_trailing_underscore_` **when the sql command mimics Python reserved keywords**

For example, some of the commands adopting this scheme use:

| Python  | Sql | SQLAlchemy |
| ----- | ----- | ----- |
| and  | AND  | and_ |
| or  | OR  | or_ |
| is  | IS  |  is_ |
| in  | IS  |  in_ |

but compound operators either do not follow the same scheme, do not have an internal underscore, or both

| Python  | Sql | SQLAlchemy |
| ----- | ----- | ----- |
| is not  | IS NOT  | isnot |
| not in  | NOT IN  | notin_ |

This ticket will list them, and serve as reference to a PR if we proceed with any re-namings.

| SQLAchemy 1.3 | Proposed A | Proposed B (*rejected*) |
| ----- | ----- | ----- |
| isnot | is_not | is_not_ |
| notin_ | not_in | not_in_ |

If a change were to happen:
* the core function will be renamed
* the old function will be an alias for backwards compatibility; it will not be deprecated or warnings
* docs will be updated to use the new terms
* API docs for the old terms will state they are kept for backwards compatibility, and promote usage of the new terms

**Comment by CaselIT** [comment]
I'm nor particularly fond of `is_not_` and `not_in_` vs `is_not` and `not_in`, but I understand the consistency of having the tailing undersoce

**Comment by zzzeek** [comment]
just FTR I was looking to go from Python's example:

```
>>> import operator
>>> operator.is_
<built-in function is_>
>>> operator.is_not
<built-in function is_not>

```

**Comment by jvanasco** [comment]
@zzzeek @CaselIT I marked my tailing underscore proposal as rejected.

**Comment by zzzeek** [comment]
we can still ask twitter I often get a lot of insight from that.   either way

**Comment by xarg** [comment]
The convention could be: trailing underscore should be reserved only for python single-word keywords.

Ex:

- `is` -> `is_`
- `is not` -> `is_not`

Also compatible with the `operator` module -> less surprises.

**Comment by CaselIT** [comment]
I've pinned this issue and 5435, so maybe we gather some other comment from the community

**Comment by jvanasco** [comment]
PR forthcoming...

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Issue #5429 version 2: Patch Set B: core library** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2200
