### ISSUE TITLE
Add Values to documentation

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5432]
Values, added in #4868, is not present in the documentation.

We should probably add both the `values` factory function and `Values` the class

**Comment by CaselIT** [comment]
Also missing
- `Exists` class
- `column`
- `cte`

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add missing function to documentation: cte, values, Exits, Values** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2068

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Add missing function to documentation: cte, Exits** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2070
