### ISSUE TITLE
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.

### ISSUE THREAD

**Issue by edo101** [sqlalchemy/sqlalchemy#5433]
Hi, so I am trying to update a table in my db thorugh sql alchmey mixed with pandas. This actually might be the culprit of my issue. I am new to sql alchemy, pandas, and python so I used a template my mentor gave me to add to the code. 

Anyways, my script processes csv files. if the file has format error, it will update the status of the file in the table to "error" and move the file to an "error" directory. To this regard I wrote an update table method:

```
def update_csv_status_db(db_instance, name_of_db_instance_tabledict, csvfile_path, dir_status):
    table_dict = db_instance[name_of_db_instance_tabledict]
    csvfile_name = csvfile_path.name
    sql = update(table_dict['table']).where(table_dict['table'].c.CSV_FILENAME == csvfile_name).values(CSV_STATUS=dir_status)
    df = pd.read_sql(sql, table_dict['connection'])
    #df.to_sql('odfs_tester_history_files', con=table_dict['engine'], if_exists='append', index=False)

```
Which is called in this function: 

```
def odf_history_from_csv_to_dbtable(db_instance):
    odfsdict = db_instance['odfs_tester_history']
    #table_row = {}
    totalresult_list = []

    dir_dict, dictofpdir_flist = make_dict_of_csvprocessing_dirs()
    print(dir_dict)
    csvbase_path_list = dictofpdir_flist["csvbase_path_list"]
    archivefiles_path_set = dictofpdir_flist["archivefiles_path_set"]
    errorfiles_path_set = dictofpdir_flist["errorfiles_path_set"]
    emptyfiles_path_set = dictofpdir_flist["emptyfiles_path_set"]

    for csv in csvbase_path_list:  # is there a faster way to compare the list of files in archive and history?
        if csv.name in archivefiles_path_set:
            print(csv.name + " is in archive folder already")
        elif csv.name in errorfiles_path_set:
            print(csv.name + " is in error folder already")
        elif csv.name in emptyfiles_path_set:
            print(csv.name + " is in empty folder already")
        else:
            csvhistoryfilelist_to_dbtable(csv, db_instance)
            df_tuple = process_csv_formatting(csv)
            df_cnum, odfscsv_df = df_tuple
            if df_cnum == 1:
                trg_path = Path(dir_dict['empty_dir'])
                csv.rename(trg_path.joinpath(csv.name))
                update_csv_status_db(db_instance, 'odfs_tester_history_files', csv, 'empty')
            elif df_cnum == 0 and len(odfscsv_df.index != 0):
                result = odfscsv_df.to_sql('odfs_tester_history', con=odfsdict['engine'], if_exists='append', index=False)
                totalresult_list.append(result)
                trg_path = Path(dir_dict['archive_dir'])
                csv.rename(trg_path.joinpath(csv.name))
                update_csv_status_db(db_instance, 'odfs_tester_history_files', csv, 'archive')

    return totalresult_list
```

So a very weird error happens after this runs. Testing it with one file that contains bad formating, an "error" file. it actually processes the file, moves it to the error directory and updates the table. However at the end, the program breaks and returns the following error:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\result.py", line 1161, in _fetchall_impl
    return self.cursor.fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/sys_nsgprobeingestio/Documents/dozie/odfs/odfshistory3.py", line 269, in <module>
    odf_history_from_csv_to_dbtable(db_instance)
  File "C:/Users/sys_nsgprobeingestio/Documents/dozie/odfs/odfshistory3.py", line 244, in odf_history_from_csv_to_dbtable
    update_csv_status_db(db_instance, 'odfs_tester_history_files', csv, 'error')
  File "C:/Users/sys_nsgprobeingestio/Documents/dozie/odfs/odfshistory3.py", line 178, in update_csv_status_db
    df = pd.read_sql(sql, table_dict['connection'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py", line 438, in read_sql
    chunksize=chunksize,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1231, in read_query
    data = result.fetchall()
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\result.py", line 1216, in fetchall
    e, None, None, self.cursor, self.context
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\result.py", line 1211, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\result.py", line 1163, in _fetchall_impl
    return self._non_result([])
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\result.py", line 1168, in _non_result
    "This result object does not return rows. "
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
```

I have noticed when I have multiple files, it will process some of them, the rest it will leave once it hits this error. And it is spontaneous on when it hits the error. How can I fix this? 

Is there a way to update thet able without needing to use pandas _readsql? COuld this  be the issue? The fact that I am using pandas _tosql. And if so, what alternative can i use to commit the update?

**Comment by zzzeek** [comment]
this error occurs when you try to read rows from a SQL statement that does not return rows.  example of such statements are INSERT, UPDATE and DELETE statements that do not feature RETURNING.  A SELECT statement, on the other hand, should always return rows, even if the number of rows is zero.

a second condition that causes this error is when the database driver has failed on a previous statement, and the application attempts to continue to use the database connection without rolling back the transaction first, however this requires additional conditions to be in place that are not easy to replicate unless the SQL statement is accessing some specific kind of issue.

from our end, we can't provide any insight into this without extra information, and I am noticing that if you used the "question" template then we didnt ask for it, so fixing that now:

**Versions**
 - OS:
 - Python:
 - SQLAlchemy:
 - Database:
 - DBAPI:


Then you want to add SQL logging output right before the error that shows the SQL statement that was emitted right before these non-existent rows were attempted to be fetched.  set echo=True on create_engine() to show this.

**Comment by edo101** [comment]
@zzzeek  What is DBAPI? How do I find this information? Also how do I find out which SQLAlchemy Version I have which is what I assume you are asking?

**Comment by zzzeek** [comment]
I would recommend a quick gothru the Core tutorial, e.g. https://docs.sqlalchemy.org/en/13/core/tutorial.html  answers below:

> @zzzeek What is DBAPI? How do I find this information? 

the DBAPI is your database driver.  unless you are using SQLite, you had to install one, and it is also referred towards in your database URL.  Introduced here in the tutorial : https://docs.sqlalchemy.org/en/13/core/tutorial.html#connecting and it is referred to in introductory chapters like https://docs.sqlalchemy.org/en/13/intro.html  https://docs.sqlalchemy.org/en/13/core/engines.html  glossary entry https://docs.sqlalchemy.org/en/13/glossary.html#term-DBAPI

> Also how do I find out which SQLAlchemy Version I have which is what I assume you are asking? 

if you just installed you are likely on 1.3.18, in your Python interpreter you can follow the example at: https://docs.sqlalchemy.org/en/13/core/tutorial.html

**Comment by zzzeek** [comment]
hoping you fixed your issue.

**Comment by wuwenrufeng** [comment]
this issue review in sqlalchemy==1.4.2, in sqlalchemy==1.3.2 is work.

**Comment by organisciak** [comment]
Thank you @wuwenrufeng. This error broke the Jupyter %sql magic, which I use as an in-between when my students start to transition gently from SQL to Python (in Colab). The default Colab install has this broken combination, so downgrading `sqlalchemy` is the temporary solution.

**Comment by joelash** [comment]
I'm a bit confused here, is this actually a bug in 1.4.x (I'm seeing it in 1.4.12) and therefore I should downgrade? Or is this not a bug and I should fix my code to work? I made no database related changes today but somehow picked up a new version of 1.3.23 -> 1.4.12 and am seeing this. Hoping to know what the recommended thing to do here is.

**Comment by zzzeek** [comment]
> I'm a bit confused here, is this actually a bug in 1.4.x (I'm seeing it in 1.4.12) and therefore I should downgrade? Or is this not a bug and I should fix my code to work? I made no database related changes today but somehow picked up a new version of 1.3.23 -> 1.4.12 and am seeing this. Hoping to know what the recommended thing to do here is.

you may have come across a regression (i.e. a bug in sqlalchemy), or your program might be doing some pattern that wasn't fully supported in 1.3 and just stopped working (possibly a bug in sqlalchemy, if we need to support that pattern), etc.    This is also a thing that happens as the result of bugs in the DBAPI drivers too, most particularly the MySQL drivers historically.    if you look above you will see that nobody has shown us code that can reproduce any kind of issue so once we get an [MCVE](http://stackoverflow.com/help/mcve) that illustrates how to reproduce the failure we can then decide if there's a bug to be fixed here, so if you can show us your reproducing test case / stack trace / share details of database in use etc. we would love to look into that.  thanks!

**Comment by zzzeek** [comment]
oh also the poster at the top is using pandas.  [they also had to fix things for their sqlalchemy support](https://github.com/pandas-dev/pandas/pull/40471).  so make sure you are on the latest pandas if this is a pandas thing.

**Comment by joelash** [comment]
The broken function call is not using Pandas, but it is using [Records](https://github.com/kennethreitz/records) the line is essentially as below. I'm on PostgreSQL 12.x using `psycopg2-binary==2.8` I can try to create a sqlalchemy only example but will need to find some time to experiment.

```python
db = records.Database(...)
db.query("CREATE SCHEMA IF NOT EXISTS foo")
```

**Comment by CaselIT** [comment]
I think you should report the issue on the records library, since it seems that it's trying to retrieve rows from any command even if no row is returned, like in your example

**Comment by joelash** [comment]
@CaselIT I'm planning on it, but when an underlying library has breaking changes in a minor version change like this I usually want to know what happened in the underlying library as well.

**Comment by zzzeek** [comment]
> @CaselIT I'm planning on it, but when an underlying library has breaking changes in a minor version change like this I usually want to know what happened in the underlying library as well.

please refer to https://www.sqlalchemy.org/download.html#versions for a complete description of SQLAlchemy's versioning system.

**Comment by zzzeek** [comment]
> The broken function call is not using Pandas, but it is using [Records](https://github.com/kennethreitz/records) the line is essentially as below. I'm on PostgreSQL 12.x using `psycopg2-binary==2.8` I can try to create a sqlalchemy only example but will need to find some time to experiment.
> 
> ```python
> db = records.Database(...)
> db.query("CREATE SCHEMA IF NOT EXISTS foo")
> ```

We can go with a "Records" example if you have something simple and succinct to run.

**Comment by zzzeek** [comment]
though it looks like Records has not been maintained for almost 18 months so not sure if we can get patches in on their end.

**Comment by joelash** [comment]
Thanks @zzzeek, didn't realize the versioning system of SQLAlchemy. We're planning on pulling Records out due to its lack of maintenance.

**Comment by zzzeek** [comment]
it's still pretty important we understand the issue so if you can provide a quick example / complete stack trace that woudl be helpful.

**Comment by joelash** [comment]
Here's a gist that recreates this bug, let me know if you have any questions. https://gist.github.com/joelash/c3e554174249bfa104ecbac04f6023b6

**Comment by zzzeek** [comment]
> Here's a gist that recreates this bug, let me know if you have any questions. https://gist.github.com/joelash/c3e554174249bfa104ecbac04f6023b6

the change here is that the Result object no longer allows one to call .keys() if the result does not return rows.  this is a regression in that it should be emitting a 2.0 deprecation warning for legacy use, will open a new issue.

**Comment by zzzeek** [comment]
see #6427

**Comment by joelash** [comment]
Thanks @zzzeek

**Comment by nikochiko** [comment]
Is it possible to intentionally allow this using some kind of argument or configuration? I am using QuestDB's SQL API with SQLAlchemy, and it does not have support for the RETURNING keyword. I just need the INSERT query to go through after I run `session.add(instance)`

**Comment by CaselIT** [comment]
I don't think this is the same error.
Session.add does not use returning if the dialect does not support it.

**Comment by nikochiko** [comment]
I am using the PostgreSQL dialect (https://questdb.io/docs/reference/api/postgres/). Postgres does support returning, but questdb doesn't

**Comment by nikochiko** [comment]
questdb's compatibility with postgres seems highly limited. i think just custom sql queries would be better for my use case now

**Comment by CaselIT** [comment]
You may be able to change the returning options in the dialect. Also maybe there is a dialect for your db.

**Comment by nikochiko** [comment]
Thank you so much. I googled after reading your comment and found this - https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.implicit_returning

> Also maybe there is a dialect for your db.

I didn't find one and created this feature request https://github.com/questdb/questdb/issues/1028. Do let me know if you come across any

**Comment by pgjmsingh** [comment]
I encountered this issue sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
I after spending 4 hours I realized that it was a print statement which was causing this issue when I removed print statement it worked just fine. I was using print statement to print output of dynamic sql :-)

**Comment by khalidxc** [comment]
I faced the same problem,
However, adding this statement ' SET NOCOUNT ON ' before the update,delete...SPs etc solved the problem for me.

**Comment by zzzeek** [comment]
let me add a little note to folks obviously coming here and reading this that this particular error message "this result set does not return rows" can be caused by lots and lots of different things, so there's no one magic solution for it, the specific context / stack trace / SQL logs / database in use / driver in use (also known as the DBAPI) and even the OS platform are all potentially significant factors

* there are lots of reasons why one SQL statement returns rows and another doesn't (SELECT vs. INSERT, or INSERT RETURNING, etc.)
* or, why a SQL statement is supposed to return rows but the database does not send the information that the driver expects in order for it to set this up (probably your NOCOUNT problem above is something like this) 
* or, why a SQL statement is supposed to return rows but the driver does not correctly interpret it (such as a driver that parses the SQL to guess if there are rows or not and the statement has a comment or CTE prefix that throws off this guessing, or doesn't function correctly if there are zero rows, things like that)
* or, why a SQL statement is supposed to return rows but there is some uncleared error condition that keeps if from doing so (used to happen lots with MySQL drivers when the state of the connection were interrupted)
* applications themselves may not be correctly set up to accommodate result sets that are non-row-returning (Records bug above)

so unfortunately if you are getting this bug, it's much better to try to figure out what the exact problem is, I know it is way easier to just "throw something" at it, which I do all day with other tools I dont know so well like Jenkins, I've spent the last three days just throwing stuff at a certain scalability issue not really understanding half their docs, but for this project, at least for now *we're here* and if you can give us specifics without a lot of other noise, we are *usually* pretty fast to respond and as you might see above we identified a small backwards-compatibility regression that we had to fix.   we fix things for this project when something is really broken and there's a clear fix to be made.   thanks for reading!

**Comment by r00ntje** [comment]
```
DECLARE @parameters TABLE (ParameterName VARCHAR(100))
INSERT INTO @parameters VALUES('par1')
INSERT INTO @parameters VALUES('par2')
SELECT * FROM @parameters
```

This creates rows, but still results in the no rows error. So I can't use INSERT anywhere in my query?

**Comment by zzzeek** [comment]
that statement has procedural directives inside of it so the DBAPI likely doesn't know how to create a .description from that.  when using procedural directives always [use the raw cursor](https://docs.sqlalchemy.org/en/14/core/connections.html#working-with-the-dbapi-cursor-directly).

**Comment by zzzeek** [comment]
background on this error for folks coming across this is at [this result object does not return rows](https://docs.sqlalchemy.org/en/14/faq/connections.html#commands-out-of-sync-you-can-t-run-this-command-now-this-result-object-does-not-return-rows-it-has-been-closed-automatically).
