### ISSUE TITLE
How to get value from sqlalchemy .execute() method? Python + Sqlalchemy+ MS SQL server

### ISSUE THREAD

**Issue by edo101** [sqlalchemy/sqlalchemy#5434]
Hi wrote a method to get the status of a csv file in a sql server table. The table has column named CSV_STATUS, and for the particular csv, I'd like my method to give me the value of the CSV status. I wrote the following function:

```
def return_csv_status_db(db_instance, name_of_db_instance_tabledict, csvfile_path):
    table_dict = db_instance[name_of_db_instance_tabledict]
    csvfile_name = csvfile_path.name
    sql = db.select([table_dict['table'].c.CSV_STATUS]).where(table_dict['table'].c.CSV_FILENAME == csvfile_name)
    result = table_dict['engine'].execute(sql)
    print(result)
```

Whenever I print result, it returns: `<sqlalchemy.engine.result.ResultProxy object at 0x0000005E642256C8>` How can I extract the value of the select statement?

**Versions**
 - OS: Windows Server 2012
 - Python: 3.6
 - SQLAlchemy: Not sure. Latest one?
 - Database: SQL Server 2017
 - DBAPI: Not sure, default?

**Comment by zzzeek** [comment]
> 
> Whenever I print result, it returns: `<sqlalchemy.engine.result.ResultProxy object at 0x0000005E642256C8>` How can I extract the value of the select statement?

going to point again to the Core tutorial:

https://docs.sqlalchemy.org/en/13/core/tutorial.html#selecting

examples there illustrate how to use fetchall(), fetchone(), python iteration, etc.

**Comment by edo101** [comment]
@zzzeek  with my code as written, Pycharm can't find a method for result called fetchone(). Why is this?

**Comment by zzzeek** [comment]
I don't use pycharm so I would recommend you reach out to more generalized help sources for programming issues like these, including IRC, mailing list, stackoverflow.    these are listed out here: https://www.sqlalchemy.org/support.html

**Comment by edo101** [comment]
@zzzeek  A better question is, does that fetchone() work on sqlalchemy.engine.result.ResultProxy objects? Because that's what type my result is in my script

**Comment by zzzeek** [comment]
> @zzzeek A better question is, does that fetchone() work on sqlalchemy.engine.result.ResultProxy objects? Because that's what type my result is in my script

I appreciate that you're confused here but the effort that you would need to make to understand these concepts is within the same Core tutorial.    The ResultProxy is introduced at https://docs.sqlalchemy.org/en/13/core/tutorial.html#executing .        The tutorial is written such that you can run a Python interpreter of your own and type the same commands locally, so that you get a feel and familiarity for what's going on.

**Comment by zzzeek** [comment]
feel free to reopen
