### ISSUE TITLE
proposal: standardize additional operator names for SqlAlchemy2.0 

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#5435]
Building off of #5429, is there a benefit to clarify any other commands that use the pythonic naming scheme (e.g. startswith, endswith) and do not mirror python builtins, to have internal underscores?

| current | potential | notes |
| ------- | ------- | ------- |
| isnot_distinct_from | is_not_distinct_from | |
| notmatch | not_match | `not_regexp_match` exists |
| notlike | not_like | |
| notilike | not_ilike | |
| notbetween | not_between | |
| istrue | is_true | |
| isfalse | is_false | |
| nullsfirst | nulls_first | |
| nullslast | nulls_last | |
| notcontains | not_contains | |
| notendswith | not_endswith | |
| notstartswith | not_startswith | |

**Comment by zzzeek** [comment]
i think using underscores there is fine.   i still want to stop short of "startswith" and "endswith" b.c. i think using Python standard library as a guide is best.

**Comment by zzzeek** [comment]
as long as we keep all the old names for compatibility we can do this.

**Comment by jvanasco** [comment]
@zzzeek if this list looks good, I can work on it over the next few days.

**Comment by CaselIT** [comment]
I think the deprecation path we decided on a dev meeting was 
- documentation only for 1.4
- warn in 2.0
- remove at a later date in 2.x series

**Comment by jvanasco** [comment]
I think `warn` will be difficult for many of these, but I can try.  I don't believe I generated warns in the earlier ticket.

**Comment by CaselIT** [comment]
warn would be a 2.0 problem, for 1.4 just a note in the documentation

**Comment by zzzeek** [comment]
im probably not in favor of warn for 2.0 either because these are just little names we can hide away and can hang around for years.   depends on how it goes over the course of 1.4.

**Comment by jvanasco** [comment]
ok this is great. I'll start work on this tomorrow.

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Apply underscore naming to several more operators** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2332
