### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [sqlalchemy/sqlalchemy#5436]
**Summary**
Installing sqlalchemy on aarch64 via pip using command "pip3 install sqlalchemy" tries to build wheel from source code

**Problem description**
sqlalchemy don't have wheel for aarch64 on PyPI repository. So, while installing sqlalchemy via pip on aarch64, pip builds wheel for same resulting in it takes more time to install sqlalchemy. Making wheel available for aarch64 will benefit aarch64 users by minimizing sqlalchemy installation time.

**Expected Output**
Pip should be able to download sqlalchemy wheel from PyPI repository rather than building it from source code.

@sqlalchemy-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make sqlalchemy wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by CaselIT** [comment]
Hi,

Wheels are a fairly recent addition, and are available only for the last three releases.
Currently we use a [github action](https://github.com/sqlalchemy/sqlalchemy/blob/master/.github/workflows/create-wheels.yaml) to build the wheels and from the [docs](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources) it does not seem to support the arm architecture in their shared runners.

Also at the moment we are using [manylinux2010](https://github.com/pypa/manylinux) to generate the linux build, and it does not seem to support the arm architecture. [Manylinux2014](https://github.com/pypa/manylinux#manylinux2014) does seems to support it so we could probably use it for arm.

Adding arm wheels should be relatively easy once github supports the arm architecture in its runner. The github actions also support private runners (I have to check if they can use the arm architecture) but at the moment I'm not sure if we have plans on adding private runners to use the arm builds @zzzeek .

What where you proposing regarding helping to generate the wheels?

**Comment by odidev** [comment]
Thanks, @CaselIT for the quick response. 

> What were you proposing regarding helping to generate the wheels?

Since, Travis-ci have added support for arm64, I can help with adding Travis-ci builds for arm64. Please share your thoughts on this.

**Comment by CaselIT** [comment]
At this time I think we would prefer to wait and see it github makes arm runners available, since managing another ci is less than ideal, and at the moment we would prefer to avoid it.

**Comment by odidev** [comment]
@CaselIT We can use qemu to run an aarch64 build on x86 machine. However, this will be a bit slow but It will enable us to run things in an aarch64 emulated environment. If you are ok with this approach, I can work on it and ship the changes. Please let me know your thoughts here.

**Comment by CaselIT** [comment]
I'll have to better check this, but it seems we could use this repo https://github.com/dbhi/qus as a baseline for qemu.

I think we would also need to run the tests on commits for the arm architecture if we are going to publish wheels for it, so if you want to give it a try I think you could probably start from that.

**Comment by odidev** [comment]
Thanks @CaselIT I will work on it and update you.

**Comment by odidev** [comment]
Hi @CaselIT ,

Thanks for the suggestion.

I have added arm64 jobs to workflows using qemu. Please check below links for updated workflows and test runs:
**For test :**
**Script** :https://github.com/odidev/sqlalchemy/blob/arm_support/.github/workflows/run-test.yaml#L92-L113
**Github-action report** : https://github.com/odidev/sqlalchemy/actions/runs/181304461

**For wheel creation:**
**Script** : https://github.com/odidev/sqlalchemy/blob/arm_support/.github/workflows/create-wheels.yaml#L296-L314
**Github-action report** : https://github.com/odidev/sqlalchemy/actions/runs/181304464

The wheel is generated for all the python version successfully in arm64

**Result :**
Added 6 test jobs for arm64. Please find below analysis on the test results:
Testing arm64-python3.6-cext : passed
Testing arm64-python3.6-nocext : passed
Testing arm64-python3.7-cext : passed
Testing arm64-python3.7-nocext : passed
Testing arm64-python3.8-cext : failed
Testing arm64-python3.8-nocext : passed

2 test are failing "Testing arm64-python3.8-cext" job.

**Failed cases:**

```
____________ ResultSetTest_sqlite+pysqlite_3_22_0.test_string ____________
[gw3] linux -- Python 3.8.0 /sqlalchemy/.tox/github-cext/bin/python
Traceback (most recent call last):
File "/sqlalchemy/.tox/github-cext/lib/python3.8/site-packages/sqlalchemy/testing/profiling.py", line 259, in wrap
return rv
File "/usr/lib/python3.8/contextlib.py", line 120, in exit
next(self.gen)
File "/sqlalchemy/.tox/github-cext/lib/python3.8/site-packages/sqlalchemy/testing/profiling.py", line 319, in count_functions
raise AssertionError(
AssertionError: Adjusted function call count 496 not within 5.0% of expected 469, platform 3.8_sqlite_pysqlite_dbapiunicode_cextensions. Rerun with --write-profiles to regenerate this callcount.
......................................................
FAILED test/aaa_profiling/test_resultset.py::ResultSetTest_sqlite+pysqlite_3_22_0::test_string
FAILED test/aaa_profiling/test_resultset.py::ResultSetTest_sqlite+pysqlite_3_22_0::test_unicode

```
Please check https://github.com/odidev/sqlalchemy/runs/907099283?check_suite_focus=true for complete logs

I have resolved this issue by changing the variance from 0.05 to 0.06 in [profiling.py](https://github.com/odidev/sqlalchemy/blob/arm_support/lib/sqlalchemy/testing/profiling.py#L233) and the report is :

**For test :**
**Github-Action** : https://github.com/odidev/sqlalchemy/actions/runs/184307906

**For wheels :**
**Github-Action** : https://github.com/odidev/sqlalchemy/actions/runs/184307902

**Result :**
All 6 test jobs are passing for arm64.
Testing arm64-python3.8-cext : passed

**Conclusion** :
All test cases are passing for all python versions.

Changes required for ARM64: https://github.com/odidev/sqlalchemy/commit/6f11e938095f60ad6db0806ab1032074090d05b4
Can I raise PR with above changes or let me know if any more changes required?

**Comment by CaselIT** [comment]
Thanks, this is looking great. I've yet to take a closer look at the changes, but it seems quite a nice start!

Regarding the failures, I think we should probably have a key in the profile line that identifies the architecture if different than the classi x86/x64, since the number of function call may depend on it. I can do that change.

I've also noticed that somehow py35 wheels are broken somehow (not in arm, in the old script). I'll take a look at it.

If you want to complete the script with also the upload to pypi and open a PR we can continue there.
If you want to try a complete run using the test pypi, you can un-comment [this line](https://github.com/odidev/sqlalchemy/blob/arm_support/.github/workflows/create-wheels.yaml#L20) to target the test-pypi and then change the project name in this [setup.cfg line](https://github.com/sqlalchemy/sqlalchemy/blob/master/setup.cfg#L2) to something unique

**Comment by CaselIT** [comment]
Another note.

I've noticed that to create the linux wheel you are using ubuntu 18.04. It is usually advisable to use these images https://github.com/pypa/manylinux to generate them, so that older systems/different releases can install them.
It seems that the action used to create the x86 linux weel https://github.com/RalfG/python-wheels-manylinux-build#using-a-different-manylinux-container may also be used on arm. Have you already tried it?

**Comment by CaselIT** [comment]
Regarding the tests that fail on arm I've added this change.
https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2110

Regarding failure on py35 wheel on master I've added this change
https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2111
