### ISSUE TITLE
Flask server crashes when making a database query with sqlalchemy

### ISSUE THREAD

**Issue by DimitarDevP** [sqlalchemy/sqlalchemy#5437]
I have created this sqlalchemy abstraction layer for performing CRUD operations. I have been using it for well over 6 months now and it has served me just fine. 
The other day though when I was developing out of nowhere my Flask server started crashing. So i played around with it for a while and found that the error is not with Flask but rather with the database or the database connection.

I saw several different errors and behaviors. Some time it will just crash the server without an error message, other times it will fail to execute the query but keep the server running and i have seen it log the error and crash the server right after.

I saw a few different errors. The one which appears most often is the  following:
```
(MySQLdb._exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")
[SQL: SELECT * FROM _users]
(Background on this error at: http://sqlalche.me/e/f405)
```
But i also saw this error:
```
(MySQLdb._exceptions.OperationalError) (2000, 'Unknown MySQL error')
[SQL: SELECT * FROM _user_types]
(Background on this error at: http://sqlalche.me/e/e3q8)
```
And this:
```
(MySQLdb._exceptions.OperationalError) (2006, 'Lost connection to MySQL server during query')
[SQL: SELECT * FROM _states]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

and this a `"No Database Selected"` error which I cannot seem to reproduce right now. 

Here is where it crashed last, but it has crashed on multiple other routes too.
```
def get_users(self, request):
    users = fdb.read("""SELECT * FROM _users""", (), True)
    return jsonify({
        "allUsers": users
    })

def read(self, query_string, query_params = (), fetchall = True):
    try:
        data = self.connection.execute(query_string, query_params)
        if fetchall: 
            data = data.fetchall()
            data = [dict(row) for row in data]
        else:
            data = data.fetchone()
            data = dict(data)
        return data
    except Exception as e:
        print(e)
        return e
    finally:
        pass # close
```

Unfortunately I cannot provide a sure way to reproduce these errors. It tends to happen more when there is a big amount of traffic hitting the REST API (multiple requests). I have only gotten this error when I am using Fetch/Axios/xhr. I tried to reproduce with cURL, postman and from the browser and none of those caused the error. 

 - OS: Arch Linux
 - Python: 3.8.3
 - SQLAlchemy: 1.3.17
 - Database: MySQL (built in to XAMPP)

**Comment by zzzeek** [comment]
hi there -

unfortunately these are difficult problems to diagnose and as it seems to occur under load, it's possible you have race conditions occurring , meaning a particular MySQL connection is possibly being shared between threads.  it also sometimes refers to bugs within the MySQL driver or server itself, and sometimes can occur if an error occurs on a MySQL connection that isn't handled properly, and then the connection is attempted to be used again.

There's nothing on the SQLAlchemy side that really relates to this except that you need to ensure ORM sessions and database connections are not shared between threads as well as that errors raised by the database are handled properly.    

I would note that catching an exception and then "returning" it does not seem like correct Python, that should be a "raise" and the exception should be propagated outwards so that the failure is handled correctly.   it's not clear if that's the source of the problem alone but I would definitely fix that code first.

**Comment by DimitarDevP** [comment]
Thanks for taking the time to respond. 

First of all, yes i agree that returning an exception is not the pythonic way of handling exceptions. I don't know what was going on in my head when I wrote that, thanks for noticing and pointing it out. That could be the cause of the server crashing because it was returning an object of type `OperationalError` and trying to parse it as `JSON` and return it. 

Second i did some research and found out that if a database is being used by someone (lets say query number N) and we get another query (query number N + 1) while the query number N is still being executed, there is some "undefined" behavior. Most common will be an error `1046 - No Database Selected` because it cannot establish a connection with the database.

Before I go ahead and work on some queuing system, is there an easy way of solving this issue? I lowered the pool size to only 2 and it seems to work fine for now, but if this goes to production as is it will most likely reappear especially under heavy loads.

**Comment by zzzeek** [comment]
the "no database selected" issue is when you use a MySQL URL that does not include a database portion, like "mysql://user:pass@hostname/".    the MySQL dialect is not prepared to handle those right now.    However it's strange you would only get that issue sporadically, so I would assume this is not in the database URL, unless you are creating new engines on the fly or something like that.

**Comment by zzzeek** [comment]
that is, in my experience "no database selected" doesn't mean you aren't connected, it means you're connected and the driver is runninig commands but there is no database that's been selected, which we do at a console with the "use" statement.

**Comment by DimitarDevP** [comment]
I dont connect to the database "on the fly". I connect to the database the first time i instantiate an object of my FlaskDB class. Here is the method I call:

```
def connect_flask_sql_alchamy(self, engine_name, user, password, host, database):
        uri = engine_name + "://" + user + ":" + password + "@" + host
        self.engine = create_engine(uri, pool_size=2, max_overflow=0)
        self.engine.execute("USE "+database)
        self.connection_type = FLASK_SQL_ALCHEMY
```

I only call this method once - when the server starts and creates an instance of the FlaskDB class.

I never executed a query like `"USE database_name"` except for in the start.

**Comment by zzzeek** [comment]
ahha.   well that is in fact your problem.    an "engine" is a whole pool of connections so your "use" statement will only take effect for one of those connections, and not all the rest.       so it's somewhat miraculous your application isn't crashing immediately with even just a few requests.

is there some reason you don't want to have the "database" portion in the URL?    

if so, the correct way to do what you have above, assuming there is some reason you can't have the database portion in the URL (can't really image what that would be), would be to use the [connect](https://docs.sqlalchemy.org/en/13/core/events.html?highlight=connect#sqlalchemy.events.PoolEvents.connect) event:

```
engine = create_engine(...)

from sqlalchemy import event

@event.listens_for(engine, "connect")
def _use_database(dbapi_connection, rec):
    cursor = dbapi_connection.cursor()
    cursor.execute("USE database")
    cursor.close()

```

**Comment by jvanasco** [comment]
> I only call this method once - when the server starts and creates an instance of the FlaskDB class.

Adding to what @zzzeek wrote, this pattern can (will) create problems if your Flask project is run in a forking model and you invoke that code *before* the fork.  

See:

* ["Working with Engines and Connections : Engine Disposal"](https://docs.sqlalchemy.org/en/13/core/connections.html#engine-disposal)
* ["Connection Pooling : Using Connection Pools with Multiprocessing"](https://docs.sqlalchemy.org/en/13/core/pooling.html#using-connection-pools-with-multiprocessing)
* ["FAQ: How do I use engines / connections / sessions with Python multiprocessing, or os.fork()?"](https://docs.sqlalchemy.org/en/13/faq/connections.html#how-do-i-use-engines-connections-sessions-with-python-multiprocessing-or-os-fork)

There is also another FAQ for the out-of-sync message, which will point you to dispose also possibly being involved here:

* [“Commands out of sync; you can’t run this command now” / “This result object does not return rows. It has been closed automatically”](https://docs.sqlalchemy.org/en/13/faq/connections.html#commands-out-of-sync-you-can-t-run-this-command-now-this-result-object-does-not-return-rows-it-has-been-closed-automatically)

**Comment by DimitarDevP** [comment]
> ahha. well that is in fact your problem. an "engine" is a whole pool of connections so your "use" statement will only take effect for one of those connections, and not all the rest. so it's somewhat miraculous your application isn't crashing immediately with even just a few requests.
> 
> is there some reason you don't want to have the "database" portion in the URL?
> 
> if so, the correct way to do what you have above, assuming there is some reason you can't have the database portion in the URL (can't really imagine what that would be), would be to use the [connect](https://docs.sqlalchemy.org/en/13/core/events.html?highlight=connect#sqlalchemy.events.PoolEvents.connect) event:
> 
> ```
> engine = create_engine(...)
> 
> from sqlalchemy import event
> 
> @event.listens_for(engine, "connect")
> def _use_database(dbapi_connection, rec):
>     cursor = dbapi_connection.cursor()
>     cursor.execute("USE database")
>     cursor.close()
> ```

Thanks for the answer. This solved my issue.

I should have read the docs before opening an issue, i'm sorry.
