### ISSUE TITLE
NullPool connections not closed in interactive session on MSSQL

### ISSUE THREAD

**Issue by thorstenkampe** [sqlalchemy/sqlalchemy#5440]
**Describe the bug**
`NullPool` connections are not closed in interactive session (IPython) on MSSQL

**Expected behavior**
After explicitly closing a `NullPool` connection I expect all sessions on the database server opened by SQlAlchemy gone. This is how it works with Oracle, PostgreSQL and MySQL but not with MSSQL.

**To Reproduce**

```py
>>> from sqlalchemy import create_engine
>>> from sqlalchemy.pool import NullPool

>>> dsn = 'mssql://sa:password@HOST/master?driver=ODBC+Driver+17+for+SQL+Server'
>>> eng = create_engine(dsn, poolclass=NullPool)
>>> conn = eng.connect()
>>> conn.close()
```

`sp_who2` (or similar tools) show that there is still an open session by Python (SQLAlchemy)

**Versions.**
 - OS: Windows 10
 - Python: 3.8.3
 - SQLAlchemy: 1.3.18
 - Database:  SQL Server 2019 on Windows and Linux

**Additional context**
It takes about 75 seconds until the session is finally gone. Exiting IPython makes the session disappear immediately.

**Comment by zzzeek** [comment]
hi -

pyodbc uses its own internal connection pooling by default.  see the discussion here: https://groups.google.com/g/pyodbc/c/Mg6rFPb4gw8?pli=1  as well as the documenation: https://github.com/mkleehammer/pyodbc/wiki/The-pyodbc-Module#pooling   so you'd want to turn this off.

I'll add this to the docs.

**Comment by thorstenkampe** [comment]
Confirming that `pyodbc.pooling = False` has the effect of immediately closing the session.

**Comment by BK-Go-Python** [comment]
you can turn off by conn.close_all()
