### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by crushsoccer** [sqlalchemy/sqlalchemy#5444]
I'm trying to build a chatter bot using python on windows 10. I downloaded chatterbot from github because pip have some problems installing chatterbot.The import and every thing works perfectly fine in my code up until when i try to initialize the package (chatbot) it gives me this error.

AttributeError: module 'time' has no attribute 'clock'

Can anyone help me please?

**Comment by zzzeek** [comment]
hi there -

can you attach the complete stack trace as well as what SQLAlchemy version is in use?
