### ISSUE TITLE
Regular expression search operator

### ISSUE THREAD

**Issue by TMiguelT** [sqlalchemy/sqlalchemy#5447]
**Is your feature request related to a problem? Please describe.**
I would like to be able to execute a "find all rows where column `a` matches regex `b`" query in a database-independent manner. 

**Describe the solution you'd like**
I propose we add the following method to `sqlalchemy.sql.operators.ColumnOperators`:

```
def regex_match(self, pattern: str):
    """
    :param pattern: A POSIX regular expression
    Returns an expression that will be converted to a database-appropriate regex match
    """
```
The call `column.regex_match('[a-z]*')` would then evaluate to:
* [Postgres](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP): `column ~ "[a-z]*"`
* [SQLite](https://www.sqlite.org/lang_expr.html#the_like_glob_regexp_and_match_operators): `column REGEXP "[a-z]*"`
* [MySQL](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#operator_regexp): `column REGEXP "[a-z]*"`
* [Oracle](https://docs.oracle.com/cd/B12037_01/server.101/b10759/conditions018.htm#SQLRF00501): `REGEXP_LIKE(column, "[a-z]*")`
* MSSQL: throw exception

**Describe alternatives you've considered**

* Doing nothing? Users can't use regular expressions in queries, which limits the ability for users to write powerful queries
* Relying on `column.op`()`? This is not database-independent, since there is no one regex operator used in the main DBMS
* Including regex flags in the function call? I considered this, but many DBMS don't support it, e.g. SQLite

**Comment by zzzeek** [comment]
hi there -

we would welcome efforts / PRs on issue #1390.  There is some work done already for PostgreSQL in our gerrit tracker at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/101 .   thanks for the info that this can also be expanded for other DBs now, we would need to look into that.

As we already have an issue for this, closing this as a dupe.

**Comment by TMiguelT** [comment]
Hi, thanks for pointing me to the right issue, I must have missed it.
