### ISSUE TITLE
Multiple table cross association

### ISSUE THREAD

**Issue by suuuch** [sqlalchemy/sqlalchemy#5448]
**Recently, I realize  a very special situation.**

I have three table .

```
classs TableA(Base):
   id = Integer
   status = Integer
   
   score = relationship("TableB", foreign_keys=TableA.id, primaryjoin='TableA.id == TableB.a_id' )
   payment = relationship("TableC", foreign_keys=TableA.id, primaryjoin='TableA.id == TableC.a_id' )

class TableB(Base):
  id = Integer
  a_id = Integer
  year = Integer
  score = Integer

class TableC(Base):
  id = Integer
  a_id = Integer
  year = Integer
  payment = Integer

```
### Table A Data:
| id  | status  |
| ------------- | ------------- |
| 1 | 100  |
| 2  | 200  |

### Table B Data:
| id  | a_id |year | score |
| ------------- | ------------- | -------- | ----- |
| 1 | 1| 2017 | 600 |
| 2  | 1| 2018 | 630 |

### Table C Data:
| id  | a_id |year | payment |
| ------------- | ------------- | -------- | ----- |
| 1 | 1| 2017 | 2000|
| 2  | 1| 2018 | 3000|
| 3  | 1| 2019 | 3000|

<hr />

### Direct query SQL
```
select *
from tableA
         left join tableB on tableA.id = tableB.id_a
         left join tableC on tableA.id = tableC.id_a
```

### Direct query results 

| id | status | id | id\_a | year | score | id | id\_a | year | payment |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | 100 | 1 | 1 | 2017 | 600 | 1 | 1 | 2017 | 1000 |
| 1 | 100 | 2 | 1 | 2018 | 630 | 1 | 1 | 2017 | 1000 |
| 1 | 100 | 1 | 1 | 2017 | 600 | 2 | 1 | 2018 | 2000 |
| 1 | 100 | 2 | 1 | 2018 | 630 | 2 | 1 | 2018 | 2000 |
| 2 | 200 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL |

## The problem is :
I want add a condition like `TableA.year == TableB.year`
make the sql like this :
```
select *
from tableA
         left join tableB on tableA.id = tableB.id_a
         left join tableC on tableA.id = tableC.id_a on TableB.year= tableC.year
```
But I don't know how.
Can I get some help ?

**Comment by zzzeek** [comment]
OK so "left join tableC on tableA.id = tableC.id_a on TableB.year= tableC.year" is not valid SQL unless you had parenthesis in mind.    did you mean, "left join tableC on tableA.id = tableC.id_a AND TableB.year= tableC.year" ?   you can make this kind of join condition like this:

```
from sqlalchemy import and_
sess.query(TableA).join(TableA.score).join(TableC, and_(TableA.id == TableC.id_a, TableB.year == TableC.year))

```

**Comment by suuuch** [comment]
@zzzeek Can I add this Join in the relationship ?

**Comment by zzzeek** [comment]
you can put it in the "primaryjoin" of the mapped relationship.

to do it on the fly in query.join() is a feature that will be in 1.4, #4472 works on that, you can do it to a limited degree right now as query.join(TableA.payment & (TableB.year == TableC.year)), might work like that.

**Comment by zzzeek** [comment]
feel free to discuss further.
