### ISSUE TITLE
With query in SQLAchamy and postgresql(Amazon redshift) giving syntax error

### ISSUE THREAD

**Issue by shubhranshbslice** [sqlalchemy/sqlalchemy#5449]
I am trying to run this query (Part of script)
`with tn as (select dateadd(minute, -135, getdate()) as last_two_hours_date) insert into loans_emi_updated(     select 
`
Using **create_engine** and **.execute** using python sqlalchemy
But it returns an exception (psycopg2.errors.SyntaxError) syntax error at or near "insert"
LINE 3:             insert into 

Any help for the same?

**Comment by zzzeek** [comment]
likely redshift doesn't support CTEs, I'm not really sure, we dont' support redshift here.

you can try asking either at the https://github.com/sqlalchemy-redshift/sqlalchemy-redshift tracker or more likely use the SQLAlchemy mailing list, IRC channels, etc.   you'd also need to be able to provide a complete example of what you're doing. 

Background on SQLAlchemy community support channels is at: https://www.sqlalchemy.org/support.html

**Comment by shubhranshbslice** [comment]
Okay, thank you for the help
