### ISSUE TITLE
sqlalchemy/1.3.18 requires zzzeeksphinx/1.1.5 but that version was never released

### ISSUE THREAD

**Issue by sandrotosi** [sqlalchemy/sqlalchemy#5450]
Hello,
at https://github.com/sqlalchemy/sqlalchemy/blob/master/doc/build/conf.py#L40 `needs_extensions = {"zzzeeksphinx": "1.1.5"}` but AFAICS, the latest released version of zzzeeksphinx is 1.1.4; there are no tags at https://github.com/sqlalchemyorg/zzzeeksphinx to understand the release process, and on PyPI https://pypi.org/project/zzzeeksphinx/#history 1.1.4 is the latest

can you clarify?

the reason is that building sqla doc from the released tarball fails with:

```
Sphinx version error:
This project needs the extension zzzeeksphinx at least in version 1.1.5 and therefore cannot be built with the loaded version (1.1.4).
```

this is to update the debian packaging of sqlalchemy

Thanks,
Sandro

**Comment by zzzeek** [comment]
hi -

please install dependencies using the [requirements.txt](https://github.com/sqlalchemy/sqlalchemy/blob/master/doc/build/requirements.txt) file.  the pypi releases are not used.

**Comment by sandrotosi** [comment]
i'm afraid that's now how debian works: we do not allow to download software from internet during build time (security and reproducibility reasons); pypi has been updated until recently, would it be possible to keep supporting it? that would help us greatly

**Comment by zzzeek** [comment]
OK....where is the sphinx build required for debian packaging, you are packing HTML documentation or somehting like that?

**Comment by zzzeek** [comment]
zzzeeksphinx 1.1.5 is updated on pypi.  im not sure how else this issue can be serviced, locally the reqs use the github links so that I can make updates and update the site without having to release continuously.

**Comment by sandrotosi** [comment]
> OK....where is the sphinx build required for debian packaging, you are packing HTML documentation or somehting like that?

that's correct, we take the documentation source from the tarball and re-build it when we package the sqlalchemy module, and provide it as a [package](https://packages.debian.org/unstable/python-sqlalchemy-doc) for the debian distribution

> zzzeeksphinx 1.1.5 is updated on pypi.

many thanks for that!

> im not sure how else this issue can be serviced, locally the reqs use the github links so that I can make updates and update the site without having to release continuously.

that's usually fine, but for binary distributions (like debian, almost all others linux distribution) it's generally common practice to rebuild everything from source, so the release of 1.1.5 would ideally help all distros :)

**Comment by sandrotosi** [comment]
@zzzeek would it be possible to release also changelog/0.5.2 to pypi?
build corrently fails with:

```
reading sources... [  5%] changelog/changelog_08
reading sources... [  6%] changelog/changelog_09
The name of the builder is: htmlThe name of the builder is: html/usr/lib/python3/dist-packages/scss/selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''

Exception occurred:
  File "/usr/lib/python3/dist-packages/changelog/docutils.py", line 249, in run
    sorted(versions, key=_str_version_as_tuple)
TypeError: '<' not supported between instances of 'str' and 'int'
```

which seems to be fixed by https://github.com/sqlalchemyorg/changelog/commit/6e0f22fa46b3569fdc9c6671d95f0286577c1acc

thanks!

**Comment by zzzeek** [comment]
I've just released that (changelog 0.5.2).  but then I looked at the changeset and there's a pdb stuck in there.  i hope I removed that but I have a feeling I didn't.  Look for 0.5.3 shortly...

**Comment by zzzeek** [comment]
0.5.3 is up...

**Comment by sandrotosi** [comment]
many thanks! I had a quick local rebuild, and the documentation build fine (i need to wait a few hours for some internal debian processes to kick in and then i'll have the final confirmation); thanks for helping out so qiuckly!

**Comment by sandrotosi** [comment]
alright, i was able to build sqla 1.3.18 in our build setup with the updated zzzeeksphinx and changelog -- thanks @zzzeek ! i believe this issue can be closed

**Comment by zzzeek** [comment]
alright.  it's just those tools arent in my "official" build system they are ad-hoc. so you might have to remind me again someday :(
