### ISSUE TITLE
memoized bug

### ISSUE THREAD

**Issue by heukirne** [sqlalchemy/sqlalchemy#5454]
**Describe the bug**

memoized does not work for dynamic Table such as schema change in the same app

**Expected behavior**

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example. 
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22)

```py
class User(Base):
     __tablename__ = 'user'
     __table_args__ = {'schema':'public'}
     id = Column(Integer, primary_key=True)
     name = Column(String)

     def setSchema(schema):
        __table_args__ = {'schema':schema}

User.setSchema('public')
sa.select(User.name).where(User.name == "name1").execute().fetchall()

User.setSchema('someschema')
sa.select(User.name).where(User.name == "name1").execute().fetchall()
```

**Error**

```
Should change schema on query but memoization do not update
```

**Versions.**
 - OS: 
 - Python:
 - SQLAlchemy:
 - Database:
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
please provide a complete reproducing example of the bug.   I don't know what a "dynamic table" is.  thanks!

**Comment by heukirne** [comment]
Working in progress... sorry ;)

**Comment by heukirne** [comment]
Update description... could you please check that @zzzeek ?

**Comment by zzzeek** [comment]
OK it sounded like this was what you were doing.   

The above pattern is supported by the [schema translate map](https://docs.sqlalchemy.org/en/13/core/connections.html?highlight=schema_translate_map#schema-translating) feature.   You cannot modify the ".schema" attribute of a Table object dynamically, this is not supported.

**Comment by heukirne** [comment]
Thank you so much, @zzzeek!
It works using schema translate map.

**Comment by zzzeek** [comment]
graet im glad that works.
