### ISSUE TITLE
quoting not applied for SQLite get_view_definition

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5456]
```
from sqlalchemy import create_engine, inspect


e = create_engine("sqlite://", echo=True)

with e.connect() as conn:
    conn.execute("create table foo (id integer)")
    conn.execute('create view "My \' View" as select id from foo')


    insp = inspect(conn)

    def_ = insp.get_view_definition("My ' View")

    assert def_ is not None
```

**Comment by zzzeek** [comment]
this should include a suite test that tests all table/ view / etc reflect methods for the following two names:
```

    insp.get_thing("my ' object")
    insp.get_thing('my " object')


```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**test single and double quote inspection scenarios** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2088

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**test single and double quote inspection scenarios** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2089
