### ISSUE TITLE
How to Insert to MsSql Table with primary key is not an identity column - Set Identity_insert to OFF error.

### ISSUE THREAD

**Issue by xhuyvn** [sqlalchemy/sqlalchemy#5464]
Hi, 

I'm using sqlalchemy 1.3 to insert a table on SQL Server 2016. The table has a primary key like this: **PKID int Not null.**
The insert script: _connection.execute(table.insert(),listToWrite)_ => it is give an errror : SQL can not set  Identity_insert to OFF.
But I use _dataframe.to_sql(...)_ for insert => it is fine.

I found the information: [sqlalchemy doc](https://docs.sqlalchemy.org/en/13/dialects/mssql.html#auto-increment-behavior-identity-columns): _**the first integer primary key column in a Table will be considered to be the identity column**_.
I updated column to **PKID int Identity(1,1)** and run _connection.execute(table.insert(),listToWrite)_ again, it fine.
The value inserted into PKID column is correct, it keeps the value of _listToWrite_ , not incremental value.

My question is: How do I insert to the table without setting the primary key to an Identity column using sqlalchemy core.

**Have a nice day!**

**Comment by CaselIT** [comment]
I think you should specify [`autoincrement=False`](https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=autoincrement#sqlalchemy.schema.Column.params.autoincrement) when defining a table. Otherwise sqlalchemy will assume that the primary key as an auto increment on it

```py
t = sa.Table('my_table', meta, sa.Column('id', sa.Integer(), autoincrement=False, primary_key=True), ...)
```

**Comment by zzzeek** [comment]
reopen if you need more help.
