### ISSUE TITLE
implement generic Double, DOUBLE types

### ISSUE THREAD

**Issue by Robert-sktai** [sqlalchemy/sqlalchemy#5465]
**Describe the bug**
The precision of a Float type is not utilized when [compiling data type](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/compiler.py#L4058). 

**Expected behavior**
In Hive, Float is a 4-byte single-precision floating-point and Double is an 8-byte double-precision floating-point. It means that the compiler should generate a "DOUBLE" type if the precision is between 24 and 53. Sadly, Hive does not have a Real type and the maximum precision of a Decimal type is 38. Thus, my conclusion is that we should also rely on a Double type.

**To Reproduce**
```py
Float(precision=53)
```

**Additional context**
I guess there are two approaches.
1) It is a quick workaround before providing a long-term solution.
```py
class GenericTypeCompiler(TypeCompiler):
    def visit_FLOAT(self, type_, **kw):
        if type_.precision > 23:
            return "DOUBLE"
        else:
            return "FLOAT"
```
2) Provide a specialized implementation of a dialect for Hive.

**Have a nice day!**

**Comment by CaselIT** [comment]
I think this should be something that the pyhive dialect should support. So the option 2 would be the best one.
The default compiler is just that, default :)

**Comment by Robert-sktai** [comment]
@CaselIT Thanks for your kind reply. I would like to contribute the second one. By the way, do you think the first option is not feasible? I guess the most of databases support Double type and we can determine between Float and Double on a value of the either precision. I am looking forward to hearing your opinion on my suggestion! Thanks.

**Comment by zzzeek** [comment]
if you need that precision you should ideally use the sqlalchemy.DOUBLE() type directly.    if [pyhive](https://github.com/dropbox/PyHive#sqlalchemy) wants to make a change, they would override "visit_Float()" to break out into either visit_FLOAT or visit_DOUBLE.  the uppercase methods should always produce that type.

**Comment by Robert-sktai** [comment]
@zzzeek Thanks for your quick answer. It seems that Double type does not exist in SQLalchemy. Do you mind if I add Double type? If you agree this approach, I would like to introduce the type(i.e. Double class) and relevant code such as visit_DOUBLE. May I do the code contribution for this feature?

**Comment by zzzeek** [comment]
we have no uppercase DOUBLE apparently.  it needs to be an uppercase type:

```
class DOUBLE(Float):

    """The SQL DOUBLE type."""

    __visit_name__ = "DOUBLE"

```

in addition all the following dialects would need appropriate updates so that their own DOUBLE types include this type in their superclasses:

sqlite
mysql

**Comment by zzzeek** [comment]
becuase all the following dialects have either DOUBLE or DOUBLE_PRECISION, we can also add Double() that would link to DOUBLE or DOUBLE_PRECISION as appropriate for:   mysql, sqlite, oracle, postgresql, firebird

class Double(Float):
   # ...


class DOUBLE(Double):
   # ...

then add appropriate entries for Double -> DOUBLE_PRECISION etc. in the dialects

need tests added to lib/sqlalchemy/dialects/testing/suite/test_types.py -> NumericTest

**Comment by Robert-sktai** [comment]
@zzzeek Thanks for your kind guidance! I am sure this information should be very helpful!

**Comment by sqla-tester** [comment]
**zeeeeeb** has proposed a fix for this issue in the **main** branch:

**Implement generic Double and related fixed types** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3585
