### ISSUE TITLE
Download documentation

### ISSUE THREAD

**Issue by eirnym** [sqlalchemy/sqlalchemy#5466]
**Is your feature request related to a problem? Please describe.**
I'm unable to use SQLAlchemy documentation offline, e.g having no or very limited internet connection. Not every environment provides free or good connection. 

**Describe the solution you'd like**
Please, add an offline documentation for personal use as many others did.

**Describe alternatives you've considered**
Downloading web pages is not an option, even "save as pdf" like macOS have

Thank you from a mountain

**Comment by zzzeek** [comment]
hi -

download any SQLAlchemy release from https://pypi.org/project/SQLAlchemy/#history , untar the file and the HTML documenation can be locally browsed from the doc/ directory.

**Comment by eirnym** [comment]
Thank you for a suggestion. I'm able read python code, after I install a package. But there's no examples, tutorials and other explanations I see on a web site. 

I don't see there a separate documentation package with HTML files similar to what I see on an official website. And preferably I want to be able to download a zip containing only documentation from the site itself. 

An expectation, that a random user have deep knowledge of Sphynx, is wrong as newbies don't have such knowledge and they are users for the documentation.

Also users who what to download a documentation has not much time for building it from the source. 

Btw, other big projects like Flask, Django and other hosted on "readthedocs" provide a separate archive with HTML and a PDF in some cases.

**Comment by zzzeek** [comment]
> Thank you for a suggestion. I'm able read python code, after I install a package. But there's no examples, tutorials and other explanations I see on a web site.

Don't "install" the package, go to your web browser at https://pypi.org/project/SQLAlchemy/#files then click on https://files.pythonhosted.org/packages/02/80/c83986fceeed04f7d42e3fd8a67e94e87b56afb223ee653e8a4a8986361e/SQLAlchemy-1.3.18.tar.gz .

then unzip or untar the file.     The HTML documentation is in doc/ starting at doc/index.html

> 
> I don't see there a separate documentation package with HTML files similar to what I see on an official website. And preferably I want to be able to download a zip containing only documentation from the site itself.

not a bad idea but this is not available right now - the docs are in the .tar.gz file for now.

> 
> An expectation, that a random user have deep knowledge of Sphynx, is wrong as newbies don't have such knowledge and they are users for the documentation.
> 
> Also users who what to download a documentation has not much time for building it from the source.


there's no need to use sphinx, the docs are built in the source distribution.

> 
> Btw, other big projects like Flask, Django and other hosted on "readthedocs" provide a separate archive with HTML and a PDF in some cases.

readthedocs was subject to frequent outages where SQLAlchemy's docs could not be built and PDF generation never worked on readthedocs.    PDF generation in Sphinx is very poor and while you can with much effort get a PDF file from our docs, it's largely unreadable.    the "downloads" might be a newer readtheocs feature that have to be added here.   can't do PDF though.

**Comment by eirnym** [comment]
Thanks for a detailed explanation and assurance that I don't need to run Sphynx to obtain a documentation! My life become more easier! 

Still looks like an undocumented magic, though. 

A download button on a web site is a new functionality I want to achieve with this ticket. It's good to know that it's needed to add just a link on a website. I'm fine with any kind of archives

**Comment by zzzeek** [comment]
please navigate to:

https://docs.sqlalchemy.org/

which should as always redirect you to:

https://docs.sqlalchemy.org/en/13/

on that page in the upper left of the main page and all content pages is a link "Download as ZIP file".   you must ensure you clear your browser cache to fully refresh the page as it is a static page.    the zip file containing the documentation in local file format is there.

**Comment by CaselIT** [comment]
@zzzeek  remember to publish the zzzeeksphinx https://github.com/sqlalchemy/sqlalchemy/issues/5450

Maybe we could create a github action that publishes it if the version changes?

**Comment by zzzeek** [comment]
I didnt publish zs because the change I made there is not required for building the documentation.  that's a change that's specific to the SQLAlchemy website.

**Comment by CaselIT** [comment]
ok!

**Comment by zzzeek** [comment]
but yes getting zs into some automated thing might be nice anyway.   it would likely work with tagging?

**Comment by CaselIT** [comment]
I believe we could also rig something to make it publish each time the version changesz but tags you surely be easier :)

**Comment by zzzeek** [comment]
I'd have to rethink my workflow for changing that numnber.  i usually bump it first, then add changes.

**Comment by CaselIT** [comment]
If you are ok with tag we can use them. It would also be easier

**Comment by CaselIT** [comment]
See https://github.com/sqlalchemyorg/zzzeeksphinx/pull/2
