### ISSUE TITLE
mssql dialect improperly quotes object (table/column) names containing ']'

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5467]
**Describe the bug**
The mssql dialect improperly quotes object (e.g., table/column) names containing ']' characters.

**Expected behavior**
The dialect should escape ']' characters as ']]' like the T-SQL function `QUOTENAMES` does.

**To Reproduce**

```py
meta = sa.MetaData()
table_name = "colo[u]r"
tbl = sa.Table(table_name, meta, sa.Column("id", sa.Integer))
meta.create_all(engine)
```

**Error**

```
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'r'. (102) (SQLExecDirectW)")
[SQL: 
CREATE TABLE [colo[u]r] (
	id INTEGER NULL
)

]
```

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix mssql dialect escaping object names containing ']'** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2097

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix mssql dialect escaping object names containing ']'** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2098
