### ISSUE TITLE
having a custom DDL at a table ORM configuration

### ISSUE THREAD

**Issue by MosheVai** [sqlalchemy/sqlalchemy#5471]
I have the following table:
```python
    class Asset2020(Base):
        __tablename__ = 'assets_2020'
        id = Column(Integer)
        asset_symbol = Column(String)
        price_date = Column(Date)
```
when I use `.create_all` to create the table I want to have a completely custom DDL script.
I didnt find how to do this in the documentation, I would imagine it will be in the `__table_args__` argument.

---

how to do something similar to this:

```python
    class Asset2020(Base):
          __table_args__ = {
        'custom_ddl': """CREATE TABLE assets_2020 PARTITION OF assets
    FOR VALUES FROM ('2020-01-01') TO ('2020-12-31');"""
    }
```

**Comment by zzzeek** [comment]
hi -

please see the chapter on [custom DDL](https://docs.sqlalchemy.org/en/13/core/ddl.html#custom-ddl)

**Comment by MosheVai** [comment]
@zzzeek seems like its solves it.

however How do i geruntee that `assets` is created before `assets_2020` so DDL wouldn't collapse.
```python
from sqlalchemy import event

event.listen(
    Asset2020.__table__,
    "after_create",
    DDL("""ALTER TABLE assets ATTACH PARTITION assets_2020
VALUES FROM ('2020-01-01') TO ('2020-12-31');;""")
)
```

**Comment by zzzeek** [comment]
that's the "after create" event so it runs after the Table is created.

**Comment by MosheVai** [comment]
@zzzeek It runs after `assets_2020` is created, However I dont know How to guarantee it running after `assets`.

`assets_2020` is a partition table of `assets`.

**Comment by zzzeek** [comment]
oh OK you want to make assets_2020 dependent on assets, hm you emit plain CREATE TABLE for both first then a second ALTER directive?  this is Postgresql, isnt there a way to send the "PARTITION" stuff along with the CREATE TABLE directly?  this is also supported: https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#postgresql-table-options  inherits, partition by, etc.

but if you want to maek "assets_2020" directly dependent on "assets" you can do that too there is a method add_is_dependent_on: https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=table#sqlalchemy.schema.Table.add_is_dependent_on

so you would say Asset2020.__table__.add_is_dependent_on(Asset.__table__)

**Comment by MosheVai** [comment]
Thanks for the help, Did not Know about this and it seems like a better approach. 
I used a `AssetMixin` and then both `Asset` and `Asset2020` inherited from it. 

Is it possible to have an example or a "page" in the cook book, about what's the best way to create postgres table [partitions ]
(https://www.postgresql.org/docs/12/ddl-partitioning.html)?

**Comment by zzzeek** [comment]
I think there's an issue to add more like first class support of this.   right now we just give basic support of the options needed but folks have to construct it themselves.  

a cookbook for now can be on the wiki.  here is a much older recipe back when PG just had INHERITS: https://github.com/sqlalchemy/sqlalchemy/wiki/PostgreSQLInheritance  I believe "partitions" is like an automated specialization of INHERITS.

**Comment by MosheVai** [comment]
@zzzeek what's the issue? I would like to help develop this but I don't know where to start?

**Comment by zzzeek** [comment]
it looks like we have a reflection issue for the INHERITS keyword at #1803.  this is a very old issue.  overall the relationship between "INHERITS" and "PARTITION" in postgresql needs to be understood and then the most appropriate way of devising this for Table would need to be devised.     the question of how Column objects should be represented in Table, when they inherit from the parent table so arent part of CREATE TABLE, would have to be figured out.   I have some different thoughts on #1803 where I keep changing my mind so I dont know that it's very clear how Table would represent this, such that it works for all of DDL (should not emit constraints and columns that are inherited) , reflection (needs to detect which columns and constraints are inherited) and SQL expressions / ORM mappings (all columns have to be locally present on a Table).

**Comment by zzzeek** [comment]
inherits / partitions is kind of an open thing where it's not clear what a higher degree of support would look like, and we have a lot of other schema things in the queue right now so it would be challenging to give this more attention right now.   For now we have some more low level workarounds so that users can use these features.
