### ISSUE TITLE
Issue on query generation with Hive

### ISSUE THREAD

**Issue by OpenDataAlex** [sqlalchemy/sqlalchemy#5472]
I'm attempting to build a GraphQL API with Hive as part of the backend.  I'm leveraging graphene-sqlalchemy, which uses sqlalchemy for the query generation.  I originally posted this on their Issue board and it was recommended to post this over here. Following the documentation I created the following schema:

`class Manufacturer(SQLAlchemyObjectType):
class Meta:
model = ManufacturerModel
interfaces = (relay.Node,)

class Query(ObjectType):
node = relay.Node.Field()
all_manufacturers = SQLAlchemyConnectionField(Manufacturer.connection)`

Which leverages the following SQLAlchemy model:

`class Manufacturer(Base):

tablename = 'manufacturer_hub'

manufacturer_hub_pk = Column(String, primary_key=True)
manufacturer_name = Column(String)`

I'm able to connect to the Hive cluster and a query attempts to run, but it fails due to the sort that is provided:

SELECT manufacturer_hub.manufacturer_hub_pk AS manufacturer_hub_manufacturer_hub_pk, manufacturer_hub.manufacturer_name AS manufacturer_hub_manufacturer_name FROM manufacturer_hub ORDER BY manufacturer_hub.manufacturer_hub_pk ASC

If aliases are being provided for columns, Hive is expecting them to be used in the ORDER BY. Running the following corrected query in Hive works:

SELECT manufacturer_hub.manufacturer_hub_pk AS manufacturer_hub_manufacturer_hub_pk, manufacturer_hub.manufacturer_name AS manufacturer_hub_manufacturer_name FROM manufacturer_hub ORDER BY manufacturer_hub_manufacturer_hub_pk ASC

**Comment by zzzeek** [comment]
So this is in fact a problem on Hive's end to fix, and below is a patch to the SQLite dialect that illustrates the technique they should use.   if you can link this to the place that you posted for them, this would be very helpful.

In the immediate term you can order by any textual string directly using literal_column().

given a mapping:

```
class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)

```


literal_column looks like:

```
from sqlalchemy import literal_column
s.query(A).order_by(literal_column("a_data")).all()
``


however this is very brittle based on the names of your columns and how SQLAlchemy chooses to label the column which can be more unusual with more complicated queries.

Hive's dialect should meet this requirement by overriding the order_by system in their SQLAlchemy statement compiler, using an approach like the following demo that applies to the SQLite compiler:

```diff
diff --git a/lib/sqlalchemy/dialects/sqlite/base.py b/lib/sqlalchemy/dialects/sqlite/base.py
index 44eb2e1d5..b876b3a84 100644
--- a/lib/sqlalchemy/dialects/sqlite/base.py
+++ b/lib/sqlalchemy/dialects/sqlite/base.py
@@ -617,6 +617,8 @@ from ...types import TIMESTAMP  # noqa
 from ...types import VARCHAR  # noqa
 
 
+from sqlalchemy.sql.compiler import _CompileLabel
+
 class _SQliteJson(JSON):
     def result_processor(self, dialect, coltype):
         default_processor = super(_SQliteJson, self).result_processor(
@@ -987,6 +989,30 @@ class SQLiteCompiler(compiler.SQLCompiler):
         },
     )
 
+    def order_by_clause(self, select, **kw):
+        """allow dialects to customize how ORDER BY is rendered."""
+
+        order_by = select._order_by_clause._compiler_dispatch(
+            self, gen_order_by_labels=True, **kw
+        )
+        if order_by:
+            return " ORDER BY " + order_by
+        else:
+            return ""
+
+    def visit_column(self, column, **kw):
+        gen_labels = kw.pop("gen_order_by_labels", False)
+        if gen_labels:
+
+            if self.stack:
+                selectable = self.stack[-1]["selectable"]
+
+                c1 = selectable.corresponding_column(column)
+                if c1 is not None:
+                    return self.process(_CompileLabel(c1, c1.name), **kw)
+
+        return super(SQLiteCompiler, self).visit_column(column, **kw)
+
     def visit_now_func(self, fn, **kw):
         return "CURRENT_TIMESTAMP"
 

```

using the above patch with the above mapping, queries like the following:

```

s.query(A).order_by(A.data).all()


s.execute(select([A]).order_by(A.data))
```

generate as:

```
SELECT a.id AS a_id, a.data AS a_data  FROM a ORDER BY a_data
SELECT a.id, a.data  FROM a ORDER BY data

```

noting that SQLAlchemy's label style is based on a flag that isn't on by default for Core SQL statements.

a different approach is needed for 1.4, next comment will have that.

**Comment by zzzeek** [comment]
Here's a patch that works for 1.4:
```

diff --git a/lib/sqlalchemy/dialects/sqlite/base.py b/lib/sqlalchemy/dialects/sqlite/base.py
index 3a8ffa23d..3564dbd97 100644
--- a/lib/sqlalchemy/dialects/sqlite/base.py
+++ b/lib/sqlalchemy/dialects/sqlite/base.py
@@ -616,6 +616,8 @@ from ...types import TIMESTAMP  # noqa
 from ...types import VARCHAR  # noqa
 
 
+from sqlalchemy.sql.compiler import _CompileLabel
+
 class _SQliteJson(JSON):
     def result_processor(self, dialect, coltype):
         default_processor = super(_SQliteJson, self).result_processor(
@@ -986,6 +988,33 @@ class SQLiteCompiler(compiler.SQLCompiler):
         },
     )
 
+    def order_by_clause(self, select, **kw):
+        """allow dialects to customize how ORDER BY is rendered."""
+
+        order_by = select._order_by_clause._compiler_dispatch(
+            self, gen_order_by_labels=True, **kw
+        )
+        if order_by:
+            return " ORDER BY " + order_by
+        else:
+            return ""
+
+    def visit_column(self, column, **kw):
+        gen_labels = kw.pop("gen_order_by_labels", False)
+        if gen_labels:
+
+            if self.stack:
+                selectable = self.stack[-1]["selectable"]
+
+                collection = selectable.selected_columns
+                lookup = {collection[key]: key for key in collection.keys()}
+                key = lookup.get(column, None)
+                if key:
+                    cl = _CompileLabel(column, key)
+                    return self.process(cl, render_label_as_label=cl, **kw)
+
+        return super(SQLiteCompiler, self).visit_column(column, **kw)
+
     def visit_now_func(self, fn, **kw):
         return "CURRENT_TIMESTAMP"
 

```

**Comment by zzzeek** [comment]
so overall, these patches are not that simple and require a lot of guessing to do the right thing.    If the Hive dialect wants to take these on there may be a lot of things that need maintainance over time.

it would be **vastly** preferable if the Hive backend itself could be enhanced to accommodate for this very simple standard SQL composition and make the necessary optimizations based on its own internal parse tree of the statement.

**Comment by OpenDataAlex** [comment]
@zzzeek thank you for the detailed response.  I'll link the other libraries I'm using to this issue so they can follow along/see what's going on as well.

**Comment by OpenDataAlex** [comment]
Doing more digging within the Hive project, apparently the lack of alias in ORDER BY is a known issue.  [Apache Hive JIRA](https://issues.apache.org/jira/browse/HIVE-15966)

**Comment by zzzeek** [comment]
OK, so nothing I can do on this end, if the hive dialect developers need changes to accommodate the above patches they can open an issue or send a mailing list note.
