### ISSUE TITLE
Why ColumnAssociationProxyInstance gets injected onto the class when getting class attributes

### ISSUE THREAD

**Issue by gjeusel** [sqlalchemy/sqlalchemy#5473]
Hello Mike !

### Question

I'm struggling with a behaviour of the association proxy, since the introductions of `ObjectAssociationProxyInstance` and `ColumnAssociationProxyInstance`.

Why the injection of a class attribute at the moment you get the attribute of an association proxy from the class ?

### Reproducible script

Here is a simple script to highlight my "tricky" question:

```python
import sqlalchemy as sa
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import backref, relationship

engine = sa.create_engine("sqlite:///:memory:")
Base = declarative_base()
Base.metadata.bind = engine
Session = sa.orm.sessionmaker(autocommit=False, autoflush=False, bind=engine)
session = sa.orm.scoped_session(Session)


class Person(Base):
    __tablename__ = "person"
    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.Unicode, unique=True)


class Book(Base):
    __tablename__ = "book"
    id = sa.Column(sa.Integer, primary_key=True)
    owner_id = sa.Column(sa.Integer, sa.ForeignKey("person.id"))
    owner = relationship("Person", backref=backref("books", lazy="dynamic"))
    owner_name = association_proxy("owner", "name")


Base.metadata.create_all()

first_dir = dir(Book)

# Getting the attr on the Class itself:
print("Type of Book.owner_name: ", type(Book.owner_name))

second_dir = dir(Book)

injected_attrs = set(second_dir) - set(first_dir)
print(f"Injected attributes are: {injected_attrs}")

attrname = tuple(injected_attrs)[0]
assert id(Book.owner_name) == id(getattr(Book, attrname))
```

Example output:

```sh
Type of Book.owner_name:  <class 'sqlalchemy.ext.associationproxy.ColumnAssociationProxyInstance'>
Injected attributes are: {'_AssociationProxy_owner_4375252160_inst'}
```

### Why does it matter ?

At the moment you inspect classes and want to find associations proxies, it's a bit struggling to exclude the injected ones.

---
### Versions:

 - OS: Macos 10.14.6
 - Python: Python 3.6.10 :: Anaconda, Inc.
 - SQLAlchemy: 1.3.18
 - Database: sqlite 3.30.1
 - DBAPI: psycopg2==2.8.5

**Comment by CaselIT** [comment]
I'm not sure if there are alternative implementation possible here, since I'm not familiar with association_proxy internals.

Regarding you use case, I believe you can use the mapper [`all_orm_descriptors`](https://docs.sqlalchemy.org/en/13/orm/mapping_api.html?highlight=all_orm_descriptors#sqlalchemy.orm.Mapper.all_orm_descriptors) to obtain all the properties and then filter only for the association proxy ones

**Comment by gjeusel** [comment]
Thx for the recommendation !
Indeed it is much better to loop over your mapper definition

**Comment by zzzeek** [comment]
the association proxy refactor that introduced these concepts took into account that having a Python descriptor on the class alone is not enough, that the class that actually gets invoked when the proxy is invoked can vary.  i..e. there can be many classes with different mappings and behaviors sharing the same descriptor.   users had bugs where depending on which class was hit first, the object would behave differently.    so now AP stores a separate object per class that has all the information it needs to produce the correct behaviors for that class.

as mentioned above, dir() is going to give you pretty raw results so using inspect(cls).all_orm_descriptors is the way to go for looking at mapped classes.

feel free to reopen if more issues.
