### ISSUE TITLE
Cleanup - UUID module is always available

### ISSUE THREAD

**Issue by ziima** [sqlalchemy/sqlalchemy#5482]
**Is your feature request related to a problem? Please describe.**
I noticed conditions handling a case of missing `uuid` module in python. Since `uuid` module is available since 2.5 and thus it's available in all supported python versions, related code may be removed.

**Describe the solution you'd like**
Import `UUID` unconditionally and remove related code.

**Comment by CaselIT** [comment]
Thanks for reporting this. Feel free to create a pull request if you want to implement the cleanup

**Comment by sqla-tester** [comment]
**Vlastimil Zíma** has proposed a fix for this issue in the **master** branch:

**Clean python UUID imports** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2115
