### ISSUE TITLE
'Using Passive Deletes' section missing in documentation

### ISSUE THREAD

**Issue by isolovey** [sqlalchemy/sqlalchemy#5484]
**Describe the bug**
The 'Using Passive Deletes' section of `doc/build/orm/collections.rst` [refers to itself](https://docs.sqlalchemy.org/en/14/orm/collections.html#passive-deletes). There's no content.

**Expected behavior**
Either having the section present, as in [v1.2](https://docs.sqlalchemy.org/en/12/orm/collections.html#passive-deletes), or a reference to elsewhere in the documentation.

**Comment by zzzeek** [comment]
so the commit was 9e1ee412b8650761af6df993e11990 yesterday and at line https://github.com/sqlalchemy/sqlalchemy/commit/9e1ee412b8650761af6df993e119906682604728#diff-67a032fee35812b72a48134e8a5a9344R143 that was supposed to get removed, not sure if a text editor undo put it back or something

**Comment by zzzeek** [comment]
thanks

the docs in question are now at https://docs.sqlalchemy.org/en/14/orm/cascades.html#using-foreign-key-on-delete-cascade-with-orm-relationships
