### ISSUE TITLE
Oracle Error ORA-01008 : Not all variables bound

### ISSUE THREAD

**Issue by CrabbyPete** [sqlalchemy/sqlalchemy#5485]
I have a schema which has long names

lass Document(Base):
    __tablename__ = 'document'

    id                                          = Column(String(100), primary_key=True, autoincrement=False)
    oid                                         = Column(String(100), nullable=True)
    displayname                                 = Column(String(500), nullable=True)
    category                                    = Column(String(100), nullable=True)
    subcategory                                 = Column(String(100), nullable=True)
    effectivedate                               = Column(Date, nullable=True)
    expirationdate                              = Column(Date, nullable=True)
    creationdate                                = Column(Date, nullable=True)
    filename                                    = Column(String(500), nullable=True)
    filesize                                    = Column(Numeric, nullable=True)
    keywords                                    = Column(String(1000), nullable=True)
    documentesignature_esignaturestatus         = Column(String(100), nullable=True)
    documentesignature_esignaturerequesteddate  = Column(Date, nullable=True)
    documentesignature_esignaturerequestername  = Column(String(100), nullable=True)
    documentesignature_esignaturesigneddate     = Column(Date, nullable=True)
    documentesignature_esignaturesignedbyname   = Column(String(100), nullable=True)

If I create a record with this like record = Document(**data) and save it I get the Oracle Error ORA-01800 
If I remove the last three columns I don't get the error. 

If I run a sql command it works from sqlalchemy it work

I am using cx_Oracle 8.0

**Comment by gordthompson** [comment]
[This page](http://www.dba-oracle.com/t_error_code_list.htm) says that ORA-01800 is ...

> ORA-01800: a literal in the date format was too large to process

... and you say that "If I remove the last three columns I don't get the error." and one of those three columns is a `Date`.

Coincidence? Perhaps.

**Comment by zzzeek** [comment]
we need to see what **data is, in its exact format.   one way to make this apparent would be to paste the complete stack trace and all error information which will illustrate the SQL statement and parameters being passed.

also if you change the length of the column names what result do you get.

finally, Oracle version would be helpful.

**Comment by zzzeek** [comment]
we would need to see the data and full info in order to have insight on what is happening, reopen if you can provide this.
