### ISSUE TITLE
Documentation typo in comment

### ISSUE THREAD

**Issue by inspire12** [sqlalchemy/sqlalchemy#5486]
Hi,
I found small typo on the following comments, in lib/sqlalchemy/sql/schema.py 1068 line

        :param type\_: The column's type, indicated using an instance which
should be
        :param type: The column's type, indicated using an instance which

Can i pr this project?

thanks!

**Comment by CaselIT** [comment]
Actually is seems correct
https://github.com/sqlalchemy/sqlalchemy/blob/3d5a64ac09b55514da6fd30f0f085348c2d10496/lib/sqlalchemy/sql/schema.py#L1336

Maybe the typo is somewhere else in the documentation?

**Comment by CaselIT** [comment]
> Can i pr this project?

Of course!

**Comment by jvanasco** [comment]
Are we sure this is a typo and not a character escape for Sphinx (or something else)?

This is rendered without the slash in the docs: https://docs.sqlalchemy.org/en/13/core/metadata.html

**Comment by zzzeek** [comment]
the backslash is a sphinx escape.    param shows up correctly:

https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=schema%20column#sqlalchemy.schema.Column.params.type_

i've linked to the relevant RST docs on the PR which unfortunately should be closed.
