### ISSUE TITLE
CTEs does not work with UPDATE statements using`engine.execute` (in Postgres)

### ISSUE THREAD

**Issue by Shadowsong27** [sqlalchemy/sqlalchemy#5492]
**Describe the bug**
I first notice this from the python archived `records` library, which uses sqlalchemy under the hood. We have a query that uses two CTEs and an update statement at the end, what we have noticed is the query is not working if you executed in code, but works if copied the query and executed in DataGrip (or any SQL client i presume).

**Expected behavior**
Based on the reproduction steps below, record should be `(1, 3)`, but it is still `(1, 2)`, with no error given.

**To Reproduce**

Setup your table:

```
CREATE TABLE public.pg_test (
    id int,
    name varchar
);

INSERT INTO public.pg_test VALUES (1, 2);
```

Setup engine connection and run the following:
Of course this is a very naive example, where the update statement has nothing to do with the CTE.
```py
query = """
        WITH to_update AS (
            SELECT * FROM playground.pg_test
        )
        UPDATE playground.pg_test
        SET name = 3"""
hook.sqla_engine.execute(
        query
    )
```

where the hook.sqla_engine is a Postgres engine.

However if I removed the CTE, left with only the UPDATE statement, it works as expected.

Tested with SELECT queries, they work fine. Not sure about INSERT (vaguely remember it works) AND DELETE

```

**Versions.**
 - OS: Mac OS Catalina
 - Python: 3.7
 - SQLAlchemy: 1.3.0 and above
 - Database: Postgres

**Comment by zzzeek** [comment]
hi -

if you are passing a string to engine.execute and it "fails", this indicates a problem with the string or the DB driver.  however, please provide what "Fails" means, is there an error message?  stack trace?   "fails" is not meaningful by itself, thanks.

**Comment by CaselIT** [comment]
I've just tried and the example query and I get no error on sqlalchemy

**Comment by Shadowsong27** [comment]
Hi I have mentioned it in the `Expected Behavior` section but probably it's not clear enough. By 'fail' I mean the expected update operation __did not take effect (data record did not change)__ in the table, and with __NO ERROR MESSAGE__ given.


And I also want to reiterate that the exact string, if executed in SQL client, it works. The next good test to do is probably to test the exact string using psycopg2 to eliminate the possibility of some SQL client syntax sugar, but it's pretty unlikely.

**Comment by CaselIT** [comment]
I guess you need to commit explicitly then..

**Comment by Shadowsong27** [comment]
> I guess you need to commit explicitly then..

So if I understand [this part of the document] (https://docs.sqlalchemy.org/en/13/core/connections.html#library-level-e-g-emulated-autocommit) correctly, auto-commit is enabled for non-transactional block query, so I doubt its related to the commit.

And after re-write the query in subqueries, it works normally, so I kinda still suspect it's CTE parsing issue though.

**Comment by CaselIT** [comment]
Sqlalchemy does not parse a the text literal, so that cannot be problem.
Pass `echo=True` to see the sql that gets sent to the server.

**Comment by Shadowsong27** [comment]
Did a few more testing (maybe I am testing it wrongly but yeah just showing the code I tested below), 

1. using `Engine.begin()` with context manager works as intended

```py
    with hook.sqla_engine.begin() as trans:
        trans.execute("""
            WITH to_update AS (
                SELECT * FROM public.pg_test
            )
            UPDATE public.pg_test
            SET name = 31
            """
        )
```

2. using `Engine.connect()` it does not work, with no error message, echoed SQL is the original SQL, this result matches my experience with `records` package since it uses Connection.execute() as well in source, not `Engine.execute`.
 

```py
    with hook.sqla_engine.connect() as conn:
        conn.execute(
            """
            WITH to_update AS (
                SELECT * FROM public.pg_test
            )
            UPDATE public.pg_test
            SET name = 2
            """
        )
```

**Comment by CaselIT** [comment]
Then it works as intended then:
- `begin()` commits at the end of the block if no exception is raised
- `connect()` does not, so an explicit `conn.commit()` is required.

Maybe the problem is that the documentation could be improved?

**Comment by Shadowsong27** [comment]
1. I did not really find `Connection.commit()` method around [here](https://docs.sqlalchemy.org/en/13/core/connections.html#sqlalchemy.engine.Connection.execute) unless i am looking into the wrong place 
2. Why then, does a normal update, a subquery works fine with the `connect()` approach, but not when query is written in CTE form?

Again thanks for the concept clarification, will probably switch to begin() anyway since its more explicit.

**Comment by zzzeek** [comment]
> Hi I have mentioned it in the `Expected Behavior` section but probably it's not clear enough. By 'fail' I mean the expected update operation **did not take effect (data record did not change)** in the table, and with **NO ERROR MESSAGE** given.

then this is the failure to commit.   the autocommit logic is detailed at https://docs.sqlalchemy.org/en/13/core/connections.html#library-level-e-g-emulated-autocommit , and as you'll note, this logic is entirely deprecated and going away, this issue being a perfect example of why.    I would advise migrating to connection-explicit patterns as will be the only way to go in 2.0:

```
  with engine.begin() as conn:
        conn.execute(text("< sql statement > "))

```

if we can confirm that was the issue, this can be closed.

**Comment by CaselIT** [comment]
Maybe we could more strongly word the fact that it is deprecated and advise the use of the `begin()` or `connect()` + explicit `commit()`?

**Comment by Shadowsong27** [comment]
> Maybe we could more strongly word the fact that it is deprecated and advise the use of the `begin()` or `connect()` + explicit `commit()`?

A warning message in console would be nice, it would be more noticeable than the docs IMO, comprehensiveness in docs sometimes may bury the important information unintentionally.

**Comment by CaselIT** [comment]
I think 1.4 will have one. (Not sure, it may be that it was there at some poi but was removed for perf reasons)

**Comment by CaselIT** [comment]
Regarding why the update succeeds while the cte does not, it is due to the way sqlalchemy detects if it should auto-commit or not.
https://github.com/sqlalchemy/sqlalchemy/blob/9a3fee2cb6b608eb5c0263cf5a7e9085f74f2e73/lib/sqlalchemy/engine/default.py#L34-L36

This regexp does not match `CTE ...` but does match `UPDATE ...`

**Comment by zzzeek** [comment]
#4846 addresses more verbiage around implicit application level autocommit being deprecated.

**Comment by zzzeek** [comment]
I think this can be closed.   autocommit is going away and this is [extensively](https://docs.sqlalchemy.org/en/14/core/connections.html#library-level-e-g-emulated-autocommit) [documented](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-20-autocommit) and also sends out deprecation warnings when "future" mode is enabled.
