### ISSUE TITLE
Add a way of specifying to the MySQL dialect that we will use MariaDb

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5496]
**Is your feature request related to a problem? Please describe.**
Currently the MySQL dialect is used by both MySQL and by MariaDB. The dialect does detect which database is connected to on first connection, but there may be cases that use the dialect without an actual connection.

**Describe the solution you'd like**
A way of specifying to the dialect that the underlying database is MariaDB. One option may be a kw argument, so that I may create it with:
```py
from sqlalchemy.dialects.mysql import dialect
mdb = dialect(is_mariadb=True)
```

An alternative may be to support `mariadb://` as an alias for `mysql://` that sets the `id_mariadb` flag, so that I can then use:
```py
from sqlalchemy import create_engine
mdb = create_engine('mariadb://').dialect
```

**Additional context**
This may be useful since there are starting to be cases where the sql of mysql and mariadb has some differences.

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use importlib_metadata; add namespace for mariadb** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2144

**Comment by CaselIT** [comment]
Thanks mike to moving taking this
