### ISSUE TITLE
evaluate why we are calling on_connect twice for first connection

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5497]
e.g. even back in 1.1:

```
      if _initialize:
            do_on_connect = dialect.on_connect()
            if do_on_connect:
                def on_connect(dbapi_connection, connection_record):
                    conn = getattr(
                        dbapi_connection, '_sqla_unwrap', dbapi_connection)
                    if conn is None:
                        return
                    do_on_connect(conn)

                event.listen(pool, 'first_connect', on_connect)
                event.listen(pool, 'connect', on_connect)

```

why?  I have the vaguest recollection of some DBAPI that needed this for some reason but this is just wrong.   Tests seem to pass without first_connect in there, but i need to do a full run.   goal should be to put a comment in there because I spent an hour confused about this.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't link on_connect to first_connect event handler** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2137

**Comment by zzzeek** [comment]
OK the reason is the isolation level setting which typically is only set in on_connect(), then we read it back in initialize().  so we will just do an extra call to set_isolation_level in initialize so that defaultdialect guarantees it was called.
