### ISSUE TITLE
Add support for data_type on sequence in all dialects

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5498]
**Is your feature request related to a problem? Please describe.**
Issue https://github.com/sqlalchemy/sqlalchemy/issues/4235 has added a data_type in the Sequence, but it is currently only used
by the mssql dialect.
**Describe the solution you'd like**
All dialects that support it have support for the sequence data type, eg postgres

**Have a nice day!**

**Comment by zzzeek** [comment]
I assume Postgresql supports this, should this issue be tagged to postgresql?

**Comment by balukrishnans** [comment]
Yes, Postgres support smallint, integer and bigint type. By default it is bigint. And this issue opened for Postgresql

**Comment by CaselIT** [comment]
not sure if oracle also support this

**Comment by CaselIT** [comment]
> not sure if oracle also support this

No oracle does not support it https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/CREATE-SEQUENCE.html#GUID-E9C78A8C-615A-4757-B2A8-5E6EFB130571

**Comment by CaselIT** [comment]
Also maria db does not support it

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Support data types for CREATE SEQUENCE in PostgreSQL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2138
