### ISSUE TITLE
result.scalars() should return a different object, like ScalarResult

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5503]
as we want to support pep-484 / liskov substitution to the greatest degree possible, this would be an intermediary object where methods like all(), fetchall(), fetchmany() etc. return lists of Any rather than lists of Row.    it would proxy the Result object underneath and if you de-select scalar mode you go back to the Result.

**Comment by zzzeek** [comment]
sigh and MappingResult

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Break scalars() and mappings() into separate objects** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2141
