### ISSUE TITLE
create declarative_base.mapper function

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5508]
as described at https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#the-original-mapper-function-removed-replaced-with-a-declarative-compatibility-function

cc #5027 .

with dataclasses we will need to place new emphasis on these newer style of "classical" mappings.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Build out new declarative systems; deprecate mapper()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2202
