### ISSUE TITLE
Support reflection/inspection of identity columns

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5527]
After https://github.com/sqlalchemy/sqlalchemy/issues/5362 we can support reflecting identity columns

Older, postgres specific issue https://github.com/sqlalchemy/sqlalchemy/issues/5324

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add reflection for Identity columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2248
