### ISSUE TITLE
Make `AsyncConnection._sync_connection` async

### ISSUE THREAD

**Issue by fantix** [sqlalchemy/sqlalchemy#5530]
**Is your feature request related to a problem? Please describe.**

In the next major version of [GINO](https://python-gino.org) which will be built on SQLAlchemy 1.4, `AsyncConnection` is subclassed to be lazy (and together with many other contextual features, to be compatible with the current GINO version). It would be neat to put the lazy-connection initialization code in the overridden `AsyncConnection._sync_connection()` method to avoid a lot of code duplicates.

**Describe the solution you'd like**

As demonstrated in https://github.com/fantix/sqlalchemy/commit/async-sync-connection, making the `_sync_connection()` method sync would allow subclasses to blend in async logic to get the actual connection.

**Describe alternatives you've considered**

Otherwise, the subclasses would have to override and copy over all `AsyncConnection` methods to add async logic.

**Additional context**

https://github.com/python-gino/gino/blob/501840be96a875490fda39f43ed5139fdee56d5d/src/gino/engine.py#L154-L166

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there.

what im not understanding is `AsyncConnection` is already lazy initialized.   when you get one from AsyncEngine.connect(), it hasn't done anything yet.   the object needs to be `__await__`ed or `__aenter__`ed before it actually connects.   it then acquires the connection in an async way since it has to.  if you call any methods on it without doing these things, you get an error.       

based on your description it seems perhaps you would intend for the part where it actually calls `.connect()` to be extensible?   that is:

```
diff --git a/lib/sqlalchemy/ext/asyncio/engine.py b/lib/sqlalchemy/ext/asyncio/engine.py
index 2d9198d16..23bfcc6ff 100644
--- a/lib/sqlalchemy/ext/asyncio/engine.py
+++ b/lib/sqlalchemy/ext/asyncio/engine.py
@@ -76,9 +76,12 @@ class AsyncConnection(StartableContext):
         """
         if self.sync_connection:
             raise exc.InvalidRequestError("connection is already started")
-        self.sync_connection = await (greenlet_spawn(self.sync_engine.connect))
+        self.sync_connection = await self._get_connection_from_engine()
         return self
 
+    async def _get_connection_from_engine(self):
+        return await (greenlet_spawn(self.sync_engine.connect))
+
     def _sync_connection(self):
         if not self.sync_connection:
             self._raise_for_not_started()

```

the PR you sent appears to partially break the usage contract I intended by allowing methods like `connection.begin()` to be called before the connection has been awaited.   that seems like a different kind of connection to me.

**Comment by fantix** [comment]
Oh hi Mike, thank you very much for looking into this one in such a short time!

> `AsyncConnection` is already lazy initialized. when you get one from `AsyncEngine.connect()`, it hasn't done anything yet. the object needs to be `__await__`ed or `__aenter__`ed before it actually connects. it then acquires the connection in an async way since it has to. if you call any methods on it without doing these things, you get an error.

Yep, this explains perfectly how `AsyncConnection` works now and it makes a lot of sense to me.

> based on your description it seems perhaps you would intend for the part where it actually calls .connect() to be extensible? 

Not exactly, sorry for the confusion - I kinda thought this was a straightforward change and didn't want to take too much of your time here. But anyways, here's an in-depth explanation of [how GINO Engine/Connection works](https://python-gino.org/docs/en/1.0/explanation/engine.html#managing-connections). The TL;DR is this sample code (with PR #5531):

```python
class GinoConnection(AsyncConnection):
    def __init__(
        self,
        sync_engine: Engine,
        head: Optional[GinoConnection],
        connect_timeout: Optional[int],
        reuse: bool,
        lazy: bool,
    ):
        super().__init__(sync_engine)
        self._head = head
        self._connect_timeout = connect_timeout
        self._reuse = reuse
        self._lazy = lazy
        self._lock = None

    async def start(self):
        if not self._lazy:
            await self._sync_connection()
        return self

    async def _sync_connection(self):
        if self._head and self._reuse:
            return await self._head._sync_connection()
        if self._lock is None:
            self._lock = asyncio.Lock()
        async with self._lock:
            if not self.sync_connection:
                self.sync_connection = await greenlet_spawn(self.sync_engine.connect)
            return self.sync_connection

    async def soft_close(self):
        async with self._lock:
            conn, self.sync_connection = self.sync_connection, None
            if conn:
                await greenlet_spawn(conn.close)


class GinoEngine(AsyncEngine):
    def __init__(self, sync_engine: Engine):
        super().__init__(sync_engine)
        self._ctx = ContextVar("gino", default=None)

    def acquire(self, *, timeout=None, reuse=False, lazy=False, reusable=True):
        if reusable:
            head = self._ctx.get()
        else:
            reuse = False
            head = None
        rv = self._connection_cls(self.sync_engine, head, timeout, reusable and reuse, lazy)
        if reusable and (not head or not reuse):
            self._ctx.set(rv)
        return rv
```

Thanks to SQLAlchemy 1.4 this is insanely simpler and cleaner than it was before. Some outlines:

* `await GinoConnection(lazy=True)` (or `async with`) doesn't immediately borrow a connection from the pool
* Any concrete actions on the connection like `execute()` or `begin()` would make sure that a connection is checked out (done in `_sync_connection()`, so no second `await` is needed - to answer the question in PR #5531)
* `GinoConnection(head=..., reuse=True)` would allow multiple `GinoConnection`s share the same underlying "sync" connection.

I'm replying to your comments in the PR #5531 here too:

> I'm not saying this is a bad idea or anything it's just that I can see this placing itself as kind of an internal rigidness to how AsyncConnection works which makes me a little nervous based on past experience.

I totally understand your concern, that's also why I left quite some async hacks and duplicate SQLAlchemy code in earlier versions of GINO (I should have considered using greenlets, that's a really neat fix you did! :+1: ), so that the upstream SQLAlchemy could be kept clean untouched. Now as SQLAlchemy 1.4 is before beta and the asyncio support is considered alpha, I think it might be a good time to blend in community projects in a proper way.

For the proposed change itself, `_sync_connection()` seems to naturally be the "aspect" or "hook-in point" before any concrete database accesses like `await execute()` or `async with begin()`, etc., even though I know it is not designed to be that way (I would also agree not to specifically design a hook/extension for this because it can easily go down the wrong way in your former bad experiences over-designing for refactor-blockers). In contrast, most other methods in this class are async (`begin()` returns a `StartableContext` so half-async) - they have no complaints calling another async method. Having sync methods is okay, my experience is that unless it serves a specific sync purpose (like being used in `@property`s), such methods may eventually become async (like the async-virus). This is not always true and I don't have a great balancing approach for it, but the `_sync_connection()` feels to me that 1) we have a (community) use case now and 2) it's more consistent with the proposed change, for example:

```python
engine = create_async_engine(...)
conn = engine.connect()
tx = conn.begin()
# no await till now, so no actual database access,

# until:
async with tx:
    ....
```

(Sample here is only a breakdown to explain what happened behind the scene, users should see the sample at the bottom)

I understand that even though making this method async doesn't look like a big change, it actually changes the conceptual design of `AsyncConnection` to something like:

> `AsyncConnection` does not always have its `.sync_connection` ready even after being `await`ed or `__aenter__`ed, you have to run `await ._sync_connection()` to get the sync connection.

So the decision is still yours - I'm basically okay either way as the `AsyncConnection` is not very complex so it's easy to copy and maintain (or I could add another `async def _ensure_sync_connection()` in GINO to avoid copying).

Apologize for the long reply. Thank you very much for looking into this again!

---

p.s. my other thoughts on the short sample above, it's more intuitive if users use and think it this way:

```python
engine = await create_async_engine(...)  # actually creates the engine, make sure it's connectable (*not true now)
conn = await engine.connect()  # concretely establishes a connection
tx = await conn.begin()  # emit BEGIN to the database (*limited by the auto-commit/implicit-begin complications)
```

Community projects may override and behave differently, but "what you see is what you get" is always good, even though I know we're not quite there yet, especially with so many dialects/drivers to support.

**Comment by CaselIT** [comment]
Just wanted to mention that `create_engine` and its async counterpart do not actually make any connection to the db, so I'm -1 on having it async since it may mislead users.

**Comment by fantix** [comment]
> Just wanted to mention that create_engine and its async counterpart do not actually make any connection to the db, so I'm -1 on having it async since it may mislead users.

Oh sorry for the confusion - I didn't mean to propose changes to the `create_engine` API family, making `AsyncConnection._sync_connection()` async doesn't change user APIs at all.

> I'm not sure if it would be beneficial to have this change, since I think it may break a lot of use cases, where the engine is creates at model load, when the db may not actually yet be ready to accept connections

The final `await create_async_engine(...)` part is just one of my other thoughts, it would be another huge topic, and it actually makes more sense to keep them as they are now.

**Comment by zzzeek** [comment]
just to confirm, you aren't actually "blocked" right now because you can just re-implement those methods yourself, you're looking to have "lazy connection-post-start()" be an intrinsic feature of the AsyncConnection's architecture.

**Comment by fantix** [comment]
Right, I'm not blocked.

**Comment by zzzeek** [comment]
OK so I think we chatted on IRC about this and IIUC you've made peace with just doing your own proxy for now, so I don't have to figure this one out for now, is that right?   closing this for now.

**Comment by fantix** [comment]
Yes! Sorry didn't get time recently to revisit this one. Thank you!
