### ISSUE TITLE
AttributeError: 'property' object has no attribute 'property'

### ISSUE THREAD

**Issue by cuzox** [sqlalchemy/sqlalchemy#5532]
Say we have a base class with an instance method that tries to read a property's type at runtime:
```python
class CustomBase(object):
  def instance_method(self):
    class_ = inspect(self).mapper.class_
    class_property = class_.bravo.property
    print(type(class_property))

Base = declarative_base(cls=CustomBase)

class Alpha(Base):
  bravo = relationship('Bravo')
```

When running `Alpha().instance_method()`, I'm getting `AttributeError: 'property' object has no attribute 'property'`.
That is because the type of `class_.bravo` is actually `<class 'property'>`
When I do the same outside of the instance method:
```python
class_ = inspect(Alpha()).mapper.class_
class_property = class_.bravo.property
print(type(class_property))
```

I get the expected output: `RelationshipProperty`
Because the type of `class_.bravo` is `<class InstrumentedAttribute>`
Why is the type of the model field different when accessed from outside, than it is when accessed from an instance method? Shouldn't it be the same?

**Versions.**
 - OS: Alpine 3.8
 - Python: 3.7
 - SQLAlchemy: 1.3.16
 - Database: PostgreSQL 11
 - DBAPI: 2

**Comment by CaselIT** [comment]
I cannot reproduce using sqlalchemy 1.3.19

Complete example:
```py
from sqlalchemy import inspect, Column, Integer, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

class CustomBase(object):
    def instance_method(self):
        class_ = inspect(self).mapper.class_
        class_property = class_.bravo.property
        print(type(class_property))

Base = declarative_base(cls=CustomBase)

class Alpha(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)
    bravo = relationship("Bravo")

class Bravo(Base):
    __tablename__ = "bar"
    id = Column(Integer, primary_key=True)
    alphaId = Column(Integer, ForeignKey(Alpha.id))
```

Calling ` Alpha().instance_method()` prints `<class 'sqlalchemy.orm.relationships.RelationshipProperty'>`

Could you try upgrading sqlalchemy. If the problem persist could you provide a more complete example?

**Comment by zzzeek** [comment]
I have a feeling this result may be caused by in once case `configure_mappers()` hasn't run yet, and on the second run it has. maybe try that

**Comment by cuzox** [comment]
I upgraded the 1.3.19 and I'm still having the problem.
Where would I call `configure_mappers`?
I tried at the beginning of my instance method and it's still acting up.

This is my actual method:
```python
def update(self, **kwargs):
  configure_mappers()
  class_ = inspect(self).mapper.class_
  db = inspect(self).session
  for field, value in kwargs.items():
    if hasattr(class_, field):
      column_property = getattr(class_, field).property
      if type(column_property) is RelationshipProperty:
        #redacted relationship update for brevity
      else:
        setattr(self, field, value)
```

I'll try to reproduce the issue in a docker container

**Comment by CaselIT** [comment]
As an alternative you may also use the mapper directly in the function:
- [get_property](https://docs.sqlalchemy.org/en/13/orm/mapping_api.html?highlight=mapper#sqlalchemy.orm.Mapper.get_property)
- [relationships](https://docs.sqlalchemy.org/en/13/orm/mapping_api.html?highlight=mapper#sqlalchemy.orm.Mapper.relationships)

**Comment by cuzox** [comment]
Found the problem, I have a model property I'm defining like this:
```python
@property
def details(self):
	module = globals()[f'{self.code}_details']
	return object_session(self).query(module).filter(self.id == module.fk_id).first()
```

Which when looped, won't neither be `ColumnProperty` or `RelationshipProperty`, but `property`.
Reason being, I have a `code` property in my model, which will determine which kind of model it relates to.
`details` is kind of a workaround for having a dynamic has-one relationship.
Anyway, I can fix it by checking if this field is a `property`, in which case I'll want it to behave like if it were a relationship.

Not originally my question, but do you guys know of a way to solve the problem of a dynamic has-one while avoiding the n+1 problem I'm incurring in with this solution?

**Comment by cuzox** [comment]
Btw, thank for your prompt and helpful responses. You guys are awesome!

**Comment by zzzeek** [comment]
if you want to look up an object for "many-to-one" you can use query.get(), which is what the lazy loader does.  if the object is in the session already there's no SQL emitted:

    alpha = object_session(self).query(Alpha).get(self.alpha_id)

**Comment by cuzox** [comment]
Thank you @zzzeek! That could certainly help!
One thing though, I'm not actually storing the fk in the parent for the one-to-one, when I do:
```python
object_session(self).query(Bravo).get({ 'alpha_id': self.id })
```

I get:
```
sqlalchemy.exc.InvalidRequestError: Incorrect names of values in identifier to formulate primary key for query.get(); primary key attribute names are 'id'
```

But I suppose I could add `Bravo`'s fk to Alpha if it's the only way to make it work

**Comment by zzzeek** [comment]
OK I'm not following what you want to do.

You have a an Alpha, and you want to get the Bravo, and Bravo has a foreing key to Alpha?  that's a one-to-many load.   that would involve eager loading as documented at https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html .   But you'd need to use relationship() for that.  I'm not sure what the purpose of `@property / details()` is here, that looks like a plain relationship.

**Comment by zzzeek** [comment]
this is one-to-one  (which is really one-to-many but you load only one object): https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html#one-to-one

**Comment by cuzox** [comment]
I have an `Alpha` table, and I also have `Bravo_one` and `Bravo_two`, which both contain the fk `alpha_id` with a unique contraint.
I have a property in `Alpha` called `code`, which contains either `one` or `two` (the bravo suffix in this case). The relationship to whatever `Bravo` table will be determined by the content of the `code` property, so I haven't found a way to use `relationship` or `@hybrid_property` to determine which table to join at fetch time. The `@property` approach was the only way I found to dynamically select the right `Bravo` table from the `code` value, with the unfortunate downside that it needs to happen at mapping time.
Does that make sense?

**Comment by cuzox** [comment]
Using `get` would prevent subsequent queries when accessing the property, but I'd need to add a "fake" fk to `Alpha` (just a string) that will contain the `id` to whatever `Bravo` table `Alpha` corresponds to, which I think is reasonable. Although ideally I could do this at fetch time.

**Comment by zzzeek** [comment]
here's one approach:  make two separate relationships, one to BravoOne, the other to BravoTwo.  Then have a `@property` called "bravo" that grants one or the other relationship based on the value of the instance variable "self.code".

For that approach to work at the querying level, like query(Alpha).join(Alpha.bravo), it would depend on what kinds of queries you need to do, if they are across multiple "code" values or not.

Another approach.  Make two subclasses AlphaOne and AlphaTwo, using single-table inheritance.  the "code" column would be the discriminator.  AlphaOne has a relationship to BravoOne and AlphaTwo has a relatonship to BravoTwo.   On the base class Alpha you could have a relationship that joins to a base Bravo that I guess would have to use AbstractConcreteBase, again this would be giving you the ability to query for Alpha objects and join to both Bravo tables at the same time.   this would be a little complicated but would theoretically allow queries from alpha->bravo to be made generically at the class level.

certainly though for just instance-level some_alpha.bravos, two separate relationships and a `@property` to  choose one or the other is the way to go.

**Comment by cuzox** [comment]
There is going to be an arbitrary number of these tables, so I wouldn't want to make a relationship for each, and have logic at the querying level to determine which one to join. An `Alpha` can have only one type of `Bravo`. I'd like to maintain the querying interface agnostic from this.
I wouldn't want to join all of the `Bravo` tables at the same time, because they contain many nested relationships which are `lazy='joined'`.

I tried to use `column_property` with `case` and/or conditionals to build a statement that would do something like: `if Alpha.code == 'two' then join Bravo_two`. However, I was unsuccessful in making it work, not sure you could even do that (join conditionally) in PostgreSQL.

Thank you again for taking the time to respond and offer solutions zzzeeek, it's greatly appreaciated!
