### ISSUE TITLE
typo in 'Constructing a pool' docs - wrong parameter name (username instead of user)

### ISSUE THREAD

**Issue by toinbis** [sqlalchemy/sqlalchemy#5535]
https://docs.sqlalchemy.org/en/13/core/pooling.html#constructing-a-pool seems to have a typo in docs.  
As per https://www.psycopg.org/docs/module.html#psycopg2.connect , psycopg2.connect takes `user`, not `username` as the argument. Once `username` is passed, the error is raised: `psycopg2.ProgrammingError: invalid dsn: invalid connection option "username"`.

![Screenshot 2020-08-24 at 23 51 18](https://user-images.githubusercontent.com/68685/91095288-c8e83280-e664-11ea-981c-e9352b30e66b.png)

P.S. Many thanks for creating SqlAlchemy!

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fix typo in docs examples of psycopg2.connect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2179

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix typo in docs examples of psycopg2.connect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2180
