### ISSUE TITLE
attribute_mapped_collection not working in some case

### ISSUE THREAD

**Issue by youtux** [sqlalchemy/sqlalchemy#5538]
**Describe the bug**
It seems to me that attribute_mapped_collection() does populate the dictionary key correctly using a specific order of argument when creating an object. See the code below.

**Expected behavior**
The argument order passed to `ItemSaleSettings.__init__` should not matter, and both definition of that object should back-populate Sale.item_settings correctly.

**To Reproduce**

```py
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm.collections import attribute_mapped_collection

# Just used for better string representation
class _Base(object):
    def __str__(self):
        return '{self.__class__.__name__}({self.id})'.format(self=self)
    __repr__ = __str__


Base = declarative_base(cls=_Base)


class Sale(Base):
    __tablename__ = "sale"
    id = Column(Integer, primary_key=True)

    item_settings = relationship(
        lambda: ItemSaleSettings,
        back_populates='sale',
        collection_class=attribute_mapped_collection('item'),
    )


class Item(Base):
    __tablename__ = "item"
    id = Column(Integer, primary_key=True)


class ItemSaleSettings(Base):
    __tablename__ = "item_sale_settings"
    __table_args__ = (UniqueConstraint('sale_id', 'item_id'),)

    id = Column(Integer, primary_key=True)

    sale_id = Column(Integer, ForeignKey(Sale.id), nullable=False)
    sale = relationship(Sale, back_populates='item_settings')

    item_id = Column(Integer, ForeignKey(Item.id), nullable=False)
    item = relationship(Item)

    enabled = Column(Boolean, nullable=False, default=False)

    # potentially other settings, but irrelevant for this bug report


sale = Sale(id=1)

item1, item2 = Item(id=1), Item(id=2)


iss1 = ItemSaleSettings(
    id=1,
    enabled=True,

    item=item1,
    sale=sale,
)

print(sale.item_settings)
assert sale.item_settings[item1].enabled  # works as expected

iss2 = ItemSaleSettings(
    id=2,
    enabled=True,
    # Swapping the order of the params (sale, item) will make the assertion fail
    sale=sale,
    item=item2,
)

print(sale.item_settings)  # Notice the key `None`, which should not exist
assert sale.item_settings[item2].enabled  # Breaks!

```

**Error**

```
{Item(1): ItemSaleSettings(1)}
{Item(1): ItemSaleSettings(1), None: ItemSaleSettings(2)}
Traceback (most recent call last):
  File "/Users/youtux/Library/Application Support/JetBrains/PyCharm2020.2/scratches/scratch_1.py", line 78, in <module>
    assert sale.item_settings[item2].enabled
KeyError: Item(2)

```

**Versions.**
 - OS: macOS Catalina 10.15.6
 - Python: 3.6.11
 - SQLAlchemy: 1.3.19
 - Database: not relevant
 - DBAPI: not relevant

**Have a nice day!**

**Comment by zzzeek** [comment]
Hi @youtux -

Using a relationship as the "key" for an attribute_mapped_collection, never occurred to me anyone would try to do that.   although, there's probably no issue with that intrinsically. 

however, It is already documented that what you're doing won't work, though it's probably not clear:

https://docs.sqlalchemy.org/en/13/orm/collections.html?highlight=attribute_mapped_collection#sqlalchemy.orm.collections.attribute_mapped_collection

> The key value must be immutable for the lifetime of the object. You can not, for example, map on foreign key values **if those key values will change** during the session, i.e. from None to a database-assigned integer after a session flush.

when you say "the argument order should not matter", I would have to disagree on that.  here's your code written differently:

```
iss1 = ItemSaleSettings(id=1, enabled=True)
iss1.item = item1
iss1.sale = sale

```

vs

```
iss2 = ItemSaleSettings(
    id=2,
    enabled=True)
iss2.sale = sale
iss2.item = item2

```

that is, the attribute mapped collection only does its thing when you actually assign to it.    so in the second example, "iss2.item" is None.  you assign iss2.sale to it, that backrefs to sale.item_settings.   the key is None and the collection is working as documented.

I would probably write a custom constructor that does the things in the order you want, and probably use `@validates` to make sure "item" is non-None when sale is assigned.   

Here's an event handler that will do that and also will even let you change the value of "iss.item" on the fly.  I haven't tested this approach, in theory this could be documented but I can't guarantee it works in all cases and isn't part of our test support right now:

```
from sqlalchemy import event
from sqlalchemy.orm import attributes

@event.listens_for(ItemSaleSettings.item, "set")
def set_item(obj, value, previous, initiator):
    if obj.sale is not None:
        if previous is attributes.NO_VALUE:
            previous = None

        obj.sale.item_settings[value] = obj
        obj.sale.item_settings.pop(previous)

```

your test case passes with the above event handler.

**Comment by youtux** [comment]
From my point of view, when inside `ItemSaleSetting.__init__`, `self` is an object being constructed, so assigning `self.sale = ...` should really not trigger actions that try to access attributes of `self` (in this case, reading `self.item`).

I think that those actions should be triggered once the `__init__` is over, or at least once the "key" attribute is set. I understand the machinery behind this may be big already, so I will just change my `__init__` to assign `self.sale` only after `self.item`.

> however, It is already documented that what you're doing won't work, though it's probably not clear:
>
>https://docs.sqlalchemy.org/en/13/orm/collections.html?highlight=attribute_mapped_collection#sqlalchemy.orm.collections.attribute_mapped_collection
>
> > The key value must be immutable for the lifetime of the object. You can not, for example, map on foreign key values if those key values will change during the session, i.e. from None to a database-assigned integer after a session flush.

I find that the documentation is not really explicit in this sense (it mention the foreign key value changing after flush, but not the fact that in the "key" attribute has to be populated before assigning the relationship), maybe it could be more explicit?

**Comment by youtux** [comment]
Slightly off-topic: Is there a way to get the following to work? It feels natural to me that the relationships on ItemSaleSettings would be automatically populated, but they are not:
```py
sale.item_settings[item1] = ItemSaleSettings(enabled=True)

assert sale.item_settings[item1].sale == sale
assert sale.item_settings[item1].item == item1
```

**Comment by zzzeek** [comment]
> From my point of view, when inside `ItemSaleSetting.__init__`, `self` is an object being constructed, so assigning `self.sale = ...` should really not trigger actions that try to access attributes of `self` (in this case, reading `self.item`).
> 
> I think that those actions should be triggered once the `__init__` is over, or at least once the "key" attribute is set. I understand the machinery behind this may be big already, so I will just change my `__init__` to assign `self.sale` only after `self.item`.

But then if I were to assign to "iss.sale" inside my own `__init__` method, the dictionary would not be populated yet.  There could be any number of other events I've set up that assumes attribute_mapped_collection works the same way in all cases, which is, when it's assigned to, then the collection is present.     what you are suggesting would imply that even backrefs don't get assigned when they happen to be inside of an `__init__` method.   IMO there's really no architecture that could assume the behaviors you're suggesting, because on-attribute-change is on-attribute-change . 

What would solve the problem entirely would be if the event handler I illustrated were an intrinsic part of attribute_mapped_collection.  I'm not ready to do that right now, but if we were to improve upon this, that would be how to do it, not by rethinking attribute events entirely to work in some new way within `__init__`.


> 
> I find that the documentation is not really explicit in this sense (it mention the foreign key value changing after flush, but not the fact that in the "key" attribute has to be populated before assigning the relationship), maybe it could be more explicit?

sure, as I mentioned, I never imagined someone using a relationship object as a key in the first place.  this was for much simpler things.

**Comment by youtux** [comment]
I think that indeed that event handler can resolve it as well, but I don't like to play too much with event handlers, I'd rather have it explicit in my `__init__`.
Of course it would be nice if attribute_mapped_collection would do that out of the box.

Did you have a chance to look at https://github.com/sqlalchemy/sqlalchemy/issues/5538#issuecomment-680941717? I assume I posted it while you were writing your post, so you may have missed that.

**Comment by zzzeek** [comment]
> Slightly off-topic: Is there a way to get the following to work? It feels natural to me that the relationships on ItemSaleSettings would be automatically populated, but they are not:
> 
> ```python
> sale.item_settings[item1] = ItemSaleSettings(enabled=True)
> 
> assert sale.item_settings[item1].sale == sale
> assert sale.item_settings[item1].item == item1
> ```

again you'd need to use set events to detect this inconsistency.  attribute_mapped_collection was not intended to be this elaborate.

**Comment by youtux** [comment]
Thank you for the explanation!

**Comment by zzzeek** [comment]
I see now that attribute_mapped_collection is kind of insufficient and is kind of still in the "older" SQLAlchemy world which had a lower bar of built-in functionality.

**Comment by youtux** [comment]
I find it super helpful though, as some relationships are better represented with dicts rather than lists.

**Comment by youtux** [comment]
In the end the following worked out:
```python

@event.listens_for(ItemSaleSettings.item, "set")
def set_item(obj, value, previous, initiator):
    sale = obj.sale
    if sale is not None:
        if previous in (attributes.NO_VALUE, attributes.NEVER_SET):
            previous = None

        sale.item_settings.pop(previous)    # will set obj.sale to None
        sale.item_settings[value] = obj

```

**Comment by blaise-io** [comment]
I also ran into this issue. Although @youtux's solution works for me, I initially expected this to be part of SQLAlchemy.

**Comment by zzzeek** [comment]
I will gladly endorse a third-party extension that does everything people want.   attribute_mapped_collection is not widely used enough to warrant a significant amount of new complexity and automation that will lead to many more bugs having to be fixed.
