### ISSUE TITLE
raise informative message when assocaition proxy attempted to be used in plain column context

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5542]
raise an error when the use case at #5541 is used, until if and when we have a better approach.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Raise NotImplemenedError for association proxy __clause_element__** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2189

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Raise NotImplemenedError for association proxy __clause_element__** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2190
