### ISSUE TITLE
bulk_update_mappings method does not work with list of dictionaries given as a variable for update while the same list when provided as an expanded form(actual dictionary with key and value) works fine

### ISSUE THREAD

**Issue by nirum09** [sqlalchemy/sqlalchemy#5543]
**Describe the bug**
updated_records=[{'id':1, 'salary':5000},{'id':2, 'salary':8000}]
db.session.bulk_update_mappings(Salary, updated_records)
throws error sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'numpy.int64' 
(Background on this error at: http://sqlalche.me/e/13/f405)

while 
db.session.bulk_update_mappings(Salary,[{'id':1, 'salary':5000}, {'id':2, 'salary':8000}]) works fine

**Expected behavior**
both scenarios should work as they are same

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example. 
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22)

```py
updated_records=[{'id':1, 'salary':5000},{'id':2, 'salary':8000}]
db.session.bulk_update_mappings(Salary, updated_records)
```

**Error**

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'numpy.int64' 
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Versions.**
 - OS: macOS Catalina 
 - Python: 3.8
 - SQLAlchemy: 1.3.18 (Flask-SQLAlchemy version: 2.4.3)
 - Database:postgresdb
 - DBAPI: psycopg2

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

there's no reproduction case attached here but it looks like you are using numpy integers, which it seems like the psycopg2 driver is rejecting.  

Convert the numpy integers to plain python integers, or feel free to raise this with numpy and/or psycopg2.

**Comment by zzzeek** [comment]
some background

https://stackoverflow.com/questions/50626058/psycopg2-cant-adapt-type-numpy-int64

**Comment by nirum09** [comment]
You are right. Thanks for assisting!
