### ISSUE TITLE
Postgres <col>.any(<obj>, operator=operators.ne) compiles incorrectly

### ISSUE THREAD

**Issue by bradykieffer** [sqlalchemy/sqlalchemy#5544]
**Describe the bug**
I'm _fairly_ sure that calling `col.any("foo", operator=operators.ne)` results in an incorrect query being compiled (although I could 100% be wrong on this). I have a draft patch put up that I think pretty succinctly demonstrates the issue [here](https://github.com/bradykieffer/sqlalchemy/pull/1) (on a fork). The generated SQL leads to weird behavior / doesn't actually guarantee that none of the elements within the aggregated set do not equal `foo`.

**Expected behavior**
I expect the underlying SQL generated from:

```python
c.any(5, operator=operators.ne)
``` 

to be:
```sql
NOT (5 = ANY(x))
```

**To Reproduce**
[This](https://github.com/sqlalchemy/sqlalchemy/blob/master/test/dialect/postgresql/test_compiler.py#L1276) test case actually repros the issue directly. Specifically calling `column.any(value, operator=operators.ne)` will repro it for me. I haven't verified other cases because I wanted to double check this isn't expected behavior first. I've modified the testcase [here](https://github.com/bradykieffer/sqlalchemy/pull/1) in a draft patch to demonstrate the error & my attempt at a fix.

```py
self.assert_compile(
    c.any(5, operator=operators.ne),
    "NOT (%(param_1)s = ANY (x))",
    checkparams={"param_1": 5},
)
```

**Versions.**
 - OS: macOS
 - Python: Python3.8
 - SQLAlchemy: Running off commit: d78686b4f109fdc78ca6239e5a5af791717bc48d
 - Database: Postgres (I'm running 9.6 at the moment)
 - DBAPI psycopg2

**Additional context**
Again I'm not 100% certain on this but I'd love to figure out how to properly test the issue assuming it is one to get more familiar with the code base 😄

**Comment by zzzeek** [comment]
so there's a thing where behaviors that havent changed in years suddenly get reported in twos.  for this one, it's #5518.   That one makes more sense to me though as it is:
```

>>> x = ~column("q", ARRAY(String)).any("foo")
>>> print(x)
NOT (:param_1 = ANY (q))
```

above, that's the repaired behavior that will be in 1.3.20 and is not released yet.

that seems to be what your intent really is.  When you actually inject the "!=" operator, that seems like it should be rendering "!=" even though it's non sensical. I might rather have that case raise an error.

**Comment by zzzeek** [comment]
also re: the PR I would not do the "switch" in the compiler like that, it woudl be when the any() object builds itself up.

**Comment by zzzeek** [comment]
the != operator with ANY, while unusual, is valid SQL on PostgreSQL and is meaningful in the way one would expect:
```

test=> select 5 != ANY(ARRAY[1, 2, 3]);
 ?column? 
----------
 t
(1 row)

test=> select 5 != ANY(ARRAY[5]);
 ?column? 
----------
 f
(1 row)

```

I can use it to detect if a list has any non-blanks, or non zeros, doesn't seem useless:

```
test=> select '' != ANY(ARRAY['', '', '', '']);
 ?column? 
----------
 f
(1 row)

test=> select '' != ANY(ARRAY['', '', 'x', '']);
 ?column? 
----------
 t
(1 row)

test=> select 0 != ANY(ARRAY[0, 0, 0, 0, 0]);
 ?column? 
----------
 f
(1 row)

test=> select 0 != ANY(ARRAY[0, 0, 0, 1, 0]);
 ?column? 
----------
 t
(1 row)

```

so I would vote we consider this a dupe of #5518 for the "NOT (x = ANY(..))" use case.

**Comment by bradykieffer** [comment]
Of course I didn't catch that 😄 , thanks for the quick response, I agree we can consider it a duper of #5518.
