### ISSUE TITLE
implement tranasction_characteristics API which mirrors isolation level API; implement flags for postgresql

### ISSUE THREAD

**Issue by ziima** [sqlalchemy/sqlalchemy#5549]
Apart from having option to select isolation level, it may come handy to create a transaction in a read only mode. This option is supported on postgres, see https://www.postgresql.org/docs/current/sql-set-transaction.html. I'm not sure about other database backends, but mysql seems to support them as well, see https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html.

I suggest to add an optional parameter transaction mode with possible values `READ WRITE` (default) or `READ ONLY` to execution options, similarly to isolation level.

**Comment by zzzeek** [comment]
hi -

can you do some research with the psycopg2 driver to see how this might work?   need driver level support.

**Comment by zzzeek** [comment]
there is also a deferrable flag so this change should support that as well.

problematic here is the API to be used.    the isolation level API has many steps and is supported at the base dialect level, as any connection that has this option changed upon it has to have it reset when that connection is returned to the connection pool.

but in this case at least "readonly" is independent of the isolation level setting even though it is still part of transaction characteristics.

it looks like "deferrable" is not actually independent of isolation level: https://www.postgresql.org/docs/current/sql-set-transaction.html

"The DEFERRABLE transaction property has no effect unless the transaction is also SERIALIZABLE and READ ONLY. "

these flags would be easy to implement as per-engine/dialect initialization flags but as they are part of transaction characteristics is makes sense they would be part of execution_options().

however that means we would have to duplicate all the logic we see in places like https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L515 unless we can inject these additional characteristics into the existing isolation level system, such as adding support for extra characteristics.    The system relies upon a "default isolation level" value that we determine at startup.  All of this needs to be enhanced to support isolation levels that have additional characteristics.

the isolation level system also supports getters, like  we need to implement those also to support additional characteristics somehow, such as https://docs.sqlalchemy.org/en/13/core/connections.html?highlight=get_isolation_level#sqlalchemy.engine.Connection.get_isolation_level etc., a huge amount of effort went into testing all this and documenting it.

I think we have to take this system at the base level and double it out for a whole new set of "transaction_characteristics" flags as it is likely other databases have flags like this as well.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Create connection characteristics API; implement postgresql flags** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2216

**Comment by zzzeek** [comment]
OK here's a surprise from asyncpg:

    ValueError: "readonly" is only supported for serializable transactions

why would asyncpg have that limitation and not psycopg2?

**Comment by ziima** [comment]
Thanks :+1:
