### ISSUE TITLE
Query.filter() fails with Int-Like structures i.e. (pandas int64)

### ISSUE THREAD

**Issue by kolumdium** [sqlalchemy/sqlalchemy#5552]
**Describe the bug**

When using the query().filter() statement with Int-like Structures like pandas int64 the statement does not return the expected Result or crashes. Even though they "==" as true they do not return the same statement.

**Expected behavior**

I either expected the query return the right result or throw an exception that this Datatype is not supported.

**To Reproduce**
```py
from sqlalchemy import Column, Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import Table
from sqlalchemy import create_engine

import pandas as pd

Base = declarative_base()

class Foo(Base):
    __tablename__ = "foos"
    
    id      = Column(Integer, primary_key=True)
    
    def __init__(self, id):
        self.id = id
    
engine = create_engine("sqlite:///:memory:")
Base.metadata.create_all(engine)
Session = sessionmaker(bind = engine)

db_session = Session()

foo = Foo(100)

db_session.add(foo)
db_session.commit()

pd = pd.DataFrame()
pd["int"] = [100]
broken_int = pd["int"].iloc[0]

bar = 100

print(bar == broken_int == 100)

print(db_session.query(Foo).filter(Foo.id == 100).count())
print(db_session.query(Foo).filter(Foo.id == bar).count())
print(db_session.query(Foo).filter(Foo.id == broken_int).count())
print(db_session.query(Foo).filter(100 == Foo.id).count())
print(db_session.query(Foo).filter(bar == Foo.id).count())
print(db_session.query(Foo).filter(broken_int == Foo.id).count())
```

**Error**

```
runfile('C:/Users/plank/Documents/git/bicyclelogger/evaluation/tests/untitled1.py', wdir='C:/Users/plank/Documents/git/bicyclelogger/evaluation/tests')
True
1
1
0
1
1
Traceback (most recent call last):

  File "C:\Users\plank\Documents\git\bicyclelogger\evaluation\tests\untitled1.py", line 50, in <module>
    print(db_session.query(Foo).filter(broken_int == Foo.id).count())

    File "<string>", line 2, in filter

  File "C:\Users\plank\anaconda3\envs\bicyclelogger\lib\site-packages\sqlalchemy\orm\base.py", line 227, in generate
    fn(self, *args[1:], **kw)

  File "C:\Users\plank\anaconda3\envs\bicyclelogger\lib\site-packages\sqlalchemy\orm\query.py", line 1862, in filter
    criterion = expression._expression_literal_as_text(criterion)

  File "C:\Users\plank\anaconda3\envs\bicyclelogger\lib\site-packages\sqlalchemy\sql\elements.py", line 4698, in _expression_literal_as_text
    return _literal_as_text(element)

  File "C:\Users\plank\anaconda3\envs\bicyclelogger\lib\site-packages\sqlalchemy\sql\elements.py", line 4721, in _literal_as_text
    return _literal_as(element, _no_text_coercion)

  File "C:\Users\plank\anaconda3\envs\bicyclelogger\lib\site-packages\sqlalchemy\sql\elements.py", line 4711, in _literal_as
    raise exc.ArgumentError(

ArgumentError: SQL expression object expected, got object of type <class 'numpy.bool_'> instead
```

**Versions.**
 - OS: Windows 20201.1000
 - Python: 3.8.5
 - SQLAlchemy: 1.3.19
 - Database: sqlite-3.33.0
 - DBAPI: sqlite-3.33.0
 - Pandas: pandas-1.1.1

**Additional context**

I am Using Spyder in Anaconda with
 ipython-7.18.1, spyder-kernels-1.9.3 and anaconda 2020.07

I am unsure if this a Problem SQLAlchemy can or should fix or if this is an issue for pandas.
**Have a nice day!**

**Comment by zzzeek** [comment]
hi -

I've created a new tag to track this unfortunately unsolvable incompatibility, similar issues can be seen at #5543, #5167, #3586.

in this case, numpy's integer datatype provides a Python ``__eq__()`` method which prevents SQLAlchemy's expression system from functioning.

An expression like ``column == number`` produces a binary expression object by overriding the ``__eq__()`` method.  this is detailed in the Core tutorial at https://docs.sqlalchemy.org/en/13/core/tutorial.html#operators.

When the numpy integer is specified first, it prevents SQLAlchemy's method from running.  Example below illustrates this:

```
import numpy
from sqlalchemy import column, Integer

n = numpy.int32(10)

expr1 = column('x', Integer) == n
expr2 = n == column('x', Integer)

print(expr1)

print(expr2)

```

output, in the second case, numpy takes over and disallows SQLAlchemy's converter from working correctly:

```
$ python test4.py 
x = :x_1
False

```

the fundamental issue is that numpy's datatypes are not honoring the ``__eq__()`` method of the other object.

**Comment by zzzeek** [comment]
interestingly though it appears to be calling our ``__eq__()`` method, which returns the correct result, and then somehow the result is vanishing.   let me see why that's happening.

**Comment by zzzeek** [comment]
ah, it appears like it lets our ``__eq__()`` run, but then it calls ``__bool__()`` on the result!  which means it has no choice but to be reduced into a ``True`` or ``False``.   still not really sure how to fix that.

**Comment by zzzeek** [comment]
nope.   they are doing it so that they can return a numpy.bool, and if I have our `__bool__()` raise an error in this case (which we can't really do for other reasons, but even if we could), numpy is *letting it through* with a warning:

```
python test4.py 
test4.py:6: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  expr2 = n == column('x', Integer)
x = :x_1

```

which IMO is worse than the error you are getting, and we can't really do it that way anyway.

perhaps some very exotic way that we're return a SQLAlchemyBool that somehow gives context to the event long ago that created the problem.     not really worth it.

You actually did get an ArgumentError and it did refer to numpy so while not perfect, that should give you enough to go on in order to fix the problem again.     i see no other actions that can be taken here other than an FAQ entry.

**Comment by kolumdium** [comment]
Fair enough.

I mean the Problem is easy enough to fix if you know whats going on.
You can cast it to a python Int again.

```
print(db_session.query(Foo).filter(Foo.id == broken_int).count())
```
returning Zero cought me off Guard and took a bit to figure out in my Application.

Thanks for the answers!

An FAQ entry sounds great.

**Comment by zzzeek** [comment]
tried to see where numpy might be doing this and this is not a library that can be studied that quick.   none of the usual keywords are presenting themselves to provide any clues.

tried this:

```
class SQLAlchemyBool(bool):
    __slots__ = "value", "clauseelement"

    def __init__(self, value, clauseelement):
        self.value = value
        self.clauseelement = clauseelement

    def __clause_element__(self):
        return self.clauseelement

    def __bool__(self):
        return self.value

    __nonzero__ = __bool__


```

and it says:

TypeError: type 'bool' is not an acceptable base type

ouch!  OK then doing this:
```

class SQLAlchemyBool(object):
    __slots__ = "value", "clauseelement"

    def __init__(self, value, clauseelement):
        self.value = value
        self.clauseelement = clauseelement

    def __clause_element__(self):
        return self.clauseelement

    def __bool__(self):
        return self.value

    __nonzero__ = __bool__

```

leads us back to the warning.

the only way left I can see this working automatically is if numpy looked for special hooks on a class, such as a ``__numpy_eq__()`` hook , we could implement that.    I doubt they have that though.

**Comment by zzzeek** [comment]
or, if numpy only called bool() *if* the object is already a Python bool object.   Seems unlikely they'd be able to make a change like that now.
