### ISSUE TITLE
query_expression not overriden if model instance for the same row is still around

### ISSUE THREAD

**Issue by bbc2** [sqlalchemy/sqlalchemy#5553]
**Describe the bug**

I retrieve an instance first without `with_expression`, then again with `with_expression`.  The second instance doesn't have the query expression populated.

**Expected behavior**

I expect the query expression to be populated on the second instance.

**To Reproduce**

```py
from sqlalchemy import Column, Integer, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import query_expression, sessionmaker, with_expression
from sqlalchemy.sql import literal

Base = declarative_base()


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    number = query_expression()


def main():
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()

    session.add(User())
    session.commit()

    user = session.query(User).one()  # Remove `user =` and the issue disappears
    same_user = session.query(User).options(with_expression(User.number, literal(1))).one()

    assert same_user.number is not None


if __name__ == "__main__":
    main()
```

**Error**

```
Traceback (most recent call last):
  File "foo.py", line 32, in <module>
    main()
  File "foo.py", line 28, in main
    assert same_user.number is not None
AssertionError
```

**Versions.**
 - Python: 3.8.5
 - SQLAlchemy: 1.3.19
 - Database: SQLite or PostgreSQL

**Additional context**

The problem appeared in SQLAlchemy 1.3.18.  By doing some testing, I was able to pinpoint the exact PR: #5354.

**Comment by CaselIT** [comment]
Hi,

From the [docs](https://docs.sqlalchemy.org/en/13/orm/loading_columns.html?highlight=with_expression#sqlalchemy.orm.with_expression) it seems this should apply only to “deferred expression” attributes.

calling `session.expire()` should expire the current session cache and making the invocation work again.

I'm not sure if the bug was before or it is now, since the current behaviour seems to enforce that the attribute should be deferred.

Still a test case or a fix is probably needed in either case

**Comment by zzzeek** [comment]
hi -

you need to use populate_existing:

    same_user = session.query(User).populate_existing().options(with_expression(User.number, literal(1))).one()

no dragon.  ok dragon coming up

**Comment by CaselIT** [comment]
Should there also be a test case to ensure that the same behaviour is in 1.4?

**Comment by zzzeek** [comment]
There's a lot of tests that would fail if mapper options suddenly implied populate_existing.  all mapper options are subject to the same beahvior.  I will add a test.

**Comment by bbc2** [comment]
Thank you for the clarification!   :dragon_face:   I didn't know about `populate_existing`.

**Comment by zzzeek** [comment]
with_expression() is very new and as it's embedded in the query it suddenly makes populate_exisitng() a lot more important to people.
