### ISSUE TITLE
Subquery Example

### ISSUE THREAD

**Issue by DraakUSA** [sqlalchemy/sqlalchemy#5556]
I would like to see examples added for subqueries, both with and without aliasing.

Nothing in the the documentation (from what I can tell) indicates how to reference the columns in the subquery.

**Comment by zzzeek** [comment]
hi -

this is illustrated here:

https://docs.sqlalchemy.org/en/13/orm/tutorial.html#using-subqueries

there are also new tutorials that will be part of version 2.0.    there's no need to leave this ticket open.

**Comment by zzzeek** [comment]
subqueries are also aliased by definition in SQLAlchemy.  there are some legacy use cases that can slip through in 1.3 but this will not be possible in 1.4.

**Comment by zzzeek** [comment]
Core has information on this as well from a Core perspective at https://docs.sqlalchemy.org/en/13/core/tutorial.html#using-aliases-and-subqueries

both of these tutorials will be unified in 1.4.
