### ISSUE TITLE
CursorResultMetaData._adapt_to_context causes ambiguous column name

### ISSUE THREAD

**Issue by fantix** [sqlalchemy/sqlalchemy#5559]
**Describe the bug**

When two identical queries (with same column names from different tables) with different memory address are executed sequentially, the latter reuses the cached compiled statement, and calls `CursorResultMetaData._adapt_to_context()` but breaks the metadata, leading to "ambiguous column name" errors when indexing by columns.

**Expected behavior**

Metadata is not broken, and the result indexing by columns works.

**To Reproduce**

```py
import sqlalchemy as sa

metadata = sa.MetaData()
users = sa.Table(
    "users",
    metadata,
    sa.Column("id", sa.Integer, primary_key=True),
    sa.Column("team_id", metadata, sa.ForeignKey("teams.id")),
)
teams = sa.Table(
    "teams", metadata, sa.Column("id", sa.Integer, primary_key=True),
)


def build_query():
    return sa.select([users.c.id, teams.c.id]).select_from(
        users.outerjoin(teams)
    )


e = sa.create_engine("postgresql:///", echo=True)
metadata.drop_all(e)
metadata.create_all(e)
tid = e.execute(teams.insert().returning(teams.c.id)).scalar()
e.execute(users.insert().values(team_id=tid))

print(e.execute(build_query()).first()[users.c.id])  # always succeed
print(e.execute(build_query()).first()[users.c.id])  # success expected
```

**Error**

```
2020-09-05 14:00:42,711 INFO sqlalchemy.engine.Engine SELECT users.id, teams.id 
FROM users LEFT OUTER JOIN teams ON teams.id = users.team_id
2020-09-05 14:00:42,711 INFO sqlalchemy.engine.Engine [generated in 0.00025s] {}
1
2020-09-05 14:00:42,712 INFO sqlalchemy.engine.Engine SELECT users.id, teams.id 
FROM users LEFT OUTER JOIN teams ON teams.id = users.team_id
2020-09-05 14:00:42,712 INFO sqlalchemy.engine.Engine [cached since 0.001864s ago] {}
Traceback (most recent call last):
  File "test_cache.py", line 28, in <module>
    print(e.execute(build_query()).first()[users.c.id])
  File "sqlalchemy/lib/sqlalchemy/engine/cursor.py", line 587, in _raise_for_ambiguous_column_name
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Ambiguous column name 'id' in result set column descriptions
```

**Versions.**
 - OS: Darwin Kernel Version 19.5.0
 - Python: Python 3.8.2
 - SQLAlchemy: 1.4.0b1 @ fc612d17145453ad95e5f9ba6a40ba70d2f507c3
 - Database: PostgreSQL 12.4
 - DBAPI: psycopg2 2.8.5 (dt dec pq3 ext lo64)

**Additional context**

```python
row = e.execute(build_query()).first()
print(row._keymap[users.c.id])
row = e.execute(build_query()).first()
print(row._keymap[users.c.id])
```

Output:
```
(0, (Column('id', Integer(), table=<users>, primary_key=True, nullable=False), 'id', 'id', 'users_id'), 'id', 'id', None, None)
(None, (), 'id')
```

Part of the reasoning:
https://github.com/sqlalchemy/sqlalchemy/blob/fc612d17145453ad95e5f9ba6a40ba70d2f507c3/lib/sqlalchemy/engine/cursor.py#L1246-L1253

Because `compiled.statement is not context.invoked_statement` (different memory address), `_adapt_to_context()` is called and I didn't follow into that method to find out why it breaks the metadata.

**Have a nice day!**

**Comment by fantix** [comment]
It works fine with SQLAlchemy 1.3.19 @ da4e4cb1c.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't rely on string col name in adapt_to_context** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2214

**Comment by zzzeek** [comment]
thanks.  this is all new stuff in 1.4, there is nothing like this caching system in 1.3.

**Comment by fantix** [comment]
Thanks for the fast fix!

**Comment by zzzeek** [comment]
well this one is at the center of everything I want to get back to the API / documentation niceness I've been working on.  all the hard stuff is supposed to be done :)
