### ISSUE TITLE
How to compare two SQL expressions for equality?

### ISSUE THREAD

**Issue by tribals** [sqlalchemy/sqlalchemy#5562]
Currently, there is a plenty of SQL constructs which can be compared to each other through its `.compare()` method. For example: [`sqlalchemy.sql.expression.ColumnElement.compare()`](https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=compare#sqlalchemy.sql.expression.ColumnElement.compare).

The problem here, that its [default implementation](https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=compare#sqlalchemy.sql.expression.ClauseElement.compare) just compares Python objects identity:

> Subclasses should override the default behavior, which is a straight identity comparison.

Seems like a little (or none) bothered with actually overriding default implementation. Example:

```python
from sqlalchemy.schema import Column, MetaData, Table
from sqlalchemy.sql import select
from sqlalchemy.types import Integer, String

metadata = MetaData()

users = Table('users', metadata, Column('id', Integer, primary_key=True), Column('name', String))


select([users]).compare(select([users]))
# False

select([users]).compare
# <bound method ClauseElement.compare of <sqlalchemy.sql.selectable.Select at 0x7fdb53f513d0; Select object>>
```

As you can see, `Select` doesn't override its `.compare()` method and inherits it from `ClauseElement`.

I can see the reason why this is so.

But I also want to finally find the way to compare statements (or expressions) by its SQL representation rather than Python identity. After all, the statement `SELECT users.id, users.name FROM users;` is essentially the *same* as `SELECT users.id, users.name FROM users;`, even if they are compiled from *different* Python `Select` objects. Isn't that?

The reason *why* to do that is that it opens infinite possibilities to manipulate statements (and expressions) directly.

To me, the main reason is *testing*. I saw so many tests that do insert, then query, then assert result is as expected. To me, such kind of test is ugly in many ways. First, it requires set up and running *database* to just run the tests! Second, they are [*flaky*](https://martinfowler.com/articles/nonDeterminism.html) - they may pass or fail depending on so many conditions: is database running, are credentials correct, is DB schema up to date, is related table populated with right rows, etc. And finally, what these tests do test, actually? The fact that whole DB stack - SQLA, driver, database itself - is working? To me, such kind of tests is completely useless.

But how *a right test* could be looking?

The solution is actually very simple. Instead of testing whole DB stack, you need to assert that your program *issues correct SQL statements* to DB. And it is where SQL constructs comparison come into play. For example, the hypothetical test for table from example above may look like this:

```python
from unittest import mock

from sqlalchemy.engine import Connection


def test_get_all_users():
    connection = mock.Mock(spec=Connection)

    assert connection.execute.called
    assert connection.execute.call_args.args[0].compare(select([users]))
```

But, in order to do so, you need a way to ensure that *two SQL constructs are the same* by its SQL representation, not by object identity.

Such approach would us to turn slow, flaky and useless (in regard of testing DB-related stuff) *integration* (or functional, or whatever you call it) tests into simple, quick and deterministic *unit* tests.

Of course, this is trivial example. In real life, you need to take into account other circumstances such as different RDBMS dialects. But, as of the SQLAlchemy tries to abstract these circumstances, personally I think that comparison by representation would be very useful feature.

I tried to manually compile statements (with proper dialect in use) and then match it with regex. Such solution seems working for simple queries. But it is very error prone (hard to write correct regex) and its difficulty quickly blows up for more-or-less sophisticated queries (a SQL-Schema(???) would be very helpful, though, but I'm not aware of any existing such a thing; do you? If so, please, tell me).

So, what you think about it?

**Comment by zzzeek** [comment]
Hey there.

.compare is fully implemented as a fundamental element of the new caching system in 1.4.   work against sqlalchemy master and you will see things are quite different, literally months of work went into implementing deep SQL element comparison.  See test/sql/test_compare.py for the central test suite.  I'll point out the issue numbers etc when I'm at my machine next. 

On Sun, Sep 6, 2020, at 7:24 AM, Anthony wrote:
> 

> Currently, there is a plenty of SQL constructs which can be compared to each other through its `.compare()` method. For example: `sqlalchemy.sql.expression.ColumnElement.compare()` <https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=compare#sqlalchemy.sql.expression.ColumnElement.compare>.

> The problem here, that its default implementation <https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=compare#sqlalchemy.sql.expression.ClauseElement.compare> just compares Python objects identity:

>> Subclasses should override the default behavior, which is a straight identity comparison.

> Seems like a little (or none) bothered with actually overriding default implementation. Example:

> from sqlalchemy.schema import Column, MetaData, Table
> from sqlalchemy.sql import select
> from sqlalchemy.types import Integer, String

> metadata = MetaData()

> users = Table('users', metadata, Column('id', Integer, primary_key=True), Column('name', String))


> select([users]).compare(select([users]))
> # False

> select([users]).compare
> # <bound method ClauseElement.compare of <sqlalchemy.sql.selectable.Select at 0x7fdb53f513d0; Select object>>
> As you can see, `Select` doesn't override its `.compare()` method and inherits it from `ClauseElement`.

> I can see the reason why this is so.

> But I also want to finally find the way to compare statements (or expressions) by its SQL representation rather than Python identity. After all, the statement `SELECT users.id, users.name FROM users;` is essentially the *same* as `SELECT users.id, users.name FROM users;`, even if they are compiled from *different* Python `Select` objects. Isn't that?

> The reason *why* to do that is that it opens infinite possibilities to manipulate statements (and expressions) directly.

> To me, the main reason is *testing*. I saw so many tests that do insert, then query, then assert result is as expected. To me, such kind of test is ugly in many ways. First, it requires set up and running *database* to just run the tests! Second, they are *flaky* <https://martinfowler.com/articles/nonDeterminism.html> - they may pass or fail depending on so many conditions: is database running, are credentials correct, is DB schema up to date, is related table populated with right rows, etc. And finally, what these tests do test, actually? The fact that whole DB stack - SQLA, driver, database itself - is working? To me, such kind of tests is completely useless.

> But how *a right test* could be looking?

> The solution is actually very simple. Instead of testing whole DB stack, you need to assert that your program *issues correct SQL statements* to DB. And it is where SQL constructs comparison come into play. For example, the hypothetical test for table from example above may look like this:

> from unittest import mock

> from sqlalchemy.engine import Connection


> def test_get_all_users():
    connection = mock.Mock(spec=Connection)

    assert connection.execute.called
    assert connection.execute.call_args == mock.call(select([users]))

**Comment by tribals** [comment]
This is fascinating news!

**Comment by CaselIT** [comment]
> To me, such kind of tests is completely useless.

Regardless of the merit of the issue at hand, I disagree with your statements regarding tests. In my opinion the hole point of the tests is assure that a piece of code does what it is supposed to do, ie `def insert_user(user)` should insert an used in the db. The test should not care how it does it, (to a point obviously), but that the expected result is that `user` is in the db with the correct value.

**Comment by zzzeek** [comment]
just so you know, the way SQLAlchemy asserts the SQL result of tests is by string comparison, which we've done for over a decade and is not only easier to implement but also more reliable than SQL construct comparison.    We use events like before_cursor_execute() to grab all the SQL strings as they invoke and then compare them to a list of strings we expect.    more advanced versions of this which we also use will compare the SQL strings in a database-agnostic way by re-compiling the given construct against the "default" dialect and our test suite has those.    Lots of examples of this in tests like https://github.com/sqlalchemy/sqlalchemy/blob/master/test/orm/test_unitofworkv2.py#L80 .


as far as compare(), we also use that now in test suites in 1.4 and it's quite convenient though for the industrial size tests like unit of work I think the string thing is more straightforward.    The original compare() issue is #4336 where I'm mostly kind of -1 on it as too much work (which it was) until I started working on the cache key system and realized that creates a much better rationale for writing a whole new visitor system that can do compare().

but I was wrong above, looks like the timescale for the basic compare() idea was 13 days, not months, but certainly it's been months overall for the whole caching / visit system it's at the core of.

**Comment by tribals** [comment]
This is very relevant information, thank you for details.

**Comment by zzzeek** [comment]
also, there's a whole *another" way of testing if you dont want to use a backend database which is to mock out the select() / query objects etc. and place them underneath the functional thing you're testing.   I demonstrated this in a talk years ago.  if it's bothering you to even have a database running at all you can check out what I did at https://bitbucket.org/zzzeek/pycon2014_atmcraft/src/master/atmcraft/tests/test_views_mockdb.py , eek sorry this doesnt seem to be in github, this is actually mocking the output of database calls so that test web requests actually complete.

this is not really the same thing but it's interesting in the realm of "I dont want a database to run for my tests".

hint: always have at least a "functional" test suite that does actually run the database and tests against it.

for "database running" kinds of concerns, there are now many tools that will set up database environments for you.  For some other projects I am using [pifpaf](https://pypi.org/project/pifpaf/), works great.     What a lot of people do now is simply run a container.    Docker has a nasty "must be root" requirement so you can use [podman](https://podman.io/), which is great.
