### ISSUE TITLE
Bug on documentation (Isolation level)

### ISSUE THREAD

**Issue by AnderUstarroz** [sqlalchemy/sqlalchemy#5563]
There seems to be contradictory information within the transaction isolation page on: 

- [https://docs.sqlalchemy.org/en/13/orm/session_transaction.html#session-transaction-isolation](https://docs.sqlalchemy.org/en/13/orm/session_transaction.html#session-transaction-isolation)

A valid Transaction level is defined as `'REPEATABLE READ'`, `'READ COMMITTED'`, etc..   but according the [create_engine accepted params](https://docs.sqlalchemy.org/en/13/core/engines.html#sqlalchemy.create_engine.params.isolation_level) should be actually `'REPEATABLE_READ'`,  `'READ_COMMITTED'`..

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,
Thanks for reporting this.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fix typo in :paramref:`_engine.create_engine.isolation_level` names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2218

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Fix typo in :paramref:`_engine.create_engine.isolation_level` names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2219

**Comment by AnderUstarroz** [comment]
Good work guys, but keep in mind that to be consistent the following example should also be updated:

``` 
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

eng = create_engine(
    "postgresql://scott:tiger@localhost/test",
    isolation_level='REPEATABLE READ'
)

Session = sessionmaker(eng)
```

**Comment by AnderUstarroz** [comment]
Also what about the following page?
[https://docs.sqlalchemy.org/en/14/core/connections.html#dbapi-autocommit](https://docs.sqlalchemy.org/en/14/core/connections.html#dbapi-autocommit)

**Comment by CaselIT** [comment]
Please note that the typo was on `create_engine` documentation.
The correct values are with the space in them.

The examples you linked are all correct.

**Comment by AnderUstarroz** [comment]
Understood, sorry for the misunderstanding  😉
