### ISSUE TITLE
AttributeError: 'tuple' object has no attribute '_run_visitor'

### ISSUE THREAD

**Issue by u1209855** [sqlalchemy/sqlalchemy#5577]
I have created a list of classes that are going to be converted into tables, but I'm getting the following attribute error. Is there something that I'm doing wrong? 

I have posted my question here https://stackoverflow.com/questions/63853604/trouble-constructing-tables-through-sqlalchemy
and I'm not sure if I'm doing something wrong.

Traceback (most recent call last):
  File "C:/Users/u1209855/PycharmProjects/baseball/main.py", line 6, in <module>
    m.create_models(engine)
  File "C:\Users\u1209855\PycharmProjects\baseball\models.py", line 170, in create_models
    Base.metadata.create_all(engine)
  File "C:\Users\u1209855\PycharmProjects\baseball\venv\lib\site-packages\sqlalchemy\sql\schema.py", line 4555, in create_all
    bind._run_visitor(
AttributeError: 'tuple' object has no attribute '_run_visitor'

**Versions**
 - OS: Windows
 - Python: 3.8
 - SQLAlchemy: 1.3.19
 - Database: Postgres 12
 - DBAPI: pgAdmin
 - psycopg2 2.8.6

**Comment by zzzeek** [comment]
the engine you are passing to create_all() is coming in as a tuple.    right here:
```

def main():
   engine = sqlalchemy_connect()  # returns a tuple of (engine, session)
   m.create_models(engine)
```

hope this helps!

**Comment by u1209855** [comment]
Ahh, I'm an idiot, thanks for that! Seemed to do the trick!

**Comment by u1209855** [comment]
well
