### ISSUE TITLE
Customize the behavior of .has() and .any()

### ISSUE THREAD

**Issue by taidinh-tiki** [sqlalchemy/sqlalchemy#5579]
I want to apply the relationship-related filter when writing query with optimize the performance also, is there any way to change the behavior of any() and has() method when generating the query. I have benchmarked and IN SUBQUERY or JOIN is better than EXISTS query.
Example:

`
class Product(db.Model):
    __tablename__ = "tiki_product_info"
    id = Column(Integer, primary_key=True)
    sku = Column(String(256), nullable=False)
    product_name = Column(String(1024), nullable=False)
    product_pricing = relationship("ProductPricing", uselist=False)

class ProductPricing(db.Model):
    __tablename__ = "product_pricing"
    id = Column(Integer, primary_key=True)
    product_id = Column(
        Integer,
        ForeignKey(Product.id, ondelete="CASCADE", onupdate="CASCADE"),
        unique=True,
        nullable=False,
    )
    product = relationship(
        Product.__name__,
        back_populates="product_pricing",
        lazy="select",
        uselist=False,
    )

`

`  db.session.query(Product).filter(Product.product_pricing.has()).count()`
produces the query like below:
`
SELECT count(*) AS count_1 
FROM (SELECT tiki_product_info.id AS tiki_product_info_id
FROM tiki_product_info 
WHERE EXISTS (SELECT 1 
FROM product_pricing 
WHERE tiki_product_info.id = product_pricing.product_id)) AS anon_1
`
which is not optimized in my opinion, it should be 
`SELECT count(*) AS count_1 
FROM (SELECT tiki_product_info.id AS tiki_product_info_id
FROM tiki_product_info 
WHERE id in (SELECT product_id 
FROM product_pricing)) AS anon_1`

**Comment by zzzeek** [comment]
hey there -

you can modify what has() or any() does by writing your own [comparator class](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/relationships.py#L1096) and sending it to relationship via [comparator factory](https://docs.sqlalchemy.org/en/13/orm/relationship_api.html?highlight=relationship#sqlalchemy.orm.relationship.params.comparator_factory).

the SQL you're illustrating does seem to be self-contained within the filter() clause, so feel free to submit a PR with tests that applies this optimization to has() though I cant guarantee we'd be able to accept it if it has problems that are not easy to solve.

**Comment by taidinh-tiki** [comment]
Thank you for your support @zzzeek :D
