### ISSUE TITLE
pre_ping settings not propagated when recreating pools

### ISSUE THREAD

**Issue by blackmicha** [sqlalchemy/sqlalchemy#5582]
The docs state for `Pool.recreate()`:

>  Return a new Pool, of the same class as this one and configured with identical creation arguments.

but `pre_ping`'s value (and a couple other values) is not passed to the class constructed in all classes inheriting Pool.

So if we chose to set pre_ping to True and disposed the engine, that setting defaults back to False.

engine.pool._pre_ping
Out[26]: True
engine.dispose()
engine.pool._pre_ping
Out[28]: False

**Comment by zzzeek** [comment]
I can only identify "pre_ping" and "use_lifo".  Can you indicate *all* attributes that you have observed aren't propagating?  thanks.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Pass all pool parameters in recreate()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2232

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Pass all pool parameters in recreate()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2233

**Comment by blackmicha** [comment]
what about events?

**Comment by zzzeek** [comment]
events are propagiated via the "dispatch" that goes along with the pool.  plenty of tests for that:


https://github.com/sqlalchemy/sqlalchemy/blob/master/test/engine/test_pool.py#L417
https://github.com/sqlalchemy/sqlalchemy/blob/master/test/engine/test_pool.py#L426
https://github.com/sqlalchemy/sqlalchemy/blob/master/test/engine/test_pool.py#L449
https://github.com/sqlalchemy/sqlalchemy/blob/master/test/engine/test_pool.py#L459
https://github.com/sqlalchemy/sqlalchemy/blob/master/test/engine/test_pool.py#L481
https://github.com/sqlalchemy/sqlalchemy/blob/master/test/engine/test_pool.py#L565
