### ISSUE TITLE
Adding `copy` mode for psycopg2 executemany_mode to accelerate data import

### ISSUE THREAD

**Issue by haobibo** [sqlalchemy/sqlalchemy#5585]
Currently, in v1.4, sqlalchemy supports modes like `batch`, `values_only`, and so on, which allow INSERT statements to execute in batch mode.

Given that PostgreSQL supports `COPY FROM` and it is believed that using COPY is usually faster than `INSERT INTO xx VALUES`, it is supposed we can get better performance to use COPY FROM to perform data batch insertion.

 - Here is an example: https://stackoverflow.com/questions/43317376/how-can-i-use-psycopg2-extras-in-sqlalchemy

So do you think it is feasible and convenient to implement a COPY mode for psycopg2 dialect to use COPY FROM for insertion operations?

https://www.psycopg.org/docs/usage.html#using-copy-to-and-copy-from

**Comment by zzzeek** [comment]
hi there -

COPY mode is a bulk utility command, not a general use SQL construct and would not be appropriate as an implementation of SQL INSERT.    

when using SQLAlchemy, psycopg2's copy() interface is fully available by using the connection directly as documened at https://docs.sqlalchemy.org/en/13/core/connections.html#working-with-raw-dbapi-connections .

**Comment by haobibo** [comment]
got. thank you for the info.
