### ISSUE TITLE
Additional argument named 'before_commit' and 'after_commit' for session.__init__

### ISSUE THREAD

**Issue by sreerajkksd** [sqlalchemy/sqlalchemy#5588]
**Is your feature request related to a problem? Please describe.**
I would like to extend session.commit to add an entry in another table for implementing change-logs for all tables present in the schema.

**Describe the solution you'd like**
Add additional arguments while initiating session namely before_commit and after_commit. These functions will be invoked before and after performing commit operations. 

**Describe alternatives you've considered**
Extending session.commit is another option but adding this feature natively would be useful for a lot of people around.

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

I think that this use case is supposed to be covered by events: https://docs.sqlalchemy.org/en/13/orm/events.html#session-events

Is your use case not covered by them?

**Comment by sreerajkksd** [comment]
yeah, that would be good enough. We can close this issue. 👍

**Comment by CaselIT** [comment]
Ok!
Feel free to reopen if you have a use case that is currently not supported by the event system.
