### ISSUE TITLE
python3.8 v1.3.19  sqlserver 2012 raise error Could not locate column in row for column xxxx

### ISSUE THREAD

**Issue by grays820** [sqlalchemy/sqlalchemy#5591]
sqlalchemy.version : 1.3.19
python version: 3.8.5
sqlserver 2012 version:11.0.3128.0

any_index_page.sid is primary key and autoinc ,
the table any_index_page have 10 field.
my code is  like above,

```
Session = sessionmaker(bind=engine)
s = Session()
o = any_index_page()
o.f1 = ''
o.f2=''
...
s.add(o)
s.commit() <---- raise error here

```
but wried is , i have 10 field in this table, if i set 4 field ,it will raise error. but if i set more filed value ,this code work fine...

<class 'sqlalchemy.exc.NoSuchColumnError'>
"Could not locate column in row for column 'any_index_page.sid'"

<FrameSummary file /Users/grays/Workspace/AnyCloud/backend/any/module/dbp/module_db.py, line 540 in module_data_save>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 1042 in commit>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 504 in commit>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 483 in _prepare_impl>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 2523 in flush>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 2664 in _flush>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\util\langhelpers.py, line 68 in __exit__>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\util\compat.py, line 182 in raise_>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 2624 in _flush>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\unitofwork.py, line 422 in execute>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\unitofwork.py, line 586 in execute>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\persistence.py, line 239 in save_obj>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\persistence.py, line 1135 in _emit_insert_statements>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\base.py, line 1011 in execute>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\sql\elements.py, line 298 in _execute_on_connection>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\base.py, line 1124 in _execute_clauseelement>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\base.py, line 1316 in _execute_context>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\base.py, line 1514 in _handle_dbapi_exception>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\util\compat.py, line 182 in raise_>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\base.py, line 1294 in _execute_context>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\default.py, line 1249 in _setup_crud_result_proxy>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\default.py, line 1314 in _setup_ins_pk_from_implicit_returning>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\default.py, line 1315 in <listcomp>>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\result.py, line 681 in _key_fallback>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\util\compat.py, line 182 in raise_>

this code work fine with sqlserver 2019

**Comment by grays820** [comment]
but it work fine with sqlserver 2019

**Comment by zzzeek** [comment]
hey there - 

I have no way to reproduce this error.   can you please run it with SQL echoing turned on and send over the INSERT statement that is emitted right before this error is raised.    if you turn on echo='debug' on your engine it will also show the rows returned.

the error indicates that the INSERT used RETURNING but the requested column is not actually returned.  

is it possible the names of the columns on your SQL Server 2012 database are different and not matching up to your model ?

**Comment by grays820** [comment]
> hey there -
> 
> I have no way to reproduce this error. can you please run it with SQL echoing turned on and send over the INSERT statement that is emitted right before this error is raised. if you turn on echo='debug' on your engine it will also show the rows returned:
> 
> ```
> engine = create_engine("mssql://<engine>", echo='debug')
> ```
> 
> the error indicates that the INSERT used RETURNING but the requested column is not actually returned.
> 
> is it possible the names of the columns on your SQL Server 2012 database are different and not matching up to your model ?
> 
> also share which database driver you're using and the version, thanks

TKS for answer

table model define 
```
class any_index_page(Base):
    __tablename__ = 'any_index_page'
    __table_args__ = ({'extend_existing': True})

    sid = Column(Integer, nullable=False, index=True, primary_key=True)
    rid = Column(Unicode(36), nullable=False, index=True)
    uid = Column(Unicode(36), index=True)
    ctime = Column(DateTime, server_default=text('(getdate())'), index=True)
    mtime = Column(DateTime, server_default=text('(getdate())'))

    has_att = Column(BIT,  server_default=text("((0))"))

    item_text = Column(Unicode(200),  server_default=text("('')"))
    item_url = Column(Unicode(200),  server_default=text("('')"))
    item_detail = Column(UnicodeText(), server_default=text("('')"))
    item_pic = Column(Unicode(200),  server_default=text("('')"))
    item_site = Column(Unicode(80),  server_default=text("('')"))
    item_site_url = Column(Unicode(200),  server_default=text("('')"))
    item_author = Column(Unicode(50),  server_default=text("('')"))
    item_time = Column(DateTime )
    item_type = Column(Unicode(50),  server_default=text("('')"))
```

error trace log

```

2020-09-17 09:31:14,136 INFO sqlalchemy.engine.base.Engine.any BEGIN (implicit)
2020-09-17 09:31:14 - log log.py info:110 - sqlalchemy.engine.base.Engine.any - BEGIN (implicit)
2020-09-17 09:31:14,137 INFO sqlalchemy.engine.base.Engine.any INSERT INTO any_index_page (rid, uid, item_text, item_url, item_time, item_type) OUTPUT inserted.sid VALUES (%(rid)s, %(uid)s, %(item_text)s, %(item_url)s, %(item_time)s, %(item_type)s)
2020-09-17 09:31:14 - log log.py info:110 - sqlalchemy.engine.base.Engine.any - INSERT INTO any_index_page (rid, uid, item_text, item_url, item_time, item_type) OUTPUT inserted.sid VALUES (%(rid)s, %(uid)s, %(item_text)s, %(item_url)s, %(item_time)s, %(item_type)s)
2020-09-17 09:31:14,137 INFO sqlalchemy.engine.base.Engine.any {'rid': '4e75e61c-7504-27ee-1b1c-61f73875b499', 'uid': 'a47d33ac-f6f7-11ea-aa81-0cc47a07b7b1', 'item_text': '1', 'item_url': '1', 'item_time': '2020-09-17 09:31:02', 'item_type': '头条'}
2020-09-17 09:31:14 - log log.py info:110 - sqlalchemy.engine.base.Engine.any - {'rid': '4e75e61c-7504-27ee-1b1c-61f73875b499', 'uid': 'a47d33ac-f6f7-11ea-aa81-0cc47a07b7b1', 'item_text': '1', 'item_url': '1', 'item_time': '2020-09-17 09:31:02', 'item_type': '头条'}
2020-09-17 09:31:14,140 INFO sqlalchemy.engine.base.Engine.any ROLLBACK
2020-09-17 09:31:14 - log log.py info:110 - sqlalchemy.engine.base.Engine.any - ROLLBACK
<class 'sqlalchemy.exc.NoSuchColumnError'>
"Could not locate column in row for column 'any_index_page.sid'"

<FrameSummary file /Users/grays/Workspace/AnyCloud/backend/any/module/dbp/module_db.py, line 540 in module_data_save>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 1042 in commit>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 504 in commit>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 483 in _prepare_impl>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 2523 in flush>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 2664 in _flush>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\util\langhelpers.py, line 68 in __exit__>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\util\compat.py, line 182 in raise_>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\session.py, line 2624 in _flush>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\unitofwork.py, line 422 in execute>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\unitofwork.py, line 586 in execute>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\persistence.py, line 239 in save_obj>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\orm\persistence.py, line 1135 in _emit_insert_statements>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\base.py, line 1011 in execute>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\sql\elements.py, line 298 in _execute_on_connection>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\base.py, line 1124 in _execute_clauseelement>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\base.py, line 1316 in _execute_context>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\base.py, line 1514 in _handle_dbapi_exception>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\util\compat.py, line 182 in raise_>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\base.py, line 1294 in _execute_context>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\default.py, line 1249 in _setup_crud_result_proxy>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\default.py, line 1314 in _setup_ins_pk_from_implicit_returning>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\default.py, line 1315 in <listcomp>>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\engine\result.py, line 681 in _key_fallback>
<FrameSummary file c:\python38\lib\site-packages\sqlalchemy\util\compat.py, line 182 in raise_>
INFO:     221.12.48.19:64116 - "POST /api/db/module/data/set HTTP/1.1" 200 OK
```

set more field successed  sql trace log
```

2020-09-17 09:32:33 - log log.py info:110 - sqlalchemy.engine.base.Engine.any - BEGIN (implicit)
2020-09-17 09:32:33,484 INFO sqlalchemy.engine.base.Engine.any INSERT INTO any_index_page (rid, uid, item_text, item_url, item_detail, item_pic, item_time, item_type) OUTPUT inserted.sid VALUES (%(rid)s, %(uid)s, %(item_text)s, %(item_url)s, %(item_detail)s, %(item_pic)s, %(item_time)s, %(item_type)s)
2020-09-17 09:32:33 - log log.py info:110 - sqlalchemy.engine.base.Engine.any - INSERT INTO any_index_page (rid, uid, item_text, item_url, item_detail, item_pic, item_time, item_type) OUTPUT inserted.sid VALUES (%(rid)s, %(uid)s, %(item_text)s, %(item_url)s, %(item_detail)s, %(item_pic)s, %(item_time)s, %(item_type)s)
2020-09-17 09:32:33,485 INFO sqlalchemy.engine.base.Engine.any {'rid': '4e75e61c-7504-27ee-1b1c-61f73875b499', 'uid': 'a47d33ac-f6f7-11ea-aa81-0cc47a07b7b1', 'item_text': '1', 'item_url': '1', 'item_detail': '2', 'item_pic': '', 'item_time': '2020-09-17 09:31:02', 'item_type': '头条'}
2020-09-17 09:32:33 - log log.py info:110 - sqlalchemy.engine.base.Engine.any - {'rid': '4e75e61c-7504-27ee-1b1c-61f73875b499', 'uid': 'a47d33ac-f6f7-11ea-aa81-0cc47a07b7b1', 'item_text': '1', 'item_url': '1', 'item_detail': '2', 'item_pic': '', 'item_time': '2020-09-17 09:31:02', 'item_type': '头条'}
2020-09-17 09:32:33,487 INFO sqlalchemy.engine.base.Engine.any COMMIT
2020-09-17 09:32:33 - log log.py info:110 - sqlalchemy.engine.base.Engine.any - COMMIT
INFO:     221.12.48.19:64215 - "POST /api/db/module/data/set HTTP/1.1" 200 OK

```

**Comment by zzzeek** [comment]
ok here are three things to try:

1. use pyodbc, pymssql is unfortunately unmaintained.

2. are there any triggers on this table?   triggers will prevent this particular insert id method from working, you would have to set implicit_returning to false

3. send implicit_returning=False to the engine, or you can also do this on a per-table basis.    create_engine("mssql://....", implicit_returning=False)

**Comment by grays820** [comment]
> ok here are three things to try:
> 
> 1. use pyodbc, pymssql is unfortunately unmaintained.
> 2. are there any triggers on this table?   triggers will prevent this particular insert id method from working, you would have to set implicit_returning to false
> 3. send implicit_returning=False to the engine, or you can also do this on a per-table basis.    create_engine("mssql://....", implicit_returning=False)

I change pymssql to pyodbc , it work fine now, thanks a a lot!

**Comment by zzzeek** [comment]
I'm guessing this one stopped at implicit_returning=False.  That's fine, though I did not expect this to fail on SQL server 2012.   closing for now.
