### ISSUE TITLE
Use of the term 'slave'

### ISSUE THREAD

**Issue by shiftbreak** [sqlalchemy/sqlalchemy#5595]
The file `sqlalchemy/testing/plugin/pytestplugin.py` includes the term 'slave' which is considered oppressive language by the IETF:

https://tools.ietf.org/id/draft-knodel-terminology-00.html

**Comment by zzzeek** [comment]
hi there -

I believe you are looking at outdated code as that terminiology is fully removed from the SQLAlchemy project including from the current 1.3.19 release.   

Original change for remaining terminology was #5381 resolved in 3512d51600c250f729 .   this removed the term from documentation and everywhere that was feasible.

for pytestplugin,  that file was making use of third party API that we had no control over until they provided new names.  They provided new names as an option but did not inform anyone they had done so.   when we found out, we were very happy to make this final change in f91d335e31e5e14794e349b7.  

as you appear to be looking at a stale version of the file, there is unfortunately no methodology that may be used for older git commits or for .tar.gz distribution files that are already out there, 

thanks!
