### ISSUE TITLE
Misleading documentation using `assert` statement for validation

### ISSUE THREAD

**Issue by wyfo** [sqlalchemy/sqlalchemy#5596]
[Validators documentation](https://docs.sqlalchemy.org/en/13/orm/mapped_attributes.html#simple-validators) presents validators using `assert` statement to validate data. However, `assert` is a [*debug* statement](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement), which is disabled (and then validation using it) when run in optimized mode.

`assert` should only be used to ensure already trusted data, but I assume this is not the principal use case.
That's why the documentation should be updated to replace this statement by raising a `ValueError` instead. A note could be added to explain why `assert` is not the statement you should use in validation, excepted if you know what you are doing.

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting this. If you want to provide a pull request, that would be great

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Fixes: #5596** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3071
