### ISSUE TITLE
MSSQL dialect can't detect temp table.

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [sqlalchemy/sqlalchemy#5597]
**Describe the bug**
When creating a temporary table I can't detect it when I run .has_table() as it returns  `False`. I can see some work has been done on detecting temp tables in https://github.com/sqlalchemy/sqlalchemy/issues/5506 but it doesn't look like this is covered.

**Expected behavior**
That `.has_table()` returns `True`

**To Reproduce**

```py
conn = engine.connect()
stmt= """
CREATE TABLE #my_table
(
    col1 VARCHAR(50),
    col2 int
)
"""
conn.execute(sql)
conn.dialect.has_table(conn,"#my_table")

```

**Versions.**
 - OS: Windows
 - Python: 3.8.2
 - SQLAlchemy: 1.3.17
 - Database: SQL Server 14
 - DBAPI: PyODBC
 - Driver: ODBC Driver 17 for SQL Server

**Comment by gordthompson** [comment]
Thanks for reporting this. I will investigate.

**Comment by zzzeek** [comment]
the temp table reflection feature is in 1.4.     so...this would be targeted at 1.4.   @thomasfrederikhoeck were you testing against git master?

**Comment by gordthompson** [comment]
@zzzeek - Oops, sorry. I forgot we changed that.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix has_table() for mssql temporary tables** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2246
