### ISSUE TITLE
Fix SQLAlchemyError.__str__ returning non-string objects

### ISSUE THREAD

**Issue by Neob91** [sqlalchemy/sqlalchemy#5599]
**Describe the bug**
When passing non-string values into `SQLAlchemyError`, and then converting the resulting exception into string, an error is raised. Check *To Reproduce* for code example.

That's because `SQLAlchemyError.__str__` doesn't convert the argument to string before returning it.
It works correctly for `Exception`.

```py
>>> class Foo(object):
...     pass
>>> str(Exception(Foo()))
'<__main__.Foo object at 0x7f3235b8e470>'
```

We should restore compatibility with `Exception`.

**Expected behavior**
Converting `SQLAlchemyError` should always work (unless the argument's `__str__` method fails).
Example:
```py
>>> from sqlalchemy.exc import SQLAlchemyError
>>> class Foo(object):
...     pass
>>> str(SQLAlchemyError(Foo()))
'<__main__.Foo object at 0x7f3235b8e470>'
```

**To Reproduce**

```py
>>> from sqlalchemy.exc import SQLAlchemyError
>>> class Foo(object):
...     pass
>>> str(SQLAlchemyError(Foo()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __str__ returned non-string (type Foo)
```

**Error**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __str__ returned non-string (type Foo)
```

**Versions.**
 - OS: all
 - Python: all
 - SQLAlchemy: 1.3.13
 - Database: N/A
 - DBAPI: N/A

**Additional context**
The issue was discovered when using `sqlalchemy-redshift` - it uses `NoSuchTableError(RelationKey(...))`.
Converting `RelationKey` to string actually results in the table name, so doing `str(NoSuchTableError(RelationKey("foo", "bar")))` should result in `bar.foo`, but it raises an error.

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Andrzej Bartosiński** has proposed a fix for this issue in the **master** branch:

**Stringify correctly for non-str exception argument** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2247

**Comment by sqla-tester** [comment]
**Andrzej Bartosiński** has proposed a fix for this issue in the **rel_1_3** branch:

**Stringify correctly for non-str exception argument** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2250
