### ISSUE TITLE
remove negative indexes thing in 2.0

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5606]
There's a super awkard "-1" hardcoded in Query found in #5605:

            if item == -1:
                return list(self)[-1]
            else:
                return list(self[item : item + 1])[0]

basically all the negative indexes just load the whole result in and slice it, I think, still looking.  loading the whole result is not what anybody wants and I dont see any way to generalize this.   the whole "sliced" thing is also not present in 2.0 style querying, so here we are basically affecting legacy Query as well as dynamic AppenderQuery which we haven't really found any way to remove in 2.0.

**Comment by zzzeek** [comment]
yeah there is additional logic that omits limit/offset entirely, and asks if we can use count, which we can't:
```

  # perhaps we should execute a count() here so that we
  # can still use LIMIT/OFFSET ?
   elif (isinstance(start, int) and start < 0) or (
                isinstance(stop, int) and stop < 0
            ):
                return list(self)[item]

```
that's a full scan stuck in there.  this has to warn.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Deprecate negative slice indexes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2257
