### ISSUE TITLE
ProxiedDictMixin incorrect truthy value when there are no properties defined

### ISSUE THREAD

**Issue by pjcunningham** [sqlalchemy/sqlalchemy#5609]
**Describe the bug**

[`ProxiedDictMixin`](https://github.com/sqlalchemy/sqlalchemy/blob/1e1a38e7801f410f244e4bbb44ec795ae152e04e/examples/vertical/dictlike.py#L36) overrides `__len__`. This causes the truthy value of a model to be `False` when the proxied dictionary is empty.

**Expected behavior**

A test for truthy should return true even when the proxied dictionary is empty.

**To Reproduce**

With reference to the [example code](https://github.com/sqlalchemy/sqlalchemy/blob/1e1a38e7801f410f244e4bbb44ec795ae152e04e/examples/vertical/dictlike.py#L121):

```py

    stoat = Animal("stoat")

    session.add(stoat)
    session.commit()

    # at this point stoat has no properties set
    print(f"Length of stoat: {len(stoat)}")

    if stoat:
        # error. stoat is not truthy because _proxied has no length
        print('Stoat is a truthy') # Never gets printed

    # add some properties

    stoat["color"] = "red"
    stoat["cuteness"] = 7
    stoat["weasel-like"] = True

    session.commit()

    # at this point stoat HAS properties set

    print(f"Length of stoat: {len(stoat)}")
    if stoat:
        print('Stoat is a truthy - printed')

```

**Error**

```
# There is no stack trace
```

**Versions.**
 - OS: Windows 10
 - Python: 3.8.5
 - SQLAlchemy: 1.3.19
 - Database: SQLite
 - DBAPI:

**Additional context**

`ProxiedDictMixin` should have `__bool__` defined.

```py
class ProxiedDictMixin(object):
    """Adds obj[key] access to a mapped class.

    This class basically proxies dictionary access to an attribute
    called ``_proxied``.  The class which inherits this class
    should have an attribute called ``_proxied`` which points to a dictionary.

    """

    def __len__(self):
        return len(self._proxied)

    def __bool__(self):
        return True

    def __iter__(self):
        return iter(self._proxied)

    def __getitem__(self, key):
        return self._proxied[key]

    def __contains__(self, key):
        return key in self._proxied

    def __setitem__(self, key, value):
        self._proxied[key] = value

    def __delitem__(self, key):
        del self._proxied[key]
```

**Comment by CaselIT** [comment]
Hi,

I guess that this depends if you consider a `ProxiedDictMixin` class as a dict or not. An empty dict evaluates to False

**Comment by pjcunningham** [comment]
Hello Federico.

What would you expect `if stoat` to evaluate to when there are no properties defined?

Cheers, Paul.

**Comment by CaselIT** [comment]
It really depends if the expected behaviour of the class it to be used as a `dict`, so a class without proprieties would evaluate to False, or more like a class with a convenient way of setting additional properties, in this second case it would evaliate to True even with no additional property.

Either way a clarification in the documentation seems warranted

**Comment by zzzeek** [comment]
this is an example class, it's not a supported / tested API.  you can modify it to work any way you'd like.

**Comment by pjcunningham** [comment]
Hello Fredrico,

Thanks for your comments. I moved the `__bool__` method out of the `ProxiedDictMixin` and into the `Animal` class.

Cheers, Paul
