### ISSUE TITLE
unable to get or set column after using ALTER to add a new column to a postgresql table; explicitly initializing the column across all rows "fixes" the issue

### ISSUE THREAD

**Issue by mzpqnxow** [sqlalchemy/sqlalchemy#5611]
There's an issue that I believe is a bug in SQLAlchemy, but I'm not entirely sure. Maybe it's expected behavior? It seems wrong to me though.

## Description

If you add a new column to a table in the PostgreSQL command line- in my case, it's type `TEXT`- which I describe in the model class as `Text`- but do not then explicitly set some value to that column across the whole table after the `ALTER` command, SQLAlchemy query results will not have this new column present, even if they have been added to the model. Additionally, assigning to the column for an `UPDATE` has no effect, it just silently doesn't update that specific column

## Reproducing

Create a table in PostgreSQL like this:

```
CREATE TABLE test_table (
    id BIGSERIAL NOT NULL,
    somecolumn TEXT
);
```

Insert a few rows, they can have any values ...

```
INSERT INTO test_table(somecolumn) VALUES('somevalue');
```

Create a model for the table:

```
class TestTable(Base):
    __tablename__ = 'test_table'
    id = Column(BigInteger, nullable=False, index=True, server_default=text("nextval('test_table_id_seq'::regclass)"))
    somecolumn = Column(Text)
```

Test an `UPDATE`:

```
for row in session.query(TestTable):
    row.somecolumn = "TEST1"
    session.commit()
```

This works, the `somecolumn` value is set to `"TEST1"`, as expected.

Now, add a new column of type `TEXT` to the table- I suspect any type will have this behavior, but I haven't tested others

```
ALTER TABLE test_table ADD COLUMN test_column TEXT
```

Update the model:

```
class TestTable(Base):
    __tablename__ = 'test_table'

    id = Column(BigInteger, nullable=False, index=True, server_default=text("nextval('test_table_id_seq'::regclass)"))
    somecolumn = Column(Text)
    test_column = Column(Text)
```

Now, query the table:

```
for row in session.query(TestTable):
    row.somecolumn = "TEST1"
    row.test_column = "TEST2"
    session.commit()
```

You'll see that the `somecolumn` column is updated, but the `test_column` is not

Another way to identify this behavior (this is how I tracked the issue down) is by reading from the row, without updating. You can detect the behavior using `getattr` on the row. The following example wil raise a `RuntimeError` on the `test_column` conditional, but not on the `somecolumn` conditional:

```
for row in session.query(TestTable):
    if getattr(row, 'somecolumn', None) is None:
        # This case doesn't happen
        raise RuntimeError('somecolumn is missing')
    if getattr(row, 'test_column', None) is None:
        # This case fires
        raise RuntimeError('test_column is missing')
```

To "fix" this behavior, you can do the following after the `ALTER` command:

```
UPDATE test_table set test_column = '';
```

Now, run the query to update the values again. You'll see that this time, the `test_column` receives the value as expected (and is also readable with `getattr()`

Is this behavior expected? I'm new to ORMs so I'm not familiar with any quirks. I'm also not very experienced with PostgreSQL (or any RDBMS in general) so maybe this is a known issue, where new columns must be initialized to some value before being used?

I have a workaround (which is probably a best practice anyway) so this isn't a blocker or anything. But I'm curious if it's a SQLAlchemy issue that should be fixed.

## Versions

**Versions.**
 - OS: Linux
 - Python: 3.7
 - SQLAlchemy:1.3.19
 - Database:PostgreSQL 10

**Comment by zzzeek** [comment]
hey there -

thanks for the great detail here.   unfortunately though all the details that would actually shed light on what's happening here are missing :)   :  

1. when you say "update the model",  how are you doing that? are you modifying the source code of your program and then running it again?  or are you runtime monkeypatching, or making a new class, or... ?   

2. when you say "alter table", is that at the psql command prompt?  is that in the same program?  are you committing the transaction ?

3. when you then go to refetch the data, are you working in a new transaction?   if you ALTER a table in a different transaction and then continue in the one you're already running, things aren't going to work necessarily. The ORM object itself will almost definitely not have the correct state if it was left around in memory before the table was altered.


Overall, the fragments above don't tell me how they are interacting together and that's the important part.  above all, setting "echo='debug'" on your create_engine() will show exactly the SQL being emitted and the result rows being received, so as you do your interaction, watch that SQL and results to ensure everything you see is what you'd expect.  that's where you will see whatever is not what you think it should be.  thanks!

**Comment by mzpqnxow** [comment]
Eek. Sorry, let me add some more clarity-

Update the model- I'm just referring to adding the field to the class. After that, I run the program again.

Alter table- yep, this is via `psql` command-line, so it takes effect immediately. Just using:

```
ALTER TABLE the_table ADD COLUMN the_column TEXT;
```

When I refetch the data it is whole new execution of the program. So the issue really should not be anything to do with transactions not getting flushed/committed

I actually did add `echo='debug'` though I admittedly did not look very deeply at it. The mangled up mess that ORMs produce (no offense!) can be pretty horrid to decipher. But you're certinaly right, there must be something there.

The whole thing really doesn't make sense to make- the first things I would have made certain of are exactly what you were checking in those first few questions- is this a matter of the table not _actually_ getting updated. But the process that I'm using (with separate invocations of everything, not using `BEGIN` in the cli or anything like that seem to rule that out.

I'll update this after taking a look. If I can't make sense of it I will paste the underlying SQL here

Thanks for the swift response

**Comment by mzpqnxow** [comment]
Closing this as the cause appears to be (embarrassing) pilot error

The class I was updating was in the wrong file, my app was importing from a file with an older version of the class that didn’t know about several fields that were added later. This became obvious when I looked carefully at the SELECT statement that was generated by sqlalchemy. Sorry for the wasted time. I’m closing this
