### ISSUE TITLE
PEP-567 context variable is not always set with async engine

### ISSUE THREAD

**Issue by fantix** [sqlalchemy/sqlalchemy#5615]
**Describe the bug**

After greenlet 0.4.17 supports PEP-567 in python-greenlet/greenlet#172, SQLAlchemy async engine is not setting the context correctly in `greenlet_spawn()`, causing bugs in retrieving context variables in sync methods like event handlers.

**Expected behavior**

The context is passed down and context variables are working properly, please see example below.

**To Reproduce**

```py
import asyncio
from contextvars import ContextVar

from sqlalchemy import event
from sqlalchemy.ext.asyncio import create_async_engine

var = ContextVar("var", default="default")


def on_connect(dbapi_connection, connection_record):
    print(var.get())


async def main():
    e = create_async_engine("postgresql+asyncpg:///")
    event.listen(e.sync_engine, "connect", on_connect)

    var.set("expected")
    async with e.connect():
        pass


asyncio.run(main())
```

**Expected**: `expected`

**Actual**: `default`

**Versions.**

 - OS: Darwin Kernel Version 19.5.0
 - Python: Python 3.8.2
 - SQLAlchemy: 1.4.0b1 @ ffafbd4b9657a4ee8bec57c0861414144f37bdc5
 - Database: PostgreSQL 12.4
 - DBAPI: asyncpg 0.21.0
 - greenlet: 0.4.17

**Additional context**

Async methods called from such sync methods by `await_only()` is not affected, because the async method is actually called within the parent greenlet, where the PEP-567 context is correct. For example, this would generate `expected`:

```python
async def async_on_connect():
    print(var.get())

def on_connect(dbapi_connection, connection_record):
    await_only(async_on_connect())
```

**Have a nice day!**

**Comment by zzzeek** [comment]
correct me if I'm wrong the idea is that greenlet does not assume that when you switch greenlets, that you would want contextvars to remain in the same context ?

**Comment by zzzeek** [comment]
specifically the thing happening in the PR looks like it may reduce performance?  it looks like contextvars is at least written in C.

**Comment by fantix** [comment]
> greenlet does not assume that when you switch greenlets, that you would want contextvars to remain in the same context

You are right, similar to `asyncio.Task`, greenlets run in their own *contexts*. Switching between `asyncio.Task` or greenlets would cause literally the PEP-567 *context* switch too.

The difference between `asyncio.Task` and greenlet is, a new `asyncio.Task` will inherit the context from where it's created:

[python/cpython: Lib/asyncio/tasks.py](https://github.com/python/cpython/blob/d9ab95ff1fe81efdf70e545d536d9f6927d1ba81/Lib/asyncio/tasks.py#L134)
```python
class Task(futures._PyFuture):
    def __init__(self, coro, *, loop=None, name=None):
        ...
        self._context = contextvars.copy_context()
```

Or the C version:

[python/cpython: Modules/_asynciomodule.c](https://github.com/python/cpython/blob/d9ab95ff1fe81efdf70e545d536d9f6927d1ba81/Modules/_asynciomodule.c#L2079)
```c
static int
_asyncio_Task___init___impl(TaskObj *self, PyObject *coro, PyObject *loop,
                            PyObject *name)
{
    ...
    Py_XSETREF(self->task_context, PyContext_CopyCurrent());
```

But greenlets start fresh with an empty context (`NULL`, no initial value set):

[python-greenlet/greenlet: greenlet.h](https://github.com/python-greenlet/greenlet/blob/71ecaa8188894dccdf35351614e65f07752c2414/greenlet.h#L50-L52)
```c
typedef struct _greenlet {
    ...
	PyObject* context;
} PyGreenlet;
```

Therefore we needed the extra `contextvars.copy_context()`, which is the same C implementation:

[python/cpython: Modules/_contextvarsmodule.c](https://github.com/python/cpython/blob/d9ab95ff1fe81efdf70e545d536d9f6927d1ba81/Modules/_contextvarsmodule.c#L15-L20)
```c
static PyObject *
_contextvars_copy_context_impl(PyObject *module)
{
    return PyContext_CopyCurrent();
}
```

(I think new greenlets should call this by default, but looks like they decided the opposite way that greenlets are more like threads (start fresh) than tasks (inherit context). There was a similar discussion even before PEP-567 in GINO: python-gino/gino#84)

> specifically the thing happening in the PR looks like it may reduce performance?

So other than the tuple concatenation, I'd expect the performance impact to be minimal. The `PyContext_CopyCurrent()` function itself doesn't really copy - because the underlying dictionary is immutable:

[python/cpython: Python/context.c](https://github.com/python/cpython/blob/cde283d16d87024f455e45c6f1b4e4f7d8905836/Python/context.c#L391-L404)
```c
PyObject *
PyContext_CopyCurrent(void)
{
    PyContext *ctx = context_get();
    if (ctx == NULL) {
        return NULL;
    }

    return (PyObject *)context_new_from_vars(ctx->ctx_vars);
}

static PyContext *
context_new_from_vars(PyHamtObject *vars)
{
    PyContext *ctx = _context_alloc();
    if (ctx == NULL) {
        return NULL;
    }

    Py_INCREF(vars);
    ctx->ctx_vars = vars;

    _PyObject_GC_TRACK(ctx);
    return ctx;
}
```

https://www.python.org/dev/peps/pep-0567/#implementation

> The Context mapping is implemented using an immutable dictionary. This allows for a O(1) implementation of the copy_context() function.

**Comment by zzzeek** [comment]
why would the greenlet devs make a hard assumption like this rather than supplying a flag "inherit_context=True" ?   that would both make it easier for us to solve and also act as an alert to people learning to use greenlet that this is a choice that has to be made when spawning greenlets.

**Comment by CaselIT** [comment]
seems to be a fairly new thing the change in greenlet. Maybe they could be open to support that flag, having it default to `False` to keep the current behaviour?

**Comment by fantix** [comment]
Yeah, I wrote a patch yesterday, will create a PR tonight:

```patch
diff --git a/greenlet.c b/greenlet.c
index 3f2ac67..166c50d 100644
--- a/greenlet.c
+++ b/greenlet.c
@@ -904,9 +904,10 @@ static int green_init(PyGreenlet *self, PyObject *args, PyObject *kwargs)
 {
 	PyObject *run = NULL;
 	PyObject* nparent = NULL;
-	static char *kwlist[] = {"run", "parent", 0};
-	if (!PyArg_ParseTupleAndKeywords(args, kwargs, "|OO:green", kwlist,
-	                                 &run, &nparent))
+	PyObject* context = NULL;
+	static char *kwlist[] = {"run", "parent", "context", 0};
+	if (!PyArg_ParseTupleAndKeywords(args, kwargs, "|OOO:green", kwlist,
+	                                 &run, &nparent, &context))
 		return -1;

 	if (run != NULL) {
@@ -915,6 +916,24 @@ static int green_init(PyGreenlet *self, PyObject *args, PyObject *kwargs)
 	}
 	if (nparent != NULL && nparent != Py_None)
 		return green_setparent(self, nparent, NULL);
+
+    if (context != NULL) {
+        if (PyBool_Check(context)) {
+            if (context == Py_True)
+                self->context = PyContext_CopyCurrent();
+        }
+        else if (PyContext_CheckExact(context)) {
+            self->context = context;
+            Py_INCREF(context);
+        }
+        else if (context != Py_None) {
+            PyErr_SetString(PyExc_AttributeError,
+                            "context must be either a bool or None, "
+                            "or a Context instance");
+            return -1;
+        }
+    }
+
 	return 0;
 }

@@ -1558,11 +1577,14 @@ PyTypeObject PyGreenlet_Type = {
 	0,                                      /* tp_setattro */
 	0,                                      /* tp_as_buffer*/
 	Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE | GREENLET_GC_FLAGS, /* tp_flags */
-	"greenlet(run=None, parent=None) -> greenlet\n\n"
+	"greenlet(run=None, parent=None, context=None) -> greenlet\n\n"
 	"Creates a new greenlet object (without running it).\n\n"
 	" - *run* -- The callable to invoke.\n"
-	" - *parent* -- The parent greenlet. The default is the current "
-	"greenlet.",                            /* tp_doc */
+	" - *parent* -- The parent greenlet. The default is the current greenlet.\n"
+	" - *context* -- A PEP-567 context to run the greenlet. The default None \n"
+	"                or False means to start with an empty context, while \n"
+	"                True means to copy from current "
+	"context. ",                            /* tp_doc */
 	(traverseproc)GREENLET_tp_traverse,     /* tp_traverse */
 	(inquiry)GREENLET_tp_clear,             /* tp_clear */
 	0,                                      /* tp_richcompare */
diff --git a/tests/test_contextvars.py b/tests/test_contextvars.py
index 43c1289..33dd4cc 100644
--- a/tests/test_contextvars.py
+++ b/tests/test_contextvars.py
@@ -5,6 +5,7 @@ from greenlet import GREENLET_USE_CONTEXT_VARS
 import unittest

 if GREENLET_USE_CONTEXT_VARS:
+    from contextvars import Context
     from contextvars import ContextVar
     from contextvars import copy_context

@@ -31,16 +32,13 @@ if GREENLET_USE_CONTEXT_VARS:

             lets = [
                 greenlet(partial(
-                    partial(
-                        copy_context().run,
-                        self._increment
-                    ) if propagate else self._increment,
+                    self._increment,
                     greenlet_id=i,
                     ctx_var=id_var,
                     callback=callback,
                     counts=counts,
                     expect=0 if propagate else None,
-                ))
+                ), context=propagate)
                 for i in range(1, 5)
             ]

@@ -66,3 +64,29 @@ if GREENLET_USE_CONTEXT_VARS:
             # interpreter emits:
             # RuntimeError: cannot exit context: thread state references a different context object
             let1.switch()
+
+        def test_context_kwarg(self):
+            var = ContextVar("var", default=123)
+
+            ctx = Context()
+            ctx.run(var.set, 456)
+
+            self.assertEqual(greenlet(var.get).switch(), 123)
+            self.assertEqual(greenlet(var.get, context=None).switch(), 123)
+            self.assertEqual(greenlet(var.get, context=True).switch(), 123)
+            self.assertEqual(greenlet(var.get, context=False).switch(), 123)
+            self.assertEqual(greenlet(var.get, context=ctx).switch(), 456)
+
+            var.set(789)
+
+            self.assertEqual(greenlet(var.get).switch(), 123)
+            self.assertEqual(greenlet(var.get, context=None).switch(), 123)
+            self.assertEqual(greenlet(var.get, context=True).switch(), 789)
+            self.assertEqual(greenlet(var.get, context=False).switch(), 123)
+            self.assertEqual(greenlet(var.get, context=ctx).switch(), 456)
+
+            with self.assertRaises(AttributeError):
+                greenlet(context=123)
+
+            with self.assertRaises(AttributeError):
+                greenlet(context={})
```

**Comment by CaselIT** [comment]
Great @fantix 
shame that they just published (6days ago) a new release

**Comment by zzzeek** [comment]
"trinary logic", yeah that's a good term.  I've done a ton of that in SQLAlchemy and I wish I hadn't :)  but sometimes it's difficult to avoid.

**Comment by zzzeek** [comment]
so....we are going to wait on https://github.com/python-greenlet/greenlet/pull/183 to handle this first?  i guess we have to change our end in any case what should we do here?

**Comment by CaselIT** [comment]
I think that it would be the best if greenlet allows handling it. Otherwise we risk having to support different behaviours for different versions of greenlet.

**Comment by zzzeek** [comment]
right but are we proposing they add some kind of a flag that we still need to pass

**Comment by jamadden** [comment]
The current proposal, [outlined here](https://github.com/python-greenlet/greenlet/pull/183#issuecomment-700662310) and implemented [here](https://github.com/python-greenlet/greenlet/pull/198) involves a writable attribute:

```python
glet = greenlet(…)
glet.gr_context = get_inherited_context()
```

We'd appreciate any feedback you have on that PR.

**Comment by CaselIT** [comment]
I think this would work for the use case we are trying to achieve here.

After that pr, we can simply update the `_AsyncIoGreenlet` subclass to copy the context, so that it plays nice with the asyncio taks

```py
 class _AsyncIoGreenlet(greenlet.greenlet):
        def __init__(self, fn, driver):
            greenlet.greenlet.__init__(self, fn, driver)
            self.driver = driver
            self.gr_context = contextvars.copy_context()
```

**Comment by sqla-tester** [comment]
**Fantix King** has proposed a fix for this issue in the **master** branch:

**Support PEP-567 context variables** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2376
