### ISSUE TITLE
lower case table doesnt guard against column from other table copied in

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5618]
as noticed in #5617, metadata works, but lower cases dont guard:

```
from sqlalchemy import *


c1 = column('x', Integer)
c2 = column('y', Integer)

t = table('t', c1, c2)

t2 = table('t2', c1, c2)

t.c.x is t2.c.x



m = MetaData()


c1 = Column('x', Integer)
c2 = Column('y', Integer)

t = Table('t', m, c1, c2)

t2 = Table('t2', m, c1, c2)

t.c.x is t2.c.x
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**raise on lower-case column shared to multiple tables** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2277

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**raise on lower-case column shared to multiple tables** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2278
