### ISSUE TITLE
Complete 2.0 api for AsyncEngine, AsyncSession, support inspection

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5628]
Currently the `AsyncEngine` implements just the methods `begin`, `connect` and `raw_connection`.

It should probably implement also the other api of the engine 2.0. As support for inspection is missing.

The api for the engine would be:
- attr `uri`, `pool`, `dialect`, `engine`, `name`, `driver`, `echo`
- methods `clear_compiled_cache`, `update_execution_options`, `execution_options`, `get_execution_options`, `dispose`

Also the `AsyncSession` has some part of the api missing (non complete list):
- attr `bind`, `new`, `deleted`
- methods `get`, `delete`

The same may apply to other `Async` classes that proxy the sync ones, like `AsyncConnection`

**Comment by CaselIT** [comment]
@zzzeek Personally I don't think that the proxy solution is a great fit for the async objects here, unless we suggest to use `sync_engine`/`sync_session`, with the relates problems (eg `sync_session.commit()` will not work/raise exceptions).
It's easy for bug like these to happen and it requires a lot of duplication.

Maybe a `BaseEngine`/`BaseSession` to be used as base classes for both the sync and async version with the common code would be the best solution?

**Comment by CaselIT** [comment]
See also #5627

**Comment by zzzeek** [comment]
since you included delete then we can close #5627.

**Comment by zzzeek** [comment]
IMO we don't need to do inspect() right now.    we don't have async interfaces for reflection overall and this would be a separate issue.   per [the documentation](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#synopsis-core) these things should be run inside of run_sync().

**Comment by CaselIT** [comment]
> 
> 
> IMO we don't need to do inspect() right now. we don't have async interfaces for reflection overall and this would be a separate issue. per [the documentation](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#synopsis-core) these things should be run inside of run_sync().

Yes, I was not thinking about the need for async reflection interfaces.

Maybe we could have an example in the documentation how to use inspect / medatata.reflect with run_sync.
I guess that `autoload_with` also does not work (should we try to detect this usage and raise a meaningful error?)

**Comment by zzzeek** [comment]
Yes we should have a section "running reflection stuff w/ async".   also run_sync() API might not be very smooth for this right now b.c. it assumes "connection" is the first argument, but we need to put something.

IMO async applications themselves are not usually (ever?) going to be doing database inspection stuff except if someone is just accustomed to writing everything async.   the "async use case" as I understand it right now is, request-oriented application that has to do a lot of async web request stuff and wants database calls intermingled.

**Comment by CaselIT** [comment]
I guess that for now we should illustrate running

```py
def fn(conn):
  insp = sa.inspect(conn)
  ...

conn/engine.run_sync(fn)
```



> IMO async applications themselves are not usually (ever?) going to be doing database inspection stuff except if someone is just accustomed to writing everything async. the "async use case" as I understand it right now is, request-oriented application that has to do a lot of async web request stuff and wants database calls intermingled.

I agree, I think it's sufficient for now to have in the documentation how reflection works in the async case, even if it's not as convenient as the sync version. Then if there is a demand for it we can think about implementing better support for 1.4.x or 2

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**generalize scoped_session proxying and apply to asyncio session** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2297

**Comment by CaselIT** [comment]
Do you plan to use the same concept for the async engine/connection?

**Comment by zzzeek** [comment]
at the moment it still feels kind of wrong for engine/connection but I don't have a verbal reason for that.   sometimes when i try to find the reason it turns out I should do it in any case.

**Comment by zzzeek** [comment]
hm I had this notion that async conn/engine were still somehow subclasses but it appears they're not.    well OK.  let's do it.

it's still not automated in that one has to write out the lists of attributes, so still some duplication.
