### ISSUE TITLE
Orm should not rely on InstanceState.obj to return non-None

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5631]
Orm relies on the weakref InstanceState.obj to never return None. This is true in general for cpython, but other implementation do not behave in the same manner, like pypy.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Handle case where InstanceState.obj returns None** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2285

**Comment by CaselIT** [comment]
this is 1.4 only. 1.3 checks only for alive objects
