### ISSUE TITLE
`StatementError.__str__` can fail due to a lazy import

### ISSUE THREAD

**Issue by karlicoss** [sqlalchemy/sqlalchemy#5632]
**Describe the bug**

Sometimes exceptions propagate during the final GC cleanup, when the interpreter exits. At that point, you can't really import new modules, so you'd get some obscure behavior if you do try to. One example I've found is https://github.com/sqlalchemy/sqlalchemy/blob/402cca8f2ac42a08fba7a200c4e1e086e2081aad/lib/sqlalchemy/exc.py#L420

This results in `sqlalchemy.exc.ProgrammingError: <exception str() failed>`, which is pretty obscure.

**Expected behavior**

At the very least, the exception message should be reasonable (in this particular case, it should be `Cannot operate on a closed database`).

Then, I'm not quite sure if that particular code should result in the errors. Not sure what's closed the database in the first place, everything is in a context manager? What's more, it's not always happening (see "NOTE:" comments).

**To Reproduce**

Apologies in advance, this madness really is the minimum I've managed to reduce it to so far (otherwise I don't get the codepath to reproduce).

```py
import_me = '''
# NOTE: if you comment this out, it works fine
from sqlalchemy import Column

import re
# NOTE: if you comment this out, it works fine
re.hack = lambda: None
'''
from pathlib import Path
Path('import_me.py').write_text(import_me)

### NOTE: couldn't reproduce without a separate file
import import_me

def it():
    from sqlalchemy import create_engine
    engine = create_engine('sqlite:////tmp/test.sqlite')
    with engine.connect() as conn:
        with conn.begin():
            yield 0

g = it()
next(g)
```

**Error**

```
Exception ignored in: <generator object it at 0x7f6aefc9a4a0>
Traceback (most recent call last):
  File "run.py", line 36, in it
  File ".../python3.8/site-packages/sqlalchemy/engine/base.py", line 1781, in __exit__
  File ".../python3.8/site-packages/sqlalchemy/engine/base.py", line 1753, in rollback
  File ".../python3.8/site-packages/sqlalchemy/engine/base.py", line 1791, in _do_rollback
  File ".../python3.8/site-packages/sqlalchemy/engine/base.py", line 751, in _rollback_impl
  File ".../python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
  File ".../python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
  File ".../python3.8/site-packages/sqlalchemy/engine/base.py", line 749, in _rollback_impl
  File ".../python3.8/site-packages/sqlalchemy/engine/default.py", line 543, in do_rollback
sqlalchemy.exc.ProgrammingError: <exception str() failed>
```

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 3.8.2
 - SQLAlchemy: 1.3.18
 - Database: sqlite

**Additional context**

A quick 'fix' could be moving the import right before it's used, which would be on fewer code paths, but it's merely deferring the issue: https://github.com/sqlalchemy/sqlalchemy/compare/master...karlicoss:patch-1 Not sure what the right thing to do because there is some circular import involved and you can't import `util` on the top level.

Regarding the `NOTE:` comments: I'll investigate more, wonder if it's some intrinsic Python's nondeterminism during the cleanup...
P.S. I  used `gc` tracing and experimented a bit more, I think this elaborate setup with two files isn't really special, it merely impacts gc order. So I guess it must be some issue with the order of finalizing stuff?

**Comment by zzzeek** [comment]
we have a standard deferred import system we will use that.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use preloaded for sql.util import in exc** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2286

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Use preloaded for sql.util import in exc** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2287
