### ISSUE TITLE
Drop py35 from 1.4 branch

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5634]
EOL date was 2020-09-13 and there should not be many reason not to use py3.6+

**Comment by zzzeek** [comment]
its in the installation doc as well, so we would update that

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Drop python 3.5 support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2296
