### ISSUE TITLE
test suite fails with pytest 6.* (fix attached)

### ISSUE THREAD

**Issue by mcepl** [sqlalchemy/sqlalchemy#5635]
**Describe the bug**
When running with pytest 6.\* (6.1.1 in my case) collection of tests fail with multiple errors:
```
[   26s] _____________ ERROR collecting test/aaa_profiling/test_compiler.py _____________
[   26s] Direct construction of Class has been deprecated, please use Class.from_parent.
[   26s] See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
```

**Expected behavior**
The test suite should pass.

**To Reproduce**
Just run the test suite with pytest 6.*

**Versions.**
 - OS: Linux/OpenSUSE/Factory
 - Python: 3.8.5
 - SQLAlchemy: 1.3.19
 - Database:
 - DBAPI:

**Additional context**
[Full build log with all details](https://github.com/sqlalchemy/sqlalchemy/files/5349079/_log.txt)
[patch fixing the issue](https://github.com/sqlalchemy/sqlalchemy/files/5349086/pytest_depr_from_parent.patch.txt)

**Have a nice day!**

**Comment by zzzeek** [comment]
this was fixed in 40cdb9c0bf4db2af293f9d86692 for 1.3 and in ffafbd4b9657a4ee8bec57c0861414144f37bdc5 for master.   run pytest against rel_1_3 branch to confirm.  thanks!

**Comment by mcepl** [comment]
I will check, but let me just observe that my patch works with pytest < 3.4.0 as well ;).

**Comment by zzzeek** [comment]
py test min version is 4.6 now

**Comment by zzzeek** [comment]
which reallly should be 4.6.11

**Comment by mcepl** [comment]
You are right, I will have to keep my patch though, because I need to keep it compatible with pytest at 3.10.1 (for older versions of SLE and OpenSUSE distributions). Oh well.
