### ISSUE TITLE
Need help with session.delete

### ISSUE THREAD

**Issue by levsh** [sqlalchemy/sqlalchemy#5640]
Hi!
I has a complex database with many relationships and try to use `session.delete(instance)` method but get the following error
```
../../../../conftest.py:74: in db_instance_manager
    db.session.delete(instance)
/home/vagrant/.local/share/virtualenvs/...-EbGmmyNc/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py:163: in do
    return getattr(self.registry(), name)(*args, **kwargs)
/home/vagrant/.local/share/virtualenvs/...-EbGmmyNc/lib/python3.7/site-packages/sqlalchemy/orm/session.py:2045: in delete
    self._delete_impl(state, instance, head=True)
/home/vagrant/.local/share/virtualenvs/...-EbGmmyNc/lib/python3.7/site-packages/sqlalchemy/orm/session.py:2062: in _delete_impl
    self.identity_map.add(state)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sqlalchemy.orm.identity.WeakInstanceDict object at 0x7fd68433b990>, state = <sqlalchemy.orm.state.InstanceState object at 0x7fd6844c7190>

    def add(self, state):
        key = state.key
        # inline of self.__contains__
        if key in self._dict:
            try:
                existing_state = self._dict[key]
            except KeyError:
                # catch gc removed the key after we just checked for it
                pass
            else:
                if existing_state is not state:
                    o = existing_state.obj()
                    if o is not None:
                        raise sa_exc.InvalidRequestError(
                            "Can't attach instance "
                            "%s; another instance with key %s is already "
                            "present in this session."
>                           % (orm_util.state_str(state), state.key)
                        )
E                       sqlalchemy.exc.InvalidRequestError: Can't attach instance <... at 0x7fd6844be9d0>; another instance with key (<class '...'>, ('...',), None) is already present in this session.
```
My code is only makes delete on existing instance no add.
I debugged and found that sqlalchemy uses weakref to store tracked objects so i add gc.collect() method before call session.delete(instance) in my code and it works, no exception is thrown.

So my question: is it possible a bug in sqlalchemy session.delete or am i using it wrong?
Unfortunately i can't provide complete reproducible code.
Thank you for any help

 - OS:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS
```
 - Python:
```
Python 3.7.9
```
 - SQLAlchemy:
```
In [1]: import sqlalchemy

In [2]: sqlalchemy.__version__
Out[2]: '1.3.19'
```
 - Database:
```
psql (10.14 (Ubuntu 10.14-0ubuntu0.18.04.1), server 10.6 (Debian 10.6-1.pgdg90+1))
```

**Comment by zzzeek** [comment]
there's no bug here in SQLAlchemy, the delete() method if given a [detached](https://docs.sqlalchemy.org/en/13/orm/session_state_management.html#session-object-states) object has no choice but to add() it first.  

the reason gc.collect() is clearing the error is because in your application, you are already loading an instance with the same primary key in this session, then discarding it.   however, because it was not garbage collected, it conflicts.    

the program below illustrates exactly how to produce this problem as well as the pattern that prevents this problem.  the overall strategy should be to not use detached objects, instead they should be discarded.

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import inspect
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

a1 = A()
s.add(a1)
s.commit()

# object is not detached
assert not inspect(a1).detached

# close session, which will detach a1
s.close()

# object is detached
assert inspect(a1).detached
assert a1 not in s


# now load another A with same primary key.
a2 = s.query(A).first()
a2.foo = a2


# object is attached
assert inspect(a2).persistent
assert a2 in s

del a2

import gc  # noqa

# 1. uncomment this to remove error
# gc.collect()

# 2. or uncomment this to use the correct pattern - dont use detached objects,
# query for what you need in the transaction
# a1 = s.query(A).first()


# error, if neither 1 nor 2 are uncommented
s.delete(a1)

```

**Comment by levsh** [comment]
@zzzeek thanks for the detailed help!
I fixed problem and issue may be closed.
Just question if sqlalchemy allows call delete on a detached instance and implicitly adds the instance to session is it possible to force discard already loaded and detached instance and then add a new without conflict? Maybe it is not right way but It seems delete has a race condition behaviour depends on gc.

**Comment by zzzeek** [comment]
> @zzzeek thanks for the detailed help!
> I fixed problem and issue may be closed.
> Just question if sqlalchemy allows call delete on a detached instance and implicitly adds the instance to session is it possible to force discard already loaded and detached instance and then add a new without conflict? Maybe it is not right way but It seems delete has a race condition behaviour depends on gc.

that's actually what the Session.merge() method is for.    However, merge() wants to merge the object you have into the transaction itself by emitting SELECT for that row first, which may not be desirable here; there's a flag load=False that would skip this SELECT but it requires the incoming object has no pending changes on it, it might work for you here.

As it stands, what's happening here is that you have this detached object that represented a row in a different transaction somewhere, and by re-associating it with the Session directly, you are telling the Session "assume this row definitely exists in the current transaction" which is not something you could know in general, it could have been deleted or moved elsewhere.       A Session lets you do this if you are starting out with a fresh session of limited scope but if you are doing it on an older session that was being used for other things then you run the risk of conflicting with the state that was already there.
