### ISSUE TITLE
Pip install prerelease 1.4.0b1 doesn't work

### ISSUE THREAD

**Issue by kuz30** [sqlalchemy/sqlalchemy#5641]
**Describe the bug**
If you follow https://docs.sqlalchemy.org/en/14/intro.html#install-via-pip to install 1.4 SQLAlchemy via pip latest released version is installed with command
`pip install --pre SQLAlchemy`
installs
`pip show SQLAlchemy
Name: SQLAlchemy
Version: 1.3.19`

**Expected behavior**
1.4.0b1 is expected

**Comment by zzzeek** [comment]
hi there -

SQLAlchemy 1.4.0b1 is not released yet.    the upper left hand corner of https://www.sqlalchemy.org/ shows what the current releases of SQLAlchemy are.   the docs at https://docs.sqlalchemy.org/en/14/ have a red indicator "PRE RELEASE", the word "release" here means "is available on pypi".  hope this clarifies.

**Comment by zzzeek** [comment]
adjusting the site

**Comment by zzzeek** [comment]
I think the "pre release" verbiage is still used when the beta is releaed however you would see a "release date".  ive boldfaced **not released yet** and changed "pre released" to "in development" when there's no release date.

**Comment by kuz30** [comment]
Thanks for clarification, I misinterpreted state of documentation it was before. I think it clear enough now.

**Comment by jeanmonet** [comment]
Is a branch or repo available for the 1.4 version to look at the code? I couldn't see a "1_4" branch on this repo.

**Comment by zzzeek** [comment]
1.4 is currently the "master" branch and has not yet been put into a named branch.

**Comment by jeanmonet** [comment]
Oh of course 😃 thanks!
