### ISSUE TITLE
move handle_error listener from engine to dialect; implement for pre_ping handler

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5648]
as noted in #5646 there's a [recipe](https://docs.sqlalchemy.org/en/13/core/events.html?highlight=handle_error#sqlalchemy.events.ConnectionEvents.handle_error) to augment the is_disconnect() handler.  however we don't consult it in dialect pre-ping.  looks like we can add classlevel "_handle_dbapi_exception_noconnection" pretty easily to at least allow the hook to be consulted.

**Comment by zzzeek** [comment]
steps are:

1. add dbapi_connection and dialect to ExceptionContext.   "engine" and "connection" can now be None in some cases
2. move handle_error to be part of DialectEvents.  nothing else needs to change here and existing code that links the event from an Engine will be the same.  Connection will still call upon the handler as always.
3. move the production of the ExceptionContext and actually running the hook from engine/base into defaultdialect
3. in DefaultDialect.do_ping(), catch exceptions and call the same hook we created in step 3, where it will call upon ExceptionContext without an Engine or Connection
4. update docs to indicate Engine / Connection may be None for the do_ping handler, maybe others, look more to dbapi_connection and Dialect for forwards compat.

**Comment by zzzeek** [comment]
glad i found this, this is sort of important

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Support handle_error for pre_ping** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3880

**Comment by zzzeek** [comment]
this was not implemented for mysql , postgresql and possibly others.  whatever test support is in place is not testing those backends

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure event handlers called for all do_ping** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4467
