### ISSUE TITLE
rework set_input_sizes() to be generically available for any backend

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5649]
we have just noticed as a result of things related to pyodbc that the way we have setinputsizes at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/default.py#L1536 is wrong!   this is hardcoded to cx_Oracle's [1] style which is actually in conflict with what pep-249 states [2], which is that the method takes a single argument.   then we see pyodbc taking a single list argument here, but they also break the pattern a bit as well in that you send a list of tuples with type arguments [3].

Since we have changed set_input_sizes() quite a bit for 1.4, and also begun using it for both asyncpg as well as pg8000, we need to make sure we get this "right" for any other DBAPI as well with the following steps:

1. DefaultDialect.set_input_sizes should do the thing it's doing, then pass off to a dialect-specific method do_input_sizes

2. do_input_sizes should receive *everything* needed for each of the calling styles, including:
    a. parameter keys, for named parameters
    b. DBAPI type objects that have been worked out
    c. the original SQLAlchemy type where it can divine things like the arguments to pass 
    d. a means of determining positioanl vs. named style
    e. the order of params

that way cx_Oracle can implement it one way, pyodbc can implement it another.   

*then* we need some system whereby *any* dialect can use this system if suddenly someone needs to use it where it was not used previously.   one way to do this is to use a before_cursor_execute() event that then fires off set_input_sizes(), but this is not forwards compatible.   

What I think we should do while we're in 1.4 territory is have a dialect-level flag that indicates that set_input_sizes is needed, so that pre_exec is no longer calling it, it happens at the DefaultExecutionContext level.  that way someone can flip that flag on for any dialect like pyodbc that normally isn't using it, and if we want to flip it on permanently as part of a bug fix we can do that.

[1] https://cx-oracle.readthedocs.io/en/latest/api_manual/cursor.html#Cursor.setinputsizes
[2] https://www.python.org/dev/peps/pep-0249/#id26
[3] https://github.com/mkleehammer/pyodbc/wiki/Cursor#setinputsizeslist_of_value_tuples

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Genericize setinputsizes and support pyodbc** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2309

**Comment by zzzeek** [comment]
why are we actually *doing* setinputsizes for pyodbc?    things were working without it?    this doesnt seem to set up any types and caused a regression in #6058.

**Comment by gordthompson** [comment]
> why are we actually doing setinputsizes for pyodbc?

Likely related to

https://github.com/mkleehammer/pyodbc/issues/835
