### ISSUE TITLE
column with % sign causes error in pandas read_sql_table

### ISSUE THREAD

**Issue by erfannariman** [sqlalchemy/sqlalchemy#5652]
I am trying to solve an issue for pandas which relates to sqlalchemy, see [here](https://github.com/pandas-dev/pandas/issues/37157). 

After investigating I found this happens in [GenerativeSelect](https://github.com/sqlalchemy/sqlalchemy/blob/87c24c498cb660e7a8d7d4dd5f630b967f79d3c8/lib/sqlalchemy/sql/selectable.py#L3295), but I cannot pinpoint the exact location.

Opening this ticket for any support or guidance where to look and where this might happen. In the ticket itself there is an reproducible example.

**Comment by gordthompson** [comment]
Hi @erfannariman 

[Here](https://github.com/pandas-dev/pandas/issues/37157#issue-723017409) you identified that this is a regression in pandas that happened sometime after version 1.0.5, and [here](https://github.com/pandas-dev/pandas/issues/37157#issuecomment-710833121) you confirm that SQLAlchemy itself has no problems with the "%_variation" column name, so there's not much that we can do unless the pandas team can make a convincing case that SQLAlchemy is doing something wrong.

**Comment by zzzeek** [comment]
@erfannariman  agree, you need to do a "git bisect" with pandas to find the changeset that causes the breakage.

What is likely involved here though it's not clear how is that when sending SQL strings to the mysqlclient driver, percent signs "%" have to be double-escaped as "%%".   

We can demonstrate this using a Core select in 1.3:


```python

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Float
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import Numeric
from sqlalchemy import select
from sqlalchemy import Table
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()


m = MetaData()

t = Table(
    "my_table", m,
    Column("id", Integer),
    Column("price", Numeric),
    Column("%_variation", Float)
)


e = create_engine("mysql+mysqldb://scott:tiger@localhost/test", echo=True)
m.create_all(e)


with e.connect() as conn:
    conn.execute(select([t])).fetchall()
```

and as we do in fact see, the column name is as appropriate, escaped with a double percent sign in the SQL output (yes, I know we are emitting the CREATE TABLE also, we will check) :


```sql
CREATE TABLE my_table (
	id INTEGER, 
	price NUMERIC, 
	`%%_variation` FLOAT
)


2020-10-17 10:20:47,950 INFO sqlalchemy.engine.base.Engine ()
2020-10-17 10:20:47,963 INFO sqlalchemy.engine.base.Engine COMMIT
2020-10-17 10:20:47,964 INFO sqlalchemy.engine.base.Engine SELECT my_table.id, my_table.price, my_table.`%%_variation` 
FROM my_table
2020-10-17 10:20:47,964 INFO sqlalchemy.engine.base.Engine ()

```

above, if we didnt know about the "%" escaping, we might think that the test is only testing a table that has "%%_variation" as the column name.  But we can go into the MySQL database directly, bypassing the mysql driver and see the percent sign is just one of them:

```
$ mysql -u scott -p test -e "show create table my_table"
Enter password: 
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table    | Create Table                                                                                                                                                            |
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| my_table | CREATE TABLE `my_table` (
  `id` int(11) DEFAULT NULL,
  `price` decimal(10,0) DEFAULT NULL,
  `%_variation` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```


we can also add inpsection logic in Python to confirm the correct name:

```python

from sqlalchemy import inspect
print(inspect(e).get_columns("my_table"))
```

output shows the correct name:

```
[{'name': 'id', 'type': INTEGER(display_width=11), 'default': None, 'comment': None, 'nullable': True, 'autoincrement': False}, 
{'name': 'price', 'type': DECIMAL(precision=10, scale=0), 'default': None, 'comment': None, 'nullable': True}, 
{'name': '%_variation', 'type': FLOAT(), 'default': None, 'comment': None, 'nullable': True}]
```

so overall, these are all techiques you can use on your end to see where it's going wrong:

1. turn on echo=True with create_engine()
2. confirm the table name in MySQL directly

**Comment by zzzeek** [comment]
also needed:

1. version of mysqlclient in use  (confirm it's not the ancient mysql-python)

2. version of SQLAlchemy

when you upgraded pandas, did either of the above two packages change as well?

**Comment by erfannariman** [comment]
Thanks for the extended explanation @zzzeek , I didn't know about inspect, comes in really handy! I will look into this.

About the versions:
```
mysqlclient                   2.0.1
SQLAlchemy                    1.3.19
```

**Comment by zzzeek** [comment]
we do seem to have a little bit of edge case with the percent column names thing internally, for example psycopg2 driver doesnt support them at all right now, and I forget why that is.   tests are turned off for MySQL drivers but  they seem to pass so turning that on now.

**Comment by erfannariman** [comment]
take

**Comment by erfannariman** [comment]
After investigating, this happens in [pandas/io/sql.py](https://github.com/pandas-dev/pandas/blob/22799d7b1c4a0b1bad0393fe9ba1327a786ea150/pandas/io/sql.py#L1162). I am not really familiar with `sqlalchemy.engine.Connection.execute_options`, but it seems like removing `no_parameters=True` fixes the issue. Is this right thinking or would there be a better option?

**Comment by zzzeek** [comment]
> After investigating, this happens in [pandas/io/sql.py](https://github.com/pandas-dev/pandas/blob/22799d7b1c4a0b1bad0393fe9ba1327a786ea150/pandas/io/sql.py#L1162). I am not really familiar with `sqlalchemy.engine.Connection.execute_options`, but it seems like removing `no_parameters=True` fixes the issue. Is this right thinking or would there be a better option?

wow, look at that, "no_parameters", heh.   that seems like it would have been a workaround for this kind of thing back when SQLAlchemy was possibly not escaping percent signs as nicely.

looks like it's here: https://github.com/pandas-dev/pandas/issues/34211 so not long ago at all, and if you were to remove the flag as this is implemented right now, that bug would come back again.

So, what actually is going wrong here is that pandas is assuming that all SQL being passed was a plain textual string and not a SQL expression construct,which they are in fact doing right here: https://github.com/pandas-dev/pandas/blame/22799d7b1c4a0b1bad0393fe9ba1327a786ea150/pandas/io/sql.py#L866 

so yes, this is a bug in pandas and the issue is that they are applying no_parameters too liberally.   they need to use that flag only when the SQL being passed is a totally raw SQL string with no parameters being passed and not a compiled construct.   if this execute() method is at the top level of statements being passed they'd need to distinguish between isinstance(stmt, str) and isinstance(stmt, sqlalchemy.sql.expression.ClauseElement).

**Comment by zzzeek** [comment]
oh im wrong about parameters not being provided.    no_parameters only takes effect if there are actually no parameters passed, so no issue there.

**Comment by zzzeek** [comment]
this is an issue in pandas
