### ISSUE TITLE
Is there a way to tell sqlalchemy to help me support specific set of dialects

### ISSUE THREAD

**Issue by AbdealiJK** [sqlalchemy/sqlalchemy#5655]
I have been using sqlalchemy for quite some time - and have always been amazed by the number of things it can do :)

Recently, I've had to start supporting oracle in the same application. i.e. users of the application can choose between MySQL and Oracle. And I found that there were a lot of differences in Oracle that I did not realize.

For example:
 - The IFNULL function isn't available in Oracle
 - Unable to use == conditions in WHERE for Text() type (which is internally a CLOB type)
 - NULL is considered a valid value in unique constraints and cannot be repeated.
 - Required a Sequence to be defined for auto-increment columns

I've burnt my fingers a fair number of times due to these issues.

To handle these issues, we've had 2 thoughts:
 - Run unit tests on all our supported databases - Currently, we just run on 1 DB
 - Have linters or runtime checks which throw errors if a capability is not available in any of our supported DB

I am wondering if there is a way for me to tell SQLAlchemy to get into a "compatibility mode" - so that I can only use the set of features that are supported by all the DBs I want to support.
For example if I use `sqlalchemy.func.ifnull()` - it could just throw an error saying "One of your supported dialects - oracle does not support this function" ?
OR even better - If I enable that, for oracle - it could automatically use coalesce or some other method to handle it

**Comment by zzzeek** [comment]
hey there -

So I understand the need here but unfortunately there's no real way to achieve that across the board.    the ifnull() symbol for example doesn't actually exist in SQLAlchemy.     For dialects to report on every SQL function they support or not means we'd have to hardcode all possible SQL functions and have lookup tables in every dialect, all third party dialects would need them as well, and then, lots of those functions probably work *differently* on different backends too, different arguments accepted, different return types, etc.  

now in fact SQLAlchemy's typing system is more or less exactly that, it's a list of all possible symbols w/ hardcoded dialect rules for each one.    but there are a lot fewer datatypes on the various backends compared to how many functions are present.

so anyway, that's just SQL functions, not all the other things you mention that are in fact a lot more subtle.    

The one thing in particular that could have a warning is the lack of a Sequence on your integer column that otherwise is noted as wanting to be "autoincrement".   Oracle and Firebird have a special case here where they don't have any kind of auto-incrementing column feature.   that's kind of a big one and maybe could have a warning.   

but overall I dont think it's feasible we'd ever have an across the board "protection" system for this kind of thing, while we could spend lots of time covering as many bases as possible, it would still give you no guarantee at all that your application would just work on Oracle if you've never tested it.

which means, if you want people using your application on Oracle, even if we spent months of work guarding against every possible issue you might have, you still need to run your test suite on every database you hope to support.

which means....if you're running your test suite in any case, that's of course the best way to make sure everything works.    

hope this clarifies the current situation :)

**Comment by CaselIT** [comment]
> The one thing in particular that could have a warning is the lack of a Sequence on your integer column that otherwise is noted as wanting to be "autoincrement". Oracle and Firebird have a special case here where they don't have any kind of auto-incrementing column feature. that's kind of a big one and maybe could have a warning.

In 1.4 `Identity` may be used to specify autoincrement on Oracle (I'm not sure regarding Firebird, but it's support is legacy), so I don't think we will need it.

**Comment by AbdealiJK** [comment]
@zzzeek Thanks for the detailed reply, I think all your points make a lot of sense.
We will be doing our tests on multiple DBs, we have some sqlite specific code that we'll have to work around - but I agree that it is the most robust way of doing it.

I also realized after posting this that the compiler-extension enables me to do a bunch of nice things like:
```python
@compiles(Function)
def compile_ifnull_for_oracle_compat(element, compiler, **kw):
    if element.name.lower() == 'ifnull':
        raise NotImplementedError(
            'Function "IFNULL" should not be used as it is not supported in Oracle. '
            'Use "COALESCE" instead.'
        )
    return compiler.visit_function(element, **kw)
```

But I'll be doing a lot of trial and error - as I'm using Oracle (and the compiler extension) for the first time :)

I'm wondering if it seems feasible to have a `sqlalchemy.ext.dbcompat` or some similar location / structure where newbies like me can go and just have a "safe-mode" which just keeps throwing errors which we can expect. And can use as a reference that can be carried over from various lessons learned by various people doing this - as it seems to be a common usecase.
I also agree that this shouldn't have any guarantees and should be a helper for people to learn.
Could also just be a recipe in the documentation ?

It could also be a completely separate repo or project or gist, but I thought it would be a lot more noticeable and collaborative if it was associated to sqlalchemy :)

PS: Again, I completely agree with you that it should be a "no guarantee" kind of thing, just a optin "helper" to catch some easy to catch issues.

**Comment by zzzeek** [comment]
> > The one thing in particular that could have a warning is the lack of a Sequence on your integer column that otherwise is noted as wanting to be "autoincrement". Oracle and Firebird have a special case here where they don't have any kind of auto-incrementing column feature. that's kind of a big one and maybe could have a warning.
> 
> In 1.4 `Identity` may be used to specify autoincrement on Oracle (I'm not sure regarding Firebird, but its support is legacy), so I don't think we will need it.

IIUC that still requires that the Identity construct is used explicitly.   all the tutorials etc. dont show this because it is not necessary for other DBs.

**Comment by zzzeek** [comment]
> 
> I'm wondering if it seems feasible to have a `sqlalchemy.ext.dbcompat` or some similar location / structure where newbies like me can go and just have a "safe-mode" which just keeps throwing errors which we can expect. And can use as a reference that can be carried over from various lessons learned by various people doing this - as it seems to be a common usecase.

that sounds like the same thing, what would this "dbcompat" extension do ?     This is not really a "newbie" problem, DB compatibility is an issue for everyone.   Databases are constantly changing, adding new features, etc.   


> I also agree that this shouldn't have any guarantees and should be a helper for people to learn.
> Could also just be a recipe in the documentation ?
> 
> It could also be a completely separate repo or project or gist, but I thought it would be a lot more noticeable and collaborative if it was associated to sqlalchemy :)

oh if someone wants to do something third party, by all means.   Having it here means we have to support and release it.   I dont think it's the kind of thing that can be generalized and relied upon.    it would be in always broken state basically, and especially that it tries to "guarantee" someones application will run on other platforms without testing, seems like users getting hit by all the places it doesnt work will be generally grumpy as well.

**Comment by zzzeek** [comment]
OK also no matter how many times we'd say "it does not GUARANTEE", we'd get the same number of bugs etc.   Alembic makes it extremely clear that it "does not guarantee" that autogenerated migration files will work out of the box without manual edits.   however as I'm sure you can guess, that's 95% of our bug reports and lots of them come from people who did not read the docs.    it's not worth adding more things like that.

**Comment by CaselIT** [comment]
> 
> 
> > > The one thing in particular that could have a warning is the lack of a Sequence on your integer column that otherwise is noted as wanting to be "autoincrement". Oracle and Firebird have a special case here where they don't have any kind of auto-incrementing column feature. that's kind of a big one and maybe could have a warning.
> > 
> > 
> > In 1.4 `Identity` may be used to specify autoincrement on Oracle (I'm not sure regarding Firebird, but its support is legacy), so I don't think we will need it.
> 
> IIUC that still requires that the Identity construct is used explicitly. all the tutorials etc. dont show this because it is not necessary for other DBs.

yes, maybe we would add introduce it in some tutorials? I don't remember if the documentation for Column.primary_key/autoincrement references is, but maybe it could be mentioned?

**Comment by zzzeek** [comment]
> > > > The one thing in particular that could have a warning is the lack of a Sequence on your integer column that otherwise is noted as wanting to be "autoincrement". Oracle and Firebird have a special case here where they don't have any kind of auto-incrementing column feature. that's kind of a big one and maybe could have a warning.
> > > 
> > > 
> > > In 1.4 `Identity` may be used to specify autoincrement on Oracle (I'm not sure regarding Firebird, but its support is legacy), so I don't think we will need it.
> > 
> > 
> > IIUC that still requires that the Identity construct is used explicitly. all the tutorials etc. dont show this because it is not necessary for other DBs.
> 
> yes, maybe we would introduce it in some tutorials? I don't remember if the documentation for Column.primary_key/autoincrement references is, but maybe it could be mentioned?

maybe, though I'm not sure I'm ready to start recommending IDENTITY as a best practice on all of these databases because I don't know how that's going to come bite us later.

**Comment by jvanasco** [comment]
> I also realized after posting this that the compiler-extension enables me to do a bunch of nice things like

Since you're dealing with supporting two databases, you can consider abstracting this into a custom function that will work on both.

For example, here is some code that defines a `year_week` function, with a default (i think it's mysql, i forget); postgres and sqlite renderer.  My Python code just calls `year_week(` and SQLAlchemy does the rest.

```python
class year_week(expression.FunctionElement):
    type = sqlalchemy.types.String()
    name = "year_week"


@compiles(year_week)
def year_week__default(element, compiler, **kw):
    # return compiler.visit_function(element)
    """
    ## select extract(week from timestamp_event) from table_a;
    week_num = sqlalchemy.sql.expression.extract('WEEK', ServerCertificate.timestamp_not_before)
    """
    args = list(element.clauses)
    return "concat(extract(year from %s), '.', extract(week from %s)) " % (
        compiler.process(args[0]),
        compiler.process(args[0]),
    )


@compiles(year_week, "postgresql")
def year_week__postgresql(element, compiler, **kw):
    """
    # select to_char(timestamp_event, 'YYYY.WW')  from table_a;
    week_num = sqlalchemy.func.to_char(ServerCertificate.timestamp_not_before, 'YYYY.WW')
    """
    args = list(element.clauses)
    return "to_char(%s, 'YYYY.WW')" % (compiler.process(args[0]),)


@compiles(year_week, "sqlite")
def year_week__sqlite(element, compiler, **kw):
    """
    # strftime('%Y.%W', cast(ServerCertificate.timestamp_not_before) as text)
    week_num = sqlalchemy.func.strftime('%Y.%W',
                                        sqlalchemy.cast(TABLE.COLUMN,
                                                        sqlalchemy.Unicode
                                                        )
                                        )
    """
    args = list(element.clauses)
    return "strftime('%%Y.%%W', %s)" % (compiler.process(args[0]),)
```

**Comment by zzzeek** [comment]
we always strive to improve cross-compatibility and documentation but it's not something we can just "add" for 100% of cases at once, for individual constructs where we can do something let's open specific actionable issues.
