### ISSUE TITLE
Support easy mapping from vendor-specific types to generic types

### ISSUE THREAD

**Issue by AndrewHannigan** [sqlalchemy/sqlalchemy#5659]
I would request the ability to map vendor-specific type to a generic type.  The reverse is already supported:

```
# Map from Generic Type to Vendor-Specific Type
ddl_type_name = engine.dialect.type_compiler.process(sa.String())
print(repr(ddl_type_name))
```

Mapping from a vendor-specific type to a generic type would be helpful when replicating a schema as closely as possible between two different type of database (IE: SQL Server to Redshift).  Data Warehousing is the initial motivation for this feature.  In this scenario you have an OLTP database with a certain schema, and you want to replicate that schema as closely as possible on some data warehouse (Redshift, Snowflake, etc).   Many ETL tools already support this (AWS Glue, AWS DMS, Fivetran, Stitchd).  Would be handy to have a way to do this in SA.

Suggested syntax for this feature:
```
ddl_type_name = engine.dialect.type_compiler.process(sa.String())
sa.to_generic(ddl_type_name) # Returns sa.String()
```

Or add `to_generic()` to the `TypeEngine` class.

**Comment by zzzeek** [comment]
hey there -

We provide the _type_affinity accesor which does this to a large extent:

```
>>> from sqlalchemy.dialects.postgresql import VARCHAR
>>> VARCHAR()._type_affinity
<class 'sqlalchemy.sql.sqltypes.String'>

```

however to actually provide the instance of the type would be challenging.   if you have a MySQL VARCHAR with four different mysql-specific flags set inside of it, something would need to figure out that we only need "length" which could be through argument inspection or much less feasibly methods on every dialect-specific type.

If you can provide a PR that includes tests which will run through all types, as you can see in a test like this: https://github.com/sqlalchemy/sqlalchemy/blob/master/test/sql/test_types.py#L289 then we would have something that could be included as public.

**Comment by zzzeek** [comment]
this is something that's been asked before but I cant find the issue for it right now, if there was one.

**Comment by gordthompson** [comment]
related: https://stackoverflow.com/q/64214225/2144390

**Comment by zzzeek** [comment]
we have logic that uses the argspec of the type's __init__ to figure things out, such as here: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/type_api.py#L556  https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/type_api.py#L577 etc. , so i believe we could combine that kind of technique with the existing _type_affinity to provide the feature.   _type_affinity has been there for years I just have it underscored so that I don't get hit supporting it :)   but i had assumed eventually we'd use it for something like this.

**Comment by CaselIT** [comment]
Wouldn't this use case be solved by the `with_variant`?
Something like `sa.String().with_variant('mssql', MSSQLString()).with_variant('redshift', REDString())`?

**Comment by zzzeek** [comment]
I believe the use case here is that of reflecting database columns / tables from one vendor's database and then running a CREATE TABLE on another vendor's database.   this feature would allow you to plug it into the column_reflect() event so that you get a reflected table with generic types.

this has definitely been proposed before and I just never got around to it but I really thought there would have been an issue for it already.   so here we are!

**Comment by CaselIT** [comment]
> I believe the use case here is that of reflecting database columns / tables from one vendor's database and then running a CREATE TABLE on another vendor's database. this feature would allow you to plug it into the column_reflect() event so that you get a reflected table with generic types.

I missed the reflection use case.

**Comment by AndrewHannigan** [comment]
`_type_affinity` certainly gets us close.  Something like this (untested) code might get us pretty close?  Do we feel like something like this alone would be sufficient, or can you think of situations where it is more complex than simply finding the union args for the vendor type and generic type?

```
# for some vendor-specific type object t

gen_class = t._type_affinity

gen_args = inspect.getargspec(sa.String).args
ven_args = inspect.getargspec(t.__class__).args

shared_args = (set(gen_args ) & set(ven_args)) - {'self'}

kwargs  = {k, getattr(t, k) for k in shared_args}
gen_obj = gen_class(**kwargs)
```

**Comment by AndrewHannigan** [comment]
Also, what's the best place for something like this to live?  `TypeEngine_to_generic()`?

**Comment by zzzeek** [comment]
so with these things like the adapt() method, we do a generic thing like the above which does get us 90% of the way there.  the types that will need special methods include Enum and ARRAY.   These two types have specialized versions of the various methods already.

I was thinking this could finally be a public supported method so it can be to_generic() or as_generic().

**Comment by AndrewHannigan** [comment]
A wrinkle - cases where the argument name and the resulting field name are different

```
In [8]: s = String(convert_unicode = True)
<ipython-input-8-524dc554b866>:1: SADeprecationWarning: The String.convert_unicode parameter is deprecated and will be removed in a future release.  All modern DBAPIs now support Python Unicode directly and this parameter is unnecessary.
  s = String(convert_unicode = True)

In [9]: s
Out[9]: String(_expect_unicode=True)
```

I can write special cases to handle this kind of thing, but do we have a sense of how frequently we would expect the basic generic logic to fail?  If the generic logic will usually work that's great, but given that I ran into this on my first test (mapping String() back to String()) wondering how far the generic approach will actually get us..

**Comment by zzzeek** [comment]
So the use case here is datatypes that were reflected, so I dont think convert_unicode is going to be part of that process, I guess if you are scanning for keyword arguments using getargspec, if the value is at its default per the getargspec, you wouldn't add it to the constructor arguments.

But also the issue of String / Unicode raises the issue that we should be returning Unicode for an NVARCHAR kind of type, not String, so here's a new version of what _type_affinity does which can be tailored for what we are doing here:

```diff

diff --git a/lib/sqlalchemy/sql/type_api.py b/lib/sqlalchemy/sql/type_api.py
index 614b70a41..9d03518d8 100644
--- a/lib/sqlalchemy/sql/type_api.py
+++ b/lib/sqlalchemy/sql/type_api.py
@@ -456,6 +456,24 @@ class TypeEngine(Traversible):
         else:
             return self.__class__
 
+    @classmethod
+    def _is_generic_type(cls):
+        n = cls.__name__
+        return n.upper() != n
+
+    def _generic_type_affinity(self):
+
+        for t in self.__class__.__mro__:
+            if t.__module__ in (
+                "sqlalchemy.sql.sqltypes",
+                "sqlalchemy.sql.type_api",
+            ) and t._is_generic_type():
+                if t in (TypeEngine, UserDefinedType):
+                    return NULLTYPE.__class__
+                return t
+        else:
+            return self.__class__
+
     def dialect_impl(self, dialect):
         """Return a dialect-specific implementation for this
         :class:`.TypeEngine`.

```

the above method is designed explicitly for the "moving types between backends" use case, so it returns NullType for a non-generic type:

```
>>> from sqlalchemy.dialects import mssql
>>> mssql.NVARCHAR()._generic_type_affinity()
<class 'sqlalchemy.sql.sqltypes.Unicode'>
>>> from sqlalchemy import Interval
>>> Interval()._generic_type_affinity()
<class 'sqlalchemy.sql.sqltypes.Interval'>
>>> from sqlalchemy import NCHAR
>>> NCHAR()._generic_type_affinity()
<class 'sqlalchemy.sql.sqltypes.Unicode'>
>>> from sqlalchemy.dialects.postgresql import INET
>>> INET()._generic_type_affinity()
<class 'sqlalchemy.sql.sqltypes.NullType'>

```

**Comment by AndrewHannigan** [comment]
@zzzeek This version of `_generic_type_affinity` fails for situations where there is a non-TypeEngine class in the MRO path. 

Try:
```
from sqlalchemy.dialects.postgresql import JSON
x = JSON()
x._generic_type_affinity()
```

Output:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-f8b49260dff1> in <module>
      1 from sqlalchemy.dialects.postgresql import JSON
      2 x = JSON()
----> 3 x._generic_type_affinity()

~/src/sqlalchemy/lib/sqlalchemy/sql/type_api.py in _generic_type_affinity(self)
    471                     "sqlalchemy.sql.type_api",
    472                 )
--> 473                 and t._is_generic_type()
    474             ):
    475                 if t in (TypeEngine, UserDefinedType):

AttributeError: type object 'Indexable' has no attribute '_is_generic_type'
```

Easy fix would be to just check if `t` has an `_is_generic_type` attr before using it. If that makes sense, I can include that fix with my PR.

The other issue though is that sometimes we do actually want an all upper case type to be thought of as a generic.  For instance `sqlalchemy.dialects.postgresql.json.JSON` should map to `sqlalchemy.sql.sqltypes.JSON` even though it all upper case.

**Comment by AndrewHannigan** [comment]
Maybe `_generic_type_affinity` should just return the first class in the MRO path that:
* comes from either the "sqlalchemy.sql.sqltypes" or "sqlalchemy.sql.type_api" modules AND
* inherits TypeEngine

And forget the upper case check?

**Comment by zzzeek** [comment]
Whatever passes all the tests is fine!    it looks like _generic_type_affinity() got committed on my end by accident in 654b462d66 .    It's not part of any tests so feel free to change it.

**Comment by sqla-tester** [comment]
**Andrew Hannigan** has proposed a fix for this issue in the **master** branch:

**Implement `TypeEngine.as_generic`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2375

**Comment by gordthompson** [comment]
@zzzeek - Should the milestone on this be updated to 1.4?

**Comment by zzzeek** [comment]
if all parties are cool having this be a 1.4 thing then yes.

**Comment by gordthompson** [comment]
> 
> 
> if all parties are cool having this be a 1.4 thing then yes.

That's fine with me.

**Comment by zzzeek** [comment]
ok if @AndrewHannigan  can work around this for now with an outside function if they are using 1.3 for now we can make this a 1.4 thing.

**Comment by AndrewHannigan** [comment]
Yes works for me
