### ISSUE TITLE
Comment on a ForeignKeyConstraint

### ISSUE THREAD

**Issue by olirice** [sqlalchemy/sqlalchemy#5667]
Is it possible to include a SQL comment on a `ForeignKeyConstraint` that gets created with `Base.metadata.create_all` or alembic?

**Database Engine**
PostgreSQL 12

This was my guess:

```python
class EntityA(Base):
    __tablename__ = 'entity_a'
    id = Column(Integer, primary_key=True)
    
class EntithB(Base):
    __tablename__ = 'entity_b'
    __table_args__  = (
        ForeignKeyConstraint(['id'], [EntityA.id], info={'comment': 'friendly description'}),
    )
    id = Column(Integer, primary_key=True)
```

but `Base.metadata.create_all` emitted

```
CREATE TABLE entity_a (
	id SERIAL NOT NULL, 
	CONSTRAINT pk_entity_a PRIMARY KEY (id)
)


CREATE TABLE entity_b (
	id INTEGER NOT NULL, 
	CONSTRAINT pk_entity_b PRIMARY KEY (id), 
	CONSTRAINT fk_entity_b_id_entity_a FOREIGN KEY(id) REFERENCES entity_a (id)
)
```

**Comment by zzzeek** [comment]
not something we have at the moment, would need contributors to help out (we have dedicated devs who might get to it).

**Comment by zzzeek** [comment]
#7742 is the PR

**Comment by sqla-tester** [comment]
**cheremnov** has proposed a fix for this issue in the **main** branch:

**Comments on (named) constraints** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3633
