### ISSUE TITLE
Method names of sqlalchemy.util._collections.Properties won't work as table names when using autospec

### ISSUE THREAD

**Issue by jkoscialkowski** [sqlalchemy/sqlalchemy#5670]
**Describe the bug**
I have a Postgres DB with several tables, including one named `values`. I tried automapping the schema, but failed to do so due to this table's name.

**Expected behavior**
I would like to be able to use `Base.classes.values` as a standard automap object.

**To Reproduce**
Run the following:

```py
from sqlalchemy import create_engine, Column, Integer
from sqlalchemy.ext.declarative import declarative_base

engine = create_engine("sqlite:////home/koscial/Repos/app.db")
Base = declarative_base()

class Value(Base):
    __tablename__ = "values"

    id = Column(Integer, primary_key=True, autoincrement=True)
    field1 = Column(Integer)


Base.metadata.create_all(engine)
```
Then in a fresh Python interpreter:
```py
from sqlalchemy import create_engine
from sqlalchemy.ext.automap import automap_base

Base = automap_base()
engine = create_engine("sqlite:////home/koscial/Repos/app.db")
Base.prepare(engine, reflect=True)

Value = Base.classes.values
Value(field1=123)
```

**Error**

```
Traceback (most recent call last):
  File "<input>", line 9, in <module>
TypeError: values() got an unexpected keyword argument 'field1'
```

**Versions.**
 - OS: Ubuntu Focal
 - Python: 3.7.9
 - SQLAlchemy: 1.3.18
 - Database: SQLite, happened when working with Postgres
 - DBAPI:

**Additional context**
This is caused by the `Base.classes` (of class `util._collections.Properties`) class having a `values` method (https://github.com/zzzeek/sqlalchemy/blob/91e14cc42c3c715f57db7d910761dfd5dd55e2b1/lib/sqlalchemy/util/_collections.py#L209). I can think of no quick fix for this, but wanted to bring this to your attention.

**Have a nice day!**

**Comment by CaselIT** [comment]
Other than removing attribute access, I don't think there is any solution possible here, since tables called as class attributes will never work in this case (a table called `keys` or `items` would have the same problem). 

You can use `Value = Base.classes['values']` or `Value = Base.classes.get('values')`

**Comment by jkoscialkowski** [comment]
My bad, this was the first time I was using automap and didn't try out doing it the way you mentioned. I tried it now and it worked for my case. Thanks a lot!
