### ISSUE TITLE
sqlalchemy query clickhouse missing rows

### ISSUE THREAD

**Issue by queerkid** [sqlalchemy/sqlalchemy#5671]
**Describe the bug**
Expect to query 3 rows of data, but get a row

**Expected behavior**
Get what i want

**To Reproduce**
via py code

```py
from sqlalchemy import create_engine

from clickhouse_sqlalchemy import make_session

uri = "clickhouse://default:xxx@ip"
sql = "select * from system.numbers limit 3"

def test_sqlalchemy(uri,sql):
    eng = create_engine(uri)
    res = eng.execute(sql)
    return list(res)

def test_clickhouse_sqlalchemy(uri,sql):
    engine = create_engine(uri)
    session = make_session(engine)
    res = session.execute(sql).fetchall()
    return list(res)

assert test_sqlalchemy(uri,sql) == test_clickhouse_sqlalchemy(uri,sql)
```

**Error**
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    assert test_sqlalchemy(uri,sql) == test_clickhouse_sqlalchemy(uri,sql)
AssertionError
```

**Versions.**
 - OS: ubuntu 20.04 on wsl and centos 7.6
 - Python:Python 3.8.5 and Python 3.6
 - SQLAlchemy:1.3.20
 - Database:clickhouse 20.03
 - DBAPI:clickhouse-sqlalchemy(0.1.4)

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there.

"clickhouse" seems to be a third party dialect which we know nothing about here.     you should post an issue with the people who develop this dialect over here:  https://github.com/xzkostyan/clickhouse-sqlalchemy/issues .  additionally you probably need to provide more specifics.    as written, I would say it seems that your SQL query is only accessing one row if that's all it is returning to you.   what information would suggest otherwise?

**Comment by queerkid** [comment]
> 
> 
> hey there.
> 
> "clickhouse" seems to be a third party dialect which we know nothing about here. you should post an issue with the people who develop this dialect over here: https://github.com/xzkostyan/clickhouse-sqlalchemy/issues . additionally you probably need to provide more specifics. as written, I would say it seems that your SQL query is only accessing one row if that's all it is returning to you. what information would suggest otherwise?

Another sql example:
```py
from sqlalchemy import create_engine

from clickhouse_sqlalchemy import make_session

uri = "clickhouse://default:xxx@ip"
sql = "select 1"

eng = create_engine(uri)
res = eng.execute(sql)

print(list(res))
```

**expect print :[(1,)]
actual print: []**

**Comment by zzzeek** [comment]
hi - 

please post an issue at  https://github.com/xzkostyan/clickhouse-sqlalchemy/issues .   thanks!
