### ISSUE TITLE
Incorrect results or errors when adding a datetime.timedelta() value to a column

### ISSUE THREAD

**Issue by vargab95** [sqlalchemy/sqlalchemy#5672]
**Describe the bug**
When using pymssql and a timedelta is added to a column which has DateTime format, an additional 70 years added beside the specified value.

Column:
```python3
end_time = Column(DateTime, nullable=False)
```
Update:
```python3
session.query(Auction).filter_by(id=auction.id).update({Auction.end_time: Auction.end_time + datetime.timedelta(seconds=10)})
```

**Expected behavior**
10 seconds are added to the original end_time value.

**To Reproduce**
Run the following code.

```py
#!/usr/bin/python3

import datetime

import sqlalchemy.ext.declarative as dec
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy import Column, Integer, DateTime
from contextlib import contextmanager


engine = create_engine("mssql+pymssql://<user>:<password>@<ip>:1433/<db>", echo=True)
session_factory = sessionmaker(bind=engine)
DbSession = scoped_session(session_factory)

@contextmanager
def session_scope():
    """Provide a transactional scope around a series of operations."""
    session = DbSession()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()
        DbSession.remove()


Base = dec.declarative_base()


class Auction(Base):
    __tablename__ = "auction"
    id = Column(Integer, primary_key=True, autoincrement=True)
    end_time = Column(DateTime, nullable=False)

Auction.metadata.create_all(engine, checkfirst=True)

with session_scope() as session:
    auction = Auction()

    auction.end_time = datetime.datetime(2020, 10, 27, 9, 55, 31)

    session.add(auction)
    session.commit()

    session.query(Auction).filter_by(id=auction.id).update({Auction.end_time: Auction.end_time + datetime.timedelta(seconds=10)})
    session.commit()

    modified_auction = session.query(Auction).filter_by(id=auction.id).first()

    if modified_auction.end_time != datetime.datetime(2020, 10, 27, 9, 55, 31) + datetime.timedelta(seconds=10):
        print("ERROR", modified_auction.end_time.isoformat())
```

**Versions.**
 - OS: Ubuntu 20.04.1 LTS
 - Python: Python 3.8.5 (default, Jul 28 2020, 12:59:40)
 - SQLAlchemy: 1.3.19
 - Database: Docker container from mcr.microsoft.com/mssql/server:2017-CU8-ubuntu image
 - DBAPI: pymssql 2.1.5

**Comment by jvanasco** [comment]
I don't have mssql available, but can help with initial triage, as there are occasionally issues with pymssql or sqlserver.

Would you mind adding some extra insight:

* Since you have echo=True, what SQL is being emitted for the INSERT (add) and UPDATE (update) routines
* Can you do a quick query to show what the end_time is after the add/commit and before the update/commit?

**Comment by gordthompson** [comment]
I am able to reproduce your issue:

``` python
import datetime

import pymssql
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

connection_uri = "mssql+pymssql://scott:tiger^5HHH@192.168.0.199/test"
engine = sa.create_engine(connection_uri, echo=True)

Base = declarative_base()


class Thing(Base):
    __tablename__ = "gh_sqla_5672"
    id = sa.Column(sa.Integer, primary_key=True, autoincrement=False)
    dtm = sa.Column(sa.DateTime)

    def __repr__(self):
        return f"<Thing(id={self.id}, dtm={self.dtm})>"


Base.metadata.drop_all(engine, checkfirst=True)
Base.metadata.create_all(engine)

Session = sessionmaker(bind=engine)
session = Session()

print(sa.__version__)  # 1.3.20
print(pymssql.__version__)  # 2.1.5

thing1 = Thing(id=1, dtm=datetime.datetime(2001, 1, 1, 1, 1, 1))
session.add(thing1)
session.commit()
print(thing1)  # <Thing(id=1, dtm=2001-01-01 01:01:01)>

session.query(Thing).update(
    {Thing.dtm: Thing.dtm + datetime.timedelta(seconds=10)}
)
"""sql rendered:
UPDATE gh_sqla_5672 SET dtm=(gh_sqla_5672.dtm + %(dtm_1)s)
{'dtm_1': datetime.datetime(1970, 1, 1, 0, 0, 10)}
"""
session.commit()
print(thing1)  # <Thing(id=1, dtm=2071-01-01 01:01:11)>
```

I will investigate further.

**Comment by gordthompson** [comment]
This issue is broader than just `mssql+pymssql`. My testing indicates that it doesn't work with `mssql+pyodbc` or `mysql+mysqldb` either, although those environments throw an error instead of returning an incorrect value.

I thought that a possible workaround might be

``` python
session.query(Thing).update(
    {Thing.dtm: sa.func.dateadd(sa.text("second"), 10, Thing.dtm)}
)
```

but that throws

> sqlalchemy.exc.InvalidRequestError: Could not evaluate current criteria in Python: "Cannot evaluate Function". Specify 'fetch' or False for the synchronize_session parameter.

even though `sa.func.dateadd` works okay in the context of a select:

``` python
print(session.query(sa.func.dateadd(sa.text("second"), 10, Thing.dtm)).all())
```

Let's see what @zzzeek might have to say about this.

**Comment by zzzeek** [comment]
hey @gordthompson  set synchronize_session=False and run that UPDATE again like that, just to see if the SQL part works.  we don't need to exercise the ORM part here.

**Comment by zzzeek** [comment]
also, the issue here woudl be that the timedelta() object is not interpreted correctly.   Which I believe might be the case; I'm not sure if pyodbc etc. know how to correctly accomodate timedelta(), nor am I very familiar with what date arithmetic SQL Server provides here for the "+" operator.   using dateadd() will of course do exactly what's needed.

basically the overarching issue is that SQLAlchemy doesn't do abstraction for date arithmetic functions right now, these have to be implemented explicitly for each backend such as using DATEADD.

**Comment by gordthompson** [comment]
> 
> 
> set synchronize_session=False and run that UPDATE again like that, just to see if the SQL part works.

Yes, that seems to do the trick with mssql+pymssql:

``` python
# …
print(thing1)  # <Thing(id=1, dtm=2001-01-01 01:01:01)>

session.query(Thing).update(
    {Thing.dtm: sa.func.dateadd(sa.text("second"), 10, Thing.dtm)},
    synchronize_session=False,
)
"""sql rendered:
UPDATE gh_sqla_5672 SET dtm=dateadd(second, %(dateadd_1)s, gh_sqla_5672.dtm)
{'dateadd_1': 10}
"""
session.commit()
print(thing1)  # <Thing(id=1, dtm=2001-01-01 01:01:11)>
```

**Comment by gordthompson** [comment]
As of the current master branch,

``` python
session.query(Thing).update(
    {Thing.dtm: Thing.dtm + datetime.timedelta(seconds=10)}
)
```

works for postgresql and oracle, but not for mssql, mysql, or sqlite.

**Comment by zzzeek** [comment]
so as mentioned earlier we don't implement date arithmetic operators.    however this kind of issue could be prevented by at least having the operators that we implement for other systems, do something appropriate, like if dateadd is available, have the "+" sign render a dateadd, and for backends where we know we aren't doing it, particularly SQLite where you need to convert both sides of an expression into an epoch to do date arithmetic, just raise an exception or emit a warning.     

this is a lot of work for little positive result so it has not been prioritized for many years.

**Comment by jvanasco** [comment]
Emitting a warning on all data arithmetic operations first might be a good initial start.  It looks like I have some affected code, but never knew because that code and tests only go against Postgresql and don't touch sqlite.

**Comment by gordthompson** [comment]
So would this be a case of subclassing `ColumnOperator.__add__()` and `ColumnOperator.__sub__()` at the dialect level for mssql, mysql, and sqlite, check for a `datetime.timedelta` object, and warn if we find one? (Actually I would prefer a raise with a message recommending `func.dateadd()` for mssql, `func_date_add()` for mysql, and ?? for sqlite.)

**Comment by zzzeek** [comment]
not quite, there's a system in place already that allows for type-specific behaviors on operators,which starts with the [TypeEngine._adapt_expression](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/type_api.py#L80) method.  For date types, they are already using this via the [LookupExpressionAdapter](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/sqltypes.py#L45) mixin so they have a more simplified form at for example https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/sqltypes.py#L874 .

The "utlimate way" to impelment this, is to go into sql/operators.py and add a new suite of operators that apply to dates, such as "operations.dateadd".     then have Date._expression_adaptations DateTime._expression_adaptations etc. use those new operators.  then go into compiler.py and implement visit_op_dateadd(), etc.   if people want to work on this we might as well start implementing at least simple functions that are right there.   SQLite will require some wrapping of operands to make it work.

**Comment by gordthompson** [comment]
Okay, thanks for the pointers. To be clear, I wasn't suggesting a full implementation of +/- date arithmetic for drivers that don't natively support it like psycopg2 does …

``` python
cnxn = psycopg2.connect(
    host="192.168.0.199", user="scott", password="tiger", dbname="mydb"
)
crsr = cnxn.cursor()
crsr.execute("CREATE TABLE gh_sqla_5672 (id int primary key, dtm timestamp)")
crsr.execute(
    "INSERT INTO gh_sqla_5672 (id, dtm) VALUES (1, '2001-01-01 00:00:00')"
)
crsr.execute(
    "SELECT dtm + %s AS foo FROM gh_sqla_5672 WHERE id = 1",
    (datetime.timedelta(seconds=10),),
)
print(crsr.fetchone()[0])  # 2001-01-01 00:00:10
```

… I was looking for the most straightforward way to warn/raise if somebody tries it when the underlying database/DBAPI "doesn't do that". `mssql+pymssql` is actually the one particular case here because it returns an incorrect result without complaint; the other failing cases (`mssql+pyodbc`, `mysql`, and `sqlite`) will raise an exception which is a pretty good hint that the operation is not supported. ;)

**Comment by gordthompson** [comment]
In addition to the `dateadd` workaround/implementation for mssql above, the corresponding approaches for mysql and sqlite are:

### mysql

``` python
thing1 = Thing(id=1, dtm=datetime.datetime(2001, 1, 1, 1, 1, 1))
session.add(thing1)
session.commit()
print(thing1)  # <Thing(id=1, dtm=2001-01-01 01:01:01)>

# https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-add
session.query(Thing).update(
    {Thing.dtm: sa.func.date_add(Thing.dtm, sa.text("INTERVAL 10 SECOND"))},
    synchronize_session=False,
)
"""sql rendered:
UPDATE gh_sqla_5672 SET dtm=date_add(gh_sqla_5672.dtm, INTERVAL 10 SECOND)
"""
session.commit()
print(thing1)  # <Thing(id=1, dtm=2001-01-01 01:01:11)>
```

### sqlite

``` python
thing1 = Thing(id=1, dtm=datetime.datetime(2001, 1, 1, 1, 1, 1))
session.add(thing1)
session.commit()
print(thing1)  # <Thing(id=1, dtm=2001-01-01 01:01:01)>

# https://www.sqlite.org/lang_datefunc.html
session.query(Thing).update(
    {Thing.dtm: sa.func.datetime(Thing.dtm, sa.text("'+10 seconds'"))},
    synchronize_session=False,
)
"""sql rendered:
UPDATE gh_sqla_5672 SET dtm=datetime(gh_sqla_5672.dtm, '+10 seconds')
"""
session.commit()
print(thing1)  # <Thing(id=1, dtm=2001-01-01 01:01:11)>
```

**Comment by zzzeek** [comment]
I've reopened this back in #2769.  I still have no plans to work on it but we can point people at this issue when this comes up.

**Comment by gordthompson** [comment]
Currently not planned. See https://github.com/sqlalchemy/sqlalchemy/discussions/9949 for more information.
