### ISSUE TITLE
Error when parsing data from an Oracle database

### ISSUE THREAD

**Issue by daveisfera** [sqlalchemy/sqlalchemy#5673]
**Describe the bug**
Getting an error when parsing a date from an Oracle database

**Expected behavior**
Date would be selected without error

**To Reproduce**
Still working on making a minimal reproducer

**Error**
```
Traceback (most recent call last):
  File \"/usr/src/app/test.py\", line 149, in _ingest
    ingest(table_api, org=table['org'], ext=table['ext'],
  File \"/usr/src/app/test.py\", line 526, in ingest
    for row in self.process_query(conn, update_query, column, value, batch_size,
  File \"/usr/src/app/test.py\", line 601, in process_query
    for record in conn.execute(curr_query):
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 1010, in __iter__ 
    row = self.fetchone()
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 1343, in fetchone 
    self.connection._handle_dbapi_exception(
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py\", line 182, in raise_
    raise exception
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 1336, in fetchone 
    row = self._fetchone_impl()
  File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 1215, in _fetchone_impl
    return self.cursor.fetchone()
ValueError: day is out of range for month
```

**Versions.**
 - OS: Debian Buster
 - Python: 3.8.6
 - SQLAlchemy: 1.3.19
 - Database: Oracle 12.2.0.1.ru-2020-07.rur-2020-07.r1
 - DBAPI:cx-Oracle 8.0.1

**Additional context**
Value displays as `1899-12-31 00:00:00` in DataGrip

**Have a nice day!**

**Comment by zzzeek** [comment]
```
File \"/usr/src/app/venv/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 1215, in _fetchone_impl
    return self.cursor.fetchone()
ValueError: day is out of range for month
```

that cursor object is cx_oracle's cursor.  likely cx_oracle isn't able to parse / format an historical date.  you'd want to report over at https://github.com/oracle/python-cx_Oracle/issues .

though I can't reproduce is locally.  might have to do with your locale settings.

**Comment by zzzeek** [comment]
Oracle client library in use, such as instant client etc., look over notes on locale etc at https://cx-oracle.readthedocs.io/en/latest/user_guide/initialization.html#oracle-environment-variables

otherwise I'm not able to reproduce even by messing with the date formats.  the error message is in Python's source code and occurs if the given day is outside of the valid range for that month.

**Comment by daveisfera** [comment]
Ya, Im not totally sure what's causing the issue because I can insert values with that same date and older and it's just fine, so there must be something funky going on with the data and I'll keep digging in and get back to you.

**Comment by zzzeek** [comment]
can't reproduce and this seems like a cx_oracle issue.

**Comment by daveisfera** [comment]
This is an issue with `cx_oracle`, but they're unwilling to address it, so is there any way that we could workaround this or load dates differently with `sqlalchemy` to make this work?

**Comment by zzzeek** [comment]
im surprised they didnt suggest just CASTing to string to bypass the date value that can't be represented by Python's datetime, or just using an outconverter.  I asked on the issue about the outconverter part.

Without using an outconverter, depending on how much integration you need, just select([cast(mytable.c.date, String)]) would do it.

for the whole round trip i had to wire two typedecorators together, but I think a simple outconverter might be better here:

```
import datetime
from typing import Any

from sqlalchemy import cast
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Date
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy import TypeDecorator
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class StrDate(TypeDecorator):
    impl = Date

    def column_expression(self, column: Any):
        return cast(column, ReceiveStrDate())

class ReceiveStrDate(TypeDecorator):
    impl = String(20)

    def process_result_value(self, value: Any, dialect: Any) -> None:
        if value is not None:
            # TODO: handle invalid dates here
            value = datetime.datetime.strptime(value, "%d-%b-%y").date()
        return value



class Example(Base):
    __tablename__ = "example"

    id = Column(Integer, primary_key=True)
    value = Column(StrDate)

e = create_engine("oracle://scott:tiger@oracle1120", echo='debug')


Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add(Example(id=1, value=datetime.date(1980, 10, 15)))
s.commit()


print(s.query(Example.value).all())


```

**Comment by zzzeek** [comment]
here's the outconverter.  go with this version.

```python

import datetime
from typing import Any

from sqlalchemy import cast
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Date
from sqlalchemy import Integer, UnicodeText
from sqlalchemy import String
from sqlalchemy import TypeDecorator
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from sqlalchemy.dialects.oracle import cx_oracle
from sqlalchemy import event
import cx_Oracle


Base = declarative_base()


class Example(Base):
    __tablename__ = "example"

    id = Column(Integer, primary_key=True)
    value = Column(Date)


e = create_engine("oracle://scott:tiger@oracle1120", echo="debug")


@event.listens_for(e, "do_execute")
def do_execute(cursor, statement, parameters, context):
    outputtypehandler = cursor.outputtypehandler

    def date_outconverter(value):
        # TODO: handle invalid dates here
        value = datetime.datetime.strptime(value, "%d-%b-%y")
        return value

    def fix_dates(cursor, name, default_type, size, precision, scale):
        if default_type is cx_Oracle.DB_TYPE_DATE:
            return cursor.var(
                cx_Oracle.STRING,
                size,
                cursor.arraysize,
                outconverter=date_outconverter,
            )
        else:
            if outputtypehandler is None:
                return None
            return outputtypehandler(
                cursor, name, default_type, size, precision, scale
            )

    cursor.outputtypehandler = fix_dates


Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add(Example(id=1, value=datetime.date(1980, 10, 15)))
s.commit()


print(s.query(Example.value).all())

```

**Comment by daveisfera** [comment]
We call `create_engine` with a dynamic set of inputs and then use `MetaData` and `Table` to inspect the list of columns and such, so is there a way to do this same sort of registration of type handling with a dynamic call like that?

**Comment by zzzeek** [comment]
the outputtypehandler recipe above is based on Oracle data type codes, so it doesnt need to be concerned with SQLAlchemy metadata/table concepts.      as for the event itself you can either register it on a per-engine basis, right after you call create_engine(), or you can apply it to the Engine class as a whole.    I don't understand how the call being "dynamic" affects any of this.

**Comment by daveisfera** [comment]
Sorry, I'm not familiar with the details of how this is being done in the code and `@event.listens_for(e, "do_execute")` has `e` from the call to `create_engine`, so I'm not sure how to set this up for our use case that calls `create_engine` to connect to different databases based on the args that are passed into the function. Is there documentation of how to do this?

**Comment by zzzeek** [comment]
in the example above, the create_engine() call is used to create a new SQLAlchemy engine.   directly below that call, the event handler is attached:

```

e = create_engine("oracle://scott:tiger@oracle1120", echo="debug")

@event.listens_for(e, "do_execute")
def do_execute(cursor, statement, parameters, context):
    outputtypehandler = cursor.outputtypehandler

    # rest of example
```

so in your application, at the point at which create_engine is called, you would place the event handler code directly below it.

if you are using create_engine() for databases that are **not** Oracle as well, then you may place the event handler conditionally as follows:

```

e = create_engine("oracle://scott:tiger@oracle1120", echo="debug")

if e.name == "oracle":
    @event.listens_for(e, "do_execute")
    def do_execute(cursor, statement, parameters, context):
        outputtypehandler = cursor.outputtypehandler

        # rest of example

```
I hope this clarifies.

**Comment by daveisfera** [comment]
Oh ok. That's some Python magic that I wasn't familiar with and I didn't realize that the `@event` decorator could be used like that, so I tried that and it's working. Thanks a ton for your help on this!

So I can make sure we're handling this correctly, what's the right way to handle errors there? Basically, should exceptions be raised from that function when the data is invalid? Or should they be caught and `None` returned?

**Comment by zzzeek** [comment]
the behavior of cx_Oracle right now is to raise an exception and that's what you were looking to change, right?   There's no "correct" answer for this issue as you have a database with invalid dates in it for some reason. so you'd need to understand why those invalid dates are there and if they mean something to people who are consuming this data.       if you truly wanted the behavior of other tools that you've mentioned, you'd probably just return the dates as strings, since I'd assume that's what they are doing, as the data is not representable in a proper date object.
