### ISSUE TITLE
Can you Update a Primary Key value using ORM

### ISSUE THREAD

**Issue by dragid10** [sqlalchemy/sqlalchemy#5678]
**Update Primary Key value using ORM**

Is it possible to do an update on the Primary key column like such using ORM? In this example, the where clause utilizes the same Primary key column to do the search, and if the value of the column has changed, then it won't be able to find the record to Update. 

Context: We have a database that uses a covering index and the INCLUDE column is being treated as a primary key (basically as described here https://github.com/sqlalchemy/sqlalchemy/issues/4458#issuecomment-685071660), so I wanted to see if there was a way to either: 
1. Ignore the fake PK when initiating a record update
OR
2. Update the proper record's fake PK value 

I also know that this might not be the greatest plan for schema definition, but I have to work with how its designed.

Let me know if you need anymore information and I'd be happy to provide it 

```
from sqlalchemy import Column, create_engine, Integer, MetaData, String, Table
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

Base = automap_base()
metadata = MetaData()


class User(Base):
    __tablename__ = 'user'

    def __init__(self, id, test_id, name="Charles E.", row_status_cd="I"):
        self.id = id
        self.test_id = test_id
        self.name = name
        self.row_status_cd = row_status_cd

    id = Column(Integer, primary_key=True, unique=True)
    test_id = Column(Integer, primary_key=True, unique=True)
    name = Column(String)
    row_status_cd = Column(String)


engine = create_engine("sqlite:///:memory:", echo=True)

# Create table to demonstrate real table configuration. The actual table I'm working with cannot be modified by me
user = Table('user', metadata,
             Column("id", String, primary_key=True, unique=True),
             Column("test_id", String, primary_key=True, unique=True),
             Column("name", String),
             Column("row_status_cd", String, primary_key=True))

metadata.create_all(engine, checkfirst=True)

Base.prepare(engine, reflect=True)

session = Session(engine)

if __name__ == '__main__':
    # Add a record to the DB first to demonstrate scenario
    u1 = User("Pizza", "Pizza", "")
    session.add(u1)
    session.commit()
    session.flush()
    session.query(User).filter(User.id == "Pizza").first()

    # Try to update record's primary key
    u1.test_id = "cheese"
    u1.row_status_cd = "U"
    session.bulk_save_objects([u1], update_changed_only=True)
    print(session.query(User).filter(User.id == "Pizza").first())
```

**Versions**
 - OS: MacOS
 - Python: 3.7
 - SQLAlchemy: 1.3.20
 - Database: DB2
 - DBAPI: ibm_db_sa

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

the issue looks like you are using the bulk_save_objects() utility which I would recommend against using.  These routines IMO were a mistake to create in the first place as their presence seems to confuse people, and it appears it is not working for primary key switches, not too surprising but I should add a caveat at https://docs.sqlalchemy.org/en/13/orm/persistence_techniques.html#bulk-operations , as though there aren't enough caveats there already.   the "bulk" routines do not know the correct primary key of the row given if you are changing it so it cannot locate the row. will add a note.

If you remove the bulk_save_objects() and just rely on regular autoflush, primary key changes work just fine (though I can't speak for what limitations DB2 might have).   example below illustrates.

```
from sqlalchemy import Column, create_engine, Integer, MetaData, String, Table
from sqlalchemy.orm import Session
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

metadata = MetaData()


class User(Base):
    __tablename__ = "user"

    def __init__(self, id, test_id, name="Charles E.", row_status_cd="I"):
        self.id = id
        self.test_id = test_id
        self.name = name
        self.row_status_cd = row_status_cd

    id = Column(Integer, primary_key=True, unique=True)
    test_id = Column(Integer, primary_key=True, unique=True)
    name = Column(String)
    row_status_cd = Column(String)


engine = create_engine("sqlite:///:memory:", echo=True)

user = Table(
    "user",
    metadata,
    Column("id", String, primary_key=True, unique=True),
    Column("test_id", String, primary_key=True, unique=True),
    Column("name", String),
    Column("row_status_cd", String, primary_key=True),
)

metadata.create_all(engine, checkfirst=True)

session = Session(engine)

if __name__ == "__main__":
    # Add a record to the DB first to demonstrate scenario
    u1 = User("Pizza", "Pizza", "")
    session.add(u1)
    session.commit()
    session.flush()
    session.query(User).filter(User.id == "Pizza").first()

    # Try to update record's primary key
    u1.test_id = "cheese"
    u1.row_status_cd = "U"
    print(session.query(User).filter(User.id == "Pizza").first())

```

**Comment by zzzeek** [comment]
I will make it more prominent but this is already documented:  https://docs.sqlalchemy.org/en/13/orm/persistence_techniques.html#bulk-operations

> The bulk insert / update methods lose a significant amount of functionality versus traditional ORM use. The following is a listing of features that are not available when using these methods:

>   Functionality related to **primary key mutation**, ON UPDATE cascade

**Comment by dragid10** [comment]
Sorry I definitely must've missed that particular warning.

Follow-up question: Is there another way to achieve bulk operations then? bulk_save_objects definitely did what I needed it to do (barring this scenario). Would you just recommended iterating through the list of objects I need to load and it'll be fine?

**Comment by zzzeek** [comment]
> Sorry I definitely must've missed that particular warning.
> 
> Follow-up question: Is there another way to achieve bulk operations then? bulk_save_objects definitely did what I needed it to do (barring this scenario). Would you just recommended iterating through the list of objects I need to load and it'll be fine? And would doing it this way still only use a single database transaction?

the Session automatically flushes whatever changes you make when you commit or query, or if you call flush().   the only reason you'd use bulk_save_objects() is because you have tens of thousands of rows to update at once and you're trying to reduce the Python overhead in how long the unit of work takes to do things.  if you are perceiving bulk_save_objects() as doing something that nothing else in the ORM does, then the docs have misled you which is why i just made that top warning more explicit and bold.   

if you have the problem of tens of thousands of rows to update and it's too slow to run flush(), then I suggest using a plain Core insert() and/or update() with executemany syntax, see https://docs.sqlalchemy.org/en/13/core/tutorial.html#executing-multiple-statements for an example.

better tutorial docs are coming for some of this stuff in 1.4.

**Comment by dragid10** [comment]
Thanks for taking the time to reply and educate me!
