### ISSUE TITLE
TABLESAMPLE system_time support for SELECT statements

### ISSUE THREAD

**Issue by PrimozGodec** [sqlalchemy/sqlalchemy#5680]
**Describe your question**

In PostgreSQL, MySQL, MSSQL and probably some other databases have option to use `TABLESAMPLE system_time(<time in ms>)` in `SELECT` queries. It will query the number of **random** rows it can read in a specified amount of time. I am using core SQLAlchemy (not ORM) and cannot find this option in the documentation. I can find TABLESAMPLE but not in combination with `system_time`. Is it possible to use this option with SQLAlchemy? Is there any other option to get a number of rows that can be retrieved in a certain amount of time? 

**Example - please use the [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) guidelines if possible**
SELECT * FROM Inventory TABLESAMPLE system_time(1000)

This query will take the number of rows that it can retrieve in 1000 ms. 

Thank you in advance.

**Comment by zzzeek** [comment]
hi there -

TABLESAMPLE allows any arbitrary SQL function as input, for example the the example at https://docs.sqlalchemy.org/en/13/core/selectable.html#sqlalchemy.sql.expression.tablesample shows the "bernoulli" function in use.  you can name any function you'd like from the [func](https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=func#sqlalchemy.sql.expression.func) namespace.
```

>>> from sqlalchemy import select, func, table, column
>>> inventory = table('inventory', column('x'))
>>> sample = inventory.tablesample(func.system_time(1000))
>>> stmt = select([sample])
>>> print(stmt)
SELECT inventory_1.x 
FROM inventory AS inventory_1 TABLESAMPLE system_time(:system_time_1)

```

**Comment by PrimozGodec** [comment]
Thank you. Somehow I didn't find that `func.system_time` exists.

**Comment by zzzeek** [comment]
right there is no way to search for it because SQL functions are generated based on the name you give to [func](https://docs.sqlalchemy.org/en/13/core/sqlelement.html?highlight=func#sqlalchemy.sql.expression.func)

**Comment by PrimozGodec** [comment]
Ok, thank you. :)
