### ISSUE TITLE
1.4 takes three times as long to import

### ISSUE THREAD

**Issue by layday** [sqlalchemy/sqlalchemy#5681]
As I use SQLAlchemy in a CLI, the first thing I noticed when upgrading to the 1.4 beta is that it took quite a bit longer to import.  I have run `python -X importtime -c 'import sqlalchemy'` under Python 3.9 on macOS with SQLAlchemy 1.3.20 and 1.4.0b1 and uploaded the output on [Gist](https://gist.github.com/layday/52843dde1149bc45cf1120da5d87fc7a).  You can use a tool like [tuna](https://pypi.org/project/tuna/) to visualise the import profile.  I am not immediately able to tell what might've caused the slowdown but it is quite severe (120ms vs 320ms).

**Comment by zzzeek** [comment]
just a quick glance it looks like asyncio and greenlet, which we can work on getting that all to not import if not used.  can you inspect the gist more carefully to see if the asyncio package is the culprit?   and/or comment it out and see if that resolves.  thanks!

**Comment by CaselIT** [comment]
It seems that asyncio adds about 40ms.
I get ~130ms for 13, ~300ms for 14 and 260ms for 14 without asyncio.

So there is still something else that makes the it import in twice the time

**Comment by layday** [comment]
I don't think asyncio is the culprit - it appears to be something related to the sql sub-package - perhaps something that's being imported dynamically?  In the past I've found the pre-compilation of regexes to slow down imports significantly but commenting out the compiler module had no visible effect.

**Comment by zzzeek** [comment]
asyncio seems to be a chunk of it.

there's a lot of dynamic code writing that happens in sql/ however and this might be what you're seeing.  SQLAlchemy is optimized for long running applications and that code writing is a big part of it so there unfortunately may not be much that can be done here.

**Comment by CaselIT** [comment]
Running tuna (nice tool btw) I get this

1.4
![image](https://user-images.githubusercontent.com/16175304/97925963-980e3300-1d62-11eb-803e-0e9e1ed19241.png)
1.3
![image](https://user-images.githubusercontent.com/16175304/97925998-a8261280-1d62-11eb-8542-fd1afbd752c3.png)

so it seems that utils takes 2x the time (50ms -> 100ms) and that's asyncio. But most of the gain is from sql

**Comment by zzzeek** [comment]
I will put up a gerrit that shows how to not use the on-import code generation.  but then we have much slower runtime code.   something to work wtih at least

**Comment by layday** [comment]
It looks like `_prepare_annotations` has the biggest part to play here but I can't tell what's changed from 1.3.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Demonstrate traversal functions calculating at runtime** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2342

**Comment by zzzeek** [comment]
the above gerrit takes the time back off of the "sqlalchemy.sql" part of this if I'm reading  the outputs of this test directly.

**Comment by CaselIT** [comment]
yes, I get ~220ms with that patch

**Comment by zzzeek** [comment]
prepare_annotations is not new in 1.4 and looks to be the same thing in 1.3.   but it creates classes and the creation of the classes probably hits all the code generation stuff.

**Comment by layday** [comment]
Well, that was quick!  Running the patch locally, 1.4 now takes about 220 ms to import, which is a substantial improvement.  The remaining difference appears to originate from `sql.compiler`.

**Comment by zzzeek** [comment]
yeah but I can't merge like that.   the functions would have to be written in C, or some kind of special magic to make them figure themselves out at runtime, or something to gain back the performance changes.  the latter function is used to generate cache keys which is a super critical function.

**Comment by zzzeek** [comment]
is tuna looking at cprofile files ? i dont see how to use this yet

**Comment by layday** [comment]
tuna takes the output of `python -X importtime ...` (or `PYTHONPROFILEIMPORTTIME=1 python ...`) which was added to the interpreter in 3.7.

**Comment by CaselIT** [comment]
The time is lost in ` _generate_dispatcher`. `_generate_compiler_dispatch` dynamic vs eval, makes basically no difference

for tuna
```
python -X importtime -c 'import sqlalchemy' 2> import14.log
tuna import14.log
```

**Comment by layday** [comment]
> The time is lost in ` _generate_dispatcher`. `_generate_compiler_dispatch` dynamic vs eval, makes basically no difference

Is that because `_generate_dispatcher` is slower (i.e. can it be optimised?) or just because it's hit more times?

**Comment by zzzeek** [comment]
the compiler dispatch one might not be a problem.  the _generate_dispatcher one is the big one

**Comment by layday** [comment]
`_generate_compiler_dispatch` is called 128 in total vs 1735 for `_generate_dispatcher` on import.

**Comment by CaselIT** [comment]
indeed, the `_generate_dispatcher` was not in 1.3. That's used to generate the new cache key if I understand that correctly.

**Comment by zzzeek** [comment]
yeah here is SQLAlchemy 1.4.0b1:
```

[classic@photon3 sqlalchemy]$ python -m examples.performance short_selects --test test_orm_query_new_style
Tests to run: test_orm_query_new_style
test_orm_query_new_style : new style ORM select() of the full entity. (10000 iterations); total time 3.245393 sec
[classic@photon3 sqlalchemy]$ python -m examples.performance short_selects --test test_orm_query_new_style
Tests to run: test_orm_query_new_style
test_orm_query_new_style : new style ORM select() of the full entity. (10000 iterations); total time 3.175400 sec
[classic@photon3 sqlalchemy]$ python -m examples.performance short_selects --test test_orm_query_new_style
Tests to run: test_orm_query_new_style
test_orm_query_new_style : new style ORM select() of the full entity. (10000 iterations); total time 3.247593 sec
[classic@photon3 sqlalchemy]$ python -m examples.performance short_selects --test test_orm_query_new_style
Tests to run: test_orm_query_new_style
test_orm_query_new_style : new style ORM select() of the full entity. (10000 iterations); total time 3.162513 sec

```

here's with the patch:

```
$ python -m examples.performance short_selects --test test_orm_query_new_style
Tests to run: test_orm_query_new_style
test_orm_query_new_style : new style ORM select() of the full entity. (10000 iterations); total time 3.569015 sec
[classic@photon3 sqlalchemy]$ python -m examples.performance short_selects --test test_orm_query_new_style
Tests to run: test_orm_query_new_style
test_orm_query_new_style : new style ORM select() of the full entity. (10000 iterations); total time 3.514611 sec
[classic@photon3 sqlalchemy]$ python -m examples.performance short_selects --test test_orm_query_new_style
Tests to run: test_orm_query_new_style
test_orm_query_new_style : new style ORM select() of the full entity. (10000 iterations); total time 3.511829 sec

```

so that is an 8% slowdown for runtime performance.    I'd prefer to be faster than 1.4.0b1 if possible.

**Comment by CaselIT** [comment]
Commenting just `_preconfigure_traversals` in `sql/__init__.py` from 1.4 instead?

**Comment by zzzeek** [comment]
oh right, it can go at runtime right?  hmmm.

i just pushed another version of "dynamic" that is almost as good, should just write it in C

**Comment by CaselIT** [comment]
> 
> 
> Commenting just `_preconfigure_traversals` in `sql/__init__.py` from 1.4 instead?

I get no difference with commenting it, and the import time is 220ms

**Comment by CaselIT** [comment]
> oh right, it can go at runtime right? hmmm.

yes, it gets generated the first time

**Comment by layday** [comment]
I've no real understanding of what's going on here but I can see that some classes and symbols are compiled repeatedly, e.g. the combination of

```
(
    <class 'sqlalchemy.sql.annotation.Annotatedpercentile_cont'>,
    [('clause_expr', symbol('CE')), ('packagenames', symbol('PO')), ('name', symbol('S')), ('type', symbol('T')), ('_annotations', symbol('AK'))]
)
```

was compiled 11 times in `InternalTraversal.generate_dispatch`.

**Comment by zzzeek** [comment]
well that's certainly wrong, would have to trace if that's the class being generated needlessly perhaps

**Comment by zzzeek** [comment]
OK I have some more improvements coming but I think part of the time is all the elaborate deprecation warnings we have right now that set up as decorators at import time.  they are using eval() also and we have a lot more of them.

**Comment by zzzeek** [comment]
OK latest version fixes the class traversal problem and seems like it's around 50% slower than 1.3 once you get the .pyc files warmed up.

at this point the decorators for the deprecations might be a part of it, asyncio comes up on the graph as about 16% if which is not nothing but we're really have to rearrange things to get that to be not needed.

just FTR pandas comes in 567 ms so we are not the worst :)

**Comment by CaselIT** [comment]
does the `_generate_compiler_dispatch` change have the same performance compared to the eval one?

**Comment by zzzeek** [comment]
the compiler dispatch one is fairly negligible because it's one call only, and compiled things are cached now.

the traversals OTOH is a definite speed bump because that's the generation of the cache key.  cache key generation is already not fast enough so moving at least the cache key traversal to be more in C is something I wanted to look into.   also using a real C swtich statement for this: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/traversals.py#L159


what is the level of "import time" we want to shoot for here?    for me anything less than 500ms is fine cc @layday

**Comment by CaselIT** [comment]
I think `50% slower than 1.3` is fine. 200% to 50% is already a great gain.

I guess we could lazily import asyncio and that would leave us about even with 1.3

**Comment by layday** [comment]
For an operation to feel instantaneous, it needs to complete in < 100 ms (there were some studies done on human perception of real time-ness), but that's obviously not realistic here.  Import time has been a long-standing issue in Python and it's not SQLAlchemy's job to fix it - just to try not to exacerbate it.  If I have to print a simple list of items in a database and the command takes something in the order of 600-800 ms to complete (500ms for SQLAlchemy + 100-300 ms for whatever else I might be depending on), that's not great.  I think what you had in 1.3 is a decent baseline.

**Comment by zzzeek** [comment]
I'd love to get there but i wasnt seeing an easy way to do it, perhaps if all those deprecation decorators were faster, or if they could be disabled by an env variable...99% go away in 2.0 so there's that.  this is assuming the deprecation decorators are the remaining extra time (that and asyncio which I think i might still try to make import on demand)

**Comment by zzzeek** [comment]
have asyncio deferred, that improves things.

next is definitely util.deprecated_params().  this is clearly a big one.  If I remove it just from one function in sqlalchemy.engine.create:

```
[classic@photon3 sqlalchemy]$ python -X importtime -c "import sqlalchemy" 2>&1 | grep create
import time:       235 |       3321 |     sqlalchemy.engine.create

```

add it back in:

```
[classic@photon3 sqlalchemy]$ python -X importtime -c "import sqlalchemy" 2>&1 | grep create
import time:      2097 |       5911 |     sqlalchemy.engine.create

```

this is going to be slowing down 1.3 also.  we just have a lot more of those now in 1.4.

**Comment by CaselIT** [comment]
what's the time with asyncio deferred?

I'm not sure it's worth it trying to optimize `deprecated_params`

**Comment by zzzeek** [comment]
im going to put some simple optimizations into it without going too crazy

**Comment by zzzeek** [comment]
so @layday we've improved things but it's still not as good as 1.3.   much more digging would be needed to get it much better.

**Comment by layday** [comment]
Thanks for working on this.
