### ISSUE TITLE
Have a documentation link referencing the latest release

### ISSUE THREAD

**Issue by PhilippSelenium** [sqlalchemy/sqlalchemy#5682]
**Is your feature request related to a problem? Please describe.**
Since https://docs.sqlalchemy.org/en/latest/ references the state of the master branch using it as intersphinx mapping breaks the doc build for every change on master

**Describe the solution you'd like**
Have a redirect https://docs.sqlalchemy.org/en/stable/ that references the latest release so the intersphinx mapping doesn't have to be changed for every release. 

**Describe alternatives you've considered**
Updating the intersphinx mapping for every release (https://docs.sqlalchemy.org/en/14/) (which is quite tedious)

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
good idea.

**Comment by zzzeek** [comment]
I had changed "latest" to point to master yesterday b.c. otherwise i had no way to link to the most recent changelogs.

**Comment by zzzeek** [comment]
/stable/ should be working the same as /latest/

https://docs.sqlalchemy.org/stable/
https://www.sqlalchemy.org/docs/stable/
https://docs.sqlalchemy.org/en/stable/

**Comment by PhilippSelenium** [comment]
@zzzeek Thanks
