### ISSUE TITLE
Sorting by hybrid_property with custom comparator

### ISSUE THREAD

**Issue by Peter92** [sqlalchemy/sqlalchemy#5683]
I have a model with the columns `short_name` and `long_name`, where a [custom comparator](https://docs.sqlalchemy.org/en/13/orm/extensions/hybrid.html#building-custom-comparators) on `name` allows me to query both at once.

I previously used it as an expression and could order the hybrid property in queries. I would like to be able to retain the ability to order when using a comparator instead of an expression.

I don't know how possible this would be, but considering expression hybrid properties can be sorted just fine, it seems like it should technically be doable when using comparator hybrid properties too.

**Current result:**

```
>>> session.query(Model).order_by(Model.name)

Traceback (most recent call last):
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\orm\query.py", line 1872, in order_by
    criterion = self._adapt_col_list(criterion)
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\orm\query.py", line 334, in _adapt_col_list
    for o in cols
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\orm\query.py", line 334, in <listcomp>
    for o in cols
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\sql\elements.py", line 4549, in _literal_as_label_reference
    return _literal_as_text(element)
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\sql\elements.py", line 4592, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\sql\elements.py", line 4584, in _literal_as
    "instead" % type(element)
sqlalchemy.exc.ArgumentError: SQL expression object expected, got object of type <class 'sqlalchemy.ext.declarative.api.DeclarativeMeta'> instead
```

**Requested result (simple):**
```python
class CustomComparator(Comparator):
    def order_by(self, op):
        model = self.__clause_element__()
        return op(model.short_name)

>>> session.query(Model).order_by(Model.name.desc())
ORDER BY model.short_name DESC
```

**Requested result (advanced):**
```python
class CustomComparator(Comparator):
    def order_by(self, op):
        # I'm not really sure of how the syntax would work here
        model = self.__clause_element__()
        if model.long_name is None:
            return op(model.long_name)
        return op(model.short_name), op(model.long_name)
        
>>> session.query(Model).order_by(Model.name.desc())
ORDER BY CASE WHEN (model.long_name IS NOT NULL) THEN model.long_name DESC, model.short_name DESC ELSE model.short_name END
```

**Trimmed down version of my current code:**

```python
class Model(Base):
    short_name = Column(String(8, collation='NOCASE'), nullable=False, primary_key=True)
    long_name = Column(String(64, collation='NOCASE'), nullable=True)

    @hybrid_property
    def name(self):
        if self.long_name is None:
            return self.short_name
        return self.long_name

    @name.expression
    def name(cls):
        """This was the OLD way, which I stopped using as I'd prefer to query both fields at once."""
        return case([(cls.long_name!=None, cls.long_name)], else_=cls.short_name)

    @name.comparator
    def name(cls):
        """This is the new way."""
        return CustomComparator(cls)


class CustomComparator(Comparator):
    def __eq__(self, name):
        cls = self.__clause_element__()
        return or_(cls.long_name==name, cls.short_name==name)

    def __ne__(self, name):
        cls = self.__clause_element__()
        return and_(
            cls.long_name!=name,
            cls.short_name!=name,
        )

    def like(self, name, **kwargs):
        cls = self.__clause_element__()
        return or_(
            cls.long_name.like(name, **kwargs),
            cls.short_name.like(name, **kwargs),
        )

    def ilike(self, name, **kwargs):
        cls = self.__clause_element__()
        return or_(
            cls.long_name.ilike(name, **kwargs),
            cls.short_name.ilike(name, **kwargs),
        )
```

**Comment by sqla-tester** [comment]
can you provide for me a single script that I can just run and produces the stack trace?  also can you try 1.4.0 beta1 as this has to do with coercion and it might be different there.   thanks




On Thu, Nov 5, 2020, at 12:31 PM, Peter Hunt wrote:
> 

> I have a model with the columns `short_name` and `long_name`, where a custom comparator <https://docs.sqlalchemy.org/en/13/orm/extensions/hybrid.html#building-custom-comparators> on `name` allows me to query both at once.

> I previously used it as an expression and could sort by the column. I would like to be able to retain the ability to sort when using a comparator instead of an expression.

> *Current result*

> `>>> session.query(Model).order_by(Model.name)

Traceback (most recent call last):
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\orm\query.py", line 1872, in order_by
    criterion = self._adapt_col_list(criterion)
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\orm\query.py", line 334, in _adapt_col_list
    for o in cols
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\orm\query.py", line 334, in <listcomp>
    for o in cols
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\sql\elements.py", line 4549, in _literal_as_label_reference
    return _literal_as_text(element)
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\sql\elements.py", line 4592, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "C:\bz_pipeline\resources\lib\python\site-packages\sqlalchemy\sql\elements.py", line 4584, in _literal_as
    "instead" % type(element)
sqlalchemy.exc.ArgumentError: SQL expression object expected, got object of type <class 'sqlalchemy.ext.declarative.api.DeclarativeMeta'> instead
`
> *Requested result (simple)*

> class CustomComparator(Comparator):
    def order_by(self, op):
        model = self.__clause_element__()
        return op(model.short_name)

> >>> session.query(Model).order_by(Model.name.desc())
> ORDER BY model.short_name DESC
> *Requested result (advanced)*

> class CustomComparator(Comparator):
    def order_by(self, op):
        # I'm not really sure of how the syntax would work here
        model = self.__clause_element__()
        if model.long_name is None:
            return op(model.long_name)
        return op(model.short_name), op(model.long_name)
        
> >>> session.query(Model).order_by(Model.name.desc())
> ORDER BY CASE WHEN (model.long_name IS NOT NULL) THEN model.long_name DESC, model.short_name DESC ELSE model.short_name END
> *Example code*

> class Model(Base):
    short_name = Column(String(8, collation='NOCASE'), nullable=False, primary_key=True)
    long_name = Column(String(64, collation='NOCASE'), nullable=True)

    @hybrid_property
    def name(self):
        if self.long_name is None:
            return self.short_name
        return self.long_name

    @name.expression
    def name(cls):
        """This was the OLD way, which I stopped using as I'd prefer to query both fields at once."""
        return case([(cls.long_name!=None, cls.long_name)], else_=cls.short_name)

    @name.comparator
    def name(cls):
        """This is the new way."""
        return CustomComparator(cls)


> class CustomComparator(Comparator):
    def __eq__(self, name):
        cls = self.__clause_element__()
        return or_(cls.long_name==name, cls.short_name==name)

    def __ne__(self, name):
        cls = self.__clause_element__()
        return and_(
            cls.long_name!=name,
            cls.short_name!=name,
        )

    def like(self, name, **kwargs):
        cls = self.__clause_element__()
        return or_(
            cls.long_name.like(name, **kwargs),
            cls.short_name.like(name, **kwargs),
        )

    def ilike(self, name, **kwargs):
        cls = self.__clause_element__()
        return or_(
            cls.long_name.ilike(name, **kwargs),
            cls.short_name.ilike(name, **kwargs),
        )

**Comment by Peter92** [comment]
Here's some working code:

```python
from sqlalchemy import Column, Integer, String, create_engine, and_, or_
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property, Comparator
Base = declarative_base()
Engine = create_engine('sqlite://')
Session = sessionmaker(Engine)


class SomeClass(Base):
    __tablename__ = 'some_table'
    id = Column(Integer, primary_key=True)
    short_name = Column(String(8, collation='NOCASE'), nullable=False, primary_key=True)
    long_name = Column(String(64, collation='NOCASE'), nullable=True)

    @hybrid_property
    def name(self):
        if self.long_name is None:
            return self.short_name
        return self.long_name

    @name.comparator
    def name(cls):
        """This is the new way."""
        return CustomComparator(cls)


class CustomComparator(Comparator):
    def __eq__(self, name):
        cls = self.__clause_element__()
        return or_(cls.long_name==name, cls.short_name==name)

    def __ne__(self, name):
        cls = self.__clause_element__()
        return and_(
            cls.long_name!=name,
            cls.short_name!=name,
        )

    def like(self, name, **kwargs):
        cls = self.__clause_element__()
        return or_(
            cls.long_name.like(name, **kwargs),
            cls.short_name.like(name, **kwargs),
        )

    def ilike(self, name, **kwargs):
        cls = self.__clause_element__()
        return or_(
            cls.long_name.ilike(name, **kwargs),
            cls.short_name.ilike(name, **kwargs),
        )

Base.metadata.create_all(Engine)


session = Session()
session.query(SomeClass).order_by(SomeClass.name)
```

In 1.4.0 the exception is still there with different wording:
```
Traceback (most recent call last):
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\sql\base.py", line 96, in _generative
    x = fn(self, *args, **kw)
  File "<string>", line 2, in order_by
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\base.py", line 225, in generate
    fn(self, *args[1:], **kw)
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\query.py", line 1697, in order_by
    for clause in clauses
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\query.py", line 1697, in <genexpr>
    for clause in clauses
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\sql\coercions.py", line 181, in expect
    original_element, resolved, argname=argname, **kw
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\sql\coercions.py", line 296, in _implicit_coercions
    if not resolved.is_clause_element:
AttributeError: 'function' object has no attribute 'is_clause_element'
```

I would assume it's not doable right at this second as the documentation doesn't really cover much about hybrid property comparators.

**Comment by sqla-tester** [comment]
OK, so this is just that the Comparator should be based around the expression that you'd like it to represent, and not the class itself.    The single argument it accepts "expr" is what is returned from __clause_element__() and that's what order_by() and anything else would be using in order to get the "default" SQL expression for the object.  so if we change as follows it may be accepted:

class CustomComparator(Comparator):
    def __init__(self, cls):
        expr = case(
            [(cls.long_name != None, cls.long_name)], else_=cls.short_name
        )
        super().__init__(expr)
        self.cls = cls

    def __eq__(self, name):
        cls = self.cls
        return or_(cls.long_name == name, cls.short_name == name)

    def __ne__(self, name):
        cls = self.cls
        return and_(
            cls.long_name != name,
            cls.short_name != name,
        )

    def like(self, name, **kwargs):
        cls = self.cls
        return or_(
            cls.long_name.like(name, **kwargs),
            cls.short_name.like(name, **kwargs),
        )

    def ilike(self, name, **kwargs):
        cls = self.cls
        return or_(
            cls.long_name.ilike(name, **kwargs),
            cls.short_name.ilike(name, **kwargs),
        )


then your script gives me a query like

SELECT some_table.id AS some_table_id, some_table.short_name AS some_table_short_name, some_table.long_name AS some_table_long_name 
FROM some_table ORDER BY CASE WHEN (some_table.long_name IS NOT NULL) THEN some_table.long_name ELSE some_table.short_name END

SQLAlchemy 1.3 and 1.4.



On Thu, Nov 5, 2020, at 12:45 PM, Peter Hunt wrote:
> 

> Here's some working code:

> from sqlalchemy import Column, Integer, String, create_engine, and_, or_
> from sqlalchemy.orm import sessionmaker
> from sqlalchemy.ext.declarative import declarative_base
> from sqlalchemy.ext.hybrid import hybrid_property, Comparator
> Base = declarative_base()
> Engine = create_engine('sqlite://')
> Session = sessionmaker(Engine)


> class SomeClass(Base):
    __tablename__ = 'some_table'
    id = Column(Integer, primary_key=True)
    short_name = Column(String(8, collation='NOCASE'), nullable=False, primary_key=True)
    long_name = Column(String(64, collation='NOCASE'), nullable=True)

    @hybrid_property
    def name(self):
        if self.long_name is None:
            return self.short_name
        return self.long_name

    @name.comparator
    def name(cls):
        """This is the new way."""
        return CustomComparator(cls)


> class CustomComparator(Comparator):
    def __eq__(self, name):
        cls = self.__clause_element__()
        return or_(cls.long_name==name, cls.short_name==name)

    def __ne__(self, name):
        cls = self.__clause_element__()
        return and_(
            cls.long_name!=name,
            cls.short_name!=name,
        )

    def like(self, name, **kwargs):
        cls = self.__clause_element__()
        return or_(
            cls.long_name.like(name, **kwargs),
            cls.short_name.like(name, **kwargs),
        )

    def ilike(self, name, **kwargs):
        cls = self.__clause_element__()
        return or_(
            cls.long_name.ilike(name, **kwargs),
            cls.short_name.ilike(name, **kwargs),
        )

> Base.metadata.create_all(Engine)


> session = Session()
> session.query(SomeClass).order_by(SomeClass.name)
> In 1.4.0 the exception is still there with different wording:

> `Traceback (most recent call last):
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\sql\base.py", line 96, in _generative
    x = fn(self, *args, **kw)
  File "<string>", line 2, in order_by
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\base.py", line 225, in generate
    fn(self, *args[1:], **kw)
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\query.py", line 1697, in order_by
    for clause in clauses
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\orm\query.py", line 1697, in <genexpr>
    for clause in clauses
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\sql\coercions.py", line 181, in expect
    original_element, resolved, argname=argname, **kw
  File "C:\Users\peterh\AppData\Roaming\Python\Python37\site-packages\sqlalchemy\sql\coercions.py", line 296, in _implicit_coercions
    if not resolved.is_clause_element:
AttributeError: 'function' object has no attribute 'is_clause_element'
`

**Comment by zzzeek** [comment]
just noticed this was a github issue and not a sqlalchemy list email!  explains a lot. sqla-tester is me :)

**Comment by Peter92** [comment]
Haha, I guessed from the formatting it was someone not on github, though I thought it meant you had a small team of testers. That also just so happened to be the one time I accidentally posted before it was ready, so I assume the edits didn't come though.

Thanks for the solution anyway, that's a ton simpler than what I was expecting. Knowing that makes a lot more sense too, I thought `__clause_element__()` was just an odd way of accessing the attribute lol. I originally started passing in the model as I had trouble making `has()` and `any()` work when passing in a column, hadn't realised there'd be knock on effects.

I imagine it's probably not worth adding any extra info to the docs so I'll give this a close, cheers again :)

**Comment by zzzeek** [comment]
> Haha, I guessed from the formatting it was someone not on github, though I thought it meant you had a small team of testers. That also just so happened to be the one time I accidentally posted before it was ready, so I assume the edits didn't come though.
> 
> Thanks for the solution anyway, that's a ton simpler than what I was expecting. Knowing that makes a lot more sense too, I thought `__clause_element__()` was just an odd way of accessing the attribute lol. I originally started passing in the model as I had trouble making `has()` and `any()` work when passing in a column, hadn't realised there'd be knock on effects.
> 
> I imagine it's probably not worth adding any extra info to the docs so I'll give this a close, cheers again :)

the example shows it though it doesn't say explicitly "this is what we're doing": https://docs.sqlalchemy.org/en/14/orm/extensions/hybrid.html#building-custom-comparators   note that a column expression is passed in, not the class.    the docstring at https://docs.sqlalchemy.org/en/14/orm/extensions/hybrid.html#sqlalchemy.ext.hybrid.Comparator should point to that doc section and should have a parameter description of the arguments, it's named "expression" but that's not enough.

**Comment by Peter92** [comment]
> note that a column expression is passed in

To be honest, that's actually the part that threw me off a little. I read the example as "pass a column in", not "pass an expression in", and I was initially a little confused why `__clause_element__() == val` would work when `__clause_element__().has(expr)` would error.

I should have figured it out after seeing what `__clause_element__` was, but as my first try was adding a comparator to query across multiple relationships (similar to an association proxy but linking to a relationship), the idea of turning the expression `model.parent_id == parent.id` into the equivalent of `Model.parent.has(Parent.child.any(expr))` seemed way too daunting, so I jumped the gun and decided to rely on the ORM querying for everything lol.

**Comment by Peter92** [comment]
I've just come across your [discussion last year](https://groups.google.com/g/sqlalchemy/c/XQW8gxX93hU) about hybrid properties not being compatible with `load_only()`.

I reworked my code above to use `column_property` to support selectively loading it, and the query emitted with `load_only(SomeColumn.name)` is this:

    SELECT CASE WHEN (some_table.long_name IS NOT NULL) THEN some_table.long_name ELSE some_table.short_name END AS anon_1, some_table.id AS some_table_id
    FROM some_table

You said you _could_ extract a select statement from a hybrid property, but you weren't sure as the concept itself is already quite confusing for end users. From the above query, it looks like `hybrid_property.expression` would be sufficient to make it work, which IMO doesn't make it any more confusing.

You don't need to explain yourself if you've already fully thought this over btw - it just with being able to override comparisons and ordering, it seems strange that overriding selects is not possible :)

**Comment by zzzeek** [comment]
the thing that I said was confusing there would be to extract the columns from the expression returned by a hybrid so that they could be sent into a load_only().      you're free to work that out which you'd need to use using a [visitor](https://docs.sqlalchemy.org/en/14/core/visitors.html?highlight=clausevisitor#sqlalchemy.sql.visitors.traverse).       I generally try to avoid adding new features that depend on visitors like that as much as possible since there are always a lot of edge cases to deal with.
