### ISSUE TITLE
Create table from SQL query with SQLAlchemy core

### ISSUE THREAD

**Issue by PrimozGodec** [sqlalchemy/sqlalchemy#5687]
**Describe your question**

I was already searching around web and issues and I couldn't find the answer. I am using SqlAlchemy core (not ORM), I want to create a table from SQL. In PostgreSQL, it would be done with `CREATE TABLE TableName AS (SELECT * FROM ExistingTable WHERE conditions)`

So I have an existing query which is a select query (Select type or textual query) and can be complex (also contains joins from more tables). It means that just making a copy of an existing table will not work. 

If I have a query
```
query = select([text("*")]).select_from(text("Inventory")).where(text("quantity > 140"))  # it can be even more complex
```
or 
```
query = text("SELECT * FROM Inventory WHERE quantity > 140 
```
I would like to create a new table in the database which is the result of a query. Is it possible to do it with SQLAlchemy? Or should I write a function for every database type I am supporting?

**Comment by zzzeek** [comment]
hey there - 

you can adapt the create view recipe at https://github.com/sqlalchemy/sqlalchemy/wiki/Views as follows:


```

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import literal
from sqlalchemy import MetaData
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy import Table
from sqlalchemy.ext import compiler
from sqlalchemy.schema import DDLElement


class CreateTableAs(DDLElement):
    def __init__(self, name, selectable):
        self.name = name
        self.selectable = selectable


@compiler.compiles(CreateTableAs)
def compile(element, compiler, **kw):
    return "CREATE TABLE %s AS (%s)" % (
        element.name,
        compiler.sql_compiler.process(element.selectable, literal_binds=True),
    )


if __name__ == "__main__":

    engine = create_engine(
        "postgresql://scott:tiger@localhost/test", echo=True
    )
    metadata = MetaData()
    stuff = Table(
        "stuff",
        metadata,
        Column("id", Integer, primary_key=True),
        Column("data", String(50)),
    )

    more_stuff = Table(
        "more_stuff",
        metadata,
        Column("id", Integer, primary_key=True),
        Column("stuff_id", Integer, ForeignKey("stuff.id")),
        Column("data", String(50)),
    )

    metadata.create_all(engine)

    stmt = (
        select(
            [
                stuff.c.id.label("id"),
                stuff.c.data.label("data"),
                more_stuff.c.data.label("moredata"),
            ]
        )
        .select_from(stuff.join(more_stuff))
        .where(stuff.c.data.like(literal('%orange%')))
    )

    with engine.begin() as conn:
        conn.execute(CreateTableAs("my_select_table", stmt))

```

**Comment by PrimozGodec** [comment]
Thank you for the response. The syntax from `compile` function is not working for all backends (Sqlite does not like parenthesis around selectable, MSSQL does not like CREATE .. AS ..). So if I understand correctly if I want to make it work for all backends I must implement the compile function separately for every backend.

**Comment by zzzeek** [comment]
> Thank you for the response. The syntax from `compile` function is not working for all backends (Sqlite does not like parenthesis around selectable, MSSQL does not like CREATE .. AS ..). So if I understand correctly if I want to make it work for all backends I must implement the compile function separately for every backend.

that's correct.  see the docs for @compiles at https://docs.sqlalchemy.org/en/13/core/compiler.html#dialect-specific-compilation-rules .

**Comment by zzzeek** [comment]
this is for a syntax "create table as" which is not too different from "create view" in that there's a "table" and a "select", however we currently leave these creation syntaxes to recipes.
