### ISSUE TITLE
emit wanrings when any combination of returning(), return_defaults() are called, as these all replace each other.  

### ISSUE THREAD

**Issue by Maillol** [sqlalchemy/sqlalchemy#5691]
**Describe the bug**

We cannot use several returning() calls with the same statement. The last call erases the previous calls.   

**Expected behavior**

This statement:
```
statement = statement.returning(user.c.firstname)
statement = statement.returning(user.c.lastname)
```

Should be equivalent to:

```
statement = statement.returning(user.c.firstname, user.c.lastname)`
```

**To Reproduce**

```py
from sqlalchemy import Table, MetaData, Integer, String, Column
from sqlalchemy.dialects import postgresql

metadata = MetaData()

user = Table('user', metadata,
             Column('id', Integer, primary_key=True, autoincrement=True),
             Column('firstname', String(255)),
             Column('lastname', String(255)),
             Column('age', Integer))

statement = user.update()
statement = statement.values(firstname='John')
statement = statement.values(lastname='Smith')
statement = statement.returning(user.c.firstname)
statement = statement.returning(user.c.lastname)

print(statement.compile(dialect=postgresql.dialect()))
```

**Error**

```
UPDATE "user" SET firstname=%(firstname)s, lastname=%(lastname)s RETURNING "user".lastname
```

**Expected Output**

```
UPDATE "user" SET firstname=%(firstname)s, lastname=%(lastname)s RETURNING "user".firstname, "user".lastname
```

**Versions.**
 - OS: Fedora (5.8.11-200.fc32.x86_64)
 - Python: Python 3.8.5
 - SQLAlchemy: 1.3.20
 - Database: postgres:9.6.19
 - DBAPI:  aiopg

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

I'm not sure I agree that successive returning() calls should be appending columns.    if so, this change would be only for the 1.4 series.    For 1.3, a warning should be emitted.  that's the bug right now.   additionally any combination of return_defauls() / returning() should emit a warning.

**Comment by zzzeek** [comment]
see #5695 for the 1.4 feature

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Warn / raise for returning() / return_defaults() combinations** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2353

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Warn / raise for returning() / return_defaults() combinations** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2354
