### ISSUE TITLE
Missing keywords in mysql dialect

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5696]
The following keywords are missing from the `RESERVED_WORDS` list for the mysql dialect:

- action
- level
- mode
- status
- text
- time

**Comment by sqla-tester** [comment]
**Oscar Batori** has proposed a fix for this issue in the **master** branch:

**Added missing keywords for MySQL dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2240

**Comment by sqla-tester** [comment]
**Oscar Batori** has proposed a fix for this issue in the **rel_1_3** branch:

**Added missing keywords for MySQL dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2357
