### ISSUE TITLE
sqlalchemy 1.4 sqlite regexp_match(): re.match() vs. re.search()

### ISSUE THREAD

**Issue by xflr6** [sqlalchemy/sqlalchemy#5699]
I think I might be missing something but from comparing with [postgresql](https://www.postgresql.org/docs/13/functions-matching.html#FUNCTIONS-POSIX-REGEXP):

```
'abc' ~ 'abc'    true
'abc' ~ '^a'     true
'abc' ~ '(b|d)'  true
'abc' ~ '^(b|c)' false
```

I think this should use `re.search()` instead of `re.match()` (which is left-anchored):

https://github.com/sqlalchemy/sqlalchemy/blob/1a9618afdd6413fd04ee44b797a15735eaa1a230/lib/sqlalchemy/dialects/sqlite/pysqlite.py#L508-L511

IIUC what is called regex matching by many tools is `re.search()`, while `re.match()` is more like a short-cut for `re.search('^...')` (maybe `letmatch` or `prefix_match` would be a better name, any way `re.fullmatch()` seems less confusing and more useful).

I took a quick look at the tests but only saw test examples for initial matches. Hope this helps.

**Comment by zzzeek** [comment]
CCing @gordthompson @jvanasco @CaselIT can we review the operators here, there is some precedent for SQLite regexp here: https://stackoverflow.com/questions/5071601/how-do-i-use-regex-in-a-sqlite-query/8338515#8338515  https://github.com/ralight/sqlite3-pcre  if we can see what they do, above all we need to add tests that check if each backend's regexp acts a search.

**Comment by zzzeek** [comment]
https://www.pcre.org/original/doc/html/pcre_exec.html  - "It returns offsets to captured substrings."   the above C library is not using any options which means the PCRE_ANCHORED flag is not set so it seems to support that the packaged use case for SQLite's regex acts like search.

**Comment by CaselIT** [comment]
yes, I agree we should use `search` instead of `match`. I guess we did kind of assumed match since it's called regexp matching everywhere.

@xflr6 would you like to proved a pr to fix this?

**Comment by xflr6** [comment]
Thanks for the quick answer.

Feel free to go ahead (sounds like nice small fix, but I am not sure if I can find the time for it).

**Comment by CaselIT** [comment]
will do

**Comment by jvanasco** [comment]
@CaselIT if you do this, can you tag me as a reviewer? i'm interested in the test coverage for this.

**Comment by CaselIT** [comment]
I've not started it, if you want to have a go at if feel free

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Use ``re.search`` instead of ``re.match`` in sqlite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2365

**Comment by xflr6** [comment]
Not sure if this was considered before: Would it make sense to use `is not None` instead of `bool()`?

```python
In [1]: import re

In [2]: %timeit bool(re.search(r'spam', 'eggs'))
1.24 µs ± 2.37 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [3]: %timeit re.search(r'spam', 'eggs') is not None
1.1 µs ± 5.09 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [4]: %timeit bool(re.search(r'spam', 'spam'))
1.4 µs ± 76.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [5]: %timeit re.search(r'spam', 'spam') is not None
1.2 µs ± 4.06 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by CaselIT** [comment]
> 
> 
> Not sure if this was considered before: Would it make sense to use `is not None` instead of `bool()`?
> 
> ```python
> In [1]: import re
> 
> In [2]: %timeit bool(re.search(r'spam', 'eggs'))
> 1.24 µs ± 2.37 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
> 
> In [3]: %timeit re.search(r'spam', 'eggs') is not None
> 1.1 µs ± 5.09 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
> 
> In [4]: %timeit bool(re.search(r'spam', 'spam'))
> 1.4 µs ± 76.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
> 
> In [5]: %timeit re.search(r'spam', 'spam') is not None
> 1.2 µs ± 4.06 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
> ```

sure. see updated gerrit

**Comment by xflr6** [comment]
Thanks! I think this might be regarded more correct (to do the `re` check for existance this way)  so WDYT about adapt the documentation as  well?

**Comment by CaselIT** [comment]
> 
> 
> Thanks! I think this might be regarded more correct (to do the `re` check for existance this way) so WDYT about adapt the documentation as well?

Thanks for catching it. Updated!

**Comment by xflr6** [comment]
Great, thanks!

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Use ``re.search`` instead of ``re.match`` in sqlite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2365
