### ISSUE TITLE
Bundles of labelled expressions always behave as if single_entity=True

### ISSUE THREAD

**Issue by acarapetis** [sqlalchemy/sqlalchemy#5702]
**Describe the bug**
Under certain conditions in SQLAlchemy 1.4 beta1, a query for an `orm.Bundle` can behave as if `single_entity=True`, even though this flag is actually off. From my testing, it seems that the required conditions are that all of the columns/expressions in the `Bundle` are labelled.

**Expected behavior**
Since the Bundle has `single_entity=False`, a query for the bundle alone should return an iterable of singleton tuples of tuples; but it actually just returns an iterable of tuples. See the failed assertion below for an example.

**To Reproduce**
I've written a test [here](https://github.com/acarapetis/sqlalchemy/commit/7a7c204bb058e1fcb5dacd5af8c830bab2b12ff4) which demonstrates the issue: it passes on 1.3.20 and fails on 1.4.0b1.

```py
    def test_labelled_cols(self):
        Data = self.classes.Data
        sess = Session()

        b1 = Bundle("b1", Data.d1.label('x'), Data.d2.label('y'))

        eq_(
            sess.query(b1).filter(b1.c.x.between("d3d1", "d5d1")).all(),
            [(("d3d1", "d3d2"),), (("d4d1", "d4d2"),), (("d5d1", "d5d2"),)],
        )

```

**Error**

```
Traceback (most recent call last):
  File "/home/anthony/sqlalchemy/test/orm/test_bundle.py", line 177, in test_labelled_cols
    eq_(
  File "/home/anthony/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 210, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: [('d3d1', 'd3d2'), ('d4d1', 'd4d2'), ('d5d1', 'd5d2')] != [(('d3d1', 'd3d2'),), (('d4d1', 'd4d2'),), (('d5d1', 'd5d2'),)]
assert [('d3d1', 'd3...5d1', 'd5d2')] == [(('d3d1', 'd...1', 'd5d2'),)]
  At index 0 diff: ('d3d1', 'd3d2') != (('d3d1', 'd3d2'),)
  Full diff:
  - [(('d3d1', 'd3d2'),), (('d4d1', 'd4d2'),), (('d5d1', 'd5d2'),)]
  ?  -                 ^^^^                 ^^^^                --
  + [('d3d1', 'd3d2'), ('d4d1', 'd4d2'), ('d5d1', 'd5d2')]
  ?                   ^                 ^
```

**Versions.**
 - OS: Ubuntu 20.04.1 LTS
 - Python: 3.8.5
 - SQLAlchemy: 1.4.0b1
 - Database: Postgresql 12, MariaDB 10.3
 - DBAPI: psycopg2, pymysql

**Comment by zzzeek** [comment]
hey there.

so actually looking at that flag, it also needs to be marked as "legacy" since it has no bearing on 2.0 style execution.  ill get it working for Query but otherwise it's a legacy use case (as is all Query use).

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure the "orm" plugin is used unconditionally for bundles** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2367
