### ISSUE TITLE
update with with_for_update() clause

### ISSUE THREAD

**Issue by lafrinte** [sqlalchemy/sqlalchemy#5704]
Description
update cannot enable with_for_update. how to use with_for_update with update in 2.x?

Example:

```
In [1]: from sqlalchemy import update
...
In [18]: update_stmt = (
    ...:     update(Subjob).
    ...:     with_for_update().
    ...:     where(Subjob.id == 1).
    ...:     values(
    ...:         {
    ...:             Subjob.ujid: 0,
    ...:             Subjob.downstream: (1,)
    ...:         }
    ...:     )
    ...: )
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-b29d751bdbcf> in <module>
      1 update_stmt = (
----> 2     update(Subjob).
      3     with_for_update().
      4     where(Subjob.id == 1).
      5     values(

AttributeError: 'Update' object has no attribute 'with_for_update'
```

Exception: "AttributeError: 'Update' object has no attribute 'with_for_update'"

Versions.

OS: ALL
Python: 3.8.2 (Looks like all of them)
SQLAlchemy: sqlalchemy
Database: postgresql
DBAPI: asnycpg

**Comment by zzzeek** [comment]
heya -

PostgreSQL always surprises me with whatever new syntaxes they are adding however I am not seeing any mention of a "FOR UPDATE" e.g. "locking clause" that accompanies the UPDATE statement itself, here's PG 13:  https://www.postgresql.org/docs/13/sql-update.html  .   if you can indicate the SQL syntax you are expecting that would be helpful but I believe FOR UPDATE only applies to SELECT statements, even though an UPDATE can have RETURNING and essentially behave in a similar way.

**Comment by lafrinte** [comment]
> heya -
> 
> PostgreSQL always surprises me with whatever new syntaxes they are adding however I am not seeing any mention of a "FOR UPDATE" e.g. "locking clause" that accompanies the UPDATE statement itself, here's PG 13: https://www.postgresql.org/docs/13/sql-update.html . if you can indicate the SQL syntax you are expecting that would be helpful but I believe FOR UPDATE only applies to SELECT statements, even though an UPDATE can have RETURNING and essentially behave in a similar way.

for 1.x condition style like below:

```
In [28]: s.query(Subjob).filter(Subjob.id == 1).with_for_update().update({"ujid": 2})
Out[28]: 1
```
it can work with pleasure in 1.x style by using the Query object.  the example above may more pythonic to update with where conditions. is there any plan to enable this statment in 2.x style?

**Comment by zzzeek** [comment]
with_for_update() when used with Query().update() does not effect the UPDATE statement.  I just took a look and it appears that it will impact the SELECT that is emitted for the "synchronize_session='fetch'" strategy although this was never covered as a real feature, it's by accident.     that seems to not happen in 1.4 so that's something to note though this was never official API.

again I really need to see the SQL string(s) you are looking for, is it the "SELECT" that's emitted on behalf of the "fetch" strategy you're looking for ?    we would need to add execution options for that.

**Comment by lafrinte** [comment]
i wants to handle a row level lock for all the rows i expect to update and then commit and close the session.  i always set synchronize_session='False' to prevent some error occure when work with `delete` and `in_`.  i may split it to two sql, one for lock and one for update in a transaction to do the lock and update action.  thankyou for replay ~ with pleasure

**Comment by zzzeek** [comment]
then with_for_update() has not been doing anything for you.  you can only explicitly lock rows using a SELECT..FOR UPDATE first.   The UPDATE statement will intrinsically apply whatever locking is needed based on the transaction isolation level in use.

**Comment by ReetiMauryaCrest** [comment]
> The UPDATE statement will intrinsically apply whatever locking is needed based on the transaction isolation level in use.

Can you clarify some more on this statement? I am currently using 2 different types of update statements in my code. The direct update code as `session.query(table1).filter(...).update(col1 = data1)` for simple updates. And the fetch and update method as **select (with for update) -> make changes -> commit** for more complex functions. 

I am trying to verify that race condition is not occurring when these 2 functions try to simultaneously change the same value, but cannot verify that the update function (method 1) would work correctly with with for update (method 2).

**Comment by CaselIT** [comment]
That depends on the db in use. Sqlalchemy does not explicitly sets any lock when running an update, but the db generally will

**Comment by ReetiMauryaCrest** [comment]
> That depends on the db in use. Sqlalchemy does not explicitly sets any lock when running an update, but the db generally will

I am using Postgres as database, I want to ensure that my data always stays consistent and does not get affected by any type of race conditions. (As most of my update is related to increasing/decreasing same data by 1 after one another continuously.) Do you have any suggestion on which syntax I should use for updates to make sure data is always consistent in the database? And if I need to update any settings in Postgres for this to work?

**Comment by CaselIT** [comment]
As far as I can tell using with for update should be fine.
Worst thing would be that it deadlocks something, but is should not otherwise mess with the data

**Comment by ReetiMauryaCrest** [comment]
Thank you @CaselIT I would update all of my functions to use with_for_update instead. I think there should be a clear documentation to explain something basic like stopping race conditions and locks.

**Comment by CaselIT** [comment]
That's generally in the database documentation. SQLAlchemy is not a database, it just sends commands to them, so you should look at the db documentation for things like that
