### ISSUE TITLE
Inconsistent handling of first() in 1.4

### ISSUE THREAD

**Issue by gboor** [sqlalchemy/sqlalchemy#5706]
**Describe the bug**
I'm using SQLAlchemy 1.4.0b1 with AsyncSession.

If I select a couple of fields like so;

```
rows = await session.execute(select(MyModel.id, MyModel.name))
entry = rows.first()
```

Then it works as expected; I can access `entry.id` and `entry.name`.

However, if I query a whole object (SELECT *, basically), something weird happens;

```
rows = await session.execute(select(MyModel))
entry = rows.first()
```

Now `entry` is iterable and `entry.id` and `entry.name` do not exist (`Could not locate column in row for column 'id'`). However, `entry[0].id` and `entry[0].name` do exist and are the correct data.

Both instances of entry are of the type `<class 'sqlalchemy.engine.row.Row'>`

**Expected behavior**
first() to always return just 1 row with the fields accessible.

**To Reproduce**

```py
import asyncio
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

Base = declarative_base()


class MyModel(Base):
    __tablename__ = 'my_table'

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, nullable=False)


async def async_main():
    engine = create_async_engine('postgresql+asyncpg://...')
    async with AsyncSession(engine) as session:
        stmt = select(MyModel.id, MyModel.name)
        rows = await session.execute(stmt)
        row = rows.first()

        print(row.id)  # this works!

        stmt = select(MyModel)
        rows = await session.execute(stmt)
        row = rows.first()

        print(row[0].id)  # This works?!
        print(row.id)  # This errors out

asyncio.run(async_main())
```

**Error**

```
Traceback (most recent call last):
  File "test-sa-first.py", line 34, in <module>
    asyncio.run(async_main())
  File "C:\Program Files\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "test-sa-first.py", line 32, in async_main
    print(row.id)
AttributeError: Could not locate column in row for column 'id'
```

**Versions.**
 - OS: Windows 10
 - Python: 3.7.3
 - SQLAlchemy: 1.4.0b1
 - Database: Postgres 11
 - DBAPI: asyncpg

**Comment by zzzeek** [comment]
hey there -

working as defined, read up on how the ORM returns rows at https://docs.sqlalchemy.org/en/14/orm/queryguide.html#orm-queryguide-select-columns 

here's the salient detail:

> When selecting from ORM entities, the entity itself is returned in the result as a single column value; for example above, the Result returns Row objects that have just a single column, that column holding onto a User object:

I believe some mention of this should also be added to the tutorial section at https://docs.sqlalchemy.org/en/14/tutorial/data.html#tutorial-selecting-orm-entities so will do that now.

**Comment by zzzeek** [comment]
there will be some additional documentation buliding from the commit I just pushed.

**Comment by CaselIT** [comment]
To further expand, there are some useful methods in the `Result` object that you can use to achieve this, like:
- [`scalars()`](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=scalar_one#sqlalchemy.engine.CursorResult.scalars) followed by `first()`
- [`scalar()`](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=scalar_one#sqlalchemy.engine.CursorResult.scalar)
- [`scalar_one()`](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=scalar_one#sqlalchemy.engine.CursorResult.scalar_one)
- [`scalar_one_or_none()`](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=scalar_one#sqlalchemy.engine.CursorResult.scalar_one_or_none)

**Comment by gboor** [comment]
Thanks for the clarification. I must've missed that one. I'll look into the scalar stuff!
