### ISSUE TITLE
ROWVERSION Column in ORM

### ISSUE THREAD

**Issue by stevesmit** [sqlalchemy/sqlalchemy#5707]
**Describe your question**

I need to add a ROWVERSION column to a class I have created using the ORM (the production engine I will be using is SQL Server, but using SQLite while testing). I don't want to (and can't or I'll get an error) insert any data into this column when creating objects. 

In pure SQL I'd just define the column as `_rv ROWVERSION`. But when creating the column in SQLAlchemy like this: `_rv = Column(TIMESTAMP().with_variant(ROWVERSION, "mssql"))` it generates the following SQL statement on SQL Server - `_rv ROWVERSION NULL`. 

This means that when creating objects/records it tries to insert a value into this column, generating this error: 
```
'[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert an explicit value into a timestamp column. Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column. (273) (SQLExecDirectW); [23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)')
```

I have tried defining the column like this:
```
_rv = Column(
        TIMESTAMP().with_variant(ROWVERSION, "mssql"),
        server_default=text("DEFAULT")
)
```

But this just defines the create statement in SQL like this `_rv = ROWVERSION NOT NULL DEFAULT DEFAULT` which raises an error

```
('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'DEFAULT'. (156) (SQLExecDirectW)")
```

**My question:** How can I define this column so that the ORM doesn't attempt to insert a value into it and it just operates as intended, creating whatever system-based value it should. 

**Example - please use the [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) guidelines if possible**

```
class ExampleObj(Base):
    __tablename__ = 'example_obj'
    id = Column(
        Integer,
        primary_key=True
    )
    name = Column(String, nullable=False)
    _rv = Column(
        TIMESTAMP().with_variant(ROWVERSION, "mssql"),
        server_default=text("DEFAULT"),
        nullable=False
    )
```

**Versions**
 - OS: Windows 10 Enterprise
 - Python: 3.8.5
 - SQLAlchemy: 1.3.19
 - Database: Azure SQL Server

**Comment by zzzeek** [comment]
hi there -

for server generated columns that are implicitly present you use FetchedValue:   https://docs.sqlalchemy.org/en/13/core/defaults.html?highlight=fetchedvalue#triggered-columns

```
class ExampleObj(Base):
    __tablename__ = 'example_obj'
    id = Column(
        Integer,
        primary_key=True
    )
    name = Column(String, nullable=False)
    _rv = Column(
        TIMESTAMP().with_variant(ROWVERSION, "mssql"),
        server_default=FetchedValue(),
        nullable=False,
    )

```

the above won't work for SQLite though because SQLite would require a default generation function to be explicitly present.   we don't yet support the "variant" concept for other kinds of constructs though it's something we want to do eventually.   so for SQLite you'd need to know ahead of time which database you are targeting and affect the "server_default" appropriately.

**Comment by stevesmit** [comment]
@zzzeek Thank you! That has solved the issue. I did as suggested and made the `server_default` conditional on the environment the application is running in.
