### ISSUE TITLE
How to get SQL execution count for a query?

### ISSUE THREAD

**Issue by flniu** [sqlalchemy/sqlalchemy#5709]
I want to check whether refactoring introduces any unexpected N+1 select problem.

For example:
```
some_query.all()  # this query should use eager loading
assert sql_execution_count <= 2
```

How can I get the `sql_execution_count` of this query?

Or is there better practice to check N+1 problem?

**Comment by olirice** [comment]
Calling `.all()` on a query will always emit exactly 1 sql query respecting the [relationship loading techniques](https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html) and [options applied to the query](https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html#relationship-loader-options). The potential N+1 problems wouldn't occur until you access lazy properties/relationships on the result set.

For example:
```python
# 1 SQL statement
authors = session.query(Author).all()

for author in authors:
    # if the books relationship is not loaded, accessing `book` relationship
    # will cause another query
    books = author.books
```

Here's the [relevant place in docs](https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html#prevent-lazy-with-raiseload) for instructions how to avoid N+1s.

You can also pass `echo=True` to `sqlalchemy.create_engine` to print out the sql is being emitted to check that only 1 query occurs. [Location in docs](https://docs.sqlalchemy.org/en/13/core/engines.html#sqlalchemy.create_engine)

**Comment by zzzeek** [comment]
some additional detail:

1. eager loaders like selectinload and subqueryload will emit additional queries within the scope of .all(), but they are not "N+1", they are O(1) per relationship path.

2. A little known loader called "immediateload" will in fact emit N+1 queries immediately.   So don't use that loader (it's obviously not generally used but is useful for some situations).

3. as suggested above, echo=True is the quickest way to see what the DB is doing.  however, if you want to programmatically count queries, you can also use an event handler.   above, we can use the [before_cursor_execute](https://docs.sqlalchemy.org/en/14/core/events.html?highlight=before_cursor_execute#sqlalchemy.events.ConnectionEvents.before_cursor_execute) event to deliver the effect you're looking for:

```
from sqlalchemy import event
import contextlib

@contextlib.contextmanager
def count_queries(conn):
    queries = []
    def before_cursor_execute(conn, cursor, statement, parameters, context, executemany):
        queries.append(statement)

    event.listen(conn, "before_cursor_execute", before_cursor_execute)
    try:
        yield queries
    finally:
        event.remove(conn, "before_cursor_execute", before_cursor_execute)

# example use
with count_queries(session.connection()) as queries:
    for a1 in s.query(A):
        a1.bs

print("total number of queries: %s" % len(queries))

```

4. there's an FAQ entry on performance that I would recommend reviewing: https://docs.sqlalchemy.org/en/14/faq/performance.html


the above "query counting" recipe I think I can add to the docs

**Comment by flniu** [comment]
Sorry, my mistake. What I actually want to test is method/API like this:

```
def get_parents():
    parents = some_query.all()  # this query should use eager loading
    return marshal(parents)  # marshal parents and their children into json

def test_get_parents():
    get_parents()
    assert sql_execution_count <= 2
```

Marshaling objects into json will access their properties/relationships.
I expect the query to use joinedload, selectinload, or subqueryload, so assert sql_execution_count <= 2.

Thank you for clarifying and additional informations. I think I can use `before_cursor_execute` event to implement a common util method in our base test class.

**Comment by flniu** [comment]
> the above "query counting" recipe I think I can add to the docs

Adding this into FAQ would be nice. Maybe "query execution counting" is a better term? When I search "sqlalchemy query counting", most of results are about `.count()`.

**Comment by swuecho** [comment]
> some additional detail:
> 
> 1. eager loaders like selectinload and subqueryload will emit additional queries within the scope of .all(), but they are not "N+1", they are O(1) per relationship path.
> 2. A little known loader called "immediateload" will in fact emit N+1 queries immediately.   So don't use that loader (it's obviously not generally used but is useful for some situations).
> 3. as suggested above, echo=True is the quickest way to see what the DB is doing.  however, if you want to programmatically count queries, you can also use an event handler.   above, we can use the [before_cursor_execute](https://docs.sqlalchemy.org/en/14/core/events.html?highlight=before_cursor_execute#sqlalchemy.events.ConnectionEvents.before_cursor_execute) event to deliver the effect you're looking for:
> 
> ```python
> from sqlalchemy import event
> import contextlib
> 
> @contextlib.contextmanager
> def count_queries(conn):
>     queries = []
>     def before_cursor_execute(conn, cursor, statement, parameters, context, executemany):
>         queries.append(statement)
> 
>     event.listen(conn, "before_cursor_execute", before_cursor_execute)
>     try:
>         yield queries
>     finally:
>         event.remove(conn, "before_cursor_execute", before_cursor_execute)
> 
> # example use
> with count_queries(session.connection()) as queries:
>     for a1 in s.query(A):
>         a1.bs
> 
> print("total number of queries: %s" % len(queries))
> ```
> 
> 4. there's an FAQ entry on performance that I would recommend reviewing: https://docs.sqlalchemy.org/en/14/faq/performance.html
> 
> the above "query counting" recipe I think I can add to the docs

`session.bind.engine` is better than `session.connection()`

**Comment by zzzeek** [comment]
session.connection() is preferred since that will give you a connection in context of the current transaction.  session.bind is not always present depending on configuration
