### ISSUE TITLE
Preprocess column names during reflection

### ISSUE THREAD

**Issue by olirice** [sqlalchemy/sqlalchemy#5711]
**Question**

Is there an equivalent to `classname_for_table`, `name_for_collection_relationship` and `name_for_scalar_relationship` to adjust column names when reflecting a schema with `Base.prepare(reflect=True ...)`?

i.e.
```python
Base.prepare(engine,
    reflect=True,
    classname_for_table=camelize_classname,
    name_for_collection_relationship=pluralize_collection,
    name_for_column=snakeify_column_name  # <-- this one 
)
```

If not, is there any other way to preprocess column names during reflection, for example, with an event listener?

Reference from [these docs](https://docs.sqlalchemy.org/en/13/orm/extensions/automap.html#overriding-naming-schemes)

**Comment by zzzeek** [comment]
the event hook for processing columns that are reflected is the [column_reflect](https://docs.sqlalchemy.org/en/14/core/events.html?highlight=column_reflect#sqlalchemy.events.DDLEvents.column_reflect) event.   the entries are delivered there for modification before the Column object is produced.    while it's not documented, you can also set the "key" entry in the dictionary which will cause the column to be accessed from the Table and the mapped class using that .key, which is independent of the "name" that's actually rendered in SQL statements.

the general documentation for this technique is at https://docs.sqlalchemy.org/en/14/orm/mapping_columns.html#automating-column-naming-schemes-from-reflected-tables  this is also in the 1.3 and prior docs.

**Comment by zzzeek** [comment]
it would be nice if that listener could be more easily associated with a specific MetaData.  seems to be a major omission.  you need to associate the listener with the Table class overall for now.

**Comment by zzzeek** [comment]
I've added #5712

**Comment by zzzeek** [comment]
documentation was improved here and in #5712 we improved the usage of the event hook.
