### ISSUE TITLE
oracle - we arent getting default schema name correctly

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5716]
```
diff --git a/lib/sqlalchemy/dialects/oracle/base.py b/lib/sqlalchemy/dialects/oracle/base.py
index 7bdaafd82..adcfa424c 100644
--- a/lib/sqlalchemy/dialects/oracle/base.py
+++ b/lib/sqlalchemy/dialects/oracle/base.py
@@ -1587,9 +1587,11 @@ class OracleDialect(default.DefaultDialect):
 
     def _get_default_schema_name(self, connection):
         return self.normalize_name(
-            connection.exec_driver_sql("SELECT USER FROM DUAL").scalar()
+#            connection.exec_driver_sql("SELECT USER FROM DUAL").scalar()
+            connection.exec_driver_sql("select sys_context( 'userenv', 'current_schema' ) from dual").scalar()
         )
 
+

```

if "ALTER SESSION SET CURRENT_SCHEMA " is used then "USER" is no longer the "current schema".

this is related to the "current schema" stuff I'm working for and it's a good thing I decided to write more tests.  PG needs some help too.

as this is a big change and we are adding "business class" support for being able to change the schema on connect,  targeting this at 1.4.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Support pool.connect() event firing before all else** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2372
