### ISSUE TITLE
ArgumentError on automap_base() only

### ISSUE THREAD

**Issue by kaldown** [sqlalchemy/sqlalchemy#5718]
**Describe your question**

I have an app where all the schemas are declared.
Have another readonly-app and want to shortcut schemas duplication for now by using `automap_base()`.
No error were given from main app, but when I'm trying to do:

```
Base = automap_base()
Base.prepare(db.engine, reflect=True)
User = Base.classes.user
db.session.query(User).first()

ArgumentError: Error creating backref 'episode_collection' on relationship 'episode.mentor': property of that name exists on mapper 'mapped class mentor->mentor'
```

I have Episode class which has relations with Mentor:
```
class Episode:
    ...
    author_id = db.Column(db.Integer, db.ForeignKey("mentor.id"))
    author = db.relationship("Mentor", backref='episodes_author')

class Mentor:
    ...
    episodes_guest = db.relationship('Episode', secondary='episode_guest', backref='guests')

class EpisodeGuest(db.Model):
    ...
    guest = db.relationship('Mentor', backref='episodes_proxy')
    episode = db.relationship('Episode', backref='guests_proxy')
```

All in all. An episode should have `author` and `guests`.
In M2M table I used `episodes_proxy` naming to use this in *Flask-Admin* as an inline model.

Can't understand where this problem comes from. Everything looks right in the main app. But failed when I trying to create using` automap_base()`

**Versions**
 - OS: arch
 - Python: 3.8
 - SQLAlchemy: 1.3.20
 - Database: postgresql

**Have a nice day!**
**You too :D**

**Comment by zzzeek** [comment]
hey there -

in the issue template we ask that people please provide a complete [mcve](http://stackoverflow.com/help/mcve) to illustrate the problem.  this not only communicates exactly what is happening but also gives the reporter the opportunity to better understand the issue at hand. 

In the interests of expedeincy, I've taken the code fragments you provided above and worked them into an MCVE based on what you presented, and no error is emitted.   Feel free to work with this test script to show how to reproduce your error message, thanks.

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class User(Base):
    __tablename__ = "user"
    id = Column(Integer, primary_key=True)


class Episode(Base):
    __tablename__ = "episode"

    id = Column(Integer, primary_key=True)
    author_id = Column(Integer, ForeignKey("mentor.id"))
    author = relationship("Mentor", backref="episodes_author")


class Mentor(Base):
    __tablename__ = "mentor"
    id = Column(Integer, primary_key=True)
    episodes_guest = relationship(
        "Episode", secondary="episode_guest", backref="guests"
    )


class EpisodeGuest(Base):
    __tablename__ = "episode_guest"

    id = Column(Integer, primary_key=True)

    episode_id = Column(ForeignKey("episode.id"))
    guest_id = Column(ForeignKey("mentor.id"))

    guest = relationship("Mentor", backref="episodes_proxy")
    episode = relationship("Episode", backref="guests_proxy")


engine = create_engine("sqlite://", echo=True)
Base.metadata.create_all(engine)

Base = automap_base()
Base.prepare(engine, reflect=True)
User = Base.classes.user

session = Session(engine)
session.query(User).first()

```

**Comment by zzzeek** [comment]
please reopen if you can provide complete detail.
