### ISSUE TITLE
Improve support for sub-second pool timeouts

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5719]
Improve documentation and add test for sub-second pool timeouts. Related PR: #5710

**Comment by sqla-tester** [comment]
**Jordan Pittier** has proposed a fix for this issue in the **master** branch:

**QueuePool: support subsecond timeout** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2373
