### ISSUE TITLE
UML diagrams for  SQLAlchemy implementation

### ISSUE THREAD

**Issue by raccarva** [sqlalchemy/sqlalchemy#5721]
I am specifying in UML a software project which relies on SQLAlchemy for database interaction. I saw in http://aosabook.org/en/sqlalchemy.html some very nice UML diagrams of the SQLAlchemy architecture and I was guessing if a set of these diagrams is available describing the whole library interface.
That would be extremely useful for me because it would allow me to specify all my queries and database operations by creating diagrams referencing the mentioned UML elements. Later, I can generate Python code from my UML diagrams so that no hand code is needed for database operations.

Does anybody know more about the diagrams which appear in the mentioned book and if they are publicly available?

An example:

![image](https://user-images.githubusercontent.com/40737487/100005915-7673fa80-2da8-11eb-827b-8cd132f75791.png)

Regards,

Ramiro.

**Comment by zzzeek** [comment]
I made those diagrams many years ago but im not sure what the copyright situation is on them.    they were also made using omnigraffle and not any kind of UML tool that generates code so if you wanted to do that, you'd have to create your own diagrams anyway.   the names in those boxes are also not current and the overall structure has likely changed quite a bit in terms of specifics.

I haven't heard of the "generate code from UML approach" in many years and I'd be a little skeptical of that as a general tecnhnique but I don't really know how you'd do that anyway.

**Comment by raccarva** [comment]
Thanks for the response, Mike.
UML has been around for a long time but hasn´t achieved popularity. Nevertheless, it is the solution proposed by most of the tools which deal with Digital Integration, MBSE (model based systems engineering), and some Business Modelling tools as well. 
The modern generation of code from UML models is done by templates that translate model elements into text. There are some initiatives on the open-source scenario as well (QVT, M2T, etc).
Actually what I need is the diagram I´ve shown but including the properties and methods which provide the interface, so that I can build a package that would act as a library for UML models to interact with SQLAlchemy.
Any way I can build that diagram from the source code as well.

Thanks!

Ramiro.

**Comment by zzzeek** [comment]
yes, I did not build out UML models for anything, those are just pictures (which nonetheless draw from UML norms since I was a UML person in the 90's).
