### ISSUE TITLE
Bidirectional one-to-one joined relationship emits SQL when it shouldn't

### ISSUE THREAD

**Issue by gerazenobi** [sqlalchemy/sqlalchemy#5725]
Hi there,

I have a bidirectional one-to-one **joined** relationship configured between 2 tables and I am seeing SQL being emitted when it shouldn't (as the referenced instance should be already loaded)

**To Reproduce**

```py
# Simplified model

from sqlalchemy import create_engine, Column, Integer, String, ForeignKey, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship, contains_eager

engine = create_engine("sqlite:///eager_loading.db", echo=True)
Base = declarative_base()


class System(Base):
    __tablename__ = "system"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, nullable=False)
    stations = relationship("Station", back_populates="system", lazy="dynamic", passive_deletes="all")


class Station(Base):
    __tablename__ = "station"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, nullable=False)
    system_id = Column(Integer, ForeignKey("system.id", ondelete="CASCADE"))

    system = relationship("System", back_populates="stations")
    status = relationship(
        "StationStatus", back_populates="station", uselist=False, passive_deletes="all", lazy="joined"
    )

    def __repr__(self):
        return f"Station(id={self.id})"


class StationStatus(Base):
    __tablename__ = "station_status"
    station_id = Column(Integer, ForeignKey("station.id", ondelete="CASCADE"), primary_key=True)
    status = Column(Boolean)
    station = relationship("Station", back_populates="status", lazy="joined", innerjoin=True)

    def __repr__(self):
        return f"StationStatus(station_id={self.station_id})"


Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()


def init():
    system = System(name="test_system")
    session.add(system)
    for i in range(3):
        st = Station(name=f"station-{i + 1}")
        st.status = StationStatus(status=True)
        system.stations.append(st)
    session.commit()


system = session.query(System).filter(System.id == 1).one_or_none()
if system is None:
    init()

# Error
system = session.query(System).filter(System.id == 1).one()
station_statuses = [st.status for st in system.stations]
station_statuses[0].station  # SQL is emitted even if station is supposed to be joined loaded already:

# INFO sqlalchemy.engine.base.Engine SELECT station.id AS station_id, station.name AS station_name, station.system_id AS station_system_id, station_status_1.station_id AS station_status_1_station_id, station_status_1.status AS station_status_1_status 
# FROM station LEFT OUTER JOIN station_status AS station_status_1 ON station.id = station_status_1.station_id 
# WHERE station.id = ?

```

**Versions.**
 - OS: macOS 10.14.6
 - Python: 3.6.8
 - SQLAlchemy:  1.3.20
 - Database: postgres (PostgreSQL) 10.13
 - DBAPI: psycopg2-binary 2.8.6

**Additional context**
Strangely enough the following, exaggerated, scenario does work as expected
```py
system = session.query(System).filter(System.id == 1).one()
stations = [st for st in system.stations]
status = stations[0].status
station = status.station  # NO SQL is emitted
station.status  # NO SQL is emitted
status = station.status  # NO SQL is emitted
print(status.station)  # NO SQL is emitted
```

Any help would be appreciated, thanks in advance.

**Comment by zzzeek** [comment]
I could give you a better answer if you gave me a runnable example but due to the difference in behavior between your two examples we can assume that the Station objects are being garbage collected after you are done with:

    station_statuses = [st.status for st in system.stations]

now you have a list of Status objects , Status.station is many-to-one so it would pull the object from the identity map and not emit SQL, however because all the Station objects were GC'ed it has to emit SQL again.

as to why a query for Station is not doing joinedload across Station -> Status -> Station I'd assume that is due to the loop detection which prevents it from going into an endless loop.  if you use explicit joinedload() options then it would have a definitive depth to be joining toward and may give you the result you want.

again with a full test case I could confirm these hunches.

**Comment by gerazenobi** [comment]
Hi @zzzeek,

Thanks for the quick response. I have updated the example with a runnable one so you could confirm your hunches.

> Status.station is many-to-one

Actually it is meant to be a one-to-one.

> as to why a query for Station is not doing joinedload across Station -> Status -> Station I'd assume that is due to the loop detection which prevents it from going into an endless loop.

the way I saw it was (and correct me I am wrong): I load `station` objects that have a (bidirectional) joined relationship with `station_status`, then since they are both loaded I can 'navigate' back and forth between them (like double linked nodes references?) without emitting any SQL.

Thanks.

**Comment by zzzeek** [comment]
> Hi @zzzeek,
> 
> Thanks for the quick response. I have updated the example with a runnable one so you could confirm your hunches.

sure, just look at the query, you can see the joined eager load only takes place for station->station_status:

```
SELECT station.id AS station_id, station.name AS station_name, station.system_id AS station_system_id, station_status_1.station_id AS station_status_1_station_id, station_status_1.status AS station_status_1_status 
FROM station LEFT OUTER JOIN station_status AS station_status_1 ON station.id = station_status_1.station_id 
WHERE ? = station.system_id

```

to joinedload both links actively, make it explciit:
```

from sqlalchemy.orm import joinedload

system = session.query(System).filter(System.id == 1).one()

statuses = list(system.stations.options(joinedload(Station.status).joinedload(StationStatus.station)))

```
now the query is:

```
SELECT station.id AS station_id, station.name AS station_name, station.system_id AS station_system_id, station_1.id AS station_1_id, station_1.name AS station_1_name, station_1.system_id AS station_1_system_id, station_status_1.station_id AS station_status_1_station_id, station_status_1.status AS station_status_1_status 
FROM station LEFT OUTER JOIN (station_status AS station_status_1 JOIN station AS station_1 ON station_1.id = station_status_1.station_id) ON station.id = station_status_1.station_id 
WHERE ? = station.system_id

```

now if we enforce that the many-to-one "load" can't happen, it still works:

```
station_statuses = [st.status for st in statuses]

# GC statuses.
del statuses


status = station_statuses[0]

# close the session.  now it will raise if there's any kind of problem
session.close()

# element is already loaded due to joinedload() above
assert "station" in status.__dict__

# works because the joinedload was forced
status.station

```


> 
> > Status.station is many-to-one
> 
> Actually it is meant to be a one-to-one.

the primary key constraint makes it one-to-one but SQLAlchemy treats any relationship where the foreign key-constrained columns are on the "local" side as "many to one" from a loading point of view.


> 
> > as to why a query for Station is not doing joinedload across Station -> Status -> Station I'd assume that is due to the loop detection which prevents it from going into an endless loop.
> 
> the way I saw it was (and correct me I am wrong): I load `station` objects that have a (bidirectional) joined relationship with `station_status`, then since they are both loaded I can 'navigate' back and forth between them (like double linked nodes references?) without emitting any SQL. 

that's correct, as long as the "Station" objects are not garbage collected.   the many-to-one relationship looks it up by primary key in the identity map. if the Station object falls out of scope, then it has to be loaded again.   the joined eager loading part of it is not actively populating the StationStatus.station attribute at query time in this case.


I guess this way of thinking would explain why the exaggerated example 2 in **Additional context** section works.
> 
> Thanks.

**Comment by zzzeek** [comment]
hope this helps.

**Comment by gerazenobi** [comment]
Thanks for the answers @zzzeek and sorry for my late reply.

 What I took is that the root cause was garbage collection.

What I didn't understand was why would the `stations` instances be garbage collected if they were being reference by `station_statuses` instances (`st.station`) as we had seen ? or these statuses don't actually hold direct references to them ?

```python
station_statuses = [st.status for st in system.stations]
st = station_statuses[0]  # statuses in scope ...

```

If you could help me understand that briefly that would be great.

Thanks again.

**Comment by zzzeek** [comment]
> Thanks for the answers @zzzeek and sorry for my late reply.
> 
> What I took is that the root cause was garbage collection.

that's correct

> 
> What I didn't understand was why would the `stations` instances be garbage collected if they were being reference by `station_statuses` instances (`st.station`) as we had seen ? or these statuses don't actually hold direct references to them ?
> 
> ```python
> station_statuses = [st.status for st in system.stations]
> st = station_statuses[0]  # statuses in scope but we've lost their references to stations ...

Above, system.stations is a dynamic relationship.  this means that "stations" is not a list, it's a Query that is stateless as far as the objects it returns.  when you iterate it, the Python `__iter__` method is used to trigger a query to the database, load a bunch of Station objects, and iterate them.

the code then iterates through each item in this iterable, assigning each Station object to the variable "st".  As the list comprehension continues, the previous Station that was assigned to "st" is no longer referenced by "st".    With each Station object, you access the ".status" attribute, which will load and/or pull from the Session a StationStatus object.   A StationStatus object is capable of referring back to its parent Station via the ".station" attribute, but this attribute is unpopulated at the time of this list comprehension taking place.

Therefore, the above code assigns a Station only to the variable "st" which is immediately replaced by a new Station for each item in the iterable.  The previously referenced Station is no longer strongly referenced.

> 
> Furthermore, I didn't understand why would I have to perform a somewhat redundant join to prevent the above? as you pointed in the query you mentioned
> 
> ```sql
> SELECT station.id AS station_id, station.name AS station_name, station.system_id AS station_system_id, station_1.id AS station_1_id, station_1.name AS station_1_name, station_1.system_id AS station_1_system_id, station_status_1.station_id AS station_status_1_station_id, station_status_1.status AS station_status_1_status 
> FROM station LEFT OUTER JOIN (station_status AS station_status_1 JOIN station AS station_1 ON station_1.id = station_status_1.station_id) ON station.id = station_status_1.station_id 
> WHERE ? = station.system_id
> ```
> 
> in other words, why this actually prevents the garbage collection seen above.

This concerns the StationStatus.station attribute.  If, as you go through the list comprehension, each "st" variable referencing a Station which references a StationStatus then contains a reference *back* to the Station, then as you collect StationStatus objects, you are also maintaining a strong reference to the Station objects in addition to the one held temporarily by the "st" variable.

For StationStatus.station to be pre-populated without your accessing it explicitly, it must be eagerly loaded in some way. There's a lot of ways to make that happen but as your relationships refer to "lazy='joined'" I've illustrated how to get the "joined" eager load to work across two levels.     Without some kind of eager loading of StationStatus.station it remains unpopulated, meaning you would not see the key "station" inside of each status_station.__dict__.

> 
> I must say I might not be familiar with the concept of _loading actively both links_ as I have never had the need for thinking when dealing with relationships.

well you don't really have to think about these things unless you are optimizing, which is what this issue is about; an extra SQL query you're looking to prevent.


> 
> Thanks again.

**Comment by gerazenobi** [comment]
Thanks again for the detailed explanation @zzzeek, very helpful.

> A StationStatus object is capable of referring back to its parent Station via the ".station" attribute, but this attribute is unpopulated at the time of this list comprehension taking place.

This was the giveaway for me as I had thought/imagined given the _joined_ specification it was in fact populated at that time. 

What I take then is, and correct me if I am wrong: even though all the information is eagerly loaded into the session: that is we have all `Station`s and all `StationStatus`s  in 1 one roundtrip to the db given how we defined the relationship as _joined_, that doesn't necessarily mean all the references between these instances will be actively populated, or in other words the double link/circular reference doesn't get automatically filled, just one side of it (and I am not talking about fetching information from the database, we are just talking about fetching the information from the session and populating the links/references).

In order from sqlalchemy to set the other side of the relationship explicit access has to occur: kind of similar concept to `lazy=select` excepts that one refers to going to the db, and here we are talking only about references and information already in the session.

Just wanted to confirm my logic was right after your last response.

Thanks :)

**Comment by zzzeek** [comment]
> 
> What I take then is, and correct me if I am wrong: even though all the information is eagerly loaded into the session: that is we have all `Station`s and all `StationStatus`s in 1 one roundtrip to the db given how we defined the relationship as _joined_, that doesn't necessarily mean all the references between these instances will be actively populated, or in other words the double link/circular reference doesn't get automatically filled, just one side of it 

that's correct in as far as that is a current behavior of a relationship() that has lazy="joined" configured on both sides.    It uses a simple loop-detection scheme to avoid joining twice.    A more sophisticated scheme could in theory try to connect in both directions but not go beyond that limit.    But overall this restriction only applies to the class-level relationship() "lazy='joined'" flag.   When using the joinedload() loader option with query.options(), the eager loads will continue for as many levels deep as you've told it to do.


> (and I am not talking about fetching information from the database, we are just talking about fetching the information from the session and populating the links/references).

I'm actually talking about fetching the information from the database.  If the database query has been instructed to eagerly load from Station->StationStatus->Station, you would get each StationStatus bi-directionally populated up front.  


> 
> In order from sqlalchemy to set the other side of the relationship explicit access has to occur: kind of similar concept to `lazy=select` excepts that one refers to going to the db, and here we are talking only about references and information already in the session.

or if you use query.options(joinedload(Station.status).joinedload(StatusStation.stations)) in your query.


> 
> Just wanted to confirm my logic was right after your last response.
> 
> Thanks :)
