### ISSUE TITLE
Wrong type for results from PostgreSQL system columns

### ISSUE THREAD

**Issue by sevens-ef** [sqlalchemy/sqlalchemy#5728]
**Describe the bug**
Following the example from https://docs.sqlalchemy.org/en/13/orm/versioning.html#server-side-version-counters , when fetching an object from the database the type of the system column (`xmin`) seems to be wrong (`str` instead of `int`).

A quick check (manual query) confirms that the value in the `xmin` column is indeed an integer in the database itself.

**Expected behavior**
The `xmin` value to be an `int`.

**To Reproduce**

```py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import *

Base = declarative_base()


class User(Base):
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True)
    name = Column(String(50), nullable=False)
    xmin = Column("xmin", Integer, system=True, server_default=FetchedValue())

    __mapper_args__ = {
        'version_id_col': xmin,
        'version_id_generator': False
    }


e = create_engine(..., echo=True)
Base.metadata.create_all(e)
s = Session(e)

user = User(name='name')
s.add(user)
s.commit()

s.expire(user)
assert isinstance(user.xmin, str)  # This succeeds, even though the column type is `Integer`
assert isinstance(user.xmin, int)  # and this fails
```

I also tested this code using the `xmax`, `cmin` system columns and they had the same issue.

**Versions.**
 - OS: Ubuntu 18.04.5
 - Python: 3.9.0 (also reproduced on 3.6.x)
 - SQLAlchemy: 1.3.20
 - Database: PostgreSQL 9.6
 - DBAPI: psycopg2 2.8.6

**Additional context**
It seems to me that either the result type is wrong, or the documentation example is wrong/confusing.

**Comment by zzzeek** [comment]
hey there -

Can you share your evidence that the value is an integer?   The test below indicates it is an internal PostgreSQL type called "xid" (I would assume transaction id), and it appears to behave more as a string than as an integer.

Given:

```
psql (12.4)
Type "help" for help.

test=> create table foo(id integer);
CREATE TABLE
test=> insert into foo values(35);
INSERT 0 1


test=> select xmin from foo;
 xmin 
------
 7178
(1 row)

```

the value successfully casts into VARCHAR, both explicitly and implicitly:

```
test=> select xmin::varchar AS "is it a string?" from foo;
 is it a string? 
-----------------
 7178
(1 row)


test=> select xmin || 'it concats, like a string' from foo;
           ?column?            
-------------------------------
 7178it concats, like a string
(1 row)

```

however it does neither for integer:

```
test=> select xmin::int AS "is it an integer?" from foo;
ERROR:  cannot cast type xid to integer
LINE 1: select xmin::int AS "is it an integer?" from foo;
                   ^


test=> select xmin + 35 AS "it's won't do arithmetic, not an int" from foo;
ERROR:  operator does not exist: xid + integer
LINE 1: select xmin + 35 AS "it's won't do arithmetic, not an int" f...
                    ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

```

it seems a safe bet we should change that documentation example to use String for xmin and not integer.

**Comment by sevens-ef** [comment]
Hi,

I just did a quick query (`SELECT xmin FROM some_table WHERE ...`) and assumed the result was an int since it looked like one.  Forgetting that in `psql` string results render just like the same as ints (I don't have to use direct SQL that often anymore, I'm blaming ORMs for that ;) ).

Besides that, https://www.postgresql.org/docs/9.6/ddl-system-columns.html talks about a "transaction ID" and I also assumed that was talking about integers (combined with the SQLAlchemy documentation example also using integers), together with me vaguely remembering us hitting an internal Postgres integer max on transaction IDs many years before.

Hence the safe-guards in my initial report on this :)

> it seems a safe bet we should change that documentation example to use String for xmin and not integer.

I agree, especially considering your tests (even *if* Postgres may use an int internally, if it's presented like a string to clients it makes sense to me if SQLAlchemy and the docs do so as well).

**Comment by zzzeek** [comment]
same all around, it looked like a number so certainly that's why I put Integer there also, will change it now.

**Comment by sevens-ef** [comment]
Great, thanks for fixing, will adjust our usages of this example as well.
