### ISSUE TITLE
Incorrect import statement in online doc

### ISSUE THREAD

**Issue by debugger22** [sqlalchemy/sqlalchemy#5731]
Link: https://docs.sqlalchemy.org/en/14/tutorial/metadata.html#setting-up-the-registry

The above link has an incorrect import statement
```
from sqlalchemy.orm import declarative_base
```
Apparently, `declarative_base` has moved out of `orm` which is not reflected in the doc.

**Have a nice day!**

**Comment by debugger22** [comment]
My bad! I was reading docs for `1.4` and running `1.3`. :1234:

**Comment by zzzeek** [comment]
there's an issue here which is I need to change the website redirects to show the 1.3 docs by default.   will see if I can do that now.

**Comment by zzzeek** [comment]
that's live now.    the /stable/ docs are what will come up by default.
