### ISSUE TITLE
`InstanceEvents.refresh()` event is not fired for lazy-loaded relationships

### ISSUE THREAD

**Issue by kolypto** [sqlalchemy/sqlalchemy#5736]
**Describe the bug**
SqlAlchemy [documentation for `InstanceEvents.refresh()`](https://docs.sqlalchemy.org/en/13/orm/events.html#sqlalchemy.orm.events.InstanceEvents.refresh) says that it's fired when *attributes* are loaded:

> Receive an object instance after one or more attributes have been refreshed from a query.

this gives the impression that it is fired for both columns and attributes.

**Expected behavior**
The event is fired for deferred columns and lazy-loaded relationships

**To Reproduce**

Run with pytest; no external dependencies

```python
from contextlib import contextmanager
from typing import Optional, Set, Union, List

import pytest

import sqlalchemy as sa
import sqlalchemy.orm
import sqlalchemy.event
import sqlalchemy.ext.declarative


def test_instance_event_refresh_fired_when_attributes_are_lazyloaded(ssn: sa.orm.Session):
    """ Test that `InstanceEvents.refresh` is fired when lazy-loading a column atttribute """
    # Create some objects
    ssn.add(
        User(
            name='John',
            articles=[Article() for _ in range(10)]
        )
    )
    ssn.flush()

    # Get a clean session
    ssn.expire_all()

    # Listen to "refresh"
    with listen_to_instance_event_refresh() as logged_events:
        # Load user
        user = ssn.query(User).options(
            # Make sure the `name` column is not loaded
            sa.orm.load_only('id')
        ).first()

        # Trigger a lazy-load
        user.name  # noqa
        user.articles  # noqa

        # Was the event fired?
        assert logged_events == [
            # 👍 This one works fine
            f"User(id={user.id}) refresh attrs=['name']",
            # 🛑 This line is not added because "refresh" is not reported for relationship lazy-loads
            f"User(id={user.id}) refresh attrs=['articles']",
        ]



# Define some models
Base = sa.ext.declarative.declarative_base()


class User(Base):
    __tablename__ = 'u'
    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.String)

    articles = sa.orm.relationship(lambda: Article, back_populates='author')


class Article(Base):
    __tablename__ = 'a'
    id = sa.Column(sa.Integer, primary_key=True)

    author_id = sa.Column(sa.Integer, sa.ForeignKey(User.id))
    author = sa.orm.relationship(User, back_populates='articles')



@contextmanager
def listen_to_instance_event_refresh() -> List[str]:
    """ Subscribe to InstanceEvents.refresh() and log every event into an array

    Returns:
        a mutable list where every event is logged as a string
    """
    # Accumulator
    logged_events = []

    # Listen
    @sa.event.listens_for(sa.orm.Mapper, "refresh", named=True)
    def on_refresh(target: Union[User, Article], context: sa.orm.query.QueryContext, attrs: Optional[Set[str]]):
        logged_events.append(f'{target.__class__.__name__}(id={target.id}) refresh attrs={sorted(attrs) if attrs else None}')

    # Test: trigger attribute lazy-load
    try:
        yield logged_events
    # Unsubscribe
    finally:
        sa.event.remove(sa.orm.Mapper, "refresh", on_refresh)




@pytest.fixture()
def ssn():
    """ Get a working SqlAlchemy session """
    # Init a working DB engine, sessionmaker
    engine: sa.engine.Engine = sa.engine.create_engine('sqlite://')
    SessionMaker = sa.orm.sessionmaker(bind=engine)

    # Recreate the database
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)

    # Session
    try:
        ssn = SessionMaker()
        yield ssn
    finally:
        ssn.close()

```

**Error**

The relationship lazy-loading is not reported:

```
E           assert ["User(id=1) refresh attrs=['name']"] == ["User(id=1) refresh attrs=['name']", "User(id=1) refresh attrs=['articles']"]
E             Right contains one more item: "User(id=1) refresh attrs=['articles']"
E             Full diff:
E             - ["User(id=1) refresh attrs=['name']", "User(id=1) refresh attrs=['articles']"]
E             + ["User(id=1) refresh attrs=['name']"]
```

**Versions.**
 - OS: Ubuntu Linux
 - Python: 3.9
 - SQLAlchemy: 1.3.20
 - Database: Any
 - DBAPI: Any

**Additional context**
Why would I care? :) Because catching this event is essential to implement a proper solution to the N+1 problem.

**Comment by zzzeek** [comment]
hey there -

the refresh() event refers to those attributes that are populated on an object of primary key P, when an ORM row is  loaded from the database that refers to primary key P.  This by definition does not include lazy loads.

```
  # will likely trigger the "load" event for User
  user = ssn.query(User).options(
            # Make sure the `name` column is not loaded
            sa.orm.load_only('id')
        ).first()

    # look at the echoed SQL.  This will show that all columns for User are being loaded.
    # this will trigger "refresh" for all those columns.  in 1.4 it also should include configured
    # *eager* loaders as separate queries, but those attribute names should also be here
    # (if not that might be a new issue to raise at that is new in 1.4)
    user.name

    # this will trigger a lazy load of "Articles".   So here there is no "refresh"
    # of User, User is already loaded fully.  The Article objects themselves as they are not loaded
    # at all would be triggering the load() event
    user.articles  # noqa
```

> Why would I care? :) Because catching this event is essential to implement a proper solution to the N+1 problem.

this is not the event one would use to catch the N+1 problem with regards to relationships as by definition it does not catch relationship lazy loads.    The N+1 problem can be caught most simply by using the [raiseload](https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html#preventing-unwanted-lazy-loads-using-raiseload) loader strategy.    if you place it at the mapping level, your program wont ever do any lazy loads by default which will inform you where you need to use eager loading.

the next way to find N+1 is counting the queries emitted on a per-operation basis; see the recipe I just wrote for someone in #5709:
```

from sqlalchemy import event
import contextlib

@contextlib.contextmanager
def count_queries(conn):
    queries = []
    def before_cursor_execute(conn, cursor, statement, parameters, context, executemany):
        queries.append(statement)

    event.listen(conn, "before_cursor_execute", before_cursor_execute)
    try:
        yield queries
    finally:
        event.remove(conn, "before_cursor_execute", before_cursor_execute)

# example use
with count_queries(session.connection()) as queries:
    for a1 in s.query(A):
        a1.bs

print("total number of queries: %s" % len(queries))
```

as mentioned in that issue, we likely need an FAQ on "how to detect N+1" that refers to the above two techniques.

**Comment by kolypto** [comment]
@zzzeek thanks for such an elaborate answer :) There's no event that serves this purpose then. I've tried all events (can show the code) and SqlAlchemy is completely silent when a relationship is lazyloaded :) 

`raiseload('*')` is a good way to catch relationships, but only works at the top level by default. If a related instance's attribute is lazyloaded (2-nd level), raiseload is not even applied.

And actually I'm not working on N+1 *detection*, but rather, a *solution* :)

I don't want to waste your time, but if you're curious, it almost works. The idea is simple: if an attribute is lazy-loaded, and there are N more instances in the Session, it's very likely that N+1 will happen on that attribute. So the solution makes 1 extra query to populate this attribute for all instances using my custom made [bulk loader](https://github.com/kolypto/py-nplus1loader/blob/master/nplus1loader/bulk_load.py).

The loader works very well. The last standing issue is when to fire it. I've tried a loader option, but the result was not reliable. Now I am trying to use SA events.... which do not provide the required support unfortunately ))

**Comment by zzzeek** [comment]
> @zzzeek thanks for such an elaborate answer :) There's no event that serves this purpose then. I've tried all events (can show the code) and SqlAlchemy is completely silent when a relationship is lazyloaded :)

that is categorically false.   Here are some of the events fired when a lazyload *that emits SQL to the database* occurs:

before_cursor_execute
after_cursor_execute
before_execute
after_execute
loaded_as_persistent
before_compile with bake_ok=False  (1.3 only) - this is the event that would most closely be identifiable as a "lazy load" as well; 1.4 has a much better hook

in 1.4 the [do_orm_execute](https://docs.sqlalchemy.org/en/14/orm/events.html?highlight=sessionevents#sqlalchemy.orm.SessionEvents.do_orm_execute) event is by far the best hook to use for this.  as you are writing an extension I'd target 1.4.

here is your test script using loaded_as_persistent:

```
from contextlib import contextmanager
from typing import Optional, Set, Union, List

import pytest

import sqlalchemy as sa
import sqlalchemy.orm
import sqlalchemy.event
import sqlalchemy.ext.declarative


def test_instance_event_refresh_fired_when_attributes_are_lazyloaded(
    ssn: sa.orm.Session,
):
    """ Test that `InstanceEvents.refresh` is fired when lazy-loading a column atttribute """
    # Create some objects
    ssn.add(User(name="John", articles=[Article() for _ in range(10)]))
    ssn.flush()

    # Get a clean session
    ssn.expire_all()

    # Listen to "refresh"
    with listen_to_instance_loaded_as_persistent() as logged_events:
        # Load user
        user = (
            ssn.query(User)
            .options(
                # Make sure the `name` column is not loaded
                sa.orm.load_only("id")
            )
            .first()
        )

        # Trigger a lazy-load
        user.name  # noqa
        user.articles  # noqa

        # Was the event fired?
        assert logged_events == [
            "User(id=1)",
            "Article(id=1)",
            "Article(id=2)",
            "Article(id=3)",
            "Article(id=4)",
            "Article(id=5)",
            "Article(id=6)",
            "Article(id=7)",
            "Article(id=8)",
            "Article(id=9)",
            "Article(id=10)",
        ]


# Define some models
Base = sa.ext.declarative.declarative_base()


class User(Base):
    __tablename__ = "u"
    id = sa.Column(sa.Integer, primary_key=True)
    name = sa.Column(sa.String)

    articles = sa.orm.relationship(lambda: Article, back_populates="author")


class Article(Base):
    __tablename__ = "a"
    id = sa.Column(sa.Integer, primary_key=True)

    author_id = sa.Column(sa.Integer, sa.ForeignKey(User.id))
    author = sa.orm.relationship(User, back_populates="articles")


@contextmanager
def listen_to_instance_loaded_as_persistent() -> List[str]:
    """Subscribe to InstanceEvents.refresh() and log every event into an array

    Returns:
        a mutable list where every event is logged as a string
    """
    # Accumulator
    logged_events = []

    # Listen
    @sa.event.listens_for(sa.orm.Session, "loaded_as_persistent", named=True)
    def on_refresh(session, instance):
        logged_events.append(
            f"{instance.__class__.__name__}(id={instance.id})"
        )

    # Test: trigger attribute lazy-load
    try:
        yield logged_events
    # Unsubscribe
    finally:
        sa.event.remove(sa.orm.Session, "loaded_as_persistent", on_refresh)


@pytest.fixture()
def ssn():
    """ Get a working SqlAlchemy session """
    # Init a working DB engine, sessionmaker
    engine: sa.engine.Engine = sa.engine.create_engine("sqlite://")
    SessionMaker = sa.orm.sessionmaker(bind=engine)

    # Recreate the database
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)

    # Session
    try:
        ssn = SessionMaker()
        yield ssn
    finally:
        ssn.close()

```

a lazy load does not emit SQL to the database if the relationship is many-to-one and the target object is locally present in the session already.  for these, the above events won't fire off.  


> 
> `raiseload('*')` is a good way to catch relationships, but only works at the top level by default. 

this is also incorrect.    raiseload when used properly works at every level and has no restrictions on "level".  Here is a demonstration using it as an option, firing off at the second level after a lazy load:

```

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import defaultload
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)
    cs = relationship("C")

class C(Base):
    __tablename__ = 'c'
    id = Column(Integer, primary_key=True)
    b_id = Column(ForeignKey("b.id"))
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs=[B(cs=[C()])]))
s.commit()


a1 = s.query(A).options(defaultload(A.bs).raiseload(B.cs)).first()

print(a1.bs[0].cs)
```

here is a demonstration using it as classlevel, firing off after a lazy load at the second level:

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import defaultload
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)
    cs = relationship("C", lazy="raise")

class C(Base):
    __tablename__ = 'c'
    id = Column(Integer, primary_key=True)
    b_id = Column(ForeignKey("b.id"))
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs=[B(cs=[C()])]))
s.commit()


a1 = s.query(A).first()

print(a1.bs[0].cs)
```

> If a related instance's attribute is lazyloaded (2-nd level), `raiseload('*')` is not applied to it. Well, unless I do it manually. This is how it's supposed to be :)

see the above MCVEs for a demonstration, please illustrate the result you are getting.


> And actually I'm not working on N+1 _detection_, but rather, a _solution_ :)
> 
> I don't want to waste your time, but if you're curious, it almost works. 

to be honest when you make comments like "X doesnt work, I guess SQLAlchemy can't do it" without the courtesy of showing an MCVE that almost seems like an intentional effort to get me to write scripts for you.     Please avoid making blanket statements without illustrating clear demonstrations of how you are making use of a particular API, what you expect, and what is not happening.  The first example here was fine in that regard and I was able to answer it without writing whole scripts.


> The idea is simple: if an attribute is lazy-loaded, and there are N more instances in the Session, it's very likely that N+1 will happen on that attribute. So the solution makes 1 extra query to populate this attribute for all instances using my custom made [bulk loader](https://github.com/kolypto/py-nplus1loader/blob/master/nplus1loader/bulk_load.py).

that is fine, this may even be an option an ORM like hibernate has buried in there some place.   the "selectinload" strategy at least now provides a load of this nature, however it is not automatically triggered from a lazyload.   it certainly could be and that might not be too difficult.  I would call it "lazy_selectinload".    However whether it spans all objects in the session or only those that were just loaded makes it a bit of a loose cannon and for the moment I'm satisfied having selectinload() being something that can be explicitly opted into.     

II hope you can make use of the "selectinload" strategy in your extension, which I would suggest you target using the above mentioned do_orm_execute() hook.

**Comment by kolypto** [comment]
@zzzeek thanks you for the examples! 
I did not intend to expect you to do my work :) Sorry if this was the impression.

The `raiseload('*')` thing was a misunderstanding. What I meant it that in order to have guaranteed exceptions for *every* lazy-load, one would need to "terminate" every relationship loader option with a `raiseload('*')` like you've shown:

```python
ssn.query(...).options(
  defaultload(...).raiseload('*'),  # 2nd level
  defaultload(...).options(
    defaultload(...).raiseload('*'),  # 3rd level
    raiseload('*'),  # 2nd level again!
  ),
  raiseload('*'),  # 1st level
)
```

and this is easy to forget if you have many relationships :) 
It's possible. But that's not an easy on/off swich that would catch them all. This is what I wanted to show.

The events you've described are good. There are some issues that are still left, but I'll find a workaround :) 
It's really impressive how responsive you are in this repository btw! I appreciate it and value your time! :) 

Thanks)

**Comment by zzzeek** [comment]
> @zzzeek thanks you for the examples!
> I did not expect you to do my work :) Sorry if this was the impression you've got.
> 
> The `raiseload('*')` thing was a misunderstanding. What I meant it that in order to have guaranteed exceptions for _every_ lazy-load, one would need to "terminate" every relationship loader option with a `raiseload('*')` like you've shown:
> 
> ```python
> ssn.query(...).options(
>   defaultload(...).raiseload('*'),  # 2nd level
>   defaultload(...).options(
>     defaultload(...).raiseload('*'),  # 3rd level
>     raiseload('*'),  # 2nd level again!
>   ),
>   raiseload('*'),  # 1st level
> )

I'm not able to reproduce this as far as a realistic scenario.  raiseload("*") is for all lazy loaders that are established in that query:

```
    a1 = s.query(A).options(raiseload("*"), selectinload(A.bs)).first()

    print(a1.bs[0].cs)  # raises on cs

```

If A.bs was not set up for "selectinload", it would also be raiseload(), so it would never be loadable and therefore you'd never get to B.cs.     

show me a script where raiseload("*") is in the options and you can get a lazyload to fire off after the fact.




> ```
> 
> and this is easy to forget if you have many relationships :)
> It's possible. But that's not an easy on/off swich that would catch them all. This is what I wanted to show.
> Class-level strategies are fine, but also have their own limitations.
> 
> The events you've described are good. There are some issues that are still left, but I'll find a workaround :)
> It's really impressive how responsive you are in this repository btw! I appreciate it and value your time! :)
> 
> Thanks)

**Comment by kolypto** [comment]
@zzzeek I just tried, and yes, indeed, `raiseload('*')` works as a catch-all loader, for every level.

I have no idea why I was so certain it won't affect the 2nd level :D
