### ISSUE TITLE
Setting identity or sequence cycle=False will render CYCLE instead of NO CYCLE

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5738]
This is because we use 
```py
if identity_options.cycle is not None:
    text.append("CYCLE")
```

edit: a similar issue is also for order

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Properly render ``cycle=False`` and ``order=False``** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2391
