### ISSUE TITLE
Queries using contains_eager and filter may include results that should be filtered

### ISSUE THREAD

**Issue by krispharper** [sqlalchemy/sqlalchemy#5740]
**Describe the bug**

When using `contains_eager` in a query that filters child objects, objects that don't match the filter are returned if they exist in the cached session already.

Specifically, if, in the same session, you

* Create a parent and child object and add them to the session.
* Perform a joined query that uses `contains_eager` and also `filter`s the child object.

then the results of that query will include a parent object that has the child as a property, even though the child was not actually returned in the query.

**Expected behavior**

Objects should be filtered accordingly. More generally, queries that use `contains_eager` should return the same results on a new session as they do on a session with objects in the local cache.

**To Reproduce**

Here's a full working example. The `assert` statements at the bottom demonstrate the issue, I think.

```
from sqlalchemy import and_, Column, create_engine, DateTime, ForeignKey, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import contains_eager, relationship, sessionmaker


create_statements = ["""
    DROP TABLE IF EXISTS child;
    """, """
    DROP TABLE IF EXISTS parent;
    """, """
    CREATE TABLE parent
    (
        id INTEGER NOT NULL PRIMARY KEY,
        name VARCHAR
    );
    """, """
    CREATE TABLE child
    (
        id INTEGER NOT NULL PRIMARY KEY,
        parent_id INTEGER REFERENCES parent(id),
        value INTEGER
    );
    """
]

Base = declarative_base()


class Parent(Base):
    __tablename__ = "parent"
    __table_args__ = {'implicit_returning': False}
    id = Column(Integer, primary_key=True)
    name = Column(String)

    children = relationship("Child", back_populates="parent")


class Child(Base):
    __tablename__ = "child"
    __table_args__ = {'implicit_returning': False}
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey(Parent.id))
    value = Column(Integer)

    parent = relationship(Parent, back_populates="children")


if __name__ == "__main__":
    engine = create_engine(f"sqlite:///")
    session = sessionmaker(bind=engine)()

    for statement in create_statements:
        session.execute(statement)

    p1 = Parent(id=1, name="A")
    c1 = Child(id=1, parent=p1, value=10)
    c2 = Child(id=2, parent=p1, value=20)
    session.add_all([p1, c1, c2])
    session.flush()
    # session.expire_all()  # Uncommenting this makes the below work as expected.

    results = session \
        .query(Parent) \
        .join(Child, Parent.id == Child.parent_id) \
        .options(
            contains_eager(Parent.children)
        ).filter(Child.value < 15) \
        .order_by(Parent.id) \
        .all()

    assert len(results[0].children) == 1  # We should only have 1 child.
    assert all(c.value < 15 for c in results[0].children)  # All children should match the above filter condition.
```

**Error**

No specific error, but the above `assert` statements demonstrate the issue.

**Versions.**
 - OS: Debian inside Docker.
 - Python: 3.8
 - SQLAlchemy: 1.3.20
 - Database: Tested on both Postgresql and Sqlite

**Additional context**

This may be expected behavior and I am just using `contains_eager` wrong. It just seems surprising to me because I think this is one of the first times that I've had to be conscious of what's in the local state versus the database.

**Comment by zzzeek** [comment]
hi there -

We have a lot of these questions coming in lately and there are some documentation patches in the works regarding the [populate_existing()](https://docs.sqlalchemy.org/en/13/orm/query.html?highlight=populate_existing#sqlalchemy.orm.query.Query.populate_existing) method however I'm amazed this one does not seem to be up on the site already as we've had a barrage of this same question over and over again in the past few weeks regarding raiseload.   

the section at https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html?highlight=contains_eager#using-contains-eager-to-load-a-custom-filtered-collection-result is not clear enough but this is all expected behavior.   use populate_existing() whenever you use contains_eager():

    query.options(conains_eager()).populate_existing()

kind of amazed I dont see this in any of the contains_eager() docs in 1.3 or 1.4, will add right now.

**Comment by krispharper** [comment]
Ah, got it. Yeah, I had read and re-read that section you linked, but I didn't quite see what I was doing wrong. I see now that places like [this](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html?highlight=contains_eager#adding-criteria-to-loader-options) describe the `populate_existing` functionality with filtering.

Thanks a bunch for the quick response. I'm happy to close this if that's the right thing to do.

**Comment by zzzeek** [comment]
i pushed up the new docs which will close this.
