### ISSUE TITLE
defaults with decimal places in them are reported differently on MariaDB, need to add decimal point for reflection

### ISSUE THREAD

**Issue by Redysz** [sqlalchemy/sqlalchemy#5744]
Suppose I have table main_table with columns:

`id (AUTO_INCREMENT), first (int), value1 (double with default=0), value2 (double)`

Using code
```
engine = sqlalchemy.create_engine(db_connect)
session = Session(engine)
base = automap_base()
base.prepare(engine, reflect=True)
table = getattr(base.classes, fact_table)
kwargs = {'first': 200016, 'value2': 1.0}
entry = table(**kwargs)
session.add(entry)
session.commit()
```

I got an error `{"error": 500, "message": "(pymysql.err.IntegrityError) (1048, \"Column 'value1' cannot be null\")`

It happens when `value1` doesn't accept null value.

I'd like to ignore this and add entry after all `value1` is not obligatory (has default).

**Versions.**
 - OS: Windows 10
 - Python: 3.8
 - SQLAlchemy: 1.3.20
 - Database: 10.5.5

**Edit:**
MariaDB 10.5.5

`SHOW CREATE TABLE main_table;`:

```
CREATE TABLE `main_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first` int(11) NOT NULL,
  `value1` double(22,6) NOT NULL DEFAULT 0.000000,
  `value2` double(22,6) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=200000 DEFAULT CHARSET=utf8
```

`db_connect = 'mysql+pymysql://[...]'`
(fact_table is just a string with "main_table" inside)

**Comment by zzzeek** [comment]
hi there -

let me illustrate a proper [MCVE](http://stackoverflow.com/help/mcve) for the behavior you describe.   note also that the issue template requests that you tell us what kind of database you're using; "10.5.5" seems to be a version number and does not tell us what database this is.

Below is an illustration of the table given and your test script; it works without error as automap reflects that the "value1" column has a server default on it, so you will note it's not included in the INSERT.   Please run this test case and feel free to modify it, including database in use, to illustrate how you are getting your results.  thanks!

```python
from sqlalchemy import create_engine
from sqlalchemy import table
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session


engine = create_engine("sqlite://", echo=True)

with engine.begin() as conn:
    conn.execute(
        """
        CREATE TABLE fact_table (
                id INTEGER PRIMARY KEY,
                first INTEGER,
                value1 DOUBLE DEFAULT 0,
                value2 DOUBLE
        )
"""
    )


session = Session(engine)
base = automap_base()
base.prepare(engine, reflect=True)
table = getattr(base.classes, "fact_table")
kwargs = {"first": 200016, "value2": 1.0}
entry = table(**kwargs)
session.add(entry)
session.commit()

```


output, after reflection queries are run:

```sql
2020-12-03 08:24:36,341 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-12-03 08:24:36,341 INFO sqlalchemy.engine.base.Engine INSERT INTO fact_table (first, value2) VALUES (?, ?)
2020-12-03 08:24:36,341 INFO sqlalchemy.engine.base.Engine (200016, 1.0)
2020-12-03 08:24:36,342 INFO sqlalchemy.engine.base.Engine COMMIT

```

**Comment by Redysz** [comment]
Hello @zzzeek , thank you for your reply. I added information about difference between our codes. Check it now and tell me if I should provide something more.

**Comment by zzzeek** [comment]
hey there -

just for future reference,  the database you're using is MariaDB as the issue does not exist on MySQL, these are important details that help us to isolate the issue.

**Comment by zzzeek** [comment]
for workaround you will need to provide a partial model with this column present:

```
base = automap_base()

class main_table(base):
    __tablename__ = "main_table"

    id = Column(Integer, primary_key=True)
    value1 = Column(Numeric, server_default="0.000")

base.prepare(engine, reflect=True)
table = main_table
kwargs = {"first": 200016, "value2": 1.0}
entry = table(**kwargs)
session.add(entry)
session.commit()

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Reflect decimal points in MariaDB non-quoted numeric defaults** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2397

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Reflect decimal points in MariaDB non-quoted numeric defaults** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2398
