### ISSUE TITLE
aiomysql support

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5747]
this driver looks to be a shallow port of pymysql so should be much easier to implement than asyncpg was.   will see if a working version is quick.

https://aiomysql.readthedocs.io/en/latest/

references #5743

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**add aiomysql support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2401

**Comment by zzzeek** [comment]
tagging https://github.com/aio-libs/aiomysql/issues/543 which we can sort of work around but I'd like to see if they can fix this.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**add aiomysql support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2408

**Comment by zzzeek** [comment]
still having problems with this

**Comment by alk-sramond** [comment]
Hi, we are looking to make sqlalchemy ORM work with aiomysql, is the issue opened (https://github.com/aio-libs/aiomysql/issues/543) still a valid issue ? (i saw that https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2408 was merged)
If yes, does it mean that using the driver in the current state will be useless (blocking) since `aiomysql.connection.cursor` is not a valid coroutine ?
Also taking the opportunity to thank you for the fantastic job on sqlalchemy :)

**Comment by zzzeek** [comment]
> Hi, we are looking to make sqlalchemy ORM work with aiomysql, is the issue opened ([aio-libs/aiomysql#543](https://github.com/aio-libs/aiomysql/issues/543)) still a valid issue ? 

it is for them, sure

> (i saw that https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2408 was merged)

yes, we are working around their issue by digging into their private attributes.  if their internals should change, that would break us.  However gauging by the project's apparent total non-activity, it seems this is unlikely to happen soon.

> If yes, does it mean that using the driver in the current state will be useless (blocking) since `aiomysql.connection.cursor` is not a valid coroutine ?

no, we've worked around that.   you only need just try out the driver to see if it works for you or not.


> Also taking the opportunity to thank you for the fantastic job on sqlalchemy :)

thanks!
