### ISSUE TITLE
How to use Property with raw query

### ISSUE THREAD

**Issue by hghaffar2** [sqlalchemy/sqlalchemy#5749]
thank you for the beatiful ORM 

i have proble using raw query with model @property 
this property is example run with every request to get the followers of next url view 
but when i run mysql raw query it doesn't work 
```
    @property
    def followers_users_ids(self):
        users_ids = db.session.query(ResFollower.user_id).filter(
            ResFollower.model_id == self.model_id, ResFollower.record_id == self.id).all()
        if users_ids:
            users_ids = list(list(zip(*users_ids))[0])
            users_ids.append(self.create_uid)
        return users_ids
```
 is there anyway to run with my raw query 
this how i run the query ( attachment_tags = db.engine.execute(sql) )

**Comment by CaselIT** [comment]
Hi,

I'm not sure I understand the question correctly. Does the example `followers_users_ids` not work?
Couple you please provide a  [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example?

Thank you

**Comment by CaselIT** [comment]
Reopen if you can provide more informations
