### ISSUE TITLE
Support serializable isolation level for oracle 

### ISSUE THREAD

**Issue by loodaobao** [sqlalchemy/sqlalchemy#5755]
**Is your feature request related to a problem? Please describe.**
Current implementation for the oracle dialect does not support 'serializable' isolation level
**Describe the solution you'd like**
Please support it

**Describe alternatives you've considered**
N.A
**Additional context**
N.A
**Have a nice day!**

Thank you very much.

**Comment by zzzeek** [comment]
i see this is unsupported, there's a technical reason for this however I'd have to re-research it to get the rationale.

**Comment by zzzeek** [comment]
okey doke, you win, the reasons for not doing it given in #5200 were bad.    as I suspected the main issue is being able to read it, so we will just implement the very ugly way to implement "reading" and hope for the best.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement Oracle SERIALIZABLE + real read of isolation level** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2406

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Implement Oracle SERIALIZABLE + real read of isolation level** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2407

**Comment by loodaobao** [comment]
man u're fast

**Comment by loodaobao** [comment]
hi @zzzeek , could u please let me know when 1.3.21 will be released (if this is merged)? i see that 1.3.x is not released at a regular interval so just wonder when i'll be able to use it. thanks a lot for your prompt response and support.

**Comment by zzzeek** [comment]
it could be weeks.  please set the isolation level manually for now, this is only a convenience feature:

```
with engine.begin() as conn:
    conn.execute("set transaction isolation level serializable")
```

**Comment by gordthompson** [comment]
@loodaobao - 1.3.21 has been released

**Comment by loodaobao** [comment]
thank you! ( this fix requires granting permission to select v$transaction but it's fine to me...)

**Comment by zzzeek** [comment]
unfortunately it's not fine to the rest of the world so we will be doing an emergency release to fix this issue.

**Comment by loodaobao** [comment]
appreciate the efforts!
