### ISSUE TITLE
Update CreateEnginePlugin docs about immutable urls

### ISSUE THREAD

**Issue by martinitus** [sqlalchemy/sqlalchemy#5756]
I think the following can be dropped from the documentation - implementing it should have no effect as it should never be called if i understood correctly.

https://github.com/sqlalchemy/sqlalchemy/blob/78d60e108ecd055481b648a05ad96bfcaf84dc70/lib/sqlalchemy/engine/interfaces.py#L977-L980

hth,
Marti

**Comment by zzzeek** [comment]
hey there -

that method is necesary and is documented just a few parargraphs below:   https://github.com/sqlalchemy/sqlalchemy/blob/78d60e108ecd055481b648a05ad96bfcaf84dc70/lib/sqlalchemy/engine/interfaces.py#L1043-L1060

it's called here:

https://github.com/sqlalchemy/sqlalchemy/blob/78d60e108ecd055481b648a05ad96bfcaf84dc70/lib/sqlalchemy/engine/url.py#L633-L637

**Comment by martinitus** [comment]
Uh oh, I thought it got/gets dropped as part of the v1.4/v2.0 migration. If I am mistaken, please just ignore/close :)

**Comment by zzzeek** [comment]
it had to be added for 1.4.   it seems to be just in the 1.4 docs and not anywhere else so if you could double check to make sure I'm not missing anything that would help.
