### ISSUE TITLE
sqlalchemy.types.Enum does not support an Enums with value of None

### ISSUE THREAD

**Issue by foxyblue** [sqlalchemy/sqlalchemy#5758]
**Describe the bug**

When providing an Enum which support `None` as a value, sqlalchemy does not expect this to be a valid case.

**Expected behavior**

Enum's with `None` should be acceptable values for an enum.

```py
from enum import Enum

from sqlalchemy import Column, Integer
from sqlalchemy.ext.declarative import declarative_base

from sqlalchemy import types


Base = declarative_base()


class Rank(Enum):

    First = "first"
    NoRank = None


class Person(Base):

    __tablename__ = "person"
    id = Column(Integer, primary_key=True)
    rank = Column(types.Enum(Rank, values_callable=lambda x: [e.value for e in x]))
```

**Error**

```
Traceback (most recent call last):
  File "alchemy.py", line 18, in <module>
    class Person(Base):
  File "alchemy.py", line 22, in Person
    rank = Column(types.Enum(Rank, values_callable=lambda x: [e.value for e in x]))
  File "<string>", line 2, in __init__
  File "/Users/<user>/Envs/project-7Zy876V8/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 279, in warned
    return fn(*args, **kwargs)
  File "/Users/<user>/Envs/project-7Zy876V8/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1429, in __init__
    self._enum_init(enums, kw)
  File "/Users/<user>/Envs/project-7Zy876V8/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1471, in _enum_init
    length = max(len(x) for x in self.enums)
  File "/Users/<user>/Envs/project-7Zy876V8/lib/python3.8/site-packages/sqlalchemy/sql/sqltypes.py", line 1471, in <genexpr>
    length = max(len(x) for x in self.enums)
TypeError: object of type 'NoneType' has no len()
```

**Versions.**
 - Python: 3.8.6
 - SQLAlchemy: 1.4.0b1
 - Database: Postgres

**Comment by foxyblue** [comment]
I got around this by filtering `None`, although I'm not sure if it's a valid fix.
https://github.com/foxyblue/sqlalchemy/pull/1

**Comment by zzzeek** [comment]
Hey there -

The value of None means that the enumeration would be NULL in the database.   It's not feasible or correct for "None" to be a positive value within the list of values, as it is not a string value and it also would not be distinguishable from a NULL in the database.  NULL is not a value, it's a constant that essentially respresents "unknown".   As you are already using a values_callable, I would suggest having it return a placeholder string such as the word "null" if the given value is "None"; it hopefully should translate back and forth without issue.

The ENUM concept also maps to native enumerated types on MySQL and PostgreSQL. These types also do not have any ability to have NULL be represented as one of the datatypes:

```
# mariadb / mysql
MariaDB [test]> create table foo (data enum('x', 'y', 'z'));
Query OK, 0 rows affected (0.037 sec)

MariaDB [test]> create table bar (data enum('x', NULL, 'z'));
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL, 'z'))' at line 1

# postgresql 
psql (12.4)
Type "help" for help.

test=> CREATE TYPE e1 AS ENUM ('x', 'y', 'z');
CREATE TYPE
test=> CREATE TYPE e2 AS ENUM ('x', NULL, 'z');
ERROR:  syntax error at or near "NULL"
LINE 1: CREATE TYPE e2 AS ENUM ('x', NULL, 'z');

```

**Comment by foxyblue** [comment]
Thanks for your speedy response.

I was using the `None` enumeration to represent the unknown instead of requiring `NOT NULL` and having to include a string/sentinel value like `'unknown'` or `'null'`.

I think the translation using value_callable will be a good alternative solution.

Thanks!

**Comment by foxyblue** [comment]
So the solution was to provide a method for `value_callable` as zzzeek has suggested:

```py
def serialise_enum(x):
    return [e.value if e.value else "none" for e in x]

class Person(Base):

    __tablename__ = "person"
    id = Column(Integer, primary_key=True)
    rank = Column(types.Enum(Rank, values_callable=serialise_enum))
```

And to include this value as an enumeration:

```sql
ALTER TYPE rank ADD VALUE 'none';
```
