### ISSUE TITLE
A safe to use example of prefiltered queries with orm.with_loader_criteria in 1.4

### ISSUE THREAD

**Issue by quantumdark** [sqlalchemy/sqlalchemy#5760]
Hello! 

I'm trying to figure out how to use **with_loader_criteria** to pre-filter all queries of the session automatically. We have a pretty big application that uses sqlalchemy 1.3, and I'm trying to figure out how to migrate to the new version. 

All approaches that I tried so far seemed to have some gotchas or didn't work at all and I was hoping you could show me how it can be used with variables in a safe way.  I'll give a few examples and gotchas that I had with them and I hope they show what I mean.

**Example 1**
This extends the example in /extending_query/filter_public.py
```python
# slightly shortened version of the listener
@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    if not execute_state.is_relationship_load:
        execute_state.statement = execute_state.statement.options(
            orm.with_loader_criteria(
                HasPrivate,
                lambda cls: cls.public == true(),
                include_aliases=True,
            )
        )

#... full example is quite large and located here /examples/extending_query/filter_public.py

   a1 = sess.query(Address).get(1)
    for _ in range(10):
        sess.refresh(a1)
```
We rarely call .refresh directly in the app but it happens a lot implicitly so the query gets bloated every time: by the 10th refresh that's what it looks like:
`SELECT address.public, address.id, address.email, address.user_id
FROM address
WHERE address.id = ? AND address.public = 1 AND address.public = 1 AND address.public = 1 AND address.public = 1 AND address.public = 1 AND address.public = 1 AND address.public = 1 AND address.public = 1 AND address.public = 1 AND address.public = 1 AND address.public = 1`

That's not too much of a problem per se but it becomes one if instead of true() there's a variable, a "bind parameter". Then it causes `sqlalchemy.exc.CompileError`, here's what I tried:
**Example 2**
```python
from sqlalchemy import event
from sqlalchemy import orm
from sqlalchemy.orm import Session


@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    if (
        not execute_state.is_relationship_load
        and not execute_state.execution_options.get("include_private", False)
    ):
        # restrict this session to user 1 so that it's impossible to read other user's data
        user_id = 1
        execute_state.statement = execute_state.statement.options(
            orm.with_loader_criteria(
                Address,
                lambda cls: cls.user_id == user_id,
                include_aliases=True,
            )
        )

if __name__ == "__main__":

    from sqlalchemy import Integer, Column, String, ForeignKey
    from sqlalchemy import create_engine
    from sqlalchemy.orm import relationship, sessionmaker
    from sqlalchemy.ext.declarative import declarative_base

    Base = declarative_base()

    class User(Base):
        __tablename__ = "user"

        id = Column(Integer, primary_key=True)
        name = Column(String)
        addresses = relationship("Address", back_populates="user")

    class Address(Base):
        __tablename__ = "address"

        id = Column(Integer, primary_key=True)
        email = Column(String)
        user_id = Column(Integer, ForeignKey("user.id"))

        user = relationship("User", back_populates="addresses")

    engine = create_engine("sqlite://", echo=True)
    Base.metadata.create_all(engine)

    Session = sessionmaker(bind=engine, future=True)

    sess = Session()

    sess.add_all(
        [
            User(
                name="u1",
                addresses=[
                    Address(email="u1a1"),
                    Address(email="u1a2"),
                ],
            ),
        ]
    )

    sess.commit()

    # this is fine
    a1 = sess.query(Address).get(1)
    
    # this raises an error
    # sqlalchemy.exc.CompileError: Bind parameter '%(4379455728 user_id)s' conflicts with unique bind parameter of the same name
    sess.refresh(a1)
```

Then it becomes even weirder, I thought that because the variable name is a problem I'll use a closure to pass the variable with user_id, and got some completely unexpected results:
**Example 3**

```python
@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    if (
        not execute_state.is_relationship_load
        and not execute_state.execution_options.get("include_private", False)
    ):
        def get_user_id_from_session_and_log():
            print(f"restricting query to user {execute_state.session.user_id}")
            return execute_state.session.user_id

        execute_state.statement = execute_state.statement.options(
            orm.with_loader_criteria(
                Address,
                lambda cls: cls.user_id == get_user_id_from_session_and_log(),
                include_aliases=True,
            )
        )

if __name__ == "__main__":
    # ... same as Example 2

    # sess restricter to user 1
    sess = Session()
    sess.user_id = 1

    sess.add_all(
        [
            User(
                name="u1",
                addresses=[
                    Address(email="u1a1"),
                    Address(email="u1a2"),
                ],
            ),
            User(
                name="u2",
                addresses=[
                    Address(email="u2a1"),
                    Address(email="u2a2"),
                ],
            ),
        ]
    )

    sess.commit()

    # this is fine
    a1 = sess.query(Address).get(1)
    print(a1)

    # this is now fine too
    sess.refresh(a1)

    # sess restricted to user 2
    sess2 = Session()
    sess2.user_id = 2

    # this shouldn't work but works, user_id=1 instead of 2
    a2 = sess2.query(Address).get(1)

```
Turns out that the result of `get_user_id_from_session_and_log` call inside the lambda gets cached by `sqlalchemy.sql.lambdas.PyWrapper` and my guess is it cannot detect the change if there's another closure of a higher order, so it's not updated and keeps the old session object in the execution context. That's a pretty big and surprising gotcha, also a scary one if this is meant to be a security feature.

**Conclusion**
So to summarize, here's my two questions:
 - How to detect that it's a `refresh` or some other implicit execution to prevent applying options multiple times?
 - How to use variables and functions inside the listeners safely? I used simplified toy examples to illustrate my problems but in the real project where I tried to apply this solution I needed to use a function that calls other functions and they bring their own execution context and I had no idea sqlalchemy would sneakily cache the result, we have something like this example from the docstring:
```python
            @event.listens_for("do_orm_execute", session)
            def _add_filtering_criteria(execute_state):
                execute_state.statement = execute_state.statement.options(
                    with_loader_criteria(
                        SecurityRole,
                        lambda cls: cls.role.in_(['some_role']),
                        include_aliases=True
                    )
                )
```
But instead of a lambda with a hardcoded list the list is generated in a complicated way, lets call it `def calculate_security_roles(cls)`, so I discovered what's going on by a lucky chance, just added print() statement inside the `calculate_security_roles` and it magically worked, because by doing so I accidentally created the variable inside the right closure and so the PyWrapper detected the change. That is some real alchemy!

And finally, this approach kinda works, ....(UPD: it also triggers `sqlalchemy.exc.CompileError: Bind parameter .... conflicts`, for some tests, I'll post examples later if I'm able to pinpoint the culprit)
```python
            @event.listens_for("do_orm_execute", session)
            def _add_filtering_criteria(execute_state):
                execute_state.statement = execute_state.statement.options(
                    with_loader_criteria(
                        SecurityRole,
                        lambda cls: cls.role.in_(execute_state.session.user_security_roles),
                        include_aliases=True
                    )
                )
```
... up until some developer working on a project decides to convert `session.user_security_roles`  into a `@property`, querying the user, or just simply mutates the attribute, because the lambda cannot detect the change of `user_security_roles`, it only detects when the session itself changes,I can't say how much of a concern something like that is, but scary stuff anyway, because I can't say I'm confident it won't happen because it's so magicky.

PS: while writing this post and testing examples, at the very end when I experimented with properties on a session I ran into this error:
`sqlalchemy.exc.InvalidRequestError: Can't invoke Python callable user_security_roles() inside of lambda expression argument; lambda cache keys should not call regular functions since the caching system does not track the values of the arguments passed to the functions.  Call the function outside of the lambda and assign to a local variable that is used in the lambda.`
This suggestion to use local variables, so how exactly do I do that, taking into account all the caveats up above? Also this error is only triggered when I tried to call `execute_state.session.user_security_roles()` if the function defined elsewhere the exception is not triggered.

**Versions**
 - Python: 3.7
 - SQLAlchemy: 1.4.0b

**Useful links**
- https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.with_loader_criteria
- https://github.com/sqlalchemy/sqlalchemy/blob/master/examples/extending_query/filter_public.py

**Thank you very much and have a nice day!**

**Comment by zzzeek** [comment]
Hey there, and thanks for testing the beta, not to mention testing out the most deep-alchemy features it has.

The part of the with_loader_criteria docs that use a lambda, which is necessary in order to produce a class-agnostic version of the behavior, are apparently not clear on why a "lambda" is used there - it's so that the SQL expression can be generated on a **per-class basis**.   That is, for a given value of cls, you can count on the lambda being called at most **once**.      The lambda feature is fully described at https://docs.sqlalchemy.org/en/14/core/connections.html#using-lambdas-to-add-significant-speed-gains-to-statement-production and it is not intended for general use.   the docs for with_loader_criteria() are clearly not making it clear that this "lambda" thing is not the same class of problem as the other examples so that has to be fixed.

so one bug report, that would be useful if you can make this separately for me, is to fully define this:

>  I used simplified toy examples to illustrate my problems but in the real project where I tried to apply this solution I needed to use a function that calls other functions and they bring their own execution context and I had no idea sqlalchemy would sneakily cache t

"sneaky" is a bug here.   Nothing should be "sneaky" and it should complain loudly if something uncacheable is detected.  The error "Can't invoke Python callable" you got later on should be generated immediately if the callable does anything that can't be cached.   if there's something we can't detect then we have to add many large conspicuous warnings in the docs.   if your callable was accessing global state in order to determine that something has to change each time, that would be an example of something we probably can't detect but that definitely will not work.

For the thing with session.refresh(), assuming I can easily reproduce that behavior using my own example that's a straight up bug, completely.   will try that now.

**Comment by zzzeek** [comment]
so when I just add a session.refresh(u1) to that script, it simply fails, which makes sense, because a refresh should always be based on primary key only.     so a means of isolating the event handler overall to not occur for "refresh" operations would be best here, what's not clear is if this should be the default behavior.

**Comment by zzzeek** [comment]
see #5761.  I am going to change the API so that you would need to pass flags at the listen() level indicating all kinds of queries you want to intercept, where refresh queries would be one category.

**Comment by zzzeek** [comment]
#5762 is a simple issue and that will fix most of the problems you're having.

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**Revise attribute refresh for with_loader_criteria, related** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2411

**Comment by zzzeek** [comment]
those issues are fixed.   If you can please try out the latest git master and see how it goes we can also close this.  again thanks for beta testing!    very glad this issue was noticed.

**Comment by quantumdark** [comment]
Wow, that was fast! Thank you for being so responsive, I appreciate all the work you do and I'm glad I could help. I will try it out

**Comment by quantumdark** [comment]
@zzzeek I tried the new version, first of all the refresh is no longer causing a problem and that's great, thank you again.

But my second question still remains, I'll try to rephrase that:

 I'd like to use variables (BindParameter) inside of the lambda, is that something that should not be possible at all?

Using the same example, If I change the code just slightly, add ` true_local = True`
```python
@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    true_local = True

    if (
        not execute_state.is_column_load
        and not execute_state.is_relationship_load
        and not execute_state.execution_options.get("include_private", False)
    ):
        execute_state.statement = execute_state.statement.options(
            orm.with_loader_criteria(HasPrivate, lambda cls: cls.public == true_local, include_aliases=True)
        )
```
It causes this error:
`sqlalchemy.exc.ArgumentError: Constant True/False/None expression expected, got BindParameter('%(4537796816 true_local)s', True, type_=Boolean()) object resolved from <sqlalchemy.sql.lambdas.PyWrapper object at 0x10e794a20> object.`

From which I assume that only constant expressions should be allowed, is that true?

But if I change ` true_local = True` → ` true_local = 1` and change the Mixin to Integer instad of Boolean (and also all `True` → `1` and `False` → `0`
```python
class HasPrivate(object):
    """Mixin that identifies a class as having private entities"""

    public = Column(Integer, nullable=False)
```

It breaks, the ArgumentError is no longer detected, and I get the CompileError instead
`sqlalchemy.exc.CompileError: Bind parameter '%(4558166784 true_local)s' conflicts with unique bind parameter of the same name`
That's the same error I see in our application, I'm just trying to use some `security_roles` that are not hardcoded constants as in the examples, but calculated for each session and stored in a variable

**Comment by zzzeek** [comment]
> @zzzeek I tried the new version, first of all the refresh is no longer causing a problem and that's great, thank you again.
> 
> But my second question still remains, I'll try to rephrase that:
> 
> I'd like to use variables (BindParameter) inside of the lambda, is that something that should not be possible at all?

you can put variables in the lambdas, their value is tracked as a function of the locals inside of the Python closure.


> 
> Using the same example, If I change the code just slightly, add ` true_local = True`
> 
> ```python
> @event.listens_for(Session, "do_orm_execute")
> def _add_filtering_criteria(execute_state):
>     true_local = True
> 
>     if (
>         not execute_state.is_column_load
>         and not execute_state.is_relationship_load
>         and not execute_state.execution_options.get("include_private", False)
>     ):
>         execute_state.statement = execute_state.statement.options(
>             orm.with_loader_criteria(HasPrivate, lambda cls: cls.public == true_local, include_aliases=True)
>         )
> ```
> 
> It causes this error:
> `sqlalchemy.exc.ArgumentError: Constant True/False/None expression expected, got BindParameter('%

That is not specifically the lambda doing that, that is something about how it is interpreting the expression up front that is then not compatible with how it is interpreted by the lambda.   if you made the value a non-boolean like "5" then that particular error doesn't occur.     #5763 will repair this.


> It breaks, the ArgumentError is no longer detected, and I get the CompileError instead
> `sqlalchemy.exc.CompileError: Bind parameter '%(4558166784 true_local)s' conflicts with unique bind parameter of the same name`

That is another bug you have discovered (so that's three), on my end I can reproduce this becasue is_relationship_load is not returning True for the "selectinload".  are you using selectinload or subqueryload?  this issue will be fixded by #5764.



> That's the same error I see in our application, I'm just trying to use some `security_roles` that are not hardcoded constants as in the examples, but calculated for each session and stored in a variable,
> 
> ```
>            #from the docstring of LoaderCriteriaOption
>             @event.listens_for("do_orm_execute", session)
>             def _add_filtering_criteria(execute_state):
>                 if (
>                     execute_state.is_select
>                     and not execute_state.is_column_load
>                     and not execute_state.is_relationship_load
>                 ):
>                     execute_state.statement = execute_state.statement.options(
>                         with_loader_criteria(
>                             SecurityRole,
>                             lambda cls: cls.role.in_(['some_role']),
>                             include_aliases=True
>                         )
>                     )
> ```
> 
> here, No matter what I try to pass ['some_role'] from the outside, it breaks. If I define `security_roles = ['some_role']` anywhere, in **global**, on the session, on the query, inside the listener, it breaks.

Can't reproduce that. Below script tries both and appears to succeed, no error and I see the correct values in the query.  Can you alter the MCVE below to illustrate how you are getting "it breaks"?  thanks.
```

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Session
from sqlalchemy.orm import with_loader_criteria

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(data="a"))
s.add(A(data="b"))
s.add(A(data="c"))
s.commit()

global_values = ["a", "b"]

@event.listens_for(s, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    if (
        not execute_state.is_column_load
        and not execute_state.is_relationship_load
    ):

        values = ["a", "b"]
        execute_state.statement = execute_state.statement.options(
            with_loader_criteria(
                A,

                # works for me
                lambda cls: cls.data.in_(values),

                # works for me
#                lambda cls: cls.data.in_(global_values),
                include_aliases=True,
            )
        )


print(s.execute(select(A)).all())

global_values[:] = ["b", "c"]

print(s.execute(select(A)).all())

```

**Comment by zzzeek** [comment]
#5763 and #5764 have a review going through CI.    this should narrow down the number of things you've found going wrong considerably and we can narrow down whatever is left.

**Comment by quantumdark** [comment]
This could be done with just one relation A of course, but then the example is too synthetic. I finally managed to find what was going wrong, here's how I broke it:

```python
from sqlalchemy import Column, ForeignKey
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.orm import declarative_base, relationship
from sqlalchemy.orm import Session
from sqlalchemy.orm import with_loader_criteria

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bbb = relationship("B", back_populates="aaa")


class B(Base):
    __tablename__ = "b"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    a_id = Column(Integer, ForeignKey("a.id"))

    aaa = relationship("A", back_populates="bbb")


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)
s.values = ["a", "b"]

s.add_all(
    [
        A(data="a", bbb=[B(data="a"), B(data="b")]),
        A(data="b", bbb=[B(data="b"), B(data="a")]),
        A(data="c", bbb=[B(data="c"), B(data="a")]),
    ]
)
s.commit()


@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    if not execute_state.is_column_load and not execute_state.is_relationship_load:

        execute_state.statement = execute_state.statement.options(
            with_loader_criteria(
                Base,
                lambda cls: cls.data.in_(execute_state.session.values) if hasattr(cls, "data") else None,
                include_aliases=True,
            )
        )


# all is fine...
a1 = s.execute(select(A).filter(A.id == 1)).scalar()
simple_sub_query = select(B.id).filter(B.a_id == a1.id)

# this breaks
a2 = s.execute(select(A).filter(A.id.in_(simple_sub_query)))
# sqlalchemy.exc.CompileError: Bind parameter '%(4519830920 values)s' conflicts with unique bind parameter of the same name
```

**Comment by zzzeek** [comment]
in that one, something is going wrong with the ternary expression that I'm not sure about .  however, that expression is not what you want anyway since that ternary can't be used in that way, it breaks the rule of "it’s not safe for an individual lambda so modify the SQL structure of the statement across calls:".   It generates a default SQL expression against "Base", which then has to compile in the same way for A and B which is not possible.

Here's how to do it the way that's expected:

```
class HasData:
    data = Column(String)

class A(HasData, Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bbb = relationship("B", back_populates="aaa")


class B(HasData, Base):
    __tablename__ = "b"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    a_id = Column(Integer, ForeignKey("a.id"))

    aaa = relationship("A", back_populates="bbb")

# ...

@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    if not execute_state.is_column_load and not execute_state.is_relationship_load:

        execute_state.statement = execute_state.statement.options(
            with_loader_criteria(
                HasData,
                lambda cls: cls.data.in_(execute_state.session.values),
                include_aliases=True,
            )
        )


```

**Comment by zzzeek** [comment]
So this patch which I might try to get in will raise an informative error for the condition you present:
```

diff --git a/lib/sqlalchemy/sql/lambdas.py b/lib/sqlalchemy/sql/lambdas.py
index 676152781..5f3faab6a 100644
--- a/lib/sqlalchemy/sql/lambdas.py
+++ b/lib/sqlalchemy/sql/lambdas.py
@@ -299,6 +299,8 @@ class DeferredLambdaElement(LambdaElement):
 
         expr = coercions.expect(self.role, expr, **self.coerce_kw)
 
+        self._validate_expr(expr)
+
         if self._resolved_bindparams:
             expr = self._setup_binds_for_tracked_expr(expr)
 
@@ -308,6 +310,17 @@ class DeferredLambdaElement(LambdaElement):
 
         return expr
 
+    def _validate_expr(self, expr):
+        if not self.expr.compare(expr):
+            raise exc.InvalidRequestError(
+                "Lambda element was generated with SQL expression: "
+                "%s but has now produced: %s.  Ensure that there are no "
+                "conditional elements in which may change the SQL structure "
+                "generated for different invocations of the function." % (
+                    self.expr, expr
+                )
+            )
+
     def _copy_internals(
         self, clone=_clone, deferred_copy_internals=None, **kw
     ):

```

error message in this example is:

```

sqlalchemy.exc.InvalidRequestError: Lambda element was generated with SQL expression: NULL but has now produced: a.data IN ([POSTCOMPILE_values_1]).  Ensure that there are no conditional elements in which may change the SQL structure generated for different invocations of the function.
```

the lambda is not able to track the "values" bound parameter because it was not present in the first version of this expression generated, which returned "NULL".

**Comment by zzzeek** [comment]
here's another big problem.   There is a subtlety to the way "values" is passed in which determines whether or not the SQL is cacheable.    this doesnt' break anything but is the difference between your statement being recompiled every time, or not:

```
@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    if (
        not execute_state.is_column_load
        and not execute_state.is_relationship_load
    ):
        values = execute_state.session.values
        execute_state.statement = execute_state.statement.options(
            with_loader_criteria(
                HasData,
                lambda cls: cls.data.in_(values),
                include_aliases=True,
            )
        )

```

vs

```
@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    if (
        not execute_state.is_column_load
        and not execute_state.is_relationship_load
    ):
        execute_state.statement = execute_state.statement.options(
            with_loader_criteria(
                HasData,
                lambda cls: cls.data.in_(execute_state.session.values),
                include_aliases=True,
            )
        )

```

in the latter case, "execute_state" necessarily becomes part of the cache key, and that's bad.   it will fill up the cache with garbage and also might be a variable that's not cacheable.  I think it should raise but this might be difficult to do because there are valid cases for this as well.

**Comment by quantumdark** [comment]
That is super cool, it's awesome, so you're saying I have to be careful and not pass the entire execution_state into the lambda but only the minima necessary objects?

I think the right approach is finally starting to emerge, I'm using multiple `with_loader_criteria` now, and simpler lambdas instead of trying to cram everything in one. 

Will this work also?
```python
class HasUserFK:
    @declared_attr
    def user_id(cls):
        return Column(Integer, ForeignKey("user.id"))

#... 
with_loader_criteria(
                HasUserFK,
                lambda cls: cls.user_id=current_user_id,
                include_aliases=True,
            )
```

**Comment by zzzeek** [comment]
yes the latter approach you have there with HasUserFK is how this was intended to work.   

if you are putting with_loader_criteria in there against a fixed class, then dont even use the lambda!  just use a fixed criteria:

    with_loader_criteria(MyCls, MyCls.user_id==current_id, include_aliases=True)

the lambda part of this is why this is hard.  i wasn't too excited to use the lambda thing for this feature in the first place because it is hard to use, but I couldnt think of another way to do this while still maintaining query caching.  I have some more changes I'm going to do that will get it to warn for more of these cases like the one in #5765 .

**Comment by zzzeek** [comment]
but anyway yes,the lambda thing, it scans all the variables inside of it and either converts them into parameters, or it tracks them on every invocation to see if they change.    im going to make it so that if a variable that isn't a bound parameter changes more than five times, it will emit a warning and then no longer use caching for that query.   good news for lambdas is the warning can display the source file and line number where the problematic lambda is defined :)

**Comment by quantumdark** [comment]
> if you are putting with_loader_criteria in there against a fixed class, then dont even use the lambda!

Well, thank you for this clarification I'll keep in mind this possibility, but no I need a lambda, I understand why it's used now. I tried it without the lambda also at first,
`sqlalchemy.exc.CompileError: Cannot compile Column object until its 'name' is assigned.`

I also tried the opposite, a very complex function (until I realized everything in it is cached and I should better not do that:

```python
def big_fancy_not_so_lambda(cls):
    #... lots of logic
    retrun statement or None
# ....
with_loader_criteria(
                MyClsMixin,
                big_fancy_not_so_lambda,
                include_aliases=True,
            )

```

Also probably not a big deal but this breaks:
```python
class HasData:
    data = Column(String)


class A(Base, HasData):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    bbb = relationship("B", back_populates="aaa")


class BunchOfFieldsMixin(HasData):
    foo = Column(String)
    bar = Column(String)


class B(Base, BunchOfFieldsMixin):
    __tablename__ = "b"

    id = Column(Integer, primary_key=True)
    a_id = Column(Integer, ForeignKey("a.id"))

    aaa = relationship("A", back_populates="bbb")

# ....
            with_loader_criteria(
                HasData,
                lambda cls: cls.data.in_(values),
                include_aliases=True,
            )

```
With the following:
`  File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/src/sqlalchemy/lib/sqlalchemy/inspection.py", line 73, in inspect
    "available for object of type %s" % type_
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'type'>`

This example turned up when I did a refactor to add "`HasData`", turns out there were mixins defining common fields and so I had to go add HasData to the list of mixins directly on the classes derived from Base and removing them from mixins

**Comment by zzzeek** [comment]
> With the following:
> ` File "/Users/quantumdark/PycharmProjects/horizon-server/.venv/src/sqlalchemy/lib/sqlalchemy/inspection.py", line 73, in inspect "available for object of type %s" % type_ sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'type'>`

sigh #5766

**Comment by zzzeek** [comment]
wow it's amazing how many edge cases you came up with above (nine).   The main theme is that, the lambda system is really about providing a Python lambda, and inside of its __closure__ are only SQLAlchemy objects which are then used to create a cache key.  Python literals like strings and ints can be there, but only if they turn out to be things that become bound parameters.    Anything else that happens in these lambdas gives rise to things that the caching system cannot track or has to make guesses how to track, so the new behavior will be all of that will raise very informative messages.

your case three will do this:

```
sqlalchemy.exc.InvalidRequestError: Can't invoke Python callable get_user_id_from_session_and_log() inside of lambda expression argument at <code object <lambda> at 0x7f56be1fb920, file "test3.py", line 19>; lambda SQL constructs should not call regular functions since the caching system cannot track the arguments passed or the return values of functions.  Call the function outside of the lambda and assign to a local variable that is used in the lambda as a closure variable.
```

OK so then suppose you change it to this:

```
        execute_state.statement = execute_state.statement.options(
            orm.with_loader_criteria(
                Address,
                lambda cls: cls.user_id == execute_state.session.user_id,
                include_aliases=True,
            )
        )

```

now you will get:

```
sqlalchemy.exc.InvalidRequestError: Closure variable named 'execute_state' inside of lambda callable <code object <lambda> at 0x7f31e603c3a0, file "test3.py", line 16> does not refer to a cachable SQL element, and also does not appear to be serving as a SQL literal bound value based on the default SQL expression returned by the function.   This variable needs to remain outside the scope of a SQL-generating lambda so that a proper cache key may be generated from the lambda's state.  Evaluate this variable outside of the lambda, or set track_closure_variables=False to exclude closure variables from being part of the cache key.
```

so you can change it either to:

```
        execute_state.statement = execute_state.statement.options(
            orm.with_loader_criteria(
                Address,
                lambda cls: cls.user_id == execute_state.session.user_id,
                include_aliases=True,
                track_closure_variables=False
            )
        )

```

or you can change it to:

```
        user_id = execute_state.session.user_id
        execute_state.statement = execute_state.statement.options(
            orm.with_loader_criteria(
                Address,
                lambda cls: cls.user_id == user_id,
                include_aliases=True
            )
        )

```

there's another version you had that looks like this:
```

        values = execute_state.session.values
        execute_state.statement = execute_state.statement.options(
            with_loader_criteria(
                Base,
                lambda cls: cls.data.in_(values) if hasattr(cls, "data") else None,
                include_aliases=True,
            )
        )


```

that one will also do:

```
sqlalchemy.exc.InvalidRequestError: Closure variable named 'values' inside of lambda callable <code object <lambda> at 0x7f22cd663920, file "test3.py", line 56> does not refer to a cachable SQL element, and also does not appear to be serving as a SQL literal bound value based on the default SQL expression returned by the function.   This variable needs to remain outside the scope of a SQL-generating lambda so that a proper cache key may be generated from the lambda's state.  Evaluate this variable outside of the lambda, or set track_closure_variables=False to exclude closure variables from being part of the cache key.
```

where above, the emphasis is on "does not appear to be serving as a SQL literal bound value based on the default SQL expression returned by the function.  " - the default SQL is the phrase "NULL" which doesn't allow us to set up that bound variable.

if you then said, OK track_closure_variables=False:

```
        values = execute_state.session.values
        execute_state.statement = execute_state.statement.options(
            with_loader_criteria(
                Base,
                lambda cls: cls.data.in_(values) if hasattr(cls, "data") else None,
                include_aliases=True,
                track_closure_variables=False
            )
        )

```

we are *still* checking!  now you get this!

```
sqlalchemy.exc.InvalidRequestError: Lambda callable at <code object <lambda> at 0x7f550155e920, file "test3.py", line 56> produced new bound parameters not accommodated by its initial run: %(140003049784416 values)s
```

these error messages are all trying to guide the user towards the main set of rules that I will have to document more explicitly:

1. build a lambda that has only SQL elements and Python literals for bound values inside of its closure variables.  these all get used to build up a cache key + parameter combination

2. if using a lambda with the "cls" argument for the with_loader_criteria() function, the lambda must produce SQL with the identical bound values on every run

3. if using a lambda in any other way, it has to produce identical SQL for a given set of closure variables each time

Overall, the lambda thing is not really meant for general use, but since this one with_loader_criteria() thing which is likely to be a fairly popular use case unfortunately needs it, hopefully people are less confused though they will still likely find it very strange.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Major revisals to lambdas** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2415

**Comment by jo47011** [comment]
Sorry, I know this issue is fixed and closed.  Nevertheless I do not understand the linked fix in the master branch.  I would need one of the following but none is working (no error but not filtering) either.  Using _SQLAlchemy-1.4.21_:

```python
with_loader_criteria(
                Base,
                lambda cls: cls.data.in_(values) if hasattr(cls, "data") else None,
                include_aliases=True,
)
```

or

```python
with_loader_criteria(
                HasData,
                lambda cls: cls.data.in_(values),
                include_aliases=True,
)
```


Or how is the conclusion from this ticket?  Thanks a lot for enlightening me.

**Comment by zzzeek** [comment]
> Sorry, I know this issue is fixed and closed. Nevertheless I do not understand the linked fix in the master branch. I would need one of the following but none is working (no error but not filtering) either. Using _SQLAlchemy-1.4.21_:
> 
> ```python
> with_loader_criteria(
>                 Base,
>                 lambda cls: cls.data.in_(values) if hasattr(cls, "data") else None,
>                 include_aliases=True,
> )
> ```
> 
> or
> 
> ```python
> with_loader_criteria(
>                 HasData,
>                 lambda cls: cls.data.in_(values),
>                 include_aliases=True,
> )
> ```
> 
> Or how is the conclusion from this ticket? Thanks a lot for enlightening me.

I would suggest running the [example cases](https://docs.sqlalchemy.org/en/14/orm/examples.html#module-examples.extending_query) and experimenting with those - the "filter_public.py" is the simpler excample.  these example cases work fully, so if you can adapt them to what it is you want to do, then you're there.  or if not, you will have a self-contained program you can share in a new [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions) here and we will figure it out.

**Comment by jo47011** [comment]
Thanks @zzzeek for the quick reply.  You're my lifesaver.  Got it working with the full example as stated in you link.
Thanks to all developers, great work 👍
