### ISSUE TITLE
do_orm_execute() needs clear and unambiguous way of isolating ORM refresh / get queries

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5761]
take the example at https://raw.githubusercontent.com/sqlalchemy/sqlalchemy/master/examples/extending_query/filter_public.py and add at the bottom:

```
     sess.refresh(u1)
```

`it fails because the event handler is adding WHERE criteria such that the row can't be located.

additionally the criteria options continue to compound each other when a refresh is used, because we take the existing options in the state and send them through again, strongly suggesting this handler should be excluded from these queries by default:

```
    u2 = sess.execute(select(User).filter(User.name == "u2")).scalar_one()
    sess.refresh(u2)

    sess.refresh(u2)

    sess.refresh(u2)
```

producing:

```
SELECT user.public, user.id, user.name 
FROM user 
WHERE user.id = ? AND user.public = 1 AND user.public = 1 AND user.public = 1

```

at the very least we need an ORMExecuteState flag and I think perhaps we should make this event require flags to indicate what operations are desired, that is:

```
@event.listens_for(Session, "do_orm_execute", normal_selects=True, relationship_loads=False)
def _add_filtering_criteria(execute_state):

```

if no flags are given, an error is raised.   user has to opt in positively to all events.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Revise attribute refresh for with_loader_criteria, related** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2411

**Comment by zzzeek** [comment]
the "flags required" thing would be a lot more effort to change the event handler to work this way, will keep this at "docs" for now.
