### ISSUE TITLE
boolean variables not interpreted by lambdas correctly

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5763]
```
from sqlalchemy import column
from sqlalchemy import select
from sqlalchemy import table

t1 = table("t1", column("q"), column("p"))

def go():
    xy = True
    stmt = select(t1).where(lambda: t1.c.q == xy)
    return stmt

print(go())

```

because the variable is a boolean, the BindParameter we substitute in conflicts with the constant expression created.  so we have to somehow get binary expressions to be adjusted for this case.

`sqlalchemy.exc.ArgumentError: Constant True/False/None expression expected, got BindParameter('%(140231888469968 xy)s', True, type_=Boolean()) object resolved from <sqlalchemy.sql.lambdas.PyWrapper object at 0x7f8a46f31880> object.
`

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Fixes for lambda expressions and relationship loaders** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2413
