### ISSUE TITLE
detect when a lambda condititional is producing different bound parameter sets

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5767]
there are a few failures modes for this one and they are very hard to track down but the general idea is that the original lambda is against the SQL expression NULL, the bound params don't get tracked, and then the working expression fails.   this should be detected in DeferredLambdaElement._resolve_with_args(), either that we illustrate that hey, this SQL specimen doesnt match (comparison is hard though as the SQL would be different per args) or hey, we don't see the same list of bound parameters here as before (we either raise for that, or we figure out some way such that we re-scan for parameters for each set of arguments which seems hard.  this is the whole thing that gives rise to the "you must have a HasData.data mixin" or whatever and maybe we should revise this whole approach such that we evaluate each set of lambda args distinctly and work with each SQL expression independently.  then we don't need to evaluate it up front for "Base" or whatever.

**Comment by zzzeek** [comment]
part of #5760

**Comment by zzzeek** [comment]
reminding myself why we *have* to run the lambda immediately, it's so that we can get the bound parameters from the expression in order to generate a cache key.

that is, 

    stmt = select(A).options(with_loader_criteria(Base, lambda cls: cls.data == 'foo'))

assuming the above is via the ``do_orm_execute()`` hook hence the base class is arbitrary.    We need to make a cache key for ``stmt`` that has scanned for bound parameters, that have to match what is cached.    so if there's a whole step that makes a LambdaElement inside the ORM compile and all that, that doesn't give us a way of knowing the bound parameters.   so the way this is done has to be how it's done for caching to be possible.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Try to make lambda callables more strict** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2415

**Comment by zzzeek** [comment]
I can't make this work reliably.  I will leave some marker code and tests but for now I need to move on.
