### ISSUE TITLE
lambda SQL wants to prevent embedded functions, but this doesn't work and there's no coverage

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5770]
this fails because we don't have any way to know how foo() is used and the bound parameter is not tracked:

```
    def test_detect_embedded_callables_one(self):
        t1 = table("t1", column("q"))

        x = 1

        def go():
            def foo():
                return x

            stmt = select(t1).where(lambda: t1.c.q == foo())
            return stmt

        self.assert_compile(
            go(),
            "SELECT t1.q FROM t1 WHERE t1.q = :q_1",
            checkparams={"q_1": 1},
        )

        x = 2

        self.assert_compile(
            go(),
            "SELECT t1.q FROM t1 WHERE t1.q = :q_1",
            checkparams={"q_1": 2},
        )

```

there's a nice error condition for this in PyWrapper which says "Can't invoke Python callable foo() inside of lambda expression argument; lambda cache keys should not call regular functions since the caching system does not track the values of the arguments passed to the functions.  Call the function outside of the lambda and assign to a local variable that is used in the lambda." but we never get there because _deep_is_literal() considers a Function to be cacheable.   so we can turn that off and prevent yet *another* unexpected thing demonsrated at #5760.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Major revisals to lambdas** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2415
