### ISSUE TITLE
incredibly, we are not nicely checking for secondary=SomeClass in relationship in 2020; support table/cls with same name (!)

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5774]
placing a class as the target of "secondary" should be using coercions / checking in order to get the correct argument and/or raise an informative error message:
```

from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import configure_mappers
from sqlalchemy.orm import relationship
Base = declarative_base()


class C(Base):
    __tablename__ = 'c'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    b_id = Column(ForeignKey("a.id"))

class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", secondary=C)


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)


configure_mappers()
```

fails differently in 1.4 and 1.3 but both with deep stack traces.  1.4 seems to actually be trying to coerce it and amazingly seems to instantiate C (!)   i guess it sees it as a callable.     test for both the string version and the class version.

additionally, we dont support string lookup for table here when table name and class name are the same, so let's try to allow that as well.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Check explicitly for mapped class as secondary** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2417

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Check explicitly for mapped class as secondary** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2418
