### ISSUE TITLE
Columns with Identity should set nullable=False

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#5775]
When trying to reflect a table like `sa.Table("foo", meta, sa.Column("id", sa.Integer(), sa.Identity))` the column 'id' will be reflected as `nullable=False`.

This behavior is consistent in oracle, postgres and mssql, that are currently the all the dialect that support this feature

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**``Identity`` implies ``nullable=False``.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2460
