### ISSUE TITLE
Add TypeVar to sqlalchemy.ext.asyncio.AsyncSession.run_sync signature

### ISSUE THREAD

**Issue by michael0liver** [sqlalchemy/sqlalchemy#5777]
**Is your feature request related to a problem? Please describe.**

At the moment in `sqlalchemy.ext.asyncio.AsyncSession.run_sync` the `fn` argument has a type declaration of `typing.Callable`: 

https://github.com/sqlalchemy/sqlalchemy/blob/09fac89debfbdcccbf2bcc433f7bec7921cf62be/lib/sqlalchemy/ext/asyncio/session.py#L105

This isn't particularly useful if you would like to use a static type checker such as mypy to type check values returning from the function as they will have the type `typing.Any`.

**Describe the solution you'd like**
> Callable[..., ReturnType] (literal ellipsis) can be used to type hint a callable taking any number of arguments and returning ReturnType

We could modify the signature a little to include a `typing.TypeVar`:
```python
    from typing import TypeVar

    T = TypeVar("T")

    async def run_sync(self, fn: Callable[..., T], *arg, **kw) -> T:
```

This gives us all the PEP484 goodies and better autocompletion inside IDE.

**Describe alternatives you've considered**
I have gotten around this by declaring the type when calling the function like this:
```python
result: bool = await session.run_sync(run_queries)
```

**Additional context**
References:
- https://docs.python.org/3/library/typing.html#typing.Callable

**Have a nice day!**

**Comment by zzzeek** [comment]
looks OK to me!   I'm reminded that Callable is not yet flexible enough for us to give the "real" signature which is that the "sync" version of the parent object is passed as the first argument ("Since using callbacks with keyword arguments is not perceived as a common use case, there is currently no support for specifying keyword arguments with Callable. " I have no idea how they came to that conclusion).

**Comment by sqla-tester** [comment]
**Michael Oliver** has proposed a fix for this issue in the **master** branch:

**Improved PEP-484 for AsyncSession.run_sync** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2420

**Comment by michael0liver** [comment]
> looks OK to me! I'm reminded that Callable is not yet flexible enough for us to give the "real" signature which is that the "sync" version of the parent object is passed as the first argument ("Since using callbacks with keyword arguments is not perceived as a common use case, there is currently no support for specifying keyword arguments with Callable. " I have no idea how they came to that conclusion).

After a quick read on https://mypy.readthedocs.io/en/stable/protocols.html#callback-protocols I think can this be achieved properly. This relies on [pep-0544/](https://www.python.org/dev/peps/pep-0544/) which is 3.7+ but backward compatible via the `typing-extensions` nodule.

There is also [pep-0612](https://www.python.org/dev/peps/pep-0612/) which introduces a new `typing.ParamSpec` which might help. That one is 3.10+ but again claims to be backwards compatible.


I will take a look later :)

**Comment by michael0liver** [comment]
I think we need pep-0612 to be implemented then backported via the `typing-extensions` module. At the moment we can do something like: 
```python
    from typing import Protocol


    class SyncSessionFirstArg(Protocol):
        def __call__(self, session: Session):
            ...

    async def run_sync(self, fn: SyncSessionFirstArg, *arg, **kw):
```

That is only useful when your function doesn't have any extra params. I tried the following but it doesn't work:
```python
    class SyncSessionFirstArg(Protocol):
        def __call__(self, session: Session, *args, **kwargs):
            ...

    async def run_sync(self, fn: SyncSessionFirstArg, *arg, **kw):
```
![image](https://user-images.githubusercontent.com/55017335/102459411-78467c00-403d-11eb-96a2-9eb8c652750b.png)

For now we can at least have the correct return type via this PR and then in the future improve it.

**Comment by zzzeek** [comment]
agree not worth trying to hack around what is available right now.
