### ISSUE TITLE
No all users have permission for select v$transaction

### ISSUE THREAD

**Issue by minisotm** [sqlalchemy/sqlalchemy#5783]
**Describe the bug**
By default, users do not have access to v$transaction. On startup all request will be fail.

new in #5755 

**Error**

```
cx_Oracle.DatabaseError: ORA-00942: table or view does not exist
```

**Versions.**
 - SQLAlchemy: 1.3.21
 - Database: Oracle
 - DBAPI: cx-Oracle-7.3.0

**Comment by CaselIT** [comment]
Thanks for reporting this.

Closing as dupliace of #5784
