### ISSUE TITLE
Values do not convert / coerce properly

### ISSUE THREAD

**Issue by atellier** [sqlalchemy/sqlalchemy#5785]
**Describe the bug**
When using `Values`, with a specific `Column`, I would expect the `data` entries to be converted into something acceptable for the provided `Column`, just like we assign a value to a given `Column`. Instead we are getting `NULL`.
This happens with regular / sqlalchemy `Enum` and also with Numpy strings (`str_` types)

**To Reproduce**
Run the code below:

```py
from sqlalchemy import String, values, column
import numpy
import enum
from sqlalchemy import Enum as SQLEnum

# Numpy String Issue
ids = numpy.array(['ab', 'cd'], dtype=str)
print("Numpy - Issue")
print(values(column("value", String), name="ids", literal_binds=True).data([(_id,) for _id in ids]))

# Fixed
print("\nNumpy - Fixed")
print(values(column("value", String), name="ids", literal_binds=True).data([(str(_id),) for _id in ids]))
print(values(column("value", String), name="ids", literal_binds=True).data([(_id,) for _id in ids.astype(object)]))

# Enum Issue
MyEnum = enum.Enum(
    "Test",
    {
      "A": "AA",
      "B": "BB"
    }
)

enums = [MyEnum.A, MyEnum.B]
print("\n\nEnum - Issue")
print(values(column("value", SQLEnum(MyEnum)), name="enums", literal_binds=True).data([(_enum,) for _enum in enums]))

# Fixed
print("\nEnum - Fixed")
print(values(column("value", SQLEnum(MyEnum)), name="enums", literal_binds=True).data([(_enum.name,) for _enum in enums]))
```

**Output:**
```py
Numpy - Issue
VALUES (NULL), (NULL)

Numpy - Fixed
VALUES ('ab'), ('cd')
VALUES ('ab'), ('cd')


Enum - Issue
VALUES (NULL), (NULL)

Enum - Fixed
VALUES ('A'), ('B')
```

**Versions.**
 - OS: OSX
 - Python: 3.8
 - SQLAlchemy: 1.4.01b
 - Database: PostgreSQL
 - DBAPI: psycopg2 

Thanks!

**Comment by zzzeek** [comment]
hey there -

I haven't looked closely, can you take a look at https://docs.sqlalchemy.org/en/13/faq/thirdparty.html and suggest if we need to add more FAQ entries?   we are not able to detect special numpy types, these are failures at the driver level and must be converted by the end-user, or using a custom type subclass that does the conversion you need.

**Comment by zzzeek** [comment]
this appears specific to literal_binds detection in 1.4 so will take a look

**Comment by atellier** [comment]
Hey - thanks for responding!

What about SQLAlchemy Enums - they seem to be returning NULLs as well, instead of being converted to str or cast to the corresponding database type (for those database that support this type)?

**Comment by atellier** [comment]
For Numpy I ended up converting my array elements to `object` via `.astype(object)` and it worked. Thanks

**Comment by zzzeek** [comment]
there appear to be two separate issues here, which makes this hard to track.  for the numpy thing, SQLAlhcemy would need to do a more comphrensive lookup on string types which is not really feasible, a hack looks like this:

```
diff --git a/lib/sqlalchemy/sql/sqltypes.py b/lib/sqlalchemy/sql/sqltypes.py
index 581573d17..d1367c574 100644
--- a/lib/sqlalchemy/sql/sqltypes.py
+++ b/lib/sqlalchemy/sql/sqltypes.py
@@ -3131,6 +3131,10 @@ else:
     _type_map[unicode] = Unicode()  # noqa
     _type_map[str] = String()
 
+
+import numpy
+_type_map[numpy.str_] = String()
+
 _type_map_get = _type_map.get

```

**Comment by zzzeek** [comment]
there's also kind of an unappealing behavior here of the literal thing spitting out NULL which is not really appopriate

**Comment by zzzeek** [comment]
OK all of these can be fixed because we should be inferring the type from the Values clause.   so we're good, these are all the same issue in fact.   nice job

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Improve type detection for Values / Tuple** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2424
