### ISSUE TITLE
doc building cron doesn't delete stale files

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5789]
**To Reproduce**

Navigate to

https://docs.sqlalchemy.org/en/docs_preview/queryguide.html

then click the "SQLAlchemy 1.4 / 2.0 Tutorial" link near the top of the sidebar on the left. That tries to load

https://docs.sqlalchemy.org/en/docs_preview/tutorial.html

but results in a "Page Not Found!". The actual address is

https://docs.sqlalchemy.org/en/docs_preview/tutorial/index.html

**Comment by zzzeek** [comment]
so these are the "docs_preview" which are no longer current.  the page that you're showing is a stale HTML file, as the "querying guide" was replaced with one that is ORM specific:  https://docs.sqlalchemy.org/en/docs_preview/orm/queryguide.html

but in any case docs_preview should be considered retired for now the 1.4 docs are at: https://docs.sqlalchemy.org/en/14/orm/queryguide.html

What we *can* observe here is that my doc building thing on the site does not delete stale files.    im never enthusiastic about writing code that rm's things :)

**Comment by jvanasco** [comment]
The string `docs_preview` does not exist in either:

* https://github.com/sqlalchemy/sqlalchemy
* https://github.com/sqlalchemyorg/sqlalchemyorg

I would just manually delete the directory, and do a `.htaccess` to redirect everything in docs_preview to the current docs
