### ISSUE TITLE
async with sessionmaker.begin()

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#5796]
One thing that seems to be missing from the asyncio API is support for an async sessionmaker.begin() method.

This would allow a simple context manager for new transactions like:

```
Session = sessionmaker(some_engine, class_=AsyncSession)

async with Session.begin() as session:
    session.add(some_object)
```

Currently, this fails with:
`AttributeError: __aexit__`

Using 1.4.0b1

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**implement sessionmaker.begin(), scalar() for async session** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2436
