### ISSUE TITLE
Missing AsyncSession.scalar()

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#5797]
It seems that `AsyncSession` does not have the `scalar()` method, which is present on `Session`.

Not sure if this is deliberate, or if it just got missed.

If deliberate, it should probably be mentioned in the docs as to why it's not there.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**implement sessionmaker.begin(), scalar() for async session** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2436

**Comment by zzzeek** [comment]
if folks can take a look at the above review to make sure i did it right, there's no asynccontextmanager in Python 3.6 so had to make one directly.
