### ISSUE TITLE
Self-referencing relationship primaryjoin condition to predefined object/list of objects

### ISSUE THREAD

**Issue by radzak** [sqlalchemy/sqlalchemy#5801]
How can I configure a relationship to a hardcoded object or a list of objects? I tried different variants of the following with no success. I went through the examples in the docs, but still struggling to make it work 😞 I found https://docs.sqlalchemy.org/en/14/core/functions.html#sqlalchemy.sql.functions.FunctionElement.as_comparison but not sure if that is even relevant to this scenario.

```python
class Object(Base):
    id = Column(UUID(as_uuid=True), primary_key=True)
    important_objects = relationship(
        "Object",
        primaryjoin=foreign(id) == "0873bcdd-321d-433d-bd74-93db30b44f49",
        viewonly=True
    )
```

> Relationship Object.important_objects could not determine any unambiguous local/remote column pairs based on join condition and remote_side arguments.  Consider using the remote() annotation to accurately mark those elements of the join condition that are on the remote side of the relationship.

I would love to know how I can achieve something like this and if I can combine it with `in_()`, etc.

**Comment by zzzeek** [comment]
I doubt you would use relationship for this, more likely plain Python `@property` as documented at https://docs.sqlalchemy.org/en/13/orm/join_conditions.html#building-query-enabled-properties , or if you are looking for some kind of query-level access, a hybrid property.

can you give an example of what usage with "in_()" looks like?   Relationships don't support in_().

**Comment by radzak** [comment]
Thanks a lot for a quick reply. Makes sense, I wasn't sure if `relationship` is suitable for this, so I guess your suggestion with a plain `@property` should suffice :)

With `in_()` I meant the same thing, just filtering by multiple IDs instead of one, but again, a `@property` would work too for this use case. 👍
