### ISSUE TITLE
CAST to FLOAT is incorrectly omitted for MariaDB v10.5.8

### ISSUE THREAD

**Issue by mkapi** [sqlalchemy/sqlalchemy#5808]
I have encountered the following warning while using `func.cast(int_column, FLOAT)`.
```
SAWarning: Datatype FLOAT does not support CAST on MySQL; the CAST will be skipped."
```

MariaDB started supporting CAST to FLOAT after [v10.4.5](https://mariadb.com/kb/en/mariadb-1045-release-notes/)
and MySQL after [v8.0.17](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-17.html#mysqld-8-0-17-feature)

I think we should update the mysql dialect to match the behaviour.

**Versions.**
 - OS: CentOS 8
 - Python: 3.7.5
 - SQLAlchemy: 1.3.12
 - Database: MariaDB 10.5.8
 - DBAPI: pymysql

**Have a nice day!**

**Comment by zzzeek** [comment]
here's a patch that I would favor going directly as is (with tests) in 1.4, however for a 1.3 backport, we should add version detection to guarantee backwards compatibility (which would also be in the 1.4 version).  that is, this is just the start of the patch we should have.
```

diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index 7a4d3261f..cf7781c53 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -1624,6 +1624,8 @@ class MySQLCompiler(compiler.SQLCompiler):
             return self.dialect.type_compiler.process(type_).replace(
                 "NUMERIC", "DECIMAL"
             )
+        elif isinstance(type_, sqltypes.FLOAT):
+            return self.dialect.type_compiler.process(type_)
         else:
             return None
 

```

**Comment by CaselIT** [comment]
I'll try looking into this

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Support casting to ``FLOAT`` in MySQL and MariaDb.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2442

**Comment by CaselIT** [comment]
@mkapi thanks for providing the versions of mysql and mariadb that introduced support

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Support casting to ``FLOAT`` in MySQL and MariaDb.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2443

**Comment by mkapi** [comment]
thanks @CaselIT
