### ISSUE TITLE
Creating a materialized view with indexes

### ISSUE THREAD

**Issue by qwAAQ** [sqlalchemy/sqlalchemy#5814]
**How do you create a materialized view in sqlalchemy with indexes**

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

SQLAlchemy currently does not support views directly.
There is a wiki recipes that I think could be adapted to support indexes: https://github.com/sqlalchemy/sqlalchemy/wiki/Views

There is also the package https://github.com/jklukas/sqlalchemy-views that supports views, but I haven't personally used it, so I don't know it if does support indexes

**Comment by jvanasco** [comment]
In addition to what @CaselIT said:

If you do not need to create/drop the view *in the database* and you just want to utilize an existing view for reading operations, you can simply use a Table construct (ORM and Core) which uses the view's name as the table name. This is a very popular approach with SqlAlchemy users.

Views are essentially special tables; SqlAlchemy does not natively support creating/dropping views, various refresh operations, or the readonly characteristics -- but you can just define a view as you would a table and accomplish 99% of what you need.

**Comment by qwAAQ** [comment]
> Hi,
> 
> SQLAlchemy currently does not support views directly.
> There is a wiki recipes that I think could be adapted to support indexes: https://github.com/sqlalchemy/sqlalchemy/wiki/Views
> 
> There is also the package https://github.com/jklukas/sqlalchemy-views that supports views, but I haven't personally used it, so I don't know it if does support indexes

Thanks will check this. I have also found this https://pypi.org/project/sqlalchemy-plus/ which I will check out as well.

> In addition to what @CaselIT said:
> 
> If you do not need to create/drop the view _in the database_ and you just want to utilize an existing view for reading operations, you can simply use a Table construct (ORM and Core) which uses the existing database view's name as the SQLAlchemy `__tablename__` (or ORM equivalent). This is a very popular approach with SQLAlchemy users.
> 
> Views are essentially special tables; SQLAlchemy does not natively support creating/dropping views, various refresh operations, or the readonly characteristics -- but you can just define a view as you would a table and accomplish 99% of what you need.

I realized this and did it, thanks for the tip though. The only thing to remember is to use a new Base for that ORM otherwise Sqlalchemy will attempt to create the table if it doesn't exist when Base.create_all() is called.
