### ISSUE TITLE
TypeDecorator.with_variant ignored in type compilation

### ISSUE THREAD

**Issue by ziima** [sqlalchemy/sqlalchemy#5816]
**Describe the bug**
I found out, that `with_variant` has no effect on type compilation, for example in `CREATE TABLE` SQLs.

I discovered bug using `ScalarListType` from sqlalchemy-utils, see https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/types/scalar_list.py, but doesn't seem to be caused by that particular implementation.

**Expected behavior**
Variant type should be used for defined dialect.

**To Reproduce**
```py
from sqlalchemy import ARRAY, Column, Integer, MetaData, Table, UnicodeText, types
from sqlalchemy.dialects import postgresql, sqlite
from sqlalchemy.schema import CreateTable
# from sqlalchemy_utils import ScalarListType


class ScalarListType(types.TypeDecorator):
    impl = UnicodeText()


# If the TypeDecorator is a variant, everything works.
array = ARRAY(Integer)
array = array.with_variant(ScalarListType(int), 'sqlite')

table = Table('table', MetaData(), Column('attach', array))

statement = CreateTable(table)

print("ARRAY in SQLite:")
print(statement.compile(dialect=sqlite.dialect()))
print("ARRAY in PostgreSQL:")
print(statement.compile(dialect=postgresql.dialect()))


# When definition is the other way around, it doesn't.
array_rev = ScalarListType(int)
array_rev = array_rev.with_variant(ARRAY(Integer), 'postgresql')

table_rev = Table('table', MetaData(), Column('attach', array_rev))

statement_rev = CreateTable(table_rev)

print("ScalarListType in SQLite:")
print(statement_rev.compile(dialect=sqlite.dialect()))
print("ScalarListType in PostgreSQL:")
print(statement_rev.compile(dialect=postgresql.dialect()))
```

**Output**

```
ARRAY in SQLite:

CREATE TABLE "table" (
	"attach" TEXT
)


ARRAY in PostgreSQL:

CREATE TABLE "table" (
	attach INTEGER[]
)


ScalarListType in SQLite:

CREATE TABLE "table" (
	"attach" TEXT
)


ScalarListType in PostgreSQL:

CREATE TABLE "table" (
	attach TEXT
)
```
In the second case, the `ARRAY` variant for PostgreSQL is ignored and main type `TEXT` is used instead.

**Versions.**
 - OS: Linux queeg-500 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux
 - Python: Python 3.9.1
 - SQLAlchemy: 1.3.20, 1.3.22, 1.4.0b1
 - Database: SQLite & PostgreSQL

**Additional context**

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove special rule for TypeDecorator of TypeDecorator** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2451

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Remove special rule for TypeDecorator of TypeDecorator** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2452

**Comment by zzzeek** [comment]
looking for a rationale, the offending line can be traced back to 2007 in c9b3f0bcef , the code is too different back then to have much relevance today so we will assume we aren't missing any test cases for why that line was there.
