### ISSUE TITLE
How to add extra info to Column?

### ISSUE THREAD

**Issue by Chise1** [sqlalchemy/sqlalchemy#5818]
**Describe your question**
I'm writing a project,and I need add extra info in Column,like this:
`Base = declarative_base()
class ControlSer(BaseModel):
    label:str
    name:str
    type:str

class User(Base):
    __tablename__ = "user"
    id = Column(Integer, primary_key=True,serializer=ControlSer(label='id',name='用户ID',type='number'))
`
How can I do it?Which attr can achieve it?

**Comment by zzzeek** [comment]
"info" is exactly that!   use the .info parameter:

https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=column%20info#sqlalchemy.schema.Column.params.info

Column(..., info={"type": "number"})

accessible via the .info attribute: https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=column%20info#sqlalchemy.schema.Column.info

**Comment by Chise1** [comment]
That's great!Thank you.
