### ISSUE TITLE
How to use it in fastapi?

### ISSUE THREAD

**Issue by Chise1** [sqlalchemy/sqlalchemy#5819]
How to open connect befare server start and close befare server stop?
Can I use it like this?

`

app = FastAPI()
print(settings.DATABASE_URL)
engine = create_async_engine(
    settings.DATABASE_URL, echo=True, future=True
)
session = AsyncSession(engine, future=True)

@app.on_event("startup")
async def startup():
    await session.begin()

@app.on_event("shutdown")
async def shutdown():
    await session.close_all()

`

**Comment by PhillCli** [comment]
you can define dependency that provides the session and use it within the handlers.

```Python
async def get_db_session() -> AsyncSession:
    async with SessionLocal() as session:
        yield session

@app.route("/")
async def sample_handler(
    db_session: AsyncSession = Depends(get_db_session),
):
    pass
````

**Comment by Chise1** [comment]
Thank you!

**Comment by Chise1** [comment]
Where is SessionLocal ? 
I can't found it in document or package.

**Comment by Chise1** [comment]
Please give me a complete example.

**Comment by jvanasco** [comment]
@Chise1 This is really a question and request for the FastAPI project, not SQLAlchemy. I recommend you ask the question in one of their groups, and update this Issue with the solution for the benefit of others.
