### ISSUE TITLE
Question about unable to add data in mysql table

### ISSUE THREAD

**Issue by zhangze1243** [sqlalchemy/sqlalchemy#5820]
![image](https://user-images.githubusercontent.com/12403096/103897854-0e4a5f80-512f-11eb-80b5-8783cb946b49.png)
![image](https://user-images.githubusercontent.com/12403096/103897876-15716d80-512f-11eb-8c6e-76025e8ef834.png)

As shown in the picture above,an error will be reported after use 'db.commit()'

**Comment by zzzeek** [comment]
hi there -

unfortunately this cannot be answered with more detail - sqlalchemy version, reproducing code.  it looks like you are creating your Session object improperly and/or you have a broken SQLAlchemy installation.   "_contextual_connect()" was removed in 1.4.
