### ISSUE TITLE
pymysql 1.0.0 came out with major compatibility changes, warnings

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5821]
1. Python 2 support dropped 

2. deprecation warning message emitting for "db" and "passwd" parameters.   I've added https://github.com/PyMySQL/PyMySQL/issues/939

3. it looks like "database" and "password" have been around for many years, so it is safe to switch to these.

**Comment by zzzeek** [comment]
also:

"ModuleNotFoundError: No module named 'pymysql.util'"

this looks like another release today issue

**Comment by zzzeek** [comment]
OK the pymysql.util issue is in aiomysql:

```
e "/home/jenkins/workspace/sqlalchemy_gerrit/455cec4c/.tox/py38-cext-mysql/lib/python3.8/site-packages/aiomysql/connection.py", line 19, in <module>
23:30:12 INTERNALERROR>     from pymysql.util import byte2int, int2byte
23:30:12 INTERNALERROR> ModuleNotFoundError: No module named 'pymysql.util'
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Update connect args for pymysql 1.0.0; aiomysql fixes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2458

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Update connect args for pymysql 1.0.0; aiomysql fixes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2459
