### ISSUE TITLE
we're doing pytest fixtures totally wrong w/ setup/teardown

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5826]
I'd like to remove most of the defensive reconnecion logic in engines.py.   however this requires that the tablestest suites and others be altered, likely to use fixtures fully instead of setup/teardown.   simply put the "connection" fixture has a transaction open, tables test goes to drop the tables and they are locked.   this is why engines.py -> _after_test_ctx() and _stop_text_ctx_aggressive(), which wastefully close out all connections every time, are needed.  this is all hacky and should be fixed in both 1.4 and 1.3, pinning to 1.4 however to raise priority.

**Comment by zzzeek** [comment]
it's likely not worth fixing in 1.3. the use of the "connection" fixture is not prevalent in 1.3 so we should likely try to keep this fairly major change in current master /1.4.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**replace xdist test methods w/ pytest fixture enabled methods** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2464

**Comment by zzzeek** [comment]
OK unfortunately we have to hack something together here.  While I have a great totally pytest fixture approach working, it fails on Python 2 because on Python 2 with older pytest the builds time out, due to performance/memory bloat that seems to occur if *any* autouse fixtures are present.

since the autouse fixtures are local to the fixtures.py, I'm going to hack it using pytest global class/test hooks instead using a simpler resolution scheme for now.
