### ISSUE TITLE
Add mssql+turbodbc to external dialect list

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5834]
I have just learned that there is an external dialect for `mssql+turbodbc`

https://pypi.org/project/sqlalchemy-turbodbc/

Adding it to the list of external dialects is dead simple, but that would make it the second external dialect for mssql (along with sqlalchemy-tds) so it might be nice to add a note to the main mssql dialect page

https://docs.sqlalchemy.org/en/14/dialects/mssql.html

so people don't jump to the conclusion that the DBAPI options listed there (pyodbc, *et al.*) are the only ones available.

Looking at 

https://github.com/sqlalchemy/sqlalchemy/blob/master/doc/build/dialects/mssql.rst

it is not obvious where the (internal) DBAPI list comes from. I suspect some sort of sorcery. :)

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add mssql+turbodbc to external dialect list** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2465

**Comment by CaselIT** [comment]
I think this can be a 1.3.x

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_3** branch:

**Add mssql+turbodbc to external dialect list** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2471
