### ISSUE TITLE
label column with percent sign and compiling returns double signs

### ISSUE THREAD

**Issue by zyp-rgb** [sqlalchemy/sqlalchemy#5835]
**Describe the bug**
Label a column with percent sign and compiling it to literal sql string.
The label would become double percent signs.

**Expected behavior**
Compiling would return single percent sign

**To Reproduce**
sql = select([table.c.id.label('%me')]).limit(5)
print(str(sql.compile(dbe, compile_kwargs={'literal_binds': True})

**Comment by CaselIT** [comment]
Hi,

This is the normal escaping used in the default string dialect. Does it cause an issue with an actual database-dbapi combination?

**Comment by zzzeek** [comment]
hey there.

I've added an FAQ entry to cover this, see https://docs.sqlalchemy.org/en/13/faq/sqlexpressions.html#why-are-percent-signs-being-doubled-up-when-stringifying-sql-statements .

no bug is here so closing.
