### ISSUE TITLE
Updated suite tests missing some requirements

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#5841]
Recent updates to the test suite are causing some unexpected failures for third-party dialects due to missing requirements.

A few selected examples:

lib/sqlalchemy/testing/suite/test_reflection.py

`test_get_table_names()` needs `@testing.requires.foreign_key_constraint_reflection`
`test_get_view_definition()` needs `@testing.requires.view_reflection`

**Comment by gordthompson** [comment]
@zzzeek - I found this when testing against sqlalchemy-access. I'll check sqlalchemy-sybase as well.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add missing requirements to suite tests** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2478
