### ISSUE TITLE
connection pool can lose connections under pypy

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5842]
this is a long standing issue for pypy that we've actually had for at least ten years and suddenly it's apparent what the problem is.  pypy does not call weakref finalizers if the thing pointing to the weakref is also being GCed.  that's it!  here's a demo, works in cpython, fails in pypy with pool timeout:

```python
from sqlalchemy import create_engine


e = create_engine(
    "postgresql+pg8000://scott:tiger@localhost/test",
    pool_size=2,
    max_overflow=0,
    pool_timeout=2,
)

c1 = e.connect()
c2 = e.connect()

del c1
del c2

import gc
gc.collect()


e.connect()

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Create explicit GC ordering between ConnectionFairy/ConnectionRecord** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2476
