### ISSUE TITLE
Nested subqueries with aliased queries/tables

### ISSUE THREAD

**Issue by mahenzon** [sqlalchemy/sqlalchemy#5843]
**Describe your question**
I'm trying to do multi-level nested query, but have some troubles
I need to unnest several arrays in json fields and select some of them

**Example**

- table is `check`, it has `id` (int) and `response` (json) fields
- json example (contents of `response` column):
```json
{
  "Results": [
    {
      "Name": "FooBar",
      "Field": "SomeValue"
    },
    {
      "Name": "SpamEggs",
      "Field": "AnotherValue"
    }
  ]
}
```

Here's simplified  SQL example which I'm trying to achieve:
 
```SQL
SELECT result_elem -> 'Field' as field
FROM "check" AS check_, json_array_elements(
    (
      SELECT check_inside.response -> 'Results'
      FROM "check" as check_inside
      WHERE check_inside.id = check_.id
    )
) AS result_elem
WHERE result_elem ->> 'Name' = 'FooBar';
```

at first I'm trying to implement inner subquery

python code:

```python
from sqlalchemy import func
from sqlalchemy.orm import aliased
from sqlalchemy.dialects import postgresql

check_inside = aliased(Check, name="check_inside")
check_ = aliased(Check, name="check_")

q_result_elems = session.query(
    check_inside.response["Results"],
).filter(
    check_inside.id == check_.id,
)
subq_result_elems = q_result_elems.subquery(name="subq_result_elems")

print(str(q_result_elems.statement.compile(compile_kwargs={"literal_binds": True}, dialect=postgresql.dialect())))
```

prints this: 

```SQL
SELECT check_inside.response -> 'Results' AS anon_1 
FROM "check" AS check_inside, "check" AS check_ 
WHERE check_inside.id = check_.id
```

it already differs on the `FROM` line
then I'm completely lost. this is kinda pseudo-code, which doesn't work at all:

```python
q_foobar_fields = session.query(
    subq_result_elems.op("->")("Field").label("field"),
).select_from(
    check_,
    func.json_array_elements(
        subq_result_elems,
    ).label("result_elem")
).filter(
    subq_result_elems.op("->>")("Name") == "FooBar"
)
```

I tried a bit another way:

```python
# added a label 'results' above and then creating a new query
q_foobar_fields = session.query(
    func.json_array_elements(subq_result_elems.c.results.op("->")("Field"))
).filter(
    subq_result_elems.c.results.op("->>")("Name") == "FooBar",
)

print(str(q_foobar_fields.statement.compile(compile_kwargs={"literal_binds": True}, dialect=postgresql.dialect())))
```

but it creates this SQL:

```SQL
SELECT json_array_elements(subq_result_elems.results -> 'Field') AS json_array_elements_1
FROM (SELECT check_inside.response -> 'Results' AS results
      FROM "check" AS check_inside,
           "check" AS check_
      WHERE check_inside.id = check_.id) AS subq_result_elems
WHERE (subq_result_elems.results ->> 'Name') = 'FooBar';
```

and here 'FROM' is different from what I need (and it creates multiple rows for each `check` item)

How can I pass an aliased subquery and refer it in the 'select' part?

Thanks in advance!

**Versions**
 - SQLAlchemy: 1.3.18
 - Database: Postgres

**Have a nice day!**

**Comment by zzzeek** [comment]
the main thing you're doing that's not directly supported is a function with a query inside of it, which then goes into the FROM clause, which is very much a postgresql thing.  you can probably find a recipe that can help if you take a look at #3566 which has a whole set of POCs for how to get these unusual PG syntaxes to work.  This is stuff that we'd like to add as a feature but it never has gotten priority.  

take a look through those and if you can't get it working, I will add your example above to the list on that issue.  basically when the feature gets added, all those comments will serve as test cases.

**Comment by zzzeek** [comment]
just a note Im going to try to do #3566 for 1.4, so will add your query above to the test cases.

**Comment by zzzeek** [comment]
I think in your example the main thing is to make use of the JSON operators, also this is more straightforward using select() since you are selecting columns anyway, in 1.4 select() is fully ORM capable in any case:

```python
"""
SELECT result_elem -> 'Field' as field
FROM "check" AS check_, json_array_elements(
    (
      SELECT check_inside.response -> 'Results'
      FROM "check" as check_inside
      WHERE check_inside.id = check_.id
    )
) AS result_elem
WHERE result_elem ->> 'Name' = 'FooBar';
"""


from sqlalchemy import column
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import JSON
from sqlalchemy import literal_column
from sqlalchemy import select
from sqlalchemy import table
from sqlalchemy.dialects import postgresql

check = table("check", column("id", Integer), column("response", JSON))

check_inside = check.alias("check_inside")

check_ = check.alias("check_")

result_elem = func.json_array_elements(
    select([check_inside.c.response["Results"]]).where(
        check_inside.c.id == check_.c.id
    ).as_scalar()
).alias("result_elem")


result_elem_col = literal_column("result_elem", type_=postgresql.JSON)
stmt = (
    select([result_elem_col["Field"].label("field")])
    .select_from(
        check.alias("check_"),
    )
    .select_from(result_elem)
    .where(result_elem_col["Name"].astext == "FooBar")
)


print(stmt.compile(dialect=postgresql.dialect()))

```

**Comment by zzzeek** [comment]
also there's an alias() method on functions.   I might not have mentioned that much in #3566 because it does not give the columns that one wants in the columns clause, that's essentially most of what has to happen for that issue.  so in the example above I just manufactured a column using ``literal_column()``.

**Comment by mahenzon** [comment]
thank you very much for your help! this is a lot closer but still is invalid. yeah, I have never used `literal_column` indeed

I tried to fix it, made a small tweak, here's full example:

```python
from sqlalchemy import column
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import JSON
from sqlalchemy import literal_column
from sqlalchemy import select
from sqlalchemy import table
from sqlalchemy.dialects import postgresql

check = table("check", column("id", Integer), column("response", JSON))

check_inside = check.alias("check_inside")

check_ = check.alias("check_")

result_elem = func.json_array_elements(
    select(
        [check_inside.c.response["Results"]]
    ).select_from(
        # !!! Added this `select_from`
        check_inside,
    ).where(
        check_inside.c.id == check_.c.id,
    ).as_scalar()
).alias("result_elem")

result_elem_col = literal_column("result_elem", type_=postgresql.JSON)
stmt = (
    select([result_elem_col["Field"].label("field")])
    .select_from(
        check.alias("check_"),
    )
    .select_from(result_elem)
    .where(result_elem_col["Name"].astext == "FooBar")
)

print(stmt.compile(compile_kwargs={"literal_binds": True}, dialect=postgresql.dialect()))
```

result:
```SQL
SELECT result_elem -> 'Field' AS field
FROM "check" AS check_, json_array_elements(
    (
        SELECT check_inside.response -> 'Results' AS anon_1
        FROM "check" AS check_inside,
             "check" AS check_
        WHERE check_inside.id = check_.id
    )
) AS result_elem
WHERE (result_elem ->> 'Name') = 'FooBar';
```

and trying to run results in this error:
`ERROR: more than one row returned by a subquery used as an expression`

it's because resulting subquery contains two `FROM` elements instead of one: 
```SQL
FROM "check" AS check_inside,
     "check" AS check_
```

but expected is `FROM "check" AS check_inside`. 
I tried to fix it this way: `.select_from(check_inside)` (in the example above), but it still results in adding two 'from' tables. I think it's because of `.where(check_inside.c.id == check_.c.id)` - two tables are used in the `where` clause

but the thing is that `check_` is imported above, take a look at the expected again (only removing `,"check" AS check_` from the result's inner subquery):
```SQL
SELECT result_elem -> 'Field' AS field
FROM "check" AS check_, json_array_elements(
    (
        SELECT check_inside.response -> 'Results' AS anon_1
        FROM "check" AS check_inside
        WHERE check_inside.id = check_.id
    )
) AS result_elem
WHERE (result_elem ->> 'Name') = 'FooBar';
```

the idea of the subquery is to return only one row with array. this row is filtered by id from the query above. query from check_ filters inner subquery by its id

is there a way to exclude that extra item in `from` clause? then this will be solved!

**Comment by zzzeek** [comment]
this is sadly another not-implemented aspect so you'd have to wait for #3566 or use the workarounds.   this is correlation from the FROM clause which is supposed to happen if we use the LATERAL construct, however it seems to not be working for this case.  will add it to the test cases.

**Comment by zzzeek** [comment]
whoops, found it, forgot to use check_ correctly:

```
result_elem = func.json_array_elements(
    select([check_inside.c.response["Results"]]).where(
        check_inside.c.id == check_.c.id
    ).as_scalar()
).alias("result_elem")


result_elem_col = literal_column("result_elem", type_=postgresql.JSON)
stmt = (
    select([result_elem_col["Field"].label("field")])
    .select_from(
        check_
    )
    .select_from(result_elem)
    .where(result_elem_col["Name"].astext == "FooBar")
)



```

the output SQL is:

```
SELECT result_elem -> %(result_elem_1)s AS field 
FROM "check" AS check_, json_array_elements((SELECT check_inside.response -> %(response_1)s AS anon_1 
FROM "check" AS check_inside 
WHERE check_inside.id = check_.id)) AS result_elem 
WHERE (result_elem ->> %(result_elem_2)s) = %(param_1)s

```

**Comment by mahenzon** [comment]
oh, that's great! yeah, now it's correct
thank you very much!
