### ISSUE TITLE
wrong query name returned

### ISSUE THREAD

**Issue by comtihon** [sqlalchemy/sqlalchemy#5844]
My library dynamically resolves column names from queries.
However, one column name from the query is resolved incorrectly.
```
select smava_id as "smavaId",
       alt.lead_validity_expiration as "Current_MA_First_LA_CAM_lead_validity_expiration",
       alt.sale_validity_expiration as "Current_MA_First_LA_CAM_sale_validity_expiration",
       ap."type" as "Current_MA_First_LA_CAM_affiliate_partner_type",
       pp.placement as "Current_MA_First_LA_CAM_affiliate_information_placementProvider_placement"
from all_tracking alt
```
`[d.name for d in proxy.cursor.description]` returns:
```
['smavaId', 'Current_MA_First_LA_CAM_lead_validity_expiration', 'Current_MA_First_LA_CAM_sale_validity_expiration', 'Current_MA_First_LA_CAM_affiliate_partner_type', 'Current_MA_First_LA_CAM_affiliate_information_placementProvider']
```
As you may see - the last column:
should: Current_MA_First_LA_CAM_affiliate_information_placementProvider_placement
actual : Current_MA_First_LA_CAM_affiliate_information_placementProvider
`_placement` is missing.
In `proxy.cursor.query` column name is proper. 

The code to extract the data:
```py

from sqlalchemy import create_engine
engine = create_engine(database)

def read_db_generator(engine, query):
    connection = engine.connect()
    proxy = connection.execution_options(stream_results=True).execute(query)
    while True:
        batch = proxy.fetchmany(5000)
        if not batch:
            break

        for row in batch:
            yield row
    proxy.close()
    connection.close()
```

**Versions.**
 - OS: ubuntu
 - Python: Conda Python 3.7.4
 - SQLAlchemy: 1.3.15
 - Database: PostgreSQL 11.5
 - DBAPI:

**Comment by zzzeek** [comment]
hey Val -

when you look in cursor.description, you are getting at the actual names returned by the database driver.  In this case you are observing a name that is being truncated by the database server in this case PostgreSQL to the maximum identifier length which is [63 characters](https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS)  (" longer names can be written in commands, but they will be truncated.").   on other databases such as oracle, an identifier that's too long will probably raise a SQL error.

In older versions of SQLAlchemy, the ORM in particular would rely upon these names to match up the columns in the result set to the Table/Column objects represented in the query, but as of the 1.1 series it usually does it positionally so these names don't matter too much, the Column objects in a select() statement for example can be matched to what you get back in a result row.

**Comment by comtihon** [comment]
Sorry, I referred to the wrong documentation where 125 chars lengh mentioned.
My bad.
Thanks for the quick answer!
