### ISSUE TITLE
Adopting the SQLAlchemy 1.4 beta release for a beta service in production?

### ISSUE THREAD

**Issue by ljiatu** [sqlalchemy/sqlalchemy#5847]
**Describe your question**
Hi folks! I want to get some expert opinion on adopting 1.4 beta release for a beta service we have in production.

We are building a product that's also currently in beta with a limited number of users trying it out, and we are aiming for a public launch in a few months. We are currently using SQLAlchemy 1.3 with a hand-rolled solution for async execution. I'm thinking about migrating our service to 1.4 now and try to make it work before the public launch so that we have enough time to iron out any issue. If something does go wrong, then the damage is very much contained due to the limited number of users. Adopting 1.4 after its official release seems a bit riskier since we may have already launched publicly and the stakes are much higher.

So I'm curious to know the following:
(1) is there is a potential date for the official release? Based on the past release schedule, it seems like it generally takes 3-4 months between the first beta release and the official release. Would you expect 1.4 to follow a similar schedule?
(2) how much do you think the API would change between now and the official release?
(3) what's your take on adopting the beta version in general?

I know these questions are hard to answer and there are unknown unknowns, so I'm definitely not looking for any commitments of any sort. Any guidance would be greatly appreciated, and thank you very much in advance for your help!

**Comment by zzzeek** [comment]
short answer I think 1.4 is going pretty well so far, right now getting 1.4.0b2 out is the big priority as there will be a lot of fixes vs 1.4.0b1.    definitely want to get 1.4.0 out within a couple of months as you mentioned.

if your own service is beta as well , then you'll be testing also, people are using the async feature now already.    I can't say it's risk free and in fact most of the "big" 1.4 bugs will likely be reported after we put 1.4.0 out, which is when people really start using it.    but if you are carefully testing your service and keeping up to date it's certainly feasible to start up with the new version.

**Comment by ljiatu** [comment]
Cool, I'll give the beta version a shot. Thanks for the really fast turnaround as always @zzzeek!
