### ISSUE TITLE
Index columns are not correctly reflected

### ISSUE THREAD

**Issue by pythonmeister** [sqlalchemy/sqlalchemy#5851]
**Description**
I created a small test to learn about the reflection capabilities of SQLAlchemy. I used Python 3.9.1 amd64 under Windows 10 and SQLAlchemy 1.4.0b1 for this.

```from sqlalchemy import create_engine, MetaData

engine = create_engine('sqlite:///:memory:')
connection = engine.connect()
connection.execute("CREATE TABLE T1(ID INTEGER PRIMARY KEY, NAME CHAR(10) )")
connection.execute("CREATE TABLE T2(ID INTEGER PRIMARY KEY, T1_ID INTEGER, NAME VARCHAR, FOREIGN KEY (T1_ID) REFERENCES T1(ID))")
connection.execute("CREATE INDEX T1_NAME ON T1(NAME)")

metadata = MetaData(bind=connection)
metadata.reflect()

for t in metadata.sorted_tables:
    print(t.name)
    for c in t.columns:
        print(c.name, c.type, "indexed" if c.index else "not indexed", c.autoincrement, c.foreign_keys, c.primary_key)

``` 

**Expected behavior**
The value of `c.index` must be `True` for T1.ID, T2.ID and T1.NAME.

**To Reproduce**
See above.

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

```py
# Insert code here
```

**Error**

```
# Copy error here. Please include the full stack trace.
```

**Versions.**
 - OS: Windows 10.0.19042.746
 - Python: 3.9.1
 - SQLAlchemy: 1.4.0b1
 - Database: SQLite
 - DBAPI: 

**Additional context**
N/A

**Have a nice day!**

**Comment by pythonmeister** [comment]
I changed the code a bit:
```
for t in metadata.sorted_tables:
    print(t.name)
    print(t.indexes)
    for c in t.columns:
        print(c.name, c.type, "indexed" if c.index else "not indexed", c.autoincrement, c.foreign_keys, c.primary_key)
```

That shows the explicetly indexed column T1.NAME: `{Index('T1_NAME', Column('NAME', CHAR(length=10), table=<T1>))}`.
All other indexes are missing (PRIMARY KEY columns).

**Comment by zzzeek** [comment]
> **Description**
> I created a small test to learn about the reflection capabilities of SQLAlchemy. I used Python 3.9.1 amd64 under Windows 10 and SQLAlchemy 1.4.0b1 for this.
> 
> ```
> 
> engine = create_engine('sqlite:///:memory:')
> connection = engine.connect()
> connection.execute("CREATE TABLE T1(ID INTEGER PRIMARY KEY, NAME CHAR(10) )")
> connection.execute("CREATE TABLE T2(ID INTEGER PRIMARY KEY, T1_ID INTEGER, NAME VARCHAR, FOREIGN KEY (T1_ID) REFERENCES T1(ID))")
> connection.execute("CREATE INDEX T1_NAME ON T1(NAME)")
> 
> metadata = MetaData(bind=connection)
> metadata.reflect()
> 
> for t in metadata.sorted_tables:
>     print(t.name)
>     for c in t.columns:
>         print(c.name, c.type, "indexed" if c.index else "not indexed", c.autoincrement, c.foreign_keys, c.primary_key)
> ```
> 
> **Expected behavior**
> The value of `c.index` must be `True` for T1.ID, T2.ID and T1.NAME.

hi there -

"c.index" only refers to the value of the [index](https://docs.sqlalchemy.org/en/13/core/metadata.html?highlight=column#sqlalchemy.schema.Column.params.index) parameter passed to the Column object.   while there is documentation lacking the behavior is currently noted in this [comment](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/schema.py#L1429):

        # these default to None because .index and .unique is *not*
        # an informational flag about Column - there can still be an
        # Index or UniqueConstraint referring to this Column.

the Index object is local to a Table and may involve any number of Column objects or expressions.  To view the indexes that were reflected on a Table the table.indexes collection, which seems like it might not be documented either, and the best way to view the indexes for a table is to use the [Inspector.get_indexes()](https://docs.sqlalchemy.org/en/13/core/reflection.html?highlight=get_indexes#sqlalchemy.engine.reflection.Inspector.get_indexes) method of Inspector.


> 
> **To Reproduce**
> See above.
> 
> **Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**. The test case must illustrate the problem **without** using any third party SQLAlchemy extensions. Otherwise, please report the bug to those projects first.
> 
> ```python
> # Insert code here
> ```
> 
> **Error**
> 
> ```
> # Copy error here. Please include the full stack trace.
> ```
> 
> **Versions.**
> 
>     * OS: Windows 10.0.19042.746
> 
>     * Python: 3.9.1
> 
>     * SQLAlchemy: 1.4.0b1
> 
>     * Database: SQLite
> 
>     * DBAPI:
> 
> 
> **Additional context**
> N/A
> 
> **Have a nice day!**

**Comment by pythonmeister** [comment]
Hi,

The Inspector class does its job, thanks for the hint. Perhaps the best would be to document that.

**Comment by zzzeek** [comment]
inspector is documented.  the .index and .indexes attributes are not easy to document because Sphinx doesn't have good support for autodocumenting attributes.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Document Table/Column accessors** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2490

**Comment by pythonmeister** [comment]
Looks good! Precise and clear.

**Comment by zzzeek** [comment]
as you might notice the inconvenience is that I have to change the source code of the object to add those docstrings such that they will be displayed in the correct context.   if I use ".. attribute" in the .rst file, they dont get sorted.

**Comment by pythonmeister** [comment]
I'm sorry, but I think that makes it clearer.

Thank you very much!

**Comment by zzzeek** [comment]
all good now!  thanks for raising the issue.
