### ISSUE TITLE
alternative to mapper's deprecated "order_by" not working

### ISSUE THREAD

**Issue by radam9** [sqlalchemy/sqlalchemy#5870]
I have a `Single Table Inheritance` orm model that looks like this:

```python
class Human(Base):
    
    __tablename__ = "human"

    id = Column(Integer, primary_key=True)
    name = Column(String)
    index = Column(Integer)
    parent_id = Column(Integer, ForeignKey("human.id"), nullable=True)
    type = Column(String)
    parent = relationship(
        "Human",
        cascade="save-update, merge",
        backref=backref("children", cascade="all"),
        lazy=False,
        remote_side="Human.id",
    )

    __mapper_args__ = {"polymorphic_on": type, "polymorphic_identity": "human"}

class Parent(Human):

    __mapper_args__ = {"polymorphic_identity": "parent"}

class Child(Human):

    hobby = Column(String)
    pet = Column(String)

    __mapper_args__ = {"polymorphic_identity": "child"}
```
This relationship looks like a nested tree, where I can query the oldest person (i.e: great grandparent, using `query.get(1)`) and then in his `children` attribute all his `children` will be present, and each child will also have their `children` present.
This relationship works just fine in every aspect.

I want the `children` that are queried when I query a `Parent` (due to lazy=False) to be ordered by the `index` column not the `id` column (which is the default).

I was achieving this by adding the following `"order_by": "index"` to the `Human` class' `__mapper_args__` as follows:
```python
__mapper_args__ = {"polymorphic_on": type, "polymorphic_identity": "human", "order_by": "index"}
```

I recently found out in SQLAlchemy's documentation the `order_by` argument in the `mapper()` class is deprecated since SQLAlchemy version `1.1` ([reference][1]). And it's said to use `Query.order_by()` to order instead, which is not working for me for some reason.

I have tried the following:
- adding `order_by` to the query, `session.query(Human).order_by(Human.index).get(1)`
- adding `order_by="Human.index"` to the `relationship()` in the `Human` class.

these two methods are not working.

How can I achieve the same effect as the `order_by` in `mapper()` now that it is deprecated?

  [1]: https://docs.sqlalchemy.org/en/13/orm/mapping_api.html?highlight=mapper#sqlalchemy.orm.mapper.params.order_by

**Versions**
 - OS: Pop!_OS 20.04 LTS
 - Python: 3.8
 - SQLAlchemy: 1.3.22
 - Database: SQLite

**Comment by zzzeek** [comment]
hey there-

the ordering of a collection loaded by a relationship is controlled by the [order_by](https://docs.sqlalchemy.org/en/13/orm/relationship_api.html?highlight=relationship%20order_by#sqlalchemy.orm.relationship.params.order_by) parameter of `relationship()` and/or backref:

```
 parent = relationship(
        "Human",
        cascade="save-update, merge",
        backref=backref("children", cascade="all", order_by="Human.index"),
        lazy=False,
        remote_side="Human.id",
    )


```

that is, this has nothing to do with mapper.order_by, although that attribute was having the effect you were seeking.  hope this helps.

**Comment by radam9** [comment]
Thank you very much for your reply, this did solve my problem and I learned something new !

The issue was that I was inserting the `order_by="Human.index"` inside the parent `relationship()` instead of inside the `backref` as you mentioned.
