### ISSUE TITLE
immutabledict.c speedups

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5871]
don't recall where the results were but @CaselIT showed some immutabledict methods were slower in C because we are using code like "PyObject_CallMethod(self->dict, "get", "OO", key, default_value);", where we should be using the PyDict_Get (or whatever it's called) methods for these basic operations.

**Comment by CaselIT** [comment]
The tests are here https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2444

I've added some other cython implementations there :)

**Comment by CaselIT** [comment]
I can work on this this week mike

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Improve c implementation of immutabledict** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2510
