### ISSUE TITLE
MySQL dialect does not support Spatial Data types

### ISSUE THREAD

**Issue by yoch** [sqlalchemy/sqlalchemy#5885]
**Describe the bug**

MySQL dialect does not support Spatial Data types.

When I use reflection, I got a warning indicating that `Point` type is not supported.

**Expected behavior**

At least not to have a warning, and if possible the ability to use Spatial Data types with SQLAlchemy.

**Error**

```
/env/lib/python3.5/site-packages/sqlalchemy/dialects/mysql/reflection.py:193: 
SAWarning: Did not recognize type 'point' of column 'coords'
```

**Versions.**
 - OS: Linux Debian 4.9
 - Python: 3.5
 - SQLAlchemy: 1.3
 - Database: mariadb 10.2
 - DBAPI: pymysql

**Thank you !**

**Comment by zzzeek** [comment]
See #4683.  Right now we'd prefer these issues are taken up by the [geoalchemy2](https://geoalchemy-2.readthedocs.io/en/latest/) project.   if that project is dead then it needs to get a new maintainer, as Geo is a large enough topic we'd prefer it have a dedicated maintainer.

**Comment by zzzeek** [comment]
looks to be fully maintained so see if they can help with MySQL support.
