### ISSUE TITLE
move mapper configuration to be per registry

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5897]
so that this is started:

1. amending my original idea here re: coercions.  we acutally want confiure_mappers() to be within the compile phase more than coercions, because we want sql expressions to be composable for unconfigured mappers as much as possible, as they themselves are used in mappings.  so looking throguh what we have now I tihnk the general idea is OK, going to streamline it some more.

2. change _mapper_registry to be a list of registries, not mappers

3. add a configure() method to each registry.  this will call something like mapper._configure_registries(self)

4. set up configure mappers so that the lock remains global, but is called on a per-registry basis.   have the call invoke on each mapper registry individually.   

5. when a mapper registry reaches out to a dependent registry, add it to a stack.   this stack is addressed outside of the lock within the _configure_registries function.

6. dependent registry is found via relationship (inheriting also?)

7. similar arch for clear_mappers()

the goals include:

1. no longer a need for all mappers in the entire application to configure at once if not needed

2. same for clearing mappers

3. consolidation of configure_mappers() points in the coercions system so that we can have fine-grained setup triggers for configure_mappers() without complexity

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**reorganize mapper compile/teardown under registry** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2524
