### ISSUE TITLE
Does Auto-truncation not work with mariadb? Or does it need to be manually turned on?

### ISSUE THREAD

**Issue by Adityashaw** [sqlalchemy/sqlalchemy#5898]
This issue is in continuation of #3989

**Describe the bug**

**Exact error received is:**
 ```
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1059, "Identifier name 'fk_faculty_marks_assistant_department_subject_id_department_subject' is too long")
```

**Expected behavior**

Sqlalchemy should auto-truncate the constraint name as it is above 64 characters.

I am expecting this behaviour as the original issue is marked as fixed and closed.

**To Reproduce**

*I don't know how to create a unit test for naming conventions and alembic. Any example link will be appreciated.*

The Naming Convention used:
```
convention = {
    "ix": 'ix_%(column_0_N_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
```

Relevant models:
```
class DepartmentSubject(db.Model):
    __tablename__ = 'department_subject'

    id = db.Column(db.SmallInteger, primary_key=True)


class FacultyMarksAssistant(db.Model):
    __tablename__ = 'faculty_marks_assistant'

    department_subject_id = db.Column(
        db.ForeignKey('department_subject.id'),
        primary_key=True, nullable=False, index=True
    )

```
**Error**

```
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1059, "Identifier name 'fk_faculty_marks_assistant_department_subject_id_department_subject' is too long")
```

**Versions.**
 - OS: archlinux 5.9.14-arch1-1
 - Python: 3.9.0
 - SQLAlchemy: 1.3.20
 - Database: mariadb   Ver 15.1 Distrib 10.5.8-MariaDB, for Linux (x86_64) using readline 5.1
 - DBAPI: mysqlclient 2.0.2

**Additional context**
>the MySQL dialect has two separate lengths set up and these are likely not accommodated >correctly:

>    # identifiers are 64, however aliases can be 255...
>     max_identifier_length = 255
>     max_index_name_length = 64

>_Originally posted by @zzzeek in https://github.com/sqlalchemy/sqlalchemy/issues/3989#issuecomment-770219401_

Where would I find this and check?

**Comment by zzzeek** [comment]
you should be able to pass max_identifier_length to create_engine right now:

   e = create_engine("mysql://...", max_identifier_length=64)

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**set identifier length for MySQL constraints to 64** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2525

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**set identifier length for MySQL constraints to 64** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2526

**Comment by zzzeek** [comment]
pretty weird that most MySQL versions are not even applying this foreign key name to the foreign key constraint itself; only MySQL 8 is doing it.  mariadb versions are naming the FK with a generated name and using the name on a related KEY element only.

**Comment by zzzeek** [comment]
latest rel_1_3 branch + master should work now if you feel like testing, thanks for reporting!
