### ISSUE TITLE
add per-connection or per-option engine logging name

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5911]
as we noted in #5896  there's no way to have individual connections put some speical context into  log messages which is pretty important for debugging.   have this be a logging_name execution option.

**Comment by zzzeek** [comment]
OK so, the "logging name" is the name given in logging.getLogger(), and this means Python logging creates a logging object that's then global in memory, and is not appropriate in a transitory way like a per-connection basis.  so lets call this "logging token" instead and have it separate.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement per-connection logging token** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2532
