### ISSUE TITLE
Multiple lateral joins trigger a "cartesian product" warning

### ISSUE THREAD

**Issue by atellier** [sqlalchemy/sqlalchemy#5924]
**Describe the bug**
Joining more than two `lateral` queries produces the right SQL command but yields a "cartesian product" warning

**Expected behavior**
No warning should be emitted

**To Reproduce**
```py
from sqlalchemy import Column, Integer, Float, select, true
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class A(Base):
    __tablename__ = "A"
    id = Column(Integer, primary_key=True)
    value = Column(Float)


class B(Base):
    __tablename__ = "B"
    id = Column(Integer, primary_key=True)
    value = Column(Float)
    id_a = Column(Integer)


class C(Base):
    __tablename__ = "C"
    id = Column(Integer, primary_key=True)
    value = Column(Float)
    id_a = Column(Integer)


a = select(A.id, A.value).subquery()
b = select(B.value).where(a.c.id == B.id_a).order_by(B.value).limit(1).lateral()
c = select(C.value).where(a.c.id == C.id_a).order_by(C.value).limit(1).lateral()

query = select(a, b, c).select_from(a).join(b, true()).join(c, true())

# Execute query here
```

Note that the correct SQL is produced:
```
[SQL: SELECT anon_1.id, anon_1.value, anon_2.value AS value_1, anon_3.value AS value_2 
FROM (SELECT "A".id AS id, "A".value AS value 
FROM "A") AS anon_1 JOIN LATERAL (SELECT "B".value AS value 
FROM "B" 
WHERE anon_1.id = "B".id_a ORDER BY "B".value
 LIMIT ? OFFSET ?) AS anon_2 ON 1 = 1 JOIN LATERAL (SELECT "C".value AS value 
FROM "C" 
WHERE anon_1.id = "C".id_a ORDER BY "C".value
 LIMIT ? OFFSET ?) AS anon_3 ON 1 = 1]
[parameters: (1, 0, 1, 0)]
```

**Error**
`sqlalchemy/sql/compiler.py:357: SAWarning: SELECT statement has a cartesian product between FROM element(s) "anon_3" and FROM element "anon_1".  Apply join condition(s) between each element to resolve.`

**Versions.**
 - OS: OSX 11.2
 - Python: 3.9.1
 - SQLAlchemy: 1.4.0b2
 - Database: All
 - DBAPI: N/A

**Additional context**
If we only join with one lateral query, then the warning is not emitted.

I also tried to add a `.subquery()` before the `lateral()`, and different combinations of `join` (chained or not) to no avail. 

*Note*: Also, I am confused at to whether or not a `subquery()` is needed before a `lateral`, or if it is already implied?

Thank you,

**Comment by zzzeek** [comment]
gonna be tricky to fix...

your code is fine.   the whole idea of "LATERAL" is that ....the cartesian product searcher thing also has to learn how to join laterally :)    there was an unfortunate issue where the test suite didn't have cartesian linting turned on for our lateral tests.

**Comment by atellier** [comment]
I know it may be a lot of work and / or a breaking change, but a better solution could be to introduce a `lateraljoin()` operator and deprecate `lateral()`.

1. That may make solving the issue at hand easier
2. It will help with https://github.com/sqlalchemy/sqlalchemy/issues/5133 for instance
3. We do not have to use an awkward construct such as `join(..., true())` 

Thanks

**Comment by atellier** [comment]
In the meantime, is there a way to suppress this warning, or do you think there is a way to re-write the query differently not to trigger the cartesian product searcher  - I have already tried a couple things but they did not work :(

Thanks

**Comment by zzzeek** [comment]
the from linting can be turned off quite simply by passing enable_from_linting=False to create_engine:

https://docs.sqlalchemy.org/en/14/core/engines.html?highlight=from%20linting#sqlalchemy.create_engine.params.enable_from_linting

**Comment by zzzeek** [comment]
also this is hard to fix not because of the API, it's hard because I have to emulate the geometry of "lateral" in the compiler, but the good news is that math and recursion still work so a fix is coming up shortly

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Track a second from_linter for lateral subqueries** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2536

**Comment by zzzeek** [comment]
oh also with this fix (or if you set the option off for now) you should not have to join() on true(), this works:

    query = select(a, b, c)

output:

```sql
SELECT anon_1.id, anon_1.value, anon_2.value AS value_1, anon_3.value AS value_2 
FROM (SELECT "A".id AS id, "A".value AS value 
FROM "A") AS anon_1, LATERAL (SELECT "B".value AS value 
FROM "B" 
WHERE anon_1.id = "B".id_a ORDER BY "B".value 
 LIMIT %(param_1)s) AS anon_2, LATERAL (SELECT "C".value AS value 
FROM "C" 
WHERE anon_1.id = "C".id_a ORDER BY "C".value 
 LIMIT %(param_2)s) AS anon_3

```

**Comment by zzzeek** [comment]
LATERAL is SQL standard, and it does not require JOIN, so we do that

**Comment by atellier** [comment]
I will try that and also `enable_from_linting` flag until next release. Thanks!

**Comment by CaselIT** [comment]
> 
> 
> In the meantime, is there a way to suppress this warning (it is clogging our logs), or do you think there is a way to re-write the query differently not to trigger the cartesian product searcher - I have already tried a couple things but they did not work :(
> 
> Thanks

Since that is a classical python warning, you could setup a warning filter for that emissing. https://docs.python.org/3/library/warnings.html

Something like this should work
```py
import warnings
warnings.simplefilter("ignore:SELECT statement has a cartesian product.*:SAWarning")
```

**Comment by atellier** [comment]
Thanks for the idea @CaselIT !

This is what worked for me:
```        
with warnings.catch_warnings():
    warnings.filterwarnings(
        "ignore", "SELECT statement has a cartesian product.*", SAWarning
    )
```

**Comment by atellier** [comment]
> LATERAL is SQL standard, and it does not require JOIN, so we do that

I am using outer "lateral" in my code so I guess I am stuck with doing the "join" version.

**Comment by zzzeek** [comment]
> Thanks for the idea @CaselIT !
> 
> This is what worked for me (I was able to pinpoint the fix on only the very query that was at fault):
> 
> ```
> with warnings.catch_warnings():
>     warnings.filterwarnings(
>         "ignore", "SELECT statement has a cartesian product.*", SAWarning
>     )
>     ...
> ```

why didn't this work?

    create_engine(..., enable_from_linting=False)

**Comment by zzzeek** [comment]
> I am using outer "lateral" in my code so I guess I am stuck with doing the "join" version.

why?    I'm not following?    what's "outer LATERAL" ?

**Comment by atellier** [comment]
I went for the context manager version because only one of my queries was concerned, and I did not want to broadly suppress that message as it is useful and relevant in other queries.

There is indeed no "OUTER LATERAL" per se in SQL - I was referring to a `LEFT JOIN LATERAL` in my case - sorry for the confusion.
