### ISSUE TITLE
2.0 style ORM queries should preserve labels in ORM result

### ISSUE THREAD

**Issue by bencf** [sqlalchemy/sqlalchemy#5933]
**Describe the bug**
Using SQLAlchemy 1.4.0b2, I'm joining one version of subquery on itself, so I get duplicate column names. The SQL produced properly disambiguates these column names, however the keys returned in the result set are not disambiguated.

(I'm new to SQLAlchemy, so this may not be a bug, but I would think it would be as I can't distinguish between the two different fields in the results.)

**Expected behavior**
For the labels to be the same as the keys in the result set.

**To Reproduce**
If we have two queries joined on each other, like this:
```py
query1 = <query>.alias('a')
query2 = <query>.alias('b')

joined_query = (
        select(query1, query2)
        .join(query1, query1.c.join_field == query2.c.join_field)
        .set_label_style(LABEL_STYLE_TABLENAME_PLUS_COL)
    )
```
We then get SQL produced like:
```sql
SELECT a.foo as a_foo, b.foo as b_foo
FROM (<query>) a
JOIN (<query>) b ON a.join_field = b.join_field
```
So far so good. The column names are disambiguated in SQL according to the specific method.

However, when I try to get the results, as follows, that disambiguation disappears:
```py
result = session.execute(joined_query)
for row in result:
    print(row.keys())
```
I get a result that looks like: `RMKeyView(['foo', 'foo'])` which means that I can't reference the two columns separately. I would think I could do something like `row['a_foo']` or `row.a_foo` and `row['b_foo']` or `row.b_foo`, but these throw an error.

(Note that this is true even using the default label disambiguation style, which would produce something like `a.foo, b.foo AS foo_1` in the SQL, but still return both keys as `foo` in the result set.)

**Versions.**
 - OS: macOS 11.1
 - Python: 3.9.0
 - SQLAlchemy: 1.4.0b2
 - Database: PostgreSQL
 - DBAPI: psycopg2==2.8.6

**Thank you for any and all help!**
I have done extensive Googling about this and can't find a resolution, which makes me think this may be a bug introduced in the new version.

If this is _not_ a bug, any recommendations about how to resolve this problem would be appreciated!

**Comment by zzzeek** [comment]
hi there might be a bug here but i would really need to see an [MCVE](http://stackoverflow.com/help/mcve) including the table definition you are working with.  I will try to reproduce locally.

**Comment by zzzeek** [comment]
does not reproduce with the below test:
```python

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import LABEL_STYLE_TABLENAME_PLUS_COL
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import declarative_base
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)


a1 = select(A.__table__).subquery("a1")
a2 = select(A.__table__).subquery("a2")

stmt = select(a1, a2).select_from(a1.join(a2, a1.c.id == a2.c.id))

e = create_engine("postgresql://scott:tiger@localhost/test", echo='debug')

with e.connect() as conn:
    conn.begin()
    Base.metadata.create_all(conn)

    conn.execute(
        A.__table__.insert(),
        {"id": 1, "data": "some data"}
    )
    result = conn.execute(
        stmt.set_label_style(LABEL_STYLE_TABLENAME_PLUS_COL)
    )
    row = result.fetchone()
    print(row.keys())

```


output:

```sql
SELECT a1.id AS a1_id, a1.data AS a1_data, a2.id AS a2_id, a2.data AS a2_data 
FROM (SELECT a.id AS id, a.data AS data 
FROM a) AS a1 JOIN (SELECT a.id AS id, a.data AS data 
FROM a) AS a2 ON a1.id = a2.id
2021-02-11 11:55:15,741 INFO sqlalchemy.engine.Engine [generated in 0.00021s] {}
2021-02-11 11:55:15,742 DEBUG sqlalchemy.engine.Engine Col ('a1_id', 'a1_data', 'a2_id', 'a2_data')
2021-02-11 11:55:15,742 DEBUG sqlalchemy.engine.Engine Row (1, 'some data', 1, 'some data')
RMKeyView(['a1_id', 'a1_data', 'a2_id', 'a2_data'])

```

**Comment by bencf** [comment]
Thanks, Mike, this is very helpful. Let me try to match your test with my code and see if I can identify the key differences and if I can get it to reproduce.

**Comment by bencf** [comment]
OK, I figured out how to reproduce it.

The differences with your test are:
(1) Using `Session`
(2) Specifying the fields in the select

Either change by itself doesn't reproduce the problem, only the combination of them.

In your code, replace:
```py
a1 = select(A.__table__).subquery("a1")
a2 = select(A.__table__).subquery("a2")
```
with
```py
a1 = select(A.id, A.data).subquery("a1")
a2 = select(A.id, A.data).subquery("a2")
```

And replace this:
```py
with e.connect() as conn:
    conn.begin()
    Base.metadata.create_all(conn)

    conn.execute(
        A.__table__.insert(),
        {"id": 1, "data": "some data"}
    )
    result = conn.execute(
        stmt.set_label_style(LABEL_STYLE_TABLENAME_PLUS_COL)
    )
    row = result.fetchone()
    print(row.keys())
```
with
```py
with Session(e) as session:
    Base.metadata.create_all(e)

    session.execute(
        A.__table__.insert(),
        {"id": 1, "data": "some data"}
    )
    result = session.execute(
        stmt.set_label_style(LABEL_STYLE_TABLENAME_PLUS_COL)
    )
    row = result.fetchone()
    print(row.keys())
```
(As well as importing `Session`.)

That gives me this output:
```sql
SELECT a1.id AS a1_id, a1.data AS a1_data, a2.id AS a2_id, a2.data AS a2_data
FROM (SELECT a.id AS id, a.data AS data
FROM a) AS a1 JOIN (SELECT a.id AS id, a.data AS data
FROM a) AS a2 ON a1.id = a2.id
2021-02-11 12:35:30,427 INFO sqlalchemy.engine.Engine [generated in 0.00026s] {}
RMKeyView(['id', 'data', 'id', 'data'])
```

As I said, I am very new to SQLAlchemy so it's possible I'm misunderstanding why these changes *should* produce this behavior, but given that the SQL query is labeled properly, it's not clear to me why these changes should change anything about the output to the result.

Thanks again for the help (and for the quick response)!

**Comment by zzzeek** [comment]
ah OK that's an ORM result.   This usage is also very new to me as well as that's a new feature in 1.4, so I agree, this seems off, and in fact this would be a big deal to fix as there's a whole set of assumptions in place right now based on how ORM queries have always worked, but in this case, now that we are trying to "unify" Core and ORM this has to be fixed and in fact this is the first issue I've seen reported against 1.4's whole paradigm shift that is actually against the new set of assumptions.

**Comment by bencf** [comment]
Thanks so much for the quick responses Mike, and glad I could be of some help!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Apply consistent labeling for all future style ORM queries** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2581

**Comment by zzzeek** [comment]
still needs some work

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**Further refine labeling for renamed columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2583
