### ISSUE TITLE
select() in v1.4b2 no longer accepts an ImmutableColumnCollection

### ISSUE THREAD

**Issue by olirice** [sqlalchemy/sqlalchemy#5935]
**Describe the bug**
Version 1.3.* supports an `ImmutableColumnCollection` in a `sqlalchemy.select` call. In 1.4.0b2 that results in an `ArgumentError`

**Expected behavior**
I don't know if this changed intentionally, so it might be expected behavior. If that is the case, a note in the [changelog around here](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#orm-query-is-internally-unified-with-select-update-delete-2-0-style-execution-available)

> The select() construct no longer needs brackets around the columns clause; see select(), case() now accept positional expressions for background on this improvement.

might help others.

**To Reproduce**
```py
from sqlalchemy import Table, Column, MetaData, Integer, Text, select

account = Table(
    'account',
    MetaData(),
    Column('id', Integer, primary_key=True),
    Column('email', Text)
)

select(account.c)
# v1.3: <sqlalchemy.sql.selectable.Select at 0x114451ba8; Select object>

# v1.4.0b2: 
#    ArgumentError: Column expression or FROM clause expected,
#                   got <sqlalchemy.sql.base.ImmutableColumnCollection object
```

**Error**
```
ArgumentError                             Traceback (most recent call last)
<ipython-input-2-1c141904fd7e> in <module>
      6 )
      7 
----> 8 select(account.c)
      9 # v1.3: <sqlalchemy.sql.selectable.Select at 0x114451ba8; Select object>
     10 # v1.4.0b2:

<string> in select(*args, **kw)
```

**Versions.**
 - OS: macOS 10.15.4
 - Python: 3.8.6
 - SQLAlchemy: 1.4.0b2
 - Database: not relevant
 - DBAPI: not relevant

**Comment by zzzeek** [comment]
heya -

this is an unexpected API pattern that's never been tested; in 1.3, the correct syntax that's documented everywhere is `select([account])`.    What's wrong with `select(account)` ?

**Comment by olirice** [comment]
Nothing at all, that syntax works great. It was just an error I ran into while upgrading.

I didn't realize that was incorrect usage in v1.3
It seemed more natural because `select` takes/took a list and `select(model.c)` felt more "list-like" than `select(model)`

My mistake, thanks for the fast response

**Comment by zzzeek** [comment]
Yeah I see why it is handy for the 1.3 style, because select() accepts a sequence and the .c is a sequence-ish thing.   Just surprised someone came up with that , that's all :)    The logic for select() right now to maintain the old behavior uses an isinstance() check so it could be enhanced to pick up on this also.   Just not sure if this affects a lot of people or not, or to what degree this affects your own work.

**Comment by olirice** [comment]
We have 7 instances, last edited by 3 (of 4) developers in a sqla heavy 20k line codebase. Most of it doesn't use the core query builder though, so its fairly common for us, but I don't know about externally.

FWIW the argument exception the legacy select statement creator says `iterable` rather than `list`, and does work on arbitrary iterables.
https://github.com/sqlalchemy/sqlalchemy/blob/4aa0c7ae76894048c5c30c89c403c7cbf5d844ff/lib/sqlalchemy/sql/selectable.py#L4746

Would you be interested in a PR to make this more permissive?
https://github.com/sqlalchemy/sqlalchemy/blob/4aa0c7ae76894048c5c30c89c403c7cbf5d844ff/lib/sqlalchemy/sql/selectable.py#L4873

**Comment by zzzeek** [comment]
sure, it all goes away in 2.0 but as long as we have a test that will ensure it doesn't get reset.   test is under deprecations right here: https://github.com/sqlalchemy/sqlalchemy/blob/master/test/sql/test_deprecations.py#L431

**Comment by sqla-tester** [comment]
**Oliver Rice** has proposed a fix for this issue in the **master** branch:

**Support legacy select(<iterable>) in addition to select(<list>) in v1.4** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2584
