### ISSUE TITLE
postgresql/sqlite/ similar (mysql on duplicate key?): on_conflict_do_update.set_ should support ImmutableColumnCollection

### ISSUE THREAD

**Issue by holymonson** [sqlalchemy/sqlalchemy#5939]
**Is your feature request related to a problem? Please describe.**

```python
from sqlalchemy.dialects.postgresql import insert

stmt = insert(table)
stmt = stmt.on_conflict_do_update(constraint=table.primary_key, set_=dict(stmt.excluded))

conn.execute(stmt, values_list)
```
This is a common usage for upsert, and `set_` must be a `dict`, so here we are using `set_=dict(stmt.excluded)`. But a semantic way is using `set_=stmt.excluded` directly, casting to `dict` seems redundant.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Accept ImmutableColumnCollection in update_on_conflict(set_** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2586
