### ISSUE TITLE
add reflection_options to automapbase.prepare()

### ISSUE THREAD

**Issue by PikalaxALT** [sqlalchemy/sqlalchemy#5942]
**Is your feature request related to a problem? Please describe.**
It may sometimes be undesirable to load all table definitions when using an automap base, so users should have a way to control this programmatically.

**Describe the solution you'd like**
Implement `AutomapBase.prepare.params.only`. This would be forwarded to `MetaData.reflect` and behave exactly the same as `MetaData.reflect.params.only`.

**Describe alternatives you've considered**
It is possible to get around this by calling `AutomapBase.metadata.reflect` yourself before `.prepare`, then not passing an engine to `.prepare`.

**Additional context**
[Where this proposed kwarg would be passed](https://github.com/sqlalchemy/sqlalchemy/blob/63f57014ef72eb0a32111777fc006bebf7ce0cc5/lib/sqlalchemy/ext/automap.py#L850-L862)

**Have a nice day!**

**Comment by zzzeek** [comment]
there's a whole bunch of options that metadata.reflect() accepts and IMO we should address them all at once by adding a new parameter "reflection_options" or "reflect_options" which is a dictionary that is passed to reflect().    that way we address ``only``, ``views``, ``resolve_fks``, as well as all ``dialect_kwargs`` all at once.   "extend_existing" and "autoload_replace" retain the current defaults used internally inside of prepare().

**Comment by gordthompson** [comment]
@zzzeek - Did you have something like this in mind?

```patch
Index: lib/sqlalchemy/ext/automap.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/sqlalchemy/ext/automap.py b/lib/sqlalchemy/ext/automap.py
--- a/lib/sqlalchemy/ext/automap.py	(revision f51f46a90a59d7d8ce93d90ec6ba30ddb74b12e9)
+++ b/lib/sqlalchemy/ext/automap.py	(date 1613485104052)
@@ -779,6 +779,7 @@
         name_for_scalar_relationship=None,
         name_for_collection_relationship=None,
         generate_relationship=None,
+        reflection_options=util.immutabledict(),
     ):
         """Extract mapped classes and relationships from the
         :class:`_schema.MetaData` and
@@ -832,8 +833,15 @@
 
         """
         glbls = globals()
+        classname_for_table = classname_for_table or reflection_options.get(
+            "classname_for_table"
+        )
         if classname_for_table is None:
             classname_for_table = glbls["classname_for_table"]
+        name_for_scalar_relationship = (
+            name_for_scalar_relationship
+            or reflection_options.get("name_for_scalar_relationship")
+        )
         if name_for_scalar_relationship is None:
             name_for_scalar_relationship = glbls[
                 "name_for_scalar_relationship"
```

**Comment by zzzeek** [comment]
yes, but I would not pull name_for_scalar_relationship or classname_for_table from this dictionary.  What we are trying to do is disambiguate parameters that are specific to the automap process, which include classname_for_table and name_for_scalar_relationship, from parameters that are specific to the table reflecton process, which include "only" and less well known options such as "oracle_resolve_synonyms".

**Comment by gordthompson** [comment]
Ah, okay, so something more like this?

```patch
Index: lib/sqlalchemy/ext/automap.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/sqlalchemy/ext/automap.py b/lib/sqlalchemy/ext/automap.py
--- a/lib/sqlalchemy/ext/automap.py	(revision f51f46a90a59d7d8ce93d90ec6ba30ddb74b12e9)
+++ b/lib/sqlalchemy/ext/automap.py	(date 1613493875394)
@@ -779,6 +779,7 @@
         name_for_scalar_relationship=None,
         name_for_collection_relationship=None,
         generate_relationship=None,
+        reflection_options=util.immutabledict(),
     ):
         """Extract mapped classes and relationships from the
         :class:`_schema.MetaData` and
@@ -830,6 +831,13 @@
 
          .. versionadded:: 1.1
 
+        :param reflection_options: When present, this dictionary of options
+         will be passed to :meth:`_schema.MetaData.reflect`
+         to supply general reflection-specific options like ``only`` and/or
+         dialect-specific options like ``oracle_resolve_synonyms``.
+
+         .. versionadded:: 1.4
+
         """
         glbls = globals()
         if classname_for_table is None:
@@ -859,6 +867,7 @@
                 schema=schema,
                 extend_existing=True,
                 autoload_replace=False,
+                **reflection_options,
             )
 
         with _CONFIGURE_MUTEX:
```

**Comment by zzzeek** [comment]
yeah like that.   the only thing I would add, is that the current parameters that *are* reflection related, work like this (assuming not an immutable dict)

    reflection_options.setdefault("extend_existing", extend_existing)
    reflection_options.setdefault("autoload_replace", autoload_replace)
   
then send **reflection_options as the sole argument to metadata.reflect().

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add reflection_options to automapbase.prepare()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2589
