### ISSUE TITLE
deprecate all schema-level .copy() functions and rename them to _copy()

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5953]
people are using these functions , like constraint.copy(), column.copy(), and they are not appropriate because these functions only work in certain contexts.    deprecate them all and rename to _copy().

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Deprecate and rename schema .copy() methods** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2591
