### ISSUE TITLE
Executing dynamic SQL on sql server

### ISSUE THREAD

**Issue by Fredchen717** [sqlalchemy/sqlalchemy#5959]
**Describe the bug**

Executing the code below does not return an error. In the create-statement of the dynamic sql statement I added a syntax-error to force an error.

**Expected behavior**
session.execute() should throw/return an error/exception.

**To Reproduce**
Just adapt the connection_string and the database attributes (DB, SCHEMA, TBL_TMP).

```py
from sqlalchemy.orm import sessionmaker
from sqlalchemy.exc import SQLAlchemyError

from sqlalchemy import create_engine


if __name__ == '__main__':
    connection_string = 'mssql+pyodbc://XXXXXXXX?driver=SQL+Server?trusted_connection=yes'
    some_engine = create_engine(connection_string, fast_executemany=True)

    Session_make = sessionmaker(bind=some_engine)
    session = Session_make()

    session.execute("""
    DECLARE @DB         AS nvarchar(40) = N'TESTDB'
    DECLARE @SCHEMA     as nvarchar(40) = N'TESTDATA'
    DECLARE @TBL_TMP    as nvarchar(40) = N'AA_TESTTABLE'
    DECLARE @DDL_STMT   as nvarchar(max)
    USE TESTDB
    
    BEGIN TRANSACTION creating
        SET @DDL_STMT = '
            CREATE TABLE  ['+ @DB +'].['+ @SCHEMA +'].['+ @TBL_TMP +'] (
                ID1 int NOT NULL
                , ID2 int NOT NULL,
                , ACTUARIAL_SEGMENT nvarchar(20) NOT NULL
                , SEGMENT_NAME nvarchar(32) NULL
            );

            ALTER TABLE  ['+ @DB +'].['+ @SCHEMA +'].['+ @TBL_TMP +'] 
            ADD CONSTRAINT PK_'+ @TBL_TMP +'  PRIMARY KEY NONCLUSTERED (
                ACTUARIAL_SEGMENT ASC
                , ID1 ASC
                , ID2 ASC
            );
            ';
        EXEC (@DDL_STMT)
    COMMIT TRANSACTION creating""")
    print('done')

    session.commit()
    some_engine.dispose()

```

**Versions.**
 - Python: 3.8
 - SQLAlchemy: 1.3.23
 - Database: SQL-Server

**Have a nice day!**

**Comment by gordthompson** [comment]
Hi @Fredchen717 

This is not an issue with SQLAlchemy. I get the same results with plain pyodbc.

The issue is that `USE TESTDB` is returning a server status message that is "blocking" the error until the next resultset is retrieved. You should receive the error correctly if you first do the `USE TESTDB` in a separate `.execute()` and then execute your anonymous code block with the `USE` statement omitted.

**Comment by Fredchen717** [comment]
Hi @gordthompson 

Thank you very much, that helped me a lot!

Kin dregards,
Fredchen717
