### ISSUE TITLE
postgresql: MONEY returns as float or Decimal

### ISSUE THREAD

**Issue by holymonson** [sqlalchemy/sqlalchemy#5965]
**Is your feature request related to a problem? Please describe.**
At present, `MONEY` type returns string like `$12.34`, which we can't use it directly in calculation. (inside postgresql we can)

**Describe the solution you'd like**
A parameter that make it returns as numeric type. May be `asdecimal`, default `None` as `str`, `False` as `float`, and `True` as `decimal.Decimal`.

**Describe alternatives you've considered**
If a 3-state parameter is not appropriate, maybe a new parameter.

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

I've just added documentation illustrating two different approaches to converting these values using TypeDecorator.    I'm more comfortable leaving the specifics to the end user as MONEY is a very infrequently used datatype and additionally with the incoming work for pep-484 in #4609 I'm actually beginning to consider deprecating the idea of a flag that changes the return type, in favor of having a different subtype.

Recipes for now are as follows:

```python
    # For this reason, it may be preferable to provide conversion to a
    # numerically-based currency datatype using :class:`_types.TypeDecorator`::

        import re
        import decimal
        from sqlalchemy import TypeDecorator

        class NumericMoney(TypeDecorator):
            impl = MONEY

            def process_result_value(self, value: Any, dialect: Any) -> None:
                if value is not None:
                    # adjust this for the currency and numeric
                    m = re.match(r"\$([\d.]+)", value)
                    if m:
                        value = decimal.Decimal(m.group(1))
                return value

    # Alternatively, the conversion may be applied as a CAST using
    # the :meth:`_types.TypeDecorator.column_expression` method as follows::

        import decimal
        from sqlalchemy import cast
        from sqlalchemy import TypeDecorator

        class NumericMoney(TypeDecorator):
            impl = MONEY

            def column_expression(self, column: Any):
                return cast(column, Numeric())

```

**Comment by holymonson** [comment]
Thanks zzzeek, closing this.
