### ISSUE TITLE
why am I getting the print out "SAWarning: Identity map already had an identity for"

### ISSUE THREAD

**Issue by chofsass** [sqlalchemy/sqlalchemy#5968]
this code:
```
    def common_bulk_save(self, instances):
        session = Session()

        try:
            session.add_all(instances)
            session.commit()
        except sqlalchemy.exc.IntegrityError as e:
            session.rollback()
        except Exception as e:
            logger.error(f"Datebase exception while saving: {e}")
        finally:
            session.close()
```

is causing this print out:
`SAWarning: Identity map already had an identity for (<class 'database_adapter.Day'>, (0,), None), replacing it with newly flushed object.   Are there load operations occurring inside of an event handler within the flush?`

**Example - please use the [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) guidelines if possible**
If I have to I will but there maybe a simple answer to this.

**Complete stack trace, if applicable**
None. Its just a print out

**Versions**
 - OS: Linux
 - Python: 3.8
 - SQLAlchemy: 1.3.23
 - Database: sqlite
 - DBAPI:

**Additional context**
None

**Useful links**
None

**Have a nice day!**

**Comment by zzzeek** [comment]
the error indicates what's being detected, which is a state change in the Session that's not possible unless you have an event handler that is modifying the state of the identity map.   Or much less likely if you have some kind of concurrent access to the Session going on.   it means that as the Session went to flush a brand new object with an INSERT and set up its new identity, something loaded that row into the same Session causing a conflict within the scope of the flush.

**Comment by chofsass** [comment]
I'm creating the session locally and closing it at the end of the function. I'm not using events unless they are being used under the hood in sqlalchemy. 

here is my table class: 
```
class Day(Base):
    __tablename__ = 'day'

    id = Column(Integer, primary_key=True)
    timestamp = Column(Integer, nullable=False)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Integer, nullable=False)
    symbol = Column(String, nullable=False)
    
    __table_args__ = (UniqueConstraint('symbol', 'timestamp', name='_symbol_timestamp_uc', sqlite_on_conflict='IGNORE'),)
```

**Comment by chofsass** [comment]
here is my session factory code as well:
```
engine = create_engine(f'sqlite:///{dir_path}/data.db', echo=False)
Base.metadata.create_all(bind=engine)
Session = sessionmaker(bind=engine)
```

**Comment by zzzeek** [comment]
OK, next thing, is I see the primary key is zero, that might be something.   let me check

**Comment by zzzeek** [comment]
seems to be no problem there, though still looks suspicious.


are you providing a primary key value of "0" manually?  as an integer?   can you try not using only non-zero numbers and see if that changes?  please try to produce a complete example, thanks.

**Comment by chofsass** [comment]
here is a reproduceable example:
It occurs on the second run using the same database. This makes me believe it is some how associated with the UniqueConstraint.

Is there a recommended way of not using a primary key of non-zero? I figured it would start at zero and increment. maybe I am miss understanding the concern.

```
import queue
import time
import os
import sys
import queue
import sqlalchemy


from sqlalchemy import create_engine, Column, Integer, String, Boolean, Float, ForeignKey, UniqueConstraint
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from threading import Thread

dir_path = os.path.dirname(os.path.realpath(__file__))
Base = declarative_base()

class Example(Base):
    __tablename__ = 'example'

    id = Column(Integer, primary_key=True)
    value1 = Column(Integer, nullable=False)
    value2 = Column(Integer, nullable=False)
    
    __table_args__ = (UniqueConstraint('value1', 'value2', name='_symbol_timestamp_uc', sqlite_on_conflict='IGNORE'),)

    def build_from_tuple(self, tup):
        self.value1 = tup[0]
        self.value2 = tup[1]
        return self

engine = create_engine(f'sqlite:///{dir_path}/data_test.db', echo=False)
Base.metadata.create_all(bind=engine)
Session = sessionmaker(bind=engine)

class DB_Writer(Thread):
    def __init__(self):
        super(DB_Writer, self).__init__()
        self.queue = queue.Queue()
        self.exit_flag = False

    def common_bulk_save(self, instances):
        session = Session()

        try:
            session.add_all(instances)
            session.commit()
        except sqlalchemy.exc.IntegrityError as e:
            session.rollback()
        except Exception as e:
            print(f"Datebase exception while saving: {e}")
        finally:
            session.close()

    def run(self):
        while not self.exit_flag:
            time.sleep(5)

            examples = []

            while not self.queue.empty():
                examples.append(Example().build_from_tuple(self.queue.get()))

            if len(examples):
                self.common_bulk_save(examples)

    def stop(self):
        self.exit_flag = True



if __name__ == "__main__":
    db_writer = DB_Writer()
    db_writer.start()

    try:
        i = 0

        while True:
            db_writer.queue.put((i, i))
            i += 1

            if i%1000 == 0: 
                time.sleep(.5)

    except (KeyboardInterrupt, SystemExit):
        pass

    finally:
        db_writer.stop()
        db_writer.join()
```

**Comment by zzzeek** [comment]
oh.    this is because of the constraint on ignore issue.

When an INSERT is emitted for the row that is already present for that constraint, the INSERT fails silently.  The ORM is not able to proceed correctly in this case because it expects INSERT operations to either succeed or fail with an exception.

the warning here only seems to emit for an "executemany"  operation, so can be reproduced as follows:

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import UniqueConstraint
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class Example(Base):
    __tablename__ = "example"

    id = Column(Integer, primary_key=True)
    value1 = Column(Integer, nullable=False)

    __table_args__ = (UniqueConstraint("value1", sqlite_on_conflict="IGNORE"),)


e = create_engine("sqlite://", echo=True)

Base.metadata.create_all(e)

s = Session(e)


s.add_all([Example(value1=1), Example(value1=2)])

s.commit()

s.close()

# these objects silently fail to be inserted.  the ORM expects INSERT
# to return a newly generated primary key value.
s.add_all([Example(value1=1), Example(value1=2)])

s.commit()


```

I dont know the exact mechanics of how the operation is resulting in this particular scenario but IMO it shouldn't matter because this usage is undefined.    that sort of constraint should not be used with the ORM, you'd have to use Core if you expect to INSERT redundant rows and have them silently ignored.

**Comment by chofsass** [comment]
Is there a way to accomplish this without rewrite a ton of code?

**Comment by zzzeek** [comment]
usually just SELECT the records you wish to insert first then only INSERT for those that aren't present already.

I use an IN for these things, very efficient and database agnostic for the most part:

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import UniqueConstraint
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
from sqlalchemy.sql.expression import tuple_

Base = declarative_base()


class Example(Base):
    __tablename__ = "example"

    id = Column(Integer, primary_key=True)
    value1 = Column(Integer, nullable=False)
    value2 = Column(Integer, nullable=False)

    __table_args__ = (
        UniqueConstraint("value1", "value2", sqlite_on_conflict="IGNORE"),
    )


def bulk_save(session, values):
    existing = set(
        session.query(Example.value1, Example.value2).filter(
            tuple_(Example.value1, Example.value2).in_(values)
        )
    )

    session.add_all(
        [
            Example(value1=value1, value2=value2)
            for value1, value2 in values
            if (value1, value2) not in existing
        ]
    )


e = create_engine("sqlite://", echo=True)

Base.metadata.create_all(e)

s = Session(e)
# save the first ten
bulk_save(s, [(i, i) for i in range(10)])

s.commit()

s.close()

# save the second ten, ignoring the first ten
bulk_save(s, [(i, i) for i in range(20)])

s.commit()


```

**Comment by zzzeek** [comment]
or you can skip the SELECT and use that constraint rule, by using Core for just this insert you're doing:

    session.execute(Example.__table__.insert(), params=[{"value1": v1, "value2": v2} for v1, v2 in values])

since you aren't working with the instances subseuqent to that anyway, you don't actually need objects.
