### ISSUE TITLE
query_class got dropped in 5de0f1cf50cc0170d8ea

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#5981]
there's no tests for query_class in relationship so this got dropped in 5de0f1cf50cc0170d8ea without any notice.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Revert AppenderQuery modifications from ORM** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2606

**Comment by alanhamlett** [comment]
Why is `lazy="dynamic"` legacy? What's the new way to dynamically load large collections?

**Comment by zzzeek** [comment]
> Why is `lazy="dynamic"` legacy? What's the new way to dynamically load large collections?

Hi -

First off note that I'm not yet satisfied with what we are doing here, which may be either a case of having to add more documentation, or maybe more helpers.   So as far as dynamic being "legacy", I would advise not to panic (yet).

The overarching theme of where I want SQLAlchemy to go is away from implicit construction and execution of SQL SELECT statements, besides those that are what I'd call "trivial", e.g. the refresh of an object or the refresh of a collection or related attribute.

A SELECT statement that's not "trivial" is one that has user-specific, per-query criteria inside of it.   The case of the "large related collection" falls under this category.   The general idea, noting that this is only an "ideal", would include:

1. you know that you're writing a SELECT statement  (user writes a query using select() ).  rationale: SQLAlchemy aims to challenge the "you don't need an ORM, just write SQL" critique by pointing out that the select() construct *is* SQL in all the ways that are important.   it is structurally equivalent to SQL in all the fundamental ways.   this is not unlike other relational querying languages like Hibernate HQL.

2. to get results from the statement, it has to be executed  (there's a specific point of .execute(), that's when database IO occurs).  rationale: with the rise of asyncio we've seen how important it is that programmers are always aware of the boundary of where IO is occurring.   The notion of "implicit IO" is beginning to be seen as an antipattern, and in recent years SQLAlchemy has added constructs like "raiseload" which have been very highly requested from users.  So we want to have a very good "no implicit IO anywhere" story, especially as we now have an asyncio API.     The Query object does in fact have "explicit" points at which IO occurs, i.e. iterating it, the .all() method, the .one() method, but the way the object munges together methods that expand the query vs. actually run IO is the pattern SQLAlchemy 2.0 wants to get rid of as much as possible (noting that Query and "dynamic" will still be there in 2.0, these patterns are far too widespread to remove outright).

3. to execute a statement, you have to specify what transactional context you want to be a part of (this .execute() is part of what you are handling in your Session etc).   This addresses the notion that programming patterns that try to hide the Session, hide the transaciton, etc. lead for programs that are difficult to debug and understand.   That said, the Session is a given based on the object you have when you call upon a dynamic relationship, so again "dynamic" sits in this uncomfortable spot.

Existing patterns that can be used instead of dynamic include:

1. for one-to-many, query the objects you want in terms of the many-to-one.    If A -> B is one to many, given A.bs -> List[B], and B.a -> A:

```python
some_a = session.get(A, 1)
some_selection_of_bs = session.execute(
    select(B).where(B.a == some_a).where(B.some_criteria == "foo").order_by(B.date)
)

```

2. Use a one-to-many or many-to-many relationship with lazy=None, then query using with_parent:

```python
some_a = session.get(A, 1)
some_selection_of_bs = session.execute(
    select(B).where(with_parent(some_a, A.bs)).where(B.some_criteria == "foo").order_by(B.date)
)er'

```


the above two patterns are a lot more verbose, and it is more verbose than I'm comfortable with too, since you have the A right there as well as its Session.   But the above two patterns are also extremely clear.    There's a battle over clarity / explicitness vs. convenience right now.    "dynamic" is in a tricky spot.

that's the thinking for now anyway but not much of a hard decision has been made in this area as of yet.

**Comment by alanhamlett** [comment]
Dynamic ∞:∞ collections already require `.all()` to execute, otherwise they return a query object. If dynamic ∞:1 and 1:1 also returned a query object instead of implicitly executing the query, that seems like a good balance between productivity and clarity?

**Comment by zzzeek** [comment]
that's the going theory, but also the Query hits the database when you iterate it..   it's designed to look kind of invisible.   Plus, it has a whole host of result-fetching methods all(), one(), first(), etc. stuck on it which look extremely similar to the ones that are on Result but don't behave the same way at all, that's a huge inconsistency.   

Overall, I have for years wanted there to be **one** way to write a query and execute it, and we had a lot of issues the way Query makes "convenient" decisions, like query(A) returns a list of objects, query(A.id, A.name) returns tuples?  lot of bug reports about that kind of thing.

a solution for dynamic that I'd prefer would include:

1. there's a single method that makes it "run the query"

2. im thinking there's a single name or method that also "gives you the query"

3. you can get the Result interface fully, so things like partitions(), first(), one_or_none() etc. all act consistently

4. you get a select() object that can be fully manipulated like any other select(), e.g. i want to put it into a union, etc.

otherwise, if we want this to act like "a collection that dynamically filters" then I'd want it to be some much more restricted interface (which would probably be in addition to the "explicit" version), like it only does list index and slice operations and maybe sorted(), that is, it's very different from select() / Result objects.   this would be difficult to produce particularly because we can't really make len() do what's expected, so I'm not too keen on this because it's one of those illusory APIs that doesn't actually deliver on its promise.

**Comment by zzzeek** [comment]
Here's a few ideas I had, noting each of these is intended to be just as good with asyncio as without it, this is a key reason .execute() is always separate.    because it seems like "thing that's executing" should be explicit, and especially w/ asyncio things just work better this way (we could have an "await a1.bs.execute_async()" but that seems like it would lead to a lot of messy situations).   there are also things like execution options, parameters, all kinds of things that go along with "im executing a query" and the idea here, if it's going to allow full construction of a select(), should not prohibit any of that stuff nor should it have to invent a whole new way to do all that.

1. select() method on the collection.   we could actually make this work for any kind of loader strategy since we instrument the collection class, we could add a select() method

```
class A:
   #...

   bs = relationship(B, lazy="queryslice")

a1 = session.get(A, 1)

stmt = a1.bs.select().where(B.foo == 'bar')
some_bs = session.execute(stmt).scalars()

```

2. token that can be applied to select() - I like this one a lot except that it will be confusing if the relationship is not the right loader type, and I wish this could work with *all* the lazy strategies but right now `a1.bs` will do a lazyload by default

```

stmt = select(a1.bs).where(B.foo == 'bar')
some_bs = session.execute(stmt).scalars()

```

3. special function that is kind of the same as with_parent() but is in terms of the parent directly

```
stmt = select(collecton(a1).bs).where(B.foo == 'bar')
some_bs = session.execute(stmt).scalars()

```

4. the above might be more succinct and actually easier to implement as

```
stmt = select_collection(a1, "bs").where(B.foo == "bar")
```

5. maybe the ability to do slices is more the important part.    since we do have lazy loads, maybe it's fine if we had slices evaluate the query like lazy="dynamic" does now:

```
bs = a1.bs[5:10]    # <-- runs the SELECT query

```

but there's no filter()/ order_by() etc. with that.    and also it doesnt work with asyncio.   if you're writing out WHERE criteria and all that I think you should have a select() object first.


im thinking about lazy loads in general here and some way to make them look nice w/ asyncio.   no clear idea yet.
