### ISSUE TITLE
Dialect not properly initialized

### ISSUE THREAD

**Issue by johnraz** [sqlalchemy/sqlalchemy#5991]
**Describe the bug**
For a reason I couldn't define so far, the dialect is sometimes wrongly initialized leading to eg: `engine.dialect._has_native_json` being set to `False` instead of `True` using Postgresql and the latest version of pyscopg2.

More than often and without any identifiable pattern the deserialization error shown below happens.

which I tracked to be exactly the same root cause as described in https://github.com/sqlalchemy/sqlalchemy/issues/4807

--> the Dialect is not initialized properly or more likely not initialized at all which leads to JSON fields being deserialized twice --> the second attempt raises the error.

**Expected behavior**

The dialect should be properly initialized and the json field only deserialized once.

**To Reproduce**
I wasn't able to reproduce this with a test case, sadly :(

**Error**

```
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'

  ... I removed some proprietary code traceback here but it's basically accessing some related field on a model...

  File "sqlalchemy/orm/attributes.py", line 294, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "sqlalchemy/orm/attributes.py", line 730, in get
    value = self.callable_(state, passive)
  File "sqlalchemy/orm/strategies.py", line 760, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "sqlalchemy/orm/strategies.py", line 902, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "sqlalchemy/ext/baked.py", line 544, in all
    return list(self)
  File "sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "sqlalchemy/orm/loading.py", line 588, in _instance
    populators,
  File "sqlalchemy/orm/loading.py", line 725, in _populate_full
    dict_[key] = getter(row)
  File "sqlalchemy/sql/type_api.py", line 1275, in process
    return process_value(impl_processor(value), dialect)
  File "sqlalchemy/sql/sqltypes.py", line 2454, in process
    return json_deserializer(value)
  File "json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
```

**Versions.**
 - OS: linux
 - Python: 3.6.12
 - SQLAlchemy: 1.3.23
 - Database: Posgresql 11.7
 - DBAPI: 2.8.6

**Additional context**

In our case the bug triggers in an [Dramatiq](https://dramatiq.io/) setup with a lot of tasks running.

We use [flask-sqlalchemy](https://flask-sqlalchemy.palletsprojects.com/) in combinaison with [flask-melodramatiq](https://flask-melodramatiq.readthedocs.io/).

The two *should*  play well together and the lifespan of a session should be the lifespan of the app context which is created when a task run and disposed of when the tasks is done executing.

Tracing the error in the logs show really no pattern of any kind, it happens on different tasks / different models / different ids and different machines on our cluster.

I also cannot reproduce locally which is making the all thing even harder to diagnose ^^

I have spotted in our codebase an abusive use of `session.bind.dispose()`  in an attempt to limit the number of connections to the DB while a simple `session.commit()` / `session.rollback()` should be enough - I removed that and I'm waiting for a release in the coming days to see if it solved anything - but I figured I would mention it anyway

What I'm looking for now is suggestions or clues of where this initialization might fail in order to narrow an pinpoint the source of the issue.

Thanks for your help 👍

**Comment by johnraz** [comment]
@zzzeek I'm taking the liberty to ping you here as you were handling the related issue 🙏

**Comment by zzzeek** [comment]
has_native_json is determined only when the engine first connects.  it is based on the psycopg2 version, however that's when it gets checked.    you can set it manually to True.   Also, _has_native_json is removed in 1.4 as it is always true for the current supported versions of psycopg2.
