### ISSUE TITLE
we forgot that session.delete() will cascade and load relatonships, needs to be asyncio

### ISSUE THREAD

**Issue by acnebs** [sqlalchemy/sqlalchemy#5998]
Hi, coming from the sync ORM, one of my favorite features is having the ORM handle cascading deletions for me. 

Context: because we want to avoid performing IO if `await` is not specified, the guidance (as per the 1.4 docs) is to eagerly load relationships either when specifying your relationships in the model, or by using the `selectinload` option on a statement.

My issue is that cascading deletions, pretty much by definition, are "eager loading". If I've specified `cascade="all, delete-orphan"` in my relationship, it means when I ask for A to be deleted I want it to automatically delete a B that relies on it, all at the same time. Unlike with a "normal" `select`, there is never an instance where I don't want these relationships to be found and annihilated if I've specified a cascade on the `relationship`.

But with the async ORM as it currently stands, you still need to use `selectinload` (or specify the entire relationship as eager, which usually you don't want to do) in order for cascading deletions to work. This can get pretty hairy if your cascades are many, e.g. if you have a `User` table and want to automatically delete all rows in 3 other tables related to a particularly user, which then relate to rows in more tables, etc.

To illustrate:

```python
import asyncio

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.future import select


Base = declarative_base()


class A(Base):
    __tablename__ = "a"
    __mapper_args__ = {"eager_defaults": True}

    id = sa.Column(sa.Integer, primary_key=True)
    data = sa.Column(sa.String)
    create_date = sa.Column(sa.DateTime, server_default=sa.func.now())


class B(Base):
    __tablename__ = "b"
    id = sa.Column(sa.Integer, primary_key=True)
    a_id = sa.Column(sa.ForeignKey("a.id"))
    a = sa.orm.relationship("A", backref=sa.orm.backref("bs", cascade="all, delete-orphan"))
    data = sa.Column(sa.String)


async def main():
    engine = create_async_engine("postgresql+asyncpg://connor@localhost/test", echo=True)
    async_session = sa.orm.sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        session.add_all(
            [
                A(bs=[B(), B()], data="a1"),
                A(bs=[B()], data="a2"),
                A(bs=[B(), B()], data="a3"),
            ]
        )
        await session.commit()

    # fails
    async with async_session() as session:
        a1 = await session.scalar(select(A).order_by(A.id))
        session.delete(a1)
        await session.commit()

    # works
    async with async_session() as session:
        a1 = await session.scalar(select(A).options(sa.orm.selectinload(A.bs)).order_by(A.id))
        session.delete(a1)
        await session.commit()


asyncio.run(main())
```

So is there a way to cause Async ORM to automatically follow the declared cascades on deletion without manually having to specify `selectinload` for every relationship you want to cascade? And if there isn't, can we add an async method that does, e.g.

```python
async with async_session() as session:
    a1 = await session.scalar(select(A))
    await session.cascading_delete(a1)
    await session.commit()
```

Where `cascading_delete()` obviously eagerly loads all relationships based on associated `cascade=`s and marks them all for deletion within the session.

For what it's worth, I also can't imagine a situation where I *wouldn't* want to do this, so I'd be happy without a new method and for `session.delete()` to always be an async method that does this, rather than its current sync behavior.

Thanks for building a great library and have a nice day!

**Comment by zzzeek** [comment]
WOW, three betas and none of us noticed this.  this is a one liner.   delete needs to be async.  woops!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**convert AsyncSession.delete into awaitable** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2611

**Comment by zzzeek** [comment]
so just a note, this isn't auto-eager-loading the relationships right now, it's just doing the usual lazy load.   it's just it correctly occurs within the awaitable.   i forgot that delete() will follow cascades immediately that can load.

**Comment by CaselIT** [comment]
Thanks, I guess we avoided a 1.4.1 one day after 1.4.0 :)
