### ISSUE TITLE
compositeproperty refresh handler replaces the object more frequently than the mutable version does

### ISSUE THREAD

**Issue by pasbec** [sqlalchemy/sqlalchemy#6001]
**Describe the bug**

Dear sqlalchemy developers,

I'm still just touching the surface of sqlalchemy, Therefore please kindly excuse me if I do not choose the right wording here and there. But I am pretty sure that I have found either a bug or some really strange behavior if an synonym attribute is used to mirror a mutable composite with declarative mapping.

It seems like the very presence of the synonym for some reason interferes with the aliased composite attribute such that the mutability of the composite "gets lost" if a mapped class is queried a second time without refreshing it, rolling it back or committing it in between.

I'll provide a minimal example that easily explains what I tried to explain so far.

**Expected behavior**

The mutability of a mutable composite property should remain unchanged if a corresponding mapped class is used in multiple queries.

**To Reproduce**

Please use this minimal setup and follow the steps below.
```py
engine = create_engine('sqlite://', echo=False)
metadata = MetaData(bind=engine)

class FooBarComposite(MutableComposite):

    def __init__(self, foo, bar):
        self.foo = foo
        self.bar = bar

    def __composite_values__(self):
        return (self.foo, self.bar)

    def __setattr__(self, key, value):
        object.__setattr__(self, key, value)
        self.changed()

Base = declarative_base(metadata=metadata)

class Test(Base):
    
    __tablename__ = "test"
    
    id = Column(Integer, primary_key=True)
    
    foo = Column("foo", String(50))
    bar = Column("bar", Float)
    
    comp = composite(FooBarComposite, foo, bar)
    
    # This is the synonym that causes trouble
    alias = synonym("comp")

metadata.drop_all()
metadata.create_all()

Session = sessionmaker(bind=engine)
session = Session()

session.add(Test(comp=FooBarComposite(foo="a", bar=1.0)))
session.add(Test(comp=FooBarComposite(foo="b", bar=2.0)))
session.add(Test(comp=FooBarComposite(foo="c", bar=3.0)))
session.commit()
```
Using the code above, we can change the foo attribute for the "row" with id=1:
```py
tests = session.query(Test).all()

tests[0].comp.foo = "d"

print({test.id: (test.foo, test.bar) for test in session.dirty})
```
This is reflected correctly in the "dirty" part of the session:
```
{1: ('d', 4.0)}
```
Now let's assume that it is intended not to commit the changes already. If the query is then repeated but this time to change attributes of all rows,
```py
for test in session.query(Test).all():
    print(test.id, (test.comp.foo, test.comp.bar), list(test.comp._parents.values()))
    test.comp.bar = 4.0
    
print({test.id: (test.foo, test.bar) for test in session.dirty})
```
suddenly some underlying columns are not flagged as modified and as shown, some of the composite instances are even missing their parents:
```
1 ('d', 1.0) ['comp']
2 ('b', 2.0) []
3 ('c', 3.0) []
{1: ('d', 4.0)}
```
If all the steps are done after commenting out the line `alias = synonym("comp")` in the Test class above, everything works as expected and the results at the end shows
```
1 ('d', 1.0) ['comp']
2 ('b', 2.0) ['comp']
3 ('c', 3.0) ['comp']
{1: ('d', 4.0), 2: ('b', 4.0), 3: ('c', 4.0)}
```
instead. One could of course argue that an intermediate flush or commit wouldn't hurt. And it would make sense to use just one query instead of those two - sure! But this example has been created after chasing some weird and somewhat random behavior in a larger context. The two queries actually happen in different locations of a library and in different functions, etc...

**Versions.**
 - OS: Windows 10 Enterprise 1909
 - Python: 3.7.9
 - SQLAlchemy: 1.3.23
 - Database: sqlite, postgresql
 - DBAPI: pysqlite, psycopg2

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
feel free to experiment with this,which seems to be the issue

```diff

diff --git a/lib/sqlalchemy/orm/descriptor_props.py b/lib/sqlalchemy/orm/descriptor_props.py
index 65fe58e61..41788071e 100644
--- a/lib/sqlalchemy/orm/descriptor_props.py
+++ b/lib/sqlalchemy/orm/descriptor_props.py
@@ -271,8 +271,10 @@ class CompositeProperty(DescriptorProperty):
         def load_handler(state, *args):
             _load_refresh_handler(state, args, is_refresh=False)
 
-        def refresh_handler(state, *args):
-            _load_refresh_handler(state, args, is_refresh=True)
+        def refresh_handler(state, context, to_load):
+            # note this corresponds to sqlalchemy.ext.mutable load_attrs()
+            if not to_load or set(self._attribute_keys).intersection(to_load):
+                _load_refresh_handler(state, (context, to_load), is_refresh=True)
 
         def _load_refresh_handler(state, args, is_refresh):
             dict_ = state.dict

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**ensure composite refresh handler synced w/ mutable composite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2617

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**ensure composite refresh handler synced w/ mutable composite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2618

**Comment by pasbec** [comment]
Thank you very much for your quick feedback. If I apply your patch manually, the mutable composite seems to work normally again.

I'm really impressed by the both the sqlalchemy package and your dedication to this project. Your software opens up so many possibilities and allows us to interact with an (old) scientific model database in an interactive and very intuitive way.

**Comment by zzzeek** [comment]
thanks very much for your compliments!    they mean a lot to me and to the team.
