### ISSUE TITLE
the reset agent in the pool is no longer needed

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6004]
as I worked on #6002 it became apparent that the connection pool no longer uses the "reset agent" under any circumstances outside of artificial ones in the test suite.  this is likely due to the rework of how transactions work starting with 0e53221eef50b3274841fbd1eb41e .

ideally, the pool reset should be skippable if the connection itself has actively emitted a ROLLBACK on the connection.  this could be achieved through the use of a new method on ConnectionFairy like _close_no_reset().   however, as the original purpose of the "reset agent", which was to use the already opened transaction for rollback, seems to no longer be a possible codepath, we should take out the whole "reset agent" thing altogether.   the test suite for #6002 added some assertions to validate that this is the case.

**Comment by zzzeek** [comment]
the reset agent is also mis-documented, somewhat.  it claims the Transaciton is used to do the rollback if present, and the reset doesn't happen.  but that's only true if the transaction is abandoned, not if its explcitly rolled back.     However, this is a regression in 1.4 because now we are doing a double rollback in this case.  that shouldn't happen .

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Replace reset_agent with direct call from connection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2622
