### ISSUE TITLE
PostgreSQL: Execute INSERT with float params not working

### ISSUE THREAD

**Issue by jgauchel** [sqlalchemy/sqlalchemy#6019]
**Describe the bug**
Executing a raw sql command with session.execute and float param values on a postgresql table with column type "double precision" does not work.

**To Reproduce**
table **user_numbers**: 
| field_name | type | nullable |
| - | - | - |
| id | integer | false |
| user_id | integer | false |
| value1 | double precision | true |
| value2 | double precision | true |
| value3 | double precision | true |

```python
session.execute(
    'INSERT INTO user_numbers (id, user_id, value1, value2, value3) VALUES(:id, :user_id, :value1, :value2, :value3'
    {'id': 1, 'user_id': 1, 'value1': 90, 'value2': 89.9216272997926, 'value3': 90.096095280000014}
)
```

**Expected behavior**
Table user_numbers should have a row with values inserted before. But the table stays empty.

If the float param values gets injected directly into sql string, it works as expected:
```python
value1 = 90
value2 = 89.9216272997926
value3 = 90.096095280000014

session.execute(
    f'INSERT INTO user_numbers (id, user_id, value1, value2, value3) VALUES(:id, :user_id, {value1}, {value2}, {value3}'
    {'id': 1, 'user_id': 1}
)
```

**Versions.**
 - OS: WSL 2
 - Python: 3.8.5
 - SQLAlchemy: 1.3.23
 - Database: PostgreSQL 12

**Have a smooooth day!**

**Comment by jgauchel** [comment]
There is no error (which caused some trouble...)! The table just stays empty after executing the insert sql command. You can check this by running 
```py
session.execute('SELECT * FROM user_numbers')
```
What are you missing to reproduce the case?

**Comment by CaselIT** [comment]
If there is no error and the table is empty you need to call `session.commit()` to commit the transaction.

>What else are you missing to reproduce the case?

a complete runnable script that would have made it clear that commit was missing
