### ISSUE TITLE
mutation extension needlessly (?) requires hashing for objects, why cant we use state?

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6020]
see #6018.

changing to use state instead of obj() and all but one test passes, not sure why yet.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Link to state, not object, for mutable extension** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2626
