### ISSUE TITLE
Support Azure SQL managed identities

### ISSUE THREAD

**Issue by lengau** [sqlalchemy/sqlalchemy#6031]
**Is your feature request related to a problem? Please describe.**
There's no clear way currently to connect to Azure SQL using Microsoft's Managed Identities. After some time working on it, there is a fairly simple way, but it's undocumented

**Describe the solution you'd like**
I wrote some code that helps do it generically. I'd either like this strategy to be integrated into sqlalchemy somehow or for it to be included in the documentation so other people don't have to spend their time figuring this out too. I'm going to make a PR for at least the documentation, and I might try to figure out a way to integrate it into the mssql+pyodbc connector

**Describe alternatives you've considered**
I could put this code into its own package, but that seems like a waste considering how little code it is.

**Additional context**
OK, here's the actual code.

# If you came here looking for a way to implement Azure access tokens with SQLAlchemy, this is it

```python
import struct
from azure import identity
from sqlalchemy import event

SQL_COPT_SS_ACCESS_TOKEN = 1256  # As defined in msodbcsql.h

def inject_azure_credential(credential, engine, token_url='https://database.windows.net/'):
    @event.listens_for(engine, 'do_connect')
    def do_connect(dialect, conn_rec, cargs, cparams):
        token = credential.get_token(token_url).token.encode('utf-16-le')
        token_struct = struct.pack(f'=I{len(token)}s', len(token), token)
        attrs_before = cparams.setdefault('attrs_before', {})
        attrs_before[SQL_COPT_SS_ACCESS_TOKEN] = bytes(token_struct)
        return dialect.connect(*cargs, **cparams)
```

This will generate an event listener that'll inject the token taken from an Azure Credentials object. Usage is as follows:

```python
creds = identity.DefaultAzureCredential()  # Or any other azure credentials. See: https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd
engine = sqlalchemy.create_engine(
    sqlalchemy.engine.url.URL('mssql+pyodbc', query={'odbc_connect': 'DRIVER={ODBC Driver 17 for SQL Server};DATABASE=myDb;server=my-server.database.windows.net'})
)
inject_azure_credential(creds, engine)
```

After setting up the event listener, any connection created with `engine` will get a token and use that. Note that you can't just say `sqlalchemy.create_engine(url, connect_args={'attrs_before': {SQL_COPT_SS_ACCESS_TOKEN: token_struct}})` because the token expires 15 minutes after creation. The Azure credentials object will cache the token and automatically refresh it if necessary when `get_token` is called.

**Have a nice day!**
You too, person who created the feature request template!

**Comment by lengau** [comment]
I'm working on a brief PR to add this to the documentation. I think there's a way to integrate this so one could just run `create_engine(url, azure_credentials=creds)` by modifying `dialects/mssql/pyodbc.py`, but I'll need some guidance on that. If somebody would be willing to point me in the right direction I'd really appreciate it.

**Comment by zzzeek** [comment]
hi there -

can I ask why you can't simply provide these features using the [connect_args](https://docs.sqlalchemy.org/en/13/core/engines.html#use-the-connect-args-dictionary-parameter) parameter?  there should be no need to override the complete connect process.

**Comment by zzzeek** [comment]
cc @gordthompson

**Comment by lengau** [comment]
You can't just say sqlalchemy.create_engine(url, connect_args={'attrs_before': {SQL_COPT_SS_ACCESS_TOKEN: token_struct}}) because the token expires 15 minutes after creation. The Azure credentials object will cache the token and automatically refresh it if necessary when get_token is called.

Because of that, we need to call `get_token` each time a connection is generated to ensure that we get a valid token.

**Comment by CaselIT** [comment]
It seems awfully complicated to require a struct to connect to the db. But I (I guess fortunately) have no  experience with azure sql managed identities in python.

**Comment by lengau** [comment]
> It seems awfully complicated to require a struct to convert the token to then connect to the db.

Yeah, it's not great, but unfortunately it's the only way to provide it right now. I'm actually busy writing a feature request (and probably a PR) for the Azure SDK to have it generate the struct per [their docs](https://docs.microsoft.com/en-us/sql/connect/odbc/using-azure-active-directory?view=sql-server-ver15#authenticating-with-an-access-token). If they accept it, once that change is in a released version of the azure sdk I'll update these docs to simplify it.

**Comment by zzzeek** [comment]
Ok so this thing with services that have time-based tokens, I'm pretty sure more than just Azure has that kind of thing going on.   Again, I'd prefer more general documentation on how to approach problems like these rather than stuffing the docs with lots of ad-hoc specifics that will all have changed in a few years.    

how about an approach where:

1. add a little subsection to https://docs.sqlalchemy.org/en/13/core/engines.html#controlling-how-parameters-are-passed-to-the-dbapi-connect-function that explains that this event is likely the best place to handle things like dynamic, time-based tokens and similar that change each time.  then we show a little bit of an example that is fairly psudoo-codeish, or perhaps the example above but much more succinctly written (for example, no need to call .connect() or return anything)

2. in https://docs.sqlalchemy.org/en/13/dialects/mssql.html#connecting-to-pyodbc, we put a section "dealing with time-based tokens (e.g. Azure Managed Identities, etc), that refers to the general idea of the section in engines.html, and can even copy the example, but should have a "seealso" the **canonical** documentation for this whole access token thing in the pyodbc documentation.


the idea is:

1. the recipe is presented as a techinique to be understood and applied as needed, rather than a magic cut-and-paste

2. we don't assume we are the canonical documentation for how to connect to Azure this year

3. the docs are general and can be referred towards by other dialects with similar kinds of issues.

the above example can be written with less structural overhead as below.   This is not that this is the "better" way to do it, it's just that I want to show the minimum amount of code to make thing happen.   just the other day someone was confused that you could use a decorator on a function inside of a function.   so show less code, illustrate the APi use rather than the specifics:

```python

import struct
from azure import identity
from sqlalchemy import event

SQL_COPT_SS_ACCESS_TOKEN = 1256  # As defined in msodbcsql.h


engine = create_engine(
    "mssql+pyodbc://@my-server.database.windows.net/myDb"
    "?driver=ODBC+Driver+17+for+SQL+Server"
)


@event.listens_for(engine, 'do_connect')
def do_connect(dialect, conn_rec, cargs, cparams):
    creds = identity.DefaultAzureCredential()
    token_url = "https://database.windows.net"

    token = credential.get_token(token_url).token.encode('utf-16-le')
    cparams["attrs_before"] = {
        SQL_COPT_SS_ACCESS_TOKEN: struct.pack(
            f'=I{len(token)}s', len(token), token)
        )
    }




```

**Comment by lengau** [comment]
I'm okay with modifying it that way - I'll work on doing that.

As a side note: The `create_engine` call I've made is also the most straightforward/readable I've been able to come up with. The one in @zzzeek's comment will cause an exception because the `@` causes `create_engine` to provide a `UID` field in the ODBC connection string, which is prohibited when using an access token. (Without the `@` also causes an exception, because it adds the `Trusted_Connection` keyword, which is also prohibited.) This was part of the difficulty I had when first implementing this as although Microsoft's documentation does specify this, it's in a single sentence at the end of [this section](https://docs.microsoft.com/en-us/sql/connect/odbc/using-azure-active-directory?view=sql-server-ver15#authenticating-with-an-access-token).

**Comment by zzzeek** [comment]
well those sound like bugs.     it looks like we do this automatically if username/pw are omitted which seems weird.  that should be changed.

**Comment by zzzeek** [comment]
though...if you pass database it shouldnt do that...

**Comment by lengau** [comment]
My mistake - I misremembered the behaviour from what I was doing earlier this week. It looks like it's treated the same with or without the @, but it adds `Trusted_Connection=Yes` either way (as of 1.4.0b3). It looks like the logic (in the pyodbc connector) is to find a user and add that, or if it can't find a user, check for an Authentication value and add that (also prohibited with access tokens in Microsoft's implementation), or if it can't find that, add "Trusted_Connection=Yes". The only behaviour I can think of that would remedy this and allow use of  standard sqlalchemy connection strings without ruining things for everyone else is to offer a parameter for trusted_connection, but even then it's not a matter of True/False/None (default), since the entire keyword needs to be absent from the connection string. 

If you think it's worth doing, I can open (and probably implement) a feature request for the ability to make sure `Trusted_Connection` isn't present in the generated connection string, but this seems like it's specific to pyodbc+mssql+access tokens, so I'm not sure. It seems like implementing Microsoft's specific implementation of access tokens in MSDialect_pyodbc might be more productive in that case. (The way Azure does this is Microsoft-specific and MSSQL specific. The first other implementation I could find was for [Azure Active Directory with MySQL](https://docs.microsoft.com/en-us/azure/mysql/howto-configure-sign-in-azure-ad-authentication), which passes the token in as the password - a better implementation IMO.)

**Comment by gordthompson** [comment]
> 
> 
> well those sound like bugs. it looks like we do this automatically if username/pw are omitted which seems weird. that should be changed.

That may have been done to accommodate a change in behaviour with SQL Server ODBC drivers connecting to a "regular" SQL Server instance. 

Older drivers (e.g.,`DRIVER=SQL Server`) would assume `Trusted_Connection=yes` if `Trusted_Connection` was not included in the connection string. Therefore an ODBC connection string with no `UID`, no `PWD` and no `Trusted_Connection` would use Windows authentication if possible.

Somewhere along the way the drivers started defaulting to `Trusted_Connection=no` so an ODBC connection string with no `UID`, no `PWD` and no `Trusted_Connection` would use SQL Server authentication and fail with `Login failed for user ''.`. Consequently, for 

```
mssql_pyodbc://@server/db?driver=ODBC+Driver+17+for+SQL+Server
```

we needed to start injecting `Trusted_Connection=yes` into the ODBC connection string in order for the login to succeed.

**Comment by sqla-tester** [comment]
**Alex Lowe** has proposed a fix for this issue in the **master** branch:

**Add documentation for connecting to Azure SQL instances with managed identities** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2632

**Comment by cloudtidings** [comment]
What about supporting Workload Identity? https://github.com/Azure/azure-workload-identity

**Comment by CaselIT** [comment]
It's probably best to open a new use case issue or discussion for new feature request
