### ISSUE TITLE
Is it possible to disable optimisations?

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#6043]
**Describe your question**

Am I right in think that sqlalchemy will deduplicate select and update statements when they don't achieve anything? For example:

```
    async with create_session() as sess:
        world1 = await sess.get(World, 1)
        world1_again = await sess.get(World, 1)
```
I'm assuming the object is cached in the first case, so this results in only 1 SELECT statement sent to the DB?

```
    async with create_session() as sess:
        world = await sess.get(World, 1)
        print(world.randomnumber)  # 2
        world.randomnumber = 2
```
Here, the attribute is being assigned the same value it already has, so I'm assuming no UPDATE statement is sent to the DB?

If that's correct, is there any way to disable these optimisations? It seems they are causing failures for a benchmarking tool, which expect the exact same number of statements to be sent for each run (it uses random values which can result in collisions shown in the above examples).

**Additional context**
https://github.com/TechEmpower/FrameworkBenchmarks/pull/6302#issuecomment-762245556

**Comment by CaselIT** [comment]
Hi,

For the get statement you can refer to the [session.get](https://docs.sqlalchemy.org/en/14/orm/session_api.html?highlight=get#sqlalchemy.orm.Session.get) documentation.
Regarding the update, you can use the update statement directly
