### ISSUE TITLE
correlate_except does not seem to correlate from a CTE or subquery, possibly local to column_property() w aliased()

### ISSUE THREAD

**Issue by quangvnm** [sqlalchemy/sqlalchemy#6060]
Hello,

Firstly, thank you very much for this library, we really appreciate this powerful tool.

**Describe the bug**
In legacy version 1.3, correlate_except is wrong with deferred loading column after CTE expression. In new version 1.4, defer doesn't work as previous version 1.3 so it isn't possible to test if the bug exists.

**Expected behavior**
FROM clause in subquery should take the correct table (correlated subquery) and `defer` in 1.4 should work as intended as previous version 1.3

**To Reproduce**

Firstly, I created a full test script:
```python
from sqlalchemy import Column, ForeignKey, Integer, Text
from sqlalchemy import func, select
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import aliased, column_property, defer, sessionmaker

Base = declarative_base()


class Address(Base):
    __tablename__ = "addresses"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    city = Column(Text)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    name = Column(Text)

    total_addresses = column_property(
        select([func.count(Address.id)])
        .where(Address.user_id == id)
        .correlate_except(Address)
        # .scalar_subquery() # SQLAlchemy 1.4
    )


session = sessionmaker()()

filtered_users = (
    session.query(User)
    .join(Address)
    .filter(Address.city == "somewhere")
    .options(defer(User.total_addresses))
    .cte("filtered_users")
)

filtered_users_alias: User = aliased(User, filtered_users)

paginated_users = (
    session.query(filtered_users_alias)
    .order_by(func.lower(filtered_users_alias.name).asc())
    .limit(25)
    .options(defer("total_addresses"))
    .cte("paginated_users")
)

paginated_users_alias: User = aliased(User, paginated_users)

print(session.query(paginated_users_alias))
```

with legacy 1.3, this script gives:
```sql
WITH filtered_users AS 
(SELECT users.id AS id, users.name AS name 
FROM users JOIN addresses ON users.id = addresses.user_id 
WHERE addresses.city = :city_1), 
paginated_users AS 
(SELECT filtered_users.id AS id, filtered_users.name AS name 
FROM filtered_users ORDER BY lower(filtered_users.name) ASC
 LIMIT :param_1)
 SELECT (SELECT count(addresses.id) AS count_1 
FROM paginated_users 
WHERE addresses.user_id = paginated_users.id) AS anon_1, paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name 
FROM paginated_users
```

This is wrong in subquery:
```sql
SELECT count(addresses.id) AS count_1 
FROM paginated_users 
WHERE addresses.user_id = paginated_users.id) AS anon_1
```

which should be (noted the different FROM clause):

```sql
SELECT count(addresses.id) AS count_1 
FROM addresses 
WHERE addresses.user_id = paginated_users.id) AS anon_1
```

This isn't producible in version 1.4, because defer doesn't work as intended, SQLAlchemy 1.4 gives:
```sql
WITH filtered_users AS 
(SELECT (SELECT count(addresses.id) AS count_1 
FROM addresses 
WHERE addresses.user_id = users.id) AS anon_1, users.id AS id, users.name AS name 
FROM users JOIN addresses ON users.id = addresses.user_id 
WHERE addresses.city = :city_1), 
paginated_users AS 
(SELECT filtered_users.anon_1 AS anon_1, filtered_users.id AS id, filtered_users.name AS name 
FROM filtered_users ORDER BY lower(filtered_users.name) ASC
 LIMIT :param_1)
 SELECT paginated_users.anon_1 AS paginated_users_anon_1, paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name 
FROM paginated_users
```

The column_property is loaded in the very first CTE despite the `defer`. This is the same result as 1.3 if I omit the defer option.

If I don't filter Address in CTE, the subquery is correlated correctly:
```python
filtered_users = (
    session.query(User)
    .options(defer(User.total_addresses))
    .cte("filtered_users")
)

filtered_users_alias: User = aliased(User, filtered_users)

paginated_users = (
    session.query(filtered_users_alias)
    .order_by(func.lower(filtered_users_alias.name).asc())
    .limit(25)
    .options(defer("total_addresses"))
    .cte("paginated_users")
)

paginated_users_alias: User = aliased(User, paginated_users)

print(session.query(paginated_users_alias))
```
gives
```sql
WITH filtered_users AS 
(SELECT users.id AS id, users.name AS name 
FROM users), 
paginated_users AS 
(SELECT filtered_users.id AS id, filtered_users.name AS name 
FROM filtered_users ORDER BY lower(filtered_users.name) ASC
 LIMIT :param_1)
 SELECT (SELECT count(addresses.id) AS count_1 
FROM addresses 
WHERE addresses.user_id = paginated_users.id) AS anon_1, paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name 
FROM paginated_users
```

The reason for which we need to defer the loading of column_property is due to performace purpose, if we defer loading the subquery after the LIMIT clause, Postgres query planner works differently and much much faster.

**Error**

```
Traceback (most recent call last):

File "./src/controllers/site_controller.py", line 180, in list

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/orm/query.py", line 3373, in all

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/orm/query.py", line 3535, in __iter__

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/engine/base.py", line 1011, in execute

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/engine/base.py", line 1317, in _execute_context

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/util/compat.py", line 182, in raise_

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/engine/base.py", line 1277, in _execute_context

File "/tmp/pip-target-sb6aifnf/lib/python/sqlalchemy/engine/default.py", line 609, in do_execute

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) missing FROM-clause entry for table "addresses"
...
```

**Versions.**

* OS: Linux
* Python: 3.6.10
* SQLAlchemy: 1.3.23 / 1.4.0

**Thank you very much!**

**Comment by zzzeek** [comment]
OK this is interesting, I was jumping in ready for a subtle and difficult issue but taking a look I think the incompatibility is that defer() was never expected to work inside of a subquery.        defer is a loader option so it only expects to take place at the top level of a SELECT statement indicating the actual columns to be loaded.

If I remove the defer() from your (very well written!) example, both 1.3 and 1. 4 produce the identical query.   so at least there is no strange subtle issue going on.

It does get a little bit subtle, because if I try to have 1.4 actually take place for the defer() internally, which is not the intent of the API but let's see what happens:

```python
diff --git a/lib/sqlalchemy/orm/context.py b/lib/sqlalchemy/orm/context.py
index 9cfa0fdc6..d56a966f3 100644
--- a/lib/sqlalchemy/orm/context.py
+++ b/lib/sqlalchemy/orm/context.py
@@ -571,9 +571,9 @@ class ORMSelectCompileState(ORMCompileState, SelectState):
 
         self.eager_order_by = ()
 
-        if toplevel and select_statement._with_options:
+#        if toplevel and select_statement._with_options:
+        if select_statement._with_options:
             self.attributes = {"_unbound_load_dedupes": set()}
-
             for opt in self.select_statement._with_options:
                 if opt._is_compile_state:
                     opt.process_compile_state(self)
diff --git a/lib/sqlalchemy/orm/strategy_options.py b/lib/sqlalchemy/orm/strategy_options.py
index f24f42a6b..2058cc4e1 100644
--- a/lib/sqlalchemy/orm/strategy_options.py
+++ b/lib/sqlalchemy/orm/strategy_options.py
@@ -130,9 +130,8 @@ class Load(Generative, LoaderOption):
     _extra_criteria = ()
 
     def process_compile_state(self, compile_state):
-        if not compile_state.compile_options._enable_eagerloads:
-            return
-
+        #$if not compile_state.compile_options._enable_eagerloads:
+        #    return
         self._process(compile_state, not bool(compile_state.current_path))
 
     def _process(self, compile_state, raiseerr):

```

the query is actually more wrong, because it renders the CTEs like 1.3 but then the bottom part is referring to a non-existent column and that is much more buglike, I'd have to dig in a lot more to see what that is about:


```sql

-- 1.4 with modification

WITH filtered_users AS 
(SELECT users.id AS id, users.name AS name 
FROM users JOIN addresses ON users.id = addresses.user_id 
WHERE addresses.city = :city_1), 

paginated_users AS 
(SELECT filtered_users.id AS id, filtered_users.name AS name 
FROM filtered_users ORDER BY lower(filtered_users.name) ASC
 LIMIT :param_1)

 SELECT paginated_users.anon_1 AS paginated_users_anon_1, 
       paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name 
FROM paginated_users

```

but, overall, the whole rearchitecture of the select/query system did not consider attribute loader options like `defer()` to be valid for SELECT statements that aren't actually returning those columns directly; all "defer" decisions are made by the outermost query only.

The new design is obviously more in mind with the relationship loading options like joinedload(), and for things like defer() / load_only(), the decision is a bit more "soft", that is, I can see why this seemed like it should work, and maybe it should emit a warning, not really sure.  

but for now, it's definitely not going to work.   When writing your CTE you need to act like writing SQL, which means you would list out the columns you are looking for:

```python
filtered_users = (
    session.query(User.id, User.name)
    .join(Address)
    .filter(Address.city == "somewhere")
    .cte("filtered_users")
)

filtered_users_alias: User = aliased(User, filtered_users)

paginated_users = (
    session.query(filtered_users_alias.id, filtered_users_alias.name)
    .order_by(func.lower(filtered_users_alias.name).asc())
    .limit(25)
    .cte("paginated_users")
)

```

but at that point, now we get into where I'm confused about this bug report.   "In legacy version 1.3, correlate_except is wrong with deferred loading column after CTE expression. In new version 1.4, defer doesn't work as previous version 1.3 so it isn't possible to test if the bug exists."

OK so, there's a bug in *both* versions, is that what we're getting at ?  

The correlate does work in differently in 1.4, and while this is an odd query I think this is the correct SQL you're looking for:

```sql
WITH filtered_users AS 
(SELECT users.id AS id, users.name AS name 
FROM users JOIN addresses ON users.id = addresses.user_id 
WHERE addresses.city = :city_1), 
paginated_users AS 
(SELECT filtered_users.id AS id, filtered_users.name AS name 
FROM filtered_users ORDER BY lower(filtered_users.name) ASC
 LIMIT :param_1)
 SELECT (SELECT count(addresses.id) AS count_1 
FROM addresses, paginated_users 
WHERE addresses.user_id = paginated_users.id) AS anon_1, paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name 
FROM paginated_users

```

while I always wince when I see "FROM a, b", I guess in this case it's correct, as it's SELECTing out from the paginated_users CTE.  it passes the cartesian product test.

so....just defer() isn't supposed to be used that way, and maybe it should warn or maybe it should allow it, but for now that's how to make it work?

**Comment by quangvnm** [comment]
Thank Mike,

So I misunderstood the expected behavior of `defer`, I'm not against the listing of columns in CTE expression, though it is a table of more than ten columns, so if we want to avoid a self join in main SELECT query (which will affect the performance based on Postgres Query Planner), we have to list every columns in these two CTEs:
``` sql
WITH filtered_users AS 
(
  SELECT users.id AS id, users.name AS name --, 10+ columns
  FROM users JOIN addresses ON users.id = addresses.user_id 
  WHERE addresses.city = :city_1
), 
paginated_users AS 
(
  SELECT filtered_users.id AS id, filtered_users.name AS name --, 10+ columns
  FROM filtered_users ORDER BY lower(filtered_users.name) ASC
   LIMIT :param_1
)
SELECT 
  (
    SELECT count(addresses.id) AS count_1 
    FROM addresses 
    WHERE addresses.user_id = paginated_users.id
  ) AS anon_1,
  paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name --, 10+ columns
FROM paginated_users
```
The rendered Python isn't really pretty because there is a list of 10 columns in each CTE expression. That's why we had opted for `defer`

We had tried the other way to keep Python code clean: we loaded only necessary columns in these CTE, if there are additional filter (which is dynamic based on input) in each CTE after the first, SQLAlchemy will make an automatic cross-join (which isn't intended, we should do a explicit self join for each CTE):
```python
from sqlalchemy import Column, ForeignKey, Integer, Text
from sqlalchemy import func, select
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import aliased, column_property, defer, sessionmaker

Base = declarative_base()


class Address(Base):
    __tablename__ = "addresses"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    city = Column(Text)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    name = Column(Text)
    another_column = Column(Text)

    total_addresses = column_property(
        select([func.count(Address.id)])
        .where(Address.user_id == id)
        .correlate_except(Address)
        # .scalar_subquery() # SQLAlchemy 1.4
    )


session = sessionmaker()()

filtered_users = (
    session.query(User.id, User.name)
    .join(Address)
    .filter(Address.city == "somewhere")
    .cte("filtered_users")
)

filtered_users_alias: User = aliased(User, filtered_users)

paginated_users = (
    session.query(filtered_users_alias)
    # this additional condition will make an implicit cross-join!! We had to make an explicit join here: .join(User, filtered_users_alias.id == User.id)
    .filter(filtered_users_alias.another_column == "another_condition")
    .order_by(func.lower(filtered_users_alias.name).asc())
    .limit(25)
    .options(defer("total_addresses"))
    .cte("paginated_users")
)

paginated_users_alias: User = aliased(User, paginated_users)

# there should be a self join in main SELECT too if we need additional columns which don't exist in CTE expression, else SQLAlchemy will make an implicit cross-join
print(session.query(paginated_users_alias))
```

I don't know if it is clear enough, if we don't have `defer`, we either have to list lots of columns in each CTE expression, or we have to made an explicit join if the next CTE or the main SELECT requires additional columns. The second method will have an impact on PostgreSQL Planner too (worse performance)

__

About your question:
> we get into where I'm confused about this bug report. "In legacy version 1.3, correlate_except is wrong with deferred loading column after CTE expression. In new version 1.4, defer doesn't work as previous version 1.3 so it isn't possible to test if the bug exists."

I thought the `defer` has been changed between 1.3 and 1.4, because in 1.3, defer "seems" to work but correlated query is wrong. If the expected behavior of `defer` concern only main SELECT, then there is no bug, though we'd like a feature request for support loader options for subquery/CTE expression.
__

For your final SQL result from 1.4, it isn't correct, because we search for total addresses **per** user, the value depends on each row, with your query, the total value is the same for every row (this column is correlated to enclosed SELECT)

here is the diff version of you query and what we expected:
```diff
--- old_query.sql	2021-03-16 19:40:20.720453887 +0100
+++ expected_query.sql	2021-03-16 19:40:47.263744799 +0100
@@ -13,7 +13,7 @@
 SELECT 
 	(
 		SELECT count(addresses.id) AS count_1 
-		FROM addresses, paginated_users 
+		FROM addresses 
 		WHERE addresses.user_id = paginated_users.id
 	) AS anon_1, paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name 
 FROM paginated_users
```

Furthermore, we still have dependencies on 1.3 and even with the listing of every column, column_property still refer to wrong table if the table in correlate_except is already refer in subquery/CTE expression:

``` python
from sqlalchemy import Column, ForeignKey, Integer, Text
from sqlalchemy import func, select
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import aliased, column_property, defer, sessionmaker

Base = declarative_base()


class Address(Base):
    __tablename__ = "addresses"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    city = Column(Text)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    name = Column(Text)

    total_addresses = column_property(
        select([func.count(Address.id)])
        .where(Address.user_id == id)
        .correlate_except(Address)
        # .scalar_subquery() # SQLAlchemy 1.4
    )


session = sessionmaker()()

filtered_users = (
    session.query(User.id, User.name)
    .join(Address)
    .filter(Address.city == "somewhere")
    # .options(defer(User.total_addresses))
    .cte("filtered_users")
)

filtered_users_alias: User = aliased(User, filtered_users)

paginated_users = (
    session.query(filtered_users_alias.id, filtered_users_alias.name)
    .order_by(func.lower(filtered_users_alias.name).asc())
    .limit(25)
    # .options(defer("total_addresses"))
    .cte("paginated_users")
)

paginated_users_alias: User = aliased(User, paginated_users)

print(session.query(paginated_users_alias))
```
which still gives the wrong correlated subquery (should be `FROM addresses` instead of `FROM paginated_users`:
```sql
WITH filtered_users AS 
(SELECT users.id AS id, users.name AS name 
FROM users JOIN addresses ON users.id = addresses.user_id 
WHERE addresses.city = :city_1), 
paginated_users AS 
(SELECT filtered_users.id AS id, filtered_users.name AS name 
FROM filtered_users ORDER BY lower(filtered_users.name) ASC
 LIMIT :param_1)
 SELECT (SELECT count(addresses.id) AS count_1 
FROM paginated_users 
WHERE addresses.user_id = paginated_users.id) AS anon_1, paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name 
FROM paginated_users
```


So I think there is still a bug with correlate_except either for 1.3 or 1.4

What do you think?

**Comment by quangvnm** [comment]
I've just made a simple test with Query.subquery(), we have the same issue:

without correlated table in subquery, the main SELECT is correct:
```python
filtered_users = (
    session.query(User.id, User.name)
    # .join(Address)
    # .filter(Address.city == "somewhere")
    .subquery()
)

filtered_users_alias: User = aliased(User, filtered_users)

paginated_users = (
    session.query(filtered_users_alias)
    .order_by(func.lower(filtered_users_alias.name).asc())
    .limit(25)
)

print(paginated_users)
```
```sql
SELECT (SELECT count(addresses.id) AS count_1 
FROM addresses -- <- this FROM clause
WHERE addresses.user_id = anon_2.id) AS anon_1, anon_2.id AS anon_2_id, anon_2.name AS anon_2_name 
FROM (SELECT users.id AS id, users.name AS name 
FROM users) AS anon_2 ORDER BY lower(anon_2.name) ASC
 LIMIT :param_1
```

with correlated table in subquery, the compiled statement becomes wrong:
```sql
SELECT (SELECT count(addresses.id) AS count_1 
FROM (SELECT users.id AS id, users.name AS name 
FROM users JOIN addresses ON users.id = addresses.user_id 
WHERE addresses.city = :city_1) AS anon_2 
WHERE addresses.user_id = anon_2.id) AS anon_1, anon_2.id AS anon_2_id, anon_2.name AS anon_2_name 
FROM (SELECT users.id AS id, users.name AS name 
FROM users JOIN addresses ON users.id = addresses.user_id 
WHERE addresses.city = :city_1) AS anon_2 ORDER BY lower(anon_2.name) ASC
 LIMIT :param_1
```

**Comment by zzzeek** [comment]
> Thank Mike,
> 
> So I misunderstood the expected behavior of `defer`, I'm not against the listing of columns in CTE expression, though it is a table of more than ten columns, so if we want to avoid a self join in main SELECT query (which will affect the performance based on Postgres Query Planner), we have to list every columns in these two CTEs:

OK I sort of get the performance issue, you want to narrow down to 25 rows first before you apply a correlated subquery, overall the pattern of placing a correlated subquery in the SELECT like that is not very popular as it is not that performant, but I see you are trying to work your way out of that by nesting CTEs, which is what leads you do this somewhat unusual case that you are putting the full entity in the CTE itself, that in itself is not too common already.

So defer() was never meant for that and this is why it's not working in 1.3 either.  A means of applying columns from a whole table or entity, minus a subset of columns, is a valid use case, and we can figure something out for that, but at the moment there are lots of ways to approximate this on your end in any case either by being explicit or looping through inspect(User).columns or something like that.    that's not the bigger problem here.


> We had tried the other way to keep Python code clean: we loaded only necessary columns in these CTE, if there are additional filter (which is dynamic based on input) in each CTE after the first, SQLAlchemy will make an automatic cross-join (which isn't intended, we should do a explicit self join for each CTE):

oh, you mean, you would access a column in filtered_users_alias that's in the User model, but not in your CTE? that's the only reason I can think of it doing that.   That's another strange thing to do and it should probably raise an explicit error.  there's certainly no way it could go into the CTE that was defined and then add columns to it, mutating things already declared leads to problems very quickly.


> I don't know if it is clear enough, if we don't have `defer`, we either have to list lots of columns in each CTE expression, 

I think you can automate this for now in the absence of a dedicated function.

def all_cols_but_x(cls, omit_keys):
   return [getattr(cls, key) for key in inspect(cls).column_attrs.keys() if key not in omit_keys]

> 
> I thought the `defer` has been changed between 1.3 and 1.4, because in 1.3, defer "seems" to work but correlated query is wrong. If the expected behavior of `defer` concern only main SELECT, then there is no bug, though we'd like a feature request for support loader options for subquery/CTE expression.
> __
> 
> 
> So I think there is still a bug with correlate_except/column_property either for 1.3 or 1.4
> 
> What do you think?

this case is not explicitly handled by either version of the library.  The correlate feature as im not sure if I mentioned earlier only knows about enclosing SELECT statements.   It does not know how to pull tables out of the inside of a CTE and when I look at the SQL you are trying to get, it looks wrong to me and I'm surprised PostgreSQL allows you to access that "addresses" table from inside of "filtered_users".      I would have to play with that to understand why that works.   I would have expected that inside of a subquery or CTE, the tables on the inside are not accessible on the outside so I dont really understand this one yet.

**Comment by zzzeek** [comment]
OK correction, I had the query wrong in my head.  you want "addresses" in the subquery, and correlate out to paginate_users.   Sure, this is a bug, I can fix it for 1.4.

**Comment by zzzeek** [comment]
> I've just made a simple test with Query.subquery(), we have the same issue:

Keep in mind today I've had about 17 regression emails in one day, so it's difficult for me to apply proper focus to this unusual query we are working with.     Looking at your subq example, the overarching difficulty here is that the aliased() construct expects all the columns in the mapped entity to be available if they are to be queried, and here we are looking for it to reconstruct the contents of total_addresses based on the columns that are in the subquery.   the issue seems to be related to correlate_except.  

If I remove the correlate_except() entirely from the total_addresses, both queries seem to generate correctly, if you can confirm.  Also if I use .correlate(User), that works also (note this requires adding the total_address attribute after the fact).

demo:

```python
from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import func
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import aliased
from sqlalchemy.orm import column_property
from sqlalchemy.orm import sessionmaker

Base = declarative_base()


class Address(Base):
    __tablename__ = "addresses"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    city = Column(Text)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    name = Column(Text)

User.total_addresses = column_property(
        select([func.count(Address.id)])
        .where(Address.user_id == User.id)
        .correlate(User)  # fine either way
        # .scalar_subquery() # SQLAlchemy 1.4
    )


session = sessionmaker()()


def test_one():
    filtered_users = (
        session.query(User.id, User.name)
        .join(Address)
        .filter(Address.city == "somewhere")
        .cte("filtered_users")
    )

    filtered_users_alias: User = aliased(User, filtered_users)

    paginated_users = (
        session.query(filtered_users_alias.id, filtered_users_alias.name)
        .order_by(func.lower(filtered_users_alias.name).asc())
        .limit(25)
        .cte("paginated_users")
    )

    paginated_users_alias: User = aliased(User, paginated_users)

    print(session.query(paginated_users_alias))


def test_two():
    filtered_users = (
        session.query(User.id, User.name)
        .join(Address)
        .filter(Address.city == "somewhere")
        .subquery("paginated_users")
    )

    filtered_users_alias: User = aliased(User, filtered_users)

    paginated_users = (
        session.query(filtered_users_alias)
        .order_by(func.lower(filtered_users_alias.name).asc())
        .limit(25)
    )

    print(paginated_users)
```

output for test one:
```

WITH filtered_users AS 
(
    SELECT users.id AS id, users.name AS name 
FROM users JOIN addresses ON users.id = addresses.user_id 
WHERE addresses.city = :city_1), 

paginated_users AS 
(SELECT filtered_users.id AS id, filtered_users.name AS name 
FROM filtered_users ORDER BY lower(filtered_users.name) ASC
 LIMIT :param_1)

 SELECT paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name, 
 (SELECT count(addresses.id) AS count_1 FROM addresses 
WHERE addresses.user_id = paginated_users.id) AS anon_1 
FROM paginated_users
```

test two:

```
SELECT paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name, 
(SELECT count(addresses.id) AS count_1 FROM addresses 
WHERE addresses.user_id = paginated_users.id) AS anon_1 
FROM (SELECT users.id AS id, users.name AS name 
FROM users JOIN addresses ON users.id = addresses.user_id 
WHERE addresses.city = :city_1) AS paginated_users ORDER BY lower(paginated_users.name) ASC
 LIMIT :param_1

```

can you confirm both queries?  this would be limited to correlate_except() and also might be local to using it inside of a column_property().

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Adjust derivation rules for table vs. subquery against a join** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2640

**Comment by zzzeek** [comment]
no fix yet, this is an old fashioned clause adaption bug, haven't had one of these in a few years in fact.

**Comment by quangvnm** [comment]
Oh, awesome, thank you for an elaborated reply and pointing me to my unusual way of doing CTE query. I didn't know that approach is an anti-pattern. I will rework the query to only load the whole collection in main SELECT and compare the Query Planner Performance, if it didn't change much, it will also avoid the defer/listing issue. (We will keep in mind the `inspect` approach, that is interesting!)

About correlated query issue, I can confirm that 1.4 works very well with `correlate()`. Unfortunately, we are stick to version 1.3 for sometime due to sub-dependencies, and in 1.3, the `addresses` couldn't be listed in FROM clause (unlike 1.4):

```python
filtered_users = (
    session.query(User.id, User.name)
    .join(Address)
    .filter(Address.city == "somewhere")
    .cte("filtered_users")
)

filtered_users_alias: User = aliased(User, filtered_users)

paginated_users = (
    session.query(filtered_users_alias.id, filtered_users_alias.name)
    .order_by(func.lower(filtered_users_alias.name).asc()).limit(25)
    .cte("paginated_users") 
)

paginated_users_alias: User = aliased(User, paginated_users)

print(session.query(paginated_users_alias))
```

```sql
WITH filtered_users AS 
(
  SELECT users.id AS id, users.name AS name 
  FROM users JOIN addresses ON users.id = addresses.user_id 
  WHERE addresses.city = :city_1
),
paginated_users AS 
(
  SELECT filtered_users.id AS id, filtered_users.name AS name 
  FROM filtered_users ORDER BY lower(filtered_users.name) ASC
  LIMIT :param_1
)
SELECT paginated_users.id AS paginated_users_id, paginated_users.name AS paginated_users_name,
  (
    SELECT count(addresses.id) AS count_1 
    WHERE addresses.user_id = :user_id_1
  ) AS anon_1 -- this subquery misses the FROM clause, unlike 1.4
FROM paginated_users
```

___

Edit: after rewokring the query, we arrive at one satisfying result in 1.3, thank Mike:
```python
filtered_users = (
    session.query(User.id, User.name)
    .join(Address).filter(Address.city == "somewhere")
    .cte("filtered_users")
)

filtered_users_alias: User = aliased(User, filtered_users)

paginated_users = (
    session.query(filtered_users_alias.id)
    .order_by(func.lower(filtered_users_alias.name).asc()).limit(25)
    .cte("paginated_users") 
)

paginated_users_alias: User = aliased(User, paginated_users)

print(
    session.query(User)
    .join(paginated_users, User.id == paginated_users_alias.id)
    .order_by(func.lower(User.name).asc())
)
```
```sql
WITH filtered_users AS 
(
  SELECT users.id AS id, users.name AS name 
  FROM users JOIN addresses ON users.id = addresses.user_id 
  WHERE addresses.city = :city_1
), 
paginated_users AS 
(
  SELECT filtered_users.id AS id 
  FROM filtered_users ORDER BY lower(filtered_users.name) ASC
  LIMIT :param_1
)
SELECT users.id AS users_id, users.name AS users_name,
  (
    SELECT count(addresses.id) AS count_1 
    FROM addresses -- <- correct!!
    WHERE addresses.user_id = :user_id_1
  ) AS anon_1 
FROM users JOIN paginated_users ON users.id = paginated_users.id ORDER BY lower(users.name) ASC
```

With this approach, the column_property is loaded correctly, in Query Planner, compared to original planner where we loaded the whole collection in CTE, there are one additional JOIN to `paginated_users` and one ORDER BY, but the performance isn't affected due to limited set of results in `paginated_users`

We are eager to move to 1.4 asap, especially the caching seems promising :)

**Comment by zzzeek** [comment]
> Oh, awesome, thank you for an elaborated reply and pointing me to my unusual way of doing CTE query. I didn't know that approach is an anti-pattern. 

this is not an anti-pattern at all!  you want to write some CTEs and have a correlated subquery, this should work.   It's just not something I've seen tried before.    we should be using more CTEs for things.


> I will rework the query to only load the whole collection in main SELECT and compare the Query Planner Performance, if it didn't change much, it will also avoid the defer/listing issue. (We will keep in mind the `inspect` approach, that is interesting!)

I think you should keep what you have, just take out the correlate_except() for now in 1.4 and it seems to work.


> 
> About correlated query issue, I can confirm that 1.4 works very well with `correlate()`. Unfortunately, we are stick to version 1.3 for sometime due to sub-dependencies, and in 1.3, the `addresses` couldn't be listed in FROM clause (unlike 1.4):

I haven't yet tailored a fix for this but I can try to see how hard it would be to backport.   it's likely the same issue just manifesting differently.

> We are eager to move to 1.4 asap, especially the caching seems promising :)

hopefully!   we have our first bug with that yesterday.
