### ISSUE TITLE
Enum column does not enforce check for inserted values

### ISSUE THREAD

**Issue by antispam2002-github** [sqlalchemy/sqlalchemy#6061]
**Describe the bug**
In a model defining the column with Enum, it is possible to enter arbitrary value into the column

**Expected behavior**
IntegrityError should be raised instead

**To Reproduce**
The following snippet does work as expected with SQLAlchemy 1.3.23 - the second insert fails with an IntegrityError. After upgrading to SQLAlchemy 1.4 the error is not reported anymore, and the count reports 2 records.

```py
import enum

from sqlalchemy import create_engine, Column, Integer, String, Enum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

if __name__ == "__main__":
    engine = create_engine("sqlite:///:memory:", echo=True)
    Base = declarative_base()

    class Choices(enum.Enum):
        ONE = "first choice"
        TWO = "two second"

    class MyTable(Base):
        __tablename__ = 'choices'

        id = Column(Integer, primary_key=True)
        choice = Column(Enum(Choices, name="choices", native_enum=False))

    Base.metadata.create_all(engine)

    session_class = sessionmaker(engine)
    session = session_class()

    session.add(MyTable(id=1, choice=Choices.ONE))
    session.commit()

    session.add(MyTable(id=2, choice="one")). # invalid choice - not in Enum - should rise IntegrityError
    session.commit()

    print(session.query(MyTable).count())
```

**Versions.**
 - OS: macOS 15.7
 - Python: 3.9.2
 - SQLAlchemy: 1.4
 - Database: any
 - DBAPI: any

**Comment by CaselIT** [comment]
Hi,

This is the expected behaviour. The default for `create_constraint` has been changed in 1.4. See https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-22b21b44239fae0edb1b03961bb883d4

**Comment by zzzeek** [comment]
this was a default that flipped , as the constraint causes a lot of complexity with migrations so we'd rather have people opt into it.   just change the flag, which is accepted in 1.3 as well.
