### ISSUE TITLE
[1.4] Correlate and correlate_except calls mapper configure when used in column_property

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6066]
Running the example below in 1.3 would not configure the mapper when a select with `correlate_except` is used in a `column_property`. In 1.4 it's instead called. 
This causes issues while importing classes, since not all files may be imported before mapper configure is called leading to unknown class errors.

**Describe the bug**
```py
import sqlalchemy as sa
import sqlalchemy.orm

try:
    from sqlalchemy.orm import registry
    Base = registry().generate_base()
except ImportError:
    from sqlalchemy.ext.declarative import declarative_base
    Base = declarative_base()

@sa.event.listens_for(sa.orm.Mapper, "after_configured")
def go1():
    print(">> mapper configured")

@sa.event.listens_for(sa.orm.Mapper, "instrument_class")
def go2(mapper, cls):
    print(">> class instrument", cls)

class Bar(Base):
    __tablename__ = "bar"
    id = sa.Column(sa.Integer, primary_key=True)
    foo_id = sa.Column(sa.ForeignKey("foo.id"))

class Foo(Base):
    __tablename__ = "foo"

    id = sa.Column(sa.Integer, primary_key=True)
    barNum = sa.orm.column_property(
        sa.select([sa.func.count(Bar.id)])
        .where(Bar.foo_id == id)
        .correlate_except(Bar)
        .as_scalar()
    )

print("class loaded. call configure_mappers()")
sa.orm.configure_mappers()
print("done")
```

**Expected behavior**
In 1.3 this gets printed:
```
>> class instrument <class '__main__.Bar'>
>> class instrument <class '__main__.Foo'>
class loaded. call configure_mappers()
>> mapper configured
done
```
in 1.4 isntead (ignoring the as_scalar warning)
```
>> class instrument <class '__main__.Bar'>
>> mapper configured
>> class instrument <class '__main__.Foo'>
class loaded. call configure_mappers()
>> mapper configured
done
```

Using the table instead of the class seems to be a viable workaround:
```py
    barNum = sa.orm.column_property(
        sa.select([sa.func.count(Bar.id)])
        .where(Bar.foo_id == id)
        .correlate_except(Bar.__table__)
        .as_scalar()
    )
```

**Versions.**
 - OS: -
 - Python: 3.8
 - SQLAlchemy: master/rel_1_3
 - Database: -
 - DBAPI: -

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
how strange that it's correlate_except() again and not the overall select()

**Comment by CaselIT** [comment]
I've not tried with `correlate` but I would guess it has a similar behaviour.

Well it's a good thing that's only correlate :)

**Comment by zzzeek** [comment]
it's with anything that does inspect, like select(User).   I know why it's doing this.

**Comment by CaselIT** [comment]
I thought it was something similar

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**turn off eager configure_mappers() outside of Query, Load** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2636
