### ISSUE TITLE
items() / values()  methods of sqlalchemy.sql.base.ImmutableColumnCollection removed in 1.4, keys() still present so these can be restored

### ISSUE THREAD

**Issue by datapythonista** [sqlalchemy/sqlalchemy#6068]
**Describe the bug**

There seems to be a regression in 1.4, as `sqlalchemy.table('my_table').columns.items()` was working in 1.3, but not in 1.4.

Not sure if I'm missing something, but I'd expect a deprecation warning if removing this method was planned.

Detected when updating SQLAlchemy in Ibis: https://github.com/ibis-project/ibis/issues/2689

**Expected behavior**

Expecting this same behaviour in 1.4:

```py
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.3.23'
>>> sqlalchemy.table('my_table').columns.items()
[]
```

**To Reproduce**

```py
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.4.0'
>>> sqlalchemy.table('my_table').columns.items()
```

**Error**

```
Traceback (most recent call last):
  File "/home/mgarcia/miniconda3/envs/ibis-dev/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 1150, in __getattr__
    return self._index[key]
KeyError: 'items'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mgarcia/miniconda3/envs/ibis-dev/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 1152, in __getattr__
    util.raise_(AttributeError(key), replace_context=err)
  File "/home/mgarcia/miniconda3/envs/ibis-dev/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
AttributeError: items
```

**Versions.**
 - OS: Linux
 - Python: Python 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:34:10)
 - SQLAlchemy: 1.4
 - Database:
 - DBAPI:

**Comment by zzzeek** [comment]
ColumnCollection has changed to allow for more sequence-like behavior, but as long as it still has a keys() method it should have a items() and values() methods

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Added back ``items`` and ``values`` to ``ColumnCollection`` class.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2638
