### ISSUE TITLE
LegacyRow breaks column names used by abc.Sequence ('index', 'count')

### ISSUE THREAD

**Issue by dwhswenson** [sqlalchemy/sqlalchemy#6074]
**Describe the bug**

`LegacyRow` inherits from `Row` which inherits from `abc.Sequence`. `abc.Sequence` has a method `index`. This means that if a table has a column named `'index'`, that cannot be accessed via `getattr`. Therefore 1.4 breaks behavior that worked in 1.3.

This is also true for columns named `'count'`.

**Expected behavior**

Attribute-based access should work for columns named `'index'` or `'count'`.

**Workaround**

It works if I use `__getitem__`-based access, i.e., `result['index']`.

**To Reproduce**

```py
import sqlalchemy
engine = sqlalchemy.create_engine('sqlite:///:memory:')
metadata = sqlalchemy.MetaData(bind=engine)

fingers = ['thumb', 'index', 'middle', 'ring', 'pinky']
columns = [
    sqlalchemy.Column(finger, sqlalchemy.Integer)
    for finger in fingers
]
table = sqlalchemy.Table('hand', metadata, *columns)
metadata.create_all(engine)

values = {'thumb': 3, 'index': 1, 'middle': 4, 'ring': 1, 'pinky': 5}

with engine.connect() as conn:
    conn.execute(table.insert([values]))

with engine.connect() as conn:
    select_all = conn.execute(table.select())
    result = select_all.fetchone()
    select_all.close()     

print(" ".join([f"{finger}={getattr(result, finger)}" for finger in fingers]))
```

In 1.3:

```
thumb=3 index=1 middle=4 ring=1 pinky=5
```

In 1.4:

```
thumb=3 index=<bound method Sequence.index of (3, 1, 4, 1, 5)> middle=4 ring=1 pinky=5
```

**Versions.**
 - OS: macOS 10.15.7
 - Python: 3.7.3
 - SQLAlchemy: 1.3.6/1.4.0

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Provide special row proxies for count and index** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2642

**Comment by zzzeek** [comment]
thanks for reporting, this will be in the 1.4.1 release.
