### ISSUE TITLE
there is still a BakedQuery used by the Mapper (!!!!)

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6079]
the feature of Mapper that can load a subclass using an IN query was never refactored and still uses a BakedQuery.     This is a huge thing to miss:

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/mapper.py#L3091

that has to get fixed.  there's no "regression" here so it is not top priority but before we get started with 2.0 that has to be reworked to use a lambda statement (or just a plain statement, which would be easier and less prone to bugs).

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**remove lambda caching from loader strategies** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3006
