### ISSUE TITLE
dataclass defaults on mapped base classes overwrite data values

### ISSUE THREAD

**Issue by benpreisler** [sqlalchemy/sqlalchemy#6085]
**Describe the bug**
Any default values set on the dataclass field on the inherited parent dataclass will overwrite data retrieved via a SELECT and will overwrite populated data when doing an INSERT

**Expected behavior**
dataclass defaults do not overwrite set data on properties

**To Reproduce**
```py
from dataclasses import dataclass
from dataclasses import field

from sqlalchemy import Column, VARCHAR, INTEGER, create_engine
from sqlalchemy.orm import registry, sessionmaker

mapper_registry = registry()
engine = create_engine('MY_URL', echo=True, future=True)
Session = sessionmaker(engine, expire_on_commit=False)


@mapper_registry.mapped
@dataclass
class MyBaseEntity:
    __sa_dataclass_metadata_key__ = "sa"
    my_base_field: str = field(metadata={"sa": Column(VARCHAR)}, default=None)
    my_version: int = field(metadata={"sa": Column(INTEGER)}, default=1)
    __mapper_args__ = {"version_id_col": my_version}


@mapper_registry.mapped
@dataclass
class MyEntity(MyBaseEntity):
    __tablename__ = "my_entity"
    my_uuid: str = field(metadata={"sa": Column(VARCHAR(36), primary_key=True)}, default=None)
    my_field: int = field(metadata={"sa": Column(INTEGER)}, default=None)


my_entity = MyEntity(
    my_uuid='bef0f282-811f-4125-a3ed-4f4d296e7209', my_field=20,  my_base_field='value_1', my_version=2)

with Session() as session:
    with session.begin():
        session.add(my_entity)
```

**Error**
Before add:
`MyEntity(my_uuid='bef0f282-811f-4125-a3ed-4f4d296e7209', my_field=20,  my_base_field='value_1', my_version=2)`

After add:
`MyEntity(my_uuid='bef0f282-811f-4125-a3ed-4f4d296e7209', my_field=20,  my_base_field=None, my_version=1)`

**Versions.**
 - OS: MacOS Catalina 10.15.7
 - Python: 3.8.6
 - SQLAlchemy: 1.4.1
 - Database: postgres 12
 - DBAPI: psycopg2

**Have a nice day!**

**Comment by zzzeek** [comment]
hi your example doesn't run, the MyBaseEntity doesn't have a __tablename__ nor does it have __abstract__ so im not sure what is intended, can yo make sure the example runs completely?  thanks

**Comment by zzzeek** [comment]
if I set it up like this:

```python
@mapper_registry.mapped
@dataclass
class MyBaseEntity:
    __sa_dataclass_metadata_key__ = "sa"

    __abstract__ = True
    my_base_field: str = field(metadata={"sa": Column(VARCHAR)}, default=None)
    my_version: int = field(metadata={"sa": Column(INTEGER)}, default=1)
    __mapper_args__ = {"version_id_col": my_version}

```

then run the program like this:

```
mapper_registry.metadata.create_all(engine)

print(my_entity)
with Session() as session:
    with session.begin():
        session.add(my_entity)

print(my_entity)

```

I dont see the behavior you're seeing:

```
MyEntity(my_base_field='value_1', my_version=2, my_uuid='bef0f282-811f-4125-a3ed-4f4d296e7209', my_field=20)
2021-03-18 13:48:53,840 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-03-18 13:48:53,841 INFO sqlalchemy.engine.Engine INSERT INTO my_entity (my_uuid, my_field) VALUES (?, ?)
2021-03-18 13:48:53,841 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ('bef0f282-811f-4125-a3ed-4f4d296e7209', 20)
2021-03-18 13:48:53,841 INFO sqlalchemy.engine.Engine COMMIT
MyEntity(my_base_field='value_1', my_version=2, my_uuid='bef0f282-811f-4125-a3ed-4f4d296e7209', my_field=20)

```

**Comment by zzzeek** [comment]
that said, I'm doing it wrong because the columns are not getting pulled in from the base class, so that's something else I guess, not sure what's happening there.

**Comment by zzzeek** [comment]
so that's a different bug - allowing dataclasses as abstract classes and mixins.

**Comment by benpreisler** [comment]
ok - yeah I confused myself looking at the output from a later select instead of the INSERT

I am seeing the same as you - the columns are being dropped from the INSERT if I have the dataclass default set - it works if no defaults set.

and fyi in case it's important: you mentioned __abstract__ causing it to not work but my code (without the defaults) is working with or without the __abstract__ = True

(As I understand it though not having __abstract__ will become an issue when I use this MyBaseEntity in other child classes)

**Comment by zzzeek** [comment]
yes so since this is mapping with a decorator, you don't need the ``__abstract__``, but you would have to omit the `@mapped` part, `@mapped ` will be looking for a ``__tablename__``.

so the next part, where columns don't get mapped, that's fixed in #6093.

is that the whole thing?  then we can close this. let me know.

**Comment by benpreisler** [comment]
yep - fix 6093 looks like it covers the issue.  Thanks for all the direct dataclass integration btw - it's much appreciated!

**Comment by zzzeek** [comment]
people had to complain for a long time and we still have the whole pydantic thing to work out but yeah!
