### ISSUE TITLE
v1.4: query.selectable attribute does not exist if no results

### ISSUE THREAD

**Issue by theoturner** [sqlalchemy/sqlalchemy#6088]
**Describe the bug**
As of v1.4, query objects no longer have the attribute `.selectable` if the query has no results. In v1.3 they do.

**Expected behavior**
Query objects always have the attribute `.selectable`.

**To Reproduce**

Create any query which would produce no results, e.g. `db.query(TableObj).filter(TableObj.id == -1)` and access `query.selectable`.

**Error**

```
AttributeError: 'Query' object has no attribute 'selectable'
```

**Versions**
 - OS: Ubuntu 18.04 and MacOS 11.2
 - Python: 3.8
 - SQLAlchemy: 1.4
 - Database: Postgres 12.5
 - DBAPI: FastAPI
 
 **Temporary workaround**
 
 Roll back to v1.3.

**Comment by zzzeek** [comment]
OK I was a little unclear what this was but I see it is just `__clause_element__()`, you can call that method directly for now, it's the same.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Restore Query.selectable** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2646
