### ISSUE TITLE
The standard one-to-one relationship with eager loading raises a 2.0 deprecation warning

### ISSUE THREAD

**Issue by jamespfennell** [sqlalchemy/sqlalchemy#6115]
**Describe the bug**

I have a one-to-one relationship set up exactly as in [the basic relationships documentation](https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html#one-to-one), except that I have configured the relationship to have joined loading on both sides. When I try to insert two elements in a certain way, I get a 2.0 deprecation warning: "using strings to indicate column or relationship paths in loader options is deprecated". Given that I'm using code straight out of the docs, I think this warning is a bug.

**Expected behavior**

No warnings are issued and in version 2.0 the elements can be operated on exactly as in version 1.4.

**To Reproduce**

Run the following code with `SQLALCHEMY_WARN_20=1 python -W always::DeprecationWarning file_name.py`:
```py
from sqlalchemy import Column, create_engine, Integer, ForeignKey
from sqlalchemy.orm import relationship, declarative_base, Session


Base = declarative_base()


# Parent and Child are exactly as in the one-to-one example in the docs,
# except lazy="joined" is added to the relationships
# https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html#one-to-one
class Parent(Base):
    __tablename__ = "parent"
    id = Column(Integer, primary_key=True)
    child_id = Column(Integer, ForeignKey("child.id"))
    child = relationship("Child", back_populates="parent", lazy="joined")


class Child(Base):
    __tablename__ = "child"
    id = Column(Integer, primary_key=True)
    parent = relationship(
        "Parent", back_populates="child", lazy="joined", uselist=False
    )


engine = create_engine("sqlite://", echo=True)
Base.metadata.create_all(engine)

with Session(engine) as session:
    parent = Parent()
    session.add(parent)
    session.flush()  # Without the flushes, no warning is issued

    child = Child()
    session.add(child)
    session.flush()

    # The next line raises a sqlalchemy.exc.RemovedIn20Warning warning
    parent.child = child

    session.commit()

```

**Error**

```
RemovedIn20Warning: Using strings to indicate column or relationship paths in loader options is deprecated and will be removed in SQLAlchemy 2.0.  Please use the class-bound attribute directly. (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
  cloned._generate_path(self.path, attr, strategy, wildcard_key)
```

**Versions.**
 - OS: Ubuntu 20.04
 - Python: 3.8.6
 - SQLAlchemy: 1.4.2
 - Database: in memory SQLite; first observed in an application using Postres
 - DBAPI: the defaults for SQLite and Postgres

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Remove internal use of string attr in loader option** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2665

**Comment by zzzeek** [comment]
thanks for reporting

**Comment by jamespfennell** [comment]
My pleasure; thank you for fixing!
