### ISSUE TITLE
Removal of ResultProxy in 1.4 is a breaking change

### ISSUE THREAD

**Issue by thomasfulton** [sqlalchemy/sqlalchemy#6118]
Classes shouldn't be removed between minor versions as it has the potential to spontaneously break projects (e.g. mine)

**Comment by sigmavirus24** [comment]
The class still appears to be [in the library](https://github.com/sqlalchemy/sqlalchemy/blob/a22b4dfbc44c78cb4fce27c33cf74cf57878a3b1/lib/sqlalchemy/engine/cursor.py#L1836) and the new and better [objects claim backwards compatibility](https://github.com/sqlalchemy/sqlalchemy/blob/fb9099d8c4b0bca350d1a88e22fcfb6a8f2d079d/doc/build/changelog/migration_14.rst#new-result-object) so I'm not sure this issue, as written is valid.

**Comment by CaselIT** [comment]
Hi,

Sqlalchemy does not follow sember, so the change 1.3 -> 1.4 is a major version in sqlalchemy, as it has always being.
Changes in the same series 1.3.x and 1.4.x are in general compatible between them, but there may be some small incompatible changes in some cases.
