### ISSUE TITLE
Allow ``.columns`` on CTE

### ISSUE THREAD

**Issue by scnerd** [sqlalchemy/sqlalchemy#6127]
**Is your feature request related to a problem? Please describe.**
When I call ``.columns`` on a ``CTE`` object, I get the following warning:

```
  /opt/conda/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py:2836: SADeprecationWarning: The SelectBase.c and SelectBase.columns attributes are deprecated and will be removed in a future release; these attributes implicitly create a subquery that should be
 explicit.  Please call SelectBase.subquery() first in order to create a subquery, which then contains this attribute.  To access the columns that this SELECT object SELECTs from, use the SelectBase.selected_columns attribute. (deprecated since: 1.4)
    return self.c
```

However, subquerying a CTE produces a new relation/anonymous table/selectable, and thus the ``.columns`` become bound to that subquery rather than the CTE. Combining such columns in a SELECT with columns bound to the CTE produces cartesian joins because they're different named relations.

**Describe the solution you'd like**
It seems that ``.columns`` should work on a CTE just like it would on a subquery or table, and should be supported, non-deprecated behavior.

**Describe alternatives you've considered**
Convert the CTE to a subquery and use that exclusively.

I also tried following the warning's suggestion of using ``selected_columns``, but these columns are then bound to the CTE's source table and not to the CTE's columns.

**Additional context**
I'm following the migration guide to 2.0 syntax via 1.4. This deprecation warning isn't explicitly tagged as a 2.0 deprecation, though.

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

CTE has .c and .columns as it is just like a subquery, and there has been no change here, see below.   The error you describe is that you are calling upon .c. on a Select object, not a CTE, which will deliver very poor results in SQLAlchemy 1.3 and earlier which is why this misleading accessor has been removed.   Please provide an [MCVE](http://stackoverflow.com/help/mcve) so that we know what you are doing.  thanks!

```python
>>> from sqlalchemy import table, column, select
>>> t1 = table('t', column('q'))
>>> s1 = select(t1).cte()
>>> s2 = select(s1.c.q).where(s1.c.q == 5)
>>> print(s2)
WITH anon_1 AS 
(SELECT t.q AS q 
FROM t)
 SELECT anon_1.q 
FROM anon_1 
WHERE anon_1.q = :q_1
>>> s2 = select(s1.columns.q).where(s1.columns.q == 5)
>>> print(s2)
WITH anon_1 AS 
(SELECT t.q AS q 
FROM t)
 SELECT anon_1.q 
FROM anon_1 
WHERE anon_1.q = :q_1

```

**Comment by scnerd** [comment]
This is correct, I was mistakenly calling .columns elsewhere in my code on a non-CTE object and associating that warning with this snippet. Thanks for the quick help.

**Comment by aymsaleem** [comment]
Had the same issue today - was missing a CTE. Thank you 👍
