### ISSUE TITLE
regression where .metadata is assigned to the cls

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6128]
The code at https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/decl_base.py#L784 is no longer looking for cls.metadata and that's a regression.  if there is cls.metadata we need to use that and this is documented at https://docs.sqlalchemy.org/en/14/orm/declarative_config.html#abstract .   not sure why there's no tests for this.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use class-local metadata for declarative base** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2674
