### ISSUE TITLE
Make it possible to used callable objects for the `back_populates` in the `relationship` function

### ISSUE THREAD

**Issue by dvaerum** [sqlalchemy/sqlalchemy#6130]
**Is your feature request related to a problem? Please describe.**
When one uses the relationship() function it is possible, in the first argument, to use both a `str` or `lambda` function to select a `class` (which I really like), but this is not possible with `back_populates`, here it is only possible to use `str` 😢 

```python
class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)

    # Exmaple
    children = relationship("Child", back_populates="parent")
    # or
    children = relationship(lambda: Child, back_populates="parent")

class Child(Base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('parent.id'))
    
    # Exmaple
    parent = relationship("Parent", back_populates="children")
    # or
    parent = relationship(lambda: Parent, back_populates="children")
```

**Describe the solution you'd like**
I have looked at the code used to handle `self.argument` if is callable (see upper example) and based on this it doesn't look difficult to make something simulate for `back_populates`
https://github.com/sqlalchemy/sqlalchemy/blob/a63b23392fc31766e32b8650127d9006ee189a0f/lib/sqlalchemy/orm/relationships.py#L2082-L2117

if we replace the code at
https://github.com/sqlalchemy/sqlalchemy/blob/a63b23392fc31766e32b8650127d9006ee189a0f/lib/sqlalchemy/orm/relationships.py#L2471-L2472
with
```python
        if self.back_populates:
            if isinstance(self.back_populates, util.string_types):
                back_populates = self.back_populates

            elif callable(self.back_populates):
                back_populates = self.back_populates()

            else:
                back_populates = self.back_populates

            if isinstance(back_populates, InstrumentedAttribute):
                back_populates = back_populates.key

            self._add_reverse_property(back_populates)
```
it would be possible to do the following
```python
class Parent(Base):
...
    children = relationship(lambda: Child, back_populates=lambda: Child.parent)

class Child(Base):
...
    parent = relationship(lambda: Parent, back_populates=lambda: Parent.children)
```

**Describe alternatives you've considered**
I don't really know of any alternative, and I have not been able to find any when searching for examples. Most of the examples I have found don't even use `lambda` for the first argument (what becomes `self.argument`).

**Additional context**
I am up for trying to make a pull request, but your guide say to make an issue first, so that is what I have done 😃 
https://www.sqlalchemy.org/develop.html#pullrequests
Also, if there is a better way for doing this I don't know about I am happy to learn, I am just getting started with SQLAlchemy

**Have a nice day!**

**Comment by zzzeek** [comment]
hi -

back_populates doesn't need any information other than the string, and you should get an error message if the attribute name does not actually resolve to another relationship.     I don't see what advantage there is to replace a simple string with a lambda to another attribute that doesn't exist yet, and additionally it may be very difficult to make the bi-directional dependency behavior work out when both relationships are still being initialized.   this would add lots of complexity and I don't see the rationale.

**Comment by dvaerum** [comment]
For me, the appeal is that it is easy to see which table/class the column comes from, also it makes it easy for an IDE to highlight the associated variables when one select a variable, but maybe that is not a good enough reason.
Didn't know that it would add lots of complexity :neutral_face:

**Comment by zzzeek** [comment]
you can see the class it comes from directly:

    bars = relationship("Bar", back_populates="foo")

allowing the full class introduces new failure modes, the IDE wouldn't know how to tell you this either:

   class Foo:
       bars = relationship("Bar", back_populates=lambda: Bat.foo)   # <-- nonsensical

My advice would be spend some time just using SQLAlchemy as it is right now and then you'll likely decide that some other things are more important on your mind to be improved rather than this one, and maybe we can do those :)

**Comment by dvaerum** [comment]
Okay, thanks for replying, I will close the issue
