### ISSUE TITLE
Implement multiple column `MATCH (X, Y) AGAINST`

### ISSUE THREAD

**Issue by kai3341** [sqlalchemy/sqlalchemy#6132]
**Is your feature request related to a problem? Please describe.**
SQLAlchemy API allows to match only single column, but fulltext index may be created on many columns

**Describe the solution you'd like**
* match multiple columns
* allow to `ORDER BY` match score

**Describe alternatives you've considered**
This feature can be implemented outside SQLAlchemy like now in my project, but why?

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

can you please supply more details for this including:

1. what does the exact syntax look like in SQL
2. is this part of the SQL standard? or is this specific to a particular database backend?  link to documentation 
3. API usage example


I see you submitted a PR but it has many problems, no tests, not clear why the existing match() method was not altered.

**Comment by zzzeek** [comment]
> It looks like it's not SQL standard, it's particular database backend:
> https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html
> 
> My current API idea is:
> 
> ```
> match_expr = match(
>     users_table.c.firstname,
>     users_table.c.lastname,
>     against="John Connor",
> )
> 
> stmt = select(users_table)\
>     .where(match_expr.in_boolean_mode())\
>     .order_by(match_expr)
> ```
> 
> So, `match` should have following methods / properties:
> 
>     * in_natural_language_mode
> 
>     * in_natural_language_mode_with_query_expansion
> 
>     * in_boolean_mode
> 
>     * with_query_expansion
> 
> 
> Hmmm. How I see `with_query_expansion` should be custom method:
> 
>     * in_natural_language_mode
> 
>     * in_boolean_mode
> 
>     * with_query_expansion
> 
> 
> And then check is it correct to call `with_query_expansion`:
> 
> ```
> match_expr = match(
>     users_table.c.firstname,
>     users_table.c.lastname,
>     against="John Connor",
> )
> 
> stmt = select(users_table)\
>     .where(match_expr.in_boolean_mode)\
>     .order_by(match_expr.in_natural_language_mode.with_query_expansion)
> ```

OK.  The existing match() operator accepts keyword arguments, and Ithis could simply be part of that.  The other way would be to use the match() function you've proposed, but it would be imported from sqlalchemy.dialects.mysql.      However I think this is easy enough to just be keyword arguments as this is not an often-requested feature.    The convention right now is <dbname>_option, as you can note in Postgresql: https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#full-text-search  

so here, the code change could be completely within the MySQL visit_match() function alone and the API would be:


```python
match_expr = users_table.c.firstname.match(
   "John Connor",
   mysql_additional_cols=[users_table.c.lastname]
)

match_expr = users_table.c.firstname.match(
   "John Connor",
   mysql_natural_language=True,
   mysql_query_expansion=True,
   mysql_additional_cols=[users_table.c.lastname]
)

```
right now "boolean mode" is the default.

You could always build a match() constrcut as you describe that runs on top of the above operator in any case.


existing tests for MySQL match are in https://github.com/sqlalchemy/sqlalchemy/blob/master/test/dialect/mysql/test_compiler.py#L418

**Comment by kai3341** [comment]
Anyway, the `match()` function uses `.match()` operator, and I have to extend `.match()` operator.

> `mysql_additional_cols=[users_table.c.lastname]`

Useless. Columns can be united into batch via ` sqlalchemy.sql.elements.ClauseElementBatch`.

Other flags are OK, and I'll do it by this way.

Than about `match()` function. I want to make it as close to sql `MATCH` operator as possible. So, could you give me advice about code example to implement such `match()` function behavior:

```
match_expr = match(
    users_table.c.firstname,
    users_table.c.lastname,
    against="John Connor",
)

stmt = select(users_table)\
    .where(match_expr.in_boolean_mode)\
    .order_by(match_expr.in_natural_language_mode.with_query_expansion)
```

**Comment by zzzeek** [comment]
> Anyway, the `match()` function uses `.match()` operator, and I have to extend `.match()` operator.
> 
> > `mysql_additional_cols=[users_table.c.lastname]`
> 
> Useless. Columns can be united into batch via ` sqlalchemy.sql.elements.ClauseElementBatch`.

sorry I'm not following.    the information is present, the visit_match method in mysqlcompiler can interpret it to produce the desired string.   The complexity of `ClauseElementBatch` is not necessary.

> 
> Than about `match()` function. I want to make it as close to sql `MATCH` operator as possible. So, could you give me advice about code example to implement such `match()` function behavior:
> 
> ```
> match_expr = match(
>     users_table.c.firstname,
>     users_table.c.lastname,
>     against="John Connor",
> )
> 
> stmt = select(users_table)\
>     .where(match_expr.in_boolean_mode)\
>     .order_by(match_expr.in_natural_language_mode.with_query_expansion)
> ```

you would implement a class that maintains state as you need and then calls upon the real operator when needed:

```
class match(ColumnElement):
    def __init__(self, *cols, **flags):
        self.cols = cols
        self.flags = flags

    @property
    def in_natural_language_mode(self):
        self.flags["mysql_natural_language"] = True
        return self

    @property
    def with_query_expansion(self):
        self.flags["mysql_natural_language"] = True
        return self


from sqlalchemy.ext.compiler import compiles


@compiles(match, "mysql")
def visit_match(element, compiler, **kw):
    return compiler.process(
        element.cols[0].match(
            additional_columns=element.cols[1:], **element.flags
        ),
        **kw
    )

```

**Comment by cyrileye** [comment]
Hello! We need this multi-column match support for filtering and ordering in our project. 👍 
Is there any ETA on this?
If not, is there a work-around that can be implemented?

**Comment by CaselIT** [comment]
Hi,

> Is there any ETA on this?

Not at the moment. PR are always welcome.

> If not, is there a work-around that can be implemented?

You can use text to render that part of the query. Also I'm not familiar with how match with multiple columns works, but it it's equivalent you can just concatenate the two column before calling match?

**Comment by zzzeek** [comment]
there's a PR for this, it just needs a few tweaks and the contributor hasn't come around yet.   PR is at #6133.   Anyone can pick this up again.

**Comment by CaselIT** [comment]
> 
> 
> there's a PR for this, it just needs a few tweaks and the contributor hasn't come around yet. PR is at #6133. Anyone can pick this up again.

missed it.

**Comment by cyrileye** [comment]
Thanks @CaselIT 
Yeah, there seems to be a PR in progress https://github.com/sqlalchemy/sqlalchemy/pull/6133/ but I'm afraid I'm not familiar enough with the implementation to pick this up right now.
Thank you for the workaround suggestions, but I'm not super clear about how to go about them. It'd be most appreciated if you could elaborate a bit or provide supporting links.
How would I "text to render that part of the query"?
MATCH AGAINST works pretty much the same with multiple columns. MATCH just takes a list of columns instead of one. How would I concatenate columns dynamically in a single arg to match()?

**Comment by CaselIT** [comment]
> How would I "text to render that part of the query"?

`text` here refers to https://docs.sqlalchemy.org/en/14/core/sqlelement.html?highlight=text#sqlalchemy.sql.expression.text
If the columns are fixed you can just do something like this
```py
q = sa.select(...).where(sa.text("MATCH(col1, col2) AGAINST(:query)").bindparams(query="my-query"))
```

> MATCH AGAINST works pretty much the same with multiple columns. MATCH just takes a list of columns instead of one. How would I concatenate columns dynamically in a single arg to match()?

By using the concatenate function https://docs.sqlalchemy.org/en/14/core/operators.html#string-alteration
so something like this
```py
concat = None
for c in column_list:
  concat = c if concat is None else concat + c
q = sa.select(...).where(concat.match('my query'))
```
But I don't know if this is actually equal with a match with multiple columns

**Comment by sqla-tester** [comment]
**Anton Kovalevich** has proposed a fix for this issue in the **master** branch:

**Implement an `sqlalchemy.sql.expression.match` expression** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2858
