### ISSUE TITLE
Table silently fails if args are sent as kws and .columns fails if the table  has no columns

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6135]
```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import Table
from sqlalchemy.schema import Table

engine = create_engine("sqlite://")
t = Table("t", MetaData(), Column("q", Integer))
t.create(engine)

# works
t2 = Table("t", MetaData(), autoload_with=engine)
t2.c


# fails to reflect or raise for arg style, reports attribute error
# for .c
t3 = Table(name="t", metadata=MetaData(), autoload_with=engine)
t3.c

```

**Comment by CaselIT** [comment]
This is the issue: https://github.com/sqlalchemy/sqlalchemy/blob/dff9fe0453d16d0bbb1991628258e4e3ff5f336e/lib/sqlalchemy/sql/schema.py#L549-L551

We also have another instance of this pattern: https://github.com/sqlalchemy/sqlalchemy/blob/dff9fe0453d16d0bbb1991628258e4e3ff5f336e/lib/sqlalchemy/sql/annotation.py#L148-L150

is the fix to check `not args and not kwargs` ?

**Comment by zzzeek** [comment]
> This is the issue:
> 
> https://github.com/sqlalchemy/sqlalchemy/blob/dff9fe0453d16d0bbb1991628258e4e3ff5f336e/lib/sqlalchemy/sql/schema.py#L549-L551
> 
> We also have another instance of this pattern:
> 
> https://github.com/sqlalchemy/sqlalchemy/blob/dff9fe0453d16d0bbb1991628258e4e3ff5f336e/lib/sqlalchemy/sql/annotation.py#L148-L150
> 
> is the fix to check `not args and not kwargs` ?

looks like a good start, yes

**Comment by CaselIT** [comment]
this is actually a 1.3

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Table arguments name and metadata are positional only** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2711

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Table arguments name and metadata are positional only** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2712
