### ISSUE TITLE
in lastrowid TypeError: handle_exception() missing 1 required positional argument: 'err'

### ISSUE THREAD

**Issue by jtzero** [sqlalchemy/sqlalchemy#6138]
**Describe the bug**
lastrowid (and rowcount) exception handler sends the wrong number of arguments to the cursor_strategy.handle_exception
method call:  https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/engine/cursor.py#L1648
method definition: https://github.com/sqlalchemy/sqlalchemy/blob/f62e0c0c7fc4be842a0f4dc4f59019b3c6285fee/lib/sqlalchemy/engine/cursor.py#L936
  
handle_exception argspec `FullArgSpec(args=['self', 'result', 'dbapi_cursor', 'err'], varargs=None, varkw=None, defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})`

**Expected behavior**

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

a cursor_strategy that lacks an implementation of lastrowid

```py
from collections import namedtuple
from sqlalchemy.testing import mock
from sqlalchemy.engine.cursor import BaseCursorResult, CursorFetchStrategy

context = mock.Mock()
del context.get_lastrowid

BaseCursorResult(context, CursorFetchStrategy() , None).lastrowid
```

**Error**

```
Traceback (most recent call last):
  File "/Users/jtzero/.local/share/virtualenvs/persistor-YNkITIws/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 1646, in lastrowid
    return self.context.get_lastrowid()
  File "/Users/jtzero/.asdf/installs/python/3.8.6/lib/python3.8/unittest/mock.py", line 647, in __getattr__
    raise AttributeError(name)
AttributeError: get_lastrowid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tst.py", line 8, in <module>
    BaseCursorResult(context, CursorFetchStrategy() , None).lastrowid
  File "/Users/jtzero/.local/share/virtualenvs/persistor-YNkITIws/lib/python3.8/site-packages/sqlalchemy/engine/cursor.py", line 1648, in lastrowid
    self.cursor_strategy.handle_exception(self, e)
TypeError: handle_exception() missing 1 required positional argument: 'err'
```

**Versions.**
 - OS: 4.19.121-linuxkit/macos 10.15.7 
 - Python: 3.8.5
 - SQLAlchemy: 1.4.2
 - Database:  snowflake (has no get_lastrowid)
 - DBAPI:  2.4.1

**Have a nice day!**

**Comment by zzzeek** [comment]
this is a theoretical bug that has no current impact so anyone is free to send a one-line PR for this.

**Comment by jtzero** [comment]
This actually happens with https://github.com/snowflakedb/snowflake-sqlalchemy, and that's how I came across it

**Comment by zzzeek** [comment]
that sounds like a different issue?    Can you please provide complete, real world details including stack trace?  thanks

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fix typo in CursorResult exception handling** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2684
