### ISSUE TITLE
Scoped sessions missing 2.0 API `get` method

### ISSUE THREAD

**Issue by Sinclert** [sqlalchemy/sqlalchemy#6144]
**Describe the bug**
The objects coming from the [`scoped_session()`](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/scoping.py#L66) factory do not have the recently added [`Session.get()`](https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session.get) method (2.0 API).

**Expected behavior**
The method [`Session.get()`](https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session.get) should be populated into [`scoped_session()`](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/scoping.py#L66) created objects.

**To Reproduce**
```python
from sqlalchemy.engine import create_engine
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import scoped_session
from sqlalchemy.orm import sessionmaker
from sqlalchemy import Column
from sqlalchemy import String

base = declarative_base()


class DummyModel(base):
    """ Dummy data model """

    __tablename__ = "dummy"

    id = Column(String(32), nullable=False, primary_key=True)


class DummyModelController:
    """ Dummy controller for the data model """

    model = DummyModel

    def __init__(self, connection_url: str):
        self.engine = create_engine(connection_url)
        self.session = scoped_session(sessionmaker(bind=self.engine))

    def setup(self):
        base.metadata.create_all(bind=self.engine)

    def retrieve(self, id: str):
        return self.session.get(self.model, id)


controller = DummyModelController("sqlite:///:memory:")
controller.setup()
record = controller.retrieve("example")

```

**Error**

```sh
Traceback (most recent call last):
  File "<MY_LOCAL_PATH>/src/test.py", line 37, in <module>
    record = controller.retrieve("example")
  File "<MY_LOCAL_PATH>/src/test.py", line 32, in retrieve
    return self.session.get(self.model, id)
AttributeError: 'scoped_session' object has no attribute 'get'
```

**Versions.**
 - OS: mac OS 11.2.3
 - Python: Python 3.7.9
 - SQLAlchemy: 1.4.3
 - Database: PostgreSQL
 - DBAPI: psycopg2

**Additional context**
I believe that when the [`Session.get()`](https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session.get) method was introduced (in [this commit](https://github.com/sqlalchemy/sqlalchemy/commit/5de0f1cf50cc0170d8ea61304e7b887259ab577b)), it was not populated to [the list of methods](https://github.com/sqlalchemy/sqlalchemy/blob/784d32edff03cd960d0c47768f7ef0d0a438463e/lib/sqlalchemy/orm/scoping.py#L25-L52) that the scoped session objects _inherits_ via the `@create_proxy_methods` decorator.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Add ScopedSession.get()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2678
