### ISSUE TITLE
Enum machinery uses repeated enum values (aliases)

### ISSUE THREAD

**Issue by jbvsmo** [sqlalchemy/sqlalchemy#6146]
**Describe the bug**
We had a legacy enum with names that have spaces so we added some aliases to make coding easier.
Notice the aliases have repeated values so they [will not create enum elements](https://docs.python.org/3/library/enum.html#duplicating-enum-members-and-values).

E.g:
```
Names = enum.Enum(
    value='Names',
    names=[
        ('Name A', 1), ('a', 1),
        ('Name B', 2), ('b', 2),
        ('Name C', 3), ('c', 3),
    ]
)
```

So when you `list(Names)`, you only see the 3 original enum names and : `Names["Name A"] is Names.a` meaning that `a` is just an alias and points to the same object.

When you pass this to `name = Column(Enum(Names))`, it will create the 6 names on the column because 
`sqlalchemy.Enum._parse_into_values` is using the `__members__` atribute from enum which shows everything, including aliases.

SQL output for that column:
``` `name` ENUM('Name A','Name B','Name C','a','b','c') NOT NULL, ```

**Expected behavior**
``` `name` ENUM('Name A','Name B','Name C') NOT NULL, ```

I propose to use  `[e.name for e in enum_class]`
instead of `enum_class.__members__`
https://github.com/sqlalchemy/sqlalchemy/blob/93ea31df86fc925a9e1df2a7dc80dd39f7ae4b9e/lib/sqlalchemy/sql/sqltypes.py#L1509

**Versions.**
 - OS: MacOS
 - Python: 3.8
 - SQLAlchemy: 1.3.23
 - Database: MySQL
 - DBAPI: pymysql

**Comment by zzzeek** [comment]
pep-435 is ambiguous about iterating over enums, with just the phrase "Within an enumeration, the values can be compared by identity, and the enumeration itself can be iterated over." being all it has.  It does however fully define `__members__` and that's also [what we document](https://docs.sqlalchemy.org/en/14/core/type_basics.html?highlight=enum#sqlalchemy.types.Enum) as well as use in tests.

So it has to keep using `__members__` but it can just use a `set()` to check for dupes.

**Comment by jbvsmo** [comment]
If you intend to keep using `__members__`, the docs define how to get aliases here:
https://docs.python.org/3/library/enum.html#iteration

So you can replace `!=` with `==` to get the actual enum names:

```[name for name, member in Shape.__members__.items() if member.name == name]```

**Comment by CaselIT** [comment]
@zzzeek While this may be a 1.3 backport, I think we could limit to 1.4 since it would change the behaviour.

We currently have tests that ensure the current handling of alias values, so if we want to change it I think it could be for 1.4 only.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Correctly handle aliases in :class:`_sql.Enum`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2686

**Comment by CaselIT** [comment]
@zzzeek in the gerrit I've left the failing test. Let me know if we want to retain the previous behaviour with a flag or simillar

**Comment by zzzeek** [comment]
> @zzzeek While this may be a 1.3 backport, I think we could limit to 1.4 since it would change the behaviour.
> 
> We currently have tests that ensure the current handling of alias values, so if we want to change it I think it could be for 1.4 only.

which test is that?     if it actually creates duplicate entries in the ENUM for the column, that's a bug.

**Comment by CaselIT** [comment]
> 
> 
> > @zzzeek While this may be a 1.3 backport, I think we could limit to 1.4 since it would change the behaviour.
> > We currently have tests that ensure the current handling of alias values, so if we want to change it I think it could be for 1.4 only.
> 
> which test is that? if it actually creates duplicate entries in the ENUM for the column, that's a bug.

mainly these two 
test_pep435_enum_round_trip at https://github.com/sqlalchemy/sqlalchemy/blob/master/test/sql/test_types.py#L2110
test_adapt https://github.com/sqlalchemy/sqlalchemy/blob/master/test/sql/test_types.py#L2195

**Comment by zzzeek** [comment]
that looks like a bug in the fixtures as the value "four" is taken as one of the database values, meaning it's not an "alias" in the sense that the PEP defines.  that's not the case here, we arent' writing "Name A" and "A" into the database, we're writing "1".

**Comment by CaselIT** [comment]
I'm pretty sure we write the names of the enums, not the values to the db. So "four" is written in the db:

```
psycopg2.errors.InvalidTextRepresentation: invalid input value for enum someenum: "four"
LINE 1: ...3, 'one'),(4, 'three'),(5, 'three'),(6, 'three'),(7, 'four')
```
https://jenkins.sqlalchemy.org/job/sqlalchemy_gerrit/cext=cext,db=sqlite-postgresql,pyv=py38/7123/testReport/junit/test.sql.test_types/EnumTest_postgresql+psycopg2_11_10/test_pep435_enum_round_trip/

Also I think the enum fixture seems to be working fine for aliases

**Comment by zzzeek** [comment]
ohhh... right we do write the names , just re-read the top of the post.    

well then this is a huge backwards-incompatible thing.   not really sure what to do besides adding an ugly flag.   someone that already has aliases on their enums already has those values in their DB.

**Comment by zzzeek** [comment]
i think "omit_aliases=True" flag that does the "name == self.name" behavior is the only way to go here.

**Comment by CaselIT** [comment]
Great label the "quagmire" one :)

I think we could place that flag to False in 1.4, and use deprecation 2.0 here to turn that True by default in 2.0

**Comment by jbvsmo** [comment]
I think you could show a warning if the enum has aliases and the user didn't pick the flag value.

But i don't believe someone would want aliases stored. Because you will fragment the data. If they want to rename the enum value stored, they can do a migration

**Comment by CaselIT** [comment]
> But i don't believe someone would want aliases stored. Because you will fragment the data. If they want to rename the enum value stored, they can do a migration

that's not as easy as is should be. For example, when using postgresql native enums, there is no way of removing enum values, you can only add them to the enum type.

So sadly I think it we will need to keep this flag for the foreseeable future. But yes, I think we will have a warning shown if the enum has aliases and the flag is not specified. Probably the flag will be initially off, and we could probably toggle it to on in v2

**Comment by zzzeek** [comment]
they should do a migration sure but we can't force that on them with a new update, they have to opt in to when they are able to do that, so we need a flag.

**Comment by CaselIT** [comment]
ok, tried to update the patch with the flag

**Comment by zzzeek** [comment]
the situation here is quite strange.   given the top example, the CHECK constraint generated is not consistent with how a PG ENUM is generated.  given this test:
```

import enum

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Enum
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base

Names = enum.Enum(
    value='Names',
    names=[
        ('Name A', 1), ('a', 1),
        ('Name B', 2), ('b', 2),
        ('Name C', 3), ('c', 3),
    ]
)
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(Enum(Names, create_constraint=True))

#e = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
e = create_engine("sqlite://", echo=True)

Base.metadata.drop_all(e)
Base.metadata.create_all(e)


```

SQlite output:

```
CREATE TABLE a (
	id INTEGER NOT NULL, 
	data VARCHAR(6), 
	PRIMARY KEY (id), 
	CONSTRAINT names CHECK (data IN ('Name A', 'Name A', 'Name B', 'Name B', 'Name C', 'Name C'))
)

```

postgresql output:

```python
CREATE TYPE names AS ENUM ('Name A', 'a', 'Name B', 'b', 'Name C', 'c')
2021-04-01 14:44:25,009 INFO sqlalchemy.engine.Engine [no key 0.00007s] {}
2021-04-01 14:44:25,010 INFO sqlalchemy.engine.Engine 
CREATE TABLE a (
	id SERIAL NOT NULL, 
	data names, 
	PRIMARY KEY (id)
)

```


@CaselIT  can you see why it's doing this and maybe we fix that also ?

**Comment by CaselIT** [comment]
How strange. Will look

**Comment by CaselIT** [comment]
@zzzeek Ok so, for postgres it has always worked that way since it was added: aa557982fa2518e6d520ce17894093d5ed03c0eb

The reason why it does this is that for pg it uses the list of elements processed as literal, without indicating that they are of type enum:
https://github.com/sqlalchemy/sqlalchemy/blob/3770dbd0028c490f72325f1c13917b021c6f6dbb/lib/sqlalchemy/dialects/postgresql/base.py#L2535-L2536

For a non-native enum it instead use a bindparam with type the enum column. This means that when it literally compile it it uses the `literal_processor` of `Enum` that uses `_db_value_for_elem` doing a lookup in a dict with these values:
```py
{
    <Names.Name C: 3>: "Name C",
    <Names.Name B: 2>: "Name B",
    <Names.Name A: 1>: "Name A",
    "Name A": "Name A",
    "a": "Name A",
    "Name B": "Name B",
    "b": "Name B",
    "Name C": "Name C",
    "c": "Name C",
    None: None,
}
```
and this disambiguates the aliases, causing the duplicate values in the check constrant.

What should be the correct option? I guess that since enum now has a flag, the correct one should be the pg one: it will render aliases if `omit_aliases=False` and it will not emit them if `omit_aliases=True`

**Comment by zzzeek** [comment]
so what value do we actually *store* in the DB?   if an enum has "Name A", and an alias "a", and we INSERT "a", does it store the string "Name A" or "a"?      does that part differ for non-native enum vs. PG enum (and what about MySQL enum?)  might need a matrix for this.

**Comment by CaselIT** [comment]
> if an enum has "Name A", and an alias "a", and we INSERT "a", does it store the string "Name A" or "a"

In think in this case it uses the bind processor and it will insert "Name A".

But i'll check all options and report back

**Comment by CaselIT** [comment]
Sees to always be the non-alias version to be inserted:

|name|native|non-alias|alias|
|--|--|--|--|
|sqlite|False|NameA|NameA|
|postgresql|False|NameA|NameA|
|postgresql|True|NameA|NameA|

this was obtained with
```py
import enum

import sqlalchemy as sa
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Enum
from sqlalchemy import MetaData
from sqlalchemy import Integer
from sqlalchemy import Table

Names = enum.Enum(
    value="Names",
    names=[
        ("NameA", 1),
        ("a", 1),
        ("NameB", 2),
        ("b", 2),
        ("NameC", 3),
        ("c", 3),
    ],
)

def go(e, native):
    meta = MetaData()
    a = Table(
        "a",
        meta,
        Column("id", Integer),
        Column(
            "data", Enum(Names, create_constraint=True, native_enum=native)
        ),
    )
    meta.drop_all(e)
    meta.create_all(e)
    with e.begin() as conn:
        conn.execute(
            a.insert(),
            [{"id": 1, "data": Names.NameA}, {"id": 1, "data": Names.a}],
        )
    with e.connect() as conn:
        data = conn.execute(
            sa.select('*').select_from(sa.table("a")).order_by(sa.column("id"))
        ).all()

    print('|name|native|non-alias|alias|')
    print(f"|{e.dialect.name}|{native}|{data[0].data}|{data[1].data}|")

epg = create_engine("postgresql://scott:tiger@localhost/test", echo=False)
esqlite = create_engine("sqlite://", echo=False)

go(esqlite, False)
go(epg, False)
go(epg, True)
```

**Comment by zzzeek** [comment]
OK so that means the omit_aliases flag we just added will be an easy upgrade for people, since the only effect it has on the DB is a CHECK constraint with too many elements, which are all repeats of what is there in any case.

to confirm, in no scenario are the "aliased" strings getting into the schema or the data of the database, except for MySQL ?

**Comment by CaselIT** [comment]
I need to verify with the tests we have, since I think in some cases we do insert the alias.

Maybe when inserting the string directly?

**Comment by zzzeek** [comment]
well we've already put omit_aliases out there, so maybe we can fix the doubling up in the constraint part here but this is low priority.

**Comment by CaselIT** [comment]
> 
> 
> I need to verify with the tests we have, since I think in some cases we do insert the alias.
> 
> Maybe when inserting the string directly?

it seems that it always gets inserted the non-alias value even when inserting the string of the alias directly

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Unify native and non-native valid values for ``Enum``** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2722
