### ISSUE TITLE
Duplicate CheckConstraint for custom type

### ISSUE THREAD

**Issue by finswimmer** [sqlalchemy/sqlalchemy#6152]
**Describe the bug**
I've created a custom column type, which converts "Y" and "N" from within the database to `True` and `False` in the python context and vice versa. I choose to implement it as an enum type.

This all works well. Now I've started to use naming convention for constraints and my oracle database suddenly complains about a duplicate constraint names.

For debugging and finding a minimal example I used sqlite as the database engine and don't used naming convention (because it seem sqlite just overwrite the first appearance of a constraint name). The code below indeed creates two check constraints with the same content. Why?

**Expected behavior**

Only one check constraint should be created.

**To Reproduce**
```py
import enum
from pathlib import Path
from typing import Any, Type

from sqlalchemy import Column, Integer, String, create_engine, text, types
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class BoolYN(types.TypeDecorator):
    impl = types.Enum

    def __init__(self, *args: Any, **kwargs: Any):
        super().__init__("Y", "N", *args, **kwargs)

    def process_literal_param(self, value: bool, dialect: Any) -> str:
        """
        Converts bool value passed to literal value on inserting to database.

        aka python --> column
        """
        if value is True:
            return "Y"
        elif value is False:
            return "N"
        else:
            raise TypeError(f"{value} is not of type bool")

    process_bind_param = process_literal_param

    def process_result_value(self, value: str, dialect: Any) -> bool:
        """
        Convert combined enum value to associated single enum type.

        aka column --> python
        """

        if value == "Y":
            return True
        elif value == "N":
            return False
        else:
            raise ValueError(f"{value} cannot be converted to a bool")


class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    name = Column(String)
    active = Column(
        BoolYN(length=1, native_enum=False, create_constraint=True),
        nullable=False,
        server_default=text("'N'"),
    )


def main():
    if Path("custom_type_db.db").exists():
        Path("custom_type_db.db").unlink()

    engine = create_engine("sqlite:///custom_type_db.db", echo="debug")

    Base.metadata.create_all(engine)


if __name__ == "__main__":
    main()
```

**Error**

![duplicate_constraint](https://user-images.githubusercontent.com/2164565/112795622-126c8600-9069-11eb-8b85-68edc80ef31b.png)

```
2021-03-29 08:43:31,474 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-03-29 08:43:31,474 INFO sqlalchemy.engine.base.Engine ()
2021-03-29 08:43:31,474 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-03-29 08:43:31,474 INFO sqlalchemy.engine.base.Engine ()
2021-03-29 08:43:31,475 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("users")
2021-03-29 08:43:31,475 INFO sqlalchemy.engine.base.Engine ()
2021-03-29 08:43:31,475 DEBUG sqlalchemy.engine.base.Engine Col ('cid', 'name', 'type', 'notnull', 'dflt_value', 'pk')
2021-03-29 08:43:31,475 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("users")
2021-03-29 08:43:31,475 INFO sqlalchemy.engine.base.Engine ()
2021-03-29 08:43:31,475 DEBUG sqlalchemy.engine.base.Engine Col ('cid', 'name', 'type', 'notnull', 'dflt_value', 'pk')
2021-03-29 08:43:31,476 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE users (
	id INTEGER NOT NULL, 
	name VARCHAR, 
	active VARCHAR(1) DEFAULT 'N' NOT NULL, 
	PRIMARY KEY (id), 
	CHECK (active IN ('Y', 'N')), 
	CHECK (active IN ('Y', 'N'))
)


2021-03-29 08:43:31,476 INFO sqlalchemy.engine.base.Engine ()
2021-03-29 08:43:31,478 INFO sqlalchemy.engine.base.Engine COMMIT
```

**Versions.**
 - OS: Ubunto 18.04
 - Python: 3.9
 - SQLAlchemy: 1.3.23 / 1.4.2
 - Database: sqlite
 - DBAPI: sqlite3

**Comment by zzzeek** [comment]
im not really sure, the event handling logic for SchemaType is very loopy around itself and with TypeDecorator in the mix it's very difficult to control the process such that things are attached only once.  someone will have to take a look at this.   in the meantime please set create_constraint=False and create a constraint manually.

**Comment by CaselIT** [comment]
Out of curiosity, since this bug is also in 1.3 would it qualify for a backport?

**Comment by zzzeek** [comment]
it's a weak backport candidate because it requires new code to be apparent.

**Comment by finswimmer** [comment]
Glad to see this is a bug and I don't mess up something obviously :laughing: 

> in the meantime please set create_constraint=False and create a constraint manually.

I was afraid I have to this. As I have many table where I have to do this, this is a bit of work but luckily copy&paste exists ;)

Thanks for the quick reponse!

**Comment by zzzeek** [comment]
> it's a weak backport candidate because it requires new code to be apparent.

then again it's an old bug and might be a clean cherry-pick to 1.3 as nothing seems to have changed in this area.

**Comment by CaselIT** [comment]
I'll change to 1.3 then when we resolve this we can check if it makes sense to backport or not

**Comment by zzzeek** [comment]
it's hard to tell where this was introduced but some combination of #2892, #2919, #3832

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**TypeDecorator passes "outer" flag to itself for set_parent accounting** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2688

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**TypeDecorator passes "outer" flag to itself for set_parent accounting** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2689

**Comment by finswimmer** [comment]
Amazing! Thanks a lot :+1:
