### ISSUE TITLE
sqlalchemy.engine.result.Result regression in 1.4.2

### ISSUE THREAD

**Issue by bmwilly** [sqlalchemy/sqlalchemy#6153]
1.4.0 deprecated `sqlalchemy.engine.result.ResultProxy` in favor of `sqlalchemy.engine.result.Result`. Now there's been some kind of regression in 1.4.2 that has undone that change.  

With 1.4.1:
```
>>> import sqlalchemy
>>> sqlalchemy.engine.result.ResultProxy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sqlalchemy.engine.result' has no attribute 'ResultProxy'
>>> sqlalchemy.engine.Result
<class 'sqlalchemy.engine.result.Result'>
```

With 1.4.2:
```
>>> import sqlalchemy
>>> sqlalchemy.engine.Result
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sqlalchemy.engine' has no attribute 'Result'
>>> sqlalchemy.engine.result.ResultProxy
<class 'sqlalchemy.engine.result.ResultProxy'>
```

**Expected behavior**

The behavior shown in 1.4.1 above should match the behavior in 1.4.2.

**Versions.**
 - OS: Linux
 - Python: 3.8.6
 - SQLAlchemy: 1.4.2
 - Database:
 - DBAPI:

**Comment by zzzeek** [comment]
hi -

please refer to #6119 .   ResultProxy is an alias for LegacyCursorResult and was inadvertently removed from the "engine" namespace where it was in 1.3, and folks rely on this for backwards compatibility.

current SQLAlchemy version is 1.4.3 and both symbols are available:

```
>>> import sqlalchemy
>>> sqlalchemy.engine.Result
<class 'sqlalchemy.engine.result.Result'>
>>> sqlalchemy.engine.ResultProxy
<class 'sqlalchemy.engine.cursor.LegacyCursorResult'>

```

**Comment by bmwilly** [comment]
Ah, sorry for missing that! thanks
