### ISSUE TITLE
DataFrame from sqlalchemy query missing column headers

### ISSUE THREAD

**Issue by isthisthat** [sqlalchemy/sqlalchemy#6154]
**Description**
Using sqlalchemy 1.4.3, initialising a pandas (v1.1.5) DataFrame from an sqlalchemy query object results in a table with no headers (defaults to RangeIndex (0, 1, 2, …, n))
Using sqlalchemy 1.3.23, you get proper column names from a query result.
Not sure whether this is described elsewhere. Couldn't see this exact bug reported.

**Expected behavior**
Expecting the pandas DataFrame headers to be the names of the sql table headers, rather than 0,1,2,3,etc

**To Reproduce**

```py
from sqlalchemy import create_engine, Table, Column, Integer, String
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
import pandas as pd

BaseModel = declarative_base()

class Test(BaseModel):
    __tablename__ = 'test'
    id = Column(Integer, primary_key=True)
    foo = Column(String(50))

engine = create_engine('sqlite:////tmp/test.db')
BaseModel.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()
query = session.query

df = pd.DataFrame({"id":[0,1],"foo":["hello","world"]})
df.to_sql("test", con=engine, index=False, if_exists='replace')

foo=query(Test.id, Test.foo)
session.commit()
session.close()
pd.DataFrame(foo)


```

**Error**

```
	0	1
0	0	hello
1	1	world
```

instead of 
```
	id	foo
0	0	hello
1	1	world
```

**Versions.**
 - Python: 3.6.13
 - SQLAlchemy: 1.4.3
 - Pandas: 1.1.5

**Comment by isthisthat** [comment]
just did a quick test and you get the same behavior without `declarative_base`:

```
from sqlalchemy import create_engine, Table, Column, Integer, String
from sqlalchemy.orm import sessionmaker
#from sqlalchemy.ext.declarative import declarative_base
import pandas as pd

#BaseModel = declarative_base()
from sqlalchemy import MetaData
metadata = MetaData()

test_table = Table('test', metadata, 
    Column('id', Integer, primary_key=True),
    Column('foo', String(50))
                  )

engine = create_engine('sqlite:////tmp/test.db')
#BaseModel.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()
query = session.query

df = pd.DataFrame({"id":[0,1],"foo":["hello","world"]})
df.to_sql("test", con=engine, index=False, if_exists='replace')

foo=query(Test.id, Test.foo)
session.commit()
session.close()
pd.DataFrame(foo)
```

**Comment by zzzeek** [comment]
this is because Row as used per https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#the-keyedtuple-object-returned-by-query-is-replaced-by-row and is not a subclass of tuple, as it is a native object, but it does implement Sequence.

pandas can make this adjustment to fix:

```
diff --git a/pandas/core/dtypes/inference.py b/pandas/core/dtypes/inference.py
index 58da257001..c2759be07c 100644
--- a/pandas/core/dtypes/inference.py
+++ b/pandas/core/dtypes/inference.py
@@ -315,7 +315,7 @@ def is_named_tuple(obj) -> bool:
     >>> is_named_tuple((1, 2))
     False
     """
-    return isinstance(obj, tuple) and hasattr(obj, "_fields")
+    return isinstance(obj, abc.Sequence) and hasattr(obj, "_fields")
 
 
 def is_hashable(obj) -> bool:

```

otherwise you can manually cast to dict as follows:

    p = pd.DataFrame([f._mapping for f in foo])

**Comment by isthisthat** [comment]
This prompted me to actually read the 1.4 release notes. Wow! Excellent work. Will set some time to migrate fully in the future. Thanks!

**Comment by zzzeek** [comment]
OK closing this, we can't really change this on our end.

**Comment by CaselIT** [comment]
I'll raid it on pandas side
