### ISSUE TITLE
Incorrect column nullable value when column is of type domain (and domain is nullable and column is not) Postgres

### ISSUE THREAD

**Issue by adstruble** [sqlalchemy/sqlalchemy#6161]
**Describe the bug**
If a table has a "not null" column that is a domain and the domain type is nullable, the reflection of the column incorrectly reports the column as nullable

**Expected behavior**
The column should not be nullable in the case where the column is set to "not null" even if the domain is nullable

**To Reproduce**
Run provided Python code with postgres 

I used: PostgreSQL 11.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

```py
database_params = {"host": 'hostnme',
                                  "database": "db_name",
                                  "user": "user_name",
                                 "password": "user_password"}

conn_string = "postgresql://{}:{}@{}/{}".format(database_params['user'],
                                              database_params['password'],
                                              database_params['host'],
                                              database_params['database'])

def main():
    engine = sqlalchemy.create_engine(conn_string)

    with engine.begin() as conn:

        with conn.connection.cursor() as cursor:

            cursor.execute("CREATE DOMAIN nullable_domain AS TEXT CHECK (VALUE IN('FOO', 'BAR'));")
            cursor.execute("CREATE TABLE sqlalchemy_domain_test (not_nullable_domain_col nullable_domain not null);")

    with engine.begin() as conn:

        meta = MetaData(bind=conn)
        sql_table = Table("sqlalchemy_domain_test", meta, autoload=True)

        # The not nullable_domain_col should not be nullable because even though the domain is nullable the col is not.
        # If the domain was NOT nullable then the col should obey the domain. But in this case, the domain nullability
        # should not be used since the column is stricter.
        if sql_table.c["not_nullable_domain_col"].nullable:
            print("FAIL")
        else:
            print("PASS")

        with conn.connection.cursor() as cursor:
            cursor.execute("DROP TABLE sqlalchemy_domain_test;")
            cursor.execute("DROP DOMAIN nullable_domain")


if __name__ == '__main__':
    main()
```

**Error**

```
There is no stacktrace, the error is that the nullable value is incorrect for the column
```

**Versions.**
 - OS: Pop!_os 19.04 ubuntu
 - Python:3.7.3
 - SQLAlchemy: 1.4.3
 - Database: (in a docker container) PostgreSQL 11.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
 - DBAPI: psycopg2 2.8.3

**Additional context**
None

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

we read the attnotnull column from the https://www.postgresql.org/docs/9.4/catalog-pg-attribute.html and what you see is what that table is giving us.   Here's the query we are using: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/base.py#L3595

can you suggest how this query might be adjusted to get the accurate information from PostgreSQL?     cc @CaselIT

**Comment by zzzeek** [comment]
graet, thanks for that we can just add a test and adjust that.

**Comment by adstruble** [comment]
Perfect, thank you!

**Comment by zzzeek** [comment]
can you confirm this is the logic, "nullable" only if both column and domain agree on "nullable", this passes your test:

                # A table can't override a not null on the domain,
                # but can override nullable
                nullable = nullable and domain["nullable"]

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Refine domain nullable rules for PostgreSQL reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2691

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**Refine domain nullable rules for PostgreSQL reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2692
