### ISSUE TITLE
The 1.3.24 release broke Python 3.4 compatibility

### ISSUE THREAD

**Issue by jgosmann** [sqlalchemy/sqlalchemy#6168]
**Describe the bug**
In commit b348e82dcf5eca1fc8496c941dc1ac2ffd60eed9 an import of the `typing` module was added in [`compat.py:189`](https://github.com/sqlalchemy/sqlalchemy/commit/b348e82dcf5eca1fc8496c941dc1ac2ffd60eed9#diff-9993a4b25b4aabf603004cf1d0b781d0c350b3802183f657725f9726b5c37611R189). The `typing` module only exists since Python 3.5 and thus SqlAlchemy 1.3.24 is now incompatible with Python 3.4. I'm not sure whether you still support Python 3.4, but the `setup.py` for that version neither excludes 3.4 in the `python_requires` line:
```python
python_requires=">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*",
```
nor did it remove the `"Programming Language :: Python :: 3.4"` classifier.

**Expected behavior**
The 1.3.x line continues to work with Python 3.4 or it is explicitly declared as incompatible.

**To Reproduce**

```py
import sqlalchemy
```

**Error**

```
Python 3.4.10 (default, Jan  2 2021, 11:38:23)
[GCC Apple LLVM 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gosmannj/Library/Python/3.4/lib/python/site-packages/sqlalchemy/__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "/Users/gosmannj/Library/Python/3.4/lib/python/site-packages/sqlalchemy/util/__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "/Users/gosmannj/Library/Python/3.4/lib/python/site-packages/sqlalchemy/util/_collections.py", line 16, in <module>
    from .compat import binary_types
  File "/Users/gosmannj/Library/Python/3.4/lib/python/site-packages/sqlalchemy/util/compat.py", line 189, in <module>
    from typing import TYPE_CHECKING
ImportError: No module named 'typing'
```

**Versions.**
 - OS: Linux (Scientific Linux 6), macOS Big Sur 
 - Python: Python 3.4
 - SQLAlchemy: 1.3.24
 - Database: n/a
 - DBAPI: n/a

**Have a nice day!**

You too!

**Comment by jgosmann** [comment]
Thanks for the quick response! I'll try to test out the patch tomorrow.

**Comment by jgosmann** [comment]
I can confirm that the patch seems to work. At least I can `import sqlalchemy` without error in Python 3.4 using it.

**Comment by zzzeek** [comment]
this is merged as above.
