### ISSUE TITLE
DeepSource integration for code quality checks

### ISSUE THREAD

**Issue by akshgpt7** [sqlalchemy/sqlalchemy#6180]
**Is your feature request related to a problem? Please describe.**
Running DeepSource analysis on the repo raises a lot of [code quality issues](https://deepsource.io/gh/akshgpt7/sqlalchemy/) that can improve the general code quality here.
I opened a PR (#6179) fixing some of the issues detected for you to assess if it is right for you, but after reading the guidelines, I'm opening this issue, and will close the PR till further discussion can take place here

**Describe the solution you'd like**
Integrating DeepSource can run a check on every new PR opened and flag any such issues in the PR itself before it is adopted in the final code-base.

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

Thanks for the interest. While the tool looks interesting, at the moment we are not planning on adding it, since we still support python 2 alongside python 3 that makes for some awkward patterns that are flagged by the tool.

We may revisit it once we are python 3 only.
