### ISSUE TITLE
assert for out of band bindparams created by compilers

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6184]
given test script:

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)


def go(value):

    with e.connect() as conn:
        conn.execute(select(A).where(A.id == value))


go(5)
go(10)

```

below we patch compiler to simulate a compiler that is silently exchanging bound parameters for ones that wont be resolved against the cache, and we also include the assertion that will catch this condition:

```diff
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index 276209103..1de718d29 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -970,9 +970,10 @@ class SQLCompiler(Compiled):
                         )
                 else:
                     if resolved_extracted:
-                        value_param = resolved_extracted.get(
-                            bindparam, bindparam
-                        )
+                        try:
+                            value_param = resolved_extracted[bindparam]
+                        except KeyError:
+                            assert False, "this is the assertion"
                     else:
                         value_param = bindparam
 
@@ -1006,7 +1007,10 @@ class SQLCompiler(Compiled):
                         )
 
                 if resolved_extracted:
-                    value_param = resolved_extracted.get(bindparam, bindparam)
+                    try:
+                        value_param = resolved_extracted[bindparam]
+                    except KeyError:
+                        assert False, "this is the assertion"
                 else:
                     value_param = bindparam
 
@@ -2227,6 +2231,13 @@ class SQLCompiler(Compiled):
         **kwargs
     ):
 
+        if not hasattr(bindparam, "_bogus"):
+            bogus_bindparam = elements.BindParameter(None, value=10, unique=True)
+            bogus_bindparam._bogus = True
+
+
+            bindparam = bogus_bindparam
+
         if not skip_bind_expression:
             impl = bindparam.type.dialect_impl(self.dialect)
             if impl._has_bind_expression:

```

next I'll remove the bogus part and run the suite to see where this assertion fails.

cc @CaselIT

**Comment by zzzeek** [comment]
lots of failures, like lots.   so lets see why

**Comment by zzzeek** [comment]
first case, is a simple offset:

```python
def go(value, offset):

    with e.connect() as conn:
        conn.execute(select(A).where(A.id == value).offset(offset))


go(5, 2)
go(10, 8)

```


why does this fail?  Because the SQLite compiler, in the case of offset with no limit, must hardcode LIMIT to the value -1:

```python
    def limit_clause(self, select, **kw):
        text = ""
        if select._limit_clause is not None:
            text += "\n LIMIT " + self.process(select._limit_clause, **kw)
        if select._offset_clause is not None:
            if select._limit_clause is None:
                text += "\n LIMIT " + self.process(sql.literal(-1))
            text += " OFFSET " + self.process(select._offset_clause, **kw)
        else:
            text += " OFFSET " + self.process(sql.literal(0), **kw)
        return text

```

so that's an example of the compiler needs to generate a fixed bound value, that isn't changing, that isn't part of the cache key.

suggestions?

**Comment by CaselIT** [comment]
Nothing that would be considered robust at this time, no.

Considering legitimate use cases like the one here, it really may really hard to do something that has no (or very low) false positives.

**Comment by zzzeek** [comment]
we can make a special flag or warpper required for such params, and emit a warning if we do the detection above and the params don't have the flag.   that will urge dialect authors to go in and make sure they aren't putting a variable value in the parameter.

**Comment by CaselIT** [comment]
Sure that's an option. I don't think we can do that automatically (without some ugly threadlocal stuff).

Should we also allow a compiler to indicate that a statement should *not* be cached?

**Comment by zzzeek** [comment]
I was thinking such that literal_column() is OK and sql.bindparam() is not, since the latter is what dialects might be doing.  but thenI looked at the dialect I assumed might be doing this, and the situation is actually much worse: https://github.com/ibmdb/python-ibmdbsa/blob/master/ibm_db_sa/ibm_db_sa/base.py#L404   

so, they're sticking numbers right into strings and spitting it out.    I can't think of any way to automatically detect that a compiler like that one is not going to work with caching.       We'd probably have to set a flag on the whole dialect cache_safe=False.     What do you think of that?

**Comment by zzzeek** [comment]
then in the logs we can have "dialect does not support caching", their users can complain to them and they can come to us for help.

**Comment by CaselIT** [comment]
I guess we have to. 

>  I can't think of any way to automatically detect that a compiler like that one is not going to work with caching

I have some idea but none of them are pretty / performant and/or easy do to in a foolproof way.

how can we search for sqlalchemy dialect in github, just to have a sample grater than one?

**Comment by zzzeek** [comment]
I'd pull some from [the list](https://docs.sqlalchemy.org/en/14/dialects/index.html#external-dialects)

this is just a flag.  if a dialect wants to be good for caching, they just set the flag to True on their dialect.   we probably need to look for the flag in `__dict__` so that if they subclass psyocpg2 dialect or something they still have to set it directly.

**Comment by CaselIT** [comment]
Ok, let's try to make a list

- redshift is good https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/60b4db04c1d26071c291aeea52f1dcb5dd8b0eb0/sqlalchemy_redshift/dialect.py#L225-L228
- drill is good https://github.com/JohnOmernik/sqlalchemy-drill/blob/2756e8ae1cb4eb0b9980b9c94560a940a1c0eff6/sqlalchemy_drill/base.py#L61
- druid is fine https://github.com/druid-io/pydruid/blob/master/pydruid/db/sqlalchemy.py#L37
- hive is good https://github.com/druid-io/pydruid/blob/master/pydruid/db/sqlalchemy.py#L37
- presto is fine https://github.com/dropbox/PyHive/blob/master/pyhive/sqlalchemy_presto.py#L45
- trino too https://github.com/dropbox/PyHive/blob/master/pyhive/sqlalchemy_trino.py#L44

...

**Comment by CaselIT** [comment]
I think it would be nice to have the flag set dynamically, since it seems most dialect are fine. But seeing the db2 one I can't think of a way, since that is just embedding stuff in the string

**Comment by CaselIT** [comment]
@zzzeek something like this is fine?

```py
def visit_getitem_binary(self, binary, operator, **kw):
        return "{0}['{1}']".format(
            self.process(binary.left, **kw),
            binary.right.value
        )
```

**Comment by CaselIT** [comment]
The use of `literal_execute=True` is fine because we get `[POSTCOMPILE_foo] = [POSTCOMPILE_var]`

**Comment by zzzeek** [comment]
> @zzzeek something like this is fine?
> 
> ```python
> def visit_getitem_binary(self, binary, operator, **kw):
>         return "{0}['{1}']".format(
>             self.process(binary.left, **kw),
>             binary.right.value
>         )
> ```

that's rendering the value of a bound parameter in the SQL.   I will get the same cache key for these two statements:

   stmt = select(table).where(table.c.y[5] == 10)

   stmt = select(table).where(table.c.y[19] == 10)

above, "5" and "19" are the .value.  the compiler can't touch those and support caching.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Default caching to opt-out for 3rd party dialects** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2706
