### ISSUE TITLE
"AsyncSession" has no attribute "add" (mypy)

### ISSUE THREAD

**Issue by mattzque** [sqlalchemy/sqlalchemy#6193]
**Describe the bug**

Mypy can't seem to find the `add` method on the new `sqlalchemy.ext.asyncio.AsyncSession` object.

It does find `execute` just fine, and I verified that the `add` method on the norrmal `sqlalchemy.orm.Session` object is correctly found by mypy.

I'm using the `sqlalchemy.ext.mypy.plugin` mypy module.

**Expected behavior**

No mypy errors.

**To Reproduce**

**example.py**
```py
from sqlalchemy.ext.asyncio import AsyncSession

session = AsyncSession()
session.add(None)
```

**mypy.ini**
```
[mypy]
plugins = pydantic.mypy, sqlalchemy.ext.mypy.plugin
ignore_missing_imports = True
disallow_untyped_defs = True
```

**Error**

```
% mypy example.py                                                               
example.py:4: error: "AsyncSession" has no attribute "add"
Found 1 error in 1 file (checked 1 source file)
```

**Versions.**
 - OS: Linux
 - Python: 3.8.5
 - SQLAlchemy: 1.4.5
 - Database: -
 - DBAPI: -
 - MyPy: 0.812

---

**Example using sessionmaker**

```py
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.orm import sessionmaker

engine = create_async_engine("")
async_session = sessionmaker(
    engine, expire_on_commit=False, class_=AsyncSession
)

async def main() -> None:
    async with async_session() as session:
        async with session.begin():
            reveal_type(session)
            sess: AsyncSession = session
            sess.add(None)
```

```
% mypy example.py                                                       
example.py:13: note: Revealed type is 'Any'
example.py:15: error: "AsyncSession" has no attribute "add"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by zzzeek** [comment]
this is not a bug in the mypy plugin, this is simply that the stubs are still under construction.  ive added a note for this at https://github.com/sqlalchemy/sqlalchemy2-stubs/issues/44.

**Comment by phdowling** [comment]
Hi @zzzeek , just curious - why is the add() method absent on AsyncSession, and what's the recommended way of actually performing inserts? I can begin() a new transaction and add objects there, but if that seems unnecessary just doing a single insert. Should I be using e.g. `stmt = insert()` followed by `await session.execute(stmt)` instead? Apologies if this is question is silly, I haven't used sqlalchemy much in the past and am now trying to start from scratch using asyncio and 2.0-style queries.

**Comment by zzzeek** [comment]
> Hi @zzzeek , just curious - why is the add() method absent on AsyncSession, 

hey there-

it's not absent, it's right here:

https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html?highlight=asyncsession%20add#sqlalchemy.ext.asyncio.AsyncSession.add

and in the example (using add_all()):

https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html?highlight=asyncsession%20add#synopsis-orm

> and what's the recommended way of actually performing inserts? 

session.add()

> I can begin() a new transaction and add objects there (like in the async ORM tutorial), but if that seems unnecessary just doing a single insert. 

the ORM session begins transactions automatically.  you only need to commit().  this is all in [the tutorial](https://docs.sqlalchemy.org/en/14/tutorial/orm_data_manipulation.html#data-manipulation-with-the-orm)


> Should I be using e.g. `stmt = insert(MyModel)` followed by `await session.execute(stmt)` instead? Apologies if this is question is silly, I haven't used sqlalchemy much in the past and am now trying to start from scratch using asyncio ORM and 2.0-style queries.

Please start with the [SQLAlhcemy Tutorial[(https://docs.sqlalchemy.org/en/14/tutorial/index.html) so that you can get some basic familiarity with SQLAlchemy.   The "async" version of the Core and ORM then involves using some slightly different APIs as documented at https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html .


> 
> Edit: nevermind, I guess I assumed the method wasn't there because my IDE wasn't autocompleting it, which I guess is sort of what this issue is about in the first place. I see the method does get added dynamically and is actually there.
> Nevertheless wondering about best practices here - is the insert() statement only meant for SQLAlchema core, and if I am doing ORM, I should use session.add()?

when using the ORM you'd use add(), yup.

**Comment by mattzque** [comment]
Thanks @zzzeek ! I just checked again with the latest version of the stubs and it works perfectly now! Great work with the new asyncio, its a very ergonomic interface. Loving 1.4/2.0!
