### ISSUE TITLE
Query.join() no longer takes a list of tables (which is OK, but I can't find any docs)

### ISSUE THREAD

**Issue by andrewcooke-isti** [sqlalchemy/sqlalchemy#6203]
**Describe the bug**
Query.join() used to take a list of tables and would treat them as a sequence of calls to join, using the foreign key.   Now the second table in the list is take as an ON clause and gives an error (because it's not an ON clause, obviously).

THIS IS OK!  I guess it was either never supported or was deprecated aeons ago.  But I could not find any documentation for this in the change logs.  So I wanted to raise an issue to (1) just make you aware so you could take any action if unexpected and (2) to provide a Google hit for anyone else trying to debug the behaviour (the fix is to use successive explicit calls to join(), obviously).

**Expected behavior**
session.query(Table1).join(Table2, Table3) used to be equivalent to session.query(Table1).join(Table2).join(Table3)

Now it gives the error:
```
sqlalchemy.exc.ArgumentError: SQL expression for ON clause expected, got <class '...Table3'>
```

**To Reproduce**
See above.

**Versions.**
 - OS: OpenSuse Leap 15.2
 - Python: 3.9
 - SQLAlchemy: 1.4.5 (but I don't know when this started; i may not have updated for some time)
 - Database: Postgres 13-3.0-alpine docker image
 - DBAPI: 

**Have a nice day!**

**Comment by zzzeek** [comment]
it's pretty deprecated but is still supposed to work in 1.4

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Detect (Entity, Entity) vs (Entity, onclause) in legacy join** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2714

**Comment by andrewcooke-isti** [comment]
Oh!  Well, I've fixed my code, but scrolling back I in the terminal I found a more detailed trace, if it's any use:

```
choochoo |   File "/usr/local/lib/python3.9/site-packages/ch2/sql/tables/statistic.py", line 330, in for_source
choochoo |     return s.query(StatisticJournal).join(StatisticName, Source). \
choochoo |   File "<string>", line 2, in join
choochoo |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 96, in _generative
choochoo |     x = fn(self, *args, **kw)
choochoo |   File "<string>", line 2, in join
choochoo |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/base.py", line 224, in generate
choochoo |     fn(self, *args[1:], **kw)
choochoo |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2315, in join
choochoo |     joins_to_add = tuple(
choochoo |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2324, in <genexpr>
choochoo |     coercions.expect(roles.OnClauseRole, prop[1], legacy=True)
choochoo |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 175, in expect
choochoo |     resolved = impl._literal_coercion(
choochoo |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 388, in _literal_coercion
choochoo |     self._raise_for_expected(element, argname)
choochoo |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 270, in _raise_for_expected
choochoo |     util.raise_(exc.ArgumentError(msg, code=code), replace_context=err)
choochoo |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
choochoo |     raise exception
choochoo | sqlalchemy.exc.ArgumentError: SQL expression for ON clause expected, got <class 'ch2.sql.tables.source.Source'>.
```

(weird formatting from docker)

**Comment by zzzeek** [comment]
usually I ask for a complete test case but i know where this is so it's  all good
