### ISSUE TITLE
Mypy plugin crashes when using instances as relationship.collection_class

### ISSUE THREAD

**Issue by MaicoTimmerman** [sqlalchemy/sqlalchemy#6205]
**Describe the bug**
When using an instance as `relationship.collection_class` the mypy plugin crashes. It works for types as `list`, `set`, `dict`. However, not using [custom collection implementations](https://docs.sqlalchemy.org/en/14/orm/collections.html#custom-collection-implementations) like those in `sqlalchemy.orm.collections` or `sqlalchemy.ext.orderinglist`.

**Expected behavior**
I'm little unsure here, it could use the type of the instance or perhaps check for the `__emulates__` attribute mentioned in the custom collection docs?

**To Reproduce**
```py
from sqlalchemy import Column, Integer, ForeignKey
from sqlalchemy.orm import registry, relationship
from sqlalchemy.ext.orderinglist import OrderingList

mapper_registry: registry = registry()

@mapper_registry.mapped
class A:
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)

    parent = relationship("A", collection_class=OrderingList("ordering"))
    parent_id = Column(Integer, ForeignKey("a.id"))
    ordering = Column(Integer)
```

**Error**

```
test5.py:10: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.812
Traceback (most recent call last):
  File "mypy/semanal.py", line 4835, in accept
  File "mypy/nodes.py", line 950, in accept
  File "mypy/semanal.py", line 1048, in visit_class_def
  File "mypy/semanal.py", line 1125, in analyze_class
  File "mypy/semanal.py", line 1134, in analyze_class_body_common
  File "mypy/semanal.py", line 1180, in apply_class_plugin_hooks
  File "/home/maico/.cache/pypoetry/virtualenvs/test-8dqErJQo-py3.9/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 201, in _cls_decorator_hook
    decl_class._scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/home/maico/.cache/pypoetry/virtualenvs/test-8dqErJQo-py3.9/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 123, in _scan_declarative_assignments_and_apply_types
    _scan_declarative_assignment_stmt(cls, api, stmt, cls_metadata)
  File "/home/maico/.cache/pypoetry/virtualenvs/test-8dqErJQo-py3.9/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 385, in _scan_declarative_assignment_stmt
    python_type_for_type = _infer_type_from_relationship(
  File "/home/maico/.cache/pypoetry/virtualenvs/test-8dqErJQo-py3.9/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 535, in _infer_type_from_relationship
    if isinstance(collection_cls_arg.node, TypeInfo):
AttributeError: 'CallExpr' object has no attribute 'node'
```

**Versions.**
 - OS: Arch Linux
 - Python: 3.9
 - SQLAlchemy: 1.4.5
 - Database: n/a
 - DBAPI: n/a

**Additional context**
I'm open to doing contributions.

**Have a nice day!**

**Comment by zzzeek** [comment]
thanks for reporting!

**Comment by MaicoTimmerman** [comment]
@zzzeek It seems that my initial report here is incorrect/incomplete. The `relationship.collection_class` should be a class or callable, not an instance of that class. I mixed that up while creating a minimal reproduction sample. 

However, it seems that mypy  does not pick up the annotation that it should be a [`Type`](https://github.com/sqlalchemy/sqlalchemy2-stubs/blob/b0afe353927feed67df8aaefa9cdc4339503fcf6/sqlalchemy-stubs/orm/relationships.pyi#L63). I'm not sure if that is an error in de stubs or that the plugin's functionality for the `relationship` ignores the stub typing.

The fix for this issue is that it should either take a type (which is functioning correctly in the 1.4.6 release) or a callable. See https://github.com/sqlalchemy/sqlalchemy2-stubs/pull/59 for reference:

```py
parent = relationship("A", collection_class=lambda: OrderingList("ordering")) # not exposed in __all__
parent = relationship("A", collection_class=ordering_list("position")) # equivalent, exposed in __all__
```

Not related to the mypy plugin, but using `sqlalchemy.ext.OrderingList("ordering")` directly results in errors as the `ordering_attr` is not actually set. I shall open a new issue for that, but this has also made it into the new test case in 64cfcf4af0d5b09efa07aeb2b863c2aae9587c3d

**Comment by zzzeek** [comment]
oh then I screwed it up too.  i never use orderinglist so I didnt realize ordering_list() is the front end

**Comment by zzzeek** [comment]
>  but using sqlalchemy.ext.OrderingList("ordering") directly results in errors as the ordering_attr is not actually set. 

OK so the test case we have is wrong, which I'll fix, but that should be it.   OrderingList does what it's supposed to AFAIK.

**Comment by MaicoTimmerman** [comment]
The attribute is not set when using `OrderingList` as an instance. But since that is not public API, should they also be removed from the stub? I can remove them directly in https://github.com/sqlalchemy/sqlalchemy2-stubs/pull/59

**Comment by sqla-tester** [comment]
**Bryan Forbes** has proposed a fix for this issue in the **master** branch:

**Fix OrderingList handling** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2738
