### ISSUE TITLE
Remove comment type annotations from the code

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6207]
The comment type annotations that were introduced in the code are superseded by the [stubs library](https://github.com/sqlalchemy/sqlalchemy2-stubs)

Since it would be hard to keep both of them in sync they should be removed until sqlalchemy is python3 only.

**Comment by zzzeek** [comment]
I just need them to take effect for the sphinx documentation, I thought I had a lot more of these but apparently not, but here's one:  https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#sqlalchemy.ext.asyncio.AsyncConnection.exec_driver_sql    

if we can add sqlalchemy2-stubs to the docs/build/requirements.txt file and then sphinx picks these up that would be amazing

**Comment by CaselIT** [comment]
I had not considered the sphinx angle. 
There seems to be https://github.com/agronholm/sphinx-autodoc-typehints but I'm not sure if it works on stubs

@layday @bryanforbes do you have advices?

**Comment by zzzeek** [comment]
sphinx already uses the type hints that are in the code, I want to see if having the .pyi installed means the `__annotations__` automatically get set up in the modules as they are loaded.

**Comment by zzzeek** [comment]
sphinx is a lost cause for now, did we remove the type comments from the code and we can close this?

**Comment by CaselIT** [comment]
yes we did. I must have forgot to reference this issue in gerrit.

This was closed by 71cb17c81d358646f8dfeac14e9662ce42bb94df
