### ISSUE TITLE
typing is used on Python 3.4 but not declared as a dependency

### ISSUE THREAD

**Issue by michael-k** [sqlalchemy/sqlalchemy#6213]
**Describe the bug**

The import `from typing import TYPE_CHECKING` in `lib/sqlalchemy/util/compat.py` is guarded with `if py3k:`.  This is fine for SQLAlchemy 1.4, but not 1.3.x, which still supports Python 3.4.  The `typing` module was added to Python's stdlib in 3.5.

**Expected behavior**

The import is guarded with `if py35:` or [`typing`](https://pypi.org/project/typing/) is listed in `install_requires` for Python 3.4.

**To Reproduce**

```sh
docker run --rm -it --entrypoint bash python:3.4-slim
# python -m pip install sqlalchemy
# python
>>> import sqlalchemy
```

**Error**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/util/__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/util/_collections.py", line 16, in <module>
    from .compat import binary_types
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 189, in <module>
    from typing import TYPE_CHECKING
ImportError: No module named 'typing'
```

**Versions.**
 - OS: all
 - Python: 3.4
 - SQLAlchemy: **1.3**.24
 - Database: n/a
 - DBAPI: n/a

**Additional context**

n/a

**Comment by CaselIT** [comment]
Hi,

This was fixed in https://github.com/sqlalchemy/sqlalchemy/issues/6168, but it's not yet released.

**Comment by michael-k** [comment]
Yeah, sorry, I missed to check that branch :/

**Comment by CaselIT** [comment]
no worries. thanks for reporting it in any case
