### ISSUE TITLE
Mypy plugin documentation @declared_attr example results in TypeError during runtime.

### ISSUE THREAD

**Issue by MaicoTimmerman** [sqlalchemy/sqlalchemy#6214]
**Describe the bug**
The first example given in the mypy plugin documentation section [Using @declared_attr and Declarative Mixins](https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html#using-declared-attr-and-declarative-mixins), uses return type `Column[DateTime]`. However, that is not valid runtime python.

**Expected behavior**
The best thing would be to make the `Column` be subscriptable for type hint purposes, otherwise remove this example from the docs and require type hints to use `Mapped[int]` or `int`.

**To Reproduce**
```py
from sqlalchemy import Column, DateTime, Integer
from sqlalchemy.orm import declared_attr, declarative_base, registry

mapper_registry: registry = registry()

@mapper_registry.mapped
class Company:
    __tablename__ = 'company'

    id = Column(Integer, primary_key=True)

    @declared_attr
    def updated_at(cls) -> Column[DateTime]:  # uses Column
        return Column(DateTime)
```
**Error**

```
Traceback (most recent call last):
  File "/home/maico/test/test8.py", line 10, in <module>
    class Company(Base):
  File "/home/maico/test/test8.py", line 16, in Company
    def updated_at(cls) -> Column[DateTime]:  # uses Column
TypeError: 'TraversibleType' object is not subscriptable
```

**Versions.**
 - OS: Arch Linux 5.11
 - Python: 3.9
 - SQLAlchemy: 1.4.6
 - Database: -
 - DBAPI: -

**Have a nice day!**

**Comment by zzzeek** [comment]
it's set up as generic in the stubs so this works:

```python
@mapper_registry.mapped
class Company:
    __tablename__ = 'company'

    id = Column(Integer, primary_key=True)

    @declared_attr
    def updated_at(cls) -> "Column[DateTime]":  # uses Column
        return Column(DateTime)
```

when the typing stubs are fully integrated into the main source code this will work in both forms.    for now I could potentially add the generic directives throughout the ColumnElement hierarchy but im not sure it's worth it yet particularly with python 2 still going on.

**Comment by zzzeek** [comment]
Using [mapped_column](https://docs.sqlalchemy.org/en/20/orm/mapping_api.html?highlight=mapped_column#sqlalchemy.orm.mapped_column) in 2.0:

```py
from sqlalchemy import DateTime
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy.orm import declared_attr
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import registry

mapper_registry: registry = registry()


@mapper_registry.mapped
class Company:
    __tablename__ = "company"

    id = mapped_column(Integer, primary_key=True)

    @declared_attr
    def updated_at(cls) -> Mapped[DateTime]:
        return mapped_column(DateTime)


print(select(Company.updated_at))
```

mypy is green
