### ISSUE TITLE
mypy plugin: mixins defined in external libraries supported cannot be annotated with @declarative_mixin

### ISSUE THREAD

**Issue by MaicoTimmerman** [sqlalchemy/sqlalchemy#6228]
**Is your feature request related to a problem? Please describe.**
In 1.4.6. the `@declarative_mixin` decorator is added to add mypy support to base classes. In some cases the mixin is not defined in user code, but comes from a pypi package, therefor the decorator cannot be applied directly. From what I understood from #6147 the decorator is pure cosmetics, could that be extended to function-style usage? That currently results in:

```
error: Unsupported dynamic base class "declarative_mixin"
```

**Describe the solution you'd like**

```py
from sqlalchemy.orm import declarative_mixin
from someotherlibary import Mixin

@mapper_registry.mapped
class A(declarative_mixin(Mixin)):
    __tablename__ = "a"
```

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
I was about to say "no", but im not totally sure.  The dynamic class hook is kind of a PITA wheras the decorator one is simple.

the pypi packages should update themselves to support this, really.

**Comment by zzzeek** [comment]
ill try it later

**Comment by zzzeek** [comment]
mypy does not support classes that come from functions at all, so this was never possible with the plugin.

as this issue is specific to the plugin, this is now a legacy issue as the plugin is no longer needed in SQLAlchemy 2.0 using new patterns.
