### ISSUE TITLE
Documentation of Unicode class assumes non-supported versions of Python

### ISSUE THREAD

**Issue by bkline** [sqlalchemy/sqlalchemy#6238]
**Describe the bug**
The [documentation](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/sqltypes.py#L452) of `sqlalchemy.types.Unicode` says

> When using the `Unicode` type, it is only appropriate to pass Python `unicode` objects, and not plain `str`.

However, for all supported versions of Python, `str` objects are the appropriate objects to be passed for this class.

**Expected behavior**
The documentation should specify the appropriate type (`str`) to be passed for the `Unicode` type. If information on use of the package with obsolete, unsupported versions of Python must be included, that information should be presented as the exception to the rule, not as the basic rule itself.

**To Reproduce**

1. Load the current _Column and Data Types_ [documentation](https://docs.sqlalchemy.org/en/14/core/type_basics.html#sqlalchemy.types.Unicode) in your favorite browser.
2. Read the first sentence of the fifth paragraph (counting the sentence fragment "A variable length Unicode string type." as the first "paragraph").

**Versions.**
 - OS: N/A
 - Python: 3.x
 - SQLAlchemy: 1.4.x
 - Database: N/A
 - DBAPI: N/A

**Have a nice day!**
;-)

**Comment by zzzeek** [comment]
> **Describe the bug**
> The [documentation](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/sqltypes.py#L452) of `sqlalchemy.types.Unicode` says
> 
> > When using the `Unicode` type, it is only appropriate to pass Python `unicode` objects, and not plain `str`.
> 
> However, for all supported versions of Python, `str` objects are the appropriate objects to be passed for this class.

SQLAlchemy currently continues support for [Python 2.7](https://docs.sqlalchemy.org/en/14/intro.html#installation).   We can clarfiy this phrasing to refer to Python 2.7 explicitly since we are dropping Python 2 support in 2.0, however for now, that documentation still applies to Python 2 where we do have lots of users still.   I agree it should be adjusted to not be misleading for the vast majority of users who are Python 3 users.

**Comment by bkline** [comment]
Awesome! That's what I call _responsive_ turnaround!!! 👍
