### ISSUE TITLE
"SADeprecationWarning: The standalone subquery() function is deprecated" should be RemovedIn20Warning

### ISSUE THREAD

**Issue by tometzky** [sqlalchemy/sqlalchemy#6240]
**Describe the bug**
This warning IMHO should not be SADeprecationWarning but RemovedIn20Warning:
SADeprecationWarning: The standalone subquery() function is deprecated and will be removed in a future release.  Use select().subquery(). (deprecated since: 1.4)

As there most probably won't be version 1.5, the warning is useful only when porting to 2.0 with SQLALCHEMY_WARN_20=1.

**Expected behavior**
No warning when SQLALCHEMY_WARN_20 is unset. RemovedIn20Warning when SQLALCHEMY_WARN_20=1

**To Reproduce**

```py
"""Unneeded warning: SADeprecationWarning: The standalone subquery() function is deprecated"""

import sqlalchemy
import sqlalchemy.sql

engine = sqlalchemy.create_engine('sqlite:///:memory:', echo=True)
conn = engine.connect()

subquery = sqlalchemy.sql.subquery(
    "_", [sqlalchemy.sql.func.sqlite_version().label("version")]
)
query = sqlalchemy.sql.select([subquery.c.version])
for row in conn.execute(query):
    print(row[0])
```

**Error**

```
$ python3 -m venv venv
$ venv/bin/pip install pip --upgrade
$ venv/bin/pip install 'sqlalchemy==1.*' --upgrade
$ venv/bin/pip freeze
greenlet==1.0.0
SQLAlchemy==1.4.7
$ venv/bin/python3 deprecated.py
deprecated.py:9: SADeprecationWarning: The standalone subquery() function is deprecated and will be removed in a future release.  Use select().subquery(). (deprecated since: 1.4)
  subquery = sqlalchemy.sql.subquery(
2021-04-10 18:44:36,199 INFO sqlalchemy.engine.Engine SELECT _.version 
FROM (SELECT sqlite_version() AS version) AS _
2021-04-10 18:44:36,199 INFO sqlalchemy.engine.Engine [generated in 0.00012s] ()
3.34.0
```

**Versions.**
 - OS: Fedora 32
 - Python: 3.8.7
 - SQLAlchemy: 1.4.7
 - Database: SQLite 3.34.0

**Additional context**
Unfortunately RemovedIn20Warning messages are almost useless - they don't show the offending line in the source. This makes it almost impossible to figure out where is the problem.

**Comment by zzzeek** [comment]
subquery() standalone is in a category by itself compared to things that are "2.0", SQLAlchemy regularly has normal deprecations in each "minor" release and there's plenty more besides this one (plus this is trivial to update in code).  use the  [warnings filter](https://docs.python.org/3/library/warnings.html#warning-filter) to tune these as you prefer.
