### ISSUE TITLE
With SQLALCHEMY_WARN_20=1 no way to see offending line instead of sqlalchemy source line

### ISSUE THREAD

**Issue by tometzky** [sqlalchemy/sqlalchemy#6241]
**Is your feature request related to a problem? Please describe.**
When I tried to see how much work will be needed to port my code to SQLAlchemy 2.0, I tried to use SQLALCHEMY_WARN_20=1.

Unfortunately the warnings that are generated are not very useful:
```
/var/tmp/deprecated/venv/lib64/python3.8/site-packages/sqlalchemy/sql/selectable.py:88: RemovedIn20Warning: The legacy calling style of select() is deprecated and will be removed in SQLAlchemy 2.0.  Please use the new calling style described at select(). (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
  return Select.create_legacy_select(*args, **kwargs).subquery(alias)
/var/tmp/deprecated/venv/lib64/python3.8/site-packages/sqlalchemy/sql/selectable.py:4893: RemovedIn20Warning: The legacy calling style of select() is deprecated and will be removed in SQLAlchemy 2.0.  Please use the new calling style described at select(). (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
```
Finding offending code will be very difficult without any reference to the file and line number.

**Describe the solution you'd like**
The proper solution would be to check traceback how deep inside module function calls we are and run warnings.warn with proper stacklevel.

**Describe alternatives you've considered**
Some way to print the whole stacktrace in case of RemovedIn20Warning would be easier to implement and maybe good enough for a start.

**Additional context**
```
"""RemovedIn20Warning: no way to see offending line"""

import sqlalchemy
import sqlalchemy.sql

engine = sqlalchemy.create_engine('sqlite:///:memory:', echo=True)
conn = engine.connect()

query = sqlalchemy.sql.select([sqlalchemy.sql.func.sqlite_version()])
for row in conn.execute(query):
    print(row[0])
```
```
$ python3 -m venv venv
$ venv/bin/pip install pip --upgrade
$ venv/bin/pip install 'sqlalchemy==1.*' --upgrade
$ venv/bin/pip freeze
greenlet==1.0.0
SQLAlchemy==1.4.7
$ SQLALCHEMY_WARN_20=1 venv/bin/python3 -W always::DeprecationWarning offending.py
/var/tmp/deprecated/venv/lib64/python3.8/site-packages/sqlalchemy/sql/selectable.py:4893: RemovedIn20Warning: The legacy calling style of select() is deprecated and will be removed in SQLAlchemy 2.0.  Please use the new calling style described at select(). (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
  return cls.create_legacy_select(*args, **kw)
2021-04-10 19:11:31,978 INFO sqlalchemy.engine.Engine SELECT sqlite_version() AS sqlite_version_1
2021-04-10 19:11:31,978 INFO sqlalchemy.engine.Engine [generated in 0.00012s] ()
3.34.0
```

**Comment by zzzeek** [comment]
> **Is your feature request related to a problem? Please describe.**
> When I tried to see how much work will be needed to port my code to SQLAlchemy 2.0, I tried to use SQLALCHEMY_WARN_20=1.
> 
> Unfortunately the warnings that are generated are not very useful:
> 
> ```
> /var/tmp/deprecated/venv/lib64/python3.8/site-packages/sqlalchemy/sql/selectable.py:88: RemovedIn20Warning: The legacy calling style of select() is deprecated and will be removed in SQLAlchemy 2.0.  Please use the new calling style described at select(). (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
>   return Select.create_legacy_select(*args, **kwargs).subquery(alias)
> /var/tmp/deprecated/venv/lib64/python3.8/site-packages/sqlalchemy/sql/selectable.py:4893: RemovedIn20Warning: The legacy calling style of select() is deprecated and will be removed in SQLAlchemy 2.0.  Please use the new calling style described at select(). (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
> ```
> 
> Finding offending code will be very difficult without any reference to the file and line number.

Python very foolishly does not have a simple way to tell it where it should break on stack traces, some way where we could tell it to emit the warning in terms of code that is one level removed from the last module called "sqlalchemy".   to do this we would have to inspect the stack frames when warnings are emitted which would be a performance hit.   instead, the option they give you is to [hardcode the stack level](https://docs.python.org/3/library/warnings.html#warnings.warn) which will help a little bit but is not very flexible.

we have our stacklevel for these warnings tuned to try to give the right answer but it's extremely difficult to have these come out correctly in all cases.     maybe at some point we should just go for the dynamic frame inspection thing.  but in the interim....  read on


> 
> **Describe the solution you'd like**
> The proper solution would be to check traceback how deep inside module function calls we are and run warnings.warn with proper stacklevel.

this is a performance hit.   warnings.warn() is implemented in C in the Python std lib, including the frame inspection that it does right now and we'd have to bypass that and do it ourselves, then call warn_explicit()     are you familiar with any libraries that use this approach right now?


> 
> **Describe alternatives you've considered**
> Some way to print the whole stacktrace in case of RemovedIn20Warning would be easier to implement and maybe good enough for a start.

just turn on -Werror and you'll get a stack trace, that's usually what people do.

**Comment by zzzeek** [comment]
this could be applicable to the "sqlalchemy 2.0" warnings because if the environment vartiable isn't set, we dont do the warning at all, so the perf hit for those warnings specifically would be limited.

**Comment by zzzeek** [comment]
here's a way to do that, would not feel confident it's going to work on every python env everywhere. IMO this really should be part of Python

```diff
diff --git a/lib/sqlalchemy/util/deprecations.py b/lib/sqlalchemy/util/deprecations.py
index 5d55a3ae61..729d668249 100644
--- a/lib/sqlalchemy/util/deprecations.py
+++ b/lib/sqlalchemy/util/deprecations.py
@@ -11,6 +11,7 @@ functionality."""
 import os
 import re
 import warnings
+import sys
 
 from . import compat
 from .langhelpers import _hash_limit_string
@@ -38,6 +39,22 @@ def _warn_with_version(msg, version, type_, stacklevel):
     warn = type_(msg)
     warn.deprecated_since = version
 
+    # guess how to tell where we are running from
+    install_path = re.sub(
+        r"sqlalchemy.util.deprecations.py[co]?$", "sqlalchemy", __file__
+    )
+    frame = sys._getframe(1)
+
+    # walk through frames and guess some more
+    stacklevel = 1
+    while frame is not None and (
+        frame.f_code.co_filename.startswith(install_path)
+        or "<string>" in frame.f_code.co_filename
+    ):
+        frame = frame.f_back
+        stacklevel += 1
+
+    # then call warnings with that stacklevel
     warnings.warn(warn, stacklevel=stacklevel + 1)
 

```

**Comment by tometzky** [comment]
Can you add this `-Werror` hint to [Migrating to SQLAlchemy 2.0](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings)?

I just felt like I had one of those [Ten Thousand](https://xkcd.com/1053/) moments. I just had monkey-patched sqlalchemy to figure out which line in my project generated some warning.

Maybe somebody would find the time to code a pylint plugin for finding such errors, so it will create a list of lines to fix. Currently the warnings will only show when code is run and rarely projects have 100% test code coverage.

**Comment by CaselIT** [comment]
> 
> 
> here's a way to do that, would not feel confident it's going to work on every python env everywhere. IMO this really should be part of Python
> 
> ```diff
> diff --git a/lib/sqlalchemy/util/deprecations.py b/lib/sqlalchemy/util/deprecations.py
> index 5d55a3ae61..729d668249 100644
> --- a/lib/sqlalchemy/util/deprecations.py
> +++ b/lib/sqlalchemy/util/deprecations.py
> @@ -11,6 +11,7 @@ functionality."""
>  import os
>  import re
>  import warnings
> +import sys
>  
>  from . import compat
>  from .langhelpers import _hash_limit_string
> @@ -38,6 +39,22 @@ def _warn_with_version(msg, version, type_, stacklevel):
>      warn = type_(msg)
>      warn.deprecated_since = version
>  
> +    # guess how to tell where we are running from
> +    install_path = re.sub(
> +        r"sqlalchemy.util.deprecations.py[co]?$", "sqlalchemy", __file__
> +    )
> +    frame = sys._getframe(1)
> +
> +    # walk through frames and guess some more
> +    stacklevel = 1
> +    while frame is not None and (
> +        frame.f_code.co_filename.startswith(install_path)
> +        or "<string>" in frame.f_code.co_filename
> +    ):
> +        frame = frame.f_back
> +        stacklevel += 1
> +
> +    # then call warnings with that stacklevel
>      warnings.warn(warn, stacklevel=stacklevel + 1)
>  
> ```

I think this may be something that can be turned on with an env variable, since it look as if it would have quite a performance impact. Also it does not help if the user is a 3rd party library, like pandas or flask_sa.

I'll add the tip in the migration files regardgin -Werror

**Comment by sqla-tester** [comment]
**Federico Caselli** referenced this issue:

**Mention how to turn warning to exceptions** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2743

**Comment by zzzeek** [comment]
Replying by email

I have a way to make it work, which is to pass an empty lambda from where the func is called, then we cache the stacklevel on the __code__ attribute, thus associating stack levels with physical code locations.  It will be plenty fast then 

On Wed, Apr 14, 2021, at 4:33 PM, Federico Caselli wrote:
> 

>> here's a way to do that, would not feel confident it's going to work on every python env everywhere. IMO this really should be part of Python

>> diff --git a/lib/sqlalchemy/util/deprecations.py b/lib/sqlalchemy/util/deprecations.py
index 5d55a3ae61..729d668249 100644
>> --- a/lib/sqlalchemy/util/deprecations.py
>> +++ b/lib/sqlalchemy/util/deprecations.py
>> @@ -11,6 +11,7 @@ functionality."""
 import os
 import re
 import warnings
>> +import sys
 
 from . import compat
 from .langhelpers import _hash_limit_string
>> @@ -38,6 +39,22 @@ def _warn_with_version(msg, version, type_, stacklevel):
     warn = type_(msg)
     warn.deprecated_since = version
 
>> +    # guess how to tell where we are running from
>> +    install_path = re.sub(
>> +        r"sqlalchemy.util.deprecations.py[co]?$", "sqlalchemy", __file__
>> +    )
>> +    frame = sys._getframe(1)
>> +
>> +    # walk through frames and guess some more
>> +    stacklevel = 1
>> +    while frame is not None and (
>> +        frame.f_code.co_filename.startswith(install_path)
>> +        or "<string>" in frame.f_code.co_filename
>> +    ):
>> +        frame = frame.f_back
>> +        stacklevel += 1
>> +
>> +    # then call warnings with that stacklevel
     warnings.warn(warn, stacklevel=stacklevel + 1)

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**calculate warnings stacklevels dynamically** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2812
