### ISSUE TITLE
multirow RETURNING for oracle

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6245]
per cx_oracle devs the OUT params we use will store ilsts if the statement is multiple row.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**cx_Oracle modernize** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3768

**Comment by zzzeek** [comment]
well that took about 5 minutes.   Could have had this a while ago :)

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement executemany RETURNING for Oracle** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4000
