### ISSUE TITLE
The mypy plugin is unable to map forward references for relationships

### ISSUE THREAD

**Issue by Parnassius** [sqlalchemy/sqlalchemy#6255]
**Describe the bug**
The mypy plugin is unable to set the correct type for relationships which refer to classes found later in the same file.

**Expected behavior**
It should be able to set the correct type. To be honest I'm not sure if this is a bug in the plugin, or a limitation in mypy's plugin system. Or simply a yet-to-be-implemented feature.

**To Reproduce**
Default mypy settings, `mypy.ini` contains only the line to enable sqlalchemy's plugin.
```python
from typing import List, Optional
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import Mapped, declarative_base, relationship

Base = declarative_base()

class User(Base):
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True)
    name = Column(String)

    addresses: List["Address"] = relationship("Address", back_populates="user")

    @property
    def some_property(self) -> List[Optional[int]]:
        return [i.id for i in self.addresses]

class Address(Base):
    __tablename__ = 'address'

    id = Column(Integer, primary_key=True)
    user_id: int = Column(ForeignKey("user.id"))

    user: "User" = relationship("User", back_populates="addresses")

    @property
    def some_other_property(self) -> Optional[str]:
        return self.user.name
```

**Error**

```
foo.py:17: error: "List?[Address?]" has no attribute "__iter__" (not iterable)
Found 1 error in 1 file (checked 1 source file)
```

Swapping the positions of the two classes the error above goes away, but it gets replaced by this (line 17 here refers to the last line of the snippet above):
```
bar.py:17: error: User? has no attribute "name"
```

**Versions.**
 - OS: Debian 10
 - Python: 3.7.10, 3.9.4, 3.8.9
 - SQLAlchemy: 1.4.7
 - sqlalchemy2-stubs: 0.0.1a4
 - mypy: 0.812

**Comment by zzzeek** [comment]
very strange because this passes:

```
    class User(Base):
        __tablename__ = 'user'

        id = Column(Integer, primary_key=True)
        name = Column(String)

        addresses: List["Address"] #= relationship("Address", back_populates="user")

```

so something about how we are applying the type is causing a problem

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Re-infer statements that got more specific on subsequent pass** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2761
