### ISSUE TITLE
try to get rid of str(self) in proxy label mechanics once and for all

### ISSUE THREAD

**Issue by adamhadani** [sqlalchemy/sqlalchemy#6256]
**Describe the bug**
I've [recently hit a a breaking test](https://github.com/globality-corp/microcosm-eventsource/pull/74) in an open source library we maintain. 

The issue involves the use of`sqlalchemy.ext.compiler.compile` decorator.

We currently have two definitions of a function, one for a "default" dialect, and one specifically for postgresql (see [here](https://github.com/globality-corp/microcosm-eventsource/blob/develop/microcosm_eventsource/func.py#L67) for context):

```python
@compiles(last)
def compile(element, compiler, **kwargs):
    """
    By default, `last` is not defined.
    """
    raise NotImplementedError("last is only defined for postgresql")


@compiles(last, "postgresql")
def compile_postgres(element, compiler, **kwargs):
    """
    Define `last` in terms of the custom functions.
    """
    return f"last_agg({compiler.process(element.clauses)})"

```

Up to 1.4, this worked well enough - but since 1.4 it seems like having both definitions doesn't work: the sqlalchemy runtime seems to somehow pick up the "wrong" one (the default one rather than the postgresql one) when running our unit-tests.

If I simply remove the default one altogether, everything works fine. In `1.3.x`, this wasn't an issue however - I was able to have both definitions and have the sqlalchemy runtime use the right one everytime.

Is this intended behavior? any tips would be helpful, otherwise seems to me like a bug.

**Expected behavior**
Having multiple definitions for a function element `compiles()` block for different dialects should work as it did before `1.4` release.

**To Reproduce**

Please see [here](https://github.com/globality-corp/microcosm-eventsource/blob/develop/microcosm_eventsource/tests/test_func.py#L63) for unit-test which used to work and now fails. the actual code which is relevant is linked to above, for completeness here it is again:

```py
class last(FunctionElement):
    """
    Define a SQLAlchemy function that maps to a postgres function to select the last non-null value in window.
    """
    name = "last"

    @classmethod
    def of(cls, column, *filter_by):
        """
        Generate a window function over an event's column.
        """
        event = column.class_
        return cls(column).filter(*filter_by).over(
            order_by=event.clock.asc(),
            partition_by=event.container_id,
        )


@compiles(last)
def compile(element, compiler, **kwargs):
    """
    By default, `last` is not defined.
    """
    raise NotImplementedError("last is only defined for postgresql")


@compiles(last, "postgresql")
def compile_postgres(element, compiler, **kwargs):
    """
    Define `last` in terms of the custom functions.
    """
    return f"last_agg({compiler.process(element.clauses)})"

```

**Error**

See above, there is no explicit error message, rather the wrong specification is picked up by the runtime which doesnt match the active dialect when using `compiles()` on a `FunctionElement` class multiple times for different dialects.

**Versions.**
 - OS: OSX
 - Python: 3.8.1
 - SQLAlchemy: 1.4.x
 - Database: postgresql
 - DBAPI: psycopg2

**Comment by zzzeek** [comment]
hey there - 

not sure what's different in your test but I can't reproduce this in a simple setup:
```

from sqlalchemy.sql.functions import FunctionElement
from sqlalchemy.ext.compiler import compiles
from sqlalchemy import column, select, create_engine
from sqlalchemy.dialects import postgresql

class now(FunctionElement):
    name = "now"



@compiles(now)
def compile(element, compiler, **kwargs):
    raise NotImplementedError("last is only defined for postgresql")


@compiles(now, "postgresql")
def compile_postgres(element, compiler, **kwargs):
    return "current_timestamp"


def go(engine):
    stmt = select(now())

    with engine.connect() as conn:
        conn.execute(stmt).scalar()


engine = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
go(engine)

go(engine)
```

it's also unclear what the failure mode you are seeing is, you say " there is no explicit error message, rather the wrong specification is picked up by the runtime for different dialects", your code seems to have only the PostgreSQL dialect defined.    Are there other implementations for other backends that don't raise notimplemented?   What is the SQL output you are seeing?       Does it include any verbiage about caching?  The functionelement you have does not have caching indicators so the log output should indicate "No Key".

if you can construct a self contained [MCVE](http://stackoverflow.com/help/mcve) that would be helpful.

**Comment by adamhadani** [comment]
@zzzeek hey and thanks for the prompt and detailed response. I spent some more time on it today and was able to produce an MCVE as you suggested. This did help me pin down the issue to something to do with the usage of `from_self()`:

```python
#!/usr/bin/env python
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.sql.functions import FunctionElement
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import declarative_base, sessionmaker


Base = declarative_base()


class User(Base):
     __tablename__ = 'users'

     id = Column(Integer, primary_key=True)
     name = Column(String)


class now(FunctionElement):
    name = "now"


@compiles(now)
def compile(element, compiler, **kwargs):
    raise NotImplementedError(f"this function is only defined for postgresql")


@compiles(now, "postgresql")
def compile_postgres(element, compiler, **kwargs):
    return "current_timestamp"


def go(engine):
    Session = sessionmaker(bind=engine)
    with engine.connect() as conn:
        session = Session()
        session.query(
            now(),
        ).from_self().all()


def main():
    engine = create_engine("postgresql://test@localhost/test_db", echo=True)
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)
    go(engine)


if __name__ == "__main__":
	main()
```

Some more info from my debugging

I *think* there is something along the way when using `from_self` which loses the current dialect as context. I was able to get one stack trace at some point using the more elaborate unit-tests I pointed to above which included the following snippet:

```
 File "/Users/adamever-hadani/.pyenv/versions/3.8.1/envs/microcosm-eventsource/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 905, in _proxy_key
    return str(self)
  File "/Users/adamever-hadani/.pyenv/versions/3.8.1/envs/microcosm-eventsource/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 572, in __str__
    return str(self.compile())
  File "/Users/adamever-hadani/.pyenv/versions/3.8.1/envs/microcosm-eventsource/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 505, in compile
    return self._compiler(dialect, **kw)
  File "/Users/adamever-hadani/.pyenv/versions/3.8.1/envs/microcosm-eventsource/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 568, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
```

In particular, using `str(self)` as the key in sqlalchemy.sql.elements (line 905 in _proxy_key per above stack trace), seems to end up with a call to `compile()` without passing any arguments, and in particular without passing the dialect.

The stack is quite elaborate so I would hope for some help tracing this back further.

Another note: I read the migration notes which suggest that `from_self` is deprecated in favor of `aliased`. I am able to reproduce the same issue when using aliased however, e.g.:

```python
#!/usr/bin/env python
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.sql.functions import FunctionElement
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.orm import aliased, declarative_base, sessionmaker


Base = declarative_base()


class User(Base):
     __tablename__ = 'users'

     id = Column(Integer, primary_key=True)
     name = Column(String)


class now(FunctionElement):
    name = "now"


@compiles(now)
def compile(element, compiler, **kwargs):
    raise NotImplementedError(f"this function is only defined for postgresql")


@compiles(now, "postgresql")
def compile_postgres(element, compiler, **kwargs):
    return "current_timestamp"


def go(engine):
    Session = sessionmaker(bind=engine)
    with engine.connect() as conn:
        session = Session()
        subq = session.query(
            now(),
        ).subquery()

        alias = aliased(subq)

        return session.query(User, subq).all()


def main():
    engine = create_engine("postgresql://test@localhost/test_db", echo=True)
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)
    go(engine)


if __name__ == "__main__":
	main()
```

**Comment by zzzeek** [comment]
this is an old issue that comes around from time to time, and I did actually fix something here very recently in 1.4 related to this so im not sure how it's surfaced again.  if you look in the stack trace, there's a naive str() being called:

File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 1093, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 907, in _proxy_key
    return str(self)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 574, in __str__
    return str(self.compile())

I'll look up the issue I fixed in 1.4 with a similar problem.   anyway the workaround is simple, give your function a label so that it doesnt' have to invent a key:

        subq = session.query(
            now().label(),
        ).subquery()

**Comment by zzzeek** [comment]
thanks for taking the time to create a great test case!

**Comment by zzzeek** [comment]
#6086 was similar

**Comment by zzzeek** [comment]
this condition can be reproduced in 1.3 as well like this, so this is not new, it's just the ORM is working in a more "core-like" way now so we see it in more places:

```
#!/usr/bin/env python
from sqlalchemy import select
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql.functions import FunctionElement


class now(FunctionElement):
    name = "now"


@compiles(now)
def compile(element, compiler, **kwargs):
    raise NotImplementedError(f"this function is only defined for postgresql")


@compiles(now, "postgresql")
def compile_postgres(element, compiler, **kwargs):
    return "current_timestamp"

subq = select([now()]).alias()

stmt = select([subq])

print(stmt.compile(dialect=postgresql.dialect()))

```

```
 File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 844, in _make_proxy
    key = str(self)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 491, in __str__
    return str(self.compile())
  File "<string>", line 1, in <lambda>
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 481, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 487, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 592, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 322, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/sql/compiler.py", line 352, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/ext/compiler.py", line 443, in <lambda>
    lambda *arg, **kw: existing(*arg, **kw),
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/ext/compiler.py", line 490, in __call__
    return fn(element, compiler, **kw)
  File "/home/classic/dev/sqlalchemy/test3.py", line 14, in compile
    raise NotImplementedError(f"this function is only defined for postgresql")
NotImplementedError: this function is only defined for postgresql
[classic@photon3 sqlalchemy:rel_1_3]$ 
``

**Comment by zzzeek** [comment]
so...... we can just catch NotImplementedError also, or you could modify your recipe as follows:

```
from sqlalchemy import exc

@compiles(now)
def compile(element, compiler, **kwargs):
    raise exc.UnsupportedCompilationError(
        compiler, "now", f"this function is only defined for postgresql"
    )

```


what I might do is catch all exceptions here and then warn that UnsupportedCompilationError should be raised.

**Comment by adamhadani** [comment]
awesome, thanks so much @zzzeek - and yes I figured it was that "naked" call to compile() from the str() as well. thanks for the workaround

**Comment by zzzeek** [comment]
I'm going to take another crack at getting rid of that str() call.  it just shouldnt be there.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Don't stringify unnamed column elements when proxying** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2750
