### ISSUE TITLE
Binary Type Import breaking change

### ISSUE THREAD

**Issue by codedawi** [sqlalchemy/sqlalchemy#6263]
**Describe the bug**

The `BINARY` only exposes all caps and no longer Pascal-style case format between `1.3` and `1.4`

https://github.com/sqlalchemy/sqlalchemy/blob/d3c3982100a617623c92b41799b19f27448a1574/lib/sqlalchemy/__init__.py#L92

**Expected behavior**
Be able to import types consistently.

**To Reproduce**

```python
from sqlalchemy import Binary, Column, DateTime, String
```

**Error**

```
ImportError: cannot import name 'Binary' from 'sqlalchemy'
```

**Comment by zzzeek** [comment]
hey there -

The ``Binary`` symbol, which is a synonym for [LargeBinary](https://docs.sqlalchemy.org/en/14/core/type_basics.html?highlight=largebinary#sqlalchemy.types.LargeBinary), was deprecated in 2010 and was removed in 1.4:

https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-214869a306f72f33237772d33fc332ec

#4643  

unfortunately there is no straightforward Python mechanism for emitting a deprecation warning on a symbol import.

**Comment by CaselIT** [comment]
> unfortunately there is no straightforward Python mechanism for emitting a deprecation warning on a symbol import.

at least not until python 3.7+ where we could use module level `__getattr__`. Maybe for sa2 :)

**Comment by codedawi** [comment]
Great thank you for the information ! We updated/migrated in our code.
