### ISSUE TITLE
How can I check if the C extensions are installed on a system?

### ISSUE THREAD

**Issue by LostInDarkMath** [sqlalchemy/sqlalchemy#6276]
I wonder if there is a way to figure out if the C extensions are installed. How can I do that
- on Windows?
- on Linux?

**Comment by CaselIT** [comment]
Hi,

If you install from pip on a compatible architecture the wheel have c extensions active.

That said you can look at https://github.com/sqlalchemy/sqlalchemy/blob/master/.github/workflows/create-wheels.yaml#L90 for 1.4 and https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3/.github/workflows/create-wheels.yaml#L91 for 1.3

note that these api are to be considered private, so they may change in the future.
