### ISSUE TITLE
`next_value` should derive `type` from `Sequence.data_type`

### ISSUE THREAD

**Issue by bryanforbes** [sqlalchemy/sqlalchemy#6287]
**Is your feature request related to a problem? Please describe.**
Currently, the `next_value` class always has a `type` of `Integer`. However, `Sequence.data_type` was added in 1.4 and should set `next_value.type`.

**Describe the solution you'd like**
```python
s = Sequence('foo', data_type=BigInteger)
n = s.next_value()
assert s.data_type.__class__ == n.type.__class__
```

**Comment by sqla-tester** [comment]
**Bryan Forbes** has proposed a fix for this issue in the **master** branch:

**Derive `next_value.type` from `Sequence.data_type` if available** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2748
