### ISSUE TITLE
Explicit commit in transaction context manager causes error.

### ISSUE THREAD

**Issue by danielknell** [sqlalchemy/sqlalchemy#6288]
**Describe the bug**

when explicitly committing a transaction in a context manager, it throws an error, this seems to be caused by a `_assert_active` call in `Transaction.__exit__`.

this is implied to work via code examples in the docs and it looks like the code following the assert handles a a transaction being already committed and just returns early?

**Expected behavior**
No error

**To Reproduce**

```py
import sqlalchemy.orm

engine = sqlalchemy.create_engine(
    "postgresql://postgres:postgres@db:5432/postgres", 
    future=True,
)

with sqlalchemy.orm.Session(engine, expire_on_commit=False) as session:
    with session.begin():
        session.execute("SELECT 1")
        session.commit()
```

**Error**

```pytb
Traceback (most recent call last):
  File "{snip}/test.py", line 10, in <module>
    session.commit()
  File "{snip}/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 937, in __exit__
    self._assert_active(deactive_ok=True, prepared_ok=True)
  File "{snip}/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 617, in _assert_active
    raise sa_exc.ResourceClosedError(closed_msg)
sqlalchemy.exc.ResourceClosedError: This transaction is closed
```

**Versions.**
 - OS: linux
 - Python: 3.9
 - SQLAlchemy: 1.4.8
 - Database: postgres
 - DBAPI: psycopg2 or asyncpg

**Comment by zzzeek** [comment]
I need to check the precedent for this on Connection, as I just made some adjustment to some of this in #6155.

It looks like the commit is allowed, but the rest of the block is then rolled back:

```python
import sqlalchemy.orm

engine = sqlalchemy.create_engine(
    "sqlite://", future=True, echo=True
)

with engine.begin() as conn:
    conn.execute(sqlalchemy.text("SELECT 1"))
    conn.commit()

    conn.execute(sqlalchemy.text("SELECT 2"))

```

output:

```
2021-04-15 12:39:30,922 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-04-15 12:39:30,922 INFO sqlalchemy.engine.Engine SELECT 1
2021-04-15 12:39:30,922 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ()
2021-04-15 12:39:30,923 INFO sqlalchemy.engine.Engine COMMIT
2021-04-15 12:39:30,923 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-04-15 12:39:30,923 INFO sqlalchemy.engine.Engine SELECT 2
2021-04-15 12:39:30,923 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ()
2021-04-15 12:39:30,923 INFO sqlalchemy.engine.Engine ROLLBACK
```

I recall handwringing about that a great deal, because IMO this leads into the area of ambiguous behavior which I think we need to get away from.   I believe the change was related to rollback(), and perhaps commt() should be raising regardless because what should the rest of the block do?   is the above what you'd expect?

Just FTR, this doesn't work on 1.3 either, using a 1.3 pattern such as:

```python
session = sqlalchemy.orm.Session(engine, expire_on_commit=False)
with session.begin():
    session.execute("SELECT 1")
    session.commit()
```

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 8, in <module>
    with session.begin():
  File "/home/classic/tmp/sqlalchemy/lib/sqlalchemy/orm/session.py", line 959, in begin
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: A transaction is already begun.  Use subtransactions=True to allow subtransactions.
[classic@photon3 sqlalchemy:rel_1_3]$ g
```

**Comment by zzzeek** [comment]
> 
> this is implied to work via code examples in the docs and it looks like the code following the assert handles a a transaction being already committed and just returns early?

can you point those out please?   This should not be a pattern casually used in the docs as it is IMO unclear.

**Comment by danielknell** [comment]
actually, i imagined that... it was the session maker in `with` i was thinking of.

**Comment by zzzeek** [comment]
sorry I'm not folllowing.  thanks for reporitng BTW and sorry i am not following, i attend to dozens of issues every day at the moment.

**Comment by CaselIT** [comment]
> with engine.begin() as conn:
>     conn.execute(sqlalchemy.text("SELECT 1"))
>     conn.commit()
> 
>     conn.execute(sqlalchemy.text("SELECT 2"))
> ```
> 
> output:
> 
> ```
> 2021-04-15 12:39:30,922 INFO sqlalchemy.engine.Engine BEGIN (implicit)
> 2021-04-15 12:39:30,922 INFO sqlalchemy.engine.Engine SELECT 1
> 2021-04-15 12:39:30,922 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ()
> 2021-04-15 12:39:30,923 INFO sqlalchemy.engine.Engine COMMIT
> 2021-04-15 12:39:30,923 INFO sqlalchemy.engine.Engine BEGIN (implicit)
> 2021-04-15 12:39:30,923 INFO sqlalchemy.engine.Engine SELECT 2
> 2021-04-15 12:39:30,923 INFO sqlalchemy.engine.Engine [generated in 0.00008s] ()
> 2021-04-15 12:39:30,923 INFO sqlalchemy.engine.Engine ROLLBACK
> ```
> 
> I recall handwringing about that a great deal, because IMO this leads into the area of ambiguous behavior which I think we need to get away from. I believe the change was related to rollback(), and perhaps commt() should be raising regardless because what should the rest of the block do? is the above what you'd expect?
 
I would expect that code to issue a commit at the end. I'm actually surprised it does not. IIRC `begin` should simply commit if not an error, rollback if an error

**Comment by zzzeek** [comment]
see im still not comfortable with what I did in #6155.  any ambiguity like this should just be forbidden.    i think it should go into "commit as you go" mode which is what the engine does now.  otherwise I have to change it again.   what if they called rollback()?    it should then...commit at the end anyway ?

**Comment by CaselIT** [comment]
yes, it should do so.

IMHO, `begin` should basically do the same as this recepie:
https://docs.sqlalchemy.org/en/14/orm/session_basics.html#framing-out-a-begin-commit-rollback-block

```py
def begin():
    conn = self.get_con()
    try:
        yield conn
    except:
        conn.rollback()
        raise
    else:
        conn.commit()
```

I think most people would expect this behavior. Having it go in commit as you go in some cases complicates the api without a clear benefit in my opinion

**Comment by zzzeek** [comment]
i wonder why the engine version isn't doing that?  this is a behavioral change in 1.4 since both session/engine have to be 100% consistent, that's the main goal

**Comment by zzzeek** [comment]
um.   no still not sure.   if you open a file, then close it:

with open("foo", "w") as f:
    f.write("foo")

**Comment by CaselIT** [comment]
not sure what you mentioned by the file case does what I mentioned:

```py
with open("foo", "w") as f:
    f.write("x")
    c = f.close

    def mock(*args, **kw):
        print("called")
        c(*args, **kw)

    f.close = mock
    f.close()
```
prints
```
called
called
```
and does not do any error

**Comment by zzzeek** [comment]
I got pulled away.  check it out now.

**Comment by zzzeek** [comment]
```
>>> with open("foo", "w") as f:
...     f.write("a")
...     f.close()
...     f.write("b")
... 
1
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
ValueError: I/O operation on closed file.

```

**Comment by zzzeek** [comment]
I'd be most comfortable w/ behavior like that

**Comment by zzzeek** [comment]
which...is not easily feasible here.    

the reason the context manager doesn't "commit" is because it has "self.transaction", which it checks if it's active, and if not, just skips it.   it doesn't do "self.connection.transaction", which would be whatever transacvtion is current to the connection.

**Comment by zzzeek** [comment]
taht is, this is what the context manager actually does:
```

@contexmanager
def begin():
    conn = get_con()
    trans = conn.begin()
    try:
        yield conn
    except:
        trans.rollback()
        raise
    else:
        trans.commit()
```

totally different

**Comment by CaselIT** [comment]
I guess it would work, but it's not compatible with how the session work.
Also it seems quite arbitrary since the connection is still open, we have not really closed it. I guess we closed the transaction, but since `conn` is a connection, not a transaction, so it seems strange to make it behave like it's closed in that case.

**Comment by CaselIT** [comment]
> 
> 
> taht is, this is what the context manager actually does:
> 
> ```
> 
> @contexmanager
> def begin():
>     conn = get_con()
>     trans = conn.begin()
>     try:
>         yield conn
>     except:
>         trans.rollback()
>         raise
>     else:
>         trans.commit()
> ```
> 
> totally different

I guess what I meant would be this, assuming that the connection would restart a transaction automatically once one commit/rollback was issued
```py
@contexmanager
def begin():
    conn = get_con()
    trans = conn.begin()
    try:
        yield conn
    except:
        if conn.current_trans:
            conn.current_trans.rollback()
        raise
    else:
       if conn.current_trans:
           conn.current_trans.commit()
```

**Comment by zzzeek** [comment]
I think it's surprising someone woudl call rollback() in the middle of the context manager and then a new transaction is implicitly begun that's committed.   I think rollback() by default is the safest bet, short of entirely disallowing further SQL.

**Comment by CaselIT** [comment]
> 
> 
> I think it's surprising someone woudl call rollback() in the middle of the context manager and then a new transaction is implicitly begun that's committed. I think rollback() by default is the safest bet, short of entirely disallowing further SQL.

I honestly would prefer an error in that case to rollback.
```py
with conn.begin():
  res = conn.exec_driver_sql('insert ... returning id').scalar()
  if res % 2:
    conn.rollback()
  conn.exec_driver_sql('insert ... returning id')
```
In this (stupid) example would be impossible to know if the last statement was committed or not, no error is emitted, then someone starts investigating why it does not work and it's not immediately obvious.

So in my opinion we could do:
- raise if further execution happens once a rollback is called
- after a commit start a new transaction and commit at the end

**Comment by zzzeek** [comment]
OK here are the tests:

```python
# engine (Future only)
import sqlalchemy

engine = sqlalchemy.create_engine(
    "sqlite://", future=True, echo=True
)

with engine.begin() as conn:
    conn.execute(sqlalchemy.text("SELECT 1"))
    conn.commit()

    conn.execute(sqlalchemy.text("SELECT 2"))
```

```python
# session (future only)
from sqlalchemy import orm
import sqlalchemy

engine = sqlalchemy.create_engine(
    "sqlite://", future=True, echo=True
)

with orm.Session(engine, future=True) as session:
    with session.begin():
        session.execute(sqlalchemy.text("SELECT 1"))
        session.commit()

        session.execute(sqlalchemy.text("SELECT 2"))
```

```python
# connection (future only)
import sqlalchemy

engine = sqlalchemy.create_engine(
    "sqlite://", future=True, echo=True
)

with engine.connect() as conn:

    with conn.begin():
        conn.execute(sqlalchemy.text("SELECT 1"))
        conn.commit()

        conn.execute(sqlalchemy.text("SELECT 2"))
```



patch:

```diff
diff --git a/lib/sqlalchemy/engine/base.py b/lib/sqlalchemy/engine/base.py
index 20d11e578e..c4172481b5 100644
--- a/lib/sqlalchemy/engine/base.py
+++ b/lib/sqlalchemy/engine/base.py
@@ -2278,6 +2278,12 @@ class Transaction(object):
                     self.rollback()
         else:
             if self._deactivated_from_connection:
+                if self.connection._is_future and self.connection._transaction:
+                    raise exc.InvalidRequestError(
+                        "Transactional state present on connection "
+                        "after commit/rollback has occurred in block"
+                    )
+
                 self.close()
             else:
                 self.rollback()
diff --git a/lib/sqlalchemy/future/engine.py b/lib/sqlalchemy/future/engine.py
index efd0b0eab9..671dee05ba 100644
--- a/lib/sqlalchemy/future/engine.py
+++ b/lib/sqlalchemy/future/engine.py
@@ -3,6 +3,7 @@ from ..engine import Connection as _LegacyConnection
 from ..engine import create_engine as _create_engine
 from ..engine import Engine as _LegacyEngine
 from ..engine.base import OptionEngineMixin
+from .. import exc

 NO_OPTIONS = util.immutabledict()

@@ -384,6 +385,12 @@ class Engine(_LegacyEngine):
                 else:
                     if self.transaction.is_active:
                         self.transaction.commit()
+
+                if self.conn._transaction:
+                    raise exc.InvalidRequestError(
+                        "Transactional state present on connection "
+                        "after commit/rollback has occurred in block"
+                    )
             finally:
                 self.conn.close()

diff --git a/lib/sqlalchemy/orm/session.py b/lib/sqlalchemy/orm/session.py
index d5f418b1ca..6159eef040 100644
--- a/lib/sqlalchemy/orm/session.py
+++ b/lib/sqlalchemy/orm/session.py
@@ -518,6 +518,7 @@ class SessionTransaction(object):
     """

     _rollback_exception = None
+    _enter_session = None

     def __init__(
         self,
@@ -931,10 +932,23 @@ class SessionTransaction(object):
         self._connections = None

     def __enter__(self):
+        self._enter_session = self.session
         return self

     def __exit__(self, type_, value, traceback):
-        self._assert_active(deactive_ok=True, prepared_ok=True)
+        _enter_session = self._enter_session
+        self._enter_session = None
+
+        if not _enter_session.future:
+            self._assert_active(deactive_ok=True, prepared_ok=True)
+        elif self.session is None:
+            if _enter_session._transaction:
+                raise sa_exc.InvalidRequestError(
+                    "Transactional state present on "
+                    "session after commit/rollback has occurred in block"
+                )
+            return
+
         if self.session._transaction is None:
             return
         if type_ is None:

```

**Comment by zzzeek** [comment]
by making this w future only for both, we buy ourselves a little bit of permsision to make a change here.  for the ORM, the current case raises immediately but for Core it currently goes into "commit as you go" mode.

the problem with the above patch is that it doesnt raise until the block ends.  it's not like people wouldn't see the error the first time they run their program though so i think this is fine.

**Comment by CaselIT** [comment]
> 
> 
> by making this w future only for both, we buy ourselves a little bit of permsision to make a change here. for the ORM, the current case raises immediately but for Core it currently goes into "commit as you go" mode.
> 
> the problem with the above patch is that it doesnt raise until the block ends. it's not like people wouldn't see the error the first time they run their program though so i think this is fine.

does this commit something with the above patch?
```py
with conn.begin() as conn:
  conn.execucte(insert(...))
  conn.rollback()
  conn.execucte(insert(...))
  conn.commit()
```

because if it does I think it should raise immediacy or at least prevent the commit

**Comment by zzzeek** [comment]
Ok then you haev to add a flag to connetion / session / etc. called "no transactions allowed".  yucky

**Comment by CaselIT** [comment]
I think so, yes. if we want to have this logic here https://github.com/sqlalchemy/sqlalchemy/issues/6288#issuecomment-820721529

the alternative is to do the easiest think possible, namely commit if not an error, rollback if error.
but that's strange wrt rollbacks

**Comment by danielknell** [comment]
so if I am tracking this correctly, the plan is to make a change for connections/sessions using `future=True` and any queries in a transaction context manager after a commit or rollback will cause an error?

**Comment by CaselIT** [comment]
Sorry for highjacking the issue to discuss implementation :)

I don't think anything is yet decided firmly.
My proposal was to error only after a rollback on subsequent commands. After a commit the context manager resets and contiues as if a new begin call was issued.

An alternative I suggested is that begin just rollbacks on error and commit whe no error happens, but I agree with Mike that this behaviour can be strange if a rollback is called in the context manager.

What would be your expectation for the begin context manage after a commit/rollback in the block?

**Comment by danielknell** [comment]
doing anything in a transaction context after a commit/rollback seems like it would be a logic error...?

personally I would expect the example in my initial ticket to work without error, but any query after a commit or rollback to just raise as the transaction is already finished.

I think for my purposes I am going to write a rollback-by-default context manager and move away built in one, so the implementation talk here will be helpful :)

**Comment by CaselIT** [comment]
> doing anything in a transaction context after a commit/rollback seems like it would be a logic error...?

While I agree that the context refers to the transaction, we are operating on the connection, so I don't really think it fit the file is closed example.

I guess it would clearer if the operations were directly on the transactions:
```py
with conn.begin() as tx:
  tx.execute(something)
  tx.commit()
  # here tx is closed, os it makes no sense operating on it again
```

I agree that the above example or yours should not cause an error, similar to the file already closed one here https://github.com/sqlalchemy/sqlalchemy/issues/6288#issuecomment-820672860

**Comment by ca-simone-chiorazzo** [comment]
Hi all, I'm facing the same issue using:

SQLAlchemy 1.4.11
asyncpg 0.20.0

Basically, we are implementing a unit of work pattern to abstract the communication with the persistence level.

In order to avoid the error "the transaction is closed" I've implemented in the following way:

`import abc
import logging
from typing import Optional, Dict

from sqlalchemy.ext.asyncio import AsyncSession, AsyncSessionTransaction
from sqlalchemy.orm import sessionmaker

from app.dependencies.database import get_engine
from app.repositories.repository import AbstractRepository, Repository

logger = logging.getLogger(__name__)


class AbstractUnitOfWork(abc.ABC):
    repository: AbstractRepository

    async def __aenter__(self):
        pass

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        pass


class UnitOfWork(AbstractUnitOfWork):
    def __init__(self, db_session: Optional[AsyncSession] = None):
        logger.info("Creating unit of work")
        if db_session:
            self.session = db_session
        else:
            engine = get_engine()
            self.session = sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)()
        self.ref_count = 0
        self.example_repository = Repository(self.session)
        self.nested_transactions_map: Dict[int, AsyncSessionTransaction] = {}

    async def __aenter__(self):
        logger.info("Entering unit of work, ref count %s", self.ref_count)
        # Save into a map the nested transaction that we start
        self.nested_transactions_map[self.ref_count] = await self.session.begin_nested()
        # Enter the SQLAlchemy nested transaction
        await self.nested_transactions_map[self.ref_count].__aenter__()
        self.ref_count += 1
        await super().__aenter__()

    async def __aexit__(self, exc_type, exc_value, traceback):
        self.ref_count -= 1
        logger.info("Exiting unit of work, ref count %s", self.ref_count)
        # Exiting from the nested transaction
        await self.nested_transactions_map[self.ref_count].__aexit__(exc_type, exc_value, traceback)
       # Commit the entire transaction only if we do not have exceptions and we are at the root level
        if self.ref_count == 0 and exc_type is None:
            logger.info("Committing all the changes to the database")
            await self.session.commit()
        if self.ref_count == 0:
            logger.info("Closing session")
            await self.session.close()
            # Reset the nested transactions map once we close the session
            self.nested_transactions_map = {}
        await super().__aexit__(exc_type, exc_value, traceback)

`

In this way, I'm basically relying on the async context manager of begin_nested to accomplish the work and I commit the entire transaction only if there are no errors at the root level.

I noticed that the context manager already rollbacks the nested savepoint in case of exceptions but do not commit it if everything goes well (for this I had to add the explicit commit).

Am I missing something? Do you see any issue in doing this?

**Comment by CaselIT** [comment]
Well I guess then nested transaction releases the savepoint on exit, but it would not commit the external transaction on its own.

**Comment by zzzeek** [comment]
> Am I missing something? Do you see any issue in doing this?

a context manager is a context manager, so there's no "issue", but that code is awfully complicated and I'm not sure what it's meant to accomplish.   if I knew the problem you are trying to solve I would hope i could suggest something much more succinct.

**Comment by zzzeek** [comment]
at least it looks like "self.nested_transactions_map[self.ref_count]" is acting like a stack.   I would use an actual stack instead, this is simpler state to manage:


```

class Thing:
    def __init__(self):
       self.stack = []

   async def __aenter__(...):
       trans = self.session.begin_nested()   # no await needed here
       self.stack.append(trans)
       await trans.__aenter__(...)
   async def __aexit__(...):
        trans = self.stack.pop(-1)
        trans.__aexit__(...)
```

what are you hoping to accomplish by keeping a stack of savepoints?   if an inner operation fails, you still want the enclosing operation to commit its work ?

**Comment by ca-simone-chiorazzo** [comment]
> Well I guess then nested transaction releases the savepoint on exit, but it would not commit the external transaction on its own.

Ok, so if I understood well this is the standard behaviour of SQLAlchemy in case of savepoints, right? Sorry but it is my first implementation of SQLAlchemy and I still ignore some behaviours of the library.

**Comment by CaselIT** [comment]
> 
> 
> > Well I guess then nested transaction releases the savepoint on exit, but it would not commit the external transaction on its own.
> 
> Ok, so if I understood well this is the standard behaviour of SQLAlchemy in case of savepoints, right? Sorry but it is my first implementation of SQLAlchemy and I still ignore some behaviours of the library.

Yes, since once you have closed the last nested transaction you are left with the global transaction, that has not yet been committed or rolled back. See also https://docs.sqlalchemy.org/en/14/orm/session_transaction.html#using-savepoint

It would be different if the first call to your context manager did a simple `begin` instead of a `begin_nested` since in that case the last transaction in the stack would be outer one, not a savepoint

**Comment by zzzeek** [comment]
> 
> Basically, we want to use multiple context managers to handle the whole transaction and nested savepoints. If everything goes well we want to commit the transaction, otherwise, roll back the entire transaction.
> In addition to that, we want to be able to roll back a single savepoint if we trap the exception inside the enclosing one.

that second part.  an exception is raised, part of the work in your transaction is rolled back, you want to commit the whole thing anyway?  that's an unusual case.   usually a savepoint in this way is used to retry an operation that might fail, such as an INSERT, fails due to PK constraint, restore savepoint, then do an UPDATE.   

that kind of code should be written in a block that is explicitly using a savepoint.   that is, the code that's doing that should call session.begin_nested().   I find the pattern of implicitly switching between an outermost transaction and then savepoints on the inside to lead to problems, because people don't understand how it works and it's hard to reason about since you never know what "with my_thing()" will do, looking at some code in isolation.

SQLAlchemy has spent many years with the "automatic nesting" thing and I can attest that it only leads to problems, so I'd advise using session.begin_nested() directly for code that expects to roll back part of its work without interrupting the enclosing transaction.


> 
> I wrote on this thread because the initial implementation was not working properly and was raising a "transaction already closed" error when we tried to roll back a single savepoint.

what's the use case to explicitly roll back a savepoint within a "with session.begin_nested()" block when an exception wasn't raised?   can you simply forego using the context manager in this case?   that's how this is documented: https://docs.sqlalchemy.org/en/14/orm/session_transaction.html#using-savepoint

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**unify transactional context managers** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2800
