### ISSUE TITLE
Allow usage of Values as a column element in postgres

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6289]
**Is your feature request related to a problem? Please describe.**
Postgresql supports using `VALUES` as a column element, in query of the type
```sql
select bar from foo where bar in (values (1),(2),(42));
select bar from foo where bar = any (values (1),(2),(42));
```

**Describe the solution you'd like**
it would be nice if these two queries could be generated using
```py
sa.select(t).where(t.c.bar.in_(sa.values(t.c.bar).data([[1],[2],[42]])))
sa.select(t).where(t.c.bar == sa.any_(sa.values(t.c.bar).data([[1],[2],[42]])))
```

**Describe alternatives you've considered**
the first one produces
```sql
SELECT bar
FROM t, (VALUES (:param_1), (:param_2), (:param_3))
WHERE bar IN (SELECT bar
FROM (VALUES (:param_4), (:param_5), (:param_6)))
```
that does not work.
While the second raises the exception:
```
SQL expression element expected, got <sqlalchemy.sql.selectable.Values object at 0x0000017717604AF0>. To create a column expression from a FROM clause row as a whole, use the .table_valued() method.
```
Using calling `table_valued()` does not produce the above query, generating intead
```sql
SELECT t.bar
FROM t, (VALUES (%(param_1)s), (%(param_2)s), (%(param_3)s)) AS x (bar)
WHERE x.bar = ANY (x)
```

this results in an error, at least on pg

**Additional context**
Since the current values is a from element, maybe this should be a pg only thing, that's not related to the global `values`?
The current compile basically works so it could be reused for also for this new construct

**Have a nice day!**

**Comment by zzzeek** [comment]
this probalby needs a new coercions role that is similar to IN impl.  Also any_() all_() should accept any SELECT statement just like in_() does.     Adding a method like .scalar() to the Values construct, with a datatype that's `Tuple(<types>)`, would be a start.

**Comment by CaselIT** [comment]
Actually also the `IN` case does not work as expected. it's coerced to an hybrid between a tolumn valued and a subquery.

if we want to use the same construct, and I'm not sure we should, I think `.scalar` should generate another type, that's not a from element.

Then I guess we can decide if in and any/all should coerce using this `.scalar` or raise

**Comment by zzzeek** [comment]
any_() / all_() should coerce to this .scalar() thing because that's what in_() does right now as well:

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/coercions.py#L555

**Comment by CaselIT** [comment]
ok, but it does not really work that coercion in this case. I've corrected the sql above, but it renders this sql
```sql
SELECT bar
FROM t, (VALUES (:param_1), (:param_2), (:param_3))
WHERE bar IN (SELECT bar
FROM (VALUES (:param_4), (:param_5), (:param_6)))
```

**Comment by zzzeek** [comment]
we need a new coercion role to Do The Right Thing on this one.

**Comment by CaselIT** [comment]
I think I get the gist, I'll try giving a go after the two other regressions.

`Values.scalar()` will returns a new object that's called something like `ScalarValue` that is _not_ a from element but a column/clause element. does it make sense?

**Comment by zzzeek** [comment]
yeah somehtiugn like.  this one seemed like it didnt have any clear way to do it right now so if we get something up we can tweak it

**Comment by CaselIT** [comment]
I'm not sure this can be generalized.
On postgres at least this is very delicate: this query works
```sql
SELECT bar
FROM t
WHERE bar IN (SELECT anon_2 FROM (VALUES (1), (2), (42)) as anon_1(anon_2))
```
this instead complain that it needs cast

```sql
SELECT bar
FROM t
WHERE bar IN (SELECT anon_1 FROM (VALUES (1), (2), (42)) as anon_1)
```

any/all behave the same as in. so 1 ok, 2 not ok.

Calling `scalar` should instead render as:
```sql
SELECT bar
FROM t
WHERE bar IN (VALUES (1), (2), (42))
```

**Comment by zzzeek** [comment]
but you mean to be using ALL/ANY in those sql examples right

**Comment by CaselIT** [comment]
they actually work the same with both

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Implement ScalarValue** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4183
