### ISSUE TITLE
`instrument_declarative` calls a not existing `registry` method

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6291]
**Describe the bug**

This is not tested anywhere, but it does not seems to used by anyone, since @bryanforbes noticed it while creating the typing

**Expected behavior**

https://github.com/sqlalchemy/sqlalchemy/blob/b3d764fa768756cd7aef73253ccceac456c76c81/lib/sqlalchemy/ext/declarative/extensions.py#L29-L37

**Comment by zzzeek** [comment]
nobody has noticed

**Comment by CaselIT** [comment]
indeed, I guess we could have just removed it instead of deprecating it.

still since it's there it should probably do something other than raise argument error

**Comment by zzzeek** [comment]
we should fix it because it hasn't been a month yet and it's very likely someone is using it

**Comment by CaselIT** [comment]
sure, I was just joking :)

**Comment by CaselIT** [comment]
what method should it call? `registry.mapped` correct?

**Comment by zzzeek** [comment]
probably yes

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fixed ``instrument_declarative`` registry call.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2752
