### ISSUE TITLE
Cannot use `session.execute(...).unique().scalar_one()`

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6299]
**Describe the bug**
Calling `.scalar_one()` after unique raises an error. Using `.scalars().one()` works instead

**Expected behavior**
`.scalar_one()` to be a synonym for `.scalars().one()`

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

```py
import sqlalchemy as sa
import sqlalchemy.orm

meta = sa.MetaData()
rr = sa.orm.registry(metadata=meta)
Base = rr.generate_base()

class Foo(Base):
    __tablename__ = "foo"

    id = sa.Column(sa.Integer, primary_key=True)
    bars = sa.orm.relationship("Bar", back_populates="foos")

class Bar(Base):
    __tablename__ = "bar"

    id = sa.Column(sa.Integer, primary_key=True)
    foo_id = sa.Column(sa.ForeignKey("foo.id"))
    foos = sa.orm.relationship("Foo", back_populates="bars")

engine = sa.create_engine("sqlite://", echo=True, future=True)

with engine.connect() as conn:
    meta.create_all(conn)
    with sa.orm.Session(conn) as sess:
        sess.add(Foo(bars=[Bar(), Bar(), Bar()]))
        sess.commit()
    conn.commit()

stmt = sa.select(Foo).options(sa.orm.joinedload(Foo.bars))
with sa.orm.Session(engine) as session:
    res = session.execute(stmt).unique().scalars().one()
    print(res)
    sess.expire_all()
    res = session.execute(stmt).unique().scalar_one()
    print(res)
```

**Error**

```
Traceback (most recent call last):
  File "C:\Users\cfede\Dev\GitHub\sqlalchemy\test4.py", line 36, in <module>
    res = session.execute(stmt).unique().scalar_one()
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\engine\result.py", line 1116, in scalar_one
    return self._only_one_row(True, True, True)
  File "c:\users\cfede\dev\github\sqlalchemy\lib\sqlalchemy\engine\result.py", line 592, in _only_one_row
    existing_row_hash = strategy(row) if strategy else row
AttributeError: 'Foo' object has no attribute '_filter_on_values'
```

**Versions.**
 - OS: any
 - Python: 3.9
 - SQLAlchemy: 1.4.8, master
 - Database: any
 - DBAPI: any

**Additional context**

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Fixed ``scalar_one`` usage after ``unique``.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2755
