### ISSUE TITLE
see if we can scale back immedaiteload's recursion check from 6232

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6301]
based on #6294 I'm having a hard time explaining exactly the behavioral contract for mutually dependent eager loaders at the relationship level (also at the option level a bit too, but the fixed level is bad enough).  If someone has "immediateload" on a relationship, that should populate, it should of course check for recursion overflow as we ensured in #6232 but we should do better with this check.

overall, the _check_recursive_postload routine, as well as whatever joinedload does to check for recursion, is inconsistent.   Below we illustrate all the combnations for waht does and does not load:

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import backref
from sqlalchemy.orm import exc as orm_exc
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session


def test(bs_load, a_load):

    Base = declarative_base()

    class A(Base):
        __tablename__ = "a"

        id = Column(Integer, primary_key=True)
        data = Column(String)
        bs = relationship("B", lazy=bs_load, backref=backref("a", lazy=a_load))

    class B(Base):
        __tablename__ = "b"
        id = Column(Integer, primary_key=True)
        a_id = Column(ForeignKey("a.id"))
        data = Column(String)

    e = create_engine("sqlite://")
    Base.metadata.create_all(e)

    s = Session(e)

    s.add(A(bs=[B()]))
    s.commit()
    s.close()

    a1 = s.query(A).first()
    s.close()

    try:
        b1 = a1.bs[0]
    except orm_exc.DetachedInstanceError:
        assert False, "this shouldnt be detached"

    assert b1.a is a1


loads = ("joined", "selectin", "subquery", "immediate")

for bs_load in loads:
    for a_load in loads:
        try:
            test(bs_load, a_load)
        except orm_exc.DetachedInstanceError:
            success = False
        else:
            success = True
        print("A->(%s)->bs->(%s)->a: %s" % (bs_load, a_load, success))

```

and we get:

```
A->(joined)->bs->(joined)->a: False
A->(joined)->bs->(selectin)->a: False
A->(joined)->bs->(subquery)->a: False
A->(joined)->bs->(immediate)->a: False
A->(selectin)->bs->(joined)->a: True
A->(selectin)->bs->(selectin)->a: False
A->(selectin)->bs->(subquery)->a: False
A->(selectin)->bs->(immediate)->a: False
A->(subquery)->bs->(joined)->a: True
A->(subquery)->bs->(selectin)->a: False
A->(subquery)->bs->(subquery)->a: False
A->(subquery)->bs->(immediate)->a: False
A->(immediate)->bs->(joined)->a: False
A->(immediate)->bs->(selectin)->a: False
A->(immediate)->bs->(subquery)->a: False
A->(immediate)->bs->(immediate)->a: False

```

everyone is False except for subquery/selectin combined with joined.  This is weird.     When we have an m2o lke that, *all* of these loaders can at least use immediateload.  I'm not undersranding how what we have here relates to the original "selectinloader can use immedaiteload" type of thing that we did in #1763.

I think other people are going to hit this because immediateload's behavior, while inconsisstent, changed from what it was for years with #6232.

**Comment by chaen** [comment]
Thanks !

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Allow immediateload to use_get for recursive call** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2763
