### ISSUE TITLE
select.get_children() causing a multiplier effect

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6304]
this is causing a very large memory / time problem in #6302.   It's difficult to show the problem at scale, however a small version looks like this:

```python
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import visitors

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    x = Column(Integer)
    y = Column(Integer)
    z = Column(Integer)
    p = Column(Integer)
    q = Column(Integer)
    r = Column(Integer)


stmt = select([A.x, A.y, A.z, A.p, A.q, A.r]).alias()

stmt2 = select(
    [stmt.c.x, stmt.c.y, stmt.c.z, stmt.c.p, stmt.c.q, stmt.c.r]
).select_from(stmt)


iter_ = visitors.iterate(stmt2, {})
elems = list(iter_)

print("total length: %s" % len(elems))
```

what happens is because select.get_children() uses this:
```python

    def _iterate_from_elements(self):

        return itertools.chain(
            itertools.chain.from_iterable(
               [element._from_objects for element in self._raw_columns]
           ),
            itertools.chain.from_iterable(
                [element._from_objects for element in self._where_criteria]
            ),
            self._from_obj,
        )

```

it means every column that refers to a certain table or subquery will cause it to traverse that whole subquery all over again.  the more columns you have, the more times it will run that same subquery. then in a more real world example where they have about seven levels of nested subqueries, it's running a few million elements into a list when the traversal happens.  and it's traversing because flask-sqlalhcemy has them using Session.__binds which does a scan of the selectable.   

1.3 didnt have this problem because it iterated "select._froms" which was already pre-calcualted as a set.  

so in 1.4 right now size is 105.   In 1.3 it's about 40.  With the fix as follows it's down to 16:

```
    def _iterate_from_elements(self):
        # note this does not include elements
        # in _setup_joins or _legacy_setup_joins

        seen = set()
        for element in self._raw_columns:
            for fr in element._from_objects:
                if fr in seen:
                    continue
                seen.add(fr)
                yield fr
        for element in self._where_criteria:
            for fr in element._from_objects:
                if fr in seen:
                    continue
                seen.add(fr)
                yield fr
        for element in self._from_obj:
            if element in seen:
                continue
            seen.add(element)
            yield element

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Uniquify FROMs when traversing through select** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2753
