### ISSUE TITLE
Implement mapping to MSSQL "DateTimeOffset" type when using SQLAlchemy generic type Datetime(Timezone=True)

### ISSUE THREAD

**Issue by scd75** [sqlalchemy/sqlalchemy#6306]
**Is your feature request related to a problem? Please describe.**
I always prefer to rely on SQLAlchemy's generic column types, so that my code is DB-backend-agnostic. Yet, when it come to handling of DateTimes, the behavior of Timezone attributes does not result in the same type on backend side:
- POSTGRES: Datetime(Timezone=True) results in timestamptz  type on DB side (which is cool)
- MSSQL: Datetime(Timezone=True) results in naive datetime type on DB side, even though there exist a DATETIMEOFFSET type, which is deisgned to support tz-aware datetimes

**Describe the solution you'd like**
map SQLAlchemy generic type Datetime to MSSQL DatetimeOffset type, when I select "(Timezone=True)"

**Describe alternatives you've considered**
all alternatives involve having some back-end specific code

**Additional context**
I understand there might also be an issue with pyodbc, but I am not sure I understood exactly what is the status on this

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add DateTime(timezone=True) support to mssql** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2759
