### ISSUE TITLE
How to execute subtransactions

### ISSUE THREAD

**Issue by leandrogmuller** [sqlalchemy/sqlalchemy#6309]
Hi.

How can I execute subtransactions?
Example below not work.

engine = create_engine("postgresql://user:pass@localhost:5432/datadev",poolclass=NullPool)
session_factory = sessionmaker(bind=engine)
session = session_factory()
session.begin_nested()  # when uses it dons't commit.
lang03 = session.query(Lang03).filter(Lang03.pkge == 'kernel').first()
lang03.text = 'aa'
session.merge(lang03)
session.commit()
session.close()

**Comment by CaselIT** [comment]
Hi,

Can you please provide a complete example? What does not work?
