### ISSUE TITLE
How ignore changes on model?

### ISSUE THREAD

**Issue by leandrogmuller** [sqlalchemy/sqlalchemy#6310]
Hello.

How can I ignore changes on model?
Example.

engine = create_engine("postgresql://user:pass@localhost:5432/datadev",
poolclass=NullPool)
session_factory = sessionmaker(bind=engine)
session = session_factory()
lang03 = session.query(Lang03).filter(Lang03.pkge == 'kernel').first()
lang03.text = 'd' # I dont't whant to change on database.
session.commit()
session.close()

**Comment by CaselIT** [comment]
Hi, there is no need to open an issue and a discussion with the same question
