### ISSUE TITLE
Not lock runtime python

### ISSUE THREAD

**Issue by leandrogmuller** [sqlalchemy/sqlalchemy#6311]
I need to execute merge, but not lock object during the process.

engine = create_engine("postgresql://user:pass@localhost:5432/datadev",poolclass=NullPool)

for i in range(3): 
    session_factory = sessionmaker(bind=engine)
    session = session_factory()
    lang03 = session.query(Lang03).filter(Lang03.pkge == 'kernel').first()
    lang03.text = 'aa'
    session.merge(lang03) #second attempt lock the code running. I dont't want lock the runtime.

**Comment by CaselIT** [comment]
Hi,

I'm not sure why you would want to merge an object that's already in the session. See the documentation for details
