### ISSUE TITLE
sqlalchemy.dialects.sqlite.DATETIME documentation example is inconsistent

### ISSUE THREAD

**Issue by jshprentz** [sqlalchemy/sqlalchemy#6313]
The documentation for class sqlalchemy.dialects.sqlite.DATETIME, https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#sqlalchemy.dialects.sqlite.DATETIME, shows the default storage format with six decimal places. The example shows only five decimal places.

![image](https://user-images.githubusercontent.com/5303785/115122624-dc933100-9f86-11eb-9ef4-8f8907675560.png)

**Comment by CaselIT** [comment]
thanks for reporting it
