### ISSUE TITLE
Spurious “Unmanaged access of declarative attribute” warning when using with_loader_criteria()

### ISSUE THREAD

**Issue by mjpieters** [sqlalchemy/sqlalchemy#6320]
I’m using a mix-in class that defines a foreign key and use this mix-in to set a query filter in a `orm_do_execute` event handler  to add a `with_loader_criteria()` object to the execution options:

```python
@declarative_mixin
class FooOwnedMixin:
    @declared_attr
    def foo_id(self):
        return Column(Integer, ForeignKey("foo.id"), nullable=False)

event.listens_for(Session, "do_orm_execute")
def _lock_foo_id(execute_state):
    if execute_state.is_column_load:
        return

    foo_id = current_foo_id()
    if foo_id is None:
        return

    execute_state.statement = execute_state.statement.options(
        with_loader_criteria(
            FooOwnedMixin,
            lambda cls: cls.foo_id == foo_id,
            include_aliases=True,
        )
    )
```

The `with_loader_criteria()` will actually execute the `lambda` passed in here using the mix-in as the argument for `cls`, the above triggers a warning:

```python
/.../site-packages/sqlalchemy/orm/decl_api.py:223: SAWarning: Unmanaged access of declarative attribute foo_id from non-mapped class FooOwnedMixin
  util.warn(
```

The warning is spurious because the cached statement will from there on out only be used together with the subclasses of the mix-in class.

Right now I work around this by adding a specific warning filter:

```python
warnings.filterwarnings(
    "ignore",
    "Unmanaged access of declarative attribute foo_id from non-mapped "
    "class FooOwnedMixin",
    SAWarning,
)
```

but this would also hide genuine incorrect use of the mix-in attribute in other contexts. Could the warning be disabled for this specific edge case? 

**Versions.**
 - OS: MacOS 10.15
 - Python: 3.9.4
 - SQLAlchemy: 1.4.9
 - Database: SQLite, PostgreSQL
 - DBAPI: sqlite3, psycopg2

**MRE**

```python
import random
from sqlalchemy import event, create_engine, Column, Integer, String, ForeignKey
from sqlalchemy.orm import declarative_base, declarative_mixin, declared_attr, sessionmaker, with_loader_criteria, Session

def current_foo_id():
    return random.randint(1, 3)

@declarative_mixin
class FooOwnedMixin:
    @declared_attr
    def foo_id(self):
        return Column(Integer, ForeignKey("foo.id"), nullable=False)

@event.listens_for(Session, "do_orm_execute")
def _lock_foo_id(execute_state):
    if execute_state.is_column_load:
        return

    foo_id = current_foo_id()
    print("foo_id =", foo_id)

    execute_state.statement = execute_state.statement.options(
        with_loader_criteria(
            FooOwnedMixin,
            lambda cls: cls.foo_id == foo_id,
            include_aliases=True,
        )
    )

Base = declarative_base()

class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)

class Bar(Base, FooOwnedMixin):
    __tablename__ = "bar"
    id = Column(Integer, primary_key=True)
    def __repr__(self):
        return f"Bar(id={self.id}, foo_id={self.foo_id})"

engine = create_engine("sqlite://")
session = sessionmaker(bind=engine)()
Base.metadata.create_all(bind=engine)

session.add_all([Foo(id=id) for id in range(1, 4)])
session.add_all([Bar(id=id, foo_id=current_foo_id()) for id in range(1, 10)])
session.commit()

print(session.query(Bar).all())
print(session.query(Bar).all())
```

**Comment by zzzeek** [comment]
it should not be warning, I'm pretty sure the unit tests for this feature make use of an unmapped mixin so im wondering how they didnt have this problem.    I believe it's not actually supposed to be running the code with the mixin class but I know the lambda does an up-front run to learn about the code.

**Comment by zzzeek** [comment]
oh it's the declared_attr.   well OK.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Bypass declared_attr w/ a custom wrapper for lambda criteria** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2760

**Comment by zzzeek** [comment]
great news, I found a much more elaborate way to work around the warning :)
