### ISSUE TITLE
Bug while parsing URL in URL.create

### ISSUE THREAD

**Issue by youtux** [sqlalchemy/sqlalchemy#6329]
**Describe the bug**
It seems to me that URL parsing has a bug when there is not `/` before the query parameters

**Expected behavior**
URL should be parsed as expected.

**To Reproduce**

```py
from sqlalchemy.engine import make_url

url = make_url("mysql://user:pass@127.0.0.1?charset=utf8mb4")
assert url.host == "127.0.0.1"  # raises, url.host is '127.0.0.1?charset=utf8mb4'
assert url.query == {"charset": "utf8mb4"}  # also raises, it's an empty dict
```

**Error**

```
  File "/Users/youtux/Library/Application Support/JetBrains/PyCharm2021.1/scratches/scratch.py", line 18, in <module>
    assert url.host == "127.0.0.1"  # raises, url.host is '127.0.0.1?charset=utf8mb4'
AssertionError
```

**Versions.**
 - OS: macos 11.2.1
 - Python: 3.6.12
 - SQLAlchemy: 1.4.10
 - Database: irrelevant
 - DBAPI: irrelevant

**Additional context**
I found this problem when I was manipulating the URL string. I started with a quey string that contains the `/`, and then I remove the database part of the query, and it's SQLAlchemy itselfs that removes the `/` from the string. Still, the resulting string should be parsed just fine.
```py
original_url = make_url("mysql://user:pass@127.0.0.1/testdb?charset=utf8mb4")

stringified_url = str(original_url._replace(database=None))
# stringified_url is now "mysql://user:pass@127.0.0.1?charset=utf8mb4"
```

**Have a nice day!**

**Comment by zzzeek** [comment]
that's a very old behavior which you will see in probably the last ten years of SQLAlchemy.

**Comment by youtux** [comment]
Ah indeed, also the 1.3 branch seems to show the same issue.
I guess that it's more visible now because I had to change the way I build the connection URL, since in 1.4 the URL object is immutable.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**URL parsing fixes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2838
