### ISSUE TITLE
Cannot override __new__ in declarative model

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/sqlalchemy#6331]
**Describe the bug**

In SQLAlchemy 1.4, `__new__` cannot be overridden in a declarative model.

**Expected behavior**

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

It's not necessary to replicate the problem, but I was setting instance variables in `__new__`. Any `__new__` override shows the problem:

```py
from sqlalchemy import Column, Integer
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class MyTable(Base):
    __tablename__ = 'my_table'
    id = Column(Integer, primary_key=True)

    def __new__(cls, *args, **kwargs):
        return cls()
```

**Error**

```
Traceback (most recent call last):
  File "/Users/.../scratch_28.py", line 7, in <module>
    class MyTable(Base):
  File "/Users/.../python3.9/site-packages/sqlalchemy/orm/decl_api.py", line 75, in __init__
    _as_declarative(reg, cls, dict_)
  File "/Users/.../python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 126, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/Users/.../python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 177, in setup_mapping
    return cfg_cls(registry, cls_, dict_, table, mapper_kw)
  File "/Users/.../python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 299, in __init__
    self._scan_attributes()
  File "/Users/.../python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 579, in _scan_attributes
    assert not attribute_is_overridden(name, obj)
AssertionError
```

**Versions.**
 - OS: macOS 10.15.7
 - Python: 3.9.1
 - SQLAlchemy: 1.4.10
 - Database: N/A
 - DBAPI: N/A

**Additional context**

I could probably use `__init__` and `@orm.reconstructor` instead, but this looks like unintentional breakage?

**Have a nice day!**

**Comment by zzzeek** [comment]
wow what weird problems

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Limit dc field logic to only fields that are definitely dc** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2765

**Comment by zzzeek** [comment]
so I don't have any workaround for that right now and 1.4.10 just went out.   it might be a few days before 1.4.11 though we are obviously releasing every few days while we get through these regressions.

**Comment by zzzeek** [comment]
feel free to test out /develop against git master for now, there will likely be another release in the upcoming days once we get a few more issues in.

**Comment by RazerM** [comment]
It works, thanks!

**Comment by zzzeek** [comment]
well we've got our critical emergency regression for today in #6337, so 1.4.11 will be today! :)
