### ISSUE TITLE
Identity column overrides AUTO_INCREMENT for MySQL

### ISSUE THREAD

**Issue by mciupak** [sqlalchemy/sqlalchemy#6338]
**Describe the bug**

As stated in https://docs.sqlalchemy.org/en/14/core/defaults.html#identity-ddl 

> When Identity is used with an unsupported backend, it is ignored, and the default SQLAlchemy logic for autoincrementing columns is used.

Creating table with Identity() and auto_increment = True produces column without AUTO_INCREMENT.

**Expected behavior**

As MySQL does not support Identity columns it should be omited and column should be created with AUTO_INCREMENT option.

**To Reproduce**
```py
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, Identity
from sqlalchemy.schema import CreateTable

engine = create_engine('mysql://...')
meta = MetaData()

table_without_identity = Table(
   'table_without_identity', meta, 
   Column('id', Integer, primary_key = True, auto_increment = True), 
     )

table_with_identity = Table(
   'table_with_identity', meta, 
   Column('id', Integer, Identity(), primary_key = True, auto_increment = True), 
     )

print(CreateTable(table_without_identity).compile(engine))
print(CreateTable(table_with_identity).compile(engine))
```

**Error**

```
CREATE TABLE table_without_identity (
        id INTEGER NOT NULL AUTO_INCREMENT, 
        PRIMARY KEY (id)
)

CREATE TABLE table_with_identity (
        id INTEGER NOT NULL, 
        PRIMARY KEY (id)
)
```

**Versions.**
 - OS: Linux 5.10.9-gentoo
 - Python: Python 3.8.8
 - SQLAlchemy: 1.4.10
 - Database: mariadb 10.5.9
 - DBAPI: mysqlclient-1.4.6-r1

**Comment by CaselIT** [comment]
Hi,
Thanks for the report, this will probably be common to all db that do not support identity columns

**Comment by zzzeek** [comment]
this is specific to mysql, at least, a simlar fix might be needed for other dialects but it's in the dialect:

```diff
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index d4c70a78e6..5a84aa9c7c 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -1933,7 +1933,7 @@ class MySQLDDLCompiler(compiler.DDLCompiler):
         if (
             column.table is not None
             and column is column.table._autoincrement_column
-            and column.server_default is None
+            and column.server_default is None and <is not an identity>
             and not (
                 self.dialect.supports_sequences
                 and isinstance(column.default, sa_schema.Sequence)

```

**Comment by CaselIT** [comment]
indeed. adding a suite test for it it's a problem though, see https://github.com/sqlalchemy/sqlalchemy/commit/785d9ac61c94e1cd17b6c3fb97e7d467ee058bbc

**Comment by CaselIT** [comment]
let me know if you have ideas for adding a suite test

**Comment by zzzeek** [comment]
how about:

1. add a table, that has an identity and "auto_increment"
2. insert a row
3. make sure new int pk was generated

?

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Propertly ignore ``Identity`` in MySQL and MariaDb.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2767

**Comment by CaselIT** [comment]
> 
> 
> how about:
> 
>     1. add a table, that has an identity and "auto_increment"
> 
>     2. insert a row
> 
>     3. make sure new int pk was generated
> 
> 
> ?

yes, that makes sense. no requirements in that case I guess

**Comment by CaselIT** [comment]
> yes, that makes sense. no requirements in that case I guess

and of course it needs one :)

**Comment by mciupak** [comment]
Any plans fixing this bug any time soon?

**Comment by CaselIT** [comment]
This will get fixed once the linked changeset is merged, if you are in a rush you can apply the patch ported by mike here https://github.com/sqlalchemy/sqlalchemy/issues/6338#issuecomment-824335949
