### ISSUE TITLE
restate legacy "isolation_level" setting in terms of execution options and fix tests

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6342]
postgresql, mysql, and probably every dialect except Oracle has an "isolation_level" dialect parameter and the tests in test/engine/test_transaction are hardcoded to it. Oracle isn't included and therefore never got tested here even though we implemented isolation level support for Oracle.  The dialects all have a hardcoded isolation level setter in on_connect() and the whole thing is totally redundant vs. the isolation_level execution option which is what we document.

the isolation_level dialect setting should be accepted by the base Dialect directly and then go straight in as an execution option in some way.     enable the remaining tests for Oracle after that.

**Comment by zzzeek** [comment]
i sort of cant bring myself to remove this beacuse if you really want an engine witha certain isoaltion level always, the engine level isolation_level setting does this within the connect handler and keeps it that way, whereas the exeution option approach resets it on every checkout.

**Comment by zzzeek** [comment]
for now im going to just generalize this setting to all the dialects.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**fully support isolation_level parameter in base dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3288
