### ISSUE TITLE
.as_generic() fails with NotImplementedError for mssql BIT column

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#6345]
**Describe the bug**
`.as_generic()` throws `NotImplementedError` for a SQL Server BIT column

**Expected behavior**
should return `sqltypes.Boolean`

**To Reproduce**
```py
with engine.begin() as conn:
    conn.exec_driver_sql(f"""\
        DROP TABLE IF EXISTS bit_tbl  
    """)
    conn.exec_driver_sql(f"""\
        CREATE TABLE bit_tbl (bit_col bit)  
    """)
    conn.exec_driver_sql(f"""\
        INSERT INTO bit_tbl (bit_col) VALUES (0)  
    """)
tbl = sa.Table("bit_tbl", sa.MetaData(), autoload_with=engine)
bit_type = tbl.c.bit_col.type.as_generic()
```

**Error**

```
Traceback (most recent call last):
  File "C:\Users\Gord\git\sqla-gerrit\gord_test\gord_test.py", line 69, in <module>
    bit_type = tbl.c.bit_col.type.as_generic()
  File "C:\Users\Gord\git\sqla-gerrit\lib\sqlalchemy\sql\type_api.py", line 514, in as_generic
    raise NotImplementedError(
NotImplementedError: Default TypeEngine.as_generic() heuristic method was unsuccessful for sqlalchemy.dialects.mssql.base.BIT. A custom as_generic() method must be implemented for this type class.
```

**Versions.**
 - SQLAlchemy: 1.4.12.dev0

**Additional context**
SQL Server does not have a BOOLEAN column type; it uses BIT instead. pyodbc already returns `bool` values from BIT columns:

```py
cnxn = engine.raw_connection()
crsr = cnxn.cursor()
bit_value = crsr.execute("SELECT bit_col FROM bit_tbl").fetchval()
print(type(bit_value))  # <class 'bool'>
```

**Comment by zzzeek** [comment]
do we make this assumption for MySQL TINYINT ? that's where we'd need to be consistent here.

**Comment by gordthompson** [comment]
`.as_generic()` returns `<class 'sqlalchemy.sql.sqltypes.Integer'>` for MySQL TINYINT, but that is an 8-bit integer. MSSQL BIT behaves like a 1-bit unsigned integer (can only be 0, 1, or NULL) so it really is only useful as a (boolean) flag.

**Comment by gordthompson** [comment]
Also, boolean and BIT are recognized as synonyms here:

https://github.com/sqlalchemy/sqlalchemy/blob/72f43a8b49803cd4d4befe91635f6691965f34fb/lib/sqlalchemy/dialects/mssql/base.py#L1497-L1498

**Comment by zzzeek** [comment]
pretty sure TINYINT and BOOL are synonyms too on MySQL.   but sure, I dont think this is going to break things for people if BIT comes down to Boolean as this method is not intrinsic to other SQLAlchemy things anyway.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Add .as_generic() support to mssql BIT columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2770

**Comment by gordthompson** [comment]
You're right that in MySQL `bool` is interpreted as a synonym of `tinyint(1)`, as in

```sql
create table gh_6345 (id int primary key, boo bool);

show create table gh_6345;
```

shows

```sql
CREATE TABLE `gh_6345` (
 `id` int(11) NOT NULL,
 `boo` tinyint(1) DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

However, in MySQL the `(1)` is just a display hint, so we can still insert values larger than 1 in that column

```
insert into gh_6345 (id, boo) values (1, 23);

select * from gh_6345;
```

gives

```
id  boo
--  ---
 1   23
```

If we really needed to deduce the intent of the tinyint column we could get the hint by using

```sql
select COLUMN_TYPE FROM INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'gh_6345' and COLUMN_NAME='boo';
```

```
COLUMN_TYPE
-----------
tinyint(1)
```

but I don't think we need to worry about that.

**Comment by zzzeek** [comment]
yes, im overreacting in total, .as_generic() is not intrinsic to any other part of SQLAlchemy so this isnt going to break anything for anybody.
