### ISSUE TITLE
deprecated .copy() methods don't propagate schema correctly

### ISSUE THREAD

**Issue by bmacphee** [sqlalchemy/sqlalchemy#6353]
**Describe the bug**
Using alembic, I have some custom schema manipulation going on to make copies of a defined schema.
Part of the code does something like this:
```python
for c in table1.constraints:
    table2.append_constraint(c.copy(schema="foo", target_table=table1))
```

This used to work in 1.3, now fails in 1.4 after an upgrade.  It seems to be specific to copying ForeignKeyConstraint

**Expected behavior**
The copy should not fail

**To Reproduce**
```python
from sqlalchemy import Table, MetaData, Column, Integer, ForeignKeyConstraint
metadata = MetaData()
foo_table = Table("foo", metadata, Column("col", Integer), ForeignKeyConstraint(("col",), ["bar.target"]))
bar_table = Table("bar", metadata, Column("target", Integer))
copy_table = Table('table3', metadata, Column("col", Integer))

for c in foo_table.constraints:
    copy_table.append_constraint(c.copy(target_table=foo_table))

```

**Error**

```
Traceback (most recent call last):
  File "/tmp/test.py", line 8, in <module>
    copy_table.append_constraint(c.copy(target_table=foo_table))
  File "<string>", line 2, in copy
  File "/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 3735, in copy
    return self._copy(target_table, **kw)
  File "/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 3748, in _copy
    for x in self.elements
  File "/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 3748, in <listcomp>
    for x in self.elements
  File "/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 2182, in _get_colspec
    if schema:
  File "/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 594, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
```

**Versions.**
 - OS: ubuntu 18
 - Python: 3.7
 - SQLAlchemy: 1.4.11
 - Database: postgresql
 - DBAPI: 

**Additional context**
A simple change seems to resolve it:
https://github.com/sqlalchemy/sqlalchemy/compare/master...bmacphee:fix-misaligned-copy-argument?expand=1

**Comment by zzzeek** [comment]
hi and thanks for reporting.  you may as well use _copy() for now but also these won't be public methods in 2.0 as they are not generic copy() methods.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Fix ForeignKeyConstraint.copy() error** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2793
