### ISSUE TITLE
unable to install sqlalchemy on macbook air with M1 chip

### ISSUE THREAD

**Issue by ss87codes** [sqlalchemy/sqlalchemy#6357]
Hi, I am unable to install sqlalchemy or flask-sqlalchemy on my macbook air with M1 chip

My python version is 3.9.4

Here is what I see when i run pip3 install SQLAlchemy==1.4.11

shobhit@Shobhits-MacBook-Air-2 ~ % pip3 install SQLAlchemy==1.4.11
Collecting SQLAlchemy==1.4.11
  Using cached SQLAlchemy-1.4.11-cp39-cp39-macosx_11_0_arm64.whl
Collecting greenlet!=0.4.17
  Using cached greenlet-1.0.0.tar.gz (84 kB)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-install-k8gppxly/greenlet_0a337552fa0d4c8e8f6a4da969c1108e/setup.py'"'"'; __file__='"'"'/private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-install-k8gppxly/greenlet_0a337552fa0d4c8e8f6a4da969c1108e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-wheel-_kdbnpmn
       cwd: /private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-install-k8gppxly/greenlet_0a337552fa0d4c8e8f6a4da969c1108e/
  Complete output (74 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11-arm64-3.9
  creating build/lib.macosx-11-arm64-3.9/greenlet
  copying src/greenlet/__init__.py -> build/lib.macosx-11-arm64-3.9/greenlet
  creating build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_version.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_weakref.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_gc.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_generator.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_throw.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_tracing.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_cpp.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_contextvars.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_greenlet.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_extension_interface.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/__init__.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_generator_nested.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_stack_saved.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/test_leaks.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  running egg_info
  writing src/greenlet.egg-info/PKG-INFO
  writing dependency_links to src/greenlet.egg-info/dependency_links.txt
  writing requirements to src/greenlet.egg-info/requires.txt
  writing top-level names to src/greenlet.egg-info/top_level.txt
  reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs/_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
  copying src/greenlet/greenlet.c -> build/lib.macosx-11-arm64-3.9/greenlet
  copying src/greenlet/greenlet.h -> build/lib.macosx-11-arm64-3.9/greenlet
  copying src/greenlet/slp_platformselect.h -> build/lib.macosx-11-arm64-3.9/greenlet
  creating build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_mips_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_s390_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_x32_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/platform/switch_x86_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
  copying src/greenlet/tests/_test_extension.c -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.macosx-11-arm64-3.9/greenlet/tests
  running build_ext
  building 'greenlet._greenlet' extension
  creating build/temp.macosx-11-arm64-3.9
  creating build/temp.macosx-11-arm64-3.9/src
  creating build/temp.macosx-11-arm64-3.9/src/greenlet
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/homebrew/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/sqlite/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/greenlet/greenlet.c -o build/temp.macosx-11-arm64-3.9/src/greenlet/greenlet.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build greenlet
Installing collected packages: greenlet, SQLAlchemy
    Running setup.py install for greenlet ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-install-k8gppxly/greenlet_0a337552fa0d4c8e8f6a4da969c1108e/setup.py'"'"'; __file__='"'"'/private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-install-k8gppxly/greenlet_0a337552fa0d4c8e8f6a4da969c1108e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-record-r0c5kptq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/greenlet
         cwd: /private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-install-k8gppxly/greenlet_0a337552fa0d4c8e8f6a4da969c1108e/
    Complete output (74 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11-arm64-3.9
    creating build/lib.macosx-11-arm64-3.9/greenlet
    copying src/greenlet/__init__.py -> build/lib.macosx-11-arm64-3.9/greenlet
    creating build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_version.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_weakref.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_gc.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_generator.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_throw.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_tracing.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_cpp.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_contextvars.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_greenlet.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_extension_interface.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/__init__.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_generator_nested.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_stack_saved.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/test_leaks.py -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    running egg_info
    writing src/greenlet.egg-info/PKG-INFO
    writing dependency_links to src/greenlet.egg-info/dependency_links.txt
    writing requirements to src/greenlet.egg-info/requires.txt
    writing top-level names to src/greenlet.egg-info/top_level.txt
    reading manifest file 'src/greenlet.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no files found matching '*.py' under directory 'appveyor'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '.coverage' found anywhere in distribution
    writing manifest file 'src/greenlet.egg-info/SOURCES.txt'
    copying src/greenlet/greenlet.c -> build/lib.macosx-11-arm64-3.9/greenlet
    copying src/greenlet/greenlet.h -> build/lib.macosx-11-arm64-3.9/greenlet
    copying src/greenlet/slp_platformselect.h -> build/lib.macosx-11-arm64-3.9/greenlet
    creating build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/setup_switch_x64_masm.cmd -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_aarch64_gcc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_alpha_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_amd64_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_arm32_gcc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_arm32_ios.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_csky_gcc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_m68k_gcc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_mips_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc64_aix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc64_linux.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc_aix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc_linux.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc_macosx.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_ppc_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_riscv_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_s390_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_sparc_sun_gcc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x32_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x64_masm.asm -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x64_masm.obj -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x64_msvc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x86_msvc.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/platform/switch_x86_unix.h -> build/lib.macosx-11-arm64-3.9/greenlet/platform
    copying src/greenlet/tests/_test_extension.c -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.macosx-11-arm64-3.9/greenlet/tests
    running build_ext
    building 'greenlet._greenlet' extension
    creating build/temp.macosx-11-arm64-3.9
    creating build/temp.macosx-11-arm64-3.9/src
    creating build/temp.macosx-11-arm64-3.9/src/greenlet
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/homebrew/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/sqlite/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/greenlet/greenlet.c -o build/temp.macosx-11-arm64-3.9/src/greenlet/greenlet.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-install-k8gppxly/greenlet_0a337552fa0d4c8e8f6a4da969c1108e/setup.py'"'"'; __file__='"'"'/private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-install-k8gppxly/greenlet_0a337552fa0d4c8e8f6a4da969c1108e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bj/fq47gjd56w3bwy8d51t7t2600000gn/T/pip-record-r0c5kptq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/greenlet Check the logs for full command output.
```
Can you please help.

**Comment by CaselIT** [comment]
hi,

it seems that the error is with installing greenlet. That dependency is only needed when using asyncio, so you can avoid installing it.
To fix you can:
- install sqlalchemy with `pip install  --no-deps sqlalchemy`
- install a compiler for your mac so that greenlet can be compiled. I'm not too familiar with osx, but I think this entails installing xcode

**Comment by ss87codes** [comment]
Thanks @CaselIT using --no-deps i was able to install sqlalchemy. However, installing xcode did not help in installing without the no dependencies statement

**Comment by CaselIT** [comment]
Searching for the error yields results similar to this one: https://medium.com/@Andrew.Budziszek/macos-xcrun-error-invalid-active-developer-path-28d0b52b23c6

Since I don't use osx so I'm not familiar on how it works wrt compiling python packages.

If you don't need async, using `--no-deps` is fine
