### ISSUE TITLE
autobegin behavioral change means that rollback() can be a no-op

### ISSUE THREAD

**Issue by youtux** [sqlalchemy/sqlalchemy#6359]
**Describe the bug**
It seems that `Session.rollback()` does not always expire the objects in the session in case the `expire_on_commit=False` is set. Only SQLAlchemy 1.4 branch seems to be affected.

**Expected behavior**
I expect `Session.rollback()` to always expire the objects in the session, regardless of the `expire_on_commit` flag. This was the behavior of SQLAlchemy 1.3.

**To Reproduce**
```py
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker


Base = declarative_base()

engine = create_engine('sqlite:///:memory:', echo=True)

class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)

    name = Column(String(40))


Base.metadata.drop_all(engine, checkfirst=True)
Base.metadata.create_all(engine)

Session = sessionmaker(
    bind=engine,
    expire_on_commit=False,  # The important bit
)

session1 = Session()
foo = Foo(name="foo")
session1.add(foo)
session1.commit()

session2 = Session()
foo_2 = session2.query(Foo).filter(Foo.id == foo.id).one()
foo_2.name = "modified_in_session_2"
session2.commit()

session1.rollback()  # This should expire foo, but it doesn't, so `foo.name` is still set to the initial value, "foo"
assert foo.name == "modified_in_session_2"

```

**Error**

```
2021-04-26 12:36:07,872 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-04-26 12:36:07,874 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("foo")
2021-04-26 12:36:07,875 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-04-26 12:36:07,877 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("foo")
2021-04-26 12:36:07,877 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-04-26 12:36:07,881 INFO sqlalchemy.engine.Engine COMMIT
2021-04-26 12:36:07,882 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-04-26 12:36:07,882 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("foo")
2021-04-26 12:36:07,882 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-04-26 12:36:07,883 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("foo")
2021-04-26 12:36:07,883 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-04-26 12:36:07,886 INFO sqlalchemy.engine.Engine 
CREATE TABLE foo (
	id INTEGER NOT NULL, 
	name VARCHAR(40), 
	PRIMARY KEY (id)
)


2021-04-26 12:36:07,886 INFO sqlalchemy.engine.Engine [no key 0.00034s] ()
2021-04-26 12:36:07,887 INFO sqlalchemy.engine.Engine COMMIT
2021-04-26 12:36:07,893 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-04-26 12:36:07,899 INFO sqlalchemy.engine.Engine INSERT INTO foo (name) VALUES (?)
2021-04-26 12:36:07,899 INFO sqlalchemy.engine.Engine [generated in 0.00046s] ('foo',)
2021-04-26 12:36:07,901 INFO sqlalchemy.engine.Engine COMMIT
2021-04-26 12:36:07,904 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-04-26 12:36:07,907 INFO sqlalchemy.engine.Engine SELECT foo.id AS foo_id, foo.name AS foo_name 
FROM foo 
WHERE foo.id = ?
2021-04-26 12:36:07,908 INFO sqlalchemy.engine.Engine [generated in 0.00040s] (1,)
2021-04-26 12:36:07,914 INFO sqlalchemy.engine.Engine UPDATE foo SET name=? WHERE foo.id = ?
2021-04-26 12:36:07,915 INFO sqlalchemy.engine.Engine [generated in 0.00053s] ('modified_in_session_2', 1)
2021-04-26 12:36:07,915 INFO sqlalchemy.engine.Engine COMMIT
Traceback (most recent call last):
  File "/Users/youtux/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/211.6693.115/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/youtux/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/211.6693.115/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/youtux/Library/Application Support/JetBrains/PyCharm2021.1/scratches/scratch_2.py", line 36, in <module>
    assert foo.name == "modified_in_session_2"
AssertionError
```

**Versions.**
 - OS: macOS 11.2.1
 - Python: 3.6.12
 - Alembic: irrelevant
 - SQLAlchemy: 1.4.10, 1.4.12.dev0 (commit 1443945e61f1f113e46a5044315a91558d4d232a)
 - Database: mysql, sqlite
 - DBAPI: sqlite3, mysqlclient
 
**Have a nice day!**

**Comment by CaselIT** [comment]
Hi,

I moved the issue to `sqlalchemy`

**Comment by youtux** [comment]
😣 I didn’t realize it was the Alembic issue tracker

**Comment by zzzeek** [comment]
hi - 

rollback() is a no-op here because no transaction was begun.    this is described at https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#session-features-new-autobegin-behavior .

what you can do now is call session.begin() if you need to ensure a transaction is begun.  this was not possible in 1.3.   

overall though if your use case is ensuring visibility into other transactions and you have expire_on_commit=True, you would probably want to call session.expire_all().

the bug here is in the changelog:

> Besides the change in when the SessionEvents.after_transaction_create() event is emitted, the change should have no other user-visible impact on the Session object’s behavior

correction, it also means .rollback() / .commit() do nothing if no transaction was begun.

**Comment by youtux** [comment]
Hmmm, this is going to have quite an impact on a codebase I'm working with, as many of the tests rely on `Session.rollback()` to mark the objects as expired and trigger a reload of the attributes when accessed.

Also, the documentation states that a session rollback should expire all the objects: https://docs.sqlalchemy.org/en/14/orm/session_basics.html#session-rollback:~:text=All%20objects%20not%20expunged%20are%20fully%20expired.
Isn't that conflicting with how `Session.rollback()` works now?

**Comment by zzzeek** [comment]
> Hmmm, this is going to have quite an impact on a codebase I'm working with, as many of the tests rely on `Session.rollback()` to mark the objects as expired and trigger a reload of the attributes when accessed.

if you need to mark objects as expired, that's what Session.expire_all() is for.

> 
> Also, the documentation states that a session rollback should expire all the objects: https://docs.sqlalchemy.org/en/14/orm/session_basics.html#session-rollback:~:text=All%20objects%20not%20expunged%20are%20fully%20expired.
> Isn't that conflicting with how `Session.rollback()` works now?

agreed the documentation is inaccurate and needs to be updated.

**Comment by zzzeek** [comment]
I have found a case where I might need to change this in any case, so you may be in luck.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Implement "soft restore" for attributes; Document autobegin** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2777

**Comment by zzzeek** [comment]
I'm still -1 on rollback() expiring objects if absolutely nothing changed in the session.    are your tests in fact just looking for pending changes to be rolled back?

**Comment by youtux** [comment]
The tests that are now breaking with sqlalchemy 1.4 are functional tests that use the browser to exercise the views, and they do a rollback after the exercise to have a clean slate and start asserting how the object should have changed.
They follow more or less like this logic:

```python
def test_edit_user_details(user, session, browser):
    user = User(...)
    session.add(user)
    session.commit()

    browser.visit(...)
    browser.fill("name", "Changed name")
    browser.click("Submit")

    session.rollback()  # ensure that from now on we read changes committed from the app worker
    assert user.name == "Changed name"
```

**Comment by youtux** [comment]
(I updated the previous comment with more information about my use case)

**Comment by zzzeek** [comment]
> ```python
> def test_edit_user_details(user, session, browser):
>     user = User(...)
>     session.add(user)
>     session.commit()
> 
>     browser.visit(...)
>     browser.fill("name", "Changed name")
>     browser.click("Submit")
> 
>     session.rollback()  # ensure that from now on we read changes committed from the app worker
>     assert user.name == "Changed name"
> ```
> 
> Also, I can't just change `session.rollback()` to `session.expire_all()`, as I really need to ensure that we use a new transaction when accessing the objects (otherwise REPEATABLE READS isolation level will let me see only the old data).

that really sounds like exactly when you want to call expire_all().   The whole point of expire_on_commit is so that when the transaction ends, e.g. you called commit(), all the effects of that transaction are gone.  But you have above a special modification to that use case, which is that you want the effects of the closed transaction to still remain  a little while longer while you render your view.  OK, so that's great, render your view, then you need to call expire_all().   There's nothing here to rollback() and really in previous versions this was not what rollback was meant to accomplish.  rollback() expires the data relative to the current transaction.

**Comment by youtux** [comment]
I need to call a rollback because I am actually using MySQL with REPEATABLE READS isolation level, and I need to ensure that I am executing queries in a transaction that was started *after* the changes committed by my web server.

If I just do a `session.expire_all()`, and the session is still bound to a transaction with the database, then I would be using the old transaction that was started before my web worker committed changes to the database. And it will make my test read stale data and fail the assertion.

The following updated snippet shows the issue:
```py
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Base = declarative_base()

# engine = create_engine('sqlite:///:memory:', echo=True)

# Using MySQL now, as I need to show what happens when the isolation level is REPEATABLE READS
engine = create_engine("mysql://root@localhost/test", echo=True)  ###### CHANGED BIT HERE ######

class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)

    name = Column(String(40))


Base.metadata.drop_all(engine, checkfirst=True)
Base.metadata.create_all(engine)

Session = sessionmaker(
    bind=engine,
    expire_on_commit=False,  # The important bit
)

session1 = Session()
foo = Foo(name="foo")
session1.add(foo)
session1.commit()

# Now I expire foo. In real life this can happen because there are other functions that sets up objects
# and a lot of things can happen there.
session1.expire(foo)   ###### CHANGED BIT HERE ######

session2 = Session()
foo_2 = session2.query(Foo).filter(Foo.id == foo.id).one()
foo_2.name = "modified_in_session_2"
session2.commit()

# session1.rollback()
session1.expire_all()  ###### CHANGED BIT HERE ######
# Changed rollback to expire_all. Now we still read the old value of foo.name, since the transaction
# was started before changes were committed by session2.
assert foo.name == "modified_in_session_2"
```

**Comment by youtux** [comment]
I understand that rollback was not intended to be used this way, but the documentation said that it would expire all the objects in the session, and that helped a lot.
Of course I can subclass Session so that `Session.rollback()` also invokes `Session.expire_all()`, but I usually don't like make such modifications that change the behaviour of the Session for the whole codebase.

**Comment by zzzeek** [comment]
> I need to call a rollback because I am actually using MySQL with REPEATABLE READS isolation level, and I need to ensure that I am executing queries in a transaction that was started _after_ the changes committed by my web server.
> 
> If I just do a `session.expire_all()`, and the session is still bound to a transaction with the database, then I would be using the old transaction that was started before my web worker committed changes to the database. And it will make my test read stale data and fail the assertion.

Your modified test seems like it isn't quite demonstrating that yet since I am not seeing where "session1" starts its second transaction (expire() shouldn't do that), but overall, if you aren't sure if commit() was just called or not, then you need to check for transaction as follows:

```python
if not session.in_transaction():
    session.expire_all()
else:
    session.rollback()
```

however,  I think you probably would be better off calling begin() explicitly in your application so that you know where the transaction starts and ends.

> I understand that rollback was not intended to be used this way, but the documentation said that it would expire all the objects in the session, and that helped a lot.  Of course I can subclass Session so that Session.rollback() also invokes Session.expire_all(), but I usually don't like make such modifications that change the behaviour of the Session for the whole codebase.

These use cases are all surprises to me, and we had beta releases of SQLAlchemy for more than four months where I was hoping people would have vetted things like this, but unfortunately the vast majority of "surprises" seem to be happening quite slowly subsequent to the 1.4.0 release, and it's too late to reverse major changes like this.

**Comment by youtux** [comment]
> Your modified test seems like it isn't quite demonstrating that yet since I am not seeing where "session1" starts its second transaction (expire() shouldn't do that), but overall, if you aren't sure if commit() was just called or not, then you need to check for transaction as follows:

the second transaction is started when accessing `foo.id`, at this line:
```py
foo_2 = session2.query(Foo).filter(Foo.id == foo.id).one()
```

> however, I think you probably would be better off calling begin() explicitly in your application so that you know where the transaction starts and ends.

Unfortunately, that would raise an exception if a transaction was already in progress, so it still does not provide the old behaviour of rollback, so I would still need to check the state of the session and decide whether to invoke rollback or expire_all().
To me session.rollback() was really handy to both make sure that the transaction is closed and that the objects in the session are expired.
Maybe that's not what rollback() was intended to do, but the documentation said it would work that way, so I would treat it as a "session.reset()" really.

> These use cases are all surprises to me, and we had beta releases of SQLAlchemy for more than four months where I was hoping people would have vetted things like this, but unfortunately the vast majority of "surprises" seem to be happening quite slowly subsequent to the 1.4.0 release, and it's too late to reverse major changes like this.

My guess is that codebases that use sqlalchemy extensively pin it to a specific version, and once the new release branch is "old enough" to be considered stable, that's when people try to upgrade.

**Comment by zzzeek** [comment]
> > Your modified test seems like it isn't quite demonstrating that yet since I am not seeing where "session1" starts its second transaction (expire() shouldn't do that), but overall, if you aren't sure if commit() was just called or not, then you need to check for transaction as follows:
> 
> the second transaction is started when accessing `foo.id`, at this line:
> 
> ```python
> foo_2 = session2.query(Foo).filter(Foo.id == foo.id).one()
> ```
> 
> > however, I think you probably would be better off calling begin() explicitly in your application so that you know where the transaction starts and ends.
> 
> Unfortunately, that would raise an exception if a transaction was already in progress, so it still does not provide the old behaviour of rollback, so I would still need to check the state of the session and decide whether to invoke rollback or expire_all().

OK do what you need to do, but it seems like this code goes in and out of transactional states without it being very predictable, we've tried to emphasize for many years that applications should have a single transactional pattern, like a decorator or context manager at the top level of requests,  that does the same thing every time.  For the pattern of "individual methods want to either begin a transaction, or participate in an existing one", I've pulled back from that being a very desirable pattern because it still suggests a mixing of concerns, however there is a fairly simple recipe for this provided at https://docs.sqlalchemy.org/en/14/orm/session_transaction.html#migrating-from-the-subtransaction-pattern .


> To me session.rollback() was really handy to both make sure that the transaction is closed and that the objects in the session are expired.
> Maybe that's not what rollback() was intended to do, but the documentation said it would work that way, so I would treat it as a "session.reset()" really.

rollback *does* work that way, but only if there's a transaction in progress.   if you use SQLAlchemy 1.3 with autocommit=True and call rollback() wihtout begin(), it will pass silently, not expire anything.  there's nothing "new" here.   the issue you're having is that you were depending on the implicit begin() after commit().  You could just as well call begin() after all your commit() calls and that would be how things used to work.




> 
> > These use cases are all surprises to me, and we had beta releases of SQLAlchemy for more than four months where I was hoping people would have vetted things like this, but unfortunately the vast majority of "surprises" seem to be happening quite slowly subsequent to the 1.4.0 release, and it's too late to reverse major changes like this.
> 
> My guess is that codebases that use sqlalchemy extensively pin it to a specific version, and once the new release branch is "old enough" to be considered stable, that's when people try to upgrade.

it sure is!  unfortunately I can't hold the project back in the stone ages because there's no viable way to get people to beta test.  the introduction of asyncio was actually largely so I could attract more beta testers, which actually worked.     There won't be any releases as broadly changing as 1.4 again, this was the one shot on this.

**Comment by zzzeek** [comment]
yeah continued thinking about this, if you want the behavior as close as possible to 1.3 as far as commit(), you would say:

```python
session.commit()
session.begin()
```

which looks really weird right ?  that's what 1.3 does though.  now can we get that begin() into an event so it's automatic?  let's try:


```python
@event.listens_for(Session, "after_transaction_end")
def _re_begin(session, trans):
    if trans.parent is None:
        session.begin()

```



adding that to your initial test case using SQLAlchemy 1.4.11 before I changed anything, and then it passes.

So you can apply that to your applciation and we can note that in the migration notes etc. as a means of having the "old" beahvior of "eager autobegin" on commit.   it won't cover the case for begin as soon as the Session is started or closed, but those don't matter for this particular use case.

**Comment by youtux** [comment]
Although that would work, I find it more obscure than overriding Session.rollback().
But in the end, I will probably add the expire_all() call in all the places where is needed
