### ISSUE TITLE
is `after_bulk_update` used always after session.delete()?

### ISSUE THREAD

**Issue by Rogalek** [sqlalchemy/sqlalchemy#6371]
Hey, I wonder if `after_bulk_update` is always used after session.delete? 

I am getting a lot of warnings after I run my all tests:
```
  |   /usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py:256: SADeprecationWarning: The argument signature for the "SessionEvents.after_bulk_update" event listener has changed as of version 0.9, and conversion for the old argument signature will be removed in a future release.  The new signature is "def after_bulk_update(update_context)"
  |     fn(*args, **kw)
```

=============================== warnings summary ===============================
`3 failed, 1488 passed, 3 skipped, 9141 warnings in 355.47 seconds`

I am using sqlalchemy events but only those:
- after_insert,
- after_update,
- after_delete

What am I doing wrong? Thanks.

**Versions**
 - OS: Ubuntu 20.04
 - Python: 3.8.0
 - SQLAlchemy: 1.4.11
 - Database: postgres

**Comment by zzzeek** [comment]
hi -

can you run your program with -Werror  (see [warnings](https://docs.python.org/3/library/warnings.html#the-warnings-filter)) and then share the stack trace here for that warning? then we'll know.

**Comment by Rogalek** [comment]
hello,

waiting first for this PR to be accepted: https://github.com/sontek/pyramid_celery/pull/94 in pyramid_celery because I got errors everywhere from that library: `1 failed, 20 passed, 3 skipped, 1470 error in 59.23 seconds`

**Comment by Rogalek** [comment]
ok, so now (after switching to 1.4.15) warnings are more verbose and I see that they are always when I use `.update` or `.delete` in my query.
It's either:
```
SADeprecationWarning: The argument signature for the "SessionEvents.after_bulk_update" event listener has changed as of version 0.9, and conversion for the old argument signature will be removed in a future release.  The new signature is "def after_bulk_update(update_context)"
    DBSession.query(Meeting) \

```
pointing to this query:
```
        DBSession.query(Meeting) \
            .filter(Meeting.id == meeting_id) \
            .update({'timerange': DateTimeTZRange(
            start_tmp, end_tmp, '[)')}, synchronize_session='fetch')
```

or 
```
SADeprecationWarning: The argument signature for the "SessionEvents.after_bulk_delete" event listener has changed as of version 0.9, and conversion for the old argument signature will be removed in a future release.  The new signature is "def after_bulk_delete(delete_context)"
    DBSession.query(Meeting) \

```
pointing to this query:
```
        DBSession.query(Meeting) \
            .filter(Meeting.creator_id == user_1['id']) \
            .delete()
```

Those queries are just examples. It occurs everywhere. Thank you for your help.

**Comment by zzzeek** [comment]
there's an event listener registered in your application, or in one of its dependencies, that is using this event hook with the old argument signature.    you'd have to identify that and get it fixed to remove the warning.

**Comment by zzzeek** [comment]
here's one, looks like it was just fixed 20 days ago:

https://github.com/zopefoundation/zope.sqlalchemy/blame/2126f51ba5d72ad76b14d5895380c8a967b5db9b/src/zope/sqlalchemy/datamanager.py#L311


since you're using pyramid you probably have zope.sqlalchemy running

**Comment by zzzeek** [comment]
see https://github.com/zopefoundation/zope.sqlalchemy/issues/54

**Comment by Rogalek** [comment]
Yes, you are right, that's it. Thank you.

**Comment by zzzeek** [comment]
great
