### ISSUE TITLE
Binding type to a schema specified in metadata (Postgresql)

### ISSUE THREAD

**Issue by Bechma** [sqlalchemy/sqlalchemy#6373]
Following the postgresql examples of the usage of enums that are in the docs https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#sqlalchemy.dialects.postgresql.ENUM:

```python
from sqlalchemy import Column, Integer, MetaData
from sqlalchemy.orm import declarative_base
from sqlalchemy.dialects.postgresql import ENUM

metadata = MetaData(schema="other")
Base = declarative_base(metadata=metadata)

class T1(Base):
    __tablename__ = "t1"

    id = Column(Integer, primary_key=True)
    enumerator = Column(ENUM('a', 'b', 'c', name='myenum', metadata=metadata))

Base.metadata.create_all()
```

What I expect is a new table created in the schema other and a new data type created in the schema other.
However, the enum is always created in the schema public... Am I missing something or this is an expected behaviour?

**Versions**
 - OS: Windows 10
 - Python: 3.8
 - SQLAlchemy: 1.4.11
 - Database: Postgresql 13

Thanks in advance

**Comment by zzzeek** [comment]
hey there -

so this is a very old bug that's never been reported.   What you can do for now is either:

1. use the schema arg on Enum directly, e.g. Enum(...,schema='my_schema')
2. use the "inherit_schema" flag that will inherit schema from the table, e.g. Enum(..., inherit_schema=True)

that said, if metadata is passed to the Enum, and there's no other schema present, it should use that, sure, which is the same as what Sequence() has done for many years.

```diff
diff --git a/lib/sqlalchemy/sql/sqltypes.py b/lib/sqlalchemy/sql/sqltypes.py
index 489594b851..fe7c60cfe5 100644
--- a/lib/sqlalchemy/sql/sqltypes.py
+++ b/lib/sqlalchemy/sql/sqltypes.py
@@ -1105,6 +1105,8 @@ class SchemaType(SchemaEventTarget):
     def _set_table(self, column, table):
         if self.inherit_schema:
             self.schema = table.schema
+        elif self.metadata and self.schema is None and self.metadata.schema:
+            self.schema = self.metadata.schema
 
         if not self._create_events:
             return
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**have SchemaType inherit schema from metadata** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2782
