### ISSUE TITLE
`NullPool` is used for in-memory SQLite database created using URI filenames when `SingletonThreadPool` should have been used instead.

### ISSUE THREAD

**Issue by YongJieYongJie** [sqlalchemy/sqlalchemy#6379]
**Describe the bug**

`NullPool` is used for in-memory SQLite database created using URI filenames* when `SingletonThreadPool` should have been used instead.

*A URI filename looks like `"sqlite:///file:foo.db?mode=memory&uri=true"`, and is described in the SQLite official documentation here: https://www.sqlite.org/inmemorydb.html (relevant portion highlighted in screenshot below).
![image](https://user-images.githubusercontent.com/14101781/116328508-c04f8980-a7fb-11eb-8d41-b965bd6dfe52.png)

**Expected behavior**

`SingletonThreadPool` should be used for connection pooling when a engine is created using a SQLite URI filename with `...?mode=memory&uri=true`.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website, and some [example issues](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22).

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

### Example 1: Wrong thread pool class used
```py
import sqlalchemy

url_colon_memory = "sqlite:///:memory:"
url_mode_memory = "sqlite:///file:foo.db?mode=memory&uri=true"

engine_colon = sqlalchemy.create_engine(url_colon_memory)
engine_mode = sqlalchemy.create_engine(url_mode_memory)

print(engine_colon.pool.__class__) # <class 'sqlalchemy.pool.impl.SingletonThreadPool'>
print(engine_mode.pool.__class__) # <class 'sqlalchemy.pool.impl.NullPool'>

assert engine_colon.pool.__class__ == engine_mode.pool.__class__
```

### Example 2: One implication of using NullPool for in-memory SQLite DB --> Operation are not persisted
```py
import sqlalchemy

# According to SQLite documentation, both strings below should create in-memory databases:
url_colon_memory = "sqlite:///:memory:"
url_mode_memory = "sqlite:///file:foo.db?mode=memory&uri=true"

create_table_stmt = "CREATE TABLE bar (id INTEGER PRIMARY KEY)"
count_table_stmt = "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='bar'"

engine_colon = sqlalchemy.create_engine(url_colon_memory)
engine_colon.execute(create_table_stmt)
num_table_colon = engine_colon.execute(count_table_stmt).one() # Returns `(1,)`as expected.

engine_mode = sqlalchemy.create_engine(url_mode_memory)
engine_mode.execute(create_table_stmt)
num_table_mode = engine_mode.execute(count_table_stmt).one() # Should return `(1,)`, but returns `(0,)` instead.

assert num_table_colon == num_table_mode
```

**Error**

N.A.

**Versions.**
 - OS: Linux Mint 20
 - Python: 3.9.4
 - SQLAlchemy: 1.4.11
 - Database: SQLite
 - DBAPI: pysqlite

**Additional context**

N.A.
**Have a nice day!**

**Comment by zzzeek** [comment]
mode=memory, it might be better to use QueuePool even, but SingletonThreadPool is better than NullPool.

**Comment by YongJieYongJie** [comment]
@zzzeek you are right, I haven't considered QueuePool.

I think we can choose the appropriate pool class as follows:
 - `":memory:"` --> SingletonThreadPool (existing behavior)
 - `"...?mode=memory..."` --> SingletonThreadPool
 - `"...?mode=memory...&cache=shared..."` --> QueuePool

Relevant file is here: https://github.com/sqlalchemy/sqlalchemy/blob/20c0f774e5517514da811bc446812baa6b1f32f1/lib/sqlalchemy/dialects/sqlite/pysqlite.py#L475-L487

**Comment by zzzeek** [comment]
I think the PR should stay as it is, because these are very unusual and esoteric "power user" features, if someone is using them they should know exactly what they want to do, so having a long list of decisionmaking hidden away is not that helpful, folks should use the pool class they want to use (plus check_same_thread is always an issue here as well).  The basic choice of using SingletonThreadPool for mode=memory is all we should do here since that at least matches the current `:memory:` behavior.

**Comment by sqla-tester** [comment]
**YongJieYongJie** has proposed a fix for this issue in the **master** branch:

**Use SingletonThreadPool for in-memory SQLite** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2786
