### ISSUE TITLE
consider disabling #4645 for empty in and generate different cache key instead

### ISSUE THREAD

**Issue by b0urb0n** [sqlalchemy/sqlalchemy#6397]
**Describe the bug**
Somewhere between 1.3.24 and 1.4.0 the treatment of empty tuples used with `in_` changed.  In 1.3.x, an empty tuple was omitted from the compiled query.  In 1.4.x, I see that the new `SQLCompiler` (or in my specific case the `PGCompiler` subclass) creates a placeholder with the `POSTCOMPILE` prefix.  I think it does this in https://github.com/sqlalchemy/sqlalchemy/blob/91562f56185e1e69676712ccb109865a6622a538/lib/sqlalchemy/sql/compiler.py#L1920

https://github.com/sqlalchemy/sqlalchemy/blob/7fdaac7b2910b5612420378519b9f60d4649daff/lib/sqlalchemy/dialects/postgresql/base.py#L2218

After the upgrade to 1.4.x, I see a massive CPU spike on my DB when one of these queries is executed.  I'm guessing that this may be due to a new value being created for each comparison but I don't know enough about PG or SQLA internals to say for certain.

In my case, if an empty tuple was provided, the value of the `POSTCOMPILE` placeholder resolves to something like `(SELECT CAST(NULL AS VARCHAR(40)) WHERE 1!=1)`.  I'm not entirely sure why this causes a massive increase in query time and CPU usage, but it does.  The table being queried has over 400 million records in it ([NSRL dataset](https://www.nist.gov/itl/ssd/software-quality-group/national-software-reference-library-nsrl/about-nsrl)).

With 1.3.x, the empty tuple was actually dropped from the query entirely:
```
SELECT hashes.id, hashes.md5, hashes.sha1
FROM hashes
WHERE hashes.md5 IN (%(md5_1)s) OR 1 != 1
```

In 1.4.x, the empty tuple is replaced with the cast:
```
SELECT hashes.id
FROM hashes
WHERE hashes.md5 IN ([POSTCOMPILE_md5_1]) OR hashes.sha1 IN ([POSTCOMPILE_sha1_1])
```

Some issues I think may be related:
https://github.com/sqlalchemy/sqlalchemy/issues/6290
https://github.com/sqlalchemy/sqlalchemy/issues/6222
https://github.com/sqlalchemy/sqlalchemy/issues/4271

**Expected behavior**
My queries to not take minutes.

**To Reproduce**
```py
import sqlalchemy
from sqlalchemy import Table, Column, String, Integer, or_

metadata = sqlalchemy.MetaData()

hashes_table = Table(
    'hashes', metadata,
    Column('id', Integer, primary_key=True),
    Column('md5', String(32)),
    Column('sha1', String(40)),
)

sel = sqlalchemy.select(
    hashes_table.columns.id  # 1.4.x
    #hashes.table.columns  # 1.3.x
).where(
    or_(
        hashes_table.columns['md5'].in_(['some_md5_sum']),
        hashes_table.columns['sha1'].in_([])
    )
)

engine = sqlalchemy.create_engine('postgresql://...')
q = sel.compile(dialect=engine.dialect)
print(q)

connection = engine.connect()
results = connection.execute(q).fetchall()
# This will take a really long time in large tables
```

**Error**
No stack trace available as the query will complete eventually.  However, the issue is the inefficient behavior resulting from the query.  Specifically, the nested `SELECT CAST(...)` I think.

**Versions.**
 - OS: Any
 - Python: Python3.7
 - SQLAlchemy: 1.4.x
 - Database: PostgreSQL
 - DBAPI: 

**Additional context**
This issue seems to only show up with large tables.  My specific use-case is with the NSRL File table from the [NSRL RDS](https://www.nist.gov/itl/ssd/software-quality-group/national-software-reference-library-nsrl/nsrl-download/current-rds) set.  It contains over 400 million records of common binaries and their cryptographic hashes.

**Have a nice day!**

**Comment by zzzeek** [comment]
There's no trivial way to change this behavior as we need to have an empty set to generate within the IN() parenthesization.

can you run EXPLAIN ANALYZE to see why this empty set expression is causing a problem ?

**Comment by zzzeek** [comment]
the other issue where this set compilation is a problem is #6258, though that's a specific place.

If this IN is producing a problem, the expression can be substituted using an approach like this:

```python

from sqlalchemy import null
list_ = []

s.query(A).filter(A.id.in_([null()] if not list_ else list_)).all()
```

**Comment by zzzeek** [comment]
I wonder if we can use ARRAY[] there instead, lets try

**Comment by zzzeek** [comment]
here's a different syntax, for composite support it has to be a little more verbose, the patch is:

```diff
diff --git a/lib/sqlalchemy/dialects/postgresql/base.py b/lib/sqlalchemy/dialects/postgresql/base.py
index 47a933479f..cb14d7f0db 100644
--- a/lib/sqlalchemy/dialects/postgresql/base.py
+++ b/lib/sqlalchemy/dialects/postgresql/base.py
@@ -2213,15 +2213,14 @@ class PGCompiler(compiler.SQLCompiler):
         # cast the empty set to the type we are comparing against.  if
         # we are comparing against the null type, pick an arbitrary
         # datatype for the empty set
-        return "SELECT %s WHERE 1!=1" % (
-            ", ".join(
-                "CAST(NULL AS %s)"
-                % self.dialect.type_compiler.process(
-                    INTEGER() if type_._isnull else type_
-                )
-                for type_ in element_types or [INTEGER()]
-            ),
-        )
+
+        return "SELECT * FROM unnest(" + ", ".join(
+            "ARRAY[]::%s[]"
+            % self.dialect.type_compiler.process(
+                INTEGER() if type_._isnull else type_
+            )
+            for type_ in element_types or [INTEGER()]
+        ) + ")"
 
     def render_literal_value(self, value, type_):
         value = super(PGCompiler, self).render_literal_value(value, type_)
```


can you try this query and check the EXPLAIN ANALYZE for it?   

```

SELECT hashes.id
FROM hashes
WHERE hashes.md5 IN (.. .values ...) OR hashes.sha1 IN (SELECT * FROM unnest(ARRAY[]::VARCHAR(40)[]))
```

**Comment by b0urb0n** [comment]
> can you run EXPLAIN ANALYZE to see why this empty set expression is causing a problem ?

```
                                                          QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------
 Seq Scan on nsrl_file  (cost=0.01..13893412.54 rows=163817502 width=116) (actual time=105719.757..105719.757 rows=0 loops=1)
   Filter: (((md5)::text = '6507c499f9f66673de194ecf2b1b0c0c'::text) OR (hashed SubPlan 1))
   Rows Removed by Filter: 478722226
   SubPlan 1
     ->  Result  (cost=0.00..0.01 rows=1 width=0) (actual time=0.001..0.001 rows=0 loops=1)
           One-Time Filter: false
 Total runtime: 105720.090 ms
(7 rows)
```

**Comment by b0urb0n** [comment]
> can you try this query and check the EXPLAIN ANALYZE for it?
```
EXPLAIN ANALYZE SELECT *
FROM nsrl_file
WHERE md5 IN ('6507c499f9f66673de194ecf2b1b0c0c') OR sha1 IN (SELECT * FROM unnest(ARRAY[]::VARCHAR(40)[]) WHERE 1!=1);
                                                          QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------
 Seq Scan on nsrl_file  (cost=1.00..13893413.54 rows=163817502 width=116) (actual time=103861.181..103861.181 rows=0 loops=1)
   Filter: (((md5)::text = '6507c499f9f66673de194ecf2b1b0c0c'::text) OR (hashed SubPlan 1))
   Rows Removed by Filter: 478722226
   SubPlan 1
     ->  Result  (cost=0.00..1.00 rows=1 width=32) (actual time=0.000..0.000 rows=0 loops=1)
           One-Time Filter: false
           ->  Function Scan on unnest  (cost=0.00..1.00 rows=1 width=32) (never executed)
 Total runtime: 103861.224 ms
(8 rows)
```

**Comment by zzzeek** [comment]
so...if you have a real subquery there with a value in it, what happens?      or if you have a literal value there, what happens?    PG is usually not this unreasonable.    

as mentioned previously I don't have any automatic way for this to render "1 != 1" we cache SQL statements now and the feature would need some significant alteration. likely to generate an entirely different cache key for the statement if the list is empty.

**Comment by b0urb0n** [comment]
Here's the query with a dummy value:

```
EXPLAIN ANALYZE SELECT *
FROM nsrl_file
WHERE md5 IN ('6507c499f9f66673de194ecf2b1b0c0c') OR sha1 IN ('abc');
                                                             QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on nsrl_file  (cost=761.84..20486.80 rows=5002 width=116) (actual time=1.466..1.466 rows=0 loops=1)
   Recheck Cond: (((md5)::text = '6507c499f9f66673de194ecf2b1b0c0c'::text) OR ((sha1)::text = 'abc'::text))
   ->  BitmapOr  (cost=761.84..761.84 rows=5002 width=0) (actual time=1.464..1.464 rows=0 loops=1)
         ->  Bitmap Index Scan on ix_nsrl_file_md5  (cost=0.00..347.77 rows=2501 width=0) (actual time=0.630..0.630 rows=0 loops=1)
               Index Cond: ((md5)::text = '6507c499f9f66673de194ecf2b1b0c0c'::text)
         ->  Bitmap Index Scan on ix_nsrl_file_sha1  (cost=0.00..411.57 rows=2501 width=0) (actual time=0.834..0.834 rows=0 loops=1)
               Index Cond: ((sha1)::text = 'abc'::text)
 Total runtime: 1.496 ms
(8 rows)
```

**Comment by CaselIT** [comment]
this is to create a sample db:
```sql
create table hashes (
	id integer primary key,
	md5 VARCHAR(32) not null,
	sha1 VARCHAR(40) not null
);
create extension pgcrypto;
insert into hashes 
select id, md5(id::text) as md5, encode(digest(id::text, 'sha1'), 'hex') as sha1
from generate_series(1, 1000000) as id
--create index on hashes(md5, sha1)
create index on hashes(md5);
create index on hashes(sha1);
analyze hashes
```

modify the `generate_series` to get the desidered size

**Comment by CaselIT** [comment]
with 1m rows the plan match the one posted by @b0urb0n 

It seems that pg cannot infer that the sha1 in is false so it does not simplify it and revert to a sequential scan

**Comment by b0urb0n** [comment]
With an actual subquery:
```
EXPLAIN ANALYZE SELECT *
FROM nsrl_file
WHERE md5 IN ('6507c499f9f66673de194ecf2b1b0c0c') OR sha1 IN (SELECT sha1 from sample where id=1234);
                                                          QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------
 Seq Scan on nsrl_file  (cost=8.46..13893420.99 rows=163817502 width=116) (actual time=175517.537..175517.537 rows=0 loops=1)
   Filter: (((md5)::text = '6507c499f9f66673de194ecf2b1b0c0c'::text) OR (hashed SubPlan 1))
   Rows Removed by Filter: 478722226
   SubPlan 1
     ->  Index Scan using sample_pkey on sample  (cost=0.00..8.46 rows=1 width=41) (actual time=1.164..1.165 rows=1 loops=1)
           Index Cond: (id = 1234)
 Total runtime: 175517.580 ms
(7 rows)
```

**Comment by zzzeek** [comment]
given #6258 as well we'd need to go back to default_comparator._in_impl() and generate a totally different object when the list is empty so that there is simply a different cache key, then we just have it render 1!=1 again.   the empty in feature was introduced a few years ago literally in https://docs.sqlalchemy.org/en/14/changelog/migration_13.html#change-4271 , and like always, it looks like not enough people used it for us to find issues like this

**Comment by zzzeek** [comment]
please use the workaround for now

**Comment by CaselIT** [comment]
workaround for pg:

`sha1 = any(array[]::VARCHAR(40)[]);`

**Comment by CaselIT** [comment]
```sql
explain analyze
SELECT hashes.id
FROM hashes
WHERE hashes.md5 IN (
'c4ca4238a0b923820dcc509a6f75849b',
'c81e728d9d4c2f636f067f89cc14862c',
'eccbc87e4b5ce2fe28308fd9f2a7baf3',
'a87ff679a2f3e71d9181a67b7542122c',
'e4da3b7fbbce2345d7772b0674a318d5',
'1679091c5a880faf6fb5e6087eb1b2dc',
'8f14e45fceea167a5a36dedd4bea2543'
)
OR sha1 = any(array[]::VARCHAR(40)[]);
```

returns

```
Bitmap Heap Scan on hashes  (cost=35.46..63.11 rows=7 width=4) (actual time=0.413..0.420 rows=7 loops=1)
  Recheck Cond: (((md5)::text = ANY ('{c4ca4238a0b923820dcc509a6f75849b,c81e728d9d4c2f636f067f89cc14862c,eccbc87e4b5ce2fe28308fd9f2a7baf3,a87ff679a2f3e71d9181a67b7542122c,e4da3b7fbbce2345d7772b0674a318d5,1679091c5a880faf6fb5e6087eb1b2dc,8f14e45fceea167a5a36dedd4bea2543}'::text[])) OR ((sha1)::text = ANY ('{}'::text[])))
  Heap Blocks: exact=1
  ->  BitmapOr  (cost=35.46..35.46 rows=7 width=0) (actual time=0.398..0.401 rows=0 loops=1)
        ->  Bitmap Index Scan on hashes_md5_idx  (cost=0.00..31.03 rows=7 width=0) (actual time=0.395..0.395 rows=7 loops=1)
              Index Cond: ((md5)::text = ANY ('{c4ca4238a0b923820dcc509a6f75849b,c81e728d9d4c2f636f067f89cc14862c,eccbc87e4b5ce2fe28308fd9f2a7baf3,a87ff679a2f3e71d9181a67b7542122c,e4da3b7fbbce2345d7772b0674a318d5,1679091c5a880faf6fb5e6087eb1b2dc,8f14e45fceea167a5a36dedd4bea2543}'::text[]))
        ->  Bitmap Index Scan on hashes_sha1_idx  (cost=0.00..4.43 rows=1 width=0) (actual time=0.001..0.001 rows=0 loops=1)
              Index Cond: ((sha1)::text = ANY ('{}'::text[]))
Planning Time: 0.630 ms
Execution Time: 0.794 ms
```

**Comment by CaselIT** [comment]
@b0urb0n can you check if that works for you?

**Comment by CaselIT** [comment]
> 
> 
> workaround for pg:
> 
> `sha1 = any(array[]::VARCHAR(40)[]);`

the corresponding `not in` -> ` `sha1 != all(array[]::VARCHAR(40)[]);``  seems to also work similar to the optimizer 1==1 wrt the optimizier

**Comment by b0urb0n** [comment]
Looks like that may solve the problem

```
EXPLAIN ANALYZE SELECT *
FROM nsrl_file
WHERE md5 IN ('6507c499f9f66673de194ecf2b1b0c0c') OR sha1 = any(array[]::VARCHAR(40)[]);
                                                             QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on nsrl_file  (cost=574.18..10653.52 rows=2544 width=116) (actual time=0.286..0.286 rows=0 loops=1)
   Recheck Cond: (((md5)::text = '6507c499f9f66673de194ecf2b1b0c0c'::text) OR ((sha1)::text = ANY ('{}'::text[])))
   ->  BitmapOr  (cost=574.18..574.18 rows=2544 width=0) (actual time=0.284..0.284 rows=0 loops=1)
         ->  Bitmap Index Scan on ix_nsrl_file_md5  (cost=0.00..348.09 rows=2544 width=0) (actual time=0.283..0.283 rows=0 loops=1)
               Index Cond: ((md5)::text = '6507c499f9f66673de194ecf2b1b0c0c'::text)
         ->  Bitmap Index Scan on ix_nsrl_file_sha1  (cost=0.00..224.82 rows=1 width=0) (actual time=0.000..0.000 rows=0 loops=1)
               Index Cond: ((sha1)::text = ANY ('{}'::text[]))
 Total runtime: 0.312 ms
(8 rows)
```

**Comment by CaselIT** [comment]
still worse than the `OR 1 != 1` that was just omitted but at least it can property plan for it.

@zzzeek I think we could implement it this way for pg for now, then look at changing the cache in case of empty list at a later time if still needed.
what do you think?

**Comment by CaselIT** [comment]
On second thought that may not be possible in all cases, since it would mean rendering the `IN` always as `= any()`

**Comment by zzzeek** [comment]
no it's not possible because it changes the operator.   we will go back to 1 != 1

**Comment by CaselIT** [comment]
yes, we would need to render all `in` as `= any ()` for it to work.
They are equal (pg does transforms in to that form) but would be a bit surprising.

**Comment by zzzeek** [comment]
interestingly, the way I'm doing this, lambda statements will still use the new way, which they kind of have to, because the cache key is based on the lambda itself and it otherwise wouldnt be that easy to differentiate.    maybe that can be done also but i think it's fine to leave the "new" way for lambda statemnets for now since these are not the norm, and we would not be using "empty in" within relationship loaders.

**Comment by zzzeek** [comment]
OK @CaselIT  has another idea that is a lot more self contained if it works...

**Comment by CaselIT** [comment]
basically doing kind of sql injection on ourself:

postcompile would be `SELECT CAST(NULL AS VARCHAR(40)) WHERE 1!=1) and (1 != 1`

**Comment by CaselIT** [comment]
it does work:

```
explain analyze
SELECT hashes.id
FROM hashes
WHERE hashes.md5 IN (
'c4ca4238a0b923820dcc509a6f75849b',
'c81e728d9d4c2f636f067f89cc14862c',
'eccbc87e4b5ce2fe28308fd9f2a7baf3',
'a87ff679a2f3e71d9181a67b7542122c',
'e4da3b7fbbce2345d7772b0674a318d5',
'1679091c5a880faf6fb5e6087eb1b2dc',
'8f14e45fceea167a5a36dedd4bea2543'
)
OR sha1 in (SELECT CAST(NULL AS VARCHAR(40)) WHERE 1!=1) and (1 != 1)
```
explain
```
Index Scan using hashes_md5_idx on hashes  (cost=0.42..59.09 rows=7 width=4) (actual time=0.040..0.148 rows=7 loops=1)
  Index Cond: ((md5)::text = ANY ('{c4ca4238a0b923820dcc509a6f75849b,c81e728d9d4c2f636f067f89cc14862c,eccbc87e4b5ce2fe28308fd9f2a7baf3,a87ff679a2f3e71d9181a67b7542122c,e4da3b7fbbce2345d7772b0674a318d5,1679091c5a880faf6fb5e6087eb1b2dc,8f14e45fceea167a5a36dedd4bea2543}'::text[]))
Planning Time: 0.389 ms
Execution Time: 0.159 ms
```

**Comment by CaselIT** [comment]
Yes can probably just use `null` instead of the subquery: `OR sha1 in (null) and (1 != 1)`

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use non-subquery form for empty IN** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2789

**Comment by zzzeek** [comment]
to the reporter -

the SQL for "sha1.in_([])" will now look like :

```sql
SELECT *
FROM nsrl_file
WHERE md5 IN ('6507c499f9f66673de194ecf2b1b0c0c') OR sha1 IN (NULL) AND 1 != 1;
```

If you want to triple check this solves the planner issue on your end as well I am planning to release later today

**Comment by b0urb0n** [comment]
Confirmed that your fix seems to work fine:

```
EXPLAIN ANALYZE SELECT *
FROM nsrl_file
WHERE md5 IN ('6507c499f9f66673de194ecf2b1b0c0c', 'a87ff679a2f3e71d9181a67b7542122c') OR sha1 IN (NULL) AND 1 != 1;
                                                           QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on nsrl_file  (cost=512.70..20557.14 rows=5087 width=116) (actual time=1.423..3.106 rows=164 loops=1)
   Recheck Cond: ((md5)::text = ANY ('{6507c499f9f66673de194ecf2b1b0c0c,a87ff679a2f3e71d9181a67b7542122c}'::text[]))
   ->  Bitmap Index Scan on ix_nsrl_file_md5  (cost=0.00..511.42 rows=5087 width=0) (actual time=1.222..1.222 rows=164 loops=1)
         Index Cond: ((md5)::text = ANY ('{6507c499f9f66673de194ecf2b1b0c0c,a87ff679a2f3e71d9181a67b7542122c}'::text[]))
 Total runtime: 3.188 ms
(5 rows)
```

Thanks for everyone's work on this!
