### ISSUE TITLE
Fatal error on SSL transport

### ISSUE THREAD

**Issue by Timtaran** [sqlalchemy/sqlalchemy#6399]
**Describe the bug**
I'm trying to use PostgreSQL(hosting - ElephantSQL free)

**Expected behavior**

**Please do not use Flask-SQLAlchemy or any other third-party extensions or dependencies in test cases**.  The test case must illustrate the problem **without** using any third party SQLAlchemy extensions.  Otherwise, please report the bug to those projects first.

```py
from src import create
import asyncio
asyncio.run(create())
```
https://pastebin.com/jRAhfxyZ

**Error**

```
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x00000000041DF4C0>
transport: <_ProactorSocketTransport fd=424 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\sslproto.py", line 685, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000000000286B790>
```

**Versions.**
 - OS: W7x64
 - Python: 3.8.6
 - SQLAlchemy: 1.14.11
 - Database: PSQL
 - DBAPI: asyncpg

**Additional context**

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi
there code you provided has no call to the create engine. or an example of the url. without it is hard to guess what may be wrong

**Comment by Timtaran** [comment]
engine = create_async_engine(
        "postgresql+asyncpg://***:***@rogue.db.elephantsql.com:5432/***",
        echo=other['debug-db'],
    )

**Comment by Timtaran** [comment]
earlier its working

**Comment by zzzeek** [comment]
this is a low level issue that might be better suited for the asyncpg list since it seems you are using SSL : https://github.com/MagicStack/asyncpg

**Comment by Timtaran** [comment]
But how I can disable SSH (I got info about this error was excepted with SSH)

**Comment by zzzeek** [comment]
I have no idea why there's SSL in your stack trace.   the asyncpg people definitely know more about this than we do, if they can point back to where we are doing something wrong, then great.

**Comment by Timtaran** [comment]
Okay, but that drivers I can use(I find only sync drivers)?
