### ISSUE TITLE
Infer type for dialects.postgresql.UUID(as_uuid=True)

### ISSUE THREAD

**Issue by charlax** [sqlalchemy/sqlalchemy#6402]
**Is your feature request related to a problem? Please describe.**

```python
from sqlalchemy import Column, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import declarative_base

Base = declarative_base()
UUIDC = UUID(as_uuid=True)


class Foo(Base):
    id = Column(UUIDC)
    bar_id = Column(UUIDC, ForeignKey("bars.id"))
```

This will yield the following errors:

```text
$ mypy --strict testuuidc.py
testuuidc.py:10: error: Need type annotation for 'id'
testuuidc.py:11: error: [SQLAlchemy Mypy plugin] Can't infer type from ORM mapped expression assigned to attribute 'bar_id'; please specify a Python type or Mapped[<python type>] on the left hand side.
Found 2 errors in 1 file (checked 1 source file)
```

**Describe the solution you'd like**

I wonder if thanks to the plugin, mypy wouldn't be able to infer the `uuid.UUID` type from the `postgresql.UUID(as_uuid=True)` definition.

**Describe alternatives you've considered**

Obviously, we can always provide the typing explicitly.

**Have a nice day!**

Thanks a lot for the amazing work on sqlalchemy!

**Comment by charlax** [comment]
Actually, providing the typing explictly fails:

```python
from uuid import UUID

from sqlalchemy import Column, ForeignKey, Integer
from sqlalchemy.dialects.postgresql import UUID as _UUIDC
from sqlalchemy.orm import declarative_base, Mapped

Base = declarative_base()
UUIDC = _UUIDC(as_uuid=True)


class Foo(Base):
    id = Column(UUIDC)
    id2: UUID = Column(UUIDC)
    id3: Mapped[UUID] = Column(UUIDC)

    bar_id = Column(UUIDC, ForeignKey("bars.id"))

    int1 = Column(Integer)
    int2: int = Column(Integer)
    int3: Mapped[int] = Column(Integer)
```

This yields the following errors:

```text
$ mypy --strict testuuidc.py
testuuidc.py:12: error: Need type annotation for 'id'
testuuidc.py:13: error: Incompatible types in assignment (expression has type "Column[<nothing>]", variable has type "UUID")
testuuidc.py:14: error: Incompatible types in assignment (expression has type "Column[<nothing>]", variable has type "Mapped[UUID]")
testuuidc.py:16: error: [SQLAlchemy Mypy plugin] Can't infer type from ORM mapped expression assigned to attribute 'bar_id'; please specify a Python type or Mapped[<python type>] on the left hand side.
Found 4 errors in 1 file (checked 1 source file)
```

**Comment by zzzeek** [comment]
it's likely the indirect reference to UUID.    for the as_uuid part we probably will need to make separate type objects for the various types that have "as_decimal", "as_uuid", etc.

**Comment by charlax** [comment]
You're right @zzzeek, this works fine:

```python
id1: UUID = Column(_UUIDC(as_uuid=True))
```

Although I guess the alias `UUIDC = _UUIDC(as_uuid=True)` should have worked too? Is it also something to be fixed?

I assume the fix would go somewhere in https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/ext/mypy/infer.py?

**Comment by zzzeek** [comment]
yes it would!

**Comment by zzzeek** [comment]
in 2.0 you can map this first like this:

```py
from uuid import UUID as _py_uuid

class Base(DeclarativeBase):
    pass


class Test(Base):
    __tablename__ = "test_table_json"

    id = mapped_column(Integer, primary_key=True)

    ident: Mapped[_py_uuid] = mapped_column(UUID())

    ident_str: Mapped[str] = mapped_column(UUID(as_uuid=False))

```

but also, we will likely have Python uuid as a full core type so you would also be able to map UUID as:

```py
from uuid import UUID as _py_uuid

class Base(DeclarativeBase):
    pass


class Test(Base):
    __tablename__ = "test_table_json"

    id = mapped_column(Integer, primary_key=True)

    ident: Mapped[_py_uuid]

```

the PG UUID type still needs to be typed and to have the appropriate overloads so will add that here.

integration of uuid as a first class Core type is #7212

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add typing for PG UUID, other types** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3870
