### ISSUE TITLE
Using django-like filters with sqlalchemy 1.4

### ISSUE THREAD

**Issue by AbdealiJK** [sqlalchemy/sqlalchemy#6405]
**Describe your question**
For quite a while now - I've been using the django-like query format shown in:
https://github.com/mitsuhiko/sqlalchemy-django-query/blob/master/sqlalchemy_django_query.py
With sqlalchemy 1.4 - this example code does not work anymore, because `._joinpoint_zero()` isn't a valid function anymore

I was hoping to check here if there are any suggestions of how this code could be tweaked so I can use it with sqlalchemy 1.4

**Example - please use the [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) guidelines if possible**
https://github.com/mitsuhiko/sqlalchemy-django-query/blob/master/tests.py

**Versions**
 - OS: Ubuntu 18.04
 - Python: 3.7.4
 - SQLAlchemy: 1.3.x - but trying to move to 1.4.11
 - Database:
 - DBAPI:

**Comment by zzzeek** [comment]
the query works pretty differently now but I think you can probably replace joinpoint_zero() for [_filter_by_zero()](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/query.py#L1697) or maybe _last_joined_entity.
