### ISSUE TITLE
mypy plugin: infer relationship information for models specified as strings

### ISSUE THREAD

**Issue by huonw** [sqlalchemy/sqlalchemy#6407]
**Is your feature request related to a problem? Please describe.**

Currently the mypy plugin can infer types/information for a `relationship` when the model parameter is an actual class value, but cannot do so when it is a string:

```python
from sqlalchemy import Column, Integer, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import as_declarative
from typing import List, Optional

@as_declarative()
class Base:
    pass

class Foo(Base):
    id = Column(Integer(), primary_key=True)
    bars = relationship("Bar", back_populates="foo", uselist=True)
    # error, must be: bars: List["Bar"] = relationship("Bar", back_populates="foo", uselist=True)

class Bar(Base):
    id = Column(Integer(), primary_key=True)
    foo_id: Optional[int] = Column(ForeignKey(Foo.id))
    foo = relationship(Foo, back_populates="bars", uselist=False)

# successful inference:
reveal_type(Bar().foo) # Union[test2.Foo, None]
```

**Describe the solution you'd like**

In https://github.com/sqlalchemy/sqlalchemy/discussions/6372, we discussed that string parameters could be handled via doing a name lookup in the current module, similar to the plugin in https://github.com/dropbox/sqlalchemy-stubs. This requires the other model name being imported (potentially in an `if TYPE_CHECKING:` block), but that's okay: doing the explicit type annotation also requires the name being in scope for mypy.

(This approach could potentially be used for `Column(ForeignKey("Abc.def"), ...)` too, but it was mentioned in #6372 that doing the `.def` lookup might be hard.)

**Describe alternatives you've considered**

The current situation of annotating the type explicitly is a little suboptimal, as the plugin doesn't validate, that, for instance, the collection types are correct. Another option would to have the righthand side be partially inferred, e.g. `list[_]` and then do a type join between LHS and RHS; if the LHS annotation is `list[Bar]`, then the join will be successful, but if it's very wrong (e.g. just `Bar`), then the `join(Bar, list[_])` will not be possible an error can be reported.

**Additional context**
N/A

**Have a nice day!** you too 😄

**Comment by huonw** [comment]
I quickly experimented with an implementation for this at https://github.com/sqlalchemy/sqlalchemy/compare/master...huonw:mypy-resolve-strings but it struggles to handle the multi-pass nature of mypy. In particular, for the example in the issue:
- the `Bar` class isn't resolvable the first time `Foo` is processed, so the pass is `defer`ed and the attr is given an "error" Any type
- on the second pass, it seems to work as expected (in that `"Bar"` can be resolved and the type is inferred to `list[Bar]`, if I add internally logging), but the type doesn't seem to get written correctly, and mypy still reports "Need type annotation for 'bars'"

I note that the sqlalchemy-stubs plugin seems to focus just on individual functions: it provides `get_function_hook` to change the type of these calls, and it seems this runs after all the top-level classes etc. are available.

**Comment by zzzeek** [comment]
mypy plugins are not easy

**Comment by zzzeek** [comment]
unless the logic here also confirms that "Bar" is a mapped class on the same mapper registry, we can have this problem:

```python

# file 1

class Foo(Base):
    id = Column(Integer(), primary_key=True)
    bars = relationship("Bar", back_populates="foo", uselist=True)

Bar = "im not a mapped class"
```
```python
# file 2

from .file1 import Base

class Bar(Base):
    id = Column(Integer(), primary_key=True)
    foo_id: Optional[int] = Column(ForeignKey(Foo.id))
    foo = relationship(Foo, back_populates="bars", uselist=False)
```


how do you propose to handle that?   I would imagine the existing plugin gets this wrong.

**Comment by huonw** [comment]
Ah, that's an interesting edge case. Type checkers/systems have to be conservative, so I think it's fine to call that code unsupported, requiring the user to either refactor their code or provide a manual annotation.

That is, I'd personally an error message like

> relationship Bar refers to a value that isn't a mapped class in this module; either import the correct Bar or provide an explicit annotation

In particular, I think it should be possible for mypy to validate that the value returned by the lookup is a class, and in particular a class that inherits from the same declarative base?

**Comment by CaselIT** [comment]
I guess we can close as will not fix since v2 will not use the plugin

**Comment by zzzeek** [comment]
it's all in 2.0 now, docs are not up yet save for the quickstart at https://docs.sqlalchemy.org/en/20/orm/quickstart.html where you can see relationship() works in the most minimal way possible, inferring the class from the string annotation.
