### ISSUE TITLE
legacy result object needs to allow .keys() even if no rows

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6427]
```python
from sqlalchemy import create_engine


e = create_engine("sqlite://")
with e.begin() as conn:
    result = conn.execute("create table foo (id integer)")
    result.keys()  # raises, should be warning for legacy
```

**Comment by zzzeek** [comment]
this is used by Records in particular so this should just warn.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Establish deprecation path for CursorResult.keys()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2803

**Comment by fabiool** [comment]
Hi there, has this fix been already released? It seems 1.4.13 doesn't include it. 
Thanks!

**Comment by zzzeek** [comment]
no it has not, it's 1.4.14

**Comment by fabiool** [comment]
Thanks Mike. I will be looking forward for the new release then.
