### ISSUE TITLE
error in documentation re. usage of default parameter

### ISSUE THREAD

**Issue by cicuz** [sqlalchemy/sqlalchemy#6458]
I think that the example at [line 102 in the mixins documentation page](https://github.com/sqlalchemy/sqlalchemy/blame/master/doc/build/orm/declarative_mixins.rst#L102) is wrong, as it shows passing _a call_ to the `now` function as the default value, instead of the callable object itself.

I couldn't really find where to discuss this so I'm opening a bug report here as it seems fastest and easiest, hope it's right.

**Comment by CaselIT** [comment]
No problem

> I couldn't really find where to discuss this so I'm opening a bug report here as it seems fastest and easiest, hope it's right.

Here a listed some alternative communication methods https://www.sqlalchemy.org/support.html
