### ISSUE TITLE
subqueryload isn't caching

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6459]
not sure what is happening here, but two things to note:

1. the subqueryload never caches, period.  not sure if this is dependent on being from the lazy loader or not.
2. it is using the lazy loader's cache, which seems a little strange

Running this with -Werror hits the size alert for the A.b lazyloader.

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    b_id = Column(ForeignKey("b.id"))
    b = relationship("B")


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    c1 = relationship("C1", lazy="subquery")


class C1(Base):
    __tablename__ = "c1"
    id = Column(Integer, primary_key=True)
    b_id = Column(ForeignKey("b.id"))


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(
    A(
        b=B(
            c1=[C1()],
        )
    )
)
s.commit()


def go():
    s.close()
    a1 = s.query(A).first()
    a1.b


for i in range(50):
    go()
```

**Comment by zzzeek** [comment]
nope, it's subuqeryloader across the board.   crazy

**Comment by CaselIT** [comment]
Well I guess better not caching that caching the wrong thing :)

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Correct cache key for proxy_owner, with_context_options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2817

**Comment by zzzeek** [comment]
OK the thing with using the lazy loaders cache is sort of to be expected, and i think the solution to that, later, will be to just remove the lazyload/selectinload caches and just have them use the main cache.

**Comment by AbdealiJK** [comment]
Hi, I was migrating from 1.3.24 to 1.4.17, and saw a bunch of warnings appearing in sqlalchemy - and was fixing them.

Saw this in the Release notes of 1.4.15 and wanted to understand whether what I'm seeing right now is correct or not:
> Fixed issue in subquery loader strategy which prevented caching from working correctly. This would have been seen in the logs as a “generated” message instead of “cached” for all subqueryload SQL emitted, which by saturating the cache with new keys would degrade overall performance; it also would produce “LRU size alert” warnings.

Right now, I have multiple relationships like: `author = relationship(Author, lazy='selectin')`
And I seem to be getting this warning:
> LRU cache size alert for loader strategy: Book.author

Looks like this happens for a bunch of relationships using the `lazy='selectin'` relationship, but doesn't seem to happen for `lazy='select'`

Is this expected, and what should I be doing different to avoid the warning ?

**Comment by zzzeek** [comment]
> Hi, I was migrating from 1.3.24 to 1.4.17, and saw a bunch of warnings appearing in sqlalchemy - and was fixing them.
> 
> Saw this in the Release notes of 1.4.15 and wanted to understand whether what I'm seeing right now is correct or not:
> 
> > Fixed issue in subquery loader strategy which prevented caching from working correctly. This would have been seen in the logs as a “generated” message instead of “cached” for all subqueryload SQL emitted, which by saturating the cache with new keys would degrade overall performance; it also would produce “LRU size alert” warnings.
> 
> Right now, I have multiple relationships like: `author = relationship(Author, lazy='selectin')`
> And I seem to be getting this warning:
> 
> > LRU cache size alert for loader strategy: Book.author
> 
> Looks like this happens for a bunch of relationships using the `lazy='selectin'` relationship, but doesn't seem to happen for `lazy='select'`
> 
> Is this expected, and what should I be doing different to avoid the warning ?

it's kind of semi-expected right now, for the case where this loader strategy is used in lots of different combinations of things, and there's a plan to move the caching around a bit and not have this warning.    the warning is mostly there for people to report to me that they are getting it, so i can understand the use cases better.

so on that note, I'd like to see how you are getting this warning and there are two options.   one is, if you can make a short standalone script that reproduces it.  This is likely not very easy for this warning.  The other is, I have a patch that you can apply to your SQLAlchemy library which you can then configure so that instead of the warning here, it will dump out a .zip file of your cache that you can send to me so I can see what's happening in your case.      this is attached here.

if you then run your program as:

     SQLALCHEMY_DEBUG_SIZE_ALERT=1 python myprogram.py

instead of the warning it will just raise an exception and also provide a .zip file that I can use to see how the cache is getting filled up here.

[size_alert.patch.txt](https://github.com/sqlalchemy/sqlalchemy/files/6591696/size_alert.patch.txt)

**Comment by AbdealiJK** [comment]
Thanks @zzzeek - You're right, making a minimal example wasn't easy ...
I've sent you the output of the above log to your email

**Comment by CaselIT** [comment]
@zzzeek do you think it may be worth it to merge that change, so it's easier to debug cache issues?

**Comment by zzzeek** [comment]
well im going to remove the warning from the loader strategies altogether so the warning won't be seen anymore.  for the main cache, im not sure what we'd do with a dump of 700 items, so while ther are some debugging features on cachekey im not sure about the dump feature.
