### ISSUE TITLE
autoincrement flag configuration from table args

### ISSUE THREAD

**Issue by bfmcneill** [sqlalchemy/sqlalchemy#6470]
Auto increment can not be set to false when creating primary key from table args.

It would be cool if we could configure autoincriment flag from table args.

There seems to be some workarounds with setting identity insert to true during the session which would allow primary key configuration to remain in table args but the sqlalchemy docs mention it is not performant to do that.

**Comment by zzzeek** [comment]
hi there- 
I'm not sure what you're referring towards.  "Autoincrement" is a feature of a Column, not of a primary key constraint.   you can set autoincrement True/False as needed, demo:

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import PrimaryKeyConstraint
from sqlalchemy import Table

m = MetaData()

t1 = Table(
    "t1",
    m,
    Column("id", Integer, autoincrement=False),
    PrimaryKeyConstraint("id"),
)


t2 = Table("t2", m, Column("id", Integer), PrimaryKeyConstraint("id"))

e = create_engine("mysql://scott:tiger@localhost/test", echo=True)
m.drop_all(e)
m.create_all(e)

```
i've chosen MySQL where we can see autoincrement false on t1, true on t2:

```sql
CREATE TABLE t1 (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
)


2021-05-11 19:38:25,406 INFO sqlalchemy.engine.Engine [no key 0.00028s] ()
2021-05-11 19:38:25,455 INFO sqlalchemy.engine.Engine 
CREATE TABLE t2 (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	PRIMARY KEY (id)
)
```

**Comment by bfmcneill** [comment]
That makes sense it is not part of the constrain logic.  Thanks.
