### ISSUE TITLE
literal_column causes syntax error in condition statement

### ISSUE THREAD

**Issue by gergo-nyiro-oi** [sqlalchemy/sqlalchemy#6488]
**Describe the bug**

We have a syntax error with the new (1.4.15) sqlalchemy when we use `literal_column` in a condition.

**To Reproduce**

The following snippet shows the generated sql statement where the selection will get an alias prefix but the alias (anon_1) is not defined anywhere.

```py
from sqlalchemy import select, literal_column, text

selection = select([literal_column("column_name")])
query = selection.subquery()
condition = query.c.column_name == text("test")

print(condition)
```

**Error**
```
anon_1.column_name = test
```

**Versions.**
 - OS: linux Ubuntu focal
 - Python: 3.8.5
 - SQLAlchemy: 1.4.15
 - Database: -
 - DBAPI: -

**Additional context**

When the `subquery` is called with name parameter, then the prefix will get the value of the name parameter but no alias is defined in this case either.

**Have a nice day!**

Any advice how to avoid this situation is welcome.

Thanks for your help in advance,
Gergo

**Comment by CaselIT** [comment]
Hi,

This seems to be correct. If you print `print(select(query))` it will output
```
SELECT anon_1.column_name
FROM (SELECT column_name) AS anon_1
```
So it follows that one of its column would be `anon_1.column_name`.

I'm not sure what you expected it to print.

**Comment by zzzeek** [comment]
just to note this is not anything unique to 1.4, 1.3 will do the same thing for a subquery.

**Comment by gergo-nyiro-oi** [comment]
Thanks for the fast reply. Your hint helped me to find a missing select call, where we used the problematic subquery in a join statement.
