### ISSUE TITLE
sqlalchemy.testing.suite.test_types._LiteralRoundTripFixture breaks when type can't be determined from values.

### ISSUE THREAD

**Issue by jimfulton** [sqlalchemy/sqlalchemy#6496]
`sqlalchemy.testing.suite.test_types._LiteralRoundTripFixture` generates literals by calling `literal` without passing a type:

https://github.com/sqlalchemy/sqlalchemy/blob/c379f80b4e6fb1b65983958116bac202c91a210a/lib/sqlalchemy/testing/suite/test_types.py#L66

This breaks for the BigQuery `TIMESTAMP` type which uses `datetime` values for Python, but has distinct literals.

The simple fix is to pass the `type_` argument passed into `run` to `literal`.

I will submit a PR.

**Comment by sqla-tester** [comment]
**Jim Fulton** has proposed a fix for this issue in the **master** branch:

**Use type_ when creating literals in _LiteralRoundTripFixture** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2828

**Comment by zzzeek** [comment]
just some notes on the possibly not consistent behavior here; literal() is coerced into the specific datatype of the left side when it has no type at all, however, it performs its own type coercion up front which blocks the more specific left-hand-side type from taking effect.  if literal() had some way to differentiate "the user specified this exact type" vs. "the user specified no type and we guessed, please upgrade us to the left side when applicable", that would improve on this.   nonetheless fixing this behavior is out of the scope of this test change for now.

demo

```python
from sqlalchemy import column, Integer, literal, BigInteger

expr = column("q", BigInteger) == literal(None)

# prints BIGINT, so given literal() is coerced.  code to do this is
# lib/sqlalchemy/sql/coercions.py -> L493
print(expr.right.type)


expr = column("q", BigInteger) == literal(5)

# prints INTEGER; literal that has a type is not coerced
print(expr.right.type)


expr = column("q", BigInteger) == 5

# prints BIGINT, freestanding right side fully coerced.
# code here starts at
# lib/sqlalchemy/sql/coercions.py -> L488 then into BindParam
# lib/sqlalchemy/sql/elements.py -> L1452
print(expr.right.type)
```
