### ISSUE TITLE
Can't pass column name as string to Index

### ISSUE THREAD

**Issue by mdczaplicki** [sqlalchemy/sqlalchemy#6500]
**GUIDELINES FOR REPORTING BUGS**

If you are new to SQLAlchemy bug reports, please review our many examples
of [well written bug reports](https://github.com/sqlalchemy/sqlalchemy/issues?q=is%3Aissue+label%3A%22great+mcve%22).   Each of these reports include the following features:

1. a **succinct description of the problem** - typically a line or two at most
2. **succinct, dependency-free code which reproduces the problem**, otherwise known as a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
3. **complete stack traces for all errors - please avoid screenshots, use formatted text inside issues**
4. Other things as applicable:   **SQL log output**, **database backend and DBAPI driver**,
   **operating system**, **comparative performance timings** for performance issues.

**Describe the bug**
`mypy` is complaining about passing column name as string to `Index` contructor.

**To Reproduce**

```py
test_table = Table(
    "test_table",
    metadata,
    Column("i", UUID(as_uuid=True), nullable=False, primary_key=True),
    Column("x", UUID(as_uuid=True), index=True),
    Column("y", UUID(as_uuid=True), index=True),
    Index(
        "ix_xy_unique",
        "x",
        "y",
        unique=True,
    ),
)
```

**Error**

```
"Index" has incompatible type "str"; expected "ColumnClause[Any]"
```

**Versions.**
 - OS: Linux Mint 19.3 Cinnamon
 - Python: 3.7.10
 - SQLAlchemy: 1.4.15
 - Database: PostgreSQL
 - DBAPI: asyncpg

**Additional context**
I've tried extracting `Index` from the `Table` constructor & use `test_table.c.x` & `test_table.c.y`, but it didn't help much:

```
"Index" has incompatible type "ColumnElement[Any]"; expected "ColumnClause[Any]"
```

Also I've tried using `text("x")` & `text("y")`, but then got:

```
"Index" has incompatible type "ColumnElement[Any]"; expected "ColumnClause[Any]"
```
**Have a nice day!**

**Comment by MaicoTimmerman** [comment]
Hi, this was first reported in https://github.com/sqlalchemy/sqlalchemy2-stubs/issues/82 and should be fixed with https://github.com/sqlalchemy/sqlalchemy2-stubs/pull/108 in the near future.
