### ISSUE TITLE
use_unicode=False causes key errors in get_foreign_keys() on mysql8/python3

### ISSUE THREAD

**Issue by dieselmachine** [sqlalchemy/sqlalchemy#6516]
If i create an engine with use_unicode=False in the connect_args, and then inspect the engine, calling get_schema_names returns a list of bytes, rather than a list of str. If use_unicode=True, strings are returned.

When get_foreign_keys is called, eventually it hits _correct_for_mysql_bugs_88718_96365, and builds a mapping with this:
```for schema, tname, cname in correct_for_wrong_fk_case:```

if use_unicode is False, the keys in that mapping are tuples of bytes such as (b'tmp', b'items').

if use_unicode is True, the keys are tuples of str, such as ('tmp', 'items')

a lookup is then done using values from the foreign key, and those values are text, regardless of the setting use_unicode. The lookup for ('tmp', 'items') fails because the key is (b'tmp', b'items'), and causes a KeyError on this line:

```fkey["referred_table"] = rec["TABLENAME"]```

**Versions.**
 - OS: Debian 10
 - Python: 3.9.2
 - SQLAlchemy: 1.4.15
 - Database: mysql 8.0.24
 - DBAPI: mysqlclient 2.0.3

[testdb.txt](https://github.com/sqlalchemy/sqlalchemy/files/6518790/testdb.txt)

**Comment by zzzeek** [comment]
use_unicode=False is not supported in Python 3 and will likely be removed in SQLAlchemy 2.

**Comment by zzzeek** [comment]
also use_unicode is a function of the pymysql driver and there's no reason to set this to false in python 3.
