### ISSUE TITLE
Automap extension uses the deprecated `ext.declarative`

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6529]
**Describe the bug**
Automap extension uses the deprecated ext.declarative

**To Reproduce**
Provide your [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example
here.

```py
# Insert code here
import os
os.environ['SQLALCHEMY_WARN_20'] = '1'
from sqlalchemy.ext.automap import automap_base
Base = automap_base()
```

**Error**
Provide the complete text of any errors received **including the complete
stack trace**.   If the message is a warning, run your program with the
``-Werror`` flag:   ``python -Werror myprogram.py``

```
MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 1.4) (Background on SQLAlchemy 2.0 at: http://sqlalche.me/e/b8d9)
Base = automap_base()
```

**Versions.**
 - OS: -
 - Python: -
 - SQLAlchemy: 1.4.x
 - Database: -
 - DBAPI: -

**Additional context**

Reported by @S-Stephen on gitter

**Have a nice day!**

**Comment by sqla-tester** [comment]
**jason3gb** has proposed a fix for this issue in the **master** branch:

**Fixes: #6529** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2841
