### ISSUE TITLE
Support cyfunction as validators

### ISSUE THREAD

**Issue by mstypinski** [sqlalchemy/sqlalchemy#6538]
**Describe the bug**
It is not possible to create a validator with the type of cyfunction.

**To Reproduce**
Create a model in SQLAlchemy with validator and cythonize the code.

**Versions.**
 - OS: alpine 3.13 docker
 - Python: 3.6
 - SQLAlchemy: 1.2.11
 - Cython 0.29.23

**Additional context**
Below is the check which is a part of `orm/mapper.py:1265` file
![image](https://user-images.githubusercontent.com/25174931/119652441-66f06f80-be26-11eb-85cd-933a2594f22d.png)

**Have a nice day!**

**Comment by zzzeek** [comment]
@CaselIT did we have any proposal here that can be linked?

**Comment by sqla-tester** [comment]
**Miłosz Stypiński** has proposed a fix for this issue in the **master** branch:

**Be less fiscal regarding validators functions** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2894
