### ISSUE TITLE
implement get unique constraints for MSSQL dialect

### ISSUE THREAD

**Issue by bfmcneill** [sqlalchemy/sqlalchemy#6552]
I tried to inspect the unique constraints for MSSQL dialect but a `NotImplementedError` was raised.

**Comment by zzzeek** [comment]
cc @gordthompson  does SQL Server have a unique constraint concept separate from unique indexes?

**Comment by zzzeek** [comment]
per https://www.mssqltips.com/sqlservertip/4270/difference-between-sql-server-unique-indexes-and-unique-constraints/ it looks like these are identitical and that a unique index is implicit.  you should be able to use get_indexes() and look for those that have unique=True.

**Comment by bfmcneill** [comment]
yes and thank you.
