### ISSUE TITLE
New exception when upgrading from SQLAlchemy 1.4.15 to 1.4.16

### ISSUE THREAD

**Issue by afetek** [sqlalchemy/sqlalchemy#6558]
**Describe the bug**

**To Reproduce**
Provide your [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example
here.

```py
# Line of code that works in 1.4.15 but breaks in 1.4.16
query = query.outerjoin(object_to_join)
```
# I put the following code and fixed the issue
```
from sqlalchemy.sql.coercions import JoinTargetImpl

# FIXME: SQLAlchemy issue in 1.4.16
if hasattr(JoinTargetImpl, '_skip_clauseelement_for_target_match'):
    JoinTargetImpl._skip_clauseelement_for_target_match = False
.
.
.
query = query.outerjoin(object_to_join)

```
# Note: _skip_clauseelement_for_target_match  in sql/coercions.py is new in 1.4.16:
```
class JoinTargetImpl(RoleImpl):
    __slots__ = ()

    _skip_clauseelement_for_target_match = True

```

**Error**
Provide the complete text of any errors received **including the complete
stack trace**.   If the message is a warning, run your program with the
``-Werror`` flag:   ``python -Werror myprogram.py``

```
# Copy complete stack trace and error message here, including SQL log output
if applicable.
(base) [05/28 23:51:29] pbsdev@pdw-ni:/nisrv/ni 120% sbank -u xxxx --debug 100
** DEBUG> Creating DB Object: <class 'ni.lib.models.User'>

Effective Monday, August 3, 2020, ALCF compute allocation units have changed from core-hours to node-hours

Unexpected Error: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Suballocation.allocation has an attribute '_propagate_attrs'

Traceback (most recent call last):
  File "/nisrv/anaconda/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 326, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute '_propagate_attrs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nisrv/anaconda/lib/python3.8/site-packages/ni/lib/client_utils.py", line 2151, in decorated_func
    retval = func(*args, **kwargs)
  File "/nisrv/anaconda/lib/python3.8/site-packages/ni/lib/client_utils.py", line 2136, in decorated_func
    retval = func(*args, **kwargs)
  File "/nisrv/anaconda/lib/python3.8/site-packages/ni/clients/list_allocations.py", line 62, in run
    allocations, fields = client_utils.resource_type_allocations(parser, kwargs)
  File "/nisrv/anaconda/lib/python3.8/site-packages/ni/lib/client_utils.py", line 2579, in resource_type_allocations
    for a in api.list_allocations(**kwargs):
  File "/nisrv/anaconda/lib/python3.8/site-packages/ni/lib/api.py", line 1045, in list_allocations
    return views.list_allocations(**kwargs)
  File "/nisrv/anaconda/lib/python3.8/site-packages/ni/lib/models.py", line 3409, in decorated_func
    value = service_func(*args, **kwargs)
  File "/nisrv/anaconda/lib/python3.8/site-packages/ni/lib/views.py", line 797, in list_allocations
    return internal.list_allocations(**kwargs)
  File "/nisrv/anaconda/lib/python3.8/site-packages/ni/lib/models.py", line 5200, in list_allocations
    suballocations_q = self.get_query(
  File "/nisrv/anaconda/lib/python3.8/site-packages/ni/lib/models.py", line 3735, in get_query
    query, joined = self.join_list(outerjoins, query, joined, outer=True)
  File "/nisrv/anaconda/lib/python3.8/site-packages/ni/lib/models.py", line 3536, in join_list
    query = query.outerjoin(object_to_join)
  File "/nisrv/anaconda/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2395, in outerjoin
    return self.join(target, *props, **kwargs)
  File "<string>", line 2, in join
  File "/nisrv/anaconda/lib/python3.8/site-packages/sqlalchemy/sql/base.py", line 104, in _generative
    x = fn(self, *args, **kw)
  File "<string>", line 2, in join
  File "/nisrv/anaconda/lib/python3.8/site-packages/sqlalchemy/orm/base.py", line 224, in generate
    fn(self, *args[1:], **kw)
  File "/nisrv/anaconda/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2349, in join
    joins_to_add = tuple(
  File "/nisrv/anaconda/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2351, in <genexpr>
    coercions.expect(
  File "/nisrv/anaconda/lib/python3.8/site-packages/sqlalchemy/sql/coercions.py", line 197, in expect
    and resolved._propagate_attrs
  File "/nisrv/anaconda/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 328, in __getattr__
    util.raise_(
  File "/nisrv/anaconda/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Suballocation.allocation has an attribute '_propagate_attrs'

```

**Versions.**
 - OS: Centos 7
 - Python: 3.8.10
 - SQLAlchemy: 1.4.16
 - Database: Db2
 - DBAPI: 
ibm-db        3.0.4
ibm-db-sa   0.3.6

**Additional context**

**Have a nice day!**

**Comment by CaselIT** [comment]
Hi, thanks for the report.

What is the `query` variable in your example?

**Comment by afetek** [comment]
Thanks for your quick response.  
The query works with other similar objects.  
Let me know if this helps:

```
I am using Table and mapper:
```
        su_table = Table(
            SU_TABLE_NAME, self.metadata,
            Column(SU_ID                   , Integer   , primary_key=True, autoincrement=True),
            Column(AL_ID                   , Integer   , ForeignKey(AL_FK), nullable=False),
            Column('admin_name'            , String(64), nullable=True),
            Column('is_primary'            , Integer   , nullable=False),
            Column('start_timestamp'       , DateTime  , nullable=False),
            Column('end_timestamp'         , DateTime  , nullable=False),
            Column('is_deleted'            , Integer   , nullable=False),
            Column('last_updated_timestamp', DateTime  , nullable=False),
            Column('suballocation_name'    , String(32), nullable=True),
            Column('is_restricted'         , Integer   , nullable=False),
            Column('is_disabled'           , Integer   , nullable=False),
            mysql_engine=self.CONFIG['mysql_engine'],
            schema=self.CONFIG['db_schema'])
...
        mapper(Suballocation, su_table, properties={
            'pk'                    : su_table.c.suballocation_id,
            'allocation'            : relation(Allocation),
            'admin_name'            : su_table.c.admin_name,
            'is_primary'            : su_table.c.is_primary,
            'start_timestamp'       : su_table.c.start_timestamp,
            'end_timestamp'         : su_table.c.end_timestamp,
            'is_deleted'            : su_table.c.is_deleted,
            'last_updated_timestamp': su_table.c.last_updated_timestamp,
            'suballocation_name'    : su_table.c.suballocation_name,
            'is_restricted'         : su_table.c.is_restricted,
            'is_disabled'           : su_table.c.is_disabled,
        })
```
# Instrumented output
```
TYPE of object_to_join: <class 'sqlalchemy.orm.attributes.InstrumentedAttribute'>
object_to_join: Suballocation.allocation
attributes of object_to_join: ['__add__', '__and__', '__class__', '__class_getitem__', '__clause_element__', '__contains__', '__delattr__', '__delete__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__orig_bases__', '__parameters__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__rshift__', '__rsub__', '__rtruediv__', '__set__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__visit_name__', '__weakref__', '_adapt_to_entity', '_annotations', '_assert_no_memoizations', '_bulk_update_tuples', '_cache_key_traversal', '_clone', '_copy_internals', '_entity_namespace', '_extra_criteria', '_from_objects', '_gen_cache_key', '_generate_cache_attrs', '_generate_cache_key', '_generate_cache_key_for_object', '_impl_uses_objects', '_is_internal_proxy', '_is_protocol', '_memoized_keys', '_of_type', '_parententity', '_parentmapper', '_post_inspect', '_reset_memoizations', '_role_name', '_set_memoized_attribute', '_supports_population', 'adapt_to_entity', 'adapter', 'all_', 'allows_lambda', 'and_', 'any', 'any_', 'any_op', 'asc', 'between', 'bool_op', 'class_', 'collate', 'comparator', 'concat', 'contains', 'desc', 'dispatch', 'distinct', 'endswith', 'expression', 'extension_type', 'get_history', 'has', 'has_op', 'hasparent', 'ilike', 'impl', 'in_', 'info', 'inherit_cache', 'is_', 'is_aliased_class', 'is_attribute', 'is_bundle', 'is_clause_element', 'is_distinct_from', 'is_instance', 'is_mapper', 'is_not', 'is_not_distinct_from', 'is_property', 'is_selectable', 'isnot', 'isnot_distinct_from', 'key', 'label', 'like', 'match', 'memoized_attribute', 'memoized_instancemethod', 'not_ilike', 'not_in', 'not_like', 'notilike', 'notin_', 'notlike', 'nulls_first', 'nulls_last', 'nullsfirst', 'nullslast', 'of_type', 'of_type_op', 'op', 'operate', 'params', 'parent', 'prop', 'property', 'regexp_match', 'regexp_replace', 'reverse_operate', 'startswith', 'timetuple', 'unique_params', 'uses_inspection']
```

**Comment by zzzeek** [comment]
OK, the code here doesn't say much but I basically took a guess based on the stack trace and came up with the MCVE:

```python
from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)


# doesn't matter
# configure_mappers()


stmt = select(A.__table__)
stmt = stmt.join(A.bs)
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure propagate_attrs available on PropComparator** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2849

**Comment by afetek** [comment]
Hi Mike,

Thank you for the proposed fix.  Looking forward to get it.

I have lot of legacy code using SQLAlchemy and trying to keep up to date with the releases.

Given my lack of knowledge on SQLAlchemy I was having issues reproducing this with a small snippet of code.    
My small snippets of code were not failing.

I did trace your code and put the following fix in my code:

```
# FIXME: SQLAlchemy issue in 1.4.16
if hasattr(JoinTargetImpl, '_skip_clauseelement_for_target_match'):
    JoinTargetImpl._skip_clauseelement_for_target_match = False
```

Once there is new release fixing this I will remove my temporary fix.

Again, thank you for the quick response.

**Comment by zzzeek** [comment]
no worries this was small and clear to locate from the change just made + your stack trace (that's why we ask for it!)
