### ISSUE TITLE
Re-enable test test_no_attach_to_event_loop

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6575]
Re-enable test disabled in cf8c76b9fcfcd1e79da4b089e7a86d6300d737e1

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Propagate asyncio flag from the dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2856
