### ISSUE TITLE
confusing docs around one-to-one relationships

### ISSUE THREAD

**Issue by danielknell** [sqlalchemy/sqlalchemy#6580]
**Describe the bug**

very minor docs only nitpick, I was trying to remind myself what `uselist=False` was called, when i noticed that the docs on one-to-one relationships suddenly switch to talking about many-to-one relationships then 180 back to one-to-one... this was a bit awkward to read.

Would the docs be improved if the whole many-to-one code example was removed? its identical to the second example in the many-to-one section just above.

**Versions.**
 - SQLAlchemy: 1.4

**Additional context**

https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#one-to-one

**Comment by zzzeek** [comment]
do you mean this text:  "To convert one-to-many into one-to-one: <example> Or for many-to-one: <example>" ?  That's the only place I can see "many-to-one" being mentioned.   The second phrase I guess needs to read "Or, to convert a many-to-one into one-to-one" so you know what it's talking about.

**Comment by zzzeek** [comment]
> do you mean this text: "To convert one-to-many into one-to-one: `<example>` Or for many-to-one:  `<example>`" ? That's the only place I can see "many-to-one" being mentioned. The second phrase I guess needs to read "Or, to convert a many-to-one into one-to-one" so you know what it's talking about.

**Comment by danielknell** [comment]
It was the former but now I am seeing I misread the docs even worse than I thought… maybe it’s because I was looking to add a fresh one-to-one relationship rather than to convert an existing one…

I read it as I can make a one-to-one  as first example, then many-to-one with second, and relevant bit of the second example was scrolled outside the box to the right)
