### ISSUE TITLE
pysqlcipher dialect fails in SQLAlchemy >= 1.4

### ISSUE THREAD

**Issue by blackm0re** [sqlalchemy/sqlalchemy#6586]
When using the pysqlcipher with the following connection string:
'sqlite+pysqlcipher://:{passwd}@/{filename}?cipher=aes-256-cfb&kdf_iter=64000'
, it fails with:

engine = create_engine(
  File "<string>", line 2, in create_engine
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 653, in create_engine
    do_on_connect = dialect.on_connect_url(url)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/pysqlcipher.py", line 134, in on_connect_url
    passphrase = url.password or ""
AttributeError: 'str' object has no attribute 'password'

The reason is that on_connect_url "expects" url to be an URL object while it receives 'str' instead.
A fix will be submitted and linked to this issue shortly.

**Comment by zzzeek** [comment]
continuation of #5848, the test suite is sending only a URL object in so the on_connect_url() hook was never tested correctly.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Pass URL object, not the string, to on_connect_url** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2859

**Comment by zzzeek** [comment]
well this certainly gives us a sense of how many people use pysqlcipher, that nobody noticed this for weeks.  thanks for reporting!  thanks also for your PR but the fix is different from what you have there, I've pushed up a review with tests.
