### ISSUE TITLE
pysqlalchemy dialect does not send the pragma params specified in the connection URL

### ISSUE THREAD

**Issue by blackm0re** [sqlalchemy/sqlalchemy#6589]
In SQLAlchemy 1.3.(24) the pragma params specified in the connection URL are not sent to the backend, hence the default values are used no matter what params are specified in the URL.

example URL: sqlite+pysqlcipher://:{passwd}@/{file}?cipher=aes-256-cfb&kdf_iter=64000

In addition to not respecting the user's security preferences, the fact that this problem does not exist in SQLAlchemy >= 1.4,
confuses the user when migrating SQLAlchemy 1.3 -> SQLAlchemy 1.4.

A small bugfix (PR) will be linked to this issue.

**Comment by zzzeek** [comment]
while this is a bug, im not sure if changing it in 1.3 is going to solve anything, because it creates a backwards compatible change in a very late-stage 1.3 release.   typically when going from 1.3->1.4 is where people expect a more major behavioral change.   what's the specific scenario where putting out a release 1.3.25 helps here, for the user that's been on 1.3.x for a long time?  for the user that hasn't been on 1.3.x, they'd start with 1.4.x?

**Comment by zzzeek** [comment]
that is, "confuses the user when going from 1.3 to 1.4", wouldnt this confuse the user even moreso when going from 1.3.24 -> 1.3.25?  it's much less appropriate for surprises there.    i think it's better to leave this behavior in place wtihin 1.3.x.

**Comment by blackm0re** [comment]
They way I see it:
Doing nothing:
A user initiated a new database sqlite+pysqlcipher database in <= 1.3.24 and stored some data in it. The user upgrades to 1.3.25 and everything is "working" as before, although the expected security settings are not set. The user upgrades to 1.4 and 1.4 is giving "file is not a database" error when of course using the same params and password. If the bug report is not public (searchable) most users will simply fall back and "blame" 1.4
A user initiated a new database in 1.3.25 -> same problem.

Fixing in 1.3.25:
A user initiated a new database sqlite+pysqlcipher database in <= 1.3.24 and stored some data in it. The user upgrades to 1.3.25 and is now unable to unlock his/her database. The user assumes that some bug has been introduced, searches and finds this particular bug report / changelog / commit message. The same goes for 1.4. A user initiating his/her database >=1.3.25 on the other hand will have no trouble migrating to 1.4. In addition no security promises will be broken.

In any of the cases the DB settings can be changed manually as described bellow and the user should be made aware of that:
https://www.zetetic.net/sqlcipher/sqlcipher-api/

Although I see the concern about introducing changes in a manor release, I believe that this is the lesser evil. Continuing the buggy behavior for as long as 1.3. lives creates more problems than it solves.

**Comment by zzzeek** [comment]
> They way I see it:
> Doing nothing:
> A user initiated a new database sqlite+pysqlcipher database in <= 1.3.24 and stored some data in it. The user upgrades to 1.3.25 and everything is "working" as before, although the expected security settings are not set. The user upgrades to 1.4 and 1.4 is giving "file is not a database" error when of course using the same params and password. If the bug report is not public (searchable) most users will simply fall back and "blame" 1.4
> A user initiated a new database in 1.3.25 -> same problem.
> 
> Fixing in 1.3.25:
> A user initiated a new database sqlite+pysqlcipher database in <= 1.3.24 and stored some data in it. The user upgrades to 1.3.25 and is now unable to unlock his/her database. The user assumes that some bug has been introduced, searches and finds this particular bug report / changelog / commit message. The same goes for 1.4. A user initiating his/her database >=1.3.25 on the other hand will have no trouble migrating to 1.4. In addition no security promises will be broken.

I think the "user initiating a new pysqlcipher DB in 1.3.25" is the least likely case.   1.3.x is now legacy, a new user starting out should be on 1.4.   

> 
> In any of the cases the DB settings can be changed manually as described bellow and the user should be made aware of that:
> https://www.zetetic.net/sqlcipher/sqlcipher-api/
> 
> Although I see the concern about introducing changes in a manor release, I believe that this is the lesser evil. Continuing the buggy behavior for as long as 1.3. lives creates more problems than it solves.

it's likely that nearly nobody is using pysqlcipher very much at all considering how broken the dialect has been without any reports.  I appreciate that you got hit by this issue but i think major backwards incompatible changes need to be kept out of late 1.3.x releases.


cc @CaselIT  what do you think?

**Comment by CaselIT** [comment]
Maybe just a note / dragon in the dialect page for 1.3 indicating this limitation and recommanding changing the option manually is best option.
The documentation for 1.4 may also note something like "prior to 1.4 the configuration options placed in the url string were ignored"

**Comment by blackm0re** [comment]
> > They way I see it:
> > Doing nothing:
> > A user initiated a new database sqlite+pysqlcipher database in <= 1.3.24 and stored some data in it. The user upgrades to 1.3.25 and everything is "working" as before, although the expected security settings are not set. The user upgrades to 1.4 and 1.4 is giving "file is not a database" error when of course using the same params and password. If the bug report is not public (searchable) most users will simply fall back and "blame" 1.4
> > A user initiated a new database in 1.3.25 -> same problem.
> > Fixing in 1.3.25:
> > A user initiated a new database sqlite+pysqlcipher database in <= 1.3.24 and stored some data in it. The user upgrades to 1.3.25 and is now unable to unlock his/her database. The user assumes that some bug has been introduced, searches and finds this particular bug report / changelog / commit message. The same goes for 1.4. A user initiating his/her database >=1.3.25 on the other hand will have no trouble migrating to 1.4. In addition no security promises will be broken.
> 
> I think the "user initiating a new pysqlcipher DB in 1.3.25" is the least likely case. 1.3.x is now legacy, a new user starting out should be on 1.4.
> 
> > In any of the cases the DB settings can be changed manually as described bellow and the user should be made aware of that:
> > https://www.zetetic.net/sqlcipher/sqlcipher-api/
> > Although I see the concern about introducing changes in a manor release, I believe that this is the lesser evil. Continuing the buggy behavior for as long as 1.3. lives creates more problems than it solves.
> 
> it's likely that nearly nobody is using pysqlcipher very much at all considering how broken the dialect has been without any reports. I appreciate that you got hit by this issue but i think major backwards incompatible changes need to be kept out of late 1.3.x releases.
It is hard for me to talk about 'backwards incompatible changes' when it comes to bugs, especially security related ones (although the default values are quite secure).
I am not familiar with the infrastructure of your project, but I hope that this issue will be made searchable / easy to find.
> 
> cc @CaselIT what do you think?

Regards

**Comment by blackm0re** [comment]
It is hard for me to talk about 'backwards incompatible changes' when it comes to bugs, especially security related ones (although the default values are quite secure).

Good suggestion, @CaselIT

Best regards

**Comment by CaselIT** [comment]
I actually missed that passing encryption-related pragmas to the query string was actually documented in 1.3
I though it was not.

That's actually a wired spot to be in, since fixing this issue may make the db unreadable for folks that update to 1.3.25.
I'll go for removing that from the documentation, but I'm no longer convinced that it's the best option

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add note regarding encryption-related pragmas** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2862

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_3** branch:

**Add note regarding encryption-related pragmas** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2863
