### ISSUE TITLE
Error while using conn.execution_options and pool_pre_ping=True

### ISSUE THREAD

**Issue by jiffyclub** [sqlalchemy/sqlalchemy#6621]
**Describe the bug**

I cannot use` conn.execution_options(postgresql_readonly=True)` along with `pool_pre_ping=True` on `create_engine`. If I do, I get a `psycopg2.ProgrammingError: set_session cannot be used inside a transaction` error the second time I try to
execute a query. Not sure if this is expected, but it's not mentioned in [these docs](https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#setting-read-only-deferrable).

**To Reproduce**
Provide your [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example
here.

```py
import sqlalchemy as sa

# engine with defaults
engine1 = sa.create_engine('postgresql://postgres:pw@localhost')

# prints 1
with engine1.connect() as conn:
    conn.execution_options(postgresql_readonly=True)
    print(conn.execute(sa.text('SELECT 1')).scalar())

# prints 2
with engine1.connect() as conn:
    conn.execution_options(postgresql_readonly=True)
    print(conn.execute(sa.text('SELECT 2')).scalar())

# engine with pool_pre_ping=True
engine2 = sa.create_engine('postgresql://postgres:pw@localhost', pool_pre_ping=True)

# prints 3
with engine2.connect() as conn:
    conn.execution_options(postgresql_readonly=True)
    print(conn.execute(sa.text('SELECT 3')).scalar())

# psycopg2.ProgrammingError: set_session cannot be used inside a transaction
with engine2.connect() as conn:
    conn.execution_options(postgresql_readonly=True)
    print(conn.execute(sa.text('SELECT 4')).scalar())
```

**Error**
Provide the complete text of any errors received **including the complete
stack trace**.   If the message is a warning, run your program with the
``-Werror`` flag:   ``python -Werror myprogram.py``

```
Traceback (most recent call last):
  File "/Users/matt/test_script.py", line 23, in <module>
    conn.execution_options(postgresql_readonly=True)
  File "/Users/matt/miniconda3/envs/populus-env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 398, in execution_options
    self.dialect.set_connection_execution_options(c, opt)
  File "/Users/matt/miniconda3/envs/populus-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 616, in set_connection_execution_options
    self._set_connection_characteristics(connection, characteristics)
  File "/Users/matt/miniconda3/envs/populus-env/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 651, in _set_connection_characteristics
    characteristic.set_characteristic(self, dbapi_connection, value)
  File "/Users/matt/miniconda3/envs/populus-env/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3050, in set_characteristic
    dialect.set_readonly(dbapi_conn, value)
  File "/Users/matt/miniconda3/envs/populus-env/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 836, in set_readonly
    connection.readonly = value
psycopg2.ProgrammingError: set_session cannot be used inside a transaction
```

**Versions.**
 - OS: Mac OS X 10.15.7
 - Python: 3.9.2
 - SQLAlchemy: 1.4.18
 - Database: Postgres 13.3
 - DBAPI: psycopg2-binary 2.8.6

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
I don't have a workaround for this other than the [manual ping recipe](https://docs.sqlalchemy.org/en/14/core/pooling.html#custom-legacy-pessimistic-ping) however please test this patch to ensure this will solve the issue:

```diff
diff --git a/lib/sqlalchemy/engine/default.py b/lib/sqlalchemy/engine/default.py
index 7b3fa091fd..ec765b80c6 100644
--- a/lib/sqlalchemy/engine/default.py
+++ b/lib/sqlalchemy/engine/default.py
@@ -684,6 +684,7 @@ class DefaultDialect(interfaces.Dialect):
                 cursor.execute(self._dialect_specific_select_one)
             finally:
                 cursor.close()
+                dbapi_connection.rollback()
         except self.dbapi.Error as err:
             if self.is_disconnect(err, dbapi_connection, cursor):
                 return False
```

**Comment by zzzeek** [comment]
very oddly, the psycopg2 driver does not seem to raise this error in all cases, there seems to be some timing related issue going on.

I will make this fix more specific to psycopg2 by setting the "autocommit" flag for the ping, so that we are avoiding using a transaction at all for this operation.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**set autocommit for psycopg2 pre-ping** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2868

**Comment by jiffyclub** [comment]
Confirming that the change to `sqlalchemy/dialects/postgresql/psycopg2.py` in https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2868 fixes this error for me. Thank you!
