### ISSUE TITLE
orm imperative mapping w/ polymorphic gets NoneType error initializing identity

### ISSUE THREAD

**Issue by kapilt** [sqlalchemy/sqlalchemy#6628]
1. We're running into an issue upon upgrade from 1.3 to 1.4 where our orm classes error out during initialization when doing session.add(), oddly if we do a session.get() first everything works fine.

2. I've struggled to make a standalone reproducible test case, this gist is representative of the usage
https://gist.github.com/kapilt/c28e1c46a28212c157ef7f43f778d6f6

if there's additional information i can provide happy to do so.

3. traceback / pytest styled

```python
        resource = {
            "QueueUrl": "https://sqs.us-east-1.amazonaws.com/1122334455566/config-changes",
            "QueueArn": "arn:aws:sqs:us-east-1:112233445566:config-changes",

        }
        resource["_rid"] = resource["QueueArn"]
        eni_peer_class = peer_factory.make()
        engine = rdb.create_engine(f"sqlite:///{tmp_path}/db")
        md.create_all(engine)
    
        session = Session()
        session.bind = engine
        serializer = Serializer(None, None, eni_peer_class, session)
>       serializer.add(resource)

tests/test_serializer.py:42: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
projects/example/serializer.py:20: in add
    peer = self.peer_class()
<string>:4: in __init__
    ???
../../.pyenv/versions/3.9.4/envs/example/lib/python3.9/site-packages/sqlalchemy/orm/state.py:439: in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
../../.pyenv/versions/3.9.4/envs/example/lib/python3.9/site-packages/sqlalchemy/event/attr.py:343: in __call__
    fn(*args, **kw)
../../.pyenv/versions/3.9.4/envs/example/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py:3571: in _event_on_init
    instrumenting_mapper._set_polymorphic_identity(state)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

state = <sqlalchemy.orm.state.InstanceState object at 0x7ffa066c41c0>

    def _set_polymorphic_identity(state):
        dict_ = state.dict
>       state.get_impl(polymorphic_key).set(
            state,
            dict_,
            state.manager.mapper.polymorphic_identity,
            None,
        )
E       AttributeError: 'NoneType' object has no attribute 'set'

../../.pyenv/versions/3.9.4/envs/example/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py:1589: AttributeError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>
> /home/kapilt/.pyenv/versions/3.9.4/envs/example/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py(1589)_set_polymorphic_identity()
-> state.get_impl(polymorphic_key).set(
```

What's super odd is simply doing a session.get() first resolves the issue.

**Versions.**
 - OS: ubuntu 20.04
 - Python: 3.9.4
 - SQLAlchemy: 1.4.17
 - Database: sqlite

**Comment by zzzeek** [comment]
hi Kapil -

this looks like mappers aren't getting configured, so in your "initialization" step, once all mapped classes have been imported, add this:

```python
from sqlalchemy.orm import configure_mappers   # import this somewhere

# ...

# init is ready...
configure_mappers()
```

that's likely what the issue is here.

**Comment by zzzeek** [comment]
seems like you have a mapper_registry in your gist, so you can do [this](https://docs.sqlalchemy.org/en/14/orm/mapping_api.html?highlight=registry#sqlalchemy.orm.registry.configure) too:

```python
mapper_registry.configure()
```

**Comment by kapilt** [comment]
thanks @zzzeek ! magic it worked, that was driving me nuts, thanks again :-)

**Comment by zzzeek** [comment]
just to clarify, you are not only moving from 1.3 to 1.4 straight you also are reorganizing your code in 1.4/2.0 style is this correct?  did the problem get introduced with the 2.0 style ?

**Comment by zzzeek** [comment]
in your example, this is where configure() gets called automatically:

```
    peer = klass(_rid="1", _id="1", _raw="xyz", _type="page")
```

so only if you are adding additional mappers after you've called "klass" above would this specific example have a problem.

we've had a few reports of configure not getting called so im trying to identify what's changed that is making this different.

**Comment by kapilt** [comment]
so we've got a bit of a mix of 1.3 / 1.4 & 2.0 style, on the upgrade, we basically updated the codebase to get tests passing, but i discovered running a few of them in isolation was leading to the aforementioned error. we're generating tables and mapper classes, so we would indeed be adding additional mappers in that context. i've updated our mapper generation to include registry.configure()

**Comment by kapilt** [comment]
hmm.. oddly simply doing mapper_registry.configure immediately after map imperatively  didn't do the trick. more oddly, that was effectively the last line in the function before returning the orm class,  But  doing mapper_configure after the function return did work..


```python

def make():
        # pseduo code, omitted.
        mapper_registry.map_imperatively(
            klass,
            self.transformer.rdb_tables[self.transformer.name],
            inherits=schema.Resource,
            inherit_condition=join_clause,
            polymorphic_on=schema.resource.c._type,
            polymorphic_identity=self.name,
        )
        # This Doesn't Work                                                                                                                                                                                                     
        # mapper_registry.configure()                                                                                                                                                                                                                                           

        return klass

def caller():
      peer = make()
        # This Works                                                                                                                                                                                                     
      mapper_registry.configure()  
```

**Comment by zzzeek** [comment]
do you have more than one mapper_registry in use, or usage of the older standalone mapper() funciton?   otherwise configure_mappers() is just finding that registry and configuring it.

**Comment by kapilt** [comment]
Thanks Mike, I audited through this app's sqlalchemy usage, indeed your right the root cause was the use of multiple registries (albeit not the legacy one in this case). consolidating app usage to a single registry removed the issue and the need for explicit registry configure.

**Comment by zzzeek** [comment]
thanks for checking into that.  this is all new stuff so it's good to know things are working as expected.
