### ISSUE TITLE
Any reason why legacy query syntax is not available at AsyncSession level?

### ISSUE THREAD

**Issue by ghevge** [sqlalchemy/sqlalchemy#6634]
Hi,

I was trying to use the sqlalchemy async support on an existing up and I've realized that the legacy query syntax, is not available at AsyncSession.

When I try it, I get the following error :

alerts = self.db.query(PlatformAlert).filter(PlatformAlert.is_active == True).all()
mix-middleware-server    |   File "<string>", line 2, in query
mix-middleware-server    | AttributeError: 'AsyncSession' object has no attribute 'query'

Any particular reason why the legacy query is not supported? 

I'm trying to convert an existing app to async  mode, but I don't feel like changing 500+ queries to align with the AsyncSession syntax.

Thanks.

**Comment by CaselIT** [comment]
Hi,

This was already discussed here https://github.com/sqlalchemy/sqlalchemy/discussions/6564
Please continue there
