### ISSUE TITLE
mysql Mixed queries I can't get lastrowid . (ver 1.4.18)

### ISSUE THREAD

**Issue by Honjoy** [sqlalchemy/sqlalchemy#6643]
I have try get lastrowid, always return 0, but in sqlalchemy version 1.3.24 and fastapi_sqlalchemy is return the correct value.

python code:
```py
from fastapi import FastAPI
from fastapi_async_sqlalchemy import SQLAlchemyMiddleware
from fastapi_async_sqlalchemy import db

app = FastAPI()
app.add_middleware(
    SQLAlchemyMiddleware, 
    db_url="mysql+aiomysql://user:user@192.168.88.200:5432/test1"
)


@app.get("/")
async def get_last_id():
    result = await db.session.execute("update test_table set pname='test name' where id=1; insert test_table2 (pname) values ('test name val')")
    lastid=result.lastrowid
    await db.session.commit()
    return lastid

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8002)
```

**Versions.**
 - OS: debian 10
 - Python: 3.7
 - SQLAlchemy: 1.4.18
 - Database: mysql 5.7
 - DBAPI: aiomysql 0.0.21

**Comment by CaselIT** [comment]
Hi,

The issue may be the different dbapi. What dbapi did you use on 1.3 instead of aiomysql?
Does that dbapi work the same in 1.4?

**Comment by Honjoy** [comment]
version1.3 use default mysqlclient 2.0.3

**Comment by CaselIT** [comment]
Can you try `mysqlclient ` with 1.4 and the same query?

**Comment by Honjoy** [comment]
maybe ok but mysqlclient can not use in async mode.
If I want to get lastrowid, I can't use the async mode？

**Comment by CaselIT** [comment]
> 
> 
> maybe is correct but mysqlclient can not use in async mode.
> If I want to get lastrowid, I can't use the async mode？

I'm trying to understand if the issue is of aiomysql or in sqlalchemy. If it's in the dbapi there isn't much we can do I fear.
I'm just asking if you can try running the same query in an script to see if it works using the `mysqlclient ` with 1.4

**Comment by Honjoy** [comment]
sorry,  I can't try it in this time, sqlalchemy 1.4 can not use fastapi-sqlalchemy, and I don't know how to use sqlalchemy core for this.
