### ISSUE TITLE
Support LONGBLOB on MariaDB backends when using PickleType

### ISSUE THREAD

**Issue by rlaunch** [sqlalchemy/sqlalchemy#6646]
**Describe the use case**
When using the PickleType data type, we have issues with MariaDB/MySQL database backends. Some pickled objects are too large for the standard BLOB type and cause the following exception:
`sqlalchemy.exc.DataError: (pymysql.err.DataError) (1406, "Data too long for column 'data' at row 1")`

Manually changing the column type in MariaDB to LONGBLOB fixes the issue.

Currently, we just make this change outside of SqlAlchemy, however, it would be great if either:

- There was a way to specify what underlying column type to use for PickleType
- LONGBLOB is always used for PickleType

**Databases / Backends / Drivers targeted**

- MariaDB
- MySQL

**Additional context**
The main goal of this is to be able to run commands such as db.create_all() etc without having to make changes outside of SQLALCHEMY or Alembic.

**Many thanks!**

**Comment by CaselIT** [comment]
hi,

I think you can just create your subtype of `PickleType` that uses longblob, since `PickleType` is already a type decorator, like so:
```py
class LongBlobPickleType(PickleType):
  impl = mysql.LONGBLOB
```

**Comment by CaselIT** [comment]
@zzzeek would adding a parameter in the `PickleType` constructor to specify the implementing column type make sense?

**Comment by zzzeek** [comment]
just call it "impl" , sure

**Comment by CaselIT** [comment]
contributions welcome then :)

**Comment by jason3gb** [comment]
@CaselIT Hi, after I looked into the issue, I found the TypeDecorator class requires a class attribute "impl" to instantiate. If we add a "impl" parameter to the constructor, is it ok to change the class-level attribute like this? Personally, I think is not very intuitive:
``` python
def __init__(
        self, protocol=pickle.HIGHEST_PROTOCOL, pickler=None, comparator=None, impl=None,
    ):
        ...
        self.__class__.impl = impl
        super(PickleType, self).__init__()
```

**Comment by CaselIT** [comment]
Shadowing the class attribute with an instance attribute does not work? I mean doing `self.impl = impl`

Using `self.__class__.impl = impl` would not work since we would change the global value when creating a new PickleType:
```py
assert PickleType.impl == LargeBinary
p1 = PickleType(impl=Integer)
assert PickleType.impl == Integer  # the class value has changed, not only on p1
```

**Comment by jason3gb** [comment]
> Shadowing the class attribute with an instance attribute does not work? I mean doing `self.impl = impl`
> 
> Using `self.__class__.impl = impl` would not work since it would change the global value when creating a new PickleType:
> 
> ```python
> assert PickleType.impl == LargeBinary
> p1 = PickleType(impl=Integer)
> assert PickleType.impl == Integer  # the class value has changed, not only on p1
> ```

Yeah, you're right, that doesn't work. I just saw these lines of codes in the constructor of TypeDecorator, which I think might overright the impl by using the self.__class__.impl. 

```python
    def __init__(self, *args, **kwargs):
        ...
        if not hasattr(self.__class__, "impl"):
            raise AssertionError(
                "TypeDecorator implementations "
                "require a class-level variable "
                "'impl' which refers to the class of "
                "type being decorated"
            )
        self.impl = to_instance(self.__class__.impl, *args, **kwargs)
```

So maybe I should set the impl instance attribute again after calling the superclass's constructor?

**Comment by sqla-tester** [comment]
**jason3gb** has proposed a fix for this issue in the **master** branch:

**Fixes: #6646** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2889

**Comment by sqla-tester** [comment]
**jason3gb** has proposed a fix for this issue in the **master** branch:

**Add "impl" parameter to PickleType** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2889

**Comment by rlaunch** [comment]
> hi,
> 
> I think you can just create your subtype of `PickleType` that uses longblob, since `PickleType` is already a type decorator, like so:
> 
> ```python
> class LongBlobPickleType(PickleType):
>   impl = mysql.LONGBLOB
> ```

Hi Federico,

Thanks for your response, i'll give this a go!

Best,
Ryan

**Comment by zzzeek** [comment]
heya quick Q are @rlaunch  and @jason3gb working together or did @jason3gb have this issue independently?

**Comment by rlaunch** [comment]
Hey @zzzeek, 
I've not done any work on this PR.
I just raised the feature request.

Best,
Ryan
