### ISSUE TITLE
Different default values for table prefixes

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy#6685]
**Describe the bug**
The handling of create table prefixes changed in alembic 1.6, I would like to check if this is intended. The original issue occurred in https://github.com/SAP/sqlalchemy-hana/issues/84

**SQLAlchemy**
https://github.com/sqlalchemy/sqlalchemy/blob/585aa7d7575dfb9a90a00bbd00c68da9e2cb31d7/lib/sqlalchemy/sql/schema.py#L662

Default is an empty list.

**Alembic**
https://github.com/sqlalchemy/alembic/blob/master/alembic/operations/ops.py#L960

This was changed in [this commit](https://github.com/sqlalchemy/alembic/commit/dd9c4d695c4463c872b25f59b6a8742bbc047150#diff-6c2637676a06e9c484a7468ba26d3f9a83e9e950d5335dfbe21cc948c3878756R954).

Default is now None.

It's of course easy to check of table._prefixes is empty, however I would like to check if his difference between alembic and SQLAlchemy is by purpose.

**To Reproduce**
Have a migration with a create table migration. In the dialect in visit_create_table access `create.element._prefixes`

**Versions.**
 - OS: Linux
 - Python: 3.7.1
 - Alembic: 1.6.5
 - SQLAlchemy: 1.4.18
 - Database: SAP HANA
 - DBAPI: hdbcli==2.9.19

**Comment by sqla-tester** [comment]
**Kai Mueller** has proposed a fix for this issue in the **master** branch:

**Fix missing None handling of Table.prefixes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2893
