### ISSUE TITLE
"many" instead of "one" side in one-to-one guide in docs used by mistake

### ISSUE THREAD

**Issue by Zaffer** [sqlalchemy/sqlalchemy#6692]
1. a **succinct description of the problem** - typically a line or two at most
2. **succinct, dependency-free code which reproduces the problem**, otherwise known as a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example.
3. **complete stack traces for all errors - please avoid screenshots, use formatted text inside issues**
4. Other things as applicable:   **SQL log output**, **database backend and DBAPI driver**,
   **operating system**, **comparative performance timings** for performance issues.

-->

**Describe the bug**
wrong wording in relationship guide here: https://docs.sqlalchemy.org/en/14/orm/basic_relationships.html#one-to-one
its says "many" side but example is the "one" side

**To Reproduce**
Read the guide at one-to-one section

```
#For example, to convert a one-to-many relationship into one-to-one, we add uselist=False to what would normally be the “many” side of the relationship, renaming Parent.children to Parent.child for clarity:

class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)

    # this was previously Parent.children
    child = relationship("Child", back_populates="parent", uselist=False)

class Child(Base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey('parent.id'))
    parent = relationship("Parent", back_populates="child")

#Similarly, to convert a many-to-one relationship into one-to-one, we again apply uselist=False to the “many” side, in the below example renaming Child.parents to Child.parent:

class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)
    child_id = Column(Integer, ForeignKey('child.id'))
    child = relationship("Child", back_populates="parent")

class Child(Base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)

    # this was previously Child.parents
    parent = relationship("Parent", back_populates="child", uselist=False)
```

**Error**
wrong wording or side explanation

**Versions.**
 - docs

**Have a nice day!**

**Comment by zzzeek** [comment]
I've clarified this section recently, and im not following where you are seeing a mistake.  is it in the first example, or the second?    the idea of both examples is that the "many" side of the relationship, i.e. the one that refers to a colllection, is converted to have uselist=False, and therefore becomes a single object, even though from a foreign key perspective, it's the "many" side.

the first example:

Relationship:  Parent.children
The "one-to-many" being illustrated is:  Parent.children
Foreign key is on:  Child
the "many" side is:  Parent.children (many Child objects can refer to one Parent)
we convert Parent.children to Parent.child via uselist=False

the second example:

Relatonship: Child.parents
the "many-to-one" being illustrated is:  Parent.child
Foreign key is on: parent
the "many" side is: Parent.child (many Parent objects can refer to one Child)
we convert Child.parents to Child.parent via uselist=False

If I'm missing something above, let me know,    Granted this is all very prone to being confusing but it is what it is.

**Comment by zzzeek** [comment]
perhaps I should be saying, "the collection side", as where we apply "uselist".

**Comment by zzzeek** [comment]
Hi -

I've again rewritten this section entirely.   can you please review the verbiage in  67edf8e  (it will be live on the site within an hour) and let me know if this clarifies.   the section is now more detailed and specific, which risks it becoming too verbose and overwhelming, it's very difficult to strike a balance.

**Comment by Zaffer** [comment]
looks good, except I think you missing "uselist=Flase" from the first code example.... Its been deleted from your change and is not put back in ...

**Comment by Zaffer** [comment]
![image](https://user-images.githubusercontent.com/51871197/123995950-1fce3f00-d9cf-11eb-88f0-3c1929c621a5.png)

**Comment by zzzeek** [comment]
the first code example is a **non** one-to-one setup, showing one-to-many, many-to-one.  the second example then converts it to be one-to-one.  the text expresses this as follows:

"In the example below we present a bidirectional relationship that includes both **one-to-many** (Parent.children) and a **many-to-one** (Child.parent) relationships:"

"Above, **Parent.children is the “one-to-many” side referring to a collection, and Child.parent is the “many-to-one” side** referring to a single object. To **convert** this to “one-to-one”, the “one-to-many” or “collection” side is converted into a scalar relationship using the uselist=False flag, renaming Parent.children to Parent.child for clarity:"

**Comment by Zaffer** [comment]
aha, thanks. The "many" side is what got me cos in a database diagram the many side for me is all the children, cos there are always many children to one parent. Thanks for the clarity and quick action! Hope the repo continues to grow an become more awesome!
