### ISSUE TITLE
1.4.X error when using schema translations on mssql

### ISSUE THREAD

**Issue by CreatingNull** [sqlalchemy/sqlalchemy#6697]
On mssql server it is no longer possible to use `schema_translate_map` to utilise a single declarative model across multiple tables if they exist inside different databases on the server. This is due to residual `[` `]` characters being placed around the translation in the compiled sql.

I cut this down as much as I could and validated I can reproduce it on a fresh development database.
The connection is started in `master` and the `example` table translation is to the `dbo` schema in the `testing` database.

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.types import INTEGER
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Example(Base):
    """Example table that exists across multiple schema in multiple databases."""

    __tablename__ = "example"
    id = Column(INTEGER, primary_key=True)


connection_string = (
    "mssql+pyodbc://"
    r"localhost\MSSQLSERVER/master?"
    r"driver=SQL+Server&trusted&trusted_connection=yes"
)
engine = create_engine(connection_string)
session_maker = sessionmaker()

session = session_maker(
    # Set which database and schema the example table resides in
    bind=engine.execution_options(schema_translate_map={None: "testing.dbo"})
)
try:
    # Dies here on sqlalchemy >=1.4, fine on 1.3.X
    result = session.query(Example).first()
finally:
    session.close()
```

In versions of SQL Alchemy >= 1.4.0 the following error is raised:

```
Traceback (most recent call last):
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'testing.dbo.example'. (208) (SQLExecDirectW)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Insert\Path\Here\.cache\test.py", line 31, in <module>
    result = session.query(Example).first()
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2760, in first
    return self.limit(1)._iter().first()
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2844, in _iter
    result = self.session.execute(
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Insert\Path\Here\venv\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'testing.dbo.example'. (208) (SQLExecDirectW)")
[SQL: SELECT TOP 1 [testing.dbo].example.id AS example_id 
FROM [testing.dbo].example]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

**Versions.**
 - OS: Windows 10 Pro x64 19042
 - Python: 3.9.5
 - SQLAlchemy: 1.4.20
 - Database: mssql server 2019.150.2000.5
 - DBAPI: pyodbc 4.0.30

**Additional context**
I understand this may be a bit of a abnormal usage pattern, to isolate tenancy across databases rather than just to the schema level, but I didn't see any explicit change note to indicate an intended change in behaviour around this. 

I traced it through and can see prior to 1.4 the compiled sql string that gets executed is:

`SELECT TOP 1 testing.dbo.example.id AS example_id FROM testing.dbo.example`

In 1.4 we get the inclusion of `[` `]` bounding chars from the `self.quote` return in the `_render_schema_translates` call. This'll produce an invalid sql string if the translate provided is of the form `database.schema`:

`SELECT TOP 1 [testing.dbo].example.id AS example_id 
FROM [testing.dbo].example
`

Sadly you can't just cheat the system by using the `testing].[dbo` map instead (which actually would also work in 1.3.X), because of the square bracket escape substitutions which occur. Fortunately I was able to resolve the issue locally by simply changing `return self.quote(effective_schema)` to `return effective_schema`. However I'm not familiar enough with the sqlalchemy source to know if there are adverse effects from excluding the quote dialect function on the map. 

Hopefully the smart devs here can help out.

**Have a nice day!**

**Comment by zzzeek** [comment]
hey there -

since you are patching locally, AFAICT this is the bug, want to confirm on your end?

```diff
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index 8ae56fd544..67da036830 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -4751,7 +4751,7 @@ class IdentifierPreparer(object):
                         "Dialect has no default schema name; can't "
                         "use None as dynamic schema target."
                     )
-            return self.quote(effective_schema)
+            return self.quote_schema(effective_schema)
 
         return re.sub(r"(\[SCHEMA_([^\]]+)\])", replace, statement)
 
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Ensure compiler uses quote_schema hook for translates renders** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2944

**Comment by CreatingNull** [comment]
> hey there -
> 
> since you are patching locally, AFAICT this is the bug, want to confirm on your end?
> 
> ```diff
> diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
> index 8ae56fd544..67da036830 100644
> --- a/lib/sqlalchemy/sql/compiler.py
> +++ b/lib/sqlalchemy/sql/compiler.py
> @@ -4751,7 +4751,7 @@ class IdentifierPreparer(object):
>                          "Dialect has no default schema name; can't "
>                          "use None as dynamic schema target."
>                      )
> -            return self.quote(effective_schema)
> +            return self.quote_schema(effective_schema)
>  
>          return re.sub(r"(\[SCHEMA_([^\]]+)\])", replace, statement)
>  
> ```

Hi, thanks for looking into this so quickly.

I can confirm the `quote_schema` change you proposed fixes the bug.
