### ISSUE TITLE
Can't override `noload` loading strategy since 1.4

### ISSUE THREAD

**Issue by jeffsawatzky** [sqlalchemy/sqlalchemy#6703]
If I have a model like this:
```
class NotificationRecipient(db.Model):
    id = db.Column(db.BigInteger, primary_key=True)
    notification_id = db.Column(
        db.BigInteger,
        db.ForeignKey('notifications.id')
    )

class Notification(db.Model):
    id = db.Column(db.BigInteger, primary_key=True)

    recipients = db.relationship(
        NotificationRecipient,
        backref='notification',
        lazy='noload'
    )
```
I can't seem to override the `noload` by doing something like this:

```
Notification.query.options(
    joinedload(Notification.recipients)
).all()
```
As the recipients are always an empty array. This started happening with 1.4, and works fine in 1.3
**Versions.**
 - OS: macOS Catalina
 - Python: 3.9
 - SQLAlchemy: 1.4.20
 - Database: MySQL 5.6
 - DBAPI: mysqlclient

Thank you and...
**Have a nice day!**

**Comment by zzzeek** [comment]
hi there -

can't reproduce.  please modify the [MCVE](http://stackoverflow.com/help/mcve) below to illustrate your failure.  thanks!

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import joinedload
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", lazy="noload")


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs=[B()]))
s.commit()

s = Session(e)

# control
a1 = s.query(A).one()

assert not a1.bs

s.expire_all()
a1 = s.query(A).options(joinedload(A.bs)).one()

# joinedload works
assert a1.bs
```

**Comment by jeffsawatzky** [comment]
Ah, I think it has to do with a combination of `expire_all` and `filter`.

My actual query looks more like this:
```
Notification.query.options(
    joinedload(Notification.recipients)
).filter(Notification.id.in_(notification_ids)).all()
```

In 1.3.24 this works fine and the notifications are loaded with the recipients.

In 1.4.20 this works if I `expire_all` before the query, and it also seems to work if I remove the `filter` without doing an `expire_all`. I'm guessing that 1.4 is caching things a bit better and if the notification is already in the session then it won't reload the recipients without doing an expire first? Not sure how the `filter` plays in. In any case it seems like with 1.4 I need to explicitly expire things, whereas in 1.3 something was doing that for me (or bypassing the cache with the filter?).

I've been trying to come up with an MCVE to show how it worked in 1.3 and not in 1.4, but I have not been successful.

For now I will just ensure I expire_all before the query, unless there is a more efficient way to go about this?

**Comment by jeffsawatzky** [comment]
Ok, I managed to get the MCVE. I'm not sure if the 1.3 behaviour is expected, or the 1.4 behaviour is.

```
from sqlalchemy import Column, ForeignKey, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, joinedload, relationship

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", lazy="noload")


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

a = A(bs=[B()])
s.add(a)
s.commit()

a_id = a.id # This line causes this test to fail in 1.4 but not 1.3

a = s.query(A).options(joinedload(A.bs)).first()

# joinedload works
assert a.bs
```

**Comment by zzzeek** [comment]
it's a call to be made but if i change the script to the following, it fails in 1.3 as well:

```py

# load A; this loads the A.bs collection as empty list
a1 = s.query(A).first()

# therefore this does not refresh A.bs
a = s.query(A).options(joinedload(A.bs)).first()

# this fails
assert a.bs
```

So this is the normal behavior of "noload" on an object in 1.3, when the attribute is "loaded", it gets an empty list and disables any further loads from occurring unless you use populate_existing():

```py

# this will *always* populate A.bs, all versions of SQLAlchemy, and likely 
# what you should do here
a = s.query(A).populate_existing().options(joinedload(A.bs)).first()
```

The change in 1.4 is [eager loaders emit during unexpire operations](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#eager-loaders-emit-during-unexpire-operations), and the "eager loader" in this case is the "noload" loader that will stick an empty list there.    

It's also generally not that useful to even use "noload" because you run the risk of getting an empty list that is not what's actually in the DB.  if you are trying to prevent unwanted lazy loads I'd use [lazy='raise'](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html#prevent-lazy-with-raiseload).

**Comment by jeffsawatzky** [comment]
Switching to `lazy="raise"` was one of the first things I tried, but that caused a bunch of other errors to be thrown all over the place. I inherited this application, and would like to keep existing behaviour the same as much as possible. Thanks for the `populate_existing` tip, that seemed to fix it for my case.
