### ISSUE TITLE
Recursive CTEs create conflicting/ambiguous column names when wrapping a joined query. 

### ISSUE THREAD

**Issue by sonthonaxrk** [sqlalchemy/sqlalchemy#6710]
Hey there, so recursive CTEs create conflicting/ambiguous column names when wrapping a joined query.   This creates invalid queries.

To reproduce (a toy example rather than a use case):

```python
from sqlalchemy import *
from sqlalchemy.orm import *

engine = create_engine('sqlite://', echo=True)
Base = declarative_base()

class Manager(Base):
    __tablename__ = 'manager'
    id = Column(Integer, primary_key=True)


class Employee(Base):
    __tablename__ = 'employee'
    id = Column(Integer, primary_key=True)
    manager_id = Column(Integer, ForeignKey(Manager.id))


Base.metadata.create_all(engine)
session = Session(engine)


top_q = session.query(
    Employee, Manager
).join(Manager)

top_q = top_q.cte("cte", recursive=True)


bottom_q = session.query(
    Employee, Manager
).join(Manager).join(
    top_q,
    top_q.c.id == Employee.id
)

rec_cte = session.query(top_q.union_all(bottom_q))
```

Now if I print `rec_cte` I get

```sql
WITH RECURSIVE cte(id, manager_id, id) AS
(SELECT employee.id AS id, employee.manager_id AS manager_id, manager.id AS id_1
FROM employee JOIN manager ON manager.id = employee.manager_id UNION ALL SELECT employee.id AS employee_id, employee.manager_id AS employee_manager_id, manager.id AS manager_id
FROM employee JOIN manager ON manager.id = employee.manager_id JOIN cte ON cte.id = employee.id)
 SELECT cte.id AS cte_id, cte.manager_id AS cte_manager_id, cte.id_1 AS cte_id_1
FROM cte
```

Notice `WITH RECURSIVE cte(id, manager_id, id)` repeats the ID parameter, when it should be `WITH RECURSIVE cte(id, manager_id, id_1)`

**Comment by sonthonaxrk** [comment]
This was tested against 1.4.20.

**Comment by zzzeek** [comment]
possibly related to #6663 , i dont have time right now but if you can try your case with 1.4.18 that might be interesting here.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Adjust CTE recrusive col list to accommodate dupe col names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2949

**Comment by sonthonaxrk** [comment]
@zzzeek wow, thanks that was quick.  I actually tried with 1.4.18 before I posted the issue when I saw your commit in `visit_cte`.

Thankfully it's not a regression and it didn't work in 1.4.18 either :)

Going to try out your solution. Dumb question, where is the commit referenced in gerrit?

**Comment by sonthonaxrk** [comment]
@zzzeek what branch is that gerrit change on?

**Comment by CaselIT** [comment]
Gerrit does bot use branches, but patches. You should be able to download that from the link

**Comment by sonthonaxrk** [comment]
@zzzeek thanks for the quick fix.  However I noticed it breaks when you try to order by anything, however I've fixed that in

https://github.com/sqlalchemy/sqlalchemy/pull/6713

**Comment by zzzeek** [comment]
OK I can add that part of the patch manually but the main work to be done is test cases in test/sql/test_cte.py.   note these are not ORM-specific tests.   im not around today so if you wanted to come up with new test cases in the style of the ones that are there which exercise this issue, that would be helpful.

**Comment by zzzeek** [comment]
thanks for the assist on this!
