### ISSUE TITLE
Hybrid property has no name in subquery results

### ISSUE THREAD

**Issue by alexa-infra** [sqlalchemy/sqlalchemy#6718]
**Describe the bug**

Hybrid properties have no clear column names in the row results when querying by subquery. It worked in SQLA 1.2 and 1.3, but has broken in 1.4

**To Reproduce**

```py
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import sessionmaker, scoped_session

Base = declarative_base()

engine = sa.create_engine('sqlite:///:memory:')

session_factory = sessionmaker()
session = scoped_session(session_factory)
session.configure(bind=engine)

class User(Base):
    __tablename__ = "users"

    id = sa.Column(sa.Integer, primary_key=True)
    firstname = sa.Column(sa.String(20), nullable=False)
    lastname = sa.Column(sa.String(20), nullable=False)

    @hybrid_property
    def name(self):
        return self.firstname + " " + self.lastname

Base.metadata.create_all(engine)

user = User(firstname="John", lastname="Doe")
session.add(user)
session.flush()

query = session.query(User.id, User.name)
a = query.first()
subquery = query.subquery()
b = session.query(subquery).first()

print("no subquery", a, "keys=", list(a.keys()))
# no subquery (1, 'John Doe') keys= ['id', 'name']
print("with subquery", b, "keys=", list(b.keys()))
# with subquery (1, 'John Doe') keys= ['id', '%(8729752983107 anon)s']
```

above output is for `1.4.20` (in `sqlalchemy==1.3.23` both lines show `['id', 'name']`). As the result it's not possible to access hybrid-property column by its name in the results, etc.

Adding a label seems to fix this behavior `query = session.query(User.id, User.name.label('name'))` but doesn't really look nice.

**Comment by zzzeek** [comment]
please use label("name") for now, no ETA on this

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**experiment w/ propagate ORM proxy name outwards in Core context** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2953
