### ISSUE TITLE
mssql connection error dependent on sa version

### ISSUE THREAD

**Issue by bfmcneill** [sqlalchemy/sqlalchemy#6723]
Using 1.4.20 when I try to make a connection to sql server I get a data source name not found and no default driver specified

```powershell
sqlalchemy.exc.InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDr...
```

here is the way I trigger the error

```python
def test_db_connect(db_cnxn_str):
    engine = sa.create_engine(db_cnxn_str)
    conn = engine.connect() # << ERROR HAPPENS HERE
    # rs = conn.execute("SELECT GETDATE()")
    assert conn
```

If I change my sqlalchemy version to 1.4.12 I am able to connect without any issue.

**Versions.**
 - OS: Windows 10 
 - Python: 3.9
 - SQLAlchemy: 1.4.20
 - Database: MSSQL
 - DBAPI: pyodbc

**Comment by CaselIT** [comment]
Hi,

Can you share your connection string (with sensitive information redacted of course)?

Cc @gordthompson

**Comment by CaselIT** [comment]
Oh, does your password contain an @ char?

If that's so you need to escape it with url escape. See https://github.com/sqlalchemy/sqlalchemy/discussions/6568#discussioncomment-811863

**Comment by bfmcneill** [comment]
@gordthompson

`PROD=mssql+pyodbc://SERVER/PROD_DB?driver=ODBC+Driver+17+for+SQL+Server?trusted_connection=yes`


I am using integrated security so no `@`

**Comment by gordthompson** [comment]
ODBC Driver 17 for SQL Server defaults to `Trusted_Connection=yes` if no UID/PWD are supplied, so try

```
PROD=mssql+pyodbc://@SERVER/PROD_DB?driver=ODBC+Driver+17+for+SQL+Server
```

**Comment by CaselIT** [comment]
>`PROD=mssql+pyodbc://SERVER/PROD_DB?driver=ODBC+Driver+17+for+SQL+Server?trusted_connection=yes`
> 
> 


The issue likely is the two `?` that makes the url invalid. Try replacing the second one with `&`

**Comment by zzzeek** [comment]
see #6601, same issue

**Comment by zzzeek** [comment]
not sure where people are getting these URLs with the two question marks in them from, is this from an online tutorial of some kind?

**Comment by bfmcneill** [comment]
> not sure where people are getting these URLs with the two question marks in them from, is this from an online tutorial of some kind?

I don't know how that got in there :/

**Comment by zzzeek** [comment]
just had another one, so there coming from *somewhere*

**Comment by roger-yu-ds** [comment]
> not sure where people are getting these URLs with the two question marks in them from, is this from an online tutorial of some kind?

I'm sure I've seen the usage of multiple question marks many times online. Can't find them now though. Also, the fact that it worked in previous SQLAlchemy versions added legitimacy in my brain.
