### ISSUE TITLE
Updating a many to many relationship doesn't add all objects to session.dirty

### ISSUE THREAD

**Issue by jtpavlock** [sqlalchemy/sqlalchemy#6736]
**Describe the bug**
When changing an object's attribute, which is mapped to another object, it doesn't always include the original object in `session.dirty`. It seems if multiple object's attributes are altered, only the most recent will be marked as dirty.

**To Reproduce**
Provide your [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve) example
here.

```py
import sqlalchemy
from typing import List
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy.schema import ForeignKey, Table
from sqlalchemy.ext.associationproxy import association_proxy

Session = sessionmaker()
Base = declarative_base()


class _Genre(Base):
    """A track can have multiple genres."""

    __tablename__ = "genre"

    name: str = Column(String, nullable=False, primary_key=True)

    def __init__(self, name: str):
        self.name = name


track_genre = Table(
    "track_genre",
    Base.metadata,
    Column("genre", String, ForeignKey("genre.name")),
    Column("track_id", Integer, ForeignKey("track.id")),
)
__table_args__ = ()


class Track(Base):  # noqa: WPS230
    __tablename__ = "track"

    id: int = Column(Integer, primary_key=True)

    _genres: List[_Genre] = relationship(
        "_Genre", secondary=track_genre, collection_class=list
    )
    genre: List[str] = association_proxy("_genres", "name")

    def __init__(self, id):
        self.id = id


engine = sqlalchemy.create_engine("sqlite:///:memory:")
Session.configure(bind=engine)
Base.metadata.create_all(engine)  # creates tables
session = Session()

track1 = Track(id=1)
track2 = Track(id=2)

session.add(track1)
session.add(track2)
session.commit()

track1.genre = ["pop"]
track2.genre = ["hip hop"]

assert track2 in session.dirty
assert track1 in session.dirty  # fails
```

**Versions.**
 - OS: Ubuntu 20.04.2 LTS
 - Python: 3.9.5
 - SQLAlchemy: 1.4.2
 - Database: sqlite
 - DBAPI:

**Have a nice day!**

**Comment by zzzeek** [comment]
the session is autoflushing between calls, so .dirty is reset when this happens.

change to:

   Session.configure(bind=engine, autoflush=False)


and the test passes.

**Comment by jtpavlock** [comment]
Interesting, I guess I wasn't expecting different behavior when changing an association attribute vs a normal one. 

I was inspecting `session.dirty` to do filesystem operations on any objects that changed throughout a session (path renaming based on attributes), but it looks like that was flawed from the beginning if a session is marked clean after any flush. After looking into this more, it seems I may be better off inspecting `session.dirty` from within an `after_flush` event handler. Does that sound right?

**Comment by zzzeek** [comment]
> Interesting, I guess I wasn't expecting different behavior when changing an association attribute vs a normal one.
> 
> I was inspecting `session.dirty` to do filesystem operations on any objects that changed throughout a session (path renaming based on attributes), but it looks like that was flawed from the beginning if a session is marked clean after any flush. After looking into this more, it seems I may be better off inspecting `session.dirty` from within an `after_flush` event handler. Does that sound right?

well you haven't said what it is you're trying to do, but yes, the event hooks are usually where it's best to do various kinds of logic that depends on the fluid state of the session.    Another option is to disable autoflush for those blocks where it's important for things to occur in a certain order, see background at https://docs.sqlalchemy.org/en/14/orm/session_basics.html?highlight=autoflush#flushing

**Comment by jtpavlock** [comment]
Got a solution using event hooks, thanks for the help.
