### ISSUE TITLE
Scoped_session should warn when used with an async session

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6746]
**Describe the use case**

We added an async version of the scoped_session. The normal scoped_session should raise when used with an async session, since it does not work properly

**Have a nice day!**

**Comment by zzzeek** [comment]
horse has left the barn so i think needs to be a warning not an exception.

**Comment by CaselIT** [comment]
Guess so. we are no longer in beta. we made AsyncEngine raise during the beta iirc

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Deprecate scoped_session usage with async sessions** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2984
