### ISSUE TITLE
Independent CTEs

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6752]
example:

```python
from sqlalchemy import table, column
from sqlalchemy.dialects.postgresql import insert

t = table("t", column("c1"), column("c2"))

delete_statement_cte = t.delete().where(t.c.c1 < 1).cte("deletions")

insert_stmt = insert(t).values([{"c1": 1, "c2": 2}])
update_statement = insert_stmt.on_conflict_do_update(
    index_elements=[t.c.c1],
    set_={
        col.name: col
        for col in insert_stmt.excluded
        if col.name in ("c1", "c2")
    },
).add_cte(delete_statement_cte)

```

produces:

```
WITH deletions AS 
(DELETE FROM t WHERE t.c1 < %(c1_1)s)
 INSERT INTO t (c1, c2) VALUES (%(c1_m0)s, %(c2_m0)s) ON CONFLICT (c1) DO UPDATE SET c1 = excluded.c1, c2 = excluded.c2
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**implement independent CTEs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2957

**Comment by Morikko** [comment]
Just 2 questions on the feature:
1. The fix does not include compound select (like `union`). Is it on purpose ?
2. If someone wants to do it on a ORM query, it should be done like this `query.statement.add_cte()` ?

**Comment by zzzeek** [comment]
> Just 2 questions on the feature:
> 
>     1. The fix does not include compound select (like `union`). Is it on purpose ?

that's an oversight as the "add_cte()" method is part of what was added to CompoundSelect.   If you can provide a short PR or open a new issue that would be helpful.

> 
>     2. If someone wants to do it on a ORM query, it should be done like this `query.statement.add_cte()` ?

please use [2.0 style querying](https://docs.sqlalchemy.org/en/14/glossary.html#term-1) for new code.

**Comment by sqla-tester** [comment]
**Eric Masseran** has proposed a fix for this issue in the **master** branch:

**Dispatch independent ctes on compound select** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2992
