### ISSUE TITLE
on_conflict_do_nothing does not truncate constraint name

### ISSUE THREAD

**Issue by DanCardin** [sqlalchemy/sqlalchemy#6755]
**Describe the bug**
In postgres, using `on_conflict_do_nothing` with a `constraint.name` longer than 63 characters, the whole constraint name will be rendered.

**To Reproduce**
```py
from sqlalchemy import Column, Integer, MetaData, UniqueConstraint
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.schema import CreateTable

convention = {
    "uq": "%(table_name)s_%(column_0_N_name)s_key",
}
Base = declarative_base(metadata=MetaData(naming_convention=convention))


class Table(Base):
    __tablename__ = "this_is_going_to_be_really_long"

    id = Column(Integer, primary_key=True)
    ill_add_some_here_for_good_measure_just_so_it_happens = Column(Integer)

    constraint = UniqueConstraint(ill_add_some_here_for_good_measure_just_so_it_happens)
    __table_args__ = (constraint,)


statement = postgresql.insert(Table).values(dict(id=1)).on_conflict_do_nothing(constraint=Table.constraint)
print(statement.compile(dialect=postgresql.dialect()))

create_table = CreateTable(Table.__table__).compile(dialect=postgresql.dialect())
print(create_table)
```

**Error**
This prints
```
INSERT INTO this_is_going_to_be_really_long (id) VALUES (%(id)s) ON CONFLICT ON CONSTRAINT this_is_going_to_be_really_long_ill_add_some_here_for_good_measure_just_so_it_happens_key DO NOTHING

CREATE TABLE this_is_going_to_be_really_long (
        id SERIAL NOT NULL,
        ill_add_some_here_for_good_measure_just_so_it_happens INTEGER,
        PRIMARY KEY (id),
        CONSTRAINT this_is_going_to_be_really_long_ill_add_some_here_for_g_2102 UNIQUE (ill_add_some_here_for_good_measure_just_so_it_happens)
)
```

I would expect the constraint name for both statements to be the same, i.e. `this_is_going_to_be_really_long_ill_add_some_here_for_g_2102`

**Additional context**
It seems like maybe https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/base.py#L2325, `self.preparer.quote` should be `self.preparer.format_constraint` instead?

In the event this is expected behavior and/or is otherwise not straightforward to make default behavior for other reasons, it'd be great if there were (or is) a way of manually invoking this behavior. But it's not obvious how one minimally produces a postgres preparer

**Comment by zzzeek** [comment]
we can't put format_constraint there because we don't have the constraint anymore, and the "name" has been figured out at this stage so it seems like that whole bit of logic to re-run the naming convention isn't needed, not sure why that's even in the compiler actually.      half of format_constraint() needs to be broken out.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Extract format_constraint truncation rules to ON CONFLICT** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2958

**Comment by DanCardin** [comment]
very quick turnaround, thanks!
