### ISSUE TITLE
Allow generic by implementing __class_getitem__

### ISSUE THREAD

**Issue by glyph** [sqlalchemy/sqlalchemy#6759]
At work we use https://pypi.org/project/sqlalchemy-stubs/ and we prohibit any-generics for code hygiene.  This means we somewhat regularly have stanzas that look like this:

```python3
if TYPE_CHECKING:
     PopulatedColumnGeneric = Column[Any]
     PopulatedBinaryExpression = BinaryExpression[bool, ColumnClause[Any], Any]
 else:
     PopulatedColumnGeneric = Column
     PopulatedBinaryExpression = BinaryExpression
```

so that anything which reads the types using introspection sees actual types, but we've explicitly populated the generic elements of the type.

I realize that sqlalchemy-stubs is a 3rd-party extension here, and you're not responsible for its choices, but I think its generics roughly accurately describe the types within sqlalchemy, and it would be handy and helpful for `[]` to be defined at runtime so we don't need to pull out this escape hatch all the time.

Thank you for your consideration!

**Comment by CaselIT** [comment]
Hi,

We are still supporting python 2 for the 1.4 series, so for now the typing definitions are managed externally since it would otherwise duplicate the work. The plan is to integrate them in the code in version 2.x

Also note that if you are using 1.4 we provide have stubs https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html that are based on https://github.com/sqlalchemy/sqlalchemy2-stubs

**Comment by zzzeek** [comment]
do we not have an issue already for unifying stubs into main source?

**Comment by CaselIT** [comment]
does not seem so: https://github.com/sqlalchemy/sqlalchemy/labels/pep484

may as well use thig

**Comment by zzzeek** [comment]
hey try this:

```diff
diff --git a/lib/sqlalchemy/sql/visitors.py b/lib/sqlalchemy/sql/visitors.py
index 1cd7b63cde..c16dfb2c62 100644
--- a/lib/sqlalchemy/sql/visitors.py
+++ b/lib/sqlalchemy/sql/visitors.py
@@ -120,6 +120,9 @@ class Traversible(util.with_metaclass(TraversibleType)):
 
     """
 
+    def __class_getitem__(self, key):
+        return self
+
     @util.preload_module("sqlalchemy.sql.traversals")
     def get_children(self, omit_attrs=(), **kw):
         r"""Return immediate child :class:`.visitors.Traversible`
```


now this program runs w/o issue python 3.9 and above:

```py
from sqlalchemy.sql.expression import BinaryExpression, ColumnClause
from sqlalchemy import Column
from typing import Any


PopulatedColumnGeneric = Column[Any]
PopulatedBinaryExpression = BinaryExpression[bool, ColumnClause[Any], Any]


```


is this a solution?

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Support generics in code to allow Column[int] etc** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2977
