### ISSUE TITLE
composing column_property with Table.table_valued()

### ISSUE THREAD

**Issue by danburkert** [sqlalchemy/sqlalchemy#6775]
It appears that the `table_valued()` function does not alias correctly when used inside a `column_property` model field.

Minimal example:

```py
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import (
    Text, Column, sql, orm, String, Integer, ForeignKey, event, create_engine,
    select,
)

Base = declarative_base()

class User(Base):
    __tablename__ = 'users'

    user_id = Column(Integer, primary_key=True)

    addresses = orm.relationship("Address", back_populates="user")


class Address(Base):
    __tablename__ = 'addresses'

    address_id = Column(Integer, primary_key=True)

    user_id = Column(Integer, ForeignKey(User.user_id))

    user = orm.relationship("User", back_populates="addresses")


Address.json = orm.column_property(sql.func.row_to_json(Address.__table__.table_valued()))

e = create_engine("postgresql://localhost", echo=False)

Base.metadata.create_all(e)

print(select(User).options(orm.joinedload(User.addresses)))
```

I expected this to print:

```sql
SELECT users.user_id, addresses_1.address_id, addresses_1.user_id AS user_id_1, row_to_json(addresses_1) AS row_to_json_1
FROM users LEFT OUTER JOIN addresses AS addresses_1 ON users.user_id = addresses_1.user_id
```

but instead it prints:

```sql
SELECT users.user_id, addresses_1.address_id, addresses_1.user_id AS user_id_1, row_to_json(addresses) AS row_to_json_1
FROM users LEFT OUTER JOIN addresses AS addresses_1 ON users.user_id = addresses_1.user_id
```

With the relevant difference being `row_to_json(addresses_1)` (expected) vs `row_to_json(addresses)` (actual).  Postgres rejects the query, since the unaliased table is not in scope of the select list.

It's not entirely clear to me, but this looks like it may be a bug. If not, is there another way to call a function which takes a table type as an argument in a column property?

**Versions.**
 - OS:
 - Python: 3.7
 - SQLAlchemy: 1.4.21
 - Database: Postgres
 - DBAPI: default

Thanks!

**Comment by CaselIT** [comment]
It does seem to be a bug. Thanks for reporting

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**reset key/name when TableValuedColumn is adapted** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2966

**Comment by zzzeek** [comment]
if you can test out github master and make sure your use cases are all working out here we can make sure there's no other things to fix here, thanks!

**Comment by danburkert** [comment]
Master fixed my issue, thanks for the quick turnaround!
