### ISSUE TITLE
Using engine to execute fetchall directly into insert fails with TypeError.

### ISSUE THREAD

**Issue by ianjosephwilson** [sqlalchemy/sqlalchemy#6779]
**Describe the bug**
Passing the results of a fetchall from one table into the execution of an insert with engine fails with an exception.

```
e.execute(table1.insert(),
          e.execute(select(table2.c)).fetchall())
```

The sorted params data in the example is  `sorted([(1, 'Customer')][0])`.

**To Reproduce**

Executing the following script on the command line produces exception.

```py
from sqlalchemy import (
    create_engine,
    UnicodeText,
    Integer,
)
from sqlalchemy.schema import (
    Table,
    Column,
    MetaData,
)
from sqlalchemy.sql import select


metadata = MetaData()

groups1_t = Table('groups1', metadata,
                  Column('id', Integer, primary_key=True),
                  Column('name', UnicodeText, nullable=False),
)
groups2_t = Table('groups2', metadata,
                  Column('id', Integer, primary_key=True),
                  Column('name', UnicodeText, nullable=False),
)

e = create_engine("sqlite://", echo=False)

metadata.create_all(e)

e.execute(groups1_t.insert().values(id=1, name='Customer'))

# Try to pump data from old table into new table.
e.execute(groups2_t.insert(),
          e.execute(select(groups1_t.c)).fetchall())

```

**Error**

```
Traceback (most recent call last):
  File "testing.py", line 33, in <module>
    e.execute(select(groups1_t.c)).fetchall())
  File "<string>", line 2, in execute
  File "/home/ian/workspace/laspilitas-project/laspilitas/laspilitas/ve/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/home/ian/workspace/laspilitas-project/laspilitas/laspilitas/ve/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3108, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/ian/workspace/laspilitas-project/laspilitas/laspilitas/ve/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1263, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/ian/workspace/laspilitas-project/laspilitas/laspilitas/ve/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/ian/workspace/laspilitas-project/laspilitas/laspilitas/ve/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1428, in _execute_clauseelement
    keys = sorted(distilled_params[0])
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Versions.**
 - OS: `Linux 5.10.0-0.bpo.7-amd64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04) x86_64 GNU/Linux`
 - Python: 3.7.3
 - SQLAlchemy: 1.4.21
 - Database: sqlite

**Additional context**

I just noticed bug after upgrading to 1.4.21.  I'm using this functionality to migrate data from mysql to posgresql in a giant migration script and for tables whose structure/data didn't change I just pump the data directly from one to the other.

This isn't a have to have for my project but might cause other problems if someone didn't already notice it already.

Maybe this usage is long since outdated?

**Comment by ianjosephwilson** [comment]
Easy solution seems to just run the results through dict like:
```
e.execute(groups2_t.insert(), [dict(r) for r in e.execute(select(groups1_t.c)).fetchall()])
```

**Comment by zzzeek** [comment]
the Row object in 1.4 acts much more like a tuple:

https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#rowproxy-is-no-longer-a-proxy-is-now-called-row-and-behaves-like-an-enhanced-named-tuple

to the extent that it still supports dict-like usages without an explicit (very simple) step, [this is all deprecated](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#result-rows-act-like-named-tuples).

to get rows as mappings, use the [_mapping](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=row%20_mapping#sqlalchemy.engine.Row._mapping) accessor or more simply use [result.mappings()](https://docs.sqlalchemy.org/en/14/core/connections.html?highlight=row%20_mapping#sqlalchemy.engine.Result.mappings).

(also, don't use engine.execute(); your code example above has to consult the connection pool twice and [this is also deprecated](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#implicit-and-connectionless-execution-bound-metadata-removed)):

```py

with e.begin() as conn:
    data = conn.execute(select(groups_1.c)).mappings().all()
    conn.execute(groups_2.t.insert(), data) 

```

**Comment by ianjosephwilson** [comment]
Thanks for clarifying why it stopped working. I'm going to close this and convert the code to use `mappings`.

BTW my migration script is 4 times faster using the context manager you proposed, from 8 mins to 2 mins.  Thanks!
