### ISSUE TITLE
CASE dict form raises deprecation warnings

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6786]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/6785

<div type='discussions-op-text'>

<sup>Originally posted by **ianjosephwilson** July 20, 2021</sup>
Trying to bring my code base into the 2020s and going through the warnings and saw a warning for my case statement.

```python
        whens = {}
        for size in ('1gal', '5gal', '15gal'):
            whens.update({
                f'{size}-fr': f'{size}-inventory',
                f'{size}-pr': f'{size}-production',
                f'{size}-nr': f'{size}-production'
            })
        category = case(whens=whens, value=items_t.c.short_code, else_=None).label('category')
```

Using a dict still seems ok in the docs.

Seems that the "Was a list but is now position args" warning should trigger in the else statement instead of this if statement??:

https://github.com/sqlalchemy/sqlalchemy/blob/a25d6ead9cf6d2d51ae67e53eac50f642a0bb432/lib/sqlalchemy/sql/elements.py#L2920</div>

from https://github.com/sqlalchemy/sqlalchemy/discussions/6785#discussioncomment-1025093

> It seems that the if block emits the warning when whens is a kw and so does the else block via coercions._expression_collection_was_a_list because *whens is a single element tuple containing the dict. Not sure but it appears the warning is unsquelchable.
> 
```py
def _expression_collection_was_a_list(attrname, fnname, args):
    if args and isinstance(args[0], (list, set, dict)) and len(args) == 1:
        util.warn_deprecated_20(
            'The "%s" argument to %s() is now passed as a series of '
            "positional "
            "elements, rather than as a list. " % (attrname, fnname)
        )
        return args[0]
    else:
        return args
```
>
```py
        #...
        if "whens" in kw:
            util.warn_deprecated_20(
                'The "whens" argument to case() is now passed as a series of '
                "positional "
                "elements, rather than as a list. "
            )
            whens = kw.pop("whens")
        else:
            whens = coercions._expression_collection_was_a_list(
                "whens", "case", whens
            )
```

**Comment by zzzeek** [comment]
Can i get a summary of the exact problem?   It's not clear to me what's emitting a deprecation warning.  is it sending the "whens" dictionary positionally?

**Comment by CaselIT** [comment]
bow these form emit deprecation warnings:
```py
case(whens={'foo': 'bar', 'bar': 'baz'}, value=sa.column('some_col'))
case({'foo': 'bar', 'bar': 'baz'}, value=sa.column('some_col'))
```
so there is no way of not getting the warning when using the dict form

**Comment by zzzeek** [comment]
oh we have the warning ignored in warnings.py, OK.

**Comment by CaselIT** [comment]
yes, it's a 20 warning so most of them are still ignored

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**repair mistaken deprecation of "whens" dictionary form** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2969
