### ISSUE TITLE
Generics on TypeDecorator

### ISSUE THREAD

**Issue by alxdb** [sqlalchemy/sqlalchemy#6804]
If I'm defining custom database types with `sqlalchemy.types.TypeDecorator` and I would like to be able to specify the related python types, so I don't have to put annotations in my ORMs (they can be inferred like they are for built in database type such as `sqlalchemy.String`)

The way this is done by the dropbox sqlalchemy-stubs is to add a generic parameter to `sqlalchemy.types.TypeDecorator` and this method is still valid here. However this leads to the issue described [here](https://github.com/dropbox/sqlalchemy-stubs/issues/36) and also seems to be unstable when the type decorator is defined in a module other than where it is used (not sure if `TYPE_CHECKING` is defined also in imported modules when type checking?).

According to the [mypy docs](https://mypy.readthedocs.io/en/latest/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime) this issue can be circumvented in python 3.9 by implementing `__class_getitem__()` which may or may not address the issue.

**Comment by CaselIT** [comment]
@zzzeek not sure if this is more something for v2 or may be also in 1.4.
I don't think it would creare issues for py < 3.9 have that method defined

**Comment by zzzeek** [comment]
my two cents:

1. this is the same issue as #6759 right?

2. this `__class_getitem__` thing could in fact fix #6759 right now, couldn't it ?  


works:

```diff
diff --git a/lib/sqlalchemy/sql/visitors.py b/lib/sqlalchemy/sql/visitors.py
index 1cd7b63cde..c16dfb2c62 100644
--- a/lib/sqlalchemy/sql/visitors.py
+++ b/lib/sqlalchemy/sql/visitors.py
@@ -120,6 +120,9 @@ class Traversible(util.with_metaclass(TraversibleType)):
 
     """
 
+    def __class_getitem__(self, key):
+        return self
+
     @util.preload_module("sqlalchemy.sql.traversals")
     def get_children(self, omit_attrs=(), **kw):
         r"""Return immediate child :class:`.visitors.Traversible`
```

**Comment by CaselIT** [comment]
if we don't repurpose #6759 for the inlining of pep484, it seems so. We can open a new issue for that

It seems a class method so its signature probably should be 

```py
    def __class_getitem__(cls, key):
        return cls
```

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Support generics in code to allow Column[int] etc** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2977

**Comment by alxdb** [comment]
I have managed to address this issue locally by doing:

```python
import sqlalchemy as sa

sa.sql.visitors.TraversibleType.__class_getitem__ = lambda cls, key: cls  # type: ignore

# this now works at runtime
class UUID(sa.types.TypeDecorator[uuid.UUID]):
    ...
```

not ideal, but I am hoping this can be removed on resolution of https://github.com/sqlalchemy/sqlalchemy/issues/6759

**Comment by CaselIT** [comment]
The fix should be merged shortly and it should be available in the next release.
