### ISSUE TITLE
ORM internals apparently using Core methods that are deprecated

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#6812]
After removing the "(?:update|delete).whereclause parameter" warning from the list of ignored 2.0 warnings for tests
https://github.com/sqlalchemy/sqlalchemy/blob/7e7d097a633d1b7a95bbd59f9a6d2a5b85249332/lib/sqlalchemy/testing/warnings.py#L79-L80

two tests are failing, not because the test code explicitly uses that construct, but (apparently) because the ORM internals use it in the process of generating the required SQL statement(s).

Failing tests are here

https://github.com/sqlalchemy/sqlalchemy/blob/7e7d097a633d1b7a95bbd59f9a6d2a5b85249332/test/orm/test_manytomany.py#L392-L397

and here

https://github.com/sqlalchemy/sqlalchemy/blob/7e7d097a633d1b7a95bbd59f9a6d2a5b85249332/test/orm/test_naturalpks.py#L556

I will add a "Fixes: #nnnn" line to the commit message to establish a link between the Gerrit change and this issue.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **master** branch:

**Modernize tests - dml_whereclause** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2978
