### ISSUE TITLE
Incorrect warning `Reassigning polymorphic association` in some cases of inheritance 

### ISSUE THREAD

**Issue by ri-gilfanov** [sqlalchemy/sqlalchemy#6819]
### Describe the bug

Incorrect warning `SAWarning: Reassigning polymorphic association for identity ... Check for duplicate use of ... as value for polymorphic_identity` under some inheritance configurations. 

In the example below, there is no duplication of polymorphic identity. But a warning is displayed.

### To Reproduce

```python
import sqlalchemy as sa
from sqlalchemy import orm


metadata = sa.MetaData()
BaseModel = orm.declarative_base(metadata=metadata)


@orm.declarative_mixin
class PolymorphicMixin:
    @orm.declared_attr
    def discriminator(cls) -> sa.Column:
        return sa.Column(sa.String(40), nullable=False)

    __mapper_args__ = {
        'polymorphic_on': discriminator,
    }


class Entity(BaseModel, PolymorphicMixin):
    __tablename__ = 'entities'
    pk = sa.Column(sa.Integer, primary_key=True)


class Actor(Entity):
    __tablename__ = 'actors'
    __mapper_args__ = {'polymorphic_identity': 'actor'}
    pk = sa.Column(sa.ForeignKey(Entity.pk), primary_key=True)


class Client(Actor):
    __tablename__ = 'clients'
    pk = sa.Column(sa.ForeignKey(Actor.pk), primary_key=True)


class Person(Client):
    __mapper_args__ = {'polymorphic_identity': 'person'}


class Company(Client):
    __mapper_args__ = {'polymorphic_identity': 'company'}
```

### Error

```
test_example.py:31: SAWarning: Reassigning polymorphic association for identity 'actor' from <Mapper at 0x7ff89b8d6070; Actor> to <Mapper at 0x7ff89b8d61c0; User>: Check for duplicate use of 'actor' as value for polymorphic_identity.
  class User(Actor):
```

### Versions

- OS: Linux Mint 20.2
- Python: 3.9.5
- SQLAlchemy: 1.4.22

### Additional context

If the ``polymorphic_identity`` argument is removed from the ``Actor`` class, there will be no warning.

If the ``polymorphic_identity`` argument is added to the ``Client`` class, there will be no warning.

**Comment by zzzeek** [comment]
hi there -


The warning is correct in this case.   the polymorphic map is reassigning the "actor" identity to the Client subclass.    This means you can no longer load an Actor object from the database polymorphically:


```py
e = create_engine("sqlite://", echo=True)
Entity.metadata.create_all(e)

s = orm.Session(e)
s.add(Actor())
s.commit()
s.close()

c1 = s.query(Entity).first()

assert isinstance(c1, Actor)
assert not isinstance(c1, Client)  # fails
```

adding a distinct identity for client fixes the above failure and resolves the warning:

```py
class Client(Actor):
    __tablename__ = 'clients'
    pk = sa.Column(sa.ForeignKey(Actor.pk), primary_key=True)

    __mapper_args__ = {"polymorphic_identity": "client"}

```

**Comment by ri-gilfanov** [comment]
@zzzeek, understood. Thanks for the consultation.

**Comment by zzzeek** [comment]
OK I suppose we are done, great
