### ISSUE TITLE
after_transaction_end event not fired when NestedTransaction commits in future mode

### ISSUE THREAD

**Issue by bigjools** [sqlalchemy/sqlalchemy#6823]
### Describe the bug

According to the documents at https://docs.sqlalchemy.org/en/14/orm/events.html#sqlalchemy.orm.SessionEvents.after_transaction_end
which say:
> This event differs from SessionEvents.after_commit() in that it corresponds to all SessionTransaction objects in use, including those for **nested transactions and subtransactions**

(my emphasis)

we should see `after_transaction_end` fire when I commit a transaction returned from `Connection.begin_nested`.
However, no such event fires.

### To Reproduce

```python
from sqlalchemy import event, create_engine, Column, Integer
from sqlalchemy.orm import declarative_base, sessionmaker
  
Base = declarative_base()
class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)
    foo = Column(Integer)
  
engine = create_engine("sqlite://", future=True)
# I know sqlite doesn't have savepoints but it makes the example easier. Fails on postgres too.
Session = sessionmaker()
Base.metadata.create_all(bind=engine)
 
connection = engine.connect()
txn = connection.begin()
session = Session(future=True, bind=connection)
 
@event.listens_for(session, "after_transaction_end")
def do_something(sess, transaction):
    print("after_transaction_end called")
 
savepoint = connection.begin_nested()
assert savepoint.is_active == True                                                                                                                                                                                             
session.add(Foo(foo=1))
savepoint.commit()
assert savepoint.is_active == False
 
 
# Should print the message above, does not.
```

### Error

No event callback happens.

### Versions

- OS: Ubuntu 20.04
- Python: 3.8
- SQLAlchemy: 1.4.22
- Database: Postgres 11
- DBAPI:

**Comment by zzzeek** [comment]
hey there -

the after_transaction_end event is an ORM session event, not a connection event.  you would need to be calling session.begin_nested(), not "begin_nested()" on a Core connection object.     to intercept Core transactional events use [connectionevents](https://docs.sqlalchemy.org/en/14/core/events.html?highlight=connectionevents#sqlalchemy.events.ConnectionEvents).

**Comment by bigjools** [comment]
Hi

I was following the example here: https://docs.sqlalchemy.org/en/14/orm/session_transaction.html?highlight=after_transaction_end#joining-a-session-into-an-external-transaction-such-as-for-test-suites
which runs `begin_nested` on the connection.

I tried `release_savepoint` in the connection events too but that hasn't set `is_active` to False before the event is called so it can't know whether to restart a savepoint or not.

The new future behaviour of committing the outer transaction when a session gets a commit (instead of just committing the savepoint) has completely broken my test suite infrastructure, as I need to test code that uses `commit`. I tried to work around it by monkey patching the savepoint commit into the session commit. With the begin_nested on the session it's still not working right and I need to investigate. Perhaps this needs to be a question but I'm not sure if GH will let me change this issue to one.

**Comment by bigjools** [comment]
Let me add that this part of the above example:

```python
        # rollback - everything that happened with the
        # Session above (including calls to commit())
        # is rolled back.
        self.trans.rollback()
```

is not the behaviour I am seeing. Any session commit() will cause data to leak between tests and rollback will do nothing because it's trying to roll back the transaction object that was already committed.

**Comment by bigjools** [comment]
The text referenced here: https://docs.sqlalchemy.org/en/14/orm/session_transaction.html#nested-transaction
`Calling the Session.commit() or Connection.commit() methods will always commit the outermost transaction; this is a SQLAlchemy 2.0 specific behavior that is reversed from the 1.x series`
Given that, I don't see how the test isolation example code can ever work as shown. Am I reading something wrong or am I missing something?

**Comment by CaselIT** [comment]
Hi,

I have not run it, but I think your example is not runnable since the session is not bound to anything.
It's not clear to me if the session you are using uses the engine as bind or a connection.
In the docs examples, the session uses a connection that's already in a transaction, so the control of the transaction stays with the connection.

Could you provide a better example that illustrates what you are doing in your tests to understand if there is something that's wrong there or if there is an issue with sqlalchemy?

Thanks

**Comment by bigjools** [comment]
It might be best to ignore the example I wrote since Mike pointed out that I was trying to get an event on the wrong thing.

The best alternative example I can give is the one at https://docs.sqlalchemy.org/en/14/orm/session_transaction.html?highlight=after_transaction_end#joining-a-session-into-an-external-transaction-such-as-for-test-suites

It doesn't work if the session is configured with `future=True`; any commits will leak into the next test.

**Comment by CaselIT** [comment]
Ok, that may be a bug. I'll take a look

**Comment by bigjools** [comment]
Ok thank you. I don't think it's a bug as such, it seems more of a design flaw or missing functionality.

**Comment by CaselIT** [comment]
I cannot reproduce. Taking the example and making it runnable:
```py
from sqlalchemy.orm import sessionmaker, declarative_base
from sqlalchemy import create_engine, event, Column, Integer, text
from unittest import TestCase, main
from logging import getLogger, Formatter

future = False
# global application scope.  create Session class, engine
Session = sessionmaker(future=future)

engine = create_engine(
    "postgresql://mamba:mamba-password@localhost/test", future=future
)
Base = declarative_base()

class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)

class Bar(Base):
    __tablename__ = "bar"
    id = Column(Integer, primary_key=True)

class SomeTest(TestCase):
    @classmethod
    def setUpClass(cls):
        Base.metadata.create_all(engine)
        engine.echo = True
        l = getLogger("sqlalchemy.engine.Engine")
        l.handlers[0].setFormatter(Formatter("[%(levelname)s] %(message)s"))
        l.warning(f'{future=}')

    @classmethod
    def tearDownClass(cls):
        engine.echo = False
        Base.metadata.drop_all(engine)

    def setUp(self):
        # connect to the database
        self.connection = engine.connect()

        # begin a non-ORM transaction
        self.trans = self.connection.begin()

        # bind an individual Session to the connection
        self.session = Session(bind=self.connection)

        ###    optional     ###

        # if the database supports SAVEPOINT (SQLite needs special
        # config for this to work), starting a savepoint
        # will allow tests to also use rollback within tests

        self.nested = self.connection.begin_nested()

        @event.listens_for(self.session, "after_transaction_end")
        def end_savepoint(session, transaction):
            print()
            if not self.nested.is_active:
                self.nested = self.connection.begin_nested()

        ### ^^^ optional ^^^ ###

    def test_something(self):
        # use the session in tests.

        self.session.add(Foo())
        # self.session.execute("select 1")
        self.session.commit()

    def test_something_with_rollbacks(self):
        # if the SAVEPOINT steps are taken, then a test can also
        # use session.rollback() and continue working with the database

        # self.session.execute("select 1")
        self.session.add(Bar())
        self.session.flush()
        self.session.rollback()

        # self.session.execute("select 1")
        self.session.add(Foo())
        self.session.commit()

    def tearDown(self):
        self.session.close()

        # rollback - everything that happened with the
        # Session above (including calls to commit())
        # is rolled back.
        self.trans.rollback()

        print(self.connection.scalar(text("select count(*) from foo")))
        print(self.connection.scalar(text("select count(*) from bar")))

        # return connection to the Engine
        self.connection.close()

main()
```

I get exactly the same output:
with `future=True`
```
[WARNING] future=True
[INFO] BEGIN (implicit)
[INFO] SAVEPOINT sa_savepoint_1
[INFO] [no key 0.00029s] {}
[INFO] INSERT INTO foo DEFAULT VALUES RETURNING foo.id
[INFO] [generated in 0.00024s] {}

[INFO] RELEASE SAVEPOINT sa_savepoint_1
[INFO] [no key 0.00029s] {}

[INFO] SAVEPOINT sa_savepoint_2
[INFO] [no key 0.00015s] {}
[INFO] ROLLBACK
[INFO] BEGIN (implicit)
[INFO] select count(*) from foo
[INFO] [generated in 0.00025s] {}
0
[INFO] select count(*) from bar
[INFO] [generated in 0.00016s] {}
0
[INFO] ROLLBACK
.[INFO] BEGIN (implicit)
[INFO] SAVEPOINT sa_savepoint_1
[INFO] [no key 0.00015s] {}
[INFO] INSERT INTO bar DEFAULT VALUES RETURNING bar.id
[INFO] [generated in 0.00017s] {}

[INFO] ROLLBACK TO SAVEPOINT sa_savepoint_1
[INFO] [no key 0.00022s] {}

[INFO] SAVEPOINT sa_savepoint_2
[INFO] [no key 0.00015s] {}
[INFO] INSERT INTO foo DEFAULT VALUES RETURNING foo.id
[INFO] [cached since 0.01088s ago] {}

[INFO] RELEASE SAVEPOINT sa_savepoint_2
[INFO] [no key 0.00016s] {}

[INFO] SAVEPOINT sa_savepoint_3
[INFO] [no key 0.00017s] {}
[INFO] ROLLBACK
[INFO] BEGIN (implicit)
[INFO] select count(*) from foo
[INFO] [cached since 0.009957s ago] {}
0
[INFO] select count(*) from bar
[INFO] [cached since 0.009605s ago] {}
0
[INFO] ROLLBACK
.
----------------------------------------------------------------------
Ran 2 tests in 0.094s

OK
```
with `future=False`:
```
[WARNING] future=False
[INFO] BEGIN (implicit)
[INFO] SAVEPOINT sa_savepoint_1
[INFO] [no key 0.00019s] {}
[INFO] INSERT INTO foo DEFAULT VALUES RETURNING foo.id
[INFO] [generated in 0.00036s] {}

[INFO] RELEASE SAVEPOINT sa_savepoint_1
[INFO] [no key 0.00023s] {}

[INFO] SAVEPOINT sa_savepoint_2
[INFO] [no key 0.00019s] {}
[INFO] ROLLBACK
[INFO] select count(*) from foo
[INFO] [generated in 0.00021s] {}
0
[INFO] select count(*) from bar
[INFO] [generated in 0.00022s] {}
0
.[INFO] BEGIN (implicit)
[INFO] SAVEPOINT sa_savepoint_1
[INFO] [no key 0.00029s] {}
[INFO] INSERT INTO bar DEFAULT VALUES RETURNING bar.id
[INFO] [generated in 0.00015s] {}

[INFO] ROLLBACK TO SAVEPOINT sa_savepoint_1
[INFO] [no key 0.00016s] {}

[INFO] SAVEPOINT sa_savepoint_2
[INFO] [no key 0.00016s] {}
[INFO] INSERT INTO foo DEFAULT VALUES RETURNING foo.id
[INFO] [cached since 0.0105s ago] {}

[INFO] RELEASE SAVEPOINT sa_savepoint_2
[INFO] [no key 0.00016s] {}

[INFO] SAVEPOINT sa_savepoint_3
[INFO] [no key 0.00015s] {}
[INFO] ROLLBACK
[INFO] select count(*) from foo
[INFO] [cached since 0.008572s ago] {}
0
[INFO] select count(*) from bar
[INFO] [cached since 0.00824s ago] {}
0
.
----------------------------------------------------------------------
Ran 2 tests in 0.094s

OK
```

I would suggest adapting the example above to check what's the issue in your case

**Comment by bigjools** [comment]
Ok thank you for following up. I'm clearly doing something differently so I'll try to convert my large test suite fixture into a smaller case to reproduce. I thought that I'd replicated this example perfectly! I'm still confused about the session commit not committing the root transaction though, as the documentation says.

**Comment by CaselIT** [comment]
Where in the documentation is that line? It may need a clarification that's only true when the session is not joining an existing transaction

**Comment by bigjools** [comment]
I referenced it in my comment above
https://github.com/sqlalchemy/sqlalchemy/issues/6823#issuecomment-889562110

**Comment by CaselIT** [comment]
that seems to be in the context of nested transactions. may be worth clarifying that though

**Comment by bigjools** [comment]
In that case I'm not entirely sure I understand what a nested transaction is, in this context. The code you pasted here is using them, isn't it?

**Comment by CaselIT** [comment]
Yes the code above uses nested transaction (creating a savepoint in the db).

Ideally the difference is who owns it.

- When using a session bound to an engine `Session(bind=engine)`, the session is the owner of the transaction, so `commit()`/`rolloback()` on the session will end the transaction. This works the same when using nested transaction.
- When using a session bound to an existing connection `Session(bind=conn)`, the session is not the owner of the transaction, the connection is, things are a bit different depending if the connection has a normal transaction or a nexted one active: 
  - in case of a normal transtaction, so without savepoints, `commit()` on the session will not end the transaction, becoming a no-op, while `session.rollback()` will rollback the outer transaction.
  - in case of a nested transtaction, so with savepoints, `commit()`/`rollback()` on the session will `release`/`rollback` the savepoint.

Assuming all this is correct (cc @zzzeek :smile: ) it may make sense having this in the doc in a table?

**Comment by bigjools** [comment]
Hi again

I have got to the bottom of things. I had a custom `sessionmaker` in place that was re-binding the session to the engine, which caused a BEGIN to get emitted and overrode the savepoint.

Thank you VERY much for helping me through this, this is an awesome project with awesome people. The support will not be forgotten.

Cheers.

**Comment by MajorDallas** [comment]
Since I wound up here having a similar problem but using pytest, here's a working pytest implementation of https://github.com/sqlalchemy/sqlalchemy/issues/6823#issuecomment-889860696 in case any other pytest users land here from google/ddg:

```python
import pytest
from sqlalchemy import event
from sqlalchemy.engine import create_engine
from sqlalchemy.orm.session import sessionmaker

engine = create_engine(<db_string>[, echo=True, echo_pool=True])
Session = sessionmaker()

@pytest.fixture
def savepoint():
    connectors = {}
    connectors["connection"] = engine.connect()
    connectors["transaction"] = connectors["connection"].begin()
    connectors["session"] = Session(bind=connectors["connection"])
    connectors["nested"] = connectors["connection"].begin_nested()

    @event.listens_for(connectors["session"], "after_transaction_end")
    def end_savepoint(session, transaction):
        if not connectors["nested"].is_active:
            connectors["nested"] =  connectors["connection"].begin_nested()

    yield connectors["session"]
    connectors["session"].close()
    connectors["transaction"].rollback()
    connectors["connection"].close()
```

As to how I actually fixed the problem of data being left behind after every test, I guess at some point during a refactor I failed to update a reference to a previously module-scoped variable (the `Session`) into a class attribute reference. My tests were then using two separate `Session` objects for different operations, and only one was inside the `Connection`'s transaction.

Overall a productive process: it revealed not only a simple programmer error but also a poor design choice.

**Comment by bigjools** [comment]
I have some [fixtures](https://pypi.org/project/fixtures/) and [resources](https://pypi.org/project/testresources/) I use under [testtools](https://testtools.readthedocs.io/en/latest/) as well, I plan on open sourcing them as a new project at some point. You can declare whether you're using SQLite or Postgres and it does the rest by giving you a session per test, without restarting the whole database. PG is in fact started in seconds on demand in a container at the start of the test run.

**Comment by zzzeek** [comment]
looks like this is figured out.
