### ISSUE TITLE
Create a function to get the driver connection

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6832]
### Describe the use case

Now that we have async support it's a bit hard to obtain the raw dbapi connection, since for example for asyncpg one would need to do:

```py
engine = create_async_engine('postgresql+asyncpg://mamba:mamba-password@localhost/test', echo=True)
async def go():
    conn = await engine.connect()
    asyncpg_conn = (await conn.get_raw_connection()).connection._connection
asyncio.run(go())
```

It would be nice to have a function (two given that we need also an async one) to obtain it.

### Databases / Backends / Drivers targeted

any

### Example Use

Let's the function are called `driver_connecion()` and `async_driver_connection()`

```py
conn = driver_connecion(engine)
conn = driver_connecion(session)

conn = await async_driver_connection(sa_conn)
```

**Comment by zzzeek** [comment]
there's a need to distinguish between  "dbapi_connection" - that is, you get a pep249 connection object, and "raw connection", you get whatever it is that's outside of SQLAlchemy.

**Comment by zzzeek** [comment]
"driver_connection" would need to be implemented by DefaultDialect as:

    def driver_connection(self, dbapi_conn):
        return dbapi_conn

then by asyncpg and the other asyncs like:

    def driver_connection(self, dbapi_conn):
        return dbapi_conn._connection

**Comment by CaselIT** [comment]
I meant a driver connection. will change the title

**Comment by CaselIT** [comment]
I think we could just make `_ConnectionFairy.connection` do the right thing, instead of adding yet another api that's similar but not quite the same as `raw_connection`.

What do you think?

**Comment by zzzeek** [comment]
I think connectionfairy.connection does the right thing now.   Asyncio has added a third (fourth?) level of "connection" to the equation, so we should add new API to access that.  We should not change existing api to suddenly return an object with an undefined API (ie whatever the async driver is giving us, which is not pep249).

**Comment by agronholm** [comment]
Is the existing API useful at all with asyncpg?

**Comment by CaselIT** [comment]
> 
> 
> We should not change existing api to suddenly return an object with an undefined API (ie whatever the async driver is giving us, which is not pep249).

it depends on how you view it. Until we supported just pep249 this reasoning makes sense. But since we have expanded the library to also support other driver with a different api, I think it would make more sense to change `_ConnectionFairy.connection` in "whatever the driver package used returned us".

For all pep249 compliant driver nothing would change, while for proxy drivers, like asyncpg, something useful would be returned.

I'm trying to make this change at the moment to see what it would look like



> 
> 
> Is the existing API useful at all with asyncpg?

not really. you would neet to use `_connection` to accesss the asyncpg connection. The same is true for the async version of mysql and sqlite

**Comment by zzzeek** [comment]
connectionfairy.connection has nothing to do with asyncio.  if you are not in the async API you should be getting pep249 connection that has the normal methods "cursor", and all of that.   we can add any amount of API to AsyncConnection to return wahtever people want.

**Comment by zzzeek** [comment]
i also think things would break internally / in the tests if we were to change this.   also, what would the new API be to get the actual pep-249 wrapper in asyncpg / aiomysql etc?  it would be inaccessible?

**Comment by CaselIT** [comment]
If we want to add a new api it would be simple, something like `_ConnectionFairy.driver_connection`.

Looking at what would happend if we change `connection` instead and add a `_ConnectionFairy.dbapi_connection` instead

**Comment by zzzeek** [comment]
it would need a deprecation path.   Code in the wild does connection.connection.connection.  renaming it to dbapi_connection is much more feasible than just switching it.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Surface driver connection object when using a proxied dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3041

**Comment by CaselIT** [comment]
> 
> 
> it would need a deprecation path. Code in the wild does connection.connection.connection. renaming it to dbapi_connection is much more feasible than just switching it.

So I've pushed an test implementation that does:
- `connection.connection.connection` is "what the driver returned us"
- `connection.connection.connection` is a pep249 compatible object that corresponds to `.connection`.

For normal dialect these two properties point to the same object.

This would break for users how are currently using an async driver and doing `connection.connection.connection._connection` or using `connection.connection.connection` as a pep249 object instead of whatever the driver returned. Considering that this asyncio is in beta it could be ok.

The alternative is to just leave `connection.connection.connection` as is, and add `connection.connection.driver_connection` with  "what the driver returned us"

All in all the internal did not require too much change
