### ISSUE TITLE
"mypy.nodes.ReturnStmt object expected" on @declared_attr in a @declarative_mixin stub

### ISSUE THREAD

**Issue by whiskeyriver** [sqlalchemy/sqlalchemy#6839]
### Describe the bug

When stubbing out a declarative_mixin, my declared_attr method would cause an "INTERNAL ERROR" for mypy.

The traceback showed that mypy expected a `ReturnStmt` when it was receiving a `PassStmt`. Updating the body of the declared_attr to return anything at all resolved the issue.

### To Reproduce

```python
from sqlalchemy.orm import Mapped, declared_attr, declarative_mixin

@declarative_mixin
class BaseMixin:
    @declared_attr
    def __tablename__(cls) -> Mapped[str]: ...
    def apply_update(self, **kwargs: object) -> None: ...
```

### A Workaround

To resolve this, I just needed a body _with any return_ for the declared_attr

```python
@declarative_mixin
class BaseMixin:
    @declared_attr
    def __tablename__(cls) -> Mapped[str]:
        return ...
    def apply_update(self, **kwargs: object) -> None: ...
```

If the class was not a @declared_mixin the @declared_attr did not cause an issue with an ellipses body.

### Error

```shell
stub-model.py:-1: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3911, in accept
  File "mypy/nodes.py", line 1866, in accept
  File "mypy/checkexpr.py", line 3511, in visit_lambda_expr
  File "mypy/nodes.py", line 1860, in expr
TypeError: mypy.nodes.ReturnStmt object expected; got mypy.nodes.PassStmt
stub-model.py:-1: : note: use --pdb to drop into pdb
```

### Versions

- OS: Linux 5.11.0-7620-generic
- Python: Python 3.8.11
- SQLAlchemy:
  - SQLAlchemy        1.4.22
  - sqlalchemy2-stubs 0.0.2a8
- Database: Postgres
- DBAPI: asyncpg2

**Comment by CaselIT** [comment]
Hi,

This is likely a bug in the mypy plugin, but I'm not sure it's worth fixing.
What is the rationale for defining a class like this?
```py
@declarative_mixin
class BaseMixin:
    @declared_attr
    def __tablename__(cls) -> Mapped[str]: ...
    def apply_update(self, **kwargs: object) -> None: ...
```

This has no effect in python. If it's just used as an interface, than it does not need to be declared as a `declarative_mixin`, the concrete subclasses would use the decorator

**Comment by whiskeyriver** [comment]
Ah, I can just leave the decorators off in my typing stubs? That definitely makes things easier.

**Comment by CaselIT** [comment]
I'm not clear what the use case you are trying to implement is.

Do you have a concrete `BaseMixin` and also a stub version of `BaseMixin`?

**Comment by whiskeyriver** [comment]
That's correct. We have a stubs package separate from our implementation.

**Comment by whiskeyriver** [comment]
I've spot checked the stubs with no decorators on the mixin and it seems to work fine.

Thank you, I appreciate the aid.

**Comment by CaselIT** [comment]
> I've spot checked the stubs with no decorators on the mixin and it seems to work fine.

That's nice to hear. Let us know if you encounter some issue.
I'm not sure if this case was ever considered when working on the plugin. Maybe we can document this if does not cause other issues.

cc @zzzeek @bryanforbes

**Comment by CaselIT** [comment]
since v2 will not use the mypy plugin to make everything work, this is a won't fix.
