### ISSUE TITLE
Can't use decorate `@deprecated` with typing?

### ISSUE THREAD

**Issue by imoyao** [sqlalchemy/sqlalchemy#6841]
### Describe the bug

while i use typing with decorate `@deprecated` i will get a `SyntaxError` unexpectedly ,it seems like that parse code incorrectly?

### To Reproduce

```python
from sqlalchemy.util.deprecations import deprecated

# raise error
@deprecated(version='0.0.1', message='bar')
def foo() -> None:
    pass

# works good
@deprecated(version='0.0.1', message='bar')
def foo():
    pass
```

### Error

```
  File "/root/fmt/backend/fmt/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 169, in decorate
    enable_warnings=enable_warnings,
  File "/root/fmt/backend/fmt/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 400, in _decorate_with_warning
    decorated = warned(func)
  File "/root/fmt/backend/fmt/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 198, in decorate
    decorated = _exec_code_in_env(code, env, fn.__name__)
  File "/root/fmt/backend/fmt/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 228, in _exec_code_in_env
    exec(code, env)
  File "<string>", line 1
    def foo() -> Non):
SyntaxError: invalid syntax
```

### Versions

- OS: CentOS Linux release 7.6.1810 (Core) 
- Python: 3.7.3
- SQLAlchemy: 1.4.22
- Database: MySQL
- DBAPI: mysql  Ver 14.14 Distrib 5.7.26, for linux-glibc2.12 (x86_64) using  EditLine wrapper

### Additional context

~~I'm using it in a flask(2.0.1) application,Does it matters?~~(I have test in a single test.py file and met the same error.)
```python
from sqlalchemy.util.deprecations import deprecated
from typing import NoReturn

# raise error
@deprecated(version='0.0.1', message='bar')
def foo() -> NoReturn:
    pass

# works good
@deprecated(version='0.0.1', message='bar')
def foo():
    pass

```

**Comment by CaselIT** [comment]
Hi,

That is not really a public api, so you should probably avoid using that.
That decorator dynamically generates a new function, and it appears that at the moment it does not work with types. I suppose it will get fixed for v2 where the plan is to add types in code to sqlalchemy.

**Comment by imoyao** [comment]
Okay,Thank you for your reply.

**Comment by zzzeek** [comment]
the "sqlalchemy.util" package is completely private, so there is no bug here.
