### ISSUE TITLE
Dogpile caching example local_session_caching not working

### ISSUE THREAD

**Issue by na-ka-na** [sqlalchemy/sqlalchemy#6858]
### Describe the bug

I'm looking at https://docs.sqlalchemy.org/en/14/orm/examples.html#module-examples.dogpile_caching

When I run `python -m examples.dogpile_caching.local_session_caching`

https://docs.sqlalchemy.org/en/14/_modules/examples/dogpile_caching/local_session_caching.html

It seems to me that the caching doesn't work. Query gets printed 3 times, I was expecting only 2 times. Does that example still work? Or am I not understanding things correctly?

### To Reproduce

```python
Download all the files from https://docs.sqlalchemy.org/en/14/orm/examples.html#module-examples.dogpile_caching

and run `python -m examples.dogpile_caching.local_session_caching`
```

### Error

Query gets printed 3 times, I was expecting only 2 times

### Versions

- OS: MacOSx
- Python: 3.7.7
- SQLAlchemy: 1.4.22
- Database: SQLlite
- DBAPI: ?

**Comment by zzzeek** [comment]
typo, please apply

```diff
diff --git a/examples/dogpile_caching/local_session_caching.py b/examples/dogpile_caching/local_session_caching.py
index 8f505ead72..ecee27cbec 100644
--- a/examples/dogpile_caching/local_session_caching.py
+++ b/examples/dogpile_caching/local_session_caching.py
@@ -76,7 +76,7 @@ if __name__ == "__main__":
     q = (
         Session.query(Person)
         .filter(Person.name == "person 10")
-        .execution_options(cache_options=FromCache("local_session"))
+        .options(FromCache("local_session"))
     )
 
     # load from DB

```

**Comment by na-ka-na** [comment]
Thanks @zzzeek another question, can you tell me what I'm doing wrong. I have a in memory dictionary backend (so the cache is across sessions). Everything is copied from the examples, the changes are:

```
cache_address_bits = (
    RelationshipCache(Person.addresses, "dictionarycache")
    .and_(RelationshipCache(Address.postal_code, "dictionarycache"))
    .and_(RelationshipCache(PostalCode.city, "dictionarycache"))
    .and_(RelationshipCache(City.country, "dictionarycache"))
)
```
Then I'm querying like so:
```
q = (
    Session.query(Person)
    .options(FromCache("dictionarycache"))
    .options(cache_address_bits)
)
people = q.all()
for person in people:
    person.format_full()
Session.remove()
```

But when I print the people, I get the same address
```
for person in people:
    print(person.format_full())

person 01	street 01	New York, 10003	United States
person 02	street 01	New York, 10003	United States
person 03	street 01	New York, 10003	United States
person 04	street 01	New York, 10003	United States
person 05	street 01	New York, 10003	United States
....
```
All the people have `street 01 New York` address

But if I query like so without the caching options:
```
q = (
    Session.query(Person)
)
people = q.all()
for person in people:
    person.format_full()
Session.remove()
```

Then I seem to get proper output
```
person 01	street 01	New York, 10003	United States
person 02	street 02	New York, 10006	United States
person 03	street 03	New York, 10006	United States
person 04	street 04	San Francisco, 94102	United States
person 05	street 05	Edmonton, T5J 1R9	Canada
.....
```

**Comment by zzzeek** [comment]
this is just another bug in the recipe

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**accommodate for untracked boundparam lambda in offline_string** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2993
