### ISSUE TITLE
Multiple with_polymorphic calls using single inh deosn't work.

### ISSUE THREAD

**Issue by dylan-thomas832** [sqlalchemy/sqlalchemy#6878]
### Describe the bug

I want to use single table inheritance to combine similar data types into one table, but I want to be able to query them efficiently by using single dispatch and `with_polymorphic()` to only query the data type subclass(es) that are relevant.

### To Reproduce

```python
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import with_polymorphic, relationship, declared_attr


Base = declarative_base()


class Employee(Base):
    __tablename__ = 'employees'
    id = Column(Integer, primary_key=True)
    name = Column(String(50))
    type = Column(String(20))

    __mapper_args__ = {
        'polymorphic_on':type,
        'polymorphic_identity':'employee'
    }

class Manager(Employee):
    manager_data = Column(String(50))

    @declared_attr
    def location_id(self):
        return Employee.__table__.c.get(
            'location_id',
            Column(Integer, ForeignKey('locations.id'))
        )

    # location_id = Column(Integer, ForeignKey('locations.id'), nullable=False)
    location = relationship("Location", lazy="joined", innerjoin=True)

    __mapper_args__ = {
        'polymorphic_identity':'manager'
    }

class Engineer(Employee):
    engineer_info = Column(String(50))

    __mapper_args__ = {
        'polymorphic_identity':'engineer'
    }

class Location(Base):
    __tablename__ = 'locations'

    id = Column(Integer, primary_key=True)
    name = Column(String(50))


# Aliases for single table inheritance
empl_engineer = with_polymorphic(Employee, [Engineer], aliased=True)
empl_manager = with_polymorphic(Employee, [Manager], aliased=True)


# Begin testing portion
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

# In-memory SQLite
sqlite_engine = create_engine("sqlite://", echo=True)
Base.metadata.create_all(sqlite_engine, checkfirst=True)
session_factory = sessionmaker(bind=sqlite_engine)


# Insert Location
from sqlalchemy.orm import Query

session = session_factory()
new_loc = Location(name="New York")
session.add(new_loc)
session.commit()
session.close()

# Test Location query
session = session_factory()
query = Query(Location)
location = query.with_session(session).one()
session.close()

# Insert Employee
session = session_factory()
new_engineer = Engineer(name="david", type="engineer", engineer_info="software")
session.add(new_engineer)
session.commit()
session.close()

# Insert Manager
new_manager = Manager(name="kevin", type="manager", manager_data="program 1", location=location)
session = session_factory()
session.add(new_manager)
session.commit()
session.close()

# Test Employee query
query = Query([empl_engineer])
session = session_factory()
engineers = query.with_session(session).all()
assert engineers
session.close()

# This fails if Manager is inserted into DB first
assert engineers[0].engineer_info == "software"


# Test Manager query
query = Query([empl_manager])
session = session_factory()
managers = query.with_session(session).all()
assert managers
session.close()

# This fails if Employee is inserted into DB first
assert managers[0].manager_data == "program 1"
```

### Error

2021-08-12 16:21:06,294 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-08-12 16:21:06,295 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("employees")
2021-08-12 16:21:06,295 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-08-12 16:21:06,295 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("employees")
2021-08-12 16:21:06,295 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-08-12 16:21:06,296 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("locations")
2021-08-12 16:21:06,296 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-08-12 16:21:06,296 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("locations")
2021-08-12 16:21:06,296 INFO sqlalchemy.engine.Engine [raw sql] ()
2021-08-12 16:21:06,297 INFO sqlalchemy.engine.Engine
CREATE TABLE locations (
        id INTEGER NOT NULL,
        name VARCHAR(50),
        PRIMARY KEY (id)
)

2021-08-12 16:21:06,297 INFO sqlalchemy.engine.Engine [no key 0.00013s] ()
2021-08-12 16:21:06,298 INFO sqlalchemy.engine.Engine
CREATE TABLE employees (
        id INTEGER NOT NULL,
        name VARCHAR(50),
        type VARCHAR(20),
        manager_data VARCHAR(50),
        location_id INTEGER,
        engineer_info VARCHAR(50),
        PRIMARY KEY (id),
        FOREIGN KEY(location_id) REFERENCES locations (id)
)

2021-08-12 16:21:06,298 INFO sqlalchemy.engine.Engine [no key 0.00017s] ()
2021-08-12 16:21:06,298 INFO sqlalchemy.engine.Engine COMMIT
2021-08-12 16:21:06,299 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-08-12 16:21:06,301 INFO sqlalchemy.engine.Engine INSERT INTO locations (name) VALUES (?)
2021-08-12 16:21:06,301 INFO sqlalchemy.engine.Engine [generated in 0.00020s] ('New York',)
2021-08-12 16:21:06,301 INFO sqlalchemy.engine.Engine COMMIT
2021-08-12 16:21:06,302 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-08-12 16:21:06,304 INFO sqlalchemy.engine.Engine SELECT locations.id AS locations_id, locations.name AS locations_name
FROM locations
2021-08-12 16:21:06,304 INFO sqlalchemy.engine.Engine [generated in 0.00017s] ()
2021-08-12 16:21:06,304 INFO sqlalchemy.engine.Engine ROLLBACK
2021-08-12 16:21:06,305 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-08-12 16:21:06,306 INFO sqlalchemy.engine.Engine INSERT INTO employees (name, type, engineer_info) VALUES (?, ?, ?)
2021-08-12 16:21:06,306 INFO sqlalchemy.engine.Engine [generated in 0.00019s] ('david', 'engineer', 'software')
2021-08-12 16:21:06,307 INFO sqlalchemy.engine.Engine COMMIT
2021-08-12 16:21:06,307 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-08-12 16:21:06,308 INFO sqlalchemy.engine.Engine INSERT INTO employees (name, type, manager_data, location_id) VALUES (?, ?, ?, ?)
2021-08-12 16:21:06,308 INFO sqlalchemy.engine.Engine [generated in 0.00019s] ('kevin', 'manager', 'program 1', 1)
2021-08-12 16:21:06,309 INFO sqlalchemy.engine.Engine COMMIT
2021-08-12 16:21:06,310 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-08-12 16:21:06,312 INFO sqlalchemy.engine.Engine SELECT employees_1.id AS employees_1_id, employees_1.name AS employees_1_name, employees_1.type AS employees_1_type, employees_1.engineer_info AS employees_1_engineer_info
FROM employees AS employees_1
2021-08-12 16:21:06,312 INFO sqlalchemy.engine.Engine [generated in 0.00020s] ()
2021-08-12 16:21:06,314 INFO sqlalchemy.engine.Engine ROLLBACK
2021-08-12 16:21:06,315 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2021-08-12 16:21:06,315 INFO sqlalchemy.engine.Engine SELECT employees_1.id AS employees_1_id, employees_1.name AS employees_1_name, employees_1.type AS employees_1_type, employees_1.engineer_info AS employees_1_engineer_info
FROM employees AS employees_1
2021-08-12 16:21:06,315 INFO sqlalchemy.engine.Engine [cached since 0.003535s ago] ()
2021-08-12 16:21:06,316 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "sql.py", line 114, in <module>
    assert managers[0].manager_data == "program 1"
AttributeError: 'Engineer' object has no attribute 'manager_data'

### Versions

- OS: Ubuntu 20.04 (WSL 2 on Windows 10)
- Python: 3.7.10
- SQLAlchemy: 1.4.22
- Database: SQLite
- DBAPI: sqlite3

### Additional context

The example is roughly similar to the use case, except `with_polymorphic()` can have multiple subclasses also.
The error depends on whether `Employee` or `Manager` is inserted into the DB first, as commented in the example.

**EDIT** This occurs with and without `aliased=True` argument

**Comment by zzzeek** [comment]
`with_polymorphic(Employee, [Manager], aliased=True)` indicates a hierarchy, of Employee objects and Manager subclasses.   if you want only Manager and not Employee, you'd query for either `Manager` or `aliased(Manager)` if you want to alias it.    does that answer the question here ?  I only skimmed briefly.

**Comment by dylan-thomas832** [comment]
I guess I should add more context.

Our actual code has several "`Employee`" types, and we want to be able to query the `Employee` table using `with_polymorphic()` to split out multiple subsets of the subclasses, depending on the "scope" of what/who is requesting the data.

```python
class TypeA(Employee):
    pass

class TypeB(Employee):
    pass

class TypeC(Employee):
    pass

class TypeD(Employee):
    pass

class TypeE(Employee):
    pass


# Dictionary mapping scopes to different `Employee` subsets
SCOPE_MAP = {
    "scope1": with_polymorphic(Employee, TypeA),
    "scope2": with_polymorphic(Employee, [TypeA, TypeB]),
    "scope3": with_polymorphic(Employee, [TypeC, TypeD, TypeE]),
}

# Generic function to properly query DB depending on the "scope"
getEmployee(session_factory, scope, datetime):
    # Select the appropriate `with_polymorphic()` set to use
    employee_alias = SCOPE_MAP[scope]

    # Or some more interesting common query
    query = Query(employee_alias ).filter(
        employee_alias.start_time<=datetime,
        employee_alias.end_time>=datetime,
    )
    
    # Query DB and return result
    session = session_factory()
    employees = query.with_session(session).all()
    session.close()
    return employees

### Example usage

# DB setup
sqlite_engine = create_engine("sqlite://", echo=True)
Base.metadata.create_all(sqlite_engine, checkfirst=True)
session_factory = sessionmaker(bind=sqlite_engine)

# Get employees using subset only with `TypeA`
employee_set1 = getEmployee(session_factory, "scope1", datetime)

# Get employees using subset with `TypeC`, `TypeD`, `TypeE`
employee_set3 = getEmployee(session_factory, "scope3", datetime)
```

The point is this allows us to call a generic `getEmployee()` function from several places, where different "sets" of `Employee` are relevant.

**Comment by zzzeek** [comment]
we dont have a built in construct for that as it would not apply cleanly to joined table inheritance.   since this is single table inh you would need to add a filtering clause manually:

    s.query(Employee).filter(Employee.type.in_(["typea", "typeb", "typec"]))

**Comment by zzzeek** [comment]
> The point of my original issue is that calling with_polymorphic() twice using the same base class seems to break stuff, and it's not clear why, or documented that it will happen.

I'm not seeing how this "breaks".  the with_polymorphic() construct queries for hierarchies and the result in your test case is expected.

**Comment by zzzeek** [comment]
I think really the main point here is that with_polymorphic() is mostly for joined table inheritance, for single table it mostly is just a way to access columns that might be mapped only to Engineer or Manager in the query but otherwise isn't going to change the *kinds* of objects that are returned.

**Comment by zzzeek** [comment]
if you can show me where in the docs here: https://docs.sqlalchemy.org/en/14/orm/inheritance_loading.html?highlight=with_polymorphic#with-polymorphic it's implied that "with_polymorphic" is going to exclude entity types, which it doesn't do at all, we can try to clarify that.

**Comment by dylan-thomas832** [comment]
> we dont have a built in construct for that as it would not apply cleanly to joined table inheritance. since this is single table inh you would need to add a filtering clause manually:
> 
> ```
> s.query(Employee).filter(Employee.type.in_(["typea", "typeb", "typec"]))
> ```

This definitely helps, thanks.

As for the first original example, I still don't get why I am getting `AttributeError: 'Engineer' object has no attribute 'manager_data'` when the object I am querying is supposed to be returning a `Manager`. I re-tested without using `empl_engineer = with_polymorphic(Employee, [Engineer], aliased=True)` at all, and it actually causes the same error.

**Comment by zzzeek** [comment]
if you query for Manager, the ORM should add a WHERE clause that will limit to just rows that are Manager.  If you query for Employee, or with_polymorphic(Employee, <anything>), you will get *all* rows from "employee", including those that match up as an "engineer".

**Comment by dylan-thomas832** [comment]
I took some extra time to tinker with my examples as well as re-reading the full documentation on `with_polymorphic()`. I believe I now know where my misunderstanding lies, and I appreciate your patience in helping me to understand.

As I understand it, `with_polymorphic()` simply changes a query of a table to include the set of columns defined by the designated subclass tables (second argument) in the query and also allows eager loading of those columns, but it will always return ALL rows that match the query. This can even include rows (sub-classes) that don't have the columns defined by the `AliasedClass` returned by the call to `with_polymorphic()`. Does this sound correct?

I guess my confusion was in that I thought/assumed (incorrectly) that it would include the sub-classes' columns in the query AND down-select/filter out the (irrelevant) sub-classes (those that have `NULL` in those columns). I see that it doesn't actually state that anywhere in the documentation, and therefore it was an incorrect assumption, but I do wonder if there's a way to improve the clarity of the function's behavior.

My suggestion would be to include some concrete demonstration code in the `with_polymorphic()` documentation using the "Employee/Engineer/Manager" example. I know the documentation includes the generated SQL statements as examples, but including concrete Python examples showing actual objects/data returned by queries using `with_polymorphic()` might make it easier to understand. I found the inheritance examples [here](https://docs.sqlalchemy.org/en/14/orm/examples.html#inheritance-mapping-recipes), but IMO they don't do a good job explaining how calls to `with_polymorphic()` with different sets of sub-classes affect the query result.

Thanks again for your help!

**Comment by zzzeek** [comment]
> 
> As I understand it, `with_polymorphic()` simply changes a query of a table to include the set of columns defined by the designated subclass tables (second argument) in the query and also allows eager loading of those columns, but it will always return ALL rows that match the query. This can even include rows (sub-classes) that don't have the columns defined by the `AliasedClass` returned by the call to `with_polymorphic()`. Does this sound correct?

that's what it does, yep.  it's both an "eager loading" construct for joined inheritance (the main thing people use it for), and a querying construct when a query needs to refer to columns that are specific to sub-classes, while still querying against a superclass and returning instances within that whole superclass' hierarcy (less common).

> 
> I guess my confusion was in that I thought/assumed (incorrectly) that it would include the sub-classes' columns in the query AND down-select/filter out the (irrelevant) sub-classes (those that have `NULL` in those columns). I see that it doesn't actually state that anywhere in the documentation, and therefore it was an incorrect assumption, but I do wonder if there's a way to improve the clarity of the function's behavior.

the problem is that of the three types of inheritance, concrete / joined and single, only single is the one where there is infrastructure right now to limit based on "type IN (values)" within the ORM's mechanics.  I guess this style of filtering could work for joined and concrete as well but the use case of loading multiple sibling classes wasn't something we've ever considered; it is after all easy enough to do the filter()/where() discussed and you could actually stick that on top of any of the styles of inheritance.   Building it into with_poly() or a similar construct might be a nice feature to have though adding new polymorphic features tends to be **really** hard because there are so many crazy edge cases to all of this, so probably stick with the custom filter/where->IN thing for now.

> 
> My suggestion would be to include some concrete demonstration code in the `with_polymorphic()` documentation using the "Employee/Engineer/Manager" example. I know the documentation includes the generated SQL statements as examples, but including concrete Python examples showing actual objects/data returned by queries using `with_polymorphic()` might make it easier to understand. 

OK, sometimes just a "tip" box that says, "with_polymorphic does not **limit** the types of objects returned, it only affects the columns available in each row", those tend to get people's attention. 


> I found the inheritance examples [here](https://docs.sqlalchemy.org/en/14/orm/examples.html#inheritance-mapping-recipes), but IMO they don't do a good job explaining how calls to `with_polymorphic()` with different sets of sub-classes affect the query result.

the examples are all pretty old and while I keep them maintained for API use, they are not as user friendly as newer documentation seeks to be.


> 
> Thanks again for your help!
