### ISSUE TITLE
Using posgresql.ARRAY.overlap() in a multiple join scenario gives a cartesian product warning

### ISSUE THREAD

**Issue by thomas-mckay** [sqlalchemy/sqlalchemy#6886]
### Describe the bug

A query that joins three entities on `ARRAY.overlap` conditions triggers a cartesian product warning despite the correct SQL being emitted.

### To Reproduce

```python
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, aliased


Base = declarative_base()


class Foo(Base):
    __tablename__ = 'foo'

    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    ancestors_ids = sa.Column(postgresql.ARRAY(sa.Integer), nullable=False, server_default='{}')
    is_bar = sa.Column(sa.Boolean, nullable=False)


engine = sa.create_engine('postgresql://user:pass@localhost:5432/db')
# engine.execute('drop table foo;')
Base.metadata.create_all(engine)
session = Session(engine)

ancestor = aliased(Foo, name='ancestor')
descendant = aliased(Foo, name='descendant')
qs = (
    session
    .query(Foo)
    .with_entities(
        Foo.id,
        Foo.is_bar,
        sa.func.bool_or(ancestor.is_bar).label('ancestor_is_bar'),
        sa.func.bool_or(descendant.is_bar).label('descendant_is_bar'),
    )
    .join(
        ancestor,
        sa.and_(
            Foo.ancestors_ids.overlap(postgresql.array((ancestor.id,))),
            ancestor.is_bar.is_(True),
        ),
        isouter=True,
    )
    .join(
        descendant,
        sa.and_(
            descendant.ancestors_ids.overlap(postgresql.array((Foo.id,))),
            descendant.is_bar.is_(True),
        ),
        isouter=True,
    )
    .group_by(
        Foo.id,
        Foo.is_bar,
    )
)
print(qs)

# SELECT
#     foo.id AS foo_id,
#     foo.is_bar AS foo_is_bar,
#     bool_or(ancestor.is_bar) AS ancestor_is_bar,
#     bool_or(descendant.is_bar) AS descendant_is_bar
# FROM foo
#     LEFT OUTER JOIN foo AS ancestor
#         ON foo.ancestors_ids && ARRAY[ancestor.id] AND ancestor.is_bar IS true
#     LEFT OUTER JOIN foo AS descendant
#         ON descendant.ancestors_ids && ARRAY[foo.id] AND descendant.is_bar IS true
# GROUP BY
#     foo.id,
#     foo.is_bar

print(qs.all())
```

### Error

SAWarning: SELECT statement has a cartesian product between FROM element(s) "ancestor", "foo" and FROM element "descendant".  Apply join condition(s) between each element to resolve.

>    print(qs.all())

### Versions

- OS: Arch Linux 5.4 (Manjaro)
- Python: 3.9.6
- SQLAlchemy: 1.4.22
- Database: Postgresql 13.3
- DBAPI: psycopg2-binary 2.9.1

### Additional context

I've read https://github.com/sqlalchemy/sqlalchemy/issues/5924 as it seemed correlated but after some testing I don't think it is, as this issue was particular to the type of `JOIN` used.

Here, changing the join type from `isouter=True` to `isouter=False` still triggers the warning. Moreover, replacing the `ancestors_ids` array column on `Foo` by a `parent_id` integer column and then replacing the `.overlap` join conditions by a simple `id`/`parent_id` equality doesn't trigger the warning. This seems to indicate that the problem comes specifically from using `.overlap` in a multiple join scenario and not from the join types themselves.

Finally, I don't know if that helps but while trying to ignore the warnings in pytest I ran into a bit of a quirk: the warning's message changes with every execution (assuming the .pyc have been recreated):
`SELECT statement has a cartesian product between FROM element(s) "foo", "ancestor" and FROM element "descendant"`
`SELECT statement has a cartesian product between FROM element(s) "descendant" and FROM element "ancestor"`
`SELECT statement has a cartesian product between FROM element(s) "descendant" and FROM element "foo"`
After a good dozen tries I got these three distinct messages which all point to the second join (the one with descendant) being the triggering point.

**Comment by zzzeek** [comment]
this is something simple, for temporary workaround you can monkeypatch:

```diff
diff --git a/lib/sqlalchemy/dialects/postgresql/array.py b/lib/sqlalchemy/dialects/postgresql/array.py
index d8e54ae0c4..1b036ac323 100644
--- a/lib/sqlalchemy/dialects/postgresql/array.py
+++ b/lib/sqlalchemy/dialects/postgresql/array.py
@@ -153,11 +153,11 @@ class array(expression.ClauseList, expression.ColumnElement):
             return self
 
 
-CONTAINS = operators.custom_op("@>", precedence=5)
+CONTAINS = operators.custom_op("@>", precedence=5, is_comparison=True)
 
-CONTAINED_BY = operators.custom_op("<@", precedence=5)
+CONTAINED_BY = operators.custom_op("<@", precedence=5, is_comparison=True)
 
-OVERLAP = operators.custom_op("&&", precedence=5)
+OVERLAP = operators.custom_op("&&", precedence=5, is_comparison=True)
```

**Comment by zzzeek** [comment]
this is also kind of general to the linter itself, as we support not emitting a warning for query like this:

"SELECT * FROM a JOIN b ON true"

but then it doesn't work for:  "SELECT * FROM a JOIN b ON true JOIN c ON true"

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**fix linter JOIN logic; fix PostgreSQL ARRAY op comparison** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3003
