### ISSUE TITLE
selectinload (others?) don't use the given query options as part of the cache key, or no way to propagate execution options

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6887]
this is really kind of an extension of #6881 and is here revealed by #6885.

A means of sending a message to the selectinloader would use the program below:

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import selectinload
from sqlalchemy.orm import Session

from sqlalchemy.orm.interfaces import UserDefinedOption
from sqlalchemy.orm.session import ORMExecuteState
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs=[B()]))
s.commit()

class SetShardOption(UserDefinedOption):
    propagate_to_loaders = True

    def _gen_cache_key(self, anon_map, bindparams):
        return (self.payload, )


@event.listens_for(s, "do_orm_execute")
def go(context: ORMExecuteState):
    for elem in context.user_defined_options:
        if isinstance(elem, SetShardOption):
            context.update_execution_options(_sa_shard_id=elem.payload)
            print(f"set shard id to: {elem.payload}")

stmt = select(A).options(selectinload(A.bs), SetShardOption("some_shard"))
s.execute(stmt).all()


print("----------------------")

stmt = select(A).options(selectinload(A.bs), SetShardOption("some_other_shard"))
s.execute(stmt).all()
```

however, lambda caching defeats this even if query caching is turned off, because we don't track on the options.  needs this patch:

```diff
diff --git a/lib/sqlalchemy/orm/strategies.py b/lib/sqlalchemy/orm/strategies.py
index 587daa332c..aab4796861 100644
--- a/lib/sqlalchemy/orm/strategies.py
+++ b/lib/sqlalchemy/orm/strategies.py
@@ -2971,7 +2971,8 @@ class SelectInLoader(PostLoader, util.MemoizedSlots):
         q = q.add_criteria(
             lambda q: q.options(*options)._update_compile_options(
                 {"_current_path": effective_path}
-            )
+            ),
+            track_on=options
         )
 
         if context.populate_existing:

```

it's not clear if this actually fixes #6881 also, which would be interesting.

**Comment by zzzeek** [comment]
but also not to mention for a sharding scenario, the "shard id" is not at all appropriate for a cache key.   the loaders should have some means of propagating execution options that is outside of caching.      if ORMExecuteState could reveal the parent query, that is one way this could be possible.

**Comment by zzzeek** [comment]
I'm incorrect about that patch, the lambda tracking seems to work for the loader option.   it's still just not ideal that a transitory thing like 'shard_id' would need to be in the cache key, and this might affect the dogpile recipe also, where we are not returning a cache key for the cache option so...selectinload is broke there too ?

**Comment by zzzeek** [comment]
why does selectinload cache the query when i use this option??  main query is "no key", where's the cache key coming from??

```py
class SetShardOption(UserDefinedOption):
    propagate_to_loaders = True

    _cache_key_traversal = None
```

**Comment by zzzeek** [comment]
this is a bug in lambdas - if an uncachable element is in the query, lambda tracking should see that and not cache.   this has to be fixed first.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**honor NO_CACHE in lambdas** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3004

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**honor NO_CACHE in lambdas** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3004

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**send user defined options from the current query** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3007
