### ISSUE TITLE
consider removing lambda query use from ORM

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6889]
looking into issues like #6887 and #6881, the use of lambdas makes working on these internals **extremely** difficult.   if we look at the cases where we are building up these lambda queries, we might consider that the overhead of building up a select() is very low, **If** we can bypass the coercions step.   I would propose trying a branch where we build up straight select() objects, making use of direct population of elements to bypass coercions.   I'm really suspecting that we are not getting any real performance bump from lambdas to justify the complexity here.

**Comment by zzzeek** [comment]
the most expensive coercion is the "binary" coercion we do when we create a WHERE clause; for a lazy loader, we aren't doing this coercion in any case.

in the perf suite, I get the same performance from both of these runs, this is not even trying to be very optimized:

```py
@Profiler.profile
def test_orm_query_new_style_using_external_lambdas(n):
    """new style ORM select() of the full entity w/ external lambdas."""

    session = Session(bind=engine)
    for id_ in random.sample(ids, n):

        stmt = lambdas.lambda_stmt(lambda: future_select(Customer))
        stmt += lambda s: s.where(Customer.id == id_)
        session.execute(stmt).scalar_one()

@Profiler.profile
def test_orm_query_new_style_using_raw_construction(n):
    """new style ORM select() of the full entity w/ raw construction"""

    session = Session(bind=engine)
    for id_ in random.sample(ids, n):

        stmt = select(Customer)
        stmt = stmt.where(lambda: Customer.id == id_)
        session.execute(stmt).scalar_one()
```

that is, the ``Customer.id == id_`` seems to be the big difference between them, so if i keep that as a lambda, the times are 1.72 sec vs. 1.86 sec, negligble.   lazy loader already has the criteria built up.

if I do totally raw Select in a more inlined way, this runs in 1.6 sec.   no lambdas needed, which will be helpful to simplify how the ORM does things:

```py
from sqlalchemy.sql.expression import Select
from sqlalchemy import inspect

@Profiler.profile
def test_orm_query_new_style_using_raw_construction(n):
    """new style ORM select() of the full entity w/ raw construction"""

    table = inspect(Customer).__clause_element__()

    crit = Customer.id == 10
    session = Session(bind=engine)
    for id_ in random.sample(ids, n):

        stmt = Select.__new__(Select)
        stmt.__dict__.update(
            _raw_columns=[table],
            _propagate_attrs=table._propagate_attrs,
            _label_style=LABEL_STYLE_DISAMBIGUATE_ONLY,
            _where_criteria=(crit, )
        )
        session.execute(stmt).scalar_one()
```

if we perhaps add some helper constructors to Select and keep them underscored, we can basically just inline the production of Select for the few places we are doing it now and it won't be impossible to debug / expand upon.     right now in https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3001 im looking at such complexity that using `stmt.compile()` will not give you the correct parameters without taking external parameters into account, which was intended to be something that would only be needed if caching were turned on.   but because the "stale" parameters are still stuck in the lambda callables, there's this whole second level of caching that I can barely keep my head around.    I'd like this code to be maintainable by others.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**remove lambda caching from ORM** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3006
