### ISSUE TITLE
support auto migrate for compatible model change

### ISSUE THREAD

**Issue by foolcage** [sqlalchemy/sqlalchemy#6896]
### Describe the use case

I know migration is supported by alembic, but most of time it's too complex.
Could we support compatible migration in sqlalchemy directly?
e.g
https://stackoverflow.com/questions/2103274/sqlalchemy-add-new-field-to-class-and-create-corresponding-column-in-table

In fact, in the real wolrd, most of time we only add columns in db, the most of the use cases is:
add column in model -> add column in database

now the create table is:
    def create_all(self, bind=None, tables=None, checkfirst=True):

could we add one argument
migration_add_column -> means if the table exists, we check it and if the model only add columns,  generate ddl to alter table add colum

### Databases / Backends / Drivers targeted

mysql, sqlite

### Example Use

migration_add_column -> we check it and if the model only add columns,  generate ddl to alter table add colum

**Comment by CaselIT** [comment]
Hi,

I'm personally -1 on this, but we should wait @zzzeek opinion.

What may be useful is a way of using alembic in a simple one off way. Something like 
```py
with alembic.one_off_config(conn=conn, ...):
  alembic.op.add_column('foo', sa.Column('bar', sa.Integer))
```
I don't think it's possible to use alembic like this at the moment.

**Comment by zzzeek** [comment]
hey there.

Sorry, this would be totally out of scope for SQLAlchemy and overall such an argument would be ineffective in many cases, the issue of "add column" is not nearly that simple in the general case.

You can of course implement a recipe to run the "ALTER TABLE ADD COLUMN" DDL yourself, using an API like [DDL](https://docs.sqlalchemy.org/en/14/core/ddl.html?highlight=ddl).

> I don't think it's possible to use alembic like this at the moment.

Alembic directives can be run directly pretty much the same as you illustrated there, see the example at https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.migration.MigrationContext .
