### ISSUE TITLE
Session.refresh on objects with joinedload relationship not behaving as expected

### ISSUE THREAD

**Issue by mgu** [sqlalchemy/sqlalchemy#6919]
### Describe the bug

When _refreshing_ an object that has a joinedload relationship, updated data for the related objects are fetched from the database (JOIN query) but the instances are not properly updated.
This happens when the related objects were already in the session.

My workaround is to use `expire_all()` instead of refreshing the object.

### To Reproduce

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", back_populates="a", lazy="joined")


class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    data = Column(String)
    a_id = Column(Integer, ForeignKey("a.id"), index=True)
    a = relationship("A", back_populates="bs")

    def __repr__(self):
        return f"<B data={self.data} a={self.a_id}>"


e = create_engine("sqlite://", echo=True)

Base.metadata.create_all(e)

s = Session(e)

# create data
s.add_all([A(bs=[B(data="b1"), B(data="b2")])])
s.commit()

# get object into session s
a = s.query(A).get(1)
b = s.query(B).get(1)

# modify b in another session
s2 = Session(e)
a2 = s2.query(A).get(1)
a2.bs[0].data = "b1mod"
s2.commit()

# Try to refresh `a`
s.refresh(a)
# same behavior using `a = s.query(A).get(1)` instead of refresh
# the next assertion fails: even if bs[0] is fetched in the JOIN, it's not
# properly (eagerly ?) updated because `b` was already in the session `s`
assert a.bs[0].data == "b1mod"
assert a.bs[1].data == "b2"
```

### Error

```py
Traceback (most recent call last):
  File "test.py", line 57, in <module>
    assert a.bs[0].data == "b1mod"
AssertionError

```

### Versions

- OS: ArchLinux
- Python: 3.9.6
- SQLAlchemy: master or 1.4.23
- Database: sqlite
- DBAPI:

**Comment by zzzeek** [comment]
hi this is documented at the note at [session.refresh()](https://docs.sqlalchemy.org/en/14/orm/session_api.html?highlight=session%20refresh#sqlalchemy.orm.Session.refresh):

> While the Session.refresh() method is capable of refreshing both column and relationship oriented attributes, its primary focus is on refreshing of local column-oriented attributes on a single instance. For more open ended “refresh” functionality, including the ability to refresh the attributes on many objects at once while having explicit control over relationship loader strategies, use the populate existing feature instead.

you want to use [populate_existing](https://docs.sqlalchemy.org/en/14/orm/queryguide.html#orm-queryguide-populate-existing) so that you can specify the level of "rewrite attributes" per query rather than per-object.

**Comment by zzzeek** [comment]
here's [populate_existing](https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.populate_existing) for ORM query, this is not a new method

**Comment by mgu** [comment]
thanks a lot for your quick answer, I'll give it a try ASAP

**Comment by mgu** [comment]
I can indeed replace `s.refresh(a)` by `s.query(A).populate_existing().get(a.id)`
