### ISSUE TITLE
Azure SQL connection using mssql+pyodbc fails with some passwords

### ISSUE THREAD

**Issue by dctech1000** [sqlalchemy/sqlalchemy#6922]
### Describe the bug

The issue is with pyodbc and sqlalchemy connections.
There is a set of passwords that work with both pyodbc and SQLAlchemy.

However, there is atleast one bad password that works with pyodbc but does not work with SQLAlchemy.

With the bad_password, the connection fails with a login error:
('28000', "[28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user '***'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user '***'. (18456)")

Problem can be reproduced with Azure SQL Database and with the password examples below.

### To Reproduce

```python
# change values as needed
server = "tcp:somedb.database.windows.net,1433" 
database = "master"
user = "myusername"  

# good_passwords all work with both pyODBC and SQLAlchemy
# bad_password only works with pyODBC and does NOT work with SQLAlchemy

bad_password  = "{pmc$x0zdsp298K7Mlq*E%E0GRzr4JRuZ}"   # note has the % 

good_password = "{pmc$x0zdsp298K7Mlq*EE0GRzr4JRuZ}"  # does not have a %
good_password = "{pmc$x0zdsp298K7Mlq*EE0GRzr4JR%uZ}"   # % in a different place
good_password = "hello123%"   
good_password = "hello1$2*3%" 
good_password = "pmc$x0q*E%E" 

password = bad_password

connect_str = ( "Driver={SQL Server};"
                f"Server={server};"
                f"Database={database};"
                f"Uid={user};"
                f"Pwd={password};"
                "TRUSTED_CONNECTION=no"
             )
dburl = URL.create("mssql+pyodbc", query={"odbc_connect":connect_str})
print ("connect_str=", connect_str)
print ("dburl=", dburl)


sql = "select CURRENT_USER"

# Direct pyODBC - works with all these passwords
with pyodbc.connect(connect_str) as conn:
    with conn.cursor() as cursor:
        cursor.execute(sql)
        row = cursor.fetchone()
        print ("PYODBC Results=", row)

# SQLAlchemy - only works with good_passwords. Does not work with bad_password
engine  = create_engine(dburl)
dbsession  =  Session(engine)
results = dbsession.execute(text(sql))
for row in results:
    print ("SQLAlchemy Results=", row)
```

### Error

---------------------------------------------------------------------------
InterfaceError                            Traceback (most recent call last)
~\anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _wrap_pool_connect(self, fn, connection)
   3140         try:
-> 3141             return fn()
   3142         except dialect.dbapi.Error as e:

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in connect(self)
    300         """
--> 301         return _ConnectionFairy._checkout(self)
    302 

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in _checkout(cls, pool, threadconns, fairy)
    754         if not fairy:
--> 755             fairy = _ConnectionRecord.checkout(pool)
    756 

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in checkout(cls, pool)
    418     def checkout(cls, pool):
--> 419         rec = pool._do_get()
    420         try:

~\anaconda3\lib\site-packages\sqlalchemy\pool\impl.py in _do_get(self)
    144                 with util.safe_reraise():
--> 145                     self._dec_overflow()
    146         else:

~\anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py in __exit__(self, type_, value, traceback)
     69             if not self.warn_only:
---> 70                 compat.raise_(
     71                     exc_value,

~\anaconda3\lib\site-packages\sqlalchemy\util\compat.py in raise_(***failed resolving arguments***)
    210         try:
--> 211             raise exception
    212         finally:

~\anaconda3\lib\site-packages\sqlalchemy\pool\impl.py in _do_get(self)
    141             try:
--> 142                 return self._create_connection()
    143             except:

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in _create_connection(self)
    246 
--> 247         return _ConnectionRecord(self)
    248 

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in __init__(self, pool, connect)
    361         if connect:
--> 362             self.__connect(first_connect_check=True)
    363         self.finalize_callback = deque()

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in __connect(self, first_connect_check)
    604             with util.safe_reraise():
--> 605                 pool.logger.debug("Error on connect(): %s", e)
    606         else:

~\anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py in __exit__(self, type_, value, traceback)
     69             if not self.warn_only:
---> 70                 compat.raise_(
     71                     exc_value,

~\anaconda3\lib\site-packages\sqlalchemy\util\compat.py in raise_(***failed resolving arguments***)
    210         try:
--> 211             raise exception
    212         finally:

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in __connect(self, first_connect_check)
    598             self.starttime = time.time()
--> 599             connection = pool._invoke_creator(self)
    600             pool.logger.debug("Created new connection %r", connection)

~\anaconda3\lib\site-packages\sqlalchemy\engine\create.py in connect(connection_record)
    577                         return connection
--> 578             return dialect.connect(*cargs, **cparams)
    579 

~\anaconda3\lib\site-packages\sqlalchemy\engine\default.py in connect(self, *cargs, **cparams)
    558         # inherits the docstring from interfaces.Dialect.connect
--> 559         return self.dbapi.connect(*cargs, **cparams)
    560 

InterfaceError: ('28000', "[28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user '**user**'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user '**user**'. (18456)")

The above exception was the direct cause of the following exception:

InterfaceError                            Traceback (most recent call last)
<ipython-input-39-0cacce1b045b> in <module>
     41 engine  = create_engine(dburl)
     42 dbsession  =  Session(engine)
---> 43 results = dbsession.execute(text(sql))
     44 for row in results:
     45     print ("SQLAlchemy Results=", row)

~\anaconda3\lib\site-packages\sqlalchemy\orm\session.py in execute(self, statement, params, execution_options, bind_arguments, _parent_execute_state, _add_event, **kw)
   1667         bind = self.get_bind(**bind_arguments)
   1668 
-> 1669         conn = self._connection_for_bind(bind, close_with_result=True)
   1670         result = conn._execute_20(statement, params or {}, execution_options)
   1671 

~\anaconda3\lib\site-packages\sqlalchemy\orm\session.py in _connection_for_bind(self, engine, execution_options, **kw)
   1517     def _connection_for_bind(self, engine, execution_options=None, **kw):
   1518         if self._transaction is not None or self._autobegin():
-> 1519             return self._transaction._connection_for_bind(
   1520                 engine, execution_options
   1521             )

~\anaconda3\lib\site-packages\sqlalchemy\orm\session.py in _connection_for_bind(self, bind, execution_options)
    745                     )
    746             else:
--> 747                 conn = bind.connect()
    748                 local_connect = True
    749 

~\anaconda3\lib\site-packages\sqlalchemy\engine\base.py in connect(self, close_with_result)
   3093         """
   3094 
-> 3095         return self._connection_cls(self, close_with_result=close_with_result)
   3096 
   3097     @util.deprecated(

~\anaconda3\lib\site-packages\sqlalchemy\engine\base.py in __init__(self, engine, connection, close_with_result, _branch_from, _execution_options, _dispatch, _has_events)
     89                 connection
     90                 if connection is not None
---> 91                 else engine.raw_connection()
     92             )
     93 

~\anaconda3\lib\site-packages\sqlalchemy\engine\base.py in raw_connection(self, _connection)
   3172 
   3173         """
-> 3174         return self._wrap_pool_connect(self.pool.connect, _connection)
   3175 
   3176 

~\anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _wrap_pool_connect(self, fn, connection)
   3142         except dialect.dbapi.Error as e:
   3143             if connection is None:
-> 3144                 Connection._handle_dbapi_exception_noconnection(
   3145                     e, dialect, self
   3146                 )

~\anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _handle_dbapi_exception_noconnection(cls, e, dialect, engine)
   2001             util.raise_(newraise, with_traceback=exc_info[2], from_=e)
   2002         elif should_wrap:
-> 2003             util.raise_(
   2004                 sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2005             )

~\anaconda3\lib\site-packages\sqlalchemy\util\compat.py in raise_(***failed resolving arguments***)
    209 
    210         try:
--> 211             raise exception
    212         finally:
    213             # credit to

~\anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _wrap_pool_connect(self, fn, connection)
   3139         dialect = self.dialect
   3140         try:
-> 3141             return fn()
   3142         except dialect.dbapi.Error as e:
   3143             if connection is None:

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in connect(self)
    299 
    300         """
--> 301         return _ConnectionFairy._checkout(self)
    302 
    303     def _return_conn(self, record):

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in _checkout(cls, pool, threadconns, fairy)
    753     def _checkout(cls, pool, threadconns=None, fairy=None):
    754         if not fairy:
--> 755             fairy = _ConnectionRecord.checkout(pool)
    756 
    757             fairy._pool = pool

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in checkout(cls, pool)
    417     @classmethod
    418     def checkout(cls, pool):
--> 419         rec = pool._do_get()
    420         try:
    421             dbapi_connection = rec.get_connection()

~\anaconda3\lib\site-packages\sqlalchemy\pool\impl.py in _do_get(self)
    143             except:
    144                 with util.safe_reraise():
--> 145                     self._dec_overflow()
    146         else:
    147             return self._do_get()

~\anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py in __exit__(self, type_, value, traceback)
     68             self._exc_info = None  # remove potential circular references
     69             if not self.warn_only:
---> 70                 compat.raise_(
     71                     exc_value,
     72                     with_traceback=exc_tb,

~\anaconda3\lib\site-packages\sqlalchemy\util\compat.py in raise_(***failed resolving arguments***)
    209 
    210         try:
--> 211             raise exception
    212         finally:
    213             # credit to

~\anaconda3\lib\site-packages\sqlalchemy\pool\impl.py in _do_get(self)
    140         if self._inc_overflow():
    141             try:
--> 142                 return self._create_connection()
    143             except:
    144                 with util.safe_reraise():

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in _create_connection(self)
    245         """Called by subclasses to create a new ConnectionRecord."""
    246 
--> 247         return _ConnectionRecord(self)
    248 
    249     def _invalidate(self, connection, exception=None, _checkin=True):

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in __init__(self, pool, connect)
    360         self.__pool = pool
    361         if connect:
--> 362             self.__connect(first_connect_check=True)
    363         self.finalize_callback = deque()
    364 

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in __connect(self, first_connect_check)
    603         except Exception as e:
    604             with util.safe_reraise():
--> 605                 pool.logger.debug("Error on connect(): %s", e)
    606         else:
    607             if first_connect_check:

~\anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py in __exit__(self, type_, value, traceback)
     68             self._exc_info = None  # remove potential circular references
     69             if not self.warn_only:
---> 70                 compat.raise_(
     71                     exc_value,
     72                     with_traceback=exc_tb,

~\anaconda3\lib\site-packages\sqlalchemy\util\compat.py in raise_(***failed resolving arguments***)
    209 
    210         try:
--> 211             raise exception
    212         finally:
    213             # credit to

~\anaconda3\lib\site-packages\sqlalchemy\pool\base.py in __connect(self, first_connect_check)
    597         try:
    598             self.starttime = time.time()
--> 599             connection = pool._invoke_creator(self)
    600             pool.logger.debug("Created new connection %r", connection)
    601             self.connection = connection

~\anaconda3\lib\site-packages\sqlalchemy\engine\create.py in connect(connection_record)
    576                     if connection is not None:
    577                         return connection
--> 578             return dialect.connect(*cargs, **cparams)
    579 
    580         creator = pop_kwarg("creator", connect)

~\anaconda3\lib\site-packages\sqlalchemy\engine\default.py in connect(self, *cargs, **cparams)
    557     def connect(self, *cargs, **cparams):
    558         # inherits the docstring from interfaces.Dialect.connect
--> 559         return self.dbapi.connect(*cargs, **cparams)
    560 
    561     def create_connect_args(self, url):

InterfaceError: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user '**user**'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user '**user**'. (18456)")
(Background on this error at: http://sqlalche.me/e/14/rvf5)

### Versions

- OS: Windows 10
- Python: Python 3.9.5
- SQLAlchemy:1.4.19           py39h2bbff1b_0
- Database: Azure SQL Server Microsoft SQL Azure (RTM) - 12.0.2000.8 \n\tJul 23 2021 13:14:19 \n\tCopyright (C) 2019 Microsoft Corporation\n
- DBAPI:

**Comment by CaselIT** [comment]
Hi,

This is expected and is documented. Special characters meed to be urlescaped in the password.

**Comment by dctech1000** [comment]
Thanks you - it turns out I needed to do **double escaping**... i.e. that did the trick.  I had done one or the other which did not work.

connect_str = ( "Driver={SQL Server};"
                f"Server={server};"
                f"Database={database};"
                f"Uid={user};"
                f"Pwd=**{urllib.parse.quote_plus(password)};"**
                "TRUSTED_CONNECTION=no"
             )

dburl = URL.create("mssql+pyodbc", query={"odbc_connect":**urllib.parse.quote_plus(connect_str)**})

**Comment by CaselIT** [comment]
Interesting, maybe pyodbc is also unescaping them.

Glad you figured it out though.
