### ISSUE TITLE
clean up session.begin() and add a no-autobegin option

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6928]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/6921

session.begin() seems to rely on _autobegin() in a weird way and this should be clarified:

```py
diff --git a/lib/sqlalchemy/orm/session.py b/lib/sqlalchemy/orm/session.py
index fdef993704..94de2d5631 100644
--- a/lib/sqlalchemy/orm/session.py
+++ b/lib/sqlalchemy/orm/session.py
@@ -1307,6 +1307,8 @@ class Session(_SessionClassMethods):
                 "subtransactions are not implemented in future "
                 "Session objects."
             )
+
+        # it looks like begin() just uses autobegin() (weird?)
         if self._autobegin():
             if not subtransactions and not nested and not _subtrans:
                 return self._transaction
@@ -1324,6 +1326,8 @@ class Session(_SessionClassMethods):
         elif not self.autocommit:
             # outermost transaction.  must be a not nested and not
             # a subtransaction
+
+            # this code is never called!
             assert not nested and not _subtrans and not subtransactions
             trans = SessionTransaction(self)
             assert self._transaction is trans

```

that is, that uncalled block should be removed if autobegin is what we are using and we should probably change the name of "autobegin()" to "_create_new_transaction(autobegin=True|False)" something like that.    We also want:

1. the after_transaction_create hook should have a way to tell if the SessionTransaction was an autobegin or not, so there should be a state variable .is_autobegin added to SessionTransaction
2. add a new option "enable_autobegin=False", if set to False, then true "autobegin" scenarios will raise InvalidRequestError.
3.  enable_autobegin=False **requires** that future=True, that way we don't get into it being mixed up with autocommit or any other weird use cases.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement autobegin=False option** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4128
