### ISSUE TITLE
Postgresql Array contains has stray kwargs

### ISSUE THREAD

**Issue by Yook74** [sqlalchemy/sqlalchemy#6930]
### Describe the bug

In the [documentation](https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#sqlalchemy.dialects.postgresql.ARRAY.Comparator.contains) and [code](https://github.com/sqlalchemy/sqlalchemy/blob/207ec35c2e175f5fcf68e886d5e61a0678c2d6fc/lib/sqlalchemy/dialects/postgresql/array.py#L221), `sqlalchemy.dialects.postgresql.ARRAY.Comparator.contains` has a mysterious `**kwargs` parameter which appears to be unused. The other Array Comparator methods do not have kwargs.

This confused me while I was reading the documentation; I had to look at the source code to find out that it was unused. 

### To Reproduce

https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#sqlalchemy.dialects.postgresql.ARRAY.Comparator.contains

https://github.com/sqlalchemy/sqlalchemy/blob/207ec35c2e175f5fcf68e886d5e61a0678c2d6fc/lib/sqlalchemy/dialects/postgresql/array.py#L221

### Error

N/A

### Versions

All

**Comment by CaselIT** [comment]
Hi,

It seems to always been that way. Also the other contains seem to be the same, like
https://github.com/sqlalchemy/sqlalchemy/blob/fb81f9c8d914f9911925dd3f4e77d7fc374b267c/lib/sqlalchemy/dialects/postgresql/json.py#L310-L314
or
https://github.com/sqlalchemy/sqlalchemy/blob/fb81f9c8d914f9911925dd3f4e77d7fc374b267c/lib/sqlalchemy/dialects/postgresql/hstore.py#L170-L174

I guess we could try removing them and see if the test break for some reason. cc @zzzeek

**Comment by jvanasco** [comment]
@CaselIT is it maybe an artifact of sql/operators.py ?

https://github.com/sqlalchemy/sqlalchemy/blob/fb81f9c8d914f9911925dd3f4e77d7fc374b267c/lib/sqlalchemy/sql/operators.py#L868

It looks to me like several 'contains' operators have unused `**kwargs` that just bubble up/down to the next operator.  IMHO, it might make more sense to just clean the docstring to say the kwargs are currently unused, and reserved for future use or backwards compat.

**Comment by CaselIT** [comment]
Ah yes, that seems to be the case.

Probably we can just note that the kwargs are ignored there

**Comment by zzzeek** [comment]
the kwargs are there to allow qualifiers to the operators such as "escape" - see example at

https://github.com/sqlalchemy/sqlalchemy/blob/207ec35c2e175f5fcf68e886d5e61a0678c2d6fc/test/sql/test_operators.py#L2803-L2808

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **master** branch:

**Fixes: #6930** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3068
