### ISSUE TITLE
TIL about reader mode and our docs do the worst thing w it

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6936]
reader mode: https://frankgroeneveld.nl/2021/08/24/most-underused-browser-feature/

our docs *do* show the reader mode icon since we implement some of the tags, *but* you then get a webpage where most of the content is silently omitted, such as at https://docs.sqlalchemy.org/en/14/tutorial/dbapi_transactions.html .

so it's the "worst" in that the icon does actually show, then silently gives you a broken page.  readers who rely on this feature are therefore subject to lots of confusion.

**Comment by CaselIT** [comment]
Maybe we could try to improve the situation in the site update we are working on?

**Comment by zzzeek** [comment]
i think yes!   in a way this is good news because it will motivate me to help you with reviewing this work.    im not doing very well with parallel thinking these days.

**Comment by zzzeek** [comment]
this is still broken.   how come all of our updates haven't fixed this?

**Comment by zzzeek** [comment]
the site looks great on mobile now with the bootstrap update and I am not getting any "reader" links on android, the docs are mobile native.  So I'm not sure what I was looking at on Oct 10, 22 above, is it possible chrome on android has changed?  not sure.

in any case site / docs on mobile has been a solved problem so ...closing this

**Comment by CaselIT** [comment]
Iirc the idea was support for reader mode. But since we don't seem to have mich request for this, I agree that we can close and revisit if needed

**Comment by zzzeek** [comment]
i dont "reader mode" on my phone right now.  which I think is, because the site is already well-formatted for mobile, "reader mode" is not suggested.
