### ISSUE TITLE
Consider deprecating the default dbapi for each dialect

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6960]
### Describe the use case

It may be worth considering deprecating the default dbapi selected by sqlalchemy when none is specified, since it makes it hard to change what the default points to in case a dbapi is deprecated or a newer version is released.

An example of this is psycopg3. I guess that at some point it may make sense to treat it as the default dbapi for postgresql, but that's hardly feasible without a huge impact on the users now using and expecting psycopg2

As discussed in a recent SQLAlchemy dev meeting, this is probably one of those "features" that will be still around in deprecated form for a long time, since it's highly probable to have a large impact on the user base (with consequent issue triage) if this ever gets removed.

Thoughts?

Feedback is welcome.

### Databases / Backends / Drivers targeted

any

### Example Use

--

**Comment by zzzeek** [comment]
main thought is i just dont see us ever "removing" it, after the "postgres" debacle this would be 100 times that.   I think all documentation should feature full DBAPI names in all URLs though, should be the case already?

**Comment by CaselIT** [comment]
> main thought is i just dont see us ever "removing" it, after the "postgres" debacle this would be 100 times that

indeed. still it may still make sense deprecating it / removing from the documentation. Maybe an alternative may be to make it use configurable, like with an argument in `create_engine`. Something like
```py
create_engine(..., default_dialects={'postgresql': 'psycopg3'. 'mysql':'pyodbc'})
```

the we would just need to support a dict of defaults somewhere with maybe a deprecation warning if we want to add that.

>  I think all documentation should feature full DBAPI names in all URLs though, should be the case already?

It's worth a check

**Comment by zzzeek** [comment]
IMO it should be removed from the docs almost entirely and be considered a "legacy" feature.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **main** branch:

**De-emphasize notion of "default driver" (DBAPI)** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3292
