### ISSUE TITLE
Tests seem not to catch failures in `test/ext/asincio`

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6967]
### Describe the bug

The current master https://github.com/sqlalchemy/sqlalchemy/commit/184e2da5992c55266b37bab5ce3a07e9dfb8caa1
fails a test in `test/ext/asyncio/test_session_py3k.py`:

`FAILED test/ext/asyncio/test_session_py3k.py::OverrideSyncSession::test_init_class - AttributeError: 'AsyncSession' object attribute 'sync_session_class' is read-only`

Looking at the error the current implementation is incompatible with `__slots__` in the `AsyncSession` class.

> 

### To Reproduce

```python
pytest --db aiosqlite .\test\ext\asyncio\
```

### Error

FAILED test/ext/asyncio/test_session_py3k.py::OverrideSyncSession::test_init_class - AttributeError: 'AsyncSession' object attribute 'sync_session_class' is read-only

### Versions

- SQLAlchemy: 184e2da5992c55266b37bab5ce3a07e9dfb8caa1

**Comment by zzzeek** [comment]
this was due to two separate commits merging, the tests were never exercised against both

af0824fd79 and 1798c3cf1c

**Comment by CaselIT** [comment]
Ok, it starts to make sense, but the merge that run on github should have failed the pipeline. We probably don't have aiosqlite running there.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**remove async session slots** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3036

**Comment by CaselIT** [comment]
reopening since I want to add asyncio tests on github (maybe only on linux, since on windows aiosqlite is less than stable)
