### ISSUE TITLE
repeated col expressions not working in ORM level queries

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6979]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/6976

```py
from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.orm import *
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)

c1 = column('q')
s1 = select(A.data, A.data)
print(s1)

print(s1.set_label_style(LABEL_STYLE_TABLENAME_PLUS_COL))

print(Session().query(A.data, A.data))
```

```
SELECT a.data 
FROM a

SELECT a.data AS a_data 
FROM a

SELECT a.data AS a_data 
FROM a
```

**Comment by zzzeek** [comment]
OK that does the same thing in 1.3, however this does not (note null is a singleton):

    print(Session().query(null(), null()))

1.3:

```
SELECT NULL AS anon_1, NULL AS anon_2
SELECT a.data AS a_data 
FROM a
```

1.4

```
SELECT NULL AS anon_1
```

we support dupe columns, these are all wrong, if you use a core select this problem does not occur

**Comment by zzzeek** [comment]
```py
print(Session().query(null(), null()))
print(Session().query(null().label(None), null().label(None)))
print(Session().query(A.data, A.data))
print(Session().query(A.data.label(None), A.data.label(None)))
```

these should all print that many columns

**Comment by zzzeek** [comment]
so the "self.dedupe_cols" seems to do this, but now it is accommodating the null() call not just the ORM entity call.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**turn off deduping for col expressions** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3061
