### ISSUE TITLE
Rework how with_variant works to avoid returning a VariantType

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy#6980]
**Describe your question**

Hi,
how do I type a type with a variant correctly? Currently I use the below code which results in a mypy error.

**Example - please use the [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) guidelines if possible**

```python
from sqlalchemy.types import BigInteger
IDType: BigInteger = BigInteger().with_variant(Integer, "sqlite")
```

**Error**

```
feed_test_results/db/types.py:13:22: error: Incompatible types in assignment (expression has type "Variant[int]", variable has type
"BigInteger")  [assignment]
    IDType: BigInteger = BigInteger().with_variant(Integer, "sqlite")
                         ^
```

**Versions**
OS: Linux
Python: 3.7.1
SQLAlchemy: 1.4.22
mypy: 0.910
SQLAlchemy2-stubs: 0.0.2a6

**Have a nice day!**

**Comment by CaselIT** [comment]
moved

**Comment by kasium** [comment]
Thanks a lot!
