### ISSUE TITLE
Deprecation for v2

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6981]
List of simple deprecation that don't warrant a separate issue by its own.

- [ ] `connection` property in _ConnectionRecord and _ConnectionFairy. Replaced by `dbapi_connection` and `driver_connection`
- [x] `encoding` parameter on create_engine(), dialect  - encoding is already removed

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**deprecate .connection on _ConnectionFairy, _ConnectionRecord** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3857
