### ISSUE TITLE
Investigate usage of `__signature__` for the init method of model classes

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#6982]
### Describe the use case

Seems like libraries like pydantic can generate signatures that are understood by ides.

I think pydantic does it by setting `__signature__` on the class, like so:
https://github.com/samuelcolvin/pydantic/blob/5ccbdcb5904f35834300b01432a665c75dc02296/pydantic/main.py#L266

This is how the signature is generated:
https://github.com/samuelcolvin/pydantic/blob/5ccbdcb5904f35834300b01432a665c75dc02296/pydantic/utils.py#L197-L259

### Databases / Backends / Drivers targeted

not really a database related thing

### Example Use
```py
r = registry()
r.mapped
class Foo:
  __tablename__='foo'
  id = Column(Intenger, primary_key=True)
  name = Column(Text)

Foo() # here the ide would suggest that the signature for Foo is (*, id: Optional[int], name: Optional[str])
```
### Additional context

Getting the correct types may be difficult to do, but I think it would be useful even if we just placed Any anywhere at least initially

**Comment by zzzeek** [comment]
how would the IDE know anything about Foo() when the IDEs only inspect source code and don't actually run anything in SQLAlchemy?

**Comment by CaselIT** [comment]
Not sure hot it works specifically, but I was looking at how dataclasses, pydantic and sqlmodel worked and it seems they use `__signature__` to properly type hint the constructor

**Comment by zzzeek** [comment]
my impression is this is useful for sphinx documentation as sphinx autodoc does import modules and uses real Python inspection, but wont help the IDE case, since IDEs dont run any code.    that said it is useful to have ``__signature__``, since our default ``__init__`` method is probably just ``__init__(self, **kw)``.   we could also just generate a fully typed ``__init__`` method since we do all kinds of ``eval()``.

**Comment by CaselIT** [comment]
We actually already use eval in the init, we wrap the default one to create the instance state and do some other stuff.

Regarding ides not sure, this seems to suggest that they somehow infer the proper signature https://github.com/tiangolo/sqlmodel#editor-support

**Comment by zzzeek** [comment]
it looks like the story of how this works is in https://github.com/samuelcolvin/pydantic/issues/650.   answer seems to be:  write pycharm plugins, trick vscode IDE into thinking the class is a pure dataclass which uses the built-in dataclass support.   see also https://github.com/microsoft/python-language-server/issues/1898.

there seems to be *some* kind of new thing happening at https://github.com/samuelcolvin/pydantic/pull/2721 for this issue but it's not clear what im looking at.   "it all is specific to dataclasses" seems to be a big theme.

We can likely get some input from @tiangolo on how far off the mark this is but I am not optimistic we have a path for pylance right now which is IMO the biggest target.

**Comment by CaselIT** [comment]
Seems that https://github.com/samuelcolvin/pydantic/pull/2721 does make this work for pylance.

I'm agreeing more and more with your opinion of the typing in python :/.

Should we move this to a discussion, since there is nothing that would help at the moment that doesn't seem like an hack?

Maybe signature may still make sense compiling, so that at least the help is correct?

**Comment by CaselIT** [comment]
> We actually already use eval in the init, we wrap the default one to create the instance state and do some other stuff.
> 
> Regarding ides not sure, this seems to suggest that they somehow infer the proper signature https://github.com/tiangolo/sqlmodel#editor-support

It seems that it uses https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md#alternate-form

**Comment by CaselIT** [comment]
I think thins will be a wont-fix and we will do https://github.com/sqlalchemy/sqlalchemy/issues/7642 instead.

I think we can close this mike
