### ISSUE TITLE
see if _UnboundLoad can be removed for 2.0

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#6986]
in 2.0 we will no longer have joinedload("stringname").    which means all options will have the parent class present:   joinedload(Entity.attribute).

Therefore, we no longer need _UnboundLoad.  There's one feature that's specific to UnboundLoad right now which is Load.options(), not sure why there was difficulty in having that work for sub-options.  But otherwise being able to remove _UnboundLoad completely will remove a lot of code and complexity and give us Load objects that we can then dig into so that they can provide their information in better ways, such as introspection.

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**Removals: strings for join(), loader_options().** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3356

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**factor out UnboundLoad for most/all cases** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3357
