### ISSUE TITLE
Add a scalars() method to the connection and session classes

### ISSUE THREAD

**Issue by miguelgrinberg** [sqlalchemy/sqlalchemy#6990]
### Describe the use case

Per discussion in https://github.com/sqlalchemy/sqlalchemy/discussions/6985, I think it would be useful to have a `scalars()` method added to the engine and ORM session classes, similar to `scalar()`. This wasn't discussed, but I think for consistency it would also be good to simplify the streaming query expressions in the asyncio connection and session classes.

### Databases / Backends / Drivers targeted

Not related to a particular backend.

### Example Use

Here is a table that shows the current query expressions and how they are simplified with this change.

| Current  | Simplified |
| ------------- | ------------- |
| conn.execute(...).scalars() | conn.scalars()  |
| sess.execute(...).scalars() | sess.scalars()  |
| await conn.execute(...).scalars() | await conn.scalars() |
| await sess.execute(...).scalars() | await sess.scalars() |
| await conn.stream(...).scalars() | await conn.stream_scalars() |
| await sess.stream(...).scalars() | await sess.stream_scalars() |

**Comment by sqla-tester** [comment]
**Miguel Grinberg** has proposed a fix for this issue in the **master** branch:

**Add scalars method to engine and session classes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3065

**Comment by CaselIT** [comment]
Thanks for the PR!

Just a nitpick in the description: engine -> connection.

I've taken a quick look at the pr and the methods are in the connection, so it's probably just a description typo.

**Comment by sqla-tester** [comment]
**Miguel Grinberg** has proposed a fix for this issue in the **master** branch:

**Add scalars method to connection and session classes** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3065

**Comment by CaselIT** [comment]
@miguelgrinberg thanks for suggesting and implementing this, I find that now that's here I use it all the time
