### ISSUE TITLE
Support for asyncmy driver

### ISSUE THREAD

**Issue by Tumornator** [sqlalchemy/sqlalchemy#6993]
### Describe the use case

Async driver for MySQL database, as an alternative driver for aiomyaql

Reasons
- `aiomysql` probably not actively maintained. Last update was 10months ago
- Issues pointing towards inactivity of `aiomysql` project : [#609](https://github.com/aio-libs/aiomysql/issues/609) [#580](https://github.com/aio-libs/aiomysql/issues/580) [#518](https://github.com/aio-libs/aiomysql/issues/518)
- Similar or slightly better benchmarks of `asyncmy` as compared to `aiomysql` (as per asyncmy homepage)
- asyncmy's owner is active

### Databases / Backends / Drivers targeted

Database : ``MySQL``
Driver : ``asyncmy``

### Example Use

`SQLALCHEMY_DATABASE_URL=mysql+asyncmy://user:pass@host:port/db-name`

**Comment by CaselIT** [comment]
Hi, this was already discussed here https://github.com/sqlalchemy/sqlalchemy/discussions/6893

The general reply is that we have the capacity to support only the most used dialects. Maybe the asyncmy maintainers could provide an external dialect?

**Comment by Tumornator** [comment]
Thank you. I will reference this part to maintainers of `asyncmy`

**Comment by CaselIT** [comment]
Thanks.

**Comment by pds2208** [comment]
This is a bit of an issue, aiomysql does not work with python 3.10

**Comment by CaselIT** [comment]
That issue should be reported on their issue tracker

**Comment by pds2208** [comment]
What is the point of reporting an issue for a product (aiomysql) that is no longer maintained? 

The point I'm trying to make is that we need an alternative for python 3.10 and asyncmy is being maintained so asyncmy support in SQLAlchemy is important for those of us that would like to use the new python features in 3.10. The other alternative is Tortoise, which does support asyncmy - I'm hoping I don't have to move over.

**Comment by CaselIT** [comment]
> What is the point of reporting an issue for a product (aiomysql) that is no longer maintained?

I'm not aware of it being abandoned yet, so it's surely more useful to report it there than complain here..

**Comment by zzzeek** [comment]
@CaselIT what about #7000?   should we reopen this and associate?

**Comment by CaselIT** [comment]
If we accept it, sure

**Comment by zzzeek** [comment]
it looks fine, submitter didnt set it up for test config so if i push it to gerrit and add tox.ini / setup it will diverge from theirs, then we're stuck with it

**Comment by CaselIT** [comment]
let's wait for feedback

**Comment by CaselIT** [comment]
we may as well reopen in the meantime

**Comment by sqla-tester** [comment]
**long2ice** has proposed a fix for this issue in the **master** branch:

**Add `asyncmy` support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3079
