### ISSUE TITLE
MariaDB DELETE/INSERT/REPLACE RETURNING

### ISSUE THREAD

**Issue by grooverdan** [sqlalchemy/sqlalchemy#7011]
### Describe the use case

Like the Oracle, MSSQL, Postgres, MariaDB has the RETURNING syntax.

The syntax is same as Postgres taking expressions or `*` (e.g. [fiddle](https://dbfiddle.uk/?rdbms=mariadb_10.5&fiddle=6a68c59ae77e40665b10eecf325c2371)).

Docs are as per:

[DELETE RETURNING](https://mariadb.com/kb/en/delete/#returning) was added  in 10.0.5
[INSERT RETURNING](https://mariadb.com/kb/en/insertreturning/) was added in 10.5.0 (versions are not a typo despite looking like a dyslexic mistake)

[REPLACE RETURNING](https://mariadb.com/kb/en/replacereturning/) was also added in 10.5.0 however SQLAlchemy doesn't expose REPLACE so not important.

What MariaDB doesn't have (yet) is:
* [UPDATE RETURNING](https://jira.mariadb.org/browse/MDEV-5092)
* Multi-table [DELETE RETURNING](https://jira.mariadb.org/browse/MDEV-12326)

### Databases / Backends / Drivers targeted

MariaDB only, MySQL doesn't support these syntaxs

### Example Use

Per existing: https://docs.sqlalchemy.org/en/14/core/dml.html?highlight=returning#sqlalchemy.sql.expression.Delete.returning

### Additional context

I've started a quite broken prototype currently - https://github.com/sqlalchemy/sqlalchemy/compare/master...grooverdan:insert-delete-returning

Without `UPDATE INSERTING` in MariaDB  the `full_returning` isn't usable and I introduced `delete_returning` and `update_returning`.

Confusing aspects for me is the `dialect=postgres` in the test_update_delete and test/orm/test_unitofworkv2.py:
```


        if testing.db.dialect.delete_returning:
            asserter.assert_(
                CompiledSQL(
                    "DELETE FROM users WHERE users.age_int > %(age_int_1)s "
                    "RETURNING users.id",
                    [{"age_int_1": 29}],
                    dialect="postgresql",
```

I'm confused why this is hard coded.

Related to removing `implicit_returning` #6962 (which also confused me). How should I handle it if I was to continue implementing  this?

**Comment by CaselIT** [comment]
This was already tracked by https://github.com/sqlalchemy/sqlalchemy/issues/6483, but we can close the old issue for this one.

Regarding the test I think it's an error in it. The issue with changing  the hardcoded version is that the bind param will change depending on the dialect

**Comment by zzzeek** [comment]
the test mentioned above is intentional, "RETURNING" is not (or at least was not) part of the "default dialect", so in order to test that a RETURNING statement was emitted, we need to check that the SQL construct itself produces a RETURNING construct on a dialect that does so, such as Postgresql.   The test is *not* testing the specific syntax of RETURNING, it's testing that the ORM is using "returning".

**Comment by CaselIT** [comment]
Hi, @grooverdan sorry to ping you.

Sqlalchemy v2 currently assumes that returning is returning rows in values order in case of an `INSERT INTO .. VALUES (), (), () RETURNING`, but it seems that's a wrong assumption as evidenced by https://github.com/sqlalchemy/sqlalchemy/issues/9603

https://github.com/sqlalchemy/sqlalchemy/issues/9618 is trying to came up with a solution to this issue, and we are currently looking at the behaviour of the various database to see if any guarantee the order. (For example sqlite is pretty explicit about not guaranteeing it https://github.com/sqlalchemy/sqlalchemy/issues/9618#issuecomment-1500938811)

The mariadb documentation for returning does not mention order at all, https://mariadb.com/kb/en/insertreturning/. Do you have guidance on this by any change?

Thanks!

**Comment by zzzeek** [comment]
we are zero for three so far so it doesn't much matter at this point for MariaDB :)

**Comment by CaselIT** [comment]
Sure, but in any case knowing it can't hurt!
