### ISSUE TITLE
Minor documentation bug

### ISSUE THREAD

**Issue by ic4f** [sqlalchemy/sqlalchemy#7016]
### Describe the bug

I think the code example in this section https://docs.sqlalchemy.org/en/14/orm/declarative_config.html#metadata should have **BaseTwo** as the parent class:
```py
@reg.mapped
class ClassThree(BaseTwo):
    __tablename__ = 't1'  # will use BaseTwo.metadata
```
The documentation lists BaseOne: `class ClassThree(BaseOne)`.

### To Reproduce

```python
n/a
```

### Error

n/a

### Versions

n/a

**Comment by CaselIT** [comment]
thanks for reporting!
