### ISSUE TITLE
greenlet is pulled as dependency in cases where it shouldn't

### ISSUE THREAD

**Issue by mortenlj** [sqlalchemy/sqlalchemy#7024]
### Describe the bug

In #6136, a way to select the greenlet dependency is devised, so as to only include it on platforms where it is supported. This is great, except the expression is not able to handle all cases correctly, causing greenlet to be included when it shouldn't.

The expression does a simple substring match against a string that contains all supported machine types. Unfortunately, unsupported machine types may have names that match parts of the supported machine types.

In my case, I'm trying to install SQLAlchemy on a Synology NAS running an old `ppc` CPU. On this machine, `platform.machine()` reports `ppc`, which is *not* supposed to be in the supported list for greenlet, but because `ppc64le` is in the supported list, and `ppc` is a substring of this, greenlet is included anyway.

A similar problem is likely to occur on old 32-bit x86 machines (which will report `x86`).

The marker is currently
```
platform_machine in 'x86_64 X86_64 aarch64 AARCH64 ppc64le PPC64LE amd64 AMD64 win32 WIN32'
```

Is there a work-around for installing SQLAlchemy without greenlet?

### To Reproduce

```python
Try installing SQLAlchemy on a ppc machine, or 32-bit x86 machine.
```

### Error

Installing SQLAlchemy triggers installation of greenlet, which will be built from source, but fails on unsupported platforms.

### Versions

- OS: Linux
- Python: 3.8.6
- SQLAlchemy: 1.4.23
- Database: N/A
- DBAPI: N/A

**Comment by CaselIT** [comment]
Hi,

You can use sqlalchemy also without greenlet installed if you don't use the async parts.

Regarding how to fix this, I'm not sure if there is a better way of indicating where that dependency should be installed and where not. Already https://github.com/sqlalchemy/sqlalchemy/issues/6136 broke some external tools used as an alternative to pip (poetry) so it seems that all this stuff is really fragile.
We are open to suggestion regarding this!

**Comment by mortenlj** [comment]
After some more experimenting I found that I can get SQLAlchemy installed by using `pip install sqlalchemy --no-deps`, but that's not possible to do as part of a dependency (so I can't just do `pip install my-package-that-depends-on-sqlalchemy`, but it works as a work-around.

I guess the markers only support comparing with strings, and not a list of strings (which would solve the problem)?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**replace "in" operator with "==" + "or" for greenlet platforms** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3076

**Comment by zzzeek** [comment]
that above will work but it's awful.    @CaselIT note I am removing the "UPPERCASE" thing for platforms other than windows as im guessing that's just a windows thing.

reaching out to the pep-508 author: https://twitter.com/zzzeek/status/1437486584232910855

**Comment by zzzeek** [comment]
this should work for you in the next release

**Comment by che-wish** [comment]
Hey @zzzeek! There is a minor typo here. It's `aarch64` instead of `arch64` and it breaks on M1 MacBook Pro for greenlet installation after upgraded to 1.4.24

**Comment by CaselIT** [comment]
You can install using the `[asyncio]` extra for now..

Thanks for reporting

**Comment by jdow7** [comment]
I've found a similar problem, my local machine has a platform_machine of "AMD64" so fails this check

**Comment by CaselIT** [comment]
Maybe it's not just windows that's case sensitive. What os is reporting that?

**Comment by jdow7** [comment]
I've got a windows machine 

>>> sys.version
'3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]'
>>> sys.platform
'win32'
>>> platform.platform()
'Windows-10-10.0.19042-SP0'
>>> platform.machine()
'AMD64'

**Comment by sqla-tester** [comment]
**JAMES.DOW** has proposed a fix for this issue in the **master** branch:

**Platform_machine names for greenlet check** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3094
