### ISSUE TITLE
SQLite ORM `datetime` conversion interprets milliseconds as microseconds on reads

### ISSUE THREAD

**Issue by posita** [sqlalchemy/sqlalchemy#7027]
### Describe the bug

A `DATETIME` value in SQLite of `2021-09-14 02:12:04.206` gets read by a `DateTime` column as a `datetime` with 206 µs, **_not_** ms. Test case is attached below.

### To Reproduce

```python
# test_case.py
from datetime import datetime
from sqlalchemy import Column, DateTime, Integer, create_engine
from sqlalchemy.orm import declarative_base, sessionmaker
from sqlalchemy.sql.expression import func

Base = declarative_base()

class Example(Base):
    __tablename__ = "app_examples"
    id = Column(Integer, primary_key=True)
    created_at = Column(
        DateTime,
        default=func.STRFTIME("%Y-%m-%d %H:%M:%f", "NOW"),
        nullable=False,
    )

engine = create_engine("sqlite://", connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base.metadata.create_all(bind=engine)

db = SessionLocal()
job = Example()
db.add(job)
db.commit()
db.refresh(job)

raw_created_at = db.execute("SELECT created_at FROM app_examples").first()[0]
dt_created_at = datetime.fromisoformat(raw_created_at)

assert (
    job.created_at.microsecond == dt_created_at.microsecond
), f"{job.created_at.microsecond!r} µs (from ORM) != {dt_created_at.microsecond!r} µs (from {raw_created_at!r})"
```

### Error

``` python
% python test_case.py
Traceback (most recent call last):
  File "/Users/matt/mm-src/takehome-job-proc-ui/test_case.py", line 31, in <module>
    assert (
AssertionError: 813 µs (from ORM) != 813000 µs (from '2021-09-14 02:44:30.813')
```

### Versions

- OS:
- Python:
- SQLAlchemy:
- Database:
- DBAPI:

``` sh
% uname -v
Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64
% python -c 'import sqlalchemy, sqlite3, sys ; print(f"python: {sys.version}") ; print(f"sqlalchemy: {sqlalchemy.__version__}") ; print(f"sqlite3: {sqlite3.version}")'
python: 3.9.6 (default, Jul  7 2021, 06:50:40)
[Clang 12.0.0 (clang-1200.0.32.29)]
sqlalchemy: 1.4.23
sqlite3: 2.6.0
```

**Comment by posita** [comment]
Whoops! Got my wires crossed. This is a `datetime.fromisoformat` bug, not a SQLAlchemy bug. Apologies!

**Comment by posita** [comment]
Erroneously closed. Note the value read back from the database has 206 _**microseconds**_ when it should have 206 milliseconds.

**Comment by zzzeek** [comment]
hey there -

SQLite doesn't have a native date format, which means dates need to be stored as strings.   that then implies that anyone saving and retriving dates from SQLite has to **choose** a string format for these dates.  as you aren't choosing one for DateTime, we can observe that SQLAlchemy's datetime type has picked one for us.   This format is documented at https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#sqlalchemy.dialects.sqlite.DATETIME and you can of course change it.   I would assume here that since you are hardcoding a date format for your default, that format is mismatched from the default used by DateTime.   your easiest bet is to use the datetime format SQLAlchemy already uses here but you can also use `sqlite.DATETIME` directly and affect these formats as you need.  For generic `DateTime` support, you can use `DateTime().with_variant(sqlite.DATETIME(<config>), "sqlite")`.

**Comment by posita** [comment]
Apologies if I'm dense, but I don't see how that fixes things, especially for a SQLite instance with mixed formats (e.g., where a `DATETIME` field could contain the string `2021-09-14 02:44:30.813` or `2021-09-14 02:44:30.813000`). I also feel pretty strongly that a default behavior for interpreting an ISO8601 string like `2021-09-14 02:44:30.813` as having its fractional component interpreted as 813 µs is a bug. In no other context that I know of does `.813` equal `.000813`.

**Comment by zzzeek** [comment]
> Apologies if I'm dense, but I don't see how that fixes things, especially for a SQLite instance with mixed formats (e.g., where a `DATETIME` field could contain the string `2021-09-14 02:44:30.813` or `2021-09-14 02:44:30.813000`). 

OK, how would you go about parsing that , when the dateformat is essentially undefined and the DateTime type is created without any specific date format?   would you use some kind of heuristic to guess the format?  would you run that heuristic on every row or just once per result?  


> I also feel pretty strongly that it's a bug to have a default behavior that interprets an ISO8601 string like `2021-09-14 02:44:30.813` as having a fractional component of 813 µs. In no other context that I know of does `.813` equal `.000813`.

per the documentation, here's how we make the datetime from the row:

```py
>>> import re
>>> import datetime
>>> DATETIME_RE = re.compile(r"(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)(?:\.(\d+))?")
>>> m = DATETIME_RE.match("2021-09-14 02:44:30.813")
>>> result = datetime.datetime(*[int(x) for x in m.groups(0)])
>>> result
datetime.datetime(2021, 9, 14, 2, 44, 30, 813)
>>> result.microsecond
813
```

so the presence of "microsecond" is because Python's datetime object itself has a "microsecond" slot.   It doesn't have a "milliseconds" slot.  In fact, the default string format of Python's datetime object matches ours:

```py
>>> str(result)
'2021-09-14 02:44:30.000813'
```

So hopefully this illustrates that this format wasn't pulled out of thin air, it's based on Python standard library.  If you use SQLAlchemy on a brand new SQLite database and stick to using only datetime() objects, you'll get clean round trips.  If you are trying to work with a **specific string format**, then you have to tell SQLAlchemy what that is.  It also should be clear that even if this format choice were completely terrible, it's been this way for many years and there is no changing it now.  


> 
> My work-around for now is this, but it's really unintuitive and not really supported by documentation:
> 
> ```python
>         default=func.STRFTIME("%Y-%m-%d %H:%M:%f000", "NOW"),  # zero "pad" the fractional component

As I noted previously, you can change the format that SQLAlchemy parses for.  It's documented and I think it's completely intuitive because there is no *single* standard string format for datetimes,  there's lots, and it's not reasonable to expect that a database library is going to perform a heuristic guess on every row what format is in use.  We picked the one that Python itself uses by default.

**Comment by zzzeek** [comment]
to be fair, the sqlite.DATETIME() object doesn't have a way to format for "milliseconds" directly as the regexp does not offer any opportunity to multiply the incoming value * 1000 to fit within Python's datetime constructor.    The rationale for using regexps is that historically it's significantly faster than the strptime() function in Python.

to make a date type based on strptime / strftime you can use TypeDecorator, recipe coming

**Comment by zzzeek** [comment]
note that Python's strftime applies different meaning to "%f" it seems 

```py
from datetime import datetime
from sqlalchemy import Column, DateTime, Integer, create_engine, String
from sqlalchemy.orm import declarative_base, sessionmaker
from sqlalchemy.sql.expression import func
from sqlalchemy.dialects import sqlite
from sqlalchemy.sql.type_api import TypeDecorator


Base = declarative_base()


class MilliSQliteTime(TypeDecorator):
    impl = String

    cache_ok = True

    def process_bind_param(self, value, dialect):
        if value is not None:
            value = value.strftime("%Y-%m-%d %H:%M:%S.%f")
        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            value = datetime.strptime(value, "%Y-%m-%d %H:%M:%S.%f")
        return value


class Example(Base):
    __tablename__ = "app_examples"
    id = Column(Integer, primary_key=True)
    created_at = Column(
        DateTime().with_variant(
            MilliSQliteTime(),
            "sqlite",
        ),
        default=func.STRFTIME("%Y-%m-%d %H:%M:%f", "NOW"),
        nullable=False,
    )


engine = create_engine("sqlite://", echo="debug")
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base.metadata.create_all(bind=engine)

db = SessionLocal()
job = Example()
db.add(job)
db.commit()
db.refresh(job)

raw_created_at = db.execute("SELECT created_at FROM app_examples").first()[0]
dt_created_at = datetime.fromisoformat(raw_created_at)

assert (
    job.created_at.microsecond == dt_created_at.microsecond
), f"{job.created_at.microsecond!r} µs (from ORM) != {dt_created_at.microsecond!r} µs (from {raw_created_at!r})"
```

**Comment by zzzeek** [comment]
sqlite.DATETIME could accept an optional "strptime" format string that would be used instead of the regexp if present.      IMO this would be nice-to-have but low priority unless someone can work on it.

**Comment by posita** [comment]
> OK, how would you go about parsing that , when the dateformat is essentially undefined and the DateTime type is created without any specific date format? …

``` python
>>> import re
>>> import datetime
>>> from decimal import Decimal
>>> DATETIME_RE = re.compile(r"(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)(\.\d+)?")
>>> m = DATETIME_RE.match("2021-09-14 02:44:30.813")
>>> args = [int(m[i]) for i in range(1, 7)]
>>> args.append(int(Decimal(m[7]) * 100000) if m[7] else 0)
>>> result = datetime.datetime(*args)
>>> result
datetime.datetime(2021, 9, 14, 2, 44, 30, 813000)
>>> result.microsecond
813000
```

Also:

``` python
>>> m = DATETIME_RE.match("2021-09-14 02:44:30")
>>> args = [int(m[i]) for i in range(1, 7)]
>>> args.append(int(Decimal(m[7]) * 100000) if m[7] else 0)
>>> result = datetime.datetime(*args)
>>> result
datetime.datetime(2021, 9, 14, 2, 44, 30)
>>> result.microsecond
0
```

**Comment by posita** [comment]
(By the way, the `STRFTIME("%Y-%m-%d %H:%M:%f", "NOW")` bit wasn't arbitrary. It was selected to closely match [`CURRENT_TIMESTAMP`, etc.](https://sqlite.org/lang_datefunc.html):

```
% sqlite3 -header -column jobs.db
SQLite version 3.36.0 2021-06-18 18:36:39
Enter ".help" for usage hints.
sqlite> SELECT CURRENT_TIMESTAMP, DATETIME('NOW'), STRFTIME('%Y-%m-%d %H:%M:%S', 'NOW'), STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW') ;

CURRENT_TIMESTAMP    DATETIME('NOW')      STRFTIME('%Y-%m-%d %H:%M:%S', 'NOW')  STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')
-------------------  -------------------  ------------------------------------  ------------------------------------
2021-09-14 19:02:25  2021-09-14 19:02:25  2021-09-14 19:02:25                   2021-09-14 19:02:25.829
```

**Comment by CaselIT** [comment]
> Again, apologies for being dense, but I don't understand how any of what you've raised justifies parsing a seconds component 30.813 of an ISO 8601 timestamp as semantically equivalent to 30.000813. I also don't see any evidence of Python's standard library doing this.

because by default sqlalchemy is not using an ISO 8601 format to represent it.

As mentioned by mike, you can use the type engine to implement your own implementation. Using `fromisoformat` would also be ~10 times faster compared to the normal regexp + int parsing

**Comment by zzzeek** [comment]
> > OK, how would you go about parsing that , when the dateformat is essentially undefined and the DateTime type is created without any specific date format? …
> 
> ```python
> >>> import re
> >>> import datetime
> >>> from decimal import Decimal
> >>> DATETIME_RE = re.compile(r"(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)(\.\d+)?")
> >>> m = DATETIME_RE.match("2021-09-14 02:44:30.813")  # with fractional component
> >>> args = [int(m[i]) for i in range(1, 7)] ; args.append(int(Decimal(m[7]) * 1000000) if m[7] else 0)
> >>> datetime.datetime(*args)
> >>> _.microsecond
> 813000
> >>> m = DATETIME_RE.match("2021-09-14 02:44:30")  # without fractional component
> >>> args = [int(m[i]) for i in range(1, 7)] ; args.append(int(Decimal(m[7]) * 1000000) if m[7] else 0)
> >>> datetime.datetime(*args)
> datetime.datetime(2021, 9, 14, 2, 44, 30)
> >>> _.microsecond
> 0

as i said, I realized you meant those *two particular* formats, not arbitrary formats, and we were going for something that doesn't have a lot of overhead.   i'd be using a split on the dot and integer math long before I'd use Decimal, which if you profile it youd see is quite slow.

> ```
> 
> See also:
> 
> ```python
> >>> datetime.datetime.fromisoformat("2021-09-14 02:44:30.813")
> datetime.datetime(2021, 9, 14, 2, 44, 30, 813000)

this function was only added in python 3.7.  SQLAlchemy's first release was for Python 2.3.


> ```
> 
> Again, apologies for being dense, but I don't understand how any of what you've raised justifies parsing a seconds component `30.813` of an ISO 8601 timestamp as semantically equivalent to `30.000813`. I also don't see any evidence of Python's standard library doing this.

you arent being dense but it's a combative, sarcastic phrase, and by using this term repeatedly as well as things like "I feel *strongly*"  you are being generally combative and putting me on the defensive which i apologize has ruined my day, the small inconvenience that this has caused in that you have to add "000" to your "default" value isn't worth this.   if OTOH you feel that your need to be sarcastic and combative is because *I* have been so, then I apologize for that, but in any case, I am done with this issue.   please re-report this issue newly, minus sarcasm please, as a feature request to allow more open-ended parsing styles for SQLite DATETIME.   have a nice day.
