### ISSUE TITLE
raise for coercion to lambda sql if the callable is a method, to avoid common mistake

### ISSUE THREAD

**Issue by simsicon** [sqlalchemy/sqlalchemy#7032]
### Describe the bug

According to the deprecation warning, `.subquery()` should be called to produce a subquery statement. But I found in the below code case, the parameter `offset` is cached when using `.subquery`, which results incorrect output.

If i remove the subquery, the output is correct.

### To Reproduce

```python
from sqlalchemy import create_engine, select, func, text
from sqlalchemy.orm import sessionmaker, declarative_base
from sqlalchemy import Column, Integer, Date
import datetime

engine = create_engine("postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/sa_test?sslmode=disable", echo=False)
Session = sessionmaker(engine)

Base = declarative_base()

class CalendarDate(Base):
    __tablename__ = 'calendar_date'

    dt = Column(Date, primary_key=True)
    value = Column(Integer)


Base.metadata.create_all(engine)

def prepare_test_data(n: int):
    today = datetime.datetime.today()

    with Session() as session:
        session.query(CalendarDate).delete()

        for i in range(n):
            _date = today - datetime.timedelta(days=i)
            session.add(CalendarDate(dt=_date, value=i))
        session.commit()

if __name__ == '__main__':
    prepare_test_data(100)

    offsets = [5, 15, 30]

    for offset in offsets:
        with Session() as session:
            sub_stmt = select(CalendarDate).where(
                CalendarDate.value < 1000
            ).order_by(CalendarDate.dt.desc()).limit(offset).subquery

            stmt = select(func.min(text("dt"))).select_from(sub_stmt)

            print(session.execute(stmt).scalars().one_or_none())

            # output is the same, offset is cached
            # 2021-09-12
            # 2021-09-12
            # 2021-09-12


    for offset in offsets:
        with Session() as session:
            sub_stmt = select(CalendarDate).where(
                CalendarDate.value < 1000
            ).order_by(CalendarDate.dt.desc()).limit(offset) # get rid of subquery

            stmt = select(func.min(text("dt"))).select_from(sub_stmt)

            print(session.execute(stmt).scalars().one_or_none())

            # a deprecated warning given but correct result
            # 2021-09-12
            # 2021-09-02
            # 2021-08-18
```

### Error

no error stacktrace

### Versions

- OS: mac os big sur 11.6 apple silicon
- Python: Python 3.9.6
- SQLAlchemy: 1.4.23
- Database: Postgresql 13.3
- DBAPI: psycopg2 2.91

**Comment by CaselIT** [comment]
Hi,

Subquery is a method, not a property: https://docs.sqlalchemy.org/en/14/core/selectable.html?highlight=subquery#sqlalchemy.sql.expression.Select.subquery

The amazing thing is that it's accepted at all. Maybe we should prevent that @zzzeek ?

**Comment by zzzeek** [comment]
it receives the method as a lambda callable, i dont have an easy way for this to be detected, it might even be valid (though probably not)

```py
(Pdb) froms
(<bound method SelectBase.subquery of <sqlalchemy.sql.selectable.Select object at 0x7f4341df2ca0>>,)
(Pdb) coercions.expect(roles.FromClauseRole, froms[0])
LambdaElement(<code object subquery at 0x7f43422cc920, file "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/selectable.py", line 3065>)

```

**Comment by CaselIT** [comment]
I guess we can detect if it's the callable is a bound method of something sqlalchemy?

Something like
```py
callable.__self__.__class__.__module__.startswith('sqlalchemy.')
```

**Comment by zzzeek** [comment]
long term we get coercions and cache key generation written in cython and we can dump the lambda thing completely

**Comment by zzzeek** [comment]
we certainly here can raise if a method is passed to lambda callables.   methods should not be used here

**Comment by simsicon** [comment]
The parameter `offset` only be read as 5 in the case,  

> Hi,
> 
> Subquery is a method, not a property: https://docs.sqlalchemy.org/en/14/core/selectable.html?highlight=subquery#sqlalchemy.sql.expression.Select.subquery
> 
> If you call it it will work correctly
> 
> The surprising thing is that it's accepted at all. Maybe we should prevent that @zzzeek ?

Thanks for the reply....I think I know it should be called as a function not a property, but I did not realize it because I was convinced it must be some kind of bug...

I like your idea it should raise somehow to prevent future misusage like this.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**reject methods as lambda SQL callables** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3533

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**reject methods as lambda SQL callables** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3534
