### ISSUE TITLE
Insert from_select with independent CTE that is also an insert from_select is selecting from wrong columns

### ISSUE THREAD

**Issue by dbluestein** [sqlalchemy/sqlalchemy#7036]
### Describe the bug

If I have two INSERT from_select statements and add one to the other as an independent CTE, the main statement's SELECT selects the columns from the CTE's SELECT.

### To Reproduce

```python
from sqlalchemy import select, text, Column, Integer, MetaData, String, Table

metadata = MetaData()

t1 = Table(
    'table1', metadata,
    Column('id1', Integer),
    Column('a', String)
)

t2 = Table(
    'table2', metadata,
    Column('id2', Integer),
    Column('b', String)
)


ins1 = t1.insert().from_select(
    ['id1', 'a'],
    select(1, text("'a'"))
)

cte1 = ins1.cte('cte1')

ins2 = t2.insert().from_select(
    ['id2', 'b'],
    select(2, text("'b'"))
)

print(ins2.add_cte(cte1))
```

### Error

This outputs:
```sql
WITH cte1 AS 
(INSERT INTO table1 (id1, a) SELECT 1, 'a')
 INSERT INTO table2 (id2, b) SELECT 1, 'a'
```

but I'd expect:
```sql
WITH cte1 AS 
(INSERT INTO table1 (id1, a) SELECT 1, 'a')
 INSERT INTO table2 (id2, b) SELECT 2, 'b'
```

### Versions

- OS: MacOS 11.5.2
- Python: 3.9
- SQLAlchemy: 1.4.23
- Database: postgres
- DBAPI: psycopg2

### Additional context

Thanks! (And apologies if this should be an enhancement request rather than a bug report, since `add_cte()` is a recent addition and I'm not sure if this use is supposed to be supported.)

**Comment by zzzeek** [comment]
I would assume the compiler has a single "this is the FROM SELECT to use" state set up and we'd have to tweak it for this.

**Comment by zzzeek** [comment]
see that

https://github.com/sqlalchemy/sqlalchemy/blob/c27bf6f7ecc1a120f0c8029eaa5969b6d2aa255d/lib/sqlalchemy/sql/crud.py#L312-L314

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**use the stack for insert_from_select** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3084

**Comment by dbluestein** [comment]
Thank you! My actual use case is more complicated than the simplified example above (involving another data-modifying CTE that returns values that are used in both the main statement and the stand-alone CTE) and this patch works there as well.
