### ISSUE TITLE
1.4 Misleading documentation about encoding configuration for create_engine() with postgresql

### ISSUE THREAD

**Issue by gregorvolkmann** [sqlalchemy/sqlalchemy#7050]
### Describe the bug

The documentation suggests, when working with python3 and unicode character sets, the encoding parameter is much likely obsolete since it "Defaults to utf-8." as stated [here](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.encoding)

This is not true.

SQLAlchemy uses the encoding from `client_encoding` in `postgresql.conf` as stated in [this thread](https://stackoverflow.com/questions/14783505/encoding-error-with-sqlalchemy-and-postgresql/14788796#14788796).

### To Reproduce

Set `client_encoding = SQL_ASCII` (or do not set at all, defaults to SQL_ASCII) in `postgresql.conf` and `create_engine()` without an encoding set.
Add data into `String` or `Unicode` Columns.

### Error

When inserting and commiting with
```python
session.add(Class_With_Column_Unicode(attr1=a, attr2="Hällö Wörld"))
session.commit()
```
The following Exception is thrown
`'ascii' codec can't encode character '\xe4' in position 20: ordinal not in range(128)`

### To Fix

Adding `?client_encoding=utf8` to the connection string fixes the problem. The documentation suggest the `client_encoding` defaults to utf8, what it does not.

### Fix globally

Wouldn't it be clearer to state in the documentation, that `client_encoding` does not neccessarily default to `utf8` since the `client_encoding` for postgresql sometimes defaults to `SQL_ASCII`?

### Versions

- OS: debian buster
- Python: 3.9.2
- SQLAlchemy: 1.4.23
- Database: postgresql
- DBAPI: psycopg2==2.9.1

### Additional context

I would have liked to contribute a pull request, but the documentation for the encoding parameters of create_engine() seems to be autogenerated. If someone can lead me to the corresponding part on Github I would make an effort to propose a better documentation on the encoding parameter.

**Comment by zzzeek** [comment]
> ### Describe the bug
> 
> The documentation suggests, when working with python3 and unicode character sets, the encoding parameter is much likely obsolete since it "Defaults to utf-8." as stated [here](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.encoding)
> 
> This is not true.

im not following this.  what's not true, that the '"encoding" parameter is mostly obsolete', and you are seeing it take effect in some unexpected way?  or that you expected utf-8 to be used somewhere where it wasn't ?   the doc you refer towards has both boldface text as well as a green warning box that this parameter is not applied to the DBAPI, and that DBAPIs in Python 3 all have their own encoding facilities that are outside of the scope of SQLAlchemy.     

the basic fact is that the "encoding" parameter for create_engine() is used by the Unicode data type under Python 2, and it is used to encode the SQL string statement under Python 2.  Under Python 3 with normal configurations, none of that takes effect and I'm not aware of any cases where it would; if there is some specific case, then I would need a clear demonstration of that and/or show me in the code how it happens; the "python 3-ness" of this feature is based on flags like "supports_unicode_statements" and "convert_unicode" which should all be set a certain way under Python 3 by default.


> 
> SQLAlchemy uses the encoding from `client_encoding` in `postgresql.conf` as stated in [this thread](https://stackoverflow.com/questions/14783505/encoding-error-with-sqlalchemy-and-postgresql/14788796#14788796).

SQLAlchemy doesn't "use" this parameter explicitly, the psycopg2 driver would be using this.  whether or not that's taking effect or interacting with postgresql.conf in some unknown way would be a psycopg2 issue.


> ### To Reproduce
> 
> ```python
> Set client_encoding = SQL_ASCII in postgresql.conf and create_engine() without an encoding set.
> Add data into String or Unicode Columns.

and....what is the issue, are you putting in non-ascii characters and you expect them to raise encoding errors ?    this doesn't tell me what the problem is.    

> ```
> 
> ### Error
> 
> Failed very quiet for me. Logging the exception did not work and the python debugger does not work with SQLAlchemy as far as I know.

what's "the exception" ?     you haven't stated what this is.   


Please provide appropriate detail as it is very unclear what is being stated here, thanks.

**Comment by gregorvolkmann** [comment]
The documentation states in the first sentence, that the encoding "[Defaults to utf-8.](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.encoding)". This seems to me not to be true.

To me it seems, the encoding defaults to the `client_encoding` in `postgresql.conf`. Wich defaults  in some circumstances to SQL_ASCII.

When inserting a unicode string like "Hällö Wörld!" into a String or Unicode Column with SQLAlchemy, the insertion does raise an exception (updated, see above) since it's out of range. When configuring the engine explicitly with `conn_string + '?client_encoding=utf8'` the insertion wörks.

I understand the parameter `client_encoding` is not "used" by SQLAlchemy. Don't you think stating it defaults to `utf8` in the documentation is misleading? Since it could default to something other, depending of the configuration of the DB and DBAPI?

Kind regards Gregor Volkmann

**Comment by gregorvolkmann** [comment]
@zzzeek Thank you for taking so much time and effort for replying to this issue! <3

**Comment by CaselIT** [comment]
I think we could clarify the documentation and deprecate the parameter under py3k (the deprecation could maybe be in v2)

**Comment by zzzeek** [comment]
> The documentation states in the first sentence, that the encoding "[Defaults to utf-8.](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.encoding)". This seems to me not to be true.

OK i think perhaps the name of the parameter, "encoding", is somehow misleading you into thinking that this means, "the actual encoding that will be used".  This is not what that means.  It means, there is a Python parameter in SQLAlchemy that happens to be called, "encoding", and its default value is most certainly the string "utf-8".  Beyond that, this information tells you nothing about what effect this might have.    The documentation that immediately follows the first word of this parameter IMO is extremely clear what this "encoding" parameter refers towards, to quote, **This is the string encoding used by SQLAlchemy for string encode/decode operations which occur within SQLAlchemy, outside of the DBAPIs own encoding facilities.**.   It's then followed by a warning box noting that **this parameter is not used in python 3 and is mostly obsolete**.

so to sum up:  1. there's a Python parameter that happens to be named "encoding"  2. its default value is the string "utf-8"  3. it is **legacy and not used at all in python 3**   4. it has nothing to do with what "encoding" behavior you will get from the DBAPI you are using.

I am sorry this parameter appears to have misled you and we obviously will likely remove it in SQLAlchemy 2 however at the moment the documentation is factually accurate.


> 
> I understand the parameter `client_encoding` is not "used" by SQLAlchemy. Don't you think stating it defaults to `utf8` in the documentation is misleading? Since it could default to something other, depending of the configuration of the DB and DBAPI?

again the word "it" is signficant here, there's the "encoding" parameter sent to the SQLAlchemy create_engine() function, which is one particular parameter, and there is another parameter called "client_encoding" which is specific to the psycopg2 dialect and refers to something else.   

the only immediate change I could see making here is adding more boldface text, but IMO there's plenty there already and i think your experience was just unfortunate.   the parameter will likely not appear in the documentation in 2.0 as it won't have any use.


> 
> Kind regards Gregor Volkmann

**Comment by gregorvolkmann** [comment]
There are two parameters here. `encoding` and `client_encoding`.

`encoding` being obsolete and handling encoding inside of python 2, because python 3 is encoding all strings in unicode, right?

`client_encoding` overwriting the encoding used in psycopg2 and **best** configured in postgresql, right?

Configuring the `client_encoding` in the connection string makes inserting unicode characters into the database with charset of SQL_ASCII throwing no exception. As you might already have guessed, this does not turn out well when trying to retrieve the inserted data.

Thank you for already updating the documentation.

**Comment by gregorvolkmann** [comment]
If anyone is stumbling on this, here is the real problem: https://github.com/ansible/ansible/issues/7246
