### ISSUE TITLE
Pylint reports abstract-method

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy#7052]
### Describe the bug

The below example fails in the pylint checker with an missing overridden method. However, I guess that I should not override it.
The pylint guys told me to "inherit fromabc.ABC to indicate that the class is abstract.". See https://github.com/PyCQA/pylint/issues/5031

Can you please consider to do that? Not sure if this is possible.

Fyi, the check responsible, checks if the method has the only statement a "raise NotImplementedError". 

### To Reproduce

```python
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql.functions import ReturnTypeFromArgs

class greatest(ReturnTypeFromArgs):
    name = "greatest"


@compiles(greatest, "foo")
def foo_greatest(element, compiler, **_):
    return compiler.visit_function(element)
```

### Error

```
pylint dummy.py --disable all --enable abstract-method,useless-suppression
```

```
dummy.py:4:0: W0223: Method '_all_selected_columns' is abstract in class 'ReturnsRows' but is not overridden (abstract-method)
```

### Versions

- OS: SUSE
- Python: 3.7.1
- SQLAlchemy: 1.4.22
- Database: None
- DBAPI: None

**Comment by zzzeek** [comment]
IMO this is totally a bug in pylint.   We are not using [abc](https://docs.python.org/3/library/abc.html) so pylint has no business stating this class is "abstract".   methods that are notimplemented are just that, not implemented.   i dont have a way to "fix" that issue here, i dont know what the fix would be.

**Comment by kasium** [comment]
@zzzeek thanks for your feedback. As an end user of both SQLAlchemy and pylint it's overall confusing. I understand if you have better stuff to do, but it would be great if you could leave a comment in the pylint issue

**Comment by zzzeek** [comment]
i can do that.

 on this end id gladly work around but i dont even know how

**Comment by zzzeek** [comment]
inherit from ABC, well I think they are just wrong.

**Comment by kasium** [comment]
Thanks a lot 😄 I'm also curious how to solve that

**Comment by zzzeek** [comment]
they want us to inherit from ABC which is not a trivial change.  also you shouldn't have to lint SQLAlchemy either when you run pylint.

**Comment by zzzeek** [comment]
pylint somehow implies sqlalchemy would need to rewrite their internal APIs to use abstract methods, we dont have such linter rules in our internal library and users who want to use pylint w/ sqlalchemy as a dependency shouldnt be forced to be subject to any internal linting problems in sqlalchemy itself, seems pretty wrong

**Comment by kasium** [comment]
Thanks for the help. Of course I can just disable the check for my custom functions but I wanted to double check

**Comment by zzzeek** [comment]
we dont have W0223 excluded in our pyflakes config , i dont know if pylint rules apply there

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**implement _all_selected_columns for functionelement** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3091

**Comment by kasium** [comment]
Thanks a lot!
