### ISSUE TITLE
order_by(None) not clear query from order defined in the model

### ISSUE THREAD

**Issue by Rogalek** [sqlalchemy/sqlalchemy#7053]
### Describe the bug

Hello again, I have a problem with deleting the order by `order_by(None)` if it is mapped in sqalchemy model.

I have two simple models: A and B with few fields and in one I use `order_by` parameter in the relationship, later when I want to cancel it, the function does not work.

### To Reproduce

```python
class User(declarative_base()):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    name = Column(Unicode(256), nullable=False)



class Photo(declarative_base()):
    __tablename__ = 'photos'

    id = Column(Integer, primary_key=True)
    user_id = Column(
        Integer, ForeignKey('as.id', ondelete='cascade'),
        index=True, nullable=False)
    name = Column(Unicode(2048), nullable=False)
    sort = Column(Integer, nullable=True)
    photo = Column(Unicode(), nullable=True)

    User = relationship("User", backref=backref('photos', cascade="all, delete-orphan", 
        order_by="Photo.sort"))


query = session.query(User).options(joinedload(User.photos))

SELECT users.id AS users_id, users.name AS users_name, photos_1.id AS photos_1_id, photos_1.user_id AS photos_1_user_id, photos_1.name AS photos_1_name, photos_1.sort AS photos_1_sort, photos_1.photo AS photos_1_photo
FROM users LEFT OUTER JOIN photos AS photos_1 ON users.id = photos_1.user_id
ORDER BY photos_1.sort

query2 = query.order_by(None)  # produce the same sql

SELECT users.id AS users_id, users.name AS users_name, photos_1.id AS photos_1_id, photos_1.user_id AS photos_1_user_id, photos_1.name AS photos_1_name, photos_1.sort AS photos_1_sort, photos_1.photo AS photos_1_photo
FROM users LEFT OUTER JOIN photos AS photos_1 ON users.id = photos_1.user_id
ORDER BY photos_1.sort

query3 = session.query(User).order_by(User.name)

SELECT users.id AS users_id, users.name AS users_name
FROM users ORDER BY users.name

query4 = query3.order_by(None)

SELECT users.id AS users_id, users.name AS users_name
FROM users
```

### Error

all showed above

### Versions

- OS: Ubuntu 20.10
- Python: 3.8.0
- SQLAlchemy: 1.4.15
- Database: postgres

**Comment by CaselIT** [comment]
Hi,

This is the expected behaviour, since the query does not control the loader options, and that's where the groupby is applied

**Comment by zzzeek** [comment]
behavior is the same in 1.3 so there's no regression here.

**Comment by CaselIT** [comment]
Is there a way of disabling the relationship sorting mike?

As an alternative you may use `selectinload` that uses a second query to load the relationship, avoiding the sorting in the main query

**Comment by zzzeek** [comment]
the loader strategies dont have configurable order_by right now, this could be added in the form of a keyword argument order_by=<val> to all the relationship loader options, that's fairly doable as a nice to have.   poster can also use contains_eager() to keep the joining present and control the ordering.

**Comment by Rogalek** [comment]
Ok, thank you for the explanation
