### ISSUE TITLE
Lost params when using `join` with `select_from`

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7055]
### Describe the bug

The params set to `.params` are lost when executing a select with a `select_from` that starts uses a `join`

### To Reproduce

```python
import sqlalchemy as sa
from sqlalchemy import event

engine = sa.create_engine("sqlite://", echo=True)
meta = sa.MetaData()

X = sa.Table("x", meta, sa.Column("a", sa.Integer), sa.Column("b", sa.Integer))
Y = sa.Table("y", meta, sa.Column("a", sa.Integer), sa.Column("b", sa.Integer))
meta.create_all(engine)

s1 = sa.select(X.c.a).where(X.c.b == sa.bindparam("xb")).alias("s1")
jj = sa.select(Y).join(s1, Y.c.a == s1.c.a).where(Y.c.b == sa.bindparam("yb")).alias("s2")
# jj = sa.select(Y).where(Y.c.b == sa.bindparam("yb")).alias('s2')

params = {"xb": 42, "yb": 33}
sel = sa.select(Y).select_from(jj).params(params)
assert sel.compile().params == params


@event.listens_for(engine, "before_cursor_execute")
def go(conn, cursor, statement, parameters, context, executemany):
    assert parameters == tuple(params.values()), (parameters, tuple(params.values()))


with engine.connect() as conn:
    conn.execute(sel)
```

### Error

The above script produces the error:
```
.\go.py:26: SAWarning: SELECT statement has a cartesian product between FROM element(s) "s2" and FROM element "y".  Apply join condition(s) between each element to resolve.
  conn.execute(sel)
Traceback (most recent call last):
  File ".\go.py", line 26, in <module>
    conn.execute(sel)
  File "C:\lib\site-packages\sqlalchemy\engine\base.py", line 1262, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\lib\site-packages\sqlalchemy\sql\elements.py", line 324, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\lib\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\\lib\site-packages\sqlalchemy\engine\base.py", line 1712, in _execute_context
    statement, parameters = fn(
  File "C:\\lib\site-packages\sqlalchemy\engine\events.py", line 128, in wrap_before_cursor_execute
    orig_fn(
  File ".\go.py", line 22, in go
    assert parameters == tuple(params.values()), (parameters, tuple(params.values()))
AssertionError: ((None, 33), (42, 33))
```

Using the commented jj does not cause issues

### Versions

- OS: -
- Python: 3.8
- SQLAlchemy: master
- Database: any
- DBAPI: any

### Additional context

I think that the cartesian produc warning is also wrong
> C:\folder\go.py:26: SAWarning: SELECT statement has a cartesian product between FROM element(s) "s2" and FROM element "y".  Apply join condition(s) between each element to resolve.

**Comment by CaselIT** [comment]
Also executing with
```
with engine.connect() as conn:
    conn.execute(sel.compile(engine))
```
works

**Comment by zzzeek** [comment]
the cartesian product warning is correct ?     "SELECT * FROM Y, (SELECT .. ) AS anon_1", Y and anon_1 are not being related together here

**Comment by CaselIT** [comment]
No, I think it's because it loses the parameters. At least, `.compile()` does not complain about it.

This is a simplified version of a more complex orm query, that was using query, and I'm trying to migrate do select. Query does correctly renders the parameters and does not render the warning

**Comment by CaselIT** [comment]
> 
> 
> No, I think it's because it loses the parameters. At least, `.compile()` does not complain about it.
> 

Nevermind, in this example yes, it renders a cartesian product, My comment was for the more complex case. I'll try to write an example of the more complex case later. For now ignore that part :)

**Comment by zzzeek** [comment]
this has to do with the cache key stuff , this works:

```
with engine.connect().execution_options(compiled_cache=None) as conn:
    conn.execute(sel)```

**Comment by CaselIT** [comment]
I figured it was somehow connected, since `sel.compile().params` is correct

**Comment by CaselIT** [comment]
the strange thing is that using `query` with basically the same query worked correctly

**Comment by zzzeek** [comment]
query.params works completely differently :(

**Comment by CaselIT** [comment]
well that's a misery solved at least

**Comment by CaselIT** [comment]
Also passing the params directly to execute works

**Comment by zzzeek** [comment]
the generate cache key comes out with these params, this is the problem

```
ck.bindparams
[BindParameter('yb', 33, type_=Integer()), BindParameter('xb', 42, type_=Integer()), BindParameter('xb', None, type_=Integer())]

```

**Comment by zzzeek** [comment]
then here is the problem at the level of clause adaption

```
(Pdb) sel._from_obj[0].element._setup_joins
((<sqlalchemy.sql.selectable.Subquery at 0x7fa047141f70; s1>, <sqlalchemy.sql.elements.BinaryExpression object at 0x7fa047141760>, None, {'isouter': False, 'full': False}),)
(Pdb) sel._from_obj[0].element._setup_joins[0][0]
<sqlalchemy.sql.selectable.Subquery at 0x7fa047141f70; s1>
(Pdb) sel._from_obj[0].element._setup_joins[0][0].element._where_criteria[0].right
BindParameter('xb', 42, type_=Integer())
(Pdb) sel._from_obj[0].element._setup_joins[0][1].right
Column('a', Integer(), table=<s1>)
(Pdb) sel._from_obj[0].element._setup_joins[0][1].right.table.element._where_criteria[0].right
BindParameter('xb', None, type_=Integer())

```

two versions of the subquery are present.

**Comment by zzzeek** [comment]
this is the fix

```diff
diff --git a/lib/sqlalchemy/sql/selectable.py b/lib/sqlalchemy/sql/selectable.py
index aa218052ea..df0ec2a7b7 100644
--- a/lib/sqlalchemy/sql/selectable.py
+++ b/lib/sqlalchemy/sql/selectable.py
@@ -5519,6 +5519,9 @@ class Select(
             itertools.chain(
                 _from_objects(*self._raw_columns),
                 _from_objects(*self._where_criteria),
+                _from_objects(*[
+                    elem[0] for elem in self._setup_joins
+                ])
             )
         )
 

```

now does that break other things, lets check

test/ext/test_external_traversal.py, seems OK , this needs a test.  will run a WIP through gerrit

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**include setup_joins targets when scanning for FROM objects to clone** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3090

**Comment by CaselIT** [comment]
That fixes the mvce above but not my real use case.

Let me try re-creating it

**Comment by zzzeek** [comment]
well that's horrible because these issues are super painful to fix

**Comment by CaselIT** [comment]
This mostly the same as the original case, minus some minor ditails:
```py
import sqlalchemy as sa
from sqlalchemy import event

engine = sa.create_engine("sqlite://", echo=True)
meta = sa.MetaData()

Pe = sa.Table(
    "pe", meta, sa.Column("c", sa.Integer), sa.Column("p", sa.Integer), sa.Column("pid", sa.Integer)
)
S = sa.Table(
    "s", meta, sa.Column("c", sa.Integer), sa.Column("p", sa.Integer), sa.Column("sid", sa.Integer)
)
Ps = sa.Table("ps", meta, sa.Column("c", sa.Integer), sa.Column("p", sa.Integer))
meta.create_all(engine)

pe_s = sa.select(Pe).where(Pe.c.pid.in_(sa.bindparam("pids", expanding=True))).alias("pe_s")
s_s = sa.select(S).where(S.c.sid == sa.bindparam("sid")).alias("s_s")
jj = sa.join(
    Ps,
    sa.join(pe_s, s_s, sa.and_(pe_s.c.c == s_s.c.c, pe_s.c.p == s_s.c.p)),
    sa.and_(Ps.c.c == pe_s.c.c, Ps.c.p == Ps.c.p),
)

params = {"pids": (42,), "sid": 33}
sel = sa.select(Ps).select_from(jj).params(params)
assert sel.compile().params == params


@event.listens_for(engine, "before_cursor_execute")
def go(conn, cursor, statement, parameters, context, executemany):
    assert parameters == tuple(params.values()), (parameters, tuple(params.values()))


with engine.connect() as conn:
    conn.execute(sel)
```

again:
```
    assert parameters == tuple(params.values()), (parameters, tuple(params.values()))
AssertionError: ((None,), ((42,), 33))
```

**Comment by zzzeek** [comment]
so also we should add a method to select() that does what query.params() does.   .params() has a different behavior that's been maintained for backwardws compat but things would be *much* more efficient to do it like query does.  "set_parameters()" or something like that.

**Comment by zzzeek** [comment]
yeah that query you have is a nightmare :(

**Comment by CaselIT** [comment]
I've updated above, since the params in `before_cursor_execute` are flat

**Comment by CaselIT** [comment]
Also here the query does raises the cartesian product warning, 
> .\go.py:35: SAWarning: SELECT statement has a cartesian product between FROM element(s) "s_s", "pe_s" and FROM element "ps".  Apply join condition(s) between each element to resolve.
  conn.execute(sel, params)

but there should not be any:
```sql
SELECT ps.c, ps.p
FROM ps JOIN ((SELECT pe.c AS c, pe.p AS p, pe.pid AS pid
FROM pe
WHERE pe.pid IN (?)) AS pe_s JOIN (SELECT s.c AS c, s.p AS p, s.sid AS sid
FROM s
WHERE s.sid = ?) AS s_s ON pe_s.c = s_s.c AND pe_s.p = s_s.p) ON ps.c = pe_s.c AND ps.p = ps.p
```

but I understand it's difficult to detect since the join is inside another one

**Comment by zzzeek** [comment]
also totally different bug in your second test.  doesnt even touch the codepath that was failing earlier

**Comment by CaselIT** [comment]
Ahah, well the second bug was free then :)

**Comment by zzzeek** [comment]
we have right nested joins all over the place that dont have a warning, someting about how you are doing this is different and unexpected

**Comment by zzzeek** [comment]
the double parens are part of it, that shouldnt be happening

**Comment by zzzeek** [comment]
im not getting a warning from your test case, are you sure that case gives you a warning?

**Comment by zzzeek** [comment]
yup definitely no warning here, b.c. if i add a bogus table to it then i do get the warning

**Comment by CaselIT** [comment]
Oh right. At work I have 1.4.18 and it has the warning. I can confirm master does not

**Comment by zzzeek** [comment]
anyway i think real solutoin here is add a new parameters method and deprecate params()

**Comment by zzzeek** [comment]
although this really doesnt apply well to session.execute(stmt, params) beause how do we merge params on the statement with the params passed to execute()....

**Comment by CaselIT** [comment]
> 
> 
> although this really doesnt apply well to session.execute(stmt, params) beause how do we merge params on the statement with the params passed to execute()....

passing params to `execute` does work

**Comment by zzzeek** [comment]
for second issue , the replace case is limited like this:

```py
params = {"pids": (42,), "sid": 33}


pe_s = sa.select(Pe).where(Pe.c.pid.in_(sa.bindparam("pids", expanding=True))).alias("pe_s")
s_s = sa.select(S).where(S.c.sid == sa.bindparam("sid")).alias("s_s")
jj = sa.join(
    Ps,
    sa.join(pe_s, s_s, sa.and_(pe_s.c.c == s_s.c.c, pe_s.c.p == s_s.c.p)),
    sa.and_(Ps.c.c == pe_s.c.c, Ps.c.p == Ps.c.p),
).params(params)


``` 

so this is more old school issue

**Comment by CaselIT** [comment]
also
```py
sa.join(pe_s, s_s, sa.and_(pe_s.c.c == s_s.c.c, pe_s.c.p == s_s.c.p)).params(params)
```

**Comment by CaselIT** [comment]
attaching them directly to the alias works instead

**Comment by CaselIT** [comment]
Note that also
```py
jj = sa.join(Ps, pe_s, sa.and_(Ps.c.c == pe_s.c.c, Ps.c.p == Ps.c.p)).join(
    s_s, sa.and_(Ps.c.c == s_s.c.c, Ps.c.p == s_s.c.p)
)
```
does not work. This seems a fairly straight forward join clause, since it renders
```sql
SELECT ps.c, ps.p
FROM ps JOIN (SELECT pe.c AS c, pe.p AS p, pe.pid AS pid
FROM pe
WHERE pe.pid IN (?)) AS pe_s ON ps.c = pe_s.c AND ps.p = ps.p JOIN (SELECT s.c AS c, s.p AS p, s.sid AS sid
FROM s
WHERE s.sid = ?) AS s_s ON ps.c = s_s.c AND ps.p = s_s.p
```

It seems params is fairly broken

**Comment by zzzeek** [comment]
has nothing to do with params...

**Comment by CaselIT** [comment]
I guess not, but it manifests like by setting the params.

Looking at the code, it seems that query just collects params that are then used in execute, while select actually traverses itself and sets a value to the bind param.

Using the query implementation what would break?

**Comment by zzzeek** [comment]
select's method comes from ClauseElement and is historic.  there's no place on ClauseElement to track a bundle of parameters and the "copy and replace" mechanics of params() works a certain way, I dont think we can just hard swap it in 1.4.xx.     i can fix the two issues you have here for now.

**Comment by CaselIT** [comment]
What I meant it that it seems fairly fragile, if poking a bit at it revealed two issues.

I wonder if they are also on 1.3

**Comment by zzzeek** [comment]
the same issue is in 1.3 however it wouldnt cause a failure because the parameters here are also getting confused w/ the cache key for this to happen.

**Comment by zzzeek** [comment]
yes params() is very fragile and inefficient

however a replacement would only be on Executable, not ClauseElement, IMO, and the defaultexecutioncontext would need to get these params and integrate them into all flows.   probably compiler.construct_params() has to do it

**Comment by CaselIT** [comment]
This seems to be different from the first (the above fix does not help), but I'm not sure if it's the same as the second
```py
import sqlalchemy as sa
from sqlalchemy import event

engine = sa.create_engine("sqlite://", echo=True)
meta = sa.MetaData()

X = sa.Table("x", meta, sa.Column("a", sa.Integer), sa.Column("b", sa.Integer))
Y = sa.Table("y", meta, sa.Column("a", sa.Integer), sa.Column("b", sa.Integer))
meta.create_all(engine)

s1 = sa.select([X.c.a]).where(X.c.b == sa.bindparam("xb")).alias("s1")
jj = (
    sa.select([Y])
    .select_from(sa.join(Y, s1, Y.c.a == s1.c.a))
    .where(Y.c.b == sa.bindparam("yb"))
    .alias("s2")
)
# jj = sa.select([Y]).join(s1, Y.c.a == s1.c.a).where(Y.c.b == sa.bindparam("yb")).alias("s2")
# jj = sa.select(Y).where(Y.c.b == sa.bindparam("yb")).alias('s2')

params = {"xb": 42, "yb": 33}
sel = sa.select([Y]).select_from(jj).params(params)
assert sel.compile().params == params

# print(sel._from_obj[0].element._setup_joins)


@event.listens_for(engine, "before_cursor_execute")
def go(conn, cursor, statement, parameters, context, executemany):
    assert parameters == tuple(params.values()), (parameters, tuple(params.values()))


with engine.connect() as conn:
    conn.execute(sel)
```

**Comment by CaselIT** [comment]
This seems to be the same as the second bug, or at least is fixed by the second patch

**Comment by CaselIT** [comment]
> 
> 
> select's method comes from ClauseElement and is historic. there's no place on ClauseElement to track a bundle of parameters and the "copy and replace" mechanics of params() works a certain way, I dont think we can just hard swap it in 1.4.xx. i can fix the two issues you have here for now.

while this issue should be fixed with the proposed patch, regarding hard swap this seems to mostly work. 5 fails in test/sql
```patch
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index 333ed36f4..9fd89d74e 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -992,7 +992,7 @@ class SQLCompiler(Compiled):
                     else name
                 )

-                if _check and bindparam.required:
+                if _check and bindparam.required and False:
                     if _group_number:
                         raise exc.InvalidRequestError(
                             "A value is required for bind parameter %r, "
diff --git a/lib/sqlalchemy/sql/elements.py b/lib/sqlalchemy/sql/elements.py
index 58db56a9c..02cec90aa 100644
--- a/lib/sqlalchemy/sql/elements.py
+++ b/lib/sqlalchemy/sql/elements.py
@@ -219,6 +219,8 @@ class ClauseElement(

     _cache_key_traversal = None

+    _params = util.EMPTY_DICT
+
     def _set_propagate_attrs(self, values):
         # usually, self._propagate_attrs is empty here.  one case where it's
         # not is a subquery against ORM select, that is then pulled as a
@@ -338,6 +340,7 @@ class ClauseElement(
         """
         return self._replace_params(True, optionaldict, kwargs)

+    @_generative
     def params(self, *optionaldict, **kwargs):
         """Return a copy with :func:`_expression.bindparam` elements
         replaced.
@@ -353,7 +356,14 @@ class ClauseElement(
           {'foo':7}

         """
-        return self._replace_params(False, optionaldict, kwargs)
+        # return self._replace_params(False, optionaldict, kwargs)
+        if len(optionaldict) == 1:
+            kwargs.update(optionaldict[0])
+        elif len(optionaldict) > 1:
+            raise exc.ArgumentError(
+                "params() takes zero or one positional dictionary argument"
+            )
+        self._params = self._params.union(kwargs)

     def _replace_params(self, unique, optionaldict, kwargs):
         if len(optionaldict) == 1:
@@ -544,6 +554,16 @@ class ClauseElement(
             else:
                 cache_hit = dialect.NO_CACHE_KEY

+        if extracted_params:
+            extracted_params = [
+                bindparam._with_value(
+                    self._params[bindparam.key], maintain_key=True
+                )
+                if bindparam.key in self._params
+                else bindparam
+                for bindparam in extracted_params
+            ]
+
         return compiled_sql, extracted_params, cache_hit

     def _compiler(self, dialect, **kw):
```

**Comment by zzzeek** [comment]
what happens if someone is doing something like:

     select().select_from(join(s1.params(a=5), s2.params(b=10), onclause).params(c=15)).params(a=10, c, 20)

there could even be things like the same clause repeated with different params:

    select().where(or_(clause.params(...), clause.params(...), ...))

replacing that system with one that just has "_params" would have to take that whole traversal into account, which I dont think is happening with your approach above.

anyway this is why i think a new set of "params" at the top level only, e.g. Executable, would make it clear that these new "parameters" are only set up at the top statement level.

**Comment by CaselIT** [comment]
Yes these use cases would not work. I guess query wilm mostly get away with it since it's not usually composed.

**Comment by CaselIT** [comment]
Thanks mike.

Do you think we should open an issue regarding a new params to add to the selectables what work like query?

Personally I'm not sure yet another way of doing thinks would help, but it's unfortunate that core and query work in different ways. I think many people will start replacing query with selects using params thinking it works the same, while it does fundamentally different things.

Maybe a clarification on the documentation could be added (but maybe it's not that useful?)

**Comment by zzzeek** [comment]
i think we should have a new method on Executable that does the simple parameters thing, add support for that, then the "params()" method we need to strongly note this is not an often used method, you probably want "with_parameters" or whatever we call it.  also ORM Query docs can be cross-linked with new method.

**Comment by CaselIT** [comment]
I've opened a new issue, so it can be tracked. Milestone it as appropriate
