### ISSUE TITLE
UnsupportedCompilationError can't be pickled

### ISSUE THREAD

**Issue by hotpxl** [sqlalchemy/sqlalchemy#7077]
### Describe the bug

`UnsupportedCompilationError` is an exception with multiple arguments. Without a `__reduce__` it can't be pickled

### To Reproduce

```python
python -c 'import pickle; import sqlalchemy.exc; print(pickle.loads(pickle.dumps(sqlalchemy.exc.UnsupportedCompilationError("compiler", "type"))))'
```

### Error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'element_type'
```

### Versions

- OS: Linux
- Python: 3.8
- SQLAlchemy: master
- Database: N/A
- DBAPI: N/A

**Comment by CaselIT** [comment]
Hi,

thanks for reporting, I'm not sure if it's a supported use case. I also think that many other exception are similar.
cc @zzzeek

**Comment by zzzeek** [comment]
Probably needs pickling for some kind of debug toolbar type of thing ?  If the change is isolated then it should be fine , what about all the other exceptions ?  Should we have a test suite for pickleness of exception objects ?

**Comment by CaselIT** [comment]
if we want to support it I think it would be better have one. If it's a best effort thing then the change seem fine

**Comment by hotpxl** [comment]
Yeah I use pickling for debugging purposes and/or in a distributed setting.

I think other exceptions in this file have received similar treament, like
```
class CircularDependencyError(SQLAlchemyError):
    ........
    def __reduce__(self):
        return self.__class__, (None, self.cycles, self.edges, self.args[0])

```

or
```
316 class NoReferencedTableError(NoReferenceError):
317     """Raised by ``ForeignKey`` when the referred ``Table`` cannot be
318     located.
319
320     """
321
322     def __init__(self, message, tname):
323         NoReferenceError.__init__(self, message)
324         self.table_name = tname
325
326     def __reduce__(self):
327         return self.__class__, (self.args[0], self.table_name)
```

**Comment by sqla-tester** [comment]
**Yutian Li** has proposed a fix for this issue in the **master** branch:

**Fix serialization of UnsupportedCompilationError** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3107
