### ISSUE TITLE
Extend `.match` to accept a tsquery

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#7081]
_Originally posted by @MajorDallas in https://github.com/sqlalchemy/sqlalchemy/issues/3160#issuecomment-923107755_

---

I've just run into this, but in my case I'm wanting to use the `websearch_to_tsquery` function.

Given the many ways for a postgres user to transform a bit of text into a `tsquery`, what I would want as a user of SQLAlchemy is the option to give `.match()` the `tsquery` I want to use myself rather than have it lock me in to just one pathway, whether that's `to_tsquery` or `plain_to_tsquery`.

Ex:

```python
my_table.c.tsvec_col.match(func.websearch_to_tsquery('"foo bar"'))
# or
my_table.c.tsvec_col.match('"foo bar"', postgres_tsquery_factory=func.websearch_to_tsquery)
```
emitting
```sql
SELECT * FROM my_table WHERE tsvec_col @@ websearch_to_tsquery('"foo bar"');
```

I think this shouldn't get in the way of other backends since

* in the first example, it's simply passing exactly what the user gives, and
* in the second example, we're using a kwarg that can be as dialect-specific or -agnostic as appropriate (went with specific for my example).

Then, `.match()` should emit `plain_to_tsquery()` as a fallback if it receives a single `str`.

**Comment by jvanasco** [comment]
I created ticket #7086 to replace the default behavior with plainto_tsquery, which was my recommendation in #3160 and part of this ticket as well.

I like the idea to *extend tsquery to accept a `postgres_tsquery_factory`*, but it should probably be named ``postgresql_tsquery_factory`` as there is a ``postgresql_regconfig`` kwarg already.

Extending `.match` to accept a tsquery function surfaces two issues for me:

1. We may need to create actual Python functions to handle each of the PostgreSQL query functions, or use some sort of filtering. This is because it is valid in both PostgreSQL and SQLAlchemy to user other `sqlalchemy.func` functions.  e.g `Table.column.match(func.UPPER("foo"))`

2. In the future, it may make it make sense to implement a version of the `with_variant` system for expressions.

**Comment by zzzeek** [comment]
I just considered doing this but I think it's too cumbersome; it requires a compile-time check but it's messy and error prone to try to distinguish between arbitrary SQL expressions and specifically func.to_tsquery().

In my review at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3847 I just added examples for how users can use all the PG full text functions and operators directly.

**Comment by zzzeek** [comment]
for expediency, review what I have at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3847 and if it's really unsatisfying then maybe reopen this.     but i think it's fine to just use the existing API directly.
