### ISSUE TITLE
Document how to use dynamic in asyncio

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7082]
dynamic essentially already does that actually, we can just document that if you want:

    result = await session.execute(author.book.statement.where(Book.id > 42))

magic !

_Originally posted by @zzzeek in https://github.com/sqlalchemy/sqlalchemy/discussions/7039#discussioncomment-1347776_

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Document dynamic for asyncio** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3117
