### ISSUE TITLE
The array_agg should specify the array demensions

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7083]
To reproduce (from @balukrishnans code)
```py
Foo = Table(
    "Foo",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("bar", JSONB),
)

metadata.create_all(engine)

conn = engine.connect()
with conn.begin() as tran:
    i_query = Foo.insert().values(
        [
            {"id": 1, "bar": [{"buz": 1}]}, 
            {"id": 2,"bar": None},
        ]
    )
    conn.execute(i_query)
    s_query = select([func.array_agg(Foo.c.bar).label("agg_val")])
    result=conn.execute(s_query).fetchall()
print(result[0].agg_val)
```
error is 
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    print(result[0].agg_val)
  File "/site-packages/sqlalchemy/dialects/postgresql/array.py", line 359, in process
    return self._proc_array(
  File "/site-packages/sqlalchemy/dialects/postgresql/array.py", line 306, in _proc_array
    return collection(
  File "/site-packages/sqlalchemy/dialects/postgresql/array.py", line 307, in <genexpr>
    self._proc_array(
  File "/site-packages/sqlalchemy/dialects/postgresql/array.py", line 289, in _proc_array
    arr = list(arr)
TypeError: 'NoneType' object is not iterable
```

I think think what's failing it the heuristic to guess the dimensions of the array. Maybe we could specify the dimension here:
https://github.com/sqlalchemy/sqlalchemy/blob/7023c07aa6d31b3527cb1171410dcb6e8dff3ec3/lib/sqlalchemy/sql/functions.py#L1331-L1348

If you pass the array dimension in the array_agg function does it work? `func.array_agg(Foo.c.bar, tyoe_=Array(Jsonb, dimensions=1))`

thoughts @zzzeek

_Originally posted by @CaselIT in https://github.com/sqlalchemy/sqlalchemy/discussions/7080#discussioncomment-1376226_

**Comment by zzzeek** [comment]
isnt the issue just that one of the elements of the array is NULL?   this fixes:

```diff
diff --git a/lib/sqlalchemy/dialects/postgresql/array.py b/lib/sqlalchemy/dialects/postgresql/array.py
index 3cb60d3f3b..f14a1b81cd 100644
--- a/lib/sqlalchemy/dialects/postgresql/array.py
+++ b/lib/sqlalchemy/dialects/postgresql/array.py
@@ -329,7 +329,7 @@ class ARRAY(sqltypes.ARRAY):
                     itemproc,
                     dim - 1 if dim is not None else None,
                     collection,
-                )
+                ) if x is not None else None
                 for x in arr
             )
 
```

expected output is `[[{'buz': 1}], None]` right?

**Comment by zzzeek** [comment]
now if first element is NULL we're out of luck they have to specify...so hmm why does this work, oh because we assume dimension is one:

```
    i_query = Foo.insert().values(
        [
            {"id": 1, "bar": None},
            {"id": 2, "bar": [{"buz": 1}]},
            #{"id": 2, "bar": [{"bat": 1}]},
        ]
    )
```

result

```
[None, [{'buz': 1}]]
```

so just the None check?

**Comment by zzzeek** [comment]
i guess the idea is that in the first case we are doing a second _proc_array for no reason, but it works out anyway IIRC

**Comment by CaselIT** [comment]
yes, I think we could do both fixes actually. array_agg can set the dimension to 1, and we can avoid crashing on None

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improve array_agg and Array processing** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4083
