### ISSUE TITLE
Replace default behavior of .match in PostgreSQL

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#7086]
### Describe the bug

This is a feature request for a breaking change, but would better standardize behavior in SQLAlchemy across database backends.

Under PostgreSQL, the current behavior of `.match()` is to emit a `to_tsquery()` element.  The input of `to_tsquery` is a specially formatted query text. ( See https://www.postgresql.org/docs/13/textsearch-controls.html , section "12.3.2. Parsing Queries". )

> to_tsquery creates a tsquery value from querytext, which must consist of single tokens separated by the tsquery operators & (AND), | (OR), ! (NOT), and <-> (FOLLOWED BY), possibly grouped using parentheses. In other words, the input to to_tsquery must already follow the general rules for tsquery input, as described in Section 8.11.2. The difference is that while basic tsquery input takes the tokens at face value, to_tsquery normalizes each token into a lexeme using the specified or default configuration, and discards any tokens that are stop words according to the configuration.

> plainto_tsquery transforms the unformatted text querytext to a tsquery value. The text is parsed and normalized much as for to_tsvector, then the & (AND) tsquery operator is inserted between surviving words

> phraseto_tsquery behaves much like plainto_tsquery, except that it inserts the <-> (FOLLOWED BY) operator between surviving words instead of the & (AND) operator. Also, stop words are not simply discarded, but are accounted for by inserting <N> operators rather than <-> operators. This function is useful when searching for exact lexeme sequences, since the FOLLOWED BY operators check lexeme order not just the presence of all the lexemes.

> websearch_to_tsquery creates a tsquery value from querytext using an alternative syntax in which simple unformatted text is a valid query. Unlike plainto_tsquery and phraseto_tsquery, it also recognizes certain operators. Moreover, this function will never raise syntax errors, which makes it possible to use raw user-supplied input for search.

Because the input for `to_tsquery` is expected to be a specially formatted querystring, this introduces compatibility issues to developer code when multiple databases are supported -- as the `match()` function in mysql mssql and sqlite appear to accept plaintext inputs.

The 2.0 (and 1.5 if we do it) versions of SQLAlchemy should switch the default behavior to utilize `plainto_tsquery`, which operates more closely to the matching syntax on the other databases.

### To Reproduce

```python
# Executing a simple query against multiple different backends, such as:

select(mytable.c.id).where(
    mytable.c.title.match('somestring')
)
```

Alternately, we could explore the idea of using substring matching or something similar.

### Error

# none

### Versions

- OS:
- Python:
- SQLAlchemy: 1.4
- Database:
- DBAPI:

### Additional context

Descoped from: #3160

Related behavior: #7081

**Comment by jvanasco** [comment]
IMHO:

* 1.4 - NO
* 1.5 - If we do a 1.5, Yes.
* 2.0 - Yes

I can handle this PR when the main branch is right for it.

**Comment by zzzeek** [comment]
so this is a seriously completely backwards incompatible change for PostgreSQL users, is that right?

**Comment by jvanasco** [comment]
It's potentially backwards incompatible for PostgreSQL users, but it would better standardize code to be backend-agnostic.

`.match(` utilizes PostgreSQL's `to_tsquery`, which expects a PostgreSQL specific "query micro-language" - not a plaintext matching or something standardized as one might expect.

Because of this, I don't think many SQLAlchemy users purposefully use it and would consider it a bug.  I am inclined to think the vast majority of users who utilize `.match` expect it to work differently (as the PR suggests), and anyone who wants to leverage this functionality has dug deep enough into the docs of both projects and migrated their code to explicitly invoke it.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use plainto_tsquery for PG match** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3847

**Comment by zzzeek** [comment]
im not sure if you had a PR for this somehwere already, just did a gerrit.  can you review?
