### ISSUE TITLE
why don't we warn for this?  (obviously wrong remote side)

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7094]
```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", primaryjoin="remote(A.id) == B.a_id")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs=[B()]))
s.commit()


a1= s.query(A).first()
print(a1.bs)
```

we get a predictably broken lazyload

```
SELECT b.id AS b_id, b.a_id AS b_a_id 
FROM b, a 
WHERE a.id = b.a_id

```

if we have a relationship between two classes mapped to different tables, using remote() on the wrong side should just be an error, full stop, for now at least a warning.  should be no use case for that.

**Comment by aminalaee** [comment]
Should this be warned/errored with the `sqlalchemy.orm.remote` too?

```python
...
class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    # bs = relationship("B", primaryjoin="remote(A.id) == B.a_id")
    bs = relationship("B", primaryjoin=remote(id) == B.a_id)
```

This produces the same query as yours and no warning is given.

**Comment by zzzeek** [comment]
> Should this be warned/errored with the `sqlalchemy.orm.remote` too?
> 
> ```python
> ...
> class B(Base):
>     __tablename__ = 'b'
>     id = Column(Integer, primary_key=True)
>     a_id = Column(ForeignKey("a.id"))
> 
> 
> class A(Base):
>     __tablename__ = 'a'
> 
>     id = Column(Integer, primary_key=True)
>     data = Column(String)
>     # bs = relationship("B", primaryjoin="remote(A.id) == B.a_id")
>     bs = relationship("B", primaryjoin=remote(id) == B.a_id)
> ```
> 
> This produces the same query as yours and no warning is given.

that's the equivalent statement so yes that will warn too when we implement this.

**Comment by aminalaee** [comment]
I can pick that up.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**warn for local-only column in remote side** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4101

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**warn for local-only column in remote side** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4102
