### ISSUE TITLE
Filtering a field `in_` a list of Enum values breaks PostgreSQL CAST operator

### ISSUE THREAD

**Issue by jordan-dimov** [sqlalchemy/sqlalchemy#7097]
### Describe the bug

When I have Python code like this:

    query.filter(models.MyModel.state.in_(states))

where `states` is a list of Enum values, it translates to the following SQL:

    WHERE models_mymodel.state IN CAST((:state_1_1, :state_1_2) AS emodelstate))]
    [parameters: {'state_1_1': 'PENDING', 'state_1_2': 'STARTING'}]

which breaks with:

    sqlalchemy.exc.DatabaseError: (common.aurora_data_api.exceptions.DatabaseError) An error occurred (BadRequestException) when calling the ExecuteStatement operation: ERROR: syntax error at or near "CAST"

I tried some things manually in PostgreSQL and noticed that if I do: `select CAST('PENDING' AS emodelstate)` that works fine and gives me an actual DB Enum value. But if I try to cast more than one value: `select CAST(('PENDING', 'STARTING') AS emodelstate)` this fials with `ERROR:  cannot cast type record to emodelstate`.

### To Reproduce

```python
See description.
```

### Error

See description. 

### Versions

- OS: Ubuntu 20.04
- Python: 3.8
- SQLAlchemy: 1.4.25
- Database: PostgreSQL 12.8
- DBAPI:

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. Are you using psycopg2?

**Comment by jordan-dimov** [comment]
Yes, psycopg2 v. 2.9.1

**Comment by CaselIT** [comment]
it would be great it you could post how the model was defined also

**Comment by jordan-dimov** [comment]
The model is rather trivial, the only interesting thing about it is that it has an Enum field, like this:

```
from enum import Enum
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.ext.declarative import declarative_base, DeclarativeMeta

Base: DeclarativeMeta = declarative_base()


class EModelState(str, Enum):
    PENDING = "pending"
    STARTING = "starting"


class MyModel(Base):
    state = Column(SQLEnum(EModelState))

```

**Comment by neilferreira** [comment]
I am currently encountering the same issue - This issue relates to https://github.com/cloud-utils/sqlalchemy-aurora-data-api and would (presumably) be better placed in that project.

**Comment by zzzeek** [comment]
this issue got missed somehow.  that CAST is clearly wrong and there is complex rewrite logic that's supposed to get it right.  if someone can make an MCVE that can get us started otherwise I'll try to look in the coming days.

**Comment by zzzeek** [comment]
ah OK , read that correctly, this is in aurora specifically.     in SQLAlchemy 2.0, we have a specialized casting feature here for DBAPIs like asyncpg but using a test case it renders correctly:

```sql
SELECT m.id, m.state 
FROM m 
WHERE m.state IN (%s::emodelstate, %s::emodelstate)
2022-02-23 10:53:45,482 INFO sqlalchemy.engine.Engine [generated in 0.00099s] ('PENDING', 'STARTING')
```

so yes this is third party driver issue.
