### ISSUE TITLE
scalars for async scope session

### ISSUE THREAD

**Issue by Bechma** [sqlalchemy/sqlalchemy#7103]
### Describe the use case

I think it's related with #6991 , when I use the scalars method with the async scoped session it gives me an attribute error.
I see the implementations in the AsyncEngine and AsyncSession, but it looks that there is no implementation for the async_scoped_session

AttributeError: 'async_scoped_session' object has no attribute 'scalars'

### Databases / Backends / Drivers targeted

PostgreSQL with asyncpg driver

### Example Use

```python
...
engine = create_async_engine(db_connstring)
session = async_scoped_session(
    sessionmaker(bind=engine, expire_on_commit=False, class_=AsyncSession),
    scopefunc=current_task)
rows = await session.scalars(select(TableOne))
...
```

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. I guess the same is true for scoped_session.

@zzzeek do you think we could automate testing for this, so that we catch similar issues in the future?

**Comment by zzzeek** [comment]
im not really sure because the scoped objects don't track every attribute

**Comment by CaselIT** [comment]
maybe we could have a test with a ignore_list when check that all other attributes are mapped. so what if something is added there is a conscious choice if it should also be in the scoped object or not

**Comment by zzzeek** [comment]
OK, we can flip our existing tests to use ignore list instead if you want to try that.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **master** branch:

**Add missing methods added in :ticket:`6991`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3112

**Comment by sqla-tester** [comment]
**Grey Li** referenced this issue:

**Add separate version notes for scalars** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4470

**Comment by sqla-tester** [comment]
**Grey Li** referenced this issue:

**Add separate version notes for scalars** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4473
