### ISSUE TITLE
test_reflection fails when running against MariaDB 10.6

### ISSUE THREAD

**Issue by 9EOR9** [sqlalchemy/sqlalchemy#7115]
### Describe the bug

test_reflection fails when running with mariadb connector or against MariaDB server > 10.6.0:

- Default character set for mariadb dialect is utf8mb4 - it cannot be changed.
- Since MariaDB 10.6.1 utf8 character set is mapped to utf8mb3 (and will be mapped to utf8mb4 in 10.7). See https://jira.mariadb.org/browse/MDEV-8334.

Proposed solution: when testing against a MariaDB server or with mariadb dialect, use character set utf8mb4 instead of utf8.

### To Reproduce

```python
pytest  --dburi=mariadb+mariadbconnector://foobar:foobar@127.0.0.1:3306/test test/dialect/mysql/test_reflection.py
```

### Error

```
_______________________ ReflectionTest_mariadb+mariadbconnector_10_6_4.test_reflection_with_table_options ________________________
Traceback (most recent call last):
  File "/home/georg/work/python/sqlalchemy/test/dialect/mysql/test_reflection.py", line 341, in test_reflection_with_table_options
    assert def_table.kwargs["mariadb_default_charset"] == "utf8"
AssertionError: assert 'utf8mb4' == 'utf8'
  - utf8
  + utf8mb4
```

### Versions

- OS: Linux
- Python: 3.9.6
- SQLAlchemy: master branch, latest version
- Database: MariaDB 10.6
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): mariadbconnector

**Comment by zzzeek** [comment]
can you note "FIxes: #7115" in the commit message of your PR so it links here.   We've already had some 10.6 things so I need to make this available on our CI containers first, then I will test manually this PR against it, then I will get it up into master and we can add 10.6 to our CI.

**Comment by jvanasco** [comment]
Just noting `utf8mb4` is already used throughout the docs and code for connection strings.

**Comment by sqla-tester** [comment]
**Georg Richter** has proposed a fix for this issue in the **master** branch:

**Test fix for #7115** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3118

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**support utf8mb3 char encoding fully for mysqlclient, others** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3125

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_3** branch:

**support utf8mb3 char encoding fully for mysqlclient, others** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3126
