### ISSUE TITLE
Can a normal connection with connection_fairy be used in dialect initialize()?

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7122]
Currently the connection created in the `first_connect` used to initialize the dialect uses a dbapi_connection directly, not a connection fairy like all other:

https://github.com/sqlalchemy/sqlalchemy/blob/257f9130c321aaa948690d0e49c7352ad1188abd/lib/sqlalchemy/engine/create.py#L675-L694

Ideally it should be the same as the other ones, so it should use a connection fairy.

This is a breaking change, so targeting 2.0

**Comment by zzzeek** [comment]
can you point to the code that would be consuming this differently?

**Comment by zzzeek** [comment]
can we add attributes to Connection that come from connection fairy:

dbapi_connection
driver_connection

then consuming dialects will use those,along with this change being made.

**Comment by CaselIT** [comment]
> 
> 
> can you point to the code that would be consuming this differently?

all the initialize code would be doing this. Like https://github.com/sqlalchemy/sqlalchemy/blob/fee0855bfe2982927ab21ce7398fa48b90af7ca4/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L962-L965

**Comment by CaselIT** [comment]
seems mostly the `set_isolation_level` call.

> 
> 
> can we add attributes to Connection that come from connection fairy:
> 
> dbapi_connection driver_connection
> 
> then consuming dialects will use those,along with this change being made.

are you proposing to jsut add these properties or to also use the fairy? just to make sure

**Comment by zzzeek** [comment]
i meant both.  however, if all the dialects refer to connection.dbapi_connection / .driver_connection, then it doesn't matter as much if we are passing dbapi_connection or fairy to Connection in the initialize(), as long as Connection knows how to get to .dbapi_connection.  but we might as well make it consistent.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**provide connectionfairy on initialize** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3331
