### ISSUE TITLE
Create a new loader that's like dynamic but uses v2 syntax

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7123]
### Describe the use case

The current relationship dynamic lazy loader returns a query object.

This new lazy loader would instead present a 2.0 interface, so it would offer the methods `select()`, `insert()`, etc

Regarding the name, mike suggested `statement_only`, but that's still wip

### Databases / Backends / Drivers targeted

All

### Example Use

```py
loaded = session.scalars(User.address.select()).all()
```

**Comment by zzzeek** [comment]
Well just "select()" and I suppose update(), delete().   insert()...OK I guess we can pre-populate the values, sure

**Comment by CaselIT** [comment]
yes, that's the idea. basically instead of dynamic that pre-populates a `Query` we get this new one that pre-polupates normal constructs

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement write-only colletions, typing for dynamic** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4104

**Comment by CaselIT** [comment]
So in the end you want to go for a write only relationship, not one that allows for creating also selects?

**Comment by zzzeek** [comment]
oh you can create selects with it, but that's a select() statement you would run separately.  the collection itself never loaded anything or iterated.

**Comment by zzzeek** [comment]
the main thing is, you expect this collection to have a million records, so under no circumstances should it ever iterate the whole collection implicitly.  turns out dynamic relationships do this all over the place

**Comment by CaselIT** [comment]
oh ok, makes sense. write only maybe is not the correct name for it.

I don't have a correct name for it though. Some ideas that are bad could be "unloaded" / "db-only" / "no-load" / "never-load". All are bad

**Comment by zzzeek** [comment]
well , can you read from it?  no.  can you write to it?  yes.

**Comment by CaselIT** [comment]
well technically you can using select

**Comment by zzzeek** [comment]
from a Python perspective, the "collection" object itself will not allow you to read from it.  you can of course query the database.   I mean, WriteOnlyInPythonButOfCourseYouCanSelectTheActualData

**Comment by zzzeek** [comment]
I guess "dynamic" got around this because "dynamic can mean anything, it's vague"

**Comment by CaselIT** [comment]
maybe we should find another word that's as abstract as dynamic :)

**Comment by zzzeek** [comment]
so the words "no-load" etc. it seems you are going for "load" to be more specific than "read", so on the other side "Persist" would be more specific than "Write", though it's not that clear what PersistOnly means.      I think the most fundamental name might be "NonIterable".  since "we dont want to iterate it" is the main thing that's special here

**Comment by zzzeek** [comment]
Here is the feature.   A 2.0 version of "dynamic" loaders, where we are trying to keep the "execute a SELECT" boundary completely clear.  for collections that are too large to efficiently iterate without criteria to limit the rows. 

```py

# say you load User, and User.addresses is a huge collection.  300K rows
some_user = session.get(User, 1)

# you can append to the collection to persist new items
some_user.addresses.append(Address(email_address='x'))

# you can make a select out of it and execute the statement, so you can load rows
# for that object, sure.  but it forces you to write a SELECT so you aren't inadvertently
# loading millions of rows by accident
address_obj = session.scalars(some_user.addresses.select().where(Address.email_address == 'x')).all()

# so you can't iterate it - because say theres 300K addresses and your program would
# crash if it did this without a very good reason
list(some_user.addresses)   # <--- raises an error.   

```

now what do we call it?

```py

class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: WriteOnlyMapped[Address] = relationship().write_only()

class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: NeverLoadMapped[Address] = relationship().never_load()

class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: NeverLoad[Address] = relationship().never_load()

class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: NoLoadMapped[Address] = relationship().no_load()

class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: NoIterateMapped[Address] = relationship().no_iterate()

class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: LargeCollectionMapped[Address] = relationship().large_collection()

class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: MutateOnlyMapped[Address] = relationship().mutate_only()

class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: PersistOnlyMapped[Address] = relationship().persist_only()


```

**Comment by miguelgrinberg** [comment]
I'm going to contribute one more option. I think of these weird write-only collections as "remote".  You can add or remove from them, but they are not local to the process, thus they are not directly accessible. What do you think?

```python
class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: RemoteMapped[Address] = relationship().remote()
```

I think the term "remote collection" is a good analogy for this pattern.

**Comment by zzzeek** [comment]
thanks for the contribution!   might be a good idea.   or "indirect" or something like that

"lazy" is not going away, that's staying, and lazy="dynamic" lazy="whatever_this_is" will work too, the XYZMapped[] part is for the type-based annotations to work.

**Comment by zzzeek** [comment]
```py
class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: UnloadedMapped[Address] = relationship().unloaded()
```

**Comment by zzzeek** [comment]
```py
class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: CollectionWriter[Address] = relationship().collection_writer()
```

**Comment by CaselIT** [comment]
After some talk on the dev metting we could not come up with anything better than `WriteOnlyMapped`. So we are calling it that for the beta. if something better comes out before non beta versions we can consider updating.

```py
class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: WriteOnlyMapped[Address] = relationship(lazy='write_only')
```

@zzzeek any reason for using `relationship().write_only()` instead of `relationship(lazy='write_only')`?

@miguelgrinberg thanks for the suggestion. Remote may also fit, but there is already a "remote" concept in the relationship mapping and it would probably cause confusion. https://docs.sqlalchemy.org/en/14/orm/relationship_api.html?highlight=remote#sqlalchemy.orm.remote

**Comment by zzzeek** [comment]
> After some talk on the dev metting we could not come up with anything better than `WriteOnlyMapped`. So we are calling it that for the beta. if something better comes out before non beta versions we can consider updating.
> 
> ```python
> class User(Base):
>     __tablename__ = "user"
>     id: Mapped[int] = mapped_column(primary_key=True)
>     addresses: WriteOnlyMapped[Address] = relationship(lazy='write_only')
> ```
> 
> @zzzeek any reason for using `relationship().write_only()` instead of `relationship(lazy='write_only')`?

yes, unfortunately we need either that, or a different function other than relationship(), for the typing to work out, so that there's no typing error generated for WriteOnlyMapping on the left side.   We need WriteOnlyMapping (or DynamicMapping) then because again for typing, "dynamic" and "write only" relationships don't act like Mapped[] at all:

```py
    def write_only(self) -> WriteOnlyMapped[_T]:
        """Modify this :class:`.Relationship` to be a "write only"
        relationship.

        ...
        """
        self.lazy = "write_only"
        self.strategy_key = (("lazy", self.lazy),)
        return self  # type: ignore

```

in ancient SQLAlchemy, we used the ``dynamic()`` function directly instead of ``relationship()``.  So we could also do something like this:

```py
class User(Base):
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    addresses: WriteOnlyMapped[Address] = write_only()
```

that gets weird though because then we have to copy all the parameters from `relationship()` to `write_only()`, and it also gets hard to explain how ``dynamic()`` and ``write_only()`` are the same as ``relationship()``.   Making them methods instead means we just have two little methods, that you dont even need if you dont care about typing.  it's less to explain

**Comment by CaselIT** [comment]
> for the typing to work out

Can't we do that with overloads? Also there is always the option of making relationship return Any, pretty much how dataclass `field` works

**Comment by zzzeek** [comment]
> > for the typing to work out
> 
> Can't we do that with overloads? 

overloads on...relationship() function?   we could yes, though users would then have to explicitly state "lazy='write_only'" for the overload to take place, so in that case something about the right side has to change to match the alternate left side.

overloads here are burdensome since they only work if you duplicate the entire argument list of the original function each time, and relationship has an enormous argument list.   So this seems not worth it.


> Also there is always the option of making relationship return Any, pretty much how dataclass `field` works

I'm generally -1 on using Any, as this would start to leak into all the ORM constructs that currently implement Mapped where we need to make something work.

Here's something that does work.   we move the evil into the top of Relationship like this, then everything works:

```diff
diff --git a/lib/sqlalchemy/orm/relationships.py b/lib/sqlalchemy/orm/relationships.py
index 7f84db9e92..d70c2cffae 100644
--- a/lib/sqlalchemy/orm/relationships.py
+++ b/lib/sqlalchemy/orm/relationships.py
@@ -289,8 +289,12 @@ class _RelationshipArgs(NamedTuple):
 
 
 @log.class_logger
-class Relationship(
-    _IntrospectsAnnotations, StrategizedProperty[_T], log.Identified
+class Relationship(  # type: ignore
+    _IntrospectsAnnotations,
+    StrategizedProperty[_T],
+    log.Identified,
+    WriteOnlyMapped[_T],
+    DynamicMapped[_T],
 ):
     """Describes an object property that holds a single item or list
     of items that correspond to a related database table.
diff --git a/test/ext/mypy/plain_files/dynamic_rel.py b/test/ext/mypy/plain_files/dynamic_rel.py
index 0f81e60f4f..78bf15f5f2 100644
--- a/test/ext/mypy/plain_files/dynamic_rel.py
+++ b/test/ext/mypy/plain_files/dynamic_rel.py
@@ -27,7 +27,7 @@ class User(Base):
     id: Mapped[int] = mapped_column(primary_key=True)
     addresses: DynamicMapped[Address] = relationship(
         cascade="all,delete-orphan"
-    ).as_dynamic()
+    )
 
 
 with Session() as session:
diff --git a/test/ext/mypy/plain_files/write_only.py b/test/ext/mypy/plain_files/write_only.py
index ff82f5aaa6..672630ee66 100644
--- a/test/ext/mypy/plain_files/write_only.py
+++ b/test/ext/mypy/plain_files/write_only.py
@@ -25,7 +25,7 @@ class Address(Base):
 class User(Base):
     __tablename__ = "user"
     id: Mapped[int] = mapped_column(primary_key=True)
-    addresses: WriteOnlyMapped[Address] = relationship().write_only()
+    addresses: WriteOnlyMapped[Address] = relationship()
 
 
 with Session() as session:
```


I really dont like having a type:ignore up there.  but this produces the best end result so far.

**Comment by zzzeek** [comment]
Using relationship() -> Any has some failures where I wanted non-annotated mappings to still detect that an attribute was instrumented:

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test/ext/mypy/test_mypy_plugin_py3k.py", line 326, in test_files
    assert False, "expected messages not found, see stdout"
AssertionError: expected messages not found, see stdout
assert False
-------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------
Couldn't locate expected messages: ['Revealed type is "sqlalchemy.*.InstrumentedAttribute\\[Any\\]"', 'Revealed type is "sqlalchemy.*.InstrumentedAttribute\\[Any\\]"', 'Revealed type is "sqlalchemy.*.InstrumentedAttribute\\[Any\\]"']
test/ext/mypy/plain_files/traditional_relationship.py:89: note: Revealed type is "Any"
test/ext/mypy/plain_files/traditional_relationship.py:95: note: Revealed type is "Any"
test/ext/mypy/plain_files/traditional_relationship.py:107: note: Revealed type is "Any"
```

so...yeah we are already "cheating" with the approach, in that Relationship, ColumnProperty etc. are "Mapped[]", because they really aren't - they have that in their MRO so that this typing thing works.  But Relationship / ColumnProperty don't actually implement the descriptor or operator protocol, so they are lying.   So.....it's weird right.

**Comment by CaselIT** [comment]
note that I'm fine with `.dynamic()` / `.write_only()`. Just thinking if there are alternatives

**Comment by CaselIT** [comment]
at worst 
```py
def dynamic_relationship(*args,**kw):
  return relationship(*args, **kw).dynamic()
def write_only_relationship(*args,**kw):
  return relationship(*args, **kw).write_only()
```
but we would lose all argument information, so probably -1

**Comment by zzzeek** [comment]
I'm going to go with this, assuming it all works

```py

class Relationship(  # type: ignore
    RelationshipProperty[_T], _DeclarativeMapped[_T],
    WriteOnlyMapped[_T],  # not compatible with Mapped[_T]
    DynamicMapped[_T],  # not compatible with Mapped[_T]
):
```

that puts the "cheating" just on the end without it affecting our ability to have accurate typing for internals

**Comment by CaselIT** [comment]
As you prefer. This way the lazy is set by looking at the left side, right?

**Comment by zzzeek** [comment]
yes, it was doing that already
