### ISSUE TITLE
sql server _ODBCDATETIMEOFFSET does not have correct superclasses

### ISSUE THREAD

**Issue by lukesmurray** [sqlalchemy/sqlalchemy#7129]
**Describe the bug**

When using a [sqlalchemy custom type](https://docs.sqlalchemy.org/en/14/core/custom_types.html) the incorrect data type is being generated in the migrations.

I'm using the following custom type to store and load datetime objects with utc.

```python
class TZTimestamp(TypeDecorator):
    """A new sqlalchemy column that is timezone aware

    Uses TIMESTAMP or datetime2
    """

    impl = TypeEngine  # placeholder since we use load_dialect_impl
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "mssql":
            return dialect.type_descriptor(DATETIMEOFFSET())
        else:
            return dialect.type_descriptor(TIMESTAMP())

    def process_bind_param(self, value, dialect):
        # prevent storing unaware datetimes
        # if not isinstance(value, datetime.datetime):
        #     raise ValueError(f"{value} must be a datetime.datetime")
        if isinstance(value, datetime.datetime) and value.tzinfo is None:
            raise ValueError(f"{value} must be TZ-aware")
        # # convert the value to utc time
        # value = value.astimezone(pytz.UTC)

        if dialect.name == "mssql":
            return value.isoformat()

        return value

    def process_result_value(self, value, engine):
        # make returned datetimes timezone aware (they are already utc)
        return value.replace(tzinfo=pytz.UTC)
```

The `load_dialect_impl` function is used to fallback on a `DateTimeOffset()` implementation for mssql and otherwise use a `Timestamp()`.

For some reason the mssql data type generated by alembic is a `datetime`.

**Expected behavior**

The mssql data type would be a `DateTimeOffset()`

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

```py
# Insert code here
```

**Error**

```
# Copy error here. Please include the full stack trace.
```

**Versions.**
 - OS: debian-buster
 - Python: 3.9
 - Alembic: 1.6.2
 - SQLAlchemy: 1.4.14
 - Database: mssql 16
 - DBAPI:  ODBC Driver 17 for SQL Server

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
proposed patch:

```diff
diff --git a/lib/sqlalchemy/dialects/mssql/pyodbc.py b/lib/sqlalchemy/dialects/mssql/pyodbc.py
index a27a3c5d02..cc2e026308 100644
--- a/lib/sqlalchemy/dialects/mssql/pyodbc.py
+++ b/lib/sqlalchemy/dialects/mssql/pyodbc.py
@@ -381,7 +381,7 @@ class _ODBCDateTime(sqltypes.DateTime):
         return process
 
 
-class _ODBCDATETIMEOFFSET(_ODBCDateTime):
+class _ODBCDATETIMEOFFSET(DATETIMEOFFSET, _ODBCDateTime):
     has_tz = True
 
 

```

regression is related to #6366

**Comment by zzzeek** [comment]
i think your case can work for now if you just return DATETIMEOFFSET() and don't do the type_descriptor() part.

**Comment by lukesmurray** [comment]
I'll try and let you know

**Comment by lukesmurray** [comment]
this worked

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**organize datetime types for correct impls** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3120
