### ISSUE TITLE
Calling sqlalchemy.engine.URL directly bypasses input validation

### ISSUE THREAD

**Issue by rolandseubert** [sqlalchemy/sqlalchemy#7130]
### Describe the bug

This issue relates to commit https://github.com/sqlalchemy/sqlalchemy/commit/3668b3a30c4b9a9f4af13457f43bfc34c28cf448.

Even though factory method [`sqlalchemy.engine.URL.create`](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.engine.URL.create) is now the recommended constructor, it is still possible to call [`sqlalchemy.engine.URL`](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.engine.URL) directly. Doing so by supplying the seven parameters as positional instead of keyword arguments will not raise the deprecation warning, bypass the input validation of the recommended constructor method and cause errors in other methods, such as [`sqlalchemy.engine.URL.render_as_string`](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.engine.URL.render_as_string).

### To Reproduce

```python
import sqlalchemy

# supplying drivername not as a regular string
drivername = b'driver'

# creating a URL via the recommended constructor will correctly raise TypeError: drivername must be a string
url = sqlalchemy.engine.URL.create(drivername=drivername, username='user', password='secret', host='10.20.30.40', port=1234, database='DB', query={'key': 'value'})

# creating a URL by calling the class directly will not validate the input and instead accept the bytes string
url = sqlalchemy.engine.URL(b'driver', 'user', 'secret', '10.20.30.40', 1234, 'DB', {'key': 'value'})

# will raise TypeError: can't concat str to bytes
print(url)
```

### Error

See code example above.

### Versions

- OS: Windows 10
- Python: 3.7.9
- SQLAlchemy: 1.4.24
- Database: not applicable
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): not applicable

**Comment by CaselIT** [comment]
Hi,

I think that's the expected behavior. `URL` is a named tuple, so the constructor is generated by python. The `create()` method ultimately calls the constructor.

I'm not sure if there is a better way of doing the above

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**indicate private use of URL.__new__ privately only** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3121

**Comment by zzzeek** [comment]
it's a bug

**Comment by CaselIT** [comment]
well that works I guess.
