### ISSUE TITLE
incosnsitent any() between col.any_() == <value> vs. null

### ISSUE THREAD

**Issue by avilaton** [sqlalchemy/sqlalchemy#7140]
### Describe the bug

We were surprised with a syntax error when `'ANY(role.zone_ids) IS NULL'` was rendered unexpectedly. The code that generated it used `.filter(sqlalchemy.any_(Role.zone_ids) == some_variable)` which apparently correctly when worked correctly when `some_variable = 5` but rendered with the equal sign flipped when `some_variable = None`.

### To Reproduce

Given an array column `zone_ids` on table `role`, the expression

```python
sqlalchemy.any_(Role.zone_ids).is_(None)
```
renders to `'ANY(role.zone_ids) IS NULL'` fails with `syntax error at or near "ANY"` on postgresql.
It renders correctly when using
```
Role.zone_ids.any(None)
```
which renders to `'NULL = ANY (role.zone_ids)'`.

### Error

```
SELECT * FROM role WHERE ANY (role.zone_ids) IS NULL;
syntax error at or near "ANY"
LINE 1: SELECT * FROM role WHERE ANY (role.zone_ids) IS NULL
``` 

### Versions

- OS: ubuntu 16.04
- Python: 3.5
- SQLAlchemy:1.3.24
- Database:Postgresql 13
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2

### Additional context

We found a test for the ANY expression at https://github.com/sqlalchemy/sqlalchemy/blob/79a27c9fcb1ba4909834a7e2d51c29afb0688cd5/lib/sqlalchemy/sql/elements.py#L3635 and will contribute a PR if pointed to where it would be correct to implement a fix for this if possible.

**Comment by zzzeek** [comment]
hi -

this operator is not just for PostgreSQL, it also applies to MySQL and possibly other backends, so generically i think it's important that it not have any surprises.   The above issue you report does not seem to be a surprise to me, it looks like the SQL code is rendering exactly as the Python code you've given it, and the function is behaving consistently here in a standalone vs. method context:

```py
>>> print(column('q').any_() == None)
ANY (q) IS NULL
>>> print(column('q').any_().is_(None))
ANY (q) IS NULL
```
this is no different from any other parenthesized SQL element.

If I wanted to render "NULL == ANY(expr)", I would do just that, pull NULL on the left side:

```py
>>> from sqlalchemy import column, any_, null
>>> print(null() == column('q').any_())
NULL = ANY (q)
>>> print(null() == (any_(column('q'))))
NULL = ANY (q)
```

SQLAlchemy is going to try to be as WYSIWYG, so IS renders IS:

```py
>>> print(null().is_(column('q').any_()))
NULL IS ANY (q)
>>> print(null().is_(any_(column('q'))))
NULL IS ANY (q)
```

etc.

I do see some documentation issues to be fixed however, such as a lack of cross-linking between column.any_() and standalone any_(), as well as misleading docs on posgresl.ARRAY.any_() suggesting the method is "legacy" which it's not.

**Comment by zzzeek** [comment]
> which apparently correctly when worked correctly when some_variable = 5

i missed that part.  sorry this is inconsistent.

**Comment by zzzeek** [comment]
to be fair, the documentation for any_() / all_() illustrate the subject expression on the left hand side:

https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.all_

im not sure of the history of this "flip the expression" behavior but it does not seem to be documented

**Comment by avilaton** [comment]
Thanks Mike for such a quick response. If you have any tips on how we could prevent this inside sqlalchemy just let us know.
We looked at https://github.com/sqlalchemy/sqlalchemy/blob/3866e931e8858311aab25dffe62651c496b7150c/lib/sqlalchemy/sql/sqltypes.py#L2832-L2838 and have a hunch that this BinaryExpression does the flipping when one side is Null, but we are not sure if that is correct and how you would prefer to deal with it.

**Comment by zzzeek** [comment]
short answer, coumn(ARRAY).any_() is completely different from column(ANYTHINGELSE).any_() so that's where this starts to go wrong

**Comment by avilaton** [comment]
don't be too hard on sqlalchemy, our code is miles under the water in comparison and we only caught this years later

**Comment by zzzeek** [comment]
can you carefully clarify the any_() / any() function you are using?  There is no "sqlalchemy.any()".

**Comment by zzzeek** [comment]
also FYI I dont plan to change the is_() case here, that does not seem relevant.  you would use "==" / "!=" here for the operator which is what you stated you were doing anyway.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**repair any_() / all_() "implicit flip" behavior for None** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3129

**Comment by avilaton** [comment]
> can you carefully clarify the any_() / any() function you are using? There is no "sqlalchemy.any()".

I updated the bug report, we use `sqlalchemy.any_`, sorry for that.
