### ISSUE TITLE
Add missing json/jsonb operators in PostgreSQL

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7147]
Since the json/jsonb support in SQLAlchemy was added PostgreSQL has added some new operators, like `@@` and `@?` in v12 https://www.postgresql.org/docs/12/datatype-json.html

It would be nice to add the missing operators to the relevant types.

One thing to finalize are the names of these operators, that are not immediately clear from the postgresql docs

First raised in https://github.com/sqlalchemy/sqlalchemy/discussions/7146

**Comment by CaselIT** [comment]
I'm not sure regarding the names, they seem to refer to other functions. In the v14 docs they are better defined https://www.postgresql.org/docs/current/functions-json.html but they are not better defined

**Comment by jvanasco** [comment]
Re-reading my comment above, my text is not clear.

I believe `@@` and `@?` are shorthand for some of the named functions but WITH preconfigured defaults.  The operators are not named and do not behave exactly like the functions, but the functions can be passed arguments to make them behave like the operators.

Referencing the v14 docs....

---

> # jsonb @? jsonpath → boolean
> Does JSON path return any item for the specified JSON value?
> `'{"a":[1,2,3,4,5]}'::jsonb @? '$.a[*] ? (@ > 2)' → t`

is *roughly* the same as...

> # jsonb_path_exists ( target jsonb, path jsonpath [, vars jsonb [, silent boolean ]] ) → boolean
> Checks whether the JSON path returns any item for the specified JSON value. If the vars argument is specified, it must be a JSON object, and its fields provide named values to be substituted into the jsonpath expression. If the silent argument is specified and is true, the function suppresses the same errors as the @? and @@ operators do.
> `jsonb_path_exists('{"a":[1,2,3,4,5]}', '$.a[*] ? (@ >= $min && @ <= $max)', '{"min":2, "max":4}') → t

---

and...

---

> # jsonb @@ jsonpath → boolean
> Returns the result of a JSON path predicate check for the specified JSON value. Only the first item of the result is taken into account. If the result is not Boolean, then NULL is returned.
> `'{"a":[1,2,3,4,5]}'::jsonb @@ '$.a[*] > 2' → t`

is *roughly* the same as...

> # jsonb_path_match ( target jsonb, path jsonpath [, vars jsonb [, silent boolean ]] ) → boolean
> Returns the result of a JSON path predicate check for the specified JSON value. Only the first item of the result is taken into account. If the result is not Boolean, then NULL is returned. The optional vars and silent arguments act the same as for jsonb_path_exists.
> `jsonb_path_match('{"a":[1,2,3,4,5]}', 'exists($.a[*] ? (@ >= $min && @ <= $max))', '{"min":2, "max":4}') → t`

**Comment by CaselIT** [comment]
oh it seems so!

Found the definition;
https://github.com/postgres/postgres/blob/0266e98c6b865246c3031bbf55cb15f330134e30/src/backend/utils/adt/jsonpath_exec.c#L377-L387
and
https://github.com/postgres/postgres/blob/0266e98c6b865246c3031bbf55cb15f330134e30/src/backend/utils/adt/jsonpath_exec.c#L309-L319

**Comment by jvanasco** [comment]
ha! i did not expect to see it officially in their code!

* `jsonb_path_exists_opr`
* `jsonb_path_match_opr`

I just noticed the definitions were similar, and recalled some other operators in postgres being shorthand versions of larger functions.

**Comment by zzzeek** [comment]
just those two operators, that's all they added?

**Comment by CaselIT** [comment]
I have not checked if there is something else missing

**Comment by jvanasco** [comment]
Any idea how this works: 

> `json_col[path]` renders `->`

I couldn't find anything in the source that could emit that.

**Comment by jvanasco** [comment]
ah ha!  the code has this string: `" -> "` and I was searching for `"->"` and `'->'` (no leading/trailing whitespace)

**Comment by jvanasco** [comment]
Updated the list above, but the 3 missing ops are:

* `#-`
* `@@`
* `@?`

I'm not sure if `-` or `\|\|` need special enablement for json; I assume not.

**Comment by CaselIT** [comment]
it seems not
```py
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

tt = sa.Table('tt', sa.MetaData(), sa.Column('col', postgresql.JSONB))

sub = tt.c.col - 'x'
concat = tt.c.col + 'x'

print(sub.compile(dialect=postgresql.dialect()))
print(concat.compile(dialect=postgresql.dialect()))
```
prints
```
tt.col - %(col_1)s
tt.col || %(col_1)s
```
