### ISSUE TITLE
Automap: prefer snake_case over lower() for relationship attribute names

### ISSUE THREAD

**Issue by januszm** [sqlalchemy/sqlalchemy#7149]
### Describe the use case

Converting from PascalCase to snake_case when converting class names to database column names and vice versa seems to be common in ORM world and more appropriate than simple lowercase class name substitution. I'd like to suggest changing the standard implementation for the `name_for_scalar_relationship` and `name_for_collection_relationship` methods to snake_case.  Sample implementation below.

### Databases / Backends / Drivers targeted

All

### Example Use

```python
# table 'users' with column 'process_status_id' referencing process_statuses table/relation

Base = automap_base()
class User(Base):
    __tablename__ = 'users'

class ProcessStatus(Base):
    __tablename__ = 'process_statuses'
    
Base.prepare(engine,  reflect=True)
```

### Current behavior:

```python
user = User()
user.processstatus # works
user.process_status
=> 'User' object has no attribute 'process_status'
```

### Proposed:

```python
user = User()
user.process_status # works
user.process_status_id #  returns foreign key ...
```

#### Current implementation

```python
# name_for_scalar_relationship
referred_cls.__name__.lower()

# name_for_collection_relationship
referred_cls.__name__.lower() + "_collection"
```

#### Proposed change:

```python
def to_pascal_case(text):
    return text.replace("_", " ").title().replace(" ", "")

def to_snake_case(text):
    return ''.join([f"_{i.lower()}" if i.isupper()
               else i for i in text]).lstrip('_')

def pluralize(text):
  return ... TBD

def name_for_scalar_relationship(_base, _local_cls, referred_cls, _constraint):
    return to_snake_case(referred_cls.__name__)

def name_for_collection_relationship(...):
  return pluralize(to_snake_case(referred_cls.__name__))
```

**Comment by zzzeek** [comment]
hey there -

using snake case is a great idea and im not sure why i didnt use that.

however, for the time being i can only accept this as new alternate functions that people can select for, along with documenation, unit tests, etc.  changing the default is not something we can handle in the near term as this would be a completely backwards incompatible change that would require a lot of deprecation / migration overhead for us as well as the userbase, as we are already in the middle of some very large changes.

we will gladly review proposals to include these new functions as alternates that can be selected, like "snake_case_scalar_relationship", "snake_case_collection_relationship", something like that.  having the functions available in the codebase etc. would also make it more straightforward to later on switch these functions into being the "default" if we want to try later, when things are not in as much flux.

or these can just be in the documentation as recipes.  but having them included as real code to be imported is also fine.

changing the default however would mean a long series of warnings, deprecations, people getting bit, etc, we are already in the midst of an enormous deprecation sweep with the 2.0 thing coming out so the code idea looks great, just not ready to work through a hard default change right now.

**Comment by zzzeek** [comment]
hit close by mistake, sorry

**Comment by januszm** [comment]
> hit close by mistake, sorry

Happens :trollface:
