### ISSUE TITLE
PostgreSQL 14 multiranges

### ISSUE THREAD

**Issue by lpsinger** [sqlalchemy/sqlalchemy#7156]
### Describe the use case

Support the new [multirange data types](https://www.postgresql.org/docs/14/rangetypes.html#RANGETYPES-BUILTIN) that were [announced in PostgreSQL 14](https://www.postgresql.org/about/news/postgresql-14-released-2318/).

### Databases / Backends / Drivers targeted

PostgreSQL

### Example Use

Some examples copied from the PostgreSQL docs:

```sql
-- literals
SELECT '{}'::int4multirange;
SELECT '{[3,7)}'::int4multirange;
SELECT '{[3,7), [8,9)}'::int4multirange;

-- assembling from ranges
SELECT nummultirange();
SELECT nummultirange(numrange(1.0, 14.0));
SELECT nummultirange(numrange(1.0, 14.0), numrange(20.0, 25.0));
```

**Comment by gmcrocetti** [comment]
@zzzeek , I would love to work on it but I don't have bandwidth to implement all of the types. Do you think it's possible to split this issue in sub-tasks ?

**Comment by zzzeek** [comment]
IIUC if someone is implementing one or two of these it's not much different from implementing them all, it's a list of names to add to a file and some corresponding boilerplate for each.   the existing RANGE types are just listed out based on a common base: https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/postgresql/ranges.py#L105   the test suites are similarly based on a repeated pattern and new datatypes are dropped in:   https://github.com/sqlalchemy/sqlalchemy/blob/fc5c54fcd4d868c2a4c7ac19668d72f506fe821e/test/dialect/postgresql/test_types.py#L3543

so if the correct frameworks were added for whatever new behaviors come from "multiranges", we can add all the types w/ basic test support without much trouble to do all of them vs just a few

**Comment by lpsinger** [comment]
FWIW, here's the application that drove this feature request: https://arxiv.org/abs/2112.06947

**Comment by sqla-tester** [comment]
**zeeeeeb** has proposed a fix for this issue in the **main** branch:

**fixes: #7156 - Adds support for PostgreSQL MultiRange type** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3728

**Comment by zzzeek** [comment]
just FYI we have a real backlog of new features in the queue for 2.0.   i hope to get to all of them in the coming weeks.

**Comment by zzzeek** [comment]
so we have the above review for this issue but it seems to be stalled  @zeeeeeb do you have plans to work on this further?  at the moment I will have to bump the milestone on this otherwise.

**Comment by zeeeeeb** [comment]
@zzzeek yeah I'll take a stab at the updates this evening :+1:

**Comment by zeeeeeb** [comment]
@zzzeek had two [clarifying](https://github.com/sqlalchemy/sqlalchemy/pull/7816/files#r898710248) [questions](https://github.com/sqlalchemy/sqlalchemy/pull/7816/files#r898713708) when you get a chance :+1:

**Comment by zzzeek** [comment]
8cb6fbfb6589078484f29059dab6bd3e3646f938 is a followup commit to clean up the  changelog between the two different changesets and also to credit @zeeeeeb !  thanks very much!

**Comment by auvipy** [comment]
should the milestone updated?

**Comment by zzzeek** [comment]
yup this is in for 2.0
