### ISSUE TITLE
with session.begin() block should not (?) require flush() to take effect

### ISSUE THREAD

**Issue by januszm** [sqlalchemy/sqlalchemy#7166]
### Describe the bug

When creating a new record using the `session.begin()` block, (it looks like) the `id` of the newly created object should be available right after the end of the block. With `autoflush=True` default and `session.begin()`, I would expect that I don't need to call `flush()` again to see the effect. An example below. Alternatively, if it is intentional, it is worth documenting the best practices on how to add a new record and use it immediately in the application code without too much boilerplate code.

### To Reproduce

```python
with db.session.begin():
  record = MyModel(name="foo")
  db.session.add(record)

print(record.id)
# => None
```

### Error

The result of the session.begin() block with session.add does not have the autogenerated attributes (such as an id or timestamps) set.

### Versions

- OS: Mac OS X
- Python: 3.9
- SQLAlchemy: 1.4.23
- Database: Postgresq;
- DBAPI : default for postgresql (`psycopg2           2.9.1`)

### Additional context

I'd expect that at least the first reference to the newly generated record's id (autogenerated) causes session.flush() and attribute setting.

**Comment by zzzeek** [comment]
does your model actually map the "id" attribute?  there's any number of reasons "object.anything" might be None but we can't know without the model that illustrates how to actually reproduce.

overall, you definitely do not need to call flush() to see the effect after a begin() block, whether or not autoflush is in effect - the begin() context manager calls .commit(), which will unconditionally flush in all cases.

**Comment by CaselIT** [comment]
> just curious, are there any plans to , for example, trigger flush after reading the created record's attribute?

That behavior is expected, since you could have many add at one, and it would not be very performant to add each one right away. The same happens for deletes, or updates, they are reflected to db only after a flush (that's triggered automatically be the session before any other db access)

If you find a way to reproduce what you were seeing feel free to reopen so we can try to fix that
