### ISSUE TITLE
Example versioned_update_old_row.py fails

### ISSUE THREAD

**Issue by paullilley** [sqlalchemy/sqlalchemy#7169]
### Describe the bug

Running the example raises an exception
TypeError: is_modified() got an unexpected keyword argument 'passive'
on line 91
```python
 if not session.is_modified(instance, passive=True):
```
Removing the passive=True gets past this exception, but it then fails later on line 243
```python
assert p2_check.child is c1
```

### To Reproduce

```python
https://github.com/sqlalchemy/sqlalchemy/blob/master/examples/versioned_rows/versioned_update_old_row.py
```

### Error

\versioned_update_old_row.py:240: SAWarning: Multiple rows returned with uselist=False for lazily-loaded attribute 'Parent.child'
  c2_check = p2_check.child
Traceback (most recent call last):
  File "\versioned_update_old_row.py", line 243, in <module>
    assert p2_check.child is c1
AssertionError

### Versions

- OS: Windows
- Python: 3.9.7
- SQLAlchemy: 1.4.25
- Database: sqlite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by zzzeek** [comment]
that example comes from something I actually did on a job, which is why i know it "works".  but it sure is a little crazy.   should be good now

**Comment by zzzeek** [comment]
momentarily

**Comment by paullilley** [comment]
Magic.  Thanks for the very quick fix!
