### ISSUE TITLE
`Sequence.start` incorrectly set to 1 when `minvalue` is set

### ISSUE THREAD

**Issue by nzig** [sqlalchemy/sqlalchemy#7211]
### Describe the bug

SQLAlchemy 1.4 will set `Sequence.start` to `1` if it is `None` during `compile()`. This is incorrect because the sequence may have a `minvalue > 1`, which is incompatible with `start == 1`.

### To Reproduce

```python
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def dump(sql, *multiparams, **params):
    print(sql.compile(dialect=engine.dialect))

engine = sa.create_mock_engine('postgresql://', dump)

seq = sa.Sequence("my_seq", minvalue=1001)
print(f"{seq.start=}")
seq.create(engine)
print(f"{seq.start=}")
```

### Error

Output:
```
seq.start=None
CREATE SEQUENCE my_seq START WITH 1 MINVALUE 1001
seq.start=1
```

Running that in Postgres will give:

```
START value (1) cannot be less than MINVALUE (1001)
```

### Versions

- OS: Arch Linux
- Python: 3.9.7
- SQLAlchemy: 1.4.25 (SQLAlchemy-1.4.25-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
- Database: PostgresSQL 13.4
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): N/A

### Additional context

This is a regression from 1.3. I think it is due to [this](https://github.com/sqlalchemy/sqlalchemy/blob/a3884f36f691df81fb5a1c795fe7ecc0c83507b6/lib/sqlalchemy/sql/compiler.py#L4465) code.

**Comment by nzig** [comment]
Thanks for looking into this! A few notes:
1. Maybe this behavior should only be for mssql? At least for postgres I know it does "the right thing" when START is omitted:
> The optional clause START WITH start allows the sequence to begin anywhere. The default starting value is minvalue for ascending sequences and maxvalue for descending ones.
https://www.postgresql.org/docs/14/sql-createsequence.html

2. It's also weird to me that `.compile()` modifies the `Sequence`. Maybe it should render the default `START WITH` but not set it on the object?

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fix start compiling in a sequence.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4097

**Comment by CaselIT** [comment]
Always rendering the start is a bit of a mess, since there are case where we don't know what value we should place to it
I've evidenced some in the tests that probably will render an error.

**Comment by zzzeek** [comment]
I think the ambiguous cases here should raise.  we haven't had any further reports of these issues with sequence for the past two years since 1.4 has been released.   so I think the 1.4 community is fine with what we have for now, can we re-milestone back to 2.0/2.x ?

**Comment by CaselIT** [comment]
I was treating this as a bugfix for the 1.4 series, but if we change it further I guess we could make this 2.0
