### ISSUE TITLE
add excecution_options to session.get()

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7236]
i dont know where we saw this but we need execution_options to be available on session.get().   Additionally, it should be possible to send execution_options to the constructor of a Session (and async session) so that certain options take place for all queries.   Here we are looking at options like "prebuffer_rows" and "populate_existing".   We also may need to check that whether these options are safe, or should be suppressed, within unit of work operations, particularly populate_existing.'

this is tagged at 2.0 to raise priority since it has to be done by 2.0, but should likely be done for 1.4 as well.

edit: the most improant part is #7410 to add execution_options to session.get() which is basically missing, that's for 1.4.  more convenience-oriented issues can be 2.0.

**Comment by kelvin-wong** [comment]
The missing `execution_options` make it impossible in `dogpile.cache` example using `session.get()`.

**Comment by zzzeek** [comment]
you can use query.get() for now.   I will break this out into two issues as the get() part of this is very simple

**Comment by zzzeek** [comment]
I don't care about the fancier features for now, that can be later.
