### ISSUE TITLE
SQLAlchemy 1.4.26 Possibly Resulting in Unusual GCP Memory Usage Spikes

### ISSUE THREAD

**Issue by npai96** [sqlalchemy/sqlalchemy#7240]
### Describe the bug

After updating SQLAlchemy from version 1.4.18 to 1.4.26, we noticed that the memory usage across all GCP Cloud Functions spiked dramatically. See example below:

<img width="1087" alt="Screen Shot 2021-10-25 at 6 13 06 PM" src="https://user-images.githubusercontent.com/35381322/138778928-889d9d5a-a5e3-4ffc-baf5-1bf2f68f4822.png">

The immediate effect of this on system functionality is not obvious, but could lead to more frequent timeouts and connection drops (if it is DB related).
While this could be a one-off issue specific to our codebase, we decided posting here might alert maintainers to potential issues that could affect other developers.

We are unsure of the underlying cause, only that the memory usage returns to normal levels after going back to 1.4.18:
<img width="1103" alt="138515227-87c883d1-af35-4657-beea-677bca48fc68" src="https://user-images.githubusercontent.com/35381322/138779081-2023eebc-b884-4ba5-9850-426d88ed5256.png">

### To Reproduce

```python
Upgrade sqlalchemy to version 1.4.26
Observe changes in Memory Usage for GCP Cloud Functions
```

### Error

No error messages

### Versions

- OS: Debian Bullseye
- Python: `3.7`
- SQLAlchemy: `1.4.26`
- Database: `PostgreSQL 11`
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): `psycopg2`

**Comment by zzzeek** [comment]
please reopen if you have more actionable information.

**Comment by npai96** [comment]
Hi @zzzeek , thank you for your detailed responses over the past few days.

We have been investigating the situation as per your suggestions as well as with the GCP Support Team and found that the memory usage spikes were actually due to a change in the GCP Python environment that increased the thread count from defaulting to 8 instead of 1.

We can hence confirm that this is not a SQLAlchemy issue.

Thanks again for your help!
