### ISSUE TITLE
Missing FILESTREAM option for VARBINARY on MS SQL

### ISSUE THREAD

**Issue by TilmanK** [sqlalchemy/sqlalchemy#7243]
### Describe the use case

When storing large files in a MS SQL database, the MS SQL server offers a FILESTREAM option that stores files in the filesystem instead of the database. 

https://docs.microsoft.com/en-us/sql/relational-databases/blob/create-a-table-for-storing-filestream-data?view=sql-server-ver15

This is faster than storing it in the database for files larger than 1MB:
https://www.microsoft.com/en-us/research/wp-content/uploads/2006/04/tr-2006-45.pdf

### Databases / Backends / Drivers targeted

MS SQL

### Example Use

i.e. When creating a Table with a VARBINARY column the SQL would look like:

```sql
CREATE TABLE Archive.dbo.Records
(
    [Id] [uniqueidentifier] ROWGUIDCOL NOT NULL UNIQUE, 
    [SerialNumber] INTEGER UNIQUE,
    [Chart] VARBINARY(MAX) FILESTREAM NULL
)
GO
```

Example taken from https://docs.microsoft.com/en-us/sql/relational-databases/blob/create-a-table-for-storing-filestream-data?view=sql-server-ver15

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Added support for ``FILESTREAM`` in MSSQL.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3540

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**Added support for ``FILESTREAM`` in MSSQL.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3541
