### ISSUE TITLE
TypeDecorator around Array

### ISSUE THREAD

**Issue by mehdigmira** [sqlalchemy/sqlalchemy#7249]
### Describe the use case

Hello, with the following snippet

```python
from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Table, TypeDecorator, create_engine, func
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import backref, contains_eager, joinedload, relationship, sessionmaker
from sqlalchemy.sql.type_api import INDEXABLE

Base = declarative_base()
engine = create_engine("postgresql://postgres@localhost:5435/postgres?sslmode=prefer", echo=True)


class SkipsFirst(TypeDecorator):
    impl = postgresql.ARRAY(Integer, zero_indexes=True)

    cache_ok = True

    def process_bind_param(self, value, dialect):
        return value[1:]

    def copy(self, **kw):
        return SkipsFirst(**kw)

    def coerce_compared_value(self, op, value):
        return self.impl.coerce_compared_value(op, value)


class Item(Base):
    __tablename__ = "item"
    id = Column(Integer, primary_key=True)
    content = Column(SkipsFirst)


Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)
Session = sessionmaker(engine)
session = Session()

session.add(Item(content=[1, 2, 3]))
session.flush()
print(session.query(Item.content[0]).all())
```

I have this error

```
raise NotImplementedError(NotImplementedError: Operator 'getitem' is not supported on this expression
```

The only thing that seems to work is making SkipsFirst subclass INDEXABLE.

```python
class SkipsFirst(TypeDecorator, INDEXABLE):
  ...
```

This doesn't seem to be coherent with the `TypeDecorator` philosophy. So I don't know if there is a canonical way to still have all the feature of `postgresql.ARRAY`.

### Databases / Backends / Drivers targeted

PostgreSQL in this case but all databases could be concerned.

### Example Use

...

**Comment by zzzeek** [comment]
not even that, there's a simple one line fix for this.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**check for TypeDecorator when handling getitem** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4003

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**check for TypeDecorator when handling getitem** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4004
