### ISSUE TITLE
Remove legacy code

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7257]
Lots of stuff here that will be removed.

this is just an epic kind of issue to track it

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**2.0 removals: LegacyRow** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3246

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**fully implement future engine and remove legacy** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3251

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**removals: all unicode encoding / decoding** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3289

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**Removals: MetaData.bind, Table.bind, all other .bind** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3339

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**remove legacy select patterns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3441

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**remove 2.0-removed Query elements** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3444

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Remove all remaining removed_in_20 warnings slated for removal** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3448

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**remove dbapi_proxy module** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3524

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**change AliasedInsp to use slots** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3532

**Comment by zzzeek** [comment]
i referenced the wrong issue
