### ISSUE TITLE
Remove deprecated dialects / dbapi

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7258]
Follow up on the deprecations added here https://github.com/sqlalchemy/sqlalchemy/issues/5189 by actually removing them

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Remove deprecated dialects and drivers** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3248
