### ISSUE TITLE
Allow Non-Linear CTE

### ISSUE THREAD

**Issue by Morikko** [sqlalchemy/sqlalchemy#7259]
### Describe the use case

Non Linear CTE:
- Multiple references to the recursive CTE
- Often with multiple UNIONs

Useful for example to do graph traversal with directional edges. One UNION to one side and the other UNION to the other side.

### Databases / Backends / Drivers targeted

SQLite & MySQL support its and maybe more. (Also: https://modern-sql.com/caniuse/with_recursive_(non-linear))

### Example Use

From https://www.sqlite.org/lang_with.html at `3.3. Queries Against A Graph`.
```
WITH RECURSIVE nodes(x) AS (
   SELECT 59
   UNION
   SELECT aa FROM edge JOIN nodes ON bb=x
   UNION
   SELECT bb FROM edge JOIN nodes ON aa=x
)
SELECT x FROM nodes;
```

**Comment by sqla-tester** [comment]
**Eric Masseran** has proposed a fix for this issue in the **master** branch:

**Add Non linear CTE support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3256

**Comment by sqla-tester** [comment]
**Eric Masseran** has proposed a fix for this issue in the **main** branch:

**Add Non linear CTE support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3220

**Comment by sqla-tester** [comment]
**Eric Masseran** has proposed a fix for this issue in the **rel_1_4** branch:

**Add Non linear CTE support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3312
