### ISSUE TITLE
Typo in 1.4 Changelog

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#7278]
### Describe the bug

`not_in_` erroneously used in place of `notin_`.

### To Reproduce

```python
docs only.
```

### Error

Docs only.

### Versions

Docs only.

**Comment by sqla-tester** [comment]
**jonathan vanasco** has proposed a fix for this issue in the **main** branch:

**Fixes: #7278** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3257
