### ISSUE TITLE
The on_duplicate_key_update method for MySQL renders with fixed columns names

### ISSUE THREAD

**Issue by SabaSCP** [sqlalchemy/sqlalchemy#7281]
### Describe the bug

When calling the `visit_on_duplicate_key_update` method, the compiled output will replace all the `insert_stmt.inserted` aliases to the one matching the `column.name`, even if the alias points to another object.
 
The issue could be considered a split-off from #5173, at https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_3_24/lib/sqlalchemy/dialects/mysql/base.py#L1436, where it sets `"VALUES(" + self.preparer.quote(column.name) + ")"`.

I think the best way is to use `obj.name` instead of `column.name`.

Btw, the issue can be reproduced on both `1.3.24` and `1.4.26`.

### To Reproduce

```python
from datetime import datetime
from sqlalchemy import Column, Integer, String, Boolean, DateTime, func
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()


class DebugTbl(Base):
    __tablename__ = 'debug_tbl'

    id = Column(Integer, primary_key=True)
    name = Column(String)
    enabled = Column(Boolean)
    updated = Column(DateTime)


entries = [
    {
        'name': 'first',
        'enabled': True,
        'updated': datetime.utcnow(),
    },
    {
        'name': 'second',
        'enabled': False,
        'updated': datetime.utcnow(),
    },
]

# check the insert/update against the `debug_tbl` table, with IF statement

insert_stmt = mysql.insert(DebugTbl).values(entries)
on_duplicate_key_stmt = insert_stmt.on_duplicate_key_update(
    name=func.IF(insert_stmt.inserted.updated > DebugTbl.updated,
                 insert_stmt.inserted.name,
                 DebugTbl.name),
    enabled=func.IF(insert_stmt.inserted.updated > DebugTbl.updated,
                    insert_stmt.inserted.enabled,
                    DebugTbl.enabled),
    updated=func.IF(insert_stmt.inserted.updated > DebugTbl.updated,
                    insert_stmt.inserted.updated,
                    DebugTbl.updated),
)
sql_statement = on_duplicate_key_stmt.compile(dialect=mysql.dialect())

assert sql_statement.string == (
    'INSERT INTO debug_tbl (name, enabled, updated) '
    'VALUES (%s, %s, %s), (%s, %s, %s) '
    'ON DUPLICATE KEY UPDATE '
    'name = IF(VALUES(updated) > debug_tbl.updated, VALUES(name), debug_tbl.name), '
    'enabled = IF(VALUES(updated) > debug_tbl.updated, VALUES(enabled), debug_tbl.enabled), '
    'updated = IF(VALUES(updated) > debug_tbl.updated, VALUES(updated), debug_tbl.updated)'
)
```

### Error

AssertionError

### Versions

- OS: Windows
- Python: 3.8.8
- SQLAlchemy: 1.3.24
- Database: MySQL 5.7.33
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pymysql 0.9.3

**Comment by zzzeek** [comment]
likely a good fix and we can accept PRs that include tests here in order to expedite.

**Comment by sqla-tester** [comment]
**Cristian Sabaila** has proposed a fix for this issue in the **main** branch:

**Fixed issue in visit_on_duplicate_key_update within a composed expression** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3262

**Comment by sqla-tester** [comment]
**Cristian Sabaila** has proposed a fix for this issue in the **rel_1_4** branch:

**Fixed issue in visit_on_duplicate_key_update within a composed expression** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3263
