### ISSUE TITLE
Can't insert in postgres async dialect

### ISSUE THREAD

**Issue by ludaavics** [sqlalchemy/sqlalchemy#7283]
### Describe the bug

Inserting infinite value in a float column fails.
11

### To Reproduce

```python
import asyncio

from sqlalchemy import Column, Integer, Float
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine

Base = declarative_base()

async_engine = create_async_engine(
    "postgresql+asyncpg://user:password@localhost:5450/postgres",
    echo=True,
)

async_session = sessionmaker(async_engine, expire_on_commit=False, class_=AsyncSession)

class Test(Base):
    __tablename__ = "test"
    id = Column(Integer, primary_key=True)
    data = Column(Float)

async def async_main():
    async with async_engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        test = Test(data=float("inf"))
        session.add(test)
        await session.commit()


if __name__ == "__main__":
    asyncio.run(async_main())
```

### Error

```
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: inf (numeric type does not support infinite values)
[SQL: INSERT INTO test (data) VALUES (%s) RETURNING test.id]
[parameters: (inf,)]
``` 

### Versions

- OS: ubuntu 20.04
- Python: 3.6.10
- SQLAlchemy: 1.4.26
- Database: postgres 9.6.2
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): asyncpg

### Additional context

Shameless copy/paste from https://github.com/MagicStack/asyncpg/issues/811

Edit: correct link

**Comment by zzzeek** [comment]
i propose this is a driver issue.  see #977.  have you tried asyncpg directly?

**Comment by zzzeek** [comment]
right here, asyncpg raises this explicitly https://github.com/MagicStack/asyncpg/blob/bc4127f44d3c7fb0e9813cf7deba023569039a93/tests/test_codecs.py#L636

**Comment by zzzeek** [comment]
it's mentioned at https://github.com/MagicStack/asyncpg/issues/811 and they state we'd use 'float" and not "numeric".

**Comment by ludaavics** [comment]
Plain asyncpg seems fine.
Numeric indeed do not support inf, but issue seems to be somewhere along the line asyncpg thinks the columns is numeric, not float? 


```
import asyncio
import asyncpg

async def main():
    conn = await asyncpg.connect()
    try:
        await conn.execute('''
            DROP TABLE IF EXISTS test;
            CREATE TABLE test (
                id serial,
                data float
            );
        ''')

        await conn.execute('INSERT INTO test (data) VALUES ($1)', float('inf'));
        print(await conn.fetch('SELECT * FROM test'))
    finally:
        await conn.execute('DROP TABLE IF EXISTS test')
        await conn.close()

asyncio.run(main())
```

**Comment by zzzeek** [comment]
did you mean to link to https://github.com/MagicStack/asyncpg/issues/811 ?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**map Float to asyncpg.FLOAT, test for infinity** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3260

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**map Float to asyncpg.FLOAT, test for infinity** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3261

**Comment by ludaavics** [comment]
Ah yes my mistake. Edited
