### ISSUE TITLE
Gracefully degrade unsupported types with asyncpg

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#7284]
### Describe the use case

Not all PostgreSQL work-alike databases support all types. For example, CockroachDB supports JSONB (OID 3802) but not JSON (OID 114). Modify the `on_connect()` method of `PGDialect_asyncpg` to gracefully degrade unsupported types instead of throwing a ValueError.

### Databases / Backends / Drivers targeted

Third-party dialects that derive from PGDialect_asyncpg.

### Example Use

This feature should be transparent to the developers of third-party dialects. No code changes should be necessary.

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **main** branch:

**Gracefully degrade unsupported types with asyncpg** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3259

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_4** branch:

**Gracefully degrade unsupported types with asyncpg** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3264

**Comment by zzzeek** [comment]
sorry, I have a whole different way to do this that I think is better.    Can I show you that?   I want to temporarily revert the change :(

**Comment by gordthompson** [comment]
@zzzeek - Sure. No problem.

**Comment by zzzeek** [comment]
so you can just add this method to your dialect:

```py

async def setup_asyncpg_jsonb_codec(self, conn):
    pass

```

that way I have a test for these methods to prevent them from getting refactored away, the code is easier to read and more obvious.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**simplify and publicize the asyncpg JSON(B) codec registrsation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3267

**Comment by gordthompson** [comment]
> so you can just add this method to your dialect:
> 
> ```python
> async def setup_asyncpg_jsonb_codec(self, conn):
>     pass

CockroachDB implements JSONB but not JSON, so we need to bypass the latter. This

```python
async def setup_asyncpg_jsonb_codec(self, conn):
    pass
```

works fine.

**Comment by zzzeek** [comment]
right right other way around "waves hands"

**Comment by jlrobins** [comment]
Thanks gordthompson, zzzeek. I do like how this latter proposed manner will both reduce a round-trip in CockroachDB's case, as well as lets the CDB dialect subclass implement the 'oddball' overriding behavior.

**Comment by CaselIT** [comment]
@gordthompson can you take a look at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3081 to see if something different should be done for CockroachDB?
