### ISSUE TITLE
fix SQLite native decimals

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7299]
we have this silly and actually embarrassing warning that SQLite does not return Decimal objects natively, and it's just wrong.  We just need to register a handler for it as illustrated at https://stackoverflow.com/a/6319513/34549 , and this is not much different from what we do for Oracle.   Lets make the switch and get rid of that warning.

**Comment by zzzeek** [comment]
OK yeah now it's all coming back why this field of dragons wasn't exactly trivial.

it's still not clear to me if you register an adapter for Decimal to convert to str on the bound parameter side, does SQLite store a string `"1234.56"` or a number.  will try to figure that out.  

but also, register_converter() I think is useless for us, because this only has any effect if you turn on PARSE_DECLTYPES and we're not doing that.  Which is sort of good news anyway because they can only be set up at the module level and it seems I can get most tests passing now without them....(not sure why?  maybe float has changed in python 3 in some way, not really sure what's going on ).

**Comment by zzzeek** [comment]
OK i just wrote a bunch of code, got all but one test to pass, and if i revert 100% of that code, including converters, etc., absolutely nothing changes.    We have just one test that is actually running in numbers that have lots of significant digits, and I can't get such a number to work on a SQLite table *at the sqlite3 console*.  So it's not supported by the DB. The driver is not really the problem.

So I think what I'm going to do is just remove the warning, because it's just silly.  People using SQLite should read the docs at https://www.sqlite.org/floatingpoint.html and see that SQLite is using FP for numbers, and that's what they're going to get.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**remove "native decimal" warning** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3290
