### ISSUE TITLE
1.4.26 KeyError when calling get_schema_names() using schema translations on mssql

### ISSUE THREAD

**Issue by asheidan** [sqlalchemy/sqlalchemy#7300]
### Describe the bug

If a schema_translate_map has been specified for an engine, calling `inspect(engine).get_schema_names()` causes a `KeyError` in what seems to be the generation of the SQL for getting all the schemas in `IdentifierPreparer._render_schema_translates()` (`sqlalchemy/sql/compiler.py:5057`).

This issue also seems to be in latest main (201c00bc0837af831f115e8313ad3ccb0be97e7a).

### To Reproduce

```python
from sqlalchemy import create_engine
from sqlalchemy import inspect
from sqlalchemy.engine import URL

DB_USERNAME = os.getenv("DB_USERNAME", "sa")
DB_PASSWORD = os.getenv("DB_PASSWORD", os.getenv("SA_PASSWORD"))
DB_HOST = os.getenv("DB_HOST", "127.0.0.1")


def main() -> None:
    username = DB_USERNAME
    password = DB_PASSWORD
    host = DB_HOST

    connection_url = URL.create(
        "mssql+pyodbc",
        username=username,
        password=password,
        host=host,
        database="master",
        query={"driver": "ODBC Driver 17 for SQL Server"},
    )

    engine = create_engine(connection_url).execution_options(
        schema_translate_map={"foo": "bar"}
    )

    schemas = inspect(engine).get_schema_names()
    print(schemas)


if __name__ == "__main__":
    main()
```

### Error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1461, in _execute_context
    dialect, self, conn, execution_options, *args, **kw
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 911, in _init_compiled
    self.unicode_statement, schema_translate_map
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/compiler.py", line 5068, in _render_schema_translates
    return re.sub(r"(\[SCHEMA_([^\]]+)\])", replace, statement)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/compiler.py", line 5057, in replace
    effective_schema = d[name]
KeyError: 'NAME'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_get_schema_names.py", line 35, in <module>
    main()
  File "test_get_schema_names.py", line 30, in main
    schemas = inspect(engine).get_schema_names()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/reflection.py", line 238, in get_schema_names
    conn, info_cache=self.info_cache
  File "<string>", line 2, in get_schema_names
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/dialects/mssql/base.py", line 2968, in get_schema_names
    schema_names = [r[0] for r in connection.execute(s)]
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1115, in execute
    execution_options or NO_OPTIONS,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    self, distilled_params, execution_options
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1309, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1467, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1769, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 206, in raise_
    raise exception
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1461, in _execute_context
    dialect, self, conn, execution_options, *args, **kw
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 911, in _init_compiled
    self.unicode_statement, schema_translate_map
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/compiler.py", line 5068, in _render_schema_translates
    return re.sub(r"(\[SCHEMA_([^\]]+)\])", replace, statement)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/compiler.py", line 5057, in replace
    effective_schema = d[name]
sqlalchemy.exc.StatementError: (builtins.KeyError) 'NAME'
[SQL: SELECT [INFORMATION_SCHEMA].[SCHEMATA].[SCHEMA_NAME] 
FROM [INFORMATION_SCHEMA].[SCHEMATA] ORDER BY [INFORMATION_SCHEMA].[SCHEMATA].[SCHEMA_NAME]]

``` 

### Versions

- OS: Debian Buster (Docker)
- Python: Python 3.7.3
- SQLAlchemy: 1.4.26
- Database: MSSQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pyodbc

### Additional context

The method where the exception occures:
```python
def _render_schema_translates(self, statement, schema_translate_map):
        d = schema_translate_map
        if None in d:
            d["_none"] = d[None]

        def replace(m):
            name = m.group(2)
            effective_schema = d[name]  # This is the line indicated by the traceback
            if not effective_schema:
                effective_schema = self.dialect.default_schema_name
                if not effective_schema:
                    # TODO: no coverage here
                    raise exc.CompileError(
                        "Dialect has no default schema name; can't "
                        "use None as dynamic schema target."
                    )
            return self.quote_schema(effective_schema)

        return re.sub(r"(\[SCHEMA_([^\]]+)\])", replace, statement)
```

When debugging, the dict `d` is (not surprisingly) the same as the configured `schema_translate_map`, but `replace()` is called with a match where group 2 is `'NAME'`, because the argument `statement` in the outer function here contains "[SCHEMA_NAME]", causing the KeyError. If no translate map has been configured this function is never called (at least my breakpoint was never triggered).

My assumption is that this should work, or give a clearer error message than the KeyError I'm getting currently.

**Comment by zzzeek** [comment]
how unfortunate that the replacement convention I chose for this one not only conflicts with SQL Server's quoting style but also a specific common name in their information schema.  cleanest solution is to use a safer escaping convention for schema translates.

**Comment by zzzeek** [comment]
yup same bug

```py
    def test_compiler_symbol_conflict(self, connection, metadata):
        t = Table("t", metadata, Column("POSTCOMPILE_DATA", String(50)))

        t.create(connection)

        connection.execute(t.insert().values(POSTCOMPILE_DATA="some data"))
        eq_(
            connection.scalar(
                select(t.c.POSTCOMPILE_DATA).where(
                    t.c.POSTCOMPILE_DATA.in_(["some data", "some other data"])
                )
            ),
            "some data",
        )

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**change the POSTCOMPILE/ SCHEMA symbols to not conflict w mssql quoting** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3294

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**change the POSTCOMPILE/ SCHEMA symbols to not conflict w mssql quoting** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3295

**Comment by zzzeek** [comment]
tiny bug, big change :(

**Comment by asheidan** [comment]
I'm really glad I didn't try to create a PR for this myself when I saw the proposed fix. ;)

**Comment by zzzeek** [comment]
yeah i dunno, did you see some easier way to do it?   seems like it would involve some kind of escaping on either side.   the change big only because we have so many tests asserting straight SQL w/ the tokens and that this also hit upon the POSTCOMPILE use case.

**Comment by asheidan** [comment]
I think changing the way the symbols are written/escaped as your PR (or something very similar) is probably the way to go. I was think of more unorthodox characters than '[]' but still in standard utf-8, but I don't know anything about how much trouble that would be during coding/testing/debugging or how that would affect the rest of the codebase.

Only other "future proof" way I can think of right now would be to use something "smarter" than a string. But that feels overly complicated and an even bigger change.

To be honest, I was looking at just skipping the schema translation for get_schema_names which would be enough for my use-case. ;)
But from what I understand would still cause the same issue for other statements.

**Comment by zzzeek** [comment]
yes without looking I thought skipping schema_translate for that one query would be the fix but then I saw it's a naming collision so that idea was out.    I also fixed a related misbehavior in the mssql dialect with this change regarding this lesser used feature where you can use a schema name like "[foo].[bar]".
