### ISSUE TITLE
switch distutils imports to setuptools for 1.4; use pep 517 for 2.0

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7311]
I was so proud of myself getting off of setuptools some years back (EDIT: no I wasn't, because setuptools is still in SQLAlchemy's setup.py, so I must be thinking of something else)  and now we're being told we have to use it (EDIT which is fine, it's already there, this is just a few lines to change in setup.py)

/home/classic/dev/zzzcomputing/release_scripts/_release_work/sa1427/setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives

2.0 should come out of the gate not using distutils.  EDITED in 1.4 we just have to change those distutils imports to setuptools.

**Comment by zzzeek** [comment]
if by python 3.12 the world is pretty much on 2.0 we will be fine, but due to the large amount of backwards incompatible changes for 1.4 / 2.0 i can imagine 1.4 might have a significantly longer span that it's still used.

**Comment by CaselIT** [comment]
In the cython change I've moved to use pep517 so we can ensure that setuptools is installed. Hopefully that will alleviate the issue

**Comment by CaselIT** [comment]
> 
> 
> if by python 3.12 the world is pretty much on 2.0 we will be fine, but due to the large amount of backwards incompatible changes for 1.4 / 2.0 i can imagine 1.4 might have a significantly longer span that it's still used.

this breaks down downloads by version: https://pepy.tech/project/sqlalchemy?versions=1.4*&versions=1.3*&versions=1.2*&versions=1.1*&versions=1.0.*

**Comment by kkirsche** [comment]
https://www.python.org/dev/peps/pep-0632/#migration-advice breaks down the specifics of the migration advice and where different sub-pieces should go / come to. Many of the migrations I've done for other projects do NOT actually use setuptools after the migration based on this advice.

**Comment by zzzeek** [comment]
@kkirsche well we are using those modules "distutils.errors" etc. that are specifically recommended to come from setuptools.

For 2.0, we are moving to cython so we won't need any setuptools or distutils.

For 1.4, I'd prefer to make only small changes, and I'm looking at our [setup.py](https://github.com/sqlalchemy/sqlalchemy/blob/main/setup.py) and apparently I'm crazy, setuptools is still there.   which is good for this change, but also, why did I think we removed it all, perhaps that was another package I was thinking of.

**Comment by zzzeek** [comment]
well we had this 4e2d54fdd5f3a156f742e19831d922af in 2008.  I'm really losing it if that just popped into my head as "oh we dont use setuptools".

**Comment by zzzeek** [comment]
it looks like setuptools has only added those symbols as of https://github.com/pypa/setuptools/blob/8af23a41194ae747faf3e60f9cc19141b5e7ad24/setuptools/errors.py ten days ago, so for this change to go in 1.4 right now we'd have to require setuptools 59.0.1 approximately.   we right now dont have any setuptools versioning implied in pyproject.toml or anything right now so we can't move on this issue right now for 1.4, unless I used a try/except (guess I'll do that)

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**favor setuptools imports over distutils** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3313

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**favor setuptools imports over distutils** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3314
