### ISSUE TITLE
Metadata reflection does not find the foreign key schema if it is Public

### ISSUE THREAD

**Issue by JeanPoffo** [sqlalchemy/sqlalchemy#7314]
### Describe the bug

On create a **Metadata** and use the **reflect** function, I encountered the follow problem:

If I use reflection setting any schema (except "public"), and inside this schema I have a table with foreign key linking to a table on public schema, the schema of the foreign key table is not mapped.

### To Reproduce

I have made an complete example with Docker.

Link: https://github.com/JeanPoffo/sqlalchemy_metadata_fk_bug

### Error

Result of example above, with author table on authors schema and public schema:

```
With 'authors' Schema
- Table found with identification 'authors.author'
---------
Columns:
['id', 'name']
---------
Schema:
authors
-----------------------------------------
With 'public' Schema
- Table found with identification 'author'
---------
Columns:
['id', 'name']
---------
Schema:
None
```

### Versions

- OS: Linux
- Python: 3.9
- SQLAlchemy: 1.4.26
- Database: musics, public
- DBAPI: psycopg2

**Comment by CaselIT** [comment]
Hi,

It's not clear to me what the issue is.

**Comment by JeanPoffo** [comment]
See the followe database structure:

```
CREATE TABLE IF NOT EXISTS public.author (
  id INT,
  name VARCHAR(50),
  PRIMARY KEY (id)
);

CREATE SCHEMA IF NOT EXISTS musics;

CREATE TABLE musics.music (
  id INT,
  author_id INT,
  name VARCHAR(50),
  PRIMARY KEY (id, author_id)
);

ALTER TABLE musics.music ADD CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES public.author (id) ON DELETE CASCADE;
```

If I use the follow statement:

```python
import sqlalchemy as sa

conn = sa.create_engine("postgresql://root:root@postgres:5432/first", client_encoding="UTF-8")

metadata = sa.MetaData(schema="musics")
metadata.reflect(conn, views=True)
table = metadata.tables["author"]

print(table.schema)
```
The result is "None".
If instead of the author table being in the public schema, it was in any other schema (such as "authors"), it would work correctly. I believe this is a bug, as it should correctly map the foreign key schemas and tables, regardless of the schema identified.

Additionally, I found this bug using the library [pgsync](https://github.com/toluaina/pgsync), that uses the SQLAlchemy.

See and reproduced with the repository example, it's very clear.

Thanks!

**Comment by CaselIT** [comment]
Oh ok, I though the fk was not being reflected.
This is the intended behaviour. By default `None` is an alias for the public schema on postgresql. 
See this part of the documentation https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#remote-schema-table-introspection-and-postgresql-search-path .

**Comment by JeanPoffo** [comment]
Okay, so it really is the default behavior.

Thank you very much for the feedback, I will be closing the issue!

😁

**Comment by CaselIT** [comment]
If `postgresql_ignore_search_path` does not work for you feel free to reopen

**Comment by zzzeek** [comment]
the reason is that we want reflection to work smoothly with what the search_path already is.   if you have a Table(schema=None), and then we reflect it, but we have to include the schema name, now we have also Table(schema='the_schema'), and that is two separate Table objects in Python which represent the same table in the PostgreSQL database, which is an invalid condition.
