### ISSUE TITLE
third party types that aren't TypeDecorator still need a cache_ok flag (at least UserDefinedType)

### ISSUE THREAD

**Issue by cibolog** [sqlalchemy/sqlalchemy#7319]
### Describe the bug

Following sqlalchemy 1.4 style and leveraging postgres column types, I am trying to issue queries with unnesting of composites, specifically:
```sql
SELECT * FROM parent p, child c
    INNER JOIN
        unnest (p.composite_array)
            AS pca(
                some_text,
                child_id
            )
    ON
        pca.child_id = c.id
    WHERE
        c.other_text ILIKE '%am%';

SELECT * FROM parent p, unnest (p.composite_array)
    AS pca(
        some_text,
        child_id
    )
    WHERE
        pca.child_id < 3;
```
However, nothing seems to work, even though the resulting sql is valid:
```python
select(['*']).select_from(Parent, func.unnest(Parent.composite_array).alias('pca'))
```
produces<br>
```sql
SELECT *
FROM parent, unnest(parent.composite_array) AS pca
```
and then errs, see the traceback.

### To Reproduce

```python
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy import select
from sqlalchemy import func
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import Session
from sqlalchemy_utils import CompositeType
from sqlalchemy_utils import CompositeArray
from sqlalchemy_utils import register_composites


Base = declarative_base()

ArrayOfComposites = Column(
        CompositeArray(
            CompositeType(
                'generic_composite',
                [
                    Column('some_text', String),
                    Column('child_id', Integer),
                ]
            )
        )
    )

class Parent(Base):
    __tablename__ = 'parent'
    id = Column(Integer, primary_key=True)
    composite_array = ArrayOfComposites

class Child(Base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)
    other_text = Column(String)


def main():
    engine = create_engine('postgresql://test:test@localhost:5432/test', echo=False)
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)
    session = Session(engine)

    register_composites(engine.connect())

    c1 = Child(other_text='spam')
    session.add(c1)

    c2 = Child(other_text='eggs')
    session.add(c2)

    c3 = Child(other_text='bacon')
    session.add(c3)

    c4 = Child(other_text='ham')
    session.add(c4)

    session.commit()

    p1 = Parent(
        composite_array = [
            {
                'some_text': 'foo',
                'child_id': 1
            }, {
                'some_text': 'bar',
                'child_id': 2
            }
        ]
    )
    session.add(p1)

    p2 = Parent(
        composite_array = [
            {
                'some_text': 'fizz',
                'child_id': 3
            }
        ]
    )

    session.add(p2)

    p3 = Parent(
        composite_array = [
            {
                'some_text': 'buzz',
                'child_id': 4
            }
        ]
    )

    session.add(p3)
    session.commit()

    select_stmt = (
        # Simple query for illustrative purposes, does not work 
        select(['*']).select_from(Parent, func.unnest(Parent.composite_array).alias('pca'))
    )

    print(select_stmt.compile(compile_kwargs={"literal_binds": True}))

    ps = session.execute(select_stmt).all()

if __name__ == '__main__':
    main()
```

### Error

```python
Traceback (most recent call last):
  File "/home/user/composite_search.py", line 106, in <module>
    main()
  File "/home/user/composite_search.py", line 103, in main
    ps = session.execute(select_stmt).all()
  File "/home/user/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/user/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/user/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/user/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1470, in _execute_clauseelement
    compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
  File "/home/user/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _compile_w_cache
    compiled_sql = compiled_cache.get(key)
  File "/home/user/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 918, in get
    item = dict.get(self, key, default)
TypeError: unhashable type: 'list'
``` 

### Versions

SQLAlchemy==1.4.25
SQLAlchemy-Utils==0.37.8
psycopg2==2.9.1
psycopg2-binary==2.9.1

Ubuntu 20.04
python 3.10
postgres 12.8

**Comment by zzzeek** [comment]
hi  -

please confirm turning off caching solves your problem for now:

    create_engine('postgresql://test:test@localhost:5432/test', echo=False, query_cache_size=0)

the fix here will be that sqlalchemy-utils datatypes will essentially turn off the caching in any case, until such time that sqlalchemy-utils can support adding cache flags to these types.

need to confirm all sqla-utils types are using UserDefinedType as a base and implement cache_ok for UDT as well.  definitely an oversight on this end that we didn't include this base in #6436 / 6967b4502079e199b12 .

**Comment by cibolog** [comment]
@zzzeek Yes, it does indeed work now, thank you. 

Two more questions if you happen to have time:
- How does one express the SQL queries from OP in SQLAlchemy, preferably with the minimal use of `text()`?
- Is it possible to attach relationship onto a CompositeType?

Thanks in advance.

**Comment by CaselIT** [comment]
>     * How does one express the SQL queries from OP in SQLAlchemy, preferably with the minimal use of `text()`?

take a look at https://docs.sqlalchemy.org/en/14/core/functions.html#sqlalchemy.sql.functions.FunctionElement.table_valued

**Comment by cibolog** [comment]
@CaselIT
What about the join on an attribute of a composite type? Join statements expect tables, not composites

**Comment by zzzeek** [comment]
> @CaselIT What about the join on an attribute of a composite type? Join statements expect tables, not composites

look at https://docs.sqlalchemy.org/en/14/orm/join_conditions.html#creating-custom-foreign-conditions and subsequent sections for examples on how to use custom SQL expressions / functions / operators / anything within the way that a relationship forms a join.   note however, this is a JOIN to another row in a table (or the same table), the composite datatype would only be involved in formulating the ON clause.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**generalize cache_ok to UserDefinedType** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3316

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**generalize cache_ok to UserDefinedType** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3317
