### ISSUE TITLE
see if we can use IntFlag etc. for ORM, other symbols, dont need util.symbol() anymore?

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7327]
we have a lot of int symbols.  can we use https://docs.python.org/3/library/enum.html#intflag for them ?  can we get rid of util.symbol() ?     we can still have the old names pointing to new enumerated versions.

**Comment by CaselIT** [comment]
We need to verify everything would work as expected.
enum do have some strange edge cases and bug yet to fix (one on flag was fixed in 3.10 but was moved to 3.11)

also there is this admonition on the enum docs regarding Int enum;
> Note
> For the majority of new code, Enum and Flag are strongly recommended, since IntEnum and IntFlag break some semantic promises of an enumeration (by being comparable to integers, and thus by transitivity to other unrelated enumerations). IntEnum and IntFlag should be used only in cases where Enum and Flag will not do; for example, when integer constants are replaced with enumerations, or for interoperability with other systems. 

just above this anchor https://docs.python.org/3/library/enum.html#others

**Comment by zzzeek** [comment]
we are using Enum as we get to places that are refactoring, but as far as having a blanket "convert all symbol() to Enum" issue, I dont think there's any requirement that we get that done for 2.0.  im still finding myself not always using Enum in any case.    the biggest set of "enums" we are using are the PASSIVE enums which are actually bitflags, and based on the warnings about IntEnum above these might be best kept as "symbol" as long as we are doing bitwise operations.

closing this as it's not strictly necessary and we can refactor sections as we have time.
