### ISSUE TITLE
Support for skipping onupdate

### ISSUE THREAD

**Issue by hugokerstens** [sqlalchemy/sqlalchemy#7351]
### Describe the use case

The argument `onupdate` allows to specify a context-sensitive default function, to allow the updated variable to depend on the current context. This feature is great, but in some cases it would be useful to NOT update the value depending on the context, and instead do not modify it.

For example, if I have the following model:
```python
class Person(UserMixin, db.Model):
    name = Column(String(100))
    age = Column(Integer)
    last_updated_name = Column(DateTime, onupdate=onupdate_function)
```
If I update the `age` of `Person`, I would like to keep `last_updated_name` unchanged.

I understand that this can be achieved with validators for this specific example, but especially in more complex cases `onupdate` would be more robust.

### Databases / Backends / Drivers targeted

All databases / backends / drivers.

### Example Use

If the function returns some magic variable, it would remain unchanged.
```python
def onupdate_function(context):
    if 'name' in context.get_current_parameters():
        return func.now()
    return sqlalchemy.something.DO_NOT_MODIFY
```

### Additional context

There exist several threads on the web already looking for this feature:
https://stackoverflow.com/questions/51956079/sqlalchemy-avoid-updating-a-field-with-onupdate-based-on-which-other-fields-a
https://stackoverflow.com/questions/33708219/how-to-handle-sqlalchemy-onupdate-when-current-context-is-empty

**Comment by zzzeek** [comment]
hi -

unfortunately I dont think this is feasible at the level of the column onupdate function.   When this function is called, the SQL statement is already compiled into a string where a bound parameter placeholder is ready to accept the value which the onupdate generator will generate.  It has to be a bound value, can't be just "the column" as that implies different SQL generation.

the onupdate function is compatible with things like executemany() and such and therefore assumes a fixed SQL compilation form.

for more business-level logic where a column may or may not be updated, ORM functions like `@validates` and attribute events are probably better choices.

**Comment by zzzeek** [comment]
indeed that's waht was chosen as the answer on the above mentioned stackoverflow question

**Comment by zzzeek** [comment]
I can see a feature that would involve an onupdate of a SQL expression that's "CASE WHEN :x IS NOT NULL THEN :x ELSE table.column", and then mechanics to run that function in the same way as onupdate but that would be very complicated to implement and support, which we avoid for features that see very little use.  contextual onupdate functions are a seldom used feature of SQLAlchemy as ORM-related rulesets are a lot more intuitive.

**Comment by zzzeek** [comment]
not to mention, that feature would still render an UPDATE statement, and does not cover the case when none of the columns are being updated, an UPDATE should not even be run.  this all continues to point towards keeping logic like this before the statement is to be emitted.

**Comment by hugokerstens** [comment]
Thanks for the quick and thorough reply! With your explanation about the way `onupdate` is implemented I see that the feature request is not really feasible. I was unaware of the fact that the `onupdate` function is executed after the SQL has been generated.

I will stick to validators, thanks for the help!
