### ISSUE TITLE
Wiki example for explaining queries does not run on sqlalchemy 1.4.26

### ISSUE THREAD

**Issue by laurentS** [sqlalchemy/sqlalchemy#7353]
### Describe the bug

I tried running the example at https://github.com/sqlalchemy/sqlalchemy/wiki/Query-Plan-SQL-construct but got the error below.
This seems to be fixed by removing `CoerceTextStatementRole` from the declaraction of `class explain`. The example in the wiki might need correcting.

As a side question, is it expected that this will not work on non-ORM queries?

### To Reproduce

```python
- install sqlalchemy 1.4.26
- copy the example from https://github.com/sqlalchemy/sqlalchemy/wiki/Query-Plan-SQL-construct (1.4 version at the top of the page)
- run the code and observe error
```

### Error

```
Traceback (most recent call last):
  File "testexpl.py", line 4, in <module>
    from sqlalchemy.sql.roles import CoerceTextStatementRole
ImportError: cannot import name 'CoerceTextStatementRole' from 'sqlalchemy.sql.roles'
``` 

### Versions

- OS: debian linux sid
- Python: 3.9.8
- SQLAlchemy: 1.4.26
- Database: postgresql 12
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2

**Comment by zzzeek** [comment]
> ### Describe the bug
> 
> I tried running the example at https://github.com/sqlalchemy/sqlalchemy/wiki/Query-Plan-SQL-construct but got the error below. This seems to be fixed by removing `CoerceTextStatementRole` from the declaraction of `class explain`. The example in the wiki might need correcting.

thanks, fixed

> 
> As a side question, is it expected that this will not work on non-ORM queries?

it works with any select() and the construct can be passed to session.execute() or connection.execute().
