### ISSUE TITLE
Postgres dialect doesn't support exists on sequences

### ISSUE THREAD

**Issue by ziima** [sqlalchemy/sqlalchemy#7354]
### Describe the bug

I noticed that `CreateSequence` and `DropSequence` provide `if_exists` and `if_not_exists` flags, but they doesn't seem to be working, at least not when postgres dialect is used.

### To Reproduce

```python
from sqlalchemy import create_engine, Sequence
from sqlalchemy.schema import CreateSequence

engine = create_engine('postgresql:///test')
seq = Sequence('my_seq')
create = CreateSequence(seq, if_not_exists=True)
str(create.compile(dialect=engine.dialect)) # >>> 'CREATE SEQUENCE my_seq START WITH 1'
```

### Error

No error, just unexpected SQL.

### Versions

- OS: SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
- Python: 3.9.2
- SQLAlchemy: 1.4.27
- Database: Postgresql 13.4
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2 2.9.2

**Comment by CaselIT** [comment]
Hi,

It seems it's not supported in any dialect. Thanks for reporting.
PR to fix this are welcome!

**Comment by CaselIT** [comment]
yes, that makes sense, I was thinking at something like this. should we re-target this to v2 then?

**Comment by zzzeek** [comment]
at least, yes

**Comment by ziima** [comment]
Shouldn't there be a two mixins `_SupportsExistsFlag` and `_SupportsNotExistsFlag`? I find it weird that it is possible to pass `if_exists` to `CreateSequence` and `if_not_exists` to `DropSequence`. It is currently possible, although it doesn't do anything as well.

**Comment by zzzeek** [comment]
That's fine, since we are building out new classes that are per-impl in any case, it can be that way also.

**Comment by sqla-tester** [comment]
**Jesse Bakker** has proposed a fix for this issue in the **main** branch:

**Make if_exists and if_not_exists flags on ddl statements match compiler** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4067

**Comment by zzzeek** [comment]
this is all set we just need a changelog file

**Comment by sqla-tester** [comment]
**Jesse Bakker** has proposed a fix for this issue in the **main** branch:

**Make if_exists and if_not_exists flags on ddl statements match compiler** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4067
