### ISSUE TITLE
Joined inheritance with non-primary parent key is not working.

### ISSUE THREAD

**Issue by greemo** [sqlalchemy/sqlalchemy#7356]
### Describe the bug

I have a situation where postal addresses are used for multiple purposes in the system, so I created a base class PostalAddress and subclasses for each use-case where they are used as part of the composition of another object. For example, I have an Organisation that has a postal address. This is a 1:1 relationship.

I want to ensure addresses don't exist without an owner, so the foreign key is declared on the address side, rather than the organisation side.

I want to look up an OrganisationAddress from the session based on the id of the organisation. I have tries a few ways: 
```
address = await session.get(OrganisationAddress, {"organisation_id": org.node_id})
```
Outcome: "sqlalchemy.exc.InvalidRequestError: Incorrect names of values in identifier to formulate primary key for query.get(); primary key attribute names are 'id'"
```
address = await session.get(OrganisationAddress, org.node_id)
```
Outcome: Wrong SQL emitted: ``` SELECT organisation_address.id AS organisation_address_id, postal_address.id AS postal_address_id, postal_address.supplement_a AS postal_address_supplement_a, organisation_address.organisation_id AS organisation_address_organisation_id 
FROM postal_address JOIN organisation_address ON postal_address.id = organisation_address.id 
WHERE postal_address.id = %s```

I want to use the session.get() method, because I want to leverage the caching of the object when available.

However the "organisation_id" attribute of OrganisationAddress is not being recognised as a primary key, even though it should be, as it is THE primary key, as confirmed by the DB.

### To Reproduce

```python
class Organisation(BaseModel):
    __tablename__ = 'organisation'
    node_id = sa.Column(sa.Integer, primary_key=True, nullable=False)
    address = sa.orm.relationship('OrganisationAddress', uselist=False)
    ...

class PostalAddress(BaseModel):
    __tablename__ = 'postal_address'
    id = sa.Column(sa.Integer, primary_key=True, nullable=False)
    ...

# The primary key for the derived class is not the foreign key to the parent class, but a foreign key to an owning class.
class OrganisationAddress(PostalAddress):
    __tablename__ = 'organisation_address'
    id = sa.Column(sa.ForeignKey("postal_address.id"), nullable=False, index=True)
    organisation_id = sa.Column(sa.ForeignKey("organisation.node_id", ondelete='CASCADE'), primary_key=True, nullable=False, doc="Organisation owning this address")
```

### Error

```
Incorrect names of values in identifier to formulate primary key for query.get(); primary key attribute names are 'id'
Traceback (most recent call last):
/orm/session.py", line 2811, in _get_impl
    primary_key_identity = list(
/orm/session.py", line 2812, in <genexpr>
    primary_key_identity[prop.key]
KeyError: 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
/execute.py", line 625, in await_result
    return_type, field_nodes, info, path, await result
in resolve
    result = await result
  File "organisation.py", line 15, in resolve_address
    address = await session.get(OrganisationAddress, {"organisation_id": org.node_id})
/session.py", line 295, in get
    return await greenlet_spawn(
/util/_concurrency_py3k.py", line 123, in greenlet_spawn
    result = context.switch(*args, **kwargs)
/orm/session.py", line 2768, in get
    return self._get_impl(
/orm/session.py", line 2817, in _get_impl
    util.raise_(
/util/compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: Incorrect names of values in identifier to formulate primary key for query.get(); primary key attribute names are 'id'


``` 

### Versions

- OS: linux
- Python: 3.8
- SQLAlchemy: 1.4.26
- Database: Postgres 12.9
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

### Additional context

Using Async Session

**Comment by zzzeek** [comment]
the primary key attribute for an OrganizationAddress model is called "id", because this is the PostalAddress.id attribute.  All objects that are instances of PostalAddress, which includes objects that are subclasses of it, are identified by PostalAddress.id first and foremost.  The OrganizationAddress.organization_id attribute being a primary key is fine but that's a persistence detail.
