### ISSUE TITLE
Postgres query language "SELECT DISTINCT ON (x)" depreciated in 1.4

### ISSUE THREAD

**Issue by quoimec** [sqlalchemy/sqlalchemy#7367]
### Describe the use case

Hello, 

I wanted to write a query using the postgres distinct on language feature. However, when looking through the [documentation](https://docs.sqlalchemy.org/en/14/core/selectable.html?highlight=distinct#sqlalchemy.sql.expression.Select.distinct) for this method I can see it's been marked as depreciated as of version 1.4. 

Are there other ways of using this feature or has this just been removed as it's too language specific?

Cheers!

### Databases / Backends / Drivers targeted

Postgres

### Example Use

```sql
select distinct on (x)
  x,
  y
from
  table
order by
  x,
  y;
```

**Comment by CaselIT** [comment]
Hi.

Please re-read the deprecated:
> Using *expr in *other dialects* is deprecated and will raise CompileError in a future version.

It will be supported only on postgresql
