### ISSUE TITLE
add __class_getitem__ to the declarative Base class 

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy#7368]
**Describe the bug**
I have a base class for SQLAlchemy tables which is shared across different projects. Therefore it uses generics.
Since the metadata, etc. is different in each project, each uses an own declarative base.
However, to have generics, the declarative base also needs to be generic.

When executing mypy, everything is fine. But during execution, it fails. As shows in the error message, a SQLAlchemy generated class is used.

**Expected behavior**
It works

**To Reproduce**

Execute `python <pyfile>`

```py
from typing import Type, TypeVar, Generic
from sqlalchemy.orm import as_declarative
from sqlalchemy import Column, Integer

T = TypeVar("T", bound="CommonBase")


class CommonBase(Generic[T]):
    @classmethod
    def boring(cls: Type[T]) -> Type[T]:
        return cls


@as_declarative()
class Base(CommonBase[T]):
    @classmethod
    def more_boring(cls: Type[T]) -> Type[T]:
        return cls


class Tab(Base["Tab"]):
    a = Column(Integer, primary_key=True)

```

**Error**

```
Traceback (most recent call last):
  File "testscript.py", line 21, in <module>
    class Tab(Base["Tab"]):
  File "/usr/lib64/python3.7/typing.py", line 251, in inner
    return func(*args, **kwds)
  File "/usr/lib64/python3.7/typing.py", line 838, in __class_getitem__
    _check_generic(cls, params)
  File "/usr/lib64/python3.7/typing.py", line 201, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: <class 'sqlalchemy.orm.decl_api.Base'> is not a generic class
```

**Versions.**
 - OS: Linux
 - Python: 3.7.1
 - SQLAlchemy: 1.4.27
 - mypy: 0.910
 - SQLAlchemy2-stubs: 0.0.2a19

**Have a nice day!**

**Comment by zzzeek** [comment]
we can accept PRs for this.   for whoever does this a simple test should also be present in test/orm/declarative/ , likely in a new suite that's py3 only test/orm/declarative/test_typing_py3k.py .

**Comment by kasium** [comment]
@zzzeek I'll give it a try in the next days. Thanks for checking

**Comment by sqla-tester** [comment]
**Kai Mueller** has proposed a fix for this issue in the **main** branch:

**Add __class_getitem__ to the declarative Base class** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3338

**Comment by sqla-tester** [comment]
**Kai Mueller** has proposed a fix for this issue in the **rel_1_4** branch:

**Add __class_getitem__ to the declarative Base class** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3340
