### ISSUE TITLE
subquery() change the DISTINCT ON usage

### ISSUE THREAD

**Issue by mroleh** [sqlalchemy/sqlalchemy#7378]
### Describe the bug

When I run the query with .distinct() it return me next correct query:
```
SELECT DISTINCT ON (invoice_id, invoice_contract_id) invoice_id, invoice_contract_id, invoice_create_date, invoice_status, invoice_update_date 
FROM invoice
ORDER BY invoice_id, invoice_contract_id, invoice_create_date DESC NULLS LAST
```
When I add .subquery() at the end to it change the SQL query to next one:
```
SELECT DISTINCT invoice_id, invoice_contract_id, invoice_create_date, invoice_status, invoice_update_date 
FROM invoice
ORDER BY invoice_id, invoice_contract_id, invoice_create_date DESC NULLS LAST
```
The difference in my code, I'm just adding .subquery() at the and.

### To Reproduce

```python
def get_subquery():
        return session.query(
            Invoice.id,
            Invoice.contract_id,
            Invoice.create_date,
            Invoice.status,
            Invoice.update_date
        ).order_by(
            Invoice.invoice_id,
            Invoice.contract_id,
            nullslast(desc(Invoice.create_date))
        ).distinct(
            Invoice.invoice_id,
            Invoice.contract_id,
        ).subquery()
```

### Error

```
There is no error message, just wrong SQL query generated
``` 

### Versions

- OS: Win 10 
- Python: 3.8.10
- SQLAlchemy: 1.4.26
- Database: 
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by zzzeek** [comment]
hi there-

your test case is not complete as it does not illustrate generation of the query and I can't reproduce an issue here.  Make sure in your real world script you are using the postgresql dialect to stringify the query, as "DISTINCT ON" will not render otherwise.

Full [MCVE](http://stackoverflow.com/help/mcve) is as follows:

```py
from sqlalchemy import Column
from sqlalchemy import desc
from sqlalchemy import Integer
from sqlalchemy import nullslast
from sqlalchemy import select
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    a = Column(Integer)
    b = Column(Integer)
    c = Column(Integer)


s = Session()

q = (
    s.query(A.id, A.a, A.b, A.c)
    .order_by(A.id, A.a, nullslast(desc(A.c)))
    .distinct(A.id, A.a)
)

q2 = q.subquery()

print("---------------------------------------------------")
print(q.statement.compile(dialect=postgresql.dialect()))

print("---------------------------------------------------")
print(q2.compile(dialect=postgresql.dialect()))

print("---------------------------------------------------")
print(select(q2).compile(dialect=postgresql.dialect()))
```

So this is Query directly, subquery() directly, then selecting from the subquery. All three have `DISTINCT ON (a.id, a.a)` present:

```sql
$ python test3.py 
---------------------------------------------------
SELECT DISTINCT ON (a.id, a.a) a.id, a.a, a.b, a.c 
FROM a ORDER BY a.id, a.a, a.c DESC NULLS LAST
---------------------------------------------------
SELECT DISTINCT ON (a.id, a.a) a.id, a.a, a.b, a.c 
FROM a ORDER BY a.id, a.a, a.c DESC NULLS LAST
---------------------------------------------------
SELECT anon_1.id, anon_1.a, anon_1.b, anon_1.c 
FROM (SELECT DISTINCT ON (a.id, a.a) a.id AS id, a.a AS a, a.b AS b, a.c AS c 
FROM a ORDER BY a.id, a.a, a.c DESC NULLS LAST) AS anon_1
````

try it out and see that you get the same result and possibly see what's different about your program.  thanks!

**Comment by zzzeek** [comment]
see also https://docs.sqlalchemy.org/en/14/faq/sqlexpressions.html#how-do-i-render-sql-expressions-as-strings-possibly-with-bound-parameters-inlined for background on stringification of SQL statements

**Comment by zzzeek** [comment]
also, if you are compiling with non-postgresql you should see this warning pretty conspiculously:

SADeprecationWarning: DISTINCT ON is currently supported only by the PostgreSQL dialect.  Use of DISTINCT ON for other backends is currently silently ignored, however this usage is deprecated, and will raise CompileError in a future release for all backends that do not support this syntax.

**Comment by zzzeek** [comment]
going to assume this has to do with running correct dialect for stringify

**Comment by mroleh** [comment]
Hello, sorry for late response.
Actually it works now good. The problem was that when we do the subquery() if shown on debugger as SELECT DISTINCT i.id, i.name from i 
But if I add this subquery to full query it work correctly and is shown as SELECT ..... LEFT JOIN (SELECT DISTINCT ON(i.id, i.name)

I didn't have to use the stringify, cause I have to use the subquery result.

Anyway looks like that this issue really isn't relevant.
Thanks a lot
