### ISSUE TITLE
Harmonize exists api with select one

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7386]
### Describe the bug

The Exists construct has some of it's api that's not consistent with the select one.
For example where accepts a single argument, not multiple like select.

There may be more examples of this

### To Reproduce

```python
sa.exists(1).where(clause1, cluase2)
```

### Error

`where` accepts a single argument

### Versions

- OS: any
- Python: any
- SQLAlchemy: 1.4+
- Database: any
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): any

**Comment by CaselIT** [comment]
seems to be only the where

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**The where method of exists now accepts multiple cluase.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3350

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**The where method of exists now accepts multiple cluase.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3351
