### ISSUE TITLE
document and possibly warn for caching disabled sitautions

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7394]
we should ensure warnings are prsent for:

1. dialects that dont set cache_ok
2. TypeDecorator / UserDefinedType subclasses (including sub-subclasses like those of PickleType) that warn for this, we should have this but need to test for PickleType
3. subclasses of built-in constructs that dont have inherit_cache=True or caching.   Just saw this in #7359

the warning can refer to errors.rst, which can then refer to the FAQ: "Why is my application so much slower in 1.4 than in 1.3?"  with bullets "step 1: turn on SQL echoing ; step 2: look for [no key]  step 3: look for a. dialects b. types c. custom constructs"

the existing caching section should be cross linked with the FAQ / errors page

the guidance for custom constructs should be to use the "inherit_cache=True" flag, but with caveats that the construct needs to have no additional attributes that affect its SQL rendering.   This should also be mentioend in the `@compiles` docs.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Warn when caching is disabled / document** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3349

**Comment by zzzeek** [comment]
as a result of this fix I have identified that ORM synonyms and other "proxied" attributes were not generating cache keys, so a query like `query(User.orders_syn_2)`  (test/orm/test_query.py::SynonymTest::test_joins) was not getting cached!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**Warn when caching is disabled / document** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3354
