### ISSUE TITLE
Add a "strip" flag for String fields to remove whitespace

### ISSUE THREAD

**Issue by tgross35** [sqlalchemy/sqlalchemy#7402]
### Describe the use case

It would be useful to have a `strip=True` flag for the `String` class that just gets rid of whitespace on the string before submitting it to the database. This would be useful for processing input forms, split strings and similar, and would just make avoiding errors easier when processing user input.

I think this would just require an extra kwarg for String init and something like this in `String.bind_processor`

```python
if self._strip:
    return value.strip()
return value
```

### Databases / Backends / Drivers targeted

All

### Example Use

```python
t= Table(
   'table', metadata_obj, 
   Column('id', Integer, primary_key = True), 
   Column('name', String(60, strip=True)), 
)
```

### Additional context

TypeDecorator can be used to achieve this for now:

```python
class StripString(TypeDecorator):
    """Remove leading and trailing whitespace."""

    impl = String

    def process_bind_param(self, value, dialect):
        return value.strip() if value else value

    def copy(self, **kw):
        return StripString(self.impl.length)
```

**Comment by CaselIT** [comment]
Hi,

I'm -1 on this, since it seems somewhat specific to the use case and I think the type decorator solution would be clearer.
The main issue is that there is a large number of possible operations that could be done on strings, and I don't think having `String(strip=True, capitalize=False, casefold=True, ...)` would make for a good api.

@zzzeek what's your take on this?

**Comment by jvanasco** [comment]
This request reads like it was inspired by the use of an anti-pattern:

> This would be useful for processing input forms, split strings and similar, and would just make avoiding errors easier when processing user input.
  
These routines are typically handled during initial form validation, and should occur much earlier in any logic pipeline than (attempted) persistence with SQLAlchemy or any other database library.

There are numerous libraries that handle form schema and validation, and several of them offer integrations with SqlAlchemy.  For example, Deform/Colander has a colanderalchemy library to accomplish that.

I think it's fine to use CustomTypes and other SqlAlchemy features to *ensure* compliance with a data format as a backup, but if someone seems to **need** this functionality, that is a warning sign to me.

**Comment by CaselIT** [comment]
@zzzeek do you have an opinion on this?

**Comment by tgross35** [comment]
Good discussion points, I realize this isn't a good fit. I'll save Mike the effort :)

**Comment by zzzeek** [comment]
Yeah I am -1 on this as well, it's an arbitrary of a use case and we of course want to have smooth expansion points for this kind of thing which is currently TypeDecorator.
