### ISSUE TITLE
The table at `2.0 Migration - ORM Usage` could use scalar

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7407]
We could probably use `scalars` in some rows in this table
https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-orm-usage

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add ``scalars`` to Migration - ORM Usage table.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3366
