### ISSUE TITLE
add execution_options to session.get()

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7410]
broken out from #7236 as this is a one liner (plus tests).

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add execution options to ``Session.get``** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3364

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**Add execution options to ``Session.get``** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3365
