### ISSUE TITLE
Assigning a Row object should rise a better error

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7431]
oh!

you're trying to assign to it!

which....you can't do with any named tuple.    

so....this would be....misleading error message then, right?

_Originally posted by @zzzeek in https://github.com/sqlalchemy/sqlalchemy/discussions/7424#discussioncomment-1780756_

**Comment by zzzeek** [comment]
I didnt even see this in my email, sorry!  as you might have noticed the issues /emails are like a rain of arrows today

**Comment by CaselIT** [comment]
yes I noticed
