### ISSUE TITLE
suite not working with pytest 7

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7436]
With pytest 7 the suite does not load:
running `pytest test/dialect/test_suite.py` collects no test

**Comment by CaselIT** [comment]
never-mind, it was an out of date branch

**Comment by tswast** [comment]
Looks like this was fixed by https://github.com/sqlalchemy/sqlalchemy/commit/deda8bf2444b7e7130001f3a9ab0c55b2e389c68 released in 1.4.28 https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-1.4.28-tests
