### ISSUE TITLE
deferred loaders on inherited subclass should use optimized loader

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7463]
looking at behaviors that were set up way back in #3468, it looks like an undefer operation at some point used the optimized subclass loader, and now it doesnt.  So see if we can restore that by having the deferred loader call upon load_scalar_attributes() instead of load_on_ident().

will run through for 2.0, if it is very problem free maybe can be in 1.4 but likely not worth the risk.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use load_scalar_attributes() for undefer** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3410
