### ISSUE TITLE
selectinload does not update results when subquery filter changes.

### ISSUE THREAD

**Issue by sweetro** [sqlalchemy/sqlalchemy#7489]
### Describe the bug

When using `selectinload` with extra criteria, and `and_` with a subquery result, the result set is initially as expected, but does not work as expected when the subquery passed changes.

For repro I adapted the test from https://github.com/sqlalchemy/sqlalchemy/issues/6881#issuecomment-898457025
I also added a sanity check that `in_` does work within in the `and_` suggesting that this is isolated to use with a subquery.

### To Reproduce

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import selectinload
from sqlalchemy.orm import Session


def test_issue():
  show_bug = True #False
  use_subquery = True #False

  Base = declarative_base()

  class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B", bake_queries=show_bug)


  class B(Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    c_id = Column(ForeignKey("c.id"))
    data = Column(String)
    c = relationship("C", bake_queries=show_bug, uselist=False)


  class C(Base):
    __tablename__ = "c"
    id = Column(Integer, primary_key=True)
    data = Column(String)

  if not show_bug:
      e = create_engine("sqlite://", echo=True, query_cache_size=0)
  else:
      e = create_engine("sqlite://", echo=True)

  Base.metadata.create_all(e)

  ses = Session(e)

  ses.add_all([A(id=1, bs=[B(c=C(data="d1"))]), A(id=2, bs=[B(c=C(data="d2"))])])
  ses.commit()
  

  if use_subquery:
    # With first subquery
    subq_1 = ses.query(C).filter(C.data == "d1").subquery()
    a_1 = ses.query(A).options(
      selectinload(A.bs.and_(B.c_id == subq_1.c.id))
    ).populate_existing().get(1)
    a_2 = ses.query(A).options(
      selectinload(A.bs.and_(B.c_id == subq_1.c.id))
    ).populate_existing().get(2)
    assert len(a_1.bs) == 1 
    assert len(a_2.bs) == 0 
    ses.close()

    # With different subquery
    subq_2 = ses.query(C).filter(C.data == "d2").subquery()
    a_1 = ses.query(A).options(
      selectinload(A.bs.and_(B.c_id == subq_2.c.id))
    ).populate_existing().get(1)
    a_2 = ses.query(A).options(
      selectinload(A.bs.and_(B.c_id == subq_2.c.id))
    ).populate_existing().get(2)
    assert len(a_1.bs) == 0 # This fails with assert 1 == 0
    assert len(a_2.bs) == 1 
  
  else:
    # Test using in_ instead
    # Using IN "d1"
    c_ids = [c.id for c in ses.query(C).filter(C.data == "d1").all()]
    a_1 = ses.query(A).options(
      selectinload(A.bs.and_(B.c_id.in_(c_ids)))
    ).populate_existing().get(1)
    a_2 = ses.query(A).options(
      selectinload(A.bs.and_(B.c_id.in_(c_ids)))
    ).populate_existing().get(2)
    assert len(a_1.bs) == 1 
    assert len(a_2.bs) == 0 
    ses.close()

    # Using IN "d2"
    c_ids = [c.id for c in ses.query(C).filter(C.data == "d2").all()]
    a_1 = ses.query(A).options(
      selectinload(A.bs.and_(B.c_id.in_(c_ids)))
    ).populate_existing().get(1)
    a_2 = ses.query(A).options(
      selectinload(A.bs.and_(B.c_id.in_(c_ids)))
    ).populate_existing().get(2)
    assert len(a_1.bs) == 0
    assert len(a_2.bs) == 1
```

### Error

------------------------------------------------------------------------------------------------- Captured log call -------------------------------------------------------------------------------------------------
INFO     sqlalchemy.engine.Engine:log.py:117 BEGIN (implicit)
INFO     sqlalchemy.engine.Engine:log.py:117 PRAGMA main.table_info("a")
INFO     sqlalchemy.engine.Engine:log.py:117 [raw sql] ()
INFO     sqlalchemy.engine.Engine:log.py:117 PRAGMA temp.table_info("a")
INFO     sqlalchemy.engine.Engine:log.py:117 [raw sql] ()
INFO     sqlalchemy.engine.Engine:log.py:117 PRAGMA main.table_info("b")
INFO     sqlalchemy.engine.Engine:log.py:117 [raw sql] ()
INFO     sqlalchemy.engine.Engine:log.py:117 PRAGMA temp.table_info("b")
INFO     sqlalchemy.engine.Engine:log.py:117 [raw sql] ()
INFO     sqlalchemy.engine.Engine:log.py:117 PRAGMA main.table_info("c")
INFO     sqlalchemy.engine.Engine:log.py:117 [raw sql] ()
INFO     sqlalchemy.engine.Engine:log.py:117 PRAGMA temp.table_info("c")
INFO     sqlalchemy.engine.Engine:log.py:117 [raw sql] ()
INFO     sqlalchemy.engine.Engine:log.py:117 
CREATE TABLE a (
	id INTEGER NOT NULL, 
	data VARCHAR, 
	PRIMARY KEY (id)
)

INFO     sqlalchemy.engine.Engine:log.py:117 [no key 0.00095s] ()
INFO     sqlalchemy.engine.Engine:log.py:117 
CREATE TABLE c (
	id INTEGER NOT NULL, 
	data VARCHAR, 
	PRIMARY KEY (id)
)

INFO     sqlalchemy.engine.Engine:log.py:117 [no key 0.00129s] ()
INFO     sqlalchemy.engine.Engine:log.py:117 
CREATE TABLE b (
	id INTEGER NOT NULL, 
	a_id INTEGER, 
	c_id INTEGER, 
	data VARCHAR, 
	PRIMARY KEY (id), 
	FOREIGN KEY(a_id) REFERENCES a (id), 
	FOREIGN KEY(c_id) REFERENCES c (id)
)

INFO     sqlalchemy.engine.Engine:log.py:117 [no key 0.00106s] ()
INFO     sqlalchemy.engine.Engine:log.py:117 COMMIT
INFO     sqlalchemy.engine.Engine:log.py:117 BEGIN (implicit)
INFO     sqlalchemy.engine.Engine:log.py:117 INSERT INTO a (id, data) VALUES (?, ?)
INFO     sqlalchemy.engine.Engine:log.py:117 [generated in 0.00421s] ((1, None), (2, None))
INFO     sqlalchemy.engine.Engine:log.py:117 INSERT INTO c (data) VALUES (?)
INFO     sqlalchemy.engine.Engine:log.py:117 [generated in 0.00132s] ('d1',)
INFO     sqlalchemy.engine.Engine:log.py:117 INSERT INTO c (data) VALUES (?)
INFO     sqlalchemy.engine.Engine:log.py:117 [cached since 0.0033s ago] ('d2',)
INFO     sqlalchemy.engine.Engine:log.py:117 INSERT INTO b (a_id, c_id, data) VALUES (?, ?, ?)
INFO     sqlalchemy.engine.Engine:log.py:117 [generated in 0.00157s] (1, 1, None)
INFO     sqlalchemy.engine.Engine:log.py:117 INSERT INTO b (a_id, c_id, data) VALUES (?, ?, ?)
INFO     sqlalchemy.engine.Engine:log.py:117 [cached since 0.004245s ago] (2, 2, None)
INFO     sqlalchemy.engine.Engine:log.py:117 COMMIT
INFO     sqlalchemy.engine.Engine:log.py:117 BEGIN (implicit)
INFO     sqlalchemy.engine.Engine:log.py:117 SELECT a.id AS a_id, a.data AS a_data 
FROM a 
WHERE a.id = ?
INFO     sqlalchemy.engine.Engine:log.py:117 [generated in 0.00123s] (1,)
INFO     sqlalchemy.engine.Engine:log.py:117 SELECT b.a_id AS b_a_id, b.id AS b_id, b.c_id AS b_c_id, b.data AS b_data 
FROM b, (SELECT c.id AS id, c.data AS data 
FROM c 
WHERE c.data = ?) AS anon_1 
WHERE b.a_id IN (?) AND b.c_id = anon_1.id
INFO     sqlalchemy.engine.Engine:log.py:117 [generated in 0.00529s] ('d1', 1)
INFO     sqlalchemy.engine.Engine:log.py:117 SELECT a.id AS a_id, a.data AS a_data 
FROM a 
WHERE a.id = ?
INFO     sqlalchemy.engine.Engine:log.py:117 [cached since 0.01661s ago] (2,)
INFO     sqlalchemy.engine.Engine:log.py:117 SELECT b.a_id AS b_a_id, b.id AS b_id, b.c_id AS b_c_id, b.data AS b_data 
FROM b, (SELECT c.id AS id, c.data AS data 
FROM c 
WHERE c.data = ?) AS anon_1 
WHERE b.a_id IN (?) AND b.c_id = anon_1.id
INFO     sqlalchemy.engine.Engine:log.py:117 [generated in 0.00160s] ('d1', 2)
INFO     sqlalchemy.engine.Engine:log.py:117 ROLLBACK
INFO     sqlalchemy.engine.Engine:log.py:117 BEGIN (implicit)
INFO     sqlalchemy.engine.Engine:log.py:117 SELECT a.id AS a_id, a.data AS a_data 
FROM a 
WHERE a.id = ?
INFO     sqlalchemy.engine.Engine:log.py:117 [cached since 0.02867s ago] (1,)
INFO     sqlalchemy.engine.Engine:log.py:117 SELECT b.a_id AS b_a_id, b.id AS b_id, b.c_id AS b_c_id, b.data AS b_data 
FROM b, (SELECT c.id AS id, c.data AS data 
FROM c 
WHERE c.data = ?) AS anon_1 
WHERE b.a_id IN (?) AND b.c_id = anon_1.id
INFO     sqlalchemy.engine.Engine:log.py:117 [cached since 0.01152s ago] ('d1', 1)
INFO     sqlalchemy.engine.Engine:log.py:117 SELECT a.id AS a_id, a.data AS a_data 
FROM a 
WHERE a.id = ?
INFO     sqlalchemy.engine.Engine:log.py:117 [cached since 0.03495s ago] (2,)
INFO     sqlalchemy.engine.Engine:log.py:117 SELECT b.a_id AS b_a_id, b.id AS b_id, b.c_id AS b_c_id, b.data AS b_data 
FROM b, (SELECT c.id AS id, c.data AS data 
FROM c 
WHERE c.data = ?) AS anon_1 
WHERE b.a_id IN (?) AND b.c_id = anon_1.id
INFO     sqlalchemy.engine.Engine:log.py:117 [cached since 0.01861s ago] ('d1', 2)

### Versions

- OS: OSX 
- Python: 3.7
- SQLAlchemy: 1.4.28
- Database: Postgresql
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**experiment with alternate means of replacing params in cache key** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3418

**Comment by zzzeek** [comment]
two observations about what you have there:

1. the two subqueries you have are not considered by the caching system to be different, they're the same strucutre.  it's just that value which is changing.
2. the way in which the subquery is used here is not in fact something that was anticipated, and if I could, I would prefer to actually not have this case "supported" right now becuase right now it's going to silently fail, which is bad.

Basically adding the subquery using subq.c.col, instead of using a scalar subquery, means it gets added to the FROM clause at compile time, and the system by which selectinload and others adapt the incoming "AND" criteria to the current parameters has no means of replacing that column expression with a new one that has the correct parameters, which builds very deeply into the assumptions of the Core expression system and would be very hard to change right now.

so there's an alternate proposal I have above which is to no longer use "replacement" of the expression with new parameters and just carry along the translation dictionary with the element, but this is also a complicated change that I'm not sure will be successful.  im more or less out of time today to look into this.   various approaches here might not be feasible for 1.4 and may have to be only in version 2.0, not sure yet.

**Comment by sweetro** [comment]
Thanks for the additional context on the underlying caching strategy for subqueries @zzzeek and how this subquery is currently being applied!

I'll track this issue, and try an alternative approach for now :) -- please let me know if you have any follow up q's!

**Comment by zzzeek** [comment]
OK after trying two wacky ways of fixing this I think there's the best way for now which is that I figured out how to alter the current method so that it catches this specific pattern, that is, column attached to a subquery which might have parameters in it.   So we'll go with that and that makes this way less risky.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**accommodate for "clone" of ColumnClause** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3419

**Comment by sweetro** [comment]
Thanks so much @zzzeek -- my team is super grateful (and impressed) with how quickly you resolved this :)

**Comment by zzzeek** [comment]
oh the caching / ORM / loady ones scare the crap out of me so yep, i do these quick :)
