### ISSUE TITLE
Support `CheckConstraint(0 < col < 5)`

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#7506]
### Describe the use case

Currently, `CheckConstraint(0 < col < 5)` gives `TypeError: Boolean value of this clause is not defined`.

This would be nice to support (maybe creating an `and` condition internally).

**Comment by CaselIT** [comment]
Hi,

I don't think this is possible. Python does not allow overriding how the `and` and `or` operator work, so it's not possible to make it `0<col and col < 5` return a boolean expression.

**Comment by Dreamsorcerer** [comment]
@CaselIT I didn't mention an `and` operator...

Both comparisons can be overloaded just fine:

```
>>> class A:
...     def __init__(self):
...         self.compared_with = []
...     def __lt__(self, other):
...         self.compared_with.append(other)
...         return self
...     def __gt__(self, other):
...         self.compared_with.append(other)
...         return self
... 
>>> a = A()
>>> print(0 < a < 5)
<__main__.A object at 0x7fde3604ac70>
>>> print(a.compared_with)
[0, 5]
```

**Comment by CaselIT** [comment]
> @CaselIT I didn't mention an `and` operator...

`0 < a < 5` executes as `0 < a and a < 5`. There is an and operator here that you cannot override

**Comment by Dreamsorcerer** [comment]
I'm not sure what the difficulty is? I just showed that working code where the result is the modified class... Is this not exactly how a single comparison works?

**Comment by Dreamsorcerer** [comment]
There's no actual `and`, the dissembled code look like:
```
  1           0 LOAD_CONST               0 (0)
              2 LOAD_NAME                0 (a)
              4 DUP_TOP
              6 ROT_THREE
              8 COMPARE_OP               0 (<)
             10 JUMP_IF_FALSE_OR_POP    18
             12 LOAD_CONST               1 (5)
             14 COMPARE_OP               0 (<)
             16 RETURN_VALUE
        >>   18 ROT_TWO
             20 POP_TOP
             22 RETURN_VALUE
```

The only thing that needs to happen is that the value returned from the comparison is never `False`, and I assume a `Column` will never be `False`.

**Comment by CaselIT** [comment]
> Is this not exactly how a single comparison works?

No, a single comparison creates a binary expression. As mentioned the issue here is that there is no way of creating an `and` since python does not allow overloading of that operation.



> There's no actual `and`,

Please see https://docs.python.org/3.10/reference/expressions.html#comparisons

**Comment by zzzeek** [comment]
> @CaselIT I didn't mention an `and` operator...
> 
> Both comparisons can be overloaded just fine:
> 
> ```
> >>> class A:
> ...     def __init__(self):
> ...         self.compared_with = []
> ...     def __lt__(self, other):
> ...         self.compared_with.append(f"<{other}")
> ...         return self
> ...     def __gt__(self, other):
> ...         self.compared_with.append(f">{other}")
> ...         return self
> ... 
> >>> a = A()
> >>> print(0 < a < 5)
> <__main__.A object at 0x7fde36930e80>
> >>> print(a.compared_with)
> ['>0', '<5']
> ```

hey there -

this is not real world code.    Work with the code below, the goal is to have "0 < a < 5" produce the structure  `And(Binary(0 < Column("a")), Binary(Column("a") < 5))`.

```py

class Operators:
    def __lt__(self, other):
        return BinaryComparison(self, "<", other)

    def __gt__(self, other):
        return BinaryComparison(self, ">", other)

class And:
    def __init__(self, *expr):
        self.expr = expr

    def __repr__(self):
        return " AND ".join(repr(x) for x in self.expr)

class BinaryComparison(Operators):
    def __init__(self, left, operator, right):
        self.left = left
        self.operator = operator
        self.right = right

    def __repr__(self):
        return f"({self.left!r} {self.operator} {self.right!r})"

class Column(Operators):
    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return self.name

col = Column("A")

# goal
print(And(col > 0, col < 5))

# desired
print(0 < col < 5)

```

**Comment by zzzeek** [comment]
I suppose we could just do ast parsing and figure it out.  but then all expressions would have to be sent as lambdas, like PonyORM does.   Also, after doing a little bit of "SQL as lambdas" stuff in SQLAlchemy 1.4 that does a super slight amount of lambda introspection, I've no appetite for any more of that stuff.    full blown AST-based SQL expression systems are out of scope for what we have here.   A third party project could certainly build an AST->SQLAlchemy translator if anyone were interested in that.    definitely not worth it on this end just to suit a few outlier expression formats.

**Comment by Dreamsorcerer** [comment]
OK, I see the problem. The returned object is not passed from one comparison to the other, so it is only possible if you modify state on the original object like my first example. No point trying to hack that in.

**Comment by CaselIT** [comment]
> OK, I see the problem. The returned object is not passed from one comparison to the other, so it is only possible if you modify state on the original object like my first example. No point trying to hack that in.

this is a good way of explaining it. I'm usually not great at explanations
