### ISSUE TITLE
Method AsyncSession.invalidate() is missing.  

### ISSUE THREAD

**Issue by davidandreoletti** [sqlalchemy/sqlalchemy#7524]
### Describe the bug

`AsyncSession` is missing an `invalidate()` method to match its synchronous counterpart `Session.invalidate()`
Note: `AsyncConnection.invalidate()` is present.

### To Reproduce

```python
Nothing to reproduce
```

### Error

No runtime error.

### Versions

- OS: Irrelevant
- Python: Irrelevant
- SQLAlchemy: 1.4.29
- Database: Irrelevant
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): Irrelevant

**Comment by zzzeek** [comment]
i had no memory of that method, strange it isn't in the interfaces.

**Comment by davidandreoletti** [comment]
No worries. 

PS: Happy New Year and thanks for being an awesome library maintainer.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Added missing method ``invalidate` in the `AsyncSession`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3537

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**Added missing method ``invalidate` in the `AsyncSession`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3538

**Comment by zzzeek** [comment]
another one for the release...OK!
