### ISSUE TITLE
with_parent example query in docs is incorrect

### ISSUE THREAD

**Issue by ThirVondukr** [sqlalchemy/sqlalchemy#7540]
### Describe the bug

Example query from sqlalchemy [documentation](https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.with_parent) seem to produce cartesian product.
Models setup:
```py
from sqlalchemy import ForeignKey, Column, Integer, select
from sqlalchemy.orm import relationship, declarative_base, with_parent

Base = declarative_base()


class User(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)

    addresses = relationship("Address", back_populates='user')


class Address(Base):
    __tablename__ = 'addresses'
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('users.id'))

    user = relationship("User", back_populates="addresses")

some_user = User(id=42)
```
Query from documentation:
```py
query = select(Address).where(with_parent(some_user, Address.user))
```
```sql
SELECT addresses.id, addresses.user_id 
FROM addresses, users 
WHERE users.id = :param_1
```
Using `User.addresses` instead of `Address.user` seem to be producing correct query:
```py
query = select(Address).where(with_parent(some_user, User.addresses))
```
```sql
SELECT addresses.id, addresses.user_id 
FROM addresses 
WHERE :param_1 = addresses.user_id
```

### To Reproduce

```python
from sqlalchemy import ForeignKey, Column, Integer, select
from sqlalchemy.orm import relationship, declarative_base, with_parent

Base = declarative_base()


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)

    addresses = relationship("Address", back_populates="user")


class Address(Base):
    __tablename__ = "addresses"
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"))

    user = relationship("User", back_populates="addresses")


if __name__ == "__main__":
    some_user = User(id=42)
    incorrect_query = select(Address).where(with_parent(some_user, Address.user))
    print(incorrect_query, end="\n\n")
    
    correct_query = select(Address).where(with_parent(some_user, User.addresses))
    print(correct_query)
```

### Error

There's no error.

### Versions

- OS: Windows
- Python: 3.9.6
- SQLAlchemy: 1.4.26
- Database: None
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): None

**Comment by ThirVondukr** [comment]
Also if it's possible to do here i'd like to know if it's possible to use `with_parent` to load related objects of multiple entities, e.g. loading addresses for a list of users, like you could do using `selectinload`.
My use case for this is loading related entities in graphql application.

**Comment by zzzeek** [comment]
> Also if it's possible to do here i'd like to know if it's possible to use `with_parent` to load related objects of multiple entities, e.g. loading addresses for a list of users, like you could do using `selectinload`. My use case for this is loading related entities in graphql application.

with_parent only works with a single entity right now.   a new option could be created that would allow a list of target objects without much difficulty but for the moment I'd suggest writing the `in_()` criteria yourself.

**Comment by zzzeek** [comment]
thanks for the bug report!
