### ISSUE TITLE
condition in where has a strange result

### ISSUE THREAD

**Issue by minyoung90** [sqlalchemy/sqlalchemy#7542]
### Describe the bug

```
stmt1 = (
                sa.select(sa.func.count(models.A.id))
                .where(models.A.email == join_info.user_email)
                .where(models.A.is_validated == True)
            )
```
stmt1 is fine

```
stmt2 = (
                sa.select(sa.func.count(models.A.id))
                .where(models.A.email == join_info.user_email)
                .where(models.A.is_validated is True)
            )
```
but, stmt2 is not working what I expected.
stmt2 results different from stmt1

### To Reproduce

```python
See describe section.
```

### Error

No errors.

### Versions

- OS: ubuntu 20.04 lts
- Python: 3.9.4
- SQLAlchemy: 1.4.29
- Database: mysql 8.0.27
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pymysql

**Comment by CaselIT** [comment]
Hi,

There are periodical issues like this one or about `or` / `and`.
The python `is` operator cannot be overridden, so in your example `models.A.is_validated is True` returns `False` and what's executed is `where(False)`. You need to use `models.A.is_validated == True` or `models.A.is_validated == true()`

**Comment by minyoung90** [comment]
@CaselIT  Thanks for great explanation!
