### ISSUE TITLE
change InstanceState.load_options to a tuple

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7558]
in #7557 i can see this is a mutable set....that doesnt help anything here.  make this a tuple as well as context.propagated_options and all that.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**change state.load_options to a tuple** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3500
