### ISSUE TITLE
implement defined behavior for aliased(aliased(cls))

### ISSUE THREAD

**Issue by dannygoldstein** [sqlalchemy/sqlalchemy#7576]
### Describe the bug

In SA1.3.x, querying an alias of an alias of a mapped class yielded a SELECT against only one table, whereas in 1.4.x, querying an alias of an alias of a mapped class yields a SELECT against a comma join of a table with itself. 

How do I reproduce the SA 1.3.x behavior in SA 1.4.x? 

### To Reproduce

```python
import sqlalchemy as sa
from sqlalchemy import orm
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()

class User(Base):
    __tablename__ = 'user'
    id = sa.Column('user_id', sa.Integer, primary_key=True)
    name = sa.Column('user_name', sa.String(50))

a1 = orm.aliased(User)
a2 = orm.aliased(a1)

e = create_engine('postgresql://', echo=True)
s = orm.Session(e)

print(s.query(a2))
```

### Error

In SA 1.3.x, the SQL rendered is:

```sql
SELECT user_1.user_id AS user_1_user_id, user_1.user_name AS user_1_user_name
FROM "user" AS user_1
```

In SA 1.4.x, the SQL rendered is (note the comma join):

```sql
SELECT user_1.user_id AS user_1_user_id, user_1.user_name AS user_1_user_name
FROM "user" AS user_1, "user" AS user_2
```

How do I produce the 1.3.x result in 1.4.x, assuming I am only given `a2`? 

### Versions

- OS: OSX
- Python: 3.8.2
- SQLAlchemy: 1.3.24 and 1.4.29
- Database: postgres
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg

**Comment by zzzeek** [comment]
for now you can extract the mapper and always alias on that, this will work when given either the mapped class directly or an aliased:

```py
def safe_aliased(entity):
    return orm.aliased(sa.inspect(entity).mapper)

a1 = safe_aliased(User)
a2 = safe_aliased(a1)
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**propose double-aliased table logic (WIP)** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3527

**Comment by dannygoldstein** [comment]
this seems to work, thanks!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**enhance double-aliased table logic to handle more cases** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3531
