### ISSUE TITLE
primary mapper already defined error not working w/ map_imperatively direct call

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7579]
this will raise the expected error "Class '<class '__main__.User'>' already has a primary mapper defined":

```py
from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy import Table
from sqlalchemy.orm import mapper
from sqlalchemy.orm import registry

reg = registry()

m = reg.metadata
users = Table("users", m, Column("id", Integer, primary_key=True))

class User:
    pass

mapper(User, users)
mapper(User, users)
```

however this doesn't, it just crashes:

```
reg.map_imperatively(User, users)

reg.map_imperatively(User, users)
```

**Comment by zzzeek** [comment]
wow, in the jenkins coverage report, zero tests for that error condition, amazing

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**detect map_imperatively() called twice** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3529

**Comment by CaselIT** [comment]
where do I go to explore the coverage report?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**detect map_imperatively() called twice** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3530

**Comment by zzzeek** [comment]
hasn't run in a month. that's wrong.

**Comment by zzzeek** [comment]
wow another "main" name change missing.  not sure how i missed so many of those

**Comment by CaselIT** [comment]
well, at least now it's updated. I guess it will also show the annotated source on new runs right?

**Comment by zzzeek** [comment]
yeah
