### ISSUE TITLE
Python 3.11: TypeError: '<' not supported between instances of 'Mapper' and 'Mapper' 

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7591]
this is reported at https://bugzilla.redhat.com/show_bug.cgi?id=2042868.  the error seems to show that Mapper objects are getting stuck in sort_states() which itself is not what's supposed to happen.   We would assume this issue appeared in 1.4.30.

```
python-sqlalchemy fails to build with Python 3.11.0a4.

=================================== FAILURES ===================================
_________ BulkInsertUpdateTest.test_bulk_save_mappings_preserve_order __________
[gw0] linux -- Python 3.11.0 /usr/bin/python3
Traceback (most recent call last):
  File "/builddir/build/BUILD/SQLAlchemy-1.4.29/test/orm/test_bulk.py", line 169, in test_bulk_save_mappings_preserve_order
    s.bulk_save_objects(objects, preserve_order=False)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/SQLAlchemy-1.4.29/test/../lib/sqlalchemy/orm/session.py", line 3610, in bulk_save_objects
    obj_states = sorted(obj_states, key=key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'Mapper' and 'Mapper'
=========================== short test summary info ============================
```

**Comment by hroncok** [comment]
Note that in Fedora, we have 1.4.29.

**Comment by zzzeek** [comment]
hmm what's the event that made this bug get reported , is this a new python 3.11 release?

**Comment by zzzeek** [comment]
this failure happens every time?   that test doesn't have Mapper objects there, something would have be going much more wrongly.  i wonder if someting in Mock changed in 3.11

**Comment by zzzeek** [comment]
oh, wrong, we are sorting with a tuple that includes mapper there.  weird, OK we will fix

**Comment by hroncok** [comment]
> hmm what's the event that made this bug get reported , is this a new python 3.11 release?

not sure. apparently, some dependencies were missing until now

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**repair mapper sort** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3544

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**repair mapper sort** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3545

**Comment by zzzeek** [comment]
no problem!  we had some other regressions that were a little more urgent so we put out the release.
