### ISSUE TITLE
add "length" to repr() for Enum

### ISSUE THREAD

**Issue by cancan101** [sqlalchemy/sqlalchemy#7598]
**Describe the bug**

When a new enum column is added to a model that specified `native_enum=False` and then an explicit `length`, the associated auto generated migration will correctly have `native_enum=False` however it will not have the `length` set.

**Expected behavior**

Instead of:
```python
sa.Column('my_type', sa.Enum('A', 'B', 'C', name='my_type', native_enum=False), nullable=False),
```
should be:
```python
sa.Column('my_type', sa.Enum('A', 'B', 'C', name='my_type', native_enum=False, length=255), nullable=False), # where 255 is what was set in the models.py
```

**To Reproduce**
add this to model:
```py
    my_type = Column(
        Enum(
            enums.MyType,
            native_enum=False,
            create_constraint=False,
            length=255,
        ),
        nullable=False,
    )
```

**Versions.**
 - OS: 
 - Python:
 - Alembic: 1.7.5
 - SQLAlchemy: 1.4.27
 - Database: Postgres
 - DBAPI:

**Additional context**

**Have a nice day!**

**Comment by zzzeek** [comment]
patch, needs a test in test/sql/test_types.py

```diff
diff --git a/lib/sqlalchemy/sql/sqltypes.py b/lib/sqlalchemy/sql/sqltypes.py
index 42fad5e044..978296538d 100644
--- a/lib/sqlalchemy/sql/sqltypes.py
+++ b/lib/sqlalchemy/sql/sqltypes.py
@@ -1264,7 +1264,7 @@ class Enum(Emulated, String, TypeEngine[Union[str, enum.Enum]], SchemaType):
         self.create_constraint = kw.pop("create_constraint", False)
         self.values_callable = kw.pop("values_callable", None)
         self._sort_key_function = kw.pop("sort_key_function", NO_ARG)
-        length_arg = kw.pop("length", NO_ARG)
+        self._length_arg = length_arg = kw.pop("length", NO_ARG)
         self._omit_aliases = kw.pop("omit_aliases", True)
 
         values, objects = self._parse_into_values(enums, kw)
@@ -1403,9 +1403,14 @@ class Enum(Emulated, String, TypeEngine[Union[str, enum.Enum]], SchemaType):
             ) from err
 
     def __repr__(self):
+
+        additional_kw = [("native_enum", True)]
+        if self._length_arg is not NO_ARG:
+            additional_kw.append(("length", None))
+
         return util.generic_repr(
             self,
-            additional_kw=[("native_enum", True)],
+            additional_kw=additional_kw,
             to_inspect=[Enum, SchemaType],
         )
 

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add length to enum repr params** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3649

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**add length to enum repr params** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3650

**Comment by zzzeek** [comment]
still not fixed

**Comment by zzzeek** [comment]
OK, this is odd but "length" is ignored when native_enum is True, which is bad becasue native_enum will stil use non-native enum on non-supporting backends.  bigger issue though.  i think i will make this emit a warning for now

**Comment by zzzeek** [comment]
separate issue .
