### ISSUE TITLE
tests should interoperate with the warnings plugin, check for xdist enabled by means other than an xdist import check

### ISSUE THREAD

**Issue by mgorny** [sqlalchemy/sqlalchemy#7599]
### Describe the bug

When one of the pytest plugins installed in the test environment triggers `DeprecationWarning`s, the whole SQLAlchemy test suite fails.

### To Reproduce

```sh
# (e.g. on top of tox test environment)
. .tox/bin/activate
pip install pytest-freezegun
pytest
```

### Error

```pytb
========================================================= test session starts =========================================================
platform linux -- Python 3.10.2, pytest-7.0.0rc1, pluggy-1.0.0 -- /tmp/sqlalchemy/.tox/py/bin/python
cachedir: .pytest_cache
rootdir: /tmp/sqlalchemy, configfile: setup.cfg
plugins: freezegun-0.4.2, xdist-2.5.0, forked-1.4.0
collected 16051 items                                                                                                                 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/_pytest/main.py", line 321, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/_pytest/main.py", line 332, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/_pytest/main.py", line 661, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pytest_freezegun.py", line 55, in pytest_collection_modifyitems
INTERNALERROR>     if get_closest_marker(item, MARKER_NAME):
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pytest_freezegun.py", line 17, in get_closest_marker
INTERNALERROR>     if LooseVersion(pytest.__version__) < LooseVersion('3.6.0'):
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/setuptools/_distutils/version.py", line 53, in __init__
INTERNALERROR>     warnings.warn(
INTERNALERROR> DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

======================================================= no tests ran in 18.50s ========================================================
``` 

### Versions

- OS: Gentoo Linux
- Python: CPython 3.10.2
- SQLAlchemy: d46a4c0326bd2e697794514b920e6727d5153324
- Database: n/a
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

### Additional context

Normally we avoid these kind of issues in Gentoo via passing `-Wdefault`. However, this doesn't work on SQLAlchemy, probably because it passes `-p no:warnings`.

If I reenable the warnings plugin (i.e. `-p warnings -Wdefault`), the test suite fails soon enough since it expects warnings to be turned into exceptions, e.g.:

```pytb
_________________________ DeclarativeMultiBaseTest_declarative_base_nometa_superclass.test_column_named_twice _________________________
Traceback (most recent call last):
  File "/tmp/sqlalchemy/test/orm/declarative/test_basic.py", line 817, in test_column_named_twice
    assert_raises_message(
  File "/tmp/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 341, in assert_raises_message
    return _assert_raises(
  File "/tmp/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 356, in _assert_raises
    with _expect_raises(except_cls, msg, check_context) as ec:
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/tmp/sqlalchemy/test/../lib/sqlalchemy/testing/assertions.py", line 396, in _expect_raises
    assert success, "Callable did not raise an exception"
AssertionError: Callable did not raise an exception
assert False
```

That said, I have no clue why it does expect exceptions rather than warnings, since FWICS `sqlalchemy/testing/assertions.py` has functions to assert on warnings.

So finally, I try a different approach: using `export PYTEST_DISABLE_PLUGIN_AUTOLOAD=1` to prevent random plugins from interfering. However, now the test suite fails because it assumes that if `import xdist` succeeded, then pytest-xdist plugin must be present while that's not necessarily true:

```pytb
========================================================= test session starts =========================================================
platform linux -- Python 3.10.2, pytest-7.0.0rc1, pluggy-1.0.0 -- /tmp/sqlalchemy/.tox/py/bin/python
cachedir: .pytest_cache
rootdir: /tmp/sqlalchemy, configfile: setup.cfg
collected 16051 items                                                                                                                 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/_pytest/main.py", line 321, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/_pytest/main.py", line 332, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/_pytest/main.py", line 660, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/tmp/sqlalchemy/.tox/py/lib/python3.10/site-packages/pluggy/_manager.py", line 262, in check_pending
INTERNALERROR>     raise PluginValidationError(
INTERNALERROR> pluggy._manager.PluginValidationError: unknown hook 'pytest_configure_node' in plugin <module 'test.conftest' from '/tmp/sqlalchemy/test/conftest.py'>

======================================================== no tests ran in 9.44s ========================================================
```

**Comment by zzzeek** [comment]
hi - 

thanks for expressing the issue clearly.  i need to see where "xdist" is being tested based on an import check, because there are state variables in play that we are checking.  this might be an issue with pytest-xdist on that end.


on the "warnings" end, the warnings plugin might not have existed when we first adapted the test suite to pytest, or we didnt know about it, our requirements are that any deprecated Python API in SQLAlchemy has to raise an exception, that has to be turned on.   we never expected that third parties would need to run our test suite while also installing other plugins.  can you describe your use case that these plugins must be installed?  we've had other such reports from packagers, and there's at least some pytest plugins that flat out dont work with test suites that don't follow special conventions.  im not sure how to determine the degree to which the requirement "SQLAlchemy's test suite must function with arbitrary plugins installed" needs to be fulfilled, nor how we can guarantee that.

**Comment by zzzeek** [comment]
I've identified the xdist part, that can be fixed.

still looking to see what the canonical approach for warnings is.  we can't have any Python deprecation warnings passing in SQLAlchemy.  deprecation warnings emitted by other plugins, those aren't our problem.

**Comment by zzzeek** [comment]
OK I got xdist, the problem when you turn on wrnings capture is that theres a subset of tests using the wrong fixgture, will see how extensive that is.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**dont use exception catches for warnings; modernize xdist detection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3555

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**dont use exception catches for warnings; modernize xdist detection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3556

**Comment by zzzeek** [comment]
the patches submitted will solve all issues for the workarounds you've tried.   as far as default not erroring out for warnings by third party plugins that have deprecations, that's not there yet, i don't have total faith in the "module" argument of filterwarnings and would need to have more time to test.

that said, these fixes will allow you to just use "-p warnings -W ignore" without any issues.

**Comment by mgorny** [comment]
As far as xdist is concerned, I think there should be a way to query whether the plugin is loaded from pytest config. However, I haven't been able to find it in the docs and I'm afraid I can't spare more time for that right now. I've seen other projects take similar approach, so if you figure out a better way, I'll be happy to pass it on.

I'm afraid I don't really understand SQLAlchemy's test suite. The normal "pytest" way is to use `with pytest.warns(...)`.

The use case is that we're testing SQLAlchemy using the complete set of packages from production systems. Unfortunately, Python packages tend to interact in a lot of unexpected ways, and running tests in a dedicated virtualenv doesn't really guarantee that the package won't fail in unexpected ways in the production environment. Testing with complete set of production packages doesn't guarantee this 100% either but we've managed to catch quite a lot weird failures in various packages this way. Ofc there are false positives too.

My private opinion is that it's a design mistake that all pytest plugins are always loaded automatically but there's not much that can be done about it at this point. We're aware that some plugins break test suites more than others, and we tend to explicitly disable them in these cases. However, this really makes sense when these plugins do something intrusive. I don't think emitting `DeprecationWarning`s falls into this category, especially that they tend to be triggered independently (e.g. by setuptools upgrade).

**Comment by zzzeek** [comment]
> As far as xdist is concerned, I think there should be a way to query whether the plugin is loaded from pytest config. However, I haven't been able to find it in the docs and I'm afraid I can't spare more time for that right now. I've seen other projects take similar approach, so if you figure out a better way, I'll be happy to pass it on.

i found it, it's here: https://docs.pytest.org/en/6.2.x/writing_plugins.html#optionally-using-hooks-from-3rd-party-plugins

> 
> I'm afraid I don't really understand SQLAlchemy's test suite. The normal "pytest" way is to use `with pytest.warns(...)`.

our test suite predates the existence of pytest by many years.   adoption of pytest has been gradual.

> 
> My private opinion is that it's a design mistake that all pytest plugins are always loaded automatically but there's not much that can be done about it at this point. We're aware that some plugins break test suites more than others, and we tend to explicitly disable them in these cases. However, this really makes sense when these plugins do something intrusive. I don't think emitting `DeprecationWarning`s falls into this category, especially that they tend to be triggered independently (e.g. by setuptools upgrade).

we have a user that is packaging something else somewhere and they run with about 45 plugins installed, then when those plugins have bugs they fail to check where the error arises and they report them to us.   often the user in question doesn't bother to check that he's even running our test suite and not someone else's.   So we are a little triggered by the "packagers running lots of plugins" use case, not really your fault (though now you know I read SQLAlchemy tweets :) )

**Comment by mgorny** [comment]
Thanks for the patch. I really like how robust it is. I'm going to start testing it in a few minutes.

I understand the problem with the user and I'm sorry to hear you've had to waste your time on that. I'm really trying hard to verify the issues I'm reporting, and avoid bothering people if things can be easily solved on our end. At this point, we already have quite an extensive documentation on how to workaround various test suite related problems. Unfortunately, in this case too many different problems simply layered and I've gotten a bit frustrated which lead to my tweet.

Naturally, I'm going to follow that up with praise for the quick response. Or I can remove it, if you prefer.

**Comment by mgorny** [comment]
Ok, I see that there's quite a lot of `expect_warnings` failures but I suppose you can reproduce that yourself. I'm sorry but it's gotten really late, so I'm not going to wait for the tests to finish. Please let me know if you need my help.

**Comment by zzzeek** [comment]
OK I've gotten the warnings also localized to the modules we care about, I think the reason "module" wasn't there before was to have the warnings filters apply to other libraries like alembic, but alembic has its own warnings filter now.   subsequent to this merge we can just start using the warnings plugin for 2.0 and likely alembic since it is nice in how it reports warnings we dont care about at the end.

**Comment by zzzeek** [comment]
our test suite had real problems, easy ones, that I am super glad to have fixed. thats why I really want people to come to me with the issues they have.   there's no need for you to test anything and we have both benefitted so thanks for reporting.
