### ISSUE TITLE
Convert build system to cibuildwheel

### ISSUE THREAD

**Issue by tgross35** [sqlalchemy/sqlalchemy#7607]
This issue was originally titled "request for musllinux wheel"

It could be a good idea to implement cibuildwheel for the build system as a github action, to replace what currently exists. Cibuildwheel builds, tests, and optionally uploads wheels for all python-supported environments (manylinux, musllinux, windows and mac on arm, x86, x84, with python 3.6-3.10 and pypy if desired).

The github action setup is here:
https://cibuildwheel.readthedocs.io/en/stable/setup/#github-actions

The only changes needed should be the github action setup, and `[tool.cibuildwheel]` config in pyprojet.toml

**Comment by CaselIT** [comment]
I did not know of the existence of cibuildwheel. It seems very useful.

It seems we can migrate to that and it should be easy to support.

**Comment by tgross35** [comment]
Hope you don't mind @CaselIT, updated the issue to just be migrating to cibuildwheel. Can of course be closed if that's not the plan, but the merits of cibw are pretty strong.

Their demo gh action is good for starters: https://cibuildwheel.readthedocs.io/en/stable/setup/#github-actions and numpy has a good example of "over the top config for everything you could possibly want to do."

**Comment by CaselIT** [comment]
Sure, it makes sense to adopt cibuildwheel.

Thanks for the pointers regarding the ci example. Will take a look at it and numpy too

**Comment by zzzeek** [comment]
how does it build for Apple M1 on Github Actions ?

**Comment by tgross35** [comment]
It seems like on `macos-10.15` you are able to compile for both. I don't really understand all the inner workings but I think the relevant bit is here https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/macos.py#L209-L244

**Comment by tgross35** [comment]
More accurate context https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/macos.py#L434-L453

Looks like you can cross compile for arm but can't test the build m1 wheel

**Comment by sqla-tester** [comment]
**Trevor Gross** has proposed a fix for this issue in the **main** branch:

**Use cibuildwheel to create wheels** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4047
