### ISSUE TITLE
base logging helper function clobbers log message metadata

### ISSUE THREAD

**Issue by Anthchirp** [sqlalchemy/sqlalchemy#7612]
### Describe the bug

[`lib/sqlalchemy/engine/base.py` contains a logging helper function](https://github.com/sqlalchemy/sqlalchemy/blob/ff1ab665cb1694b85085680d1a02c7c11fa2a6d4/lib/sqlalchemy/engine/base.py#L133-L139):
```python
    def _log_info(self, message, *arg, **kw):
        fmt = self._message_formatter

        if fmt:
            message = fmt(message)

        self.engine.logger.info(message, *arg, **kw)
```
Using this function will cause all emitted log messages to contain the metadata `function='_log_info'` and `line=131`. This makes it harder to group and filter messages.

### To Reproduce

```python
import sqlalchemy.engine.base
import logging
from unittest import mock

formatter = logging.Formatter("%(asctime)s %(funcName)s:%(lineno)d: %(message)s")
syslog = logging.StreamHandler()
syslog.setFormatter(formatter)
logging.getLogger().addHandler(syslog)
logging.getLogger().setLevel(logging.INFO)
logger = logging.getLogger(__name__)

logger.info("Message with correct metadata")
            
mock_self = mock.Mock()
mock_self.engine.logger = logger
mock_self._message_formatter = None
sqlalchemy.engine.base.Connection._log_info(mock_self, "Metadata overwritten")
```

### Error

```
2022-01-25 10:09:48,658 <module>:12: Message with correct metadata
2022-01-25 10:09:48,658 _log_info:131: Metadata overwritten
```

### Versions

- OS: independent
- Python: independent
- SQLAlchemy: 1.4.6 and newer, haven't checked when this was introduced

### Additional context

I don't have a ready solution that allows retaining the metadata with a helper function (ie. it's not as simple as adding a `stacklevel=2` with the `warnings` module)

**Comment by zzzeek** [comment]
im not familiar with "funcname" and "lineno" tokens in logging, and IIUC from what you have there it looks like it's doing some kind of traceback inspection when you emit a log line, which means that no logging helper functions of any kind can be used by any application.   if I have all that right, that's unfortunately an unreasonable constraint so I wouldnt see any way to fix this.   But this is just my reading in the last 30 seconds, so correct me if im not getting it right.

I would recommend setting a separate formatter for the sqlalchemy.engine namespace that has the prefixing information you want pre-formatted.

**Comment by Anthchirp** [comment]
[funcname and lineno are part of the Python `LogRecord` object, next to 'message'](https://docs.python.org/3/library/logging.html#logrecord-objects), which is of course the text that is usually shown on stdout. However all the other fields are on an equal level, even if not shown. For my use case we forward all logging records to a graylog server, where they are aggregated. All sqlalchemy related log messages are shown as coming from the same file, the same function, and the same line, although it is clear that they come from separate log calls. This makes it hard to filter for relevant messages.
![image](https://user-images.githubusercontent.com/2102431/150995759-f41d642d-5f26-42f1-a477-3f607e1badcf.png)

Judging from the code the only reason these helper functions exist is to include prefixes into the log message, specifically a [`logging_token`](https://docs.sqlalchemy.org/en/14/core/engines.html#setting-per-connection-sub-engine-tokens). That token is then prefixed into the message.

This is unfortunate, as a cleaner way would have been to leave the message alone, add the token as an [_`extra`_](https://docs.python.org/3/library/logging.html#logging.Logger.debug) field to the log message (example from the Python logging documentation):
```python
d = {'clientip': '192.168.0.1', 'user': 'fbloggs'}
logger = logging.getLogger('tcpserver')
logger.warning('Protocol problem: %s', 'connection reset', extra=d)
```
That way the field can be directly filtered on, the original message is retained - and there would not be a need for a helper function, therefore you'd also get the correct logging context in the message (There's no need to add the field to every individual message, [a `LoggerAdapter` can do that for you](https://docs.python.org/3/howto/logging-cookbook.html#adding-contextual-information-to-your-logging-output)).

I guess the main underlying issue is that people weren't aware that the logging framework does a lot more underneath the hood than just carry a flat string...

I'm happy to have a look into upgrading SQLAlchemy to make full use of python logging framework features. It would probably be incompatible with the current `logging_token` functionality though.

**Comment by zzzeek** [comment]
I'm pretty aware the logging framework is quite extensible so I would request that we refrain from talking about decisions being "unfortunate" or otherwise commenting on the relative ignorance of the developers, kind of makes it difficult for me to be open to your suggestions.  sorry

**Comment by CaselIT** [comment]
It seems that no-one knows all the stuff that the logging module can do.

From https://docs.python.org/3/library/logging.html#logging.Logger.debug it seems we can just set `stacklevel=2` to fix this

**Comment by Anthchirp** [comment]
@zzzeek that is a fair enough comment, and no disrespect intended.

@CaselIT nailed it... It looks like a trivial and backwards compatible solution is indeed available. :laughing: 

I'll have a go at making a PR. And if at some point someone really wants to put in the work to have extra fields then that can be done separately.

**Comment by zzzeek** [comment]
i dont really recall why i have it implemented with that extra formatting, i'd need to review what the docs /changelog / rationale for "logging token" are.  i think the idea was that i didnt want a blank pair of brackets in the log message if there were no "logging token" but I could have just formatted it with "[]".

but otherwise with _log_info and _log_debug, those methods are also called from CursorResult and maybe elsewhere too.  that is, the purpose of these methods is to abstract away additional logging behaviors that the Connection wants to maintain.     So yes, you can make a LoggerAdapter or otherwise inject using systems like that.  overall though, if we did that here and made sure we invoked from the logger directly where it's used, i dont know of an automated way to prevent it from being changed again three years later unless we add some new tests that asserts the formatting of the messages including code lines (we have a test suite for logging that already runs tests like this, so I think we should add to it).

so if we can in fact just stick a stacklevel in , let's do that, but yes the thing I'm actually doing in _log_info / _log_debug looks kind of clumsy in any case so I'm open to cleaning that up also.

**Comment by zzzeek** [comment]
@Anthchirp  if you want to try asserting a particular log output for these fields, so that this doesnt break later, see if you can add to https://github.com/sqlalchemy/sqlalchemy/blob/main/test/engine/test_logging.py , where in places like https://github.com/sqlalchemy/sqlalchemy/blob/main/test/engine/test_logging.py#L659 you can see we are using logging handlers to capture log messages and we then assert that they have a desired format.

**Comment by Anthchirp** [comment]
-> #7615

**Comment by sqla-tester** [comment]
**Markus Gerstel** has proposed a fix for this issue in the **main** branch:

**Fix up Python logging metadata** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3565

**Comment by sqla-tester** [comment]
**Markus Gerstel** has proposed a fix for this issue in the **rel_1_4** branch:

**Fix up Python logging metadata** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3566

**Comment by zzzeek** [comment]
so a more concrete example, test case:

```py
import sqlalchemy.engine.base
import logging
from unittest import mock
from sqlalchemy import create_engine

formatter = logging.Formatter("%(asctime)s %(funcName)s:%(lineno)d: %(message)s")
syslog = logging.StreamHandler()
syslog.setFormatter(formatter)
logging.getLogger("sqlalchemy.engine").addHandler(syslog)
logging.getLogger("sqlalchemy.engine").setLevel(logging.DEBUG)


e = create_engine("sqlite://")

with e.connect() as conn:
    result = conn.exec_driver_sql("Select 1")
    result.fetchone()
```


before:

```
2022-01-27 09:35:46,170 _log_info:139: BEGIN (implicit)
2022-01-27 09:35:46,171 _log_info:139: Select 1
2022-01-27 09:35:46,171 _log_info:139: [raw sql] ()
2022-01-27 09:35:46,171 _log_debug:147: Col ('1',)
2022-01-27 09:35:46,171 _log_debug:147: Row (1,)
2022-01-27 09:35:46,171 _log_info:139: ROLLBACK

```

after:

```
2022-01-27 09:35:34,298 _begin_impl:885: BEGIN (implicit)
2022-01-27 09:35:34,298 _execute_context:1531: Select 1
2022-01-27 09:35:34,298 _execute_context:1536: [raw sql] ()
2022-01-27 09:35:34,298 _init_metadata:1197: Col ('1',)
2022-01-27 09:35:34,298 log_row:1124: Row (1,)
2022-01-27 09:35:34,298 _rollback_impl:911: ROLLBACK
```

so yes, better.  didnt realize people would want to filter like that.

**Comment by sqla-tester** [comment]
**Markus Gerstel** has proposed a fix for this issue in the **main** branch:

**Fix up Python logging metadata** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3565

**Comment by sqla-tester** [comment]
**Markus Gerstel** has proposed a fix for this issue in the **rel_1_4** branch:

**Fix up Python logging metadata** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3566

**Comment by zzzeek** [comment]
so heads up, the tokens in use here are in all Python versions but "stacklevel" is only in Python 3.8 and above.    so, hoping your use case is on py38 or higher.
