### ISSUE TITLE
allow conditional DDL to be assocaited with SchemaItem directly

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7631]
the Index object automatically associates itself with a Table, and Alembic would also like constraints and indexes to be part of the table metadata.   this makes it impossible to use conditional DDL with these elements.   The conditional DDL system should be integrated into the normal DDL execution sequence where it can be taken advantage of by Alembic as well.

proposal looks like:

```py
from sqlalchemy import CheckConstraint, Column
from sqlalchemy import create_engine
from sqlalchemy import Index
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import declarative_base
Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    num = Column(Integer)
    data = Column(String)

    __table_args__ = (
        Index("my_pg_index", data).ddl_if(dialect='postgresql'),
        CheckConstraint("num > 5").ddl_if(dialect="postgresql")

    )

e1 = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e1)


e2 = create_engine("postgresql://scott:tiger@localhost/test", echo=True)
Base.metadata.drop_all(e2)
Base.metadata.create_all(e2)

```

the above index and check constraint only generate on PostgreSQL.    later, will see if Alembic can also invoke the conditional rule when it does autogenerate comparison against a particular target database.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**generalize conditional DDL throughout schema / DDL** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3569
