### ISSUE TITLE
implement MS dataclass descriptor for DeclarativeBase

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7642]
this would be the final missing feature for what the mypy plugin does.    the spec as we know is at  https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md .  But they've **implemented it** and it **requires no imports!!**  https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md#alternate-form

pydantic doing it here: https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L97-L104

**Comment by CaselIT** [comment]
This probably solves also https://github.com/sqlalchemy/sqlalchemy/issues/6982 ?

**Comment by zzzeek** [comment]
seems to be the same thing yes.     I've found a wrinkle that MS probably would have to address - we annotate as `Mapped[int]` and not `[int]`.  so...need to check with them.

**Comment by CaselIT** [comment]
that may be a problem. I think it's the same issue we have with Row. there is no way of getting the inner type from a generic type

**Comment by zzzeek** [comment]
https://github.com/microsoft/pyright/discussions/2958

**Comment by CaselIT** [comment]
let's see what they reply

**Comment by zzzeek** [comment]
from the reply it looks like what they have there is very specific to the way dataclasses work, it's already coming through in a pep and wont work for us in two different ways, no way to transform from descriptor to direct type and also the arguments to `__init__` are considered to be required unless there's an explicit default on the mapping side.  so i think both this and #6982 should just be a "wontfix".  our `__init__` method is not nearly as interesting as that of dataclasses in any case since all arguments are keyword and optional.

**Comment by mehdigmira** [comment]
Will this only be available on SQLAlchemy 2.0 ? Would be awesome to have a better typing experience with pyright/pylance with 1.4, especially as SQLAlchemy 2.0 release date is not known yet.

**Comment by zzzeek** [comment]
@mehdigmira the dataclass feature in 2.0 builds upon an entirely reworked declarative system that is foundationally based on pep-484 annotations.  all of this would be a non-starter in 1.4 as 1.4 is still python 2 compatible, beyond the fact that 1.4 is well into feature freeze in any case.

**Comment by ramarivera** [comment]
Hey @zzzeek , small question: if I install the latest version of SQLAlchemy (`2.0.0b1`) plus the RC for Python 3.11, I should be able to reproduce the typing magic you had in your screenshot? 🥺

**Comment by CaselIT** [comment]
Yes. Also no need of python 3.11. the library will work from python 3.7+, but python 3.9 is better for typing related stuff

**Comment by ramarivera** [comment]
Any clue what I could be missing then? 
I have prerelease Pylance, latest Sqlalchemy, Python 3.11.

And yet I cannot get any error where I suppose there should be.

One think I noticed is different is the lack of `HasDataclassSemantics` class (I cannot import it)

![image](https://user-images.githubusercontent.com/7547875/195984925-5e186576-26af-4786-85ce-4f961a2c5164.png)

**Comment by CaselIT** [comment]
Please refer to the docs https://docs.sqlalchemy.org/en/20/orm/dataclasses.html

The init is generated only in case of dataclass usage

**Comment by ramarivera** [comment]
Oh.. I just noticed my very dumb mistake 🤦 
Thanks for pointing me to the docs

**Comment by CaselIT** [comment]
No worries, it image above had an old name that has been changed since that image was created
