### ISSUE TITLE
[sqlite] RETURNING is not supported by this dialect's statement compiler

### ISSUE THREAD

**Issue by loynoir** [sqlalchemy/sqlalchemy#7644]
### Describe the bug

```txt
CompileError: RETURNING is not supported by this dialect's statement compiler
```

### To Reproduce

```python
import sqlalchemy as sa
import sqlalchemy.dialects.sqlite as dialects_sqlite
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Message(Base):
    __tablename__ = "message"
    id = sa.Column(sa.Integer, primary_key=True, autoincrement=True)
    message = sa.Column(sa.String)
    foo = sa.Column(sa.String, server_default="bar")


print(
    sa.insert(Message.__table__)
    .returning(Message.foo)
    .compile(dialect=dialects_sqlite.dialect())
)
```

### Error

```
CompileError: RETURNING is not supported by this dialect's statement compiler.
``` 

### Versions

- OS:
- Python:
- SQLAlchemy: 1.4.31
- Database:
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

### Additional context

- What's new in SQLite 3.35
https://antonz.org/sqlite-3-35/
- SQLite changelog 2021-03-12 (3.35.0)
https://www.sqlite.org/changes.html
- SQLite returing
https://www.sqlite.org/lang_returning.html

**Comment by zzzeek** [comment]
hi there -

this work is tracked in #6195 which we can hopefully provide as part of the SQLAlchemy 2.0 release.
