### ISSUE TITLE
Support for PostgreSQL version 14

### ISSUE THREAD

**Issue by balu211221** [sqlalchemy/sqlalchemy#7647]
### Describe the use case

Need support for the PostgreSQL version 14. Currently,  support for 13 is there https://docs.sqlalchemy.org/en/14/dialects/#support-levels-for-included-dialects.

### Databases / Backends / Drivers targeted

PosgreSQL v14

### Example Use

.

**Comment by CaselIT** [comment]
Hi,

Postgresql 14 is already supported. The documentation is probably outdated
