### ISSUE TITLE
`CreateSchema` Incorrect Argument for Superclass when calling print() without a specific dialect

### ISSUE THREAD

**Issue by luciengaitskell** [sqlalchemy/sqlalchemy#7664]
### Describe the bug

The `CreateSchema` class constructor expects a `str` value and passes it to the `_CreateDropBase` superclass. However, this causes an error as it expects an element with the method `create_drop_stringify_dialect()`.

### To Reproduce

```python
from sqlalchemy.schema import CreateSchema

CreateSchema("abc")
```

### Error

```
  File "main.py", line 52, in <module>
    print(CreateSchema("abc"))
  File "lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 562, in __str__
    return str(self.compile())
  File "lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 485, in compile
    if self.stringify_dialect == "default":
  File "lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 392, in stringify_dialect
    return self.element.create_drop_stringify_dialect
AttributeError: 'str' object has no attribute 'create_drop_stringify_dialect'
``` 

### Versions

- OS: macOS 11.6
- Python: 3.9
- SQLAlchemy: 1.4.31
- Database: n/a
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

**Comment by zzzeek** [comment]
thanks for reporting

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**fix stringify for CreateSchema** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4382

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**fix stringify for CreateSchema** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4383

**Comment by obataku** [comment]
this also affects `DropSchema` afaict:
```
>>> print(DropSchema("foo"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 562, in __str__
    return str(self.compile())
  File ".../lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 485, in compile
    if self.stringify_dialect == "default":
  File ".../lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 401, in stringify_dialect
    return self.element.create_drop_stringify_dialect
AttributeError: 'str' object has no attribute 'create_drop_stringify_dialect'
```

that said, what is the preferred way to render/compile these DDL statements? for statements I know we can call `compile` directly but that isn't the case here

**Comment by zzzeek** [comment]
ouch, that was bad

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Correct #7664 to include DropSchema** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4398

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**Correct #7664 to include DropSchema** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4399
