### ISSUE TITLE
sqlalchemy "do_orm_execute" event does not trigger for pandas.read_sql

### ISSUE THREAD

**Issue by pbillante** [sqlalchemy/sqlalchemy#7707]
### Describe the bug

When using the pd.read_sql function in pandas, the SQLAlchemy "do_orm_execute" event is not triggered, so logic tied to that event will not run. If for example, the application is using the do_orm_execute event to enforce security rules, this can be a problem as no errors are triggered and all results are returned.

SQLAlchemy recommends using this event for public filters and other use cases. See:
https://docs.sqlalchemy.org/en/14/_modules/examples/extending_query/filter_public.html

It is possible this is due to some logic missing in SQLAlchemy, but I noticed it only for queries using this pandas function.

### To Reproduce

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import Column, Integer, String, event
from sqlalchemy.orm import Session
import pandas as pd

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://[insert connection here]'
db = SQLAlchemy(app)


@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
    print("*** The do_orm_execute event was triggered ***")


class Data(db.Model):
    __tablename__ = 'testdata'
    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    name = Column(String(255))
    info = Column(String(255))


if __name__ == '__main__':
    # setup some test data
    print("insert test data")
    data = Data(
      name="Alice",
      info="Apple")
    db.session.add(data)
    db.session.commit()
    data = Data(
      name="Bill",
      info="Banana")
    db.session.add(data)
    db.session.commit()

    # results from orm query
    print("\norm test")
    orm_data = Data.query.all()
    for result in orm_data:
       print(result.id, result.name, result.info)

    # results from pandas query
    print("\npandas test")
    pd_data = Data.query
    df = pd.read_sql(pd_data.statement, pd_data.session.bind)
    print(df)

-------------------------------------------------------------------------
Generates this result:
-------------------------------------------------------------------------

insert test data

orm test
*** The do_orm_execute event was triggered ***
1 Alice Apple
2 Bill Banana

pandas test
   id   name    info
0   1  Alice   Apple
1   2   Bill  Banana

Process finished with exit code 0
```

### Error

```
# Copy complete stack trace and error message here, including SQL log output if applicable.
``` 

### Versions

- OS: Mac OS, Linux
- Python: 3.9
- SQLAlchemy: 1.4.31
- Database: MariaDB 10.4.22
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): PyMySQL

### Additional context

Also logged with pandas, however it was determined this is not a pandas bug:
https://github.com/pandas-dev/pandas/issues/45978

**Comment by CaselIT** [comment]
Hi,

This is expected. do_orm_execute is run only when using the orm via the session, not when a core connection is used directly.
Pandas uses a core connection, so that's the reason for the event not triggering.

I think the equivalent core event is before_execute, but it's not a 1-1 replacement for the do_orm_execute, since the core connection can accept a wider range of executable items.

@zzzeek do you have other suggestions here? Maybe the docs should make this clearer?

**Comment by zzzeek** [comment]
The listen is for the Session class and there is no Session passed to pandas.read_sql().       the approach here should use core level events like the [before_execute](https://docs.sqlalchemy.org/en/14/core/events.html?highlight=before_execute#sqlalchemy.events.ConnectionEvents.before_execute).  We could add a note at [do_orm_execute](https://docs.sqlalchemy.org/en/14/orm/events.html?highlight=do_orm_execute#sqlalchemy.orm.SessionEvents.do_orm_execute) itself noting this is only for ORM executions.   but people would have to read that doc to know this, we can't note it in every example everywhere.

**Comment by CaselIT** [comment]
> We could add a note at [do_orm_execute](https://docs.sqlalchemy.org/en/14/orm/events.html?highlight=do_orm_execute#sqlalchemy.orm.SessionEvents.do_orm_execute) itself noting this is only for ORM executions

that what I meant

**Comment by pbillante** [comment]
Thanks, understood.  If I wanted to replicate the same kind of logic described in the [orm public filter example](https://docs.sqlalchemy.org/en/14/_modules/examples/extending_query/filter_public.html) where I want to set a default filter for all queries including pd.read_sql, but instead using the [before_execute](https://docs.sqlalchemy.org/en/14/core/events.html?highlight=before_execute#sqlalchemy.events.ConnectionEvents.before_execute) event, would this be an acceptable approach?

```
@event.listens_for(Engine, "before_execute", retval=True)
def _add_filtering_critera(conn, clauseelement, multiparams, params, execution_options):
    from sqlalchemy.sql.selectable import Select

    if isinstance(clauseelement, Select) and "_sa_orm_load_options" not in execution_options:
        table = clauseelement.froms[0]
        try:
            clauseelement = clauseelement.where(table.c.public == session['public'])
        except AttributeError:
            pass

    return clauseelement, multiparams, params
```

It seems to work for simple pandas queries, except when clauseelement.froms[0] is a Join object.  Is there a recommended approach for adding the where clause for joins?

**Comment by zzzeek** [comment]
so one thing I think is relevant here is that when someone makes a statement and then invokes pd.read_sql(), that is already something that happens in your application, so in theory you could forego using events entirely and instead make sure that pd.read_sql() isn't called directly, rather, it goes through a library function that applies the rules you want to statements that are incoming.

another thing about [read_sql](https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html) is that the "con" argument is listed as a "connectable", which refers to an object that has a .connect() method.   If they are in fact calling .connect() on the object passed, that would make it more difficult to pass a Session instead of a connection to it, but you could make a Session subclass with a connect() method that returns "self", then they'd be using session.execute().

Still another thing is, pandas read_sql *should* have an option to accept a Session object directly since session.execute() is now an important API that people are going to be using quite a lot.  I'd request this feature from them.

re: select with join(), doing manipulation of select() is not that convenient which is why the whole with_loader_criteria() thing were added.  I did not anticipate users would be stymied from using this API because Pandas doesn't allow it.    Digging into the select().froms and getting a Join object, you can add criteria to the ON clause of it, like join.onclause = and_(join.onclause, new_criteria).   that's fine.  But it would be a whoile lot better if you could use the API that I wrote for this use case as I put a ton of effort into making this very common case possible.

If pandas is looking for a "connectable" see if you can do this:

```py
class ConnectableSession(Session):
    def connect(self):
       return self

sess = ConnectableSession()
pandas.read_sql(statement, sess)

```

because with_loader_criteria does all of that where/from stuff that is not very easy to do manually.

**Comment by pbillante** [comment]
Great, I'd like to try to test the "connectable" idea and keep it all in a single method.

But, I'm unclear on where in my original code I can create a new ConnectableSession object like you've described using my current db = SQLAlchemy(app) config, and pass that to pandas along with the query statement like in the example.  

How would I apply that?

**Comment by zzzeek** [comment]
well that's flask-sqlalchemy stuff, I'm looking at https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/#flask_sqlalchemy.SQLAlchemy and it doesnt seem like it's that easy to provide your own Session class, looks like you'd need to subclass the "SQLAlchemy" object and provide a subclass of SignallingSession, pretty inconvenient.

so just make a quick object that looks like connectable and session.execute at the same time:

```py
class PandasSessionThing:
    def __init__(self, session):
       self.session = session

    def connect(self):
       return self

    # tailor the argument signature here to something pandas
    # agrees with 
    def execute(self, *arg, **kw):
        return self.session.execute(*arg, **kw)


db = SQLAlchemy(app)

pandas.read_sql(statement, PandasSessionThing(db.session))
```

**Comment by pbillante** [comment]
Tried, this and it looks like pandas needs a cursor attribute.  I tried it both passing db.session and pd_data.session.bind and got the same error.

Here's the result:

```
/multitenant-test/venv/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
Traceback (most recent call last):
  File "/multitenant-test/app-bugreport.py", line 60, in <module>
    df = pd.read_sql(pd_data.statement, PandasSessionThing(db.session))
  File "/multitenant-test/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 566, in read_sql
    return pandas_sql.read_query(
  File "/multitenant-test/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 2080, in read_query
    cursor = self.execute(*args)
  File "/multitenant-test/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 2018, in execute
    cur = self.con.cursor()
AttributeError: 'PandasSessionThing' object has no attribute 'cursor'

Process finished with exit code 1
```

**Comment by zzzeek** [comment]
oh yuck, what a crap implementation.   Pandas should really fix that.   do they have some other API that just reads from arbitrary rows ?   This stuff isn't hard from a programming perspective, but pandas likes to have things "out of the box"

**Comment by zzzeek** [comment]
looks like it's looking for "connectable".  try this:

```py
from sqlalchemy.engine import Connectable
class PandasSessionThing(Connectable):
    def __init__(self, session):
       self.session = session

    def connect(self):
       return self

    # tailor the argument signature here to something pandas
    # agrees with 
    def execute(self, *arg, **kw):
        return self.session.execute(*arg, **kw)


db = SQLAlchemy(app)

pandas.read_sql(statement, PandasSessionThing(db.session))
```

**Comment by pbillante** [comment]
Closer.... looks like it needs an execution_options.  See:

```
Traceback (most recent call last):
  File "/multitenant-test/app-bugreport.py", line 61, in <module>
    df = pd.read_sql(pd_data.statement, PandasSessionThing(pd_data.session.bind))
  File "/multitenant-test/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 592, in read_sql
    return pandas_sql.read_query(
  File "/multitenant-test/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1557, in read_query
    result = self.execute(*args)
  File "/multitenant-test/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1402, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
AttributeError: 'PandasSessionThing' object has no attribute 'execution_options'

Process finished with exit code 1
```

**Comment by zzzeek** [comment]
see #7727

**Comment by pbillante** [comment]
```
Traceback (most recent call last):
  File "/multitenant-test/app-bugreport.py", line 69, in <module>
    df = pd.read_sql(pd_data.statement, PandasSessionThing(pd_data.session.bind))
  File "/multitenant-test/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 592, in read_sql
    return pandas_sql.read_query(
  File "/multitenant-test/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1557, in read_query
    result = self.execute(*args)
  File "/multitenant-test/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 1402, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
TypeError: 'dict' object is not callable
```

**Comment by zzzeek** [comment]
oh duh,  I edited my code above, see the new edit

**Comment by pbillante** [comment]
This runs, but I get different results if I pass in PandasSessionThing(pd_data.session.bind) versus PandasSessionThing(pd_data.session)

Using PandasSessionThing(pd_data.session.bind), the do_orm_execute event does NOT trigger, and I get this result set:
```
pandas test
    id   name    info
0    1  Alice   Apple
1    2   Bill  Banana
```

Using PandasSessionThing(pd_data.session), the do_orm_execute event DOES trigger, and I get this result set:
```
pandas test
*** The do_orm_execute event was triggered ***
         Data
0    <Data 1>
1    <Data 2>
```

**Comment by pbillante** [comment]
Right.  What would you recommend to get the result data back into the original query columns?

**Comment by zzzeek** [comment]
oh, well this is more API stuff.  Don't use Data.query, that's flask-sqlalchemy stuff.  you have to query either as ``session.query(Data.id, Data.name, ...)``  or as ``select(Data.id, Data.name, ...)``.  there's not a pre-provided shortcut at the moment to turning "session.query(Data)" into an individual ORM column query so you'd want to spell out the individual attributes.

**Comment by CaselIT** [comment]
I think you can use `pd_data = db.session.query(Data.__table__)` or the v2 equivalent of `select(Data.__table__)`


> This seems usable, although it'd be awfully nice to use the flask-sqlalchemy constructs if there's a way to do that at some point

Query is considered legacy in v2. It will not go anywhere anytime soon, but the preferred usage going forward will be to use `select` instead

**Comment by zzzeek** [comment]
if they use `query(Data.__table__)` that might work, but going forward, im not sure `select(Data.__table__)` will work because that will not be treated as an ORM query.  they'd need to do `select(Data.__table__).select_from(Data)` and that might have some weird effects too.

**Comment by pbillante** [comment]
`query(Data.__table__)` does work and constructs the dataframe correctly for all columns, but `select(Data.__table__)` does not.  It returns no results.

However, even though this approach does trigger the `do_orm_execute` event, it seems that the `orm.with_loader_criteria` filter options are ignored.

I'm using the same technique as in the original [example for public filters](https://docs.sqlalchemy.org/en/14/_modules/examples/extending_query/filter_public.html), and although it does run the `with_loader_criteria` part, it doesn't apply the filter to the pandas result set.  I'm getting all rows in the table regardless of the filter value.

**Comment by zzzeek** [comment]
yes that's what I'd expect because Data.__table__ is not the ORM entity.

please verify it works if you spell out the columns as Data.x, Data.y, Data.q, ... etc.

**Comment by pbillante** [comment]
Verified.  It does work correctly (i.e. `with_loader_criteria` applies the filter) if you spell out the columns as above.  I'll test with joins also shortly.
