### ISSUE TITLE
SET class in lib/sqlalchemy/dialects/mysql/enumerated.py is missing __repr__method

### ISSUE THREAD

**Issue by turntayble81** [sqlalchemy/sqlalchemy#7720]
### Describe the bug

As a result, when auto generating migrations with Alembic, allowable SET values are missing.

### Error

```python
# Should look like this:
sa.Column('target', mysql.SET('_blank', '_self'), server_default=sa.text("'_self'"), nullable=False)

# Looks like this:
sa.Column('target', mysql.SET(length=11), server_default=sa.text("'_self'"), nullable=False)
```

### Versions

- OS:
- Python:
- SQLAlchemy:
- Database:
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by zzzeek** [comment]
thanks for reporting , this is queued but no timeline for us to get to it locally.  should be straightforward for a PR that includes tests in test/dialect/mysql/test_types.py

**Comment by sqla-tester** [comment]
**petit87** has proposed a fix for this issue in the **main** branch:

**7720: Mysql SET column type values are missing when using the repr method** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3636

**Comment by sqla-tester** [comment]
**petit87** has proposed a fix for this issue in the **main** branch:

**Fix repr for MySQL SET, generic Enum** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3636

**Comment by sqla-tester** [comment]
**petit87** has proposed a fix for this issue in the **rel_1_4** branch:

**Fix repr for MySQL SET, generic Enum** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3643
