### ISSUE TITLE
Tuple Argument Yields Ambiguous Error in Compiler

### ISSUE THREAD

**Issue by luciengaitskell** [sqlalchemy/sqlalchemy#7721]
### Describe the bug

Inputting a Python tuple into a function such as `array_agg` yields an ambiguous error in the compiler. This is due to an error occurring when formatting the initial `CompileError` message.

### To Reproduce

```python
func.array_agg(
    (
        "table1.a",
        "table1.b",
        "table1.c",
    )
)
```

### Error

```
value = ('a', 'b', 'c')

    def process(value):
        raise exc.CompileError(
>           "Don't know how to render literal SQL value: %r" % value
        )
E       TypeError: not all arguments converted during string formatting

../python3.9/site-packages/sqlalchemy/sql/sqltypes.py:3216: TypeError
```
### Versions

- OS: macOS 11.6
- Python: 3.9.2
- SQLAlchemy: 1.4.31
- Database: Postgresql 13
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pg8000

**Comment by CaselIT** [comment]
Hi,

thanks for reporting. this is one of the footguns of the `%` format...

**Comment by zzzeek** [comment]
to be clear this is wiht literal binds

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**fix type string formatting calls** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3647

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**fix type string formatting calls** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3648
