### ISSUE TITLE
Issue with PEP484 (mypy) when using 2.0 query syntax

### ISSUE THREAD

**Issue by kripnerl** [sqlalchemy/sqlalchemy#7726]
### Describe the bug

I have found the problem with `mypy` when implementing new `select` syntax, which according to docs implement PEP484 properly. The example bellow basically show that any new 2.0 functionality is not recognized by `mypy`. The old `query` syntax is usually recognized properly even without the `mypy` plugin. Here `mypy` fails even with the plugin.  

Thank you for the advice if I missed something. 

### To Reproduce

```python
application = session.get(Application, some_uuid)

        select_query = (
            select(Application.applicant_id)
            .join(Person, Person.id == Application.applicant_id)
            .where(Application.id == some_uuid)
        )
        (person_id, user_id, mojeid_id) = session.execute(select_query).one()
```

### Error

```
>> mypy app
app/tests/models/test_application.py:77: error: "Session" has no attribute "get"
app/tests/models/test_application.py:80: error: "Join" has no attribute "where"
app/tests/models/test_application.py:80: error: Argument 1 to "Select" has incompatible type "Column[str]"; expected "Optional[Iterable[Union[ColumnElement[Any], FromClause, int]]]"
app/tests/models/test_application.py:81: error: Argument 1 to "join" of "FromClause" has incompatible type "Type[Person]"; expected "FromClause"

``` 

### Versions

- OS: Linux lk-ntb 5.4.0-99-generic 112~18.04.1-Ubuntu SMP Thu Feb 3 14:09:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Python: Python 3.8.5
- SQLAlchemy:   1.4.31
- mypy: 0.931

**Comment by kripnerl** [comment]
Hi @zzzeek, 

thank you for the answer, although I tried what you wrote before, I was not able to recognize that we are already using `sqlalchemy-stubs` with `sqlmypy` plugin. The combination with `sqlalchemy2-stubs` seems to lead to conflicts. When I removed the former from the project I got a wonderful message: 
`Found 168 errors in 23 files (checked 101 source files)`

When going through the errors it seems that it misses mainly using `Mapped` for type declaration. 

Now we have to decide whether to stick with 1.4 syntaxes or rewrite the code in order to satisfy mypy with `sqlalchemy2-stubs`
and rewrite the code when 2.0 is out. 

Honestly, I was quite confused with the message [_SQLAlchemy Mypy Plugin Status Update_](https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html) when digging into the documentation. I was convicted that no plugin is needed when using the new syntax. 

Thank you again, 
Lukas

**Comment by zzzeek** [comment]
> Hi @zzzeek,
> 
> thank you for the answer, although I tried what you wrote before, I was not able to recognize that we are already using `sqlalchemy-stubs` with `sqlmypy` plugin.

those stubs/plugin are not compatible with SQLAlchemy 1.4.


 The combination with `sqlalchemy2-stubs` seems to lead to conflicts. When I removed the former from the project I got a wonderful message: `Found 168 errors in 23 files (checked 101 source files)`

you need to uninstall sqlalchemy-stubs fully, and then install sqlalchemy2-stubs.   There could still be errors as things have changed slightly and also sqlalchemy2-stubs is not as mature as sqlalchemy-stubs.  168 errors in 23 files if you are using strict mode doesn't seem *too* terrible, but this is a transitional period.  once people are on 2.0 this won't really happen anymore.

> 
> When going through the errors it seems that it misses mainly using `Mapped` for type declaration.

the mypy plugin applies Mapped[] in most cases except those which it indicates it can't determine the correct type.   

> 
> Now we have to decide whether to stick with 1.4 syntaxes or rewrite the code in order to satisfy mypy with `sqlalchemy2-stubs` and rewrite the code when 2.0 is out.

if you get your code to pass in 1.4 using the mypy plugin, it will continue to pass under 2.0 using the 2.0 version of the same plugin. the typing syntaxes are not changing.    There are new syntaxes being added which don't require the plugin.   you would probably want to migrate to those slowly but there is no requirement to use them in 2.0.

> 
> Honestly, I was quite confused with the message [_SQLAlchemy Mypy Plugin Status Update_](https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html) when digging into the documentation. I was convicted that no plugin is needed when using the new syntax.

OK, I guess it's the last line that says "SQLAlchemy 2.0 code that makes use of upcoming declarative APIs, which are slightly adjusted from the existing APIs, will enjoy full compliance with pep-484 as well as working correctly within IDEs and other typing tools." was not strongly enough suggestive of future tense (this is what "**will** enjoy full compliance" means).     Also the line "SQLAlchemy 2.0 will allow for construction of declarative mappings in place which will support proper typing directly, without the need for plugins.", I guess "will" here is ambiguous.  I just put up this paragraph like three days ago and it's already being mis-interpreted - I will (that is, in upcoming future today) adjust it now to make it pretty impossible for this misinterpretation to occur.



> 
> Thank you again, Lukas

**Comment by funkindy** [comment]
Hi @zzzeek. I use SA v2.0.13 with plugin mypy plugin. Executing your code snippet (which reflects my issue very well) gives this two errors:

```
temp.local.py:18: error: [SQLAlchemy Mypy plugin] Left hand assignment 'id: "UUID"' not compatible with ORM mapped expression of type "Mapped[_UUID_RETURN]"  [misc]
temp.local.py:24: error: [SQLAlchemy Mypy plugin] Left hand assignment 'id: "UUID"' not compatible with ORM mapped expression of type "Mapped[_UUID_RETURN]"  [misc]
```

am i missing something?

**Comment by zzzeek** [comment]
Hi - 

I have no idea, as mentioned above the mypy plugin is extremely limited for 2.0 and we are looking to remove this plugin ASAP.   issues with mypy plugin on 2.0 I would address by search-and-replacing occurrences of `Column` with `mapped_column`, see https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#step-two-replace-declarative-use-of-schema-column-with-orm-mapped-column
