### ISSUE TITLE
re-add "Connectable" name as a legacy alias for ConnectionEventsTarget

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7727]
pandas hardcodes to Connectable at https://github.com/pandas-dev/pandas/blob/2541e000979555e803de478e212106256ae221f7/pandas/io/sql.py#L747 .   There will be much suffering all around if we drop this name as is the current status in 2.0 main,  just leave it as an alias for ConnectionEventsTarget.

**Comment by CaselIT** [comment]
It seems that pandas 1.4.x is v2 compatible. I'm running it future=True without issues.

In any case their 1.4+ code still uses it https://github.com/pandas-dev/pandas/blob/d2aa44f50f6ac4789d4e351e4e52a53a358da42e/pandas/io/sql.py#L750

**Comment by zzzeek** [comment]
this was done also for openstack in 0cad8827c2
