### ISSUE TITLE
Handle sqlite column names escaped with `[ ]`

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7736]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/7729

<div type='discussions-op-text'>

<sup>Originally posted by **mirrorcoloured** February 18, 2022</sup>
I made a post on SO (https://stackoverflow.com/questions/71152652/unique-constraints-not-detected-in-sqlalchemy-reflection), but copying here for relevance:

I'm attempting to use SQLAlchemy to detect constraints on an existing SQL database by reflection. First, I create some (what I think are) equivalent tables with slightly different syntax:

```
DROP TABLE IF EXISTS a;
DROP TABLE IF EXISTS b;
DROP TABLE IF EXISTS c;

CREATE TABLE IF NOT EXISTS a (
    Id integer PRIMARY KEY,
    Code text UNIQUE
);
CREATE TABLE IF NOT EXISTS b (
    Id integer PRIMARY KEY,
    [Code] text UNIQUE
);
CREATE TABLE IF NOT EXISTS c (
    Id integer PRIMARY KEY,
    Code text
);
GO
CREATE UNIQUE INDEX index_1 ON c (Code);
```

Then I try to reflect the table properties back through SQLAlchemy:

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///example.db'
db = SQLAlchemy(app)
engine = db.get_engine()
db.metadata.reflect(engine)

for table, table_data in db.metadata.tables.items():
    print(table)
    for c in table_data.constraints:
        print("  ", c)
```

And get back:

```
a
   UniqueConstraint(Column('Code', TEXT(), table=<a>))
   PrimaryKeyConstraint(Column('Id', INTEGER(), table=<a>, primary_key=True))
b
   PrimaryKeyConstraint(Column('Id', INTEGER(), table=<b>, primary_key=True))
c
   PrimaryKeyConstraint(Column('Id', INTEGER(), table=<c>, primary_key=True))
```

Why is the unique constraint only detected for table a?

If I inspect the table outside of SQLAlchemy (using [Database.NET](https://fishcodelib.com/Database.htm)), the generated DDL for each of the three tables looks like the format of table c (UNIQUE INDEX outside of CREATE TABLE statement). This led me to believe that any of these three methods were equivalent.

However, SQLAlchemy's behavior is now telling me that they are different, and furthermore it cannot detect any UNIQUE constraints unless defined in the first way. What am I missing here?</div>

The issue is that the column `[Code]` is not handled by the unique reflection regexp.
A simple fix is below, but there may be similar issues in other cases as well

```diff
diff --git a/lib/sqlalchemy/dialects/sqlite/base.py b/lib/sqlalchemy/dialects/sqlite/base.py
index dbb75a9ea..0c10aaad8 100644
--- a/lib/sqlalchemy/dialects/sqlite/base.py
+++ b/lib/sqlalchemy/dialects/sqlite/base.py
@@ -2395,7 +2398,7 @@ class SQLiteDialect(default.DefaultDialect):
         def parse_uqs():
             UNIQUE_PATTERN = r'(?:CONSTRAINT "?(.+?)"? +)?UNIQUE *\((.+?)\)'
             INLINE_UNIQUE_PATTERN = (
-                r'(?:(".+?")|([a-z0-9]+)) ' r"+[a-z0-9_ ]+? +UNIQUE"
+                r'(?:(".+?")|[\[]?([a-z0-9]+))[\]]? +[a-z0-9_ ]+? +UNIQUE'
             )
 
             for match in re.finditer(UNIQUE_PATTERN, table_data, re.I):
```

**Comment by zzzeek** [comment]
hey there -

after looking at this issue I dont think this can be fixed, because the table definition is invalid.    the brackets are not part of the column name because the name is not properly quoted, and the actual name of the column is "Code":

```sql
sqlite> pragma table_info(b);
0|Id|integer|0||1
1|Code|text|0||0
sqlite> SELECT sql FROM sqlite_master WHERE name='b';
CREATE TABLE b (
    Id integer PRIMARY KEY,
    [Code] text UNIQUE
)
```

SQLAlchemy handles a column that is properly named ``[Code]`` without issue.

to make this case "work" we would need to determine if the column name was given without quotes, then reverse-engineer SQLite's rules for silently dropping characters in column names which is the part I'm not currently comfortable with.   

I am going to look right now to see if this maybe can emit a warning for unknown columns located, since we can do that part without guessing and you would then know to fix your table definition.

**Comment by CaselIT** [comment]
I think `[ ]` are escape characters for sqlite for keyword: https://www.sqlite.org/lang_keywords.html

**Comment by zzzeek** [comment]
OK, or backticks, if it's explcitly documented we can support it

**Comment by zzzeek** [comment]
found another bug anyway which is we skipped colnames with an underscore in their name, for this style of unique constraint.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**improve reflection of inline UNIQUE constraints** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3623

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**improve reflection of inline UNIQUE constraints** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3624

**Comment by CaselIT** [comment]
thanks for taking the time mike!
