### ISSUE TITLE
mariadbconnector is no longer allowing cursor.lastrowid on closed cursor

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7738]
as of version 1.0.10 released yesterday

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**updates for mariadb connector 1.0.10** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3600

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**updates for mariadb connector 1.0.10** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3621

**Comment by yacine-harbi** [comment]
The value of lastrowid is now None (in a transaction). I get the correct value with: SELECT LAST_INSERT_ID().
