### ISSUE TITLE
add new API to more detemrinistically place nested CTEs

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7759]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/7756

API will look like the following:

```py
import sqlalchemy as sa
from sqlalchemy import select
from sqlalchemy import true

metadata_obj = sa.MetaData()
contracts = sa.Table(
    "contracts",
    metadata_obj,
    sa.Column("id", sa.String, primary_key=True),
)

invoices = sa.Table(
    "invoices",
    metadata_obj,
    sa.Column("id", sa.String, primary_key=True),
    sa.Column("contract_id", sa.String),
)

contracts_alias = contracts.alias()
cte1 = (
    select(contracts_alias)
    .where(contracts_alias.c.id == contracts.c.id)
    .correlate(contracts)
    .cte()
)
cte2 = (
    select(invoices)
    .join(cte1, invoices.c.contract_id == cte1.c.id)
    .cte()
)

subq = select(cte1, cte2).add_cte(cte1, cte2, nest_here=True)
stmt = select(contracts).outerjoin(subq.lateral(), true())


print(stmt)

```

this will be an API that uses the same "nesting" feature but allows the "nesting" aspect to be set up in the other direction.   if one uses add_cte() exclusively to control nesting it is believed to be more intuitive for some scenarios (going through the nesting tests, I can see how "nesting=True" is easier in other cases).  So this API would be something we can give to folks if otherwise use of "nesting=True" is making things less clear.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Add more nesting features to add_cte()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3628

**Comment by Morikko** [comment]
Great propositions:
1. Accepting many CTEs in `add_cte` is going to be more straight to the point for this usage
2. The parameter `nest_here` will be the single source of truth for the nested level definition

I am just thinking if some edge cases could emerge:
1. Does the parameter `nest_here` has an impact on the CTEs in `add_cte` if the nesting flag is not set ? Like mutating the CTEs or creating a new query (eg query before != after).
2. Also does the order in `add_cte` matters in `subq = select(cte1, cte2).add_cte(cte1, cte2, nest_here=True)` ? (eg if `cte2` is first, then is `cte1` still only at the same level)

Is there a branch where I can try the current changes locally on the repo ?

**Comment by zzzeek** [comment]
you can git checkout the patch by using the download options up at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3628 - click the three dots on the upper right then "download patch" for many options.  one that might work right off is:

    git pull https://gerrit.sqlalchemy.org/sqlalchemy/sqlalchemy refs/changes/28/3628/2

**Comment by Morikko** [comment]
If I reverse `cte1` and `cte2` in the `add_cte` function then I get this:
```sql
WITH cte1 AS
  (SELECT contracts_1.id AS id
   FROM contracts AS contracts_1
   WHERE contracts_1.id = contracts.id)
SELECT contracts.id
FROM contracts
LEFT OUTER JOIN LATERAL
  (WITH cte2 AS
     (SELECT invoices.id AS id,
             invoices.contract_id AS contract_id
      FROM invoices
      JOIN cte1 ON invoices.contract_id = cte1.id) SELECT cte1.id AS id,
                                                          cte2.id AS id_1,
                                                          cte2.contract_id AS contract_id
   FROM cte1,
        cte2) AS anon_1 ON TRUE
```

`cte1` is a top CTE instead of being at the lateral level.

**Comment by zzzeek** [comment]
great catch.  I've updated the gerrit with new logic to detect incoming "nest_here=True" against existing "nest_here=False", and it moves the existing CTE to the new level.   check it out

**Comment by zzzeek** [comment]
i think that's a good behavior.  if they say "nest here", it means, "put it here".  I think that's what people usually want.  if the query is rejected by the compiler, they can fix it.
