### ISSUE TITLE
TextualSelect.add_cte() drops the CTE when compiled

### ISSUE THREAD

**Issue by cansjt** [sqlalchemy/sqlalchemy#7760]
### Describe the bug

When using the `.add_cte()` method on a `TextualSelect` instance, the CTE does not seem to be taken into account when the statement is compiled.

In the example code below, the expected output would be:
```
WITH baz AS (
    SELECT id FROM foo
)
SELECT bar.id, bar.attr FROM bar WHERE bar.foo_id IN (SELECT id FROM baz)
```
Yet the actual output is `SELECT bar.id, bar.attr FROM bar WHERE bar.foo_id IN (SELECT id FROM baz)`, without the CTE, whether compiling the statement with a specific dialect or the default "StrCompiler".

Reading the documentation again and in particular this note:
> Changed in version 1.4: the [`TextualSelect`](https://docs.sqlalchemy.org/en/14/core/selectable.html?highlight=add_cte#sqlalchemy.sql.expression.TextualSelect) class was renamed from `TextAsFrom`, to more correctly suit its role as a SELECT-oriented object and not a FROM clause.

Had me think the `TextAsFrom` is maybe still not behaving exaclty like "full blown" SELECT statement but more like a FROM clause as its old name suggested. From there I managed to find a work around (see code below). But I wonder if this is really working as intended?

### To Reproduce

```python
from sqlalchemy import Column, Integer, MetaData, select, Table, Text, text
from sqlalchemy.dialects.postgresql import dialect as pg_dialect
from sqlalchemy.dialects.mysql import dialect as mysql_dialect

meta = MetaData()
foo = Table('foo', meta, Column('id', Integer))
bar = Table('bar',
            meta,
            Column('id', Integer),
            Column('attr', Text),
            Column('foo_id', Integer)
            )
s1 = select(foo.c.id)
s2 = (text('SELECT bar.id, bar.attr FROM bar WHERE bar.foo_id IN (SELECT id FROM baz)')
      .columns(bar.c.id, bar.c.attr))
s3 = s2.add_cte(s1.cte(name='baz'))
print(s3)
print(str(pg_dialect.statement_compiler(pg_dialect(), s3)))
print(str(mysql_dialect.statement_compiler(mysql_dialect(), s3)))


# Work around:
s4 = select(literal('*')).select_from(s3)
print(s4)
# Does show the CTE
```

### Error

n/a

### Versions

- OS: ubuntu 21.10
- Python: 3.9.7
- SQLAlchemy: 1.4.31
- Database: postgresql, mysql (though I am not sure this matters, unless the dialect does not support CTE)
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

### Additional context

Thanks for the hard and enduring work on this great framework!

**Comment by zzzeek** [comment]
not surprisingly I've been working on CTEs all morning anyway for different issues.  This was just never added as when we did add_cte(), we had missed a lot of constructs that suddenly got this method.  I'm still being too lazy to add a test that searches for all the "add_cte()" methods to make sure they all work, but we can get this one working and as a bonus our test suite happened to notice it needed some other fixes to work with DML updates also.   should be good thanks for reporting.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**support add_cte() for TextualSelect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3629

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**support add_cte() for TextualSelect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3630

**Comment by cansjt** [comment]
Thanks!
