### ISSUE TITLE
AssociationProxy is missing typing hints to properly mimic the type it is pointing to

### ISSUE THREAD

**Issue by Sygmei** [sqlalchemy/sqlalchemy#7774]
### Describe the bug

Having this tables defined :
```python
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Parent(Base):
    __tablename__ = "parent"
    id = Column(String, primary_key=True, nullable=False, unique=True)

    children_relationship = relationship("ActionTags", cascade="all,delete,delete-orphan")
    children = association_proxy("children_relationship", "id")


class Children(Base):
    __tablename__ = "children"
    id = Column(String, primary_key=True, nullable=False, unique=True)
    parent_id = Column(String, ForeignKey(Parent.id), nullable=False)
```
Whenever we create a new parent and a few children : 
```python
parent1 = Parent("parent1")
session.add(parent1)

child1 = Child("child1", "parent1")
session.add(child1)
child2 = Child("child2", "parent1")
session.add(child2)

session.commit()
```

The `assocation_proxy` field does not have proper type hinting unlike the `relationship` field
```python
import typing

print(isinstance(parent1.children, typing.Collection)) # Shows True
print(isinstance(parent1.children, typing.Sequence)) # Shows False
print(isinstance(parent1.children, typing.List)) # Shows False

print(isinstance(parent1.children_relationship, typing.Collection)) # Shows True
print(isinstance(parent1.children_relationship, typing.Sequence)) # Shows True
print(isinstance(parent1.children_relationship, typing.List)) # Shows True
```

This makes it pretty hard to work with frameworks like Pydantic which relies on this type-hinting : 
```python
from pydantic import BaseModel, Field, validator

class Parent(BaseModel):
    id: str
    children_ids: List[str]

    # We have to use a validator because SQLAlchemy association_proxy does not
    # get recognized as a proper Sequence type :(
    @validator("children_ids", pre=True)
    def children_ids_validator(cls, value) -> Set[str]:
        assert isinstance(value, Collection), "children_ids must be a collection"
        return set(value) # Re-cast into proper Sequence-like type

    class Config:
        orm_mode = True
```

### To Reproduce

```python
See code above
```

### Error

Error shown depends on the validation framework used (such as Pydantic).

### Versions

- OS: Arch Linux
- Python: 3.10.2
- SQLAlchemy: 1.4.31
- Database: PostgreSQL 14
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2-binary

**Comment by zzzeek** [comment]
It's not clear if the issue you're describing is in terms of using the [SQLAlchemy Mypy Extension](https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html) or not, but without a MyPy plugin, it's not possible for associationproxy to implicitly know the type of attribute that it's proxying at the TYPE_CHECKING level, as it only has string names which require programmatic evaluation.  

as further development on the mypy plugin has ceased, you will need to apply a Mapped[] annotation to an association proxy in all cases.    whether or not associationproxy accommodates `Mapped[]` right now will be resolved as part of #6810, you can use a cast() in the interim:


```py

from sqlalchemy.orm import Mapped

class Parent(Base):
    __tablename__ = "parent"
    id = Column(String, primary_key=True, nullable=False, unique=True)

    children_relationship = relationship("ActionTags", cascade="all,delete,delete-orphan")
    children: Mapped[List["ActionTags"]] = cast(Mapped[List["ActionTags"]], association_proxy("children_relationship", "id"))

```

**Comment by Sygmei** [comment]
@zzzeek thanks for the quick answer !

My issue is not with mypy but rather with Pydantic, using `typing.cast` does not influence the `__instancecheck__` performed later on the `AssociationProxy`

**Comment by zzzeek** [comment]
SQLAlhemy does not implement ``__instancecheck__`` and I dont see how implementing this method would be useful by relationship() or association proxy, nor does it include any Pydantic integration, so I'm not familiar with what functionality you are describing.    If you are using some pydantic/ sqlalchemy integration layer, you'd want to post with that project, because this one is not it.

**Comment by zzzeek** [comment]
oh, unless you are talking about the collections themselves not implementing ABCs. This was abandoned many years ago in #3040 as there were many issues at that time making it unworkable, but it looks like in that issue it had to do with older JSON serialization.     

Here you're looking for AssocaitionList/set/dict to implement the appropriate typing collection.  This will be done as part of #6810 in 2.0.

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**pep484 + abc bases for assocaitionproxy** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3637

**Comment by nettnikl** [comment]
Hey, i'm not if this is the correct ticket to place this, so please tell me if not.

According to https://github.com/sqlalchemy/sqlalchemy/issues/6810, the association_proxy (so probably also the AssociationList) is already fully typed.
But in this case, shouldn't `tags` be successfully validated as a `List[str]` here?
```python
class Item(Base):
    ...
    _tags: Mapped[List["Tag"]] = relationship(secondary=lambda: item_tag_table)
    tags: AssociationProxy[List[str]] = association_proxy(target_collection='_tags', attr='name')
...

class ItemBase(BaseModel):
    ...
    tags: List[str]
...

@app.get("/item/{id}", response_model=schemas.Item)
def get_item(id: int, session: Session = Depends(get_session)):
    return session.query(models.Item).get(id)
```

```
pydantic.error_wrappers.ValidationError: 2 validation errors for Item
response -> tags
  value is not a valid list (type=type_error.list)
```

**Comment by zzzeek** [comment]
hi -

there's no context here , I dont see what ItemBase is or any of that.   

if you can create a real issue with a self-contained test case preferably not using pydantic (if the issue only reproduces with pydantic, report the bug to pydantic first), I would have some idea what we're doing. thanks

**Comment by Snort-dissatisfied741** [comment]
> Hey, i'm not if this is the correct ticket to place this, so please tell me if not.
> 
> According to [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810), the association_proxy (so probably also the AssociationList) is already fully typed. But in this case, shouldn't `tags` be successfully validated as a `List[str]` here?
> 
> class Item(Base):
>     ...
>     _tags: Mapped[List["Tag"]] = relationship(secondary=lambda: item_tag_table)
>     tags: AssociationProxy[List[str]] = association_proxy(target_collection='_tags', attr='name')
> ...
> 
> class ItemBase(BaseModel):
>     ...
>     tags: List[str]
> ...
> 
> @app.get("/item/{id}", response_model=schemas.ItemBase)
> def get_item(id: int, session: Session = Depends(get_session)):
>     return session.query(models.Item).get(id)
> ```
> pydantic.error_wrappers.ValidationError: 2 validation errors for Item
> response -> tags
>   value is not a valid list (type=type_error.list)
> ```
> 
> * OS: Arch Linux
> * Python: 3.10.10
> * SQLAlchemy: 2.0.9
> * Database: SQLite





https://pythoner.space/questions/tips-for-effectively-utilizing-type-hints-in-python
