### ISSUE TITLE
add create_constraint kwarg to enum repr

### ISSUE THREAD

**Issue by sz3lbi** [sqlalchemy/sqlalchemy#7789]
**Describe the bug**

As I use the SQLite database and it does not have the `Enum` type, I wanted to use the `create_constraint` property for my `Enum`.
I add it like: `status = Column(SQLAlchemyEnum(ExampleEnum, create_constraint=True), nullable=False)` and after running the automatic revision generation, it gets ignored in the process and it results in a column of `Enum` type but without the property mentioned: `sa.Column('status', sa.Enum('first', 'second', name='exampleenum'), nullable=False),`

When I add the `create_constraint=True` by myself to to revision, the database table generates as expected.

**Expected behavior**

The `create_constraint` property present in the `Enum` in the generated revision.

**To Reproduce**
Please try to provide a [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) example, with the migration script and/or the SQLAlchemy tables or models involved.
See also [Reporting Bugs](https://www.sqlalchemy.org/participate.html#bugs) on the website.

MRE repository: https://github.com/sz3lbi/alembic_enum_constraint_bug

```py
from enum import Enum, auto

from sqlalchemy.sql.schema import Column
from sqlalchemy.sql.sqltypes import Enum as SQLAlchemyEnum, Integer

from app.db import Base

class ExampleEnum(Enum):
    first = auto()
    second = auto()

class Test(Base):
    __tablename__ = "test"

    id = Column(Integer, primary_key=True)
    status = Column(SQLAlchemyEnum(ExampleEnum, create_constraint=True), nullable=False)

```

Migration script:
```python
"""Initial Migration

Revision ID: 5c5f574e8985
Revises: 
Create Date: 2022-03-03 21:20:04.585431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5f574e8985'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('first', 'second', name='exampleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###

```

**Error**

There is no error in the terminal.

**Versions.**
 - OS: Windows 10
 - Python: 3.10.2
 - Alembic: 1.7.6
 - SQLAlchemy: 1.4.31
 - Database: SQLite
 - DBAPI: aiosqlite

**Comment by zzzeek** [comment]
same as #7720

**Comment by zzzeek** [comment]
patch , needs test similar to #7720 

```diff
diff --git a/lib/sqlalchemy/sql/sqltypes.py b/lib/sqlalchemy/sql/sqltypes.py
index 69cb858e50..4d81d1c02a 100644
--- a/lib/sqlalchemy/sql/sqltypes.py
+++ b/lib/sqlalchemy/sql/sqltypes.py
@@ -1672,7 +1672,7 @@ class Enum(Emulated, String, SchemaType):
     def __repr__(self):
         return util.generic_repr(
             self,
-            additional_kw=[("native_enum", True)],
+            additional_kw=[("native_enum", True), ("create_constraint", False)],
             to_inspect=[Enum, SchemaType],
         )
```

**Comment by sqla-tester** [comment]
**petit87** has proposed a fix for this issue in the **main** branch:

**Fix repr for MySQL SET, generic Enum** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3636

**Comment by sqla-tester** [comment]
**petit87** has proposed a fix for this issue in the **rel_1_4** branch:

**Fix repr for MySQL SET, generic Enum** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3643
