### ISSUE TITLE
implement a SQLite SAVEPOINT fixture for test suite so that our SQLite savepoint recipe is tested

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7795]
right now we skip SQLite for all SAVEPOINT related tasks in particular the ORM test harness tests, and if I naively add the SAVEPOINT events to provisioning, the tests fail.  We should make sure the published SQLite SAVEPOINT recipe works in our own test suite and consider hardening it with .info flags as it seems sensitive to BEGIN being called twice.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**test sqlite w/ savepoint workaround in session fixture test** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3653

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**test sqlite w/ savepoint workaround in session fixture test** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3654
