### ISSUE TITLE
attrs slots=True breaks Imperative Table example

### ISSUE THREAD

**Issue by TomGoBravo** [sqlalchemy/sqlalchemy#7802]
### Describe the bug

I took the example at https://docs.sqlalchemy.org/en/20/orm/declarative_styles.html#example-three-attrs-with-imperative-table and added the attr slots=True to the declaration. sqlalchemy now raises `sqlalchemy.exc.ArgumentError: Mapper mapped class User->user could not assemble any primary key columns for mapped table 'user'`.

### To Reproduce

Run it at https://replit.com/@TomGoBravo/DopeyGlamorousComputergraphics#main.py

```python
import attr
from sqlalchemy.orm import registry, sessionmaker
from sqlalchemy import Table, Column, Integer, String
from sqlalchemy import create_engine
​
mapper_registry = registry()
​
@mapper_registry.mapped
@attr.s(slots=True)
class User:
  __table__ = Table("user", mapper_registry.metadata, Column("id", Integer, primary_key=True), Column("name", String(50)))
  id: int = attr.ib()
  name: str = attr.ib()
  ​
engine = create_engine('sqlite://')
mapper_registry.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()
​
session.add(User(5, 'sam'))
session.add(User(6, 'wei'))
session.commit()
​
print(list(session.query(User).all()))
```

### Error

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    class User:
  File "/home/runner/DopeyGlamorousComputergraphics/venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_api.py", line 860, in mapped
    _as_declarative(self, cls, cls.__dict__)
  File "/home/runner/DopeyGlamorousComputergraphics/venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 126, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/runner/DopeyGlamorousComputergraphics/venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 177, in setup_mapping
    return cfg_cls(registry, cls_, dict_, table, mapper_kw)
  File "/home/runner/DopeyGlamorousComputergraphics/venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 326, in __init__
    self._early_mapping(mapper_kw)
  File "/home/runner/DopeyGlamorousComputergraphics/venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 209, in _early_mapping
    self.map(mapper_kw)
  File "/home/runner/DopeyGlamorousComputergraphics/venv/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 1004, in map
    mapper_cls(self.cls, self.local_table, **self.mapper_args),
  File "<string>", line 2, in __init__
  File "/home/runner/DopeyGlamorousComputergraphics/venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/runner/DopeyGlamorousComputergraphics/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 664, in __init__
    self._configure_pks()
  File "/home/runner/DopeyGlamorousComputergraphics/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1354, in _configure_pks
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapper mapped class User->user could not assemble any primary key columns for mapped table 'user'
``` 

### Versions

- Python: 3.8.12
- SQLAlchemy: 1.4.32
- attrs 21.4.0
- Database: sqlite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by CaselIT** [comment]
Hi,

The issue here seems to be that when using `slot=True` the class is replaced by attrs with a new one that defines the slots.

I'm not sure if it's something sqlalchemy can fix

**Comment by zzzeek** [comment]
SQLAlchemy mapped classes unfortunately do not support slots directly.   They could be supported in theory using custom instrumentation extensions but the complexity of this would likely not be worth it.

**Comment by zzzeek** [comment]
i can add a note.  not sure how to detect it as I dont really know how attrs works.  is it monkeypatching `__slots__` after the fact?

**Comment by TomGoBravo** [comment]
@zzzeek Thank you for adding a note in the docs.

I don't know attrs that well but dug up https://github.com/python-attrs/attrs/commit/7b201eb1999cd3b2d769a209721d12c0085e6eec which led me to https://github.com/python-attrs/attrs/blob/main/src/attr/_make.py#L812-L815 where a new class is made when `slots=True` @Tinche knows attrs internals.

**Comment by TomGoBravo** [comment]
@zzzeek Thank you for adding a note in the docs.

I don't know attrs that well but dug up https://github.com/python-attrs/attrs/commit/7b201eb1999cd3b2d769a209721d12c0085e6eec which led me to https://github.com/python-attrs/attrs/blob/main/src/attr/_make.py#L812-L815 where a new class is made when `slots=True` @Tinche knows attrs internals.

**Comment by Tinche** [comment]
Yeah, if you pass in `slots=True` (the default for `@define`), we essentially create a new class that has the `__slot__` classvar set properly (and then we do some more work to ensure `super()` works, and some other black magic stuff). The end result is that the final class will have `__slots__` set as if you'd written the attribute yourself. Dataclasses do the same in 3.10+ IIRC, but it's not the default.

**Comment by CaselIT** [comment]
> Dataclasses do the same in 3.10+ IIRC, but it's not the default.

It will probably have the same issue, since I think it uses the same strategy as attrs to generate it (since I think it's the only way, since attaching a `__slots__` to an existing class does noting)

**Comment by zzzeek** [comment]
well I dont know what the failure mode for attrs is.  For a normal mapped class, the failure modes for `__slots__` are exactly as expected, and you can in fact use `__slots__` as long as you provide for `__dict__`, works fine as:

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import registry
from sqlalchemy.orm import Session

Base = declarative_base()

reg = registry()


@reg.mapped
class A:
    __tablename__ = "a"

    __slots__ = ("__weakref__", "_sa_instance_state", "__dict__")

    id = Column(Integer, primary_key=True)
    data = Column(String)


e = create_engine("sqlite://", echo=True)
reg.metadata.create_all(e)

a1 = A(id=5, data="asdf")

s = Session(e)
s.add(a1)
s.commit()


a1 = s.scalars(select(A))

```


failure modes are also normal:

```py
@reg.mapped
class A:
    __tablename__ = "a"

    __slots__ = ()

    id = Column(Integer, primary_key=True)
    data = Column(String)
```

produces as expected:

    TypeError: cannot create weak reference to 'A' object

then:

```py
@reg.mapped
class A:
    __tablename__ = "a"

    __slots__ = ("__weakref__", )

    id = Column(Integer, primary_key=True)
    data = Column(String)

```

produces

    AttributeError: 'A' object has no attribute '_sa_instance_state'

```py
@reg.mapped
class A:
    __tablename__ = "a"

    __slots__ = ("__weakref__", "_sa_instance_state")

    id = Column(Integer, primary_key=True)
    data = Column(String)
```

produces:

    AttributeError: 'A' object has no attribute '__dict__'. Did you mean: '__dir__'?

then adding `__dict__`, class is fine.  these error messages are all the normal failure modes one would expect with unpopulated `__slots__` and it's clear what attributes are needed.

so a generalized "raise if `__slots__` is present"  as well as "`__slots__` is not supported" don't seem to be appropriate.     @CaselIT mentioned dataclasses has a similar option but i dont know that we can assume its behavior and potential failure modes will be the same as attrs.

**Comment by zzzeek** [comment]
the issue seems to be that when calling upon `@attr.s(slots=True)`, the `attr.ib()` elements remain attached to the class, which SQLAlchemy then perceives as descriptors that should not be overridden, therefore those attributes aren't mapped.  When`slots=False`,these elements don't seem to be present, therefore the attribute gets mapped.  This seems to be something specific to `__slots__`:

```py
# without slots=True
(Pdb) self.class_.__dict__['id']
*** KeyError: 'id'

# with slots=True
-> if local:
(Pdb) self.class_.__dict__['id']
<member 'id' of 'User' objects>
```   

We can then reach the "normal" `__slots__` failure modes if we tell the mapper to map these attributes in any case, which is not public API, so patch like this to demonstrate the effect:

```diff
diff --git a/lib/sqlalchemy/orm/mapper.py b/lib/sqlalchemy/orm/mapper.py
index 011e7d2efc..f129ddadd8 100644
--- a/lib/sqlalchemy/orm/mapper.py
+++ b/lib/sqlalchemy/orm/mapper.py
@@ -2639,6 +2639,7 @@ class Mapper(
         return result
 
     def _is_userland_descriptor(self, assigned_name, obj):
+        return False
         if isinstance(
             obj,
             (
```

then I get the normal failure modes again, and I can map the class as before by adding the missing slots, somewhat awkwardly since I don't know the correct attr pattern, but:

```py
@mapper_registry.mapped
@attr.s(slots=True)
class User:
    __table__ = Table(
        "user",
        mapper_registry.metadata,
        Column("id", Integer, primary_key=True),
        Column("name", String(50)),
    )
    _sa_instance_state: Any = attr.ib(init=False)
    __dict__: Any = attr.ib(init=False)
    id: int = attr.ib()
    name: str = attr.ib()
```

**Comment by zzzeek** [comment]
specifically, dataclasses, if they use this same pattern for their slots, would not have this problem, because our is_userland_descriptor function recognizes dataclass fields and allows them to be mapped.

**Comment by Tinche** [comment]
> the attr.ib() elements remain attached to the class

Not sure what exactly do you mean by this, but we don't leave anything on the class. What you're seeing is a descriptor generated by Python itself to access that slot attribute, just like any slot class would have.
