### ISSUE TITLE
reduce _is_clone_of depth for memory savings

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7823]
everytime we clone an expression it keeps around `_is_clone_of` as an intermediary, so that we have chains of expressions and columns that are all wasteful.  _is_clone_of and _cloned_set are not consulted in too many places and it's very likely we only need it maintained for the root item, so we can at least flatten these.

```py
import gc

from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm.mapper import configure_mappers
from sqlalchemy.sql.expression import BinaryExpression

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)
    bs = relationship("B")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    a_id = Column(ForeignKey("a.id"))
    data = Column(String)


configure_mappers()
bc = A.bs.property.strategy._simple_lazy_clause[0]

gc.collect()
be = [x for x in gc.get_objects() if isinstance(x, BinaryExpression)]

#breakpoint()
print("binaries: %s" % len(be))
print("binaries: %s" % be)
print("binaries: %s" % [str(x) for x in be])
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**remove intermediary _is_clone_of entries when cloning** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3711

**Comment by zzzeek** [comment]
if 1.4's tests pass we can release as part of 1.4.  there is more SQL cloning stuff going on in versions prior to 2.0.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**remove intermediary _is_clone_of entries when cloning** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3713
