### ISSUE TITLE
Association proxy to hybrid property not working since 1.3

### ISSUE THREAD

**Issue by r-scott** [sqlalchemy/sqlalchemy#7827]
### Describe the bug

I'm trying to update to a newer version of SQLAlchemy but I'm getting a type error when using an association proxy with a potentially recursive hybrid property.  The hybrid property is ultimately used to create an editable numpy masked array although I've removed that (along with other surplus details) from the example below.  Perhaps I'm going about it the wrong way but it was working until the following commit (at least according to a git bisect):

commit 90574aabef36fd59841b7df7d8ac30e2030e9854 (HEAD)
Author: Mike Bayer <mike_mp@zzzcomputing.com>
Date:   Tue Oct 23 19:38:46 2018 -0400

    Create object- and column-oriented versions of AssociationProxyInstance
    
    The :class:`.AssociationProxy` now has standard column comparison operations
    such as :meth:`.ColumnOperators.like` and
    :meth:`.ColumnOperators.startswith` available when the target attribute is a
    plain column - the EXISTS expression that joins to the target table is
    rendered as usual, but the column expression is then use within the WHERE
    criteria of the EXISTS.  Note that this alters the behavior of the
    ``.contains()`` method on the association proxy to make use of
    :meth:`.ColumnOperators.contains` when used on a column-based attribute.
    
    Fixes: #4351
    Change-Id: I310941f4e8f778c200f8144a26a89e5364cd4dfb

### To Reproduce

```python
from sqlalchemy import BigInteger, Column, Float, ForeignKey
from sqlalchemy import SmallInteger, Text, UniqueConstraint
from sqlalchemy import create_engine
from sqlalchemy.orm import relationship, backref, Session
from sqlalchemy.orm.collections import attribute_mapped_collection
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.ext.declarative import declarative_base
#from sqlalchemy.orm import declarative_base
import sqlalchemy

Base = declarative_base()

class XProfile(Base):
    __tablename__ = 'x_profile'

    x_id = Column(BigInteger, primary_key=True)

    array = relationship('XDataArray', collection_class=attribute_mapped_collection('name'))

    data = association_proxy('array','all_values')

class XDataArray(Base):
    __tablename__ = 'x_data_array'
    __table_args__ = (
        UniqueConstraint('x_id', 'name', 'parent_array_id'),
    )

    array_id = Column(BigInteger, primary_key=True)
    x_id = Column(ForeignKey('x_profile.x_id'), nullable=True, index=True)
    name = Column(Text, nullable=False)

    # Need for nested tables
    parent_array_id = Column(ForeignKey('x_data_array.array_id'), index=True)
    child_index = Column(SmallInteger)
    children = relationship('XDataArray', order_by='XDataArray.child_index')

    values = relationship('XDataArrayValue', order_by='XDataArrayValue.index')

    @hybrid_property
    def all_values(self):
        if len(self.children) > 0:
            return [x.all_values for x in self.children]
        return [x.value for x in self.values]


class XDataArrayValue(Base):
    __tablename__ = 'x_data_array_value'

    array_id = Column(ForeignKey('x_data_array.array_id'), primary_key=True, nullable=False, index=True)
    index = Column(SmallInteger, primary_key=True, nullable=False)
    value = Column(Float(53), nullable=True)

e = create_engine("sqlite://", echo=False)
Base.metadata.create_all(e)
s = Session(e)

# Bit of a hack but gets the data in for this minimal case where
# we don't have the back relationships defined.
s.add(XProfile(x_id=1))
s.add(XDataArray(array_id=1,x_id=1,name='x'))
s.add(XDataArray(array_id=2,name='x',parent_array_id=1,child_index=0))
s.add(XDataArray(array_id=3,name='x',parent_array_id=1,child_index=1))
s.add(XDataArrayValue(array_id=2,index=0,value=1))
s.add(XDataArrayValue(array_id=2,index=1,value=2))
s.add(XDataArrayValue(array_id=3,index=0,value=3))
s.add(XDataArrayValue(array_id=3,index=1,value=4))
s.commit()

p = s.query(XProfile).filter_by(x_id=1).one()
print(p.array['x'].all_values)  # ok
print(p.data['x'])  # not ok
```

### Error

minnow$ python3 x.py
[[1.0, 2.0], [3.0, 4.0]]
Traceback (most recent call last):
  File "/tmp/x.py", line 68, in <module>
    print(p.data['x'])  # not ok
  File "/usr/lib/python3.9/site-packages/sqlalchemy/ext/associationproxy.py", line 191, in __get__
    inst = self._as_instance(class_, obj)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/ext/associationproxy.py", line 253, in _as_instance
    inst = AssociationProxyInstance.for_proxy(self, owner, obj)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/ext/associationproxy.py", line 376, in for_proxy
    target_assoc = cls._cls_unwrap_target_assoc_proxy(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/ext/associationproxy.py", line 432, in _cls_unwrap_target_assoc_proxy
    attr = getattr(target_class, value_attr)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/ext/hybrid.py", line 925, in __get__
    return self._expr_comparator(owner)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/ext/hybrid.py", line 1143, in expr_comparator
    comparator(owner),
  File "/usr/lib/python3.9/site-packages/sqlalchemy/ext/hybrid.py", line 1117, in _expr
    return ExprComparator(cls, expr(cls), self)
  File "/tmp/x.py", line 40, in all_values
    if len(self.children) > 0:
TypeError: object of type 'InstrumentedAttribute' has no len()

### Versions

- OS: Multiple
- Python: 3.7, 3.8, 3.9
- SQLAlchemy: Works with 1.2, not with 1.3, 1.4
- Database:  PostgresQL, sqlite
- DBAPI :psycopg, sqlite

**Comment by zzzeek** [comment]
hey there -

the reason one uses a `@hybrid_property` as opposed to `@property` is so that the attribute can also be used as a SQL-producing attribute, when accessed at the class level.  This means that if the hybrid function calls upon any Python functions that aren't directly supported by the SQL expression language, you have to also construct a separate [expression](https://docs.sqlalchemy.org/en/14/orm/extensions/hybrid.html#defining-expression-behavior-distinct-from-attribute-behavior) callable that will produce some kind of SQL element.

so with your test, the hybrid uses the python function `len()`. This prohibits your hybrid from producing a SQL value (this should be the case in 1.2 also):

```py
print(s.query(XDataArray).join(XDataArrayValue).filter(XDataArray.all_values == 'x'))

...

TypeError: object of type 'InstrumentedAttribute' has no len()
```

it looks like "all_values" in a SQL sense is basically the XDataArrayValue.values column, so we can approximate an expression by implementing that:

```py
    @hybrid_property
    def all_values(self):
        if len(self.children) > 0:
            return [x.all_values for x in self.children]
        return [x.value for x in self.values]

    @all_values.expression
    def all_values(cls):
        return XDataArrayValue.value
```

now for a query against the whole thing it makes sense (I understand this might not be the exact meaning of all_values, but the main thing is that it returns something at the class level):

```
print(s.query(XDataArray).join(XDataArrayValue).filter(XDataArray.all_values == 'x'))

SELECT x_data_array.array_id AS x_data_array_array_id, x_data_array.x_id AS x_data_array_x_id, x_data_array.name AS x_data_array_name, x_data_array.parent_array_id AS x_data_array_parent_array_id, x_data_array.child_index AS x_data_array_child_index 
FROM x_data_array JOIN x_data_array_value ON x_data_array.array_id = x_data_array_value.array_id 
WHERE x_data_array_value.value = ?

```

whether or not the hybrid is useful at the class level for SQL expressions, the association proxy change involves that it will access the target attribute as a class-level attribute as part of the routine it now uses in order to figure out how to best represent its contents.  so the attribute has to be able to be accessed if someone says XDataArray.all_values, whereas before your `len()` function was causing it to fail.

with the above change the test you have retrieves the same content at the instance level for both:

```
[[1.0, 2.0], [3.0, 4.0]]
[[1.0, 2.0], [3.0, 4.0]]
```

hope this helps.

**Comment by zzzeek** [comment]
I can likely make a nicer error for this

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**catch unexpected errors when accessing clslevel attribute** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3725

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**catch unexpected errors when accessing clslevel attribute** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3726
