### ISSUE TITLE
primary key reduction logic tripped up by equiv columns not being equivalent in a later selectable of a UNION

### ISSUE THREAD

**Issue by K1DV5** [sqlalchemy/sqlalchemy#7842]
### Describe the bug

I'm trying to create a mapper for a tree structure and the best way I found was using a CTE. I have the relationships in a table and I want to get

1. all children for a given node id
2. the full path to a given node id

And a good way for this would be to have a relationship on a given node mapper to parents (for point 2) and children (for point 1). For that I created a mappers `Node` and `NodeRel` (see below) where `Node.parents` and `Node.children` would return `NodeRel` objects. `NodeRel` has a recursive CTE as its `__table__`. Problem is, `Node.children` returns the correct data but `Node.parents` returns only the immediate parent and not above. On further investigation, selecting a `NodeRel` with a given id returns the same immediate parent, repeated the same number of times as the number of parents. However, running the raw SQL query SA emits returns the correct results.

### To Reproduce

```python
from sqlalchemy import create_engine, Column, Integer, ForeignKey, select, literal, text
from sqlalchemy.orm import declarative_base, Session, relationship

Base = declarative_base()

class Node(Base):
    __tablename__ = 'nodes'

    id = Column(Integer, primary_key=True)
    parent = Column(Integer, ForeignKey('nodes.id'))
    parents = relationship('NodeRel', foreign_keys='NodeRel.id', primaryjoin='NodeRel.id == Node.id')
    children = relationship('NodeRel', foreign_keys='NodeRel.parent', primaryjoin='NodeRel.parent == Node.id')

class NodeRel(Base):
    table = select(
        Node.id,
        Node.parent,
        literal(0).label('depth')).cte(recursive=True)
    __table__ = table.union_all(select(
        Node.id,
        table.c.parent,
        table.c.depth + literal(1),
        ).select_from(Node).join(table, Node.parent == table.c.id))

    def __repr__(self):
        return f'<NodeRel {self.parent} -> {self.id}>'

e = create_engine("sqlite://", echo=False)
Base.metadata.create_all(e)
s = Session(e)

# just a single chain for this test
s.add(Node(id=1))
s.add(Node(id=2, parent=1))
s.add(Node(id=3, parent=2))
s.add(Node(id=4, parent=3))
s.add(Node(id=5, parent=4))
s.add(Node(id=6, parent=5))

q = select(Node).filter_by(id=4)

node = s.execute(q).scalar()

print('These are the correct children')
for child in node.children:
    print(child)
    # <NodeRel 4 -> 5>
    # <NodeRel 4 -> 6>

print('This is just the immediate parent')
for parent in node.parents:
    print(parent)
    # <NodeRel 3 -> 4>

q_rel = select(NodeRel).filter_by(id=4)

print('This is the same rel repeated the number of parents')
for rel in s.execute(q_rel).scalars():
    print(rel)
    # <NodeRel 3 -> 4>
    # <NodeRel 3 -> 4>
    # <NodeRel 3 -> 4>
    # <NodeRel 3 -> 4>

    # expected:
    # <NodeRel 3 -> 4>
    # <NodeRel 2 -> 4>
    # <NodeRel 1 -> 4>
    # <NodeRel None -> 4>


print('These are the results of the raw sql of the above query (correct)')
for rel in s.execute(text(str(q_rel.compile(compile_kwargs={"literal_binds": True})))):
    print(rel)
    # (4, 3, 0)
    # (4, 2, 1)
    # (4, 1, 2)
    # (4, None, 3)
```

### Error

No error, just wrong results. See above.

### Versions

- OS: Windows 10
- Python: 3.10.3
- SQLAlchemy: 1.4.26
- Database: SQLite 3.37.2
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pysqlite

**Comment by zzzeek** [comment]
your mapping requires that the primary key be established to include "id" and "parent" explicitly:

```py
class NodeRel(Base):
    table = select(
        Node.id,
        Node.parent,
        literal(0).label('depth')).cte(recursive=True)
    __table__ = table.union_all(select(
        Node.id,
        table.c.parent,
        table.c.depth + literal(1),
        ).select_from(Node).join(table, Node.parent == table.c.id))

    __mapper_args__ = {
        "primary_key": (__table__.c.id, __table__.c.parent)
    }
    def __repr__(self):
        return f'<NodeRel {self.parent} -> {self.id}>'

```

otherwise, when you ask for "id=4", it gets all rows with "id=4" and as far as the ORM knows, "id" is the only column that's a primary key.

However, the above mapping has a totally separate problem in that the ORM is attempting to "reduce" the columns given for that primary key to columns that are known to have unique values; columns that are equated to each other are assumed to have the same value and are reduced.  So the above "primary_key" argument will be silently truncated back down to the "id" column alone. 

at the moment, the only workaround I have is to patch away the function in question:

```diff
diff --git a/lib/sqlalchemy/orm/mapper.py b/lib/sqlalchemy/orm/mapper.py
index 967c1064ad..7fe7716194 100644
--- a/lib/sqlalchemy/orm/mapper.py
+++ b/lib/sqlalchemy/orm/mapper.py
@@ -1347,6 +1347,7 @@ class Mapper(
                     self._pks_by_table[k.table] = util.OrderedSet()
                 self._pks_by_table[k.table].add(k)
 
+
         # otherwise, see that we got a full PK for the mapped table
         elif (
             self.persist_selectable not in self._pks_by_table
@@ -1379,13 +1380,10 @@ class Mapper(
             # determine primary key from argument or persist_selectable pks -
             # reduce to the minimal set of columns
             if self._primary_key_argument:
-                primary_key = sql_util.reduce_columns(
-                    [
+                primary_key =[
                         self.persist_selectable.corresponding_column(c)
                         for c in self._primary_key_argument
-                    ],
-                    ignore_nonexistent_tables=True,
-                )
+                    ]
             else:
                 primary_key = sql_util.reduce_columns(
                     self._pks_by_table[self.persist_selectable],
```

the the rows are identified as individual primary keys:

```
WITH RECURSIVE anon_1(id, parent, depth) AS 
(SELECT nodes.id AS id, nodes.parent AS parent, ? AS depth 
FROM nodes UNION ALL SELECT nodes.id AS id, anon_1.parent AS parent, anon_1.depth + ? AS anon_2 
FROM nodes JOIN anon_1 ON nodes.parent = anon_1.id)
 SELECT anon_1.id, anon_1.parent, anon_1.depth 
FROM anon_1 
WHERE anon_1.id = ?
2022-03-22 17:16:33,295 INFO sqlalchemy.engine.Engine [generated in 0.00014s] (0, 1, 4)
2022-03-22 17:16:33,295 DEBUG sqlalchemy.engine.Engine Col ('id', 'parent', 'depth')
2022-03-22 17:16:33,295 DEBUG sqlalchemy.engine.Engine Row (4, 3, 0)
2022-03-22 17:16:33,295 DEBUG sqlalchemy.engine.Engine Row (4, 2, 1)
2022-03-22 17:16:33,295 DEBUG sqlalchemy.engine.Engine Row (4, 1, 2)
2022-03-22 17:16:33,295 DEBUG sqlalchemy.engine.Engine Row (4, None, 3)
<NodeRel 3 -> 4>
<NodeRel 2 -> 4>
<NodeRel 1 -> 4>
<NodeRel None -> 4>

```

**Comment by zzzeek** [comment]
it's because Node.parent is a foreign key to Node.id, so the ORM assumes these will always be equal.  it doesnt see that there's a UNION in there redefining the value of the column down below.  

So you can work around this by using a name-only column that isn't related to "parent" like this:

```py
class NodeRel(Base):
    table = select(
        Node.id,
        column("parent"), #Node.parent,
        literal(0).label('depth')).cte(recursive=True)
    __table__ = table.union_all(select(
        Node.id,
        table.c.parent,
        table.c.depth + literal(1),
        ).select_from(Node).join(table, Node.parent == table.c.id))

    __mapper_args__ = {
        "primary_key": (__table__.c.id, __table__.c.parent)
    }
    def __repr__(self):
        return f'<NodeRel {self.parent} -> {self.id}>'

```

then it sees both cols as uniquely part of the PK.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**trust user PK argument as given; don't reduce** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3730

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**trust user PK argument as given; don't reduce** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3731

**Comment by zzzeek** [comment]
going to see if we can remove that "reduction" logic for the case of user-defined PK.   This should be safe for 1.4, there's a slight chance it might change the structure of an existing mapper PK definition that is badly defined but such a mapping should still function.

**Comment by K1DV5** [comment]
> it's because Node.parent is a foreign key to Node.id, so the ORM assumes these will always be equal. it doesnt see that there's a UNION in there redefining the value of the column down below.
> 
> So you can work around this by using a name-only column that isn't related to "parent" like this:
> 
> ```python
> class NodeRel(Base):
>     table = select(
>         Node.id,
>         column("parent"), #Node.parent,
>         literal(0).label('depth')).cte(recursive=True)
>     __table__ = table.union_all(select(
>         Node.id,
>         table.c.parent,
>         table.c.depth + literal(1),
>         ).select_from(Node).join(table, Node.parent == table.c.id))
> 
>     __mapper_args__ = {
>         "primary_key": (__table__.c.id, __table__.c.parent)
>     }
>     def __repr__(self):
>         return f'<NodeRel {self.parent} -> {self.id}>'
> ```
> 
> then it sees both cols as uniquely part of the PK.

This worked. Thanks! Will close the issue when it is fixed internally.
