### ISSUE TITLE
Connection AWS RDS Database with Tokens and rotating Password

### ISSUE THREAD

**Issue by packhack** [sqlalchemy/sqlalchemy#7850]
### Describe the use case

Hi,

i want to use a AWS RDS Database with rotating Passwords and keep the connection pool alive after the PW Change.

Currently i give the connection string on the initial connection but later connects fail because of the changing password.

### Databases / Backends / Drivers targeted

- AWS RDS
- PostgreSQL

### Example Use

export RDSHOST="aurorapg-ssl.cluster-XXXXXXXXXXX.us-west-2.rds.amazonaws.com"
export PGPASSWORD="$(aws rds generate-db-auth-token --hostname $RDSHOST --port 5432 --region us-west-2 --username iamuser)"

connectString = postgresql+psycopg2://$DBHOST:$PGPASSWORD

### Additional context

https://aws.amazon.com/de/premiumsupport/knowledge-center/rds-postgresql-connect-using-iam/

**Comment by CaselIT** [comment]
Hi,

This is documented at https://docs.sqlalchemy.org/en/14/core/engines.html#generating-dynamic-authentication-tokens

It has been asked multiple times, so searching the issues or discussion will find additional details.
