### ISSUE TITLE
even clearer logging language for autocommit

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7853]
1. the engine-level "isolation_level='AUTOCOMMIT'" parameter is not detected when logging that this is autocommit
2. the BEGIN (implicit) should include messaging as well.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**more autocommit messaging** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3734

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**more autocommit messaging** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3735
