### ISSUE TITLE
Converting table from "with schema" metadata to "without schema" metadata does not work on foreign keys

### ISSUE THREAD

**Issue by tmijieux** [sqlalchemy/sqlalchemy#7860]
### Describe the bug

I'm trying to convert a set of tables (along with their foreign keys) from their original metadata that have a schema defined on it, to a different metadata that does not ("i.e its schema is `None` ") (see the reproduction code below) . 

I expect to have any reference to the schema removed from the table and its constraint using the following snippet:
```python
meta = MetaData()
def referred_schema_fn(table, to_schema, constraint, referred_schema):
    #explicitely selecting 'None' here
    return None
table.to_metadata(meta, schema=None, referred_schema_fn=referred_schema_fn)
```
but in the end the reference to the original schema remains in the foreign keys. (the schema can be succesfully replaced if we chose anything other than `None` in the return value of `reffered_schema_fn` but it does not work with `None`.)

The reason i'm trying to do this is rather complex, there may be another way to get to do what I want but i still think the behavior I expected here can legitimately be expected. 

Technically i want to use the metadata for a alembic migration script and my database organisation is a little elaborated.
I have a multi-tenant application where one metadata have its tables replicated in multiple schemas (one for each tenants) and an other metadata that holds table common to all tenants, but is referred by the tenant specific tables, so i'm trying to work around all of this.

 The issue i currently have is that the autogeneration of alembic always recreate foreign keys because it detects a difference between the metadata and the reflected metadata(the foreign keys schema is different everytime).
 The workaround i'm currently thinking of but not tried yet is to let alembic connect to the mariadb backend without selecting the "database"(i.e without specifying a default schema) and that would maybe give me a different results... 

==================================

Foreign keys are copied here
https://github.com/sqlalchemy/sqlalchemy/blob/59308fd60fd8f7750205063134df4b944d12704b/lib/sqlalchemy/sql/schema.py#L1163-L1178

the `_copy` method use `_get_colspec`: 
https://github.com/sqlalchemy/sqlalchemy/blob/59308fd60fd8f7750205063134df4b944d12704b/lib/sqlalchemy/sql/schema.py#L4101-L4114

but the issue with this is that `None` is the default value for the `schema` parameter in `_get_colspec` and thus the code in `_get_colspec` does not consider the `None` value as being explicitely chosing to have no schema rather just that the caller did not specify any parameters:
https://github.com/sqlalchemy/sqlalchemy/blob/59308fd60fd8f7750205063134df4b944d12704b/lib/sqlalchemy/sql/schema.py#L2462-L2480

what i would expect in my case where i return `None` from `reffered_schema_fn` is that the first branch of the `if` to be taken here (with an additional nested branch to handle the `None` value for `schema`). Instead the second branch(or following) is taken and the original schema is retained.

the first way that comes to my mind is to have `RETAIN_SCHEMA` as the default value for `_get_colspec` `schema` parameter here, but that would probably require to rework a large share of the code ... Would that be an option ?

### To Reproduce

```python
import sqlalchemy as sa
from sqlalchemy import (
    Column,
    Integer,
    String,
    ForeignKey,
    MetaData,
)
from sqlalchemy.orm import declarative_base

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(column_0_N_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(schema="myschema", naming_convention=NAMING_CONVENTION)
Base = declarative_base(metadata=metadata)

class TableA(Base):
    __tablename__ = "tableA"
    id = Column(Integer, primary_key=True, autoincrement=True)
    value = Column(String(30))


class TableB(Base):
    __tablename__ = "tableB"
    id = Column(Integer, primary_key=True, autoincrement=True)
    id_table_a = Column(Integer, ForeignKey(TableA.id, ondelete="CASCADE"))
    value = Column(String(30))

def referred_schema_fn(table, to_schema, constraint, referred_schema):
    #explicitely selecting 'None' here
    return None

meta = MetaData(naming_convention=NAMING_CONVENTION)
for t in metadata.tables.values():
    t.to_metadata(meta, schema=None, referred_schema_fn=referred_schema_fn)


for t in meta.tables.values():
    print("t=", repr(t))
    for s in t.foreign_keys:
        print("   s=", s)

    print("\n\n")
```

### Error

The output from my reproduction script :
```
t= Table('tableA', MetaData(), Column('id', Integer(), table=<tableA>, primary_key=True, nullable=False), Column('value', String(length=30), table=<tableA>), schema=None)



t= Table('tableB', MetaData(), Column('id', Integer(), table=<tableB>, primary_key=True, nullable=False), Column('id_table_a', Integer(), ForeignKey('myschema.tableA.id'), table=<tableB>), Column('value', String(length=30), table=<tableB>), schema=None)
   s= ForeignKey('myschema.tableA.id')

``` 
we can see that `myschema` is still referenced by the foreign key in `tableB`

### Versions

- OS: Linux 5.16.14-arch1-1 # 1 SMP PREEMPT Fri, 11 Mar 2022 17:40:36 +0000 x86_64 GNU/Linux
- Python: Python 3.10.2
- SQLAlchemy: SQLAlchemy==1.4.32
- Database: mariadb 10.5.9
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): mysqlclient 2.1.0

### Additional context

alembic==1.7.7
greenlet==1.1.2
Mako==1.2.0
MarkupSafe==2.1.1
mysql==0.0.3
mysqlclient==2.1.0
SQLAlchemy==1.4.32

**Comment by zzzeek** [comment]
looks like None can't work here you would need to return `BLANK_SCHEMA` to actively set the schema to nothing from something.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**support BLANK_SCHEMA, RETAIN_SCHEMA FK schema on copy** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3738

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**support BLANK_SCHEMA, RETAIN_SCHEMA FK schema on copy** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3739

**Comment by zzzeek** [comment]
I did this patch very quickly so if you can click on the link above and take a look, preferably try it out if possible, that would be very helpful.

**Comment by tmijieux** [comment]
> I did this patch very quickly so if you can click on the link above and take a look, preferably try it out if possible, that would be very helpful.

Very fast indeed !! 🚀 💯 
I tried out the patch and it successfully achieved the behavior that I was expecting (both in my reproduction sample and my real use case)

**Comment by zzzeek** [comment]
great. the BLANK_SCHEMA symbol is there for these cases where the schema should be blanked out, "None" is usually regarded as "dont change it", so I kept that as is as several tests were asserting that part of it

**Comment by tmijieux** [comment]
> great. the BLANK_SCHEMA symbol is there for these cases where the schema should be blanked out, "None" is usually regarded as "dont change it", so I kept that as is as several tests were asserting that part of it

Yes i understand that it is a good way to extend the api without modifying the existing surface. good idea 👍
