### ISSUE TITLE
2.0-style column_descriptions not documented at all and also isnt available on DML

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7861]

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**WIP: column_descriptions or equiv for DML, core select** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3741

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**column_descriptions or equiv for DML, core select** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3742
