### ISSUE TITLE
Sphinx documentation improvements

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#7873]
A checklist of sphinx improvement to look into:
- [ ] classmethod seems to rendered in a strange way, like 
![image](https://user-images.githubusercontent.com/16175304/160703927-a8daabfb-902c-47bd-b2a3-1d246188022e.png)
https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.engine.URL.create
- [ ] we may want to find a way of ignoring the overloads, like in the case of create_engine https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine

**Comment by zzzeek** [comment]
I agree the overloads are out of control and dont make the docs any better.  sphinx does not appear to have a way to disable these so i will hack something in zzzeeksphinx

**Comment by zzzeek** [comment]
i did the work on this one because it's quite a bug in sphinx

https://github.com/sphinx-doc/sphinx/issues/10351

**Comment by CaselIT** [comment]
thanks for taking care of it mike!

**Comment by zzzeek** [comment]
lets see how it looks on the site... still building

**Comment by zzzeek** [comment]
looks good

https://docs.sqlalchemy.org/en/20/core/metadata.html?highlight=column#sqlalchemy.schema.Column

https://docs.sqlalchemy.org/en/20/core/metadata.html?highlight=column#sqlalchemy.schema.Column.argument_for

**Comment by CaselIT** [comment]
indeed it does!
