### ISSUE TITLE
regression - executemany "values" mode is not working in 1.4, was this intentional?

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7880]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/7879

```py
import sqlalchemy
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import insert
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class User(Base):
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True)
    name = Column(String)
    fullname= Column(String)

stmt = insert(User).values(
    [
        dict(name="sandy", fullname="Sandy Cheeks"),
        dict(name="squidward", fullname="Squidward Tentacles"),
        dict(name="spongebob", fullname="Spongebob Squarepants"),
    ]
)

engine = create_engine("postgresql://scott:tiger@localhost/test", echo='debug',
    executemany_mode="values"
)
Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)

session = Session(engine)
stmt = sqlalchemy.dialects.postgresql.insert(User.__table__).on_conflict_do_nothing()
session.execute(stmt,     [
        dict(name="sandy", fullname="Sandy Cheeks"),
        dict(name="squidward", fullname="Squidward Tentacles"),
        dict(name="spongebob", fullname="Spongebob Squarepants"),
    ]
)


```

in the pg server logs:

    INSERT INTO "user" (name, fullname) VALUES ('sandy', 'Sandy Cheeks'),('squidward', 'Squidward Tentacles'),('spongebob', 'Spongebob Squarepants') ON CONFLICT DO NOTHING

for 1.3 only.  in 1.4 it sends them individualy

**Comment by zzzeek** [comment]
this is the established behavior from #6581.  I will scale it back a bit to allow DO NOTHING clauses to go through.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**allow executemany values for ON CONFLICT DO NOTHING** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3763

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**allow executemany values for ON CONFLICT DO NOTHING** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3764
