### ISSUE TITLE
Int32 out of range error when using big integers on postgresql

### ISSUE THREAD

**Issue by Apakottur** [sqlalchemy/sqlalchemy#7909]
### Describe the bug

I am unable to use big integer columns with `tuple_`  when querying the DB.

### To Reproduce
The following code is a minimal example:
```python
big_int = 2**31 + 123
session.add(Actor(id=big_int))
await session.commit()

s = select(Actor.id).where(tuple_(Actor.id, Actor.id) == tuple_(big_int, big_int))
await session.execute(s)
```

Attempting to execute the query leads to the error below.

I fixed the issue by using `func.cast(big_int, BigInteger)` explicitely before calling `tuple_`, but I would expect this to be automatic? 

### Error

```sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: 2147483771 (value out of int32 range)```

### Versions

- OS: Ubuntu 22.04
- Python: 3.10.3
- SQLAlchemy: 1.4.34
- Database: Postgres
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): postgresql+asyncpg

### Additional context

Full reproducible gist here:
https://gist.github.com/Apakottur/62e38315949c0e57169cc95616299f22

**Comment by zzzeek** [comment]
we can do it.  propose the approach that we see in e215db01d48c418e1.  though i think this would be a 2.0 thing.

**Comment by CaselIT** [comment]
I wonder if this behaviour is something that's happening only on async pg, or if all drivers that do server side binding on pg behave the same (so pg8000 and psycopg3)

**Comment by zzzeek** [comment]
it's all three of asyncpg, pg8000, psycopg, the ones where we send explicit casts back to the DB.  other DBs dont have an issue (sqlite, mssql, oracle, mariadb).

**Comment by CaselIT** [comment]
> it's all three of asyncpg, pg8000, psycopg, the ones where we send explicit casts back to the DB. other DBs dont have an issue (sqlite, mssql, oracle, mariadb).

Yes, pg with server side binding is very picky regarding the types

**Comment by Apakottur** [comment]
I just checked this issue against the new release (1.4.38) and the crash it still hapenning.
Was the fix not included in the release?

**Comment by zzzeek** [comment]
@Apakottur this fix is tagged for the 2.0 release.   

if you want to work around in 1.4 you can subclass the Integer type and add the method illustrated in the patch.

**Comment by zzzeek** [comment]
oh and you'd need to patch it into the `sqlalchemy.sql.sqltypes._type_map` for it to take effect.

**Comment by Barefoot-Dev** [comment]
Installed the 2.0 beta and can confirm this if fixed. Thanks!
`pip install SQLAlchemy==2.0.0b2`

**Comment by Barefoot-Dev** [comment]
Although now I can't delete anything.. is this still the correct syntax @zzzeek?

```
with engine.connect() as conn:
        conn.execute(
            """
            DELETE FROM member_community_mapping
            WHERE member_id = %s AND community_id = %s;
            """,
            (member_id, community_id),
        )
```

**Comment by CaselIT** [comment]
that's not a supported code in 2.0. Before updating to v2 you need to follow there migration steps https://docs.sqlalchemy.org/en/14/changelog/migration_20.html

**Comment by zzzeek** [comment]
you want to use exec_driver_sql() if you are putting a raw DBAPI string in there. will work on 1.4 also
