### ISSUE TITLE
SimpleUpdateDeleteTest Should Require sane_rowcount

### ISSUE THREAD

**Issue by cancan101** [sqlalchemy/sqlalchemy#7919]
### Describe the bug

The `SimpleUpdateDeleteTest` tests should be marked as requiring `sane_rowcount`. Currently they are not marked as such which means tests will fail if the dialect does not support `rowcount`s.

[From the docs for `supports_sane_rowcount`](https://github.com/sqlalchemy/sqlalchemy/blob/7a336f42704a7de214eff560a5b35e272a8050c5/lib/sqlalchemy/engine/interfaces.py#L712-L715):
>Indicate whether the dialect properly implements rowcount for
      ``UPDATE`` and ``DELETE`` statements.

but then the test checks `rowcount` : https://github.com/sqlalchemy/sqlalchemy/blob/979ea6b21f71605314dc0ac1231dd385eced98c4/lib/sqlalchemy/testing/suite/test_update_delete.py#L47-L52

### To Reproduce

```python
n/a. Use the existing test suite against a new dialect w/o rowcount.
```

### Error

```
__________________________________________________________________________ SimpleUpdateDeleteTest_sqlite+apsw_3_38_1.test_delete ___________________________________________________________________________
Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/3.10.2/envs/apsw-db-api/lib/python3.10/site-packages/sqlalchemy/testing/suite/test_update_delete.py", line 52, in test_delete
    assert r.rowcount == 1
AssertionError
``` 

### Versions

- OS: MacOS
- Python: 3.10.2
- SQLAlchemy: `main`
- Database: sqlite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):custom

**Comment by cancan101** [comment]
Yes, that seems to fix the issues with this test suite.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add sane_rowcount to SimpleUpdateDeleteTest** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3778

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**add sane_rowcount to SimpleUpdateDeleteTest** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3779
