### ISSUE TITLE
Session and SessionTransaction subclassing

### ISSUE THREAD

**Issue by aathan** [sqlalchemy/sqlalchemy#7920]
### Describe the use case

Subclassing Session may require Subclassing SessionTransaction, but the latter is created directly in Session code. Changing the class of SessionTransaction used is therefore cumbersome. This little patch fixes that.

### Databases / Backends / Drivers targeted

N/A

### Example Use

Subclass Session and override _create_transaction(). <--- example use of the associated PR I'm submitting

**Comment by zzzeek** [comment]
as discussed earlier , we dont want SessionTransaction subclasses to be a public pattern.
