### ISSUE TITLE
For MacOS with M1 chipset greenlet is not properly installing as sub-dependency

### ISSUE THREAD

**Issue by Drachenfels** [sqlalchemy/sqlalchemy#7922]
### Describe the bug

If we take a look into master of sqlalchemy it defines following install_requires:

    greenlet != 0.4.17;(platform_machine=='aarch64' or (platform_machine=='ppc64le' or (platform_machine=='x86_64' or (platform_machine=='amd64' or (platform_machine=='AMD64' or (platform_machine=='win32' or platform_machine=='WIN32'))))))
    
Thus because platform_machine is not one of the above, greenlet is never installed. I was told that platform_machine for such macos is `arm64` (I do not have Mac M1 at hand)

This in effect prevents sqlalchemy from running.

Fix is easy by `pip install greenlet` and then everything is back to normal.

### To Reproduce

```python

$ pip install sqlalchemy[asyncio]

$ pip show

    SQLAlchemy==1.4.35

While it should be:

$ pip show

    greenlet==1.1.2
    SQLAlchemy==1.4.35
```

### Error

```
N/A
``` 

### Versions

- OS: MacOS
- Python: Python3.9+
- SQLAlchemy: SQLAlchemy = {version = "^1.4.35", extras = ["asyncio"]}
- Database: Postgres
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): postgresql+asyncpg

**Comment by zzzeek** [comment]
Hey there -

This looks like a duplicate of #7714, however, I am assuming your description of the issue is that you did `pip install sqlalchemy`, not `pip install sqlalchemy[asyncio]`.  The latter should definitely install greenlet in all cases.   Can you clarify that `pip install sqlalchemy[asyncio]` **does** in fact install greenlet?   

as far as `pip install sqlalchemy`, as stated in #7714 we disallow automatic installation of greenlet for platforms where there is no pre-built wheel of greenlet.

**Comment by Drachenfels** [comment]
Hi @zzzeek 

Sorry, my bad, indeed it looks like a duplicate, I actually used poetry for those shenanigans and it seems to be a bug on that side. I only translated it into pip install for purpose of this bug.

**Comment by Drachenfels** [comment]
Maybe it warrants adding to FAQ of sqlalchemy to prevent you from being bothered with duplicated issues. ;-)

**Comment by zzzeek** [comment]
> Maybe it warrants adding to FAQ of sqlalchemy to prevent you from being bothered with duplicated issues. ;-)

I'd much prefer greenlet provide an M1 wheel file.  Anyone who reads the docs for SQLAlchemy asyncio should see this right at the top [here](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#asyncio-platform-installation-notes).  However, doc writing these days is much more difficult as you can't just write docs, you have to add colors and fonts and flashing lights to get people to see things, so maybe will be doing that here.   the FAQ is another such place but we've moved the FAQ down on the doc index and I bet people dont realize we have an FAQ now.    We have a lot of important docs and I am still trying to figure out how to get people to read them.  but when you have 1M downloads a day I think it's unavoidable docs will be missed by some subset of users.

**Comment by zzzeek** [comment]
it's mentioned in the [installation guide](https://docs.sqlalchemy.org/en/14/intro.html#asyncio-support) also.  I'm adding more links / fonts / sections now, but this will be reported again...

**Comment by Drachenfels** [comment]
@zzzeek Honestly I think you did a great job with those changes to docs, it's hard to miss at this stage and the explanation is superb as always.

**Comment by Bobronium** [comment]
@Drachenfels, why did you close it though? The issue is still reproducible on my machine.

> Can you clarify that pip install sqlalchemy[asyncio] does in fact install greenlet?

On my machine, It doesn't.

macOS: 12.4 (`21F79`)
Python: 3.10.1
Chip: Apple M1 Pro (arm64)

**Comment by Bobronium** [comment]
My bad. I just tried it with pip and it worked. 

I was installing it with `poetry add sqlalchemy --extras=asyncio`, sorry, that I haven't mentioned it upfront. 

This doesn't work with `poetry 1.1.13`. I guess, if it correctly installed with pip, It's a poetry issue then?

<details>

```py
$ poetry add sqlalchemy --extras=asyncio
Creating virtualenv al in /Users/bobronium/dev/temp/al/.venv
Using version ^1.4.39 for SQLAlchemy

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing sqlalchemy (1.4.39)
```

```py
$ cat pyproject.toml
[tool.poetry]
name = "al"
version = "0.1.0"
description = ""
authors = ["Bobronium <email@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
SQLAlchemy = {version = "^1.4.39", extras = ["asyncio"]}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by Bobronium** [comment]
It is indeed issue with poetry: https://github.com/python-poetry/poetry/issues/5429

**Comment by CaselIT** [comment]
if it works with pip then it seems to be an issue with poetry.

**Comment by corentingi** [comment]
I found a solution to this problem by adding a conditional dependency only for macOS platforms.
This solution should only be applied when working directly on a MacBook (local environment)
```toml
# Explicit dependency on greenlet for macOS M1 (arm64)
greenlet = { version = "*", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'" }
```

You can then apply this new config with `poetry lock --no-update` and `poetry install`

**Comment by CaselIT** [comment]
@corentingi does installing with the extra dependency not work? with pip you can simply do `pip install sqlalchemy[asyncio]`

**Comment by corentingi** [comment]
@CaselIT it probably works.
In my case specifically, `sqlalchemy` is a dependency of `alembic` and I don't know if there is a way to force it to use `sqlalchemy[asyncio]`.

Do you think in my case I should point to `sqlalchemy[asyncio]` instead of `greenlet`?

**Comment by CaselIT** [comment]
It's likely better.

@zzzeek maybe alembic should include an async extra than depends on the sqlalchemy extra?

**Comment by zzzeek** [comment]
> It's likely better.
> 
> [@zzzeek](https://github.com/zzzeek) maybe alembic should include an async extra than depends on the sqlalchemy extra?

what's wrong with installing alembic + sqlalchemy[asyncio]  ? if you are using sqlalchemy's asyncio features then you are referring to them directly in your source code, so sqlalchemy[asyncio] becomes a dependency
