### ISSUE TITLE
Add python_type property for PostgreSQL UUID column type

### ISSUE THREAD

**Issue by agronholm** [sqlalchemy/sqlalchemy#7943]
### Describe the use case

The UUID column type in the PostgreSQL dialect (`sqlalchemy.dialects.postgresql.UUID`) lacks the `python_type` property which would tell if the column holds objects of type `uuid.UUID` or plain `str`. This is trivially fixable by implementing said `@property` which would look at `self.as_uuid`.

### Databases / Backends / Drivers targeted

PostgreSQL (all drivers)

### Example Use

SQL is irrelevant here.

### Additional context

This is useful for sqlacodegen to determine the correct type annotation for UUID column attributes in data classes.

**Comment by sqla-tester** [comment]
**Alex Grönholm** has proposed a fix for this issue in the **main** branch:

**Implement the `python_type` property for the PostgreSQL UUID column type.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3797

**Comment by sqla-tester** [comment]
**Alex Grönholm** has proposed a fix for this issue in the **rel_1_4** branch:

**Implement the `python_type` property for the PostgreSQL UUID column type.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3800
