### ISSUE TITLE
Docs: Bundle example output does not match code

### ISSUE THREAD

**Issue by DanLipsitt** [sqlalchemy/sqlalchemy#8013]
### Describe the bug

The output shown in the bundle example appears not to match the code. Both the python and sql show `name`, `fullname`, and `email_address`, but the output only has two fields.
https://github.com/sqlalchemy/sqlalchemy/blob/9294ac7fe02eb2f8aad78122eae199192f12ef52/doc/build/orm/queryguide.rst?plain=1#L253-L267

[Rendered version](https://docs.sqlalchemy.org/en/14/orm/queryguide.html#grouping-selected-attributes-with-bundles)
### Versions

- SQLAlchemy: Current (1.4.36) and main branch (rev 9294ac7fe02eb) docs

**Comment by CaselIT** [comment]
Hi,

Not sure I understand what the issue is. The documentation seems correct to me

**Comment by DanLipsitt** [comment]
Oh, I see the print statement now that outputs only name and address. I didn't notice it between the bundle code and the SQL. Wouldn't it be more informative to output all three columns? Otherwise it doesn't seem to make sense to query for them - the result is the same as the Selecting Individual Attributes section above. I agree though that I was wrong and the output is correct.

**Comment by CaselIT** [comment]
I guess we could. Care to create a PR?

**Comment by CaselIT** [comment]
@zzzeek opinions?

**Comment by zzzeek** [comment]
we can add `row.user.fullname`, sure.    These are examples so it already is kind of contrived to use a Bundle here just to print the three columns, so it's illustrating just how to access that data.  but I agree, discarding the one column despite the overwrought-ness of the example might be off putting.

note that queryguide.rst as well as all the tutorial files are run as doctests, so there's no chance the output doesn't match the code.
