### ISSUE TITLE
new flake8-future-annotations == 0.0.5 re-enables type checking in "not TYPE_CHECKING" blocks

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8020]
0.0.5 was released yesterday and the change appears that we have to add # noqa or otherwise to flake8 issues underneath TYPE_CHECKING blocks

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**update for flake8-future-imports 0.0.5** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3840
