### ISSUE TITLE
add support for new oracle thin driver

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8054]
cx_Oracle is being superseded by this new driver:

https://oracle.github.io/python-oracledb/
https://github.com/oracle/python-oracledb

fortunately it has an all new name and all new module, so we can add it as a new dialect and test it concurrently.

we will be testing it in "thin" mode and for starters the dialect can hopefully be a subclass of cx_Oracle, though I can see it might need to be one of those "common base" kinds of things like psycopg2 and psycopg.

there will be a lot of demand for support of this driver so we will need to get this done for 2.0.

**Comment by zzzeek** [comment]
notes from the developers:

>>> I agree with testing Thin mode.
>>> The development tasks I think that are needed are:
>>> - a stub dialect
>>> - update the dead connection error code checking.  Since there isn't always Oracle Client, these error numbers have had to change again.  We did add a 'full_code' attribute to make this easier for you.
>>> - You probably won't want to add code to toggle a call to init_oracle_client() to turn on the 'thick' mode.  I would let applications do this themselves so they can pass any parameters they want to the call.

**Comment by CaselIT** [comment]
Still no async support right?

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add support for the new oracle driver ``oracledb``.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3892
