### ISSUE TITLE
keyed index operations do not work on json columns in sql server 2016

### ISSUE THREAD

**Issue by lukesmurray** [sqlalchemy/sqlalchemy#8061]
### Describe the bug

I am using sql server 2016 and it doesn't support parameters in JSON_VALUE statements [link (arguments > path)](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-value-transact-sql?view=sql-server-2016#arguments) or JSON_QUERY statements [link (arguments > path)](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-query-transact-sql?view=sql-server-2016#arguments).

I believe the current sqlalchemy compiler makes it impossible to express keyed index operations on JSON columns without using parameters.
Given that the docs state that the JSON type supports SQL server 2016 and greater I think passing literals to the keyed index operation should be supported.
I understand that normal strings must be parameterized in order to avoid SQL injection attacks.

For example, given the table

```python
Base = declarative_base()

class MyTable(Base):
    __tablename__ = "my_table"
    id = Column(Integer, primary_key=True)
    data = Column(JSON)
```

A keyed index operation produces a parameterized statement and fails

```python
select(MyTable.data['foo'])
```

```sql
SELECT JSON_QUERY([my_table].data, ?) AS anon_1 
FROM [my_table]
```

Passing a literal does not work either

```python
select(MyTable.data[literal('foo')])
```

```sql
SELECT JSON_QUERY([my_table].data, ?) AS anon_1 
FROM [my_table]
```

When I execute either of these I get the following error.

```
ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The argument 2 of the "JSON_VALUE or JSON_QUERY" must be a string literal. (13610) (SQLExecDirectW)')
```

### To Reproduce

```python
from sqlalchemy import JSON, Column, Integer, create_engine, literal, select
from sqlalchemy.engine import URL
from sqlalchemy.orm import Session, declarative_base

engine = create_engine(
    URL.create(
        "mssql+pyodbc",
        query={
            "odbc_connect": f"DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={{{server}}};DATABASE={{{database}}};UID={{{user}}};PWD={{{pwd}}}"
        },
    )
)

Base = declarative_base()


class MyTable(Base):
    __tablename__ = "my_table"
    id = Column(Integer, primary_key=True)
    data = Column(JSON)


with Session(engine) as session:
    session.scalars(select(MyTable.data["foo"])).all()

with Session(engine) as session:
    session.scalars(select(MyTable.data[literal("foo")])).all()
```

### Error

---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
File /opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1819, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1818     if not evt_handled:
-> 1819         self.dialect.do_execute(
   1820             cursor, statement, parameters, context
   1821         )
   1823 if self._has_events or self.engine._has_events:

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py:732, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    731 def do_execute(self, cursor, statement, parameters, context=None):
--> 732     cursor.execute(statement, parameters)

ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The argument 2 of the "JSON_VALUE or JSON_QUERY" must be a string literal. (13610) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

ProgrammingError                          Traceback (most recent call last)
Input In [18], in <cell line: 1>()
----> 1 session.scalars(select(DBEntity.json_key[literal('foo')]))

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py:1755, in Session.scalars(self, statement, params, execution_options, bind_arguments, **kw)
   1734 def scalars(
   1735     self,
   1736     statement,
   (...)
   1740     **kw
   1741 ):
   1742     """Execute a statement and return the results as scalars.
   1743 
   1744     Usage and parameters are the same as that of
   (...)
   1752 
   1753     """
-> 1755     return self.execute(
   1756         statement,
   1757         params=params,
   1758         execution_options=execution_options,
   1759         bind_arguments=bind_arguments,
   1760         **kw
   1761     ).scalars()

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py:1696, in Session.execute(self, statement, params, execution_options, bind_arguments, _parent_execute_state, _add_event, **kw)
   1694 else:
   1695     conn = self._connection_for_bind(bind)
-> 1696 result = conn._execute_20(statement, params or {}, execution_options)
   1698 if compile_state_cls:
   1699     result = compile_state_cls.orm_setup_cursor_result(
   1700         self,
   1701         statement,
   (...)
   1705         result,
   1706     )

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1631, in Connection._execute_20(self, statement, parameters, execution_options)
   1627     util.raise_(
   1628         exc.ObjectNotExecutableError(statement), replace_context=err
   1629     )
   1630 else:
-> 1631     return meth(self, args_10style, kwargs_10style, execution_options)

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py:325, in ClauseElement._execute_on_connection(self, connection, multiparams, params, execution_options, _force)
    321 def _execute_on_connection(
    322     self, connection, multiparams, params, execution_options, _force=False
    323 ):
    324     if _force or self.supports_execution:
--> 325         return connection._execute_clauseelement(
    326             self, multiparams, params, execution_options
    327         )
    328     else:
    329         raise exc.ObjectNotExecutableError(self)

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1498, in Connection._execute_clauseelement(self, elem, multiparams, params, execution_options)
   1486 compiled_cache = execution_options.get(
   1487     "compiled_cache", self.engine._compiled_cache
   1488 )
   1490 compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
   1491     dialect=dialect,
   1492     compiled_cache=compiled_cache,
   (...)
   1496     linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
   1497 )
-> 1498 ret = self._execute_context(
   1499     dialect,
   1500     dialect.execution_ctx_cls._init_compiled,
   1501     compiled_sql,
   1502     distilled_params,
   1503     execution_options,
   1504     compiled_sql,
   1505     distilled_params,
   1506     elem,
   1507     extracted_params,
   1508     cache_hit=cache_hit,
   1509 )
   1510 if has_events:
   1511     self.dispatch.after_execute(
   1512         self,
   1513         elem,
   (...)
   1517         ret,
   1518     )

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1862, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1859             branched.close()
   1861 except BaseException as e:
-> 1862     self._handle_dbapi_exception(
   1863         e, statement, parameters, cursor, context
   1864     )
   1866 return result

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2043, in Connection._handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   2041     util.raise_(newraise, with_traceback=exc_info[2], from_=e)
   2042 elif should_wrap:
-> 2043     util.raise_(
   2044         sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2045     )
   2046 else:
   2047     util.raise_(exc_info[1], with_traceback=exc_info[2])

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py:207, in raise_(***failed resolving arguments***)
    204     exception.__cause__ = replace_context
    206 try:
--> 207     raise exception
    208 finally:
    209     # credit to
    210     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    211     # as the __traceback__ object creates a cycle
    212     del exception, replace_context, from_, with_traceback

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1819, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1817                 break
   1818     if not evt_handled:
-> 1819         self.dialect.do_execute(
   1820             cursor, statement, parameters, context
   1821         )
   1823 if self._has_events or self.engine._has_events:
   1824     self.dispatch.after_cursor_execute(
   1825         self,
   1826         cursor,
   (...)
   1830         context.executemany,
   1831     )

File /opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py:732, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    731 def do_execute(self, cursor, statement, parameters, context=None):
--> 732     cursor.execute(statement, parameters)

ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The argument 2 of the "JSON_VALUE or JSON_QUERY" must be a string literal. (13610) (SQLExecDirectW)')
[SQL: SELECT JSON_QUERY([knowts_dev_Entity].json_key, ?) AS anon_1 
FROM [knowts_dev_Entity]]
[parameters: ('foo',)]
(Background on this error at: https://sqlalche.me/e/14/f405)

### Versions

- OS:

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Python: 3.8.12
- SQLAlchemy: 1.4.36
- Database:

```
Microsoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64)
	Oct 31 2020 02:43:57
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor)
```

- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pyodbc

**Comment by lukesmurray** [comment]
I understand that solving this may take a minute. For now if there is a user-land extension I could write, such as a custom compiles statement for mssql [JSONIndexType](https://github.com/sqlalchemy/sqlalchemy/blob/21ae13765d7410228672a282fef29fc0e2b3b098/lib/sqlalchemy/dialects/mssql/json.py#L109-L115) that would be tremendously helpful for unblocking me.

**Comment by zzzeek** [comment]
use text("literal") or literal_column('"literal"') which will render it literally.
