### ISSUE TITLE
scalar_subquery in column_property does not apply polymorphic filter to query

### ISSUE THREAD

**Issue by sjhewitt** [sqlalchemy/sqlalchemy#8064]
### Describe the bug

when using a `scalar_subquery` in a `column_property` that `select`s from a polymorphic class, the necessary filters are not applied to the generated query

### To Reproduce

```python
from sqlalchemy import Column, Integer, String, ForeignKey, case, select, func
from sqlalchemy.orm import declarative_base, relationship, column_property


Base = declarative_base()

class Employee(Base):
    __tablename__ = 'employee'
    id = Column(Integer, primary_key=True)
    type = Column(String(20))

    __mapper_args__ = {
        'polymorphic_on':'type',
        'polymorphic_identity':'employee'
    }

class Engineer(Employee):
    __mapper_args__ = {
        'polymorphic_identity':'engineer'
    }


class Company(Base):
    __tablename__ = 'company'
    id = Column(Integer, primary_key=True)

    max_employee_id = column_property(select(func.max(Employee.id)).scalar_subquery())
    max_engineer_id = column_property(select(func.max(Engineer.id)).scalar_subquery())


print(select(Company.max_employee_id))
print(select(Company.max_engineer_id))
```

### Error

generated output:
```
SELECT (SELECT max(employee.id) AS max_1 FROM employee) AS anon_1
SELECT (SELECT max(employee.id) AS max_1 FROM employee) AS anon_1
``` 

expected output:
```
SELECT (SELECT max(employee.id) AS max_1 FROM employee) AS anon_1
SELECT (SELECT max(employee.id) AS max_1 FROM employee WHERE employee.type IN ('engineer')) AS anon_1
``` 

### Versions

- OS: ArchOS
- Python: 3.9.7
- SQLAlchemy: 1.4.32
- Database: postgres
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2

**Comment by zzzeek** [comment]
I unfortunately don't have an expedient fix for that as it would require the full ORM statement compilation to occur in an entirely new way.    I would work around this limitation by applying the IN criteria within the column_property() manually.

**Comment by zzzeek** [comment]
hokay, there's a pretty critical spot involved here and I'm pretty sure I know why it's doing what it's doing, and if i make it not do that, then the example works, which means there's not too much in the way of it working.   So we would have to make sure the "why it's doing that" part is still happening and somehow allow this case to still slip through.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**try to preserve ORM compilation in mapped scalar subquery** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3872

**Comment by sjhewitt** [comment]
Thanks for investigating so quickly! I am not in a rush for a fix as I've just included the polymorphic condition in the column_property where filter for now, and will keep my team aware of the issue in any new code.

**Comment by zzzeek** [comment]
OK the deannotate in question, which I thought was for performance, but it's not, was added in 699146086df8fd8778582a03267f8f28c5c in order to fix #2316.   Clearly, the ORM has been refactored many times since then so the fix there would appear to no longer apply, however, let's look to see exactly what was fixed there and prove that current approaches don't need to remove these annotations.

**Comment by zzzeek** [comment]
Seems to be fine.  The test that's in #2036 is not a good test now as the query it shows doesn't really need the column to be adapted.  Below is an old school mapping that definitely needs the expressions to be adapted, and with the deannotate removed, the adaptation still takes place:

```py
from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import column_property
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import polymorphic_union
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)
    type = Column(String(40), nullable=False)
    x_id = Column(Integer, ForeignKey("x.id"), nullable=False)
    __mapper_args__ = {"polymorphic_on": type}

A.anything = column_property(A.id + 1000)


class B(A):
    __tablename__ = "b"
    account_id = Column(Integer, ForeignKey("a.id"), primary_key=True)
    __mapper_args__ = {"polymorphic_identity": "named"}


person_join = polymorphic_union(
    {"named": A.__table__.join(B.__table__)},
    None,
    "pjoin",
)
A.__mapper__._set_with_polymorphic(("*", person_join))


class X(Base):
    __tablename__ = "x"
    id = Column(Integer, primary_key=True)
    a = relationship("A")


s = Session()


print(s.query(X, A).join("a"))
```

printing:

```
SELECT x.id AS x_id, pjoin.id AS pjoin_id, pjoin.type AS pjoin_type, pjoin.x_id AS pjoin_x_id, pjoin.id + :id_1 AS anon_1, pjoin.account_id AS pjoin_account_id 
FROM x JOIN (SELECT a.id AS id, a.type AS type, a.x_id AS x_id, b.account_id AS account_id 
FROM a JOIN b ON a.id = b.account_id) AS pjoin ON x.id = pjoin.x_id
```

that query doesnt come out like that in earlier versions but they still use adaption and that part is still working.   so....seems like it's fine.   OK!

**Comment by zzzeek** [comment]
OK scratch all of that, the case shown in #2036 is still failing with this change, it seems the test case isn't in our test suite correctly.  will see if we can figure this out

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**remove "deannotate" from column_property expression** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3877

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**add with_loader_criteria() test for #8064 / #9091** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4356
