### ISSUE TITLE
Add a mechanism to customize index reflection

### ISSUE THREAD

**Issue by adrien-berchet** [sqlalchemy/sqlalchemy#8080]
### Describe the use case

In [GeoAlchemy2](https://github.com/geoalchemy/geoalchemy2) we have to deal with spatial indexes. In SQLite dialect, spatial types are handled by the SpatiaLite extension, and SpatiaLite handles spatial indexes using tables, not actual indexes. In this context, spatial indexes reflection needs specific queries. In the current implementation, it is not possible to inject custom code during index reflection as it is possible with events for example.

### Databases / Backends / Drivers targeted

Mainly SQLite with SpatiaLite extension because [GeoAlchemy2](https://github.com/geoalchemy/geoalchemy2) only supports PostgreSQL (in which spatial indexes are handles using regular indexes so it works fine) and SQLite. But supporting other dialects is planned so the same issue might occur for them.

### Example Use

The following query gives the table and column names which have spatial indexes:
```sql
SELECT f_table_name, f_geometry_column
FROM geometry_columns
WHERE CAST(spatial_index_enabled AS BOOL)
ORDER BY f_table_name, f_geometry_column;
```

For a specific column, it is also possible to use the following query:
```sql
SELECT CheckSpatialIndex('MyTable', 'MySpatialColumn');
```
which returns `1` if a spatial index is enabled for this column or `[NULL]` if there is no spatial index for this column.

### Additional context

Currently this issue is handled in `GeoAlchemy2` using the `column_reflect` event, but it does not work if one wants to get all indexes using `sqlalchemy.dialects.sqlite.base.SQLiteDialect.get_indexes()`. This issue come from https://github.com/sqlalchemy/alembic/pull/1036 because Alembic reflects all indexes at once using this method, so the spatial indexes are lost.

**Comment by zzzeek** [comment]
so as mentioned at https://github.com/sqlalchemy/alembic/pull/1036 I'm -1 on extending existing SQLAlchemy reflection methods. These methods return lists of things.   if the extension use case is one of reflecting additional things that aren't in these lists, extension writers should provide that method within their own libraries separately, in this case a function like `get_spatial_indexes()`.   If OTOH a SQLAlchemy reflection method is returning incorrect information (as opposed to incomplete information), then that's just a bug which we'd fix.

The SQL used within reflection as well as the processing used against the results of those queries is **extremely** detailed and specific and is not really "extensible" without rewriting the whole thing, especially indexes which tend to have the most complex query/ loading process of all.  also in 2.0, these queries are being completely rewritten to work in an entirely different way.

Additionally, a "geo spatial" index is not really the same thing as a usual SQL index, so it would be surprising if the get_indexes() method suddenly returned additional records for these new kinds of indexes.

if the use case is limited to alembic autogenerate, as mentioned, [custom comparison functions](https://alembic.sqlalchemy.org/en/latest/api/autogenerate.html#registering-a-comparison-function) should be used; if there's a reason that can't work here, I'd want to address it on the alembic side where we can do "plugins" more easily, as it's abstracted away from the reflection internals.

**Comment by adrien-berchet** [comment]
We can indeed discuss whether spatial indexes should be considered as indexes or not. I am not a DBMS expert but IMO they should. For me they are just indexes applied to a specific data type (we could use the same index type as for integer columns for example, it would just be very inefficient). And for PostGIS, the spatial extension for PostgreSQL, spatial indexes are handled as regular indexes and are thus returned in the index list by SQLAlchemy. That's not the case for SpatiaLite, the spatial extension for SQLite, which handles spatial indexes with tables and triggers (I don't know the technical reasons for this, maybe the relevant index type for spatial data is not provided by SQLite so they need something else). This results in inconsistent behaviors of SQLAlchemy, as these spatial indexes are not returned in the index list in this case. This is my main concern actually, if they were just never returned it could be fine, but inconsistent behaviors can be surprising for users. But maybe it's just a non-standard choice of SpatiaLite, and in that case I agree that it is not supposed to fixed by a non-standard mechanism in SQLAlchemy.

**Comment by zzzeek** [comment]
if these are in fact special tables and triggers on SQLite then they aren't indexes at all.   It's normal for the inspectors of different databases to return different kinds of objects.   

as in all cases the approach here should follow what it is someone needs to do.    Do geoalchemy users want to call inspect(engine).get_indexes() directly and within that list would be entries that are not really "indexes"?   the typical reason I might call get_indexes() is becasue I want to drop them all.  So if I iterate through that list of names and say "DROP INDEX <name>", that works only if every name returned is actually an index that works within that DDL syntax.    Adding a SQLite spatial construct to that list would break code that works that way.    So I think constructs that are treated as "something that's not a regular index" should not be returned by the inspection method that seeks to return "regular indexes".

**Comment by adrien-berchet** [comment]
I get your point. From a DB administrator point of view, I fully agree that these tables are not indexes. But for a users of spatial types, I am pretty sure that they don't care about how these spatial indexes are stored, they are just spatial indexes for them. So it could be confusing for them (and therefore a bit for me too :blush: ). But again, it seems like this is all because of the weird implementation of SpatiaLite, so if it is the only case where 'indexes' are not handled as regular indexes, then I fully agree that SQLAlchemy should not try to fix this.

**Comment by CaselIT** [comment]
I've followed the discussion and while I think something like this may be useful, the maintenance burden is most likely not worh it, since the use cases seem pretty limited

We can probably close this

**Comment by adrien-berchet** [comment]
Ok, thanks!
