### ISSUE TITLE
Call to .label() must be last

### ISSUE THREAD

**Issue by ntb001** [sqlalchemy/sqlalchemy#8084]
### Describe the bug

When adding a ColumnClause to a query, the .label() is broken by subsequent modifications, such as cast().

### To Reproduce

```python
from sqlalchemy import select, null, BigInteger
query = select(null().label("a").cast(BigInteger)).subquery()
query.c.a  # error
query = select(null().cast(BigInteger).label("a")).subquery()
query.c.a  # ok
```

### Error

```
Traceback (most recent call last):
  File "~/.venv/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 1222, in __getattr__
    return self._index[key]
KeyError: 'a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.venv/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 1224, in __getattr__
    util.raise_(AttributeError(key), replace_context=err)
  File "~/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
AttributeError: a
``` 

### Versions

- OS: macOS 11.6.6
- Python: 3.7.12
- SQLAlchemy: 1.4.37
- Database: postgresql
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**propagate proxy_key from WrapsColumnExpression** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3887

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**propagate proxy_key from WrapsColumnExpression** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3888
