### ISSUE TITLE
The order of MySQL CREATE TABLE options are not deterministic

### ISSUE THREAD

**Issue by blaise-io** [sqlalchemy/sqlalchemy#8092]
### Describe the bug

The order of MySQL `CREATE TABLE` options `CHARSET` and `ENGINE` is not deterministic. The table options part of MySQL queries is produced in `sqlalchemy.dialects.mysql.base.MySQLDDLCompiler.post_create_table`.

### To Reproduce

```python
# See also test.dialect.mysql.test_compiler.SQLTest.test_create_table_with_collate
# This test currently accepts two results.
# The test below also reproduces the issue, but you may need to rerun a few times to reproduce since outcome is random.

def test_create_table_engine_first(self):
    t1 = Table(
        "testtable",
        MetaData(),
        Column("id", Integer(), primary_key=True, autoincrement=True),
        mysql_engine="InnoDB",
        mysql_charset="utf8",
        mysql_collate="utf8_icelandic_ci",
    )
    self.assert_compile(
        schema.CreateTable(t1),
        "CREATE TABLE testtable ("
        "id INTEGER NOT NULL AUTO_INCREMENT, "
        "PRIMARY KEY (id))"
        "ENGINE=InnoDB CHARSET=utf8 COLLATE utf8_icelandic_ci",
    )

def test_create_table_charset_first(self):
    t1 = Table(
        "testtable",
        MetaData(),
        Column("id", Integer(), primary_key=True, autoincrement=True),
        mysql_charset="utf8",
        mysql_collate="utf8_unicode_ci",
        mysql_engine="InnoDB",
    )
    self.assert_compile(
        schema.CreateTable(t1),
        "CREATE TABLE testtable ("
        "id INTEGER NOT NULL AUTO_INCREMENT, "
        "PRIMARY KEY (id))"
        "CHARSET=utf8 ENGINE=InnoDB COLLATE utf8_unicode_ci",
    )
```

### Error

–

### Versions

- OS: all
- Python: all
- SQLAlchemy: 1.4.37
- Database: MySQL
- DBAPI: mysqlclient

### Additional context

A potential fix:

```diff
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index b585ea992..1f998ecb3 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -1778,7 +1778,7 @@ class MySQLDDLCompiler(compiler.DDLCompiler):
             "SUBPARTITION_BY",
         ]
 
-        nonpart_options = set(opts).difference(partition_options)
+        nonpart_options = util.OrderedSet(opts).difference(partition_options)
         part_options = set(opts).intersection(partition_options)
 
         for opt in topological.sort(
@@ -1789,6 +1789,7 @@ class MySQLDDLCompiler(compiler.DDLCompiler):
                 ("CHARACTER_SET", "COLLATE"),
             ],
             nonpart_options,
+            deterministic_order=True,
         ):
             arg = opts[opt]
             if opt in _reflection._options_of_type_string:
```

[Fix including tests](https://github.com/sqlalchemy/sqlalchemy/files/8831498/mysql_deterministic_table_opts.diff.txt)

**Comment by zzzeek** [comment]
I would favor a change like this:

```diff
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index e4d89b2dce..877336a1cb 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -1782,6 +1782,7 @@ class MySQLDDLCompiler(compiler.DDLCompiler):
                 ("DEFAULT_CHARSET", "COLLATE"),
                 ("DEFAULT_CHARACTER_SET", "COLLATE"),
                 ("CHARSET", "COLLATE"),
+                ("CHARSET", "ENGINE"),
                 ("CHARACTER_SET", "COLLATE"),
             ],
             nonpart_options,
```

which is the order that MySQL / MariaDB are requiring them ?  is there an error produced ?

**Comment by zzzeek** [comment]
> Hey zzzeek, thanks for your reply!
> 
> There's no error produced. Perhaps this is a new use case.
> 
> I encountered this issue with the SQL that I generate from existing Alembic revisions. In our CI flows, Alembic generates SQL, and if the SQL is different from a previous run, it triggers a review process because we assume that table schema is changed. But the schema is not really changed, it's just some reordering of table options.
> 
> Our Alembic revisions contain many additions and removals for columns, tables and indexes. The only non-deterministic SQL I encountered is in MySQL's table options.
> 
> Your favored solution would work for us, since we only use CHARSET and ENGINE for table options, but it would likely not work for SQLAlchemy/Alembic as a whole since there are 27 different table options in MySQL 8.

OK so at least for alembic, the most common way that people test for schema changes occurring in CI is not to compare the strings, for which there can always be differences if for example SQLAlchemy changes how it renders some DDL, but to use alembic's comparison utility directly with [compare_metadata](https://alembic.sqlalchemy.org/en/latest/api/autogenerate.html#alembic.autogenerate.compare_metadata) .   that would be a lot more portable and is what Alembic uses to generate that SQL in the first place.

**Comment by blaise-io** [comment]
Thanks for the recommendation! I will change the approach we use on our CI. I think this issue can be closed.

**Comment by blaise-io** [comment]
One additional note: considering your profile picture I'd like to share this picture of my cat and me: 

<img width="282" alt="image" src="https://user-images.githubusercontent.com/788368/172007973-eea7a83d-6142-49da-92b4-ee9799471308.png">

**Comment by zzzeek** [comment]
> One additional note: considering your profile picture I'd like to share this picture of my cat and me:
> 
> <img alt="image" width="282" src="https://user-images.githubusercontent.com/788368/172007973-eea7a83d-6142-49da-92b4-ee9799471308.png">

the classic cat pose!  we have four cats here and one of them is a small tux cat like that one.  the cat in my profile pic is sadly no longer with us :(
