### ISSUE TITLE
`union_all` creates invalid SQL in SQLite when used with nested subclauses

### ISSUE THREAD

**Issue by provinzkraut** [sqlalchemy/sqlalchemy#8094]
### Describe the bug

When using `union_all` with an SQLite engine, invalid SQL is generated when one of the subclauses has itself a subclause, such as `LIMIT`.

### To Reproduce

```python
from sqlalchemy import Column, Integer, String, create_engine, select, union_all
from sqlalchemy.orm import Session, aliased, declarative_base

Base = declarative_base()
engine = create_engine("sqlite://", future=True)


class Foo(Base):
    __tablename__ = "foo"
    id = Column(Integer, primary_key=True)
    name = Column(String)


Base.metadata.create_all(engine)

session = Session(engine)

stmt = union_all(
    select(Foo).where(Foo.id == 1).limit(1),
    select(Foo).where(Foo.id == 2),
).subquery()


session.execute(select(aliased(Foo, stmt)))
```

### Error

```
Traceback (most recent call last):
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "UNION": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/***/main.py", line 24, in <module>
    session.execute(select(aliased(Foo, stmt)))
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/***/.cache/pypoetry/virtualenvs/A1rRx-K7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "UNION": syntax error
[SQL: SELECT anon_1.id, anon_1.name 
FROM ((SELECT foo.id AS id, foo.name AS name 
FROM foo 
WHERE foo.id = ?
 LIMIT ? OFFSET ?) UNION ALL SELECT foo.id AS id, foo.name AS name 
FROM foo 
WHERE foo.id = ?) AS anon_1]
[parameters: (1, 1, 0, 2)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### Versions

- OS: Ubuntu
- Python: 3.10.4
- SQLAlchemy: 1.4.37
- Database: SQLite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pysqlite

### Additional context

The cause for the syntax error are the extra parentheses being around the subclauses. If we modify the SQL like so;

```sql
SELECT anon_1.id, anon_1.name
FROM (
    SELECT foo.id AS id, foo.name AS name
    FROM foo
    WHERE foo.id = ?
    LIMIT ? OFFSET ?
UNION ALL
    SELECT foo.id AS id, foo.name AS name
    FROM foo
    WHERE foo.id = ?
) AS anon_1
```

<details>
<summary>original version</summary>

```sql
SELECT anon_1.id, anon_1.name 
FROM (
    (
        SELECT foo.id AS id, foo.name AS name 
        FROM foo 
        WHERE foo.id = ?
        LIMIT ? OFFSET ?
    ) 
UNION ALL 
    SELECT foo.id AS id, foo.name AS name 
    FROM foo 
    WHERE foo.id = ?
) AS anon_1
```
</details>

we now get `LIMIT clause should come after UNION ALL not before`, which is still an error, but at least tells us what the root cause of our problem is.

**Comment by CaselIT** [comment]
Hi,

I don't think this can be fixed. Sqlalchemy us rendering exactly what's requested.
The only change that may be done is the renoval of the parents, but I don't know if it's there for some reason

**Comment by provinzkraut** [comment]
The last error I'm getting wouldn't need to be "fixed" imho. It'd just be nicer if SQLAlchemy would render it without the parentheses so you get an easier-to-debug error from SQLite. 

My thinking would be that SQLAlchemy should render correct syntax, but it doesn't need to prevent you from making "logical" errors within the resulting SQL.

**Comment by zzzeek** [comment]
so it looks like the logic is so that we can distinguish between:

```sql
SELECT foo.id AS id, foo.name AS name
    FROM foo
    WHERE foo.id = ?
UNION ALL
    (SELECT foo.id AS id, foo.name AS name
    FROM foo
    WHERE foo.id = ?
    LIMIT ? OFFSET ?)
```

and


```sql
SELECT foo.id AS id, foo.name AS name
    FROM foo
    WHERE foo.id = ?
UNION ALL
    SELECT foo.id AS id, foo.name AS name
    FROM foo
    WHERE foo.id = ?
LIMIT ? OFFSET ?
```

similarly when using ORDER BY.    This looks to be first implemented by #2528.

SQLite not being able to handle this is a pretty known (and IMHO fairly unreasonable) SQLite limitation.

it looks like SQLite disallows parens entirely so I'm not sure how sqlite discerns between the above two statements.    if we could figure that out, then we'd have a workaround for this.

**Comment by provinzkraut** [comment]
Well SQLite doesn't really discern between the two. The first one is just a syntax error and there is no way to express this in SQLite.

Looking at the SQLite documentation for ["Compound Select Statements"](https://www.sqlite.org/lang_select.html#compound_select_statements), it shows in the diagram that only what are called `select-core` statements are allowed in a compound select and `select-core` does not support `LIMIT` or `OFFSET` [according to this diagram](https://www.sqlite.org/syntax/select-core.html).

(The description for "Compound Select Statements" indicates that "simple SELECT" statements are supported in "Compound Select Statements", but this is contradicted by the diagram this is followed by as well as real world SQLite behaviour)

I'm not sure how this should be handled SQLAlchemy though. It could either render the "wrong correct" query, which would result in SQLite giving a more useful error message but also in a query that wasn't really intended that way, or it could do what it does now; Render the query "properly" but have it result in an error that's not immediately indicative of the root cause of this issue.

**Comment by zzzeek** [comment]
> Well SQLite doesn't really discern between the two. The first one is just a syntax error and there is no way to express this in SQLite.
> 
> Looking at the SQLite documentation for ["Compound Select Statements"](https://www.sqlite.org/lang_select.html#compound_select_statements), it shows in the diagram that only what are called `select-core` statements are allowed in a compound select and `select-core` does not support `LIMIT` or `OFFSET` [according to this diagram](https://www.sqlite.org/syntax/select-core.html).

which would mean....the statement you are trying to run is not supported in SQLite in any case, right?

> 
> I'm not sure how this should be handled SQLAlchemy though. It could either render the "wrong correct" query, which would result in SQLite giving a more useful error message but also in a query that wasn't really intended that way, or it could do what it does now; Render the query "properly" but have it result in an error that's not immediately indicative of the root cause of this issue.

what other error message are you seeking?   like if it doesnt have the parens there's a better message?   For this kind of thing we'd just raise CompileError in the sqlite compiler, however, we don't like to do that because one day SQlite 3.xy will suddenly support the syntax.    

I vote for "unfortunate error message" and call it a day.

**Comment by provinzkraut** [comment]
> which would mean....the statement you are trying to run is not supported in SQLite in any case, right?
That is correct

> what other error message are you seeking? like if it doesnt have the parens there's a better message?
That's my thinking, yes. IMO it would make for a slightly more convenient debugging experience.

I'm not very particular about this though. If there's no straightforward way of implementing it, so be it.
