### ISSUE TITLE
SqlAlchemy release 1.4.37 breaks when querying JSONB columns due to encoding

### ISSUE THREAD

**Issue by ramannanda9** [sqlalchemy/sqlalchemy#8112]
### Describe the bug

The query is failing to execute due to encoding issue since 1.4.37 release.

We are using sqlacodegen for mapping tables to python types.
And encode/databases as async client.

#### Table Schema
```sql
create table if not exists dummy(
    "tags" jsonb not null,
     id SERIAL not null primary key);
```
#### Python code to reproduce
```python

from typing import Any, Dict

from databases import Database
from sqlalchemy import column, select, String, bindparam, Column, Integer
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import declarative_base

Base = declarative_base()
metadata = Base.metadata


class DBClient:
    """
    This class returns a traceable version of encode/databases client.
    """

    def __init__(self, *args, **kwargs):
        """
        You would generally pass in a url string and other options supported by the encode/database client

        :param args: the arguments supported by encode/database.Database
        :param kwargs: the keyword arguments supported by encode/database.Database
        """
        self._db_driver = Database(*args, **kwargs)

    async def get_db_driver(self) -> Database:
        """
        Checks and connects to the database if not connected and then returns the connected instance
        :return: a wrapped Database instance
        """
        if not self._db_driver.is_connected:
            await self._db_driver.connect()
        return self._db_driver

    async def shutdown(self):
        """
        Disconnects the database instance, is called on shutdown event
        """
        if self._db_driver.is_connected:
            await self._db_driver.disconnect()


class Dummy(Base):
    __tablename__ = 'dummy'
    id = Column(Integer, primary_key=True)
    dummy_field = Column(String(length=255), nullable=False)


db_url = 'postgresql://dummy:dummy@db_instance/db_name'

db_client = DBClient(db_url)



async def search_key_value_in_dummy(key: str, value: str) -> Dict[str, Any]:
    tbl = Dummy.__table__
    db_driver = await db_client.get_db_driver()
    col_expr = column("tags", type_=JSONB)
    q = select(tbl.c).where(col_expr[key].astext == bindparam(key, value=value, type_=String))
    return await db_driver.fetch_one(q)


if __name__ == "__main__":
    import asyncio
    asyncio.get_event_loop().run_until_complete(search_key_value_in_dummy('some_key("idx")', 'dummy_value'))
```

### Error

``` bash
Traceback (most recent call last):
  File "/Users/ramandeepsingh/.pyenv/versions/3.9.11/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 3, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ramandeepsingh/dev/model-envelope/registry/dummy.py", line 66, in <module>
    asyncio.get_event_loop().run_until_complete(search_key_value_in_dummy('some_key("idx")', 'dummy_value'))
  File "/Users/ramandeepsingh/.pyenv/versions/3.9.11/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/ramandeepsingh/dev/model-envelope/registry/dummy.py", line 61, in search_key_value_in_dummy
    return await db_driver.fetch_one(q)
  File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/core.py", line 154, in fetch_one
    return await connection.fetch_one(query, values)
  File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/core.py", line 278, in fetch_one
    return await self._connection.fetch_one(built_query)
  File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/backends/postgres.py", line 181, in fetch_one
    query_str, args, result_columns = self._compile(query)
  File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/backends/postgres.py", line 244, in _compile
    compiled_query = compiled.string % mapping
KeyError: 'some_keyA"idx"Z'

``` 

### Versions

- OS: Linux
- Python: 3.9
- SQLAlchemy: 1.4.37
- Database: PostGreSQL 
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): asyncpg

**Comment by zzzeek** [comment]
hi - 

you seem to be using a database library called [databases](https://github.com/encode/databases) which has nothing to do with SQLAlchemy, I suggest reporting an issue with them.

**Comment by ramannanda9** [comment]
Likely stems from [This](https://github.com/sqlalchemy/sqlalchemy/commit/d6ac4ded87f4363399d82219ed08110982325f1f)

**Comment by ramannanda9** [comment]
The issue was with the weird key encoding and not external library issue.

**Comment by zzzeek** [comment]
please provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that uses only SQLAlchemy.     The databases project does not use SQLAlchemy's dialects for statement execution

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**add tests to confirm no issue w/ pg json keys** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3907

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**add tests to confirm no issue w/ pg json keys** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3908

**Comment by zzzeek** [comment]
I mean literally, the code that is failing is *in the databases project*, if you want to be helpful, they are the ones who need it

```
  File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/core.py", line 154, in fetch_one
    return await connection.fetch_one(query, values)
  File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/core.py", line 278, in fetch_one
    return await self._connection.fetch_one(built_query)
  File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/backends/postgres.py", line 181, in fetch_one
    query_str, args, result_columns = self._compile(query)
  File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/backends/postgres.py", line 244, in _compile
    compiled_query = compiled.string % mapping
KeyError: 'some_keyA"idx"Z'

```

**Comment by ramannanda9** [comment]
> I mean literally, the code that is failing is _in the databases project_, if you want to be helpful, they are the ones who need it
> 
> this is not SQLAlchemy
> 
> ```
>   File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/core.py", line 154, in fetch_one
>     return await connection.fetch_one(query, values)
>   File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/core.py", line 278, in fetch_one
>     return await self._connection.fetch_one(built_query)
>   File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/backends/postgres.py", line 181, in fetch_one
>     query_str, args, result_columns = self._compile(query)
>   File "/Users/ramandeepsingh/.pyenv/versions/model_envelope_3_9/lib/python3.9/site-packages/databases/backends/postgres.py", line 244, in _compile
>     compiled_query = compiled.string % mapping
> KeyError: 'some_keyA"idx"Z'
> ```

Thanks, I get that, but it was caused by change in behavior of escaping the bind variable names?

**Comment by zzzeek** [comment]
there's all kinds of things in https://github.com/encode/databases/blob/master/databases/backends/postgres.py that are brittle and could break, including that they are using the pypostgresql dialect which is unmaintained and removed in 2.0, that dialect has not supported any JSON features or anything since we've been doing JSON.    they are also accessing all kinds of private API [here](https://github.com/encode/databases/blob/fbea46d28bda46ba86e940645b456d5ca7f8f5a3/databases/backends/postgres.py#L240) which falls out of the realm of SQLAlchemy's behavioral contract.

**Comment by ramannanda9** [comment]
perfect thanks for pointing these out.

**Comment by zzzeek** [comment]
the change in #8113 will restore the public API part of this to match what we have [in the FAQ](https://docs.sqlalchemy.org/en/14/faq/sqlexpressions.html#how-do-i-render-sql-expressions-as-strings-possibly-with-bound-parameters-inlined) which "Databases" seems to be using, since that was documented, that's a regression .  however they're still going to have to use compiled.escaped_names when they peek into compiled._bind_processors as that's private, that also changed.
