### ISSUE TITLE
published FAQ recipe wont work w/ special chars in bind names unless we output 'escaped' for .params

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8113]
from #8112

given a recipe based on [this faq entry](https://docs.sqlalchemy.org/en/14/faq/sqlexpressions.html#how-do-i-render-sql-expressions-as-strings-possibly-with-bound-parameters-inlined):

```py

from sqlalchemy import bindparam
from sqlalchemy import Column
from sqlalchemy import column
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(String)


key = 'some_key("idx")'
value = 'dummy_value'
q = select([A.__table__]).where(A.data == bindparam('some_key("idx")', value='x'))


d = postgresql.dialect(paramstyle="pyformat")
c = q.compile(dialect=d, compile_kwargs={"render_postcompile": True})
print(c.string % c.params)
```

this worked in 1.3 because that key was not escaped at all.  so if we restore escpaed_params to compiler.params that published recipe will work again, we can add a kw arg to construct_params().

**Comment by zzzeek** [comment]
that is from #8056

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**restore parameter escaping for public methods** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3909

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**restore parameter escaping for public methods** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3910
