### ISSUE TITLE
Deprecation decorators using `_decorate_cls_with_warning()` break `inspect.getmembers()` and access to `__weakref__` 

### ISSUE THREAD

**Issue by bacchuswng** [sqlalchemy/sqlalchemy#8115]
### Describe the bug

Within `sqlalchemy.util.deprecations`, SQLAlchemy uses `_decorate_cls_with_warning()` through `deprecated_cls()` and `deprecated_20_cls()` methods to denote classes that are deprecated, e.g., `sqlalchemy.engine.interfaces.Connectable`.  However, this deprecation decorator appears to incorrectly handle the `__weakref__`descriptor. 

Specifically, `_decorate_cls_with_warning()` will reconstruct the decorated class by:

1. [Taking the current `__dict__` associated with the class](https://github.com/sqlalchemy/sqlalchemy/blob/a08e7350d35f5a839b77cb656ee91b57b94ef4ff/lib/sqlalchemy/util/deprecations.py#L356)
1. [Removing the `__dict__` descriptor instance] (https://github.com/sqlalchemy/sqlalchemy/blob/a08e7350d35f5a839b77cb656ee91b57b94ef4ff/lib/sqlalchemy/util/deprecations.py#L358) from soon-to-be reconstructed class dictionary.
1. [Using `type()` to reconstruct the class (`cls`)](https://github.com/sqlalchemy/sqlalchemy/blob/a08e7350d35f5a839b77cb656ee91b57b94ef4ff/lib/sqlalchemy/util/deprecations.py#L359)
 
However, the code fails to similarly remove `__weakref__` before reconstructing the class, thus causing unexpected issues when, e.g., trying to access `__weakref__` directly or doing introspection on a Connection object via `inspect.getmembers()`.

### To Reproduce

```python
import inspect

import sqlalchemy
from sqlalchemy.engine import Connection

engine = sqlalchemy.create_engine("postgresql://postgres@localhost:5432/postgres")
conn = Connection(engine)

# Both of the following lines will error out
conn.__weakref__
inspect.getmembers(conn)
```

### Error

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    conn.__weakref__
TypeError: descriptor '__weakref__' for 'Connectable' objects doesn't apply to a 'Connection' object
``` 

### Versions

- OS: macOS 12.3.1
- Python: 3.8.13
- SQLAlchemy: 1.4.37
- Database: PostgreSQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2

### Additional context

Simply adding `clsdict.pop("__weakref__", None)` fixes this issue.

I'm happy to submit a PR to fix this and a test, although I'm not sure where to put the test.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**dont transfer __weakref__ to regenerated class** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3914
