### ISSUE TITLE
Views as schema objects that can be created and dropped

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#812]
**Migrated issue, originally created by Anonymous**

I'd like to ask for ability to define views as schema items, and that they be included in metadata.create_all and drop_all.

So i could do something like this:

v = View(name, metadata, selectable) or  
v = View(name, metadata, autoload=True).
and then use v as any other selectable.

I think what's needed would be a visit_view in DDLSchemaGenerator and dropper, but i'm not proficient enough at SQLAlchemy internals to implement this myself.

**Comment by jvanasco** [comment]
When sketching out support for this object, it would make sense to prepare for eventual support of Materialized Views.

* PostgreSQL
  * Create: [links to Alter/Drop/Refresh] https://www.postgresql.org/docs/13/sql-creatematerializedview.html
  * Rules: https://www.postgresql.org/docs/13/rules-materializedviews.html
* Oracle
  * https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_6002.htm
* Microsoft
  * Indexed View - https://docs.microsoft.com/en-us/sql/relational-databases/views/create-indexed-views
  * Materialized View (azure) - https://docs.microsoft.com/en-us/sql/t-sql/statements/create-materialized-view-as-select-transact-sql
  * MySQL/MariaDB - unsupported

**Comment by zzzeek** [comment]
there's no interest / plans to actually do this and the recipes we have seem to be suiting it well enough, so closing.

someone who wants to present and implement in a timely manner a very comprehensive front-to-back, well-tested plan for such a feature should feel free to revisit this.

**Comment by CaselIT** [comment]
We are trying a new discussion category for these kind of issues.
