### ISSUE TITLE
Filtering in async with relationship doesn't work

### ISSUE THREAD

**Issue by 0dminnimda** [sqlalchemy/sqlalchemy#8125]
### Describe the bug

Selection with inload works normally, it loads all the relationship, but if I am also trying to filter this selection, then the relationship for some reason stops loading.

### To Reproduce

```python
import asyncio
from pprint import pprint

from sqlalchemy import Column, ForeignKey, Integer, String
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.future import select
from sqlalchemy.orm import (declarative_base, relationship, selectinload,
                            sessionmaker)

Base = declarative_base()

class Node(Base):
    __tablename__ = "nodes"

    id = Column(Integer, primary_key=True, unique=True)
    parent_id = Column(Integer, ForeignKey('nodes.id'), nullable=True)
    children = relationship("Node")

    name = Column(String)


def serialize(o):
    if isinstance(o, Base):
        return {name: serialize(getattr(o, name))
                for name in dir(o)
                if not name.startswith("_")}
    elif isinstance(o, list):
        return [serialize(i) for i in o]
    return o


async def async_main():
    engine = create_async_engine(
        "sqlite+aiosqlite:///./sqlite.db",
        future=True,
        connect_args={"check_same_thread": False},
    )

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    async_session = sessionmaker(
        bind=engine, expire_on_commit=False, class_=AsyncSession
    )

    root_id = 1
    async with async_session() as session:
        async with session.begin():
            session.add(Node(name="root", children=[
                Node(name="1", children=[Node(name="11"), Node(name="12")]),
                Node(name="2", children=[Node(name="21")]),
                Node(name="3", children=[Node(name="31"), Node(name="32")]),
            ]))

    async with async_session() as session:
        async with session.begin():
            stmt = (select(Node)
                    .options(selectinload(Node.children))
                    # neither of those work
                    # .filter(Node.id == root_id)
                    # .filter_by(id=root_id)
                )
            result = await session.execute(stmt)
            pprint(serialize(result.scalars().first()))


asyncio.run(async_main())
```

### Error

Uncomment one of `filter` or `filter_by`:

```
Traceback (most recent call last):
    ...
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)
sys:1: RuntimeWarning: coroutine 'Connection.cursor' was never awaited
``` 

### Versions

- OS: Windows10
- Python: 3.10.0rc1
- SQLAlchemy: 1.4.34
- Database: sqlite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): aiosqlite

### Additional context

I expect to see the same result both with filtration and without it:

```
{'children': [{'children': [{'children': [],
                             'id': 3,
                             'metadata': MetaData(),
                             'name': '11',
                             'parent_id': 2,
                             'registry': <sqlalchemy.orm.decl_api.registry object at 0x0000017F7F1942E0>},
                            {'children': [],
                             'id': 4,
                             'metadata': MetaData(),
                             'name': '12',
                             'parent_id': 2,
                             'registry': <sqlalchemy.orm.decl_api.registry object at 0x0000017F7F1942E0>}],
               'id': 2,
               'metadata': MetaData(),
               'name': '1',
               'parent_id': 1,
               'registry': <sqlalchemy.orm.decl_api.registry object at 0x0000017F7F1942E0>},
              {'children': [{'children': [],
                             'id': 6,
                             'metadata': MetaData(),
                             'name': '21',
                             'parent_id': 5,
                             'registry': <sqlalchemy.orm.decl_api.registry object at 0x0000017F7F1942E0>}],
               'id': 5,
               'metadata': MetaData(),
               'name': '2',
               'parent_id': 1,
               'registry': <sqlalchemy.orm.decl_api.registry object at 0x0000017F7F1942E0>},
              {'children': [{'children': [],
                             'id': 8,
                             'metadata': MetaData(),
                             'name': '31',
                             'parent_id': 7,
                             'registry': <sqlalchemy.orm.decl_api.registry object at 0x0000017F7F1942E0>},
                            {'children': [],
                             'id': 9,
                             'metadata': MetaData(),
                             'name': '32',
                             'parent_id': 7,
                             'registry': <sqlalchemy.orm.decl_api.registry object at 0x0000017F7F1942E0>}],
               'id': 7,
               'metadata': MetaData(),
               'name': '3',
               'parent_id': 1,
               'registry': <sqlalchemy.orm.decl_api.registry object at 0x0000017F7F1942E0>}],
 'id': 1,
 'metadata': MetaData(),
 'name': 'root',
 'parent_id': None,
 'registry': <sqlalchemy.orm.decl_api.registry object at 0x0000017F7F1942E0>}
```

**Comment by zzzeek** [comment]
hi there -

this is a recursive structure so loading must be applied to each level deep that you wish to load:

```py
        async with session.begin():
            stmt = (select(Node)
                    .options(selectinload(Node.children).selectinload(Node.children).selectinload(Node.children))
                    .filter(Node.id == root_id)
                )
            result = await session.execute(stmt)
```

the reason it works without the filter is because the list of `select(Node)` loads all nodes and immediately loads each of their children.  but when you filter it, only the top level node is loaded; the rest rely on how many levels deep you wish to eagerly load.

**Comment by 0dminnimda** [comment]
Thanks for the responce! Is there any way to load all children in selectoin if you don't know the depth of the recursion?

**Comment by zzzeek** [comment]
there isn't, but interestingly, as you said that I realized that "selectin" loading is probably the one eager loading where such a thing would be theoretically possible, since it naturally stops as collections are empty.  it would also have to detect loops, but that might also resolve naturally as the objects located are already present in the identity map and have loaded collections.  

then i was going to say, OK, that's interesting but it would be a lot of work someday but with 2.0's new options architecture I can make your test case work with a two line hack in selectinload.   that's interesting.    2.0 is hoped to be early betas by the end of the summer at the earliest so things are a long way away, but I can maybe add an **experimental, alpha, not guaranteed to work very well** paramter on selectinload called "auto_recurse" and add that to 2.0.

**Comment by 0dminnimda** [comment]
What will the patch for 1.4 look like? Is it harder to patch this for 1.4 because of new options architecture?

**Comment by zzzeek** [comment]
it would be harder to patch for 1.4 yes.   I think this feature has a lot of other things it could be doing someday, but it depends on if it sees real-world use.  I think the presence of asyncio is what makes this kind of thing more important than it's been previously because people really want eager loading to do a lot now.

**Comment by 0dminnimda** [comment]
For sure asynchronous sessions shine new light on eager loading. Now it have much more uses

**Comment by 0dminnimda** [comment]
For now I create a stack of 100 `selectinload(Node.children)` back to back, and notiched that if I try to query a node with 75 children then it takes a loot of time compared to any other operation ~ hundreads of seconds
I profiled and saw that the hotest functoins are in decending order: `<built-in method _overlapped.GetQueuedCompletionStatus>`, `path_registry.py:324(__init__)` and `traversals.py:159(_gen_cache_key)`  - tens of seconds spent running the function, excluding calls to sub-functions, everything else is only a few seconds

Are there any ways/options to turn to lower the overhead?

I'll also look into querying children of depth 1 or nodes with `parent_id == node.id`, collecting primary children keys and recursively repeating the proccess. Use of the async db may help to make this approach faster

**Comment by CaselIT** [comment]
if you have that depth it's probably better if you look into recursive ctes, that are a lot more optimized for this kind of queries

the slowness you noticed seems like a bug though. couple you post a code snipped of what you mean with this

> For now I create a stack of 100 selectinload(Node.children) back to back

so we may investigate?

**Comment by zzzeek** [comment]
> For now I create a stack of 100 `selectinload(Node.children)` back to back, and notiched that if I try to query a node with 75 children then it takes a loot of time compared to any other operation ~ hundreads of seconds I profiled and saw that the hotest functoins are in decending order: `<built-in method _overlapped.GetQueuedCompletionStatus>`, `path_registry.py:324(__init__)` and `traversals.py:159(_gen_cache_key)` - tens of seconds spent running the function, excluding calls to sub-functions, everything else is only a few seconds

can you be more specific about the node structure?  one node with 75 immediate children should be just two queries.  how many actual SQL queries did it emit?

>

**Comment by CaselIT** [comment]
I think 75 are the levels of the tree, not the children of one node

**Comment by 0dminnimda** [comment]
Yes, 75 is depth of the recursion, so it looks something like this
```
Node1
│
└───Node2
    │
    └───Node3
        │
        └───Node4
            │
            ...
            └───Node75
```

> For now I create a stack of 100 selectinload(Node.children) back to back

The code snippet would be

```python
def stack_selectinload(depth: int) -> Load:
    if depth == 1:
        return selectinload(Node.children)
    elif depth < 1:
        raise ValueError("'depth' should be >= 1")
    return stack_selectinload(depth - 1).selectinload(Node.children)
```

And expectedly the use is such
```python
stmt = select(Node).filter(Node.id == root_id).options(stack_selectinload(100))
result = await session.execute(stmt)
```

**Comment by CaselIT** [comment]
It's not taking me 100s of seconds, but there's definitely something wrong going on. Will open an issue. Thanks for reporting it

**Comment by zzzeek** [comment]
> It's not taking me 100s of seconds, but there's definitely something wrong going on. Will open an issue. Thanks for reporting it

75 levels deep of selectinload is slow?  that's not too surprising, what's the "wrong" part?

**Comment by zzzeek** [comment]
oh fuck

**Comment by CaselIT** [comment]
I still have to look into it better, but the bug seems not on the kind "wrong things are queried" but of the kind "the cache key generation is wrong and we generate the same string over and over and it takes a longer time to create the cache"

**Comment by zzzeek** [comment]
I think, at the moment that would mostly be expected because the 75 levels deep each have a different selectinload option which will create a different cache key. I think we can maybe try to optimize that by creating the path in some different way but that might be a little bit tricky. It would be more expedient at the moment to just not cache statements that are more than like five levels deep since it's more wasteful to cache it than not

**Comment by zzzeek** [comment]
I guess if we add some special logic in the option to cash in a certain way for what's known to be a recursive option and then somehow reconcile that with what we know the initial path to be, I'm not really sure this is kind of tricky.  Like, each query also has an initial path setting that also changes the cache key

**Comment by CaselIT** [comment]
oh so the cache in the case of a loader is not only of the select, but of all the logic that's needed to generate that select? Otherwise the select would not need to keep the path at all.

In any case we seem to keep too much stuff in the cache key, since 1gb to cache 150 loaders seems a bit too much even considering all the information we have here that could influence the cache

**Comment by zzzeek** [comment]
1gb sounds very unfamiliar to me I can't imagine even with 150 loaders what would be in there, i guess the recursiveness, which is an unfamiliar concept to eager loading up until now, is producing some kind of product

**Comment by CaselIT** [comment]
note that I'm not using main. the test was on 1.4.37, so it's not something due to the new option

**Comment by zzzeek** [comment]
yes but you are still generating a recursive selectinload option, its the same thing

**Comment by zzzeek** [comment]
OK so , right now, dont use very deep selectinloads because they dont solve your problem anyway, you dont want to run 75 queries deep.    we will have to further enhance the new "recusrion" thing to take a numeric depth number and then figure out some way to have it use the same cache entry over and over without actually building a long option.

**Comment by zzzeek** [comment]
I think if im reading correctly your code is going to create a bunch of pending change events that you dont want.   You need to write to a standalone list first, *then* use set_committed_value().   if you set_committed_value() with an empty list, that does essentially nothing.  that list is not used in the object's state, it's copied.

```py
def assemble_nodes(in_nodes: List[Node]) -> List[Node]:
    nodes: Dict[int, Tuple[Node, List[Node]]] = {}
    for node in in_nodes:
        nodes[node.id] = (node, [])

    top_ids: Set[int] = set(nodes.keys())
    for node in nodes.values():
        parent = nodes.get(node.parent_id, None)
        if parent is not None:
            top_ids.remove(node.id)
            parent[1].append(node)

    for node, collection in nodes.values():
        set_committed_state(node, "children", collection)

    return [nodes[id] for id in top_ids]


```

**Comment by 0dminnimda** [comment]
I can't find any up-to-date references for `set_committed_state`, was it renamed to `set_committed_value`?

**Comment by CaselIT** [comment]
I think it's a typo in mike snippet, since the description talks of `set_committed_value`.

I've updated the snipped

**Comment by zzzeek** [comment]
i am old
