### ISSUE TITLE
Support `DROP CONSTRAINT IF EXISTS` for Postgres Dialect

### ISSUE THREAD

**Issue by miketheman** [sqlalchemy/sqlalchemy#8141]
### Describe the use case

Recently was using `alembic.op.drop_constraint()` and found that there was no way to implement "IF EXISTS..." behavior, leading to a ProgrammingError as a result if the constraint wasn't there.

`IF EXISTS` support was added to sqlalchemy in https://github.com/sqlalchemy/sqlalchemy/issues/2843 and the notes target Constraints, but that change doesn't appear to have entered the code.

It appears that it was entertained, but not implemented, so there's an opportunity for sqlalchemy to implement the behavior, and then alembic can use it.

### Databases / Backends / Drivers targeted

Postgres, psycopg2

### Example Use

Use case:

```python
alembic.op.drop_constraint("release_files_name_fkey", "release_files", type_="foreignkey")
```

```sql
ALTER TABLE release_files DROP CONSTRAINT IF EXISTS release_files_name_fkey;
```

### Additional context

Depending on whether this is a good idea, the scope could expand to "add constraint if not exists" semantics, or even potentially cover other types like sequences.

https://github.com/sqlalchemy/sqlalchemy/issues/7354
https://github.com/sqlalchemy/alembic/issues/524

I'm happy to take a stab at this, but considering there's been more than a few efforts on this over the years, I wanted to make sure this was inline with the project's scope and direction.

**Comment by zzzeek** [comment]
the patches that were made apply to tables and indexes, weren't implemented for constraints.    we can have IF (NOT) EXISTS added to constraints, though it looks like it needs to be dialect specific as detailed in the matrix at https://github.com/sqlalchemy/sqlalchemy/issues/2843#issuecomment-694990756 .

**Comment by miketheman** [comment]
Thanks, that is what I thought too. I'll work on this soon!

**Comment by miketheman** [comment]
I've gotten a little lost in looking for current examples how how to best write tests and the implementation for a dialect-based feature, so apologies if I've gone down the wrong path.

It appears that the way to accomplish this is to add a new `visit_` method to each dialect's compiler/base, is that right?

I've created a [Draft PR](https://github.com/sqlalchemy/sqlalchemy/pull/8161) for feedback - looking forward to learning more!
