### ISSUE TITLE
default use_setinputsizes=True for SQL Server pyodbc and automate it against fast_executemany

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#8177]
### Describe the use case

The current default `use_setinputsizes=False` causes all parameter values to be sent as `nvarchar`, even if the column is `varchar`. That can trigger index scans (as opposed to index seeks) which degrade performance.

However, `use_setinputsizes=True` and `fast_executemany=True` don't play nicely together ( #6058 ), so the current plan for 2.0 is to have `use_setinputsizes=True` as the default but bypass it on `.executemany()` when `fast_executemany=True`.

### Databases / Backends / Drivers targeted

mssql+pyodbc://

### Example Use

Related discussion:

https://github.com/sqlalchemy/sqlalchemy/discussions/8171

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **main** branch:

**Change setinputsizes behavior for mssql+pyodbc** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3949

**Comment by zzzeek** [comment]
im trying to fix this now but we seem to have an issue with JSON comparisons where our JSON uses NVARCHAR, so comparing a JSON field to a unicode string fails because it casts the unicode string as varchar.

I think I might detect this at a different level to work around this

**Comment by zzzeek** [comment]
hmmm trick in question is being used, String._resolve_for_literal(), OK.   will see where it's going wrong
