### ISSUE TITLE
implement psycopg3-similar Range and Mulltirange types and get them to work for all DB adapters

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8178]
once #7816 merges, build data-holding objects resembling https://github.com/psycopg/psycopg/blob/master/psycopg/psycopg/types/range.py and https://github.com/psycopg/psycopg/blob/master/psycopg/psycopg/types/multirange.py, just the base type, I dont think we need all the specific subtypes.   then remove use of "psycopg" to get at the range types both from our docs and our test suite, document our own vendored version of these two type objects.

we have users e.g. #8175 trying to use ranges with asyncpg which is a reasonable use case.

**Comment by zzzeek** [comment]
I guess we will be making great use of our literal processors for this since we will have to render those strings ourselves within bind_processor().   receiving them back should be fun too....asyncpg seems to have a Range type but not yet a multirange, so if we get a string back we will just regexp it.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement PG ranges/multiranges agnostically** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4026
