### ISSUE TITLE
`with_variant` should require at least a dialect

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8179]
`type.with_variant(other_type) ` is allowed but it's basically a no-op since there is no dialect specified.

I think this could in v2

**Comment by zzzeek** [comment]
if we make the arg signature lke `dialect, *addl_dialects` then it's done, but i just mocked that up and it looks dumb, let's just do a len check

**Comment by CaselIT** [comment]
yes, that's an alternative, but I agree we should just do a len check.

also this is v2 only, since in 1.x a single dialect was accepted, so I don't think we needed the issue, but it should not be an issue

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**require at least one dialect name for variant** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3952
