### ISSUE TITLE
why does AsyncResult not have yield_per()?

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8199]
this is streaming rows and...what if i want it to build 100 ORM objects at a time?   Look into this and see if I thought of this in some other way, I'm not understanding why this method isnt there.  

if there's no reason and it seems like an omission this really should be added with some tests.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**repair yield_per for non-SS dialects and add new options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3963

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**repair yield_per for non-SS dialects and add new options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3964
