### ISSUE TITLE
asyncpg dialect's dollar-number conversion does not use the same "dollar number" for the same-named parameter

### ISSUE THREAD

**Issue by mitchej123** [sqlalchemy/sqlalchemy#8204]
### Describe the bug

SQLAlchemy is making a new position parameter for each usage of a pyformat parameter. This seems to work well in general practice, but when combine with postgres (via asyncpg) and a group by on a JSONB columns this causes a GroupingError to be generated.  The same code (run as sync) works when run using psycopg2 which uses "pyformat".

Example bind params 
```python
bind_params = {  ":bind1": "some_key" }
```

Example Query: 
```sql
SELECT jsonb_column ->> :bind1 
FROM some_table 
GROUP BY jsonb_column ->> :bind1
```
converts to the following when using positional ("format" vs "pyformat")
```sql
SELECT jsonb_column ->> %s -- $1 as seen by the DB
FROM some_table 
GROUP BY jsonb_column ->> %s -- $2 as seen by the DB
-- params = ["some_key", "some_key"]
```

### To Reproduce

```python
from __future__ import annotations

import asyncio
import uuid
from pprint import pprint

import asyncpg
from sqlalchemy import create_engine, text
from sqlalchemy.ext.asyncio import create_async_engine

HOST = "localhost"
USER = "scott"
PASSWORD = "tiger"
DATABASE = "test"


async def run_all():
    await setup_example()
    try:
        await run_sqlalchemy_with_asyncpg()
    except Exception as e:
        print(f"--- SQLAlchemy AsyncPG Example raised an exception: {e}")

    try:
        run_sqlalchemy_with_psycopg2()
    except Exception as e:
        print(f"--- SQLAlchemy PsycoPG2 Example raised an exception: {e}")

    try:
        await run_asyncpg()
    except Exception as e:
        print(f"--- AsyncPG Example raised an exception: {e}")


async def setup_example():
    print("=== Setting up tables")
    asyncpg_connection = await asyncpg.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)
    await asyncpg_connection.execute(
        """
            CREATE TABLE IF NOT EXISTS alarms (
                id serial PRIMARY KEY,
                obj_guid UUID,
                attributes JSONB
            );
        """
    )

    rows = await asyncpg_connection.fetch("SELECT * FROM alarms")

    if len(rows) == 0:
        obj1 = str(uuid.uuid4())

        await asyncpg_connection.executemany(
            """
            INSERT INTO alarms (obj_guid, attributes)
            VALUES ($1, $2);
            """,
            [
                (obj1, '{"severity": "MAJOR"}'),
                (obj1, '{"severity": "MAJOR"}'),
                (obj1, '{"severity": "MAJOR"}'),
                (obj1, '{"severity": "CRITICAL"}'),
            ],
        )


async def run_sqlalchemy_with_asyncpg():
    print("=== Running SQL Alchemy AsyncPG Example")

    engine = create_async_engine(f"postgresql+asyncpg://{USER}:{PASSWORD}@{HOST}/{DATABASE}", echo=True)
    async with engine.connect() as conn:
        await conn.execute(
            text(
                """
                SELECT alarms.attributes ->> :bind1 AS severity
                FROM alarms
                GROUP BY alarms.attributes ->> :bind1 ;
            """
            ),
            dict(bind1="severity"),
        )
    print("+++ SqlAlchemy AsyncPG Example passed")


def run_sqlalchemy_with_psycopg2():
    print("=== Running SQL Alchemy PsycoPG2 Example")
    engine = create_engine(f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}/{DATABASE}", echo=True)
    with engine.connect() as conn:
        conn.execute(
            text(
                """
                SELECT alarms.attributes ->> :bind1 AS severity
                FROM alarms
                GROUP BY alarms.attributes ->> :bind1 ;
            """
            ),
            dict(bind1="severity"),
        )
    print("+++ SqlAlchemy PsycoPG2 Example passed")


async def run_asyncpg():
    print("=== Running AsyncPG Example")
    asyncpg_connection = await asyncpg.connect(host=HOST, user=USER, password=PASSWORD, database=DATABASE)
    query = """
    SELECT alarms.attributes ->> $1 AS severity
    FROM alarms
    GROUP BY alarms.attributes ->> $1;
    """
    print(" ===  Running one bind-param")
    values = await asyncpg_connection.fetch(query, "severity")
    pprint(values)
    query = """
    SELECT alarms.attributes ->> $1 AS severity
    FROM alarms
    GROUP BY alarms.attributes ->> $2;
    """
    print(" +++ one-bind-param succeeded")

    print(" === Running two bind-param")
    values = await asyncpg_connection.fetch(query, ["severity", "severity"])
    pprint(values)
    print(" +++ two-bind-param succeeded")


asyncio.run(run_all())
```

### Error

```python
=== Setting up tables
=== Running SQL Alchemy AsyncPG Example
2022-07-02 15:35:48,788 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2022-07-02 15:35:48,788 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-02 15:35:48,794 INFO sqlalchemy.engine.Engine select current_schema()
2022-07-02 15:35:48,794 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-02 15:35:48,799 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2022-07-02 15:35:48,799 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-07-02 15:35:48,803 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-07-02 15:35:48,803 INFO sqlalchemy.engine.Engine 
                SELECT alarms.attributes ->> %s AS severity
                FROM alarms
                GROUP BY alarms.attributes ->> %s ;
            
2022-07-02 15:35:48,803 INFO sqlalchemy.engine.Engine [generated in 0.00025s] ('severity', 'severity')
2022-07-02 15:35:48,809 INFO sqlalchemy.engine.Engine ROLLBACK
--- SQLAlchemy AsyncPG Example raised an exception: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.GroupingError'>: column "alarms.attributes" must appear in the GROUP BY clause or be used in an aggregate function
[SQL: 
                SELECT alarms.attributes ->> %s AS severity
                FROM alarms
                GROUP BY alarms.attributes ->> %s ;
            ]
[parameters: ('severity', 'severity')]
(Background on this error at: https://sqlalche.me/e/14/f405)
=== Running SQL Alchemy PsycoPG2 Example
2022-07-02 15:35:48,880 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2022-07-02 15:35:48,880 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-07-02 15:35:48,883 INFO sqlalchemy.engine.Engine select current_schema()
2022-07-02 15:35:48,883 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-07-02 15:35:48,886 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2022-07-02 15:35:48,886 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-07-02 15:35:48,890 INFO sqlalchemy.engine.Engine 
                SELECT alarms.attributes ->> %(bind1)s AS severity
                FROM alarms
                GROUP BY alarms.attributes ->> %(bind1)s ;
            
2022-07-02 15:35:48,890 INFO sqlalchemy.engine.Engine [generated in 0.00020s] {'bind1': 'severity'}
+++ SqlAlchemy PsycoPG2 Example passed
=== Running AsyncPG Example
 ===  Running one bind-param
[<Record severity='MAJOR'>, <Record severity='CRITICAL'>]
 +++ one-bind-param succeeded
 === Running two bind-param
--- AsyncPG Example raised an exception: column "alarms.attributes" must appear in the GROUP BY clause or be used in an aggregate function

```

### Versions

- OS: OSX 12.4
- Python: 3.10.2
- SQLAlchemy: 1.4.39
- Database: PostgreSQL 14.4
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): asyncpg 0.25

### Additional context

Other relevant issues I found while tracking this down:

[AsyncConnection.exec_driver_sql with asyncpg not support named parameters sqlalchemy/6452](https://github.com/sqlalchemy/sqlalchemy/issues/6452)

[GroupingError when using bind param on JSONB column asyncpg/885](https://github.com/MagicStack/asyncpg/issues/885) 
Credit to for the inspiration for the example code goes to ugtar on this issue. The source of his issue, similar to mine, is when using `select()` along with `table.c.jsonbcolumn['field'].astext.label('labeled')` 

~~He has a workaround using `sqlalchemy.text('labeled')`on this issue; however it does not seem to work for me, perhaps because I'm also using the column in a join and even when using sqlalchemy.text("alias_name") it still gives the same error.~~ Edit: With some further investigation I realized the column alias was overlapping with one of the columns from a join table (not queried directly); renaming the label did indeed allow his workaround to work.

**Comment by zzzeek** [comment]
OK this is a *very* niche use case, which occurs due to the specific limitation that PostgreSQL requires the GROUP BY to be the identical SQL expression as that of what's being SELECTed, and the reason asyncpg fails vs. PG does not is because asyncpg is using prepared statements.  

At the moment the asyncpg dialect uses a positional parameter style and the information that would be required to detect the same parameter being used and therefore adjust the numeric counter applied to the parameters is not immediately present.  I don't have an expedient way to make the use case work at the moment without changing how the asyncpg dialect handles parameters totally, likely implementing the "dollar number" format within the compiler directly.  that's too big a change for 1.4.

**Comment by zzzeek** [comment]
> With some further investigation I realized the column alias was overlapping with one of the columns from a join table (not queried directly); renaming the label did indeed allow his workaround to work.

correct, that's the normal way to do this which is to use a label.   with DBs like MSSQL, this is a common requirement.


Workaround, which is IMO better SQL anyway:

```py
        await conn.execute(
            text(
                """
                SELECT (alarms.attributes ->> :bind1) AS severity
                FROM alarms
                GROUP BY severity ;
            """
            ),
            dict(bind1="severity"),
        )
```

since this issue is a little bit misleading but doesn't have any straightforward fix without rewriting how the dialect works and a very easy workaround which IMO is clearer I am leaning towards wontfix.

cc @caselit

**Comment by CaselIT** [comment]
Since the query is a sql string, if you prefer using asyncpg syntax you can also make use of `exec_driver_sql`.



> I am leaning towards wontfix.

I'm fine with this. Since asyncpg has its own kind of paramstyle that's not one of the dbapi one, I guess it's not possible without some effort to support it at the compiler level. Unless we can just piggy back on the numeric paramstyle that seem to kind of look like the asyncpg native one

**Comment by mrtolkien** [comment]
I'm having the same issue with a standard `timestamp with timezone` grouping query:

```python
from_hour = sqlalchemy.func.DATE_TRUNC(
    "hour", db.models.InOutCount.timestamp_from
).label("hour")

hourly_query = (
    sqlalchemy.select(
        from_hour,
        sqlalchemy.func.SUM(db.models.InOutCount.fw_count).label("sum"),
    )
    .group_by(from_hour)
)
```

This gives me the following error:
```log
./tests/routers/insights/test_recent_entries.py::test_old_entries Failed: [undefined]sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.GroupingError'>: column "in_out_count.timestamp_from" must appear in the GROUP BY clause or be used in an aggregate function
```

Despite that, running the query *exactly as written in the logs* works.

**Comment by CaselIT** [comment]
the above query does not seem to have binds, so I'm not sure if it's se same problem.

This almost seems like an issue with asyncpg. Does running that sql using `await conn.exec_driver_sql(the_sql)` raises the same error?

**Comment by mrtolkien** [comment]
Running the raw `SQL` query through the session works without any issue. Using `.group_by(sqlalchemy.text("hour"))` also work:
```python
# This one is OK
from_hour = sqlalchemy.func.DATE_TRUNC(
    "hour", db.models.InOutCount.timestamp_from
).label("hour")

hourly_query = (
    sqlalchemy.select(
        from_hour,
        sqlalchemy.func.SUM(db.models.InOutCount.fw_count).label("sum"),
    )
    .group_by(sqlalchemy.text("hour"))
)
```

I'm not sure where the issue lies tbh, this looks like a pretty simple query.

**Comment by CaselIT** [comment]
it may indeed be the same underlying issue.

strange that running the string works while running it via sqlalchemy (that runs the same string) does not.
@zzzeek ideas?

**Comment by zzzeek** [comment]
> I'm having the same issue with a standard `timestamp with timezone` grouping query instead of a JSONB:
> 
> ```python
> from_hour = sqlalchemy.func.DATE_TRUNC(
>     "hour", db.models.InOutCount.timestamp_from
> ).label("hour")
> 
> hourly_query = (
>     sqlalchemy.select(
>         from_hour,
>         sqlalchemy.func.SUM(db.models.InOutCount.fw_count).label("sum"),
>     )
>     .group_by(from_hour)
> )
> ```
> 
> This gives me the following error:
> 
> ```
> ./tests/routers/insights/test_recent_entries.py::test_old_entries Failed: [undefined]sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.GroupingError'>: column "in_out_count.timestamp_from" must appear in the GROUP BY clause or be used in an aggregate function
> ```
> 
> Despite that, running the query _exactly as written in the logs_ works:
> 
> ```
> SELECT DATE_TRUNC('hour', in_out_count.timestamp_from) AS hour, sum(in_out_count.fw_count) AS sum 
> FROM in_out_count GROUP BY DATE_TRUNC('hour', in_out_count.timestamp_from)
> ```
> 
> Should I make another issue? It looks like it's the exact same problem.

it's a completely different issue from what this issue is ultimately about, which is about parameters being shared.     The GROUP BY thing is a known PostgreSQL thing and the reason asyncpg behaves differently is that it's using a prepared statement.

**Comment by zzzeek** [comment]
write the query as:

```py
hourly_query = (
    sqlalchemy.select(
        from_hour,
        sqlalchemy.func.SUM(db.models.InOutCount.fw_count).label("sum"),
    )
    .group_by("hour")
)
```

docs (in the tutorial): https://docs.sqlalchemy.org/en/14/tutorial/data_select.html#tutorial-order-by-label

**Comment by mrtolkien** [comment]
Thanks for the help!

It feels a bit hacky but it works. I usually try to have as little raw string values as possible when composing queries to minimize errors, but I guess it's unavoidable here.

**Comment by zzzeek** [comment]
it's not a raw string.  try it with some random other string and see what happens

**Comment by zzzeek** [comment]
confirm this is fixed by 06c234d037bdab48e716d6c5f5 for #8926 

the above test case unmodified has the following output for the SQLA asyncpg section

```
=== Running SQL Alchemy AsyncPG Example
2023-01-25 11:44:16,101 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-01-25 11:44:16,101 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-25 11:44:16,102 INFO sqlalchemy.engine.Engine select current_schema()
2023-01-25 11:44:16,102 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-25 11:44:16,103 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-01-25 11:44:16,103 INFO sqlalchemy.engine.Engine [raw sql] ()
2023-01-25 11:44:16,104 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-25 11:44:16,104 INFO sqlalchemy.engine.Engine 
                SELECT alarms.attributes ->> $1 AS severity
                FROM alarms
                GROUP BY alarms.attributes ->> $1 ;
            
2023-01-25 11:44:16,104 INFO sqlalchemy.engine.Engine [generated in 0.00016s] ('severity',)
2023-01-25 11:44:16,105 INFO sqlalchemy.engine.Engine ROLLBACK
+++ SqlAlchemy AsyncPG Example passed

```

**Comment by MRigal** [comment]
I've just faced this issue, witout AsyncPG, plain psycopg(3), latest psycopg and sqlalchemy (2.0.43).

```
hourly_query = (
    sqlalchemy.select(
        installations.c.country,
        installations.c.custom["ascent_phase"].astext.label("reporting_phase"),  # custom being a JSONB field
    )
    .group_by(installations.c.custom["ascent_phase"].astext.label("reporting_phase"))
)
```

resulted in a psycopg.GroupingError.

Also trying `installations.c.custom[("ascent_phase",)]` and other variants led to the same result. Only using the label as `text("reporting_phase")` was able to solve the issue.
Grouping by JSONB column is uncommon, but I would not say niche. And possibly sqlalchemy could raise a warning or catch the error to raise a better one, possibly hinting the docs to use labels for grouping and ordering...

**Comment by CaselIT** [comment]
what you are trying to do is not related to this issue. the two bind parameters are different in your query

**Comment by MRigal** [comment]
Hi @CaselIT !

I've tried with various parameters, sometimes including, sometimes not, the label, to test it effects (thus I updated my previous comment to a situation relating to this issue). Sometimes forcing the `->>` operator, sometimes the `#>>`, I consistently had failures. Only using the label directly as text worked out and IMHO it is not made clear enough in the docs, this is why I was reporting that here

**Comment by CaselIT** [comment]
You are not telling SQLAlchemy to use the same parameter in your query so two different ones are used.

The error you see is expected with server side binding on pg if you use two different bind arguments.

Create a literal with the `reporting_phase` string and use it in both places and the query will work correctly.

**Comment by zzzeek** [comment]
> I've just faced this issue, witout AsyncPG, plain psycopg(3), latest psycopg and sqlalchemy (2.0.43).
> 
> ```
> hourly_query = (
>     sqlalchemy.select(
>         installations.c.country,
>         installations.c.custom["ascent_phase"].astext.label("reporting_phase"),  # custom being a JSONB field
>     )
>     .group_by(installations.c.custom["ascent_phase"].astext.label("reporting_phase"))
> )
> ```
> 
> resulted in a psycopg.GroupingError.
> 
> Also trying `installations.c.custom[("ascent_phase",)]` and other variants led to the same result. Only using the label as `text("reporting_phase")` was able to solve the issue. Grouping by JSONB column is uncommon, but I would not say niche. And possibly sqlalchemy could raise a warning or catch the error to raise a better one, possibly hinting the docs to use labels for grouping and ordering...

hi - dont use text(), dont use literal(), this is a well supported use case for SQLAlchemy.  

do it like this:

```
hourly_query = (
     sqlalchemy.select(
         installations.c.country,
         installations.c.custom["ascent_phase"].astext.label("reporting_phase"),  # custom being a JSONB field
     )
     .group_by("reporting_phase")
 )
```

docs:

https://docs.sqlalchemy.org/en/20/tutorial/data_select.html#ordering-or-grouping-by-a-label

demo:

```py
from sqlalchemy import column
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy import table
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB

installations = table(
    "installations", column("country", String), column("custom", JSONB)
)


hourly_query = select(
    installations.c.country,
    installations.c.custom["ascent_phase"].astext.label(
        "reporting_phase"
    ),  # custom being a JSONB field
).group_by("reporting_phase")


print(hourly_query.compile(dialect=postgresql.dialect()))

```

output:

```
SELECT installations.country, installations.custom ->> :custom_1 AS reporting_phase 
FROM installations GROUP BY reporting_phase
```


Note this is not a new problem that people dont realize they should do this, but I dont see any way to document this more prominently.  it is [explicitly mentioned in the docstring for group_by()](https://docs.sqlalchemy.org/en/20/core/selectable.html#sqlalchemy.sql.expression.Select.group_by), [including for the legacy Query one](https://docs.sqlalchemy.org/en/20/orm/queryguide/query.html#sqlalchemy.orm.Query.group_by), it is [right in the tutorial under ordering and grouping](https://docs.sqlalchemy.org/en/20/tutorial/data_select.html#order-by-group-by-having), and I dont see any way to make it more succinct than "name the label you want to GROUP BY in the method".

**Comment by MRigal** [comment]
Thanks for your answers!

@CaselIT I understand your point now and you are right towards the original question/issue. However I was more reacting on the latest exchanges in the issue, which were reporting the same issue than mine (the thread/issue diverged).

@zzzeek thanks for your detailed answer and understanding to which aspect I was commenting. I have been through the various documentation part and here is how I came to missing the point:

1. I'm used to group_by() from other queries, where reusing what is used in select works, so I started with that.
2. I went to the [group_by documentation](https://docs.sqlalchemy.org/en/20/core/selectable.html#sqlalchemy.sql.expression.Select.group_by) and exactly there, there is no mention of using the label. I would especially suggest to add a second example with label here, as I tend for technical documentation to focus on examples before text/description
3. I've followed the link to the group_by documentation, scrolled down to the label part. But also here, the example is about using the label in the order_by part only and using the `desc()` function. It is not clear enough to me that it "just works" for `group_by()` (although stated in the text before). I would here also add/complete the code example with one label used in the `group_by()`
4. I came from using path index operations on a JSONB with a label and be willing to group by it. There is no such example in the documentation, maybe something could be added there: https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#sqlalchemy.dialects.postgresql.JSONB

What do you think about these suggestions? Would you like me to submit a PR for it?

**Comment by zzzeek** [comment]
OK in group_by docs, the label matching behavior is mentioned only as a  seealso, so the actual `*clauses` parameter should mention that a string value may also be passed, which will be matched to a label name within the statement.   would that work?

the JSONB docs dont talk about grouping.  I think people doing grouping know to find group_by() so it needs to be mentioned further (also probably in order_by() if it is not mentioned as prominently)

**Comment by zzzeek** [comment]
in https://docs.sqlalchemy.org/en/20/tutorial/data_select.html#tutorial-order-by-label , the paragraph of text indicates the things you mention. I can try using an LLM to make the text pop more, if the text is not clear.

**Comment by MRigal** [comment]
> OK in group_by docs, the label matching behavior is mentioned only as a seealso, so the actual `*clauses` parameter should mention that a string value may also be passed, which will be matched to a label name within the statement. would that work?

Yes, that sounds like a good improvement. Also a code example would make it more obvious.

> the JSONB docs dont talk about grouping. I think people doing grouping know to find group_by() so it needs to be mentioned further (also probably in order_by() if it is not mentioned as prominently)

Why not a JSON(B) example in the classical group_by docs indeed.

> in https://docs.sqlalchemy.org/en/20/tutorial/data_select.html#tutorial-order-by-label , the paragraph of text indicates the things you mention. I can try using an LLM to make the text pop more, if the text is not clear.

I think the text is not an issue (except that it is maybe slightly long), it should "just" also be added in the code example as a `group_by` example and not only an `order_by()` example

**Comment by zzzeek** [comment]
> > OK in group_by docs, the label matching behavior is mentioned only as a seealso, so the actual `*clauses` parameter should mention that a string value may also be passed, which will be matched to a label name within the statement. would that work?
> 
> Yes, that sounds like a good improvement. Also a code example would make it more obvious.

did the first part.  for code example, the link is in the paramref, click on that to see the example.


> 
> > the JSONB docs dont talk about grouping. I think people doing grouping know to find group_by() so it needs to be mentioned further (also probably in order_by() if it is not mentioned as prominently)
> 
> Why not a JSON(B) example in the classical group_by docs indeed.

JSONB is not a SQL standard concept and it's specific to PostgreSQL.   General discussion of order_by/group_by shouldn't be crowded with deep esoteric use cases.

> 
> > in https://docs.sqlalchemy.org/en/20/tutorial/data_select.html#tutorial-order-by-label , the paragraph of text indicates the things you mention. I can try using an LLM to make the text pop more, if the text is not clear.
> 
> I think the text is not an issue (except that it is maybe slightly long), it should "just" also be added in the code example as a `group_by` example and not only an `order_by()` example

the example already includes both

```
    >>> from sqlalchemy import func, desc
    >>> stmt = (
    ...     select(Address.user_id, func.count(Address.id).label("num_addresses"))
    ...     .group_by("user_id")
    ...     .order_by("user_id", desc("num_addresses"))
    ... )
    >>> print(stmt)
    {printsql}SELECT address.user_id, count(address.id) AS num_addresses
    FROM address GROUP BY address.user_id ORDER BY address.user_id, num_addresses DESC

```


the section can be expanded to illustrate more examples including a slower discussion of what it's doing but i think people mostly need to find the section in the first place
