### ISSUE TITLE
Support 'async_creator' argument for create_async_engine

### ISSUE THREAD

**Issue by jackwotherspoon** [sqlalchemy/sqlalchemy#8215]
### Describe the use case

`sqlalchemy.create_engine` has a `creator` argument that allows a user to pass in a callable which returns a DBAPI connection to be used when creating connection pool engines.

The asyncio engine `create_async_engine` from what I can tell does not have a similar `creator` parameter. It would be nice if the async interface followed a similar pattern and had an `async_creator` parameter for performing the same functionality but with an async function.

### Databases / Backends / Drivers targeted

Would be used for all asyncio drivers. (`asyncpg`, `aiomysql`, `psycopg2` etc)

### Example Use

The [Cloud SQL Python Connector](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector) is looking to support drivers such as `aiomysql` and `asyncpg` and requires the `creator` argument currently for it's synchronous supported drivers ([Example](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/main/README.md#how-to-use-this-connector)). 

We would like to support the same functionality but with async drivers as follows:
```python
import asyncio
import asyncpg
from google.cloud.sql.connector import Connector
from sqlalchemy.ext.asyncio import create_async_engine

# initialize Cloud SQL Python Connector object
connector = Connector()

# creator function to return the database connection
async def getconn() -> asyncpg.Connection:
    conn: asyncpg.Connection = await connector.connect_async(
        "project:region:instance",  # Cloud SQL connection name
        "asyncpg",  # database driver
        user="root",
        password="shhh",
        db="your-db-name"
    )
    return conn

# create connection pool
pool = create_async_engine(
    "postgresql+asyncpg://",
    async_creator=getconn,
)
```

### Additional context

In progress Cloud SQL Python Connector [PR](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/390) looking to add support for asyncpg which would want this use case. Currently having to use native `asyncpg.create_pool` for connection pooling because SQLAlchemy does not have `async_creator` param for `create_async_engine`.

**Comment by jackwotherspoon** [comment]
@jvanasco Thanks for the quick response! That is awesome that it is on the radar, glad to hear. Is there a rough timeline on this feature that you can potentially share?

Unfortunately the workaround doesn't really work for our use case, we would be looking to have the code sample like the one pasted above referenced within the official [Google Cloud docs](https://cloud.google.com/sql/docs/postgres/connect-connectors#python) for our customers to use as reference material. Showing a workaround isn't something that we feel comfortable publishing to our customers at this time. 

Let me know if there is anyway in which I can help with the feature? More than happy to provide a helping hand and try to assist if need be.

**Comment by zzzeek** [comment]
this is likely OK for a 1.4 backport if something is being contributed soon.

**Comment by CaselIT** [comment]
Do you actually want to expose the proxy (AsyncAdapt_asyncpg_connection) ?

or should `create_async_engine` handle that?

**Comment by zzzeek** [comment]
I think async_creator should return the driver level connection and the DBAPI wrapping thing we should keep doing that part internally.  so that means all the async DBAPI wrappers have to change a little bit

**Comment by jackwotherspoon** [comment]
@zzzeek so if I were to attempt a first pass at trying to implement this ... I would just want to add internally an `adapted_creator` (from your sample above) style wrapper for each async driver? Is that what I should be taking away from this?

Any other guidance you can provide or files to point me at that will need updating would be super helpful as I start to look into this feature a bit more.

Thanks so much in advance :)

**Comment by CaselIT** [comment]
My idea is to have a way of asking for a wrapper to the dialect and have it work the same for sync and async dialects (where sync dialect would use no wrapper, while async dialects would create the proxy.

**Comment by zzzeek** [comment]
I might have been thinking the same thing but I didn't try to do it so feel free to implement

**Comment by jackwotherspoon** [comment]
@CaselIT just following up here since I may start attempting a PR if I understand your implementation correctly. What did you have in mind for implementing the following:

> My idea is to have a way of asking for a wrapper to the dialect and have it work the same for sync and async dialects

Would this be a type of flag to dictate adding the wrapper or not? Let me know if you have any examples or code snippets I should look at.

I'm happy to start work on a PR if I can just understand the desired implementation a bit better :)

**Comment by CaselIT** [comment]
> My idea is to have a way of asking for a wrapper to the dialect and have it work the same for sync and async dialects

If I remember correctly what I had in mind was the following:

- the same creator kw could be used
- all processing would be done by the sync create_engine
- when creator is present it would ask to the driver for a wrapper function, using a new dialect method called something like `def adapt_creator(self, creator_fn: Callable):`.
- The default implementation for sync engine would be to just return `creator_fn` unchanged
- for a driver like asyncpg it would basically execute the same as the current connect, so something along these lines (the current connect could share the same code)
```py
    def adapt_creator(self, creator_fn):
        def do_connect():
            async_fallback = kw.pop("async_fallback", False)
            prepared_statement_cache_size = kw.pop(
                "prepared_statement_cache_size", 100
            )
            if util.asbool(async_fallback):
                return AsyncAdaptFallback_asyncpg_connection(
                    self,
                    await_fallback(creator_fn()),
                    prepared_statement_cache_size=prepared_statement_cache_size,
                )
            else:
                return AsyncAdapt_asyncpg_connection(
                    self,
                    await_only(creator_fn()),
                    prepared_statement_cache_size=prepared_statement_cache_size,
                )
        return do_connect
```

this said I'm not sure if this would have any advantage over the solution proposed by mike above.

**Comment by Diviyan-Kalainathan** [comment]
> I came here to find solution to the same problem.
> 
> I am just wondering what is the `engine` in `engine.dialect.dbapi` here, if you are creating the engine in the succeeding lines?

I think you can solve the issue by instantiating a new dbapi [(defined here)](https://github.com/sqlalchemy/sqlalchemy/blob/228490ead7048f2e558c25b0f055bdb952272ec4/lib/sqlalchemy/dialects/postgresql/asyncpg.py#L865) : 

```python
import asyncpg
from sqlalchemy.dialects.postgresql.asyncpg import (
    AsyncAdapt_asyncpg_dbapi
)

dbapi = AsyncAdapt_asyncpg_dbapi(asyncpg)
```

hope this helps, 
Best,

**Comment by sqla-tester** [comment]
**Jack Wotherspoon** has proposed a fix for this issue in the **main** branch:

**feat: add `async_creator` argument to `create_async_engine`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4722
