### ISSUE TITLE
Use new oracledb module instead of cx_Oracle with create_engine

### ISSUE THREAD

**Issue by bburbidge** [sqlalchemy/sqlalchemy#8226]
### Describe the use case

According to the cx_Oracle github.io page(https://oracle.github.io/python-cx_Oracle/)

"cx_Oracle has a major new release under a new name and homepage [python-oracledb](https://oracle.github.io/python-oracledb/)."

The new module will allow for querying oracle without having to install additional dependencies. Currently, the create_engine module requires cx_Oracle installed, ignoring the new OracleDB module.

### Databases / Backends / Drivers targeted

Oracle. cx_Oracle.

### Example Use

usage would be like

`oracledb.create_pool(user=data['oracle_user'], password=data['oracle_pw'], dsn=data['oracle_server_ip'], min=2, max=5, increment=1, encoding='UTF-8')`

instead of

'cx_Oracle.SessionPool(user=data['oracle_user'], password=data['oracle_pw'], dsn=data['oracle_server_ip'], min=2, max=5, increment=1, encoding='UTF-8')'

**Comment by CaselIT** [comment]
Hi,

oracledb is already supported in the version 2 branch that is currently in develop.
To use it before you can do as suggested in the oracledb docs https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#python-frameworks-sql-generators-and-orms
