### ISSUE TITLE
add sqlite_system reflection parameter; ignore tables starting with sqlite_ otherwise

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8234]
sqlite defines a system table as [any table, index, view, or trigger whose name begins with "sqlite_" is an internal schema object.](https://www.sqlite.org/fileformat2.html#intschema).  we should not reflect these unless a new reflection parameter sqlite_system=True, works like "oracle_resolve_synonyms".  this should be for all reflection methods that look up tables including get_columns, get_table_names etc.

this to support https://github.com/sqlalchemy/alembic/issues/1062

cc @CaselIT is this feasible ?

**Comment by CaselIT** [comment]
I can't see why not. I'll take a look at this.

**Comment by CaselIT** [comment]
this is a breaking change compared to how the sqlite dialect currently works.
just mentioning it, I think it makes sense to have as a feature

**Comment by zzzeek** [comment]
yes it's a breaking change but we really should not be including system tables without them being asked for.

**Comment by zzzeek** [comment]
like i dont think it's going to "break" anything for anybody really, this is a pretty obscure sqlite behavior I somehow didnt ever know about for 16 years, so it really doesn't come up :)

**Comment by CaselIT** [comment]
> this should be for all reflection methods that look up tables including get_columns, get_table_names etc.

I'm not sure about `get_columns` and all other `get_` that take a `table_name` as input.
I think it would be fine to have the flag in the `get_table_names` and similar, but if the table specified in `table_name` is a system table then it should be fine to reflect.

Opition?

**Comment by CaselIT** [comment]
it seems that sqlite_master / sqlite_temp_master does not return system tables, so not sure if we actually need to do anything here?

Are `slite_*` that are returned and that will get reflected by something like `metadata.reflect`?

**Comment by zzzeek** [comment]
see the issue at https://github.com/sqlalchemy/alembic/issues/1062.  queries that ask for "all tables" need to exclude tables that start with "sqlite_".   these tables are only produced in very specific cases and they are not the tables in sqlite_master.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Sqlite reflection ignores system tables** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4012

**Comment by zzzeek** [comment]
going to change the name of the parameter as SQLite refers to these as "internal schema objects", not system tables.  that will eliminate the confusion

**Comment by CaselIT** [comment]
As you prefer. I can update it too if you have a suggestion
