### ISSUE TITLE
Support NULLS [NOT] DISTINCT in unique indexes and unique constraint

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8240]
Currently supported in pg15+ but it's supposedly part of the sql spec: https://news.ycombinator.com/item?id=32054151

https://www.postgresql.org/docs/15/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS

Assuming it's sql standard we could have a `null_distinct` equal to `True` to render `NULLS DISTINCT` and `False` to render `NULLS NOT DISTINCT`. The default `None` should not render anything.
If it's implemented for only for postgresql, a flag `postgresql_nulls_not_distinct=True` could render `NULLS NOT DISTINCT`

I would guess that reflection and alembic support would also be needed

**Comment by zzzeek** [comment]
the feature is called F292, see https://modern-sql.com/caniuse/F292

**Comment by rodrigoestevao** [comment]
Will this feature be added on version 1.4 too?

**Comment by CaselIT** [comment]
> Will this feature be added on version 1.4 too?

Unlikely, since v2 is nearing release and this is not currently planned for 2.0.0

I guess if PR are provided before release of 2.0 we could consider backporing to 1.4

**Comment by sqla-tester** [comment]
**pavelserchenia** has proposed a fix for this issue in the **main** branch:

**PG nulls not distinct support** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4632

**Comment by network-mapping-dev** [comment]
I am trying to use this option with postgres using the async driver but I get a syntax error on the Unique constraint where NULLS NOT DISTINCT is inserted:

E   asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "NULLS"

The above exception was the direct cause of the following exception:
E   sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class 'asyncpg.exceptions.PostgresSyntaxError'>: syntax error at or near "NULLS"

The above exception was the direct cause of the following exception:
E   sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.PostgresSyntaxError'>: syntax error at or near "NULLS"
    [SQL: 
    CREATE TABLE aar.rating_scheme (
    	transmission_line_id INTEGER NOT NULL, 
    	rating_methodology_id INTEGER NOT NULL, 
    	seasonal_conditions_scheme_id INTEGER NOT NULL, 
    	name VARCHAR(63) NOT NULL, 
    	mutable BOOLEAN NOT NULL, 
    	epsg INTEGER NOT NULL, 
    	active BOOLEAN, 
    	id SERIAL NOT NULL, 
    	PRIMARY KEY (id), 
    	CONSTRAINT active_rating_scheme_unique_constraint UNIQUE NULLS NOT DISTINCT (transmission_line_id, active), 
    	FOREIGN KEY(transmission_line_id) REFERENCES aar.transmission_line (id), 
    	FOREIGN KEY(rating_methodology_id) REFERENCES aar.rating_methodology (id), 
    	FOREIGN KEY(seasonal_conditions_scheme_id) REFERENCES aar.seasonal_conditions_scheme (id)
    )
    
    ]
    (Background on this error at: https://sqlalche.me/e/20/f405)

The SQL looks ok to me?

**Comment by zzzeek** [comment]
you are likely on a very old postgresql version or some variant like redshift

**Comment by network-mapping-dev** [comment]
Ah yes, thanks, I am on: PostgreSQL 14.1 and the feature was not introduced until Postgres 15+.

**Comment by pedroska777** [comment]
what is the syntax of this? Can we get some examples?
I tried something like below  :
_id = Column(UUID(as_uuid=True), postgresql_nulls_not_distinct=True)
__table_args__ = (
        UniqueConstraint(_id", name="_id_uc"),
    )

and received an error as below:
  sqlalchemy.exc.ArgumentError: Argument 'postgresql_nulls_not_distinct' is not accepted by dialect 'postgresql' on behalf of <class 'sqlalchemy.sql.schema.Column'>

**Comment by CaselIT** [comment]
that's an option of an unique constraint so that would to on the `UniqueConstraint` definition not on the column one
