### ISSUE TITLE
Find a way of raising if `DeclarativeBase` is used directly as Base

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8248]
Given that for v2 the suggested approach is to use `DeclarativeBase` to create a base class, I'm guessing there will be cases where the base will be forgotten, like the below example:

```py
import sqlalchemy as sa
from sqlalchemy import orm

class Foo(orm.DeclarativeBase):
    id = orm.mapped_column(sa.Integer, primary_key=True)

    __tablename__ = "foo"

print(Foo.metadata.tables)
```

This does not raises any error, but no table get mapped. It would be great if it could somehow raise an error, but I don't know what heuristic to use.
We could probably look for __tablename__  set to a string?

For reference the correct example above is this:

```py
import sqlalchemy as sa
from sqlalchemy import orm

class FooBase(orm.DeclarativeBase):
    pass

class Foo(FooBase):
    id = orm.mapped_column(sa.Integer, primary_key=True)

    __tablename__ = "foo"

print(Foo.metadata.tables)
```

**Comment by zzzeek** [comment]
I guess, or `__table__` is present and either are non-callables

**Comment by CaselIT** [comment]
I'll take a look. What error should it raise? invalid operation or you have a better candidate?

**Comment by zzzeek** [comment]
just do invalidreq , I dont think this will come up too much

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Ensure that a daclarative base is not used directly** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3993
