### ISSUE TITLE
ensure concat ops are used for contains / startswith / endswith independently of datatype

### ISSUE THREAD

**Issue by palisadoes** [sqlalchemy/sqlalchemy#8253]
### Describe the use case

The existing documentation for these methods only has examples using strings. The examples are not applicable to VARBINARY columns where the queries fail.
1. [ColumnOperators.contains()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.contains)
1. [ColumnOperators.endswith()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.endswith)
1. [ColumnOperators.like()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.like)
1. [ColumnOperators.startswith()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.startswith)

### Databases / Backends / Drivers targeted

N/A

### Example Use

The respective sections of documentation should be updated with edited text equivalent to the suggestions below:

 [ColumnOperators.contains()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.contains)
* When byte strings are stored in the database columns (eg. VARBINARY), you should use standard SQL wildcards with the `like()` method to represent `.contains()`:

```  
stmt = select(sometable).where(
    sometable.like(func.concat(func.concat('%', 'foobar'.encode()), '%'))
)    
```
Using `.contains()` with the same concatenations will produce an equivalent result.

[ColumnOperators.startswith()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.startswith)
* When byte strings are stored in the database columns (eg. VARBINARY), you should use standard SQL wildcards with the `like()` method to represent `.startswith()`:

```  
stmt = select(sometable).where(
    sometable.like(func.concat(func.concat('foobar'.encode()), '%'))
)    
```
Using `.startswith()` with the same concatenations will produce an equivalent result.

[ColumnOperators.endswith()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.endswith)
* When byte strings are stored in the database columns (eg. VARBINARY), you should use standard SQL wildcards with the `like()` method to represent `.endswith()`:

```  
stmt = select(sometable).where(
    sometable.like(func.concat(func.concat('%', 'foobar'.encode())))
)    
```
Using `.endswith()` with the same concatenations will produce an equivalent result.

### Additional context

N/A

**Comment by zzzeek** [comment]
So I dont think a document here is sufficient, because people tend not to find docs like these.

What I would prefer is:

1. we figure out what these operators *should* do when passed a bytestring and do that
2. we have it raise an error

1 is likely preferable

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use concat() directly for contains, startswith, endswith** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3996

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**use concat() directly for contains, startswith, endswith** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3997
