### ISSUE TITLE
Connection to database with @ as the last character of the password

### ISSUE THREAD

**Issue by Festus-Kwafo** [sqlalchemy/sqlalchemy#8278]
### Describe the bug

Connection with a password with @ as the last character raises an error stating '@host/.s.PGSQL.5432' failed. 
I think probably it catches the first @ and takes the rest as the host of the database. 

Passwords can contain any character I guess?

### To Reproduce

```python
SQLALCHEMY_DATABASE_URL = 'postgresql://user:password@@localhost/SmartToll'
```

### Error

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server on socket "@localhost/.s.PGSQL.5432" failed: Invalid argument (0x00002726/10022)
        Is the server running locally and accepting connections on that socket?

### Versions

- OS:
- Python:
- SQLAlchemy:
- Database:
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by jvanasco** [comment]
you have to URL escape special characters in passwords such as @ signs, see https://docs.sqlalchemy.org/en/14/core/engines.html#database-urls for details.

reference: #7375, #6482, #6574, #6567, #5715

**Comment by jvanasco** [comment]
You can also read on [programmatic construction of the URL object](https://docs.sqlalchemy.org/en/14/core/engines.html?highlight=url#sqlalchemy.engine.URL.create):

```
from sqlalchemy.engine import URL
url = URL.create("mysql", username="user", password="pw", host="host", database="my@database")
engine = create_engine(url)
```

**Comment by subhajit111** [comment]
u r a lifesaver. I have been stuck in this for a 2 days. 
Thankyou
