### ISSUE TITLE
Wrong type annotations for `Query.{update,delete}` parameter `synchronize_session`

### ISSUE THREAD

**Issue by akselaase** [sqlalchemy/sqlalchemy#8280]
### Describe the bug

The two functions `Query.update` and `Query.delete` allow a parameter `synchronize_session`, which is [annotated as a `str`](https://github.com/sqlalchemy/sqlalchemy/blob/741af02893a19c879ba4d929151b9358aeb48148/lib/sqlalchemy/orm/query.py#L2972). However, the documentation for the function clearly specifies that the boolean `False` is also allowed, so the correct type annotation should be either `Union[str, bool]` or maybe even `Literal['evaluate', 'fetch', False]`.

I am not sure if there is a reason for this specific type annotation, or if it simply is a mistake. I'll be glad to provide a PR to update the annotations, but which type would you prefer in that case?

### To Reproduce

```python
from sqlalchemy.orm import Query
q = Query()  # type: ignore
q.update({}, synchronize_session=False)
# Pylance complains that:
#   Argument of type "Literal[False]" cannot be assigned to parameter "synchronize_session" of type "str" in function "update"
#    "Literal[False]" is incompatible with "str"
```

### Error

There is no stack trace, since this happens during static type checking, not at runtime. The error message from Pyright is:
```
Argument of type "Literal[False]" cannot be assigned to parameter "synchronize_session" of type "str" in function "update"
  "Literal[False]" is incompatible with "str"
```

### Versions

- OS: Linux
- Python: 3.10
- SQLAlchemy: 1.4.31 (but also latest master per July 23rd)
- Database: N/A
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): N/A

### Additional context

Not a runtime problem, but a static type annotation issue.

**Comment by zzzeek** [comment]
no 1.4 fix here, someone would need to send a PR to github.com/sqlalchemy/sqlalchemy2-stubs.

for 2.0 it looks like mypy 0.971 broke the whole test suite with cause unknown at this time.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**set up Literal for synchronize_session** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4008

**Comment by zzzeek** [comment]
if someone wants to PR for https://github.com/sqlalchemy/sqlalchemy2-stubs, the main idea is:

```py
_SynchronizeSessionArgument = Literal[False, "evaluate", "fetch"]
```
