### ISSUE TITLE
func.to_char bug

### ISSUE THREAD

**Issue by frbelotto** [sqlalchemy/sqlalchemy#8291]
### Describe the bug

Hello guys,
I am trying run a single TO_CHAR func over a DB2 for Z/OS, but it does not work.

```
guiaspagas = Table ('ANL_GUIAS_PAGAS_PREPAGO', metadata, Column('dt_arrec', Date))
select_stmt_resumoguias = select(func.to_char(guiaspagas.c.dt_arrec,'YYYY'))
```

If I try it by a simple SQL RAW instruction, it work. 
`select_stmt_resumoguias = '''select to_char(dt_arrec, 'yyyy') from DB2I023A.ANL_GUIAS_PAGAS_PREPAGO;'''`

### To Reproduce

```python
guiaspagas = Table ('ANL_GUIAS_PAGAS_PREPAGO', metadata, Column('dt_arrec', Date))
select_stmt_resumoguias = select(func.to_char(guiaspagas.c.dt_arrec,'YYYY'))
```

### Error

```
Exception has occurred: ProgrammingError
(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2] SQL0171N  The statement was not processed because the data type, length or value of the argument for the parameter in position "2" of routine "TO_CHAR" is incorrect. Parameter name: "TO_CHAR".  SQLSTATE=42815  SQLCODE=-171
[SQL: SELECT to_char("DB2I023A"."ANL_GUIAS_PAGAS_PREPAGO".dt_arrec, ?) AS to_char_1 
FROM "DB2I023A"."ANL_GUIAS_PAGAS_PREPAGO"]
[parameters: (b'YYYY',)]
(Background on this error at: https://sqlalche.me/e/14/f405)
```
### Versions

- Python: 3.10.5
- SQLAlchemy: 1.4.39
- Database: DB2 Z/OS
- DBAPI : ibm_db_sa 0.3.8

### Additional context

1) Is SQLAlchemy column names case sensitive?

**Comment by CaselIT** [comment]
Hi,

from the error message
> `[parameters: (b'YYYY',)]`

it seems that the dialect is passing bytes instead of a string? This may be an external driver issue.

Does using cast or text fix it? Something like `select(func.to_char(guiaspagas.c.dt_arrec, sa.text("'YYYY'")))`

>Is SQLAlchemy column names case sensitive?

yes, `dt_arrec` will render `dt_arrec` lowercase. Note that many database ignore case unless using quote chars like `"`

**Comment by frbelotto** [comment]
> > `[parameters: (b'YYYY',)]`
> > it seems that the dialect is passing bytes instead of a string? This may be an external driver issue.
> > Does using cast or text fix it? Something like `select(func.to_char(guiaspagas.c.dt_arrec, sa.text("'YYYY'")))`
> 

Yes, it works. When using your suggestion the SQL Query is writen different. 

```
select_stmt_resumoguias = select(func.to_char(guiaspagas.c.dt_arrec, text("'YYYY'")))

 SELECT to_char("DB2I023A"."ANL_GUIAS_PAGAS_PREPAGO".dt_arrec, **'YYYY') AS to_char_1** 
FROM "DB2I023A"."ANL_GUIAS_PAGAS_PREPAGO"
```

**Comment by frbelotto** [comment]
I am testing such function over a different database now and I´ve notice 

This works:
```
stmt = select(func.count(employees.c.emp_id), func.to_char(employees.c.b_date,'MM/YYYY')).group_by(employees.c.b_date)
>> (1, '07/1972') output normally
```

But this one does not. :
`
stmt = select(func.count(employees.c.emp_id), func.to_char(employees.c.b_date,'MM/YYYY')).group_by(func.to_char(employees.c.b_date,'MM/YYYY'))`


```
```
SQL0119N  An expression starting with "B_DATE" specified in a SELECT clause, HAVING clause, or ORDER BY clause is not specified in the GROUP BY clause or it is in a SELECT clause, HAVING clause, or ORDER BY clause with a column function and no GROUP BY clause is specified.  SQLSTATE=42803  SQLCODE=-119
[SQL: SELECT count(employees.emp_id) AS count_1, to_char(employees.b_date, ?) AS to_char_1 
FROM employees GROUP BY to_char(employees.b_date, ?)]
[parameters: (b'MM/YYYY', b'MM/YYYY')]
```

Despite of the different error, take note that the "parameters" seems to being passed in bytes anyway.

**Comment by frbelotto** [comment]
Another test:

Using IBM DB
```
sql = '''select count(emp_id), to_char(b_date,'YYYY') from employees group by to_char(b_date,'YYYY')'''      

stmt = ibm_db.exec_immediate(conn, sql)
dictionary = ibm_db.fetch_tuple(stmt)
while dictionary != False:
    print(dictionary)
    dictionary = ibm_db.fetch_tuple(stmt)
>>>(1, '1972')
>>>(1, '1975')
>>>(1, '1976')

```
Using SQLA text
```
stmt = text('''select count(emp_id), to_char(b_date,'YYYY') from employees group by to_char(b_date,'YYYY')''')        
print (stmt)
with engine.begin() as conn:
    result = conn.execute(stmt)
    for row in result:
        print (row)
>>>(1, '1972')
>>>(1, '1975')
>>>(1, '1976')
```


using SQLA core select
```
stmt = select(func.count(employees.c.emp_id), func.to_char(employees.c.b_date,('YYYY'))).group_by(func.to_char(employees.c.b_date,('YYYY')))
print(stmt.compile(compile_kwargs={"literal_binds": True}))
with engine.begin() as conn:
    result = conn.execute(stmt)
    for row in result:
        print (row)

SELECT count(employees.emp_id) AS count_1, to_char(employees.b_date, 'YYYY') AS to_char_1 
FROM employees GROUP BY to_char(employees.b_date, 'YYYY')

ProgrammingError: (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0119N  An expression starting with "B_DATE" specified in a SELECT clause, HAVING clause, or ORDER BY clause is not specified in the GROUP BY clause or it is in a SELECT clause, HAVING clause, or ORDER BY clause with a column function and no GROUP BY clause is specified.  SQLSTATE=42803  SQLCODE=-119
[SQL: SELECT count(employees.emp_id) AS count_1, to_char(employees.b_date, ?) AS to_char_1 
FROM employees GROUP BY to_char(employees.b_date, ?)]
[parameters: (b'YYYY', b'YYYY')]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by zzzeek** [comment]
we can keep discussing here but these are issues specific to the ibm_db_sa project which should have its own support. We don't support it here.
