### ISSUE TITLE
PyODBC / MSSQL not releasing connection after exception

### ISSUE THREAD

**Issue by scossu** [sqlalchemy/sqlalchemy#8296]
### Describe the bug

I am using Flask-SQLAlchemy with PyODBC to connect to a MSSQL database. 

Occasionally, the code raises a custom exception. When this happens, the connection used to access the DB is not released, eventually raising the `QueuePool limit of size <x> overflow <y> reached, connection timed out, timeout <z>` error.

Below is a snippet of the logs capturing the leak. This is happening after a string of single-threaded of HTTP requests. I only ever see one connection open at any time. 

```
tms_gw  | DEBUG:sqlalchemy.pool.impl.QueuePool:Connection <pyodbc.Connection object at 0x7f538ae9a110>
 checked out from pool
tms_gw  | INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
tms_gw  | 2022-07-27 21:22:50,046 INFO sqlalchemy.engine.Engine BEGIN (implicit)
[...]
tms_gw  |     _recurse(art, loc_set)
tms_gw  |   File "/.../artifact.py", line 328, in _recurse
tms_gw  |     _recurse(art.parent, loc_set, "parent")
tms_gw  |   File "/.../artifact.py", line 325, in _recurse
tms_gw  |     raise DataError(
tms_gw  | tms_gw.exceptions.DataError: Artifact requires parent location but has no parent!
tms_gw  | DEBUG:sqlalchemy.pool.impl.QueuePool:Created new connection <pyodbc.Connection object at 0x7f53889dd730>
tms_gw  | DEBUG:sqlalchemy.pool.impl.QueuePool:Connection <pyodbc.Connection object at 0x7f53889dd730> checked out from pool
```

Connection `0x7f538ae9a110` is never mentioned again in the logs, as `0x7f53889dd730` takes over. 

I am raising the issue here because I see that the connection class belongs to SQLAlchemy, but please direct me otherwise if you think that the problem lies elsewhere in the stack.

### To Reproduce

```python
import logging

from os import environ

from flask import Flask
from flask_sqlalchemy import SQLAlchemy


logger = logging.getLogger(__name__)
logging.basicConfig(encoding='utf-8', level=logging.DEBUG)


class CustomError(RuntimeError):
    pass


def create_app():
    app = Flask(__name__)
    app.config.update({
        "ENV": "development",
        "SECRET_KEY": "changeme",
        "JSON_AS_ASCII": False,
        "JSONIFY_PRETTYPRINT_REGULAR": True,
    })

    return app


app = create_app()

app.config["SQLALCHEMY_DATABASE_URI"] = (
    f"mssql+pyodbc://{environ['DB_USER']}:"
    f"{environ['DB_PW']}@{environ['DB_HOST']}/"
    f"{environ['DB_DBNAME']}?driver=ODBC+Driver+17+for+SQL+Server"
)
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
db = SQLAlchemy(
        app, engine_options={
            "pool_size": 10,
            "max_overflow": 20,
            "echo": True,
        })


@app.route("/")
def raise_error():
    raise CustomError("blah")
```

### Error

See log snippet in description. The issue does not necessarily raise an error (with `max_overflow=-1`), but consumes increasingly more resources.

### Versions

- OS: Docker: python:3.9-alpine3.15
- Python: 3.9.13
- SQLAlchemy: 1.4.39
- Database: MSSQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pyodbc 4.0.34

### Additional context

odbcinst.txt:
```
[MSSQLServerDatabase]
Driver      = ODBC Driver 17 for SQL Server
Description = MSSQL database connection
Trace       = No
Server      = <server name>
```

**Comment by zzzeek** [comment]
I would normally convert to discussion here since [per the bug reporting guidelines](https://github.com/sqlalchemy/sqlalchemy/blob/main/.github/ISSUE_TEMPLATE/bug_report.yaml) there's nothing actionable here nor is the error given unusual, it's [the most common error recieved](https://docs.sqlalchemy.org/en/14/errors.html#queuepool-limit-of-size-x-overflow-y-reached-connection-timed-out-timeout-z), but since you are using Flask, you can ask the Flask group for help, your issue is improper handling of database connections in your application.
