### ISSUE TITLE
Memory usage when streaming data

### ISSUE THREAD

**Issue by olliemath** [sqlalchemy/sqlalchemy#8301]
### Describe the bug

# Issue

When streaming objects from a large table like so:
```python
for user in session.query(User):
    pass
```
memory usage increases constantly. This true under cpython, but especially prominent under pypy where we can end up with 10s of gigabytes allocated for objects that are no longer referenced.

# Expected behaviour

I would expect the memory usage to be constant when streaming data like this.

### To Reproduce

```python
import gc
import os
import random
import sys
from csv import DictReader, DictWriter
from string import ascii_letters


try:
    import psutil
    from sqlalchemy import create_engine
    from sqlalchemy import Column, Integer, String
    from sqlalchemy.ext.declarative import declarative_base
    from sqlalchemy.orm import sessionmaker
    from tqdm import tqdm
except ImportError:
    print("Please run 'pip install sqlalchemy psutil tqdm'")
    exit(1)


def printmem(msg):
    # Not crazy accurate, but good enough for our purposes
    raw = psutil.Process().memory_info().rss // (1024 * 1024)
    print(f"{msg} {raw}m")


def rstring():
    return "".join(random.sample(ascii_letters, 8))


# Setting up SQLA
Base = declarative_base()

class User(Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    fullname = Column(String)
    nickname = Column(String)


if not os.path.exists("user.csv"):
    if os.path.exists("db.sqlite"):
        os.remove("db.sqlite")

    print("Generating data - this may take some time.")
    with open("user.csv", "w") as f:
        writer = DictWriter(
            f, fieldnames=("id", "name", "fullname", "nickname")
        )
        writer.writeheader()
        for n in tqdm(range(10_000_000)):
            writer.writerow(dict(id=n, name=rstring(), fullname=rstring(), nickname=rstring()))


    # Bypass SQLA for the initial load (let's not skew our statistics)
    printmem("Before inserting")
    engine = create_engine('sqlite:///db.sqlite', echo=False)
    Base.metadata.create_all(engine)
    _con = engine.raw_connection()
    _cur = _con.cursor()

    with open("user.csv") as f:
        reader = DictReader(f)

        _cur.executemany(
            "INSERT INTO user (id, name, fullname, nickname) VALUES (?, ?, ?, ?);",
            (
                (int(row["id"]), row["name"], row["fullname"], row["nickname"])
                for row in reader
            ),
        )

    _con.commit()
    _cur.close()
    _con.close()
    engine.dispose()
    gc.collect()
    printmem("After inserting")

# Fresh engine and time for the actual benchmark
engine = create_engine('sqlite:///db.sqlite', echo=False)
Session = sessionmaker(bind=engine)
Session = sessionmaker()
Session.configure(bind=engine)
session = Session()

try:
    N = int(sys.argv[1])
except IndexError:
    N = int(input("Enter number of rows to stream: (0-10000000)"))
for user in session.query(User).limit(N):
    assert user.name
    # session.commit()  # Makes no difference

printmem("After querying")
session.commit()
printmem("After commit")
gc.collect()
printmem("After gc collect\n")
```

### Error

| users | cypthon 3.8 memory (mb) | pypy 3.8 memory (mb) |
| ------ | ------ | ------ |
| 1_000 | 27 | 89 |
| 10_000 | 30 | 107 |
| 100_000 | 39 | 208 |
| 1_000_000 | 110 | 1533 |
| 10_000_000 | 384 | 13793 |

### Versions

- OS: Ubuntu
- Python: PyPy 3.8
- SQLAlchemy: 1.3-1.4
- Database: sqlite3

### Additional context

This is actually a sister issue to one already opened with the pypy project https://foss.heptapod.net/pypy/pypy/-/issues/3790 I'd appreciate your help in finding whether this a SQLAlchemy issue, or if it's something to do with how CPython/PyPy handle weak refs.

In particular, if this is "not a SQLAlchemy problem", I would very much appreciate pointers to dig into the SQLAlchemy codebase and pull out as minimal a reproducer as possible to help cpython/pypy get better at this.

**Comment by olliemath** [comment]
Possibly I have misunderstood the behaviour of `iter(session.query(User))`?

Is this allocating all of the users into memory at the same time, rather than iterating over them in some sort of default batch size?

**Comment by jvanasco** [comment]
> Possibly I have misunderstood the behaviour of iter(session.query(User))?

Yes.

> Is this allocating all of the users into memory at the same time, rather than iterating over them in some sort of default batch size?

No. You are iteratively stepping through each query, but you are using the Session to query - which is loading each record into the ORM's active Session as a Python object, and persisting them throughout the scope of the Session.  see https://docs.sqlalchemy.org/en/14/orm/session.html ; the `user` instance is no longer within scope of your code, but it is within the scope of the active Session.

If you are dealing with large numbers of records, you probably want to use the SQLAlachemy Core - not ORM.  see https://docs.sqlalchemy.org/en/14/tutorial/index.html . You can use the existing ORM classes to query with the CORE.

Also worth reading is this FAQ entry: https://docs.sqlalchemy.org/en/14/faq/performance.html#i-m-inserting-400-000-rows-with-the-orm-and-it-s-really-slow ; there are some ORM utilities that can leverage core and minimize the involvement with ORM.

There are a handful of examples and edge cases on optimizing this in closed issues and the mailing-list/group archives.

**Comment by zzzeek** [comment]
hi - 

for streaming you need to use [yield_per](https://docs.sqlalchemy.org/en/14/orm/queryguide.html#orm-queryguide-yield-per) - see that section for extensive docs on how to stream large collections.

**Comment by zzzeek** [comment]
> > Possibly I have misunderstood the behaviour of iter(session.query(User))?
> 
> Yes.


yes in taht you should use the [yield_per](https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.yield_per) method 
> 
> > Is this allocating all of the users into memory at the same time, rather than iterating over them in some sort of default batch size?

> 
> No. 

yes,  it is.  the entire list of results is loaded into memory at once without yield_per.  turn on yield_per, problem here goes away.

> Pay attention to this section: https://docs.sqlalchemy.org/en/14/orm/session_basics.html#what-does-the-session-do
> 
> If you are dealing with large numbers of records, you probably want to use the SQLAlachemy Core - not ORM. 

this case is fine with the ORM as long as not too many objects in memory at once.

> Also worth reading is this FAQ entry: https://docs.sqlalchemy.org/en/14/faq/performance.html#i-m-inserting-400-000-rows-with-the-orm-and-it-s-really-slow ; there are some ORM utilities that can leverage core and minimize the involvement with ORM.

that applies to INSERTs, not SELECTs.  also that whole FAQ entry will mostly go away for 2.0....

**Comment by olliemath** [comment]
Thanks both for your quick / thorough replies and sorry for the noise.

OK, that's cleared up some misunderstandings I had around `iter(session.query(User))` - I had assumed it would act more like `iter` on a file handle (or similar IO-based thingamajig).

**Comment by zzzeek** [comment]
it's theoretically possible that yield_per could be more of a default in future releases for new-style queries, though there would be some awkwardnesses there re: server side cursors.  it's not out of the gate compatible with the legacy `Query` object, which wants to uniquify rows in memory and also not compatible with joined / subquery eager loading of  related collections.
