### ISSUE TITLE
proactively detetct illegal @ sign in URL and raise an explicit error with link to errors page

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8328]
we need to fix the @ sign problem with a link to docs

**Comment by CaselIT** [comment]
Personally I was leaning towards a checkbox to fill in the new issue template.

"The issue is not @ in password" y/n

**Comment by zzzeek** [comment]
I guess the original issue was someone had an @ sign in their host, right?  then it would be impossible to detect this

```py
u = url.make_url("dialect://user:pa@ho@st/db?arg1=param1&arg2=param2")
```

**Comment by zzzeek** [comment]
in #6482 looks like it was database portion

the problem with the issue template is that nobody reads it

**Comment by zzzeek** [comment]
but yeah no way to detect this

**Comment by CaselIT** [comment]
Still better than nothing.



> but yeah no way to detect this

Not without a lot of potential false positive

**Comment by zzzeek** [comment]
the template is up, linking to a section in engines.html that is building for sphinx now, link is broken for the moment
