### ISSUE TITLE
Docs: async_scoped_session example wastes memory

### ISSUE THREAD

**Issue by auxsvr** [sqlalchemy/sqlalchemy#8340]
### Describe the bug

According to the [sample code](https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html?highlight=asyncscopedsession) for an asyncio scoped session, using `asyncio.current_task` for the scope function is suggested. However, this is a bad idea, as it implies that every task with a session will remain in memory forever due to the reference as a key in the `ScopedRegistry.registry`. The following scope function seems to avoid this issue:

```python
def scopefunc():
    def cb(task):
        del AsyncScopedSession.registry.registry[task]

    task = asyncio.current_task()
    task.add_done_callback(cb)
    return task
```

### To Reproduce

```python
Follow the documentation about creating an asyncio scoped session.
```

### Error

The code in the documentation results in wasting about 5 MiB RAM for each iteration in a simple loop that creates 1k tasks reading from the database.

### Versions

- OS: openSUSE Tumbleweed
- Python: 3.10
- SQLAlchemy: master
- Database: Postgresql 14.3
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg 3.0.16

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. The suggested method is not safe, since it cannot be called multiple times, a normal thing when dealing with a scoped session.

Also note that there is no problem if the scoped session is correctly used, ie `remove()` is called once the scope is done.
Failing to do that will also leak the session, not only the task

**Comment by zzzeek** [comment]
im not sure how that scopefunc is feasible since scopefunc() can be called any number of times, it would create tons of callbacks.

I think the main thing when using a "scoped" registry is that it has to be in some context that is calling .remove() at the appropriate time, which should be set up by whatever it is that is setting up the current task to start with.   however a nice way to do that is not coming to me since the .remove() has to be in the coroutine function itself.

the bigger theme here is that "scoped session" is really awkward to use with asyncio and I dont know why we really have this.

**Comment by zzzeek** [comment]
the documentation here already shows the correct use in the second example.  So i think we add a warning and be done w it

**Comment by zzzeek** [comment]
I also need to warn against the pattern you have above as that is also very wasteful

**Comment by auxsvr** [comment]
Perhaps I'm not using the scoped session correctly: shouldn't the scope be defined so that the session's lifetime matches that of the task in this case? If so, using:

1. the scope function below and
2. the `AsyncSession` as a context manager 

without `AsyncSession.remove()` should be enough. Using `asyncio.current_task` instead and `await AsyncSession.remove()` at the end of the loop seems to make the scoped session redundant. Why not use a simple session instead if resource management is completely manual?

Regarding idempotency: the following `scope` is idempotent, but unfortunately accesses a private variable:
```python
def cb(task):
    del AsyncSession.registry.registry[task]


def scope() -> asyncio.Task:
    task = asyncio.current_task()
    if not any(c for c in task._callbacks if c[0] is cb):
        task.add_done_callback(cb)
    return task
```

Having used ActiveRecord for years, I ought to say that SQLAlchemy and alembic are much closer to the ideal ORM/SQL toolkit for me, and I would like to thank you for creating them.

**Comment by CaselIT** [comment]
> without `AsyncSession.remove()` should be enough

I believe that would leave the session open



> Why not use a simple session instead if resource management is completely manual?

Scoped session is used when one wants to avoid passing a session around a possibly deep call stack

**Comment by zzzeek** [comment]
> 
> without `AsyncSession.remove()` should be enough. Using `asyncio.current_task` instead and `await AsyncSession.remove()` at the end of the loop seems to make the scoped session redundant. Why not use a simple session instead if resource management is completely manual?

I would agree.    People keep asking for scoped sessions , so we added it.   in my change above note I added a tip right at the above, this is likely not worth using.


> 
> Regarding idempotency: the following `scope` is idempotent, but unfortunately accesses a private variable:
> 
> ```python
> def cb(task):
>     del AsyncSession.registry.registry[task]

sure, the scoped sessions in this case would be better off having more API to allow removal of specific scopes.    none of this really mattered in the thread local version as people were usually in web frameworks with a clear "here's where we tear things down", and you were always in that one thread.  async is nothing like this.

> 
> 
> def scope() -> asyncio.Task:
>     task = asyncio.current_task()
>     if not any(c for c in task._callbacks if c[0] is cb):
>         task.add_done_callback(cb)
>     return task
> ```
> 
> Having used ActiveRecord for years, I ought to say that SQLAlchemy and alembic are much closer to the ideal ORM/SQL toolkit for me, and I would like to thank you for creating them.

you're welcome!   havent heard that before usually AR proponents are very sold on that way of working.
