### ISSUE TITLE
Support kw_only (and maybe match_args) in dataclasses

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8346]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/8345

<div type='discussions-op-text'>

<sup>Originally posted by **lonelyteapot** August  3, 2022</sup>
I'm looking into SQLAlchemy 2.0.0b1 and the new dataclasses mapping feature.

Here's a quote from [the docs](https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#class-level-feature-configuration):

> Support for dataclasses features is partial. Currently supported are the `init`, `repr`, `eq`, `order` and `unsafe_hash` features. Currently not supported are the `frozen`, `slots`, `match_args`, and `kw_only` features.

Is there any particular reason they're not supported? If not, are they being worked on currently? I couldn't find any issues nor PRs regarding this. I'm not that familiar with the project, so I hesitate filing an issue myself.

My use case needs `kw_only` enabled. I'd like to declare models like this:

```python
class Foo(MappedAsDataclass, Base, kw_only=True):
    id: Mapped[UUID] = mapped_column(UUID, primary_key=True, default_factory=uuid4)
    name: Mapped[str] = mapped_column()
```

Notice that a default-initialized field `id` comes before a not-default-initialized field `name`. This is not possible without `kw_only=True` because of the conflict of positional arguments in the generated `__init__` method.
</div>

let's try for 2.0

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Support kw_only and match_args in dataclass mapping** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4024
