### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_global_attributes'

### ISSUE THREAD

**Issue by anler** [sqlalchemy/sqlalchemy#8347]
### Describe the bug

Hello! I'm getting this error when using `Query.instances(result)` method.

Digging in more I saw that the method `sqlalchemy.orm.context.ORMFromStatementCompileState.create_for_statement` receives a `compiler` argument and checks if it's None like this:

```python
    def create_for_statement(cls, statement_container, compiler, **kw):

        if compiler is not None:
            toplevel = not compiler.stack
        else:
            toplevel = True
```

The problem is that in case compiler is None, it will cause this AttributeError because a few lines down in that method it tries to read `compiler._global_attributes`

```python
        if toplevel and statement_container._with_options:
            self.attributes = {"_unbound_load_dedupes": set()}
            self.global_attributes = compiler._global_attributes
```

### To Reproduce

```python
- Execute a statement with a session `result = session.execute(stmt)`
- Query a model and bind instances:

query = meta.session.query(SomeModel)
query = query.from_statement(stmt)
query = query.options(load_only(SomeModel.fields...))
query.instances(result) # <-- raises AttributeError: NoneType has no attribute _global_attributes
```

### Error

```
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3002, in instances
    compile_state = self._compile_state(for_statement=False)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3331, in _compile_state
    return compile_state_cls.create_for_statement(stmt, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/context.py", line 462, in create_for_statement
    self.attributes = {"_unbound_load_dedupes": set()}
AttributeError: 'NoneType' object has no attribute '_global_attributes'``` 

### Versions

- OS: Linux 4b15329cc56f 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Python: 2.7.12
- SQLAlchemy: 1.4.39
- Database: MySQL 5.6
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): mysqlclient


### Additional context

_No response_

**Comment by zzzeek** [comment]
instances() is basically going away, and you now have much better ways to get ORM objects from all kinds of statements.   so I would lean towards "wontfix" on this and if you can share what query you actually need to run, I can show you how to do it using newer APIs.

**Comment by anler** [comment]
Hi @zzzeek, that was my suspicion, I'm trying to update from an older version to 1.4.39 and did not want to move things around too much, but I understand you so I will try to rewrite it with the new API and I'll let you know if I need some help. Thank you so much 🙏🏻

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**deprecate Query.instances()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4025

**Comment by zzzeek** [comment]
yeah it wasn't formally "deprecated" because it seemed like nobody was using it, so it will be under deprecated status in 2.0.  thanks!
