### ISSUE TITLE
Where clause does not include IS NULL

### ISSUE THREAD

**Issue by CrafterSvK** [sqlalchemy/sqlalchemy#8382]
### Describe the bug

Where clause with `is None` condition is ignored and not present in SQL query.

### To Reproduce

```python
session.execute(select(Data).where(
  or_(
    and_(Data.class != '05', Data.grid == 1),
    and_(Data.class == '05', Data.grid is None)
))
```

### Error

No error

### Versions

- OS: ArchLinux rolling
- Python: 3.10
- SQLAlchemy: 1.4.31
- Database: PostgreSQL 14.3
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg

### Additional context

Because of this, sometimes isn't index isn't used or condition just isn't the same.
This can be fixed using `text('grid IS NULL')`

**Comment by CaselIT** [comment]
Hi,

This is expected, since python does not allow implenting a custom operation of is. See https://github.com/sqlalchemy/sqlalchemy/discussions/8378 for details.


You can use `==` or the `is_()` method instead

**Comment by zzzeek** [comment]
i wish we had a "law of twos" label, but I'd never be able to find the 300 issues that have followed it
