### ISSUE TITLE
add before/after event hooks for all schema items

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8394]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/8390

this is straightforward and a gerrit is upcoming.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**support create/drop events for all CREATE/DROP** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4035
