### ISSUE TITLE
`with_loader_criteria` with deferred relationship loaders, closure variables not carrying forward

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8399]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/8398

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import event
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import orm
from sqlalchemy.sql import Select
from sqlalchemy import String
from sqlalchemy import Table
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import declared_attr
from sqlalchemy.orm import ORMExecuteState
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker


class Context:
    def __init__(self):
        self.current_account = None

    def get_current_account(self):
        return self.current_account

    def set_current_account(self, account):
        self.current_account = account


context = Context()


@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state: ORMExecuteState):
    """Intercept all ORM queries.   Add a with_loader_criteria option to all
    of them.

    This adds a filter by account id to provide automatic 'tenant isolation'.
    """

    # the with_loader_criteria automatically applies itself to
    # relationship loads as well including lazy loads.   So if this is
    # a relationship load, assume the option was set up from the top level
    # query.

    if (
        not execute_state.is_relationship_load
        and not execute_state.is_column_load
        and not execute_state.execution_options.get(
            "include_all_accounts", False
        )
        # avoid infinite recursion where getting the account makes a request
        # that needs to get the account and...
        and not (
            isinstance(execute_state.statement, Select)
            and len(execute_state.statement.get_final_froms()) == 1
            and isinstance(execute_state.statement.get_final_froms()[0], Table)
            and execute_state.statement.get_final_froms()[0].name
            == Account.__tablename__
        )
    ):
        account = context.get_current_account()
        current_account_id = account.id
        if current_account_id is not None:
            execute_state.statement = execute_state.statement.options(
                orm.with_loader_criteria(
                    AccountBoundMixin,
                    lambda cls: cls.account_id == current_account_id,
                    include_aliases=True,
                    track_closure_variables=True,
                )
            )


Base = declarative_base()


class Account(Base):
    __tablename__ = "account"

    id = Column(
        String,
        primary_key=True,
    )
    name = Column(String)


class AccountBoundMixin:
    @declared_attr
    def account_id(cls):
        return Column(
            String, ForeignKey("account.id"), index=True, nullable=False
        )

    @declared_attr
    def account(cls):
        return relationship("Account")


class User(Base, AccountBoundMixin):
    __tablename__ = "user"

    id = Column(Integer, primary_key=True)
    name = Column(String)
    addresses = relationship("Address", back_populates="user")


class Address(Base, AccountBoundMixin):
    __tablename__ = "address"

    id = Column(Integer, primary_key=True)
    email = Column(String)
    user_id = Column(Integer, ForeignKey("user.id"))

    user = relationship("User", back_populates="addresses")


if __name__ == "__main__":
    MAKE_TESTS_PASS = False

    kwargs = dict() if not MAKE_TESTS_PASS else dict(query_cache_size=0)

    engine = create_engine("sqlite://", pool_pre_ping=True, echo=True, **kwargs)

    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(bind=engine, future=True)

    sess = Session()

    acc1 = Account(name="test account 1", id="acc1")
    acc2 = Account(name="test account 2", id="acc2")
    sess.add_all([acc1, acc2])
    sess.flush()

    context.set_current_account(account=acc1)

    sess.add_all(
        [
            User(
                name="u1",
                account_id=acc1.id,
                addresses=[
                    Address(email="u1a1", account_id=acc1.id),
                    Address(email="u1a2", account_id=acc1.id),
                ],
            ),
            User(
                name="u2",
                account_id=acc1.id,
                addresses=[
                    Address(email="u2a1", account_id=acc2.id),
                    Address(email="u2a2", account_id=acc1.id),
                ],
            ),
            User(
                name="u3",
                account_id=acc2.id,
                addresses=[
                    Address(email="u3a1", account_id=acc2.id),
                    Address(email="u3a2", account_id=acc2.id),
                ],
            ),
            User(
                name="u4",
                account_id=acc2.id,
                addresses=[
                    Address(email="u4a1", account_id=acc2.id),
                    Address(email="u4a2", account_id=acc1.id),
                ],
            ),
            User(
                name="u5",
                account_id=acc1.id,
                addresses=[
                    Address(email="u5a1", account_id=acc1.id),
                    Address(email="u5a2", account_id=acc2.id),
                ],
            ),
        ]
    )

    sess.commit()

    # now querying Address or User objects only gives us the ones from the
    # current account
    for u1 in sess.query(User).options(orm.selectinload(User.addresses)):
        assert u1.account_id == acc1.id

        # the addresses collection will also be "current account only",
        # which works for all relationship loaders including joinedload
        for address in u1.addresses:
            assert address.account_id == acc1.id

    # change account and check we only get data from the 'new current account'
    context.set_current_account(account=acc2)
    for u1 in sess.query(User).options(orm.selectinload(User.addresses)):
        assert u1.account_id == acc2.id

        for address in u1.addresses:
            assert (
                address.account_id == acc2.id
            ), "expected all addresses to belong to account 2"
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**refine transfer of cached ORM options for selectin, lazy** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4036

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**refine transfer of cached ORM options for selectin, lazy** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4037

**Comment by ldirer** [comment]
Thank you for the patch and the very quick response!

I looked into the patch. I can see it's now working, but I don't understand it well enough to give useful feedback :slightly_smiling_face: .

**Comment by zzzeek** [comment]
the loader strategies, which are things like "SelectInLoader" that's responsible for emitting that second SELECT after the ORM loads some objects, need to refer to the parent query (the one you wrote and sent to execute()) in order to retrieve the "option" objects from it.  These are the options like "selectinload()" and "with_loader_crtiera()", and they exist as relatively simple objects with some state inside of them that indicates what actions should be taken when the objects are queried and/or loaded.   Such as in this case, the SelectInLoader needs to pull out and use that "with_loader_criteria()" option because we want it to take effect for all the loaders.

the complicated thing comes in when the parent query is cached.    When that happens, when you say `session.execute(stmt)`, there are actually two select() objects involved; the one that you just created and passed to `session.execute()`, and the one that you sent originally, which is now the "cached" statement.   the way those two different objects get matched up is because they advertise that they have a specific structure, which in this case happens to be identical for both select() objects, and that structure is what is used as the cache key.  

within the caching process, way more than just the string SQL is cached, the whole structure of how the ORM will load objects from the rows returned by query is also part of what's cached since creating that is in fact more computationally intense than just the string SQL statement.

Back to SelectInLoader, which wants to re-use the option objects from the "parent" query which is cached.   This is happening just as objects were loaded.   But those objects that were loaded, were loaded using the *cached* "ORM loading structure", and it's that cached ORM loading structure that is calling the SelectInLoader right now, and it's passing it things like what kinds of objects we are loading, which could include various forms of "aliased" objects, like `aliased(Account)`, or `with_polymorphic()` structures, etc.  The specific case looks like this:

```py

user_alias_1 = aliased(User)
address_alias_1 = aliased(Address)

stmt_1 = select(user_alias_1).options(
     selectinload(user_alias_1.addresses.of_type(address_alias_1))
    .selectinload(address_alias_1.some_related_thing)
)

session.execute(stmt_1)


# ... later ...

user_alias_2 = aliased(User)
address_alias_2 = aliased(Address)

stmt_2 = select(user_alias_2).options(
     selectinload(user_alias_2.addresses.of_type(address_alias_2))
    .selectinload(address_alias_2.some_related_thing)
)

session.execute(stmt_2)

```

when stmt_2 is executed, the selectinload() options is has will be invoked using the user_alias_1 and address_alias_1 objects as targets, and not the user_alias_2 and address_alias_2.  So SelectInLoader needs to use the **cached** options from stmt_1 for them to match up correctly to the entities given.

But, then for other options that aren't "loader strategies", like the with_loader_criteria() that has a lambda with a closure, we need to use the **uncached** one.   That was the bug here, the decision was not being made to treat `with_loader_criteria()` options as different from loader strategies with regards to this "use the cached option or the uncached option".  The code change basically takes what was a complicated conditional expression and replaces it with a method that's on all the ORMOption objects as a whole to just make the decision which option to use, the cached or the uncached one.

Another way this could all work would be if loader strategies could use the uncached options in all cases, and we figure out a way to get the paths to match up.  That would mean that SelectInLoader could use user_alias_2 and address_alias_2 and the internal mechanics of how they are matched to the options somehow makes use of common structure of user_alias_1 / user_alias_2 instead of matching them up by identity.   That would likely be an improvement here and simplify things, but this stuff is very hard to work on as you can probably see.
