### ISSUE TITLE
improved abstractconcretebase

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8403]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/8402

with not too many changes I can make the use case indicated at #8402 work and our current tests, which I think are kind of minimal, still pass.   Maybe call this AbstractConcreteBaseV2 and have it be experimental for now.   gerrit coming up

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**improve abstractconcretebase** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4041
