### ISSUE TITLE
`with_variant` example in 1.x cannot run

### ISSUE THREAD

**Issue by ljmc-github** [sqlalchemy/sqlalchemy#8408]
### Describe the bug

The example given at 

https://docs.sqlalchemy.org/en/14/core/type_basics.html#using-uppercase-and-backend-specific-types-for-multiple-backends

https://github.com/sqlalchemy/sqlalchemy/blame/main/doc/build/core/type_basics.rst#L130-L159

cannot run with SQLalchemy `1.4.x`, even though it is part of the `14` documentation.

### To Reproduce

```python
from sqlalchemy import MetaData
from sqlalchemy import Table, Column, Integer, String
from sqlalchemy.dialects.mysql import VARCHAR

metadata_obj = MetaData()

user = Table(
    "user",
    metadata_obj,
    Column("user_name", String, primary_key=True),
    Column(
        "bio",
        String(255).with_variant(VARCHAR(255, charset="utf-8"), "mysql", "mariadb"),
    ),
)
```

### Error

```
TypeError: TypeEngine.with_variant() takes 3 positional arguments but 4 were given
``` 

### Versions

- OS: N/A
- Python: 3.10
- SQLAlchemy: 1.4.40
- Database: N/A
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): N/A

**Comment by CaselIT** [comment]
Hi,.
Thanks for reporting. We probably changed the api for v2 and backported the wrong example in 1.4

**Comment by zzzeek** [comment]
woops, I thought I had put that API into 1.4 as well.

**Comment by ljmc-github** [comment]
@CaselIT, I can confirm, API is changed and has a variadic `dialect_names` arguments rather than the single `dialect_name`.

**Comment by CaselIT** [comment]
I think we can revert the docs in 1.4 and keep the current api on 1.4

**Comment by zzzeek** [comment]
that whole page was rewritten so the change cannot be reverted.  i am correcting that issue as well as some other inaccuracies in the example re: mysql/mariadb.

**Comment by zzzeek** [comment]
what's still wrong ?

**Comment by CaselIT** [comment]
I think the issue is in the 1.4 docs and examples are using the v2 api, but the code is still using the old one

**Comment by CaselIT** [comment]
Oh ok, that commit did not show up in the issue
