### ISSUE TITLE
Column's nullable property derived from Mapped annotation is not copied

### ISSUE THREAD

**Issue by lonelyteapot** [sqlalchemy/sqlalchemy#8410]
### Describe the bug

According to the [docs](https://docs.sqlalchemy.org/en/20/orm/declarative_tables.html#mapped-column-derives-the-datatype-and-nullability-from-the-mapped-annotation), `mapped_column()` derives nullability from the `Mapped` annotation if `nullable` argument is not specified.

In this case, `Column._user_defined_nullable` remains `NULL_UNSPECIFIED`.

It appears that `Column.copy()` ignores the actual `nullable` property of the original column, but only uses `_user_defined_nullable`:
https://github.com/sqlalchemy/sqlalchemy/blob/f55ae66f70d6b28fbccd75ac9089f11e951c4c39/lib/sqlalchemy/sql/schema.py#L2243-L2246
The new column's constructor sets `nullable` as if it wasn't specified (usually `True`).

### To Reproduce

```python
from sqlalchemy.orm import Mapped, mapped_column, registry


mapper_registry = registry()


@mapper_registry.mapped
class User:
    __tablename__ = "user"
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]


column = User.name.expression
print(repr(column))  # Column('name', String(), table=<user>, nullable=False)
print(column.nullable)  # False

column_copy = column._copy()
print(repr(column_copy))  # Column('name', String(), table=None)
print(column_copy.nullable)  # True
```

### Error

No errors produced

### Versions

- Python: 3.10.2
- SQLAlchemy: 2.0.0b1 (f55ae66)

### Additional context

This impacts alembic migrations autogen, causing `nullable=True` being set on mapped columns that are not `Optional`.

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting and for testing the v2 version! Feel free to report any other issues you may find, thanks!

**Comment by zzzeek** [comment]
we're setting it after the fact so that the "user defined nullable" field isn't set.   

just as a note these pre-release fixes don't need any changelog.

**Comment by zzzeek** [comment]
also a note, this is **REALLY HARD** to fix.   I might have to add a whole new series of state to everything to track this

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Column._copy() duplicates "user defined" nullable state exactly** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4044

**Comment by zzzeek** [comment]
> also a note, this is **REALLY HARD** to fix. I might have to add a whole new series of state to everything to track this

as we can see, the actual fix is pretty much what @lonelyteapot said to do and not hard at all.  :)  however, I went down a few wrong paths that were fairly chaotic before arriving there.     thanks @lonelyteapot for figuring it out

**Comment by lonelyteapot** [comment]
@zzzeek, thank you for your quick help, as always!
