### ISSUE TITLE
support for multiple statements within query?

### ISSUE THREAD

**Issue by bayesfactor** [sqlalchemy/sqlalchemy#8462]
### Describe the use case

I would like to update multiple rows, for example:
```
update_query = """UPDATE table1 SET col1=val1 WHERE primary_key=pk1;
                  UPDATE table1 SET col1=val2 WHERE primary_key=pk2;"""
eng.execute(update_query)
```

It looks like there was [some discussion in 2013](https://groups.google.com/g/sqlalchemy/c/-8dIb-VX1tI?pli=1). Can this feature request be considered please?

### Databases / Backends / Drivers targeted

MySQL / python / pymysql or pyodbc or ...

### Example Use

SQL looks like:
```
UPDATE table1 SET col1=val1 WHERE primary_key=pk1;
UPDATE table1 SET col1=val2 WHERE primary_key=pk2
```

**Comment by CaselIT** [comment]
Hi,

This depends mainly on the driver used to connect to the db.
If the driver supports it that statement should be executable, since it does not return any row. The number of updated row reported by sqlalchemy will probably be wrong thought

**Comment by zzzeek** [comment]
oh and also, bigger picture.   "I want to update multple rows".  Normally you use [executemany](https://docs.sqlalchemy.org/en/14/tutorial/dbapi_transactions.html#sending-multiple-parameters) for this:

```py
with engine.connect() as conn:
    conn.execute(
        text("UPDATE table1 SET col1=:val WHERE primary_key=:pk"),
        [{"val": val1, "pk": pk1}, {"val": val2, "pk": pk2}]
    )


```
