### ISSUE TITLE
customize the result class returned by `execute`

### ISSUE THREAD

**Issue by davidism** [sqlalchemy/sqlalchemy#8476]
Flask-SQLAlchemy overrides `Session.query_cls` and `RelationshipProperty.query_class` to use a `Query` subclass that provides the methods `get_or_404`, `first_or_404`, `one_or_404`, and `paginate`. Since the `Query` class is legacy in SQLAlchemy 2.0, I want to add these same methods to the `execute(select())` result.

I'd like to create a `Result` subclass with the extra methods, and pass it as `Session.result_class`. Unlike `Query`, `engine.execute` also returns `Result`, so I'd like to customize `Engine.result_class` as well. Since it looks like dynamic relationships will switch to using `select` instead of `query`, I'd also like to customize `RelationshipProperty.result_class`.

```python
@app.route("/user/<username>")
def user_detail(username):
    user = db.session.execute(select(User).filter_by(uesrname=username)).one_or_404()
    ...
```

**Comment by CaselIT** [comment]
Hi,

Not sure how feasible is this request, since there are multiple result classes, not a single one: https://docs.sqlalchemy.org/en/20/core/connections.html?highlight=result#result-set-api

Maybe we could add the ability to wrap a result, so that an extension could obtain the particular instance of result and wrap it in a proxy class that includes additional methods and/or delegates to the original result?

**Comment by davidism** [comment]
I don't think manual wrapping is the correct solution. Flask-SQLAlchemy is fairly hands-off in terms of how SQLAlchemy actually works, the ideal solution is passing in something while configuring the engine/session/etc. that SQLAlchemy will apply automatically.

I'm also fine with saying "adding methods to the result set is not supported, and query is legacy". If it's not planned in SQLAlchemy itself, Flask-SQLAlchemy will follow suite.

We'd probably just provide some helper functions like `db.first_or_404(select)`, `db.paginate(select)`, etc. because those extra result methods are still useful for web applications.

**Comment by CaselIT** [comment]
> I don't think manual wrapping is the correct solution. Flask-SQLAlchemy is fairly hands-off in terms of how SQLAlchemy actually works, the ideal solution is passing in something while configuring the engine/session/etc. that SQLAlchemy will apply automatically.

I was not clear, the wrapping idea I mentioned would be something to pass to the engine / session and sqlalchemy would wrap the results before returning them. 

> I'm also fine with saying "adding methods to the result set is not supported, and query is legacy". If it's not planned in SQLAlchemy itself, Flask-SQLAlchemy will follow suite.

That was not my point, sorry if it did seem that way. I'm just trying to think of possible alternatives to having to provide 5+ result formats. It may well be that the best option is to allow customizing each of them

**Comment by zzzeek** [comment]
> I don't think manual wrapping is the correct solution. Flask-SQLAlchemy is fairly hands-off in terms of how SQLAlchemy actually works, the ideal solution is passing in something while configuring the engine/session/etc. that SQLAlchemy will apply automatically.
> 
> I'm also fine with saying "adding methods to the result set is not supported, and query is legacy". If it's not planned in SQLAlchemy itself, Flask-SQLAlchemy will follow suite.
> 
> We'd probably just provide some helper functions like `db.first_or_404(select)`, `db.paginate(select)`, etc. because those extra result methods are still useful for web applications.

to be honest, one of the many inspirations for Result and moving away from Query types of patterns is to move away from that specific kind of pattern.    If I wanted to have web-specific methods like first_or_404() I would be building my own facade class (i.e. wrapping).

**Comment by davidism** [comment]
Unless you mean my example of just making separate methods on the `db` object, I'm not sure how I would do that though. Would I make a `Session` subclass that overrides `execute` to return a wrapper around the result of `super().execute`?

**Comment by zzzeek** [comment]
if you really wanted it to be Session, then yes, I think that would be how.      sessionmaker() accepts `class_` for this kind of purpose (more for the horizontal sharding extension, but would work here also).

I really dont see "first_or_404()" as appropriate on an ORM Session though, that's a web framework concern.

**Comment by davidism** [comment]
> I really don't see "first_or_404()" as appropriate on an ORM Session though, that's a web framework concern.

I'm good with that, so I'd probably provide some new methods on the extension in that case:

```python
class SQLAlchemy:
   def first_or_404(self, statement):
       result = self.session.execute(statement)
       value = result.first()
       if value is None:
           abort(404)
       return value
```

Just to make sure I understand the facade idea though, is this what you meant?

```python
class ResultWrapper:
    def __init__(self, result):
        self._result = result

    def first_or_404(self):
        value = self._result.first()
        if value is None:
            abort(404)
        return value

    def __getattr__(self, name):
        return getattr(self._result, name)

class Session(sa.orm.Session):
    def execute(self, statement):
        return ResultWrapper(super().execute(statement))
```

**Comment by zzzeek** [comment]
yeah I think that would be it, but it really goes counter to what people would have read in our own tutorials and docs, which causes confusion.

**Comment by davidism** [comment]
We have the same problem on our side, Flask-SQLAlchemy has had `Model.query.get_or_404` etc. for so long that making query legacy while still providing similar features is going counter to everything out there already. But that's the nature of the 2.0 changes anyway, regardless of if users are using Flask or not, so that's why I'm fine with going along with whatever upstream says is the preferred pattern.

Would you recommend that we deprecate `Model.query` too? The SQLAlchemy docs say that `Query` is legacy and will be removed from the docs, but it's not _actually_ deprecated.

**Comment by CaselIT** [comment]
> Would you recommend that we deprecate `Model.query` too? The SQLAlchemy docs say that `Query` is legacy and will be removed from the docs, but it's not _actually_ deprecated.

At the moment there is no plan on deprecating query, since there are millions of lines of code that use it, and it would be very impractical for the users. The current idea is to have it stick around as is, without adding any new functionality to it

**Comment by zzzeek** [comment]
I would be 100% all for if you wanted to remove `Model.query` but your users are **really** into it.  most of our bug reports have ``Model.query`` in their code.   I hate having to rewrite it all the time :)   (yes it was my idea originally, in like, 2007.  so this is all my own fault)

**Comment by davidism** [comment]
Hmm, I'll consider deprecating it. :-) I think I've got my answer though, implement the methods on the extension class for the new execute/select pattern, and keep the query methods for users that like that (for now).
