### ISSUE TITLE
more declarative support for `__init_subclass__`

### ISSUE THREAD

**Issue by davidism** [sqlalchemy/sqlalchemy#8477]
Flask-SQLAlchemy uses a custom `DeclarativeBase` metaclass subclass that handles two special behaviors: setting different metadata based on the `__bind_key__` attribute; and setting a `__tablename__` automatically under certain conditions.

I wanted to try using the `__init_subclass__` special method instead of the custom metaclass. However, `__init_subclass__` runs completely _before_ `metaclass.__init__`, so there's no way to do things before and after that `__init__` like I could when calling `super().__init__` in a custom metaclass.

I was able to implement `__bind_key__` metadata support in `Model.__init_subclass__`, it was enough to set `cls.metadata` from there.

However, `__tablename__` was not possible. I had trouble defining the special `__table_class__` method on the `Model` class, it seems like it must be defined on the `DeclarativeBase` metaclass. I also need to examine the _result_ of `__table_class__` to see what type of table inheritance ended up being used, and unset the generated `__tablename__` and `__table__` in some cases. Since `metaclass.__init__` runs after `__init_subclass__`, that wasn't possible. (Alternatively, if I was able to return a special `NoTable` marker from `__table_class__`, I _think_ that would also solve this. Returning `None` isn't enough.)

Here's a demonstration of the special method order that's causing the issue:

```python
class BaseModel:
    def __init_subclass__(cls, **kwargs):
        print(f"BaseModel.__init_subclass__ {cls.__name__} before")
        super().__init_subclass__(**kwargs)
        print(f"BaseModel.__init_subclass__ {cls.__name__} after")

class DeclarativeMeta(type):
    def __init__(cls, name, bases, d):
        print(f"DeclarativeMeta.__init__ {cls.__name__} before")
        super().__init__(name, bases, d)
        print(f"DeclarativeMeta.__init__ {cls.__name__} after\n")

class Model(BaseModel, metaclass=DeclarativeMeta):
    pass

class User(Model):
    pass
```

```
BaseModel.__init_subclass__ Model before
BaseModel.__init_subclass__ Model after
DeclarativeMeta.__init__ Model before
DeclarativeMeta.__init__ Model after

BaseModel.__init_subclass__ User before
BaseModel.__init_subclass__ User after
DeclarativeMeta.__init__ User before
DeclarativeMeta.__init__ User after
```

Note that the `__init_subclass__` runs completely before `metaclass.__init__`, so it's not possible to modify the result of `__init__` without continuing to use a custom metaclass.

---

Here's a small related side request that you might be interested in as well. `__init_subclass__` also allows "class parameters", so I'm playing around with allowing the following as well:

```python
class User(db.Model, bind_key="auth", table_name="users")
```

Perhaps SQLAlchemy would like to add similar support for its custom dunder attributes such as `__table_args__`, `__tablename__`, etc.

```python
class Model:
    def __init_subclass__(cls, /, table_name=None, table_args=None, mapper_args=None, table=None):
        cls.__tablename__ = table_name
        cls.__table_args__ = table_args
        # etc
```

**Comment by davidism** [comment]
That's true for a trivial `__tablename__` implementation, but we get quite a bit more complex. We automatically support joined/single table inheritance models, look at the MRO, whether `__table__` is set, whether the generated/set table has a primary key, etc. Some of those things can only be known and acted on _after_ SQLAlchemy generates the table, which happens after `__init_subclass__`. https://github.com/pallets-eco/flask-sqlalchemy/blob/2d9257e79b8246632b7518c613fb24bc523f9b1d/src/flask_sqlalchemy/model.py

**Comment by davidism** [comment]
As for the class parameters, I mostly wanted to get a sense of whether SQLAlchemy itself was interested in doing that, to inform whether I added it. I've found it's possible to support both parameter and attribute, preferring one over the other or raising an error if both are set.

**Comment by davidism** [comment]
I'll have to play around with it, but it sounds like you're saying that instead of doing `sa.orm.declarative_base(class_=Model, metaclass=SpecialMeta)`, I could do the same setup that it does and call `registry.mapped` in `Model.__init_subclass__` instead.

**Comment by davidism** [comment]
Where does `registry` come from?

**Comment by zzzeek** [comment]
yes if you are really setting up inheritance and all that, registry has all the new functions and such so that you can build up whatever process you want to get the class in there.

**Comment by davidism** [comment]
Really the only thing I need is to be able to set `__table_class__` on the `Model` class, which doesn't seem to work, and some way to signal from `__table_class__` that no table should be set (which is different than returning `None`). I'm starting to look at the rest of the registry/declarative API, but I'm getting the sense that I'll be going to a lot of work duplicating what `DeclarativeBase` does just to override that one limitation of `DeclarativeBase`.

**Comment by davidism** [comment]
I know this is a really complex topic, it's hard for me to describe. If you have time for a screen share on Discord or somewhere, that might make it easier for me to show what I want.

**Comment by davidism** [comment]
Thanks, after playing around with the registry API the interactions of these different things makes sense now. I'll stick with `DeclarativeMeta`, but it's cool that we can instrument it in other ways, might be useful in Flask-SQLAlchemy down the road.
