### ISSUE TITLE
Joins with polymorphic entities

### ISSUE THREAD

**Issue by torsdag** [sqlalchemy/sqlalchemy#8495]
### Describe the bug

Hi,

Just wanted to clarify this before we start updating a lot of code written towards sqlalchemy 1.2. It is related to a previous question [8473](https://github.com/sqlalchemy/sqlalchemy/issues/8473) and I imagine the response to be the same ie an alias should be used.

Apologies if this is a redundant question but since the behavior has changed between patch releases I feel like it is worth double checking.

The example below works in 1.4.36 resulting in the following query

```
SELECT entity.id AS entity_id, entity.attribute_type AS entity_attribute_type 
FROM entity JOIN (entity AS entity_1 JOIN entity_two AS entity_two_1 ON entity_1.id = entity_two_1.id) ON entity_two_1.id = entity.id 
WHERE entity.id = ?
```

In 1.4.37 and onward the same query results in (the outer join condition references the inner):
```
SELECT entity.id AS entity_id, entity.attribute_type AS entity_attribute_type 
FROM entity JOIN (entity AS entity_1 JOIN entity_two AS entity_two_1 ON entity_1.id = entity_two_1.id) ON entity_two_1.id = entity_1.id 
WHERE entity_1.id = ?
```

We can get around this using an alias, something we want to move towards anyway eventually. Is it correct to assume we should not expect this to work moving forwards?

cheers

### To Reproduce

```python
import sqlalchemy.orm

from sqlalchemy.ext.declarative import (
    declarative_base
)

Base = declarative_base()


class Entity(Base):
    __tablename__ = 'entity'

    id = sqlalchemy.Column(
        sqlalchemy.Integer, primary_key=True
    )

    attribute_type = sqlalchemy.Column(
        sqlalchemy.String(32)
    )

    __mapper_args__ = {
        'polymorphic_on': attribute_type,
        'polymorphic_identity': 'entity'
    }


class EntityTwo(Entity):
    __tablename__ = 'entity_two'

    id = sqlalchemy.Column(
        sqlalchemy.Integer, sqlalchemy.ForeignKey(Entity.id), primary_key=True
    )

    name = sqlalchemy.Column(
        sqlalchemy.String(32)
    )

    __mapper_args__ = {
        'polymorphic_identity': 'entity_two'
    }


engine = sqlalchemy.create_engine(
    'sqlite:///:memory:', echo=True
)

Base.metadata.create_all(engine)

Session = sqlalchemy.orm.sessionmaker(
    bind=engine
)

session = Session()

session.add(
    EntityTwo(
        id=1,
        name='test1'
    )
)
session.add(
    EntityTwo(
        id=2,
        name='test2'

    )
)

session.commit()

result = session.query(
    Entity
).join(
    EntityTwo,
    EntityTwo.id == Entity.id
).filter(
    Entity.id == 1
)

assert(len(result.all()) == 1)
```

### Error

```
test.py:80: SAWarning: An alias is being generated automatically against joined entity mapped class EntityTwo->entity_two due to overlapping tables.  This is a legacy pattern which may be deprecated in a later release.  Use the aliased(<entity>, flat=True) construct explicitly, see the linked example. (Background on this error at: https://sqlalche.me/e/14/xaj2)
  assert(len(result.all()) == 1)
Traceback (most recent call last):
  File "test.py", line 80, in <module>
    assert(len(result.all()) == 1)
AssertionError
``` 

### Versions

- OS: fedora 36
- Python: python 2.7
- SQLAlchemy: sqlalchemy 1.4.41

**Comment by zzzeek** [comment]
hi -

the test case you posted here is virtually identical to the one you posted at https://github.com/sqlalchemy/sqlalchemy/issues/8473#issuecomment-1234293376

```py
result = session.query(
    sqlalchemy.inspect(EntityTwo).primary_key[0]
).join(
    EntityTwo,
    EntityTwo.id == Entity.id
).filter(
    EntityTwo.name == 'test1'
)
```

vs

```py
result = session.query(
    Entity
).join(
    EntityTwo,
    EntityTwo.id == Entity.id
).filter(
    Entity.id == 1
)
```

so yes, same warning, same ambiguity as before that you should now set up a hint for, hope this helps!

**Comment by zzzeek** [comment]
we can define this as "query join() between BaseClass and SubClassThatJoinsOnThatSameBaseClass", at least one needs to be aliased() now to avoid ambiguities.

**Comment by zzzeek** [comment]
the difference between these and #8456 is that #8456 had the other entity enclosed inside of a subquery, which is already an alias().  the intent is clearer on that one, although even in that case, if the inheritance hierarchy is using any kind of with_polymorphic setting on the mapper, you need to use an alias() there as well.

basically we are out of the business of     ``query(BaseEntity, SubClassThatJoinsOnThatSameBaseClass).filter(BaseEntity.foo == 'x').filter(SubClassThatJoinsOnThatSameBaseClass.bar == 'y')``, from a SQL perspective that has the same BaseEntity table stated twice and trying to track which one is which with an anoymously generated alias has been a huge source of bugs-that-only-zzzeek-can-fix-yet-keep-popping-up-over-and-over-again for years.    If anything , it looks like we need to move quicker towards deprecation / removal of that patern.

**Comment by torsdag** [comment]
thank you for the clarification, understand your reasoning!

cheers
