### ISSUE TITLE
Snowflake metadata cache is not working

### ISSUE THREAD

**Issue by sergiotj** [sqlalchemy/sqlalchemy#8500]
### Describe the bug

Hello. Multiple calls to inspector.get_table_names() makes the sqlalchemy query the snowflake multiple times. Also tried to add cache_column_metadata=True to my engine, but the behavior maintains. So, cache is not working as expected in snowflake connection.
Snowflake receives multiple queries like this:

```sql
SHOW /* sqlalchemy:get_table_names */ TABLES IN schema
```

### To Reproduce

```python
from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine

engine = create_engine(URL(
    account = '',
    host = '',
    password = '',
    user = '',
    database = '',
    schema = '',
    warehouse = '',
    role='',
    cache_column_metadata=True
))

from sqlalchemy import inspect
inspector = inspect(engine)

tables = inspector.get_table_names()
```

### Versions

- OS: MacOS M1
- Python: 3.9
- SQLAlchemy: 1.4.39
- Database: Snowflake

**Comment by CaselIT** [comment]
Hi, you need to report this issue in the snowflake sqlalchemy dialect repository, since that's not one of the internal dialects
