### ISSUE TITLE
Support GROUP BY ... WITH ROLLUP in mysql / mariadb

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8503]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/8502

> it's an extension of the GROUP BY clause: https://www.sqltutorial.org/sql-rollup/ and it's only once
> 
> let's add `group_by(.., rollup=True)` as the use case

| database | format                                                                                                        | Notes                      |
|-----------|----------------------------------------------------------------------------|----------------------|
| mssql      | `GROUP BY ROLLUP (Country, Region);` `GROUP BY Country, ROLLUP (Region);` | `func` works, not sure about partial rollup |
| pg          |  `GROUP BY ROLLUP (Country, Region);` `GROUP BY Country, ROLLUP (Region);` | `func` works|
| oracle    |  `GROUP BY ROLLUP (Country, Region);` `GROUP BY Country, ROLLUP (Region);` | `func` works|
| mariadb/mysql |  `GROUP BY Country, Region WITH  ROLLUP`  | does its own thing: https://mariadb.com/kb/en/select-with-rollup/|

**Comment by CaselIT** [comment]
The above syntax seems not sufficient, at least for postgresql, that can do things like `GROUP BY foo, ROLLUP bar` https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-rollup/

I think also oracle can support something similar, since it seems that's treated like a function. I'll try finding links for the various dbs

**Comment by CaselIT** [comment]
It seems that only mysql and mariadb require special syntax, the other dbs use rollup as a function.

So the flag should be `mysql_rollup/mariadb_rollup`

**Comment by zzzeek** [comment]
> It seems that only mysql and mariadb require special syntax, the other dbs use rollup as a function.
> 
> So the flag should be `mysql_rollup/mariadb_rollup`

that would make it impossible to use ROLLUP in a database-agnostic way, and I dont see a need for that here.   Looking at what ROLLUP does, it's very oriented towards reporting of subtotals and grant totals and generates additional rows that are pretty artificial looking, one for each totalling of fields with NULL inside each field that was "rolled up".    The "partial rollup" referred towards at https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-rollup/ from what I can see simply omits some of those manufactured rows.      I think for normal use cases, doing "group_by(..., rollup=True)" is pretty functional and more declarative, and in the `:param rollup:` doc, we can mention that to do partial rollup, use `func.rollup()` instead.

the tutorial above seems to have two versions, https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-rollup/ and https://www.sqltutorial.org/sql-rollup/ which while they are different domains are obviously the same site.    the "partial rollup" is kind of a special case, so given MySQL/ MariaDB's syntax (I checked mariadb also to make sure they dont have something different) as well as the usual use for this, a rollup=True flag should solve the problem in the usual case.

**Comment by CaselIT** [comment]
I'm not sure about the `roolup=True`, it seems kind of half backed. The issue here seems mainly that mysql/mariadb decided to do something arbitrary and different from the standard.

Maybe we could just add a custom rollup compilation for the mariadb/mysql dialect that does `c1, c2 with rollup` instead of `rollup(c1,c2)` ? I don't thing there is a rollup function that can be used on select

As an alternative, considering that the full spec seems to be what's supported by (and I think the sql spec)
- postgresql https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-GROUPING-SETS
- mssql https://docs.microsoft.com/en-us/sql/t-sql/queries/select-group-by-transact-sql?view=sql-server-ver16

maybe a grouping set construct makes more sense?

**Comment by zzzeek** [comment]
we have grouping sets

```py
>>> from sqlalchemy import table, column, func, select
>>> t = table('t', column('x'), column('y'), column('z'))
>>> stmt = select(func.sum(t.c.x), t.c['y', 'z']).group_by(func.grouping_sets(*t.c['y', 'z']))
>>> print(stmt)
SELECT sum(t.x) AS sum_1, t.y, t.z 
FROM t GROUP BY GROUPING SETS(t.y, t.z)
```

the thing that is making this not feel like `rollup(x, y)` for MySQL / MariaDB is that "WITH ROLLUP" has no concept of grouping on the columns.   if someone says `group_by(rollup(x), rollup(y))` for example.     

Can we just do this then, this will just do what people want for the normal rollup case

```py
diff --git a/lib/sqlalchemy/dialects/mysql/base.py b/lib/sqlalchemy/dialects/mysql/base.py
index 6aeb231fa7..fa51979b97 100644
--- a/lib/sqlalchemy/dialects/mysql/base.py
+++ b/lib/sqlalchemy/dialects/mysql/base.py
@@ -1210,6 +1210,14 @@ class MySQLCompiler(compiler.SQLCompiler):
     def visit_random_func(self, fn, **kw):
         return "rand%s" % self.function_argspec(fn)
 
+    def visit_rollup_func(self, fn, **kw):
+        return "%s WITH ROLLUP" % (
+            ", ".join(
+                elem._compiler_dispatch(self, **kw)
+                for elem in fn.clauses
+            )
+        )
+
     def visit_sequence(self, seq, **kw):
         return "nextval(%s)" % self.preparer.format_sequence(seq)
 
```

```py
>>> from sqlalchemy import table, column, func, select
>>> from sqlalchemy.dialects import mysql
>>> t = table('t', column('x'), column('y'), column('z'))
>>> stmt = select(func.sum(t.c.x), t.c['y', 'z']).group_by(func.rollup(*t.c['y', 'z']))
>>> print(stmt)
SELECT sum(t.x) AS sum_1, t.y, t.z 
FROM t GROUP BY ROLLUP(t.y, t.z)
>>> print(stmt.compile(dialect=mysql.dialect()))
SELECT sum(t.x) AS sum_1, t.y, t.z 
FROM t GROUP BY t.y, t.z WITH ROLLUP
```

Basically I dont want a "mysql" keyword / import out front on this because the vastly most common use case here is common to all backends

**Comment by CaselIT** [comment]
> we have grouping sets

oh right, I did not think that grouping sets are functions

>  if someone says group_by(rollup(x), rollup(y)) for example.

Indeed that will not work on mysql, but I don't think that syntax is supported even when doing an sql string.
It does on postgresql, but it seems like it would return the "wrong" data.

I kind of like the func solution better.

**Comment by zzzeek** [comment]
sure we can do that then

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Support GROUP BY ROLLUP on MySql/MariaDB** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4072

**Comment by martin-greentrax** [comment]
You are awesome, thank you very much for your work!

**Comment by necro42** [comment]
Does this feature work now?
Version 1.4.44 but it doesn't work.
Do I need to set something up?

**Comment by CaselIT** [comment]
This was added to the version 2 that's currently on beta
