### ISSUE TITLE
Malformed query with Sequence()

### ISSUE THREAD

**Issue by pavelschon** [sqlalchemy/sqlalchemy#8515]
### Describe the bug

Malformed query has been rendered if used Sequence and literal_binds.

### To Reproduce

```python
#!/usr/bin/env python3.9
from sqlalchemy import Table, Integer, Column, String, insert, Sequence, MetaData
from sqlalchemy.dialects import postgresql

metadata = MetaData()

table = Table('Test', metadata,
    Column('pk', Integer, Sequence("pk_seq"), primary_key=True),
    Column('name', String),
)

statement = insert(table).values([{ 'name': name } for name in ['foo', 'bar', 'baz']])

print(statement.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True}))
```

### Error

Output:
```
INSERT INTO "Test" (pk, name) VALUES (nextval('pk_seq'), 'foo'), (%(pk_m1)s, 'bar'), (%(pk_m2)s, 'baz')
``` 
As you can see, the `nextval()` is applied only on the first value, remaining values are not rendered.

### Versions

- OS: Ubuntu 22.04
- Python: 3.9
- SQLAlchemy: 1.3.24
- Database: Postgresql

### Additional context

No database is needed in order to reproduce issue.

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. This is fixed in the 1.4 series.
Running the same example will print the correct
```
INSERT INTO "Test" (pk, name) VALUES (nextval('pk_seq'), 'foo'), (nextval('pk_seq'), 'bar'), (nextval('pk_seq'), 'baz')
```

Not sure if it will be fixed in the 1.3 series. cc @zzzeek

**Comment by zzzeek** [comment]
the behavior here has changed a few times since 1.3 however the ultimate fix is specific to sequence and is in #6361.

if you are writing new SQLAlchemy code it is imperative that you first upgrade your application to the latest release series before making use of new behaviors.

**Comment by CaselIT** [comment]
for a further workaround you can refer to this comment https://github.com/sqlalchemy/sqlalchemy/issues/6361#issuecomment-827016729

**Comment by pavelschon** [comment]
Thank you guys.
