### ISSUE TITLE
pool_size=0 means empty pool instead of unlimited pool as documentation says

### ISSUE THREAD

**Issue by marcinbarczynski** [sqlalchemy/sqlalchemy#8523]
### Describe the bug

According to https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.pool_size setting `pool_size` size 0 means that the pool is unlimited. I expected that `max_overflow` is ignored in such a case and the pool size will increase when necessary and never decrease. Hence, it will always be equal to the peak demand for connections.

However, the following code hangs on the query which suggests `pool_size=0` means empty pool.

### To Reproduce

```python
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import QueuePool

engine = create_engine(
    "PG_URI",
    echo=True,
    pool_size=0,
    max_overflow=0,
    poolclass=QueuePool,
)
Session = sessionmaker(bind=engine)
session = Session()

session.execute("SELECT 1")
```

### Error

The code hangs.

### Versions

- OS: Ubuntu
- Python: 3.10
- SQLAlchemy: 1.4.41
- Database: PostgreSQL 13
- DBAPI: psycopg2

### Additional context

As connections are created lazily, unlimited pool size can be emulated by setting `pool_size` to a huge number. Maybe it's just a documentation issue.

**Comment by zzzeek** [comment]
this has never been tested before.   has same behavior going back many years.

set max_overflow=-1 for this to work as expected.     im going to milestone this to 2.0 otherwise as this is easily worked around for now.


```diff
diff --git a/lib/sqlalchemy/pool/impl.py b/lib/sqlalchemy/pool/impl.py
index 91d0290955..cc7df3b48d 100644
--- a/lib/sqlalchemy/pool/impl.py
+++ b/lib/sqlalchemy/pool/impl.py
@@ -103,7 +103,10 @@ class QueuePool(Pool):
         Pool.__init__(self, creator, **kw)
         self._pool = self._queue_class(pool_size, use_lifo=use_lifo)
         self._overflow = 0 - pool_size
-        self._max_overflow = max_overflow
+        if pool_size == 0:
+            self._max_overflow = -1
+        else:
+            self._max_overflow = max_overflow
         self._timeout = timeout
         self._overflow_lock = threading.Lock()
 
@@ -217,7 +220,7 @@ class QueuePool(Pool):
         return self._pool.qsize()
 
     def overflow(self):
-        return self._overflow
+        return self._overflow if self._pool.maxsize else 0
 
     def checkedout(self):
         return self._pool.maxsize - self._pool.qsize() + self._overflow
```

**Comment by CaselIT** [comment]
I'll move it in gerrit, but I'm not sure what test we should do here

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Ignore max_overflow when pool_size is 0** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4081
