### ISSUE TITLE
Typo in API docs

### ISSUE THREAD

**Issue by jenstroeger** [sqlalchemy/sqlalchemy#8527]
### Describe the bug

The example in [Redefining Comparison Operations for Composites](https://docs.sqlalchemy.org/en/14/orm/composites.html#redefining-comparison-operations-for-composites) contains this code:
```python
class Vertex(Base):
    ___tablename__ = "vertices"
```
Notice the three `_` before `tablename` — should be two.

### To Reproduce

```python
n/a
```

### Error

n/a

### Versions

Online.

### Additional context

Need a PR? 😁

**Comment by CaselIT** [comment]
Hi,

Shure, feel free to open a PR.
For documentation issue you can also just open a PR!
thanks

**Comment by jenstroeger** [comment]
@CaselIT thanks for that. I looks like the typo is in v1.4 (`rel_1_4` branch)

https://github.com/sqlalchemy/sqlalchemy/blob/3bd8a3625f17b124557b0d3346c51b39782a9fb6/doc/build/orm/composites.rst?plain=1#L146-L147

but not in `main`. I’ve not checked the other branches, and not sure they matter?

What’s your recommendation?

**Comment by CaselIT** [comment]
It's fine to just open a pr from rel_14

**Comment by CaselIT** [comment]
Thanks for reporting

**Comment by jenstroeger** [comment]
Beat me to it, that was on my list for today! My one-byte contribution to this marvelous package 😁

**Comment by jenstroeger** [comment]
Uhm… @CaselIT the referenced commit doesn’t address the `___tablename__` issue, but two others?

**Comment by CaselIT** [comment]
the one on the 1.4 branch is the other one linked 02b1ed522038cbe90f9548c49ce41c29fc68032c
