### ISSUE TITLE
'SELECT *' causes 'Ambiguous column name' error when accessing returned rows

### ISSUE THREAD

**Issue by N-Maas** [sqlalchemy/sqlalchemy#8536]
### Describe the bug

When using a query of the form `SELECT *, some_column FROM some_table` (in sqlalchemy core via `text('*')`), `some_column` is not accessible by name in the returned rows.

Also, the error does not appear for a specific ordering combined with `label` (see code example).

### To Reproduce

```python
from sqlalchemy import select, text
from sqlalchemy.engine.base import Connection

some_table = # initialize table with column 'some_col'
connection = # get a database connection

stmt = select(some_table.c.some_col, text('*')).select_from(some_table)
row = connection.execute(stmt).first()
print(row.some_col)  # sqlalchemy.exc.InvalidRequestError: Ambiguous column name

stmt = select(text('*'), some_table.c.some_col).select_from(some_table)
row = connection.execute(stmt).first()
print(row.some_col)  # sqlalchemy.exc.InvalidRequestError: Ambiguous column name

stmt = select(text('*'), some_table.c.some_col.label("label")).select_from(some_table)
row = connection.execute(stmt).first()
print(row.label)  # sqlalchemy.exc.InvalidRequestError: Ambiguous column name

stmt = select(some_table.c.some_col.label("label"), text('*')).select_from(some_table)
row = connection.execute(stmt).first()
print(row.label)  # WORKS!
```

### Error

```
  File "/home/***/.local/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 625, in _raise_for_ambiguous_column_name
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Ambiguous column name 'some_column' in result set column descriptions
``` 

### Versions

- OS: Debian GNU/Linux 11 (bullseye)
- Python: 3.9.2
- SQLAlchemy: 1.4.29
- Database: PSQL 13.8
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg2

**Comment by zzzeek** [comment]
that's an abusive case as throwing a star in there makes it extremely difficult for the compiled SQL to be matched to the cursor.description, which prefers to match things positionally, however I have added additional detection for this case where it will use name matching rather than positional matching.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**break out text() from TextualSelect for col matching** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4086

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**break out text() from TextualSelect for col matching** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4087
