### ISSUE TITLE
Literals in SELECT columns incorrectly converted to strings

### ISSUE THREAD

**Issue by TallJimbo** [sqlalchemy/sqlalchemy#8539]
### Describe the bug

PostgreSQL range literals that appear in the SELECT clause (i.e. result columns) of a query are converted to strings as they would be when actually being passed to the database, but are not converted back to `psycopg2.extras.NumericRange` instances as result values usually are.

### To Reproduce

```python
import sqlalchemy.dialects.postgresql
from psycopg2.extras import NumericRange


engine = sqlalchemy.engine.create_engine("postgresql://user:pass@localhost:5432/db")

query = sqlalchemy.sql.select(
    [
        sqlalchemy.sql.literal(
            NumericRange(lower=4, upper=8), type_=sqlalchemy.dialects.postgresql.INT8RANGE
        ).label("a")
    ]
)
with engine.begin() as connection:
    row = connection.execute(query).fetchone()
assert isinstance(row.a, NumericRange), f"{type(row.a)} is not an instance of NumericRange"
```

### Error

Expected assertion not to be triggered, by either passing the literal through as-is or having it converted it back from a string to a `NumericRange`.

### Versions

- OS: Linux Mint 21
- Python: 3.10
- SQLAlchemy: 1.4.41
- Database: PostgreSQL
- DBAPI: psycopg2

### Additional context

I also see the problem when the literal is just one of several columns in the SELECT clause and the others are "real" columns from a real table.

From inspecting the query that is actually executed it seems the literal column is cleverly elided rather than actually included, but I haven't been able to track down where the literal value is instead injected into the result row objects, or why it's being converted one way rather than not at all or both ways (which would at least be correct, if inefficient).

Another possible factor is that this is really a psycopg2 custom type in terms of where the conversion to/from strings happens (the SQLAlchemy type wrapper only exists to define some operators).

**Comment by zzzeek** [comment]
the PG drivers do the range there and they pass them as strings.  The database has no way to know , returning it back, that this is not a string.  so you need to cast things like this:

```py
query = sqlalchemy.sql.select(
        sqlalchemy.cast(sqlalchemy.sql.literal(
            NumericRange(lower=4, upper=8),
        ), type_=sqlalchemy.dialects.postgresql.INT8RANGE).label("a")
)
```

same goes for other "composed" values like JSON, HSTORE, etc.   the database doesn't know what these are without a database table column present.
