### ISSUE TITLE
remove URL.__str__ so that it uses __repr__, which will obfuscate PW by default

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8567]
Discussed in #8547

working on this in #8563

needs some alembic test suite updates.

This change might be a big bump for some, as it is for us.

**Comment by sqla-tester** [comment]
**Yassen Damyanov** has proposed a fix for this issue in the **main** branch:

**Tighten password security by removing `URL.__str__`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4090

**Comment by zzzeek** [comment]
as predicted, it seems likely that flask-migrate has a regression due to this, see https://github.com/sqlalchemy/sqlalchemy/discussions/9225#discussioncomment-4853537 where user w/ flask-migrate has sudden authentication failure, yet the database name and driver are being maintained in the URL.    suggesting the password has been obfuscated.
