### ISSUE TITLE
Support cache generation when aggregate_order_by is used in a query

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8574]
Currently `aggregate_order_by` does not support query generation.

It should be improved so that it does.
This is useful for #8561

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**`aggregate_order_by` now supports cache generation.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4098

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**`aggregate_order_by` now supports cache generation.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4099
