### ISSUE TITLE
`validates` makes function untyped

### ISSUE THREAD

**Issue by ZanderBrown** [sqlalchemy/sqlalchemy#8577]
Use of `sqlalchemy.orm.validates` triggers

```
error: Untyped decorator makes function "<func>" untyped
```

In practice it's a harmless distraction, but annoying nevertheless

**Comment by zzzeek** [comment]
great was about to tell you to make a bug report, these are all bugs now for 2.0

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add typing for sqlalchemy.orm.validates** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4103
