### ISSUE TITLE
Type execution options

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8605]
Improve typing of `execution_options()` method using `if TYPE_CHECKING` block, to avoid changing the implementation

Also makes sense to have typed dict with the execution options to use when passing them around as a dict

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improve typings of execution options** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4133
