### ISSUE TITLE
Add Protocol to represent a mapped class

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8624]
The protocol would basically provide the attributes listed here https://docs.sqlalchemy.org/en/14/orm/mapping_styles.html#runtime-introspection-of-mapped-classes-instances-and-mappers

It's called "MappedClass"

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add public protocol for mapped class** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4377
