### ISSUE TITLE
SQLAlchemy 2 RC is out. Help by testing on your project!

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8631]
Version 2 brings a lot of changes, and it would be very helpful if as many people as possible test the beta to help in fixing issues before the official release.

You can install with `pip install SQLAlchemy==2.0.0rc2`

What's new: https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html
Migration from 1.4: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html
Changelog: https://docs.sqlalchemy.org/en/20/changelog/changelog_20.html

**Comment by malikovss** [comment]
Hi there!
I'm facing with this warning

![image](https://user-images.githubusercontent.com/47824375/197238773-fa8c2689-bed8-4b85-98dd-e8ac85a1c11b.png)

`Expected type 'str | Type[TypeEngine] | TypeEngine | SchemaEventTarget | None', got 'ForeignKey' instead`

**Comment by zzzeek** [comment]
> Hi there! I'm facing with this warning
> 
> ![image](https://user-images.githubusercontent.com/47824375/197238773-fa8c2689-bed8-4b85-98dd-e8ac85a1c11b.png)
> 
> `Expected type 'str | Type[TypeEngine] | TypeEngine | SchemaEventTarget | None', got 'ForeignKey' instead`
> 
> I was following the documentation

Hi -

your screenshot shows the correct form and I can't reproduce that with pylance strict or mypy.   is it possible that you are importing "Column" as "mapped_column()" ?    other than that, look for stubs that may be in use by your tools.

**Comment by zzzeek** [comment]
also make sure ForeignKey is correctly imported as "from sqlalchemy import ForeignKey"

**Comment by cdcadman** [comment]
Hi, I came across some code that is breaking in 2.0.0b1 while trying to get a test to work.  At the end of the test, the sqlite database file needs to be cleaned up, but there is a lock on the file.  Here is an example script:

```
from pathlib import Path
import sqlalchemy as sa

metadata = sa.MetaData()

user = sa.Table(
    "user",
    metadata,
    sa.Column("user_id", sa.Integer, primary_key=True),
    sa.Column("user_name", sa.String(16), nullable=False),
    sa.Column("email_address", sa.String(60)),
    sa.Column("nickname", sa.String(50), nullable=False),
)

db_file = Path(r"C:\Temp\test.db")
db_file.unlink(missing_ok=True)
db_uri = "sqlite:///" + str(db_file)
engine = sa.create_engine(db_uri)
user.create(bind=engine)
db_file.unlink()
```

This works on 1.4.42, but fails on 2.0.0b1, running on Windows 11 with python 3.10.2:

```
Traceback (most recent call last):
  File "C:\Temp\test_sq20.py", line 20, in <module>
    db_file.unlink()
  File "C:\Program Files\Python310\lib\pathlib.py", line 1204, in unlink
    self._accessor.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Temp\\test.db'
```

**Comment by zzzeek** [comment]
@cdcadman try calling engine.dispose() before unlinking the file.    2.0 has switched SQLite to use [QueuePool](https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#the-sqlite-dialect-uses-queuepool-for-file-based-databases)

**Comment by cdcadman** [comment]
@zzzeek , that worked, thanks!

**Comment by peterschutt** [comment]
I've run into what I think may be an issue with forward ref resolution in 2.0. 

I've put an MVCE here: https://github.com/peterschutt/sqla-mvce.

If a base class defines a column that isn't a builtin, resolving the forward ref seems to fail as it tries to resolve the type in the subclass module, not the base class module.

I have `app/lib/orm.py` with a base class that defines a `UUID` pk column. In `app/lib/domain.py` I import that base and use it to define an `Author` class.

This is the traceback:

```python-traceback
Traceback (most recent call last):
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/util/typing.py", line 118, in de_stringify_annotation
    annotation = eval(annotation, base_globals, None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'UUID' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/PycharmProjects/sqla-test/main.py", line 1, in <module>
    from lib.domain import Author
  File "/home/peter/PycharmProjects/sqla-test/lib/domain.py", line 6, in <module>
    class Author(Base):
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_api.py", line 701, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 207, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 288, in setup_mapping
    return _ClassScanMapperConfig(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 523, in __init__
    self._extract_mappable_attributes()
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/decl_base.py", line 1278, in _extract_mappable_attributes
    value.declarative_scan(
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/properties.py", line 660, in declarative_scan
    self._init_column_for_annotation(
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/orm/properties.py", line 686, in _init_column_for_annotation
    argument = de_stringify_annotation(cls, argument)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/PycharmProjects/sqla-test/.venv/lib/python3.11/site-packages/sqlalchemy/util/typing.py", line 120, in de_stringify_annotation
    raise NameError(
NameError: Could not de-stringify annotation UUID
```

Sorry in advance if I'm doing something incorrect!

**Comment by CaselIT** [comment]
This seems a bug or at least something that should be documented. Can you open a new issue?

**Comment by peterschutt** [comment]
> This seems a bug or at least something that should be documented. Can you open a new issue?

[Done](https://github.com/sqlalchemy/sqlalchemy/issues/8742). LMK if anything I can do to help. Cheers.

**Comment by bryanforbes** [comment]
I'm getting an error in pyright passing a `lambda` returning `list[UnaryExpression[int] | UnaryExpression[int | None]]` to `relationship.order_by`:

```python
class One(Base):
    __tablename__ = 'ones'

    id: Mapped[int] = mapped_column(Integer, primary_key=True, init=False)
    two_id: Mapped[int] = mapped_column(
        Integer, ForeignKey('twos.id'), nullable=False
    )
    sortable: Mapped[int] = mapped_column(Integer, nullable=False)
    second_sortable: Mapped[int | None] = mapped_column(Integer)

class Two(Base):
    __tablename__ = 'twos'

    id: Mapped[int] = mapped_column(Integer, primary_key=True, init=False)
    ones: Mapped[list[One]] = relationship(
        One,
        order_by=lambda: [  # error here
            One.sortable.asc(),
            One.second_sortable.asc().nulls_first()
        ],
        lazy='raise'
    )
```

The error is the following:

```
Argument of type "() -> list[UnaryExpression[int] | UnaryExpression[int | None]]" cannot be assigned to parameter "order_by" of type "_ORMOrderByArgument" in function "relationship"
    Type "() -> list[UnaryExpression[int] | UnaryExpression[int | None]]" cannot be assigned to type "_ORMOrderByArgument"
      "object" is incompatible with "str"
      "object" is incompatible with "ColumnElement[Any]"
      "object" is incompatible with protocol "_HasClauseElement"
        "__clause_element__" is not present
      "object" is incompatible with "ExpressionElementRole[Any]"
      Type "() -> list[UnaryExpression[int] | UnaryExpression[int | None]]" cannot be assigned to type "() -> ColumnElement[Any]"
        Function return type "list[UnaryExpression[int] | UnaryExpression[int | None]]" is incompatible with type "ColumnElement[Any]"
```

I did a little poking and it looks like `_ColumnExpressionArgument` includes `Callable[[], "ColumnElement[_T]"]`, so I imagine `_ORMOrderByArgument` needs `Callable[[], Iterable[ColumnElement[Any]]]`.

**Comment by bryanforbes** [comment]
When I import and use `sqlalchemy.dialects.postgresql.insert`, pyright (in strict mode) complains that the types of `insert` and `Insert.on_conflict_do_update()` are partially unknown. Can the argument types be added to those functions?

**Comment by bryanforbes** [comment]
There's a fairly large open question about [descriptors and protocols](https://github.com/python/typing/discussions/1123) that needs to be answered. Essentially, the canonical way to declare a protocol attribute as read-only is to declare it as a read-only `@property`, but both mypy and pyright reject passing instances using descriptors for those attributes. It would be good to get your influence behind this discussion so we can get an answer.

**Comment by CaselIT** [comment]
Hey Bryan!



> When I import and use `sqlalchemy.dialects.postgresql.insert`, pyright (in strict mode) complains that the types of `insert` and `Insert.on_conflict_do_update()` are partially unknown. Can the argument types be added to those functions?

the `dialects.*` package is not really typed at the moment, so for the moment I think it would be expected. The plain is I think to add them during the 2.0.x releases, once most other things are figured out.

If you have some time to spare to start adding them maybe on the public interfaces, like the `insert` method fell free to open a PR!



> There's a fairly large open question about [descriptors and protocols](https://github.com/python/typing/discussions/1123) that needs to be answered. Essentially, the canonical way to declare a protocol attribute as read-only is to declare it as a read-only `@property`, but both mypy and pyright reject passing instances using descriptors for those attributes. It would be good to get your influence behind this discussion so we can get an answer.

off the top of my head I don't think sqlalchemy uses that pattern at the moment. Not many protocols are used in the code

**Comment by bryanforbes** [comment]
I've found a couple more issues.

First, using `Mapping[dict[str, str] | None]` throws `sqlalchemy.exc.ArgumentError` (but using `Mapping[dict[str, str]]` does not):

```python
from __future__ import annotations

from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column


class Base(MappedAsDataclass, DeclarativeBase):
    ...


class A(Base):
    __tablename__ = 'a'

    id: Mapped[int] = mapped_column(primary_key=True)
    has_something: Mapped[bool | None]
    json: Mapped[dict[str, str] | None] = mapped_column(JSONB(none_as_null=True))
```

Second, how do I reference a mapped column in a `Computed` column? I have the following:

```python
from __future__ import annotations

from sqlalchemy import Computed, String, func, text
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column


class Base(MappedAsDataclass, DeclarativeBase):
    ...


class A(Base):
    __tablename__ = 'a'

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]

    sortable_name: Mapped[str] = mapped_column(
        String,
        Computed(
            func.regexp_replace(
                name,  # NameError: 'name' not defined
                text(r"'^(the|an?)\s+(.*)$'"),
                text(r"'\2, \1'"),
                text("'i'"),
            )
        ),
        init=False,
    )
```

I can add `= mapped_column()` after the `name` declaration in the class, or I could pass `text("name")` to `regexp_replace()`, but both of those seem redundant. Is there a better way?

**Comment by CaselIT** [comment]
> First, using Mapping[dict[str, str] | None] throws sqlalchemy.exc.ArgumentError (but using Mapping[dict[str, str]] does not):

That's another issue (feel free to open issues for things that look like issues)

> Second, how do I reference a mapped column in a `Computed` column? I have the following:
> 
> ```python
> from __future__ import annotations
> 
> from sqlalchemy import Computed, String, func, text
> from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column
> 
> 
> class Base(MappedAsDataclass, DeclarativeBase):
>     ...
> 
> 
> class A(Base):
>     __tablename__ = 'a'
> 
>     id: Mapped[int] = mapped_column(primary_key=True)
>     name: Mapped[str]
> 
>     sortable_name: Mapped[str] = mapped_column(
>         String,
>         Computed(
>             func.regexp_replace(
>                 name,  # NameError: 'name' not defined
>                 text(r"'^(the|an?)\s+(.*)$'"),
>                 text(r"'\2, \1'"),
>                 text("'i'"),
>             )
>         ),
>         init=False,
>     )
> ```
> 
> I can add `= mapped_column()` after the `name` declaration in the class, or I could pass `text("name")` to `regexp_replace()`, but both of those seem redundant. Is there a better way?

I don't think there is anything sqlalchemy can do here, since this how python works. do use  `= mapped_column()`

**Comment by bryanforbes** [comment]
@CaselIT Thanks for the help!!

**Comment by zzzeek** [comment]
1.3 is just about effectively EOL as we aren't releasing anything new for 1.3, and have not for a few years now.    my hopes for SQLAlchemy 2 are early next year, January was hoped but that may be optimistic.

**Comment by tal-chan** [comment]
@zzzeek Thank you for your quick answer !

**Comment by amotl** [comment]
Dear Federico and Mike,

first of all, thank you very much for all the efforts you are pouring into SQLAlchemy, and congratulations for the upcoming SQLAlchemy 2.0. Hereby, I just want to report about a little detail on this topic.

We've recently worked on corresponding support at https://github.com/crate/crate-python/pull/485 and https://github.com/crate/crate-python/pull/488, and everything worked well so far. You did an excellent job there.

Now, we just want to make sure our observations are correct, that code written for SQLAlchemy 2.0 will no longer be compatible with SQLAlchemy 1.3 (https://github.com/crate/crate-python/issues/494)?

On the one hand, it might have been obvious, because [SQLAlchemy 1.3 is effectively EOL](https://github.com/sqlalchemy/sqlalchemy/issues/8631#issuecomment-1329264864). On the other hand, do you think it might make sense to explicitly add this detail more prominently to the documentation somewhere on `{whatsnew,migration,changelog}_20`?

Keep up the spirit and with kind regards,
Andreas.

**Comment by zzzeek** [comment]
It's possible to have code that is compatible with 2.0 and 1.3 at the same time, you would just need to ensure you use the subset of features and APIs that are common to both.  Alembic is continuing SQLAlchemy 1.3 compatibility for the time being and it's still part of our test suite.     

that said, if you want to use SQLAlchemy features that are new in 1.4 or 2.0, like async support or features like with_loader_criteria() or the do_orm_execute() event hook, then that part of the code would not work with SQLAlchemy 1.3.  

so it depends on what SQLAlchemy behaviors and features you rely upon.  

I dont have any notion of how to go about listing every feature in SQLAlchemy 2.0 and commenting on its compatibility with SQLAlchemy 1.3; SQLAlchemy 2.0 is compared to version 1.4, and version 1.4 is compared to version 1.3.  We have migration guides that go between each version.

**Comment by CaselIT** [comment]
> Alembic is continuing SQLAlchemy 1.3 compatibility for the time being and it's still part of our test suite.

In particular this is the compat file used by alembic: https://github.com/sqlalchemy/alembic/blob/main/alembic/util/sqla_compat.py
In particular for the select it has https://github.com/sqlalchemy/alembic/blob/b1fad6b6b2865bb59660d9d2a1cd74c16c4cf4bd/alembic/util/sqla_compat.py#L557-L558
while it does not use declaratie base you you could use the classing `try / except ImportError` fallback that's usual in python

**Comment by amotl** [comment]
Hi again,

thank you very much for your quick responses. We followed your advises at https://github.com/crate/crate-python/pull/497, where we also added a [small compatibility module](https://github.com/crate/crate-python/blob/67a4cf26bc328a3377da651036ce3e442df1e5aa/src/crate/client/sqlalchemy/compat/api13.py), inspired by your pointers, which particularly fits our needs of making a slightly modernized SQLAlchemy dialect (and test suite) compatible with SQLAlchemy 1.3 again on two details [^1]. Maybe this is useful for others facing the same situation.

With kind regards,
Andreas.

[^1]: 1. Add the `exec_driver_sql()` method to SQLAlchemy's `Connection` and `Engine`.
      2. Amend the `sql.select()` function to accept the calling semantics of the modern variant.

**Comment by DanCardin** [comment]
I noticed the `quote` argument to `CreateSchema` was removed [here](https://github.com/sqlalchemy/sqlalchemy/commit/b6eed88ef4ebb3fd7035b4e366bf6653ebb26d15) with no context/rationale given.

We have an existing usage of `quote=True` in code that would ideally support 1.3/1.4/2.0, but I dont know that i have any concrete test cases proving whether the default behavior correctly quotes when required and why I would care to set the parameter. Should I care?

**Comment by CaselIT** [comment]
I think the reason is that it was not used by the compiler, so that issue was used to do some clean-up.
Do you have an use case that's not working correctly in sqlalchemy v2?

**Comment by DanCardin** [comment]
Just tested `CreateSchema("table", quote=False)` in 1.3/1.4 and it appears to work, so 🤷 ignore this i guess. Just checking that our usage of quote in prior versions was unwarranted. Thanks!

**Comment by om26er** [comment]
I have been using the RC1 in one of our projects, so far so good. However I see this error message in PG logs now when my service starts
```
st-cloud-postgres-1  | 2023-01-02 15:25:45.844 UTC [391] ERROR:  type "hstore" does not exist
st-cloud-postgres-1  | 2023-01-02 15:25:45.844 UTC [391] CONTEXT:  unnamed portal parameter $1 = '...'
st-cloud-postgres-1  | 2023-01-02 15:25:45.844 UTC [391] STATEMENT:  SELECT
st-cloud-postgres-1  | 	    typname AS name, oid, typarray AS array_oid,
st-cloud-postgres-1  | 	    oid::regtype::text AS regtype, typdelim AS delimiter
st-cloud-postgres-1  | 	FROM pg_type t
st-cloud-postgres-1  | 	WHERE t.oid = $1::regtype
st-cloud-postgres-1  | 	ORDER BY t.oid
st-cloud-postgres-1  |
```

**Comment by CaselIT** [comment]
Hi, that seems something that the driver (I'm assuming asyncpg) is issuing to get the information about hstore. I think you can safely ignore it.

**Comment by om26er** [comment]
So that only happens when using `psycopg` as the pg driver. I just tried `asyncpg` and it does not happen there. cc @dvarrazzo, maybe that's harmless but worth a mention

**Comment by dvarrazzo** [comment]
> I have been using the RC1 in one of our projects, so far so good. However I see this error message in PG logs now when my service starts. That happens on await conn.run_sync(Base.metadata.create_all)
> 
> ```
> st-cloud-postgres-1  | 2023-01-02 15:25:45.844 UTC [391] ERROR:  type "hstore" does not exist
> st-cloud-postgres-1  | 2023-01-02 15:25:45.844 UTC [391] CONTEXT:  unnamed portal parameter $1 = '...'
> st-cloud-postgres-1  | 2023-01-02 15:25:45.844 UTC [391] STATEMENT:  SELECT
> st-cloud-postgres-1  | 	    typname AS name, oid, typarray AS array_oid,
> st-cloud-postgres-1  | 	    oid::regtype::text AS regtype, typdelim AS delimiter
> st-cloud-postgres-1  | 	FROM pg_type t
> st-cloud-postgres-1  | 	WHERE t.oid = $1::regtype
> st-cloud-postgres-1  | 	ORDER BY t.oid
> st-cloud-postgres-1  |
> ```

You seem you are connected to a database that doesn't have the hstore extension installed, and you, or the driver are looking for the oid of that data type. See here for details:

https://www.psycopg.org/psycopg3/docs/basic/pgtypes.html#hstore-adaptation

Maybe there is a pattern like:

```python
try:
    info = TypeInfo.fetch(conn, "hstore")
except Exception:
    pass
else:
    register_hstore(info, conn)
```

somewhere?

**Comment by zzzeek** [comment]
there is!  it's here https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/postgresql/psycopg.py#L339

**Comment by CaselIT** [comment]
I've checked quickly and there seem to be a similar query. I'll try to look if it's possible to run the query without making the db error out

**Comment by CaselIT** [comment]
Oh, it's actually in psycopg the query. `TypeInfo.fetch`.

**Comment by CaselIT** [comment]
Not sure how to proceed here. I see two options here:
- SQLAlchemy could try to detect if a type exists before issuing the `TypeInfo.fetch` call, but that would result in 2 sql query. 
- Alternatively psycopg could modify the query it issue to avid making it fail if hstore (or any other type) does not exists. The issue seems to be in the cast `$1::regtype`, that cold be replaced with `to_regclass($1)` that returns NULL instead of raising an error if the type is not found https://www.postgresql.org/docs/current/functions-info.html

Thoughts @zzzeek @dvarrazzo

**Comment by dvarrazzo** [comment]
@CaselIT:

> Alternatively psycopg could modify the query it issue to avid making it fail if hstore (or any other type) does not exists. The issue seems to be in the cast $1::regtype, that cold be replaced with to_regclass($1) that returns NULL instead of raising an error if the type is not found https://www.postgresql.org/docs/current/functions-info.html (if this is the preferred solution I can open a PR to psycopg)

That looks perfect! I wasn't aware of that function, and it seems exactly what needed.

If you would like to contribute a patch, it would be very welcome.

**Comment by CaselIT** [comment]
ok, will try to do this week

**Comment by CaselIT** [comment]
> ok, will try to do this week

I've opened https://github.com/psycopg/psycopg/pull/474

**Comment by CaselIT** [comment]
the function is actually `to_regtype`, since it's using regtype not regclass.

**Comment by slubovsky** [comment]
Hi. I really like the new system with dataclasses and annotated fields. In our project, we use uuid as ids and uuid.uuid4 to generate them. 
I created an annotation:
```python
uuidpk = Annotated[
    uuid_.UUID,
    mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default_factory=uuid_.uuid4,
    ),
]
```
where uuid_ is std python uuid module.

Then i use this annotation in class:
```python3
class User(MappedAsDataclass, Base, repr=True, unsafe_hash=True):
    __tablename__ = "user"

    id: Mapped[uuidpk] = mapped_column(init=False)
    name: Mapped[vchar15]
    email: Mapped[vchar63]
```

And try to create an object and save it to db:
```python3
engine = create_engine(
    "postgresql+psycopg://postgres:postgres@localhost:5432/postgres"
)

Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine, expire_on_commit=False)

with Session() as session:
    user = User(name="John Dude", email="john@gmail.com")
    session.add(user)
    session.commit()
```

And got this:
```
/home/wallseat/Sources/sqla_20_test/src/models.py:63: SAWarning: Column 'user.id' is marked as a member of the primary key for table 'user', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL.
  session.commit()
Traceback (most recent call last):
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 746, in do_execute
    cursor.execute(statement, parameters)
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute
    raise ex.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "id" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (null, John Dude, john@gmail.com).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wallseat/Sources/sqla_20_test/src/models.py", line 71, in <module>
    main()
  File "/home/wallseat/Sources/sqla_20_test/src/models.py", line 63, in main
    session.commit()
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1894, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1209, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1184, in _prepare_impl
    self.session.flush()
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4125, in flush
    self._flush(objects)
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4261, in _flush
    with util.safe_reraise():
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 148, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4222, in _flush
    flush_context.execute()
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1188, in _emit_insert_statements
    result = connection.execute(
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 489, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 746, in do_execute
    cursor.execute(statement, parameters)
  File "/home/wallseat/Sources/sqla_20_test/.venv/lib/python3.10/site-packages/psycopg/cursor.py", line 728, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.IntegrityError: (psycopg.errors.NotNullViolation) null value in column "id" of relation "user" violates not-null constraint
DETAIL:  Failing row contains (null, John Dude, john@gmail.com).
[SQL: INSERT INTO "user" (name, email) VALUES (%(name)s::VARCHAR(15), %(email)s::VARCHAR(63))]
[parameters: {'name': 'John Dude', 'email': 'john@gmail.com'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```
Am I doing everything right?

**Comment by ryzhovalex** [comment]
Pylance: Illegal type annotation: variable not allowed unless it is a type alias for dynamically created Enum.
```python
def test_enum_field(sqlite: SQLService):
    Color: Enum = Enum("Color", ["RED", "BLUE", "GREEN"])

    class T1(Table):
        color: Mapped[Color]
```
![image](https://user-images.githubusercontent.com/72242438/212571224-09d59de2-4778-415b-8c6f-92c60993fb70.png)

For normally-defined Enum it's ok.

**Comment by zzzeek** [comment]
> Pylance: Illegal type annotation: variable not allowed unless it is a type alias for dynamically created Enum.

hi -

that error has nothing to do with SQLAlchemy.  An Enum object that is created imperatively can't be used as a type:

```py
from enum import Enum

Color: Enum = Enum("Color", ["RED", "BLUE", "GREEN"])

# same rror
d: list[Color] = []
```

**Comment by vamshiaruru-virgodesigns** [comment]
Hi guys, great job on sqlalchemy 2.0!

In the documentation here: https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#step-five-make-use-of-pep-593-annotated-to-package-common-directives-into-types , I think it would be good to have the line 
```python
from sqlalchemy.orm import registry
```
In the code snippets.

**Comment by CaselIT** [comment]
thanks for noticing that. I think we could remove the registry and just do 
```py
class Base(DeclarativeBase):
    type_annotation_map={
        str50: String(50),
    }
```

**Comment by CaselIT** [comment]
v2 is out, closing this.

thanks to anyone who tried the beta and rc versions!
