### ISSUE TITLE
`ImportError: cannot import name '_rfc_1738_quote' from 'sqlalchemy.engine.url'` with SQLAlchemy==1.4.42

### ISSUE THREAD

**Issue by ReubenFrankel** [sqlalchemy/sqlalchemy#8652]
### Describe the bug

Cannot import `_rfc_1738_quote` from `sqlalchemy.engine.url` with SQLAlchemy==1.4.42. <1.14.42 versions seem to work ok still.
![image](https://user-images.githubusercontent.com/60552974/196193622-5ff06898-b479-47aa-b571-96b48b3729ae.png)

### To Reproduce

```python
from sqlalchemy.engine.url import _rfc_1738_quote
```

### Error

```
ImportError: cannot import name '_rfc_1738_quote' from 'sqlalchemy.engine.url' (/tmp/.venv/lib/python3.7/site-packages/sqlalchemy/engine/url.py)
``` 

### Versions

- OS: Ubuntu 22.04.1 LTS
- Python: 3.7.14, 3.8.13, 3.19.13
- SQLAlchemy: 1.4.42
- Database: N/A
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): N/A

**Comment by drew-hansen** [comment]
This broke on all of our pipelines this morning as well. Only difference was we are using Python 3.8.14.

**Comment by ReubenFrankel** [comment]
Yeah, I also tested with 3.8 and 3.9 with the same error...

**Comment by zzzeek** [comment]
please see #8647
