### ISSUE TITLE
implement full annotations for sqlalchemy.ext.mutable

### ISSUE THREAD

**Issue by ramarivera** [sqlalchemy/sqlalchemy#8667]
### Describe the bug

Not sure if it's just extra strict type checking.
It works perfectly in runtime.

### To Reproduce

```python
class GenericSetting(BaseEntity):

    value: Mapped[list[str]] = mapped_column(
        MutableDict.as_mutable(JSON), init=True, default_factory=lambda: []
    )
```

### Error

```
Type of "as_mutable" is partially unknown
  Type of "as_mutable" is "(sqltype: Unknown) -> (SchemaEventTarget | Unknown)"Pylance[reportUnknownMemberType]

Argument type is partially unknown
  Argument corresponds to parameter "__name_pos" in function "mapped_column"
  Argument type is "SchemaEventTarget | Unknown"Pylance[reportUnknownArgumentType]

``` 

### Versions

- OS:
- Python: 3.10.8
- SQLAlchemy: latest beta
- Database:
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by ramarivera** [comment]
Pylance on strict type checking mode, if that helps

**Comment by zzzeek** [comment]
OK I think this is just we haven't done annotations for `sqlalchemy.ext.mutable` yet

**Comment by CaselIT** [comment]
@ramarivera feel free to open a PR if you want to try

**Comment by ramarivera** [comment]
> @ramarivera feel free to open a PR if you want to try

Nice. I'll try to take it up during the weekend :)

**Comment by ramarivera** [comment]
Hey @CaselIT , I'm not exactly sure how to get started with writing the types. Would you mind sharing some general idea of how it should be done, or maybe some past PR for the main package where you already did it?

**Comment by zzzeek** [comment]
It's probably not that easy to know where to start on this since we have a pretty big typing approach set up at this point.

you might try looking at a diff for another extension like this:

   git diff rel_1_4...main lib/sqlalchemy/ext/hybrid.py

since 1.4 has no type annotations at all, that would show the full move to being typed.

But for every module we typically have to invent new things.  So yeah typing `sqlalchemy.ext.mutable`, I haven't looked at it yet but there may be things that require some up front design decisions.

**Comment by g-kisenkov** [comment]
@ramarivera 

I've created a draft PR #8775 where I'm trying to figure out how to best type out this and possibly other modules. Feel free to join the effort. Maybe we'll be able to figure it out together.

**Comment by ramarivera** [comment]
hey @g-kisenkov , glad to help, I think I will have some time for it during the weekend

**Comment by sqla-tester** [comment]
**Gleb Kisenkov** has proposed a fix for this issue in the **main** branch:

**Type annotations for sqlalchemy.ext.mutable** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4202
