### ISSUE TITLE
need to clean up the "annotations can't be interpreted" case

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8692]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/8691

We need to set up ``__allow_unmapped__`` as a first class way to have declarative types that are incorrect to be ignored, for 1.4 compatibility.

right now it fails for this case:

```py
from __future__ import annotations

from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship
from sqlalchemy.orm import Session


class Base(DeclarativeBase):
    pass
    __allow_unmapped__ = True


class A(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(primary_key=True)
    data: Mapped[str]
    bs: list[B] = relationship("B")


class B(Base):
    __tablename__ = "b"
    id: Mapped[int] = mapped_column(primary_key=True)
    a_id: Mapped[int] = mapped_column(ForeignKey("a.id"))
    data: Mapped[str]


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(bs=[B()]))
s.commit()
```

because:

```
When initializing mapper Mapper[A(a)], expression "relationship('list[B]')" seems to be using a generic class as the argument to relationship(); please state the generic argument using an annotation, e.g. "bs: Mapped[list['B']] = relationship()"
```

what it should do is completely not use that annotation that was detected as "wrong".

also the error message raised for the non-evaluable annotation is very confusing and im not sure what I has in mind when I wrote that.   so let's make something less ambiguous.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**allow legacy forms with __allow_unmapped__** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4141
