### ISSUE TITLE
PEP 584 missing from python immutabledict fallback

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8695]
The python only version of immutabledict does not include support for [PEP 584](https://peps.python.org/pep-0584/) while the cython version does

https://github.com/sqlalchemy/sqlalchemy/blob/8e3ec05b2e4b3f22089b531b737c12c249fd2d8e/lib/sqlalchemy/util/_py_collections.py#L75

https://github.com/sqlalchemy/sqlalchemy/blob/8e3ec05b2e4b3f22089b531b737c12c249fd2d8e/lib/sqlalchemy/cyextension/immutabledict.pyx#L117-L124

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add pep 584 to python immutabledict fallback** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4143
