### ISSUE TITLE
1.4 regression, has_table stopped working for views

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8700]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/8678

confirm this works for sqlite, postgresql, mysql for 1.4.   in 1.3, it applies cleanly and works for those backends plus mssql, so this is a clear regression.

```diff
diff --git a/lib/sqlalchemy/testing/suite/test_reflection.py b/lib/sqlalchemy/testing/suite/test_reflection.py
index 459a4d8211..d4f385a152 100644
--- a/lib/sqlalchemy/testing/suite/test_reflection.py
+++ b/lib/sqlalchemy/testing/suite/test_reflection.py
@@ -53,6 +53,19 @@ class HasTableTest(fixtures.TablesTest):
                 schema=config.test_schema,
             )
 
+        if testing.requires.view_reflection:
+            cls.define_views(metadata)
+
+    @classmethod
+    def define_views(cls, metadata):
+        query = "CREATE VIEW test_table_v AS SELECT * FROM test_table"
+
+        event.listen(metadata, "after_create", DDL(query))
+        event.listen(
+            metadata, "before_drop", DDL("DROP VIEW test_table_v")
+        )
+
+
     def test_has_table(self):
         with config.db.begin() as conn:
             is_true(config.db.dialect.has_table(conn, "test_table"))
@@ -78,6 +91,11 @@ class HasTableTest(fixtures.TablesTest):
                 )
             )
 
+    @testing.requires.view_reflection
+    def test_has_table_views(self):
+        with config.db.begin() as conn:
+            is_true(config.db.dialect.has_table(conn, "test_table_v"))
+
 
 class HasIndexTest(fixtures.TablesTest):
     __backend__ = True

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**test support for has_table()->view; backport to 1.4** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4146

**Comment by zzzeek** [comment]
this came absolutely out of nowhere in a patch from me that had nothing to do with reflection, I have absolutely no idea what led me to change this or even how I'd know to change it that way, 2f617f56f

**Comment by zzzeek** [comment]
it looks like I copied it from get_table_names() and assumed has_table() was following that ruleset

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**test support for has_table()->view; backport to 1.4** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4147

**Comment by CaselIT** [comment]
> this came absolutely out of nowhere in a patch from me that had nothing to do with reflection, I have absolutely no idea what led me to change this or even how I'd know to change it that way, [2f617f5](https://github.com/sqlalchemy/sqlalchemy/commit/2f617f56f2acdce00b88f746c403cf5ed66d4d27)

Maybe the change was because in 1.3 the has_table is really an has_object, since it would return if any object of a particular name existed.
