### ISSUE TITLE
declarative cols that have explicit name get placed at the top of the cols list above other attrs, within the mapper only, not the table which is OK

### ISSUE THREAD

**Issue by demishu** [sqlalchemy/sqlalchemy#8705]
Introduction:
I have used 
df1 = pd.read_sql_query(session.query(TableClass), con)  
and
df2 = pd.read_sql_query('select * from table_name', con)
then I got 2 df with the same data but the first has disordered columns.
For this reason, I start to find the issue.

Main Part:
Later I found that session.query (TableClass) is the matter, its SQL statements have disordered columns.
e.g. for a table with A, B, C, and D 4 columns. With 

query = session.query(TableClass)
stmt = query.statement
print(stmt.compile(con))

we can find in the terminal a SQL sentence like "Select C, D, A, B from `table_name`"

### To Reproduce

```python
from sqlalchemy import Column, String, Integer, Float, UniqueConstraint
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

con = create_engine('sqlite:///example.db', echo = False)
Base = declarative_base(bind = con)

class Styles(Base):
    __tablename__ = 'styles_list'
    row = Column(Integer, primary_key = True, autoincrement = True)
    Style = Column(String(10), index = True)
    ColorId = Column(Integer, index = True)
    Color = Column(String(10))
    Size = Column(String(10))
    Pcs = Column("Pcs/Box", Integer)
    Price = Column("Price/Pc", Float, index = True)
    UniqueConstraint(Style, Price, name = 'StylePrice')
    UniqueConstraint(Style, ColorId, name = 'StyleColor')

Base.metadata.create_all(con)
Session = sessionmaker(bind = con)
session = Session()
style1 = Styles(Style = '0001', ColorId = 1, Color = 'blue', Size = '38-43', Pcs = 2)
session.add(style1)
session.commit()

query = session.query(Styles)
stmt = query.statement
print(stmt.compile(con))
```

### Error

SELECT styles_list."Pcs/Box", styles_list."Price/Pc", styles_list."row", styles_list."Style", styles_list."ColorId", styles_list."Color", styles_list."Size" 
FROM styles_list

### Versions

- OS: Windows 11 version 22H2
- Python: 3.9.12
- SQLAlchemy: 1.4.39
- Database: sqlite3 3.39.2
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting, but all the version informations are missing. Can you please complete?

**Comment by demishu** [comment]
> 
sqlalchemy.__version__
Out[4]: '1.4.39'

**Comment by demishu** [comment]
> Hi,
> 
> Thanks for reporting, but all the version informations are missing. Can you please complete?

I completed all the versions' information, plz check, and thank you for having read this issue.

**Comment by zzzeek** [comment]
I will fix this today for 2.0.  unfortunately zero chance of this being changed in 1.4.

**Comment by zzzeek** [comment]
Interesting, this applies only to the SELECT statement and not the Table itself.   OK, most of the hard work w/ the ordering is getting them from the class to the table, that's what people usually care about.  this is just the ORM assignment part of it.

**Comment by CaselIT** [comment]
> this applies only to the SELECT statement and not the Table itself. 

in this case in the 1.x series you can use as workaround `session.query(Styles.__table__)`

**Comment by zzzeek** [comment]
> > this applies only to the SELECT statement and not the Table itself.
> 
> in this case in the 1.x series you can use as workaround `session.query(Styles.__table__)`

that's probably not going to work beacuse those cols would not be ORM annotated.

I've identified this issue all the way at bedrock.  Minecraft level 2 where you're hitting the bottom of the game :)   it's not *too* hard to fix but the thing causing this to happen goes back to v0.0.1.      So.... :)   good timing that we are at 2.0 and can change something this fundamental.

**Comment by CaselIT** [comment]
> that's probably not going to work beacuse those cols would not be ORM annotated.

well, the use case is `pd.read_sql_query(session.query(TableClass), con)` so for that it should be fine

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**reconcile Mapper properties ordering against mapped Table** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4150

**Comment by zzzeek** [comment]
btw @demishu  this is a *great* improvement.  I have a lot of tests to update but they are all being adjusted so that SELECT statements render columns in table order regardless of config, which is great.   This seems to be your first bug report ever on github, you should get a badge for a very rare hole-in-one, getting the SQLAlchemy guy to like your suggestion, not a common occurrence :)
