### ISSUE TITLE
Improve new SA 2.0 PG Range

### ISSUE THREAD

**Issue by lelit** [sqlalchemy/sqlalchemy#8706]
### Describe the use case

In SA 2.0 there is a new _native_ `Range` class that exposes the underlying PostgreSQL `range` types.

The new class is kept intentionally minimal, and indeed it has been implemented using a `dataclass` carrying just the values that make up a range, the `lower` and the `upper` ends, their `bounds` and whether the range is `empty`.

However, some more methods would make the life easier, and an [exchange] identified three of them: `contains_value()`, `issubset()` and `issuperset()`.

### Databases / Backends / Drivers targeted

The new class is PostgreSQL specific, and drivers agnostic.

### Example Use

```python

from datetime import date

from sqlalchemy import create_engine, select
from sqlalchemy.dialects.postgresql import DATERANGE, Range
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, Session


class Base(DeclarativeBase):
    pass


class Contract(Base):
    __tablename__ = "contracts"

    id: Mapped[int] = mapped_column(primary_key=True)
    validity: Mapped[Range[date]] = mapped_column(DATERANGE)


engine = create_engine("postgresql+psycopg://scott:tiger@pg14/dbname")

Base.metadata.create_all(engine)

with Session(engine) as session:
    old_contract = Contract(validity=Range(date(2021, 1, 1), date(2021, 12, 31))
    session.add(old_contract)
    cur_contract = Contract(validity=Range(date(2022, 1, 1), date(2022, 12, 31))
    session.add(cur_contract)
    session.commit()

    for contract in session.execute(select(Contract)):
        print(contract.validity.contains_value(date.today())
```

**Comment by sqla-tester** [comment]
**Lele Gaifax** has proposed a fix for this issue in the **main** branch:

**Implement contains_value(), issubset() and issuperset() on PG Range** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4151
