### ISSUE TITLE
Result cursors are not closed when Exceptions are raised w/in ORM loading loop

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8710]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/8709

<div type='discussions-op-text'>

<sup>Originally posted by **briandamaged** October 24, 2022</sup>
I'm fairly certain that this is a bug, but I'm mentioning it here first just in case this was a conscious design decision.

The `sqlalchemy.orm.loading.instances(..)` generator function implements exception handling logic that attempts to close the underlying cursor before re-raising the exception. Unfortunately, most errors will actually bypass this logic entirely. Consequently, the cursor will be garbage collected rather than closed. This can lead to unexpected behaviors depending upon the implementation of the underlying cursor.

The problem occurs because `sqlalchemy.orm.loading.instances(..)` is a generator function. As such, it never receives the exceptions that are raised by the Consumer. For example:

```python
for result in sqlalchemy.orm.loading.instances(..):
  # Consumer logic
  raise ValueError("sqlalchemy.orm.loading.instances will never receive this exception!")
```

Instead, a `GeneratorExit` exception is raised inside of the generator once the generator goes out of scope. However, the `GeneratorExit` exception is _not_ a subclass of `Exception`; therefore, it is not caught by `except Exception` statements such as these:

* https://github.com/sqlalchemy/sqlalchemy/blob/ee17cbad9ed4adbc1a6a1b6273ad1ded66e25d99/lib/sqlalchemy/orm/loading.py#L98
* https://github.com/sqlalchemy/sqlalchemy/blob/e3ce7ee2ee5b647416654763bd0c8c781b88d79f/lib/sqlalchemy/orm/loading.py#L86

So, the end result is that the `cursor` is never explicitly closed when the Consumer raises an exception. Instead, the generator goes out of scope, which causes the `cursor` to be garbage collected. **This means that SQLAlchemy itself does not guarantee that the cursor will be closed properly**.</div>

**Comment by zzzeek** [comment]
this is likely new as of 1.4 where loading was rearchitected

**Comment by briandamaged** [comment]
Thanks for converting the discussion into a bug, @zzzeek !

This issue is present in both `1.3.x` and 1.4.x`. The fix is potentially as easy as adding `GeneratorExit` to the list exceptions that should be handled:

```python
try:
  ...
except (Exception, GeneratorExit):
  ...
```

Unfortunately for me (and probably others!), this bug actually shielded our codebase from [a separate bug in the `mysqlclient` library](https://github.com/PyMySQL/mysqlclient/issues/560). So, once this is fixed, there is a good chance that some of the people using `mysqlclient` will begin to observe memory errors.

**Comment by zzzeek** [comment]
The code at https://github.com/sqlalchemy/sqlalchemy/blob/ee17cbad9ed4adbc1a6a1b6273ad1ded66e25d99/lib/sqlalchemy/orm/loading.py#L98 is from 1.3, and it has the bug.  

in 1.4, the Exception catch you refer towards is before any yields.      The test at https://github.com/sqlalchemy/sqlalchemy/blob/37b29b58cb3e1b0715711327724166b0fb991c70/test/orm/test_loading.py#L155 confirms cursor is closed if an exception is raised in that block.

Exception raises within iteration would therefore be once you have the Result object, which is wrapping the cursor itself.    If you arent using yield_per, then the real cursor is already closed before you ever iterate any rows.  If you were using yield_per, and had an exception mid-stream, you still have an open server-side Result object there so your code would have to be closing that.

so I can't reproduce without a specific example.  if this is only in 1.3.x, upgrade to 1.4.

**Comment by briandamaged** [comment]
Gotcha. I probably forgot to rebuild my container when testing against `1.4.x`. We _are_ using `yield_per`, so I'll double-check that everything is behaving as expected later this afternoon. Thanks!

In either case: should I go ahead and implement a fix for `1.3.x`? Or, would you rather just have people upgrade?

**Comment by zzzeek** [comment]
1.3.x is not having releases at this point aside from a show-stopping security issue, so you'd want to get onto 1.4.  it's been out for two years.

**Comment by briandamaged** [comment]
Alright, I've confirmed that that specific exception handler is not relevant in `1.4.x`.

Unfortunately, so far I have not had any success with gaining access to the `Result` instance that you mentioned. I've tried the following:

```python
# Keep in mind that I'm using ORM queries here.
# (Unfortunately, I did not discover the `core` layer until later. So, sections of the code still
# need to be rewritten to take advantage of that)
query = session.query(...).yield_per(2000)

result = iter(query)                         # result will be a Generator Function
result = query.all()                          # Appears to be loading all records into a list.
result = session.execute(query)   # Also appears to be loading all records into a list.

# Documentation indicates that this approach is deprecated; however, it appears that it's
# already broken. It results in the following error:
#
#    AttributeError: 'Query' object has no attribute '_from_objects'. Did you mean: '_from_obj'?
#
result = query.execute()

# Documentation also mentions a `Query#instances(..)` method, but it does not provide any
# examples of its usage. Based upon its usage within the automated tests, it almost looks like
# this is intended as an internal method that should not be touched. (In particular, the `context`
# is instantiated via a protected method.)
```

So, do you have any suggestions for obtaining either a `Result` or `ResultProxy` instance like you mentioned earlier? Additionally, if `Query#instances(..)` is the correct method to use, then I might also need some advice on instantiating `context` objects without relying upon the protected `Query._compile_context(..)` method.

Thanks in advance!

**Comment by zzzeek** [comment]
that said if you have Query already, you can pass query.statement to session.execute(), that will give you the Result

**Comment by briandamaged** [comment]
Got it. We're already using the `2.x` style statements on another project, but we haven't integrated them into this codebase yet. But, this might be a good reason to go ahead and switch over.

In the meantime, do you think it's worthwhile to continue investigating an unobtrusive fix for people who still rely upon the traditional `Query` mechanisms? If so, then I can continue this investigation a bit later in the week. Otherwise, we can probably just close this ticket out.

**Comment by briandamaged** [comment]
(I forgot to mention: I'm 95% certain that the cursors are still being garbage collected without being closed first. Otherwise, I would encounter the memory exhaustion bug that I mentioned in the other library)

**Comment by zzzeek** [comment]
I just need some kind of repro case and I can just figure out the best way to fix it.

**Comment by briandamaged** [comment]
The basic pattern is really just this:

```python
query = session.query(...).yield_per(2000)
results = iter(query)     # Returns a Generator
for r in results:
  raise ValueError("Oops!")
```

_However_, I found that pulling the `results` variable onto its own line like that will actually change the behavior of the program. I believe that this is because `results` is a named variable, which then impacts the order that the variables are garbage collected. (In my particular case, it actually causes the program to crash with an error that states `"Commands out of sync; you can't run this command now"`. It looks like it's attempting to rollback the transaction before the cursor has been cleaned up)

So, to recreate my specific case, you would need to do:

```python
query = session.query(...).yield_per(2000)
for r in query:    # Implicitly calls `iter(..)` and stores the Generator in a temporary variable
  raise ValueError("Oops!")
```

(But yeah: this behavior I just described is yet another argument for just switching over to the `2.x` style. It allows the programmer to control the cursor's lifecycle directly rather than relying upon Python's garbage collector to make the decision)

**Comment by zzzeek** [comment]
OK can you play a bit with this patch?   the MySQL drivers are indeed very problematic about server side cursors

```diff
diff --git a/lib/sqlalchemy/engine/result.py b/lib/sqlalchemy/engine/result.py
index 05ca17063b..4b5ed4abad 100644
--- a/lib/sqlalchemy/engine/result.py
+++ b/lib/sqlalchemy/engine/result.py
@@ -408,6 +408,14 @@ class ResultInternal(InPlaceGenerative, Generic[_R]):
     def _soft_close(self, hard: bool = False) -> None:
         raise NotImplementedError()
 
+    def _iter_w_gen_close(self) -> Iterator[RowMapping]:
+        try:
+            for row in self._iter_impl():
+                yield row
+        except GeneratorExit:
+            self._soft_close()
+            raise
+
     @HasMemoized_ro_memoized_attribute
     def _row_getter(self) -> Optional[Callable[..., _R]]:
         real_result: Result[Any] = (
diff --git a/lib/sqlalchemy/orm/query.py b/lib/sqlalchemy/orm/query.py
index 86137e00e6..68bd0e60a8 100644
--- a/lib/sqlalchemy/orm/query.py
+++ b/lib/sqlalchemy/orm/query.py
@@ -2687,7 +2687,7 @@ class Query(
             return None
 
     def __iter__(self) -> Iterable[_T]:
-        return self._iter().__iter__()  # type: ignore
+        return self._iter()._iter_w_gen_close()  # type: ignore
 
     def _iter(self) -> Union[ScalarResult[_T], Result[_T]]:
         # new style execution.

```

**Comment by briandamaged** [comment]
Howdy again! FYI: I had some other things come up, so I haven't had a chance to try out the patch yet. But, I should be able to look at it later this afternoon.

Skimming over it, it looks like it will most likely do the trick.

**Comment by zzzeek** [comment]
alterantive approach: dont use server side cursors and do pagination of some kind.    MySQL ss cursors are just not very good

**Comment by briandamaged** [comment]
Howdy again!

Hmmz... I'd have to see your specific example. Based upon your description, it sounds like you might be creating a 2nd instance of the iterator.

I suspect that `GeneratorExit` is raised when the Generator goes out of scope. That is: the "inner raise" does not directly cause the `GeneratorExit` to occur. For example:

```
row_iter = iter(query)
try:
  for row in row_iter:
    raise ValueError("Oops!")
except:
  print("GeneratorExit is not raised because row_iter is still in scope")
```

This would at least explain the behavior that I observed here:

https://github.com/sqlalchemy/sqlalchemy/issues/8710#issuecomment-1291042982

BTW: I had some other priorities come up, but I should be able to verify your patch tomorrow.

**Comment by zzzeek** [comment]
GeneratorExit is also raised if you simply call "break" in the middle of an iterator.  So for the core Result objects it doesnt seem like we could ever do anything automatically w/ GeneratorExit.  Here's a test I'm adding:

```py
        result = connection.execute(table.select())
        result = result.yield_per(100)
        for i, row in enumerate(result):
            if i == 188:
                # this will raise GeneratorExit inside the iterator.
                # so we can't close the DBAPI cursor here, we have plenty
                # more rows to yield
                break

        # demonstrate getting more rows
        for i, row in enumerate(result):
            if i == 206:
                break

        eq_(i, 206)
```

the above test fails if I make the following change:

```diff
diff --git a/lib/sqlalchemy/engine/cursor.py b/lib/sqlalchemy/engine/cursor.py
index f22e89fbeb..85bd4c7a17 100644
--- a/lib/sqlalchemy/engine/cursor.py
+++ b/lib/sqlalchemy/engine/cursor.py
@@ -2090,11 +2090,16 @@ class CursorResult(Result[_T]):
     def _fetchiter_impl(self):
         fetchone = self.cursor_strategy.fetchone
 
-        while True:
-            row = fetchone(self, self.cursor)
-            if row is None:
-                break
-            yield row
+        try:
+            while True:
+                row = fetchone(self, self.cursor)
+                if row is None:
+                    break
+                yield row
+        except GeneratorExit:
+            self._soft_close()
+            raise
 
     def _fetchone_impl(self, hard_close=False):
         return self.cursor_strategy.fetchone(self, self.cursor, hard_close)
```

for 2.0 I'm implementing context manager support for all result objects (like what's illustrated [here](https://stackoverflow.com/a/34486172/34549)

**Comment by briandamaged** [comment]
Hmmz... I believe that this is still the same case I mentioned before. That is: the `break` statement is indirectly causing the Generator (or Iterator) to go out of scope, which then causes `GeneratorExit` to get raised.

In particular: `break` doesn't imply that you have finished the iteration. It simply breaks out of the current loop. You can then have subsequent logic that continues the same iteration from where it left off. Ex:

```python
def keep_counting():
  x = 0
  while True:
    yield x
    x += 1

count_iter = keep_counting()

# Generators are already Iterators; therefore, iter(count_iter) is the same as count_iter
assert count_iter is iter(count_iter)

for x in count_iter:
  print(x)
  if x >= 3:
    break

for x in count_iter:
  print(x * x)
  if x >= 10:
    break
```

Throughout this snippet, `GeneratorExit` is never raised because `count_iter` never goes out of scope. (ie: it's never garbage collected)

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Support result.close() for all iterator patterns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4172

**Comment by zzzeek** [comment]
The iterator returned by Query.__iter__() is special; it creates a new iterator right at the start of the method.  So for that specific iterator, once it's broken, it's broken, and we definitely should close the result.  this is the main case you have.   for the iterators inside of Result, the Result object stays stateful with more rows after an iterator is broken. so for that one, close should not be automatic when an iterator breaks.

**Comment by briandamaged** [comment]
I agree w/ the high-level behavior you outlined.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**soft close cursor for Query direct iterator interrupted** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4173

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**soft close cursor for Query direct iterator interrupted** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4174

**Comment by zzzeek** [comment]
also I observed the "break" statement definitely raising GeneratorExit.  run this

```py
def things():
    try:
        for i in range(10):
            yield i
    except GeneratorExit:
        print("GeneratorExit!")



for x in things():
    print(f"{x}")

    if x > 3:
        break
```

output

```
0
1
2
3
4
GeneratorExit!
```
