### ISSUE TITLE
Query.get() in dictionary mode does not respect orm.synonym()

### ISSUE THREAD

**Issue by linobino1** [sqlalchemy/sqlalchemy#8753]
### Describe the bug

When using a dictionary for specifying primary keys in Query.get(), synonyms for the primary key fields are not being respected.

### To Reproduce

```python
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, declarative_base, synonym
from sqlalchemy.schema import Column, ForeignKey
from sqlalchemy.types import Integer

engine = create_engine("sqlite:///:memory:")
session = Session(engine)
Base = declarative_base()

class Parent(Base):
    __tablename__ = 'membership'
    child_id = Column(ForeignKey('child.id'), primary_key=True)
    synonym_child_id = synonym(child_id)


class Child(Base):
    __tablename__ = 'child'
    id = Column(Integer, primary_key=True)

Base.metadata.create_all(engine)

session.query(Parent).get({
    'synonym_child_id': 0,
})
```

### Error

```
Traceback (most recent call last):
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Sites/bugs/sqlalchemy_synonym/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2897, in _get_impl
    primary_key_identity = list(
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Sites/bugs/sqlalchemy_synonym/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2898, in <genexpr>
    primary_key_identity[prop.key]
KeyError: 'child_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Sites/bugs/sqlalchemy_synonym/example.py", line 22, in <module>
    session.query(Parent).get({
  File "<string>", line 2, in get
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Sites/bugs/sqlalchemy_synonym/venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Sites/bugs/sqlalchemy_synonym/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 947, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Sites/bugs/sqlalchemy_synonym/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 951, in _get_impl
    return self.session._get_impl(
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Sites/bugs/sqlalchemy_synonym/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2903, in _get_impl
    util.raise_(
  File "/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Sites/bugs/sqlalchemy_synonym/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: Incorrect names of values in identifier to formulate primary key for session.get(); primary key attribute names are 'child_id'
```

### Versions

- OS: macOS 12.6
- Python: 3.9.6
- SQLAlchemy: 1.4.42
- Database: sqlite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pysqlite

**Comment by zzzeek** [comment]
not totally sure about this.   do we also do hybrid methods?  what does the error message say when an invalid name is passed, if "child_id" is the PK col name but there are three other synonyms?

**Comment by zzzeek** [comment]
"Incorrect names of values in identifier to formulate primary key for session.get(); primary key attribute names are 'child_id' (with alternate names 'synonym_child_id')"

that would actually be kind of hard to implement and I'd rather not do that.

**Comment by linobino1** [comment]
> not totally sure about this. do we also do hybrid methods? what does the error message say when an invalid name is passed, if "child_id" is the PK col name but there are three other synonyms?

it says the same no matter what

**Comment by linobino1** [comment]
> "Incorrect names of values in identifier to formulate primary key for session.get(); primary key attribute names are 'child_id' (with alternate names 'synonym_child_id')"
> 
> that would actually be kind of hard to implement and I'd rather not do that.

Why would you not do it like this? To me this feels like the desired behaviour.

**Comment by CaselIT** [comment]
> "Incorrect names of values in identifier to formulate primary key for session.get(); primary key attribute names are 'child_id' (with alternate names 'synonym_child_id')"
> 
> that would actually be kind of hard to implement and I'd rather not do that.

I'm fine with documenting this limitation and closing as won't fix

**Comment by zzzeek** [comment]
i meant, the error message that's printed when an incorrect name is used.

**Comment by linobino1** [comment]
> i meant, the error message that's printed when an incorrect name is used.
```
class Parent(Base):
    __tablename__ = 'parent'
    child_id = Column(ForeignKey('child.id'), primary_key=True)
    synonym_1 = synonym(child_id)
    synonym_2 = synonym(child_id)

session.query(Parent).get({
    'invalid': 0,
})
```
prints:
```
sqlalchemy.exc.InvalidRequestError: Incorrect names of values in identifier to formulate primary key for session.get(); primary key attribute names are 'child_id'
```

The error message is always the same. Synonyms are not included. It is produced in `sqlalchemy.orm.session.Session._get_impl()`:

```
class Session(_SessionClassMethods):
    def _get_impl(
        ...
         except KeyError as err:
                util.raise_(
                    sa_exc.InvalidRequestError(
                        "Incorrect names of values in identifier to formulate "
                        "primary key for session.get(); primary key attribute "
                        "names are %s"
                        % ",".join(
                            "'%s'" % prop.key
                            for prop in mapper._identity_key_props
                        )
                    ),
                    replace_context=err,
                )
```

**Comment by zzzeek** [comment]
in your example, the error message:

"sqlalchemy.exc.InvalidRequestError: Incorrect names of values in identifier to formulate primary key for session.get(); primary key attribute names are 'child_id'"

is not strictly accurate; if this issue were fixed, you can also use "synonym_child_id" as an attribute name.

the use case I have in mind is the typical one for synonyms, where the attribute is named `_PRIVATE_pk` or something ugly, and such dictionary access would want to use the nicer synonym name, which I'm assuming is your use case. 

overall, synoynms are not used very much and im not sure what your case is here for using them with a PK col.  there's easier ways to have the ORM attribute name being different from the real column name.

**Comment by linobino1** [comment]
My use case is sth. like this:

```
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, declarative_base, synonym, declared_attr
from sqlalchemy.schema import Column, ForeignKey
from sqlalchemy.types import Integer
import logging

logging.basicConfig()
logging.getLogger("sqlalchemy").setLevel(logging.DEBUG)

engine = create_engine("sqlite+pysqlite:///:memory:")
session = Session(engine)
Base = declarative_base()


class User(Base):
    __tablename__ = 'user'
    pk = Column(Integer, primary_key=True)

class Role(Base):
    __tablename__ = 'role'
    pk = Column(Integer, primary_key=True)

class Permission(Base):
    __tablename__ = 'permission'
    pk = Column(Integer, primary_key=True)


class PermissionUserAssociation(Base):
    __tablename__ = 'permission_user'
    permission_pk = Column(ForeignKey('permission.pk'), primary_key=True)
    user_pk = Column(ForeignKey('user.pk'), primary_key=True)
    entity_pk = synonym(user_pk)

class PermissionRoleAssociation(Base):
    __tablename__ = 'permission_role'
    permission_pk = Column(ForeignKey('permission.pk'), primary_key=True)
    role_pk = Column(ForeignKey('role.pk'), primary_key=True)
    entity_pk = synonym(role_pk)


for association in [PermissionUserAssociation, PermissionRoleAssociation]:
    session.query(association).get({
        'permission_pk': 99,
        'entity_pk': 99,
    })
```

I know I could use `Query.get()` with a tuple of primary keys, but this seems very dangerous, as the primary keys might be mixed up.

**Comment by zzzeek** [comment]
that is a great use case, thanks for explaining.

**Comment by zzzeek** [comment]
heya -

are all your samples actual?  synonym() requires a string argument, not a column object

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**resolve synonyms in dictionary form of Session.get()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4176

**Comment by linobino1** [comment]
> heya -
> 
> are all your samples actual? synonym() requires a string argument, not a column object

Yes, I ran the code above - I was wondering about that too but it works just the same in this case at least

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**resolve synonyms in dictionary form of Session.get()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4177

**Comment by zzzeek** [comment]
> > heya -
> > are all your samples actual? synonym() requires a string argument, not a column object
> 
> Yes, I ran the code above - I was wondering about that too but it works just the same in this case at least

column objects in synonym aren't supported, if you try to use that synonym in any meaningful context it will raise TypeError.  the argument is not at the moment checked up front
