### ISSUE TITLE
Memory leak with asyncpg and Python 3.11

### ISSUE THREAD

**Issue by roman-g** [sqlalchemy/sqlalchemy#8763]
### Describe the bug

The code below consumes memory at the rate about 200 MB/s. The similar code calling asyncpg directly doesn't have the issue and demonstrates that asyncpg itself seems not to be affected.

### To Reproduce

The full sample in a container: https://github.com/roman-g/sqlalchemy-memory-leak

```python


import sqlalchemy.ext.asyncio as sa_async
import asyncpg
import asyncio


async def sa_main():
    engine = sa_async.create_async_engine('postgresql+asyncpg://postgres:some_secret@postgresql:5432/postgres')
    while True:
        async with engine.connect():
            pass


async def asyncpg_main():
    connection = await asyncpg.connect('postgresql://postgres:some_secret@postgresql:5432/postgres')
    while True:
        async with connection.transaction():
            pass


asyncio.run(sa_main())
```
```


### Error

No errors

### Versions

- OS: Linux
- Python: 3.11
- SQLAlchemy: 1.4.43
- Database: Postgres 14.1
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): asyncpg


### Additional context

_No response_

**Comment by zzzeek** [comment]
memory is flat as a board with python 3.10.   have not reproduced on 3.11 yet, but if it does reproduce, greenlet would be likely as they have a C implementation that had to change for 3.11.

**Comment by zzzeek** [comment]
seems like greenlet, still confirming.

This script leaks directly under python 3.11.0rc1 and does not leak at all under python 3.10.

feel free to test on your end

```py
import greenlet
import time


def greenlet_spawn(fn, *args, **kwargs):
    context = greenlet.greenlet(fn, greenlet.getcurrent())
    result = context.switch(*args, **kwargs)
    return result



def hi():
    time.sleep(.001)
    return "hello"

def go():
    while True:
        print(greenlet_spawn(hi))
go()

```

**Comment by zzzeek** [comment]
welp it seems pretty obvious and is reported in https://github.com/python-greenlet/greenlet/issues/328 .   not much I can do on this end but I will obviously keep this open, and if greenlet's response is slow I may have to publicize this.   not sure how eventlet /gevent users arent seeing this.

**Comment by Kludex** [comment]
> Does this reproduce also using greenlet 1.x versions? Version 1.1.3 has python 3.11 wheels so it should be easly testable.
> 
> If not I guess we can add a <2 in SQLAlchemy requirements until that's solved

https://github.com/gevent/gevent/issues/1924#issuecomment-1303544463

**Comment by CaselIT** [comment]
Then I guess we can't really do anything on sqlalchemy side. Not sure if documenting it would make sense

**Comment by zzzeek** [comment]
yeah i was able to reproduce with older versions also.    i dont see how you "document" this, it's more of a news item.   if greenlet isn't responding by tonight we will have to start reading C code

**Comment by CaselIT** [comment]
I think tonight is a bit excessive, let's say start of by Tuesday. Unless you want to read C code again:)

**Comment by zzzeek** [comment]
it's C++ code.  so i have even less idea what's going on.     development on greenlet seems to be extremely active so hopefully this gets addressed ASAP

**Comment by zzzeek** [comment]
it looks like @jamadden is addressing it on the gevent issue for two days already.

**Comment by zzzeek** [comment]
OK that issue was fixed but unfortunately the above test program still leaks memory on py3.11 only, i will have to rework it down to a new test case and report a new greenlet bug

**Comment by roman-anna-money** [comment]
It seems to work well in that isolated test, we'll test it in real cases and let you know soon

**Comment by roman-g** [comment]
It seems to work well in that isolated test, we'll test it in real cases and let you know soon

**Comment by zzzeek** [comment]
I've identified a separate leak that seems to be completely local to the aiosqlite library, which is not involved here, so this one is fixed.

**Comment by zzzeek** [comment]
the leak appears to be in Python itself and looks like the same issue with Thread: https://github.com/python/cpython/issues/99205
