### ISSUE TITLE
Further improvements to new SA 2.0 PG Range

### ISSUE THREAD

**Issue by lelit** [sqlalchemy/sqlalchemy#8765]
### Describe the use case

[This comment](https://github.com/sqlalchemy/sqlalchemy/pull/8707#issuecomment-1302068565) asks for implementation of a new set of methods on the PG Range class to bring it in par with the functionalities of the concrete `XXXRANGE` classes wrt comparison between different ranges.

PR #8707 implemented a few of them, as well as a test infrastructure that asserts their correct behaviour.

### Databases / Backends / Drivers targeted

The new class is PostgreSQL specific, and drivers agnostic.

### Example Use

```python
from datetime import date
from itertools import pairwise

from sqlalchemy import create_engine, select
from sqlalchemy.dialects.postgresql import DATERANGE, Range
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, Session


class Base(DeclarativeBase):
    pass


class Contract(Base):
    __tablename__ = "contracts"

    id: Mapped[int] = mapped_column(primary_key=True)
    validity: Mapped[Range[date]] = mapped_column(DATERANGE)


engine = create_engine("postgresql+psycopg://scott:tiger@pg14/dbname")

Base.metadata.create_all(engine)

with Session(engine) as session:
    old_contract = Contract(validity=Range(date(2021, 1, 1), date(2021, 12, 31)))
    session.add(old_contract)
    cur_contract = Contract(validity=Range(date(2022, 1, 1), date(2022, 12, 31)))
    session.add(cur_contract)
    session.commit()

    validities = session.scalars(select(Contract.validity).order_by(Contract.validity)).all()
    for v1, v2 in pairwise(validities):
        assert v1.adjacent_to(v2), f"There is a gap between {v1} and {v2}"
```

**Comment by lelit** [comment]
The related PR didn't carry a "fixes" marker... should this be closed manually?

**Comment by zzzeek** [comment]
wow that's a weird oversight for me.   yes thanks!

**Comment by lelit** [comment]
Mike, I see a possible "defect" in [current implementation](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/postgresql/ranges.py#L287) of the `__eq__()` method: it accepts an `other: Any` argument, and that suggests that a code like
```python
if my_range == None:
  pass
```
is valid, even if perhaps not ideal. As written, that raises
```python
>       elif self.empty != other.empty:
E       AttributeError: 'NoneType' object has no attribute 'empty'
```
Do I have your bless to fix that, basically adding `if not isinstance(other, Range): return False`?

**Comment by CaselIT** [comment]
Can't we return not implement instead? https://docs.python.org/3/library/constants.html#NotImplemented

**Comment by zzzeek** [comment]
yes that is likely more appropriate

**Comment by lelit** [comment]
Ok, thanks.
