### ISSUE TITLE
Relationship with selectin lazy and expire_on_commit turned on loads lazily

### ISSUE THREAD

**Issue by Danstiv** [sqlalchemy/sqlalchemy#8769]
### Describe the bug

Hello.
If you create an object, add it to session and commit, and then request collection, sqlalchemy will perform a lazy load.
This becomes a problem when using an async engine, async session, etc., as implicit IO occurs.

### To Reproduce

```python
import logging

from sqlalchemy import (
    Column,
    ForeignKey,
    Integer,
    create_engine,
)
from sqlalchemy.orm import declarative_base, relationship, Session

Base = declarative_base()


class User(Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    posts = relationship('Post', back_populates='user', lazy='selectin')


class Post(Base):
    __tablename__ = 'post'
    id = Column(Integer, primary_key=True)
    user_id = Column(ForeignKey('user.id'))
    user = relationship('User', back_populates='posts')

def main():
    engine = create_engine('sqlite://', echo=True)
    logger = logging.getLogger('sqlalchemy.engine.Engine')
    logger.handlers[0].setFormatter(logging.Formatter('%(message)s'))
    Base.metadata.create_all(engine)
    session = Session(engine, expire_on_commit=False)
    user = User()
    print(f'User created: posts is {user.posts}')
    session.add(user)
    print(f'User added: posts is {user.posts}')
    session.commit()
    print('committed')
    print(f'now posts is {user.posts}')


if __name__ == '__main__':
    main()
```

### Error

```
D:\temp>sa_test.py
BEGIN (implicit)
PRAGMA main.table_info("user")
[raw sql] ()
PRAGMA temp.table_info("user")
[raw sql] ()
PRAGMA main.table_info("post")
[raw sql] ()
PRAGMA temp.table_info("post")
[raw sql] ()

CREATE TABLE user (
        id INTEGER NOT NULL,
        PRIMARY KEY (id)
)


[no key 0.00749s] ()

CREATE TABLE post (
        id INTEGER NOT NULL,
        user_id INTEGER,
        PRIMARY KEY (id),
        FOREIGN KEY(user_id) REFERENCES user (id)
)


[no key 0.01636s] ()
COMMIT
User created: posts is []
User added: posts is []
BEGIN (implicit)
INSERT INTO user DEFAULT VALUES
[generated in 0.00169s] ()
COMMIT
committed
BEGIN (implicit)
SELECT post.id AS post_id, post.user_id AS post_user_id
FROM post
WHERE ? = post.user_id
[generated in 0.00331s] (1,)
now posts is []
``` 

### Versions

- OS: Windows 10 21H1 (x64) build 19043.1706
- Python: 3.10.2
- SQLAlchemy: 1.4.43
- Database: sqlite
- DBAPI: aiosqlite 0.17.0

**Comment by zzzeek** [comment]
hi -

eager loading doesn't occur during flushes for attributes that aren't part of the operation.   since `user.posts` was given no initial value, and nothing is loaded for it, the ORM has no choice but to emit a load for that individual operation when you access it.

solution in this specific case would be to ensure you assign it up front:

```py
    user = User(posts=[])

```

**Comment by Danstiv** [comment]
Thanks for the answer.

Yes, now I'm using this solution and the problem is fixed.

It seemed strange to me that sqlalchemy would try to query for relation objects when it just knew they weren't there, since it's a new object.

On the other hand, the absence of an additional query can probably lead to some problems that are not obvious to me.

Also, I did not find a mention of this behavior in the documentation. Is it described somewhere?

**Comment by zzzeek** [comment]
> 
> It seemed strange to me that sqlalchemy would try to query for relation objects when it just knew they weren't there, since it's a new object.

there is some historical baggage here as it doesnt know if you were also adding Post objects with user_id=X to them at the same time, which you'd then expect to see loaded.

> 
> On the other hand, the absence of an additional query can probably lead to some problems that are not obvious to me.

same here.   it *could* go through every relationship and assume empty for them, but there's tons of cases where people add objects with FK attributes and dont combine the objects together pre-flush and that's the whole set of use cases that break in this case.

> 
> Also, I did not find a mention of this behavior in the documentation. Is it described somewhere?

this general area of things is discussed in a few contexts such as at https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#accessing-an-uninitialized-collection-attribute-on-a-transient-object-no-longer-mutates-dict , and in the tutorial we tend to discuss things across the commit boundary, so like at https://docs.sqlalchemy.org/en/14/tutorial/orm_related_objects.html#loading-relationships , but a subtle thing like this is difficult to have as a 'first class documented behavior' unless we are writing a line-by-line behavioral specification, which is out of scope for the project.

**Comment by zzzeek** [comment]
definitely this could be added as as bullet at https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#preventing-implicit-io-when-using-asyncsession
