### ISSUE TITLE
labels for functions not rendering in RETURNING the same way as in SELECT

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8770]
```py
from sqlalchemy import Column
from sqlalchemy import func
from sqlalchemy import insert
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy import TypeDecorator
from sqlalchemy.orm import declarative_base
Base = declarative_base()


class MyThing(TypeDecorator):
    impl = String

    def column_expression(self, column):
        return func.lower(column)

class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    data = Column(MyThing)

print(insert(A.__table__).returning(A.__table__.c.data))

print(select(A.__table__))

print(insert(A).returning(A))

print(insert(A).returning(A.__table__))


```

from https://github.com/geoalchemy/geoalchemy2/issues/409

we render the colname as label name in select but not Insert..returning

```
$ python test3.py 
INSERT INTO a (id, data) VALUES (:id, :data) RETURNING lower(a.data) AS data_1
SELECT a.id, lower(a.data) AS data 
FROM a
INSERT INTO a (id, data) VALUES (:id, :data) RETURNING a.id, lower(a.data) AS data_1
INSERT INTO a (id, data) VALUES (:id, :data) RETURNING a.id, lower(a.data) AS data_1

```

this is said to have changed in 673ca806b323f47ef7064dd64ffc98240818b93 and seems unnecessary, even though in 2.0 we get the right column back for ORM round trips.

**Comment by jerluc** [comment]
@zzzeek being new to the internals of this codebase, this was where I was able to fix the above test example while still ensuring no pre-existing unit tests fail:

```patch
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index 704c0d19c..72fb14b6d 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -3789,6 +3789,7 @@ class SQLCompiler(Compiled):
                     column._tq_label,
                 ),
             )
+
         else:
             # determine here whether this column should be rendered in
             # a labelled context or not, as we were given no required label
@@ -3799,6 +3800,8 @@ class SQLCompiler(Compiled):
                 # type-specific expression wrapping the given column,
                 # so we render a label
                 render_with_label = True
+                if isinstance(column.type, sqltypes.TypeDecorator):
+                    fallback_label_name = column.name
             elif isinstance(column, elements.ColumnClause):
                 # table-bound column, we render its name as a label if we are
                 # inside of a subquery only
```

Being honest though, I'm a bit uncertain about a few things:

- `fallback_label_name` was convenient and works, but I'm not sure if this is the right variable to reuse for this purpose
- Is `TypeDecorator` the right type to check for? Or is this making too broad of an assumption that all `TypeDecorator`s intend to wrap columns in column expressions that would need to be relabeled?
- Another attempt I made was to manipulate `col_expr` itself by wrapping it in something like `Label(column.name, col_expr)`; this also worked, but I'm not sure if this breaks other behaviors that might introspect `col_expr`
- You mentioned in geoalchemy/geoalchemy2#409 that there's a possibility this will all change again in SQLAlchemy 2.0; while it'd be great (for me at least) to get a patch in for 1.4, I'd also love to hear more about how you see 2.0 better handling this scenario

**Comment by zzzeek** [comment]
OK let me look into it, because those label names come from a standard function that's part of Select, and for RETURNING, I would think it wants to use common functionality.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**establish consistency for RETURNING column labels** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4180

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**establish consistency for RETURNING column labels** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4181

**Comment by zzzeek** [comment]
OK that's the 2.0 version, and as I look at what we have, this can't be easily merged into 1.4 because it takes advantage of lots of refactorings that aren't present in 1.4.   So there is a much more minimal change for 1.4 that won't handle dupes ( which arent handled now anyway)

**Comment by zzzeek** [comment]
this is going to take several passes to get the 2.0 one to pass everything, get the changelogs worked out since they need to be separate

**Comment by zzzeek** [comment]
welp see if the patch at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4181 works for you , I can clean that up in the next two days, im not around much tomorrow

**Comment by jerluc** [comment]
Thanks @zzzeek, yeah it looks like applying that patch to ToT on `rel_1_4` (I'm assuming this is the correct branch for v1.4.x releases) resolves the original problem I was running into. Also I can see now how short-sighted my original patch was, as I didn't even think to look at some of the dialect-specific parts!
