### ISSUE TITLE
IntFlag broke backwards compatibility in Python 3.11, is not compatible w/ _FastIntFlag

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8783]
as demonstrated in https://github.com/python/cpython/issues/99304, our habit of extracting the elements of an enum into individual variables no longer works in Python 3.11.  The reason we don't see any failures is because we have our own ``_FastIntEnum`` workaround class that already replaces observed slowness in `IntEnum`, however, running mypy under python 3.11 now fails for these, we would assume because they've modified the class hierarchy for `IntEnum`  (it seems from other IntEnum issues in cpython github that they've changed its architecture).

The change in behavior might be a regression but in any case we need to shield ourselves from it with a compat function of some kind.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**work around Python 3.11 IntEnum issue** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4186

**Comment by ethanfurman** [comment]
`IntEnum` is not the problem, it's `IntFlag`.  There have been significant speed improvements for `IntFlag` -- you might want to check if `FastIntFlag` is still necessary.

**Comment by zzzeek** [comment]
> `IntEnum` is not the problem, it's `IntFlag`. There have been significant speed improvements for `IntFlag` -- you might want to check if `FastIntFlag` is still necessary.

I would imagine FastIntFlag is not necessary as I understand the theme of Python 3.11 is speed improvements, and the Python 3.10 version indeed was pretty slow.  however, for the moment we are supporting python versions 3.7-3.11 so we need a compatibiltiy layer in any case.
