### ISSUE TITLE
send bound param contextual info into render_literal_value, raise informative exception when internal error in render occurrs

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8800]

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add informative exception context for literal render** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4197

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**add informative exception context for literal render** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4198
