### ISSUE TITLE
SQLite reflection drops the WHERE clause of partial indexes

### ISSUE THREAD

**Issue by tgpfeiffer** [sqlalchemy/sqlalchemy#8804]
### Describe the bug

`SQLiteDialect.get_indexes()` does not distinguish between full and partial indexes. If an index is partial, that information is not communicated to the caller of `get_indexes()` and this may cause, say, alembic to recreate a partial index as a full index during a migration, cf. https://github.com/sqlalchemy/alembic/issues/1112

In https://github.com/sqlalchemy/sqlalchemy/blob/9237bf15e612ba82555444751bd69dc2a831e7f4/lib/sqlalchemy/dialects/sqlite/base.py#L2647-L2654 we should treat the case `row[4] == 1` separately (see [`index_list()`](https://www.sqlite.org/pragma.html#pragma_index_list)) and then probably need to do some extra work like parsing the string in `sqlite_master.sql` for that particular index in order to get the actual filter predicate.

### To Reproduce

```python
    def test_reflect_partial_indexes(self):
        with testing.db.begin() as conn:
            conn.exec_driver_sql(
                "create table foo_with_partial_index (x integer, y integer)"
            )
            conn.exec_driver_sql(
                "create unique index ix_partial on foo_with_partial_index (x) where y > 10"
            )
            conn.exec_driver_sql(
                "create unique index ix_no_partial on foo_with_partial_index (x)"
            )

            inspector = inspect(conn)
            eq_(
                inspector.get_indexes("foo_with_partial_index"),
                [
                    # the two indexes are indistinguishable
                    {
                        "unique": 1,
                        "name": "ix_no_partial",
                        "column_names": ["x"],
                    },
                    {
                        "unique": 1,
                        "name": "ix_partial",
                        "column_names": ["x"],
                    },
                ],
            )
```

### Error

(no error)

### Versions

- OS: openSUSE Linux
- Python: 3.8.15
- SQLAlchemy: current main (9237bf15e612ba82555444751bd69dc2a831e7f4)
- Database: SQLite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): ?

### Additional context

Probably this is similar to the non-handling of expression-based indexes, which are also not handled: https://github.com/sqlalchemy/sqlalchemy/blob/9237bf15e612ba82555444751bd69dc2a831e7f4/lib/sqlalchemy/dialects/sqlite/base.py#L2663-L2669

**Comment by tgpfeiffer** [comment]
I'll see if I can create a PR for this.

**Comment by CaselIT** [comment]
Thanks for looking into it. If partial indexes are similar to expression based ones maybe we could try to add support for both.

Feel free to ask for guidance on this, such as where the test are, etc.

**Comment by zzzeek** [comment]
it looks great.  Are you OK with 2.0 series only  or were you hoping for 1.4 backport?  this is a little bit 2.0-ish as it changes behavior a bit.

**Comment by tgpfeiffer** [comment]
I was hoping for a 1.4 backport :wink: 

This affects us as described in https://github.com/sqlalchemy/alembic/issues/1112 in the sense that any batch operation in an alembic migration on a table with a partial index transforms that partial index into a non-partial one, which could either (1) make the migration fail or (2) make the application fail at a later point in time, where the migration seems to have worked fine. So from my point of view this is a bugfix and I would be happy to have this in the 1.4 release, or we'd have to upgrade our whole application to a 2.0 pre-release... happy to help with any backporting work.

**Comment by sqla-tester** [comment]
**Tobias Pfeiffer** has proposed a fix for this issue in the **main** branch:

**add partial index predicate to SQLiteDialect.get_indexes() result** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4200

**Comment by sqla-tester** [comment]
**Tobias Pfeiffer** has proposed a fix for this issue in the **rel_1_4** branch:

**add partial index predicate to SQLiteDialect.get_indexes() result** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4251

**Comment by zzzeek** [comment]
it's a bit of a troubling backport but we'll get through it
