### ISSUE TITLE
BUG: ``engine.fetchall()`` result does not behave NamedTuple like

### ISSUE THREAD

**Issue by phofl** [sqlalchemy/sqlalchemy#8811]
### Describe the bug

When extracting rows from a table with ``fetchall()`` or ``first()`` the resulting ``Row`` object does not behave NamedTuple-like as described in https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#result-rows-act-like-named-tuples

When trying to access a column by name, this fails.

I added a simple reproduced with sqlite, saw this initially with ms sql.

This is a bit confusing, since using 
``engine = create_engine(connection_string, future=True)`` on SQLAlchemy 1.4.44 worked as expected and returned "test".

### To Reproduce

```python
connection_string = "sqlite+pysqlite:///:memory:"
engine = create_engine(connection_string)

testtable = Table('testtable', MetaData(),
        Column('id', Integer, primary_key=True), Column('foo', String))

testtable.create(engine)

with engine.connect() as conn:
    conn.execute(text("insert into testtable (id, foo) values (1, 'test')"))

    result = conn.execute(
        text(
            f"Select * from testtable"
        )
    ).fetchall()


result[0]["foo"]
```

### Error

```
Traceback (most recent call last):
  File "/Users/patrick/Library/Application Support/JetBrains/PyCharm2022.2/scratches/scratch.py", line 348, in <module>
    result[0]["foo"]
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 67, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
TypeError: tuple indices must be integers or slices, not str
``` 

### Versions

- OS: Ventura 13.0.1
- Python: 3.10
- SQLAlchemy: 2.0.0b3
- Database:sqlite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pysqlite

### Additional context

In case this is the expected behavior now: Would be good to update the docs accordingly.

**Comment by zzzeek** [comment]
for named tuple access, you would refer to `row.foo`, not `row["foo"]`:

```py
Python 3.11.0rc1 (main, Sep  9 2022, 11:22:20) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import namedtuple
>>> R = namedtuple("R", ["foo", "bar"])
>>> row = R("one", "two")
>>> row.foo
'one'
>>> row.bar
'two'
>>> row["foo"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: tuple indices must be integers or slices, not str

```

in 1.4, "future" mode tries to be as forwards-compat as possible, however in this specific case I think we had to make an exception for some reason and still allow subscript access. however, it definitely emits a warning in [migration mode](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings):

```
$ SQLALCHEMY_WARN_20=1 python -Walways test3.py 
/home/classic/dev/sqlalchemy/test3.py:12: RemovedIn20Warning: The current statement is being autocommitted using implicit autocommit, which will be removed in SQLAlchemy 2.0. Use the .begin() method of Engine or Connection in order to use an explicit transaction for DML and DDL statements. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  conn.execute(text("insert into testtable (id, foo) values (1, 'test')"))
/home/classic/dev/sqlalchemy/test3.py:21: RemovedIn20Warning: Using non-integer/slice indices on Row is deprecated and will be removed in version 2.0; please use row._mapping[<key>], or the mappings() accessor on the Result object. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  result[0]["foo"]
```

**Comment by phofl** [comment]
Sorry for that, mixed this up. You are correct, that's what I was trying to do.

Thanks very much
