### ISSUE TITLE
macOS running on Arm doesn't require greenlet

### ISSUE THREAD

**Issue by f0rmiga** [sqlalchemy/sqlalchemy#8813]
### Describe the bug

When locking my requirements.txt file, I get different results on a macOS M1 than on other platforms:

```diff
@@ -327,9 +337,7 @@ greenlet==1.1.2 \
     --hash=sha256:f9d29ca8a77117315101425ec7ec2a47a22ccf59f5593378fc4077ac5b754fce \
     --hash=sha256:fa877ca7f6b48054f847b61d6fa7bed5cebb663ebc55e018fda12db09dcc664c \
     --hash=sha256:fdcec0b8399108577ec290f55551d926d9a1fa6cad45882093a7a07ac5ec147b
-    # via
-    #   -r third_party/python/requirements.txt
-    #   sqlalchemy
+    # via -r third_party/python/requirements.txt
```

`platform_machine` is the same as `platform.machine()`:

```
$ python3
Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'arm64'
```

### To Reproduce

```python
Lock your requirements on a Mac running on Arm (M1, M2) and check the differences it produces compared to other platforms.
```

### Error

N/A

### Versions

- OS: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64
- Python: 3.10.8
- SQLAlchemy: Initially 1.4.34, but also tried on 1.4.44 (latest at this point)
- Database: N/A
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): N/A

**Comment by zzzeek** [comment]
hi -

can you define what you mean by "lock requirements" ?  do you mean "pip freeze" ?   

also make sure you familiarize with the caveats for Apple M1 at https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#asyncio-platform-installation-notes-including-apple-m1

**Comment by zzzeek** [comment]
original issue #6136
