### ISSUE TITLE
[2.0] mypy: Base is not valid as a type

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#8832]
### Describe the bug

When writing code with a declarative_base() as shown in the example at:
https://docs.sqlalchemy.org/en/20/orm/extensions/mypy.html

Mypy produces:
```
models.py:83: error: Variable "app.models.Base" is not valid as a type  [valid-type]
models.py:83: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
```

### Versions

- SQLAlchemy: 2b3
- Mypy: 0.991 (no plugin)

**Comment by Dreamsorcerer** [comment]
Also, `reveal_type(declarative_base())` is `Any`, which doesn't seem right..

**Comment by zzzeek** [comment]
hi -

all code exmaples on that page assume SQLAlchemy's mypy plugin is installed, so if "no plugin" means you didn't install the plugin, that's the expected behavior.

**Comment by Dreamsorcerer** [comment]
Right, but it says the mypy plugin is deprecated and the behaviour in v2 should be better than the plugin...
Is this typing functionality just not ready yet (in the current beta release), or am I misreading that note?

**Comment by zzzeek** [comment]
yes you want this:   https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#migrating-an-existing-mapping
