### ISSUE TITLE
Add `eager_default='auto'` that behaves similarly to `synchronize_session='auto'`

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8889]
If the dialect supports returning, eager default is basically free and can be enabled by default.
See discussion at https://github.com/sqlalchemy/sqlalchemy/discussions/8877#discussioncomment-4242694

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add eager_defaults="auto" for inserts** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4283
