### ISSUE TITLE
reliance on open "git diff" in test suite relies upon git commit status, git presence

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8892]
the entry in tox.ini

```
     sh -c 'python ./tools/generate_tuple_map_overloads.py && git diff --exit-code'
     sh -c 'python ./tools/generate_proxy_methods.py && git diff --exit-code'
     sh -c 'python ./tools/sync_test_files.py && git diff --exit-code'
```

breaks if I run tox -e pep8 without committing all my files.  it would be better if each script supported it's own "diff" mode that returned diffs for the files it is targeting, without relying upon the git tree.

**Comment by CaselIT** [comment]
Yes, I thought of that too.

Or the global interface could do that.
I'll try thinking of something

**Comment by zzzeek** [comment]
gonna try something today, that ok?  assuming you didnt start this yet

**Comment by CaselIT** [comment]
sure go ahead

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**refactor code generation tools , include --check command** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4369
