### ISSUE TITLE
SQLite reflection doesn't detect DEFERRABLE and INITIALLY options on foreign keys

### ISSUE THREAD

**Issue by mgorven** [sqlalchemy/sqlalchemy#8903]
### Describe the bug

SQLite [supports foreign keys](https://www.sqlite.org/syntax/foreign-key-clause.html) with the `DEFERRABLE` and `INITIALLY` options. Reflection doesn't detect these however, which causes bogus Alembic changes if these are used.

### To Reproduce

```python
from sqlalchemy import create_engine, inspect
conn = create_engine("sqlite:///:memory:").connect()
conn.exec_driver_sql("CREATE TABLE test1 (id INTEGER)")
conn.exec_driver_sql("CREATE TABLE test2 (ref INTEGER, CONSTRAINT ref FOREIGN KEY(ref) REFERENCES test1(id) DEFERRABLE INITIALLY DEFERRED)")
print(inspect(conn).get_foreign_keys("test2"))
```

### Error

```
[{'name': 'ref', 'constrained_columns': ['ref'], 'referred_schema': None, 'referred_table': 'test1', 'referred_columns': ['id'], 'options': {}}]
``` 
`options` is empty.

### Versions

- OS: Linux
- Python: 3.10
- SQLAlchemy: 1.4.44
- Database: SQLite
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pysqlite

**Comment by zzzeek** [comment]
we can accept PRs for this.   We just merged a similar PR for indexes that use `sqlite_where` and that was backported to 1.4.x..

**Comment by mgorven** [comment]
> we can accept PRs for this. We just merged a similar PR for indexes that use `sqlite_where` and that was backported to 1.4.x..

#8904 for main. Should I make a separate PR for 1.4?

**Comment by zzzeek** [comment]
This looks short (that was fast too thanks) I can just cherry-pick it just as easily, thanks

**Comment by sqla-tester** [comment]
**Michael Gorven** has proposed a fix for this issue in the **main** branch:

**[sqlite] Reflect DEFERRABLE and INITIALLY options for foreign keys** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4253

**Comment by sqla-tester** [comment]
**Michael Gorven** has proposed a fix for this issue in the **rel_1_4** branch:

**[sqlite] Reflect DEFERRABLE and INITIALLY options for foreign keys** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4255
