### ISSUE TITLE
sphinx formatting of param annotations seems to have been screwed up

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8920]
this looks different on 1.4 and 2.0 but in both cases I am suspecting the zzzeeksphinx extension is getting involved and making things worse.  We really need to turn off display of annotations if they are going to look this bad.

https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Table.to_metadata

https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.Table.to_metadata

![Screenshot from 2022-12-01 16-21-29](https://user-images.githubusercontent.com/128223/205161710-4d370b9b-e32f-43d6-8901-381b179bc8e7.png)
![Screenshot from 2022-12-01 16-21-56](https://user-images.githubusercontent.com/128223/205161787-2558736d-4055-4160-be44-8bbe99b8a2ec.png)

**Comment by zzzeek** [comment]
keeping in mind sphinx has been updated a few times, so it's likely something has regressed

**Comment by CaselIT** [comment]
Sphinx seems to have various options for the type annotations: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints

**Comment by zzzeek** [comment]
it's not a systemic issue.  in 2.0, most docstrings look great.  for this string, it's caused specifically by `Literal[SchemaConst.RETAIN_SCHEMA]` in the signature.  so some kind of sphinx bug.

**Comment by zzzeek** [comment]
seems to be a cooincidence that the same method in 1.4 has a problem for a different reason, but involving the same argument.

**Comment by zzzeek** [comment]
I've posted https://github.com/sphinx-doc/sphinx/issues/11156 for the 2.0 version of the issue.

**Comment by zzzeek** [comment]
for 2.0, this seems to have resolved:

![image](https://github.com/sqlalchemy/sqlalchemy/assets/128223/1d5ab7aa-91cb-4bbf-a01b-2ef6f93f652f)


it's not clear if this is because a. they are using `|` now for optional instead of `Optional` b. they just fixed the bug outright even though https://github.com/sphinx-doc/sphinx/issues/11156 is still open

for 1.4, our use of `symbol` still messes it up, so I think "a." is our answer for above, it just happens to be working now.

in any case i dont have any good system on this end to change any of this so closing.
