### ISSUE TITLE
extend_existing will dupe columns if key is a differentiator, needs to warn or resolve

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8925]
```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import select
from sqlalchemy import Table
from sqlalchemy import text


e = create_engine("sqlite://", echo=True)
with e.begin() as conn:
    conn.execute(
        text(
            """
create table t (
    a integer,
    b integer
)
"""
        )
    )

m = MetaData()

t = Table(
    "t",
    m,
    Column("a", Integer),
    Column("b", Integer, key="b2"),
)

m.reflect(
    e,
    extend_existing=True,
    # autoload_replace=False,  # prevents issue
)
print(select(t))

```

```
SELECT t.a, t.b, t.b AS b_1 
FROM t
```

Table should never under any circumstances have two Column objects with the same name, regardless of .key

**Comment by zzzeek** [comment]
it only happens for metadata.reflect(), not table autoload_with

**Comment by zzzeek** [comment]
not too surprisingly this can break things if a program is relying on the old behavior, because we dont want to mutate a Column, we want to warn and replace the column as instructed.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**disallow same-named columns, unchecked replacement in Table** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4263
