### ISSUE TITLE
Use native paramstyle in asyncpg dialect

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8926]
Replace the asyncpg paramstyle from format to numeric, using `$` instead of the standard `:`.

The main advantage of this style is that allows repeated parameters to not be duplicated

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Rewrite positional handling, test for "numeric"** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4225
