### ISSUE TITLE
Remove non functional `AsyncResult.merge` method

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#8952]
This method was a refuse dating back the the first introduction of asyncion in sqlalchemy in 5fb0138a3220161703e6ab1087319a669d14e7f4.

This method is non functional, since it's a sync method that does async io, and since no-one ever reported an issue about it, it appears it's not in active usage.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Better syncronize async result docs with plain ones.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4281

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **rel_1_4** branch:

**Better syncronize async result docs with plain ones.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4282
