### ISSUE TITLE
HasTableTest assumes support for SELECT * in CREATE VIEW

### ISSUE THREAD

**Issue by gordthompson** [sqlalchemy/sqlalchemy#8960]
### Describe the bug

`HasTableTest` currently creates views as

```sql
CREATE VIEW vv AS SELECT * FROM test_table
```

and not all databases support that (e.g., CockroachDB, see "To Reproduce") resulting in test suite errors.

### To Reproduce

```python
gord@gord-dv7:~$ ./crdb_sql.sh 
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# …
#
root@localhost:26257/defaultdb> create table t (id int primary key, data varchar(50));
CREATE TABLE


Time: 307ms total (execution 307ms / network 1ms)

root@localhost:26257/defaultdb> create view vv as select * from t;
ERROR: unimplemented: views do not currently support * expressions
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/10028/v22.2
```

### Error

```
ERROR: unimplemented: views do not currently support * expressions
``` 

### Versions

- OS: (any)
- Python: (any)
- SQLAlchemy: 2.0.0b4
- Database: CockroachDB
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): sqlalchemy-cockroachdb

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **main** branch:

**Specify view columns in HasTableTest** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4284

**Comment by zzzeek** [comment]
if you provide a 1.4 backport and we merge that, we can update the milestone to 1.4.x

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **rel_1_4** branch:

**Specify view columns in HasTableTest** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4288
