### ISSUE TITLE
freeze does not work for textual SQL

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8963]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/8962

```py

import sqlalchemy as sa

metadata = sa.MetaData()

user = sa.Table(
    "user",
    metadata,
    sa.Column("user_id", sa.Integer, primary_key=True),
    sa.Column("user_name", sa.String(16), nullable=False),
    sa.Column("email_address", sa.String(60)),
    sa.Column("nickname", sa.String(50), nullable=False),
)

db_uri = "sqlite:///"
engine = sa.create_engine(db_uri, future=True)
user.create(bind=engine)
with engine.connect() as conn:
    result = conn.execute(sa.select(user))
    frozen = result.freeze()

    # both fail
    result = conn.execute(sa.text("select * from user"))
#    result = conn.exec_driver_sql("select * from user")
    frozen = result.freeze()


```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**look out for extras=None in freeze** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4286

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**look out for extras=None in freeze** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4287

**Comment by CaselIT** [comment]
strange that typing tools did not catch it

**Comment by zzzeek** [comment]
I dont think we're typed on that stuff are we

**Comment by CaselIT** [comment]
ah, it's typed as `Sequence[Any]`
