### ISSUE TITLE
sqlalchemy 2.0 uber warning

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8983]
when a SQLALCHEMY_WARN_20 warning is encountered, and the variable is not set:

1. do a single warning, with a boolean switch so that it is not emitted again, even if their warnings filter is set to "always"
2. warning should include that the program has breaking changes, links to the errors.rst page with background on upgrading
3. also should note pinning requirements to < 2
4. I like the idea of doing an isatty() check and adding colors

**Comment by zzzeek** [comment]
* use FutureWarning?
* Py2 code, just ignore the whole thing, py2 is long EOL

**Comment by CaselIT** [comment]
> * Py2 code, just ignore the whole thing, py2 is long EOL 

also 3.6 since it's not supported on v2

**Comment by zzzeek** [comment]
sure, i think nobody is using py36 anymore either

**Comment by zzzeek** [comment]
trove classifiers are good enough that if I said "pip install sqlalchemy" in py36, it would not install 2.0, is that correct?

**Comment by lelit** [comment]
> trove classifiers are good enough that if I said "pip install sqlalchemy" in py36, it would not install 2.0, is that correct?

Uhm, I doubt: I may be wrong, and recent `pip` may very well do that, but IIRC _old enough_ `pip` did not consult Trove classifiers to determine that.

**Comment by lelit** [comment]
I had to actively check that for example in [rapidjson](https://github.com/python-rapidjson/python-rapidjson/blob/master/setup.py#L27).

**Comment by zzzeek** [comment]
i think it would be best if we just did a simple py3 check.

ignoring py2 is just so that we dont have to test the warning etc. , the py2 base nearly nonexistent now (source: https://pypistats.org/packages/sqlalchemy)

**Comment by CaselIT** [comment]
We have this.
https://github.com/sqlalchemy/sqlalchemy/blob/a8d76cff39dbaf6354d42d35cd68332df469d124/setup.cfg#L34
It should be enough

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**add uber warning for 1.4** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4335

**Comment by zzzeek** [comment]
this was done in [4f7b6a0](https://github.com/sqlalchemy/sqlalchemy/commit/4f7b6a095590e1216c44935e7a7ba725733ca8d5) and released
