### ISSUE TITLE
per-dialect / compiler extensibility for _BIND_TRANSLATE_RE / _BIND_TRANSLATE_CHARS

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8994]
see #8993

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**make bind escape lookup extensible** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4308
