### ISSUE TITLE
Importing sqlalchemy superfluously forks off file command

### ISSUE THREAD

**Issue by gsauthof** [sqlalchemy/sqlalchemy#8995]
### Describe the bug

With the November SQLalchemy 1.4.44 update simply importing `sqlalchemy` now forks of the `file` utility.
This is new behavior in the 1.4 branch and a **regression** when you are running your Python program under a relatively strict seccomp filter, SELinux policy or similar that doesn't allow vfork/pipe2/wait4 syscalls, because your program isn't expected to use those.

Importing `sqlalchemy` now calls the `file` utility because it calls `platform.architecture()` in order to initialize its `is64bit` field (in `lib/sqlalchemy/util/compat.py`).
However, this call is superfluous because the information the `file` call provides is ignored.

Thus, a better way to initialize that field is to write

```
is64bit = sys.maxsize > 2**32
```

as [recommended](https://docs.python.org/3/library/platform.html#platform.architecture) by Python's standard library documentation.

See also:

- [Introducing commit in 1.4 branch](https://github.com/sqlalchemy/sqlalchemy/commit/3d892381996e7ba68ee3bf6d7de40c8414e3812a)
- [Introducing commit in 2 branch](https://github.com/sqlalchemy/sqlalchemy/commit/9f4ac8d155f58b59cf314cfbc73195ed51a0c146)

### To Reproduce

```python
strace -y -f -o s.log python3 -c 'import sqlalchemy'
grep 'fork\|pipe2\|wait\|exec' s.log
```

### Error

```
1326150 execve("/usr/bin/python3", ["python3", "-c", "import sqlalchemy"], 0x7ffcbd5f4910 /* 44 vars */) = 0
1326150 pipe2([3<pipe:[8138992]>, 4<pipe:[8138992]>], O_CLOEXEC) = 0
1326150 pipe2([6<pipe:[8138993]>, 7<pipe:[8138993]>], O_CLOEXEC) = 0
1326150 vfork( <unfinished ...>
1326151 execve("/home/gms/local/bin/file", ["file", "-b", "/usr/bin/python3.10"], 0x7fafb2af6cc0 /* 45 vars */) = -1 ENOENT (No such file or directory)
1326151 execve("/usr/local/bin/file", ["file", "-b", "/usr/bin/python3.10"], 0x7fafb2af6cc0 /* 45 vars */) = -1 ENOENT (No such file or directory)
1326151 execve("/usr/bin/file", ["file", "-b", "/usr/bin/python3.10"], 0x7fafb2af6cc0 /* 45 vars */ <unfinished ...>
1326150 <... vfork resumed>)            = 1326151
1326151 <... execve resumed>)           = 0
1326151 write(1<pipe:[8138992]>, "ELF 64-bit LSB pie executable, x"..., 204) = 204
1326150 <... read resumed>"ELF 64-bit LSB pie executable, x"..., 8192) = 204
1326150 wait4(1326151, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 1326151
``` 

When running under a seccomp filter that doesn't allow pipe2/vfork/wait4 you would get a core file for which gdb would print something like:

```
Program terminated with signal SIGSYS, Bad system call.
```

### Versions

- OS: Fedora 35 and 37
- Python: 10 and 11
- SQLAlchemy: 1.4.44 (but also present in version 2 branch)
- Database: all
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): all

**Comment by zzzeek** [comment]
thanks for reporting!

**Comment by zzzeek** [comment]
python standard lib docs should definitely warn for this

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**dont call platform.architecture()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4309

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**dont call platform.architecture()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4310
