### ISSUE TITLE
add new requirements for various DB characters for DifficultParametersTest

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9002]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/8993

we'd like to make some rules for column names as the DifficultParametersTest, while we escape all bind names, we can't escape those chars in a database column, so add a req for test_round_trip_same_named_column

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add exclusion for unusual chars in column names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4314

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**add exclusion for unusual chars in column names** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4315
