### ISSUE TITLE
Execution of select query returns wrong values (floats become very large integers)

### ISSUE THREAD

**Issue by SimoneD89** [sqlalchemy/sqlalchemy#9030]
### Describe the bug

I hit the following bug by trying to use the module scriptforge (to use python functions in libreoffice Calc).

I've tried to reduce the example as much as possible. The script imports a float number from a sql query. When executed from shell it returns -0.65, when executed from libreoffice calc it returns -650000000. I suspect it is related to local configurations (see e.g. bug https://github.com/mkleehammer/pyodbc/issues/753). 

### To Reproduce

```python
 ├── script.py
 ├── module.py

script.py
---------
from scriptforge import CreateScriptService
from module import import_float


def test(args=None) -> None:
    float_number = float(import_float())

    doc = CreateScriptService("Calc")
    doc.SetValue("A12", float_number)
    return None


module.py
---------
import os
import urllib

from sqlalchemy import create_engine


def import_float(args=None) -> float:
    # Connection to the server
    driver = "{ODBC Driver 17 for SQL Server}"
    url, database, uid, pwd = ...
    params = urllib.parse.quote(
        "DRIVER=" + driver + ";"
        "SERVER=" + url + ";"
        "DATABASE=" + database + ";"
        "UID=" + uid + ";"
        "PWD=" + pwd
    )
    engine = create_engine(
        "mssql+pyodbc:///?odbc_connect=%s" % params
    )
    conn = engine.connect()

    # Query to select a single float number [decimal(38, 9)]
    query = (
        "SELECT TOP 1 column FROM Table"
    )

    float_number = list(conn.execute(query))[0][0]
    conn.close()

    return float_number
```

### Error

It returns -650000000 instead of -0,65 when the test function (in scripy.py) is executed from libreoffice Calc. If I put the `import_float` function inside script.py it correctly returns -0.65. In the past I already hit similar bugs without using scriptforge/libreoffice).

### Versions

- OS: fedora 37, kernel 6.0.11-300.fc37.x86_64
- Python: 3.11.1
- SQLAlchemy: 1.4.45
- Database: Microsoft SQL Server
- DBAPI: mssql - pyodbc 4.0.35)

**Comment by zzzeek** [comment]
hi -

it looks like you are illustrating the bug that you've referred towards at https://github.com/mkleehammer/pyodbc/issues/753 .   SQLAlchemy is not involved in the example provided above outside of creating a connection and does not generally try to work around bugs that should be fixed in the driver.
