### ISSUE TITLE
Docs error: MySQL SSL Connections connect_args example is wrong

### ISSUE THREAD

**Issue by bialix** [sqlalchemy/sqlalchemy#9031]
### Describe the bug

https://docs.sqlalchemy.org/en/14/dialects/mysql.html#ssl-connections

First example here shows how to using the [create_engine.connect_args](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.connect_args) dictionary. It has error: items in "ssl" subdictionary must not have "ssl_" prefix.

Using your example I can't establish SSL connection to my MySQL server.
But using second example with encoding parameters to DB URL does work.

So, I've checked with debug print what parameters arrived to the pymysql Connect() object and found out they are in "ssl" dict and all keys without "ssl_" prefix. After fixing my connect_args to be without "ssl_" prefix - the code works as expected.

### To Reproduce

```python
Our admin created special user_ssl in MySQL which requires using only SSL connections to database. 

        url = "mysql+pymysql://user_ssl:password@192.168.130.123:3306/base?charset=utf8mb4"
        connect_args = {
            "ssl": {
                "ssl_ca": "mysql-ssl/ca.pem",             # should be "ca"
                "ssl_cert": "mysql-ssl/client-cert.pem",  # should be "cert"
                "ssl_key": "mysql-ssl/client-key.pem",    # should be "key"
                "ssl_check_hostname": False,              # should be "check_hostname"
            }
        }
        self.engine = sa.create_engine(
            url,
            echo=echo,
            future=True,
            pool_recycle=pool_recycle,
            connect_args=connect_args,
        )

Then do any SQL select and get error.
```

### Error

```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'user_ssl'@'192.168.31.78' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
``` 

### Versions

- OS: Windows
- Python: 3.10
- SQLAlchemy: 1.4.45
- Database: MySQL
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): pymysql

**Comment by zzzeek** [comment]
thanks for reporting
