### ISSUE TITLE
(1.4.45) Docs small error: import URL class from sqlalchemy.engine

### ISSUE THREAD

**Issue by bialix** [sqlalchemy/sqlalchemy#9032]
### Describe the bug

https://docs.sqlalchemy.org/en/14/core/engines.html#creating-urls-programmatically

This section explains how to create DB URL programmatically. Unfortunately example there is not quite correct. In 1.4.45 I should use ```from sqlalchemy.engine import URL```.

### To Reproduce

```python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.4.45'
>>> from sqlalchemy import URL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'URL' from 'sqlalchemy' (D:\Temp\venv\lib\site-packages\sqlalchemy\__init__.py)
>>> from sqlalchemy.engine import URL
>>> URL
<class 'sqlalchemy.engine.url.URL'>
```

### Error

ImportError

### Versions

- OS:
- Python: 3.10
- SQLAlchemy: 1.4.45
- Database:
- DBAPI (eg: psycopg, cx_oracle, mysqlclient):

**Comment by CaselIT** [comment]
This is 1.4 only, since for v2 the import is correct
