### ISSUE TITLE
support or raise for ORM DML + lambda statements

### ISSUE THREAD

**Issue by Alexxxir** [sqlalchemy/sqlalchemy#9033]
### Describe the bug

The error is raised when a new criteria is added to update query after a method `values` with a field of type UUID.

### To Reproduce

```python
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, create_engine, lambda_stmt, update
from sqlalchemy.orm import Session
import uuid


Base = declarative_base()


class Table(Base):
    __tablename__ = "table"

    id = Column(Integer, primary_key=True)
    data = Column(
        postgresql.UUID(as_uuid=True),
    )


engine = create_engine('postgresql://postgres:postgres@localhost/postgres', echo=True)
Base.metadata.create_all(engine)

session = Session(bind=engine)

uuid_ = uuid.uuid4()

stmt = lambda_stmt(lambda: update(Table))
stmt += lambda s: s.where(Table.id == 21)
stmt += lambda s: s.values(data=uuid_)

session.execute(stmt)  # no error

stmt = lambda_stmt(lambda: update(Table))
stmt += lambda s: s.values(data=uuid_)
stmt += lambda s: s.where(Table.id == 21)

session.execute(stmt)  # error
```

### Error

```
Traceback (most recent call last):
  File "/sqlalchemy_test.py", line 37, in <module>
    session.execute(stmt)
  File "/sqlalchemy/orm/session.py", line 1662, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/sqlalchemy/orm/persistence.py", line 1843, in orm_pre_session_exec
    update_options = cls._do_pre_synchronize_evaluate(
  File "/sqlalchemy/orm/persistence.py", line 1951, in _do_pre_synchronize_evaluate
    crit += statement._where_criteria
TypeError: can only concatenate tuple (not "list") to tuple
```

### Versions

- OS: MacOS
- Python: 3.10
- SQLAlchemy: 1.4.45
- Database: Postgresql

**Comment by zzzeek** [comment]
hi -

there's no reason to use lambda SQL with update() statements and there is currently no test support with DML + lambdas so I would forego using this feature for now.

**Comment by zzzeek** [comment]
alternatively, turn of synchronize_session:

    session.execute(stmt, execution_options={"synchronize_session": None}) 

it's unlikely that lambda SQL can work with synchronize_session so the likely fix here is to raise an informative error.

**Comment by Alexxxir** [comment]
It seems in this case I get the wrong statement, with an extra condition

```python
stmt = lambda_stmt(lambda: update(Table))
stmt += lambda s: s.values(data=uuid_)
stmt += lambda s: s.where(Table.id == 21)

session.execute(stmt, execution_options={"synchronize_session": False})

# INFO sqlalchemy.engine.Engine UPDATE "table" SET data=%(data)s WHERE "table".id = %(id_1)s AND "table".id = %(id_2)s
# INFO sqlalchemy.engine.Engine [generated in 0.00029s] {'data': UUID('650ca199-771f-41b5-921a-4e453a8a6b53'), 'id_1': 21, 'id_2': 21}
```

**Comment by zzzeek** [comment]
yeah I would lean towards just raising an informative error that lambdas are not supported with ORM DML right now

**Comment by Alexxxir** [comment]
Ok, thanks

**Comment by zzzeek** [comment]
okey doke this might be somehting very small.  the larger effort is the tests but i think the simple case above should be doable

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure whereclause, returning copied as tuples** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4331

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**ensure whereclause, returning copied as tuples** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4332
