### ISSUE TITLE
Typo in connections.rst: "LamdaElement" should be "LambdaElement"

### ISSUE THREAD

**Issue by lelit** [sqlalchemy/sqlalchemy#9034]
### Describe the bug

In both 1.4 and 2.0 `doc/build/core/connections.rst` the [LambdaElement](https://docs.sqlalchemy.org/en/20/core/foundation.html#sqlalchemy.sql.expression.LambdaElement) is misreferenced as `LamdaElement`

### To Reproduce

```python
$ git grep LamdaElement
```

### Error

```
doc/build/core/connections.rst:SQL string it will produce.   The :class:`_sql.LamdaElement` and related
``` 

### Versions

- SQLAlchemy: 1.4 and 2.0rc

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. Feel free to just create a PR for documentation only fixes (if you're planning on submitting a PR)

**Comment by lelit** [comment]
Ok.

**Comment by lelit** [comment]
Actually, two of them, one for each branch, right?

**Comment by CaselIT** [comment]
Usually the PR is only one and then me or mike cherry picks, but two PR also work

**Comment by lelit** [comment]
Ok, #9037 is against `rel_1_4` branch.

**Comment by lelit** [comment]
Thank you. As I could not check the _pickability_ of the change into v2, just drop me a note if you'd prefer having a specific PR for that.

**Comment by lelit** [comment]
Oh, I missed the second commit, sorry for the noise.

**Comment by CaselIT** [comment]
No problem. It's easy to cherry pick locally, since I need to push to gerrit in any case when merging from GitHub (it's automatic only in gerrit-> GitHub direction)
