### ISSUE TITLE
Unify operator definition in postgresql

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9041]
In the postgresql there are some operators that are defined multiple times, like the `@>` for range, array, hstore, range.
We could probably clean things up a bit by having them defined only once

**Comment by jazzthief** [comment]
Hey @CaselIT, I looked into these operators and in `HSTORE` `contains()`, for example, is done with `operate()` taking a `custom_op` defined earlier in the file; while in `AbstractRange` the same thing is done with `expr.op()` taking the `@>` directly. Is there some reasoning behind it, or should we try to get all of it written the same way?

**Comment by CaselIT** [comment]
That was mainly the reason for the issue. I've not looked at this in a while, so I'm not sure if there is a reason for the current implementation, or if most of the custom operations could be make common for all postgresql types

**Comment by jazzthief** [comment]
> That was mainly the reason for the issue. I've not looked at this in a while, so I'm not sure if there is a reason for the current implementation, or if most of the custom operations could be made common for all postgresql types

Got you. I can't see how to do it best yet - but will try. Perhaps with just the `@>` for starters

**Comment by jazzthief** [comment]
Ok, I got away with just importing a definition of `CONTAINS` from `HSTORE` and using it in `AbstractRange` - no tests failed. If I were to go any further, it would require to export the definitions from one place: where should I put them? The way I see it, it is either `postgresql.base`, or a separate defs file just like we have for `postgresql.types`. @CaselIT what do you think?

**Comment by CaselIT** [comment]
It may make sense to create a operators.py module in postgresql so we can move there all the various operators.

At this point it may make sense also change range to use operators like json, array and hstore.

let's see also if @zzzeek has preferences on this?

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improve PostgreSQL custom operators** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4636
