### ISSUE TITLE
[asyncpg] rowcount not returned for SELECT statements

### ISSUE THREAD

**Issue by mgorven** [sqlalchemy/sqlalchemy#9048]
### Describe the use case

`cursor.rowcount` always returns -1 for SELECT statements.

### Databases / Backends / Drivers targeted

asyncpg

### Example Use

```
result = await connection.execute(text("SELECT * FROM test"))
print(result.rowcount)
```

**Comment by zzzeek** [comment]
I would be -1 on this (no pun intended) if this only works on asyncpg.    DBAPI rowcount is only supposed to be for DML statements.

If this is relevant to a CTE INSERT, then it should work for all the PostgreSQL drivers and we'd need all-pg-backend tests which exercise this.  the bug would be that no test is exercising this right now.

**Comment by mgorven** [comment]
> If this is relevant to a CTE INSERT, then it should work for all the PostgreSQL drivers and we'd need all-pg-backend tests which exercise this. the bug would be that no test is exercising this right now.

It does work for psycopg2 at least, I can check the other dialects.

**Comment by mgorven** [comment]
All the other postgresql drivers support it already (I haven't tested py-postgresql because I think it needs an older python version). #9049 adds a test for this (is `MiscBackendTest` the right place?)

**Comment by zzzeek** [comment]
miscbackend is probably fine sure.    psycopg2, psycopg, and asyncpg are the three we normally try to keep together

**Comment by sqla-tester** [comment]
**Michael Gorven** has proposed a fix for this issue in the **main** branch:

**[asyncpg] Extract rowcount for SELECT statements** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4340
