### ISSUE TITLE
Add mapper param that allows mapped class that does not expect instantitaion

### ISSUE THREAD

**Issue by daemonkeeper** [sqlalchemy/sqlalchemy#9060]
### Describe the use case

See the full discussion here: https://github.com/sqlalchemy/sqlalchemy/discussions/8959

As an outcome of that discussion, please redefine the [__abstract__ attribute](https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/api.html#abstract), and allow it to be either set to:

``True``, ``full``: fully abstract class (the existing meaning of the attribute; backwards-compatible, while suggesting in the docs to not use a boolean for it in new code)
``virtual``, or ``polymorphic``: abstract class, allowed to be used relational target in ``relationship()`` 

Actual naming of the flag values are of course changeable at you discretion.

Setting it to ``virtual`` would make the class purely abstract, but allow it to be used on the left side of a relationship() foreign-key relation. Intent of the change is to allow relationships into sub-classes of a polymorphic type, where only a subset of the classes support a certain foreign key. Here's an example:

```python
class TeamMixIn:
    team_id: Mapped[int|None] = mapped_column(ForeignKey("teams.id"), init=False, use_existing_column=True, repr=False)

    @declared_attr.cascading
    def team(_cls) -> Mapped["Team"]:
        return relationship(back_populates="user", init=False, repr=True)


class User(BaseModel):
    __tablename__ = "users"
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]
    user_type: Mapped[str] = mapped_column(init=False, repr=False)

    __mapper_args__ = {
        "polymorphic_identity": "user",
        "polymorphic_on": "user_type",
    }

class HasTeams(User, TeamMixIn):
   __abstract__ = 'virtual'

class Engineer(HasTeams):
    __mapper_args__ = {
        "polymorphic_identity": "engineer",
    }

class Accounting(HasTeams):
    __mapper_args__ = {
        "polymorphic_identity": "accounting",
    }

class Manager(User):
    __mapper_args__ = {
        "polymorphic_identity": "hr",
    }


class Team(BaseModel):
    __tablename__ = "teams"
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]
    user: Mapped[HasTeams] = relationship(back_populates="team", init=False)
```

Now, the foreign key from Team can be either an Engineer class instance, or an Accounting class instance, but never a Manager instance. 

### Databases / Backends / Drivers targeted

Purely declarative; no actual database backend

### Example Use

No changes to existing SQL; relationship() already builds the correct SQL queries

**Comment by zzzeek** [comment]
we will have to haggle over the terminology.   "virtual" seems like a word with a lot of baggage :)  

another word we wont use, but describes the sentiment, is `__abstract__ = 'map_the_class_anyway_but_dont_allow_instantiation'`.

I usually write those words out to get ideas for the best terminology.

**Comment by zzzeek** [comment]
this parameter has to be at the very least a param on ``Mapper`` itself.   Since this is not a widely requested feature, I think for now we should start with it being a parameter that in declarative one would place in ``__mapper_args__`` for now, this does not preclude there being some attribute value for ``__abstract__`` in the future however I think that would be redundant:

```py
class HasTeams(User, TeamMixIn):
   __mapper_args__ = {"abstract": True}
```

**Comment by jvanasco** [comment]
> we will have to haggle over the terminology. "virtual" seems like a word with a lot of baggage :)

This seems somewhat related to a "virtual foreign keys" idea I had a few years ago (see #5601 and the gerrit).  We ultimately settled on @zzzeek's idea of calling this "indirect foreign keys", though I pulled the PR.

Anyways, it sounds like "indirect" might work here.

**Comment by zzzeek** [comment]
I just took a look at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2249/8/doc/build/orm/join_conditions.rst and...im not seeing the relationship here.   I'm currently documenting this as an extension to ORM inheritance, mostly single inheritance.

**Comment by jvanasco** [comment]
I just meant the reading of the term seems to work on their description, as both concepts seem to be around indirect placeholders.   e.g.

> Setting it to `indirect` would make the class purely abstract, but allow it to be used on the left side of a relationship() foreign-key relation. Intent of the change is to allow relationships into sub-classes of a polymorphic type, where only a subset of the classes support a certain foreign key

**Comment by zzzeek** [comment]
I was calling this ``Mapper.polymorphic_abstract = True``.  the word "abstract" is the most descriptive here but since that word is a little ambiguous, and this parameter is very specific to polymorphic behavior, it's strictly a small option within the scope of inheritance mappings.

**Comment by jvanasco** [comment]
I like `polymorphic_abstract`, but I do not like the `abstract_polymorphic` above.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**implement polymorphic_abstract=True feature** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4362
