### ISSUE TITLE
Wrong dataclass_transform parameter name used for DCTransformDeclarative

### ISSUE THREAD

**Issue by ImogenBits** [sqlalchemy/sqlalchemy#9067]
### Describe the bug

This is basically the same issue that happened to pydantic [here](https://github.com/pydantic/pydantic/issues/4500). Previous versions of PEP 681 had `dataclass_transform` take a parameter called `field_descriptors` but this name was changed to `field_specifiers`. SQLAlchemy still uses the old name for `MappedAsDataclass`, [here](https://github.com/sqlalchemy/sqlalchemy/blob/a76f4cbb7d3066f71b035b29e511eb811b810c9c/lib/sqlalchemy/orm/decl_api.py#L147).

### To Reproduce

```python
from typing import reveal_type
from sqlalchemy.orm import DeclarativeBase, mapped_column, Mapped, MappedAsDataclass

class Model(MappedAsDataclass, DeclarativeBase):
    a: Mapped[int] = mapped_column(default=1)

reveal_type(Model.__init__)
```

### Error

```
Type of "Model.__init__" is "(self: Model, a: SQLCoreOperations[int] | int = mapped_column(default=1)) -> None"
``` 

### Versions

- Python: 3.11
- SQLAlchemy: 2.0.0rc1

### Additional context

The type of the init method should be `(self: Model, a: SQLCoreOperations[int] | int = 1) -> None`, which it is if the `dataclass_transform` call on `DCTransformDeclarative` uses the correct parameter name.

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting. Since mypy doesn't support this I guess it was not detected, since we are not currently running pyright on the code

@zzzeek maybe it would be good to try have also pyright run on the code (assuming it would detect this error)?

**Comment by CaselIT** [comment]
> Hi,
> 
> Thanks for reporting. Since mypy doesn't support this I guess it was not detected, since we are not currently running pyright on the code
> 
> @zzzeek maybe it would be good to try have also pyright run on the code (assuming it would detect this error)?

It seems pyrigth still accepts both, so it would not have helped in any case:
https://github.com/microsoft/pyright/blob/ddc6932b9c53b09b9b32926addbcefcab37b9b2a/packages/pyright-internal/src/analyzer/dataClasses.ts#L802-L807

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Use field_specifiers instead of deprecated field_descriptors** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4346
