### ISSUE TITLE
@hybrid_method would actually work in typing as an instance method + class method with explicitly typed args 

### ISSUE THREAD

**Issue by AlexanderPodorov** [sqlalchemy/sqlalchemy#9096]
### Describe the bug

SQLAlchemy 2.0 new typing system has typing issues with @hybrid_method decorator:
1. Once a method is decorated, all type checks for arguments are missing
2. Decorator return type is incompatible with `select(...).where(...)`. Type checker gives us a warning in place of `where`

P.S. Thank you very much for SQLAlchemy!

### To Reproduce

```python
# Sample code taken from documentation
# https://docs.sqlalchemy.org/en/20/orm/extensions/hybrid.html
# Modified and properly typed
# See below code, type checker: pyright.

from sqlalchemy.orm import DeclarativeBase, MappedAsDataclass, Mapped, mapped_column
from sqlalchemy.ext.hybrid import hybrid_method
from sqlalchemy import select



class Base(DeclarativeBase, MappedAsDataclass):
    pass


class Interval(Base):
    __tablename__ = 'interval'

    id: Mapped[int] = mapped_column(primary_key=True)
    start: Mapped[int] = mapped_column()
    end: Mapped[int] = mapped_column()

    @hybrid_method
    def contains(self, point: int, p2: int, p3: int) -> bool:
        return (self.start <= point) & (point <= self.end)


# type: SQLCoreOperations[bool]
# no warnings for incorrect arguments: first, second and third argument must be int
cond = Interval.contains('dfdf')

# warning: type SQLCoreOperations[bool] is incompatible with any of accepted types
s = select(Interval).where(cond)
```

### Error

See type checker warnings in the comments to example code.

### Versions

- OS: MacOS
- Python: 3.11.1
- SQLAlchemy: 2.0.0rc2

**Comment by zzzeek** [comment]
we'd have to use pep-612 for this which may still cause errors with mypy depending on how far along they've gotten with it

**Comment by zzzeek** [comment]
also this is nothing new in 2.0, do you have an example of stubs that were previously "working" ?

**Comment by zzzeek** [comment]
yeah I dont think this is really possible with Python typing.  This patch would get us closer, however, I don't know how to make it recognize the method as an instance method, and then as far as it being both an instancemethod and a classmethod, this is likely impossible.  My experiments with typing have shown that it's impossible to make any decorator that indicates a method is a classmethod other than using `@classmethod` directly in the source.


```diff
diff --git a/lib/sqlalchemy/ext/hybrid.py b/lib/sqlalchemy/ext/hybrid.py
index 657bc8c6e6..7cdd00a177 100644
--- a/lib/sqlalchemy/ext/hybrid.py
+++ b/lib/sqlalchemy/ext/hybrid.py
@@ -784,7 +784,13 @@ class _HybridExprCallableType(Protocol[_T_co]):
         ...
 
 
-class hybrid_method(interfaces.InspectionAttrInfo, Generic[_T]):
+from typing import Callable
+from sqlalchemy.util.typing import ParamSpec
+
+P = ParamSpec("P")
+R = TypeVar("R")
+
+class hybrid_method(interfaces.InspectionAttrInfo, Generic[P, R]):
     """A decorator which allows definition of a Python object method with both
     instance-level and class-level behavior.
 
@@ -795,8 +801,8 @@ class hybrid_method(interfaces.InspectionAttrInfo, Generic[_T]):
 
     def __init__(
         self,
-        func: Callable[..., _T],
-        expr: Optional[Callable[..., SQLCoreOperations[_T]]] = None,
+        func: Callable[P, R],
+        expr: Optional[Callable[P, SQLCoreOperations[R]]] = None,
     ):
         """Create a new :class:`.hybrid_method`.
 
@@ -815,31 +821,34 @@ class hybrid_method(interfaces.InspectionAttrInfo, Generic[_T]):
 
         """
         self.func = func
-        self.expression(expr or func)
+        if expr is not None:
+            self.expression(expr)
+        else:
+            self.expression(func)  # type: ignore
 
     @overload
     def __get__(
         self, instance: Literal[None], owner: Type[object]
-    ) -> Callable[[Any], SQLCoreOperations[_T]]:
+    ) -> Callable[P, SQLCoreOperations[R]]:
         ...
 
     @overload
     def __get__(
         self, instance: object, owner: Type[object]
-    ) -> Callable[[Any], _T]:
+    ) -> Callable[P, R]:
         ...
 
     def __get__(
         self, instance: Optional[object], owner: Type[object]
-    ) -> Union[Callable[[Any], _T], Callable[[Any], SQLCoreOperations[_T]]]:
+    ) -> Union[Callable[P, R], Callable[P, SQLCoreOperations[R]]]:
         if instance is None:
             return self.expr.__get__(owner, owner)  # type: ignore
         else:
             return self.func.__get__(instance, owner)  # type: ignore
 
     def expression(
-        self, expr: Callable[..., SQLCoreOperations[_T]]
-    ) -> hybrid_method[_T]:
+        self, expr: Callable[P, SQLCoreOperations[R]]
+    ) -> hybrid_method[P, R]:
         """Provide a modifying decorator that defines a
         SQL-expression producing method."""
 

```

**Comment by zzzeek** [comment]
We can try to make it at least accept multiple arguments that can be of any length though

**Comment by zzzeek** [comment]
OK the descriptor protocol seems to be working around the classmethod/instnacemethod problem and Concatenate seems to work in mypy now, so this might be doable

**Comment by AlexanderPodorov** [comment]
@zzzeek : thank you for investigation!
PEP612 should work in mypy, AFAIK.
1.4 stubs worked with mypy in the past, but started from some recent mypy version (I can’t remember exactly which one), mypy started to report warnings on it.
If we can’t cover all possible use cases here, I think it might be valuable to fix issue with “where” method.

**Comment by AlexanderPodorov** [comment]
Also ParamSpec has to be used everywhere where we apply decorators, in order to keep args typed.

**Comment by zzzeek** [comment]
ParamSpec was not working at all in mypy about a year ago last we tried to deal with it and it caused errors, especially Concatenate.  now it seems to be working fully.    so i think this works

**Comment by AlexanderPodorov** [comment]
Yes, mypy adds new typing features pretty slowly. E.g. typing.Self and dataclass transforms are still not supported.
So I would not rely on mypy fully in that regards. This was the reason why I switched from Pycharm + mypy to VSCode + pyright.
Thank you!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**apply pep-612 to hybrid_method; accept SQLCoreOperations** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4363

**Comment by zzzeek** [comment]
we target mypy as a baseline that has to "pass" with allowance for pyright-only features like dataclass transforms as long as they dont break mypy, since most users have mypy runs in their CI.

mypy has just landed support for pep-673 but not released yet, we will be implementing that throughout the library once that's released.

**Comment by AlexanderPodorov** [comment]
That all makes perfect sense 👍 
Thanks again for the quick response and your hard work on SQLAlchemy! I will keep testing it on my projects to help to make it better.

**Comment by zzzeek** [comment]
feel free to test latest main, the fix worked for my tests but perhaps you have more

**Comment by AlexanderPodorov** [comment]
Just tested it, works perfectly, thanks a lot!
