### ISSUE TITLE
Allow passing Python `bool` to `or`, `and` operators

### ISSUE THREAD

**Issue by emontnemery** [sqlalchemy/sqlalchemy#9123]
### Describe the bug

The typing of `or_` does not allow passing a Python `bool` as an argument.

This contradicts the documentation which states:
> The [or_()](https://docs.sqlalchemy.org/en/20/core/sqlelement.html#sqlalchemy.sql.expression.or_) construct must be given at least one positional argument in order to be valid; a [or_()](https://docs.sqlalchemy.org/en/20/core/sqlelement.html#sqlalchemy.sql.expression.or_) construct with no arguments is ambiguous. To produce an “empty” or dynamically generated [or_()](https://docs.sqlalchemy.org/en/20/core/sqlelement.html#sqlalchemy.sql.expression.or_) expression, from a given list of expressions, a “default” element of False should be specified:

```py
or_criteria = or_(False, *expressions)
```

### To Reproduce

```python
def _make_or_stmt() -> ClauseList:
    return or_(False)
```

### Error

mypy error:

> error: Argument 1 to "or_" has incompatible type "bool"; expected "Union[ColumnElement[bool], _HasClauseElement, SQLCoreOperations[bool], ExpressionElementRole[bool], Callable[[], ColumnElement[bool]], LambdaElement]"  [arg-type]

### Versions

- Python: 3.9
- SQLAlchemy: 2.0.0rc3

**Comment by zzzeek** [comment]
im not sure if i like that guidance, that looks like something really old in any case.   We have an actual `false()` construct that is SQL false.   let me play with it.

also note we have and_() with the same thing (True) so that would be part of this.

**Comment by zzzeek** [comment]
plus these dont allow zero arguments

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**typing updates** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4372
