### ISSUE TITLE
Type checkers do not allow looping over 1.x style Query

### ISSUE THREAD

**Issue by emontnemery** [sqlalchemy/sqlalchemy#9125]
### Describe the bug

Type checkers do not allow looping over 1.x style query

### To Reproduce

```python
class Base(DeclarativeBase):
    ...

class Events(Base):
    idx = Column(Integer)

def loop_query(session: Session) -> None:
    for row in session.query(Events):
        ...
```

### Error

```
mypy --strict test.py
error: "Iterable[Events]" has no attribute "__next__"  [attr-defined]

pyright test.py
error: "Query[Events]" is not iterable
``` 

### Versions

- Python: 3.9
- SQLAlchemy: 2.0.0rc3

**Comment by CaselIT** [comment]
hi

Thanks for reporting.

@zzzeek I think we could create a typing tool issue template, since I'm guessing more of these will be coming once v2 is live

**Comment by emontnemery** [comment]
I updated the title since this seems to work fine with 2.0 style:

```py
def loop_query(session: Session) -> None:
    for row in session.execute(select(Events)):
        ...
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**typing updates** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4372
