### ISSUE TITLE
MSSQL - Incorrect DDL generated for single token schemas

### ISSUE THREAD

**Issue by sl224** [sqlalchemy/sqlalchemy#9133]
### Describe the bug

Incorrect DDL is generated when checking if a table exists for single token schemas. 
The execution context believes the table doesn't exist when it does and errors when trying to create a table

Edit: See PR below for a candidate solution. 

### To Reproduce

```python
from sqlalchemy import create_engine, Table, Column, MetaData, Integer
eng = create_engine("mssql+pymssql://scott:tiger^5HHH@127.0.0.1:1433/test", echo=True)
t = Table(
    "test",
    MetaData(),
    Column("id", Integer, primary_key=True),
    schema='[test_schema]'
)
t.create(eng) # can create table
t.create(eng, checkfirst=True) # Fails to detect existing table
```

### Error

```
2023-01-20 20:07:12,984 INFO sqlalchemy.engine.Engine [no key 0.00007s] {}
2023-01-20 20:07:13,002 INFO sqlalchemy.engine.Engine COMMIT
2023-01-20 20:07:13,010 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-01-20 20:07:13,010 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME], [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(%(table_name_1)s AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(%(table_schema_1)s AS NVARCHAR(max))
2023-01-20 20:07:13,010 INFO sqlalchemy.engine.Engine [cached since 0.03453s ago] {'table_name_1': 'test', 'table_schema_1': '[test_schema]'}
2023-01-20 20:07:13,013 INFO sqlalchemy.engine.Engine 
CREATE TABLE test_schema.test (
	id INTEGER NOT NULL IDENTITY, 
	PRIMARY KEY (id)
)


2023-01-20 20:07:13,013 INFO sqlalchemy.engine.Engine [no key 0.00007s] {}
2023-01-20 20:07:13,021 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 459, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1087, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1118, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1789, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (2714, b"There is already an object named 'test' in the database.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

``` 

We can see the incorrect DDL with the echo flag on 

```
SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME], [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(%(table_name_1)s AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(%(table_schema_1)s AS NVARCHAR(max))
2023-01-20 20:07:13,010 INFO sqlalchemy.engine.Engine [cached since 0.03453s ago] {'table_name_1': 'test', 'table_schema_1': '[test_schema]'}
```

I believe the schema value should be `test_schema` not `[test_schema]` 

Notice the first two combinations in the test below will pass and the final will fail. 
```
    @testing.combinations(
        ("test_schema"),
        ("[test_schema.test_sub_schema]"),
        ("[test_schema]"),
        argnames="test_schema",
    )
    def test_schema_configurations(self, metadata, connection, test_schema):
        _ = Table(
            "test",
            metadata,
            Column("id", Integer, primary_key=True),
            schema=test_schema
        )
        metadata.create_all(connection, checkfirst=True)
        metadata.create_all(connection, checkfirst=True)
```

**Comment by CaselIT** [comment]
Hi,

thanks for reporting. I guess no-one ever used the bracket form with a single token schemas.
I don't think there are other constraints here that prevent the fix, cc @gordthompson @zzzeek

**Comment by gordthompson** [comment]
There is a bug, but it's not in `.has_table()`:

```python
with eng.begin() as conn:
    conn.exec_driver_sql("DROP TABLE IF EXISTS [[test_schema]]].test")
    conn.exec_driver_sql("DROP SCHEMA IF EXISTS [[test_schema]]]")
    conn.exec_driver_sql("CREATE SCHEMA [[test_schema]]]")
    conn.exec_driver_sql("CREATE TABLE [[test_schema]]].test (id int)")

insp = inspect(eng)
print(insp.has_table("test", schema="[test_schema]"))  # True
```

The bug is that for `schema='[test_schema]'`, `t.create(eng)` is emitting

```sql
CREATE TABLE test_schema.test (
	id INTEGER NOT NULL IDENTITY, 
	PRIMARY KEY (id)
)
```

when it should be emitting

```sql
CREATE TABLE [[test_schema]]].test (
	id INTEGER NOT NULL IDENTITY, 
	PRIMARY KEY (id)
)

**Comment by zzzeek** [comment]
> The bug is that for `schema='[test_schema]'`, `t.create(eng)` is emitting
> 
> ```sql
> CREATE TABLE test_schema.test (
> 	id INTEGER NOT NULL IDENTITY, 
> 	PRIMARY KEY (id)
> )
> ```
> 
> when it should be emitting
> 
> ```sql
> CREATE TABLE [[test_schema]]].test (
> 	id INTEGER NOT NULL IDENTITY, 
> 	PRIMARY KEY (id)
> )
> ```

we have a [documented notation](https://docs.sqlalchemy.org/en/14/dialects/mssql.html#multipart-schema-names) that brackets can be used to indicate the individual elements of a multipart schema name, and I dont believe we have any way of using a schema name that has actual brackets in it, which would be very awkward since the bracket is SQL Server's "quoting" character, so the correct schema emitted here should be "test_schema" without brackets.

**Comment by gordthompson** [comment]
Ah, okay. So

```python
insp.has_table("test", schema="[test_schema]")
```

really should be looking in the schema named "test_schema", not "[test_schema]".

And users who have a schema named "[test_schema]" are out of luck (but their lives are probably miserable, anyway).

**Comment by sqla-tester** [comment]
**Shan** has proposed a fix for this issue in the **main** branch:

**Run bracket interpretation for reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4374

**Comment by sqla-tester** [comment]
**Shan** has proposed a fix for this issue in the **rel_1_4** branch:

**Run bracket interpretation for reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4376

**Comment by zzzeek** [comment]
> Ah, okay. So
> 
> ```python
> insp.has_table("test", schema="[test_schema]")
> ```
> 
> really should be looking in the schema named "test_schema", not "[test_schema]".
> 
> And users who have a schema named "[test_schema]" are out of luck (but their lives are probably miserable, anyway).

finally found a post that indicates this is a non-use case  https://www.tektutorialshub.com/sql-server/identifiers-in-sql-server/#delimited-identifiers

> The Delimited Identifier’s must follow these rules.
>   ...
>    The Delimited Characters i.e [] & "" are not allowed.

**Comment by gordthompson** [comment]
> > The Delimited Characters i.e [] & "" are not allowed.

That is not strictly true. See [this example](https://learn.microsoft.com/en-us/sql/t-sql/functions/quotename-transact-sql?view=sql-server-ver16#examples) from the MSSQL docs.

However, I do agree that we have sufficient reason to not support such unfortunate names like `[test_schema]`.

**Comment by zzzeek** [comment]
ugh yuck!   the thing is we are "safe" here for this change because using `"[schemaname]"` was already being handled as `"schemaname"` for all the DDL / SQL rendering, just not reflection.

**Comment by zzzeek** [comment]
thanks @sl224 for your contribution!
