### ISSUE TITLE
Result.__enter__ annotation

### ISSUE THREAD

**Issue by embecka** [sqlalchemy/sqlalchemy#9136]
### Describe the bug

When using `Result` subclasses (like for example `CursorResult`) as context managers, the return type is always `Result` (instead of that subclass)

### To Reproduce

```python
from sqlalchemy import create_engine, sql

engine = create_engine('sqlite://')

with engine.connect() as connection:
    with connection.execute(sql.select(1)) as result:  # <- wrong type hint
        if result.returns_rows:
            print(result.all())
```

### Error

No stack trace, just wrong type hint:

Unresolved attribute reference 'returns_rows' for class 'Result' 

### Versions

- OS: Ubuntu 22.10
- Python: python 3.10
- SQLAlchemy: sqlalchemy-2.0.0b3
- Database: sqlite 3.40.0
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): sqlite

**Comment by sqla-tester** [comment]
**Martin Baláž** has proposed a fix for this issue in the **main** branch:

**Result.__enter__ annotation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4375
