### ISSUE TITLE
connection.dialect.has_schema doesn't work with async engine

### ISSUE THREAD

**Issue by NL9** [sqlalchemy/sqlalchemy#9141]
### Describe the bug

connection.dialect methods don't work with async connection.

### To Reproduce

```python
import asyncio
import platform

import sqlalchemy.ext.asyncio

engine = sqlalchemy.ext.asyncio.create_async_engine(
    "postgresql+psycopg://user:password@localhost:5434/database", future=True
)


async def main():
    async with engine.begin() as connection:
        has_schema = await connection.dialect.has_schema(connection, "public")
        print(has_schema)


if __name__ == "__main__":
    if platform.system() == "Windows":
        asyncio.set_event_loop_policy(
            asyncio.windows_events.WindowsSelectorEventLoopPolicy()
        )
    asyncio.run(main())
```

### Error

C:\Users\Username\AppData\Local\pypoetry\Cache\virtualenvs\name-alf24XV6-py3.11\Lib\site-packages\sqlalchemy\dialects\postgresql\base.py:3124: RuntimeWarning: coroutine 'AsyncConnection.scalar' was never awaited
  return bool(connection.scalar(query))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "...\tt2.py", line 22, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\Username\AppData\Local\pypoetry\Cache\virtualenvs\name-alf24XV6-py3.11\Lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 968, in begin
    yield conn
  File "...\tt2.py", line 13, in main
    has_schema = await connection.dialect.has_schema(connection, "public")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object bool can't be used in 'await' expression

### Versions

- OS: Windows 10
- Python: 3.11.1
- SQLAlchemy: [2.0.0rc3](https://www.sqlalchemy.org/download.html)
- Database: PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit (via Docker)
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): psycopg[binary] 3.1.8

**Comment by CaselIT** [comment]
Hi,

As documented, that method is internal for dialect use only. The public interface is the Inspector https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#using-the-inspector-to-inspect-schema-objects
