### ISSUE TITLE
2.0: sqlalchemy.engine.Result class, some methods return Sequence instead of List

### ISSUE THREAD

**Issue by AlexanderPodorov** [sqlalchemy/sqlalchemy#9144]
### Describe the typing issue

In the `sqlalchemy.engine.Result` class there's several methods that return Sequence instead of inferred List type, for example:
1. `def fetchall(self) -> Sequence[Row[_TP]]`, inferred return type: `List[Row[_TP]]`
2. `def fetchmany(self, size: Optional[int] = None) -> Sequence[Row[_TP]]`, inferred return type: `List[Row[_TP]]`
3. `def all(self) -> Sequence[Row[_TP]]`, inferred return type: `List[Row[_TP]]`

I've noticed similar thing in `ScalarResult` class as well. I don't want to say it's really a typing bug, but just want to make sure it was done on purpose.

### To Reproduce

```python
-
```

### Error

-

### Versions

- OS: MacOS
- Python: 3.11.1
- SQLAlchemy: 2.0.0rc3
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): pylance v2023.1.30

**Comment by zzzeek** [comment]
yes, see #9138
