### ISSUE TITLE
Type checkers do not allow using `isnot` in an `AND` clause

### ISSUE THREAD

**Issue by emontnemery** [sqlalchemy/sqlalchemy#9148]
### Describe the typing issue

Type checkers do not allow using `isnot` in an `AND` clause

### To Reproduce

```python
from sqlalchemy import Integer
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql.elements import ColumnElement
from sqlalchemy.sql.expression import and_

class Base(DeclarativeBase):
    ...

class MyTable(Base):
    state_id: Mapped[int | None] = mapped_column(Integer)

def test() -> ColumnElement[bool]:
    return and_(MyTable.state_id.isnot(None))
```

### Error

Mypy:
```
"ColumnOperators"; expected "Union[Literal[True], Union[ColumnElement[bool], _HasClauseElement, SQLCoreOperations[bool], ExpressionElementRole[bool], Callable[[], ColumnElement[bool]], LambdaElement]]"  [arg-type])
``` 

Pyright:
```
error: Argument of type "ColumnOperators" cannot be assigned to parameter "clauses" of type "_ColumnExpressionArgument[bool]" in function "and_"
    Type "ColumnOperators" cannot be assigned to type "_ColumnExpressionArgument[bool]"
      "ColumnOperators" is incompatible with "ColumnElement[bool]"
      "ColumnOperators" is incompatible with protocol "_HasClauseElement"
        "__clause_element__" is not present
      "ColumnOperators" is incompatible with "SQLCoreOperations[bool]"
      "ColumnOperators" is incompatible with "ExpressionElementRole[bool]"
      Type "ColumnOperators" cannot be assigned to type "() -> ColumnElement[bool]"
      "ColumnOperators" is incompatible with "LambdaElement" (reportGeneralTypeIssues)
```

### Versions

- OS:
- Python:
- SQLAlchemy: 2.0.0rc3
- Type checkers:
  - mypy 0.991
  - pyright 1.1.290

**Comment by CaselIT** [comment]
Hi,

have you tried using `is_not`?
isnot is "soft" deprecated since 1.4

**Comment by emontnemery** [comment]
That does indeed work with both mypy and pyright 👍 
Thanks a lot @CaselIT !

**Comment by CaselIT** [comment]
I'm not sure if this behaviour is intended or not. Let's hear mike opition @zzzeek

**Comment by zzzeek** [comment]
if `isnot` is there it should be typed also.  I guess it's there like an assignment right now and needs to be a full method ?  Not at my computer to look right now

**Comment by zzzeek** [comment]
yeah none of it is typed, doing it now

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add typing to legacy operators** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4392

**Comment by CaselIT** [comment]
> if `isnot` is there it should be typed also. I guess it's there like an assignment right now and needs to be a full method ? Not at my computer to look right now

The types are in a TYPE_CHECKING block so we can do whatever there
