### ISSUE TITLE
Mypy does not allow a relationship where the `remote_side` is `Mapped`

### ISSUE THREAD

**Issue by emontnemery** [sqlalchemy/sqlalchemy#9150]
### Describe the typing issue

Mypy does not allow a relationship where the `remote_side` column is annotated with `Mapped`

The [example in the documentation](https://docs.sqlalchemy.org/en/20/orm/join_conditions.html#creating-custom-foreign-conditions) is not fully updated for 2.0; the columns are not `Mapped` and the imports are slightly wrong (`mapped_column` is forgotten, and `Column` is not removed).

### To Reproduce

```python
from __future__ import annotations

from sqlalchemy import Integer
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

class Base(DeclarativeBase):
    ...

class MyTable(Base):
    __tablename__ = "MyTable"

    idx: Mapped[int] = mapped_column(Integer, primary_key=True)
    table1: Mapped[MyTable | None] = relationship("MyTable", remote_side=idx)
```

If the `table1` column is simplified to it's not annotated with `Mapped`, mypy does not complain:
```diff
-    table1: Mapped[MyTable | None] = relationship("MyTable", remote_side=idx)
+    table1 = relationship("MyTable", remote_side=idx)
```

### Error

```
error: Argument "remote_side" to "relationship" has incompatible type "Mapped[int]"; expected "Union[str, Sequence[Union[ColumnClause[Any], _HasClauseElement, DMLColumnRole]], Callable[[], Sequence[Union[ColumnClause[Any], _HasClauseElement, DMLColumnRole]]], Callable[[], Union[ColumnClause[Any], _HasClauseElement, DMLColumnRole]], _HasClauseElement, DMLColumnRole, None]"
``` 

### Versions

- OS:
- Python:
- SQLAlchemy: 2.0.0rc3
- Type checker: mypy 0.991

**Comment by zzzeek** [comment]
nice catch

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add Mapped to _ORMColCollectionElement** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4393
