### ISSUE TITLE
`ColumnElement.cast` doesn't accept `Type[TypeEngine[T]]`

### ISSUE THREAD

**Issue by uriyyo** [sqlalchemy/sqlalchemy#9156]
### Describe the typing issue

`ColumnElement.cast` accepts only `TypeEngine[T]` as an argument, but also should accept `Type[TypeEngine[T]]` as `sqlachemy.cast` function does.

### To Reproduce

```python
from sqlalchemy import func, Date

func.now().cast(Date)
```

### Error

```py
temp.py:3: error: Argument 1 to "cast" of "ColumnElement" has incompatible type "Type[Date]"; expected "TypeEngine[Any]"  [arg-type]
``` 

### Versions

- OS: MacOS
- Python: python 3.11
- SQLAlchemy: 2.0
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 0.991

**Comment by CaselIT** [comment]
Hi,

Thanks for the report and the PR

**Comment by sqla-tester** [comment]
**Yurii Karabas** has proposed a fix for this issue in the **main** branch:

**Set correct type annotations for ColumnElement.cast** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4396
