### ISSUE TITLE
Consistently use typing collections in the docs

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9168]
The current docs are a mix of typing collection and plain ones (`List[Thing]` vs `list[Thing]`). The second is only supported by python 3.9+.
Since v2 supports 3.7+ to offer more consistent we should use everywhere the typing collection ones.

Discussed in https://github.com/sqlalchemy/sqlalchemy/issues/7659#issuecomment-1407432444

**Comment by sqla-tester** [comment]
**Harry Lees** has proposed a fix for this issue in the **main** branch:

**Unify doc typing** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4409
