### ISSUE TITLE
Typing: Support MappedColumn in UniqueConstraint

### ISSUE THREAD

**Issue by wookie184** [sqlalchemy/sqlalchemy#9170]
### Describe the typing issue

MyPy gives an error when passing a `Mapped` column to `UniqueConstraint`, even though it seems to work correctly at runtime.

A workaround is to pass strings instead, e.g. `UniqueConstraint("thing_one", "thing_two")`, although using the columns directly seems nicer.

I'd guess this might also apply to other constraints, and possibly other things too, although haven't looked into it.

### To Reproduce

```python
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import UniqueConstraint


class MyTable(DeclarativeBase):
    thing_one: Mapped[int] = mapped_column()
    thing_two: Mapped[int] = mapped_column()

    unique_constraint = UniqueConstraint(thing_one, thing_two)
```

### Error

```
test.py:9: error: Argument 1 to "UniqueConstraint" has incompatible type "Mapped[int]"; expected "Union[str, Column[Any], DDLConstraintColumnRole]"  [arg-type]
test.py:9: error: Argument 2 to "UniqueConstraint" has incompatible type "Mapped[int]"; expected "Union[str, Column[Any], DDLConstraintColumnRole]"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
``` 

### Versions

- OS: N/A
- Python: 3.11
- SQLAlchemy: 2.0.0
- Type checker: mypy 0.991

(by the way, congratulations on the 2.0 release! The typing support is fantastic!)

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Place DDLConstraintColumn Role in Mapped** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4401
