### ISSUE TITLE
apply @dataclass to non-mapped classes that inherit from MappedAsDataclass ?   or some kind of messaging /documentation maybe

### ISSUE THREAD

**Issue by ImogenBits** [sqlalchemy/sqlalchemy#9179]
### Describe the typing issue

I'm using a base class for all my tables that inherits both MappedAsDataclass and Declarative base. When I now define an init only field, the child class doesn't have that argument in it's init method and it won't get passed to post_init either.   
The code below passes pylance, but crashes when executed because of the additional argument. I'm not sure if this actually is a typing or a runtime bug. The default dataclasses don't inherit init only fields, so it would make sense if sqlalchemy also wouldn't. But at least for my use case it'd be very useful and the expected behaviour if they did.

### To Reproduce

```python
from dataclasses import InitVar
from sqlalchemy.orm import Mapped, mapped_column, DeclarativeBase, MappedAsDataclass


class Parent(MappedAsDataclass, DeclarativeBase):
    a: InitVar[int]


class Child(Parent):
    __tablename__ = "child"
    b: Mapped[int] = mapped_column(primary_key=True)


Child(1, 2)
```

### Error

```
__init__() takes 2 positional arguments but 3 were given
``` 

### Versions

- OS: Windows 10
- Python: 3.11
- SQLAlchemy: 2.0.0
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): pyright e96b3ece

**Comment by zzzeek** [comment]
well it's runtime because you run the program to see it happen

**Comment by zzzeek** [comment]
this is actually a curious use case that I hadn't considered, which is that the base class here isn't actually a dataclass since it's your base.     This implies things like mixins would work too which I also never considered, like this:

```py
class Parent(MappedAsDataclass, DeclarativeBase):
    pass


class Sub(Parent):
    __abstract__ = True
    a: InitVar[int] = field()

class Child(Sub):
    __tablename__ = "child"

    b: Mapped[int] = mapped_column(primary_key=True)

```

so none of this is set up right now, I'd have to look and see how hard it is to make patterns like these work.

**Comment by zzzeek** [comment]
like this doesn't work either:

```py
from dataclasses import InitVar, dataclass


class Parent:
    a: InitVar[int]


@dataclass
class Child(Parent):
    __tablename__ = "child"

    b: int


Child(1, 2)
```

because `Parent` isn't a dataclass.  that's essentially what's happening here

**Comment by zzzeek** [comment]
annnnd....it looks like your program works if we just do this:

```py
from dataclasses import InitVar, dataclass
from sqlalchemy.orm import Mapped, mapped_column, DeclarativeBase, MappedAsDataclass


@dataclass
class Parent(MappedAsDataclass, DeclarativeBase):
    a: InitVar[int]


class Child(Parent):
    __tablename__ = "child"
    b: Mapped[int] = mapped_column(primary_key=True)


Child(1, 2)
```

so....try that as a workaround and see if there are any issues?  We would essentially look into making all classes into dataclasses, not just the mapped ones.

**Comment by ImogenBits** [comment]
ah ok, I didn't realise that the base class wouldn't receive dataclass semantics at all. That also explains why typing thinks the init only fields are there since PEP 681 just assumes all children of MappedAsDataClass get dataclass semantics.  
That workaround seems to be working fine for my use case. Thanks for the help!

**Comment by zzzeek** [comment]
OK but here is the thing - I'm going to most likely change this behavior for 2.0.1,  having all classes which extend MappedAsDataclass be dataclasses, since that's what they should be per typing.   Which will fix your original problem, however, it means your workaround will throw an error due to applying dataclass a second time :(  so...if you could not go into production with this workaround for now, or otherwise block for the next version until you can get it out.

**Comment by ImogenBits** [comment]
yeah for sure, this project is still in prototyping anyways (and tbh I'm not even sure if I actually am gonna end up doing things this way at all). feel free to change the behaviour, I'll just adopt my code to be whatever it needs to work with sqlalchemy

**Comment by zzzeek** [comment]
great news - dataclasses doesn't raise :)

this is fine

```py
@dataclass
@dataclass
@dataclass
class Parent:
    a: InitVar[int]

```

so we're good

**Comment by zzzeek** [comment]
fun fact (will workaround) - you can be a dataclass but not a dataclass at the same time

```py
import dataclasses


@dataclasses.dataclass
class Parent:
    a: int

class Mixin(Parent):
    b: int

# it's a dataclass...(?)
assert dataclasses.is_dataclass(Mixin)


@dataclasses.dataclass
class Child(Mixin):

    c: int

# but b is not an argument!   need @dataclass on Mixin as well.
# so...what is is_dataclass?   apparently we'd want to use _is_dataclass_instance
c = Child(1, 2, 3)


```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**MappedAsDataclass applies @dataclasses.dataclass unconditionally** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4407
