### ISSUE TITLE
mypy and pylint take forever when SQLAlchemy v2 is imported

### ISSUE THREAD

**Issue by chrisoro** [sqlalchemy/sqlalchemy#9181]
### Describe the typing issue

I updated to sqlalchemy 2.0 today and found out that my linters take forever. Pylint and mypy need up to 20x the time compared to 1.4.

Can be reproduced with this simple file containing basically nothing. 
- create venv and install pylint, mypy, sqlalchemy
- run pylint and mypy (with default config) on the attached code
- pylint will take ~20s and mypy 50s.

### To Reproduce

```python
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

engine = create_engine("")
session = sessionmaker(engine)
```

### Error

```
No error but very very slow
``` 

### Versions

- OS: Win+Linux
- Python: 3.11
- SQLAlchemy: 2.0
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy==0.991, pylint==2.15.10

**Comment by zzzeek** [comment]
that's nothing within our control, make sure you are not using the mypy plugin at all.   mypy caches its typing information so after the first run there should be no issue; otherwise please report a bug to mypy and/or pylint.

**Comment by chaen** [comment]
Unfortunately, caching is of limited help when it comes to CI. I've opened an issue with pylint, let's hope a solution is found quickly.

**Comment by CaselIT** [comment]
In most CI you can indicate some folder to save as cache between jobs, for things like downloaded package cache etc.
Maybe it could be of help to add the mypy cache folders?
