### ISSUE TITLE
Select.limit and .offset allow None as parameters

### ISSUE THREAD

**Issue by nidico** [sqlalchemy/sqlalchemy#9183]
### Describe the typing issue

According to the [`GenerativeSelect.limit`](https://docs.sqlalchemy.org/en/20/core/selectable.html#sqlalchemy.sql.expression.GenerativeSelect.limit.params.limit) and [`GenerativeSelect.offset`](https://docs.sqlalchemy.org/en/20/core/selectable.html#sqlalchemy.sql.expression.GenerativeSelect.offset.params.offset) docs, `None` can be passed to reset limit / option.

However the type checker doesn't allow those parameters to be `None`.

### To Reproduce

```python
from sqlalchemy import Select, select
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


class Table(Base):
    __tablename__ = "table"


def query_limit() -> Select[tuple[Table]]:
    return select(
        Table,
    ).limit(None)


def query_offset() -> Select[tuple[Table]]:
    return select(
        Table,
    ).offset(None)
```

### Error

```
testcase.py:16: error: Argument 1 to "limit" of "GenerativeSelect" has incompatible type "None"; expected "Union[int, _HasClauseElement, SQLCoreOperations[int], ExpressionElementRole[int], Callable[[], ColumnElement[int]], LambdaElement]"  [arg-type]
testcase.py:22: error: Argument 1 to "offset" of "GenerativeSelect" has incompatible type "None"; expected "Union[int, _HasClauseElement, SQLCoreOperations[int], ExpressionElementRole[int], Callable[[], ColumnElement[int]], LambdaElement]"  [arg-type]
``` 

### Versions

- OS: Linux Mint 21.1 Vera
- Python: 3.11
- SQLAlchemy: 2.0.0
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 0.991

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fixed typing of limit, offset and fetch to allow ``None``.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4410
