### ISSUE TITLE
fix count() migration docs to indicate a non-None type

### ISSUE THREAD

**Issue by nidico** [sqlalchemy/sqlalchemy#9184]
### Describe the typing issue

In order to get the row count in SQLAlchemy 2 style, I'm running the following code and expect an `int` as a result, but get an `Optional[int]` instead.

### To Reproduce

```python
from sqlalchemy import create_engine, func, select, Select
from sqlalchemy.orm import DeclarativeBase, Session

engine = create_engine("sqlite:///:memory:")
session = Session(engine)


class Base(DeclarativeBase):
    pass


class Table(Base):
    __tablename__ = "table"


def good() -> Select[tuple[int]]:
    return select(func.count(Table))


def bad() -> int:
    return session.scalar(select(func.count(Table)))
```

### Error

```
testcase.py:21: error: Incompatible return value type (got "Optional[int]", expected "int")  [return-value]
``` 

### Versions

- OS: Linux Mint 21.1 Vera
- Python: 3.11
- SQLAlchemy: 2.0.0
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 0.991

**Comment by CaselIT** [comment]
Hi,

This is expected, since no row could be returned by a `Select[tuple[int]]` object.
Now this example is not the case, but there is currently no way of indicating that a select returns at least a row in all cases.

You can either use `scalars().one()` or `execute().scalar_one()` or use assert on the return value or type ignore.

**Comment by CaselIT** [comment]
@zzzeek do you think something better could be done here?

**Comment by nidico** [comment]
> This is expected, since no row could be returned by a `Select[tuple[int]]` object.
> Now this example is not the case, but there is currently no way of indicating that a select returns at least a row in all cases.

Understand. I kind of expected this, but wasn't sure about it when digging through the source code.

> You can either use `scalars().one()` or `execute().scalar_one()` or use assert on the return value or type ignore.

I'd then suggest to use one of those options in the [2.0 Migration - ORM Usage comparison table](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-orm-usage) (and maybe in other similar places in the docs if there are any).

**Comment by zzzeek** [comment]
> I'd then suggest to use one of those options in the [2.0 Migration - ORM Usage comparison table](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-orm-usage) (and maybe in other similar places in the docs if there are any).

for the two count() functions there?  ok
