### ISSUE TITLE
add overloads to Session.execute() to qualify for Update/Delete without returning that we are returning CursorResult in those specific cases

### ISSUE THREAD

**Issue by erdnaxeli** [sqlalchemy/sqlalchemy#9185]
### Describe the typing issue

[The doc](https://docs.sqlalchemy.org/en/20/tutorial/data_update.html#getting-affected-row-count-from-update-delete) says  

> The [CursorResult](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.CursorResult) class is a subclass of [Result](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result) which contains additional attributes that are specific to the DBAPI cursor object. An instance of this subclass is returned when a statement is invoked via the [Connection.execute()](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Connection.execute) method. When using the ORM, the [Session.execute()](https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.execute) method returns an object of this type for all INSERT, UPDATE, and DELETE statements.

But when calling `Session.execute` with an `update` or `delete` request mypy think the returned value is a `Result[Any]`. If I add an annotation to specify `CursorResult` it says

> Incompatible types in assignment (expression has type "Result[Any]", variable
has type "CursorResult[Any]")  [assignment]

### To Reproduce

```python
from typing import Optional
from sqlalchemy import ForeignKey
from sqlalchemy import String
from sqlalchemy import create_engine, update
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import Session
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "user_account"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(30))
    fullname: Mapped[Optional[str]]



engine = create_engine("sqlite://", echo=True)
Base.metadata.create_all(engine)

with Session(engine) as session:
    result = session.execute(update(User).values(name="name"))
    print(result.rowcount)
```

### Error

```
t.py:30: error: "Result[Any]" has no attribute "rowcount"  [attr-defined]
``` 

### Versions

- OS: Fedora 36
- Python: 3.10.9
- SQLAlchemy: 2.0.0
- Type checker: mypy 0.991

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting

**Comment by zzzeek** [comment]
this is on the edge of functionality, `session.execute()` usually does not return a `CursorResult` and the case here for using ORM-enabled update/delete returning `CursorResult` is not well defined, and it will be difficult to type.  If the update() includes returning() for example, then you get `Result` again.   We would have to qualify update().returning() and delete().returning() as a new sub-type ReturningUpdate/ReturningDelete, as we do for Insert, then add more overloads to Session.execute().  might need to be just one extra overload, not sure.

we'd want to be absolutely sure update()/delete() without returning are always returning CursorResult, as I'm not sure how "official" that is.

**Comment by zzzeek** [comment]
beyond that, we can't really type for arbitrary Core-only statements since there's not really a consistent way to tell if an Executable is Core-only from typing.

You should use cast() in this case for now.

**Comment by zzzeek** [comment]
but that opens the door for us to have *every* method on Result that's on CursorResult

**Comment by CaselIT** [comment]
that's indeed the case.

trying to think at something to make usage convenient. Something like
```py
# some alternatives
result.as_cursor_result().rowcount
result.as_cursor_result.rowcount
result.acr.rowcount
```

where `as_cursor_result` is basically a isinstance + raise if not, and we document that's only to improve use with type checkers?

**Comment by zzzeek** [comment]
I think for now we can just add an overload for update() and delete() without returning(), since that's the main place people want to get .rowcount

**Comment by erdnaxeli** [comment]
> maybe an alternative could be to have rowcount also on result, but make it raise not implemented error (or equivalent. exc.InvalidRequest is also valid)?
> 
> this way one would avoid having to cast, but would get an exception when called on a not supported implementation

This breaks the type checking no? I don't want a not implemented error on runtime, I want a type error when running mypy.

**Comment by zzzeek** [comment]
see #10108

**Comment by sqla-tester** [comment]
**Mehdi Gmira** has proposed a fix for this issue in the **main** branch:

**Fix annotations** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4794

**Comment by ahyatt-continua** [comment]
This seems to be an issue again in version 2.0.44 - when we upgraded from 2.0.43 we started getting type warnings about `rowcount`.

**Comment by CaselIT** [comment]
that was intentional https://github.com/sqlalchemy/sqlalchemy/issues/12913

please use cast / isinstance
