### ISSUE TITLE
annotated declarative mis-interprets Literal within Mapped[]

### ISSUE THREAD

**Issue by frederikaalund** [sqlalchemy/sqlalchemy#9187]
### Describe the bug

I get an `sqlalchemy.exc.ArgumentError: Could not resolve all types within mapped annotation: "Mapped[Status]"` error when I use `from __future__ import annotations` together with a `Mapped` column of type `typing.Literal`.

When I remove `from __future__ import annotations`, everything works as expected.

I'm aware that sqlalchemy already includes built-in support for `enum.Enum`. I'm aware that this is another workaround.

### To Reproduce

```python
# NOTE: Code works if we remove the following line
from __future__ import annotations

from typing import Any, Literal, Optional, get_args

import sqlalchemy.types as types
from sqlalchemy import Dialect
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class LiteralSqlType(types.TypeDecorator):
    impl = types.String
    cache_ok = True

    def __init__(self, literal_type: Any) -> None:
        super().__init__()
        self._possible_values = get_args(literal_type)

    def process_bind_param(
        self, value: Optional[str], dialect: Dialect
    ) -> Optional[str]:
        if value not in self._possible_values:
            raise ValueError(
                f"Invalid literal value '{value}'. Value must be one of"
                f" {self._possible_values}."
            )
        return value


Status = Literal["to-do", "in-progress", "done"]


class Base(DeclarativeBase):
    pass


class Foo(Base):
    __tablename__ = "foo"

    id: Mapped[int] = mapped_column(primary_key=True)
    status: Mapped[Status] = mapped_column(None, LiteralSqlType(Status))
```

### Error

```
Traceback (most recent call last):
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 189, in eval_expression
    annotation = eval(expression, base_globals, None)
  File "<string>", line 1, in <module>
NameError: name 'to' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1388, in _extract_mappable_attributes
    value.declarative_scan(
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/orm/properties.py", line 681, in declarative_scan
    self._init_column_for_annotation(
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/orm/properties.py", line 717, in _init_column_for_annotation
    argument = de_stringify_annotation(
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 154, in de_stringify_annotation
    elements = tuple(
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 155, in <genexpr>
    de_stringify_annotation(
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 151, in de_stringify_annotation
    annotation = eval_expression(annotation, originating_module)
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/util/typing.py", line 191, in eval_expression
    raise NameError(
NameError: Could not de-stringify annotation 'to-do'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/sqlalchemy_issue.py", line 37, in <module>
    class Foo(Base):
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_api.py", line 768, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 246, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 327, in setup_mapping
    return _ClassScanMapperConfig(
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 569, in __init__
    self._extract_mappable_attributes()
  File "/sbt-yocto/build-bactobox/workspace/sources/gmdb/python/.venv/lib/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 1400, in _extract_mappable_attributes
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not resolve all types within mapped annotation: "Mapped[Status]".  Ensure all types are written correctly and are imported within the module in use.
```

### Versions

- OS: `Linux 6f5cb13b6c98 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Python: `Python 3.10.9`
- SQLAlchemy: `sqlalchemy 2.0.0` (as released a couple of days ago)
- Database: N/A
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): N/A

### Additional context

# My understanding of the issue

With `from __future__ import annotations`, python automatically converts all annotations to strings (simplified explanation). This makes it easier to use types out of declaration order. In turn, libraries that use annotations must "de-stringify" the annotations first. This last part is where I think the bug is at.

I think that sqlalchemy is too aggressive with it's "de-stringify annotations" logic.
First, sqlalchemy de-stringifies the literal itself: `'Literal["to-do", "in-progress", "done"]'` becomes `Literal["to-do", "in-progress", "done"]`. So far so good!
Second, sqlalchemy notices that `Literal` is generic (has arguments) and therefore attempts to recursively de-stringify each argument ("to-do", "in-progress", and "done"). However, these arguments are *not* annotations but mere strings. This causes the error.

# Patch to fix the issue

Change the `de_stringify_annotation` function in `sqlalchemy/util/typing.py` so that it explicitly accounts for the `typing.Literal` case:
Specifically, change the recursive part from:

```python
    if include_generic and is_generic(annotation):
        elements = tuple(
            de_stringify_annotation(
                cls,
                elem,
                originating_module,
                str_cleanup_fn=str_cleanup_fn,
                include_generic=include_generic,
            )
            for elem in annotation.__args__
        )

        return _copy_generic_annotation_with(annotation, elements)
    return annotation  # type: ignore
```

to:

```python
    is_literal = get_origin(annotation) is Literal
    if include_generic and is_generic(annotation) and not is_literal:
        elements = tuple(
            de_stringify_annotation(
                cls,
                elem,
                originating_module,
                str_cleanup_fn=str_cleanup_fn,
                include_generic=include_generic,
            )
            for elem in annotation.__args__
        )

        return _copy_generic_annotation_with(annotation, elements)
    return annotation  # type: ignore
```

The code works as expected (no errors) with this fix applied.

Let me know if you have any questions.

*Side note*: Version 2.0 of sqlalchemy is amazing. Great job!

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting.
Have you tried using `status: Mapped[Status] = mapped_column(LiteralSqlType(Status))`?

Btw I did not know about `typing.get_args`. @zzzeek I wonder if it could be useful

**Comment by frederikaalund** [comment]
Hi Federico, thanks for the *very* prompt response.

> Have you tried using status: Mapped[Status] = mapped_column(LiteralSqlType(Status))?

I just tried this and the issue persists.
Note that the `None` value was a left-over from my production code that erroneously made it into the simplified reproduction code for this issue.

~Frederik

**Comment by frederikaalund** [comment]
By the way, I'm willing to make a PR if you like the proposed fix (or slight modifications thereof). :+1:

**Comment by CaselIT** [comment]
Let's wait for Mike's input on this 

One thing to consider is that `get_origin` is 3.8+ and sqlalchemy still supports 3.7. But if it's in typing_extension we are good to use it

**Comment by zzzeek** [comment]
> Let's wait for Mike's input on this
> 
> One thing to consider is that `get_origin` is 3.8+ and sqlalchemy still supports 3.7. But if it's in typing_extension we are good to use it

we are using both via typing_extensions already so no change is needed for these specifically, see util/typing.py

**Comment by zzzeek** [comment]
> # Patch to fix the issue

the patch is fine, I would tighten it up by adding a kw argument `include_literal=False` to our `is_generic()` function:

```py
    if include_generic and is_generic(annotation, include_literal=False):
        elements = tuple(
            de_stringify_annotation(
                cls,
                elem,
                originating_module,
                str_cleanup_fn=str_cleanup_fn,
                include_generic=include_generic,
            )
            for elem in annotation.__args__
        )

        return _copy_generic_annotation_with(annotation, elements)
    return annotation  # type: ignore
```

does that work?   Anyone here want to contribute a patch?  the test cases are the more labor intensive part

**Comment by zzzeek** [comment]
we should have tests that also feature a fixed Literal within `type_annotation_map`

**Comment by frederikaalund** [comment]
Thanks for the feedback. I'll incorporate it.

>  Anyone here want to contribute a patch? 

I'm on it. :+1:

**Comment by sqla-tester** [comment]
**Frederik Aalund** has proposed a fix for this issue in the **main** branch:

**Add support for typing.Literal in Mapped** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4406
