### ISSUE TITLE
Pylint does not allow calling func.max, func.min, etc.

### ISSUE THREAD

**Issue by emontnemery** [sqlalchemy/sqlalchemy#9189]
### Describe the typing issue

Pylint does not allow calling `func.max`, `func.min`, `func.count`

This problem did not exist in SQLAlchemy 2.0.0rc3, it first appears in 2.0.0

### To Reproduce

```python
from sqlalchemy import func, select, Integer
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.sql.selectable import Select

class Base(DeclarativeBase):
    pass


class MyTable(Base):
    __tablename__ = "host_entry"

    id = mapped_column(Integer, primary_key=True)


def state_attrs_exist(attr: int | None) -> Select:
    """Check if a state attributes id exists in the states table."""
    return select(func.min(MyTable.id)).where(MyTable.id == attr)
```

### Error

Pylint error:
```
E1102: func.min is not callable (not-callable)
``` 

### Versions

- OS:
- Python: 3.9
- SQLAlchemy: 2.0.0
- Type checker pylint 2.15.10

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting

**Comment by CaselIT** [comment]
The issue here seems of pylink. The returned object from `func.min` is a type, so that's callable, since you are instantiating it.

I think you should report it to pylint

**Comment by zzzeek** [comment]
does pylint honor TYPE_CHECKING blocks?

**Comment by zzzeek** [comment]
also is it the name "min" that's part of builtins throwing off pylint?  what do you get for say func.char_length

**Comment by zzzeek** [comment]
it's almost like I have pylint here too and can just run it

**Comment by zzzeek** [comment]
OK it's not the name, breaks for both.  OK!

```
test3.py:18:18: E1102: func.min is not callable (not-callable)
test3.py:18:18: E1102: func.min is not callable (not-callable)
test3.py:21:0: C0116: Missing function or method docstring (missing-function-docstring)
test3.py:22:18: E1102: func.char_length is not callable (not-callable)
test3.py:22:18: E1102: func.char_length is not callable (not-callable)
```

**Comment by CaselIT** [comment]
I think it's a pylint thing then

**Comment by zzzeek** [comment]
@emontnemery great, thanks *so* much for giving them an isolated test case , that helps a lot otherwise we get ping pong

**Comment by funkatron82** [comment]
Someone commented a possible reason for the issue: https://github.com/pylint-dev/pylint/issues/8138#issuecomment-2210372652

**Comment by sbrunner** [comment]
Looks to work with the module: `sqlalchemy.sql.functions`.

**Comment by sbrunner** [comment]
For the count:
```
import sqlalchemy.sql.functions

session.scalar(
    select(sqlalchemy.sql.functions.count(Queue.id)).where(
        and_(Queue.status == _STATUS_PENDING, Queue.job_id == job.id)
    )
)
```

**Comment by funkatron82** [comment]
Okay calling them directly instead of relying on the dynamic calling I think the module does.  Thank you.  Pylint isn't throwing a fit anymore

**Comment by lucapriorelli** [comment]
_FunctionGenerator functions are declared with the property decorator while thery are called as functions.
PyLint will complain
