### ISSUE TITLE
Aliased and alias constructs within tuples produce unexpected behaviour, exceptions on 1.4.x-2.x style

### ISSUE THREAD

**Issue by FrozzWay** [sqlalchemy/sqlalchemy#9194]
### Describe the bug

Use of **aliased** (and **alias**) construct within **tuples** in 2.x queries (_select_, _delete_, etc) produces unexpected behaviour and in some cases exceptions that are not supposed to appear.
No issue present with Query API 1.x style

- First, examples with **different results** for the same query:

    Returns several elements (No issue: Query API 1.x style):
    ``` lang-python
    B = aliased(tables.BookedClasses)
    res = (
        session.query(B)
        .where(tuple_(B.class_id, B.date).in_(obj_to_remove))
        .all()
    )
    ```
  Returns 0 elements
  ```
  B = aliased(tables.BookedClasses)
  res = session.execute(
      select(B)
      .where(tuple_(B.class_id, B.date).in_(obj_to_remove))
  ).all()
  ```

- Second, if you try to use aliased constructs within _delete()_ statement you are going to get _sqlalchemy.orm.exc.UnmappedColumnError_

   > No column anon_1.class_id is configured on mapper mapped class BookedClasses->booked_classes...

  which is not true
  
   ```
  B = aliased(tables.BookedClasses) 
  self.session.execute(
      delete(tables.BookedClasses)
      .where(tuple_(B.class_id, B.date).in_(obj_to_remove))
  )
  ```
- Third, executing delete() with **alias()** simply removes **all** rows regardless of _where_ clause.
   ```  
        B = alias(tables.BookedClasses.__table__)
        self.session.execute(
            delete(B)
            .where(tuple_(B.c.class_id, B.c.date).in_(obj_to_remove))
        )
   ```  

I'm sorry I can't tell you what exactly is wrong inside of instances, but SQL previews of above statements seem completely fine and yet unexpected behaviour.

### To Reproduce

```python
Foo
```

### Error
```
  File "C:\Education\Python\FastAPI\sport-app\src\sport_app\services\schedules\schema.py", line 137, in _remove_booking
    self.session.execute(
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1662, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1843, in orm_pre_session_exec
    update_options = cls._do_pre_synchronize_evaluate(
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1964, in _do_pre_synchronize_evaluate
    eval_condition = evaluator_compiler.process(*crit)
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\evaluator.py", line 92, in process
    return meth(clause)
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\evaluator.py", line 187, in visit_binary
    eval_left, eval_right = list(
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\evaluator.py", line 92, in process
    return meth(clause)
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\evaluator.py", line 140, in visit_tuple
    return self.visit_clauselist(clause)
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\evaluator.py", line 143, in visit_clauselist
    evaluators = list(map(self.process, clause.clauses))
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\evaluator.py", line 92, in process
    return meth(clause)
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\evaluator.py", line 116, in visit_column
    key = parentmapper._columntoproperty[clause].key
  File "C:\Education\Python\FastAPI\sport-app\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 3738, in __missing__
    raise orm_exc.UnmappedColumnError(
sqlalchemy.orm.exc.UnmappedColumnError: No column anon_1.class_id is configured on mapper mapped class BookedClasses->booked_classes...
```

### Versions

- SQLAlchemy: 1.4.x

**Comment by FrozzWay** [comment]
I'm kinda forced to use Query API 1.x style
```
B = aliased(tables.BookedClasses)
rows = (
    session
    .query(B)
    .where(tuple_(B.class_id, B.date).in_(obj_to_remove))
    .all()
)
for row in rows:
  session.delete(row)
```
or to not use aliases
```
self.session.execute(
    delete(tables.BookedClasses)
    .where(tuple_(tables.BookedClasses.class_id, tables.BookedClasses.date).in_(obj_to_remove))
).all()
```

**Comment by CaselIT** [comment]
Hi,
`Foo` is not really a valid reproducing case.

You have not provided
- the models
- what is obj_to_remove

**Comment by FrozzWay** [comment]
> Hi, `Foo` is not really a valid reproducing case....
I guessed reproducing case form was just for code input and I had comments on each query.
> You have not provided
> * the models
> * what is obj_to_remove

class BookedClasses(Base):
    __tablename__ = "booked_classes"

    id = Column(Integer, primary_key=True)
    client_id = Column(Integer, ForeignKey("client.id", ondelete="CASCADE"))
    class_id = Column(Integer, ForeignKey("class.id", ondelete="CASCADE"))
    date = Column(DateTime(timezone=True))

obj_to_remove is simply list[tuple[int, datetime]] for id and date fields

the context really doesn't matter here

**Comment by zzzeek** [comment]
> the context really doesn't matter here

hey there -

agree the specifics of your case don't matter to what the issue actually is, however we can't reproduce any issue with what we've been given.     take a look at the [great mcve](https://github.com/sqlalchemy/sqlalchemy/issues?q=is%3Aissue+label%3A%22great+mcve%22+) tag for many examples of what well written and most importantly **actionable** bug reports look like.        I will note that a statement like ``delete(MappedClass).where(AliasOfMappedClass.foo == 'bar')`` does not make any sense, so I can't even try to figure out what it is you might be trying to do.   additoinally, a bug report should refer to just **one** test case / behavior at a time, as it is difficult to track three separate issues in one bug report.

if you cant provide an MCVE, please open a [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions) and we will try to work out what it is you might be doing.
