### ISSUE TITLE
apply typing to top-level dialect public types and upsert functions

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9205]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9203

```py
from sqlalchemy import JSON
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import mysql

# fine
JSON()

# both bad

postgresql.JSON()

postgresql.JSONB()


# these are fine
mysql.BIT()

mysql.BIGINT()
```

```
$ mypy test3.py 
test3.py:10: error: Call to untyped function "JSON" in typed context  [no-untyped-call]
test3.py:12: error: Call to untyped function "JSONB" in typed context  [no-untyped-call]
Found 2 errors in 1 file (checked 1 source file)
```

strange? What's special about those two types?

**Comment by zzzeek** [comment]
I can't quite pin down the pattern to this.  seems like a bug in mypy.

**Comment by zzzeek** [comment]
why has this not been reported at all throughout the beta phase?   This seems to be the behavior everywhere, such as `sqlalchemy.ext.compiler`

how was this not noticed?

```py
from typing import Any

from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql.selectable import Select

@compiles(Select)
def foo(elem: Any, compiler: Any, **kw: Any) -> str:
    return "hi"


```

```
$ mypy test3.py 
test3.py:6: error: Call to untyped function "compiles" in typed context  [no-untyped-call]
test3.py:6: error: Untyped decorator makes function "foo" untyped  [misc]
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by CaselIT** [comment]
> we may need to run a job to globally apply "Any" types to all otherwise untyped methods and functions, like in dialects, extensions, etc

I'm -1 on this. I think we can take our time to update these.

mypy can be instructed to not report the `no-untyped-call` using disallow_untyped_defs  on a per-module from the example https://mypy.readthedocs.io/en/stable/config_file.html#example-pyproject-toml

**Comment by zzzeek** [comment]
agree, seeing how hard it will be to type these

**Comment by CaselIT** [comment]
Just for reference, this is part of https://github.com/sqlalchemy/sqlalchemy/issues/6810

**Comment by zzzeek** [comment]
nothing novel happening here.   help wanted.  dupe of #6810

**Comment by CaselIT** [comment]
ok, I'll update that issue to make it clear what still needs work and what's done
