### ISSUE TITLE
Not able to use model in select, update or delete statements

### ISSUE THREAD

**Issue by Voldemat** [sqlalchemy/sqlalchemy#9208]
### Describe the typing issue

 Argument 1 to "Delete" has incompatible type "Type[Tariff]"; expected "Union[str, Selectable]"

### To Reproduce

```python
import sqlalchemy as sa
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.ext.asyncio import AsyncSession


class Base(DeclarativeBase):
	pass

class Tariff(Base):
	__tablename__ = "tariffs"

	id = sa.Column(sa.Integer, primary_key=True)

	hashtags_count = sa.Column(sa.Integer, nullable = False)


async def delete_tariffs(session: AsyncSession) -> None:
	await session.execute(sa.delete(Tariff))
```

### Error

check.py:2: error: Module "sqlalchemy.orm" has no attribute "DeclarativeBase"  [attr-defined]
    from sqlalchemy.orm import DeclarativeBase
    ^
check.py:6: error: Class cannot subclass "DeclarativeBase" (has type "Any")  [misc]
    class Base(DeclarativeBase):
               ^
check.py:18: error: Argument 1 to "Delete" has incompatible type "Type[Tariff]"; expected "Union[str, Selectable]"  [arg-type]
            await session.execute(sa.delete(Tariff))
                                            ^~~~~~
Found 3 errors in 1 file (checked 1 source file)

### Versions

- OS: MacOS 13.1 (22C65)
- Python: 3.10
- SQLAlchemy: 2.0
- Type checker: mypy 0.991

**Comment by zzzeek** [comment]
hi -

your file passes mypy 100% for me.  can you make sure you remove any .pyi stubs for SQLAlchemy including from your tooling's private directories.

**Comment by zzzeek** [comment]
"Module "sqlalchemy.orm" has no attribute "DeclarativeBase" [attr-defined]

that's definitely a SQLAlchemy version and/or stubs issue.   make sure you're on SQLAlchemy 2.0 and have no stubs.
