### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by rhynzler** [sqlalchemy/sqlalchemy#9209]
It is not a typing issue, I just want to report an error in the documentation of Basic Relationship Patterns in the Late-Evaluation of Relationship Arguments section, to be specific, line 1050 of the file: [basic_relationships.rst](https://github.com/sqlalchemy/sqlalchemy/blob/main/doc/build/orm/basic_relationships.rst)

The parentheses of the function should not go, because if we leave the parentheses, the function will be executed when the application is initialized and it may be possible to throw an ImportError exception

### Suggested Change

Just remove the parentheses from the Late-Evaluaton function

```python
import typing

    from sqlalchemy import desc

    if typing.TYPE_CHECKING:
        from myapplication import Child


    def _resolve_child_model():
        from myapplication import Child

        return Child


    class Parent(Base):
        # ...

        children: Mapped[List["Child"]] = relationship(
            # _resolve_child_model() Raise ImportError
            # _resolve_child_model or lambda: _resolve_child_model() Correct
            _resolve_child_model,
            order_by=lambda: desc(_resolve_child_model().email_address),
            primaryjoin=lambda: Parent.id == _resolve_child_model().parent_id,
        )
```

### Versions

- OS: Manjaro Linux
- Python: 3.10
- SQLAlchemy: 2.0
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): pyright with Pylance

**Comment by zzzeek** [comment]
indeed, nice catch

**Comment by zzzeek** [comment]
backported to 1.4 as well
