### ISSUE TITLE
Remove `typing.Self` workaround

### ISSUE THREAD

**Issue by uriyyo** [sqlalchemy/sqlalchemy#9254]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

New `mypy` version `1.0.0` supports [PEP 673](https://peps.python.org/pep-0673/) so we can replace workarounds that `slqalchemy` has.

### To Reproduce

```python
SelfInsert = typing.TypeVar("SelfInsert", bound="Insert")


class Insert(StandardInsert):
    def on_duplicate_key_update(self: SelfInsert, *args, **kw) -> SelfInsert:
```

### Error

```
# No error
``` 

### Versions

- OS: macOS
- Python: python3.11
- SQLAlchemy: 2.0.2
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.0.0

**Comment by CaselIT** [comment]
Hi,

Great, that's something to do

**Comment by uriyyo** [comment]
@CaselIT I have opened PR that removes all workarounds. Please see #9255

**Comment by CaselIT** [comment]
I saw that, many thanks

**Comment by sqla-tester** [comment]
**Yurii Karabas** has proposed a fix for this issue in the **main** branch:

**Remove `typing.Self` workaround** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4432
