### ISSUE TITLE
mike is creating a test bug report.

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9260]
### Describe the bug

We have too many users that spend a lot of effort posting bug reports that we cannot act upon and they get converted to discussions.

### Link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://www.sqlalchemy.org/support.html#discussions

### SQLAlchemy Version in Use

2.0.2

### DBAPI Version

pysqlite

### Database Vendor and Version

sqlite

### Python Version

3.11

### Operating system

linux

### To Reproduce

```python
print("post a bug")
```

### Error

```
raise Exception("mike converted it to discussion")
```

**Comment by CaselIT** [comment]
you can use my form for this mike https://github.com/CaselIT/sqlalchemy

**Comment by zzzeek** [comment]
well I want to try this out for now, having input fields for sqlalhcemy version so they type them in since a lot of people are not, also see if we can get them to read the docs a bit

**Comment by CaselIT** [comment]
makes sense. there are also checkboxes that people have to click if you want to add them (like I added in the typing template)

**Comment by zzzeek** [comment]
I think the "write a link" might annoy people but we will see
