### ISSUE TITLE
Allow customization of the dataclass library used by sqlalchemy, process annotations on mixins

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9266]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9264

it seems that there are 3rd party libraries that extend dataclasses with additional functionality, like [pydantic](https://docs.pydantic.dev/usage/dataclasses/)

The registry could have an argument that allows customization of the dataclasses library

~~@zzzeek do you think we should accept a module or a single `dataclass` classable here?~~

let's pass a single callable, since the pydantic dataclasses module has a different interface than the builtin one

**Comment by zzzeek** [comment]
also, just realized this can't be on registry, it has to be part of MappedAsDataclass and mapped_as_dataclass.   because a mixin doesn't have a registry.

**Comment by CaselIT** [comment]
indeed not. 

the api will look a bit awkward :(

**Comment by zzzeek** [comment]
it'll be great

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add dataclasses callable and apply annotations more strictly** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4439
