### ISSUE TITLE
hybrid_property setter method signature can match _HybridSetterType

### ISSUE THREAD

**Issue by sileht** [sqlalchemy/sqlalchemy#9268]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

mypy complains about hybrid_property setter method signature.

### To Reproduce

```python
Peusdo model:


class Foo(Base):
    def needs_update_getter(self) -> bool:
        ... some code ...

    def needs_update_setter(self, value: bool) -> None:
        ... some code ...

    needs_update: sqlalchemy.ext.hybrid.hybrid_property[
        bool
    ] = sqlalchemy.ext.hybrid.hybrid_property(
        needs_update_getter,
        needs_update_setter, 
    )
```

### Error

```
error: Argument 2 to "hybrid_property" has incompatible type "Callable[[Foo, bool], None]"; expected "Optional[_HybridSetterType[bool]]"  [arg-type])
``` 

### Versions

- OS: macos 13.2
- Python: 3.11.1
- SQLAlchemy: 2.0.2
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): mypy 1.0.0

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting and for the fix!
