### ISSUE TITLE
New method to check if column is autoincremented

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#9277]
### Describe the use case

A method to tell if a column is autoincremented or not.

Preference would be to have something like `Column.is_autoincremented: bool`, but a `Table.get_autoincrement_column() -> Column` (as suggested by @zzzeek) would work fine too.

### Example Use

```
for c in table.c:
    show_in_create_form = not c.is_autoincremented
    # Create input widget from column
```

Or, with an actual implementation:
https://github.com/aio-libs/aiohttp_admin/blob/master/aiohttp_admin/backends/sqlalchemy.py#L43

### Additional context

https://github.com/sqlalchemy/sqlalchemy/discussions/9261

**Comment by CaselIT** [comment]
Hi,

I'm not sure if excluding only incrementing columns would be sufficient for your use case.
Computed columns are also generated by the db, and depending on the db they may not be set in the insert. Postgresql is one such db (requires default to be used for generated always columns)

**Comment by Dreamsorcerer** [comment]
You may be right, would a `is_computed` or similar be possible? Ultimately, I just want something which tells me this column should not have a value passed in for a normal insert.

**Comment by CaselIT** [comment]
there is already `.computed` that you can test for none

**Comment by zzzeek** [comment]
if you want any server default col you need to look at server_default also

**Comment by zzzeek** [comment]
though for now, the only API that's not public is the "which col is autoincrement" , so we can make that public.  I do think it should be for Table though because it's the Table that chooses this, not the column

**Comment by Dreamsorcerer** [comment]
> there is already `.computed` that you can test for none

But, that returns `None` on autoincrement. So, I guess I'll need to check both autoincrement and computed.

> if you want any server default col you need to look at server_default also

Yes, already thought about looking at default/server_default/nullable to decide whether a field is required or not.

**Comment by CaselIT** [comment]
> > there is already `.computed` that you can test for none
> 
> But, that returns `None` on autoincrement. So, I guess I'll need to check both autoincrement and computed.

well yes, an autoincrement or itentity column is not a computed one (as identified by "generated always as")

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add ``Table.autoincrement_column``** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4438
