### ISSUE TITLE
naming convention docs refer to using classes as keys as well as callables for values in some cases; neither are typed

### ISSUE THREAD

**Issue by tiesjan** [sqlalchemy/sqlalchemy#9284]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

The documentation on `MetaData.naming_convention` specifies that the keys of the mapping can be either string or a Constraint/Index type. However, [the type annotations](https://github.com/sqlalchemy/sqlalchemy/blob/b95b22d8c0f9f26e33e1912d8ee205319fc20362/lib/sqlalchemy/sql/schema.py#L5088) only accept `Dict[str, str]`. Therefore, a dictionary with type `Dict[Type[Union[Constraint, Index]], str]` is not accepted.

As for the mapping values: it might probably need to accept a callable too for user token definitions, but I don't have this use case in my code.

### To Reproduce

```python
from typing import Dict, Type, Union

from sqlalchemy import MetaData
from sqlalchemy.sql.schema import (
    CheckConstraint,
    Constraint,
    ForeignKeyConstraint,
    Index,
    PrimaryKeyConstraint,
    UniqueConstraint,
)

naming_convention: Dict[Type[Union[Constraint, Index]], str] = {
    PrimaryKeyConstraint: "pk_%(table_name)s",
    ForeignKeyConstraint: "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    CheckConstraint: "ck_%(table_name)s_%(constraint_name)s",
    UniqueConstraint: "uq_%(table_name)s_%(column_0_N_name)s",
    Index: "ix_%(column_0_N_label)s",
}

metadata = MetaData(naming_convention=naming_convention)
```

### Error

```
<file>:<line>: error: Argument "naming_convention" to "MetaData" has incompatible type "Dict[Union[Type[Constraint], Type[Index]], str]"; expected "Optional[Dict[str, str]]"  [arg-type]
``` 

### Versions

- OS: **Debian 11.6**
- Python: **3.9.2**
- SQLAlchemy: **2.0.3**
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): **mypy 1.0.0**

**Comment by zzzeek** [comment]
hi -

this usage is, well, I'd say 100% news to me, however, that's not possible because I wrote those docs.    When I wrote them along with the feature, it seems I made the choice not to have a single unit test using this "class-based" key.   I've never seen anyone use classes for keys but sure enough there it is in the docs.    Please use strings for now.  I would need to go in and add basic tests to see if this usage even works, along with typing.

**Comment by tiesjan** [comment]
Thanks for diving into it!

It does seem to work at runtime for me, due to [line 147-148 of this file](https://github.com/sqlalchemy/sqlalchemy/blob/1b726c48384931c813d254b6451cfb6ea4e5b882/lib/sqlalchemy/sql/naming.py#L133-L150) if I'm not mistaken. For me it's just the type check that fails. However, I don't have enough experience with the SQLAlchemy code base to be sure here.

**Comment by zzzeek** [comment]
for this issue we also need to handle the value accepting a callable:

> The values associated with each “constraint class” or “constraint mnemonic” key are string naming templates, such as "uq_%(table_name)s_%(column_0_name)s", which describe how the name should be composed. The values associated with user-defined “token” keys should be callables of the form fn(constraint, table), which accepts the constraint/index object and [Table](https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Table) as arguments, returning a string result.

let's get everything mentioned at https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.MetaData.params.naming_convention all in one PR.

**Comment by CaselIT** [comment]
this is connected to #10264

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**allow any key for naming_convention dict, typing is not possible** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4882
