### ISSUE TITLE
Treat thick_mode=False as off when passed to oracledb

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9295]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9291

The current behaviour is to check only of `is not None`

**Comment by zzzeek** [comment]
weird bug

**Comment by CaselIT** [comment]
Indeed. I think it was though that people would ignore it unless required to set the thick mode. But yes having `thick_mode=False` activate the thing is indeed unfortunate
