### ISSUE TITLE
SQLAlchemy 2.0.3 is not compatible with pandas 1.3.5 on MetaData function

### ISSUE THREAD

**Issue by borgle** [sqlalchemy/sqlalchemy#9296]
### Describe the bug

when I upgrade to 2.0.x， I got below errors on read_sql.
if I upgrade pandas 1.3.5 to 1.4.2, it's running ok.

### SQLAlchemy Version in Use

2.0.3

### DBAPI (i.e. the database driver)

oracledb

### Database Vendor and Major Version

12c

### Python Version

3.8.1

### Operating system

linux

### To Reproduce

```python
import oracledb
from sqlalchemy import create_engine
import sys

import pandas as pd

oracledb.version = "8.3.0"
sys.modules["cx_Oracle"] = oracledb

engine = create_engine('oracle://user:pass@ip:1521/orcl', echo=False)

sql = 'select * from t_tablename'
with engine.connect() as conn:
    index_col = ['inter_prd_code']
    result = pd.read_sql(sql=sql, con=conn, index_col=index_col)
    result.columns = result.columns.map(lambda x: x.lower())
    print(result)
```

### Error

```
Traceback (most recent call last):
  File "test_pandas.py", line 15, in <module>
    result = pd.read_sql(sql=sql, con=conn, index_col=index_col)
  File "/usr/local/python3.7/lib/python3.7/site-packages/pandas/io/sql.py", line 599, in read_sql
    pandas_sql = pandasSQL_builder(con)
  File "/usr/local/python3.7/lib/python3.7/site-packages/pandas/io/sql.py", line 788, in pandasSQL_builder
    return SQLDatabase(con, schema=schema, meta=meta)
  File "/usr/local/python3.7/lib/python3.7/site-packages/pandas/io/sql.py", line 1410, in __init__
    meta = MetaData(self.connectable, schema=schema)
TypeError: __init__() got multiple values for argument 'schema'
```

**Comment by zzzeek** [comment]
hi - 

please make sure you are on the latest pandas release, and if the issue persists, please report it to Pandas at https://github.com/pandas-dev/pandas

**Comment by borgle** [comment]
> hi -
> 
> please make sure you are on the latest pandas release, and if the issue persists, please report it to Pandas at https://github.com/pandas-dev/pandas

what's the solution if python is 3.7.*.  the pandas 1.3.5 is the latest release.

**Comment by CaselIT** [comment]
I think your best option is to keep sqlalchemy 1.4 or update your python version
