### ISSUE TITLE
Inspector escapes `\` character in comments (for mysql at least, unknown for other backends)

### ISSUE THREAD

**Issue by maver1ck** [sqlalchemy/sqlalchemy#9326]
### Describe the bug

Inspector escapes `\` character in columns description 

### SQLAlchemy Version in Use

2.0.3

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

MySQL 8.0.31

### Python Version

3.11

### Operating system

MacOS

### To Reproduce

```python
1. Create Table with comment with `\n` sign. Example:

-- test.test definition

CREATE TABLE `test` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '123\nABC',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_polish_ci;
```
2. Run `Inspector.get_columns('test')`

```
[{'name': 'id',
  'type': INTEGER(),
  'default': None,
  'comment': '123\\nABC',
  'nullable': False,
  'autoincrement': True}]
```

### Error

As seen above `123\nABC` was changed into `123\\nABC`

**Comment by zzzeek** [comment]
thanks for reporting 

@CaselIT do you think this is MySQL only?  we should just have a suite test for this

**Comment by CaselIT** [comment]
Not sure, we can check

**Comment by maver1ck** [comment]
I think problem is here:
https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/mysql/reflection.py#L313

There is partial unescape of string done.
I would say this should be changed to
comment = comment.encode('utf8').decode("unicode_escape").replace("''", "'").

**Comment by CaselIT** [comment]
That's strange. We do have test with `\` in comments here
https://github.com/sqlalchemy/sqlalchemy/blob/c6ecc39b62b41c4f21375a51bac582c61baa3d9d/lib/sqlalchemy/testing/suite/test_reflection.py#L557-L569

I'll take a look to see what's happening

**Comment by CaselIT** [comment]
This is working as expected.
What you see is simply the python string repr
