### ISSUE TITLE
support different attr names with use_existing_column

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9332]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9330

<div type='discussions-op-text'>

<sup>Originally posted by **fanzeyi** February 18, 2023</sup>
So I'm running into a bit issue when trying to create some polymorphic classes with SQLAlchemy.

Specifically, I'm trying to have two sub-classes sharing the same column that these sub-classes declared themselves, while having a different field name.

For example (taken from SQLAlchemy document):

```python
from sqlalchemy import ForeignKey
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class Employee(Base):
    __tablename__ = "employee"
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]
    type: Mapped[str]

    __mapper_args__ = {
        "polymorphic_identity": "employee",
        "polymorphic_on": "type",
    }

    def __repr__(self):
        return f"{self.__class__.__name__}({self.name!r})"


class Engineer(Employee):
    __mapper_args__ = {
        "polymorphic_identity": "engineer",
    }

    team: Mapped[str] = mapped_column(
        "team", nullable=True, use_existing_column=True
    )


class Manager(Employee):
    __mapper_args__ = {
        "polymorphic_identity": "manager",
    }

    department: Mapped[str] = mapped_column(
        "team", nullable=True, use_existing_column=True
    )
```

I want `Manager.department` to share the same column as `Engineer.team` in the table. Even though I have specified them to be the same column name, SQLAlchemy doesn't seem to recognize that and it gives me:

```
ArgumentError: Column 'team' on class Manager conflicts with existing column 'employee.team'.  If using Declarative, consider using the use_existing_column parameter of mapped_column() to resolve conflicts.
```

However `use_existing_column=True` is already set.

I traced the code a bit and it looks like here, SQLAlchemy doesn't really consider the case where column name is explicitly specified:

https://github.com/sqlalchemy/sqlalchemy/blob/c6ecc39b62b41c4f21375a51bac582c61baa3d9d/lib/sqlalchemy/orm/properties.py#L666-L668

What do you think? Should SQLAlchemy be able to support this use case?</div>

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**consider column.name directly when evaluating use_existing_column** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4456
