### ISSUE TITLE
before_update is not triggered for update statement 

### ISSUE THREAD

**Issue by jony89** [sqlalchemy/sqlalchemy#9339]
### Describe the bug

I've registered to the `before_update` hook with:

```
class MyTable(Base):
  id = Column("id", UUID_DB(as_uuid=True), primary_key=True, default=uuid4)

from sqlalchemy import MetaData, event
event.listen(MyTable, "before_update", modified_at_hook)

def modified_at_hook(mapper, connection, target):
    ...
```

then executing an update statement:

```
stmt = (
    sqlalchemy.update(MyTable)
    .where(table.id == obj_id)
    .values(**dict_object)
    .execution_options(synchronize_session="fetch")
)
async with AsyncSession(db_engine.get_engine()) as async_session:
    result = await async_session.execute(stmt)
    await async_session.commit()
```

but the hook is not being triggered.

When I am trying to use the `merge` function of the async_session, only `before_insert` hook is triggered. and there is no `.update` method for async session.

Further more, when using the `.add` method, and the entity has id, I get exception that the entity is already exist. how can I mark the entity for update without using `SELECT`  to retrieve it first? 

### SQLAlchemy Version in Use

1.4.40

### DBAPI (i.e. the database driver)

default

### Database Vendor and Major Version

PostgreSQL 12

### Python Version

3.11

### Operating system

losx

### To Reproduce

```python
aboe
```

### Error

no error

**Comment by CaselIT** [comment]
Hi,

I believe this is expected behaviour on the 1.4 series, since core insert/update/delete are not orm enabled.
It should work on v2

@zzzeek is that correct?

**Comment by zzzeek** [comment]
> Hi,
> 
> I believe this is expected behaviour on the 1.4 series, since core insert/update/delete are not orm enabled. It should work on v2
> 
> @zzzeek is that correct?

no that is incorrect.  before_update applies only to ORM flush operations.  for all use at https://docs.sqlalchemy.org/en/20/orm/queryguide/dml.html, the only event hook to use is do_orm_execute()

**Comment by jony89** [comment]
@zzzeek is statement execute is the only way to update an entity using `UPDATE` sql statement without selecting it first with async session? is there a way to mark an entity as dirty for update?

statement execute i.e ->

```
stmt = (
    update(user_table).
    where(user_table.c.id == 5).
    values(name='user #5')
)

async with AsyncSession(db_engine.get_engine()) as async_session:
    result = await async_session.execute(stmt)
    await async_session.commit()

```

also will `do_orm_execute` will be triggered for all operations such as `.merge` or updating with sync session and `Query`?

**Comment by CaselIT** [comment]
> > Hi,
> > I believe this is expected behaviour on the 1.4 series, since core insert/update/delete are not orm enabled. It should work on v2
> > @zzzeek is that correct?
> 
> no that is incorrect. before_update applies only to ORM flush operations. for all use at https://docs.sqlalchemy.org/en/20/orm/queryguide/dml.html, the only event hook to use is do_orm_execute()

Documentation was definitely needed here. Looks clearer now

> @zzzeek is statement execute is the only way to update an entity using UPDATE sql statement without selecting it first with async session

Yes, using session.mergle will necessarily do a select first 

> also will do_orm_execute will be triggered for all operations such as .merge or updating with sync session and Query?

Yes that hook will be called for every sql that's emitted by a session

**Comment by jony89** [comment]
Thanks for the response!

I will just add that I think that `before_update` should trigger before `UPDATE`, as stated in the documentations by the way, regardless of orm flush operations. that should not be taking into account.

- today there are many threads of engineers confused exactly because of that, just search for "before_update not triggered" in stackoverflow. even a contributor here was not so sure about it.
- other ORMs whether its on node.js such as `sequelize`/`typeorm` and more in python are not distinguishing between the cases

I am suggesting to change that behavior and stick the hooks to the actual SQL statement type regardless of the type of the operation.

**Comment by CaselIT** [comment]
> I will just add that I think that before_update should trigger before UPDATE

in the current form that event can't be triggered by a bulk update operation, since it would require each orm instance to be loaded and present on the handler.

> * today there are many threads of engineers confused exactly because of that, just search for "before_update not triggered" in stackoverflow. even a contributor here was not so sure about it.

this is the first time if was reported on github, we the mantainers were not aware of the fact that the documentation was confusing

> * other ORMs whether its on node.js such as `sequelize`/`typeorm` and more in python are not distinguishing between the cases
> 
> 
> I am suggesting to change that behavior and stick the hooks to the actual SQL statement type regardless of the type of the operation.

I'm assuming they have the equivalent of `do_orm_execute`, meaning that only the statement is presented, not the actual orm object. Is that correct?
If so we can improve the docs to indicate how to replace `before_update` et al with a `do_orm_execute` for the equivalent use

**Comment by jony89** [comment]
I would never expect that the each instance will be loaded upon bulk update. 

The hooks are defined on the model, and usually there is a distinguish between bulk and instance update. for example `sequelize` provides `beforeBulkUpdate` and `beforeUpdate`. in case of a bulk, the callback only gets the update options. see https://sequelize.org/docs/v6/other-topics/hooks/

@CaselIT Is this possible to provide an example of how to update an entity/instance using async session and triggering on update hook without `SELECT` it first from the database? I've done a lot of search for that. I think that is also great example for the documentations!

**Comment by zzzeek** [comment]
> Thanks for the response!
> 
> I will just add that I think that `before_update` should trigger before `UPDATE`, as stated in the documentations by the way, regardless of orm flush operations. that should not be taking into account.
> 
>     * today there are many threads of engineers confused exactly because of that, just search for "before_update not triggered" in stackoverflow. even a contributor here was not so sure about it.
> 
>     * other ORMs whether its on node.js such as `sequelize`/`typeorm` and more in python are not distinguishing between the cases

this hook is designed to receive the actual object which is being updated by primary key alone.   The state that is provided is not possible for the use case where only an UPDATE statement, without a series of object instances that are the complete set of target instances, is provided.   The other ORMs you mention cannot possibly have an equivalent event hook unless they very wastefully run a SELECT statement for all matching rows every time one runs an arbitrary UPDATE statement.

the only argument to be made here is that the "before_update" event is poorly named given modern SQLAlchemy features.   When it was first implemented, there was no other way to run UPDATE statements.

**Comment by zzzeek** [comment]
> I would never expect that the each instance will be loaded upon bulk update.
> 
> The hooks are defined on the model, and usually there is a distinguish between bulk and instance update. for example `sequelize` provides `beforeBulkUpdate` and `beforeUpdate`. in case of a bulk, the callback only gets the update options. see https://sequelize.org/docs/v6/other-topics/hooks/

We have the do_orm_execute() event for this purpose, which is much more flexible than a fixed "before bulk update" event.  we have a deprecated [after_bulk_update](https://docs.sqlalchemy.org/en/20/orm/events.html#sqlalchemy.orm.SessionEvents.after_bulk_update) event but do_orm_execute() is more flexible for these cases.

**Comment by jony89** [comment]
@zzzeek Thanks for the detailed answer. 

I agree with everything said. 

I think that the only thing missing on my end is how should I update an entity with async session without selecting it first? as you said yourself, that is a waste of query. the only option I found is either `merge` which is not `UPDATE` or use statement execution that not triggering the `before_update` hook.

**Comment by zzzeek** [comment]
> @zzzeek Thanks for the detailed answer.
> 
> I agree with everything said.
> 
> I think that the only thing missing on my end is how should I update an entity with async session without selecting it first? as you said yourself, that is a waste of query. the only option I found is either `merge` which is not `UPDATE` or use statement execution that not triggering the `before_update` hook.

to understand the use case, can you confirm

1. you want to ultimately emit an UPDATE statement to the database
2. you want to also do something with an ORM object that somehow would be the source of data for this UPDATE statement
3. you cannot simply write an UPDATE statement with the parameters you want.  somehow you need to have an ORM object ready that somehow informs the statement

is that right?

so from my view, item 3 pushes this into the "unusual, special case" territory.   We have a method for this special case.   Create the object that you want exactly, including primary key data.  then call [make_transient_to_detached](https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.make_transient_to_detached) on it.  then .add() it to your session.

**Comment by zzzeek** [comment]
this function is noted as an alternative at the bottom of the docstring for [merge()](https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.merge)

**Comment by jony89** [comment]
Thanks @zzzeek, indeed `make_transient_to_detached` what I was looking for. yet we are using within `.add` context and not `.merge`
