### ISSUE TITLE
ExcludeConstraint  does not use literal compile when generating ddl

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9349]
Using something like
```py
ExcludeConstraint((sa.func.power(sa.column("a"), 2), '!'))
```

renders a bind param.

Ref alembic issue https://github.com/sqlalchemy/alembic/issues/1184

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**ExcludeConstraint literal_compile** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4462
