### ISSUE TITLE
attributes on mixins and superclasses that aren't MappedAsDataclass / equiv should be ignored for dataclass constructor

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9350]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9333

this probably needs to warn in some way, or raise, this unfortunately has been released for several versions and it's wrong.

dataclasses:  fields on non-dataclass superclasses don't exist:

```py
from dataclasses import dataclass
from dataclasses import field
import inspect
from typing import Optional
from uuid import uuid4

class _BaseMixin:
    create_user: int
    update_user: Optional[int] = field(default=None)

@dataclass
class Base(_BaseMixin):
    pass

@dataclass
class User(Base):
    uid: str = field(init=False, default_factory=lambda: str(uuid4()))
    username: str
    password: str
    email: str

print(inspect.getfullargspec(User.__init__))

print(User('uname', 'passwd', 'email'))
```

output:

```
FullArgSpec(args=['self', 'username', 'password', 'email'], varargs=None, varkw=None, defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={'return': None, 'username': <class 'str'>, 'password': <class 'str'>, 'email': <class 'str'>})
User(uid='70ae6ee3-648f-4d18-a387-cf511024bbf5', username='uname', password='passwd', email='email')
```

for us, we have randomly applied rules for non-dataclass superclasses (they've changed sometime between b1 and 2.0):

```py
from __future__ import annotations

import inspect
from typing import Optional
from uuid import uuid4

from sqlalchemy import String
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import MappedAsDataclass

class _BaseMixin:

    create_user: Mapped[int] = mapped_column(
        #init=False
    )
    update_user: Mapped[Optional[int]] = mapped_column(
        default=None,
        init=False
   )


class Base(DeclarativeBase, MappedAsDataclass, _BaseMixin):
    pass

class User(Base):
    __tablename__ = "sys_user"

    uid: Mapped[str] = mapped_column(
        String(50), init=False, default_factory=uuid4, primary_key=True
    )
    username: Mapped[str] = mapped_column(String(20), unique=True, index=True)
    password: Mapped[str] = mapped_column(String(255))
    email: Mapped[str] = mapped_column(String(50), unique=True, index=True)

print(inspect.getfullargspec(User.__init__))
```

output includes create_user and also would raise TypeError for update_user

```
FullArgSpec(args=['self', 'create_user', 'username', 'password', 'email'], varargs=None, varkw=None, defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})

```

in reality, create_user and update_user should not be passed to dataclasses at all, should be ignored as far as dataclasses are concerned.

however this would be backwards incompatible, the same way whatever we changed for #9333 was also backwards incompatible.   we have gotten it wrong twice.

**Comment by CaselIT** [comment]
It also seems that annotations are somewhat lost somewhere in the sqlalchemy version of dataclasses

Not sure if it's feasible to look at the python test suite for dataclass and copy parts of it over here?

**Comment by CaselIT** [comment]
> Not sure if it's feasible to look at the python test suite for dataclass and copy parts of it over here?

for reference these are the tests of dataclasses of python https://github.com/python/cpython/blob/main/Lib/test/test_dataclasses.py.
Is seems that python ships the tests, so it can be imported with `import test.test_dataclasses` (probably not from sqlalchemy home)

**Comment by CaselIT** [comment]
from the discussion

> Mike: there's unfortunately no fix for this that will not break backwards compatibility. i think we should start by warning for those fields that are incorrectly being applied.

we are doing kw on the class now. That's add a flag `correct_thing=True|False|'warn'` that defaults to `warn` and does the old thing.
We deprecated in 2.1 to allow only True (like future on create_engine)

**Comment by CaselIT** [comment]
> > Not sure if it's feasible to look at the python test suite for dataclass and copy parts of it over here?
> 
> for reference these are the tests of dataclasses of python https://github.com/python/cpython/blob/main/Lib/test/test_dataclasses.py. Is seems that python ships the tests, so it can be imported with `import test.test_dataclasses` (probably not from sqlalchemy home)

seems non trivial reusing them, since most test define the test case inside the test function, but it could still be used as reference to the inheritance tests

**Comment by zzzeek** [comment]
id prefer not to add new flags, and simply warn when these fields are detected that this is not a supported pattern, please make the class in question with the attribute we are seeing also a MappedAsDataclass, otherwise using that field in their dataclass def is undefined behavior that can change at any time and will change in 2.1 (where IMO it should raise probably).

**Comment by CaselIT** [comment]
Not sure about raising here, since dataclass is fine with that pattern.
My suggestion for the flag was to allow people to opt in the correct dataclass behaviour in 2.0

So your thinking was to disallow that pattern completely?

**Comment by zzzeek** [comment]
I think its safer to disallow it since it doesnt make any sense to use such a pattern with mapped elements specifically, so having it be silently ignored seems like a recipe for more user frustration, it seems much more likely it's a configurational mistake rather than intentional.

dataclasses itself is targeting a more open-ended set of elements but I think dataclasses should raise if you have unused field() objects like that also.

**Comment by CaselIT** [comment]
ok works for me, I don't think we have to follow 100% dataclass, but I would err on the side of more limited than of more open-ended. This behaviour is on the side of more open-ended.

So the idea is deprecation warning now, raise on 2.1, correct?

**Comment by zzzeek** [comment]
yes , likely.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**warn for DC mixin / abstract fields that are not on a dataclass** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4539
