### ISSUE TITLE
Typing error in Pylance when integrating with pydantic dataclass

### ISSUE THREAD

**Issue by Evan6998** [sqlalchemy/sqlalchemy#9354]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

when I was using `MappedAsDataclass` and integrating with pydantic dataclass to `dataclass_callable`, Pylance complains: "No overloaded function matches type "(...) -> type"

I don't know if it's an issue about `pydantic`.
Thanks for the library anyway!

### To Reproduce

```python
import pydantic

from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import MappedAsDataclass


class Base(
    MappedAsDataclass,
    DeclarativeBase,
    dataclass_callable=pydantic.dataclasses.dataclass,
):
    pass
```

### Error

with the error:

<img width="976" alt="image" src="https://user-images.githubusercontent.com/17891367/220893001-27defff4-1b6d-46e0-99d1-1bc8b90d9101.png">

### Versions

- OS: MacOS 12.3
- Python: Python 3.10.9
- SQLAlchemy: 2.0.4
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc): visual studio code plugin Pylance v2023.2.40

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting.
I'm not sure from where pylance gets that typing. This may be an option
https://github.com/sqlalchemy/sqlalchemy/blob/fc57bafbae9d67b7ce95e26c939ca957c366b0f7/lib/sqlalchemy/orm/decl_api.py#L151-L167
but it does not explain how `_NoArg` fits with it. The other alternative is that is used https://github.com/sqlalchemy/sqlalchemy/blob/fc57bafbae9d67b7ce95e26c939ca957c366b0f7/lib/sqlalchemy/orm/decl_api.py#LL587C5-L599C15 but that seems to have the correct type.

**Comment by zzzeek** [comment]
this issue does not reproduce for me with pylance and it also passes mypy 100% .  @CaselIT are you able to reproduce?

Here's mypy and pyright for me with the test program as given:

```
[classic@photon3 sqlalchemy:main]$ mypy test3.py 
Success: no issues found in 1 source file
[classic@photon3 sqlalchemy:main]$ pyright test3.py 
No configuration file found.
pyproject.toml file found at /home/classic/dev/sqlalchemy.
Loading pyproject.toml file at /home/classic/dev/sqlalchemy/pyproject.toml
Assuming Python version 3.10
Assuming Python platform Linux
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /home/classic/dev/sqlalchemy/typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.295
0 errors, 0 warnings, 0 informations 
Completed in 2.998sec
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.5.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.1
npm notice Run npm install -g npm@9.5.1 to update!
npm notice 

```

**Comment by CaselIT** [comment]
Hi,

I can reproduce using pylance in vscode and with pyright, but I think the issue is on pydantic side.
Using the plain dataclass callable works correctly.
Considering that the sqlalchemy typing here is just `Callable[..., Type[Any]]` I think the issue is that the pydantic typing is not compatible with the one of the default dataclass callable

**Comment by zzzeek** [comment]
weird mine does not reproduce anything?  what version of pydantic do you have?

**Comment by CaselIT** [comment]
The last one. I just installed it, since I did not have it installed locally.

Maybe they changed the typing?

**Comment by CaselIT** [comment]
(just checked pydantic-1.10.5)

**Comment by zzzeek** [comment]
I had 1.9.1 but 1.10.5 does reproduce with pyright.    so...yup
