### ISSUE TITLE
Random error about modifying duque when event listener is set

### ISSUE THREAD

**Issue by tharwan** [sqlalchemy/sqlalchemy#9357]
### Describe the bug

We saw some random errors occurring in production. We are not able to reproduce them nor determine the exact circumstances. 

<img width="690" alt="Screenshot 2023-02-23 at 08 20 54" src="https://user-images.githubusercontent.com/964241/220969761-72bdea3a-048e-4c9a-877e-7dddac91b232.png">

in the code we set a listener like this:
```python
 @listens_for(self._db_engine, "engine_connect", named=True)
def add_connection_timeout(conn, branch):
            # will capture all checkout events of connections from the engines pool of connections

            # the timeout will persist beyond this transaction because of the connection pooling
            # however we only want to ensure it is always set during writes
            conn.connection.connection.timeout = settings.timeout
```

however as can be seen in the traceback the listener is not invoked during the error.

Any hint how we might be able to reproduce this are very much appreciated.

### SQLAlchemy Version in Use

1.4.46

### DBAPI (i.e. the database driver)

pyodbc

### Database Vendor and Major Version

MSSQL

### Python Version

3.8

### Operating system

Linux

### To Reproduce

we have not found a way to reproduce, it passes our tests. Works in production until it does not, a few seconds later it works again.

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 120, in __init_
self.dispatch.engine_connect(self, _branch_from is not None)
L None
L ‹sqlalchemy.engine.base.Connection object at 0x7fac6cef5160>
L <member 'engine_connect of 'JoinedConnectionEventsDispatch' objects>
L <sqlalchemy.event.base. JoinedConnectionEventsDispatch object at 0x7fac6d544a00> 4 <sqlalchemy.engine. base. Connection object at 0x7fac6cef5160>
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py",line 333, in _call_.
for fn in self. listeners:
L ‹property object at Ox7fac77fba400>
LI <sqlalchemy.event.attr._JoinedListener object at Ox7fac6c3b4580>
L ‹function.
_CIsLevelDispatch._wrap_fn_for_kw.<locals>.wrap_kw at 0x7fac6db4ea60>
RuntimeError: deque mutated during iteration
```

**Comment by CaselIT** [comment]
Hi,

With the provided core it's hard to make guesses. What I can say is that it's not a common issue.

Just guessing now: are you creating events on instances of connections or session or similar in a dynamic way (meaning that you keep adding events it?) This issue may be caused by the gc that cleans up a listener target while the event dispatch is in progress, resulting in the deque changing size.

Are you creating self._db_engine or the class it's attached to dynamically?

**Comment by tharwan** [comment]
The engine can come from the outside in theory. So we don’t have full control over it.

we do not add events dynamically. So there is not much more going on regarding events that what I posted. We add the listener during init of our class.

We will try to workaround by using the first connect event and recreating the pool of the engine, so we see all connections.

**Comment by CaselIT** [comment]
If you do find a reproducing example please share.

@zzzeek do you have ideas here?

**Comment by Evan6998** [comment]
I am curious about how to record errors with typing information like your screenshot.

**Comment by zzzeek** [comment]
the error means that listeners are being added, removed, or garbage collected while the event handling is in progress.   if it's "random" then that points to threading  / concurrency concerns.    "We add the listener during init of our class.", OK, but what is "self._db_engine"?  where did "_db_engine" come from and is it shared with other instances, threads etc.

as it stands without a reproducer there's no action to take here.

**Comment by tharwan** [comment]
> I am curious about how to record errors with typing information like your screenshot.

Loguru includes those:
https://loguru.readthedocs.io/en/stable/overview.html#fully-descriptive-exceptions

**Comment by tharwan** [comment]
> the error means that listeners are being added, removed, or garbage collected while the event handling is in progress. if it's "random" then that points to threading / concurrency concerns. "We add the listener during init of our class.", OK, but what is "self._db_engine"? where did "_db_engine" come from and is it shared with other instances, threads etc.
> 
> as it stands without a reproducer there's no action to take here.

The discussion was very helpful for us nevertheless. Thanks!

**Comment by Evan6998** [comment]
> > I am curious about how to record errors with typing information like your screenshot.
> 
> Loguru includes those: https://loguru.readthedocs.io/en/stable/overview.html#fully-descriptive-exceptions

Thanks!

**Comment by tharwan** [comment]
For reference, we managed to reproduce the bug. It was down to multiple factors, we believe.

1. fastapi runs non async functions in a thread pool
2. We had a bug where our init, registering the listener would run every request

with a high number of small request there could be a situation where deque was changed while calling a listener was going on.

we managed to reproduce this by dramatically increasing the time spend in the listener function and producing many requests.

i am not sure in how far you consider this a bug on your end. We definitely had some misunderstandings about how fastAPI works in detail.

**Comment by zzzeek** [comment]
so that seems like many listeners being assigned to a single engine concurrently while requests are being served, which we'd expect to have problems, thanks for tracking that down.   I assume problem is solved now.

**Comment by PeterSR** [comment]
Thank you so much for the fast reply! 

I can see that we do `event.listen` and `event.remove` on both `Session` and specific models (like `Customer`) to be able to hook into both `after_flush`, `before_commit` etc, as well as specific updates to ORM model objects like `after_insert`, `after_update` etc. 

I will try do what you are suggesting and don't want to bother you or the others in this thread more than necessary, but I would like to know that I understand one thing correctly:

Can I do `event.listen` on `engine` to track both things like `before_commit` (related to session and connection) and `after_update` (related to specific ORM objects)

If I look here https://docs.sqlalchemy.org/en/20/orm/events.html, it seems like I need the session object.

**Comment by zzzeek** [comment]
before_commit and after_update are both session events so you can put those on your `sessionmaker` class, where they will take effect for all `Session` objects.  

```py
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

@event.listens_for("before_commit", SessionLocal)
def my_event(...):
   # ...

```

**Comment by PeterSR** [comment]
I have tried this

```python

engine = create_engine(
    SQLALCHEMY_DATABASE_URL,
    connect_args=connect_args,
    pool_size=10,
    max_overflow=50,
    echo=settings.database_echo,
    json_serializer=custom_sqlalchemy_json_serializer,
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


@event.listens_for(SessionLocal, "before_commit")
def receive_before_commit(session):
    print(session)

@event.listens_for(SessionLocal, "after_update")
def receive_after_update(mapper, connection, target):
    print(mapper, connection, target)
```

`before_commit` works, but `after_update` gives 

```
  File "sqlalchemy/event/api.py", line 171, in decorate
    listen(target, identifier, fn, *args, **kw)
  File "sqlalchemy/event/api.py", line 124, in listen
    _event_key(target, identifier, fn).listen(*args, **kw)
  File "sqlalchemy/event/registry.py", line 291, in listen
    dispatch_collection = getattr(target.dispatch, identifier)
                                  ^^^^^^^^^^^^^^^
AttributeError: 'sessionmaker' object has no attribute 'dispatch'
```

(`sqlalchemy==2.0.30`)

And according to https://docs.sqlalchemy.org/en/20/orm/events.html, it seems like it is only listed under [MapperEvents](https://docs.sqlalchemy.org/en/20/orm/events.html#sqlalchemy.orm.MapperEvents.after_update). 

But it might very well be my that is misunderstanding.

I can try to just use the mapper events on our models classes like `Customer` and then just make sure our event manager is a singleton shared between all "threads" in FastAPI.

**Comment by zzzeek** [comment]
the after_update event is per ORM mapped class, not per session.   so for that one you'd attach it either to the specific ORM mapped class you want to listen for, or you can put it across the board on your declarative `Base` class, adding propagate=True so it takes effect for subclasses 

https://docs.sqlalchemy.org/en/20/orm/events.html#sqlalchemy.orm.MapperEvents
