### ISSUE TITLE
Expanded definitions in dialect for insert statements

### ISSUE THREAD

**Issue by alexclavel-ocient** [sqlalchemy/sqlalchemy#9362]
### Describe the use case

Hi, I am writing a sqlalchemy driver for Ocient, and am currently running into issues formatting insert queries.

I would like to define certain definitions in the dialect:

- boolean value denoting whether to include column specifiers in insert statements
- boolean value denoting whether to wrap values in parentheses in insert statements
- prefix and postfix strings to wrap values lines in insert statements

### Databases / Backends / Drivers targeted

This would be a drop-in replacement for all dialects, as current behavior can be preserved through values in the default dialect. The goal is to use this in [sqlalchemy_ocient](https://pypi.org/project/sqlalchemy-ocient/).

### Example Use

As it stands, for Ocient, the query

INSERT INTO foo
  (col1, col2, col3)
  VALUES (c1r1, c2r1, c3r1)
  VALUES (c1r12, c2r2, c3r2)
  VALUES ...

is formatted:

INSERT INTO foo
   SELECT c1r1, c2r1, c3r1 UNION ALL
   SELECT c1r12, c2r2, c3r2 UNION ALL
   SELECT ...

This can be achieved by changing the proposed defaults (names are placeholder):

- include_col_names: True
- wrap_values_parentheses: True
- values_prefix: 'VALUES'
- values_postfix: ''

to different values in the Ocient dialect:

- include_col_names: False
- wrap_values_parentheses: False
- values_prefix: 'SELECT'
- values_postfix: 'UNION ALL'

### Additional context

I am cognizant that this may not be the best solution, nor something that SQLAlchemy wants to do. Please let me know what you think.

**Comment by zzzeek** [comment]
hi -

these are attributes that are not currently necessary for any other SQL dialect, and they introduce fine-grained behavior within SQLAlchemy directly that seem to specific to what ocient is looking for.  another dialect with highly unusual requirements could also come along for which these parameters are insufficient.    

Therefore we can support template methods within visit_insert for this instead, as these are more open ended for the third party dialect to do whatever is needed, and this also places the burden of implementing and testing these alternative syntaxes on the third party dialect, not on SQLAlchemy.

Here's a template method proposal that we could add test support for, let me know if you can inject your custom routines within this format.

```diff
diff --git a/lib/sqlalchemy/sql/compiler.py b/lib/sqlalchemy/sql/compiler.py
index bc463f9a1e..8278df6803 100644
--- a/lib/sqlalchemy/sql/compiler.py
+++ b/lib/sqlalchemy/sql/compiler.py
@@ -5357,7 +5357,6 @@ class SQLCompiler(Compiled):
             crud_params_single = crud_params_struct.single_params
 
         preparer = self.preparer
-        supports_default_values = self.dialect.supports_default_values
 
         text = "INSERT "
 
@@ -5377,10 +5376,9 @@ class SQLCompiler(Compiled):
 
         text += table_text
 
-        if crud_params_single or not supports_default_values:
-            text += " (%s)" % ", ".join(
-                [expr for _, expr, _, _ in crud_params_single]
-            )
+        text += self._render_insert_columns_clause(
+            insert_stmt, compile_state, crud_params_struct, **kw
+        )
 
         if self.implicit_returning or insert_stmt._returning:
 
@@ -5396,6 +5394,67 @@ class SQLCompiler(Compiled):
         else:
             returning_clause = None
 
+        text += self._render_insert_values_clause(
+            insert_stmt,
+            compile_state,
+            crud_params_struct,
+            toplevel=toplevel,
+            counted_bindparam=counted_bindparam,
+            **kw,
+        )
+
+        if insert_stmt._post_values_clause is not None:
+            post_values_clause = self.process(
+                insert_stmt._post_values_clause, **kw
+            )
+            if post_values_clause:
+                text += " " + post_values_clause
+
+        if returning_clause and not self.returning_precedes_values:
+            text += " " + returning_clause
+
+        if self.ctes and not self.dialect.cte_follows_insert:
+            nesting_level = len(self.stack) if not toplevel else None
+            text = (
+                self._render_cte_clause(
+                    nesting_level=nesting_level,
+                    include_following_stack=True,
+                )
+                + text
+            )
+
+        self.stack.pop(-1)
+
+        return text
+
+    def _render_insert_columns_clause(
+        self, insert_stmt, compile_state, crud_params_struct, **kw
+    ):
+        supports_default_values = self.dialect.supports_default_values
+        crud_params_single = crud_params_struct.single_params
+        text = ""
+        if crud_params_single or not supports_default_values:
+            text += " (%s)" % ", ".join(
+                [expr for _, expr, _, _ in crud_params_single]
+            )
+        return text
+
+    def _render_insert_values_clause(
+        self,
+        insert_stmt,
+        compile_state,
+        crud_params_struct,
+        *,
+        toplevel,
+        counted_bindparam,
+        **kw,
+    ):
+
+        text = ""
+
+        supports_default_values = self.dialect.supports_default_values
+        crud_params_single = crud_params_struct.single_params
+
         if insert_stmt.select is not None:
             # placed here by crud.py
             select_text = self.process(
@@ -5461,28 +5520,6 @@ class SQLCompiler(Compiled):
                     counted_bindparam,
                 )
 
-        if insert_stmt._post_values_clause is not None:
-            post_values_clause = self.process(
-                insert_stmt._post_values_clause, **kw
-            )
-            if post_values_clause:
-                text += " " + post_values_clause
-
-        if returning_clause and not self.returning_precedes_values:
-            text += " " + returning_clause
-
-        if self.ctes and not self.dialect.cte_follows_insert:
-            nesting_level = len(self.stack) if not toplevel else None
-            text = (
-                self._render_cte_clause(
-                    nesting_level=nesting_level,
-                    include_following_stack=True,
-                )
-                + text
-            )
-
-        self.stack.pop(-1)
-
         return text
 
     def update_limit_clause(self, update_stmt):

```

**Comment by zzzeek** [comment]
for that second part, probably something more like this:

```
        elif not crud_params_single and supports_default_values:
            text += self._render_insert_default_values(...)
        elif compile_state._has_multi_parameters:
            text += self._render_insert_multi_parameters(...)
        else:
            text += self._render_insert_single_parameters(...)

```

I dont want to expose the _CrudParamElement type to third parties.     The _InsertManyValues part of it, I may have to expose, as that would also have to be something you'd want to fill in, assuming you want to support InsertManyValues.

**Comment by zzzeek** [comment]
another approach that might be worth it here is to just receive the default INSERT output and use a regular expression to rewrite VALUES clauses using that syntax.  that syntax is very unusual and I'd be petitioning Ocient to please support standard syntax on their end if it were me.

**Comment by jwilliams-ocient** [comment]
> another approach that might be worth it here is to just receive the default INSERT output and use a regular expression to rewrite VALUES clauses using that syntax. that syntax is very unusual and I'd be petitioning Ocient to please support standard syntax on their end if it were me.

Yep, completely agree that this syntax is unusual. For context, Ocient does have proper `INSERT INTO` support on the product roadmap, but that work item is currently in the backlog.

One other problem is that the `sqlalchemy-ocient 1.0.x` is not compatible with `sqlalchemy >= 2.0.0` just yet so I think we'd also need a 1.4.47 release as well.

We'll explore the regex path first though - this is a good suggestion. At this time, we really only need `INSERT` support to run the integration tests so a best-effort regex _might_ be good enough as a stopgap solution. 

Thanks for looking into this @zzzeek , we'll circle back with our findings.

**Comment by CaselIT** [comment]
> One other problem is that the `sqlalchemy-ocient 1.0.x` is not compatible with `sqlalchemy >= 2.0.0` just yet so I think we'd also need a 1.4.47 release as well.

I don't think back porting this to 1.4 is a good options, since 1.4 should be mostly in feature freeze &  bugfix at this point

**Comment by jwilliams-ocient** [comment]
> I don't think back porting this to 1.4 is a good options, since 1.4 should be mostly in feature freeze & bugfix at this point

Ah, that makes sense. So it sounds like the options available to us are to either:
1. Add support for the `INSERT INTO` syntax
2. Or apply a regex to rewrite the columns/values clauses in the non-standard Ocient syntax

Neither of these options require changes to the SQLAlchemy core library. I will defer to @alexclavel-ocient on whether or not to close this ticket.
