### ISSUE TITLE
incredible automap issue creating inheritance where there is none

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9367]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9360

I looked through automap and in no place does it create inheriting classes, so for the next five minutes until I see where this goes wrong, let's enjoy a totally impossible paradox of a test case

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy.ext.automap import automap_base

engine = create_engine('sqlite://', echo=True)

Base = automap_base()

class TestData(Base):
    __tablename__ = 'testdata'
    id = Column('id',Integer,autoincrement=True, primary_key=True)



class TestUser(Base):
    __tablename__ = 'testuser'
    id = Column('id',Integer,autoincrement=True, primary_key=True)




TestData.metadata.create_all(engine)
TestData.prepare(engine)

TestUser.metadata.create_all(engine)
TestUser.prepare(engine)


```

it seems to want to find a foreign key between these two and in later 1.4 versions ends up with

```
sqlalchemy.exc.NoForeignKeysError: Can't determine the inherit condition between inherited table 'testdata' and inheriting table 'testuser'; tables have no foreign key relationships established.  Please ensure the inheriting table has a foreign key relationship to the inherited table, or provide an 'on clause' using the 'inherit_condition' mapper argument.

```

In earlier versions it crashes on trying to find FKs between the two classes.  issue is on 2.0 as well (!!!!) even after we made some improvements to automap in #5145 which explicitly allows multiple prepare() calls.

the issue seems to be related to calling prepare() from the mapped class and not the base.

**Comment by zzzeek** [comment]
this issue is in earlier versions but only occurs for the off-label use illustrated above.  since we have refactored automap for 2.0 it would be easier for this to be a 2.0 local thing.

**Comment by zzzeek** [comment]
when we do this

```py
                    mapped_cls = type(
                        newname,
                        (cls,),
                        clsdict,
                    )

```

we didnt check that "cls" is the automap base, so it uses the given class.   very simple...

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**locate automap base in hierarchy directly** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4466
