### ISSUE TITLE
.values() requires a dict[Union[...], ...]

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#9376]
### Describe the typing issue

The .values() method requires a dict, which makes it rather cumbersome to type, as the type must match the full definition.
https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/sql/dml.py#L947

Maybe this should be typed as Mapping instead? In that case, it should probably work with an intersection of the dict types.

### To Reproduce

```python
d: dict[str, Any]
sa.insert(table).values(d)
```

### Error

```
aiohttp_admin/backends/sqlalchemy.py:107:50: error: Argument 1 to "values" of "ValuesBase" has incompatible type "Dict[str, Any]"; expected
"Union[Dict[Union[str, _HasClauseElement, DMLColumnRole, SQLCoreOperations[Any]], Any], Sequence[Any]]"  [arg-type]
                stmt = sa.insert(self._table).values(params["data"]).returning(*self._table.c)
                                                     ^~~~~~~~~~~~~~
``` 

### Versions

- Python: 3.9
- SQLAlchemy: 2.0.4
- Type checker: mypy 1.0.1

### Additional context

I think the reason it won't allow dict[str, Any] is because a function with that signature could assign non-str keys into the passed dict. With a Mapping, which is immutable, I would expect mypy to allow passing this dict.

**Comment by zzzeek** [comment]
right, Mapping allows the keys to be more limited, got it

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**use read-only Mapping for values dictionary type** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4472
