### ISSUE TITLE
Execution result of a update statement have no typing for `rowcount` member

### ISSUE THREAD

**Issue by ykun91** [sqlalchemy/sqlalchemy#9377]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

The execution result of a update statement seems have no `rowcount` member in typing, but it actually have `rowcount` in runtime.

And, the `result` is typed as `Result[Any]`. But in runtime, it is a instance of `CursorResult`, which have `rowcount` as member. 

Sorry I don't sure whether the api is a module listed in #6810 or not, as `sqlalchemy.sql.update` is not listed in that, I opened this Issue.

Runtime debug output ↓
![スクリーンショット 2023-02-27 14 54 16](https://user-images.githubusercontent.com/10774721/221485479-c956b1dd-ca0c-40a4-bc32-741ed18b8a93.png)

### To Reproduce

```python
from datetime import datetime

from pydantic import BaseModel, Field
from sqlalchemy import update
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import BIGINT, TIMESTAMP, VARCHAR


class TestUpdate(BaseModel):
    name: str | None = Field(None, description='Name')
    address: str | None = Field(None, description='Address')
    email: str | None = Field(None, description='Email')


class Base(DeclarativeBase):
    pass


class TestORM(Base):
    __tablename__ = 'test'

    id: Mapped[int] = mapped_column(BIGINT, primary_key=True)
    name: Mapped[str] = mapped_column(VARCHAR(64))
    address: Mapped[str] = mapped_column(VARCHAR(256))
    email: Mapped[str] = mapped_column(VARCHAR(64))
    update_time: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True))
    create_time: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True))


async def test_update(db: AsyncSession, update_id: str, update_data: TestUpdate):
    stmt = update(TestORM).where(
        TestORM.id == update_id
    ).values(
        update_time=datetime.now(),
        **update_data.dict(exclude_none=True)
    )

    result = await db.execute(stmt)
    await db.commit()

    return result.rowcount
```

### Error

"Result[Any]" has no attribute "rowcount"  [attr-defined] mypy(error) [Ln 42, Col 12]

Cannot access member "rowcount" for type "Result[Any]" Pylance(reportGeneralTypeIssues) [Ln42, Col 19]
  Member "rowcount" is unknown

### Versions

- OS: macOS Ventura 13.2.1
- Python: 3.10.8
- SQLAlchemy: 2.0.4
- Type checker: mypy 1.0.1, Pylance v2023.2.40

**Comment by zzzeek** [comment]
#9815

**Comment by ykun91** [comment]
@zzzeek Thanks! I did not noticed this issued is already reported.

I have read the #9185, and yes maybe many people need the `rowcount`.

But I more likely to return the updated ORM instance if I can.

The reason the I  use the core `update` instead of the ORM way, is because sometimes it is more convenient to use the core `update` as I can use `update().values(**update_data)`

as I understand it. If I update data in the ORM way, I need to write code like following, which is awful.

``` python
async def test_update(db: AsyncSession, update_id: str, update_data: TestUpdate):
    stmt = select(TestORM).where(
        TestORM.id == update_id
    )

    result = await db.execute(stmt)
    test = result.scalar()

    if test is None:
        return None

    if update_data.name:
        test.name = update_data.name
    if update_data.address:
        test.address = update_data.address
    if update_data.email:
        test.email = update_data.email

    await db.commit()
    return test
```

maybe I can use `test.__dict__.update(update_data.dict(exclude_none=True))`, but I don't know whether this way is intended by SQLAlchemy and works fine or not.

**Comment by ykun91** [comment]
Oh, I notice that I can use `setattr` to do that.

Thanks, have a nice day.
