### ISSUE TITLE
Pyright warnings in strict mode: type is partially unknown for op.create_index and sa.Column (when sa.Numeric type is used)

### ISSUE THREAD

**Issue by AlexanderPodorov** [sqlalchemy/sqlalchemy#9391]
Two typing warnings in VSCode in strict mode (type is partially unknown):

Example of `op.create_index`:
`op.create_index(op.f('ix_token_expired_at'), 'token', ['expired_at'], unique=False)`
warning: Type of "create_index" is partially unknown
reason (most likely): `columns` parameter has type `Sequence[str | TextClause | Function[Unknown]]`. `Function` generic is missing type parameter.

Example of `sa.Column` with `sa.Numeric` (all other types seem to work well):
`sa.Column('tax_percentage', sa.Numeric(precision=8, scale=2), nullable=False),`
warning: Argument type is partially unknown
reason (most likely): `Numeric` class has following signature:
```python
_N = TypeVar("_N", bound=Union[decimal.Decimal, float])

class Numeric(HasExpressionLookup, TypeEngine[_N]):
    ...
```
I believe `_N` should be defined as `_N = TypeVar("_N", decimal.Decimal, float)`, so no `bound=` and `Union`.

**Expected behavior**
No warnings produced

**Versions.**
 - OS: MacOS
 - Python: 3.11.2
 - Alembic: 1.9.4
 - SQLAlchemy: 2.0.4
 - Database: Postgres 14
 - DBAPI: asyncpg

Thanks a lot for `sqlalchemy` and `alembic`!

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add missing overload to Numeric** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4482

**Comment by AlexanderPodorov** [comment]
@CaselIT , what do you think about issue with `op.create_index`? It was the first typing issue I mentioned. Thanks!

**Comment by CaselIT** [comment]
oh I though the issue was only with numeric. Can you reproduce also without invoicing numeric at all?

**Comment by AlexanderPodorov** [comment]
Sorry I did the wrong thing posting two different issues into one ticket...
`op.create_index` shows warning no matter what datatype is (I believe due to missing type arg for `Function` generic)

> Can you reproduce also without invoicing numeric at all?

Sorry, I did not get what you mean here.

**Comment by CaselIT** [comment]
ok, no problem. Can you re-open the issue in alembic? Sorry about that!

**Comment by CaselIT** [comment]
yes, feel free to link this one.

**Comment by CaselIT** [comment]
> > Can you reproduce also without invoicing numeric at all?
> 
> Sorry, I did not get what you mean here.

(I meant involving, sorry for the confusion. you answered in any case)
