### ISSUE TITLE
Support for PostgreSQLs CIText

### ISSUE THREAD

**Issue by julian-r** [sqlalchemy/sqlalchemy#9416]
### Describe the use case

[`citext`](https://www.postgresql.org/docs/current/citext.html) is a useful data type in databases that allows case-insensitive text comparisons. This is particularly helpful when working with text data where different cases may be used interchangeably, such as with usernames or email addresses. By supporting CIText, SQLAlchemy can provide a more seamless experience for developers working with such data.

There are implementations of this, but they are quite unmaintained, E.g.:
 - https://github.com/mahmoudimus/sqlalchemy-citext

Also, django ORM supports it:
 - https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/fields/#citext-fields
 
### Databases / Backends / Drivers targeted

PostgreSQL, optionally also have a version for other databases with coerce. 

### Example Use

```py
from sqlalchemy.dialects.postgresql import CIText

# use CIText as column

```

### Additional context

I am happy to provide a PR.

**Comment by zzzeek** [comment]
looks useful thanks!

**Comment by sqla-tester** [comment]
**Julian David Rath** has proposed a fix for this issue in the **main** branch:

**Implementation of CITEXT , unittest and documentation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4488
