### ISSUE TITLE
building wheels failed for 2.0.5

### ISSUE THREAD

**Issue by onerandomusername** [sqlalchemy/sqlalchemy#9429]
### Describe the bug

Don't know much about the wheel process here but was watching the logs and PyPI. https://github.com/sqlalchemy/sqlalchemy/actions/runs/4339180666

### SQLAlchemy Version in Use

2.0.5

### DBAPI (i.e. the database driver)

any

### Database Vendor and Major Version

any

### Python Version

3.7+

### Operating system

all compiled wheels, pure python unaffected

### To Reproduce

```python
Simply `pip install sqlalchemy==2.0.5`, or view the wheels on pypi compared to 2.0.4

2.0.5: https://pypi.org/project/SQLAlchemy/2.0.5/#files
2.0.4: https://pypi.org/project/SQLAlchemy/2.0.4/#files
```

### Error

Full logs are here https://github.com/sqlalchemy/sqlalchemy/actions/runs/4339180666

### Additional context

Sorry if this is already known/unhelpful. I wanted to report it as I discovered it the easy way, before it affects anyone expecting the missing wheels.

**Comment by zzzeek** [comment]
I am preparing 2.0.5post1 and 2.0.5 will be yanked

**Comment by onerandomusername** [comment]
> I am preparing 2.0.5post1 and 2.0.5 will be yanked

@zzzeek Looks like wheels won't build in CI unless there's a new release and tag.

https://github.com/sqlalchemy/sqlalchemy/blob/67ce99402a848c3553e53e51c79db8e765fb4295/.github/workflows/create-wheels.yaml#L3-L7

**Comment by CaselIT** [comment]
Note that we could have avoided the post release, by doing something like the following:
- start a branch from the tag
- fix the wheel issue, keeping the version number 2.0.5
- a tag and github release named something like "2.0.5.wheels"
- the wheel pipeline starts and pushes to the same pypi release
- merge/cherry pick the fix also in main

IIIRC I did something along these lines in the 1.4 series when some wheels did bot build for an issue on the release pipeline.

Not sure if this alternative is any better, just mentioning it.
