### ISSUE TITLE
The wheel test suite is running without cython making the tests basically useless

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9434]
As evidenced in https://github.com/sqlalchemy/sqlalchemy/issues/9423#issuecomment-1455958490 the wheel tests seems to work with the pure python version of the rows, since that bug only happed when loading a python only serialized row into a cython enabled sqlalchemy.

Proposed fix are:
- understand why the wheel run in python only mode
- add env variable (or set it) to ensure that the test run in cython mode

**Comment by CaselIT** [comment]
no, I've yet to look at this. I will try fixing for 2.0.7

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improved wheel pipeline** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4517
