### ISSUE TITLE
Cannot call `.exists()` with empty `sa.select()`

### ISSUE THREAD

**Issue by alphavector** [sqlalchemy/sqlalchemy#9440]
### Describe the bug

Since sqlalchemy version 2.0 you cannot call `.exists()` without specifying the `.select()` arguments.

But Postgres [allows to call `SELECT` without specifying columns](https://www.postgresql.org/docs/15/sql-select.html#:~:text=Empty%20SELECT%20Lists,DISTINCT%20is%20used.) (although this is not allowed syntax according to SQL standard)

https://sqlize.online/sql/psql15/82d7212d49769da33d7106f8f54fc2bb/

And this is a feature of Postgres, for other databases it is an unacceptable syntax

### SQLAlchemy Version in Use

2.0.5

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.11.1

### Operating system

OSX

### To Reproduce

```python
import sqlalchemy as sa
tbl = sa.table("tbl", sa.column("id"))
str(sa.select().select_from(tbl).where(tbl.c.id == 123).exists())
```

### Error

```python
  File ".../venv/lib/python3.11/site-packages/sqlalchemy/sql/selectable.py", line 5170, in _scalar_type
    elem = self._raw_columns[0]
           ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
``` 

### Additional context

**Expected behavior**
`EXISTS (SELECT  \nFROM tbl \nWHERE tbl.id = :id_1)`

**Possible solutions:**

* Explicitly disallow calling without arguments, so that the user explicitly specifies `sa.select(sa.literal(1))`.
* Return NULLTYPE if `_raw_columns` is empty

```diff
diff --git a/lib/sqlalchemy/sql/selectable.py b/lib/sqlalchemy/sql/selectable.py
index 39ef420dd..cefb5816a 100644
--- a/lib/sqlalchemy/sql/selectable.py
+++ b/lib/sqlalchemy/sql/selectable.py
@@ -88,6 +88,7 @@ from .elements import GroupedElement
 from .elements import literal_column
 from .elements import TableValuedColumn
 from .elements import UnaryExpression
+from .sqltypes import NULLTYPE
 from .operators import OperatorType
 from .visitors import _TraverseInternalsType
 from .visitors import InternalTraversal
@@ -5167,6 +5168,9 @@ class Select(
         GenerativeSelect.__init__(self)
 
     def _scalar_type(self) -> TypeEngine[Any]:
+        if not self._raw_columns:
+            return NULLTYPE
+
         elem = self._raw_columns[0]
         cols = list(elem._select_iterable)
         return cols[0].type
```

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting.
Personally I have no preference on this, but of the two I would go for preventing empty selects.

**Comment by zzzeek** [comment]
I would go for restoring what 1.4 does at the moment ... :)    esp that PG accepts it.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**resolve select to NULLTYPE if no columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4495

**Comment by zzzeek** [comment]
pretty much sure

**Comment by CaselIT** [comment]
ok then. did not check what 1.4 did, assumed it was similarly broken

**Comment by alphavector** [comment]
Just for the record: it worked in version 1.4
```
~ > docker run -it python:3.11.1-slim bash
root@826ea1a09665:/# pip install "sqlalchemy<2.0"
<.............>
Successfully installed greenlet-2.0.2 sqlalchemy-1.4.46
root@826ea1a09665:/# python
Python 3.11.1 (main, Feb  4 2023, 14:44:26) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy as sa
>>> tbl = sa.table("tbl", sa.column("id"))
>>> str(sa.select().select_from(tbl).where(tbl.c.id == 123).exists())
'EXISTS (SELECT  \nFROM tbl \nWHERE tbl.id = :id_1)'
>>>
```
