### ISSUE TITLE
2.0.4: versioned as `dev`

### ISSUE THREAD

**Issue by kloczek** [sqlalchemy/sqlalchemy#9448]
### Describe the bug

Just noticed that in pip output `sqlalchemy` is versioned as `2.0.4.dev0`.
Is it any reason why it is versioned las dev? 🤔 

### SQLAlchemy Version in Use

2.0.4

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.8.16

### Operating system

Linux/x86_64

### To Reproduce

```python
Just look on `pip show sqlalchemy` after install
```

### Error

```console
[tkloczko@pers-jacek Packages]$ pip show sqlalchemy
Name: SQLAlchemy
Version: 2.0.4.dev0
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: /usr/lib64/python3.8/site-packages
Requires: greenlet, typing-extensions
Required-by:
```

### Additional context

N/A

**Comment by kloczek** [comment]
https://github.com/sqlalchemy/sqlalchemy/blob/b97b313c6eb7f2fe4b98d011c292de4d258c508c/setup.cfg#L84-L85

**Comment by zzzeek** [comment]
builds from git are tagged as dev.   the releases on pypi do not have this tag

**Comment by kloczek** [comment]
Just checked what is on tagged 2.0.5 and still it is versioned as dev
https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0_5/setup.cfg#L84-L85

**Comment by zzzeek** [comment]
is https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0_5/setup.cfg#L84-L85 a release on pypi?

the release on pypi is https://files.pythonhosted.org/packages/a6/40/59fabc00cfaf0e505555dfdcdd56e450097176e9c5d33c71da825b0fbfe0/SQLAlchemy-2.0.5.post1.tar.gz

they're listed here:  https://pypi.org/project/SQLAlchemy/#files

**Comment by zzzeek** [comment]
no

**Comment by zzzeek** [comment]
pretty sure you asked this a few years back, or someone else did, answer is still no, sorry

**Comment by CaselIT** [comment]
> Just checked what is on tagged 2.0.5 and still it is versioned as dev https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0_5/setup.cfg#L84-L85

we remove that tag with a `sed` like command in the wheel pipeline before releaseing to pypi. that prevents unwanted releases from being made, since they would me tagged as `dev`

**Comment by zzzeek** [comment]
from git we generate the docs into the doc/ directory using "make dist-html" and we remove the dev tag.  that's where the release comes from

> So it means that it is not possible to reproduce the same state using git tree ..

Most projects don't use tag_build=dev anymore, and it looks like when we move to [non-setup.cfg builds](https://packaging.python.org/en/latest/tutorials/packaging-projects/) we will move onto newer conventions.
