### ISSUE TITLE
cast(Integer) fail with typing error while cast(Numeric) works, the issues reported by pylance

### ISSUE THREAD

**Issue by PiotrCzapla** [sqlalchemy/sqlalchemy#9451]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

Pylance complains that the Integer cannot be casted to TypeEngine[_OPT@op] because `int` cannot be cast to `_OPT@op`. It does not have issues if cast receives Numeric as type_. 
mypy works fine though. 

### To Reproduce

```python
This unit test that works fine shows a typing error

import copy

import pytest
from sqlalchemy import JSON, Integer, Float, create_engine, select
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column


class Base(DeclarativeBase): pass
class A(Base):
    __tablename__ = 'a'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    data: Mapped[dict|None] = mapped_column(JSON)
    

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)

s.add(A(data={"foo": ["one", "two"], "product_id": "10"}))
s.commit()  # test commit


def test_cast_integer():
    assert s.scalar(select(A.data.op('->>')('product_id').cast(Integer))) == 10 # typing error is here
    s.rollback()
    
def test_cast_numeric():
    assert s.scalar(select(A.data.op('->>')('product_id').cast(Float))) == 10.0
    s.rollback()

```

### Error

``` 
Found 1 source file
pyright 1.1.297
/Users/pczapla/WorkJB/simplerp/tests/test_database_sqllite_json_cast.py
  /Users/pczapla/WorkJB/simplerp/tests/test_database_sqllite_json_cast.py:26:64 - error: Argument of type "Type[Integer]" cannot be assigned to parameter "type_" of type "Type[TypeEngine[_OPT@op]] | TypeEngine[_OPT@op]" in function "cast"
    Type "Type[Integer]" cannot be assigned to type "Type[TypeEngine[_OPT@op]] | TypeEngine[_OPT@op]"
      "Type[Integer]" is incompatible with "Type[TypeEngine[_OPT@op]]"
      Type "Type[Integer]" cannot be assigned to type "Type[TypeEngine[_OPT@op]]"
        TypeVar "_T@TypeEngine" is invariant
          Type "int" cannot be assigned to type "_OPT@op"
      "Type[type]" is incompatible with "Type[TypeEngine[_OPT@op]]" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations 
Completed in 1.006sec
```
### Versions

- OS: mac os
- Python: python3.11
- SQLAlchemy: 2.0.5.post1
- Type checker: pyright v1.1.297 (and pylance), works with mypy 1.1.1

### Additional context

Thank you for the SQLAlchemy so far the experience is great!

**Comment by zzzeek** [comment]
wow i have no idea what the heck that is.   looking

**Comment by zzzeek** [comment]
OK Float works because by itself Float is still ambiguous as a type because it is generic.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Use independent TypeVar for ColumnElement.cast** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4499
