### ISSUE TITLE
Minor improvements in sqlalchemy/cyextension/collections.pyx

### ISSUE THREAD

**Issue by matusvalo** [sqlalchemy/sqlalchemy#9477]
### Describe the use case

Cython module collections.pyx is missing in several places:

* type annotations - e.g. `OrderedSet.update()` method is returning `OrderedSet`
* marking method as `cpdef` instead of `def` to optimise access - e.g. `OrderedSet.update()`
* private methods can marked as `@cython.final`

All improvements are yielding slightly more optimised code but it does not improve significantly performance though. 

### Databases / Backends / Drivers targeted

N/A

### Example Use

N/A

**Comment by CaselIT** [comment]
thanks.

btw not very user friendly and documented, but there is a naive perf suite at `python test/perf/compiled_extensions.py IdentitySet` and `python test/perf/compiled_extensions.py OrderedSet` you can check

**Comment by matusvalo** [comment]
Additional possible improvement can be to replace all occurrences of `in self` in `OrderedSet` class with direct call of `PySet_Contains`. This will replace `PySequence_Contains` with `PySet_Contains` which should be faster in theory. Unfortunately, I am not seeing any visible performance improvement (maybe hidden in the noise) in performance suite. I consider the change too invasive for something having almost no performance impact. But I can create separate PR if there is interest in this change.

**Comment by matusvalo** [comment]
> thanks.
> 
> btw not very user friendly and documented, but there is a naive perf suite at `python test/perf/compiled_extensions.py IdentitySet` and `python test/perf/compiled_extensions.py OrderedSet` you can check

Yes I used that suite.

**Comment by CaselIT** [comment]
I think that I may have investigate some of these changes while writing that code, and I too came to the conclusion that with the current perf suite there does not seem to be much difference.

it may well be that the suite is not that good (feel free to update it if you like)

**Comment by sqla-tester** [comment]
**Matus Valo** has proposed a fix for this issue in the **main** branch:

**Minor improvements in collections.pyx** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4510
