### ISSUE TITLE
Add missing copy and pop to ordered set

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9487]
util.OrderedSet is kinda private, but it probably makes sense to implement these two methods.
They are most likely not implemented because sqlalchemy does not use them.

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Add missing methods to OrderedSet.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4513

**Comment by CaselIT** [comment]
@matusvalo if you could take a look at that patch it would be appreciated!
