### ISSUE TITLE
Bug loading relationship when using selectinload() with case insensitive fields

### ISSUE THREAD

**Issue by jordantshaw** [sqlalchemy/sqlalchemy#9488]
### Describe the bug

MSSQL by default it is case insensitive.  So case doesn't matter when using foreign keys. In SA when using the default lazy-load behavior on  a relationship this works the same way.  Meaning the case doesnt matter, as long as the keys match (regardless of case) the relationship is correctly loaded.  
 
 However this is not the behavior when preloading a relationship using the `selectinload()` function in a SA query.  When using `selectinload()` to preload a relationship in a SA query, it causes  the join to become case sensitive and returns null. 

### SQLAlchemy Version in Use

1.4.1

### DBAPI (i.e. the database driver)

pyodbc

### Database Vendor and Major Version

MS SQL Server 2019

### Python Version

3.10.6

### Operating system

OSX

### To Reproduce

```python
class EntityAddress(Base):
    __tablename__ = 'EntityAddress'

    entity_address_id = Column(UNIQUEIDENTIFIER, primary_key=True)
    address_type_code = Column(ForeignKey('dbo.AddressType.address_type_code'), nullable=False)
    
    type = relationship('AddressType', back_populates='entity_address')


class AddressType(Base):
    __tablename__ = 'AddressType'

    name = Column(String(128), nullable=False)
    address_type_code = Column(String(10), primary_key=True)

    entity_address = relationship("EntityAddress", back_populates="type")


query = (
    select(models.EntityAddress)
    .options(
        selectinload(models.EntityAddress.type),
    )
)

results = session.execute(query).scalars().all()
for row in results:
    print(row.type)
```

### Error

```
N/A
```

**Comment by zzzeek** [comment]
there's no complete test case attached here so I rounded it out with some data.  everything works as expected:

```py
import uuid

from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import query
from sqlalchemy.orm import relationship
from sqlalchemy.orm import selectinload
from sqlalchemy.orm import Session
from sqlalchemy.orm import session

Base = declarative_base()


class EntityAddress(Base):
    __tablename__ = "EntityAddress"

    entity_address_id = Column(UNIQUEIDENTIFIER, primary_key=True)
    address_type_code = Column(
        ForeignKey("AddressType.address_type_code"), nullable=False
    )

    type = relationship("AddressType", back_populates="entity_address")


class AddressType(Base):
    __tablename__ = "AddressType"

    name = Column(String(128), nullable=False)
    address_type_code = Column(String(10), primary_key=True)

    entity_address = relationship("EntityAddress", back_populates="type")


e = create_engine(
    "mssql+pyodbc://scott:tiger^5HHH@mssql2017:1433/test?driver=ODBC+Driver+13+for+SQL+Server",
    echo=True,
)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

session = Session(e)

session.add_all(
    [
        AddressType(
            name="ac1name",
            address_type_code="ac1",
            entity_address=[
                EntityAddress(entity_address_id=uuid.uuid4()),
                EntityAddress(entity_address_id=uuid.uuid4())
            ],
        ),
        AddressType(
            name="ac2name",
            address_type_code="ac2",
            entity_address=[
                EntityAddress(entity_address_id=uuid.uuid4()),
                EntityAddress(entity_address_id=uuid.uuid4())
            ],
        )

    ]
)

session.commit()

query = select(EntityAddress).options(
    selectinload(EntityAddress.type),
)

results = session.execute(query).scalars().all()
for row in results:
    print(row.type)

```

output:

```
SELECT [EntityAddress].entity_address_id, [EntityAddress].address_type_code 
FROM [EntityAddress]
2023-03-14 19:41:58,142 INFO sqlalchemy.engine.Engine [generated in 0.00018s] ()
2023-03-14 19:41:58,150 INFO sqlalchemy.engine.Engine SELECT [AddressType].address_type_code AS [AddressType_address_type_code], [AddressType].name AS [AddressType_name] 
FROM [AddressType] 
WHERE [AddressType].address_type_code IN (?, ?)
2023-03-14 19:41:58,150 INFO sqlalchemy.engine.Engine [generated in 0.00050s] ('ac1', 'ac2')
<__main__.AddressType object at 0x7fd6d221e050>
<__main__.AddressType object at 0x7fd6d221e050>
<__main__.AddressType object at 0x7fd6d221de10>
<__main__.AddressType object at 0x7fd6d221de10>

```

The results are not NULL and the table names are matched correctly.

If the **actual tables are not named with this same casing using quotes (e.g. there are no brackets)**, then of course, you don't want to indicate a [case sensitive name](https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Table.params.name) , and you want to name your tables / columns using **all lower case names to indicate case insensitive**.

**Comment by jordantshaw** [comment]
@zzzeek  thank you for the feedback.  I understand what you are saying.  So out of curiosity then, why does the test case work if we remove the "selectinload" function from the query, and just use lazy loading instead?

**Comment by zzzeek** [comment]
lazyloading is using a query that is explicitly for a single parent primary key value, so all the results it gets back are applied to the collection.  the selectinloader receives result rows that are for many primary key values, so it has to cross-reference them using a dictionary.  this is where in Python the dictionary doesn't match those values.

there might be a place where selectinloader could detect PK values that were not consumed and warn, however, this assumes that all selectinload cases always expect to have all possible parents locally available.

**Comment by jordantshaw** [comment]
> but how selectinload works is not the important part here, if you are not normalizing that PK value you will be open to other much more subtle issues by potentially having multiple copies of the same primary key identity in the identity map at one time.

Thank you for clarifying.  I understand what you are saying.  Obviously the ideal solution is to have consistent values within the database itself.  But if input cannot be enforced then the next best option would be to normalize them through SA.  Thank you for your help!
