### ISSUE TITLE
python-vertica connection issue with 2.0 version

### ISSUE THREAD

**Issue by anilmcmt** [sqlalchemy/sqlalchemy#9495]
### Describe the bug

When I try to connect with latest version of  sqlalchemy we have faced issue, Older version it's fine

import sqlalchemy as sa
engine = sa.create_engine('vertica+vertica_python://***:data***@*********:5433/*****')

conn = engine.connect()

sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'select version()'

### SQLAlchemy Version in Use

2.0.2

### DBAPI (i.e. the database driver)

python_vertica

### Database Vendor and Major Version

Vertica 10.1.0

### Python Version

3.11

### Operating system

Window/Linux

### To Reproduce

```python
import sqlalchemy as sa


# create engine
engine = sa.create_engine('vertica+vertica_python://***:data***@*********:5433/*****')
conn = engine.connect()
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
```

**Comment by CaselIT** [comment]
Hi,

The vertica driver is not maintained by sqlalchemy, you should report it to their devepolers
