### ISSUE TITLE
Values expression (kinda) for sqlite

### ISSUE THREAD

**Issue by MeRuslan** [sqlalchemy/sqlalchemy#9497]
### Describe the use case

sqlalchemy values are sometimes super useful
``` python
value_expr = values(
    column('id', Integer),
    column('name', String),
    name="my_values"
).data(
    [(1, 'name1'), (2, 'name2'), (3, 'name3')]
)
```
but those kinds of values are not supported by sqlite, however
``` sql
with cte(id) as 
  (values (1),(2),(3),(4),(5))
select * from cte;
```
that is

Seems like Values we have in sqlalchemy now can't act like these accepted by sqlite, e.g. `(values (1),(2),(3),(4),(5))`.
I tried covering them into `select(values).cte()` but that obviously did not change values themselves.

Would it it take a lot to implement (maybe downgrade what we have now?) values compatible with sqlite as well?

### Databases / Backends / Drivers targeted

sqlite

### Example Use

Probably something like that
``` python
values_data(
    [(1, 'name1'), (2, 'name2'), (3, 'name3')]
)
```
or rather: 
``` python
value_expr = values(
    column('id', Integer),
    column('name', String),
    name="my_values"
).data(
    [(1, 'name1'), (2, 'name2'), (3, 'name3')]
).as_cte()
```

**Comment by zzzeek** [comment]
there is #7228 for this, which discusses two ways of doing it, there is an old patch in review that wasn't really finished so overall the feature needs someone to pick it up.

**Comment by zzzeek** [comment]
see #7228
