### ISSUE TITLE
Python postgres `Range` impl missed `intersection` method

### ISSUE THREAD

**Issue by uriyyo** [sqlalchemy/sqlalchemy#9509]
### Describe the use case

Python postgres `Range` impl missed `intersection` method:

```sql
SELECT '[1, 10]'::int4range * '[5, 15]'::int4range  -- [5, 11)
```

### Databases / Backends / Drivers targeted

postgresql

### Example Use

```py
a = Range(1, 10)
b = Range(5, 15)

c = a * b
```

**Comment by sqla-tester** [comment]
**Yurii Karabas** has proposed a fix for this issue in the **main** branch:

**Add intersection method to Range class** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4523
