### ISSUE TITLE
scalar_one function on Session

### ISSUE THREAD

**Issue by erik1994nl** [sqlalchemy/sqlalchemy#9517]
### Describe the use case

When I try to retrieve a single which I want to either retrieve or get an exception when it's not there.
The current solution I have is to use `my_session.scalars(stmt).one()` on my `Session`.
I would like to be able to do `my_session.scalar_one(stmt)` as an alternative.
This would need to either provide the Python scalar value OR throw an exception if no value is found.

### Databases / Backends / Drivers targeted

PostgreSQL.

### Example Use

```
stmt = select(...).where(...)
with get_session() as my_session:
    my_session.scalar_one(stmt)
```

**Comment by zzzeek** [comment]
or session.scalars(stmt).one().  that's really what should be used here.

**Comment by zzzeek** [comment]
this is not a "use case" because the use case is already provided
