### ISSUE TITLE
nested_sets example 

### ISSUE THREAD

**Issue by svafn** [sqlalchemy/sqlalchemy#9520]
### Describe the bug

https://github.com/sqlalchemy/sqlalchemy/blob/main/examples/nested_sets/nested_sets.py

row 55:

          personnel.update(personnel.c.rgt >= right_most_sibling).values(
TypeError: TableClause.update() takes 1 positional argument but 2 were given

Maybe right :
         
        personnel.update().where(personnel.c.rgt >= right_most_sibling).values(
                  

### SQLAlchemy Version in Use

2.0.7

### DBAPI (i.e. the database driver)

pysqlite

### Database Vendor and Major Version

SQLite

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
connection.execute(
            personnel.update(personnel.c.rgt >= right_most_sibling).values(
                lft=case(
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
``` 

### Additional context

Maybe right :
       
        personnel.update().where(personnel.c.rgt >= right_most_sibling).values(

**Comment by zzzeek** [comment]
thanks for reporting!
