### ISSUE TITLE
engine parameter server_side_cursor is not coerced for postgresql dialect

### ISSUE THREAD

**Issue by mdobrzanski** [sqlalchemy/sqlalchemy#9534]
### Describe the bug

Engine created with `engine_from_config` does not convert string value to boolean. 

If I get it right, I think [PGDialect.engine_config_types](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L718) should contain `"server_side_cursors": util.asbool` as well.

Please, see example in "To Reproduce" and patch in "Additional context"

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#server-side-cursors

### SQLAlchemy Version in Use

1.4

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 

### Python Version

3.8

### Operating system

Linux

### To Reproduce

```python
from sqlalchemy import engine_from_config


e = engine_from_config(
    {
        'sqlalchemy.url': 'postgresql://chinook:p4ssw0rd@127.0.0.1/Chinook',
        'sqlalchemy.echo': 'true',
        'sqlalchemy.server_side_cursors': 'false'
    }
)
print('echo:', e.echo)  # this is fine
print('server_side_cursors:', e.dialect.server_side_cursors)  # expected False
```

output
``` 
echo: True
server_side_cursors: True
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
``` 

### Additional context

```
from sqlalchemy import engine_from_config
from sqlalchemy import util
from sqlalchemy.dialects.postgresql.psycopg2 import PGDialect_psycopg2

#### patch
PGDialect_psycopg2.engine_config_types = PGDialect_psycopg2.engine_config_types.union(
    {"server_side_cursors": util.asbool}
)
#####

e = engine_from_config(
    {
        'sqlalchemy.url': 'postgresql://chinook:p4ssw0rd@127.0.0.1/Chinook',
        'sqlalchemy.echo': 'true',
        'sqlalchemy.server_side_cursors': 'false'
    }
)
print('patched')
print('echo:', e.echo)  # still ok
print('server_side_cursors:', e.dialect.server_side_cursors)  # now is ok
```
output
```
patched
echo: True
server_side_cursors: False
```

**Comment by zzzeek** [comment]
hi - 

you're not wrong but [server_side_cursors as a dialect-level setting is deprecated](https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#server-side-cursors), since it is not generally an efficient way to operate and I wouldn't want someone turning that on in a config file either as it has behavioral implications that require code changes if turned on across the board.    server side cursor use should be done on a per-statement basis for those statements where it is advantageous.
