### ISSUE TITLE
.ilike() ColumnOperator adds % characters with psycopg

### ISSUE THREAD

**Issue by waderoberts123** [sqlalchemy/sqlalchemy#9540]
### Describe the bug

When I use the `.ilike()` ColumnOperator I am getting extra % characters in the query.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Column.ilike

### SQLAlchemy Version in Use

2.0.7

### DBAPI (i.e. the database driver)

psycopg (async)

### Database Vendor and Major Version

PostgreSQL

### Python Version

3.8

### Operating system

Linux and Windows

### To Reproduce

```python
>>> stmt = sa.select(public.Address.street).where(public.Address.street.ilike(f"%asdf%"))
>>> print(stmt.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True}))
SELECT addresses.street 
FROM addresses 
WHERE addresses.street ILIKE '%%asdf%%'
```

### Error

No error, but it seems like this should not be adding the characters unless a user wants them.

**Comment by waderoberts123** [comment]
Wait, now I can see that when I remove the % characters from the query, then they don't get inserted. I think this is not actually a bug, my apologies!

```python
>>> stmt = sa.select(public.Address).where(public.Address.street.ilike(f"asdf"))
>>> print(stmt.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True}))
SELECT addresses.addressesid, addresses.created_at, addresses.touched_txid, addresses.updated, addresses.updated_by, addresses.created_by, addresses.active, addresses.street, addresses.city, addresses.state, addresses.zipcode, addresses.num_type, addresses.num_1, addresses.num_2, addresses.street_1, addresses.street_2, addresses.unit_type, addresses.unit_num, addresses.orig_street_1, addresses.orig_street_2, addresses.expanded_street_1, addresses.expanded_street_2, addresses.parser_error, addresses.owner_agenciesid, addresses.convertedid, addresses.address_groupsid, addresses.latitude, addresses.longitude, addresses.verification_override, addresses.cad_map_layers_polygonsids, addresses.address_verification_typesid, addresses.manually_grouped_addressesid, addresses.common_addressesid 
FROM addresses 
WHERE addresses.street ILIKE 'asdf'
```

**Comment by CaselIT** [comment]
Hi,

That's expected, since % chars need to be escaped when using psycopg
