### ISSUE TITLE
mysql.CHAR(0) is created as CHAR(1)

### ISSUE THREAD

**Issue by bdraco** [sqlalchemy/sqlalchemy#9544]
### Describe the bug

When creating schema with `mysql.CHAR(0)` it gets rendering to the datatbase as `CHAR(1)`

https://dev.mysql.com/doc/refman/8.0/en/string-type-syntax.html
> MySQL permits you to create a column of type CHAR(0). This is useful primarily when you must be compliant with old applications that depend on the existence of a column but that do not actually use its value. CHAR(0) is also quite nice when you need a column that can take only two values: A column that is defined as CHAR(0) NULL occupies only one bit and can take only the values NULL and  (the empty string).

### SQLAlchemy Version in Use

2.0.6

### DBAPI (i.e. the database driver)

mysqlclient

### Database Vendor and Major Version

Mysql 8

### Python Version

3.10

### Operating system

linux

### To Reproduce

```python
`SPEC = CHAR(1).with_variant(mysql.CHAR(0), "mysql", "mariadb")`
```

### Error

N/A

**Comment by sqla-tester** [comment]
**J. Nick Koston** has proposed a fix for this issue in the **main** branch:

**Fix creating zero length char with MySQL dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4528

**Comment by sqla-tester** [comment]
**J. Nick Koston** has proposed a fix for this issue in the **main** branch:

**Fix creating zero length char with MySQL dialect** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4528
