### ISSUE TITLE
batch update

### ISSUE THREAD

**Issue by q1165600785** [sqlalchemy/sqlalchemy#9547]
### Describe the bug

why in session   batch update  can  find  primary  key  but in engine connect  not find primary key   it  cause  batch  update  error   why is situation happen  

### SQLAlchemy Version in Use

2.07

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

mysql8

### Python Version

3.8

### Operating system

Windows

### To Reproduce

```python
dute key  error
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
```dute key  error

### Additional context

_No response_

**Comment by zzzeek** [comment]
hi -

please [post a discussion](https://github.com/sqlalchemy/sqlalchemy/discussions) for questions and please provide code examples of what you are doing and what is not working.  Look at examples under the [great mcve](https://github.com/sqlalchemy/sqlalchemy/issues?q=label%3A%22great+mcve%22+) tag for the kinds of code examples we can work with.  thanks!
