### ISSUE TITLE
Column named 'row_number' gives error in MariaDB 10.11

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9588]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9585

<div type='discussions-op-text'>

<sup>Originally posted by **BackSeat** April  1, 2023</sup>
This does not produce an error with MariaDB 10.5; it does with 10.11:

```
CREATE DATABASE test;

USE test;

CREATE TABLE `kae` (
    `id` int(11) NOT NULL,
    `row_number` int(11) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `kae` (`id`, `row_number`) VALUES (1, 0);

UPDATE kae SET row_number=12 WHERE id=1;

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual
that corresponds to your MariaDB server version for the right syntax to
use near 'row_number=12 WHERE id=1' at line 1
```

I believe SQLAlchemy should wrap the column name in backticks (I actually believe this is  regression from MariaDB 10.5 → 10.11, but 'row_number' is a function name in MariaDB).</div>

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Added ``row_number`` as reserved word in MariaDb.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4542
