### ISSUE TITLE
Oracle ignores function column when reflecting indexes, including sorted cols

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9597]
Indexes like
```py
Index("foo_idx", desc(column("x")))
```
reflect as no columns, since the columns that's reflected is a "system pseudocolumn" `sync_nc` that's ignored.

Fixing this does not seem too had, since we now support expression index reflection and we can use `ALL_IND_EXPRESSIONS` to reflect these

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Improve oracle index reflection** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4584
