### ISSUE TITLE
Typo in PG DOMAIN docs

### ISSUE THREAD

**Issue by jenstroeger** [sqlalchemy/sqlalchemy#9599]
### Describe the bug

I think the examples here

https://github.com/sqlalchemy/sqlalchemy/blob/e79ab08165e01dc7af50fcffadb31468ace51b6c/lib/sqlalchemy/dialects/postgresql/named_types.py#L377-L385

should actually be `DOMAIN()` instead of `Domain()`?

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#sqlalchemy.dialects.postgresql.DOMAIN

### SQLAlchemy Version in Use

2.0.8

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.10

### Operating system

macOS

### To Reproduce

```python
n/a
```

### Error

n/a

**Comment by zzzeek** [comment]
absolutely

**Comment by jenstroeger** [comment]
Thanks @zzzeek, mind a PR?

**Comment by zzzeek** [comment]
we have a tag "PRs welcome" that I added above, you can always use that as an indicator

**Comment by CaselIT** [comment]
the pr did not have `Fixes #9599` so closing manually
