### ISSUE TITLE
cross-platform MERGE that leverages existing ON CONFLICT, etc. clauses within dialects

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/sqlalchemy#960]
**Migrated issue, originally created by jek ([@jek](https://github.com/jek))**

Implement generic MERGE, aka 'upsert'.  In ANSI, it looks like:

    MERGE INTO table_name1 USING table_name2 ON (condition)
    WHEN MATCHED THEN UPDATE SET column1 = value1 [column2 = value2 ...](,)
    WHEN NOT MATCHED THEN INSERT columns VALUES (values) 

Dialect support differs pretty widely.  A quick & likely inaccurate poll:

 - Oracle 9+ has a MERGE
 - t-sql 2008 has a MERGE, earlier can maybe do `IF EXISTS(SELECT ...)`
 - MySQL is limited to a key violation condition, and can do either `INSERT ... ON DUPLICATE KEY UPDATE` or `REPLACE INTO`, INSERT being preferable
 - SQLite is limited to a key violation condition, and has `INSERT .. ON CONFLICT REPLACE`

**Comment by zzzeek** [comment]
I think in most cases people are going to use the DB-specific "on conflict" types of operators, because they are already so DB specific.  I don't have an interest in the cross-platform MERGE construct, if a truly motivated volunteer wants to implement fully with tests we can reopen.

**Comment by dwt** [comment]
I've noticed that sqlite now also supports upset clauses: https://www.sqlite.org/lang_UPSERT.html

Where would be the right place to track an additional method on the sqlite dialect to generate these?

**Comment by dwt** [comment]
https://github.com/sqlalchemy/sqlalchemy/issues/4010 found it.

**Comment by zzzeek** [comment]
there's a WIP for that as well: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2230
