### ISSUE TITLE
Proposal: Add support for asyncpg adapter unique name generator

### ISSUE THREAD

**Issue by teror4uks** [sqlalchemy/sqlalchemy#9608]
### Describe the use case

The issue: https://github.com/sqlalchemy/sqlalchemy/issues/6467 describes the problem with unique naming prepared statements on asyncpg side when using pg bouncer. 

To avoid this the asyncpg added an optional name parameter to provide a custom name for prepared statements https://github.com/MagicStack/asyncpg/pull/846. 

I suggest populating an optional custom function to generate unique names for prepared statements in Asyncpg Adapter

### Databases / Backends / Drivers targeted

Postgresql, asyncpg

### Example Use

```python
from uuid import uuid4

engine = create_async_engine(...,     
    connect_args={
        'prepared_statement_name_func': lambda:  f'__asyncpg_{uuid4()}__',
    },
)
```

**Comment by sqla-tester** [comment]
**Pavel Sirotkin** has proposed a fix for this issue in the **main** branch:

**Add name_func optional attribute for asyncpg adapter** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4565
