### ISSUE TITLE
PostgreSQL regexp_match operator precedence should be equal to concat

### ISSUE THREAD

**Issue by RazerM** [sqlalchemy/sqlalchemy#9610]
### Describe the bug

SQLAlchemy's `regexp_match` precedence is lower than `concat`.

### SQLAlchemy Version in Use

1.4.47

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 14

### Python Version

3.10.6

### Operating system

macOS

### To Reproduce

```python
from sqlalchemy import (
    Column,
    Integer,
    MetaData,
    Table,
    Text,
    create_engine,
    insert,
    select,
)

# Uncomment to "fix"
# from sqlalchemy.sql.operators import _PRECEDENCE, concat_op, regexp_match_op
# _PRECEDENCE[regexp_match_op] = _PRECEDENCE[concat_op]

meta = MetaData()

foo = Table(
    'foo',
    meta,
    Column('id', Integer, primary_key=True),
    Column('name', Text),
)

engine = create_engine('postgresql:///precedenceissue', future=True, echo=True)

with engine.begin() as conn:
    meta.create_all(bind=conn)
    conn.execute(insert(foo).values(name='Alice'))

    stmt = select(foo.c.name.regexp_match(foo.c.name + '$'))
    result = conn.scalar(stmt)
    print(f'\nGot {result!r}, expected True\n')

    conn.rollback()
```

### Error

Output of above script

```
2023-04-06 19:06:59,675 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2023-04-06 19:06:59,677 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-06 19:06:59,678 INFO sqlalchemy.engine.Engine select current_schema()
2023-04-06 19:06:59,678 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-06 19:06:59,679 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2023-04-06 19:06:59,680 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-06 19:06:59,681 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-06 19:06:59,682 INFO sqlalchemy.engine.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2023-04-06 19:06:59,682 INFO sqlalchemy.engine.Engine [generated in 0.00036s] {'name': 'foo'}
2023-04-06 19:06:59,686 INFO sqlalchemy.engine.Engine 
CREATE TABLE foo (
	id SERIAL NOT NULL, 
	name TEXT, 
	PRIMARY KEY (id)
)


2023-04-06 19:06:59,686 INFO sqlalchemy.engine.Engine [no key 0.00017s] {}
2023-04-06 19:06:59,703 INFO sqlalchemy.engine.Engine INSERT INTO foo (name) VALUES (%(name)s) RETURNING foo.id
2023-04-06 19:06:59,703 INFO sqlalchemy.engine.Engine [generated in 0.00027s] {'name': 'Alice'}
2023-04-06 19:06:59,879 INFO sqlalchemy.engine.Engine SELECT foo.name ~ foo.name || %(name_1)s AS anon_1 
FROM foo
2023-04-06 19:06:59,879 INFO sqlalchemy.engine.Engine [generated in 0.00024s] {'name_1': '$'}

Got 'true$', expected True

2023-04-06 19:06:59,880 INFO sqlalchemy.engine.Engine ROLLBACK
```

### Additional context

I'm aware of the `.self_group()` workaround.

Current precedence values:

https://github.com/sqlalchemy/sqlalchemy/blob/1aef8e75a69319469d3b447422b8cdee2a1cf894/lib/sqlalchemy/sql/operators.py#L1660

https://github.com/sqlalchemy/sqlalchemy/blob/1aef8e75a69319469d3b447422b8cdee2a1cf894/lib/sqlalchemy/sql/operators.py#L1664

PostgreSQL docs indicate that `||` and `~` are the same precedence, but SQLAlchemy has `~` lumped in with `LIKE` etc.:

Operator/Element | Associativity | Description
-- | -- | --
. | left | table/column name separator
:: | left | PostgreSQL-style typecast
[ ] | left | array element selection
\+ - | right | unary plus, unary minus
^ | left | exponentiation
\* / % | left | multiplication, division, modulo
\+ - | left | addition, subtraction
(any other operator) | left | all other native and user-defined operators
BETWEEN IN LIKE ILIKE SIMILAR |   | range containment, set membership, string matching
< > = <= >= <> |   | comparison operators
IS ISNULL NOTNULL |   | IS TRUE, IS FALSE, IS NULL, IS DISTINCT FROM, etc.
NOT | right | logical negation
AND | left | logical conjunction
OR | left | logical disjunction

Source: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-PRECEDENCE-TABLE

For additional context I've read through other precedence issues but those seemed to be around things like type coercion whereas this seems (?) relatively straightforward barring any other compatibility issues this would cause.

**Comment by zzzeek** [comment]
needed:

1. confirm this is the same in 2.0, we are not really doing many 1.4 releases right now and there is a workaround in any case, not clear if this is worth backporting
2. other backends for match, are we using operators for any of those or are they generally using SQL functions, in which case it's safe to tinker with PG
3. we would need some backend agnostic tests added to https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/testing/suite/test_select.py#L1488 which is where we have the current regexp_match.

if you can send a PR that adds tests to that suite we can confirm immediately if the change has any negative implications for other backends.

**Comment by shreyanshgautam24** [comment]
Uploading SampleVideo_1280x720_1mb.mp4…

**Comment by rajat315315** [comment]
Added a few test cases but postgres one surely fails.. @zzzeek

**Comment by sqla-tester** [comment]
**Rajat Jain** has proposed a fix for this issue in the **main** branch:

**Added test cases to check precedence of regexp and concat operators.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4790

**Comment by zzzeek** [comment]
correct me if I'm wrong but this appears like **all** the match ops should be equal to concat for this to work, match_op, not_match_op, not_regex_match_op, then what about the LIKE operators?


test:

```py
from sqlalchemy import column, String


c = column('x', String)
q = column('q', String)

for exp in [
    c.regexp_match(q + 'y'),
    c.like(q + 'y'),
    ~c.regexp_match(q + 'y'),
    ~c.match(q + 'y'),
    c.match(q + 'y'),

]:
    print(exp)
```

current output:

```
x <regexp> q || :q_1
x LIKE q || :q_1
x <not regexp> q || :q_1
NOT x MATCH q || :q_1
x MATCH q || :q_1

```

apply change:

```diff
diff --git a/lib/sqlalchemy/sql/operators.py b/lib/sqlalchemy/sql/operators.py
index dbd593e9fb..0df5a66846 100644
--- a/lib/sqlalchemy/sql/operators.py
+++ b/lib/sqlalchemy/sql/operators.py
@@ -2533,7 +2533,7 @@ _PRECEDENCE: Dict[OperatorType, int] = {
     bitwise_and_op: 7,
     bitwise_lshift_op: 7,
     bitwise_rshift_op: 7,
-    concat_op: 6,
+    concat_op: 5,
     filter_op: 6,
     match_op: 5,
     not_match_op: 5,

```

output:

```
x <regexp> (q || :q_1)
x LIKE (q || :q_1)
x <not regexp> (q || :q_1)
NOT x MATCH (q || :q_1)
x MATCH (q || :q_1)

```

seems good to me right?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**adjust concat precedence to match that of string comparison** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4816
