### ISSUE TITLE
postgresql ENUM auto-chooses the name from the given Enum, so "name" needs to be optional

### ISSUE THREAD

**Issue by al-dpopowich** [sqlalchemy/sqlalchemy#9611]
### Describe the bug

Prior to 2.0, I could create a postgresql enum column with:

```
from sqlalchemy.dialects.postgresql import ENUM
...
Column('colname', ENUM(MyEnum))

```

This now generates an exception:

`TypeError: __init__() missing 1 required keyword-only argument: 'name'`

Yet, this is not documented in the 2.0 upgrade changes, nor is the keyword arg discussed in any detail in the API documentation, though it is used in examples.

The docs say:

> Arguments are the same as that of [Enum](https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Enum), but also including the following parameters.

In fact, for the stock `Enum` type, `name` is not required.

Why is `name` required?  What is it used for?

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#sqlalchemy.dialects.postgresql.ENUM

### SQLAlchemy Version in Use

2.0.9

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

PostgreSQL 14.2

### Python Version

3.9.13

### Operating system

Linux

### To Reproduce

```python
import enum

from sqlalchemy import Enum
from sqlalchemy.dialects.postgresql import ENUM

class MyEnum(enum.Enum):
   ONE = 1
   TWO = 2

# stock Enum is fine
Enum(MyEnum)
print('Using non-dialect version without `name` works fine')

# Using PG dialect throws an exception
try:
   ENUM(MyEnum)
except TypeError as exc:
   print(f'PG ENUM without name threw exception: {exc}')

# with name, it's OK
ENUM(MyEnum, name='myname')
print('Using PG ENUM with `name` works')
```

### Error

`
TypeError: __init__() missing 1 required keyword-only argument: 'name'
`

### Additional context

Without understanding why `name` is required, it's just a tedious annotation repeating the first argument to `Column`.

**Comment by zzzeek** [comment]
that was an unplanned regression, please create the ENUM as:

    ENUM(MyEnum, name=MyEnum.__name__)

**Comment by al-dpopowich** [comment]
Thanks for the quick response.  I had already figured out what is wanted for `name` (by trial and error) and started to do, essentially, your suggestion.  That works for now.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**fix pg ENUM issues** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4557
