### ISSUE TITLE
document how to use pools w/ dialect features w/o the actual engine

### ISSUE THREAD

**Issue by drum445** [sqlalchemy/sqlalchemy#9613]
### Describe the bug

When creating a QueuePool and using pre_ping, requiring a dialect to be passed, the dialect will not be initialised correctly which causes an unexpected Exception to be thrown when the pre_ping cannot connect to the DB (due to the mysql server being shutdown)

This can be fixed by manually initialising the dbapi against the dilect and then supplying that to the pool as shown in the reproduce code below

This does seem like a bug and something that shouldn't have to be dealt with by the invoker, as the documentation doesn't state this has to be done.

Many Thanks

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

[Docs](https://docs.sqlalchemy.org/en/20/core/pooling.html#sqlalchemy.pool.Pool.__init__)

### SQLAlchemy Version in Use

SQLAlchemy==2.0.9

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

MariaDB 11.1.0

### Python Version

3.11.2 & 3.10

### Operating system

Linux, Windows and macOS

### To Reproduce

```python
import pymysql
import pymysql.cursors
import sqlalchemy.pool as pool
from sqlalchemy.dialects import mysql

def create_new_connection():
    con = pymysql.connect(
        host="localhost",
        user="root",
        passwd="password",
        db="test",
        cursorclass=pymysql.cursors.DictCursor
    )

    return con


# This will throw an unexpecter error
mypool = pool.QueuePool(create_new_connection, max_overflow=5, pool_size=5, pre_ping=True, dialect=mysql.pymysql.dialect())

# This will throw the correct error after trying to pre_ping
# mydialect = mysql.pymysql.dialect()
# mydialect.dbapi = mysql.pymysql.dialect.import_dbapi()
# mypool = pool.QueuePool(create_new_connection, max_overflow=5, pool_size=5, pre_ping=True, dialect=mydialect)

if __name__ == "__main__":

    # to rep
    import time;

    con = mypool.connect()
    con.close()

    # Manually stop the sql service
    print("Stop the mysql service now")
    time.sleep(5)

    con = mypool.connect()
```

### Error

```
  File "C:\Users\e\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py", line 1370, in _checkout
    with util.safe_reraise():
  File "C:\Users\e\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\e\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\pool\base.py", line 1308, in _checkout
    result = pool._dialect._do_ping_w_event(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 675, in _do_ping_w_event
    except self.loaded_dbapi.Error as err:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1138, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\e\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 387, in loaded_dbapi
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Dialect <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x000001CE5466AC10> does not have a Python DBAPI established and cannot be used for actual database interaction
```

**Comment by CaselIT** [comment]
Hi,

I think this is the expected behaviour. A pool should be used by an engine, not directly by user code.
The engine does a series of things to initialize the dbapi and select the proper implementation that are outside of the scope of a pool

**Comment by drum445** [comment]
@CaselIT cool thank you, do you think my code is correct then for using the pool?

The use-case is I have a project that has a very large amount of raw SQL stmts that interact with mysql simply using the pymysql driver, but I want to add pooling to it and using the one supplied by SQLAlchemy seemed like the best solution. Do you know of a different way of achieving this if it feels like I am misusing the SQLAlchemy pool?

**Comment by zzzeek** [comment]
you are passing the dialect so it seems like this should work, let me see where it's going wrong

**Comment by zzzeek** [comment]
oh, beacuse it didnt load the DBAPI and if you do that manually , it works.  so sure.  

all at once looks like this:


```py
mypool = pool.QueuePool(
    create_new_connection,
    max_overflow=5,
    pool_size=5,
    pre_ping=True,
    dialect=mysql.pymysql.dialect(dbapi=mysql.pymysql.dialect.import_dbapi()),
)
```

id rather not make API changes right now so perhaps we just document that in a sidebar for "pre_ping"

**Comment by zzzeek** [comment]
we can add an error code to the message here and even point to it at errors.rst

**Comment by zzzeek** [comment]
of course, the easiest way to get what you want here is, if I may use a word I try not to overuse, simply:

```py
e = create_engine("mysql+pymysql://user:pass@host/db")

pool = e.pool

```

tada

**Comment by drum445** [comment]
Thanks @zzzeek, passing into the constructor also works

With the create_engine usage the reason I couldn't use this is because you cannot pass through things such as `cursorclass=pymysql.cursors.DictCursor` to create_engine can you?

**Comment by CaselIT** [comment]
I think so, you can use `connect_args`: https://docs.sqlalchemy.org/en/20/core/engines.html#use-the-connect-args-dictionary-parameter

**Comment by drum445** [comment]
Cheers, but now it crashes with the following, which I think is the reason I went for hitting the QueuePool directly

```
File "C:\Users\e\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 478, in
                                                                                                                       n initialize
    self.server_version_info = self._get_server_version_info(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\mysql\base.py", line 25
                                                                                                                       538, in _get_server_version_info
    val = cursor.fetchone()[0]
          ~~~~~~~~~~~~~~~~~^^^
```

**Comment by zzzeek** [comment]
> Thanks @zzzeek, passing into the constructor also works
> 
> With the create_engine usage the reason I couldn't use this is because you cannot pass through things such as `cursorclass=pymysql.cursors.DictCursor` to create_engine can you?

as @CaselIT  mentioned the connect_args will give you this, you can also pass the "creator" to create_engine, etc.

**Comment by drum445** [comment]
@zzzeek thanks, any ideas how to prevent the _get_server_version_info crashing?

**Comment by zzzeek** [comment]
well that's their dictcursor class getting in the way.    they'd have to supply a subclass of the dialect, or any object that extends [_ConnDialect](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/pool/base.py#L110) and includes their own ping method.

**Comment by zzzeek** [comment]
or a DictCursor class that still allows numeric indexed access

**Comment by drum445** [comment]
I'll stick to accessing QueuePool correctly for now I think, as that seems to work fine.

Thanks both for your input

**Comment by zzzeek** [comment]
oh right, the engine adds a creator that does a lot more stuff.  good point.  let's leave that out then

**Comment by zzzeek** [comment]
OK I'm not liking this API and I dont see why I'd want to document it when I dont think this is the best way to do this.

create_engine() is our front end for this.   I just remembered there's a way to turn off the initializers.  that part is "private" but not a big deal to turn into a public use case

this demo works, using the engine and not accessing into the pool

```py
import pymysql.cursors
from sqlalchemy import create_engine

e = create_engine(
    "mysql+pymysql://scott:tiger@localhost/test",
    connect_args={"cursorclass": pymysql.cursors.DictCursor},
    _initialize=False,
)

if __name__ == "__main__":

    # to rep
    import time

    con = e.raw_connection()
    cursor = con.cursor()
    cursor.execute("select 1 as x")
    print(cursor.fetchone()['x'])
    cursor.close()

    con.close()

    # Manually stop the sql service
    print("Stop the mysql service now")
    time.sleep(5)

    con = e.raw_connection()

```

**Comment by drum445** [comment]
@zzzeek that looks like the missing piece, thanks. I do agree with you though, if this isn't a recommended way to access pooling then it may be best not to have it documented.

I'll give create_engine with the _initialize arg passed a few tests, along with pool_pre_ping which is the reason for this ticket originally and see how they go

Cheers!

**Comment by CaselIT** [comment]
> OK I'm not liking this API and I dont see why I'd want to document it when I dont think this is the best way to do this.
> 
> create_engine() is our front end for this. I just remembered there's a way to turn off the initializers. that part is "private" but not a big deal to turn into a public use case
> 
> this demo works, using the engine and not accessing into the pool
> 
> ```python
> import pymysql.cursors
> from sqlalchemy import create_engine
> 
> e = create_engine(
>     "mysql+pymysql://scott:tiger@localhost/test",
>     connect_args={"cursorclass": pymysql.cursors.DictCursor},
>     _initialize=False,
> )
> 
> if __name__ == "__main__":
> 
>     # to rep
>     import time
> 
>     con = e.raw_connection()
>     cursor = con.cursor()
>     cursor.execute("select 1 as x")
>     print(cursor.fetchone()['x'])
>     cursor.close()
> 
>     con.close()
> 
>     # Manually stop the sql service
>     print("Stop the mysql service now")
>     time.sleep(5)
> 
>     con = e.raw_connection()
> ```

shall I make `_initialize` public? maybe as `initialize_dialect`?

**Comment by zzzeek** [comment]
it seems not clean to do it that way because now you have an engine that's broken unless you use only the .pool attribute

more like something like "create_pool_from_url()" or something

**Comment by CaselIT** [comment]
Ok. So the function could create an engine with initialize=False then return just the pool and discard the engine?
Or do you want to do something a bit more optimized?

**Comment by zzzeek** [comment]
I think 99% of what create_engine does you would need for this anyway, so there's no need to change it.  we can always pass another parameter _pool_only=True if we want to further qualify behaviors within the `create()` function.

**Comment by CaselIT** [comment]
the create_pool function should be in engine/create or in a new module pool/create?

I'm thinking pool/create would be better but it will create issue with circular imports, since pool create depends on create engine.

I'm going with engine/create

**Comment by zzzeek** [comment]
yes just leave it in engine, this is like, a nobody will use it kind of feature sorry poster
