### ISSUE TITLE
Example based on docs generates Mypy error when assigning None to an Optional column

### ISSUE THREAD

**Issue by mfsjr** [sqlalchemy/sqlalchemy#9617]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Confirm this is not Mypy dataclasses issue 13856

- [X] This is not related to Mypy issue 13856

### Describe the typing issue

Using a pared down example from 2.09 docs, an Optional column is assigned None but gets a Mypy error.  It seems like it should allow None, especially since it is being defaulted to None.

It would seem that explicitly typing it should work, but you get a similar error:
fullname: Mapped[str | None] = mapped_column(default=None)

### To Reproduce

```python
from typing import Optional, Annotated
from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column, DeclarativeBase, MappedAsDataclass

# Paring down an example from the docs...
intpk = Annotated[int, mapped_column(primary_key=True)]
str30 = Annotated[str, mapped_column(String(30))]

class User(MappedAsDataclass, DeclarativeBase):
    __tablename__ = "user_account"
    id: Mapped[intpk] = mapped_column(init=False)
    name: Mapped[str30]
    fullname: Mapped[Optional[str]] = mapped_column(default=None)

user = User(name="Me", fullname="Myself")  # good
user = User(name="Me")  # also good
user = User(name="Me", fullname=None)  # "Mypy: Argument "fullname" to "User" has incompatible type "None"; expected "Union[SQLCoreOperations[Optional[str]], str]" [arg-type]"
```

### Error

```
# Copy the complete text of any errors received by the type checker(s).
``` 
Mypy: Argument "fullname" to "User" has incompatible type "None"; expected "Union[SQLCoreOperations[Optional[str]], str]" [arg-type]

### Versions

- OS:  OSX v11.6.8 
- Python: 3.11
- SQLAlchemy:  2.09
- Type checker (eg: mypy 0.991, pyright 1.1.290, etc):  Mypy 1.2

### Additional context

I'm not totally sure where this sits relative to #6810, but it seems to use api's that are also used in the currently open issue #9587, so hopefully I'm not asking about something being worked on elsewhere.

**Comment by zzzeek** [comment]
this looks like another mypy bug

**Comment by zzzeek** [comment]
this is raised at https://github.com/python/mypy/issues/15020 .  this is another mypy issue unfortunately.
