### ISSUE TITLE
autoincrement=True not applying to non-primary-key column in mysql+pymysql

### ISSUE THREAD

**Issue by BrandonNolet** [sqlalchemy/sqlalchemy#9622]
### Describe the bug

Here's a simplified table definition for my category table:

```python
class Category(Base):
    __tablename__ = "category"

    id: Mapped[UUID] = Column(CHAR(36), primary_key=True, default=hex_uuid)
    ext_id: Mapped[int] = Column(Integer, autoincrement=True, unique=True, default=None)
```

If I create this table via `Base.metadata.create_all(engine)` the AUTO_INCREMENT parameter is not included in the table creation statement. 

I'm obligated to manually run `ALTER TABLE category MODIFY ext_id INT AUTO_INCREMENT` so that the behaviour works as expected.

### SQLAlchemy Version in Use

2.0.9

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

MariaDB 10.11

### Python Version

3.11.2

### Operating system

macOS

### To Reproduce

```python
from sqlalchemy import String, CHAR, Integer
from sqlalchemy.orm import declarative_base, Mapped

def hex_uuid(uuid: str = None):
    return str(uuid4())

Base = declarative_base()

class Category(Base):
    __tablename__ = "category"

    id: Mapped[UUID] = Column(CHAR(36), primary_key=True, default=hex_uuid)
    ext_id: Mapped[int] = Column(Integer, autoincrement=True, unique=True, default=None)

conn_str = 'mysql+pymysql://user:password@localhost/mydatabase'

engine = create_engine(conn_str, echo=True)
Base.metadata.create_all(engine)
```

### Error

2023-04-09 14:15:51,762 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2023-04-09 14:15:51,762 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-09 14:15:51,764 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2023-04-09 14:15:51,764 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-09 14:15:51,766 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2023-04-09 14:15:51,766 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-09 14:15:51,769 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-09 14:15:51,776 INFO sqlalchemy.engine.Engine DESCRIBE `mydatabase`.`category`
2023-04-09 14:15:51,776 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-09 14:15:51,813 INFO sqlalchemy.engine.Engine 
CREATE TABLE category (
        id CHAR(36) NOT NULL, 
        ext_id INTEGER, 
        PRIMARY KEY (id), 
        UNIQUE (ext_id), 
)
2023-04-09 14:15:51,821 INFO sqlalchemy.engine.Engine [no key 0.00011s] {}
2023-04-09 14:15:51,826 INFO sqlalchemy.engine.Engine COMMIT

### Additional context

I know that autoincrement works fine with the primary key, but I do not want to use the primary key as the autoincrement value here.

**Comment by CaselIT** [comment]
Hi,

that's the expected and documented behavior: https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Column.params.autoincrement

> Set up “auto increment” semantics for an integer primary key column with no foreign key dependencies 

I'm not sure if at the moment there is a way of adding auto-increment to a non primary key column. cc @zzzeek

**Comment by zzzeek** [comment]
for MySQL there's not anything built in.     some suggestions are at https://stackoverflow.com/questions/1151314/i-need-to-auto-increment-a-field-in-mysql-that-is-not-primary-key, but in those cases the AUTO_INCREMENT has to be a "UNIQUE KEY" which is also a syntax we don't have direct support for right now.

We can accept a PR for a new feature "mysql_unique_key" and "mysql_unique_key_autoincrement" that packages these up.  Open a new use case issue if there's any interest.
