### ISSUE TITLE
`sqlalchemy.exc.MissingGreenlet` (lazy loading configured to `selectin` on both sides) - does not seem consistent

### ISSUE THREAD

**Issue by Alc-Alc** [sqlalchemy/sqlalchemy#9627]
### Describe the bug

I have a one to one relationship between `A` and `B` but accessing `B` throws an error `sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)`, I've already configured lazy loading to `selectin` on both sides.

Kindly look at "Additional context" for my reasoning on why I believe this to be unexpected.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#preventing-implicit-io-when-using-asyncsession

### SQLAlchemy Version in Use

2.0.9

### DBAPI (i.e. the database driver)

aiosqlite 0.18.0

### Database Vendor and Major Version

SQLite

### Python Version

3.11

### Operating system

OSX

### To Reproduce

```python
import asyncio
from sqlalchemy import ForeignKey, select
from sqlalchemy.orm import Mapped, MappedAsDataclass, DeclarativeBase, mapped_column, relationship, selectinload
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession


class Base(MappedAsDataclass, DeclarativeBase):
    id: Mapped[int] = mapped_column(primary_key=True, init=False)


class A(Base):
    __tablename__ = "a"
    b: Mapped["B"] = relationship(back_populates="a", lazy="selectin", init=False)
    name: Mapped[str] = mapped_column(default="A")


class B(Base):
    __tablename__ = "b"
    a_id: Mapped[int] = mapped_column(ForeignKey(A.id), init=False)
    a: Mapped["A"] = relationship(back_populates="b", uselist=False, lazy="selectin")
    name: Mapped[str] = mapped_column(default="B")


async def main():
    engine = create_async_engine("sqlite+aiosqlite://")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    async with AsyncSession(engine) as session, session.begin():
        a = A()
        b = B(a=a)
        session.add_all((a, b))
    async with AsyncSession(engine) as session:
        # this for loop works standalone
        # uncommenting this will print `A` instances and also fix the issue
        # for i in await session.scalars(select(A).options(selectinload(A.b))):
            # print(i)

        # this for loop does not work standalone
        # uncommenting the previous for loop will make this work
        # why is that?, the previous one works standalone
        for i in await session.scalars(select(B).options(selectinload(B.a))):
            print(i)

asyncio.run(main())
```

### Error

```
  File "/opt/homebrew/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 93, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s)
sys:1: RuntimeWarning: coroutine 'Connection.cursor' was never awaited
``` 

### Additional context

- Uncommenting the following lines makes `select(B).options(selectinload(B.a))` works as expected.

```python
for i in await session.scalars(select(A).options(selectinload(A.b))):
    print(i)
```
- The above query also works standalone, which is why I expect the following to work, but it does not, unless the above query is run.
```python
        for i in await session.scalars(select(B).options(selectinload(B.a))):
            print(i)
```

Disclaimer: I asked this in [gitter](https://app.gitter.im/#/room/#sqlalchemy_community:gitter.im), while I did receive a solution (setting `repr=False`), I consider that a workaround and wanted to either know if this is a bug that needs fixing or a doc update if this is expected. I am leaning towards this being a bug, because printing `A` instances work (without setting `repr=False` on any side), how is `B` any different in a 1 to 1 relationship?

**Comment by Alc-Alc** [comment]
@zzzeek  thanks for the quick reply, why is it that `A` which has reference to `B` works, but `B` which has reference to `A` does not work? In the code I have shown the commented for loop works, why is that?

**Comment by zzzeek** [comment]
> @zzzeek thanks for the quick reply, why is it that `A` which has reference to `B` works, but `B` which has reference to `A` does not work? In the code I have shown the commented for loop works, why is that?

Let's use a [dicsussion](https://github.com/sqlalchemy/sqlalchemy/discussions) next time, but many-to-one lazy loads often do not have to emit any SQL because the "A" object is already present in the identity map.  That is, one A, loads many Bs, each B.a is that same A which we already have by primary key, SQLAlchemy is smart enough to know this.    this is mentioned in https://docs.sqlalchemy.org/en/20/orm/queryguide/relationships.html#lazy-loading and probably some other places too.
