### ISSUE TITLE
greenlet is not pulled as dependency in cases where it should

### ISSUE THREAD

**Issue by trim21** [sqlalchemy/sqlalchemy#9631]
### Describe the bug

This is a opposite issue of previous issue https://github.com/sqlalchemy/sqlalchemy/issues/7024

in short word, `platform_machine` is not a reliable env marker.

`platform_machine` is read from `platform.machine()`, and in windows, it may read from env variable which could be missing when installing, and it will return a empty string.

So greenlet will not be installed in some case

you can try the reproduction script in windows x64 or x86 (with .venv), and you will find `greenlet` is not installed

### SQLAlchemy Version in Use

2.0.9

### DBAPI (i.e. the database driver)

No

### Database Vendor and Major Version

No

### Python Version

3.11

### Operating system

Windows

### To Reproduce

```python
import os
import subprocess

print("python version:")
subprocess.run(
    ['python', '-V'],
    env={"PATH": os.environ.get("PATH")}
)

print("platform_version:")
subprocess.run(
    ['python', '-c', 'import platform;print(platform.machine())'],
    env={"PATH": os.environ.get("PATH")}
)

print("not install sqlalchemy:")
subprocess.run(
    ['./.venv/scripts/pip.exe', 'install', '-e', '.'],
    env={
            key: os.environ.get(key) for key in
            ['PATH', 'ALLUSERSPROFILE', 'VIRTUAL_ENV', 'WINDIR', 'TEMP', 'TMP',
             'APPDATA',
             'USERPROFILE', 'PROGRAMFILES', 'PROGRAMW6432']
        } | {name: value for name, value in os.environ.items() if value.startswith("C:")}
)

output = subprocess.getoutput(r'.\.venv\scripts\pip.exe freeze')

print("pip freeze:")
print(output.splitlines())

print("=====")
print("and you can't find greenlet")
```

### Error

No greenlet installed

**Comment by CaselIT** [comment]
Hi,

I'm not aware of a better alternative to `platform_machine`. If that's not reliable, bugs should be reported to python
Use the asyncio extra if you need to ensure that asyncio dependencies are installed.

**Comment by CaselIT** [comment]
ok, again there are no better alternative I'm aware of

**Comment by trim21** [comment]
> ok, again there are no better alternative I'm aware of

There is, just add `sys_platform == 'win32'`, it's much more common than `platform_machine` in my observation

`platform_machine=='win32' or platform_machine=='WIN32'` => `platform_machine=='win32' or platform_machine=='WIN32' or sys_platform == 'win32'`

**Comment by trim21** [comment]
at least `sys_platform == 'win32'` is safe because it's coverd by current marker `... or (platform_machine=='win32' or platform_machine=='WIN32')` 😄

**Comment by zzzeek** [comment]
What are the conditions under which the bug can be reproduced?

**Comment by trim21** [comment]
> What are the conditions under which the bug can be reproduced?

that depend on how platform.machine is determined, I think it read certain environment variable on windws.

So if you running pip(python) in limit env you may encounter it.

**Comment by zzzeek** [comment]
I dont think the proposed solution is feasible.   Just because sys_platform=='win32' does not mean there is a wheel for the architecture in use at https://pypi.org/project/greenlet/#files , and the build will still fail if you do not have MSVC runtime installed.

Can you please state what platform architecture you have exactly where this test is failing and indicate the wheel file at https://pypi.org/project/greenlet/#files which you expect to be installed without compilation ?

**Comment by trim21** [comment]
> I dont think the proposed solution is feasible. Just because sys_platform=='win32' does not mean there is a wheel for the architecture in use at https://pypi.org/project/greenlet/#files , and the build will still fail if you do not have MSVC runtime installed.
> 
> Can you please state what platform architecture you have exactly where this test is failing and indicate the wheel file at https://pypi.org/project/greenlet/#files which you expect to be installed without compilation ?

You are right, I just realise there is windows ARM, and it's `sys_platform` is `win32` but it's `platform_machine` is `ARM64` 🤔

**Comment by asfaltboy** [comment]
I've got a shiny new M2 Macbook, and greenlet isn't being installed, my architecture is `arm64`.

```python
>>> import platform
>>> platform.machine()
'arm64'
```

I do believe the name of the wheel that satisfies this platform is 'universal2', and is being pre-compiled for greenlet: https://pypi.org/project/greenlet/#copy-hash-modal-20abd92d-b5c6-46bb-a946-72541b267ef2

**Comment by CaselIT** [comment]
it's really annoying that arm on linux reports `aarch64`, while on osx it returned as `arm64`

@asfaltboy if you can confirm that you can install greenlet from wheel (meaning that pip does not start compiling it) feel free to open a PR to add it to this ever growing list of checks
https://github.com/sqlalchemy/sqlalchemy/blob/1e7dcdd6bda3fa49848f5d7f0b82b3145c541b5b/setup.cfg#L40C44-L40C51

**Comment by asfaltboy** [comment]
Thanks @CaselIT for the quick response.

I have confirmed it uses a wheel on my machine:
```sh
pip install -I greenlet
Collecting greenlet
  Downloading greenlet-2.0.2-cp311-cp311-macosx_10_9_universal2.whl (243 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.0/243.0 kB 4.0 MB/s eta 0:00:00
Installing collected packages: greenlet
Successfully installed greenlet-2.0.2
```

I can open a PR to add arm64, but won't this break for windows users?

How about we also limit to `arm64` machiens that use the MacOS system platform `darwin`? I.e: `(platform_machine=='arm64' and sys_platform=='darwin') or ...`

Here are all the values that can be used by pip (according to PEP 496):

```
➜  oss python
Python 3.11.4 (main, Jun 24 2023, 09:00:12) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform, os, sys
>>> platform.machine()
'arm64'
>>> sys.implementation.name
'cpython'
>>> platform.release()
'22.5.0'
>>> sys.platform
'darwin'
>>> os.name
'posix'
>>> platform.python_implementation()
'CPython'
>>>
```

**Side note:** I don't quite understand why we need both this and the asyncio extra (which requires greenlet)? Is there usage of greenlet outside asyncio implementation? And, is this documented as a known limitation, or tech-debt?

**Comment by CaselIT** [comment]
> I can open a PR to add arm64, but won't this break for windows users?

right, I have no clue what will arm windows report in `machine`.. (if we go with the current behaviour my guess is something different again)

> How about we also limit to only arm64 machines that use the MacOS system platform darwin? I.e: (platform_machine=='arm64' and sys_platform=='darwin') or ...

sure this looks sensible

> Side note: I don't quite understand why we need both this and the asyncio extra (which requires greenlet)? Is there usage of greenlet outside asyncio implementation? And, is this documented as a known limitation, or tech-debt?

originally the list was a lot smaller. also having the extra indicates "install all dependencies for asyncio, regardless of constraints"

there are probably better way of doing this, but it seems to be kinda working so not really a priority
