### ISSUE TITLE
investigate ways for loader options in some cases to take place on nested SELECTs, e.g. for union

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9635]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9633

there's no way to get loader criteria on the two SELECTs here because they are not top level.   A new definition of "top level" that accommodates for UNION might be beneficial

```py
from typing import Any

from sqlalchemy import Column, Integer, create_engine, select, event, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, with_loader_criteria

Base: Any = declarative_base()

class SoftDeleted:
    deleted_at = Column(DateTime)

class A(SoftDeleted, Base):
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)

class B(SoftDeleted, Base):
    __tablename__ = "b"
    id = Column(Integer, primary_key=True)


@event.listens_for(Session, "do_orm_execute")
def _add_soft_delete_filtering_criteria(execute_state):
    execute_state.statement = execute_state.statement.options(
        with_loader_criteria(
            SoftDeleted,
            lambda cls: cls.deleted_at.is_(None),
            include_aliases=True,
        )
    )

e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

session = Session(e)

all_items_stmt = select(A.id).union(select(B.id))

session.execute(all_items_stmt).scalars().all()
```

**Comment by zzzeek** [comment]
I think I want to first try to make a rule that if we are a SELECT inside of a top-level CompoundSelect, we should apply options at that level also.   it's a special case here

**Comment by CaselIT** [comment]
what about an insert / update / delete returning there?

**Comment by zzzeek** [comment]
not following

**Comment by CaselIT** [comment]
if we have `insert .. returning union insert returning `

does `with_loader_criteria` work at all with things that aren't selects?

**Comment by zzzeek** [comment]
it...hmmm... doesnt?  it adds WHERE clauses.   so not for an INSERT no

**Comment by CaselIT** [comment]
so does (or should) `with_loader_criteria ` add where clauses to update returning and delete returning ?

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**apply criteria options from top-level core-only statement** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4572

**Comment by zzzeek** [comment]
this wasn't quite what I thought it was at all so the fix is simpler than expected
