### ISSUE TITLE
Optimize Row index lookup by pre-building the row-index dict

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9678]
See details at [9668](https://github.com/sqlalchemy/sqlalchemy/pull/9668)

**Comment by sqla-tester** [comment]
**J. Nick Koston** has proposed a fix for this issue in the **main** branch:

**Prebuild the row string to position lookup for Rows** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4575
