### ISSUE TITLE
Optimize bytes sqltype so that is does not create a processor for engines that return native bytes

### ISSUE THREAD

**Issue by bdraco** [sqlalchemy/sqlalchemy#9680]
### Describe the use case

With Home Assistant we have a lot of binary data in the database.  I noticed that there is no cython row processor for bytes, but for MySQL and SQLite it looks like the data is already in bytes so one is not needed

### Databases / Backends / Drivers targeted

mysql
mariadb
sqlite

### Example Use

n/a

**Comment by zzzeek** [comment]
all drivers have this issue other than psycopg2

**Comment by sqla-tester** [comment]
**J. Nick Koston** has proposed a fix for this issue in the **main** branch:

**disable "bytes" handler for all drivers other than psycopg2** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4577
