### ISSUE TITLE
greenlet dependency not installed on arm64.

### ISSUE THREAD

**Issue by ryan-clancy** [sqlalchemy/sqlalchemy#9687]
### Describe the bug

On M1 Macs, the `greenlet` dependency is not installed because `arm64` is not is in `setup.cfg`.  

When using build tools in CI pipelines that validate generated requirements lock files are equal, the requirement lock files generated on `arm64` (from a local laptop) and `x84_64` (from CI pipelines) differ and tests fail.

When lock files are generated from `arm64` machines, tests fail in CI pipelines. When lock files are generated from `x86_64` machines, tests fail on `arm64`.

### SQLAlchemy Version in Use

2.0.10

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.10

### Operating system

OSX

### To Reproduce

```python
N/A
```

### Error

From Bazel from `arm64` machine:
```
Repository '@pip_greenlet' is not defined and referenced by '@pip_sqlalchemy//:pkg'
```

**Comment by zzzeek** [comment]
hey there -

there is no arm64 wheel at https://pypi.org/project/greenlet/#files.   We cannot enable any archs for which there isn't a wheel file available for greenlet.  that's the whole reason that byzantine list of requirements is there.

is there any reason you can't use the `sqlalchemy[asyncio]` target as [documented](https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#asyncio-install) ?

the PR submission instructions weren't followed here so closing

**Comment by zzzeek** [comment]
I see there's kind of an exotic ask here that you have a CI that is comparing "pip freeze" on different platforms.  That's an unusual req which you'd have to work around.   We may eventually remove "greenlet" as a required dependency altogether but we can't enable it for platforms that have no pre-built wheel so I am -1 on changing things here.

**Comment by CaselIT** [comment]
> there is no arm64 wheel at https://pypi.org/project/greenlet/#files. We cannot enable any archs for which there isn't a wheel file available for greenlet. that's the whole reason that byzantine list of requirements is there.

I wonder if `greenlet-2.0.2-cp311-cp311-macosx_10_9_universal2.whl` is actually installed also on arm.

@ryan-clancy does running `pip install -I greenlet` install from wheel or source (requiring compile?)

**Comment by ryan-clancy** [comment]
@zzzeek The dependency is coming in transitively from another (Airflow) so I cannot update the `sqlalchemy` dependency easily. Yeah, it's a bit of an odd case with checking pip freeze across archs, I may need to disable this test altogether in my CI.

@CaselIT I get the following when running the install, looks to install from source:
```
$ pip install -I greenlet
Collecting greenlet
  Using cached https://files.pythonhosted.org/packages/1e/1e/632e55a04d732c8184201238d911207682b119c35cecbb9a573a6c566731/greenlet-2.0.2.tar.gz (164 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: greenlet
  Building wheel for greenlet (setup.py) ... done
  Created wheel for greenlet: filename=greenlet-2.0.2-cp310-cp310-macosx_13_0_arm64.whl size=195930 sha256=c2419bceb86ce7873d018c82a5f131a877a836e39fa203b9836e0a2def25fea3
  Stored in directory: /Users/ryan/Library/Caches/pip/wheels/4c/f8/0a/a2b5385d249fe916ab527726cd91eda1d1f76c5bc66d03dacc
Successfully built greenlet
Installing collected packages: greenlet
Successfully installed greenlet-2.0.2
```

**Comment by CaselIT** [comment]
No, it does not seem to be using that wheel.
See
> Using cached https://files.pythonhosted.org/packages/1e/1e/632e55a04d732c8184201238d911207682b119c35cecbb9a573a6c566731/greenlet-2.0.2.tar.gz
and
> Building wheel for greenlet (setup.py) ... done
> Created wheel for greenlet: filename=greenlet-2.0.2-cp310-cp310-macosx_13_0_arm64.whl

so I guess we are at the starting point.

**Comment by CaselIT** [comment]
Closing it for now.

> The dependency is coming in transitively from another (Airflow) so I cannot update the sqlalchemy dependency easily. 

You can still add sqlalchemy as a direct dependency, specifying any extra requirements you need. You just need to ensure that the direct dependency is not in contrast with the ones coming form other dependencies (like sqlalchemy>2 if airflow has sqlalchemy<2)
