### ISSUE TITLE
async connection/session should have a "aclose" method that calls "close"

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9698]
### Discussed in https://github.com/sqlalchemy/sqlalchemy/discussions/9697

<div type='discussions-op-text'>

<sup>Originally posted by **jalvespinto** April 25, 2023</sup>
With sync I use the code bellow to delete tables:
```
 with contextlib.closing(pg_engine.connect()) as con:
     trans = con.begin()
     for table in reversed(database.Base.metadata.sorted_tables):
         con.execute(table.delete())
     trans.commit()
```
I see that contextlib have a 'aclosing' method, but it calls the 'aclose' method from thing passed to it (asyncconnection in my case). Which async connection does not have. </div>

**Comment by BlackDereker** [comment]
I can give it a shot.

**Comment by sqla-tester** [comment]
**semen603089** has proposed a fix for this issue in the **main** branch:

**`AsyncConnection[AsyncSession].aclose` implementation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4785
