### ISSUE TITLE
Bulk insert on conflict in SQLite fails for missing columns in some rows, works on mysql

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9703]
Thanks for the really fast reply. Interestingly this is a difference between SQLite and MySQL dialects. Bulk upsert in MySQL (see discussion https://github.com/sqlalchemy/sqlalchemy/discussions/9328) works fine.  I worked up a SSCCE for this also:
```py
import sqlalchemy as db
import sqlalchemy.dialects.sqlite as sqlite
from sqlalchemy import delete, select, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = 'user'
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(30), nullable=False)
    count: Mapped[int] = mapped_column(nullable=True)


engine = db.create_engine('sqlite:///:memory:')
conn = engine.connect()

# setup step 0 - ensure the table exists
Base().metadata.create_all(bind=engine)

# setup step 1 - clean out rows with id 1..5
del_stmt = delete(User).where(User.id.in_([1, 2, 3, 4, 5]))
conn.execute(del_stmt)
conn.commit()
sel_stmt = select(User)
users = list(conn.execute(sel_stmt))
print(f'Table size after cleanout: {len(users)}')

# setup step 2 - insert 4 rows
ins_stmt = sqlite.insert(User).values(
    [
        {'id': 1, 'name': 'x', 'count': 10},
        {'id': 2, 'name': 'y', 'count': 20},
        {'id': 3, 'name': 'w'}, # no count
        {'id': 4, 'name': 'z', 'count': 40},
    ]
)
# FAILS HERE IF COUNT IS MISSING
conn.execute(ins_stmt)
conn.commit()
users = list(conn.execute(sel_stmt))
print(f'Table size after insert: {len(users)}')

# demonstrate upsert
ups_stmt = sqlite.insert(User).values(
    [
        {'id': 1, 'name': 'xx', 'count': 10},
        {'id': 2, 'name': 'yy', 'count': 20},
        {'id': 3, 'name': 'ww'}, # no count
        {'id': 5, 'name': 'new', 'count': 50},
    ]
)
ups_stmt = ups_stmt.on_conflict_do_update(
    index_elements=['id'],
    set_=dict(
        name=ups_stmt.excluded.name,
        count=ups_stmt.excluded.count))
# if you want to see the compiled result
x = ups_stmt.compile(dialect=sqlite.dialect())
print(x.string, x.construct_params())
conn.execute(ups_stmt)
conn.commit()

users = list(conn.execute(sel_stmt))
print(f'Table size after upsert: {len(users)}')
```

_Originally posted by @chrisinmtown in https://github.com/sqlalchemy/sqlalchemy/discussions/9702#discussioncomment-5733073_

Error:
```
sqlalchemy.exc.CompileError: INSERT value for column ip_time.time is explicitly rendered as a boundparameter in the VALUES clause;
a Python-side value or SQL expression is required
```

**Comment by CaselIT** [comment]
This may be tangentially related to #8321

Should probably verify if it works on PG too

**Comment by zzzeek** [comment]
well sqlite/pg should work identically.  mysql is totally different

what I will say is that this:

```py
ups_stmt = sqlite.insert(User).values(
    [
        {'id': 1, 'name': 'xx', 'count': 10},
        {'id': 2, 'name': 'yy', 'count': 20},
        {'id': 3, 'name': 'ww'}, # no count
        {'id': 5, 'name': 'new', 'count': 50},
    ]
)
```

is bad.  we document that this is undefined.   IMO i dont see a bug here if that's what is required to trigger it

**Comment by zzzeek** [comment]
i mean, to "Fix", that above should raise for all backends, ideally.  it's just too expensive to check every param dict typically

**Comment by CaselIT** [comment]
> well sqlite/pg should work identically. mysql is totally different

we don't rendered a single statement for mysql?

**Comment by zzzeek** [comment]
we do the "on conflict" thing differently.  "insertmanyvalues" isnt happening here, we just feed the params to the driver

**Comment by CaselIT** [comment]
I'm not sure why we do things differently. The fact that compile error is raised sqlite suggests what we in fact are looping over the list of passed values. That's not an error of the driver.

**Comment by zzzeek** [comment]
by "do things differently" i mean the SQL syntax of "ON CONFLICT DO UPDATE" vs. "ON DUPLICATE KEY".  we dont do anything different with the parameters.

**Comment by zzzeek** [comment]
correction to my comment above, I thought that was execute(stmt, [parameters]).  it's stmt.values(parameters).  Those have to be all the same and raises if they are not.

**Comment by zzzeek** [comment]
confirmed mysql.insert().values( one parameter dict missing a key ) fails with the same error.

**Comment by CaselIT** [comment]
then I guess there isn't much to do here

**Comment by zzzeek** [comment]
well whats the thing that "works " on mysql?  can i see a side by side comparison?

**Comment by chrisinmtown** [comment]
Yes you can have a side-by-side comparison :)  
* Mysql example of bulk upsert: https://github.com/sqlalchemy/sqlalchemy/discussions/9328
* SQLite example of bulk upsert: https://github.com/sqlalchemy/sqlalchemy/discussions/9702#discussioncomment-5733073
HTH

**Comment by zzzeek** [comment]
the SQLite example has:

```py
ups_stmt = sqlite.insert(User).values(
    [
        {'id': 1, 'name': 'xx', 'count': 10},
        {'id': 2, 'name': 'yy', 'count': 20},
        {'id': 3, 'name': 'ww'}, # no count
        {'id': 5, 'name': 'new', 'count': 50},
    ]
)
```

the mysql one has:

```py
ups_stmt = mysql.insert(User).values(
    [
        {"id": 1, "name": "xx"},
        {"id": 2, "name": "yy"},
        {"id": 3, "name": "ww"},
        {"id": 5, "name": "new"},
    ]
)
```

these look like different examples

**Comment by chrisinmtown** [comment]
Thanks for keeping me honest here. I updated the Mysql example and it has exactly the same behavior, fails at the first insert, doesn't get to the upsert:
```
sqlalchemy.exc.CompileError: INSERT value for column user.count is explicitly rendered as a boundparameter in the VALUES clause; a Python-side value or SQL expression is required
```

**Comment by chrisinmtown** [comment]
@CaselIT please close this issue, I was incorrect about stating this works in MySQL.

**Comment by CaselIT** [comment]
All right.
We still should try unifying the implementations someday
