### ISSUE TITLE
Use binary_float/double in Oracle when using the generic Float/Double.

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9704]
At the moment on oracle numeric is used in all cases, unless one specifies the binary_float/binary_double type explicitly.

This is a requirement for doing #5252

**Comment by zzzeek** [comment]
what are the specific steps proposed here?

**Comment by CaselIT** [comment]
the issues is suggesting to replace the current mapping sqltype.Float -> oracle.Float with sqltype.Float -> oracle.binary_float/oracle.binary_double.

the binary types work similarly to normal float32bit / float64bit in most programming languages, and would be the equivalent of float4 / float8 in postgresql (that are alias of float and double precision)

That said I think this is doable only if a table like this:
```py
sa.Table('t', sa.MetaData(), sa.Column('c', sa.Float))
```
cannot be created in oracle without adding `.with_valiant(...)`. (I don't have an oracle instance available at the moment).

If that's not the case then this change may be a bit too dramatic without first a deprecation phase

**Comment by zzzeek** [comment]
OK were binary float / double introduced in some version of Oracle past version 8 or they've always been there?

I can see us maybe making this switch and then proposing a with_variant() case for the old behavior (`Float().with_variant(Numeric(as_float=True), "oracle")`).   but this would be a hard switch.    in particular if it is being used on a database that was craeted with an older SQLAlchemy version where the datatype is "numeric" we might need to accommodate for this as well

**Comment by CaselIT** [comment]
> OK were binary float / double introduced in some version of Oracle past version 8 or they've always been there?

not sure, I think always been there. I quick search found them listed here in 8 https://ss64.com/ora/syntax-datatypes.html and 10 https://docs.oracle.com/cd/B13789_01/server.101/b10758/sqlqr06.htm

> Float().with_variant(Numeric(as_float=True), "oracle")

the usual `Float().with_variant(oracle.Float(as_float=True), "oracle")` would continue to work as now.


> in particular if it is being used on a database that was craeted with an older SQLAlchemy version where the datatype is "numeric" we might need to accommodate for this as well

you meant when using float without variant? So this statement works also in oracle `sa.Table('t', sa.MetaData(), sa.Column('c', sa.Float))`; I had a vague recollection that binary float was needed

**Comment by zzzeek** [comment]
i mean right now we have numerical handlers to convert either from string/decimal or float so if someone used new Float but the DB is using NUMBER then we'd get string/decimal back.  but I think all of this uses oracle outputtype handlers which look at the real oracle type at result time.  will have to see

**Comment by zzzeek** [comment]
I really dont think we can make a change like this nor should we

the `Float` datatype in a generic sense expects mostly to tell the database "store a FLOAT"

On Oracle, FLOAT is present, it clearly is not the "binary float" datatype:

https://docs.oracle.com/javadb/10.6.2.1/ref/rrefsqlj27281.html

Our own reflection logic works with this also

```
            elif coltype == "FLOAT":
                # https://docs.oracle.com/cd/B14117_01/server.101/b10758/sqlqr06.htm
                if precision == 126:
                    # The DOUBLE PRECISION datatype is a floating-point
                    # number with binary precision 126.
                    coltype = DOUBLE_PRECISION()
                elif precision == 63:
                    # The REAL datatype is a floating-point number with a
                    # binary precision of 63, or 18 decimal.
                    coltype = REAL()
                else:
                    # non standard precision
                    coltype = FLOAT(binary_precision=precision)

```

you can use with_variant if you want the "real" float type and we can just document this

```py
from __future__ import annotations

from sqlalchemy import create_engine
from sqlalchemy import Float
from sqlalchemy import func
from sqlalchemy import Identity
from sqlalchemy import select
from sqlalchemy.dialects import oracle
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import Session


class Base(DeclarativeBase):
    pass


class A(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(Identity(), primary_key=True)
    data: Mapped[float | None] = mapped_column(
        Float().with_variant(oracle.BINARY_FLOAT(), "oracle")
    )
    data_norm: Mapped[float | None] = mapped_column(Float())


e = create_engine("oracle+oracledb://scott:tiger@oracle18c/xe", echo="debug")
Base.metadata.drop_all(e)
Base.metadata.create_all(e)

s = Session(e)

s.add_all(
    [
        A(data=45.2345345, data_norm=45.2345345),
        A(data=49.2345345, data_norm=45.2345345),
        A(data=0.0056, data_norm=0.0056),
        A(data=34834.006, data_norm=34834.006),
        A(data=None, data_norm=None),
    ]
)


print(s.execute(select(A.data, A.data_norm)).all())

# expression support works

# existing float is actually a decimal
print(s.execute(select(A.data_norm).where(A.data_norm == .0056)).all())

# to match real float, need to do something like this
print(s.execute(select(A.data).where(func.abs(A.data - .0056) < .00001)).all())

```

**Comment by CaselIT** [comment]
> On Oracle, FLOAT is present, it clearly is not the "binary float" datatype:

> https://docs.oracle.com/javadb/10.6.2.1/ref/rrefsqlj27281.html

this is javadb that's not oracle. oracle float is this one: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlqr/Data-Types.html

I follow the rest. The main issue is that real, float and double precision in oracle mean something different than IEEE 754 that is what most other use of the word imply

**Comment by zzzeek** [comment]
our `Float` generic datatype should mostly want to do the most generic thing possible, so for Oracle that's FLOAT

**Comment by zzzeek** [comment]
-1 on changing what `Float` does, people expect `Float` to emit `FLOAT` on the backend database, if they want to tune for oracle they can use with_variant

**Comment by CaselIT** [comment]
Ok!
