### ISSUE TITLE
Mysql reflection doesn't escape comments correctly

### ISSUE THREAD

**Issue by TheoGoudout** [sqlalchemy/sqlalchemy#9722]
**Describe the bug**
When a column has a comment associated to it with a special character (newline, in my case), a modification is incorrectly detected where the special character (`\n`) is escaped (`\\n`).

**Expected behavior**
No modification should be detected and the migration script should not contain the alter_column instruction.

**To Reproduce**
Migrate from
```mysql
CREATE TABLE `FOO` (
  `BAR` timestamp COMMENT 'This is a comment line\nThis is another comment line'
);
```
to
```mysql
CREATE TABLE `FOO` (
  `BAR` timestamp COMMENT 'This is a comment line\nThis is another comment line',
  `NEW_BAR` timestamp
);
```

**Versions.**
 - OS: Ubuntu 22.04
 - Python: 3.7
 - Alembic: 1.10.2
 - SQLAlchemy: 2.0.8
 - Database: MariaDB/MySQL 5.7.12

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Support control char reflection in mysql mariadb** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4593
