### ISSUE TITLE
Column.default is not ColumnDefault

### ISSUE THREAD

**Issue by Dreamsorcerer** [sqlalchemy/sqlalchemy#9740]
### Describe the typing issue

It seems that Column.default appears as DefaultGenerator, rather than ColumnDefault.
A quick glance at the code suggests that it should be ColumnDefault, unless I'm misreading something.

### To Reproduce

```python
import sqlalchemy
t: sqlalchemy.Table
assert t.c["foo"].default is not None
t.c["foo"].default.arg == 5
```

### Error

```
test.py:4: error: "DefaultGenerator" has no attribute "arg"  [attr-defined]
``` 

### Versions

- SQLAlchemy: 2.0.5.post1
- Type checker: mypy 1.2

**Comment by zzzeek** [comment]
well we can argue the way this is designed is not great or stuff like that, the typing of `c.default` was first devised way back in 2006 which were very unsophisticated times overall, but DefaultGenerator is what the base type is, and it's not always ColumnDefault right now:

```py
from __future__ import annotations

from sqlalchemy import ColumnDefault
from sqlalchemy.sql.schema import DefaultGenerator
from sqlalchemy import Sequence
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
import itertools


class Base(DeclarativeBase):
    pass


counter = itertools.count()


class A(Base):
    __tablename__ = "a"

    id: Mapped[int] = mapped_column(
        default=lambda: next(counter), primary_key=True
    )
    data: Mapped[str]


class B(Base):
    __tablename__ = "b"

    id: Mapped[int] = mapped_column(Sequence("foo_seq"), primary_key=True)
    data: Mapped[str]


assert A.__table__.c.id.default is not None
assert isinstance(A.__table__.c.id.default, DefaultGenerator)
assert isinstance(A.__table__.c.id.default, ColumnDefault)


assert B.__table__.c.id.default is not None
assert isinstance(B.__table__.c.id.default, DefaultGenerator)
assert isinstance(B.__table__.c.id.default, ColumnDefault)

```

so there's not a "bug" per se but issues like "Sequence should not be the .default" or "Sequence should be ColumnDefault" are all debatable.      Basically the hierarchy is DefaultGenerator -> (Sequence, ColumnDefault)

**Comment by Dreamsorcerer** [comment]
I must have misread the code then. If it can be another type at runtime, I'll just add an isinstance() check.
