### ISSUE TITLE
Calling the pool.dispatch.checkout before calling pool._dialect.do_ping if pool._pre_ping is true

### ISSUE THREAD

**Issue by JorhsonDeng** [sqlalchemy/sqlalchemy#9743]
### Describe the bug

In pool.base._ConnectionFairy._checkout function，there will call the pool._dialect.do_ping function to ping the mysql，and then call the user's registered function pool.dispatch.checkout( fairy.connection, fairy._connection_record, fairy ).

there should be call the callback function -- pool.dispatch.checkout( fairy.connection, fairy._connection_record, fairy ) firstly, and then call the pool._dialect.do_ping(fairy.connection) function if the pool._pre_ping is true.

In this way, we can check the connection in users' application, if the connection is legal, we can ping the database again.

### SQLAlchemy Version in Use

lastest

### DBAPI (i.e. the database driver)

pysqlite etc.

### Database Vendor and Major Version

Mysql

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
@classmethod
    def _checkout(
        cls,
        pool: Pool,
        threadconns: Optional[threading.local] = None,
        fairy: Optional[_ConnectionFairy] = None,
    ) -> _ConnectionFairy:
        .......
                pool.dispatch.checkout(
                    fairy.dbapi_connection, fairy._connection_record, fairy
                )
                if pool._pre_ping:
                    if not connection_is_fresh:
                        if fairy._echo:
                            pool.logger.debug(
                                "Pool pre-ping on connection %s",
                                fairy.dbapi_connection,
                            )
                        result = pool._dialect._do_ping_w_event(
                            fairy.dbapi_connection
                        )
                        if not result:
                            if fairy._echo:
                                pool.logger.debug(
                                    "Pool pre-ping on connection %s failed, "
                                    "will invalidate pool",
                                    fairy.dbapi_connection,
                                )
                            raise exc.InvalidatePoolError()
                    elif fairy._echo:
                        pool.logger.debug(
                            "Connection %s is fresh, skipping pre-ping",
                            fairy.dbapi_connection,
                        )
       ......
```

### Error

```
# Copy the complete stack trace and error message here, including SQL log output if applicable.
```

**Comment by CaselIT** [comment]
Hi,

I think the current logic is correct, since checkout means that a connection has been retrieved from the pool. When using pre-ping, before getting a connection from the pool the pre-ping logic will need to run.

If you want manually validate the connection on checkout I think you should disable pool pre-ping

**Comment by JorhsonDeng** [comment]
Hello, 
There is a application scenario, when forking a child process from parent process.
The child maybe own the connection belonging to the parent. we can check the pid of the connection with the children pid in fairy._connection_record, to avoid using the connection belong to parent process in children process by raising a exception.

So, I think we should call the hook function like fairy._connection_record. If the connection is valid and then to call the pre_ping to check the connection can connect to the database.

In addition to the above scenario, I think it will be more reasonable to place the hook function before pre_ping function. 
Because the hook function we can check the connection legitimacy quickly, and if the connection is not legal, we won't call the pre_ping function again, it will be more effective in practical application.

**Comment by zzzeek** [comment]
> Hello, There is a application scenario, when forking a child process from parent process. The child maybe own the connection belonging to the parent.

we have a recommended approach for this which is item two at https://docs.sqlalchemy.org/en/20/core/pooling.html#using-connection-pools-with-multiprocessing-or-os-fork ; call `engine.dispose()` at the start of the fork, passing the additional `close=False` boolean that was added for exactly this use case.

In that same section, the "check the pid" recipe is also present, and as you note, it uses the "checkout" event, and that recipe actually pre-dates the existence of the "pre-ping" feature.  using the current "check the pid" recipe along with "pre-ping" will as you mention have a ping occurring in the child proc on a parent connection.     That should likely be noted in that document.

However, "check the pid" is too complicated of an approach anyway which we don't really recommend; the `engine.dispose()` up front is much easier to deal with.   "check the pid" can still be used to raise an exception that the application didn't correctly set up the engine for the fork.

> In addition to the above scenario, I think it will be more reasonable to place the hook function before pre_ping function. 

That's where this proposal is not really making sense.   We can't just **move** this hook to suddenly behave in an entirely different way, delivering a potentially stale connection to the "checkout" hook when there are potentially thousands of applications relying upon this hook receiving an already-pinged connection.

> Because the hook function we can check the connection legitimacy quickly, and if the connection is not legal, we won't call the pre_ping function again, it will be more effective in practical application.

this all sounds like you simply want a custom "do_ping" event that has the option to allow the existing "ping" to still take place.    That would be much more reasonable.     This should be worked out in [ideas](https://github.com/sqlalchemy/sqlalchemy/discussions/categories/ideas).

There's no "bug" with the current "checkout" event and this is more of a feature request that needs to be worked out first.
