### ISSUE TITLE
Extending TryCast support to duckdb and BigQuery?

### ISSUE THREAD

**Issue by NickCrews** [sqlalchemy/sqlalchemy#9752]
### Describe the use case

Thanks in advance of the help.

Currently, [sqlalchemy supports mssql's TryCast operation](https://github.com/sqlalchemy/sqlalchemy/commit/b02388643357b5243175506e9a258f1ee624c3a8). I want to also be able to use TryCast with duckdb and bigquery, in order to support [.try_cast() in ibis](https://github.com/ibis-project/ibis/issues/6009).

I've never worked with the sqlalchemy codebase, how should I go about making TryCast more generic? I assume move `TryCast` out of `lib/sqlalchemy/dialects/mssql/base.py` to somewhere more generic, but I'm not sure exactly where. 

### Databases / Backends / Drivers targeted

[duckdb has `TRY_CAST()`](https://duckdb.org/docs/sql/expressions/cast.html), and [BQ has `SAFE_CAST`](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#safe_casting). BQ is a little weird because it accepts an optional `format_string` argument like "YYYY-MM-DD" for custom parsing, and I'd guess I'd want to add this to the TryCast object, but I'm not sure if that is bad, since other backends don't use it.

### Example Use

sa.try_cast(..., dtype)

**Comment by zzzeek** [comment]
snowflake seems to support it https://docs.snowflake.com/en/sql-reference/functions/try_cast

so all that's needed here is to move the try_cast element itself to sqlalchemy.sql.elements.  , add it to appropriate elements.rst doc and changelog

**Comment by CaselIT** [comment]
The default compilation would still be to raise a compile error, tight?

**Comment by NickCrews** [comment]
Thanks for the quick reply.  When you get a chance take a look at that PR :)

**Comment by sqla-tester** [comment]
**Nick Crews** has proposed a fix for this issue in the **main** branch:

**Move try_cast() from mssql to base** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4605
