### ISSUE TITLE
Alias Tutorial has syntactic error (or out of date?)

### ISSUE THREAD

**Issue by ColinStroud** [sqlalchemy/sqlalchemy#9755]
### Describe the bug

The "Using Aliases" tutorial has a [minor, yet confusing, error](https://docs.sqlalchemy.org/en/20/tutorial/data_select.html#using-aliases). Essentially, the code snippet:
```python
...     select(user_alias_1.c.name, user_alias_2.c.name).join_from(
...         user_alias_1, user_alias_2, user_alias_1.c.id > user_alias_2.c.id
...     )
```
Should actually be (removed the .name in the initial select, I figure the astrix is optional, including for completeness):
```python
...     select(*user_alias_1.c, *user_alias_2.c).join_from(
...         user_alias_1, user_alias_2, user_alias_1.c.id > user_alias_2.c.id
...     )
```

I figure this is *very* low priority, just wanted to give a heads-up.

Happy Coding,
Colin

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/tutorial/data_select.html#using-aliases

### SQLAlchemy Version in Use

2.0.12

### DBAPI (i.e. the database driver)

mysqlclient

### Database Vendor and Major Version

mysql

### Python Version

3.11

### Operating system

Windows 10 Pro 22H2

### To Reproduce

```python
from sqlanarchy import select

user_table_1 = table()
user_table_2 = table()
user_alias_1 = user_table.alias()
user_alias_2 = user_table.alias()

select(user_alias_1.c.name, user_alias_2.c.name).join_from(
    user_alias_1, user_alias_2, user_alias_1.c.id > user_alias_2.c.id
)
```

### Error

```
# Copy the complete text of any errors received by the type checker(s).
``` 
NOTE: Errors are runtime based, as this is only a tutorial I didn't think it worthy of filing a bug report.
Traceback (most recent call last):
  File "C:\[EnvPath]\Lib\site-packages\sqlalchemy\sql\base.py", line 1624, in __getattr__
    return self._index[key][1]
           ~~~~~~~~~~~^^^^^
KeyError: 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "start.py", line 69, in main
    test = get_grouped_lineups()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\[UserDir]\...\source.py", line 143, in get_grouped_lineups
    joined = select(lu_alias.c.name,ro_alias.c.name).join_from(
                    ^^^^^^^^^^^^^^^
  File "C:\[EnvPath]\Lib\site-packages\sqlalchemy\sql\base.py", line 1626, in __getattr__
    raise AttributeError(key) from err
AttributeError: name


### Additional context

I apologise if this is in the wrong category, I didn't find one that fit perfectly (even the "New Type" category), mea culpa.

**Comment by ColinStroud** [comment]
I didn't intentionally add the requires triage tag fyi.

**Comment by zzzeek** [comment]
hi -

the code in the tutorial features table objects which have a ".name" column, so the code is correct.  That code actually runs in our test suite, and the short example you show is not the same thing, you've made empty "table()" objects there.

**Comment by ColinStroud** [comment]
Hey Mike,

I ran the code in question *as is* & experienced the attached error. Not
sure why the 'alias name column' wasn't there, just know it led to said
error & found that instead using the code I posted which worked didn't
produce said error. Any word whether my experience was reproduceable?

Colin

On Tuesday, May 9, 2023, mike bayer ***@***.***> wrote:
> hi -
>
> the code in the tutorial features table objects which have a ".name"
column, so the code is correct. That code actually runs in our test suite,
and the short example you show is not the same thing, you've made empty
"table()" objects there.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci3.googleusercontent.com/proxy/fTE9KQ1eOh_VdThEWIE_-djCT2041yDn8XVO2qzHWLdic0gyIOEg3Brg1c8cwQegjxg5h11FjrAvkajbGDi9h3yIs7gLL6QCJgQjUv2rR2ootMQxSlkCfaOmOh8qzkkD9pKf8M8TasQp2sbUed1MRKxjmoH4Ck_Y7ZO7HSj2H_n-U29ch-3rt3njlsRN3qq-jGgoMeGzn0NvmQBCwW6AQfT2ciDLciSyzGuNB0x4ethf568Vxw=s0-d-e1-ft#https://github.com/notifications/beacon/AJZJKVSSKMPYYN24DXTBSL3XFIX3LA5CNFSM6AAAAAAX267I32WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTS3ZLLBE.gif>Message
ID: ***@***.***>

**Comment by ColinStroud** [comment]
Saw you couldn't reproduce, I'll assume PEBCAC on my part. Do you think it
would be with posting the code you used which worked in-case anyone else
encounters this?

On Tuesday, May 9, 2023, mike bayer ***@***.***> wrote:
> Closed #9755 as not planned.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci6.googleusercontent.com/proxy/Kaog2nEEfv6tT_3jM_P3HbKpXW8prcJXsJC6B6gkZCq04WiuJMjN7gqzHnGFUbeeRbQe22UKYf_442Tui0fBFpGeXyr0QstxsYQmfpWurtZ33KSZvwiqSe4jUiwzLXepXIxXsPkt8DCaTaYFomB7whOgtqPPLdIk2CaXDmX4-q3dHqj50VsZEY0IdPkZFp7fYGlf3H4iU-ugWGWY1SPSq6D3UvlGpdiCtePt4Lv_qXMcDkjHXXzNQpCgkaCKgrRu6CO1zrupg67ecU6c=s0-d-e1-ft#https://github.com/notifications/beacon/AJZJKVWQNOYJUB4RHVN5ILLXFIX3TA5CNFSM6AAAAAAX267I32WGG33NNVSW45C7OR4XAZNWJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XKUY3PNVWWK3TUL5UWJTYAAAAAEJC36G6A.gif>Message
ID: ***@***.***>

**Comment by zzzeek** [comment]
> Hey Mike, I ran the code in question *as is* & experienced the attached error. 

OK so in the tutorial, each individual code example is dependent on the one before it, because the full set of each little code example put together makes one big Python script.  so you can't run a single snippet from the tutorial in isolation without any changes and expect it to work; running each example requires that the prerequisite objects and imports that were named previously be included in the script.

for the example in question, it will fail not because of the column missing but because the "user_table" object is not defined, plus it's missing imports:

```py
user_alias_1 = user_table.alias()
user_alias_2 = user_table.alias()
print(
    select(user_alias_1.c.name, user_alias_2.c.name).join_from(
        user_alias_1, user_alias_2, user_alias_1.c.id > user_alias_2.c.id
    )
)
```

output:

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 1, in <module>
    user_alias_1 = user_table.alias()
                   ^^^^^^^^^^
NameError: name 'user_table' is not defined
```

that's the error we get if the code is run *as is*.

so in the reproducing example you illustrate, you did something *different*.   you made two empty table() objects:

```
user_table_1 = table()
user_table_2 = table()
```

that's not in the tutorial at all, and then it still won't exactly work because a. the aliases refer to `user_table`, not `user_table_1` or `user_table_2`, b. the `table()` construct requires a name (separate from a "name" column), c. it's missing imports and you also used we would assume the tongue-in-cheek import name "sqlanarchy" (which is less accurate, but easier to pronounce, than "sqlneoliberal").    

I don't mean to get this pedantic but when you say you are running the code "as is", that's not really the case here and the details like "what kind of object is `user_table`" matter.

if we take your approach of using an empty `table()` construct with a name and add all working imports, then yes we get the error you're referring towards

```py
from sqlalchemy import select
from sqlalchemy import table

user_table = table('user_table')

user_alias_1 = user_table.alias()
user_alias_2 = user_table.alias()
print(
    select(user_alias_1.c.name, user_alias_2.c.name).join_from(
        user_alias_1, user_alias_2, user_alias_1.c.id > user_alias_2.c.id
    )
)
```

with the output you describe:

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/base.py", line 1624, in __getattr__
    return self._index[key][1]
           ~~~~~~~~~~~^^^^^
KeyError: 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 9, in <module>
    select(user_alias_1.c.name, user_alias_2.c.name).join_from(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/base.py", line 1626, in __getattr__
    raise AttributeError(key) from err
AttributeError: name
```

So how would we make your example work more like what's in the tutorial?   well the tutorial is referring to `user_alias_1.c.name` (and also `user_alias_1.c.id`), so that means we need to give it a columns called `id` and `name`:

```py
from sqlalchemy import column
from sqlalchemy import select
from sqlalchemy import table

user_table = table('user_table', column('id'), column('name'))

user_alias_1 = user_table.alias()
user_alias_2 = user_table.alias()
print(
    select(user_alias_1.c.name, user_alias_2.c.name).join_from(
        user_alias_1, user_alias_2, user_alias_1.c.id > user_alias_2.c.id
    )
)

```

then the program runs and we get the output:

```
SELECT user_table_1.name, user_table_2.name AS name_1 
FROM user_table AS user_table_1 JOIN user_table AS user_table_2 ON user_table_1.id > user_table_2.id
```

so when you see an attribute error referring to "name" and you see in the stack trace it's the line of code calling upon `user_alias_1.c.name`, you know that the originating `table` or `Table` needs to have a column of that name present.

**Comment by ColinStroud** [comment]
Ok, whether the code in question (built up from prev ex or not) works as is
or not. I simply wanted to bring it to your attn that when I ran sample,
the result had no name column & I found that the code I posted seemed to
get the job done. If you don't think it's important enough to take any
action, all good. If you're interested in further triage or info let me
know.

To put all speculation, etc. to bed, does it make sense to provide a
minimal ex that you found to work & I can just run it locally & see if I
experience the same issue?

Either way, many thanks for what has (otherwise, been a really excellent
library.

- Colin

On Wednesday, May 10, 2023, mike bayer ***@***.***> wrote:
> Hey Mike, I ran the code in question as is & experienced the attached
error.
>
> OK so in the tutorial, each individual code example is dependent on the
one before it, because the full set of each little code example put
together makes one big Python script. so you can't run a single snippet
from the tutorial in isolation without any changes and expect it to work;
running each example requires that the prerequisite objects and imports
that were named previously be included in the script.
>
> for the example in question, it will fail not because of the column
missing but because the "user_table" object is not defined, plus it's
missing imports:
>
> user_alias_1 = user_table.alias()
> user_alias_2 = user_table.alias()
> print(
> select(user_alias_1.c.name, user_alias_2.c.name).join_from(
> user_alias_1, user_alias_2, user_alias_1.c.id > user_alias_2.c.id
> )
> )
>
> output:
>
> Traceback (most recent call last):
> File "/home/classic/dev/sqlalchemy/test3.py", line 1, in <module>
> user_alias_1 = user_table.alias()
> ^^^^^^^^^^
> NameError: name 'user_table' is not defined
>
> that's the error we get if the code is run as is.
>
> so in the reproducing example you illustrate, you did something
different. you made two empty table() objects:
>
> user_table_1 = table()
> user_table_2 = table()
>
> that's not in the tutorial at all, and then it still won't exactly work
because a. the aliases refer to user_table, not user_table_1 or
user_table_2, b. the table() construct requires a name (separate from a
"name" column), c. it's missing imports and you also used we would assume
the tongue-in-cheek import name "sqlanarchy" (which is less accurate, but
easier to pronounce, than "sqlneoliberal").
>
> I don't mean to get this pedantic but when you say you are running the
code "as is", that's not really the case here and the details like "what
kind of object is user_table" matter.
>
> if we take your approach of using an empty table() construct with a name
and add all working imports, then yes we get the error you're referring
towards
>
> from sqlalchemy import select
> from sqlalchemy import table
>
> user_table = table('user_table')
>
> user_alias_1 = user_table.alias()
> user_alias_2 = user_table.alias()
> print(
> select(user_alias_1.c.name, user_alias_2.c.name).join_from(
> user_alias_1, user_alias_2, user_alias_1.c.id > user_alias_2.c.id
> )
> )
>
> with the output you describe:
>
> Traceback (most recent call last):
> File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/base.py", line
1624, in __getattr__
> return self._index[key][1]
> ~~~~~~~~~~~^^^^^
> KeyError: 'name'
>
> The above exception was the direct cause of the following exception:
>
> Traceback (most recent call last):
> File "/home/classic/dev/sqlalchemy/test3.py", line 9, in <module>
> select(user_alias_1.c.name, user_alias_2.c.name).join_from(
> ^^^^^^^^^^^^^^^^^^^
> File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/base.py", line
1626, in __getattr__
> raise AttributeError(key) from err
> AttributeError: name
>
> So how would we make your example work more like what's in the tutorial?
well the tutorial is referring to user_alias_1.c.name (and also
user_alias_1.c.id), so that means we need to give it a columns called id
and name:
>
> from sqlalchemy import column
> from sqlalchemy import select
> from sqlalchemy import table
>
> user_table = table('user_table', column('id'), column('name'))
>
> user_alias_1 = user_table.alias()
> user_alias_2 = user_table.alias()
> print(
> select(user_alias_1.c.name, user_alias_2.c.name).join_from(
> user_alias_1, user_alias_2, user_alias_1.c.id > user_alias_2.c.id
> )
> )
>
> then the program runs and we get the output:
>
> SELECT user_table_1.name, user_table_2.name AS name_1
> FROM user_table AS user_table_1 JOIN user_table AS user_table_2 ON
user_table_1.id > user_table_2.id
>
> so when you see an attribute error referring to "name" and you see in the
stack trace it's the line of code calling upon user_alias_1.c.name, you
know that the originating table or Table needs to have a column of that
name present.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci4.googleusercontent.com/proxy/xJiIqTaQlYDD94ozBY-icNbgQkbpVSpGgo7MLWOA4F2PsVrEjyN2vtmaFIfpXby5Mdzm7-Ur5l8c8_CXS2in6lmsiVRSwAx0s4Ve7EuMUWUJFU1jMzSgrBdZX2OcRmyWDeF8AARoNN0tF-ZoqEzzK-o_UF7jYy3NzZomhoB-Nfc1QDmp9GkqLjs9Iavff8LpWj_-9FUbxGZTrRo6mnr66ml58WMZmVTpDPh7FWDblKvXzpwQDA=s0-d-e1-ft#https://github.com/notifications/beacon/AJZJKVWFYSLSQ4DLSYAXQ6LXFOIJBA5CNFSM6AAAAAAX267I32WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTS35QEF6.gif>Message
ID: ***@***.***>

**Comment by zzzeek** [comment]
> To put all speculation, etc. to bed, does it make sense to provide a minimal ex that you found to work & I can just run it locally & see if I experience the same issue? 


I had an example up in my comment at https://github.com/sqlalchemy/sqlalchemy/issues/9755#issuecomment-1542195295 .  here it is, you can paste this into "test.py" and run it:

```py
from sqlalchemy import column
from sqlalchemy import select
from sqlalchemy import table

user_table = table('user_table', column('id'), column('name'))

user_alias_1 = user_table.alias()
user_alias_2 = user_table.alias()
print(
    select(user_alias_1.c.name, user_alias_2.c.name).join_from(
        user_alias_1, user_alias_2, user_alias_1.c.id > user_alias_2.c.id
    )
)

```
