### ISSUE TITLE
Incorrect typing of Session.get(with_for_update=True) parameter

### ISSUE THREAD

**Issue by philer-jambit** [sqlalchemy/sqlalchemy#9762]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

The `with_for_update` parameter of `Session.get` in the `sqlalchemy.orm.session` package is documented as:

> with_for_update: optional boolean ``True`` indicating FOR UPDATE should be used [...]

([line](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/orm/session.py#L3512))

yet the actual type hint is:

```py
with_for_update: Optional[ForUpdateArg] = None,
```
([line](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/orm/session.py#L3435))

Note, that the implementation appears to work. That is, passing `with_for_update=True` does not raise an error at runtime.

I assume there may be a few more methods in that class affected by the same issue.

### To Reproduce

```python
from sqlalchemy.orm import Session

session = Session(...)

session.get(..., with_for_update=True)  # type error
```

### Error

```
Argument of type "Literal[True]" cannot be assigned to parameter "with_for_update" of type "ForUpdateArg | None" in function "get"
    Type "Literal[True]" cannot be assigned to type "ForUpdateArg | None"
        "Literal[True]" is incompatible with "ForUpdateArg"
        Type cannot be assigned to type "None"
``` 

### Versions

- OS: Linux Mint 21.1
- Python: 3.11.2
- SQLAlchemy: 2.0.12
- Type checker: pyright 1.1.299

**Comment by zzzeek** [comment]
ORM get/replace are the only places that happens in that way.  it's not in Core like that
