### ISSUE TITLE
Duplicate ForeignKeyConstraint generated when using PEP-593 Annotated

### ISSUE THREAD

**Issue by spladug** [sqlalchemy/sqlalchemy#9766]
**Describe the bug**

When using `Annotated[int, mapped_column(ForeignKey("foo.id"))]` in SQLAlchemy declarative models, `alembic revision --autogenerate` produces two identical `ForeignKeyConstraint`s for the column.

**Expected behavior**

A single `ForeignKeyConstraint` is generated.

**To Reproduce**

In a fresh environment, copy down the [`Annotated` example from the SQLAlchemy docs](https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#step-five-make-use-of-pep-593-annotated-to-package-common-directives-into-types):

```py
from typing_extensions import Annotated
from typing import List
from typing import Optional
from sqlalchemy import ForeignKey
from sqlalchemy import String
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship

# declarative base from previous example
str50 = Annotated[str, 50]


class Base(DeclarativeBase):
    type_annotation_map = {
        str50: String(50),
    }


# set up mapped_column() overrides, using whole column styles that are
# expected to be used in multiple places
intpk = Annotated[int, mapped_column(primary_key=True)]
user_fk = Annotated[int, mapped_column(ForeignKey("user_account.id"))]


class User(Base):
    __tablename__ = "user_account"

    id: Mapped[intpk]
    name: Mapped[str50]
    fullname: Mapped[Optional[str]]
    addresses: Mapped[List["Address"]] = relationship(back_populates="user")


class Address(Base):
    __tablename__ = "address"

    id: Mapped[intpk]
    email_address: Mapped[str50]
    user_id: Mapped[user_fk]
    user: Mapped["User"] = relationship(back_populates="addresses")
```

Initialize an Alembic environment and wire it up to PostgreSQL and the schema. 

Then run `alembic revision --autogenerate` and inspect the output.

**Error**

```python
def upgrade_user_db() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
```

Note the second `ForeignKeyConstraint` for the `address` table.

If the declaration for the `user_id` column is changed to `user_id: Mapped[int] = mapped_column(ForeignKey("user_account.id"))` only a single `ForeignKeyConstraint` is generated.

If I manually remove the `ForeignKeyConstraint` from the migration and apply it, alembic does not try to re-add the duplicate constraint on future runs of `alembic revision --autogenerate`.

I was able to reproduce this with asyncpg, psycopg2, and sqlite.

**Versions.**
 - OS: Linux
 - Python: 3.11.3
 - Alembic: 1.10.4
 - SQLAlchemy: 2.0.12
 - Database: PostgreSQL
 - DBAPI: asyncpg 0.27 or psycopg2 2.9.6

Thanks for the awesome library and tool. The new declarative models are great. **Have a nice day!**

**Comment by zzzeek** [comment]
this is completely a SQLAlchemy thing, just a create_all() will show the duplicated FKs.    Wish this was reported an hour earlier before I put 2.0.13 out, next release might not be for a few weeks.

**Comment by zzzeek** [comment]
interestingly if you include `from __future__ import annotations` there is no issue

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**return empty MappedColumn() at early pep-593 step** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4606
