### ISSUE TITLE
[Postgresql] `ENUM` does not forward `create_type` when producing column copies for `declarative_base`

### ISSUE THREAD

**Issue by ohaibbq** [sqlalchemy/sqlalchemy#9773]
### Describe the bug

This causes `CreateEnumType` elements to be emitted when creating tables, even though they should not. I believe the fix is as simple as forwarding the `kwarg` from `impl` here: https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4_48/lib/sqlalchemy/dialects/postgresql/base.py#L2077-L2090

### SQLAlchemy Version in Use

1.4.25

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PostgreSQL 12

### Python Version

3.9

### Operating system

OSX

### To Reproduce

```python
import enum

from sqlalchemy import Column
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Period(enum.Enum):
    MONTH = "MONTH"
    QUARTER = "QUARTER"
    YEAR = "YEAR"


class ModelBase:
    period = Column(
        ENUM(Period, create_type=False),
        primary_key=True,
        nullable=False,
    )


class TestModel(ModelBase, Base):
    __tablename__ = "test_model"


print(
    ModelBase.period.type.create_type,
    TestModel.__table__.columns['period'].type.create_type
) # => False True
```

### Error

n/a

**Comment by ohaibbq** [comment]
We also run into this when producing copies of tables via `Table.to_metadata()`. I've verified that this diff does fix the issue. I will put together a pull request once this issue has been triaged.

```diff
diff --git a/lib/sqlalchemy/dialects/postgresql/named_types.py b/lib/sqlalchemy/dialects/postgresql/named_types.py
index 92aba6f63..2a2ab95ca 100644
--- a/lib/sqlalchemy/dialects/postgresql/named_types.py
+++ b/lib/sqlalchemy/dialects/postgresql/named_types.py
@@ -311,6 +311,7 @@ class ENUM(NamedType, sqltypes.NativeForEmulated, sqltypes.Enum):
         kw.setdefault("_create_events", False)
         kw.setdefault("values_callable", impl.values_callable)
         kw.setdefault("omit_aliases", impl._omit_aliases)
+        kw.setdefault("create_type", impl.create_type)
         kw.setdefault("_adapted_from", impl)
         return cls(**kw)
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**include create_type in pg.ENUM.adapt; test all attrs** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4612

**Comment by zzzeek** [comment]
that's OK re: the PR, this needed test coverage for this codepath.

I guess you are looking for a backport.   We dont have a lot of 1.4.x releases coming out

**Comment by ohaibbq** [comment]
Thank you! A backport would be nice, but we figured that it wouldn't make it to a release anytime soon, so we've opted not to use Postgresql enums where we're running into the issue.
