### ISSUE TITLE
write-only mapping example seems to have a formatting / zeeksphinx problem

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#9810]
at https://docs.sqlalchemy.org/en/20/orm/large_collections.html#write-only-relationships

the highlighting is not working in the classes, and the annotation detection is failing.  need to determine if this is a source issue, zeeksphinx issue, or pygments / sphinx issue.

**Comment by CaselIT** [comment]
Maybe it does not like a fragment this long with `>>>`?

**Comment by zzzeek** [comment]
like `if num_of_lines_after_arrows > 10: forget_it()` ?  :)

**Comment by zzzeek** [comment]
very similar example at https://docs.sqlalchemy.org/en/20/orm/quickstart.html, that highlights fine, it has blank lines in it, f strings , all the same elements

**Comment by CaselIT** [comment]
> like `if num_of_lines_after_arrows > 10: forget_it()` ? :)

seems like something I could have coded 💯

**Comment by zzzeek** [comment]
so it's the highlighter in use, though it seems like pycon+sql should support class definitions...
