### ISSUE TITLE
It would be more convenient to support @ in password by optimize the reg

### ISSUE THREAD

**Issue by lijiaweinpc** [sqlalchemy/sqlalchemy#9811]
### Describe the use case

Though we can url quote to get rid of all the special char in password. It would be more convenient to support @ in password by optimize the reg. Since @ is very common used as the only special char in password.

### Databases / Backends / Drivers targeted

all database

### Example Use

as is:
engine = create_engine(f"mysql+pymysql://myuser:{urlquote(mysql_password_with_@)}@127.0.0.1:3306/dbtest")
to be:
engine = create_engine(f"mysql+pymysql://myuser:mysql_password_with_@@127.0.0.1:3306/dbtest")

**Comment by CaselIT** [comment]
Hi,

@ is used to separate the password from the host. The current behaviour is the correct one.
You can follow the rationale by looking at the label https://github.com/sqlalchemy/sqlalchemy/labels/%40%20%28or%20other%20chars%29%20in%20password
