### ISSUE TITLE
Access to asyncpg error for IntegrityError

### ISSUE THREAD

**Issue by amacfie-tc** [sqlalchemy/sqlalchemy#9843]
### Describe the use case

As mentioned in [this discussion](https://github.com/sqlalchemy/sqlalchemy/discussions/6199#discussioncomment-2006533), when we catch `sqlalchemy.exc.IntegrityError` with asyncpg, we may not have convenient access to the underlying asyncpg error. 

### Databases / Backends / Drivers targeted

asyncpg

### Example Use

```python
try:
    # <execute statement>
except IntegrityError as ie:
    ...
```
E.g. currently for a check constraint violation, `repr(ie.orig)` is
```
IntegrityError("<class 'asyncpg.exceptions.CheckViolationError'>: ...\nDETAIL:  ...")
```
and `vars(ie.orig)` is simply `{'pgcode': '23514', 'sqlstate': '23514'}`.

We would either want access to the actual `asyncpg.exceptions.CheckViolationError` object or we would want more of that object's fields copied into `ie.orig`. [This](https://github.com/MagicStack/asyncpg/blob/bf74e88bb5193b39cf942a6f0e9b838da3d0214a/asyncpg/exceptions/_base.py#L27) appears to be a list of available fields (detail, table_name, etc.) although they may not all exist on every object, see [here](https://github.com/sqlalchemy/sqlalchemy/discussions/6199#discussioncomment-571398).

Currently the [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions/6199#discussioncomment-2006533) mentions a workaround involving `ie.orig.__cause__`.

**Comment by amacfie-tc** [comment]
Possible duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/8047

**Comment by zzzeek** [comment]
yes this is exactly #8047, it's a dupe.  anyone can work on this
