### ISSUE TITLE
MappedAsDataclass Optional generates non-Optional typing annotations

### ISSUE THREAD

**Issue by BranislavBajuzik** [sqlalchemy/sqlalchemy#9855]
### Ensure stubs packages are not installed

- [X] No sqlalchemy stub packages is installed (both `sqlalchemy-stubs` and `sqlalchemy2-stubs` are not compatible with v2)

### Verify if the api is typed

- [X] The api is not in a module listed in [#6810](https://github.com/sqlalchemy/sqlalchemy/issues/6810) so it should pass type checking

### Describe the typing issue

When having `MappedAsDataclass` in the class hierarchy, Mypy reports `Optional` attributes as not `Optional`.

The generated DDL is correct, without the `NOT NULL` part

### To Reproduce

```python
from sqlalchemy.orm import MappedAsDataclass, DeclarativeBase, Mapped


class Test(MappedAsDataclass, DeclarativeBase):
    __tablename__ = "test"
    test_str_attribute: Mapped[str | None]


Test(test_str_attribute=None)
```

### Error

```
error: Argument "test_str_attribute" to "Test" has incompatible type "None"; expected "Union[SQLCoreOperations[Optional[str]], str]"  [arg-type]
``` 

### Versions

- OS: Kubuntu 22.04
- Python: 3.10.6
- SQLAlchemy: 2.0.15
- Type checker: mypy 1.3.0 (compiled: yes) 

### Additional context

This seems oddly similar to #9567, but the referenced mypy issue, https://github.com/python/mypy/issues/13856, is marked as resolved in 1.2 (also in [docs](https://docs.sqlalchemy.org/en/20/orm/dataclasses.html#declarative-dataclass-mapping))

Thank you

**Comment by CaselIT** [comment]
Hi,

That's expected. If you try to run the above code it errors with:
> `sqlalchemy.exc.InvalidRequestError: Cannot use 'DeclarativeBase' directly as a declarative base class. Create a Base by creating a subclass of it.`

Follow what the error suggests and it should work

**Comment by BranislavBajuzik** [comment]
I apologize for making the example unrunnable while trying to make a minimal example. I do not have much experience with SQLAlchemy, I am actually using it for the first time (I got excited about the typing :sweat_smile: )

I did subclass the `DeclarativeBase` and I still get this error:
![image](https://github.com/sqlalchemy/sqlalchemy/assets/17835743/6a4681c3-f37f-4536-a23c-a98239722e68)


As you can see, the database is created successfully, and the data is inserted, but Mypy is not happy. If I remove the `MappedAsDataclass`, the error is gone:
![image](https://github.com/sqlalchemy/sqlalchemy/assets/17835743/0d43285b-b3ec-4f26-b21a-32aa4380e817)


Thank you

**Comment by CaselIT** [comment]
This is a bug of MyPy. pyright or pylance type check the code correctly. cc @zzzeek 
Example:
```py
from typing import Any, Generic, TypeVar, dataclass_transform, reveal_type

T = TypeVar("T")

class Desc(Generic[T]):
    def __set__(self, instance: Any, value: "Desc[T]| T") -> None:
        ...

@dataclass_transform(field_specifiers=(Desc,))
class DescMeta(type):
    pass

class DescBase(metaclass=DescMeta):
    pass

class Foo(DescBase):
    bar: Desc[int | None]

reveal_type(Foo.__init__)
Foo(bar=None)
```
This prints in mypy
```
test1.py:19: note: Revealed type is "def (self: test1.Foo, bar: Union[test1.Desc[Union[builtins.int, None]], builtins.int])"
test1.py:20: error: Argument "bar" to "Foo" has incompatible type "None"; expected "Union[Desc[Optional[int]], int]"
  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```
while pyright correctly says
```
test1.py:19:13 - information: Type of "Foo.__init__" is "(self: Foo, bar: Desc[int | None] | int | None) -> None"
```

**Comment by CaselIT** [comment]
@zzzeek I don't remember if you already reported this one to mypy

**Comment by zzzeek** [comment]
yes it's https://github.com/python/mypy/issues/15020

**Comment by zzzeek** [comment]
so if that's the issue, then dupe of #9617
