### ISSUE TITLE
Propose new known function: `string_agg`

### ISSUE THREAD

**Issue by yajo** [sqlalchemy/sqlalchemy#9873]
### Describe the use case

Having the collection of [known functions](https://docs.sqlalchemy.org/en/20/core/functions.html#selected-known-functions) is very helpful to abstract away from the underlying DB engine.

I'm currently missing the aggregated concat function in that list. Otherwise, we need to deal with engine differences manually.

### Databases / Backends / Drivers targeted

I'm currently using sqlite, psycopg2 and mssql+pyodbc.

### Example Use

Example query in SQLite (from [here](https://stackoverflow.com/a/3515329/1468388))

```sql
SELECT GROUP_CONCAT(animal) FROM animals;

-- dog,cat,rat,mice,mouse
```

Same example in PostgreSQL and MSSQL:

```sql
SELECT STRING_AGG(animal, ',') FROM animals;
```

### Additional context

I'm not using it currently, but [mysql is also different](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_group-concat):

```sql
SELECT GROUP_CONCAT(animal SEPARATOR ',') FROM animals;
```

**Comment by CaselIT** [comment]
Hi,

Sure, I guess it makes sense. Not sure about the name though, since `string_agg` is very pg specific

**Comment by CaselIT** [comment]
There is also in mssql, called string_agg https://learn.microsoft.com/en-gb/sql/t-sql/functions/string-agg-transact-sql?view=sql-server-2017

**Comment by yajo** [comment]
There's already [`array_agg`](https://docs.sqlalchemy.org/en/20/core/functions.html#sqlalchemy.sql.functions.array_agg) so I proposed it because it seems consistent. Maybe `concat_agg`?

**Comment by CaselIT** [comment]
since we have two example of string_agg and two of group_concat, I would go for string_agg, since it's the clearest one (we are aggregating things into string)

**Comment by sqla-tester** [comment]
**Joshua Morris** has proposed a fix for this issue in the **main** branch:

**Add support for SQL string aggregation function aggregate_strings.** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4781
