### ISSUE TITLE
Prefer JSONB over JSON data type for Postgres DB

### ISSUE THREAD

**Issue by AlexanderPodorov** [sqlalchemy/sqlalchemy#9875]
### Describe the use case

Currently in order to use `JSONB` data type, we have to import it from postgres dialect:
```python
from sqlalchemy.dialects.postgresql import JSONB
```
However it would be nicer if we could map it directly from `sqlalchemy.JSON`, so that if DDL is created against postgres backend, `JSONB` type is used instead of `JSON`. Postgres docs states that `JSONB` should be preferable type in almost every use case

### Databases / Backends / Drivers targeted

Postgres

### Example Use

```python
from sqlalchemy import JSON

# use it in the ORM mapping, and JSONB type is used under the hood

```

### Additional context

We could add some parameter to `sqlalchemy.JSON`, like bool `is_better`, so that:
```python
sqlalchemy.JSON(is_better=False)  # maps to sqlalchemy.dialects.postgresql.JSON
sqlalchemy.JSON(is_better=True)  # maps to sqlalchemy.dialects.postgresql.JSONB
```
Pretty much the same way as it is done for `sqlalchemy.DateTime`, where `timezone` parameter is used to determine whether the timestamp should be aware or naive

**Comment by zzzeek** [comment]
also note that JSONB features more operators than JSON.  These operators cannot be available on the base JSON datatype since they have no analogue on other backends.

**Comment by AlexanderPodorov** [comment]
Hi, thank you, that all makes sense, just wanted to double check. Have a nice day!
