### ISSUE TITLE
inconsistent behavior of default and default_factory for mapped_column

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9879]
Take a look at this MRE, see comments to `print`s
`sqlalchemy==2.0.15`

```python
from uuid import UUID, uuid4

from sqlalchemy.orm import DeclarativeBase, Mapped, MappedAsDataclass, mapped_column


class Base(DeclarativeBase, MappedAsDataclass):
    pass


class Test(Base):
    __tablename__ = 'test'

    id: Mapped[UUID] = mapped_column(primary_key=True)
    flag_df: Mapped[bool] = mapped_column(default_factory=lambda: True, init=False)
    flag_d: Mapped[bool] = mapped_column(default=True, init=False)


test = Test(id=uuid4())

print(f'flag from default factory = {test.flag_df}')  # shows True. Behavior is OK
print(f'flag from default = {test.flag_d}')  # shows None. Most likely it is a bug
```

_Originally posted by @AlexanderPodorov in https://github.com/sqlalchemy/sqlalchemy/discussions/9877_

**Comment by CaselIT** [comment]
This is the cause: https://github.com/sqlalchemy/sqlalchemy/discussions/9877#discussioncomment-6066075

And here is the proposed solution: https://github.com/sqlalchemy/sqlalchemy/discussions/9877#discussioncomment-6066971

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Support dataclass default with init=False** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4721

**Comment by sqla-tester** [comment]
**Federico Caselli** referenced this issue:

**Document limitation in dataclass mapping styles** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4999

**Comment by sqla-tester** [comment]
**Federico Caselli** referenced this issue:

**Document limitation in dataclass mapping styles** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5000
