### ISSUE TITLE
Variant type cannot be copied (RecursionError: maximum recursion depth exceeded)

### ISSUE THREAD

**Issue by espdev** [sqlalchemy/sqlalchemy#9922]
### Describe the bug

When we try to copy any Variant type, we get an error: `RecursionError: maximum recursion depth exceeded`

### SQLAlchemy Version in Use

1.4.41

### DBAPI (i.e. the database driver)

does not depend on the driver

### Database Vendor and Major Version

does not depend on the database

### Python Version

3.10

### Operating system

Cross platform

### To Reproduce

```python
import copy

from sqlalchemy import JSON
from sqlalchemy.dialects.postgresql import JSONB

JsonVariant = JSONB().with_variant(JSON, "sqlite")

copy.copy(JsonVariant)  # <-- RecursionError: maximum recursion depth exceeded
# copy.deepcopy(JsonVariant)  # the same error
```

### Error

```
Traceback (most recent call last):
  File "scratch_51.py", line 17, in <module>
    copy(JsonVariant)
  File "/usr/lib/python3.10/copy.py", line 102, in copy
    return _reconstruct(x, None, *rv)
  File "/usr/lib/python3.10/copy.py", line 272, in _reconstruct
    if hasattr(y, '__setstate__'):
  File "python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1486, in __getattr__
    return getattr(self.impl, key)
  File "python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1486, in __getattr__
    return getattr(self.impl, key)
  File "python3.10/site-packages/sqlalchemy/sql/type_api.py", line 1486, in __getattr__
    return getattr(self.impl, key)
  [Previous line repeated 993 more times]
RecursionError: maximum recursion depth exceeded
``` 

### Additional context

The issue affects SQLModel library when we use the model inheritance: 
https://github.com/tiangolo/sqlmodel/issues/276

Here is a minimal example to reproduce:

```python
from sqlalchemy import Column, JSON
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import SQLModel, Field

JsonVariant = JSONB().with_variant(JSON, "sqlite")

class A(SQLModel):
    a: dict | None = Field(None, sa_column=Column(JsonVariant))

class B(A):
    pass
```

**Comment by zzzeek** [comment]
this is a legacy architecture which was replaced by #6980, where there is no issue.    

there's also no reason to use copy() on a `TypeEngine`.  `TypeEngine` objects are intended to be immutable so SQLModel should not be calling copy() or deepcopy() on them.   IMO this should be corrected in SQLModel (and hopefully they will also support 2.0 soon).

cc @CaselIT voting "wontfix" here

**Comment by CaselIT** [comment]
> cc @CaselIT voting "wontfix" here

Fine by me, since v2 also made copy private, so it makes sense not supporting this use case

**Comment by zzzeek** [comment]
> > cc @CaselIT voting "wontfix" here
> 
> Fine by me, since v2 also made copy private, so it makes sense not supporting this use case

howd we do that?

**Comment by zzzeek** [comment]
oh you mean column.copy().   theyre' calling copy.copy() on the type here, at least in the example above.  taht would be the `__copy__()` and `__deepcopy__()` methods

**Comment by CaselIT** [comment]
I meant that copy is not something that's supported in general by sqlalchemy. Of course column.copy is different from copy.copy
