### ISSUE TITLE
MSSQL / Mysql dialects generates wrong syntax for CAST with collate

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9932]
My repro code:

```python
tbl = sa.Table("disc_9914", sa.MetaData(), autoload_with=engine)
qry = sa.select(sa.cast(tbl.c.txt, tbl.c.txt.type).label("txt_cast"))
engine.echo = True
with engine.begin() as conn:
    results = conn.execute(qry)
```

### mssql

SELECT CAST(disc_9914.txt AS VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS) AS txt_cast
FROM disc_9914

Incorrect syntax near the keyword 'COLLATE'. (156)

### mysql

SELECT CAST(disc_9914.txt AS CHAR(50) COLLATE utf8mb4_unicode_ci) AS txt_cast
FROM disc_9914

"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COLLATE utf8mb4_unicode_ci) AS txt_cast \nFROM disc_9914' at line 1)

### oracle

SELECT CAST(disc_9914.txt AS VARCHAR(50 CHAR)) AS txt_cast

no error; collate not rendered

### postgresql

SELECT CAST(disc_9914.txt AS VARCHAR(50)) AS txt_cast 
FROM disc_9914

no error; likely to error if collate were rendered

### sqlite

SELECT CAST(disc_9914.txt AS VARCHAR(50)) AS txt_cast 
FROM disc_9914

no error; collected not rendered

_Originally posted by @gordthompson in https://github.com/sqlalchemy/sqlalchemy/discussions/9914#discussioncomment-6140861_

**Comment by zzzeek** [comment]
those other dialects are not rendering the collation at all.    do they support the COLLATE clause in the first place?

**Comment by CaselIT** [comment]
> those other dialects are not rendering the collation at all. do they support the COLLATE clause in the first place?

duh. not sure how could I miss that...

from what I can gather from pg docs they also don't support what's rendered: https://www.postgresql.org/docs/13/sql-expressions.html#SQL-SYNTAX-TYPE-CASTS

**Comment by gordthompson** [comment]
### mysql

SELECT CAST(disc_9914.txt AS CHAR(50)) COLLATE utf8mb4_unicode_ci AS txt_cast
FROM disc_9914

no error

### oracle

Sorry, but I don't know Oracle well enough to comment.

### postgresql

SELECT CAST(disc_9914.txt AS VARCHAR(50)) COLLATE "en_US" AS txt_cast
FROM disc_9914

no error

### sqlite

SELECT CAST(disc_9914.txt AS VARCHAR(50)) COLLATE NOCASE AS txt_cast
FROM disc_9914

no error

**Comment by zzzeek** [comment]
we should be able to just change the `visit_cast()` render to put the COLLATE on the outside for all backends.

**Comment by CaselIT** [comment]
that seems like the best option

regarding oracle don't mention anything about collate so it seems to behave like all the other backends https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CAST.html#GUID-5A70235E-1209-4281-8521-B94497AAEF75

**Comment by zzzeek** [comment]
were you planning to work on this?

**Comment by CaselIT** [comment]
I have not planned any work on it mike

**Comment by sqla-tester** [comment]
**Gord Thompson** has proposed a fix for this issue in the **main** branch:

**Fix SQL syntax for CAST with explicit collation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4735
