### ISSUE TITLE
relationship with primaryjoin uselist not inferred from Mapped annotation

### ISSUE THREAD

**Issue by 0e4ef622** [sqlalchemy/sqlalchemy#9937]
### Describe the bug

Specifying a `relationship()` with a primary join that uses `remote()` and `foreign()` annotations appears to cause `uselist=False` regardless of what is specified in the `Mapped` type annotation.

Adding `uselist=True` or removing the `remote()`/`foreign()` annotations cause the error to go away.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/orm/relationship_api.html#sqlalchemy.orm.relationship.params.uselist

### SQLAlchemy Version in Use

2.0.16

### DBAPI (i.e. the database driver)

psycopg2-binary

### Database Vendor and Major Version

PostgreSQL 12.15

### Python Version

3.11.3

### Operating system

Linux 6.3.7-arch1-1

### To Reproduce

```python
from __future__ import annotations
from sqlalchemy import ForeignKey, create_engine
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    MappedAsDataclass,
    Session,
    mapped_column,
    relationship,
)


class Base(DeclarativeBase):
    pass


class User(MappedAsDataclass, Base):
    __tablename__ = "user"

    id: Mapped[int] = mapped_column(primary_key=True, init=False)
    notes: Mapped[list[Note]] = relationship(
        primaryjoin="remote(Note.user_id) == foreign(User.id)",
        default_factory=list,
    )


class Note(MappedAsDataclass, Base):
    __tablename__ = "notes"
    id: Mapped[int] = mapped_column(primary_key=True, init=False)
    user_id: Mapped[int] = mapped_column(ForeignKey(User.id))
    content: Mapped[str]


engine = create_engine("postgresql://postgres:postgres@localhost:5432/postgres")

Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)


with Session(engine) as sess:
    u = User()
    sess.add(u)
```

### Error

```
Traceback (most recent call last):
  File "sqlbug.py", line 42, in <module>
    sess.add(u)
  File ".venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3318, in add
    self._save_or_update_state(state)
  File ".venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3345, in _save_or_update_state
    for o, m, st_, dct_ in mapper.cascade_iterator(
  File ".venv/lib/python3.11/site-packages/sqlalchemy/orm/mapper.py", line 3954, in cascade_iterator
    queue = deque(
            ^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/orm/relationships.py", line 1501, in cascade_iterator
    tuples = state.manager[self.key].impl.get_all_pending(state, dict_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 1407, in get_all_pending
    ret = [(instance_state(current), current)]
            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute '_sa_instance_state'
```

**Comment by zzzeek** [comment]
your foreign() annotation is on the wrong side, it's Note.user_id that contains the ForeignKey, and is also unnecessary here since you have a ForeignKey already in your table metadata.

```py
    notes: Mapped[list[Note]] = relationship(
        primaryjoin="remote(Note.user_id) == User.id",
        default_factory=list,
    )

```

closing this as it was claimed to be a bug.  open a [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions) for general usage questions.

**Comment by CaselIT** [comment]
I think you can also omit the primary join entirely, and sqlalchemy will figure it out since there is a single fk that connects the tables

**Comment by 0e4ef622** [comment]
This was simplified from a larger example that required the primary join.
