### ISSUE TITLE
Unexpected/incorrect Python type returned for INET data type when used with psycopg driver

### ISSUE THREAD

**Issue by jtbeach** [sqlalchemy/sqlalchemy#9945]
### Describe the bug

When using the INET data type with the `psycopg` driver, the returned value is not a `str` as expected and declared using `Mapped`, but is instead an `IPv4Address` or `IPv6Address` object due to the "Network Types Adaptation" described at https://www.psycopg.org/psycopg3/docs/basic/adapt.html#network-data-types-adaptation

I would expect the return type of this to be `str` to match with the declared Python type in the example below. 

I have a workaround where I define a `result_processor` on a subclass of INET that always called `str` on the result but thought I'd report since this seems like unexpected behaviour to me and does not match the declared Python types.

### SQLAlchemy Version in Use

2.0.15

### DBAPI (i.e. the database driver)

psycopg

### Database Vendor and Major Version

PostgreSQL 15

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
from uuid import UUID

from sqlalchemy.dialects.postgresql import INET
from sqlalchemy import create_engine, text, select
from sqlalchemy.orm import (
    DeclarativeBase,
    MappedAsDataclass,
    Mapped,
    mapped_column,
    Session,
)


class Base(MappedAsDataclass, DeclarativeBase):
    pass


class Test(Base, kw_only=True):
    __tablename__ = "test"

    id: Mapped[UUID] = mapped_column(
        init=False,
        default=None,
        server_default=text("gen_random_uuid()"),
        primary_key=True,
    )
    signer_ip_address: Mapped[str | None] = mapped_column(INET)


engine = create_engine("postgresql+psycopg://postgres@localhost/test")
with engine.begin() as conn:
    Base.metadata.create_all(conn)


with Session(engine, expire_on_commit=False) as write_sess, write_sess.begin():
    x = Test(signer_ip_address="127.0.0.1")
    write_sess.add(x)

with Session(engine, expire_on_commit=False) as read_sess:
    stmt = select(Test).filter_by(id=x.id)
    res = read_sess.scalars(stmt).one()
    print(repr(x.signer_ip_address))  # Prints '127.0.0.1'
    print(repr(res.signer_ip_address)) # Prints IPv4Address('127.0.0.1')
```

### Error

The type of signer_ip_address is declared as type `str | None`, but res.signer_ip_address is coming back as an IPv4Address. I believe this is due to built-in type adaptation in psycopg for network addresses (https://www.psycopg.org/psycopg3/docs/basic/adapt.html#network-data-types-adaptation), which does not happen for psycopg2.

I made the following hack to the `INET` class in the postgresql dialect and it resulted in the type coming back as a `str` which is what I expected:

```
class INET(sqltypes.TypeEngine[str]):
    __visit_name__ = "INET"

    def result_processor(self, dialect: Dialect, coltype: object) -> Optional[_ResultProcessorType[_T]]:
        return lambda x: str(x) if x is not None else None
```

**Comment by CaselIT** [comment]
Hi,

This is probably something that should be normalized.

For now you can use a type decorator that's definined in user code, without needing to change sqlalchemy internals: https://docs.sqlalchemy.org/en/20/core/custom_types.html#sqlalchemy.types.TypeDecorator

Just fyi
> The type of signer_ip_address is declared as type str | None, but res.signer_ip_address is coming back as an IPv4Address

The annotation type does not really matter. Sqlalchemy uses it only to decide the type of it's not specified in the mapped column, but it's otherwise ignored. Meaning that `some_value: Mapped[str] = mapped_column(Integer)` will return ints.

**Comment by jtbeach** [comment]
> Hi,
> 
> This is probably something that should be normalized.
> 
> For now you can use a type decorator that's definined in user code, without needing to change sqlalchemy internals: https://docs.sqlalchemy.org/en/20/core/custom_types.html#sqlalchemy.types.TypeDecorator
> 
> Just fyi

Thanks @CaselIT  -- have revised solution to one based on a TypeDecorator:

```
class CustomINET(types.TypeDecorator):
    """Custom implementation of the INET data type defined in SQLAlchemy.

    See https://github.com/sqlalchemy/sqlalchemy/issues/9945 for why this
    is necessary -- psycopg is doing some automatic type adaptation that results
    in values being of a different type (IPv4Address/IPv6Address) than
    that declared in models (str).

    Once that bug is resolved, we can remove this and go back to using the base
    INET class from the postgresql dialect.
    """

    impl = INET
    cache_ok = True

    def process_result_value(self, value, dialect) -> str | None:
        """Coerce IPv4Address and IPv6Address objects returned by psycopg to str."""
        return str(value) if value is not None else None
```

> 
> > The type of signer_ip_address is declared as type str | None, but res.signer_ip_address is coming back as an IPv4Address
> 
> The annotation type does not really matter. Sqlalchemy uses it only to decide the type of it's not specified in the mapped column, but it's otherwise ignored. Meaning that `some_value: Mapped[str] = mapped_column(Integer)` will return ints.

Yeah, I guess from a mypy / typechecking point of view it's still being type-checked as though it is a `str | None` though, so was hoping to have them line up so that things like autocomplete, static type checking, etc. are more useful/accurate.

**Comment by zzzeek** [comment]
@CaselIT immedaitely, we can have the INET type do a cast as "str" so psycopg does the thing we want.

optionally in addition, we can add "as_ipaddress=True" to inet types and provide ipaddress conversion for the other PG dialects.

**Comment by zzzeek** [comment]
I assumed it didnt and that part was working here.   a little weird we dont have INET round trips anyway

**Comment by zzzeek** [comment]
the dialects are split on this.  asyncpg also returns the network types.    I think we should default letting the DBAPI do what it will do, and a paramter "enable_network_types=False" that is accepted by psycopg and asyncpg to turn off the adaptation.

**Comment by zzzeek** [comment]
that is, this "bug" exists in 1.4 as well with asyncpg.     pg8000 is only halfway, supporting INET but not CIDR.   a mess all around

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**add option to disable INET, CIDR result set conversion** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4763

**Comment by jtbeach** [comment]
Thank you @zzzeek !
