### ISSUE TITLE
possible regression on 2.0 `load_only`

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#9953]
### Describe the bug

I am honestly not sure if this is a regression or an intended behavior change that was not easily discerned from the migration guide.

Apologies if I dumbed the example down too much.  I tried to make it so the same code passes on 1.4.x and fails on 2.x, to better mimic a migrated application.

The example shows a `declarative_base` table and uses the legacy `session.query()` API.

`load_only()` is invoked on a column name as `load_only("status")`

In 1.4, SqlAlchemy is able to determine we want the `Foo.status` column based on the string.

In 2.x, SqlAlchemy does not like the string, and requires a `Foo.status` column object.

### SQLAlchemy Version in Use

2.0.16

### DBAPI (i.e. the database driver)

NA

### Database Vendor and Major Version

NA

### Python Version

3.10

### Operating system

OSX

### To Reproduce

```python
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import Unicode
from sqlalchemy.orm import load_only
from sqlalchemy.orm import Session


try:
    # SQLAlchemy 2.0
    from sqlalchemy.orm import declarative_base
except Exception as exc:
    # SQLAlchemy 1.4
    from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()


class FooObject(Base):
    __tablename__ = "foo_object"

    id = Column(Integer, primary_key=True)
    status = Column(Unicode, nullable=True, default=None)

engine = create_engine('sqlite://')
Base.metadata.create_all(engine)

with Session(engine) as session:
    foo = session.query(FooObject)\
        .filter(FooObject.id == 2)\
        .options(load_only("status"))\
        .first()
```

### Error

```python
Traceback (most recent call last):
  File "/Volumes/Development/webserver/os-projects-mine/_venv_mypy/lib/python3.10/site-packages/sqlalchemy/orm/strategy_options.py", line 2269, in _parse_attr_argument
    insp: InspectionAttr = inspect(attr)  # type: ignore
  File "/Volumes/Development/webserver/os-projects-mine/_venv_mypy/lib/python3.10/site-packages/sqlalchemy/inspection.py", line 118, in inspect
    raise exc.NoInspectionAvailable(
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'str'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jvanasco/Desktop/examply.py", line 32, in <module>
    .options(load_only("status"))\
  File "/Volumes/Development/webserver/os-projects-mine/_venv_mypy/lib/python3.10/site-packages/sqlalchemy/orm/strategy_options.py", line 2322, in load_only
    _, lead_element, _ = _parse_attr_argument(attrs[0])
  File "/Volumes/Development/webserver/os-projects-mine/_venv_mypy/lib/python3.10/site-packages/sqlalchemy/orm/strategy_options.py", line 2271, in _parse_attr_argument
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: expected ORM mapped attribute for loader strategy argument
```

**Comment by zzzeek** [comment]
that's current behavior.    all loader options require a class-bound attribute to reduce ambiguity now.

the migration notes are not really clear here since it says "relationships", it's all loader options: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#orm-query-joining-loading-on-relationships-uses-attributes-not-strings

**Comment by jvanasco** [comment]
I searched for `load_only` on the docs and issues, and found nothing.

Do you think it's worth compiling a listing of the loader options and drop them in there?

I don't seem to have any real code affected as I normally use attributes.  This just came up in a random testcase.

**Comment by zzzeek** [comment]
that changelog has to be fleshed out to refer to all loader options,not just relatoinship, and sure we can list them out there if that helps

**Comment by jvanasco** [comment]
Actually, what if we just do an error code that links to a new docs entry when the exception is raised?  That might be the easiest to implement and more informative for people who encounter this.

**Comment by zzzeek** [comment]
OK., we have a built in mechanism to add a code that links to errors.rst, this is a coercion error so might need a little extra logic in coercions.py to push an errors.rst code through but would not be hard.
