### ISSUE TITLE
Improve session state change detection

### ISSUE THREAD

**Issue by CaselIT** [sqlalchemy/sqlalchemy#9973]
When using asyncio trying to use a single session on multiple tasks at the same time it may happen that a single SessionTransaction connects multiple times to the same bind.

This eventually causes a state change error, but only on the next state change.
Reproducing example:
```py
import sqlalchemy as sa
from sqlalchemy import event
from sqlalchemy import orm
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
import asyncio

if hasattr(asyncio, 'WindowsProactorEventLoopPolicy'):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

num = 2

@event.listens_for(orm.Session, "after_transaction_create")
def afc(session, transaction):
    print("after_transaction_create", session, transaction)
@event.listens_for(orm.Session, "after_begin")
def ab(session, transaction, conn):
    print("after_begin", session, transaction, conn)

async def amain():
    e = create_async_engine("postgresql+psycopg://scott:tiger@127.0.0.1:5432/test")
    b = asyncio.Barrier(num)

    async def go_t(session: AsyncSession):
        await b.wait()
        p = {"num": asyncio.current_task().get_name()}
        res = await session.execute(sa.text("select 1, :num"), p)).first()
        print(res)

    session = AsyncSession(e)
    # await session.connection()
    try:
        await asyncio.gather(*(go_t(session) for _ in range(num)))
        await session.close()
    finally:
        await e.dispose()

asyncio.run(amain())
```

The above logs:
```
after_transaction_create <sqlalchemy.orm.session.Session object at 0x000001BFA73D5C50> <sqlalchemy.orm.session.SessionTransaction object at 0x000001BFA73DC230>
after_begin <sqlalchemy.orm.session.Session object at 0x000001BFA73D5C50> <sqlalchemy.orm.session.SessionTransaction object at 0x000001BFA73DC230> <sqlalchemy.engine.base.Connection object at 0x000001BFA73D6910>
after_begin <sqlalchemy.orm.session.Session object at 0x000001BFA73D5C50> <sqlalchemy.orm.session.SessionTransaction object at 0x000001BFA73DC230> <sqlalchemy.engine.base.Connection object at 0x000001BFA73D7310>
(1, 'Task-3')
(1, 'Task-2')
Traceback (most recent call last):
    ...
    raise sa_exc.IllegalStateChangeError(
sqlalchemy.exc.IllegalStateChangeError: Method 'close()' can't be called here; method '_connection_for_bind()' is already in progress and this would cause an unexpected state change to <SessionTransactionState.CLOSED: 5>
```

This can be detected (probably not 100% reliably, but better than nothing) applying the following patch
```diff
diff --git a/lib/sqlalchemy/orm/session.py b/lib/sqlalchemy/orm/session.py
index dd0cfb790..492d5c337 100644
--- a/lib/sqlalchemy/orm/session.py
+++ b/lib/sqlalchemy/orm/session.py
@@ -1147,6 +1147,11 @@ class SessionTransaction(_StateChange, TransactionalContext):
                     assert False, join_transaction_mode
             else:
                 transaction = conn.begin()
+
+            if bind in self._connections:
+                raise sa_exc.IllegalStateChangeError(
+                    "Another connection already associated"
+                )
         except:
             # connection will not not be associated with this Session;
             # close it immediately so that it isn't closed under GC
```

Re-running the above script results in the following log:
```
after_transaction_create <sqlalchemy.orm.session.Session object at 0x00000242791D5C50> <sqlalchemy.orm.session.SessionTransaction object at 0x00000242791DC410>
after_begin <sqlalchemy.orm.session.Session object at 0x00000242791D5C50> <sqlalchemy.orm.session.SessionTransaction object at 0x00000242791DC410> <sqlalchemy.engine.base.Connection object at 0x00000242791D6A10>
Traceback (most recent call last):
    ...
    raise sa_exc.IllegalStateChangeError(
sqlalchemy.exc.IllegalStateChangeError: Another connection already associated
```

The sync version of the script fails in the same way, and triggers the same new illegal state change.

```py
import sqlalchemy as sa
from sqlalchemy import event
from sqlalchemy import orm
from threading import Thread, Barrier, get_ident

num = 2
b = Barrier(num)

@event.listens_for(orm.Session, "after_transaction_create")
def afc(session, transaction):
    print("after_transaction_create", session, transaction)
@event.listens_for(orm.Session, "after_begin")
def ab(session, transaction, conn):
    print("after_begin", session, transaction, conn)

e = sa.create_engine("postgresql+psycopg://scott:tiger@127.0.0.1:5432/test", echo=False)

def go_t(session: orm.Session):
    b.wait()
    res = session.execute(sa.text("select 1, :num"), {"num": get_ident()}).first()
    print(res)

def main():
    session = orm.Session(e)
    # session.connection()
    tt = [(t := Thread(target=go_t, args=(session,))) and t.start() or t for _ in range(num)]

    for t in tt:
        t.join()

    session.close()
    e.dispose()

main()
```
this logs
```
after_transaction_create <sqlalchemy.orm.session.Session object at 0x000001CDBA939F90> <sqlalchemy.orm.session.SessionTransaction object at 0x000001CDBADEBAC0>
after_begin <sqlalchemy.orm.session.Session object at 0x000001CDBA939F90> <sqlalchemy.orm.session.SessionTransaction object at 0x000001CDBADEBAC0> <sqlalchemy.engine.base.Connection object at 0x000001CDBADF5F10>
Exception in thread Thread-2 (go_t):
Traceback (most recent call last):
   ...
sqlalchemy.exc.IllegalStateChangeError: Another connection already associated
```

In some cases the threaded version may also fail the `assert self._transaction is trans` while creating a `SessionTransaction` in `_autobegin_t`, so maybe that error could also be improved.

Note that de-commenting the `session.connection()` line before starting the parallel section removes this error, but in general may lead to other issues when running orm statements.

Considerations:
- I think adding a better check make sense, both in _connection_for_bind and in _autobegin_t
  - The state change logic could probably detect the _connection_for_bind issue introducing new SessionTransactionState state(s) and splitting the function in multiple ones.
- Does it make sense detecting parallel execution on a session once it has attached to a connection? Looking a bit it seems that:
  - running multiple core statements in parallel is fine, since there is no internal session state change
  - running multiple core statements plus a single orm statement in parallel is fine, since a single internal session state change is done
  - running multiple orm statements in parallel is problematic, since parallel internal session state change happen.

  Assuming that core and orm statement can be reliably discriminated (IIRC this is not easy, since the simple check `is_core_stmt = compile_state_cls is None` will probably not work, since `select(func.count(OrmModel.id))` is an orm statement, but does not change the internal session state), detecting and preventing the above should be doable. The question is if session should

This is somewhat connected with this discussion https://github.com/sqlalchemy/sqlalchemy/discussions/5980#discussioncomment-6203772

**Comment by zzzeek** [comment]
> Considerations:
> 
>     * I think adding a better check make sense, both in _connection_for_bind and in _autobegin_t

I propose a generic reentrant-access detection decorator and just be done with it:

```diff
diff --git a/lib/sqlalchemy/orm/session.py b/lib/sqlalchemy/orm/session.py
index dd0cfb7908..6e03fe8e3b 100644
--- a/lib/sqlalchemy/orm/session.py
+++ b/lib/sqlalchemy/orm/session.py
@@ -13,6 +13,7 @@ import contextlib
 from enum import Enum
 import itertools
 import sys
+import threading
 import typing
 from typing import Any
 from typing import Callable
@@ -194,6 +195,18 @@ def _state_session(state: InstanceState[Any]) -> Optional[Session]:
     """
     return state.session
 
+_F = TypeVar("_F", bound=Callable[..., Any])
+
+def _block_reentrant_access(fn: _F) -> _F:
+    def go(sessiontrans, *arg, **kw):
+        session = sessiontrans.session
+        if not session._mutex.acquire(False):
+            raise sa_exc.InvalidRequestError("Concurrent access to Session detected.  The Session / AsyncSession objects are not threadsafe/concurrency safe.")
+        try:
+            return fn(sessiontrans, *arg, **kw)
+        finally:
+            session._mutex.release()
+    return go
 
 class _SessionClassMethods:
     """Class-level methods for :class:`.Session`, :class:`.sessionmaker`."""
@@ -1077,6 +1090,7 @@ class SessionTransaction(_StateChange, TransactionalContext):
     @_StateChange.declare_states(
         (SessionTransactionState.ACTIVE,), _StateChangeStates.NO_CHANGE
     )
+    @_block_reentrant_access
     def _connection_for_bind(
         self,
         bind: _SessionBind,
@@ -1147,6 +1161,7 @@ class SessionTransaction(_StateChange, TransactionalContext):
                     assert False, join_transaction_mode
             else:
                 transaction = conn.begin()
+
         except:
             # connection will not not be associated with this Session;
             # close it immediately so that it isn't closed under GC
@@ -1634,6 +1649,8 @@ class Session(_SessionClassMethods, EventTarget):
                 "Session() may only be set to True."
             )
 
+        self._mutex = threading.Lock()
+
         self._new = {}  # InstanceState->object, strong refs object
         self._deleted = {}  # same
         self.bind = bind
```

I may be wrong but I'm not seeing any reason this wouldn't work for async calling formats as well.


>       
>       * The state change logic could probably detect the _connection_for_bind issue introducing new SessionTransactionState state(s) and splitting the function in multiple ones.

not possible because any number of binds / connections can be present, the sessiontransaction doesnt have two states "didnt get a connection yet" and "has a connection".

> 
>     * Does it make sense detecting parallel execution on a session once it has attached to a connection? Looking a bit it seems that:


I'm not really sure why we would go through all this trouble, rather than, add extremely clear / unmissable notes to docs for:

* Connection
* AsyncConnection
* Session
* AsyncSession

which state, "the X object is a stateful object.   **It is not threadsafe nor is it safe for concurrent asyncio calls**"

then link to a newly revised / modernized version of the doc at https://docs.sqlalchemy.org/en/20/orm/session_basics.html#is-the-session-thread-safe 

Python std lib documentation is simple enough: https://docs.python.org/3/library/asyncio-sync.html#asyncio.Lock   "Implements a mutex lock for asyncio tasks. Not thread-safe." .   and they're done.

Additionally update the illegalstatechange exception to have a code that points out to errors.rst.

We already have a "detect concurrent access" system in place, the "problem" is that because it's not instantaneous, users (well, exactly one user) still comes to complain that we aren't doing it right, and their complaint was, there's not enough documentation warnings.  so we add that.   we should not be stopping to bending over backwards codewise here, we should make sure the docs are clear.  it's a documentation issue.



>       Assuming that core and orm statement can be reliably discriminated (IIRC this is not easy, since the simple check `is_core_stmt = compile_state_cls is None` will probably not work, since `select(func.count(OrmModel.id))` is an orm statement, but does not change the internal session state), detecting and preventing the above should be doable. The question is if session should

absolutely not!  :)     asyncio database drivers certainly can't be assumed to be concurrency-safe and this level of guessing for a use case that should not exist is not something we should be doing.

**Comment by CaselIT** [comment]
> I may be wrong but I'm not seeing any reason this wouldn't work for async calling formats as well.

**Comment by sqla-tester** [comment]
**Mike Bayer** referenced this issue:

**harden concurrency warnings and documentation** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4748

**Comment by zzzeek** [comment]
> > I may be wrong but I'm not seeing any reason this wouldn't work for async calling formats as well.
> 
> I'm not sure a lock is even needed. a simple boolean flag may be enough

right
 
> I was thinking more about adding a connecting state that's transitory, meaning active -> connecting -> active. But this is basically achieving the same behavior of using a flag / lock

yes, thought of that today.  maybe we can do that.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**track state change within _connection_for_bind()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4748
